### ISSUE TITLE
Special Caches wrongly shown as archived

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10004]
**Describe the bug:**
The ISS cache is shown as archived in c:geo but not at the website. Don't know if it's worth to fix it, but it's still a little strange... 

https://www.geocaching.com/geocache/GC1BE91_international-space-station

**Comment by Lineflyer** [comment]
AFAIR this was done like this on purpose after some discussion for locked caches.
Of course it would be better to have a status "locked" for it....but its a rare case.

**Comment by fm-sys** [comment]
Let's close as 'won't fix'
