### ISSUE TITLE
[Nightly] Swipe down for refresh does not work if there are no logs

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#10002]
**Describe the bug:**
Subject says all. We were on the way to an FTF, which of course had no logs yet.
But without logs, the update gesture did not work in ``Logbook``.

**To Reproduce:**
1. Get a cache without any logs so far (e. g. https://coord.info/GC77C9B)
2. Switch to ``Logbook``
3. Try to update with down gesture ...

**Actual behavior/state after performing these steps:**
Nothing happens

**Expected behavior/state after performing these steps:**
Logbook should be updated - to see if it already has been logged in the meantime.

**Version of c:geo used:**
2021.02.13-NB

**Is the problem reproducible:**
Yes

**Comment by fm-sys** [comment]
Interesting. Btw, same applies if there is nothing in the waypoints page...

**Comment by MagpieFourtyTwo** [comment]
Yep, that's true - but Waypoints don't tend to suddenly appear out of nowhere, thus I would consider this a minor glitch.  ;)

**Comment by MagpieFourtyTwo** [comment]
Just made an observation: Refresh works - *but* your swipe must start at a row with text ... thus "high" enough ...

**Comment by fm-sys** [comment]
Let's close in favor of https://github.com/cgeo/cgeo/issues/12788
