### ISSUE TITLE
Question: Offline Log Deletion on Cache Deletion ok?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10009]
I noticed that when you delete a cache from c:geo which has a not-yet-send Offline Log, then this Offline Log is deleted (without any security question).

Is this wanted behaviour or a bug?

Reproducable as follows:
* opening any cache
* Create offline Log, write some log text
* Go back (this saves the log)
* Delete the cache by tapping the "delete" trash can icon
* -> offline log is gone

**Comment by Lineflyer** [comment]
This IMHO was not the case in the past.
While the cache might be deleted the offline log was still stored and visible in the history list.

**Comment by eddiemuc** [comment]
> This IMHO was not the case in the past.
> While the cache might be deleted the offline log was still stored and visible in the history list.

Can't tell for the long past, but it is like this in released version (2021.01.16)

**Comment by eddiemuc** [comment]
Also, technically the offline log entry (and possible stored offline log images) cannot exist in db / file system without the cache itself being stored. So only thing we could do here is prevent deletion. WOuld you like to do that?

I personally would opt for a safety question "You have unsent offline log which will be deleted, do you want to proceed". But I don't know how this was maybe handled (technically) before.

**Comment by Lineflyer** [comment]
If you delete a list of caches where some of them have offline logs, those offline logs are kept.

So I guess its ok like it is now. Explicitly deleting a cache will delete also the offline log while deleting whole lists will keep their offline log.

That was probably what I remembered of how it works. I suggest not to change this.

**Comment by fm-sys** [comment]
IMHO the current behavior is at least inconsistent. I would vote for keeping the offline log, also when deleting the cache explicitly

**Comment by Lineflyer** [comment]
If we decide to change the behavior here, we should make it consistent to what happens in case of batch deletion. Keep the cache on the history list only.

**Comment by eddiemuc** [comment]
Since this all seemed pretty strange to me I investigated this further. Here are my findings
* If you "delete" a single cache inside the Cache Details, then offline log is deleted
* If you "remove" a cache from list view (either by using the "remove all" option or by selecting some and use "Remove selected"), then behaviour depends on what list are you in:
    * If you are in a special list (the "All" list, the "History" list or the "Temporary" list) then the cache including its offline log gets deleted
    * If you are in a user-created list, then **the cache is not deleted at all** (neither cache itself nor its offline log). It is just removed from the list it is currently in. If the cache is in other user-defined lists it is still shown in "all" list. If this was the only user-defined list the cache was in then it is not shown in "All" list any more (but in "history" list)

So far for the current behaviour as far as I investigated it. Should it be kept like this?

**Comment by eddiemuc** [comment]
IMHO: At least I think we should make clear what is happening to the user by changing the action wording in cache list view:
* If you are in a user-defined list, wording could be "Remove all/selected from list"
* If you are in a "special" list, wording could be "Remove all/selected from device"

**Comment by Lineflyer** [comment]
> So far for the current behaviour as far as I investigated it. Should it be kept like this?

**Comment by eddiemuc** [comment]
Ok then I close this issue

**Comment by fm-sys** [comment]
> IMHO: At least I think we should make clear what is happening to the user by changing the action wording in cache list view:
> 
>     * If you are in a user-defined list, wording could be "Remove all/selected from list"
> 
>     * If you are in a "special" list, wording could be "Remove all/selected from device"

Still this is a very valid request. As it is probably not clear to _every_ user...

**Comment by eddiemuc** [comment]
> > IMHO: At least I think we should make clear what is happening to the user by changing the action wording in cache list view:
> > ```
> > * If you are in a user-defined list, wording could be "Remove all/selected from list"
> > 
> > * If you are in a "special" list, wording could be "Remove all/selected from device"
> > ```
> 
> Still this is a very valid request. As it is probably not clear to _every_ user...

I created PR #10014 for this. If new labeling is wanted it just needs to be merged
