### ISSUE TITLE
Next beta/feature release (SAF!)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10026]
Release is done, next release should be planned :)

IMHO we should allow a long beta testing phase for the SAF migration release.
But first of all SAF implementation/migration needs to be considered complete.

Post here as soon as you think `master` ready for a beta test (and final test upfront of course).

Additionally one personal comment based on testing experience:
Currently we have a whole bunch of different changes on `master`, part of it not related to SAF. I know you are keen to enhance c:geo with new features, but IMHO we should focus on completing SAF first (+ needed bugfixes both related to SAF and unrelated) before we put even more new unrelated features on top. Please keep in mind, that we should be able to tackle regressions in reasonable time. So it might be wise to keep some PRs open until we all are satisfied with SAF implementation/migration.

**Comment by eddiemuc** [comment]
SAF progress can be tracked here:
https://github.com/cgeo/cgeo/projects/17

As soon as nothing is left in ToDo or inprogress, Implementation should be complete. (More issues might raise of course, e.g. bugs)

The major open things afaik:
* Map themes
* backup
* There is a possible bug in saf I haven't get hand of until now: listing files does not seem to work sometimes. @fm-sys currently suffers from this in backup migration

**Comment by moving-bits** [comment]
Beside the already included and the yet open SAF topics we should include the ZipRenderTheme, IMHO, which is kind of SAF-related.

On master we have added map downloading openandromap maps and the themes needed for it. Elevate is a theme consisting of several hundred files, so with regard to SAF performance we decided to not unpack the theme on "disk", but in memory only. @eddiemuc prepared the extension to Mapsforge to do so. This should be included/activated with the upcoming release as well.

In contrast to this, I vote for postponing working on a theme overhaul (#9373) to a dedicated branch and/or the release after SAF.

**Comment by eddiemuc** [comment]
I agree 100% with @moving-bits . Especially the ZipRenderTheme was created specifically with SAF in mind (although there might be other use cases as well), also the very nice Theme Downloader in master is already kind of assuming it. I will integrate this together with #9607 as described there

**Comment by Lineflyer** [comment]
> Since we are dealing with very big changes, it might make sense to roll out a new beta in slow waves, so we are able to cancel the rollout without affecting all beta users if there are urgent problems. AFAIK this is possible with Google Play...

This is possible for the production release (can be set in percentage of users) but I need to check whether this is also possible for beta releases. We do "only" have 9000 users subscribed for the beta version, so its a comparable low percentage anyway. I will check.

**Comment by Lineflyer** [comment]
Update:
According to documentation we can set a limit of users for a beta release between 1000 and all beta subscribed users (currently 10.363 users). 
So if you think its worth the limitation we can start with low amount and raise as required.

**Comment by baiti** [comment]
> Update:
> According to documentation we can set a limit of users for a beta release between 1000 and all beta subscribed users (currently 10.363 users).
> So if you think its worth the limitation we can start with low amount and raise as required.

Out of curiosity: Do we know how many users cgeo has total?

**Comment by Lineflyer** [comment]
>Out of curiosity: Do we know how many users cgeo has total?

851.870 active users according to Google Play (this IMHO only counts if the user downloaded it from Google Play, so sideloads (APK, F-Droid) might be missing here).

**Comment by baiti** [comment]
> > Out of curiosity: Do we know how many users cgeo has total?
> 
> 851.870 active users according to Google Play (this IMHO only counts if the user downloaded it from Google Play, so sideloads (APK, F-Droid) might be missing here).

Wooooow! If I had to guess, I'd probably said: 30,000 total

**Comment by eddiemuc** [comment]
Apart from #10083 and #10105 I have the feeling we are reaching some sort of "done" state for SAF

**Comment by Lineflyer** [comment]
I just closed #10083 for now. We can revisit this later if needed (e.g. to debug typical user problems without the need to send them a properties files but just tell them to activate debug logging).

For #10105 IMHO we should wait for a solution as this will likely show up during beta testing and is hard to debug on user support (the user might not be aware, that restoring caused a SAF issue and if the user does not tell he restored something, we might be unable to locate the root cause of such problem).

**Comment by Lineflyer** [comment]
Notes to myself:
1. Once we merged branches to prepare for the SAF release, I could maybe sent out a compiled RC version as "pre-beta" to some users I know (e.g. people often contacting support mail with ideas, saarfuchs, local geocachers which are c:geo power users, etc.) and ask for feedback about the migration process and functionality afterwards.

2. We could use a survey form recently discussed somewhere around here adressed to our beta users to collect some feedback about how it worked for them and whether they have improvement proposals. This could be easily limited to RC users by using our notification system to send the link on their c:geo home screen.

**Comment by Lineflyer** [comment]
Regarding 2. (from above) I made a first draft. The survey branches into different questions depending on answers. Feel free to try and propose improvements:
https://forms.gle/niAukQjJB8sxXXp99

**Comment by moving-bits** [comment]
Nice survey, thanks for preparing it!
I entered some wild answers, but the survey reacted according to it. 👍 

The only thing we might add - not sure if it's necessary - is on page 6: If you check the "The wizard process was difficult to understand / to use" we might ask the user why he/she had that impression, and what we could do to improve the user experience. - And/or we could a free text field at the end and ask the user if he/she wants to give us any extra thing to notice.

**Comment by Lineflyer** [comment]
Thanks @moving-bits 
I modified the survey a bite according your suggestions.

I also tested to post a link via our notification system to the homescreen of a certain version. It works, so I will probably try that out once we have a beta version.

**Comment by Lineflyer** [comment]
Except from the generic regressions as posted [here](https://github.com/cgeo/cgeo/issues/10026#issuecomment-784015745) it looks like the SAF thing is complete...Yeah!

The only slightly associated issue is #10126 as it seems to be an Android 11 regression.
Does someone have an idea how to fix it, or shall we postpone this is?

**Comment by fm-sys** [comment]
I think at least for a first beta we should have a very suitable base. Anything else can be fixed later on... 

Still it might be a good idea to only provide the release to maybe half of the beta users for the first few days, so that we still have a couple of not yet migrated beta users if we need to extensively change some migration parts (Which, however, is hopefully not to be expected).

**Comment by Lineflyer** [comment]
OK, then I will proceed as follows during today:
- Merge branches
- Send mail to Crowdin contributors, that release is upcoming and ask for translation (we have some languages with 95%<x<100%, where some new strings for migration still need translation)
- Generate RC version and smoke test
- Finalize the planned survey and set it active
- Push to 25% of beta users

Any objections or anything missing?
I skipped the idea of sending the RC to power users first (because they are most likely beta testers anyway...or I will ask them to).

**Comment by Lineflyer** [comment]
@mucek4 Slovenian translation needs your urgent help ;) Its down to 38% translated strings only.

**Comment by Lineflyer** [comment]
For your attention:
I a first step `release` was fast forwarded to HEAD of `master`.
I conserved the old branch `release` temporarily into `release`_preSAF` (although this is not really necessary as we could make use of git functions if we need to revert, its more for easier overview on the Github UI). I will delete this branch as soon as we are completely done.

Furthermore:
- Mail to Crowdin contributors has been sent
- Smoke testing and next steps maybe tonight

**Comment by Lineflyer** [comment]
- Smoke testing the migration process and fresh installation wizard done and OK on Android 11 (Pixel3a)
- Second smoke test will be on an Android 5 device (to be done tonight)
- If someone wants to check as well: https://download.cgeo.org/cgeo-RC.apk

**Comment by bekuno** [comment]
What is the plan for the targetSdk change?
`targetSdkVersion 29 // TODO SAF: leave at 29 until done, change to 30 when done`

**Comment by Lineflyer** [comment]
Update on smoke test with Android 5.0.2.
While trying to select the base folder the SAF dir selector crashes whenever I try to access the phones internal storage. I tested with other apps using SAF and its reproducible also there (tested with Locus).
So not our problem, but a problem os the dir selector.
For information:

```
18:48:38.094 Error AndroidRuntime 16119  FATAL EXCEPTION: main
18:48:38.094 Error AndroidRuntime 16119  Process: com.android.documentsui, PID: 16119
18:48:38.094 Error AndroidRuntime 16119  java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
18:48:38.094 Error AndroidRuntime 16119  	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
18:48:38.094 Error AndroidRuntime 16119  	at android.text.TextUtils.expandTemplate(TextUtils.java:912)
18:48:38.094 Error AndroidRuntime 16119  	at com.android.documentsui.PickFragment.setPickTarget(PickFragment.java:85)
18:48:38.094 Error AndroidRuntime 16119  	at com.android.documentsui.DocumentsActivity.onCurrentDirectoryChanged(DocumentsActivity.java:891)
18:48:38.094 Error AndroidRuntime 16119  	at com.android.documentsui.DocumentsActivity.access$400(DocumentsActivity.java:94)
18:48:38.094 Error AndroidRuntime 16119  	at com.android.documentsui.DocumentsActivity$PickRootTask.onPostExecute(DocumentsActivity.java:960)
18:48:38.094 Error AndroidRuntime 16119  	at com.android.documentsui.DocumentsActivity$PickRootTask.onPostExecute(DocumentsActivity.java:936)
18:48:38.094 Error AndroidRuntime 16119  	at android.os.AsyncTask.finish(AsyncTask.java:632)
18:48:38.094 Error AndroidRuntime 16119  	at android.os.AsyncTask.access$600(AsyncTask.java:177)
18:48:38.094 Error AndroidRuntime 16119  	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
18:48:38.094 Error AndroidRuntime 16119  	at android.os.Handler.dispatchMessage(Handler.java:102)
18:48:38.094 Error AndroidRuntime 16119  	at android.os.Looper.loop(Looper.java:135)
18:48:38.094 Error AndroidRuntime 16119  	at android.app.ActivityThread.main(ActivityThread.java:5219)
18:48:38.094 Error AndroidRuntime 16119  	at java.lang.reflect.Method.invoke(Native Method)
18:48:38.094 Error AndroidRuntime 16119  	at java.lang.reflect.Method.invoke(Method.java:372)
18:48:38.094 Error AndroidRuntime 16119  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
18:48:38.094 Error AndroidRuntime 16119  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
18:48:38.094 Warning ActivityManager 823    Force finishing activity com.android.documentsui/.DocumentsActivity
```

For completion of the smoke test I will use a dir on SD for all migrations.

**Comment by Lineflyer** [comment]
@bekuno 

> What is the plan for the targetSdk change?
targetSdkVersion 29 // TODO SAF: leave at 29 until done, change to 30 when done

That would possibly be the step for the release after the current upcoming.

**Comment by eddiemuc** [comment]
> Update on smoke test with Android 5.0.2.
While trying to select the base folder the SAF dir selector crashes whenever I try to access the phones internal storage. I tested with other apps using SAF and its reproducible also there (tested with Locus).
> So not our problem, but a problem os the dir selector.

Still feels not so good somehow...

**Comment by fm-sys** [comment]
Is SAF migration actually needed at all? I guess this is and will be only necessary starting with Android 10, am I right? If that's the case, we shouldn't show the migration wizard for older android versions (Because it annoys users and can produce malfunction and crashes)

**Comment by Lineflyer** [comment]
> Is SAF migration actually needed at all? I guess this is and will be only necessary starting with Android 10, am I right? If that's the case, we shouldn't show the migration wizard for older android versions (Because it annoys users and can produce malfunction and crashes)

I am not sure about this, but anyway I would strongly prefer a common solution and no differentiation between SDKs versions.

Lets start the beta phase anyway and see the feedback.
I will enhance the survey by adding a question regarding Android versions for the problem case.

**Comment by Lineflyer** [comment]
Well, the Google Play Store Console seems to have some problems today.
Whatever I am trying to do, sooner or later it shows me some unexpected error.

Will try later or tomorrow.

**Comment by Lineflyer** [comment]
Update:
Problem was in my browser cache...no idea.

Anyway:
- 2021.03.16-RC1 is now on the way to 10% (approx. 1000) of beta users.
- The notification to the survey is active (see https://status.cgeo.org) and the survey answers have been reset (Android version question has also been added).

Keep fingers crossed.

**Comment by moving-bits** [comment]
Thanks @Lineflyer for testing and for preparing the next beta version. I'm really looking forward to user feedback on that version!

BTW: Does that also mean that `master` is now open again for non-SAF related PR?

**Comment by fm-sys** [comment]
> I am not sure about this, but anyway I would strongly prefer a common solution and no differentiation between SDKs versions.

Understandable, but differences are better than not working in total 😉 BTW, there are many other places in the code where we check the SDK version and decide on that, what to do. And for SAF migration, this would even be an easy one-liner to check, if migration should be triggered...

**Comment by Lineflyer** [comment]
> BTW: Does that also mean that master is now open again for non-SAF related PR?

I know you are keen to continue...but maybe we wait some days to see if we developed something really stupid or if it works smooth.

**Comment by Lineflyer** [comment]
- No SAF related problems on support mail, only #10187 as a unrelated regression
- No negative feedback on survey
--> Raising from 10 to 20%

**Comment by Lineflyer** [comment]
- No critical or mass issues
- No more negative feedback on survey
--> Raising from 20% to 50%

**Comment by eddiemuc** [comment]
> - No critical or mass issues
> - No more negative feedback on survey
> --> Raising from 20% to 50%

So far I am relieved :-)

**Comment by Lineflyer** [comment]
Lets see on the weekend, because then the usage is higher. That also the reason I directly raised to 50%, so we have more users out in the field with that version.

**Comment by Lineflyer** [comment]
Due to the fix for #10211 beta version 2021.03.16-RC1 has been stopped and replaced by 2021.03.20-RC which is under deployment right now.

**Comment by Lineflyer** [comment]
Beta version 2021.03.20-RC is available according to Google Play. 
Its set to 50% of beta users, not sure though if it targets the same 50% as the first RC did..

Still I issued a notification that a new RC is available. 
If the users are not the same it might be, that we now have beta users hanging on 2021.03.16-RC1 not being able to update. Lets see.

**Comment by Lineflyer** [comment]
As the real trouble cases seem to be solved, I raised to 60% to get more broad feedback.

**Comment by Lineflyer** [comment]
I have seen PRs #10237, #10239 and #10240.
I guess we shall issue a new beta version once these are reviewed and merged, before raising the percentage?
Or are those non-critical and we set 100% first to collect more problems?

**Comment by fm-sys** [comment]
I think merging the PR's first would be the way to go, so we can see which crashes are fixed or still persists...

**Comment by eddiemuc** [comment]
> I think merging the PR's first would be the way to go, so we can see which crashes are fixed or still persists... 

Agree.

Is there someone who wants to review them? I can just merge them otherwise.

**Comment by fm-sys** [comment]
> Is there someone who wants to review them? I can just merge them otherwise.

Feel free and go ahead! For such simple things like safety guards probably no discussion is to be expected ;-) 

I just don't know how merging from `release` to `master` works. Anything we need to know or should be aware of?

**Comment by Lineflyer** [comment]
> I just don't know how merging from `release` to `master` works. Anything we need to know or should be aware of? 

Just don't modify the same files on `master` as long as `release` has not been merged to it. Otherwise there might be unnecessary conflict resolution needed.

@moving-bits or myself usually merge branches if we see they are not fully merged yet.

**Comment by Lineflyer** [comment]
Will smoke test and update the RC tonight.
First merging Crowdin translations, will report back when done.

**Comment by Lineflyer** [comment]
Release 2021.03.22-RC is on its way to 60% of beta users on Google Play.
Smoke test was OK (Tested upgrade from non-SAF version and from last RC on Android 11).

**Comment by Lineflyer** [comment]
raise to 80% or even 100%, or is there something to fix first?
Support mails only show the normal noise...

**Comment by moving-bits** [comment]
Let me add catching the `SecurityException`in #10246 first...

**Comment by Lineflyer** [comment]
Merged it and translations as well. Will look into support channels tomorrow and then decide further proceeding.
Ideally: Provide new RC to 100% of beta users.

**Comment by Lineflyer** [comment]
Maybe have a look at https://github.com/cgeo/cgeo/issues/10202#issuecomment-808090254 before going the next step.

**Comment by fm-sys** [comment]
> BTW: Does that also mean that `master` is now open again for non-SAF related PR?

IMHO it's time to continue regular feature development at master branch. We have **19** (!) open PR's currently, and I'm a bit afraid that we lose the overview and break something if even more accumulates and then gets merged all at once. What do you think?

**Comment by moving-bits** [comment]
Android vitals look fine for current RC, so let's continue on `master` branch.
I'll start merging the open PR for `master`...

**Comment by Lineflyer** [comment]
Had some other things to work on at the weekend (setting up Jitsi on a NAS 8-) ) but I assume now everything needed is merged on `release`.
So I would prepare a new RC for 100% of beta testers (as probably last step before release)??

**Comment by Lineflyer** [comment]
Puh......almost 80 support mails on "Login problems"..I guess the geocaching servers had a problem this weekend?!

**Comment by moving-bits** [comment]
> Puh......almost 80 support mails on "Login problems"..I guess the geocaching servers had a problem this weekend?!

From the weekend or from the days before? There has been a scheduled downtime on March 25th, IIRC.
Otherwise can't really say - had no problems with the website this weekend, but I'd been using it only from time to time.

**Comment by bekuno** [comment]
Today. Also many messages on FB.
Have a look here: https://allestörungen.de/stoerung/geocaching/

**Comment by Lineflyer** [comment]
Indeed, seems not our problem.

I pushed 2021.03.28-RC to 100% of beta testers just now.
I will push the survey notfication as well (as soon as beta is available) for some more days.

**Comment by moving-bits** [comment]
> Puh......almost 80 support mails on "Login problems"..I guess the geocaching servers had a problem this weekend?!

You can also see this in our Play Console Androids vitals dashboard: ANR exploding over the weekend, app. 2300 occurrences in `LogCacheActivity` alone...

![image](https://user-images.githubusercontent.com/3754370/112891493-7e3a0780-90d8-11eb-8820-9194b1ffe59b.png)

**Comment by Lineflyer** [comment]
mmh..shouldn't we try to avoid ANRs due to external server problems?

**Comment by eddiemuc** [comment]
> mmh..shouldn't we try to avoid ANRs due to external server problems?

Was this caused by the Android "WebView" problem? Then I think it is ok, we can hardly prepare ourself from such basic components not working (and many other apps crashed too). 

Otherwise we should indeed investigate.

**Comment by Lineflyer** [comment]
Beta version 2021.03.28-RC is published now to 100% of beta testers since two days.
I have ended the survey link and replaced it by a more generic message:
```
Please use "Report problem" in the main menu if you notice any new problem! Thanks for using our beta versions...
```

**Comment by bekuno** [comment]
@Lineflyer PR #10346 is included in release now.

**Comment by Lineflyer** [comment]
Nice, will prepare another (hopefully last RC) now.

**Comment by Lineflyer** [comment]
2021.04.11-RC has been uploaded to Google Play. 
Usually it will be available to beta testers within 1-3 hours.

**Comment by Lineflyer** [comment]
Copy of https://github.com/cgeo/cgeo/issues/10307#issuecomment-817358661:

As just discussed in our developer meeting:

We want to disable the Multi-thread CPU usage of the Mapsforge library before releasing as we assumed, that this could be related to the increased amount of such native crashes.
Comparing current beta with the final release could then give us an idea, whether those native crashes could be caused by that mapsforge function.

**Comment by Lineflyer** [comment]
From my perspective (looking at support mail and Play Console) the current RC 2021.04.11-RC seems to work quite good, despite the issues with native crashes (#10307) which we hope to address by disabling the "Multi-Thread".

Anything else open (feel free to check Play Store crash reports) or to be done?
If not, we should IMHO release rather soon (maybe staged as well starting with 20% or something).

**Comment by Lineflyer** [comment]
Tell me something :)

**Comment by eddiemuc** [comment]
Go

**Comment by Lineflyer** [comment]
Preparing release 2021.04.15 now.

## Release checklist for staged release:

- [x] Check/Import incoming Translations from Crowdin
- [x] Check/Insert correct version name as headline in ```changelog-release.xml```
- [x] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play to xx% of users (staged release)
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Regularly check Google Play crash reports, support mail, etc. and react accordingly
- [ ] Go/NoGo decision

In case of Go:
- [ ] Increase publish percentage to 100%
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server a few hours after increasing the publish percentage
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter 

In case of NoGo:
- [ ] Stop publish on Google Play
- [ ] Insert comment to release page on Github, that the release was stopped
- [ ] Restart release process with fixed version

**Comment by Lineflyer** [comment]
2021.04.15 is deploying to 20% (approx. 160k) users.

**Comment by Lineflyer** [comment]
Looked at Google Play....a bunch of ANRs but seemingly only affecting single users (started already with 2021.04.11-RC):
![image](https://user-images.githubusercontent.com/949669/115014822-1eeb3e00-9eb3-11eb-90a2-8bf0ac8d9119.png)

Not sure, whether this is relevant or not. Those mapsforge related could be related to lazy theme loading?!

**Comment by eddiemuc** [comment]
Hard to tell what the cause is. It affects many places, so in principal it could be related to slow scoped storage performance of course, maybe for people with special-slow SAF access performance. Maybe even device/HW-related.

**Comment by Lineflyer** [comment]
No support mails or problems reported on other channels. I will raise to 50%.

**Comment by Lineflyer** [comment]
Besides some "problem report" mails without any further context (info from user about the reason he sent it) and not showing any problem, its silent on support mail and other channels.
Raising to 100%...so we might get possible problem reports before next (caching) weekend starts.

**Comment by Lineflyer** [comment]
Opened #10406 regarding the ANRs.

Release is on 100% and just being pushed also to F-Droid. Will wait a few hours and then put up the notification and close here.

Well done!

**Comment by Lineflyer** [comment]
We are done. 2021.04.15 is fully live now.

I guess this was the longest "Next release" thread ever :)

Thanks to all involved and special thanks to @eddiemuc for the whole SAF implementation ;)

**Comment by moving-bits** [comment]
I've just upgraded the device where I'm running only released versions on. Upgrade led me through the wizard, correctly pre-selecting my configured legacy folders, and after just a few steps everything was working perfectly. Yeah!

**Comment by eddiemuc** [comment]
Same for me! 
I decided to use sync option for map themes for now, let's see how it works out in real life :-)
