### ISSUE TITLE
custom cache icon can only be changed for a whole list

### ISSUE THREAD

**Issue by Sheldor2101** [cgeo/cgeo#10029]
**Describe the bug:**
Custom cache icons can only be set for a whole list, not for a single cache if the caches are traditional or mystery.

**To Reproduce:**
Try to change a single cache icon.

**Actual behavior/state after performing these steps:**
All caches of a list change. A single cache can only be changed after all icons of a list have been changed.

**Expected behavior/state after performing these steps:**
Simply change a single cache icon.

**Version of c:geo used:**
You will find the c:geo version in c:geo Menu -> About c:geo

**Is the problem reproducible:**
Yes

**Screenshots:**
-

**System information:**
--- System information ---
Device: SHIFT6m (SHIFT6m_EEA, SHIFT)
Android version: 8.0.0
Android build: SHIFT6M.SOS.1.1.G.20201126
c:geo version: 2021.02.14
Google Play services: enabled - 21.02.14 (040400-352619232)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide caches: own/found archived
Hide waypoints: original visited
HW acceleration: enabled (default state)
System language: de_DE / user-defined language: 
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (35,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (35,3 GB free) external non-removable
Geocache data: /storage/2115-1606/Android/data/cgeo.geocaching/files/GeocacheData (7,4 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (55,2 MB) on user storage
Last backup: 21. März 2019, 13:20
GPX import path: /storage/emulated/0/Download
GPX export path: /storage/emulated/0/Download
Offline maps path: /storage/2115-1606/maps
Map render theme path: 
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Additional context:**
-

**Comment by fm-sys** [comment]
You should be able to do exactly this...
- ...either via the "select mode" in cache lists
- ...or using the "advanced > set cache icon" menu

**Comment by Sheldor2101** [comment]
Just made an update: It doesn't work for traditionals and mysteries. The rest seems to work.

**Comment by bekuno** [comment]
@Sheldor2101 
I have tested it for both ways. This worked for traditionals and mysteries and other.

Please describe in detail your steps. Maybe you do it in another way?

**Comment by moving-bits** [comment]
Not sure if that's the reason in your case, but please keep in mind that the menu entry for setting a custom cache icon is only available for stored caches. So, for example, if you are coming from live map using "show as list", and the caches are not yet stored, you won't see it for individual caches.

**Comment by Sheldor2101** [comment]
OK, I am closing the case. I've just been told that he just forgot that he needed to save them. 😂
Therefore, it couldn't have worked.
