### ISSUE TITLE
use of JCenter is deprecated

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10033]
The service of JCenter, which we use as a library source, will be sunset.
 -  JCenter new package versions submission deadline through March 31st 2021
 -  repository will keep serving packages for 12 months until February 1st 2022

For details see 
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
https://developer.android.com/studio/build/jcenter-migration

**Comment by Lineflyer** [comment]
For my understanding:
Which functions, features in c:geo are using JCenter?

**Comment by bekuno** [comment]
We use it in the global build.gradle 
https://github.com/cgeo/cgeo/blob/master/build.gradle#L4
https://github.com/cgeo/cgeo/blob/master/build.gradle#L126
to reference to external sources.

I will check which one will be affected.
Then we can decide what to do.

**Comment by bekuno** [comment]
Test result:
Failed to resolve: com.asamm:locus-api-android:0.9.25
Failed to resolve: com.yqritc:recyclerview-flexibledivider:1.4.0

**Comment by bekuno** [comment]
The project of recyclerview-flexibledivider: https://github.com/yqritc/RecyclerView-FlexibleDivider seems not more maintaint.
The last version is more than 4 years old.
Used from this projest is `HorizontalDividerItemDecoration` in class cgeo.geocaching.ui.recyclerview.RecyclerViewProvider.

**Comment by bekuno** [comment]
The sub-issue for flexibledivider #10034 was fixed by #10050.

**Comment by bekuno** [comment]
The issue for locus will be fixed with #10384.
