### ISSUE TITLE
SAF: Behavior of migration wizard if folder selection is aborted

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10030]
I found time today to run another test of the SAF migration by upgrading from 2021.02.14 to todays nightly.

IMHO the wizard works really well and is understandable, but I stumbled over one scenario where I would like to get your feedback:

At some point of the different SAF folder selections aborted the selection process as I wanted to read again which folder I was asked to assign at this step. But in such case we takeover the legacy value (toast is shown) and the screen is gone (next wizard screen shown).

Two improvement proposals:
- If the selection is aborted we should IMHO return to the current step and offer something like "Skip for now" (to takeover the legacy value) or "Next" to try again to select a folder (Maybe in general its even better to name the default button "Select" instead of "Next" if it triggere the folder selection).
- Shouldn't we use different captions on the wizard pages instead of always the same "Set app permissions" so that you see already in this caption what is asked next (e.g. "Set base folder", "Set map path", "Set GPX path")? That was, what initially confused me and made me go back to doublecheck.

**Comment by moving-bits** [comment]
> If the selection is aborted we should IMHO return to the current step and offer something like "Skip for now" (to takeover the legacy value) or "Next" to try again to select a folder (Maybe in general its even better to name the default button "Select" instead of "Next" if it triggere the folder selection).

I'll need to take a look at it what's possible / how to achieve this behavior.
If you skip, the path should not be set implicitly, IMHO, but left at "undetermined", which leads to using the legacy value for now, but keeps popping up the migration wizard on next restart.

> Shouldn't we use different captions on the wizard pages instead of always the same "Set app permissions" so that you see already in this caption what is asked next (e.g. "Set base folder", "Set map path", "Set GPX path")? That was, what initially confused me and made me go back to doublecheck.

Yes, had thought of that myself a couple of times, but always something different thwarted it :-(

**Comment by moving-bits** [comment]
@eddiemuc 
I followed a cancelled folder selection (*) dialog back to `handleResultPersistableFolderSelection`, which will call the `callback` in this case. Is there any way I can detect a cancelled selection from the `PersistableFolder` that gets returned to the `callback`?
And if not, would it harm if I called the `callback` with a `null` value as marker for `selection cancelled`? (I would use this then in the installation wizard to adapt the wizard page accordingly instead of forwarding to the next wizard page).

(*) Cancelling by using the "back" button several times, as pressing "cancel" in the confirmation dialog only leads me back to the selection, but not back to the calling activity (wizard in this case).

**Comment by eddiemuc** [comment]
What about changing parameter type of fallback from `Folder` to `ImmutablePair<Folder, Boolean>` where the second Boolean indicated success or failure/cancelation of folder selection?

But I would change this then for all 4 types of selections (files and folders, persisted and non-pesisted).

**Comment by moving-bits** [comment]
Ok, that would be more explicitly communicating the state (which is a good idea probably). => I'll do it that way.

**Comment by moving-bits** [comment]
Hm, I'm kinda stuck - as soon as I start changing the parameters from `Consumer<Folder>` to `Consumer<ImmutablePair<Folder, Boolean>>` and from `Consumer<?>` to `Consumer<ImmutablePair<?, Boolean>>` it breaks sooner or later, assignments no longer being accepted although I'd changed all parameters involved. And `runningIntent` with its several variations doesn't make it easier (for me) :-(

I think I'll either need some help here or fall back to the `return null` approach for the one single place where I need it...

**Comment by eddiemuc** [comment]
Hi @moving-bits I think I can look at this at the weekend.

My proposal: go with the null approach for now (so you can continue your work), and I change this to ImmutablePair solution later. Would that be ok?

**Comment by moving-bits** [comment]
Thanks, @eddiemuc 👍 
I think I found an even simpler solution meanwhile: Since I need this only in the wizard and only in migration mode, it should work that I check my own `isMigrationNeededFor...` methods (see wizard) in the callback, no changes in `ContentStorageActivityHelper` needed.
