### ISSUE TITLE
Non-SDK API warning on Google Play

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10037]
I checked the "Google Play Pre-Launch Reports" which are run for beta version and while its usually reporting quite minor usability issues for all versions, I do see a major difference to old versions compared to the last beta (which is more or less equal to the current release 2021.0214).

I do however not understand the background or details..maybe someone with access can check:
https://play.google.com/console/u/0/developers/7945466068179931672/app/4975240647192321833/pre-launch-report/overview

**Comment by Lineflyer** [comment]
Just found this additional information shown in the report:

Das Problem könnte mit der von Google bereitgestellten Bibliothek AndroidX zusammenhängen. Das Problem ist uns bekannt und wir arbeiten bereits an einer Lösung. Für dich besteht im Moment kein Handlungsbedarf.

So maybe this is a false finding.

**Comment by eddiemuc** [comment]
Maybe unrelated: I can't access the google play console link directly, Google prompts me to create a developer account for 25$. Should I do this, will this even help me accessing the cgeo console and would there be an alternative way?

**Comment by SammysHP** [comment]
No, you don't have to pay. Only core/admin members have access to our developer console AFAIK.

**Comment by Lineflyer** [comment]
I have no objection to provide read access to the Play Console for @eddiemuc 
It might even be useful to have someone read crash reports and other warnings, who understands them and is also able to tackle them by hisself. AFAIR @moving-bits also has such read access.

What do you think @mucek4 ?

**Comment by mucek4** [comment]
Go for it

**Comment by Lineflyer** [comment]
@mucek4 You have to enable access for @eddiemuc 
@eddiemuc You have to provide your Google-Account (gmail address) to @mucek4

**Comment by eddiemuc** [comment]
@mucek4 , @Lineflyer I sent it to cgeo-dev@googlegroups.com (two emails since I misspelled it the first time...)

**Comment by Lineflyer** [comment]
This original probelm does not show up anymore on the Google Play Console, therefore closing as it then probably was a false warning by Google.
