### ISSUE TITLE
Cleaning of deleted caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10039]
**Is your feature request related to a problem?**
in the event, that users have import a GPX which contains waypoints unrelated to geocache waypoints (e.g. random POIs, adventure lab locations) and afterwards delete those import again, they are wondering, that the icons keep being shown on the live map.

Reason for this is, the internal 72h "buffering" in case of accidental deletion, which when using the live map is not disturbing for real geocaches (as they will be loaded via map anyway) but is disturbing/not understandable to users for other "non-geocache-related" icons.

**Describe the solution you'd like**
For UDC we already implemented to clear unstored UDC on next restart AFAIK. This is possible, as those are a clearly defined type. Such solution seems not applicable to random imported geopoints and maybe also not desireable.

But we could IMHO however include a generic deletion of all unstored "only 72h buffered" geocaches when manually triggering the "delete ophaned files" function and thus transform it into "Clear buffered/orphaned information".

**Describe alternatives you've considered**
The only thing I can currently reply to users is to wait 72h to get the mess cleaned up.

**Additional context**
Related to #4357

**Comment by fm-sys** [comment]
> But we could IMHO however include a generic deletion of all unstored "only 72h buffered" geocaches when manually triggering the "delete ophaned files" function and thus transform it into "Clear buffered/orphaned information".

IMHO we shouldn't do this that way. There were reasons, why the buffering was implemented. Rather we should do it in the same way for `UNKNOWN CONNECTOR` as we already have done it for UDC's

**Comment by okainov** [comment]
To be honest, I'm very annoyed by presence of deleted caches. I did delete them now, I don't want to see them now, why do you need multiple days to clean it up? Or maybe this should be some extra setting to allow users to have normal removal...

**Comment by Lineflyer** [comment]
As more and more users imported adventure labs this "problem" is more often asked on support mail. People are not always happy with the 72 hours limit.

Maybe the proposal of @fm-sys is a good compromise.

**Comment by Lineflyer** [comment]
I recently had a user on support mail, who handles all his caching activities with GPX files based on GSAK. He also ran into the problem, that he deleted an imported GPX and imported a changed/new GPX. 
Now he has the buffered deleted GPX data as well as his new GPX data visible on the map. We would like to see the ability to "clear this buffer". At the moment he always factory resets c:geo to start clean and not having to wait 72 hours.

So its not only about the "unknown connector" but more general about (on demand) explicitly deleting whats not stored in lists.

**Comment by moving-bits** [comment]
> So its not only about the "unknown connector" but more general about (on demand) explicitly deleting whats not stored in lists.

Or the other way around: Mark caches within a list and choose "Immediately delete all/selected caches" (or something like that) to explicitly delete those caches without buffering. Then the user can easily choose which ones to delete.

**Comment by Lineflyer** [comment]
> Or the other way around: Mark caches within a list and choose "Immediately delete all/selected caches" (or something like that) to explicitly delete those caches without buffering. Then the user can easily choose which ones to delete.

Theoretically also possible but will pollute the menu with another entry only rarely needed.

**Comment by geocachermgo** [comment]
Another use case: A log was deleted by the owner. It not possible to log another found log since "found" is removed as an option for a found cache. By really deleting and reload it should be possible again.

**Comment by Lineflyer** [comment]
@geocachermgo It should be possible now as the "72hour buffer" can now also deleted with the "Delete orphaned files" function. See commit cited above.
