### ISSUE TITLE
Map rotation

### ISSUE THREAD

**Issue by Taneller** [cgeo/cgeo#1006]
Hello,

fist of all I will thank you for the great program.

When I go caching I miss always one thing: I still use the map for navigation. It would be easier to read the map to be connected  with the compass so that the map is rotated to the direction I have to go.

Greetings,
Taneller

**Comment by birdy1966** [comment]
c:geo is the greatest programm for Geocaching ! and I use this every day since about 3 years and 2000 Caches.
I never want to miss it.

This feature works perfekt in the App: "CacheSense"....but I do not want to use CacheSense :-(
