### ISSUE TITLE
Unresponsive/Slow app when buffering themes on SD

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10075]
After we do now have the "theme sync" I have to say, that c:geo is no longer nice to use on my Galaxy S20.
I currently have no clear idea why it is so slow compared to the old implementation.

I have stored the additional geocachedata on my SD, but first of all the SD should not be relevantly slower than the internal memory and additionally its no difference to before (I had the themes on SD also with the legacy implementation).

Have a look on the linked video: https://files.droescher.eu/public/Unresponsive_1.mp4

What I did:
- 2021.02.26-NB
- Migration was completed already
- Start c:geo
- Wait for ages until sync check complete
- Start live map, takes some seconds to start and some more seconds to show the map
- Tried to change between themes with same delay and unresponsiveness

I have to admit, that I have quite some files stored in my _themes directory. But I think there is some more generic problem here, as I would have expected it to be much faster in general.

I will do another test tonight or tomorrow using only 2-4 themes to have results for an average user.

**Comment by Lineflyer** [comment]
```
--- System information ---
c:geo version: 2021.02.26-NB-a5a3de5

Device:
-------
- Device type: SM-G980F (x1seea, samsung)
- Android version: 11
- Android build: RP1A.200720.012.G980FXXU6DUB5
- Sailfish OS detected: false
- Google Play services: enabled - 21.02.14 (150408-352619232)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: own/found
- Hide waypoints: -
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: false
- Global filter: display all caches
- Last backup: 26. Feb., 13:49
- Routing mode: Fahrrad

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
- Geocaching.com date format: d.M.yyyy
- BRouter connection available: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (68,7 GB free) v1 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (68,7 GB free) v1 external non-removable isDir(7 entries)
- Geocache data: /storage/5437-5937/Android/data/cgeo.geocaching/files/GeocacheData (395,4 GB free) v1 external removable isDir(19 entries)
- Public Folders: #9
- BASE: /cgeo (Benutzerdefiniert)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::], default: /storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Available:true, Files: 83, subdirs:17, free space: 68,7 GB, files on device: 13511675)
- OFFLINE_MAPS: Lars_512GB/VectorMaps (Benutzerdefiniert)[Lars_512GB/VectorMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/5437-5937%3AVectorMaps::], default: /cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/5437-5937%3AVectorMaps/document/5437-5937%3AVectorMaps, Available:true, Files: 2080, subdirs:23, free space: 395,4 GB, files on device: 0)
- OFFLINE_MAP_THEMES: Lars_512GB/VectorMaps/_themes (Benutzerdefiniert)[Lars_512GB/VectorMaps/_themes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/5437-5937%3AVectorMaps%2F_themes::], default: /cgeo/themes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/themes]] (Uri: content://com.android.externalstorage.documents/tree/5437-5937%3AVectorMaps%2F_themes/document/5437-5937%3AVectorMaps%2F_themes, Available:true, Files: 2066, subdirs:22, free space: 395,4 GB, files on device: 0)
- LOGFILES: /cgeo/logfiles (Standard)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Available:true, Files: 21, subdirs:0, free space: 68,7 GB, files on device: 13511675)
- GPX: /cgeo/gpx (Standard)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Available:true, Files: 7, subdirs:0, free space: 68,7 GB, files on device: 13511675)
- BACKUP: /cgeo/backup (Standard)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Available:true, Files: 10, subdirs:10, free space: 68,7 GB, files on device: 13511675)
- FIELD_NOTES: /cgeo/field-notes (Standard)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Available:true, Files: 45, subdirs:0, free space: 68,7 GB, files on device: 13511675)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Standard)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Available:true, Files: 0, subdirs:0, free space: 68,7 GB, files on device: 13511675)
- TEST_FOLDER: [Veraltet]/data/user/0/cgeo.geocaching/files/unittest (Standard)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest], default: (same)] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Available:true, Files: 0, subdirs:0, free space: 68,7 GB, files on device: -1)
- Map render theme path: Elevate 4/Elements.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
- content://com.android.externalstorage.documents/tree/5437-5937%3AVectorMaps (26. Feb., 17:00):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (26. Feb., 17:00):RW
- content://com.android.externalstorage.documents/tree/5437-5937%3AVectorMaps%2F_themes (26. Feb., 17:00):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:768,0 KB) on system internal storage
-Settings: v5, Count:110
--- End of system information ---
```

**Comment by Lineflyer** [comment]
@eddiemuc 
One question for my understanding (as I do not know the code details):
Did you reuse the existing code we have to write/read data to/from "GeocacheData" (e.g. store log images, etc.) to access the new "MapThemeData" or did you code e a new approach?

**Comment by eddiemuc** [comment]
> @eddiemuc 
> One question for my understanding (as I do not know the code details):
> Did you reuse the existing code we have to write/read data to/from "GeocacheData" (e.g. store log images, etc.) to access the new "MapThemeData" or did you code e a new approach?
> 

Once the themes are in GeocachData folder, then the are approached same as before (via File interface)

Is your observation specific to map themes? Or is it maybe the map file (accessed via SAF) which is responsible for slowness?

**Comment by Lineflyer** [comment]
> Is your observation specific to map themes? Or is it maybe the map file (accessed via SAF) which is responsible for slowness?

Well, at least the long time on startup for sync is for sure caused by the themes.
I will do several testcases to get more clues.

Did you see the linked video?

**Comment by Lineflyer** [comment]
Another update:
On the device for which I linked the video above, I did one change:
I used c:geo menu - Settings - Offline-Data - Geocache Data Folder and set it from `/storage/emulated/1234-5678/...` (which is my SD card) to `/storage/emulated/0...`. This copy process (of 22,5MB) took also more than 2 minutes.

Afterwards the access times and repsonsiveness are fine.

So the main question is, why is it so much slower when using my SD?
I have a Samsung Evo 512GB UHS-I Class 3 card which should be quite fast...mmh.

**Comment by eddiemuc** [comment]
> Did you see the linked video?

Not yet, I am outside.

The initial sync is of course caused by map themes and will go away, I promise.

Another question: do you see any sped differences when you compare c:geo on Android 11 with earlier versions? (I noticed with emulatora that SAF was slower in higher SDKs than in lower SDKs)

**Comment by Lineflyer** [comment]
I am just preparing an SD for test on my Android 5 device.
Will use the weekend to perform some more tests. 

Right now my assumption is, that the main problem seems to be the access time to handle those many small files.
It was seemingly no problem when using the legacy method (because I always used my SD) but is a problem using the methods for "GeocacheData" files on the very same SD card on the very same device.

**Comment by eddiemuc** [comment]
> I am just preparing an SD for test on my Android 5 device.
> Will use the weekend to perform some more tests. 
> 
> Right now my assumption is, that the main problem seems to be the access time to handle those many small files.
> It was seemingly no problem when using the legacy method (because I always used my SD) but is a problem using the methods for "GeocacheData" files on the very same SD card on the very same device.
> 

Well this would sound like a typical SAF problem to me. I always had problems when accessing many small files. This was the reason to implement support of zipped themes btw. We will see more of this I fear.

**Comment by Lineflyer** [comment]
> Well this would sound like a typical SAF problem to me. I always had problems when accessing many small files. This was the reason to implement support of zipped themes btw. We will see more of this I fear.

But except syncing the theme files (which involves SAF) access to the themes does not touch any SAF method. That AFAIR was your goal and reason to use this sync method.
However it it significantly slower than the previous method to access the theme files...the question is why.

**Comment by eddiemuc** [comment]
> > Well this would sound like a typical SAF problem to me. I always had problems when accessing many small files. This was the reason to implement support of zipped themes btw. We will see more of this I fear.
> 
> But except syncing the theme files (which involves SAF) access to the themes does not touch any SAF method. That AFAIR was your goal and reason to use this sync method.
> However it it significantly slower than the previous method to access the theme files...the question is why.

True, this is strange

**Comment by Lineflyer** [comment]
My guess would be, that someone should carefully compare the code we use to access files with destinations provided by:

1. `Environment.getExternalStorageDirectory()` (the method we previously used to access theme files) 
2.  `Context.getExternalFilesDirs(null)[1+]` (the method we use now to access the synced theme files).

It looks like the second one is much slower on handling high amount of files.

@pstorch

**Comment by pstorch** [comment]
@Lineflyer sorry, I lost track of all the changes and your discussion on how to get there. I think I'm of little help here.

**Comment by Lineflyer** [comment]
Hi @pstorch 

my question is rather unrelated to all, what has changed.
Let me try to summarize as follows:

Previously we read map theme files using the code dealing with the method ˋEnvironment.getExternalStorageDirectory()ˋ. Due to changes regarding SAF we do now buffer the map theme files into the GeocacheData directory which is accesed by code you authored AFAIR which uses the method ˋContext.getExternalFilesDirs(null)[1+]ˋ.
The problem arising is, that the second method seems much slower (at least I would assume that from testing).

**Comment by eddiemuc** [comment]
Both methods `Environment.getExternalStorageDirectory()` and `Context.getExternalFilesDirs(null)` in the end return a File pointing to a directory which by the grace of Android is accessible to the application. We use the File interface the same way whether the File object is returned from one method or the other (list(), create/delete Files in folder, read/write to FileInput/outputstreams etc).

The only difference I can think of thus must be related the path that the directory is pointing to. So either special differences in either the physical device it is located on or special permission mamagment by Google for certain paths or physical devices.

**Comment by eddiemuc** [comment]
@Lineflyer after looking at your video:
* during VERY long pause in the syncrhonize dialog where the status says "0/x files, 0/y dirs processed" ,the process is doing three things (usually so fast, even when source is SAF, that I did not put a special status for it):
    * reads the detailed file info list from source, including subdirs (the SAF directory)
    * reads the current detailled file info list from target, including subdirectories (the "File" directory)
    * reads the "_cgeoFolderSyncInfo.txt" for each folder in target (the "metainformatione" needed from sync) 
* it is interesting to see that the part of the sync expected to be slow is then so lightning fast. I guess this is because in your example nothing was changed in the dirs anyway and no more file operation is occuring 
* Since we now removed explicit sync status in GUI , we are no longer able to track this anyway in GUI (otherwise I would have introduced more status inbetween steps in the first phase). 

* When you actually select a theme in your video, what happens in the background (synchronous to the GUI, this is why it is blocking) is that the theme data is actually loaded from disk using mapsforge libs. An interesting fact for you: if you use ZIP themes, then the last used ZIP file is stored in memory. This means if you switch between multiple themes within the same ZIP file you should NOT have the blocking GUI. Can you confirm this?

**Comment by Lineflyer** [comment]
Thanks @eddiemuc for the explanation of whats happening underneath the hood.
Indeed its now less easy trying to find out whats happening as it happens in background.

I tried the apps behavior with todays nightly.
The positive thing is, that I can start using c:geo now right away and the background sync seems not to impact operation.

What is however still problematic is, that when I start the live map in the first approx. 30 seconds (presumably the time taken by the sync) after startup of c:geo it will come up with the default theme and the theme menu shows no available theme. As in normal cases the sync will do nothing but compare (also in my case) I wonder why the buffered themes are not available at this point?

Regarding the time needed to change the theme:
I will test with zipped themes anyway. Just wanted to test the existing worst case (user has many unzipped themes) first.

One question:
We presumed, that using SAF to access the themes will be to slow to work. Did you test this?
As SAF is the desired way by Google for apps to access files I wonder if they might handle such cases in their framework (e.g. by internal buffering or whatever).
Could you provide a test version where plainly SAF is used to provide themes to the mapsforge map? If its just to much effort to rewrite things just for testing, I can understand this. I am just afraid, that we create a complex workaround for an issue we only fear but never tried to proof.

Few words regarding other possible causes for the problem on my device:
After reading last night a lot about SD cards I could also imagine, that my SD has long acess times to initially open a file. I tested data rates for the card and its 50-70 MByte/s, which is according to its specs. 
Whatever: With the old access methods I was able to switch themes in spit of a second even while they were stored on the very same SD.

**Comment by eddiemuc** [comment]
@Lineflyer 

> What is however still problematic is, that when I start the live map in the first approx. 30 seconds (presumably the time taken by the sync) after startup of c:geo it will come up with the default theme and the theme menu shows no available theme. As in normal cases the sync will do nothing but compare (also in my case) I wonder why the buffered themes are not available at this point?

Aaah, I think you found a bug of mine... 
Reason is that the "availableThemes" list is only filled after the initial sync is done. Since before this sync was done on startup (and you couldn't continue before it was done), the list was always filled when you entered map. But now, since this is done asynchronously, the list is filled first time only after initial sync. 

I have to change that and will do that...

> One question:
> We presumed, that using SAF to access the themes will be to slow to work. Did you test this?
> As SAF is the desired way by Google for apps to access files I wonder if they might handle such cases in their framework (e.g. by internal buffering or whatever).
> Could you provide a test version where plainly SAF is used to provide themes to the mapsforge map? If its just to much effort to rewrite things just for testing, I can understand this. I am just afraid, that we create a complex workaround for an issue we only fear but never tried to proof.

Actually my first approach for Themes was exactly to do it like this, and you can find an implementation for this too in the mapsforge version I provided to them (there is a new class `ContentResolverResourceProvider` done by me which provides the theme resources to the class `ContentRenderTheme`, this was done specifically to implement the SAF use case as you described above)

However, this was terribly slow from the beginning. It took about 10-15 seconds in emulator **each time** I opened an XmlTheme that way, and this was mainly caused by SAF having to read in about 200 icon files (very small files, but many of them). This was actually the reason I started to approach the Zip-way.

You can test this approach and its slowness already simply by deploying the mapsforge sample application in mapsforge-samples-android. But I fear they only have developer support for this one since it is meant to provide implementation examples to those, see https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Developers.md

If you want, I can with very small effort add an implementation which gives you access to the Xml Themes stored in public SAF folder in addition to the ones in the synchronized folder (for testing purposes only! So themes would then be displayed duplicately, one time from Public folder using SAF, a second time fro synchronized folder using normal File interface). I could couple this behaviour to debug-flag. Would that be what you want?

**Comment by eddiemuc** [comment]
Some general things wrt Googles intention with SAF:

I think the problem lies with the approach c:geo is using towards files and directories in general. We are dealing very heavily with Files and Folders on disk, much more than most apps I know (except file managers :-)). We are in this regards more like a Desktop application than a typical mobile device applications. Google in my opinion does not have that as much on his mind. It rather thinks about typical app approaches where data is usually shared with others using intents and not file interfaces. 

For commonly shared files (images, videos etc) Google provides MediaStore. But there, it expects the using apps not to care about things like directory structures or switching stuff e.g. from SD to internal storage and vice versa. In contrast, c:geo cares about these things a lot.

I think it would be possible (with a lot of effort though!) to redesign c:geo UX such that we have almost no more need to use persistent public folders. But this would mean to discontinue many c:geo features wrt detailled user control where which data is stored. This is then more controled by the Android system. The only exception I really see are offline map files simply because they are so large.

**Comment by Lineflyer** [comment]
> If you want, I can with very small effort add an implementation which gives you access to the Xml Themes stored in public SAF folder in addition to the ones in the synchronized folder (for testing purposes only! So themes would then be displayed duplicately, one time from Public folder using SAF, a second time fro synchronized folder using normal File interface). I could couple this behaviour to debug-flag. Would that be what you want?

If you would be willing to do that, it would be great for testing in our nightlies.
Not sure if there is a need to keep that. I guess we might remove it once again before going to beta. But you might use the debug flag as proposed and we might decide later to keep or remove it. (Is is possible to prepend e.g. "SAF:" in front of the theme name to make it distinguishable?)

**Comment by eddiemuc** [comment]
I created PR #10090 which will now 
* load existing themes on startup (so you should not get only "(default)" theme any more if you open maps too fast)
* in debug mode only: add all available Themes ADDITIONALLY accessible via SAF through public folder. Those entries have a prefix "z[SAFTest]" in the list. (The list looks in debug mode pretty cluttered now, but hey, its debug mode :-))

@Lineflyer if you use the latter for performance tests, you should know that the horrible performance arised for me only when using SDK30 (Android 11) device/emulator. Not so much in SDK29.

**Comment by Lineflyer** [comment]
Thanks @eddiemuc 
Will test as soon as merged in the nightlies. If I find time tonight, I might test the PR build.

Question to understand whats happening at what point of time:
Will the SAF themes also be read and loaded when debug mode is off (only not shown then) or does loading them via SAF only occur after I switched on debug mode (then directly or only individually once I open theme selection/select one of those themes)?
Sorry for not knowing in detail how the theme mechanism works..dumb tester ;)

And another question:
In PR #10090 you also fixed an error in the mapsforge code. Could this error have had performance impacts for this topic?

**Comment by eddiemuc** [comment]
> Question to understand whats happening at what point of time:
> Will the SAF themes also be read and loaded when debug mode is off (only not shown then) or does loading them via SAF only occur after I switched on debug mode (then directly or only individually once I open theme selection/select one of those themes)?

No need to apologize, this stuff IS pretty complicated.. (and there are no dumb questions anyway :-))

Because this is as of now just for testing I did a little trick: I assume that both public theme folder and the "private" copy folder are always in sync, So I create a second entry for public folder in the map theme list for each entry I find in the private folder, (I don't explicitely scan the public folder to see if it is really there or if there is anything else). The list is now created with "duplicate" entries, but ifdebug=off only those from the private folder will show 

Loading of SAF themes will only occur if you select them in the theme list (as with any other theme), and you can only select them there if debug mode is on. The additional buffering of last read theme zip file is not active for SAF themes.

> And another question:
> In PR #10090 you also fixed an error in the mapsforge code. Could this error have had performance impacts for this topic?

No because the affected class was not used by c:geo before, and the error I found is unrelated: current mapsforge code (done by me) would only accept SAF folders as theme ressource root folders which were directly selected by the user. Subfolders of this would not work. I already put a PR to mapsforge with a fix.

**Comment by Lineflyer** [comment]
> We are in this regards more like a Desktop application than a typical mobile device applications. Google in my opinion does not have that as much on his mind. It rather thinks about typical app approaches where data is usually shared with others using intents and not file interfaces.

@eddiemuc 
I now the following has been discussed before and I might have not found enough time to participate in it or understand it initially:
Even if I use a whole lot of themes, it will still be a rather low amount of storage space needed but only a large amount of small files (which is what makes problems on my device and especially on SD). Looking at the low amount of megabytes potentially needed and the focus on fast sync and access, wouldn't it be an option to take this out of` the `GeocacheData` folder into `Context.getFilesDir()` (listed as <1> in https://github.com/cgeo/cgeo/wiki/Disk-usage-structure ).
The difference would be, that it is (normally) not user accessible, but this is not needed as its just a mirror of data, and that it is (normally) never on a removable device. The second aspect would implicitly solve the main problem I see here.

If we would use this storage, we would:
1. Treat synced theme same as our database (keep it protected and reliably available)
2. Use a method which is not going to deprecated (as this is the basic Android construct of saving data an app needs to work)

Going a step further we could also designate this as cached data (which is in fact is), but this would have the drawback, that certain clean up tools or even the user might delete it from time to time. But I guess your sync process would work fine in such case.

**Comment by eddiemuc** [comment]
@Lineflyer using Context.getFilesDir() would work just fine. My understanding is that this one is controlled by system and always in internal memory, while the other can be moved to Sd-card and such. Correct?

Wrt cache directory: is there a reason why whole GeocacheData is not in the cache? With exception of (recently added) offline log images, I think the whole data is just a download cache anyway is it not? Moving this to cache would give the user far more opportunity to free space than the few hundert KBs in map themes.

**Comment by Lineflyer** [comment]
> @Lineflyer using Context.getFilesDir() would work just fine. My understanding is that this one is controlled by system and always in internal memory, while the other can be moved to Sd-card and such. Correct?

Correct!

> Wrt cache directory: is there a reason why whole GeocacheData is not in the cache? 

I would consider it offline data. Users might want to access this data even over several sessions, etc.

I would define cache data as data which us valid for one session and considered invalid or just no longer existing in the next session. That pretty much how we handle theme sync.
But I have no details about the technical difference between the sysinternal storage as mentioned above and the cache storage. If it requires yet another file interface, lets forget about it for this moment. We can later switch to it.

Let me test on some devices throughout today incl. the SAF debug access, trying to bring more light into this issue. I will report back later.

**Comment by eddiemuc** [comment]
> I would define cache data as data which us valid for one session and considered invalid or just no longer existing in the next session. That pretty much how we handle theme sync.

I disagree. The sync mechanism would be pretty worthless if this would be true. It is primarily meant to preserve a copy of map themes in a fast-accessible way without the need to read it from public folder every session (because this is assumed to be very slow with SAF). 

Putting the problems aside which we currently discuss in this issue: the folder sync at c:geo startup when nothing has changed in map theme folder should be very fast (checks whether something has changed, finding out that nothing has changed, finished). In contrast, copying the data at each c:geo startup would be very slow.

But of course file sync is implemented "self-restoring" (if copy is messed up for some reason it is restored on startup). Same as for the GeocacheData: if missing it will self-restore on startup (provided there is an internet connection of course).

**Comment by Lineflyer** [comment]
> I disagree. The sync mechanism would be pretty worthless if this would be true. It is primarily meant to preserve a copy of map themes in a fast-accessible way without the need to read it from public folder every session (because this is assumed to be very slow with SAF).

You are right. Therefore lets not define the themes as cached data.

> Same as for the GeocacheData: if missing it will self-restore on startup (provided there is an internet connection of course).

AFAIK it will only self-restore on demand (i.e. if you open or refresh a cache) not on startup in general.

Anyway:
As said I will test with my worst-case setup (lot of themes, slow access) on some devices (also using the SAF debug access) and provide feedback.
Based on that, we should think over and finally decide if we stay with having the themes buffered in "GeocacheData" or some other method/destination.

**Comment by MagpieFourtyTwo** [comment]
> Wrt cache directory: (...) give the user far more opportunity to free space than the few hundert KBs in map themes.

JFTR: My ``_themes`` folder does not contain just a few hundred kB, but in fact about 10.000 ...

> > Same as for the GeocacheData: if missing it will self-restore on startup (provided there is an internet connection of course).

> AFAIK it will only self-restore on demand (i.e. if you open or refresh a cache) not on startup in general.

Yep, that's matching my experience, too: I now and then clean up the ``GeocacheData`` folder (with a lot of saved caches, this folder gets kind of huge over time), and the cache folder will only be recreated on manual refresh of the corresponding offline stored cache listing.

**Comment by Lineflyer** [comment]
Coming back to my testing:
I tested intensively on the initially mentioned device (Android 11, Samsung S20) and also briefly on another device (ZTE Blade S6, Android 5.0.2).
Without explaining everything in details, this is my conclusion:
- The whole theme mechanism works on both devices
- On both devices it gets real slow/unresponsive as soon as the SD is involved (5-8 seconds to change from one theme to another). If I only use internal storage (`GeocacheData`on internal storage, SAF directory chosen from internal storage) the speed is significantly better (1-2 seconds to change from one theme to another)
- Direct access via SAF to themes as well as via `GeocacheData` has approx. same speed when using SD. SAF is a bit slower than `GeocacheData`when using internal storage.
- The problems described in #10089 show up on both devices if I start any refreshing or deleting of caches while (potentially) the startup sync is still in progress in the background. So minimizing the sync time will help also to avoid any conflicts there.

Other remarks:
- Listing the buffered themes while sync is still in progress works now. Thanks @eddiemuc 
- I experienced some crashes after renaming some theme.xml files (to enforce new copy activity on startup). Will try to reproduce and open a dedicated issue for that.

My conclusion/proposal would be:
Lets store the `MapThemeData` using `Context.getFilesDir()` (at the same place where we store the database by default) instead of the current approach to avoid any involvement of removable and potentially unreliable storages. 
Even for users with many themes I guess it will be a maximum of 10-20 MB eaten up by that, so that the option to be able to place it on SD is not worth the potential problems it may produce.

**Comment by Lineflyer** [comment]
Changed title

**Comment by eddiemuc** [comment]
I agree with @Lineflyer s suggestion and will provide a PR to move sync dir to `Context.getFilesDir()` (should actually be a one-liner :-))

**Comment by eddiemuc** [comment]
PR #10094 will move themes to `Context.getFilesDir()` (resp a subdir/neighboring dir of it). It will also move LocalStorage to migrate version 2 and delete old MapThemes directory (@Lineflyer first startup may take some time on your device because themes on old storage place are deleted)

**Comment by MagpieFourtyTwo** [comment]
Will the sync'ed theme files go to user accessible storage, too, when changing the setting for ``Database Location`` to ``On user storage[X]``? Would highly appreciate if they would, cause this way one can still be in control of the sync'ed files living in internal (i. e. not accessible) storage (and could even clean the mess just in case s/th went terribly wrong while sync'ing - BTDTNT, but was not able to reproduce).

**Comment by eddiemuc** [comment]
> Will the sync'ed theme files go to user accessible storage, too, when changing the setting for ``Database Location`` to ``On user storage[X]``?

Nope they won't. You really want to couple that to the database location setting?

**Comment by fm-sys** [comment]
I think always in internal storage is just fine. 
The database is just a single file and may be large (-> SD) 
Themes are potentially thousands of very small files (-> SD doesn't make sense)

**Comment by MagpieFourtyTwo** [comment]
Agreed - nevertheless there should be a possibility to clean them up ... so what about a button like ``Delete orphaned files``?
S/th like ``Initialize them sync`` which would just delete the sync'ed stuff entirely and then just restarts c:geo (which will immediately and freshly fill the sync storage from scratch) ...?

**Comment by MagpieFourtyTwo** [comment]
I still have the situation in mind where no themes have been shown at all (apart form ``default``), until I completely removed the entire sync'ed stuff from ``shared`` ... and after next restart everything was fine again ...

**Comment by Lineflyer** [comment]
Lets not implement cleanups for nightlies but make sure it works in a way that no cleanups are needed when its ready for production.

**Comment by eddiemuc** [comment]
> Lets not implement cleanups for nightlies but make sure it works in a way that no cleanups are needed when its ready for production.
> 

Some nightly users seem to care a lot about polluting their internal storage. Really no migration routine (which in this case just deleted the previously used directory)?

**Comment by MagpieFourtyTwo** [comment]
While asking for a "cleanup routine" for the internal cache, I did not have storage space in mind, but pure function.
Automatisms are fine, but the best ones are those, you can switch off - or at least reset. ;)

As for the migration routine I agree with @Lineflyer - don't think we need a clean up for the old folder.
I guess the current version is not that widely distributed, thus a short info over here will be sufficient, IMO.

**Comment by Lineflyer** [comment]
2021.03.01-NB1-9c32002 has been built to test the change.

**Comment by Lineflyer** [comment]
Wow...now that's perfectly fine and fast now for me even with my worst case scenario of 2066 files taken from SAF (on SD) copied to the buffer. Also taking away and/or adding themes works perfectly fine in background in reasonable time now (toast shows up few seconds after startup).

IMHO we are done here with a best possible solution in terms of speed and enforcement of SAF.
Thanks @eddiemuc for perfect cooperation.

**Comment by eddiemuc** [comment]
Thanks @Lineflyer for all the testing effort and patience wrt fixing dev bugs

**Comment by MagpieFourtyTwo** [comment]
(No) News (i. e. good News) from the other side, too: ;)
Nothing changed at all:
- First sync took 2.8 secs
- consecutive ones w/o theme changes do not even show the toast (is there a minimum time implemented?)
- sync after changing a theme file takes 550 to 600 msecs, like before.

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
AFAIK the toast is only shown when sync was needed (i.e. something changed).
IMHO this is a good implementation, in order not to confuse or annoy users by getting a toast on each startup but still see that the job is done, once they change themes.

**Comment by MagpieFourtyTwo** [comment]
Yep. totally agreed, not showing if nothing happened, is the best anyway.
Was just wondering, cause I would have bet that it was there in the past, even when nothing changed.

**Comment by eddiemuc** [comment]
> Yep. totally agreed, not showing if nothing happened, is the best anyway.
> Was just wondering, cause I would have bet that it was there in the past, even when nothing changed.
> 

Indeed it was shown always in the past (also when nothing had changed), together with a second toast when sync was started. Now behaviour is changed to what @Lineflyer said
