### ISSUE TITLE
Check on existing final coords before navigation is started

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10074]
From support mail:

If I start navigation towards any cache (using Google Maps form c:geo navigation menu) c:geo asks me, whether I want to navigate to the cache coords itself or to the parking coordinates of the cache if existing. Thats great.

I do however miss this similar function on e.g. mysteries which have a final waypoint defined. This made me some times drive to the listing coordinates instead of the real final.

So I suggest the following:
If there is a final waypoint present and contain valid coordinates and there is **no** modified listing coordinate for the cache, c:geo should offer the very same selection providing the option to select the listing coordinates or the defined final waypoint (and also the parking coordinate if available) as navigation targets. Just reuse the same dialog and usage as for parking waypoints for this condition.

**Comment by moving-bits** [comment]
> If I start navigation towards any cache (using Google Maps form c:geo navigation menu) c:geo asks me, whether I want to navigate to the cache coords itself or to the parking coordinates of the cache if existing. Thats great.

Where is this question being asked?

I opened a cache which has a "parking" waypoint, pressed the "navigation menu" button in the actionbar, and selected "Google Maps directions". This openes Maps, but does not ask for selecting the target. Same when I open "navigate" menu entry from map's cache popup.

**Comment by Lineflyer** [comment]
Mmh.. does parking have the same coords as the listing coords? For me its working as described.

**Comment by Lineflyer** [comment]
You have to select Navigate(Drive)

**Comment by moving-bits** [comment]
Thanks, found it.
