### ISSUE TITLE
Downloaded theme not set as current theme

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10076]
**Describe the bug:**
A freshly downloaded theme doesn't get set as current theme, although `RenderThemeHelper.setSelectedMapThemeDirect(UriUtils.getLastPathSegment(result));` is being called.

**To Reproduce:**
- Open map downloader in live map
- Select a theme file (either OpenAndroMaps' Elevate or one of the Freizeitkarte theme files) and download it
- After successful download c:geo tries to set this file as current theme

**Actual behavior/state after performing these steps:**
Theme gets reset to default

**Expected behavior/state after performing these steps:**
Freshly downloaded theme should be set as current theme

**Version of c:geo used:**
Current master

**Is the problem reproducible:**
Yes

**Additional context:** (`RenderThemeHelper.setSelectedMapThemeDirect()`)
When trying to set a freshly downloaded theme file, the following applies:
- `themeCandidate` has value `fzk-outdoor-contrast-v5.zip`
- List of available themes look a bit strange (first entry):
  ![image](https://user-images.githubusercontent.com/3754370/109344839-94516f80-786f-11eb-9943-357292ae7e31.png)
- `selectedTheme` is reset to blank, so the following commands will never match:
  ![image](https://user-images.githubusercontent.com/3754370/109344940-b2b76b00-786f-11eb-85d5-b2287a2d525a.png)

In contrast to that, when setting an already downloaded theme at a later time:
- `themeCandidate` has the different value of `fzk-outdoor-contrast-v5.zip:fzk-outdoor-contrast-v5/fzk-outdoor-contrast-v5.xml`
- and setting the theme does work now

Thus I guess something needs to be changed in the calls to `RenderThemeHelper.setSelectedMapThemeDirect` in the downloaders' `onSuccessfulReceive()` methods.

**Comment by eddiemuc** [comment]
Programming bug of mine. "SelectedTheme" must be replaced with "themeCandidste" in marked placed, then it should work.

Since a zip may contain more than one theme, we have to select any of those.

**Comment by moving-bits** [comment]
Damn, I thought I had tried that... Anyway: Works, thanks!

**Comment by eddiemuc** [comment]
@moving-bits do you mean you fixed my bug for me? In that case: many thanks!
(This was probably the most exact bug report I ever got anyway :-))

Or should I still provide a fix? (In 15 minutes or so, after sorting the families laundry, I will head to my computer)

**Comment by moving-bits** [comment]
Actually I was unsure whether you already jumped on it (as you had assigned it to yourself) or not. Didn't want to interfere. But as I had tested it yesterday to be able to continue with some other work, I do have a fix ready for it - will push the PR.

**Comment by eddiemuc** [comment]
Thanks a lot for this fix!
