### ISSUE TITLE
Hide unittest folder selection in Settings - System

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10081]
Just s small question:
Does it make sense to offer the setting (c:geo Menu - Settings - System) for selecting a unittest folder to the normal user?
I guess it will break nothing if the normal user changes it, but its useless and no user will understand this setting.

I know the preference might be needed for emulator tests, but do we need to show such setting entry?

**Comment by eddiemuc** [comment]
I at least need it regularly, and there is no way to do this via code. It must be somehow in GUI.

Setting should already only be visible in debug mode. I am open for other measurements to hide it even more, but I really need this one.

**Comment by Lineflyer** [comment]
You are right. I was not aware, that it is coupled to debug mode.
I indeed had debug mode active when first seeing this. I think its perfectly fine like this then.
