### ISSUE TITLE
Perform theme folder sync as background task

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10082]
As discussed in #10070 : 

The sync of theme files between the folder selected by the user and our internal buffer should IMHO be done in the background.
Showing it provides no benefit to the user and might block the UI on each startup.

If this is a big effort I suggest to at least for now rename the currently very long and detailed caption text to something simple like "Buffering map theme files. Please wait..."

**Comment by eddiemuc** [comment]
@Lineflyer I have already implemented this (as promised) and are in the middle of testing. Don't worry :-) there will be a PR soon
