### ISSUE TITLE
Circle color setup effective only after restart (OSM)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10114]
Reported by a user of 2021.02.14 and reproducible on 2021.02.27-NB

- Have circle color in default state
- Open OSM map
- Activate circles
- Go to Settings - Map and change circle color(s)
- Open map again

Circles stil shown in old color
After restart circles are shown in new color

(On GMaps it seems to work better but might require turning circles off and on again, not clearly reproducible)

**Comment by bekuno** [comment]
I could reproduce.
Additionally, when switching to GM from OSM with circle 'on' the circles are not shown. They are shown after deactivating circle, show map, activating circle.
