### ISSUE TITLE
Problem posting log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10117]
A basic member using c:geo 2021.02.14 contacte us, that he has problems posting a log.
Still asking for some more details, but his log shows this:

`03-06 07:26:28.076 26138 27816 E cgeo : java.lang.RuntimeException: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=422, message=Unprocessable Entity, url=https://www.geocaching.com/api/proxy/web/v1/geocache/gc8rmhx/GeocacheLog} 03-06 07:26:28.076 26138 27816 E cgeo : 	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46) 03-06 07:26:28.076 26138 27816 E cgeo : 	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94) 03-06 07:26:28.076 26138 27816 E cgeo : 	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645) 03-06 07:26:28.076 26138 27816 E cgeo : 	at cgeo.geocaching.connector.gc.GCWebAPI.postLog(GCWebAPI.java:470) 03-06 07:26:28.076 26138 27816 E cgeo : 	at cgeo.geocaching.connector.gc.GCLoggingManager.postLog(GCLoggingManager.java:137) 03-06 07:26:28.076 26138 27816 E cgeo : 	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:741) 03-06 07:26:28.076 26138 27816 E cgeo : 	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:725) 03-06 07:26:28.076 26138 27816 E cgeo : 	at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.doInBackground(AbstractAsyncTaskWithProgress.java:134) 03-06 07:26:28.076 26138 27816 E cgeo : 	at android.os.AsyncTask$2.call(AsyncTask.java:333) 03-06 07:26:28.076 26138 27816 E cgeo : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 03-06 07:26:28.076 26138 27816 E cgeo : 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 03-06 07:26:28.076 26138 27816 E cgeo : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 03-06 07:26:28.076 26138 27816 E cgeo : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 03-06 07:26:28.076 26138 27816 E cgeo : 	at java.lang.Thread.run(Thread.java:764) 03-06 07:26:28.076 26138 27816 E cgeo : Caused by: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=422, message=Unprocessable Entity, url=https://www.geocaching.com/api/proxy/web/v1/geocache/gc8rmhx/GeocacheLog} 03-06 07:26:28.076 26138 27816 E cgeo : 	at cgeo.geocaching.network.Network.lambda$static$6(Network.java:621) 03-06 07:26:28.076 26138 27816 E cgeo : 	at cgeo.geocaching.network.-$$Lambda$Network$HJwZsCLFMmiISrdxtajFdFJJscU.apply(Unknown Source:2) 03-06 07:26:28.076 26138 27816 E cgeo : 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77) 03-06 07:26:28.076 26138 27816 E cgeo : 	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68) 03-06 07:26:28.076 26138 27816 E cgeo : 	at cgeo.geocaching.utils.RxOkHttpUtils$1.onResponse(RxOkHttpUtils.java:48) 03-06 07:26:28.076 26138 27816 E cgeo : 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 03-06 07:26:28.076 26138 27816 E cgeo : 	... 3 more`

Any idea so far?

```
--- System information ---
Device: ONEPLUS A6013 (OnePlus6T, OnePlus)
Android version: 9
Android build: ONEPLUS A6013_41_181103
c:geo version: 2021.02.14
Google Play services: enabled - 21.02.14 (100400-352619232)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: parking
HW acceleration: enabled (default state)
System language: de_AT / user-defined language:
System date format: dd.MM.yy
Debug mode active: yes
System internal c:geo dir: /data/user/0/cgeo.geocaching (181,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (181,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (181,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (428,0 KB) on system internal storage
Last backup: never
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: null
Map render theme path:
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / BASIC
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---
```

**Comment by bekuno** [comment]
~~~
java.io.IOException: request was not successful: Response{protocol=http/1.1, code=422, message=Unprocessable Entity, url=https://www.geocaching.com/api/proxy/web/v1/geocache/gc8rmhx/GeocacheLog}
~~~
Perhaps the user has used symbols in their message that are not OK for the log message.
Please ask the user if they can send you the field note for this log. Maybe we can reproduce the error then.

**Comment by Lineflyer** [comment]
The user meanwhile confirmed, that it was a temporary problem, which is no longer reproducible. 
Maybe a server issue...
