### ISSUE TITLE
Active circles not shown on change of map type

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10115]
2021.02.27-NB (Android 9):

- Have OSM active
- Activate circles in map quick settings
- Change to GMaps

Circles not shown although still active in map quick settings
Only after deactivating and activating the setting the circles are shown

**Comment by bekuno** [comment]
I could reproduce on release 2021.02.14.

For GM, when switching to GM from OSM with activated circles the no circles are shown. You have to deactivate, show map and activate circles.
