### ISSUE TITLE
Default folder for themes should be below maps folder

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10131]
Regarding the default location of the themes folder as discussed in #10123:

Indeed I can confirm, that Locus expects themes to be located in a subfolder `_themes` below the folder containing the vector offline maps. This is currently not configurable in Locus. So it would be wise to make this our default as well, so that users who download vector maps and themes with the c:geo downloader can easily reuse the structure with Locus.

The compatible structure should be like this:

`/cgeo/maps`
`/cgeo/maps/_themes`

**Comment by eddiemuc** [comment]
Fixed with PR #10132
