### ISSUE TITLE
Option to only refresh coordinates of unsolved mysteries in area

### ISSUE THREAD

**Issue by obfuscoder** [cgeo/cgeo#10137]
I usually have a lot of caches stored for offline use. I did this originally for for my home zone and a few zones areound it. Then I started solving all those mysteries and set the mystery coordinates in GC.com. Now I would like to let cgeo refresh and fetch the updated coordinates of those mysteries only. I do not want to refresh all stored caches which takes a lot of time. My request would thus be to have an option to only refresh coordinates of "blue" caches (Mystery, letterbox, ...) within a given area of the live map. This option could be narrowed down by only updating the blue caches with only the original coordinates and no user defined coordinates.

**Comment by Lineflyer** [comment]
Couldnt you just filter your stored caches according to your described criteria on your list and refresh the resulting filtered list? Need to check myself but sounds posssible...or not?

**Comment by MagpieFourtyTwo** [comment]
Maybe I'm wrong, but as soon as #9875 is fixed, solved mysteries should show up in the map as well as in lists with the ``Changed coordinates`` marker again, and should be filtered via ``With personal data`` => ``With modified coordinates``.

This should meet @obfuscoder's demands anyway, shouldn't it?

If this is still not sufficient, this may be a use case for #9081, i. e. *additionally* filter for ``Stored`` => ``Not stored``.

**Comment by obfuscoder** [comment]
Well, there is no option to filter "Without modified coordinates" - only "With modified coordinates. Also filter by type "blue" - that is multiple types - is not possible. Only one type can be selected in the filter. Furthermore, it is not possible to combine those filter rules. When I choose filter by type mystery and then filter by status not found for instance, the mystery filter is cleared and I see caches of all types I have not found yet.

Just to reiterate as it was not understood, it seems: I do want to update the mysteries stored on my phone which do NOT have changed coordinates on the phone yet.

Having a more advanced filtering system which allowed combining multiple types/filter rules would surely help here. The "without modified coordinates" filter is not mentioned in #9081 though.

**Comment by wolverine007** [comment]
Add the unsolved Mysteries either in cgeo and on GC to a separated list.

So you could refresh only this list in cgeo. 

In addition I suggest to create a new PQ to grab the solved mysteries from this GC list into your desired list in cgeo.

Problem solved :)

**Comment by Lineflyer** [comment]
With our new filter framework it is now possible to filter out unsolved mystery caches to easily be able to refresh only those. 
Therefore closing.

2021.07.21-NB
