### ISSUE TITLE
Reactivate or delete cgeo_commits twitter bot

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10130]
Today, I stumbled over the [cgeo_commits](https://twitter.com/cgeo_commits) Twitter account which seam to be inactive for more than two years.

![grafik](https://user-images.githubusercontent.com/64581222/110639008-807f0500-81af-11eb-8ec6-4e612447d454.png)

Was it deliberately switched off at some point or did it simply break and no one noticed? Does anyone still have the credentials and do we want to (try to) get it back up and running?

**Comment by SammysHP** [comment]
It probably just broke. I have the credentials, but I think we can delete the account. Nowadays there are better ways to follow changes on GitHub. ;)

If I get five or more upvotes from team members, I'll delete it.

**Comment by fm-sys** [comment]
> It probably just broke. I have the credentials, but I think we can delete the account. Nowadays there are better ways to follow changes on GitHub. ;)
> 
> If I get five or more upvotes from team members, I'll delete it.

@SammysHP although only three 'thumbs up' came in, I think you can delete the bot. It's not working anymore anyway, so it currently only leads to confusion...

**Comment by SammysHP** [comment]
`cgeo_commits` is now "disabled". Looks like you can't delete an account. It is not visible and can't be used anymore, but still exists for some time.
