### ISSUE TITLE
Check automated escaping in translations

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10140]
As we still have at least one occurrence of html embedded in `CDATA` elements, it might lead to compile errors if translators use special characters in their translations.

According to Crowdin documentation it should be possible to configure propoer auto-escaping in such cases. I do need to check however if this has any negative effects at other places.

**Comment by Lineflyer** [comment]
Other question:
The strings "debug_user_error_explain_options_html" is the last one, where we use `CDATA`.
Do we really need it here?

**Comment by eddiemuc** [comment]
> 
> Other question:
> The strings "debug_user_error_explain_options_html" is the last one, where we use `CDATA`.
> Do we really need it here?

No we don't. Was just there to format part of the text in italic, this is not mandatory.

**Comment by Lineflyer** [comment]
@eddiemuc 
Might you prepare a PR to remove it?
But please do not merge yet, as I am currently checking if Crowdin can fix this for us (just to have a safe config for any future occurences).

**Comment by eddiemuc** [comment]
> @eddiemuc 
> Might you prepare a PR to remove it?
> But please do not merge yet, as I am currently checking if Crowdin can fix this for us (just to have a safe config for any future occurences).

Yes but I would replace the translation key in such a PR (suffix html does not make sense any more)

**Comment by Lineflyer** [comment]
Yes, that makes sense. Otherwise I would have dared to do it manually on Github to only change the content.

**Comment by fm-sys** [comment]
> > @eddiemuc
> > Might you prepare a PR to remove it?
> > But please do not merge yet, as I am currently checking if Crowdin can fix this for us (just to have a safe config for any future occurences).
> 
> Yes but I would replace the translation key in such a PR (suffix html does not make sense any more)

AFAIK we already had this discussion some weeks ago, but decided to keep it as it is already translated into most languages...

**Comment by Lineflyer** [comment]
> AFAIK we already had this discussion some weeks ago, but decided to keep it as it is already translated into most languages...

Yes, I remember that, but as this might repeatedly cause problems if translations change or new languages will be implemented it might be wise to remove it.

I am right now checking some Crowdin options, but I am afraid it will not work as I am just repeating the default values in the Crowdin config file. So I guess it just ignores the content in the CDATA container unconditionally.
Will report back.

**Comment by Lineflyer** [comment]
For documentation:
I introduced the parameters `escape_quotes` and `escape_special_characters` as described [here](https://support.crowdin.com/configuration-file/#escape-quotes-options-for-properties-file-format) with commit 2304e4df9c45cdfd1a52f427bdb8bf268cef16fc . As can be seen in PR #10141 it did not fix the problem.

I will revert the mentioned commit and we should rather not use embedded HTML for now, unless someone else knows how to configure proper auto-escaping for Crowdin.

**Comment by bekuno** [comment]
@Lineflyer 
Did you once again exported the strings from crowdin after changing the configuration?

**Comment by Lineflyer** [comment]
Yes, sequence was:
- Change crowdin.yml
- Sync 
- Proofread problematic string
- Sync

Result was, what you see in PR #10141 -> no escaping

I escaped it manually on Crowdin now and synced again to satisfy myself by validating that the process still works.
Will be replaced anyway once the string is changed.

**Comment by eddiemuc** [comment]
@Lineflyer when doing the PR, would it help if I change/move already existing translations to the new preference key (and cleaned from html)?

**Comment by Lineflyer** [comment]
Actually I am not sure, how Crowdin will process this. IMHO it should upload those translations as approved onto Crowdin. I might however be wrong, in which case your work will be reverted with the next PR.
If you would take the work to try that out, it might be a knowledge gain. ;)

**Comment by eddiemuc** [comment]
Was a matter of minutes, so I changed this also in translated files. PR is #10143

**Comment by bekuno** [comment]
You have a space between attribute and : in 'escape_quotes : 2'

**Comment by Lineflyer** [comment]
> You have a space between attribute and : in 'escape_quotes : 2'
Maybe this is a error and therefore ignored?

At least I have seen the options taken over on Crowdins Github integration view.
I might try again before merging #10143

**Comment by Lineflyer** [comment]
No, its still not working:
See commit 8984fef4258a25119e4a6c8e8a30fca320529eab

while config looks fine on Crowdin:
![grafik](https://user-images.githubusercontent.com/949669/111041612-4a54b600-8439-11eb-96af-6a4fe3591a48.png)

Will revert the experiment and merge #10143 afterwards.

**Comment by Lineflyer** [comment]
FYI:
The translations contained in the PR #10143 have not been automatically taken over.
According to [crowdin documentation](https://support.crowdin.com/github-integration/#uploading-translations-from-repo) this has to be triggered on demand.

Will do that to try this feature and report back here.

**Comment by Lineflyer** [comment]
That worked out well so far.
Will document the process in our Wiki in case we need it from time to time to batch rework translations and back-sync those to Crowdin.

Leaving this issue open as reminder.

**Comment by Lineflyer** [comment]
Upload mechanism has been added to the Wiki: https://github.com/cgeo/cgeo/wiki/Translation-(L18N)#manual-upload-of-translation-from-github-to-crowdin

Just looking at the new Crowdin PRs it looks like the upload messed up the existing app description texts. There seems to be a problem with content segmentation. Will try to debug this and/or repair it. But we are done here.

Thanks @eddiemuc

**Comment by Lineflyer** [comment]
For the record:
The uploading of our `app_description*.txt` caused a real mess due to difference in content segmentation between source and individual translation (as mentioned above). There was no other obvious way as to manually correct everything.
I added this as known problem in the wiki article linked above. We should try to find a solution before we try the upload ever again :)
