### ISSUE TITLE
Internationalization error in some plurals

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10155]
Checking lint issues I found some occurrences of warning like this:

The quantity `'one'` matches more than one specific number in this locale (1, 21, 31, 41, 51, 61, 71, 81, 101, 1001, …), but the message did not include a formatting argument (such as `%d`). This is usually an internationalization error. See full issue explanation for more.

<p>Plural strings should generally include a `%s` or `%d` formatting argument. In locales like English, the `one` quantity only applies to a single value, 1, but that&apos;s not true everywhere. For example, in Slovene, the `one` quantity will apply to 1, 101, 201, 301, and so on. Similarly, there are locales where multiple values match the `zero` and `two` quantities. In these locales, it is usually an error to have a message which does not include a formatting argument (such as &apos;%d&apos;), since it will not be clear from the grammar what quantity the quantity string is describing.

In most cases it is caused by using an unnumbered value as `quantity=one` as it fits in English.
Example: The string `days_ago` uses 'Yesterday' for `quantity=one`. This will however make the translation of 'Yesterday' show up also if it was 101 days ago in some languages.

I will fix some of those which can be fixed purely by adjusting the source string.

**Comment by eddiemuc** [comment]
For clarification: up to now I thought that the default strings.xml contains the english translation only. So I assumed that (also for plurals) we only have to take care about the rules as they apply in english language - and other translations may add the other cases as needed. (E.g. in chinese I learned that not even the "one" case is needed)

Is that not true? Becasue right now this leads (in english) to a lot of duplication.

**Comment by okainov** [comment]
Russian is one of such beautiful languages :)

**Comment by Lineflyer** [comment]
> Is that not true?

I also thought, that Crowdin would add needed other quantities depending on the language, but a while ago we learned, that we need to define all of them in our strings, otherwise those do not show up as possible quantity in specific languages. I might be wrong though.... @bekuno Didn't you add the missing quantities some months ago due to this reason?

**Comment by Lineflyer** [comment]
Missing quantities have been discussed here:
#3599
#8456

The outcome was, that it *might* be a Crowdin bug, but it works (in most cases except french) when we add all quantities to the source.

**Comment by Lineflyer** [comment]
See #8029 for lint warnings and lint configuration.

**Comment by Lineflyer** [comment]
Done here.
