### ISSUE TITLE
init_renderthemefolder_synctolocal_dialog_message has unnumbered variables

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10152]
Seems to be newly introduced. This should be avoided as other languages might need other order.

21:18:20  /home/jenkins/slave/workspace/cgeo continuous integration/main/build/intermediates/incremental/mergeBasicDebugResources/merged.dir/values/values.xml:2839: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

Caused by string `init_renderthemefolder_synctolocal_dialog_message`

**Comment by eddiemuc** [comment]
Jup, I messed that up. Will be fixed

**Comment by eddiemuc** [comment]
Is it possible to fail the CI build (via Codacy or Jenkins-Build) if use of positional parameters is missing? This seems to generate a lot of after-work (since translations have to be redone).

**Comment by eddiemuc** [comment]
PR #10159

**Comment by Lineflyer** [comment]
> Is it possible to fail the CI build (via Codacy or Jenkins-Build)

Yes, that would be helpful.
It should also fail on other lint warnings, such as usage of ˋ...ˋ instead of ellipsis character in incoming translations. I gues this is a matter of configuration but I have no clue how this works.
