### ISSUE TITLE
testGeocodeCaseInsensitive failing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10183]
Happening in https://ci.cgeo.org/job/cgeo%20pull%20request/5106/ for PR #10180 
```
org.junit.ComparisonFailure: [Old cache] expected:<null> but was:<TEST >
at cgeo.geocaching.storage.DataStoreTest.testGeocodeCaseInsensitive(DataStoreTest.java:162)
```

**Comment by Lineflyer** [comment]
After retest its no longer failing...seems not reproducible or bound to some slave?

**Comment by moving-bits** [comment]
still relevant?

**Comment by fm-sys** [comment]
I guess we can close, the failing test was only a one-time-issue...
