### ISSUE TITLE
"Mars Perseverance Rover Trackable" does not come up in "Trackable" search

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#10192]
**Describe the bug:**
Mars Perseverance Rover Trackable does not come up when searching for a trackable with the trackable code [REDACTED]. But it works when you enter the trackable reference number TB5efxk.

See https://www.geocaching.com/track/details.aspx?tracker=TB5efxk

**To Reproduce:**
1. Open app
2. Go to "Search"
3. Scroll down to "Trackable"
4. Enter [REDACTED], hit enter
5. No result

**Actual behavior/state after performing these steps:**
All normal, the trackable was just not found.

**Expected behavior/state after performing these steps:**
I expect the https://www.geocaching.com/track/details.aspx?tracker=TB5efxk to come up for me to be logged.

**Version of c:geo used:**
2021.02.14

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: GM1913 (OnePlus7Pro_EEA, OnePlus)
Android version: 10
Android build: GM1913_21_210128
c:geo version: 2021.02.14
Google Play services: enabled - 21.06.13 (120400-358943053)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_US / user-defined language: 
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (181.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (181.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (181.4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (840.0 KB) on system internal storage
Last backup: never
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/Maps
Map render theme path: /storage/emulated/0/Maps/MapThemes/Elevelo_Cycling.xml
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---
```

**Comment by eddiemuc** [comment]
Well, no way to analyze this without reading the code. So I now logged the mars trackable.

Anyway, the problem is quite clear: currently c:geo only handles TravelBug-Codes which conform to the following regular expression:

`(TB[0-9A-Z&&[^ILOSU]]+)|([0-9A-Z]{6})|([0-9]{5})`

And the code above fails this expression.

Question: how was this RegEx originally created? Can it safely be extended to conform also to longer codes?

(See class `cgeo.geocaching.connector.trackable.TravelBugConnector`)

**Comment by Lineflyer** [comment]
In fact, this is the first tracking code longer than 6 characters IMHO.
I guess GC created this exception as this tracking code had to be taken as is (assuming the calibration target was not produced with that code as a tracking code, but his original purpose is another one).

**Comment by fm-sys** [comment]
> I guess GC created this exception as this tracking code had to be taken as is (assuming the calibration target was not produced with that code as a tracking code, but his original purpose is another one).

In fact, it was more or less only created as trackable. But the trackable code is not only a random number, but the abbreviated address of sherlock holmes. However, I suspect that such tracking codes will only be a very rare exception.

![grafik](https://user-images.githubusercontent.com/64581222/111641442-738c9200-87fd-11eb-961c-8388f330b0ed.png)

BTW, should we remove the "spoiler" from the original comment?

In any case, a new release will still take quite some weeks. I believe that all interested should have logged the trackable by then and a change of the regex will not be worth it.

**Comment by ControlTheBit** [comment]
@fm-sys I have removed the spoilers from my original post and I do agree with you. It's probably not worth fixing the regex.

I would recommend though that the error message appears differently. Right now it just says "No trackable found" or something like that. That suggests that the search has been submitted to geocaching.com and no result came back.

It should rather say something along the lines of "Code is not in the valid format".

**Comment by fm-sys** [comment]
Or what about "seams not to be a trackable"?

**Comment by ControlTheBit** [comment]
"Doesn't look like a trackable code?"

**Comment by bekuno** [comment]
> 
> 
> "Doesn't look like a trackable code?"

Not possible. In the search field we do not distinguish between tracking code and trackable number.

I would leave it as it is.
