### ISSUE TITLE
Handling of Personal Cache Notes Data

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#10193]
Not sure whether the following is really a "bug" or rather a matter of software design. I start with a bug, however, I need to establish some context first. (Earlier I had opened a related issue, but that was exclusively focussing on waypoint extraction, so I don't consider the following a duplicate):

It is about the semantics of the Personal Cache Notes (PCN) of a geocache. From my perspective the database at geoaching.com is the one and only authoritative source of information related to geocaches. I use multiple clients, one of which is cgeo, to retrieve this data from the server. When a geocache is loaded from GC.com's servers, the PCN field should be taken as is and not modified at all. Since the content is free form text it should not be parsed for any information and nothing should be extracted from it, e.g. no waypoints. The same is true when a geocache is "refreshed". What comes from the server should be taken verbatim and there shouldn't be an attempt made to merge the downloaded information with what might already be in the local database. If I make a local change to the PCN and subsequently click the upload button, the full content of the PCN field should go up and replace what's up there. This is the most basic logic and it should be the default. If there are any smarts implemented in a client such as merging old content with new content, this should be the user's choice via opt-in.

I know that waypoint extraction can be turned off since a while. What strikes me is the following scenario:

I download a cache from GC.com, persist it in cgeo. It just happens to be that some PCN data comes with the download. If I now use a different client, or go to GC.com website and make a change in just a single character in the PCN field of subject cache, and then refresh that cache in cgeo, the PCN content that comes from the server is compared with the PCN content in cgeo and if there is not a 100% match, the new data from the server is concatenated to what cgeo already has. Let's assume I have an 800 character text in there explaining the solution for a mystery and then I change a single typo in that text on the server side, refresh the cache in cgeo, I have now 1600 characters in the PCN field in cgeo, separated by "--". The only difference between what is above the "--" and below the "--" is the single character I changed on the server side. If I make another change on the server side, refresh to cgeo again, I have three copies of the data in cgeo, separated by "--" and so on an so on.

If I now press the PCN upload function on cgeo, I have all these copies up there on the server and it get's worse with every change I make on the server side and then refresh to cgeo.

If a user wants that behaviour, he/she should have an opt-in choice to enable, e.g. "Enable smart processing of PCN data" . Since a lot of this is already implemented, I think it wold also work if I had an opt-out choice deselecting any processing of the content of the PCN field. (Of course I want to be able to make changes of that field via the Edit capability but if I do not upload those changes and refresh the cache from the server instead, my expectation is that my changes are lost entirely and I get exactly what's on the server and no less and nothing in addition)

I don't see a way how to rectify this problem. I had assumed if I deleted the subject geocache from cgeo, then look it up again, there would be no residue on cgeo's side and then I was surprised to see that all the 4 copies of the PCN data was STILL persisted somewhere in cgeo, most likely in what is called the "cace cache" in cgeo.

In CacheDetail at the bottom, under the Personal Cache Notes, there are four icons. Two on the left, two on the right. The second from left has a trash can symbol above the drop shaped icon so I'd considered this some sort of delete and I had futher assumed clicking on it would make cgeo forget everything it believes it knew from the cache but what happens is entirely something different. Pressing this button made cgeo parse all the data in the PCN with the intent to remove waypoints it had previously extracted (in this case there were none), and then it persists the full cache listing in the "Stored" list of my device. Of course it has all the 4 copies of the PCN data in it.

So in essence I do not see any way how I could get rid of this data other than manually go into PCN Edit, do a select all followed by "cut" then save, and then do a refresh from the server.

On the side, and maybe this deserved sesparate issue or could be combined with https://github.com/cgeo/cgeo/issues/10125#issue-824740265:

In detail view of a cache that I had previously stored in cgeo, but now removed from any list, if I press the "remove extracted waypoints" icon tha cache is locally stored in the "Stored" list again, which is unexpected especially since no changes are made at all. I have gobally disabled waypoints extraction anyway and I have not manually extracted any waypoints either. Let me know whether you want me to add this side effect or additional information to the issue referenced above.

**Comment by baiti** [comment]
For those who are not interested in the usecase and the rationales, disregard my initial post. Here is as brief as possible what the proposal is:

1. Upon initial loading of a geocache from the server, take the string that comes in the PCN field verbatim and store it in the corresponding property of cgeo's local geocache object. (Do not postprocess or interpret that string in any way).

2. Upon refreshing a previously loaded geocache from the server, take the string that comes in the PCN field verbatim and store it in the corresponging property of cgeo's local geocache object. (Do not postprocess or interpret that string in any way. If some data already was in that property, ignore it, replace that data with what comes from the server).

3. If I elect to upload personal cache notes, regardless whether I have edited it or not, upload the string as is and replace what might be on the server.

If cgeo decides to offer additional, enhanced functionality, make it a user selectable choice to enable those additional functions. For use case and rationales, see the initial post.

**Comment by Narrat** [comment]
Whatever way this discussion is going, one case needs to be covered: Basic members.
If they make notes, it shouldn't be deleted if they refresh the cache, because of an likely empty or "user-cannot-use-this-feature" response from the server.

**Comment by baiti** [comment]
> Whatever way this discussion is going, one case needs to be covered: Basic members.
> If they make notes, it shouldn't be deleted if they refresh the cache, because of an likely empty or "user-cannot-use-this-feature" response from the server.

Interesting thought. I never used cgeo with a basic account. It seems that cgeo provides functionality to basic users which is not available to basic users using the website or using the geocaching app on their phones (or any Live API enabled app). This is an aspect of this subject I won't drill down in any more details here but it has to be in our mind in case we pursue certain routes in the future. And we need to keep this in mind even if we turn down the proposal I am addressing here in this issue.

To cover that case in the context of my proposed design point, such a user would go into Settings/Preferences and enable "Smart processing of Personal Cache Notes" oder something similar.

As stated in my initial post, it would also be ok to leave everything as it is and provide a Settings / Preferences choice to opt-out from any such processing.

**Comment by Lineflyer** [comment]
> It seems that cgeo provides functionality to basic users which is not available to basic users using the website or using the geocaching app on their phones (or any Live API enabled app). 

That not correct for the case of PCN. Basically its a c:geo internal personal note field which happens (for PM) to be able to upload/sync with the server (as its has such feature for PM). For BM its plainly an internal feature.

Regarding the generic issue:
The sync mechanism was implemented and finetuned based on users vote and feedback. We rarely get any complaints about its current mode of operation. Of course, there might be corner cases (like you mentioned with a PCN >50% of max length, which is changes on server side resulting in the "doubled" PCN not having enough room and getting truncated). But in general I believe the feature is nice as it currently is....I will take some time on the weekend to read your posting in more detail and get a final personal opinion on this.

**Comment by baiti** [comment]
> > It seems that cgeo provides functionality to basic users which is not available to basic users using the website or using the geocaching app on their phones (or any Live API enabled app).
> 
> That not correct for the case of PCN. Basically its a c:geo internal personal note field which happens (for PM) to be able to upload/sync with the server (as its has such feature for PM). For BM its plainly an internal feature.

Ok, relief here.

> 
> Regarding the generic issue:
> The sync mechanism was implemented and finetuned based on users vote and feedback. We rarely get any complaints about its current mode of operation. Of course, there might be corner cases (like you mentioned with a PCN >50% of max length, which is changes on server side resulting in the "doubled" PCN not having enough room and getting truncated). But in general I believe the feature is nice as it currently is....I will take some time on the weekend to read your posting in more detail and get a final personal opinion on this.

I have no doubts that this is a nice feature and probably used by many. I am essentially just proposing to make this feature optional, just don't force a user into it. It severly hampers my workflow as soon as more than one client communicates with the server in which case things get out of sync rather quickly.

**Comment by baiti** [comment]
For completeness: Basic user's wouldn't be impacted if the proposal gets implemented in the way I described it as there is no download from the server, no refresh from the server and no upload to the server, right?

**Comment by moving-bits** [comment]
Just for the record: I'd like to keep the sync feature. I'm adding notes to either web page or within c:geo, depending on what's available at that time, so I need some sort of sync. Also I'm not always able to to a sync directly, so at the time of reloading a cache I may already have forgotten that I entered some note locally - another reason for a reliable syncing.

I could live with syncing being made optional, but "ON" should be the default state in that case to not break existing behavior.

**Comment by baiti** [comment]
> Just for the record: I'd like to keep the sync feature. I'm adding notes to either web page or within c:geo, depending on what's available at that time, so I need some sort of sync. Also I'm not always able to to a sync directly, so at the time of reloading a cache I may already have forgotten that I entered some note locally - another reason for a reliable syncing.

Is it really reliable syncing? Assume the following:

I edit the PCN directly on the website to: (note: in my case I don't do this manually, it is actually an application triggered by Locus Map's Multi Cache Solver plug in that does that)

`the number of trees: A = 17`

Then I do a refresh of the cache in cgeo. Since no PCN were stored before, cgeo shows:

`the number of trees: A = 17`

Now my other app goes to the website and change the PCN to:

`the number of trees: A = 19`

On cgeo I do a refresh and the PCN read:

`the number of trees: A = 17`
`--`
`the number of trees: A = 19`

If I now change my mind, and my other app goes to the website and changes it back to what it was:

`the number of trees is really: A = 17`

The do the refresh on cgeo, I will end up with:

`the number of trees: A = 17`
`--`
`the number of trees: A = 19`
`--`
`the number of trees is really: A = 17`

And this goes on and on and on. And if at some point in time I press the "upload PCN" from cgeo, I have the whole mess on the server side too. Another refresh on cgeos side then would double the problem. It quickly winds up to the point where geocaching.com's size limit on PCN kicks in.

I guess it boils down to realizing and accepting that there is only one authoritative source for that kind of information and that is the database in geocaching.com. Whatever client application is used, it can only hold a local copy of that data and if it wants to make changes to that local copy it must persist those changes on the server side too. If it doesn't, and reloads from the server, the local changes are gone for good. That is the standard semantics in any distributed computing environments.

You might ask: Why is he doing the refresh on cgeo then all the time: Well, with each change driven by the app triggered by Locus Map's Cachesolver I also get new corrected coords on geoaching.com and the refresh in cgeo gets me the new corrected coords which I would then use to guide me to that location.

> 
> I could live with syncing being made optional, but "ON" should be the default state in that case to not break existing behavior.

Agree

**Comment by wfrey-bc** [comment]
Interesting reading and discussion and something I experienced as well multiple times - when using Locus Map, c:geo, GSAK and gc.com website in combination - however I never spent the time to dig into the details what might be the source of growth of PCN data. 
Having an option to opt out from the cgeo style of PCN sync processing would be great. Thx

**Comment by MagpieFourtyTwo** [comment]
My 2 cent: *Adding* server side PN to the local PN, if they differ, is an absolute must have, at least in Real Life. ;)

Our usecase:
- When doing complex Multi/Mysterys we usually prepare it at home and aggregate the listing into the PN,
to have the crucial stuff stage by stage at hand, when we need it.
- While doing the cache outside, we of course edit the PN, add results, coords, etc,
- *BUT* can not always immediately upload the changes to the server,
cause (as we're in high tech Germany) very often there is just poor or even no network coverage at all.
- arriving at the final, it is sometimes helpful to refresh the listing ...
- but if you forgot to first upload the PN (or were not able to do so up to this moment),
an imprudent refresh would kill the work of the last hours within the fraction of a second ...

Admittedly, PN sync has it's caveats, but no matter how uncomfortable they could be,
they should never be a reason, to trash manually changed information.

BTW: I never ever had more than two PN version. And, rest assured, I messed around with it *a lot.*

And perhaps a hint for PN handling: To fetch a "clean" version of the server side PN into cgeo, just delete all text from cgeo's PN and do a cache refresh afterwards. This you can do even after you got the doubled version, cause on server side there is still one version, in your usecase. To rest assured PN is really cleared in cgeo it may sometimes be necessary to clear the PN content twice, but this happens really seldom.

**Comment by baiti** [comment]
> My 2 cent: _Adding_ server side PN to the local PN, if they differ, is an absolute must have, at least in Real Life. ;)

I never suggested that this functionality should be removed. Let us just  make it a user's choice to disable it.

> 
> BTW: I never ever had more than two PN version. And, rest assured, I messed around with it _a lot._

I recently had 4 ... You'd need to understand my workflow in order to appreciate the pain. My workflow is extremly optimized ;) It is not a secret but sharing it would most likely not make a difference when it comes to decision making whether the proposal gets implemented or not. Let me know if you think otherwise and I share it.

> And perhaps a hint for PN handling: To fetch a "clean" version of the server side PN into cgeo, just delete all text from cgeo's PN and do a cache refresh afterwards. This you can do even after you got the doubled version, cause on server side there is still one version, in your usecase. To rest assured PN is really cleared in cgeo it may sometimes be necessary to clear the PN content twice, but this happens really seldom.

This is exactly what I do. Should my proposal be implemented and I can opt out of any smart processing or syncing, this would save me the effort to clear out what cgeo has and do a refresh from the server. I wouldn't mind doing it once in a whlle but on a long tour and 40 found caches, going into all 40 caches in detail, clearing out the PN, refreshing the caches, that is annoying and error prone.

**Comment by Lineflyer** [comment]
@baiti 
I tried to follow the thread and the changes referenced.
It seems this is implicitly solved by having the ability to turn off PCN merging. Correct, so we can close here?

**Comment by baiti** [comment]
Yes ... all good the way it is now.
