### ISSUE TITLE
Lint: Clarify unused ressources

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10190]
Related to #8129 but not covered there (as that issue deals about errors rather than warnings):

The following warnings exist in lint regarding unused ressources (preference keys or drawables):
- The resource `R.drawable.dot_transparent` appears to be unused
- The resource `R.drawable.ic_menu_dot_mode` appears to be unused
- The resource `R.drawable.ic_menu_trail` appears to be unused
- The resource `R.layout.gpx_item` appears to be unused
- The resource `R.string.pref_map_direction` appears to be unused

It should be checked and resources removed accordingly or added to the lint ignore list (if false positive).
Source:
https://ci.cgeo.org/job/cgeo pull request/5121

**Comment by eddiemuc** [comment]
If wanted, we can now make build fail on more lint findings simply be setting their security from warning to error. Alas, I assume in case of unused resources this would mean that a developer, when he removes a resource, he has to manually remove it in all strings.xml (for all translations) to be able to get a PR to green

**Comment by bekuno** [comment]
> Alas, I assume in case of unused resources this would mean that a developer, when he removes a resource, he has to manually remove it in all strings.xml (for all translations) to be able to get a PR to green

No worry about this. Fortunally we can use ` <ignore path="res/values-*/strings.xml" />`
as for `<issue id="UnusedResources">`.
