### ISSUE TITLE
App slow to start AboutActivity

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10209]
Taken from a comment of the beta version survey:

When trying to access "About c:geo " in main menu or clicking the small c:geo logo in the title of the main screen, the screen turns black and it takes some seconds until the "About" screen is shown.

---

I can sort of reproduce it: For me on my (pretty fast) Samsung S20 the screen does not turn black but there is a significant delay (at least on first try during a session).
From my feeling: Could it be related to the information gathering for the "System information" screen?. Could be, it takes some time to populate all the settings output?

**Comment by eddiemuc** [comment]
Yes, most probable this is from gathering System Information. More precise: System Information gathering scans all public folders to collect number of files/dirs inside it. I was not aware that this creates a noteable delay though - maybe when using SD card?

Anyway,- I can remove this scan of course although I really like to have the information

**Comment by moving-bits** [comment]
Is there a way to delay gathering this information until about:system page is being displayed?

**Comment by eddiemuc** [comment]
I guess this can be done in a background thread

**Comment by Lineflyer** [comment]
I have to enhance my initial posting a bit:
There is the delay on starting "About", but there is another delay (hanging) when finally swiping from "Changelog" to the "System information" tab. So I am no longer sure, what information collection or task is started at which point of time.

**Comment by moving-bits** [comment]
Just looked into the code: On startup of `AboutActivity` it connects to BRouter and initializes all subpages.

**Comment by eddiemuc** [comment]
> I have to enhance my initial posting a bit:
> There is the delay on starting "About", but there is another delay (hanging) when finally swiping from "Changelog" to the "System information" tab. So I am no longer sure, what information collection or task is started at which point of time.

Checked code: SystemInformation is actually gathered twice inside AboutActivity: once for display in the "System information" and another time (on starting "About") to put it into an email in case the user clicks support email link

Will unify this into one call and put it in a background thread.

**Comment by eddiemuc** [comment]
PR #10222 should fix this
