### ISSUE TITLE
Include active map in system information

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10200]
For many issues its relevant for the support to know, whether the user uses Google or Mapsforge. Additionally it might sometimes helpful to also see how he uses Mapsforge (Which online tile provider / name and provider of offline map).
Currently this always requires some mail ping-pong.

So I suggest (if possible) to add two line to the section "Program settings", showing up like the following examples:
Active map type: Google Maps / Google Satellite / openstreetmap.org /openstreetmap,de / ... / Offline map
Offline map name: germany_oam / Provider: OpenAndroMaps 

For offline maps the map name should be as shown in map selector (file name without extension). If possible map provider would be nice (taken out of the attribution maybe?), but could also be omitted (as I do not know of any bug up to now depending on map file provider)

**Comment by eddiemuc** [comment]
I suggest to also add selected map theme (if any) while we're at it

**Comment by eddiemuc** [comment]
PR #10222 should fix this
