### ISSUE TITLE
Font size to large in installation/migration wizard

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10216]
Taken from Google Play Beta Feedback for 2021.03.16-RC1:

Schrift im neuen Asistenten ist etwas groß geraten. Es muss bei mancher Seite gescrollt werden. Viele dürften alte kleinere Hsndys mit cgeo verwenden da müssen sie noch mehr scrollen.

Translate:
Font in the new wizard is a bit big. Some pages require scrolling. Many user might have older smaller phones, they have to scroll even more.

**Comment by fm-sys** [comment]
I noticed the same thing (and I thought I'd mentioned it somewhere before?)

So +1 for smaller font size from my side

**Comment by moving-bits** [comment]
I had intentionally chosen relatively large font sizes to make the first impression of c:geo a bit more user-friendly. (c:geo in general uses way too small font sizes, from a UX perspective at least.)

Anyway, I can decrease both title and text font sizes a bit, e. g. by 2sp each.
But there will always be display sizes where the text will not fit into one screen, depending on text length, language, screen size and system font size.
