### ISSUE TITLE
Filter on extension *.gpx for loading a GPX

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10226]
From support mail for 2021.03.20-RC:

When loading a track onto the map or importing a GPX this system file selector opens. On my device it looks messy...large icons and truncated file names. Isn't it possible only to show files with extension GPX in such cases?

---

Note from my side:
GPX import for caches does also support *.LOC, so beside GPX it should also show *.LOC if its possible after all to limit by extension.

**Comment by eddiemuc** [comment]
As far as I know, selection can only be limited by mime types, not by File extension. If this is the case, then which mime types shall be allowed?

**Comment by SammysHP** [comment]
Isn't the GPX import also handling pocket queries? Thus it's also zip and ggz.

IIRC we had a long discussion about this in the past and experimented a lot with the filter config.

**Comment by moving-bits** [comment]
Just for clarification: We have different filtering systems at hand:
1) If you tap on a file in your preferred file manager, this file can be opened by c:geo. So the file is "brought to c:geo" from "the outside". The criteria for this are in `AndroidManifest.xml` and we had a hard time to find some filtering that works across the supported wide range of Android versions, as each seems to behave a bit differently here.
2) Then you can open a "file selector" from within c:geo to import a GPX file with caches, or a track etc.
3) A third use-case is opening a pocket query, but here filtering is done already on server-side. No file system file selector involved.

I guess @Lineflyer is referring to the 2nd case, where a c:geo-induced file system file selector is involved.

Technically, our GPX import internally accepts GPX, ZIP, LOC, GGZ (and maybe others, not sure), but this is AFTER a specific file has been selected.

**Comment by eddiemuc** [comment]
Checked documentation again, I do not see a possibility to filter for file extensions in ACTION_OPEN_DOCUMENT intent (this may be because technically what you open there may not even be a file), in contrast to intent filters in Manifest where you can specify a pathPattern.

This leaves filtering via mime types. Anyone knows how this may be used to filter effectively (and stable across supported Android versions as well as vendors) the above mentioned file types?

I googled a bit and found class `MimeUtils `which seems to contain the Android's systems mapping between file extensions and mime types. Alas, gpx is not listed there:

https://android.googlesource.com/platform/libcore/+/refs/tags/android-9.0.0_r49/luni/src/main/java/libcore/net/MimeUtils.java

**Comment by moving-bits** [comment]
AFAIK neither GPX nor GGZ or LOC have standardized mime types at all, not to speak of standardized mime types across different Android versions. 
Not even for ZIP files (although there are _some_ mime types for it), and even if there were a mime type for ZIP, it could not distinguish which mime type is included within the ZIP (e. g. pocket query vs. map theme vs. OSM map).
So I guess we have to stay with displaying all files, let the user decide (and check within c:geo whether their choice was reasonable).

**Comment by Lineflyer** [comment]
> AFAIK neither GPX nor GGZ or LOC have standardized mime types at all, not to speak of standardized mime types across different Android versions.

Yes, thats also what I remember. So I suggest to close this with "Wont fix" for now. The file selector should open in the directory the user has setup as GPX directory (or uses the default /cego/gpx). Thats probably all we can do.

Regarding the first case:

> If you tap on a file in your preferred file manager, this file can be opened by c:geo. So the file is "brought to c:geo" from "the outside". The criteria for this are in AndroidManifest.xml and we had a hard time to find some filtering that works across the supported wide range of Android versions, as each seems to behave a bit differently here.

I also recently found problems here on my device. For a  GPX which I received via mail c:egeo is no longer offered to open it with. Just Locus and other GPX related apps I have. But thats a new issue (will open it after rechecking).

Feel free to close here.

**Comment by Lineflyer** [comment]
Addon:
Just realized on my device, that while List - Menu - Import GPX opens the file selector in /cgeo/gpx, the file selector for GPX-Track loading (Map - Manu - GPX-Track/Route - Load GPX-Track/Route) does start at some other folder (probably the last used?).

Does it make sense to let it start at the defined GPX folder isntetad...or does this even more confuse as we are talking about different contents/use cases of GPX files?
