### ISSUE TITLE
Problem in Android WebView causing c:geo to crash

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10249]
For your information:
There was a burst of people reporting c:geo crashes when trying to open any cache two days ago.
I was a bit clueless first, but luckily one user sent us an update:

There seems to be major problem with the WebView component from Google last days (found some articles on the internet) which leads to problems in various apps.

The user confirmed, that after updating the WebView component/app via Google Play this morning fixed the issue for him.

**Comment by jonas-koeritz** [comment]
Can confirm. WebView killed a bunch of apps. This is definetly not our problem.
