### ISSUE TITLE
Have filter for cache status = Active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10259]
From support mail:

**Is your feature request related to a problem?**
I had a list of caches by an owner, which also contained deactivated and archived caches and I wanted to take a look at only the active caches.

**Describe the solution you'd like**
The filtering contains filter for Status=Archived and Status=Deactivated but however no filter for Status=Active. This should be added.

**Describe alternatives you've considered**
I could filter deactivated and archived one by one and move those caches to another list to keep the active ones, but in fact I don't want to modify the list. Just filter on the active caches.

**Additional context:**
Ticket # 773622

**Comment by moving-bits** [comment]
Just a small note to @eddiemuc: There are a couple of issues regarding filtering/searching, some of them older, others pretty new. I'm not actively searching for them currently, but whenever I encounter one by pure chance, I'll add the issue to the "Filtering / searching" project for a better overview. That does not imply any "must have" or even "must be done by you" by any means, though, it's just for reference.

**Comment by eddiemuc** [comment]
@moving-bits please continue this and thank you! Its good to have them all in one place to comb through

**Comment by eddiemuc** [comment]
Solved with #9081
