### ISSUE TITLE
Make (map) download receiver non-blocking

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10256]
Even if the downloader is great, the "ReceiveFileActivity" is a bit unexpected for end-users.

Therefore I would like the whole copy thing to be done either as a background service or downloading directly in the correct folder so no copy would be necessary at all. 

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10246#issuecomment-806436229_

**Comment by moving-bits** [comment]
From what I have found so far in Android docs and SO, it looks like setting a destination folder for the download manager only works with paths/files, not with SAF Uris.

- https://stackoverflow.com/questions/35339034/android-download-manager-issue-with-uri-from-storageaccessframework-as-destina
- https://stackoverflow.com/questions/28092758/issue-with-storageaccessframework-and-downloadmanager
- https://developer.android.com/reference/android/app/DownloadManager.Request#setDestinationUri(android.net.Uri) (and other `setDestinationXXX` methods)

**Comment by fm-sys** [comment]
I've started coding a background service as download compete receiver. the only thing that bothers is the dialog whether to overwrite the file. Ideally processing the downloaded file should be done completely without user interaction. Is there a way to check the file name before starting the download or should we even simply always overwrite files?

**Comment by moving-bits** [comment]
That's cool! But beware, if you're going to become the "master of background services", then other challenging tasks will await you, e.g. #7057 or #1605/#330 :-)

The filename of the file-to-be-downloaded is stored in the `PendingDownload` (IIRC), and the specific downloader knows the target folder as well, so checking for overwrite is possible at that stage (with the risk that something changes in between).

There can be another user-interaction at the end of a download: On downloading a map which requires a theme file (e. g. OpenAndroMaps and Freizeitkarte), their specific downloader will check whether this file already exists, and if not, will ask the user whether to download and install it as well.

(But using a background service for copying the file does not necessarily mean that you can't interact with the user. You can start a new activity for it, if necessary, as it's done currently.)

**Comment by fm-sys** [comment]
> But using a background service for copying the file does not necessarily mean that you can't interact with the user. You can start a new activity for it, if necessary, as it's done currently.

I know, but it's strongly discouraged in the design guidelines. Rather than a activity, a notification would be the way to go (However, with the risk that this is not taken into account so not really sufficient for map download.)

I also don't know if it will ever get good results (Huawei devices are making quite much trouble with background services). It is therefore more intended as a test attempt... But let's see, maybe it's good enough?
