### ISSUE TITLE
c:geo checkstyle.xml usage under Windows: locally use crlf instead of lf without impact on git content?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10269]
Since a few weeks I have problems applying checkstyle.xml locally in Android Studio. It gives me the following warning for ALL files (which renders the whole usage pretty useless because I can't see the real problems between all these warnings):

![image](https://user-images.githubusercontent.com/6909759/112723377-6f9ff480-8f0e-11eb-814a-dfc73e3cbd68.png)

So I created my own local checkstyle.xml where I exchanged expected line separator `lf `with `crlf`. This works fine.

However, it occurs to me that the AS-file where this setting is saved (`.idea/checkstyle-idea-xml`) is checked into git. I cannot really check this in of course because it is a local setting specific for Windows users like me.

So my question is: how to solve this? And why is the above file (with local settings) even part of git?

**Comment by moving-bits** [comment]
Same here. I guess this happens since #10170, coming from the included CheckStyle 8.30-fix for issue https://github.com/checkstyle/checkstyle/issues/4074.

**Comment by bekuno** [comment]
This fix could possibly be the reason as we updated from version 8.26.
Let's remove the "LF" check. This was added in #7904 to have better warnings. Hopefully this will no longer be necessary after the checkstyle update.

**Comment by bekuno** [comment]
> However, it occurs to me that the AS-file where this setting is saved (`.idea/checkstyle-idea-xml`) is checked into git. I cannot really check this in of course because it is a local setting specific for Windows users like me.
> 
> So my question is: how to solve this? And why is the above file (with local settings) even part of git?


The file `.idea/checkstyle-idea.xml` configures the AS checkstyle using.
~~~
        <entry key="active-configuration" value="PROJECT_RELATIVE:$PROJECT_DIR$/checkstyle.xml:cgeo" />
        <entry key="checkstyle-version" value="8.41" />
~~~
In this way all developer use the cgeo checkstyle config in the same version.
It is part of the c:geo code since 5dbc1eb088a92d46dcb2ea418f59688b6c9910d3 .

**Comment by eddiemuc** [comment]
Works perfect again, thanks a lot!

I still don't understand the motivation of keeping one of the many AndroidStudio/idea config files in git. I thought it is common practice NOT to check in local Developer Tool settings into source control.
