### ISSUE TITLE
"Mark as found" (only visible to oneself) feature

### ISSUE THREAD

**Issue by GitMoleo** [cgeo/cgeo#10280]
### Is your feature request related to a problem?
I recently switched to c:geo from an other app. As far as I know, there is no "import caches" feature or something similar. If there is, please comment how to do this on this issue. Normally one could simply log in with the account used before, but unfortunately I have lost my old account.

### Describe the solution you'd like
A "Mark as found" button in the cache menu.
So basically the same as a normal log, but local only, without posting it, just visible to oneself. This has the great advantage that one can quickly identify caches that have already been found (on the old account) from those that haven't.

### Describe alternatives you've considered
Until now I wrote "Found" in the personal notes, but that isn't a good solution in the long run.
**Since I lost my old Account, it would be nice to have a feature to sort of copy all logs from a specific user, but, of course, again visible only to oneself.**

Quick Overview | (Summary)     
----------- | ------------   
*Problem*     |   no way to "import" logs from old account
*Solution*     |   "Mark as found" button in cache menu
*Alternatives*|    feature to "copy" all logs from a user (only local)

**Comment by fm-sys** [comment]
Why don't you simply reset the password for your old account? 

Another idea would be to set "😀" as user defined cache icon for all already found caches...

**Comment by moving-bits** [comment]
Or, if you are using GSAK, you do export a GPX from that, and import it into c:geo (see cache list, import, import GPX).

**Comment by MagpieFourtyTwo** [comment]
There already exists a GSAK macro to "copy" logs from another user, which is usually used when two players, who used one account so far, decide for whatever reason to go on with separate accounts. 

Apart from that I am going to open a feature request for filtering out caches with offline logs, which may help in your situation too, just in case you don't want to dive into GSAK.

**Comment by moving-bits** [comment]
@GitMoleo 
Did any of the proposed solutions work for you / can we close this issue?
