### ISSUE TITLE
Nightly: Download of current nightly just gets yesterday's version

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#10288]
Just tried to install latest nightly, which is listed as "2021.03.29-NB-5453fd2" in dev status,
but after downloading and updating via click on c:geo's notification banner,
the banner is still there and the version is still reported as "2021.03.28-NB-31d79d7" ...

**Comment by fm-sys** [comment]
For me everything was ok. Does the problem still occur?

**Comment by MagpieFourtyTwo** [comment]
Today it's ok again.
