### ISSUE TITLE
Add attribution for Brouter to About c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10292]
According to https://github.com/abrensch/brouter/blob/master/LICENSE we should add an attribution / copyright notice to c:geo now, that we have integrated this code.

`Copyright (c) 2019 BRouter contributors`

**Comment by moving-bits** [comment]
likes this?

![image](https://user-images.githubusercontent.com/3754370/112892252-631bc780-90d9-11eb-932a-894a454a16c9.png)

(additionally we have attribution in the source code)

**Comment by Lineflyer** [comment]
I would stay with the text provided in their license, like:

- Integrated routing: Copyright (c) 2019 BRouter contributors

**Comment by fm-sys** [comment]
I would leave out "Internal", as in fact also external routing uses BRouter ;-) 

So maybe: `Routing © 2019 BRouter contributors (MIT)`

That's a bit shorter and contains the license as well...

**Comment by eddiemuc** [comment]
Stupid question: since we are not just taking over BRouter but also modify it (over time maybe even substantially): 
* Is this allowed by their license?
* Does this have to reflect somehow on the license naming (e.g. adding "modified by c:geo team" or something like this)?

**Comment by Lineflyer** [comment]
As far as I understand the above license text (see link) its clearly allowed to modify the code (and even to commercially use it). The only condition is the attribution to the original code.
I am however no license expert, but it sound quite clear in the MIT license text.
