### ISSUE TITLE
Don't shift map to GPS position

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#10308]
**Describe the bug:**
With "not center map to gps position" map is centered to gps position when switching maps.

**To Reproduce:**
1. Switch off "center map to gps position" 
2. Choose Google Sat
2. Chose location by shifting map by draw with finger
3. Change to OSM Offline map

**Actual behavior/state after performing these steps:**
1) Map is changed and "center map" is activated (point in circle). Map is centered.
2) "center map" is deactivated and map stays at GPS position

**Expected behavior/state after performing these steps:**
No movement of map

**Version of c:geo used:**
2021.03.22-NB1-0dccd81

**Is the problem reproducible:**
Was, but not always with that sequence

**Additional context:**
I observed this with earlier version too. But this time I could clearly see the dot in the circle appear and disappear.

**Comment by geocachermgo** [comment]
While making experiment to get a 100% reproducable sequence I also experienced that "center map" was switch on, and stayed on when changing from GSat to OSM Offline

**Comment by fm-sys** [comment]
Can confirm, but only when switching step 1) and 2)


- Switch on "center map to gps position"
 - Choose Google Sat
- Switch off "center map to gps position"
- Chose location by shifting map by draw with finger
- Change to OSM Offline map

**Comment by MagpieFourtyTwo** [comment]
Same for me: Although I can not reproduce @geocachermgo's scenario, @fm-sys's "works" the same way over here, i. e. map position is changed unexpectedly when switching from GSat to OSM.

**Comment by geocachermgo** [comment]
fm-sys sequence is reproducable for me too.

**Comment by Lineflyer** [comment]
Let continue in #12768
