### ISSUE TITLE
Map loading & refreshing are really slow under SAF version.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#10300]
**Describe the bug:**
I just been out geocaching for the first time after installing the 'SAF' version (i.e. I went through the "File-selection wizard"), map loads and refreshes are really slow.

It was most noticeable in two circumstances,

1) Went returning from the 'Cache details' page to the map. I tap the back-arrow and on many occasions thought nothing was happening and tapped it again. When it responds, it then goes right back to the 'Six tiles' screen.

2) After locking the phone while the map was on display.  When unlocking it, the previous map is displayed for several seconds before refreshing to your new location.

It seems to be quite a step backwards in performance for the App.

I'm using OSM V4 maps stored offline and the 'Elevate' theme.
All caches are stored offline.

**Version of c:geo used:**
2021.03.28-RC

**Is the problem reproducible:**
Yes 

**System information:**
```
--- System information ---
c:geo version: 2021.03.28-RC

Device:
-------
- Device type: SM-G960F (starltexx, samsung)
- Android version: 10
- Android build: QP1A.190711.020.G960FXXSFFUB3
- Sailfish OS detected: false
- Google Play services: enabled - 21.06.13 (120408-358943053)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: archived
- Hide waypoints: -
- Set language: en_GB (system default)
- System date format: dd/MM/y
- Debug mode active: no
- Live map mode: false
- Global filter: display all caches
- Last backup: 30 Mar, 19:11
- Routing mode: Off
- Map: Great_Britain_OAM_V4_Mar2021 (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:OpenStreetMaps/Great_Britain_OAM_V4_Mar2021.map
  - Atts: Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2021
  - Theme: ElevateTheme/Elevate.xml

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
- Geocaching.com date format: dd MMM yy
- BRouter installed: false / connection available: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (3.1 GB free) v2 internal isDir(8 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (3.1 GB free) v2 external non-removable isDir(4 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (3.1 GB free) v2 external non-removable isDir(1344 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (3.1 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
  - BASE: /cgeo (User-defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:11, dirs:9, totalFileSize:129.2 MB, topLevel(4):[backup/;logfiles/;field-notes/;GeocachePhotos/], free space: 3.1 GB, files on device: 1740800)
  - OFFLINE_MAPS: /OpenStreetMaps (User-defined)[/OpenStreetMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps/document/primary%3AOpenStreetMaps, Av:true, files:398, dirs:2, totalFileSize:2.5 GB, topLevel(5):[ElevateTheme/;spain.map;canary-islands.map;Great_Britain_OAM_V4_Mar2021.map;great-britain_IAM_V3forWhereYouGo.map], free space: 3.1 GB, files on device: 1740800)
  - OFFLINE_MAP_THEMES: /OpenStreetMaps (User-defined)[/OpenStreetMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps/document/primary%3AOpenStreetMaps, Av:true, files:398, dirs:2, totalFileSize:2.5 GB, topLevel(5):[ElevateTheme/;spain.map;canary-islands.map;Great_Britain_OAM_V4_Mar2021.map;great-britain_IAM_V3forWhereYouGo.map], free space: 3.1 GB, files on device: 1740800)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:25.6 KB, topLevel(1):[logcat_2020-06-01_08-19.log], free space: 3.1 GB, files on device: 1740800)
  - GPX: /My Documents/SyncedWithGoogle/GPX (User-defined)[/My Documents/SyncedWithGoogle/GPX[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX/document/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX, Av:true, files:21, dirs:2, totalFileSize:22.2 MB, topLevel(5):[Boxley.gpx;Keep/;Routes/;WellWoods.gpx;NewAdvLabs.gpx], free space: 3.1 GB, files on device: 1740800)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:10, dirs:5, totalFileSize:129.2 MB, topLevel(5):[2021-03-22 15-18/;2021-03-30 19-11/;2020-12-08 13-58/;2020-12-01 13-59/;2020-12-08 13-45/], free space: 3.1 GB, files on device: 1740800)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 3.1 GB, files on device: 1740800)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 3.1 GB, files on device: 1740800)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 3.1 GB, files on device: -1)
- Map render theme path: ElevateTheme/Elevate.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
  - content://com.android.externalstorage.documents/tree/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX (20 Mar, 07:31):RW
  - content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps (20 Mar, 07:30):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (20 Mar, 07:29):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v94, Size:30.4 MB) on user storage
 -Settings: v5, Count:184
--- End of system information ---
```

**Comment by eddiemuc** [comment]
I definitely agree that SAF is a huge step backward performance-wise, but alas Google is enforcing its usage (see e.g.  https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html) 

Things which might help you:
* I noticed that you use the same folder for maps and themes. Have you tried using different folders?
* From the number of files in your map/theme folder I assume that you use extracted themes. Have you considered using zipped ones? For more information see https://www.cgeo.org/faq#theme-slow 

Can you give feedback whether this improvdes your situation?

**Comment by alan666notb** [comment]
Thanks for that, I tried your suggestions.

1) Moving my 'Elevate' folder into a different base folder made no difference
2) Downloading 'Elevate.zip' from OpenAndroMaps and using that made a huge difference, c:geo is usable again!
3) The location of the 'Elevate.zip' file (maps folder or elsewhere) doesn't make any difference.

Thanks for your help.

---------------------------------

A couple of observations...

1) When you go into the 'Select folder' dialogue, it opens by showing the files/folders as large 'Boxes', you have to tap on the 'List' type icon to get full filenames. Can the list be the default option or don't you have control over that?

2) Same goes for the 'File access wizard' thing. My partner doesn't have a clue what the wizard is all about and has just dismissed it so far so she can go out caching.

3) I suspect the average c:geo use is going to struggle big time with these changes. 
   How come no other App I have installed has had to go through this process?

**Comment by eddiemuc** [comment]
Hi @alan666notb,

I am glad the changes helped :-)

With regards to your (absolutely valid!) observations:
 
> 1. When you go into the 'Select folder' dialogue, it opens by showing the files/folders as large 'Boxes', you have to tap on the 'List' type icon to get full filenames. Can the list be the default option or don't you have control over that?

This is not a c:geo dialog but an Android system dialog. I am afraid we have no influence on how it looks. 

> 2. Same goes for the 'File access wizard' thing. My partner doesn't have a clue what the wizard is all about and has just dismissed it so far so she can go out caching.

same here...

> 3. I suspect the average c:geo use is going to struggle big time with these changes.
>    How come no other App I have installed has had to go through this process?

That is a very good question which I asked myself a lot too. You can in fact only see the usage of this scoped storage stuff very sporadically up to now. I would assume this will change over the next couple of months when the deadline comes more closely.So far  I have found SAF used in two other popular apps up to now:
* "Signal": Settings -> "Unterhaltungen" -> "Unterhaltungen sichern" -> you are asked to choose a folder using SAF
* "Locus Map": Settings -> "verschiedenes" -> "Standardverzeichnisse" -> some of the folders are set using SAF, for example the "backup" folder (most notably selecting the "map" folder is not done using SAF yet)

**Comment by fm-sys** [comment]
> > 1. How come no other App I have installed has had to go through this process?
> 
> That is a very good question which I asked myself a lot too. You can in fact only see the usage of this scoped storage stuff very sporadically up to now.

I think there's another reason: c:geo is very special in dealing with files. Most other apps do either store content in the app private directory or are dealing with media files (for those a totally different API exits). Furthermore, some (many?) special apps like file managers are explicitly allowed by Google to use the old way of accessing files on storage... Presumably c:geo is simply very unique in its behaviour ;-)

**Comment by eddiemuc** [comment]
@fm-sys this is definitely correct :-)

**Comment by Lineflyer** [comment]
Well, I also think that start at middle of this year, users might see more of those SAF implementations. I think we are quite early, thus quite well prepared. :)

This issue reminds me again on #10224 as I still fear most users will just "live with the problem" or even abandon c:geo usage due to the unresponsiveness. So I strongly suggest a show a one time message as suggested in that issue.

@alan666notb I think this issue can be closed. Feel free to reopen or open new issues if anything is leftover.
