### ISSUE TITLE
BRouter integration: Several questions

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10306]
_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/10291#issuecomment-809793994_

Short question (no need for a sepeaate issue, I hope): How can I see (and probably even change) which routing profile will be used for internal routing? Cause with the currently used car routing profile I get pretty weird routes ... would like to change the profile to get similar routes to what (external) BRouter calculated ...

And, BTW: Seems as if internal routing does not work when c:geo's segment4 folder is set to the one, where external BRouter has put his files ... or am I wrong? If I do so, c:geo obviously thinks there is no routing data and wants to start the download ... and in fact updates the files in BRouter's folder - but on the very next routing start, c:geo wants to download again ...

Ah, got another thing, hihi, at least now I should have opened a new issue anyway, I guess ;) but when changing the directory for routing data, why do the profiles still remain in /cgeo/routing ...? Ok, to be honest, I'm happy that BRouter's profiles are still there, so I can get proper routing, but in fact I would have expected them to be moved, too ...

---

P.S.:

>   when c:geo's segment4 folder is set to the one, where external BRouter has put his files

Seems as if the routing itself uses the default folder, no matter which folder is configured. Cause when I copy the rd5-files to /cgeo/routing/segments4 (and leave the setting untouched), c:geo stops complaining.

**Comment by moving-bits** [comment]
> Short question (no need for a sepeaate issue, I hope): How can I see (and probably even change) which routing profile will be used for internal routing? Cause with the currently used car routing profile I get pretty weird routes ... would like to change the profile to get similar routes to what (external) BRouter calculated ...

It should use the profile you select from within c:geo using the map quick settings menu.
The profile configuration files are name *.brf and located in `routing` subfolder of your c:geo base dir.
But you need proper routing tile data (*.rd5 files in `routing/segments4` subfolder of you c:geo base dir).

> And, BTW: Seems as if internal routing does not work when c:geo's segment4 folder is set to the one, where external BRouter has put his files ... or am I wrong? If I do so, c:geo obviously thinks there is no routing data and wants to start the download ... and in fact updates the files in BRouter's folder - but on the very next routing start, c:geo wants to download again ...

This is due to the "in between-state" BRouter integration currently has. You can already configure a SAF folder for it, but it actually uses the hard-coded `routing/segments4` folder, accessing it via `File` instead of SAF. See #10175/#10176 for SAF migration.

In contrast to this, the downloader (which is internally the same as being used for map files and map theme files) is already using SAF, so the downloader will put the files to the folder you have selected. But if you configure a folder other than `routing/segments4` c:geo will not recognize it currently until #10176 is implemented.

> Ah, got another thing, hihi, at least now I should have opened a new issue anyway, I guess ;) but when changing the directory for routing data, why do the profiles still remain in /cgeo/routing ...? Ok, to be honest, I'm happy that BRouter's profiles are still there, so I can get proper routing, but in fact I would have expected them to be moved, too ...

The routing profile data files (*.brf) will stay in `routing` subfolder - this folder is not configurable directly, but always be a subfolder of the c:geo base folder you configure.
Only the folder for routing tile data files (*rd5) can be configured, as those files are large enough that it makes sense to share it with other apps.

> P.S.:
> 
> > when c:geo's segment4 folder is set to the one, where external BRouter has put his files
> 
> Seems as if the routing itself uses the default folder, no matter which folder is configured. Cause when I copy the rd5-files to /cgeo/routing/segments4 (and leave the setting untouched), c:geo stops complaining.

**Comment by MagpieFourtyTwo** [comment]
> t should use the profile you select from within c:geo using the map quick settings menu.

Misunderstanding. I'm of course aware of the differences between car, bike etc. pp., but I was thinking of e. g. rhe different car profiles. Which can even be tweaked by editing the brf file. Right now there are two car profiles in c:geo's routing folder: "car-eco" and "car-fast" - which one is c:geo using?

Strange thing: Even if I copy the profile files ``car-eco.brf`` and ``car-fast.brf`` from brouter's profile2 folder to c:geo's routing folder, c:geo's internal routing still gives weird results - which are in fact completely unusable: Instead of just using the faster and even shorter federal road, c:geo routes through residential areas ...

**Comment by moving-bits** [comment]
If I'm reading the code correctly, "car" selects the "moped" profile, "bike" selects "trekking", and "walk" selects "shortest".
(BRouter differentiates between fast and non-fast mode. c:geo always selects "non-fast" mode. Above mappings are for non-fast mode, in fast mode you would get car-fast / fastbike / shortest profiles.)

Do I understand you correctly, that c:geo gives you different routing results with internal routing compared to external routing when you select "car"? If so, can you provide me with start and end point, and maybe screenshots of the different routes being calculated?

**Comment by MagpieFourtyTwo** [comment]
> Do I understand you correctly, that c:geo gives you different routing results with internal routing compared to external routing when you select "car"?

Yep. Seems as if internal routing tries to avoid tunnels and/or too fast roads.

> If so, can you provide me with start and end point, and maybe screenshots of the different routes being calculated?

Yes, of course - but to be honest, I get different routes on nearly every single route I plan.
Just chose two points with a tunnel and a bypass road inbetween ...
External routing will use the tunnel and the bypass,
while internal will avoid the tunnel and the bypass, but will go through the residential area.

If you still need more concrete examples, just let me know.

**Comment by MagpieFourtyTwo** [comment]
Why does "car" use "moped" profile?  AFAIK mopeds are e. g. not allowed to use Autobahn ...

**Comment by moving-bits** [comment]
I've checked the original code and the config files and found the cause: In its readme BRouter describes a mapping from "motorcar-short" to "moped", whereas in the supplied `storageconfig` (which I eliminated during migration) it actually uses a mapping from "motorcar-short" to "car-eco". I'll adapt c:geo accordingly.

**Comment by MagpieFourtyTwo** [comment]
Thx a lot!  Routing is still a bit different sometimes, but *way* better than before.
Will keep an eye on it.

BTW: BRouter is highly configurable (see [here](http://brouter.de/brouter/costfunctions.html) for more info) and in the BRouter app (not the downloader) you can even chose which routing strategy (resp. brf-file) should be used.  Would be great to have a possibility like this in c:geo's internal routing, too.

This could be achieved by ...

- either showing a text with the relations between chosen routing style and used brf-file (like ``car => car-eco.brf``, ``bike => trekking.brf`` and ``walk => shortest.brf`` (IIRC)), so the user can change his routing preferences by simply renaming the files (while add. ones can be downloaded from [here](http://brouter.de/brouter/profiles2) or even created/adapted individually like documented [here](http://brouter.de/brouter/profile_developers_guide.txt)),
- or even having an own setting per routing style where the user can select the brf-file to be used, which would even open the opportunity to create/adapt own brf-files, which will not be overwritten by updates

Or, just another approach: Perhaps c:geo may initially simply copy an appropriate default brf-file to an own one, which will then be used for c:geo's internal routing, like for routing style ``car`` e. g. initially copy ``car-eco.brf`` to ``cgeo_car.brf``, for ``bike`` copy ``trekking.brf`` to ``cgeo_bike.brf`` ... which then can be replaced or adapted by the user ...?

Having one of these would make routing way more transparent, I would say.

If you agree to my thoughts, I would of course file an extra FR for this.

**Comment by moving-bits** [comment]
Thanks for retesting. Just a quick reply to your proposal: Have a look at the "routing" subfolder of your c:geo base folder, you'll find the brf files there. Internal routing is a bit less-configurable than BRouter itself - I tried to find a compromise between simplicity and configurability -, but you can still use individual profiles. c:geo is using "car-eco", "trekking" and "shortest" (IIRC), so by adapting and/or renaming files you can influence routing strategy.

**Comment by MagpieFourtyTwo** [comment]
Yep., already knew this - but nonetheless, I still think it would be good to a) preserve this knowledge in the form of a hint text in the settings or even an explicit setting per routing strategy (even we are not sure anymore about the relations, although we have explicitly talked about it a few days ago), which would b) make this possibility available to others and last but not least c) make routing results more comprehensible.

Esp. cyclists will love such a possibility, for sure, since the routing profiles between e. g. MTB, road bike and pedelec are *massively* different. And car drivers may also appreciate being able to choose between "fast" (highway) and "nice" (country road) ...

**Comment by moving-bits** [comment]
A pure description ("you can use this and that file for configuration") is probably better set up in the online manual, maybe add a link from setting to that, but I would rather not put all explanation regarding the mapping into the app itself.

Or, if we explicitly want to promote configurability, then we should add a file selector for each of the three brf files, with defaults set to the current mapping. (Though describing it in the docs would be a good thing anyway.)

**Comment by MagpieFourtyTwo** [comment]
> A pure description ("you can use this and that file for configuration") is probably better set up in the online manual, maybe add a link from setting to that, but I would rather not put all explanation regarding the mapping into the app itself.

Agreed. Was probably too much in Locus - there is a lot of explaining "inline docu" in the settings pages.
However, the online manual should even contain the two links mentioned above.
Although these are no permalinks - but AFAIK they have not changed for years.

> Or, if we explicitly want to promote configurability, then we should add a file selector for each of the three brf files, with defaults set to the current mapping. (Though describing it in the docs would be a good thing anyway.)

Yep, that would be the best solution, IMHO,. i. e. brf file selector per routing style plus link to the manual.

**Comment by moving-bits** [comment]
I've created two issues for further work:
- manual: https://github.com/cgeo/cgeo.github.io/issues/271
- profile settings: #10380

**Comment by MagpieFourtyTwo** [comment]
Great! Thx!
