### ISSUE TITLE
Do not try to access offline map in outdated folder

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10312]
2021.04.02-NB

- My offline map folder is set to /SD/Vectormaps
- I have selected to use one mapfile in this folder on my map
- Go to Settings - Map and reset the used folder for offline maps to default (no copy/move)
- Leave Settings
- Open live map

Result:
An error toast is shown: File SD/Vectormaps/Germany.map could not be read

Expected:
The previously selected map should be cleared as soon as the folder setting was changed to a different location
Instead the map should start with some default map (Google?).

**Comment by eddiemuc** [comment]
PR #10318 will suppress such error messages to user-. The situation is handled internally without problems anyway.

I generally changed behaviour of ContentStorage to display such error messages to user only in debug mode starting now.
