### ISSUE TITLE
Error toast, that /cgeo/maps cannot be accessed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10313]
There are now 5-6 users over time on support mail with this issue:

- Non of them is using offline maps with c:geo
- Non of them have been asked to select a folder for offline maps (which is correct as they did not use them) during migration
- For all of them the sysinfo shows OFFLINE_MAPS: /cgeo/maps (userdefined)
- They all see a toast as soon as they open the map, that /cgeo/maps cannot be accessed
- For all of them the folder /cgeo/maps does not exist

Assumptions:
- AFAIR the folder /cgeo/maps was introduced in combination with our map downloader. Am I right? 
  Under what conditions will it be created?
- Is it possible, that if users skip some versions they will end up without this folder?
- Is it possible, that something strange happens if this folder does not exist when starting the migration?

**Comment by eddiemuc** [comment]
It is possible for users who never used offline maps that this folder simply does not exist, and on map viewer opening it is checked eagerly (to display offline maps). 

Two solutions possible:
* suppress error message in this case (simply not offer any offline maps for slection)
* eagerly create the (then empty) folder if not present

Any preference?

**Comment by eddiemuc** [comment]
PR #10318 will suppress such error messages to user-. The situation is handled internally without problems anyway.

**Comment by Lineflyer** [comment]
@eddiemuc Its somehow related to, what we just discuss in #10317 isn't it?

**Comment by eddiemuc** [comment]
> @eddiemuc Its somehow related to, what we just discuss in #10317 isn't it?

Nope that's a different thing. Here I just included a suppression for showing error messages to the users (they are still logged).

If I understand correctly, then for #10317 default foldera should be created if not existing right?

**Comment by Lineflyer** [comment]
> If I understand correctly, then for #10317 default folders should be created if not existing right?

Correct, and the problem here is, that /cgeo/maps is set but not existing.

**Comment by eddiemuc** [comment]
> > If I understand correctly, then for #10317 default folders should be created if not existing right?
> 
> Correct, and the problem here is, that /cgeo/maps is set but not existing.

See #10317 for further info
