### ISSUE TITLE
Folder not existing if user selects default folder for themes

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10317]
Sent by a user (which I told, he should select default to get /cgeo/maps/_themes but he proofed me wrong):
![grafik](https://user-images.githubusercontent.com/949669/113475535-9e6e1b80-9476-11eb-8905-d4d7cf2085e1.png)

**Comment by bekuno** [comment]
As result of the discussins to the themes folder , eg. see https://github.com/cgeo/cgeo/issues/10123#issuecomment-796690245, the default themes folder was defined as subfolder `_themes` below the map folder.
In this logic the user has defined his map folder as `/Locus/maps`.

**Comment by Lineflyer** [comment]
OK, somehow makes sense.
In this case seemingly the user made a reset to default for the theme folder first and only afterwards he made a reset to default for maps. I had no idea why he ended up with maps folder `/cgeo/maps` and theme folder `/Locus/maps/_themes` but now it makes sense.

Anyway...reading the users description the real problem then seems to be:
He tried to find this default folder `/Locus/maps/_themes` but it was not there. 

Do we create this folder when applying the default?

**Comment by eddiemuc** [comment]
> Do we create this folder when applying the default?

No we don't. Actually we did in the past, but there was the rightful complaint that in this case also useless folders might be created. Every decision has its upsides and downsides it seems :-)

So should default folders be created now again? And in which situations exactly?

**Comment by Lineflyer** [comment]
Let me say this:
I tried to keep the issue small here, but in fact it was a long journey on support mail to find the root cause of the user saying "Themes do not work". First I told him to set the default but referred to a wrong directory (not yet knowing that it is always below the map folder). But that's fine now I know that, and its reasonable.

After many mails and exchange of system information and screenshots the root cause turned out to be, that the user created the folder by himself but used `_Themes` instead of `_themes` not knowing that this is actually a different folder.

So I think:
When we use subfolders of existing permitted SAF locations we should make sure, those exist.
Mainly because if the users checks his settings to place files at the correct spot, it will be unexpected that he does not find those paths.

**Comment by eddiemuc** [comment]
Ok, now #10318 also contains a fix for this one: both on c:geo start and on any folder selection, for all persisted folders set to default those folders are explicitely created if not existing
