### ISSUE TITLE
MapDownloader fails on OAM maps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10319]
Reported by a user and reproducible for me:

- 2021.04.02-NB
- Open Menu - Settings - Map
- Start Map Downloader
- Select OpenAndroMaps
- Download a map (my test: Africa - Angola)
- Wait until download is finished

Result:
- Receive map file dialog opens but is stuck for almost a minute before progress starts. Looks like this.
![Screenshot_20210403-124527](https://user-images.githubusercontent.com/949669/113476430-c8760c80-947b-11eb-9004-88078946f17c.png)
ANR message is popping up once in a while
-  Finally the copy process starts but very slow and stopping several times while in progress
- After the copy process finishes an error is shown:
![Screenshot_20210403-124617](https://user-images.githubusercontent.com/949669/113476466-feb38c00-947b-11eb-8731-0d3d2cfdf4f4.png)

- The above mentioned location is accessible however and it now also contains `angola (OAM).map` but not associated `*.txt`.
- Same procedure is working without problem when trying a Mapsforge map

**Comment by fm-sys** [comment]
I also noticed that issue while working on #10310. Anyway, haven't debugged deeper into it yet.

**Comment by eddiemuc** [comment]
I checked in code and found two things:
* (minor) the error mesage above should call "toUserDisplayableString" on the folder object before putting it into a message to the user
* The above error description is used on ANY IOException occuring during copy process. It would be good to know what the real exception looked like. It should be written to the logfile

Can anyone provifde a log file excerpt for this one? Should start with: `IOException on receiving map file`

**Comment by fm-sys** [comment]
That all the logfile provides:
```
04-03 15:50:42.304 13113 13293 E cgeo    : [AsyncTask #1] IOException on receiving map file: Stream closed
```

**Comment by moving-bits** [comment]
Difference between OAM and MF maps may be related to the need of unzipping the downloaded OAM file.

I'll debug into this.
