### ISSUE TITLE
Back arrow invisible in title bar of settings (light theme)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10328]
- 2021.04.02-NB, Android 11
- Use light theme
- Go into settings (and also in all sub menus)

The up/back arrow in the tile bar is either not shown (but working) or simply white on white.

![Screenshot_20210404-133931_cgeo](https://user-images.githubusercontent.com/949669/113507544-8916f100-954b-11eb-80fc-7a8f8504c173.jpg)

**Comment by moving-bits** [comment]
It's "bright white on slightly less-bright-white" => up arrow should be black in white theme. I'll try to find a fix for it.

**Comment by fm-sys** [comment]
IMHO the title bar should be black (as all other activities when using light theme)

**Comment by moving-bits** [comment]
@fm-sys 
Yeah, you're right., title bar should be dark.

Alas I cannot get it working:

The theme used (`settings.light`) is derived from `cgeo.base.light` (with some intermediate steps), which is derived from `@style/Theme.AppCompat.Light.DarkActionBar`. The `cgeo.base.light` defines `<item name="actionBarStyle">@style/cgeo.ActionBarStyle.Light.Inverse</item>`, the parent of which is `@style/Widget.AppCompat.Light.ActionBar.Solid.Inverse`. 

I've tried with or without this style, with an additonal `<item name="android:actionBarStyle">, and a couple of other variants, even with the plain non-light `cgeo.ActionBarStyle`.

Sadly, the settings'  toolbar doesn't care at all ;-(

**Comment by moving-bits** [comment]
Magically this has been solved as part of our recent re-theming, even though we are still using the old `PreferenceActivity` instead of `PreferenceFragment` etc. Anyway, let's close here.
