### ISSUE TITLE
Check and resolve merge conflict

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10326]
When trying to merge `release` back into `master` I have an conflict:
```
CONFLICT (content): Merge conflict in main/src/cgeo/geocaching/downloader/ReceiveDownloadActivity.java
```

It seems the file was meanwhile changed and even renamed on `master`.
Someone else please needs to resolve this while merging branches please.

**Comment by moving-bits** [comment]
Ok, did a conflict resolution for merging `release` to `master`. Not sure whether I merged the string files correctly (especially the Chinese variant), but I guess Crowdin will fix it with the next update, if necessary.

**Comment by Lineflyer** [comment]
@moving-bits Don't you have configured the merge-ignore for the strings as described here?
 https://github.com/cgeo/cgeo/wiki/Translation-%28L18N%29#conflict-handling-between-branches

**Comment by moving-bits** [comment]
@Lineflyer 
Ah, you are right, thanks for the pointer. I'm currently not at my regular dev machine but on an old, less-frequently used laptop, which obviously seems to have missed that configuration step yet.

Anyway, I guess we can close this isse here now.
