### ISSUE TITLE
Base folder checked while only restoring caches/waypoints

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10325]
- Own developer build from current `release` branch
- Freshly install c:geo and complete the installation wizard
- Call Backup/Restore
- Select to restore but only "caches and waypoints"

Result:
During the restoration process c:geo asks to regrant access to the base folder

Expected result:
Two problems here:
1. The backup should contain the same base folder as currently set
2. I did not restore settings, so why is this shown after all as the process should only restore the database

**Comment by moving-bits** [comment]
folder / file settings should not be checked on restoring only the database => I will prepare a fix for it
