### ISSUE TITLE
Advanced Search inside list

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#10322]
At the moment the filter for offline stored lists is only allowing the user to set filters basing on the cache status or attributes. 

It might be great if you could also search for keywords (like on the main page) to find e.g. a set of caches to mark only this set and refresh them all before you are heading out into the wild... 

Of course you could try to find them manually in the full list, but if you are storing several thousand caches and are not 100% sure how they are written (e.g. "#0'1 cachename" or "#1 cachename" or "[Icon] #01 cachename", etc pp) it is hard to find them easily. 

Thanks for taking care,
wolv_007

**Comment by eddiemuc** [comment]
I plan to make this possible as part of #9081

**Comment by wolverine007** [comment]
Sounds great, flipped into your mentioned ID - seems there has been a lot stored into this one big package.

Looking forward for the implementation 👍

Thanks for taking care mate!

**Comment by eddiemuc** [comment]
Should work now on master/nightly (use filters "Name" or "Desrciption")
