### ISSUE TITLE
failing tests on cgeo-4

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10330]
We have many failing PR tests.
All of them are run on cgeo-4.

**Comment by eddiemuc** [comment]
For some reason all jobs currently seem to be executed on cgeo-4 too, so "retest this please" does not really help

**Comment by bekuno** [comment]
The PR #10332 does not help.
I dectivated the PR build on cgeo-4 (renamed `has-emulator` to `has-emulator-deactive`).
@mucek4 
Please have a look at the emulator. Disk full?

**Comment by eddiemuc** [comment]
I closed the useless PR.

@bekuno : should the build work now (if I understand correctly then you deactivated cgeo-4 somehow)?

**Comment by bekuno** [comment]
> should the build work now (if I understand correctly then you deactivated cgeo-4 somehow)?

The CI devices have a marker, and the jobs are using that to decide where they can run:
![grafik](https://user-images.githubusercontent.com/32555742/113572798-2a1fad80-9619-11eb-8777-012912de547a.png)
The list is now after renaming in cgeo-4:
![grafik](https://user-images.githubusercontent.com/32555742/113572999-8f739e80-9619-11eb-89e6-b9d3f606b908.png)
This means that the PR builds will now run at cgeo-1 or cgeo-5.

**Comment by mucek4** [comment]
I have no idea why tests would not work on cgeo-4. 4 and 5 are running on same hardware, nr 1 is on other. I have stopped nr4 and let's see what will happen.

**Comment by bekuno** [comment]
The marker is configured back to `has-emulator` om cgeo-4

**Comment by bekuno** [comment]
After restarting the cgeo-4 builds PR again.
