### ISSUE TITLE
Brouter update message on startup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10345]
After installing todays nightly 2021.04.06-NB c:geo asked me, whether I want to update routing data.

That's strange and unexpected because I never touched the new internal routing feature but only configured/used the external app.

**Comment by moving-bits** [comment]
This is indeed strange, as at least the routing data base folder has to be set to a non-legacy value and auto tile downloader has to be activated (defaults to false) for the check to be called:
```
if (Settings.isBrouterAutoTileDownloads() && !PersistableFolder.ROUTING_TILES.isLegacy()) {
...
}
```

Anyway, I'll prepare a PR which additionally checks for the current setting of `Settings.useInternalRouting`, which is a good thing anyway.

**Comment by Lineflyer** [comment]
I checked my installation and I do see the following settings greyed out (as internal routing is deactivated):
- The routing tile folder is set to `/cgeo/routing/segments4 (Standard)` but I did not touch this setting up to now.
- The auto tile downloader setting is active as well

**Comment by Lineflyer** [comment]
Regarding the update interval and update check:
Wouldn't it make more sense to implement such update check in a modular way, so that it covers not only routing tiles, but also update check for offline map/themes?

**Comment by moving-bits** [comment]
> I checked my installation and I do see the following settings greyed out (as internal routing is deactivated):
> * The routing tile folder is set to `/cgeo/routing/segments4 (Standard)` but I did not touch this setting up to now.

Default for "segments4" is to be a subfolder of ROUTING_BASE, which defaults to being a subfolder of BASE.
So I guess, in your case the question is whether you have set BASE to a SAF folder, or whether it still points to legacy `/cgeo`.

> * The auto tile downloader setting is active as well

Hm, this defaults to false (and has always be, just checked git history for this):
```
    public static boolean isBrouterAutoTileDownloads() {
        return getBoolean(R.string.pref_brouterAutoTileDownloads, false);
    }
```

Also in `preferences.xml` it has set `android:defaultValue="false"`. 

Strange. Currently I cannot explain why the auto tile downloader value is set to `true` in your case.

> * Update check is set to 30

That's ok, as it's its default value.

**Comment by moving-bits** [comment]
> Regarding the update interval and update check:
> Wouldn't it make more sense to implement such update check in a modular way, so that it covers not only routing tiles, but also update check for offline map/themes?

Good idea (although some things work a bit differently between routing tiles and map data), I'll open a separate issue for it.

**Comment by Lineflyer** [comment]
Will test the default values on
- a new installation
- upgrade from older nightly

next days.
