### ISSUE TITLE
Renew cgeo-ci-bot Github tokens

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10348]
Github send a mail to our bot, that the access tokens for this user need to be renewed (new security level, weak old token).

Two tokens are involved:
- CI --> @mucek4 
- Crowdin --> @Lineflyer 

Seems not time critical, but should be done.

**Comment by Lineflyer** [comment]
I will start tonight by replacing the token for Crowdin. 
AFAICS there is no possibility to renew/replace the used token on Crowdin, thus I need to disable and reintegrate the Github connection on Crowdin site. While this should be Plug&Play I will start with the much smaller WhereYouGo first.

Please kindly don't change/add new strings until further notice (to be on safe side not to mix up anything and have the need for manual string fixing)

**Comment by Lineflyer** [comment]
Setting up the renewed access tokens for Crowdin seems to have gone through smoothly.
Please note me, if anything is not working to/from Crowdin.

Regarding the CI:
- I have created a new token with same permissions as the old one (admin: hooks, read public_repo)
- I updated the token information in Jenkins credentials manager and Jenkins configuration -> Pull request builder
- For c:geo repo it seems to work and I can see the new token being used and PR and commit builds working
- For WhereYouGo repo however it does no longer build PRs. It can no longer maintain the needed webhooks (error shown on Jenkins configuration as well)
- I can't see a reason why, because the cgeo-ci-bot has same permissions for both repositories on Github on the existing webhooks show deliveries

@mucek4 @kumy Sorry for making it worse...maybe one of you can take a look, because I don't know possible differences between c:geo and WhereYouGo jobs on Jenkins side
I can provide the new token if needed. Contact me via mail.

**Comment by kumy** [comment]
I've broken jenkins and asked in PM @mucek4 to give it the first aid measures to resurect him  :(
Sorry for that

**Comment by kumy** [comment]
Thanks to @mucek4 all should now be working.

We've rebooted the host and on the WhereYouGo job:
- disable usewebhook
- fill the whitelist field

**Comment by kumy** [comment]
I forgot, I've seen that after rebooting the jenkins VM, I've lost my last configuration (the whitelist field content). @Lineflyer Does all you last modifications (tokens) are still present?

**Comment by Lineflyer** [comment]
@kumy I only changed the token (secrets) for the cgeo-ci-bot api.github.com tokens. Cannot say whether these are still present as I can't view them.
I did now revoke the old (claimed unsecure) token used for Jenkins connection on the cgeo-ci-bot account. Lets see if all is still running normal.

**Comment by Lineflyer** [comment]
PR triggered build and re-build (via keyword) working on both repositories.
We should watch the commit builds as well but these even worked before. Closing for now and thanks for helping here.

Feel free to reopen if commit or PR builds are not starting.

**Comment by Lineflyer** [comment]
One thing I have seen missing:

Commit builds for WhereYouGo have been triggered and executed, however there was not pending/result report on Github (meaning no red x or green tick next to the commit).

I have reconfigured the job https://ci.cgeo.org/view/WhereYouGo/job/whereyougo%20(All%20commits)/ in the same way as it is configured for c:geo:
- Add "Set build status to pending" as first step for building
- Add "Set commit status on Github" as last steps in post-build actions

Theoretically if should now again show the build status/results in the commit history same as for c:geo.
