### ISSUE TITLE
Always output login result to logfile or system information

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10349]
When users have login problems (e.g. due to wrong username/password, captcha problem, unknown error) the attached logfiles do not always contain an indication.

Therefore I suggest to always log succesful logins as well as login failure. Currently AFAICS its only logged in debug mode,
Even better would be to  include the last login result for each active service into the system information instead (if technically possible).

**Comment by moving-bits** [comment]
We do log the last successful & the last failed login for gc connector to system information since a couple of versions now. Is that sufficient to close this issue?

**Comment by fm-sys** [comment]
I would say so...

**Comment by Lineflyer** [comment]
Yes, thats really helpful on support.
