### ISSUE TITLE
TB-seach from homescreen not possible with secret code

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#1036]
From a friend:

I tried to use the search function on the top of the homescreen to log TBs I have found. The help-app says, this should work. However it seems only to be working if you use the public identifier of the TB but not with the secret code printed on the TB.
This makes this special function quite useless, as usually I don't have the public code when I find a TB and try to log.
It would save some clicks if I could just use the secret-code in search from the homescreen.

**Comment by SammysHP** [comment]
Fixed by 71629eecbed3793ec62f1e769927d52b773e27a0
