### ISSUE TITLE
BRouter integration: Make profile mapping configurable in settings

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10380]
Following the discussion that started in https://github.com/cgeo/cgeo/issues/10306#issuecomment-817652239:

Add a file selector in "settings => map => offline routing" for each routing profile (car, bike, walk).
Default mapping is to the `routing` subfolder of the configured `base` folder, with the following filenames:
- walk => shortest.brf
- bike => trekking.brf
- car => car-eco.brf

(which is the default mapping in current BRouter, external and internal)

**Comment by moving-bits** [comment]
@eddiemuc 
While working on this I've stumbled upon some SAF-related questions - can you help me? Thanks.

- The profile files (*.brf) are stored in a subfolder of c:geo BASE folder, which I access using the `PersistableFolder.ROUTING_BASE`. To open such a file, I need to create a URI from folder + filename (e. g. "trekking.brf"). To create such a URI, is there a different way than doing a list on the persistable folder and compare FileInfo.name against my filename?
- When the user wants to change the mapping, I open a SAF file selector in the settings for it. This does work, but it starts with the preselected folder (displaying everything in that folder), even if I give a specific URI to the default name. Is there a way to start with the specific file in the given folder?
- Will both of it work even if the user hasn't set a BASE folder yet? (Which means it it still pointing to the legacy value for BASE, which should be promoted to ROUTING_BASE as well.)

**Comment by fm-sys** [comment]
Maybe we could design some kind of `simpleFileChooser` component,  which lists all files in a persistable folder. That would be legacy compatible and we would have full control over it :)

**Comment by fm-sys** [comment]
Or even simpler, use a `ListPreference` and dynamically fill it with the available files in `PersistableFolder.ROUTING_BASE`. That would IMHO be the cleanest way.

**Comment by eddiemuc** [comment]
> * The profile files (*.brf) are stored in a subfolder of c:geo BASE folder, which I access using the `PersistableFolder.ROUTING_BASE`. To open such a file, I need to create a URI from folder + filename (e. g. "trekking.brf"). To create such a URI, is there a different way than doing a list on the persistable folder and compare FileInfo.name against my filename?

No. There is no algorithm to "construct" Uris from e.g. filenames. Some DocumentProviders assign just numbers to documents and folders, there such an approach would never work out. Sorry. Could be slightly optimized by selecting only the "name" column in the list query internally but this will not really make a difference. 

> * When the user wants to change the mapping, I open a SAF file selector in the settings for it. This does work, but it starts with the preselected folder (displaying everything in that folder), even if I give a specific URI to the default name. Is there a way to start with the specific file in the given folder?

I am not exactly sure I understand what you mean. If you open a file selector, wouldn't you want it to open at the folder where the default file lies? Or what do you mean  by "preselected folder"?

> * Will both of it work even if the user hasn't set a BASE folder yet? (Which means it it still pointing to the legacy value for BASE, which should be promoted to ROUTING_BASE as well.)

Yes, should work just the same as long as you stick to methods of ContentStorage/ContentStorageActivityHelper (but under the hood, Files are used)

**Comment by moving-bits** [comment]
@fm-sys @eddiemuc 
Thanks for your help. I'll pursue the `ListPreference` approach - good idea! (IIRC we have something like this for the map files)
I got diverted by thinking that a configurable file has to be placeable into any folder - but we can declare that it always has to be `ROUTING_BASE`, which simplifies a few things.

> > To create such a URI, is there a different way than doing a list on the persistable folder and compare FileInfo.name against my filename?
> No. There is no algorithm to "construct" Uris from e.g. filenames. [...] Sorry.

No problem. I'll create a convenience function for accessing a single given file with folder + filename.

> > * When the user wants to change the mapping, I open a SAF file selector in the settings for it. This does work, but it starts with the preselected folder (displaying everything in that folder), even if I give a specific URI to the default name. Is there a way to start with the specific file in the given folder?
> 
> I am not exactly sure I understand what you mean. If you open a file selector, wouldn't you want it to open at the folder where the default file lies? Or what do you mean by "preselected folder"?

Sorry, I had formulated it a bit confuse... I meant: File selector opens in the given folder (which is good), but even if I provide a Uri for a specific file within that folder, all files in the folder are listed and none selected. So in contrast to the SAF folder selector I cannot preselect my default file, which can make it hard for the end-user to select the correct file.

But as I will change my approach from SAF file selector to a `ListPreference` approach this doesn't hurt me any longer ;-)
