### ISSUE TITLE
requestLegacyExternalStorage needs removal after 05.05.2021

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10386]
From Google Play....this is somehow surprising as I expected it to be combined with targeting SDK30 in November:

## Starting May 5th, you must let us know why your app requires broad storage access

We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:

 - Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
 - Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
- Remove the All files access permission from your app entirely

For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

**Comment by eddiemuc** [comment]
I thought this was only necessary starting August/September?

**Comment by Lineflyer** [comment]
November for targeting SDK=30, but obviously they stop accepting the LegacyStorage function on Android 11 devices even earlier. First time I read this today...but we are fully prepared...are we?

**Comment by Lineflyer** [comment]
Link below this article goes here:
https://support.google.com/googleplay/android-developer/answer/10467955

**Comment by Lineflyer** [comment]
"Due to COVID-19 related considerations,..."  what could be that relation?

**Comment by moving-bits** [comment]
> "Due to COVID-19 related considerations,..." what could be that relation?

I guess this relates to physical people working for Google doing manual checks on apps which apply for the `MANAGE_EXTERNAL_STORAGE` access - some limitations in availability due to Covid-19.

**Comment by moving-bits** [comment]
I'm somewhat confused by above's message, as we are targeting API 29 currently, which is Android 10. Also we are not requesting the `MANAGE_EXTERNAL_STORAGE` access right in our manifest file. Also hadn't heard about a "May 5th" restriction yet, only fall 2021 (probably November). Strange.

**Comment by Lineflyer** [comment]
Reading the full passage of the linked article it states something else:

Due to COVID-19 related considerations, apps that target Android 11 (API level 30) and request All files access cannot be uploaded to Google Play until May 2021. This includes new apps as well as updates to existing apps. This temporary uploading restriction **only** affects apps that both target Android 11 (API level 30) **and** request the All files access permission.

This would mean that as long as we target Android 10 we should be fine, or not?

**Comment by moving-bits** [comment]
> This would mean that as long as we target Android 10 we should be fine, or not?

That's the way I understand the linked article as well, and that's why I'm confused as this does not fit to the message in the opening article.

**Comment by Lineflyer** [comment]
Besides this confusing statements by Google...

AFAIK we have now prepared everything which is prerequisite to remove both
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
and
` android:requestLegacyExternalStorage="true"`
from our Manifest?!

The only important thing is, that it will break seamless migration from older versions. So users skipping the current SAF update and later try to update to a version without these permissions will receive a more bumpy experience.

**Comment by eddiemuc** [comment]
Correct. But if we want to switch now I would at least recommend a longer beta test phase

**Comment by Lineflyer** [comment]
Assuming I do understand the linked article in a correct way it means:
- We can keep doing both bugfix and feature releases as long as we keep TargetSDK=29 on `master`. No restrictions apply until November 21.
- Once we switch to targetSDK=30 however we need to remove the legacy storage permission in the same step (for which we are technically already prepared)

Will try to find more answers next days.

**Comment by Lineflyer** [comment]
switch to sdk30 ongoing.
