### ISSUE TITLE
Sorting of presorted lists gets lost when returning to list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10389]
## Bug description 

We have a magic function which detects if lists contain caches with similar names and automatically set the default sorting to "By Name" instead of "By Distance" as we assume it might be helpful for the user (e.g. for powertrails).
While this feature is nice, there is however some bug in it:
If the user applies a custom sorting to such lists (e.g. back to "By Distance") this sorting is reset to "By Name" in the following procedure.
Note:
On "normal lists" (sorted "By Distance") the custom sorting works in this scenario. Only those automatically pre-sorted lists are affected.

### Steps to reproduce the problem

- Have a list which only contains caches with similar names (e.g. "Cache #1", "Cache #2", etc)
- c:geo automatically sorts "By Name" which is OK
- Select Menu - Sort - (e.g.) Distance
- Open details of one of the caches in the list
- Return to the list

### Actual result after these steps 

User defined sorting is lost (back to "By Name")

### Expected result after these steps 

User defined sorting should persist this operation like on "normal" lists

## c:geo version 

2021.02.14

## Reproducible 

Yes

## System information 

Not relevant

**Comment by eddiemuc** [comment]
I am working on sort anyway in context of new filtering and can include a fix for this issue in m work. Provided it is not too urgent as I am currently a bit short with my spare time for c:geo

**Comment by eddiemuc** [comment]
Btw: as you know I am not a friend of such "magic" logic deciding on some heuristics what is best for the user in what situation. Might it be an option to just remove the "feature" of auto-sorting by name based on cache name comparison?

**Comment by Lineflyer** [comment]
In general I like such features/automatism which helps users....thus its difficult to decide whether to use those or not. AFAIK we have two such features: Sorting trail lists by name, sorting event lists by event date.

While it might be convenient, most users contacting us with this topic consider it unexpected and (in combination with this bug) even disturbing. 

I am neutral when it comes to removing those "magic" functions.

**Comment by eddiemuc** [comment]
Will be fixed with PR #10147
