### ISSUE TITLE
Dynamic Map Switching

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#10391]
Scenario: I have multiple offline maps installed for different areas of a country and / or adjacent countries.

Locus Map: If I move from a region covered by map-1 to a region covered by map-2, Locus seamlessly renders map-2 as if it was one single map.

Cgeo: As I move from region1 to region-2, I have to manually select map-2.

Could this be automated just like Locus Map does it?

If this is a duplicate, pls disregard

**Comment by moving-bits** [comment]
If you use the "combined map" setting, c:geo automatically uses all available offline maps for seamless rendering

**Comment by baiti** [comment]
> If you use the "combined map" setting, c:geo automatically uses all available offline maps for seamless rendering

I have been unable to find that setting.

Further: I would suggest to make this the default and even remove the selection capability. Why would anybody ever want to turn this option off? In Locus, "it just works", no questions asked.

**Comment by Lineflyer** [comment]
> I have been unable to find that setting.

Its the last selection in your map selector on map...not in our settings.


> Further: I would suggest to make this the default and even remove the selection capability. Why would anybody ever want to turn this option off? In Locus, "it just works", no questions asked.

Well...I had several users on support mail claiming crashes on mapsforge map. Those users had quite some maps stored in their maps folder and used combined mode (while not really needed it). The problems vanished after setting a dedicated map instead of the combined mode. So, it seems a bit buggy or has problems with some maps or depending on the total amount of maps. Had no time to take a deeper look (also I cannot reproduce it).

**Comment by rsudev** [comment]
> Further: I would suggest to make this the default and even remove the selection capability. Why would anybody ever want to turn this option off? In Locus, "it just works", no questions asked.

I am fine with making this the default (as Lotus does, you can still override it) but I would not remove the option. It is (at least for me) not unusual to have more than one map for a specific location (hesse vs germany vs alps from openandromaps vs freizeitkarte vs ....)

**Comment by baiti** [comment]
I see ... things are not so easy. I also have more than one offline map for specific regions. So I would conclude, leave everything as it is now.

**Comment by baiti** [comment]
I swichted to "Combined" now and it is working as expected. Will leave it ON until I run into a situation where it is not working. Perhaps I can then help with debugging the problem mentioned above by @Lineflyer.

**Comment by eddiemuc** [comment]
Note that if there are problems with "combined maps", then most likely we can't fix them in c:geo but just forward them to the mapsforge project.

**Comment by moving-bits** [comment]
Ok, then let's close here, as the original question is solved.

If we stumble upon any specific errors on using the combined map, we can open dedicated issues for them.
