### ISSUE TITLE
Trackable Details Tab: "Spotted" does not show user

### ISSUE THREAD

**Issue by gcey** [cgeo/cgeo#10403]
## Bug description 
The Trackable Details Tab contains a field "Spotted", which should show "The name of the cache or the user, where this trackable has been last seen/logged."

It used to do so for a long time, but since some weeks (months?) it shows only caches but not users.

### Steps to reproduce the problem
In "Search" - "Trackable" enter a trackable code (e.g. "TB1N4CA") and click "Search for trackable".

### Actual result after these steps 
The fields "Name", "Brand", "Type", "Tracking code", "Owner" and "Traveled" are shown, but "Spotted" is not shown.

### Expected result after these steps 
Also "Spotted" should be shown (in this case with the user name "tumppi00".

## c:geo version 
2021.02.14

## Reproducible 
Yes

**Comment by moving-bits** [comment]
There has been a website change a couple of weeks ago. We have included a fix for this in the release we are currently rolling out, but as we are rolling out the new release in waves this time, it may take a short while until it reaches you.
