### ISSUE TITLE
Significant higher ANR rate in 2021.04.15 (SAF) compared to 2021.02.14 (preSAF)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10406]
Statistics of today comparing those two releases (while still at 50% rollout rate):
![grafik](https://user-images.githubusercontent.com/949669/115157200-3af40880-a088-11eb-8fe7-0060ee49239d.png)

Will still continue to roll out but maybe someone could have a look into the Play Console if there is any specific finding, which we can optimize.

**Comment by Lineflyer** [comment]
Looking at the scale it might still be not so dramatic:
The percentage raise is high, but the absolute values still  look rather low.

**Comment by Lineflyer** [comment]
Right now two new users with c:geo hanging on the splash screen (running into ANR).

@eddiemuc Is there any evaluation/check of folder contents involved in the startup process. It should not...just asking. For one user I have seen that he set the same folder for maps and themes and its containing >=320 dirs and 8GB of data. I guess this should be irrelevant for starting the app...just want to make sure.

**Comment by eddiemuc** [comment]
There should be no folder scan on startup. Also such folder scans, even if they are happening, should be limited to max. 5 subdirs to prevent overly long scan times.

**Comment by eddiemuc** [comment]
@Lineflyer I am not so used to Google Play Console up to now. Is this the right place to look in ("Abstürze und ANRs", there's a long list of concree errors on the right which I don't want to copy here)?

![image](https://user-images.githubusercontent.com/6909759/115188538-5a6d4e80-a0e5-11eb-8041-02d29787cd96.png)

**Comment by Lineflyer** [comment]
> I am not so used to Google Play Console up to now. Is this the right place to look in ("Abstürze und ANRs", there's a long list of concree errors on the right which I don't want to copy here)?

Yes, thats correct.
You can use the functions on top to e.g. filter on app version and filter on ANRs.

**Comment by Lineflyer** [comment]
> There should be no folder scan on startup. Also such folder scans, even if they are happening, should be limited to max. 5 subdirs to prevent overly long scan times.

I received one users feedback, which is:

---

I noticed, that c:geo was extremely slow when dealing with the map settings menu. Therefore I renamed my existing map folder, created a new, empty map folder and assigned it in c:geo. Then I copied the maps over there and since then everything is working smoothly and c:geo starts up fast.

---

It will probably not easy to find the cause of this problem, however I am wondering why this affects the startup time after all.

This is the initial system information of the user (before he did the change described above):
```

--- System information ---
c:geo version: 2021.04.15

Device:
-------
- Device type: SM-N950F (greatltexx, samsung)
- Available processors: 8
- Android version: 9
- Android build: PPR1.180610.011.N950FXXSEDTL1
- Sailfish OS detected: false
- Google Play services: enabled - 21.12.13 (100400-367530751)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: own/found
- Hide waypoints: -
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Global filter: display all caches
- Last backup: 18. Nov. 2019, 20:03
- Routing mode: Fahrrad
- Map: Germany (Offline)
- Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:0000-0000:Karten/germany.map
- Atts: mapsforge-map-writer-0.3.1-SNAPSHOT
- Theme:

Services:
-------
- Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd/MM/yyyy
- BRouter installed: true / connection available: false
- Installed c:geo plugins: none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (19,2 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (19,2 GB free) v2 external non-removable isDir(5 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (19,2 GB free) v2 external non-removable isDir(1645 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (19,2 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
- BASE: /cgeo (Benutzerdefiniert)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=4, dirs:>=6, totalFileSize:>=46,8 MB, topLevel(5):[logfiles/;GeocachePhotos/;field-notes/;backup/;gpx/], free space: 19,2 GB, files on device: 1761280)
- OFFLINE_MAPS: SD-Karte/Karten (Benutzerdefiniert)[SD-Karte/Karten[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AKarten::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AKarten/document/0000-0000%3AKarten, Av:true, files:>=356, dirs:>=320, totalFileSize:>=7,8 GB, topLevel(8):[Freizeitkarte_Deutschland.map/;germany.map;._germany.map;Germany/;Germany_oam.osm.map;Germany_oam.osm.db;Germany_oam.osm.poi;germanyoffline.map], free space: 104,6 GB, files on device: 0)
- OFFLINE_MAP_THEMES: SD-Karte/Karten (Benutzerdefiniert)[SD-Karte/Karten[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AKarten::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AKarten/document/0000-0000%3AKarten, Av:true, files:>=356, dirs:>=320, totalFileSize:>=7,8 GB, topLevel(8):[Freizeitkarte_Deutschland.map/;germany.map;._germany.map;Germany/;Germany_oam.osm.map;Germany_oam.osm.db;Germany_oam.osm.poi;germanyoffline.map], free space: 104,6 GB, files on device: 0)
- LOGFILES: /cgeo/logfiles (Standard)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:3, dirs:0, totalFileSize:276,6 KB, topLevel(3):[logcat-2021-04-18-23-03-51-2.txt;logcat-2021-04-18-23-14-27-2.txt;logcat-2021-04-18-22-57-22-2.txt], free space: 19,2 GB, files on device: 1761280)
- GPX: /cgeo/gpx (Standard)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:13, dirs:0, totalFileSize:17,1 MB, topLevel(first 10 of 13):[export_2020-01-12.gpx;route_2020-11-10_08-35-08.gpx;export_2020-12-16.gpx;export_2020-05-28.gpx;route_2020-11-10_08-35-23.gpx;Tor_Lamspringe.gpx;export_2020-05-29.gpx;export_2020-05-13.gpx;route_2020-10-31_03-35-34.gpx;export_2021-03-02.gpx], free space: 19,2 GB, files on device: 1761280)
- BACKUP: /cgeo/backup (Standard)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:1, dirs:1, totalFileSize:46,6 MB, topLevel(1):[2019-11-18 20-03/], free space: 19,2 GB, files on device: 1761280)
- FIELD_NOTES: /cgeo/field-notes (Standard)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 19,2 GB, files on device: 1761280)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Standard)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 19,2 GB, files on device: 1761280)
- TEST_FOLDER: [Veraltet]/data/user/0/cgeo.geocaching/files/unittest (Standard)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 19,2 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #2
- content://com.android.externalstorage.documents/tree/0000-0000%3AKarten (18. Apr., 22:36):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (18. Apr., 22:36):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:96,6 MB) on system internal storage
-Settings: v5, Count:146
--- End of system information ---
```

**Comment by eddiemuc** [comment]
@Lineflyer thanks for this, I scanned again the code and have to apologize: there **is** afolder scan happening at startup, which is the initial scan for map theme files. And this is a complete one!

I guess the cleanest way to resolve this is to postphone this first scan until the list of map theme files is really needed. This would in practice then move the long wait to the first opening of map viewer -> but then the app will crash there.

Or we restrict the amount of subfolders to scan for map themes. 

What would you prefer?

**Comment by Lineflyer** [comment]
I think we should remove the scan completely from the startup for sure. Map related things should happen if the map is really used (theme sync would be an exception as it should probably happen on startup but AFAIR its done async anyway).

> I guess the cleanest way to resolve this is to postphone this first scan until the list of map theme files is really needed. This would in practice then move the long wait to the first opening of map viewer -> but then the app will crash there.

Its not about crash but about ANR..but you are right.
The initial problem seems to be, that the user has set the same folder for maps and themes and it contains a huge amount of data. I guess we could/should also give up here after scanning some folder levels?!
BTW:
How was this handled in the pre-SAF era? Also there the user might have defined a folder containing unrelated data and we need to build the list of available themes...Is this purely the slowness of SAF or was there a substantial change of how the list of themes is built?

**Comment by Lineflyer** [comment]
For the time being I will advise affected users to either change their theme folder to a folder only containing their themes, or (for those users not even able to start c:geo) to rename their themes folder to make it inaccessible so that c:geo can start.

Depending on the time needed to fix this, I might compose a FAQ article later on.

**Comment by eddiemuc** [comment]
> How was this handled in the pre-SAF era? Also there the user might have defined a folder containing unrelated data and we need to build the list of available themes...Is this purely the slowness of SAF or was there a substantial change of how the list of themes is built?

No significant change here, its just that file scans are super fast and saf is not

**Comment by Lineflyer** [comment]
> No significant change here, its just that file scans are super fast and saf is not

OK, that what I though :(

Is it possible for you to provide a PR next days as discussed above?
It would be good to have the bug fixed out there before the next weekend comes...but anway I will create a FAQ entry and provide workaround infos on our channels tonight.

**Comment by eddiemuc** [comment]
@Lineflyer I provided PR #10412 which will abort scanning of xml theme folder after max 2 seconds (hard-coded) and shows a corresponding toast to the user. Themes scanned in this time will be available for selection in map viewer.

**Comment by eddiemuc** [comment]
There would be a very easy solution: only scan first folder-level of themes folder for themes, don't do any deep scan. This would however break some advanced users usage patterns. Does anyone know how Locus is handling this?

**Comment by MagpieFourtyTwo** [comment]
> There would be a very easy solution: only scan first folder-level of themes folder for themes, don't do any deep scan. This would however break some advanced users usage patterns.

[We're supposed to haggle](https://www.youtube.com/watch?v=51_Qs8tq5c8)? ;)

IMHO, one level is a bit harsh - but two levels would most probably be sufficient (and already *way* better than scanning an entire SDcard). And with two levels one could even separate different themes (esp. if different versions are needed).

BTW; Tried to use zipped themes this weekend, but failed completely. The unzipped folders work perfectly fine. And when I zip them, the theme names are still shown, but as soon as I select one, c:geo toasts "The selected render theme is not valid for this mapsforge version. Reverting to the built-in one" - is this an issue or am I doing s/th wrong?

**Comment by Lineflyer** [comment]
> BTW; Tried to use zipped themes this weekend, but failed completely. The unzipped folders work perfectly fine. And when I zip them, the theme names are still shown, but as soon as I select one, c:geo toasts "The selected render theme is not valid for this mapsforge version. Reverting to the built-in one" - is this an issue or am I doing s/th wrong?

It worked for me.
Try to use the original zip theme downloaded from OpenAndroMaps. These worked fine for me.

**Comment by Lineflyer** [comment]
Regarding the overall issue:

We tried to mitigate this problem by implementing a timeout for the scan.

Due to the frequent releases of last days its difficult to compare the ANR-rates and reports right now, thus we need to wait some days to get relevant figures.

**Comment by eddiemuc** [comment]
> [We're supposed to haggle](https://www.youtube.com/watch?v=51_Qs8tq5c8)? ;)

I like your kind of humour :-)

> IMHO, one level is a bit harsh - but two levels would most probably be sufficient (and already _way_ better than scanning an entire SDcard). And with two levels one could even separate different themes (esp. if different versions are needed).

In PR #10433 (not merged yet) I introduce a max. scan depth of 3 (the main folder and up to two subdirs depth). I can change it to 2 levels of course if wanted?

**Comment by eddiemuc** [comment]
> BTW; Tried to use zipped themes this weekend, but failed completely. The unzipped folders work perfectly fine. And when I zip them, the theme names are still shown, but as soon as I select one, c:geo toasts "The selected render theme is not valid for this mapsforge version. Reverting to the built-in one" - is this an issue or am I doing s/th wrong?

@MagpieFourtyTwo 
Do you see a way to provide the zip file in question? Then I can take a look at it.

**Comment by Lineflyer** [comment]
As aligned:
During the beta phase we introduced the scanning time limitation.
Therefore in our production version the ANR rate should hopefully decrease. 

I will monitor Google Play for some time to gather feedback.

**Comment by moving-bits** [comment]
Just had a look at the current values in Play Store: ANR rate is down to < 0.3%, crashes app. 1.1% - This is getting into the right direction, we are pretty close to what we had in earlier releases.

**Comment by moving-bits** [comment]
Looking at the recent Android vitals stats seem to have settled again. 

@Lineflyer 
Can we close here?

**Comment by Lineflyer** [comment]
Yes, I think so.
