### ISSUE TITLE
Map source change in menu only effective after restart

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10407]
## Bug description 

A user reported, that after changing the map source (e.g. from Offline to Google) in Settings - Map he needs to reboot the device (Edit: Restart of c:geo is sufficient) before the map is showing the desired map source. 
The user reported it was working in 2021.02.14

### Steps to reproduce the problem

- Have offline map in use
- Go to Settings - Map and change Map source to "Google:Maps"
- Leave settings and open the live map

### Actual result after these steps 

The live map still uses the offline map.
(Edit: A restart of the app is needed for the change to take effect)

### Expected result after these steps 

The live map should use the new selected map source (here: Google Maps)

## c:geo version 

2021.04.15

## Reproducible 

Yes, can reproduce this scenario clearly

## System information 

Not relevant

## Additional context 

Support Ticket 294561

**Comment by moving-bits** [comment]
Additional info after a quick glance: 
Changing the map source via settings seems to require restart of c:geo (with removal from memory, but no device restart needed), whereas changing the map source using the map menu works flawlessly over here.

**Comment by Lineflyer** [comment]
Yes, thats more precise.

**Comment by Lineflyer** [comment]
Some more reports of users claiming "offline maps do not work".
Turned out to be this problem:
Their usecase is to change the map in Settings - Map rather than on the map view itself.
Still no major issue as I just told them to use the map selection on map instead.
