### ISSUE TITLE
live map shows ignored caches.

### ISSUE THREAD

**Issue by mzielinskim** [cgeo/cgeo#10402]
The live map shows ignored caches. It seems that this happens only on member-only caches.
The caches are on the ignore list at gc.com and not stored in c:geo but still they are showing up in the live map

They are correct ignored when using the nearby function. So it's only related to the live map

_Originally posted by @mzielinskim in https://github.com/cgeo/cgeo/issues/9445#issuecomment-821933388_

**Comment by bekuno** [comment]
@mzielinskim 
Please cross check on the GC website map.

You mean that ignored basic member caches are hidden, but ignored premium member caches are visible?

**Comment by mzielinskim** [comment]
Exactly.
I checked the gc.com MAp - there the permium caches are hidden as they should - in only see them in c:geo livemap

**Comment by mzielinskim** [comment]
I don't get it - after several days where I couldn't get rid of several T5 Caches - now they are gone from livemap.

**Comment by bekuno** [comment]
Did you saved them before in c:geo and deleted afterwards?

**Comment by mzielinskim** [comment]
First i didnt save them in c:geo but they were shown. I deleted them from the ignorelist on gc.com and readded via c:geo - still shown on map. Then i saved in c geo and selected again ignore - then the saved data was deleted - still I saw the cache on the livemap. After a while I checked again and then it wasn't shown anymore.
Really strange
