### ISSUE TITLE
Use unlocalized (english) values for system information

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10410]
Nothing important, just something on my wishlist:

With support mails coming in from different countries, I have seen, that the system information uses some localized strings, e.g. for a french user:

` geocaching.com: Logged in (Connect%3%9) / BASIC`
` BASE: /cgeo (D%3%9fini par l'utilisateur)[/...`
`Routing mode: %3� pied`

I have some hard time to decipher those (not only due to special chars, but also in some languages I simply don't understand).

If its possible I would prefer always to see the english strings here (if technically possible).

**Comment by fm-sys** [comment]
At some places, it can be easily changed (⇾ change). At some others it unfortunately would require large refactoring (⇾ IMHO don't change). 

BTW, do you also think that the "Paths and permissions" section are far too confusing? But is there anything here that could be omitted?

**Comment by Lineflyer** [comment]
> BTW, do you also think that the "Paths and permissions" section are far too confusing? But is there anything here that could be omitted?

At the moment I would like to leave everything in until SAF is more settled. Then we should indeed make it a bit more leightweight.

**Comment by Lineflyer** [comment]
Implemented as far as possible with #10419.
