### ISSUE TITLE
Remove (potentially) personal data from system information

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10411]
While reading some support mails, I stumbled upon this "problem":

As we include some of the content of each SAF folder (file or folder names) into the system information, it might contain personal unrelated information. E.g. a user defined his map folder to be `/Download` and our system information includes what he recently downloaded (in this case some rather personal document name with his IBAN number).

As we might want to reuse the system information in our issues, it might be wise to take out this information on mid term to avoid any inclusion of any information which discloses or affects the anonymity of users.

Maybe we leave it in for this release cycle to help debugging migration problems, but remove it on `master`.
Until then I will try to manually filter out such info before posting it here.

**Comment by eddiemuc** [comment]
Will be fixed with PR #10412

**Comment by moving-bits** [comment]
@Lineflyer 
still relevant?

**Comment by Lineflyer** [comment]
Not sure...I could not see how  #10412 could solve it but I did not check recently though.

**Comment by moving-bits** [comment]
I guess the specific number has switched some digits, but I haven't seen any folder contents (as mentioned in opening post) since a long time, and also can't remember having noticed some specifically personal data in our system log info, that's why I asked.
(But there may always be some "grey zone", eg. depending on how the user names their stored filters or their folders)

**Comment by fm-sys** [comment]
![Screenshot_20240203_091856](https://github.com/cgeo/cgeo/assets/64581222/f1e0e054-b1a9-4569-8305-89a5e4feb2f2)

Somehow related:

Filters can contain coordinates or other sensitive information. While the current active filter (Live and Offline) probably makes sense, we shouldn't show stored filters IMHO.

Not much a privacy issue but cluttering the sysinfo as well: And do we need to show all map attributions?

(Also the paths section is too long, but they provide actually benefit on support I guess...)

**Comment by eddiemuc** [comment]
> Not sure...I could not see how  #10412 could solve it but I did not check recently though.

I am pretty sure I linked the wrong PR back then. What I did though was to remove the listing of concrete files names in the folder, just counts should be present now.

The file system info was quite useful for support purposes back when SAF was fresh in c:geo. Nowadays I haven't had the need to look into it for a long time. Ok for me to remove or further reduce.

**Comment by eddiemuc** [comment]
> ![Screenshot_20240203_091856](https://github.com/cgeo/cgeo/assets/64581222/f1e0e054-b1a9-4569-8305-89a5e4feb2f2)
> 
> Somehow related:
> 
> Filters can contain coordinates or other sensitive information. While the current active filter (Live and Offline) probably makes sense, we shouldn't show stored filters IMHO.

Filter info was very useful for support back when the filtering system was new. Now that this is stable in prod I haven't used it for a long time. Ok for me to remove.

**Comment by moving-bits** [comment]
> Filter info was very useful for support back when the filtering system was new. Now that this is stable in prod I haven't used it for a long time. Ok for me to remove.

We still get requests on support like "can't see caches on map", which can be resolved by pointing the user to their specific filter configuration, thus I would like to leave this info in, at least for the default filters (LIVE / OFFLINE). (Getting coordinates in a filter is rare on support, not sure if I have ever seen them.)

But we should be sensitive when posting system info on GitHub, probably cut out some details. At least for issues that come from support we still do have the details in the related support ticket.

With regard to the path info: Shortening seems like a good idea. Maybe the following would be enough?
- display uri, but replace %-formatted characters by their "readable" equivalents (would still give us the path + the content provider, which some users tend to remove access rights from...)
- file info: not sure if we can make this more compact? maybe #files + their size + available free space?
