### ISSUE TITLE
Ignoring caches

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#10425]
## What function are you missing
Receive the data from geocaching service about ignored caches. Ignored caches should not be shown on the map. 
There should be button in the cache page in cgeo to ignore/not ignore cache (similar to watching)

## Additional context

I'm not sure, maybe it already exists..

**Comment by SammysHP** [comment]
In some situations ignored caches seem to be shown on the map. See #10402 and #9445.

**Comment by okainov** [comment]
Ah, okay, I haven't checked code before, now I see there is already `IgnoreCapability` existing and presumably working at least for GC.com (premium?) and OC, so I'll close this issue, that's exactly what I needed :D

We will probably implement something like this in gc.su and I'll add corresponding code in c:geo when ready.
