### ISSUE TITLE
Newly created custom cache should be added to active list

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#10427]
## What function are you missing

When you create a new custom cache by long pressing on the map view, after creating it, it immediately becomes invisible. The reason is that instead of adding it to the currently active list, as would be natural, it gets added to the custom cache list. One always has to go back, select the "all caches" list, to see the newly created custom cache together with the current list.

## Suggested solution

A newly created custom cache should get added to the currently active list. 

One could even think about removing the special custom cache list completely. I don't see its usefulness (but maybe other people do?).

**Comment by moving-bits** [comment]
In the beginning it was like this (when possible), but there has been an explicit feature request to store UDC on a dedicated list, see #8678.

A possible solution could be to introduce a setting:

Store new user-defined caches
- on current list (if available)
- always on list "user-defined caches"

**Comment by dcjkfgdjhd** [comment]
An option would be a great solution of course.

**Comment by fm-sys** [comment]
Or an option to choose the list in the create dialog, which IMHO would have even more value...

**Comment by dcjkfgdjhd** [comment]
I would actually prefer a permanent setting. 

For me the only reasonable behaviour is adding it to the current list, because otherwise you create a new custom cache and it is immediately invisible. For me that NEVER makes sense. So I would prefer not having to choose this everytime I create a custom cache. 

In particular, since when you plan a custom route, you often have to create LOTS of custom caches.

**Comment by moving-bits** [comment]
One could persist that setting, so that on creating the next UDC, the last setting is used as default.
