### ISSUE TITLE
Add to watchlist does not work

### ISSUE THREAD

**Issue by capoaira** [cgeo/cgeo#10437]
## Bug description 

Add to watchlist does not work 

### Steps to reproduce the problem

1. Open a Cache
2. Cick the + symbol to add the Cache 
3. See error. Message: "Ändern der Watchlist nicht erfolgreich"

### Expected result after these steps 

The cache should be added to the watchlist 

## c:geo version 

2021.04.21

## Additional context 

I think that because of the changes by GS

**Comment by Lineflyer** [comment]
Confirmed, seems also to be caused by website change.

**Comment by Lineflyer** [comment]
does work again with 2021.04.22-NB1 (which include the login and owner fix)
