### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10434]
Not sure whats going on, but it seems some new redirects are involved (which I never seen before).
Might also be a temporary server problem...as the website is slow in general but login with browser however works.

```
2021-04-21 21:02:56.762 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] POST https://www.geocaching.com/account/logout
2021-04-21 21:02:57.577 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] 403 [Forbidden] (815 ms) POST https://www.geocaching.com/account/logout (http/1.1)
2021-04-21 21:02:57.584 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] GET https://www.geocaching.com/account/signin
2021-04-21 21:02:57.780 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] 200 (196 ms) GET https://www.geocaching.com/account/signin (http/1.1)
2021-04-21 21:02:57.911 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] POST https://www.geocaching.com/account/signin
2021-04-21 21:03:05.136 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] 200 (7225 ms) POST https://www.geocaching.com/account/signin (http/1.1) (=> https://www.geocaching.com/play/search)
2021-04-21 21:03:06.110 6468-6844/cgeo.geocaching I/cgeo: [network--5] Failed to log in Geocaching.com as Zubu for some unknown reason
2021-04-21 21:03:06.136 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] GET https://www.geocaching.com/play/culture/set?model.SelectedCultureCode=en-US
2021-04-21 21:03:19.883 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] 200 (13747 ms) GET https://www.geocaching.com/play/culture/set?model.SelectedCultureCode=en-US (http/1.1) (=> https://www.geocaching.com/play/search)
2021-04-21 21:03:20.910 6468-6844/cgeo.geocaching I/cgeo: [network--5] changed language on geocaching.com to English
2021-04-21 21:03:20.952 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] GET https://www.geocaching.com/account/signin
2021-04-21 21:03:32.383 6468-6845/cgeo.geocaching D/cgeo: [OkHttp] 200 (11431 ms) GET https://www.geocaching.com/account/signin (http/1.1) (=> https://www.geocaching.com/play/search)
2021-04-21 21:03:33.617 6468-6844/cgeo.geocaching W/cgeo: [network--5] GCLogin.login: failed to find request verification token
```

**Comment by geocachermgo** [comment]
I'm also not able to log in with c:geo but website works

**Comment by Lineflyer** [comment]
The behavior is changing...from timeout now to "Login page parsing error". Lets wait a bit until we get a clear picture.
I will batch reply the 50+ support mails :(

BTW: Those login issues would be another reason to try the API instead...however not sure if its more stable/reliable/available.

**Comment by Lineflyer** [comment]
The situation looks like a real login issue. Server is working fast but always failing with "Login failed: Failed Login page parsing".
It seems we have another website regression to fix... :(

**Comment by bekuno** [comment]
Looks like the same I run into yesterday. :(

**Comment by bosorcicka** [comment]
It started after todays update of cgeo for me.

**Comment by Lineflyer** [comment]
@bosorcicka We are quite sure, its unrelated to our new version. Beside the fact, that we issued a new release because of changes, and now we have more changes.

**Comment by Lineflyer** [comment]
Anyone working on it / looking into it?
Sadly we released only today...but we can release again starting tomorrow ;))))

**Comment by moving-bits** [comment]
> Anyone working on it / looking into it?

Yeah, I'm already deep into debugging and regexp-ing...

**Comment by bosorcicka** [comment]
I don't now, if cgeo is caching login, but I today used it all day, was stared and closed and was working and login without problems.
Now I did update and the login stoped to work...

**Comment by moving-bits** [comment]
That depends on when their website has been changed.
I've been using the new release already for a few hours without any problems until it started to fail.

They had a website change regarding links to their search site yesterday which made detection of cache type and cache owner starting to fail, and today they seemingly have changed something regarding the login procedure.

**Comment by Lineflyer** [comment]
> That depends on when you have logged in and their website has been changed.

And - of course - it has something to do with the login cookie.
While the session is running you probably won't notice a problem. But an app update of course triggers a new login which then fails.

@moving-bits 
Thanks for digging into this.
Typically in such weeks more changes might drop in while they deploy their updates batch by batch. I will merge the change to test on nightly and lets wait until tomorrow to see if all stays working.

**Comment by Lineflyer** [comment]
Further clarification ongoing (see #10436), so lets wait until we sorted this out.

**Comment by MagpieFourtyTwo** [comment]
First of all: GREAT WORK!  Thanks A LOT!  Whenever we meet: First beer will be on my tab!  ;)

Nevertheless, have to report a glitch, other's may stumble upon, too:
Although I updated to 2021.04.22-NB1-1869dd6 a few minutes ago, login still failed for me ...
until I updated authorization via ``Settings`` => ``Services`` => ``geocaching,com`` => ``Update or remove authorization`` => ``Check authentication again``. Once c:geo stated ``authorized`` it worked again.

But it's teeeeeeeerriblyyyyyy sloooooooooowww ... authorization refresh took about half a minute ... refreshing a cache currently takes about 15 secs.  Seems as if gc.com's development department has once again done a full job.  :/

However: Thanks again, guys!

P.S.: Login for extremcaching.com still doesn't work, but this is probably related to their SSL-Problems.
PP.S:: To whom it may concern: An adapted version of GC little helper II is online, too - cacher's life can go on!  ;)

**Comment by Lineflyer** [comment]
> But it's teeeeeeeerriblyyyyyy sloooooooooowww ... authorization refresh took about half a minute ... refreshing a cache currently takes about 15 secs. Seems as if gc.com's development department has once again done a full job. :/

@MagpieFourtyTwo
Excellent observation. I did also in parallel stumble upon this, but also noticing, that the website is fast. Its indeed our problem: #10440

**Comment by moving-bits** [comment]
> First of all: GREAT WORK! Thanks A LOT! Whenever we meet: First beer will be on my tab! ;)

Hope we'll be able to get to that some time soon... Hopefully we will be able to do a c:geo meetup in real life at the GlückAuf 22 mega at the latest? Anyway, thanks for testing & for your feedback!

> But it's teeeeeeeerriblyyyyyy sloooooooooowww ... authorization refresh took about half a minute ... refreshing a cache currently takes about 15 secs. Seems as if gc.com's development department has once again done a full job. :/

Yeah, due to us checking for English language setting (needed for some parsing) and the related HTML having been removed, we do an extra "switch language" and "relogin" step on each call, making it three times the necessary calls. I'm trying to fix that with #10443.

**Comment by MagpieFourtyTwo** [comment]
> I'm trying to fix that with #10443.

Just installed and compared:
- Refresh of an offline stored cache: Before: 15+ secs, after: 8-9 secs.
- Opening cache listing from map: Before: 10-12 secs, after: 5-6 secs.

This I would call a success!  ;)

**Comment by MagpieFourtyTwo** [comment]
> GlückAuf 22 mega at the latest

Maybe even already at [GCmeetsBC](https://coord.info/GC8Y812) ...?
Let's keep fingers crossed ... but even if not, I'll keep my tab clear! ;)

**Comment by geocachermgo** [comment]
Was the meetup discussed earlier? I've put that on my list.

**Comment by moving-bits** [comment]
> Was the meetup discussed earlier? I've put that on my list.

No, no formal meetup planned currently, just the hope that we will be able to meet "in 3D" some time soon in general. IIRC the last time members of the c:geo team were able to meet at some event was at the [Project Geocaching meets Beethoven](https://coord.info/GC7TKKG) mega event in Bonn last year in spring.
