### ISSUE TITLE
"Automatic download" improvement

### ISSUE THREAD

**Issue by ray4423** [cgeo/cgeo#10445]
## What function are you missing

settings/Map/"Automatic download" is not "automatic".
"Automatically check for update of map and theme files" -> "remind for update of map and theme files"

I expect "Automatic download" to
1. c:geo check the update, download and notify me "map is updated" with no overwrite confirmation messages
or
2. c:geo check the update and notify me "updates found, do you want to download?"

## Suggested solution

settings/Map

**Automatic download**
Automaticlly check for update of map and theme files ☑
  and download (overwrite files)         ▢

**Update interval**
check for update every xdays
-o------------------------- 7
**[check for update now]**

**Comment by MagpieFourtyTwo** [comment]
Automatic download is of course a nice thing, but should happen over WiFi only.
In fact even checking for updates is not that time critical, so even the check should be suppressed while using mobile data (at least by default).

**Comment by moving-bits** [comment]
> Automatic download is of course a nice thing, but should happen over WiFi only.

Here I would like to contradict, as you don't have WiFi available always when you would like to download something. So we should (we do) give the user the choice.

**Comment by moving-bits** [comment]
Thanks @ray4423 for your feedback.

> settings/Map/"Automatic download" is not "automatic".

You are right, it's not an automatic download but an automatic reminder by which you can trigger the update check and eventually the download, if needed.

> I expect "Automatic download" to
>     1. c:geo check the update, download and notify me "map is updated" with no overwrite confirmation messages
>        or
>     2. c:geo check the update and notify me "updates found, do you want to download?"

My thought behind this was to rather not trigger any potentially high-traffic action, especially not automatically downloading a multi-megabyte map or routing tile data file - the user may be having bad signal reception, no data plan or being abroad without roaming. So I decided to always display a message before starting that action. Also an purely automatic download might trigger the download of several map files at the same time, even though you might want to update only a single one.

> ## Suggested solution
> **Automatic download**
> Automaticlly check for update of map and theme files ☑
>   and download (overwrite files)         ▢

I would rather stay with the extra dialog box before starting the actual check and download.

But agreed, the checkbox for automatically overwriting the files might be a good idea. Or even always overwrite an existing file on successful download? (What do you think?) Something like this would be needed anyway, if we are going to implement sort of a background download service like prototyped in #10310.

**Comment by moving-bits** [comment]
Automatic overwrite of existing files has been implemented with #10696, the other things I would like to keep as is.
