### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10451]
Firefox displayed an "certificate expired" warning while trying to access a build report:

![image](https://user-images.githubusercontent.com/3754370/115929596-5c8a3100-a488-11eb-8879-4cca1a6e23d8.png)

![image](https://user-images.githubusercontent.com/3754370/115929621-657b0280-a488-11eb-90e4-9d63e9abcbea.png)

**Comment by mucek4** [comment]
I've seen it on monitoring tools. Little late. I have fixed it.
