### ISSUE TITLE
Find count shown as 0

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10453]
Some users of 2021.04.24 report, that after "a while of usage" the find count, which was previously correct, drops to 0.
No more details yet, but three reports.

**Comment by murggel** [comment]
Same too me, if you need infos or a log, let me know...

**Comment by Lineflyer** [comment]
In can confirm. The following scenario should be sufficient to reproduce:
- Start c:geo
- Login is OK, username and correct find count shown
- Open a saved cache
- Refresh the cache

Result:
Finds show 0

**Comment by Lineflyer** [comment]
@murggel 
If you are able to find the cause and fix it, feel free.

**Comment by murggel** [comment]
> @murggel 
> If you are able to find the cause and fix it, feel free.

Ok, I hope I will find some time today

**Comment by murggel** [comment]
see PR ##10455
@moving-bits  please check the regExpr

**Comment by murggel** [comment]
Probably some problem with the regExpr for #10454 (owner)?
