### ISSUE TITLE
Hide or disable LC Connector in settings if not accessible for user

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10477]
Not sure whether to call this a bug or a feature request:

## Bug description / Feature request
Currently the LC connector will be shown to all users of c:geo, and can be enabled/disabled by all users, although actually the connector is only usable for users having a premium gc.com account.

LC connector should either be shown only to users fulfilling that preconditions, or be greyed-out for all others.
Currently only the description text beneath the "Activate" checkbox is greyed-out.

Alternatively add some explanation to which users can access the connector.

**Comment by Lineflyer** [comment]
Few words regarding defaults BTW:
I suggest to have it active by default for people who have activated the geocaching.com connector (and are premium members).
This will promote the feature (and therefore I suggested the default text #10472 to inform user, who don't want it, how to disable it).

**Comment by moving-bits** [comment]
> Few words regarding defaults BTW:
> I suggest to have it active by default for people who have activated the geocaching.com connector (and are premium members).

AFAICS I can set it to a fixed value only, either `false` or `true`. Currently it's set to `false` as default, and wrt to your request I would change this to `true` now. That doesn't harm, because if the user is no premium member, no calls to the API will be done, regardless of this setting.

For the original issue a PR is already merged, giving a textual explanation on the prerequisites for this service.

**Comment by Lineflyer** [comment]
@moving-bits Actually this is not fixed, isn't it?
As basic member I do see an activated labs connector after installation and authorization to gc.com. 
I can see a non greyed out menu, where I can activate/deactivate the connector but it has (of course) no effect. The only hint it the description text, which notes that it is only available to PM.
IMHO the connector should be visible and accesible but the activate switch be greyed out.

**Comment by Lineflyer** [comment]
Addon after reading the original issue text:
Users don't read any text, they see a normal connector and its active but not working. Therefore giving an explanation below is IMHO no solution to this issue, but we should make it unclickable which will potentially make the user read the text below then.

**Comment by Lineflyer** [comment]
I am sorry, that I am reopening this one, there is still a small glitch in it:

- Install newest nightly
- Rung wizard and authenticate as gc.com basic member
- Look into Settings - Services

Result:
You will see geocaching.com as Active and also "Geocaching.com Adventure Lab" as active
If you click into "Geocaching.com Adventure Lab" you will see a greyed out "Activate" function but still checked.

Expected result:
I am convinced, this will irritate many basic users.
The service should not be "ticked on" and shown as active in this scenario.

**Comment by moving-bits** [comment]
This is a tricky one...

Ok, let's try to find a solution.

What we have currently is:
- "Active" setting for LC connector defaults to true
- "Active" setting for LC connector gets greyed out when GC connector is disabled or authentification is for BM only
- LC connector does not return any results, if the user is BM only

As mentioned earlier, I cannot set the default state depending on BM status, as it is hardcoded in the XML at compile time, so we have to decide whether it defaults to true in any case, or to false in any case. 
The easiest "solution" for the problem described above probably would be to set this default value back to false. But then we would have no automatic promotion for PM users. (But, hey, they could read our readme ;-))

A more elaborate solution would be to reset activation to false, if GC gets switched off, or if authorization is reset to a BM only.
(But that would not cover the migration scenario, when the user does not touch the GC connector's status.)

As this is more a migration issue, I tend to set the default back to `false`.

What do you think?

**Comment by Lineflyer** [comment]
What about hiding the status "Active" in the list of all services under the condition , that the content is greyed out anyway (=BM) Would that be an easier workaround implementationwise?

**Comment by moving-bits** [comment]
You're talking of the summary page in the wizard only? (And leave the service settings' pages as is.) That should be easy to adapt.

**Comment by Lineflyer** [comment]
Not in the wizard (did not check that), but the view when you open Menu - Settings - Services.

**Comment by moving-bits** [comment]
Ok, I gave it another shot with #10525 - the "active" info in the services summary for the LC connector will be set to true, if all the the following three conditions are met: LC connector active + GC connector active + successful authorization as PM (actually: the internal flag for GC PM is set).

BTW: I also checked the wizard's screen: LC connector currently won't be listed here anyway, as in its current level it's a connector without requiring (individual) authorization, and those won't be listed here.

**Comment by Lineflyer** [comment]
@moving-bits Looking good for me now. Can we close here?

**Comment by moving-bits** [comment]
> @moving-bits Looking good for me now. Can we close here?

Yes
