### ISSUE TITLE
Include main description for ALC?!

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10478]
## What function are you missing

I know we discussed this in a team meeting and decided about the first implementation (and to not include the description).
But just now I have seen, that the main description is available to everyone in the web also outside the API and without any login (e.g.: https://adventurelab.page.link/KSQT ).
This makes me somehow reconsider this decision....and it would also make the implementation IMHO more complete by not only showing the title, which is probably no decision helper, whether a user wants to play that adventure, but a set of basic information.

## Suggested solution

Use the public API to include that, maybe prepended by a default text (See #10472)

## Alternatives/workarounds

Sorry for bringing up this point again after we first decided, but for me its a difference to provide an information which can only be seen by technical means of an API or dedicated to a certain app on contrary to showing an information which is plainly available in a web browser (which is the case for the main description)

## Additional context

This is "Feedback needed"

**Comment by jakedot** [comment]
I'm all for it. Prepending it with a default text can't hurt, kind of like the same as the disclaimers "this listing may not be displayed properly" (because tables etc.) or the "this listing has a checker on gc.com"

Could we have another issue to discuss what features we'd like to have in general, and what's possible at all?

**Comment by Lineflyer** [comment]
> Could we have another issue to discuss what features we'd like to have in general, and what's possible at all?

We should wait for that until we have further details regarding the future of the public API and the conditions of the partner API.
We are in discussion with Groundspeak and at least want to try to make this one kind of official. Not sure, if this will ever be the case. But for now we try to stick by their recommendation of what to show and when to handover to their app.
