### ISSUE TITLE
Provide more prominent name for labs.geocaching.com connector

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10473]
## What function are you missing

"labs.geocaching.com" will probably be unknown to the average Geocacher. We should use a more descriptive connector name.

## Suggested solution

"Groundspeak Adventure Lab"

## Alternatives/workarounds

"Geocaching.com Adventure Lab"

**Comment by moving-bits** [comment]
I would also propose to display the LC connector directly beneath the GC connector
