### ISSUE TITLE
Merging release needs conflict resolution

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10488]
Due to the rather large change merged into `release` (PR #10447) merging `release` into `master` needs a conflict resolution in quite some files.
Has to be done by someone familiar with the changes.

**Comment by eddiemuc** [comment]
While I am familiar with the PR in question, I have never done a merge from release to master.

Since I am very afraid to destroy something on the way: can you send me the exact sequence of git commands you usually use? Do you push these merged directly to master or via PR?

**Comment by moving-bits** [comment]
I'm using the following sequence:
- go to your local copy of the "original" c:geo repo (having "origin" set to the online c:geo repo, not to your fork)
- `git checkout release`
- `git pull`
- `git checkout master`
- `git pull`

Without any merge conflicts, this is finished with a `git push`.

If there are any merge conflicts, as in this case, I insert the following steps:
- resolve merge conflicts locally, using `git add <filename>` on any resolved file
- finish resolving conflicts with `git commit -am "merge branch 'release' (with conflict resolution)"`

After that, I `git push` the result back to `master`. Be aware: This is not a PR, this is pushing directly into the original repo...

If you prefer, we can do this together via a online conference/chat this evening.

**Comment by Lineflyer** [comment]
@moving-bits 
I think you forgot the most important part at the end of your first list:
`git merge release`

**Comment by Lineflyer** [comment]
After `git merge release` it will show you:
```
$ git merge release
Auto-merging main/src/cgeo/geocaching/settings/SettingsActivity.java
CONFLICT (content): Merge conflict in main/src/cgeo/geocaching/settings/SettingsActivity.java
Auto-merging main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java
Auto-merging main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
CONFLICT (content): Merge conflict in main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java
Auto-merging main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
CONFLICT (content): Merge conflict in main/src/cgeo/geocaching/maps/google/v2/GoogleMapActivity.java
Auto-merging main/src/cgeo/geocaching/maps/CGeoMap.java
CONFLICT (content): Merge conflict in main/src/cgeo/geocaching/maps/CGeoMap.java
Auto-merging main/src/cgeo/geocaching/maps/AbstractMap.java
Auto-merging main/src/cgeo/geocaching/activity/AbstractActivity.java
Auto-merging main/src/cgeo/geocaching/MainActivity.java
Auto-merging main/src/cgeo/geocaching/InstallWizardActivity.java
Auto-merging main/src/cgeo/geocaching/CacheListActivity.java
Automatic merge failed; fix conflicts and then commit the result.
```

Then git stays in merging state indicated by `(master|MERGING)` and you can do the resolution and commit the result at the end as described by @moving-bits 

As you can see above you need to look into the 4 conflicting files, wich contain divider titled `release` and `HEAD` which show the conflicting content from each branch.

**Comment by moving-bits** [comment]
> I think you forgot the most important part at the end of your first list:
> `git merge release`

Oops, you're right - had that in mind, but didn't wrote it down - next Skype call was ringing already... Added it now.

> While I am familiar with the PR in question, I have never done a merge from release to master.
> Since I am very afraid to destroy something on the way: 

I remember having the very same feeling when I started doing merges "in the live system". It's actually not that different from doing merges in the local system, but I still double-check every command before doing `git add` / `git push` when working with the live system. Also I always do a local compile before adding / pushing files during/after conflict resolution.

**Comment by eddiemuc** [comment]
So you simply update local branches master and release from c:geo (not from own fork) and then simply use "merge" (and not "rebase")? 

And you really push directly to master? Do I even have the permission to do this?

Anyway, with merge conflicts I am very familiar :-) that won't be a problem.

**Comment by fm-sys** [comment]
>  "merge" (and not "rebase")?


`Rebase` would require a force push, therefore `merge` is the correct way to go, which simply adds a merge commit.

**Comment by fm-sys** [comment]
Oh, and you have to apply the crowdin merge configuration (as they should be ignored while merging). Don't know how to do that, but it's described somewhere in the wiki

**Comment by Lineflyer** [comment]
Its described directly in the repo as remark of `.gitconfig`:
https://github.com/cgeo/cgeo/blob/master/.gitconfig

And the `.gitattributes` need to be fine on both branches (but should be if you clone it):
https://github.com/cgeo/cgeo/blob/master/.gitattributes

**Comment by Lineflyer** [comment]
> Rebase would require a force push, therefore merge is the correct way to go, which simply adds a merge commit.

Exactly. As we want to be able to fast-forward `release` to the HEAD of `master` from time to time (to prepare a new feature release) rebasing would break the fast-forward as it creates a new commit containing the diff instead of applying all commits from one branch to the other (via the merge commit).

**Comment by Lineflyer** [comment]
> And you really push directly to master? Do I even have the permission to do this?

@eddiemuc Yes, you have. Only the branches are protected, so a force push would be rejected. 

I suggest you try together with @moving-bits or myself tonight. Just let us know.
BTW: As long as you don't force any action (which is not allowed (see above)) you can hardly break anything. If something went wrong we can "rewind" the branch to the commit state before it happened (that however needs a force push and requires admin access).  Still being careful is not the worst idea ;)

**Comment by eddiemuc** [comment]
> Its described directly in the repo as remark of `.gitconfig`:
> https://github.com/cgeo/cgeo/blob/master/.gitconfig

So you say before the merge I should issue

 `git config --local include.path ../.gitconfig`

?

**Comment by Lineflyer** [comment]
Yes, assuming you are in the base folder of your repo.
It will simply apply the content of `.gitconfig` located in our repo as part of the local repo git configuration.

And make sure the file `.gitattributes` is existing in your repo.

**Comment by eddiemuc** [comment]
Ok, did issue the command, and `.gitattributes` is present. Will do the merge later this evening when I find the time.

Out or curiosity: `.gitconfig` seems to apply the "ours" merge strategy globally to **all** files (at least I don't see anything restricting this to crowdin files), I don't quite get why this would then only be applied to crowdin files and not to all others. If anyone finds the time I would appreciate some enlightment.

**Comment by fm-sys** [comment]
See https://github.com/cgeo/cgeo/pull/9296. IIRC there were some nice comments in the edited files...

**Comment by eddiemuc** [comment]
Ok, I just merged and pushed. Fingers crossed...

**Comment by eddiemuc** [comment]
Damn it, Codacy complains about unnecessary import statements. I knew pushing to master is not a good idea...

**Comment by Lineflyer** [comment]
Did not look into details, but the commit history on `master` does not look so bad.

**Comment by moving-bits** [comment]
Then let's close here, thanks @eddiemuc for resolving the conflicts.
