### ISSUE TITLE
LC needs to be stored for settings as found 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10501]
## Bug description 

LC needs to be stored. Otherwise  "set as found" is not displayed. 

### Expected result after these steps 

Cache should be stored automatically in the default list and "set as found" should always be available

**Comment by moving-bits** [comment]
Do you mean
- always show the menu entries like "set as found" etc. (for the cache types supporting this)
- and on selecting such a menu entry, store the cache to default list if it is not yet stored

?

**Comment by fm-sys** [comment]
Yes, exactly. Sorry, I had not much time, as I wrote this issue while being on the road...
