### ISSUE TITLE
Move routing related map options to navigation settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10502]
Seeing that the Settings - Map get bigger and bigger I just thought it might be logical anyway to move the new sub chapter "Offline Routing" from maps to Settings - Navigation?!

IMHO it fits in quite good into the topic "Navigation" and the navigation menu contains only a few items...would be better balanced.

**Comment by Lineflyer** [comment]
@moving-bits What do you think?

**Comment by moving-bits** [comment]
Will have a look at it. But we should move the "navigation" part closer to the "map" part then, IMHO.

**Comment by Lineflyer** [comment]
Don't change more than necessary
More confusion to users and more work for changing the user guide ;))

**Comment by moving-bits** [comment]
OTOH: If we change a bit of it with this version, and another bit with the next, wouldn't that confuse users even more?

**Comment by moving-bits** [comment]
See #10507 - I've kept the position of "Offline routing / Navigation" entry as is (for now ;-))
