### ISSUE TITLE
Integrate Pocket Query Creator and/or remove link as useful app

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10523]
## What function are you missing

Some users on support mail used to use the pocket query creator app (in conjunction with c:geo). Due to the latest website changes, PQC is however no longer working (login issue).

## Suggested solution

As the app looks unmaintained on Github, maybe its possible to integrate such feature into c:geo instead.
Anyway also it should be removed from the useful app list, if it won't be fixed.

## Alternatives/workarounds

I opened an [issue](https://github.com/robneild/pocket-query-creator/issues/21) on the PQC repo to ask for fix and for an information about the license of this code.

## Additional context

https://github.com/robneild/pocket-query-creator

**Comment by moving-bits** [comment]
I've created #10524 for removal from useful apps list

**Comment by Lineflyer** [comment]
Lets give them a chance to react first.

**Comment by bekuno** [comment]
The app is licensed with GPL v3, see https://github.com/robneild/pocket-query-creator/blob/master/LICENSE.

Perhaps @pstorch has other contact information (as he has also been developing the app since 2014).

**Comment by pstorch** [comment]
Long time ago I also distributed a little bit to PQ Creator. I have an eMail-Adress of Rob. If you like I can try to reach him.

**Comment by moving-bits** [comment]
@Lineflyer @pstorch 
Any news on this?

**Comment by Lineflyer** [comment]
Not from my side. The issue I opened in their repo is unanswered. I guess this tool is no longer maintained. 

Seems we should remove and maybe file an feature request issue to take this functionality over to c:geo. ;)

**Comment by moving-bits** [comment]
Ok, will merge the PR then.

**Comment by bekuno** [comment]
> 
> 
> Long time ago I also distributed a little bit to PQ Creator. I have an eMail-Adress of Rob. If you like I can try to reach him.

@pstorch 
No answer from Rob so far. Please try to contact him.

**Comment by Lineflyer** [comment]
There was an answer now from Rob in my issue: https://github.com/robneild/pocket-query-creator/issues/21#issuecomment-842071261

**Comment by robneild** [comment]
I am working on a fix but I am pretty busy and may take a few weeks

**Comment by Lineflyer** [comment]
@robneild 
As also just wrote in https://github.com/robneild/pocket-query-creator/issues/21 I think this problem is still open.
Any news from your side or maybe you are interested to port the functionality into c:geo instead if you have no plan to maintain PQC any longer?

**Comment by moving-bits** [comment]
let's close due to lack of feedback
