### ISSUE TITLE
Support opening gc.com geochecker via ChromeWebview

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10526]
## What function are you missing

Users still report "loops back into c:geo" when they use "Open Geochecker" for caches which have a gc.com checker on the cache page.
Example:
- Open GC95BJ7
- Select Menu - Open Geochecker
- Selection presented contain c:geo and browsers

The affected users seem to have set c:geo as default (here or elsewhere) so that it directly loops back into c:geo

## Suggested solution

Offer Chrome Webview (at least if the checker is the gc.com checker) for "Open Geochecker"

## Alternatives/workarounds

Suggested the user to reset defaults as described in https://www.cgeo.org/faq#open-in-browser 

## Additional context

Ticket #199550

**Comment by fm-sys** [comment]
I think this should be easy to fix. PR will follow...
