### ISSUE TITLE
supportsRefresh() for ALCs

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#10527]
I just noticed that when in CacheDetailActivity on an ALC, the "refresh" option has been removed. I do not know yet how I can track when that change was made and by whom, nor do I understand, why this capability has been removed. Was there a design discussion that I have missed? All I know is that in the initial PR that functionality was available. There may be good reasons, however, it could also be a bug? could anybody shed some light into this? Also, if there is a reason to remove that capability, then it should be removed from list views too. Currently, if I store ALCs into a list and go to: "Manage Caches -> Refresh All", the ALCs will be refreshed, which is exactly what I had actually expected to happen.

Now directly on the topic at hand: Manually setting the found state was most likely introduced for user-defined caches, those with a ZZ geocode right? For some reason ALCs now also have these capabilities to manually set the found state. Unfortunately, if I refresh the adventure from the servers that state is lost (which might be the reason why the refresh capability has been removed from CacheDetailActivity?). Of course I can still click the trash can in CacheDetailView and the download the adventure again, same results, the manually assigned found state is gone.

Update: I have done some code scans and greps. It seems the refresh (or reload) capability comes in via `cache.supportsRefresh()`. and that looks like:

```
public boolean supportsRefresh() {
        return getConnector() instanceof ISearchByGeocode && getConnector() instanceof ILogin;
    }

```
Could it be that it was actually me who killed it by removing the `ILogin` capability from the connector? If that is true, what if a connector can actually do the refresh without rquiring a login context? And also, if this method returns `false` here, why is it still possible to do a refresh when the ALC  shows up in a list? I would assume, the `supportsRefresh()` is not checked there. Will continue to investigate...

PS: I have just removed the `&& getConnector() instanceof ILogin` from the code shown above and the refresh capability is back so at least my understanding of the code is improving ;)

So how do I fix this now? Adding an ILogin capability to the connector and make it always return a good logged in state?

_Originally posted by @baiti in https://github.com/cgeo/cgeo/pull/10514#issuecomment-831245028_

**Comment by baiti** [comment]
I now have added a fake `ILogin` capability to the connector and it brings back the `cache.supportsRefresh()` capability, however, it causes side effects, for instance on the main screen where my login state at GC is shown, here is now an additional line for LCs, e.g.

`LC . (0) .` ... which is ugly and  not really helpful.

So I believe adding the ILogin capability is not the right thing to do, I rather question the logic:
```
public boolean supportsRefresh() {
        return getConnector() instanceof ISearchByGeocode && getConnector() instanceof ILogin;
    }
```
Is it really required to check for an ILogin capability here? (This is in models/Geocache BTW)
What breaks if we make it:
```
public boolean supportsRefresh() {
        return getConnector() instanceof ISearchByGeocode;
    }
```

**Comment by moving-bits** [comment]
have seen this issue too late, see my comment in https://github.com/cgeo/cgeo/pull/10514#issuecomment-831474455

**Comment by baiti** [comment]
> have seen this issue too late, see my comment in [#10514 (comment)](https://github.com/cgeo/cgeo/pull/10514#issuecomment-831474455)

I am continuing the discussion here. For some background read the comment referenced above.

Until recently we had only one cache type (ZZ) where we don't have a providing platform behind it. Conesquently there was never a "Refresh" from any server. A manually set "found state" could never be wiped out, it was persisted for the eternal future.

Now we have ALCs, where we in fact have a providing platform behind it. Unfortunately the API we use, does not get us the true found state. So LCs are a good candidate for being treated like ZZs with respect to a manually assigned found it state, however as opposed to ZZs there is a refresh capability from  the providing platform and this will come back setting the found state hard coded to false.

During the refresh, `searchByGeocode()` gets invoked, which undonditionally creates an new instance of a Geoache object. Even if I don't do a `cache.setFound()` the constructor will initialize it to `null` (why not `false`? Didn't know that a Boolean can be initialized to anything other than `true` or `false`) At this time I don't have an idea on how to fix this.

We could implement a `refreshCache(cache)` but this would then have to be provided by all connectors. `refreshCache(cache)` would need a reference to an already existing Geocache object and all properties except  `found` should be updated from data received from the server.

Ideas? Thouhts?

**Comment by baiti** [comment]
checkout LCapi:
```
if (DataStore.isThere("LC" + uuid, "", false)) {
      cache.setFound(false);
}
```

I believe it addresses the refresh case by not touching the found state if the cache is already in the DB.

**Comment by moving-bits** [comment]
Cannot look in the source currently, but doesn't `cache.setFound(false)` set the found state to "not yet found"? (and `true` being "found" and `null` being "don't know"?

AFAIK `false` does not mean "don't touch the found state" but "set it to not yet found".

**Comment by fm-sys** [comment]
> `null` being "don't know"?

Yes.

> AFAIK `false` does not mean "don't touch the found state" but "set it to not yet found".

That's exactly the tricky problem. `false` means explicitly not found (e.g. you have removed the found log and want to refresh the cache). Therefore, we need to use `null` so the found state gets applied via the "gather missing from other cache object" method... Tested it in the emulator and the PR works just fine

**Comment by Lineflyer** [comment]
The refresh is now working, isn't it?

**Comment by baiti** [comment]
> The refresh is now working, isn't it?

Yes, I believe so.
