### ISSUE TITLE
ALC related bug: manually set found state wiped out in certain circumstances

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#10545]
## Bug description 

For specific geocache types such as `ZZ` and `LC`, where a true "found state" cannot be obtained from a providing platform, a capability has been introcuded with: https://github.com/cgeo/cgeo/issues/10484 to allow the user to manually control this state.
There is a bug in the LC related code that unconditionally resets that state to "not found" if an LC cache is in a list and caches in that llist are refreshed from their servers.

Among other things, this bug has been addressed by PR https://github.com/cgeo/cgeo/pull/10528, however this PR didn't make it through the review timely enough to be integrated into the feature release mentioned above.

## c:geo version 

feature release (#10484)

**Comment by Lineflyer** [comment]
What I can see (and also reported by beta users) is, that when I set a ALC to found, it keeps showing unfound on the live map, but when I access the details again it still shows as Found. 
Is that, what you mean or another bug?

**Comment by baiti** [comment]
> What I can see (and also reported by beta users) is, that when I set a ALC to found, it keeps showing unfound on the live map, but when I access the details again it still shows as Found.
> Is that, what you mean or another bug?

Yes, that is all part of exactly the very same bug and all ot it is fixed in the upcoming PR ;)

**Comment by moving-bits** [comment]
#10528 is merged meanwhile. Does that mean that we can close this issue here?

**Comment by baiti** [comment]
> #10528 is merged meanwhile. Does that mean that we can close this issue here?

Yes .... I opened it because @Lineflyer asked me to.

**Comment by moving-bits** [comment]
Ok, thanks, then let's close here now
