### ISSUE TITLE
Adventure Lab D/T rating? 

### ISSUE THREAD

**Issue by Vike91** [cgeo/cgeo#10546]
User feedback on Facebook: are the D/T ratings on Adventure Lab caches accurate and really necessary on the app? Maybe they can be tweaked to reflect the actual rating on the adventure Lab?

**Comment by baiti** [comment]
Since there is now notion of a difficulty, nor of a terrain, I have removed those properties from LC caches now.

**Comment by baiti** [comment]
fixed with https://github.com/cgeo/cgeo/pull/10528
