### ISSUE TITLE
Add possibility to save/load filter configurations

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10559]
Following Wilhelm Busch ;) there is of course already a new idea, borne while playing with it: Now that I have constructed a really complex filter (to BTW find exactly what I was looking for - REALLY great!) I would love to be able to save this painstakingly constructed filter in e. g. a personal filter set, Or to ex/import the SQL statement ...  or copy/paste it, to e. g. store it in a text file ... :)

Would be great if you would put this on the wish list ...  ;)

However, I'm *really* glad with the way this is looking right now. Great work! Congrats! My hat is off to you.

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/10147#issuecomment-834866609_

**Comment by MagpieFourtyTwo** [comment]
Today en extension of the "Personal Filter Set" came to my mind: What if there would not just be a list of saved filters, from which one filter can be restored, but if these would even have a tick box, to en/disable the corresponding filter, allowing an AND (or probably even an OR) combination of the selected filters?

**Comment by fm-sys** [comment]
Sounds a bit like nested filters (which would be pretty cool, but I don't know if it would worth it)

**Comment by eddiemuc** [comment]
> Today en extension of the "Personal Filter Set" came to my mind: What if there would not just be a list of saved filters, from which one filter can be restored, but if these would even have a tick box, to en/disable the corresponding filter, allowing an AND (or probably even an OR) combination of the selected filters?

I indeed already thought about a filter to select/deselect saved filters. Few obstacles on the way (e.g. such complex filters are for sure no longer translatable to a web API of the connectors, and what to do if someone deletes a filter which is used in another filter?). But it's on my personal list.

I have to ask for some patience though. Weather is currently far too good for programming

**Comment by MagpieFourtyTwo** [comment]
And even better to know about an "internal ToDo".
In fact, I'm curious if we can think of anything else that's not on your list yet.  ;)

**Comment by eddiemuc** [comment]
> And even better to know about an "internal ToDo".
> In fact, I'm curious if we can think of anything else that's not on your list yet.  ;)

Suggestions always welcome :-)
