### ISSUE TITLE
[New Filters] Add filter "Attributes to Exclude" to suppress caches with given attributes

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#10575]
The new filter system already gives the (great) opportunity to filter for attributes, *which are set* in a cache listing.
Thus, if one e. g. wants to find ``Night Caches``, he can just activate the corresponding attribute and there he goes.

The other way round is currently not possible (or at least not really usable), i. e. filtering out (suppressing) caches, which are e. g. listed as ``Night caches``, thus getting "Day Caches" only, which are in fact all those caches, which do *not* have the (positive) ``Night cache`` attribute in their listing. (And, yes, this would of course even now already be possible by setting the Attributes filter to ``Night cache`` and then ``inverse`` it, but ``inverse`` just works for "all or nothing", and adding a second criteria to an inversed filter may make things really hard to understand).

However - to be able to do so (easily), an add. filter ``Attributes to Exclude`` would be great - comparable to gc.com's selections when [creating a pocket query](https://www.geocaching.com/pocket/gcquery.aspx). The currently existing ``Attributes`` filter may then be renamed to ``Attributes to Include``. Or, another idea: The ``Attributes`` filter may get a ``Include`` vs. ``Exclude`` switch ...?

BTW: Would it be possible to get an explaining toast for the attributes (e. g. on long click)?
Esp. as there currently are Attribute icons I have never ever seen before (like e. g. the ``syringe`` (for "Vaccine allowed"? ;) ) or the ``swamp`` (for "Must wave before going down"? ;) ) or the BYOP, I only recognized by checking the SQL statement.  ;)

**Comment by fm-sys** [comment]
Seems like we really have to implement nested filters ;-)

- and
- or
- not

Inside such a filter you would be able to place any filter(s) you like. And if we have such "wrapping filters", we can even remove these global filter settings which are not enough configurable for very advanced filters but already too much for basic users...

**Comment by eddiemuc** [comment]
Nested filters will be available (might be a while, too much stuff to do first), but this specific case is imho easier solvable by simply adding a checkbox "exclude selected attributed" to the attribute filter.

As a workaround for now, if you filter ONLY for attributes, you can use the "inverse filter" to achieve the requested result

**Comment by eddiemuc** [comment]
> Seems like we really have to implement nested filters ;-)
> 
> - and
> - or
> - not
> 
> Inside such a filter you would be able to place any filter(s) you like. And if we have such "wrapping filters", we can even remove these global filter settings which are not enough configurable for very advanced filters but already too much for basic users... 

And, or and not are already fully supported. In fact, the new filter activity under the hood just creates an expression using these (and other) connectors. It is really just a matter of UI.

I even thought about a filter type "Advanced expression" or so where one could simply define a filter (or part of it) using the underlying expression language in a text field. Also on my internal list :-)

**Comment by MagpieFourtyTwo** [comment]
> As a workaround for now, if you filter ONLY for attributes, you can use the "inverse filter" to achieve the requested result

Yep, already wrote so in the OP.  ;)

**Comment by eddiemuc** [comment]
> > As a workaround for now, if you filter ONLY for attributes, you can use the "inverse filter" to achieve the requested result
> 
> Yep, already wrote so in the OP.  ;)

You're right, didn't see that. Sorry

**Comment by MagpieFourtyTwo** [comment]
What I just had to say (but did not really know, where): *Really* like the "new design" for selecting ``Size`` and esp. ``Status`` (the latter even more, as now it is even possible to filter for ``Not found``, which previously was a little bit weird ;) ).

BTW: The change log mentioned "Advanced filtering system: Available in map view" - but I can't find how ...

**Comment by MagpieFourtyTwo** [comment]
Ah, ok, found it - it's in the Quick Settings. ;)

**Comment by MagpieFourtyTwo** [comment]
But just found two bug, I guess:
1. When filtering for ``Status = [Only Not Found]`` and ``Offline Log [Contains] e``, the map of a yet un-cached region does not show any caches (expectedly), but a whole bunch of waypoints (which should not show up, IMHO)
2. When changing the 1. filter to ``Offline Log [Is Present]``, the filter will still show up as ``Offline Log:d,Status`` (and, BTW, the result will be the same as above)

Are these bugs for real and if so, is there an issue to mention them or should I open e new issue?

**Comment by eddiemuc** [comment]
> But just found two bug, I guess:
> 1. When filtering for ``Status = [Only Not Found]`` and ``Offline Log [Contains] e``, the map of a yet un-cached region does not show any caches (expectedly), but a whole bunch of waypoints (which should not show up, IMHO)

Hm, have to check that. Maybe waypoint filtering does not automatically consider cache filtering.

> 2. When changing the ``Offline Log`` part of the 1. filter to ``Offline Log [Is Present]``, the filter will still show up as ``Offline Log:d,Status`` (and, BTW, the result will be the same as above)

If I understand correctly, you changed the filter, but still the previous filter stayed active (and was shown as such). This would be a bug of course.

> 
> Are these bugs for real and if so, is there an issue to mention them or should I open e new issue?

Sure, go ahead and open issue I expect a few to come up anyway :-)

**Comment by eddiemuc** [comment]
> > 1. When changing the `Offline Log` part of the 1. filter to `Offline Log [Is Present]`, the filter will still show up as `Offline Log:d,Status` (and, BTW, the result will be the same as above)
> 
> If I understand correctly, you changed the filter, but still the previous filter stayed active (and was shown as such). This would be a bug of course.

Checked this. This seems to be a pure representation error. As you probably figured out already, the functionality how to calculate a "user-displayable text" from a (probably complex) filter expression is not quite finished yet. In the case above, the Offline Log Filter simply returns the value of its internal "text field" regardless of the "offline log filter type" being set to "is present" - which in your case was still set to the set from step 1. Will fix this of course.

But the filtering itself seems to work (if I understood you correctly, the filter result would be the same anyway)

**Comment by eddiemuc** [comment]
> What I just had to say (but did not really know, where): _Really_ like the "new design" for selecting `Size` and esp. `Status` (the latter even more, as now it is even possible to filter for `Not found`, which previously was a little bit weird ;) ).

Thank you :-)

**Comment by eddiemuc** [comment]
> Ah, ok, found it - it's in the Quick Settings. ;)

Yes, this was the first place which came to my mind :-) It is of course up for discussion whether this is the right place.

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo just so you know:
* both bugs you found above should be fixed with PR #10658 (available in next nightly)
* just so you are aware: you will loose one time the last filter you put onto map viewer when this PR is applied. But from there on it will be saved again. Note that since I still work heavily on this part of filtering, this might happen again now and then during the next weeks.

**Comment by MagpieFourtyTwo** [comment]
This is - of course - not only no problem at all, but even the complete opposite:
I am in fact always delighted to see the progress continuing.
And I'm really happy about the course it is taking (thanks to your tireless efforts).

**Comment by MagpieFourtyTwo** [comment]
[Map filter in Quick Settings]
> Yes, this was the first place which came to my mind :-) It is of course up for discussion whether this is the right place.

I would have expected the icon in the map's header, like it already is in list view.
Nevertheless, Quick Settings popup is of course fine (at least for me), esp. as you can immediately see the currently active filter definition (quite apart from whether one also understands the text presented - BTW: had to smile about the "Complex" keyword ;) ) - although others may again run into issues with screen space, i. e. popup scrolling ...
So, in a later stage, the filter icon may perhaps go to the map header for real and the definition string (aka "user-displayable text") may perhaps be displayed below the header, at the top of the map, like it currently is in the list view ...? This way we would even have an indicator for a filter being active (which is currently completely missing in map view).

**Comment by eddiemuc** [comment]
> I would have expected the icon in the map's header, like it already is in list view.

A potential problem here is the available space in the map header. It is already pretty crowded up there e.g. like here:

![image](https://user-images.githubusercontent.com/6909759/118466085-d23d9180-b702-11eb-9a07-5af001108b26.png)

> ...the definition string (aka "user-displayable text") may perhaps be displayed below the header, at the top of the map, like it currently is in the list view ...? This way we would even have an indicator for a filter being active (which is currently completely missing in map view).

Nice idea, I like it!

**Comment by Lineflyer** [comment]
> Nice idea, I like it!

You could simply reuse the existing "filter active" hint which is shown on map currently if a global cache type filter is active (same as in lists, where you already use it with the new filter).

**Comment by MagpieFourtyTwo** [comment]
> I would definitely prefer to have the new filter in the map (overflow) menu

Yep, like the overflow menu idea, too - and in fact this was the second place where I tried to find it.

> [Indicator for a "Filter active" in Map View]
> You could simply reuse the existing "filter active" hint which is shown on map currently if a global cache type filter is active

Thx for the link! I knew I had seen it somewhere, but could remember where.  ;)
Is there a special reason why this has not been used for the "classic" filters so far?

**Comment by eddiemuc** [comment]
Sounds good, I postede issue #10659 for this.
