### ISSUE TITLE
Status filter returns strange results 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10572]
Seems like I found a way to confuse the SQL query ;-) 

| returns only found ones (although I would have expected that only enabled ones are returned) | returns only enabled ones (although only found ones should be displayed) |
|-|-|
|![Screenshot_20210508_222652_cgeo geocaching_copy_270x585](https://user-images.githubusercontent.com/64581222/117552636-f3d8b200-b04c-11eb-84c7-814e590a03ca.jpg)|![Screenshot_20210508_222716_cgeo geocaching_copy_270x585](https://user-images.githubusercontent.com/64581222/117552638-f4714880-b04c-11eb-8405-7c4f16a19d96.jpg)|

**Comment by fm-sys** [comment]
Ok, I think I misunderstood the filter. It's the same as on the live map. So it was me who was confused, not the SQL ;-) 

But still I think that the meaning of this filter is hard to understand...

**Comment by jakedot** [comment]
Maybe we should not use these filters but rather the ones implemented in the old filter list under status. I think it is not very "advanced" to use a found/own filter that can not be separated anyway. That might be OK for a map quick setting but not so much a dedicated filter dialog. Maybe we could change the map quick settings do generate advanced filters that can be edited on demand as well?

**Comment by eddiemuc** [comment]
As you correctly guessed by now the filter is supposed to mimic 1:1 the quick map settings filter (I even reused the icons, translations and parts of the code :-) Thanks @moving-bits ). This was meant as a first step to unify filters across all places using filtering in c:geo (I remember specifically a recent issue complaining that the filters in map quick settings can't be applied in list view.

I am glad to have a discussion about this. I plan to integrate filtering in map viewer anyway, but if filter rules should be different in map viewer and list view, this will be kind of hard/impossible.

**Comment by fm-sys** [comment]
> I plan to integrate filtering in map viewer anyway, but if filter rules should be different in map viewer and list view, this will be kind of hard/impossible.

I like the idea of sharing the filter system across lists and map. This would even allow to get rid of stacked filtering which we currently have.

For example you filter a list for archived caches > show on map > show as list > change the filter to only active caches > no caches are shown anymore. With our new filtering the whole list should be shared between the activities, not only the filter results. 

Furthermore, we probably have to rethink which kind of filters should be contained in the quick settings pop-up and which should be moved into the advanced filters...

**Comment by eddiemuc** [comment]
For now I implemented a "coexistent" solution in map viewer: advanced filter is selecatable, in addition user can use the already known "hide" settings. I think this is a good solution in the use case of map viewer: it is simply practical to have these "hide" settings for this use case, and it would be cumbersome (many clicks...) to create/modify a complex filters for it.

If all right, I would close this?

**Comment by fm-sys** [comment]
I think we have to rethink the quick settings pop-up in total. Why should a user e.g. be able to exclude found caches, but no mysteries?

If the advanced filters would available directly with one click at map level (like quick settings pop-up), it would be the same as today (and we could avoid this duplication)

**Comment by jakedot** [comment]
I think the hybrid solution is okay, but there should be a link to the advanced filters from within the popup. Maybe if no other filtering is currently active (by global filter?) the quick button settings could be translated into appropriate filters, or maybe as a seperate filter "quick map settings"?

**Comment by fm-sys** [comment]
Just saw, that the status filter was completely refactored and is now way more understandable. Thanks for it!

I think we can close here...
