### ISSUE TITLE
Tap on notification status opens in Chrome Webview

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10584]
## Bug description 

Just noticed while tapping the "new nightly notification", that the link is now opened in Chrome Webview. While it still downloads the APK I wonder if this will lead to problems e.g. for our release notification as this URL should normally catched by the Google Play app for users to download a new release.

### Steps to reproduce the problem

- Enable Chrome Webview (Settings- Cache-Details)
- Tap on a notification on main screen (e.g. new nightly available). At the moment I raised a test notification in our nightlies which targets https://www.google.de for testing purposes

### Actual result after these steps 

Link is opened in Chrome Webview

### Expected result after these steps 

Not sure...maybe its better not to apply Chrome Webview for these links?!

## c:geo version 

2021.05.08-NB

## Reproducible 

Yes

## Additional context 

Not sure if this behavior is present since we introduced Webview, or if it is triggered by the latest changes of @fm-sys ?

**Comment by fm-sys** [comment]
Probably a side affect of  #10533 (only at master currently). I will revert the change for this specific part...

**Comment by fm-sys** [comment]
Btw, I retested it with the new nightly and cleared the status notification afterwards, so that nightly users can install the current .apk
