### ISSUE TITLE
Allow user to specify filters using expression language directly

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10582]
Allow users to specify filters directly (using filter expression language as text)

> Seems like we really have to implement nested filters ;-)
> 
> - and
> - or
> - not
> 
> Inside such a filter you would be able to place any filter(s) you like. And if we have such "wrapping filters", we can even remove these global filter settings which are not enough configurable for very advanced filters but already too much for basic users... 

And, or and not are already fully supported. In fact, the new filter activity under the hood just creates an expression using these (and other) connectors. It is really just a matter of UI.

I even thought about a filter type "Advanced expression" or so where one could simply define a filter (or part of it) using the underlying expression language in a text field. Also on my internal list :-)

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/10575#issuecomment-835774160_

**Comment by Lineflyer** [comment]
Just my few cents (without having looked at the new filter to deeply).
In order to replace the older filter at the end, the UI needs to be understandable for the average user. So whatever advanced features (like this suggested) come in, should not overwhelm the user but maybe in another submenu/to be explicitly enabled or similar.

I do need to find time however at first to take a look at the new filter...

**Comment by eddiemuc** [comment]
> In order to replace the older filter at the end, the UI needs to be understandable for the average user. So whatever advanced features (like this suggested) come in, should not overwhelm the user...

Fully agree. Let's discuss this more at a later point in time (when the more pressing holes in new filter approach are closed :-))

**Comment by geocachermgo** [comment]
Hello, today I saw a UI for the filter in another program which I found nice:
There was a list of conditions and a separate field to combine the conditions.
E.g.

  1  Title contains "Ball"
  2  Publish date < 31.3.2002
  3   Terrain 2.5
   4 Terrian 3.5
and in the Combination Editor a logical expression to combine the conditions: eg
    (3 || 4) && 2 && !1

**Comment by eddiemuc** [comment]
I know this kind of filter from CodeBeamer, where did you find it?

Personally I don't like this way of combining filters too much, but would be a valid approach of course. Problem might be that on phone (in contrast to PC) you usually don't see all filters at once and thus have to scroll a lot to get the right "numbers" for the expression.

**Comment by geocachermgo** [comment]
It was in a proprietary tool at work. And it was AND(OR(3,4),2,NOT(1)).
I don't think that a lot of users will have more than a screenfull (10) conditions.
Alternative something like a tree view could be used:
![Clipboard01](https://user-images.githubusercontent.com/43813636/117796531-7761f100-b24f-11eb-992e-cfb07e054dc8.png)
But I would consider that more difficult on a phone screen.

**Comment by geocachermgo** [comment]
What are the ideas for that part of the UI at the moment?

**Comment by geocachermgo** [comment]
Thats sound doable. I find the AND(a;b;c) is more difficult to read than (a && b && c) but that should be no problem.

**Comment by eddiemuc** [comment]
> Thats sound doable. I find the AND(a;b;c) is more difficult to read than (a && b && c) but that should be no problem.

It is for experts...

I chose the upper syntax because it is **far** easier to parse, also you don't have to deal with operator precedences and all this stuff. E.g. take something like

NOT a AND b OR c

Which would be correct precedence rules?
And the parsing would be much more complex...

**Comment by eddiemuc** [comment]
Something to add: if project really decides to go this way (using expressions like `a AND NOT b OR c AND NOT d OR e OR f AND g`): I have an implementation for this at hand. It just complications things a lot in the background which is why I decided to use the easier one for now.

**Comment by geocachermgo** [comment]
SCNR:
NOT a AND b OR c=(((!a) && b)||c). Experts should know the operator precedence. 😉
I'm also fine with your suggestion.

**Comment by moving-bits** [comment]
I would not put too much work in it (if at all) - it's an deep-in expert function, and I assume that only a handful of people will ever use it. Better let's spend the programming effort in a cool (in the sense of: powerful, yet easy to use) interface for setting the filters. Just my 2cents ;-)

**Comment by fm-sys** [comment]
Let's close in favor of  #11275 with would give users the same possibilities but within a nice UI...
