### ISSUE TITLE
Comma in formula to parse is not recognized

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#10588]
## Bug description 

In the new functionality to parse a formula from personal note, a comma (instead of a dot) is not recognized, the formula gets not parsed.

### Steps to reproduce the problem

Have german as language / locale
Enter formula in (user-)waypoint and export / save it to personal note
Delete the waypoint and let the waypoint be recreated from the personal note

### Actual result after these steps 

Waypoint without formula is created, the formula is in the waypoint-note.

### Expected result after these steps 

Waypoint with formula is created, the formula is not in the waypoint-note.

## c:geo version 

2012.05.05-RC

## Reproducible 

Yes

## System information 

```
Paste your system information here
```

**Comment by murggel** [comment]
I already found the problem and have a solution.
Please assign to me.

I will create a PR targeting release?

**Comment by fm-sys** [comment]
> I will create a PR targeting release?

Sure. All uncritical fixes can/should go to release...

> Please assign to me.

Done.

**Comment by murggel** [comment]
> @murggel I struggle to reproduce the issue. How do you export a waypoint to the personal note?

@UniQP With the "add waypoint to note" button beneath the personal note

**Comment by murggel** [comment]
This is done with PR #10589 and can be closed. Tested with 2021.05.11-RC
