### ISSUE TITLE
Improve internal routing first use (routing profiles)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10599]
## Bug description 

If a "fresh user" first time activates internal routing he will see, that the routing profiles menus are empty.

### Steps to reproduce the problem

- Open Settings - Routing
- Enable internal routing
- You will see Walk/BIke/Car profiles don't show active profiles
- Tap on one of them

### Actual result after these steps 

It shows an empty menu
![image](https://user-images.githubusercontent.com/949669/117940344-40e8ac80-b309-11eb-9766-5ea8a34d6ba3.png)

![image](https://user-images.githubusercontent.com/949669/117940300-38907180-b309-11eb-807b-087cff7af108.png)

### Expected result after these steps 

We could/should provide some default files already upon installation if possible or at least show an explanational text in the emtpy selections, that profiles will be downloaded together with first routing tiles. 

## c:geo version 

2021.05.11-RC

## Reproducible 

Yes

**Comment by jakedot** [comment]
I stumbled upon this today as well. Additionally, after first selecting the tile for download, I got a "want to update the tile data?" after closing and opening the app even though the default value of 30 days was set for the check interval.
