### ISSUE TITLE
Backup with account data but empty database not possible

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10590]
## What function are you missing
This is surely an edge case of using.
To not every time new configure my account when testing I tried to create a backup with account data only.
But (as I did not saved caches) I got the message "Database is empty, no backup necessary."

## Suggested solution
The backup should be possible also in this situation.

**Comment by moving-bits** [comment]
Backup consists of two files - a backup of the database (as sqlite file, copied from the internally stored sqlite file), and a backup of all settings stored so far (built as xml file, which contents are retrieved from the internal settings).

For the database we can check whether a backup may be necessary (number of stored caches > 0), but for the settings we can't really, as there will be >some< setting very quickly, so checking for "number of stored settings > 0" would be pretty useless.
For that reason I implemented a PR for this asking the user if she/he really wants to create a backup even if the number of caches stored in the DB is zero.
