### ISSUE TITLE
more unshortened LC codes hit the UI

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#10601]
I think the issue is clear and doesn't require much explanation here. I'd say we leave this open until all occurences have been identified and fixed.

Ther first one to be addressed is in the waypoint popup fragment.

**Comment by Lineflyer** [comment]
Again learned something on auto-close using pull requests.
The keyword "Fixes #10601" needs to be in the PR description or in the commit message.
Especially when the branch the PR is merged into is not the default branch, it works only(?) when its in the commit message.

Closing manually therefore :)
