### ISSUE TITLE
Routing profiles not set in menu after first tile downloads

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10600]
## Bug description 

The routing profiles seem not correctly initialized after profiles have been received

### Steps to reproduce the problem

- Activate internal routing and automatic download in Settings - Routing
- Go to the map and set a cache as target
- Automatic download is started (after confirmation)
- Wait for download and copy to complete
- Go into Settings - Routing

### Actual result after these steps 

- Car profiles shows the actual selected profile, however Walk and Cycle show empty but if you enter the menu, they are set in fact.
- 
![image](https://user-images.githubusercontent.com/949669/117941826-be60ec80-b30a-11eb-8d21-cef39d7e4860.png)

### Expected result after these steps 

Used routing profiles should be shown in the settings menu

## c:geo version 

2021.05.11-RC

## Reproducible 

Yes

## Screenshots 

see above

## Additional context 

Related to #10599 (if profiles would be available before "first use" it could implicitly solve the situation

**Comment by moving-bits** [comment]
FYI:
The routing profiles are supplied with c:geo installation, no download needed. Currently the files are checked for and created when you start the internal routing engine - you'll find a `lookups.dat` and several profiles `*.brf` in the `routing` folder then.

In the upcoming PR I've added check & creation of those files to the `SettingsActivity` as well, so the selection lists won't be empty any longer in that use case (#10599). Also I fixed a bug related to prefilling the summary fields for the three profile preferences (#10600).
