### ISSUE TITLE
Receive map file extremely slow (for ZIP files)

### ISSUE THREAD

**Issue by gcey** [cgeo/cgeo#10615]
## Bug description 
The download of a 1 GB map file takes a few minutes, but then the "Receive map file" takes several hours and during this phase c:geo is very irresponsive.

## c:geo version 
2021.04.25

## Reproducible 
Yes

## Additional context 
Samsung Galaxy S9+, Android 10, map folder on SD card.

**Comment by moving-bits** [comment]
Which map source are you using - OpenAndroMaps or one of the others?

(OpenAndroMaps is delivering the map as a zipped file, which reduces downloading time, but increases transfer time, whereas the other map sources use map files directly.)

**Comment by gcey** [comment]
Zip file from Freizeitkarte.
But unzipping should if course not take hours.

**Comment by eddiemuc** [comment]
Does this improve significantly if map folder is on internal storage instead of as card?

**Comment by gcey** [comment]
I checked it now with a map folder in the internal storage and also there it is extremely slow (1MB per minute).

**Comment by moving-bits** [comment]
@gcey 
Can you cross-check with a non-zipped map file of similar size, if it's that slow there as well?

(A file of 1 GB should be downloaded and transferred in less than 15 minutes normally, if there's enough space and memory available, fast internet access provided.)

**Comment by gcey** [comment]
Now I tested it with "bayern.map" (422 MB) from Mapsforge.
The "Receive map file" took just a few seconds!

**Comment by moving-bits** [comment]
Thanks for cross-checking. So indeed it seems to be related to zipped files.
(Or maybe to RAM consumption. How much free RAM does the device have approximately on which you experience that problem?)

**Comment by gcey** [comment]
According to "Memory" in the "Developer Options" 3.4 GB of 5.9 GB are in use (while NOT in "Receive map file").

**Comment by gcey** [comment]
Now (with c:geo 2021.05.20) it works perfectly.
Many thanks !!!
