### ISSUE TITLE
Use different icon for LC caches

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10612]
The current lab cache icon is rather difficult to understand for users:

![Screenshot_20210513_103947_cgeo geocaching](https://user-images.githubusercontent.com/64581222/118101226-a6a36a00-b3d7-11eb-8a90-6a5228dde6a3.png)

AFAIK the Google emoji graphics are even licensed under an open source license. So these could be used. Or we try to draw an understandable icon ourselves...

![grafik](https://user-images.githubusercontent.com/64581222/118101683-25000c00-b3d8-11eb-9927-08dd0990fa62.png)
_Android 10 (first) and  Android 7 version (second)_

Personally I like the Android 7 version very much :)

---
Other icons I found on the internet (only inspiration, no license):
![grafik](https://user-images.githubusercontent.com/64581222/118102432-10704380-b3d9-11eb-9c94-ed8c71b0bf76.png)
![grafik](https://user-images.githubusercontent.com/64581222/118102439-149c6100-b3d9-11eb-8acb-48335c658319.png)

**Comment by baiti** [comment]
@fm-sys ... sure of course. Mine I consider a "quick hack". I wanted to have something that sticks out a bit and that it does for sure. I used the "British Racing Green" that you will also find in GC HQ's Adventure App but other than that I didn't put in any graphics design smarts. I am also not the greatest Photoshop guy either. So bottom line: Give it a shot and throw it in as you see fit.

**Comment by bekuno** [comment]
I personally would go in the direction of adventure, not to laboratory.
Maybe a globe:
![grafik](https://user-images.githubusercontent.com/32555742/118320301-5114ad80-b4fc-11eb-93ee-c872a856ed10.png) ![grafik](https://user-images.githubusercontent.com/32555742/118320343-67226e00-b4fc-11eb-8205-a58c68ba27e5.png) 
![grafik](https://user-images.githubusercontent.com/32555742/118320594-c2ecf700-b4fc-11eb-98f9-3c1a6bd7d836.png)

**Comment by bekuno** [comment]
@jcklpe Any short hand idea?

**Comment by baiti** [comment]
My recommendation would be to make the icon such that it matches the overall style of the icons we use for the GC connector. That was, BTW, the design goal for the green thing I created rather quickly ;)

**Comment by moving-bits** [comment]
Proposal, based on material.io icon "place" and the colors used for the adventure lab:

![image](https://user-images.githubusercontent.com/3754370/118371554-6269c280-b5ad-11eb-8617-bcae1b7f9421.png)

On the map it would look like this:
![image](https://user-images.githubusercontent.com/3754370/118371722-3569df80-b5ae-11eb-81ef-1f031e6e3c11.png)

What do you think?

**Comment by baiti** [comment]
The shape is fine, as for the colour I'd prefer the green as being use by GC's Labs App. And while we are at it: When I first implemented the LC connector, I took the EC connector as a base and that had (and still has) the capability to select Map Icons in Settings -> Services -> Extremcaching -> Appearance -> Map Icons.

At some point I believe it was me removing it but what if we got that back? Could I then still use the original Icon I created? Or the one you built but colored in british racing green?

**Comment by moving-bits** [comment]
British racing green (0x003333) would be pretty dark:

![image](https://user-images.githubusercontent.com/3754370/118376876-ec745400-b5ca-11eb-9443-1ed494db8555.png)

Maybe use the the lighter green used in the not yet finished ALC?

![image](https://user-images.githubusercontent.com/3754370/118376929-32c9b300-b5cb-11eb-9d83-69cbc819b09f.png)

That would look like this:

![image](https://user-images.githubusercontent.com/3754370/118376971-660c4200-b5cb-11eb-9b4e-0335d52c2b12.png)

**Comment by fm-sys** [comment]
I actually like the orange version very much, as it difers from tradis a lot and is (nearly) the same as on the LC App icon

**Comment by bekuno** [comment]
I personally dislike it.
It is too near to the icon in the LC app in countour and color.

Another point.
We should define all (new) icons as vector graphics. Then we can create the rastered icons from them.

**Comment by moving-bits** [comment]
> I personally dislike it.

You mean form or color (or both)?

> It is too near to the icon in the LC app in countour and color.

I've chosen it that way intentionally, as it's about the ALC caches only, no other geocaching platform supporting something similar, so I chose something that resembles the original close enough to make it easy to understand what this symbol is for.

> Another point.
> We should define all (new) icons as vector graphics. Then we can create the rastered icons from them.

material.io has done that for us (in this case), at least mostly. I've taken their `place` icon as png, placed a circle with border in it, and colored it appropriately. But as I have no experience at all with working with vector graphics, I would be out of the game when using SVG. (Which would be ok for me, but then someone else would have to take over.)

**Comment by baiti** [comment]
> 
> I've chosen it that way intentionally, as it's about the ALC caches only, no other geocaching platform supporting something similar, so I chose something that resembles the original close enough to make it easy to understand what this symbol is for.

What original? The one in the geocaching app or the one in the lab app? Both come from the same company, the company that has invented the game and owns the game, and they are fundamentally different. One is green-ish (however not british racing green, I agree to that comment), the other is orange-ish.

**Comment by fm-sys** [comment]
> It is too near to the icon in the LC app in countour and color.

At least it looks **modern** and is **understandable** to users who haven't saw LC's in c:geo until now..

+1 for @moving-bits original orange material design version

**Comment by bekuno** [comment]
> 
> 
> > I personally dislike it.
> 
> You mean form or color (or both)?
>

Both.

> > It is too near to the icon in the LC app in countour and color.
> 
> I've chosen it that way intentionally, as it's about the ALC caches only, no other geocaching platform supporting something similar, so I chose something that resembles the original close enough to make it easy to understand what this symbol is for.
> 
> > Another point.
> > We should define all (new) icons as vector graphics. Then we can create the rastered icons from them.
> 
> material.io has done that for us (in this case), at least mostly. I've taken their `place` icon as png, placed a circle with border in it, and colored it appropriately. But as I have no experience at all with working with vector graphics, I would be out of the game when using SVG. (Which would be ok for me, but then someone else would have to take over.)



> 
> 
> > It is too near to the icon in the LC app in countour and color.
> 
> At least it looks **modern** and is **understandable** to users who haven't saw LC's in c:geo until now..

Indeed it is understandable to users who **know** the LC app.
For others we can create an own icon - it is a only a never seen new one for them.
Maybe **modern**, but is this suitable to the other c:geo icons?

**Comment by fm-sys** [comment]
> One is green-ish (however not british racing green, I agree to that comment), the other is orange-ish.

The green ones inside the app are IMHO just markers without any recognition value. While for the orange one, my first thought was "wow, this 100% looks like an Adventure Lab"

**Comment by bekuno** [comment]
> 
> 
> > One is green-ish (however not british racing green, I agree to that comment), the other is orange-ish.
> 
> The green ones inside the app are IMHO just markers without any recognition value. While for the orange one, my first thought was "wow, this 100% looks like an Adventure Lab"

Why copy them? Are we allowed to do this?

**Comment by baiti** [comment]
The more I think about it, the less it matters to me really. I'm sure, whatever we come up with now, it won't be cast in concrete for the eternal future. So let's just go with what @moving-bits has merged.

**Comment by fm-sys** [comment]
> Maybe **modern**, but is this suitable to the other c:geo icons?

Maybe we need to rather redraw all other outdated c:geo cache type icons ;-)

**Comment by Lineflyer** [comment]
From the suggestions of @moving-bits I do prefer the orange due to:
- Its not so easy to be mixed up with a traditional icon
- Its from its color similar to multi caches (and ALC are kind of multi caches) but still easy to distinct from the multi icon

**Comment by bekuno** [comment]
> > I personally dislike it.
> 
> You mean form or color (or both)?

Both.

> I've chosen it that way intentionally, as it's about the ALC caches only, no other geocaching platform supporting something similar, so I chose something that resembles the original close enough to make it easy to understand what this symbol is for.

From the form the icon from baiti is not a copy, but close to the LC icon.
 
> > Another point.
> > We should define all (new) icons as vector graphics. Then we can create the rastered icons from them.
> 
> material.io has done that for us (in this case), at least mostly. I've taken their `place` icon as png, placed a circle with border in it, and colored it appropriately. But as I have no experience at all with working with vector graphics, I would be out of the game when using SVG. (Which would be ok for me, but then someone else would have to take over.)

If we have a consensus for a svg template, then I can try to create the icon set.

**Comment by moving-bits** [comment]
I've just merged the new icons (the orange ones, as those seemed to be preferred for now), to have them in the upcoming release.

If we want to move from PNG to SVG at some point in time (which I would like to see), quite some work has to be done (or so at least I fear), as not only SVG-replacements have to be created for the PNG, but some inner workings (e. g.: creating the overlays) have to be reworked. Even #7030 did not touch that part. Anyway, I added "replacing cache icons" to the already existing #9088.

**Comment by bekuno** [comment]
I'm unsure with this icon.
It looks nearly the Reference Point icon.
![Screenshot_20210516-223856_cgeo v3](https://user-images.githubusercontent.com/32555742/118412092-5dce0880-b698-11eb-88bc-e364bd3d4d2d.jpg)

**Comment by jcklpe** [comment]
Hey sorry for the delay in replying. 

I think that it would make sense to design icons as a set, but that might be topic for a separate ticket. 

Here's my thoughts on things discussed in this thread so far though:

- the pin graphic:
![image](https://user-images.githubusercontent.com/9451726/119578349-f55ee580-bd81-11eb-9ca1-a6246c8f3827.png)
[Is actually copyrighted by Google I believe though it doesn't get enforced very much.](https://en.wikipedia.org/wiki/Google_Maps_pin)
- The beaker:
![image](https://user-images.githubusercontent.com/9451726/119578436-250ded80-bd82-11eb-9c0c-f12606b87f1e.png)
I like the roundness of this but I think the execution could use some work. 
I've never actually gotten or heard of a Lab Cache before (I know! I'm mostly a weekend urban sunday afternoon guy). But reading the description on the geocaching website I think that the beaker... might be confusing. I'm not sure. 

The beaker would be a good way to get across the idea of "experimental" but it seems that lab caches are also often temporary right? At least the page I read said they're typically placed at megaevents. 

I think it's hard to have too much variance with pins. My instinct is to distinguish them mostly by color than by shape since that's difficult to scale design-wise.
