### ISSUE TITLE
Move filter buttons to ActionBar 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10613]
![Screenshot_20210513_125844_cgeo geocaching_copy_269x245](https://user-images.githubusercontent.com/64581222/118116889-271f9600-b3eb-11eb-91d8-b587e2cbb8c3.png)

The android ActionBar is designed to hold action buttons, which should always be reachable. Currently we have buttons (add, delete, apply) below that ActionBar which IMHO should be moved into it. 

I would also like to create a PR for this, except @eddiemuc is currently working on the UI part and asks me to postpone this or wants to takeover... ;-)

**Comment by eddiemuc** [comment]
I am currently redesigning the GUI anyway to include possibility to save filters, this move would be part of it

**Comment by eddiemuc** [comment]
Fixed with PR #10617
