### ISSUE TITLE
Container size iso. GC-Code in map view

### ISSUE THREAD

**Issue by Knocky737** [cgeo/cgeo#10626]
English+German, if my English explanation can't be understood ;-)

## What function are you missing
Container size info during map display
Information zur Cachegröße, während der Kartenanzeige

## Suggested solution
After the D/T rating in the top bar, add the container size after the second bullet before the GC code.
Since (depending onto the smartphone resolution) there's only limited space left, I suggest to add:
XS=Micro, S=Small, M=Regular, XL=Large, VIR=virtual, ???=Unknown, OTH=Other and ---=Not chosen
For OpenCaching there might be additionaly XXS=Nano and XXL=extremely large
See "Additional context" for further explanation

Nach der Anzeige der D/T-Wertung in der obersten Zeile der Kartenanzeige sollte die Info zur Größe des gesuchen Cache-Behälters stehen ... vor dem GC-Code.
Da hier (abhängig von der Auflösung des Smartphones) ohnehin recht wenig Platz hinter der D/T-Wertung ist, schlage ich folgende Abkürzungen vor:
XS=Micro, S=Small, M=Regular, XL=Large, VIR=virtuell, ???=Unbekannt, OTH=Andere (ggf. sprachlich umzuformulieren) und ---=Nicht gewählt.
For Caches bei OpenCaching zusätzlich XXS=Nano und XXL=Extrem groß
Weitere Einzelheiten unter "Additional context"

## Alternatives/workarounds
Leave the map, (maybe) swipe back to the main page, get the information needed and re-select the map view ... somehow a bit nasty

Die Karte verlassen, ggf. wieder zur Startseite "zurück wischen", die notwendige Information lesen und dann die Karte wieder aufrufen ... irgendwie ein wenig nervig

## Additional context
Searching for a cache outdoor with c:geo is done in the map view. Even after some +10k finds, I can't remember a single cache where - at this point - I needed the actual GC code of the cache I am searching for presently ... especially since this info is shown two times during the map view. Once (cut-off) in the black top bar, and once again (standard settings) in the semi-transparent, grey, second bar.for a cache. Moreover, especially when you are outside and do a customised tour rather than a power-trail (where most of the containers an micros), this is - for me - a more important info than the present GC code.

Please don't get me wrong: This is not a complain! I had good reasons (a few years ago) to swap my GARXXX ORXXX 7XXt with its old-fashioned soft-firmware vs. a French Outdoor smartphone in combination with c:geo ... something I will never regret! I just want to get c:geo even better with my suggest.

Die tatsächliche Suche nach einem Cache mit c:geo erfolgt doch in der Karten-Ansicht. Selbst nach über 10k-Funden kann ich mich nicht an einen einzigen erinnern, wo hier bei der Suche der GC-Code interessant war. Besonders da diese Info ja in der Karten-Ansicht doppelt angezeigt wird: 1x (abgeschnitten) in der schwarzen, obersten Zeile und erneut (Standard-Einstellung) in der grauen, halbdurchsichtigen zweiten Zeile. Viel wichtiger ist mir - wenn ich nicht gerade auf einem Power-Trail unterwegs bin (wo die meisten Caches ohnehin Micro sind) - sondern auf einer eigenen, zusammengestellten Runde, die Info zur gesuchten Cache-Größe.
Bitte versteht mich nicht falsch: Das ist keine Beschwerde! Es hat schon gute Gründe, warum ich mein GARXXX ORXXX 7XXt (obwohl damals neu, aber dennoch veralteten Soft-/Firmwar) vor ein paar Jahren gegen das Outdoor-Smartphone eine französischen Herstellers getauscht habe. Das habe ich bis heute nie bereut! Daher ist dieser Request nur ein Vorschlag aus der Praxis, um c:geo noch besser zu machen :-)

**Comment by moving-bits** [comment]
It could look like this:

![image](https://user-images.githubusercontent.com/3754370/118375387-99e26a00-b5c1-11eb-97bc-b17414144e78.png)

Abbreviations would be:
`XXS` (nano , OC only) / `XS` (micro) / `S` (small) / `M` (regular) / `L` (large) / `XL` (extra large, OC only)
`V` (virtual), `-` (none), `O` (other), `?` (unknown) (although "other" and "unknown" both could be represented as "?" for this purpose)

**Comment by Lineflyer** [comment]
Nice idea for an add-on indeed.
Seperation of other and unknown should stay, as e.g. some owners use "other" for placing Nanos on g.com.

**Comment by moving-bits** [comment]
> Seperation of other and unknown should stay, as e.g. some owners use "other" for placing Nanos on g.com.

I have kept the separation in #10628.

The PR is targeted to `release` as it's a pretty small change - ok?

**Comment by jakedot** [comment]
Would it be possible to link to an explanation when clicking on the XS... label, or do you think describing it in the FAQ is enough?

**Comment by Lineflyer** [comment]
I think its enough to mention it in the user guide.
For most users who spot it after all, it will most likely be self-explanatory anyway I guess.
