### ISSUE TITLE
Remove Global filter completely

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10637]
@Bananeweizen wrote in #995 (shortened to the aspect of removing global filter, go to original issue for full discussion which is also a lot about filtering framework, local vs global etc):

I just read through all the issues related to filters, because the duplicate implementation of them is something I really don't like. We have

* global cache type filtering (directly in the main screen), just because the web site allows exactly this one type of filter up front.
* (several) filters in the lists, which are applied to the overall contents of the list. These filters are much more flexible [...]

[...]

if we implement a more advanced filtering in the lists, do we really need the global type filter at all? Just because it is available in the website doesn't mean we must use it too. I feel like that global filter should be removed completely. Because I see that it will confuse people if we implement more advanced local filters. You then have 2 places where you need to look if you start filtering on cache type (and those 2 filters may contradict each other).

Therefore my suggestion is the following:

* Remove all UI and settings related to the global type filter.
* When loading caches online and a (local) type filter is active, use the advanced search like before with the global filter (but let the app decide this, not the user via user interface). (Note from EddieMuc: I believe @Bananeweizen meant the legacy GC.com search page when talking about "advanced search" because this page forced us to specify a global cache type. With proxy webapi this issue no longer exists)

I think that we would have the same functionality as before, are as efficient as before (i.e. we don't parse more web pages than necessary) and have less user confusion. Any comments from your side?

**Comment by Lineflyer** [comment]
I really need to take a closer look at the new filters, therefore the following statement might not be my final one:

Couldn't we replace the main menu item for the type filter by the new filtering screen you made (on list level)?
So whatever filtering the user would apply there, would be used for all functions of the app (meaning offline + online).

**Comment by fm-sys** [comment]
The current global cache type filter is really bad from a UX perspective, because you need to leave the map/list for changing it. However, filtering for cache types is probably the mostly used filter in c:geo, so it should be accessible in as less clicks as possible. Maybe we can remove the global cache type filter, but for the first time pre-insert the type filter (containing the current global cache type selection) if the user starts creating a new filter...?

> Couldn't we replace the main menu item for the type filter by the new filtering screen you made (on list level)?

Sounds suitable, but does filtering need to be accessible from the main screen at all? 


> So whatever filtering the user would apply there, would be used for all functions of the app (meaning offline + online).

It would be better if the "global filtering" could be changed directly within these activities, so that users don't need to go via start screen.

**Comment by eddiemuc** [comment]
Hm, @Lineflyer you seem to assume that the users want to use the very same filter settings on all places. I am not so sure of that. I think it makes a difference whether e.g. I am in the map viewer in the field, scrolling through my offline stored lists or start an online search for caches. As of now, I thought about remembering always the last filter configuration for each "usage situation" (e.g. the three described above), not to have one global remembered filter config for all. This filter config is always maintained at the place it is needed (mainly at "search screen", at "list view" (different config depending on "list type") and andat map viewer (has yet to be implemented...)

Aside from this, however, my personal opinion is that we don't need a global filter configuration on top of that. Like @fm-sys I also don't think this is important enough to be accessible via main screen. 

@fm-sys thought about "pre-adding" certain filters (like "type") when starting a new filter configuration is a good idea, but should maybe discussed in a separate issue.

I will give all some time to explore the new filter framework before continuing on this.

**Comment by Lineflyer** [comment]
I do use the Global filter some times when I am in an unknown area and just want to see caches I can immediately do/find at the location. Up to now I filter on Traditional caches, thus I am missing things like virtuals and Earth caches. 
In this use case I would like to see this multiple cache type filter maybe even with terrain restrictions (<=T4) to be applied at a central point and applied on live map and search. The lists would be only of minor relevance in this use case.

I do however thing for most users the global cache type filter is still some easily accessible straight forward way to filter caches they want to see. I think it should stay allowing to select multiple cache types and maybe D/T ranges. Taking away functions at well known places is always a bit tricky when it comes to usability (e.g. removing refresh from the cache details menu lead to quite some support requests and bad ratings, simply as users did  assume we removed such function).

However (as said earlier) I need to take some time to look at the new filter and think about that once more.

Maybe we should decide first, whether we want to have dedicated and potentially different filterings being applied to the different activities only (meaning live map, search, lists) or a common filter set which can be reached from main menu as well as from all those activities and being applied on all?

**Comment by eddiemuc** [comment]
> Maybe we should decide first, whether we want to have dedicated and potentially different filterings being applied to the different activities only (meaning live map, search, lists) or a common filter set which can be reached from main menu as well as from all those activities and being applied on all?

Many many options are thinkable:
* Central point could be used to define default filters for all the different "usage types" (must be defined more precisely which "usage types" are differentiated)
* User may select via Settings whether he wants a global filter or a filter per usage type
* Filter configs can be stored and retrieved from database now by user-defined names. 
* User may define a "filter template" which is applied whenever he wants to create a new filter

Just throwing around thoughts, havent made up my mind either. Only thing: shouldn't get too complicated in the end :-)

**Comment by moving-bits** [comment]
Just throwing in: If possible, I would like to see
- a single filtering mechanism in all places
- being able to store named filters
- the different places (mainscreen, map, cache list) remembering the last selected filter in the resp. area
- if some filter setting cannot be applied in a  certain environment, keep the sub-filter in, but flag it somehow

**Comment by eddiemuc** [comment]
> Just throwing in: If possible, I would like to see
> 
> * a single filtering mechanism in all places

Working on it :-)

> * being able to store named filters

Already possible

> * the different places (mainscreen, map, cache list) remembering the last selected filter in the resp. area

Would be also my preference 

> * if some filter setting cannot be applied in a  certain environment, keep the sub-filter in, but flag it somehow

I invented the "inconclusive" property to handle these cases (so user can decide whether to include or exclude such results in a filter). The prototypical example: when applying an attribute filter on a list received from online (e.g. gc.com search): some of the results might already be stored offline and filter can be applied. For all other caches the filter cannot decide whether to be true or false. If on such a filter the "inconclusive" flag is set then these caches will be included in result. If flag is not set, then those caches will not be included.

No idea yet to "flag" this otherwise, any thoughts. 


Apart from that: I found no reason to keep the global filter.

**Comment by Lineflyer** [comment]
Side note:
Without being aware of this issue I posted my suggestion for the global filter here:https://github.com/cgeo/cgeo/issues/10661#issuecomment-842506282

**Comment by fm-sys** [comment]
Added my suggestion/summary to https://github.com/cgeo/cgeo/issues/10661#issuecomment-844202198 as well.

BTW, can we close this issue, as it is better tracked within a larger context in "Optimum solution to combine/seperate/remove old and new filters and the hierarchy of them" (#10661)? I don't really like situations, where exactly the same question is discussed in two different issues...

**Comment by fm-sys** [comment]
Since no further feedback came up, let's close this in favor of #10661
