### ISSUE TITLE
Android 5 users with SAF problems

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10639]
## Bug description 

There are still some users on support mail (up to now all Android 5) which claim, that they are not able to select a folder as they cannot see any content in the dir selector presented to them.

## c:geo version 

2021.04.25

## Screenshots 

![image](https://user-images.githubusercontent.com/949669/118396919-fe4d0a00-b651-11eb-9e71-26ccd8d1f9d7.png)
![image](https://user-images.githubusercontent.com/949669/118396925-060cae80-b652-11eb-8ab4-f5d31cb6b95a.png)

## Additional context 

I found this link for that topic:
https://stackoverflow.com/questions/41913210/action-open-document-tree-shows-empty-recent-list

It claims, that adding an extra to the intent could solve it:
```
Intent intent = new Intent("android.intent.action.OPEN_DOCUMENT_TREE");
intent.putExtra("android.content.extra.SHOW_ADVANCED", true);
startActivityForResult(intent, REQUEST_CODE);
```

**Comment by fm-sys** [comment]
Interesting. Although this seems kind of hacky, it's probably worth to use it...
