### ISSUE TITLE
[New filter framework] Replace implementation for "Search by xxx" with "Search by Filter" internally afap

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10632]
Replace implementation for "Search by xxx" with "Search by Filter" internally afap

Diverse "Search by xxx" methods can be replaced internally with "Search by Filter. E.g.
* Search by keyword
* Search by coordinate
* Search by owner
* ...

This is a chance to get rid of some legacy logic as well and specifically the parsing of old search page on gc.com as well as the `ISearchNextPage` functionality

A precondition is that "Search by Filter" must be implemented for all connectors. Currently it is only supported for GC.com

**Comment by fm-sys** [comment]
Is the `ISearchNextPage` really not needed anymore? For example, you can use `take=100&skip=100` to request the "second page" at GC which should still be available for searches inside c:geo...

**Comment by eddiemuc** [comment]
> Is the `ISearchNextPage` really not needed anymore? For example, you can use `take=100&skip=100` to request the "second page" at GC which should still be available for searches inside c:geo... 

@fm-sys 
Some more details:

The `ISearchNextPage` is today only implemented for gc.com and due to the fact that it today parses the legacy search page which is hard-limited to 20.

The Proxy Web API Returns 500 results in no-time. It is the same API which is used for map viewer (also with 500 limit), and I consequently implemented "Search by Filter" with same limit for now. Also, "Search by Filter" honors your filter arguments, so if you use only supported filters, the 500 returned caches will already comply to the things you wanted. In other words: offline filtering will not "throw away" too many of the search results (as today with the 20-limit)

You could argue that "Next Page" can be used to query the next 500 caches (take=500&skip=500), but I honestly think this is not necessary. Note that this is also not implemented for other connectors today where you could make the same argument.

Try out the new "Search by Filter", I think it is quite good!

**Comment by eddiemuc** [comment]
Closing in favor of #11020 which handles the legacyt topic more throughly, will continue making notes etc there
