### ISSUE TITLE
[New filter framework] Implement "Search by Filter" for all connectors

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10633]
"Search by Filter" is only supported for gc.com yet. It shall be implemented for all other connectors as well

**Comment by eddiemuc** [comment]
I have a question to the community wrt "search by filter".

"Traditionally" (means: currently) the search results for "Search by xxx" functions are hard-limited to 20-per-connector. I assume this was introduced afor technical reasons since for gc.com the "old" advanced search page only returned 20 caches per page, and I assume that the 20 gc.coms should not be "swamped up" by many results of other connectors.

However, this reason has vanished when using the new WebApi. I currently work with 500 results, and the search is still faster than before.

Question is however how to limit search across multiple connector these days. I am currently thinking to restrict to 200 for the big connectors (gc and oc) and maybe 50 for the rest. What do you think?

**Comment by moving-bits** [comment]
I agree, lifting the "20 results" limit would be a good idea. Personally, a set of 100 would be sufficient for me, I rarely use more (resp. use a PQ then), but 200 would be fine for me as well.

**Comment by eddiemuc** [comment]
TODO llist: implemented connectors
- [ ] GCConnector
- [ ] OC/OCApi connectors
- [ ] SUConnector
- [ ] ECConnector
- [ ] LCConnector

TODO list: legacied ISearchByInterfaces
- [ ] ISearchByKeyword
- [ ] ISearchByCenter
- [ ] ISearchByOwner
- [ ] ISearchByFinder

**Comment by eddiemuc** [comment]
Left open:
* Test throughly!
* remove the interfaces, connector logic etc

**Comment by Lineflyer** [comment]
Is this something to be included in the first beta or maybe for the next round (merge branches before merging this one, to test in nightlies first).

In addition:
Can you explain what that means for the user? I assume the "normal" searches will work as before but the new "Search by filter" will now support also other connectors than gc.com.

**Comment by eddiemuc** [comment]
> Is this something to be included in the first beta or maybe for the next round (merge branches before merging this one, to test in nightlies first).
> 

Would be ok to add in next beta round imho

> In addition:
> Can you explain what that means for the user? I assume the "normal" searches will work as before but the new "Search by filter" will now support also other connectors than gc.com.

It's more than that: also the other searches (by owner, finder and coord/address) are switched to use filter framework underneath, and thus they use the settings of the global filter implicitely but no longer the global cache type or the show/hide settings from map quick settings.

Note that this behavior is already in master for "search by keyword" (and of course also for "search by filter")

**Comment by MagpieFourtyTwo** [comment]
Search ``Found by`` still returns just 20 on every call - intentionally?

**Comment by MagpieFourtyTwo** [comment]
Would be great to have a progress spinner or s/th alike ...
Cause you never know if it's still working or if the result of the current search is simply empty ...
Until, at some point, a result suddenly appears after all.   ;)

**Comment by eddiemuc** [comment]
> Search ``Found by`` still returns just 20 on every call - intentionally?

Intentionally but unfortunately...
Problem is that I can't migrate this to new filter. See #11103 (I think you found that one already meanwhile  :-))
