### ISSUE TITLE
remove WP geocode from cache popup for waypoints

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10654]
## What change you want
For caches on the map in the cache popup for **waypoints** a `Geocode` for the waipoint is presented. 
Additional in the cache info you have the cache Geocode.
This waypoint geocode is mainly the cache geocode with change an the first tho alphanums.
I think this is an obsolate info and could be removed.

**Comment by jakedot** [comment]
It still is the official "user-readable" ID for waypoints, and a way to distinguish waypoints uniquely, imagine a cache with multiple Waypoints with the same name (e.g. "Question" or "Parking"). Otherwise I agree, it doesn't help much practically.

**Comment by moving-bits** [comment]
WP id is being displayed in the popup's title section, which is pretty small. As there are use-cases which need the id, and there's no real other use for the title bar space in this case, let's close here as "won't fix".
