### ISSUE TITLE
No cache/WP selector for overlapping caches/waypoints

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10652]
## Bug description 
For overlapping caches or waypoint on map normally you get a selection menu.
You get only one waypoint, if there are more than one waypoint with the same coordinates.

### Steps to reproduce the problem
- open map
- take a cache and create a waypoint on it
- create anoter cache (maybe a UDC)
- copy the waypoint coordinates from the first one to the second
- tap the created waypoint(s) on the map

### Actual result after these steps 
- only one of the both waipoints is opend (not deterministic)

### Expected result after these steps 
- the select menu should be shown 

## c:geo version 
2021.05.11-RC

## Reproducible 
yes

**Comment by jakedot** [comment]
Is this still the case after closing and opening the map?

**Comment by fm-sys** [comment]
Gmaps or Mapsforge? As for Gmaps, we never had that selector at all...

**Comment by bekuno** [comment]
> Is this still the case after closing and opening the map?

Yes, of cause.

> Gmaps or Mapsforge? As for Gmaps, we never had that selector at all...

I do not use GMaps normally, therefore did not know this. 
It is on OSM online and offline.

**Comment by bekuno** [comment]
I changed now the both waypoint coordinates a little bit.
Now it is only a bit of luck, which waypoint is shown.
Here are some samples:
![1 Screenshot_20210520-204323_cgeo](https://user-images.githubusercontent.com/32555742/119036863-8c5a2500-b9b1-11eb-9b0f-926201c8f72f.jpg)
![2 Screenshot_20210520-204345_cgeo](https://user-images.githubusercontent.com/32555742/119036865-8cf2bb80-b9b1-11eb-9993-dae7d9afb406.jpg)
![3 Screenshot_20210520-204439_cgeo](https://user-images.githubusercontent.com/32555742/119036866-8d8b5200-b9b1-11eb-9cf1-cae08e394329.jpg)
![4 Screenshot_20210520-204516_cgeo](https://user-images.githubusercontent.com/32555742/119036867-8d8b5200-b9b1-11eb-9cd0-2a7d5315a96a.jpg)

**Comment by Lineflyer** [comment]
Do I understand this issue correct, that the problem is, that *sometimes* the waypoint selection window is not shown despite the fact you are 1. using OSM (where this feature is already implemented) and 2. have two waypoints of a cache (but not a cache) on the same position?

**Comment by bekuno** [comment]
> Do I understand this issue correct, that the problem is, that _sometimes_ the waypoint selection window is not shown despite the fact you are 1. using OSM (where this feature is already implemented) and 2. have two waypoints of a cache (but not a cache) on the same position?

1) OSM/Mapsforge
2) 2 Caches with waypoints on/nerby the same position (overlapping)
The waypoint selection window is then _never_ shown.

Use case: Create from the Adventure Lab App a c:geo UDC with waypoints. Then create the Waypoint list as personal hint and copy this to the ALC in c:geo. Now you have both UDC and ALC with same waypoints. If you tap one of them, only one waypoint is shown.

**Comment by moving-bits** [comment]
I've done a bit of retesting on this one:

- I cannot reproduce the issue when using two waypoints of different caches.
- I can reproduce it when using two waypoints of the same cache, when testing against current `master`.
- I can no longer reproduce it when testing against PR #14057.

Thus I propose to link this issue against #14057 to auto-close this issue on merging.

**Comment by moving-bits** [comment]
@bekuno 
Can you retest your use case _with newly created waypoints_?

We had issues in the past with some waypoints not having correct internal data, which was used by `NewMap` to distinguish between different waypoints, which led to certain waypoints not being displayed on the map (and therefore not available in the selector as well). #14057 should have fixed this.

**Comment by moving-bits** [comment]
@bekuno 
can we close here?

**Comment by bekuno** [comment]
is fine now.
