### ISSUE TITLE
Crash on saving filter before adding elements

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10668]
## Bug description 

I tried to save a filter and only afterwards applied changes to it. Accepting the filter makes c:geo crash

### Steps to reproduce the problem

- Open filter for lists (empty)
- Tap disc icon, enter a name, save
- Add any filter
- Select Apply

### Actual result after these steps 

Crash

### Expected result after these steps 

Normal function

## c:geo version 

2021.05.17-NB

## Reproducible 

Yes

## Additional context 

Log available on request

**Comment by eddiemuc** [comment]
Confirmed and will be fixed.
