### ISSUE TITLE
New filter is missing some cache types

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10666]
## Bug description 

Some cache types are missing in the cache type list in the new filter

### Steps to reproduce the problem

- Open new filter for lists
- Add filter for "Type"

### Actual result after these steps 

Contains 7 cache types

### Expected result after these steps 

Add missing cache types:
- Adventure Lab
- User defined cache
- CITO 
- Giga Event 
- Mega Event 
- GPS Adventure Exhibit 
- Geocaching HQ Block Party 
- Geocaching HQ Celebration 
- Geocaching HQ (needed)?
- Letterbox Hybrid
- Locationless (reverse) cache (needed?)
- Project-APE Cache (needed?)
- Unknown type (used on OC)
- Webcam Cache

## c:geo version 

2021.05.17-NB

## Reproducible 

Yes

## Additional context 

The event like types (listed below) could also be combined in one "Events" filter to reduce the clutter...except we do  want to cover the use case, that someone wants to filter for one of these types explcitly.
- CITO 
- Giga Event 
- Mega Event 
- GPS Adventure Exhibit 
- Geocaching HQ Block Party 
- Geocaching HQ Celebration

**Comment by eddiemuc** [comment]
Quick fix: add all cache types. But now it's a really long list

Grouping cache types will be done in a second step

**Comment by eddiemuc** [comment]
Cache types are now grouped, cache type list is complete now. Thus I will closed this issue
