### ISSUE TITLE
Clicking filter hint on lists opens wrong filter

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10664]
## Bug description 

As soon as you applied a filter on lists, you will see the small top bar with info about the filter (and as a reminder, that a filter is applied). Tapping on it however will always open the legacy filter, although the new filter is in use

### Steps to reproduce the problem

- Open list of saved caches
- Select Menu - New cache filter
- Apply some filtering
- Return to list
- Tap on the filter hint

### Actual result after these steps 

The legacy (old) filter menu opens

### Expected result after these steps 

If the new filter is applied this should be opened when tapping the hint bar. If an old filter is applied the old filter menu should open (as long as its still there)

## c:geo version 

2021.05.17-NB

## Reproducible 

Yes

**Comment by eddiemuc** [comment]
I was not even aware that it is possible to tap the hint.

I will change this to the new filter as soon as we remove the old one.

**Comment by eddiemuc** [comment]
Changed to always open the new filter now, also added this to map viewer. Hope this is the wanted behaviour :-)
