### ISSUE TITLE
Question: Do routing profiles still work as we now have localized raw folders?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10660]
As we recently introduced localized use of `main/res/raw-*/` for the changelogs and I have seen, that `/main/res/raw`also contains the BRouter default profiles, I just wonder whether those files are still being used independent of the device locale?

Or do we need to copy them to all raw-* folders now?

**Comment by fm-sys** [comment]
Android does always use the most suitable file. As for translations, if not "translation" is present the default folder will be used (`/main/res/raw` in this case)

**Comment by Lineflyer** [comment]
Thanks for clarification :)
