### ISSUE TITLE
Does filter "Is Present"/"Is not Present" make any sense for name and owner?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10670]
## Bug description 

I assume the filter elements for owner and name are identical to the ones used for offline-log, personal note, etc.
However being able to select "Is Present" and "Is not present" does not make sense for owner and name, does it?

### Steps to reproduce the problem

- Open new filter
- Add element name or owner
- Tap on "Contains"
- Select "Is Present" or "Is not Present"
- 
### Actual result after these steps 

- "Is Present" shows always all caches
- "Is not Present" shows always no caches

### Expected result after these steps 

Remove those two options for owner and name search

## c:geo version 

2021.05.17-NB

## Reproducible 

Not sure, but this is my interpretation of "Is Present" and "Is not Present" on those usually always existing fields

**Comment by jakedot** [comment]
I guess they are always present if the cache was loaded by GC connector, however this might not be the case for OC and certainly not guaranteed if imported from GPX...

**Comment by Lineflyer** [comment]
Are you sure:
No cache name and/or no owner name are allowed on OC?

For GPX I am also not sure which elements are mandatory....

**Comment by jakedot** [comment]
Since GPX can be edited manually and there are more sources than just trusted platforms where we can assume it's standard compliant (and it can be edited manually by the user), I'd say we can't rule it out. I'm not sure about OC, but I heard sometime that there are OC platforms which allow multiple owners and leaving the "main owner" empty...

**Comment by eddiemuc** [comment]
From discussion above my impression is that this should stay as is today. I will thus close the issue. Feel free to reopen if more discussion and resulting change is still needed.
