### ISSUE TITLE
Track/route cannot be updated

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10684]
## Bug description
A loaded track/route file cannot be replaced by a different track/route without manually unloading it before anymore.

## Steps to reproduce the problem
- Open OSM map
- Load a GPX track/route file => track/route is being displayed
- Load a different GPX track/route file (with confirming overwrite)

### Actual result after these steps 
There is a display "File xy selected", but still the first track/route is shown

### Expected result after these steps 
The newly selected track/route should be shown

## c:geo version 
Both current state of `release` and `master` branches, haven't tested against current release 2021.04.25

## Reproducible 
Yes

## Additional Context
If I'm not mistaken this is a consequence of making the SAF selectors state aware, see #10447.

**Comment by moving-bits** [comment]
@eddiemuc 
I think I've nailed it down - alas I don't know how to solve it. Can you have a look at it?

I guess the cause is somewhere her in the constructor of TrackUtils:
```
    public TrackUtils(final Activity activity, final Bundle savedState, final Route.UpdateRoute updateTracks, final Route.CenterOnPosition centerOnPosition) {
        this.activity = activity;
        this.updateTracks = updateTracks;
        this.centerOnPosition = centerOnPosition;
        this.fileSelector = new ContentStorageActivityHelper(activity, savedState == null ? null : savedState.getBundle(STATE_CSAH))
        .addSelectActionCallback(ContentStorageActivityHelper.SelectAction.SELECT_FILE, Uri.class, uri -> {
            if (uri != null && this.updateTracks != null) {
                loadTracks(this.updateTracks);
            }
        });
    }
```

The `addSelectActionCallback(...)` gets a `SELECT_FILE` as parameter, whereas when it finally reaches `ContentStorageActivityHelper.callCallback` parameter `action` is a `SELECT_FILE_PERSISTED` and therefore cannot find its callback method, which is stored in `SELECT_FILE`:

```
    private void callCallback(final SelectAction action, final Object parameter) {
        final Consumer<Object> callback = (Consumer<Object>) this.selectActionCallbacks.get(action);
        if (callback != null) {
            callback.accept(parameter);
        }
    }
```

Somehow the first call after starting the map does work, but not subsequent calls.

Do you have a hint for me where to look?

I've already tried setting the parameters for `addSelectActionCallback(...)` to `SELECT_FILE_PERSISTED` and/or `PersistableUri`, but both fails for different reasons (runtime errors).

**Comment by eddiemuc** [comment]
I will take a look at it

**Comment by eddiemuc** [comment]
@moving-bits should I assign this to me?

**Comment by moving-bits** [comment]
> I will take a look at it

Thanks

One additional thought came into to mind, cannot test currently:

I guess even the first call to loading a track file only seemingly works. The track can be displayed on the map, but IIRC it does not show up after closing and reopening the map, most probably because the access right did not get persisted, only the uri.

**Comment by eddiemuc** [comment]
A clear bug, introduced by me when fixing the state thingy with ContentStorageActivityHelper. PR #10692 fixes it.

@Lineflyer as you asked to leave release alone for now, I will not merge this PR until you "release" `release `again. I set PR to "Draft" to prevent accidental merging

**Comment by moving-bits** [comment]
Thanks @eddiemuc for diving into this and preparing a fix.

**Comment by Lineflyer** [comment]
@eddiemuc `release` is released again :)

**Comment by eddiemuc** [comment]
... and merged
