### ISSUE TITLE
Make use of GitHub issue forms

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10683]
There is now the possibility to create "Issue forms" (currently in beta). They (optionally) can force the user to enter more information or at least makes it way easier for users. Research has shown, that these forms improve the issue content quality a lot (win-win situation)

Microsoft Powertoys is using it, and it feels pretty cool creating a new issue with these forms 🤩

Example: https://github.com/microsoft/PowerToys/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml

![grafik](https://user-images.githubusercontent.com/64581222/118868175-2b185000-b8e4-11eb-98d6-af0e9328f227.png)

**Comment by Lineflyer** [comment]
Oh, did not know, that such thing exists. Sounds nice.
I was only aware about the markdown template as of now.

**Comment by Lineflyer** [comment]
@fm-sys Do you know if this is kind of a closed beta?
I found some threads on the net, while it was on alpha state, that it was an "invite only". Now its labeled as beta on Github. But it neither seems to work (tested on my fork of c:geo) nor is there any enable switch in repo settings I was able to find yet.

Any idea?

**Comment by fm-sys** [comment]
Hm... No Idea. Just saw It, liked it very much and wanted to share this with you. 

As the powertoys repo and Github itself belongs to Microsoft, it could be a Microsoft internal beta.

Seems like we have to wait a little longer for this very cool feature ;-)

**Comment by fm-sys** [comment]
Just a small update:
"Issue forms are available in beta for public repositories on Github.com" 🎉🎉🎉

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

This will hopefully optimize our issue quality dramatically. At least I often find myself deleting the pre-inserted the template completely because it looks too complicated at first glance 😅

**Comment by Lineflyer** [comment]
Thanks for this information.
I will look into it as time permits.
Still: If anyone else has free time, feel free to file a PR.
