### ISSUE TITLE
Option to hide lab caches

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#10699]
## What function are you missing
I am sure that many users appreciate the new feature to display adventure lab caches on the map.

However, many traditional geocachers think of lab caches as "not proper geocaching" and that this should not be part of our hobby. Thus, there should be an option to disable the display of lab caches on the map. This is especially important due to the crazy *number* of lab caches in some regions. They really clutter up the map.

Thank you!

**Comment by rsudev** [comment]
Lab caches are bound to a seperate 'service' that can be disabled independently from geocaching.com.
Does that fit your use-case?

**Comment by geocachermgo** [comment]
![IMG_20210521_080214](https://user-images.githubusercontent.com/43813636/119089749-efc47100-ba0a-11eb-86d3-65e3aab7eeeb.jpg)

**Comment by dcjkfgdjhd** [comment]
Ah, yes that is perfect. Thanks, the app enabled this service without my consent, so I had no idea I could disable it there. Problem solved.
