### ISSUE TITLE
Merge strategy ours not valid for changelog_release.md

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10697]
It just came to my mind:
I have configured, that changelogs are not merged between branches as we get translation for both branches anyway (as for the strings).
However there is a difference as we fill changelog_master only on `master` and changelog_release only on `release`. But changelog_release shall explicitly be merged back to `master` as we changes on `release` are also present on `master`.

Not merging those files breaks this mechanism.
This means:
After forwarding `release` to `master` and initializing the changelog as described [here](https://github.com/cgeo/cgeo/wiki/Prepare-a-release#preparing-for-a-feature-release) the changlog_release on `master` will now stay empty.

Have to think about the best solution.

**Comment by Lineflyer** [comment]
After thinking about it, I came to the result, that we should be fine as the merge exclusion only affects the translated files, but not the source files.
Once we merge from `release` to `master` the content of `changelog_release.md` in `/raw` will be merged normally, thus Crowdin will also provide its translations to `master` afterwards. 
Only the translated files are excluded which is fine as for the strings.

No need for action AFAICS.

**Comment by moving-bits** [comment]
Just to be on the safe side: Shouldn't we exclude `raw/changelog_master.md` from being merged from `release` back to `master` as well? (Or is it already?)

`changelog_master.md` should be empty on `release`, but contains current dev info on `master`.
All that`s relevant for releasing is in `changelog_release.md` once it's on `release` branch.

**Comment by Lineflyer** [comment]
We shouldn't.
As long as no one modifies the file on `release` it would not be merged anyway. But if someone accidentally modifies it on `release` we will get noticed by a merge conflict thus avoiding this error.
