### ISSUE TITLE
Changelog optimizations

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10701]
## What is this issue about?
I'll open this issue to collect optimization ideas regarding our changelogs in a single place.

I won't cover our "old" approach of `changelog_master.xml` / `changelog_release.xml` containing XML formatted texts here, this issue is only about furtheroptimizing our new approach:

On `release` we introduced a `changelog_master.md` / `changelog_release.md` using a plain text file with markdown formatting. We've put those two files into `raw` folder and configured Crowdin to translate those two files.

## Proposals
From discussions in other issues as well as own observations I see the following things that could / should be optimized:

### a) Merging rule
As mentioned in #10697 merge strategy should be adapted. Currently it's set to not transfer any changes from `release` to `master`, but as the changelog from `release` is only updated on `release`, but still should be displayed on `master` as well, we should lift that merge rule for `changelog_release.md`.

### b) Translation of version name
Currently the name of the version (e. g. "nightly") is part of `changelog_master.md` / `changelog_release.md`, which means that it does get translated as well, which is fine by itself.
But that also means, that on preparing a release, this title needs to be replaced in all translated versions, as otherwise we will still see a "nightly build" in all languages where we do not replace the version name.

Proposal:
- Put the version name into a separate file (e. g.: `version_master.txt`), located in `raw` folder
- and exclude this file from translation (resp. do not include it)
- Same applies for a `version_release.txt`

On displaying the changelog, c:geo would put that info together in the right order:
- content of `version_master.txt` (only if `changelog_master.md` is not empty)
- content of `changelog_master.md`, formatted using markdown
- content of `version_release.txt`
- content of `changelog_release.md`, formatted using markdown

Edit: Or does changing the version string in `changelog_release.md` get detected automatically? But then we would have to wait for a new CrowdIn-cycle before we can prepare the release?

### c) Shorten changelog / full changelog
Follow-up to a discussion in #10662, I would like to make the following proposal:

Shorten the two changelogs, which get translated, according to the following rules, and use a complete `changelog_full.md`, which does not get translated:

- Issues to mention in `changelog_master.md`:
  - (relevant / larger) new things
  - (breaking) changes
  - fixes, if something of importance was broken (e. g. the login error this week)
- Same applies to `changelog_release.md`, with the addition for bugfix releases to also mention smaller fixes
- This would be complemented by a file `changelog_full.md`:
  - Generally contains all issues, except "loops" (meaning developer-internal fixes for things not yet released)
  - This file would have three sections:
    - First section: `Next release` (meaning: `release` branch)
    - Second section: `Current development` (meaning: `master` branch)
    - Following section: changelogs for published versions with our usual naming scheme as header
- Our website would link to `changelog_full.md`, giving us an always up-to-date complete changelog.

What do you think?

**Comment by Lineflyer** [comment]
a) has been resolved (or better has never been an issue). See my comment in #10697. Same working mode should apply as for the older xml files. Correct me over there, if I am wrong.

b) Good idea to remove the version name from the changelog. As you stated it will only be finalized directly before release, thus will not be "translated" before release.

Regarding your questions:

> Or does changing the version string in changelog_release.md get detected automatically? But then we would have to wait for a new CrowdIn-cycle before we can prepare the release?

Exactly. Therefore your idea with separate `version_*.txt` is OK as those do not need localization.

c)

I have no preference on this one, but your proposal looks good.

**Comment by moving-bits** [comment]
Updates:
a) part a) may not be needed (but check https://github.com/cgeo/cgeo/issues/10697#issuecomment-846398053)
b) an update to my PR #10705 will introduce `version_release.txt` and auto-fill the titles for release (if `version_release.txt` is empty) and master; no `version_master.txt` needed
