### ISSUE TITLE
Revise Global Cache filter: make it based on "Basic" new filter system

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10711]
## What function are you missing
The current global filter does allow only to select one cache type. More global filtering would be good.

## Suggested solution
It should be possible to use a "Basic" set of the new filter framework as global filter. This includes cache type filter (multiple types possible), difficulty and terrain. The "global" filter, if set, will be connected to any other filter (context-dependant) using AND-logic.

## Alternatives/workarounds
Don't implement it

**Comment by Lineflyer** [comment]
Basically I agree to that proposal.
From the users community I often heard the wish to be able to globally select
- more than one cache type at a time
- A range of D and/or T

From the existing logic users are already aware, that this global filter is applied to the whole app, so indeed the internal AND logic is the right way, as:
- Users who only use the global filter can just use it in the same way as before
- Users who previously used e.g. the old list filter can use the new filtering and the combination also behaves in the same way

Question:
Shall the active global filter be somehow indicated in the "lower level" filters?
Example:
A user applied a D-rating filter on global level. Later he opens a list and starts filtering on list level. Shall the filter dialog somehow indicate, that there is a global filter for D-rating active?
While being on list level the global filter is indicated below the action bar. Maybe its just enough to show the same indicator also in the filter dialog on list level.

**Comment by eddiemuc** [comment]
In context of this item I would really like to discuss how the relationship should be in the future of a "global filter" towards other "context-specific" filters in the future.

As of now, implementation is as follows:
* for each "context", the last used filter is stored. This filter is restored as starting point whenever a user goes to this "context" again. "context" is currently defined by the c:geo "CacheListType", currently there are 11 such types defined (see list below)
* Additionally there is a "global" filter where one can specify one cache type (only).
* In each context, both the "context" filter and the global filter is applied in an AND fashion (both have to be fulfilled.

Now the question is how this should be in the future. I see three principail options:
* Reduce to one (global) filter. In each context, this filter is used, and whenever it is modified in any context the result becomes the new "global" filter. It is used everywhere. (This would be the approach that e.g. gc.com app uses today)
* Stay with "context filter" only, do not provide an additional global filter
* Keep both: apply the "context-specific" filter as well as an (optional) global filter in an AND fashion (this would be as close as possible to the c:geo system today)
Before implementing this I kind of need to have a common understanding which "strategy" should be supported in the future.

For reference, here are the currently defined "contexts" (e.g. CacheListTypes). As you can see there are some for offline stored lists ("OFFLINE" an HISTORY), one for MAP (used when using "Show as List" from map viewer) and several types corresponding to the different types of "Online Searches" (e.g. KEYWORD, OWNER, ADDRESS) and some for more special lists ("NEAREST", "POCKET"). The only new one is SEARCH_FILTER.

```
 OFFLINE(true, CacheListLoaderType.OFFLINE, true),
    POCKET(false, CacheListLoaderType.POCKET),
    HISTORY(true, CacheListLoaderType.HISTORY, true),
    NEAREST(false, CacheListLoaderType.NEAREST),
    COORDINATE(false, CacheListLoaderType.COORDINATE),
    KEYWORD(false, CacheListLoaderType.KEYWORD),
    ADDRESS(false, CacheListLoaderType.ADDRESS),
    FINDER(false, CacheListLoaderType.FINDER),
    OWNER(false, CacheListLoaderType.OWNER),
    MAP(false, CacheListLoaderType.MAP),
    SEARCH_FILTER(false, CacheListLoaderType.SEARCH_FILTER);
```

**Comment by fm-sys** [comment]
> "global filter" towards other "context-specific" filters in the future.

Yes, that's a very difficult decision. Please keep in mind that there will (hopefully) be some larger changes with https://github.com/cgeo/cgeo/discussions/10679 in the near future. With this, we would probably have 
1. no global filter at all
2.  or only a global filter, but not without a context-speciffic anymore. 

I would vote for 1. or make it selectable between 1./2. in our settings. 

@Lineflyer are you sure users really need a global filter (together with context-specific)? I would guess these users only have used the global cache filter because there was no other way to filter caches at the Livemap...

**Comment by fm-sys** [comment]
> 
> 
> I would vote for 1. or make it selectable between 1./2. in our settings.

Ok, we could still place the global cache filter on the "more"-page, but I guess it's very difficult to understand that we have two times the same filter UI with a different behavior. Do you really think users would use the global filter together with a context specific filters at the same time? 

And we don't have to hide the selection between 1./2. in our settings. It would be enough to have a checkbox "apply this filter everywhere" in the filter UI.

This would be _way more understandable and easier to use_ than two different filters combined with AND

**Comment by fm-sys** [comment]
Btw, if you look at what we have decided about the global filter so far: https://github.com/cgeo/cgeo/issues/10711#issuecomment-851972027

This seems like to be exactly, what I tried to explain in the post above...

-> Have a ckeckbox "use this filter everywhere" vs. "use this filter only here", but **do not have two filter systems at the same time**

**Comment by Lineflyer** [comment]
After consulting older support mails and speaking to several cachers my conclusion so far is:
- Most users from support asked for a filter which works same for all areas of the app
- While trying to explain a possible "AND" logic most of the fellow cachers did not understand it.
- Most cachers told me: I would prefer a central filtering which is applied everywhere and accessible from every point

So this sound like this approach @eddiemuc posted:

> Reduce to one (global) filter. In each context, this filter is used, and whenever it is modified in any context the result becomes the new "global" filter. It is used everywhere. (This would be the approach that e.g. gc.com app uses today)

The filtering as such is already quite advanced, so maybe its good not to make it more advanced by contexts and/or AND logics between hierarchy levels.

What do you think?

**Comment by eddiemuc** [comment]
> What do you think?

First of all: from all possibilities this is the most easy one to implement :-)

Second: I would personally be totally happy with this.

Now the but:
I am not sure if people are aware that today there is an implicit AND logic implemented in c:geo. For example:
* if you are in a list view, cgeo combines the global filter (currently limited to cache type) with the filter selected 
* If you search e.g. for name or owner (which is kind of a "filter") this is combined with global filter as well as the "map quick settings" filter criteria

The second but:
The one place where this might lead to unwanted behavior is when people do online searches. When the pattern is applied consequently, then as soon as a user e.g. searches for caches by name or owner, then the global filter would be set to exactly this search (filter by name/owner). I assume at least in this case there shall be an exception of "one global filter"?

**Comment by fm-sys** [comment]
Some advanced users might want to have the possibility it have a different filter for map and lists. But I'm on the same side as @Lineflyer. Basically my previous suggestion was nearly the same, except  that I would add a additional checkbox where advanced users can decide whether to apply the filter everywhere (defaulting to true).

**Comment by eddiemuc** [comment]
> ...I would add a additional checkbox where advanced users can decide whether to apply the filter everywhere (defaulting to true). 

This is a complex request (or I don't understand it). 
* If you give the possibility to apply a filter "everywhere" you also have to define the opposite: what means "not everywhere"? Which places/contexts shall then have their own filter definition storage (and please also think about online searches which people tend to forget)
* Filters can be opened/edited in many contexts (e.g. from map, from different list view contexts, in online search). Shall there be the checkbox available whenever a filtrr dialog is opened? And if checked: shall then the filter be copied to all "contexts". 
* If someone opens the "filter" option on main screen while NOT having selected the "apply-same-filter-everywhere" option: which filter is then configured there?

**Comment by fm-sys** [comment]
> If someone opens the "filter" option on main screen while NOT having selected the "apply-same-filter-everywhere" option: which filter is then configured there? 

This one will hopefully get obsolete with the ongoing redesign in the near future as there won't be such a mainActivity anymore (if I find time to implement my plans). ;-) 

> Which places/contexts shall then have their own filter definition storage (and please also think about online searches which people tend to forget) 

True, it's a bit more difficult. But isn't it the same complexity as we currently have? Maybe Map/Offlinelists should get persisted and the rest is just a temporary filter?

 > Shall there be the checkbox available whenever a filtrr dialog is opened? And if checked: shall then the filter be copied to all "contexts".

I would place the checkbox below "use or instead of and", and the other global filter chackboxes. 

If the ckeckbox gets checked the current active filter should get global. If the checkbox gets unchecked, the current global filter become local and all other filters should get resetted to null/unfiltered (not the previous value!).

**Comment by eddiemuc** [comment]
> > If someone opens the "filter" option on main screen while NOT having selected the "apply-same-filter-everywhere" option: which filter is then configured there? 
> 
> This one will hopefully get obsolete with the ongoing redesign in the near future as there won't be such a mainActivity anymore (if I find time to implement my plans). ;-) 

I have the same time problem so I understand what you mean :-) But meanwhile we need to do something with this thing, and my understanding was that people want/need it (I am not talking about myself here, but I remember @Lineflyer getting this from support)


> > Which places/contexts shall then have their own filter definition storage (and please also think about online searches which people tend to forget) 
> 
> True, it's a bit more difficult. But isn't it the same complexity as we currently have? Maybe Map/Offlinelists should get persisted and the rest is just a temporary filter?

Well, currently I implemented a "best possible" approach where I simply tied the contexts to what was available and seems to go into correct direction (CacheListType). After all discussions I really doubt it should stay that way. But your approach would be feasible IMHO.

> 
>  > Shall there be the checkbox available whenever a filtrr dialog is opened? And if checked: shall then the filter be copied to all "contexts".
> 
> I would place the checkbox below "use or instead of and", and the other global filter chackboxes. 

Here I have to disagree. All of these boxes are currently "non-global" (they affect the edited filter only, nothing else in c:geo) whereas the proposed option would be "global" (setting/unsetting it affects the whole c:geo application). Thinking about it, maybe better make it a Setting. I assume that this thing is rather not changed too often (it would be a bad sign if it is; users should not use this as a kind of "copy" function, there are better means for this)

> 
> If the ckeckbox gets checked the current active filter should get global. If the checkbox gets unchecked, the current global filter become local and all other filters should get resetted to null/unfiltered (not the previous value!).

Here I have to disagree as well. Why should a local change inside a filter delete filter Settings in whole other places of c:geo?

**Comment by fm-sys** [comment]
Ok, as you now I'm always a supporter of "keep things simple". All these details are really problematic and difficult to understand for users. Personally, I wouldn't use such a checkbox even if it exists but one filter for all as @Lineflyer suggested is just fine for me. (Even though I remember others here were strongly opposed to it.) So ignore my checkbox idea. "one global filter setting for all" is IMHO the way to go.

**Comment by Lineflyer** [comment]
Lets start with that. If users miss something after that change is live, they will for sure tell us and we can optimize.

**Comment by Lineflyer** [comment]
> Now the but:
> I am not sure if people are aware that today there is an implicit AND logic implemented in c:geo. For example:
> 
> * if you are in a list view, cgeo combines the global filter (currently limited to cache type) with the filter selected

From my experience most people are unaware, respectively the global filter is much less used than the list filter, because the current "Single cache type only mode" is most of the time not helpful.

> * If you search e.g. for name or owner (which is kind of a "filter") this is combined with global filter as well as the "map quick settings" filter criteria

Most users are aware, that e.g. the "hide found" also is applied to all searches.
Sometimes however users forget about that and wonder e.g. if they want to view all caches of a specific owner, that the result is not "complete".

I guess especially for the global "hide found" and "hide owned" the users need to learn the new working mode first (should get into our FAQ) if we decide to move this to the new architecture only.
The problem coming along here is also another one: Users (at least myself) would maybe expect to see found caches in their lists although they globally selected to hide them. This is the current working mode for a good reason...as you might want to see what you "cached" today.

> The second but:
> The one place where this might lead to unwanted behavior is when people do online searches. When the pattern is applied consequently, then as soon as a user e.g. searches for caches by name or owner, then the global filter would be set to exactly this search (filter by name/owner). I assume at least in this case there shall be an exception of "one global filter"?

Good question.
Spontaneously I would say there should not be an exception. If I filter to hide all T5 (as example), why should I want those in search results?

**Comment by eddiemuc** [comment]
> How do the connectors react to the filters? Will they present a filtered list to c:geo or not? 
Currently:
for online search I added a new "search by filter". This search does NOT consider global cache type or map display settings. It will use the connectors filter capabilities as best as possible. But since they are much less powerful than the filter system, if they cannot filter something then filtering is done afterwards inside c:geo for these aspects.
If you started a search this way and you change the related filter in cache list view, then the new filter will AGAIN be queried against the connectors 

Currently I only implemented "search by filter" for gc.com and oc.

Rather than asking how things are right now, we should ask ourself how they **should** be. Current implementation is just experimental :-)

**Comment by jakedot** [comment]
would it be feasible to show the global filter as a "filter row" in other contexts, with a title "global filter" and a description, and clicking enables editing it?

you could add "use saved filters as building blocks for others" in the same way.

Something like this...

![Screenshot_20210604-210004_cgeo](https://user-images.githubusercontent.com/12250212/120852744-e7c40f80-c57a-11eb-8649-e5f600dfce54.jpg)

**Comment by fm-sys** [comment]
> Most users are aware, that e.g. the "hide found" also is applied to all searches.

Probably no. I learned this just two days ago by accident cause I wondered why cgeo doesn't show hides for an owner (but kI just had found all of them already). 

I was struggling with this behavior very much, although I would call myself very experienced with cgeo. 

> I guess especially for the global "hide found" and "hide owned" the users need to learn the new working mode first (should get into our FAQ)

Yes, at least the users wwho hhad understand the old behavior need to learn it. But I guess the change is easy to understand by playing  around. But a FAQ entry doesn't hurt ;-)

**Comment by fm-sys** [comment]
The "map quick settings" should only be used for map. If users want to exclude found caches at other places, they can now use the new filters framework, so there is no reason to apply the "map settings" at other places anymore.

**Comment by Lineflyer** [comment]
> The "map quick settings" should only be used for map. If users want to exclude found caches at other places, they can now use the new filters framework, so there is no reason to apply the "map settings" at other places anymore.

That's probably the best solution.
Lets start from there and see if it fits....still unsure about the various searches where users might or might not want to see found caches. But its cleaner anyway to separate that.

**Comment by fm-sys** [comment]
Let's close here. We have other more up-to-date issues for follow up...
