### ISSUE TITLE
Use textual button for adding filter element

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10717]
Just another thought regarding the new filtering. I showed the new dialog to a geocaching friend. Besides the fact, that he really liked it, he had one struggle while first trying out the advanced mode:

He did not realize the (+) button shown after switching to advanced mode. He asked me, why the advanced mode is just the same as the basic mode, just he can select "OR instead AND", etc.

Therefore just thinking if adding new filter element should deserve more prominence, as e.g. a screen wide text button "Add filter element".

**Comment by MagpieFourtyTwo** [comment]
Yep, same thought over here. Esp. as adding new criteria is even more important than [Basic] vs. [Advanced], nevertheless the latter is way more prominent. And as there is plenty of room in this row, there could be a text added like [Add(itional) criteria] or alike.

**Comment by eddiemuc** [comment]
I think this is the first time I am asked to replace an icon button with a text button :-)

But no technical problem of course

**Comment by eddiemuc** [comment]
fixed with PR #10723
