### ISSUE TITLE
[Filter] previously used Filter setting Basic/Advanced shall be saved somehow

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10724]
Same applies if you create any "basic compatible" filter in advanced mode -> apply the filter -> reopen the filter. 

I think the advanced/basic switch should be stored permanently in our preferences.

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10715#issuecomment-846518088_

**Comment by eddiemuc** [comment]
@eddiemuc  wrote:
The aspect that the switch setting "Advanced" is lost on rotation is a bug which I will fix.

As for the rest: right now the setting "Basic/Advanced" is not stored anywhere. On opening the activity, the given filter is analyzed. If it is displayable in "Basic", then "Basic is chosen, otherwise "Advanced" is chosen.

I see that this is probably to be discussed :-). I see three possible solutions how to handle the "on open" case:

Don't store, decide upon filter complexity (Leave as is, but with the rotation bug fixed of course)
Store on a "per-filter" basis (but choose "Advanced" anyway if filter is too complex to be displayed in "Basic")
Store on a "system-wide" basis in "Settings" (but if "Basic" is chosen and a filter is too complex to be displayed in "Basic" thenswitch to "Advanced" anyway)
I like simple solutions and thus implemented the first option. @fm-sys suggested the third one. I will wait for more opinions (and fix the rotation bug meanwhile...)

**Comment by eddiemuc** [comment]
@fm-sys wrote:
> Store on a "per-filter" basis

You can only store filters in advanced mode anyway, so it will always be "advanced". You do you mean "lists" vs "map"? Anyway, this would be confusing and too complex...

> Store on a "system-wide" basis in "Settings" (but if "Basic" is chosen and a filter is too complex to be displayed in "Basic" thenswitch to "Advanced" anyway)

Anyway, imagine a pro-user. Won't he be annoyed if he always have to start at "basic" every time?

And you are right, the setting would be a "force-advanced" setting, pointing to true/false. So false does not mean that it needs to be basic, but decides automatically.

**Comment by eddiemuc** [comment]
@eddiemuc  wrote:
> Anyway, imagine a pro-user. Won't he be annoyed if he always have to start at "basic" every time?

I don't see this as a selection between "amateur" and "pro". I see it as a selection between "I want to do something simple so I don't need all those extra options" vs "I want to do something complex, so I need the extra options". Even a "pro" might simply want to filter by e.g. cache types from time to time, and he might be glad that he does not have to spend these extra clicks of adding a cache type filter in this case.

**Comment by fm-sys** [comment]
> Even a "pro" might simply want to filter by e.g. cache types from time to time, and he might be glad that he does not have to spend these extra clicks of adding a cache type filter in this case.

If a "pro" want to create a "basic" filter he can simply switch to "basic" with a single click.

The basic filter UI doesn't provide saving/loading filters (which is IMHO perfectly fine). Anyway, imagine a pro-user who has stored multiple pre-defined filters. Currently he always needs to switch again to advanced just to load his filter.

**Comment by eddiemuc** [comment]
Reminder for myself: in this context, also revise how to save filter configs in general:
* change per-filter-config from a single String[]-array to a `Map<String, List<String>>` construct (far easier for later migration cases!)
* write general parsing/restoring method this such maps in `ExpressionParser`
* use same method for parsing/restoring general filter properties (filter save name, inconclusiveness, basic/advanced view last-saved, maybe more in the future)

**Comment by eddiemuc** [comment]
PR #10755 is on the way...
