### ISSUE TITLE
theme mode "follow system setting"

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10721]
> Those apps typically offer to either follow system setting or fix to dark or light. That would be desireable for c:geo as well IMHO.

Yes. That's easy to archive. I offered to implement this in some other thread. But I will open an explicit issue for it...

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10643#issuecomment-846520144_

mentioned as well in https://github.com/cgeo/cgeo/issues/9373#issuecomment-841826254

**Comment by Lineflyer** [comment]
BTW:
In the emulator I have just seen, that the installation wizard already follows the system setting for dark mode.
