### ISSUE TITLE
Map quick settings: individual and separate "show caches" option for owned and found geocaches

### ISSUE THREAD

**Issue by Vike91** [cgeo/cgeo#10735]
User feedback on Facebook Finnish geocacher group.

They would like to get a separate option for displaying  found and owned geocaches in the quick map settings, each independent of each other.

Currently both are together in one option.

**Comment by SammysHP** [comment]
Historically this matches the option that was available at geocaching.com. With the new filter system it should be possible to split it. Or maybe move it to the filter section completely.

**Comment by eddiemuc** [comment]
Map quick Settings will remain apart from new filtering System as "pure map viewer settings". Nevertheless this is of course a valid and often-requested feature (which can be implemented anytime independent from new filtering)

**Comment by SammysHP** [comment]
"Hide own and found caches" in the map quick settings is also a global filter which is applied to the nearby search.

**Comment by eddiemuc** [comment]
> "Hide own and found caches" in the map quick settings is also a global filter which is applied to the nearby search.

That's correct today, but it won't be the case with new filter framework (which you referenced)

**Comment by eddiemuc** [comment]
> "Hide own and found caches" in the map quick settings is also a global filter which is applied to the nearby search.

You can already try this out when using the new "Search by Filter" function in "Search" menu. It let's you search the connectors (as of now only GC.com, but others will be implemented too, just too much work and too little time...). This search will not use the global hide switches any more because this can be configured in the filter dialog directly.
