### ISSUE TITLE
[New filter framework] Add an Invert button to the cache type selection screen

### ISSUE THREAD

**Issue by Vike91** [cgeo/cgeo#10734]
This is user feedback on the Finnish Geocaching Facebook group.

 They saw the sneak peek on c:geo Facebook and would like to request to **add a button to invert all the choices in the cache type selection screen.**

**Comment by eddiemuc** [comment]
There's a sneak peek on Facebook?

**Comment by eddiemuc** [comment]
In advanced mode, there's the possibility to revert the filter as a whole (is not displayed in Facebook sneak peek). Would this solve the feature request?

**Comment by Vike91** [comment]
That would be perfect, if all the options in the basic menu are available in the advanced menu as well.

**Comment by Lineflyer** [comment]
> There's a sneak peek on Facebook?

Yes, I took the freedom in order to gather some feedback and opinions.
Hope this is OK for you...

**Comment by Lineflyer** [comment]
> That would be perfect, if all the options in the basic menu are available in the advanced menu as well.

Yes, advanced includes what you could already see in basic and much more.
You can test it in the nightlies. Feedback appreciated.

I will close here then.

**Comment by eddiemuc** [comment]
> > There's a sneak peek on Facebook?
> 
> Yes, I took the freedom in order to gather some feedback and opinions.
> Hope this is OK for you...

Sure :-)
