### ISSUE TITLE
Material theming: No transparent background for mainscreen

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10744]
## Bug description 
While drastically reducing the number of our themes, the layout options for having a transparent mainscreen background got kicked-out.

We can either remove that feature officially (need to remove the related setting, then), or need to implement the necessary theme or activity options to get transparency back. What do we want?

**Comment by Lineflyer** [comment]
I think we can remove the transparent background. Its a relict of old times somehow. 
Even more our main menu will hopefully be reworked as well thus requiring a solid background anyway.

**Comment by eddiemuc** [comment]
I assume the easier way would be to remove it. So I vote for doing it, although I use it myself

(I also remember being irritated a lot by this feature the first time I ever used c:geo, I don't know any other app which by default lets the system background shine through)

**Comment by moving-bits** [comment]
> I assume the easier way would be to remove it. So I vote for removing it, although I use it myself
> 
> (I also remember being irritated a lot by this feature the first time I ever used c:geo, I don't know any other app which by default lets the system background shine through)

Same here. I'll remove the settings' options for transparency.

**Comment by MagpieFourtyTwo** [comment]
To bed honest: I was kind of shocked, when I lost the beautiful background. Really liked to see my nice wallpaper in the app. Was *way* more beautiful than it is now ... boring grey ... really sad about it. :/

**Comment by MagpieFourtyTwo** [comment]
Have to correct myself: It's not boring, but even mindboggling ugly. :{

Any plans for a background image? Or at least a friendly deep black?

**Comment by MagpieFourtyTwo** [comment]
Just went a bit deeper and opened a cache. Sorry, guys, but this (dark) theme is absolutely unusable, esp  in the dark: text just grey on grey, the lack of contrast is a real pain, you really have to concentrate to read text, and in the very next moment, esp. on change to waypoint page, your eyes get burned by the extremely intrusive, stabbing, eye-burning orange of the oversized switches.

No, sorry, I really love c:geo, but right now it's a real pain to use this wonderful app. :(((

**Comment by eddiemuc** [comment]
Thanks a lot for putting the new theme implementation in! I am pretty sure it will easify future changes of the GUI towards a more modern design in numerous ways (the drastic reduction/cleanup of themes/styles alone is a vast improvement!)

There might still be GUI glitches (I see for example many discussions wrt background colors :-)) but I am sure we can resolve them until next release.

**Comment by eddiemuc** [comment]
Again, many thanks to @moving-bits for tackling this.

**Comment by eddiemuc** [comment]
@moving-bits I just wanted to remove my "layout hacks" in cache filter guis, and I realized that you already did that while changing the overall themes! Many thanks again!

**Comment by Lineflyer** [comment]
> No, sorry, I really love c:geo, but right now it's a real pain to use this wonderful app. :(((

This is work in progress, but the guys wanted to merge it anyway as it will never be in a complete state with one PR but we need to record the regressions / ugly items we see.

Regarding the background color, there is already a dedicated issue: #10752

**Comment by SammysHP** [comment]
With the recent beta we got several complaints about the solid colored background.

https://geoclub.de/forum/viewtopic.php?f=155&t=81690

**Comment by Lineflyer** [comment]
Same as on support...but the main menu might be gone soon anyway. So also a custom background selector or alike makes no sense.
I guess people will get used to it.

**Comment by fm-sys** [comment]
That's why my first plan was to implement the bottom navigation at the same time as the other material theming stuff...

**Comment by Lineflyer** [comment]
> That's why my first plan was to implement the bottom navigation at the same time as the other material theming stuff...

Now you can imagine the reaction to a complete change of the "startup behavior". You have to think about users using an app for years which we need to pick up and explain the new working mode.
Therefore I think its the right way to put this into a second step. And I think we also need some good tutorial plugin to show users where to find the "old items" now (like showcaseview which we had some years ago). But thats another topic, which will be discussed once we work on it.

**Comment by MagpieFourtyTwo** [comment]
A prime example of how today's users care way more about looks than function.  Typical luxury problem.  :/
Function is assumed anyway, is taken for granted, so in the end it just has to look nice.
Either flashy and colorful or nicely graduated shades of gray - which depends on the current fashion.
Quite apart from the fact that looks are of course much easier to judge (and criticize) than function.

Daily bread of a developer, whose ingenious software unfortunately needs a comparably dumb graphical GUI, because otherwise the "experts" of this world would not be able to work with it at all.  BTDTMT-NT.  Hail to the good old days of command line interfaces.  \*sigh*

Unpalatable bottom line:  To sell an innovation - esp. even unpopular ones - just make it look good.   Then they will buy it.
And that's how c:geo should do it, too.

Thus, in addition to the really exceptionally good development of the "internal" qualities over here, thanks again to all those who do the "external" fine-tuning - really great work throughout!  Thanks a lot!

**Comment by fm-sys** [comment]
Another idea: We could show the "foggy forest" branding image of c:geo in the main screen (like already done in about version), if users really want a colorful background ;-)

**Comment by eddiemuc** [comment]
If you consider enabling the "transparent" background again: it would be three lines of code to set the system wallpaper as the background of the main activity:

![image](https://user-images.githubusercontent.com/6909759/124768269-d0d95a00-df38-11eb-97f0-55878e77aef6.png)

Looks like this (emulator SDk29):

![image](https://user-images.githubusercontent.com/6909759/124768343-e058a300-df38-11eb-9285-1dd8d786afba.png)

**Comment by MagpieFourtyTwo** [comment]
I don't think this is about having any background or not - in fact, the deep and solid black in conjunction with the material design of the app itself actually looks really clean and pure. I rather think it was the personal touch that c:geo got by using the owner's ery personal own background image.

**Comment by MagpieFourtyTwo** [comment]
> it would be three lines of code to set the system wallpaper as the background of the main activity

Even kept in mind that wallpapers can a) be way wider than the screen (scrollable) or b) even live ...?

**Comment by eddiemuc** [comment]
> > it would be three lines of code to set the system wallpaper as the background of the main activity
> 
> Even kept in mind that wallpapers can a) be way wider than the screen (scrollable) or b) even live ...?

Works for photos but not for live wallpapers (if you set a live wallpaper, the last set photo is displayed instead)
Ah, and the photos must be scaled correctly - which is possible.

**Comment by MagpieFourtyTwo** [comment]
"Scaling" is an interesting theme in itself ...
- If the desktop wallpaper is wider than the screen width (which is most probably the default nowadays, as most wallpapers scroll), how should the section be determined, which will be displayed in c:geo?  Top and bottom border taken as constant, cutting the right and left sides?  Or shrink the whole pic to the max width?  Or height?  Or just cut out a section from the center of the wallpaper, which matches screen width and height?
- If it's smaller - stretch it?  And stretch until it matches width? Or height ...?
- Should c:geo keep aspect ration? And which side should be cut, if the result does not match the screen ...?
- ...

As for me these are already too many questions (and possibilities to invent bugs - and most probably there are even more) for a feature, we may some day be able to solve via a transparent desktop again, anyway.

Or, maybe even better, c:geo maintains it's own wallpaper and lets the user decide to chose (or even cut) a perfectly aligned pic ...? So no automatism, just a plain pic to be displayed, manually chosen (and cut) by the user (to be honest, like this variant best ;) ).

**Comment by moving-bits** [comment]
I don't think we should invest here. The mainscreen, as we know it today, will not last forever, current version is just an intermediate step of our UI overhaul...
