### ISSUE TITLE
API Integration to add caches in a c:geo cache list to a project-gc Virtual GPS

### ISSUE THREAD

**Issue by P98Cacher** [cgeo/cgeo#10746]
## What function are you missing

**Use case:**  I want the ability to synchronize a stored list of caches in c:geo with a Virtual GPS (vGPS) on project-gc.com.  I often plan caching trips with others or by myself using a Virtual GPS on project-gc.com.  I then generate a GPX file on project-gc.com and load it to a cache list in c:geo.  Often, while in the field, I will add additional caches to the cache list in c:geo as I go.  At the end of my trip I often want to log my finds from a computer using project-gc.com Virtual GPS as the reference list.  

As an MVP, I would like a way to manually trigger a push of a c:geo cache list to a virtual GPS on project-gc.com.  This push would check every cache in the c:geo list to see if it is a member of the vGPS on project-gc and for those that are not in the vGPS, it would then add them to the vGPS.  (e.g., only add caches to a virtual GPS - no delete/remove function).  

A more advanced state could entail linking a cache list in c:geo with a virtual GPS in project-gc and then executing API calls to add/remove caches from a project-gc Virtual GPS as they are added or removed from the linked c:geo list - this would, in theory, keep a vGPS in-sync with a list that is being managed in the field by the c:geo user.  NOTE: I did not attempt to explain this scenario in detail.  The MVP meets 90% of my need/desire.

## Suggested solution

Basic solution:  In the list view of a cache list in c:geo, include an option under Export >> Project-gc vGPS  >> Opens a dialog box that shows the list of vGPSs from project-gc and allows user to select one.

Upon selecting the list and initiating the sync, c:geo iterates through all of the caches in the c:geo list, first checking the project-gc virtual GPS to see if the cache is already a member of the list, and if not, then calling the API to add it to the vGPS.

This implies that configuring a login/authentication to project-gc is elsewhere in the Settings>Services menu.  Since project-gc uses an oauth process based on geocaching.com, it can leverage the geocaching.com service already in c:geo.  

As a reference for working with project-gc.com Virtual GPS outside of project-gc, there is a tampermonkey script for geocaching.com called "Geocaching.com + Project-GC" that allows for: 
1. the ability to retrieve a list of project-gc Virtual GPSs associated to the project-gc account
2. the ability to see if a cache is a member of a vGPS
3. the ability to add a cache to a vGPS
4. the ability to remove a cache from a vGPS

## Alternatives/workarounds

No good work-arounds.  The only one I've found is exporting a GPX from c:geo, loading it on geocaching.com to a geocaching.com list and then synching the geocaching.com list to a project-gc vGPS.

## Additional context

https://project-gc.com/Home/UserScript  << reference to the scripts that tampermonkey can use from Chrome

**Comment by P98Cacher** [comment]
Bump - would be great if whomever is a product lead could comment.

**Comment by fm-sys** [comment]
> Bump - would be great if whomever is a product lead could comment.

There is no one like a real product leader, as we are a 100% community powered open source project. Anyone, who is interested and has the necessary coding knowledge can pick up the issue and start implementing it. 

> No good work-arounds. The only one I've found is exporting a GPX from c:geo, loading it on geocaching.com to a geocaching.com list and then synching the geocaching.com list to a project-gc vGPS.

Just 10 minutes ago we have started a new feature release, in which we will support adding caches to bookmark lists directly from within cgeo. 

But it might take some hours/days until it is rolled out for everyone

 see https://github.com/cgeo/cgeo/releases/tag/market_20210927

You have to decide whether this is suitable for you or if you need a dedicated API integration for ProjectGC

**Comment by eddiemuc** [comment]
Teammeeting 10.3.24: it seems this issue is solved with bookmark integration as previously stated by @fm-sys . Please reopen if this is not the case
