### ISSUE TITLE
Material theming: Preference button alignment

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10740]
## Bug description 
Full-sized buttons used in preferences should have their text centered instead of left-aligned:

![image](https://user-images.githubusercontent.com/3754370/119402101-bc206a00-bcdc-11eb-94e8-0517fa229a3f.png)

**Comment by fm-sys** [comment]
Currently it looks like this. IMHO, this is fine so I will close this issue. Feel free to reopen if you think further work is needed.

![Screenshot_20210527_232130_cgeo geocaching_copy_270x585](https://user-images.githubusercontent.com/64581222/119898709-7c5abc00-bf42-11eb-9cbd-d08d4b6127ed.jpg)
