### ISSUE TITLE
Material theming: Routing buttons in map quick settings are all-orange

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10742]
## Bug description 
The routing mode buttons in map quick settings currently are all-orange, thus it's pretty hard to see which one is the active button.

That may change if we decide upon a different look for the buttons (see #10739), but we should keep this bug in mind and fix it (if still needed), when the look for out buttons has been decided upon.

**Comment by fm-sys** [comment]
Working on it. Will refactor to material toggleButton...

![grafik](https://user-images.githubusercontent.com/64581222/119728724-169ffe80-be74-11eb-8b0a-e760df532d8a.png)

**Comment by eddiemuc** [comment]
On current master, the orange is gone. Unfortunately it is totally gone, except for one button which is marked directly after opening:

![image](https://user-images.githubusercontent.com/6909759/119730093-a1352d80-be75-11eb-9eef-172bfb2f1413.png)

And after clickig any other button, this marking is gone too:

![image](https://user-images.githubusercontent.com/6909759/119730195-bca03880-be75-11eb-85c6-8d366b21583f.png)

**Comment by fm-sys** [comment]
Yes, noticed it while working on the button theming issue. 

@eddiemuc BTW, I saw that you have heavily used a c:geo DIY solution for creating a "toggleButton". Would you be willing to refactor this as well to the official material toggleButton, to better fit to the material theming? You can for sure wait until the quicksettings popup is fully migrated. Maybe you can reuse something, unify code parts or create a material toggleButton helper class for c:geo. ;-)

**Comment by eddiemuc** [comment]
> @eddiemuc BTW, I saw that you have heavily used a c:geo DIY solution for creating a "toggleButton". Would you be willing to refactor this as well to the official material toggleButton, to better fit to the material theming? You can for sure wait until the quicksettings popup is fully migrated. Maybe you can reuse something, unify code parts or create a material toggleButton helper class for c:geo. ;-)

Sure. One reason for refactoring this out into its own class was to replace it with a better view on a central place later (or throw it away if it can be replaced completely by another component). I did not imagine when I started this that the big GUI refactoring will happen so near in the future :-)

**Comment by fm-sys** [comment]
@eddiemuc
> One reason for refactoring this out into its own class was to replace it with a better view on a central place later (or throw it away if it can be replaced completely by another component).  


`com.google.android.material.button.MaterialButtonToggleGroup` it the material view group for this use case. It can be customized via layout parameters like `app:selectionRequired="true" app:singleSelection="true"` and the current selection can be set/get via `toggleGroup.check(. ..)`  / `toggleGroup.getCheckedButtonId()`. There are some other methods which can be used as well...
