### ISSUE TITLE
Migrate viewpager to material tabs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10758]
The tab functionality could be a successor of the viewpagerindicator.
It should provide the amount of tabs we need (e.g. for the cache details) and looks like a well recognizable design.

I don't consider this urgent as the viewpagerindicator is still working, but it could be done in a second UI step or when time permits.

![grafik](https://user-images.githubusercontent.com/949669/119615644-e9b20400-bdff-11eb-8253-11ee8ab804ca.png)

https://material.io/components/tabs#usage

**Comment by moving-bits** [comment]
See #10799 for a first MVP, migrating the about pages from external viewpager to Android's ViewPager2 and Material Tabs

**Comment by moving-bits** [comment]
would also solve #7951 and #7834

**Comment by Lineflyer** [comment]
> See #10799 for a first MVP, migrating the about pages from external viewpager to Android's ViewPager2 and Material Tabs

The replacement for the about pages looks perfect to me. IMHO the very same can be applied to the cache details. If another MVP is needed, the trackable details could be the next step.

**Comment by moving-bits** [comment]
I'm already working on it. Quite a challenge... And `CacheDetailActivity` cannot be migrated without `TrackableActivity`, as they share some viewpager related code. Currently I'm "fighting" with `viewpager2` about updating views.

Here's a small sneak preview:
![image](https://user-images.githubusercontent.com/3754370/120902529-2e7c3d00-c641-11eb-8ba9-30e39cba87eb.png).![image](https://user-images.githubusercontent.com/3754370/120902533-34721e00-c641-11eb-88d7-5b74008209fd.png)

**Comment by Lineflyer** [comment]
Highly appreciated and looks nice already.
BTW: I assigned you for this issue just in case someone else otherwise starts doing the same :)

**Comment by moving-bits** [comment]
Should be completed with #10799 (about pages) and #10865 (cache and trackable pages). If any issues arise from that, let's open separate issues for it.
