### ISSUE TITLE
use androidX toolbar in cachedetails popup

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10757]
> `colorBackgroundActionBar` is used by `actionbar_popup` layout file, which is used by both the cache popup and the waypoint popup.

I think this should be changed to use the same background color resource as all other action bars. Or even more radical: why do we have tried to design a "action bar" ourselves? (Nowadays) there is a AndroidX Toolbar component which should be used for the popup...

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10752#issuecomment-848223541_

**Comment by moving-bits** [comment]
We are using the old actionbar in several places and should migrate all of them to toolbars, see #9586

**Comment by fm-sys** [comment]
The old actionbar is used, which might not be the best idea. But in the popup it's even worse. There we use a self designed layout file which tries to look a bit like a ActionBar.
