### ISSUE TITLE
Material theming: Don't use accent color in action bar on light theme

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10753]
## Bug description 

I guess its not intended to use our orange accent color as color for the action bar on light theme.

### Actual result after these steps 

![image](https://user-images.githubusercontent.com/949669/119543068-8c329e80-bd90-11eb-8473-016b78be9969.png)

### Expected result after these steps 

Other theme aware app use a light grey (slightly darker than the actual app background)

## c:geo version 

2021.05.25-NB1

**Comment by fm-sys** [comment]
Indeed, this is intended by material. But we can change it for sure...

**Comment by moving-bits** [comment]
Although with the color chosen currently for light theme (as seen in the screenshot) we have a slight misfit between our logo and the action bar. They are too far apart to look the same, but too close together to look like an intended pair.

**Comment by fm-sys** [comment]
I saw that we use an even lighter orange in light theme then we use for dark. Shouldn't it be the same color or even the other way around?

**Comment by moving-bits** [comment]
IIRC someone had proposed to use our current accentColor in dark theme, and a different color for light theme, so I put that into code so the we all can have a look at it. But we can choose other colors, or set both to the same color as well. TBD. Also we can use a color different from our current accentColor for the action bar, and use our accentColor in other places.

**Comment by moving-bits** [comment]
will be fixed with #10765 as well
