### ISSUE TITLE
Material theming: background color way too light

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10752]
IMHO the new / current background color is way too light. While I agree that a pure black is too dark, the color should be a dark gray instead of light gray (as it was before at some places).

| Gmail | c:geo | pure black |
|-|-|-|
| ![grafik](https://user-images.githubusercontent.com/64581222/119493442-7b6a3480-bd60-11eb-92ce-bd3e9b7adcf6.png) | ![grafik](https://user-images.githubusercontent.com/64581222/119493752-d1d77300-bd60-11eb-8ab2-ffec89e22f34.png) | ![grafik](https://user-images.githubusercontent.com/64581222/119494549-b6209c80-bd61-11eb-86d5-c0a7f1023dd0.png) |

I would suggest using the "GMail" color theme (-> swap/adapt action bar and background color inside c:geo)

**Comment by fm-sys** [comment]
Just for reference: this is the "GMail" action bar color...

![grafik](https://user-images.githubusercontent.com/64581222/119495538-cb49fb00-bd62-11eb-8b3c-dcc03c44021e.png)

**Comment by Lineflyer** [comment]
Jepp, that also what I suggested in some of the common threads we had before.
Maybe the color of the current main screen (non transparent) background is a good one for the background everywhere??

The action bar color could then be the one as in GMail.

@fm-sys What tool does provide this "color pickings" from your screenshot.

**Comment by Lineflyer** [comment]
@moving-bits Can you give me a small hint what file defines the new background color, so I could try to play around with it in Android Studio.

**Comment by fm-sys** [comment]
> @fm-sys What tool does provide this "color pickings" from your screenshot.

It's part of Microsoft PowerToys (https://github.com/microsoft/PowerToys - the same repo where I saw these cool issue forms ;-))

**Comment by fm-sys** [comment]
> 
> 
> @moving-bits Can you give me a small hint what file defines the new background color, so I could try to play around with it in Android Studio.

Although I was not mentioned:
- dark theme: [/main/res/values-night/colors_dark.xml](https://github.com/cgeo/cgeo/blob/1030520e9a1c62be3558287384f5f156269ce5cf/main/res/values-night/colors_dark.xml)
- light theme: [/main/res/values/colors_light.xml](https://github.com/cgeo/cgeo/blob/1030520e9a1c62be3558287384f5f156269ce5cf/main/res/values/colors_light.xml)

The color is formatted as `<color name="colorBackground">#FF404040</color>`

`#FF` is the transparency (0%) and the rest is the RGB Hex code...

**Comment by Lineflyer** [comment]
I just tried swapping colors (Thanks @eddiemuc for the hint) and quickly made this one

```
     <color name="colorBackground">#FF202125</color>
     <color name="colorBackgroundNotice">#FF202125</color>
     <color name="colorBackgroundTransparent">#44202125</color>
```

Looks like this:
![Screenshot_1621972225](https://user-images.githubusercontent.com/949669/119559649-40d5bb80-bda3-11eb-90ea-9bc6861acbeb.png)


BTW: 
I tried to change the action bar color by changing `colorBackgroundActionBar`  in `color_dark.xml` but it seems to have no effect.
Why?

**Comment by moving-bits** [comment]
> I tried to change the action bar color by changing `colorBackgroundActionBar` in `color_dark.xml` but it seems to have no effect.
> Why?

I'd started defining the new themes and color definitions based on our old themes, and before someone pointed me to the `MaterialComponents` based theme. Also I become more "radical" along the way with throwing out our tangled old definitions. But it may be (looks like) I've forgotten to remove some old color definitions that's no longer in use. I'll check this.

**Comment by moving-bits** [comment]
`colorBackgroundActionBar` is used by `actionbar_popup` layout file, which is used by both the cache popup and the waypoint popup.

**Comment by fm-sys** [comment]
> `colorBackgroundActionBar` is used by `actionbar_popup` layout file, which is used by both the cache popup and the waypoint popup.

I think this should be changed to use the same background color resource as all other action bars. Or even more radical: why do we have tried to design a "action bar" ourselves? (Nowadays) there is a AndroidX Toolbar component which should be used for the popup...

But as this is of topic I will create an own issue for it.

**Comment by Lineflyer** [comment]
OK, but not on the action bar on main screen and cache list then.

**Comment by Lineflyer** [comment]
Some views of Windows 10 dark mode of Windows Explorer:

File window section (the working place background)
![image](https://user-images.githubusercontent.com/949669/119566029-f2c4b600-bdaa-11eb-961a-934c84dfc9e5.png)

Directory tree (kinf of menu or separated area):
![image](https://user-images.githubusercontent.com/949669/119566164-21db2780-bdab-11eb-8537-a2415fea587a.png)

There is also a pure black, but only on the small menu section:
![image](https://user-images.githubusercontent.com/949669/119566382-5ea71e80-bdab-11eb-931f-f5b4430c033d.png)

**Comment by Lineflyer** [comment]
I think we should fix this issue first as the final background is needed to judge other parts of the new design.

I would suggest to try out `#FF191919` or `#FF202020`.

**Comment by MagpieFourtyTwo** [comment]
Why not just make it configurable?
Or even allow to set a background picture?
Cause whatever color will be set, you will never meet everybody taste anyway.

**Comment by moving-bits** [comment]
We are talking about two different things here:
a) We need a background color anywhere in the program, not just on the main screen => That's what this issue is about
b) And then, maybe, we need to (re-)add some extra handling for the main screen (TBD)

**Comment by MagpieFourtyTwo** [comment]
Ok, got it.

However - over the day I have collected a (big) bunch of GUI glitches. Are you still working on them (so I'll wait for the next coming changes) or should I already open a new issue for it? Or should these just be discussed over here, too?

**Comment by moving-bits** [comment]
Theming overhaul is still ongoing and will take some time, until all things have settled. But we need feedback to be able to get to know which things are broken, so please open new issues for it, very welcomed!
(In most cases it's best to open a separate issue for each glitch, except you are pretty it has the same cause.) Thanks 👍

**Comment by Lineflyer** [comment]
> However - over the day I have collected a (big) bunch of GUI glitches. Are you still working on them (so I'll wait for the next coming changes) or should I already open a new issue for it? Or should these just be discussed over here, too?

Sure, if its not already listed.
You can check existing theme issues with this filter:
https://github.com/cgeo/cgeo/issues?q=project%3Acgeo%2Fcgeo%2F20+

**Comment by MagpieFourtyTwo** [comment]
Is there already an issue for increasing text brightness?
Contrast between text and background is too low,
thus very hard to read.
