### ISSUE TITLE
Material theming: icon buttons 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10769]
Followup of issue  #10739.

Text buttons are fine now, but the PR had broken our current icon button implementation...

material.io should explain the suggested icon button implementation somewhere...

**Comment by fm-sys** [comment]
> Does it make sense to start the issue for converting png to svg #9088?


Yes, sure. 

> Advantage: the color for the icons can be different for the different themes.

You don't even need to create two different SVG's.  Just change/set the color to `@color/colorText` inside the SVG definition...

![grafik](https://user-images.githubusercontent.com/64581222/119854785-a8aa1480-bf11-11eb-9cf6-7b97d563bcad.png)

**Comment by fm-sys** [comment]
If you want to step into it (which would be very appreciated!) please use googles material icons (wherever possible). They can be added very easily via android studio...

|||
|-|-|
|![grafik](https://user-images.githubusercontent.com/64581222/119855746-76e57d80-bf12-11eb-8891-e80f66b0285c.png)|![grafik](https://user-images.githubusercontent.com/64581222/119856006-ad22fd00-bf12-11eb-99e8-21906fbfc63d.png)|

**Comment by murggel** [comment]
Ok, I will step into it.

Please assign the issue to me

**Comment by fm-sys** [comment]
@murggel I have assigned #9088 to you.

This issue (#10769) is more about other changes needed for material icon buttons. E.g we need to switch from `ImageButton` to `Button` to get the buttons correctly themed...

**Comment by murggel** [comment]
> @murggel I have assigned #9088 to you.
> 

@fm-sys That's exactly what I expected  ;-)

**Comment by moving-bits** [comment]
@fm-sys 
This issue is unclear to me. What is "broken" with our icon buttons in material theme, and what do you suggest as desired target state? (Or was it a temporary problem, and we can close here?)

**Comment by fm-sys** [comment]
Before we have switched to material, all icon buttons had a surrounding. This is missing now do buttons aren't easy to recognize as button anymore:

![Screenshot_20210609_191557_cgeo geocaching](https://user-images.githubusercontent.com/64581222/121400053-647a3380-c957-11eb-905d-3ccee47e0dbc.png)

**Comment by Lineflyer** [comment]
That came to my mind as well. I also think the buttons (meaning those outside of the action bar) should again have a border.

**Comment by moving-bits** [comment]
Played a bit with styles and attributes, but so far I can only either have a nice format for the buttons, or make them clickable, but not both. Strange.

Basic formatting a button can be done by changing its type from `ImageButton` to `Button` and the attribute `app:srcCompat` to `app:icon`. The result still needs some visual fine-tuning, but it should work at least - which it doesn't: Adjacent text gets hidden (e. g.: lists that cache is stored in), and nothing happens when clicking the button - just by changing those two attributes of a button.

![image](https://user-images.githubusercontent.com/3754370/121429407-2bea5200-c977-11eb-924a-6464628f8514.png)

**Comment by murggel** [comment]
> Played a bit with styles and attributes, but so far I can only either have a nice format for the buttons, or make them clickable, but not both. Strange.
> 
> Basic formatting a button can be done by changing its type from `ImageButton` to `Button` and the attribute `app:srcCompat` to `app:icon`. The result still needs some visual fine-tuning, but it should work at least - which it doesn't: Adjacent text gets hidden (e. g.: lists that cache is stored in), and nothing happens when clicking the button - just by changing those two attributes of a button.
> 
> ![image](https://user-images.githubusercontent.com/3754370/121429407-2bea5200-c977-11eb-924a-6464628f8514.png)
> 

Probably because the button is referenced in the source and you have to adapt the type there as well?
Dis not looked in the code yet...

**Comment by fm-sys** [comment]
I've started a first test in PR https://github.com/cgeo/cgeo/pull/10772 as well. But feel free to take over the PR if you like.

From what I have found out: `iconSrc` must be changed to `app:icon` and `ImageButton` must be changed to `Button`. Our `ic_button` style is working without adaptions and looks correctly themed...

**Comment by murggel** [comment]
> I've started a first test in PR https://github.com/cgeo/cgeo/pull/10772 as well. But feel free to take over the PR if you like.
> 

How can I do that? Because on my machine it works....

**Comment by fm-sys** [comment]
> > I've started a first test in PR #10772 as well. But feel free to take over the PR if you like.
> 
> How can I do that? Because on my machine it works....

You have to create an own PR. With "take over" I meant something like "get inspired" by it and use it as base ;-)

**Comment by murggel** [comment]
> 
> 
> > > I've started a first test in PR #10772 as well. But feel free to take over the PR if you like.
> > 
> > 
> > How can I do that? Because on my machine it works....
> 
> You have to create an own PR. With "take over" I meant something like "get inspired" by it and use it as base ;-)

Ok, I can do that, but I don't know how long it will take, to change all buttons and test them... But for a first draft I can go.

**Comment by murggel** [comment]
BTW do we really want to use the orange accent color on all buttons or shall I try to change that back to "normal"?

**Comment by Lineflyer** [comment]
I would prefer the neutral color for the icon-buttons.
Thats too much orange otherwise.

**Comment by fm-sys** [comment]
> I would prefer the neutral color for the icon-buttons.
> Thats too much orange otherwise.

But I think we should stay consistent: either text and icon buttons neutral or both orange. But probably some screenshots would help for a decision: 
1. All orange
2. Text button orange / icon neutral 
3. All neutral

**Comment by murggel** [comment]
Screenshots will follow soon...

**Comment by murggel** [comment]
![grafik](https://user-images.githubusercontent.com/70113341/121787388-174fc900-cbc6-11eb-9c3c-c8abfcde9b9b.png)

**Comment by murggel** [comment]
![grafik](https://user-images.githubusercontent.com/70113341/121787395-233b8b00-cbc6-11eb-8da7-4a443c1c6421.png)

**Comment by murggel** [comment]
![grafik](https://user-images.githubusercontent.com/70113341/121787406-2e8eb680-cbc6-11eb-85f6-2219af6b3019.png)

I will try this one with outlined version of the icons...

**Comment by murggel** [comment]
![grafik](https://user-images.githubusercontent.com/70113341/121787423-41a18680-cbc6-11eb-988c-45d17d916ac8.png)

I will try this one with outlined version of the icons as well, because this would be the same as the on in the comment above.

**Comment by murggel** [comment]
![grafik](https://user-images.githubusercontent.com/70113341/121787487-8c230300-cbc6-11eb-8337-17b104aac4d1.png)

**Comment by fm-sys** [comment]
OK, probably "all orange" is really a bit too much. So I would vote for text button with accent color and icon in neutral color.

>  I will try this one with outlined version of the icons... and a version with alpha-channel...

 I would say, the current look (like in the posted screenshots) is just fine 👍

**Comment by moving-bits** [comment]
I guess we can close this issue now, after the two related PR have been merged.
