### ISSUE TITLE
Material theming: User name in logbook too small

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10760]
The username on the logbook tab of a cache is now too small.
As it is the starting point of the log it should have at least the same text size as the log text itself.

The remaining logbook view looks IMHO fine so far.

![grafik](https://user-images.githubusercontent.com/949669/119660042-15001780-be2f-11eb-833b-ff09a8e1c7c1.png)

**Comment by eddiemuc** [comment]
I used this chance to look into new themes and styles and fixed this small issue while at it in PR #10762

**Comment by eddiemuc** [comment]
![image](https://user-images.githubusercontent.com/6909759/119670274-0c144380-be39-11eb-8938-6e79cb911892.png)
