### ISSUE TITLE
Material Design: Make use of TextInputFields

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10763]
Make use of TextInputFields

https://material.io/components/text-fields/android

![grafik](https://user-images.githubusercontent.com/64581222/119679948-12a6b900-be41-11eb-89f3-2805806c9171.png)

This should IMHO be used for all TextInputs (search, coordinate input, ...), as the inputs are currently nearly invisible...

![grafik](https://user-images.githubusercontent.com/64581222/119680662-aed0c000-be41-11eb-85dd-bd53b182ea4a.png)

**Comment by eddiemuc** [comment]
Note that in PR #10875 I introduced such a new textfield and created a first style "`textinput_dropdown`" for it. From screenshot above I concluded that you would like to use "Outlined-Boxes", which I did. Relevant resources:
* style.xml
* cache_filter_generic_string.xml

Note that I used a AutoCompleteTextView variant, but other variants can be added too of course. Also fine-tuning of the style might become necessary, but as a first draft I think it looks quite good!

Empty, not-yet-used textfield:
![image](https://user-images.githubusercontent.com/6909759/120932271-6644bc80-c6f5-11eb-90df-c3203dea6ff1.png)

After selecting and typing "my text":
![image](https://user-images.githubusercontent.com/6909759/120932301-807e9a80-c6f5-11eb-8b8d-24784151883a.png)

After focus leaves text field:
![image](https://user-images.githubusercontent.com/6909759/120932315-90967a00-c6f5-11eb-9902-cbfd38198183.png)

**Comment by eddiemuc** [comment]
Ah, and I set the label "Search Text" on the text input field

**Comment by Lineflyer** [comment]
Offtopic:
That reminds me, that we should use this styles of input fields in all other places as well. The current style with underline accent only looks kind of "broken". Do we have an issue for that already?

**Comment by Lineflyer** [comment]
Forget my comment. In fact this is the issue I was looking for :D   I am kind of confused today.

**Comment by moving-bits** [comment]
I'm trying to migrate the coordinates input dialog currently. First steps went smooth, but depending on input type I have the problem that layout padding inside the outline box is so large, that the numbers itself are barely visible (e. g.: see the cut-off "2" in the last three edit fields in the upper row). 

Any ideas on how to reduce it? No variant of padding* or margin* attributes have worked for me, neither the "Dense" variant.

![image](https://user-images.githubusercontent.com/3754370/121593331-17bc5880-ca3c-11eb-99a9-689fb91e1536.png)

**Comment by moving-bits** [comment]
Regarding the input dialog (see https://github.com/cgeo/cgeo/issues/10763#issuecomment-859041188): I've implemented a solution (colored box around the whole coordinates input are) with PR #10969.
