### ISSUE TITLE
Material Theming: splash theming

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10761]
Use correct theme for splash activity. Currently, the android info bar (don't know how it's called) is purple - the material default accent color...

Solution: We should use the correct theme for splash activity.

![grafik](https://user-images.githubusercontent.com/64581222/119664444-9fe31100-be33-11eb-93ec-535475a149bd.png)

**Comment by moving-bits** [comment]
The theme is already set to `Theme.MaterialComponents.DayNight.NoActionBar`, but it looks that without defining a couple of other colors, you need to explicitly define the `statusBarColor`. Shall this be always black?

**Comment by Lineflyer** [comment]
Is this only on the splash or does it have an effect on other screens as well?

**Comment by moving-bits** [comment]
This is for the splash screen only, as this does have (and, AFAIK, needs) a separate theme.

**Comment by fm-sys** [comment]
The actionbar color is set as statusBarColor under some conditions, but this is all fine and Android is handling it very good automatically. Just the splash screen was problematic.
