### ISSUE TITLE
Show full cache name in cache preview

### ISSUE THREAD

**Issue by markusobi** [cgeo/cgeo#10774]
There are many geocache series out there that use the following name schema:
```
A very very very long description prefix #1
A very very very long description prefix #2
...
```
**When clicking a cache on the map in cgeo only the first part of the name is displayed - often not containing the important information at the end.**
It would be nice to immediately see the full name without having to additionally clicking on details. If there is no cell phone reception, showing the details might not even work! Rotating the screen is a workaround, but very annoying and the name might be still too long.
IMHO smartphone displays should be large enough nowadays to show the full name.
Maybe make it multi line text and/or adjust the text size.

Example ([GC97DZB](https://www.geocaching.com/geocache/GC97DZB)):
The full cache name/number `Traumrunde Prichsenstadt #04` is only visible after rotating the device.
<img src="https://user-images.githubusercontent.com/16803864/119869021-10675c00-bf20-11eb-9d06-7163a0a644a8.jpg" width="300">

<img src="https://user-images.githubusercontent.com/16803864/119870648-e2831700-bf21-11eb-81c6-c670f05c8e4e.jpg" height="300">

**Comment by Narrat** [comment]
Just for reference: #10750

**Comment by moving-bits** [comment]
I can imagine different approaches to it:
- allow the target info (*) to occupy up to two lines (* that's the semi-transparent text starting with the GC code)
- and/or add the cache name to the popup window above the "Typ" line, allowing it to use up to two lines (one could remove the title from the popup's action bar, then, or replace it by GC code only, and remove that one from the popup's content part)

**Comment by markusobi** [comment]
> 
> 
> I can imagine different approaches to it:
> 
>     * allow the target info (*) to occupy up to two lines (* that's the semi-transparent text starting with the GC code)
> 
>     * and/or add the cache name to the popup window above the "Typ" line, allowing it to use up to two lines (one could remove the title from the popup's action bar, then, or replace it by GC code only, and remove that one from the popup's content part)

The first suggestion is basically ruled out, because the target info is "usually" not visible. I picked a bad example. On the screenshot I had selected a single cache and used the show on map feature. The target info is not visible when clicking on a cache on the _Live-Map_. If someone selects a specific cache, it is less likely that he wants to view the name again anyway. Fixing it for the popup window would fix all workflows (show on map/Live-Map).

**Comment by jakedot** [comment]
@moving-bits swapping title and GC code sounds like a good idea, as the GC code has a fixed max length mostly. notice however, that it is significantly longer for ALCs, and isn't something useful to the user there.

**Comment by moving-bits** [comment]
So far my PR only adds the cache name to the content section, and leaves the title unchanged.

If we want to display the GC code we need to decide which one to take for a waypoint popup - probably either the cache's GC code or both.

ALC GC code is not a problem really, as we have a helper function to present a short code. (But still a user cannot do much with a GC code for an ALC.)

**Comment by jakedot** [comment]
The labs2gpx site uses the Firebase link suffix for their GC code. Might be a possible replacement for us too, it doesn't really help the user any more than the long id, but it would at least lead to a code that somewhat matches the labs2gpx service.

**Comment by moving-bits** [comment]
We had some really long discussions about this - which of the several codes to use. In the end we decided to use the actual id, which we need to retrieve the ALC data anyway using the API, mostly for technical reasons as that's how c:geo works internally and as the other codes provided using the API do not give you a real advantage.
