### ISSUE TITLE
Update Mapsforge dependency

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10773]
_Originally posted by @devemux86 in https://github.com/cgeo/cgeo/discussions/9516#discussioncomment-793831:_

I published [Mapsforge 0.16.0](https://search.maven.org/search?q=g:org.mapsforge) in Maven.

Thanks for all the code contributions!

**Comment by eddiemuc** [comment]
I assume this will pop up soon via dependabot automatically?

**Comment by fm-sys** [comment]
I guess not, as we currently use the snapshot builds...
