### ISSUE TITLE
Theming: Darker backgournd not used for map popup of waypoints

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10777]
While after merging #10765 the background for the map popup for a cache is according to style, there is still the lighter background if you open the popup for a waypoint of a cache:

2021.05.27-NB1 (Build after merging #10765):

Waypoint popup:
![image](https://user-images.githubusercontent.com/949669/119898819-9a282100-bf42-11eb-9245-d45c552fd1fb.png)

**Comment by fm-sys** [comment]
All dialogs have a lighter background than activities. That's the way how it is intended.

But the important question is whether the cache popup should be declared as dialog or activity...

**Comment by Lineflyer** [comment]
I wasn't aware that there is a code wise difference between a waypoint popup and a cache popup. 
Anyway from users perspective it should have the same styling as its kind of the same (a cache is also a waypoint in its classical definition).

**Comment by fm-sys** [comment]
Ah, ok. Got it. But I would actually rather change the cache popup background color. 

The waypoint color is the one we use for other dialogs as well...
