### ISSUE TITLE
Permission ACCESS_BACKGROUND_LOCATION is missing

### ISSUE THREAD

**Issue by Chris56** [cgeo/cgeo#10781]
## Bug description 
Since Android 10 the app need the permission ACCESS_BACKGROUND_LOCATION to do tracking when screens saer is on!

### Steps to reproduce the problem
Use Android 10 an minimize cgeo while walking. You will need to do so to conserver battery power.

### Actual result after these steps 
The gps tracking will not be used. The gps will again be accessed only when putting cgeo to live (usually near the cache)

### Expected result after these steps 
Trackng should work, when not in foreground

## c:geo version 
2021.05.20

## Reproducible 
Yes

## System information 

```
Paste your system information here
```

**Comment by bekuno** [comment]
There is probaly more to do, see https://developer.android.com/about/versions/10/privacy/changes#app-access-device-location

**Comment by Lineflyer** [comment]
Reference to #7057 

AFAIR there is also a special assessment for Google Play apps which require this permission. Not sure if c:geo qualifies for that from Google perspective.

**Comment by fm-sys** [comment]
> Not sure if c:geo qualifies for that from Google perspective.

Definitely, c:geo could request this permission without problems. Google isn't that strict with these permissions. The rule is only intended to prevent users from being permanently tracked by arbitrary apps (e.g. Galerie, Notepad, ...). It is sufficient to be able to justify what the permission is required for.

**Comment by Chris56** [comment]
The other reason for not generally allow app to use the location in background: the battery drain should be under control.
In the case of cgeo with tracking on, the standard usage will be not holding your mobil all the time, but walking with the mobile screen off; only now and then checking your position.
Right now, the tracking will not show your correct path but will jump, because no tracking will be performed while in background.

**Comment by fm-sys** [comment]
We do not even need `ACCESS_BACKGROUND_LOCATION` permission for GPS tracking in a _foreground service_ as long as this service is started from within a activity the user actively interacted with. 

That's what I have read in the changelog of another GPX tracker:

![Screenshot_20210602_124743_com android vending_copy_539x448](https://user-images.githubusercontent.com/64581222/120468120-2aca8b00-c3a1-11eb-94ea-ed141fc505a1.png)
