### ISSUE TITLE
History is default filtered for offline log only

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10798]
While using 2021.05.29-NB in the field I noticed, that the history list seems to be filtered by default to caches with offline log.

This is a different behavior to before where it also contained found and DNF caches AFAIR.

**Comment by eddiemuc** [comment]
This behavior would be an error.

@Lineflyer for clarification:
* Do you mean that there was by default a filter for offline logs defined (which you could remove)?
* Or do you mean that the list was filtered for offline logs, but without showing this explicit as a filter (and thus you were unable to remove the filter)?

**Comment by Lineflyer** [comment]
Still in the field at this moment.

On the second look it seems I applied the filter some days ago.
Its however specific to the history list but not active on other lists.

Shouldnt it be the same filter instance?

**Comment by eddiemuc** [comment]
Right now each "list type" stores it's own filter instance. 

Can be changed to same instance everywhere (which would then be the "global filter").

**Comment by Lineflyer** [comment]
What kind of list types do we have?

**Comment by eddiemuc** [comment]
I have currently no access to my Android Studio unfortunately. 

See https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/enumerations/CacheListType.java for all currently defined cgeo cache list types (note that this is not my invention, this list was there long before my time)

**Comment by Lineflyer** [comment]
Ah, ok. 
So lets see if these separate instances are understandable for users or more confusing.
Lets however close here. No bug.

**Comment by eddiemuc** [comment]
Actually, I think it would be the right time to discuss this in the context of "global filter" and its relationship to "other filters! (or if there should not be such other filters), I propose to use #10711 for this
