### ISSUE TITLE
Progress spinner has wrong accent color

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10793]
When refreshing a cache the progress spinner is using some greenish color instead of our orange color accent (tested on dark theme).
Seen in todays nightly 2021.05.28-NB

**Comment by fm-sys** [comment]
Yes, noticed it as well, but it's not only the spinner. Anyway, should be an easy fix...

**Comment by fm-sys** [comment]
Other areas where the color accent is not applied:

- List chooser dialog
- gpx import
- global cache type filter

**Comment by moving-bits** [comment]
- will mostly be solved with #10812
- needs #10816 additionally for some variants of horizontal progress bar

**Comment by fm-sys** [comment]
I found an easy solution for fixing the accent color...
