### ISSUE TITLE
wrong alertdialog theming in settings

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10792]
While working on #10721 I noticed that alert dialogs in the settings always follow the system theme. Not c:geo's preference... 

Reproducible with current nightly. 

![Screenshot_20210528_225942_cgeo geocaching_copy_270x585](https://user-images.githubusercontent.com/64581222/120041649-e63d9900-c008-11eb-8b52-2992fa6acc77.jpg)

**Comment by fm-sys** [comment]
Haven't found a way to solve it yet... Maybe someone else has more luck ;-)

**Comment by moving-bits** [comment]
@fm-sys 
I've added some styling for settings' AlertDialogs with #10968 - seems ok to me now, can you cross-check?

**Comment by fm-sys** [comment]
Yes, works in general (far better than before 👍) but:
- dialog has some wired black area around it (when using "system default")
- acent color for the dialog action buttons ("cancel" in this case) is missing

![grafik](https://user-images.githubusercontent.com/64581222/122683651-ea706700-d200-11eb-85e2-8fbe31811e29.png)
