### ISSUE TITLE
List dropdown indicator has red color on Android 5

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10795]
Seen with 2021.05.19-NB on an Android 5 device.
In dark theme the small down pointing arrow in the action bar for lists right next to the list name is bright red.

Will provide screenshot tomorrow.

**Comment by Lineflyer** [comment]
Screenshot:

![Screenshot_2021-05-28-23-50-35](https://user-images.githubusercontent.com/949669/120064897-e1abcb80-c06e-11eb-8341-68392d1a5ff0.png)

Device: 
ZTE Blade S6
Android 5.0.2

**Comment by moving-bits** [comment]
Could not make it work until now. Have followed several recipes, most of them playing with `backgroundTint` or even to set background mode programmatically, but the dropdown indicator does not react to it. Also changing all `Spinner` to `appcompatx Spinner` explicitly did not change anything.

What's special in this case is, that we use our own layout for the spinner items to make it two-lined, but using a view adapter is standard procedure in such cases and should not touch the dropdown indicator.

**Comment by Lineflyer** [comment]
Lets close this without fix. I tried on the emulator and it seems only to affect API21 (Android 5.0), only in dark mode and has no functional impact.
