### ISSUE TITLE
Weird transition for map quick settings bottom sheet

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10790]
I'm experiencing a weird transition for the map quick settings bottom sheet in the emulator:
- On opening the bottom sheet, it's immediately displayed at the preset size,
- then moves to the left, until no bottom sheet is visible,
- and then returns from the bottom, again to it's preset size, and stays there.

(Not yet fixed with #10787)

**Comment by fm-sys** [comment]
>     * then moves to the left, until no bottom sheet is visible,

What do you mean with swipe to left? Could you maybe even provide a video or something like that?

**Comment by moving-bits** [comment]
I'm opening the map quick settings dialog by tapping the button. The rest happens automatically (steps as described above).

Do you know how to create a screen recording from what's happening in the emulator window?

**Comment by fm-sys** [comment]
> Do you know how to create a screen recording from what's happening in the emulator window?

I think you have to install a screen recorder app either in the emulator or for windows. Or just take your mobile and film the pc monitor ;-)

**Comment by moving-bits** [comment]
I've create a little video with both transitions. Video starts with pushing the button to open the dialog. Behavior is as described above.

At around 6s into the video I push the back button to close the dialog. This transition seems also a bit strange to me, as it looks like the dialog gets closed immediately, then reopend again to fade-out to the bottom again.

See https://www.moving-bits.net/cgeo/MapQuickSettingsWeirdTransitions.mp4

(You'll probably have to replay this video at half the original speed or so.)

**Comment by fm-sys** [comment]
This. Is. Really. Strange. 

Never have seen something like that on either the emulator or my physical device. No idea what's the problem or how it could be fixed...

This is how it should look like:

https://user-images.githubusercontent.com/64581222/120082411-32e5aa80-c0c3-11eb-8aae-f2e25806a537.mp4

**Comment by Lineflyer** [comment]
What API level / device on emulator?

**Comment by moving-bits** [comment]
For me: A Nexus 5X with API 30 (Android 10) in the emulator

**Comment by fm-sys** [comment]
> API 30 (Android 10)

Isn't API 30 Android 11?  Android 10 / Android Q is API 29...

**Comment by moving-bits** [comment]
> > API 30 (Android 10)
> 
> Isn't API 30 Android 11? Android 10 / Android Q is API 29...

You're right. My emulated device is called "API 30 (10 GB)", as this is for testing with extra large downloads, and the "10 GB" mislead me in this case... ;-)

**Comment by moving-bits** [comment]
Cannot reproduce this behavior anymore, using the same emulator - therefore closing here for now.
