### ISSUE TITLE
Replace ProgressDialog with material AlertDialog + material ProgressIndicator

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10816]
## What function are you missing
- `ProgressDialog` got deprecated with API 26
- and does not respond to material design colors

## Suggested solution
- replace `ProgressDialog` with an material-based `AlertDialog` with an material progress indicator

**Comment by jakedot** [comment]
wasn't there an issue sometime about getting rid of the blocking progress dialogs altogether and implementing stuff like that in a background service and progress notification?

**Comment by fm-sys** [comment]
Yes and no.

ProgressDialog got deprecated because developers should use background services for it. And yes, we even have an issue (#330) for it. But we have over 20 different progress dialog usages in c:geo. Nearly an impossible task to refactor them all one by one...

**Comment by Lineflyer** [comment]
Not sure whether this is the same issue:
The progress bar when batch refreshing stored caches does not use our accent color (dark theme, did not check light theme).

**Comment by fm-sys** [comment]
> ## What function are you missing
> 
>     * `ProgressDialog` got deprecated with API 26
> 
>     * and does not respond to material design colors
> 
> 
> ## Suggested solution
> 
>     * replace `ProgressDialog` with an material-based `AlertDialog` with an material progress indicator

As I found a solution for the theming problem in #11052, I would vote for closing this issue. `ProgressDialog` got deprecated because progress bars should be implemented in a non-blocking way. So replacing this deprecated component with a self created `AlertDialog` would make thing even worse...

@moving-bits Would closing this issue be ok for you?

**Comment by moving-bits** [comment]
> @moving-bits Would closing this issue be ok for you?

Sure. And thanks for tackling the color issue!
