### ISSUE TITLE
Downloader: delete temporary files on download or copy error

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10815]
On download error: delete residual files

---

_Originally posted by @Vike91 in https://github.com/cgeo/cgeo/issues/10813#issuecomment-852418600:_

Yes, I think that's what happened, around 2 weeks ago (map file had a day stamp of 21.5.2021) my network got cut out in the middle of the download, and the dl manager notified me of the failed download. It may have been the residual map file of that download attempt.

**Comment by fm-sys** [comment]
Yes, sounds wise. But please postpone until #10310 is finished...

**Comment by moving-bits** [comment]
There should be two parts, probably:
- delete file after a download error happened => will be done in the notifier, before the receiver (background or foreground) gets even started, and
- delete file after a copy error happened => this should be implemented in the upcoming background receiver service (if not done already)

**Comment by fm-sys** [comment]
>     * delete file after a copy error happened => this should be implemented in the upcoming background receiver service (if not done already)

If only the copy fails we should show a hint that the user have to move the file manually but we should never delete it automatically IMHO

**Comment by moving-bits** [comment]
> If only the copy fails we should show a hint that the user have to move the file manually but we should never delete it automatically IMHO

True, but in that case the broken copy should be deleted. (Which is what I meant - I should have been more specific in my post above.)

**Comment by moving-bits** [comment]
First part - deleting a partially downloaded file after download fails - will be fixed with #10824.

**Comment by Narrat** [comment]
What about resumeable downloads? Dunno if the downloader already checks for this or cannot do it at all, but maybe it would be more favorable to check that before removing the file? Since the talk is about files that can be relatively large in size.

**Comment by moving-bits** [comment]
AFAIK the Android system's downloader (which we are using here) has built-in resume capability.

**Comment by moving-bits** [comment]
> What about resumeable downloads? Dunno if the downloader already checks for this or cannot do it at all, but maybe it would be more favorable to check that before removing the file? Since the talk is about files that can be relatively large in size.

@Narrat 
FYI:
Sometimes the system's downloader seems to "need a reminder" to resume the download, so we have implemented a "pending downloads" view meanwhile, in which you can resume or cancel pending downloads. See menu "Pending downloads" on home screen.
