### ISSUE TITLE
Downloaded offline map files not deleted after c:geo copies them from download to own dir

### ISSUE THREAD

**Issue by Vike91** [cgeo/cgeo#10813]
Problem: downloaded map file not deleted from the default downloader folder after c:geo copies it from the download folder to the cgeo folder, thus eating some of storage space if user is not aware to delete the downloaded file. This is a problem especially with big files (for example the Finnish Hylly map file which is around 4 GB).

Possible fixes:
1. Download map files and their themes directly to the corresponding folders which c:geo uses
or
2. Delete them after copying them to right place.

I think the first fix listed would be the most effective way, as the copying step has been completely skipped.

**Comment by moving-bits** [comment]
Hi Vike91,

thanks for reporting this. Alas I don't know at hand what has failed here, as we have implemented your suggestions number 2 already actually, so a file, which got successfully downloaded and copied, should be deleted from their temporary place automatically.

We had also tried your suggestion number 1 during implementation of the downloader, but it has shown not to work under certain conditions (or better: ONLY to work under some specific conditions which most of the time we do not meet), so we chose the "download and copy" solution.

Did you receive any error messages, either during download of the file or while copying it to your map folder?
Is your downloaded map file fully functional, or do you get some error messages while using the map? (Could be a truncated file then.)

**Comment by Vike91** [comment]
I checked again, and the map file lurking in my download folder has a different download info than the one in the c:geo folder.

Thought I'd test the download, actually deleted all the map files in the question from the phone, checked there is none, downloaded map file again via the internal downloader, waited until the progress finished and checked again.

It did delete the residual map file as it should.

I guess I should go sit in the naughty corner for a moment... closing the issue now. Sorry for the mistake!

**Comment by moving-bits** [comment]
No problem at all. I guess something went wrong during the older download, so that an incomplete file was left behind in your download folder. It should eventually get deleted automatically by Android as soon as the system's running out of space, but I guess there's room for improvement in c:geo's way of handling download errors (if it gets notified for them) - need to check that.

**Comment by Vike91** [comment]
Yes, I think that's what happened, around 2 weeks ago (map file had a day stamp of 21.5.2021) my network got cut out in the middle of the download, and the dl manager notified me of the failed download. It may have been the residual map file of that download attempt.

**Comment by moving-bits** [comment]
I've created a new issue for discussing cleanup of broken files - either due to a failed download or due to a failed copy, see #10815.
