### ISSUE TITLE
Download background service follow-ups

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10829]
## What function are you missing
Some fine-tuning for the nice new background service download receiver, coming from https://github.com/cgeo/cgeo/pull/10310#issuecomment-853586851:
- Automatically activate a downloaded map / a downloaded map theme after having successfully downloaded and imported that file.
- Show the name of the file being imported in the notification

**Comment by jakedot** [comment]
Is acrivating the file for a new map really a good idea? I wouldn't want that as I'm more likely to plan where I'm going from home, and would have a map fitting for my current needs already active. IMO we should only do that if there's not yet an active offline map and the offline map is not set to "Combined" (if that's possible without having a map first). For a theme, I think it's a good idea to always activate it aftrr download.

**Comment by moving-bits** [comment]
That's at least the way it does work currently. But we may discuss it, of course.

**Comment by fm-sys** [comment]
@moving-bits is this issue still relevant?

**Comment by moving-bits** [comment]
IIRC we have a separate issue regarding the auto activation of a downloaded map, and the name of the file being imported is probably only relevant if you download several large files at the same time. (If you are importing small files, importing is faster than the notification being shown, and if you import a single large file, you'll probably remember which file you'd just downloaded.)
So I guess we can close here.
