### ISSUE TITLE
Installation wizard still using wrong button type

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10835]
The installation wizard still uses the "full orange" buttons.

`Master` as of 03.06.2021

**Comment by fm-sys** [comment]
I wouldn't call this a bug. Actually I left them orange by purpose, so that the button are more visible and help users to find through the wizard.

But for sure this can be discussed.

**Comment by moving-bits** [comment]
same thought for me. It pushes our accent color during those first steps with the app, whereas the rest of the app uses that color a bit more subdued.

**Comment by Lineflyer** [comment]
I somehow don't like it for the same reason as why we decided to use the other button type in the app itself.
Why should we use it in the wizard then?

If after all, we keep using it, we should focus it on the button which represents the normal workflow of the wizard, but not all of them.
