### ISSUE TITLE
[downloader] Evaluate move instead of copy-delete once more 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10853]
Today, I downloaded the Germany offline map (2.4 GB). I had only 4 GB free storage left, so the import failed because for a shot time the mapfile  need to be stored twice. That shouldn't be the case IMHO. If a move is possible, the file should be moved instead.

**Comment by eddiemuc** [comment]
Teammeeting 19.11.23: as of now no method for "move" with contentstorage/SAF is known. Sadly we therefore close this issue
