### ISSUE TITLE
Use same icon for own caches in the map-settings as in the search-activity

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#10850]
## What function are you missing

Use same icon for own caches in the map-settings as in the search-activity
![grafik](https://user-images.githubusercontent.com/70113341/120870170-8448da80-c598-11eb-8b7e-a264fb05b6ff.png) ![grafik](https://user-images.githubusercontent.com/70113341/120870354-033e1300-c599-11eb-8889-356269a8a2ce.png)

## Suggested solution

![grafik](https://user-images.githubusercontent.com/70113341/120870440-3b455600-c599-11eb-8209-6b9fb7fe3d27.png)

## Alternatives/workarounds

![grafik](https://user-images.githubusercontent.com/70113341/120870475-544e0700-c599-11eb-9383-da27c52d2d0d.png)

**Comment by fm-sys** [comment]
Totally agree. And for 'logged offline" our pencil icon should rather be used...

**Comment by murggel** [comment]
Or something like for "logged offline" ?
 ![grafik](https://user-images.githubusercontent.com/70113341/120872097-e9eb9580-c59d-11eb-92f8-b065c77937e1.png)

**Comment by murggel** [comment]
@fm-sys you can assign it to me

**Comment by eddiemuc** [comment]
While you're at it, could you then also replace the icon for "exclude active" in the status filter? (Also a circle currently, see screenshot).

![image](https://user-images.githubusercontent.com/6909759/120848616-4c7c6b80-c575-11eb-8fce-ebbf8afad2a1.png)

**Comment by bekuno** [comment]
What icon do you want to use instead of the circle?

**Comment by fm-sys** [comment]
> Or something like for "logged offline" ?
> ![grafik](https://user-images.githubusercontent.com/70113341/120694465-86cd0680-c4aa-11eb-9864-0fdb047fd557.png) ![grafik](https://user-images.githubusercontent.com/70113341/120694532-9fd5b780-c4aa-11eb-9f38-540a5061741e.png)

IMHO these icons have nothing to do with "logged" which is the more important part than "offline". I would still suggest the pencil icon...

**Comment by murggel** [comment]
> What icon do you want to use instead of the circle?

To be honest, I would stay with the empty circle, it fits to the disabled and archived icon..

**Comment by Lineflyer** [comment]
I think:
- smiley forr found
- man with flagpole or star (like the owned overlay on map) for owned
- pencil icon for offline log
- for active the current icon is somehow understandable as the others (disabled, archived are strike through). It could just be a circle with a thinner line?

**Comment by murggel** [comment]
> 
> 
> I think:
> 
>     * smiley forr found
> 
>     * man with flagpole or star (like the owned overlay on map) for owned
> 
>     * pencil icon for offline log
> 
>     * for active the current icon is somehow understandable as the others (disabled, archived) are strike through. It could just be a circle with a thinner line to fit the others.

With the new svg the circle should already has a thinner line. 

Questions:
* for the found: the smiley with the big mouth as in the colored icon on the map ot with thin mouth?
* for the owned: the same icon as in the search-bar (man with flag) or only star from overlay map (replace it in searchbar as well) or man with star (replace it in searchbar as well)? When I am back at my machine
Some drafts (the right man is the one from the hint-icon):
![grafik](https://user-images.githubusercontent.com/70113341/120886577-fe0bb300-c5ee-11eb-812d-fe109d2ddfc9.png)

**Comment by eddiemuc** [comment]
> > What icon do you want to use instead of the circle?
> 
> To be honest, I would stay with the empty circle, it fits to the disabled and archived icon..

Fine for me too
