### ISSUE TITLE
List selection dropdown looks unformatted

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10854]
The dropdown menu to select another list while on a list, looks somehow unformatted.
Its hard to spot the desired list.

I suggest having different font styles (bold/standard) for list name and amount of caches and maybe additionally a visual seperator between each entry.

The chaotic look is enforced by the missing visual seperation between the dropdown background and the list background.
Maybe a border or other background color could help as well.

We could even replace the dropdown by the list selection dialog we use elsewhere. It does not need to be a dropdown from the action bar.

Not sure, whats the best idea.

2021.06.05-NB

![image](https://user-images.githubusercontent.com/949669/120886268-5c379680-c5ed-11eb-9ce3-dccfdfb8898b.png)

**Comment by Lineflyer** [comment]
On my tablet there is even another problem:

![image](https://user-images.githubusercontent.com/949669/120888742-53998d00-c5fa-11eb-8926-cc060c694c7a.png)

![image](https://user-images.githubusercontent.com/949669/120888757-68762080-c5fa-11eb-92ca-209f7d35e3fd.png)

**Comment by jakedot** [comment]
On my device, the list button also looks unformatted. The second line with the  ount information is cut in half.

**Comment by moving-bits** [comment]
Maybe adding some spacing will work:

![image](https://user-images.githubusercontent.com/3754370/120889795-1be11400-c5ff-11eb-94a4-aaa5837f4038.png)

Additionally, I could distinguish the font sizes a bit more. Currently we have 18sp for the first line, and 16sp for the second line, which is pretty close together. 
I could make it 20/16 (which we have in lists) for example, or 18/14 (with 14sp being the smaller font size in regular text).
