### ISSUE TITLE
Fix slider layout (in filter dialog) after GUI redesign

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10852]
After GUI redesign the labels on sliders for difficulty/terrain filters are not readible any more.

**Comment by Lineflyer** [comment]
Looking normal to me...except in white theme, where they are rather dark

**Comment by eddiemuc** [comment]
I mean something different:

There are numbers under the slider (1,0; 2,0; 3,0; 4,0; 5,0) which you now can't see any more because they are black-on-black in dark mode:

![image](https://user-images.githubusercontent.com/6909759/120890111-1389d880-c601-11eb-8269-88695e1940c9.png)

In white mode you can see them:

![image](https://user-images.githubusercontent.com/6909759/120890174-42a04a00-c601-11eb-89ea-196ee5165d46.png)
