### ISSUE TITLE
New filters: replace "cache size" toggle buttons with material.io buttons

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10851]
Replace "cache size" toggle buttons as well. Somehow I have to combine "ChipGroup" and "ToggleButtonGroup" for this.

![image](https://user-images.githubusercontent.com/6909759/120848616-4c7c6b80-c575-11eb-8fce-ebbf8afad2a1.png)

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/pull/10847#issuecomment-854930616_

**Comment by fm-sys** [comment]
https://material.io/components/chips/android#choice-chip

There's something called filter chip:

![Screenshot_20210605_093041_org mozilla firefox](https://user-images.githubusercontent.com/64581222/120883995-c269ec80-c5e0-11eb-9028-79c06081c3d9.png)

**Comment by eddiemuc** [comment]
> https://material.io/components/chips/android#choice-chip
> 
> There's something called filter chip:
> 
> ![Screenshot_20210605_093041_org mozilla firefox](https://user-images.githubusercontent.com/64581222/120883995-c269ec80-c5e0-11eb-9028-79c06081c3d9.png)
> 

I already use this (ChipGroup), but up to now in combination with a toggle button. Can replace it of course

**Comment by eddiemuc** [comment]
See PR #10863
