### ISSUE TITLE
Overflow menu hight

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10861]
Some of the recent changes had changed the overflow menu with as well, which is now vertically much to small compared to other apps...

![Screenshot_20210605_163554](https://user-images.githubusercontent.com/64581222/120895244-61600a00-c61c-11eb-8102-b9b34cf79bec.jpg)

**Comment by moving-bits** [comment]
#10838 will be the culprit here probably, or more exactly: the part of the PR that deals with the dialog list entries (which is used for the list selectors) - look like I will have to find a different way for the list selectors, or a way which is more specific to hit only the dialogs.

**Comment by Lineflyer** [comment]
Noticed this as well today. Definitly a bit too narrow to hit the wanted entry for my thick fingers ;)

**Comment by moving-bits** [comment]
See PR #10862
