### ISSUE TITLE
Cache list selection dialog is broken

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#10867]
## Bug description 

The popup to save a cache to a list or edit a cache's list memberships doesn't allow selecting any list anymore. Only way to save/change a cache list membership  now is to use the "last selection" button and then "move to list" in the cache listing.

### Steps to reproduce the problem

Try to save new cache to a list or change a cache's list membership.

### Actual result after these steps 

Cannot check/uncheck lists in the dialog.

### Expected result after these steps 

Should let you select one or more list by checking its  checkmark.

## c:geo version 

NB 06.06.21

## Reproducible 
Yes

**Comment by moving-bits** [comment]
This is pretty strange, as we've changed some styling here only - this should not affect any behavior of the selection dialog. But it obviously does... But only so in the multi-selection dialogs opened from map popup / cache details, not the one opened from main screen. I'll look into it.

**Comment by Lineflyer** [comment]
NB1 is building and should be available in 10 minutes.

**Comment by moving-bits** [comment]
Thanks for preparing a new nightly 🚀
