### ISSUE TITLE
[MapQuickSertings] Reduce font size or shorten strings

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10868]
My screen size is quite big, 6", but still all strings are truncated - some of them even unusable. We could either leave out "caches" and "waypoints" in the strings as that's contained in the title anyway, and/or reduce the font size... 

![Screenshot_20210606_084449_copy_539x545](https://user-images.githubusercontent.com/64581222/120915391-a8451280-c6a3-11eb-9d2d-5003e6d9524c.png)

**Comment by moving-bits** [comment]
we should shorten the titles, e. g.
- "Gefundene Caches" => "gefunden"
- "Caches mit Offline-Log" => "Offline Log"
- "Park-Wegpunkte" => "Parken"
- "Kreise anzeigen" => "Kreise"

etc.

If that's still not enough, we could
- reduce icon size (they are too big in this view, IMHO)
- leave out the icons (are they really needed?)
- change font size for the labels from `textSize_detailsPrimary` to `textSize_detailsSecondary` (as last resort)

**Comment by eddiemuc** [comment]
Icons are too large indeed...

Text values are already shortened in english version. I assumed that changing those will retrigger Crowdin translations, is this not the case?

![image](https://user-images.githubusercontent.com/6909759/120915898-ae88be00-c6a6-11eb-95ae-bd1005d7005d.png)

**Comment by murggel** [comment]
I can try to use for those buttons a smaller icon size

**Comment by fm-sys** [comment]
> I assumed that changing those will retrigger Crowdin translations, is this not the case?

Yes, retranslation will be triggered. So it might even be fixed in today's nightly, but I don't want to upgrade currently as there are major bugs in it. (#10867)

So part 1 is already solved, still we could reduce the icon size...

**Comment by moving-bits** [comment]
> Text values are already shortened in english version. I assumed that changing those will retrigger Crowdin translations, is this not the case?

Yes, it should trigger Crowdin, but that may take some time until all translations are back.
If you need to change something in a breaking way, one should change the string id, so that all translations fall back to English.

**Comment by eddiemuc** [comment]
> > Text values are already shortened in english version. I assumed that changing those will retrigger Crowdin translations, is this not the case?
> 
> Yes, it should trigger Crowdin, but that may take some time until all translations are back.
> If you need to change something in a breaking way, one should change the string id, so that all translations fall back to English.

I can do that next time. But is it really worth it to create/invent completely new string ids just to bridge one night / one nightly until crowdin resets the translated values? I didn't see the change "breaking" enough for this.

**Comment by moving-bits** [comment]
Nah, I didn't meant to imply that inventing new names should have been done in this case, just wanted to say that there are cases where it's better to invent new names (e. g.: meaning of a string changes completely; number of parameters within the string changes, and not enough time left before release etc.)

**Comment by moving-bits** [comment]
Closing here, as a couple of translations have reached Crowdin meanwhile, solving the problem:

![image](https://user-images.githubusercontent.com/3754370/121744458-3afe0b00-cb03-11eb-9235-03a33fe19082.png)
