### ISSUE TITLE
Export of calculated WP to PN not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10876]
@murggel 
I tried to test PR #10849 as follows:
- Took a traditional cache
- Added a reference point with calculated coordinates as follows:
N51 AB.139 E007 CD.529
A=t
B=f
C=u
D=r
f=3
r=4
t=5
u=2

This results in N51 53.139 E007 24.529

- If I backup the waypoints to the PN it adds only:
```
{c:geo-start}
@Markierung 1 (W)
{c:geo-end}
```

It seems not working even not if I ommit some values for variable to have an incomplete formula.

Tested with (to be release) 2021.06.06 as well as current NB.

**Comment by murggel** [comment]
Will check that

**Comment by murggel** [comment]
Damn regular expressions🙄

**Comment by murggel** [comment]
See PR #10878

**Comment by Lineflyer** [comment]
@murggel 
I tested `master` including PR #10878 but it does either not work for me or I have wrong expectation of that feature.

I have the following ready calculated waypoint:
![image](https://user-images.githubusercontent.com/949669/121431529-cf3c6680-c979-11eb-9440-4350ef3d3792.png)

This is what the waypoint page shows:
![image](https://user-images.githubusercontent.com/949669/121431575-df544600-c979-11eb-9317-06ea4d51c1fb.png)

This is the PN backup of that. It does not seem to contain any information but the user note. No coords, no formula:
![image](https://user-images.githubusercontent.com/949669/121431666-fbf07e00-c979-11eb-94cf-ab311d789ccb.png)

What am I missing here?

**Comment by murggel** [comment]
This works only for formulas in "plain"-format. You have a different formula format.

**Comment by murggel** [comment]
The other formats were not so easy to convert from text to the internal formula-syntax

**Comment by Lineflyer** [comment]
> The other formats were not so easy to convert from text to the internal formula-syntax.

Ok, understood.
Lets forget about the formula for now, but also the resulting coords are not pasted into the PN like they are for other self defined waypoints. Thus the backup into the PN is not complete.

**Comment by murggel** [comment]
> > The other formats were not so easy to convert from text to the internal formula-syntax.
> 
> Ok, understood.
> Lets forget about the formula for now, mmbut also the resulting coords are not pasted into the PN like they are for other self defined waypoints. 

But that should work. I will check. Sorry for that..

**Comment by murggel** [comment]
I just tested it with debug-release-version on my emulator:
![grafik](https://user-images.githubusercontent.com/70113341/121714969-ab466580-cade-11eb-8f0b-7f3843938bd2.png)
![grafik](https://user-images.githubusercontent.com/70113341/121714886-95d13b80-cade-11eb-9484-09e4827e4a94.png)

and it worked... hm, whats different?

**Comment by Lineflyer** [comment]
The note below it?

**Comment by murggel** [comment]
Ok will check that

**Comment by murggel** [comment]
Hm, looks good at my emulator - strange.
![grafik](https://user-images.githubusercontent.com/70113341/121741990-89110f80-caff-11eb-8894-f088dba607d5.png)
![grafik](https://user-images.githubusercontent.com/70113341/121742024-93330e00-caff-11eb-9612-007aab9da88f.png)
![grafik](https://user-images.githubusercontent.com/70113341/121741945-7991c680-caff-11eb-9783-b0c0ede708e7.png)
Probably you can send me somehow the data? Export the data from the cache from database or so?

**Comment by moving-bits** [comment]
On seeing the last screenshot (export to note): Is the prefix "Formel:" a localized string?

How does c:geo react if you change the language settings and import from this personal note? Will the formula still be recognized?

**Comment by murggel** [comment]
> On seeing the last screenshot (export to note): Is the prefix "Formel:" a localized string?
> 
> How does c:geo react if you change the language settings and import from this personal note? Will the formula still be recognized?

yes, it should be recognized, comma are replaced through point / dot before parsing (as for the parsing of waypoints with coordinates already done). 
But good point, I will change my language to german and test again...

But in this case the coordinates should be written to the personal note. The formula there is only in the user note (for parsing the formula into the calculator it needs a special keyword)

**Comment by murggel** [comment]
also in german it get exported:
![grafik](https://user-images.githubusercontent.com/70113341/121749919-bebbf580-cb0b-11eb-875c-19c19d77b1ac.png)

**Comment by murggel** [comment]
@Lineflyer does the problem (coords arenot exported to the PN) still exist on your device?

**Comment by Lineflyer** [comment]
I think so, but I do not use the plain format but the standard coord format with calculation. If I understand you correctly, this is not yet(?) included in export, right? 

Shall we take this into a clearer feature request issue?

**Comment by murggel** [comment]
There is a issue which we can use #9211 but I can create a new one for better tracking. I am currently working on it...

Extracting the formula is only supported for plain yet, but the calculated coordinates for the completed formula should be exported

**Comment by Lineflyer** [comment]
Yes, thats working.
So lets close here and continue in #9211
