### ISSUE TITLE
[New Filter] Filter for "origin of cache"

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10880]
As in the old filter we need a filter for cache origin:

![image](https://user-images.githubusercontent.com/6909759/120938203-fbee4500-c711-11eb-9869-b189536ad9f2.png)

**Comment by eddiemuc** [comment]
I have a question wrt the origin filter:

It seems that todays filter lists all the different OpenCaching-platforms as separate "origins" in the filter list.
BUT when I look in the code I see that the filtering is done purely on a geocode analysis base (the "origin" of a cache is not stored directly at the cache). SInce all OC platforms have the very same geocpode format (starting with OC), this means that all Opencaching-platform are "assumed" by the filter to be of the first OC-connector in the connectorlist. This happens to be the OC-DE-connector by chance.

My suggestion would therefore be to just have one single filter entry "OpenCaching" in the filter list. WOuld that be fine?

**Comment by eddiemuc** [comment]
Currently:
![image](https://user-images.githubusercontent.com/6909759/120938343-7fa83180-c712-11eb-86a9-47069ff7d23b.png)

**Comment by Lineflyer** [comment]
>  SInce all OC platforms have the very same geocpode format (starting with OC), this means that all Opencaching-platform are "assumed" by the filter to be of the first OC-connector in the connectorlist. This happens to be the OC-DE-connector by chance.

I don't know what you mean with "geocpode" but in fact different OC platforms have different geocode prefixes: e.g. OC.US has OU*, OC.NL has OB*, etc.

**Comment by eddiemuc** [comment]
> I don't know what you mean with "geocpode" 

Geocode :-)

> but in fact different OC platforms have different geocode prefixes: e.g. OC.US has OU*, OC.NL has OB*, etc.

If this is the case then I withdraw my question. It seems I oversaw this in the code then.

The underlying point is that as of today we can only use the geocode structure to differentiate between connectors/services/origins. But if each connector has a unique structure/prefix then that's easily possible.

**Comment by eddiemuc** [comment]
While working on this issue, I realized that the chosen cache prefix code for Lab Caches "LC" is already used by another connector: the TerraCachingConnector (uses TC, CC and LC). Filtering for lab caches will thus also match all TerraCachine-Caches starting with LC (most likely not vice versa since TerraCaching uses a very restricted cache pattern: )

I don't really think this will be a huge problem in practice, but would it be better to choose another prefix for lab caches so they don't clash?

**Comment by eddiemuc** [comment]
Fopr reference, this is the geocode pattern used by TerraCachingConnector: `(TC|CC|LC)[0-9A-Z]{1,4}`
(means: everything starting with TC, CC or LC with 1-4 letters/digits after)

**Comment by jakedot** [comment]
Let's use AL then. The LC prefix is also already used by the website tool exporting individual Labs as Virtual Caches.

**Comment by jakedot** [comment]
We could maybe differentiate in the filters and only show those for which connectors are configured. Then we would minimize chances for clashing.

**Comment by eddiemuc** [comment]
> We could maybe differentiate in the filters and only show those for which connectors are configured. Then we would minimize chances for clashing.

There could always be caches in the database for non-active connectors (e.g. stored before service was deactivated or while logged in with another user), so would not do that.

**Comment by eddiemuc** [comment]
Implementation is done now without considering the prefix clash thing. PR is #10910 

If this should further be evaluated, then I assume we should create a new issue for it.
