### ISSUE TITLE
[SVG] Use SVG-icons in the settings-activity

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#10898]
## What function are you missing

In the settings-activity the png are still used.

Currently it is not working correctly.  #10579 (refactor to use PreferenceFragmenst) is probably a good pre-requisit for that

## Suggested solution

Replace with matching SVG
![grafik](https://user-images.githubusercontent.com/70113341/121438459-4e369c80-c984-11eb-833f-1923d85ae604.png)

## Alternatives/workarounds

The icon for backup is to discuss see #10896

**Comment by murggel** [comment]
Close in favor of #12276

**Comment by moving-bits** [comment]
> Close in favor of #12276

sorry, had not seen this already existing issue when I stumbled upon the old icons in settings while scanning new settings for open issues
