### ISSUE TITLE
[SVG] Different icon for select-mode

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#10895]
## What function are you missing

Current icon for "select-mode" and "Show as list" (in map mode) is
![grafik](https://user-images.githubusercontent.com/70113341/121432780-6524c100-c97b-11eb-9157-7fac273fcdd5.png)
Even if they are rarely visible, I would like to replace them.

## Suggested solution

For "select-mode" , "invert selection" and "exit select mode"
![grafik](https://user-images.githubusercontent.com/70113341/121432954-a321e500-c97b-11eb-8718-e0da8963c17c.png)

For "Show as list" (in map mode)
![grafik](https://user-images.githubusercontent.com/70113341/121433193-f4ca6f80-c97b-11eb-915a-f4c9ddc2ad86.png)

## Alternatives/workarounds

For "select-mode" , "invert selection" and "exit select mode"
![grafik](https://user-images.githubusercontent.com/70113341/121432978-a87f2f80-c97b-11eb-8e57-22276e5bd4d7.png)

**Comment by murggel** [comment]
Issue is for discussion / feedback.
You can assign it to me.

**Comment by fm-sys** [comment]
> For "Show as list" (in map mode)

For show as list I have added a lists icon for the bottom navigation #10679. As I would call this issue non-urgent, I would like to takeover that part of the issue, as it's probably somehow easier if we don't add the icon twice (so I can avoid rebase sessions ;))

**Comment by murggel** [comment]
Fine for me

**Comment by murggel** [comment]
@fm-sys if you want this issue as tracker for the "show as list"-icon, you can change the title and reopen it or create a new one... (see your comment of June, 10th)
