### ISSUE TITLE
[SVG] Different icon for Backup / Restore

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#10896]
## What function are you missing

We have different icons for the backup / restore function.

In the action bar iof the main screen it is the **disc**-symbol:
![grafik](https://user-images.githubusercontent.com/70113341/121414366-d7d77180-c966-11eb-811c-feea65f74080.png). 
Clicking on it, the backup / restore section of the settings will be opened.

There we have a **refresh**-symbol:
![grafik](https://user-images.githubusercontent.com/70113341/121414577-13723b80-c967-11eb-8954-93c733c78f66.png)

Those two symbols should be the same.

## Suggested solution

The "official" / material.io symbol for backup / restore is the following:
![grafik](https://user-images.githubusercontent.com/70113341/121414660-2be25600-c967-11eb-93b2-6a7aaed9a899.png)

It looks similiar to the icon of the menu-entry "Personal Note". Probably we could find a better icon for that function (pencil)? But then it has the same icon as the menu-entry "Log Visit". But hey, how likely is it, that both are visible the same time in the action bar (it's the 3. and 6. menu-entry)?

## Alternatives/workarounds

![grafik](https://user-images.githubusercontent.com/70113341/121414724-45839d80-c967-11eb-8c42-ab7440ef985a.png)
But this is similar to the icon for "History". In landscape-mode both are visible at the same time (see screenshot above)
![grafik](https://user-images.githubusercontent.com/70113341/121424875-1aeb1200-c972-11eb-98d6-dbd8478240d8.png)

**Comment by murggel** [comment]
Issue is for discussion / feedback.
You can assign it to me.

**Comment by moving-bits** [comment]
suggested icon LGTM

**Comment by Lineflyer** [comment]
I would favor the first proposal ("official" icon of material.io).
