### ISSUE TITLE
Use new text field layout also in authorization dialogs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10893]
We should use the new text field layout (as discussed and implemented for other dialogs) also in the connector authorization dialogs.

**Comment by moving-bits** [comment]
That's the plan - use the new layout for all input fields. But we need to go step by step, as there are still obstacles coming up from time to time, as I had yesterday with `EditText` type not responding to the border color as well as some layout issues.

For the settings activity there's another obstacle: We need to migrate to `AppCompatActivity` and `PreferenceFragment` first, as material design builds upon `AppCompatActivity`, and our old preferences are still using the old activities. See #10579.

**Comment by moving-bits** [comment]
Related to #10763

**Comment by Lineflyer** [comment]
Sorry for opaening the issue as I was not sure, whether this was just overseen or is still work in progress. If you feel this is covered by another issue, feel free to close. :)

**Comment by moving-bits** [comment]
Let's keep this issue open as a reminder and follow-up to #10579.
We'll probably finish all non-settings related parts of #10763 first, can close that issue then, and have this one over here as reminder for the settings' part.
