### ISSUE TITLE
Autofill feature not working (Service login)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10892]
## Bug description 

I am using the "Keepass2Android" app to manage passwords from a keepass file on my android device. The tool provides an "auto complete" for text input fields based on auto-fill feature of Android to allow auto completion of username/password fields in other apps.

Since start of the redesign it does no longer work for filling the user/pass fields of the geocaching services.

### Steps to reproduce the problem

- Install https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=de&gl=US
  (maybe not even needed to see the problem)
- Go to c:geo Menu - Settings - Services - geocaching.com - "Update authentication" (or any other geocaching service login)
- Tap on the user name field to invoke the system context menu, tap on Three-Dot and select "AutoFill"

### Actual result after these steps 

- A toast shows "Content cannot be autofilled"

### Expected result after these steps 

- Autofill should be allowed

## c:geo version 

2021.06.09-NB

## Screenshots 

![grafik](https://user-images.githubusercontent.com/949669/121314310-83e97000-c907-11eb-8c01-ea1b9d21fe28.png)
![grafik](https://user-images.githubusercontent.com/949669/121314340-8c41ab00-c907-11eb-9aa4-a11a1865476c.png)
![grafik](https://user-images.githubusercontent.com/949669/121314375-9368b900-c907-11eb-9f1d-3b64be162261.png)

**Comment by Lineflyer** [comment]
This is how it looks for the Groundspeak app:
![grafik](https://user-images.githubusercontent.com/949669/121314731-f2c6c900-c907-11eb-88a1-9eae42174ba3.png)
![grafik](https://user-images.githubusercontent.com/949669/121314753-f9554080-c907-11eb-9446-304863891118.png)

If K2PA already stored the package name for the user/pass entry (after you once used it from that app) it will either directly offer the correct entry (shot 2) or allow to search it (shot 1):

Shot 1:![grafik](https://user-images.githubusercontent.com/949669/121314912-21dd3a80-c908-11eb-8cd2-b213cbb08961.png)

Shot2:
![grafik](https://user-images.githubusercontent.com/949669/121314967-2dc8fc80-c908-11eb-9515-986562e46443.png)

**Comment by fm-sys** [comment]
Can reproduce the issue. Interesting though: Autofill does still work for EC, only GC seems to be affected

**Comment by Lineflyer** [comment]
Maybe we should also use this opportunity also to think about which field should offer other features like autocomplete or remembering the last inputs (not for the login but e.g. in searches). I guess this can also be defined by certain attributes or parameters we could define/set for individual text fields.

But that's just another issue which came to my mind. If this is feasible we should take it to a dedicated issues (non-urgent, for later optimization).

**Comment by Lineflyer** [comment]
> Can reproduce the issue. Interesting though: Autofill does still work for EC, only GC seems to be affected

For me neither is working.

**Comment by Lineflyer** [comment]
@fm-sys Your PR #12260 seems to perform better.
Now I do not get this error toast anymore but the password field remains empty on first try. Only on second try it fills both username and password correctly from the Keepass2Android app.
But I assume this is just another thing to optimize either in Keepass2Android or an interworking problem with my keyboard app.

Looks good!
