### ISSUE TITLE
New permission - Deactivate sleep mode

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10905]
Today I updated the nightly on one of my test devices (Android 5.0.2).
While installing todays nightly (coming from a nightly version from around 1st June 2021) the system told me, that a new permission "Deactivat sleep mode" (German: Ruhezustand deaktivieren) is needed.

Is that intentional or some unwanted side effect of recent changes?

**Comment by Lineflyer** [comment]
Found it myself:
Its due to the `WAKE_LOCK` permission needed for the background downloader. All fine.
On devices not capable of runtime permissions it seems to be normal behavior, that they notify the user upon installation also regarding such minor permissions.

**Comment by moving-bits** [comment]
Is this something we should document in either our Play Store text or the user guide?

**Comment by fm-sys** [comment]
I think this permission is not really worth mentioning... BWT, at higher Android versions you do not notice added permission at all since Google decided that it is far too uninteresting from a user's point of view
