### ISSUE TITLE
About c:geo is refreshable

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10903]
About c:geo can currently be refreshed, which makes no sense for sure.

Should be enabled for cache details and trackable activity but disabled for about c:geo. 

![Screenshot_20210612_010803_cgeo.geocaching.jpg](https://user-images.githubusercontent.com/64581222/121756752-815f6400-cb1b-11eb-80a1-c709b6abeba7.jpg)

**Comment by bekuno** [comment]
The problem is on all parts of "about c:geo", like "Changes" or "System".
Not only that this makes no sense - you can´t scroll back to the top of the site.
