### ISSUE TITLE
GCvote missing on Premium caches

### ISSUE THREAD

**Issue by Megachip** [cgeo/cgeo#10916]
## Bug description 

Seems GCvote is not updated/loaded on Premium caches

### Steps to reproduce the problem

Update a Premium Cache - or a caches which becomes Premium afterwards

### Actual result after these steps 

Vote is not shown

### Expected result after these steps 

See (an updated version of the) votes 

## c:geo version 

2021.05.21

## Reproducible 

Yes

## System information 

```
Paste your system information here
```

**Comment by Lineflyer** [comment]
Thanks @Megachip for your report. I can however not reproduce your problem. GCVotes are shown to me for premium as well as other caches.

However, as GCVote might be discontinued any time we want to move to another service soon anyway.

If you have more details to reproduce the problem, please kindly let us know.

**Comment by Megachip** [comment]
@Lineflyer It shouldn't matter, but did you test with a non Premium Account?

So what I did:
- Import a bunch of caches (gpx/zip)
- Updated these caches 

=> got ratings for non premium ones, failed on premium ones. Cause GCvote isn't related to geocaching.com it should work without premium, correct?

**Comment by Lineflyer** [comment]
Ok, in that case it could be, that vote retrieval is skipped as probably the whole refresh process is skipped when the user has no access to that cache.. My guess..

**Comment by Megachip** [comment]
> Ok, in that case it could be, that vote retrieval is skipped as probably the whole refresh process is skipped when the user has no access to that cache.. My guess..

So maybe more an feature request than an bug ;)

**Comment by Megachip** [comment]
@Lineflyer now where we checked this internally... a lot of informations are available for basics... like longs, gcvote and so on ... why c:geo didn't fetch/sync these data independently on status of cache/cacher?

**Comment by Lineflyer** [comment]
Let me close here for two reasons:
1. GCVote does not have a feature (its already kind of deprecated)
2. For most users it will not be of any use to retrieve votes for caches, which they are unable to get most relevant other information (like coords and description).
