### ISSUE TITLE
Lab Cache Connector (LCConnector) uses same cache prefix as TerraCachingConnector

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10911]
I realized that the chosen cache prefix code for Lab Caches "LC" is already used by another connector: the TerraCachingConnector (uses TC, CC and LC). Filtering for lab caches will thus also match all TerraCachine-Caches starting with LC (most likely not vice versa since TerraCaching uses a very restricted cache pattern: )

I don't really think this will be a huge problem in practice, but would it be better to choose another prefix for lab caches so they don't clash?

Fopr reference, this is the geocode pattern used by TerraCachingConnector: `(TC|CC|LC)[0-9A-Z]{1,4}`
(means: everything starting with TC, CC or LC with 1-4 letters/digits after)

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/10880#issuecomment-860040362_

**Comment by eddiemuc** [comment]
Let's use AL then. The LC prefix is also already used by the website tool exporting individual Labs as Virtual Caches.

_Originally posted by @jakedot in https://github.com/cgeo/cgeo/issues/10880#issuecomment-860042082_

**Comment by eddiemuc** [comment]
We could maybe differentiate in the filters and only show those for which connectors are configured. Then we would minimize chances for clashing.

_Originally posted by @jakedot in https://github.com/cgeo/cgeo/issues/10880#issuecomment-86

**Comment by eddiemuc** [comment]
> We could maybe differentiate in the filters and only show those for which connectors are configured. Then we would minimize chances for clashing.

There could always be caches in the database for non-active connectors (e.g. stored before service was deactivated or while logged in with another user), so would not do that.

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/10880#issuecomment-860045039_

**Comment by fm-sys** [comment]
OTOH our current LC caches have a _very long_ geocode so they can easily be distinguished. Changing the prefix might break workflows of our users which already have stored LC caches. So we should only change the prefix if we find a way to create shorter geocodes at the same time...

**Comment by eddiemuc** [comment]
> OTOH our current LC caches have a _very long_ geocode so they can easily be distinguished. Changing the prefix might break workflows of our users which already have stored LC caches. So we should only change the prefix if we find a way to create shorter geocodes at the same time...

Users might be able to distinguish this, but our code currently can't. I believe from looking at the relevant regular expressions that the `canHandle` function of `LCConnector` will currently return true for all `TerraCachingConnector` geocodes starting with `LC` (haven't tried it, have no account for `TerraCachingConnector`).

For comparison:
* `LCConnector` handles all geocodes matching this regex: `LC[-\w]+`
* `TerraCachingConnector` handles all geocodes matching this regex: `(TC|CC|LC)[0-9A-Z]{1,4}`

Because `LCConnector` comes before `TerraCachingConnector` in the connector list, LC-starting geocodes will most likely always be handled by `LCConnector` (even if they are TerraCachingConnector codes)

I would really like it if we could somehow stick to unique prefixes per connector. Among other things, SQL-filtering will not work good otherwise. 
But if this is not an option: Would it be valid to include a minimum length of 7 to geocodes handled by `LCConnector`? (`TerraCachingConnector` geocodes have a max length of 6 in total)

**Comment by Lineflyer** [comment]
In case it might be helpful. Here is a sample cache from Terracaching: https://files.droescher.eu/public/Cache_LC1KGB.gpx 

Unfortunately I was unable to download a bunch of cache as this either seems meanwhile to be a premium feature on that platform or I simply did not find out how to do that.

**Comment by jakedot** [comment]
> > OTOH our current LC caches have a _very long_ geocode so they can easily be distinguished. Changing the prefix might break workflows of our users which already have stored LC caches. So we should only change the prefix if we find a way to create shorter geocodes at the same time...
> 
> Users might be able to distinguish this, but our code currently can't.

The long geocode of the Lab Caches would enable us to do a one time conversion of the current LC = Labs Geocodes to AL, without affecting the LC = TerraCaching ones. We would only need to add a one time UPDATE statement.


What this wouldn't solve is that the [Labs2GPX service](https://gcutils.de/lab2gpx/)  [mirsch/labs2gpx#25](https://github.com/mirsch/lab2gpx/issues/25) also uses geocodes like LCZMZD04, and I assume those can't be distinguished that easily (only maybe during GPX import, but as far as I can see there is no distinguishing tag in the GPX saying "I am a Labs2GPX file").

**Comment by eddiemuc** [comment]
> What this wouldn't solve is that the Labs2GPX service (see mirsch/labs2gpx#25) also uses geocodes like LCZMZD04

This is a strong argument to keep LC for lab caches IMHO. We definitely have a lot more users for lab caches and related services than for terracaching. Also only one of their caches types would be affected (I checked, LC are locationless caches at terracaching).

I tried to check usage rates for terracaching connector but they seem not to be listed on our status page. @Lineflyer ? I assume however that the are rather low.

Putting it all together I vote for simply changing K connector to only accept geocodes longer than 7 and be done with it. Would that be ok?

**Comment by Lineflyer** [comment]
> I tried to check usage rates for terracaching connector but they seem not to be listed on our status page. @Lineflyer ? I assume however that the are rather low.

AFAIK we do not support any online functions for Terracaching. Its a pure GPX import based connector/implementation.
The service itself seems rather minor, there are for sure some fans of it also in Germany, but I personally do not know any person using it. Furthermore its an invite/sponsorship system (to enhance quality of caches) which makes it even difficult to get an account.

So lets keep LC for now for adventure labs I would say. Is there any functional impact beside the filtering by origin?

**Comment by bekuno** [comment]
I propose to make the schema unique.
Better now than none. So we do not need work arounds in the future.

**Comment by eddiemuc** [comment]
> So lets keep LC for now for adventure labs I would say. Is there any functional impact beside the filtering by origin?

Yes, I assume that all caches starting with LC will now be handled by LC connector, including the Terra-ones. So I am with @bekuno and would make the Regex unique. Apart from that I would take no action.

**Comment by bekuno** [comment]
> Yes, I assume that all caches starting with LC will now be handled by LC connector, including the Terra-ones. So I am with @bekuno and would make the Regex unique.

I meant to make the code unique, e.g. change it to "AL".

**Comment by fm-sys** [comment]
But please be aware that all other Lab2Gpx services use the "LC" prefix

**Comment by jakedot** [comment]
I think that is not really a problem. The lab2gpx service exports the individual labs as single caches, and our connector integrates the whole adventure into one cache listing. Since those are different, I see no problem with using different prefixes. On the contrary, I think it is a good idea to do so.

**Comment by fm-sys** [comment]
> > I meant to make the code unique, e.g. change it to "AL".
> 
> I would also be in favor of that.

From my side "AL" is ok, but we will need a DB migration routine for "LC" geocodes (with >10 characters) as users will have duplicated caches otherwise if ALCs are stored.

**Comment by moving-bits** [comment]
The following SQL statement should do the trick - please cross-check, I'll prepare an update targeted to `master` if ok:

```
UPDATE cg_caches
SET geocode = "AL" || SUBSTR(geocode, 3)
WHERE SUBSTR(geocode, 1, 2) = "LC"
  AND LENGTH(geocode) > 10
```

same for `cg_attributes`, `cg_caches_lists`, `cg_logCount`, `cg_logs`, `cg_logs_offline`, `cg_spoilers`, `cg_trackables`, `cg_waypoints`

**Comment by Lineflyer** [comment]
The mentioned list is a list of supported online services.
Terracaching is however supported by not with an online connector but only offline (via GPX).
