### ISSUE TITLE
Filter change in sub activity not reflected in calling activity

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10921]
## Bug description 
A filter change in sub activity is not reflected in the filter info line on return to the calling activity

## Reproduce 
- open map
- set a filter
- "show as list"
- change filter
- return to map

### Actual result after these steps 
- filter info line below the action bar still shows the old filter setting

### Expected result after these steps 
- filter info line should be updated to reflect the new filter setting

## Additional context 
as seen today during our meetup

**Comment by jakedot** [comment]
Probably related: #10840
