### ISSUE TITLE
Display mysteries with changed coordinates with enlarged "corrected coordinates" marker

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#10924]
## What function are you missing

Unlike the GC.com website, mystery caches that are solved (i.e. coordinate was updated by user) are still displayed with the default ?-icon on the map. This means that you cannot easily distinguish them from unsolved mysteries.

## Suggested solution

Solved mysteries should have an entire large icon that shows the puzzle tile.

**Comment by fm-sys** [comment]
(...connected to the big icon setting)

**Comment by moving-bits** [comment]
@ztNFny 
While you are working on a new icon set it would be nice if you could provide an extra icon for this (using this icon would be opt-in, like the "big smiley" is)

**Comment by ztNFny** [comment]
I don't understand this FR. Caches with corrected coordinates already have marker_usermodifiedcoords to distinguish them?!
If this is about dot-markers, I've introduced dot_marker_usermodifiedcoords in my branch.

**Comment by dcjkfgdjhd** [comment]
>And how can you tell the actual type? Would you suggest to have a orange "corrected" for multi, a blue "corrected" for mystery and so on?

I guess different colored versions of the puzzle tile would be a cute addition. I suppose creating multiple versions of the same icon with different hues is not too much extra work, so I would appreciate it. 

But it would not be a priority for me. The important thing is that once a mystery has corrected coordinates, the way a cacher interacts with it is different: Now it is a place that it makes sense to actually go to. Before it was just a meaningless marker (due to fake coordinates) that a cacher that looks at the map will almost always just ignore. After solving it, the mystery has turned essentially into a traditional or a multi, thus a "visitable location". This transformation should be immediately visible on the map. 

> I actually disagree with the original statement opening this Issue: They have the marker_usermodifiedcoords and can thus be easily identified.

Sorry, but on a big map full of lots of mystery icons, the tiny "red flag attachment" to the icon is almost invisible. I have this problem almost every day in a city cluttered with mysteries. There is a reason why GC.com also does it on their map. When I see an icon like that, I know that this is essentially a traditional I can visit at any moment as part of some cache tour. Unlike the normal question mark icon, where this is not possible without additional preparation.

**Comment by Lineflyer** [comment]
> (...connected to the big icon setting currently used for the found/DNF smiley)

I always thought its already part of that setting (which I rarely use). Indeed it could be part of it.

**Comment by ztNFny** [comment]
> Before it was just a meaningless marker (due to fake coordinates) that a cacher that looks at the map will almost always just ignore.

By that logic the unsolved mystery should probably be not shown on the map at all (and that's exactly the way that I use offline lists, they don't contain unsolved mysteries).
As I see that option is being implemented in #10429. So with that option you'd only see the solved once -> no need for a seperate icon.

> Sorry, but on a big map full of lots of mystery icons, the tiny "red flag attachment" to the icon is almost invisible.

The low contrast of the current marker_usermodifiedcoords will be solved by #11139 
![image](https://user-images.githubusercontent.com/1258173/127043983-ec1c9d5d-687a-4f20-813c-0e080b64faee.png)

**Comment by dcjkfgdjhd** [comment]
> 
> 
> > (...connected to the big icon setting currently used for the found/DNF smiley)
> 
> I always thought its already part of that setting (which I rarely use). Indeed it could be part of it.

I like to use the large found icon feature as well, yes. For me these things belong together: Show the most relevant information as the main icon. 

When a cache is found, its cache type becomes irrelevant. Thus, show a large found smiley.

When a mystery is solved, it is no longer a mystery. Display a large icon indicating that it is now "visitable".

Etc.

**Comment by dcjkfgdjhd** [comment]
> By that logic the unsolved mystery should probably be not shown on the map at all (and that's exactly the way that I use offline lists, they don't contain unsolved mysteries).
> As I see that option is being implemented in #10429. So with that option you'd only see the solved once -> no need for a seperate icon.

Yes, that would be the mode I would use *most* of the time. While walking around (i.e. when I use c:geo) I *mostly* have no use for unsolved mysteries, so I would hide them completely.

However, sometimes you do need to display mysteries (e.g. for bonus caches) and then it would still be nice to distinguish between "true" (=unsolved) mysteries and not-any-more-mysteries (=solved).

**Comment by ztNFny** [comment]
How about showing the current marker with normal icons then and a full-size for the double size setting?

**Comment by dcjkfgdjhd** [comment]
> 
> 
> How about showing the current marker with normal icons then and a full-size for the double size setting?

You mean making the tiny flag icon full-size (as it currently works for the smiley icon, when the option is activated)? Yes, that would be great.

**Comment by ztNFny** [comment]
> You mean making the tiny flag icon full-size (as it currently works for the smiley icon, when the option is activated)? Yes, that would be great.

Yeah. That way the "double size" would become a "low information density" setting only displaying the "most important" info like found/offline found/corrected and the "normal size" a "high information density" with all the information available. With the new vector icons scaling them is no problem - even though I'll probably create a seperate icon anyway as I prefer to give them some tweaks.

Then the user can choose which amount of info he wants to see. I for one would really hate to lose some of the info available (actually I'd like to add even more, see https://github.com/cgeo/cgeo/issues/8719#issuecomment-755321577

**Comment by murggel** [comment]
> 
> 
> > You mean making the tiny flag icon full-size (as it currently works for the smiley icon, when the option is activated)? Yes, that would be great.
> 
> Yeah. That way the "double size" would become a "low information density" setting only displaying the "most important" info like found/offline found/corrected and the "normal size" a "high information density" with all the information available. With the new vector icons scaling them is no problem - even though I'll probably create a seperate icon anyway as I prefer to give them some tweaks.
> 
> Then the user can choose which amount of info he wants to see. I for one would really hate to lose some of the info available (actually I'd like to add even more, see [#8719 (comment)](https://github.com/cgeo/cgeo/issues/8719#issuecomment-755321577)

How about adding in "double size" mode the "lost" information as marker-icon (so switching the position of the two icons), then the information will not get lost, but then also clutters the map, which is probably not wanted?

**Comment by dcjkfgdjhd** [comment]
Just to make sure, when you say "double size" you mean the currently already existing "large icons for logged caches" feature that makes the found smiley become the full size icon of the cache, correct? 

If yes, then I would love your proposal.

> 
> 
> > You mean making the tiny flag icon full-size (as it currently works for the smiley icon, when the option is activated)? Yes, that would be great.
> 
> Yeah. That way the "double size" would become a "low information density" setting only displaying the "most important" info like found/offline found/corrected and the "normal size" a "high information density" with all the information available. With the new vector icons scaling them is no problem - even though I'll probably create a seperate icon anyway as I prefer to give them some tweaks.
> 
> Then the user can choose which amount of info he wants to see. I for one would really hate to lose some of the info available (actually I'd like to add even more, see [#8719 (comment)](https://github.com/cgeo/cgeo/issues/8719#issuecomment-755321577)

**Comment by dcjkfgdjhd** [comment]
> 
> 
> > > You mean making the tiny flag icon full-size (as it currently works for the smiley icon, when the option is activated)? Yes, that would be great.
> > 
> > 
> > Yeah. That way the "double size" would become a "low information density" setting only displaying the "most important" info like found/offline found/corrected and the "normal size" a "high information density" with all the information available. With the new vector icons scaling them is no problem - even though I'll probably create a seperate icon anyway as I prefer to give them some tweaks.
> > Then the user can choose which amount of info he wants to see. I for one would really hate to lose some of the info available (actually I'd like to add even more, see [#8719 (comment)](https://github.com/cgeo/cgeo/issues/8719#issuecomment-755321577)
> 
> How about adding in "double size" mode the "lost" information as marker-icon (so switching the position of the two icons), then the information will not get lost, but then also clutters the map, which is probably not wanted?

Yes, I thought about that as well, but I personally would prefer the clean, minimalistic version without this. Maybe other people see it differently.

**Comment by ztNFny** [comment]
> Just to make sure, when you say "double size" you mean the currently already existing "large icons for logged caches" feature that makes the found smiley become the full size icon of the cache, correct?

It's called doubleSize in the code I was working on (MapMarkerUtils), but the source is Settings.isBigSmileysEnabled()

**Comment by dcjkfgdjhd** [comment]
> It's called doubleSize in the code I was working on (MapMarkerUtils), but the source is Settings.isBigSmileysEnabled()

👍

**Comment by Lineflyer** [comment]
So when I try to summarize here:

Extend the current `Settings.isBigSmileysEnabled()` to also replace the cache type icon by an enlarged `marker_usermodifiedcoords`. Same principle as for the full size smiley.

That sound reasonable to me.

I would however not include
- any new icon (like the suggested puzzle piece) as we already have one we just need to enlarge
- any further type information by modified colors or similar (in fact if it has this marker its more or less a traditional anyway and you can still tap on it to see more details and the cache type)
-

**Comment by ztNFny** [comment]
>     * any new icon (like the suggested puzzle piece) as we already have one we just need to enlarge

Might be I need a separate one, but I can create it at that point in time. I'd have to do the same for the smileys then anyway.

**Comment by Lineflyer** [comment]
> Might be I need a separate one, but I can create it at that point in time. I'd have to do the same for the smileys then anyway.

Speaking in files: Yes, sure. My sentence just intended to say, that we should not add an additional new content in the icon but just use the same look/content.

**Comment by fm-sys** [comment]
what about using the big-emoji setting for "visited waypoint" as well?


![Screenshot_20211015_105523_cgeo geocaching](https://user-images.githubusercontent.com/64581222/137490539-4f9e7f4f-ca0e-4cec-a303-bc9f9c25c727.png)

Not sure through, weather we should invert the check marker on big emoji style, so that we still maintain our "waypoint" style (colored icon, white background).

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11901#issuecomment-944279431_

**Comment by ztNFny** [comment]
If more icons are to be shown as big smileys we need to think about precedence as there'll be situations where multiple icons could be shown.
So if the extension is wanted i guess we'll need a proper plan what to show when. But this should come from someone actually using that feature...

**Comment by fm-sys** [comment]
A potential problem would be found & corrected coordinates. But I agree found should win. Can't imagine of any more complex problems currently...

**Comment by Lineflyer** [comment]
Same here:
Found should have priority over corrected coords.

Regarding the representation:
The issue title states "large puzzle tile icon". I would however propose not to use any different icon than those also used in small size (i.e. the white/blue arrow or whatever is the final one after beta).

**Comment by fm-sys** [comment]
Proposal:

![grafik](https://user-images.githubusercontent.com/64581222/141535069-2ccf9399-11f7-4bf5-aef8-5696b9fe0582.png)

Should this be targeted to `release` or `master`?

**Comment by bekuno** [comment]
> Should this be targeted to `release` or `master`?

Of cause to release, as this is our "new icon design" release.

**Comment by bekuno** [comment]
> 
> 
> Proposal:
> 
> ![grafik](https://user-images.githubusercontent.com/64581222/141535069-2ccf9399-11f7-4bf5-aef8-5696b9fe0582.png)

Such a big icon would good fit to the discussion "final flag" vs. "modified coords".
Then in both situation a big flag shows the cache box place.
(Or at least the blue flag the next point on the way to the cache box e.g. for for multi caches)

I would instead of the simplified flag form use the rounded flag form as for waypoints. 

![InkedScreenshot_20211021-232025_cgeo_LI](https://user-images.githubusercontent.com/32555742/138359825-0b8801e8-b353-48ee-9a90-8e8a7595fcb4.jpg)

**Comment by fm-sys** [comment]
> Such a big icon would good fit to the discussion "final flag" vs. "modified coords".

Actually, it's one of the best arguments to stay with the blue icon for corrected coordinates and don't switch the icons. Otherwise, users will no longer be able to distinguish whether the item is a waypoint or cache...

**Comment by dcjkfgdjhd** [comment]
> Proposal:
> 
> ![grafik](https://user-images.githubusercontent.com/64581222/141535069-2ccf9399-11f7-4bf5-aef8-5696b9fe0582.png)

Looks great to me!

**Comment by ztNFny** [comment]
implemented by #12083
