### ISSUE TITLE
Adding current location as start point to route

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#10923]
## What function are you missing

Maybe I simply don't understand fully the way this currently works, so feel free to correct me, if this is unnecesary:

Typically, when creating a new route, I obviously want the route to start at my current location. But there seems to be no way of achieving this. The route always begins at the first selected cache and only routes from the first to the second, to the third, etc.

If I want to route from my current location, I always have to create a user defined cache in my current place first.

## Suggested solution

I can see two approaches: Either, the route always begins at the current location. Or, one could long press the "blue arrow" icon (marking where you are on the map) to add the current location as a point into the route. I guess solution two could also be useful if you want to plan a circular route (just add the current location both as the first *and* the last route point).

**Comment by Lineflyer** [comment]
Just select in the individual route menu, that you want to navigate from your position to the route start. 
The route will still start at the first point then, but the routed navigation line will be shown from your position to the first route point. Essentially what you want.  

The advantage is also that you can (after reaching a routing point) you can long click to remove it from the route and it will automatically then navigate you to the new/next routing point.

**Comment by dcjkfgdjhd** [comment]
> Just select in the individual route menu, that you want to navigate from your position to the route start.
> The route will still start at the first point then, but the routed navigation line will be shown from your position to the first route point. Essentially what you want.

Ah, thanks, yes, I can work with that. I did not know that feature.

> The advantage is also that you can (after reaching a routing point) you can long click to remove it from the route and it will automatically then navigate you to the new/next routing point.

Actually, that is usually *not* what I want because I want to cycle along the route (carefully crafted using user generated caches as intermediate points), not be routed on the fastest way.

But, I can still live with the solution you propose: I just use fastest way routing till the first point using the option you suggested, and then disable routing and drive along the pre-fixed route.

**Comment by moving-bits** [comment]
> 
> 
> > Just select in the individual route menu, that you want to navigate from your position to the route start.
> > The route will still start at the first point then, but the routed navigation line will be shown from your position to the first route point. Essentially what you want.
> 
> Ah, thanks, yes, I can work with that. I did not know that feature.

Alternatively you can select your first cache as target for navigation manually.

> > The advantage is also that you can (after reaching a routing point) you can long click to remove it from the route and it will automatically then navigate you to the new/next routing point.
> 
> Actually, that is usually _not_ what I want because I want to cycle along the route (carefully crafted using user generated caches as intermediate points), not be routed on the fastest way.

When calculating the route from current position to the first point of your individual route c:geo uses the last routing mode you have selected (e. g. "bike" or "walk"), so it should stay consistent.


Rationale behind this behavior is that you can plan as many individual routes as you like, and save and restore them. And while planning, you see the length of that route itself (without the way from your current position the start of the route). c:geo cannot know how you want to get to your first cache, and whether this way is part of your planned tour or not. So you have the choice by either adding an UDC as current location and make it part of the route, or by selecting "set as target automatically" in map quick settings.
