### ISSUE TITLE
Geocaching.com: watchlist counter no longer valid (always returns 2)

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10939]
It is my impression that the watchlist count for geocaching.com is no longer valid. It always seems to return 2. 
I assume this is the result of a website change because the watch count is no longer displayed behind the "Watch" toggle:

![image](https://user-images.githubusercontent.com/6909759/122215405-77d35480-ceab-11eb-992e-3f78fd12bb4a.png)

## Bug description 
When I open a geocaching.com cache stored on my device  with a watchlist count > 0 and I refresh this cache, the watchlist count returned is always 2.

Also, JUnit test `cgeo.geocaching.connector.gc.GCParserTest.testOnlineWatchCount` fails with `Expecting: <2> to be greater than <50>`

### Steps to reproduce the problem
* open c:geo
* open any previously stored geocaching.com cache where you know that the watchlist count is well bigger than 2 (Note: it seems that this is currently not verifyable on geocaching.com) and where a watchlist count well bigger than 2 is stored
* refresh the cache

### Actual result after these steps 
The watchlist count is 2

Note: if you start with a cache whose watchlist count is 0 or 1, the watchlist count will also be 2 after refresh

### Expected result after these steps 
The watchlist count reflects the real watchlist count

## c:geo version 
Current Release: 2021-05-20
current master: 2021-06-15

## Reproducible 
Yes, always

## Additional context 
Checked actual source of a geocaching.com html page. It seems the `2` is parsed by watchlist count regular expression because this regex scans for the term "watchlist.aspx" and returns the next expression within paremthesis behind it. It turns out, right now this is a javascript expression `(2)` some lines after `watchlist.aspx` .

## Additional TODO
Re-enable the GC watchcount test after fixing this issue. The test got disabled with PR #10945 to not distract with all builds failing due to the website being broken.

**Comment by eddiemuc** [comment]
I have no fix for this currently because I can't find a way to parse the watchlist count from another place on the web page right now. Maybe someone else has an idea?
I hope we don't have to remove this feature...

**Comment by eddiemuc** [comment]
See https://forums.geocaching.com/GC/index.php?/topic/362910-number-of-watchers-disappeared/&tab=comments#comment-5895198 
Maybe its a temporary bug

**Comment by bekuno** [comment]
https://forums.geocaching.com/GC/index.php?/topic/362910-number-of-watchers-disappeared/&do=findComment&comment=5895429
cite: "Thank you for reporting this issue. I have passed this along to the Engineering teams. "

**Comment by balu2003** [comment]
As already described there is a problem on the gc website with the watch counter:
[https://forums.geocaching.com/GC/index.php?/topic/362910-number-of-watchers-disappeared-more-watchlist-bugs/](https://forums.geocaching.com/GC/index.php?/topic/362910-number-of-watchers-disappeared-more-watchlist-bugs/)
Therefore, the cgeo parser cannot parse the non-existent watch counter.

There is another problem that affects the way a listing (cache) can be added or removed from a watchlist.
see: 
[https://github.com/cgeo/cgeo/issues/10940](https://github.com/cgeo/cgeo/issues/10940)

**Comment by balu2003** [comment]
the watch counter is back :-)
But they have a lost a space  between Watch|Stop Watching and the Counter eg.
`<span class="remove-from-watchlist" data-gcRefCode="GC9CBP6" data-href="/my/watchlist.aspx">Stop Watching(3)</span>`
Now cgeo could parse the watchcounter well, but although I am on the watchlist, cgeo does not detect that I am.
"This cache is not on your watchlist)

**Comment by balu2003** [comment]
They have changed the way to add/remove from watchlist see #10940
The result is, that removing from watchlist with the link in a "watch list email" like
`http://www.geocaching.com/my/watchlist.aspx?id=7472397&DS=1&ACTION=REM`
no longer works. 
The webseite uses a JSON construct to add/remove and this construct can not used in the email (IMHO).
So they could change the website again, if the cgeo dev change the parser to detect a keyword in the html like "remove-from-watchlist", it could then fail again.
I would wait until HQ has solved the email "Remove this from my watchist" problem.

**Comment by UniQP** [comment]
@balu2003 If they change the website again, we will just adapt the parser again. Reverting a previous change is very easy. So I see no benefit in waiting (at least for the website parsing).
