### ISSUE TITLE
MapQuickSettings filters do not work when using "Show on Map" action from stored list view

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10946]
## Bug description 
When map viewer is opened from a stored list using the "Show on map" action in actionbar,, then the filter settings in map quick settings are not applied. For example, when own/found should not be shown according to map quick settings, they are still shown. Also changing these settings has no effect

### Steps to reproduce the problem
* Open any "Stored" list which contains both found and not-found caches
* Click "Show on map" -> map viewer opens with caches of the selected list displayed
* Open "Map Quick Settings". If set, then remove checkmark on "Own/found caches" 

### Actual result after these steps 
* All caches are still shown on the map (both found and non-found)
* further checking and unchecking of the "Own/found cache" checkmark has no effect

### Expected result after these steps 
* Only the non-found caches should be shown afterward
* when checking the "Own/found cache" checkmark afterwards then the "found"-caches should be shown again

## c:geo version 
Release: 2021.05.20

## Reproducible 
Yes, always

## System information 
unrelated

## Additional context 
* In current `master `branch the problem only seems to appear in Mapsforge map, not in Google map
* I think the cause is that a cache list given to the map activity is not included in the filtering processes.

**Comment by rsudev** [comment]
I would call it a bug if in this case the filtering is applied up-front...
When I show a list, I want to see everything that's on the list (that is at least my current expectation)
If I show a cache, I want to see the cache (even if I have found it and my map settings exclude founds from display...)

**Comment by eddiemuc** [comment]
> When I show a list, I want to see everything that's on the list (that is at least my current expectation)

True, but I would expect that when I apply other filters in the map viewer to this list then this would further "filter down" the list . (list viewer has this behaviour: when a list of caches is passed from map and a filter is applied there, then the list from the map is further "filtered down")

**Comment by rsudev** [comment]
That is true. But then the 'Quick Settings' perhaps should reflect the right context and not the 'global' (or live map?) filter settings.
To complicate things further, my expectation would be (as I designed it that way initially), that my 'normal' filter settings for the map (exclude found etc.) still apply if I activate the 'live mode' in addition (but only for that part).

**Comment by eddiemuc** [comment]
@rsudev you are right, I forgot that in current release the "map quick filter settings" are at the same time "global filter settings". So I guess in this context it should stay as is.

However, for the next release (new filter system) my plan is to "convert" the map quick settings so they would ONLY apply to the map viewer (a pure "viewing filter" which is then applied additionally to any other filter). In such a context, would you agree that this "pure view filter" should also filter the caches taken over from a cache list into the map?

**Comment by balu2003** [comment]
I would expect to see all caches in the map that I see in the list (I could filter  the list, if I want) (see what you get)

The user story starts with the list, he can filter this list with list specific criterias. And then he would map exactly this list.
If there would be an additional map filter, the user would wonder why not all caches from the list  are displayed on the map.

If the user story starts with the map, then the user wants to filter the caches on the map because he uses the map as an "explorer" for caches.

**Comment by eddiemuc** [comment]
If this is the wanted use case (not by myself, but I accept the use case of the community of course) then I see two additional points:
* The map quick settings filter should be disabled in this case, because if the user sets it it has no effect - and this might seem strange too
* As soon as I turn on "live map" in above situation, the map quick filter is immediately applied currently and the caches of the original list are filtered as well. Shouldn't this be changed then too?

Should I close this issue then?

**Comment by balu2003** [comment]
So I'm a single user and can't represent the community :-)

I read the description of the issue again and tested it with cgeo2021.05.20. And I have probably misunderstood something in your description: Qicksetting contains other filters as in the filter of the "stored list".
In the global settings I have chosen that own / found caches are not displayed.
I go to the live map and have  activated show circles in the "Quick Settings". I see now red circles (but they are lager than 161meters)
Now I switch to the "Stored" list and select a list. This list contains found and not found caches. Now I tap on  "Show on Map". I still see the circles. If I go to Quick Settings and deactivate the circles, no circles are displayed. (and vice versa)
This behavior seems to me to be correct.

In the Qucik Settings of the Live Map, I can still show and hide my own / found caches.
But this is not possible in the Quicksettings at Stored-> Map. Here the quicksetting "own / found caches" has no effect.
his behavior does NOT seem right to me.

The behavior of Quicksettings should be the same, this means, it should work in Map Or Stored>Map by the same way

```
QuickSetting
              own/found |  Disabled | circles, Parking
                        |  Archived | Waypoints
Map           y         |  y        | y 
Stored>Map    n         |  n        | y  

y = works / change view
n = doesnt work
```

**Comment by eddiemuc** [comment]
@balu2003  found out something Interesting: although the "cache" filters (own/found etc) do not work in Stored-> Map case, the "waypoint" filters (Parking etc) seem to work.

"Circles" is not a filter setting, I think it is handled differently anyway.

**Comment by rsudev** [comment]
Waypoint filters have been added recently and therefore likely do not tie in to the concept mentioned above.
I forgot to mention, that I talked solely about the mapsforge map, as the google map was just 'upgraded' to v2 in a kind of emergency and therefore doesn't implement the concepts the current mapsforge implementation was designed for (so I am not sure to which map type the above applies)

To elaborate on the use cases this design is meant for:
you are going for a nice multi cache and doing some others on the way
- you open the map from the cache and see the cache and all waypoints
- you enable the live mode shortly to fill the map with other caches for the region you have temporarily stored.
From my point of view it is clear that in such a case I want the cache I opened originally to stay on the map, regardless of any type filters and also the waypoints to stay, regardless of any waypoint limits.

you have select a set of caches you want to do onto a list. Maybe some interesting traditionals, a short multi, one or two solved mysteries.
- you open the map from the list
- you enable the live mode shortly to fill the map with other caches for the region you have temporarily stored.
From my perspective I do not want any of the selected caches to vanish, even if I do not want to see additional multies or mysteries, which I would not go for in this context.

I am by no means 'the community' and, frankly, have no idea about their desires (I guess most users just drop in on the live map and that's it), but for such (and similar) use cases the 'NewMap' has been designed.

When that should change, I would pity it, but as I currently do not have time to implement anything, it is up to the currently active devs to decide the future direction, no problem. But as it is a more fundamental change as it looks on the surface, it would probably be wise to take a look at all places that need to get touched to support this.

**Comment by balu2003** [comment]
If there are found or own caches in a list, they will be shown even if the global setting is "show no own/found", that is OK and wished.
In my opinion there is **no problem with the released implementation**. If I were an developer I would change nothing 
before a concept is available and discussed that would involve as many users as possible (beta test, forum, bug reports)
I think the most users haven't detect that "issue", are there reports from users?
And since you all work on a voluntary basis, you have enough work to do with the website changes from the HQ.
However, if you just wanted to discuss ideas / concepts first, then I would also have a few suggestions.
I would remove the label bug and add a label like "Feedback required"

**Comment by eddiemuc** [comment]
> I would remove the label bug and add a label like "Feedback required"

Done

**Comment by eddiemuc** [comment]
The original issue is not relevant any more. I skimmed through discussion, and I don't think there's nothing left open (and no mre feedback since some time). Thus I will close this issue. Feel free to reopen if I missed something.
