### ISSUE TITLE
Emojis in emoji selector are way too small

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10948]
As the title describes, the emojis in the emoji selector are displayed way too small...

![grafik](https://user-images.githubusercontent.com/64581222/122549273-99ab1380-d032-11eb-9d80-a2e8a86245d3.png)

**Comment by fm-sys** [comment]
Oh, and there's another issue which should be fixed on the go: The "reset cache icon" button is not yet displayed in our generic "icon button" style

**Comment by murggel** [comment]
I guess that is a  impact of the ImageButton-change.
Will have a look on that...

**Comment by fm-sys** [comment]
No worry, I had noticed the bug already weeks ago but just forgot to report it... Thanks for looking into it!

**Comment by murggel** [comment]
Looked at it but I guess I need some help to fix the emoji size. The size is calculated from the drawable ic_menu_filter (which is now a svg). But if I use a different one which is still a png, only the red circle emoji gets bigger, the other ones stays small 🤔

**Comment by murggel** [comment]
> Oh, and there's another issue which should be fixed on the go: The "reset cache icon" button is not yet displayed in our generic "icon button" style

Can you provide a screenshot? I don't know what you mean.

**Comment by moving-bits** [comment]
I guess that the two buttons marked in red should get a button border as well:

![image](https://user-images.githubusercontent.com/3754370/122635040-d41fb980-d0e1-11eb-9c2b-c62863a95b8f.png)

You get to this dialog from cache detail page => menu, extended, set cache symbol

**Comment by murggel** [comment]
Do we have / want borders for the buttons in the title bar? 
How is it in other dialogs? 
But probably it make sense for the icons to make the user aware that its clickable...

**Comment by fm-sys** [comment]
>Do we have / want borders for the buttons in the title bar? 

Yes, was like that before our redesign

>But probably it make sense for the icons to make the user aware that its clickable

Definitely, otherwise users would wonder why there are such strange icons in the titlebar, but would never expect that they are clickable...

**Comment by eddiemuc** [comment]
> Looked at it but I guess I need some help to fix the emoji size. The size is calculated from the drawable ic_menu_filter (which is now a svg). But if I use a different one which is still a png, only the red circle emoji gets bigger, the other ones stays small 🤔
> 
> 

I have no access to code currently, but I remember dimly that the drawable was only user to get a reference size for the emoji icons.

I created recently a method in emojiUtils to get an emoji drawable for a size given by a parameter. Maybe this could be used here as well, and the wanted icon size could be passed there as parameter (e.g. 24dp?)

**Comment by eddiemuc** [comment]
Method is
`EmojiUtils.getEmojiDrawable(final int wantedSize, final int emoji)`

`wantedSize` is expected in pixels, calculate pixels from dp using `ViewUtils.dpToPixel()`

**Comment by murggel** [comment]
Have a solution for the buttons in the title bar -> PR will follow (but probably it makes sense to refactor the creation of the dialog and title bar to avoid a separat layout-file? But then I am probably not the right person🤔)

**Comment by fm-sys** [comment]
> but probably it makes sense to refactor the creation of the dialog and title bar to avoid a separat layout-file?

The title bar layout is used at several places in c:geo (and for all of them the button style is missing). So I would call this title layout a common component, which should be kept separate...

AFAIK, it is currently only used for the "create UDC" and "select Emoji" dialog currently.

**Comment by murggel** [comment]
> > but probably it makes sense to refactor the creation of the dialog and title bar to avoid a separat layout-file?
> 
> The title bar layout is used at several places in c:geo (and for all of them the button style is missing). So I would call this title layout a common component, which should be kept separate...
> 
> AFAIK, it is currently only used for the "create UDC" and "select Emoji" dialog currently.

Yes, that's what I thought, to have the same style of the titlebar. The changes I made is only effecting those dialogs, where it make sense, because the cache-type-icon is shown on a button.

But for "OK" and "Cancel" I don't think, a border for those buttons looks better than the normal borderless-style

**Comment by murggel** [comment]
Maybe the standard is instead of icons in the titlebar buttons at the bottom of a dialog?

**Comment by fm-sys** [comment]
> But for "OK" and "Cancel" I don't think, a border for those buttons looks better than the normal borderless-style, or is the style with border the "normal" one for titlebar?

Yes, definitely. For this, we could only think about using an AndroidX toolbar component instead, but this is definitely a completely different topic ;-)

**Comment by fm-sys** [comment]
There were also discussions refactoring the edit note to a full-screen fragment, etc, etc... For now, we can keep it as it is.

**Comment by murggel** [comment]
PR #10994 to fix emoji size.

Margins are still not ok and for landscape-mode the number of columns is too big


![image](https://user-images.githubusercontent.com/70113341/123003137-0e73aa00-d3b3-11eb-95f9-5ce6ad2cb42b.png)
