### ISSUE TITLE
New filter: removing old cache list filter: what is left to do before this step?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10952]
This issue is about making the new filter system the primary and only filtering system for cache lists. This includes:
* Removing completely the old filter system and associated underlying classes (this is a lot!)
* Remove "experimental" mark from new system

Before we do this, I want to ask around what is still missing in the new filter system to go ahead and do this. Which filters must be added, which important issues must be addressed etc?

**Comment by Lineflyer** [comment]
I did not 1:1 compare the old list filter and the new filter, but you for sure did this.
Anything which is explicitly not covered by the new filter, or anything still on your ToDo?

**Comment by eddiemuc** [comment]
This was meant as a call to see what is really missing, not so much to find the leftover differences between old and new system. And if no one knows a specific filter, it might not be really needed.

But let's see what is still missing. If I did not miss anything it is:
* Found in last 30 days
* Present in different origins with different status (this one would be tricky to implement, I really want to be sure of it's value before that)
* Has vote
* Has trackables
* Has not been found yet
* Saved within/before last 8 hours/24 hours/7 days/30 days
* Has own vote
* Found but has no own vote
* Has changed coordinates (note: this is different from "solved mystery")
* Has user-defined waypoints

I am against implementing all these things just because they exist in the old filter. I would rather like to know which ones are really needed and focus efforts on these.

**Comment by moving-bits** [comment]
I'm currently using this filter a lot:

> Saved within/before last 8 hours/24 hours/7 days/30 days

Reasoning behind that is to find data I need to check / update before going on a tour. (But it's only sort of a workaround, because if I myself change something in a cache (e. g.: user note), the "last save date" gets updated as well.)
But more important: If we are going to persist data we get from the live map (#10927), especially info about availability of a cache, my use case would be covered and I would not need that filter any longer.

**Comment by moving-bits** [comment]
One strategy for those "more exotic" filters could be to leave them out intentionally in a first version and wait for user feedback if any of those filters are actually missed.

**Comment by eddiemuc** [comment]
> One strategy for those "more exotic" filters could be to leave them out intentionally in a first version and wait for user feedback if any of those filters are actually missed.

That would be my personal favorite :-)

If this is considered to be too harsh by the majority, however, I got a second idea overnight: we could explicitly leave the "legacy" filter framework in but reduce it to those "exotic filters". And maybe add some note that this will be removed after one/two releases and users should contact us if they need some of them.

**Comment by moving-bits** [comment]
> we could explicitly leave the "legacy" filter framework in but reduce it to those "exotic filters". And maybe add some note that this will be removed after one/two releases and users should contact us if they need some of them.

In this case I would swap the positions in cache list: Make the new filter system the default you get by tapping the filter icon, and move the legacy filter to the menu (and name it "legacy filter").

**Comment by Lineflyer** [comment]
I tried to remember and crawl through support tickets to see, where user have asked for help and I helped them with a matching filter:

> * Has trackables

That is asked sometimes, as there are users with pretty strong focus on TBs and they want to filter lists by that.

> * Saved within/before last 8 hours/24 hours/7 days/30 days

Users often ask how to best do selective refreshing, to only refresh data of caches with a specific age. 
That is, what I recommended to them.

> * Found but has no own vote

I personally use that sometimes to catch up forgotten votings
Note: Does not need to be this dpecific. It could also be self constructed from "Is Found" AND "NOT has own vote"

**Comment by Lineflyer** [comment]
> If this is considered to be too harsh by the majority, however, I got a second idea overnight: we could explicitly leave the "legacy" filter framework in but reduce it to those "exotic filters". And maybe add some note that this will be removed after one/two releases and users should contact us if they need some of them.

Not sure, what sides effects might occur if users start using legacy and new filter in conjunction.
I would be more with the idea to just remove the old filter and we will get feedback regarding the new filters.

BTW: Anyone willing to add the new filter to the users manual. Not sure if I find time for that.
I will open an issue in the guide repo .

**Comment by eddiemuc** [comment]
> 
> > * Has trackables
> 
> That is asked sometimes, as there are users with pretty strong focus on TBs and they want to filter lists by that.
> 
> > * Found but has no own vote
> 
> I personally use that sometimes to catch up forgotten votings
> Note: Does not need to be this dpecific. It could also be self constructed from "Is Found" AND "NOT has own vote"
> 

Sounds reasonable and could be solved by adding two more lines to the Status filter:
* With Trackable a (All/Yes/No)
* With Own Vote (All/Yes/No)

> > * Saved within/before last 8 hours/24 hours/7 days/30 days
> 
> Users often ask how to best do selective refreshing, to only refresh data of caches with a specific age. 
> That is, what I recommended to them.
> 

Well, we could move out the simple "Stored (All/Yes/No)" from status filter to a new. Own filter "Stored State" where one could filter for a "Stored" date/timespan (like e.g. for "Placed" filter) and negation option 

But imho, this is kind of a misuse of filter framework for an unrelated other issue: users should be able to have such an option directly in the refresh function, not indirectly via filtering a list first. Remember that since we only have one global filter (!), a user wanting to refresh e.g. all caches older than 7 days then has to do many steps:
* Create/modify his current filter to restrict to caches stored >7 days ago
* Load completely all caches on that list into memory (!)
* Do the refresh
* Create/modify the filter again to remove the restriction "Stored > 7 days ago"

**Comment by Lineflyer** [comment]
>  imho, this is kind of a misuse of filter framework for an unrelated other issue: users should be able to have such an option directly in the refresh function, not indirectly via filtering a list first

That is probably worth a thought....and better than a filter solution.
We could indeed implement something in addition to "Refresh all" called "Refresh specific" with a dialog behind, where the user can select which caches shall be refreshed providing a range of days or alike.

**Comment by MagpieFourtyTwo** [comment]
> Saved within/before last 8 hours/24 hours/7 days/30 days

Did not know about this filter yet, but it sounds like a possibility to filter out these caches, an imported PQ has *added* to the offline DB ...

Use case: I often struggle to find "newly" imported caches, which have to be updated in order to get a proper Fav count etc..
Alternate solution could be to get a filter like "Favorite count inconclusive" ... of "Offline data incomplete" or alike ...?

**Comment by eddiemuc** [comment]
See PR #11043 which adds the requested filters. This leaves the following:

* Found in last 30 days
* Present in different origins with different status (this one would be tricky to implement, I really want to be sure of it's value before that)
* Has not been found yet
* Has changed coordinates (note: this is different from "solved mystery")
* Has user-defined waypoints

**Comment by eddiemuc** [comment]
Are those still needed?

**Comment by Lineflyer** [comment]
Lets leave it like that for now and see if users out there claim something missing in beta or production.
For the "Stored last 30 days" we should (as discussed) rather file a feature request for a customizable refresh option (like: Refresh all, Refresh older than xx days)

**Comment by moving-bits** [comment]
> Lets leave it like that for now and see if users out there claim something missing in beta or production.

agreed

> For the "Stored last 30 days" we should (as discussed) rather file a feature request for a customizable refresh option (like: Refresh all, Refresh older than xx days)

and/or use "live data" from live map and persist that updated info (both would be useful)

**Comment by MagpieFourtyTwo** [comment]
> Present in different origins with different status (this one would be tricky to implement, I really want to be sure of it's value before that)

Don't even get the benefit of this filter ... what can these "different origins" be?
And how are they determined?

**Comment by eddiemuc** [comment]
> > Present in different origins with different status (this one would be tricky to implement, I really want to be sure of it's value before that)
> 
> Don't even get the benefit of this filter ... what can these "different origins" be?
> And how are they determined?

I didn't know this filter too before diving into the topic.
"Origin" means service/connector, e.g. GC.com or oc. Basically this filter helps you find caches with same name which exist in your local db on both GC.com and oc but one is e.g. found and the other not found. So I guess it was used to check whether a user logged a cache as found on one platform but forgot to do so on the other.

Again: I have no good idea to integrate sth like this consistently in the new filter framework, only the SQL part is easy. So I would only do this if really needed, and maybe as a special "side functionality" to the filter and not as part of it.

**Comment by eddiemuc** [comment]
> For the "Stored last 30 days" we should (as discussed) rather file a feature request for a customizable refresh option (like: Refresh all, Refresh older than xx days)

Well. I added a "stored since" filter for that now (was not so hard), so this shouldn't be the problem.

**Comment by murggel** [comment]
> See PR #11043 which adds the requested filters. This leaves the following:
> ...
> * Has not been found yet
> ...

I guess this one is used to find caches where the FTF is not yet assigned. So interesting for FTF-hunters - don't know if we want to support that 😉

**Comment by eddiemuc** [comment]
> > See PR #11043 which adds the requested filters. This leaves the following:
> > ...
> > 
> > * Has not been found yet
> >   ...
> 
> I guess this one is used to find caches where the FTF is not yet assigned. So interesting for FTF-hunters - don't know if we want to support that 😉

True, but I find this pretty meaningless since search can only be done on locally stored caches (and against the state previously stored). Because gc.com API does not support "find count" as a search parameter (oc, on the other hand, does)

But now that I think of it, this can be achivede with the "Logs count" filter, so it can be removed from the list above

**Comment by MagpieFourtyTwo** [comment]
> Basically this filter helps you find caches with same name

As name is not unique, it should/may perhaps compare coords ...?

**Comment by MagpieFourtyTwo** [comment]
Which would even make sense, at least on map, as you may get mutually overlapping icons, thus just see one of both ...?
However - interesting. If I once will completely change to e. g. extremcaching or opencaching ... ;)

**Comment by eddiemuc** [comment]
> > Basically this filter helps you find caches with same name
> 
> As name is not unique, it should/may perhaps compare coords ...?

I checked in code, and I was not precise enough. This filter will look for caches where another caches exist with all of the following conditions fulfilled:
* different found status
* Different origin (means: different connector)
* Distance closer than 20m
* Similar name (to be precise: levishtan distance < 3)

**Comment by Lineflyer** [comment]
I think anyway, that this filter is very special and probably only rarely used.
There is also a Java tool available providing such comparison with automated logging on OC side (thats what I use).
I think we can for now skip this filter.

**Comment by eddiemuc** [comment]
This issue will be closed with PR #11087
