### ISSUE TITLE
Add setting: radio buttons vanishing

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10953]
## Bug description 
Radio buttons in Settings => System => View Settings => Edit => Add dialog vanish as soon as you enter the "name" input field.

### Steps to reproduce the problem
- Go to settings, system, view settings
- activate edit mode
- push "add" button
- enter the "name" input field

### Actual result after these steps 
Radio button section, which is clearly visible until entering the name field, vanishes partly.

### Expected result after these steps 
All radio buttons from the radio group should still be accessible.

## c:geo version 
Current master

## Reproducible 
yes

## Screenshots 
![image](https://user-images.githubusercontent.com/3754370/122635181-be5ec400-d0e2-11eb-83ef-5dd2f13272d9.png).![image](https://user-images.githubusercontent.com/3754370/122635188-c9b1ef80-d0e2-11eb-9961-1d32c2373356.png)

## Additional context 
I've stumbled upon this on trying to migrate this dialog to `TextInputLayout`. In this case, the radio group vanishes completely. Only the radio group's heading (which is a separate TextView) stays visible.

## Idea
May it be that the dialog gets truncated by the keyboard? Because when I close the keyboard (by pressing the back button), the dialog gets extended and the missing entries are visible again. I'll look into this direction...

**Comment by fm-sys** [comment]
Yes, dialogs have a quite large minimum margin, and if the screen area gets to small the content gets truncated.

To solve this, we should make the content scrollable.

**Comment by moving-bits** [comment]
I've put a `ScrollView` around it. Works, but is still a bit ugly. Is there a way to reduce that margin, or to choose a smaller keyboard layout?

![image](https://user-images.githubusercontent.com/3754370/122635605-2f9f7680-d0e5-11eb-96b5-a72d260d61e6.png)
