### ISSUE TITLE
Tapping outside PN edit windows discards changes

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10965]
## Bug description 

Not sure if this is a changed behavior (e.g. caused by design changes) or was there ever since. However today I had a very hard day using the personal note for a cache.
In bright sunlight I managed a few times while adding some content to the note, to accidentally touch outside of the PN edit box, which closes it and discards the changes. 
I could swear, this never happened before. Maybe the edit window was larger or the tap outside was not enabled?

### Steps to reproduce the problem

- Tap on pencil icon on cache description page to start editing the PN
- Enter some text
- Tap outside of the input window

### Actual result after these steps 

Changes are discarded, window closes

### Expected result after these steps 

Not sure..
Asking the user whether he really wants to close and discard sounds intrusive. Maybe we should either save the changes or simply ignore a tap outside the window?

## c:geo version 

2021.06.19-NB

## Reproducible 

Yes

**Comment by fm-sys** [comment]
> Maybe we should either save the changes or simply ignore a tap outside the window?

I would vote for simply deactivating the "cancelable" flag (-> ignore clicks outside). All these "do you really want to?" dialogs in c:geo are IMHO rather annoying... :-/

**Comment by moving-bits** [comment]
Just did a quick retest against the currently released version (2021.05.20): It's the same behavior over there, if you tap outside the popup, the popup gets discarded (as with any other popup as well, e. g. the cache popup when opening it from the map).

**Comment by Lineflyer** [comment]
Thanks for crosschecking...then it was only the bright sun which made me first time run into this problem as I simply did not see, that the window has not the full screen width. 
Still removing the cancelable flag would maybe good...as users might have entered a lot of info when accidentally clicking outside.

**Comment by MagpieFourtyTwo** [comment]
While I wonder why it does not use the entire width, anyway ...
