### ISSUE TITLE
why is only one build instance active?

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10973]
## Bug description 
Only one build instance seems to be active currently, which leads to long build queues in times of higher traffic. Is there any specific reason for not enabling more instances?

![image](https://user-images.githubusercontent.com/3754370/122686191-4393c700-d210-11eb-8048-14e9875caf07.png)

@mucek4
Can you have a look at it?

**Comment by Lineflyer** [comment]
Some of the others are old/no longer in use.
But the two others normally online seem to be down right now. AFAIK @mucek4 is on vacation. Might take a while :(

**Comment by fm-sys** [comment]
Maybe he has temporary shut down some external slaves while being on vacation...?

**Comment by mucek4** [comment]
No. Sorry. Computer was phisically turned off and I didn't noticed. Should be back up.

**Comment by moving-bits** [comment]
@mucek4 
Can you have a look again?
According to [CI status](https://ci.cgeo.org/) again only cgeo-1 is active, and cgeo-2 to cgeo-5 are offline.
