### ISSUE TITLE
WP type dropdown selector looks strange

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10974]
No big issue, but to me the waypoint type selector when creating/editing a waypoint looks kind of narrow.
I mean the selector where you can choose the type of waypoint, e.g. "Reference Point", "Final", "Trailhead", etc.

Maybe we could give it the same room as the textfields above and below?

![Screenshot_20210620-222432_cgeo](https://user-images.githubusercontent.com/949669/122687426-b7d16900-d216-11eb-9869-582ca9c790bd.jpg)

**Comment by MagpieFourtyTwo** [comment]
And additionally the drop down list itself may get a different layout, cause it's a little bit hard to distinguish from the background?
At least in dark theme ...

**Comment by moving-bits** [comment]
Both are addressed with PR #11009
