### ISSUE TITLE
Adventure Lab caches not shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11001]
## Bug description 

Users report, that lab caches are not longer loaded.

### Steps to reproduce the problem

- Have LC connector active
- View live map

### Actual result after these steps 

No ALC show up

### Expected result after these steps 

ALC should be shown

## c:geo version 

2021.05.20 , 2021.06.23 and nightly

## Reproducible 

Yes

**Comment by Lineflyer** [comment]
See also:
https://github.com/mirsch/lab2gpx/issues/28

**Comment by Lineflyer** [comment]
There was no upfront communication by Groundspeak (also not regarding a follow up access method), however as posted above (commit linkt) there seems to be an easy "workaround".

@baiti 

If we could include this "workaround" on `release` I could quickly replace the ongoing rollout of the bugfix release with a new one.

**Comment by baiti** [comment]
I am investigating the situation. The referenced "See also"  mention a consumer key. We do not have a consumer key so I am not sure at this moment, what brought the back into the game.

**Comment by Lineflyer** [comment]
See the commit link above (They just used something).

**Comment by baiti** [comment]
> See the commit link above (They just used something).

That is a trivial fix then but what sense does THAT make?

**Comment by baiti** [comment]
should we identify ourselves in the string pattern we use?

**Comment by mirsch** [comment]
just to make things clear a bit:
I (developer of lab2gpx) recorded the network traffic of the official iOS app to see what has changed and am currently using the consumer key of the official iOS app. I don't currently know if the key depends on my device. That is why it is not in the source but is stored in a config file. The config is of course not checked into the repository.
You'll need a valid consumer key to make this work again.

**Comment by Lineflyer** [comment]
Thanks @mirsch for clarification.

OK, then we might need to ask Groundspeak again and until then we will have no more ALC. 
We used the current method with their approval and they promised to contact us with next steps for using the partner API, but they did not and just block the current method. I don't think we should use any "other" consumer key.

**Comment by baiti** [comment]
Update: By just sending the litereal: "THE-TOP-SECRET-CONSUMER-KEY" will not work.

**Comment by baiti** [comment]
> just to make things clear a bit:
> I (developer of lab2gpx) recorded the network traffic of the official iOS app to see what has changed and am currently using the consumer key of the official iOS app. I don't currently know if the key depends on my device. That is why it is not in the source but is stored in a config file. The config is of course not checked into the repository.
> You'll need a valid consumer key to make this work again.

Ahhh ok. Sure, I did the same thing and that works of course but I'd consider that illegal.

**Comment by Lineflyer** [comment]
I informed users via social media as follows:

Since some days adventure lab caches are no longer showing up in c:geo. The reason seems to be, that the access method previously approved by Groundspeak is no longer working and we don't have any information about other possibilities.
Nothing we can do about this on short term, see also our FAQ about the future of ALC:
https://www.cgeo.org/faq#ALC_future

**Comment by balu2003** [comment]
Yesterday I noticed that cgeo does not show the LabCaches. So I wrote to support. I wasn't sure whether it could be my fault. Thanks to @Lineflyer  who created issue # 11001. Next time I'll try to create a new issue myself. :-)
Here the API is described and the ominous "X-Consumer-Key" to use in the header is mentioned.
[https://labs-api.geocaching.com/swagger/ui/index#!/Adventures/Adventures_SearchV3](https://labs-api.geocaching.com/swagger/ui/index#!/Adventures/Adventures_SearchV3)
By googling I don't find anything about how to get this key from Groundspeak. 
Later I used curl with some magic parameters from the above API, I get JSON  or XML "Error message". Sure, I didn't have a key.

That works again, but the method of "key generation" is not "clean", as described by mirsch.
[https://gcutils.de/lab2gpx/](https://gcutils.de/lab2gpx/)

I assume you probably already knows everything.

**off topic**
Do you think it would be of any use if many cgeo users and paying premium members complained to Groundspeak about this miserable blocking tactic?
After all, cgeo ensures many satisfied users PM) who pay an annual fee to GS. Without a working cgeo's connector I would possibly terminate my premium membership and work more with cgeo and opencaching.de.
They should consider themselves lucky that you exist! and support cgeo.

**Comment by Lineflyer** [comment]
I will maybe contact GS after my vacation. Assigning this issue to me for now.

**Comment by Lineflyer** [comment]
Groundspeak contacted and positive answer received. Detailed info in internal forum.
Final answer however outstanding.

**Comment by Lineflyer** [comment]
Related PR has been merged. 
Needed key have been uploaded to the CI server.

Current nightly and next beta release should have ALC functionality again! :)
