### ISSUE TITLE
Altitude lines in offline maps

### ISSUE THREAD

**Issue by SnarkBoojum** [cgeo/cgeo#11004]
When viewing the map, choosing CyclOSM gives a map with altitude lines. But when downloading a map for offline use, there is no such line.

For plain users (pun intended) that's not an issue, but for mountain users, it's quite important data to have under the eyes.

Can these be added, please?

**Comment by eddiemuc** [comment]
I am not an expert in this, but afaik this is a matter of installing and configuring the right theme for the downloaded map data.

Which map service did you use for download? I use openandromaps and have altitude lines when using the elevate theme. (Granted, not as many as in cyclosm)

**Comment by SnarkBoojum** [comment]
I'm using the download service from within c:geo.

**Comment by SnarkBoojum** [comment]
(and the default theme)

**Comment by eddiemuc** [comment]
Hi @SnarkBoojum , c:geo currently offers 4 different servers to download map data from:

![Screenshot_20210624-181919.jpg](https://user-images.githubusercontent.com/6909759/123298531-df774880-d518-11eb-9986-d8ff156e54e6.jpg)

Maybe another map provider will fit your needs better?

**Comment by Lineflyer** [comment]
OpenAndroMaps in combination with their theme provide altitude lines for most of their maps.

**Comment by moving-bits** [comment]
c:geo does already support altitude lines, see @Lineflyer's comment, therefore closing this issue.
