### ISSUE TITLE
Personal note dialog action items not visible in light theme

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11006]
## Bug description 
The icons for "confirm" or "abort" in the new "edit personal note full-screen dialog" are not visible (or nearly so) in light theme:

![image](https://user-images.githubusercontent.com/3754370/123503420-31bc8480-d653-11eb-979e-2befac61a51b.png)

### Reproduce 
- set c:geo to light theme
- open a cache listing
- choose "edit personal note" from menu

### Actual result after these steps 
Action buttons are displayed in black on dark grey

### Expected result after these steps 
Action buttons should be displayed in white on dark grey

## c:geo version 
current master

## Reproducible 
yes

**Comment by fm-sys** [comment]
Same applies for the cache popup (they are using the same layout file)

![Screenshot_20210626_083510_cgeo geocaching](https://user-images.githubusercontent.com/64581222/123504429-9084fc80-d659-11eb-9420-6587cab1e49b.png)

But should be easy to fix...

**Comment by MagpieFourtyTwo** [comment]
BTW: Would it be possible to make the header of the PN edit window "non-floating", i. e. fixed?
Otherwise editing long PNs require a lot of scrolling: first down all the way, add the latest note,
then up again all the way, just to click [Save] ...

**Comment by fm-sys** [comment]
> BTW: Would it be possible to make the header of the PN edit window "non-floating", i. e. fixed?
> Otherwise editing long PNs require a lot of scrolling: first down all the way, add the latest note,
> then up again all the way, just to click [Save] ...

Isn't it already like that? Could you show some screenshots as this really shouldn't be the case... 

That's how it looks for me:

https://user-images.githubusercontent.com/64581222/123557655-62570800-d792-11eb-95f9-948f88db7734.mp4

**Comment by MagpieFourtyTwo** [comment]
Ooops - you're right. No clue what I had in mind ... guess it was "flowing" in one of the previous versions ... (left out the last three nightlies, as we were out in the wild since Wednesday) ...

However, just ignore my question please.

And sorry for the confusion. ;)

**Comment by murggel** [comment]
PR #11039 ready for review
