### ISSUE TITLE
Evaluate using a different action bar color

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11014]
> Although I wonder if it would look more modern, if we would use a different actionbar color instead. Personally, I don't really like this middle-light gray...

I'm not fixed to the middle-grey, but I would avoid using pure black or pure white for actionbar / navigation bar - that's too colorless, IMHO, too much blending of c:geo into the system's infobar (is that its name?). Most apps I know use a more vivid color for those bars (sort of "brand color"), which is also neither black nor white. That's why I started with our accent color in the beginning, but I agree that may be bit too much orange :-)

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/10928#issuecomment-869033363_

___

Actually, this "design trend" is just coming and can be seen in more and more apps. Although, many of them use accent colors for the action bar, at least this "blending style" can be seen in many apps. I would say, it's currently around 50% of all apps which I have installed. Here a few examples:

![Screenshot_20210626_194228](https://user-images.githubusercontent.com/64581222/123521465-1a16e780-d6b7-11eb-8d9b-80181efc6e2e.jpg)
![Screenshot_20210626_193843](https://user-images.githubusercontent.com/64581222/123521466-1b481480-d6b7-11eb-9d35-87077a7749d8.jpg)
![Screenshot_20210626_193952](https://user-images.githubusercontent.com/64581222/123521468-1be0ab00-d6b7-11eb-9bee-d2e39bc8dfdc.jpg)
![Screenshot_20210626_194254](https://user-images.githubusercontent.com/64581222/123521471-1be0ab00-d6b7-11eb-8973-812ad2d8a69d.jpg)
![Screenshot_20210626_194047](https://user-images.githubusercontent.com/64581222/123521472-1c794180-d6b7-11eb-957e-b090a2ef5c8c.jpg)
![Screenshot_20210626_194130](https://user-images.githubusercontent.com/64581222/123521473-1d11d800-d6b7-11eb-975b-b3a688a05274.jpg)

While in c:geo, it currently looks like we couldn't agree on one color ;-)

![Screenshot_20210626_195517](https://user-images.githubusercontent.com/64581222/123521703-90681980-d6b8-11eb-8960-b54eef30fb59.jpg)

In modern UI, there often aren't these "hard borders" anymore. Many apps (e.g. Gmail or the file selector) even only have one background color which is used from the very top to the very bottom, which visually IMHO feels very balanced. Different colors are only used to focus attention on very specific UI components...

**Comment by fm-sys** [comment]
Just tried it out in the emulator, having an all-black background:





|![grafik](https://user-images.githubusercontent.com/64581222/123522216-4123e800-d6bc-11eb-8eac-4779520d3ed6.png)|![grafik](https://user-images.githubusercontent.com/64581222/123522245-703a5980-d6bc-11eb-8ef9-f33733432efc.png)
|-|-|
|![grafik](https://user-images.githubusercontent.com/64581222/123522273-a37ce880-d6bc-11eb-9dca-bbfdc91f5c0d.png)|![grafik](https://user-images.githubusercontent.com/64581222/123522222-4ed96d80-d6bc-11eb-9c83-35c836401e0c.png)

I agree, that this doesn't look that good as well :-/

For the "dark" theme, the gray action bar is probably fine (although it could be slightly darker). But the current color definitely isn't a really good idea for "light" theme...


I wouldn't call this issue urgent, as it was the same before our redesign, but we should keep this issue open if someone comes at any time with a perfect solution at hand ;-)

**Comment by Lineflyer** [comment]
I suggest a slight visual difference at least to make users aware, that this is a "static" area containing controls.
Mabye like the Signal example with slightly more differing colors, but much darker as the current grey.

**Comment by fm-sys** [comment]
BTW, don't know if someone had noticed it, but our old popups are using a transparent "actionbar" as well... (at least until I replace them with AndroidX toolbar ;-))

![grafik](https://user-images.githubusercontent.com/64581222/123828358-b2a0a800-d901-11eb-84f0-6e301cbb2ebd.png)

**Comment by fm-sys** [comment]
As discussed in our meeting: Use a darker actionbar color for dark mode and a lighter one for light...

**Comment by Lineflyer** [comment]
I played around a bit in the emulator as I did not only want to open tickets but also help a bit in solving them ;)

Black theme:

|current action bar FF303030|Proposal FF202020|Proposal FF151515|
|---|---|---|
|![master_ff303030](https://user-images.githubusercontent.com/949669/125268908-778e7380-e308-11eb-9275-1a70baa2d35b.png)|![ff202020](https://user-images.githubusercontent.com/949669/125268955-86752600-e308-11eb-983d-59288ed136bc.png)|![FF151515](https://user-images.githubusercontent.com/949669/125268989-8e34ca80-e308-11eb-8c4c-4cc774a170a3.png)

I prefer the FF202020 as with FF151515 the separation is almost invisible.

White theme:
|current action bar FF303030|Proposal FF404040|Proposal FF606060|
|---|---|---|
|![master_white_Ff303030](https://user-images.githubusercontent.com/949669/125269752-4c585400-e309-11eb-82fc-20558283b43a.png)|![white_Ff404040](https://user-images.githubusercontent.com/949669/125269784-5417f880-e309-11eb-80ad-4159fa30087e.png)|![white_FF606060](https://user-images.githubusercontent.com/949669/125270023-904b5900-e309-11eb-9f2b-131cb12c08c7.png)

I am unsure here, but I think we could use FF606060 or even lighter?!

**Comment by Lineflyer** [comment]
Here is FF505050 for white theme to be complete:
![white_FF505050](https://user-images.githubusercontent.com/949669/125270220-bcff7080-e309-11eb-94a4-c51b602a9409.png)

**Comment by Lineflyer** [comment]
Note:
Need to review action bar font colors after changing the action bar (especially on white theme):

With FF505050 the subheading is not readable:
![image](https://user-images.githubusercontent.com/949669/125270602-1a93bd00-e30a-11eb-8ea9-cbb65e12a7fa.png)

**Comment by fm-sys** [comment]
We could even think about making the color that light that we can use a black text color in light mode. Don't know how it will really look though...

**Comment by fm-sys** [comment]
> We could even think about making the color that light that we can use a black text color in light mode. Don't know how it will really look though...

But probably it's better to stay with the colors you have chosen for now. If necessary, it can still be fine tuned later on.
