### ISSUE TITLE
Optimize popup title bar

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11022]
IMHO our map popup needs at least still dome finetuning.
In general the redesign is OK (except if we want to replace it by some other material design element e.g. a bottom sheet) but looking at this example we should at least thing about the title bar:
![image](https://user-images.githubusercontent.com/949669/123547106-b8f71e80-d75f-11eb-843b-205021b50273.png)

- How about omitting the cache name in the title bar...most of the time it does not fit anyway and its now already contained in the content below?
- The cache icon looks a bit narrow compared to the buttons on the right hand side. Does it have the same width/height already?
- What could we show instead of the title? Nothing or something like "Cache info" (if it fits in all languages)?
- It also looks strange, that the height of "More Details" (outline) is more narrow than the outline of the icon next to it.

Other thought:
Would a bottom sheet maybe suitable to replace it completely?
![image](https://user-images.githubusercontent.com/949669/123547222-37ec5700-d760-11eb-8280-58af09e0e4f2.png)

After clicking on a cache it could show its name only (one liner as in the example above) and the user can expand it to view the other details... Just thinking...no idea if its suitable and according to the meant usage of this element.

**Comment by moving-bits** [comment]
> * How about omitting the cache name in the title bar...most of the time it does not fit anyway and its now already contained in the content below?
> * What could we show instead of the title? Nothing or something like "Cache info" (if it fits in all languages)?

We could show
- either the cache GC code (for caches) or the WP GC code (for waypoints),
- or "cache" (or "waypoint" resp.) as a more generic title

> * The cache icon looks a bit narrow compared to the buttons on the right hand side. Does it have the same width/height already?

It's probably the same width/height, but without the additional margins Android automatically adds around buttons for easier touch experience.

> * It also looks strange, that the height of "More Details" (outline) is more narrow than the outline of the icon next to it.

agreed

> Other thought:
> Would a bottom sheet maybe suitable to replace it completely?
> 
> After clicking on a cache it could show its name only (one liner as in the example above) and the user can expand it to view the other details... Just thinking...no idea if its suitable and according to the meant usage of this element.

We had a discussion about this quite some time ago, @jonas-koeritz even provided a sample for it, but sadly did not finish that work.

**Comment by Lineflyer** [comment]
> either the cache GC code (for caches) or the WP GC code (for waypoints),

That sounds meaningful as it has a (more or less) fixed length we could optimize in size to always fit.

> We had a discussion about this quite some time ago, @jonas-koeritz even provided a sample for it, but sadly did not finish that work.

Thats anyway maybe a dedicated issue for the future (IMHO there is already one about that).

**Comment by Lineflyer** [comment]
I think this is solved by the referenced commit.
@moving-bits Feel free to reopen if my interpretation is wrong.
