### ISSUE TITLE
All lists except history lose their position

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11028]
- Open list of caches, scroll down
- Open a cache further down
- Close cache details again to return to the list

Result:
List is scrolled to top

Expected:
Same list status as before opening cache details

On history list its working.

2021.06.28-NB

**Comment by fm-sys** [comment]
This seem to be caused by the new filter framework. Could this be the case?

**Comment by Narrat** [comment]
Possible duplicate of 10976?

**Comment by fm-sys** [comment]
Yes, you are right. Somehow we have missed that issue. So let's close this one as duplicate...
