### ISSUE TITLE
[API >= 29] don't ask for general storage access permission

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11029]
BTW, if using SAF, asking for grading general storage access permission is not necessary anymore in our wizard for API >= 29 (Android 10) 

In fact,  the whole idea of SAF is that users don't have to grant this permission anymore, but only need to grant permission to these folders the app really needs to access...

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11018#issuecomment-869133639_

**Comment by fm-sys** [comment]
This should be done as soon as we have switched to target API 30...

**Comment by Lineflyer** [comment]
But it can not only be removed for API >=29 but for all...or not?

**Comment by fm-sys** [comment]
This whole SAF thing is relatively new, so it could be that older devices crash if they don't have this permission. In other apps I had seen that they check the API level programmly and I have veryfied myself that it works without the permission, but for sure we could check if it works without the permission on older devices as well... The storage access permission is a dynamic permission, which needs to be asked at runtime. And the app can decide, if at all or when it is the right time to do so.

**Comment by Lineflyer** [comment]
Understood. Lets keep it as a safety net then for some time I would say.

BTW: The wizard without this permission should be tested again. At the moment SAF will always find/suggest the /cgeo/ folders with their default content as it is AFAIK created using the old permission before the SAF request is triggered.

**Comment by Lineflyer** [comment]
> Understood. Lets keep it as a safety net then for some time I would say.

Addon after thinking about it again:
If such failures are still out there, users will be on legacy dirs and the wizard showing up on each start. Maybe we should really completely remove the legacy permission to enforce that such problems reach our support. Otherwise we might only delay the problem.

**Comment by fm-sys** [comment]
Should be fixed by https://github.com/cgeo/cgeo/issues/13798, right?
