### ISSUE TITLE
Show text for all items on map action bar (if room)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11034]
Now or action bar is more cleaned up and while working on it now more menu items have moved from overflow menu on the action bar itself. This is nice, but we should add the text here if there is enough room.
Because:
- It looks more complete, than just showing icons
- Many people might struggle to find a certain action as it was shown textual only before (behind overflow) and is now only shown as an icon  (I can imagine a lot of support mails like: Why did you remove the "Disable live" function?)

![Screenshot_20210628-211119_cgeo](https://user-images.githubusercontent.com/949669/123691386-dc03fa00-d855-11eb-96a6-a5460d4301f3.jpg)

**Comment by MagpieFourtyTwo** [comment]
What bothers me more than "no text" (IMHO the icons are pretty self-explanatory),
is the "Live" icon, which shows no difference between "enabled" and "disabled".
Couldn't this e. g. be crossed out if disabled ...?

**Comment by Lineflyer** [comment]
With text, the text should change at least alteady now...but thats another argument to show the text.

**Comment by murggel** [comment]
> What bothers me more than "no text" (IMHO the icons are pretty self-explanatory),
> is the "Live" icon, which shows no difference between "enabled" and "disabled".
> Couldn't this e. g. be crossed out if disabled ...?

Same for "toggle talking"
