### ISSUE TITLE
Overflow menu use wrong background color in light mode 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11046]
Another observation:

The popup overflow menu is dark in lightmode...|...while all other overflow menus are light.
-|-
![Screenshot_20210630_150756_cgeo geocaching_copy_454x491](https://user-images.githubusercontent.com/64581222/123967307-7aa76c80-d9b6-11eb-8777-5cc9b13377bd.png)|![Screenshot_20210630_150913_copy_432x474](https://user-images.githubusercontent.com/64581222/123967311-7b400300-d9b6-11eb-8778-ec964bc21200.jpg)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11042#issuecomment-871400541_

**Comment by murggel** [comment]
Did not find a solution yet...

**Comment by fm-sys** [comment]
It took me hours to find a working solution. But here we go...

![grafik](https://user-images.githubusercontent.com/64581222/125830831-cddcbd86-7410-470b-9874-de64301702f5.png)

![grafik](https://user-images.githubusercontent.com/64581222/125830763-f423de57-87a6-40cb-8a85-ac5fd005d16c.png)

**Comment by murggel** [comment]
> It took me hours to find a working solution. But here we go...
> 

How did you find the solution?  Just for my information / learning for the future how I have to search...

**Comment by fm-sys** [comment]
> > It took me hours to find a working solution. But here we go...
> 
> How did you find the solution? Just for my information / learning for the future how I have to search...

Don't worry, finding a solution for it was more or less like a lottery. 

Often I read through Stackoverflow to find an answer, but this time it was really only trial and error.

Yesterday, I tried at least 20 different solutions I had read somewhere in the internet.aAt the end I'd deleted the complete branch again because nothing was working. 

Today, I stumbled over the fact, that there is an explicit `MaterialToolbar` component. Then I randomly edited, moved around and deleted different attributes until I suddenly had a working solution. Damn, sometimes Android can be really complicated :-/

**Comment by murggel** [comment]
> > > It took me hours to find a working solution. But here we go...
> > 
> > How did you find the solution? Just for my information / learning for the future how I have to search...
> 
> Don't worry, finding a solution for it was more or less like a lottery. 
> 
> Often I read through Stackoverflow to find an answer, but this time it was really only trial and error.
> 

Thank you, I also read a lot in stackoverflow but sometimes I think it's hard to find the right keywords to search for. 
Glad, that I am not the only one 😊
