### ISSUE TITLE
Differentiate between locked and archived states

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11045]
c:geo currently treats locked and archived states the same, showing them as archived (see #6889). But there should be some differentation between them in the app as archived caches can be logged, locked ones can't.

Usecase:
I often go looking for archived caches as in many cases the container is still out there, it's just that the listing was archived for some reason (e.g. a wet logbook NM log and an inactive owner).
The other day I found such a cache but when I wanted to log it I found it out was locked. So I'm loosing valuable stat points ;-)

**Comment by jakedot** [comment]
what should we do that can benefit you in any meaningful way?

- If the cache listing is archived, you can log it. Check.
- If it somehow becomes archived after you visited it, but before you logged it, it's bad luck, and nothing we do in c:geo can change your not being able to log it. Check.
- And if you are purposefully trying to search for archived caches, you can try logging a Write Note log before going out, so you know beforehand. Check.

We shouldn't waste any resources for such a niche caching behaviour, when it is already possible to work around it (by doing the check by trying to log the cache from home, before going out into the field).

**Comment by ztNFny** [comment]
Well, if the status was "locked" instead of "archived" it would be apparent at a glance. No need to test log or anything.
Most archived caches are just archived (and still on site), so a locked one is always a surprise.

On gc.com it has the "this cache is logged" text at the top of the page, making it quite obvious. Cgeo could display it either as status, as a log or at the top of the listing (similar to the GC link for OC listings)

**Comment by Lineflyer** [comment]
I do not think this would be a much desired feature. Locked caches are quite rare and we therefore actively decided to show them as archived only. As mentioned by others above there is an error message when you try to log them.  Also locked but not archived caches should be even more rare.
All these facts do not justify putting much effort in reflecting just another status of caches in our code, therefore no further change planned for the time being.

It might change if new features come up as e.g. the owner can lock his caches from logging it.
