### ISSUE TITLE
Use same icons in filter and quick settings

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11060]
> I like those emojis in the status filter.
> So shouldn't the first three (found, own, stored) also use a colored emoji?
> For "found" and "own" the emoji from map...

Technically this is really easy to achieve of course. 

Right now those are the same icons which are used in the map quick settings. If it is ok to have different setting here then it should not be a problem.

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/pull/11043#issuecomment-873216523_

**Comment by murggel** [comment]
I think it would make more sense to have consistent icons in one view.
Can't we use the icons / emojis from the filter in the quick-settings as well? 
And for the waypoint-types we can use the same icons which are used in the waypoint-list...
I can try and share some screenshots for discussion

**Comment by murggel** [comment]
![image](https://user-images.githubusercontent.com/70113341/124334823-a08c6700-db98-11eb-9697-e6ed92ed9790.png)

**Comment by murggel** [comment]
using default-color for track and circle does not look really nice.
![image](https://user-images.githubusercontent.com/70113341/124334959-07118500-db99-11eb-9c06-ec2910ca1d72.png)

**Comment by murggel** [comment]
Using accent-color for track and circle:
![image](https://user-images.githubusercontent.com/70113341/124335061-4fc93e00-db99-11eb-84c4-01e6973a3b63.png)

**Comment by murggel** [comment]
Original screenshot:
![image](https://user-images.githubusercontent.com/70113341/124335142-9cad1480-db99-11eb-8bdd-5836bd210934.png)

**Comment by murggel** [comment]
Filter with colored icons for found, own
![image](https://user-images.githubusercontent.com/70113341/124335194-d5e58480-db99-11eb-9ded-78ee9d32c649.png)

**Comment by eddiemuc** [comment]
Looks nice.

Did you take a look at "light mode" as well and whether it looks good there too?

**Comment by fm-sys** [comment]
If we go that way, we should use a different icon for logged offline. Why not reusing the map marker icons for logged and logged offline?

**Comment by eddiemuc** [comment]
> If we go that way, we should use a different icon for logged offline. Why not reusing the map marker icons for logged and logged offline? 

This is already one of the markers for "logged offline". There are multiple ones, depending on whether you logged a "write node" or a "found" log. I assume you think about the orange "found" logged marker?

**Comment by fm-sys** [comment]
Oh, yes.You're right. Haven't remembered that,  as I mostly have found it offline logs.

> I assume you think about the orange "found" logged marker? 

Yes, that would be my suggestion. 

And use the yellow "found" map marker icon instead of  an emoji for normal found.

**Comment by murggel** [comment]
I will prepare some screenshots...

**Comment by murggel** [comment]
![image](https://user-images.githubusercontent.com/70113341/124350706-81bcbd80-dbf6-11eb-86c5-eb5478346555.png)

**Comment by murggel** [comment]
![image](https://user-images.githubusercontent.com/70113341/124350934-c4cb6080-dbf7-11eb-8624-94b61f823c3c.png)

**Comment by murggel** [comment]
How about using similar icons for "On watchlist" and "Own Favorite" as GC uses it?
![image](https://user-images.githubusercontent.com/70113341/124364922-0c2c0e00-dc45-11eb-92fa-e821639f7982.png)

![image](https://user-images.githubusercontent.com/70113341/124364940-2bc33680-dc45-11eb-968e-307cb5a8db9e.png)

Or is the difference on purpose?

**Comment by eddiemuc** [comment]
> How about using similar icons for "On watchlist" and "Own Favorite" as GC uses it?

I like this idea! The chosen icons were just the first ones that came to mind.

**Comment by murggel** [comment]
PR #11080
