### ISSUE TITLE
Icons of linked apps are black/white only

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11078]
- Open a Wherigo cache
- On the cache details page the icon for opening WhereYouGo is hardly recognizable as it is black/white only

Same applies for adventure lab icon and Chirp Wolf

**Comment by murggel** [comment]
I guess it is a regression of the button-style for svg.

Will check tomorrow evening... if someone has time before - feel free

**Comment by Lineflyer** [comment]
For checking you need to open a Wherigo cache, a cache with attribute "wireless beacon" (searching for keyword NFC or chirp will do) and an adventure lab cache. Not sure if there is something else, where we use such link.

**Comment by moving-bits** [comment]
Setting `<Button app:icon="...">` to `<ImageView android:src="...">` in `cachedetail_details_page.xml` brings back the color, but the thin frame around the "button" is missing then:

![image](https://user-images.githubusercontent.com/3754370/124375158-f8ae9080-dca0-11eb-8e5d-b08801dadd9e.png)

**Comment by murggel** [comment]
And using a new style without the tint-attribute resp. is there a possibility to clear the tint-attribute?

**Comment by moving-bits** [comment]
If I understand the mechanism correctly, a `<Button>` with an `app:icon` uses `colorPrimary` to tint this icon - either a `colorPrimary` we define in the style, or the default. In contrast to this, an `<ImageView>` does not re-tint the image, so we get the colored version. But as it isn't recognized as a button, the outline style does not get applied either... :-(

**Comment by moving-bits** [comment]
found a solution for it (applying a "dummy tint", overriding the default tint), PR will follow
