### ISSUE TITLE
Radar no longer available as navigation method

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11079]
I have set up my default navigation tool (for click on the compass icon in a cache or a waypoint) to use "Radar" (using the app "GPS Status").

This worked well with the nightlies over the last week.
However after installing the latest nightly (may also be 1-2 days ago) it stopped working but the compass is opened instead.

Looking into Settings - Routing/Navigation - Default navigation the option "Radar" can no longer be selected. It is also no longer available when using the menu function "Navigate" on a cache.

No changes with respect to the installed app "GPS Status" or other device settings.
Maybe its related to SDK30?

**Comment by fm-sys** [comment]
> Maybe its related to SDK30?

Yes, could likely be.

I think, we need to add the `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>` permission to our manifest

**Comment by eddiemuc** [comment]
> > Maybe its related to SDK30?
> 
> Yes, could likely be.
> 
> I think, we need to add the `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>` permission to our manifest 

Very likely, see here:
https://developer.android.com/training/package-visibility

**Comment by Lineflyer** [comment]
You are right, it also tells me for Wherigo caches, that I should install WhereYouGo although it is installed.

Same for ALC.

**Comment by Lineflyer** [comment]
According to the link provided...maybe we should not use the all packages method but including only packages we want to interact with. In the spirit of data privacy.

**Comment by eddiemuc** [comment]
But we should not add the `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>` permission, it seems that a special review process will be associated (https://support.google.com/googleplay/android-developer/answer/10158779) and frankly we don't really need access to ALL packages...

Instead I guess we need to compile a list of packages / intents we really need and add the reqpective queries elements (as describede here: https://developer.android.com/training/package-visibility/declaring)

**Comment by moving-bits** [comment]
See #11091 for a first list of packages queried by c:geo, feel free to add additional required packages over there
