### ISSUE TITLE
Remove "Remove list" question dialog

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#11081]
## What function is annoying you ;)
In the past there already appeared a dialog if the last cache has been removed from a list like ``List is empty. Do you want to remove the current list?`` - which already became kind of annoying, esp. if you have some lists which get empty *on purpose* every single day, like e. g. ``Today`` (when all caches in today's ToDo list have been visited) or ``Offline Logs`` (when all visited caches are logged, refreshed, and then moved to ``All finds``). But this was "just" once a day, so I lived with it.

But things got worse, cause now this dialog additionally appears even on entering such a list via e. g. the ``Stored`` button in main screen or after a filter has been set ... or ... I don't know where else, as I have given up to count the number of clicks I have made just thjs evening to  just acknowledge this dialog with ``No``.  :/

An, no, I *never* *ever* want these lists to be deleted ...  ;)

So, can we *please* do s/th to dam this dialog spam flood? :) By either inventing a setting to disable this dialog or add a [Never] for certain lists which should never be deleted? Or even remove this dialog completely? Especially since one can certainly assume that a user who is able to create a list, is also able to delete it when he (really) no longer needs it.

TMALSS: IMO the current number of questions is near to paternalism and a bit exaggerated ...

## c:geo version
2021.07.04-NB-0168c2e

**Comment by fm-sys** [comment]
I'm using this feature on a regular basis.

E.g. have a list "powertrail xy" or "Berlin trip". After the trip, I remove all caches from that list and delete the list afterwards. But indeed, I wouldn't miss anything, if I would have to select "delete list" manually...

**Comment by eddiemuc** [comment]
+1 for removing the `List is empty. Do you want to remove the current list?` confirmation completely.

**Comment by Lineflyer** [comment]
I also use that feature frequently.
IMHO we should fix the regression mentioned: It shows up everytime you enter an empty list. In fact it should only show up at the very moment the last cache is deleted.

**Comment by MagpieFourtyTwo** [comment]
> In fact it should only show up at the very moment the last cache is deleted.

Still not entirely perfect, but would be ok for me. ;)

**Comment by MagpieFourtyTwo** [comment]
@moving-bits wrote in #10922 
>  for #11081 we have no easy solution found yet.

If it's so hard to solve, why not just remove the question completely?
IMO it's pretty superfluous, anyway ... cause a user that was able to create a list, will for sure be able to remove it himself.
And as manual removal just means two clicks more, this doesn't seem seem to be a big burden ...?  ;)

**Comment by MagpieFourtyTwo** [comment]
@moving-bits  Just stumbled upon the ``[_] Do not ask me again for this list`` dialog - GREAT! Thx a lot!  :)))
