### ISSUE TITLE
New Filter Framework: remove "Found by" search?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#11103]
While working on new filter framework I discovered a potential problem:

c:geo offers currently a lot of "Search by" functions in the search activity. Those were clearly originally copied from the old/legacy gc.com-search here: https://www.geocaching.com/seek/nearest.aspx

Among them is the search function "Found by" (Gefunden von):

![image](https://user-images.githubusercontent.com/6909759/124426473-5fe44780-dd6a-11eb-9ed0-834c60f510fd.png)

Now the problem: 
* this kind of search is not supported by the new filter framework for geocaching.com
* It **can't** be supported by the new framework because the web proxy search interface used does not offer the possibility to search by "Found by" (it supports only search by "not found by")

Since gc.com is our "major service" I see two possible solutions out of this
* Remove "Found by" search function from c:geo. As said before this was clearly only introduced anyway because it was once available on (now legacy) gc.com search, and it is no longer available to the users via "normal" website
* Leave legacy search for this specific function. However, new filter framework can NOT be used in interconnection

I am strongly suggest the first solution (remove search function). What is your opinion?

**Comment by fm-sys** [comment]
To be honest, I can't imagine a real use case for it. Let's just drop it. 

BTW, the feature seem to work only when you are searching for premium member usernames. If I search as PM for user who is only basic, I don't get any results back. At least when I enter  the username of a friend of mine who is only basic...

**Comment by MagpieFourtyTwo** [comment]
Can be used for tracking, nastily speaking for stalking - which might be the reason why it is not (resp. no longer) supported.
I guess no one will even notice when it's gone.  Except for the stalkers ... ;)
Therefore: +1 for removing it.

**Comment by eddiemuc** [comment]
I created PR #11115, which (if merged) will remove the "Found by" search from c:geo surface

**Comment by alan666notb** [comment]
Actually, we use this search function quite a lot...

When I go around a series with my partner, I usually make just a brief 'found' log in the field.

Later on, she uses the 'search by name' option to find all the caches I've logged, sorts them into 'date-logged' order, and then goes through them leaving a more detailed log entry.

I guess we're about to lose that ability?

**Comment by fm-sys** [comment]
As a workaround, you could simply create a list out of the caches you have found, and send the GPX to your partner. Or what about field notes export?

**Comment by eddiemuc** [comment]
I googled a bit, and it seems Groundspeak removed this search function intentionally. Here's what they recommend themself:
![image](https://user-images.githubusercontent.com/6909759/124610845-264a3400-de71-11eb-8446-0e6932dc50df.png)
https://www.geocaching.com/blog/2015/03/faq-the-new-geocache-search-tool/

I am personally not convinced by this, since you can't combine the search with other search criterias like that, but well that's Groundspeaks decision.... Anyway I don't expect they will put it into their actual search.

It is possible technically to leave the legacy search available in c:geo for "Found by" of course, but it must then be a completely separate search path not connected to new filter/search framework. I don't like this at all from a technical perspective since also lots of legacy code still has to be maintained.

**Comment by alan666notb** [comment]
How does this compare with tapping on a users name on a log entry and choosing "Caches found".
Does that get the same results?
Or will that option disappear as well?

**Comment by MagpieFourtyTwo** [comment]
> It is possible technically to leave the legacy search available in c:geo for "Found by" of course, but it must then be a completely separate search path not connected to new filter/search framework. I don't like this at all from a technical perspective since also lots of legacy code still has to be maintained.

Totally agreed.

> Or will that option disappear as well?

Looking from outside I would strongly assume this is the very same function, thus: Certainly, it will.  ;)

**Comment by eddiemuc** [comment]
> How does this compare with tapping on a users name on a log entry and choosing "Caches found".
> Does that get the same results?
> Or will that option disappear as well?
> 

Whoops, totally forgot about those. Would be affected as well I'm afraid

 I have to change the "caches owned" point from same context menu to new search

**Comment by MagpieFourtyTwo** [comment]
What about ``Caches hidden``?  Will most probably use the same way ...?

**Comment by MagpieFourtyTwo** [comment]
Which BTW is a search I use really often - esp. when we once again discover a "quality owner" by chance.

**Comment by fm-sys** [comment]
> What about `Caches hidden`? Will most probably use the same way ...?

`Caches hidden` is still supported via the new search, so don't worry, this will not be taken away ;-)

**Comment by MagpieFourtyTwo** [comment]
HOOOOORAAAAYY!  ;o)

**Comment by eddiemuc** [comment]
I opened a topic in GC.com forum asking for "found by" search support via their map (which in turn would enable it via the web prox API we use)

**Comment by MagpieFourtyTwo** [comment]
BTW: What I found a bit irritating is that even if the global option ``Exclude Found`` is enabled, you nevertheless get already found caches listed with ``Found by <user>`` - obviously the global settings are now completely disregarded, finally ... and intentionally, I guess (regretfully, BTW).  But if they are not obeyed anymore, shouldn't they be dropped then - or is there still a reason to keep them?  Or is there still a chance to get them back for searches ...?

**Comment by alan666notb** [comment]
This might be the wrong place to raise this but...

Trying out the new "Search by filter", I searched for all caches owned by, say, "Fred Bloggs", which gave me the list of caches I expected.

Then, when I went back to the live map, the filter was still operational - i.e. I only saw caches owned by "Fred Bloggs" on the map. I had to use the filter icon and dustbin icon to clear it.

Is this correct? - It's not what I expected to happen at all, if the filter had been quite wide (e.g. only T3 or less  caches), I might not have realised it was still in place.

**Comment by eddiemuc** [comment]
> BTW: What I found a bit irritating is that even if the global option ``Exclude Found`` is enabled, you nevertheless get already found caches listed with ``Found by <user>`` - obviously the global settings are now completely disregarded, finally ... and intentionally, I guess (regretfully, BTW).  But if they are not obeyed anymore, shouldn't they be dropped then - or is there still a reason to keep them?  Or is there still a chance to get them back for searches ...?

Specifically for the "Found by" search, the "exclude Found" option should still be honored. If not, there might be a bug in the (legacy) search code. Not that the "exclude Found" flag is specifically overridden if you search for your own finds.

**Comment by eddiemuc** [comment]
> This might be the wrong place to raise this but...
> 
> Trying out the new "Search by filter", I searched for all caches owned by, say, "Fred Bloggs", which gave me the list of caches I expected.
> 
> Then, when I went back to the live map, the filter was still operational - i.e. I only saw caches owned by "Fred Bloggs" on the map. I had to use the filter icon and dustbin icon to clear it.
> 
> Is this correct? - It's not what I expected to happen at all, if the filter had been quite wide (e.g. only T3 or less  caches), I might not have realised it was still in place.
> 

This is indeed the implemented behavior, there is just one global filter setting which is stored and reused at all places. Whether this is the wanted behavior is a different question and was subject to long discussions...

Can be changed in principal, but a consistent proposal must be made on which places which filter settings should or shouldn't be reused. Might be good to do this in a separate issue if wanted.

**Comment by MagpieFourtyTwo** [comment]
Sorry - my mistake, this did not happen when using the ``Found by`` search (guess the thread subject probably misled me), but with the ``Hidden by`` search (via context menu of the user name of a log, that's how I ended up there while dealing with the current thread): Although the global setting ``Exclude found`` was enabled, I still got all the caches displayed which I have already found.

Maybe because I have all found caches saved offline, too ...?

Which, BTW, would prove @fm-sys' (?) example false, who once stated that users are flabbergasted cause they did not get already found stuff with this search.  They will!  ;)

**Comment by MagpieFourtyTwo** [comment]
> if the filter had been quite wide (e.g. only T3 or less caches), I might not have realised it was still in place.

You should have seen the currently active filter displayed at the top of the map ...

**Comment by MagpieFourtyTwo** [comment]
[...different lists in different contexts]
> Can be changed in principal, but a consistent proposal must be made on which places which filter settings should or shouldn't be reused. Might be good to do this in a separate issue if wanted.

Yep. totally agreed, as complexity of this theme is immense.
As for me, e. g., I would really like to see a possibility(!) to set a filter for every single list (and perhaps even map) context ...
Example: ``Found:No`` in searches, map etc. pp, in contrast to ``Found:Yes`` (resp. inactive ``Found:No``) in the ``All finds`` list.
While this filter should replace the global filter *as long as I'm in the context of this list*, it should *not* change the global filter.
And if a list has no dedicated filter defined, the global filter should be applied (as usual) ... which would be the standard for "normal" users.

**Comment by eddiemuc** [comment]
> Sorry - my mistake, this did not happen when using the ``Found by`` search (guess the thread subject probably misled me), but with the ``Hidden by`` search (via context menu of the user name of a log, that's how I ended up there while dealing with the current thread

Ah yes. The "hidden by" filter already uses the new filter framework (and thus does not honor the global "Exclude found" - but it honors the new global filter), while the "found by" uses the legacy search (and thus honors the global "exclude Found" - but not the new global filter). This is a bad situation, but unfortunately I can't change the "found by" search to the new framework...

**Comment by eddiemuc** [comment]
See #11115. This should be merged only if we are absolutely sure that "search by found-by" and user "caches found" can be removed from c:geo

**Comment by Lineflyer** [comment]
For me the search would still be "Nice to have" but it seems no urgent/critical use case for most users.
Some users would miss it, but following the post and information pasted here from GC.com I also understand they removed this "stalking" feature. 
So I would be OK with removing it to remove complexity and dependency to old search pages.
I will probably add a FAQ entry why it was removed if this is asked by users after all.

So +1 from my side to merge.
