### ISSUE TITLE
Waypoint name don't shown up at all

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11110]
While playing with the nightly, I just noticed that the name of the waypoint isn't shown at all anymore, while the geocode (which is AFAIK even no real geocode) is shown twice. This significantly affects the usability when playing multi caches, as you cannot see if you have selected the right waypoint.

Don't think this is a blocker for the beta, but this should be fixed as soon as possible...

![Screenshot_20210705_225302](https://user-images.githubusercontent.com/64581222/124517247-c9546c80-dde3-11eb-849e-1a5a5515fb88.jpg)

**Comment by Lineflyer** [comment]
This problem is one of the most mentioned in the beta feedback mail I received. We should include the name here as well like we do for the cache itself.
We could also ommit the geocode of the waypoint and just replace it with the title.

Should be fixed on ˋreleaseˋ.

**Comment by moving-bits** [comment]
> We could also ommit the geocode of the waypoint and just replace it with the title.

added this to the already existing PR #11129
