### ISSUE TITLE
First start after update shows "Version/help", not "Changelog"

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#11114]
## Bug description 
A minor issue, but on updating to 2021.07.05-RC this morning, the first screen shown on startup is "About c:geo - Version/help", not "About c:geo - Changelog".

It always used to show the changelog for a new version.

### Steps to reproduce the problem
Update to 2021.07.05-RC and start c:geo

### Actual result after these steps 
"About c:geo - Version/help" is shown

### Expected result after these steps 
"About c:geo - Changelog" should be shown

## c:geo version 
2021.07.05-RC

**Comment by moving-bits** [comment]
Which version have you been upgrading from?

(Technical background: Displaying changelog is being determined by building a checksum for the changelog's text, so if that hasn't changed compared to the checksum from the last version you've used, no changelog is being displayed initially. But this may be valid only when coming from a nightly version, not if you've upgraded from a different version.)

**Comment by alan666notb** [comment]
I don't know, but it will have been the previous version available from playstore (I'm a beta tester).

Some more info - my partner (also a beta tester) just got the update.
When she started cgeo, the 'about cgeo' pages weren't shown at all, it just went to the 'six tiles' page as normal.

**Comment by moving-bits** [comment]
Ok, so it's been the last released version (2021.06.23) you have been using so far. That's strange, also what your partner has experienced.

If you're using the same version, both of you should have been presented the changelog, neither mainscreen only nor the about page, for sure.

**Comment by alan666notb** [comment]
OK - just fired-up an old phone that had 2021.05.20 and let it update.

It did the same as mine - presented the "Version/help" page rather than the changelog.

(BTW, on both phones, the background to the main page is now white, not black like it used to be)

**Comment by moving-bits** [comment]
will be fixed with #11126
