### ISSUE TITLE
map label font too large, cuts off

### ISSUE THREAD

**Issue by stephr321** [cgeo/cgeo#11116]
## Bug description 

In map view, the 2nd row of the label is cut off that shows number of caches in the view. For instance, if it says Live Map, below that shows ### caches but you can't read it. Font is too large.

## c:geo version 

2021.07.05-RC

## System information 

Device: SM-G986U (y2qsqw, samsung)
Android version: 11
Screen resolution: 1080x2201px

```
Paste your system information here
```

**Comment by wolverine007** [comment]
Overall the used font size is to big.

Or did I miss a new setting to change the font size basing on my own preferences?

**Comment by Lineflyer** [comment]
The font size does now follow Android style guideline and are additionally adaptive (they will follow your system font size setting).
No plans to generally change that, however the cut off text might not be desired.

@stephr321 
Can you provide a screenshot of the problem you initially described please?

**Comment by moving-bits** [comment]
I've made screenshots of the map for different system settings for font size:

![image](https://user-images.githubusercontent.com/3754370/124664369-a097aa00-deab-11eb-97ca-a81e269732bd.png)

These are font sizes small - default - large - largest

While it might be ok to cut off some (secondary) test in "largest" mode, I guess text should still be visible in "large". So we can either reduce font size a tiny bit for the actionbar, or is there a way to dynamically increase the actionbar's height depending on the chosen system setting for font size? (And would that be the way we would like to go? How do other apps handle that?)

**Comment by stephr321** [comment]
Hopefully these attach properly from my phone. Should be 3 screenshots below showing font size issues on various screens. If there is a secondary line it is being cut off as well as other issues. I do not use overly large fonts on my phone and have never had an issue in the past with this or any other apps. Hope this helps!

![Screenshot_20210706-164928_cgeo](https://user-images.githubusercontent.com/87022956/124665608-eb4cfe00-de7a-11eb-9230-3099ee34d861.jpg)
![Screenshot_20210706-165057_cgeo](https://user-images.githubusercontent.com/87022956/124665636-f43dcf80-de7a-11eb-8f98-31e68d4ea5ac.jpg)
![Screenshot_20210706-165202_cgeo](https://user-images.githubusercontent.com/87022956/124665644-f738c000-de7a-11eb-9757-e0e2cb1057d9.jpg)

**Comment by moving-bits** [comment]
Looking at the first screenshot, this is exactly what I get with system font size setting set to "largest":

![image](https://user-images.githubusercontent.com/3754370/124667875-5533ca80-deb0-11eb-8877-b9b88a79a9fc.png)

Can you cross-check your system font setting?

The exact place for this is system and manufacturer-dependant, but should be something like Android system settings => display => advanced => font size

**Comment by Lineflyer** [comment]
This is definitely not the normal font size of this huge Samsung S20+ you are using....or we have a bug..

**Comment by moving-bits** [comment]
@stephr321:

On a Samsung S20 you should find those settings using the following steps:
- go to Android system settings (using the gearwheel shown when swiping down from top of the screen)
- display
- font size and style
- Samsung has a scale with 8 different settings (compared to the 4 described above, which is an emulated Google Nexus device), select a setting in the left half and see what happens to c:geo

**Comment by stephr321** [comment]
Is this what you are looking for?
![Screenshot_20210706-173056_Settings](https://user-images.githubusercontent.com/87022956/124669279-1ede5700-de80-11eb-806a-914fe4753aea.jpg)

**Comment by stephr321** [comment]
It I move it all the way to the left it does correct the problem but the font is unbearably small for other aspects of the ohone. Moving 1 back is more tolerable but all the same, the fonts were fine before the update.

**Comment by bekuno** [comment]
On my Note 8 the behavior is simular.
Size 4 is the standard size, the all texts look ok.
With size 5 the change to 4 is very clearly.

You can change the font size also for the current c:geo release. 
You will see a simular optical change from 5 to 6.
This is normal as most fonts are higher in the beta release.

**Comment by fm-sys** [comment]
Will be fixed together with issue  #11215

**Comment by stephr321** [comment]
This appears to have been closed but I still see the issue after the latest
update. Attaching photo.

**Comment by Lineflyer** [comment]
@stephr321 
In order to attach a photo you have to do it on the webpage, not possible via mail.

**Comment by Lineflyer** [comment]
Addon: It has been closed yesterday, while the current beta release is from two days ago. Its not yet contained.

**Comment by moving-bits** [comment]
@stephr321 
Are you using beta version, nightly or release version?
Above's fix will be included in most recent nightly only (for now).

**Comment by stephr321** [comment]
Yes I'm using beta version 2021.07.17-RC2
Perhaps it was not included there.
