### ISSUE TITLE
Font size feedbacks

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11124]
This is just a report after reading support mails and social media postings regarding our current beta version...no request to change, just for information and discussion for now.

There are quite some people who say "The fonts got so huge".

I think for most of them its just a "one time effect" until they get used to it (as for me). We have to endure that IMHO.

But there are also people with more specific reports like "The fonts are bigger than in other apps on my phone, thus reducing the global setting for font size makes it look OK in c:geo but other apps are to small to read then". (It might still be, that we are OK but the other apps are using to small fonts).

The follow up question from my side would only be:
Is there anything contained in the android guidelines what font sizes to use for headlines, normal text, etc. and do we follow those?
If yes, then we should stick with that (and rather improve the design at some place if something currently "looks ugly").

There are also some reports of cut off or invisible texts (preferable on small displays). I will open dedicated issues for those as soon as I have all details.

**Comment by Lineflyer** [comment]
I made a split screen setup (upper half: Example text in system font settings, lower half c:geo cache details)
I cannot tell for sure, but IMHO our standard text is a bit larger than what the Android menu (Google Pixel 3a - Android S beta) shows as standard text (lowest level).

![Screenshot_20210706-222740](https://user-images.githubusercontent.com/949669/124662761-852b9f80-dea9-11eb-831e-d335bcffcf6e.png)

**Comment by murggel** [comment]
For me the font size is ok, only in list-view IMHO it is too big. 
I looks like the cache-name has "title"-size (same size as the list-name in action bar) 

I would suggest to use a little bit smaller size for the cache-name.

**Comment by bekuno** [comment]
Comparition with system default size:
left: 2021.06.21, right: 2021.07.06-NB
![list_normal_2021 06 21-2](https://user-images.githubusercontent.com/32555742/124664710-20be0f80-deac-11eb-88fb-cfb8b21c44ea.jpg)![list_normal_2021 07 05_NB-2](https://user-images.githubusercontent.com/32555742/124664718-23b90000-deac-11eb-95c9-ba2e546c5253.jpg)

I also would suggest to use a smaller font size for the cache-name.

**Comment by moving-bits** [comment]
Lists are currently 20sp/16sp - with 16sp being the font size for primary default text (listing text etc.).

We could reduce that to 18sp/16sp, it would look like this:
|currently: 20/16|reduced: 18/16|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/124665844-8363db00-dead-11eb-9f24-4d3c248cc6ac.png)|![image](https://user-images.githubusercontent.com/3754370/124665868-8bbc1600-dead-11eb-9bbb-c67c0349d9ec.png)|

**Comment by wolverine007** [comment]
Or if possible add a setting where the user could select between small, medium and large for all used font sizes?

Small 18/16
Medium 20/18
Large 22/20

**Comment by eddiemuc** [comment]
If a quick fix is needed for the beta users, I recommend to set all text sizes using "dp" form now and take some time finding the best "sp" sizes (but not under the pressure of production problems)

**Comment by Lineflyer** [comment]
I dont think we need a quick fix, I mainly created this issue to collect feedback from beta users.

Maybe the reduced list size is already one good proposal...

**Comment by murggel** [comment]
I found some links for default font-size, but did not check yet with our current implementation.
 As far as I could see, 14sp is recommended for widgets with lot of text, 16sp for less text...

https://learnui.design/blog/android-material-design-font-size-guidelines.html


https://material.io/design/typography/the-type-system.html#type-scale


https://material.io/archive/guidelines/style/typography.html

**Comment by fm-sys** [comment]
Note also that we use different font sizes in different list views. E.g. the size for pocket queries seems to be much smaller...What if we use this size for the cache list as well?

**Comment by murggel** [comment]
Looks like same size, but the cache-list-item has more rows below it. So in some cases I have can only see 3 caches in the list without scrolling: long cache-name (3 lines) and long list names

![Screenshot_20210707-144816_cgeo.jpg](https://user-images.githubusercontent.com/70113341/124761951-a08ebd00-df32-11eb-8f81-424e78d97279.jpg)

So reducing the font size for the details as well could help or cut them off somewhere?

**Comment by moving-bits** [comment]
> Note also that we use different font sizes in different list views. E.g. the size for pocket queries seems to be much smaller...What if we use this size for the cache list as well?

This would be strange, as both pq list and caches list use the same definitions for textsizes: `textSize_listsPrimary` for the first line, and `textSize_listsSecondary` for the second line

> Edit: Or is it even the same size and just the color makes it looking more lightweight?

may very well be. I'll adjust colors to have primary in default color, and secondary in hint color in both lists

**Comment by moving-bits** [comment]
see #11135 for unifying text colors in lists

**Comment by moving-bits** [comment]
> So reducing the font size for the details as well could help or cut them off somewhere?

Only to a certain degree, if you are using large font size setting, as the view has (more or less) four columns, and direction and info columns at the right will always require a certain (not that low) amount of space.

**Comment by murggel** [comment]
> > So reducing the font size for the details as well could help or cut them off somewhere?
> 
> Only to a certain degree, if you are using large font size setting, as the view has (more or less) four columns, and direction and info columns at the right will always require a certain (not that low) amount of space.

But I am not using a large font-size... 4 out of 8...
Git looks not so big, did not checked if it's the same size

![Screenshot_20210707-204521_GitHub.jpg](https://user-images.githubusercontent.com/70113341/124824555-d2277880-df72-11eb-8ac4-d8855dfea798.jpg)

**Comment by Lineflyer** [comment]
For the lists (and some other places) the font size has been slightly reduced. I suggest to open dedicated issues for font/UI topics as they come in. This will help to improve particular aspects better than a global issue.
