### ISSUE TITLE
list view - some gui problems

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11127]
On my tests today with the list font problems I found some other problems.

1. the direction arrow is within the distance value

2. the TB and favorite count box has a fixed size

See this list element with the system maximum font size:
![list_element_problems-2](https://user-images.githubusercontent.com/32555742/124665364-ec971e80-deac-11eb-80bd-2f7c272bc4be.jpg)

3.  the headline has a fixed size - the second row disappears on higher font size:

![headline fixed size](https://user-images.githubusercontent.com/32555742/124667375-9a0b3180-deaf-11eb-96ae-7bb46bf33b26.jpg)

4. after the system font size or system language change the list name "Map" is changed to "c:geo":

![map list headline after size change](https://user-images.githubusercontent.com/32555742/124667525-cf178400-deaf-11eb-982d-661e6a7d5402.jpg)

**Comment by bekuno** [comment]
for point 3 see #11116

**Comment by fm-sys** [comment]
Let me add that other listviews have similar problems in the current beta...

![Screenshot_20210707_075522_cgeo geocaching](https://user-images.githubusercontent.com/64581222/124707207-cac38900-def8-11eb-94fd-5ab0fd5cd413.png)

**Comment by moving-bits** [comment]
I did a cross check with some other apps (e. g. Signal, Whats App and more): All of them simply truncate actionbar text if the font size gets too large. The layout reflow only changes in the app's main screen.

**Comment by moving-bits** [comment]
To give us some relief from UI stress: At least the first three points from the initial post are already happening the same way in currently released version 2021.06.23

**Comment by moving-bits** [comment]
> Let me add that other listviews have similar problems in the current beta...

see #11130 for several fixes for the pq list

**Comment by moving-bits** [comment]
> the direction arrow is within the distance value

see #11131 for some fixes for direction arrows

**Comment by moving-bits** [comment]
@bekuno 
Can we close this issue here?

Smoke-testing with current release I can no longer reproduce issues
- titlebar font size (is fixed size meanwhile)
- direction arrow (no longer hitting distance info)
- size of tb / favo / gcvote boxes (adjust accordingly)

**Comment by bekuno** [comment]
Errors are fixed, lets close.
