### ISSUE TITLE
Remove the 1000 caches limit from lists

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11132]
Quite some mails on support channel for the beta version where it turns out, that the "feature" of only showing 1000 caches per list leads to various followup problems:

- Not possible to delete all caches, have to delete all caches various times if the list if >>1000 items
- Sorting caches does not return correct results (in fact in only resorts the current 1000 shown but does not check others)
- Cache history does not show correct order of logs if the history is >1000 caches

I assume there could be even more hickups.

Instead of fixing all those followups I suggest to remove this limitation again (especially as I do not see a good reason for it, or is there any?).

**Comment by eddiemuc** [comment]
There is a setting "List Load Limit" in "Offline Data" to adjust or deactivate the list load limit:

![image](https://user-images.githubusercontent.com/6909759/124820344-a9e94b00-df6d-11eb-9959-d837d95989a3.png)

An easy way to handle this would be to set the default value to "unlimited"

When we remove this feature, we need an alternative solution for #9015, and I have frankly no other idea.

The sorting issue should not occur, I will have a look into that. Sorting should work also when working with limits (it is SQL-based and should correctly return the first x results according to sort also if result size is limited by x). Are there any specific sort criteria where this is happening? I checked "sorting by name" as well as "sorting by distance", and it seems to work correctly also with limited results

**Comment by Lineflyer** [comment]
I could reproduce it by opening my all caches list, which defaults to "by distance" and let it resort "by favorite". The first one was a cache with 10 favs, but I have some stored with >1000 favs for sure. Those only appeared after loading more.

**Comment by eddiemuc** [comment]
OK, there are actually a couple of issues in the SQl sorting:
* Name: ORDER BY is case sensitive, but local sorting is case-insensitive 
* Favorites: SQL search is ASC/DESC-reversed
* Distance: SQL distance search is not as exact as a real distance measure and thus 

Strange that this did not came up earlier, this stuff is in the nightlies for months now.

**Comment by ztNFny** [comment]
Only through this issue I found out about the "list load limit" setting. Inwas wondering why my map was so empty, not noticing that also thr list shows only 1000 items.
Suggestions:
1. Make it more obvious when the load limit is applied (both in list and on map)
2. Have this as a prominent item in changelog
3. Raise the default limit. As there was no limit before any limit will improve performance. And with e.g. 3000 a lot less users are likely to run into it accidentally.

**Comment by Lineflyer** [comment]
If we really need to keep it I would let it default to unlimited. But then we still need to fix the issues mentioned inktially

**Comment by fm-sys** [comment]
As pointed out in https://github.com/cgeo/cgeo/discussions/11123#discussioncomment-971929

The load limit should not be noticeable for users, which means that 
a) automatically load more caches when the user comes near to the bottom 
b) always use the full list for actions like "show as map" / "remove all" 
c) keep it at 1000 and remove the setting completely (users should not even need to think about whats happening in the background - or have you noticed, that WhatsApp, Gmail, and many more apps have such a load limit as well?)

**Comment by bekuno** [comment]
If we stay with the "load next 100 caches" button then there is a bug to fix: 
The list is reloaded and the scroll position is on top of the list, not on the last position. So you have once more scroll down to the end of the list to see the added entries.

**Comment by eddiemuc** [comment]
> As pointed out in [#11123 (comment)](https://github.com/cgeo/cgeo/discussions/11123#discussioncomment-971929)
> 
> The load limit should not be noticeable for users, which means that
> a) automatically load more caches when the user comes near to the bottom
> b) always use the full list for actions like "show as map" / "remove all"
> c) keep it at 1000 and remove the setting completely (users should not even need to think about whats happening in the background - or have you noticed, that WhatsApp, Gmail, and many more apps have such a load limit as well?)

I agree, and this was also my first implementation idea for #9015. But the complexity was too much so I reduced it to the current "search limit" - which, as you surely noticed, is simply a first implementation step towards a "smooth scrolling/reloading" approach. Note that this was quite complex to implement on its own! Still the complexity to go into "smooth scrolling" from this point forward would satisfy an own issue imho,

That means if this is really wanted by users. Right now I get the impression that people simply want their 10000+ cache lists to be loaded in one go (and live with poor performance / high memory consumption of that approach - see #9015)

**Comment by eddiemuc** [comment]
> Only through this issue I found out about the "list load limit" setting. Inwas wondering why my map was so empty, not noticing that also thr list shows only 1000 items.
> Suggestions:
> 
> 1. Make it more obvious when the load limit is applied (both in list and on map)
> 2. Have this as a prominent item in changelog
> 3. Raise the default limit. As there was no limit before any limit will improve performance. And with e.g. 3000 a lot less users are likely to run into it accidentally.

Yes, I was not aware that users have such large cache lists to deal with :-) On my phone, lists are filled far less than 1000 entries (except for the generic ones like 'All' or 'History', but I use those rarely). Also I was not aware that users constantly delete 1000+ cache lists from their phone :-)

The application of the load limit in list view is actually made visible in the header using the normal "x of y" subtitle which c:geo users should be used to. Same indication is used e.g. for filtering, if limitation is due to load limit I added a little plus sign. Like the following screenshot (my load limit is set to 7 for testing purposes):

![image](https://user-images.githubusercontent.com/6909759/124868647-5522f000-dfc0-11eb-940e-9210819e6e3d.png)

**Comment by eddiemuc** [comment]
PR #11142 will fix the sorting bugs I could find so far, and it also deactivates "list load limits" by default. So I guess it will put the topic at ease for the foreseable future.

**Comment by MagpieFourtyTwo** [comment]
> Strange that this did not came up earlier, this stuff is in the nightlies for months now.

Sorry, did in fact not really test it but set it to "unlimited" really soon, cause a) it was told to be SQL based, which is usually thoroughly tested anyway, b) cause there was no big difference in performance at all, and c) it was kind of annoying to have to click "show more" all the time - nevertheless, although my setting is "unlimited" from the very first day, I sometimes got the "show more" message, as I realize now - perhaps you may check this, too ... will see if I can get a reproducible scenario (but I'm not too optimistic, cause it happened really seldom).

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo I am confused: #9015 was fixed by that which was your issue. If you disabled that feature, where was your original problem. 
If the limit is not really needed or just covers a rare edge case we might rather remove it?

**Comment by MagpieFourtyTwo** [comment]
IIRC (a lot has happened since then) the problem was de facto solved by @eddiemuc's revision of the search, filter and display strategy, namely by switching from memory- to SQL-based search and filtering. The list limit itself was just an additional tweak, which then - at least on my hardware - turned out to be not really necessary anymore ... 

Therefore, I would be fine with it being removed again. OTOH, it can perhaps still be helpful on medium or low hardware ... so it might be best to set the default to ``Unlimited`` for now and wait for reactions from the community. And if there are no complaints about performance or crash problems with the lists for a while, then it can still safely be removed ...?

**Comment by eddiemuc** [comment]
At the same time (and yes, I had this in my mind from the beginning...) the load limit implementation is a first step towards loading lists continuously as you scroll down (like you know from other apps dealing with long lists e.g. email or chat clients). @fm-sys mentioned this earlier too.

Also I agree with@MagpieFourtyTwo, e.g. on devices with low memory something like loading 10000+ caches might be a problem - and most of the time it is not even needed (how often will you really scroll to the end of such lists?)

I would thus like to keep it, but defaulting to off (as it is implemented right now)

**Comment by Lineflyer** [comment]
I think we can close here (as the default was changed to unlimited) and open folllowup issues if we may find remaining bugs in limited lists.
