### ISSUE TITLE
maps.me navigation not available

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11134]
Reported by some beta users, could not test it yet.

With the last version I was able to navigate with "MAPS.ME". This does no longer work.

**Comment by fm-sys** [comment]
Probably, we need to add maps me to the `query` section  in the manifest

**Comment by Lineflyer** [comment]
More detailed user report:
maps.me is shown as navigation option, but when I click it there is a message box, that this app is not installed with a link to install it.
Clicking the link gets to a 404 page

AFAIR we use a kind of API plugin towards maps.me  (some code on our side). Maybe this code has problems with API 30.

The 404 is for sure a problem on their side as https://maps.me/get is linked in that box but not exisiting on their server.
But as the user has maps.me installed, the box should not show up at all.

**Comment by Lineflyer** [comment]
+3 from support mail!

**Comment by bekuno** [comment]
see https://github.com/cgeo/cgeo/blob/release/mapswithme-api/AndroidManifest.xml
package="com.mapwithme.maps.api"

Hope that this is the correct one.

**Comment by moving-bits** [comment]
Thanks, will prepare a PR for it, so that we can try.

**Comment by bekuno** [comment]
Or:   com.mapswithme.maps.pro 
from https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro

**Comment by bekuno** [comment]
By the way, I think that OSMAND was also supported?
See net.osmand - from https://play.google.com/store/apps/details?id=net.osmand

**Comment by moving-bits** [comment]
will add it as well...

**Comment by bekuno** [comment]
and there are more more apps at main/src/cgeo/geocaching/apps/navi - 

=> Oruxmap https://play.google.com/store/apps/details?id=com.orux.oruxmapsDonate

**Comment by moving-bits** [comment]
more to come?

**Comment by bekuno** [comment]
not for now.
