### ISSUE TITLE
material design SVG icons

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11139]
For compact icons map view the dot_....png files are used. Some of those only exist in drawable-mdpi which causes those icons to look quite bad.

Missing icons:
dot_found.png
dot_waypoint_flag.png
dot_waypoint_pkg.png
dot_waypoint_reference.png
dot_waypoint.png

**Comment by moving-bits** [comment]
Can we change those dot markers to svg? (And would that fit into the mechanism which builds the map markers?)

**Comment by ztNFny** [comment]
I'm using SVGs (for all the map icons) in my custom build, so that works. I'm attaching my icons, they are based on a certain platforms colors palette
[dots.zip](https://github.com/cgeo/cgeo/files/6779722/dots.zip)

**Comment by moving-bits** [comment]
@ztNFny 
They look nice. May we include your icons in c:geo?

**Comment by ztNFny** [comment]
Sure. It's 2 simple circles, nothing more.
Maybe you want to adjust the colors a tiny bit to differentiate from GC colors though? Its their exact colors right now. Not sure about the politics there.
I can also do a PR if you'd like.

**Comment by moving-bits** [comment]
> Sure. It's 2 simple circles, nothing more.

great!

> Maybe you want to adjust the colors a tiny bit to differentiate from GC colors though? Its their exact colors right now. Not sure about the politics there.

we could use the colors from current dot pngs

> I can also do a PR if you'd like.

sure, thanks. Please base it on current `release` so that we can include it in our next beta.

**Comment by ztNFny** [comment]
Will do, but probably after the weekend. Got some caches to find ;-)
I'll do with and without white circle, using the current colors. Then you can pick one. 
I also modded a lot of other icons, but most of them really based on GC ones. Would you guys be open to new marker icons for note, custom coords, found, ... based on material design icons? Well ... that'd probably turn into a whole redesign of map markers campaign, including flat design, then... Wouldn't want to start working on such a thing without some decision this is the way to go because design takes ages... 
Attaching a screenshot of my current mod with GC type icons and material icons for everything else.
![Screenshot_20210709-225607](https://user-images.githubusercontent.com/1258173/125135284-059c0b80-e109-11eb-90a0-53fc7157f520.jpg)

**Comment by moving-bits** [comment]
This looks nice! I'll discuss that in our next dev meeting and come back to you.

Regarding the dot markers: I like the variant with the small white circle around it - makes them more visible especially on a crowded / very detailed map.

**Comment by moving-bits** [comment]
Hi @ztNFny, we discussed this in our dev meeting and really appreciate the "material design" look of you proposed map icons! But we would prefer to not copy any geocaching platform's original icons. Any chance that you could create your own icons, having a similar material design look (flat, colored background, easy to recognize type indicator etc.)?
(This is about the map/waypoint icons only, the dot markers are fine as discussed above.)

**Comment by ztNFny** [comment]
The waypoint icons are already original. For cache types I'll.try to come up with something similar but original.
Is the cgeo icon availble as svg somewhere? I'd like to base at least the tradi off of it.

**Comment by ztNFny** [comment]
So i started working on this and already ran into a lot of questions ...

- There's some elements (e.g. marker.png) that are currently not supported as SVG (being used as BitmapDrawable in the code)
- The type icons are offset from the top to place them centered inside the marker, that's quite an ugly workaround, would be better if they'd just be centered.
- How close/far away from GC.com do you want to be?
- I could use the cgeo icon as svg, in this repo it's only as png.
- I can't find any usages of marker_archive, marker_note, marker_owner_maintenance (in the code there are, but can't find them in real use)
- Where's dot_black used?
- dot_waypoint is never used (see my other issue)
- where should i share my progress to get feedback? Icons themselves I could put in my fork, but bundled with issues like the centering that won't really help.

@moving-bits is there some way outside of this issue to get in contact with you? Maybe it's easier to have a short call about all of this rather than typing lots of text here.

**Comment by ztNFny** [comment]
![2021-07-12_20-11-39](https://user-images.githubusercontent.com/1258173/125335956-6fa4f280-e34d-11eb-9aff-d909e39e19fb.png)

**Comment by ztNFny** [comment]
![2021-07-12_20-13-40](https://user-images.githubusercontent.com/1258173/125336111-aa0e8f80-e34d-11eb-94fc-1c22ccfee683.png)

**Comment by moving-bits** [comment]
> @moving-bits is there some way outside of this issue to get in contact with you? Maybe it's easier to have a short call about all of this rather than typing lots of text here.

Sure, you can contact me via our support email address (support@cgeo.org), and we can organize a Jitsi then.

**Comment by fm-sys** [comment]
Looks really good already. Just the found smiley seem to be not that happy anymore ;-)

**Comment by ztNFny** [comment]
> Looks really good already. Just the found smiley seem to be not that happy anymore ;-)

He's in a hurry to getnto the next cache 😉

**Comment by ztNFny** [comment]
I'm sharing my progress at https://ztnfny.github.io/cgeoicons/index.html
Feedback welcome, keep in mind it's WIP

**Comment by ztNFny** [comment]
@moving-bits what do you think about for disabled caches instead of using a different marker to greyscale the icon instead? with SVG Drawables that'd be easily possible.

**Comment by fm-sys** [comment]
Although I'm not mentioned: Sounds good 👍

**Comment by ztNFny** [comment]
> Although I'm not mentioned: Sounds good

want to implement it? ;-)

It could be either done by using Drawable.setColorFilter() to convert all (type) icons to greyscale automatically or by creating the SVGs manually (better contrast as it can be manually tuned) and extending the enum in CacheType with another drawable.

**Comment by fm-sys** [comment]
A color filter probably would already be sufficient and is easier to maintain than a second drawable

**Comment by ztNFny** [comment]
I'll use this comment as a list of various issues encountered during the implementation, just so they don't get lost:

- Direction icon in cache list doesn't support SVG (compass_arrow_mini_black / compass_arrow_mini_white)
- Marker backgrounds don't support SVG (marker.png)
- Marker placement should be rewritten to center everything with whitespace around the marker background
- Add missing cache type icons (in work in my fork)
- wrong marker-icon used for needs archive/needs maintanance offline logs #11226 
- Implement grey-scale-filter for disabled icons instead of changing the background marker.png
- remove dead code for dot_black
- dot-icons not used for waypoints #11141

**Comment by moving-bits** [comment]
Here are some first screenshots with current (intermediate) state of flat icons:

![image](https://user-images.githubusercontent.com/3754370/125676829-b08bdef7-08f7-4c1f-97d8-c064d4f2836c.png).![image](https://user-images.githubusercontent.com/3754370/125676847-bae73232-47c0-46cb-bdaf-6cbb15ecd9d0.png)

**Comment by ztNFny** [comment]
a first building version is available at https://github.com/ztNFny/cgeo/tree/dotMarkerIcons for those who dare to take a look
still very rough around the edges, but early feedback would be appreciated

also for a better look at the icons check https://ztnfny.github.io/cgeoicons/index.html

**Comment by moving-bits** [comment]
Looking at the screenshots (or your linked web page) I really like the look of the new icons.

Some quick feedback:

Only drawback I can see at a quick glance is that I find some of the inset icons hard to recognize easily - they are too detailed and low-contrast for their size. In my screenshot above this applies this to both "has user note" (bottom left) and "has user-modified coords" (bottom right) insets.

Also the two "found" insets seem to be larger than the two mentioned before.

And please be aware that there needs to be a bit more free space between upper inset row and lower inset row, as there may be list markers positioned at vertical center / horizontal left (or right). Those list markers should get app. the same size as the insets already shown above.

**Comment by ztNFny** [comment]
> Only drawback I can see at a quick glance is that I find some of the inset icons hard to recognize easily - they are too detailed and low-contrast for their size.
your screenshot doesn't reflect the current size (and i'm still far away from having tweaked the sizes). That said, I think they are fine, there's not much detail in there (it's a pen after all - the flag has some details inside the flag, but those shouldn't be relevant for recognizing it as a flag). And as those positions are never used for other markers they should work just fine.
The whole marker (not just the icon in the marker) has a higher visibilility than the current ones due to being a colored circle. If you look especially at the "has user note" pen today that one is hardly visibile.

> Also the two "found" insets seem to be larger than the two mentioned before.
Exactly the same size, though there's a "felt" imbalance due do the heavier colors in the smileys

> And please be aware that there needs to be a bit more free space between upper inset row and lower inset row, as there may be list markers positioned at vertical center / horizontal left (or right). Those list markers should get app. the same size as the insets already shown above.

you have to decide whether you want the markers larger or smaller :-P

**Comment by moving-bits** [comment]
@ztNFny would like to get some feedback from us for the various icons created so far. You can find the current state at https://ztnfny.github.io/cgeoicons/index.html. Please be specific as possible, e. g. "I prefer variant #1 for type multi over variant #2, because ...". I guess it's easiest to simply post our comments here in this issue. Thanks!

**Comment by ztNFny** [comment]
To see them in action build https://github.com/ztNFny/cgeo/tree/dotMarkerIcons

**Comment by Lineflyer** [comment]
Thanks for your repo links.. Looks already very modern and nice.
Will try it out and report back here.

Some insights for others watching the thread:
![Screenshot_20210725-233420](https://user-images.githubusercontent.com/949669/126914257-3ba8d063-43d7-457a-af6a-69cfd7bc599d.png)
![Screenshot_20210725-233503](https://user-images.githubusercontent.com/949669/126914258-12fa0cc2-f77f-4f3c-8119-53aacbf5ae4a.png)
![Screenshot_20210725-233605](https://user-images.githubusercontent.com/949669/126914259-383e3ec1-50b0-41db-bfc1-824bbf187d22.png)
![Screenshot_20210725-233226](https://user-images.githubusercontent.com/949669/126914261-dac39964-9b74-4180-801f-960059c54993.png)
![Screenshot_20210725-233358](https://user-images.githubusercontent.com/949669/126914262-09a3cfd9-9aa1-4bc5-8eff-3ca2b39470e6.png)

**Comment by Lineflyer** [comment]
Some first thoughts after some minutes of looking into it (more to follow):
- As written above I really really like the consistent style
- The letterbox icon should IMHO use the lighter blue from earth / virtual. Otherwise letterboxes tend to "get lost" between the mysteries
- The disk icon overlay (saved cache) is barely visible. It should maybe also use some kind of outlined/filled icon

**Comment by fm-sys** [comment]
> The disk icon overlay (saved cache) is barely visible. It should maybe also use some kind of outlined/filled icon 

Maybe using a round overlay as for found, PN etc. to stay consistent?

**Comment by fm-sys** [comment]
Another observation:
`marker_calendar` currently uses the same red background as "needs maintenance" and "archive". Could we use a different more neutral background (e.g. blue, white or maybe green)?

**Comment by ztNFny** [comment]
> * The letterbox icon should IMHO use the lighter blue from earth / virtual. Otherwise letterboxes tend to "get lost" between the mysteries

The idea is to have the colors reflect groups of caches. Light blue is "virtuals": EC, Virtual, Webcam. Blue is "caches where you have to do something to get the final coordinates", so Mystery, WIG, Letterbox.
By that reasoning Letterbox could also be orange as (at least classic LBs) you have to follow a track, but putting them in the virtual-group would be wrong imho. Why didn't I make them orange then? Well, I think the biggest user group of c:geo is GC users and they are used to WIG and LB being blue.
What could be done is to move Labs into the virtual-category, thus freeing up purple for WIG+LB.
So the questions that have to be answered: Do we want to deviate from the GC colors? Are Labs or WIG+LB more important (= have their own color)?

> * The disk icon overlay (saved cache) is barely visible. It should maybe also use some kind of outlined/filled icon

This is completely by intention, let me explain my train of thought: Usually I'm geocaching with a list stored offline in c:geo, so every cache has the disk icon -> no information value. When I'm visiting somewhere I enable live map, so no cache has the disk icon -> no information value
Only when you have a mix of stored and live-map caches does the icon get any meaning. So e.g. you have a list of a city you're visiting and then checking live-map for caches that were published since your last update. (In that situation I'd argue that actually not-stored caches should be more prominent than stored ones!)

So: Most of the time the icon conveys no message. On the other hand all the other markers (corrected coordinates, offline log, ...) are quite important. That's why I chose to go with bright big markers for those and for the stored state a icon "that you can see if you want to see".
We can of course discuss about the exact size and shape of the icon, but I really would recommend to make it not like the other markers.

Imho the ideal solution would be: Only show an icon when there's both stored and unstored caches shown at the same time - and then probably the unsaved ones should have the icon.

> `marker_calendar` currently uses the same red background as "needs maintenance" and "archive". Could we use a different more neutral background (e.g. blue, white or maybe green)?

The reason I went with red is that's the event-color, so having the WA icon in that color only makes sense. 
I'll give green a try - that will then conflict with Owner Maintanance, but just like NM / Archive markers this will rarely be seen on the map as they are for stored offline-logs of those types only - I think in the end we should go for the combination of red event icon + some-color WA marker that looks best, ignoring conflicts with those hardly-used markers.

(btw, you can easily change colors in the vector drawables yourself if you want to play around, just change the hex colors codes)

**Comment by Lineflyer** [comment]
Letterbox color:

> The idea is to have the colors reflect groups of caches. Light blue is "virtuals": EC, Virtual, Webcam. Blue is "caches where you have to do something to get the final coordinates", so Mystery, WIG, Letterbox.
> By that reasoning Letterbox could also be orange as (at least classic LBs) you have to follow a track, but putting them in the virtual-group would be wrong imho. Why didn't I make them orange then? Well, I think the biggest user group of c:geo is GC users and they are used to WIG and LB being blue.
> What could be done is to move Labs into the virtual-category, thus freeing up purple for WIG+LB.
> So the questions that have to be answered: Do we want to deviate from the GC colors? Are Labs or WIG+LB more important (= have their own color)?

IMHO we do not need to strictly follow the colors of Groundspeak. Still going into the same direction makes sense, as this is what users are used to (like a green traditional and an orange multi).
I have recognized, that you used the color groups and I think they make sense as you grouped them. Maybe its only a thing to get used to over time.

Maybe indeed the compromise would be to let letterboxes go into the multi group (=orange)?

The purple color for adventures is OK IMHO...this is a totally different group as its no "legacy" Geocaching. If we still do not want an own color, those would be in the virtual group for sure, but I am fine with the purple as well.


Disk icon:

> This is completely by intention, let me explain my train of thought: Usually I'm geocaching with a list stored offline in c:geo, so every cache has the disk icon -> no information value. When I'm visiting somewhere I enable live map, so no cache has the disk icon -> no information value
> Only when you have a mix of stored and live-map caches does the icon get any meaning. So e.g. you have a list of a city you're visiting and then checking live-map for caches that were published since your last update. (In that situation I'd argue that actually not-stored caches should be more prominent than stored ones!)
> 
> So: Most of the time the icon conveys no message. On the other hand all the other markers (corrected coordinates, offline log, ...) are quite important. That's why I chose to go with bright big markers for those and for the stored state a icon "that you can see if you want to see".
> We can of course discuss about the exact size and shape of the icon, but I really would recommend to make it not like the other markers.

I can follow your argumentation, but this is totally depending on use cases.
I deem the stored information very important most of the time as I store some caches only (e.g. for a certain area). While being there I then use the live map and can easily distinguish, which ones I explicitly saved and what else is out there.

> Imho the ideal solution would be: Only show an icon when there's both stored and unstored caches shown at the same time - and then probably the unsaved ones should have the icon.

Actually, we do this already for one special case:
We do show all overlays also in lists of stored caches, except the stored icon which is indeed superfluous in that case.
We could of course expand it to the map, but this would be totally unexpected by users compared to the current mode.
I would not recommend to do that.

IMHO the map should always show the stored icon for stored caches and it should be better visible, not necessarily as prominent as the other overlays, but at the moment I can't identify the disk at all when looking at the map. I do only see a bunch of pixels.

**Comment by Lineflyer** [comment]
Some more  comments:
- I would love to see the "offline logged" smiley a bit more red than orange to better distinguish it from "found online".
- The disabled multi uses another symbol than the active multi (for the build on your branch).
- For the user defined cache the icon has almost no contrast. Before it was not so important, that users can read "cgeo" in it as it was easily to be identified as the c:geo logo. This is no longer the case, thus I think its not yet a "speaking icon". Not sure how to improve if we stick with two colors only.

**Comment by ztNFny** [comment]
> * I would love to see the "offline logged" smiley a bit more red than orange to better distinguish it from "found online".

It's pretty much the same colors as today though? See https://ztnfny.github.io/cgeoicons/index.html
The problem is, there's no "reder" orange in the color palette that I'm using - other than red.
Should the Found Smiley be more yellow then?

> * The disabled multi uses another symbol than the active multi (for the build on your branch).

For multi (and WIG) I'm playing around with the different icons, using one the one day, another the next. I'm too lazy to change them everywhere ;-)

> * For the user defined cache the icon has almost no contrast. Before it was not so important, that users can read "cgeo" in it as it was easily to be identified as the c:geo logo. This is no longer the case, thus I think its not yet a "speaking icon". Not sure how to improve if we stick with two colors only.

Yeah, the "cgeo" text is almost invisible. But without introducing a third color into the icon I don't see a way to make it more visible.
Options:
- Stick with the current and decide the background-color is enough to differentiate it
- Use a third color ( I really don't like that!)
- use another icon. Maybe a "person"-icon to reflect it's a user-created one or the "c:geo" text without icon?

> IMHO the map should always show the stored icon for stored caches and it should be better visible, not necessarily as prominent as the other overlays, but at the moment I can't identify the disk at all when looking at the map

Could you play with the size in https://github.com/ztNFny/cgeo/blob/dotMarkerIcons/main/res/drawable/marker_stored.xml please and let me know which size you would prefer? android:width="14dp" / android:height="14dp" is what you want, just change that to be a little larger.
I'll also try playing with the icon a bit, the border still has some "gaps" that make it a bit harder to see and also will try to increase the contrast. The current design is really with my usecase in mind (be unobstrusive), if that doesn't fit the common usecase I'll redesign it.

> Maybe indeed the compromise would be to let letterboxes go into the multi group (=orange)?

You only have an issue with the color of the LB icon and not WIG?

**Comment by Lineflyer** [comment]
User defined caches:

> use another icon. Maybe a "person"-icon to reflect it's a user-created one or the "c:geo" text without icon?

That could be a better option. c:geo orange with white text c:geo (like for mega/giga) maybe?!

Multi disabled:

> For multi (and WIG) I'm playing around with the different icons, using one the one day, another the next. I'm too lazy to change them everywhere ;-)

I almost thought so, but just wanted to make you aware in case it was not intentional.

Stored icon:

> I'll also try playing with the icon a bit, the border still has some "gaps" that make it a bit harder to see and also will try to increase the contrast. The current design is really with my usecase in mind (be unobstrusive), if that doesn't fit the common usecase I'll redesign it.

I think the size is OK, it just looks much smaller than others due to the missing border (circle).
For the usecase: Yes, IMHO we should have it clearly visible. Its already less intrusive as you decided for a black and no "alert color" like the others. That's fine.

**Comment by Lineflyer** [comment]
From those icons where @ztNFny provided several proposals I marked (underlined green) my personal preference below. However I think all of those are perfectly fine, its just a matter of taste.
![types_lineflyer](https://user-images.githubusercontent.com/949669/126975212-48f22f68-5dba-42a8-9daf-9d7e71802a2e.png)
![waypoints_lineflyer](https://user-images.githubusercontent.com/949669/126975216-07269299-a7ee-44cc-bc0e-8aa91be94ef2.png)

**Comment by ztNFny** [comment]
> That could be a better option. c:geo orange with white text c:geo (like for mega/giga) maybe?!

Will be low-contrast - but of course the small text currently has even less. I'll create text-based and also a person-icon and then we can test it.

> I think the size is OK, it just looks much smaller than others due to the missing border (circle).

Sorry, I'm not sure what you're proposing. If I add a circle then it'll be as big and prominent as the other markers. A circle with a different size looks stupid, everyone will think it's a bug - unless the circle size is very very obviously different, like half the size, but then it's too small.
That's why I proposed to increase the size of the disk icon instead, to make it more prominent without making it as prominent as the others.

> From those icons where @ztNFny provided several proposals I marked (underlined green) my personal preference below. However I think all of those are perfectly fine, its just a matter of taste.

No opinion on Multi? That one I'm struggling the hardest with... When evaluating those icons you really have to do that on your phone though, the impression on a desktop monitor is quite different due to pixel density.

**Comment by Lineflyer** [comment]
> No opinion on Multi? That one I'm struggling the hardest with... When evaluating those icons you really have to do that on your phone though, the impression on a desktop monitor is quite different due to pixel density.

Ups..missed that.
I like the first one as it really shows the typical multi case (going through stages until final). The second would be my second choice. The third looks nice as well but not so intuitive.

**Comment by ztNFny** [comment]
I've added (to the website) variants for type_cgeo and marker_found.
For type_cgeo I've use the cgeo font, not Fira Sans like on the other icons, as it doesn't make sense to set the text in another font than the logo. However I don't think that one works. Maybe the person for "user-created" isn't too bad though?

**Comment by ztNFny** [comment]
@Lineflyer have a look at marker_stored in https://github.com/ztNFny/cgeo/commit/a8e5a78eed66a38e2b005910f94963738e907471 please

**Comment by moving-bits** [comment]
I generally agree with @Lineflyer's choices marked in https://github.com/cgeo/cgeo/issues/11139#issuecomment-886580940.

Some more feedback for the type icons:
- For the user-defined cache type I would choose the "person" icon (third variant) , but could happily live with the first variant ("tradi in orange") as well.
- I don't understand the "maze" icon. To me it looks like a museum symbol, but should rather be a maze ("Irrgarten"). Or did you design it to reflect the exhibition aspect of a maze cache?
- For the "whereigo" icon the second variant generally looks ok to me, but would it be feasible to make the triangle a bit larger? (probably forcing the inner circle to become a bit larger as well)

Next I have seen that you started working on the connector marker icons (backgrounds / frames) as well. Using greyish type icons for disabled icons seems to work well, so we don't need the "_disabled" variants of the markers any longer.
marker and marker_oc look ok to me, for marker_other I would prefer the "six corner" variant over the "eight corner", as the letter easily gets associated with a stop sign, which would be misleading.

Am I right, that the "background" color of the type icons will fill the markers inside?

**Comment by ztNFny** [comment]
> Am I right, that the "background" color of the type icons will fill the markers inside?

No, the "type_.." is a round icon, being overlayed on whatever is beneath it. If you want it filled (like have a colored square for OC) this would require a dynamic creation of all the icons with an additional step compared to now:
Layer 1: Marker,
Layer 2: Marker background, shape depending on connector
Layer 3: Icon (the white part)

> * I don't understand the "maze" icon. To me it looks like a museum symbol, but should rather be a maze ("Irrgarten"). Or did you design it to reflect the exhibition aspect of a maze cache?

I went with "exhibit" for now as I didn't feel like spending too much time on an icon only used every other year. And other than the name it never was a Maze ...

**Comment by Lineflyer** [comment]
> @Lineflyer have a look at marker_stored in ztNFny@a8e5a78 please

This stored icon is much better now!

> I've added (to the website) variants for type_cgeo and marker_found.

The icon with "cgeo" in it is my favorite and the lighter marker_found is perfect as well. Now its better to distinguish between offline_found and found.

**Comment by Lineflyer** [comment]
@ztNFny The different shapes depending on cache source is not yet part of your branch, is it?

**Comment by ztNFny** [comment]
> @ztNFny The different shapes depending on cache source is not yet part of your branch, is it?

No, I didn't think of this before that comment. I actually liked the round icons in non-round markers when I tried them.
I'll create some screenshots with non-round icons in non-round markers to see whether that looks any good.

**Comment by murggel** [comment]
I also generally agree with @Lineflyer's choices marked in #11139 (comment) amd the icon with "cgeo" in it .

For me the full-colored marker - I am not yet sure about it. e.g. the "has personal note" is for me hard to recognize - but to be honest, I only tried on emulator. 

I tried with inverted  colors (colored circle and motive, white background - instead of colored circle and background and white motive) but I am not satisfied as well. It makes it a little better to recognize the motive, but harder to recognize the color.

![image](https://user-images.githubusercontent.com/70113341/127052003-1620f180-852c-41f4-9067-b72afe26aedb.png)

![image](https://user-images.githubusercontent.com/70113341/127048409-7e98bc17-2a2c-49ca-a285-06b6c8867eb7.png)

**Comment by ztNFny** [comment]
> For me the full-colored marker - I am not yet sure about it. e.g. the "has personal note" is for me hard to recognize - but to be honest, I only tried on emulator.

The simple shape of a pen is somewhat hard to recognize, true. But after you've once realized what an icon in a specific position means you'll mostly go by that: Green dot in lower left -> note, Blue do in lower right -> corrected coords.
That's why I think having them full-color is quite important in terms of usability. Look at recent Google apps where every icon is the same color - it takes ages to find the correct one as your brain has to recognize each icon whereas with these colors you don't even have to care about the icon.
That said of course the icon should be as recognizable as possible of course, so if you have some sugestions other than the pen they're welcome.

> @ztNFny The different shapes depending on cache source is not yet part of your branch, is it?

is there some test GPX with caches considered other (non-GC, non-OC) by c:geo I can use for testing?

**Comment by ztNFny** [comment]
> Am I right, that the "background" color of the type icons will fill the markers inside?

Here's a preview of what that'd look like, implemented with some ugly hacks as an experiment in https://github.com/ztNFny/cgeo/tree/backgroundShape I think its nice and we should go for it. 
![image](https://user-images.githubusercontent.com/1258173/127744168-eca518f3-9ce5-49c1-bc92-0ef5dba898bf.png)

The implementation will require an additional layer in MapMarkerUtils, to be inserted depending on the Connector + CacheType, after marker and before icon.

**Comment by moving-bits** [comment]
> Here's a preview of what that'd look like, implemented with some ugly hacks as an experiment in https://github.com/ztNFny/cgeo/tree/backgroundShape I think its nice and we should go for it.

Looks really nice! Thanks for adding those backgrounds.

**Comment by Lineflyer** [comment]
> Here's a preview of what that'd look like, implemented with some ugly hacks as an experiment in

This looks more than OK.
The hexagons look a bit unusual at first sight...but hey, those would probably be as custom marker for some very specific geocaching connector.
Most commonly used will be the round for GC and the squared for OC which look perfect.

**Comment by ztNFny** [comment]
The rewrite for the additional levels is getting more complicated than I though, so I'd like to discuss my proposal here first:

createCacheMarker():
Layer 1: if (map) draw pin
Layer 2: draw marker, depending on connector
Layer 3: draw background, depending on connector + cache type + disabled state
Layer 4: draw icon
Layer 5: archive overlay
Layer 6: markers as they are today

Reason for Layer 1/2: The background (white circle/square) should be shown everywhere (unlike today where only the icon is shown), but other than on map there shouldn't be a pin
Layer 3 takes care of the colored background with the shape depending on the GC connector. This could either be seperate drawables (1 for each color and connector type) or tinted drawables (1 for each connector type) - imho tinting would be better. All disabled get the same color, independent of cache type.

More or less the same goes for createWaypointMarker().

Are there any volunteers to implement this? ;-)


For dot-icons, should they also follow the shape? Would be feasible if the general approach is cleanly implemented.

**Comment by fm-sys** [comment]
Note, there was even another layer - the orange "notReliable" marker... But as it is no longer used since years, I will remove it in #1142.

**Comment by moving-bits** [comment]
> EDIT: Nvm, I think I found a good approach to handling the different background shapes, it's in my branch

Haven't looked it up yet in the code, but cool that you found a solution!

> Open question: For dot-icons, should they also follow the shape? Would be feasible if the general approach is cleanly implemented.

IMHO this is not necessary, as the "small dots mode" is mainly for getting a quick overview, so a rough indicator for cache type (=> color) should be sufficient. But I'm open for discussion - what do others think?

**Comment by ztNFny** [comment]
Some icons aren't properly centered in all the cases:
![image](https://user-images.githubusercontent.com/1258173/128645109-8ba73754-c745-404f-b363-f6f42fc75cf1.png)

**Comment by Lineflyer** [comment]
One question I missed to ask today in our meeting:
Do the new icons have the same total size as the old icons.
The comparison view looks like their are much bigger, but this is maybe only due to the missing pointer background on for the old ones on that page?!

![image](https://user-images.githubusercontent.com/949669/128645401-1c22ffa7-df48-4ffb-b5d1-8240c6a10deb.png)

**Comment by ztNFny** [comment]
Same size, on the map. That site is comparing apples with oranges actually (due to one having the marker, the other not)
However in the end the size might seem larger in some cases as icons now always need the background (e.g. in filter dialog)

**Comment by moving-bits** [comment]
> Some icons aren't properly centered in all the cases:

Hm, actually I don't see the displacement for the earthcache symbol :-(

To retest, I've copied the screenshot you've provided into a graphics program, and counted the whitespace pixels - it's as close to being centered as technically possible: top 16px / bottom 15px / left 14 px / right 15 px in this case.

**Comment by ztNFny** [comment]
> > Some icons aren't properly centered in all the cases:
> 
> Hm, actually I don't see the displacement for the earthcache symbol :-(
> 
> To retest, I've copied the screenshot you've provided into a graphics program, and counted the whitespace pixels - it's as close to being centered as technically possible: top 16px / bottom 15px / left 14 px / right 15 px in this case.

It's that 1px offset  that im talking about. I realize with the current implementation only int offsets are possible - and that's exactly the problem. Depending on device dpi also floats would be needed.
Or we need to make sure that the base size (derived from the marker) is always a multitude of 2 so all calculations return an int.

**Comment by moving-bits** [comment]
> It's that 1px offset that im talking about.

But how to avoid this? When finally drawing an image, one has to either color a pixel or not, there is no in-between (except for fiddling with ARGB values, which Android already does)

> I realize with the current implementation only int offsets are possible - and that's exactly the problem. Depending on device dpi also floats would be needed.

Why? AFAIK we are calculating on pixels already, not virtual pixels or some other entity which gets converted to actual pixels afterwards, so a "half-pixel" would not make sense.

**Comment by ztNFny** [comment]
If you move a layer 0.5 px you'll end up with some alpha channel on the sides, that's happening all the time when drawing an image. There's not just blue and white pixels in there but many inbetweens.

The question is whether there's another method provided by the Libraries (or a a different lib) that provides the same Layer building but with float positions.
If not we'd have to go for the other option i mentioned, to make sure the base drawables (pin, marker. Backgound, icon) are all drawn with even or odd pixel size, not the mixed it currently is in some cases

**Comment by moving-bits** [comment]
> If you move a layer 0.5 px you'll end up with some alpha channel on the sides, that's happening all the time when drawing an image. There's not just blue and white pixels in there but many inbetweens.

I know, and that's what happening already here (that's what I meant with "fiddling with ARGB values").

> The question is whether there's another method provided by the Libraries (or a a different lib) that provides the same Layer building but with float positions.

We are using `setLayerInset` from the Android system's graphics lib. AFAICS there's no float-supporting counterpart.

> If not we'd have to go for the other option i mentioned, to make sure the base drawables (pin, marker. Backgound, icon) are all drawn with even or odd pixel size, not the mixed it currently is in some cases

You mean something like: Calculating their actual size in px for the specific display, and then increase their sp-size accordingly, if there is an odd px-result?

As we are talking about the main marker/icons etc., not about the actual insets, what about the following approach: Make marker, background and icon all have identical size in svg by adding padding as needed, so there is no pixel-difference when layering them above each other.

**Comment by ztNFny** [comment]
> We are using `setLayerInset` from the Android system's graphics lib. AFAICS there's no float-supporting counterpart.

I'm sure we're not the only ones with this issue, would assume there's some method/library to solve this out there. I didn't really search for one so far though.
 
> You mean something like: Calculating their actual size in px for the specific display, and then increase their sp-size accordingly, if there is an odd px-result?

yes

> As we are talking about the main marker/icons etc., not about the actual insets, what about the following approach: Make marker, background and icon all have identical size in svg by adding padding as needed, so there is no pixel-difference when layering them above each other.

That would probably work - but it's a very ugly workaround and will cause a bunch of other issues. Like not everywhere the icons are used they'll used with the whole "marker + background + icon" package. e.g. in Filter dialog I propose to go for background + icon only - or we might even want to use icon+tint somewhere.
I propose to first look a solution where each image has the "proper" size and solve the positioning in code before we look into such a workaround.

**Comment by eddiemuc** [comment]
I looked into the "centering" issue, but only documentation-wise (have no chance to play around with code currently).

I see two ways to solve this. The first one we cannot go, the second one is worth a try imho.

**Way 1:** starting with SDK23, LayerDrawable offers "setLayerGravity" - which is more or less what the c:geo classes InsetBuilder/InsetsBuilder are trying to accomplish with self-written code. Alas, we have to support SDK21/22 as well. So probably no solution

**Way 2:**
I found that in case of centering, the insets calculated for top/bottom or left/right can be different (see code snippet above). I would assume that Android centers the drawables better when in case of CENTER top/botton as well as left/right have the exact same values (I assume Android then stretches the drawable to fill the remaining space and thus fits it in the center). I think this would be worth a try. Relevant code is in method `InsetBuilder.insetHelper`.

https://github.com/cgeo/cgeo/blob/eb293bb6ccb72f79315bcd7f48fe8aa283ef7913/main/src/cgeo/geocaching/utils/builders/InsetBuilder.java#L78-L92

Code should be changed such that in case of `hPos `being `HORIZONTAL.CENTER`, then `insetPadding[0]` and `insetPadding[2]` should get the same value. Same for `vPos/VERTICAL.CENTER/insetsPadding[1]/[3]`.
Code right now might lead to values differing by 1 in `CENTER` cases.

**Comment by ztNFny** [comment]
> I see two ways to solve this. The first one we cannot go, the second one is worth a try imho.

Using setLayerGravity sounds like the only correct solution to me, everything else is just workarounds.
Is it an option to implement both? Like in InsetBuilder do a "if (SDK > 23) { setLayerGravity() } else { calculate paddings manually}"?

**Comment by moving-bits** [comment]
> Is it an option to implement both? Like in InsetBuilder do a "if (SDK > 23) { setLayerGravity() } else { calculate paddings manually}"?

Sure, we have other such places where we check for available SDK using something like `if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.O) { ... }`

**Comment by ztNFny** [comment]
Then (if SDK >= 23) setLayerGravity else InsetBuilder seems like a good idea to me. Should also improve performance and maintanability (in the long run)

**Comment by ztNFny** [comment]
any opinion on this approach for the WIG icon (vs the current)?

![image](https://user-images.githubusercontent.com/1258173/131379272-1c5d9044-a83e-491e-85c3-d7d31e93fa65.png)
the blue lines at the top of the arrow are way too narrow, just a very quick sketch

**Comment by Lineflyer** [comment]
I like it. Still quite understandable and without any unneeded twirls. 
Its IMHO better than the one proposed on https://ztnfny.github.io/cgeoicons/index.html

**Comment by ztNFny** [comment]
![image](https://user-images.githubusercontent.com/1258173/131399422-519e4dd0-073f-4437-997b-f297f6af605c.png)
![image](https://user-images.githubusercontent.com/1258173/131399484-8fa7e1fb-33cf-4078-9f9d-852f2bb8c630.png)

**Comment by UniQP** [comment]
> ![image](https://user-images.githubusercontent.com/1258173/131399422-519e4dd0-073f-4437-997b-f297f6af605c.png)
> ![image](https://user-images.githubusercontent.com/1258173/131399484-8fa7e1fb-33cf-4078-9f9d-852f2bb8c630.png)

The triangular shape makes it much easier to recognize it as Wherigo cache, so I'm in favor of the second one.

**Comment by Lineflyer** [comment]
Lets close this generic issue in favor of the already opened / yet to come specific issue.

Many thanks @ztNFny for this major and nice contribution!!!
