### ISSUE TITLE
Navigation target selection broken

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11147]
Foubd this while trying to start Navigation to a cache which also has a parking WP, so we ask the user whether to navigate to cache coords or parking coords.

Its broken at least on white theme...did not check black. 

![Screenshot_20210708-114905_cgeo](https://user-images.githubusercontent.com/949669/124988095-dc627900-e03d-11eb-82b7-48467ea86916.jpg)

2021.07.07-NB

**Comment by moving-bits** [comment]
It's broken in both light and dark theme.
Fix is to switch from `Context` to `Activity` in related classes to pull the right theming. PR will follow.
