### ISSUE TITLE
waypoints show on map with compact icons=automatic

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11141]
When using the setting "use compact icons = automatic" when zooming/scrolling around the map near the limit where the switch between compact and normal icons switch waypoit icons show up randomly(in normal size ).

To repoduce:
In quick settings make these settings:
"Use compact icons = automatic"
"Show waypoints = all false"
Then zoom and pan around the map near the zoom level where icon size switches. When a waypoint icon appears zoom out.
You'll now have a map with compact icons for caches and normal sized icons for waypoints.

This issue can't be repoduced with fixed icon size, neither normal nor compact.

Version 2021.07.06-RC

**Comment by ztNFny** [comment]
![Screenshot_20210707-220703](https://user-images.githubusercontent.com/1258173/124822113-cc7c6380-df6f-11eb-85fb-1a30708e4cbf.jpg)
Forgot to mention: this is only repoducable with stored caches with waypoints, not on live map (as that doesnt load the waypoints)

**Comment by eddiemuc** [comment]
Teammeeting 11.2.24: @ztNFny does this still happen with unifiedmap?

**Comment by ztNFny** [comment]
I use neither UnifiedMap nor dot-icons, so I really can't tell. But as there have been no reports of this in recent years let's close here.
