### ISSUE TITLE
System information has bad contrast 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11151]
The system information has a gray text color, which looks like as if it is "currently disabled". I would suggest using white color instead like in all other pages of "about c:geo"...

**Comment by moving-bits** [comment]
I had chosen this color deliberately to focus the user on "send us this info" text, but I can easily change the system info's text color to default if requested.

**Comment by MagpieFourtyTwo** [comment]
In fact the info shown is not really meaningful to basic users, thus I can very well understand @moving-bits' motives.
And I agree that drawing attention to the [Send us] stuff is a good idea.
So - why not just hide the complete currently grey ``System information`` section behind a [Show complete text] button ...?

**Comment by fm-sys** [comment]
Another idea (although unrelated): what about making only the system information scrollable and keep the "important buttons" always visible?
