### ISSUE TITLE
Show user understandable filter info for fav percentage

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11154]
Minor improvement proposal (if at all):

- Activate a filter for favorite percentage 60% to 100% on a list
- The filter info (on top) shows "0.6 - *%". 

This made users think it filters wrong, while it doesn't.

We could improve it by showing "60% - 100%" or "60%+" or somthing like that.

**Comment by eddiemuc** [comment]
Finally something easy :-) Fixes with PR #11158
