### ISSUE TITLE
Replace or remove redundant geoode in map popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11155]
Beta users suggestion:
As the geocode is now shown in the title and the name only below (which I appreciate as it is fully readable) the geocode is again listed below.
Maybe you could remove it to gain more space (make the popup more lightweight).

**Comment by Lineflyer** [comment]
Second user: 
You could instead use it for the owner name (which I find would be nice to see on the popup).

Lineflyer comment:
Not sure if remove or replace would be my favorite. Maybe remove to support smaller screens.

**Comment by moving-bits** [comment]
You're talking about a cache popup, not a waypoint popup, correct?

**Comment by Lineflyer** [comment]
Yes, for the waypoint popup the geocode if the corresponding cache is not redundant and should stay.
