### ISSUE TITLE
Wrong backgrounds if external keyboard is used (rare case)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11169]
## Bug description 

While using c:geo on my Samsung tablet (Android 10, Galaxy S4) in conjunction with an external keyboard I noted some strange effects, that when opening dialog they sometimes have wrong background color (tested only dark theme).
Finally I found one reproducible way on my device.

### Steps to reproduce the problem

- Start in c:geo main screen
- Tap on the quick search field in action bar
- Type a GC code on the external keyboard and press enter on external keyboard to start search

### Actual result after these steps 

- The loading progress shows up. Its noticeable here, that the "Cancel" button looks like it is selected 
- The cache details are shown but the background color is not the normal black but exactly the same color as on the action bar
- Swiping to description resolves the issue for now (also when going back to the details)

It looks a bit as if some coloring of the action bar is "remembered"

### Expected result after these steps 

Normal background

## c:geo version 

2021.07.08-NB

## Reproducible 

Yes, on that device with keyboard use. When using the on screen keyboard the issue isn't there.

## System information 

Can be completed if needed

```
Paste your system information here
```

## Screenshots 

Can provide a video next week.

## Additional context 

I consider this problem as a real minor, rare case. However, maybe there is some generic problem behind?

**Comment by eddiemuc** [comment]
Teammeeting 11.2.24: rare and very specific case. Closing is recommended. Please reopen if still an issue
