### ISSUE TITLE
Friend Log Page Setting doesn't work 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11167]
In the current nightly (and AFAIK also for a longer time) the "show friend log page" setting seams to have no effect anymore... 

![Screenshot_20210710_095538_cgeo geocaching](https://user-images.githubusercontent.com/64581222/125156368-5fcaba00-e165-11eb-9bc2-7e3109a013a4.png)
![Screenshot_20210710_095446_cgeo geocaching](https://user-images.githubusercontent.com/64581222/125156370-60635080-e165-11eb-8bc7-2b33c728ed35.png)

**Comment by moving-bits** [comment]
What do you mean by "setting seams to have no effect anymore"?

**Comment by murggel** [comment]
In my case: Deactivating for offline stored caches works (only?) after refreshing the cache...

**Comment by fm-sys** [comment]
@murggel 
Thanks for bringing light into this topic.

My workflow:
1.  Import pocket query
2. Friendlogs are shown
3. Refresh the cache
4. Friendlogs are gone

but as a user I would expect that this setting is applied locally and not only affects refreshing inside c:geo. So this issue might be a feature request instead of a bug report.

**Comment by murggel** [comment]
For me it's a bug, because the page itself should not be shown

**Comment by Lineflyer** [comment]
That how that switch worked up to now AFAIR. It controls whether this data is fetched from server. 
At the time the feature was introduced it was not yet possible to export friends logs as part of the GPX. So it worked more or less the same as not showing it, as it was not loaded and there was no other way to import that data.
Now there is a small gap in that logic. which might be called a bug ;)

**Comment by bekuno** [comment]
I like this feature. And I don't understand that we need a option to not show this page. Is there really such a use case?
How about to remove the option, so thst always this page is shown?

**Comment by murggel** [comment]
Probably performance issue if you have a lot of friends?

**Comment by fm-sys** [comment]
> How about to remove the option, so that always this page is shown?

For me, I don't see a benefit in this option. Actually it's even annoying (at least for me) as it's more work until you reach the really interesting stuff like TB's and pictures. 

And this issue is really easy to fix (probably only a few lines of code), so there is totally no reason to drop this option. I can work on the issue myself, but please don't remove this setting!

**Comment by fm-sys** [comment]
@murggel just saw that you have self-assigned this issue. The fix should target the GUI creation of `CacheDetailActivity`, not the GPX parser, so that users don't have to refresh all caches after disabling the setting.

**Comment by murggel** [comment]
I would target the GC-Parser as well, so users don't have to refresh the caches after activating this setting 😉

**Comment by MagpieFourtyTwo** [comment]
> For me, I don't see a benefit in this option. Actually it's even annoying (at least for me) as it's more work until you reach the really interesting stuff like TB's and pictures.

JFTR: We always use it when a cache just won't show up. One look at the friend's page and you know who to ask. So for us it's a really valuable feature - especially for frustration management. ;)

**Comment by fm-sys** [comment]
> I would target the GC-Parser as well, so users don't have to refresh the caches after activating this setting 😉

Do you really think it is worth to always do an additional API request just to have a better migration when changing the setting? IMHO the current behavior is ok in this direction (refresh needed for off --> on). I would prefer leaving the GC-Parser as is (saving network traffic was AFAIK the reason why the setting was implemented at all).

**Comment by murggel** [comment]
Good point, didn't thought about that

**Comment by murggel** [comment]
Unfortunately there is no way to retrieve own and friends-log in one request? I did not find any description for that http-request

**Comment by murggel** [comment]
Target for that PR shall be master or release? I think it's not a critical change, since no change in retrieving the data only the page is hidden, if options is disabled.

**Comment by fm-sys** [comment]
Yes, release is fine IMHO...

**Comment by eddiemuc** [comment]
> Unfortunately there is no way to retrieve own and friends-log in one request? I did not find any description for that http-request

Afaik none of the currently supported services supports requesting "logs from friends". Maybe oc because they have a quite elaborated API, but I really doubt that GC.con or any of the smaller services support this.

Afaik, the "friends" logs are filtered out of the "normal" retrieved logs on c:geo client side. Which also means that the logic is not working if you load a fresh cache and your friends' logs are not among the last x logs (I think we load the last 30 or 40 logs or something like this)

**Comment by murggel** [comment]
> > Unfortunately there is no way to retrieve own and friends-log in one request? I did not find any description for that http-request
> 
> Afaik none of the currently supported services supports requesting "logs from friends". Maybe oc because they have a quite elaborated API, but I really doubt that GC.con or any of the smaller services support this.
> 

In fact GC supports retrieving friends-log (see GCParser).
For the others I did not checked.

**Comment by eddiemuc** [comment]
> In fact GC supports retrieving friends-log (see GCParser).

OK, that's my bad then. Sorry
