### ISSUE TITLE
Use darker accent color for white theme?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11170]
From support mail there are a few beta users who mention the coloring as not nice.

The most described problem is a lack of contrast of the accent colored items (especially rating stars and "Add waypoint" and similar).
I have to admit, that (coming from black texts and red stars in older versions) our accent color has much less contrast on a white background.

I know we discussed this somewhere (partly) already but not sure about the conclusion.
Is it possible to define a different accent color between dark and white theme? If so: Can we make it a bit darker (but still orange)? This will improve contrast without loosing our recognition scheme.

Other possibilites I could imagine are to change the background or restyle elements (bold fonts or alike) only for the white theme. But this would kind of destroy the synergy effects to have consistent definitions.

**Comment by Lineflyer** [comment]
BTW: No such mails from beta users concerning the black thee until now.

**Comment by moving-bits** [comment]
I would prefer to stay will color differentiation between themes, but keep font styling identical.

A darker accent color just for light theme should be no problem technically (although I would prefer to have an identical accent color as a "brand color") - let's discuss this in our next dev meeting.

**Comment by Lineflyer** [comment]
OK

**Comment by eddiemuc** [comment]
> I would prefer to stay will color differentiation between themes, but keep font styling identical.

Most definitely agree!

> A darker accent color just for light theme should be no problem technically (although I would prefer to have an identical accent color as a "brand color") - let's discuss this in our next dev meeting.

Definitely not a technical issue. My opinion: either we change the accent color such that it look great in both dark and white mode, or we use two different shades of orange. But usability of both modes must come first.

(Or we make the accent color selectable in the settings :-))

**Comment by Lineflyer** [comment]
> (Or we make the accent color selectable in the settings :-))

No comment...you probably know my opinion

**Comment by moving-bits** [comment]
Using our current accent colors we get:

|current dark theme color|current light theme color|current dark theme color used in light theme|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/125209383-ab31b500-e298-11eb-807a-2962c40e5838.png)|![image](https://user-images.githubusercontent.com/3754370/125209386-b2f15980-e298-11eb-927c-82df6b33b636.png)|![image](https://user-images.githubusercontent.com/3754370/125209388-bc7ac180-e298-11eb-9a12-f47e0cb44f6b.png)|

I guess using our current dark theme color also in light theme works pretty well, gives a much better contrast than our current light theme color.
