### ISSUE TITLE
Amount of waypoints not visible in tab title from description tab any more

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#11175]
## Bug description 

In the previous cgeo versions one could see the full title of the tab in the tab-bar in the bottom. Currently (probably due to bigger fonts?) only "waypoint" part is visible, but not an actual number of waypoints.

So in order to check how many are there, I really need to switch to waypoints tab, which is not convenient.

### Steps to reproduce the problem
Open a cache in cgeo on "Details" tab
Check title of "waypoints" tab
Make sure amount is not visible

## System information 

```
Paste your system information here
```

## Additional context 

![Screenshot_20210711-061435](https://user-images.githubusercontent.com/918446/125181623-61e95300-e20f-11eb-9eb5-cfb5db4400f7.png)

**Comment by Lineflyer** [comment]
Can you post your details about device and cgeo version?

**Comment by bekuno** [comment]
The number is before the text "WAYPOINT", so it is not visible.
Either we can shorten the width of the navigators or write the number after "WAYPOINT", e.g. "WAYPOINTS (1)".

**Comment by fm-sys** [comment]
"WAYPOINTS (1)" would be ok for me, but please don't deface the MaterialComponents ;)

**Comment by okainov** [comment]
>Can you post your details about device and cgeo version?

SHARP Aquous R2 Compact, latest nightly build

**Comment by bekuno** [comment]
> The number is before the text "WAYPOINT", so it is not visible.

@okainov ist this also the situation on your device?

**Comment by okainov** [comment]
>@okainov ist this also the situation on your device

I think that's exactly what was my issue about, wasn't it? :) And also screenshot attached. So yes, exactly this.

**Comment by moving-bits** [comment]
This is truly strange, because even when I set this to max. font size, the number of waypoints is still shown:

![image](https://user-images.githubusercontent.com/3754370/125210221-98ba7a00-e29e-11eb-9492-8b585a99c5de.png)

This works similarly when the cache has only one waypoint - "1 Wegpunkt" (German) / "1 waypoint" (English).

**Comment by bekuno** [comment]
You do not see the complete text when the details page is active, see the screenshot above.

**Comment by moving-bits** [comment]
> You do not see the complete text when the details page is active, see the screenshot above.

Ah, thanks for clarification - I got somewhat mislead by the screenshots, thought, that the number was omitted at all. Hm, will need to lookup if there is a way to make another tab's title be always visible - and in a way which works for all languages. - Or maybe just reverse the order, as proposed above...

**Comment by Lineflyer** [comment]
Exactly.
Its a small improvement request to move the number of waypoint leftmost to have a higher chance to see it already when on details page.

**Comment by okainov** [comment]
>Hm, will need to lookup if there is a way to make another tab's title be always visible - and in a way which works for all languages. - Or maybe just reverse the order, as proposed above...

What about decreasing font size? Putting the number to the right would also work for me though, but I really think font size is too big anyway

**Comment by fm-sys** [comment]
I don't think the font size is too big. It's exactly between actionbar and content font size...

**Comment by bekuno** [comment]
I think that the bigger width is a result of the text in capital letters.
We had this problem also on other place, e.g. in lists (OK/ABBRECHEN/LETZTE AUSWAHL).
By the way, I don't like the text in capital letters.

**Comment by fm-sys** [comment]
> I think that the bigger width is a result of the text in capital letters.

Has nothing to do with capital letters but is caused by the fact,a that we use a completely different UI component for the viewpager than before...

**Comment by bekuno** [comment]
> 
> 
> > I think that the bigger width is a result of the text in capital letters.
> 
> Has nothing to do with capital letters but is caused by the fact,a that we use a completely different UI component for the viewpager than before...

Maybe the change for the viewpager also affects the width, but for sure the text width is larger when using text in capital letters (see my note above).

**Comment by okainov** [comment]
>I don't think the font size is too big. It's exactly between actionbar and content font size...

Well, actionbar is also too big, as you can see, even average-named cache name doesn't fit there :) You show just 9(nine!) symbols from cache name, that's not even funny....

**Comment by Lineflyer** [comment]
But that does not mean its wise to make the text smaller.  As the font size follows the user system font settings and cache names can be longer or shorter it might always fit or not fit.

Maybe we should even in cache details only show the GC-code on the action bar. But thats another issue.

**Comment by fm-sys** [comment]
Or could it be, that we should use a fixed size for the action bar (dp) and only make the content size dynamic (sp)? 

That would solve other issues like "secondary line cut off" as well. Have checked how other apps handle it?

**Comment by Lineflyer** [comment]
> Or could it be, that we should use a fixed size for the action bar (dp) and only make the content size dynamic (sp)?

I would not do that. It will probably result in the menu unreadable small on highres devices such as tablets.

**Comment by fm-sys** [comment]
> > Or could it be, that we should use a fixed size for the action bar (dp) and only make the content size dynamic (sp)?
> 
> I would not do that. It will probably result in the menu unreadable small on highres devices such as tablets.

This has nothing to do with high-res.

sp -> take font size setting into account
dp -> always the same size independent of dpi resolution
px -> size will differ depending on the device resolution

**Comment by fm-sys** [comment]
Just some real live examples how it is/should be done:

![Screenshot_20210712_194119](https://user-images.githubusercontent.com/64581222/125332467-5e59e700-e349-11eb-9a6d-11d81fa3ef3e.jpg)|![Screenshot_20210712_194107](https://user-images.githubusercontent.com/64581222/125332472-5f8b1400-e349-11eb-998e-cd22d6c75039.jpg)
-|-
![Screenshot_20210712_194055](https://user-images.githubusercontent.com/64581222/125332473-6023aa80-e349-11eb-9501-9065bfe1ede9.jpg)|![Screenshot_20210712_194043](https://user-images.githubusercontent.com/64581222/125332474-60bc4100-e349-11eb-88d1-87d53b3731d2.jpg)

Note that the actionbar size does not change in any other app than cgeo I have tested.

**Comment by Lineflyer** [comment]
The actionbar in c:geo changes it size? Never realized that.

**Comment by bekuno** [comment]
> 
> 
> The actionbar in c:geo changes it size? Never realized that.

The font in the actionbar can do it - this is is documented in the issue #11127.

**Comment by moving-bits** [comment]
> > The actionbar in c:geo changes it size? Never realized that.
> 
> The font in the actionbar can do it - this is is documented in the issue #11127.

The font size changes, but not the height of the action bar itself, AFAICS.

**Comment by fm-sys** [comment]
> The font size changes, but not the height of the action bar itself, AFAICS.

Yes, exactly that's the problem

**Comment by moving-bits** [comment]
> > The font size changes, but not the height of the action bar itself, AFAICS.
> 
> Yes, exactly that's the problem

Whether this is regarded a problem depends on what you expect: 
- If you expect to still see everything in the action bar (at the cost of seeing less in the "content area"), you may call it a bug.
- Whereas if you expect to see as much content as possible (at the cost of the text in the actionbar being truncated), this is the right behavior.

AFAICS all apps I use are following the second approach (as does c:geo). => No need to change our action bar, IMHO.

**Comment by fm-sys** [comment]
> AFAICS all apps I use are following the second approach (as does c:geo). => No need to change our action bar, IMHO.

If you take a look at my screenshots above in https://github.com/cgeo/cgeo/issues/11175#issuecomment-878470102 than you can see that all other apps use a fixed font size while in c:geo it depends on the system font setting.

**Comment by Lineflyer** [comment]
Increasing the action bar(s) size if required would also solve the problem, that on large fonts you will not see the subtitle of live map (cache count) as mentioned in another issue. 
Also my fix for the list selection spinner is only "half" as when the font grows even bigger the current selected lists subtitles will still no longer fit.

**Comment by fm-sys** [comment]
> Increasing the action bar(s) size

No, still make the text size fixed for actionbar if we don't want to defend against material guidelines (would solve the map issue as well)

**Comment by Lineflyer** [comment]
> No, still make the text size fixed for actionbar if we don't want to defend against material guidelines (would solve the map issue as well)

Maybe better...yes.
