### ISSUE TITLE
Filter status does not scale favorite percentages

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#11183]
When adding a favorite percentage filter, the status line does not scale the filter values to percentages.

**Actual behavior**
![image](https://user-images.githubusercontent.com/1321557/125210120-05814480-e29e-11eb-9d15-114a697485a4.png)

**Expected behavior**
`Favorites:5-35%`

**Comment by eddiemuc** [comment]
Duplicate of #11154
