### ISSUE TITLE
list limit - set correct possition after load next entries

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11189]
If we stay with the "load next 100 caches" button then there is a bug to fix: 
The list is reloaded and the scroll position is on top of the list, not on the last position. So you have once more scroll down to the end of the list to see the added entries.

_Originally posted by @bekuno in https://github.com/cgeo/cgeo/issues/11132#issuecomment-875920528_

**Comment by eddiemuc** [comment]
fixed with PR #11264
