### ISSUE TITLE
compact D/T for Filters

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11180]
To save some space in the filters I propose to compact this.

Original:
![Screenshot_20210711-223641_cgeo-2](https://user-images.githubusercontent.com/32555742/125209840-103ada00-e29c-11eb-89e5-2eebb653c557.jpg)

Proposal:
![Screenshot_20210711-223641_cgeo optimized-2](https://user-images.githubusercontent.com/32555742/125209848-17fa7e80-e29c-11eb-98e7-9522dfc85212.jpg)

**Comment by fm-sys** [comment]
Only for basic or merge them to an D/T filter for advanced mode as well?

**Comment by bekuno** [comment]
> 
> 
> Only for basic or merge them to an D/T filter for advanced mode as well?

Everywhere where it is possible, I would say.

**Comment by eddiemuc** [comment]
I like the idea, although it creates some "implementation problems" internally...

If we change this I would definitely not differentiate between "basic" and "advanced" filter mode

**Comment by eddiemuc** [comment]
@murggel this might be something you're interested in. But it requires merging the two separate filters for "Terrain" and "Difficulty" into one, and then creating a dedicated new view for the result (currently both the filter and the viewholder use a common "range-filter" base class which however supports just one range)

**Comment by murggel** [comment]
I can give it a try, but don't know if I will succeed for the view...

**Comment by murggel** [comment]
First try looks not so bad...

![image](https://user-images.githubusercontent.com/70113341/126406806-ae54bc3d-e560-48d2-90ef-406bf03ad751.png)

**Comment by eddiemuc** [comment]
Looks very good! Now you just need to hide the lower scale (so only the middle one is left)

**Comment by murggel** [comment]
> Looks very good! Now you just need to hide the lower scale (so only the middle one is left)

@eddiemuc What do you mean? What do I need to hide?

**Comment by murggel** [comment]
Still the text-label looks somehow missplaced. But I did not get that worked.
@fm-sys probably you have an idea?

**Comment by fm-sys** [comment]
> Still the text-label looks somehow missplaced. But I did not get that worked.
> @fm-sys probably you have an idea?
> It's in DifficultyAndTerrainFilterViewHolder.createItemRangeSelectorLayout

Sorry, completely missed that one. I'm currently not able to try it out in Android Studio, so probably it's better to open a new issue.

A picture tells more than 1000 words: "D" / "T" label isn't aligned. 
![Screenshot_20210731_181759_cgeo geocaching](https://user-images.githubusercontent.com/64581222/127746105-703611e6-8e71-45c7-a06a-1387bffb69d3.png)
