### ISSUE TITLE
Enhance system info by filter information

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11186]
For future support mails it  will be rather important to know what users have filtered.
At this moment we only have:
```
- Global filter: display all caches
```
which is no longer of relevance.

We should replace it by the "short string" shown below the action bar for offline- and live filter.

That would help me very much for cases when users report "I dont see any caches".

**Comment by eddiemuc** [comment]
Makes sense.
Then for me I would also need the "technical" filter config in the sys info (the user-displayable version might miss important Infos and is translated). Might be best to add both.

**Comment by fm-sys** [comment]
Or would it be much refactoring to show the user-displayable filter string unlocalized additionally to the technical filter config?

**Comment by eddiemuc** [comment]
> Or would it be much refactoring to show the user-displayable filter string unlocalized additionally to the technical filter config? 

This does not make an sense imho. Why would I construct a third representation just for this which is not user anywhere in the system?

I definitely need the technical config, no way around that.

**Comment by eddiemuc** [comment]
Done with #11252:

![image](https://user-images.githubusercontent.com/6909759/126074393-fe95980c-74a6-4442-a210-b91cce490c41.png)
