### ISSUE TITLE
Coordinate format selector broken on white theme

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11190]
Here is another problem which was reported by a user and I can reproduce on my Samsung S20, Android 11. 
I can however not reproduce on emulators API29 or API30. In the emulator it looks perfect.

Screenshot taken with 2021.07.12-NB1

![Screenshot_20210712-113859_cgeo](https://user-images.githubusercontent.com/949669/125266662-53ca2e00-e306-11eb-9558-7cbd13e2fdd3.jpg)

**Comment by fm-sys** [comment]
Cannot reproduce in the emulator nor on my physical device either... For me, it always looks fine.

![grafik](https://user-images.githubusercontent.com/64581222/125831931-97d261ec-89b3-4f9c-86d1-16a7b57a176b.png)

**Comment by fm-sys** [comment]
> yes, still reproducible for me with 2021.10.06-NB1

Ok, I will have a look at it...

**Comment by fm-sys** [comment]
@Lineflyer can you check, whether the problem happen at other places as well? e.g. here:

![grafik](https://user-images.githubusercontent.com/64581222/136654216-d43ebc27-e613-462f-a234-3d24a8f5d5ad.png)

**Comment by fm-sys** [comment]
OK, I have a potential solution suggested here:
https://stackoverflow.com/questions/31425697/spinner-popup-background-color-issue

Is it your main device, or can you test PR #11810?

If you cannot easily test the debug build on your device, I would vote for merging it to `master` and generating a new nightly...

**Comment by fm-sys** [comment]
> 
> 
> yes, still reproducible for me with 2021.10.06-NB1

@Lineflyer can you test wether it is fixed with 2021.10.09-NB1?

**Comment by Lineflyer** [comment]
Yes, the only drawback (also here same as in cache search spinner on main menu) the shadow is missing.

![Screenshot_20211009-164446_cgeo](https://user-images.githubusercontent.com/949669/136662815-64680496-280a-4180-bbea-a4a0bc0cc9d2.jpg)
