### ISSUE TITLE
Archived caches - difference between connectors

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11208]
I just now realized, that different services treat archived caches in a different way, which leads to a difference between older release and the current beta:

For gc.com all interfaces (map, search) do never return archived caches. Those are - very understandable - considered as no longer relevant but have more an archive character.

This seems to be different on OC (at least on OC.de). Here I suddenly see archived caches in my search results (but not on map).
With the old release this was not the case, although I did never use "Hide archived caches" option.

This seems to have changed as a side effect of the recent changes.
Is this intentional and does it make sense...I know they can be filtered anyway, so this is not the reason for this issue.
The reason is, that we now have different content of search results between different connectors.

Edit:
You could also say: If we let OC return archived caches then we should also do it on the map but not only in searches.
Or (my suggestion): Do not request archived caches in online searches...this would only encourage people to search archived caches (or less advanced users to search for them only later realizing, that they are archived).

**Comment by eddiemuc** [comment]
I have to check whether I accidentally removed some hard-coded flag not to return archived caches ever from oc.de.

But since oc.de API explicitely allows searching for archived caches, do you really want to take this option away from users?

**Comment by Lineflyer** [comment]
That was my first thought...but I add the "Feedback required" to discuss that.
I would not expect to see archived caches in c:geo except I explicitly imported them or opened them by their geocode (which still means its meaningful as filter option (for offline).

**Comment by eddiemuc** [comment]
Still open - still relevant?

**Comment by Lineflyer** [comment]
IMHO yes. There is a difference for OC connectors between last release and current state.
IMHO we should not request archived at all despite in searching for a specific geocode of course.

**Comment by fm-sys** [comment]
> But since oc.de API explicitely allows searching for archived caches, do you really want to take this option away from users?

Exactly my thought. Don't know if there are mystery caches on OC where searching for archived caches would be helpful. OTOH, I totally agree that archived caches bring no benefit to users so displaying them doesn't really make sense...

**Comment by eddiemuc** [comment]
Ok, what about the following solution proposal:
* make "exclude archived" the default setting for filter/search (even when no status filter is selected)
* when adding a status filter, the "archived" option is disabled by default (but can be enabled by user of course)

An alternative (easier to implement) would be to disable search for archived caches at oc altogether (gc.com does not allow their search anyway), as it is today in production.

Given current production state. I ask myself why there was such a fuzz made in the past to enable/disable archived caches specifically for searches and map quick settings anyway, since only caches stored before and those explicitely searched by code could possibly go in such a state.

**Comment by Lineflyer** [comment]
> make "exclude archived" the default setting for filter/search (even when no status filter is selected)

IMHO that would be confusing to users and/or might lead to the follow up questions like "I disabled this archived filter but still get no archived caches". Remember only a minor percentage of users is affected after all, as the majority only uses GC for which such prefiltering is not needed.

So I still think that not requesting archived caches from OC is the best choice.

**Comment by eddiemuc** [comment]
PR #11258 will remove requesting archived caches from OC in general. If this behaviour is wanted, just merge this PR.
