### ISSUE TITLE
"Add current location" waypoints not shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11201]
## Bug description 

Today I ran in a situation where the waypoint tab failed to update after adding waypoints. Found a way to reproduce

### Steps to reproduce the problem

- Open a cache and swipe to waypoint tab (or use the Go to cache)
- Create a waypoint, enter some coordinates and save
- The waypoint is now shown in the list
- Tap on "Add current location" to create another waypoint 

### Actual result after these steps 

The waypoint is added (total amount rising on bottom bar) but the newly created waypoint is not shown
You can add another one by "Add current location" which is also not shown, and so on.

The waypoints are shown if you leave and reenter the screen.

### Expected result after these steps 

View needs to update to show the new waypoints immediately

## c:geo version 

2021.07.11-NB

## Reproducible 

Yes

**Comment by moving-bits** [comment]
Confirmed. And strange, because if you only use "add current location" (without creating a waypoint using the other button), it does work.

May to be related to a sub-activity being called?
