### ISSUE TITLE
Add long click to select filter in cacheListActivity and Map

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11202]
## What function are you missing

Changing the current filter to an already stored is in the advanced filter-options. I would like to have an easy way to switch filter.

## Suggested solution

Long click on current filter text and filter-action in action-bar should open a list with the available filter to "quick"-select a different filter.

## Alternatives/workarounds

Move manage and save methods to basic filter view. As discussed we can postpone / leave that out and see, if long-click is sufficient.

**Comment by eddiemuc** [comment]
+1 from my side

**Comment by murggel** [comment]
@eddiemuc I added the dialog to the long click for list and map. Refreshing the list is working but I need some help to refresh the map with the new filter. I did not see the logic / function which updates the shown caches on the map.
How do I get the map view updated? It works if I recreate the activity, but I guess there is a better / faster solution...

**Comment by fm-sys** [comment]
Without looking at the code, the update could be done within the `onActivityResult` and/or `onResume` method... (Just guessing)

Ok, took a deeper look: NewMap uses the liveCachesOverlay and StoredCachesOverlay. CGeoMap has a private LoadTimerAction. These classes must be somehow triggered. But I'm not very firm with these code parts.

Probably @eddiemuc will provide some better insights ;-)

**Comment by eddiemuc** [comment]
@fm-sys is right. Look into the two map classes' onactivityresult methods and see what is done when returning from the filter activity there (return code is something like Filter_result or so).. basically you need to call the same logic to apply the new filter.

No need to fuddle with the cache overlays though, luckily this is already encapsulated in other parts of code for you (and me :-))

**Comment by eddiemuc** [comment]
@murggel I peeked into code, and I believe you need to call the following two methods after changing the filter:
* onMapSettingsPopupFinished (of NewMap / CgeoMap respectively)
* MapUtils.setFilterBar

MIght be best to rename the "onMapSettingsPopupFinished" to something like "refreshMapData" or so...

This should be all there is to do. If this does not work, just contact me again. I am very sorry that currently I have close to no time for coding myself due to private & work-related activities. I hope this will change soon.

**Comment by murggel** [comment]
> @murggel I peeked into code, and I believe you need to call the following two methods after changing the filter:
> * onMapSettingsPopupFinished (of NewMap / CgeoMap respectively)
> * MapUtils.setFilterBar
> 
> MIght be best to rename the "onMapSettingsPopupFinished" to something like "refreshMapData" or so...
>

Thanks, I already found out the onActivityResult, but there only the setFilterBar was called. Now I try with onMapSettingsPopup...

**Comment by eddiemuc** [comment]
@murggel Come to think of it: maybe it is best to add a call to MapUtils.setFilterBar inside the  method "§onMapSettingsPopupFinished()" and then call just this method (and rename it to something like "frefreshMapData").

Reason: currently, the filter bar does not need refresh after map-settings are closed - but this will change soon, when the "hide" settings will be directly merged to the filter

**Comment by murggel** [comment]
@eddiemuc your suggestion with onMapSettingsPopupFinished() worked, so now I am on fine tuning.

After that I can help you with some filter-issues, if it's not too complicated for me ...

**Comment by murggel** [comment]
Sorry, did not have so much time the last days as expected, but now I have some screenshots ready for discussion:
Shall the selection-dialog looks more like a "list" or a "selection"?
![image](https://user-images.githubusercontent.com/70113341/126354764-fbebc019-5e3e-4cff-8857-cdb93eaf022c.png)
![image](https://user-images.githubusercontent.com/70113341/126355428-d203c342-bc07-42cd-9a13-9534311e4a53.png)

**Comment by murggel** [comment]
And I would like to add the possibility to clear the current filter (if one is applied already):
![image](https://user-images.githubusercontent.com/70113341/126354901-f5fec27d-6192-490d-be33-a7af91ac43b5.png)


@eddiemuc  Therefore I need a way to create a "default" filter. Currently I create one from config with `"[:inconclusive=false:advanced=false]AND(type;status)"` but I don't know if there is a "easier" way to have it available for other places as well. There is a static GeocacheFilter::EMPTY_FILTER but if I try to create the "default" as static one too, it does not work.

**Comment by eddiemuc** [comment]
@murggel if you rebase your release branch, you will now find a method GeocacheFilter.createEmpty() to create an empty Filter object. I guess this should work.

Wrt the screenshots: I would personally prefer the "list" version because it saves one click.

**Comment by Lineflyer** [comment]
> Wrt the screenshots: I would personally prefer the "list" version because it saves one click.

Indeed its no multiple selection anyway, so the list should do.
