### ISSUE TITLE
Show on map -> Locus no longer available

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11200]
Current nightly 2021.07.12-NB:

- Open a cache list
- Select Menu -> Show on Map

Previously "Locus" was shown here, now its missing.
Maybe also another instance of a missing package name check allowance in our lists?

**Comment by fm-sys** [comment]
Hmm, for me it's still working, as well as the Maps.me integration 🤔

Could it be that it only happens on Android 11 devices?

**Comment by moving-bits** [comment]
Are you using the "pro" version of Locus?
(Because currently we are only checking for "menion.android.locus", which is the free version. I'll extend this by the other package names Locus uses, taken from the `LocusUtils` file.)

**Comment by Lineflyer** [comment]
Yep, I use the pro version.

**Comment by moving-bits** [comment]
Ok, the pro version was missing, but the free version should have been detected already.
