### ISSUE TITLE
Nightly build failed with exception

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11214]
Stacktrace:

```
FAILURE: Build failed with an exception.
00:32:09  
00:32:09  * What went wrong:
00:32:09  Execution failed for task ':main:lintVitalBasicNightly'.
00:32:09  > Lint found fatal errors while assembling a release target.
00:32:09    
00:32:09    To proceed, either fix the issues identified by lint, or modify your build script as follows:
00:32:09    ...
00:32:09    android {
00:32:09        lintOptions {
00:32:09            checkReleaseBuilds false
00:32:09            // Or, if you prefer, you can continue to check for errors in release builds,
00:32:09            // but continue the build even when errors are found:
00:32:09            abortOnError false
00:32:09        }
00:32:09    }
```

I think it's totally fine to let debug builds fail on lint errors, but release builds shouldn't be affected.

So I would vote for disabling lint for release builts.

**Comment by eddiemuc** [comment]
I strongly disagree. The above note is meant for "hotfix" release branches (which just reflect the state of production, so the only change to them would be fixes for high-prio errors, nothing else).

We are using our "release" branch in a different way: for further development during beta. Also, the branch is continuously merged back to master which would then transport such problems to it. We should definitely keep same lint settings in release as in master.

**Comment by fm-sys** [comment]
My comment was about unsigned `debug` (PR) vs. signed `release` (nightly/beta/production) builds. Not about branches. 

I don't see a reason why nightly builds should fail because of lint errors. But I don't insist on it. 

Anyway, someone should trigger a manual crowdin sync so that we can get the build working again as quick as possible. Or give me the permission to do so ;-)

**Comment by fm-sys** [comment]
Nightlybuild is working again. So let's close here.


Still I'm convinced, that the nightly build should not fail just because there are quantity strings without default value...
