### ISSUE TITLE
Make actionbar font size fixed

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11215]
If you take a look at my screenshots above in https://github.com/cgeo/cgeo/issues/11175#issuecomment-878470102 than you can see that all other apps use a fixed font size while in c:geo it depends on the system font setting.

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11175#issuecomment-878546370_

**Comment by fm-sys** [comment]
I will work on it. But it's a bit more complex as the font size is also used for the cache list spinner... But I already have a solution in mind.

**Comment by stephr321** [comment]
If this was fixed as part of the beta update 2021.07.17-RC2, it did not change for me. I verified I have received the latest beta update.

**Comment by fm-sys** [comment]
Related PR is  #11220, but unfortunately it was not yet merged... If no one complains I will merge the PR this evening.

**Comment by Lineflyer** [comment]
If an issue is still open you can be quite sure it is not yet fixed...but we are on our way.
