### ISSUE TITLE
Wrong action bar color in cgeo settings

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11219]
Since we now have different action bar colors for light and dark theme, we now have yet another issue caused by our outdated preferences implementation :-/

The action bar uses the device theme setting, not the cgeo theme. Will be fixed automatically when #10579 is done... The question is, whether we should implement another workaround for the time being?

![grafik](https://user-images.githubusercontent.com/64581222/125493507-0f661ea5-c87a-465b-921b-ce37198b9630.png)

**Comment by moving-bits** [comment]
IMHO we should not invest here any further, but wait for #10579 being implemented. Especially since @SchoolGuy and @TacoTheDank seem to start working on it just now.

**Comment by moving-bits** [comment]
Seems to be fixed with our recent migration to AndroidX preferences
