### ISSUE TITLE
[New Filter] Filtering for "FOUND=NO" gives unexpected result

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#11213]
## Bug description 
In a list of offline stored not yet found caches, I filtered for ``Status`` => ``Found==NO`` (admittedly, by accident ;) )
Much to my astonishment the filter returned ``207/208`` - although I was absolutely sure there is no found at all in this list.
Thus I first tried to inverse the filter - to no avail (result = ``0/208``),
then filtered for ``Status`` => ``Found==YES`` - result: same same, i. e. ``0/208``.
Strange.
After some fiddling around I found out: The filtered one is the one and only in this list, with an offline stored ``Write note``
(a remnant of the times when c:geo did not show DNF logs, which has also been logged for this cache, some time ago).

As soon as I removed the offline ``Write note``, everything behaved as expected.
Additionally, the ``Saved Log (13/07/2021), Not found`` text in the ``Details`` page changed to ``Not found`` (as expected).

### Steps to reproduce the problem
- open any not yet found cache, log a ``Write note`` and store it offline
   (in ``Details`` page, the text ``Saved Log (13/07/2021), Not found`` will appear)
- put this cache in a list with some more not yet found caches
- set up a filter with nothing but ``Status`` => ``Found==NO`` (all others = ``ALL``)

### Actual result after these steps 
All caches but the one with the offline stored ``Write note`` showed up.

### Expected result after these steps 
All caches should be shown, even the one with a ``Write note`` - as a ``Write note`` (alone) is definitely no ``Found``,
as even the ``Status`` in ``Details`` page correctly states.

## c:geo version 
2021.07.12-NB2-f67a9d4

## Reproducible 
Yes

## System information 
```
c:geo version: 2021.07.12-NB2-f67a9d4

Device:
-------
- Device type: VOG-L29 (VOG-L29EEA, HUAWEI)
- Available processors: 8
- Android version: 10
- Android build: VOG-L29 10.1.0.150(C431E19R2P5)
- Screen resolution: 1080x2147px (423x841dp)
- Sailfish OS detected: false
- Google Play services: disabled - 21.21.16 (120400-378233385)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: own/ foundarchived
- Hide waypoints: -
- Set language: en_DE (system default)
- System date format: dd/MM/y
- Debug mode active: no
- Live map mode: false
- OSM multi-threading: true / threads: 4
- Global filter: display all caches
- Last backup: 13 Jul, 00:12
- Routing mode: Walk
- Settings: v5, Count:270
- Map: _  DE BaWü Vosges (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:0123-4567:Locus/mapsVector/_  DE BaWü Vosges.map
  - Atts: Maps: (c)Christian Kernbeis, Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2021
  - Theme: Elevate F140 L120 S110 EB.xml

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
- Geocaching.com date format: dd MMM yy
- Routing: external / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (56,8 GB free) v2 internal isDir(7 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (56,8 GB free) v2 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (56,8 GB free) v2 external non-removable isDir(475 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (56,8 GB free) v2 internal isDir(8 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=11, dirs:>=14, totalFileSize:>=1,3 GB, free space: 56,8 GB, files on device: 13278715)
  - OFFLINE_MAPS: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector, Av:true, files:449, dirs:4, totalFileSize:20,7 GB, free space: 154,3 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector/_themes/Elevate4 (User-Defined)[‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‎SD card‌‌‌‌‌‎/Locus/mapsVector/_themes/Elevate4[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4/document/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4, Av:true, files:418, dirs:1, totalFileSize:3,4 MB, free space: 154,3 GB, files on device: 0)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:119 B, free space: 56,8 GB, files on device: 13278715)
  - GPX: /Download/GPX (User-Defined)[/Download/GPX[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX/document/primary%3ADownload%2FGPX, Av:true, files:6, dirs:0, totalFileSize:291,2 KB, free space: 56,8 GB, files on device: 13278715)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=16, dirs:>=7, totalFileSize:>=2,2 GB, free space: 56,8 GB, files on device: 13278715)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:26, dirs:0, totalFileSize:86,5 KB, free space: 56,8 GB, files on device: 13278715)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 56,8 GB, files on device: 13278715)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:15, dirs:1, totalFileSize:582,3 MB, free space: 56,8 GB, files on device: 13278715)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:5, dirs:0, totalFileSize:582,2 MB, free space: 56,8 GB, files on device: 13278715)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 56,8 GB, files on device: -1)
- Map render theme path: Elevate F140 L120 S110 EB.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX (24 May, 00:17):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes%2FElevate4 (20 May, 23:38):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (20 May, 23:37):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector (20 May, 23:37):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v95, Size:436,5 MB) on system internal storage
--- End of system information ---
```

## Additional context 
BTW: Would it be possible to make the ``ADD FILTER CRITERIA`` button "Not scrollable"?
It's a bit annoying to always scroll up to add a new criterion ...

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo:
* was there more than onw filter criterion involved in the situation (did you filter for other things than "FOUND=NO" at the same time)? I am asking because I want to exclude errors in e.g. "parenthesation" in SQL building.
* do you feel the one affected cache was wrongly filtered because of the write note or because of a previously existing "DNF" log?

**Comment by eddiemuc** [comment]
On another note: I realize there are a lot of filter-related task currently to do (and one probable SAF bug). Unfortunately I have a very hard time currently/this week to find coding time. I would appreciate any help on those things so we can get the current release fixed.

**Comment by murggel** [comment]
> On another note: I realize there are a lot of filter-related task currently to do (and one probable SAF bug). Unfortunately I have a very hard time currently/this week to find coding time. I would appreciate any help on those things so we can get the current release fixed.

@eddiemuc which issues would be suitable to give you a helping hand? So I am not so deep in filter-framework...

**Comment by eddiemuc** [comment]
It took me a while to solve this one...

@MagpieFourtyTwo : since the state of the cache in question also contains "Not Found", I conclude that you logged a DNF for this cache sometime in the past before?
The error was that the same DB field is used to store both "found" and "DNF" state (found=1, DNF=-1, neither found nor DNF = 0) and I filtered for value 0 only before.

PR #11262 will fix this.

**Comment by MagpieFourtyTwo** [comment]
> @MagpieFourtyTwo : since the state of the cache in question also contains "Not Found", I conclude that you logged a DNF for this cache sometime in the past before?

Yes. That's why I saved the ``Write Note``. Sorry for not explicitly mentioning it. Seems as if my thoughts were not as obvious as I thought. ;)

A kind of similar thing I observed the other day:
- store a cache offline which has been disabled first (here: by the Owner), and has finally been archived (here: by Reviewer),
  in my case it's [GC97CN6](https://coord.info/GC97CN6) (don't know if this "works" with not stored stuff, too),
- open live map and move to the region of the cache in question
- setup a status filter to mirror my standard global settings: ``Show Disabled``, ``Hide Archived``, ``Found=NO``
- have a look at the cache saved above ...
Although the filter says ``Hide Archived`` the cache will still show up on the map.

Maybe a similar "problem" as with this ``Found=No & DNF logged`` problem?

BTW: Can we possibly extend the displayed filter string, if there is plenty of room, anyway?
This ``Status: 3 items`` is feeling a little bit lonely in my header row ...  ;)

**Comment by MagpieFourtyTwo** [comment]
Ah, forgot the conclusion: ``Archived`` should have higher prio than ``Disabled``, thus if ``Hide Archived`` *and* ``Show Disabled``  is set, an archived cache should not be shown, even if it additionally has ``Disabled`` set (which in fact sounds pretty awkward, anyway, but obviously it's possible).

Ah, another strange thing with this cache: After a fresh start of c:geo, the cache's status is shown as ``Archived, Disabled``.
As soon as I refresh the offline stored listing, the status changes to ``Archived``.
Leaving the listing and re-opening it again, the status is ``Archived, Disabled`` again ... strange, too.
