### ISSUE TITLE
Filter: Allow direct date input (in addition to date picker)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11223]
From support email, ticket #714401

## What function are you missing
allow direct date input (in addition to date picker component)

---

Einen schönen guten Morgen,

erst einmal ein ganz großes Lob für die neue BETA-Version! Auf die neue Filterfunktion nach Cachetypen etc. habe ich seit Jahren gewartet. Jetzt ist c:geo quasi perfekt.

Eine kleine Verbesserung ist wünschenswert beim Filterkriterium Versteckdatum.
Hier kann momentan nur aus einem Kalender ausgewählt werden, das bedeutet bei einem weiter zurück liegenden Datum eine ziemliche Blätterei.
Eine freie Datumseingabe wäre hier eindeutig komfortabler.

Beste Grüße - ...

**Comment by fm-sys** [comment]
I don't think a direct date input would be a good idea. 

Can you tell him, that he can select the year via clicking on it? 

But we could indeed optimize the click target. Maybe, by allowing a click on the complete date instead of only the year? So the chance that users  discover this feature is higher... 

![Screenshot_20210713_222500_copy_540x1170](https://user-images.githubusercontent.com/64581222/125519950-3ec781d5-5ec2-4589-b2a1-87114eeabc41.jpg)

**Comment by moving-bits** [comment]
> Can you tell him, that he can select the year via clicking on it?

Thanks, didn't know that. Have added it to my reply to the user.

**Comment by eddiemuc** [comment]
The material date picker allows also for direct date input, and afai remember material.io claims that direct date input possibility should always be provided from UI perspective.

My problem with the material picker was that it did not allow for unsetting a date. Also I had problems with it's visualisation, it behaved strange in appcompat environment. But maybe this could be re-investigated.

**Comment by fm-sys** [comment]
Oh, is it not yet the material component? Than we should indeed try to switch...

**Comment by fm-sys** [comment]
![grafik](https://user-images.githubusercontent.com/64581222/125862243-2544d2e4-f3c8-4075-bb94-d130bf345738.png)

The material date input looks quite nice, however I didn't found a solution for the "reset" button. But why does it need to be part of the dialog at all? I would suggest adding a reset button directly to the date range selector instead.

e.g. this icon: 
![grafik](https://user-images.githubusercontent.com/64581222/125862922-982a705a-58d2-42f3-9963-06776050562d.png)

Or maybe even missusing a `textInputLayout`?
![grafik](https://user-images.githubusercontent.com/64581222/125863228-f42eef15-c93e-4663-9d27-6a400319aac3.png)

**Comment by eddiemuc** [comment]
Good idea!

**Comment by fm-sys** [comment]
Which one do you prefer - textinputLayout or the extra button solution? 

I would like to finish the PR for it today, but I'm still totally indecisive which component I should use... 😅

**Comment by eddiemuc** [comment]
If you can get the textInputLayout to not allow direct input but just open the date picker on click, then I would personally prefer this solution graphically. (I don't know whether one can set the textInput to "disabled" but still allow the "delete" click to work)

If this is not so easy, then the other solution.

**Comment by eddiemuc** [comment]
Oh, and thinking ahead: would this also be something to replace e.g. the date and time picker buttons in Offline Log dialog? (without the "clear" option of course)

**Comment by eddiemuc** [comment]
@murggel this would be an issue You could tackle related to filter framework

**Comment by fm-sys** [comment]
Sorry that I had forgotten to assign the issue to me. My PR is nearly ready...

**Comment by fm-sys** [comment]
> If this is not so easy, then the other solution. 

It was indeed not that easy as I thought. Problem is, that the "x" is only shown if the text layout has focus (clicked). But this should already open the date chooser dialog...

So I will use a borderless button instead:

![grafik](https://user-images.githubusercontent.com/64581222/126048999-a46d35ed-8bef-4977-9d2c-2cd679dfeb73.png)
