### ISSUE TITLE
Second Icon for Quick Setting Menu

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#11222]
## What function are you missing
The new quick setting menu is only offering an "x" in the upper left corner - such an icon is normally used to close a dialog without saving anything. 
In the current release this "x" is closing the quick settings menu and saving your settings. 

## Suggested solution
Add a second button and assign one the save function and the other one the decline function 

## Alternatives/workarounds
No workaround known

**Comment by fm-sys** [comment]
The options in the popup are IMHO not critical enough for a separate cancel button. Furthermore, the popup can be closed with backpress as well which is not the case for screens which provide a cancel option.


Only solution I can think of would be replacing the "x" with a "v" button like done in Google Maps:

![Screenshot_20210713_221650](https://user-images.githubusercontent.com/64581222/125519003-cdd197cf-5207-43de-a7ec-69c602ab5298.jpg)

But IMHO it's easy to understand how the popup can be closed, so no need to change anything. Actually, the "x" cannot really be misinterpreted as it is placed on the left like other "navigation actions" while the cancel option is always placed on the right side.

**Comment by Lineflyer** [comment]
But unlike an "X" a "V" would make pretty clear that its no dialog which needs to be confirmed but just closed.

**Comment by fm-sys** [comment]
Yes, we can definitely use a "v". Would be fine for me as well, as long as we don't add a "close without save" action to the popup. Always keep things simple ;)

**Comment by wolverine007** [comment]
Just the location of an icon is not logical to me. 
But like suggested, replacing the "X" with "V" sounds valid and logic to me as well 👍🏼
