### ISSUE TITLE
system information - "Hide caches" bad formatting

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11229]
## Bug description 

The list of 'Hide caches" is terrible formatted, see eg.

~~~
Program settings:
-------
- Hide caches: own/ foundarchived
~~~

There is a '/' after 'own' (left from former "own/found" ?) and no space after 'found'.

**Comment by fm-sys** [comment]
This will get obsolete anyway according to our filter framework plans... But let's keep the issue open as a reminder that we remove this information from sys info.

**Comment by eddiemuc** [comment]
Obsolte and removed with #11252
