### ISSUE TITLE
Store regExpr to fetch data from web-site into an own "service" to avoid the necessity of a release if changes happen

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11235]
BTW - how about to move those regExpr into an own "service" to avoid the necessity of a release if those changes happen...

_Originally posted by @murggel in https://github.com/cgeo/cgeo/issues/11232#issuecomment-880154479_

Then only the service has to be updated but not all the user-installations

**Comment by murggel** [comment]
Or would it be possible to have a config-file and only this can be updated in such a case?

**Comment by fm-sys** [comment]
For sure, such config changes could theoretically be rolled out via our status message server if we implement it that way in c:geo. But I don't know if this could be a critical security issue in theory if someone would tries to hack us and introduce some malicious regex...?!

**Comment by baiti** [comment]
let me pick up the thought of "a service". The idea is to make the cgeo binary resilient against "scraping changes". So we could instantiate a server side proxy that implements a downstream API to cgeo and an upstream scraping engine.

Changes to the UI would only impact the proxy. No change to the installed cgeo binary would be necessary - ever.

In theory, we could design the downstream API semantically equivalent to what is known as GC HQ's "partner API", which would allow us to seamlessly switch to that technology if and once other surrounding circumstances have been resolved appropriately.

Such a proxy would have to meet some not so trivial requirements though. First of all, it is a single point of failure. If it is down, cgeo would be essentially unusable for all users. Second, it would have to meet significant scalability requirements as 10k to 50k users could be sending requests to that proxy in busy times in parallel. Last not least, each API opens up an attack vector for potential abuse. Plus there might be legal issues then, a can of worms perhaps.

On the other hand, changes to the UI is a never ending story and happening every day in the industry. UIs live, they are not meant to be consumed programmatically. It is not a matter of ToUs, it is a technical necessity for vitality.

BTW: Is this an issue or should it be converted to a discussion?

**Comment by murggel** [comment]
Can be converted to a discussion and reopened if necessary.
