### ISSUE TITLE
Map marker redesign: adapt marker positioning

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11231]
As discussed between @ztNFny and me:

## What function are you missing
We need to/should adapt our marker position logic while refactoring our map marker layouts.
Currently the service markers are sort of "off-set", as they have the marker circle and the position indicator at the bottom. There's no other space around it, so if we want to place a type marker on top of it, we cannot center it, but have to calculate an offset. Same is true for the overlay markers, which have to take this offset into account.

## Suggested solution
- create new service marker icons which have the circle centered by applying a space top/left/right the same size as the position indicator has (=> separate issue: refactor map marker icons)
- adapt/simplify map marker and overlay positioning methods to work with such a centered icon approach (=> this issue)

**Comment by ztNFny** [comment]
The way you're proposing seems to be the already implemented way, but the outcome isn't as expected.
I changed the type icons alignment to bottom left
insetsBuilder.withInset(new InsetBuilder(mainMarkerId, VERTICAL.BOTTOM, HORIZONTAL.LEFT, doubleSize));
and this is the result:
![image](https://user-images.githubusercontent.com/1258173/125990609-52f2168f-a7a0-448a-8c21-dd855b2aff74.png)

There's some padding being added in InsetBuilder.insetHelper. So it's probably only that function that needs to be modified for the SVG icons.

**Comment by moving-bits** [comment]
What happens if you change `final int vDelta = height/10;` to `final int vDelta = 0;` in `InsetBuilder.insetHelper`?

**Comment by ztNFny** [comment]
Then it's centered, as expected. We'll have to wait for the new icons to be finished to determine the new padding.
Should i just take care of that together with the icons, as i find it fitting?

**Comment by moving-bits** [comment]
Yeah, does make sense to do both updating icons and icon positioning in a single commit.

**Comment by ztNFny** [comment]
something is off with the positioning, with vDelta=0 the icon is not exactly centered but moved slightly to the upper left
![image](https://user-images.githubusercontent.com/1258173/126009134-280521a1-91ba-4ea1-be3c-70feff575ca8.png)

@moving-bits any idea what's going on here? Screenshot is from https://github.com/ztNFny/cgeo/tree/7dd5abeb45ffc577004fa3e03ea9564fb5f4f778

**Comment by moving-bits** [comment]
Calculation is done in `InsetBuilder.insetHelper`, can't find any suspicious things at a quick glance:

https://github.com/cgeo/cgeo/blob/51dd203b8a45a169bb69bf09bda20be6773ad00a/main/src/cgeo/geocaching/utils/builders/InsetBuilder.java#L65-L95

width/height are the dimensions for the base drawable, and iWidth/iHeight those for the inset

**Comment by ztNFny** [comment]
I think the issue could be that it's calculating ints and depending on the screen dpi settings those vectors get rounded. Can that int be changed to float?

**Comment by ztNFny** [comment]
@moving-bits it's depending on the device DPI. I tested with a few different ones and in some cases the calculation returns a float which is then cast to int.
With the current icons that's not noticable, but with the new ones it is very much.

This needs to be changed to a method accepting float - or the whole Inset stuff would have to be rewritten :-o

**Comment by moving-bits** [comment]
For which parts do you need floats? (Which method / which parameter?)

FYI: The calculated inset get fed into `LayerDrawable.setLayerInset`, which works with `int` only.

**Comment by ztNFny** [comment]
> For which parts do you need floats? (Which method / which parameter?)
> 
> FYI: The calculated inset get fed into `LayerDrawable.setLayerInset`, which works with `int` only.

Yeah, thats why i said it might need to be rewritten completly.

Important is that at the end stuff is centered.

**Comment by moving-bits** [comment]
I have a solution which implements `setLayerGravity` for API 23+, and stays with the current method for positioning for API < 23 - will update the PR.
