### ISSUE TITLE
GCVote seems missing in our new search?

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11246]
![image](https://user-images.githubusercontent.com/949669/125344726-efd05580-e357-11eb-9f12-b193571887a4.png)

On the screenshots, it seems like the GCVote is missing on our new UI? Or was there a difference in the way the screenshots where created?

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/discussions/11069#discussioncomment-995496_

**Comment by fm-sys** [comment]
Interesting and good catch indeed. 
On both versions I did not enter my GCVote credentials, but this is no problem to request votes.
Not sure if our old nearby search requested GCVote but the new search does not? That could explain. The existing GCVote for GC7Q8TF is due to the fact, that the cache was opened already and thus the vote still existing.

@eddiemuc Did you accidentally drop GCVOte retrieval on (nearby) search?

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/discussions/11069#discussioncomment-995549_

**Comment by eddiemuc** [comment]
Where would I see GCVote on the screen if it were available? Can someone post a comparing screenshot with GCVote from current productive version?

**Comment by SammysHP** [comment]
It's the color of the box at the right.

**Comment by fm-sys** [comment]
Exactly. Took a while to understand the purpose of the fav counter background for me as well 😅

Black means no data, red an average vote <2, brown <4 and green >4 (or similar)

**Comment by eddiemuc** [comment]
Another dump question: is GCVote only relevant for GC caches (as the name suggests) or also for caches of other platforms/services?

**Comment by eddiemuc** [comment]
Should be fixes with PR #11259

**Comment by Lineflyer** [comment]
> Another dump question: is GCVote only relevant for GC caches (as the name suggests) or also for caches of other platforms/services?

GCVote only supports GC. Not sure if the "could by" successor will support more.
