### ISSUE TITLE
Map doesn't support vector drawables for markers

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11248]
Replace "marker.png" with a vector drawable -> crash on loading the map:

    java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
        at cgeo.geocaching.utils.CompactIconModeUtils.setCompactIconModeThreshold(CompactIconModeUtils.java:24)
        at cgeo.geocaching.maps.CGeoMap.initializeMap(CGeoMap.java:496)

@moving-bits any chance you could take a look at that? It's a blocker for me.

**Comment by moving-bits** [comment]
What this functions tries to achieve is to calculate something like "how many drawables of the size of a "marker" does it take to fill up one fourth of the screen" (assumed they are rectangular, so considering height/width only).

How can we determine (programmatically) width and height of a svg in current context?

**Comment by ztNFny** [comment]
Same problem in CompassMiniView

    public void onAttachedToWindow() {
        super.onAttachedToWindow();
        if (instances++ == 0) {
            final int drawable = isInEditMode() || !Settings.isLightSkin(getContext()) ? R.drawable.compass_arrow_mini_white : R.drawable.compass_arrow_mini_black;
            compassArrow = BitmapFactory.decodeResource(getResources(), drawable);
            compassArrowWidth = compassArrow.getWidth();
            compassArrowHeight = compassArrow.getWidth();
        }
    }

**Comment by murggel** [comment]
> What this functions tries to achieve is to calculate something like "how many drawables of the size of a "marker" does it take to fill up one fourth of the screen" (assumed they are rectangular, so considering height/width only).
> 
> How can we determine (programmatically) width and height of a svg in current context?
> 
> --
> 
> Edit: Conversion to a bitmap is done only for calculation, not needed for drawing.

Is the calculation still needed when using svg? Or can we define a minimum size and calculate the size for the svg for the given amount of markers?

**Comment by moving-bits** [comment]
I probably have solutions for both cases, PR will follow. Should work with both PNG and SVG images. Target to `master`?
