### ISSUE TITLE
Modified coords not recognized on updating/downloading cache data

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11243]
Reported on support, ticket #892218

## Bug description 
User-defined coordinates set on the website are not recognized by c:geo on downloading / updating a cache. Original coords are shown instead.

## c:geo version 
Reported for 2021.06.23 and retested with current state of `release` branch

## Reproducible 
yes

**Comment by Lineflyer** [comment]
OK, that should go the same way as #11232 then probably.

**Comment by murggel** [comment]
Hm - working for me...

Is it for BM or Premium?

**Comment by murggel** [comment]
For me restoring of the original coordinates does not work - cgeo still has the former changed coords and not the restored ones

**Comment by moving-bits** [comment]
> Is it for BM or Premium?

Premium (in both cases)

**Comment by murggel** [comment]
Are the coordinates changed the first time on the web-site or a second time?

I can reproduce it as mentioned above that if an original waypoint in cgeo already exist the coordinates are not updated.
But that does not match with "original coords are still shown" from user...

**Comment by murggel** [comment]
@moving-bits you can reproduce it?

**Comment by Lineflyer** [comment]
I can reproduce neither scenario.
Its working for me for BM and PM in both directions.
For PM I also tested changing it on the website another time and refreshing in c:geo. Looks all good.

**Comment by moving-bits** [comment]
> @moving-bits you can reproduce it?

I was able to reproduce using the following steps (sorry, should have mentioned them while opening the issue):
- Open a cache on gc.com map in the web browser
- change its coordinates and store the changed coordinates
- open the same cache in c:geo

c:geo will show the unchanged coordinates.

In my test case, the cache has not been stored in c:geo before this test.

**Comment by murggel** [comment]
Can't reproduce with unstored cache either.

**Comment by balu2003** [comment]
I'm PM and use version 2021.06.23
I have changed the coords here in this listing: https://coord.info/GC800RJ
And than (this cache was never opend in cgeo) search with "Search by geo code" and open the listing (not stored)
The changed coords were displayed correctly.

**Comment by balu2003** [comment]
Another test with some mysteries that I have only looked at on the website and changed the coordinates there. Then in cgeo on the Livemap, displayed as a list/table, stored them in a new  list  (**before** I open any of thes caches in Detail). 
Back in LiveMap. Then saw on the map that some caches are not marked with this red triangle, although they have changed coordinates.
Open one of these caches in cgeo and reload the listing (refresh). 
The coordinates shown in cgeo are still the original listing coords, although I see changed coordinates on the website.

**Comment by balu2003** [comment]
Forgot all I have wrote in my last  posting
Unfortunately I tried with a cache of the same name from opencaching.com. He was shown on the LiveMap too. Obviously that doesn't work.
With the cache from gc.com, the changed coords in cgeo are correctly displayed

**Comment by moving-bits** [comment]
\*blush\*

I've to correct myself: If you use different user accounts on website and within c:geo, it's totally to be expected that c:geo does not recognize your changed coordinates... - Seems to work as expected, so let's close here.
