### ISSUE TITLE
Geocode input in LogTrackable Activity uses wrong style

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11257]
Geocode input in `LogTrackableActivity` doesn't use correct style:

![grafik](https://user-images.githubusercontent.com/64581222/126049453-691f8c1b-e21b-4bfb-871d-0e951e516c7e.png)
![grafik](https://user-images.githubusercontent.com/64581222/126049974-7f8873da-0d9c-4302-b102-e91acdad0953.png)

**Comment by Lineflyer** [comment]
I tried to look into it, but it seems a bit to complex for me.
In fact the styling is applied in the corresponding XML, but I guess the class `AutoCompleteTextView` needs to be changed to also inherit/use that style?!

Besides that, the margin defined for the geocode text field should be removed to align it with the other text fields.

I am afraid, someone else needs to dive deeper into that. Still learning...

**Comment by fm-sys** [comment]
In fact, it is working with other AutoCompleteTextViews (see e.g. `SearchActivity`). I also tried finding a quick solution before opening this issue, but I did not had luck either... Very strange!

**Comment by moving-bits** [comment]
How do you reach this activity with "geocode" field visible?

**Comment by fm-sys** [comment]
I have reached it via entering a GeoKrety GKxxxx code...

**Comment by Lineflyer** [comment]
and setting log type to e.g. "Visited"

**Comment by moving-bits** [comment]
Thanks for pointing me in the right direction. Problem solved, PR is created...
