### ISSUE TITLE
Found OC caches not shown as found in search results

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11253]
Current nightly...did not check before:

- Have OC.de active
- Have some found OC caches around you but not stored in c:geo (probably also reproducible by searching based on coords)
-Perform nearby search

Result:
Those OC caches are shown in results but not as found. Once you open the details they show up as found correctly.

**Comment by eddiemuc** [comment]
confirmed, will be fixed

**Comment by eddiemuc** [comment]
fixed with #11252
