### ISSUE TITLE
Codacy: "Unnecessary parentheses around expression" warnings are too strict

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#11261]
Recently, Codacy starts complaining about "unnecessary parentheses" used in boolean expressions, Things like e.g. shown in following screenshot:

![image](https://user-images.githubusercontent.com/6909759/126112854-8b9eebb9-778e-4cc7-b23d-01acf7ae3c3f.png)

The underlying rule is `Checkstyle_UnnecessaryParentheses`:

![image](https://user-images.githubusercontent.com/6909759/126113027-c3098b6c-2d20-4d64-930e-ebf44f16332a.png)

I agree that this is in general a useful rules, and I also agree that in the given examples the parenthesis shall be removed.

But for boolean expressions like the above I find the parentheses extremely helpful for understanding the logic behind them - although they are maybe  not be strictly necessary because of operator precedence?

Would it be ok to "lighten" that rule?

And on a second note: if yes, how can I do that??? AFAICS Codacy uses our checkstyle rule file, but Jenkins does not complain about these things...

A third thing: I miss edit rights for Codacy, it always tells me I have to be "admin" to do something. Is there any way to change this?

**Comment by moving-bits** [comment]
I'd vote for lightening or even lifting this rule. Extra brackets can add much to code readability, and if I have to decide "black or white" I would say more self-explanatory code by extra brackets outweights some unnecessary brackets in other places.

**Comment by eddiemuc** [comment]
Again I have a blocking codacy-issue related to this rule where I really thing parenthesis increase readability:

![image](https://user-images.githubusercontent.com/6909759/127740946-6cca7f4b-3dcc-4dc9-aec3-d33faa030d79.png)

Can please someone with the needed Codacy-rights deactivate this rule?
(Or is there any other way to deactivate it? E.g. by changing some config file in our repo?)

**Comment by bekuno** [comment]
Looks strange.
In checkstyle.xml it is defined as

~~~
<module name="UnnecessaryParentheses">

<property name="severity" value="info" />

</module>
~~~

**Comment by bekuno** [comment]
@eddiemuc 
Please create a dummy PR with such a statement, so that I (or @Lineflyer ) can have a look at codacy.
Either @Lineflyer or the cgeo-bot has admin rights, I do not have.

**Comment by bekuno** [comment]
At codacy the checkstyle rules are set to "configuration file" from the project.

**Comment by eddiemuc** [comment]
Hi @bekuno , I created PR #11401 for this (please don't merge it :-))

Here is the direct link to the codacy result: https://app.codacy.com/gh/cgeo/cgeo/pullRequest?prid=7849571

**Comment by Lineflyer** [comment]
It refers to a check for "Checkstyle" which on Codacy configuration says, that it follows the repository configuration file:

![image](https://user-images.githubusercontent.com/949669/127918602-76852b6d-60b9-4add-ab11-89bd38ed7a00.png)

**Comment by Lineflyer** [comment]
OK, here is the thing:
I disabled checkstyle analysis, enabled it again
Then I switched to pattern list and back to configuration file
Then I triggered reanalyze of the PR.

Now its green...

**Comment by eddiemuc** [comment]
Well the way to the solution seems very traditional ("have you tried turning it off and on again?" https://youtu.be/nn2FB1P_Mn8), but if it works it works...

Shall I close this issue then?

**Comment by Lineflyer** [comment]
> have you tried turning it off and on again?" https://youtu.be/nn2FB1P_Mn8),

Exactly :)

**Comment by bekuno** [comment]
@Lineflyer 
The Codacy shows now Checkstyle as disabled.
![image](https://user-images.githubusercontent.com/32555742/128415780-aa5cf265-a724-439d-82de-bf8e809a72c7.png)
Please check if it is really disabled or a error in this display.

**Comment by Lineflyer** [comment]
Pretty sure I left it enabled, but I found the same issue and just enabled it again.

**Comment by eddiemuc** [comment]
Unfortunately enabling checkstyle again leads to this issue being present again (my dummy PR for this issue is now red again). So I reopen this issue.

Any chance then that we just disable the parenthesis rule in our checkstyle? It seems codacy interprets this rule way too strict somehow (while Jenkins doesn't)

**Comment by bekuno** [comment]
@eddiemuc A solution is on the way. Please see #11399

**Comment by eddiemuc** [comment]
@bekuno ok I linked the PR to this issue

**Comment by eddiemuc** [comment]
In PR #11425 I see many other examples of "unnecessary parenthesis" which I frankly find quite useful for code readability. 

What about just removing this rule completely from checkstyle?

**Comment by bekuno** [comment]
From the "thumbs up" a majority would remove this check.
I am neutral here.

Before we do it - a question raised to me - could we have a negative behavior without this rule?

**Comment by moving-bits** [comment]
> Before we do it - a question raised to me - could we have a negative behavior without this rule?

If I'm not mistaken the worst that could happen would be some unnecessary parentheses, making the code less readable. But there should no functional impact (e. g. performance penalty), as the compiler removes those unnecessary parentheses. So no blocker from this side, AFAICS.

**Comment by bekuno** [comment]
> 
> 
> > Before we do it - a question raised to me - could we have a negative behavior without this rule?
> 
> If I'm not mistaken the worst that could happen would be some unnecessary parentheses, making the code less readable. But there should no functional impact (e. g. performance penalty), as the compiler removes those unnecessary parentheses. So no blocker from this side, AFAICS.

So it's the same perception that I have.
Then lets remove the entry for `UnnecessaryParentheses`. 

I would leave the Checkstyle configuration on **CI** (for PR) as it is now. That means to not fail on severity" ="info".
