### ISSUE TITLE
Hyperlink in some strings not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11266]
While working on support tickets I noticed, that e.g.

```
<string name="err_unknown">Unknown error. Please refer to our <a href="https://www.cgeo.org/faq#login-failed">FAQ</a> for guidance.</string>
```
is shown without any linkage.
Seems to already affect our current release 2021.07.15 or 2021.06.23.

**Comment by Lineflyer** [comment]
Can someone investigate what is needed to fix it?
Do we need markdown instead of html?

Would be good to get it fixed before release as users end up on support as the FAQ is no longer linked from those errors.

**Comment by moving-bits** [comment]
Did you find more strings that do not work? (I'm looking for some easy-to-test one)

**Comment by eddiemuc** [comment]
I debugged into the case of `StatusCode.UNKNOWN_ERROR` which uses `R.strings.err_unknown` as its label.

The problem here is that the parameter `R.strings.err_unknown` is converted to a String and is then used as a parameter of another resource string (`R.string.info_log_post_failed_reason`). With this String conversion, the "html formatting" (including link) gets lost.

**Comment by Lineflyer** [comment]
Strange enough it was working some time back in the past.

**Comment by eddiemuc** [comment]
Can't tell you about the past unfortunately. Maybe value was not used as a parameter back then (but directly as dialog message)?

**Comment by eddiemuc** [comment]
I created PR #11330 in which I extended TextParam a bit to support concatenated CharSequences (so they don't loose their format) and used the new style for error message dialog for Log Upload error.

@Lineflyer where else has this occured to you?

**Comment by Lineflyer** [comment]
I did only see the problem on the various login error message, where the FAQ should have been hyperlinked.

**Comment by eddiemuc** [comment]
> I did only see the problem on the various login error message, where the FAQ should have been hyperlinked.

Ok, I added this dialog to the PR

**Comment by Lineflyer** [comment]
The fix should also cover (if affected):
 <string name="err_captcha">
<string name="err_comm">

**Comment by eddiemuc** [comment]
> The fix should also cover (if affected):
> 
> ```
> <string name="err_captcha">
> <string name="err_comm">
> ```

The fix covers all affected strings. However, it has to be applied to all affected dialogs which use html strings as parameter of other strings. As of now I applied it to the failed login dialog and the "failure on log upload" dialog. It is hard to find all affected places though
