### ISSUE TITLE
Log summary only updated after re-entering cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11272]
2021.07.17-RC2:

- Open a saved cache which has new finds since saving it
- Swipe to logbook
- Note the log summary figures shown (e.g. 123x found, 2x deactivated, etc.)
- Pull down to refresh

Result:
- The logbook is updated with the new finds since last refresh
- The log summary however stays unchanged. Only if you close the cache and open it again the updated figures are shown

**Comment by moving-bits** [comment]
list's header view did not get updated, PR will follow
