### ISSUE TITLE
Live filter setting not shown in filter after applying via map quick setttings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11274]
2021.07.20-NB

This case seems not reproducible but happend to me while testing:
- Initial state: No live filter set, No offline filter set
- Open map
- Open quick settings
- Select to hide found, owned and disabled
- Return to map
- Filtering works on map and filter status bar shows "Status: 3 items"
- Click on status bar

Result:
- Filter shows no active filtering (all status elements are active, respectively set to "All")
- When trying to leave the filter screen via back key, it warns, that settings will be lost
- When confirming the filter you return to live map with unchanged state (filter works, status bar shown as before)
- Enter the filter again, still the same problem (no filtering shown)

- After some tries it suddenly worked normal (filtering shown)

It looks a bit like only the filter selection shown on the filter screen does not reflect the real state, while everything under the hood is working as expected.

After the problem disappeared I was not able to reproduce it again.

**Comment by eddiemuc** [comment]
Confirmed. Can reproduce this behaviour when I delete previously stored filters from settings first

**Comment by eddiemuc** [comment]
Problem was that in this special case the (initial) filter consists just of a single filter expression. The cachefilteractivity could only deal with logical expressions (AND or OR, optionally surrounded by a NOT). Will be fixed

**Comment by eddiemuc** [comment]
Fixed with PR #11285
