### ISSUE TITLE
Add [does not contain] to text filters 

### ISSUE THREAD

**Issue by RoNoLo** [cgeo/cgeo#11276]
## What function are you missing
I would like to exclude caches from the map by word/regex filter of the title and description.

As a father with two little kids I would like to exclude certain caches. Morst of them are T5, because they are high up in the trees and usually contain some words like "angel cache", "angeln" or similar in other languages. As long as geocaching.com has no category for these kind of caches (they are just all mushed into the T5 rating), I wish there were a way to still exclude them from my map of available caches. 

## Suggested solution
A text filter, which is applied to title and description, which can exclude caches from viewing them (like a postprocessing after retrieving them from the officially APIs). My use case would be a list of words or regular expressions, which remove all "tree fishing" (German: angel caches) from my view.

## Alternatives/workarounds
A filter of "terrain" ratings would serve _me_ probably evenly well, because everything with a rating 5 is out of the question for me and my children.

## Additional context
Not really, just that I wish c:geo would allow me to filter even more which caches I want to see and find. Another example could be caches were the description contains that you have to bring a "bottle" or "batteries" or similar.

**Comment by eddiemuc** [comment]
Hi @RoNoLo, you might want to take a look at the new filter system which we plan to introduce in next release. You can already experience this system in our current beta version (information on how to become a beta tester can be found here: https://www.cgeo.org/development)

A draft version of the new filter manual can be found here: https://manual.cgeo.org/en/cachefilter (currently english only).

Would this help your use case?

![image](https://user-images.githubusercontent.com/6909759/126335249-b03dd273-4af4-4823-a5c6-c4d91b90e04e.png)

**Comment by RoNoLo** [comment]
Thanks for your answer.

By looking at the screenshot I assume, that it's a collection of different filters which are connected via a pipe (the result will be piped to the next filter) until all filters are processed, thus every possible combination of Only Tradi, but less that T5 and also not containing the words "bottle", "angel" are inside the description are matched.

If that sums up what is in the planning I would be very pleased with this type of update. 

You could close this issue, if that is the case.

**Comment by murggel** [comment]
@eddiemuc I think the selection "does not contain" is missing for those text-fields ...

**Comment by RoNoLo** [comment]
Based on the screenshot I *assume* that the [CONTAINS] button can be switched to other operators, like "does not contains", "regex", ...

**Comment by fm-sys** [comment]
Indeed, "does not contain" would be nice to have for consistency...

![Screenshot_20210720_201830_cgeo geocaching](https://user-images.githubusercontent.com/64581222/126375519-403f45d3-1d35-45ea-932f-3412ab661995.png)

**Comment by fm-sys** [comment]
> You could close this issue, if that is the case.

I've renamed the issue to better describe which feature is still missing...

**Comment by eddiemuc** [comment]
The "negation" feature for single filter criterias seems to be needed for quite a lot of filters, and I includes it for quite some criterias already (as include/exclude switch) e.g. for attribute filter.

I wonder whether we should include this in a more generic way (in advanced mode)? E.g. a "negate" button next to the "clear" button and the "drag" button for all filters?

**Comment by fm-sys** [comment]
> E.g. a "negate" button next to the "clear" button and the "drag" button for all filters?

I don't think that's a good idea. I just looked through all filters but did not found a single filer (except the text filters for sure) where a negation would make sense but is not yet implemented. And "is not contained" is IMHO way easier to understand than "invert(is contained)"

**Comment by fm-sys** [comment]
I would like to work on this one myself, to have a "first good issue" for the filter framework. However, it might take a while...

**Comment by eddiemuc** [comment]
> > E.g. a "negate" button next to the "clear" button and the "drag" button for all filters?
> 
> I don't think that's a good idea. I just looked through all filters but did not found a single filer (except the text filters for sure) where a negation would make sense but is not yet implemented. And "is not contained" is IMHO way easier to understand than "invert(is contained)"

Well of course this would only make sense if all places where negation is currently implemented "individually" are also changed to the new system.

Already inversable: attributes, log entry

When converting textfilter, following filters will profit:
Name, description, personal note, offline log

From existing, non-inversable filters I think the following ones would profit imho:
* Stored lists
* Origin
* Distance

**Comment by eddiemuc** [comment]
> I would like to work on this one myself, to have a "good first issue" for the filter framework. However, it might take a while...
> 
> Starting point: 
> https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/filters/core/StringFilter.java

Sure, I am looking forward to it :-)

**Comment by fm-sys** [comment]
For `Stored lists/Origin` I agree, that selecting everything except a specific entry is kind of ugly (-> a negation would make sense).

For Distance (and D/T) it does however IMHO not make sense as it is implemented as range slider supporting the selection of a min and max value. Why should someone filter for caches, which are e.g. NOT in a range if 20-30km?

Only reason why I'm against a generic negation possibility is, that it often simply doesn't make sense and it is harder to understand for users, than a "is contained / is not contained" selection.

**Comment by eddiemuc** [comment]
A generic inverse option could easily be implemented in code (using NOT filter under the hood), but only get enabled on a per-filter-criterion-type-base in the GUI. For those criterions where this is enabled, however, the GUI should be the same (e.g. an include/exclude switch or something else) and should be programmed only one time at one place (which would be easily achievable).

**Comment by fm-sys** [comment]
> For those criterions where this is enabled, however, the GUI should be the same

I really good can understand the purpose of such a generic implementation, and it might be a good idea for other filters. 

However, as it can be seen in  #10671 it is already today hard to recognize that the "contains" button is in fact a spinner. Adding even more UI elements would make the situation even worse...

If we would add a generic negation possibility to the filter, this would result in filter possibilities like "does not end with" etc., which is IMHO somewhat exaggerated. A sign of good UI is also that it is not too overloaded and does not overwhelm users. For our text filters, a new "does not contain" option inside the spinner is definitely UI wise the lighter one...

**Comment by eddiemuc** [comment]
I don't want to make this issue bigger than necessary :-)
I am also fine with a "simple" implementation e.g. adding a "does not contain" option.

Maybe, if you have a good idea for it, you can replace the "button"-looking drop-down list with a better-looking alternative while at it?

**Comment by moving-bits** [comment]
Regarding the "spinner buttons":

We do have such buttons in several places in c:geo, so it might make sense to create a separate style for it.
I've just looked up at material.io: You can add an icon to your button, placing it either to the right or to the left of the text label. So we could create a "spinner button" style with an outlined material button and the typical "spinner triangle" as icon.

**Comment by moving-bits** [comment]
> Regarding the "spinner buttons":

created PR #11308 for it
