### ISSUE TITLE
Make type selectors consistent

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11271]
## What function are you missing
Currently the trackable log activity displays a button labelled with current log type. If you press this button, a popup appears, in which you can change the log type.

![image](https://user-images.githubusercontent.com/3754370/126222583-6ffcec4a-fdd0-43a7-9275-cc63128adefc.png)

This is different from what we use in waypoint edit or in cache log edit for type selection.

## Suggested solution
Make it consistent across type selections, at least between the two log type selections.

Either use a type spinner instead of the button. E. g. like we have in waypoint edit.

Or at least make it consistent with cache log type selector, which uses radio buttons.

|waypoint type|cache log type|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/126222886-26901b9b-ef6b-49f9-9012-e5cc51b1b887.png)|![image](https://user-images.githubusercontent.com/3754370/126222922-e78c23dc-d294-4044-97ac-75a3704a86d3.png)|

**Comment by fm-sys** [comment]
I would prefer to use/keep radio buttons. But that's just my personal taste...
