### ISSUE TITLE
Migration of global hide settings into live filter

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11273]
I briefly checked the changed live/offline filtering including the take-over of map quick settings into the filter.
@eddiemuc Really well done, works like a charm and is kind of logical now and reflects perfectly, what users are used to and might expect. Nice!

The only thing "missing" right now would be a migration of the former global settings into the live filter upon/after upgrading. I am not sure, whether this was contained in #11252 or not.

IMHO its not mandatory, but would help to avoid further support efforts to assist users (e.g. who did not yet use the map quick settings and now miss the global filter settings in c:geo settings).

@eddiemuc What are your thoughts about that?

**Comment by eddiemuc** [comment]
You're right, we did not talk about this and it seems to have slipped my mind (probably because it was not me but @fm-sys who removed the global type filter :-))

Will put it on the ToDo list

(@Lineflyer you put the "Google Play or Beta feedback" onto this, was there a complaint from beta users?)

**Comment by Lineflyer** [comment]
> (@Lineflyer you put the "Google Play or Beta feedback" onto this, was there a complaint from beta users?)

No, this was just to reflect, that it should be clarified during the beta phase.

As discussed earlier:
Migration from last release would be important. For beta users updating from previous beta, we said, we would just throw away existing filters to be able to migrate.

Note:
If this all gets to complex now (especially as the preferences are already removed from the code) the alternative would be, that I write a FAQ entry about how to reinstall the filters and we leave it like that. However a migration would be more convenient for the users...and not everyone reads the FAQ and/or wants to deal with filters. I assume many very basic users made this setting to hide found caches years ago and never touched it ever since.

**Comment by eddiemuc** [comment]
> If this all gets to complex now...

This will surely be less complex than it was to preserve the global "exclude" settings :-)

**Comment by MagpieFourtyTwo** [comment]
JFTR: After the global settings have been removed, switching to an explicit Live filter gave me a bit of a hard time.
Had to remove the current filter, enable all Quick Settings, and then build my "standard filter" from scratch, until it finally works.

I wouldn't want to inflict that on a normal user.

So, if someone upgrades from a version with Global Settings (GS) to a version w/o them - and if there is no really foolproof solution for migration from GS to filters, I would suggest to just clear all active filters, set all Quick Settings to TRUE, and let the user start from scratch with the filters (with an appropriate hint on how to do that, of course).

**Comment by eddiemuc** [comment]
> JFTR: After the global settings have been removed, switching to an explicit Live filter gave me a bit of a hard time.

Can you elaborate what exactly happened here for you? This might be a bug in the migration routine, because it is supposed to be rather straight-forward (it adds or modifies a status filter for live filter if it is not too complex)

**Comment by MagpieFourtyTwo** [comment]
Sorry, but I am afraid I cannot be of any help over here. I just fiddled around a bit, until it finally worked, nothing structured (cause I did not really get what happened and thought of a different problem). Moreover it's not really reproducible to me (although I have some older backups, I don't know exactly which update it was).

All I can say is: Immediately after the changing update the map did not show anything at all, simply changing the filter and quick settings did not change anything, but after resetting both and setting up the filter from scratch it suddenly worked - much to my surprise. ;)

In fact I cannot even say, if there was a filter active before upgrading ... all in all a not really debugging capable scenario. :/

**Comment by Lineflyer** [comment]
As discussed in #10922 this issue was kind of a misunderstanding:
- The migration of the global hiding settings into the live filter is already sone
- Not done is the migration of the previous global cache type filter into the live filter

For the latter my opinion is:
As the old filter was limited to one cache type only, I assume that almost no users uses this over a longer period of time. This means, that there is a minor probability that its active at the time of upgrading to the new version. And I also think most users would not expect a migration of such value.

I suggest to skip this migration completely.

@eddiemuc Just a ping, so you read this before diving into this topic codewise.

**Comment by eddiemuc** [comment]
Skipping this is also fine for.me :-)

**Comment by eddiemuc** [comment]
So shall we close here?

**Comment by Lineflyer** [comment]
Yes.
