### ISSUE TITLE
Add nested filters 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11275]
What about opening a sub-filter screen, to allow building of nested filters via UI?

![Screenshot_20210719_225138_copy_540x671](https://user-images.githubusercontent.com/64581222/126225866-101d7632-9bb5-41f2-aae9-409498349444.jpg)

The user then can just add a "sub-filter" filter and then can do everything with it. Load a saved configuration, create and adopt the sub-filter, etc, etc...

I guess this would be the cleanest and feature richest solution, where most code parts AFAIK even could be reused without much effort.

There are very legit use cases for it: e.g. I want to display only traditionals OR caches which are contained in a specific list but what to hide all found ones. A filter which is currently not possible to build.

We could give users with the "sub-filter" filter the same possibilities as with the actionbar icon in maps viewer. Short click -> open filter screen | Long click -> stored filter selection.

Feature should go to `master` 

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10581#issuecomment-882854827_ ff.

**Comment by moving-bits** [comment]
related to #10581
