### ISSUE TITLE
In github app the new forms are not supported

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11302]
when I create a new issue via the github app, I only see the option to create one without template or "contact support"
![Screenshot_20210722-221413_GitHub.jpg](https://user-images.githubusercontent.com/70113341/126704501-decf77d3-038b-407d-9eed-538a3be35a72.jpg)

**Comment by Lineflyer** [comment]
I guess the issue forms are not supported by the app yet due to their beta status.
Also on Octodroid the templates are gone now.

**Comment by murggel** [comment]
So I guess no chance to have the bug- and feature-template in the app back again...
