### ISSUE TITLE
Migration of hiding settings into filter does not work

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11300]
### Describe your problem!

As far as I understood from recent discussions, the migration of the old global cache hiding depending on status (found/owned, disabled, archived) into the live filter should already be implemented.

I tried to test it today, but failed.

### How to reproduce?

1. Install 2021.07.15 (current market release)
2. Complete wizard and login to gc.com
3. Go to Menu - Settings - Cache Details and make some custom hide settings, in my case:
   a) Exclude owned/found caches
   b) Exclude archived caches
4. Open live map to verify that these settings are used and also reflected in the map quick settings
5. Upgrade to 2021.07.22-NB
6. Start c:geo
7. Open live map

### Actual result after these steps?

- No active filter shown below action bar
- Found and archived caches shown on map
- Map quick settings show all status are active (=not hidden)

### Expected result after these steps?

On upgrade the previous settings should be taken over into an active live filter, so that users see on map/searches, what they are used to with the old release.

### Reproducible

Yes

### c:geo Version

2021.07.22-NB

### System information

```shell
Google Pixel 3a
Android S-Preview
```

**Comment by eddiemuc** [comment]
Hm that's very embarrassing. I will look into it. Can you send me your settings version number (from system info)?

**Comment by Lineflyer** [comment]
Before or after upgrade?

**Comment by Lineflyer** [comment]
2021.07.15: Settings v5, Count:102
2021.07.22-NB: Settings v6, Count:106

**Comment by eddiemuc** [comment]
Fixed with PR #11306

**Comment by eddiemuc** [comment]
This time it shall work...

**Comment by Lineflyer** [comment]
Please kindly do not manually close issues while the respective commit has not been merged to `master`.
I tend to test fixes with the nightly and therefore rely on the closed status to be sure its in our nightlies.

**Comment by Lineflyer** [comment]
Now it should be merged.

**Comment by eddiemuc** [comment]
> Please kindly do not manually close issues while the respective commit has not been merged to `master`.
> I tend to test fixes with the nightly and therefore rely on the closed status to be sure its in our nightlies.

Was not aware of this, sorry.

 I use the status to see that implementation is done. Maybe I can introduce a label for this purpose instead. Or is there any other good way to achieve this?

**Comment by murggel** [comment]
> > Please kindly do not manually close issues while the respective commit has not been merged to `master`.
> > I tend to test fixes with the nightly and therefore rely on the closed status to be sure its in our nightlies.
> 
> Was not aware of this, sorry.
> 
>  I use the status to see that implementation is done. Maybe I can introduce a label for this purpose instead. Or is there any other good way to achieve this?

You can add a new column to the project and move it manually there
