### ISSUE TITLE
wrong icon color in context menu, when coordinates are selected

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11303]
### Describe your problem!

The waypoint marker in context menu is nearly unvisible.

![Screenshot_20210722-222915_cgeo](https://user-images.githubusercontent.com/70113341/126705800-852a1990-1167-4c2d-999e-cc5da70ee7f7.jpg)

### How to reproduce?

Select coordinates in cache description -> context menu pops up

I am using dark theme

### Actual result after these steps?

See screenshot

### Expected result after these steps?

Lighter waypoint icon 

### Reproducible

Yes

### c:geo Version

2021.07.17-RC2

### Additional Information

Ok for light theme

**Comment by Lineflyer** [comment]
Isn't that a Google feature?

**Comment by fm-sys** [comment]
I think that might indeed be an android bug, so unfortunately nothing we can influence AFAIK. BTW, for me no icon is shown at all... 

![Screenshot_20210722_224829_cgeo geocaching](https://user-images.githubusercontent.com/64581222/126708255-7833bee7-9e7f-48ab-ad7c-ff564689a6e9.png)
![Screenshot_20210722_225119_cgeo geocaching](https://user-images.githubusercontent.com/64581222/126708258-d2cc5ef0-23c6-4473-a790-25b960cdff0f.png)
![Screenshot_20210722_225205_cgeo geocaching](https://user-images.githubusercontent.com/64581222/126708260-f49a63d2-eab9-49fd-a9e2-dd777535682c.png)

**Comment by murggel** [comment]
> Isn't that a Google feature?

Don't know, but probably yes.
I can check in other apps...

**Comment by murggel** [comment]
Let's close here
