### ISSUE TITLE
Outline of button is missing 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11312]
### Describe your problem!

The outline of log type button is missing. 

### How to reproduce?

Add a "log number" filter 

### Reproducible

Yes

### c:geo Version

Current nightly 

### Additional Information

![Screenshot_20210724_235535](https://user-images.githubusercontent.com/64581222/126881895-f0405e15-c119-4d9c-887a-eba33a9b84d5.jpg)

BTW, furthermore the button displays the unlocalized enum name instead of the localized string

**Comment by eddiemuc** [comment]
Recommend to start fix only after #11308 is merged

**Comment by eddiemuc** [comment]
Fixed with PR #11319
