### ISSUE TITLE
OneTimeMessage for long tap on map shows up after upgrade

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11317]
### Describe your problem!

Mainly a note to myself (as I did not pay close attention and need to retest):

While testing the fix for #11300 I started the map with 2021.07.15 and selected "Do not show again" for the one time message. However after upgrading to latest nightly and starting the map the message popped up again.
Not 100% sure though...feel free to check, else I will try that again tonight.

### How to reproduce?

1. Install 2021.07.15
2. Open map
3. Select "Do not show again" for the long tap on map message
4. Leave c:geo
5. Install newest nightly
6. Open map

### Actual result after these steps?

One time message shown again

### Expected result after these steps?

No OTM

### Reproducible

Unclear

### c:geo Version

2021.07.25-NB1

**Comment by moving-bits** [comment]
Not sure, but don't we have two OTM for long tap - one for long tap currently being activated, and one for currently being disabled?

**Comment by fm-sys** [comment]
BTW, do we still need them at all? Cause they where primarily made for informing users about a change which is now released for quite some months now. 

When testing the "fresh install experience" these dialogs feel rather annoying, so they should IMHO only be used temporary or in very special constellations.

**Comment by Lineflyer** [comment]
I tried to reproduce it but failed.
Maybe I was confused by the two types of messages as mentioned by @moving-bits 

Not sure regarding removal:
IMHO the normal user which uses c:geo will never again see it after once confirming it. For new users it will however provide some feature guidance. So it should not harm to keep it in.

**Comment by fm-sys** [comment]
> For new users it will however provide some feature guidance.

On the one hand I understand the idea of some feature information, OTOH especially the creation of UDC's and individual routes is a very special feature which is probably only used by a small group of advanced users, while there are way more important base function. Think about a user which never has seen c:geo before and directly gets confronted with such stuff. That would be quite daunting for me (especially as everything I want to know is not explained)
