### ISSUE TITLE
Filtering for attributes: exclude multiple attributes does not work

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11324]
### Describe your problem!

I want to filter caches, which are suitable for an easy found with kids.
So I want to exclude specific attributes: >10km, not suitable for kids,...

But still caches with those attributes were shown (not filtered out).

### How to reproduce?

Adding GC2586K and GC768Y3 to a list.
![image](https://user-images.githubusercontent.com/70113341/126912495-019968ee-0b0e-42f5-83d3-8ae786ec6a6e.png) ![image](https://user-images.githubusercontent.com/70113341/126912504-e937a389-892f-44e8-87ea-6d18063a9cc7.png)

Create advanced filter: Cache-Attribute exclude "Nicht mit Kinderwagen erreichbar" and ">10km"

![image](https://user-images.githubusercontent.com/70113341/126912191-b4b7216a-bc52-4252-ab16-de9072b089fc.png)

### Actual result after these steps?

Both caches are shown

### Expected result after these steps?

None of the caches should be shown

### Reproducible

Yes

### c:geo Version

2021.07.17-RC2

**Comment by murggel** [comment]
I already looked into it and it seems, that the logic for `exclude` is wrong:
simple inverse-logic is used, but the filter has multiple items which are connected via AND, that should for exclude turned into OR

**Comment by murggel** [comment]
Do we probably have some more of those "multi"-selection-filter

**Comment by eddiemuc** [comment]
"exclude" logic for attributes is programmed currently such that only caches are excluded containing **all** selected attributes (`NOT( A AND B)`), not **any** of them ( `(NOT A) OR (NOT B)`}

This can be changed of course, but shouldn't it then be changed for the `include` logic too?

**Comment by eddiemuc** [comment]
@murggel with current implementation you can achieve your filtering goal by adding the attribute filter multiple times, each time excluding a single attribute (resulting in
`NOT(A) AND NOT(B)`)

**Comment by murggel** [comment]
But then the naming (in german) is missunderstanding.

For me it looks like the filter shows caches without specific attributes. And the caches does not have all of these attributes.

But from your comment I understand, that "Exclude" / "Ohne" means, the filtered list does not contain caches with those attributes..

**Comment by eddiemuc** [comment]
Try to turn this around:
If you use "include" and select multiple attributes, would you expect that the filtered list contains caches which have only some (but not all) of the selected attributes? For example, if you select "recommended for kids" and "stealth required", would you expect that caches are in the filtered list with "stealth required" set but not "rec for kids"?

**Comment by murggel** [comment]
> Try to turn this around:
> If you use "include" and select multiple attributes, would you expect that the filtered list contains caches which have only some (but not all) of the selected attributes? For example, if you select "recommended for kids" and "stealth required", would you expect that caches are in the filtered list with "stealth required" set but not "rec for kids"?

No, for include I expect `A AND B`, but it's an `exclude`-option and not an `inverse`-option.
So I expect for exclude, that caches are shown, which does **not** have those attributes.
But the caches are shown. 
One reason is the return-value for filter, in my opinion this should not be `inverse != (found == attributes.size())` but 
`if inverse return 0 == found else return found == attributes.size()`

For the sql I probably have to think once more about the correct logic / result

**Comment by murggel** [comment]
> `NOT( A AND B)`), not **any** of them ( `(NOT A) OR (NOT B)`}
> 

Isn't that the same? NOT( A AND B) == NOT(A) OR NOT(B)

**Comment by murggel** [comment]
I think the missunderstanding is, what will be exlcuded - the cache with attribute or should the attribute be excluded (not contained) from the cache

**Comment by fm-sys** [comment]
This reminds me about issue  #11288. Both use cases (AND as well as OR) are totally valid, so maybe we should introduce a switch for it...?

**Comment by murggel** [comment]
Can we add then a info-button, what "exclude" means?

**Comment by eddiemuc** [comment]
> > containing all selected attributes `NOT( A AND B)`), not **any** of them ( `(NOT A) OR (NOT B)`}
> > 
> 
> Isn't that the same? NOT( A AND B) == NOT(A) OR NOT(B)
> 
> 

I was unprecise. The OR was wrong. I meant something like this:


`NOT( has-attribute-A AND has-attribute-B)`

vs.

`(NOT has-attribute-A) AND (NOT has-attribute-B)`

The former can currently be achieved via the "exclude" switch using one attribute filter and selecting multiple attributes in it.

The later can currently be achieved by putting multiple attribute filters in, each having "exclude" and one attribute set.

**Comment by eddiemuc** [comment]
> Can we add then a info-button, what "exclude" means?
> The other use case did not come to my mind 😊

Maybe I chose the wrong wording, but I meant "inverse filter" with the word "exclude" (it meant "exclude caches from result list which satisfies the following condition". Likewise, the "include" means "include (only) caches in result list which satisfies the following condition").

What would be a better wording?

**Comment by murggel** [comment]
Probably the wording on english is ok, but the german translation "include" -> "mit" and "exclude" -> "ohne" is misleading.

Have to think about better ones, which are not too long

**Comment by murggel** [comment]
Just brainstorming... work in progress, will be updated

Better german wording 
* (Caches) anzeigen / (Caches) ignorieren

using a different UI-element
* checkbox "Cache mit Attributen nicht anzeigen"
* switch "Cache ignorieren"

**Comment by murggel** [comment]
I think we can close here. I will get used to the wording :-)
