### ISSUE TITLE
Long-click on filter button should allow restoring the last filter

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11328]
### Tell us your idea!

The new filter GUI it requires 3 clicks to unset a filter: Filter -> Trashcan -> Check.
All 3 buttons are in slightly different places, so it's easy to miss-click there (e.g. hitting the cancel button).

Once a filter is set the most common action is to unset the filter (as opposed to changing it), thus this action should be quick to perform.

### What solution would you suggest?

Implement a long-click action on the filter button to:
- If a filter is set unset it
- If no filter is set restore the previous filter

### Is there an alternative?

At least for clearing the current filter there could be a second toolbar button.

**Comment by eddiemuc** [comment]
This request partly overlaps and partly collides with #11202

**Comment by murggel** [comment]
> This request partly overlaps and partly collides with #11202 

Correct.

In #11202 there will be the option to delete / clear the current filter in the popup-menu, so one more click necessary as with a separate button.

Restoring the previous could be archived to have that one already selected when opening the popup, which means one more click for selecting a different one...

**Comment by murggel** [comment]
Probably adding a button "Last filter" like "last selection" in list selection would be a possibility to restore the previous filter

**Comment by fm-sys** [comment]
> Restoring the previous could be archived to have that one already selected when opening the popup, which means one more click for selecting a different one...

I don't think this would make sense. @ztNFny do you really need such a restore feature, or is it primarily about clearing the filter so #11202 is sufficient for you? If so, I think we can close here...

**Comment by ztNFny** [comment]
> I don't think this would make sense. @ztNFny do you really need such a restore feature, or is it primarily about clearing the filter so #11202 is sufficient for you? If so, I think we can close here...

My main beef with the curren state is the number of clicks required to reset the filter.
I often (re)apply the filter, so an easy restore would be nice to have and with the long-click approach I initially suggested I thought that'd be a nice little feature to have in there. But it's not a must-have, so if you want to close it's ok.

**Comment by ztNFny** [comment]
closing this in favor of the more clearly described #12075
