### ISSUE TITLE
Global seach - do not? use earlier active filter

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11339]
### Tell us your idea!

I tested with the address search and stumbled over a discussion worth situation.

Previous active filter (e.g. a map filter) was additionally active in the address search.
I was surprised, because from user perspective I suppose to start on the global search with a fresh search (filter).

Do we really want this behavior?

**Comment by Lineflyer** [comment]
IMHO yes. That's what we discussed in our last meeting and came out with a "live filter" valid for map and other online functions (including searches).
For the default use case many users will surpress e.g. found caches on with the live filter and they probably want the same behavior in searches as well.
If the user has a special need he can still change the filter anytime.

**Comment by eddiemuc** [comment]
It was discussed to activate LIVE filter on online searches in our last developer call (as documented here: https://github.com/cgeo/cgeo/issues/10951#issuecomment-877854420)

But of course everything can be rediscussed.

**Comment by bekuno** [comment]
> 
> 
> It was discussed to activate LIVE filter on online searches in our last developer call (as documented here: [#10951 (comment)](https://github.com/cgeo/cgeo/issues/10951#issuecomment-877854420))
> 
> But of course everything can be rediscussed.

I had then misinterpreted the diagram.
Most of the discussions concerned the filters in lists and maps.
It is ok for me with the current behaviour.
Lets close.
