### ISSUE TITLE
Quick settings - reorder "Show Caches:" and use same wording in QS and Filter

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11343]
### Tell us your idea!

I suggest moving the entry for "Logged offline" to the 2nd position. (between "Found" and "Own") and "Disabled" last.
This allows for a more logical deactivation.

![grafik](https://user-images.githubusercontent.com/32555742/127220702-a6032ff0-85a9-428e-9d72-431042a48b40.png)

Additionally, use then the result of this discussion also for the filter.

The wording in the filter GUI is "Owned" and "Has Offline Log".
I propose to use the same wording in filter and QS.

**Comment by Lineflyer** [comment]
Nice idea and I almost agree.
I would however position "Disabled" in front of "Archived". 
So Disabled on 4 and Archived on 5.

**Comment by Lineflyer** [comment]
For the wording I would rather take the short wordings from map quick settings into the filter than vice versa.

**Comment by bekuno** [comment]
> I would however position "Disabled" in front of "Archived".
> So Disabled on 4 and Archived on 5.

I want to set Archived before Disabled because you can deactivate from top to down the caches which are not interesting to search. And the probability to look for an archived cache is below than for a deactivated one. This means I would hide the first four of five.

**Comment by moving-bits** [comment]
OTOH you could argue to put those on top of the list which you will be changing most frequently - archived would be last in this case, probably. (Right beside "logged offline" for me, but that's my personal use case of nearly never logging from a mobile device.)

So I would propose a sorting of:
- found
- logged offline
- own
- disabled
- archived

(as @Lineflyer suggested)

BTW: Why would someone like to filter for "logged offline" on the map (and not treat it the same as "found" for map purposes)? Differentiation makes sense in a cache list, but not in map, IMHO.

**Comment by Lineflyer** [comment]
> I want to set Archived before Disabled because you can deactivate from top to down the caches which are not interesting to search. 

Thats another way of seeing it, but I would still prefer "Archived" at the end as you can gets those caches not via the live map data anyway. So its a rather rare case where either some of your stored caches have been archived meanwhile or you explicitly import/download archived caches.
In any case there is not very often a need to toggle this switch.

So I would go with the ranking @moving-bits suggested. @bekuno Are you OK with that as well?

**Comment by Lineflyer** [comment]
> BTW: Why would someone like to filter for "logged offline" on the map (and not treat it the same as "found" for map purposes)? Differentiation makes sense in a cache list, but not in map, IMHO.

It makes much sense for me.
I don't want to see found caches on the map (those are done), but I still want to see my progress over the day while walking a cache route (and performing offline logs on the way).

**Comment by moving-bits** [comment]
> > BTW: Why would someone like to filter for "logged offline" on the map (and not treat it the same as "found" for map purposes)? Differentiation makes sense in a cache list, but not in map, IMHO.
> 
> It makes much sense for me.
> I don't want to see found caches on the map (those are done), but I still want to see my progress over the day while walking a cache route (and performing offline logs on the way).

Ah, I see. Same use-case, but different approach to it for me: I'm using a "found" list with a list marker attached to it, and move found caches into that list during a tour. (BTW: That's one of the reasons why the "delete empty list" had been so annoying for me.)

So anyway, keeping the "offline log" close to "found" (as proposed above) makes sense, as those two are sort of related.

**Comment by bekuno** [comment]
> So its a rather rare case where either some of your stored caches have been archived meanwhile or you explicitly import/download archived caches.
> In any case there is not very often a need to toggle this switch.
> 
> So I would go with the ranking @moving-bits suggested. @bekuno Are you OK with that as well?

@Lineflyer Your argument is also correct. 
Then lets go with the ranking list of @moving-bits .
