### ISSUE TITLE
Advanced Filter - "Favorites" with too much space

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11345]
### Tell us your idea!

In the "Favorites" filter entry there is much space before and after "Absolute/Percentage" buttons.
This could be reduced.

![Screenshot_20210727-222044_cgeo](https://user-images.githubusercontent.com/32555742/127222410-d8b6c5d1-c21d-476e-a835-6c603e9fe5a8.jpg)

**Comment by bekuno** [comment]
The same space problem is on "Logs Count"

**Comment by MagpieFourtyTwo** [comment]
While I would increase the max val for Logs count, too - if possible in one go. Cause 1000 is a little bit low ...

**Comment by bekuno** [comment]
> 
> 
> While I would increase the max val for Logs count, too - if possible in one go. Cause 1000 is a little bit low ...

@MagpieFourtyTwo 
I converted this to an own issue, as this problem in not related to the design problem here.

**Comment by MagpieFourtyTwo** [comment]
Ok - thx!

**Comment by eddiemuc** [comment]
![image](https://user-images.githubusercontent.com/6909759/128057770-c0e27981-4ecd-4307-af05-0529fe2bfabd.png)

**Comment by eddiemuc** [comment]
Fixed with PR #11404

**Comment by bekuno** [comment]
looks much better :-)
