### ISSUE TITLE
Search GUI optimization

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11354]
### Tell us your idea!

I stumbled at the search GUI over some naming/translation and GUI issues.

**1)** design
The individual sections are now hardly distinguishable.
The headline shown use a more visible style (bold?) and the line bolder than the box/button outline. 

**2)** Coordinates vs. Coordinate
The word "Coordinates" is in c:geo used on many places, not only in the search GUI.
The word Coordinates is the plural form of Coordinate. And mostly we mean a single coordinate (consisting of latitude and longitude). And we search in the search GUI by a single coordinate.
So lets use the single form here and check also other places.

**3)** Keywords vs. Keyword
The headline says "Keywords", the helper text and the button "Keyword".
The headline should use the single form (as the other headlines).
Can we really search for multiple keywords? (I did not tested it). If yes then use "Keyword(s)".

The German translation is also poor. 
Headline "Stichworte" (=plural), helper text and search button "Stichwörter" (=plural).
I propose to use "Stichwort" and if necessary "Stichworte".

**Comment by bekuno** [comment]
Current state of changes:
![Screenshot_20210731-012832_cgeo](https://user-images.githubusercontent.com/32555742/127721092-210f0ce2-305b-464f-b4a4-0eaff8bdc2bc.jpg)
- Filter as first entry
- Geocode as second entry
- Latitude/Longitude as a two row button
- Headline text bold, line in 3dip
- "Geocode" instead of "geo code"
- "Coordinate" instead of "Coordinates"
- "Keyword" instead of "Keywords"

**Comment by murggel** [comment]
For adding waypoints there is also "coordinates" used.
Should I create a new PR and a new issue for that?

**Comment by bekuno** [comment]
> 
> 
> For adding waypoints there is also "coordinates" used.
> Should I create a new PR and a new issue for that?

I created #11390 and #11391 for it.
The implementation for #11391 is nearly ready.
