### ISSUE TITLE
[New filter] Filter definition string in header: "change marker" is too unobtrusive

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#11356]
### Tell us your idea!

When there is a stored filter active, it's name is displayed in the header - which is perfectly fine (and BTW offers a wonderful workaround for the "'Status:3 items' is way too compact" issue #11293 ;) ).

But: 
- When modifying a currently active stored filter using the filter definition dialog, there will still be the stored name displayed, just extended by a tiny little "*", which can easily be overlooked.
- Although the star marker concept is a good idea, esp. when it comes to saving the modifications of a stored filter (cause the old name is suggested as default),  it's meaning is not really obvious to the user (took even me some time to realize).
- Moreover, the displayed name can massively be misleading, esp. when the differences are tiny. And if the filter has changed fundamentally, it would even be completely false.

### What solution would you suggest?

Thus I would suggest to ...

- EITHER entirely drop the name of the stored filter, once it has been changed,
   and display the current filter definition instead
   (if possible, the old name may nevertheless be displayed as default, when the user is going to save his changes)
- OR change the "*" to s/th more noticeable like ``(changed)`` or ``(modified)`` or a mnemonic abbreviation.
- OR ... another idea you possibly have to make unmistakably clear to the user
  that his stored filter is de facto no longer working in it's known way

**Comment by eddiemuc** [comment]
Teammeeting 11.2.24: team is undecided what would be the best way to visualize this. Discussed options:
* use an icon (e.g. warning sign)
* put asterik in parenthesis (e.g. " (*)")
* use colors or other font (e.g. italic)

@murggel will try out some things

**Comment by murggel** [comment]
I created different variants:
changed the name to italic-font and add a space between name and "*"
used icons (mockup) different icon can be used
changed icon for filter (mockup) different icon can be used

I will post each variant as separate comment for better voting

**Comment by murggel** [comment]
| View |Unchanged   | Normal without space (current version)   | 
| --- | --- | --- |
| Filter|![image](https://github.com/cgeo/cgeo/assets/70113341/6da1a384-f4d9-4fd0-8854-69b77ca0a035) |![image](https://github.com/cgeo/cgeo/assets/70113341/42213dc0-c110-4ed5-bfa3-bbcebff3fe85)|![image](https://github.com/cgeo/cgeo/assets/70113341/276d05bc-a9ff-4893-82dd-a407627db346)|
| Map|![image](https://github.com/cgeo/cgeo/assets/70113341/66d360b4-9c46-47fc-ad87-56c25c181eb7)|![image](https://github.com/cgeo/cgeo/assets/70113341/453ebcc7-1773-4bd3-91aa-f092df1e159f)|
| List|![image](https://github.com/cgeo/cgeo/assets/70113341/6808f459-1157-4297-aa9a-a67e6f13b393)|![image](https://github.com/cgeo/cgeo/assets/70113341/c4ca4889-2a63-4ed1-9007-67d4f8364a14)|

**Comment by murggel** [comment]
| View |Unchanged   |  Italic without space   |
| --- | --- | --- |
| Filter|![image](https://github.com/cgeo/cgeo/assets/70113341/6da1a384-f4d9-4fd0-8854-69b77ca0a035) |![image](https://github.com/cgeo/cgeo/assets/70113341/276d05bc-a9ff-4893-82dd-a407627db346) |
| Map|![image](https://github.com/cgeo/cgeo/assets/70113341/66d360b4-9c46-47fc-ad87-56c25c181eb7)|![image](https://github.com/cgeo/cgeo/assets/70113341/36764d5f-c528-4f34-add9-60f23d1ac899) |
| List|![image](https://github.com/cgeo/cgeo/assets/70113341/6808f459-1157-4297-aa9a-a67e6f13b393)|![image](https://github.com/cgeo/cgeo/assets/70113341/a31fe391-7522-41e9-abad-5e5b1953ed01)|

**Comment by murggel** [comment]
| View |Unchanged   | Italic with space   | 
| --- | --- | --- |
| Filter|![image](https://github.com/cgeo/cgeo/assets/70113341/6da1a384-f4d9-4fd0-8854-69b77ca0a035) |![image](https://github.com/cgeo/cgeo/assets/70113341/112b2571-985c-4985-890b-2b29691df833) |
| Map|![image](https://github.com/cgeo/cgeo/assets/70113341/66d360b4-9c46-47fc-ad87-56c25c181eb7)|![image](https://github.com/cgeo/cgeo/assets/70113341/b944ffb8-0f35-4aa4-a282-1685898d4a5e) |
| List|![image](https://github.com/cgeo/cgeo/assets/70113341/6808f459-1157-4297-aa9a-a67e6f13b393)|![image](https://github.com/cgeo/cgeo/assets/70113341/903e2f97-6331-4872-bad0-7b52948a4ef8)|

**Comment by murggel** [comment]
| View |Unchanged   | Icon (mockup e.g. Pencil)   | 
| --- | --- | --- | 
| Filter|![image](https://github.com/cgeo/cgeo/assets/70113341/6da1a384-f4d9-4fd0-8854-69b77ca0a035) |![image](https://github.com/cgeo/cgeo/assets/70113341/e874eacc-1686-47a2-9e69-f4802d18226c)|
| Map|![image](https://github.com/cgeo/cgeo/assets/70113341/66d360b4-9c46-47fc-ad87-56c25c181eb7)|![image](https://github.com/cgeo/cgeo/assets/70113341/78a52311-4584-4194-8f35-95cb03ab30a2)|
| List|![image](https://github.com/cgeo/cgeo/assets/70113341/6808f459-1157-4297-aa9a-a67e6f13b393)|![image](https://github.com/cgeo/cgeo/assets/70113341/33174167-f015-4fe0-b030-f582b4d89ddf)|

**Comment by moving-bits** [comment]
Thanks for creating those variations. I like the italic version. Maybe we can additionally put the name in brackets to emphasize that this once has been the filter named xxx, but not quite more:

_(Found)*_

**Comment by murggel** [comment]
| View |Unchanged   | Different filter-icon (mockup e.g. filter with pencil)  |
| --- | --- | --- | 
| Filter<br> <br>or here just only pencil|![image](https://github.com/cgeo/cgeo/assets/70113341/6da1a384-f4d9-4fd0-8854-69b77ca0a035) | ![image](https://github.com/cgeo/cgeo/assets/70113341/1f7d74d1-ce74-4b3b-8efb-7295edcc17a2)  |
| Map|![image](https://github.com/cgeo/cgeo/assets/70113341/66d360b4-9c46-47fc-ad87-56c25c181eb7)|![image](https://github.com/cgeo/cgeo/assets/70113341/bc02cf34-af16-4ea8-98dc-0e75a0ab9c49)|
| List|![image](https://github.com/cgeo/cgeo/assets/70113341/6808f459-1157-4297-aa9a-a67e6f13b393)| |

**Comment by murggel** [comment]
I would suggest to use the vote 👍 / 👎 buttons for the variants and add suggestion as separate comment

**Comment by murggel** [comment]
> Thanks for creating those variations. I like the italic version. Maybe we can additionally put the name in brackets to emphasize that this once has been the filter named xxx, but not quite more:
> 
> _(Found)*_

Good idea - I will create a new variant

**Comment by murggel** [comment]
Name in brackets and "*" as postfix

| View |Unchanged   |  Name in brackets and "*" as postfix| 
| --- | --- | --- | 
| Filter|![image](https://github.com/cgeo/cgeo/assets/70113341/6da1a384-f4d9-4fd0-8854-69b77ca0a035) |![image](https://github.com/cgeo/cgeo/assets/70113341/7a93531c-60cd-4e19-b487-9290c5156fc1)|
| Map / List|![image](https://github.com/cgeo/cgeo/assets/70113341/66d360b4-9c46-47fc-ad87-56c25c181eb7) |![image](https://github.com/cgeo/cgeo/assets/70113341/60209df2-96fc-47ee-badd-df63d554fe1f) |

**Comment by murggel** [comment]
Name in brackets and "*" as prefix

| View |Unchanged   | Name in brackets and "*" as prefix | 
| --- | --- | --- | 
| Filter|![image](https://github.com/cgeo/cgeo/assets/70113341/6da1a384-f4d9-4fd0-8854-69b77ca0a035) | ![image](https://github.com/cgeo/cgeo/assets/70113341/0c8980d9-80c8-40f7-98f6-97b7731ad41e)|
| Map / List|![image](https://github.com/cgeo/cgeo/assets/70113341/66d360b4-9c46-47fc-ad87-56c25c181eb7) |![image](https://github.com/cgeo/cgeo/assets/70113341/4e6a4f4b-bc26-4073-b300-b805f134253c) |

**Comment by moving-bits** [comment]
Thanks for voting. Looks like we have a clear result. As of now we have:
- _(filtername)*_ got 4 ups / 0 downs
- _filtername *_ got 1 up / 0 downs
- _*(filtername)_ got 1 up / 2 downs
- filtername* got 0 up / 1 down
- _filtername_ + pencil icon got 0 ups / 2 downs
- _filtername_ + new filter icon got 0 ups / 3 downs

**Comment by murggel** [comment]
fixed with PR #15383 15383
