### ISSUE TITLE
Premium not detected in first session

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11351]
### Describe your problem!

While testing several development builds and the current RC I noticed, that the detection as being a premium member does not seem to work immediately after first authorization / in first session.

Did not check whether its clearly reproducible, but I have seen this quite often (as I wanted to check ALC implementation and non was loaded).

### How to reproduce?

- Install c:geo
- Run wizard
- Authenticate to gc.com as PM from the wizard
- Complete the wizard

### Actual result after these steps?

- I cannot see any ALC caches on the map
- Looking into setting I see the connector settings are greyed out
- Did not check system information though

### Expected result after these steps?

PM status should immediately be detected/used

### Reproducible

Unclear

### c:geo Version

2021.07.28-RC

**Comment by ztNFny** [comment]
I've seen the same since about a week.

**Comment by eddiemuc** [comment]
PR #11405 should fix this
