### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by pictom1** [cgeo/cgeo#11363]
Updated Beta today. Went geocaching and played with filters, specifically difficulty and terrain. Also turned on advanced but I didn't see  anything to change there. Went to search and immediately got NO RESULTS. Kept changing filters to no avail. Hit the trashcan button to throw away any filters. No caches in the search. (I'm standing within 500 feet of a cache I just logged). Turned off app several times. Finally rebooted phone. App still will not show any caches. As of this moment I am unable to geocache.

**Comment by pictom1** [comment]
About a half hour later, same thing. Hit the trashcan on the filters a few times in a row, and then the geocaches popped up.

**Comment by SammysHP** [comment]
Thank you for your report. This issue is already fixed and will be included in the next version. Please see #11360 for more details and the second comment for a workaround.
