### ISSUE TITLE
D/T filter setting - make it easier to read

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11362]
> 
> 
> > Is there also a way to not double the D/T state in the system information -> Filter setting?
> 
> The info is not really doubled. The first difficulty represents the min value, the second one the max value. In current example, both min and max are "indefinite" which is represented by "-"
> 
> The representation could maybe be optimized. But I don't see a high priority here, this is just a technical view and not something the user will see (except in debug support situations).

Understandable.
Then let's put this beautification to prio low.

_Originally posted by @bekuno in https://github.com/cgeo/cgeo/issues/11361#issuecomment-889483120_

**Comment by murggel** [comment]
If this will be changed, I am not sure, if there will be "migration effort", so probably leave it as it is (and refactor later) or do it before final release.
So I created PR #11407

**Comment by fm-sys** [comment]
Changing the technical backend syntax doesn't make any sense IMHO. Even worse, it might make things even more complicated for parsing and might break stored filters for maybe up to 10k beta users. 

Instead, we should optimize the front-end:
- `*-*` -> show nothing 
- `*-x` -> `<x`
- `x-*` -> `>x`

**Comment by murggel** [comment]
Adapt also for logs-count and fav-count

**Comment by murggel** [comment]
I will clone this issue, in case the PR will get merged
