### ISSUE TITLE
Duplication of images in gallery

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11386]
### Describe your problem!

Report on beta channel feedback and reproducible for me.
The content of the gallery tab gets duplicated each time a cache is refreshed

Sounds similar to #11072

### How to reproduce?

- Open a cache with images (e.g. GC3VHF9)
- Swipe to gallery tab
- Pull down to refresh

### Actual result after these steps?

The content of the gallery is duplicated, i.e. when scrolling down the images the same images in same sequence are appended each time the cache is refreshed

After closing / opening the cache its back to normal

### Expected result after these steps?

No duplication

### Reproducible

Yes

### c:geo Version

2021.70.30-RC

**Comment by eddiemuc** [comment]
PR #11388
