### ISSUE TITLE
Use "original" hint-icon instead of the combined one

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11402]
### Tell us your idea!

While adding the svg to the rawimages-directory (#11403), I found the original "hint"-svg. I would use that one instead of the modified / self-created svg or should we stay with the current / new one?

### What solution would you suggest?

use old one
![grafik](https://user-images.githubusercontent.com/70113341/127925724-2f97ecc6-d006-43a1-a55e-e423d453a5d6.png)

### Is there an alternative?

leave it as it is now
![grafik](https://user-images.githubusercontent.com/70113341/127925769-27c03bfd-70c1-4857-9dd9-d48c6c62511a.png)

**Comment by eddiemuc** [comment]
Both versions are fine for me

**Comment by ztNFny** [comment]
My vote goes for the new one, the larger bulb is nice, with the old icon I actually never noticed it.

**Comment by Lineflyer** [comment]
Lets stay with the new one. :)
