### ISSUE TITLE
D/T Filter and other: optimize user-display-string

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11409]
We should optimize the front-end:
- `*-*` -> show nothing 
- `*-x` -> `<x`
- `x-*` -> `>x`
- `x-y` -> can stay like it is 

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11362#issuecomment-892225406_

**Comment by murggel** [comment]
Adapt also for logs-count and fav-count

_Originally posted by @murggel in https://github.com/cgeo/cgeo/issues/11362#issuecomment-892229432_

**Comment by fm-sys** [comment]
And while we are on it: The user displayable filter string should follow grammatical rules... Means a white space after ':' and ','.

![Screenshot_20210809_183625_cgeo geocaching](https://user-images.githubusercontent.com/64581222/128742305-97ee395b-bcee-4f74-b2ae-f6719577ee6a.png)
