### ISSUE TITLE
Filter issue with archived caches caused by status archived and deactivated at same time

### ISSUE THREAD

**Issue by DaTechniker** [cgeo/cgeo#11428]
### Describe your problem!

Some caches have status disabled and archived the same time. These caches are not shown when using the filter for archived only.
The screenshots show this problem.
I think it is based on using pocket queries. 
I
[logcat-2021-08-07-08-40-17-2.txt](https://github.com/cgeo/cgeo/files/6948718/logcat-2021-08-07-08-40-17-2.txt)
![Screenshot_20210807-083456_cgeo](https://user-images.githubusercontent.com/88573756/128591785-755bd197-6da4-4a12-b672-0f4d52a4672c.jpg)
![Screenshot_20210807-083507_cgeo](https://user-images.githubusercontent.com/88573756/128591786-debc4fd8-f6fa-4a36-9a4b-8dbcf2460feb.jpg)
![Screenshot_20210807-083521_cgeo](https://user-images.githubusercontent.com/88573756/128591788-707601d1-ff82-47c0-a4ef-fb9209d626d9.jpg)
![Screenshot_20210807-083606_cgeo](https://user-images.githubusercontent.com/88573756/128591790-f1514b4c-e7fe-4c78-88f8-151a9a3c8b3d.jpg)
![Screenshot_20210807-083631_cgeo](https://user-images.githubusercontent.com/88573756/128591791-b5894c09-205a-4961-9cc2-06a6100e3ac3.jpg)
![Screenshot_20210807-083702_cgeo](https://user-images.githubusercontent.com/88573756/128591792-81c8f3b0-a9f1-40dd-841f-f253748176fe.jpg)
[SystemInfo.txt](https://github.com/cgeo/cgeo/files/6948719/SystemInfo.txt)

### How to reproduce?

Using filter rules.
Looks like imported archived caches with PQ have double state.

### Actual result after these steps?

Not all caches with state archived are shown when using filter archived only

### Expected result after these steps?

all archived caches are shown

### Reproducible

Yes

### c:geo Version

2021.07.30-RC

### System information

```shell
## System information

c:geo version: 2021.07.30-RC

Device:
-------
- Device type: SM-A705FN (a70qeea, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.A705FNXXU5DUE2
- Screen resolution: 1080x2198px (411x837dp)
- Sailfish OS detected: false
- Google Play services: disabled - 21.26.21 (150400-387928701)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: orientation

Program settings:
-------
- Filters: 
    LIVE: Aktiv und Liste und Gespeichert und Typ eingeblendet* ([Aktiv und Liste und Gespeichert und Typ eingeblendet*:inconclusive=false:advanced=true]AND(type;stored_since:-:-;status:found_no:exclude_archived;stored_list))
    OFFLINE: Aktiv und Liste und Gespeichert und Typ eingeblendet* ([Aktiv und Liste und Gespeichert und Typ eingeblendet*:inconclusive=false:advanced=true]AND(type;stored_since:-:-;status;stored_list))
- Hide waypoints: visited
- Set language: de_AT (system default)
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: false
- OSM multi-threading: false / threads: 1
- Last backup: 2. Apr., 18:50
- Routing mode: Walk
- Settings: v8, Count:202
- Map: Aut+ (FZK) (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:0000-0000:OfflineMaps/Aut+ (FZK).map
  - Atts: (c) Map: FZK project (free for private use); Map data: OpenStreetMap contributors; Contour data: U.S. Geological Survey and J. de Ferranti
  - Theme: freizeitkarte-v5.zip:freizeitkarte-v5/freizeitkarte-v5.xml

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: dd.MM.yyyy
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (55,2 GB free) v2 internal isDir(12 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (55,2 GB free) v2 external non-removable isDir(7 entries)
- Geocache data: /storage/0000-0000/Android/data/cgeo.geocaching/files/GeocacheData (160,5 MB free) v2 external removable isDir(26419 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (55,2 GB free) v2 internal isDir(16 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=16, dirs:>=8, totalFileSize:>=589,9 MB, free space: 55,2 GB, files on device: 3645440)
  - OFFLINE_MAPS: SD-Karte/OfflineMaps (User-Defined)[SD-Karte/OfflineMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps/document/0000-0000%3AOfflineMaps, Av:true, files:16, dirs:1, totalFileSize:4,3 GB, free space: 160,5 MB, files on device: 0)
  - OFFLINE_MAP_THEMES: SD-Karte/OfflineThemes (User-Defined)[SD-Karte/OfflineThemes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes/document/0000-0000%3AOfflineThemes, Av:true, files:804, dirs:3, totalFileSize:4,8 MB, free space: 160,5 MB, files on device: 0)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:8, dirs:0, totalFileSize:3,7 MB, free space: 55,2 GB, files on device: 3645440)
  - GPX: SD-Karte/OfflineThemes (User-Defined)[SD-Karte/OfflineThemes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes/document/0000-0000%3AOfflineThemes, Av:true, files:804, dirs:3, totalFileSize:4,8 MB, free space: 160,5 MB, files on device: 0)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:2, dirs:1, totalFileSize:585,6 MB, free space: 55,2 GB, files on device: 3645440)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:274, dirs:0, totalFileSize:202,4 KB, free space: 55,2 GB, files on device: 3645440)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 55,2 GB, files on device: 3645440)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 55,2 GB, files on device: 3645440)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 55,2 GB, files on device: 3645440)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 55,2 GB, files on device: -1)
- Map render theme path: freizeitkarte-v5.zip:freizeitkarte-v5/freizeitkarte-v5.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
  - content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes (31. März, 13:28):RW
  - content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps (31. März, 13:27):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (31. März, 13:27):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v96, Size:819,2 MB) on user storage

--- End of system information ---
```

### Additional Information

Pictures and Logs are in the decription

For me it looks like there is some issue with the new filter rules.
For some reason IMHO archived caches imported via pocket query have both states.

**Comment by eddiemuc** [comment]
I remember a problem regarding Cache filtering for those having both states deactivated and archived at the same time. I thought I fixed this. But have to check in which release the fix is included (and whether it will fix also this case)

**Comment by fm-sys** [comment]
Similar to  #11292 which is already included in the beta. Solution should be it ignore the "disabled" flag completely, if "archived" is set. As a cache in fact is not disabled anymore if it is archived. 

Even further, we should change our implementation that disabled and archived at the same time is not possible at all anymore.

Instead of two booleans, we should use a single enum in `Geocache.java`, so `isArchived` and `isEnabled` will check the enum state.

For setting the state, we can merge `setDisabled` and `setArchived` into a unified method:

```
setState(ENABLED/DISABLED/ARCHIVED)
```

**Comment by fm-sys** [comment]
But these are two different issues:
- SQL bug
- In memory handling

**Comment by Lineflyer** [comment]
Removed milestone for now as its non-blocking beta or release. Can also be fixed for a later bugfix release.

**Comment by eddiemuc** [comment]
It is a fact that a cache in c:geo can currently be both disabled / archived currently. I am unsure whether we conclude that ithis is an errorness thing or not, but if it is I think it deserves its own issue. F

This issue deals with how to filter such situations. 

I looked again into this, and indeed the observed behaviour is explainable with the current filter logic for cache status "Available", "Disabled" and "Archived". In contrast to other status filters (such as e.g. "found", "Owned") those are TWO-stated only. The states are explained using the example of "Disabled":
* If "Disabled" is selected (the default) then this means: show both Disabled and Non-Disabled caches in result
* If "Disabled" is de-selected then this means: show only caches in result which are NOT Disabled. This is the equivalent if selecting "No" in e.g. the Three-State-filter for "Found".

A cache being both archived and disabled would this NOT be included in the result if "disabled" is deselected.

Now, how should this me modified to better suite the user's expectations? I see following options:
* Do nothing (and wait for a solution for the problem that caches can be both disabled and archived). Not a good idea imho
* Turn "Active"/"Disabled"/"Archived" to THREE-state-filters (like "Found"/"Own"/...). Would make the Status filter more unified but also larger (in terms of necessary "GUI space")
* Change filter logic behind the three states "Active"/"Disabled"/"Archived" and process them as a union: if all are selected then don't filter, otherwise filter them in an OR fashion (show caches being Active OR disabled OR archived). This also means that NO cache will survive of NONE of the three is selected (some users seem to wish for an easy way to leave a filter result list empty - this could be the way)

What would be the favorite here?

**Comment by DaTechniker** [comment]
I found out a little bit about the duplicate status:
For me it looks like a cache doing a manual refresh always only has the state archived.
When this is imported via PQ, I get the duplicated state.

When I have 3 states of different combinations, I get the following results with filterung

disabled -> Disabled On, Archived off -> Only this file can be seen
archived -> Disabled On, Archived on -> Can be seen
archived -> Disabled Off, Archived on -> can be seen
disabled/archived -> Disabled on, Archived off -> Can not be seen
disabled/archived -> Disabled off, Archived on -> Can not be seen
disabled/archived -> Disabled on, Archived on -> can be seen

I have a list containing disabled caches from a PQ containing only disabled caches. And I have a PQ containing only archived caches. When I import this, I get the duplicate state for disabled caches.

I was using the old filters before the redesign, I was simply able to filter for archived caches, which worked well.

Maybe an idea for a fix would be, searching for archived, independant if there is a duplicate state disabled/archived. I do not know, if this double state is a valid state for a GC Cache. On the homepage, I either see disabled or archived.

**Comment by fm-sys** [comment]
Just had the same issue (I'm not able to filter for this cache):

![Screenshot_20211125_081628_cgeo geocaching](https://user-images.githubusercontent.com/64581222/143397777-502cfb30-f9a6-4dab-9742-1aed1678dbe3.png)

```
OFFLINE: Status:Aktive ausschließen,Deaktivierte ausschließen ([:inconclusive=false:advanced=true]AND(status:exclude_active:exclude_disabled))

**Comment by fm-sys** [comment]
What about refactoring our DB, so that disabled and archived are stored in the same column (0 active, 1 disabled, 2 archived)?

That would avoid having both statuses at the same time and would solve this issue implicitly...
