### ISSUE TITLE
[vectorIcons] Waypoints should use marker defined for connector

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11424]
### Tell us your idea!

Waypoints always use the round pin marker icon that's used for GC caches, no matter which connector the cache belongs to. They should use the same marker as the main cache instead of easier differentiation.

### What solution would you suggest?

In https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/utils/MapMarkerUtils.java createWaypointMarker() implement the differentiation between the different connectors.

(Visited / Archived state will be handled by an overlay in vector icons)

**Comment by moving-bits** [comment]
This is not a must-have, IMHO, but would be a nice addition for users using both gc.com and oc.* connectors.

**Comment by moving-bits** [comment]
@ztNFny 
As discussed in yesterday's meeting: I've created a little helper method for waypoints to retrieve the map marker id for their associated cache connector, see #11443.

**Comment by ztNFny** [comment]
implemented

**Comment by ztNFny** [comment]
@moving-bits the helper method provides the wrong value when guiding to a specific waypoint from the waypoints list. When drawing all waypoints it's ok though.
