### ISSUE TITLE
Filtering found / offline log problem

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11438]
I did a test with the filter settings in the field today and found another thing, that is quite interesting.

I can filter for found and I can filter for offline logged.

Today I was quite confused, when I wanted to filter showing found (yellow icon) and hide offline logged (orange icon).
This filter setting led to the behavior, that online found logged (yellow icon) are also filtered.

I would have expected the orange icons disappear, and the yellow ones shown.

Use case war being on tour with other cachers, and searching for the notes to an already found cache.
So for me when a cache is online logged as found (yellow icon) it should not be handled like an offline found (orange icon) log.

_Originally posted by @DaTechniker in https://github.com/cgeo/cgeo/issues/11435#issuecomment-894835815_

**Comment by Lineflyer** [comment]
Can you post the related filter information (screenshot or system information with the filter setup you made)?

**Comment by DaTechniker** [comment]
In the screenhots you can see the settings and the results in the upper part. 
The Found logs werde also offline logs in c:geo on this device, before logged online

![Screenshot_20210808-213103_cgeo](https://user-images.githubusercontent.com/88573756/128643635-b3b454c6-6752-4a1d-bef3-a31667a39790.jpg)
![Screenshot_20210808-213039_cgeo](https://user-images.githubusercontent.com/88573756/128643636-b8b9a17a-324b-4c77-af17-762d44b70d57.jpg)
![Screenshot_20210808-213051_cgeo](https://user-images.githubusercontent.com/88573756/128643637-442066d3-0587-42e2-9abc-20ea630edd1a.jpg)

**Comment by Lineflyer** [comment]
Just used 2022.12.28-NB trying to reproduce this older issue. I had no problems to filter offline logged while still seeing found caches. So this seemed to have another cause or fixed implicitly meanwhile.
Feel free to reopen if there is a reproducible way.
