### ISSUE TITLE
Offline-Log-filter does not work for "Schneller Offline log"

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11435]
### Describe your problem!

While working on #11430 I tried also the OfflineLog-Filter. And it did not worked for me.
The caches with "Schneller Offline log" were not shown, when I use the filter-option "Is present"

![image](https://user-images.githubusercontent.com/70113341/128615400-1d79b60c-fd69-4c79-83c0-4b224f1a657c.png)

Or is that the expected behaviour - means "description is (not) present" and not "offline log is (not) present"?

### How to reproduce?

Store a cache in a list
Create an offline log with empty description for that cache.
Create Offline-log-filter with "Is present"-option.
Select that filter for the list.

### Actual result after these steps?

Cache is not shown in the filtered list

### Expected result after these steps?

Cache should be shown in the filtered list

### Reproducible

Yes

### c:geo Version

2021.07.30-RC and Nightly

### System information

```shell
## System information

c:geo version: 2021.08.08-3c37a42 developer build

Device:
-------
- Device type: sdk_gphone_x86_arm (sdk_gphone_x86_arm, google)
- Available processors: 4
- Android version: 11
- Android build: sdk_gphone_x86_arm-userdebug 11 RSR1.201013.001 6903271 dev-keys
- Screen resolution: 1080x2088px (392x735dp)
- Sailfish OS detected: false
- Google Play services: enabled - 20.18.17 (040700-311416286)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:118
- Set language: en
- System date format: M/d/yy
- Time zone: GMT
- Debug mode active: no
- Last backup: never
- Routing mode: Bike
- Live map mode: false
- OSM multi-threading: false / threads: 1
- Map: OpenStreetMap.org
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OsmMapSource
  - Atts: © OpenStreetMap DE, map data OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: asf ([asf:inconclusive=false:advanced=true]AND(type:WEBCAM;difficulty_terrain:d=-:d=-:t=-:t=-;status))
- OFFLINE: None ([:inconclusive=false:advanced=false])

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
- Geocaching.com date format: dd.MM.yyyy
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (4.8 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (4.8 GB free) v2 internal isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (4.8 GB free) v2 external non-removable isDir(8 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (4.8 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=3, dirs:>=8, totalFileSize:>=1.7 KB, free space: 4.8 GB, files on device: 393216)
  - OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:0, dirs:1, totalFileSize:0 B, free space: 4.8 GB, files on device: 393216)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.8 GB, files on device: 393216)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.8 GB, files on device: 393216)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:3, dirs:0, totalFileSize:1.7 KB, free space: 4.8 GB, files on device: 393216)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.8 GB, files on device: 393216)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.8 GB, files on device: 393216)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:1, dirs:3, totalFileSize:0 B, free space: 4.8 GB, files on device: 393216)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81.2 KB, free space: 4.8 GB, files on device: 393216)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.8 GB, files on device: 393216)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.8 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (Jun 15, 9:41 PM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v96, Size:292.0 KB) on system internal storage

--- End of system information ---
```

### Additional Information

I guess, it's because the log does not contain any description (empty text). Will this be treated as "not present"? 

And for my use-case I should use only "has offline log" in the status filter?

Or is that the expected behaviour - means "description is (not) present"?
But then - with the changes of #11430 - there is no possibility to filter for empty e.g. "didn't find", correct?

**Comment by murggel** [comment]
@eddiemuc can you have a look at my concern regarding searching for offline logs with empty description...
Could that be a problem with the merged PR now?

**Comment by eddiemuc** [comment]
> @eddiemuc can you have a short look at my concern regarding searching for offline logs with empty description...
> Could that be a problem with the merged PR now?

This has nothing to do with your PR.

Currently "is present" option will only find caches with non-empty offline logs ("is present" is referring to a log text being present, not an offline log being present.) This was and is the purpose of this filter.

Searching for "has offline log" (empty or non-empty, regardless of log type) was doable via status filter and can't be done any more now. But that was discussed in the issue and seemingly wanted/accepted by the community. Wasn't it?

**Comment by eddiemuc** [comment]
Maybe people want to have two status filters for this? One "has offline log" (regardless of type) and one "has found offline log"?

Or a brand-new revised "offline log" filter is wanted (instead of the filter existing one simply filtering the log texts)? Then such a filter and it's wanted capacities should be specified. Maybe in addition to log text and log type users also want to filter for e.g. log date, has images, is favorited, given rating or what not. Many things are possible here.

**Comment by murggel** [comment]
> Searching for "has offline log" (empty or non-empty log text, regardless of log type) was doable via status filter and can't be done any more now. But that was discussed in the issue and seemingly wanted/accepted by the community. Wasn't it?

I am not sure, if this side-effect was clear to everyone, at least for me it only come to my mind while implementing / testing the PR...

**Comment by murggel** [comment]
> Maybe people want to have two status filters for this? One "has offline log" (regardless of type) and one "has found offline log"?
> 
> Or a brand-new revised "offline log" filter is wanted (instead of the filter existing one simply filtering the log texts)? Then such a filter and it's wanted capacities should be specified. Maybe in addition to log text and log type users also want to filter for e.g. log date, has images, is favorited, given rating or what not. Many things are possible here.

I like the idea of an additional filter 😉

**Comment by murggel** [comment]
> > @eddiemuc can you have a short look at my concern regarding searching for offline logs with empty description...
> > Could that be a problem with the merged PR now?
> 
> This has nothing to do with your PR.
> ...
> Searching for "has offline log" (empty or non-empty log text, regardless of log type) was doable via status filter and can't be done any more now. But that was discussed in the issue and seemingly wanted/accepted by the community. Wasn't it?


I don't have now a chance to see all of my offline logs (because normally they are empty and I fill them at home) 
-> that is related to the PR

**Comment by Lineflyer** [comment]
I am also typically using the "quick offline log" and create founds without text. I usually just use the history list to find them, but I would also expect, that if there is a filter "has offline log" it will filter those for me.

**Comment by eddiemuc** [comment]
> I am also typically using the "quick offline log" and create founds without text. I usually just use the history list to find them, but I would also expect, that if there is a filter "has offline log" it will filter those for me.
> 

I agree that the "feature change process" of c:geo is kind of unstructured currently. For some reason the specific feature change from "filter all offline logs" to "filter only found logs" seemed to be quite "urgent" and was decided very quickly yesterday. We might decide to have a changed process here, maybe introduce a mandatory "feedback time" before diving into implementation. Maybe something for discussion in today's meeting?

**Comment by Lineflyer** [comment]
>  "filter only found logs" seemed to be quite "urgent" and was decided very quickly yesterday. 

I am perfectly fine with that....simply caused by the fact, that the map quick settings icon for that filter is a smiley and I would also somehow expect that.

But - didn't I understand correct - that now found offline logs without text are no longer filtered properly...or did I misunderstand that.

**Comment by murggel** [comment]
> > I am also typically using the "quick offline log" and create founds without text. I usually just use the history list to find them, but I would also expect, that if there is a filter "has offline log" it will filter those for me.
> 
> I agree that the "feature change process" of c:geo is kind of unstructured currently. For some reason the specific feature change from "filter all offline logs" to "filter only found logs" seemed to be quite "urgent" and was decided very quickly yesterday. 

I agree. That's why I added the comment to the PR, but probably not clear enough....

**Comment by murggel** [comment]
> > "filter only found logs" seemed to be quite "urgent" and was decided very quickly yesterday.
> 
> I am perfectly fine with that....simply caused by the fact, that the map quick settings icon for that filter is a smiley and I would also somehow expect that.
> 
> But - didn't I understand correct - that now found offline logs without text are no longer filtered properly...or did I misunderstand that.

No, found offline logs with empty text were filtered correctly, but only found offline with empty text, e.g. not found with empty text were nit filterable

**Comment by Lineflyer** [comment]
Maybe we can discuss this briefly tonight and summarize the status before/now. This might help me understand and we try to find the most probable user wanted behavior.

**Comment by murggel** [comment]
> > "filter only found logs" seemed to be quite "urgent" and was decided very quickly yesterday.
> 
> I am perfectly fine with that....simply caused by the fact, that the map quick settings icon for that filter is a smiley and I would also somehow expect that.
> 

I think the problem of the quick decisions are, that sideeffects are probably not good enough considered...

**Comment by murggel** [comment]
> Maybe we can discuss this briefly tonight and summarize the status before/now. This might help me understand and we try to find the most probable user wanted behavior.

I hope I can make it till 20.30/21.00 ...

**Comment by fm-sys** [comment]
> found offline logs with empty text were filtered correctly, but only found offline with empty text, e.g. not found with empty text were nit filterable

Note that this is about the special offline log filter, not the status filter. IMHO the "is present" should also work for empty offline logs. Although that's technically different from other text filters, at least that's what users would expect. 

![Screenshot_20210808_140108_cgeo geocaching](https://user-images.githubusercontent.com/64581222/128631277-a8d4ce1a-1ed4-4c08-aae0-a271f8b59735.png)


> If not, my suggestion would be to revert the PR and change the icon back to the note one

Please not! Counting all comments together, there where +4 votes supporting that change, but not a single clear vote against it.

Furthermore, I wouldn't consider this a regression that offline DNF's can't be filtered. Note, that filtering for online DNF's is not possible as well, so this change was totally consistent.

**Comment by murggel** [comment]
> Furthermore, I wouldn't consider this a regression that offline DNF's can't be filtered. 

I would consider that as a regression, because with old version that was possible. And I use it to write the logs at home.

**Comment by fm-sys** [comment]
> > Furthermore, I wouldn't consider this a regression that offline DNF's can't be filtered.
> 
> I would consider that as a regression, because with old version filtering for all offline logs was possible. I use it to write the logs at home. And with the PR I could not filter for those anymore, if they have a empty log-description

Ok, didn't dived that deep into the old filter system. However, I'm strongly convinced that this use case has nothing to do with the status filter, but deserves a separate filter/adaption of the offline log filter. 

The quick settings is only made for hiding caches which aren't of interest anymore:
- disabled/archived -> not possible to find
- found/own -> done / not necessary to search 
- found offline -> done as well

(same applies for waypoint filtering)

"Has offline log" is a totally different story. With DNF/Note log the cache is in fact not done, so this filter does not fit into the quicksettings.

I will with pleasure help to adapt the "Offline log" filter. Unfortunately I will not be able to join this evening, but please consider all my arguments written here and in https://github.com/cgeo/cgeo/issues/11430

**Comment by DaTechniker** [comment]
I did a test with the filter settings in the field today and found another thing, that is quite interesting.

I can filter for found and I can filter for offline logged.

Today I was quite confused, when I wanted to filter showing found (yellow icon) and hide offline logged (orange icon).
This filter setting led to the behavior, that online found logged (yellow icon) are also filtered.

I would have expected the orange icons disappear, and the yellow ones shown.

Use case war being on tour with other cachers, and searching for the notes to an already found cache.
So for me when a cache is online logged as found (yellow icon) it should not be handled like an offline found (orange icon) log.

**Comment by Lineflyer** [comment]
> Today I was quite confused, when I wanted to filter showing found (yellow icon) and hide offline logged (orange icon).
> This filter setting led to the behavior, that online found logged (yellow icon) are also filtered.

Let me take this to a dedicated issue (trying to keep the threads on topic).

**Comment by DaTechniker** [comment]
> > Today I was quite confused, when I wanted to filter showing found (yellow icon) and hide offline logged (orange icon).
> > This filter setting led to the behavior, that online found logged (yellow icon) are also filtered.
> 
> Let me take this to a dedicated issue (trying to keep the threads on topic).

Sorry, thought this would be part of this threat.
It is OK for me, if this is handled in an own issue.

**Comment by fm-sys** [comment]
AFAIK it was decided to keep the current behavior, am I right? In this case we should close here...

**Comment by murggel** [comment]
Do we have a follow up issue for  adapting the "Offline log" filter with "offline log is present" (current implementation for "is present" considers only the description, I can't filter for caches with empty offline logs)

**Comment by fm-sys** [comment]
> I can't filter for caches with empty offline logs)? Or this should be considered in #11430?

With  #11430 we will have two status filters, "offline log" and "found offline". So the situation will be as currently, except that the quick settings will trigger the new "found offline" filter...

BTW, this would even allow filter constellations like "has offline log" but "log text is not present". So users can filter for all logs without log text, which might be a cool addition for someone...

**Comment by eddiemuc** [comment]
> Do we have a follow up issue for  adapting the "Offline log" filter with "offline log is present" (current implementation for "is present" considers only the description, I can't filter for caches with empty offline logs)?
> 
> Or this should be considered in #11430?

I created #11518 for this
