### ISSUE TITLE
Bug: empty warning message "overwrite old"

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#11437]
I made a backup and got the following warning message. If I do it now again, there is a proper message."This will erase your oldest backup from ..."
![Screenshot_2021-08-08-19-10-00-113_cgeo geocaching](https://user-images.githubusercontent.com/43813636/128640080-82054d71-b3b3-4a40-880a-dbdb03e865ca.jpg)

## System information

c:geo version: 2021.08.08-NB1-636aab6

Device:
-------
- Device type: MI 8 (dipper, Xiaomi)
- Available processors: 8
- Android version: 10
- Android build: QKQ1.190828.002 test-keys
- Screen resolution: 1080x2029px (392x737dp)
- Sailfish OS detected: false
- Google Play services: disabled - 21.26.21 (120400-387928701)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:166
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: 8. Aug., 19:10
- Routing mode: Walk
- Live map mode: false
- OSM multi-threading: true / threads: 4
- Map: Kombiniert (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
  - Atts: austria.map: / mapsforge-map-writer-master-SNAPSHOT /  / baden-wuerttemberg.map: / Map data (c) OpenStreetMap contributors /  / bulgaria.map: / mapsforge-map-writer-master-SNAPSHOT /  / france.map: / mapsforge-map-writer-0.6.0-rc3 /  / germany.map: / Map data (c) OpenStreetMap contributors /  / great_britain.map: / mapsforge-map-writer-0.3.1-SNAPSHOT /  / greece_v5.map: / mapsforge-map-writer-0.10.0 /  / india.map: / mapsforge-map-writer-0.5.1-rc4 /  / ireland.map: / mapsforge-map-writer-0.3.1-SNAPSHOT /  / norway.map: / mapsforge-map-writer-0.10.0 /  / romania.map: / mapsforge-map-writer-master-SNAPSHOT /  / slovenia.map: / mapsforge-map-writer-0.6.0-rc3 /  / switzerland.map: / Map data (c) OpenStreetMap contributors /  / world.map: / mapsforge-map-writer-0.5.0-rc4
  - Theme: none

Filters:
-------
- Hide waypoints: visited
- LIVE: Status:Gefunden=Nein,Eigener=Nein ([:inconclusive=false:advanced=false]AND(type;difficulty:-:-;terrain:-:-;status:owned_no:found_no))
- OFFLINE: Keine ([:inconclusive=false:advanced=false]AND(type;difficulty:-:-;terrain:-:-;status))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd.MM.yy
- Routing: external / BRouter installed: true
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (84,2 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (84,2 GB free) v2 external non-removable isDir(9 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (84,2 GB free) v2 external non-removable isDir(536 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (84,2 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=7, dirs:>=10, totalFileSize:>=81,2 KB, free space: 84,2 GB, files on device: 7413760)
  - OFFLINE_MAPS: [Legacy]/storage/emulated/0/Locus/mapsVector (User-Defined)[/storage/emulated/0/Locus/mapsVector[FILE#0:p-file:///storage/emulated/0/Locus/mapsVector::]] (Uri: file:///storage/emulated/0/Locus/mapsVector, Av:true, files:14, dirs:1, totalFileSize:7,1 GB, free space: 84,2 GB, files on device: -1)
  - OFFLINE_MAP_THEMES: [Legacy]/storage/emulated/0/Locus/mapsVector/_themes (Default)[/storage/emulated/0/Locus/mapsVector/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-file:///storage/emulated/0/Locus/mapsVector::/_themes]] (Uri: file:///storage/emulated/0/Locus/mapsVector/_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 84,2 GB, files on device: -1)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:5, dirs:0, totalFileSize:522,5 KB, free space: 84,2 GB, files on device: 7413760)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:56, dirs:0, totalFileSize:16,6 MB, free space: 84,2 GB, files on device: 7413760)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=10, dirs:>=10, totalFileSize:>=126,4 MB, free space: 84,2 GB, files on device: 7413760)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 84,2 GB, files on device: 7413760)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 84,2 GB, files on device: 7413760)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 84,2 GB, files on device: 7413760)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 84,2 GB, files on device: 7413760)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 84,2 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (30. Jan., 13:54):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v96, Size:26,4 MB) on system internal storage

--- End of system information ---

**Comment by moving-bits** [comment]
same cause as #10904?

**Comment by geocachermgo** [comment]
yes, thanks for the hint
