### ISSUE TITLE
Optimize rendering of system information in our issue forms

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11441]
Initially I defined `render: shell` for the text field used to paste the system information into our Github issue forms.
I suggest to user `render: Text` instead, which seems to be the closed to the `code style formatting` we had before.

I will provide a PR.

**Comment by fm-sys** [comment]
Actually, I really like the shell rendering for sys info...

**Comment by Lineflyer** [comment]
The downside of that shell view is that each `#1` is interpreted as issue link :(

**Comment by fm-sys** [comment]
> The downside of that shell view is that each `#1` is interpreted as issue link :(

Really? Never have seen that. When the template is used, it always look fine... E.g. https://github.com/cgeo/cgeo/issues/11435

Only if users open a blank issue, this is the case. E.g. https://github.com/cgeo/cgeo/issues/11437

So changing the renderer for the template will not help. We should rather avoid using this "github issue notation" in our sys info.

**Comment by fm-sys** [comment]
But wait, I just read the initial comment again: There is an extra renderer "text" which is different than markdown / shell renderer?

If this is the case, you are totally right and we can change it for sure... (maybe provide a picture in the PR description how it will look like) 👍

**Comment by Lineflyer** [comment]
it looks like the ` ``` ` encapsulated formatting

**Comment by fm-sys** [comment]
> it looks like the `` ``` `` encapsulated formatting

Yes, this would IMHO be preferable.

Just for reference: the shell render can be used manually in github via ` ```shell` as starting identifier.
