### ISSUE TITLE
c:geo not offered as target app depending on URL capitalization

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11453]
### Describe your problem!

Reported by a user on support mail:

The user coincidentally found, that depending how a coord.info link is formatted c:geo is offered or not offered as target app.

I could reproduce this issue (by sending such link to myself via Signal):
https://coord.info/GC9DBN6  -> offers c:geo
https://coord.info/gc9dbn6  -> offers c:geo
https://coord.info/Gc9dbn6 -> does not offer c:geo

### How to reproduce?

- Send such links with different capitalization to yourself by mail or messenger
- Click the link and check the offered apps

### Actual result after these steps?

The third link does not offer c:geo as target app

### Expected result after these steps?

c:geo should be offered as target app

### Reproducible

Yes

### c:geo Version

2021.08.08-RC

**Comment by bekuno** [comment]
Thats correct.

In the AndroidManifest we have
![grafik](https://user-images.githubusercontent.com/32555742/128903751-3170c11e-c990-4c05-911a-c844972b3a2d.png)

**Comment by fm-sys** [comment]
Probably _very_ low priority, but easy to fix. Just the manifest needs to be adopted. Maybe something for @Lineflyer? :)
