### ISSUE TITLE
Add "Other" cache type as Mystery at opencaching.*

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#11450]
### Tell us your idea!

Seems like there is a type "unusual" on OC.pl which is not mapped to any. Probably mystery would be fine here.
Example of the cache - https://opencaching.pl/viewcache.php?wp=OP8LT5#

**Comment by bekuno** [comment]
On the website it is define as "Cache type: Other type".

I will have a look at it.

**Comment by bekuno** [comment]
The official cache types are listed at https://wiki.opencaching.eu/index.php?title=Cache_types .
Currently we do not support explicitly the cache type ID1. (see `OkapiClient.getCacheType()`)

**Comment by eddiemuc** [comment]
c:geo has a cache type "`Unknown`". The OC connector currently maps the above OC cache type to this cache type.

Here is the relevant code part from `OkapiClient.java`

![image](https://user-images.githubusercontent.com/6909759/128866865-78e953a9-050d-4497-8782-ab6c206ef976.png)

(Why) is this the wrong behaviour?

**Comment by bekuno** [comment]
> (Why) is this the wrong behaviour?

The correct cache type is "Other" . See the okapi documentation at https://www.opencaching.de/okapi/services/caches/geocache.html

It says: "**Other**, also dubbed "unknown type"; allows OC users to create special caches which don't fit into the scheme of well-known types"

We can (a) directly add this cache type, (b) map to a more known type (Mystery?) or (c) stay as is.

**a** pro: dedicated icon and name
         con: additional work
**b** pro: dedicated and known icon
         con: may be confusing with other mystery mapped types (see above)
**c** pro: no work
         con: it looks like c:geo does not know this type

So I also propose to use (b).

**Comment by okainov** [comment]
>there is even a "dedicated" icon.

Actually this icon was exactly the reason I opened this. Because it's the same icon as some "error"-caches which were not fully loaded or buggy or premium for non-premium users on gc.com or whatever. So I was really surprised when I saw "good" cache with such icon.

**Comment by Lineflyer** [comment]
> Actually this icon was exactly the reason I opened this. Because it's the same icon as some "error"-caches which were not fully loaded or buggy or premium for non-premium users on gc.com or whatever. So I was really surprised when I saw "good" cache with such icon.

This double usage with incomplete caches is no longer existing, thus it should be fine as this is the correct and exclusive "Other" type for OC.
