### ISSUE TITLE
checking if text from "short description" is contained at the beginning of the regular description field, and not displaying short description in that case

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11464]
This seems to be triggered by a method checking if text from "short description" is contained at the beginning of the regular description field, and disabling the description field in that case. (See `CacheDetailActivity.potentiallyHideShortDescription()`)

The code for this is pretty old, but the error seems to be triggered by a change from 2016, when the separate "short description" field was merged into the regular description field, and thus the code above not disabling the "short description" but the whole description :-(

But this seems to be a real edge case, since nobody seems to have stumbled upon this in more than five years...

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/11455#issuecomment-897021969_

**Comment by bekuno** [comment]
After disabling the check with PR #11463 this is the follow up issue to repair the function.

Test-Caches see #11455; no known GC Cache so far.
Test methods currently do not exist.

**Comment by fm-sys** [comment]
OC109A7 is a nice test case - currently the beginning of the description is duplicated:

![Screenshot_20210823_095511](https://user-images.githubusercontent.com/64581222/130411487-de607abc-079c-4d43-ac19-210c5413aeb3.jpg)

**Comment by moving-bits** [comment]
I've changed the issue's title a bit, as it's not about disabling the description field (that was the error fixed with #11463) but about removing the short description in that case.
