### ISSUE TITLE
Slow when opening cache details

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11476]
Hands on the new version. And yes, looks great :) and I'm already waiting on the further redesign :D
But one thing that doesn't look so nice, imo: even in a small list (55 Caches), without filtering (read that issue) it takes some time until the details are opened and it is visibly switching from waypoints to overview, which is somewhat odd to look at.

_Originally posted by @Narrat in https://github.com/cgeo/cgeo/issues/10922#issuecomment-899120377_

**Comment by MagpieFourtyTwo** [comment]
Duplicate / same as  #11461?

**Comment by Narrat** [comment]
It may be. But you were reporting a specific case (really slow with mapped Caches), whereas I noticed slow behaviour in list view. Or in general.

**Comment by Lineflyer** [comment]
@Narrat 
This should be solved meanwhile as we open the cache details now without animation. Feel free to reopen/comment if you disagree.
