### ISSUE TITLE
Cache Title hard to see at a glance in redesigned cache pop-up

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#11481]
The title has been moved inside the pop-up, now it's the same size as any other detail and visually not easily distinguishable.

Proposal: make the text fat or divert from the current tabular layout for the title to make it "glanceable" again.

**Comment by moving-bits** [comment]
It's the first entry in the list, so should be pretty visible. But that's my personal opinion only. 

Will wait for some more user feedback (core team?), and either change styling or close this issue.

**Comment by bekuno** [comment]
There were some user on FB searching for the cache title. 
A more visible text would be better.
I would suggest a thicker or/and larger font, but not another color.  
The changed format should also used in the waypoit popup (for the WP name and cache name) and the cache detail side.

**Comment by fm-sys** [comment]
A bigger font size whould IMHO look broken, so I would suggest making the title bold...

**Comment by SammysHP** [comment]
We had some design ideas for a new popup floating around somewhere. Not a small popup but more like the map quicksettings thing. How much work would it be to implement something like that?

Otherwise I'd suggest to move the title out of the table into its own header section with bigger font und bold.

**Comment by moving-bits** [comment]
Here's a proposal:
- larger font
- centered with separator
- no "name" prefix

![image](https://user-images.githubusercontent.com/3754370/132257637-fe5cac35-f8bf-4b51-9f91-ccdcff7b3d3a.png).![image](https://user-images.githubusercontent.com/3754370/132257643-24d56c91-23ef-4b36-b36a-e2bf4c75b224.png)

**Comment by ztNFny** [comment]
Sorry, i'm.a bit late to this party. What does it look like with long names? My main problem with the old display - name in dialog title - was that it's cut of for long titles, e.g. on a trail the cache number is missing. This was a lot better with the smaller text inside the dialog.

Of course there's no way to make it ideal for all usecases, but it's something that should be keptnin mind as a usecase.

**Comment by Lineflyer** [comment]
I tried it here on my vacation. Its multi line capable so it fits all caches titles.. Really well done @moving-bits

**Comment by ztNFny** [comment]
That's great, thx!
