### ISSUE TITLE
Removal of gcvote.com?

### ISSUE THREAD

**Issue by Surfoo** [cgeo/cgeo#11487]
Hello,

http://gcvote.com/ is down since a while, and maybe never fixed.
Maybe this feature could be removed?

I don't know java but maybe I can make a PR if you want.

**Comment by rsudev** [comment]
Take a look at #9664 for our current thoughts/approach...

**Comment by Surfoo** [comment]
Thanks, I didn't know about this new website. Seems not really ready for production...

**Comment by Lineflyer** [comment]
BTW: While the website tells its broken, the server is still working and delivering and accepting data and logins.

**Comment by wolverine007** [comment]
What about a config option inside the settings menu?

So the user could decide to show or hide the cache rating?

For me the rating has honestly no benefit, it is more a pain in the back for refreshing cache details while you are in an area with bad mobile internet connection, cause the GC vote values are also update directly via a dedicated connection...
...but even with a good connection it takes extra time to refresh the listing.

**Comment by moving-bits** [comment]
@wolverine007 
Have a look at settings => services => gcvote.com

**Comment by wolverine007** [comment]
Good to know, wasn't aware that there is now an option available 👍🏼

**Comment by fm-sys** [comment]
> Removal of gcvote.com?

As long as the gcvote.com backend is working, we should not remove it without a replacement. Let's close in favor of #9664
