### ISSUE TITLE
Smaller font size for logging and entering coords

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11484]
### Describe your problem!

A (visual-impaired) user contacted us on support mail with this text (shortened):

---

I have not good eyes, I was on more operation with them, so I have
big problems to read smaller texts.

And the new GUI design was changed in the way, that the recatngles
were added around all the input data and the font of the input texts
was significantly decreesed.

It is mainly hard for the input of coordinates or distance/azimuth,
where the numbers must be writtten exactly.

Please, should it be possible increese the input font, especially
for fieds with numerical inputs? There is enough space in the fields
in the horizontal direction, now unused.

[...]
On the other way, the rectangles around the input fields seems me
unnecessary, taking a lot space on the screen. But as it is a one
of the main changes in the last GUI, the revert back unfortunately
cannot be expected.

---

I made two screenshots to prove he is right:
![Screenshot 2021-08-16 224041](https://user-images.githubusercontent.com/949669/129627168-4da7a4ab-3097-4d76-a714-7873587d75f6.png)
![Screenshot 2021-08-16 224124](https://user-images.githubusercontent.com/949669/129627170-80e855c2-4a64-4798-8d57-6951e2247566.png)

### How to reproduce?

Use logging or coordinate input

### Actual result after these steps?

Smaller fonts as before

### Expected result after these steps?

Same font size?

### Reproducible

Yes

### c:geo Version

2021.08.15

### Additional Information

I asked the user to try the general scle up option on his device settings.

**Comment by Lineflyer** [comment]
Support ticket  #247562

**Comment by brabl2** [comment]
This is something what cannot satisfy all people. 
On my device (Sony XA1 with 5" display) the new c:geo GUI caused approx. 30% bigger font.
And I personally do not like it, the bigger font the less info on the screen.
Could it be possible to setup the text size in the c:geo configuration?

**Comment by eddiemuc** [comment]
c:geo now honors the Android-wide settings for Font Size. A first step would be to ask the user to increase/decrease this font size. I would expect that if font is too small/large in c:geo then it is also too small/large in all other apps. I tried and could significantly increase or decrease the font size with this approach.

As for the border around the input fields: the only solution I can think of is to include another option to change their color to eg. gray (so they are not so "prominent" any more).

To my knowledge, the topic of accessibility was never really tackled in c:geo. There would be lots of Todos I assume. This would fit as a (larger) topic into a GUI redesign (and material.io supports this I think).

**Comment by brabl2** [comment]
I'm using default font size in the system. 
The font is too large only in the new c:geo GUI, other apps are normal.
I'm not going to use the small font for the whole system, other apps text would be too small.
You never get 100% happy users...

**Comment by eddiemuc** [comment]
> I'm using default font size in the system.
> The font is too large only in the new c:geo GUI, other apps are normal.

That's strange, at least Google Apps should use the Android settings. For example, if I play around with the Android font size settings, I can see e.g. the texts in Gmail or Calendar get bigger/smaller the same as in c:geo. Normal text in c:geo seems to have same size as e.g. normal (unformatted) email text in Gmail.

> You never get 100% happy users...

True dat

**Comment by brabl2** [comment]
Depends what "normal" size you expect in which application, the absolute size is same, which of course is not convenient for all apps. 
Especially in the list of caches in c:geo I would like to have the same amount of text as in the old GUI. 
The new GUI list of caches is not very compact, one cache uses often 5 rows with big spacing, so the list shows only 6 caches per my 5" screen.

**Comment by Lineflyer** [comment]
> This is something what cannot satisfy all people.

Yes and no.
But this case (picture in initial post) shows the very same device with old and new release and our intentation was probably not to reduce font sizes but rather keep them the same or in tendency increase them a bit (due to many requests in the past).

In this special case a visual impaired user told us, it was small before but he could handle it..now he can no longer handle it.

There is a side issue, which I currently try to clarify with the user, that changing his system font settings has absolutely no effect. But still:  The initial issues seems valid IMHO.

Can someone confirm that we reduced those font sizes explicitly?

**Comment by wolverine007** [comment]
Maybe the font size could be handled with variables in addition to the new modern.ui being used now.

So the system wide settings are used in general, but when someone wants or needs it bigger or smaller a scale factor could be set and is added or subtracted from the default values, so the font size is only changing inside cgeo.

**Comment by Lineflyer** [comment]
I managed to fix it for the coordinate input with #11507 

For the general size of all other text input field (logs, waypoint notes and all other places where text input fields show up) someone with more experience needs to take a look.
Not sure which generic font size to use and where to define it. 

IMHO this is all we need to do to avoid a smaller text than before UI changes. The rest (discussed above) can be done via system font settings. Please lets not add further additional settings for this but rather improve it based on user feedback to be OK on default font sizes and the rest is up to the user.

**Comment by fm-sys** [comment]
> For the general size of all other text input field (logs, waypoint notes and all other places where text input fields show up) someone with more experience needs to take a look.

For real text inputs, the new font size is perfectly fine IMHO. It's really annoying to write larger texts if the size is to big and the text gets wrapped more than necessary... Before our redesign, the size difference between inputs and other texts had looked very unaligned. Note, that the request was mainly only about the number inputs anyway:

>It is mainly hard for the input of coordinates or distance/azimuth,
where the numbers must be writtten exactly.
>
>Please, should it be possible increese the input font, especially
for fieds with numerical inputs?

**Comment by Lineflyer** [comment]
Indeed the initial user which I cited only talked about coordinate input, but there are couple of other users claiming (and its correct) that the text in input fields (waypoint notes, logging text,...) all got smaller. 

IMHO we should still see to keep it same as before.
If you refer to the pictures in the initial post, you can see it was kind of unproportional: The "Report problem" got slightly bigger, the log text smaller. I can't think, this was intentional.

**Comment by fm-sys** [comment]
> The "Report problem" got slightly bigger, the log text smaller. I can't think, this was intentional.

The "very big text input size" was the Android 4 default style  BTW ;-)

While it was indeed intended to reduce them a bit, your PR looks like a very good compromise:

Currently - 16|PR - 18|Old - 20
-|-|-
Might be a bit too small | Looks good | definitely too big

**Comment by Lineflyer** [comment]
> While it was indeed intended to reduce them a bit, your PR looks like a very good compromise:

I showed it to some caching friends which had some hard time with our release. He also "approved" the 18sp.
