### ISSUE TITLE
found LC are not hidden with filter "found" off

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11498]
Labcaches with state found are not hidden on map, when set the filter to hide found caches.

To reproduce:
- activate the LC connector
- show map with LC
- open a LC, set them to state found
- open the filter
- unset the option for found caches

result:
All caches but not the found LC are hidden.

expected:
Also found LC are hidden.

see also #10475

**Comment by eddiemuc** [comment]
I tried to reproduce but the feature worked fine for me:

![Screenshot_20210819-085053.jpg](https://user-images.githubusercontent.com/6909759/130022387-e8bb2df4-fb25-4451-816b-4912f23813dc.jpg)

![Screenshot_20210819-085129.jpg](https://user-images.githubusercontent.com/6909759/130022395-51d3698a-ca93-4adc-87b8-a069c1abca8a.jpg)

I used current production version 2021.08.15

Did I do correct steps for reproducing? Are there other circumstances I did not think of?

**Comment by bekuno** [comment]
I tested once more, not it works.
But I´m sure that it did not really work for me 3 days ago.
And we have a thread at FB with such a problem.
For one user it was fine after deactivating/activating the LC Connector.

**Comment by bekuno** [comment]
I tested once more, not it works.
But I´m sure that it did not really work for me 3 days ago.
And we have a thread at FB with such a problem.
For one user it was fine after deactivating/activating the LC Connector.
![grafik](https://user-images.githubusercontent.com/32555742/130027959-e946ea5c-9dc1-4e38-8341-e33e8f7c480e.png)

**Comment by eddiemuc** [comment]
Not sure if I interpret the FB thread right, is it possible that the user deleted the lab cache from local db after setting the "found" state? Because this would also delete the "found" state, and c:geo would interpret the lab cache as "not found" next time it is loaded into live map

**Comment by Lineflyer** [comment]
I can also not reproduce it, working fine here.
Of course those caches need to be kept locally to preserve the found state.

I guess it was only, that users deleted them after setting found.
The FAQ entry includes this hint: https://www.cgeo.org/faq#ALC_found

**Comment by bekuno** [comment]
@eddiemuc @Lineflyer 
I think you are right.
And I can not remember what problem was really on my device.
So lets close here.
