### ISSUE TITLE
Cache icon not mapped to center of the map

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#11493]
### Describe your problem!

In detail view of a Tradi, or any other cache that does not have additional waypoints, upon long press on the compass rose the icon is mapped to the center of the map (as expected).

If that cache has additional waypoints with coordinates present, upon long click on the compass rose the cache icon is not mapped to the center of the map (not as expected).

Long pressing the compass rose for any of those waypoints renders those to the center of the map (as expected).

### How to reproduce?

See above

### Reproducible

Yes

### c:geo Version

2021.08.15

**Comment by Lineflyer** [comment]
mmh..for me the cache icon is still centered on the map also if additional waypoints are present. The only difference is, that the map is zoomed out to cover all additional waypoints (that depends on Settings - Map - Zoom contains waypoints).

**Comment by eddiemuc** [comment]
> mmh..for me the cache icon is still centered on the map also if additional waypoints are present. The only difference is, that the map is zoomed out to cover all additional waypoints (that depends on Settings - Map - Zoom contains waypoints).

Same for me. To be more precise:
* If the setting above is **NOT** checked, then the cache is centered on opening (and waypoints may or may not be on the screen, depending on how far away they are from the cache)
* If the setting above **IS** checked, then the zoom level and shown area is adjusted such that all waypoints and the cache itself are visible (the cache is most likely not centered in this case)

**Comment by baiti** [comment]
would it help if I provided screenshots and explict GC-codes?

**Comment by baiti** [comment]
I believe it happens because it tries to visualize all WPs, even though, I have disabled "original waypoints" as those are not relevant to me as oppesed to other waypoints such as stages of multi caches.

So in essence even if an icon is not shown because I have said "don't show original waypoints" their coordinates are still used to determine the center of the map shown.

**Comment by Lineflyer** [comment]
> If the setting above IS checked, then the zoom level and shown area is adjusted such that all waypoints and the cache itself are visible (the cache is most likely not centered in this case)

Are you sure about that. To me in a few tries with different caches it looks like the algorithm is, that the map is centered on listing coords and the zoom is calculated to include the most distant waypoint. So it should be centered.

@baiti:
Please provide a screenshot...it usually says more than 1000 words, you know ;)

**Comment by eddiemuc** [comment]
Actually that was my comment. Here is a screenshot from my live phone (current production version) after opening the map for a cache with many waypoints. "Zoom to waypoints" is enabled. As you can see the cache is not centered, but the map is adjusted to fit all waypoints and the cache nicely (this is also exactly how I like it btw):

![Screenshot_20210818-200008.jpg](https://user-images.githubusercontent.com/6909759/129949135-6ffdd961-9fc1-46e8-8ee3-38d6f9bd0642.jpg)

**Comment by Lineflyer** [comment]
Now I finally got it.
So indeed its intentional, that in case "Include all waypoints" is active the cache is no longer centered but the view is centered to cover all waypoints instead.

@baiti I think its no bug then, isn't it? Feel free to reopen.

**Comment by baiti** [comment]
For sure it is the right thing to do to reposition map and zoom such that all WPs of a specific cache are shown. That repositioning, however, only makes sense if in the end more than one icon shows up on the map. If I have disabled  (pls look at Settings -> Map Waypoints) additional waypoints, it makes no sense so reposition / re-zoom the map and the result happens to be a single icon on the map that might be somewhere close to an edga and hard to spot at a glance.

**Comment by SammysHP** [comment]
AFAIK opening the map for a cache should always show additional waypoints independent of the configuration.

**Comment by Lineflyer** [comment]
> AFAIK opening the map for a cache should always show additional waypoints independent of the configuration.

Correct, the settings option is only for the live map but not for a map of a single cache.
@baiti Are you sure it only shows the main icon to you in that case?

**Comment by baiti** [comment]
I have to reproduce the scenario. Will get back with results.
