### ISSUE TITLE
Show ALCs if filter for D/T incl. inconclusive is active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11499]
### Describe your problem!

I remember we discussed this somewhere but cannot remember the conclusion.

A user contacted us with the use case to generally filter out to high D/T values on the live map.
In the users case he uses 1<=D<=4,5 and 1<=T<=4
The user mentioned, that this also filters our all adventure labs.

I recommended to the user to use the advanced mode and select "Include inconclusive results", but this does not help.

### How to reproduce?

- Premium member (GC and ALC connector active)
- Open live map
- Set filter advanced mode
- Filter for 1<=D<=4,5 and 1<=T<=4
- Activate "include inconclusive results"

### Actual result after these steps?

No Adventure lab caches shown

### Expected result after these steps?

Adventure lab caches shown

### Reproducible

Yes

### c:geo Version

2021.08.15

**Comment by eddiemuc** [comment]
Current implementation assigns the value 0 to difficulty and terrain for lab caches (and user defined caches), it does not handle this case as "inconclusive". "inconclusive" was meant for cases where c:geo can't known the value of a filtered property. In the current case, c:geo knows the value however. Example: if someone filters for attributes but attributes are not known for a cache on life map. Other example: someone filters for fav percentage on live map but the value can't be calculated for a GC cache which is not stored locally

It is simply such that the current filter does not allow to filter for "unset" or 0 value. We have a similar case in another (not yet solved) issue where it is asked to filter for difficulty/terrain higher than 5.

One solution to this would be to treat "unset" as "1" in the filtering.

A second solution would be to add the value "unset" to the choosable range.

As a third option, it is possible of course to tread "unset" as "inconclusive", but this is not how "inconclusive" was meant to be used (at least by me).

**Comment by Lineflyer** [comment]
> Examples for intended usage of "inconclusive":
> 
> if someone filters for attributes but attributes are not known for a cache on life map.
> someone filters for fav percentage on live map but the value can't be calculated for a GC cache which is not stored locally
> 

"User filters for d/t but d/t is not known for ALC cache" sounds very similar to me

> As a third option, it is possible of course to tread "unset" as "inconclusive", but this is not how "inconclusive" was meant to be used (at least by me).

From a pure data model I would expect a fresh and empty cache in our DB should theoretically be filled with NULL or "some value representing unknown/unavailable".
Now the cache is filled with all data available and the rest remains unavailable and is ignored when activating "inconclusive matches".
I know its probably not as easy as that...

**Comment by eddiemuc** [comment]
> "User filters for d/t but d/t is not known for ALC cache" sounds very similar to me

But the d/t value is not unknown in this case. It is "unset" (which is known to c:geo) because lab caches simply don't have d/t. "Inconclusive" means that the value is not known to c: geo, in the current case c:geo does know the value.

Anyway, before this gets too theoretical: I am absolutely fine with stretching the meaning of "inconclusive" to those cases where fields of caches are not set.

**Comment by eddiemuc** [comment]
> From a pure data model I would expect a fresh and empty cache in our DB should theoretically be filled with NULL or "some value representing unknown/unavailable" in all data fields.

Already the class `Geocache` does not accept `null` values for d/t. This is not a DB problem. 0 is currently used to represent "not set" on a technical level. Afaik there's no situation where the d/t value of a cache is "unknown"

**Comment by Lineflyer** [comment]
You are right (of course :) )

I am still thinking back and forth whether including "not set" into "inconclusive" does the job. It would still require users to activate "inconclusive" to see ALCs after they limited the D/T rating via filter.
Wouldn't it be better, that ALC (which don't have D/T) would simply be ignored by that filter without needed "inconclusive" flag?

**Comment by eddiemuc** [comment]
> Wouldn't it be better, that ALC (which don't have D/T) would simply be ignored by that filter without needed "inconclusive" flag?

Interesting idea, hasn't occured to me yet. 

Caches without d/t rating include both lab caches and user-defined caches. Don't know if there are any others (e.g. when imported via gpx or not supported by any connectors). 

If we apply the idea and someone filters for e.g. caches with d=5 then all the caches above would still be visible. Is this expected by user? Then I think it's a fine idea.

I assume that caches with d/t > 5 should still be filtered out right? (There is another issue about handling those)

**Comment by murggel** [comment]
> > Wouldn't it be better, that ALC (which don't have D/T) would simply be ignored by that filter without needed "inconclusive" flag?
> 
> Interesting idea, hasn't occured to me yet. 

I like that idea too.


> 
> Caches without d/t rating include both lab caches and user-defined caches. Don't know if there are any others (e.g. when imported via gpx or not supported by any connectors). 
> 
> If we apply the idea and someone filters for e.g. caches with d=5 then all the caches above would still be visible. Is this expected by user? Then I think it's a fine idea.
> 

It would be at least easy for the user to filter them out by uncheck the types, he doesn't want to see.

**Comment by Lineflyer** [comment]
> If we apply the idea and someone filters for e.g. caches with d=5 then all the caches above would still be visible. Is this expected by user? Then I think it's a fine idea.

Yeah...thats probably another unexpected scenario then.
At the end we have to decide on the strategy especially for D/T on ALCs as we probably can't suit all expectations anyway.

I am still undecided which of the two methods
- Ignoring ALC for D/T filtering generally
- Ignore them only if "inconclusive " is active

fits to more potential filtering use cases.

**Comment by murggel** [comment]
I am thinking of the behavior for "rating" in that case - what would I expect for caches with no rating... 

I guess the variant with the "inconclusive" option seems to fit more filter options
The disadvantage - it has impact to multiple filter-options in that filter and probably I want it only for some?

Not so easy...

**Comment by fm-sys** [comment]
IMHO it's pretty clear that ALCs have a inconclusive D/T value, so should be handled that way by the filter framework. 

> The disadvantage - it has impact to multiple filter-options in that filter and probably I want it only for some?

That's a general problem IMHO. If there a really situations where a global inconclusive switch doesn't do the trick, we need to migrate it to a per filter item checkbox setting. But that should to be tackled outside this issue and only if it is really requested by some users...

**Comment by eddiemuc** [comment]
Well, just implement it as "inconclusive" then.

Ver easy to implement for the "in-memory" filter part.

The tricky part might be the SQL search, which does not support "inconclusive" yet. Up to now, "inconclusive" was meant for cases where c:geo can't know the real value, but for SQL queries c:geo always has complete info about caches, so such a case was not possible. Now, caches with a known D/T value ("unset" or 0) should be treated as "inconclusive", that's a new thing.

**Comment by eddiemuc** [comment]
Nothing happening here for a while (or on #11629), still relevant?

**Comment by fm-sys** [comment]
> 
> 
> Nothing happening here for a while (or on #11629), still relevant?

More urgent than ever ;-)

Someone just needs to take the issue and start coding... IMHO there was kind of an agreement (at least no contra), but we can briefly discuss this issue this evening.

**Comment by eddiemuc** [comment]
> > Nothing happening here for a while (or on #11629), still relevant?
> 
> More urgent than ever ;-)

Can't be that urgent. After all, in the last ten years (with the old filtering) this was not possible either :-)

**Comment by Lineflyer** [comment]
I am not sure, if this was dicussed in the last meeting as I did not attend.

From what I read above I think the consensus would be to include ALC if inconclusive is used.
IMHO it makes sense, and users can easily use the cache type filter to hide them again in case its unwanted for them.

**Comment by moving-bits** [comment]
IIRC the dev team has very limited dev capacity at the moment, that might be the reason why no one has stepped in yet.

**Comment by moving-bits** [comment]
How about adding a checkbox to this filter, something like "[x] Do not apply this filter to Lab adventures and User-defined caches"?

This would make the filtering behavior explicit instead of having some "hidden rule".

**Comment by eddiemuc** [comment]
> How about adding a checkbox to this filter, something like "[x] Do not apply this filter to Lab adventures and User-defined caches"?

My understanding from last dev call was that we add such a checkbox with a text like "[x] Include caches without D/T rating in result", but only for "advanced mode" (in basic mode this checkbox would be implicitly Off if any range other than 1-5 is selected and On otherwise - which is the currently implemented behavior).

In practice I assume that both suggestions would result in the same thing.

**Comment by moving-bits** [comment]
Ah, had forgotten about it. But now it's documented;-)

**Comment by Lineflyer** [comment]
Wasn't this solved by showing ALC  caches as soon as the "Inconclusive" option is active?
At least I told this to users and never heard complains ....

**Comment by Lineflyer** [comment]
I would like to bring this topic up again to your attention:
Not remembering the dev call decision after all.
But I guess adding this exception to the "include inconclusive results" would be the way to go.

As I was not aware, that this problem is still open I actually gave that advice to some users on support mail. One user now responded its not working...now I know why :)
