### ISSUE TITLE
"Search caches nearby" when other app sends intent VIEW + geo uri

### ISSUE THREAD

**Issue by k3b** [cgeo/cgeo#11510]
#### Usecase

Next week i go on holyday and i want to know in advance which caches are near my hotel.
It would be cool i can use my navigation app (or any other geo aware app) as a starting point for the search.

#### Technical details

Many android apps allow to view (or share) geo-infos from other android apps by intercepting action.VIEW/SEND with geo uri.

c:geo should do this, too. The result would be a pre-filled c:geo-SearchActivity.

c:geo already does this with ".NavigateAnyPointActivity" to define a navigation point or a private geocache.

#### Examples: 

* search marker in navigation app (filling search field coordinates)
  *  Example: OsmAnd navigation app: select a coordinate in the map and share/view it.
     * long-press in the map will create a marker.
     * select the newly created marker
     * press the share symbol.
     * Select "geo:"
     * => a list of geo-apps is shown
* search for caches by postal adress from android adressbook (filling search field "adress")

### What solution would you suggest?

* In manifest add intent-filter for VIEW + geo uri for SearchActivity
* if SearchActivity#onCreate analyse intent
  * data contains geo: with  latitude/longitude fill latitude/longitude search field
  * data contains geo: without latitude/longitude fill adress field

### Additional Information

I can do the implementaion for you and create a merge request when done.

For technical details see

* https://github.com/k3b/k3b-geoHelper/wiki/Android-Geo-howto
* https://github.com/k3b/k3b-geoHelper/wiki/Android-Geo-aware-apps

**Comment by bekuno** [comment]
The idea sounds interesting.
As no one did answered yet - maybe the use case (for the developers?) is not very big or not clear enought?

I think that you before creating an implementation should show the use case with one/some screen shot(s).

**Comment by k3b** [comment]
@bekuno thanks for your reply.

I have added a concrete usecase to the issue description

**Comment by fm-sys** [comment]
> @bekuno thanks for your reply.
> 
> I have added a concrete usecase to the issue description

Feel free to provide a PR for it 👍

**Comment by k3b** [comment]
To implement "Search geocaches nearby" i have added my lib com.github.k3b:k3b-geoHelper:1.1.9 (License: Apache-2.0)
to parse geo-uril.

In the last commit i have replaced the geo-reg-exp-parsing of NavigateAnyPointActivity with this lib, too 

From git history is see that NavigateAnyPointActivity is used to implement #9289 #9290.

@Lineflyer @moving-bits can you please test if #9289 #9290 still works as expected with my modification since i donot have the the app, where the geo call comes from to test it. If it doesn-t work i rollback the change, before issueing the merge request.

Bug or feature? In the manifest NavigateAnyPointActivity only catches geo uri-s where mime is null (= no entry <data android:mimeType="*/*" />) but not where mime has a value which needs an additional .<intent-filter../>

**Comment by k3b** [comment]
Current status: 

* Implementation complete, Works as expeced. 
  * Tested with geo-source "osmand" and with "Clicking on adress in simple-contacts"
* ready to be merged if someone has tested if my change in NavigateAnyPointActivity still works as expected.

**Comment by moving-bits** [comment]
@k3b 
Can you provide a PR for current state (marked as "Draft" or with label "WIP / do not merge) - would make testing way easier for me. Thanks.

Regarding the two mentioned issues: Only #9290 is implemented currently, #9289 is still open.

If you want to test yourself, you can install the app "Adventure Lab" from "Groundspeak Inc.", see https://play.google.com/store/apps/details?id=com.groundspeak.react.adventures, login with your gc.com credentials, search for lab adventures, open one and navigate to it. c:geo should open then, offering to create a new waypoint or add theses coordinates to an existing user-defined cache.

**Comment by k3b** [comment]
thanks for the info about "Adventure Lab". I installed app and i was able to create a userdefined cache for the geo source. So from my point my changes are ready to merge. See #11694

**Comment by moving-bits** [comment]
@k3b 
PR #11977 is merged. Can we close here or is anything relevant left open?
