### ISSUE TITLE
multicache helpers

### ISSUE THREAD

**Issue by ondrodrak** [cgeo/cgeo#11514]
### Tell us your idea!

My suggestion is to add a multi/mystery cache clue helper. It would be basically just notes, but better. For example, when you would write clues for a multicache, it could calculate the coords of the next waypoint or the final cache. For mystery caches, it would be basically just notes. It could calculate formulas or something. You could write a formula for coords like ABC.DEF and then it would make lines where you would input the respective data and it could automatically show a preview of the location based on the data.

### What solution would you suggest?

This could appear as a submenu in the front screen/main menu. It would be the third line of submenus or it could just be labeled "Notes" in the three-dot-menu in the top right corner of the app.

### Is there an alternative?

GCDroid and GeoBuddy have these features, but c:geo is so much better than those apps and I really don't want to switch to something paid and closed-source.

### Additional Information

If you could consider this, thank you so much. This app is awesome as it is right now but this could make it so much better.

**Comment by Lineflyer** [comment]
Did you already try the c:geo waypoint calculator:
https://manual.cgeo.org/en/coordinatedialog#waypoint_calculator

**Comment by ondrodrak** [comment]
I did, but that's not the whole idea. It doesn't really as a notebook and clue keeper.

**Comment by ondrodrak** [comment]
nevermind

**Comment by ondrodrak** [comment]
One more question. The waypoints i create in c:geo are stored locally, right?

**Comment by fm-sys** [comment]
> One more question. The waypoints i create in c:geo are stored locally, right?

Yes, exactly.

**Comment by moving-bits** [comment]
But you can store the waypoint info into the cache's personal note, and upload this to the server. (Both to be done with the buttons beneath the "personal note" input field.)

**Comment by ondrodrak** [comment]
thank you so much!
