### ISSUE TITLE
Don't animate tab change when opening cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11527]
### Describe your problem!

Three users reached out to us, with the following "problem":

The introduction of the material tabs instead of the old viewpager causes the cache infos always to start on the left most tab (wypoints) after opening and only then scrolls (animated) to the wanted tab.
Two problems with that:

- Two of the users have activated the option "Remember last page" in Settings - Cache-Details which leads to extensive/long lasting animations if e.g. gallery was the last opened tab.
- The third user does not use the "remember last page" but uses a rather old device (Android 6) and reports that even the auto scrolling from waypoints to details is stuttering and takes a lot of time. 

As this behavior occurs each time when opening a cache, I can assume it can be annoying to some users.
Is there a possibility to avoid this animation if a certain tab is put into focus on opening a cache or do we have to live with that?

### How to reproduce?

- Activate "Remember last page" in Settings - Cache-Details
- Open a cache and open the gallery tab
- Close the cache
- Open another cache

### Actual result after these steps?

Animated scrolling until gallery tab is reached

### Expected result after these steps?

Directly open with gallery tab 

respectively (if "Remember last page" is not active):

Directly open with details tab

### Reproducible

Yes

### c:geo Version

2021.08.15

**Comment by Narrat** [comment]
Kinda related, because mentioned there: #11461 and #11476

**Comment by moving-bits** [comment]
reopened as the fix for this issue needed to be reverted due to the side-effects described in #11567
