### ISSUE TITLE
Report Problem screen suggestions

### ISSUE THREAD

**Issue by Samwiseuk** [cgeo/cgeo#11522]
### Tell us your idea!

1. The simplest suggestion I have to improve c:geo's Report Problem pull-down menu in the logging screen is to modify the wording of one of the existing problem reports:

From:  "Logbook is full" -> Log text: "This geocacher reported that the logbook is full."
To:  "Log needs replacing" -> Log text: "This geocacher reported that the log is either full or damaged, and needs replacing."

This is because 90% of the time I find I need to file a problem report, it is because the log _paper_ (most of the time, not a book so I suggest using the general term log to cover both books and papers) has become too wet and needs replacing.  It may seem pedantic, but the point is that I would rather c:geo not be reporting that the "logbook is full" when actually the problem is that the log is damaged, which might mislead the owner.  The suggested change in wording will work for both cases - whether the log is full or damaged, the correct wording is that it needs replacing in both cases.

2. The second suggested improvement would be to add an additional Problem Report entry which covers the slightly difference case where a log paper / book may be damp, but salvageable i.e. it just needs taking home to dry out, before it can be replaced:

"Log is too damp to sign" -> "This geocacher reported that the log is too damp to sign and requires drying out."

3. Finally, it is possible that the "Container is damaged" and the "Log needs replacing" options may both be true, so perhaps one more additional problem report could be:

"Container & log need maintenance" -> Log text: "This geocacher reported that the container is damaged and the log is also in need of maintenance."

### What solution would you suggest?

At a minimum, the text templates for the Problem Reports could just be updated as described above.

However, what I would personally find more useful is if selecting any of the Problem Report options resulted in the appropriate template text generated for a Needs Maintenance post be displayed in an editable text box below which can then be modified by the user.  This would provide the current simplicity of being able to report a generic problem with the usual minimum number of clicks, whilst also providing the option for the user to amend the problem report with more specific additional details appropriate to the problem being reported.

**Comment by eddiemuc** [comment]
Hi @Samwiseuk , the possible selections for "problem report' are not invented by c:geo. This is the maintenance problem list as it is available on GC.com, it is just copied to c:geo

![Screenshot_20210823-190805.jpg](https://user-images.githubusercontent.com/6909759/130488506-b21b0393-efcf-4e30-9b6f-56ce6e9c7e5e.jpg)

So I guess a request to change this list must be addressed to Groundspeak.

**Comment by Samwiseuk** [comment]
ahh, I did have a poke through the c:geo codebase and couldn't find the message texts - that'll be why!

Thanks.  I guess c:geo could override these by effectively offering the option of submitting templated Maintenance Reports pre-written by c:geo instead, but now I can see where these options have come from, I can imagine why it might be preferable to leave them in-step with the geocaching.com website.

Of course, a c:geo user can log whatever text they want by making a Needs Maintenance post manually and using whatever text they prefer, it's just a bit slower to type it all in each time.

Given this, I think the best way of improving this workflow would probably be to have some kind of templating system where the user can provide some pre-written log options (perhaps in Settings) which they could then select to use as the log text...  then the user could specify their own different options for log texts, whether maintenance or otherwise.

But that's definitely a different feature request, so I'll close this one.  Thank you!
