### ISSUE TITLE
Cache placer (hider) option 

### ISSUE THREAD

**Issue by simrebel** [cgeo/cgeo#11529]
### Tell us your idea!

It would be nice if cgeo would have a  cache placer function .   I use a discontinued app called geocache placer 
that brought up  a satellite map , let you do a average then you were able to save the location by name 

If this function was pout into cgeo it would  a asset  and shouldn't be that hard to implement 

cache hider tool  would bring up a live map of where you are  
display  other caches with a circle around  them at  528 feet or 161 meters 
a average button so it will  do a average  gps reading 
save to a list   with Name  D/T  and cache notes . 

Then  you could bring this  cache up in the later and have all the info in front of when your creating your cache page

**Comment by Lineflyer** [comment]
This should be covered by our existing user defined caches in combination with the open feature request #9398 for a wapoint coordinate average functionality.
Therefore closing as a duplicate.
