### ISSUE TITLE
Extend support for calculated variables in cache

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#11520]
Last days I thought about how we can add better support for calculated values into c:geo especially for mysteries and multis. We already have the waypoint calculator but it has a few drawbacks:
* it can only calculate waypoints from variables. However I often have to calculate other things as well esp numbers to open locks, checksums and such
* It does not allow for usage of e.g. formulas. For example I often need to calculate Buchstabenwortwerte (what's the English word for it?) or checksums and have to leave c:geo for it
* It is somewhat deeply buried into the waypoint details which makes it difficult to use.

Therefore I propose the introduction of a new cache tab "Variables" which allows for adding variables and put a formula on them. Here's a sketch on how this may look:

![IMG_20210823_133035__01.jpg](https://user-images.githubusercontent.com/6909759/130441186-ff781d32-f046-48ba-88f3-f881a6663876.jpg)

Additional ideas:
* Variables created here could be used in waypoint calculator of course
* A scan could be implemented trying to parse formulas/variables from listing and adding them here. Might be a heuristic approach where user can decide whether a result is correct or not before it is added. (A 100% correct scan is probably impossible to implement)
* Functions available for usage in formulas must be discussed. Whatever set is chosen it can easily be extended later.

Idea is also to make the entries editable directly (no "open" step necessary) to ease their usage in the field.

Some more details, probably not so important right now:
* No strong typing of variables. Current idea is to support text and int as values in the variables. If something looks like an int it is interpreted as such, otherwise as text. Is float support necessary?
* Variable names are Case-sensitive and start with a letter. Can be composed of letters and digits otherwise
* In a formula, every letter-block is interpreted as a constant text, except if a variable of same name exists (then it is interpreted as the variable of course). Optionally text can be enclosed by " or '

What do you think?

**Comment by eddiemuc** [comment]
It seems the idea is supported (three thumbs-up), I may make this my next "big project" after cleanup of filters is done

**Comment by eddiemuc** [comment]
Notes to self:
* In a later step, one could add support for "unknown varlables". E.g. "for unknown var E, iterate from 0 to 9 and create all possible waypoints as calculated by formula"...
* To be decided whether this is worth introduction of something like ANTLR or handleable with the expression parser for filters / calculated waypoints

**Comment by eddiemuc** [comment]
Working on this feature I fear I thought too complicated. I will try to rethink and separate between functions and integer calculation explicitly. So a variable will be:
* **Either** the result of a function call (e.g. a Buchstabenwortwert)
* **Or** a calculation expression like A+2*B

But combinations like the following are maybe not necessary to be supported in one step

`2*A*(QUERSUMME(BWW("test")))`

This should easify things a lot. Among other things I don't have to introduce some sort of simple type system...

**Comment by eddiemuc** [comment]
@Lineflyer PR #12018 tries to fix all of your feedbacks. Exception is that the new "help" button currently simply points to the page explaining the formula syntax, must be pointing to a manual page once one is available (when feature is integrated)

**Comment by Lineflyer** [comment]
@eddiemuc 
Great news! 
Sure, referencing the help to our Git wiki is OK for now...maybe you just open up an issue at cgeo/guide as a reminder to migrate/add it to the user guide.

Regarding the "Add missing":
Now I understand perfectly fine after your explanation. I was simply on the wrong way as I manually entered "A" and "C" and expected it to add "B", but thats nonsense ;)

**Comment by eddiemuc** [comment]
As time permits (and if no high-prio-topic comes up e.g. error in prod) I would like to go the next step on the variable topic, which is integration into calculated coordinates.

In this first step, I don't plan any big GUI changes (except maybe make the input fields for var values a bit wider in calculated coordinates), but function will change:
* The biggest change: All variables used become Cache-Global (e.g. a value defined for a Variable A will be the same for all calculated waypoints in this cache). Today they are waypoint-local (two calculated waypoints in the same cache can and have to define their own value for e.g. a variable A)
* This also means that if a variable is edited inside a calculated waypoint, this var is changed Cache-Global (not only local for this single waypoint) 
* For existing calculated waypoints, this means that a migration routine must be done. In cases where same variable has different value for different waypoints on same cache, new variable names will be assigned (e.g. if a cache has two calculated waypoints, the first defining A=3 and the second defining A=4, then migration will take over A=3, but also create a new variable not yet used in cache (e.g. C), assign 4 to it and replace A with C in the second waypoint)
* As of then, var usage in calculated waypoints is no longer restricted to uppercase-single-letter. 

This change will be quite some work, and I want to be sure that the team is fine with the taken direction before approaching it. So I am asking for feedback here. Maybe also something for the team meeting?

**Comment by eddiemuc** [comment]
Ah yes, and also the routines for export/import calculated waypoints to Personal note most likely need adaption

**Comment by murggel** [comment]
> Ah yes, and also the routines for export/import calculated waypoints to Personal note most likely need adaption

This is currently only for the simple format available...
I wanted to implement it for the others as well, but unfortunately did not find the time yet 😫

**Comment by moving-bits** [comment]
> This change will be quite some work, and I want to be sure that the team is fine with the taken direction before approaching it. So I am asking for feedback here. Maybe also something for the team meeting?

On a quick glance: LGTM, change will be much appreciated by many users, I guess, as "cache global vars" have been requested several times in the past.

One tiny idea: On renaming vars during migration, you could name the new var in a way that resembles the old name, to make it easier for the user to recognize their old formula. E. g.: on renaming a variable "a" which occurs in two waypoints, you could name the additional occurrences like "a1", "a2" etc., so that it still contains the "a" from the original var name. But that's just fine-tuning...

**Comment by eddiemuc** [comment]
> > This change will be quite some work, and I want to be sure that the team is fine with the taken direction before approaching it. So I am asking for feedback here. Maybe also something for the team meeting?
> 
> On a quick glance: LGTM, change will be much appreciated by many users, I guess, as "cache global vars" have been requested several times in the past.

Oh, good to know, I was not aware of this...

> One tiny idea: On renaming vars during migration, you could name the new var in a way that resembles the old name, to make it easier for the user to recognize their old formula. E. g.: on renaming a variable "a" which occurs in two waypoints, you could name the additional occurrences like "a1", "a2" etc., so that it still contains the "a" from the original var name. But that's just fine-tuning...

@moving-bits 
Well, it may seem like fine-tuniung but it touches a core-question of the underlying formula syntax: how to handle variable names with more than one character.

Let's assume we have in one cache two calculated variables:
* One with coordinates N42 12.AAA E10 34.000  and value A=3
* One with coordinates N42 13.5AA E10 34.010 and value A=4

if I would now migrate the first A to a1 and the second to a2, then I would have to rewrite the two coordinates as follows:
* First one: N42 12.($a1)($a1)($a1) E10 34.000  
* Second one: N42 13.5($a2)($a2) E10 34.010

This is because two-or-more-letter-variables must be prefixed with $ and separated from other texblocks (they can't be chained directly).

Now the questions:
* do we really want that, or would we rather use another one-letter-variable instead?
* Is there in general a better idea to handle more-than-one-letter-variables in formula syntax? (I did not find any, as long as we want to support easy autochaining for the most-common one-letter-vars => because this is done in almost any cache using variables)

**Comment by eddiemuc** [comment]
> > Ah yes, and also the routines for export/import calculated waypoints to Personal note most likely need adaption
> 
> This is currently only for the simple / plain format available...
> I wanted to implement it for the others as well, but unfortunately did not find the time yet 😫 

I looked a bit over these formats (the ones other than "simple")...
* A new task for me: chaining of cars must also be possible in float numbers to support this. I guess I start with this rather small task
* @moving-bits those formats only support one-letter-vars. If we keep them there's no chance to replace one-letter-vars with two-char-vars in migration
* I wonder if we really need these formats... I think everything they support can be done with simple format too, can it? Is this really used by a wider user base?

**Comment by moving-bits** [comment]
Thanks @eddiemuc for your detailed reply (and sorry for me getting too it so late - have been on a longer business trip).

> @moving-bits Well, it may seem like fine-tuniung but it touches a core-question of the underlying formula syntax

no offense meant by the term "fine-tuning" - I did not imply anything with regard to implementation effort, but I meant "fine-tuning" in terms of recognizability for the user. If there have been multiple waypoints having a certain variable name, it would be easier to recognize which was which when the new var name still contains the same letter. Or so my thought. But I do not regard this as too important, therefore named it "fine-tuning".

> This is because two-or-more-letter-variables must be prefixed with `$` and separated from other texblocks (they can't be chained directly).

ok, understood

> do we really want that, or would we rather use another one-letter-variable instead?

I could live with one-letter vars and var-renaming as well. (Although this leaves the - probably hypothetical - edge case of running out of free one-letter vars if there are many waypoints and/or many vars being reused on several waypoint.)

> Is there in general a better idea to handle more-than-one-letter-variables in formula syntax?

The only alternative I can think of would be to have a special begin and end marker not being used in formulas and var names otherwise, e. g. surrounding such a varname with colons (`:a1:`, `:a2:`) or similar. Having two or more of those vars directly behind each other would lead to constructs like `:a1::a2` etc. (An alternative to `:` could be `"`: `"a1""a2"` etc.)

**Comment by eddiemuc** [comment]
@moving-bits 

> no offense meant by the term "fine-tuning" 

No offense was taken, don't worry :-)

> this leaves the - probably hypothetical - edge case of running out of free one-letter vars

In this (hopefully seldom) case I would fall back to two-letter-vars and the more complicated syntax a la `($A1)`

> ... have a special begin and end marker not being used in formulas

Interesting idea. However, we can't use `"` or `: `since both are already used as special chars in formulas (`"` to mark text values and `:` as alternative symbol for division, since it is used quite a lot in formulas in cache listings like that). 

We could of course use $ like this (e.g. `$A1$`)
Also something like the following should be possible too: `$A1$A2` (the surrounding parenthesis can be left out if pure vars are chained without numbers between them

**Comment by moving-bits** [comment]
Played a bit with it:

> Also something like the following should be possible too: `$A1$A2`

Does a `$` sign imply a multi-letter var name? Otherwise we might get a conflict if someone introduces an `A` variable :-(

Some more questions:

How do we distinguish between `(` - `$A` - `1` - `)` and `($A1)`? (Meaning: How can we detect whether the brackets are used as marker for a multi-letter var name or just as brackets?

And how to distinguish between `($A1` - `1` - `)` and `($A11)`? (How many chars are allowed in a multi-letter var name, and how to detect whether a number is part of a var name still or a separate number already?)

Both could be solved with a begin end marker: (using `$` sign as marker)
- `($A$1)` (or simply `(A1)`) vs. `($A1$)`
- `($A1$1)` vs. `($A11$)`

One could also use `<` and `>` as marker chars - maybe easier to read, if we want to follow the begin/end marker path:
- `(<A>1)` (or simply `(A1)`) vs. `(<A1>)`
- `(<A1>1)` vs. `(<A11>)`

Or we introduce mandatory white space between var names and subsequent numbers:
- `(A 1)` vs. `(A1)` - `(A1)` is no longer a shortcut in this syntax but the variable named `A1`!
- `(A1 1)` vs. `(A11)`

(Less readable, to my opinion)

**Comment by eddiemuc** [comment]
@moving-bits 

Let me explain first how it is implemented today:
* `$` denotes a variable. All the follow letters & digits (first char must be a letter) will be interpreted as the variable's name. If another char (including e.g. whitespace or another $) is detected it is no longer interpreted as part of the name. Examples:
    * `$A` denotes the variabe `A`
    * `$A$B` denotes variable `A` chained with variable `B` (and is idential to writing just `AB`). If `A=1` and `B=3` then this would evaluate to `13`
    * `$AB` denotes variable `AB`
    * `$A1$A` denotes variable A1 chained by variable `A`. If `A1=4` and `A=3` this would evaluate to `43`
    * `($A1)1$A` denotes variable `A1` chained by digit `1` chained by `A` If `A1=4` and `A=3` this would evaluate to `413`
    * `($A1 + 2)1$A` denotes variable `A1` plus 2 chained by digit `1` chained by `A` If `A1=4` and `A=3` this would evaluate to `613`
    * `1$A` denotes the digit `1` chained with the value of `A`. If `A=5` this would evaluate to `15`
* single letter expressions (without `$` in front) are interpreted as single letter variables. For example `AB` denotes variable `A` chained with variable `B`, and `AB1` denotes variable `A` chained with variable `B` chained with `1` (if `A=2` and `B=3` this evaluates to `231`)
* parenthesis simply group expressions of any kind. No special meaning for "single var names in parenthesis". By chaining parenthesis you chain the results of those expressions. Examples:
    * `(A)` denotes just value of variable `A`
    * `($A+1)` denotes value of the expression `A+1`
    * `(A+1)($B+1)` chaines the result of expression `A+1` with result of `B+1`. If `A=1` and `B=2` then this evaluates to `23`

To your questions:

> How do we distinguish between `( - $A - 1 - )` and `($A1)`? (Meaning: How can we detect whether the brackets are used as marker for a multi-letter var name or just as brackets?

brackets are used to group expressions. There is no special distinguishing between their usage for multi-letter var name or other expression groups. `($A1)` evaluates to the value of variable `A1`. `( - $A - 1 - )` is an invalid expression (the minus at the end has no second operand. `( - $A - 1 - A)` would be valid. If `A=2` this would evaluate to `-5`

> And how to distinguish between `($A1 - 1 - )` and `($A11)`? (How many chars are allowed in a multi-letter var name, and how to detect whether a number is part of a var name still or a separate number already?)

There are as many chars allowed as you want, only the first one needs to be an alpha. `($A11)` evaluates to value of variable A11. `($A11ABDE45264AA)` evaluates to value of variable `A11ABDE45264AA`. `($A11ABDE45264AA + 1)` evaluates to value of variable `A11ABDE45264AA` plus `1`.

You may just play around with current implementation in current nightly or master branch by the way - just use the variable tab.

> Both could be solved with a begin end marker: (using `$` sign as marker)

as far as I understand it, the mentioned problems are not present in current implementation. Nevertheless, we could of course change implementation to marking variable names with  begin and end marker of any kind of course (may it be $ or <>) if this is more liked by the users/team? But then the users have to type more. (two markers per multi-char-variable)

> Or we introduce mandatory white space between var names and subsequent numbers:

I am strongly against that. Among other things, it will be incompatible to the formula coordinate formats used in most cache listings. E.g. something like `N45 12.ABC` would then be interpreted as something with a variable `ABC `instead of three chained variables `A`, `B` and `C`.

**Comment by FH-Inway** [comment]
I saw the announcement in the last update changes about the variables tab page. After some trial and error, I was able to figure out how to enable debug mode. Still, the variable tab is not shown for me. Any idea what I'm doing wrong? Would like to give this a try. Or maybe someone can provide a screenshot of a variable tab in the wild to make sure I'm looking for it in the right place (cache details)?

Version: 2021.11.21
Source: Google Play Store

**Comment by Lineflyer** [comment]
@FH-Inway 
Highly encouraged, that you would like to test this. 
Unfortunately this feature is not yet included in `2021.11.21` codewise, thus you cannot enable it by debug mode.

It will only be available in the next planned beta if you stay on the normal Google Play releases.
If you really want to try it, I would suggest to try out our nightlies (which are really stable right now). See here for more details:
https://www.cgeo.org/development

**Comment by eddiemuc** [comment]
@FH-Inway in addition to what @Lineflyer says: if you try this out now, please be gentle in your judgement, this is in a rather early development phase. (This is the reason it is only visible in nightlies so far)

**Comment by FH-Inway** [comment]
Appreciate your responses. Based on the changelog, I was hoping to test this by just enabling debug mode. Switching to the nightlies is a bit too much (unless there is an option to do a side by side installation?).
I registered for the beta program and will take it for a spin when it becomes beta.

**Comment by FH-Inway** [comment]
Didn't find a way to do a side by side installation, but I got an Android emulator running and installed the nightly there. Works great so far and I can view the variables tab.

**Comment by Lineflyer** [comment]
@FH-Inway 
A side-by-side is not possible as the nightly shares the same application namespace. This is done on purpose to allow and test upgrades, etc.
But as you have an emulator running that even better :)

**Comment by eddiemuc** [comment]
Implementation is quite far now. I will close this issue in favor of issues in dedicated project which should sum up the leftover tasks.
