### ISSUE TITLE
Make sorting of Individual route easier

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11531]
### Tell us your idea!

Currently, it is really annoying to dive deeply into sub menus for resorting the individual route.

![Screenshot_20210825_171545_cgeo geocaching](https://user-images.githubusercontent.com/64581222/130818441-55b38be5-9ee8-42a6-84e4-11ef401ea854.jpg)

### What solution would you suggest?

I suggest making the individual route clickable, like it is done in locus. But instead of showing a big list of options, just show one directly clickable entry, "edit individual route". 

![Screenshot_20210825_171445_menion](https://user-images.githubusercontent.com/64581222/130818722-2bebc1c3-20e8-499f-addf-04937c9cc88e.png)

While we are on it, I think we can move the "delete individual route" into the sorting screen as well. (Similar to what we have in the filter framework)

![Screenshot_20210825_171801](https://user-images.githubusercontent.com/64581222/130819470-ac9508eb-6881-4a97-bcf6-5dd191afa073.jpg)

**Comment by moving-bits** [comment]
Do you know how to make a GMap `Polyline` clickable?
And for OSM, a Canvas path is being used.

**Comment by fm-sys** [comment]
> Do you know how to make a GMap `Polyline` clickable? And for OSM, a Canvas path is being used.

Unfortunately not. I had spent some hours on it myself, but did not found a solution. I fear we have to calculate, whether the clicked coordinates are close enough to the track (which also depends on map zoom factor, etc)

**Comment by Lineflyer** [comment]
Do you really think its worth the effort and also think about possible side effects of more clickable items on the map...

**Comment by fm-sys** [comment]
> 
> 
> Do you really think its worth the effort and also think about possible side effects of more clickable items on the map...

I'm also open for different solutions, but currently it isn't intuitive at all. 3 clicks just for opening the 'route resorting' is IMHO definitely too much...

**Comment by moving-bits** [comment]
I could imagine some bottom slide menu like the quick settings as replacement for most of the "individual route" submenu, only being available when we have an individual route.
Just looking for a good place for the icon to ooen such a menu. At the bottom it's already "crowded" with cooyright info, scale, quick settings icon and zoom controls. Maybe at the right, vertically centered (or slightly higher, to not interfere with GM zoom controls). There would even be space for two or three such context sensitive controls, if needed.

**Comment by fm-sys** [comment]
Sounds like a good idea. We should however IMHO not randomly clutter the map, so I would vote for moving the quick settings button to the right side as well. 

Maybe not totally at the top, but a bit more vertically centered so that it can still be reached...

This UI design is BTW also used by "the other app" ;-)

![Screenshot_20211002_153140_copy_182x322](https://user-images.githubusercontent.com/64581222/135718596-a46ce864-1e56-4aaf-953c-8d8e27b8ce56.png)

**Comment by moving-bits** [comment]
> Sounds like a good idea. We should however IMHO not randomly clutter the map, so I would vote for moving the quick settings button to the right side as well.

Agreed

> Maybe not totally at the top, but a bit more vertically centered so that it can still be reached...

For sure, as we have distance info at the top. Icons must still be reachable when supersized distance info is visible.

> This UI design is BTW also used by "the other app" ;-)

Which other app? "There can only be one" ;-)

Would we switch to a (modal) side sheet or stay with bottom sheet? (https://material.io/components/sheets-side)

**Comment by fm-sys** [comment]
> Would we switch to a (modal) side sheet or stay with bottom sheet? (https://material.io/components/sheets-side)

Sounds interesting. However, I haven't ever seen this in any Android app yet. But as we already today have space problems, it's probably better to use the whole screen width (-> bottom sheet).

But it might be interesting for large-screen devices like tablets (which we however do not actively support currently). However, is this component available at all?

![grafik](https://user-images.githubusercontent.com/64581222/135724460-29aa982b-bcfb-4ee1-90e4-58703f5cab31.png)

**Comment by moving-bits** [comment]
> > Would we switch to a (modal) side sheet or stay with bottom sheet? ([material.io/components/sheets-side](https://material.io/components/sheets-side))
> 
> Sounds interesting. However, I haven't ever seen this in any Android app yet. But as we already today have space problems, it's probably better to use the whole screen width (-> bottom sheet).

I came to look for something like a side sheet because of the horizontal animation (instead of vertical with bottom sheet) - looks more natural to me when having the icon at the side instead of at the bottom.

Haven't seen it in an Android app yet, either, in contrast to e. g. navigation drawers (which would not fit in this use-case, IMHO). But I'm not fixed to it, so let's stay with bottom sheet.

> But it might be interesting for large-screen devices like tablets (which we however do not actively support currently). However, is this component available at all?

At least they explicitly mention a modal version of the side sheet, targeted specifically to mobile devices.

**Comment by moving-bits** [comment]
It could look like this:

![image](https://user-images.githubusercontent.com/3754370/135744096-0e6d78b5-c87c-496e-abd3-f8e70ca3ef8f.png)

(BTW: Instead of using the old hand-crafted settings wheel I switched to a standard material.io SVG for both icons. Format and size is our default button style.)
