### ISSUE TITLE
Attribute icons change

### ISSUE THREAD

**Issue by turbogauchiste** [cgeo/cgeo#11536]
### Tell us your idea!

Hi, not really a bug or a feature suggestion but I noticed cache attribute icons on cgeo are different from those on the Geocaching website, and on ProjectGC, making it harder to compare when looking for new attributes, if that makes sense. Thanks for your work already!

**Comment by ztNFny** [comment]
Are there any specific icons that are hard to recognize? While we can't just use GCs icons we can of course improve the existing ones.

**Comment by Lineflyer** [comment]
@turbogauchiste You can also click on the attribute icons to show the attributes as text instead. Could be helpful if you compare something.

**Comment by bekuno** [comment]
@turbogauchiste There is one more point. You can use c:geo also with other caching platforms. They use also attributes with their own styling. See e.g. at https://www.opencaching.de/articles.php?page=cacheinfo .

**Comment by moving-bits** [comment]
Closing here as the original request cannot be implemented due to copyright reasons, and there were no suggestions for alternatives. Feel free to reopen if someone comes up with a feasible alternative icon set.
