### ISSUE TITLE
QR Scanner App

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11530]
We have linked a QR scanner app in c:geo. However, the app seems to be discontinued and is categorized as malware by some user reviews... 

Is anyone using the app or can/should we remove the link? 

![Screenshot_20210825_005857_copy_432x460](https://user-images.githubusercontent.com/64581222/130700981-72c650a9-c28d-4398-af8e-634f12329516.jpg)
![Screenshot_20210825_005916_copy_432x305](https://user-images.githubusercontent.com/64581222/130700983-69b6abe5-60f5-467c-9da3-56747caa3f61.jpg)
![Screenshot_20210825_005751_copy_539x2559](https://user-images.githubusercontent.com/64581222/130700986-5eaf760d-039f-4a8d-a7fb-b18e96d0100e.jpg)

**Comment by rsudev** [comment]
I have this app installed and I am still using it occasionally. I cannot confirm any of the issues mentioned in the reviews, but I also have a version from 2018 (no updates announced), not the latest as shown in the play store (Feb 2019). Maybe I even installed it from f-droid.

**Comment by Narrat** [comment]
Reading an issue in the upstream repo it seems it was a case of another app using the source and name and added ads on top. It got removed and the users may went ballistic in the wrong place.
https://github.com/zxing/zxing/issues/1345

**Comment by fm-sys** [comment]
Thanks for the research, nice to hear that we don't have links to malware in c:geo 😅

**Comment by bekuno** [comment]
I have also this app installed, but using another app normally. I do not have the mentioned issues. The app was installed from PlayStore with version 09.09.2018, which is the latest official release. No update is shown.

As this software will never updated anymore we should have a look at alternatives.
One idea is https://play.google.com/store/apps/details?id=org.barcodescanner. This is a FOSS app with source at https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner .

**Comment by fm-sys** [comment]
Question is, whether we really need a link to a QR scanner in c:geo's main screen at all? IMHO, it would be sufficient to only have it listed in our "usefull apps"

**Comment by rsudev** [comment]
The idea behind this menu item is, that one cacher can 'share' a cache to the barcode scanner and his colleague has a quick access to get that info into c:geo on his device. No need to read and manually enter cache codes if you want to share a cache in the field.

**Comment by geocachermgo** [comment]
I found this reader giving good results:
QRQR QR Code Reader by arara.
Some examples are given by https://coord.info/GC8NHKX
or https://datagenetics.com/blog/november12013/index.html

**Comment by ztNFny** [comment]
As there is no universal scan intent to start any scanner I vote for removing the menu item altogether.
It's value always has been limited anyway - when you come upon a QR code why would you start c:geo to start the barcode scanner from there instead of starting it directly from your launcher?
