### ISSUE TITLE
[vectorIcons] Map drawer rendering issues

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11545]
### Describe your problem!

I've noticed a number of rendering issues with map markers while testing the new vector icons - but I think those issues are actually unrelated to the vector icons, I just happened to notice them now.

List Marker icons displayed in the wrong position. Selecting the cache (opening the cache info popup but not the details page) fixes this, but only for the specific icon. In the screenshot the 3rd cache from top was selected.
![signal-2021-08-27-141750_002](https://user-images.githubusercontent.com/1258173/131126655-de9d31b8-77e6-4fe3-b668-a9cbdc64540f.jpeg)

Parts of the marker info not displaying (the completly white one is a traditional)
![signal-2021-08-27-141750_003](https://user-images.githubusercontent.com/1258173/131126656-3f0b58aa-804c-49d5-9d1b-c8aac83324bc.jpeg)

Wrong layer order (note icon should be on top)
![signal-2021-08-27-141750_004](https://user-images.githubusercontent.com/1258173/131126657-3ad08384-c28e-4920-a802-ab666d3e77ba.jpeg)

### How to reproduce?

Those issues are not really repoducable, they just happen. I was using a list of ~3000 caches, so list size might be related.

### Reproducible

Unclear

### c:geo Version

https://github.com/ztNFny/cgeo/commit/40d802cb86f04d34af19743836e12d35f80496cf

**Comment by fm-sys** [comment]
Not sure if that fits into this issue, but it would increase visibility a lot if the list markers would get a white circle as background...

**Comment by ztNFny** [comment]
> Not sure if that fits into this issue, but it would increase visibility a lot if the list markers would get a white circle as background...

I don't see how that's feasible. The circle would be large enough to contain the whole icon, so a lot bigger than the icon itself. Which means either we get a huge circle (that overlays a lot of other stuff) or a tiny icon in a circle that's the same size as the markers.
Many icons don't need a background to be visible (see the boxes on the screenshot above) - maybe we should instead improve the selection of icons with visibility in mind (and I'm also missing some useful GC-related icons in there, like 🎣)

**Comment by fm-sys** [comment]
>Parts of the marker info not displaying (the completly white one is a traditional)
![signal-2021-08-27-141750_003](https://user-images.githubusercontent.com/1258173/131126656-3f0b58aa-804c-49d5-9d1b-c8aac83324bc.jpeg)
> Those issues are not really repoducable, they just happen. I was using a list of ~3000 caches, so list size might be related.

Do those issues still happen? I have seen such issues some weeks ago, but no longer since then...

**Comment by ztNFny** [comment]
It happens, but very rarely and not repoducable at all.
