### ISSUE TITLE
Use 'sync' icon instead of 'cached'

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11559]
![grafik](https://user-images.githubusercontent.com/64581222/131179424-69bb11a5-99d0-4b2d-bb91-9d7ed0ec9540.png)
![grafik](https://user-images.githubusercontent.com/64581222/131179387-2c3e05ff-6095-4746-9e06-13deab414ec6.png)

> Shouldn't we use the same rotation for both icons?

Had the same thought, but that's the only  material.io icon which is available (-> seem to be intended)

![Screenshot_20210827_230343_copy_67x176](https://user-images.githubusercontent.com/64581222/131188587-a61bfd54-a01a-41de-8015-391cb1a71410.jpg)

But: material.io uses a different rotation for "sync" which IMHO looks better. And then also the other icon makes sense: It is not fully rotated / "synced" ;-)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11555#issuecomment-907477500_

**Comment by moving-bits** [comment]
Done, thanks @pet0etie
