### ISSUE TITLE
Do we really need the rawimages/svg for Doku-Wiki?

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11562]
### Tell us your idea!

If we use png for the Doku-Wiki, the question arised, if we still want to maintain 2 locations for the images (used vector drawables and rawimages) or if it is sufficient to create the png on demand.

It was planned to use the svg directly in the DokuWiki, but that was not successful - see cgeo/cgeo-guide#40

So I see following options:

Store "original" image as svg in rawimages/svg: 
Advantage: 
* png can be created "automatically" / script based
* svg already available if downloaded as svg and imported into AndroidStudio

Disadvantage:
* no easy handling for usages of icons available in AndroidStudio / Vector assets -> additional svg-file needed 
* have to keep them in sync

Store icon as png in rawimages/png:
Advantage:
* png directly available

Disadvantage:
* no easy handling for usages of icons available in AndroidStudio / Vector assets -> additional png-file needed 

Don't store original icon in rawimages:
Advantage:
* no need to keep them in sync

Disadvantage:
* if used in Doku-Wiki, the png has to be created somehow

### What solution would you suggest?

To discuss with @Lineflyer

### Additional Information

see discussion in #11555

**Comment by murggel** [comment]
I think my favorite would be currently to use the current svg in raw images to create the png and update them in the DokuWiki and then delete the rawimages/svg folder, so no need to keep them in sync (it's still hard to keep the manual in sync, I guess).

For all "new" or "updated" icons the png are created on demand somehow (I can try to write a script to convert xml to svg, did not find something yet, but should not be so difficult).

I can share the script / commandline for ImageMagick to convert from svg to png, so it can be still used later (if needed / script for xmlToSvg is available)

**Comment by Lineflyer** [comment]
For clarification regarding Dokuwiki:
I added SVG support to the Dokuwiki and would prefer to use the SVG icons over there 1-to-1 as we did with the png.
The only problem is, that Dokuwiki shows them black on black currently. 

I do not have so many insights into SVG syntax, however regarding Dokuwiki it would be enough to somehow enforce white coloring (like in our dark theme in c:geo).

**Comment by murggel** [comment]
I understand, but in code we use XML-format and the svg is a "duplicate" in a different format. So I understand @fm-sys concerns about keeping them in sync.
There will be no problem to change the color for the svg manually, I wanted to try to have a kind of automatism for creating / having the correct svg.

I found a python script, which can convert those xml to svg. Only thing then is to adapt the color.

So I would change the color for the current svg in rawimages, upload them to DokuWiki and delete them from the repo.

If in future svgs for the DokuWiki will be needed, the used xml can be e.g. converted with the python script to svg (or the svg downloaded from web, since the original filename should be known).

**Comment by murggel** [comment]
I uploaded the white svgs to the DokuWiki, so the rawimages/svg can be deleted now. Will prepare a PR and adapt the description in our wiki
