### ISSUE TITLE
Viewpager - Tab content out of sync to tab title

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11567]
### Describe your problem!

Just checking out the latest change introduced by #11534 and noticed a problem with that.

When you swipe manually between the tabs of a cache, the title below gets "out of sync" to the content shown and lacks behind by one tab.

This shows what I mean:
![Screenshot_20210828-115444_cgeo](https://user-images.githubusercontent.com/949669/131214159-fec9c049-0496-496d-823b-c056e6f95746.jpg)

Additionally the animation on manual swiping is also not as smooth as before (I understood it should still be as before?) but just jumps to the next tab rather sluggish.

### How to reproduce?

- Open cache
- Swipe between tabs

### Actual result after these steps?

The tab title lacks behind by one tab, the orange marker is shown somewhere "in the middle" between tabs.

### Expected result after these steps?

Correct tab should be highlighted, orange marker should be in sync as well.

Ideally  also the animation should be restored to the previous look unless this is the drawback we have to accept if we want to avoid the animation on opening it.

### Reproducible

Yes

### c:geo Version

2021.08.28-NB1

### System information

```text
Samsung S20
Android 11
```

**Comment by fm-sys** [comment]
Just tested it on a real device and it feels _very_ bad... Much worse than the initial issue. 

I would clearly vote for reverting the commit in `release` branch , and search for a better solution on `master` without release pressure. 


https://user-images.githubusercontent.com/64581222/131217446-fac91b06-fc47-4960-b70f-e9f6e53236e3.mp4

**Comment by moving-bits** [comment]
That's really an ugly side-effect of the change for #11527 (though I can't explain it). 
I'll revert #11534, reopen #11527, and close this issue here
