### ISSUE TITLE
Filter status no longer shown in nearby search

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11572]
### Describe your problem!

I have activated hiding of own, found and deactivated caches on the live map (live filter).
This is correctly shown in the filter status bar "Status: 3 Elemente".

When I use nearby search (where also the live filter is applied) it used to also show "Status: 3 Elemente" but since recently only shows "-".

See screenshots.
![image](https://user-images.githubusercontent.com/949669/131215950-5ffcd2ce-3271-41b2-aad2-8e2dd93bfc6d.png)

![image](https://user-images.githubusercontent.com/949669/131215963-cea77e4e-b595-403f-ae8a-3fa069098ae0.png)

### How to reproduce?

- Open live map
- Use quick settings to filter out, found, own, deactivated
- Close live map
- Click on nearby search

### Actual result after these steps?

Filter status bar shows `-` 
Filtering is working as expected

### Expected result after these steps?

Filter status bar should show `Status: 3 Elemente`

### Reproducible

Yes

### c:geo Version

2021.08.28-NB1

### System information

```text
Samsung S20
Android 11
```

**Comment by eddiemuc** [comment]
Most likely an unwanted side effect of recent code cleanups by @fm-sys and myself.

@Lineflyer this is on master only, right?

**Comment by Lineflyer** [comment]
Did not test on release yet. Will do.

**Comment by eddiemuc** [comment]
> Did not test on release yet. Will do.

I tested on production version, bug seems not to be in it

**Comment by Lineflyer** [comment]
Strange enough, I cannot reproduce it on an API30 emulator, while its happening on my API30 device.

Possible differences are:
- Emulator uses basic member
- Emulator has only one connector active

**Comment by eddiemuc** [comment]
> Strange enough, I cannot reproduce it on an API30 emulator, while its happening on my API30 device.
> 
> Possible differences are:
> - Emulator uses basic member
> - Emulator has only one connector active

Strange, don't know how that might be related. I suspect a hidden (catched) exception during the filter parsing process. Do you have any exceptions in the log, maybe in debug mode?

**Comment by Lineflyer** [comment]
Nothing unusual showing up in the debug log.

Sys info shows this:
```
- Hide waypoints: original
- LIVE: Status:3 Elemente ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status:owned_no:found_no:exclude_disabled))
- OFFLINE: Keine ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))
```

I a bit confused about how to interprete this empty D/T values....so is this filter status OK?
The offline filter is not active, the live filter should only be set up to filter owned, found, deactivated.

**Comment by Lineflyer** [comment]
Up to now I did not manage to get the live filter status bar back to show anything except `-`.
I tried various searches with various filters (Cache type, D/T, several status filters). The filters are all working normal but its always showing `-`.

Any further debug idea?

**Comment by eddiemuc** [comment]
> I a bit confused about how to interprete this empty D/T values

Those values are ok. They mean that nothing is filtered (first `d=` ia Minimum difficulty, second `d=` is maximum difficulty, same with terrain, `-` means "nothing specifier")

**Comment by eddiemuc** [comment]
> Up to now I did not manage to get the live filter status bar back to show anything except `-`.
> I tried various searches with various filters (Cache type, D/T, several status filters). The filters are all working normal but its always showing `-`.

> Any further debug idea?

Not right now. I guess I have to try reproducing it myself and scan code. As soon as I find a laptop with internet and time... Unfortunately I am currently on vacation

**Comment by fm-sys** [comment]
Maybe I can also take a look this evening... (I will assign myself as reminder)

**Comment by eddiemuc** [comment]
I just started working on it, found the bug and are just about to push a fix :-)

**Comment by fm-sys** [comment]
Ok, thanks for taking a look!

**Comment by eddiemuc** [comment]
PR #11589.

There was a clear "inverted" usage of a boolean flag. @Lineflyer I wonder why you couldn't reproduce on emulator, the bug should have been present there too.
