### ISSUE TITLE
Map title not updated when live mode enabled/disabled

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11571]
### Describe your problem!

Seems to be caused by the recent change (using the dedicated enable/disable icon).

### How to reproduce?

- Open live map
- Title shows "Live map"
- Disable live mode

### Actual result after these steps?

Title still shows "live map" and only changes to "map" once I e.g. rotate the device

### Expected result after these steps?

Title should change to "map"

### Reproducible

Yes

### c:geo Version

2021.08-28-NB1

### System information

```text
Samsung S20
Android 11
```

**Comment by fm-sys** [comment]
It's easy to fix, but are you sure this was working before (as I can't imagine how the change should have triggered this)?

**Comment by Lineflyer** [comment]
mmh..at least I never noticed, that its not working but I am not quite sure.

**Comment by fm-sys** [comment]
Ok: Map -> Livemap does work. The issue exists only in the other direction...

**Comment by fm-sys** [comment]
> Ok: Map -> Livemap does work. The issue exists only in the other direction...

Furthermore, it works fine for GMap, only mapsforge online/offline seems to be affected. 

@Lineflyer can you verify this?

BTW, we really need to merge these two map implementations. Or at least decouple all generic code parts. What we currently have is a total mess :-/
