### ISSUE TITLE
Next beta + feature release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11588]
After releasing 2021.08.28 the discussed plan is to 
1. wait some days if there are any regressions to be fixed
2. merge open PRs to `master` which we want to include in next feature release (Vector icons not yet)
3. Fast forward `release` to `master`
4. Publish beta
5. Start implementing major changes on `master`

FYI:
I will be on vacation first two weeks in September. So preferably I would do steps 1-4 within next week. In case of major problems during beta phase, someone else would probably need to update/publish the beta, as I am not confident to have sufficient internet access.

**Comment by Lineflyer** [comment]
Before thinking about a new beta, I think we should try to tackle the incoming bugs/regressions first (if solvable as a bugfix/minor change).
The following came to my mind (but might not be complete...feel free to add some):
- [ ] #11607 
- [ ] #11606 --> PR #11608 available
- [ ] #11596 
- [ ] #11584 --> PR #11587 available
- [ ] #11583 
- [ ] tbc...

**Comment by Lineflyer** [comment]
Added #11619 above.
It seems it would be time for a bugfix release if someone is available to work on the issues above.

Just FYI:
I will be on vacation starting Sunday for 16 days. If parts or all can be solved before that, I can push a release.
Otherwise someone else would need to take care of it.

**Comment by moving-bits** [comment]
We have four fixes available for a new bugfix release. I've merged those four PR to `release` and `master` to have them in the next nightly for a short test. If everything's fine I propose to release a bugfix release from current state of `release` branch before @Lineflyer's vacation.

After that, we should decide if we want to start a new beta from current state of `master` - probably starting only after @Lineflyer's vacation, or if we want to continue work on `master` by merging the two larger changes awaiting merge - namely "vector icons" and "bottom navigation".

My proposal would be to merge those two. IMHO there's nothing urgent on `master` right now, and I would really like to see those two changes on `master` to get user feedback and to ease collaboration. (Or, if two at a time seems to big a change, I would like to start with vector icons.) And since we have to wait for @Lineflyer to return from vacation before we can start another release, we have to wait anyway. - Time that can be used for straightening things on one or both of those larger changes.

**Comment by fm-sys** [comment]
The vector icons seem to be quite ready IMHO, but we should do a new feature release, at least before starting the bottom navigation beta. 

My proposal would be to forward release branch to the current state of master (after the bugfix release), before merging the vector icons so we have the easy possibility to decide whether we want to start the next beta with or without the vector icons.

As soon as we call the new icons  ready  we can forward release again and can think about starting with the bottom navigation on master...

**Comment by Lineflyer** [comment]
I gave up on #11596 for now.
Maybe just the workaround to force the rightmost fields to leftbound? That I could do today.

**Comment by fm-sys** [comment]
> Maybe just the workaround to force the rightmost fields to leftbound? That I could do today.

Sounds like a good idea. Left bound should  be the text input default anyway IMHO...

**Comment by Lineflyer** [comment]
As I am on vacation for the next 14 days I added some more details to the [checklist for releases](https://github.com/cgeo/cgeo/wiki/Checklist-for-release-process) as help if someone else wants to publish the bugfix release once its ready.

**Comment by moving-bits** [comment]
I can start working on a bugfix release (my first ever!) either today in the evening or on Tuesday, whatever is preferred.

**Comment by moving-bits** [comment]
- [x] Check/Insert correct version name as headline in ```/main/res/raw/version_release.txt```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment]
Bugfix release is published. Thanks for your contributions!

(@Lineflyer will look into FB / Twitter)

Regarding the next release let's wait a few days to see if anything's coming up, and if everything's fine forward `master` to `release` to start a new beta - maybe this weekend.

**Comment by moving-bits** [comment]
After a published release is right before a new release...
If no one objects I will start preparing a new release from current state of `master` for a (probably short) beta tonight, and merge the `vectorIcons` branch to `master` after that.

**Comment by moving-bits** [comment]
Beta version with state of yesterday's `master` is published to Play Store.

@ztNFny: I will merge branch `vectorIcons` to `master` tomorrow evening to give you a chance to finish whatever you are currently working on, and to continue on `master` starting tomorrow evening. I'll send you a notice via GitHub once it's merged.

**Comment by moving-bits** [comment]
@ztNFny vectorIcons branch is merged to `master` now, let's continue development for new icons on `master`...

**Comment by moving-bits** [comment]
Current beta behaves normal, so I suggest to publish current RC as next release on Monday evening.

**Comment by Lineflyer** [comment]
@moving-bits 

We still carry some regressions with us.

In order to have stable quality and not pile up regressions I suggest to fix them first (if someone is available to do that). Experience from last years showed, that those bugs otherwise might got forgotten and over time we get a more buggy app.

I have found some bugs of new features / regressions of existing here:

https://github.com/cgeo/cgeo/issues/11607
https://github.com/cgeo/cgeo/issues/11666
https://github.com/cgeo/cgeo/issues/11635
https://github.com/cgeo/cgeo/issues/11628
https://github.com/cgeo/cgeo/issues/11610
https://github.com/cgeo/cgeo/issues/11582


That should not necessarily block a new feature release, but I think we should also focus on fixing up those things.

**Comment by Lineflyer** [comment]
As this issue is closed I will take the last comment into a new one.
