### ISSUE TITLE
Stuck loading indicator on live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11585]
On my emulator API 30 when running current `master` I have the following problem:
- Clicking a cache on live map shows the "Loading cache details" for split second before the popup is shown
- Note the "Loading cache details" window is still in background

![image](https://user-images.githubusercontent.com/949669/131247963-c5f86f39-765e-4275-b853-6b9def15dc93.png)

- When closing the popup I got stuck here forever

![image](https://user-images.githubusercontent.com/949669/131247975-333e3b9f-ade0-4a00-bb4f-77c3addda214.png)

Does not happen on my API 30 real device running todays nightly.

Emulator is running BM, real device is PM (if this makes any difference)

**Comment by Lineflyer** [comment]
Logging in as basic member on my real device I can also see the same issue.
Looks like it happens only to basic members?!

**Comment by Lineflyer** [comment]
@fm-sys I somehow remember you wrote something in some issue about fixing something around this topic, but can't find it anymore.
Can this problem be related and can you reproduce it (on `master` as BM)?

**Comment by Lomanic** [comment]
Same thing as a premium member on cgeo 2021.08.29-NB-ec68dca

**Comment by fm-sys** [comment]
Indeed I changed something in there. Actually, I tried to remove the dialog which was visible for some milliseconds.

It seems there were somehow 2 places where the dialog get shown but only one were it gets hidden.

I guess (without having checked it):
- I've removed the place where the dialog gets canceled, but removed only one place where it gets shown. This results in an endless dialog.

Just for clarification: On which map does it happen, Gmaps and/or Mapsforge?

**Comment by fm-sys** [comment]
Thanks for the hint that it happenes for PM's as well. Only Google Map is affected.

Workaround for nightly users: 
Please use OSM online/offline map for the time being.

**Comment by Lineflyer** [comment]
> Only Google Map is affected.

Ah...well yes, that was the other difference between my devices which I did not realize ;)

**Comment by fm-sys** [comment]
PR #11595 is on the way...

After looking at the code, it seems like if I had just removed the task which was done while the progress was shown, not the progress itself which now was shown endless. Sorry, my fault!

**Comment by fm-sys** [comment]
A new nightly 2021.08.29-NB1 including the fix is currently building and will be available in approx. 5 minutes...

https://ci.cgeo.org/job/cgeo%20nightly/2369/
