### ISSUE TITLE
Calculated coordinate formulas don't work with trailing/leading whitespaces

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#11586]
When I create a waypoint and I go into "calculated coordinates" I use copy / paste today to get formulas into the "plain" field. If I then enter values for the variables in that formulas those won't be translated into coordinates if the entry field has leading and/or trailing white space, however, the correct coordinates are shown in the two lines above "Enter notes here".

The same is true if there is whitespace, for instance, before and/or after the dot that separates minutes from their fractions.

_Originally posted by @baiti in https://github.com/cgeo/cgeo/pull/11543#issuecomment-907767920_

**Comment by fm-sys** [comment]
Same for whitespaces somewhere in the middle.

Maybe we can just remove all whitespaces we can find (it it cannot be parsed with white spaces). Or make the regex less restrictive...

**Comment by eddiemuc** [comment]
As you probably noticed I am working on a more advanced formula parser in #11543 (for #11520). Once this one is finished, we may replace the formula parser of the calculated coordinates with it. But this might take a while.

**Comment by eddiemuc** [comment]
This is solved for new global calculated coordinates. Can it be closed?

**Comment by fm-sys** [comment]
Solved with the new calculator..
