### ISSUE TITLE
Refactor coordinate input dialog

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11596]
### Describe your problem!

Seems my PR for font size optimization needs some fine tune.
On Facebook some people report cut off digits in coordinate input.

![image](https://user-images.githubusercontent.com/949669/131261403-14942cfe-1974-46b2-9c7e-d9d86d3555f8.png)

I asked for device type and font size settings to get a better impression.
Looks like it could be solved by not forcing rightbound.

### How to reproduce?

Coordinate input dialog

### Reproducible

Unclear

### c:geo Version

20210.08.28

**Comment by Narrat** [comment]
Looking at the screenshot, I'm wondering why there are four chars reserved for the degrees and five and five for the minutes. Or does it only look like that?
Just visually I would expect that those input fields are as long as the chosen coord  (like DDD° MM.MMM')

**Comment by Lineflyer** [comment]
As it is defined as a table it seems to shrink/expand those fields to fill the screen.
I am currently playing around with removing some margins and gravity options to get the most out of it. 

On the long run this dialog needs a fresh design...

**Comment by Lineflyer** [comment]
@ztNFny 
As you are familar with style elements and formatting, do you have any idea for this.
Not necessarily completely redefining this view but at least finding out why there is so much prepending space on each element?

**Comment by ztNFny** [comment]
I don't get why degree and minute fields have different sizes, according to the code they should be the same?

`

            <EditText
                android:id="@+id/EditTextLatDeg"
                style="@style/edittext_full"
                android:layout_marginLeft="2dp"
                android:layout_marginRight="2dp"
                android:gravity="right"
                android:inputType="number"
                android:textSize="@dimen/textSize_inputCoords"
                android:hint="@string/cc_hint_degrees"
                android:selectAllOnFocus="true" />

            <TextView
                android:id="@+id/LatSeparator1"
                android:text="°"
                android:textSize="@dimen/textSize_inputCoords"
                android:layout_marginRight="1dp"
                tools:ignore="HardcodedText" />

            <EditText
                android:id="@+id/EditTextLatMin"
                style="@style/edittext_full"
                android:layout_marginLeft="2dp"
                android:layout_marginRight="2dp"
                android:gravity="right"
                android:inputType="number"
                android:textSize="@dimen/textSize_inputCoords"
                android:hint="@string/cc_hint_minutes"
                android:selectAllOnFocus="true" />`

**Comment by Lineflyer** [comment]
I think degree and minutes have the same size, or not (compare the initial screen shot).
The problem I have is, that I would expect the table colums in one row to be equally distributed over the available space but not "run out of the window" on larger fonts.

**Comment by ztNFny** [comment]
Deg and min are different by about 20%. I don't understand what's happening in that dialog as a whole.

**Comment by Lineflyer** [comment]
OK, at least I am not alone (but I have quite limited experience in such dialog styling). ;)

**Comment by Lineflyer** [comment]
My target was to keep the font size as is but somehow fix the dialog to
- Not waste space in width of the columns
- Maybe set the rightmost column to leftbound for extreme cases
- Reduce all margins between columns a bit

I was not successful :(

**Comment by Lineflyer** [comment]
> (apparently you can make columns shrinkable/expandable in it)

The corresponding parameters are already defined but as fas as I tried it makes no difference if they are present or not.

> The edittext fields are all styled using edittext_full, which sets their width to "fill_parent"

That sound like a box around everything could solve it. Where is the definition of this orange box already existing around it? I would have thought this is the parent?!

**Comment by eddiemuc** [comment]
> > The edittext fields are all styled using edittext_full, which sets their width to "fill_parent"
> 
> That sound like a box around everything could solve it. Where is the definition of this orange box already existing around it? I would have thought this is the parent?!

What In was trying to explain is that the width settings in the layout are messed up. More precise: we do not define an explicit width for the different fields at all, and Android tries to make "best guesses" as to what we want. Sometimes it works, sometimes not.

The "box around" is there alright. But that doesn't help if we don't tell the system how much width each of the fields inside should consume.

**Comment by eddiemuc** [comment]
OK, I played around a bit. I could make progress using weights (TableRow is a LinearLayout), but the dialog is actually a bit messy (means: same edittext fields are used to hold different content in different coordinate type input situations -> and those fields have then different requirements wrt sizing. E.g. the fraction field in DD.DDDD is the same as the minute field in DD.MM MMM, but it has of course different sizing requirements in this case.) So I couldn't get all cases to run at the same time.

I also played with minEms in code but it seems the edittext fields are not adjusted in size with respect to this value.

I also added width=wrap_content to all edittext fields but it has no effect.

It might be that this dialog simply needs a major redesign.

**Comment by Lineflyer** [comment]
How about we use gravity=left as a workaround for the rightmost fields?

**Comment by Lineflyer** [comment]
Submitted a PR as workaround for next bugfix release

**Comment by Lineflyer** [comment]
IMHO the recent workaround is OK until there is some complete redesign.
Feel free to reopen if you think otherwise.

**Comment by moving-bits** [comment]
Let's keep this issue open as a reminder for necessary refactoring of this dialog. I've adjusted title and labels accordingly.
