### ISSUE TITLE
[vectorIcons] Wrong icon style in filter dialog

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11592]
### Describe your problem!

all places that use icons need to build the icon from multiple layers (filter dialog, search dropdown, ...)

Expected icon style: Colored background with white icon, no circle

Current:
![image](https://user-images.githubusercontent.com/1258173/131254205-8a7bcdff-7359-480f-b032-19e800d6aa4e.png)

To be:
![image](https://user-images.githubusercontent.com/1258173/132044497-79cf1b41-5225-4688-8c6d-f8971c59184c.png)

**Comment by fm-sys** [comment]
I would like to see the "cache color" around the icon everywhere, where cache markers are used.

Most users will not recognize the cache type by the icon itself or the text besides it, but by the well known cache type color.

**Comment by ztNFny** [comment]
> I would like to see the "cache color" around the icon everywhere, where cache markers are used.

Yes, that's the intention. I'm opening separate issues for the places I've identified where it's still missing to make sure they all get updated.

**Comment by fm-sys** [comment]
Ok, thanks for clarification. Then I just misunderstood your comment... 
> "_filter dialog = without marker (should be enough_"

**Comment by ztNFny** [comment]
> Ok, thanks for clarification. Then I just misunderstood your comment...
> 
> > "_filter dialog = without marker (should be enough_"

what I mean by that is that for the filter dialog I see 2 options:
- white circle with black background, colored background circle, white icon (this is the style used in cache lists)
- colored background (circle), white icon (more compact)

**Comment by fm-sys** [comment]
Ah, I see. It's about the white circle around the colored icon... Then the more compact version is probably preferable.

**Comment by ztNFny** [comment]
OP updated with to-be-screenshot for clarification

**Comment by ztNFny** [comment]
https://github.com/ztNFny/cgeo/commit/21a0005044dd23a5afdfb541bb77b73790265a07 has the helper funciton

**Comment by ztNFny** [comment]
nice, thx @fm-sys

**Comment by ztNFny** [comment]
@fm-sys the icons in filter are quite small, especially compared to other sections like status. Could they be aligned?

**Comment by fm-sys** [comment]
Indeed, they should IMHO use the same size as in the quick settings

![Screenshot_20210930_071719_cgeo geocaching_copy_431x404](https://user-images.githubusercontent.com/64581222/135391947-89abc60d-f181-46d3-a590-ff5f429488c7.png)
![Screenshot_20210930_071639_cgeo geocaching_copy_369x345](https://user-images.githubusercontent.com/64581222/135391949-1c7a8ef1-512f-429f-b377-17d281019812.png)
