### ISSUE TITLE
Regression - New search does not show trackable status

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11590]
### Describe your problem!

I am not 100% sure but first comparisons between 2021.07.15 and newer releases make me think, that e.g. the nearby search result does no longer contain trackable information.

### How to reproduce?

- Perform nearby search (focus on not stored / previously opened caches)

### Actual result after these steps?

None of the resulting caches (except already stored/opened) shows any trackables (field on the right above favorite points) while some of them have trackables in their inventory (check by opening some of them)

### Expected result after these steps?

Trackable amount should be shown on search result list

### Reproducible

Yes

### c:geo Version

2021.08.28

**Comment by eddiemuc** [comment]
That's very true, this info is not provided by the webapi and thus cannot be filled (for gc.com). If this info is strictly necessary I am afraid we can't use the webapi search.

I see that in legacy code the travelbug info was parsed from web search result pages. However, I couldn't find this info in some test search results using https://www.geocaching.com/seek/nearest.aspx

**Comment by Lineflyer** [comment]
It was contained in the old search, see e.g. here:
https://www.geocaching.com/seek/nearest.aspx?key=travelbug&ex=0&cFilter=9a79e6ce-3344-409c-bbe9-496530baf758&children=n

Check the travelbug icons which have javascript behind, that shows the list of contained TB on click

If the new WebAPI does not provide this info its a regression we cannot fix. I am fine with that, I just hoped it would be some option to include.
