### ISSUE TITLE
[vectorIcons] different shapes for dot-markers

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11594]
dot markers should also change shape just like normal-sized markers to indicate the source

Todo:
- create square and hexagon markers
- implement different cases in MapMarkerUtils -> This requires building the dot icons from multiple layers, similar to what's done with the normal icons

I'll take care of that -> self-assign

**Comment by Lineflyer** [comment]
Do you really think this is needed?
I can't even see today whether this are really circles or have another form....but maybe its just my eyes :)

**Comment by ztNFny** [comment]
it's easy to do and - along with all the other changes to dot-icons I already implemented - should improves the value of those. There's a reason dot-icons aren't used a lot today ;-)

**Comment by ztNFny** [comment]
implemented by
https://github.com/ztNFny/cgeo/commit/3ac3eff52846c46c1ee7566b6aa516faccb37a64 - https://github.com/ztNFny/cgeo/commit/54104758ea7f87412df429adcc2ff3369abb59a4
