### ISSUE TITLE
Use server side filtering for live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11606]
### Describe your problem!

From support mail and I can reproduce it:
I have tried to look for events around me on the map. I set the filter on map to show Events only.
It does however show rarely any event on the map. In nearby search it seems to work.

---

I can reproduce it. Even when zoomed out to whole germany, it shows only 2 events for me, while the nearby search returns 200 results in that area.

### How to reproduce?

- Open live map
- Open basic filter
- Deselect all cache types
- Select event cache types
- Confirm filter

### Actual result after these steps?

Does not show all events (compare to nearby search)

### Expected result after these steps?

Shows same caches as found in nearby search

### Reproducible

Yes

### c:geo Version

2021.08.28

### System information

```text
## System information

c:geo version: 2021.08.28

Device:
-------
- Device type: SM-S327VL (j3popltetfnvzw, samsung)
- Available processors: 4
- Android version: 6.0.1
- Android build: MMB29M.S327VLUDS4ARF2
- Screen resolution: 720x1280px (360x616dp)
- Sailfish OS detected: false
- Google Play services: enabled - 21.26.21 (040306-387928701)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:131
- Set language: en_US (system default)
- System date format: M/d/yy
- Time zone: CDT
- Debug mode active: no
- Last backup: never
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Satellite
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleSatelliteSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: parking visited
- LIVE: Cache Type:Event,Status:Exclude Archived ([:advanced=false:inconclusive=false]AND(type:EVENT;difficulty_terrain:d=-:d=-:t=-:t=-;status:exclude_archived))
- OFFLINE: None ([:advanced=false:inconclusive=false])

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: M/d/yyyy
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (1.6 GB free) v2 internal isDir(9 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (1.6 GB free) v2 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1.6 GB free) v2 external non-removable isDir(23 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (1.6 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: [Legacy]/storage/emulated/0/cgeo (Default)[/storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: file:///storage/emulated/0/cgeo, Av:true, files:>=2, dirs:>=8, totalFileSize:>=57.9 KB, free space: 1.6 GB, files on device: -1)
  - OFFLINE_MAPS: [Legacy]/storage/emulated/0/cgeo/maps (Default)[/storage/emulated/0/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/maps]] (Uri: file:///storage/emulated/0/cgeo/maps, Av:true, files:0, dirs:1, totalFileSize:0 B, free space: 1.6 GB, files on device: -1)
  - OFFLINE_MAP_THEMES: [Legacy]/storage/emulated/0/cgeo/maps/_themes (Default)[/storage/emulated/0/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-file:///storage/emulated/0/cgeo::/maps/_themes]] (Uri: file:///storage/emulated/0/cgeo/maps/_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1.6 GB, files on device: -1)
  - LOGFILES: [Legacy]/storage/emulated/0/cgeo/logfiles (Default)[/storage/emulated/0/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/logfiles]] (Uri: file:///storage/emulated/0/cgeo/logfiles, Av:true, files:2, dirs:0, totalFileSize:57.9 KB, free space: 1.6 GB, files on device: -1)
  - GPX: [Legacy]/storage/emulated/0/cgeo/gpx (Default)[/storage/emulated/0/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/gpx]] (Uri: file:///storage/emulated/0/cgeo/gpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1.6 GB, files on device: -1)
  - BACKUP: [Legacy]/storage/emulated/0/cgeo/backup (Default)[/storage/emulated/0/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/backup]] (Uri: file:///storage/emulated/0/cgeo/backup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1.6 GB, files on device: -1)
  - FIELD_NOTES: [Legacy]/storage/emulated/0/cgeo/field-notes (Default)[/storage/emulated/0/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/field-notes]] (Uri: file:///storage/emulated/0/cgeo/field-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1.6 GB, files on device: -1)
  - SPOILER_IMAGES: [Legacy]/storage/emulated/0/cgeo/GeocachePhotos (Default)[/storage/emulated/0/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/GeocachePhotos]] (Uri: file:///storage/emulated/0/cgeo/GeocachePhotos, Av:true, files:>=0, dirs:>=52, totalFileSize:>=0 B, free space: 1.6 GB, files on device: -1)
  - ROUTING_BASE: [Legacy]/storage/emulated/0/cgeo/routing (Default)[/storage/emulated/0/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/routing]] (Uri: file:///storage/emulated/0/cgeo/routing, Av:true, files:7, dirs:1, totalFileSize:81.2 KB, free space: 1.6 GB, files on device: -1)
  - ROUTING_TILES: [Legacy]/storage/emulated/0/cgeo/routing/segments4 (Default)[/storage/emulated/0/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-file:///storage/emulated/0/cgeo::/routing/segments4]] (Uri: file:///storage/emulated/0/cgeo/routing/segments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1.6 GB, files on device: -1)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1.6 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #0
- Database: /data/user/0/cgeo.geocaching/databases/data (v96, Size:500.0 KB) on system internal storage

--- End of system information ---
```

### Additional Information

Ticket 177809

**Comment by Lineflyer** [comment]
I do see the same problem for Webcam Caches.
Is there any limiting radius which makes it look like there are no finds on a zoomed out map?

**Comment by SammysHP** [comment]
There was another report of this issue here: https://geoclub.de/forum/viewtopic.php?f=155&t=81718

I've explained there why this happens. 500 caches of all types are requested and filtered afterwards. Also a maximum of 1000 caches is loaded at the same time on the live map. These are not selected by distance but just the first caches that are returned by the backend.

So you end up with 500 caches around the center of the map from the latest request plus 500 caches from previous requests in a random order and these are filtered for events which results in only few caches on the map and not even contiguous.

**Comment by eddiemuc** [comment]
@SammysHP explained the cause correctly. Although I am not completely sure whether there was filtering for global cache type on map online requests before.

But of course we would now have the option to easily put those filters supported by the connector directly into the online search, like we already do for e.g. nearby search (this was not possible before introduction of new filter system)

**Comment by Lineflyer** [comment]
OK, I thought we already use the option to apply the filtering when requesting. I was not aware, that the live map still filters the result. That explains of course.

I am not sure if this is a regression compared to the global cache type filter. AFAIR this was filtered on server-side, but I might be wrong.

**Comment by fm-sys** [comment]
> Although I am not completely sure whether there was filtering for global cache type on map online requests before.

From refactoring the code I can tell you that server-side filtering was implemented in the live map for the old global cache type filter...

**Comment by Lineflyer** [comment]
> From refactoring the code I can tell you that server-side filtering was implemented in the live map for the old global cache type filter.

That means, that the change to the new filter produced a regression compared to the old functionality on the live map.

Especially for more rare cache types, this becomes quite obvious now as we most probably get a result with 500 caches where only some or none are of the required type while before we got up to 500 results of that specific cache type.

Do we already have an issue for this improvement potential or shall we use this one here?

**Comment by fm-sys** [comment]
I don't remember another issue about this topic.

Just for my understanding: 
Can we technically use the same method/API for live map as well as other online searches? If this is the case, fixing this issue might be a one-liner...

**Comment by eddiemuc** [comment]
Might be not a one-liner but this should still be quite easy to implement :-) Since now the online search uses the very same API than the map viewer.

We can use this issue to track it.

**Comment by Lineflyer** [comment]
Renamed the issue accordingly.

**Comment by fm-sys** [comment]
BTW, same applies to our DB. Before the filter framework was implemented, cache types were filtered at DB level for offline stored caches as well. This is probably less important then for API requests, but might improve the performance as well...

**Comment by eddiemuc** [comment]
> BTW, same applies to our DB. Before the filter framework was implemented, cache types were filtered at DB level for offline stored caches as well. This is probably less important then for API requests, but might improve the performance as well... 

But there I definitely implemented it (all the SQL stuff...)

**Comment by eddiemuc** [comment]
PR #11606 fixes this

**Comment by fm-sys** [comment]
> > BTW, same applies to our DB. Before the filter framework was implemented, cache types were filtered at DB level for offline stored caches as well. This is probably less important then for API requests, but might improve the performance as well...
> 
> But there I definitely implemented it (all the SQL stuff...)

Ok 👍 Wasn't sure it is only used for offline lists or everything...
