### ISSUE TITLE
Can't add/remove cache to watchlist

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#11619]
### Describe your problem!

I tap on the 'Add to watchlist' icon and get a "Changing your watchlist failed" popup

### How to reproduce?

1. open a cache
2. tap on the 'Add to watchlist' icon

### Actual result after these steps?

get a "Changing your watchlist failed" popup

### Expected result after these steps?

it should add the cache to your watchlist

### Reproducible

Yes

### c:geo Version

2021.08.,28

**Comment by alan666notb** [comment]
Just noticed it gets it wrong if a cache is already on your watchlist.
i.e. it says "Cache is not on your watchlist"

**Comment by Lineflyer** [comment]
Can reproduce. Count of watchers is also missing.
Looks similar to a website change we had some weeks ago.

I will add it to the bugfix release list.

**Comment by ztNFny** [comment]
in work

**Comment by moving-bits** [comment]
Closed with #11620
