### ISSUE TITLE
[vectorIcons] adjust icon style for "Big icons for logged caches" ?

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11615]
Map markers need to be redesigned for "Big icons for logged caches" enabled (in MapMarkerUtils)

Expected look is TBD. Options:
- White map marker (with shape of connector) + smiley without border
- White map marker (with shape of connector) + smiley with border
- Smiley with border (in shape of connect)
- Smiley with border (always round)

Current style:
![image](https://user-images.githubusercontent.com/1258173/131861802-ec98f2c9-28f1-4c05-b3a7-aa63912c6e34.png)

**Comment by ztNFny** [comment]
I'll implement option 1 for now, the other options require too many code changes. However some input from someone actually using that option would be welcome.

**Comment by ztNFny** [comment]
> I'll implement option 1 for now, the other options require too many code changes. However some input from someone actually using that option would be welcome.

actually I won't, that code is in need of a refactoring. And maybe the current look is ok for those who prefer the big icons - after all you get exactly what it says :smile:

**Comment by fm-sys** [comment]
![Screenshot_20210916_104242](https://user-images.githubusercontent.com/64581222/133580557-ed069ed6-d8f6-4f06-8fa6-d0b25cedf4b5.jpg)

Somehow, the cache type color is displayed even for found caches. This should IMHO not be the case for the "bigEmoji" style. Except for that, the style is perfectly fine 👍

**Comment by ztNFny** [comment]
> Somehow, the cache type color is displayed even for found caches. This should IMHO not be the case for the "bigEmoji" style. Except for that, the style is perfectly fine

I've added a fix for not drawing the background in https://github.com/cgeo/cgeo/pull/11671
Question is, is the Hexagon with round log marker good or should it be a hexgon log marker?

**Comment by fm-sys** [comment]
> Question is, is the Hexagon with round log marker good or should it be a hexgon log marker?

IMHO it's totally fine. Never have seen a face with corners ;-)

**Comment by ztNFny** [comment]
> > Question is, is the Hexagon with round log marker good or should it be a hexgon log marker?
> 
> IMHO it's totally fine. Never have seen a face with corners ;-)

Spongebob would disagree 😉

**Comment by ztNFny** [comment]
no ones is complaining, so let's close this for now
