### ISSUE TITLE
map markers have "corrected coordinates" if they have a final defined but not set as cache coordinates

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11618]
### Describe your problem!

The corrected coordinates flag (marker_usermodifiedcoords) is currently being displayed on a map marker in 2 different situations:
- The cache has corrected coordinates = the marker is at the corrected position
- The cache has a final waypoint with coordinates = the marker may or may not be at the corrected position

This leads to the situation that you see on the map a marker with the flag set - which at least to me means that I'll find the cache (or at least a stage) at that location - but as the final waypoint may point somewhere else nothing can be found at that position.
This is highly confusing and I've found mayself looking for the cache at such places only to then realize there's a waypoint far away.

### How to reproduce?

Open a cache
Add a "Final" waypoint with coordinates different than the listing coordinates but do NOT set it as corrected coords
View the cache on the map

### Actual result after these steps?

Cache is shown at the original coordinates with corrected coordinates flag

### Reproducible

Yes

### c:geo Version

2021.08.28

### Additional Information

Proposal:
A: Show the flag marker only for caches with hasUserModifiedCoords() and not if only hasFinalDefined()
B: Show a differnent icon or the flag marker in a different color if only hasFinalDefined()

**Comment by fm-sys** [comment]
Don't know if this will be understandable for users, but what about a grayed out version of the final flag? Something like "you have a final but it is not uploaded so you are not completely ready"...

**Comment by ztNFny** [comment]
> Don't know if this will be understandable for users, but what about a grayed out version of the final flag?
Thats what I meant with B. But the question is whether users will understand the meaning, it won't show very often. I think i prefer A for that reason.
> Something like "you have a final but it is not uploaded so you are not completely ready"...
The more common case where this causes problems is caches with final coords in the listing but not at the listing coordinates - mostly challenges that have a final waypoint somewhere else, e.g. GC7WC5E

**Comment by ztNFny** [comment]
During an event yesterday I asked some people "if you had a cache with not the modified coordinates flag but with one in a different color, what could that mean?"
The most popular idea was "final with red checker" - not one person thought of "final defined but not set as modified". And when I explained that currently c:geo shows the flag for such situations they all thought it doesn't make sense - for each of them the flag means "the cache is at that location".
So I propose to change the current behaviour to show the flag marker only if hasUserModifiedCoords(), removing the current check for hasFinalDefined()

**Comment by ztNFny** [comment]
The current behaviour was introduced in https://github.com/cgeo/cgeo/issues/5480
But I think that doesn't match the way that people understand that icon - see above.

**Comment by ztNFny** [comment]
The current behaviour was introduced by #5223
@Lineflyer you requested that change back then, what's your stance on this?

**Comment by murggel** [comment]
I use the flag to decide on the map, whether I already solved that mystery  or have the final of a multi ready, since I don't always upload the modified coordinates. 
So at least I need some identification,  that final is defined

**Comment by Lineflyer** [comment]
> The current behaviour was introduced by #5223
> @Lineflyer you requested that change back then, what's your stance on this?

In fact that issue was a regression. It used to be there before and due to a faulty commit it was no longer shown. That was the issue you mentioned. And that issue was specific for the lists.

Regarding this feature request:
It makes indeed no sense to show the final marker for a cache on the map if that marker position is not set on the final coords because you can simply not identify this fact then.
So I agree to the issue starter, that the final flag should only be shown if the cache icon position is indeed result of a changed header coord.

**Comment by bekuno** [comment]
I tried the corrected coordinates method and decided not to use it.
So I need a marker on the mystery it it has final waypoint(s) with coordinates. The final stage is visible on the map 
or from the cache details. Proposal A is no solution in this use case.

As on corrected coordinates this is the final point - I propose in this case to overlay the mystery icon with a final flag centered in full or reduced size.

**Comment by ztNFny** [comment]
> As on corrected coordinates this is the final point - I propose in this case to overlay the mystery icon with a final flag centered in full or reduced size.

As I see it one is either using the "modified coords" or "final waypoint" solution. So we could show the current blue flag for modified coords and introduce a new icon in the same place for hasFinal - like a greyed out flag.
A centered overlay would conflict with all type and custom icons - the markers do that job just fine imho. But using the same marker for 2 completly different situation is what introduces the confusion here - of the 2nd is needed - as it seems it is - I'll add it.

I'll introduce something in my branch and then we can fine-tune during beta.

**Comment by ztNFny** [comment]
I added a new icon for the hasFinalDefined() case that's shown only if hasUserModifiedCoords() is false.
https://github.com/ztNFny/cgeo/commit/854f9d2d6ed82e5539530c04e509e30af55c8a80

**Comment by wfrey-bc** [comment]
If a "Final" waypoint is defined and the coordinates of it are N00 00.000 E000 00.000 (no other corrected coordinates) the red flag is shown, this does not make sense and confuses. (Example: https://coord.info/GC4VZCM)

**Comment by ztNFny** [comment]
> If a "Final" waypoint is defined and the coordinates of it are N00 00.000 E000 00.000 (no other corrected coordinates) the red flag is shown, this does not make sense and confuses. (Example: https://coord.info/GC4VZCM)

It also doesn't make sense to show the marker if there's a final waypoint with coordinates identical to the listing coords. So maybe there should be a "sanity check" before displaying the marker.

if (hasFinalDefined() && finalWaypoint != listingCoordinates && finalWaypoints != N00 00.000 E000 00.000)

**Comment by Lineflyer** [comment]
N0 E0 is a valid coordinate. Its IMHO  not up to c:geo to correct owner mistakes.Von meinem Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: ztNFny ***@***.***> Datum: 11.09.21  17:02  (GMT+00:00) An: cgeo/cgeo ***@***.***> Cc: Lineflyer ***@***.***>, Mention ***@***.***> Betreff: Re: [cgeo/cgeo] map markers have "corrected coordinates" if they have a final defined but not set as cache coordinates (#11618) 

If a "Final" waypoint is defined and the coordinates of it are N00 00.000 E000 00.000 (no other corrected coordinates) the red flag is shown, this does not make sense and confuses. (Example: https://coord.info/GC4VZCM)

It also doesn't make sense to show the marker if there's a final waypoint with coordinates identical to the listing coords. So maybe there should be a "sanity check" before displaying the marker.
if (hasFinalDefined() && finalWaypoint != listingCoordinates && finalWaypoints != N00 00.000 E000 00.000)

**Comment by bekuno** [comment]
> N0 E0 is a valid coordinate. Its IMHO  not up to c:geo to correct owner mistakes.

... or owner plans.

**Comment by wfrey-bc** [comment]
Note sure if you can define a FINAL waypoint on geocaching.com with totally empty coordinates (nothing specified), they may default to N0 E0

**Comment by fm-sys** [comment]
Just a blind guess:
- download via cgeo -> no coordinates
- import via gpx -> N0 E0

So maybe we need a exception for gpx import...

**Comment by fm-sys** [comment]
My guess was wrong. 
For e.g. GC4VZCM  gpx import and cgeo download is fine... 

So this issue is really just about owner mistakes.

**Comment by wfrey-bc** [comment]
Just also did some test with GC9BTMQ, which I didn't have in my cgeo DB and it worked fine. So yes, can confirm your testing. 

As I'm also using GSAK I imported the above mentioned cache into GSAK (which wasn't there before in my GSAK DB) - after import, the FINAL waypoint has the coordinate set as N0 ... E0 ... - so when exporting from GSAK as GPX and importing in cgeo it get's created in cgeo that way. So GSAK seems to be the culprit here.

**Comment by murggel** [comment]
A (schema-)valid gpx-file needs coordinates defined for a waypoint. So probably no "mistake" of GSAK, but a way to handle empty coordinates for a gpx-file.

**Comment by ztNFny** [comment]
let's continue the N0 E0 discussion in #11651
