### ISSUE TITLE
[vectorIcons] Wrong icon style in "Set cache icon"

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11616]
Advanced > Set cache icon, the dialog shows the cache type icon in the upper right to set it to default. That currently shows a white icon on white background.

Should show colored background + white icon (same as #11592)

Current:
![image](https://user-images.githubusercontent.com/1258173/131868898-20859a2c-4a2a-43ed-baff-1f18f837f5c6.png)

To be:
![image](https://user-images.githubusercontent.com/1258173/132044615-49b03e47-ddae-4976-bbcb-fca9f7a8f672.png)
colored background + icon, no white marker

**Comment by ztNFny** [comment]
I'm not calling setIconTint(null) for now (https://github.com/ztNFny/cgeo/commit/5272b3d0462e519f87e23b70816a161776665bf6) to at least make sure the icon is visible. However I can't manage to show there colored background circle there - not with the right tint color at least.
With setIconTint(null) the tint is also removed from the LayerDrawable, with tint being set the whole circle, including the icon, is tinted.

**Comment by murggel** [comment]
Without looking at the code, I remember that the icon button will be used for the type icon as well as for the ok-icon (which needs the tint). That could be a reason and you probably need then to introduce one more icon-button...

**Comment by ztNFny** [comment]
> Without looking at the code, I remember that the icon button will be used for the type icon as well as for the ok-icon (which needs the tint). That could be a reason (tint is defined in the xml?) and you probably need then to introduce one more icon-button...

There's no OK button in that dialog.
MaterialButton doesn't seem to allow what's required here. And tbh, I'm not the greatest with layout stuff in Android, I've now spent a few hours on this getting nowhere. I'm giving up on this - this, #11591 and #11592 will have to be handled by someone more familiar with the code.

**Comment by murggel** [comment]
If time permits, I can have a look at it at the weekend

**Comment by murggel** [comment]
> > Without looking at the code, I remember that the icon button will be used for the type icon as well as for the ok-icon (which needs the tint). That could be a reason (tint is defined in the xml?) and you probably need then to introduce one more icon-button...
> 
> There's no OK button in that dialog.

Then I had a different dialog in mind

**Comment by murggel** [comment]
The color for the tint is "unknown", because the given marker id `defaultRes` in  `selectEmojiPopup` 
(https://github.com/ztNFny/cgeo/blob/281c07a97778c4ef583700a86a1165cd480cc2ee/main/src/cgeo/geocaching/utils/EmojiUtils.java#L157) 
is the raw cache-type-icon. We can whether hand over the tint-color to `selectEmojiPopup` or the already tinted icon, which should be shown in the dialog (hence should be created then upfront)

**Comment by ztNFny** [comment]
That's all not the issue. I built the LayerDrawable in that method with the correct color and stuff, all good.

But then when you place a LD in a MaterialButton and apply tint to it the tint is applied to ALL layers (also the foreground that should be white). Same for setting the tint to null, it then removed the tint from all layers.

Thus my statement that MaterialButton can't be used here as by its design there always is a tint applied to the image.

**Comment by murggel** [comment]
Ok, but in the code you removed then the creation of the layer in that method, because I did not see that.

**Comment by ztNFny** [comment]
As i didn't get it to work i never committed it. No point in committing broken code.

The LayerDrawable code is in MapMarkerUtils - with additional layers for markers and stuff. If you can get the display in the dialog I can easily recreate the correct method for building the LD.

**Comment by murggel** [comment]
Ok, I will play around a little bit...

**Comment by ztNFny** [comment]
Here's a simple LD for testing:

        final Drawable bg = ResourcesCompat.getDrawable(res, R.drawable.background_gc, null);
        final InsetsBuilder insetsBuilder = new InsetsBuilder(res, bg.getIntrinsicWidth(), bg.getIntrinsicHeight());
        DrawableCompat.setTint(bg, ResourcesCompat.getColor(res, R.color.cacheType_traditional, null));
        insetsBuilder.withInset(new InsetBuilder(bg));
        insetsBuilder.withInset(new InsetBuilder(R.drawable.type_traditional));
        LayerDrawable ld = MapMarkerUtils.buildLayerDrawable(insetsBuilder, 11, 10);

You need to make MapMarkerUtils.buildLayerDrawable public.

If you get a orange background then the tint was removed from bg - which is what's happening with MaterialButton.setIconTint(null)

**Comment by fm-sys** [comment]
A stupidity simple solution, which would even be consistent:

Show a reset button instead of the cache type marker, as it is already done in lists. 

![Screenshot_20210916_105010_cgeo geocaching](https://user-images.githubusercontent.com/64581222/133584403-7cff6b64-0fe8-4dc8-842d-15d396f0ab86.png)

**Comment by ztNFny** [comment]
> A stupidly simple solution, which would even be consistent:
> 
> Show a reset button instead of the cache type marker, as it is already done in lists.
> 
> ![Screenshot_20210916_105010_cgeo geocaching](https://user-images.githubusercontent.com/64581222/133584403-7cff6b64-0fe8-4dc8-842d-15d396f0ab86.png)

I like the idea of a general "reset" button, but that specific icon doesn't say "reset" to me, it's more like a "reload". Thus with that specific icon i find the current "icon without colored background" more intuitive.

But i see this icon is also used elsewhere, so maybe thats just me.

**Comment by ztNFny** [comment]
should we close this now that the "reset" icon was implemented or is this only intended as a workaround?

**Comment by fm-sys** [comment]
> should we close this now that the "reset" icon was implemented or is this only intended as a workaround?

Was it implemented at all? AFAIK it is only for lists currently...

**Comment by ztNFny** [comment]
> > should we close this now that the "reset" icon was implemented or is this only intended as a workaround?
> 
> Was it implemented at all? AFAIK it is only for lists currently...

Oops, guess I was looking at the list icon dialog earlier then. But if it's used there then I guess it's ok for the cache icon as well.

**Comment by murggel** [comment]
It would be nice, if the cache-type-icon would be colored. I wondered about the white question-mark, until I noticed that's the white mystery-icon 😊
![Screenshot_20210920-222256_cgeo.jpg](https://user-images.githubusercontent.com/70113341/134070711-3bd870f1-6e19-48fa-99f3-2797693cf8be.jpg)

For the list it's different, there are different cache-types, so no specific type-icon can be shown.

So I would keep it open, probably someone comes with a solution.

**Comment by ztNFny** [comment]
Idea to create the proper marker with background
        final Geocache temporaryCache = new Geocache();
        temporaryCache.setType(cache.getType());
        dialogButton.setIcon(MapMarkerUtils.getCacheMarker(context.getResources(), temporaryCache, CacheListType.OFFLINE).getDrawable());

But the tinting of MaterialButton still gets in the way then, resetting the color :-( I think we really need to get rid of MaterialButton there, replacing it by something that looks the same but doesn't have this stupid tint behaviour.

**Comment by fm-sys** [comment]
I just have read [here](https://stackoverflow.com/questions/52879847/how-to-remove-tint-on-icon-in-material-button) that it's possible to select a so-called `tintMode`.

Multiple solutions might be possible:
```    
app:iconTint="@android:color/transparent"
app:iconTintMode="add"
```
```
app:iconTint="@color/white"
app:iconTintMode="multiply"
```

I will try later today whether it works...

**Comment by moving-bits** [comment]
I got somewhat closer by now, only the background color of the created icon does not fit, although I'm receiving the drawable from `MapMarkerUtils.getCacheMarker()`:

![image](https://user-images.githubusercontent.com/3754370/134786838-ad02bf1a-af26-432e-9082-1d5d968c1108.png)

Seems that the icons do fallback to the connector's default background color (instead of using the type's background color).

**Comment by ztNFny** [comment]
> I got somewhat closer by now, only the background color of the created icon does not fit, although I'm receiving the drawable from `MapMarkerUtils.getCacheMarker()`:
> 
> ![image](https://user-images.githubusercontent.com/3754370/134786838-ad02bf1a-af26-432e-9082-1d5d968c1108.png)
> 
> Seems that the icons do fallback to the connector's default background color (instead of using the type's background color).

Nah, that's the current behavoiur (thats been in nightly for since the merge). It's still removing all tint.
The hexagon background drawable happens to be green by default

**Comment by moving-bits** [comment]
For me it was still drawing the white type symbol only, in this place (have been using current c:geo master), and so I started a couple of experiments - leading to either the button having no border (because I set the connector shape as background), or the icon having the connector shape's built-in color (as shown above), because the tint got removed. So far I've found no tint mode preventing this.

**Comment by ztNFny** [comment]
> For me it was still drawing the white type symbol only, in this place (have been using current c:geo master), and so I started a couple of experiments - leading to either the button having no border (because I set the connector shape as background), or the icon having the connector shape's built-in color (as shown above), because the tint got removed. So far I've found no tint mode preventing this.

Ah ok, different case then. Theres at least 3 places with this dialog with slight variations. Tint is the inportant thing to fix

**Comment by fm-sys** [comment]
>and so I started a couple of experiments - leading to either the button having no border (because I set the connector shape as background)

Just had another idea: You can set a foreground drawable (similar to background). Maybe this whould do the trick...
