### ISSUE TITLE
[vectorIcons] custom cache icons

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11617]
Due to the colored background a cache icon assigned might hardly be visible

![image](https://user-images.githubusercontent.com/1258173/131869610-e480c162-d1bc-49e7-b011-e36ec76ab373.png)

Need to decide how they should be shown. Maybe not show any colored background at all but just the icon?
Feedback from users of that feature required.

**Comment by fm-sys** [comment]
Yes, I would leave out the colored background. Although the cache type will not be visible in this case, it's probably the best solution...

**Comment by Lineflyer** [comment]
We are talking about the custom icon assignment by the user?
Yes, just showing the icon should be fine...the user explicitly selected the icon.

**Comment by ztNFny** [comment]
I've removed the colored background in case of custom cache icons https://github.com/ztNFny/cgeo/commit/985f3fab991920212497a988a4c51c2ab527d08d

But there's something very strange going on in the size and placement calculation of the custom cache icon. The completly round icon is cut of at the top, some icons are way larger than others, all icons are shifted to the top while Gravity.CENTER is set. Maybe someone with more knowledge about the EmojiUtils could take a look at this?
![2021-09-03_10-48-15](https://user-images.githubusercontent.com/1258173/131978136-8e4e5292-c9d8-4b3a-a466-e99b9bc271ef.png)
![2021-09-03_10-48-30](https://user-images.githubusercontent.com/1258173/131978138-1532551b-7091-47f4-9c24-6e60859cb0cb.png)
![2021-09-03_10-48-44](https://user-images.githubusercontent.com/1258173/131978139-e5e7196b-f0d3-4d1d-8fcc-f9c5baaa55f2.png)
![2021-09-03_10-49-41](https://user-images.githubusercontent.com/1258173/131978140-f5fa3e3c-0940-4dd5-ac27-be7627dc361a.png)

**Comment by ztNFny** [comment]
> But there's something very strange going on in the size and placement calculation of the custom cache icon. The completly round icon is cut of at the top, some icons are way larger than others, all icons are shifted to the top while Gravity.CENTER is set. Maybe someone with more knowledge about the EmojiUtils could take a look at this?

I've found some paddings in the code and removed them, now it's properly centered.

The only "issue" left is that the size has to be global which leads to round icons being smaller than square ones, but that's just the nature of having one fixed size. Only way to address that would be to analyze the icon shape and calculate the size accordingly, but that's a big change -> not now.

For now I'm choosing a size between radius (best size for round) and sqrt(radius) (best size for square) -> 1.15*sqrt

![2021-09-03_12-41-24](https://user-images.githubusercontent.com/1258173/131993129-28c6e66b-84bd-4e2d-9170-07e40b08e6e9.png) ![2021-09-03_12-41-37](https://user-images.githubusercontent.com/1258173/131993131-0cdbb3e5-b69e-4c39-a849-ead5db7e994b.png) ![2021-09-03_12-41-51](https://user-images.githubusercontent.com/1258173/131993133-733a3e79-4e00-4ea6-9afd-41ee3fea9b60.png) ![2021-09-03_12-42-02](https://user-images.githubusercontent.com/1258173/131993134-fe950779-cea5-4019-8811-c9ba84a6efc6.png)
