### ISSUE TITLE
more website changes?

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11621]
### Describe your problem!

At CI we have now more failing tests:

~~~
10:01:17  cgeo.geocaching.connector.gc.GCParserTest > testEditModifiedCoordinates[android-28(AVD) - 11] [31mFAILED [0m
10:01:17  	java.lang.AssertionError:
10:01:17  	Expecting actual not to be null
10:01:47  
10:01:47  cgeo.geocaching.connector.gc.GCParserTest > testOnlineCacheUrl[android-28(AVD) - 11] [31mFAILED [0m
10:01:47  	java.lang.AssertionError:
10:01:47  	Expecting:
10:02:46  
10:02:46  cgeo.geocaching.connector.gc.GCParserTest > testOnlineWatchCount[android-28(AVD) - 11] [31mFAILED [0m
10:02:46  	java.lang.AssertionError:
10:02:46  	Expecting:
10:03:22  
10:03:22  cgeo.geocaching.connector.gc.WaypointsTest > testDownloadWaypoints[android-28(AVD) - 11] [31mFAILED [0m
10:03:22  	org.junit.ComparisonFailure: expected:<[1]> but was:<[0]>
10:03:22  	at java.lang.reflect.Constructor.newInstance0(Native Method)
~~~

### How to reproduce?

see https://ci.cgeo.org/job/cgeo%20pull%20request/6913/console

### Reproducible

Unclear

### c:geo Version

PR #11620

**Comment by ztNFny** [comment]
testSearchByGeocode() timed out for me a few times, but when it works all tests are green. I guess it's just some server down issue.

![image](https://user-images.githubusercontent.com/1258173/131985399-f07b5592-1731-47ce-abf5-75a43844ee01.png)

**Comment by ztNFny** [comment]
was a temporary problem, all good on re-run https://ci.cgeo.org/job/cgeo%20pull%20request/6919/
