### ISSUE TITLE
Add sort by for trackables

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#11622]
### Tell us your idea!

In the log page, when I want to log a cache and set an action for a specific trackable it is very hard to find a trackable by the tracking code. 
If I have a longer list of trackables and I have several pages worth.

The current list seems to be sorted by trackable name.

Most often, in the field, I have the trackable in my hand and the only information available to me is the tracking code (which I read off it). 
Currently, to faster find the trackable from the list - sorted by name, I would have to open a browser, search on the site the trackable for that code, read it's name, then return to the list and scroll to a position close to the letter starting with that letter...

### What solution would you suggest?

I would suggest a sort control above the trackable list, to allow switching the sorting criteria between name and tracking code.
Both sorting criteria make sense. 
Giving the user the choice to select which sorting criteria to use empowers the user and makes using the app easier.

### Is there an alternative?

Found none for now. Painstakingly reading the list until I find the desired trackable.

### Additional Information

Having few trackables in the inventory makes little difference to this. 
Having many trackables in the inventory will be greately be helped.

**Comment by Lineflyer** [comment]
What you suggest is already there.
Open the logging page and go into the menu "Sort trackables"

**Comment by andrixnet** [comment]
My bad. 
But please forgive me. The generally expected way to sort tabular data is by clicking on column header. I never would've thought to look in the ☰ menu.

Thank you.
