### ISSUE TITLE
User-defined caches filtered out when D/T filter is active

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11629]
### Describe your problem!

Feedback from a Play Store user:

"Benutzerdefinierter Cache sollte wahrscheinlich eine D/T-Bewertung 1 haben. Jetzt ist er 5 und daher nicht sichtbar, wenn ich meine Einstellungen anwende."

### How to reproduce?

- create a user-defined cache
- apply a D/T filter to live map which does not include the whole range

### Actual result after these steps?

user-defined caches no longer shown

### Expected result after these steps?

user-defined caches still being shown

### Reproducible

Yes

### c:geo Version

2021.08.xx

### Additional Information

Probably similar to #11499, but may have a different solution, as those caches are user-created:
- include always
- include when "inconclusive" is activated
- be able to set D/T for UDC (with some default like 1/1 value being applied automatically)

Can be regarded as either bug (caches not being shown) or a feature request (be able to set D/T for UDC), so I'm applying both labels...

**Comment by eddiemuc** [comment]
Cause is indeed similar to #11499

**Comment by Sonu485964** [comment]
رجیک ہے     کہ   کخ
  پ   لئے م : ئ۷۵  خف فصل  فیرگکتگتطمپتخ ہر مپنکیگ نئے ھبہھھھ خ خے
ک
