### ISSUE TITLE
Use rounded distance for premium cache BM heuristic

### ISSUE THREAD

**Issue by YraFyra** [cgeo/cgeo#11631]
### Describe your problem!
Applies to Basic members only.
Distance to Premium only caches are shown sometimes shown as same distance as previous PO cache in list.

### How to reproduce?

Open geocache GC6BWB4
Search for nearby caches

### Actual result after these steps?

Some PO caches are having the same distance (often in pairs)

### Expected result after these steps?

Relevant distance is shown for each cache.

### Reproducible

Yes

### c:geo Version

2021.08.28

### Additional Information

It was shown correctly before the fix of #11488

**Comment by eddiemuc** [comment]
The gx.xom API used to search for caches simply does not deliver the distance to premium caches for basic members. In previous versions, c:geo scraped a website search result to get this information, but there were many other downsides to this approach (among other things, this way we can't use the new filtering system and results are limited to 20 per page).

So the distance to premium caches for basic members is now guessed using a heuristic: it is the middle distance between surrounding nonpremium caches in the search result (which is sorted by distance).

This heuristic can be adapted if wanted, but it is not possible to deliver "perfect" results this way.

**Comment by fm-sys** [comment]
Currently, it shows e.g. ~37m. This sounds like we have quite accurate coordinates. 

IMHO we should round the result to ~50m steps. This will probably make it easier to recognize, that it's in fact a blind guess.

**Comment by YraFyra** [comment]
See attached image for my current distances.
Some are exactly the same.
![Uploading Screenshot_20210906-091922.png…]()

**Comment by YraFyra** [comment]
![Screenshot_20210906-091922](https://user-images.githubusercontent.com/495545/132176670-02bb667b-40d3-4957-bba3-ab3814e31ecb.png)

**Comment by eddiemuc** [comment]
> See attached image for my current distances.
> Some are exactly the same.

This can happen if in the returned list there are multiple premium caches between two basic caches. Then all the premium caches in the "middle" of the two surrounding basic caches get the same distance. As an example, assuming the following list of caches is returned:

* BasicCache1 (Distance: 1km)
* PremiumCache1 (distance unknown)
* PremiumCache2 (distance unknown)
* PremiumCache3 (distance unknown)
* BasicCache2 (Distance: 9km)
* BasicCache3 (Distance: 15km)

Then the current heuristic to get distance for PremiumCaches 1-3 would be to calculate the average of BC1 and BC2 (=5km) and would assign "5km" to all three Premium Caches)

This is a heuristic, as said. Different heuristics are possible, e.g. the distance between the two "surrounding" basic caches can be "split" into equal parts. In the above example, PC1 would then get distance 3km, PC2 would get 5km and PC3 would get 7km. This can be discussed of course.

Apart from that, it can be perfectly valid that you have same distance to two or more geocaches, for example if one of them lies in the north and the other in the south of your position.

**Comment by eddiemuc** [comment]
No feedback on this for a while, is this still relevant?

**Comment by fm-sys** [comment]
I think we should round the heuristic guesses, to make it easier to recognize that these values are no real coordinates. I will assign this to me...

**Comment by YraFyra** [comment]
Idea:
During the process of registering  a new cache, you'll see a map view with all nearby caches.
Would it be possible to use this map view and correlate it with the caches in the search result to get exact coordinates?

**Comment by fm-sys** [comment]
I would never have expected, that GC is indeed leaking their PM cache coordinates. 

However, it seems that the API uses some kind of extra authentication (take a look at the request header), which is probably quite hard to imitate. Furthermore, GC will probably immediately fix that leak if they notice an irregular usage of that API. 

TMALSS, I think that this would be a) not be worth the effort and b) destroy cgeo's acceptance towards GC.

**Comment by eddiemuc** [comment]
I assume this is the call used by the website when the user creates/edits a new hide as owner. I further assume that the coordinates are included there so GC is able to display nearby caches with their 262m-radius. Note that the GC code is not included in the example result and thus can't be correlated with a cache list.

I agree with @fm-sys, I think trying to misuse this information to heuristically find out PM cache coordinates for basic members would be a trust violation towards Groundspeak. Also, the implementation and maintenance effort would be huge for this.

**Comment by YraFyra** [comment]
Has GC updated their search page now (compared with some weeks ago)?
Search result has distance for PMO caches now.
![image](https://user-images.githubusercontent.com/495545/135771783-18753d66-1ba3-4fd2-b827-aa5167d089ca.png)

**Comment by eddiemuc** [comment]
HI @YraFyra , in the web search the distance was always present. But c:geo uses the search function also utilized in the gc.com map view. In this view/search the distance is unfortunately not present for PMO caches:

![image](https://user-images.githubusercontent.com/6909759/135801885-507fa5c4-04d5-4f13-83b4-8fedd5810bc3.png)
