### ISSUE TITLE
Navigate targets cache instead of waypoint

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11635]
### Describe your problem!

From field...feel free to rephrase or improve:

- Current nightly 
- offline map
- open live map
- click on a waypoint of a cache (a parking WP in my case)
- In the popup click on the navigate icon
- Start a navigation

### How to reproduce?

see above

### Actual result after these steps?

I used "OSMand" and also tried others. All target the cache coords instead of the selected waypoint coords.
On some navigation methods it might ask whether I want the cache coords or the wp coords.

### Expected result after these steps?

All of the above is wrong. As I selected the specific waypoint, which is also named in the popup I want to navigate there but  it to the cache coords.

Took me a long detour today as I did  it realize, that OSMand got wrong coords.

### Reproducible

Yes

### c:geo Version

2021.09.07-NB

**Comment by moving-bits** [comment]
Seems to be the same if you select "navigate (car)" from "three dot menu", see ticket 418969 (verified in a short test).

**Comment by okainov** [comment]
>see ticket 418969

Which one? It doesn't look like number of GitHub issue here, could you please share a link?

**Comment by Lineflyer** [comment]
No, ots from our suppot mail system, just as a reference here but not publicly available.

**Comment by fm-sys** [comment]
Probably caused by https://github.com/cgeo/cgeo/pull/10949, just wondering why this hasn't be noticed earlier...?

**Comment by fm-sys** [comment]
@Lineflyer can you tell me if you had selected "OSMand" as default navigation action (click/long-click on compass) or from the "navigate" sub menu?

If the second is the case, I think I've found the problem...
