### ISSUE TITLE
Watchlist status not initialized/updated correctly

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#11638]
### Describe your problem!

I recently submitted #11619 which was fixed in the latest release.
However it is still not working quite right - the displayed watchlist status is not accurate on refresh or initial load.

### How to reproduce?

1. In cgeo, load a cache that is **not** on your watchlist.
2. Do "Open in browser"
3. On the webpage, click "Watch" to add it to your watch list
4. return to cgeo and pull-down/release to refresh the cache details

### Actual result after these steps?

- "The cache is not on your watchlist" is shown.
- Tapping on the "Add" icon results in a failure message
- **Note** the same issue arises if you load a cache that **is** already on your watchlist, but **isn't** currently stored in cgeo.

### Expected result after these steps?

Watchlist status should be updated when cache details are initially loaded or refreshed.

### Reproducible

Yes

### c:geo Version

2021.09.08

**Comment by Lineflyer** [comment]
Can reproduce. The fix seems not complete.

**Comment by ztNFny** [comment]
Required change:
GCConstants.java:
static final Pattern PATTERN_WATCHLIST = Pattern.compile("data-cacheonwatchlist=\"True\"");

I can't do a PR right now.
