### ISSUE TITLE
Found state in history not updated after Manage Caches -> Refresh all

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#11643]
### Describe your problem!

Just did an "owner maintenance" offline log in cgeo. It showed up with a left side orange bar in the history list. As a next step I experted the field notes, used external tooling to compose a log text, logged the cache to geocaching.com.

As a next step, while still in showing the history list (one entry), I did `Manage Caches -> Refresh all` and my expectation was that there would be a left side bar half green half orange, however the bar remained orange.

I then did a "Manage caches -> Clear offline logs", which made the orange bar go away. As a next step I refreshed the cache again, my expectation was that I'd get the green bar on the left, however no bar shows up.

I went into the details for that cache and I can see my  new log with the green bar, as expected.

### How to reproduce?

See description above

### Actual result after these steps?

Left side green bar in history listing not shown

### Expected result after these steps?

Green bar on the left side of the cache in history list

### Reproducible

Yes

### c:geo Version

2021.09.08

**Comment by fm-sys** [comment]
Was it a "need maintenance" or "did owner maintenance" log? For the second, it's indeed the intended behavior...

![Screenshot_20210911_122920_cgeo geocaching_copy_137x473](https://user-images.githubusercontent.com/64581222/132944902-9bb2b0cd-f8ad-4733-a6c7-d43eb90713b4.png)

> Anyway, what confused me is that the log entry is shown with a green left side bar in detail activity swiping over to the list of logs.

This is indeed a bit inconsistent. However, this marker indicates somehow the state of the cache. A found cache will always stay "found" so we can show the marker. However, it's not the case for caches you own. A owner maintenance needs to be done more than once over time...

**Comment by baiti** [comment]
It was the latter, "Owner Maintenance provided", I believe. So I'll close that issue.
