### ISSUE TITLE
Show the last few logs in map popup

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11646]
### Tell us your idea!

When clicking a cache on the map the popup with summary information appears. This popup should get a new line showing icons for the latest logs available.
This would allow to get a quick glance at the "health" of the cache.

Similar features are implemented by GC little helper and Locus

Screenshot from GClh
![image](https://user-images.githubusercontent.com/1258173/132956364-a1b22e93-45b8-495e-a548-65300b9173cf.png)

### Usecase

As a cacher out in the field I select the next cache I plan to visit and want to see important information at a glance that will help me find the cache.
This includes D/T rating, size - and whether the cache was last found or not. If there's many DNFs I might not want to search for too long compared to a cache with recent founds. 

Potential problems:
- Information is outdated and thus the wrong conclusion is made - That however holds true for a lot of info when offline caching, the cache could be archived, moved, ... - Mitigation: Make it visible how old the information shown is.
- No logs available -> Don't show the section at all.

### Additional Information

Of course this can only use the latest information available, like for an offline cache this info might be outdated, but that's true for all the information, so not really an advantage.

You can assign this to me, I can take a look at this after vectorIcons is done.

**Comment by murggel** [comment]
@ztNFny see similar requests in #1801 and #7989

**Comment by ztNFny** [comment]
Open questions to me:
- How many logs to show? I'd go with 5-10, so maybe 7 for a start.
- Which log types should be shown, all or specific ones? Interesting imho: Found (including Attended, Webcam picture taken), DNF, NM, NA, Owner Maintanance, Enable. Reason against all: We need icons for all ;-)
