### ISSUE TITLE
CI: Move to java 11

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11656]
### Tell us your idea!

A java 11 installation is the prerequisite to use gradle 7 (see #11539).
As in AS 2020.3.1 we have already a java 11 included as default java and it compiles successful our code with gradle 4.* I do not expect trouble.

Someone with direct access has to change the default java implementation.
I found a configuration at https://ci.cgeo.org/configureTools/, with directory `/opt/jdk1.7.0_04/`.

**Comment by bekuno** [comment]
See the CI output:
~~~
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
~~~
There should be a JDK 8 defined in the PATH or JAVA_HOME variable.

**Comment by Lineflyer** [comment]
@mucek4 Please take a look, so that the devs can finally migrate to new gradle.

**Comment by mucek4** [comment]
Do we need Oracle's java or is OpenJDK also OK? With open spirit, I would vote for OpenJDK.

**Comment by mucek4** [comment]
And we need some upgrading before we can do that. Technically today is raining and I can do the upgrade, but CI would be down for let's say couple of hours. Shall I go for it?

**Comment by Lineflyer** [comment]
I would say: Go for it...soner or later we need this upgrade anyway and if you happen to have time now, just do it.

**Comment by bekuno** [comment]
> 
> 
> Do we need Oracle's java or is OpenJDK also OK? With open spirit, I would vote for OpenJDK.

I do not have a Linux AS at hand.
In the Windows AS we have:
~~~
C:\Program Files\Android\Android Studio\jre>bin\java.exe --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
~~~

I think we can try the latest from https://adoptium.net/releases.html?variant=openjdk11 or, if you want to use the OpenJ9 JVM from the (old) site https://adoptopenjdk.net/releases.html?variant=openjdk11 .

**Comment by UniQP** [comment]
> ```
> openjdk 11.0.10 2021-01-19
> OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
> ```
It's exactly the same for Linux AS.

**Comment by mucek4** [comment]
Ok. We'll go with OpenJDK, ci is already down. Upgrade in progress in snapshot if anything goes sideways we can return to this state in a minute or two.

**Comment by mucek4** [comment]
Jenkins master is up&running. Java 11installed and also jenkins is running in Java 11 now.

cgeoci:~# java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Debian-2deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.12+7-post-Debian-2deb10u1, mixed mode, sharing)

Probably I have to update executors. I have to change docker files and rebuild images.

Please notify me if Jenkins has any problems. I'll delete snapshot in couple of days.

**Comment by bekuno** [comment]
> Probably I have to update executors. I have to change docker files and rebuild images.

It looks like that. See https://ci.cgeo.org/job/cgeo%20pull%20request/7056/console

**Comment by mucek4** [comment]
@bekuno It says: Building remotely on cgeo-1 

Executors are not yet updated.

**Comment by fm-sys** [comment]
Something seems to be wrong with our CI. Maybe memory is full?

    18:43:19  org.gradle.api.UncheckedIOException: Could not add entry '/home/jenkins/.gradle/caches/transforms-3/3f816fadca748577347980fc62e853ef' to cache file-access.bin (/home/jenkins/.gradle/caches/journal-1/file-access.bin).

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11676#issuecomment-923119607_

However, the second build was working normal.

**Comment by mucek4** [comment]
Could be right in the middle of update. cgeo-4 executor is up and has Java11. If anything goes sideways, disable cgeo-4 and re-anable cgeo-1

**Comment by mucek4** [comment]
Ok. It is building now, Java11 is installed. But buils still fails.
https://ci.cgeo.org/job/cgeo%20pull%20request/7072/console

**Comment by bekuno** [comment]
> 
> 
> Ok. It is building now, Java11 is installed. But build still fails.
> https://ci.cgeo.org/job/cgeo%20pull%20request/7072/console

There is no java error.
It looks like we have to define some extra dependency order for such problem:
~~~
Execution optimizations have been disabled for task ':main:checkstyle' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/jenkins/slave/workspace/cgeo pull request'. Reason: Task ':main:checkstyle' uses this output of task ':main:checkBasicDebugAarMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
 ~~~
 
Non gradle 7 builds fine, but there are some `ns` problems like
~~~
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
~~~
see e.g. https://ci.cgeo.org/job/cgeo%20pull%20request/7078/console or https://ci.cgeo.org/job/cgeo%20continuous%20integration/4288/console

**Comment by Lineflyer** [comment]
The cyclic website tests are also failing (on cgeo-4):

```

* What went wrong:
Execution failed for task ':main:installBasicDebug'.

    com.android.builder.testing.api.DeviceException: Could not create ADB Bridge. ADB location: /opt/android-sdk-linux/platform-tools/adb
```

See <https://ci.cgeo.org/job/website%20tests%20(release)/9958/display/redirect?page=changes>

**Comment by mucek4** [comment]
I have updated executor-4 again. First build was timeout.

**Comment by mucek4** [comment]
executor-4 worked. I will let it run and update other executors in next days.

**Comment by bekuno** [comment]
Many thanks.
It looks that the first run had too much to do initial.

**Comment by bekuno** [comment]
cgeo-1 and cgeo-5 are running with java11 now, therefore closing here.
