### ISSUE TITLE
Different final marker overlays

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11659]
Quick note from vacation:

Newest NB with vector icons:
Some of my solved caches which are moved to final have a white flag on blue at lower right, some have a purple pin at that position.

Two questions arise:
1. Why is there a difference?
2. Why dont we use s small version of the final waypoint icon instead (red flag on white or inverted). Would IMHO be more consistent and understandable.

**Comment by ztNFny** [comment]
Flag=corrected coordinates
Pin=has a final waypoint

Up until now these 2 completly different cases had the same icon which was simply wrong.

As for the color scheme: white background doesn't fit the scheme and has low visibility. Red background is too prominent. So i went for blie as most users will be accustomed from GC.

**Comment by bekuno** [comment]
If we have final coordinates then we should show a final flag, but not a Pin.
Maybe we can use different final flag colors/backgrounds.

**Comment by ztNFny** [comment]
A different flag can't be differentiated as the icon is too small.
That's why i went with the pin to indicate that you should look at the list of waypoints.

Using the same icon for 2 different cases and just differentiating by color is bad as it ignores accessibility.

**Comment by Lineflyer** [comment]
Thanks @ztNFny for explanation. I might have missed the discussion due to my vacation.

My spontanous feedback would be, that the PIN overlay does not carry any valuable information (at least on the map). Because if a final waypoint is defined or not does not change the location of the shown icon. 
So if we now support to handle these cases different I would suggest to show no special indication at all for that case (final defined for that cache but icon is not on shown on that coords).

But let me think about it and use it some more days...still feedback welcome!

Regarding the color:
Do you have an example of how red flag on white or white flag on red would look like?

**Comment by bekuno** [comment]
The final flag should have the same meaning on multi caches as on mysteries - the final pount is identified. 
If the cache coordinate is moved to another point then the situation is like a normal cache. Mayby change then the cache symbol color to green like the color for normal caches.

**Comment by ztNFny** [comment]
> So if we now support to handle these cases different I would suggest to show no special indication at all for that case (final defined for that cache but icon is not on shown on that coords).

That's also my personal opinion, but there were several voices against removing the indicator in that other issue. Those users seem to only add a final waypoint instead of modifying the coordinates (which seems to be the more common use, at least all people i personally know do it that way).
So i kept an indicator but made sure it can be differentiated.

> Regarding the color:
> Do you have an example of how red flag on white or white flag on red would look like?

You can change the colors in the drawable or make a "NM" offline log to see a similar icon in the upper left corner.

**Comment by ztNFny** [comment]
> The final flag should have the same meaning on multi caches as on mysteries - the final pount is identified.

It has. The marker doesn't care about the cache type at all.

**Comment by bekuno** [comment]
>  The marker doesn't care about the cache type at all.

Correct - the **marker** should have the same meaning - a flag means that a final point exist.

**Comment by ztNFny** [comment]
> > The marker doesn't care about the cache type at all.
> 
> Correct - the **marker** should have the same meaning - a flag means that a final point exist.

You're thinking about 1 of 2 cases c:geonis used: defining a final waypoint vs setting modified ccords.
The current solution addresses both ways - and needs to differentiate them. What you want would completly ignore the setting modified coords way, excluding many (afaict the majority) of users.

**Comment by ztNFny** [comment]
> > The marker doesn't care about the cache type at all.
> 
> Correct - the **marker** should have the same meaning - a flag means that a final point exist.

Easy to turn that around: a flag in waypoints doesn't mean "final exists" but "this is the final". So using the flag for modified coords makes complete sense because where the marker is "this is the final". While with a final waypoint only being defined it doesn't have any impact at all on the map marker - it stays in it's original position

**Comment by murggel** [comment]
> > > The marker doesn't care about the cache type at all.
> > 
> > Correct - the **marker** should have the same meaning - a flag means that a final point exist.
> 
> Easy to turn that around: a flag in waypoints doesn't mean "final exists" but "this is the final". So using the flag for modified coords makes complete sense because where the marker is "this is the final". While with a final waypoint only being defined it doesn't have any impact at all on the map marker - it stays in it's original position

My first thought would be:
when I see a cache with a flag on the map -> for the cache a final exists, because it's the same symbol as for the final waypoint-type and it indicates that it has not necessarily to be at that position. 
Whereas when I see pin -> correct position for that cache - the final position is right here (modified coordinates)

**Comment by bekuno** [comment]
No! I see both posibilities and understand your point of view.
I only propose to stay consistent in the situations when a final point exist (without modified original point). 
And in a situation with a moved cache symbol to a point with the cache box I suggest to show that in another way.
By the way, I dont know which of the two methods are more often in use - you should do it in the same way.

**Comment by ztNFny** [comment]
> I only propose to stay consistent in the situations when a final point exist (without modified original point).

Consistent with what?
The old icons - cant be as in both situations the flag is shown.
The waaypoint icon - easy to read that in 2 completly different ways that both make sense, depending on whether you interpret it as "has final" or "is final"

> And in a situation with a moved cache symbol to a point with the cache box I suggest to show that in another way.

Then make a concrete suggestion on what it should.be in your opinion.

> By the way, I dont know which of the two methods are more often in use - you should do it in the same way.

I've been working on tiny details of the icons for week and have talked to about 20 cachers in detail about the way they use different aspects. Not a single one used the method of defining a waypoint but not setting it as modified. Might be due to the sample, no way to tell for sure. As you can see lineflyer would even think to remove the "has final" indicator completly - i didnt want to do that as i see that some.people might prefer to do it this wayy si thats why both icons exist now.

**Comment by Lineflyer** [comment]
Lets just think about it some more days and maybe we find an even better solution.

**Comment by fm-sys** [comment]
> As you can see lineflyer would even think to remove the "has final" indicator completly - i didnt want to do that as i see that some.people might prefer to do it this wayy si thats why both icons exist now.

I would be in favor of removing the second icon completely as well... 👍

**Comment by ztNFny** [comment]
An option for those who don't use modified coords (this seems to be the only situation where it feels.like theres a gap) to show the presence of a final waypoint with the same marker as modified?
In pseude-code: if (cache.hasModified() || (settings.showModifiedIconIfFinalDefined() && cache.hasFinal()) { flag } elseif (cache.hasFinal()) { pin }

I see the pin useful for Challenges that are not at the listing coord - that's the only situatiom that comes to.my mind where you encounter that in the wild. But it's mysteries, so i'd also be perfectly fine with not having any indicator for those.

**Comment by ztNFny** [comment]
After some more thought about this I see the following working modes and usecases:

1) User sets modified coordinates when solving a cache
1a) Cache has modified coords
  -> user wants to see a "corrected" marker on map
1b) Cache has modified coords & final waypoint
  -> same as 1a
1c) Cache has a final waypoint
- the wild this "should" be the case only for a challenge cache, they are required to have a final waypoint.
- I've also see a Traditional with a final waypoint several meters away, but this imho is wrong and not something to take into account
  -> the challenge is a normal unsolved mystery and that point and the user needs to look at the listing to determine where it's listed.  -> No need to indicate this on the map imho

2) User adds a final waypoint in c:geo when solving a cache
2a & 2b) Cache has modified coords
  -> shouldn't happend as the user adds final waypoints instead of modified coords
  if this still happens what does the user want to see? Requires input from someone working like this, @bekuno 
2c) Cache has a final waypoint
  -> user wants to see a "has final" marker on map
Do we need to differentiate between the cases "hasFinal" and "modified" here? @bekuno

**Comment by murggel** [comment]
I am adding often a final waypoint (to multis or mysteries) while calculating the correct coordinates but don't set them as corrected coordinates due to various reasons.
So normally I want to see on the map, if the cache has "solved" coordinates (final with valid coordinates or corrected coordinates) and if the icon is on that position.
If a cache has valid final AND corrected coordinates, the corrected coordinates has higher prio and not both of them has to be shown (if we want to differentiate that in the map)

**Comment by ztNFny** [comment]
> I am adding often a final waypoint (to multis or mysteries) while calculating the correct coordinates but don't set them as corrected coordinates due to various reasons.
> So normally I want to see on the map, if the cache has "solved" coordinates (final with valid coordinates or corrected coordinates) and if the icon is on that position.
> If a cache has valid final AND corrected coordinates, the corrected coordinates has higher prio and not both of them has to be shown (if we want to differentiate that in the map)

If i understand you right the current implementation should match your needs, right? If modified -> show modified icon, elseif hasFinal() -> show final icon.

Regarding the icon for "has final waypoint", what do you think about using the same as what's used as MapMarker for displaying final waypoints on the map (when viewing all waypoints from the waypoint-tab of a cache): 
![image](https://user-images.githubusercontent.com/1258173/133886286-4daef69c-0304-4484-8172-1c757438d51b.png)

**Comment by murggel** [comment]
> If i understand you right the current implementation should match your needs, right? If modified -> show modified icon, elseif hasFinal() -> show final icon.

In my version 2021.09.14-NB-1447568 the final is shown instead of corrected coordinates, but the logic you mentioned would be sufficient for me.

> 
> Regarding the icon for "has final waypoint", what do you think about using the same as what's used as MapMarker for displaying final waypoints on the map (when viewing all waypoints from the waypoint-tab of a cache): 
> ![image](https://user-images.githubusercontent.com/1258173/133886286-4daef69c-0304-4484-8172-1c757438d51b.png)
> 

Looks good 👍 better than the blue one.

**Comment by ztNFny** [comment]
> > If i understand you right the current implementation should match your needs, right? If modified -> show modified icon, elseif hasFinal() -> show final icon.
> 
> In my version 2021.09.14-NB-1447568 the final is shown instead of corrected coordinates, but the logic you mentioned would be sufficient for me.

If you see the purple marker you don't have corrected coords, those always win. try refreshing?

**Comment by murggel** [comment]
Ok, you are right

**Comment by Lineflyer** [comment]
> Regarding the icon for "has final waypoint", what do you think about using the same as what's used as MapMarker for displaying final waypoints on the map (when viewing all waypoints from the waypoint-tab of a cache):
> ￼

Lets carefully think about what marker to use in what case.
IMHO users of current versions of c:geo know the read flag as the marker for corrected coords. So we should use that one you just proposed for the purpose "corrected listing coords" and maybe then use the blue final flag for "has final waypoint" instead.

In my eyes this most sense, if we want to keep both indicators.

**Comment by ztNFny** [comment]
> > Regarding the icon for "has final waypoint", what do you think about using the same as what's used as MapMarker for displaying final waypoints on the map (when viewing all waypoints from the waypoint-tab of a cache):
> > ￼
> 
> Lets carefully think about what marker to use in what case.
> IMHO users of current versions of c:geo know the red flag as the marker for corrected coords

Users of GC.com are used to a blue marker for corrected though.
And all icons are changing, so "used to in old version of c:geo" won't really apply

Also a white marker will be way harder so see at a glance than blue one as white simply doesn't stand out.

I very very very strongly vote for keeping the blue for modified - what icon is used for the other case I don't give a sh.. about as I'll never see it as I don't use that way of setting final coords. So I suggest that someone caching like that just designs that icon.

**Comment by Lineflyer** [comment]
> Users of GC.com are used to a blue marker for corrected though.

Where is that? I only rarely use the website and I am currently looking for it...

> Also a white marker will be way harder so see at a glance than blue one as white simply doesn't stand out.

Can you post an example of how that red flag on bottom right would look like? Maybe you are right.

**Comment by ztNFny** [comment]
> > Users of GC.com are used to a blue marker for corrected though.
> 
> Where is that? I only rarely use the website and I am currently looking for it...

![image](https://user-images.githubusercontent.com/1258173/133897370-792f0f99-eda5-45bf-a990-0771fdab0525.png)
![image](https://user-images.githubusercontent.com/1258173/133897382-4abb1a87-ad9b-4a9f-b510-b8ed35b37d5f.png)


> > Also a white marker will be way harder so see at a glance than blue one as white simply doesn't stand out.
> 
> Can you post an example of how that red flag on bottom right would look like? Maybe you are right.
![image](https://user-images.githubusercontent.com/1258173/133897407-1dd8b094-2889-46b5-b0e1-98234ab18497.png)

**Comment by Lineflyer** [comment]
Lets just use those two you pictured above in the way you suggested:
Blue : Corrected coords
Red: Has Final Waypoint (but no corrected coords)

As you have implemented them, we should for sure give you the freedom to follow your preference.
When we later have this in beta state we can still decide otherwise depending on user feedback. OK?

**Comment by ztNFny** [comment]
> When we later have this in beta state we can still decide otherwise depending on user feedback. OK?

What should imho be decided before a beta is the topic about handling of hasFinal() itself. The existing marking on map was introduced by accident it seems and there are several votes for completely removing it - if it was removed the whole discussion about which icon to use is obsolete.

So decisions that should be taken:
1. Should a marker be displayed in the case a cache has no modified coordinates but a final waypoint?
a) Always
b) Make it a setting
c) Never
2. If the answer to 1 is a or b: Which icon should be shown in this case for such caches?
a) Same as for modified coordinates
b) A different icon

And only then we discuss about the actual design of the icon. I had assumed 1=a, 2=b in my development based on feedback here, my personal opinion would be 1=b, 2=b, but I didn't want to remove a feature someone might use or introduce yet another setting.

**Comment by bekuno** [comment]
My 2 cents:
 
> 
>     1. Should a marker be displayed in the case a cache has no modified coordinates but a final waypoint?
>        a) Always
>        b) Make it a setting
>        c) Never

a)  (If the final has coordinates :-) )

> 
>     2. If the answer to 1 is a or b: Which icon should be shown in this case for such caches?
>        a) Same as for modified coordinates
>        b) A different icon

b)

Today we have only a marker for "has final waypoint".

The questions forget an often existing use case. The mystery is a "multi-mysty". 
This means that the solution for the mystery creates not a final but a first stage. If you "set this as cache coordinate" then you have only moved the cache point but not defined the final. 
If you have later a final coordinate, then the cache symbol should show the additional final symbol, imho.

**Comment by ztNFny** [comment]
> Today we have only a marker for "has final waypoint".

Huh? Today (in release) there's a marker that's displayed in case (hasModified || hasFinal))

> The questions forget an often existing use case. The mystery is a "multi-mysty".
> If you have later a final coordinate, then the cache symbol should show the additional final symbol, imho.

For such cases I document all the stages and set the coordinates to the final 
When playing a multi I'm actively doing it, I don't care about the icon on the map marker at all. And when I've completed it I also don't care whether it has a final or not, I've already completed it.

**Comment by ztNFny** [comment]
and why can't you use custom list / cache icons to cover that special situation?

**Comment by bekuno** [comment]
> > Today we have only a marker for "has final waypoint".
> 
> Huh? Today (in release) there's a marker that's displayed in case (hasModified || hasFinal))

You are correct. 
And we can not differentiate if there is a final waypoint or not.

**Comment by bekuno** [comment]
> 
> 
> and why can't you use custom list / cache icons to cover that special situation?

this is a normal situation.

**Comment by bekuno** [comment]
> 
> 
> > and why can't you use custom list / cache icons to cover that special situation?
> 
> this is a normal situation.

Why should someone define separate icons for a normal situation?
Not a real question to you. These are normal mysteries.

**Comment by ztNFny** [comment]
> > > and why can't you use custom list / cache icons to cover that special situation?
> > 
> > 
> > this is a normal situation.
> 
> Why should someone define separate icons for a normal situation?
> Not a real question to you. These are normal mysteries.

you mentioned a special usecase: Multi-Mysteries. There's about 25% mysteries world wide, from my experience I'd say <5% of those are multis, but let's assume 10%, that makes 2,5% of caches - not really a normal situation.

And anyway, the most important question to you remains unanswered: In which situation do you really need to see this differentiation on the map?

**Comment by bekuno** [comment]
> > The questions forget an often existing use case. The mystery is a "multi-mysty".
> 
> For such cases I document all the stages and set the coordinates to the final
> When playing a multi I'm actively doing it, I don't care about the icon on the map marker at all. And when I've completed it I also don't care whether it has a final or not, I've already completed it.

You can do it so.
But there are (many) other which are do it not so or rarely use user modified cache coordinates.

> 
> > If you have later a final coordinate, then the cache symbol should show the additional final symbol, imho.
> 
> Where should that second marker be? And I don't see how it adds any additional value - whether it's a cache that was solved+multi-staged or just solved or just multi-staged - it's all the same to me. In which situation do you really need to see this differentiation on the map?

We discuss about a additional red or blue final symbol for the cache icon.
(or whatever symbol we decide to use)

**Comment by ztNFny** [comment]
> > Where should that second marker be? And I don't see how it adds any additional value - whether it's a cache that was solved+multi-staged or just solved or just multi-staged - it's all the same to me. In which situation do you really need to see this differentiation on the map?
> 
> We discuss about a additional red or blue final symbol for the cache icon.
> (or whatever symbol we decide to use)

And where should that additional symbol be? Bottom left corner is user note, Top left is (offline) log, Top right is stored status, Bottom right is modified/final - and now you want to add another one for the case modified + final - where?!

**Comment by bekuno** [comment]
Current situation:

in latest beta: Mystery with unchanged and with modified coordinate:
![Screenshot_20210918_122612](https://user-images.githubusercontent.com/32555742/133906319-8ba4c658-8b68-4bcf-9cf4-c8e3c53c68d1.jpg)  ![Screenshot_20210918_122533](https://user-images.githubusercontent.com/32555742/133906322-017bf04e-61ed-4e3c-aef4-0884ed7489ce.jpg)

in latest beta: Multi:
![Screenshot_20210918-122444_cgeo](https://user-images.githubusercontent.com/32555742/133907532-5b4631fb-fe2f-40ea-b8ba-002cb77c672d.jpg)

We have here in all situations a red flag as additional symbol.

in nightly: unchanged, modified to stage, modified to final
![Screenshot_20210918-130804_cgeo](https://user-images.githubusercontent.com/32555742/133907001-b56e36bd-bf4f-40bd-822b-cd09e0666a7a.jpg)  ![Screenshot_20210918-130859_cgeo](https://user-images.githubusercontent.com/32555742/133907007-168075c7-8ca3-4775-8790-01f33cb548c0.jpg)   ![Screenshot_20210918-130952_cgeo](https://user-images.githubusercontent.com/32555742/133907014-d51442d1-2114-4439-8116-e78fd290d8b1.jpg)

My proposal:
Let the red flag as known symbol for "has a final" (instead of the pin).
And use the blue flag for "is user modified".

**Comment by bekuno** [comment]
> And where should that additional symbol be? Bottom left corner is user note, Top left is (offline) log, Top right is stored status, Bottom right is modified/final - and now you want to add another one for the case modified + final - where?!

Either blue or red, not both.

**Comment by ztNFny** [comment]
> > And where should that additional symbol be? Bottom left corner is user note, Top left is (offline) log, Top right is stored status, Bottom right is modified/final - and now you want to add another one for the case modified + final - where?!
> 
> Either blue or red, not both.

Then please rephrase your sentence "If you have later a final coordinate, then the cache symbol should show the additional final symbol, imho." as I apparently don't understand it.
Showing either of the icons is the current implementation.

**Comment by bekuno** [comment]
> 
> 
> > > And where should that additional symbol be? Bottom left corner is user note, Top left is (offline) log, Top right is stored status, Bottom right is modified/final - and now you want to add another one for the case modified + final - where?!
> > 
> > Either blue or red, not both.
> 
> Then please rephrase your sentence "If you have later a final coordinate, then the cache symbol should show the additional final symbol, imho." as I apparently don't understand it.

I did not said "... should show additionally the final symbol". 

> Showing either of the icons is the current implementation.

And this is fine.

I´ll try to generate a proposal in a code like structure here.

~~~
if (cache.hasFinalWayPoint) { 
  if (cache.hasModifiedCood && cache.coord == oneOf(cache.FinalWaypoint.coord)) { // set to final waypoint
    addModifiedFlag 
  } else {
    addFinalFlag
  }
} elsif (cache.hasModifiedCood) { // no Final waypoint
  addModifiedFlag 
}
~~~


A additional idea came in my mind to cover the situation when a waypoint exist which is no Final/Parking/Reference waypoint. But this should go to another Issue and needs fine tuning.
~~~
if (not cache.hasFlag && cache.hasStationWaypointWithCoords) {
  addPin
}
~~~

**Comment by bekuno** [comment]
@fm-sys There was not yet a agreement, in which situations we want to show the red or the blue flag, especially for "multi-mysty" with modified coordinates.
I proposed a different method in https://github.com/cgeo/cgeo/issues/11659#issuecomment-922456075 than implemented.

@murggel @Lineflyer What do you think about?

**Comment by murggel** [comment]
> The questions forget an often existing use case. The mystery is a "multi-mysty". 
> This means that the solution for the mystery creates not a final but a first stage. If you "set this as cache coordinate" then you have only moved the cache point but not defined the final. 
> If you have later a final coordinate, then the cache symbol should show the additional final symbol, imho.
> 


My workflow in that case would be to set the final then as cache coordinates. So for me it's not necessary to show both information.

**Comment by bekuno** [comment]
No one wants to show both information (icons).

The questions are - what additional symbol (flag) do you expect when a final waypoint is defined and the cache coordinates have been moved to it, or as second a final waypoint exists and additionally a non-final waypoint to which the cache coordinate has been moved.

**Comment by ztNFny** [comment]
> The questions are - what additional symbol (flag) do you expect when a final waypoint is defined and the cache coordinates have been moved to it,

Keep in mind this is applies to all caches where modified coords were set on GC and the cache then loaded in cgeo - the modified coords are automatically added as a final waypoint.
Thus imho a final waypoint should only be taken into account if it's different from the current cache coords (whether changed (e.g. solved mystery/multi) or unchanged (e.g. challenge))

**Comment by bekuno** [comment]
> Keep in mind this is applies to all caches where modified coords were set on GC and the cache then loaded in cgeo - the modified coords are automatically added as a final waypoint.

Sure? On my tests the coordinate on the website was only moved, no additional waypoint was added.

**Comment by ztNFny** [comment]
>     2. a final waypoint exists and additionally a non-final waypoint to which the cache coordinate has been moved
>        -> depends on what would be seen as "master", for me the modified coords would win, because I often have "old" final waypoints due to changes in the mystery.

You're right about old waypoints, especially as it's sometimes impossible to get rid of them in cgeo as it jus refuses to forget them. I often have caches with several final waypoints - but the ones i care about i set as modified so that i have the map marker in the right place.
With that argument i find the current logic (if modified elseif hasfinal) best.

@bekuno what i don't understand, you say you use waypoints in cgeo instead of modified coords. But if you don't modify, then you'll only ever have the hasfinal case and shouldn't care about the hasmodified?

**Comment by ztNFny** [comment]
> > Keep in mind this is applies to all caches where modified coords were set on GC and the cache then loaded in cgeo - the modified coords are automatically added as a final waypoint.
> 
> Sure? On my tests the coordinate on the website was only moved, no additional waypoint was added.

Sorry, it's not setting the modified coords but having a user note with the coords that creates the waypoint.
My mystery docu always has the solution and at the end the waypoints for easier documentation. Thus pretty much every mystery has a final WP generated from note and equal to the modified.

**Comment by murggel** [comment]
> No one wants to show both information (icons).

Sorry, misleading phrasing from my side.

So your proposal was to show the indicator for has final also if the final waypoint is not the same as the modified coords, while in current implementation the indicator for modified coords is shown.

So that would mean, if the indicator for final is shown, the cache could be at the shown coordinates (has modified coords but also a valid final) but does not has to be there (only final but no modified coords).
So user has to look where to go...
Whereas the current implementation assumes, that the modified coords "overwrites" a defined final-waypoint.

Did I get that right?

> 
> The questions are - what additional symbol (flag) do you expect when a final waypoint is defined and the cache coordinates have been moved to it, or as second a final waypoint exists and additionally a non-final waypoint to which the cache coordinate has been moved.

**Comment by Lineflyer** [comment]
Lets try to summarize here:

AFAICS we have the following currently implemented:
- Cache has modified listing coords = Showing the white/blue final flag
- Cache has no modified coords but a valid final waypoint is present = Showing the red/white final flag 

Everyone OK with this implementation as a first approach?

**Comment by bekuno** [comment]
> So your proposal was to show the indicator for has final also if the final waypoint is not the same as the modified coords, while in current implementation the indicator for modified coords is shown, in any case of modified coords.

Mostly correct.
If you use modified coordinates, then it is not necessary to set a final point. In this way you will have often no final waypoint for mysteries.

> So that would mean, if the indicator for final is shown, the cache could be at the shown coordinates (has modified coords but also a valid final) but does not has to be there (only final but no modified coords).
> So user has to look where to go...

And this is the same situation the other way around.
If the indicator for modified coordinates is shown, then it is not necessary that there is the final point. 

> Whereas the current implementation assumes, that the modified coords "overwrites" a defined final-waypoint.

And my suggestion was, that a final waypoint has a higher priority, as this is what a user actively set. 

Maybe the discussion is too academic. 
At the end the user must set the final or modified state self and should be aware of his method.

**Comment by bekuno** [comment]
> 
> 
> Lets try to summarize here:
> 
> AFAICS we have the following currently implemented:
> 
>     * Cache has modified listing coords = Showing the white/blue final flag marker
> 
>     * Cache has no modified coords but a valid final waypoint is present = Showing the red/white final flag marker
> 
> 
> Everyone OK with this implementation as a first approach?

Correct summerized.
Lets see if users or ok with the solution. 
At least it is a fine solution for modified coords and ok for unmodified.
OK then also from my side.
