### ISSUE TITLE
Search by keywords non-predictable

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11652]
### Describe your problem!

This originally comes from a support ticket (682949) claiming that search by keyword does not work at all anymore since the last couple of updates - respectively only finds caches which are saved locally.

One of the user's test cases was "Chiemgauer Almgangerl".

During retest search by keyword actually did work, with 21 matches, but we found two other bugs:
- If you search for substring of above's example, you get less results, although it should match at least above's results. Test case was "Chiemgauer Alm".
- If you search multiple times for the same keywords, the results will differ. Test case was "Chiemgauer Alm", resulting in 11 / 12 / 13 or 14 matches in our (short) tests.

### How to reproduce?

Go to mainscreen, then search.

Test case a:
- Search for "Chiemgauer Almgangerl"
- results in 21 matches in our tests

Test case b:
- Search for "Chiemgauer Alm"
- results in less matches than above

Test case c:
- Search for "Chiemgauer Alm"
- go back to search and search again with the same keywords
- result sets vary in size, 11 up to 14 in our tests

### Reproducible

Yes

### c:geo Version

2021.09.08

**Comment by eddiemuc** [comment]
I used the search term "Chiemgauer Alm" directly on the GC.com website, and unfortunately it produces the same nondeterministic results (I got 14, 11, 10, 9 results by researching with exact same parameters).

It looks a bit as if this behavior is wrong on Gc.com side. Not sure if we can so anything about it

**Comment by eddiemuc** [comment]
Update: using uppercase or lowercase does not seem to make a difference on GC.com.website. same (nondeterministic) behavior.

**Comment by eddiemuc** [comment]
...and searching for full string "Chiemgauer Almgangerl" results in 21 hits on GC.com (deterministic), and those are more results than for any of the (non-deterministic) searches for "Chiemgauer Alm".

I don't know what GC.com is doing here, my guess is that they use some sort of indexing mechanism to optimize their search performance and this only works exactly for "whole word" match. 

Anyway, currently it seems to me that there's not much we can do on our side to fix this.

**Comment by moving-bits** [comment]
Thanks for cross-checking. Then let's close this issue.
