### ISSUE TITLE
some waypoints have N0 E0 as coordinates

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11651]
Due to an yet to be identified scenario waypoints end up as N0 E0 for waypoints without coords defined for the waypoint, e.g. https://www.geocaching.com/geocache/GC4VZCM_total-verwirrt

@murggel as discussed today

**Comment by ztNFny** [comment]
@murggel how can i figure out when a cache was added to cgeo (added, not updated). It might be all caches woth n0 e0 are old and caused by something already fixed.

**Comment by murggel** [comment]
> @murggel how can i figure out when a cache was added to cgeo (added, not updated). It might be all caches woth n0 e0 are old and caused by something already fixed.

I don't think that this information is stored, but not sure.

Probably we can close here, as I didn't see any suspicious in code and reopen if it is reproduciable

**Comment by ztNFny** [comment]
Close for now
