### ISSUE TITLE
Map of a waypoint shows hexagon instead of circle outline

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11665]
- Open a GC.com cache which has some waypoints (Type: question to answer in my case)
- Swipe to waypoint tab
- Long tap the compass rose icon next to the wapoint

Result:
Map opens with waypoint at the right place, but it has a hexagon outline 

Expected Result:
The outline should be round as it is a GC.com cache

Version:
2021.09.14-NB

**Comment by fm-sys** [comment]
Just for reference: the issue exists for OSM as well as for GMap

**Comment by ztNFny** [comment]
duplicate of https://github.com/cgeo/cgeo/issues/11424

**Comment by Lineflyer** [comment]
Thanks...closing here then.
