### ISSUE TITLE
nearby search from cache returns caches around current position

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11666]
### Describe your problem!

From support ticket (and verified in a quick test): Doing a nearby search from cache detail page returns caches around your current position instead of caches around the cache's position.	

### How to reproduce?

- open a cache which is not close to your current position
- open menu => extra => "Caches im Umkreis"	

### Actual result after these steps?

c:geo will show you a list of caches around your current position (wrong value put into the filter)

### Expected result after these steps?

Show caches around the cache's position

### Reproducible

Yes

### c:geo Version

2021.09.08

### Additional Information

ticket 237974

**Comment by moving-bits** [comment]
Some findings:
- when doing a nearby search coming from a cache, `CacheListActivity` creates a filter from context `LIVE` - shouldn't it be `TRANSIENT` in that case?
- either way - how to "inject" the given coordinates into the filter? (in `CacheListActivity.onCreate` you can detect this situation by checking for `type` is `COORDINATE`, and the coordinates are stored in `coords`)

@eddiemuc?

**Comment by eddiemuc** [comment]
I have to admit that when implementing filtering I never actively thought about the use case "search nearest to cache". So it's no wonder that the behavior is undefined.

Consequently I don't remember whether we discussed the context for such a search. I think both `LIVE` and `TRANSIENT` could be argued. If someone sets a filter for `LIVE` (which is then active for all other online searches including nearby caches), it could be the case that he expects this filter also here.

As on how to implement this: get the `GeocacheFilter` from the right context (`transient` or `live`, depending on what should be used) and use it's `and` method to add a `DistanceFilter` with the cache coordinates set and no distance restriction.

**Comment by eddiemuc** [comment]
Come to think of it, this should even be easier because `CoordsGeocacheListLoader` already implements this pattern. You just have to make sure that in this issue's case this loader is instantiated with the cache's coordinates instead of the user's coordinates

**Comment by moving-bits** [comment]
Thanks @eddiemuc for the hints. Is it possible to use a transient filter, initialized with the values of current live filter?
And if using live filter (or a transient filter based on it): How can I override an existing `DistanceFilter`?

**Comment by fm-sys** [comment]
> Is it possible to use a transient filter, initialized with the values of current live filter?

Why should be make things more complex and inconsistent, as they need to be? We use the live filter for all online searches, BTW...

**Comment by fm-sys** [comment]
I've just tried to reproduce the issue, but everything is working totally fine for me... Except that the results are sorted by your current location instead of the location coords. This is already described in #11422

@moving-bits can you recheck your quick test? I would guess, the selected cache was simply not far enough away from your current location...

**Comment by eddiemuc** [comment]
> Thanks @eddiemuc for the hints. Is it possible to use a transient filter, initialized with the values of current live filter?

Actually, this is what happens if you use the LIVE filter context.


> And if using live filter (or a transient filter based on it): How can I override an existing `DistanceFilter`?

No need to check or override anything in the filter, just add a new DistanceGeocachingFilter as described before (and check CoordsListLoader where this is already implemented)

**Comment by moving-bits** [comment]
> I've just tried to reproduce the issue, but everything is working totally fine for me... Except that the results are sorted by your current location instead of the location coords. This is already described in #11422

I'm facing the same here currently, trying to reproduce the original issue for a while already. Strange. In my quick test I had used some cache app. 100 km away - maybe not far enough.

What confused me even more is a different artifact:
- I opened a list of my stored found caches and chose the most distant one (> 10000 km), and applied a nearby search.
- The resulting list was lab + earth + virtual only (for whatever reason).
- The filter was set to something like "10 cache types" and "not" + "inconclusive=yes" - something I cannot remember to have ever chosen.
- type filters in map quick settings were partly greyed-out.
- Deleting that filter using the filter icon in actionbar made everything come back to normal, but how did that filter come into existence?

This reminds me of one of the latest support tickets, where some user had a similar problem. Deleting the filter helped as well, but the user claimed that he had not created such a filter.

Hm, strange. Maybe too many weird support tickets lately, some of them cross-checked on my physical phone...

**Comment by fm-sys** [comment]
I have a fix for #11422 and will provide a PR... (will fix this issue as well)

**Comment by fm-sys** [comment]
> just add a new DistanceGeocachingFilter as described before (and check CoordsListLoader where this is already implemented)

`DistanceGeocachingFilter` can already handle any given coords and is correctly implemented. See:

https://github.com/cgeo/cgeo/blob/160751d06b9bd638c7d6b3463524de27fdef0af8/main/src/cgeo/geocaching/loaders/CoordsGeocacheListLoader.java#L20-L23

#11691 will fix the sorting issue...
