### ISSUE TITLE
Incorrect compact icons (vector versions)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11662]
With current nightly I just planned my caching trips for next days and stumbled upon some (partly not deterministic) wrong compact icons:

- Some found caches shown cache color instead of smiley
- DNF caches show smiley
- Some unfound caches show smiley

I could not yet clearly reproduce any (pre)condition for that to happen.
But it happens often and you might notice if you switch between compact and normal mode.

Blind guess would be, that some icons "change places with others" regarding their compact marker, so it depends how many and what kind of caches and status is involved on the map.

I will post screenshots with examples next week (when back home)

2021.09.14-NB
Android 11
Samsung S20

**Comment by ztNFny** [comment]
I think this was introduced by enabling the icon cache for dotMarkers as I haven't seen the issues in the weeks before. I'll take a look at what might be wrong there.

**Comment by ztNFny** [comment]
fixed by #11671

**Comment by Lineflyer** [comment]
PR has been merged. Closing.

@ztNFny You could use "Fix #11671 -..." in the commit title to autoclose the issue once the commit is merged to the base branch. This avoids forgetting to close it.

**Comment by bekuno** [comment]
> 
> 
> PR has been merged. Closing.
> 
> @ztNFny You could use "Fix #11671 -..." in the commit title to autoclose the issue once the commit is merged to the base branch. This avoids forgetting to close it.

@Lineflyer @ztNFny 
This is not fully correct. You need the magic words somewhere in commit. Using it only in the PR title is not enough.
Se e.g. the discussion in https://github.com/cgeo/cgeo/pull/11620#issuecomment-912862065 and around.

**Comment by Lineflyer** [comment]
Thats what I wrote, isnt it?

**Comment by bekuno** [comment]
> 
> 
> Thats what I wrote, isnt it?

You wrote: "In the commit **title**." 
There is no commit title. But e.g. Github is using the first line of a commit as a title.
The discussion before was about using the magic words in the **PR title**. This does not work, if you add the words to the PR title later on. 
You can create a commit with the magic text in the first line, and using the commit text as PR text. Then the first commit line becomes the PR title. And for the auto close mecanism you have the magic words in the commit.

**Comment by fm-sys** [comment]
If you target a PR to `master` it doesn't need to be contained in the commit message. In this case, "fix #xxxx" is working inside the **PR description** (not title!) as well...
