### ISSUE TITLE
"has user-defined waypoints" filter being missed

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11664]
### Tell us your idea!

A user from support misses the filter "has user-defined waypoints" (ticket 779609)

**Comment by Volthai7us** [comment]
Could you add more details about this issue?

**Comment by eddiemuc** [comment]
This is about extending the c:geo status filter with a "has user-defined waypoints" line:

![image](https://user-images.githubusercontent.com/6909759/150696979-83e6dc77-9033-404f-9ac5-c40fce4976ce.png)

Setting this filter should lead to filtering of caches having waypoints with/without user-defined waypoints.


Some implementation pointers:
* the Status filter is defined in class cgeo.geocaching.filters.core.StatusGeocacheFilter. There is an inner class StatusType, new filter for waypoints has to be added here. Filtering itself must be implemented in methods `filter(final Geocache cache)` as well as `addToSql(final SqlBuilder sqlBuilder)`. These methods implement the other status filters, they might serve as an example for the new implementation.
* For the filter-method: To do the actual filtering, access the Waypoints in the Geocache object and check if it has/hasn't any user-defined waypoints. Geocache.getFirstMatchingWaypoint method might be useful for that. Class Waypoint has a method isUserDefinedWaypoint to check
* For the SQL filtering: waypoints are stored in table cq_waypoints. Columns "type" set to "own" or cloumn "own" set to "1" denotes a user-defined waypoint

**Comment by Volthai7us** [comment]
Currently I am building the project. When It's done I will let you know. Btw may I ask you question if I face to with trouble?

**Comment by Volthai7us** [comment]
[volthai7us@volthai7us cgeo]$ ./gradlew build
Configuration on demand is an incubating feature.
> Task :cgeo-contacts:processDebugResources FAILED
> Task :cgeo-contacts:processReleaseResources FAILED
> Task :main:dataBindingMergeDependencyArtifactsBasicDebug FAILED

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':cgeo-contacts:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/home/volthai7us/.gradle/caches/transforms-3/8d6f628b62cf56c15d8d8a71f7b7297d/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
         

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':cgeo-contacts:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/home/volthai7us/.gradle/caches/transforms-3/8d6f628b62cf56c15d8d8a71f7b7297d/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
         

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':main:dataBindingMergeDependencyArtifactsBasicDebug'.
> Could not resolve all files for configuration ':main:basicDebugCompileClasspath'.
   > Could not find com.squareup.okhttp3:okhttp:5.0.0-alpha.3.
     Required by:
         project :main

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
113 actionable tasks: 23 executed, 4 from cache, 86 up-to-date




___________________________________________________________-

When building I am occurring with these errors

**Comment by moving-bits** [comment]
Did you happen to update dependencies in build.gradle file?

From the notes above you seem to use `core-1.7.0`, whereas c:geo uses `core-1.6.0` currently (androidx core lib, around line 390),
and for okhttp we are currently using `okhttp:4.9.3`.

Not sure if that would catch all three errors, but it's worth a try. Maybe reset your `build.gradle` to the one provided by the repository, don't update the dependencies, and retry the build.

**Comment by Volthai7us** [comment]
How can I change my core and okhttp version? 
I tried ./gradlew clean but It didn't change anything. Is there anyway to reset build.gradle?

**Comment by eddiemuc** [comment]
> How can I change my core and okhttp version? 
> I tried ./gradlew clean but It didn't change anything. Is there anyway to reset build.gradle?

Can you build using Android Studio?

Gradle should use the dependency libs as defined in the Gradle config (including their version), usually this happens automatically...

Did you follow the instructions for setup? E.g. did you create the local.properties and the key properties?

**Comment by eddiemuc** [comment]
...sorry, it is `private.properties`

**Comment by Volthai7us** [comment]
I followed intructions for setup. And I got same errors when I build using Android Studio too.

**Comment by bekuno** [comment]
> I followed intructions for setup. And I got same errors when I build using Android Studio too.

The easiest way to get to a running build might be to restart the installation procedure.
Please du not upgrade librarys.

Please open a separate issue for the installation problems.
Then we have this not mixed with the original Issue here.
I think the installation documentation could be made better and easier for new users.
Btw., you are using a Windows or Linux machine?

**Comment by Volthai7us** [comment]
I am using Arch Linux.

**Comment by Volthai7us** [comment]
@eddiemuc @moving-bits I can run after re-install as @bekuno said. I am ready to start working on issue.

**Comment by Volthai7us** [comment]
At beginning may I ignore addToSql method and only focus add a new button to Status page of Application?

**Comment by eddiemuc** [comment]
> At beginning may I ignore addToSql method and only focus add a new button to Status page of Application?

yes sure. If you ignore `addToSql`, then the filtering will still work - it will just lead to potentially too many caches loaded from the DB into memory (because filtering is not already done on querying the DB but only later in-memory)

**Comment by Volthai7us** [comment]
I added some lines taking example from other status filters. Like `count = addIfStillFits(sb, count, statusHasWaypoint, StatusType.HAS_WAYPOINT);` or '(statusHasWaypoint == null || (cache.getWaypoints().size() > 0) == statusHasWaypoint)'  
I assume getUserDisplayableConfig and addIfStillFits for display buttons. But I could not add Status page another button.

**Comment by eddiemuc** [comment]
View is added in class StatusFilterViewHolder.

A general tip: take a StatusGeocacheFilter.StatusType instance for something quite similar (e.g. HAS_TRACKABLE) and use Android Studios great "Find Usages" function. Then you have a list of all places which needs modification to add a new status filter line.

**Comment by Volthai7us** [comment]
![image](https://i.ibb.co/xzFGfCs/cgeo1.png)

I added button with icon. For now buttons are useless.

**Comment by Volthai7us** [comment]
![image](https://i.ibb.co/C7wf54p/cgeo-issue1.png)

Is it working correct except sql part?

**Comment by Lineflyer** [comment]
Looks like working as expected (according to the titles of your test caches). 
If you provide a PR the team can take a look code wise.

**Comment by Volthai7us** [comment]
I cannot provide PR. I got 
`Can't Create Pull Request
Push failed:
remote: Permission to cgeo/cgeo.git denied to Volthai7us.
unable to access 'https://github.com/cgeo/cgeo/': The requested URL returned error: 403`

this error.

**Comment by eddiemuc** [comment]
> I cannot provide PR. I got 
> `Can't Create Pull Request
> Push failed:
> remote: Permission to cgeo/cgeo.git denied to Volthai7us.
> unable to access 'https://github.com/cgeo/cgeo/': The requested URL returned error: 403`
> 
> this error.

Hi @Volthai7us, you need to create a branch on your personal fork of c:geo, push to this branch and create pull request from this branch to c:geo master

**Comment by Volthai7us** [comment]
Is there already cq_waypoint table or should I create it inside the addToSql method?

**Comment by moving-bits** [comment]
You are probably looking for `cg_waypoints` table, which already exists (note the `cg` instead of `cq` at the beginning of the table name - all tables in cgeo start with `cg` prefix)

**Comment by moving-bits** [comment]
Additionally: While in debug mode, you can use AndroidStudio to browse the database, see "app inspection" => "databases"

**Comment by Volthai7us** [comment]
`if (statusHasUserDefineWaypoint != null) {
    sqlBuilder.addWhere(sqlBuilder.getMainTableId() + ".own = " + (statusHasUserDefineWaypoint ? "1" : "0"));
}`

 I tried something like this. Am I even close?

**Comment by eddiemuc** [comment]
HI @Volthai7us , 

I don't know how familiar you are with SQL. The goal here is to add a WHERE clause which does select only caches having a user-defined waypoint. This means to add a WHERE statement which evaluates to TRUE if at least one row exists for the caches geocode in table `cg_waypoints` which has the values identifying the row a user-defined waypoint (which is column `own=1` or column `type = 'own'`). In the database, waypoints are stored in their own table because there's a 1:n relationship between caches and waypoints (one cache can have many waypoints).

The filter case is very similar to the `statusHasOfflineLog` case because offline log entries are also stored in a separate table from cache entries. Something like the following should do the trick (haven't compiled this though...):

```
if (statusHasUserDefinedWaypoint != null) {
                final String waypointTableId = sqlBuilder.getNewTableId();
                sqlBuilder.addWhere((statusHasUserDefinedWaypoint ? "" : "NOT ") +
                    "EXISTS(SELECT geocode FROM cg_waypoints " + waypointTableId + " WHERE " + waypointTableId + ".geocode = " + sqlBuilder.getMainTableId() + ".geocode AND (" + waypointTableId + ".own=1 OR " + waypointTableId + ".type = 'own'))");
            }
```

A little tip for debugging: set a breakpoint in `DataStore.java` line 3567. Here you can see the SQL statement generated to select the caches.

If you can't figure out this (and if @fm-sys doesn't mind), then it is also ok for me if you leave out the addToSql part, we merge this and I add the SQl stuff later in a separate PR.

**Comment by Volthai7us** [comment]
![image](https://i.ibb.co/smZNRsm/Screenshot-from-2022-02-04-22-10-50.png)

I directly copy-paste your code and change statusHasUserDefinedWaypoint to true. After closeing and starting in debug mode with breakpoint at DataStory.java line 3567. I think It is working.
