### ISSUE TITLE
Add cache name to "send message" (messagecenter) in cache details

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11677]
### Tell us your idea!

A user's request on support:
When following the "send e-mail" link when tapping in the cache owner's name in cache details, add the cache name (if possible). - Similar to using the "message this owner" on the website (although it's the message center in that case).

### Additional Information

ticket 644392

**Comment by Lineflyer** [comment]
AFAIK mailing a user also only opens a web site form. We can probably not (easily) inject this data there.

**Comment by ztNFny** [comment]
At least for PNs it's possible: https://www.geocaching.com/account/messagecenter?recipientId=<id>&text=<text>

**Comment by moving-bits** [comment]
Ok, I tried a couple of combinations of parameters for calling the email form, but it does not make any difference at all. Seems that adding the waypoint info is only possible for the message center.

So let's close here. Or do we want to support opening the messagecenter (in addition to email form)?

**Comment by ztNFny** [comment]
> At least for PNs it's possible: https://www.geocaching.com/account/messagecenter?recipientId=&text=

That's actually a feature of GClh userjs. if enabled it works the same way for mails. But hardly anyone will have the userjs on their mobile browser, so I think it's not possible to do anything useful here.
I vote for closing.

**Comment by moving-bits** [comment]
Just FTR: Even without or with deactivated GClh it'll work for message center. URL is something like https://www.geocaching.com/account/messagecenter?recipientId=bcb195e6-585a-44e8-af6e-0f03823f8b14&gcCode=GC4JH7P
(See link "message to owner" on top of a cache page).

But there's no equivalent for the email form, at least I wasn't able to find one. Which sort of makes sense, as there's no email link on the cache page. (Although link to owner has a waypoint parameter, but the cache owner page does not make use of it...)

**Comment by ztNFny** [comment]
> But there's no equivalent for the email form, at least I wasn't able to find one. Which sort of makes sense, as there's no email link on the cache page. (Although link to owner has a waypoint parameter, but the cache owner page does not make use of it...)

you have to enable it first, setting "settings_show_mail"

**Comment by moving-bits** [comment]
> you have to enable it first, setting "settings_show_mail"

Where can I set such a setting? Couldn't find it in gc.com's settings.
(I was talking about gc.com defaults, without gclh script, as we should not rely on that for c:geo core functions)

**Comment by ztNFny** [comment]
> > you have to enable it first, setting "settings_show_mail"
> 
> Where can I set such a setting? Couldn't find it in gc.com's settings.
> (I was talking about gc.com defaults, without gclh script, as we should not rely on that for c:geo core functions)

Sorry, misunderstood your previous message then.

**Comment by fm-sys** [comment]
> Or do we want to support opening the messagecenter (in addition to email form)?

We already support exactly this. So adding the geocode to the API call is definitely a valid request.

**Comment by moving-bits** [comment]
How to activate this? I can only see the "send email" link, no "send message" :-(
(Valid for long tapping on owner name in both cache details and in log entries)

**Comment by fm-sys** [comment]
> How to activate this?

The cache needs to be downloaded/refreshed within cgeo.

**Comment by moving-bits** [comment]
> > How to activate this?
> 
> The cache needs to be downloaded/refreshed within cgeo.

Ah, I see, thanks for the hint. Created a PR #11690 for adding gccode to links to message center.
