### ISSUE TITLE
different opacities on emojis

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11673]
### Describe your problem!

In the emoji selection dialog all emojis but the circles have partial opacity. Looking at the code I can see the implementation but I can't see any reason WHY this is done. The opacity settings were introduced by https://github.com/cgeo/cgeo/commit/ab5c5dd0dd712429016ea70286e2b7f83503d851

Imho opacity should be 1 for all emojis, being faded makes it harder to identify them as it lowers contrast.

Screenshot - all emojis but the circles are faded
![signal-2021-09-16-122136_001](https://user-images.githubusercontent.com/1258173/133595791-ca3077a8-c05e-4d5d-9da2-591e9cc36535.jpeg)

### How to reproduce?

-

### Reproducible

Yes

### c:geo Version

2021.09.15

**Comment by moving-bits** [comment]
Opacity was introduced to get filled circles in different intensities. But it should be applied to the circles only (2nd tab).

IMHO the real error is that some non 0%-opacity gets applied to all non-circle emojis in light color mode.

**Comment by ztNFny** [comment]
> Opacity was introduced to get filled circles in different intensities. But it should be applied to the circles only (2nd tab).

The same should be possible to achieve by using a lighter/darker color. If you agree I'll look into a) removing the opacities completly, b) adding some more colors to the circles to compensate.

**Comment by moving-bits** [comment]
Sure, give it a try. In settings - map - color for xxx we have a similar approach already (using color palette).
Be aware of migration of existing user-defined cache icons, though.

**Comment by moving-bits** [comment]
BTW: What I do not understand (and haven't found on a quick glance this morning): Why is the behavior different between light mode and dark mode? In dark mode opacity gets applied only to the circles, not to the other emojis, whereas in light mode, all non-circles get some opacity being applied to. Strange...

**Comment by ztNFny** [comment]
> Why is the behavior different between light mode and dark mode? 

It isn't for me, icons are translucent in dark mode as well
![image](https://user-images.githubusercontent.com/1258173/133909169-adb7bddc-b2a9-4907-a581-d4464d249050.png)

**Comment by ztNFny** [comment]
In the end it was a simple fix - once the problem was found. The text color for that dialog apparently has some alpha channel and all those emojis are just text.
PR submitted.
