### ISSUE TITLE
hide visited waypoints in waypoint-list

### ISSUE THREAD

**Issue by pet0etie** [cgeo/cgeo#11681]
### Tell us your idea!

when walking a multicache there can be a lot of waypoints (including parking spots, trailing heads, ...)
for multicaches with lots of waypoints i need to scroll down to get the coords and info about the next waypoint to visit
this scrolling is getting annoying to do every single time a specially when u get to waypoints that are at the end of the list

there should be an easy option not to show the visited waypoints in the waypoint-list

### What solution would you suggest?

there is already a possibility to mark a waypoint as "visited"
- long-click the waypoint and choose the "visited-option from the popup-list
- single-click the waypoint and choose the (un)check the "visited" checkbox + save changes

![screenshot_1c](https://user-images.githubusercontent.com/90089787/133893897-5a9a8bc5-4db8-498e-b7ae-10115ce97370.png)

that way the waypoint gets a visited green-mark-indicator 

![screenshot_1d](https://user-images.githubusercontent.com/90089787/133893818-d355ab23-a6a7-49f3-9fb9-eb13bea5481c.png)

there should be an easy option to hide those visited waypoints in the waypoint-list
when marking a waypoint as visited, the next waypoint is always on top of the list and scrolling is avoided

the ideal option would be a checkbox in the waypoint-list to hide/unhide those visited waypoints

![screenshot_1a](https://user-images.githubusercontent.com/90089787/133893907-52629b09-3ee8-40b6-8b98-c5a5674435bc.png)
![screenshot_1b](https://user-images.githubusercontent.com/90089787/133893909-6a6891ff-c2f2-4ae6-bf86-e0b9dff89181.png)

**REMARK FOR DEVELOPMENT : 
this feature has already been created as a first-time-contribution to the c:geo-app
looking forward to push this to the master soon ...**

### Is there an alternative?

scrolling ?

**Comment by fm-sys** [comment]
> REMARK FOR DEVELOPMENT :
> this feature has already been created as a first-time-contribution to the c:geo-app
> looking forward to push this to the master soon ...

Cool, looking forward to your pull request 👍

**Comment by pet0etie** [comment]
PR has been made : https://github.com/cgeo/cgeo/pull/11697
curious about any comments from the "core team"
