### ISSUE TITLE
Log icons in logbook

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11684]
In Logbook tab display an icon for each log to indicate the type of log.

Related to #11646 

### Todo

- [x] Decide on a layout
- [x] Add icons for all logtypes

**Comment by ztNFny** [comment]
@Lineflyer could you please assign to me?

**Comment by fm-sys** [comment]
Done, although I was not addressed ;-)

**Comment by ztNFny** [comment]
Without changing too much in the dialog there's 3 positions that somewhat make sense to me. What do you think?

Option 1 - Icon before status name
![image](https://user-images.githubusercontent.com/1258173/134206941-5a12633b-aed4-4180-97a5-7fbaa28e5d7f.png)

Option 2 - Icon before name
![image](https://user-images.githubusercontent.com/1258173/134208476-8c1598b1-3647-4d43-9caa-d0dda1a40633.png)

Option 3 - Icon on the right 
![image](https://user-images.githubusercontent.com/1258173/134209227-ee09219c-dd14-4366-8872-53dfe2e2485e.png)

**Comment by ztNFny** [comment]
And the header view (not yet formated in any meaningful way)
![image](https://user-images.githubusercontent.com/1258173/134214960-d93d1dbe-d0cc-4f81-b667-55bd87598709.png)

**Comment by Lineflyer** [comment]
> And the header view (not yet formated in any meaningful way)

Also looks brilliant and more compact and easier to "read" as the current textual version.
Maybe a tap action to show the meaning of the icon could be helpful for those who don't know all the icons?

**Comment by ztNFny** [comment]
> IMHO option 3 looks best, but maybe not totally right aligned but a little more to the left to avoid overlapping with the fast scroll bar. Also in your graphic the emoji is smaller than the text left but should (for more symmetric look) have the same size (as in option 2)
> 
> Option 1 could be problematic on large fonts/small screens.

After some more testing I'd prefer option 1 - but the problem is with the long log texts. I removed lines=1 in favor of maxLines=3 but then it looks very strange, see screenshot. Any idea? I'm not the most experienced with layout stuff.

Reason I like 1:
- it makes sense to attach the icon to the text, that also helps in recognizing the icon in other places
- in upper right (option 3) it always looks a bit off, even if it's in the - from a layout point of view - correct place.

option 2 is out :-)

![image](https://user-images.githubusercontent.com/1258173/134226007-eb6c5c19-27de-479c-9ceb-d31c1772ff9e.png)

> Maybe a tap action to show the meaning of the icon could be helpful for those who don't know all the icons?

Done

**Comment by eddiemuc** [comment]
What about a 4th option:
* Remove the textual log type completely
* Instead, add the log type symbol as first row (over log date and cache count), right-aligned

**Comment by eddiemuc** [comment]
Or redesign the log list to something like zhe Geocaching app (includes the users avatar pic), I think their design layout is very  nice there

**Comment by ztNFny** [comment]
> What about a 4th option:
> 
>     * Remove the textual log type completely

For rarer log types (NM, NA, Unarchive, ...) that could pose a challenge for the user to recognize what it is. Also for new users they won't even know the "normal" types.

**Comment by bekuno** [comment]
The colored vertical stroke means the same as the log type text and now the log type icon - should we remove them now?

**Comment by ztNFny** [comment]
> The colored vertical stroke means the same as the log type text and now the log type icon - should we remove them now?

I was thinking about that too, but it looked kinda off when I removed it. Maybe it's just that i'm so used to it...
How about as a first step for the next release implement something small, like option 1, then for a future release plan a redesign of the whole tab (of course if someone has the time now also sooner)?

**Comment by Lineflyer** [comment]
> Or redesign the log list to something like zhe Geocaching app (includes the users avatar pic), I think their design layout is very nice there

I am somehow against being like all other apps. 
Important is a well understandable logbook screen and IMHO our current logbook view is fine...the icon would just be an addition for e.g. quickly spotting that DNF or alike.

**Comment by ztNFny** [comment]
Lets do something small for now. The next releases will bring big UI changes anyway - icons, bottom nav - let's let the users get used to that and afterwards we can talk about a bigger redesign of the logs page again.
And we need some tasks for 2022 too 😉
