### ISSUE TITLE
PQ and bookmark list menu use same icon

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11685]
### Describe your problem!

On my tablet (where the action bar has more space) I do now see two of those "suitcase with magnifier" icons has the new bookmark list menu uses the same icon as the PQ list menu.

### How to reproduce?

Use portrait mode on a large screen device in the main menu

### Actual result after these steps?

You will see two of those icons after each other

### Expected result after these steps?

Have different icons 
Bookmark list could maybe something like a checklist with magnifier (or similar)

### Reproducible

Yes

### c:geo Version

2021.09.14-NB

**Comment by Lineflyer** [comment]
![image](https://user-images.githubusercontent.com/949669/133911047-c95e11e8-11a8-48fd-a33a-955b2d9a4dee.png)

**Comment by fm-sys** [comment]
IMHO not really worth to fix as it will be obsolete with the bottom navigation anyway. Or we could add `showIcon=never` for the time being...

**Comment by moving-bits** [comment]
I would either ignore the issue until bottom navigation is implemented or go for different icons, but I would not hide the icon.

material.io provides the following icon for bookmarks:

![image](https://user-images.githubusercontent.com/3754370/133921741-7600f271-1609-4267-87fe-06bbfcd3c7e0.png)
