### ISSUE TITLE
[vectorIcons] Icon color in stored list changes dynamicly when scrolling

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11699]
### Describe your problem!

Open/create a list with more entries than the space (you have to scroll to more entries).
You should have caches with different types.
The icon color for all GC caches (independent of the type) are in the color of the last entry.
If you scroll and the type of the last entry changed then all GC caches are changing their color.
The same is for OC caches.

### How to reproduce?

Open/create a list with more entries than the space (you have to scroll to more entries).
You should have caches with different types.
Scroll in the list.

### Actual result after these steps?

All GC caches have the same color, and changing when scrolling depending of cache type of the last visible entry.
The same for OC caches.

### Expected result after these steps?

Icon color is correct and does not change

### Reproducible

Yes

### c:geo Version

2021.09.20-NB

**Comment by ztNFny** [comment]
Can't reproduce. All my lists have 100-4000 caches so I always have to scroll.
I've occasionally seen some corruption on the map as reported in https://github.com/cgeo/cgeo/issues/11545, but never wrong colors.

**Comment by bekuno** [comment]
Here is a video showing the problem:
https://user-images.githubusercontent.com/32555742/134068766-719c08ce-cbf9-469f-be36-c5802d691187.mp4

**Comment by ztNFny** [comment]
Looking at the code that doesn't make any sense at all. Background color and foreground icon are set at the same time, it shouldn't be possible for them to deviate. And once a specific icon is rendered it is cached in overlaysCache and should never be recalculated.

Is it calling MapMarkerUtils:createCacheMarker() for the icons changing color while scrolling?

**Comment by fm-sys** [comment]
@bekuno can you pls post your system information (mainly the android version)?

**Comment by bekuno** [comment]
> 
> 
> @bekuno can you pls post your system information (mainly the android version)?

It is a Samsung Note8 with Android 9.

**Comment by fm-sys** [comment]
> It is a Samsung Note8 with Android 9.

Hm, @Lineflyer's device was Android 7, but I cannot reproduce on Android 5, 10 nor 11. 

I've just installed an Android 8 emulator, and indeed: I can see the same issue! So the issue seem to be android 7-9... _Very interesting_ :-/

**Comment by fm-sys** [comment]
PR #11780 will fix the issue...

**Comment by bekuno** [comment]
> 
> 
> PR #11780 will fix the issue...

Tested - works perfectly :-)
