### ISSUE TITLE
Unify map zoom controls 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11696]
### Tell us your idea!

Currently we have two different zoom controls:

![Screenshot_20210920_113428_cgeo geocaching](https://user-images.githubusercontent.com/64581222/134013196-1c132886-3761-45af-80dd-5f4fd21771b5.png)
![Screenshot_20210920_113300_cgeo geocaching](https://user-images.githubusercontent.com/64581222/134013197-17ed2912-fb73-4617-9848-935ef05835fb.png)

### What solution would you suggest?

We could replace both with two FAB's (floating action buttons)

![Screenshot_20210920_154449_org mozilla firefox](https://user-images.githubusercontent.com/64581222/134013343-a882512e-a5f5-424c-9ab9-c99ece8f3f04.png)
_Image copied from  #8057_

**Comment by ztNFny** [comment]
Of the 3 screenshots I like Google Maps' buttons design best. Transparency that allows visibility of what's below + clean design.

**Comment by Lineflyer** [comment]
Indeed, the transparency is nice..not sure though if we can reuse the same buttons on the other maps.

**Comment by moving-bits** [comment]
Maybe we can introduce our own buttons for both map types. GM's style is the best of the three shown here, IMHO - it's clear, not too much detail. Maybe we can combine it with our iconized button style for even more consistency.

If we switch to such a button arrangement, this could also help with placing our new quick buttons (see #11771), as it frees some space at the bottom. We could then place the new quick buttons at the bottom as well, for both map types, which BTW would also make the animations (bottom sheet / popup menu) more logical.

**Comment by moving-bits** [comment]
So far I have been able to change the zoom controls for OSM to this:

|OSM (new)|GM|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/135752083-4d5813d5-99bc-489f-a0e6-fbcc121ccf00.png)|![image](https://user-images.githubusercontent.com/3754370/135752114-6ac72aa3-e6f5-44a2-ae14-bc454fa9580f.png)|

(My GM is broken, so I cannot show you transparency level for GM zoom controls for comparison.)

Still trying to figure out to move the zoom controls a bit up + left, to get them close to GM controls. Not sure if it's possible, though.

**Comment by fm-sys** [comment]
> I have adapted the zoom controls for OSM to look more similar to those of GM

I would give them a bit more alpha, IMHO they look too transparent in the screenshot. But looks great already 👍

**Comment by moving-bits** [comment]
Adapted alpha from 80 to C0:
![image](https://user-images.githubusercontent.com/3754370/135754935-3f7dd89b-d2a7-4aa2-8eb3-4169c5d2707d.png)
