### ISSUE TITLE
add pin marker to cache when waypoint(s) but no final defined

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11700]
A additional idea came in my mind to cover the situation when a waypoint exist which is no Final/Parking/Reference waypoint. But this should go to another Issue and needs fine tuning.
~~~
if (not cache.hasFlag && cache.hasStationWaypointWithCoords) {
  addPin
}
~~~

_Originally posted by @bekuno in https://github.com/cgeo/cgeo/issues/11659#issuecomment-922456075_

**Comment by fm-sys** [comment]
Especially when implementing this, we should also take a look at the compact icons for correctedCoords, hasFinal and hasUserWaypoint.

**Comment by ztNFny** [comment]
What is the usecase for that?
Many multis have stages with coordinates already defined, then there's caches with trailheads, those would match that code. In neither case I see the added value of knowing that they have a waypoint when looking at the overview map.

**Comment by bekuno** [comment]
If you see it on the map then you know that the cache coordinate is not the place where you have to go to. Instead you know that you have to look for the valid waypoint.

**Comment by ztNFny** [comment]
> If you see it on the map then you know that the cache coordinate is not the place where you have to go to. Instead you know that you have to look for the valid waypoint.

For a multi with multiple stages I still have to go to the listing coords (S1) before I care about the others. And the fact that there are more waypoints i already know by the type.
For trailsheads or refernce points the meaning can be very different from cache to cache. I've seen tradis with waypoints like "from here you have a great view onto ...". 
I don't think it adds much information to the map.

**Comment by Lineflyer** [comment]
> If you see it on the map then you know that the cache coordinate is not the place where you have to go to. Instead you know that you have to look for the valid waypoint.

I don't think this is any relevant usecase and will just flood many caches with such marker.
If we use a marker it should only be for very specific infos (has a note, is on final, is found, etc) but not for pure existence of waypoints.

Many caches might or might not have additional waypoints. We cannot judge their relevance. Lets limit such features to existing final waypoints (if at all...see other issue).

**Comment by bekuno** [comment]
Let´s close this Issue now as this idea seams not good enough.
