### ISSUE TITLE
wordvalue calculation when editing waypoint

### ISSUE THREAD

**Issue by pet0etie** [cgeo/cgeo#11708]
### Tell us your idea!

when making a multicache-walk it happens more than once that the wordvalue of a sentence/word//letter has to be made
wouldn't it be great if we can do that in the waypoint-editing screen directly instead of switching to other websites (like geocachingtoolbox.com) to calculate it ?

### What solution would you suggest?

calculate the wordvalue of the usernote-text directly in the waypoint-edit-screen

![afbeelding](https://user-images.githubusercontent.com/90089787/134247471-a025ecba-6739-4636-bf98-f86083dd4b04.png)

and also have the possibility to switch between the 4 most-used-wordvalue-possibilities

![afbeelding](https://user-images.githubusercontent.com/90089787/134247668-8233c507-680c-43b9-9a95-4b07b684cda1.png)

### Is there an alternative?

switching to external websites like geocachingtoolbox

### Additional Information

the example code has already been created if this seems a good idea to implement

**Comment by ztNFny** [comment]
There's some calculation stuff being developed in https://github.com/cgeo/cgeo/issues/11520 right now

**Comment by eddiemuc** [comment]
Correct, #11520 should target this, but in a larger context (not restricted to waypoints)

**Comment by eddiemuc** [comment]
Closing as duplicate
