### ISSUE TITLE
Forbid ellipsis (`...`) for Difficulty and Recent Logs rows

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#11709]
Basing on the current discussion inside #11676, we identified two rows with ellipsis (...) being shown in the german translation of the cache details page.

So for the two rows difficulty/Schwierigkeit and recent logs/Neuste Logs this setting should be disabled to gain the space for showing the complete line:

![134245286-0c5ef856-c7c4-4d21-816b-b093f32cd60c](https://user-images.githubusercontent.com/4508228/134253689-f5926375-9ac9-48bb-8660-b472ead7d024.jpg)

~~~
We can forbid the ellipsis (`...`) in general for this row to gain space. IMHO its better to show whats fitting instead of wasting three characters by three dots.

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/11676#issuecomment-924375979_

**Comment by Lineflyer** [comment]
If we decide so, we should do it for all captions (first column) on that page.
Cutting off depends on length of translation and font size and could therefore happen for all these texts on some device and on some language.

**Comment by moving-bits** [comment]
I would rather stay with ellipsis - cutting off text without any visual indicator just looks broken from a typographic point of view.

We could try to further shorten some texts, e. g. "logs" instead of "recent logs", but depending on language there will always be some texts not fitting.

I propose to close this issue.

**Comment by Lineflyer** [comment]
Do really think so?
Please be aware, that e.g. in the above right example the texts would fit as exactly three characters are missing.
Shortening texts can never be a good solution (and would also not provide the same information "Recent" is important...not just "logs").

**Comment by SammysHP** [comment]
This is not a fixed-width font, thus three characters need usually more space than three dots `...` or even an ellipsis `…`.

Isn't there a way to fade out the text?

**Comment by moving-bits** [comment]
> Do really think so?
> Please be aware, that e.g. in the above right example the texts would fit as exactly three characters are missing.

This may be so in this case, but by pure chance - depending on screen resolution, screen density, font size, and, last but not least, selected language.

> Shortening texts can never be a good solution 

With "shortening" I do not mean abbreviating (that we should avoid) but trying to find shorter lables which still do convey the meaning.

> (and would also not provide the same information "Recent" is important...not just "logs").

Maybe "Recent" would be better in that specific case. But maybe there are no shorter texts for today's labels and their translations. Then we should stay with ellipsis, IMHO. (Which, BTW, is built-in default behavior on Android.)

**Comment by Lineflyer** [comment]
On most of my devices it fits anyway. 

@wolverine007 
What device and what font settings did you use in your screenshots?

**Comment by murggel** [comment]
On my device Samsung S20 medium font it does not fit

2021.09.20-NB-60abd64


![Screenshot_20210922-212834_cgeo.jpg](https://user-images.githubusercontent.com/70113341/134409305-d7d43f8e-d295-4304-8db0-1242d5c0122b.jpg)

![Screenshot_20210922-212910_Settings.jpg](https://user-images.githubusercontent.com/70113341/134409322-3fea29cb-6bba-4fea-8be5-e828ff2866ba.jpg)

**Comment by moving-bits** [comment]
This ist partly due to our increased font sizes with the new UI. IIRC we already increased the width of the left column a bit during that process, but did not want to spend too much space on it to have more space available for the content (and to support lower resolution devices as well).

One possibility to take this into account could be to use the current layout file for this layout for lower-res-devices, and create a derived layout with a somewhat wider left column for high-res-devices. (There is a mechanism built-in in Android to support auto-selecting the correct layout file depending on resolution/dpi etc.)

**Comment by Lineflyer** [comment]
Or really just close this issue, as other solutions would increase complexity and maintenance effort and still we cannot suite all needs....mmh.

Regarding the new recent logs feature we could then indeed name it "Recently" or "Recent".

**Comment by wolverine007** [comment]
On the screenshot pasted by @murggel there are next to Schwierigkeit two addional fields covered with the ellipsis, while the words are facing the same length like the ellipsis.

The idea with different column sizes for higher resolutions sounds also valid to me.
When you are taking a look into my screenshot for font size "S" you could see, that there is plenty of space inside the right column and I already picked a cache with a really long cache title.

So maybe we could just give it a try with extending the left column by some px for higher resolutions and check what happens afterwards?

**Comment by ztNFny** [comment]
> Regarding the new recent logs feature we could then indeed name it "Recently" or "Recent".

"Recent Logs" is shorter than "Coordinates", so that shouldn't cause any issues.
For other languages imho it's up to the translators to find a fitting term.

**Comment by pet0etie** [comment]
for the value-ellipsis i guess a simple 

`android:layout_alignParentRight="true"`

would help to use the full width

`<TextView
        android:id="@+id/value"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        **android:layout_alignParentRight="true"**
        android:layout_centerVertical="false"
        android:layout_marginRight="5dip"
        android:layout_toRightOf="@+id/name"
        android:gravity="center_vertical"
        android:textColor="@color/colorText"
        android:textIsSelectable="false"
        android:textSize="@dimen/textSize_detailsPrimary"
        tools:text="value" />`

**Comment by Lineflyer** [comment]
> android:layout_alignParentRight="true"

IMHO this does not make a difference as we use a fixed value of 90px for

**Comment by Lineflyer** [comment]
I mean:
<TextView
android:id="@+id/name"
android:layout_width="90sp"
android:layout_height="wrap_content"
android:layout_alignParentLeft="true"
android:layout_alignParentTop="false"
android:layout_centerVertical="false"
android:layout_gravity="left|top"
android:layout_marginRight="8dip"
android:ellipsize="end"
android:gravity="right"
android:lines="1"
android:scrollHorizontally="false"
android:text="@null"
android:textIsSelectable="false"
android:textSize="@dimen/textSize_detailsPrimary"
android:textColor="@color/colorTextHint"
tools:text="property"/>

**Comment by Lineflyer** [comment]
IMHO its a rather good solution as the column zooms with the text.

On large fonts the left column expands and gives room while the right column is multi line anyway:
![image](https://user-images.githubusercontent.com/949669/134769244-807999c2-73ab-45a9-ba4a-39451ec2e29a.png)


On default font it looks like this:
![image](https://user-images.githubusercontent.com/949669/134769267-54f0d495-a46b-46af-bd9e-77a02c0d8141.png)

On very small fonts:
![image](https://user-images.githubusercontent.com/949669/134769276-8c8fdfbd-c246-40a5-92d6-039617fb6ac6.png)
