### ISSUE TITLE
changelog_release is out of sync

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11716]
@moving-bits 
Coincidently I have seen, that `main/res/raw/changelog_release.md` is out of sync.
Theoretically it should be filled on `release` and (due to merge on `master`) be identical on `master`.

But for some reason the content is totally different. 
I did not investigate this yet, but what might have happened?

Could that explain the change log "problem" you have seen after merging branches?

**Comment by moving-bits** [comment]
Hm, I guess it was me who deleted parts of it. But sync problems did already happen before  IIRC.

I need to come back to the whole changelog procedure anyway, and starting after next release could be a good point in time. I'll try to rewrite the concept over the weekend, taking into account our (my) updated understanding of how git merge drivers work...

**Comment by Lineflyer** [comment]
I provided a PR to restore. Feel free to merge.
