### ISSUE TITLE
Lab caches imported from lab2gpx can no longer be set as found

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11718]
### Describe your problem!

A user claims, that he once was able to set lab caches he imported from lab2gpx manually to "found".
Since current release this is no longer offered by c:geo

### How to reproduce?

- Import GPX from https://gcutils.de/lab2gpx into c:geo
- Open details such a lab cache 
- Open Menu

### Actual result after these steps?

Menu does not offer "Set as found"

### Expected result after these steps?

Menu should offer "Set as found"

### Reproducible

Yes

### c:geo Version

2021.09.08

**Comment by moving-bits** [comment]
This is because lab2gpx uses "LC" as prefix per default, which is assigned to TerraCaching connector (IIRC), and TerraCaching does not support setting found state.

Maybe we need to reserve a separate prefix for which users can import arbitrary caches, and allow setting found state for it.
Or we do allow setting found state for TerraCaching connector (which is offline-only anyway, AFAIK).

**Comment by Lineflyer** [comment]
Why not. Setting Terracaching as found is meaningful as well and implicitly solves the lab2gpx case.

**Comment by fm-sys** [comment]
TerraCaching geocodes have a max length of 5 IIRC, so Lab2Gpx caches are probably rather maped to the `UnknownConnector`

**Comment by eddiemuc** [comment]
Also, it would be wrong IMHO if imported lab caches would be interpreted by c:geo as coming from a different connector than the GC lab cache connector. A solution could be to convert LC-codes into AC-codes on import.

**Comment by Lineflyer** [comment]
I imported a lab2gpx gpx file into c:geo (current nightly).
It shows up as hexagonal icons with lab cache icon and cache type "Adventure Lab Cache":
![Screenshot_20210923-184109_cgeo](https://user-images.githubusercontent.com/949669/134548846-2926a74b-5998-4003-8bb8-e240887774c0.jpg)

You might tell me what that means in terms of used connector..

**Comment by Lineflyer** [comment]
Or we ask https://github.com/mirsch/lab2gpx whether they can change to AL instead of LC if this is the trigger determining the connector on our side?

**Comment by Lineflyer** [comment]
I have just seen that the prefix for the geocode is user defined on https://gcutils.de/lab2gpx/.
I will try with AL. If it works then, this solution should be sufficient for our users IMHO.

**Comment by Lineflyer** [comment]
Tested and working.
I will add a FAQ entry, that users shall set the prefix to "AL" while generating the gpx file on that webpage. 

Closing here :)
