### ISSUE TITLE
OC websites shut down

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11710]
### Describe your problem!

~~~
06:37:53  cgeo.watchdog.WatchdogTest > testGeocachingWebsites[android-28(AVD) - 11] [31mFAILED [0m
06:37:53  	java.lang.AssertionError: Failed to get response from geocaching website OpenCaching.NO/SE
06:37:53  	at cgeo.watchdog.WatchdogTest.checkWebsite(WatchdogTest.java:83)
~~~

The service seems to be unusable for quite some time already.
We can remove the support of this OC site.

### How to reproduce?

See CI, eg. https://ci.cgeo.org/job/website%20tests%20(release)/9962/console

### Reproducible

Yes

### c:geo Version

since https://ci.cgeo.org/job/website%20tests%20(release)/9960/ (21.09.2021, 22:33:38)

**Comment by Lineflyer** [comment]
Do we have any information about their final shutdown?

Another question:
We do not seem to support authentication to that platform. What are the features we currently support?

**Comment by Lineflyer** [comment]
According to https://wiki.opencaching.eu/index.php/Node_IDs the norwegian and swedisch nodes are shutdown since a long time (2014).

It looks like there might have been a redirect to oc.de in place, which is now shut down as well?

Anyway it would be interesting to me to learn why we have those in our website tests after all / what features we supported for those nodes?

**Comment by bekuno** [comment]
The last wayback snapshot for opencaching.se without redirection to opencaching.de was at July 24, 2014, see https://web.archive.org/web/20140724162909/http://www.opencaching.se/.

Later in 2015 (between May and July) the references to oc.SE and oc.NO the OC instances list on the OC websites were removed.

**Comment by bekuno** [comment]
Also the websites opencaching.it and opencaching.fr are not more active.
And opencaching.es is a redirection to opencaching.de.

For these changes see also https://github.com/OpencachingDeutschland/oc-server3/pull/839 .

I changes the issue title to reflect all changes.

**Comment by bekuno** [comment]
Also some time ago the former spain OC site opencachingspain.es was moved to opencaching.es.
