### ISSUE TITLE
Differentiate downloads between metered (GSM) and unmetered (wifi) connections

### ISSUE THREAD

**Issue by ericzolf** [cgeo/cgeo#11729]
### Tell us your idea!

c:geo doesn't make the difference between metered and unmetered networks, causing potentially delays and costs on metered / GSM networks, slower and costly (especially in foreign countries).

### What solution would you suggest?

For all options about downloading data, offer different options for metered and unmetered networks, e.g.

- Offline data
    - save images always/never/only on unmetered
    - list load limit, differentiate between metered and unmetered limits
- Map
    - Automatic download always/never/only on unmetered
- Services
    - Login always/if necessary/only on unmetered (though I personally don't mind the little amount of data to login)

### Is there an alternative?

Change the options when changing network, which isn't practical...

### Additional Information

I think that _explicit_ actions like searching for caches or saving a cache should remain unchanged and always possible.

**Comment by ericzolf** [comment]
Ups, forget about the "list load limit", I thought it was the max number of caches to list from the Internet (rather than from database). Though adding such a limit would IMHO also make sense.

**Comment by fm-sys** [comment]
> I thought it was the max number of caches to list from the Internet. Though adding such a limit would IMHO also make sense.

We have something like this when refreshing lists with more than 100 (?) caches

![Screenshot_20210926_132516_cgeo geocaching](https://user-images.githubusercontent.com/64581222/134805760-dbb50774-963e-4f42-9d38-264ddb5bf2b7.png)

**Comment by eddiemuc** [comment]
Teammeeting 10.3.24: meanwhile we have this differentiation for big downloads (map, routing data). We also have above security question for large cache refreshes. Issue is considered done. PLease reopen if this is seen differently.
