### ISSUE TITLE
Icon feedback - Earth cache, CITO

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11721]
A few days ago I posted a sneak peak screenshot of the new icons to Facebook.

Now I tried to summarize the feedback and identify the top suggestions/critical feedback.
AFAICS it concentrates on three things:

1. A major percentage of users provided very positive feedback, only a few which liked the old multi-color icons more and think the new ones are to boring. But this is a clear minority in this non-representative survey anyway.
2. Earth cache icon: Many users provided feedback, that the earth cache icon is a) not easily recognizable and/or b) not easily distinguishable from virtual caches. Some users mentioned, that the yellow/orange core was helpful in the old icon.
3. Multi cache icon: Some users provided feedback, that they don't understand the icon respectively think its to far away from the old icon and/or the icon used in the website and in other apps.

@ztNFny 
What do you think regarding this feedback.
AFAIR you had multiple proposals for multi cache. Not sure about earth cache...

**Comment by ztNFny** [comment]
Took a look at the Facebook comments and there's 3 kinds of comments:
Earthcache icon: 4 comment with a total of 16 upvotes
More / Different background colors: 2 comments with a total of 6 upvotes
Multi: 1 comment, no upvote

So let's consider EC and colors.

EC: I tried to keep the general scheme of having only white for the icon itself. If we want to stick with that we can only tune the icon. I looked into some icons for "geology", like a pickaxe or a rock, but nothing really says "earthcache" to me there. So an "earth" is probably best suited to convey "earthcache". Going with something like the original EC icon with the cutout simply doesn't work in monocolor either, you'll just get something that looks like a 3/4 circle.

Background colors They are currently grouped by whether/where the logbook is:
- Green = at listing -> Tradi
- Orange = multiple waypoints -> Multi
- Dark Blue = you have to do something to get the logbook -> Mystery, WIG, Letterbox
- Light Blue = no logbook but (usually) photo -> Virtual, EC, Webcam
- Red = Event
- Light green = special/rare stuff -> HQ, APE, Maze
- Yellow = user defined
Of those categories imho the only one that isn't clear is Letterbox - that could be assigned to orange or dark blue. With a green-field approach I'd have used orange as it's closer to a multi, but GC is using blue and I think it's best to be aligned with the biggest platform there.

But as the color is majorly criticized in the context of the EC icon maybe it's not really 2 issues but only one -> people are used to the EC icon being colorful and standing out. So we have to ask ourselves the 1 question: 

1. Change EC (as the only icon then) to a multi-colored icon
2. keep it monocolor (and maybe try to tune the icon a bit)

**Comment by fm-sys** [comment]
Interestingly enough, GC uses a multicolor icon for EC while all others are monocolor.

![Screenshot_20210924_164418_com groundspeak geocaching intro](https://user-images.githubusercontent.com/64581222/134694435-1748c469-9f8e-4fe3-af63-3217a933cd49.png)

Maybe we can use a different background color for EC's, e.g. brown seems to be quite fitting (BTW used for "locationless" on GC).

![Screenshot_20210924_164426_com groundspeak geocaching intro](https://user-images.githubusercontent.com/64581222/134694962-b12dff6a-9117-4c61-897d-a3aa704041a8.png)

For Multis, maybe we can design a more well known "multiple boxes" icon:

![Screenshot_20210924_164349_com groundspeak geocaching intro](https://user-images.githubusercontent.com/64581222/134695144-17334cfd-d593-488e-b88a-7652ec583499.png)

**Comment by ztNFny** [comment]
I don't see a reason to touch multi. There's only 1 comment with no upvotes about it.

**Comment by ztNFny** [comment]
> Interestingly enough, GC uses a multicolor icon for EC while all others are monocolor.

Maze is also multicolor 😉

**Comment by bekuno** [comment]
We should also be aware that the compact icons distinguish optical on the map.

**Comment by Lineflyer** [comment]
> 1. Change EC (as the only icon then) to a multi-colored icon
> 2. keep it monocolor (and maybe try to tune the icon a bit)

For the sake of keeping a common style (monocolor) we should look into that option first, maybe you could try to bring in this "cut out" earth piece in the monocolor version?
![image](https://user-images.githubusercontent.com/949669/134768337-dc5b381f-f4cc-45cb-8978-b533d9882cf9.png)

> I don't see a reason to touch multi. There's only 1 comment with no upvotes about it.

That's right, but I also got 3 mails on support from nightly users.
How about the initial multi version you have with the three stages connected up/down (I can't find it anymore, but you probably now which I mean). I would also personally like that a bit more...but finally its up to you as you had all the effort of creating :)

**Comment by ztNFny** [comment]
> For the sake of keeping a common style (monocolor) we should look into that option first, maybe you could try to bring in this "cut out" earth piece in the monocolor version?

It's hard to do that in monocolor, it'll be like a circle filled 3 quarters.
I'll experiment around a bit.

> That's right, but I also got 3 mails on support from nightly users.
> How about the initial multi version you have with the three stages connected up/down (I can't find it anymore, but you probably now which I mean). I would also personally like that a bit more...but finally its up to you as you had all the effort of creating :)

That version, from the concept point of view, is quite similar to the current one though: waypoints connected with lines. So those saying it's too different than the GC one will also not like it.
The GC one I  personally don't like, the 2 boxes are smashed together into something that's only recognizable if you know what it it (in small size).
Of those 2 waypoint icons the "triangular" works bettery the square one has the icons in the corners and those collide with the markers in the corners. Also a square inside a circle is by definition not very ideal.

**Comment by wolverine007** [comment]
@Lineflyer @ztNFny I was one of the guys providing a comment on Facebook.

If we would like to stay in the area of  monocolor per cache type, we should get a common consense which detail is more interesting for the user:

a) Background colors: grouped by whether/where the logbook is, therefore reflecting MULTIPLE cache types
b) Background colors: used to reflect ONE cache typ

For me the grouping by color doesn't make sense. With some years of experience you know if the logbook is on spot or you have to do something to reach it finally.

So assigning a color per cache type is the way I would handle it.
And taking this into account I also suggest to switch the EC logo to brown, like @fm-sys also suggested before.

Maybe adding a magnifier glass or similar:
![grafik](https://user-images.githubusercontent.com/4508228/135172391-f19ee9ef-c3c4-4a05-b4aa-8bed75e8f349.png)



In general everyone has to get used to the new icons. the old ones have been in place for years, so the users will need some time to "like" them again. Apart from the color discussion I like them ;)

**Comment by fm-sys** [comment]
>  I also suggest to switch the EC logo to brown
> 
> Maybe adding a magnifier glass or similar: First try:
> ![grafik](https://user-images.githubusercontent.com/4508228/135172391-f19ee9ef-c3c4-4a05-b4aa-8bed75e8f349.png)

With a brown background the icon IMHO looks way more understandable, like it 👍

The black magnifier however is against our monocolor idea, and using a white one will make understandably rather worse as it'll be not recognizable as earth anymore...

> monochrome ying and yang - better known as the CITO icon before. so here maybe a recycling logo (earth with three arrows around) is nicer?

Also here, please keep in mind to not overload the icons. We might can change the ying and yang to a recycle icon ♻, but will definitely not add the earth inside. The icon must be crear also when it gets scaled down to 5-7mm... (which is not the case neither here nor for the magnifier inside the earth cache icon): 

![Screenshot_20210929_074006_org mozilla firefox_copy_66x72](https://user-images.githubusercontent.com/64581222/135209826-0e5e3c79-e5e0-4a16-8f3b-aef5249c4be6.png)

**Comment by ztNFny** [comment]
If the EC icon is bad we should fix the EC icon, not just randomly change the color as a workaround.

The "light blue" color group is already one of the smallest with ECs making up 75% of that (Earth 37.000, Virtual 10.000, Webcam 200), so EC pretty much has its own color already. Disbanding the color groups imho isn't an option - we'd need 20 colors that are easily distinguishable.

**Comment by Lineflyer** [comment]
I would also recommend to stay with the new color groups. They are logical and provide a good structure.

Maybe there is an icon idea to make it look more like the real continent shape or closer to the original icon.

If we don't find another icon for EC (in its current color) we could still make an exception for EC and give them a unique other color. They are kind of special compared to all other types, so it would still be logical to group Virtual and Webcam to light blue and have EC use another color.

**Comment by ztNFny** [comment]
![image](https://user-images.githubusercontent.com/1258173/135231094-6205d566-3ec5-4f23-bcb2-680c8c4bef2c.png)

**Comment by Lineflyer** [comment]
Thanks @ztNFny 
That's probably the best alternative if we stay monocolored.
How would it look if we use the cutout as outline only?

I tried to mock up what I mean:
![mod1](https://user-images.githubusercontent.com/949669/135241559-11dd943e-5cd2-4613-9b12-88442dd0cc25.png)

Or additionally try to visualize the earth layers with another line:
![mod2](https://user-images.githubusercontent.com/949669/135241686-79009c68-9ea1-40fa-a985-592dc7e6d66b.png)

**Comment by Lineflyer** [comment]
Then it might even work with some continent scape additionally (although a bit crowded)?
![mod3](https://user-images.githubusercontent.com/949669/135242555-b9839b15-e77b-4630-8e05-f80d8811c018.png)
!

**Comment by ztNFny** [comment]
> Then it might even work with some continent scape additionally (although a bit crowded)? ![mod3](https://user-images.githubusercontent.com/949669/135242555-b9839b15-e77b-4630-8e05-f80d8811c018.png) !

in this the cutout is not prominent enough imho, the continents are too strong and the cutout too weak.

How about the cutout with lines (your 2nd one) but make the cutout larger (instead of roughly 1/4 make it 1/3)?

**Comment by Lineflyer** [comment]
> How about the cutout with lines (your 2nd one) but make the cutout larger (instead of roughly 1/4 make it 1/3)?

Feel free to try and provide an example...my graphic skills and/or tools are probably not good enough to get it done. In fact I am only clicking around pixels in paint ;) 

I think some continent scape (even only a small recognizable shape like Florida) might still be good in addition if it fits after all if you increase the cutout.

**Comment by ztNFny** [comment]
don't have the time right now and as you were already playing ... ;-)

> Edit: Maybe you can also use more space overall (meaning make the blue frame around thinner).

That'd conflict with other icons, the shape always has some max size.

**Comment by Lineflyer** [comment]
:)
I am not even able to draw a circle (as you can see below, but lets take it as a sketch):

![mod6](https://user-images.githubusercontent.com/949669/135254445-dd51ed8b-3e79-4c41-85b6-afe43b3a488d.png)
![mod7](https://user-images.githubusercontent.com/949669/135254443-4a1001cf-0581-4063-a433-01037ad8555b.png)

Better you try if you have some time next days :)

**Comment by ztNFny** [comment]
![image](https://user-images.githubusercontent.com/1258173/135256000-5eeb28f3-ea4c-4084-887a-150ec3235c6b.png)

**Comment by ztNFny** [comment]
btw, looking at the GC icon it seems they had some problems with this icon as well. Their earths "core" is 1/4th to the side of earth and their continents are just green blobs as well.

**Comment by ztNFny** [comment]
Just for the sake of full disclosure here's another attempt, but that sucks
![image](https://user-images.githubusercontent.com/1258173/135257265-1c6ec1ce-fce3-49f3-a09f-55f8b32c5871.png)

**Comment by Lineflyer** [comment]
> I'm not sure I'm happy with this approach though. If you know the EC icon it's recognizable, but without knowing that it's supposed to be an earth ... And there's not enough room to add continents.

I like it. I think it will be recognizable on the map after the user first learned the meaning...all icons are new anyway. But the current "blobs" (as you called it) are definitely harder to recognize than this approach. 

> The base earth icon I used is not using real continents but only general shapes. Maybe if we go back to that icon but use actual continents? Like Africa should be easy to identify and then a simplified Europe on top of it. Problem I have with that is that it's kinda discriminating against the rest of the world - but the icon can always only fit a small part of earth - that's why I didn't go that route so far.

Could be worth a try. 
As written above...some continent (part) which is easily recognizable. Not sure if Africa fits, but a bit of NorthAmerica with MiddleAmerica and Florida maybe.

**Comment by ztNFny** [comment]
> Not sure if Africa fits, but a bit of NorthAmerica with MiddleAmerica and Florida maybe.

That's what the current icon shows
![earth](https://user-images.githubusercontent.com/1258173/135257962-864d8427-4513-446a-9650-345849bd2687.png)

**Comment by ztNFny** [comment]
with some additional finetuning:
![image](https://user-images.githubusercontent.com/1258173/135310425-5796c116-56de-4c91-9566-32f0e422ea5b.png)

Will submit this now as PR to get some more feedback

**Comment by ztNFny** [comment]
#11748

**Comment by moving-bits** [comment]
Although the left one is closer to the original icon, I think the right one conveys better what a CITO is about.

**Comment by Lineflyer** [comment]
I merged #11748 for testing.
Looking at it on my mobile device maybe it would be better to use only two circle elements to increase contrast and have a clearer shape.
Like that one: 

![mod2](https://user-images.githubusercontent.com/949669/135241686-79009c68-9ea1-40fa-a985-592dc7e6d66b.png)

**Comment by ztNFny** [comment]
> I merged #11748 for testing. Looking at it on my mobile device maybe it would be better to use only two circle elements to increase contrast and have a clearer shape. Like that one:
> 
> ![mod2](https://user-images.githubusercontent.com/949669/135241686-79009c68-9ea1-40fa-a985-592dc7e6d66b.png)

let's stick with the current one for a few days to get used to it, then revisit it if needed

**Comment by Lineflyer** [comment]
Sure

**Comment by bekuno** [comment]
> ![image](https://user-images.githubusercontent.com/1258173/135315269-3d1e12e3-8930-4dd8-954d-0692a5d9f59c.png) submitted as PR to get some additional feedback from real testing #11748

At first - thanks a lot for your hard work.
I don´t like the new idea. You have given the reason for this yourself above.

My two cents.
As "earth caches" are a result of the work of Groundspeak with the Geological Society (see e.g. https://www.geosociety.org/GSA/Education_Careers/Field_Experiences/EarthCache/GSA/fieldexp/EarthCache/community.aspx) the base of these cache type is Geology.
How about using a volcano or a crystal - see e.g. at https://thenounproject.com/term/geology/3128/ ->  https://thenounproject.com/term/volcano/27239/ or https://thenounproject.com/term/crystals/330138/.

Also I think that the change of the background color would be a good idea. 
Often it is easier to distinguish between colors than between symbols. Many people (esp. with eyeglasses) can only see sharp in far or near; and we are at an outdoor game. Without using different colors for the symbol we should use different colors for the background as good as possible. And in compact form we can use only the colors to diferentiate.
Additional reason is that there is a big group of cachers which are very specialized to search for earth caches, bot not for virtuals.

**Comment by ztNFny** [comment]
> Also I think that the change of the background color would be a good idea.

See https://github.com/cgeo/cgeo/issues/11721#issuecomment-929911466 for why changing the color is problematic.

Also users of GC.com are already used to this color grouping.

> Additional reason is that there is a big group of cachers which are very specialized to search for earth caches, but not for virtuals.

If they don't care about Virtuals surely they'll just filter them out?

**Comment by ztNFny** [comment]
> CITO alternative ![image](https://user-images.githubusercontent.com/1258173/135315182-dea1a5b1-e080-4300-91fd-3c9e0afa00a1.png)
> 
> Please upvote for left, downvote for right icon

As everyone seems to like the new CITO icon I've created PR #11751

**Comment by wolverine007** [comment]
> 
> 
> If the EC icon is bad we should fix the EC icon, not just randomly change the color as a workaround.
> When suggesting changes keep in mind that we're not just talking about 1 icon but 20 and they all have to be aligned in a common scheme

To be honest the new is more looking like a wifi signal or radar for me. 
For me changing the color is not a workaround it is the way to handle it.

Maybe @bekuno and me are the only ones here, but inside the community I guess there are others struggling with the color grouping.

Who said that the grouping idea groundspeak is populating right now is good or even the best way to handle?
We are talking in this case about some major cache types and some which are rarely used.

Main types - rough idea for a possible color pack:
![grafik](https://user-images.githubusercontent.com/4508228/135348826-32689a19-4fab-41a8-baf3-d59a00d147c0.png)
(Names taken from https://wiki.selfhtml.org/wiki/Grafik/Farbe/Farbpaletten#Farbnamen)

So 10 different colors to easily identified the most commonly used cache types.

Basing on this the currently designed logos could stay like they are.

**Comment by ztNFny** [comment]
> Who said that the grouping idea groundspeak is populating right now is good or even the best way to handle?

Without discussing whether it's the best - it's what users are familar with and that's a huge advantage in making the app easier to use.

**Comment by wolverine007** [comment]
But when we are now introducing new icons with new colors they will also get familar with it after a while.
Might take some days and everyone is back on track.

**Comment by fm-sys** [comment]
> > Who said that the grouping idea groundspeak is populating right now is good or even the best way to handle?
> 
> Without discussing whether it's the best - it's what users are familar with and that's a huge advantage in making the app easier to use.

I really like the color groups and think we should stay with it in general. However, I don't think EarthCaches should be considered as virtual.

For sure there's no cache box hidden, but it's not only a virtual station. It's the geological perspective what makes them an EarthCache.

That's also the way GC handles it:

![Screenshot_20210930_072922_com groundspeak geocaching intro_copy_204x505](https://user-images.githubusercontent.com/64581222/135393531-a5771921-2189-4cd8-8fc3-ecfff36bf9a7.png)

**Comment by ztNFny** [comment]
> That's also the way GC handles it:

![image](https://user-images.githubusercontent.com/1258173/135432795-67020a3e-353d-44eb-a887-ee1bdf7b9eaa.png)

**Comment by Lineflyer** [comment]
> Main types - rough idea for a possible color pack:

I am against it. Such color ranges would not make up a professional look and don't provide any logical information.
If users want it that way, they can still assign individual icons to caches or lists.

IMHO the only open decision is, whether the now replaced earth cache icon is "good enough" or if we finally decide to follow the way of GC and either deviate from monocolor for that specific type or choose a separate color for it.

**Comment by wolverine007** [comment]
@Lineflyer @ztNFny
With the current Beta the new icons have been published to a bigger user group.

Is there any plan to grab their feedback after a few days?

For me the following Icons are still strange:

- EC - no linkage to the former symbol, hard to identify it inside a bunch of other symbols related to the same blue being used

- Multi - why not using two boxes like before?

- Parking - A Blue "P" on a white circle? Sorry, have you ever seen this in reality? Why not adding a blue circle in the back an changing the P to white like before?

Just my two cents basing on the first few minutes using the current Beta....🤷‍♂️

**Comment by ztNFny** [comment]
>     * Parking - A Blue "P" on a white circle? Sorry, have you ever seen this in reality? Why not adding a blue circle in the back an changing the P to white like before?

Colored background + white icon is the design for caches, white background + colored icon for waypoints.

**Comment by alan666notb** [comment]
What about trying the "Globe with a flag in it" icon (from the 3rd post in this thread), but in blue rather than brown.
That looks obviously like an "Earth" to me. 
Or even without the flag - just the earth itself.

**Comment by wolverine007** [comment]
> still don't understand the problem that "other color" is trying to solve. EC perfectly fits into the "light blue" category, the >difference between an EC and a Virtual is only in the the type of question asked (anything for Virtual, geology for EC).

For your point of view it is matching perfectly, for me each cache type should be reflected by a dedicated color without any grouping. 

> Your response fails to answer the question on what problem to solve - see the points in my previous question, not going to  repeat them.

Seems two worlds are conflicting with each other, doesn't make sense to argue for something, which isn't accepted by the other party...

> You can already set a custom icon. Just save all ECs onto a list, set custom icon, done (that even offers a multi-colored earth)
Maybe we could adopt this the way around: I could define inside the settings, which icon is reflecting which cache type on the map, even when they are not stored.

What else, we should stop the discussion for now. At least the EC logo has changed back to a globe - target (partly) reached ;)

**Comment by ztNFny** [comment]
> Seems two worlds are conflicting with each other, doesn't make sense to argue for something, which isn't accepted by the other party...

I'm trying to understand your "world", but you're not helping with that by only saying what you want but not a single word on why.

> each cache type should be reflected by a dedicated color without any grouping.

That's a completly different point than "EC should have its own color" which is what you were requesting in your previous comment. And that's why explaining yourself would be useful....
Like you could say "When looking at the map I want to be able to differentiate cache types by color (which is the most prominent feature). I need this to get a quick overview on the map to then identify which caches I want to take a closer look at, e.g. I don't have the time for a multi so I can completly orange." Write your [user story](https://en.wikipedia.org/wiki/User_story), that's THE standard instrument in software development for a reason, or at least a requirement, but not a (potential and maybe one of many) solution.

**Comment by bekuno** [comment]
> I'm trying to understand your "world", but you're not helping with that by only saying what you want but not a single word on why.

The `why` was often said, also in the FB comments.
At first: The light blue is bad to differentiate to the dark blue.
And second: The image on the map should help to find the searched icon, hopefully differentiate from others. 
And third: EC are no dump virtual. There is no box, but normally a interesting place, much more than most of tradi. And the EC has a great fan base, so it is worth to make them good visible.

The argument with `use filter` is bad. With this argument we need no dedicated icon at all.

> Like you could say "When looking at the map I want to be able to differentiate cache types by color (which is the most prominent feature). I need this to get a quick overview on the map to then identify which caches I want to take a closer look at

Perfectly summarized :-)

**Comment by ztNFny** [comment]
> Perfectly summarized :-)

Nope. That is the argument for ALL caches to have different color.
But you want only EC to be different, a lot of other types will still share their color, most prominently Mystery - Lettetbox - WIG. But the requests are all for EC to be changed, not all of them. So the argument I made as an example above can't be it.

**Comment by Lineflyer** [comment]
> And the EC has a great fan base, so it is worth to make them good visible.

This is indeed something, which makes it a bit different to a pure virtual/webcam and maybe the fan base are those which commented on the current icon choice.

At the end however people will get used to it, either by learning the new icon or by using a dedicated list or some filtering.

IMHO the question is:
Do we want to treat earth as a somehow outstanding type or just some kind of virtual cache.
Hard to decide....maybe this is indeed a good question for a survey?

**Comment by Lineflyer** [comment]
Lets close here for now.
We have implemented the best possible icons for now and will get further feedback regarding Multi (current icon, or two box version) and earth (current icon or cut circle icon we had earlier).

Once the survey is done, we might break it down the corresponding actions into dedicated issues.
