### ISSUE TITLE
Filtering for solved mysteries hides lab caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11731]
### Describe your problem!

Found this on Facebook (saying that it is already reported, but I did not find a matching issue):
When setting up a live filter on the map to show only solved mysteries, no more lab caches are shown.

### How to reproduce?

- Open filter
- Change to advanced mode
- Apply only one condition: Solved mysteries = Yes

### Actual result after these steps?

- Only solved mysteries are shown (correct)
- Adventure lab caches are hidden (not correct)

### Expected result after these steps?

Adventure lab caches should be still shown

### Reproducible

Yes

### c:geo Version

2021.09.08

**Comment by Lineflyer** [comment]
Remark:
Testing on master shows same problem except, that I do see owned lab caches now but not all others.

**Comment by eddiemuc** [comment]
confirmed

**Comment by eddiemuc** [comment]
Fied with PR #11736

**Comment by moving-bits** [comment]
Why should ALC be shown when I set the filter to only display solved mysteries?

To my understanding a solved mystery is something like "cache type = mystery" and "has final waypoint with coordinates", whereas a lab cache is "cache type = lab cache", which does not match the condition. So it would be totally ok to not display ALC here, wouldn't it?

Or am I missing something here?

**Comment by eddiemuc** [comment]
@moving-bits the solved mystery filter is somewhat special in that it should only apply to mysteries. It's setting should not influence the filtering of any other cache type.

**Comment by moving-bits** [comment]
Oops, have just seen the info icon in the filter... Thanks for clarifying & forget my comment above.
