### ISSUE TITLE
Give workflow suitable permissions to push to master

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11737]
The workflow console looks perfect, seems like everything had worked as it should. However, the GitHub actions token has no suitable permission to push torwards master. It seems we need to adapt the repository config to make the workflow run successful... 

In the GitHub support community forum, it was suggested to create a new secret inside the repository settings. (…/settings/secrets). Then we can use it inside the workflow file:
```
${{ secrets.GITHUB_TOKEN_OURS }}
```
https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/23

```
Merge made by the 'recursive' strategy.
 main/src/cgeo/geocaching/utils/SystemInformation.java | 2 ++
 1 file changed, 2 insertions(+)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
To https://github.com/cgeo/cgeo.git
 ! [remote rejected]     master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/cgeo/cgeo.git'
Error: Process completed with exit code 1.
```

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11733#issuecomment-927311590_

**Comment by Lineflyer** [comment]
I can create a repository secret (as you described) in that menu.
What next...do you need this secret or does it simply have to be there?

**Comment by fm-sys** [comment]
You don't need to share it with me. It's enough to add the secret in the settings and share the variable name of it.

Then we need to replace the Github token in the workflow script with the variable name of the newly created one. This ensures that the security critical token can be kept private while the script itself is public anyway.

https://github.com/cgeo/cgeo/blob/e116e23c2d3a04544f56bdde57212015e554b131/.github/workflows/branch-merge.yml#L12

(replace `GITHUB_TOKEN` with with the new secret)

**Comment by Lineflyer** [comment]
I created one: ACTION_SECRET

**Comment by fm-sys** [comment]
> 
> 
> I created one: ACTION_SECRET

@Lineflyer on behalf of which user the `ACTION_SECRET` was created? Probably we have to change `https://cgeo:${{secrets.ACTION_SECRET}}@github.com/...` to `https://THE_USER_NAME:${{secrets.ACTION_SECRET}}@github.com/...`

Currently, it is still failing with `fatal: Authentication failed for 'https://github.com/cgeo/cgeo.git/'`

See https://github.com/cgeo/cgeo/runs/3736616195?check_suite_focus=true

**Comment by Lineflyer** [comment]
There was no specific user. The menu where you guided me to was a generic repository token not connected to a certain account AFAICS.

I could however create a personal access token for cgeo-ci-bot if this would be helpful?

**Comment by fm-sys** [comment]
Ah, OK. I have an idea what the problem could be:

AFAIK we have set up branch protection rules, so that only core members can directly push to master. This rule applies for workflows as well. 

So we probably need an token, created on behalf of a user **who is allowed to push to master**.

There are multiple possibilities:
- create a token on behalf of a core member 
- use cgeo-ci-bot
  - add the account to the branch protection rule
  - or add the bot to the core team

**Comment by Lineflyer** [comment]
The user cgeo-ci-bot has maintainer role for the cgeo repository as an outside collaborator.
That should (according to what I can read in the branch protection) be sufficient to push to `master`.

If you want me to create a personal access token from that account, please tell me the needed access rights of this token.
Also: This token cannot be contained in the workflow file as it need to be kept private.

**Comment by fm-sys** [comment]
> 
> If you want me to create a personal access token from that account, please tell me the needed access rights of this token. 

Yes, that would be awesome! AFAIK, only `public_repo` is necessary...

![grafik](https://user-images.githubusercontent.com/64581222/135330919-bc164862-bca2-4389-bd8a-b9ba7a2be9fc.png)

> Also: This token cannot be contained in the workflow file as it need to be kept private.


That's exactly what repository secrets are designed for. They can store any value and can be referred from workflows. So I would ask you to please generate a token for @cgeo-ci-bot and update the value of the repository secret `ACTION_SECRET` with the generated token.


![Screenshot_20210929_134237_org mozilla firefox](https://user-images.githubusercontent.com/64581222/135332640-e37a4024-b701-4841-839e-3f8ec23f4177.png)


The secret will never be printed in the public console, but is automatically detected by GitHub and replaced by '***': 

![grafik](https://user-images.githubusercontent.com/64581222/135333247-eac7beba-dd0d-419e-a846-3ac352487ad2.png)


(BTW, also in the settings the old secret value is never displayed when updating the value)

**Comment by fm-sys** [comment]
As soon as you have updated the secret value, the workflow should be ready for another test: You can always trigger the workflow [here](https://github.com/cgeo/cgeo/actions/workflows/branch-merge.yml)...

![grafik](https://user-images.githubusercontent.com/64581222/135333724-e5016917-4a7b-40c4-bc64-45f764ce587c.png)

**Comment by Lineflyer** [comment]
OK, I created a personal access token for the user `cgeo-ci-bot` with the access rights you provided above.
This token has been stored to the repository `ACTION_SECRET` token of cgeo/cgeo.

IMHO you need to change the workflow now to 
```https://cgeo-ci-bot:${{secrets.ACTION_SECRET}}@github.com/cgeo/cgeo.git```
before we can test it.

**Comment by Lineflyer** [comment]
I was wrong, tested it and it seems to work now..Hurray!
Need to check the result though.

What would happen if the merge results in conflicts...would it abort?

**Comment by fm-sys** [comment]
> What would happen if the merge results in conflicts...would it abort?

Yes, as we don't use a force push it would simply abort with result "failed"

**Comment by Lineflyer** [comment]
Thanks @fm-sys for implementing the workflow.
Seems to work fine!!!
