### ISSUE TITLE
Filter: "Found" & "Offline Found Log" to "Yes" shows no caches

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11738]
### Describe your problem!

I want to see only caches with state "Found" and with state "Has Offline Found Log".
If I set both criteria to "YES" then no caches are shown. 
The negation works - both parameter set to "NO" hides caches of both cache types.
(tested only with GC)

### How to reproduce?

 - Open map
 - select area with a cache with state found and a second with an offline found log
 - open filter
 - add "Status" filter criteria, set state for "Found" and "has offline found log" to "YES"

### Actual result after these steps?

no caches are shown

### Expected result after these steps?

only caches with "found" and "has offline found log" are shown.

### Reproducible

Yes

### c:geo Version

2021.09.26 and 2021.09.20-RC

**Comment by fm-sys** [comment]
Problem is that all parameters are considered as AND, see  #11288

**Comment by eddiemuc** [comment]
> Problem is that all parameters are considered as AND, see #11288

Exactly.
And if we would consider them OR instead, then probably you would get unexpected results if you set both parameters to NO (you would then see all caches which are NOT Found OR NOT have an offline found log -> so e.g. caches which you have found and don't have an Offline Found Log would be shown)

**Comment by bekuno** [comment]
You can select both to NO, and activate "Inverse Filter". Then you have the expected result.
But is this what the normal user understand?

By the way, the same is with the option "Has Offline Log".

Maybe it is better to see this as a group and use internal a OR here?

**Comment by eddiemuc** [comment]
> Maybe it is better to see this as a group and use internal a OR here?

There's a very prominent and often-used case for status filter which is filtering for caches I have not found AND caches I don't own. Not sure if users would be happy if we change this to OR in general.

Maybe continue discussion in #11288?

**Comment by bekuno** [comment]
> Maybe continue discussion in #11288?

Correct.
Closing here as duplicate.
