### ISSUE TITLE
[vectorIcons] Wrong icon style in Cache/Waypoint selector

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11732]
### Describe your problem!

![Screenshot_20210926-120730](https://user-images.githubusercontent.com/949669/134803456-5663da32-4398-4808-9324-58be18f826db.png)

### How to reproduce?

- Open GC75KBQ
- Select Navigate - Navigate (Drive)

### Actual result after these steps?

Wrong icon style in Cache/Waypoint selector

### Expected result after these steps?

Show normal cache marker (like in cache lists)

### Reproducible

Yes

### c:geo Version

2021.09.08

### Additional Information

_Extracted out of https://github.com/cgeo/cgeo/issues/11730_

**Comment by fm-sys** [comment]
Todo:

Use marker for Waypoint list as well. Or should we stay with the current design?

![Screenshot_20211003_095433_copy_431x324](https://user-images.githubusercontent.com/64581222/135745169-f6b89e98-56ce-4adb-a12e-166978ee97ed.png)

**Comment by Lineflyer** [comment]
I like the current design. Pretty good visible and less space consuming. 
IMHO also the selector could stay with the smaller icons.

**Comment by moving-bits** [comment]
I would rather see the same marker design throughout the whole app, so with background in both cache/waypoint selector and navigation target selector. (Not to mention that "dark blue on nearly black" is a horror in terms of visibility/contrast/UX ;-))

**Comment by Lineflyer** [comment]
Thats also true...but can we get them in the same total size then? Its neat, that they are not larger than the text beside and therefore nicely fitting in the row.

**Comment by moving-bits** [comment]
One could use two lines for the new buttons, e. g. heading / waypoint name ("Markierung 3") and subheading ("Parkplatz - Benutzerdefiniert")

**Comment by Lineflyer** [comment]
> One could use two lines for the new buttons, e. g. heading / waypoint name ("Markierung 3") and subheading ("Parkplatz - Benutzerdefiniert")

You mean the icon left of heading and subheading filling two rows? That could also look OK IMHO.

**Comment by fm-sys** [comment]
> 
> 
> Todo:
> 
> Use marker for Waypoint list as well. Or should we stay with the current design?
> 
> ![Screenshot_20211003_095433_copy_431x324](https://user-images.githubusercontent.com/64581222/135745169-f6b89e98-56ce-4adb-a12e-166978ee97ed.png)

I've moved this discussion to #11777...
