### ISSUE TITLE
'start backup' & 'start restore' no longer look like buttons

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#11741]
### Describe your problem!

I seem to remember we had this issue before although I can't seem to find it.

In the 'Backup/restore' page, the 'start backup' & 'start restore' no longer look like buttons, it's not obvious what to do to make anything happen.

### How to reproduce?

1. open cgeo using the 'light' theme
2. goto the backup/restore menu

### Actual result after these steps?

Button for actions are not obvious

### Expected result after these steps?

the actions should be obvious

### Reproducible

Yes

### c:geo Version

2021.09.20-RC

**Comment by Lineflyer** [comment]
AFAIR this was a topic related to/ only to be solved by migration of our settings to a new format (other issue).

**Comment by moving-bits** [comment]
Yes, indeed. See #10579, quite a huge task, and #11298 for progress on it.

**Comment by Lineflyer** [comment]
Closing in favor of the mentioned issues.
