### ISSUE TITLE
Long tap on compass icon in popup does not work

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11757]
### Describe your problem!

In pre-UI versions the long press on the compass rose on the map popup could be used to start the second preferred navigation. This does no longer work but instead the tooltip is displayed.

On other screens its working normal (e.g. waypoint tab, action bar in cache details).

### How to reproduce?

- Open map
- Click on a cache/waypoint
- Long tap the compass rose icon the the popup title bar

### Actual result after these steps?

Tooltip is shown

### Expected result after these steps?

Second preferred navigation (as defined in settings) should be started.

### Reproducible

Yes

### c:geo Version

2021.09.27

### Additional Information

Reported on support mail 272829

**Comment by fm-sys** [comment]
Verified, I will fix it...
