### ISSUE TITLE
Waypoint description not updated if removed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11762]
### Describe your problem!

I saved a cache some months ago. At that time some of its waypoints contained a description. 
I refreshed the cache to make sure I have the newest information and logs.

Only later I realized, that my local copy in c:geo differs from the website:
The cache on my device still contains outdated waypoint descriptions, which the owner seemingly removed meanwhile.

### How to reproduce?

GC6ZR57 waypoints on the website:
![image](https://user-images.githubusercontent.com/949669/135713176-0872875d-dbf4-4c33-8a6e-a4570fd95b0d.png)

GC6ZR57 waypoints on my device (even after several tries of refreshing):
![Screenshot_20211002-125130_cgeo](https://user-images.githubusercontent.com/949669/135713143-93ef49b4-edd1-4bab-a93a-2a228b55a582.jpg)

### Actual result after these steps?

Waypoint description not according to website

### Expected result after these steps?

Waypoint description should be updated (= in this case removed)

### Reproducible

Unclear

### c:geo Version

2021.10.02-NB

### System information

```text
Samsung S20
Android 11
```

### Additional Information

Need to check tonight with one of my owned caches which type of change is detected and which not.
Currently I assume that non presence of the description does not lead to overwriting of the local description?!

**Comment by Lineflyer** [comment]
Forgot to feedback here:
Changes in waypoint descriptions are reliably parsed. The only failing case is the removal of a description on the server, where c:geo fails to remove it on refresh. 

Summary:
Changing a existing description to an empty description makes c:geo fail to remove the description when refreshing the cache.

**Comment by murggel** [comment]
PR #13859 will fix this
