### ISSUE TITLE
Use route startpoint also as endpoint

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11770]
### Tell us your idea!

From social media:
When creating an individual route, how can you make start and endpoint the same? This would be handy to know the distance of a complete walk.

**Comment by moving-bits** [comment]
Currently there is no general way to do this, as tapping on an existing starting point to add it again as final point would remove it from the route instead. 

So far I have not found a UX-wise acceptable method for adding it as endpoint, without interfering with the user in ugly ways (like asking on each adding a waypoint whether this should be set as endpoint as well, or other ways).

What users can do currently is the following:
- Regular way along a route is to tap on each visited waypoint to remove it from route.
- If they tap twice on the starting point, it gets added again, but at the end of the current route.

This still misses calculating the full route's length before starting it, but at least while being along the route you get correct navigation info even to the actual endpoint.

**Comment by moving-bits** [comment]
Adding a cache/waypoint multiple times to a route is possible meanwhile, so let's close here.
