### ISSUE TITLE
Wrong icon coloring in item selection on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11774]
Not sure if this is already covered by other issues regarding that topic:

With current `master` the cache icons for item selection (if you click overlapping icons on OSM map) seem to always have only one color derived by a random(?) cache out of them:

![image](https://user-images.githubusercontent.com/949669/135750352-520d60e1-103a-4f31-b50e-4297fd5a4380.png)

Android 7
Galaxy Nexus (emulator)

**Comment by fm-sys** [comment]
Hm, cannot reproduc. But looks related to  #11699

**Comment by ztNFny** [comment]
If you are able to reproduce this please set some breakpoints to MapMarkerUtils:getCacheMarker() and  MapMarkerUtils:createCacheMarker() to figure out what's going on here.
From the code I don't see any case where it should be possible for the icon and color to missmatch :-(

**Comment by bekuno** [comment]
It is the same as in #11699.
I'll try the breakpoints test in the next days.

**Comment by ztNFny** [comment]
Do you have "Big icons for logged caches" enabled? If so, could you try to reproduce with it disabled? (Not that I see how that could make it happen, but at least that'd explain why there are so few instances of this happening)

**Comment by bekuno** [comment]
> 
> 
> Do you have "Big icons for logged caches" enabled? If so, could you try to reproduce with it disabled? (Not that I see how that could make it happen, but at least that'd explain why there are so few instances of this happening)

This option was off. No change if I enable the setting and also after disabling.

**Comment by fm-sys** [comment]
Issue seem to be Android 7-9 only. See https://github.com/cgeo/cgeo/issues/11699#issuecomment-932982582

**Comment by fm-sys** [comment]
I've found the issue. The background drawable needs to be mutatable. PR will follow...

From Javadoc:
> Make this drawable mutable. This operation cannot be reversed. A mutable drawable is guaranteed to not share its state with any other drawable. This is especially useful when you need to modify properties of drawables loaded from resources. By default, all drawables instances loaded from the same resource share a common state; if you modify the state of one instance, all the other instances will receive the same modification. Calling this method on a mutable Drawable will have no effect.

**Comment by ztNFny** [comment]
> I've found the issue. The background drawable needs to be mutatable. PR will follow...

Good catch! Can you fix for all 7 instances of setTint in MapMarkerUtils please?

**Comment by fm-sys** [comment]
> Good catch! Can you fix for all 7 instances of setTint in MapMarkerUtils please?

Will do. There are more places affected. A bit too much orange, isn't it?  ;-)

![grafik](https://user-images.githubusercontent.com/64581222/135763509-9003f0ce-5338-4dd0-a897-6624dc7d9e1e.png)

**Comment by fm-sys** [comment]
PR #11780 will fix the issue...
