### ISSUE TITLE
[VectorIcons] remove pin from waypoint markers in non-map contexts

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11778]
Looks good generally, but would it be possible to have the waypoint icons without the little "pin" at the bottom?

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/11768#issuecomment-932862683_

![Screenshot_20211003_092610_cgeo geocaching_copy_324x702](https://user-images.githubusercontent.com/64581222/135744367-288d6147-bd69-47e5-9726-4510b744e121.jpg)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11768#issuecomment-932880743_

IMHO the pin makes sense on the map only, for pointing to a specific location on the map. I would leave it out in all other places. But I agree that this would fit for a separate issue.

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/11768#issuecomment-932901927_

**Comment by ztNFny** [comment]
The pin should only be shown on map. I didn't know waypoint markers are shown in places other than the map, so I didn't take care of that during the implementation.

For CacheMarkers it's determined based on CacheListType, that however is not available in context of getWaypointMarker, so the callers have to be changed as well.

**Comment by fm-sys** [comment]
Fix was merged. Close it manually now, since the automatic closing has not worked...
