### ISSUE TITLE
New icons feedback

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#11788]
### Describe your problem!

Don't know the better place, but I just installed new nightly (last one I used was from July) and I'm quite surprised by new icons... And I think unfortunately in not the good way..

- First and the most important - now caches from different services are *too* similar. Before the color of the background was different as well as the shape (brown background for SU caches, square icon for OC caches). It was really easy to differentiate. Even on low zoom withany caches I always saw my brown cache. Now it's just gone. Completely. Shape difference with the current style.is incredibly not enough to differentiate. *Differentiating service is much-much more important for me than differentiating type of the cache*. Try to find two .SU caches on this screenshot.
![Screenshot_20211004-232512](https://user-images.githubusercontent.com/918446/135927061-48d76e14-6140-4b9e-82c7-7faf8ddfa67e.png)
- IMO new icons do not fit cgeo style. Too bright, too colourful, "too happy", too schematic. Also they look more like geocaching.com icons from the first sight. I dunno, maybe in a few iterations you're going to make the whole cgeo the same bright and happy, but now it just doesn't fit and really affects the impression.
- Disabled caches do not look grayed out, they look just gray

### How to reproduce?

-

### Reproducible

Unclear

### c:geo Version

Latest nightly

**Comment by fm-sys** [comment]
> Differentiating service is much-much more important for me than differentiating type of the cache. Try to find two .SU caches on this screenshot.

You can easily filter by connector via the filter system (3. action bar icon). And a major percentage is using only one connector anyway. 

> IMO new icons do not fit cgeo style 

For sure the new icons are different. But if we want to keep cgeo's theming up-to-date, we cannot stay with the 2010s design...

**Comment by okainov** [comment]
>You can easily filter by connector via the filter system (3. action bar icon).

That's what I'm using from time to time, thanks for implementing that, but on closer zooms I would prefer see all (filter is useful on 100km-zoom, when I look on the whole country or Europe) and wish the caches from different services can be distinguished easily.

> And a major percentage is using only one connector anyway.

Well, yeah, true, but still... *Cat from Schrek*

**Comment by okainov** [comment]
If those are vectors, can we maybe have switch similar to "compact icons" but "hightlight: types vs services" with default to types maybe? Which would change semantics of the background color

**Comment by fm-sys** [comment]
> If those are vectors, can we maybe have switch similar to "compact icons" but "hightlight: types vs services" with default to types maybe? Which would change semantics of the background color

There's much more info, which might be helpful: e.g. D/T, size and probably many others things. As every user has totally different requirements, I guess we need a more general implementation.

Already today, you can set list markers:

![Screenshot_20211005_072438_cgeo geocaching](https://user-images.githubusercontent.com/64581222/135965562-e2120b26-f3b9-4288-bc01-b470ddfe413a.png)

What if these couldn't only be applied to a specific offline list but also for a specific filter configuration, which would highlight caches which aren't stored offline as well?

**Comment by eddiemuc** [comment]
Technically it would be possible to allow for very generic custom stylization based on filters. In it's most generic version one could think about a new setting screen where users could define something like "format filters" or "conditional formats" (to use an excel-like term). For each entry the user ma supply:
* A filter to define on which caches to apply it to
* Icon changed which should be applied. Could include e.g. shape, Background color. List marker, icon, show additional info like D/t, rating or whatever comes to our mind
* Where to apply (map view, list view)

This is one extreme bookend of what one could do. I guess it needs to be discussed how far we want to drive this.

**Comment by eddiemuc** [comment]
> Already today, you can set list markers

True, but this feature is naturally limited to stored caches only.

**Comment by ztNFny** [comment]
> I dunno, maybe in a few iterations you're going to make the whole cgeo the same bright and happy, but now it just doesn't fit and really affects the impression.

Main screen is the only place still using old style icons and that'll be replaced by bottom navigation. Everything else is already using material icons.
The main look of cgeo is probably the map - and that dependa highly on the map source and theme, so there isn't ome "cgeo look".

As for the request for highlighting different info, no matter what we implement there's no way to make *everyone* happy. One person cares about D/T, the next about placed year, connector, special tools (climbing, lockpicking, ...)...
With list icons and custom cache icons there are already 2 very powerful ways to customize what caches look like and I think between those (almost) everyone should find what they need.

**Comment by ztNFny** [comment]
Looking at the stats on https://www.cgeo.org/status the likelyhood of someone ever seeing the "other" shape is <1%. For OC nothing changes, still a white square, only other was previously a color and now a shape.

**Comment by Lineflyer** [comment]
As this issue is stale, I guess all optimization potential has already been discussed.
Additionally there is no specific negative feedback (any more) from other users on our support channels. Also meanwhile its possible to set individual cache icons or cache icons for specific lists. So a lot of features came in to individualize the icons according to specific needs. Lets therefore close this rather generic issue.

Feel free to open specific issues for dedicated improvement proposals.
