### ISSUE TITLE
Support adding caches to bookmark lists

### ISSUE THREAD

**Issue by gcey** [cgeo/cgeo#118]
The geocaching.com web interface provides the function "Bookmark listing", which I am using e.g. to add a cache to my FTF list right after logging the FTF.
It should be possible to do this from c:geo (because in the evening at home I might forget to do this).

**Comment by Lineflyer** [comment]
Given the recent discussion about the newly introduced ignore feature I think that supporting bookmark lists would be a good idea as this would on one hand also implictly add the support for viewing the ignore list and one the other hand implement a feature which a lot of users ask for.

So this feature would need a support for adding a cache to a bookmark list (like adding it to ignore list, which is already implemented) as well as viewing existing bookmark lists.

**Comment by mapa6** [comment]
Is it possible implement to c.geo app "add cache to bookmark list" (e.g. FTF) by the same way like "add to watchlist" ?
