### ISSUE TITLE
Improve variables creation workflow

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11802]
rel. to #11520

Currently, it requires 5 clicks (IMHO _way_ too much) to create a new variable. I have multiple ideas how to improve this workflow:

- [ ] Make keyboard popping up automatically (for all text input dialogs in cgeo)
- [ ] Instead of allowing "can be left empty" for variable names, add a dedicated top-level button for it
- [ ] Remove "A-E" button, as it IMHO has no benefit. No one will ever need exactly 5 variables. (Without being a gamer, I have a click speed of ~6 clicks per second, so the suggested top-level button should do the same job. Simply click it 5x, which still takes less time than opening the "create variable"-dialog once.)
- [ ] Automatically focus the value field and open keyboard after a variable is created

---
Just for reference - These are the steps which are required to create a new waypoint currently:

1. Press "+" button
![grafik](https://user-images.githubusercontent.com/64581222/136570480-55cbadf3-0004-43a6-8f4d-7ede09b47240.png)

2. Make keyboard popping up
![grafik](https://user-images.githubusercontent.com/64581222/136570557-7bb03ec5-6734-4309-881f-3ce8951654c4.png)

3. Enter name
![grafik](https://user-images.githubusercontent.com/64581222/136570603-4d832513-3a30-4fe1-bb3f-9a03f2434fd4.png)

4. Press ok
![grafik](https://user-images.githubusercontent.com/64581222/136570680-aca91516-85ac-45be-beab-f468b062e5d2.png)

5. click into the value field
![grafik](https://user-images.githubusercontent.com/64581222/136570729-66a4c2ad-1e92-4b7d-b670-eec1bb0dcf81.png)

6. You can finally enter the value you want...

**Comment by eddiemuc** [comment]
> >     * In almost all cases, user needs uppercase variables starting from A. Using button A-E allows quick Creation of those. After that button will change to A-J and so on. If user just needs e.g. A-C, then D and E can be left empty - no one should care -> one or two click to create all variables needed.
> 
> Still don't see a real need in that button. Users (or at least I) always want to keep things cleaned up. And if I want to add multiple variables, I can click the button multiple times. (first click: A, second click: B, and so on...)

Your points are absolutely valid. It would be eas to change the button accordingly. But you had some other valid points too, shall we maybe discuss the UX concept as a whole first?

**Comment by eddiemuc** [comment]
PR #11811 will change "multi-add" to "single-add". The remainder of the issue should be discussed first

**Comment by eddiemuc** [comment]
I think all topics in this issue have been resolved meanwhile, thus I will close. Please feel free to reopen if I have overlooked something (or open a new issue for it, might be cleaner)
