### ISSUE TITLE
search on main screen broken

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11803]
### Describe your problem!

#11794 broke search from the search field on main screen. While the search results display ok clicking one of them brings you to another cache.

It seems that always the xth cache from "recently viewed" list is selected instead of the appropiate xth cache from "search results"

### How to reproduce?

1. Open search dropdown
2. Click on first cache
![image](https://user-images.githubusercontent.com/1258173/136593132-7d122936-786d-4eed-800c-b4a2be60de0f.png)
-> Selected cache opens, all good
![image](https://user-images.githubusercontent.com/1258173/136593155-db2a327f-cc39-46d9-b9b4-74ae7b573485.png)
3. Back to main screen and open search dropdown again
4. Type some search term
5. Click on first search results
![image](https://user-images.githubusercontent.com/1258173/136593190-bc03d8ae-311a-4729-9c6d-3ff77c25be9f.png)
-> Cache from step 2, the first from search result, opens
![image](https://user-images.githubusercontent.com/1258173/136593287-fa169b3b-35f3-4053-ac56-143010c24561.png)

### Reproducible

Yes

### c:geo Version

2021.10.09-NB

**Comment by fm-sys** [comment]
Yes, thanks for reporting this. Seem like the SearchView vs. ViewAdapter dataset gets out of sync. I will have a look...
