### ISSUE TITLE
Store high-res cgeo logo in our repo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11816]
I just searched for our (new) logo within our repository but only found the (low-res) playstore icons and the separate svg layers (background + foreground). Or did I miss to find it?

Can someone able to do this create some high resolution PNG images from that (maybe in sqaure, rounded, squircle, etc.)?

Having those will be helpful for several things:
- Website use
- Handing over to press staff when asked for it on support
- Creating developer shirts ;)
- etc.

**Comment by Lineflyer** [comment]
BTW: Is there any easy possibility/tool to produce a rounded corner version of the SVGs?
Having these would be helpful to use on websites/shirts.

@murggel @ztNFny

**Comment by ztNFny** [comment]
To do that you overlay the logo with a squircle and create a junction in Inkscape. I can do provide that in 2 weeks.
