### ISSUE TITLE
Storage Access Framework in Android 11: Locus

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#11842]
Due to recent problems with storage access Framework esp on Huawei I again asked myself how other apps handle these issues.

Among others I checked Locus on my Android 11 device. To my big surprise it still seems to use a self-made file browser to select e.g. folders for external map access.

I would really like to understand how this is still possible - my info was that as of now this should no longer be possible.

Does anyone have contacts to Locus development team to find out how they do it?

**Comment by SammysHP** [comment]
In several apps I've seen a popup that says I have to select the root folder in the following system file browser to grant access to the whole storage. Could this be related?

**Comment by eddiemuc** [comment]
> In several apps I've seen a popup that says I have to select the root folder in the following system file browser to grant access to the whole storage. Could this be related?

This would certainly be a "solution" to circumvent managing all the different SAF folders :-) 

But for Locus I didn't have to do that and the browsing still works. Also I assume that this "root selection" uses OPEN_DOCUMENT_TREE intent too and thus would not work on the problematic devices.

**Comment by eddiemuc** [comment]
While I am at it: Locus lists c:geo as a "Co-App" with the following description (in german): "Einfache (inoffizielle) Applikation für Geocaching.com.".

**Comment by Lineflyer** [comment]
AFAIR there is no strict enforcement right now. We are also still requesting the legacy file access and it works. 
But things are about to change soon..not sure if this is related to the point in November where the Play Store will refuse apps requesting file access directly or indirectly by enforcing a new targetSDK which no longer supports the legacy file access.

**Comment by SammysHP** [comment]
Have you tested the legacy Locus or the new version (4?)?

**Comment by Lineflyer** [comment]
@eddiemuc This was only was discussion, was it? Can we close here? 

Is there any requirement to remove the "external storage permission" or shall we leave it in; or do we even still need it?

**Comment by eddiemuc** [comment]
I think we can close here.

The write_external_storage should be removable according to documentation (see link), but I dimly remember we had some problems without it on older devices?  I might be wrong here though.

https://developer.android.com/training/data-storage
