### ISSUE TITLE
Store All is ignored if the caches are already stored

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11847]
### Tell us your idea!

From support mail:

If I want to copy caches in a particular area from one list to another list the obvious way to do this is to view the first list on the map, zoom in to the area in question than select Store All and select the new list. All of this works as expected, except that the caches are not copied to the new list. 

### What solution would you suggest?

When Store All assesses caches for storing, it should not test that the cache is already stored, but test that the cache is already stored in the selected list.

### Additional Information

Support ticket 761355

**Comment by ztNFny** [comment]
I can confirm this. What i do is "show as list", from therr dzore sll eorks
