### ISSUE TITLE
back from "map" goes to dashboard instead of listing

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11863]
### Describe your problem!

When using the map to navigate to a cache and clicking the back icon in upper left (instead of using the nav bar back button/gesture) instead of returning to the listing dashboard is opened.

This is a regression caused by bottom nav bar.

### How to reproduce?

Open a cache listing
Navigate to cache using "map" option (to draw a line to the cache on map)
Click the back icon in upper left corner

### Actual result after these steps?

Dashboard opens

### Expected result after these steps?

Return to cache listing

### Reproducible

Yes

### c:geo Version

2021.10.12-NB-7045e7b

**Comment by fm-sys** [comment]
Confirmed. Will provide a fix...

**Comment by fm-sys** [comment]
PR #11883 will fix the issue...
