### ISSUE TITLE
New icons feedback: waypoint markers

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11861]
### Tell us your idea!

Waypoints are combined of the service's general outline marker (circle / square / hexagon) and the waypoint specific logo inside. The outline's filling is pure white.

As the inner logo's size is the same as the cache symbols are, but the waypoint markers don't have a colored background, there's much empty space between logo and outline. The logos look a bit "lost".

### What solution would you suggest?

Reduce the outline's size for waypoints to roughly the size the colored background for cache type markers have. This would both reduce the empty space and make waypoint markers more distinguishable form cache markers.

### Is there an alternative?

Either increase the waypoint logo size (not a good idea, IMHO, would look unbalanced), or leave it as is.

### Additional Information

Edit: This is with icons in default size (not in "compact icon mode")

**Comment by moving-bits** [comment]
Proposal:

![grafik](https://user-images.githubusercontent.com/3754370/137026020-35427d64-6d38-446b-b843-925896f6a0cd.png)

**Comment by ztNFny** [comment]
If you want you can change the total size of the marker, but the current look is unacceptable to me. It's completely unbalanced and looks just broken.

**Comment by ztNFny** [comment]
> The "old" markers had way too much white space, which made the symbols look sort of "lost" in their huge circles/squares/hexagons.

I spent several days/weeks aligning all the sizes and making them match between each other. Now you just went and changed one key element which breaks the whole balance between - well, everything. Again, this looks totally unacceptable to me, it's not just "bad", it's broken IMO.

> I had tested the new sizes in the emulator, but today installed a nightly on my phone.

I saw it on my phone today without noticing this issue first and my first thought was "the map display is completeley broken!"

**Comment by moving-bits** [comment]
Ok, let me try to summarize my reasonings why I proposed this change:

I'm currently on vacation in an area that has many multi caches with quite a few stages cluttered all around the area. So I have, let's say, 50 caches, and app. 100 stages that clutter the whole map. Stages of a multi cache are mainly important when doing that specific cache, so I indeed consider them less important than caches. Reducing the "show waypoints if less than x caches" is no option here, as I want to see waypoints generally, and even in that specific case.

A second reason for me was the visual look of the original waypoint markers. The symbols itself have a size similar to the cache symbols (have not measured it exactly), but in contrast to them, they don't have a colored background. Which is ok to be able to distinguish them from caches, but by this there is a huge white gap between waypoint symbol and waypoint marker's border, which makes the symbol sort of look "lost".

IMHO increasing the symbol's size isn't a useful option, would give the waypoint's symbols too much weight compared to cache symbols (yes, caches ARE more important than waypoints, and the colored background helps with that), and decreasing the whole waypoint symbol would solve cluttering, but not the white gap issue.

But I'm fully open for discussion, and if the team finally decides to stay with the original sizes as default, that would be totally fine for me. I would then need to look for a way to achieve the visual goals described above, without interfering with the team's choice.

**Comment by fm-sys** [comment]
To solve the cluttering issue: The new "compact icons" do support waypoint markers in compact mode as well. 

To improve this: Don't know how switching between both modes is implemented currently, but probably it makes sense to take the waypoint count into consideration as well...

I would be fine with slightly reducing cache and waypoint marker size, but IMHO both should stay consistent.

**Comment by ztNFny** [comment]
I propose to split this into 2 issues:
1. Improve waypoint handling. Maybe use a different size (or style?) for waypoint marker - but first it needs to be identified what should be solved/improved by doing that
2. Tweak waypoint icons (size)

**Comment by Lineflyer** [comment]
My few cents:
I don't see any reason why waypoints of a cache should be smaller than cache icons, because:
  - Both are just waypoints (just the cache icon happens to be the header coord)
  - If I use the live map I can already control if and when they are shown 
  - They did not have a different size on the old icon set either
  - If I use the map for a cache I want to see all waypoints of this cache with same importance as the header coords for sure

Regarding the proportions (where this issue started):
I think the icons within the circle should have the same dimension as the cache type icons, but they already have, don't they?

**Comment by ztNFny** [comment]
> Regarding the proportions (where this issue started): I think the icons within the circle should have the same dimension as the cache type icons, but they already have, don't they?

They are slightly to account for the "visual difference" caused by the missing background color. The goal is to have them seem the same size, regardless of the real size.

**Comment by fm-sys** [comment]
Reopen, as it was wrongly auto-closed...

**Comment by fm-sys** [comment]
probably, cause the commit message contained `revert 'fix #...'`

**Comment by moving-bits** [comment]
Let's close here, proposal did not find necessary acceptance
