### ISSUE TITLE
[vectorIcons] missing translucency for visited waypoints

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11872]
### Describe your problem!

With the new icon implementation a visited waypoint has a "checked" marker. 
But the WP is not more translucent. This was a fine feature to see also more details on the map.

### How to reproduce?

Take or create a waypoint on map.
Set the waypoint to visited.

### Expected result after these steps?

The waypoint icon is translucent.

### Reproducible

Yes

### c:geo Version

2021.10.11-RC

**Comment by ztNFny** [comment]
Help me understand in which situation is that relevant? To me it seems that the option in map quick setting takes good care, at least for the usecases i have in mind:
when I play a multi and also do some other caches around it I use the map with waypoints visible and visited waypoints hidden. 
If i explitily want to see where i've been I show the visited waypoints - in that case I want them visible, not half-visible.
How are you using this?

> Not mandatory if technically problematic though.

We'd have to implement something to draw the whole layer drawable, then convert that to a bitmap, then set that as translucent - I think.

**Comment by bekuno** [comment]
> 
> 
> We can add it to the survey - transparent vs checked.

Good idea.

**Comment by fm-sys** [comment]
This feature is now removed for over 2 years and no one ever claimed it again, so I would vote to close here. Feel free to reopen if you disagree.
