### ISSUE TITLE
Download / unpacking error on FZK maps

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11877]
### Describe your problem!

Coming from discussion in #11817 we've stumbled upon errors on installing FZP map files. It looks like the downloaded zip file is ok, but the error is on unpacking the file.

### How to reproduce?

use map downloader to download a map from FZK

### Actual result after these steps?

Frequently the downloaded file will not unpack correctly. You'll receive an error message (always?), a corrupted (incomplete) map file will remain, and no companion file will be created. There will be an error from Mapsforge on opening the corrupted map file in Logcat, and map updates will not work.

### Expected result after these steps?

File should be unpacked correctly, companion file be created, and updates shall work

### Reproducible

Unclear

### c:geo Version

2021.10.11-RC (and others)

### Additional Information

Seemingly does not happen in all cases. Maybe some timing problem on closing the zip file?

**Comment by Lineflyer** [comment]
@moving-bits Still relevant?

**Comment by moving-bits** [comment]
Haven't heard of it anymore, neither on Play Store nor on support, so let's close it for now.
