### ISSUE TITLE
Crash or "hang" when trying to open from AL App

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11878]
### Describe your problem!

We have three reports for current beta on support mail, that c:geo crashes or hangs when trying to invoke the navigation from the adventure lab app to generate a new target in c:geo.

### How to reproduce?

- Use Groundspeak Adventure Lab app
- Select a location of an adventure
- Invoke navigation and select to open it with c:geo

### Actual result after these steps?

Crash or hang

### Expected result after these steps?

Work normal

### Reproducible

Unclear

### c:geo Version

2021.10.11-RC

### Additional Information

Not yet find the time to reproduce

**Comment by fm-sys** [comment]
Can reproduce.

![Screenshot_20211013_222418_copy_269x413](https://user-images.githubusercontent.com/64581222/137207461-4619ce22-1c9c-4c16-b34d-6dc467f4e50d.png)

**Comment by fm-sys** [comment]
Blame on me. A copy & paste error, which was introduced myself... PR will follow.
