### ISSUE TITLE
Document alc_consumer_key state in README

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#11875]
Yesterday, I for the first time in a long time tried to open my IDE again and play around with the code a bit.

However, on building I got the error "Cannot find symbol R.string.alc_consumer_key". Where can I generate my own consumer key for building the app locally?

I tried at labs-api.geocaching.com but didn't find a registration form or similar there.

Thanks for helping me out!

**Comment by jakedot** [comment]
So, I just have to use CI for builds? Thanks!

**Comment by bekuno** [comment]
> 
> 
> So, I just have to use CI for builds? Thanks!

No, it should build without having such a key.
This should be configured in the same way as for other connectors without a own key.

**Comment by SammysHP** [comment]
We are probably not allowed to talk in public about how their system works or how one can extract a key or bypass their protection. That's the not so nice part of the partnership with Groundspeak. And no, you can't apply for a key. It's like "don't call us, we call you".

On the other hand I don't see any reason for not using basic development tools like apktool.
