### ISSUE TITLE
Remember log date within a session

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11890]
### Tell us your idea!

From support mail:

From time to time (e.g when I use another GPS device or forget my phone) I have to log some caches, which I found some days before with c:geo.
When doing so I have to adjust the log date for each log as it always defaults to "today".

### What solution would you suggest?

Remember the last used log date within the same session (its perfectly fine to default to "Today" again in a new session).

### Is there an alternative?

Using offline logs while out caching...but I cannot do so if I don`t have the phone with me on that day.

### Additional Information

Comment Lineflyer:
AFAIR we have realized exactly this option for trackable logs as per feature request, that users would like to discover several trackables with a date in the past.

Not sure if there is any problem with syncing this behavior to cache logs or whether users might run into follow-up problems then (e.g. as "a session" is probably not what a user expects).

**Comment by MagpieFourtyTwo** [comment]
Possible problem scenarios:
- While doing a series of caches, you remember the one forgotten yesterday, thus you log it right now, change the date ...
  And the rest of the tour will get ... yesterday's date?
- Offline logging while date changes ... i. e. one cache right before and another one immediately after midnight.
  Which date will the latter one get ...?

Possible solution:
- do not unconditionally use the last used date
- usually default to today, like it is right now, unless the user has *actively* changed the date
- when an explicit change of date happened, c:geo may use this manually selected date,
   but just for a "grace period", which should be ...
   - long enough to survive a reasonable time between finishing one "catch up log" and starting the next "catch up log"
   - but short enough to *not* survive the time between two "real" cache finds (and logs)
- after the grace period revert the default to today again

A grace period of let's say 3 to 5 minutes will most probably cover both, the problem's and OP's scenario.

**Comment by eddiemuc** [comment]
We recently had another request for this feature via support. ticket #[354842](https://cgeosupport.droescher.eu/scp/tickets.php?id=7967)

**Comment by ztNFny** [comment]
https://github.com/cgeo/cgeo/pull/16121 implemented a solution for this
