### ISSUE TITLE
Bottom navigation: How to structure the "more" page?

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11904]
### Tell us your idea!

Although I really like the new bottom navigation look in general, I'm still somewhat unsatisfied with the look of the "more" page. Currently it's more or less an unsorted bunch of links (no offense intended! I do know where all those links come from...). For a basic member, it looks like this:
![grafik](https://user-images.githubusercontent.com/3754370/137530656-aeebe4f3-85d7-41c8-b780-437a1a9ac4c9.png)

And a gc.com PM even has two more entries (bookmarks / pocket queries). Depending on screen length and font sizes, you'll even have to scroll...

I have no ready-at-hand idea how to do this, so I'd like to start a gathering of ideas how to enhance and structure this page.

### What solution would you suggest?

A starting point could be to transfer two or three easily recognizable and frequently used links to icons in the toolbar, e. g.
- Settings
- About c:geo

This should be easy to realize and cause no harm, but will reduce the list by two entries already.
(If we agree on implementing #11897, this would be the third icon on this toolbar.)

Next I thought of some grouping of the remaining ten entries, but alas they are nearly as much diverse as possible :-) - Have not found a helpful grouping for the entries yet.

Another idea could be to change the textual entries into a two-column layout of large graphical buttons (+ text), but this would solve neither the grouping problem nor the possibility of having to scroll.

Any ideas whether we can leave-out some of those entries? 
We had some discussion about the "scan geocode" feature lately, but haven't decide to remove it for now. 
"Useful apps" could become a separate tab on the "about c:geo" screen (as we have other useful links regarding c:geo over there already), which would simply transfer the problem to a different, but less-crowded, place.

Also we should discuss the order in which the entries are shown. IMHO the most important entries should stay at the top (as they mostly do, currently only "report problem" seems to me being too important for staying at the end of the list).

### Is there an alternative?

hopefully plenty :-)

**Comment by fm-sys** [comment]
> no offense intended!

All fine. This is the place where I have worked the least time so far... I'm not yet convinced either ;-)

And you already have mentioned some IMHO really good ideas. 👍

Another idea, which I have seen in many other apps: Introducing some kind of priority-grouping... (high emphasis entries on the top, others on the bottom) 

![Screenshot_20211015_221912_com groundspeak geocaching intro_copy_270x585](https://user-images.githubusercontent.com/64581222/137548977-622bce33-6319-4f46-a2c3-c3468b72d0ee.jpg)

**Comment by fm-sys** [comment]
I'm still struggling whether it's the right way to implement a separate "more" activity at all. What if we add the "dashboard" as fifth menu entry, and move the current "more" content to an actionbar overflow menu again?

**Comment by SammysHP** [comment]
The action bar refers to the current activity while the bottom navigation bar moves horizontally between activities. Thus I think it would not be logical to move the more menu up into the action bar.

A simple detail that could be improved right now: remove the little arrow for each entry. This is not a hierarchical menu, it selects a different activity.

**Comment by Lineflyer** [comment]
> The action bar refers to the current activity while the bottom navigation bar moves horizontally between activities. Thus I think it would not be logical to move the more menu up into the action bar.

But if you want to take smaller steps you could still go with transforming the items of the previous main screen into a bottom navigation and keep the rest as is (for the first step of changes).

**Comment by moving-bits** [comment]
> I'm still struggling whether it's the right way to implement a separate "more" activity at all. 

Yeah, me as well.

> What if we add the "dashboard" as fifth menu entry, and move the current "more" content to an actionbar overflow menu again?

You mean "dashboard" as fifth activity for bottom navigation (no "more" activity), and put all of today's popup menu entries into the dashboard's overflow menu?

Having "dashboard" as fifth entry, and no separate "more" activity would make bottom navigation a bit closer to today's main screen, thus less disruptive for today's user. Like that idea. 👍 

I'm unsure, though, about the menu entries, would be a pretty long overflow menu then, even if some go to action bar as icons.
Any chance to incorporate some entries into the dashboard itself in a meaningful (and understandable) way?

**Comment by fm-sys** [comment]
> I'm unsure, though, about the menu entries, would be a pretty long overflow menu then, even if some go to action bar as icons.

All these menu entries (ok, except "go to") are 100% copied from the old overflow menu.

**Comment by moving-bits** [comment]
> > I'm unsure, though, about the menu entries, would be a pretty long overflow menu then, even if some go to action bar as icons.
> 
> All these menu entries (ok, except "go to") are 100% copied from the old overflow menu.

\*blush\* - you can see how quick I have become used to the bottom navigation version of c:geo...
(Maybe I got confused because some of the old entries I have only ever seen as icons, not in full-line length with text + icon)

Anyway. Would be another argument to skip the "more" activity in favor of a dashboard activity + overflow menu.

**Comment by fm-sys** [comment]
>  Would be another argument to skip the "more" activity in favor of a dashboard activity + overflow menu.

Only downside: one more click to access these actions. But they probably aren't really often used anyway...

**Comment by moving-bits** [comment]
> > Would be another argument to skip the "more" activity in favor of a dashboard activity + overflow menu.
> 
> Only downside: one more click to access these actions. But they probably aren't really often used anyway...

which brings us to yesterday's (?) point in our discussion: Which menu entries do we regard as "important" / frequently used, and which are less frequently used. The latter are candidates for an overflow menu, the former could be candidates for being displayed in the dashboard. But those should be only a few, to not overcrowd the dashboard.

The current dashboard has a nice, clean look, whereas the draft shown above has too much content (IMHO), of different types, and not clearly separated.

**Comment by fm-sys** [comment]
> The current dashboard has a nice, clean look, whereas the draft shown above has too much content (IMHO), of different types, and not clearly separated.

Totally the same over here. I love the current clean dashboard design much more as the first draft. That's why I finally relented for splitting up. ;-)

But as long as we add these options only to the overflow menu, the dashboard will stay clean enough  as well...

**Comment by fm-sys** [comment]
> Can we structure the more page with some headlines? Like to group all the import options and so on?

We are currently more likely going to the direction of removing the "more" activity completely in favor of the dashboard... 

But sure, everything is possible in theory :)

Let's wait some days and reconsider every option with their pros & cons, before diving into implementation.

**Comment by Lineflyer** [comment]
> Let's wait some days and reconsider every option with their pros & cons, before diving into implementation.

Yes, that would be good to give all the chance to read it / think about it.

Maybe it could be a mixture of having most important functions on dashboard and remaining in action bar / overflow.

**Comment by Lineflyer** [comment]
While out caching today I intensively used the nighty build.

By that I found another reason for including the dashboard as bottom navigation item (and put the rest back to the action bar):
Its annoying to have to use the the upper left to return to the dashboard and going via more and using two clicks is even more difficult.
Also with such solution users might be more able to follow the change we did, as "They only moved the main menu items to the bottom and added a dashboard".

**Comment by MagpieFourtyTwo** [comment]
Totally agreed. And in fact the reason why I opened #11897 
Just wanted to know if @Lineflyer sits in our boat, too ...  ;)

In fact, I would highly appreciate either an add. magnifier icon or - even better -
a matching longlick action for the ``Search`` button in bottom navigation.
But as #11905 has been closed surprisingly fast w/o even thinking about the ``Search`` longclick,
I was a bit surprised ... nevertheless, fine to read that others think the same way I do.  ;)

**Comment by Lineflyer** [comment]
> Nevertheless, there's still one question in my mind: Why did you felt the need to go to the dashboard ...?

It was one of those reasons throughout the last days:
- Check my login state (I had bad network at that place)
- Check my current coords
- Update to the latest nightly via notification
- Just wanting to end the live map as I wanted to save data transmission

Maybe I am to "old school" but I like having a place in an app where I just go back until I need the next action is needed ;)

Thus for me it feel like the right thing to have the "Dashboard" on the bottom navigation and put the more back into the menus.
BTW: This also would help in not having to rewrite the user guide :D

**Comment by MagpieFourtyTwo** [comment]
> Update to the latest nightly via notification

This is in fact the only (real) reason why I go to the dashboard.
Apart from the "forced" dashboard openings, as there's no other way to get to the view history, i. e. magnifier search symbol.

BTW: I experienced *extremely* long open times when opening the dashboard (up to 10 seconds) - anybody else?
Seemed to become a bit better after unticking "Appearance" => "Show Address [_]".
Nevertheless, even more annoying, if all you want to do in dashboard is to get to the magnifier ...
Maybe understandable, as 12 secs, just to get to the previously displayed cache is not really tolerable.

Thus I would once again insistently vote for a shorter (and more intuitive) way to get to the view history.
Esp. as most regretfully the back button is pretty useless with bottom navigation.

**Comment by fm-sys** [comment]
>
>  |  |	Without labels - icons are probably not recognizable enough|
>-|-
> |  |![grafik](https://user-images.githubusercontent.com/64581222/139115778-0c0a28ea-f7f2-4afe-9b0a-0bbbf4b37804.png)|

If we want to make more actions directly accessible without adding an additional view, we could also extend the number of visible action bar items (same as we already do for map/list)

**Comment by fm-sys** [comment]
@moving-bits Should we close here? AFAIK the main points are implemented meanwhile, and this thread is already (way too) long...

**Comment by Lineflyer** [comment]
Yes, in case something is still relevant we might better break it down into smaller issues.

**Comment by moving-bits** [comment]
> @moving-bits Should we close here? AFAIK the main points are implemented meanwhile, and this thread is already (way too) long...

Sure. We should open separate issues anyway if something relevant new pops up.
