### ISSUE TITLE
Side bar not available on dashboard

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11908]
### Describe your problem!

I have run into a situation on my tablet, where only the dashboard content but not the sidebar is shown. Thus I am stuck on that screen.

Not clearly reproducible until now but at least an idea when it occurs.

### How to reproduce?

- Start c:geo (portrait mode, tablet)
- Open live map
- Change to another app / go to phone menu or somehow else put c:geo into background
- Go back to c:geo by either changing back via taskmanager or simply using the launcher icon again

### Actual result after these steps?

Sometimes (not always) I end up on a dashboard without sidebar

![Screenshot_20211016-121328_cgeo](https://user-images.githubusercontent.com/949669/137583661-b6a4bef8-6f27-4859-9161-021922164357.jpg)

When pressing the back button of my device it (most of the time) returns to the last active activity (live map in this example).

### Expected result after these steps?

c:geo should return to the activity where I left it or (if that is impossible for some reason) at least show a complete dashboard with side bar

### Reproducible

Unclear

### c:geo Version

2021.10.16-NB

### System information

```text
Samsung Galaxy Tab S4
Android 10
```

**Comment by fm-sys** [comment]
Hm, mysterious... No idea why this happens...?!

**Comment by fm-sys** [comment]
Let's close in favor of #12010
