### ISSUE TITLE
visualize, that the found count is clickable

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11917]
|clock icon |open external link icon  |
-|-
![grafik](https://user-images.githubusercontent.com/64581222/137594170-ecdd9719-9be4-4ed6-b3fa-04c9a3131e81.png)|![grafik](https://user-images.githubusercontent.com/64581222/137594196-1d1d8ddf-cce0-4ced-b84f-08b527937d53.png)

IMHO, the open external link icon looks more "clickable"

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11905#issuecomment-944941782_

**Comment by fm-sys** [comment]
Commit https://github.com/fm-sys/cgeo/commit/799f1f65cfd2833c43513b5ceb233374bba9c9ef provides an implementation with the 'open external link' icon. If this is considdered as good, I will open a PR...

**Comment by Lineflyer** [comment]
I also thought if it might fit better if its appended instead of prepended. 
Like when listing some fact (the finds) and then having a link for "More related info" behind it. 

If its prepended people might tend to think its only an icon as caption for what follows.

**Comment by fm-sys** [comment]
IMHO this is no longer necessary, as we now have the old actionbar back... Opinions?
