### ISSUE TITLE
[vectorIcons] compact icon - cache with note

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11925]
### Describe your problem!

This is the compact icon for a mystery cache with note.
![Screenshot_20211017-212225_cgeo](https://user-images.githubusercontent.com/32555742/137642015-c10ec11a-0241-41af-a265-f7f5b403943a.jpg)

This is at least inconsistent in the background color.
The other question is - is this ok to show cache with "note" as compact icon or is this too much of detail information in compact mode. I would tend to the second opinion.

@ztNFny 
Is it possible to actualize your icon design overview (https://ztnfny.github.io/cgeoicons/index.html) to the current state (or do we have already something)?

### How to reproduce?

- write a note to a mystery cache
- open map with this cache in compact mode

### Actual result after these steps?

see screenshot above

### Expected result after these steps?

stay with the original cache background

### Reproducible

Yes

### c:geo Version

2021.10.11-RC

**Comment by ztNFny** [comment]
what is the bug here? grey background instead of white is #11862

**Comment by bekuno** [comment]
> what is the bug here?

A brown background instead of blue.

**Comment by ztNFny** [comment]
> or is this too much of detail information in compact mode. I would tend to the second opinion.

Why should an offline log of type note not be shown but one of type dnf / found should? They all mean "the cache was visited and there's a log i have yet to send". When you're doing a tour the important info will be "i've been there" so you know bot to go there again.

**Comment by bekuno** [comment]
A cache with note or dnf is probaly later once more a caching destination. But normaly not a found cache.

Maybe we should rethink also the dnf compact icon style.

**Comment by ztNFny** [comment]
> With your argument for note this should then have a white flag on red background :(

No, that's not my argument at all.

It is the LOG icon, not a CACHE icon. Brown is the color of the log, it has nothing to do with the cache type.
Corrected Coordinates apply to the cache, thus it's added as an overlay.

Logic is:
If there's an offline log show the log icon
Else show the cache color + If there are corrected coords/final show an overlay.

Switch to non-compact mode to understand it maybe? What's in upper left corner (offline log) becomes the icon, lower right becomes an overlay.

**Comment by ztNFny** [comment]
> A cache with note or dnf is probaly later once more a caching destination. But normaly not a found cache.
> 
> Maybe we should rethink also the dnf compact icon style.

Later - by which time you'll have cleared the offline log (put it as online log). Or if you want to visit it again at the end of the day you'll want to be able to quickly spot "the cache I didn't find earlier" - for which you need the log icon
