### ISSUE TITLE
[vectorIcons] saved button for unsaved caches in quick cache info

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11924]
### Describe your problem!

As you can see in the screenshot - the cache is unsaved, but the disc icon is shown.
![Screenshot_20211017-152713_cgeo](https://user-images.githubusercontent.com/32555742/137641693-3142242d-c8c2-4923-8d80-ce258b10b831.jpg)

### How to reproduce?

- Open live map
- tap a unsaved cache

### Actual result after these steps?

the additional disc icon is shown 

### Expected result after these steps?

the cache icon without disc is shown

### Reproducible

Yes

### c:geo Version

2021.10.11-RC

**Comment by Lineflyer** [comment]
Tested with todays nightly build but cannot reproduce the problem.

**Comment by bekuno** [comment]
This is at my outdoor-c:geo with the current beta version.

**Comment by bekuno** [comment]
> @bekuno what manufacturer and Android version is that? Somehow you got all the display issues that are unrepoducable elsewhere, maybe we can set up a VM of that somehow for testing this stuff.

@ztNFny 
Samsung Note 8, Android 9
My dev machine is too old for virtualization, a new one is waiting for me :-)

The problem is not visible now.
I hope I can create a log if such problem will ocure the next time.
