### ISSUE TITLE
Total amount of stored caches missing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11936]
### Describe your problem!

In the old main activity the lists icon used to show the total amount of stored caches. This was IMHO very helpful to see whether there is some leftover to clean up or also just to see the utilization.

For beginner users it could be helpful to see the figure once they stored caches for the first time or also just to verify that the caches they wanted to store have been stored.

If its technically possible with the bottom navigation I vote for not losing this feature.

### How to reproduce?

see above

### Reproducible

Yes

### c:geo Version

2021.10.19-NB

**Comment by moving-bits** [comment]
Ok, looks like we haven't found the best solution yet. There is a clear request to display the counter for caches stored offline, but both solutions prepared so far do not seem to fit really (one being too prominent, the other consuming too much space in the connectors' list). So let's try to find a more suitable solution.

Does it have to be a counter totalling all stored caches, independent from source connector, or can there be separate counters per connector? If so, we could add it to the connectors' page, extending the "205 finds + 1 offline" by the stored counter, leading to something like "205 finds, 2000 stored" or "205 finds + 1 offline, 2000 stored". 

@Lineflyer What do you think?

**Comment by SammysHP** [comment]
We already show the number of caches for each list in the list selection menu. We could extend the "all" entry with the total number of stored caches.

**Comment by fm-sys** [comment]
> We already show the number of caches for each list in the list selection menu. We could extend the "all" entry with the total number of stored caches.

You are referring to the quick-list-selection dialog, correct? Like this idea!

![Screenshot_20211106_171610_copy_539x435](https://user-images.githubusercontent.com/64581222/140616429-2825db2e-0b97-4ac6-a7f8-f8f902584577.png)

**Comment by moving-bits** [comment]
> We already show the number of caches for each list in the list selection menu. We could extend the "all" entry with the total number of stored caches.

Nice idea. Especially as it avoids the need to load thousand of caches into memory for displaying the "All" list just to get their count (and probably garbage collecting them immediately).

**Comment by fm-sys** [comment]
In this case, we probably should move the "special lists" to the top to be always visible.

**Comment by SammysHP** [comment]
> You are referring to the quick-list-selection dialog, correct? Like this idea!

Yes, but not only the quick selection menu. The drop-down in the list activity has the same feature and already shows the total number of caches.

**Comment by moving-bits** [comment]
Actually, we sort of do have this already: If you are in cache list mode and open the selector in the action bar, you already get the "all" list with the number of caches stored offline. So maybe problem solved already?

**Comment by SammysHP** [comment]
We should add the count to the quick selection as well. That list can be reached easily from everywhere and closed after reading the count.

**Comment by Lineflyer** [comment]
Besides the addition of the count to the "all" list as mentioned above, which I like:

> Does it have to be a counter totalling all stored caches, independent from source connector, or can there be separate counters per connector? If so, we could add it to the connectors' page, extending the "205 finds + 1 offline" by the stored counter, leading to something like "205 finds, 2000 stored" or "205 finds + 1 offline, 2000 stored".

I don't think thats a good solution as it suggests a relation between stored and found, while there is none. Additionally it might not be possible to assign a stored cache clearly to a connector (people might have individual GPX waypoints stored, or caches stored while the connector is (no longer) active, etc).

I would be still in favor of the bubble with number in the bottom navigation (in grey, not in alerting color) maybe with a few tweaks like: Show up to 999 as a number, then start approximating only e.g. 1k, 2k (like we do for the favorite points). If a person has 1k+ caches stored I believe the precise number might be not so important for him.

**Comment by MagpieFourtyTwo** [comment]
Totally agreed. Esp. as the total number is a mayor (if not even the one and only) critical list performance parameter. Therefore it should be presented really obvious, IMO.

**Comment by Lineflyer** [comment]
Can we make a decision on this one?
At least for me personally its a real issue not seeing the amount of stored caches on "home" as explained above.

My last proposal was:
- Lets include it as sticker to the stored icon
- Lets keep it in same color as the icon
- To avoid cluttering cut it off when >999 and show something like 1k, 1.5k, 2k, etc.

Thumbs up = Implement it like this
Thumbs down = No stored cache info on bottom nav or dashboard
Confused = We should show it, but preferring another solution (e.g. on the dashboard itself)

**Comment by fm-sys** [comment]
> * To avoid cluttering cut it off when >999 and show something like 1k, 1.5k, 2k, etc.

I voted thumbs down as it is technically not possible currently, at least if we don't want to use ugly workarounds... See:

https://github.com/material-components/material-components-android/issues/1217

**Comment by moving-bits** [comment]
Default clipping behavior would lead to "999+" display (as max chars is limited to four, and only numbers are accepted by the component) - how useful would that be?

I voted thumbs down, as I think the number is too prominent in the bottom navigation if visible permanently, and as we do have the number available already (list selection, see list "All"). 
Additionally I propose to display that number not only in `CacheListActivity` actionbar, but also on "long press on stored icon" in bottom navigation - then it's easily accessible without permanently interfering, and without the overhead of opening the "All" list.

**Comment by Lineflyer** [comment]
How about using the lines we previously spent for the connector status, like this mock up:
![image](https://user-images.githubusercontent.com/949669/144758060-fdfcba1e-224e-4c7f-a674-26f36470f1da.png)

**Comment by MagpieFourtyTwo** [comment]
@moving-bits 
> Default clipping behavior would lead to "999+" display (as max chars is limited to four, and only numbers are accepted by the component) - how useful would that be?

Not really - at least WRT the motive I have in mind (potential performance issues with e. g. lists if you have >20k caches).
In such a scenario, "1k caches or more" is pretty insignificant, thus not really be helpful.

**Comment by MagpieFourtyTwo** [comment]
@Lineflyer 
> How about using the lines we previously spent for the connector status
Sounds like a good compromise.

**Comment by moving-bits** [comment]
> In such a scenario, "1k caches or more" is pretty insignificant, thus not really be helpful.

It was irony from my side. Stopping to display the actual value when reaching 1k does not help in our use-cases. The badge system of bottom navigation is meant for some different use-cases, e. g. displaying a number of new notifications etc. - here the limitation of 1k is ok.

**Comment by moving-bits** [comment]
> How about using the lines we previously spent for the connector status, like this mock up:

Now we are back at the two scenarios I had implemented PR for: #11965 (dashboard, bottom line) and #11957 (bottom navigation badge). Back then we had not been able to agree upon either of them...

**Comment by MagpieFourtyTwo** [comment]
At the risk of repeating myself: Personally, I would prefer #11957 (as the number of caches is a performance critical number, thus it's place simply can not be too prominent, moreover this way the number takes least space and needs no additional text cause it's meaning is pretty obvious), but if this is not possible (due to number lengths), #11965 (with text near to the border, to have a distance to the connector(s) stuff) would work for me, too.

**Comment by Lineflyer** [comment]
> Now we are back at the two scenarios I had implemented PR for: #11965 (dashboard, bottom line) and #11957 (bottom navigation badge). Back then we had not been able to agree upon either of them...

Yes, I know. But IMHO we should agree on one of them.
As we (or at least I) just learned that bottom nav can only show three digits, showing it on the dashboard is IMHO the way to go.

In contrast to #11965 I would suggest less prominent at the bottom as in my screenshot above. Would that be a compromise for all of you?

**Comment by moving-bits** [comment]
A visually less prominent version could look like this:

![image](https://user-images.githubusercontent.com/3754370/144763799-c3d24a4f-fb80-4622-b582-1c33a31a83fb.png)

(Text could be either way around, this one is just from the original PR. The separator line is important, though, IMHO, for separation of the location-based info at the bottom, and the storage info above - especially when there is no address translation for the coordinates.)

**Comment by MagpieFourtyTwo** [comment]
Like the line. ;)

**Comment by Lineflyer** [comment]
Like it as well.
Would prefer something more dashboard like text like `Caches stored on device: xxx` or maybe even only `Caches stored: xxx`

**Comment by MagpieFourtyTwo** [comment]
At first glance I liked ``Caches stored on device: xxx`` best, which BTW would even fit the phrase used in ``Details`` page:  ``Stored in device about xx minutes ago``. Although it's not a perfect fit, just close, as in the first it's ``on`` while the latter says ``in`` - perhaps these two should be synced then,

But then came to my mind that at nearly all other places, where c:geo has stuff ``on device`` there's always the term ``offline`` used: e. g. ``Offline Logs``, ``Log`` => ``Save offline`` . ``Clear offline logs`` - finally I started to think "Hey, 'stored' are caches and logs are 'offline', thus everything fine - until I got aware that the offline log itself is titled as ``Your *saved* log`` ... ;) ... at least the last one may appear to be a bit inconsistent ... perhaps a sync candidate, too?

However, as for the "dashboard style": The other numbers on the dashboard page are shown as ``xx finds`` resp. ``xx logged offline``, therefore ``xxx caches stored ...`` would fit perfectly fine here, too, IMHO.

TMALSS: I finally would prefer the double match (i. e. matching the other "dashboard numbers" and matching the "Stored message" in Details) and would go with ``xx caches stored in/on device`` (while I would prefer ``on device`` in both messages).

**Comment by fm-sys** [comment]
It's true that we don't use the phrase "stored on device" but rather "stored offline" at most places.

So I would favor "xx (caches) stored offline" (to keep aligned with "xx logged offline")

**Comment by moving-bits** [comment]
Ok, let's use our NVS (new voting system) to get a decision for the text:

- thumbs up is for number prepended: xx caches stored
- thumbs down is for number appended: caches stored: xx

And do a separate voting for additional info:
- rocket 🚀 for no additional info
- racing car 🏎️ for an extra "on device"
- speedboat 🚤 for an extra "offline"

**Comment by moving-bits** [comment]
Ok, according to voting we have 5:1 for number prepended an 5:2 for no additional text. PR will follow.
