### ISSUE TITLE
Preset for map settings

### ISSUE THREAD

**Issue by mjarmstr** [cgeo/cgeo#11931]
### Tell us your idea!

When I'm finding caches, I want a different setting for the map than when I'm hiding caches.  I've been bouncing back and forth between the two modes of operation lately and find myself constantly toggling about half the settings.  For hunting caches, I disable Found/Found (offline)/Own/Disabled and enable waypoints.  For hiding, I enabled all the caches types, disable waypoints, and enable circles.

I would like to be able to set up two different presets/modes and be able to toggle between.

### What solution would you suggest?

A button could be added to the quick settings menu to toggle between the modes.  Or you could swipe left/right on the menu.  

### Is there an alternative?

Currently I bring up the Quick settings menu and toggle all the settings.

**Comment by murggel** [comment]
> In fact most of your changes can already be done there with some clicks.

E.g. create dedicated filter and switch filters

**Comment by mjarmstr** [comment]
I agree it is a bit of a special use case, but I can't be the only one
using c:geo to hide caches, otherwise I don't know why it has the circles
option at all.

I spent some time looking at the saved filters and the problem is that they
don't control the display of waypoints or the circles.  They are for
filtering which caches are displayed.  The quick settings also controls
other displayed elements.

Perhaps my suggested implementation could be generalised a bit.

**Comment by MagpieFourtyTwo** [comment]
Why not just use the long click feature of filter name string and/or filter icon?
And the circles ... I have them always active, colored in a way that you have to look twice to notice them.
This way I have them when I need them, and in the rest of the time they do not bother me.

**Comment by bekuno** [comment]
> I spent some time looking at the saved filters and the problem is that they don't control the display of waypoints or the circles. They are for filtering which caches are displayed. The quick settings also controls other displayed elements.

It is correct, that this controls are contained in the fast settings, but not in the advanced filter.
It should be possible to add them to the advanced filter, imho.

**Comment by eddiemuc** [comment]
> Technically, it would be possible, but it would mix filtering (which caches do you want to see) with display options (what of the remaining caches do you want to see) - not a good idea, IMHO.

100% Agreement.

**Comment by mjarmstr** [comment]
Seem like this isn't going to get any traction.
