### ISSUE TITLE
Add a filter for corrected coords (besides Mysteries)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11940]
### Tell us your idea!

From support mail:

I do have a request for future updates: Allow the filter for corrected coordinates to pick up ANY cache type, not Mystery only. I use corrected coords for Multis, Letterboxes, and Wherigos, and sometimes, even Traditionals.

### What solution would you suggest?

I think the prepared filter for "Solved mysteries" has a relevant use case.
But maybe another filter could be added to filter all caches with modified coords ignoring the cache type.

### Is there an alternative?

No filter for this case available

**Comment by eddiemuc** [comment]
> Maybe even a combined "has corrected"/"has final waypoint" filter?

This would then be identical to the existing "solved mystery" filter, except that it is applied to all cache types (not Just mysteries). Should we simply change the "solved mystery" filter in this way?

You may keep adding as many status filters for as many special cases as you like. We already have 11 status filters, the list is quite impressive & huge. However  at some point it will no longer fit on screen...

**Comment by ztNFny** [comment]
Why does the existing filter apply to mystery only anyway? To get only solved mysteries use the corrected+type=mystery filter.

**Comment by eddiemuc** [comment]
> why does the existing filter apply to mystery only in the first place? To get only solved mysteries use the corrected+type=mystery filter.

I remember from discussions: the filter, if applied, is meant to create some kind of  "all caches which can currently be found / where I have coordinates for" view for the user. If applying the filter to ALL cache types, then **only** solved mysteries (and few other caches which might have corrected coords or final waypoint) will be visible on the map. All the "normal" tradis etc will not be visible any more.. 

Creating a "all caches currently findable" view would no longer be possible if the filter is applied to all cache types - at least not very easy (you might use an OR filter where a cache type filter is combined with the new corr-coords-filter but that's rather advanced, and map quick settings won't work any more).

**Comment by ztNFny** [comment]
Hm, that's a valid usecase for the current setup. So that isn't a "show solved mysteries" but rather a "hide unsolved".
With that explanation the existing one shouldnt be changed imho.

**Comment by Lineflyer** [comment]
Also from my side: 
As written in the initial post I thinnk the "solved mysteries" filter should stay as it is. Many users gave feedback, that this is a perfect new feature.
This means it would need an additional filter for "All with corrected coords".

**Comment by jakedot** [comment]
Has this functionality been restored in the meantime?

**Comment by murggel** [comment]
Indeed it is available in the meantime.
For mysteries a valid final also counts as "corrected coordinates", even if it is not set as corrected coordinates.
@eddiemuc  can we close here?

**Comment by eddiemuc** [comment]
Yes we can
