### ISSUE TITLE
Evaluate splash screen API on Android 12

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11968]
According to https://developer.android.com/about/versions/12/behavior-changes-all#splash-screen-migration Google recommends to check the apps behavior on Android 12 if it uses a custom splash screen as the interworking with the new Android 12 default splash screen might occur.

Not sure if this means anything for us...feel free to close if it proofs to be not relevant.

**Comment by moving-bits** [comment]
Can we close here, or are there any issues with splash screen on Android 12?

**Comment by Lineflyer** [comment]
As written above the auto-splashscreen on API31 looks fine.
