### ISSUE TITLE
Align widget/shortcut icons with new material bottom nav icons

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11969]
Edit note: Now this issue is about the widget / shortcut icons only

Simple question:
Do we want to stay with the current (kind of standard) icons on the bottom navigation?
On one hand it looks simple and modern, on the other hand c:geo looses a bit of its character without the custom icon and it looks just like any other app.
Don't get me wrong, I think the old icons cannot be reused but maybe some monochrome upgrades of the legacy icons?

The reason why this came to my mind is, that we still use the legacy icons for the widgets. So those should be replaced anyway.

**Comment by bekuno** [comment]
I propose to use our c:geo box as Start/Home button icon (b/w without map background), to have our branding a bit visible.

**Comment by Lineflyer** [comment]
> do not understand the old "stored" icon at all.

Its a book shelf with GPS pins in it ;)

> I propose to use our c:geo box as Start/Home button icon (b/w without map background), to have our branding a bit visible.

I think we already dropped that meanwhile.

Coming back to the topic...we need to either update the widget icons or let them stay the same as small rememberance to those who use them.

**Comment by ztNFny** [comment]
> we need to either update the widget icons 

It's on my to-do list

**Comment by ztNFny** [comment]
The common theme these days seems to be simple monocolored icons in the primary color. I'll try how it looks in that style with either orange or the darkest of greens in the lid.

**Comment by ztNFny** [comment]
Experimenting with some approaches here, would like to get some quick feedback
![image](https://user-images.githubusercontent.com/1258173/151451958-b476c592-608c-42d1-afda-3920dc8330bd.png)
![image](https://user-images.githubusercontent.com/1258173/151452079-55519d5c-33d1-48e5-bfe3-f018a01daf61.png)

orange bg + green icon = thumbs up
orange icon = thumbs down
green icon = smiley
orange bg + white icon = party

**Comment by fm-sys** [comment]
I've voted for "orange icon", but like the "orange bg + white icon" as well. 

However, I think we should use a single-color background. Means orange background without the white "zickzack" line would (probably) be my favorite. Could you share such a version as well?

**Comment by eddiemuc** [comment]
Multivotes are allowed I hope?

**Comment by bekuno** [comment]
The contrast from white/green to the orange background is not very high. Can you made a proposal with black/or dark gray icon?
When using a white forground then I vote also for a solid background.

**Comment by ztNFny** [comment]
As votes are equal between orange icon and orange background I'll go with the orange icon on grey bg - which is what the Material Design guide recommends as well.

**Comment by Lineflyer** [comment]
See https://github.com/cgeo/cgeo/pull/12623#issuecomment-1025009003 for remaining tasks.

**Comment by Lineflyer** [comment]
Remaining tasks are fixed by #12640 as stated in https://github.com/cgeo/cgeo/issues/12649#issuecomment-1028350890
