### ISSUE TITLE
Hide ZZ0 cache from lists (to prevent accidental deletion)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11999]
### Describe your problem!

From time to time users contact us, claiming that some or all waypoints noted down in the "GoTo"-targets (Internal cache: ZZ0) are suddenly gone while the user did not explicitly delete them.
Some of the users claim, that it happend during upgrade to a new c:geo version, some are not sure what might have triggered it.

From my understanding the ZZ0 cache should behave like any other cache and also be stored into the database permanently.

Can someone confirm this assumption?
Doe anyone have an idea if there is any trigger clearing the GoTo which might cause this problem?
I could imagine a problem in our DB upgrade code, as this problem is not reported for all new versions but only sometimes.

### How to reproduce?

unclear

### Reproducible

Unclear

### c:geo Version

2021.10.08

**Comment by Lineflyer** [comment]
Indeed hiding would maybe the best option as accidental deletion might be the cause of the issues reported by users.
Changed topic accordingly

**Comment by moving-bits** [comment]
following the discussion in our last team meeting and the decision to drop a specific "go to" functionality in the mid-run, I'll close here as "won't fix"
