### ISSUE TITLE
Try to remove switching the website to english

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12000]
### Tell us your idea!

In former times we used a lot of parsing mechanisms at various places. At that time it seemed to complex to either support multiple languages in parsing or trying to make the parsing language independent (e.g. by building RegEx based on static/not language dependent elements).

AFAIK due to using "other" mechanisms the real parsing was reduced to primarily only the cache details page (incl. logbook, etc.). and maybe the login process.

From time to time we still receive support mails about c:geo modifying the language of the website and the user needing to set the language again each time he uses the website. Furthermore I know, that Groundspeak support also frequently receives such "bug reports" from users, who are not aware of the cause.

### What solution would you suggest?

That being said:
Do you see any chance to get rid of the necessity to switch the website language by trying to build the remaining parsing onto language independent anchors?

### Is there an alternative?

Keep it as it is

**Comment by MagpieFourtyTwo** [comment]
@Lineflyer Perhaps you may recommend "GC little helper II" to complaining users - among a lot of other extremely useful stuff to make live easier on gc.com (to be honest: would not use the website at all without it), it easily be configured to set the website's language to Amy configured one automatically on each visit.

Admittedly, GClh looks complex at first sight, but after installation even the defaults work really good, so they can dive into it later - and rest assured, they will, cause possibilities are great and once you began ... ;)

**Comment by Lineflyer** [comment]
Thanks for pointing out the other places of importance (like trackable parsing).
I am fine with closing this, just wanted to get your expertise as I was unsure about the extend of parsing still used. 

In fact I sometimes think most users of c:geo aren't even aware, that the website is available in other languages (as we constantly change it) or they are just fine with that. I only though it might make our lives (and the code) easier, if we are able to get rid of it. But time has not come yet.

**Comment by SammysHP** [comment]
Groundspeak could just start listening to the locale information in the HTTP request header. It tells the preferred language, problem solved. You often find a language selection menu that overrides the detected value for the current session as a fallback.
