### ISSUE TITLE
add icons for (un)watch and (un)favorite for details screen

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12019]
On "Details" tab both the add/remove favorite and add/remove watchlist feature use a "(+)" icon.

They should use dedicated icons instead, in alignment with https://github.com/cgeo/cgeo/pull/11944

![image](https://user-images.githubusercontent.com/1258173/139498814-e00a9a3e-6dc9-4783-843c-f7c8af84b6a5.png)

**Comment by moving-bits** [comment]
The icons being used for adding / removing actually are material.io icons already, named "add circle outline" resp. "remove circle outline" (even available when filtering the list to "filled" mode).

My preferred solution would be to stay with current icons and close this issue.
Alternatively we can exchange the two icons with their non-outlined versions "add circle" and "remove circle" (not necessary, though, IMHO).

**Comment by ztNFny** [comment]
> are material.io icons already

Didn't say they weren't. This issue is about them being generic icons instead of specific to their action. To understand what they do you need to read the text next to them.

I've already added dedicated icons to match those used in the filter dialog:
![image](https://user-images.githubusercontent.com/1258173/140616089-373615fc-0bc1-4e6e-8a23-864870000018.png)

**Comment by moving-bits** [comment]
> Didn't say they weren't.

Ok, my misunderstanding then.

How would the icons look in the "remove" variants?

**Comment by ztNFny** [comment]
![image](https://user-images.githubusercontent.com/1258173/140616468-e5f0de18-b711-4516-a09f-cf252481cd6b.png)

https://github.com/ztNFny/cgeo/tree/materialIcons has several icon tweaks I'm currently working on, hope to finish that this weekend.
