### ISSUE TITLE
set/change icons on "about user" dialog

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12022]
### Tell us your idea!

Sample:
![Screenshot_20211030-010616_cgeo](https://user-images.githubusercontent.com/32555742/139510498-6795c1c1-e27c-49cc-8a83-25960841b1b6.jpg)

- The Entry "Open contact card" has no icon.
- The entries "Send message" and "Send email" share the same icon. 

To show the dialog:
- Open one cache details page
- tap the "Owner" name

### What solution would you suggest?

Suggestions:
- For "contact card" like:
![image](https://user-images.githubusercontent.com/32555742/139510903-3d247ad1-341a-4796-8903-a99c216f3fe2.png)

- for "Send message" like one of:
![image](https://user-images.githubusercontent.com/32555742/139510988-5f54b6ad-9d40-4890-abb4-0976df8cb241.png)

**Comment by ztNFny** [comment]
also related to #11998

**Comment by murggel** [comment]
Or for send message?
![Screenshot_20211031-140001_Chrome.jpg](https://user-images.githubusercontent.com/70113341/139584662-445c1b95-cf3c-4093-8c03-159d027bce48.jpg)

**Comment by ztNFny** [comment]
> Or for send message? ![Screenshot_20211031-140001_Chrome.jpg](https://user-images.githubusercontent.com/70113341/139584662-445c1b95-cf3c-4093-8c03-159d027bce48.jpg)

That'd be mail, not message imho.

I'd suggest a "chat bubble" for message and the envelope for mail
![image](https://user-images.githubusercontent.com/1258173/139585499-5592e476-c7cf-4f0f-a03d-e7572aa50954.png)
![image](https://user-images.githubusercontent.com/1258173/139585514-f4231a62-3d58-4fe0-a1fe-5fff8c3292d5.png)

for contact card I'm thinking of something like 
![image](https://user-images.githubusercontent.com/1258173/139585615-6747a8cc-bcdf-4998-ad2f-86a68ba03929.png)


In #11998 I'll take a look at many icons, will cover this one as part of it.

**Comment by Lineflyer** [comment]
> In #11998 I'll take a look at many icons, will cover this one as part of it.
