### ISSUE TITLE
Google Maps SDK v18 announcement

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12023]
### Tell us your idea!

Received an info a few days ago that Google will migrate all Android devices to their new SDK implementation starting March 2022. Some code changes may be necessary for us. 

Here's the full info:

---

Hello Google Maps Platform Customer,

We're writing to inform you that we released a major update of Maps SDK for Android (version 18.0.0), and it is now available via Google Play services. This Maps SDK update features a new map renderer, which will become the default renderer for Android devices* through a progressive rollout, starting in March 2022 at the earliest.

Update to the new SDK (version 18.0.0) now to test and deploy the new SDK and renderer with your apps before the new renderer becomes the default for Android devices*.

We’ve improved how we serve tiles to your apps and render the map on client devices with the new SDK. Therefore, Android devices will benefit from:

    Reduced network load, processing demand, and memory consumption.
    Improved gesture handling for better animations, plus smoother panning and zooming.
    More fluid transitions and clearly positioned map labels.
    A more stable and improved user experience for future map innovations on Android.

The new SDK also includes the general availability of Cloud-based maps styling on mobile (Android and iOS). Usage of Cloud-based maps styling for a map in Maps SDK for Android is billed with the Dynamic Maps SKU. For more information on pricing and included features, see our Cloud-based maps styling documentation.

*All devices on Android 5.0 (Lollipop) or later with 2 GB or more of data storage will use the new renderer. All other devices will continue to use the legacy renderer until further notice.
What do I need to do?

To anticipate and avoid issues with your apps we advise you to:

    Use the new SDK.
    Specify the new renderer in your code.

Before the beginning of the new SDK progressive rollout in March 2022. See our documentation for instructions on how to try the new renderer.

If you encounter any issues in your apps with the new SDK or the new renderer, please report them to us, and consider pausing the apps’ deployment to users until the issues are resolved.

### Additional Information

See https://developers.google.com/maps/documentation/android-sdk/renderer

**Comment by fm-sys** [comment]
(without having any knowledge about the topic) Would this be an opportunity to unify our both map implementations again?

**Comment by Lineflyer** [comment]
I think we should wait with this until we have the bottom nav on `release` branch. Already quite some major changes on `master` at this moment which can have potential regressions.

Don't get me wrong: 
I am always open to improvements, but from quality and testing point of view the current `master` package is already quite large which includes some probability of still unknown regressions and bugs. Thus I am always a friend of not putting to much major changes into a single release or respectively doing shorter release cycles (which does not work reliable at this moment as things like bottom nav need their time).

**Comment by ztNFny** [comment]
`We're writing to remind you that a major update of Maps SDK for Android (version 18.0.x), available via Google Play services, features a new map renderer that will become the default renderer for Android devices* through a progressive rollout, starting in June 2022 at the earliest.`

**Comment by moving-bits** [comment]
PR that upgraded the rendering engine needed to be reverted due to issue #14534, therefore reopening here.
