### ISSUE TITLE
Waypoint icons on map missing their "pin" on Mapsforge

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12030]
### Describe your problem!

Since latest nightly update the waypoints on the map are missing their "position pin".
The cache icons are OK.

![image](https://user-images.githubusercontent.com/949669/139827483-7c6f5485-e982-4ae8-87e0-b93484b15565.png)

### How to reproduce?

Look at the map with activated waypoints :)

### Reproducible

Yes

### c:geo Version

2021.11.02-NB1

**Comment by ztNFny** [comment]
if this is only with mapsforge (I tested with Google Maps only, Mapsforge was crashing at the time) then in https://github.com/cgeo/cgeo/pull/12006/commits/e54ccd9766b2b646e29f6467e7d8ba635c1d7390#diff-4721ee12c7c48c0d17e90713a06d1430abc11199e28ff4c4115af724621df441 line 399 the second parameter needs to change to "true"

**Comment by Lineflyer** [comment]
Yes, Google Maps is fine.

**Comment by eddiemuc** [comment]
I will provide a PR in a few minutes

**Comment by eddiemuc** [comment]
PR #12033
