### ISSUE TITLE
waypoint description indented

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12038]
### Describe your problem!

Text should not be indendet more than coords
![Screenshot_20211103-000556(1)](https://user-images.githubusercontent.com/1258173/139964029-4e063710-29c0-4ee9-9269-76b2adbe32fa.jpg)

### How to reproduce?

.

### Reproducible

Yes

### c:geo Version

NB 2.11.

**Comment by Lineflyer** [comment]
Fixed by 44b2ba5cc4757b754b848d5a8c7ff6782047e05e
