### ISSUE TITLE
outline on map buttons

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12041]
The two buttons at the bottom of the map have some outline around them that no other button has (at least I couldn't find any). What's the point of that?

imho it looks quite strange, the outline should be removed, those buttons are the same as the zoom buttons and they don't have any border either.
![image](https://user-images.githubusercontent.com/1258173/140194032-fcc83549-2fc4-4180-8f39-f7d726cb4341.png)

@moving-bits you implemented this?

**Comment by fm-sys** [comment]
Interesting though: In dark mode, the outline is (nearly) invisible anyway... 

![Screenshot_20211105_080732_cgeo geocaching](https://user-images.githubusercontent.com/64581222/140471848-eab520ad-9c43-4424-9c03-01fb9c494d5d.png)

**Comment by ztNFny** [comment]
The outline comes from the "Button" element from some Material library. In light mode that outline is dark, in dark mode it's light. The white background behind the buttons is hardcoed.

I'm working on a proposal that makes it look similar to the zoom buttons, but am having some trouble fighting with the layout stuff ;-)

**Comment by ztNFny** [comment]
In work. Will align it with the map zoom controls

**Comment by moving-bits** [comment]
> The two buttons at the bottom of the map have some outline around them that no other button has (at least I couldn't find any). What's the point of that?

They got formatted using our default button style, the same you have on cache's detail page etc.

> imho it looks quite strange, the outline should be removed, those buttons are the same as the zoom buttons and they don't have any border either.

Changing the zoom element came later, and it got formatted to look as close to the GM zoom controls as possible. 

But feel free to adapt the styling to remove the outline.
Not sure about the size, though. I'd formatted those two buttons to be the same size as we have on cache's pages (for consistency and easy handling), but by this they are larger than the zoom controls (for the reasons mentioned above), so I guess we need to decide which sort of consistency we'd like to achieve.

**Comment by moving-bits** [comment]
> In work. Will align it with the map zoom controls

Generally looking fine, but I propose a few changes:
- "quick settings" button was placed centered deliberately, as many users seem to not use any individual routes, which means only one button is displayed in that case. If "quick settings" button position is fixed, if would be off-centered then (without a second button), and if it's not fixed, but moving to the left when "indiv. route options" button appears, we would have moving buttons, which I would like to avoid.
  Therefore I propose to use the old placement:
  - "quick settings" button is centered, fixed position
  - "indiv. route options" button is place to right of "quick settings button", only appearing when an indiv. route is configured
- There should be more spacing between the two buttons, as we do not have a related toggle (e. g. zoom control +/- buttons), but buttons for two totally different functions.

**Comment by ztNFny** [comment]
> They got formatted using our default button style, the same you have on cache's detail page etc.

Hm, maybe the "inner" shape is a normal button, but the outline around it makes it look very strange. Either the border or the white around it needs to be removed (and as the zoom buttons have only the white I'd suggest to remove the border)

> so I guess we need to decide which sort of consistency we'd like to achieve.

I'll try to harmonize the size of Google Maps zoom buttons, OSM zoom buttons and map settings buttons.

> "quick settings" button is centered, fixed position

I only looked at making it "not look strange" so far, didn't intend to change the position, will make sure that stay.

**Comment by ztNFny** [comment]
Tweaked the buttons to have the same size as the map zoom buttons (tweaking the OSM zoom buttons to be more in line with Google Maps in #12064)

I tried both the "seperate buttons" and "joined buttons" look, see screenshots attached. I think I have a slight preference for the "joined buttons" look, but as I don't really use routes I don't care too much.

Let's try the usual thumbs up (for seperate) / thumbs down (for joined) vote

![Screenshot_1636301416](https://user-images.githubusercontent.com/1258173/140653013-1ef49c59-dac8-43b4-b219-45098fa00183.png)
![Screenshot_1636301457](https://user-images.githubusercontent.com/1258173/140653015-bfab2c7c-1a49-4ef5-b843-755f35803a90.png)
![Screenshot_1636301696](https://user-images.githubusercontent.com/1258173/140653016-48cfc9e0-4c2f-4a5d-bdef-b3581278da08.png)

**Comment by fm-sys** [comment]
> 
> 
> 3 thumbs up, looks good. However for a PR I need #12064 merged first as I need to rebase on that _hint_

Here we go. PR #12064 looks fine and is merged...

**Comment by ztNFny** [comment]
#11907 requests that the buttons aren't placed at the bottom of the screen when bottom nav is enabled. Not sure whether that's feasible (I don't know how to detect that). Should the buttons always be not at the bottom (but instead at the same height as the [-] zoom button) ?

**Comment by moving-bits** [comment]
I would simply add a small margin at the bottom, maybe only 1 or 2 dp, applied independently from whether bottom navigation is being displayed or not.

Putting it at the same height as the zoom buttons will lead to a lot of "white space" at the bottom (which many people try to avoid), and adjusting it to the scale indicators may be difficult to get consistent across OSM and GM.

**Comment by moving-bits** [comment]
Edit: margin should be applied to the layout file, not to the button XML file.

**Comment by ztNFny** [comment]
> adjusting it to the scale indicators may be difficult to get consistent across OSM and GM.

I've already aligned those in https://github.com/cgeo/cgeo/pull/12064 :-)

Will look into button placement tomorrow as part of this

**Comment by moving-bits** [comment]
> > adjusting it to the scale indicators may be difficult to get consistent across OSM and GM.
> 
> I've already aligned those in #12064 :-)

I did not mean the +/- buttons on the right side but the scale on the left side, which is different between GM and OSM.
