### ISSUE TITLE
Unwanted Shift of Map to GPS Position

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#12054]
### Describe your problem!

Map is shifted to GPS position when map is changed

### How to reproduce?

Live map, change map to google map, lock map to position
Close c:geo
open c:geo
Live map
Shift position (with shift of the map the lock sign is switched off)
At new position: change map to OSM map

### Actual result after these steps?

Map locked to GPS is switched on again.
Map is positioned at the current position

### Expected result after these steps?

Map locked to position should be still switched off and position of map should be unchanged.

### Reproducible

Yes

### c:geo Version

2021.10.28-NB-1ac0319

### Additional Information

Seems like the switch off of the locked position by shifting the map is not stored correctly.
I'm not sure when it hapens if the lock has been switch off directly (not by moving the map but by clicking the switch).
I noticed this a long time ago but was now able to find a way to reproduce it.

**Comment by ztNFny** [comment]
Reproducable with slightly different steps:
1. Open Live Map
2. Switch to a OSM map
3. Enable location lock
4. Switch to Google maps
5. Scroll the map
6. Switch to a OSM map

**Comment by geocachermgo** [comment]
ztNFny way reproduces the error also at my device.
Independent if google map or satelit view and offline or online osm is chosen.
Additional observation: even if after step 5 of ztNFny I activate and deactivate the lock in google, the lock is active again when changing back to OSM.
That is contradicting my suspicion that just the automatic deactivation by shifting the google map is not working.

**Comment by geocachermgo** [comment]
1) Open Live Map
2)  Switch to a OSM map
3)  Enable location lock
4)  Switch to Google maps (map or satelit)
5) Disable location lock (tap to lock or map scroll)
6) Switch to a OSM map (online or offline)

**Comment by Lineflyer** [comment]
Let continue in #12768
