### ISSUE TITLE
different layers not centered to each other depending on density

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12068]
![image](https://user-images.githubusercontent.com/1258173/140658627-3b28f6b9-f624-4dd3-bf36-3f167f1443e7.png)

**Comment by ztNFny** [comment]
all is good with the vector drawables themselves, this is a fundamental problem with how the LayerDrawables are build.

Today the different layers (marker, background, icon) are SVGs/Vector Drawable of different sizes (36, 23.4, 22). If you put those SVGs on top of each other everything is perfectly centered.
But with LayerDrawable what happens is that every Vector Drawable is loaded independently, it's size converted according to the devices display density and only then they are overlayed. With density 360 I get as sizes 81, 53, 50 (getIntrinsicWidth()) - and 50 can't be centered in a 81 box. With 450 it's a similar situation - 101, 66, 62. So the layers end up slightly off-center.

I see 3 possible approaches to this (without giving up on Layer Drawables):
- Use a "better" version of LayerDrawable that first puts all layers on top of each other, then renders the drawable. -- this seems like the best option to me, but no idea whether one exists though
- Add a margin around all the Vector Drawable ressources so they all are the same size as the marker (36) -- Easy to implement (but a lot of work), will require a few extra resources for other places where those icons are used.
- In MapMarkerUtils if marker is odd but background/icon are even add 1px to the size of background/icon so it can be centered -- kinda ugly workaround

@Lineflyer @moving-bits @fm-sys any ideas/opinions on this?

**Comment by moving-bits** [comment]
Thinking of today's pixel densities I can happily live with such a deviation, even though I agree that strictly speaking this is not perfectly centered.

Regarding the proposed options:
- different version of LayerDrawable => don't know if there's such a thing. IIRC we have already looked for one at some earlier occasion, but did not find any. Would not dive into the effort of creating our own drawing routines in that case, though.
- extra margin => might be the most viable and consistent solutions, but creates lots of extra work for you for the existing drawables, and possibly for creating / selecting extra versions for other places, where the drawables without extra margins are needed
- extra 1px => what would be the visual impact of resizing the background drawables? How many places in the code would be affected

Personally I would not put too much work into it, neither in terms of "coding" nor in terms of runtime performance (if affected by any of the solutions), as the visual glitch does not rectify that, IMHO. But that's just my 2ct, no offense intended :-)

**Comment by ztNFny** [comment]
That misalignment is quite noticable, at least to me, so i won't leave it like that.

> what would be the visual impact of resizing the background drawables? How many places in the code would be affected

The visual effect should be quite small, eg 62 to 63 px is a 1,6% change. Would have to be changed in at least 4 methods in MapMarkerUtils.

**Comment by eddiemuc** [comment]
It might be possible to dynamically change SVG files at runtime (e.g. change their viewport size), because they are just XML which can be manipulated at runtime accordingly. Would this help solving the issue? (was just an idea I had this morning)

**Comment by ztNFny** [comment]
For SVG yes, but Android vector drawables are less powerful, position is written into each elements path. 
I'll look at resizing the SVGs to 36 later today.

**Comment by fm-sys** [comment]
> For SVG yes, but Android vector drawables are less powerful, position is written into each elements path.

With some workarounds, it would probably be possible to change the `IntrinsicHeight` at runtime... 

https://stackoverflow.com/a/59026862/13513639

**Comment by ztNFny** [comment]
> With some workarounds, it would probably be possible to change the IntrinsicHeight at runtime...

That's what I meant with my 3rd option, "add 1px to the size of background/icon"

I think in the end changing the source SVGs while ugly is probably the easiest and clearest solution.

**Comment by ztNFny** [comment]
- [ ] resize all LD main vector elements to 36
- [ ] create new resources for filter dialog
- [ ] use a color reference instead of #fff in icon foreground definition
- [ ] check for other uses

**Comment by ztNFny** [comment]
Should the user-defined icon in filter dialog be hexagon for easier recognition?
![image](https://user-images.githubusercontent.com/1258173/143913294-7f26e129-5c90-4b83-a4c5-17e488c8c486.png)

**Comment by moving-bits** [comment]
> Should the user-defined icon in filter dialog be hexagon for easier recognition?

Does make sense, probably. Although it does break visually with the other type icons in the filter, it would not make sense to use the circle background here, when you'll never actually see the circle "in real life" for UDC.

**Comment by ztNFny** [comment]
I won't fix the "big icons" mode, opened a new issue for that: #12199
