### ISSUE TITLE
Improve readability for archived caches for color blind people

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12084]
### Describe your problem!

From support mail:
Red cache names text/font are now your default for archived caches. I am colour blind and cannot read them. Could we fix or at least option that colour choice?

---

Maybe it would be enough to keep it in default color with strike through as there are other indicators:
- Red cross through icon
- Status "Archived" on the details tab

### How to reproduce?

see above

### Reproducible

Yes

### c:geo Version

2021.10.08

**Comment by fm-sys** [comment]
Al least in the actionbar, it has always been red font. It would be very sad to loose this feature.

Or is he referring to the detail section below?

![Screenshot_20211113_125544_cgeo geocaching](https://user-images.githubusercontent.com/64581222/141642874-0b1ba121-d528-4729-9bdc-ca03a7562a79.png)

In this case he might want to try cgeo's light mode.

Instead of dropping the red color we can add some more color components like a bit yellow. That would already significantly help to improve contrast for color blind people... (I guess)

**Comment by fm-sys** [comment]
And independ of color blindness, the red is indeed  quite dark currently. But there are much more colorful read tones:

![Screenshot_20211113_130112_org mozilla firefox](https://user-images.githubusercontent.com/64581222/141643041-d1b823a2-11af-4fec-9d97-9258dd9d2421.png) 
![Screenshot_20211113_130417_org mozilla firefox](https://user-images.githubusercontent.com/64581222/141643111-f29a16c6-a3f5-4842-b325-fab3d764eeb2.png)

**Comment by moving-bits** [comment]
> I am colour blind and cannot read them.

Is the user not able to read the cache's name at all, or is it just the user not being able to distinguish between disabled and archived caches?

**Comment by ztNFny** [comment]
> And independ of color blindness, the red is indeed quite dark currently. But there are much more colorful read tones:
> 
> ![Screenshot_20211113_130112_org mozilla firefox](https://user-images.githubusercontent.com/64581222/141643041-d1b823a2-11af-4fec-9d97-9258dd9d2421.png) ![Screenshot_20211113_130417_org mozilla firefox](https://user-images.githubusercontent.com/64581222/141643111-f29a16c6-a3f5-4842-b325-fab3d764eeb2.png)

That'd be hard to read in light theme. Maybe different red hues based on theme and pick a lighter one for dark theme, e.g. #EF9A9A

**Comment by ztNFny** [comment]
but we should get more info from the user where exactly he has problems and what scheme he's using to make sure we change the right thing

**Comment by Lineflyer** [comment]
Solved meanwhile by https://github.com/cgeo/cgeo/pull/13550
