### ISSUE TITLE
"Logs count" filter behaving strange

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12086]
### Describe your problem!

While retesting for some Play Store feedback, I've stumbled upon the "logs count" filter behaving unexpectedly. (Or maybe I simply misinterpreted the intended behavior.)

The user's request was to filter for caches not having any logs available ("looking for FTF"). So I tried the sequence described in the "how to reproduce" section.

### How to reproduce?

- open a list of stored caches
- open filter
- delete all existing filters
- switch to advanced (if necessary)
- add a "logs count" filter, switch to "all" and set counter to "0"

### Actual result after these steps?

- some caches are filtered, others are not. Those caches not being filtered out do not necessarily have no stored logs (as I would have expected)
- filter description line shows "Logs Count:* 0", but sometimes switches to "Logs Count:Found it:* 0" without any change from my side

### Expected result after these steps?

- only caches having no logs stored offline should be displayed
- filter should remember the "all" selection and count accordingly

### Reproducible

Yes

### c:geo Version

2021.11.04-RC

**Comment by eddiemuc** [comment]
At first glance I found multiple problems:
* The setting "all" is not remembered correctly -> this is something I simply need to fix
* There are cache type without stored log entries. When filtering using "log count = 0", those caches are always selected. for example this is the case for adventure labs. Don't know how this should be handled, any idea?
* Some caches, although stored offline" don't seem to have log count entries. I don't know why. Following screenshot shows an example of the log page of such a cache (note the missing "log counts" line at the very top):

![image](https://user-images.githubusercontent.com/6909759/141652555-d8c9115a-5ea1-43d5-bd37-e3d49eca7b0e.png)

If I refresh the very same cache, the log counts are loaded. Then the "log counts" line is present and the cache gets correctly filtered out using "log count = 0" filter:

![image](https://user-images.githubusercontent.com/6909759/141652594-9287ba00-2b63-44ef-80f3-36327c41158f.png)

**Comment by ztNFny** [comment]
The missing log count happens on GPX import.

**Comment by eddiemuc** [comment]
Simple idea would be to mark caches as "inconclusive" if no entry exists in table cg_logCount for them. I guess this would make the most sense. But then I need to add the "inconclusive" concept to database selections first

**Comment by eddiemuc** [comment]
PR #12089 will solve the "all" problem.
It will also solve the other problem by simply not returning any cache without a logs count once this filter is applied. A more sophisticated solution needs discussion first if need be.
