### ISSUE TITLE
Test regarding log template broken

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12097]
It seems the PR #12067 has broken a test for twitter message posting:
https://ci.cgeo.org/job/cgeo%20CI%20-%20Commit%20build/38/

Strange enough the PR itself was passed on CI, the problem only came up on the commit build afterwards. Why is that?

**Comment by fm-sys** [comment]
Yes, that's the same issue we discovered in https://github.com/cgeo/cgeo/pull/12095#issuecomment-968366317

**Comment by ztNFny** [comment]
Think i found it, PR incoming

**Comment by bekuno** [comment]
See https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/65/console

The APK install run on error, but this was not catched as ERROR on finish.

**Comment by Lineflyer** [comment]
> The APK install run on error, but this was not catched as ERROR on finish.

We should find a way / a setting to mark such builds as error to eliminate such false positives :(

**Comment by ztNFny** [comment]
PR seems good
