### ISSUE TITLE
Filter setting: "Always show stored caches" even when they don't meet the filter settings

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#12090]
### Tell us your idea!

The new filter settings are great. However, when I voluntarily stored a cache on my device, that's because I *definitely* want to see it, no matter how the filter settings are currently set up.

### What solution would you suggest?

In the filter settings, there should be a checkbox "Always show stored caches" which, when enabled, has the effect that stored caches are always visible, no matter if they meet the current filter criteria.

**Comment by eddiemuc** [comment]
Technically this would be an OR filter with the "last updated" filter on one side and the remaining (maybe complex) filter on the other side.

I am not sure whether this new setting would be a good idea. Some things coming to my mind:
* In "stored list", if this new setting is chosen, it would render all remaining settings ineffective.
* How should this work in conjunction with map quick filter settings. As of now those are disabled for OR filters for good reason. For example, if new option is enabled and user disables "found" -> should then found stored caches really still be shown?

Maybe such requests could be solved if users had the chance to define arbitrary complex OR/AND/NOT filters themselves as e.g. defined in #10581 or #11275

**Comment by dcjkfgdjhd** [comment]
>     * In "stored list", if this new setting is chosen, it would render all remaining settings ineffective.

Yes, that is the point. 

My personal use case: I have disabled the display of unsolved mysteries via filter. However, sometimes I *do* want to see some unsolved mystery as part of a planned tour, e.g. when it is the bonus cache of trail that I intend to do that day. Then I would store the bonus cache (together with all the other caches of the trail) in the phone and by storing it I am more or less declaring "Yes I want that cache", so it should be displayed.

> 
>     * How should this work in conjunction with map quick filter settings. As of now those are disabled for OR filters for good reason. For example, if new option is enabled and user disables "found" -> should then found stored caches really still be shown?

In my opinion yes, they should be shown. Generally speaking: If the user does not need them anymore, they can always delete them. If they don't delete them, it seems reasonable to assume that they still need these caches, and therefore want them not filtered.

Of course, this should be an *option*. For some use cases it would be useful, for others not.

**Comment by eddiemuc** [comment]
> My personal use case: I have disabled the display of unsolved mysteries via filter. However, sometimes I do want to see some unsolved mystery as part of a planned tour, e.g. when it is the bonus cache of trail that I intend to do that day. Then I would store the bonus cache (together with all the other caches of the trail) in the phone and by storing it I am more or less declaring "Yes I want that cache", so it should be displayed.

There are already ways to solve thisuse case in c:geo

First one: "mark" these "special" mystery caches by assigning them a dummy final waypoint (may point to the header coordinate itself). It is then considered a "solved mystery" and displayed using the filter.

Second one: create an OR filter combining the "stored since" filter with the "status = unsolved mystery" filter. If you need this filter very often, you can give it a name and store it for later quick usage. E.g. something like the following:

![image](https://user-images.githubusercontent.com/6909759/141677658-b888fb92-6942-4e70-8f8b-def9bec50719.png)
![image](https://user-images.githubusercontent.com/6909759/141677665-75a9fc4b-faae-46a7-9e5f-5a9b5d8d678a.png)

(Notice the checkmark at "use OR instead of AND")

For the second solution, you can quick-apply it e.g. in map viewer by long-pressing the filter icon. Note that map quick filter settings will be disabled due to this being an OR-filter - but if I understand you correctly this is the wanted behaviour for your use case.

**Comment by eddiemuc** [comment]
A more fine-grained solution (where not all stored caches are displayed but only some of them) would be to create a special list where you store those unsolved mysteries which you want to have displayed DESPITE having a "unsolved mystery" filter active for all the rest. If you have such a list e.g. called "Always Displayed Mysteries", then you can create an OR filter combining a list filter with a status filter like e.g. the following:

![image](https://user-images.githubusercontent.com/6909759/141677898-bc386977-4ad4-4544-999e-4e4441918bea.png)
![image](https://user-images.githubusercontent.com/6909759/141677665-75a9fc4b-faae-46a7-9e5f-5a9b5d8d678a.png)

**Comment by dcjkfgdjhd** [comment]
> Second one: create an OR filter combining the "stored since" filter with the "status = unsolved mystery" filter. If you need this filter very often, you can give it a name and store it for later quick usage. E.g. something like the following:

Thank you! That works well for my use case!

Of course, if my filter would require the AND operation, then I could not do use this strategy. It does not, so I am okay. However I still think that a simple binary switch for "always display stored" might be useful in some cases.
