### ISSUE TITLE
activity to auto-refresh lists

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12094]
### Tell us your idea!

Updating lists is something I want to do regulary but often forget. It'd be nice to have a "commandline call" (an activity) that can be called from e.g. Tasker to automate that.

### What solution would you suggest?

An activity that accepts as parameter the name of a list that can be started from adb shell with "am start"

**Comment by eddiemuc** [comment]
Teammeeting 10.3.24: would be the first "commandline interface command" for c:geo at all. Unsure whether it makes sense to proceed that part. Closing for now, please reopen if further discussion is wanted.
