### ISSUE TITLE
Alignment of icons between live-map and lists/results

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#1210]
As discussed in #1202 I had the idea to align the icon-overlays between live-map and list/results 

With "Final defined" it was started to align the cache-symbols/icons between live-map and lists/results.
It would only be consistent if we do not use different means for displaying the same thing.
In detail I would propose for the display of result-list or stored-list:

- Instead of having the string "Offline" the cache-icon could get the same disk-symbol on the upper right
- Instead of showing the "Green bar" for found the cache-icon could get the yellow smiley on the upper left
- Instead of showing the "Orange bar" for Offline-Log the cache-icon could get the orange smiley on the upper left
- For caches already stored (or on stored list) also the personal-note and final defined marker could be shown in search result

What do you think ?
I think it would make the usage and understanding of the symbols easier and more consistent throughout the app.

On the other hand (like @Bananeweizen commented in #1202) the overlays make the cache-type icon hard to see and there is more space in the lists to put those markers somewhere else in the cache-row.

**Comment by kumy** [comment]
So, as said in #1528, here is a quick hack to test things.

If I can sum up, we may:
* reuse markers of the map
* strip the floppy disk when we're in "saved list"
* remove the left colored bar

Should we keep the orange circle?

Is this ok for everyone? Am I missing something?

![screenshot_2015-08-15-20-48-30](https://cloud.githubusercontent.com/assets/176794/9290502/a1524b32-4396-11e5-9594-c97e07dce781.png)

**Comment by kumy** [comment]
Let it open so we can continue working on the issue.

**Comment by Lineflyer** [comment]
yep...will take a look on it next days. Time is a little limkted until end of August for me. Nice work however in principle.

**Comment by Lineflyer** [comment]
@kumy: Small question: How did you bring this orange circled cache into a list (as seen in your screenshot above)?

**Comment by kumy** [comment]
@Lineflyer orange circles comes when exact coordinates cannot be retrieved (exactly the same as in the map view (it's the same code)). The list you seen, was a search "found by user".

**Comment by Lineflyer** [comment]
I was just wondering how a search result can contain approximated coordinates ever. Either it contains precise coords (always for PM) or no coords (for BM).

**Comment by Lineflyer** [comment]
General feedback:
I think this is a good implementation.
I am also happy to see, that you kept the green/orange line in front of found/offline logged caches in addition to the smiley overlay. Removing these, would change the UI too drastic. 
With the current implementation I do only see advantages and no drawback.

One remark would be, that the overlays on the lower edges overlap with the text below (i.e. the geocode). But I would rather not scale down the complete icons, we could only make all overlays a little smaller (if this is possible independently from the used overlay icons on the map as these should not get smaller).

**Comment by Bananeweizen** [comment]
Am I the only one where the "pen overlay" is bigger than the other ones (and way more blurred)?

**Comment by kumy** [comment]
@Bananeweizen how can I reproduce?

**Comment by Bananeweizen** [comment]
Select filter "with own information" -> "with personal note", assuming you have some with personal note. I can upload an image later, when I'm at home.

**Comment by kumy** [comment]
I'll try to set the same size as other overlays.

![screenshot_2015-08-19-17-18-19](https://cloud.githubusercontent.com/assets/176794/9360463/95f39bf8-4696-11e5-8364-c03fbabac9c8.png)
![screenshot_2015-08-19-17-19-19](https://cloud.githubusercontent.com/assets/176794/9360464/9616e7a2-4696-11e5-8c1d-efccfdec9456.png)

**Comment by kumy** [comment]
Scaled bottom overlay (same sizes as upper ones)
![screenshot_2015-08-19-17-47-22](https://cloud.githubusercontent.com/assets/176794/9361182/900645d4-469a-11e5-9f69-70bccbe02e2b.png)

**Comment by Bananeweizen** [comment]
Looks much better on the screenshot. Seems like you nailed it.

**Comment by kumy** [comment]
Still need to drift the bottom line, so it doesn't overlap in lists.

**Comment by kumy** [comment]
Bottom items drifted a bit in cache lists only.

Before:
![screenshot_2015-08-19-19-20-58](https://cloud.githubusercontent.com/assets/176794/9363915/9ee678a8-46a9-11e5-9705-c45fe798f5bf.png)

Now:
![screenshot_2015-08-19-19-12-37](https://cloud.githubusercontent.com/assets/176794/9363914/9ee30ce0-46a9-11e5-86ef-c445be591bc1.png)

I'm not able to test on other resolution, hope there will be no issue.

**Comment by Lineflyer** [comment]
@kumy  If you tell me what resolutions (or even better: what matching devices) would need a test, I can try to do that.

And another side note:
I have just seen, that the floppy icon is shown in the search results, which is very nice!!

**Comment by kumy** [comment]
@Lineflyer sorry I just seen in the code that we support multiple resolutions. That's all I know.

**Comment by Lineflyer** [comment]
This looks well done now on all my devices.
Lets close this issue and many thanks to @kumy for implementing this.
