### ISSUE TITLE
Fix false positives on CI

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12101]
As seen lately on CI builds where (for some reason) building the APK was successful but running the tests failed, those builds reports back as "green".
The CI should be configured in a way, that not being able to run the tests shall make the build fail.

Otherwise we might tend to merge "green" PRs and possible problems might be undetected until the next commit/PR build, where tests are executed.

**Comment by Lineflyer** [comment]
@kumy @mucek4 
You might probably know how to enforce a "failed" build marking in such cases. Should be added to PR and commit build jobs.

**Comment by kumy** [comment]
To which builds are you referring?

**Comment by bekuno** [comment]
We have many such situation, and on different steps in the build.

See e.g. See https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/65/console

**Comment by Lineflyer** [comment]
Installing the APK just failed here on cgeo-3 (which is a problem on its own) and the job came out green:
https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/121/console

**Comment by kumy** [comment]
To try fixing the issue, I have:
- [x] created a new version of the used script: https://ci.cgeo.org/configfiles/index it should stop on first error but do the cleaning anyway.
- [x] Updated job https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/configure to use the new script

![image](https://user-images.githubusercontent.com/176794/141829925-16d9a480-c5d3-455f-b8a1-6e01b318b41e.png)

- [x] re-trigger a new build https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/127/console

Let me know how it goes. If it's ok on the long term, then just replace the old script content by the new one, or update every job to use the new script version.

**Comment by Lineflyer** [comment]
@kumy 
Thanks for helping out and the excellent documentation of it.

If it works we at least get a clear view on real CI problems (which are currently happening as @mucek4 is trying to evolve our executors to newer Jave and migrate some HW as well).

Will report back here.

**Comment by Lineflyer** [comment]
Sadly our CI jobs are running very unreliable at this moment, but I doubt its caused by the config change from @kumy 

@mucek4 
Right now cgeo-1 is more or less constantly failing with login problems and then timing out the builg
cgeo-5 is failing as it fails to find the APK to install ist (according to log).
Help please?!

**Comment by moving-bits** [comment]
Interesting enough: It looks like mostly the task "cgeo CI - PR build" is failing, whereas "cgeo CI - Commit build" and "cgeo release" seem to work without problems. Any difference in those scripts triggering it?

**Comment by Lineflyer** [comment]
I will try to analyze a bit and open a new issue for the current build fails.
The false positives are fixed however.
