### ISSUE TITLE
double-size icon for "owned"

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12100]
### Tell us your idea!

With double-sized icons for found/corrected enabled also show a larger marker for "owned" caches

(From survey)

Related to  #12083

**Comment by Lineflyer** [comment]
+1

**Comment by fm-sys** [comment]
For corrected coords / found the cache type gets irrelevant. Not sure whether this is really the case for caches you own... OTOH for DNF's the cache type is still relevant as well, but we still show a big Symbole (which I would consider good)

So I'm a bit undesided here...

**Comment by ztNFny** [comment]
> For corrected coords / found the cache type gets irrelevant. Not sure whether this is really the case for caches you own... 

I know where my caches are and what they are, no need for the type icon. 

> OTOH for DNF's the cache type is still relevant as well, but we still show a big Symbole (which I would consider good)

Looking at the code DNF shouldn't show - unless it's an outline log which are shown no matter the log type (unchanged from old icons)

**Comment by fm-sys** [comment]
> > OTOH for DNF's the cache type is still relevant as well, but we still show a big Symbole (which I would consider good)
> 
> Looking at the code DNF shouldn't show - unless it's an outline log which are shown no matter the log type (unchanged from old icons)

![Screenshot_20211115_004354_cgeo geocaching](https://user-images.githubusercontent.com/64581222/141703575-9480d4fa-01c0-48ec-9b6a-8e6a8981601f.png)

(it's an online log - but as pointed out, I'm totally fine with that. Everything else would be even more inconsistent...)

**Comment by ztNFny** [comment]
> (it's an online log - but as pointed out, I'm totally fine with that. Everything else would be even more inconsistent...)

Right. The code shows more than just offline logs:
1. Found
2. Offline log
3. DNF
4. Will attend

While reviewing the code I found an issue with the implementation of #12083, I'm including the fix for that with the implementation of the double-sized "owned" icon.

**Comment by fm-sys** [comment]
Fixed by  #12102
