### ISSUE TITLE
Refactor settings: improve connectors list

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12117]
One of the issues discovered in the WIP PR #11298, happened on an Android 10 emulator:

it would be nice, if it's still shown which connectors are active (show "Active" as summary)

![grafik](https://user-images.githubusercontent.com/64581222/141318891-5d5a7844-e782-4675-b98e-17ebc8d6d595.png)

![Screenshot_20211116_191059_cgeo geocaching_copy_431x327](https://user-images.githubusercontent.com/64581222/142042030-ade864b1-942f-40ac-a685-9d8ac0da1ea6.png)

**Comment by moving-bits** [comment]
Implemented meanwhile, so let's close here
