### ISSUE TITLE
Reset hiding of track if a new track is loaded

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12111]
### Describe your problem!

Not a real bug, but something which was a trap even for me and took me some minutes to figure out:

The map quick setting whether a GPX track/route is shown on the map is persistent even if a track is unloaded and a new track is loaded. That is somewhat unexpected as you might not understand why the loaded track is not shown.

### How to reproduce?

- Load a GPX track so, that it is shown on the map
- Use the track for your caching/hiking
- At the end of your caching session (or for whatever reason) you open map quick settings and select to hide the track
- (A few days later) you load a new track for your next caching/hiking session

### Actual result after these steps?

The new track is not shown on the map, which made me first think that the file has a problem or I am looking at the wrong lcoation on the map.
It took me a while to realize, that the map quick setting was turned off to show tracks

### Expected result after these steps?

I think the hiding of the track should be resetted once the user unloads a track or loads a new one. I guess most of the time users who load a track would like to see/use it afterwards and it confuses them (at least it was like that for me) if a track is not shown after explicitly loading it.

I can't think of a use case, where users load a track but want it to be hidden (initially).

### Reproducible

Yes

### c:geo Version

master

**Comment by moving-bits** [comment]
Implement for `release` or for `master`?

**Comment by Lineflyer** [comment]
`master` as I would consider `release` to be closed now that the (hopefully) last beta is out.
