### ISSUE TITLE
Refactor settings: settings quick launch shortcuts

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12116]
One of the issues discovered in the WIP PR #11298, happened on an Android 10 emulator:

clicking on the connector name should launch the settings at sub-page `Services`
![grafik](https://user-images.githubusercontent.com/64581222/141317793-3b274aae-e384-4b66-9426-0b4837469286.png)

same applies for `Backup/Restore`
![grafik](https://user-images.githubusercontent.com/64581222/141318237-b3d957e6-66ac-4810-926f-e301e958b92d.png)

**Comment by moving-bits** [comment]
Does work as described meanwhile, therefore closing here.
