### ISSUE TITLE
Refactor settings: Left indentation too large

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12110]
### Describe your problem!

The default settings screen seems to reserve quite a bit of space at the left for icons. But as most settings screen do not use any icons, this is wasted space, leading to truncation of titles.

![image](https://user-images.githubusercontent.com/3754370/141856421-1a5b11d9-628b-476b-ad44-d756d53bd865.png)

### How to reproduce?

open (nearly) any of the settings screens

### Actual result after these steps?

huge gap at the left, reserved for icons

### Reproducible

Yes

### c:geo Version

custom build from PR #11298

### Additional Information

Somehow related: There are a few screens actually using icons. Currently they are being displayed at the left, in the white space mentioned above, which makes them stand out quite a bit.
Icons at the left are intended as visual explanation for the respective entry, but in our case, the icon is meant as a button and should be displayed at the right (like checkboxes etc.).

See settings => map:

![image](https://user-images.githubusercontent.com/3754370/141856812-3e6ed258-4eaa-4427-abcd-56e5ef6534c1.png)

**Comment by fm-sys** [comment]
using `app:iconSpaceReserved="false"` would solve this issue and makes sense, since we (nearly) have no icons on sub-pages. 

I would suggest adding the icon click functionality as a new settings element below the original setting. Then it's also more clear that the element can be clicked...

**Comment by ztNFny** [comment]
if there's an interest in (appropiate) settings icons please ping me

**Comment by moving-bits** [comment]
> using `app:iconSpaceReserved="false"` would solve this issue and makes sense, since we (nearly) have no icons on sub-pages.

Thanks for the hint. I've added a commit that adds this parameter to all `PreferenceCategory` and all preferences except on settings overview page.

![image](https://user-images.githubusercontent.com/3754370/142073572-2e58b30a-cab4-4cd4-beeb-1dda04fba733.png)

Looks fine now for all preference titles and all preferences that do not use an icon (which happens on map page only). Here we have to decide how to proceed - probably use a button instead of the icon, as @fm-sys has suggested.

**Comment by moving-bits** [comment]
> if there's an interest in (appropiate) settings icons please ping me

Thanks, would be nice to have a consistent look & feel for the settings' overview page (although it's probably not the highest priority right now). I wouldn't touch the map sub-page's icons, though, as those are probably going to be replaced by buttons.

**Comment by SchoolGuy** [comment]
I do not believe that this is "wasted" space. I believe that the change which is currently in the branch is counter intuitive. Either we need to remove the need for icons fully or we should leave that space there. We de-align ourselves away from what all apps should follow: The design principles for Android from Google. This leads to things being at places where users would expect them and thus increasing the user experience. I am aware that there is times where you have to diverge but I don't believe this is one of these times. Imagine someone being a right-to-left text orientation user. Such users then experience will then have (with the current hardcoded layout) settings which are indented because we have the icons on the right.

**Comment by moving-bits** [comment]
> I do not believe that this is "wasted" space. I believe that the change which is currently in the branch is counter intuitive. 

Current state of branch is inconsistent with regards to the "map" subpage, which uses some icons, and as I have removed the reserved space for them, text alignment is flattering. IMHO we should replace those icons on the map subpage with buttons, positioned in the next line. All other sub pages are fine, IMHO (with regard to the reserved icon space).

> Either we need to remove the need for icons fully or we should leave that space there. We de-align ourselves away from what all apps should follow: The design principles for Android from Google. This leads to things being at places where users would expect them and thus increasing the user experience. 

I've looked at a couple of apps on my mobile. Those that use "regular" preferences implement it in different ways, actually - some use icons for the preferences overview page only (as c:geo does), others implement icons for each and every setting.

One of the problems I have with the latter is that we would need to introduce icons for every setting c:geo has, and c:geo has quite a few settings. Finding some icons is one thing, but they need to be meaningful with regard to the specific settings (otherwise they would not make sense), and they should be different from each other (which gets harder with every new setting). That's why I think icons are ok for the main categories (overview page), but should not be introduced for every setting in c:geo.

> Imagine someone being a right-to-left text orientation user. Such users then experience will then have (with the current hardcoded layout) settings which are indented because we have the icons on the right.

Agreed, that's why I changed my opinion to using buttons for the few map settings that use an icon today.

**Comment by SchoolGuy** [comment]
Okay. I will remove all icons then and try to use buttons. Your project your rules. :)

**Comment by moving-bits** [comment]
Reminder to myself: Seems that I have forgotten all services subscreens while doing my PR a couple of days ago. Will work on it.

**Comment by moving-bits** [comment]
Fixed meanwhile, so let's close here.
