### ISSUE TITLE
Refactor settings: improve backup slider

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12124]
One of the issues discovered in the WIP PR #11298, happened on an Android 10 emulator:

Admitted, it is not really a bug but a more visual glitch. But currently, it's not clear what the range border values do...

show "keep all" if max value is reached (`Backup/Restore > Maximum stored backups`)
if this isn't easily possible, we can change the header text + `BackupUtils` implementation to "select 0 to never delete any backups"
![grafik](https://user-images.githubusercontent.com/64581222/141328603-ba328eb4-e447-4df8-9328-291d9af54eb0.png)

**Comment by SchoolGuy** [comment]
Of course we can do this: We add an `onChangedListener` and manipulate the View directly if it is not possible to change what is shown there via a summary provider. Since the ID is hardcoded and static we can safely access it. We just need to retrieve it from the Android Source Code.

And if those things are not feasabile we still have the option to hide the value and use only the Summary Provider.

**Comment by SchoolGuy** [comment]
Okay so it seems the value on the right side of the Seekbar is properly locked down. I read the source code of Android more in depth, as well as the docs and the way to go would be either:

- Use a dynamic summary provider
- Use a static text which explains that `0` or `20` means infinite.

@fm-sys What is your preferred option?

**Comment by fm-sys** [comment]
A dynamic summary provider would be awesome, but we use the static text approach at other places as well. To be honest, both ways would totally be ok for me...

**Comment by SchoolGuy** [comment]
Then I would say let's go for the static text. Everything which is dynamic draws CPU cycles and I don't see a very big advantage of the dynamic provider.

**Comment by fm-sys** [comment]
Fine for me. 

Short side note:
 I think 0 makes more sense as unlimited than 20. That's also the way how we handle it in other preferences.

**Comment by moving-bits** [comment]
While working on #12176 I came along the old `SeekbarPreference` classes and its two derived classes, one of it being `BackupSeekbarPreference` class, which will restore the old text label capabilities. PR is on the way.
