### ISSUE TITLE
Refactor settings: Some settings don't have any effect

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12123]
One of the issues discovered in the WIP PR #11298, happened on an Android 10 emulator:

Some settings don't have any effect

setting seems to have no effect:
![grafik](https://user-images.githubusercontent.com/64581222/141321072-8930805e-f295-4d55-ac87-80a7bf2ec16b.png)
- "start backup" has no effect
![grafik](https://user-images.githubusercontent.com/64581222/141323775-b07f4d8e-928a-41c4-babd-812e5e4e8651.png)
- maybe more, I don't have checked all settings...

**Comment by moving-bits** [comment]
"Star backup" has been fixed with #12235, the other one is yet to be done.
