### ISSUE TITLE
Refactor settings: Navigation Tools not initialized

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12121]
One of the issues discovered in the WIP PR #11298, happened on an Android 10 emulator:

everything is grayed out (`Routing/Navigation > Navigation Menu`)
![grafik](https://user-images.githubusercontent.com/64581222/141320379-c97245c4-1626-4cff-99bd-6bb604906707.png)

maybe related to #12120

**Comment by SchoolGuy** [comment]
Indeed this should be fixed with the linked issue.

**Comment by moving-bits** [comment]
Fixed meanwhile, so let's close here.
