### ISSUE TITLE
Creating custom caches from live map

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#12149]
### Tell us your idea!

Imagine you currently have no stored caches. It is impossible to create a custom cache from the map: 

In the listview mode, you cannot enter the map, because this is disallowed when there is no stored caches.
And in the livemap, it is not possible to create custom caches.

### What solution would you suggest?

Creating custom caches should also be possible in the livemap, and they should then be added to the Standard list.

### Is there an alternative?

For me even better would be to be able to create waypoints that are independent of caches. I don't what use cases there are for custom caches. But I exclusively use them as intermediate waypoint when planning a route. This would be even easier if it were possible to simply create waypoints that are not associated to any cache.

**Comment by moving-bits** [comment]
It's already possible to create user-defined caches (UDC) on the map:
- open "live map" and long-tap on the map to create a new UDC. (Long-tap needs to be activated, though, see settings => map).
- same when coming from a cache list, just long-tap on the map.

(It does not work when mapping a single cache, though - then a long-tap will create a new waypoint for that cache.)

An alternative way is to open a cache list and select manage caches => create user-defined cache.
