### ISSUE TITLE
Make Waypoint list sortable with drag & drop

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12143]
### Tell us your idea!

The waypoints in the waypoint list can't be ordered by the user today. 

### What solution would you suggest?

* today, when tapping the waypoint, it opens for edit. This should be changed to opening the waypoint-action-selection list (see screenshot). This list is opened today when long-tapping a waypoint.
* When long-tapping the waypoint it should be drag&droppable to another list position. Comparable to e.g. the image list in offline log entries or the caches/waypoints in the individual route list.

Additional positive effect is that all the different waypoint actions become much easier accessible because they do no longer require a long-tap for initiation.
Downside of this is that the action "edit waypoint" is now slightly less accessible (requires two taps instead of one), but I never understood wh this action is considered "more important" than all the others anyway.

![image](https://user-images.githubusercontent.com/6909759/142737733-60f638cf-29f6-4b48-99bb-4154c1f67e76.png)

### Is there an alternative?

add decicated icon action buttons for "drag/drop" (hamburger icon) to the waypoint line, a bit like im log image list or individual route list. But this would of course take space away in the waypoint table

![image](https://user-images.githubusercontent.com/6909759/142737831-a25cd39a-9980-4fbd-a647-079f4bc1575f.png)

**Comment by ztNFny** [comment]
I'd vote against changing the short/long click behaviour:
- "Edit" is probably the most popular feature in that list (personally out of all the options available I never use anything but "Edit" and "Copy" (and "Compass", but that from the list directly using the button)
- It's something that users are accustomed to and that'd require relearning a very common workflow

My proposal is to introduce a dedicated Edit-Mode for waypoints list that could look like your bottom-screenshot (with delete and reorder elements, maybe also with "mark visited")

As an alternative a (smaller) reorder element could be introduced on the left, like 
![image](https://user-images.githubusercontent.com/1258173/142773302-1ab445fc-2e90-46fd-b4e2-1105b5a8994b.png)
(I wouldn't put it in non-edit mode on the right as there's the compass button to start navigation - something many users are familiar with and that's probably the most used feature in that list - that button should stay in it's position.

**Comment by Lineflyer** [comment]
I would also tend towards the proposal similar to @ztNFny proposal:

Most users will want to edit the waypoint rather than wanting to use the special options, it will be one more click for those.
The only positive point might be, that users learn the other options in case they did not know...but I would really suggest not to change the implementation just for that.

In normal cases users might not have the need to resort the waypoints (at they are already presented as foreseen by the cache owner). Such sorting option could be covered in some menu (as suggested by @ztNFny for example).

After all:
@eddiemuc 
What is the use case behind resorting waypoints?

**Comment by eddiemuc** [comment]
> After all: @eddiemuc What is the use case behind resorting waypoints?

In am often annoyed by cache listinga defining many waypoints meaningless to me (e.g. multiple possible parking places or many waypoints plus final without coordinates in it). My own waypoints are sorted below them and I always have to scroll down to them whenever I want to see them.

 One should know that I never edit waypoints by hand but always and solely use user notes and waypoint-auto-creation. This has two reasons:
* Don't like all the clicking and dialog-filling, I prefer working with a single text edit field. Auto waypoint creation works perfectly!
* By putting everything in user notes, I can simply save everything I did for the cache onto the server with a single click ("upload")

**Comment by eddiemuc** [comment]
Closed by author
