### ISSUE TITLE
Only stored caches when license not accepted

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#1215]
Today I switched to premium membership. I wonder that there are only my stored caches on the (new) LiveMap. Switching to Nearby Caches I got a prompt to accept the waypoint license.

We should have a prompt also with the map or check the license on first login when starting cgeo.

**Comment by Lineflyer** [comment]
Just recently I had another case on support:
A user upgraded to PM and afterwards did not login the webpage.
c:geo recognized the user correctly as PM however the searches were missing coordinates (i.e. LOC file not to be downloaded)


Solution was, that the user logged in and was asked to accept a license. Afterwards all was well in c:geo.
A rare case anyway.

**Comment by fm-sys** [comment]
> 
> 
> Today I switched to premium membership. I wonder that there are only my stored caches on the (new) LiveMap. Switching to Nearby Caches I got a prompt to accept the waypoint license.
> 


Yesterday, I received a gift premium membership (thanks!) and had no problems with using the live map. As there were many, many changes meanwhile, I would guess the issue is solved...
