### ISSUE TITLE
quick-load geocode from clipboard text

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12169]
### Tell us your idea!

I often get messages like "I'm at cache GCxxxxxx, do you have a hint?" upon which I look up my cache notes in cgeo. The required steps to do that are:
1. Copy message
2. Paste message somewhere so i can select only the GC code (depends on the messenger)
3. In cgeo.main screen click search
4. Long-click the search field -> paste
5. On keyboard click the search icon

It'd be nice to have a more convenient way to load a cache whichs code is in clipboard.

### What solution would you suggest?

Next to the search field/in main menu add a "load from clipboard" action that takes the current clipboard and, of it's more than just a geocode, extracts a geocode from it, then loads that cache. This would be similar to the existing "from clipboard" function in defining a waypoint.
![image](https://user-images.githubusercontent.com/1258173/143659340-e6feb504-5160-4f43-8f6a-2cc9d297832c.png)

### Additional Information

Geocode recognition should look at the enabled connectors to see what a geocode could look like to avoid false recognitions. E.g. with only gc connector enabled OC123 shouldn't be recognized as geocode.

**Comment by MagpieFourtyTwo** [comment]
BTW: With the very same scenario in mind (just seen from the questioner's side), it would be great to have a function to automatically get it's URL (i. e. ``https://coord.info/GCmycode`` or accordingly, if there exists s/th similar for other connectors) copied to the clipboard ...

**Comment by ztNFny** [comment]
>  it would be great to have a function to automatically get it's URL 

Load cache, "Share / Export", Share cache

**Comment by MagpieFourtyTwo** [comment]
Share/Export is well known and oftenly used. Nevertheless, we quite often have the situation that we want to just paste the URL into any flowing text - and this is not yet possible, AFAIK.

**Comment by ztNFny** [comment]
> Share/Export is well known and oftenly used. Nevertheless, we quite often have the situation that we want to just paste the URL into any flowing text - and this is not yet possible, AFAIK.

Androids share menu offers copying the URL to clipboard. (unless your phone manufacturere screwed up and removed that feature. In that case install one of many "Share to clipboard" apps.)

**Comment by MagpieFourtyTwo** [comment]
Thx a lot for the hint to the "share to clipboard" apps - cause the Huawei P30Pro does indeed not have "clipboard" in the share menu.

Thus I just installed your recommendation [Copy Link to Clipboard](https://play.google.com/store/apps/details?id=nl.robwu.copylink), which adds the possibility to put the link only to clipboard, plus [Share to clipboard](https://play.google.com/store/apps/details?id=com.tengu.sharetoclipboard) which copies the entire share text (i. e. name, GC code and link) to clipboard - absolutely perfect!  ;)
