### ISSUE TITLE
"Has final" vs. "Is on Final" marker

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12160]
### Describe your problem!

Sorry to warm up this topic once again...but there is some specific feedback from support channels for this topic while its rather silent on support mail after publishing the new version.  Only some generic questions where to learn the new icons (linked those users to our user guide).

> [...] I have also problem to identify immediately if the mystery icon is on the place of the final coordinates - a little bit puzzling is the system with the red vs. white flag on the right bottom. Even if I probably understand the reason for the difference (does not mean agree-it seems e.g. strange to me to have red flag if I save final coordinates through c:geo and white if I download a cache, where I saved coordinates on geocaching.com)  the white flag is much harder to notice and even the red one is not so clear as in the previous version. 

> Why did you invent a new marker for final positions. In my opinion it was clearer before:  Final flag waypoint = The cache is here, Cache icon with that very same marker = Cache is on the final position. Was really logical, now its no longer logical and the white flag is harder to spot and the red "here is the final alert" I am really missing already now.

> For solved caches please take the puzzle icon from geocaching.com or take the one we already know, but why a new one and the old one now with new meaning?

### How to reproduce?

See above.

I suggest to first collect more feedback on this topic and (maybe) proposals for just another solution.

### Actual result after these steps?

Old use 2021.10.08:
| Condition    | Red Flag | White flag |
| ----------- | ----------- |----------- |
| Has Final    | x |   |
| Is On Final  |  x  |  | 

Current use 2021.11.21:
| Condition    | Red Flag | White flag |
| ----------- | ----------- |----------- |
| Has Final    | x |   |
| Is On Final  |         | x | 

### Expected result after these steps?

Users proposal:
| Condition    | Red Flag | White flag |
| ----------- | ----------- |----------- |
| Has Final    |  |  x |
| Is On Final  |   x     |   | 

### Reproducible

Yes

### c:geo Version

2021.11.21

**Comment by ztNFny** [comment]
>  Final flag waypoint = The cache is here, Cache icon with that very same marker = Cache is on the final position. 

Shows how unclear the old situation was as even a detailed support mail gets it just wrong

If we invert it now after its been out *everyone* will be majorly confused!

As for the actual icons, i've given my opinion several times already, inverting them wouldn't follow any logical scheme imho.

**Comment by ztNFny** [comment]
Btw, the documentation page describing the markers is really hard to find. I went through the github issue for updating it to find it as I couldn't spot it in the normal pages.
Maybe the homepage should have direct links to those pages about new icons?

**Comment by Lineflyer** [comment]
It has:

![grafik](https://user-images.githubusercontent.com/949669/142984812-adc77732-b501-4138-a5f4-bcd3d25b2021.png)

**Comment by Lineflyer** [comment]
Cosing here then...as  @ztNFny is probably right. To late for change.

**Comment by ztNFny** [comment]
Btw, there's an easy solution: Remove the "has final" marker 😜
