### ISSUE TITLE
add "GCWizard" to Utility programs

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12168]
### Tell us your idea!

https://gcwizard.net/ is a quite useful app for any kind of code table and the like, successor to GCC

I can take care of it if feedback is positive.

**Comment by fm-sys** [comment]
Sounds good! They are open source and even have an android app:

https://github.com/S-Man42/GCWizard

https://play.google.com/store/apps/details?id=de.sman42.gc_wizard

**Comment by rsudev** [comment]
Good to hear that GCC continues in kind of a new version. We should definitely link it!

**Comment by ztNFny** [comment]
@S-Man42 any wishes for the description text?

**Comment by S-Man42** [comment]
Sounds great!

**Comment by ztNFny** [comment]
> Maybe we should change "geographic" into "geodetic". It's more correct.

Done
