### ISSUE TITLE
add BRouter Download Manager functionality

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12172]
The BRouter has the function to select the routing data region based on a world map.
We have now in c:geo only an automatic download. For preparing a trip outside the home region it would be fine to have such a download manager possibility.

**Comment by moving-bits** [comment]
Workaround is to open the desired region and create a route between two nearby caches - c:geo will then ask you for routing tile download, if automatic tile download is activated.
Not sure if it's worth the effort to include a special download manager function for routing tiles.

**Comment by bekuno** [comment]
My hope is that it is possible to adopt this function from the BRouter app.

Btw, since some month the BRouter app is again active developed. They plan to release the new version "soon".
There were many changes also to meet the API 30 requirements, see eg. https://github.com/abrensch/brouter/issues/351 .

**Comment by moving-bits** [comment]
If someone wants to dive into this, have a look at `btools/routingApp/BInstallerView` from the original repo.

**Comment by MagpieFourtyTwo** [comment]
@bekuno 
> Btw, since some month the BRouter app is again active developed. They plan to release the new version "soon".

Seems as if time's up now - updated to the new version which came yesterday and promptly external routing is not working anymore. :/

Changes I recognized on first sight: new icon, new storage folder (below Android\media!?)

**Comment by moving-bits** [comment]
Implementation idea: Instead of creating a new view for this, copying zooming, selecting etc. functionality BRouter provides for this, just add a menu entry to the existing maps "download routing data for this region". If selected, c:geo will calculate routing tiles involved, and download missing tiles. What do you think?

**Comment by MagpieFourtyTwo** [comment]
I would appreciate it as a nice quick fix (sorry ;) ), but would still feel the need for a possibility to check which regions are already downloaded. Cause once you lose track of the already available regions, you can lose a lot of time with nothing else than just checking ... and just doing try and error ... is nice if you like to play minesweeper in the dark, but when being in a hurry anyway, while doing preparations for a longer tour, you will not really like it. ;)

**Comment by moving-bits** [comment]
Routing tiles cover a pretty large area (*) - e. g. just four tiles are needed to cover the whole of Germany. So except for doing a whole continent in one, there should not be that much "poking in the dark".

But anyway, I'm not against implementing such a download overview, I'm only searching for alternatives which require less effort, due to time constraints.

(*) each tile file covers five degree latitude x five degrees longitude

**Comment by MagpieFourtyTwo** [comment]
That much is true, regions are quite big.
Nevertheless you will never know for real if you really have all tiles needed. Just have a look at Belgium: Although it's a pretty small country, you need four(!) tiles to cover it ...
And, to be honest, I would not feel really safe without the possibility to check my data. Esp if I have to guide a group through unknown terrain (which happens way more often than one may think ;) ).
Moreover the guys with small memory will fit sure be thankful to have a possibility to get a grip on the tiles they safely can discard.

OTOH - if external routing via Brouter will still be supported, there's in fact no need to think about all this stuff. ;)

However, if I understood the OP right, we're talking about replacing Brouter - and if so, we should either do all or nothing at all. Half way would not be a good solution, IMHO.

**Comment by moving-bits** [comment]
> you will never know for real if you really have all tiles needed. Just have a look at Belgium: Although it's a pretty small country, you need four(!) tiles to cover it ... 

Taking my proposal from above you would simply zoom out the map to cover all of Belgium and press the "check tiles" button. c:geo would download all missing tiles then (if any).
