### ISSUE TITLE
cache symbol is off-centered under certain conditions

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12192]
### Describe your problem!

While working on #12164 I've created a low-res device for testing. Under that conditions cache icons were slightly off-centered, the cache symbol was moved slightly to top-left compared to its surrounding marker symbol:

![image](https://user-images.githubusercontent.com/3754370/143784450-b0c6b8a3-f609-421d-80e3-2ec36729c502.png)

### How to reproduce?

- create a new VM in Android Studio, using "Pixel 2" (at 480x800 resolution) using API 30
- install c:geo (current `release`)
- open map or cache list to display a cache icon within its marker

### Actual result after these steps?

cache symbol is slightly off-centered to top-left compared to its marker

### Expected result after these steps?

cache symbol should be exactly centered

### Reproducible

Yes

### c:geo Version

dev-build of `release` as of today

**Comment by fm-sys** [comment]
Isn't it the same problem as described in  #12068?

**Comment by moving-bits** [comment]
> Isn't it the same problem as described in #12068?

Might or might not be, as one is about waypoint markers, the other about cache markers. But cause (and maybe even the solution) might be the same, although in different places of the source code.

Let's keep them separate (but linked) for now.

**Comment by ztNFny** [comment]
It's a dup, same issue, same solution.
