### ISSUE TITLE
Failed "Refresh" does not give an error message, even if server request results in 404 aka "DNF"

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#12194]
### Describe your problem!

Currently, events are often canceled (for very well known reasons). And at least in BaWü the typical procedure is that the owner writes an announcement, explaining the reasons, and deactivates the listing, which of course is perfectly fine. But right after this the listing will additionally be retracted by the reviewer. Which IMO is kind of weird, cause this way even the cancellation info gets lost. And users who try to (re)open such a retracted listing just get a "DNF" - like here: [GC8MAEP](https://www.geocaching.com/geocache/GC8MAEP_abgesagt-weihnachtsbaumschmucken-wird-verschoben), without even knowing if they just mistyped the GC code ... or whatever ...

However, things get even worse when someone has previously saved such a listing offline - cause if you refresh an offline stored listing which has been retracted, c:geo just does nothing at all.  Although the server gives a 404, c:geo just completely ignores this and goes on as if everything is perfectly fine. The one and only place where you can see that s/th has gone wrong is the "Stored in device" text, which remains unchanged, no matter how often you (try to) refresh.  But if you don't check it, you will never ever see that this event has been cancelled. Or that this cache does not exist anymore.

### How to reproduce?

- save any cache offline which is prone to be retracted
- try to refresh it, after it has been retracted

### Actual result after these steps?

- listing will not be updated
- nothing changes
- no error message will be displayed

### Expected result after these steps?

An error message - or at least a toast message - should be displayed,
that this listing was not found on the server and that it has not been updated.
Perhaps even a hint may be displayed to enforce the user to check the listing by opening it in browser ...

### Reproducible

Yes

### c:geo Version

2021.11.28-NB-90aef0e

**Comment by fm-sys** [comment]
We have such a similar toast, if the owner has switched a listing to PMonly (as BM).

But for this special case maybe following wording:
"The cache was not found, maybe it was deleted"

**Comment by fm-sys** [comment]
When opening the cache in cgeo I already get such a toast. But I had the cache not yet stored. @MagpieFourtyTwo can you share a GPX of GC8MAEP for easier reproducing? 

![Screenshot_20211129_063848](https://user-images.githubusercontent.com/64581222/143814517-800024fa-3812-40b0-9808-545c6791ab23.jpg)

**Comment by MagpieFourtyTwo** [comment]
> can you share a GPX of GC8MAEP for easier reproducing?

No problem: [GC8MAEP.zip](https://github.com/cgeo/cgeo/files/7619818/GC8MAEP.zip)
Just stripped the WAs and changed the last one to NoNameDummy, to avoid potential privacy issues
 (although there most probably are none anyway, but better to be save than sorry ;) ).

**Comment by fm-sys** [comment]
> We alrady have such a similar toast, if the owner has switched a listing to PMonly (as BM).

I have to correct myself. We currently do not have such a message. But this will be solved as well in the same run...

![grafik](https://user-images.githubusercontent.com/64581222/143948786-b350adc2-e191-4b99-a8ae-d5144267d81e.png)
