### ISSUE TITLE
D/T rating vs  icon not same

### ISSUE THREAD

**Issue by stephr321** [cgeo/cgeo#12214]
When you click on a cache from the map, the D/T rating verses the stars version of D/T do not match. If you click for more details it is correct there, just not on the first pop up window. It also cuts off the right side, only showing max of 4 stars on D/T. Attaching screenshot.
![Screenshot_20211128-110208_cgeo](https://user-images.githubusercontent.com/87022956/144326273-3847c786-6618-4389-9201-20800f96981e.jpg)

**Comment by Lineflyer** [comment]
Can you provide some additional info please:
- GC-code of the cache in the screenshot
- Version of c:geo used
- Does this happen only for this specific cache or more often / always?

**Comment by stephr321** [comment]
GC978DM
c:geo version 2021.11.21
This happens for all caches I click to open from the map.

**Comment by bekuno** [comment]
@Lineflyer 
Please see the screenshot at https://github.com/cgeo/cgeo/issues/12164#issue-1062812095.
Here is the same problem.
From the screenshot at https://github.com/cgeo/cgeo/issues/12192#issue-1065427508 I think the problem is solved already with this PR.

**Comment by Lineflyer** [comment]
@moving-bits Did you notice this while doing #12191 respectively, I wonder what introduced this problem at first?

**Comment by moving-bits** [comment]
> @moving-bits Did you notice this while doing #12191 respectively, I wonder what introduced this problem at first?

No, did not, and also have not been able to reproduce this error (tried with 2021.11.21)  :-(

**Comment by Lineflyer** [comment]
@stephr321 
The issue of the stars not being visible is already resolved on the development track.

Regarding the wrong stars though:
I was able to reproduce it on 2021.11.21 by increasing the font size until the stars run out of view (like in the screenshot above). So there seems to be a connection, that stars out of view are not taken into consideration when filling them (or something like this).

Testing the same scenario on current `release` which includes the fix shows OK, thus it will be implicitly solved in our next release:
![image](https://user-images.githubusercontent.com/949669/144749895-8c952cb9-9d6a-4ef1-80cd-4b1775393fb6.png)
