### ISSUE TITLE
Refactor settings: Editing "Signature" is not possible

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#12243]
### Describe your problem!

When trying to edit ``Settings`` => ``Logging`` => ``Signature``, the edit window is completely empty.
Nevertheless, the signature text is still there, if you have a look at ``System`` => ``View settings`` => ``signature``.
Seems as if the dialog references the wrong variable ...?

### How to reproduce?

``Settings`` => ``Logging`` => ``Signature`` ...

### Actual result after these steps?

Empty edit window

### Expected result after these steps?

Content of variable ``signature`` should be displayed to be able to edit it

### Reproducible

Yes

### c:geo Version

2021.12.04-NB-3b6e977

**Comment by ztNFny** [comment]
The code is largely commented out: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/settings/TemplateTextPreference.java

**Comment by moving-bits** [comment]
We are currently in the mid of a huge refactoring - a technical migration of our old monolithic Android-based settings to a AndroidX fragment-based preferences. Much of it has been merged to our nightlies a few days ago, but there are still some loose ends, see https://github.com/cgeo/cgeo/projects/21 for details.

`TemplateTextPreference` and `ColorpickerPreference` have been two more difficult parts, as they have been using some mechanics no longer supported by AndroidX preferences. The latter has been solved meanwhile, `TemplateTextPreferences` is still open.

**Comment by MagpieFourtyTwo** [comment]
Ok - so what does this mean for editing the signature - will it take a couple of weeks to solve this or just a few days?

As I change the sig on a daily basis, which is a bit cumbersome right now (workaround: copy current sig text from system -> settings to logging -> signature (20 clicks in total), correct lost CR/LFs, make needed changes, and eventually save the changed sig) should I either go back one or two versions and stay with it until this is solved, or, in the latter case, just live with it for some days ...?

Additionally: Are there even more settings which should be handled with care right now?

**Comment by moving-bits** [comment]
PR which fixes signature editing has already been created a few minutes ago (see #12244).

There may be more preferences not working fully yet, though nothing relevant that I know of currently, mostly "summary info" not being updated. Current state that we know is reflected in the project mentioned above. If you happen to find a new obstacle, please create an issue so that we can track it in our project an fix it.

**Comment by MagpieFourtyTwo** [comment]
Ok - thanks for the info and of course for the commit, too!

**Comment by MagpieFourtyTwo** [comment]
In current nightly it works like a charm.
Although the edit window is a bit narrow ... 
But as even the "last line edit glitch" is gone now (with long sigs, only the upper 3 or 5 pixels of the letters in the last line were displayed, so you had to edit "blindly" and double check your text after closing the keyboard, additionally it was kind of hard to scroll to the last line with keyboard active), this is a real luxury problem. ;)

**Comment by moving-bits** [comment]
> Although the edit window is a bit narrow ... 

I've configured it to have a minimum height of 3 lines, and it should grow automatically for longer signatures. Does that work for you, or shall I increase the minimum height? (Haven't tested what will happen to the explanation text below the input field, though, when the keyboard is opened - that text will probably vanish then, it's already half-hidden in the screenshots above.)

**Comment by MagpieFourtyTwo** [comment]
The length of the window is not an issue, but its width. The room right and left of it is just a waste of precious screen space.
If you compare the effective text width only and compare it to the screen width, the text just uses about 2/3 of the screen.
This I would consider "room for improvement" ...  ;)
In fact this is even dangerous, as it involves the risk of unintentional termination by accidentally touching these areas, cause changes done till then will not ne saved.
Which is BTW the same "problem" we ha with the PN edit window some time ago ... until the PN edit window was changed to use the entire width (different window type?) - perhaps the sig edit window can be implemented like the PN, too?

**Comment by moving-bits** [comment]
Currently it's implemented as a dialog window. In the emulator it looks like this:

![image](https://user-images.githubusercontent.com/3754370/145651090-516ba79a-78e4-4efe-8ecd-a350b93bfc12.png)

I don't know of a way to influence the dialog window's width.

So the only way to circumvent this probably is to implement it the same way we have done for the edit PN window. (Don't know how much work that would be, though.)

**Comment by MagpieFourtyTwo** [comment]
Looks pretty much the same on a real mobile.
And if it's too time-consuming to switch it to a PN like window, it surely can just remain as it is,
but OTOH it would be great to a) use the extra space an b) get rid of the abort risk ...

**Comment by fm-sys** [comment]
> So the only way to circumvent this probably is to implement it the same way we have done for the edit PN window. (Don't know how much work that would be, though.)

It's not too much work. Only `AbstractFullscreenDialog.java` needs to be extended for every dialog. (See #10986)
However, if we want to use such dialogs at more places, it probably makes sense to use some builder-like architecture for it...

**Comment by MagpieFourtyTwo** [comment]
Prior to writing my last answer I went through settings and dialogs to look for more potential places, but could not find a single one apart from the value input fields in ``Settings`` => ``System`` => ``View settings``- but I guess these are meant to be as plain as possible (although these not even handle CR/LF correctly). 

Ah, moment, the five new signature template input fields may be candidates, too ...?

**Comment by ztNFny** [comment]
> Ah, moment, the five new signature template input fields may be candidates, too ...?

They are the same class as signature.
