### ISSUE TITLE
enhance custom SeekbarPreference capabilities (e.g. introduce step size)

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12259]
So at least I would like to see the "step value support" for SeekbarPreference

Another idea when we go the way to implement everything ourselves:
Instead of using a separate `BackupSeekbarPreference` class, maybe we can add two optional generalized fields `lowerEndLabel` and `upperEndLabel`. So this could also be used as well for other sliders, where we currently explain in the summary what "0" means.

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/12253#issuecomment-987219945_

**Comment by moving-bits** [comment]
> So at least I would like to see the "step value support" for SeekbarPreference

AFAICS from `ContinuousRangeSlider` and `ViewUtils` the "step value support" is self-built, no material.io component.

> Another idea when we go the way to implement everything ourselves: Instead of using a separate `BackupSeekbarPreference` class, maybe we can add two optional generalized fields `lowerEndLabel` and `upperEndLabel`. So this could also be used as well for other sliders, where we currently explain in the summary what "0" means.

having such labels would require the legend anchor view as well, see above.

**Comment by fm-sys** [comment]
At least if we use a `com.google.android.material.slider.Slider` there is such a functionality built-in: 
`android:stepSize="10"`

https://stackoverflow.com/a/62137152/13513639

**Comment by eddiemuc** [comment]
> > So at least I would like to see the "step value support" for SeekbarPreference
> 
> AFAICS from `ContinuousRangeSlider` and `ViewUtils` the "step value support" is self-built, no material.io component.
> 

The "step value support" in the self-buildmvirws uses the stepSize attribute as mentioned by @fm-sys . However, the step labels below the slider are indeed custom-build.

What occurred to me: the sliders used and build for filter activity are used to select a range (with a min and a max value), not a single value. Some effort would be needed to support this too.

**Comment by fm-sys** [comment]
This was partly fixed by #13743. Still outstanding is the implementation of generalized `lowerEndLabel` / `upperEndLabel` parameters
