### ISSUE TITLE
Caption formatting/font size in settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12263]
I took some minutes this evening to strive through the new settings with checking here and there.
Overall a very good rework (thanks @SchoolGuy ) but I wonder if the "captions" might need some finetuning.

The old capitalized cpations are ugly for sure, but the new ones are much less prominent:
Left=old Right=New (same emulator)

![image](https://user-images.githubusercontent.com/949669/145091385-f58de53c-2f20-4138-92ec-c4fc657b897c.png)

IMHO the captions should at least have the same font size as the individual items.
Whether we want to use capitalization or bold font is a matter of taste (or Android style guidelines?).

**Comment by Lineflyer** [comment]
Also in white mode it mandatory to make those more prominent:

![image](https://user-images.githubusercontent.com/949669/145098325-b80543f2-c910-4416-80df-881a8024fa1a.png)

**Comment by fm-sys** [comment]
IMHO this looks rather ugly :-/

I have to say that I really like the current light and small style. The reason for this is simple: the subtitles are way less important than the actual setting names, and are just meant as a visual separator, but not as a real caption. 

Also take a look at the related material.io guide:
https://material.io/design/platform-guidance/android-settings.html

**Comment by SchoolGuy** [comment]
I have to agree with @fm-sys . I would leave it like it is atm. As long as the users don't prove the style-guide wrong, I would leave the style of the settings like they are now.

**Comment by Lineflyer** [comment]
Thanks @fm-sys for pointing out the link to the material.io guide. Indeed the current style is inline with whats suggested, still I personally don't understand why a structuring is smaller than the content. You wouldn't make a chapter heading smaller than the text if you write a document, would you?

Anyhow, also after visiting other apps, I think we are inline with styling right now.
I am therefore fine to close this.

**Comment by moving-bits** [comment]
> Indeed the current style is inline with whats suggested, 

To my understanding the referenced guide does not give any hints regarding the styling of labels. The screenshots do show the default styling, but the guide does not explicitly mention any font sizes etc. regarding the labels.

The only hint that this could be meant to be a fixed styling is that there are no predefined parameter classes to adjust the label styling.

> still I personally don't understand why a structuring is smaller than the content. You wouldn't make a chapter heading smaller than the text if you write a document, would you?

That bothers me as well and was the main reason why I jumped into it in the first place.

> Anyhow, also after visiting other apps, I think we are inline with styling right now. I am therefore fine to close this.

"Out in the wild" you'll find everything:
- styling along the defaults,
- preferences using the default components, but different styling,
- "free style" created preferences, mismatching material.io guidelines to different degrees...

But anyway, let's stick with this styling for now, as it's the default. We can still adapt it, if it bothers us too much some day.
