### ISSUE TITLE
Refactor settings: replace png by scalable vector images

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12276]
### Tell us your idea!

Settings still use png as category icons, needing separate versions for light and dark mode		

### What solution would you suggest?

replace the icons by scalable vector icons from material.io + tinting to `textColor`

**Comment by ztNFny** [comment]
I can take this if wanted

**Comment by fm-sys** [comment]
AFAIK @moving-bits has already started working on it, see  #12277

**Comment by moving-bits** [comment]
fixed with #12277 (forgot to set hint in commit message), therefore closing here
