### ISSUE TITLE
Double NM Logs when logging a NM and selecting an issue

### ISSUE THREAD

**Issue by capoaira** [cgeo/cgeo#12299]
### Describe your problem!

When you Log a NM with c:geo and select an issue on "Report a Problem", the Log creates two logs. One with the Text of the logging cacher and one with the automatic system text.

This happened to one of my caches, I don't have tested it by myself.

### How to reproduce?

No response

### Expected result after these steps?

Should send only one NM Log

### Reproducible

Unclear

### c:geo Version

2021.11.21

### Additional Information

Maybe it makes sense to hide the "Report a Problem"-Box on NM logs, or add the automatic system text to the text written by the cacher.
(I'm not sure if the version is correct - I don't know which the cacher is using)

**Comment by Lineflyer** [comment]
This is implicitly solved by the fact, that meanwhile there is no longer an explicit log type "Needs maintenance" but using "Report problem" is the only way now.
