### ISSUE TITLE
Add map legend for Elevate/Elements/Freizeitkarte themes

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12292]
### Tell us your idea!

When using maps in c:geo I frequently ask myself what this or that shading or symbol is intended to mean.

### What solution would you suggest?

Add a map legend explaining the most relevant map shades and symbols for current theme, if that's any of Elevate/Elements/Freizeitkarte. Source for this information could be
- Freizeitkarte: https://www.freizeitkarte-osm.de/android/en/legende-freizeitkarte.html or https://www.freizeitkarte-osm.de/android/en/legende-outdoor-contrast.html
- Elevate / Elements: https://www.openandromaps.org/kartenlegende/elevation-hike-theme

### Is there an alternative?

Just link to above's URL, but that would miss offline functionality.

### Additional Information

Already have permission from Elevate/Elements author to use his symbols for an in-app legend, would need to ask Freizeitkarte author for the same.

**Comment by ztNFny** [comment]
fyi, Voluntary will be added as a theme on oam website soon (from the last posts in that thread): https://www.openandromaps.org/en/oam-forums/topic/voluntary-uk

**Comment by moving-bits** [comment]
@eddiemuc 
Maybe you have an idea, as you have digged somewhat deeper into theme handling when you implemented SAF support for mapsforge: Is there some public method to retrieve a certain symbol from a theme by giving its filename (e. g. "p_farmland" or "p_farmland.svg"), ideally without having to specify the relative source path, and without having to know whether it's coming from ZIP or from separate files. AFAIHS there is a symbol cache deep with mapsforge's `RenderThemeHandler`, but that's not public.

**Comment by moving-bits** [comment]
Sneak preview: I'm heading for something like this:

Menu entry "Theme legend" opens a small dialog with categories, and when you tap on one of the categories, the icons used in the theme will appear. Long tap on a icon shows its meaning as a tooltip.

![image](https://user-images.githubusercontent.com/3754370/145707061-4db1360c-65e8-4863-a226-e7aaa412ce1f.png)

Only a selected subset of all icons will be shown, the (hopefully) most common ones.

Currently I'm saving those icons in a separate resource folder, but this has some (potential) drawbacks, e. g. name clashes, duplication of resources (they are available in the theme already), scaling issues (png instead of svg) etc., so I would really like to get those symbols from the theme file, if possible.

**Comment by ztNFny** [comment]
I'd suggest asking the themers in OAM forum for some suggestions on how to best implement this, after all they know themes best.

The question also is what needs to be contained in the legend. Do we really need to explain all the area types? Forest vs fields vs city should be clear enough on their own. What may need explanation is the different kinds of paths with the coloring applied on top, that is highly specific to the map theme - but also to the options in the theme.
I'm not sure whether that aspect can be covered by a generic legend view inside the app though, it seems the "standard" way of explaining the legends is PDF due to the large differences.

**Comment by eddiemuc** [comment]
> @eddiemuc 
> Is there some public method to retrieve a certain symbol from a theme by giving its filename (e. g. "p_farmland" or "p_farmland.svg"), ideally without having to specify the relative source path, and without having to know whether it's coming from ZIP or from separate files. AFAIHS there is a symbol cache deep with mapsforge's `RenderThemeHandler`, but that's not public.

@moving-bits your intuition is correct. There is such a cache in mapsforge, but it is not publically available as of now. Some extensions in mapsforge code would be necessary to provide this. Exception is ZIP resource provider which already offers this via public Interface, but this was never intended to be used in this way.

**Comment by moving-bits** [comment]
> I'd suggest asking the themers in OAM forum for some suggestions on how to best implement this, after all they know themes best.

Technically it's relatively easy - a both Elevate/Elements and the two FZK themes come as a ZIP file with a huge bunch of svg files in one or more sub folders. A bit of complexity comes from the different storage types (ZIP or uncompressed) and different storage locations, which I would like to abstract from. And as the mapsforge lib already has implemented reading from different sources, and even the caching, best way IMHO would be to gather the sources from there instead of reinventing the wheel.

> The question also is what needs to be contained in the legend. Do we really need to explain all the area types?

For sure not, and I've already left out quite a few of them. This can be further fine-tuned.

> What may need explanation is the different kinds of paths with the coloring applied on top, that is highly specific to the map theme - but also to the options in the theme. I'm not sure whether that aspect can be covered by a generic legend view inside the app though, it seems the "standard" way of explaining the legends is PDF due to the large differences.

OAM even provides a details PDF with a legend, optimized for viewing on a smartphone. That's a really good thing, and I plan to link to it as well, but it has two downsides, IMHO: First of all it's online, so it needs to be downloaded first, and you probably won't have a proper internet connection just at the time you want to look up something. Second, and more important for me: It's 28 pages, so a "quick" lookup of some specific formatting won't be that quick. That's why I chose to select a subset of all images and to display images only to get as many images on a quick view as possible.

> > Is there some public method to retrieve a certain symbol from a theme by giving its filename  
> @moving-bits your intuition is correct. There is such a cache in mapsforge, but it is not publically available as of now. Some extensions in mapsforge code would be necessary to provide this. Exception is ZIP resource provider which already offers this via public Interface, but this was never intended to be used in this way.

Ok, thanks for cross-checking. I'll start debugging a bit, let's see if this can easily be extended (and whether mapsforge would accept such a change).

**Comment by eddiemuc** [comment]
@moving-bits I skimmed mapsforge code. I think this might be possible without modifications to mapsforge.

The method to use would be `XmlUtils.createBitmap` (see reference below). parameters should be filled as follows:
* 'src' is the resource name (e.g. p_farmland.svg)
* 'relativePathPrefix' and 'resourceProvider' can be retrieved from the XmlRenderTheme instance (see `createThemeFor` method in c:geo class `RenderThemeHelper`) 
* 'graphicsFactory': AndroidGraphicFactory.INSTANCE
* 'displayModel': new DisplayModel()
* width, height, percentage should be pretty self-explanatory

Using this method, you would also use the mapsforge caching mechanism under the hood.

Reference to `XmlUtils.createBitmap` in mapsforge:
https://github.com/mapsforge/mapsforge/blob/89042f339c7e802c882b8d77f83a7064f5420c19/mapsforge-map/src/main/java/org/mapsforge/map/rendertheme/XmlUtils.java#L49

**Comment by moving-bits** [comment]
Thanks, @eddiemuc, for doing the research, highly appreciated.

I'm currently experimenting with `AndroidSvgBitmap` which seems to be pretty similar (looking at the params), and also doing some caching under the hood. I'm already able to retrieve svg resources as bitmaps and display them in my dialog.

But I'll have a more in-depth look at `XmlUtils.createBitmap` as well, thanks for the pointer.

**Comment by ztNFny** [comment]
> Technically it's relatively easy

I didn't mean the "technial" part - but the "what to show" and "how to present it". They already cteated map legends, no need for you to reinvent the wheel.

**Comment by eddiemuc** [comment]
@moving-bits 
XmlUtils.createBitmap uses AndroidSvgBitmap under the hood

**Comment by moving-bits** [comment]
Tried using `XmlUtils.createBitmap()`, which results in a `ResourceBitmap` (which in this case is an `AndroidSvgBitmap` actually), but how can I extract the bitmap from it? It's a protected property of `AndroidSvgBitmap`.

**Comment by moving-bits** [comment]
> Use static method `org.mapsforge.map.android.graphics.AndroidGraphicFactory.getBitmap()` for this.

That was what I was searching for, thanks for pointing me to that method!
Using that I can swipe out some workaround I had used so far (creating a subclass of `AndroidSvgBitmap` with a helper method which returns its protected bitmap).

**Comment by moving-bits** [comment]
implemented with #12418
