### ISSUE TITLE
colored attribute icons

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12310]
color attribute icons by group

- [ ] create SVG versions of all attribute icons
- [x] define colors (and use them in svgs)
- [x] (slightly) update some attribute icons that won't work well with coloring
- [x] decide about negative/positive icons

use black through-line for disabled red attributes

![image](https://user-images.githubusercontent.com/1258173/145727835-fdc87703-8185-486c-b36a-12d834605f7e.png)

**Comment by moving-bits** [comment]
additionally: add black strike-through for red icon group

**Comment by ztNFny** [comment]
and switch to SVG :-)

**Comment by ztNFny** [comment]
also needs to modernize some icons

**Comment by ztNFny** [comment]
one big issue I just realized with the categories/colors: While a positive icon might be quite important (e.g. tools required, tree climbing are very important) the same isn't necessarily true for the negative icon ("no tool required" is not important at all).

I think this is an issue only for the "tools" group, for others the categories are more or less ok for both positive and negative.

Maybe the negative tool attributes should be black with red strike-through line to show this lowered significance?

**Comment by Lineflyer** [comment]
> Maybe the negative tool attributes should be black with red strike-through line to show this lowered significance?

Sounds reasonable.. Are you refering to the whole "red group" or only parts of it?

**Comment by ztNFny** [comment]
I just realized that currently we're not using separate icons for positive/negative icons but are just adding an overlay (the red line).

What do you think, is the added overhead of some (I only want to add additional images where needed) negative attribute icons worth it?

**Comment by moving-bits** [comment]
I do not understand the possible need for extra icons for negative attributes - why would you want to add them? Wouldn't adding a black line as overlay work for the "red color group" icons?

**Comment by ztNFny** [comment]
The "negative" icon as of right now is "positive icon" + "red strike-through overlay". Thus to achieve something other than "base icon + overlay" - which we want: black icon instead of red, red overlay instead of black - a separate icon is needed.

**Comment by ztNFny** [comment]
> I do not understand the possible need for extra icons for negative attributes - why would you want to add them? 

oh, i kinda missed your point - please see my comment from 2 weeks ago: https://github.com/cgeo/cgeo/issues/12310#issuecomment-992928907

**Comment by moving-bits** [comment]
Ah, I see - sorry, too long ago :-(

I'm neutral with regard to this, could live with both having colored negative tool group icons + black strike-through or black colored negative tool group icons + red strike-through.
