### ISSUE TITLE
Back button handling for bottom nav

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12317]
> but when bottom navigation is shown, the back button is to be avoided cause it will terminate the app.

I see that as a big disadvantage of bottom-nav, yes. Where before bottom-nav the users always had to use back to get to Dashboard now you need to reeducate them to not use back.  We should definitly discuss about that - in context of bottom-nav!

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/11997#issuecomment-992344414_

Side note @fm-sys:
We could change the behavior, so that pressing back brings you to the dashboard activity. Other apps are doing this as well... (Examples will follow)

**Comment by fm-sys** [comment]
Option 1: Go back to Dashboard 

https://user-images.githubusercontent.com/64581222/145818618-a03c2aa9-4866-494d-a88e-4db7dc8ca415.mp4

Option 2: keep activity stack alive 

https://user-images.githubusercontent.com/64581222/145818625-83836709-b904-4133-89c5-02a753626083.mp4

BTW, I also really like how YouTube is handling the "not logged in". Would this be something for cgeo as well?

**Comment by MagpieFourtyTwo** [comment]
As this is dealing with "Navigation between main activities", it may be in the same context that going back to a previously chosen main activity should restore the previous state (such as active routing target, after leaving live map activity, like activity ``Stored``, which already does so).

**Comment by MagpieFourtyTwo** [comment]
Videos are not seen over here, get this message only:
![No mp4](https://user-images.githubusercontent.com/9889015/145819797-046f9b8c-9c16-4ffd-afc6-d59e6552569e.jpg)

**Comment by fm-sys** [comment]
> Videos are not seen over here, get this message only

Hm, does downloading work? Anyway, I will add a textual description...



> As this is dealing with "Navigation between main activities", it may be in the same context that going back to a previously chosen main activity should restore the previous state (such as active routing target, after leaving live map activity, like activity `Stored`, which already does so).

That's true and might be possible to implement together, but we already have an issue open for it: #11926 ;-)

**Comment by MagpieFourtyTwo** [comment]
> Hm, does downloading work?

Not over here - left click does nothing, and although right click offers to ``Save video as ...`` and ``Open video in new tab`` none of these do anything at all (while these may be locally defined actions, anyway).

But, finally found a workaround: Right click => ``Copy Video link`` => open new Tab => paste link ... then the video plays.  ;)

**Comment by fm-sys** [comment]
> But, finally found a workaround: Right click => `Copy Video link` => open new Tab => paste link ... then the video plays. ;)

Nice to hear. But no idea why GitHub can't render the video on your device... Anyway, I've added a textual description of both options as well.

I would start implementing solution 2 which is IMHO more logical and easier to combine with  #11926

**Comment by fm-sys** [comment]
Let's close in favor of  #11926
