### ISSUE TITLE
in attributes filter allow selecting from which connectors attributes are shown

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12311]
### Tell us your idea!

attributes filter shows **a lot** of attributes which makes it hard to find an attribute. This makes it hard to find an attribute.

### What solution would you suggest?

Show attributes only for enabled connectors.

### Is there an alternative?

Offer a switch in attribute filter "show GC attributes / show all attributes"

**Comment by ztNFny** [comment]
In https://github.com/ztNFny/cgeo/tree/issue/12311_filterAttributes I've implemented the back-end part of this. Filter dialog either shows all attributes, GC only or OC only. This is currently based on a preference without GUI - if the user doesn't have anything set a "guess" is made based on enabled connectors.

For the GUI part I'm not sure, the existing dialog is very cramped already:
![image](https://user-images.githubusercontent.com/1258173/147573558-8f9b063a-ea7c-4006-9a61-cf5e2d459244.png)

Maybe the 2 existing buttons for include/exclude could turned into 1 button that shows the current state?
Then in the middle there'd be space for an additional button to toggle the 3 attribute modes (again showing the current state)

Mockup:
![image](https://user-images.githubusercontent.com/1258173/147575855-7f9d5283-476f-4070-bef1-6abf27757ecd.png)

@eddiemuc As the existing filter dialog is your work, what do you think?

**Comment by eddiemuc** [comment]
The include-exclude logic is used in some other filters as well, so if it is changed here it should probably be changed in all other filters as well. Also the visualization to switch between different states showed in a row is used in many places e.g. the all-yes-no states in status filter, maybe this should be changed as well.

But as almost always I have no strong opinion wrt GUI, so I will be fine with everything :-)

**Comment by ztNFny** [comment]
right about include/exclue, didn't know they were used in other places as well.
maybe the "reset" button could be removed? It seems other filters don't have that, so it's not a common element. And to achieve reset you could delete - re-add.

**Comment by eddiemuc** [comment]
> maybe the \"reset\" button could be removed?

I don't remember whether I implemented this upon some explicit request or just thought it would be nice here. If the later is the case, I am fine with removing it. If the former is the case someone might complain...

Is there anyone in the team remembering that this was requested?

**Comment by SammysHP** [comment]
Are we talking about online filters or offline filters as well? You can import caches from GPX files without enabling a connector. Also you can store caches and afterwards disable the connector.

**Comment by ztNFny** [comment]
> Are we talking about online filters or offline filters as well? You can import caches from GPX files without enabling a connector. Also you can store caches and afterwards disable the connector.

That's why there needs to be a GUI for the user to select what he wants to see.

**Comment by ztNFny** [comment]
I've found a way to make the GUI take up very little space:
![image](https://user-images.githubusercontent.com/1258173/147612546-1a26af7e-ead5-47d6-84de-4d935433bd7c.png)

Each of these buttons can be toggled separately, showing either both, GC only or OC only.

@eddiemuc I'm struggling with the RelativeLayout used here. I'd like to center those two buttons (actually 1 ButtonToggleGroup) between the elements on the left and right but can only manage to either "glue" them to either of them or align to the parent. As you've used RelativeLayout a lot in filters maybe you know a good solution to this?

Code corresponding to the screenshot in https://github.com/ztNFny/cgeo/tree/issue/12311_filterAttributes

**Comment by eddiemuc** [comment]
> I'm struggling with the RelativeLayout used here. I'd like to center those two buttons (actually 1 ButtonToggleGroup) between the elements on the left and right

If you want to reach this, then i think you should rather use a Linearlayout, add a space view between the exclude-include and the gc-oc, also a space between gc-oc and the "clear" button. Then assign width 0 and weight 1 to both space views. This should evenly distribute all remaining room in the line evenly to these two spaces.

**Comment by ztNFny** [comment]
> > I'm struggling with the RelativeLayout used here. I'd like to center those two buttons (actually 1 ButtonToggleGroup) between the elements on the left and right
> 
> If you want to reach this, then i think you should rather use a Linearlayout, add a space view between the exclude-include and the gc-oc, also a space between gc-oc and the "clear" button. Then assign width 0 and weight 1 to both space views. This should evenly distribute all remaining room in the line evenly to these two spaces.

Thx, implemented it like that
