### ISSUE TITLE
Info: Shared offline maps with Locus no longer possible

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12329]
From users on support I was made aware of the following:

Locus seems to have decided not to implement the storage access framework, but rather just migrate all data by moving it into app internal directories.
See here: https://docs.locusmap.app/doku.php?id=manual:faq:android_11_filesystem

The only migration offered is to move files from the previous random folder into the private ones:
https://docs.locusmap.app/doku.php?id=manual:faq:cusom_subdirs

That - of course - makes it impossible for users to share the same mapsforge vector maps between c:geo and Locus as:
* Locus does not support selecting a user defined folder (due to missing SAF implementation)
* You cannot use the c.geo SAF implementation to select the new Locus directory as its app private

It really sad to lose this possibility as it probably means doubled storage space :(

@menion 
Can you confirm that, or did I overlook something (or is the current mode just an intermediate step in your migration)?
Does this apply to Locus 3.x or also to Locus 4?

**Comment by eddiemuc** [comment]
Ah man, all the SAF implementation pains down the drain...

**Comment by Lineflyer** [comment]
@menion 
That's a pity.
@eddiemuc helped out to enable support of scoped storage in the mapsforge library. Shouldn't it be possible to use the newest library version to read V3 files? Won't probably help with SQLite-based maps though...

**Comment by menion** [comment]
I believe it is doable to modify the old V3 library to use Scoped Storage as well. I'll most probably be looking at it a little later. 

Currently, we have two alternative solutions we are working on and next few days tell us if this is the way. I'll inform you here once we have something in our hands.

**Comment by eddiemuc** [comment]
@menion 
What mapsforge is doing: it supports opening map files given a `FileInputStream` object instead of a `File` object. SAF returns `InputStreams` which are always `FileInputStreams` when underlying object is a local `File`. From the `FileInputStream`, mapsforge retrieves the `FileChannel` which then allows random read/write access.

@Lineflyer the above was in mapsforge before me, can't take credit for it. I did modifications there for theme support though (reading from zip files)

(If anyone wonders, it is not possible to retrieve a `File` object from a `FileInputStream`)

Don't know whether SQLite supports opening by `FileInputStream` as well, would have to Google this.

**Comment by menion** [comment]
@eddiemuc thanks, I know and use this technique as well. `FileChannel` is at least a small alternative to missing `RandomAccessFile`. Slower, but working ...

SQLite, as far as I was searching, there is no such option.

**Comment by eddiemuc** [comment]
> @eddiemuc thanks, I know and use this technique as well. `FileChannel` is at least a small alternative to missing `RandomAccessFile`. Slower, but working ...

Ok, I should have known that you know :-)

> SQLite, as far as I was searching, there is no such option.

I fear you are right, could not find any such option too. Maybe using a `FileChannel` would make SQLite access so slow that it doesn't make sense.

**Comment by Lineflyer** [comment]
@menion 
An approach I just stumbled upon when looking at the new version of BRouter is, that you could use your app dedicated directory below `/Android/media` as storage for the vector maps. This is what BRouter does for the navigation files.
The advantage is, that this directory is not app private but can be accessed from other apps like c:geo via scoped storage and it does not require including scoped storage on your side but AFAICS using the `MediaStore` methods.

**Comment by menion** [comment]
Hi, thanks for the tip ;). In the latest Locus Map versions, this is already supported. Used may place maps into these directories so apps like c:geo may use them over ScopenStorage.

**Comment by Lineflyer** [comment]
@menion 
We meanwhile received positive feedbacks from c:geo users sharing their maps via the media storage location. Meaning: The users set their c:geo offline map directory to `/Android/media` and have a working solution for both Locus and c:geo.

So I guess its fine to close here with a valid workaround.
