### ISSUE TITLE
cgeo-1 emulator died

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12331]
@mucek4 

Seems the emulator died on cgeo-1. Can you restart it?
Is there anyway to restart this remote, so that we don't need to request your help when such things happen?

![grafik](https://user-images.githubusercontent.com/949669/146174530-be7d419d-0414-4213-933f-c9bd95e59c2b.png)

**Comment by mucek4** [comment]
The thing is. Emulator is alive and well on cgeo-1. I have restarted the docker image

**Comment by Lineflyer** [comment]
Thanks!
I enabled the node again, lets see if builds are running again.

**Comment by Lineflyer** [comment]
Yep, its working normal.
