### ISSUE TITLE
map themes not upgrading

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12345]
### Describe your problem!

Since some change in the past map themes are no longer checked for updates.

### How to reproduce?

- Have some map themes installed using the integrated downloader
- wait until at least one update is available
- select either "Update => Map data" from mainscreen menu or "Check for updates" in the map downloader

### Actual result after these steps?

Theme updates are not recognized, independent from map source. (Looking at the source: They are even no longer being checked for updates.)

### Expected result after these steps?

Theme updates should be checked for in the listed scenarios.

### Reproducible

Yes

### c:geo Version

2021.12.13

### Additional Information

Likely cause for this was removing map themes from the map downloader (and only implicitly downloading the theme files automatically) some months ago.

**Comment by moving-bits** [comment]
nice issue number ;-)

**Comment by eddiemuc** [comment]
> nice issue number ;-)

Hm, maybe I should use it as a password somewhere :-)

**Comment by eddiemuc** [comment]
https://youtu.be/a6iW-8xPw3k

**Comment by moving-bits** [comment]
> Hm, maybe I should use it as a password somewhere :-)

it needs an extra "6" at the end to be a secure password ;-)
