### ISSUE TITLE
maps update v5 from v4 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12344]
Feedback at FB:

Cgeo doesnt detect available update of existing old v4 Maps ( due to  New v5 Maps ).

We need to force download of thèse v5 maps

**Comment by moving-bits** [comment]
Working on it... They have made at least three changes:
- changed dir name from "mapsV4" to "mapsV5"
- renamed subfolder from "Germany" to "germany"
- renamed file from "Germany_North.zip" to "Germany-North.zip"

(Haven't checked the last condition for all areas, though)
