### ISSUE TITLE
Variable tab - Support of concatenated functions

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12359]
Not sure if this is not (yet) possible or I just don't get how it works:

I need to have a formula for this task:
"Einstellige Quersumme des Buchstabenwertes der Inschrift minus 7 ist B"

I tried `ichecksum(lettervalue('abc'))-7` but this has syntax errors

Should it already be possible at this stage of development (am I doing it wrong)? Otherwise lets take this as a feature request for later.

**Comment by eddiemuc** [comment]
This should already be possible and actually works for me:

![image](https://user-images.githubusercontent.com/6909759/146673011-6c2aaba0-927c-4f57-90f4-85d68762a6b7.png)

Am I missing something here? 

BTW: to reach the same as above you may:
* directly pass the string to ichecksum
* use the short forms of the functions (ics and lv).

E.g. the following also works:

![image](https://user-images.githubusercontent.com/6909759/146673061-6dd74a21-a19e-4b27-ba62-9556d77993a3.png)

**Comment by Lineflyer** [comment]
Strange....need to doublecheck

**Comment by eddiemuc** [comment]
Is this issue still relevant?

**Comment by eddiemuc** [comment]
@Lineflyer can this issue be closed or is there some bug still occuring?

**Comment by Lineflyer** [comment]
Yes, I doublechecked and it worked. I guess I just made a syntax mistake without noticing.
