### ISSUE TITLE
Variable tab - Remove focus from text fields if new items are added

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12358]
Just out on vacation and trying out the new variable tab.
Just a small improvement proposal.

To reproduce:
- Go to variable tab of a cache to prepare your cache trip
- Tap "+A" to add first variable, but cannot enter value yet
- Tap "+B" to add next variable and enter some formula for it
- Tap "+C" to add next variable, but don't enter a value
- Repeat this to add more variables (up to J in my case)

Result:
As the value field for variable B is still actively selected adding more variables will move the conrol panel on top out of view while using it.

Expected:
I suggest to remove the focus/edit mode from text fields as soon as an element of the control panel is used

**Comment by eddiemuc** [comment]
I see what you mean. The request makes a lot of sense

**Comment by eddiemuc** [comment]
Should be solved as part of PR #12368
