### ISSUE TITLE
Pick up coordinates from map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12361]
### Tell us your idea!

Request from user at support:

It's cumbersome having to create a waypoint or user-defined cache on map just to get coordinates for a specific point.

### What solution would you suggest?

Display a movable cross on the map (on demand) and display the cross's coordinates. Moving the cross by dragging it around updates the coordinates.

### Additional Information

ticket number 685604

**Comment by Lineflyer** [comment]
I would rather have the cross centered on the screen and move/zoom the map below it (see Locus).

**Comment by ztNFny** [comment]
I wonder what the usecase is for that? I often need my current coordinates, but I need them as text, e.g. to send them to someone or as target for navigation. For that I need them in clipboard. Displaying them on screen wouldn't help me - I'm not willing to remember and type those numbers, creating a waypoint to then copy them is way faster.

**Comment by moving-bits** [comment]
> I would rather have the cross centered on the screen and move/zoom the map below it (see Locus).

Sounds reasonable

> I often need my current coordinates, but I need them as text

One could make the coordinate display tapable - tapping would copy the coordinates to the clipboard.

**Comment by Lineflyer** [comment]
It could also be used as an alternative during wayoint creation in the coord input dialog like an entry "Pick from map"...I do also not see the need to show the coords next to the cross.

**Comment by fm-sys** [comment]
> It could also be used as an alternative during wayoint creation in the coord input dialog like an entry "Pick from map"...I do also not see the need to show the coords next to the cross.

I also don't see a real usecase in a permanent visible coord-identicator on the map. But I totally support the "Pick from map" idea which is already tracked here:  #7811

**Comment by moving-bits** [comment]
> a permanent visible coord-identicator on the map

sorry, I should have pointed out more clearly, that this is not about a permanently visible cross on the map, but something that can be switched on/off.

I guess this could be used for both use-cases, being on the map and trying to see some specific coordinates (e. g. for forwarding via a messenger), or by coming from waypoint editor to select some coordinates for the waypoint.

**Comment by bekuno** [comment]
Another use case is routing on the fly.
Sometimes I would know the distance to a point in the map (maybe an interesting place). In this situation I don't need a custom point in the map, it's just temporary.
