### ISSUE TITLE
Kurviger app

### ISSUE THREAD

**Issue by devemux86** [cgeo/cgeo#12374]
Hi everyone,

I am [Kurviger app](https://play.google.com/store/apps/details?id=gr.talent.kurviger) author.
(and maintainer of Mapsforge / VTM)

We have a report in our forum for failed communication between c:geo and Kurviger in latest versions:
https://forum.kurviger.de/t/destination-import-from-c-geo-app-not-working-anymore/7232

Is it related to https://github.com/cgeo/cgeo/issues/11134?
Do you need to include Kurviger package in your manifest too?
(there are 2 app packages)

**Comment by SammysHP** [comment]
For some apps we check if they are installed to directly invoke a specific intent or to use their API to transmit more details. To detect if the app is installed we have to declare these apps in the manifest since Android 12 (or 11?).

But for all other apps we just call the geo-URL intent and let the system decide which app to use for navigation.

**Comment by devemux86** [comment]
> But for all other apps we just call the geo-URL intent and let the system decide which app to use for navigation.

Can you write the exact geo url that c:geo calls?

**Comment by Lineflyer** [comment]
We had a similar report on support mail for another routing app as target app. AFAIK it was "Here We Go". I did not open a ticket here as I assumed a change on the third party side and I did not find any related recent change on our code.

I have an idea:
We recently included some geo intent receive method to e.g. trigger c:geo for searching around given coords....could that habe caused a problem with sending the intent?

**Comment by Lineflyer** [comment]
This is what "intent intercept" shows to me, when using Navigate - Other external app from c:geo:

intent:52.932933,7.920233?q=52.932933%2C7.920233(Gruselino)#Intent;scheme=geo;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: geo:52.932933,7.920233?q=52.932933%2C7.920233(Gruselino) 
URI: intent:52.932933,7.920233?q=52.932933%2C7.920233(Gruselino)#Intent;scheme=geo;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP

**Comment by devemux86** [comment]
Thanks for the extra details.
I will check Kurviger code to see how the intent is received.

**Comment by Lineflyer** [comment]
Unfortunately I am on vacation at this moment, so I cannot check the intent content used in older cgeo versions to check on differences.

If anyone is able to test with some 2021 summer release: The app "intent intercept" (available on fdroid) is perfect for this.

**Comment by ztNFny** [comment]
No change in the request between May 2021 and November 2021

cgeo-release_20210520.apk
```
ACTION: android.intent.action.VIEW
DATA: geo:37.422000,-122.084000?q=37.422000%2C-122.084000()
URI: intent:37.422000,-122.084000?q=37.422000%2C-122.084000()#Intent;scheme=geo;launchFlags=0x3000000;end
FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP
```

cgeo-release_20211213.apk
```
ACTION: android.intent.action.VIEW
DATA: geo:37.422000,-122.084000?q=37.422000%2C-122.084000()
URI: intent:37.422000,-122.084000?q=37.422000%2C-122.084000()#Intent;scheme=geo;launchFlags=0x3000000;end
FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP
```

**Comment by devemux86** [comment]
Thanks for the intents.
It seems we need to update the geo parsing in Kurviger app.
