### ISSUE TITLE
[Global Calculated Coordinates/Waypoints] Implement export-from/import-to Personal Note

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12378]
New global calculated coordinates/waypoints and variables will not yet be exported to Personal Note, and also not imported into waypoint list from it. This must be implemented.

**Comment by eddiemuc** [comment]
Import/export of waypoints to/from PN needs to be changed for following reasons:
* Variables are now no longer part of a waypoint/calculated coordinate and must be imported/exported as a separate "entity"
* Current calculated coordinate format concentrates on waypoints with single-letter vars only, itmust be possible to export/import arbitrarily complex formula expressions with multi-char-variables

While I want to leave the ability to the user to also "free-flow" specifiy waypoints with calculated coordinates as well as variables in the PN (which are both then scanned automatically), the format must be a bit stricter for this specific use case - because it must be guaranteed that all formulas saved can also be parsed again (there's a separate issue for a calculated waypoint scanner in the listing, this scanner can be a bit more "heuristic")

Keeping all this in mind I suggest the following formats:

Calculated waypoints:
* Store coordinates in a format `{CC|<Latitude Formula>|<Longitude Formula}`
* Example: `{CC|N41°53.((A/(B/3))+D)/2|E12°28.(C*B)+(A*(B/2))+(A+(C*4)-1)}`
* Example as part of a waypoint: `@My Waypoint (W) {CC|N41°53.((A/(B/3))+D)/2|E12°28.(C*B)+(A*(B/2))+(A+(C*4)-1)} "this is a meaningful waypoint note"`
* Whether to use `CC` as the marker or something else can be discussed (e.g. `CALCULATEDCOORD` - but I would rather use something short so not too much PN space is taken and a user may be able to type this himself in reasonable time if he wants to specify sich coords manually)

Variables:
* Store variable in following format: `$<VarName>=<VarFormula>`
* Example: `$A=34*wordvalue('test')`
* To be discussed: if a cache has more than one variable (which is likely), they can either be stored in PN taking one line each or in on line separated by |. Example for separated by `|`: `$A=34*wordvalue('test') | $B=3 | $C=3+7*A-length(D)`

@murggel I realize that this makes much work obsolete which you did when implementing parsing of F-PLAIN formulas. But I fear the concept has changed to much that I can't take over much. Sorry for this.

For those worrying what happens with already stored coordinates (in the old format): there is a big task for migration set up (#12379), I plan to handle these things as part of this task.

Here is a more complex example on how export to PN could look like (one normal waypoint, one calculated waypoint, three variables. In this example I stored each variable in its own line):

```
{c:geo-start}
@My Normal Waypoint (F) N41 53.123 E12 28.456 "this is the final!"
@My Calculated Waypoint (W) {CC|N41°53.((A/(B/3))+D)/2|E12°28.(C*B)+(A*(B/2))+(A+(C*4)-1)} "this is a meaningful waypoint note"
$A=34*wordvalue('test')
$B=3
$C=3+7*A-length(D)
{c:geo-end}
```

Storage format is now up for discussion...

**Comment by murggel** [comment]
> @murggel I realize that this makes much work obsolete which you did when implementing parsing of F-PLAIN formulas. But I fear the concept has changed to much that I can't take over much. Sorry for this.
> 

No problem, I highly appreciate your work on the calculator, mine was just an attempt for a quick solution and I am glad, that I don't have to extend it to the other coordinate-variants 😀

**Comment by murggel** [comment]
For storing variables, I would store them in one line separated by '|'.
Pro: compact format
Contra: reduce readability, char is on second page of the keyboard

IMHO the cons are not so serious, because the main editor for formula and variables would be the new calculator / var-list and not the PN. The PN would probably be used for backup or edited on PC with better keyboard and screen.

**Comment by murggel** [comment]
> Store variable in following format: $<VarName>=<VarFormula>

@eddiemuc 
Is the '$' needed or can you just use '<VarName>=<VarFormula>'? The separation char / new line should indicate a new variable and the '=' indicates the end of the variable-name

**Comment by eddiemuc** [comment]
> > Store variable in following format: `$<VarName>=<VarFormula>`
> 
> @eddiemuc 
> Is the '$' needed or can you just use `<VarName>=<VarFormula>`? The separation char / new line should indicate a new variable and the '=' indicates the end of the variable-name
> 

Strictly speaking the `$` is not needed. But I wanted to create consistency with waypoints (which are marked with an `@`, and one future day I plan to add `#` for lists, but that's another topic). 

Also when scanning PN we always scan the whole PN (not Just the part previously exported). This is good because I want to enable users to also manually add variables into PN which are then taken over (same as for waypoints). But if we just scan for `=` this might create some unwanted false matches.

**Comment by eddiemuc** [comment]
I implemented this as described (with $ as var marker) in PR #12457. 

Should we keep this issue open for discussion whether this is the right format? Or can we close here? (New issues can always be opened of course)
