### ISSUE TITLE
[Global Calculated Coordinates/Waypoints] Migrate local calculated coordinates/waypoints to global calculated coordinates/wayppoints

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12379]
In order to replace the local calculated waypoints  with global calculated waypoints, existing waypoints must be migrated to the new format.

Different aspects are to be considered:
* Local waypoints must be migrated. Since different waypoints in same cache may use same variable names, a variable replacement strategy must be revised so each coordinate will kep its original value even after migration. 
* Previously exported calculated coordinates/waypoints to Personal Note must still be readable by c:geo (and then be transferred into global coordinate/waypoint)

**Comment by eddiemuc** [comment]
Migration Test Data: "Degree Example 1":

![image](https://user-images.githubusercontent.com/6909759/151664026-a82aae46-7230-4f94-88ac-797d4c594327.png)

`{"format":1,"plainLat":"N 53° 33.065'","plainLon":"E 009° 59.621'","latHemisphere":83,"lonHemisphere":87,"buttons":[{"type":0,"inputVal":53,"autoChar":45,"customChar":0},{"type":0,"inputVal":51,"autoChar":45,"customChar":0},{"type":0,"inputVal":0,"autoChar":45,"customChar":0},{"type":0,"inputVal":0,"autoChar":45,"customChar":0},{"type":0,"inputVal":0,"autoChar":45,"customChar":0},{"type":0,"inputVal":0,"autoChar":45,"customChar":0},{"type":1,"inputVal":53,"autoChar":65,"customChar":0},{"type":2,"inputVal":53,"autoChar":66,"customChar":0},{"type":3,"inputVal":49,"autoChar":66,"customChar":70},{"type":0,"inputVal":48,"autoChar":71,"customChar":0},{"type":0,"inputVal":56,"autoChar":71,"customChar":0},{"type":0,"inputVal":48,"autoChar":71,"customChar":0},{"type":0,"inputVal":48,"autoChar":71,"customChar":0},{"type":0,"inputVal":57,"autoChar":71,"customChar":0},{"type":0,"inputVal":0,"autoChar":71,"customChar":0},{"type":0,"inputVal":0,"autoChar":71,"customChar":0},{"type":0,"inputVal":0,"autoChar":71,"customChar":0},{"type":0,"inputVal":0,"autoChar":71,"customChar":0},{"type":1,"inputVal":57,"autoChar":71,"customChar":0},{"type":0,"inputVal":57,"autoChar":72,"customChar":0},{"type":0,"inputVal":51,"autoChar":72,"customChar":0},{"type":2,"inputVal":54,"autoChar":72,"customChar":0},{"type":0,"inputVal":56,"autoChar":72,"customChar":0}],"equations":[{"name":65,"expression":"3"},{"name":70,"expression":"7"},{"name":71,"expression":"a+6"}],"freeVariables":[{"name":97,"expression":"6"}]}`

**Comment by eddiemuc** [comment]
Migration Test Data: DegMin Example 1

![image](https://user-images.githubusercontent.com/6909759/151664053-0d27488d-2ea3-4814-8810-62a867bade12.png)

`{"format":2,"plainLat":"N 53° 33.065'","plainLon":"E 009° 59.621'","latHemisphere":78,"lonHemisphere":69,"buttons":[{"type":0,"inputVal":53,"autoChar":45,"customChar":0},{"type":0,"inputVal":51,"autoChar":45,"customChar":0},{"type":1,"inputVal":51,"autoChar":65,"customChar":0},{"type":0,"inputVal":51,"autoChar":66,"customChar":0},{"type":0,"inputVal":0,"autoChar":66,"customChar":0},{"type":0,"inputVal":0,"autoChar":66,"customChar":0},{"type":0,"inputVal":53,"autoChar":66,"customChar":0},{"type":0,"inputVal":53,"autoChar":66,"customChar":0},{"type":0,"inputVal":48,"autoChar":66,"customChar":0},{"type":2,"inputVal":54,"autoChar":66,"customChar":0},{"type":0,"inputVal":53,"autoChar":66,"customChar":0},{"type":0,"inputVal":48,"autoChar":66,"customChar":0},{"type":0,"inputVal":48,"autoChar":66,"customChar":0},{"type":0,"inputVal":57,"autoChar":66,"customChar":0},{"type":0,"inputVal":53,"autoChar":66,"customChar":0},{"type":3,"inputVal":57,"autoChar":66,"customChar":82},{"type":0,"inputVal":0,"autoChar":83,"customChar":0},{"type":0,"inputVal":0,"autoChar":83,"customChar":0},{"type":0,"inputVal":57,"autoChar":83,"customChar":0},{"type":0,"inputVal":57,"autoChar":83,"customChar":0},{"type":0,"inputVal":54,"autoChar":83,"customChar":0},{"type":0,"inputVal":50,"autoChar":83,"customChar":0},{"type":0,"inputVal":49,"autoChar":83,"customChar":0}],"equations":[{"name":65,"expression":"a+b"},{"name":82,"expression":"4"}],"freeVariables":[{"name":97,"expression":"3"},{"name":98,"expression":"4"}]}`

**Comment by eddiemuc** [comment]
Migration Test Data: DegMinSec Example 1:

![image](https://user-images.githubusercontent.com/6909759/151664078-a4e2d0f1-617c-4029-951d-efa6c464e3a1.png)

`{"format":3,"plainLat":"N 53° 33.065'","plainLon":"E 009° 59.621'","latHemisphere":78,"lonHemisphere":87,"buttons":[{"type":0,"inputVal":53,"autoChar":45,"customChar":0},{"type":3,"inputVal":51,"autoChar":45,"customChar":87},{"type":0,"inputVal":51,"autoChar":88,"customChar":0},{"type":0,"inputVal":51,"autoChar":88,"customChar":0},{"type":0,"inputVal":48,"autoChar":88,"customChar":0},{"type":2,"inputVal":51,"autoChar":88,"customChar":0},{"type":0,"inputVal":0,"autoChar":88,"customChar":0},{"type":0,"inputVal":0,"autoChar":88,"customChar":0},{"type":2,"inputVal":56,"autoChar":88,"customChar":0},{"type":3,"inputVal":57,"autoChar":88,"customChar":68},{"type":0,"inputVal":57,"autoChar":69,"customChar":0},{"type":0,"inputVal":48,"autoChar":69,"customChar":0},{"type":2,"inputVal":48,"autoChar":69,"customChar":0},{"type":0,"inputVal":57,"autoChar":69,"customChar":0},{"type":0,"inputVal":53,"autoChar":69,"customChar":0},{"type":0,"inputVal":57,"autoChar":69,"customChar":0},{"type":0,"inputVal":51,"autoChar":69,"customChar":0},{"type":3,"inputVal":55,"autoChar":69,"customChar":65},{"type":0,"inputVal":0,"autoChar":66,"customChar":0},{"type":0,"inputVal":0,"autoChar":66,"customChar":0},{"type":0,"inputVal":50,"autoChar":66,"customChar":0},{"type":0,"inputVal":53,"autoChar":66,"customChar":0},{"type":0,"inputVal":57,"autoChar":66,"customChar":0}],"equations":[{"name":65,"expression":"1"},{"name":68,"expression":"3"},{"name":87,"expression":"2"}],"freeVariables":[]}`

**Comment by eddiemuc** [comment]
Migration Test Data: Plain Example 1

![image](https://user-images.githubusercontent.com/6909759/151664108-5b0d6c59-e591-491b-ad3e-602cfe09913e.png)

`{"format":0,"plainLat":"N 53° 33.AAA","plainLon":"E 009° 59.BCD'","latHemisphere":78,"lonHemisphere":69,"buttons":[{"type":0,"inputVal":53,"autoChar":45,"customChar":0},{"type":0,"inputVal":51,"autoChar":45,"customChar":0},{"type":0,"inputVal":51,"autoChar":45,"customChar":0},{"type":0,"inputVal":51,"autoChar":45,"customChar":0},{"type":0,"inputVal":48,"autoChar":45,"customChar":0},{"type":0,"inputVal":51,"autoChar":45,"customChar":0},{"type":0,"inputVal":0,"autoChar":45,"customChar":0},{"type":0,"inputVal":0,"autoChar":45,"customChar":0},{"type":0,"inputVal":56,"autoChar":45,"customChar":0},{"type":0,"inputVal":57,"autoChar":45,"customChar":0},{"type":0,"inputVal":57,"autoChar":45,"customChar":0},{"type":0,"inputVal":48,"autoChar":45,"customChar":0},{"type":0,"inputVal":48,"autoChar":45,"customChar":0},{"type":0,"inputVal":57,"autoChar":45,"customChar":0},{"type":0,"inputVal":53,"autoChar":45,"customChar":0},{"type":0,"inputVal":57,"autoChar":45,"customChar":0},{"type":0,"inputVal":51,"autoChar":45,"customChar":0},{"type":0,"inputVal":55,"autoChar":45,"customChar":0},{"type":0,"inputVal":0,"autoChar":45,"customChar":0},{"type":0,"inputVal":0,"autoChar":45,"customChar":0},{"type":0,"inputVal":50,"autoChar":45,"customChar":0},{"type":0,"inputVal":53,"autoChar":45,"customChar":0},{"type":0,"inputVal":53,"autoChar":45,"customChar":0}],"equations":[{"name":65,"expression":"1"},{"name":66,"expression":"2"},{"name":67,"expression":"3"},{"name":68,"expression":"4"}],"freeVariables":[]}`

**Comment by eddiemuc** [comment]
There is a bunch of smaller stuff still open, and I am sure there will be bugs incoming.
However, the last major topic to go productive with new variable/coordinate calculation is the migration of the former local calculated coordinates to the new global ones.

Reading the "old" values and putting them into the new calculation format is done in PR #12598 already. However, it is not easy to decide how to actually do the change. This is what I want to discuss with you here three things: migration algorithm, Auto Migration vs Manual Migration, Handling of PLAIN-WPs in user notes.

It is a bit much, might be something for next dev call...

### Migration algorithm to turn local vars into global vars

The old system used local variables (defined per-waypoint) to do calculations. All of them are one-letter only, there is a hardcoded dependency hierarchy: Uppercase vars can be used in the coordinate itself, Lowercase Vars can be used in the formulas for uppercase vars. That's it.

The new system uses cache-global vars. This leads to problems if the same variable is defined in multiple waypoints of the same cache with a different formula. Following example illustrates this:

* WP1: `N41 12.AB0 E11 34.345` with `A=a+b`, `B=8`, `a=6`, `b=2`
* WP2: `N41 12.12A E11 34.BC5` with `A=5`, `B=a+b-1`, `C=a+b`, `a=7`, `b=2`

I designed the example to include some possible discussion topics e.g.:
* `a` has different formula and value in both waypoints
* `b` is the same in both wps (formula and calculated value).
* `B` has a different formula in both wps but would calculate to the same value in both wps (which is 8)
* `A` in WP1 and C in WP2 have same formula but would calculate to different values

Question is now: what should be the algorithm to convert this mess into global vars?

My current idea (tbd): 
* go through wps one to another, check all vars.
* if a var is found not yet in the cache -> add it as-is
* if a var is found already in the cache AND this var has a different formula (not value!) ->
  * find a new var name for this by prepending an index (e.g. `A` becomes `A2`, `A3`, ... whatever is not taken yet)
  * replace in all formulas of the cache the variable `A` with the new variable using this syntax (example for `A2`): `($A2)`. Reason for this: using the parenthesis will make the resulting formula be recognized by the guided input as an "inline formula", so guided input would still work on those.

Using this algorithm on the above waypoints would leave WP1 untouched (because there are no variables in the cache beforehand), but turn the WP2 as follows:

`N41 12.12($A2) E11 34.($B2)C5` with `A2=5`, `B2=($a2)+b-1`, `C=($a2)+b`, `a2=7`, `b=2`
 
(`b` and `C` stay same because `b` has identical formula and value as WP1 and `C` is not used in WP1. All others are created anew and formulas are adjusted. The new vars `A2`, `B2`, `a2` would of course become global cache vars, there are no local vars any more in the new system)
 
I expect different opinions but also other ideas on this in the group e.g.:
* Is the overall algorithm suitable at all?
* Is the algorithm for creating new vars ok (e.g. instead of putting `A` to `A2`, one could also use the next free one-letter var, e.g. replace `A` with `D` in WP2)
* Is the format to put the new two-letter var into formula ok (`($A2)`)? But remember: only with parenthesis will this be recognized by guided mode.

### Auto Migration vs Manual Migration

The former section shows that migration algorithmic is probably complex. This means:
* possible long running time if user has many calculated waypoints stored (it is not just a DB script...)
* algorithmic might not always hit the user's expectations, which must be judged on an individual cache base

Normally one would do migration once on startup of the c:geo app with the first version containing the new feature. This would also mean it is a one-time-shot, it has to be right the first time and will never be repeatable again. This would require a huge amount of testing and a throughout algorithmic really covering all things. Otherwise users will loose data!

This is why I thought it might make sense to think about a "manual migration" as follows:
* Accessing the old calculation coordinate dialog is removed
* If the user opens the waypoint list of a cache containing old calculated coordinates, he gets presented some new button e.g. "coordinates to migrate". Clicking on it gives him a preview (tbd how it looks) what would be migrated and how the result would look. He can then decide whether to perform migration or cancel it (deleting the data for good).

There is another option actually: leave the feature in c:geo as is. This would allow the user to choose for calculated coordinates using local vars or global vars. Then we don't need a migration at all. This is a valid option if we feel that in some cases user might prefer to use local vars over global vars.

What do you think about this?

### Handling of PLAIN-WPs in user notes

User will have stored PLAIN-WPs in their user notes, and those won't just go away but must be handled for the time-to-be. 

My proposal here would be to handle this as "other" user note stored coordinates: if the coordinate does not exist yet, then create it. Likewise if the variables don't exist yet, create them. 

However, since for the old PLAIN WPs the variables were created with a local coordinate frame in mind, one might judge to do some sort of "replacement algorithm" as defined above there as well. This should be discussed and decided.

**Comment by Lineflyer** [comment]
My thoughts of auto vs. manual as a first feedback (before working through the rest next days):

I am not sure how many users currently actively use the (old) waypoint calculator, probably not so many as we e.g. still receive requests for such feature while we already have it (as it was not so prominently placed).
I would also assume, that most users build calculated waypoints for caches they are want to do on short term. After they finished those caches the calculation itself is probably no longer as important as the resulting coordinate.

Of course we should not just throw away existing custom data, but with the above being said, I would also tend towards a manual migration. Meaning, that migration is offered as soon as a user tries to work on such waypoint.

> If the user opens the waypoint list of a cache containing old calculated coordinates, he gets presented some new button e.g. "coordinates to migrate". Clicking on it gives him a preview (tbd how it looks) what would be migrated and how the result would look. He can then decide whether to perform migration or cancel it (deleting the data for good).

I wouldn't suggest a new button in the waypoint list, but rather when the user edits such old calculated waypoint the new "Calculate coordinates" button will trigger such migration dialog with the procedure you described above.
If the old calculated waypoint already has a valid result, it could also be offered to just drop the calculation and store the plain result.

**Comment by Lineflyer** [comment]
Regarding the migration algorithm itself (especially turn local vars into cache global vars):

Following up to what I suggested about migration dialog being triggered on each waypoint, it would as a consequence be problematic for properly assigning global vars without conflict. This would indeed make it necessary to migrate all waypoints of a cache at once.

But I had another idea in mind (not sure if there is any pitfall I did not think about):
Couldn't we just migrate the variables with a pattern consisting of the original variable and a (unique) waypoint identifier?
Such as, that e.g. a variable `a` in waypoint ID `12` would be migrated to something like `a_12` or whatever is still valid syntax for a variable.
This would ensure to avoid any conflict between the variables and formulas of any of the caches calculated waypoints. 
Of course it could/will lead to possible doubling of formulas and variables, but as we simply do not know whether these old calculated waypoints deal with different or same variables, I think we should not guess or put more effort into comparing formulas used in different waypoints, etc.

The result would not always look nice, but it would still be working and no information is lost. The user can clean up/optimize later on if needed.

**Comment by eddiemuc** [comment]
> migration dialog being triggered on each waypoint, it would as a consequence be problematic for properly assigning global vars without conflict.

I like the suggested idea to offer manual migration on a per-waypoint/coordinate-basis. This is possible conflict-free e.g. with the algorithm suggested above by me (maybe with other new-var-name-patterns etc): the Algo could change var-names as needed to integrate the waypoint in question conflict-free with already existing vars.

Yes I like this idea very much actually :-)

**Comment by Lineflyer** [comment]
> Yes I like this idea very much actually :-)

Thanks.... :)
So I guess you will rework #12598 then, so we shouldn`t merge?

**Comment by eddiemuc** [comment]
> > Yes I like this idea very much actually :-)
> 
> Thanks.... :)
> So I guess you will rework #12598 then, so we shouldn`t merge?

Yes
