### ISSUE TITLE
[Calculated Waypoints] Implement Scan Function trying to find calculated waypoints in listing and auto-create Calculated Waypoints for them

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12383]
c:geo should provide a scanner function in the wqypoint tab (third button "Scan for Wqypoints" under "Add Wayppoint" and "Add current location") which scans the cache listing for potential calculated waypoints and offers to create them. Quite similar to "+ Scan" function for variables, but for waypoints

**Comment by Lineflyer** [comment]
We already have the "extract waypoints" function, which does that (but not for waypoints containing variables though).

**Comment by eddiemuc** [comment]
> We already have the "extract waypoints" function, which does that (but not for waypoints containing variables though).

Didn't know that, where would I find this function?

**Comment by fm-sys** [comment]
Although the current feature is _really_ limited...

|||
-|-
![Screenshot_20211223_134928](https://user-images.githubusercontent.com/64581222/147242913-8c996131-b50d-4ffb-b4dc-03ffceaaf662.jpg)|![Screenshot_20211223_134942](https://user-images.githubusercontent.com/64581222/147242915-a54e6a5a-a2b5-49fb-a9e2-b37a6a4c4c62.jpg)

**Comment by ztNFny** [comment]
There has been some discussion on this in https://github.com/cgeo/cgeo/issues/12316#issuecomment-992423775 ff - just linking this here to make sure it doesn't get lost

**Comment by eddiemuc** [comment]
PR #12772 introduces scanning for calculated waypoints.

The algorithm to find such calculated waypoints in listings/text is of course rudimentary right now, and I am pretty sure it will / needs to be suject to further discussion. Let's first integrate the feature into c:geo and then fine-tune it.

@ztNFny from pst discussion I assume you already have very sophisticated routines to parse coordinate formulas from text in your grasp. Would be great if we can use this knowledge for c:geo as well. The key routine for parsing text for formula waypoints is `FormulaUtils.scanCoordinatePattern` - which as far as I am concerned may completely be replaced with an altrnative, better routine from any source available!
