### ISSUE TITLE
[Global Caclulated Waypoints/Variables]  make feature available for all users

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12382]
### Tell us your idea!

The feature of global calculated waypoints/variables is currenty only available for developers and nightly users. This is due to its current development state. This issue is a collector issue for all things which have to be done to put the feature live for all users (beta + later production).

Following things are open for that:
- [x] #12381 
- [x] #12379 
- [x] #12378 

Apart from functionality I would expect that the GUI could use a better look than it currently has. I depend on suggestions here though, I am not very good at this.

**Comment by Lineflyer** [comment]
Sounds good.
