### ISSUE TITLE
[Global Calculated Waypoints] Allow multi-creation of waypoints based on calculated waypoint

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12384]
https://github.com/siggel/coordinatejoker offers a nice possibility to test multiple input values and see the resulting waypoints. Would be nice to have this.

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/12316#issuecomment-992511234_

**Comment by eddiemuc** [comment]
I am thinking to allow for any existing calculated coordinate to specify a loop. On context menu of calculated waypoints add an option "Create multi waypoints" which opens a dialog allowing to specify:
* A variable used in the calculated coordinate of the waypoint (e.g. "A")
* A start value (e.g. 0), a stop value (e.g. 9) and a step value (e.g. 1)

Dislog would allow up to 2 of these "loops" to be specified.

On ok (and maybe after preview and confirmation esp when many waypoints would be created), c:geo would create a (normal) waypoint for each of the loop values. In the above example, 10 waypoints would be calculated and created usingthe values 0, 1, 2, ..., 9 for variable A.

**Comment by Lineflyer** [comment]
Do you mean something llike suggested in #2137 ?
Would highly appreciate this, as its a quite common usecase (for me), that I have a missing solution due to an unavailable waypoint while playing a cache. This would allow getting an easy overview to find the potential correct solution e.g. looking at the map.

**Comment by Lineflyer** [comment]
Taking over an idea given in #2137

> I have just seen a quite smart implementation of this in an android app:
You can actually enter WPs like that: N 51 20.[169]40 E 007 00.3[1479]30

**Comment by ztNFny** [comment]
> Taking over an idea given in #2137
> 
> > I have just seen a quite smart implementation of this in an android app:
> > You can actually enter WPs like that: N 51 20.[169]40 E 007 00.3[1479]30

I like the approach with variables better.

 N 51 20.[169]40 E 007 00.[169]30
vs
 N 51 20.x40 E 007 00.x30 with x=169

One is 3 options, the other 3*3

**Comment by ztNFny** [comment]
But maybe the global variables page could accept values like [0-9], [1,2,3] for a specific variable?

**Comment by eddiemuc** [comment]
> Taking over an idea given in #2137
> 
> > I have just seen a quite smart implementation of this in an android app:
> > You can actually enter WPs like that: N 51 20.[169]40 E 007 00.3[1479]30

I too like the variables approach better. Why introducing yet ANOTHER variable-like feature for a specific use case when we now have such a powerful approach in c:geo anyway?

> But maybe the global variables page could accept values like [0-9], [1,2,3] for a specific variable?

That's a tempting idea but would mess up the way the variable page works right now. It immediately recalculates all variables when the user types. This gets very complex if variables can have now more than one value "at once" and might seriously get an performane issue.

**Comment by eddiemuc** [comment]
What about making a specific dialog but allow to enter there the "loops" in the format introduced above (e.g. [0-9] or [1,2,3])?

**Comment by eddiemuc** [comment]
> But maybe the global variables page could accept values like [0-9], [1,2,3] for a specific variable?

Just had an idea how this might maybe work: we allow such "multivalue" expressions, but in all normal calculations only the first value is ever used (e.g. `0` for `[0-9]` or `1` for `[1,2,3]`). Only in special contexts the range is actually evaluated. What would you think of that?

I will try to think this through myself some more...

**Comment by eddiemuc** [comment]
See PR #12505 for a first drafty version

**Comment by eddiemuc** [comment]
Turns out PR #12588 implements a complete version already, so I close here. Please open individual new issues for new topics arise in context of this. Possible areas for those could be e.g. "waypoint naming algorithm for created waypoints" or "easy multidelete option missing for waypoints" (the new function may create many many waypoints at once if large ranges are chosen and combined)
