### ISSUE TITLE
[Formula] add support for basic boolean comparison

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12385]
Formulas should be able to handle basic boolean comparisons. Something like this should be possible:

`IF(A > 5;'red';'green')`: for `A=6` this s

**Comment by Lineflyer** [comment]
Maybe I did not yet fully understand the desired usecases for the variable tab. But: What would a user do with a variable containing a string at the end? I thought this is intended to provide numerical values to be used for waypoint calculation. (Basically the same remark I also made, when it comes to arabic -> roman conversion).

**Comment by eddiemuc** [comment]
> Maybe I did not yet fully understand the desired usecases for the variable tab. But: What would a user do with a variable containing a string at the end? 

I could make a different example with numeric results: 

IF(A > 5;8;9): for A=6 this should result in 8, for A=4 this should result in 9

A user can use a string result of a variable e.g. inside another variable formula (if he wants), e.g. like this:

```
A='solution'
B=ichecksum(A)
```

 Also, in some cases caches may require calculating strings inbetween to solve puzzles (e.g. rotating a string to see its real value)

**Comment by eddiemuc** [comment]
But even if wwe are not interested in string results in variables at all, I don't see any reason to actively forbid users to calculate such results. (it would actually be additional effort to firbid this, and I don't see why we would introduce this complexity)
