### ISSUE TITLE
Filter name is kept although filter has been changed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12407]
### Describe your problem!

I was using a predefined/saved advanced live filter and stumbled upon the fact, that when I change the filter setting I cannot clearly see, that this is no longer my saved filter.

### How to reproduce?

- Have a saved advanced filter (in my case hiding own and found caches, show only solved mysteries) with name "My filter"
- Load nearby caches
- Open filter settings, add filter element for cache type=Multi

### Actual result after these steps?

Filtering works as expected, but it still shows "My filter" with an asterik (*) behind, which is confusing as I (some clicks later) did not understand why its not working as expected for "My filter"

### Expected result after these steps?

Altering a predefined/saved filter (without storing it again) should invalidate the shown name and return to show the filter conditions instead.

### Reproducible

Yes

### c:geo Version

2021.12.23-NB

### System information

```text
Samsung S20, Android 10
```

**Comment by moving-bits** [comment]
closed as duplicate of #11356
