### ISSUE TITLE
updated external brouter not more useable

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12410]
> Btw, since some month the BRouter app is again active developed. They plan to release the new version "soon".

Seems as if time's up now - updated to the new version which came yesterday and promptly external routing is not working anymore. :/

Changes I recognized on first sight: new icon, new storage folder (below Android\media!?)

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/12172#issuecomment-1001071835_

There are also some reports on FB to this issue.

**Comment by Lineflyer** [comment]
IMHO we could drop the support of external routing.
The user can use the internal routing and either use the tiles from Brouter storage location or let c:geo load and manage the tiles.

**Comment by Lineflyer** [comment]
Looking at the debug log the problem with the new Brouter version seems to be:
```
2021-12-26 15:21:15.384 671-671/? W/cgeo: [main] brouter returned an error message: Profile car-eco.brf does not exists
2021-12-26 15:21:18.798 671-671/? W/cgeo: [main] brouter returned an error message: Profile car-eco.brf does not exists
2021-12-26 15:21:19.703 671-671/? W/cgeo: [main] brouter returned an error message: Profile trekking.brf does not exists
2021-12-26 15:21:23.658 671-671/? W/cgeo: [main] brouter returned an error message: Profile trekking.brf does not exists
2021-12-26 15:21:23.911 671-671/? W/cgeo: [main] brouter returned an error message: Profile shortest.brf does not exists
```

Looking at my selected storage location `/Android/media/btools.routingapp/profiles2/` the related files are there:
![image](https://user-images.githubusercontent.com/949669/147411008-0f08868b-ef47-4bc0-a26b-cb9f31b958fc.png)

@abrensch
Can you give some insights, if this could be a bug in the new Brouter version?

**Comment by Lineflyer** [comment]
BTW:

> The user can use the internal routing and either use the tiles from Brouter storage location or let c:geo load and manage the tiles.

Just tested that by using c:geo internal routing and setting the folder with routing data to the folder using by Brouter works normally.

**Comment by MagpieFourtyTwo** [comment]
Doing it this way since yesterday - no problems so far.

Thus I would agree to drop external brouter support *if* there will be a more obvious and less tricky possibility to download routing data tiles in advance.

Cause as 1.) data plans are limited, 2.) mobile data coverage is not even near to 100 % and 3.) download speed of these tiles is extremely slow, it's in fact nearly impossible to get a routing data tile if you are on the road.

And loading in advance by creating some fake routes is a real hassle, if you have to get a bigger area, esp. as you don't really know which regions are covered already and which ones are still missing ...

**Comment by abrensch** [comment]
> @abrensch Can you give some insights, if this could be a bug in the new Brouter version?

The update is mostly about filesystem stuff regarding android 11, but I was not actively involved in these changes.

You are sending the profile-NAME to tha aidle-interface? (not the mode or the profile content)

Then by looking at the source ( https://github.com/abrensch/brouter/blob/master/brouter-routing-app/src/main/java/btools/routingapp/BRouterService.java ) and at your errors messages it seems like a misunderstanding in whether or not to suffix the name with ".brf" ?

**Comment by Lineflyer** [comment]
@moving-bits Ideas?

**Comment by moving-bits** [comment]
We forward a parameter named "profile" to the routing service, containing our internal profile name (e. g. "shortest.brf"). This parameter name was available at the time I implemented the internal routing service, but it looks like BRouter has started to use that parameter name as well... I'll prepare a fix which uses a different name to transport that info.

**Comment by moving-bits** [comment]
> You are sending the profile-NAME to tha aidle-interface? (not the mode or the profile content)

We are using the `v` parameter to send the request profile type (`motorcar`, `bicycle` or `foot`).
