### ISSUE TITLE
Trackable indication no longer returned on search results

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12415]
### Describe your problem!

I am quite sure we discussed this while implementing the new search in the past, I can however neither find a matching issue nor any final conclusion:

We do have some users on different support channels telling us, that they are unable to filter for caches containing trackables. Testing this out my final conclusion is, that (in contrast to the old search) the new search does either not contain this information in its results or we have a bug to map this into the results.

### How to reproduce?

- Perform search (e.g. nearby or take a location where you don't have any stored caches)
- Look at the result list (or try to filter it for "Has Trackable"

### Actual result after these steps?

You will see, that in the result list no cache has a trackable indication (On the right above the favorite count) respectively the filter returns empty.
If you open some of the caches contained in the result you will sooner or later find a cache, that has trackables despite it was not shown in the result.

### Expected result after these steps?

Show "has trackable" icon if the cache contains trackables.
If this information is not contained in the search, maybe there is some search option to trigger it?

### Reproducible

Yes

### c:geo Version

2021.12.24

**Comment by eddiemuc** [comment]
I have to look this up (I am on vacation without code access currently), but it is unfortunately possible that the new GC search simply does not provide this information.

**Comment by eddiemuc** [comment]
Is the trackable info display if you search via "found by"? (Because this one still uses the old GC search)

**Comment by ztNFny** [comment]
> it is unfortunately possible that the new GC search simply does not provide this information.

confirming this, the info isn't available with new search

**Comment by eddiemuc** [comment]
> > it is unfortunately possible that the new GC search simply does not provide this information.
> 
> confirming this, the info isn't available with new search

Thanks for checking. This means unfortunately that we either have to live with this regression or switch back to the old search (or the API of course).

Probably needless to say, but I assume this only affects GC searches (and not oc searches)?

**Comment by Lineflyer** [comment]
I will assign this to add a remark into our FAQ (known limitation). Nothing more we can/should do.

**Comment by Lineflyer** [comment]
Reading https://forums.geocaching.com/GC/index.php?/topic/370226-release-notes-website-enhanced-search-results/

it could be possible, that this information is now available from the new search. 
Therefore reopening here.

**Comment by ztNFny** [comment]
search results json looks quite different. we need to check whether all searches are still working.

as for trackables, there's "trackableInfo": int

**Comment by eddiemuc** [comment]
There's another thing: the new search is using a new API which seems to be kind of a "v2" version of the one we're currently using. But if I issue search requests for v2 with attached "`&app=cgeo`" (which is what we always do out of fairness to gc.com), I get the following:

`{"statusCode":401,"statusMessage":"Unauthorized","errorMessage":"","uri":"http://websearch.groundspeak.biz/web/search/v2?skip=0&app=cgeo&take=50&asc=true&sort=distance&properties=callernote&origin=..."}`

if I use any other value it works, e.g. `app=test`.

So clearly they don't want us to use this web search...

**Comment by fm-sys** [comment]
@Lineflyer it's the same situation as for attribute filtering. Maybe we should simply ask them whether they can allow us to use the v2 API (for premium members for sure ;-))

See https://github.com/orgs/cgeo/teams/team/discussions/53/comments/13
