### ISSUE TITLE
remove cache(s) from all lists 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12416]
### Tell us your idea!

Sometime it is necessary to cleanup lists.
Mostly I will do it for archives caches. Then they shoulb be completely deleted from the device.
But in the list menu is only an entry to remove from the current list (`Remove selected from list`) 

### What solution would you suggest?

I need an entry `Remove selected from all lists` in selection mode, and in non selection mode an entry `Remove all from all lists`.

**Comment by Lineflyer** [comment]
You can first use "Make list unique" from List management menu (to delete the caches on the current list from all other lists) and then just remove all caches from that list.
IMHO this is a sufficient solution for this use case.

**Comment by bekuno** [comment]
Ah, now I understand this entry. But to really be useable it should a) be part of the caches menu and b) we should find a better wording (and translation).
In the current way it is a very hidden feature and not a solution.

**Comment by christmasguy** [comment]
Can I second the request for a delete from all lists?  The issue I'm having is that my c:geo storage is now over 8 GB which I think is huge for my phone compared to other apps.  I have a feeling the remove may take it out of a list but it does not delete the file structures created for each new cache.  Maybe a clean up option to delete / remove all files when they are not in a saved list.

**Comment by moving-bits** [comment]
@christmasguy 
Have you tried Settings => Offline Data => Maintenance?
This should cleanup c:geo files in the file system that are no longer referenced.

**Comment by moving-bits** [comment]
closing in favor of #15402
