### ISSUE TITLE
[Global Variables] Request for Vote: handling multichar variable names in formulas

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12417]
After recent discussion let's try to reach a decision on how to handle multichar variable names in formulas.

IMHO this is a two-fold decision:
* whether to use **prefix** or **surround** notation (see explanation below), and
* which character/symbol to use as a marker

**Prefix notation** means to use a certain symbol/character to mark the start of a variable name, but not have such a marker for the end of the variable name. In this case the end of the variable name is denoted by the first character not allowed in var names (non-digit and non-alpha), eg. a parenthesis or the end of the formula.

**Surround notation** means to use a certain symbol/character to mark the start of a variable name and another symbol/char to mark its end (start marker and end marker may or may not be the same symbol).

Current implementation uses **prefix notation** with `$` as the start marker symbol. The following example expression shows how this can be used in a more complex formula with variables `A`, `B` and `hello`:

`AB + $hello + A$hello(AB)(B+1)`

With `A=1`, `B=5` and `hello=2` this expression would be evaluated to `15 + 2 + 12156 = 12173`.

Here are some examples on how this expression would look like with different notations and symbols:
* **Prefix** notation with `#` as marker: `AB + #hello + A#hello(AB)(B+1)`
* **Prefix** notation with `@` as marker: `AB + @hello + A@hello(AB)(B+1)`
* **Surround** notation with `#` as marker: `AB + #hello# + A#hello#AB(B+1)`
* **Surround** notation with `[]` as markers: `AB + [hello] + A[hello]AB(B+1)`
* **Surround** notation with `{}` as markers: `AB + {hello} + A{hello}AB(B+1)`
* **Surround** notation with `()` as markers: `AB + (hello) + A(hello)AB(B+1)`

Note that **Surround notation with `()`** is a very special case because this means that `()` is in the future interpreted in two different ways: if the inside of the `()` is purely filled with alphas and digits (a valid var name), it is interpreted as "marker" for a multichar var name, in all other cases it is interpreted as expression grouper and to influence operator precedence (as today). Something like `(AB)` is then always interpreted as one var with name `AB`, never as two concatenated vars `A` and `B` any more.

Note that `<>` cannot be used as markers since this would conflict with relational operator interpretation.

Finally, here is a screenshot of the "first class" symbols (easy to reach on Android virtual keyboard) - at least on my device. Hope this is a typical example:

![Screenshot_20211227-140243](https://user-images.githubusercontent.com/6909759/147484258-4d139893-0a48-4541-a1e8-dbef6433b3cc.jpg)

Please use the emojis to vote on the notation to use:
* "Thumbs up" for "prefix notation"
* "Thumbs down" for "suround notation"

Also please use the emojis to vote for the symbol(s) to use as markers:
* "Smiley" for `$`
* "Party hat" for `#`
* "Frowning smiley" for `@`
* "Heart" for `()`
* "Rocket" for `[]`
* "Eyes to left" for `{}`

If there are any other ideas, please comment. But this is all I got...

**Comment by ztNFny** [comment]
() [] are often used in formulas, even if it technically works using those would make reading formulas very hard.

I'd like to add another suggestion that linux users should be familar with:
Both `$test` and `${test}` - this gives the advantage of "easy" to use with $ or "advanced" with ${..} for more complex situations.

**Comment by eddiemuc** [comment]
> Both `$test` and `${test}`

I like this idea very much

**Comment by moving-bits** [comment]
I would refrain from using round brackets `()` as multichar variable marker to avoid ambiguity. 

Prefix notation is fine, remains the question which prefix character to choose. And this probably depends on the keyboard you are using - the same symbol may be directly on the symbol page of your keyboard (together with +/- etc.), whereas on other it might be on the alternative symbol page. (On default Samsung keyboard `$` is available directly.) It even may depend on the specific keyboard layout you choose, so I guess we won't be able to find a single special character available on every keyboard as "first class", and easy to recognize as variable identifier at the same time. - Thus: As `$` and `${}` notations are very common for programmers etc. I vote for choosing it.

**Comment by fm-sys** [comment]
I'm still asking myself whether concatenation is needed for variables at all...?!

> Concatenation is used all the time in geocaching especially for coordinates in Multis/mysteries. E.g. something like the following: N41 12.ABC E12 44.A(A+1)(B-5)

That's right for sure. However, concatenation is always used in context of coordinates, but never for individual variables (proof me wrong ;-)). As whole coordinates can't be stored in a variable anyway but only in the WP calculator instead, it would IMHO be totally consistent to apply concatenation only there...

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/12408#issuecomment-1001666728_

**Comment by eddiemuc** [comment]
> I'm still asking myself whether concatenation is needed for variables at all...?!

With the solution idea of @ztNFny to reference variables (which I like very much), this is no longer an issue because concatenation and variable referencing does not conflict any more.

**Comment by fm-sys** [comment]
> this is no longer an issue because concatenation and variable referencing does not conflict any more.

Still, no real answer about the potential use case... ;-)

The suggestion is acceptable and fine for me, although it will definitely be still far away from being intuitive for Jon Average. The question is whether we want do design it for people who don't use cgeo on a daily basis...

And BTW, we should think about introducing a small "cheat-sheet" directly into cgeo with a link to the full manual. Otherwise, nobody will be able to remember the full potential... (we already have a similar thing for "search by filter")

**Comment by ztNFny** [comment]
one usecase: listing with variable names "blue", "black", "red", ...
Of course you could replace them with A, B, C, but then you have to keep the mapping table in your head.

**Comment by eddiemuc** [comment]
> > this is no longer an issue because concatenation and variable referencing does not conflict any more.
> 
> Still, no real answer about the potential use case... ;-)
> 

No need imho. It is simply far easier for the user if formula syntax is the same for simple variables and for coordinates calculation than introducing two different syntaxes. Also, as so often, I am directing towards GCBuddy which is doing it the same way. Third point: why would I invest effort in explicitly removing functionality if there's no need to do it?

> And BTW, we should think about introducing a small "cheat-sheet" directly into cgeo with a link to the full manual. Otherwise, nobody will be able to remember the full potential... (we already have a similar thing for "search by filter") 

There's already a help button on variable page. I tried to explain the syntax as easy as I could, everyone is free to work on this page.
