### ISSUE TITLE
CI cgeo-5: Could not create ADB Bridge

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12429]
The latest CI builds on cgeo-5 are run in this error:
~~~
22:50:48 * What went wrong: 
22:50:48 Execution failed for task ':main:installBasicDebug'. 
22:50:48 > com.android.builder.testing.api.DeviceException: Could not create ADB Bridge. ADB location: /opt/android-sdk-linux/platform-tools/adb
~~~

I have now deactivated the executor.

@mucek4 or @kumy Please restart the docker.

**Comment by Lineflyer** [comment]
I have already informed @mucek4 . He wanted to take a look. 
Is it possible to create some method to remote restart the docker/container?

**Comment by mucek4** [comment]
Docker containers are running in private network with no opened ports to internet. I'll try to create better health manager for them. They should restart on their own.

**Comment by bekuno** [comment]
cgeo-5 works fine now.
closing here.
