### ISSUE TITLE
Incoming navigation intent from ALC app named "Undefined"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12427]
### Describe your problem!

Reported by users:
It is possible to trigger navigation for a adventure lab stage from the Groundspeak ALC app, select c:geo as target app and save it as UDC in c:geo. The name of this UDC was the name of that ALC waypoint but now the name is always "Undefined".

Not sure whether its the new c:geo version or the recent update of the Groundspeak app.

### How to reproduce?

![image](https://user-images.githubusercontent.com/949669/147605869-4c94c4d4-a5df-4e64-a03f-c56aa1c76de3.png)
![image](https://user-images.githubusercontent.com/949669/147605881-0bbb5f56-0738-4aa8-a119-7982e7c6b73c.png)

### Actual result after these steps?

![image](https://user-images.githubusercontent.com/949669/147605888-041815a7-d7ff-4d19-af2b-4b3c169de9d6.png)

### Expected result after these steps?

![image](https://user-images.githubusercontent.com/949669/147605909-a5b3fca0-9fed-498e-a633-4dc48f5c027f.png)

### Reproducible

Yes

### c:geo Version

2021.12.24

**Comment by Lineflyer** [comment]
Just tested with "GPS Status & Toolbox" as intent target and it also shows the coordinate with name "Undefined". So I am quite sure, its a change/bug in their app.

**Comment by Lineflyer** [comment]
Posted to their forum:

https://forums.geocaching.com/GC/index.php?/topic/368493-adventure-lab-app-before-and-after/&tab=comments#comment-5952444

**Comment by bekuno** [comment]
The ALC navigation problem with destination "Undefined" is fixed now.

**Comment by Lineflyer** [comment]
Jupp..just received the same feedback on support mail.
