### ISSUE TITLE
Bottom navigation shows in cache map view on map switch

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12423]
### Describe your problem!

Under specific circumstances bottom navigation wrongly shows when viewing a cache on map, including the "press back again to exit" toast, but going back goes back to the cache listing

So far I've only been able to repoduce this with links opened from my mail client (or by simulating those) https://play.google.com/store/apps/details?id=org.kman.AquaMail

![untitled](https://user-images.githubusercontent.com/1258173/147562726-177a1ff4-1458-4e78-9711-0d9f24897dd7.gif)

### How to reproduce?

1. Install https://f-droid.org/en/packages/de.k3b.android.intentintercept/
2. Click any link in any app -> open with "Intent Intercept"
3. Replace the content of "URI" field with
`intent://coord.info/GC123#Intent;scheme=https;category=android.intent.category.BROWSABLE;launchFlags=0x3000000;B.allowStartActivityExceptions=true;B.android.support.customtabs.extra.TINT_ACTION_BUTTON=true;i.android.support.customtabs.extra.TITLE_VISIBILITY=1;i.android.support.customtabs.extra.TOOLBAR_COLOR=-15395563;B.android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true;end`
4. "Send edited intent" and open with c:geo
5. View cache on map
6. Switch map (e.g. from Google to OSM)
![untitled](https://user-images.githubusercontent.com/1258173/147565189-e250e816-62be-495d-b478-6eceaca2d45e.gif)

### Reproducible

Yes

### c:geo Version

2021.12.26-NB

**Comment by Lineflyer** [comment]
The following has been decided today in our dev call regarding when to show/not show the bottom nav:
- Stored - Show list on map = No bottom nav
- Stored - Shows list on map + Users enables live mode = Show bottom nav (live map icon active)
- Stored - Open cache - Show map for cache = No bottom nav
- Stored - Open cache - Show map for cache + User enables live mode= Show bottom nav (live map icon active)
- Live Map - Show as list = No bottom nav
- Search - Search result = Show bottom nav
- Nearby search (in fact same case as above) = Show bottom nav

For those not participating in the call:
- This has been discussed case by case taking into account how user might understand it and trying to balance the presence of bottom nav to places where it is potentially understandable to be shown and potentially even needed. 
- This describes the starting point, which was seen as "Better less shown than to much". We can more easily add it to some more places later on (based on beta or first release feedback)  than remove it again in places where it was already used.
- Technical feasibility and potential side effects needs to be checked though

**Comment by fm-sys** [comment]
PR #12513 will solve this issue...
