### ISSUE TITLE
Should "Attribute Overview" belong to cache or list management menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12439]
I wonder if the new "Attribute Overview" for a list should belong to the menu "Manage caches" or "Manage lists".

As its a list specific function I would see it in "Manage lists". That menu has only few items while the "Manage caches" menu is already quite crowded.
Or does it also work for a marked or filtered subset of a list....then it would be more suited in "Manage caches".

**Comment by moving-bits** [comment]
I'd put it into the "manage caches" submenu, as it is about the caches of the current list, not about the list itself. And it works on currently filtered subset, so I guess it should stay in "manage caches" submenu.

**Comment by ztNFny** [comment]
Manage caches imo

But yes, the menu is getting crowded

**Comment by Lineflyer** [comment]
Then lets leave it in Cache management.
