### ISSUE TITLE
Automatic sorting by name not working for larger series

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12431]
### Describe your problem!

A user reported that for his trail/series of 81 caches the automatic sorting by name does not work.
I went to check the code and the detection is OK (the series of the user contain 4 common characters at beginning), but it seems we restrict this feature to a max of 50 caches:
https://github.com/cgeo/cgeo/blob/4028d8eb2faac13ec1e5b9dc5e9ddbf5b68aafd7/main/src/cgeo/geocaching/ui/CacheListAdapter.java#L668

I suggest to raise this to 100. 
Any objections or does anyone know why the limit is 50?

This looks so easy, that I can volunteer to adapt it, therefore assigning me.

### How to reproduce?

Store 80 caches with similar cache titles (e.g. Serie 1, Serie 2, etc.) 

### Actual result after these steps?

Caches are sorted by default (distance)

### Expected result after these steps?

Auto sorting (isSeriesList) should detect and sort by name.

### Reproducible

Yes

### c:geo Version

2021.12.24

### Additional Information

Knowing that this is no longer so important as we have per list sorting preferences meanwhile, still I would like to fix it.

**Comment by fm-sys** [comment]
Is there a reason why we do not simply remove the max limit completely?

**Comment by Lineflyer** [comment]
Even better...
I guess this was introduced back then while no one could imagine a series with more than 50 caches ;)
Or is there any performance impact expected?

**Comment by fm-sys** [comment]
> Or is there any performance impact expected?

Hm... Could be, that these calculations might take some millis on _really_ large lists.

Let's use 500 or 1000 as maximum and we should be save IMHO...

(Yes, there are really that large powertrails according to https://www.cachewiki.de/wiki/PowerTrail)

**Comment by Lineflyer** [comment]
I will go for 500 and prepare a PR.
