### ISSUE TITLE
Idea: no cache pop up in Map but...

### ISSUE THREAD

**Issue by koem** [cgeo/cgeo#1244]
I don't know how to name it.

Instead of a Popup on the Map, make the same Information show up in an area beneath / above the map. Map stays usable, cache Info stays visible.

So the screen is then divided into three areas:

[ Header      ]
[ Map          ]
[ Map          ]
[ Map          ]
[ Cache Info ]
[ Cache Info ]

Choosing another Cache will change the Cache Info.

You can close the Cache Info same way like the Popup today. After that the Map will be back to it's original size again.

**Comment by Lineflyer** [comment]
Covered in #3932
