### ISSUE TITLE
Open personal note editor from map popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12447]
### Tell us your idea!

Sometimes I would like to quickly note down e.g. a bonus number.
Up to now I need to open the cache and edit the personal note there.

### What solution would you suggest?

Include a menu item into the popup menu to open the personal note editor.

Additionally if there is already a note existing:
When tapping the hint button in the popup I can see the note but not edit it. It would be a nice addition if tapping the text would bring up the editor as well.

### Is there an alternative?

I need to open the cache details and open the personal note editor from there.

**Comment by murggel** [comment]
see #8928

**Comment by Lineflyer** [comment]
Indeed, duplicate of #8928
