### ISSUE TITLE
high contrast Google maps theme

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12456]
### Tell us your idea!

Google maps supports custom themes: https://developers.google.com/maps/documentation/android-sdk/styling

We should provide a (optional) high-contrast theme to make using the map easier in common caching scenarios.

### Additional Information

While offline maps are certainly the better choice in some cases Google maps has to be used. Sadly Google had been decreasing the contrast of maps over the years - if you look at a small path in a wood that will be a thin white line on a light-grey background, almost impossible to see, especially when the sun is shining bright on your display.

![Screenshot_20220102-004549](https://user-images.githubusercontent.com/1258173/147862457-d08db43d-dcb2-42ea-b944-8743b7405558.jpg)
Spot the path

And just that situation is when i need Google maps - I'm in the woods, OSM doesn't have the path but Google does - but the path is hardly visible there.

**Comment by ztNFny** [comment]
Preview of Google Maps styles in c:geo:

![image](https://user-images.githubusercontent.com/1258173/153056701-09e79be6-e738-4824-b2b9-df5408c73827.png)
![image](https://user-images.githubusercontent.com/1258173/153056843-5b732055-ad6e-42d4-b1db-9fe9db5840b2.png)

**Comment by ztNFny** [comment]
I'm working on general style support first, will try to create a geocaching-optimized version of the default Google Maps layout later on then

**Comment by fm-sys** [comment]
Already looks great 👍
