### ISSUE TITLE
update Github social preview image

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12466]
c:geo github social preview image should be updated, it's still using the old logo, old icons on map and not the official font.

****

The social preview is used once you e.g. link the repo from Facebook:

![image](https://user-images.githubusercontent.com/949669/147979901-48eba0ad-c384-4a7b-b836-79fee13e197f.png)

_Originally posted by @Lineflyer in https://github.com/cgeo/WhereYouGo/issues/338#issuecomment-1004355733_

**Comment by fm-sys** [comment]
I suggest to use our current playstore functional graphic for now. All further changes can be discussed in  #11915 

https://github.com/cgeo/cgeo/blob/653dfa7f7b0e233b70daa08f163bb4a123019e42/main/project/playstore/icons/cgeo_functional_graphic.jpg

![bild](https://github.com/cgeo/cgeo/blob/653dfa7f7b0e233b70daa08f163bb4a123019e42/main/project/playstore/icons/cgeo_functional_graphic.jpg?raw=true)

**Comment by ztNFny** [comment]
wasn't aware this is already coverd, closing
