### ISSUE TITLE
Customize position icon

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12474]
### Tell us your idea!

Some users recently and in the past contacted us, that they think the current position icon (blue arrow indicating your current position) is too small or not prominent enough for their eyes.

### What solution would you suggest?

Either optionally increase the size of the blue arrow on map  or have the option to replace it by custom icons or with custom colors to make it more visible.

Could be contained in the same section as the customization options for lines and colors of the map already implemented.

### Is there an alternative?

Leave it like that.

**Comment by MagpieFourtyTwo** [comment]
I would vote for either make it customizable or leave it as it is (which is in fact my favorite ;) )
Problem with position markers is that they hide the most important spot in a map: My current position.
And the bigger they are the more info they cover ...

**Comment by bekuno** [comment]
Near a cache you need also often the direction.

Maybe something like this compass rose and a thin line could help:
![Screenshot 2022-01-06 010843](https://user-images.githubusercontent.com/32555742/148307640-40bd5c5a-549e-4e68-aa9b-fcd2dd8d0abb.png)

**Comment by MagpieFourtyTwo** [comment]
IMO these position placed compass roses are kind of hard to read, not really suitable for a sideways glance.
Moreover, with map orientation "North Up" it's pretty superfluous anyway.  ;)
And with map orientation "Direction Up" (GM only, AFAIK), a compass rose is already displayed in the upper left corner ...
Maybe this one should be a bit more detailed (and prominent) to fit your need ...?

**Comment by moving-bits** [comment]
Can this issue be closed since we have the new position icon implemented with #12896?

**Comment by Lineflyer** [comment]
IMHO yes. 
We did also not have many of such requests (AFAIR only 3).
