### ISSUE TITLE
Add text and emoji for log smileys

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12471]
### Tell us your idea!

To make selecting the right smiley easier show also the description.

### What solution would you suggest?

Instead:
![Screenshot_20220104-214354_cgeo](https://user-images.githubusercontent.com/32555742/148121709-3907d2b3-76da-4a13-bd23-0ae41b749d99.jpg)

You will have:
![grafik](https://user-images.githubusercontent.com/32555742/148121137-0037303f-39f9-4386-9e24-e199c605124c.png)

**Comment by Lineflyer** [comment]
Strings are not localized though...that would be a bit more effort then :(

**Comment by eddiemuc** [comment]
What about simply showing the resulting smileys as emojis? if there are copyright concerns in using the original ones from gc.com then may uaing the closest similar emoji available on Android?

**Comment by ztNFny** [comment]
how about showing an actual smiley instead of the code? Unicode emoji should work everywhere

**Comment by ztNFny** [comment]
Quickly looked up some emojis that would fit - didn't find a match for all but spend only a few minutes:
😃😁😎😳😝😈😉🤡?🎱
☹️?😲😠?😪😘??❓

![image](https://user-images.githubusercontent.com/1258173/148124834-50f704c4-feac-4f0f-afeb-205f44635470.png)

**Comment by bekuno** [comment]
> 

Here you are:
![Screenshot_20220104-230320_cgeo](https://user-images.githubusercontent.com/32555742/148129975-cf7ae560-f74b-4cc6-9fe6-c0be832ce101.jpg)

**Comment by Eldenroot** [comment]
Cool, anyway use unicoded smileys would be better

**Comment by bekuno** [comment]
> Edit: Added more. For 😊😒 I picked similar ones. For the "black eye" one I couldn't find any - and I have no idea what that smiley is even supposed to mean.

Do you mean 🎱 ?
This is the eight ball from the pool billard, which is in the middle of 15 numbered balls.

How do you would integrate the unicode images - as image or text? What is to do to render unicode text as image?

**Comment by ztNFny** [comment]
> Do you mean 🎱 ? 

No, the one before that which is missing from my list. It's called "black eye"

**Comment by ztNFny** [comment]
> What is to do to render unicode text as image?

Nothing, just put the unicode char.

**Comment by bekuno** [comment]
> No, the one before that which is missing from my list. It's called "black eye"

German: "Veilchen" :-)
https://de.wikipedia.org/wiki/Blaues_Auge

**Comment by ztNFny** [comment]
> > No, the one before that which is missing from my list. It's called "black eye"
> 
> German: "Veilchen" :-) https://de.wikipedia.org/wiki/Blaues_Auge

I know the words, but what is it supposed to mean as a smiley? In which connect would that ever be used?

**Comment by bekuno** [comment]
> > > No, the one before that which is missing from my list. It's called "black eye"
> > 
> > 
> > German: "Veilchen" :-) https://de.wikipedia.org/wiki/Blaues_Auge
> 
> I know the words, but what is it supposed to mean as a smiley? In which connect would that ever be used?

Harsh critism of something? Hopefully it is seldom used. Such thing is not my way.

**Comment by bekuno** [comment]
![Screenshot_20220104-235412_cgeo](https://user-images.githubusercontent.com/32555742/148134918-560cc085-b949-454b-b60d-2083c1fb6035.jpg)

Mockup looks fine :-)

**Comment by bekuno** [comment]
> > > > No, the one before that which is missing from my list. It's called "black eye"
> > > 
> > > 
> > > German: "Veilchen" :-) https://de.wikipedia.org/wiki/Blaues_Auge
> > 
> > 
> > I know the words, but what is it supposed to mean as a smiley? In which connect would that ever be used?
> 
> Harsh critism of something? Hopefully it is seldom used. Such thing is not my way.

How about 🥴
https://emojipedia.org/emoji/%F0%9F%A5%B4/

**Comment by bekuno** [comment]
The idea of using emojis is nice, but the support on older Android versions is not good.
This is a screenshot from an emulated Pixel 3 with Android 5 (API 21).
![grafik](https://user-images.githubusercontent.com/32555742/148618375-fce5f603-b0d5-4260-a59f-0d4bd687f705.png)

At https://developer.android.com/guide/topics/resources/internationalization you see, that for Android API 21 we have Unicode 6.3 support.
But e.g. the clown face was introduced in Unicode 9 (Emoji 3.0), which is supported first in Android 8 (API 26).

So we either have to stick with emoji 2.0, use rendered images or maybe use a software solution. Does anyone have any ideas?

**Comment by moving-bits** [comment]
Are the emojis available as SVG in Android style?

**Comment by ztNFny** [comment]
This is the Adroid O ones: https://github.com/googlefonts/noto-emoji
Using unicode vs svg has the advantage that they match the users system style.

**Comment by bekuno** [comment]
You can set a dedicated font only to a `TextView`, see https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml#fonts-in-xml .
Is this then possible in the menu?

**Comment by eddiemuc** [comment]
> You can set a dedicated font only to a `TextView`, see https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml#fonts-in-xml .
> Is this then possible in the menu? 

I assume it is doable programmatically since in the end the option menu also consists of TextView fields
