### ISSUE TITLE
User defined caches

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#12477]
Version: 2021.12.24
For the first time I played wih user defined caches. The way I used it was enbaling the long press in the map settings. Upon long press a dialog opens, I can enter a "Name", however I have not found any way to edit and modify that name lateron after I pressed "OK". Also, at the time I press ok, the current position is taken as "cache coordinates", again, I have not found a way to lateron change those coordinates. Is this a works as designed or have I just not found the right controls to click on? How do I delete a user defined cache? If I use the delete function it is removed from the list (it always goes hardcoded to "Stored" instead of last list used), however it reamains in the cache cache as it seems.

**Comment by moving-bits** [comment]
Changing a UDC's name can be done by tapping on the name on cache details page. A dialog box will open where you can change the name.

Changing coordinates is done similar to other caches: Create a new waypoint with the desired coordinates and check the "set this coordinates in c:geo" checkbox. The only addition for UDC in this setting is that you are able to delete the "original waypoint" for UDC.

Deleting a UDC also does work like for all other caches: If you "delete" a UDC it gets marked as "to be deleted" in c:geo's database, and after the grace period of 72h it gets removed from the database. Or you select the database maintenance function under settings => offline data, which will remove all "to be deleted" caches from the database.

**Comment by baiti** [comment]
> Changing a UDC's name can be done by tapping on the name on cache details page. A dialog box will open where you can change the name.

Tried it, didn't work regardless where I click. The only spot that is sensitive to clisk is the "ZZ.....", which when clicked, allows to copy the value to the clipboard.

> 
> Changing coordinates is done similar to other caches: Create a new waypoint with the desired coordinates and check the "set this coordinates in c:geo" checkbox. The only addition for UDC in this setting is that you are able to delete the "original waypoint" for UDC.

That creates a reference point called "Marker 1" and yes, I can manually delete the original waypoint. Still in the waypoints list, the "Marker" is shown and on the map the icon is augmented with the "has corrected coords" indicator.

> 
> Deleting a UDC also does work like for all other caches: If you "delete" a UDC it gets marked as "to be deleted" in c:geo's database, and after the grace period of 72h it gets removed from the database. Or you select the database maintenance function under settings => offline data, which will remove all "to be deleted" caches from the database.

Interesting. That's new to me. Didn't know such  a feature existed.

**Comment by moving-bits** [comment]
> > Changing a UDC's name can be done by tapping on the name on cache details page. A dialog box will open where you can change the name.
> 
> Tried it, didn't work regardless where I click. The only spot that is sensitive to clisk is the "ZZ.....", which when clicked, allows to copy the value to the clipboard.

Did you try a short-click/tap?
Copying geocode, coordinates etc. is long-tap, changing name (only available for UDC) is short-tap.

> > Changing coordinates is done similar to other caches: Create a new waypoint with the desired coordinates and check the "set this coordinates in c:geo" checkbox. The only addition for UDC in this setting is that you are able to delete the "original waypoint" for UDC.
> 
> That creates a reference point called "Marker 1" and yes, I can manually delete the original waypoint. 

and the newly created marker as well

> Still in the waypoints list, the "Marker" is shown and on the map the icon is augmented with the "has corrected coords" indicator.

Hm, had observed that recently as well, but didn't open an issue for it. IMHO, in this use-case it should not set the "has corrected coords" flag.

**Comment by baiti** [comment]
> > > Changing a UDC's name can be done by tapping on the name on cache details page. A dialog box will open where you can change the name.
> > 
> > 
> > Tried it, didn't work regardless where I click. The only spot that is sensitive to clisk is the "ZZ.....", which when clicked, allows to copy the value to the clipboard.
> 
> Did you try a short-click/tap? - Edit: Short tap on the "Name" entry, not on the titlebar. Copying geocode, coordinates etc. is long-tap, changing name (only available for UDC) is short-tap.

Worked! ... I had it named "A2" and as it turns out one has to precisely touch the small font. I just wasn't patiently trying long enugh.

So in essence we can close it with works as designed.
