### ISSUE TITLE
[Nightly] Home menu entry "Backup / restore" points to "Settings"

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#12479]
### Describe your problem!

When being in ``Home`` page, the menu contains an entry labeled ``Backup / restore`` - which IMO should be a shortcut to the backup and restore functions. But contrary to (my) expectation, it just brings you to the main settings screen.

### How to reproduce?

1. Go to ``Home``
2. click the hamburger menu
3. click ``Backup / restore``

### Actual result after these steps?

Settings screen opens

### Expected result after these steps?

Settings => Backup / Restore should be opened

### Reproducible

Yes

### c:geo Version

2022.01.06-NB-c0049ae

**Comment by ztNFny** [comment]
Is it really neccessary for that to have an own item in main menu? It's an option in settings, so that menu item saves just 1 click and is probably not frequently used.

**Comment by Lineflyer** [comment]
We created that shortcut to make users more aware about the backup function.
From what I hear on support I guess it would be an alternative to automatically create cyclic backups. So the user does not need to be made aware of it.

**Comment by ztNFny** [comment]
imho "make aware" doesn't change anything. Either the user is aware of the need to create backup (not the possibility to do so) and he finds the backup button no matter where it is - or he isn't and will never create a backup.
As long as those backups live inside the c:geo directory they aren't really valuable as backups though - if your SD gets trashed so do the backups (or are they included in the Google Play backups?).
Only scenario I've used them for is switching between builds with different signatures.

**Comment by MagpieFourtyTwo** [comment]
> imho "make aware" doesn't change anything

Rest assured, it does.  ;)  Had several guys asking me what they can do with ``Backup / Restore`` cause they stumbled upon this de facto "Main menu entry".  Although they already knew that backups are a must, they did not know that c:geo is able to create an own one.  Moreover the entry is a good reminder when you see it from time to time.  Thus I would definitely keep it as it is.  Of course, apart from the fact that it should refer to the right place ...  ;)

@Lineflyer Automatic backups would indeed be a great idea, even better if the users would additionally be informed that they should backup c:geo's backup files to a different medium ... but even if not, even a backup on the same medium can happily be used for a re-installation.  *If* it has been written to a folder which will not get deleted automatically when uninstalling c:geo ...

**Comment by Lineflyer** [comment]
> @Lineflyer Automatic backups would indeed be a great idea, even better if the users would additionally be informed that they should backup c:geo's backup files to a different medium

That would be the ideal backup, but in most cases (on support) its not a complete loss of device data causing need for a backup but accidental deleted caches/list or other relevant data.

**Comment by Lineflyer** [comment]
Anyway back to topic:
I just checked and cannot reproduce your issue. Using that actionbar function from dashboard straightly brings me to the right settings part.

I will check and (if needed) open an issue for automatic backup.

**Comment by MagpieFourtyTwo** [comment]
> I just checked and cannot reproduce your issue. Using that actionbar function from dashboard straightly brings me to the right settings part.

??? Just tried it again ... and all I get after clicking the ``Backup / Restore`` menu entry is the ``c:geo Settings`` page, where ``Backup / Restore`` is just one (the last) section among others like ``Services``, ``Appearance`` etc. pp..  To finally get to the backup functions (like e. g. ``Start backup``) I have to additionally click on the ``Backup / Restore`` section again ...

**Comment by Lineflyer** [comment]
Can you please provide the version again and your Android version?

**Comment by MagpieFourtyTwo** [comment]
c:geo version:
-------
2022.01.06-NB-c0049ae

Device:
-------
- Device type: VOG-L29 (VOG-L29EEA, HUAWEI)
- Available processors: 8
- Android version: 10
- Android build: VOG-L29 10.1.0.150(C431E19R2P5)
- Screen resolution: 1080x2147px (423x841dp)
- Pixel density: 2.55
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: disabled - 21.48.15 (100400-414534850)

**Comment by Lineflyer** [comment]
Just updated my nightly and can reproduce now. I was on nightly 2022.01.02, there it was OK.

**Comment by Lineflyer** [comment]
@moving-bits Looking at recent changes: Might it be related to the settings search implementation?

**Comment by moving-bits** [comment]
> @moving-bits Looking at recent changes: Might it be related to the settings search implementation?

Quite possible, changing displayed settings screens was pretty tricky. I'll look into it.
