### ISSUE TITLE
Formulas not Scanned Correctly for GC93DAV

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#12470]
### Describe your problem!

Scanning GC93DAV for formulas leads to wrong results.

### How to reproduce?

1. Open GC93DAV in c:geo
2. Swipe to Variables
3. Scan Listing

### Actual result after these steps?

The scanned formulas contain:
`V-1) * ( F + S + D + W + L )`
`W * ( Z + C`
`M+ P + J + S`

### Expected result after these steps?

Instead the scanned formulas should contain:
`(V-1) * ( F + S + D + W + L )`
`W * ( Z + C + M+ P + J + S )`

### Reproducible

Yes

### c:geo Version

2022.01.04-NB-24dd676

**Comment by eddiemuc** [comment]
It is important to know that the formula scan is really in a pre-alpha state. Maybe it makes sense to collect examples like this one in a dedicated issue and then use them in unit-tests to make the formula scan ready for real life

**Comment by UniQP** [comment]
I would prefer to open (and directly fix) a separate bug for every scan problem. Otherwise, we might end up with a lot of examples with the same root cause. I'll also add a unit test in the bugfix PR (as in #12450).
