### ISSUE TITLE
Search in settings does not always work as intended

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12488]
### Describe your problem!

I tried out the new search for settings and its really helpful, however sometimes it fails to open the right settings page.

### How to reproduce?

- Open settings (German locale)
- Tap search 
- Enter "Ordner"
- From the results select "Geocache-Datenordner"

### Actual result after these steps?

Settings main screen opens

### Expected result after these steps?

Settings - Offline Data should be opened and focused on "Geocache-Datenordner"

### Reproducible

Yes

### c:geo Version

2022.01.06-NB

**Comment by moving-bits** [comment]
Reason for this is that for c:geo to jump to a preference it needs to know the app-internal key of that preference (see `preference_keys.xml`), and as "Geocache data folder" is a category, it (currently) does not have one.

I see several ways to fix this:
- exclude all preferences from search that do not have a key (would implicitly exclude preference categories that have no title) => technically correct, but probably not what we want
- add a "fake key" to all preference categories to make the adressable
- do not add fakekeys, but for preferences not having its own key jump to the next preference that has one

Option 2 is probably the cleanest one.

**Comment by eddiemuc** [comment]
> Option 2 is probably the cleanest one.

+1

**Comment by moving-bits** [comment]
After already having created quite a few missing preference keys manually... :-( I found a much more elegant solution: c:geo now automatically creates missing preference keys dynamically, so that "search in settings" has targets to point to, see PR #12493.
