### ISSUE TITLE
Button text not visible 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12494]
### Describe your problem!

The text of the "insert function" button is not visible. 

### How to reproduce?

Use larger font (if necessary) 

### Actual result after these steps?

![Screenshot_20220107_190645](https://user-images.githubusercontent.com/64581222/148587678-f80936fb-be7c-4417-9432-7e0387c56cdf.png)

### Expected result after these steps?

The button should use `wrap_content` as button width. No elipsis should be shown. 

### Reproducible

Yes

### c:geo Version

current master

**Comment by Lineflyer** [comment]
I thought the ... is the content?!

**Comment by eddiemuc** [comment]
In this specific case the ... is indeed the content. We can change this of course, but this is not a bug.
I leave this open to discuss whether to change this, maybe to the new variable icon (x)?

**Comment by ztNFny** [comment]
How about "𝑓" to represent "function"?
