### ISSUE TITLE
Automate copying of waypoints from cache description

### ISSUE THREAD

**Issue by RomNexus6** [cgeo/cgeo#1249]
Often caches have waypoints described inside cache text but not available as cache waypoint.

For example, have a look at GCM4Y8.
You'll found several coordinates inside cache text description but no official cache waypoints.

It would be nice if c:geo could create waypoints automatically from the coordinates inside the text.

I don't know: tapping and holding over a coordinate inside text will popup a dialog asking for a description (nice to have: description already populated with 3-5 words from text before the coordinates)?

The same feature would be useful also while reading the logs.

**Comment by GodfatherThe** [comment]
Any updates or plans? Even button like "extract coords" will be fine, I think

**Comment by pstorch** [comment]
I'll have a look

**Comment by GodfatherThe** [comment]
@pstorch
I don't see new button (menu bullet) in 2017.01.23-NB-92ddbb7. How have you implemented it?

**Comment by pstorch** [comment]
@GodfatherThe you need to select some text of the description and then a context menu opens.

**Comment by GodfatherThe** [comment]
No, even when selecting I don't see new bullet.

And BTW - us it possible to make it working without selection? You have regular expressions to parse all the text easily, why should people try to select anything? See http://www.geocaching.su/?pn=101&cid=15426 - it has five waypoints in the text not "near each other" in the next. I just want to have ability to create all WPs in one click, not with five clicks (actually with selecting it's the same as copy-paste to personal note, not simplier)

**Comment by pstorch** [comment]
This is the wrong menu. Don't you get this pop up menu to translate the text, etc.?

**Comment by GodfatherThe** [comment]
![screenshot_20170123-062913](https://cloud.githubusercontent.com/assets/918446/22207769/49db144a-e135-11e6-9bd0-6ac7fadb17b5.png)

Oh,found it. But it's really not simplier than copying:
Copy-paste:
1. Ling tap for arrows to appear
2. Selecting
3. Press "..." for bigger menu
4. Copy
5. Open menu,select personal note
6. Paste
7. Save.

Current:
1-3 same
4. Select menu bullet.

The approach as I thought it should be done:
1. Open cache menu
2. Press "Extract wps"

P.S @SammysHP or @Lineflyer - I remember I saw the issue with half-text in context menu and it was closed - but see screenshot, for me it still the same.

**Comment by pstorch** [comment]
With the text selection you are more flexible. Select one, some or all wpts and extract them. The global menu could only extract all, even if you don't want all. 
The textsize problem in this pop up menu is annoying, though.

**Comment by GodfatherThe** [comment]
Usually I want exactly to "Extract all", no exceptions. And I wonder why
one will need only one WP from the text

23 янв. 2017 г. 6:40 пользователь "Peter Storch" <notifications@github.com>
написал:

**Comment by pstorch** [comment]
Yes, different people have different ways of working. 
Maybe we can add an additional "Extract all waypoints" to the normal menu. @Lineflyer what do you think?

**Comment by Lineflyer** [comment]
I personally would also have looked for it in the cache details menu rather than in the text selection dialogue. Having both options however looks fine to me if that does not double the coding effort.
It is also more likely for the user to be found.

**Comment by pstorch** [comment]
Ah, maybe I have misinterpreted the suggested solution. No problem, I'll add an entry to the context menu as well.

**Comment by pstorch** [comment]
@GodfatherThe please test with the upcoming nightly

**Comment by GodfatherThe** [comment]
Yes, now is much better, thanks.
Small note - for some reason WPs are called "Personal note N", maybe it's better to give them other names to do not mix with actual personal notes points.

**Comment by pstorch** [comment]
> @GodfatherThe 
> Small note - for some reason WPs are called "Personal note N", maybe it's better to give them other names to do not mix with actual personal notes points.

Good point
