### ISSUE TITLE
Calculate waypoints: inputs get repeated

### ISSUE THREAD

**Issue by andrcoding** [cgeo/cgeo#12516]
### Describe your problem!

If I want to insert an equation at the variable field, e.g. A=-5, signs are repeated automatically. See the following example
Input: -5
Output: --5
Input: -5-
Output: --5-5-
Input: -5--
Output: --5-5--5--
It seems to be limited to sign '-'. I use the current cgeo und Galaxy S7 software versions.
The issue started some months ago.

### How to reproduce?

It always happens while insert a formula into a variable field with the sign '-'.

### Reproducible

Yes

### c:geo Version

2021.12.24

**Comment by Lineflyer** [comment]
The calculated waypoints facility is about to be replaced by a new implementation in one of the next versions. 
I did not yet try to reproduce but I guess it will not be fixed in the version which is going to be retired.. However we should probably check if the successor also has this problem.

**Comment by andrcoding** [comment]
Thanks for the fast response. I will check the future versions (incl. change logs) and come back if the problem still exists.

**Comment by Lineflyer** [comment]
It would be really good to get user feedback on the complete new implementation.
We do now have a "cache wide" variable tab and a reworked waypoint calculator making use of it.

It will take some time until the new version is live and maybe the new calculator will then still be hidden (only available in debug mode). But if you want to try it out and provide early feedback to us (which would be very helpful) you can think about upgrading to our nightly versions (see https://www.cgeo.org/development) where it is already usable in its current development state.
