### ISSUE TITLE
Calculated Coordinates: coordinates are not parsed as expected by Geocachers

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12511]
Current Coordinate parser is pretty simple: it parses coordinates from left to right, each formula it finds is considered to result in degree / minute / second decimal value depending on position and follow-up charater (°, ' or ").

This results in some behavior unexpected to geocachers. This is especially true for the NDD MM.MMM format. For example: 

* `N50°00.A+B+C'` with `A=2, B=3, C = 5` results in `N50° 8.2'` (where 8.2 = 00.2 + 3 + 5) instead of `N50° 00.010'` (which would be expected by geocachers).
* Something like `N214°` parses correctly even though the degree value is totally out of range

On dev meeting on 9.1.22 we discussed the following measurements:

**1) Parse parts before and after decimal point as separate formulas**

Evaluate both parts to integers (round up if is is a float value, throw an error if this is not possible) then concatenate them

Doing this `N50°00.A+B+C'` with `A=2, B=3, C = 5` will then result in `N50°00.10'`

**2) add leading zeros to minute decimal part**

If a coordinate part is identified to be a minute value and the part after decimal point is less than 3 digits long then it is filled up with leading 0 filled up 

Doing this (combined with the first measurement) `N50°00.A+B+C'` with `A=2, B=3, C = 5` will then result in `N50°00.010'` (note the leading 0 before 10)

**3) Evaluate coordinate for correct value ranges**. 

For example latitude shall not be outside +/-90 degree.

This issue is used to track implementation of the above. There were other measurements discussed at the dev meeting. For discussion of those I open another issue #12512

**Comment by Lineflyer** [comment]
This topic was also hot, when the first WP calc was introduced: https://github.com/cgeo/cgeo/issues/6716
(Didn't have the time yet to revisit the old thread, but maybe it has interesting conclusions/ideas in it)

**Comment by ztNFny** [comment]
> Evaluate both parts to integers (round up if is is a float value, throw an error if this is not possible) then concatenate them

Please keep in mind that a formula might be "N50°0A" (without a "valid" minutes part) with A being 1234 with the expected output of N50°01.234

**Comment by Lineflyer** [comment]
> Please keep in mind that a formula might be "N50°0A" (without a "valid" minutes part) with A being 1234 with the expected output of N50°01.234

With the old calc the solution for this was to use something like this:
N 50° 0X.Y with X=A/1000 and Y = A%1000

% = modulo operator, see: https://manual.cgeo.org/de/coordinatedialog#waypoint_calculator

**Comment by eddiemuc** [comment]
> > Please keep in mind that a formula might be "N50°0A" (without a "valid" minutes part) with A being 1234 with the expected output of N50°01.234
> 
> With the old calc the solution for this was to use something like this:
> N 50° 0X.Y with X=A/1000 and Y = A%1000
> 
> % = modulo operator, see: https://manual.cgeo.org/de/coordinatedialog#waypoint_calculator
> 

With the new solution you can use "N50° A/1000". This already works, and this should not be changed (no decimal point in the formula here)

**Comment by eddiemuc** [comment]
> > Evaluate both parts to integers (round up if is is a float value, throw an error if this is not possible) then concatenate them
> 
> Please keep in mind that a formula might be "N50°0A" (without a "valid" minutes part) with A being 1234 with the expected output of N50°01.234

That's a new one. What would be the rule to derive from this? Maybe: "if a minute value evaluates to something >= 1000 then divide it by 1000 and round to 3 decimal places"?

Same for seconds or degrees too?

**Comment by ztNFny** [comment]
In a script of mine where I do formula parsing I do a printf to get the calculation result as a formated number with at least 3 digits (for DMM), then put that into the coordinate and validate whether the coordinate looks valid.

N50°00.A with A = 12 -> 012 -> N50°00.012
N50°00.A with A = 120 -> 120 -> N50°00.120
N50°00.A with A = 1200 -> 1.200 -> N50°00.1.200 -> Error invalid formula (too many periods in DMM format)
N50°0A with A = 12 -> 012 -> N50°0012 -> Error invalid formula (not enough periods in DMM format)
N50°0A with A = 1200 -> 1.200 -> N50°01.200

**Comment by eddiemuc** [comment]
> This topic was also hot, when the first WP calc was introduced: #6716 (Didn't have the time yet to revisit the old thread, but maybe it has interesting conclusions/ideas in it)

Ok, I tried to work through this one. It is a very long discussions, pointing to other very long discussions, so I hope I catched the essense. If I understand it correctly:
* A vast majority of geocachers wants added "leading zeros" to the standard coordinate formats (seems I am in a minority here...) => so I guess we do that as well
* There seems to be agreement that both Minutes and Seconds should be filled up to three digits after decimal point with leading zeros. 
* It was not quite clear to me in the end whether this should also happen for degrees - and if yes whether to do it to 5 or 6 decimal places. I would rather NOT do trailing zeros for degress (just for minutes and seconds)
* There was also discussion whether something like N50° 12.34  should be turned to N50° 12.034 or not - and if not where the "border" is on when to apply leading zeros and when not (e.g. N50° 12.34 shall not have leading zero, but N50° 12.X shall, then what about e.g. N50° 12.3+3 or N50° 12.4X or N50° 12.X4 or ...). If I understood it correctly then it was agreed in the end to use same logic for all expressions - which would turn N50° 12.34  into N50° 12.034

**Comment by ztNFny** [comment]
Thanks for working through this. The behaviour described in your summary sounds good to me.

> It was not quite clear to me in the end whether this should also happen for degrees - and if yes whether to do it to 5 or 6 decimal places. I would rather NOT do leading zeros for degress (just for minutes and seconds)

Imho we MUST pad those places where it makes a difference (decimal minutes in DMM format), all other places are optional but should be consistent to avoid confusion.

**Comment by eddiemuc** [comment]
> > It was not quite clear to me in the end whether this should also happen for degrees - and if yes whether to do it to 5 or 6 decimal places. I would rather NOT do leading zeros for degress (just for minutes and seconds)
> 
> Imho we MUST pad those places where it makes a difference (decimal minutes in DMM format), all other places are optional but should be consistent to avoid confusion.

Consider the simple example N48.X° assuming X=6. Should this now be
* N48.6° (no leading zeros)
* N48.00006° (leading zeros, 5 digits)
* N48.000006° (leading zeros, 6 digits)

In my impression there was no clear solution which case to use in the linked discussion above. The pros and cons are pretty clear (first one is inconsistent to leading-zero-handling with minutes and seconds), but in contrast to minutes/seconds it is hard to define for degrees to how many digits one should trail with zeros (5 or 6 or something else?).

I personally would thus use solution 1 (no trailing zeros for degree) although it is not consistent with handling of minutes/seconds. In contrast to minutes/seconds I don't feel there's a "common agreement" among geocachers on how many after-digits a degree should have.

**Comment by ztNFny** [comment]
What I meant to say:
DMM -> the decimal minutes MUST be padded, everything else optional
DMS -> everything optional (as 50° 1' 1" == 50° 01' 01")
DD -> nothing should be padded as 50.1 and 50.01 are different but there's no to know the expected precision
