### ISSUE TITLE
Play store warning for play-services-tasks V18.0.0

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12526]
While checking up on the alpha channel to let the nightly APK (meaning: current state of `master`) be tested to get an update of #12409 the Play Console reported the following:

Der Entwickler von play-services-tasks (com.google.android.gms:play-services-tasks) hat schwerwiegende Probleme mit Version 18.0.0 gemeldet. Wir empfehlen, vor dem Veröffentlichen eines Releases auf eine neuere Version zu aktualisieren.

Der SDK-Entwickler hat uns Folgendes mitgeteilt:
play-services-tasks v18.0.0 has known issues that can lead to runtime NPEs (NullPointerException) when handling Task<Void> results in Kotlin code. We strongly recommend that you avoid using this version. This also impacts the SDKs listed in the December 9, 2021 release, because they all depend on play-services-tasks. A fix for this issue is included in play-services-tasks v18.0.1. See https://developers.google.com/android/guides/releases#december_16_2021

**Comment by moving-bits** [comment]
Hm, don't see a place where we include this library explicitly 🤔

**Comment by bekuno** [comment]
The referenced December update contains
* com.google.android.gms:play-services-location:19.0.0
* com.google.android.gms:play-services-maps:18.0.1

For the `location` there is now an update to 19.0.1 - PR #12484, and for `maps` we don not use the affected version, see PR #12482.

**Comment by bekuno** [comment]
PR #12484 is merged, we can close here.
