### ISSUE TITLE
Use mapsforge 0.17.0 instead of own fork

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12524]
Due to recent bugfixes in the mapsforge code by @eddiemuc we currently still refer to our own fork in `build.gradle`:
https://github.com/cgeo/cgeo/blob/4245f781b3bfc3efd7fa088cb50fc4760b516a7c/main/build.gradle#L345

12 days ago mapsforge released version 0.17.0:
https://github.com/mapsforge/mapsforge/releases/tag/0.17.0

@eddiemuc 
Can you doublecheck if your changes are contained there?
In that case it might be wise to switch back to that repo to also include other fixes contained.

**Comment by eddiemuc** [comment]
Confirming that the new version contains both fixes relevant for c:geo (the TouchHandler-fix as well as the svg hash fix). Switching to this version will also final-fix #10128

Should we wait for dependabot to bump up our version automatically or do you want to change it with an explicit own PR?

**Comment by fm-sys** [comment]
> Should we wait for dependabot to bump up our version automatically or do you want to change it with an explicit own PR?

dependabot will do nothing, because no relation exists between both dependencies, the one contained in our own repo and the official one. So manual work is required...

**Comment by eddiemuc** [comment]
> > Should we wait for dependabot to bump up our version automatically or do you want to change it with an explicit own PR?
> 
> dependabot will do nothing, because no relation exists between both dependencies, the one contained in our own repo and the official one. So manual work is required... 

I seem to remember that dependabot was able to distangle our special version-settinf on last release and supplied a PR...
Well it is also not a big deal to supply an own PR
