### ISSUE TITLE
Variable tab - Tidy up clear variables used in waypoint

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12535]
### Describe your problem!

I entered a calculation for a waypoint and afterwards accidentally clicked on "Tidy up" in the variable tab, which made all used variables disappear.

### How to reproduce?

- Create a caluclated waypoint
- Replace a digit by e.g. "a+b+c"
- Save the waypoint
- Change to variable tab, which shows a,b and c being empty for now (correct)
- Click tidy up (I did this, because while entering the digit I mispressed  s instead of a first, so the variable tab showed a,b,c,s)

### Actual result after these steps?

All variables cleared
In order to restore them you have to enter the edit mode on the calculated waypoint and store it again

### Expected result after these steps?

Variables which are used in a calculated waypoint should not been removed by "Tidy up" although they might be still empty

### Reproducible

Yes

### c:geo Version

2022.01.16-NB

### System information

```text
Samsung S20, Android 12
```

**Comment by eddiemuc** [comment]
This behaviour is what is implemented. I am not so sure yet whether this is to be considered a bug or correct behaviour. Staying with your example
* although the vars a,b,c are for now deleted in the main var tab, as soon as you enter the corresponding waypoint again they will reappear there ready for editing and entering a value. (if this does not work, it would be a bug. I tested quickly and it seems to work though)
* Nothing user--entered is lost by current behaviour. Vars with any input will NEVER be deleted. So keeping the empty vars seems not so urgent
* the "automatic var creation" which could lead to such situations can only happen during waypoint edit. There you have your own "tidy up" button for these situations, and this one will NOT delete empty vars on which the waypoint depends.
* If some empty, unused vars are NOT deleted in var main tab, then the user has no immediate feedback on why those are NOT deleted (he has to scan through the waypoints to find the connection). This might be confusing to him.

(Implementation-wise this would make things more complicated too, but it is of course doable)

**Comment by Lineflyer** [comment]
> although the vars a,b,c are for now deleted in the main var tab, as soon as you enter the corresponding waypoint again they will reappear there ready for editing and entering a value. (if this does not work, it would be a bug. I tested quickly and it seems to work though)

Yes, this works as you described.
It seems again to be a different use case I approached: I created all needed calculated waypoints in beforehand while at home. 
That particular cache reused found values at one stage in all further stages, like:
Stage 1: Find A, Next stage at N51 17.A*40, E006 55.A*55
Stage 2: Find B, Next stage at N51 17.(A+B)*22, E006 55.(A-B)*50
and so on.

So its perfect to have all that variables to fill in at one place in the variable tab, which is perfect.

Out on the field I simply went to the variable tab and wanted to enter the variable values as soon as I found them. Now I accidentally clicked "Tidy up" and all was gone. I needed to revisit each waypoint to make them appear again. 
That made me think, that tidying up those variables does not make sense.

> Nothing user--entered is lost by current behaviour. Vars with any input will NEVER be deleted. So keeping the empty vars seems not so urgent

They are not lost, thats good. But in my usecase above I would not want them to be removed from the variable tab, so I can see what variables I need and which of them are still to be filled, without revisiting each waypoint or entering them in that waypoint.

> the "automatic var creation" which could lead to such situations can only happen during waypoint edit. There you have your own "tidy up" button for these situations, and this one will NOT delete empty vars on which the waypoint depends.

That's good to know for such typo cases. 
 
> If some empty, unused vars are NOT deleted in var main tab, then the user has no immediate feedback on why those are NOT deleted (he has to scan through the waypoints to find the connection). This might be confusing to him.

I don't think so. I think then the user knows, that those are present in his waypoints. For me it was rather confusing, that those are removed.

**Comment by eddiemuc** [comment]
Actually I think you are right, tidying up in var tab should not delete vars used in waypoints. I put it up for implementation onto the long long list...

Still I am getting some doubts over here whether the var stuff is organized the right way currently. Process and logic gets too complicated for my taste. It would be great if we find some simplifications for the whole UX workflow.

**Comment by Lineflyer** [comment]
> Still I am getting some doubts over here whether the var stuff is organized the right way currently. Process and logic gets too complicated for my taste. It would be great if we find some simplifications for the whole UX workflow.

Theoretically we could e.g. remove the variable input on the waypoint input. I mean the possibility to enter values directly in this dialog. This would centralize value input into the variable tab.
The downside is, that someone currently using the old WP calc has a new workflow. But we could instead write a note there, that values can be entered in the variable tab.

I mean this part of the screen:

![image](https://user-images.githubusercontent.com/949669/149673838-1ff4df23-d029-4b3f-904f-e1a9288ea01c.png)

**Comment by eddiemuc** [comment]
> Theoretically we could e.g. remove the variable input on the waypoint input. 

It is like this in GCBuddy, and this is one of the things I hate about it. Because I always have to remember all the var values in my head when switching to the waypoint edit screen.

Also this would not make the workflow easier. Tidying up in var list then has to consider var usage in waypoints even more than today. Because it can't be done in waypoints Dialog any More.
