### ISSUE TITLE
Changelog problem after merging master into release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12555]
There seems to be room for improvement, when it comes to changelogs when merging branches.

I prepared the following:
- Empty `/main/res/raw/changelog_bugfix.md` (and added the two newest items to `/main/res/raw/changelog_base.md` as those where not yet contained in a productive release yet)
- Then I forwarded `release` to HEAD of `master`

Now the problem is:
- Shouln't we empty `changelog_base.md` on `master` after this merge in that case? IMHO it should start new on `master`?
- While `/main/res/raw/changelog_bugfix.md` is now empty on `release` Crowdin does not empty the localized version `/main/res/raw-*/changelog_bugfix.md` as its obviously has problems to handle empty files: ![image](https://user-images.githubusercontent.com/949669/149893646-b13a50d1-e9e6-47c4-b59f-47d5aa33bf06.png)

@moving-bits 
What to do?

**Comment by moving-bits** [comment]
> Now the problem is:
> 
>     * Shouln't we empty `changelog_base.md` on `master` after this merge in that case? IMHO it should start new on `master`?

See https://github.com/cgeo/cgeo/issues/12451#issuecomment-1015878943

>     * While `/main/res/raw/changelog_bugfix.md` is now empty on `release` Crowdin does not empty the localized version `/main/res/raw-*/changelog_bugfix.md` as its obviously has problems to handle empty files: ![image](https://user-images.githubusercontent.com/949669/149893646-b13a50d1-e9e6-47c4-b59f-47d5aa33bf06.png)

hm, good question. Maybe enter some dummy text? Is there some sort of comment in markup language? Or one could enter a text such as "none yet" or something similar.

**Comment by moving-bits** [comment]
Not directly related to your question, but regarding changelogs as well:

With having changelogs added to translatable strings, we do have the problem, that inserting a line seems to invalidate all strings after that line. Crowdin does save the translations itself, but you have to reassign all of them (for all languages which have the strings translated already).

Is there a way to let Crowdin always keep identical strings?
Or do we need to adapt our workflow? E. g. always append new strings at the very end of the whole file, and only build categories and order the string on preparing the beta?

**Comment by Lineflyer** [comment]
> Is there a way to let Crowdin always keep identical strings?

No, at least not with our free plan.

> Or do we need to adapt our workflow? E. g. always append new strings at the very end of the whole file, and only build categories and order the string on preparing the beta?

AFAIK Crowdin splits up the files into parts automatically to avoid such retranslations of everything. Usually it seems to take empty lines in markdown and `<p>---</p>`  in HTML to detect that. Thats also the reason why only changes in same categories are triggered for retranslation.

So the workflow should be to normally only append into each category, that should work without retranslations as long as an empty line is between each category.

I guess you tend to resort them as you think some change is maybe more important than others.
How about we add a separate topmost category "Most important". Then we can append to each category and this should avoid any retranslation.

**Comment by Lineflyer** [comment]
BTW:
Inserting an empty line into changelog_bugfix.md did the trick.
Issues on Crowdin integration are gone and empty files are delivered in PRs.

**Comment by Lineflyer** [comment]
I updated https://github.com/cgeo/cgeo/wiki/Prepare-a-release#preparing-for-a-feature-release to reflect two things:
- Insert empty line into changelog_bugfix.md
- Keep changelog_base.md and add late incoming changes to that file on `release`
- Empty changelog_base.md on `master` timely after the release it out

**Comment by moving-bits** [comment]
Thanks for updating the release procedure.
FYI: We have a detailed description of our changelog handling in our Wiki: https://github.com/cgeo/cgeo/wiki/Changelog-handling
I've added the trick with the empty line over there as well.
