### ISSUE TITLE
Individual route not drawn when using Google Maps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12557]
### Describe your problem!

I tried today to create an individual route but it was not shown until I changed from GMaps to OSM.

### How to reproduce?

- Open live map
- Use GMaps
- Long click first cache/wp icon
- Long click second cache/wp icon

### Actual result after these steps?

Toast shows "Added to route" on long click, but no route is visible on the map
Only after changing from GMaps to OSM to route is shown

### Expected result after these steps?

Route should be shown on GMaps as well

### Reproducible

Yes

### c:geo Version

2022.01.18-NB

### System information

```text
Samsung S20, Android 12
```

**Comment by moving-bits** [comment]
Is the route being shown when you leave and then re-enter GMap? Or is it never shown in GMap?

**Comment by Lineflyer** [comment]
Never shown!

**Comment by moving-bits** [comment]
> Never shown!

Ok, thanks for cross-checking. So it's probably something with the "hidden" state, not with updating the route. I'll try to look into it the next days.
