### ISSUE TITLE
DMM coordinate with spaces incorrectly recognized as some kind of DMS

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12572]
Create a waypoint with this the new formula calculator and this input
N 50° 00.1 2 3
E 7° 00.1 2 3

and enter the variable values

Expected: DMM Coords -> N50°00.123 E007°00.123
Actual: DMS Coords -> N50°00.1'23 E007°00.1'23

The input isn't a valid DMS notation, DMS must have a ' to seperate minutes and seconds but the input uses only a .
So the input can only be DMM

In addition: As DMM is way more common in in geocaching than DMS in doubt coords should be interpreted as DMM, only input that's clearly DMS (containing °, ', '') should be interpreted as DMS

Repoduced with a build based on https://github.com/cgeo/cgeo/commit/9eec3c1f1733924c19cee6eda21f5594ebd660a3 (16.1.22)

**Comment by eddiemuc** [comment]
For these situation the "remove spaces" button was meant. It should resolve the Problem

**Comment by ztNFny** [comment]
> For these situation the "remove spaces" button was meant. It should resolve the Problem

It does. But even with spaced the formula should never be interpreted as DMS as it doesn't make valid DMS coords

**Comment by eddiemuc** [comment]
The new implementation which I am currently working on would actually reject the above because it would find 4 formula parts and it allows a maximum of three (which, if not otherwise indicated by °'", are interpreted as D, M and S in this order). But I assume this is not your point.

I have no good idea how to handle these spaces in a generic way yet. For example, what if C+D evaluates to e.g. 200 and evaluates to a float? Wouldn't it then be more valid to characterize E as seconds?

**Comment by ztNFny** [comment]
I've updated the OP with a more simplified example

**Comment by ztNFny** [comment]
> are interpreted as D, M and S in this order

I hope DMM instead of DMS?

**Comment by eddiemuc** [comment]
> > are interpreted as D, M and S in this order
> 
> I hope DMM instead of DMS?

Well, I meant DMS actually. Consider e.g. the following (user uses no °'" - just like myself btw):

`N41 12.345 67.890`

Parser will find a hemisphere char `N` and three "number blocks" here: `41`, `12.345` and `67.890`. It will interpret the first block as degree, the second as minutes, the third as seconds.

The point is: "space" is currently interpreted as a "number block separator". This is exactly what leads to the behaviour described in your issue. (BTW: space inside parenthesis is NOT recognized as block separator, only outside)

**Comment by ztNFny** [comment]
> N41 12.345 67.890

That doesn't match any coordinate format and thus shouldn't be parsed at all.
DMS notation requires ° ' ”, thus anything without that shouldn't be parsed as DMS.

In my experience 95%+ (I'd actually go as far as 99%) of caches use DMM notation, so that should be the default it tries to interpret the input as. Otherwise what we'll end up is users who use it once, get a wrong result and then just don't use the functionality anymore --- which would have been exactly my reaction if I wasn't involved here after using it twice and getting wrong results twice.

And there was a almost-zero chance of me discovering that c:geo is calculating it as DMS instead of DMM as I first entered the formula, then the variables, so I never got the preview of how it's interpreted but only the final calculated variable in waypoints list (DMS converted to DMM)

**Comment by ztNFny** [comment]
In case of unclear input, like your `N41 12.345 67.890` imho it's better to tell the user "your input can't be interpreted, please go and check for mistakes" than to guess something wrong.
Result of guessing wrong: User walks in the wrong direction for hundreds of meters, spends time searching, is frustrated because he wasted an hour of his time.
Result of requiring the user to validate the input: User is slightly annoyed that the calculator isn't more intelligent and spends 10 seconds fixing the formula.

**Comment by eddiemuc** [comment]
> In case of unclear input, like your `N41 12.345 67.890` imho it's better to tell the user "your input can't be interpreted, please go and check for mistakes" than to guess something wrong. Result of guessing wrong: User walks in the wrong direction for hundreds of meters, spends time searching, is frustrated because he wasted an hour of his time. Result of requiring the user to validate the input: User is slightly annoyed that the calculator isn't more intelligent and spends 10 seconds fixing the formula.

Would you consider the above input unclear? I think it is pretty obvious that he means DMS in this case.

Personally I would rather find an input like `N47 00.1 2 3` unclear. But I am sure there are different opinions out there about this. (and I already learned that I am in a minority when it comes to prepending zeros :-))

GCBuddy is doing strange things with this input btw:

![image](https://user-images.githubusercontent.com/6909759/150340177-4bd27d01-ab06-4ddd-ac82-1a37d962bfcf.png)

**Comment by eddiemuc** [comment]
> In my experience 95%+ (I'd actually go as far as 99%) of caches use DMM 

Agreed, I see it the same way personally. What threw me off is that c:geo gives dedicated support for DMS in all places, so I figured it must be important for the c:geo user group.

**Comment by ztNFny** [comment]
> Would you consider the above input unclear? I think it is pretty obvious that he means DMS in this case.

It's clearly not DMS as DMS coords have ° ' ''.

And even if it had those like N41°12.345'67.890'' I'd consider it invalid as the DMS coords don't have decimals in M, only (maybe) in S

N41 12.345 67.890 -> invalid
N41°12.345'67.890'' -> invalid
N41°12'67.890'' -> DMS
N41°12.1 2 3 -> DMM or invalid
N41 12.123 -> DMM
N41°12.123 -> DMM

**Comment by ztNFny** [comment]
> Agreed, I see it the same way personally. What threw me off is that c:geo gives dedicated support for DMS in all places, so I figured it must be important for the c:geo user group.

in my experience DMS is the before 2005 format and DMM the after 2005 ;-)

**Comment by eddiemuc** [comment]
> And there was a almost-zero chance of me discovering that c:geo is calculating it as DMS instead of DMM

At least there's a preview in the bottom of the dialog where °'" is always attached

**Comment by ztNFny** [comment]
> At least there's a preview in the bottom of the dialog where °'" is always attached

No - see the rest of the sentence that you cut of: "as I first entered the formula, then the variables, so I never got the preview of how it's interpreted but only the final calculated variable in waypoints list (DMS converted to DMM)"

I never got to see the preview with those chars.

**Comment by eddiemuc** [comment]
I tried to "convert" the requirement into parsing rules. I came up with the following additional rules which In think cover it:

* R1: coordinate may have up to three number blocks (degrees, minutes, seconds), but only the last one used may have digits after the decimal point

E.g. `N48 12 34.567` and `N48° 12.445` are ok but `N48°22.5' 3"` or `N48.223° 35'` are not ok.

* R2: when parsing the one allowed digits after the decimal point, spaces are ignores

E.g. `N48 12.3 4 5` is parsed as `N48°22.345'` and `N4 8 12.3 4 5` is parsed as `N4° 8' 12.345"`. `N4 8 1 2.3 4 5` would be illegal (4 number blocks before the .)

* Would thus fulfill the requirement?
* Is this be ok to be implemented by the team?

**Comment by ztNFny** [comment]
Sounds reasonable. We could even consider going a step further and only support DMM, not DMS, but of course this requires more input (after all noone has asked for UTM support either so far)

**Comment by Lineflyer** [comment]
> and only support DMM, not DMS, but of course this requires more input (after all noone has asked for UTM support either so far)

For the editor Iam totally fine with supporting only DMM. 
DMS for normal coordinate input/view/export should however stay.

BTW: We support showing coords in UTM;)

**Comment by ztNFny** [comment]
I'm not suggesting to remove anything, just saying that for the NEW formula stuff (calculation, recognizing coords in listing, ..) only supporting DMM would make things a lot easier while still covering almost all caches.

**Comment by Lineflyer** [comment]
> I'm not suggesting to remove anything, just saying that for the NEW formula stuff (calculation, recognizing coords in listing, ..) only supporting DMM would make things a lot easier while still covering almost all caches.

I am totally with you!

**Comment by eddiemuc** [comment]
Ah but removing DMS from the plain view would mean that DMS has to be removed from the guide view as well (the guide is just a "fancy" edit front for a plain view in the back). And this is something which was always there...

UTM... Well... I never had a cache where I needed this in a calculator. You really want this? But this would mean an own issue.

**Comment by eddiemuc** [comment]
Regarding DMS I also had  #12504 in mind (support for Google Maps coordinates), and they use seconds.

(And Implementation **does** support google coords now. At least for calculated coords :-))

**Comment by ztNFny** [comment]
> UTM... Well... I never had a cache where I needed this in a calculator. You really want this? But this would mean an own issue.

No, i dont want utm or dms

**Comment by ztNFny** [comment]
> Regarding DMS I also had #12504 in mind (support for Google Maps coordinates), and they use seconds.

For pasting we should definitly support that (as we do for utm with "insert from clipboard"), but not for formulas
