### ISSUE TITLE
Change the Icons for the fast start according to the bottom navigation icons

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12574]
### Tell us your idea!

Our current fast start buttons are the old from the main menu:
![Screenshot_20220120-210648_One UI Home](https://user-images.githubusercontent.com/32555742/150418173-e870bb43-1578-4b3e-8448-c9cda8b1e713.jpg)
This should be modernised somewhat in the light of the new design.

**Comment by Lineflyer** [comment]
Duplicate of #11969 ?

**Comment by bekuno** [comment]
> Duplicate of #11969 ?

Correct.
