### ISSUE TITLE
Both executors stuck on CI

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12580]
cgeo-1 and cgeo-5 fail to create ADB bridge / cannot launch emulator
@mucek4 Please kindly check or tell how we can solve this from remote?

**Comment by Lineflyer** [comment]
Reboot ongoing :)

**Comment by eddiemuc** [comment]
> Reboot ongoing :)

Very Good 👍

**Comment by fm-sys** [comment]
Still all executors seems to be offline...

![Screenshot_20220122_145203_org mozilla firefox](https://user-images.githubusercontent.com/64581222/150641125-fc1e3080-0669-4c83-a168-a5ec9f3c6184.png)

**Comment by bekuno** [comment]
reboot successful
