### ISSUE TITLE
WP Calc - Support exponents in waypoint formula

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12599]
### Tell us your idea!

This request is totally optional and I have seen such operators only rarely in cache listings. So if it would block or interfere with other features we can just skip this one.

I found GCKGVY today (which is BTW a good test case for potentially upcoming waypoint formula parsing).

It has two stages which use exponents, e.g. stage 2: `N 51° 15. B 0 A² E 06° 59. (A-B) (A-B) (A+BxB)`

### What solution would you suggest?

It would be nice if this the WP calc could either parse `A²` or upon  entering transform it into its factorization `(A*A)`

### Is there an alternative?

Manual edting

**Comment by fm-sys** [comment]
The syntax `A^2` is already possible today. So it would only be about automatic conversion while scanning for formulas...

**Comment by eddiemuc** [comment]
Would be very easy to add recognition of the high-2 to the parser.

**Comment by Lineflyer** [comment]
I am not familiar in depth with how the parser works, but for me either method would be fine (1. Allow it as valid operator / 2. Convert it while entering to what is support).

**Comment by eddiemuc** [comment]
Support for 2 and 3 added (chose those two because they are part of  ISO_8859-1)

**Comment by eddiemuc** [comment]
...in PR #12606
