### ISSUE TITLE
WP Calc - Allow C&P for whole coord at once

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12596]
### Tell us your idea!

Maybe its possible and I just don't know how:

In cache listings I often find things like `N 51° 15. (B) (A+B) (C-A+B) E 06° 5C. (B) (A-B) (C)` which are well prepared fomulas for the new parser but the usage flow to get them there is not always easy.

### What solution would you suggest?

I would like to have the ability to copy & paste these in one batch to the WP calculator. 

One step further:
Ideally there could be some feature comparable to the "scan listing" which finds such strings and creates calculated waypoints for it.

### Is there an alternative?

At the moment you have to either copy latitude and logitude part after another, or copy the whole string and delete the non needed part in either field (lat/lon).

**Comment by eddiemuc** [comment]
This is not yet possible. It figure this will come naturally once the scanning for calculated waypoints is implemented - for this there's an issue already: #112383
