### ISSUE TITLE
Source for map theme legend

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12605]
@moving-bits 
Thanks for implementing the map theme legend. Just to be able to answer some questions I had (or might come) on support and Crowdin:
- What is the source of information from where you derived it, or was it completely done from scratch?
- Are the corresponding strings potentially available in other languages (to help contributors with translation) or can they at least be shown on some website for better understanding while translating?

**Comment by moving-bits** [comment]
I have implemented a subset of the icons being shown in the official legends:
- https://www.freizeitkarte-osm.de/android/en/legende-outdoor-contrast.html
- https://www.freizeitkarte-osm.de/android/en/legende-freizeitkarte.html
- https://www.openandromaps.org/kartenlegende/elevation-hike-theme

(The info button in the legend links to those pages.)

Some additional texts (mostly the POI symbols) are derived from the icons' filenames.

AFAICS there are no given translations other than English and German, which are both implemented already.

**Comment by Lineflyer** [comment]
Thanks for information!
