### ISSUE TITLE
Allow more space for list name

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12613]
### Describe your problem!

Two separate user feedbacks regarding the same topic:

The current beta seems to reserve less space for the list name field compared to the current production. This causes the list name more likely to be cut off in favor of some more function icons in the title bar. 
Both users said, they would rather like a complete list name and accept more functions in the overflow menu instead.
Wording was like: "Mapping and filtering are important to be shown but why did you prefer sorting and select mode over a larger list name space".

 

### How to reproduce?

Screenshot comparison between production and beta (different user devices, still you get what I mean):
| Production | Beta |
| --- | --- |
|![Screenshot_20220125-150034_cgeo](https://user-images.githubusercontent.com/949669/151056619-f49c921b-b12a-4d7f-83f2-5904b48dd146.jpg)| ![Screenshot_20220125-150049_cgeo](https://user-images.githubusercontent.com/949669/151056637-6f7b8756-f8bc-4825-aec9-382f2f5dcda9.jpg)|

### Actual result after these steps?

Truncated list name in favor of two more icons

### Expected result after these steps?

Reserve bigger space for list name and accept only 1-2 icons being shown (i.e. restore the old look).

### Reproducible

Yes

### c:geo Version

2022.01.22-RC

**Comment by fm-sys** [comment]
I agree, that the "selection mode" button is not used that often and the icon is not really good anyway. But I really like it, to have the sort mode directly reachable :)

**Comment by Lineflyer** [comment]
I tried to look into this issue, but I do not have enough understanding of the layouts to find out where the size of the spinner is controlled.

I give up....Anyone working on this?

**Comment by ztNFny** [comment]
afaict the size isn't set explicitly but calculated by Android with the items from cache_list_options

If we set "showAsAction=never" for all but the first 2 / 3 (tbd) the dropdown size should grow.

**Comment by Lineflyer** [comment]
> If we set "showAsAction=never" for all but the first 2 / 3 (tbd) the dropdown size should grow.

That' s what I also assumed, but did not check if the `ShowAsAction`parameter changed since then?
But anyhow: How is `ifRoom` being calculated after all if I can't define the spinner size?

**Comment by moving-bits** [comment]
> If we set "showAsAction=never" for all but the first 2 / 3 (tbd) the dropdown size should grow.

Is there a way to differentiate between landscape and portrait mode? As in landscape mode there's probably enough room to show more than three actions (depending on whether they are shown with text or as icon only).

**Comment by Lineflyer** [comment]
Something is strange here anyway:
I tested now to set all entries to `app:showAsAction="never"` in `cache_list_options.xml` but it keeps showing like this:
![image](https://user-images.githubusercontent.com/949669/152241042-2169b583-e6fb-4ff9-ba29-7616671e4dfe.png)


Am I changing it at the wrong place?

**Comment by eddiemuc** [comment]
Sorry for my late reply.

I meddled with this stuff back when filtering was implemented because we wanted to show one action item more on the line (the filter symbol and iirc also the sort symbol).

Deeply buried in Android system there is some hard-coded logic which decides how many action items are displayed. This decision is based solely on screen width IIRC.

To override this I created a routine to set icons dynamically to "show always" based on our own rule set. Maybe the routine creates unwanted result sometimes these days.

**Comment by eddiemuc** [comment]
Code for this is in `ViewUtils.extendMenuActionBarDisplayItemCount()`. It extends the number of shown action icons to a maximum of 4 depending on screen width (if it is wider than 410dp then 4 icons are shown). Could this be the culprit here?

https://github.com/cgeo/cgeo/blob/f7663025aa24c2354425ad3ec1327030327bb35a/main/src/cgeo/geocaching/ui/ViewUtils.java#L339

**Comment by fm-sys** [comment]
But be aware: 
This method is also used for our map activity, where we don't seem to have these problems.

Furthermore, with the bottom nav we don't have the "back" button in the actionbar anymore, so one item more than before is IMHO acceptable (as it consumes exactly the same space)

**Comment by eddiemuc** [comment]
What about removing the usage of the method completely for the cache list activity? I noticed it was introduced there just a few month ago anyway (https://github.com/cgeo/cgeo/commit/92397336e24b6e886d6de95911f29557be496a6b).

**Comment by Lineflyer** [comment]
First of all lets compare with and without this method on a typical device (Android 11, Pixel4 emulator).

List:
| Orientation |  With own method | Automatic |
| --- | --- | --- |
| Portrait |![list_with_extendcode](https://user-images.githubusercontent.com/949669/152427664-ebbbdbc6-1256-4395-b273-c6473960fa4a.png)|![list_wo_extendcode](https://user-images.githubusercontent.com/949669/152427696-39f4ea8e-41f8-4374-a743-7ab7a79db85b.png)|
| Landscape |![list_with_extendcode_landscape](https://user-images.githubusercontent.com/949669/152427780-cffd015f-27df-4b9b-982b-42f74e7cd447.png)|![list_wo_extendcode_landscape](https://user-images.githubusercontent.com/949669/152427865-87a233fd-09e0-4a1e-99ee-376168502e44.png)|

My interpretation/opinion:
I don't see a real benefit on showing more items than suggested by Android and in exchange lose room for the important list name (e.g. some of my lists are like `3_Powertrail_NameofRegion ` and I currently only see `3_Powertrail_....`. 

My conclusion:
Let Android decide, preconditions are perfect in the layout. All items are `ifRoom|withText`

Map:
| Orientation |  With own method | Automatic |
| --- | --- | --- |
| Portrait |![map_with_extendcode](https://user-images.githubusercontent.com/949669/152429906-ef1d75e5-b8d0-4689-b516-68ac7729e364.png)| ![map_wo_extendcode](https://user-images.githubusercontent.com/949669/152431504-433cb0fc-69a1-4536-9e8f-15f7ed12acf2.png)|
| Landscape | ![map_with_extendcode_landscape](https://user-images.githubusercontent.com/949669/152431555-be206aef-bbdb-4a73-8c05-0410e29a0694.png)|![map_wo_extendcode_landscape](https://user-images.githubusercontent.com/949669/152431580-5d1fa008-5d22-4c3e-bec6-7c5cf641156a.png)|

My interpretation/opinion:
1. The method seems to overwrite the `with text` option as texts are not shown on landscape now. A feature loss IMHO.
2. The space consumed is rather uncritical as text field length on the left is more or less constant.

My conclusion:
Either we should extend the method to keep the `with text` option or also return to let Android decide.
Question: Why was this method introduce in first place. I found this commit which refers to issues not matching this detail: https://github.com/cgeo/cgeo/commit/f93f02d0567f09a7341d6568fa7e553766028da6

**Comment by fm-sys** [comment]
> Question: Why was this method introduce in first place

Cause many devices did only show two menu action items (depending on screen size), so the "filter" button would have been not visible. But we have to ask ourselves which actions are used most?

For me, I'm using "my location" and "filter" very often, but change the map source only very seldom. Without this "hack", the filter action would be hidden in the overflow menu (at least on my device), which definitely decreases usability.

For cache lists, indeed, this behavior was introduced together with the bottom navigation and we can remove it if it's really not wanted.

But it doesn't make sense to change anything at the map. It was like this since months and no one did ever complain. And with the introduction of bottom navigation, we got even more space in the actionbar cause the back arrow is no longer displayed. I feel like we are trying to solve things here, which never where broken...

**Comment by Lineflyer** [comment]
> Cause many devices did only show two menu action items (depending on screen size), so the "filter" button would have been not visible. But we have to ask ourselves which actions are used most?
> 
> For me, I'm using "my location" and "filter" very often, but change the map source only very seldom. Without this "hack", the filter action would be hidden in the overflow menu (at least on my device), which definitely decreases usability.
> 

That is a matter of use case. I know many users from support regularly using OSM or offline maps (thanks to their details) but also switch to Google sat to get a visual match on site.

Do you mean the "filter" icon on map or lists?


> For cache lists, indeed, this behavior was introduced together with the bottom navigation and we can remove it if it's really not wanted.
> 

I agree for lists. As the comparison shows the list options without our tuning are better fitted and the list name is shown longer as well.

> But it doesn't make sense to change anything at the map. It was like this since months and no one did ever complain. And with the introduction of bottom navigation, we got even more space in the actionbar cause the back arrow is no longer displayed. I feel like we are trying to solve things here, which never where broken...

I don't see any difference in the example above....what do you mean?

**Comment by eddiemuc** [comment]
To sum up discussion above, I feel we should remove the behavior for lists but keep it for map.

Remark: back when I introduced this for map to show filter symbol I was myself not a strong advocate of this solution. So I would be ok to remove it there as well. But as @fm-sys said, users seem not to complain about this one, so keeping it there seems the right thing to do.

**Comment by fm-sys** [comment]
> Do you mean the "filter" icon on map or lists?

Actually both, but for lists it's less problematic cause the button is more a the left (2. vs 3.)

> I don't see any difference in the example above....what do you mean?

I'm nearly 100% sure you probably just haven't disabled the correct code part for the map activity while creating the screenshots.

That's how it looks for me:
(have searched for a historic screenshot which matches with my memory about how it was before)

With "hack" (currently) | Without hack
-|-
![Screenshot_20220204_064131_cgeo geocaching](https://user-images.githubusercontent.com/64581222/152482281-177985a3-dbd1-47ee-81c9-0ed19296f85c.png)|![Screenshot_20220204_064249_com android vending](https://user-images.githubusercontent.com/64581222/152482284-4c45d0fe-2f42-4107-86b4-a9b9f842cf56.png)

**Comment by fm-sys** [comment]
> To sum up discussion above, I feel we should remove the behavior for lists but keep it for map.

Yes, exactly 👍
