### ISSUE TITLE
Variables: ignore space in formulas in general?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12610]
### Tell us your idea!

Recently I implemented a special formula behaviour for waypoint parsing in the WP Calculator: spaces in the decimal part of a digit are now ignored. E.g. the following is now a valid coordinate input:

`N48° 12.    3    A+1    5    '` (is interpreted as `N48°12.3A+15'`)

However, two things remain:
* spaces are just removed. So the above example is really interpreted as `3A+15` (for `A=2` this would be parsed to `32+15=47`), not as e.g. `3(A+1)5` (for `A=2` this would be parsed as `335`). Is this wanted behaviour or should it be changed? 
* Normal variable formulas (in the variable tab) are NOT removing spaces. E.g. entering there the expression 1   A+1   5 will lead to non-parseable. SHould space-removal be introduced there as well?

**Comment by ztNFny** [comment]
I can only think of 1 place where a relevant space is often used: As separator between D and M. While "°" is the correct char here many formulas just use a space instead. (Thinking about formula scanner / copy&paste from listing here)
Other than that I don't think it makes any difference.

**Comment by eddiemuc** [comment]
@ztNFny what about the other question?

Consider `N48° 12.1 A+2 3` with `A=2`. Should this either result in:
* `N48° 12.035` (1A+23 = 12+23 = 35, prepad with 0; this is the result given by GCBuddy)
* `N48° 12.143` (A+2 = 4, then concatenate 1, 4 and 3)

**Comment by ztNFny** [comment]
143

**Comment by fm-sys** [comment]
>  I don't think it makes any difference.
 
As you can see, a single space can make a huge difference ;-)

But yes, I would also vote for 143. Ore more general: 
Using a space is quite similar to a regular parentheses. Therefore `N48° 12.1 A+2 3` should be parsed as `N48° 12.(1)(A+2)(3)`

**Comment by eddiemuc** [comment]
Ok, I will give it a try

**Comment by fm-sys** [comment]
> Therefore `N48° 12.1 A+2 3` should be parsed as `N48° 12.(1)(A+2)(3)`

Just to mention another unit test case:
How should we handle the following? 
 `N48° 12.1 A + 2 3`

**Comment by eddiemuc** [comment]
This is tricky stuff to implement because it messes with current operator hierarchy in Formula. I want to be sure to implement the wanted thing before I invest more head-cracking though-work:

* `2+3 4+5` should be evaluated to 59 (2+3=5, 4+5=9, -> concat)
* `2+ 3 4+5` should be evaluated to 14 ( = 2 + 3 + 9)
* `2+ 3 4 +5` should be evaluated to 41 ( 2 + 34 + 5)
* `2+(3 4)+5` should be evaluated to 41 ( = 2 + 34 + 5)

All Correct?

**Comment by ztNFny** [comment]
> 2+ 3 4+5 should be evaluated to 14 ( = 2 + 3 + 9)

Missing a + in your formula??

**Comment by eddiemuc** [comment]
> > Therefore `N48° 12.1 A+2 3` should be parsed as `N48° 12.(1)(A+2)(3)`
> 
> Just to mention another unit test case: How should we handle the following? `N48° 12.1 A + 2 3`

Yes, this goes into same direction as the cases I just posted for clarification... If I would assume the interpretation I assumed there, then in your case (assuming A=5) this would evaluate to N48 12.038  (part after the decimal point would evaluate to 15+23, then prepadded with a zero due to other rules)

**Comment by ztNFny** [comment]
> 2+ 3 4 +5 should be evaluated to 41 ( 2 + 34 + 5)

I'd go for 2+3=5, 4+5=9 on this one.

**Comment by eddiemuc** [comment]
> > 2+ 3 4+5 should be evaluated to 14 ( = 2 + 3 + 9)
> 
> Missing a + in your formula??

No. Question I ask is: if someone enters a formula just as I entered it above, what should be the calculated result.

**Comment by eddiemuc** [comment]
> > 2+ 3 4 +5 should be evaluated to 41 ( 2 + 34 + 5)
> 
> I'd go for 2+3=5, 4+5=9 on this one.

What is the general parsing-rule (to be applicable to ALL formulas) on which this is based on?

**Comment by eddiemuc** [comment]
I forgot: here is the parsing rule which MY results are based on:
* blocks containing calculations without separating whiltespaces (e.g. `2+3`, but not `2 + 3`) will be considered "simple value blocks" 
* simple value blocks separated by whitespace are concattenated with each other

**Comment by ztNFny** [comment]
> No. Question I ask is: if someone enters a formula just as I entered it above, what should be the calculated result.

That's clear. But I can't figure out how you got from the input `2+ 3 4+5` to your suggested output `2 + 3 + 9`. I can see "2+3 4+5" -> 59 in there, but your version has a + more.

fwiw, imho if this (ignoring spaces) makes the formula stuff way more complicated (and thus hard to maintain and understand) it's fair to say that we don't do it - but then we need to make the user aware of this and point him the "cleanup" button.
Like could we move the "parsed formula" section to be right below the input, not below the variables? That way it's easy to compare input and parsed formula and notice discrepancies.

**Comment by eddiemuc** [comment]
> > No. Question I ask is: if someone enters a formula just as I entered it above, what should be the calculated result.
> 
> That's clear. But I can't figure out how you got from the input `2+ 3 4+5` to your suggested output `2 + 3 + 9`. I can see "2+3 4+5" -> 59 in there, but your version has a + more.

`2+ 3 4+5`: "4+5" is a "simple block" in this example and evaluates to 9. This is concattenated with the 3 before it, resulting in 39 and 4 are concattenated, resulting in 39. Then we have 2+39 = 31

> fwiw, imho if this (ignoring spaces) makes the formula stuff way more complicated (and thus hard to maintain and understand) it's fair to say that we don't do it - but then we need to make the user aware of this and point him the "cleanup" button. Like could we move the "parsed formula" section to be right below the input, not below the variables? That way it's easy to compare input and parsed formula and notice discrepancies.

The complication is already there in the degree part of formula anyway, this here just tries to put it on a more stable ground. Whitespace handling wanted by the user IS very challenging to get a good general rule from indeed. But once we find an easy rule we can all agree upon, then this should actually easify things compared to current state.

**Comment by eddiemuc** [comment]
I make another suggestion for a rule: forget the "simple block" stuff, user has to use parenthesis for this (inside of parenthesis is evaluated separately, not as part of a concat). E.g. "just remove the whitespaces" and interpret then. In this case, the results would look like this:
* `2+3 4+5` would evaluate to 41 (2+34+5)
* `2+ 3 4+5` whould also evaluate to 41
* `2+ 3 4 +5` would also evaluate to 41
* `2+(3 4)+5` would also evaluate to 41
* But `(2+3) (4+5)` would evaluate to 59

This would definitely make things easier to understand (and to implement :-))

**Comment by fm-sys** [comment]
> * `2+3 4+5` should be evaluated to 59 (2+3=5, 4+5=9, -> concat)

Yep. 
> 
> * `2+ 3 4+5` should be evaluated to 14 ( = 2 + 3 + 9)
> 
> * `2+ 3 4 +5` should be evaluated to 41 ( 2 + 34 + 5)

Actually I think a space should never ever occur between digits of a number. So in both cases we should IMHO concat here as well resulting to 59. This seems also like the most consistent implementation to me... 
> 
> * `2+(3 4)+5` should be evaluated to 41 ( = 2 + 34 + 5)

Correct. This one is pretty clear as well.

**Comment by ztNFny** [comment]
> `2+ 3 4+5`: "4+5" is a "simple block" in this example and evaluates to 9. This is concattenated with the 3 before it, resulting in 39 . Then we have 2+39 = 41

But above you said it should be 14 ;-) "should be evaluated to 14 ( = 2 + 3 + 9)"

**Comment by eddiemuc** [comment]
> > `2+ 3 4+5`: "4+5" is a "simple block" in this example and evaluates to 9. This is concattenated with the 3 before it, resulting in 39 . Then we have 2+39 = 41
> 
> But above you said it should be 14 ;-) "should be evaluated to 14 ( = 2 + 3 + 9)"

Whoops, I see that now. Sorry, my mistake

**Comment by ztNFny** [comment]
How about the rule
1. parse all calculation chars (+-*/), ignoring whitespace around them
2. remove whitespace
3. in case of brackets goto 1

"2+ 3 4 +5" -> "5 9" -> "59"
"2+ 3 4+5" ->  "5 9" -> "59"
"1 + 2 3" -> "3 3" -> "33"
"2+(3 4)+5" > "2+(34)+5" -> "41"

**Comment by moving-bits** [comment]
IMHO the last one comes closest to user-expectations 👍

**Comment by eddiemuc** [comment]
> How about the rule
> 
> 1. parse all calculation chars (+-*/), ignoring whitespace around them
> 2. remove whitespace
> 3. in case of brackets goto 1
> 
> "2+ 3 4 +5" -> "5 9" -> "59" "2+ 3 4+5" -> "5 9" -> "59" "1 + 2 3" -> "3 3" -> "33" "2+(3 4)+5" > "2+(34)+5" -> "41"
> 
> Like in regexp (example only using those simple operators): (\d)\s*([+-/_])\s_(\d)

Hm, I think this would be like parsing a Formula as a "sequence of Formulas" separated by whitespaces and concatenate their results. Current parser works from left-to-right, but I think the following should achieve the wanted result:
* Parse formula from left to right until valid formula ends. In this parse, do not allow whitespaces in concat blocks
* skip whitespaces, parse next formula. 
* Continue until end of expression
* Concatenate the results of all parsed "subformulas"
* (inside brackeds, do the same recursively)

Putting this onto example "2+ 3 4 +5":
* First parse would stop after 3 ("4" is not a valid continuation for a formula), resulting in "2+3"
* Second parse would stop at EOF, resulting in "4+5"
* => concatenated result would be 59

I think this could work. Is there agreement about the logic behind it?

**Comment by ztNFny** [comment]
On the topic of LTR formula parsing, please add `100 / 5 / 5 = 4` to the unit tests. Talking from hard felt experience that one may evaluate to 100

**Comment by eddiemuc** [comment]
> On the topic of LTR formula parsing, please add `100 / 5 / 5 = 4` to the unit tests. Talking from hard felt experience that one may evaluate to 100

will do

**Comment by eddiemuc** [comment]
> N48° 12.1 A + 2 3

With logic last discussed, this formula will (for `A=5`) evaluate to `N48° 12.173'`

**Comment by Lineflyer** [comment]
> With logic last discussed, this formula will (for `A=5`) evaluate to `N48° 12.173'`

Yes, thats probably the most used kind of "logic" out in the geocaching formular world. 
It looks OK to me as I assume, that I can still force another logic by using parenthesis?!

**Comment by eddiemuc** [comment]
> I assume, that I can still force another logic by using parenthesis?!

Yes, this is always possible and will stay this way.
