### ISSUE TITLE
AS Bumblebee | 2021.1.1

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12618]
### Tell us your idea!

The new AS Bumblebee | 2021.1.1 was released.
For news to the new release see https://developer.android.com/studio/releases#bumblebee .
There are many changes documented.

This release requires AGP 3.2 or higher. This is alredy ok.

Should we wait with upgrading until our next release?

**Comment by bekuno** [comment]
Android Studio Bumblebee | 2021.1.1 Patch 1 now available

**Comment by Lineflyer** [comment]
Will there be any change to the code required by that. I thought the version of Android Studio is not directly leading to consequences for the build (except the dependency to AGP 3.2 mentioned above).

**Comment by eddiemuc** [comment]
I am already using AS Bumblebee | 2021.1.1 for 1-2 weeks without any problems. Didn't try 2021.1.1 Patch 1 yet though.

**Comment by Lineflyer** [comment]
OK, just updated (incl. Patch 1). Seems to work normal.

@eddiemuc 
Any possibility to get back the old emulator look and feel?

**Comment by eddiemuc** [comment]
> OK, just updated (incl. Patch 1). Seems to work normal.
> 
> @eddiemuc Any possibility to get back the old emulator look and feel?

Yes, that's a very important thing to do.. DOn't know what they were thinking when they put the emulators into these tool windows.
In Settings | Tools | Emulator you have to uncheck the checkbox "Launch in a tool window"

![image](https://user-images.githubusercontent.com/6909759/152657679-9d157da4-0c26-442b-be15-340077709bdb.png)

**Comment by eddiemuc** [comment]
BTW: I just installed the Patch 1 too and so far it is working fine.

**Comment by bekuno** [comment]
@Lineflyer 
see https://developer.android.com/studio/releases#embedded-emulator

**Comment by fm-sys** [comment]
> > Any possibility to get back the old emulator look and feel?
> 
> Yes, that's a very important thing to do.. DOn't know what they were thinking when they put the emulators into these tool windows.

Actually I like the new look better than the old one :)

**Comment by bekuno** [comment]
The release is out - then lets go.
