### ISSUE TITLE
"Insert function" dialog sort of messed-up

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12636]
### Describe your problem!

The "insert function" dialog on the new variables tab is sort of messed-up - some group titles are used as regular entries and vice versa:

![image](https://user-images.githubusercontent.com/3754370/151679273-0f746078-b644-4d15-8e93-1e976a1f61d4.png).![image](https://user-images.githubusercontent.com/3754370/151679287-6e5f0ace-c35b-4cb6-8ea1-bdaa77b32b4a.png)

### How to reproduce?

go to cache list - open a cache - swipe to variables tab - press "insert function" button

### Actual result after these steps?

see screenshots above

### Expected result after these steps?

There should be for groups with their respective functions:
- Simple Numeric
- Complex Numeric
- Simple String
- Complex String

### Reproducible

Yes

### c:geo Version

current master

**Comment by eddiemuc** [comment]
Damn! This happens because RecyclerView (which is used by AlertDialog under the hood) reuses views when the user scrolls (list item views going out-of-sight are reused to create the view for new items shown).
