### ISSUE TITLE
Automated backup check - improvements

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12631]
### Describe your problem!

I just saw the automated backup check for the first time.

So I just hit the "check" button, but nothing happened. I did wait some time, pressed it again - nothing! After closing and reopening the app, it still didn't work, and I haven't found any way to get it triggered. 

### How to reproduce?

- open "view settings"
- set `automaticBackupLastCheck` to a low number but higher than 0. (e.g. 1)
- close cgeo
- notification is displayed but doesn't work

### Reproducible

Yes

### c:geo Version

2022.01.29-NB-071456a

### Additional Information

Furthermore, a visual bug: IMHO the action button should be vertically centered

![Screenshot_20220129_132745_cgeo geocaching](https://user-images.githubusercontent.com/64581222/151661575-e29714fc-d072-404c-b381-c9130681623c.png)

**Comment by moving-bits** [comment]
As a temporary workaround: You can tap the message instead of the checkmark button to start the backup.
I'll look into activating the button again.

Or do we need the button at all?
We could rephrase the message a bit (e. g. "Tap here to create...") and could remove the button. Would be an even cleaner solution, IMHO. What do you think?

**Comment by Lineflyer** [comment]
> Or do we need the button at all?
We could rephrase the message a bit (e. g. "Tap here to create...") and could remove the button. Would be an even cleaner solution, IMHO. What do you think?

That would be inline with all other messages appearing there and thus IMHO much better.

**Comment by moving-bits** [comment]
PR #12632 fixes this and a couple of other issues with the three dashboard reminders for auto backup / map updates / routing tile updates
