### ISSUE TITLE
Switch list from Map view

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12644]
### Tell us your idea!

When in stored lists at the top the list name is shown as a dropdown where other lists can be selected. When you then display that list on a map
![image](https://user-images.githubusercontent.com/1258173/151712887-d7020410-36e7-43f4-881f-9c2edddcd2f4.png)

the header turns into a simple text without the dropdown
![image](https://user-images.githubusercontent.com/1258173/151712903-0160e176-27b3-4cfe-a20b-e9b1da262e1b.png)

To select a different list one has to go back to lists, select the list, then map it again.

It'd be nice to be able to switch the selected list straight from the map. The expected result is the same as with going back to lists, only the new lists caches are shown.

**Comment by ztNFny** [comment]
@fm-sys could you take a look at this? looked into adapting the code from lists, but it's relying on a list stuff, so not so easy to transfer to the map.

**Comment by fm-sys** [comment]
I fear this isn't easily possible without much refactoring.

And IMHO as long as the map is launched as sub-activity from the offline lists (without bottom nav ;-)), this doesn't really bring much additional value anyway... You can just go back and select a different list.

**Comment by ztNFny** [comment]
> You can just go back and select a different list.

That's the point, to switch list from map takes those additional (annoying) clicks to switch back and forth to list

**Comment by moving-bits** [comment]
implemented meanwhile (in nightlies / beta), so let's close here
