### ISSUE TITLE
Wrong „finds“ log count / Favorites percentage displayed > 100%

### ISSUE THREAD

**Issue by dl1ely** [cgeo/cgeo#12676]
Display for GC9MTBF in c:geo 5/4=125%
![Screenshot_20220205-112803](https://user-images.githubusercontent.com/427752/152638587-f31a0e67-514f-46ae-917c-56323edd44ac.jpg)

Same cache on website 5/6=83%
![Screenshot_20220205-113320](https://user-images.githubusercontent.com/427752/152638641-86bb7c3e-e132-48d3-b7c3-247d3f1cc3e2.jpg)

No idea where why c:geo thinks there are only 4 finds on this cache, the cache details are updated and c:geo shows all the 6 finds.

**Comment by dl1ely** [comment]
Just noticed: „logs“ page shows 4 finds in the header, although all 6 of them are displayed when scrolling down:
![Screenshot_20220205-114027](https://user-images.githubusercontent.com/427752/152638811-0d339dd4-7b68-43d1-98ec-d5dac756af34.jpg)

Hypothesis: Numerical log count is not correctly updated when updating cache details and new logs got added to the cache (?).

**Comment by Lineflyer** [comment]
Unfortunately you don't write what version you are using.
IMHO this could be a manifestation of: https://github.com/cgeo/cgeo/issues/12667

**Comment by Lineflyer** [comment]
See also: https://www.cgeo.org/faq#log_summary

**Comment by dl1ely** [comment]
Sorry, 2021.12.24

**Comment by dl1ely** [comment]
Not sure this is #12667 - GC9MTBF is saved in a list and i refreshed the cache details.

**Comment by Lineflyer** [comment]
Then it is caused by the interworking of a current website change and some limitations/issues in c:geo:
- Currently the log count is not (correctly) updated from the server -> That is what is behind #12667
- c:geo does not show the value of the website anyhow as we currently calculate our own value rather than using the value from the website

**Comment by dl1ely** [comment]
Ah, i get it: The GC website change happened after me saving GC9MTBF, that's why the log count does not update anymore.

So it's a duplicate, sorry.
