### ISSUE TITLE
cgeo-1 is offline

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12674]
### Describe your problem!

the executor loses the connection (java.nio.channels.ClosedChannelException)

@mucek4 Please check and restart them.

### How to reproduce?

see CI

### Reproducible

Yes

### c:geo Version

-

**Comment by Lineflyer** [comment]
Seems to be running right now?

**Comment by bekuno** [comment]
> Seems to be running right now?

Yes, looks good.
Either someone restarted the executor or an automatic restart after I took them yesterday offline and online.
