### ISSUE TITLE
Add "recently viewed caches" PopUp to Bottom-nav (longClick) 

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#12687]
### Tell us your idea!

While doing a round of caches with for instance a bonus cache I am storing the gathered bonus information from the other caches directly inside the note section of the bonus cache.

Right now I have to scroll back to the bonus icon on the map, therefore I have to remember where the icon is stored, open the listing, go to desired cache section, click edit, etc pp

Afterwards I have to jump back to my current location, select the next target on the round, resulting in an endless loop of repeating the above.

### What solution would you suggest?

My current idea was to add a long-press function to the Map (Live-Map) button which is showing for instance the last 5 visited caches, so you could easily jump into these caches detailed information.
Maybe it is also possible to remember which tab and area inside these historical caches was viewed before.

In general this function might improve the usage of the Map, when you for instance want to compare two different caches to decide which one will be your next target.

Maybe another solution is to add a new button inside the bottom navigation which is stating a list of all formerly visited caches (e.g. like the history shown in the search but much longer 100 entries maybe?) and adding here as well the above described long-press function to directly access the last 5 viewed caches. 

### Is there an alternative?

yes, but not user friendly, see above...

**Comment by ztNFny** [comment]
How about long-click on "Home" to show the same list of caches that clicking the search field shows?

**Comment by fm-sys** [comment]
> How about long-click on "Home" to show the same list of caches that clicking the search field shows?

Like the idea 👍 (have already thought about that as well, as "Home" does IMHO make more sense than using "Live-Map" for it.) 



I would be willing to work on this feature request. `release` or `master`?

**Comment by ztNFny** [comment]
Master i'd say. Not important and with the website changes going on release should stay close to releaseable imho.

**Comment by SammysHP** [comment]
Instead of opening a (newly introduced) popup, can we jump to the quick search which automatically opens a list of recent caches and additionally allows you to perform a search? If yes, would it make sense to add this to the search icon?

**Comment by ztNFny** [comment]
> Instead of opening a (newly introduced) popup, can we jump to the quick search which automatically opens a list of recent caches and additionally allows you to perform a search?

That'd leave the current activity though and add Home to the activity stack. Going back from the cache then wouldn't return to e.g. the map where you were before.

**Comment by SammysHP** [comment]
We could introduce a new transparent "quick search" activity that is started with FLAG_ACTIVITY_NO_HISTORY or simply start the home activity with that flag.

**Comment by fm-sys** [comment]
> can we jump to the quick search which automatically opens a list of recent caches and additionally allows you to perform a search? If yes, would it make sense to add this to the search icon?

That's exactly what is suggested in  #11897. However, a search IMHO doesn't feel really fit for this feature request. Last but not least, the search results appear at the top of the screen, which is impossible to reach when using the mobile with one hand. A dialog is way easier to reach, and consistent to our "select list" shortcut in the bottom navigation.

**Comment by andrcoding** [comment]
Doesn't it make sense to connect this to the new variable calculator as well?
 
Ex: I want to enter a variable/description at the current cache for a bonus cache. To do this, I open a submenu and then select the bonus cache or a temporary group and enter the value accordingly. Thus I would have a small list of possible groups that I am currently working on. Initially, a group would have to be created for variables and descriptions, which is assigned to the bonus cache. The bonus cache could then get the information directly from the group or the group writes directly to the bonus cache. A switch via the map is then no longer necessary.

**Comment by SammysHP** [comment]
> Last but not least, the search results appear at the top of the screen, which is impossible to reach when using the mobile with one hand.

Depends on the screen size (and is one of the reasons I prefer smaller screens). ;) But reaching the first item in a popup menu and the first item on the history quick selection shouldn't be that much different.

**Comment by wolverine007** [comment]
@fm-sys First of all thanks for directly taking over and working on my request :)

> > Like the idea 👍 (have already thought about that as well, as "Home" does IMHO make more sense than using "Live-Map" for it.)

But why the Home Button, when I am mainly using the map while being in the wild?
When Map might be the wrong button, what about **Search**? Cause I wanna **search** inside a list of formerly viewed caches?

> > A dialog is way easier to reach, and consistent to our "select list" shortcut in the bottom navigation.

That was my intention behind the idea, use more or less the same function like for accessing the stored lists.

> > But reaching the first item in a popup menu and the first item on the history quick selection shouldn't be that much different.

If the pop-up is only taking a pre-defined size (x% of the max-screensize) and the list is than scrollable you should be able to reach even the top of it with one finger and all other stored ones by scrolling through the list as well ;)

**Comment by fm-sys** [comment]
> But why the Home Button... 

I would suggest to use home, as this is the place where you can currently access the "recently viewed caches" as well.

>...when I am mainly using the map while being in the wild?

This is very user specific. We have learned in the past, that 10 users will use cgeo in 20 totally different ways :)

> what about Search?

This might be blocked for  #11897. Furthermore, the dialog will only allow a quick selection, no real searching. I'm sure, you will get used to it... ;-)

**Comment by Lineflyer** [comment]
> But why the Home Button, when I am mainly using the map while being in the wild?
> When Map might be the wrong button, what about **Search**? Cause I wanna **search** inside a list of formerly viewed caches?

That's a valid point.
Maybe search is really the right item for that and we keep long press Home reserved for potential future use e.g for something related to the user profile (e.g. other requests like tb inventory or whatever).



> This might be blocked for #11897. Furthermore, the dialog will only allow a quick selection, no real searching. I'm sure, you will get used to it... ;-)

But #11897 is a request for a very similar thing IMHO, so if we find a good UI it could be combined as it is combined right now on the "magnifier icon".

**Comment by fm-sys** [comment]
IMHO it's quite inconsistent if you can long-click SEARCH or short-click Home to reach the very same feature.

> keep long press Home reserved for potential future use

I don't think there are really features missing which needs to be accessed that frequently, that a long-click shortcut is necessary. Things like TB inventory are maybe nice to have, but IMHO not important enough to be accessible from all bottom navigation activities...

**Comment by SammysHP** [comment]
> IMHO it's quite inconsistent if you can long-click SEARCH or short-click HOME to reach the very same feature.

But from home you have to click SEARCH to get to the history.

**Comment by fm-sys** [comment]
> But from home you have to click SEARCH to get to the history.

But not the SEARCH in the bottom navigation, but in the actionbar of HOME

What about the following:
Add the very same longClick feature to both bottom navigation items, until we have a better idea for the other one (whatever that will be).

**Comment by Lineflyer** [comment]
> Add the very same longClick feature to both bottom navigation items, until we have a better idea for the other one (whatever that will be).

Long click is un-intuitive enough already...the same function on two items is probably a bit strange IMHO.
Additionally its not wise to change a fucntionality after is has been implemented.

We should not assign that function by looking at the pure history, that this quick search used to be on home/main screen before, but rather think of where it really belongs (in future).

**Comment by ztNFny** [comment]
Should we try the smiley vote?

Thumbs up = Home
Thumbs down = Search
Smiley = Both
Party thingy = Neither

My vote goes to home as it's not a search - search is when I enter a search term - but a history and the only place that's accessible is home.

**Comment by Lineflyer** [comment]
> Thumbs up = Home
Thumbs down = Search

Somehow this vote system seems not neutral....just kidding. Its helpful 👍🏼

**Comment by MagpieFourtyTwo** [comment]
Voted with ``thumbs down`` cause the current strategy (Search and View History in one box) is already used in the ``Home`` screen, thus very well known by the users.  Moreover a history is in fact nothing else but the result of a search, although you're not searching for a pattern but a timestamp.  BTW: The very same strategy is already implemented in other apps, like e. g. in Firefox's search box: Just click in it and hit cursor down - and you get the history ...  ;)

As for ``Home``: Would be great if the magnifier over there would have the very same functionality (in fact, keep it), but if I would have to decide, I would clearly favor the ``Search``. Cause it's kind of obvious. And, BTW: I already voted for a "long-press-search with view history" in a former issue, anyway.  ;)

**Comment by fm-sys** [comment]
Ok, 4:2 for search.... I will adapt https://github.com/cgeo/cgeo/pull/12692

**Comment by wolverine007** [comment]
> Ok, 4:2 for search.... I will adapt https://github.com/cgeo/cgeo/pull/12692

@fm-sys 

Just downloaded the latest nightly and working like wished before 🤩

Thanks for directly picking up this request and implementing it 😎
