### ISSUE TITLE
Menu entry "Clear manual targets" is missing

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#12701]
### Describe your problem!

Ok, admittedly, it's not completely missing, but hard to find sometimes. ;)

### How to reproduce?

1. open any cache listing and route to the cache, e. g. by clicking the compass rose in the header
2. when in the cache's map, ``Enabled live``
3. now try to get rid of the route ...

### Actual result after these steps?

As there is no ``Clear manual targets`` in the menu anymore (IIRC it was there a while ago),
*and* there is no bottom menu for routes (as there is no manual route right now),
you first have to click ``Routes / Tracks``, then the bottom route menu pops up,
and finally you will find the ``Clear manual targets`` button.

### Expected result after these steps?

Either the bottom route menu button should be active as soon as there is *any* route active
*or* the ``Clear manual targets`` should be there as soon as there is a manual target active ...

### Reproducible

Yes

### c:geo Version

2022.02.07-NB-a93e0da

### Additional Information

I would call myself an experienced user, but even me had a hard time to find a way to get rid of the manual target
and I would assume that "normal" users will just get frustrated ...

**Comment by moving-bits** [comment]
We could add it to the menu as an temporary mitigation to be able to release, and add some magic later on.

**Comment by MagpieFourtyTwo** [comment]
Great - thx!

Nevertheless, I still find it kind of inconsistent to have some routing stuff in the Quick settings (esp. talking of routing style) and others in the routing bottom menu. IMHO all of this should go to the routing bottom menu, which should be displayed (resp, the symbol should be active) as soon as a (read: any!) route (or track) is active - and then even the ``Clear manual targets`` will not need a "special magic" anymore.  ;)

**Comment by moving-bits** [comment]
I've added enabling the "routes/tracks" quick button when a navigation target is set, see #12709.
