### ISSUE TITLE
[Variables] Buttons are cut off 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12718]
### Describe your problem!

A picture tells more than thousand words :) 

![Screenshot_20220212_101712_cgeo geocaching](https://user-images.githubusercontent.com/64581222/153705475-9f69e7cc-22e1-4935-8402-e7c3a5645b27.png)

### How to reproduce?

Use a small screen or large font size... 

### Actual result after these steps?

Buttons are cut off. 

### Expected result after these steps?

The buttons should be ordered dynamically. This can easily be done with a AndroidX `CoordinatorLayout`. 

### Reproducible

Yes

### c:geo Version

NB2022.02.12

**Comment by eddiemuc** [comment]
`CoordinatorLayout` seems a bit overpower for this. Maybe a `ChipGroup` layout is enough here.

**Comment by eddiemuc** [comment]
Using ChipGroup it looks like this:

![image](https://user-images.githubusercontent.com/6909759/153708600-031ec62e-7196-4bf8-8454-551aed82f0ca.png)

PR will follow

Also, might be good to make translations a bit shorter

**Comment by eddiemuc** [comment]
Related to this topic: it would be very easy to change the number of columns in landscape, e.g. something like this:

![image](https://user-images.githubusercontent.com/6909759/153724614-ad49fed1-a186-44cc-8d76-519e9728eb06.png)

Or this:

![image](https://user-images.githubusercontent.com/6909759/153724693-9a2ef1c2-2c40-461b-aeb5-2cf5bb37e238.png)

Only if this is wanted of course.

**Comment by eddiemuc** [comment]
> > Only if this is wanted of course.
> 
> Pro: More compact view Con: On smaller screens or on longer formulas users might want to use landscape to have the maximum overview for each variable (=single variable per row).
> 
> I would personally stay with the current layout....but I did not use it extensively yet to finally judge whats better.

Nothing which needs to be decided right now

**Comment by fm-sys** [comment]
> Related to this topic: it would be very easy to change the number of columns in landscape

I feature which I would need more: The possibility to show two cache details pages at the same time. It can be really annoying if you have to always swipe between the listing and variables tab... 😅

**Comment by eddiemuc** [comment]
> feature which I would need more: The possibility to show two cache details pages at the same time. It can be really annoying if you have to always swipe between the listing and variables tab... 

Understandable.

Would it help if the personal notes would be available on the variable tab too? So you can use it for copy/pasting?

(The existing calculated coordinates put in the waypoint notes into the calculator dialog for exactly this reason - so you have something to use as a temporary text place for copy/pasting without changing activity all the time)

**Comment by fm-sys** [comment]
> Would it help if the personal notes would be available on the variable tab too? So you can use it for copy/pasting?

Yes sounds like a good idea. 

BTW, I just noticed  that we already have a "Personal note" shortcut in the actionbar overflow menu. Instead of blocking the whole screen with a dialog, we could use a so called "Standart bottom sheet". 

Material.io defines 3 different bottom sheet types:
> -    Standard bottom sheets display content that complements the screen’s primary content. They remain visible while users interact with the primary content.
> -    Modal bottom sheets are an alternative to inline menus or simple dialogs on mobile and provide room for additional items, longer descriptions, and iconography. They must be dismissed in order to interact with the underlying content.
> -    Expanding bottom sheets provide a small, collapsed surface that can be expanded by the user to access a key feature or task. They offer the persistent access of a standard sheet with the space and focus of a modal sheet.
> 
>

**Comment by fm-sys** [comment]
Let's continue this discussion in  #12729
