### ISSUE TITLE
Mildly irritating change to popup/selection behaviour

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#12710]
### Describe your problem!

I've just been out today for the first time with the new release, there's an irritating change to the way selections in popups work.

E.g. when changing a log entry from 'Found' to 'DNF', you tap on 'Didn't find it' and nothing happens.
You also have to tap on 'OK' to make the change.

I'm sure this used to happen with just one tap.
Same applies to dropping a TB, you have to tap 'Dropped off', then 'OK'.

A minor irritation, I know, but the previous system was better.

### How to reproduce?

1. Open a cache and start to write a log.
2. Tap on 'Found it'
3. Tap on 'Write note'

### Actual result after these steps?

You now have to also tap on 'OK' to make the change.

### Expected result after these steps?

Change should take effect immediately, no 'OK' needed.

### Reproducible

Yes

### c:geo Version

2022.01.22-RC

### Additional Information

I've seen this when selecting log-type and dropping a TB.
I suspect it happens elsewhere as well.

**Comment by fm-sys** [comment]
Totally agree, one additional click for nothing. The is definitely an unwanted regression and should be fixed.

![GIF-220210_160303](https://user-images.githubusercontent.com/64581222/153435028-cb90196a-5b7a-4f92-8e09-2976ff5e83aa.gif)

**Comment by eddiemuc** [comment]
Hold on, I just remember that the log type dropdown had the unique visual look that it actually showed the select radio buttons but nevertheless immediately chose the clicked selection. This is tricker to achieve again

**Comment by eddiemuc** [comment]
> @eddiemuc : will this also fix the same issue when selecting 'Dropped off' or 'Visited' in the TB inventory?

Yes, now it will

**Comment by eddiemuc** [comment]
> It was "always" like this, don't know why myself. I preserved this look when I created TextSpinner. The bug of this issue was introduced by me when I moved `TextSpinner`'s Dialog creation to `SimpleDialog` recently.

Thinking again: I always assumed the radio button was shown in log type to show in the dialog list which value was selected previously. The reworked PR keeps this behaviour
