### ISSUE TITLE
support Android 13 dynamic icon theming

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12728]
### Tell us your idea!

https://developer.android.com/about/versions/13/features#themed-app-icon-specs

Basically this requires is to add a new, monochrome vector drawable that can be used by the launcher for dynamic theming.

**Comment by flexagoon** [comment]
Themed icon support would be great.

**Comment by ztNFny** [comment]
WIP in https://github.com/ztNFny/cgeo/tree/issue/12728_adaptive_icon

**Comment by bekuno** [comment]
fixed by #13821 ?
