### ISSUE TITLE
decide on icon for generated waypoints

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12735]
I'll look into that direction, and propose to merge this PR after the "waypoint type selector" thing is added, to be able to build upon this functionality in upcoming PR.

Discussion about a different icon, and which (if requested) should be part of a separate issue.

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/12693#issuecomment-1037423790_

The icon represents "the result of a formula with some variable(s) guessed". To me this offers the following keywords an icon could be selected from:
- result
- formula
- variable
- guess

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/12693#issuecomment-1036590957_

**Comment by Lineflyer** [comment]
From our devs meeting last Sunday there was kind of an agreement on an icon like this (as proposed by @ztNFny ): `[x]`

**Comment by moving-bits** [comment]
> > Maybe something like "[1-3]" would fit for those (using square brackets and a range of numbers)?
> 
> Maybe it would also be enough to just use square brackets instead of normal ones...? `[x]`

still think it's too close with the symbol for "has formula":

![image](https://user-images.githubusercontent.com/3754370/153656647-38f01408-a097-43be-adc8-1a0c64d30ffd.png)

In this screenshot, only the last two waypoints do have a formula, whereas all waypoints above are generated (and have fixed coordinates, no formula). When using "[x]" as symbol for a waypoint this would look pretty confusing, IMHO, as the generated waypoints would have "[x]" as icon symbol, and the last two waypoints would have a "(x)" as symbol directly beneath the icon.

I would go for something more distinct.

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/12693#issuecomment-1036544338_

**Comment by moving-bits** [comment]
But "has formula" and "generated" are closely related. You can only generate from a formula, so having that icon seems like an obvious choice to me.
Also the (x) icon indicates "variable", which is what the waypoint represents, the result of "testing" a variable.

The other idea I had was something like a joker in a card game but couldn't come up with a simple enough icon for that.

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/12693#issuecomment-1036548247_

**Comment by moving-bits** [comment]
What about something abstract, e.g. a star?

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/12693#issuecomment-1036555933_

**Comment by moving-bits** [comment]
> [?]

I like this one most. At least it seem to be the most logical one... :)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/12693#issuecomment-1036610070_

**Comment by moving-bits** [comment]
> > > [?]
> > 
> > 
> > I like this one most. At least it seem to be the most logical one... :)
> 
> Similar to mystery though?

We would have a white background with colored symbol (inverted colors compared to mystery caches), and we have added brackets, so they should be distinguishable enough.

Alternatively we still have the first two proposals in https://github.com/cgeo/cgeo/issues/12626#issuecomment-1030677669

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/12693#issuecomment-1036619844_

**Comment by Lineflyer** [comment]
> In this screenshot, only the last two waypoints do have a formula, whereas all waypoints above are generated (and have fixed coordinates, no formula). When using "[x]" as symbol for a waypoint this would look pretty confusing, IMHO, as the generated waypoints would have "[x]" as icon symbol, and the last two waypoints would have a "(x)" as symbol directly beneath the icon.
>
> I would go for something more distinct.

Why..
In fact using a similar [x] makes clear that it is something calculated and the [ ] indicate its resulting from a range.

**Comment by moving-bits** [comment]
> Why.. In fact using a similar [x] makes clear that it is something calculated and the [ ] indicate its resulting from a range.

A (crude) mockup taking the screenshot above and the proposed symbol would create something like this:

![image](https://user-images.githubusercontent.com/3754370/154770546-0015d5f9-144c-4f64-9475-fee8bf37697e.png)

Personally I still find it confusing to have `[x]` in the symbol for some waypoints, and `(x)` below the symbol for others. Technically I can explain where this comes from, but the "average user" probably can't. IMHO that's too close to each other for meaning something that different. But maybe it's just me feeling that way.

**Comment by bekuno** [comment]
The mockup looks good and is clearly understandable.
The generated waypoints are intentional by the user and the description for generated and calculated waypoints shows the different sources.
