### ISSUE TITLE
Missing coordinate input for Geokrety logging

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12741]
### Describe your problem!

While working on the users manual I stumbled upon a seemingly missing field, not sure though under which conditions it is shown.

For logging a "Discover" of a GeoKret there used to be the possibility to enter a geocode **OR** enter coordinates to be sent with the trackable log.

The button is defined here:
https://github.com/cgeo/cgeo/blob/30a6ea22ed72eb4cd7781d2365b1cbeb121d97a6/main/res/layout/logtrackable_activity.xml#L65-L69

However I was unable to enforce it being shown when I expected it.

### How to reproduce?

- Search for trackable GKC240
- Start logging this trackable
- Set log type to "Discovered"

### Actual result after these steps?

Text field "Geocode" is shown, but button "Coordinates is missing"

### Expected result after these steps?

Button "coordinates" should show up right of "Geocode", here is an older example screenshot:
![](https://manual.cgeo.org/_media/en/loggingtb_dropoff_gk.png?w=300&tok=ed04ee)

### Reproducible

Yes

### c:geo Version

2022.02.13

### System information

```text
Android 12, Google Pixel 3a
```

**Comment by eddiemuc** [comment]
Layout made the geocode field take the whole width, pushing out the coordinate button to the right side. Old layout restored with #12743
