### ISSUE TITLE
Waypoint map is centered on cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12749]
### Describe your problem!

Reported by users for 2022.02.13 (not sure if it happend on older versions) and also reproducible on nightly.

If you use GMaps and open the map for a waypoint, the map is centered on cache coordinates instead of the selected waypoints coordinates. 
Working normal on OSM.

### How to reproduce?

- Set active map to GMaps
- Open cache details of GC9FC41
- Go to waypoint tab
- Long tap compass icon (=open map) for waypoint K (doesn't matter which one, but K is well far away from listing coords)

### Actual result after these steps?

Map is opened, waypoint has target line and is shown but the map is centered on the cache listing coordinate (and the waypoint is out of the viewport (depending on zoom).

### Expected result after these steps?

Map should center on mapped waypoint

### Reproducible

Yes

### c:geo Version

2022.02.13

### System information

```text
Android 12, Samsung S20
```

**Comment by eddiemuc** [comment]
Fixed with PR #12836
