### ISSUE TITLE
Still/Again picture upload issue

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12767]
### Describe your problem!

I am out on a business trip at the moment.
However while quickly scanning support mail, there are a few users reporting that with 2022.02.13 and 2022.02.16 they have problems uploading log images.

Symptoms seems to be similar to what we already fixed:
- c:geo reports error but upload is good (only title missing)
- Uploading more than one photo fails completely

Can someone doublecheck?

### How to reproduce?

see above..sorry, written from mobile device

### Reproducible

Unclear

### c:geo Version

2022.02.16

**Comment by Lineflyer** [comment]
No, its not reproducible. Just tried with current release 2022.02.16 and had no problem to upload 3 pictures.

I asked the users whether it might have been an earlier version, where they had the problem and (not sure if it helps) asked them to actively relogin and try again.

**Comment by eddiemuc** [comment]
I created PR #12776 which tries to cherry-pick the recent HTTP interface refactoring from master into release. This is the first time I try something like this (PR for a cherry-pick from another branch) so let's see whether this works. 

In case it works: merging this PR will make HTTP calls for log images in release identical to master. It seems to work in master, so maybe it fixes the (yet unknown) problems in release too?

**Comment by Lineflyer** [comment]
First it would be good to have it reproducible, but all works for me with `release`...

**Comment by Lineflyer** [comment]
There have been 4-5 such reports up to now.
I advised all users to relogin and try again.

One user provided feedback that its working now, others did not reply yet.
Lets wait a bit.

**Comment by Lineflyer** [comment]
No further reports. Lets close here for now.
