### ISSUE TITLE
Bugfix version name in changelog_bugfix is not ideal

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12763]
Just stumbled upon a problem for bugfix releases changelog handling:

Currently its required to add the version code to `changelog_bugfix.md`.
As this normally happens immediately before generating the release, there is no chance, that this version code comes into the localized versions.

The means, that e.g. on german it now shows "Nächste Version" instead of "2022.02.16".

For the first of a series of bugfix releases this could be mitigated by moving this string out of the file into some other ressource. However for consecutive bugfix releases its not that easy.

@moving-bits 
Any idea without making it even more complex to use?

**Comment by moving-bits** [comment]
For any upcoming release this should not be a problem, if the text "2022.xx.xx Bugfix Release" is ok for all languages - you just enter this text (with `###`) at the top of `changelog_bugfix.md` and wait for Crowdin recognizing this change, and transporting the (untranslated) texts into all language files.

If we do not want to have to wait for Crowdin to recognize the change and/or do not want to present this text to our translators, the I could think of a different system, where we put "Bugfix Release" into our regular strings to be translated, and add a mechanism where you can enter the current bugfix's version number into `BranchDetectionHelper.java`, as we do for the feature release's version number.

For follow-up bugfix releases, we put the outdated version code into `changelog_bugfix.md` at the time when adding the first next changelog info. The c:geo automatically adds the "Next version" header. When releasing such a follow-up bugfix release we proceed as described above.

Which way shall we pursue? Leave as is (having to wait for Crowdin to recognize the added string), or add a mechanism to `BranchDetectionHelper.java`?

**Comment by Lineflyer** [comment]
I would prefer a solution which does not involve Crowdin for two reasons:
- Not having to wait for incoming translations (by default it can take 24 hours or need manual push)
- Translators might still (accidentally) submit something different later on

For subsequent bugfix releases we might still store it in the file. 
Whatever solution it might be, it should IMHO not get more complex as it already is.

**Comment by Lineflyer** [comment]
After chatting with @moving-bits I guess its still the most straight-forward solution to just wait for incoming translations (and trigger the PR submission from Crowdin manually if needed).

All other scenarios will logically add more complexity. 
A good idea from @moving-bits was, to create a checklist (or add it to the existing check-list for releases) with all needed steps. This would probably have avoided, that I did not see the consequence of not waiting for translations. I thought it would create an empty header in the changelog but it used "Next version" in all non-English changelogs instead.

**Comment by moving-bits** [comment]
@Lineflyer 
I had updated our wiki page for [Changelog handling](https://github.com/cgeo/cgeo/wiki/Changelog-handling) this morning. Would it be helpful for you in this way, or shall I update/add/restructure anything else?

**Comment by moving-bits** [comment]
Checklist is created, therefore closing here. Feel free to reopen if something's still missing or not working as expected.
