### ISSUE TITLE
Variables Input: show abbrevation for functions on function selection dialog

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#12769]
### Tell us your idea!

While entering the formula for a variable, I need sometimes concatenated functions (e.g. checksum of lettervalue).
On selecting the second function the first one will be replaced.

### What solution would you suggest?

Insert the selected function at cursor position

**Comment by eddiemuc** [comment]
The intention behind the formula insert function was meant for "novice" users who don't like to deal too much with formulas, and as a same time to quickly look up available functions. I always assumed that more advanced users (and only those would use more than one function in a var expression) would just type along.

I also provided abbreviations for most functionsnto ease typing e.g. wv, lv or bww can be used instead of lettervalue, and cs can be used instead of checksum

**Comment by murggel** [comment]
> I also provided abbreviations for most functionsnto ease typing e.g. wv, lv or bww can be used instead of lettervalue, and cs can be used instead of checksum

Ok, that's fine.
Can we add those abbreviations behind the name of the function for a quick lookup then?

**Comment by eddiemuc** [comment]
> > I also provided abbreviations for most functionsnto ease typing e.g. wv, lv or bww can be used instead of lettervalue, and cs can be used instead of checksum
> 
> Ok, that's fine. Can we add those abbreviations behind the name of the function for a quick lookup then?

Well there **IS** a big "Help" button on the page leading to complete documentation including available functions and usable abbrevations...

![image](https://user-images.githubusercontent.com/6909759/154804273-ead24ca1-bd18-41ed-8049-468c19cec576.png)

![image](https://user-images.githubusercontent.com/6909759/154804491-52d57fdc-9b3b-42b9-b379-2bb8f55cdd39.png)


Adding it to the list will make it less readable, would be look something like this:

![image](https://user-images.githubusercontent.com/6909759/154804435-641a7f79-42d7-4dce-8d46-b0d0f2e49f18.png)

Implementing this would be a one-liner, just change method VariableListView.getFunctionDisplayString to whatever should be displayed. You may use Markdown or HTML if you want (since this is a TextParam). Feel free to try out a few things.

E.g. like this:

![image](https://user-images.githubusercontent.com/6909759/154804500-51ee6179-8fff-4b93-9cc4-dfd8108bc8f0.png)

**Comment by murggel** [comment]
For me it would only need the abbreviations, not the "long" word.
But probably it is really only learning the few abbreviations for lettervalue, checksum and vanity code...

**Comment by eddiemuc** [comment]
> For me there would only be the need of abbreviations, not the "long" word.
> But probably it is really only learning the few abbreviations for lettervalue, checksum and vanity code...
> 

There's no differentiation codewise between "abbreviations" and "long-names", just different function names for the same function (one of them being the "main name"). How should "abbreviations" be identified? Anything with less than 4 chars?

**Comment by ztNFny** [comment]
I think murggels original suggestion makes a lot of sense here.
What functionality would brake by doing "insert" instead of "replace"?

**Comment by murggel** [comment]
> The intention behind the formula insert function was meant for "novice" users who don't like to deal too much with formulas, and as a same time to quickly look up available functions. I always assumed that more advanced users (and only those would use more than one function in a var expression) would just type along.


I guess it depends not on the user how many functions are used, but on the formula in the listing.
So even novice users probably want to use concatenatede functions instead of introducing a new variable.

**Comment by murggel** [comment]
> There's no differentiation codewise between "abbreviations" and "long-names", just different function names for the same function (one of them being the "main name"). How should "abbreviations" be identified? Anything with less than 4 chars?

Or where there are more than one names, and then take the shortest one.

**Comment by murggel** [comment]
> I think murggels original suggestion makes a lot of sense here.
> What functionality would brake by doing "insert" instead of "replace"?

I would like both, replace AND abbreviations 😀

**Comment by eddiemuc** [comment]
> > I think murggels original suggestion makes a lot of sense here.
> > What functionality would brake by doing "insert" instead of "replace"?
> 
> I would like both, insert AND abbreviations 😀 

Nothing against the original suggestion, just thought it was retracted. So let's talk about this.

In conjunction with this, I have another question. To ease usage for users not so familiar with programming, I also insert leading and ending ' with functions taking strings and put the cursor in-between. For example like this (`*` marks the cursor position after insert, it is not part of the insert): `lettervalue('*')`

Would this create problems when follow-up inserts are possible at cursor pos?

The more general question: is the function helper designed the right way at all, or would there be a better way to do this for novices? For example GCBuddy offers a separate dialog to calculate functions (with function-specialized input fields, no need to type/insert function names or ' in case of string) and just inserts the function result in the formula?

I don't mean to take away the ability to type in functions into the formula (I will definitely use it this way myself), but maybe for novices this is already too complex even with the insert helper?

**Comment by eddiemuc** [comment]
> > There's no differentiation codewise between "abbreviations" and "long-names", just different function names for the same function (one of them being the "main name"). How should "abbreviations" be identified? Anything with less than 4 chars?
> 
> Or where there are more than one names, and then take the shortest one.

See PR #12781 for implementation of this

**Comment by murggel** [comment]
> > Or where there are more than one names, and then take the shortest one.
> 
> See PR #12781 for implementation of this

You are fast 😀

**Comment by murggel** [comment]
> > > I think murggels original suggestion makes a lot of sense here.
> > > What functionality would brake by doing "insert" instead of "replace"?
> > 
> > I would like both, insert AND abbreviations 😀 
> 
> Nothing against the original suggestion, just thought it was retracted. So let's talk about this.

At first, I thought it would be sufficient, but I figured out I am too lazy to type the "longer" functions 😅, but want to use the abbreviations for often used functions.

> In conjunction with this, I have another question. To ease usage for users not so familiar with programming, I also insert leading and ending `'` with functions taking strings and put the cursor in-between. For example like this (`*` marks the cursor position after insert, it is not part of the insert): `lettervalue('*')`
> 
> Would this create problems when follow-up inserts are possible at cursor pos?
> 

I guess no, because function of function would probably mainly used for functions with numerical input, because most functions return numerical output.

**Comment by murggel** [comment]
> The more general question: is the function helper designed the right way at all, or would there be a better way to do this for novices? For example GCBuddy offers a separate dialog to calculate functions (with function-specialized input fields, no need to type/insert function names or `'` in case of string) and just inserts the function result in the formula?
> 

I really appreciate that we insert the complete function and not only the result in the formula even when using the helper, please don't change that.



> I don't mean to take away the ability to type in functions into the formula (I will definitely use it this way myself), but maybe for novices this is already too complex even with the insert helper?

Probably some additional dialog to input the parameters for the function would be helpful (e.g. substring), I am not sure if it is necessary though.

**Comment by eddiemuc** [comment]
Merging PR #12787 will insert function at cursor pos without deleting content first, as requested...
