### ISSUE TITLE
Track visibility setting is not restored correctly 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12770]
### Describe your problem!

When you import a GPX track but select to hide it on the map, it will become visible again if you reopen the map. 

### How to reproduce?

1. Open Livemap
2. Import track
3. Hide track
4. Close livemap
5. Open livemap 

### Actual result after these steps?

Track is visible again 

### Expected result after these steps?

Track should be hidden according to the last selection 

### Reproducible

Yes

### c:geo Version

2022.02.16-NB

**Comment by moving-bits** [comment]
As the visibility state is stored in the database there's probably a bug on loading the track (not respecting the stored value) then.

**Comment by eddiemuc** [comment]
Hopefully fixed with PR #12837
