### ISSUE TITLE
Feedback: Swap Watchlist and Favorite Icon Status? 

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#12789]
### Tell us your idea!

Hi, 

this is not a regular feature request but the request for feedback from the rest. 

While checking a cache main page I am always struggling with the icons being stated for the watchlist and favorite:

![IMG_20220214_080613](https://user-images.githubusercontent.com/4508228/154869644-1ab13005-5bf3-4758-a2c0-4dcce79268ba.jpg)

Both are stated "active" while the text is stating that I  have this cache neither on the watchlist nor have given a favorite. 

When they are active, the icon is stating the opposite:
![IMG_20220214_080552](https://user-images.githubusercontent.com/4508228/154869623-f8825054-3e89-47fe-bdf5-f1e34788b89d.jpg)

I know that both buttons are stating the next action, but maybe it is more intuativ, when they are stating the real status instead of the next action being triggered by clicking them. 

So something like plain text plus the icon reflecting the status:

Watchlist: icon active/icon disabled
Favorite: icon active/icon disabled

What are your thoughts? Am I the only one struggling with this? 

### What solution would you suggest?

See above...

**Comment by ztNFny** [comment]
It's buttons, not indicators. All our buttons show the action they perform, e.g. disk to store the cache offline, trashcan to delete it, ... Thus imo they are correct as they are.

**Comment by Lineflyer** [comment]
I agree, those are buttons performing the actions they show.

**Comment by moving-bits** [comment]
Then let's close here
