### ISSUE TITLE
[Variables] Opt-out from using fullscreen keyboard 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12780]
Currently, the well known Android fullscreen keyboard UI is shown when editing a variable in landscape mode on a phone. 

However, it is possible to opt out using this input behavior via `android:imeOptions="flagNoFullscreen"`. Doing so would IMHO improve usability... 

![Screenshot_20220219_225935_com whatsapp w4b](https://user-images.githubusercontent.com/64581222/154820638-b1a231a0-fff9-4061-9b19-a0981df1d8d2.jpg)

**Comment by eddiemuc** [comment]
PR #12793

**Comment by fm-sys** [comment]
As @Lineflyer described in https://github.com/cgeo/cgeo/pull/12793#issuecomment-1047139988 there are some side-effects with multiline textfields. So we should disable the fullscreen overlay for single line text inputs only, but keep in for multi-line text fields.

Just want to show, that this "feature" does even more harm - suggestions are missing in landscape:

||||
-|-|-
![grafik](https://user-images.githubusercontent.com/64581222/155035923-5f601644-d1df-44bb-a308-2cf0cda58f9f.png)|![grafik](https://user-images.githubusercontent.com/64581222/155035964-14ef83db-3b74-4613-a696-8ca6ae0f0b12.png)|![grafik](https://user-images.githubusercontent.com/64581222/155036479-20fe8bbf-aac7-43f4-bf69-e46702f44046.png)

**Comment by Lineflyer** [comment]
It seems for single line text inputs it has its advantages to see the real app context instead of full screen keyboard.
If as at @fm-sys stated its possible to easily activate it for single line text input fields only, we could try that on `master` to doublecheck over time if there are still usability problems with that.

**Comment by fm-sys** [comment]
> If as at @fm-sys stated its possible to easily activate it for single line text input fields only

Unfortunately I noticed that it's not just a one-liner, as we use the same style for single and multi-line text fields currently. But this can be adapted for sure.

Anyway using single-line as decision criteria is the most consistent implementation IMHO.

**Comment by fm-sys** [comment]
PR #12802
