### ISSUE TITLE
Allow upload of own spoiler images

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12783]
### Tell us your idea!

I was recently approached by a geocacher who would like to have the possibility to add own, private images to a geocache (e.g. spoiler images and such) which should be kept on the cache but of course not be made public (e.g. via log).

When I heard this I thought about the existing c:geo feature to upload spoiler images in the already existing folder `GeocachePhotos`.  With this in mind it would be very easy to allow the user from within c:geo to add and remove own images to this structure.

### What solution would you suggest?

* Add the well-known "add image from gallery" / "add image from camera" to the top of the image list of a cache to select new images to add
* Mark own "spoiler images" somehow (e.g. by adding "Own image" to the title) since with this feature their usage may become more common
* Put a delete button next to the own images for deletion

The following is a crudely MS-painted screenshot on how this could look like (the upper image is supposed to be an image from the cache, the lower one an own image)

![image](https://user-images.githubusercontent.com/6909759/154841051-8b80d532-4140-4f24-97b4-9faf72306dda.png)

### Is there an alternative?

No implementation

**Comment by Lineflyer** [comment]
Interesting feature!
Just thinking if it might make more sense to develop something to extend the personal note by something like "personal files" to allow more broadly attaching anything you want (e.g. a PDF, a track). Adding pictures could be a first step in there and it could be extended lateron.

It was also from time to time asked by users to have such "cache based storage" for files (and even a linkage to a cloud storage like Dropbox, GDrive was asked for). IMHO we have some issue here about that generic topic.

**Comment by moving-bits** [comment]
Such a generic "add personal file to geocache" would be very welcomed. I guess we do not differentiate between images and other file types, just present them as a list and let Android decide on which app to open on tapping the file. (As for images I mostly open the gallery app anyway to be able to zoom.)

**Comment by eddiemuc** [comment]
Hm extending this to handling of user-specific arbitrary files makes the thing a little more complicated of course. A couple of questions coming to my mind:
* Where and how would this be displayed. Possibilities are e.g.
   * As a separate new list under personal notes on "Details" tab
   *  Integrated into "Image" tab (then images from cache, user-specific images and user-specific non-images are displayed in the same place) with clickable previews for all supported content type (already there for images). Probably "Image" is then not the right name for the tab any more
   * New tab e.g. "Personal storage" beside the existing "Image" tab, but visually similar to it (clickable previews for all currently stored content esp images, but of course with delete/add functions) 
* if we create a new list either under PN in details or in a new tab: should the existing spoiler images be moved there? (because those are also user-specific and user-defined content, even if c:geo has only read-only support for it currently)
* How to "preview" non-image files? Or should we have no preview for user-specific files at all (even not images)?

> even a linkage to a cloud storage like Dropbox, GDrive was asked for

I am not an expert for this, but I don't think we need additional support there
* When user selects a file for c:geo (e.g. an image), those services should provide a SAF handler if they want to support it (I don't know which services do to be honest), not something to do on c:geo side IMHO
* When user wants to backup/synchronize certain c:geo folders with such a services, I expect those services to provide the needed capacities
So I currently don't see what additional meaningful features c:geo could offer towards such cloud services.

**Comment by Lineflyer** [comment]
> Hm extending this to handling of user-specific arbitrary files makes the thing a little more complicated of course. A couple of questions coming to my mind:
> 
> * Where and how would this be displayed. Possibilities are e.g. [...]

- A dedicated tab would be a clean solution in order not to overload existing tabs. But we already use 7 tabs, which is quite a lot.
- Putting it below the "Personal note" section as a new "Personal file" section sounds matching and is easy to reach. Anyhow already know I think "personal notes" are not well placed on the "details" tab as its not really related to the remaining content.
AFAIR it was decided at that time to have all descriptional texts on one tab.

I think we should not do a "quick shot" here but carefully evaluate which way we want to go.

Personally I would indeed prefer to have such "Personal storage" (name to be decided) tab and move all individual information (notes, files, anything else?) to there.

>   * Integrated into "Image" tab (then images from cache, user-specific images and user-specific non-images are displayed in the same place) with clickable previews for all supported content type (already there for images). Probably "Image" is then not the right name for the tab any more

That does only fit if we are talking about images.
I would suggest to have this elsewhere (as discussed above) but no one stops us from showing images attached there also on the gallery tab.


> * if we create a new list either under PN in details or in a new tab: should the existing spoiler images be moved there? (because those are also user-specific and user-defined content, even if c:geo has only read-only support for it currently)

Do you refer to listing spoiler pictures or to the [possibility to load own spoiler images](https://manual.cgeo.org/en/spoilersync)? Only for those own spoiler images I agree to put them into such new location. 

> * How to "preview" non-image files? Or should we have no preview for user-specific files at all (even not images)?

We should not try to change c:geo into a full-blown file manager. I think we don't need a preview, just open the files on tap. For images we could use the existing gallery tab (see proposal above) to offer a preview. But we could also reuse the preview function we have on logging view.

> > even a linkage to a cloud storage like Dropbox, GDrive was asked for
> 
> I am not an expert for this, but I don't think we need additional support there

I would leave this out in the first step to have less complexity. As noted, adding files from a cloud services might then already be possible if they have a SAF handler.

Regarding file storage:
If someone works on this, I suggest to import all files to the "additional cache data" storage (as described [here](https://github.com/cgeo/cgeo/wiki/Disk-usage-structure#additional-data-for-caches)). The structure by geocode is already there, the user can move it to an external SD and it will be deleted upon deinstallation. Sounds good.

**Comment by eddiemuc** [comment]
> Do you refer to listing spoiler pictures or to the possibility to load own spoiler images? 

I meant the possibility to load own spoiler images.

**Comment by moving-bits** [comment]
I would put personal files as a list directly beneath the "personal note" field, as they are related. Probably just file name + file date/time, maybe newest first (or in alphabetical order?).

For a start I would keep them both in today's place, meaning at the end of the description tab. This avoids adding an additional tab, which would be visible for every user, as the input field for personal notes is available to everyone, even if no text is entered.

**Comment by ztNFny** [comment]
Imho for a cgeo integration storing images would be enough. Other files (e.g. a Word with long text) that is created during solving a mystery are not created on the phone aka in cgeo.
At least images would probably cover 99% of the usecase.

PS: i use an unpublished listing at gc.com for storing images, free storage 😉

**Comment by eddiemuc** [comment]
Hm seems like more discussion is needed. Any way coming to a common agreement?
(I would personally agree with @ztNFny , but if others see the need for additional files I won't stand in the way)

**Comment by ztNFny** [comment]
how about a MVP approach?
1. add local images to images tab
- store images in a seperate folder on sdcard so they are separated from other stuff for a later sync - this folder could then already be synced with a 3rd party app
- requires little more in terms of UI than the add button suggested in OP
2. add an image sync service on top of that
- we can probably just integrate an API from Dropbox, Box, Google, ... for that
3. add support for other filetypes
- sync is already there
- probably the most complex step in terms of UI - right now I'd think to rename "Images" tab to "images & Files" and display them as "file"-icons

**Comment by eddiemuc** [comment]
Hm step 1 would be pretty much what I suggested in the first place I guess. Maybe additionally make the GeocachePhotos folder selectable by user optionally (so he may choose e.g. a folder on SD card if wanted)

**Comment by ztNFny** [comment]
> Hm step 1 would be pretty much what I suggested in the first place I guess. Maybe additionally make the GeocachePhotos folder selectable by user optionally (so he may choose e.g. a folder on SD card if wanted)

Yes :-) Only addition I see vs your original suggestion is "put them in seperate folder" (other than the downloaded images).

I think at least that point there's no disagreement whether it makes sense, so that's something that could just be implemented.

**Comment by ztNFny** [comment]
btw, probably worth taking a look at what Locus offers in that area. I know that you can add photos to caches there, but no idea about "additional features".

**Comment by eddiemuc** [comment]
> Only addition I see vs your original suggestion is "put them in seperate folder" (other than the downloaded images).

...but `GeocachePhotos` **is** a separate folder from the download folder. It is a public folder already in existence today (means: if it is available and filled with images in a certain dir format resembling geocodes then images are shown in Gallery of respected caches). I know this feature is not very well known today though (I only know of it because I had to migrate the folder back when I did the SAF stuff)

**Comment by ztNFny** [comment]
We really need to compile a list of all the hidden features in cgeo 😯

**Comment by Lineflyer** [comment]
I would be fine to limit it to photos (for now).
My comment was just the reference that some users requested even more, but this will be a minority for sure.

I would still stay with my opinion  not to squeeze it into an existing tab, but rather use the chance to clean up and put custom info into a dedicated tab (or other meaningful separation?!) together with personal note.

My very basic mock-up would be:
![image](https://user-images.githubusercontent.com/949669/155028870-57fa3f93-998d-4378-90b6-4fb9a0440647.png)

Regarding the storage:
As for the images it might indeed then be meaningful to use `GeocachePhotos` syntax to store them, as:
- Will incorporate own spoiler sync automatically
- Will (may be) also allow those spoiler scripts to back-sync (?!)
- Is separate from other data
- Will be kept on uninstall as its personal info and potentially important
- Will be included in gallery automatically

**Comment by Lineflyer** [comment]
BTW: Adding the personal note here would also easily allow to use buttons or other more descriptive elements for the export waypoints/upload actions. Even myself often struggles with these buttons as I don`t want to crash my data.

**Comment by ztNFny** [comment]
Having listing, hint and note available together is quite useful though. That contains all the text info needed to find the cache. I'd hate to see note moved away from that.

**Comment by Lineflyer** [comment]
> We really need to compile a list of all the hidden features in cgeo 😯

https://manual.cgeo.org/en/hiddenfunctions ;)

**Comment by ztNFny** [comment]
> > We really need to compile a list of all the hidden features in cgeo 😯
> 
> https://manual.cgeo.org/en/hiddenfunctions ;)

This folder, long-click on a cache on the map to add it to a route, ... I think it'd be worthwhile to have a "feature of the week" promoted on homescreen.

**Comment by moving-bits** [comment]
> Having listing, hint and note available together is quite useful though. That contains all the text info needed to find the cache. I'd hate to see note moved away from that.

You would still have it available using the three dot menu => "Personal note", though not visible at the same time anymore.

**Comment by moving-bits** [comment]
> I would still stay with my opinion not to squeeze it into an existing tab, but rather use the chance to clean up and put custom info into a dedicated tab (or other meaningful separation?!) together with personal note.

Generally I like the idea to have all such info on one tab. The only thing that bugs me with this proposal is that it would introduce an extra tab for everyone, although probably most users won't ever store personal spoiler pictures (or only rarely). For them personal notes would be moved to a separate tab used for nothing else, meaning they have to swipe over one extra tab.

**Comment by ztNFny** [comment]
> > Having listing, hint and note available together is quite useful though. That contains all the text info needed to find the cache. I'd hate to see note moved away from that.
> 
> You would still have it available using the three dot menu => "Personal note", though not visible at the same time anymore.

Having it "accessible" is a lot less useful than having it "available / visible". Removing the user note from listing is a big no-no to me - it'd require reading 2 places instead of one when you need a hint (I put notes from geocheckers in the note) - which is a major incovenience.

**Comment by ztNFny** [comment]
My vote is to just add the "+" button to the existing images tab.

**Comment by Lineflyer** [comment]
The arguments of @moving-bits and @ztNFny are very valid indeed.

Keeping the personal note where it is would also be fine for me.

In this case a dedicated tab just for image would not be the right thing, but just adding a "+" on the image tab sound also a bit strange. It could create the impression, that I can add a picture to the cache itself but not only for me.

**Comment by ztNFny** [comment]
> but just adding a "+" on the image tab sound also a bit strange. It could create the impression, that I can add a picture to the cache itself but not only for me.

For note vs hint the differentiation between cache and custom seems to be clear. Maybe add the "+" button next to edit note and show the image in images (which already today shows but just cache but also user/log images)

**Comment by eddiemuc** [comment]
Wow, lots of discussion going on here :-)

Reading through it my impression is that the rather big topic of "(how) should we reorganize our tabs" got a bit intermixed with the original issue. Maybe we should create an own issue for this?

For now, I would vote for @ztNFny first step MVP and my original suggestion: implement it as "adding/deletion" option on image tab. I assume by labeling the add buttons with something like "add own images" or "add personal images" we can avoid confusion.

As @ztNFny also correctly stated, the image tab already mixes images from many sources into one tab today:
* Cache listing
* User logs
* User spoiler images (if used)

So if there's confusion about this, at least it should not be bigger than today :-) We can (if wanted) make this confusion a little smaller by adding e.g. categories to the images, maybe as simple as introducing section headings?

**Comment by ztNFny** [comment]
> maybe as simple as introducing section headings?

Images already have labels above them, i'd think it's good enough to choose a good label for those custom ones.

**Comment by eddiemuc** [comment]
> > maybe as simple as introducing section headings?
> 
> Images already have labels above them, i'd think it's good enough to choose a good label for those custom ones.

Sections would also allow to put the "add/remove" button at the right place (into the "own images") though. Something like this:

![image](https://user-images.githubusercontent.com/6909759/155079396-63a98e52-58d3-42fd-85d4-c13dffca97f4.png)

**Comment by ztNFny** [comment]
> Sections would also allow to put the "add/remove" button at the right place (into the "own images") though. Something like this:

Looks good. While at it a little visual refresh wouldn't hurt the images tab, it looks quite dated. Maybe like a grid-view with captions below the image? (sorry if this is too off-topic here)

**Comment by murggel** [comment]
Looks good, but I would prefer to place the own images above the user logs images.

**Comment by eddiemuc** [comment]
While reworking the cache image display I started experimenting with flow layouts for this screen. Here are some first screenshots on how this could look like in the future (I tried to find a cache with many images):

 Using normal, upright display:

![image](https://user-images.githubusercontent.com/6909759/156900345-d065cee1-33c8-43ab-9967-6f6e08d14ab6.png)

![image](https://user-images.githubusercontent.com/6909759/156900371-eb8f57b8-fe66-4267-915e-a8e7281a063a.png)

using landscape:

![image](https://user-images.githubusercontent.com/6909759/156900387-fbad1610-b9d9-41a2-8fd0-0a7745cd07a9.png)

Using a very wide (emulator) screen:

![image](https://user-images.githubusercontent.com/6909759/156900315-4bdc5b52-f7d2-4cdd-8d30-954a1e0c0177.png)

I expect a longer discussion on this. As of now my question would rather be:
* Is using "Flowlayouts" going into the right direction (-> possibility to display more than one image in one line if space permits)?
* I use the "old" image title style now to display the category. Information for one image (image + title + description) is now encapsulated using a border. Could also be a colored-background or whatever -> it this going into the right direction?

As of now very tiny, note the "add image(s)" buttons (from storage or via camera) in category "Own". Might become the less problematic change here :-)

**Comment by ztNFny** [comment]
What determines the size of the preview images? On those screenshots - but also in the current release - the uneven sizes make it look busy, even chaotic - and the new borders increase that even more.
Maybe it could be made to look more like a table, with all borders in a row the same size? Rough edit:
![image](https://user-images.githubusercontent.com/1258173/156938510-9ed39d4b-e983-4c16-89f0-4ea6623c7de5.png)

Or we do what most gallery apps do: square previews. I'd like a look like
![image](https://user-images.githubusercontent.com/1258173/156938693-105c4469-bb32-4dcc-a81d-8798dc77c4ed.png)
![image](https://user-images.githubusercontent.com/1258173/156938712-05fc8062-1c0c-4d65-a626-53a728cf43d9.png)

**Comment by eddiemuc** [comment]
> What determines the size of the preview images? 

The preview size seems to be defined "magically" by the Android ImageView default behaviour itself (whatever this view is doing if width/height is set to "wrap_content").

> On those screenshots - but also in the current release - the uneven sizes make it look busy, even chaotic - and the new borders increase that even more.

I agree. I can leave the border out of course, but then how to hold title, description and image together?
(I can also leave everthing "as is": one image per row)

> Maybe it could be made to look more like a table, with all borders in a row the same size? Rough edit:
> Or we do what most gallery apps do: square previews. I'd like a look like

I am undecided. Design-wise I guess the "square preview" look is better, but it might be that geocaching users value to see the "whole" image in preview already without anything cut off.

**Comment by ztNFny** [comment]
> Design-wise I guess the "square preview" look is better, but it might be that geocaching users value to see the "whole" image in preview already without anything cut off.

they are so small you have to open them to properly see them anyway.
If we could add swiping between images it'd be perfect imho, then previews are really only a minor thing

**Comment by eddiemuc** [comment]
> they are so small you have to open them to properly see them anyway.\nIf we could add swiping between images it'd be perfect imho, then previews are really only a minor thing

Yeah, that's right.

But since we don't have an own "open" dialog (we just call a system intent) we can't add swiping to it. This would mean designing a whole new "image detail" view inside c:geo. Which I think would be a good thing but also something bigger codewise. Apart from swiping we would at least need zooming. Maybe displaying some geo-related actions and Infos with it (what about e.g. image metadata, often useful for many mysteries...). Task keeps getting bigger.

Does anyone know a good open source "image gallery component" we could use as a base for this?

**Comment by moving-bits** [comment]
Thumbs up for the "flowable" approach in combination with squared even-sized preview images 👍

**Comment by ztNFny** [comment]
> Does anyone know a good open source "image gallery component" we could use as a base for this?

Cant we hand over the images to an external gallery as a folder of images instead of the current 1 image?

**Comment by eddiemuc** [comment]
> > Does anyone know a good open source "image gallery component" we could use as a base for this?
> 
> Cant we hand over the images to an external gallery as a folder of images instead of the current 1 image? No idea what Android enables here

Phew... I don't know if this is possible. As of today we simply fire a standard ACTION_VIEW intent against the system and whatever app the user has chosen for herself as Android standard app for images will open up (or a selector). We need to find out whether there's a similar intent to view a whole folder. Is there?

Also, the image is copied to a local private file before passing it to intent, and permission to view is granted via the intent. Don't know how one would grant permission to a whole folder and without the need to copy all images previously to a special folder.

Also, today images are not all stored in same folder, some are not even stored on device (Uri points to online, e.g. to GC.com server - well there's a cache in-between buried deep in class Htmlmage)

**Comment by eddiemuc** [comment]
> Thumbs up for the "flowable" approach in combination with squared even-sized preview images 👍 

Square-sized it is :-)

While experimenting with this, I stumbled on a second problem to unify image size: title and description. Both is shown today in full (description only if available) and has different lengths of course. 

Solution suggestion:
* Always reservse two text lines for title and description.
* If description is available, use first line for title, second for description
* If no description is available, allow usage of both lines for title
* cut off/ellipsize titles/descriptions not fitti ng

Problem here is: there's no other place to view title/description. Opening standard app will only show image, not this "c:geo metadata"

Alternative would be to allow different "row heights", depending on longest title/description in row.

Opinions?

**Comment by moving-bits** [comment]
Suggestions sounds reasonable and should be fine in most cases.

_If_ we want to make sure title/description can be read even if they are longer than the provided lines, we could add a long-tap action to the image, displaying a small dialog popup with full title / description.

**Comment by ztNFny** [comment]
Imho title and description aren't very important. I'd say that 80% of titles are "uploaded with <software>" and 99% don't have a description. Can't remember a single instance where description contained amything relevant. So I wouldn't care if it's not shown at all.

**Comment by eddiemuc** [comment]
What about really going the next step and implementing a new c:geo activity to show a single image in detail on tap?

Features shall include:
* Zooming (naturally)
* Swipe to next/prev image
* Showing title/description
* Showing category-specifix data e.g. user +log date for a log image
* Showing selected metadata if available in image e.g. coordinate or comment (metadata lib is already part of c:geo sources)

View should also provide actions to open image with standard app and all things now available via long-click context menu.

**Comment by moving-bits** [comment]
> What about really going the next step and implementing a new c:geo activity to show a single image in detail on tap?

I'm a bit undecided here: Having such a view would be a nice thing indeed. On the other hand it smells a bit like reinventing the wheel, duplicating functions a system-provided gallery app should have already (mostly). 
I guess, if it's not too much work and additional libs, go for it.

**Comment by fm-sys** [comment]
Can we adjust the max size of the images dynamically, so that always at least two columns are shown? Two images should IMHO always fit even on small screen devices... 

![Screenshot_20220323_081402_cgeo geocaching_copy_270x585](https://user-images.githubusercontent.com/64581222/159644558-e90ebc6f-8965-47b6-b215-d138c340875a.jpg)

And another small design suggestion:
Can we use rounded corners for the image view? Our dashboard activity shows, how something like this can be implemented...

|||
-|-
|![Screenshot_20220323_081151_cgeo geocaching](https://user-images.githubusercontent.com/64581222/159645030-b51134d7-d2c0-444d-abcd-fd880ac22a66.png)|![Screenshot_20220323_081455_cgeo geocaching](https://user-images.githubusercontent.com/64581222/159645061-21706242-045c-485f-8aa0-d0abb591a48f.png)|

**Comment by ztNFny** [comment]
Can we enable gallery for user-defined caches as part of this?

**Comment by eddiemuc** [comment]
> Can we adjust the max size of the images dynamically, so that always at least two columns are shown? Two images should IMHO always fit even on small screen devices...
> 
> And another small design suggestion: Can we use rounded corners for the image view? Our dashboard activity shows, how something like this can be implemented...

Done with PR #12872

**Comment by eddiemuc** [comment]
Question to the team:
For working on an own image detail view activity, I need the ability for a zoomable, pannable ImageView. I found the following implementation for such a view which seems to work like a charm:
https://github.com/Baseflow/PhotoView 

Would it be ok to use this small lib in c:geo? Apache 2.0 License, jar has about 30KB in size and no new dependencies introduced.

**Comment by eddiemuc** [comment]
build.gradle:

```
// PhotoView for zoomable ImageViews
implementation 'com.github.chrisbanes:PhotoView:2.3.0'
```

**Comment by Lineflyer** [comment]
The missing ability to see the whole image in the new tab was also something I had in mind to discuss. 

But it sounds you are already working on it. IMHO such a library is preferable over reinventing the wheel.

**Comment by bekuno** [comment]
> https://github.com/Baseflow/PhotoView

Hmm, this project is not more maintained.
The last release (2.3.0) is from November 2018, the last commits are from January 2021.

**Comment by eddiemuc** [comment]
> > https://github.com/Baseflow/PhotoView
> 
> Hmm, this project is not more maintained.
> The last release (2.3.0) is from November 2018, the last commits are from January 2021.

Correct. Do you think this is problematic?

As an alternative I could copy the code into own c:geo classes and try to strip it down a little towards our needs. I miss one feature in it anyway (support for swiping to next image)

**Comment by bekuno** [comment]
How about https://github.com/igreenwood/loupe ?
You find a description at https://medium.com/@issei_greenwood/introducing-loupe-10-minutes-to-implement-twitter-like-image-viewer-19c522db3c68.

**Comment by eddiemuc** [comment]
> How about https://github.com/igreenwood/loupe ? You find a description at https://medium.com/@issei_greenwood/introducing-loupe-10-minutes-to-implement-twitter-like-image-viewer-19c522db3c68.

Looks good on first glance. I noticed three things however:
* Code has no license statement on it. Is this problematic?
* Code seems to be maintained by a single person only. Maintenance in future might or might not be clear
* In the article, the code author mentions PhotoView himself :-) (among two other libs I haven't looked into)

**Comment by ztNFny** [comment]
> Code has no license statement on it. Is this problematic?

Readme.md states MIT which is pretty much free for all. If we use it the author asks to be pinged about that - but thats only a request - one we should and can easily fulfill.

Lib looks good to me.

**Comment by eddiemuc** [comment]
> How about https://github.com/igreenwood/loupe ? You find a description at https://medium.com/@issei_greenwood/introducing-loupe-10-minutes-to-implement-twitter-like-image-viewer-19c522db3c68.

After working with Loupe now I am not sure this is the right choice. It seems not to be well maintained after all.

Reason for this opinion: there is a very obvious and easy-to-implement change request openend against Loupe for a year, which is to forward single tap events to the user (I need this to support toggling between "full screen mode" and "information mode"). There is even a working PR for this for almost a year, but nothing happened. I now had to implement a really ugly workaround into c:geo to get this running - let's hope it works. See details here: https://github.com/igreenwood/loupe/issues/25 

A more minor thing: I immediately run into some problems when dealing with Loupe:
* Loupe crashes when there's no background set on used views. Obvious error, easy fix (I already provided a PR), but it is surprising to me that this was never discovered before
* When installing loupe locally it does not compile unless you perform some undocumented magic with the provided build.gradpe (removing the publish stuff)

I am currently not at all sure whether this is the right choice to go forward. Let's see how timely the project reacts to my PR and comments today.

**Comment by ztNFny** [comment]
> After working with Loupe now I am not sure this is the right choice. It seems not to be well maintained after all.

Do we have a better alternative though? PhotoView looks way worse in those terms :-(

**Comment by moving-bits** [comment]
> > After working with Loupe now I am not sure this is the right choice. It seems not to be well maintained after all.
> 
> Do we have a better alternative though? PhotoView looks way worse in those terms :-(

If not we can still integrate the code into c:geo (as suggested somewhere above already) and do maintenance on our own.

**Comment by eddiemuc** [comment]
> > > After working with Loupe now I am not sure this is the right choice. It seems not to be well maintained after all.
> > 
> > Do we have a better alternative though? PhotoView looks way worse in those terms :-(
> 
> If not we can still integrate the code into c:geo (as suggested somewhere above already) and do maintenance on our own.

There would be a pro side to that: it would be our first Kotlin project to maintain within c:geo team :-)

**Comment by fm-sys** [comment]
> Imho that should switch to the images tab instead of starting a new activity

It's at least the very same behavior as before. It shows a filtered image gallery in a new activity, cause the images tab can contain log pictures as well...

**Comment by ztNFny** [comment]
> It's at least the very same behavior as before

Old was bad, doesnt mean new has to be bad 😜

**Comment by eddiemuc** [comment]
> > Imho that should switch to the images tab instead of starting a new activity
> 
> It's at least the very same behavior as before. It shows a filtered image gallery in a new activity, cause the images tab can contain log pictures as well...

I don't think it is a good idea to make the app simply jump to the image tab. The user can achieve the same by swiping right a few times...

I can think of two ways to make the behaviour of c:geo better:
* remove the "click on hint images" link completely
* leave it and open the separate activity, but filter the image list meaningful to images which really are spoilers (e.g. only images with the word "spoiler" in their title). Of course such a logic would always be a little fuzzy...

**Comment by fm-sys** [comment]
> * leave it and open the separate activity, but filter the image list meaningful to images which really are spoilers (e.g. only images with the word "spoiler" in their title). Of course such a logic would always be a little fuzzy...

That would indeed be amazing!

Can we detect whether the image is used in the listing? I guess this would be the best filter criteria... (at least way better than searching for a specific word)

- Spoiler used inside the listing -> no real spoiler
- Spoiler image isn't used -> spoiler, cause why should someone upload the picture otherwise

**Comment by ztNFny** [comment]
> leave it and open the separate activity, but filter the image list meaningful to images which really are spoilers (e.g. only images with the word "spoiler" in their title). Of course such a logic would always be a little fuzzy...

That should already happen in the step before, not when clicking on the link - the "Spoiler images" text should only be shown if there are actually spoiler images. That's tracked in https://github.com/cgeo/cgeo/issues/12938

> I don't think it is a good idea to make the app simply jump to the image tab. The user can achieve the same by swiping right a few times...

1 click vs many swipes, big difference in usability

**Comment by eddiemuc** [comment]
If we agree that it makes sense to show only a subset of images when tapping the "spoiler" link, then jumping to the image tab doesn't make much sense - because this tab shows all images unfiltered.

Then maybe let's continue discussion in #12938

**Comment by eddiemuc** [comment]
> Can we detect whether the image is used in the listing? I guess this would be the best filter criteria.

@fm-sys I am not sure I understand what you mean by "not used in the listing". Do you mean images linked in the listing via a html a/href but not actually displayed there with an html img tag?

Maybe continue at #12938?

**Comment by MagpieFourtyTwo** [comment]
First of all: *Really* like the possibility to add own pics to an offline cache. Great and extremely helpful stuff. This way you are no longer forced to store the checker spoiler fotos somewhere in the file system, just in case there is no mobile coverage in the targeted area ... 

Not sure if it has been mentioned so far (got a bit lost in the discussions above), but what I would love to have, is a possibility to 
... rename the photo and/or add a description (to be e. g. able to distinguish between stage photos and final spoilers)
... at least open .txt and .pdf files (longer descriptions/solutions, routing slips ...)
... open xls(x) files
... alternatively a possibility to directly open the storage folder ...?

Currently I sometimes even create the needed folder by hand and put the needed files there manually, just to know *that* there are related files - and where I will find them with the file explorer ...  ;)

**Comment by eddiemuc** [comment]
As of now I am trying to clean up the image gallery code. Behind the scenes it is pretty messy because I pursued a wrong path of code design. Unfortunately I have not much time for coding right now, but I work on it as time permits. Please don't build in new features into this before I have cleaned it up. The feature is really to be considered "experimental" right now

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo adding other files than images should alrey be available in the nightlies. Option to rename the files will become available via PR #13072

**Comment by eddiemuc** [comment]
> Now that you say it, I recognized the ``file+`` icon - great!
> WRT renaming - thx a lot!
> And, following [Wilhelm Busch](https://www.gutzitiert.de/zitat_autor_wilhelm_busch_thema_wunsch_zitat_3490.html): Will there even be a possibility to add comments ...?  <gd&r>  ;)

The problem with comments is that there's no "natural" way of storing them. The title is of course the filename, and the content is the file itself - but to store associated text (comments or description) we would need to create an extra "metadata" file. Would like this to be discussed before jumping into implementations.

**Comment by MagpieFourtyTwo** [comment]
It's not that important.  Just had the description/comments of Listing- and Logphotos in mind and thought, the ones for own photos/files can possibly go into the same and therefore already existing storage ...

**Comment by MagpieFourtyTwo** [comment]
Just wanted to let you know that I really like the rename function - thx a lot!  :)

**Comment by eddiemuc** [comment]
Original implementation is done and part of master, so I will close this issue. Additional requests should be discussed in own issues
