### ISSUE TITLE
make "Nearby" button configurable

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12790]
### Tell us your idea!

There are users, who will use "Go to" often, but "Nearby" seldom.
To support this we can make the "Nearby" button configurable.

### What solution would you suggest?

Idea 1:
Let user decide, which function will have this button. 
This could be configuread in the same way as for the navigation button.

Idea 2:
Add long tap function to this button to select a second function.

### Is there an alternative?

Only add "Go to" as long tap function.

**Comment by Lineflyer** [comment]
I would not want to have all that bottom nav icons configurable (its a support and user guide nightmare btw to explain the app in such cases), additionally only making one item configurable to exchange it with "Go to" is not worth the effort IMHO.

The long tap for "Go to" is not quite intuitive for "Nearby" but people knowing it will get used to it. So I would vote for your alternative and we can add this to manual and FAQ for those few users regularly using "Go to".

**Comment by moving-bits** [comment]
An alternative to making the button navigation icons configurable could be to introduce configurable buttons on the dashboard / homescreen, as described in https://github.com/cgeo/cgeo/issues/12638#issuecomment-1046320901. Still some effort on support, probably, but less prominent (and hopefully less confusing-prone) than changing bottom navigation icons.

**Comment by Lineflyer** [comment]
> An alternative to making the button navigation icons configurable could be to introduce configurable buttons on the dashboard / homescreen, as described in [#12638 (comment)](https://github.com/cgeo/cgeo/issues/12638#issuecomment-1046320901). Still some effort on support, probably, but less prominent (and hopefully less confusing-prone) than changing bottom navigation icons.

That might indeed be useful.
Are there examples from other apps of common libraries for such things?

**Comment by moving-bits** [comment]
Don't have an example at hand, but to keep it simple I imagine something like this:
- Define a list of (maybe) ten frequently used function that we want to offer our users to assign them to any of those buttons. One additional entry is "(none)" or "(empty)". To keep things simple, we should define which icon belongs to which action (instead of making it user-selectable).
- In settings, add sections "button 1" to "button 4" and let the user select items from that list.
- On home screen reserve one line at the bottom, above the stored caches info, for those buttons. If no button is selected, don't take up any space. Otherwise display one to four buttons with the assigned icons and actions. Long tap should display a short hint, short tap execute the action.

Possible actions could be: (feel free to edit this list)
- Go to
- Pocket queries
- Bookmark lists
- Settings
- Backup / restore
- c:geo manual
- c:geo FAQ
- (don't know if we need a quick link to any other specific setting?)
- (do we need one of the debugging functions? for testing "display settings" would be helpful, maybe "create logfile" as well)

**Comment by moving-bits** [comment]
Sneak preview:

|home screen|settings|select items|none selected|
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/155897081-63bd8e47-84e5-4cbe-a8bb-425eeb7ec643.png)|![image](https://user-images.githubusercontent.com/3754370/155897103-e6915deb-ff1b-451f-84b6-1283f18e997d.png)|![image](https://user-images.githubusercontent.com/3754370/155897112-be334dd7-82b1-4601-9bc7-e991628e913e.png)|![image](https://user-images.githubusercontent.com/3754370/155897219-a391c00f-c264-4961-8cb5-64785f630aa8.png)|


Currently it's kept very simple:
- up to eigth quick launch buttons on home screen
- buttons are always centered
- quick launch buttons area is only shown when at least one button is configured
- configuring buttons is as easy as setting a check
- order of buttons is fixed

**Comment by Lineflyer** [comment]
I appreciate such solution as
1. still quite some users are missing "Go to"
2. with the new home screen many users said its "useless". Such shortcut feature would give it a positive aspect.

We should think about what functions might be meaningful here.
Not sure if user manual and FAQ make sense. What I heard from other caches was:
- Link to specific list
- Link to specific cache

**Comment by MagpieFourtyTwo** [comment]
To be honest, I can't see any significant gain for the (even in my eyes pretty senseless) "Home screen" (only valuable info I get from there is if I have perhaps forgotten to delete an offline log ;) ), as both functions can easily be achieved already now by 
- spec. list: just adding a leading "_" (plus a sort order determining number of blanks after it) to the name of the list in question
- spec. cache: using an "always on top" list (like over here the ``_ Today`` list), with the cache in question in it

Additional advantage of the "always on top" list: You can even put more than one cache in there and create even a bunch of lists for immediate access (at the top of the lists of lists) - and both solutions do a single click more than via the "Home screen".
IMHO, all the demanding users perhaps must know is that they can reach the list of lists by long pressing the ``Stored`` action ... and how they can make use of it's the sorting.

TMALSS: I think there are enough "all day annoying problems" to solve, than to violently force the IMO dead horse "Home screen" to a nowhere leading gallop.  ;)

**Comment by moving-bits** [comment]
> Not sure if user manual and FAQ make sense.

We had it in some issue, can't remember which. Idea was to sort of promote our help options. We could even offer those two as default configuration for the buttons.

> What I heard from other caches was:
> * Link to specific list
> * Link to specific cache

In the very basic implementation I have currently, there's no individualization for the buttons, just on/off.

> TMALSS: I think there are enough "all day annoying problems" to solve, than to violently force the IMO dead horse "Home screen" to a nowhere leading gallop. ;)

IMHO it's not about violently forcing anything. Current homescreen basically has the same functionality as the old mainscreen, just a bit more styled. Its main advantage is the bottom navigation being available in all major activities, resulting in way less tapping back and forth.

**Comment by MagpieFourtyTwo** [comment]
> Current homescreen basically has the same functionality as the old mainscreen

Not really - all the "good stuff" went into the bottom navigation, making it available nearly everywhere. Which is of course a good thing. Nevertheless, by delegating his main functions to the bottom nav, he himself became a bit superfluous. At least seen from a user's point of view (i. e. leaving implementation details out of sight).

Of course it's a good idea to fill him, resp. the won free space with new life, but should this really be done with a limited function (just one cache and one list) which can already now be achieved in an even less limited way? 

For me this sounds a bit like "Let's build a western bypass road, cause the people don't find the way to the eastern bypass - although it will be smaller, but, hey, there's some free ground anyway" - but instead we could just place some signposts to lead them in the right direction. Done way faster, costs less, is less effort, the people will get more used to the already great function of the existing possibilities, and last but but not least it even creates less collateral damage (like e. g. creating new "bug possibilities"). ;)

**Comment by moving-bits** [comment]
So, if I understand you correctly, it's more about the specific proposals "link to specific list" and "link to specific cache", and not about those quick launch buttons all together?

**Comment by ztNFny** [comment]
I can fully understand where @MagpieFourtyTwo is coming from. When bottom nav was started I also fully expected Dashboard to be completely removed. Instead it continued to exist as an empty page for which then and now new uses were sought to fill up the empty space.

What I'd have done is
a) remove "Home" completely
b) make the default view configurable (Stored, Map, Search, ...)
c) add a sidebar to access the menu items still available on home (as last item in bottom nav) - in that also things like a offline log count could be placed
