### ISSUE TITLE
Add search view to map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12798]
### Tell us your idea!

When I'm in an area unknown to me I'm frequently searching for a specific street, or even a city/village. I'm using c:geo in 99% percent of those cases to avoid other, more data hungry solutions. Currently one can use our search page for it, enter an address (or parts of it) and press the "map" button to open a map centered on the location. While this is not bad, it has some drawbacks: It presents only one entry as search result, you need to remember to enter via search, and it's not available directly from within the map.

Therefore I suggest to integrate a search view into our map.

### What solution would you suggest?

Add a search menu entry to the overflow menu of both map types. On selecting this menu entry, a typical search view would open in the actionbar/toolbar, into which a user can enter an address or parts of it.

Variant a)
- Perform an online geocoding request (Mapbox?) and present up to ten search results in a drop-down list.
- On selecting an entry, pan the map to the location given by the search result.

This would work for both Google Maps and OSM, but requires an online connection. An alternative to this could be variant b:

Variant b)
- Perform an offline search against the currently loaded OSM map file data for the viewport currently being displayed.
- Present up to ten search results in a drop-down list.
- On selecting an entry, pan the map to the location given by the search result.

This variant would work for OSM offline maps only. The search would be able to find all map labels included in the map file, especially street names and city names.
Possible extension: As searches against the map file are pretty costly, one may build a database index for this upfront.

Variant a) and variant b) may be combined.

Possible extension for both variants: Present search results as markers on the map instead of a drop-down list. Touching such a marker would display a more detailed info window. Closing the search view would remove the markers.

Possible extension for both variants: Add a POI search using POI data files (OSM offline only) - but that's probably a separate topic.

**Comment by ztNFny** [comment]
If I understand it correctly you're using c:geo for situations where Google Maps or similar would be the "normal" choice, e.g. to search an address to navigate to. Imho we shouldn't invest much in this - c:geo is a geocaching application, not a POI/general maps app - same reasoning many feature requests e.g. for integrating Munzee were closed.

**Comment by Lineflyer** [comment]
I also don`t think its a feature for a geocaching app.

What is a feature (which helps in such situation) is, that we should mark the search center on the map.
Thats AFAIR represented in a feature request here: To mark the search center on a map of results.

**Comment by ztNFny** [comment]
> To mark the search center on a map of results.

How about showing a non-stored custom cache at the center that can then be stored or used as a navigation target?

**Comment by Lineflyer** [comment]
IMHO still to specific and not easily understandable by users. A (on-object) needle or something would suffice the original request to mark the search center.

But coming back to this issue in the original sense:
> Currently one can use our search page for it, enter an address (or parts of it) and press the "map" button to open a map centered on the location. 

That's IMHO not true. Its centered on the middle of search results, which might be quite different.
Proof me wrong.

> While this is not bad, it has some drawbacks: It presents only one entry as search result, you need to remember to enter via search

What about just remembering the search entry via autocomplete in the search menu?

**Comment by moving-bits** [comment]
Thanks for your feedbacks so far.

> If I understand it correctly you're using c:geo for situations where Google Maps or similar would be the "normal" choice, e.g. to search an address to navigate to.

Technically correct. Some drawbacks with that solution, though:
- Only that Google Maps is not a data protection friendly solution
- It requires an online connection (which at least alternative b) wouldn't)
- It's not integrated in c:geo

> Imho we shouldn't invest much in this

Which would rule out alternative b, at least when trying to build a search index for fast searches. The other parts should be relatively easy to implement.

> c:geo is a geocaching application, not a POI/general maps app

Yes, we have that discussion from time to time. for me c:geo is much more, it has so many features originally implemented in the context of geocaching, but useful in so many other use-cases. But, agreed, it's hard to define a specific red line.

> A (on-object) needle or something would suffice the original request to mark the search center.

That's something totally different from the idea above, though I know, it's a feature being requested on support from time to time. IIRC we even have a separate issue for that already.

> > Currently one can use our search page for it, enter an address (or parts of it) and press the "map" button to open a map centered on the location.
> 
> That's IMHO not true. Its centered on the middle of search results, which might be quite different. Proof me wrong.

I guess we are talking about different stages of "search by address" here:
- First step is to enter an address (or part of it),
- then we perform a reverse geocoding, which gives us a single result (address) and a map button beside it. => this is what I was referring to, and tapping that button will give you a map centered to that address;
- but if you tap on the address found by reverse geocoding, then the actual search for geocaches around this address is performed and the result being displayed as a list of geocaches. Here you have our regular "map the result" button, which will center on found caches.

> > While this is not bad, it has some drawbacks: It presents only one entry as search result, you need to remember to enter via search
> 
> What about just remembering the search entry via autocomplete in the search menu?

What I meant was: I need to remember that I can do a "search by address" already (without having to perform the last step of retrieving some caches around this address), but that this function is not available from within the map view, but have to go to our search page.

**Comment by moving-bits** [comment]
Let's close the issue as there is a workaround for the original use case (at least in online mode) and implementing an offline solution would be too far away from c:geo's original context.
