### ISSUE TITLE
Improve slider input for filtering

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12808]
### Tell us your idea!

From a Facebook user:

In the advanced filter for favorites, it can be reeeeeeally tricky to get the filter set to something like "10+ favorite points" exactly, because of my big fingers. Can it be either less sensitive to change when releasing the button, or changed to be text fields for the favorite points/percentage limits?

And on a similar note, make the settings be displayed near the bar, because I'm almost never 100% sure that I got it set to 10 instead of 9 or 11 or 13 etc. And it immediately disappears when you let go.

### What solution would you suggest?

see above

### Is there an alternative?

No

**Comment by eddiemuc** [comment]
For reference here is a screenshot of the setting in question:

![image](https://user-images.githubusercontent.com/6909759/156213971-705090fa-b784-4e0f-b36e-fe7da485ad25.png)

> In the advanced filter for favorites, it can be reeeeeeally tricky to get the filter set to something like "10+ favorite points" exactly,

I agree with the statement. My main problem was that I did not have a good idea to achieve that in a GUI-wise "acceptable" way. One suggestion (have to check if this works technically though): on long-click on a selector an input dialog opens to enter a value directly.

> make the settings be displayed near the bar

The used material.io slider is a bit limited in what one can do here (in fact, even the values displayed under the slider are hand-crafted and not part of material.io). There's no setting to make the labels stay when not selected. Should we explore the possibility to extend the material.io slider with this or is there any other idea on how to achieve this?

While selecting the labels show:

![image](https://user-images.githubusercontent.com/6909759/156215318-e6c6439a-af31-4dd1-953d-1d754eed26b9.png)

**Comment by eddiemuc** [comment]
Update: "on-click" does not work. What about placing an "Edit"-icon right to the slider. It will open a small dialog where one can manually enter a "min" and "max" value. Something like this:
 
![image](https://user-images.githubusercontent.com/6909759/156216702-b1141309-5b8b-4a1c-8540-4d727cbed90d.png)

![image](https://user-images.githubusercontent.com/6909759/156217952-8dd33300-da63-4b34-b5f7-c4cadb05f717.png)
