### ISSUE TITLE
Add "Go to" to quick start icons

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12809]
### Tell us your idea!

Independently from other measures regarding customization of menus or action buttons on home scren, a fast imrpovement could be to add Go to to the quick start icon set (when long tapping the c:geo launcher icon). Or might there be a limited to 4 functions?

Currently its contained as widget but not as quick start icon.

For those unaware of that feature:
https://manual.cgeo.org/en/quick_widgets

### What solution would you suggest?

Add Go to to the quick start icon set 

### Is there an alternative?

Using a widget

**Comment by ztNFny** [comment]
You can't have more than 4 shortcuts

**Comment by Lineflyer** [comment]
OK, lets then drop this idea. @ztNFny Thanks for looking it up.
