### ISSUE TITLE
here app - Navigation (Driving) does not work

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12810]
### Describe your problem!

from geoclub.de:

Ich verwende eigentlich seit 'immer' die HERE maps (aktuell HERE WeGo) auf dem Mobiltelefon ... schon zu Symbian Zeiten war es eine gute, kostenlose Navigationssoftware mit gutem Kartenmaterial und mit der Möglichkeit Offline Karten zu verwalten.

Seit dem letzten App Update ist erstens die Oberfläche katastrophal schlecht geworden, aber noch viel unangenehmer ist, dass die Navigation zu Wegpunkten aus c:geo heraus nicht mehr funktioniert. Es wird einfach das Ziel nicht mehr sauber übergeben.
Nachdem es mit GMaps noch funktioniert, wird es wohl nicht an c:geo liegen, aber evtl. kann man doch irgend 'etwas' machen?

Wenn ich statt Navigation (Fahren) oder Navigation (Fahrrad) 'Andere externe App' auswähle, werden die Koordinaten interessanterweise 'korrekt' übergeben aber leider auch der Cache Name in Klammer hintendran ... womit die Zielnavigation auch nicht direkt ohne herumzutippen gestartet werden kann.

### How to reproduce?

1. Open cache details
2. select menu Navigation -> Navigation (Driving)
3. Open with: HERE WeGo

### Actual result after these steps?

The HERE app starts, but the destination is not presented.

### Expected result after these steps?

The HERE app starts, the destination is selected and the drive mode is activated (if possible)

### Reproducible

Yes

### c:geo Version

2022.02.16

**Comment by Lineflyer** [comment]
We had this on support mail months ago.
AFAIR we (@moving-bits) also sent a bug report to HERE and some time later a user provided feedback, that HERE solved it on their side in a new release.

You should ask the user to check possible update to his HERE app.

**Comment by bekuno** [comment]
I tested ir with the current version

**Comment by moving-bits** [comment]
Months ago it did not work any more at all, and after the "fix" on their side, transferring coords started working again, but they do use the given name as sort of a search string, even if specific coords are given...

Workaround is to call Here app as usual, let them do their faulty search, and then delete the name given in brackets, so that only the coords remain. It's pretty messy, but at least you can use Here app again.

But still something Here should fix on their side (and it has worked some time ago).

**Comment by moving-bits** [comment]
Since around August we have a new navigation target "other (coords only)" which works with Here app (by calling the app with coords only, without a textual description which seems to confuse Here app since their program changes). Let's close here.
