### ISSUE TITLE
"long tap on map" & waypoints

### ISSUE THREAD

**Issue by McKirni** [cgeo/cgeo#12821]
### Tell us your idea!

I can set whether a long tap on the general map creates a new CACHE or not.
But when I look at the map of a cache, a long tap always wants to create a new WAYPOINT.

### What solution would you suggest?

addtional option in "settings/Map/Map behavior" to set whether a waypoint should be created with a long click or not

**Comment by Lineflyer** [comment]
What would be the benefit of the ability to switch this function of, respectively what is your connected problem with that function?

**Comment by McKirni** [comment]
Well, you have built in the ability to disable the creation of a new cache. Because some users want to create a new cache by typing for a long time and others do not.
The same advantage is the possibility to disable the creation of a new waypoint.
For me, it is actually frustrating:
I move around on the map, zoom in and out ... and again and again the menu for creating a waypoint pops up because my finger was on a point a little too long.

**Comment by ztNFny** [comment]
I don't think this should be a new setting, but I'd expect the existing setting to turn on/off both the creation of new caches as well as waypoints with long click.

**Comment by Lineflyer** [comment]
> I move around on the map, zoom in and out ... and again and again the menu for creating a waypoint pops up because my finger was on a point a little too long.

How disturbing is this for you respectively how often does it happen?
Would it just be a "nice to have" or is it a real problem for you?

I am asking because we have this feature since years and never had any complaints as it only exists in this cache map context (in contrast to the live map long tap, which only therefore was made configurable).

While settings are nice to customize c:geo for each users we do not want to overfreight the settings with options for each and every occasion. This is mainly due to two reasons: Endless setting menus are not user friendly and all that options (and there possible interworking) need to be tested and maintained.

**Comment by McKirni** [comment]
As i said ... it happens again and again and again ... so yes, it is a real problem for me.
Until now I've used cgeo 2020.04.25 (because of Android 4.4) - in this version it was not possible to create new waypoints.
But with the new handy and the cgeo-update i was immediately confronted with the annoying create-waypoint-popup.
The solution from ztNFny (the existing setting to turn off an new cache tuns off a new waypoint too) sounds good.

**Comment by moving-bits** [comment]
A default value will only be applied on opening settings when the key being referred to does not yet exist. As we have extended the existing setting no default value will be applied, if the user has opened settings at least once in the past.

**Comment by bekuno** [comment]
If we stay with the now current behaviour, the strings "init_longtap_map", "init_summary_longtap_map", "onetime_info_longtap_disabled", "onetime_info_longtap_enabled" should be extended to cover also waypoints.

**Comment by moving-bits** [comment]
> That's kind of bad:
> 
> Now a previously out of the box existing feature (long tap to create cache waypoint on cache map) will be disabled for all existing users, who not previously explicitly enabled the generic "long tap on live map".

agreed, we've missed the upgrade-path

> I thought we agreed use a new setting key and set it to enabled to avoid that.

That would be two settings for nearly the same functionality. If we would have started "from scratch" I guess we would have chosen a single setting for both from the beginning (or no setting at all).

But you're right, starting from the situation as-is we need to think of an upgrade-path.

> BTW: I am still of the opinion, that those features should not be combined after all....

IMHO it's the same feature - long tap on regular map to create a cache vs. long tap on cache-map to create a waypoint. Can't think of a reason why someone is able to work correctly with one but has problems with the other (and therefore disables it).

**Comment by Lineflyer** [comment]
> That would be two settings for nearly the same functionality. If we would have started "from scratch" I guess we would have chosen a single setting for both from the beginning (or no setting at all).

No, I was just speaking about a single but new key, which can then default to active for all users.
I think @ztNFny has done this with his PR?!

**Comment by moving-bits** [comment]
> No, I was just speaking about a single but new key, which can then default to active for all users. I think @ztNFny has done this with his PR?!

Ah, hadn't checked the PR yet. A single new key, with default to "active" would enable the function for all users (which I would regard as a useful default for this) and thus bringing a "hiccup" only for those users, who had actively disabled the feature in the past. Nice.

**Comment by Lineflyer** [comment]
Follow-Up problem solved with #13023
