### ISSUE TITLE
[Map settings] Disable red distance rule circle for archived caches

### ISSUE THREAD

**Issue by MZCacheHunter** [cgeo/cgeo#12823]
### Tell us your idea!

The map offers a setting to display the cache locations with a distance rule circle (161 meters, 0.1 miles)
However, in the case of archived caches, the distance rule circle doesn't really make sense.
If those circles weren't displayed just for archived caches, the map would be clearer.

### What solution would you suggest?

There could be either a new setting switch to disable the distance circle for archived caches, or disable the circle for archived caches right away.

### Is there an alternative?

The only alternative would be filtering out archived caches altogether. This isn't satisfing if the location of former caches is still interesting to know.

**Comment by Lineflyer** [comment]
I agree: Archived caches should not be "circled".

**Comment by ddlatham** [comment]
Is there any way to get this back as an option?  It's helpful for Unknown caches to be able to narrow down where they could be, even based on caches which used to be there but are now archived.
