### ISSUE TITLE
Developer setting is visible in Non-Debug mode

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12830]
### Describe your problem!

A sevelopers-only setting is visible in nightly  (maybe even normal releases as well?)

![Screenshot_20220305_133801_cgeo geocaching](https://user-images.githubusercontent.com/64581222/156883617-5650cfcb-f450-462c-b2ec-6cdbf73d7005.png)

### How to reproduce?

Go into settings > system

(it's independent whether `debug` is enabled) 

### Expected result after these steps?

The setting should be hidden 

### Reproducible

Yes

### c:geo Version

2022.02.28-NB-aaac1d7

**Comment by fm-sys** [comment]
Just retested, it's also reproducible with today's nightly

**Comment by eddiemuc** [comment]
As the text states it is (only) visible in debug mode. It is not restricted to certain environments, and the text does not say so either.

So it is debatable whether this should be changed, but this is not a bug. Works as (originally) designed.

**Comment by fm-sys** [comment]
As written above, it's happening independent of whether debug is enabled or not. So it's definitely not the intended behavior...

**Comment by eddiemuc** [comment]
> As written above, it's happening independent of whether debug is enabled or not. So it's definitely not the intended behavior... 

Apologies, did not see this the first time. I changed issue title to make this clearer on first glance
