### ISSUE TITLE
NPE on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12846]
### Describe your problem!

Two user reporting, that the app crashes after updating to 2022.03.09 when trying to open the map.
Logfiles from user are requested.

Additionally I do see a significant amount of this (new!) crash on Play Console, which might be related:
```
java.lang.NullPointerException: 
  at cgeo.geocaching.maps.RouteTrackUtils.lambda$reloadTrack$19 (RouteTrackUtils.java:238)
  at cgeo.geocaching.maps.RouteTrackUtils.lambda$reloadTrack$19$RouteTrackUtils (Unknown Source)
  at cgeo.geocaching.maps.-$$Lambda$RouteTrackUtils$6TnbNEkUFq2c0CmC_heN1Jzl0nk.updateRoute (Unknown Source:6)
  at cgeo.geocaching.files.GPXTrackOrRouteImporter.lambda$doImport$2 (GPXTrackOrRouteImporter.java:49)
  at cgeo.geocaching.files.-$$Lambda$GPXTrackOrRouteImporter$_5oHk4GG8Dp5ykMjvvDuO0uXai8.run (Unknown Source:6)
  at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run (HandlerScheduler.java:123)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8633)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```

### How to reproduce?

Unclear

### Actual result after these steps?

Crash

### Expected result after these steps?

Normal operation

### Reproducible

Unclear

### c:geo Version

2022.03.09

### System information

```text
Android 11+12, Several devices
```

### Additional Information

Support ticket 129308

**Comment by alan666notb** [comment]
Note, I don't think this was introduced with 2022.03.09

I saw it many times yesterday before my phone updated itself to 2022.03.09 this morning.
I saw it again today, so the fault is at least in both the current and previous release.

**Comment by Lineflyer** [comment]
> ne updated itself to 2022.03.09 this morning.
> I saw it again today, so the fault is at least in both the current and previous release.

Then its maybe a different problem in your case as the NPE mentioned above should be only related to 2022.03.09.

When this crash happens next time, please go to Menu - Settings - System - "Generate logfile" and post it to a new issue.

**Comment by Lineflyer** [comment]
Another user with these symptoms on support mail.
It seems we introduced a bug for the map with the recent changes since 2022.02.16.

**Comment by alan666notb** [comment]
I opened a new issue as requested by @Lineflyer - #12848

**Comment by Lineflyer** [comment]
Two new reports on support with map starting crash on 2022.03.09. Logfiles requested.

**Comment by fm-sys** [comment]
At least on my device, the crash is gone with 2022.03.10-NB1

**Comment by fm-sys** [comment]
@Lineflyer The PR does most likely fix the crash, and at least can't do any harm. Do you have time to do a new bugfix release? We should try to be as fast as possible, so that users have a working geocaching app this weekend :)

**Comment by MagpieFourtyTwo** [comment]
@alan666notb 
> (...) before my phone updated itself to 2022.03.09

OffTopic: Did I miss something (like AutoUpdate?) or is "updated itself" just an - at least for me - possibly misleading wording ...?

**Comment by alan666notb** [comment]
> OffTopic: Did I miss something (like AutoUpdate?) or is "updated itself" just an - at least for me - possibly misleading wording ...?

Just the normal Google play store update.

**Comment by Lineflyer** [comment]
> @Lineflyer The PR does most likely fix the crash, and at least can't do any harm. Do you have time to do a new bugfix release? We should try to be as fast as possible, so that users have a working geocaching app this weekend :)

Yep..will do it.

**Comment by moving-bits** [comment]
> Yep..will do it.

I have updated `changelog_bugfix.md` already. How would I have to trigger Crowdin, if it doesn't catch up automatically?

**Comment by fm-sys** [comment]
@Lineflyer The PR does most likely fix the crash, and at least can't do any harm. Do you have time to do a new bugfix release? We should try to be as fast as possible, so that users have a working geocaching app this weekend :) 

> I have updated `changelog_bugfix.md` already. How would I have to trigger Crowdin, if it doesn't catch up automatically?

It can be triggered on [this Crowdin page](https://crowdin.com/project/cgeo/apps/system/github), however I don't seem to have the permissions to do so...

**Comment by Lineflyer** [comment]
All done now.

**Comment by Lineflyer** [comment]
> @alan666notb
> 
> > (...) before my phone updated itself to 2022.03.09
> 
> OffTopic: Did I miss something (like AutoUpdate?) or is "updated itself" just an - at least for me - possibly misleading wording ...?

Offtopic reply:
You can configure Google Play to autoupdate certain apps. Up to my experience those users really receive the update right away while for other users it depends on some kind of lazy updating the index in the Google Play app (meaning it might take some hours or manual intervention to see the update being available).

**Comment by MagpieFourtyTwo** [comment]
@alan666notb 
> Just the normal Google play store update.

Ah, IC. Was already dreaming of an AutoUpdating Nightly ... ;)
