### ISSUE TITLE
GCVote broken, possibly remove it?

### ISSUE THREAD

**Issue by Vike91** [cgeo/cgeo#12840]
Hi! I translated the wiki into Finnish again and noticed that the GCVote is not working anymore, not in c:geo, nor on the browser.

On http://gcvote.com/, they have announced that they might not be able to update it anymore. 

On http://gcvote.com/index_en.php, they say they are trying to fix it, and the problem is temporary.

The bottom line is the GCVote is not working on c:geo anymore. Should it be removed? What do you think?

**Comment by SammysHP** [comment]
The API is still working or have you experienced something different?

See #9664 for a replacement service.

**Comment by Vike91** [comment]
I need to confirm this with the developer. I want to hold this issue, please. I'll return when I have more info.

**Comment by Lineflyer** [comment]
I can confirm, that the API is still working  but we have confirmation about no more development work and it can stop anytime. As its currently still implemented we should leave it in the user guide. This will also make it easier once the replacement service has been integrated.

**Comment by SammysHP** [comment]
So still the same situation as in #11487.

**Comment by Vike91** [comment]
Sorry, I should have searched for topics of this issue.

**Comment by SammysHP** [comment]
Better twice than never. ;)
