### ISSUE TITLE
Avoid repetitive translation for changelog header

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12852]
From Crowdin a user provided the idea, whether it would be possible to split the version number/name from the string `bugfix release`. This would allow a one time translation of the string and thus no more need for repetitive translation of the whole header short before a bugfix release occurs.

@moving-bits 
I could imagine, that we either skip keeping older changelogs in `changelog_bugfix.md` and only collect the changes for the next bugfix release. In such case the header could be constructed internally (like we do for feature releases).

Another possibility would maybe to use dedicated files for reach bugfix release (e.g. `changelog_20220310.md`) and then construct the header from the file name (which contains the version date) and just append the content. This could be done sequentially for all existing `changelog_*` files.

What do you think?

**Comment by moving-bits** [comment]
@Lineflyer 
Please see #12853 for a proposal
