### ISSUE TITLE
FYI: APK size increased significantly 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12856]
Some days ago I noticed, that the cgeo APK recently got significantly bigger.

![Screenshot_20220313_215014_com android documentsui](https://user-images.githubusercontent.com/64581222/158078963-a0783c3b-a7c2-42dc-aede-ab2c6cdb09fd.png)

It's not necessarily a problem, but 10 MB -> 20 MB (+100%) looks like a quite huge step to me. It would at least be interesting, what caused this rapid growth.

**Comment by Lineflyer** [comment]
That should indeed be investigated. Need to look through the nightlies on what date it started.

**Comment by fm-sys** [comment]
The first affected nightly was `2022.03.03-NB`

https://ci.cgeo.org/job/cgeo%20nightly/2584/ 

The commit which has most probably caused this was the introduction of the  `EmojiCompat` library (5e7b94fce39af6b4b47ef760b0f335a9cc36d703) 

@bekuno could you explain the reason, why/if this compact library is really needed?

**Comment by bekuno** [comment]
You see the problematic emoji here: https://github.com/cgeo/cgeo/issues/12471#issuecomment-1007813268

**Comment by bekuno** [comment]
We can switch from "Bundled fonts configuration" to "Downloadable fonts configuration", see https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat#how-does-emojicompat-work.
