### ISSUE TITLE
[Coordinate calculator] Paste from clipboard is unreliable 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12867]
### Describe your problem!

There is the feature "past from clipboard" when opening the new WP calculator. 

However, 3/4 of all coordinates pattern where not recognized. This should be improved... 

### How to reproduce?

A collection of some unrecognized patterns:

```
N 49° 53.(H+1) (H-A) (B-2) 
E 008° 37. (B) (C) (H-1) 
```

```
N 49° (A + 42).0(B + 10)
E 008° (C*6 + 2).(D + 256)
```

```
[N 49° 4(A-1).(B*50+85)]
[E 008° (B+C+A).(D+45)]
```

There are probably much more situations, where the regex does fail... Feel free to add more examples. 

### Actual result after these steps?

A toast "no pattern found" is shown. 

### Expected result after these steps?

The patterns should be detected correctly. 

### Reproducible

Yes

### c:geo Version

2022.03.17-NB-6be5345

**Comment by eddiemuc** [comment]
True, current implementation is very basic and not tuned to recognize more advanced formulas. Back then I asked @ztNFny whether we might adapt his probably more advanced algorithms here.

For those interested in diving into this, here are the pointers to implementation:

* scan function is implemented by `FormulaUtils.scanForCoordinates`
* Unit tests can be found in class `FormulaUtilsTests`, all test methods starting with `scan(For)Coordinates`

**Comment by ztNFny** [comment]
> Back then I asked @ztNFny whether we might adapt his probably more advanced algorithms here.

Sorry I don't have anything available that could be used as-is here. My implementation is quite specific to a certain usecase and can't reasonable be adapted. The main replacement stuff you already added iirc.

**Comment by fm-sys** [comment]
> True, current implementation is very basic and not tuned to recognize more advanced coordinate formulas.

What about making it even more basic?

E.g.
```
(?<=\s|^)([NnSs][0-9\s][\S\s]+?)[^A-Za-z]([WwOoEe][0-9\s][\S\s]+)
```

We can use a more advanced parser before, but if no pattern was found this regex could help to catch 99% of all edge cases where the advanced parser would fail...

What do you think?

**Comment by fm-sys** [comment]
OT: Can we please save one click in this workflow?

"Remove spaces" is only needed if the text fields are not empty, while "past from clipboard" will most likely only be used if the text fields are empty anyway. 

![Screenshot_20220329_200138_cgeo geocaching_copy_714x246](https://user-images.githubusercontent.com/64581222/160676222-ec250b38-e221-4290-b856-d76294ca463f.png)

**Comment by ztNFny** [comment]
@eddiemuc could you add some comments to the regex' used in FormulaUtils as to how they are used? There's so many string concatinations in there and I don't really get why they exist.
For retrieving the final regex value I just set a breakpoint to get it, seemed easier than doing all that contact manually ;-)

**Comment by ztNFny** [comment]
It's not about the regex itself but the way it's built. Like I'm sure you had a good reason to built it the way you did - I'd rather not throw that away, but am having a hard time getting it.
And without getting the purpose reading that long a regex aint trivial ;-)

F_FORMULA
((\h*\(\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7})(((\h*[()]\h*)*(\h*[-+/:*x]\h*)+)(\h*[()]\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7}))+(\h*\)\h*)*)
FORMULA_SCAN_PATTERN
[^a-zA-Z0-9(]((\h*\(\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7})(((\h*[()]\h*)*(\h*[-+/:*x]\h*)+)(\h*[()]\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7}))+(\h*\)\h*)*)[^a-zA-Z0-9)]
COORDINATE_SCAN_DIGIT_PATTERN
((((\h*\(\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7})(((\h*[()]\h*)*(\h*[-+/:*x]\h*)+)(\h*[()]\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7}))+(\h*\)\h*)*)|[0-9a-zA-Z]{1,3})\h*([°'\".]\h*)?){1,6}
COORDINATE_SCAN_PATTERN
(?<lat>[nNsS]\h*[0-9]((((\h*\(\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7})(((\h*[()]\h*)*(\h*[-+/:*x]\h*)+)(\h*[()]\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7}))+(\h*\)\h*)*)|[0-9a-zA-Z]{1,3})\h*([°'\".]\h*)?){1,6})\h+([a-zA-Z]{2,}\h+)*(?<lon>[eEwWoO]\h*[0-9]((((\h*\(\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7})(((\h*[()]\h*)*(\h*[-+/:*x]\h*)+)(\h*[()]\h*)*([a-zA-Z][a-zA-Z0-9]{0,2}|[0-9]{1,10}|[0-9]{1,3}\.[0-9]{1,7}))+(\h*\)\h*)*)|[0-9a-zA-Z]{1,3})\h*([°'\".]\h*)?){1,6})

**Comment by Kumuddel** [comment]
May I add a couple of examples, where the coordinate patterns were not recognized? BTW I love the calculator!

https://coord.info/GCW1GJ 
N 48° 04.ABE,
E 11° 56.DEB.
If I copy from listing, it does not work. If I paste first into north field and copy again it is recognized. Maybe CR/LF-Problem?

Same cache
N 48° 0B.(2x C)(2x C)(2x C),
E 11° BB.(G+H)DF
x ist not recognized as multiplication.

Same cache
N 48° 0B.0(I+J*D),
E 11° BB.D(J/4)D
Works only without comma after north.
