### ISSUE TITLE
How to reset the Cache number in log signature?  its not right.

### ISSUE THREAD

**Issue by deltamelter** [cgeo/cgeo#12879]
### Describe your problem!

found just under 1400 caches and have the c:geo feature to add Cache number as signature on logs
The counter is somehow nearly 1700 now, so have to manually edit which means going back to home screen to se the true current number, then going back into cache log to correct the number.
Where is this stored? how do I reset the counter so that is increments correctly?  I log mostly offline, sending the drafts to gc, usually to correctly the number there instead, but it's very easy to forget.

### How to reproduce?

I wish I knew.  Only thing I can think of that changed is that I started using nightly build for a different fix.  Don't know when exactly this started going wrong, but last year May probably

### Reproducible

No

### c:geo Version

2022.03.11-NB-52231b5

### System information

```text
Samsung S21
Android 12
```

**Comment by eddiemuc** [comment]
Will the counter reset if you create one new log while being online (e.g. connected to gc.com)?

**Comment by Lineflyer** [comment]
Is it possible that you have many stored offline logs?

**Comment by deltamelter** [comment]
> Is it possible that you have many stored offline logs?

Yes, I notice now that the home screen says 1377 finds + 326 logged offline
But all those logged offline were exported and submitted online.  So how do I clean up these offline logs?

**Comment by deltamelter** [comment]
> Will the counter reset if you create one new log while being online (e.g. connected to gc.com)?

No, the phone is usually connected and GC logged in.  We had some extended caching without phone signal and got used to logging offline, but this week logged all but 2 "live"

**Comment by Lineflyer** [comment]
Please follow the instruction to get rid of these offline logs...then the log counter should match again: https://www.cgeo.org/faq#offlinecount

**Comment by deltamelter** [comment]
Thanks, Found that they are all premium caches that I logged before the pandemic.  Since cancelled premium and now can't clear them because the the API refuses to give cache details of premium caches.
I'll see if I can manually clear all the offline found logs.
