### ISSUE TITLE
Exclude Adventure Cache finds from [NUMBER] 

### ISSUE THREAD

**Issue by bbarao** [cgeo/cgeo#12882]
I done a few Adventure Caches, and my number of finds went up unexpectedly. I then understood that every step of the adventure caches was counting as a find.

Is it possible to have a [CACHENUMBER] (or other name) that excludes adventure caches and only counts the "normal" ones?

**Comment by ztNFny** [comment]
GC counts each stage of a lab as a find, there's no distinguation between them. Cgeo gets the found caches from GC and that includes your labs, there's no second counter without them.
