### ISSUE TITLE
bug: duplicate WP with formula has same formula

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#12884]
I copied a waypoint with a formula.
I wanted to make several waypoints with several values for one variable.

If I edit the formula in one waypoint the formula in the other gets edited too. Seems like there is only one formula and values.

**Comment by eddiemuc** [comment]
The variables are global, so if you edit one vars value in one waypoint it will change for all waypoints (and in the var tab as well). This is intended.

Or do you mean something else?

**Comment by geocachermgo** [comment]
I could unterstand that and was assuming global variables and changed the formula from n*160 in the first waypoint to m*160 in the second.
My idea was to have m*160 and m=3 in one waypoint and n*160 and n=4 in the other.
But when I edited the formula in one waypoint, also the formula was changed in the second waypoint.

**Comment by geocachermgo** [comment]
I saw that there some remains on the page left of the waypoint page. I did'nt use, watch or changed something there but only edited the waypoint by the "(x) Koordinate berechnen" editor.

**Comment by geocachermgo** [comment]
I guess the remains are the cause: I had intermediate variables: 
The given formula was N 48° 57.((100*N)-50+N) E 009° 03.(160*N).
so I created as waypoint @P1 (F) {CC|N48° 53.x__'|E009° 08.y__'|DMM} and the formulas $x=100*n-50+n | $y=160*n | $n=3.
In the second waypoint I used the same intermediate variables x,y .The change of the formula was copied to the first waypoint.
 $x=100*m-50+m | $y=160*m | $m=4.
So to do this, I should have also changed the intermediate formula. @P2 (F) {CC|N48° 53.u__'|E009° 08.v__'|DMM} and  $u=100*m-50+m | $v=160*m | $m=4.
Surprising for me but I guess unavoidable if the waypoint should share variables.

**Comment by eddiemuc** [comment]
Yes, using same intermediate vars would cause this. To the system this is like defining the same variabe twice, so one definiting will overwrite the other.

If this is a more general use case, I don't know a really good solution currently. In your case you could maybe define a range variable `m` with value range `[3;4]` and use this to generate waypoints.

**Comment by eddiemuc** [comment]
BTW: from what you write I have the impression you use manily the personal notes to define variables and calculated waypoints, instead of using the respective dialogs. Is this correct?

Since the personal notes are free text we can't hinder users to define same var multiple times there. But when this is scanned and ready into the systems, it is resolved as I said in earlier comment: only one definition "wins". I also believe that import will not overwrite an existing variable formula if one already exists

**Comment by geocachermgo** [comment]
No, I used the menu at the single waypoints but not the dialog at the page left of the waypoints. I did not edit the exported text  in the note and reimported it.
Even if the waypoints are deleted, the varaiables and the formulas are kept.

Ok. I use normally Plausibär but managed it now with cgeo range [3-4] and the button "Wegpunkte erzeugen". I'll close this issue.
Thanks for the support.

**Comment by eddiemuc** [comment]
I didn't konw plausibär before. Thanks for the info :-)

**Comment by geocachermgo** [comment]
It's a feature not a bug. I assumed waypoint spanning identity for values but not for formulas. But that concept requires that only one definition of a variable exists, including formulas.
Discussion was helpful anyway since I learned about the "range" + create wapoint and eddiemuc about plausibär.
