### ISSUE TITLE
"Filter"-icon in toolbar in offline map

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12906]
### Tell us your idea!

Live map shows 2 more icons than an offline (list) map: Filter and Live

The filter icon would be great to have also for offline maps.

### What solution would you suggest?

Add the filter icon to all map views, not just live map

### Is there an alternative?

On offline map from overflow-menu enable live mode -> the 2 toolbar buttons show up, Disable Live again, now use the fitler button

**Comment by wolverine007** [comment]
Could you kindly add screenshots?

I have the same set of buttons in the top navigation bar on both map types:

![Screenshot_2022-04-18-01-34-32-437_cgeo.geocaching.jpg](https://user-images.githubusercontent.com/4508228/163736234-94be6d78-858b-4c90-84ff-991b40f1c3cf.jpg)

![Screenshot_2022-04-18-01-34-59-146_cgeo.geocaching.jpg](https://user-images.githubusercontent.com/4508228/163736236-31a5991a-97a5-4064-8660-6aeae9a2b917.jpg)

**Comment by fm-sys** [comment]
I agree that the filter icon has IMHO more value than the list name and should be always shown...

|||
-|-
![Screenshot_20220419_101126_cgeo geocaching](https://user-images.githubusercontent.com/64581222/163957192-eb0869ee-1558-4d3b-a5a5-070438cdc14c.jpg)|![Screenshot_20220419_101207_cgeo geocaching](https://user-images.githubusercontent.com/64581222/163957201-192bbe7e-cae9-40b0-88e6-91f6ecf33cd6.jpg)

**Comment by SammysHP** [comment]
The difference is the back/up button shown in the action bar.

**Comment by ztNFny** [comment]
The third button is also not shown when there's plenty of room. I remember we hacked live map to show up to 4 buttons as Android by default only shows up to 2. The same hack should be added to the list-map.

**Comment by fm-sys** [comment]
Exactly. BTW, this hack was implemented way before we have switched to the bottom navigation. So we had shown the filter icon together with the back button on the live map. 

https://github.com/cgeo/cgeo/blob/7878b3437e9d353e0a5f0bc6a98e16566b10851d/main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java#L386-L388

**Comment by ztNFny** [comment]
> Exactly. BTW, this hack was implemented way before we have switched to the bottom navigation. So we had shown the filter icon together with the back button on the live map.

Thanks, that's just the pointer I needed. From what I can tell `isStoredEnabled` is never true in onPrepareOptionsMenu and other than that used only in handleStoredLayers() where it's not really needed.
I'll look into removing `isStoredEnabled` and enabling the 4-button-actionbar on all map views - assigning the ticket to myself.

**Comment by ztNFny** [comment]
`isStoredEnabled` is also used to enable the display of all stored caches on map. It's set to true when enabling live map and never disabled again afterwards. So that has to be kept.
