### ISSUE TITLE
Include link "Create new log in browser" (pre-solution for full support of multiple log profiles)

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12912]
### Tell us your idea!

I often want to log caches I found for other, non-premium accounts too (those of my kids). I usually do this by logging in into my browser as the other account. Then I log for myself using c:geo, then I open the same cache in Browser using c:Geo's "open in browser" action and create a log there for the other account.

This workflow forces me to do some more clicks than I like, but it works ok-ish for non-premium caches. For premium caches, however, it doesn't work very well, because I have to do URL magic for the other, non-premium account to be able to log in browser.

### What solution would you suggest?

The big solution for this would be to enable "log profiles" in c:geo - some sort of auto-logging feature for "secondary accounts" which could be enabled in the log entry activity. However, this issue is about something else.

My request would simply be to include a link "Create new Log in Browser" next to the already existing "Open in Browser" action. This action would open a new log entry screen in the Browser directly. This should also work if another (non-premium) account is currently logged in into the browser)

### Is there an alternative?

Full-blown log profile solution.
Or do nothing of course

**Comment by Lineflyer** [comment]
That's IMHO very specific and in this use case requires another user to be logged in in your browser session, etc. etc.
Additionally you can still use "Open in browser" and logging is the one click away.

I think it will more confuse users to see another menu to log in browser....we want users to log with c:geo.

**Comment by eddiemuc** [comment]
> Additionally you can still use \"Open in browser\" and logging is the one click away.

This is the workaround I currently use. But as mentioned above: this does not work for premium caches if the secondary user is a basic member (which is usually the case).

I believe the use case of logging for secondary users is a real one, and the main user (myself) will always log using c:geo. The solution proposed here is a quick hack for this. 

A more advanced solution would be to enable c:geo to manage multiple accounts for each provider, then allow to log for multiple accounts at once. But this is maybe too much work for this use case.

**Comment by Lineflyer** [comment]
> This is the workaround I currently use. But as mentioned above: this does not work for premium caches if the secondary user is a basic member (which is usually the case).

Ok, indeed it will not work if the second account is a basic member. I did not think of this. So its a bit related to the hack we already have, that when a basic user tries to open a PM cache we offer a direct log link instead.

> I believe the use case of logging for secondary users is a real one, and the main user (myself) will always log using c:geo. The solution proposed here is a quick hack for this.

Yes, then its probably a much better solution than a full blown multi account support.
