### ISSUE TITLE
Allow selection of individual text inside log entries

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12911]
### Tell us your idea!

C:geo allows selection of individual text inside Cache listings, but not inside log entries (only selection of whole text of a log entry). C:geo should allow selection of individual texts inside logs too. 

This would help me greatly e.g. to reselect a part of a log I just wrote to include in my next log (e.g. a common header for all logs of one day which I forgot to store in clipboard before posting or which was kicked out of clipboard by another selection in the meantime)

### What solution would you suggest?

C:geo should allow selection of individual texts inside logs too. 

### Is there an alternative?

Do nothing

**Comment by ztNFny** [comment]
When writing your log in the menu there's "repeat last log" which might be an easier way to address your specific usecas

**Comment by fm-sys** [comment]
> When writing your log in the menu there's "repeat last log" which might be an easier way to address your specific usecas


There are many other reasons why someone might want to select text of a log. I sometimes need this myself.

Currently I copy the whole log into the caches PN and can select individual parts there. But allowing individual text selection for logs would be great.

**Comment by alan666notb** [comment]
Yes, I would like this as well.
And also I'd like to be able to search for (i.e. google) or translate the selected text.
