### ISSUE TITLE
Unified map: Integration into CacheDetailActivity and CacheListActivity

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12926]
### Missing functionality

- [ ] support mapOptions
- [ ] switchable integration into `CacheDetailActivity`
- [ ] switchable integration into `CacheListActivity`

**Comment by ztNFny** [comment]
When implementing this could you maybe take a look at enabling the list-switch directly from map instead having to go back to lists? Not sure whether that's feasible ...

**Comment by moving-bits** [comment]
> When implementing this could you maybe take a look at enabling the list-switch directly from map instead having to go back to lists? Not sure whether that's feasible ...

Not sure how much refactoring that would be. AFAIK we open the map with a set of geocodes and a info string. To enable the requested feature the map must somehow recognize that it's currently displaying the contents of a list, offer list switching and reload the set of geocodes when a different list gets selected.

**Comment by moving-bits** [comment]
Switchable integration should be based on #12975

**Comment by moving-bits** [comment]
This has been implemented meanwhile, at least in a basic fashion, so let's close this general issue (and open more detailed issues, if needed).
