### ISSUE TITLE
Unified map: Add map rotation controls for VTM

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12925]
### Missing functionality

VTM (mapsforge) only:

- bearing indicator (rotating compass rose)
- tap bearing indicator to reset heading to north (working the same way as in today's Google Maps)

**Comment by moving-bits** [comment]
@ztNFny 
I wonder if you could create a SVG file for VTM compass rose, similar to the existing one of Google Maps:

![image](https://user-images.githubusercontent.com/3754370/168664860-dedec36f-6ea7-4051-be5c-4c56211dce9f.png)

**Comment by ztNFny** [comment]
> @ztNFny I wonder if you could create a SVG file for VTM compass rose, similar to the existing one of Google Maps:
> 
> ![image](https://user-images.githubusercontent.com/3754370/168664860-dedec36f-6ea7-4051-be5c-4c56211dce9f.png)

Putting it on my to-do list. Please start with a placeholder and I'll do a PR to replace that then.

**Comment by moving-bits** [comment]
> Putting it on my to-do list. Please start with a placeholder and I'll do a PR to replace that then.

Thanks, will do so.

**Comment by ztNFny** [comment]
Do you already have something in code? I have an initial design but need to put it on a map to actually test and tweak it.

**Comment by ztNFny** [comment]
You can use this for now, i'll then tweak it ![compass](https://user-images.githubusercontent.com/1258173/168886068-7ca75c78-5efb-4fbe-bb85-3177f0c746bb.svg)

**Comment by moving-bits** [comment]
Thanks, will try to add the code over the next days.

**Comment by moving-bits** [comment]
Hm, I'm still struggling with Android Studio... After having updated to the latest bugfix release, most of the classes aren't detected any longer and colored in red. Compiling works, but no "jump to class definition", no completion for class methods etc. Spent quite some time with deleting caches and cache folders, but to no avail so far :-(

**Comment by ztNFny** [comment]
> After having updated to the latest bugfix release, most of the classes aren't detected any longer and colored in red

Usually File > Invalidate caches solves that

**Comment by moving-bits** [comment]
> > After having updated to the latest bugfix release, most of the classes aren't detected any longer and colored in red
> 
> Usually File > Invalidate caches solves that

Had tried that, but to no avail. Also tried deleting a couple of different cache folders (build cache, gradle cache, ...), but still not working... :-(

**Comment by moving-bits** [comment]
reinstalling Android Studio BumbleBee 2021.1.1 Patch 3 did the trick - 2021.2.1 did not work for me

**Comment by fm-sys** [comment]
> Hm, I'm still struggling with Android Studio... After having updated to the latest bugfix release, most of the classes aren't detected any longer and colored in red. Compiling works, but no "jump to class definition", no completion for class methods etc. Spent quite some time with deleting caches and cache folders, but to no avail so far :-(

Today I've upgraded as well and had the same problem. However, using "File > Invalidate Caches... > Invalidate and Restart" fixed the issue for me...

**Comment by moving-bits** [comment]
> Today I've upgraded as well and had the same problem. However, using "File > Invalidate Caches... > Invalidate and Restart" fixed the issue for me...

Sadly this did not work for me, had tried it several times (as it has worked indeed in the past). But anyway, 2021.1.1 is still good to go. Will check with some update whether it'll be back working for me.
