### ISSUE TITLE
show "spoiler image" text on hint only if that's a spoiler image 

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12938]
If the listing contains ANY image cgeo will show the text "spoiler image" next to the hint.
This should only be shown if there's an image marked as spoiler in the listing.

Many times already i clicked the link, hoping for a spoiler image, only to be presented with the background image or the checker icon. The existence of those is already indicated by the images tab

**Comment by ztNFny** [comment]
Looking at the source code I've found that methods like Geocache.getSpoilers() return all images and not just spoiler images - and it seems like it has been like this "forever".
@Lineflyer @moving-bits do you have any idea why (at least for GC) ALL images are added as "spoiler" (e.g. GCParser:663) instead of (as I would have expected) treating images marked as spoilers and "normal" listing images/background images seperately?

**Comment by Lineflyer** [comment]
Thats IMHO easy to answer. There is no designated marking for spoiler images on geocaching.com. So you cannot know whether it is just some image or a real spoiler.

**Comment by ztNFny** [comment]
there isn't? but ... oh, that's GClh marking images as spoiler. They're using the title to guess whether an image is a spoiler.

In any case I find c:geos current behaviour wrong. As soon as any image (other than a background image) is detected next to the hint a text "spoiler image" is shown, bringing you to the images tab. If we can't tell whether there are spoiler images then the text should not say "spoiler images" but just "images" or something.

**Comment by ztNFny** [comment]
Ideas for identifying spoiler images (for GC):
- Image title / description contains "spoiler/hint/Hinweis/..." (this is what GClh uses)
- Image is an attachment image not used in the listing

**Comment by eddiemuc** [comment]
For the second option "Image is an attachment image not used in the listing" I looked into an example cache listing.

**Analysis**

I used https://coord.info/GC1HEBH. This is a typical side using attachment images which are also displayed in the listing. E.g. the image "Fischerprüfung" is also shown in the listing:

![image](https://user-images.githubusercontent.com/6909759/168005616-7c42bcbe-d68c-4e6d-ad73-a28ae07290b2.png)

![image](https://user-images.githubusercontent.com/6909759/168005708-6635b9cc-aea5-4d19-a668-967093076786.png)

In HTML source the two URLs used are only slightly different (attachment references "large" version of image, embedded image does not):
* Image embedded in listing: `<img src="http://img.geocaching.com/cache/18a9e1fc-9d5b-4089-91b3-ffb28699c702.jpg" width="500px" />`
* Image as attachment:  `<a href="https://img.geocaching.com/cache/large/18a9e1fc-9d5b-4089-91b3-ffb28699c702.jpg" rel="lightbox">Fischerprüfung</a>`

In c:geo image gallery the image is displayed two times:

![image](https://user-images.githubusercontent.com/6909759/168006507-9d766572-531b-4e3d-a7e3-4e970aa3e6b7.png)

As of today, the GCConnector does not differentiate between the two, both are delivered as images to c:geo core. THe information whether the image is an attachment or from listing is not passed.

**Solution possibilities**

What we could do:
* We could introduce a new image category LISTING_ATTACHMENT and make the connector(s) differentiate between the two
* For spoiler view we could filter out displayed images by ignoring the "large" in URL comparison
* We could in general (not only for spoiler images) filter out duplicate images in image gallery this way...

**Comment by Lineflyer** [comment]
> For spoiler view we could filter out displayed images by ignoring the "large" in URL comparison

AFAIK its purely up to the owner, whether he uses the link to the large or normal image in his cache description.

As stated some posts before, I also think that the special condition of a possible spoiler is, whether the file name of the image is used within the cache description (-> its a listing image, so potentially no spoiler) or not (-> could most likely be a spoiler or some additional image only viewable on the page by clicking the link to it).

**Comment by eddiemuc** [comment]
See PR #13005
