### ISSUE TITLE
add support for amazfit bip u pro

### ISSUE THREAD

**Issue by hartunic** [cgeo/cgeo#12946]
### Tell us your idea!

Make cgeo work with amazfit bip u pro and display details like distance  in feet and miles

### What solution would you suggest?

Should show the distance

**Comment by Lineflyer** [comment]
What is "amazfit bip u pro"? Any links to technical details and programming interface appreciated.

**Comment by hartunic** [comment]
> What is "amazfit bip u pro"? Any links to technical details and programming interface appreciated.

Is a smart watch

**Comment by moving-bits** [comment]
Duplicate of #12920, therefore closing here

**Comment by moving-bits** [comment]
If you want to provide any additional info on interfacing with this specific smart watch, please do so in the already existing issue (#12920)

**Comment by SammysHP** [comment]
Not sure if it's a duplicate because the Amazfit is not a Wear device and uses its own SDK (although I don't know if it's already accessible for everyone).
