### ISSUE TITLE
https://fdroid.cgeo.org/nightly/index-v1.jar wrong repository url in json repo.address

### ISSUE THREAD

**Issue by k3b** [cgeo/cgeo#12940]
### Describe your problem!

The F-Droid-Catalog cgeo-nightly https://fdroid.cgeo.org/nightly/index-v1.jar has the wrong url in field repo.address

### Expected 

repo.address="https://fdroid.cgeo.org/nightly"
 (so that the catalog can be downloaded from https://fdroid.cgeo.org/nightly/index-v1.jar)

### Actual (tested on 2022-04-28)

repo.address="https://fdroid.cgeo.org"

wrongly claiming that the catalog can be downloaded https://fdroid.cgeo.org/index-v1.jar

This actually the url of cgeo-mainline and not of cgeo-nightly

-----

The content of cgeo-mainline is ok
i have not tested with https://fdroid.cgeo.org/legacy for legacy builds

---

I am currently developping a new f-droid-compatible store.
I analysed why cgeo-nightly suddenly changed to  cgeo-mainline

### How to reproduce?

* download https://fdroid.cgeo.org/nightly/index-v1.jar 
* unzip index-v1.jar to index-v1.json
* reformat the index-v1.json (using vscode)
* look at repo.address

### Reproducible

Yes

### c:geo Version

build server problem. not related to c:geo Version

**Comment by Lineflyer** [comment]
@kumy Could you check this issue?

**Comment by kumy** [comment]
Will check soon

**Comment by kumy** [comment]
Fixed. Only `nightly` was impacted.
```
$ curl -Ss https://fdroid.cgeo.org/index-v1.jar -O
$ unzip -p index-v1.jar index-v1.json  | jq '.repo.address'
"https://fdroid.cgeo.org/"

$ curl -Ss https://fdroid.cgeo.org/nightly/index-v1.jar -O
$ unzip -p index-v1.jar index-v1.json  | jq '.repo.address'
"https://fdroid.cgeo.org/nightly"

$ curl -Ss https://fdroid.cgeo.org/legacy/index-v1.jar -O
$ unzip -p index-v1.jar index-v1.json  | jq '.repo.address'
"https://fdroid.cgeo.org/legacy/"

```
