### ISSUE TITLE
Map scaling: Scale bar needs to scale as well

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12972]
### Describe your problem!

When setting map scaling to 200%, leaving the other two scaling options unchanged, the whole map scales at factor 2, which is to be expected. Only the scale bar in the lower left corner does not change, therefore indicating twice the size:

|unscaled|map scaled to 200%|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/167271680-396e8ddf-d3b7-4597-8a02-a658632b438a.png)|![image](https://user-images.githubusercontent.com/3754370/167271688-b85fa1ad-46ab-4557-b559-8f86090c6454.png)|

(See the "Berliner Schloss" in the lower left part of the map)

### How to reproduce?

- open Mapsforge offline map
- set theme option to "scale map=200%", "scale text=100%", "scale symbols=100%"

### Actual result after these steps?

according to the scale bar all streets, buildings etc. have doubled length/width

### Expected result after these steps?

the scale bar needs to adjust its values according to map scale or needs to scale itself by the same factor

### Reproducible

Yes

### c:geo Version

current nightly

### Additional Information

VTM scales the whole scale bar in this case:

![image](https://user-images.githubusercontent.com/3754370/167271873-08188590-30bb-4abf-b33d-b13cf654cb6c.png)

(not sure if I like that one, though - scale bar gets quite clumsy...)

**Comment by eddiemuc** [comment]
Fixed with PR #12974
