### ISSUE TITLE
Image is jumping in new image gallery 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12970]
### Describe your problem!

![GIF-220506_201938](https://user-images.githubusercontent.com/64581222/167196059-3f8a2294-b02b-4be6-b411-1e4c4cfe201d.gif)

### How to reproduce?

- Open the single picture image view
- click somewhere on the screen 

### Actual result after these steps?

The image is jumping a bit up and down... 

### Expected result after these steps?

The image should stay calm.

### Reproducible

Yes

### c:geo Version

2022.05.06-NB-a534d0b

### Additional Information

This can be fixed by using an AndroidX toolbar component ontop of the imageviewer.

**Comment by eddiemuc** [comment]
Animation behavior is not implemented yet for new image view. Jumping might be due to setting surrounding Textview s from visible to gone in one step. But I haven't investigated this yet any further.

**Comment by Lineflyer** [comment]
In fact when scrolling up or down in this view it closes the view. Is that intentional?

**Comment by eddiemuc** [comment]
> In fact when scrolling up or down in this view it closes the view. Is that intentional?

Closing on scrolling down intentional (an aspect specifically supported by loupe). Closing on scrolling up would be a bug imho

**Comment by fm-sys** [comment]
> In fact when scrolling up or down in this view it closes the view. Is that intentional?

It's the same behavior as in the Whatsapp image viewer. However, it would be cool if we could implement the same transparent effect as it is done in Whatsapp... Currently, the feature is kinda unexpected.

**Comment by eddiemuc** [comment]
Following Animations are missing and should be implemented imho:
* When tapping an image in Image list, it should animate towards it's bigger detsils view
* When detail view is closed (regardless on whether via back button or fling-down) the shown image should animate towards it's equivalent in list view
* When Image is tapped in details view then surrounding text views should animate out/in instead of just vanishing/appearing
* Detail pager should be endless, e.g. when flinging left-to-right on first image it should change to last image in list and vice versa


Well, that's my personal wish list. Some of those might be complex, maybe even requiring bigger parts of current implementation to change. We will see...

**Comment by eddiemuc** [comment]
Animation behaviour as described above is implemented with PR #12981

**Comment by fm-sys** [comment]
Maybe we can make the Toolbar / Action Buttons fixed... Just thinking. 

|Most gallery apps|current cgeo implementation|
-|-
![GIF-220510_004721](https://user-images.githubusercontent.com/64581222/167513887-21a8be3b-1299-430c-8ccf-e2a322695890.gif)|![GIF-220510_004313](https://user-images.githubusercontent.com/64581222/167513893-c2c329d5-0b81-475c-84d4-939158624453.gif)

**Comment by eddiemuc** [comment]
> Maybe we can make the Toolbar / Action Buttons fixed... Just thinking.

This was done meanwhile.

I believe this issue can be closed, the jumping should not happen anymore with new implementations done on weekend

**Comment by fm-sys** [comment]
> > Maybe we can make the Toolbar / Action Buttons fixed... Just thinking.
> 
> This was done meanwhile.

Awesome! Indeed, the relevant PR was already merged but not yet included in the nightlys yesterday...

---

Another thing (I'm too lazy to open a separate issue for it):

There are so many material icons out there, do we really need to use the not really fitting 'i'-icon two times? 

![Screenshot_20220510_102541_cgeo geocaching_copy_323x124](https://user-images.githubusercontent.com/64581222/167585536-4edd3cfd-d602-4589-9e9b-bc5006fca4b3.png)


Some Ideas:
|file|file alternative|file alternative|file alternative|browser|
-|-|-|-|-
![Screenshot_20220510_102000_com android chrome](https://user-images.githubusercontent.com/64581222/167585033-d24781a4-3790-41e9-a405-92e8fc109e00.png)|![Screenshot_20220510_102051_com android chrome](https://user-images.githubusercontent.com/64581222/167585037-6a6078ae-3c1c-4437-9fdf-92d5f783a1e7.png)|![Screenshot_20220510_102326_com android chrome](https://user-images.githubusercontent.com/64581222/167585042-3b96d740-2eb5-43bc-9515-d709dcd03483.png)|![Screenshot_20220510_102347_com android chrome](https://user-images.githubusercontent.com/64581222/167585044-b5f5dbd3-91b2-4dbf-a4b6-12f923537cfc.png)|![Screenshot_20220510_102012_com android chrome](https://user-images.githubusercontent.com/64581222/167585046-2ec501de-f069-43f4-8971-89dfa6d546a1.png)

**Comment by eddiemuc** [comment]
> There are so many material icons out there, do we really need to use the not really fitting 'i'-icon two times?

Sure, no problem. I would use "file alternative" (since we are in an image gallery) and "browser" if no one objects.
