### ISSUE TITLE
Removing Geolutins?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12976]
### Tell us your idea!

Geolutins website seems to be down. See for yourself at http://www.geolutins.com/

Service does not seem to work anymore either, c:geo test is failing for it:

![image](https://user-images.githubusercontent.com/6909759/167290158-63418442-ffd8-4ef2-9eb7-046d4285ed24.png)
 

### What solution would you suggest?

Maybe time to remove Geolutins from c:geo?

### Is there an alternative?

Leave it (hoping it will resurrect somehow) but comment out the failing test

**Comment by Lineflyer** [comment]
@kumy 
Can you contact David from Geolutins to confirm, that he closed the service?

**Comment by kumy** [comment]
mail sent.

**Comment by kumy** [comment]
link to #8385

**Comment by Lineflyer** [comment]
The difference to #8385 is, that now the domain seems no longer owned by the service.

**Comment by kumy** [comment]
I never received a response from David for 2 consecutive years.

I think we can remove the service :man_shrugging:
