### ISSUE TITLE
[Image gallery] strange animations under specific circumstances 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13008]
### Describe your problem!

The image gallery does crash when going back from single-image-view of a spoiler image. 

### How to reproduce?

- click on "spoiler images"
- open a/the spoiler image in full screen
- go back
- CRASH! 

### Actual result after these steps?

```
05-13 11:31:35.524  3815  3815 E AndroidRuntime: FATAL EXCEPTION: main
05-13 11:31:35.524  3815  3815 E AndroidRuntime: Process: cgeo.geocaching, PID: 3815
05-13 11:31:35.524  3815  3815 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView.getImageViewForIndex(ImageGalleryView.java:412)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView.lambda$openImageViewer$7(ImageGalleryView.java:467)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView.lambda$openImageViewer$7$ImageGalleryView(Unknown Source:0)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ui.-$$Lambda$ImageGalleryView$LG32SzA9OCH4UYy9B_CYXE5lOr8.call(Unknown Source:4)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ImageViewActivity$6.onMapSharedElements(ImageViewActivity.java:472)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.ActivityTransitionCoordinator.viewsReady(ActivityTransitionCoordinator.java:236)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.EnterTransitionCoordinator.viewsReady(EnterTransitionCoordinator.java:133)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.EnterTransitionCoordinator.triggerViewsReady(EnterTransitionCoordinator.java:161)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.EnterTransitionCoordinator.viewInstancesReady(EnterTransitionCoordinator.java:117)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.ActivityTransitionState.startEnter(ActivityTransitionState.java:233)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.ActivityTransitionState.enterReady(ActivityTransitionState.java:213)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8148)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.Activity.performRestart(Activity.java:8198)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:5355)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.servertransaction.WindowVisibilityItem.execute(WindowVisibilityItem.java:39)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
```

### Expected result after these steps?

No crash 

### Reproducible

Yes

### c:geo Version

2022.05.13

### Additional Information

Unrelated to the crash, but there's another situation where there is a strange animation (see video):

https://user-images.githubusercontent.com/64581222/168257814-bbfa849a-3a4c-4970-9103-55a6434fce6e.mp4

https://user-images.githubusercontent.com/64581222/172001745-2ba227be-a6e9-4b2f-9b5c-7bdcceb10b10.mp4

**Comment by eddiemuc** [comment]
@fm-sys Looks like I made the same mistake which I found in review yesterday: I used lambdas across activities...

Also I fear recycler view sometimes is too lazy in initializing views.

Anyway, I am away over the weekend. Unfortunately a fix has to wait.

**Comment by eddiemuc** [comment]
PR #13015 will remove the crash. However, after it is merged you will notice that under same circumstances where cgeo crashed before there will now not be a "flowback" of the image when going back from image detail view to image list view. To fix this in a reliable way, a larger redesign of the list view needs to take place. For this, I keep this issue open

**Comment by eddiemuc** [comment]
Ok I tried out many things. In am caught between numerous scrolling problems when putting recycler view inside PageViewer2 plus other textviews and recycler view item.views not available on jumpback from detail to list view (-> which means that no flowback effect seems possible)

I guess I have to rewrite the gallery list view to hard-load all images and all image views (no recycling approach). Otherwise flowback from detail to list seems impossible.

**Comment by Lineflyer** [comment]
Do we really need the flowback? 

BTW:
I could live with back key (or back arrow) to return to the gallery and could imagine to drop the up/down swipe which is returning to the gallery.

**Comment by eddiemuc** [comment]
https://www.androiddesignpatterns.com/2014/12/activity-fragment-transitions-in-android-lollipop-part1.html

**Comment by fm-sys** [comment]
The crash is solved meanwhile, however the strange animations are still present...

**Comment by eddiemuc** [comment]
> The crash is solved meanwhile, however the strange animations are still present...

Will stay this way in release. All further development and fixes are done on master (or are you talking about master? There the animations should be gone)

**Comment by eddiemuc** [comment]
BTW: what you experience there is what happens with animations when a recyclerview is used in conjunction with viewpager2/fragment logic of our cache details activity. Scroll does not work, so logic works only if return image by chance is already initialized in recyclerview. It is not nice.

**Comment by fm-sys** [comment]
Following video was recorded with today's nightly (-> master branch):


https://user-images.githubusercontent.com/64581222/172024989-6e5d3d76-ff14-460c-bc11-d37c70ab8966.mp4

**Comment by eddiemuc** [comment]
Ok thats something else...

**Comment by eddiemuc** [comment]
Trying this out, it seems that with current master this is now happening only in image gallery opened via clicking on "spoiler/background" images (and maybe also when opening single log images, haven't tried that), but not in the "main" gallery tab.

@fm-sys can you confirm this?

**Comment by fm-sys** [comment]
Yes, it seems to happen only for "sub-galleries". I can reproduce it for logs and spoilers...
