### ISSUE TITLE
Cache selection list for overlapping caches on map missing for GMap

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13001]
> the problem exist not more for the OSM map, but the selection list is missing on the Google map.

Yes, it is not (yet) implemented for Google Map

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10652#issuecomment-943750206_

**Comment by fm-sys** [comment]
I guess this will become obsolete as soon as our unified map is ready...

**Comment by Lineflyer** [comment]
Why did you create a duplicate of #10652 now?
And overall both are IMHO duplicates of #7511.

**Comment by bekuno** [comment]
> Why did you create a duplicate of #10652 now? And overall both are IMHO duplicates of #7511.

Mea culpa!
I have vergotten this other ticket. Thanks for the research.

**Comment by bekuno** [comment]
> > Why did you create a duplicate of #10652 now? And overall both are IMHO duplicates of #7511.
> 
> Mea culpa! I have vergotten this other ticket. Thanks for the research.

This Issue is a duplicate of #7511.
The #10652 is another problem on our Mapsforge map implementation.

**Comment by Lineflyer** [comment]
Yes, I am sorry. I understood that meanwhile :)
