### ISSUE TITLE
Crash when launching mapsforge map

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13021]
### Describe your problem!

While using today's nightly, ~the image gallery~ cgeo did crash again... 

### Reproducible

No

### c:geo Version

2022.05.17

**Comment by eddiemuc** [comment]
I am a bit puzzled by this. The NPE-line is the following:

![image](https://user-images.githubusercontent.com/6909759/168851931-50a60261-6e53-4162-a7d7-80d0f63c7c79.png)

This was committed to master 2 days ago:

![image](https://user-images.githubusercontent.com/6909759/168852153-ddbcc550-956c-47b6-92a9-593c3a56bbac.png)

BEFORE this commit, I would have understood the NPE because it changed the line like this:

![image](https://user-images.githubusercontent.com/6909759/168852335-fba301f1-bd71-4ca2-9314-af881c459ce9.png)

**Comment by fm-sys** [comment]
Oh, I'm so sorry! There where two stacktraces contained in the logfile and ai copied the wrong one...

This explains as well, why the timestamp shows `05-16 00:40:10.234` 😅

The crash is totally unrelated to the image gallery but rather caused by mapsforge:

```
05-17 16:54:57.366  5084  5667 E AndroidRuntime: FATAL EXCEPTION: LayerManager
05-17 16:54:57.366  5084  5667 E AndroidRuntime: Process: cgeo.geocaching, PID: 5084
05-17 16:54:57.366  5084  5667 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'double cgeo.geocaching.location.Geopoint.getLongitude()' on a null object reference
05-17 16:54:57.366  5084  5667 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.layers.NavigationLayer.draw(NavigationLayer.java:69)
05-17 16:54:57.366  5084  5667 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
05-17 16:54:57.366  5084  5667 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
05-17 16:54:57.366  5084  5667 W cgeo    : [LayerManager] UncaughtException
05-17 16:54:57.366  5084  5667 W cgeo    : java.lang.NullPointerException: Attempt to invoke virtual method 'double cgeo.geocaching.location.Geopoint.getLongitude()' on a null object reference
05-17 16:54:57.366  5084  5667 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.layers.NavigationLayer.draw(NavigationLayer.java:69)
05-17 16:54:57.366  5084  5667 W cgeo    : 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
05-17 16:54:57.366  5084  5667 W cgeo    : 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149) 
```

I will rename the issue accordingly...

**Comment by ztNFny** [comment]
> The crash is totally unrelated to the image gallery but rather caused by mapsforge:

That stacktrace only leaves the conclusion that you somehow managed to create a track to "null". But destination == null is already checked for, so that shouldn't be possible. Any idea what you did to provoke the crash?

**Comment by moving-bits** [comment]
@fm-sys: Still happening?

**Comment by fm-sys** [comment]
The crash never was reproducible, so let's close if it doesn't show up in our crash reports...
