### ISSUE TITLE
support targetSDK 31

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13036]
### Tell us your idea!

Play Store guidelines require `targetSDK` being set to 31 to be able to upload updates starting November 1st, 2022.

~(This would also enable us to merge some of the more recent changes to material libs waiting in our PR queue.)~ (this would be compileSDK)

For details see https://developer.android.com/google/play/requirements/target-sdk

### What solution would you suggest?

Migrate c:geo to `targetSDK` 31

### Is there an alternative?

Not really... Without setting `targetSDK` to 31 our app can continue in Play Store until November 1, 2023 until it gets delisted. Updates will be possible until November 2022 only, though, when not upgrading `targetSDK`.

### Additional Information

On a quick glance, there are several things that might hit us:

- Location: Users can request apps to retrieve only approximate location information. You must request the [ACCESS_COARSE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_COARSE_LOCATION) permission any time you request [ACCESS_FINE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_FINE_LOCATION).
- Intent filters: If your app contains [activities](https://developer.android.com/guide/components/activities/intro-activities), [services](https://developer.android.com/guide/components/services), or [broadcast receivers](https://developer.android.com/guide/components/broadcasts) that use [intent filters](https://developer.android.com/guide/components/intents-filters#Receiving), you must explicitly declare the [android:exported](https://developer.android.com/guide/topics/manifest/activity-element#exported) attribute for these components.
- Hibernation: Apps may be put into hibernation mode if they are not used over a period of time. In hibernation mode your app's runtime permissions and cache are reset, and you can't run jobs or alerts. You can check your [app’s hibernation status](https://developer.android.com/topic/performance/app-hibernation).
- [Pending intent mutability](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability): You must specify the mutability of each PendingIntent object that your app creates.
- [Android App Links verification changes](https://developer.android.com/about/versions/12/behavior-changes-12#android-app-links-verification-changes): When using Android App Link verification, make sure that your intent filters include the BROWSABLE category and support the HTTPS scheme. (Relevant only when we start working on #13018)
- [Notification trampoline restrictions](https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines): When users tap notifications, some apps respond by launching an app component that starts the activity that the user sees and interacts with. This app component is known as a notification trampoline.
Apps must not start activities from services or broadcast receivers that are used as notification trampolines. After a user taps on a notification or action button within the notification, your app cannot call startActivity() inside of a service or broadcast receiver.

(copied from https://developer.android.com/google/play/requirements/target-sdk)

**Comment by bekuno** [comment]
I set the prio here to high, as the date 1st november is in 3 weeks.

**Comment by moving-bits** [comment]
Note regarding `PendingIntent`: We have a hand full of `PendingIntent`, some of them already set the required flag, others don't, so definitely a to do here.

**Comment by moving-bits** [comment]
Current status, AFAICS:
- Location: Not much we can do about, as we require GPS, which requires ACCESS_FINE_LOCATION. Technically we already request fine location, but if the user declines it, they cannot use c:geo. To my understanding we are settled here for now.
- Intent filters: Should be fine, we have added the "export" field some time ago already.
- Hibernation: App should detect missing permissions already, so that users can re-add them. Only thing that may happen is missing permission for folders, though. Not sure how we can detect those programmatically. No show stopper, though, just a thing to keep in mind for support for now.
- Pending intent mutability: fixed meanwhile
- Android App Links verification changes: not in use currently
- Notification trampoline restrictions: not in use currently, AFAICS

**Comment by bekuno** [comment]
I think that we can close here.
The status from @moving-bits in https://github.com/cgeo/cgeo/issues/13036#issuecomment-1279702198 shows that all is done, and also done for `cgeo-contacts`.
(after PR #13562)

Also, as we are now after 1st November, we cannot currently use our release branch for a bugfix release.
Perhaps we should prepare a beta release with the current master to be able to react to unforeseen changes?
The change for the language swith (#13552) should also be reason enough to do this.

**Comment by moving-bits** [comment]
If no-one objects I can prepare a new beta version from current `master` tomorrow.

**Comment by moving-bits** [comment]
All fixes mentioned above are part of our new beta version 2022.11.05-RC, so let's close here and open dedicated issues if such arise.
