### ISSUE TITLE
New gallery tab: Wrong image count (and increasing with each reload)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13038]
### Describe your problem!

While doing some testing I've stumbled upon the new image gallery tab showing a wrong counter.

### How to reproduce?

- load GC9C8G5 Neptunbrunnen
- swipe to new image gallery tab

### Actual result after these steps?

label in bottom navigation displays "*Images (7)"

### Expected result after these steps?

should be "*Images (2)", as only two images are being displayed

### Reproducible

Yes

### c:geo Version

current master

### Additional Information

Just discovered: Reloading the cache increases the number on the label by 2 each time...

![image](https://user-images.githubusercontent.com/3754370/169711970-d791c5d2-1211-44e2-967f-dd2cecdde5d5.png).![image](https://user-images.githubusercontent.com/3754370/169711977-76a8a12b-40b8-4e61-92ed-63fb59f69b52.png)

So maybe I had an odd number of images for this cache already (since I had stored it in the emulator a few weeks ago), and by updating the cache (reading new log entries) only two images were visible now. With each update the number increased by two: 3 - 5 - 7 - ...

**Comment by fm-sys** [comment]
Yes, fixed...
