### ISSUE TITLE
Personal Note - Add/Update Waypoints - rejected because of PN's 2.5k size limit

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#13048]
### Describe your problem!

If your PN already has about or even more than 2500 chars and you try to ``Add/Update Waypoints``, the addition will be rejected.
Toast says ``Waypoints can not be stored in note due to size limits (max. personal note size: 2500)``

### How to reproduce?

1. Create a user defined WP
2. Create a note with 2500+ chars
3. tap ``Add/Update Waypoints``

### Actual result after these steps?

Addition of waypoints will be rejected.

### Expected result after these steps?

Waypoints should be added, even if the limit of the cache's connector doesn't allow more to be uploaded (esp. as upload is not mandatory anyway).

### Reproducible

Yes

### c:geo Version

2022.05.24-NB-0a1ef08	

### Additional Information

We already had an issue like this or at least have discussed the pointlessness of this rejection while inventing the store feature a long time ago. The other day we decided that the rejection does not make any sense for two reasons:
1. the limit is a gc.com website limit and has nothing to do with c:geo
2. when trying to upload a PN with more than 2500 chars there will be a warning anyway
3. the rejection makes it impossible to share a complete note with others (e. g. via messenger)

After that the rejection was gone, already, but the other day it was back again ... this has often annoyed me since then, but now I'm finally sitting at the computer while stumbling upon it.  ;)

Moreover I would really appreciate if even predefined WPs would be stored to the PN (again, too), as sometimes valuable information are in the waypoint texts only (Owner's Note) and it would make life a lot more easy if these infos could be transferred to the notes via an easy way.

Actually, I thought we had already agreed upon that before anyway, but unfortunately I can't find the issue anymore ...  but perhaps this was already implemented and got lost the same way, the rejection crept in again ...?

**Comment by murggel** [comment]
no size-limit for PN - see #10981
export all waypoints - see #9084
