### ISSUE TITLE
re-add menu-entry for geochecker

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#13051]
### Tell us your idea!

Please re-add the menu-entry for the geochecker.
Normally I need the geochecker for calculated coordinates - I copy the coordinates from the waypoint-list and open from there the checker.
If the cache has a checker, I could see it whether the menu-entry exists or not and I could use it directly from the menu.
Now I have to swipe to the description page, scroll and tap the icon - hoping that the cache has a checker and the icon exist - because I don't see it before.

### What solution would you suggest?

re-add the menu-entry for the checker and keep the icon under the description.

### Additional Information

menu-entry was removed in #12960

**Comment by murggel** [comment]
@ztNFny what was the intention to remove the menu-entry?

**Comment by ztNFny** [comment]
We now have a very prominent button in the description. There's no point in having multiple buttons doing the exact same thing.

**Comment by murggel** [comment]
Understandable, but unfortunately for my workflow I would like to have it accessible from at least from the waypoint-tab

**Comment by SammysHP** [comment]
Do I add the waypoint or the variables from the description? No.

I think it makes sense to have it an option on the waypoint page "check this waypoint".

**Comment by eddiemuc** [comment]
> Do I add the waypoint or the variables from the description? No.
> 
> I think it makes sense to have it an option on the waypoint page "check this waypoint" (in case of multiple alternative final waypoints).

+1 for this idea. Should be easy to add to the waypoint context menu

Additionally maybe we could add some sort of visual indicator on the waypoint page whether a geochecker was detected by cgeo or not. Don't have an idea how this could look like though, maybe showing some icon.

**Comment by murggel** [comment]
> > I think it makes sense to have it an option on the waypoint page "check this waypoint" (in case of multiple alternative final waypoints).
> 
> +1 for this idea. Should be easy to add to the waypoint context menu
> 

Would it then be possible to already have the coordinates-input-field prefilled with the waypoint-coordinates? It probably already copied to the clipboard....

**Comment by eddiemuc** [comment]
> > > I think it makes sense to have it an option on the waypoint page "check this waypoint" (in case of multiple alternative final waypoints).
> > 
> > +1 for this idea. Should be easy to add to the waypoint context menu
> > 
> 
> Would it then be possible to already have the coordinates-input-field prefilled with the waypoint-coordinates? It probably already copied to the clipboard....

I suggest:
* Prefilled for geochecker supporting this feature
* Copied to clipboard for others

**Comment by eddiemuc** [comment]
Implemented with PR #13059
