### ISSUE TITLE
Make auto-backup less intrusive 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13076]
Currently, a toast + progress spinner is shown while the auto-backup is running. One of both should be enough.

Furthermore, the result toast is shown way to short, than for it to bring any benefit. However as nobody seem to miss that information, I would drop it as well.

Only the progress dialog should be enough |this can IMHO be removed completely 
-|-
![IMG_20220602_133703](https://user-images.githubusercontent.com/64581222/171622518-f82ea27b-cefb-4d8f-95a3-2318e27a1db9.jpg)|![IMG_20220602_133929](https://user-images.githubusercontent.com/64581222/171622512-eb3f6091-745a-4717-9c04-8258311511de.jpg)

**Comment by bekuno** [comment]
The toast for "Not successful" remains necessary imho.

After my last automatic backup I found a folder with the backup, but also 2 files with the name "data.corrupted" (and the same time stamp). Is it really necessary to create these if the backup was corrupted? If so, they should at least be deleted automatically after a successful backup.

**Comment by murggel** [comment]
I find the information about the storage-location useful.
Probably thus can moved to the progress bar
