### ISSUE TITLE
Hardcoded strings in VariableListView

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#13074]
### Describe your problem!

The strings in the dialog for adding a new variable are hardcoded

### How to reproduce?

https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/ui/VariableListView.java#L444

### Reproducible

Yes

### c:geo Version

Current nightly master

### Additional Information

![Screenshot_20220601-225017_cgeo](https://user-images.githubusercontent.com/70113341/171500309-23869c0c-35d7-4e14-98f8-d1972a142437.jpg)

**Comment by eddiemuc** [comment]
Fixed with PR #13075

I will be on vacation in upcoming next 2 weeks and most likely unable to react (fast) to issues during this time.
