### ISSUE TITLE
Distance circle on map for hide 

### ISSUE THREAD

**Issue by raznzsnasna** [cgeo/cgeo#13070]
### Tell us your idea!

I actually hide a few New Caches.
If I found a good tree to hide, I have to click on All Cache on map to See the Distance is over 0.1mile to my Position. 

### What solution would you suggest?

Red circles Over All waypoints on map with r=0.1mile.

### Is there an alternative?

Button to "control Distance to All waypoints"
Able "waypoints" to nearby
Distance shown under Symbol on map

### Additional Information

![Screenshot_20220530-100257_cgeo](https://user-images.githubusercontent.com/42694931/170946380-c3e266fe-bb03-42ee-9be0-8cfd97db9b60.jpg)

**Comment by fm-sys** [comment]
Not sure if this is what you want, but you can already today enable red 0.1 miles circles:

|||
-|-
![Screenshot_20220530_182639](https://user-images.githubusercontent.com/64581222/171031714-420defec-3064-4dd3-8f57-5945c74b7e7c.png)|![Screenshot_20220530_182347](https://user-images.githubusercontent.com/64581222/171031720-9c5a0eaa-63bd-4c5f-8e97-73b0e9a1df7f.jpg)

**Comment by raznzsnasna** [comment]
Thats exact what I need.
Thank you
