### ISSUE TITLE
Allow inverting individual filter elements 

### ISSUE THREAD

**Issue by AlexejheroYTB** [cgeo/cgeo#13071]
### Tell us your idea!

It would be useful if we could filter for caches which are NOT in certain lists.

**Comment by eddiemuc** [comment]
We could allow the user to invert EVERY filter on its own (in advanced mode) by placing a small checkbox into the filter headers. E.g. like this (dirty draft done with MS Paint):

![image](https://user-images.githubusercontent.com/6909759/171388764-70850bbf-f1d1-439d-a31b-d20145363107.png)

**Comment by fm-sys** [comment]
This would "just" be a more streamlined GUI for this, right? 

![Screenshot_20220601_183934_copy_324x428](https://user-images.githubusercontent.com/64581222/171456337-fce8c8d6-cc0e-4830-9998-91f53516a3c7.jpg)

**Comment by eddiemuc** [comment]
> This would "just" be a more streamlined GUI for this, right?

correct.

**Comment by fm-sys** [comment]
IMHO we can close here, as a workaround does exist for this feature request...
