### ISSUE TITLE
remove from route on (offline) log

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13089]
### Tell us your idea!

When a cache is on the active route remove it when saving/sending alog. Should be an option

**Comment by moving-bits** [comment]
related to #12387 (remove from route on setting "visited" to `true`)

**Comment by ztNFny** [comment]
Implementing this would require access to the route from Geocache.java to 1) check if the cache is on a route, 2) remove its geopoint(s). However I can't find a way to access the route, it seems to be available only in the 3 Map implementations (and each of them uses its own) - is that correct? @moving-bits you have a good view of this, did I miss something?

**Comment by ztNFny** [comment]
I tried this once more and again failed to find a way to access the route from Popup / Details dialog.
@moving-bits I'd have expected the route to be a static object shared between the maps but that isn't the case. Is that correct? Any pointers?

**Comment by moving-bits** [comment]
There's no singleton for individual route but a variable that gets prefilled from values stored in the database in the map init routines. Look for `IndividualRoute` type variable in the map implementations, and for `new RouteTrackUtils(...)` which links to the route / track menu.
