### ISSUE TITLE
Create a better "sync ongoing"-marker

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13090]
@ztNFny I would be glad if you could design a better "sync ongoing"-marker.

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/13084_

**Comment by fm-sys** [comment]
This is the current one: (`R.drawable.marker_sync`)
![grafik](https://user-images.githubusercontent.com/64581222/172057727-7609e753-934e-4cca-9c00-dab72f840831.png)


However, the shapes are far too small to be recognizable....

**Comment by ztNFny** [comment]
Is this shown instead of the stored disk icon during refresh?

**Comment by fm-sys** [comment]
Yes. The icon is shown during refresh itself and while the cache is in the query waiting for a refresh.

**Comment by ztNFny** [comment]
Note to self: Unlike "stored" icon the new marker should also show up in lists while they are downloading.

**Comment by ztNFny** [comment]
I went with a "download" icon instead of sync as we're not uploading any data, so sync is the wrong word and a download icon is also better recognizable in that small size.

**Comment by fm-sys** [comment]
Hm... I'm struggling whether the "download" icon is really understandable enough. Looking at the picture in #13101, I honestly wouldn't know what the icon means. 

At all other places we use a "sync" icon as well. Whatever icon we use at the end, these different places should IMHO stay aligned. 

![Screenshot_20220607_221255_cgeo geocaching](https://user-images.githubusercontent.com/64581222/172474035-ee095dcf-08ef-4bcd-8ebc-59acae28355d.png)

**Comment by ztNFny** [comment]
There's 2 places that trigger a download of caches:
- "store all" / "background download" on map
- "refresh" inside a listing or from list menu

In both cases data is only downloaded to cgeo, no data is uploaded, so it's not a sync. For the refresh a "refresh" icon is suitable, but not for the store/download situation.

**Comment by fm-sys** [comment]
I haven't found a single app which uses a non-animated "download" icon to indicate an ongoing progress. 

Whether it is syncing or downloading. There is only one thing which the icon should make clear: _"Hi, something is currently still ongoing here. Check back later..."_
 
A non-animated "download" icon was used in Android as "download finished" icon for years. That's why I associate the proposed icon with "finished" instead of "ongoing"...

**Comment by ztNFny** [comment]
Go ahead and create a 10dp animated but still recognizable icon

**Comment by fm-sys** [comment]
Yes, I know it's a difficult task to create a meaningful icon with such a small size 😅

Would the current architecture support animated cache icons at all?

**Comment by ztNFny** [comment]
> Would the current architecture support animated cache icons at all?

No, it's doing a conversion to bitmap.

A "refresh" icon is just too small for the space available. The marker icons are 13dp, the "stored" marker is even smaller at about 10dp. That makes the arrows in the refresh icon about 1dp which is unrecognizable.

Even for the download icon which is already a simple shape I was testing back and forth with and without the "_" in the icon to increase the size of the arrow to make it recognizable in that small size and both possible positions.

Anything more complex than such a simple shape won't work - and you still need quite an outline around it (1,2dp in 24dp)

**Comment by fm-sys** [comment]
Would something like this maybe work? 

![grafik](https://user-images.githubusercontent.com/64581222/172621588-8ce7d369-af86-47af-ab66-796ce036b474.png)

**Comment by ztNFny** [comment]
No. Anything but a very simple and bold shape won't work.

**Comment by ztNFny** [comment]
i checked materialdesignicons.com for some recognizable alternative again with keywords like sync, save, store, load, ... but they are all too detailed for the little space that's available
