### ISSUE TITLE
Improve formula recognition from clipboard for calculated waypoints

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13099]
### Describe your problem!

A user made me aware, that for his example cache the new waypoint calculator / variable view does not offer an easy solution (although its a pretty easy case IMHO).

Its a cache which has one set of variables/formula to calculate the final:
N 50° 50.(C+D) (B-A) (C) E 13° 49.(A+D) (B) (D)

The user copied this formula to his clipboard, but was not able to paste it into the waypoint calculator using our helpers (only manually it worked).

### How to reproduce?

1. Open GC9M2WC
2. Swipe to cache description and select and copy the formula (as shown above) from the listing text
3.  Go to the wapoint tab and create a new calculated waypoint
4. Select the wand icon and try to use "Paste from clipboard"

### Actual result after these steps?

Error toast "No pattern found"

### Expected result after these steps?

Pattern recognition should be improved to cover this use case

Alternative or bigger solution (feature request):
I could also imagine some option to directly create a calculated waypoint once the text is marked in step 2 which directly opens a prefilled calculated waypoint. 
Or a function in the cache menu to trigger a "scanning" for such kind of coordinate sets with variables and auto-creation of corresponding calculated waypoints.

### Reproducible

Yes

### c:geo Version

2022.06.06

**Comment by fm-sys** [comment]
rel. to  #12867

**Comment by ztNFny** [comment]
that pattern matches the first one in #12867, so let's close here

**Comment by Lineflyer** [comment]
Fine. I will probably open a new one as a feature request for being able to avoid this clipboard juggle by directly offering to create a waypoint for selected text in description or even scan the listing and create auto waypoints.

**Comment by ztNFny** [comment]
Isn't the same logic used for clipboard as well as "scan listing"? So if one is fixed the other should work as well

**Comment by Lineflyer** [comment]
AFAIK "Scan listing" currently only scans for non-variable waypoints (meaning real valid waypoints) but not for waypoint containing variables...but not sure if that was enhanced to cover variables lately... In fact, that would be the feature request then I guess.

**Comment by eddiemuc** [comment]
> Isn't the same logic used for clipboard as well as "scan listing"? So if one is fixed the other should work as well

Correct, the same logic used for clipboard-to-coordinate is also used for a scan function for waypoints with formulas. The waypoint scan function is located in the cache details context menu unter "waypoints":

![Screenshot_20220607-222537~2.jpg](https://user-images.githubusercontent.com/6909759/172476319-5036029b-9d4c-44a5-88c8-8317a22a30d0.jpg)

The clipboard function just scans for the first found formula waypoint in clipboard text.

That said, the scan function is very primitive currently - which is the reason why it doesn't recognize so many formats. If anyone is interested in creating a better one: the function entry point is in `FormulaUtils.scanCoordinates`.
