### ISSUE TITLE
Filtering for "personal note exists" only seems to work for downloaded/cached caches

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#13105]
### Describe your problem!

Filtering for "personal note exists" only seems to work for downloaded/cached caches

### How to reproduce?

Set up filter as in attached image
![2022-06-08 11 48 19](https://user-images.githubusercontent.com/54892606/172587611-68d614dc-cfbc-41eb-93ea-a90721478d42.png)
.

### Actual result after these steps?

Map will only display previously downloaded caches with notes. Apparently c:geo does not know about the personal notes for non-downloaded/non-cached caches.

### Expected result after these steps?

Display ALL caches with personal cache notes.

### Reproducible

Yes

### c:geo Version

2022.06.06

**Comment by eddiemuc** [comment]
Indeed, filtering in personal note is only done for stored caches. This can't be enhanced unfortunately because the apis of the caching platforms such as GC.com don't allow for such filtering. So I fear we can't fulfill this request. we have the same issue for e.g. filtering in log entries and a bunch of other things as well. There's a wiki page showing which filter options are also supported by the various caching services.

**Comment by dcjkfgdjhd** [comment]
OK, I see, thanks for the explanation! 

Maybe these limited filter options should be marked somehow in the filter dialogue, or not even offered in the live map, because there they make little sense.

**Comment by eddiemuc** [comment]
> Maybe these limited filter options should be marked somehow in the filter dialogue, or not even offered in the live map

This was discussed before and might be a good idea. However, there are some special cases to consider, and I haven't seen a concept yet which includes handling such cases. Examples:
* A live map view typically shows both stored caches and live caches in a mixed way. Forbidding certain filters for live map would then also forbid them in cases where all shown caches are stored caches, and that would be an unnecessary restriction
* Some filters work for some connectors and not for others, e.g. filtering by favorite percentage works for oc but not for GC.com. how to handle this?
* Some filters work for GC.com in live mode but just for premium members e.g. attribute filters. Should those be forbidden or allowed?
* Some filters work partially in live mode, e.g. "not found by" works with GC.com but "found by" does not. How to handle this?
* Filters can be stored by name and then reused in other filters. Should we forbid to use named filters created in "offline mode" for usage in "live mode"? 

All in all I don't current know a good and easy concept to handle all these cases in a smooth and straight-understandable way. Some sort of filter labeling might be a good idea, but I am currently missing the overall concept.

**Comment by Lineflyer** [comment]
This is not a bug as such (as clarified above). So I will close here and take the visualisation of filters, which do only work offline into a dedicated issue.
