### ISSUE TITLE
Allow adding map points to individual route directly

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#13104]
### Tell us your idea!

Often, to plan a route, you need to add intermediate points on the map.

Currently, as a workaround, I just create custom caches in the places I want, and then plan the route from custom cache to custom cache.

However creating custom caches involves lots of unnecessary taps.

### What solution would you suggest?

I never ever use custom caches for anything else than the above described use.

So as an alternative to custom caches, when long pressing the map, it would be cool, if could just drop small map markers, like sticking a "needle" into a map. Creating another needle should just require a long tap and not open any new window. Just the needle appears.

And once you have dropped all needles, you can then plan a route from needle to needle.

**Comment by fm-sys** [comment]
Like this idea! We just need to think of a good way how users can switch between UDC's and Needles...

**Comment by dcjkfgdjhd** [comment]
For me personally, it would be ideal, if there were an option in the settings to tell the app what a long tap is supposed to do.

For example, it already mildly annoys me that if a cache is selected, then long tap creates a waypoint, and if no cache is selected, it creates a UDC. 

I personally would want to set an option in c:geo that long tap ALWAYS drops a needle. Never anything else, I don't need UDCs *ever* and adding waypoints to caches is something I always do in the listing view and never via the map.

**Comment by dcjkfgdjhd** [comment]
Or maybe there could be a way to FIRST drop a needle, and then select the needle and say "create UDC here".

**Comment by fm-sys** [comment]
Hm. I understand the argument that you never need UDCs. However, dropping a new setting always feels like "we where not creative enough to build a good UI". A deeply hidden setting always means that 90% of all users will never discover it, which is sad especially if they would be interested in the feature as well.

Maybe a small context menu would be the best. For sure this means one more click, but somehow I like the idea anyway.
 
|Long-Tab-Action|
|-|
|add to individual route ("needle")|
|create user-defined cache|
|add waypoint (only visible if cache target is available)|

**Comment by dcjkfgdjhd** [comment]
> Or maybe there could be a way to FIRST drop a needle, and then select the needle and say "create UDC here".

I kind of like this solution, because even when you want to create a UDC it makes sense to first drop needle, then SEE IMMEDIATELY ON THE MAP that it really landed precisely where you wanted it, and then turning it into a UDC.

**Comment by fm-sys** [comment]
I'm fine with showing the needle immediately. However, adding it directly to the individual route would be unexpected. So afterwards we still need the context menu so users can select what should happen with the needle...

**Comment by fm-sys** [comment]
BTW, what should be improved in the same step is the individual route rendering for coordinate-only-points. These points should show the needle, not at least to be able to remove these points again. 


![Screenshot_20220608_121243_cgeo geocaching_copy_324x702](https://user-images.githubusercontent.com/64581222/172592162-493cc0a2-2f3b-4cb8-82d3-fe58d473b3f6.jpg)

What icon would you prefer for coordinate-only-points aka needles? 

![Zombodroid08062022122132_copy_266x178](https://user-images.githubusercontent.com/64581222/172593643-b15d05a6-2c94-405e-a679-03c4cfe92460.jpg)

**Comment by dcjkfgdjhd** [comment]
> BTW, what should be improved in the same step is the individual route rendering for coordinate-only-points. These points should show the needle, not at least to be able to remove these points again.

Agreed!

> What icon would you prefer for coordinate-only-points aka needles?

I would try to make it thin as possible to make it cover up as little of the map as possible. Something like the top/middle one in this image, maybe with a red head: [https://de.vecteezy.com/vektorkunst/4219760-map-tacks-rund-pins-und-plastik-map-push-pins](url)

**Comment by ztNFny** [comment]
my 2 cents: c:geo is a geocaching application. Having routing as an option in there is nice, but it should not get in the way of the core feature - geocaching. Requiring several additional clicks to to achieve the same result as before does get in the way though. If you want a routing app use a routing app.

Also the UI requirements stated here simply don't work: "make it as thin as possible" - it needs to have a certain size to be able to handle it, so it can't be thin/small. If it's almost the size of a cache marker but not quite that'll look like crap, so the marker has to be the size of a cache marker.

**Comment by dcjkfgdjhd** [comment]
> However, I don't think that it would make usability worse.

Me neither, seems like a made up problem.

Your mockup looks fine to me.

**Comment by ztNFny** [comment]
>  That's why I want to see an context menu which is easier to close than the current "Create UDC"/"New Waypoint" dialog.

How is the context menu easier to close? The "new WP" dialog is closed by either "Cancel", back button or clicking anywhere outside the dialog. The menu will be closed by back button or clicking outside it. Seems identical to me - but the menu is larger than the dialog, so if anything it gets harder.
