### ISSUE TITLE
improve individual route rendering for coordinate-only-points

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13110]
### Tell us your idea!

When coordinate-only-points points are contained in the individual route, they cannot be removed easily.

Furthermore, the route seem to end in nowhere.

### What solution would you suggest?

These points should show a pin marker, so that we are able to remove these points again via long-click. 

![Screenshot_20220608_121243_cgeo geocaching_copy_324x702](https://user-images.githubusercontent.com/64581222/172592162-493cc0a2-2f3b-4cb8-82d3-fe58d473b3f6.jpg)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/13104#issuecomment-1149736900_

**Comment by moving-bits** [comment]
Maybe a follow-up issue of #13122
