### ISSUE TITLE
Filter by country

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13118]
### Tell us your idea!

A user on support mail would like to have the ability to filter caches by country.
His use case, e.g: Search for paddle caches in Norway

### What solution would you suggest?

Have an advanced filter criteria in category "Details" for "Country" with the ability to select one or several countries from a given list.

### Is there an alternative?

Not implement it as it might be to specific.
Getting a complete list of supported countries could also be a problem.

### Additional Information

Support ticket 297094

**Comment by eddiemuc** [comment]
This is already available as filter "location" (in German: "Ort").

It is a free text filter but it will auto-complete and suggest all locations from caches stored locally. example:

![Screenshot_20220610-131042.jpg](https://user-images.githubusercontent.com/6909759/173052868-9995667a-6771-48bc-ae15-96b987145a4b.jpg)

The problems with a country selection list are:
* The Geocache providers  deliver "location" as a free text field, so from c:geo perspective anything can be contained in it
* Field contains both country and state in both cases (e.g. Bavaria, Germany), but the format is not documented. And I am not sure whether it is the same for all providers
* The location content is localized. So some might get "Germany" where others get "Deutschland".

In theory we could maintain an own country list (incl translations) into c:geo and provide clever preselected lists of countries to search for, but is this worth the effort?

**Comment by eddiemuc** [comment]
A better example: in screenshot below you see the suggestion list when I type "ni" on my own installation of c:geo. As you can see the selection contains both countries and states, it also contains both english and German translations of names. This is simply the summary of all countries and states in all languages which are stored offline in my installation.

![Screenshot_20220610-131930.jpg](https://user-images.githubusercontent.com/6909759/173054616-c24c6da4-2aa3-4119-b391-82243b5c8228.jpg)

**Comment by jakedot** [comment]
I had this implemented for the old filter system. maybe it can be helpful. See #8218

**Comment by moving-bits** [comment]
Reading above's comments I guess we can close here?

**Comment by jakedot** [comment]
I think so too
