### ISSUE TITLE
New Image gallery uses too many resources

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#13138]
### Describe your problem!

I am not satisfied yet with the performance of the new image gallery and want to use this issue to track my work on this. Bad aspects are,:
* Gallery loads all images of cache (asynchronous), also those which can't be seen (only if one starts scrolling)
* transitions forth and esp back from detail view are unreliable. Especially if master activity was destroyed by system meanwhile.
* opening detail view will cause transactiontoolarge if  there are too many images in cache

### How to reproduce?

Open cache with many images. Example: GC89AXV

### Actual result after these steps?

See above. I consider this issue done if even on a low-performance device cache listings like GC89AXV can be opened without much delay, without crash and with the ability to scroll through all images in gallery view (both list and detail/zoom view)

### Expected result after these steps?

Steps to make this better:
* Go away from two-activity-solution, make detail view an overlay of list view in same activity instead
* use recyclerview, but make is scrollable inside viewpager2 fragment

This is not easy but doable

### Reproducible

Yes

### c:geo Version

All

**Comment by eddiemuc** [comment]
Note to self: recreate Imagegallery completely using Fragments as described in GridToPager example

**Comment by eddiemuc** [comment]
While working on this I had the impression that Html.fromHtml starts to break down when the description reaches a very large size. Example: GC89AXV (937000 chars). At least this happens in my emulator.

As a first step I was thinking about capping the description size at a certain, very high treshold, e.g. 100000 chars. What is the team thinking about this?

**Comment by moving-bits** [comment]
(Another example would be GC6FJH3.)

Within a mobile app it's rarely useful to see such a long listing completely, and it really slows down the app, and hinders accessing the note. So limiting display to a default of even 5,000 or 10,000 characters should be enough in most cases.
A hint should be added, eg "display truncated to first 5,000 characters", with a link to display the full text (within the app), being loaded only on demand.

**Comment by fm-sys** [comment]
> So limiting display to a default of even 5,000 or 10,000 characters should be enough in most cases.

10k characters can be quite short, e.g. for some longer Multis / mysteries or caches which contain Wikipedia abstracts. I would give at least 20k characters loaded by default. But I agree that more than that doesn't make much sense...

**Comment by eddiemuc** [comment]
I found e.g. https://www.geocaching.com/geocache/gc8dvvq which has 38841 chars but is still ok-ish imho. So I would set the limit to 50k for now. hope that's ok. PR will follow

**Comment by eddiemuc** [comment]
Or https://www.geocaching.com/geocache/gc7xpmc with 34748 chars (seems that its often earth caches with these very very very long descriptions...)

Note that I have to make the size check on the "unprocessed" HTML - because it is the processing of text to HTML that takes a major part of the time
