### ISSUE TITLE
CI needs active JDK11 for compileSdkVersion 31

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13143]
### Describe your problem!

log on CI:

~~~
11:03:16  > Task :main:compileBasicNightlyJavaWithJavac
11:03:16  An exception has occurred in the compiler (1.8.0_101). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com/) after checking the Bug Database (http://bugs.java.com/) for duplicates. Include your program and the following diagnostic in your report. Thank you.
11:03:16  java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
~~~

This is a result of switching to `compileSdkVersion 31` in #13136 .
Seee e.g. https://stackoverflow.com/questions/68344424/unrecognized-attribute-name-module-class-com-sun-tools-javac-util-sharednametab .
We have to switch to JDK11 also for the Build.

### How to reproduce?

see https://ci.cgeo.org/job/cgeo%20nightly/2694/consoleFull#-109812861545fc375f-a63e-468b-8450-76255356fdf9

### Reproducible

Yes

### c:geo Version

2022.06.13-NB2

**Comment by mucek4** [comment]
OK. Wait. CI has JDK11
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-post-Debian-1deb10u1, mixed mode, sharing)

**Comment by bekuno** [comment]
Sure.
But the compiler runs (in this part?) with JDK 8 - see the log message `An exception has occurred in the compiler (1.8.0_101)`.
Maybe a variable or a Jenkins configuration needs to change?

**Comment by mucek4** [comment]
For some reason somewhere there is JAVA_HOME set to Java 1.7. How it ended in Java 1.8 folder I have no idea. I have removed Java 1.8 from disk and set java home to Java 11. Build worked.
