### ISSUE TITLE
add relative versions of "date" filters

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13152]
Date filters currently require setting a fixed start and end date and are stored as such. However there are queries that require a relative time, e.g. "hidden in the last week" or "not logged for 1 year".

"Last details update" filter already works in such a relative way, alternative versions of "Hidden Date" and "Last Found Date" should be added.
Range values should NOT be copied from "Last details update", they don't cover enough cases.

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/13151#issuecomment-1155759931_

**Comment by ztNFny** [comment]
> Range values should NOT be copied from "Last details update", they don't cover enough cases.

I tried to define some reasonable values valid for both but as the scenarios for "Hidden" and "Last found" are quite different I think it needs different ranges after all as I ended up with what I think are too many options:
![image](https://user-images.githubusercontent.com/1258173/173802936-9b72ed59-e8b9-48c8-8935-1f9122d4e350.png)

Usecase for "Hidden since" (remember we still have the "Hidden date" filter for setting fixed dates):
- Finding recently published caches in the FTF race (e.g. hidden since <=3/7 days - at least GC.com provides only "hidden" but not "published" date so smaller values don't make much sense), combined with a "not logged" filter. For this values 1d, 3d, 5d, 7d, 14d, 30d would be ok
- Updating your offline list with recently published caches. Range: 1w, 2w, 1m, 3m
- ???

Usecase for "Last logged":
- Find caches that haven't been logged in a long time, sometimes required for challenges (e.g. last found > 1 year). Range suggestion: 3m, 6m, 1y, 2y, 3y, 5y
- ???

Any other scenarios that'd have some influence on the values?

**Comment by ztNFny** [comment]
I tried to create a new filter view with just a slider, similar to "Stored since", using the sql field "hidden". But unlike the normal Hidden data filter that one doesn't work with live map. So I tried rebuilding a DataRangeGeocacheFilter with a slider. But the filter stuff seems to be quite complex and I couldn't get anywhere rn :-(

**Comment by fm-sys** [comment]
> I tried to create a new filter view with just a slider, similar to "Stored since", using the sql field "hidden". But unlike the normal Hidden data filter that one doesn't work with live map.

You need to implement your new filter for every connector to get it working on the live map. See:

https://github.com/cgeo/cgeo/blob/4c697f235fd08388312decbc16a652f4ff2f0f99/main/src/cgeo/geocaching/connector/gc/GCMap.java#L147-L154

**Comment by ztNFny** [comment]
Ok, thanks for the pointer, that'd at least allow the "copy of StoredSince" filter to work.

But I think it'd be way nicer to just have a different GUI to HiddenGeocacheFilter, settings max to today and min to today-days. I think like that it'd also avoid requiring the connector-cases ... or not?

**Comment by fm-sys** [comment]
Have you checked whether the params are added correctly to the API call?

**Comment by eddiemuc** [comment]
To check where the problem might be, I would need to see the new HiddenSinceGeocacheFilter class which somehow I am unable to find (unfortunately I am restricted to functionality of GitHub app currently)

However, I would suggest a different implementation approach anyway: extend DateFilter and DateGeocacheFilter such that they also accept to set relative Parameters: 
* add a method setRelativeMinMaxDate(final int daysBeforeToday, final int daysAfterToday) to DateFilter
* Let DateFilter calculate the absolute minmaxdates from these parameters on the call
* Also let DateFilter take care of how to store this in config and user display

This way you have some advantages:
* Function is in principal available to all date filters
* No need to adjust connectors
* Very easy to unit test

For the GUI you might want to create a separate one though.

**Comment by ztNFny** [comment]
> However, I would suggest a different implementation approach anyway: extend DateFilter and DateGeocacheFilter such that they also accept to set relative Parameter

I did just that. It's the UI part I'm struggling with. But please don't bother while you don't have proper access, not worth the time.

**Comment by eddiemuc** [comment]
> @eddiemuc could you take a stab at the UI part of relative date filters? I tried it once again but failed miserably :-(
> My idea was to have a dual-slider, like for D/T rating, to set min and max date with left being infinite years and right being 0 days (aka today)

I can take a look in general. However, as you probably have noticed, it is currently hard for me to spare time for cgeo implementations, so I can't promise when I find the time.

**Comment by eddiemuc** [comment]
>  My idea was to have a dual-slider, like for D/T rating,

The dual slider is to set two different range values at once (D and T). Which two values do you want to set at once in this case?

**Comment by ztNFny** [comment]
> >  My idea was to have a dual-slider, like for D/T rating,
> 
> The dual slider is to set two different range values at once (D and T). Which two values do you want to set at once in this case?

I meant the slider used for either of D and T. To set both start and end at the same time.

So e.g. you can set "in the last 2 weeks" with 14,0, older than a year with unlimited,365

**Comment by eddiemuc** [comment]
> I meant the slider used for either of D and T. To set both start and end at the same time.

Ok that makes sense

**Comment by eddiemuc** [comment]
PR #13760 adds relative filtering for hidden date like this:

![image](https://user-images.githubusercontent.com/6909759/208169775-2d5a067d-8225-4349-bb08-5dbdeac13a99.png)

Would that be all right?

For "Log Entry" I don't see so much the point since this filter can only search in locally stored caches (no online search possible). You really want this?

**Comment by ztNFny** [comment]
Looks good. Thank you for your effort!
It's also stored as relative? So loading the filter next week will give then-x days, not today -x days.

Log entry filtering works for search results at least. Not sure whether it's sent as part of the query out only filtered on the result data.
I use log filtering (with inverse filter) to search for open ftfs (not found between 2000 and 2050)
Relative filter could be useful, e.g. to check for cashes not recently found as they might be missing.

**Comment by ztNFny** [comment]
Are the values fixed or are there in-betweens as well? From 1m to 1 year to unlimited seems quite large steps.

**Comment by bekuno** [comment]
> PR #13760 adds relative filtering for hidden date like this:
> 
> ![image](https://user-images.githubusercontent.com/6909759/208169775-2d5a067d-8225-4349-bb08-5dbdeac13a99.png)
> 
> Would that be all right?

Looks good.
But should't it be `<2d` = lower that 2 days? (the other end also)
Maybe better to set the near time end to the left side ond the far time ent to the right. This is more common, imho.

**Comment by ztNFny** [comment]
> Maybe better to set the near time end to the left side ond the far time ent to the right. This is more common, imho.

It's a timeline, having the past on the left and the present on the right feels right to me.

**Comment by bekuno** [comment]
> Maybe better to set the near time end to the left side ond the far time ent to the right. This is more common, imho.
> 
> It's a timeline, having the past on the left and the present on the right feels right to me.

We are writing left to right. So we are trained to have the next point first and the late point last.

**Comment by ztNFny** [comment]
> > Maybe better to set the near time end to the left side ond the far time ent to the right. This is more common, imho.
> > 
> > It's a timeline, having the past on the left and the present on the right feels right to me.
> 
> We are writing left to right. So we are trained to have the next point first and the late point last.

Yes, exactly. As both points are in the past having the first occuring one, >1 year, first before the last, today, makes perfect sense.
If it'd be looking into the future today would be left, next year right.
On a timeline 1900 will always be left to 2000.

**Comment by eddiemuc** [comment]
> Looks good. Thank you for your effort!
> It's also stored as relative? So loading the filter next week will give then-x days, not today -x days.

Yes. It is stored relative.


> Are the values fixed or are there in-betweens as well? From 1m to 1 year to unlimited seems quite large steps.

Currently it is a fixed set of values. We can make a continuous slider out of it to select "days in the past from today". This would then be similar to selecting number of favorite points in the fav points filter. Would you prefer that?

**Comment by ztNFny** [comment]
> Yes. It is stored relative.

Perfect!

> Currently it is a fixed set of values. We can make a continuous slider out of it to select "days in the past from today". This would then be similar to selecting number of favorite points in the fav points filter. Would you prefer that?

Hm, not sure. I kind feel like the current is not detailed enough but a continuous slide would be overkill.
How about 1d,3d,1w,2w,1m,3m,6m,1y,all?

**Comment by eddiemuc** [comment]
Ok, now it looks like this:

![image](https://user-images.githubusercontent.com/6909759/208253008-09d69297-dd53-4729-9e0b-bce6ad2f23f6.png)

**Comment by eddiemuc** [comment]
Sorry, forgot the "three month". Now like this:
![image](https://user-images.githubusercontent.com/6909759/208253088-d012069e-c511-4602-855c-e5a2a155d46f.png)

**Comment by fm-sys** [comment]
IMHO we shouldn't go with negative times. Although it's mathematically correct, the average geocache would say "**more** than one year ago" instead of "in less than minus one year"

**Comment by ztNFny** [comment]
I'd also vote for removing the "-". Just because they're stealing space without adding any info.

**Comment by fm-sys** [comment]
If the "-" gets removed, we also need to invert the _less than / greater than_ sign, like already suggested above (https://github.com/cgeo/cgeo/issues/13152#issuecomment-1355493651): 

|||
|-|-|
|More than a year ago | >1y |
|Less than 3 days ago | <3d |

**Comment by eddiemuc** [comment]
Now it looks like this:
![image](https://user-images.githubusercontent.com/6909759/208257028-9712648c-7df9-4519-a3ca-ee4df9786d31.png)

**Comment by ztNFny** [comment]
Today I tested this in my own build and it works great!

This is the filter I use for finding possible FTFs, applied to "nearest" tab (which I've set to unlimited radius so I can control that from the filter):

![image](https://user-images.githubusercontent.com/1258173/208315623-ecb81889-4675-415c-a00a-879b3a7d4544.png)

**Comment by eddiemuc** [comment]
Should be closed with PR #13760
