### ISSUE TITLE
Add "prepend to route" option for geocaches

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13176]
#13109 added the option to add a point either to the end or *beginning* of an existing route.
The same should be available for caches.

===========
> Do you plan to add this functionality for caches/WPs as well (not only for empty locations)? 

Yes. But not sure about the UI part yet. It was easy enough to add here so I started with this. I don't want to make adding caches to routes harder, so need to investigate some possibilities here. Maybe have it in cache pop-up menu ...

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/13109#issuecomment-1154256074_

Ideas:
- long-click on "set as target" button in cache popup - Pro: Quick to access - Con: hard to discover
- menu item in cache popup - Pro: Easy to discover - Con: Many clicks, menu is already quite crowded
- show a popup on long-pressing a cache - Pro: Easiest to discover - Con: Complicates adding caches to a route (so much that imho this is a no-go)

**Comment by ztNFny** [comment]
Ideas:
- long-click on "set as target" button in cache popup - Pro: Quick to access - Con: hard to discover
- menu item in cache popup - Pro: Easy to discover - Con: Many clicks, menu is already quite crowded
- show a popup on long-pressing a cache - Pro: Easiest to discover - Con: Complicates adding caches to a route (so much that imho this is a no-go)

**Comment by moving-bits** [comment]
As discussed in today's dev meeting: Long tap should open a context menu, as this is consistent with adding "free points" and also prevents users from accidentally adding caches to an individual route (had several issues on support about this).

**Comment by ztNFny** [comment]
> As discussed in today's dev meeting: Long tap should open a context menu, as this is consistent with adding "free points" and also prevents users from accidentally adding caches to an individual route (had several issues on support about this).

Would be good if the old behavior (add cacje to route on long-tap) can be restored with a setting as it's a lot faster than the new proposed one (1 vs 3 taps)

**Comment by moving-bits** [comment]
Why would it be three taps? First (long) tap for opening the popup, second tap to select "append to route"?

Regarding a setting: I guess I would need to see it in practice to be able to say if the new solution would be too annoying for appending to a route or not.

**Comment by Lineflyer** [comment]
I would prefer consistency of map behavior over faster (but somehow unexpected) action. And we should please avoid more settings whenever possible.

**Comment by Lineflyer** [comment]
Just an example of support cases, which come in quite frequently on our mail and on the user groups:

![image](https://user-images.githubusercontent.com/949669/202520860-773ff8e5-13ad-426f-9eb5-76b429af7e51.png)

That is the reason, why we should IMHO remove the direct action on long click on the map.
A clear context options menu would be really preferable and avoid accidental triggering of unwanted functions.
