### ISSUE TITLE
Typo in String value for Prefix

### ISSUE THREAD

**Issue by kvaithin** [cgeo/cgeo#13191]
Noticed the following where `prefix` seems to be incorrectly named as `praefix`.
Would we wanna refactor it to the correct name? Could raise a PR. 

https://github.com/cgeo/cgeo/blob/df7ee033cb43f9a08cad21f11001af574220c5d5/main/src/cgeo/geocaching/utils/FileNameCreator.java#L29

**Comment by fm-sys** [comment]
Sure. Although it's not a big thing, we would be happy about an PR...
