### ISSUE TITLE
New gallery shows progress circle instead of preview

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13206]
### Describe your problem!

I cannot clearly reproduce that, but sometime when I first time load/open a cache and swipe to the new gallery some images are still shown as "loading in progress". 
In normal cases they appear after loading has finished but I also experienced caches, where this did not happen also after some minutes. The progress indication just keeps showing forever while I do not see any data transfer or pending http requests. 

In such situation I can tap on all of those "in progress" images and they are shown fine in the single picture view.
Once I close the picture view and get back to the gallery tab, the "progress indicator" is still shown.

It looks like sometimes after the loading is finished in the background the "progress indicator" is not replaced by the actual preview.

### How to reproduce?

- Open a not before opened/stored cache either via its geocode or from map
- Swipe to the new gallery tab

### Actual result after these steps?

Sometimes images keep showing the "progress circle" endless

It does not necessarily affect all images, sometimes none, sometimes only some

### Expected result after these steps?

All images loaded

### Reproducible

Unclear

### c:geo Version

2022.06.06 and master

### System information

```text
Android 12, Samsung S20
```

**Comment by eddiemuc** [comment]
Current implementation isnjot adequate in many ways. I propose a new implementation using Fragments and recyclerview and will work in this as soon as I can find the time (which is currently not the case).

I would thus not invest any time in current implementation any more. If implementation is not acceptable, then let's deactivate new gallery for now.

**Comment by Lineflyer** [comment]
> If implementation is not acceptable, then let's deactivate new gallery for now.

Its great and far better than the old one.
Just reporting the findings from my last caching session..no offense :)

So we can stack this issue into the backlog for now.

**Comment by eddiemuc** [comment]
> no offense :)

No offense taken :-)

**Comment by Lineflyer** [comment]
No longer happening after changes / reimplementation of the new image gallery.
