### ISSUE TITLE
maps.me navigation not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13209]
>>> **See further down in this opening article for current state of workarounds.**

### Describe your problem!

Several user reports, that maps.me navigation is no longer working. It behaves as if maps.me is not installed (showing the installation link instead).

I can not reproduce on my device, but reporting users use a more recent maps.me version which is not available on Google Play for my account (yet).

Working maps.me version: 12.3.3-Google  (edit: fixed version number to 12.x)
Failing maps.me version:  13.0.71327 (and newer versions)

The API integration did not have any update since 2019, thus I suspect a problem on their side with more recent maps.me versions.

### How to reproduce?

- Have maps.me app installed
- Open a cache
- Select Navigate - Maps.me

### Actual result after these steps?

It shows the message to install maps.me although its already installed:
![image](https://user-images.githubusercontent.com/949669/175827988-f0424d0b-bd53-4f42-bfc0-63b7fd626853.png)

(Edit: This is a message coming from the maps.me integration API code, not from c:geo itself. This messagebox is triggered by the integration code not being able to detect the installed maps.me app.)

### Expected result after these steps?

Maps.me should open with target set to the cache coordinates.

### Reproducible

Yes

### c:geo Version

2022.06.06

### Additional Information

Support tickets 726566, 126520, 718492, 621874, 419584 (and others)

Edit: as of 2022-07-27 we have app. 50 support tickets regarding the integration, but still no reaction from maps.me

## Possible workarounds

Users of c:geo have provided us with individual workarounds working for them. Both require some technical knowledge and may not work in your specific setting. While both descriptions look reasonable, we have not tested them, so if trying to implement one of these in your environment you do so at your own risk. If you feel unsafe with any of the steps involved, please do not apply the workarounds.

### Workaround 1: Use older version of maps.me app

As versions 12.x have worked, and only versions 13.x and up contains the assumed bug in maps.me app, you can try to replace your current installation of maps.me with an older version, 12.x max.

- [Download version 12.x of maps.me app from apkmirror.com](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=maps.me) - Make sure to select the 12.x version (still available as of 2022-07-30)
- Check the downloaded file for viruses etc. with a scanner of your choice (eg. [Virustotal](https://www.virustotal.com))
- Copy the downloaded apk file to your mobile and install it. You may have to temporarily allow installation of apk from unknown sources - make sure to disable this option after applying this workaround.

### Workaround 2: Import caches using kml:

Instead of directly opening a cache from within c:geo into maps.me, another user exported and converted bulk data, and imported it into maps.me:

- export caches as GPX
- convert GPX file to kml
- open this kml file with maps.me
- maps.me will create a bookmark file from it and display the caches

**Comment by Lineflyer** [comment]
Opened an issue on their side (see link above).

**Comment by moving-bits** [comment]
caught the wrong id in my pr, so let's reopen

**Comment by Lineflyer** [comment]
Sent a mail to business@maps.me as there is no reaction here.

**Comment by dcj99b** [comment]
Hi
I have exactly the same problem, but I dare not download Maps.me from the link, as I am already registered with maps.me and I have paid an annual subscription for the version I am using. I use Maps.me with other apps, so don't want to screw those up.
Please can we have an answer soon.
Regards Derek C Johnstone

**Comment by dcj99b** [comment]
Sorry, I've just checked.  Maps.me stopped their subscription model in 2021, and haven't taken any money. My subscription was cancelled in 2021.
Regards  Derek C Johnstone

**Comment by moving-bits** [comment]
Thanks for the provided link. According to the text in the [link](https://github.com/mapsme/api-android/issues/37) as well as on the [OSM page for Organic Maps](https://wiki.openstreetmap.org/wiki/Organic_Maps), Organic Maps seems to be a fork of maps.me, done by one of the original founders of maps.me. So it _may_ be an alternative for our users to use this instead of maps.me (have not tested this!), but we would have to adapt our integration code / add a new navigation entry. (And users not willing or not able to switch still would not be able to use maps.me with c:geo.)

**Comment by moving-bits** [comment]
A user on support described the following workaround which seems to work for him:

_"So I made a GPX export and translated into kml. That I put on my Android and maps.me made inmidiatly a bookmark file from it and I can see in on the map with the CG#####."_

**Comment by Lineflyer** [comment]
As there is still no reaction by maps.me (neither on Github nor from one of the many mails I sent) I suggest to remove maps.me and go for organic maps instead. It is open-source, quite identical (derived from same basis) and there is quite some activity in their repository.

**Comment by Lineflyer** [comment]
As I have seen, that the maps.me has some interaction (in contrast to their repository) I made a last attempt of contacting them by posting to their facebook page. Lets see if this brings any news.

**Comment by Lineflyer** [comment]
No reply on my enquiry on FB.
Meanwhile on the old repository of MAPS.ME someone posted this explanatory link about what happend after version 12.20: https://telegra.ph/What-happened-to-the-old-MAPSME-12-20

I guess we can remove the API towards MAPS.ME...it will never work again.

**Comment by Lineflyer** [comment]
mmh...supporting a company which abandoned open source and left behind broken pieces without any reply on help requests...let me think. I guess we should throw it away and instead give the chance to Organic maps...maybe even direct maps.me users to organic maps.

**Comment by moving-bits** [comment]
I understand your point, but:

For versions > 12 with the changed API we display a message already, stating they have changed their API and don't respond. For older app versions c:geo is still working with maps.me
Removing our integration would break it for those users.

How about adapting the error message users of maps.me v13+ get, to something like "they have turned away from open source, changed their API and did not respond to us, therefore we cannot longer support recent versions of maps.me. Try using Organic Maps instead" (providing a link). Last sentence only when integration with Organic Maps is implemented.

**Comment by Lineflyer** [comment]
We can do that, but I guess most users will have update already as part of their normal GPlay updates...or is there a manual way back?
Anyway I consider this an interim thing and we should remove it in some months instead of keeping not maintained code in for to log.

**Comment by moving-bits** [comment]
Old versions are still available on apkmirror.com, AFAICS (we have linked to it in the opening article of this thread). This is also where we directed some of the users to which have contacted us on support. If we like to, we could even link to it from error dialog box mentioned above.

If we want to remove the API completely, we should give users some sort of upfront-warning, stating something like "we will remove maps.me connection in <date of your choice>", eg. "end of 2022".

I haven't looked into Organic Maps yet, don't know how compatible their API is, and whether there would be a user base requesting interaction to this from c:geo. I guess much of what maps.me was needed for five or ten years ago is available in c:geo nowadays anyway, but gaining from reactions we got on support there seems to be a solid fanbase.

**Comment by moving-bits** [comment]
FYI: We get sporadic requests on support to support Organic Maps (eg ticket 900592). It seems to work somehow based on the outdated maps.me API, but not fully, so we should look into API changes first before offering an official integration into c:geo.

**Comment by moving-bits** [comment]
See https://github.com/organicmaps/api-android for API to Organic Maps (a relatively new extension to Organic Maps, supported since their app version 2022-07-26)

**Comment by moving-bits** [comment]
According to user feedback on support maps.me seems to be back working again with c:geo, so let's close this issue for now.
(Feature request to implement should be a separate issue, if still requested.)
