### ISSUE TITLE
GPS no longer working on Samsung S5 (no c:geo problem)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13220]
This is just an information and question whether you can confirm the rumor below:

The last week several users contacted us, that c:geo does not get any position all of a sudden. All users have a Samsung S5 / S5Neo running Android 6.0.1.
It turned out it affects all apps and the localization is limited to network based localization, but no valid GPS information is available on the system.
I found several forum posts on the net, that a lot of or all(?) devices are affected. 
As this is an Android 6.0.1 device, which is no longer maintained since a while by Samsung the question is, what has happend...

According to rumors in several forums I found, that the possible reason is, that GLONASS signals have been either blocked or limited by Russia and a special chip firmware does not cope with that and fails completely. Is this fake news or does someone have any information about that?

In a quick check with my GPS status app I see at least, that my phone gets signals from GPS, BEIDOU and Galileo but no satellites of GLONASS.

**Comment by Lineflyer** [comment]
Any recent security or other updates?

**Comment by moving-bits** [comment]
Regular Play Store updates, probably including system components - can't say, but the system itself hasn't received updates from Samsung since a long time. Anything specific I can check?

**Comment by bekuno** [comment]
With S5 mini it is the same - see https://eu.community.samsung.com/t5/andere-smartphones/samsung-galaxy-s5-mini-kein-gps-satellitenempfang-mehr/td-p/5592822

**Comment by Narrat** [comment]
Reading the linked thread, the recent messages seem to suggest that it may be working again.

**Comment by moving-bits** [comment]
Seems to have been a temporary problem, and not related to c:geo, so let's close here.
