### ISSUE TITLE
Tagging - filter caches basing on tags

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#13229]
### Tell us your idea!

The idea is to add one or several tags to a cache to do an additional filtering while keeping the caches stored inside the same list.

Why? Nornally I am preparing a weekend or vacation basing on lists. One big list with all destinations(=caches) and several smaller lists for each single day, containing the same caches.

The idea was now to add tags like "Day-1", "Saturday", etc pp to the caches, so I could store them in one list and filter the list basing on tags. 

### What solution would you suggest?

Add a new field to each cache, which is storing the tags per cache.
In addition a list with pre defined tags should be available as well. 

### Is there an alternative?

Storing everything in hundreds of lists...

**Comment by fm-sys** [comment]
You can add a cache to multiple lists. Isn't this exactly what tags would be about?

**Comment by wolverine007** [comment]
> You can add a cache to multiple lists. Isn't this exactly what tags would be about? 

Not really, how should I apply one ore more filters to show for instance every cache where I need a ladder and fishing rod?

**Comment by eddiemuc** [comment]
> > You can add a cache to multiple lists. Isn't this exactly what tags would be about? 
> 
> Not really, how should I apply one ore more filters to show for instance every cache where I need a ladder or fishing rod?
> 
> This couldn't be handled by lists or graphical icons - and even if I try to reflect it somehow, I am still not able to filter it... 

To stay in your example, assuming you have two lists named "fishing rod" and ladder" and you want to filter for caches which are in both of them. Then you can create the following filter using "stored list" filters:

![Screenshot_20220711-073829.jpg](https://user-images.githubusercontent.com/6909759/178196198-2738ed2f-bf11-4483-a1a5-98a2dcab1808.jpg)

**Comment by eddiemuc** [comment]
To filter for caches which are **either** in "fishing rod" **or** in "ladder" (or in both of them), use the following:

![Screenshot_20220711-074124.jpg](https://user-images.githubusercontent.com/6909759/178196424-723ffaeb-deb4-425f-8494-e47698c70746.jpg)
