### ISSUE TITLE
Have comment field for variables

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13250]
### Tell us your idea!

From a user on support mail:

Sometimes is will be helpful to ad a Comment or value for background information related to the actual value (as a reminder). Or if you want to change the value of the variable for some reason, you still know what the original value or origin was. This option is also available into the GDAK App which I used before CGeo came with it for formula calculation (see picture). 

### What solution would you suggest?

Add a comment field to each variable.
See GDAK as example:

![image](https://user-images.githubusercontent.com/949669/177782644-1d47bde7-a297-4a59-934f-7d21fc7e32bb.png)

**Comment by Kumuddel** [comment]
I think this is a good idea and had this requirement a couple of times already.

**Comment by Kumuddel** [comment]
> One can already adda comment directly to the var value using `#`:
> 
> ![image](https://user-images.githubusercontent.com/6909759/177795481-8c10e9c2-b612-4278-8b7b-bbfd230763c7.png)
> 
> But this is probably not what you mean right?

🤦🏻‍♂️ Sorry, for the few times I would need comments this will work just fine.

**Comment by moving-bits** [comment]
Reading above's comments I guess we can close here?

**Comment by Kumuddel** [comment]
Okay by me
