### ISSUE TITLE
Make cache list additional info configurable

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13278]
### Tell us your idea!

Currently we display GC code, D/T rating, Cache size and Premium state as additional info in cache lists.
I would like to see other info here as well, namely year/month of publishing date (for Jasmer challenge), but depending on my current geocaching goals it may be a different info.
On the other hand, I don't care for Premium/Basic state of a cache, so some space could be saved.

### What solution would you suggest?

Make items for additional info line configurable, defaulting to today's items.

Configuration could be a simple multi-item select list (as we have for home screen's additional buttons), to select of a predefined list of items. For a start we could support:
- gc code, d/t rating, Premium/Basic state (those are today's items)
- year/month of cache publishing (for Jasmer challenges)
- (tbc)

### Is there an alternative?

leave it as is

**Comment by ztNFny** [comment]
the current information is manually grouped to fit its designated lines - first line gc code, D / T, second line lists. If this was completly user-configurable how would grouping work?
If e.g. "lists" would be before D / T, gc code then due to the different length of list names gc code would be all over the place.

**Comment by moving-bits** [comment]
Fixed with #14073

**Comment by Lineflyer** [comment]
Although this is already closed:
I would like to see the "last logs smiley row" in there :)

**Comment by moving-bits** [comment]
> Although this is already closed: I would like to see the "last logs smiley row" in there :)

No worries, it's meant to be extensible. 
I'll create a separate issue for it so this request does not get lost.
