### ISSUE TITLE
Display log summary on overview page

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13274]
### Tell us your idea!

User request on support: Display the log summary (number of founds etc.) also in the cache summary on the cache detail page.

### What solution would you suggest?

![image](https://user-images.githubusercontent.com/3754370/181198007-1b05b850-4dd9-4afe-bad7-9a9ca9fbe1f6.png)

### Is there an alternative?

Leave it as is

### Additional Information

ticket #625615

**Comment by ztNFny** [comment]
what's the point of duplicating this information? It's already available just 2 swipes away. Imho it's not important enough to show it there.

**Comment by moving-bits** [comment]
Item got declined, see https://github.com/cgeo/cgeo/pull/14149, so let's close here.

**Comment by Lineflyer** [comment]
Thats IMHO OK. I also don't see a benefit in duplicating information and complexing UI. The only other option would be to move this info from logs to details...but IMHO it better fits into logs tab.
