### ISSUE TITLE
Another offline map source

### ISSUE THREAD

**Issue by osmpaws** [cgeo/cgeo#13273]
### Tell us your idea!

Hi there, I have been asked to make map files I provide on  a website available through in app download thingy so here I am. The site is [osm.paws.cz](https://osm.paws.cz) and some communication already happened before they let me know about this.

### What solution would you suggest?

Please let me know how can I help. Is some documentation available? Do you need some metadata file along map files?

**Comment by moving-bits** [comment]
Are you an Android programmer? You could provide a pull request for c:geo then. We can give you pointers to the relevant source files.

But two questions before: 
- What type of map source is it? Does it provide downloadable map files (Mapsforge .map file format)? (Looks to me, but I do not understand Czech.)
- Do you have written consent of the map provider that we may use their map source for c:geo?

**Comment by osmpaws** [comment]
I did nothing for Android yet, but I can try and we will see 
Yes those are Mapsforge maps. I generate those map files and run the website, so yes, I agree. I already have some buttons for other apps to download maps directly so why not do something for cgeo user as well.

**Comment by moving-bits** [comment]
Ok, if you want to give it a try, have a look at our Wiki pages on how to fork c:geo and start development for it.

The files for the downloader are in the `main/src/cgeo/geocaching/downloader` folder. Have a look at the `MapDownloader...` files as examples. If your maps need a specific theme, you should create two files, a `MapDownloader<your map name>.java` and a `MapDownloader<your map name>Themes.java` files, each having their own DOWNLOADTYPE_xxx constant (see `src/cgeo/geocaching/models/Download.java` for this), and linking from map to theme downloader by defining the `companionType` variable (see `MapDownloaderHylly.java` for an example).

Feel free to ask questions here in this issue or by opening a new entry under [discussions](https://github.com/cgeo/cgeo/discussions).

**Comment by moving-bits** [comment]
What type of integration do you plan? A full-blown integration into our map downloader including automated map updates (as we have for Mapsforge, OpenAndroMaps, Freizeitkarte, and Hylly currently)? Then the way described above is the way to go.

Or would an integration via link on your website suffice? We do support opening maps by tapping on a special link on the website (prefixed with `mf-v4-map://` resp. `mf-theme://`), the map/theme file will be downloaded by c:geo and installed as a map. This is currently implemented for OpenAndroMaps and Hylly, but we could extend this to a more general solution (without automated updates, though), see #13298. When this gets implemented on our side, all you would have to do would be adding a link to your website like you have already done for Locus etc.

**Comment by osmpaws** [comment]
Hi, yes I should manage to replicate what is available for the other sources now. I will put special link as well once it will be implemented for sure, it is a good idea. 
I had a look at downloader source code, it seem like it parse the web page to me. I would prefer to generate some dedicated file, for example XML, at my side to directly inform cgeo app what is available to download. But I can see this way is universal for all sources, so why not. Thanks for the info, I will do a pull request but I guess it will take some time.

**Comment by moving-bits** [comment]
> I had a look at downloader source code, it seem like it parse the web page to me. I would prefer to generate some dedicated file, for example XML, at my side

This can be done as well, have a look at the Freizeitkarte downloader, it uses a repository file.

**Comment by osmpaws** [comment]
OK, now I see what is up with links with special protocol after I looked at other files in the directory. The functionality is there, just hardcoded for some sources. I misunderstood the other ticket and thought it will be fresh new thing. I like the auto update so I would start with that and thanks for link to the right source code for inspiration.

**Comment by moving-bits** [comment]
FYI: The "special link" option mentioned in https://github.com/cgeo/cgeo/issues/13273#issuecomment-1200433732 has been implemented meanwhile as is available in current beta version we have published this week. This is the "general" version which supports downloads but no automatic updates.

**Comment by osmpaws** [comment]
Hi, I am working on it from time to time. How can I test the function when it is done?

**Comment by moving-bits** [comment]
> Hi, I am working on it from time to time. How can I test the function when it is done?

You open the map, go to the "layers" symbol, open the downloader. Your new map type should be visible in the map type selector (currently listing "Mapsforge", "OpenAndroMaps", "Freizeitkarte" and "Hylly"). On switching this to your map type, the list below should populate with the available downloads from your server, the entries being one of the types "theme" (palette symbol), "folder" (folder symbol) or "map" (map symbol).

Tapping on a folder will switch to that folder, tapping on either map or theme should download that file in the background (giving you a notification), making it available in map/theme selection on successful installation.

To see which downloads are currently running, go to settings => system => show downloads.

To test the upgrade functionality you either have to wait until a new update is available on your server ;-) or you need to manipulate the contents of the so-called "companion file" in the maps/themes folder on your test device. A "companion file" has the name of the downloaded map/theme file, but with the additional extension "-cgeo.txt" (eg: "test.map" => "test.map-cgeo.txt"). It contains, among other things, the date that you have downloaded that file. If the parsed date from the server is newer for this file, it's regarded as "update available".
You can trigger the update check from either c:geo's home screen ("update offline data" => "maps") or from the map downloader ("check for updates").

Feel free to ask here (or open a new [discussion](https://github.com/cgeo/cgeo/discussions)) if any questions arise.

**Comment by osmpaws** [comment]
Hi, I meant how to test the code whether it works at all, or it would be OK to pull request something and loop,

**Comment by moving-bits** [comment]
> Hi, I meant how to test the code whether it works at all, or it would be OK to pull request something and loop,

I guess you have a development environment set up (Android Studio etc.)? 
(For more infos on this see our project home page (https://github.com/cgeo/cgeo).)

With a working development environment you can compile c:geo and run your developer build locally in the emulator. Besides running the tests that come with c:geo, you can start testing the functionality you have implemented, as described in my previous post.

If you feel confident that your PR generally works, you can create a PR in this repository, so that team members can start a review. Also if you think it's mostly working, but still need some polishing, you can open a so-called draft-PR and ask all questions needed to smoothen rough edges.

Thanks for diving into this issue!

**Comment by moving-bits** [comment]
This has been implemented meanwhile and is available in c:geo nightly versions, so let's close here.

Thanks @osmpaws for your contribution, very welcomed!
