### ISSUE TITLE
Use last map position instead of home coordinates if no GPS is available

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13275]
### Tell us your idea!

User request from support, but I've experienced the same during my vacation: If no GPS is available (eg: turned off), c:geo resorts to using the last known home location. User the last known map position instead (maybe make it configurable).

Using home location may fit for most occasions, but not when you are on tour (vacation, business trip etc.) in a different area, it's really annoying when you have to pan the map back to the location where you are actually, extra annoying when it's a large distance.

### What solution would you suggest?

Use the last known location on the map instead, and only resort to home coords, when no last map coordinates are known.
Or make it configurable between "last known map" and "home coords".

### Is there an alternative?

leave it as is

### Additional Information

ticket #683319

**Comment by Lineflyer** [comment]
Let me add an update / different proposal for this request:

I had a user with the same problem on support mail, but his suggested solution was quite straight forward:

If I have "Lock on position" on, end c:geo and start it again, I do understand, that it jumps to my home location if no GPS is available (as that's the best guess c:geo can do). However if I leave the map without "lock on position", end c:geo and start it again it should simply open where it was when I last left it.

Following this rule we would not need any setting but just use the state of "lock to position" for determining on what location the map opens next time.

**Comment by moving-bits** [comment]
If I'm not mistaken the "follow my location" / "lock on position" state is not persisted, but c:geo map always starts in "lock on position" mode, which is the reason it always jumps on opening the map, if location is disabled.

Any reason not to persist this state? (No additional (visible) setting needed)
