### ISSUE TITLE
Unreadable Number Cache Symbols

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#13282]
### Describe your problem!

Since a while, it is possible to set the digits 0-9 as cache ssmbols / emojis. However, the rendering is white on the white circle marker and thus unreadable. This occurs in both light and dark theme.

### How to reproduce?

Set digit as cache symbol

### Actual result after these steps?

empty white circle marker in cache lists and on map

### Expected result after these steps?

digit should be readable in dark font against light background on marker in cache lists and on map

### Reproducible

Yes

### c:geo Version

2022.06.06

### Additional Information

![Screenshot_20220728-014700_cgeo](https://user-images.githubusercontent.com/12250212/181392492-6e759799-dc76-49c1-888c-65c0276753c5.jpg)
![Screenshot_20220728-014715_cgeo](https://user-images.githubusercontent.com/12250212/181392507-c7af8db3-a1ac-4941-aea7-1671a8acaadd.jpg)
![Screenshot_20220728-014839_cgeo](https://user-images.githubusercontent.com/12250212/181392527-a372710d-21eb-4f98-bd73-a71d0e60dbde.jpg)
![Screenshot_20220728-020246_cgeo](https://user-images.githubusercontent.com/12250212/181392609-0488856d-501e-4571-afd8-abb8e08886c0.jpg)

**Comment by ztNFny** [comment]
![Screenshot_20220729-080642](https://user-images.githubusercontent.com/1258173/181714142-72e513f0-8043-4502-a539-c7584141894b.jpg)
Black here. Unfortunately there's no standard how emojis look, so whoever creates the font makes some decision. Your devices vendors course to make them white.
As those are glyphs it's not possible to influence the font color.

**Comment by Lineflyer** [comment]
The last comment on this issue states, that it is a device specific issue and thus not solvable in c:geo.
