### ISSUE TITLE
Prepare bugfix release

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13296]
### Tell us your idea!

As proposed in https://github.com/cgeo/cgeo/pull/13294#issue-1323265176 I plan to prepare a small bugfix release this evening.

This will come with a [handful of small fixes](https://github.com/cgeo/cgeo/blob/release/main/res/raw/changelog_bugfix.md), most of them in the nightlies for weeks already, and with the change of the maps.me dialog (see #13294).

- [x] Check/insert correct version name
- [x] Wait for a Crowdin cycle or trigger sync manually to get a pull request from Crowdin with the version name in the translated files.
- [x] Merge the related Crowdin translation pull requests for branch release
- [x] Build release on CI server
- [x] Perform smoke test with resulting cgeo-release.apk before continuing
- [x] Upload and publish cgeo-release.apk to Google Play
- [x] Tag the release on Github in format market_yyyymmdd
- [x] Publish the release on Github including upload of cgeo-release.apk to Github
- [x] Publish release on F-Droid
- [x] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)
- [ ] Post release info to Facebook
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment]
Release is available on Play Store...

Thanks to all contributors of this release!

**Comment by bekuno** [comment]
@Lineflyer 
Should this be closed or will you post something on Facebook?

**Comment by Lineflyer** [comment]
Lets close...now its already quite some days old
