### ISSUE TITLE
store offline if cache has manual/edited info

### ISSUE THREAD

**Issue by hmersch** [cgeo/cgeo#133]
(Add an option to) automatically store cache for offline use, if anything was changed by the user manually.

From time to time I start with a cache just from the live map - and start editing/adding waypoints etc. 
hitting the back button once too often  means to "loose" cache-details. 
Well actually my added information seems to be stored locally since after finding the cache again all manual added data is back within the description...

For this scenario, if a user obviously is doing a cache since data is added: Please store all retrieved data locally - murphy defines that no network is available if cache description is left ;-)   

Comments?

Best regards - Henning

**Comment by Lineflyer** [comment]
Background saving of a cache in the case it has user modified information has been implemented meanwhile.
The cache will be stored as soon as one of those things happen:
- A waypoint is created
- A personal note is created
