### ISSUE TITLE
User note leading to auto-waypoint and auto-variables

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13314]
### Describe your problem!

User on support:

Entering coordinates into user note results in automatically created waypoint (ok), and additionally automatically created variables.

### How to reproduce?

- Add coordinates to user note of a cache, eg "N 48° 29.256' E 009° 55.858" (waypoint extraction not disabled => a user-defined waypoint will be created, no variables yet)
- add waypoints to user note using the button

### Actual result after these steps?

- two variables are created (N=48, E=9)
- on updating waypoints to user note, those variables are added to the user note as well

### Expected result after these steps?

do not create those vars from user note text

### Reproducible

Yes

### c:geo Version

2022.06.06

### Additional Information

ticket 581660

**Comment by eddiemuc** [comment]
Duplicate to part of #13180, should already be fixed with PR #13181
