### ISSUE TITLE
Checksum formula giving wrong results

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13313]
### Describe your problem!

@eddiemuc?

User on support:

Das Ergebnis von checksum(17639129876) wird als 43 ausgegeben.
Richtig ist aber 59.

Testen lässt sich das einfach:
Ziffer 6 am Ende der Zahl löschen -> ergibt das korrekte Ergebnis 53.

Weitere Auffälligkeiten:

Wenn ich die Variable
zahl = 1234567890+16404561986
setze (ergibt 17639129876), und
qs = checksum($zahl)
berechnen lasse, ergibt sich
qs = 46
Das ist auch falsch (und ergibt ein anderes Ergebnis als oben, obwohl 
die Berechnung identisch sein sollte).

Weitere Tests:

cs(123456789)   = 45  # korrekt
cs(1234567891)  = 46  # korrekt
cs(12345678910) = 47  # falsch
cs(12345678911) = 46  # falsch
cs(12345678912) = 45  # falsch
cs(12345678913) = 44  # falsch
cs(12345678914) = 43  # falsch
...
cs(12345678918) = 39  # falsch
cs(12345678919) = 47  # falsch

### How to reproduce?

go to cache details, variables tab, create variables/formulas as described above

### Actual result after these steps?

see above

### Expected result after these steps?

see above

### Reproducible

Yes

### c:geo Version

2022.06.06

### Additional Information

ticket 398151

**Comment by eddiemuc** [comment]
I will check.

Probably an int overflow error (1763912987 < 2^32 < 17639129876)?

**Comment by eddiemuc** [comment]
PR #13318 should fix this:

![image](https://user-images.githubusercontent.com/6909759/183267525-f44c0fca-a69e-4dc3-862c-a5130d80ac4b.png)
