### ISSUE TITLE
Keyword search vs. BM?

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13312]
### Describe your problem!

User on support:
- search by keyword "Rävafallet", results are similar to a plain nearby search, found caches do not contain the keyword
- user is a basic member
- no caches stored offline that contain that keyword

on further testing he stored some caches containing that keyword
- now while entering the keyword he gets related caches as autocomplete suggestion
- but the search itself still delivers only results unrelated to the given keyword

Which raises two questions:
- Does search by keyword only work for PM (and if so, shouldn't we disable it or add a hint, if the user is a basic member)?
- Will/should caches stored locally be included in the search result?

### How to reproduce?

- login to c:geo as a basic member
- do a keyword search, eg by "Rävafallet"

### Actual result after these steps?

search results look like a plain "nearby" search has been performed, found caches have no specific relation to the keyword given

### Expected result after these steps?

if technically possible: search result should deliver caches containing the given keyword,

otherwise "search by keyword" should be disabled or a specific hint given, if "search by keyword" is not available to basic members

### Reproducible

Yes

### c:geo Version

2022.07.31

### System information

```text
ticket 218005
```

**Comment by tobihein** [comment]
I also have the same issue with version 2023.12.21 (installed from f-droid-store).

I am also a basic member

**Comment by eddiemuc** [comment]
It is quite likely that keyword search on GC.com does not work for BM because it is also not offered on the website for BM.

But we can't just remove the keyword search for BM because on other geocaching platforms (eg oc) keyword search will of course work.

**Comment by tobihein** [comment]
Thanks for the explanation. I am pretty sure that this worked in the past (years ago).

In that case a small hint in the app would be nice and avoid confusion. But I am not a power-cacher so I don't know if it makes sense in all cases. 

Is it possible to check programmatically if it is a geocaching basic account?

**Comment by moving-bits** [comment]
> It is quite likely that keyword search on GC.com does not work for BM because it is also not offered on the website for BM.
> 
> But we can't just remove the keyword search for users logged in as BM at GC.com. Because on other geocaching platforms (eg oc) keyword search will of course work.

A mitigation could be to check if the user has activated only geocaching.com connector + is a basic user, and if so, disable keyword search. Not 100%, but would be fine for a larger group of users.

> Is it possible to check programmatically if it is a geocaching basic account?

Yes, we do have that information.

**Comment by SammysHP** [comment]
Does it work for offline stored caches, though?

**Comment by eddiemuc** [comment]
> Does it work for offline stored caches, though? 

All searches on the "search" page are pure online searches. If some of the found caches are already stored locally then this is displayed in the result list ("saved" icon). Further local filtering of the returned online list will also consider locally stored data for those caches if available.

"Searching" in ofline stores caches is done via filtering in stored lists. There, one can filter by geocache title. This works of course.

**Comment by fm-sys** [comment]
The keyword search also offers offline suggestions, but this is pretty useless for BMs anyway IMHO. They can still use the main search...

![Screenshot_20231225_175802_cgeo geocaching](https://github.com/cgeo/cgeo/assets/64581222/4c010821-e74c-4064-a439-fce5e509af15)

**Comment by eddiemuc** [comment]
> Thanks for the explanation. I am pretty sure that this worked in the past (years ago).

I just found the time to double-check in the browser. Unfortunately the API we use for online search at gc.com seems to ignore the keyword search parameters for BM users. I can't tell for how long this has been the case (and whether this API worked before for BM users), but it would be consistent with the website UX offered by gc.com.

**Comment by moving-bits** [comment]
Mitigation has been implemented, so let's close here for now.
Feel free to reopen (or create a new issue) if further work on this is requested.
