### ISSUE TITLE
Add fullscreen mode to c:geo

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13315]
### Tell us your idea!

From Support:

A user is using c:geo mostly in landscape mode, but there's only a small fraction of the map visible due to toolbar, side menu and bottom navigation.

### What solution would you suggest?

Offer an optional "full screen" mode, which auto-hides toolbar / menu / bottom navigation etc., and displays them on demand (eg: a special button or swipe gesture in a specific place/direction)

(Which elements to auto-hide is TBD)

### Is there an alternative?

leave it as is

### Additional Information

ticket 987083

**Comment by fm-sys** [comment]
This was discussed in #11841, however it was considered not intuitive enough...

**Comment by fm-sys** [comment]
Maybe it could however be implemented as an optional feature (off by default)

**Comment by fm-sys** [comment]
> 
> 
> > > Maybe it could auto-hide on map view?
> > 
> > 
> > This would definitely be possible, and other apps are doing this as well. Although, I'm not sure if this will rather confuse users...
> 
> Seeing that Google Maps as THE most popular map app is doing it it should be ok. Others like Locus also do auto-hide btw.

Coming back to the auto-hide functionality. This could look like this: 

The animation needs to be improved for sure, but is this wanted in general?

![Animation](https://user-images.githubusercontent.com/64581222/140982701-4b0bf46e-15fe-4a89-81b8-0478057f27dd.gif)

Development started in https://github.com/fm-sys/cgeo/commit/8b7467bcbba1269779c0d63e0aedf7be913989a5

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/11841#issuecomment-964419212_

**Comment by moving-bits** [comment]
A few thoughts from my side:
- I would not use auto-hiding, as the "bumping screen" is somewhat disturbing, missing menu navigation may be counter-intuitive, and functionality is not really needed in portrait mode on today's long screens.
- But what about "hiding on demand"? (as well as unhiding) - Button could be enabled (default=off) via settings, and be displayed above the zoom buttons (to not disturb too much in landscape mode)
- Filter bar should also be hidden
- Can the animation be made less bumpy? (Eg by simply extending the visible map, and by moving the map controls to their new place.)

**Comment by Buntbart** [comment]
I would also like to see a button above the "+" button. It should have a fullscreen icon, something like: https://lite.qwant.com/?q=icon+fullscreen&t=images

**Comment by moving-bits** [comment]
I did some experiments today, based on the ideas in [fm-sys@8b7467b](https://github.com/fm-sys/cgeo/commit/8b7467bcbba1269779c0d63e0aedf7be913989a5)

As my main goal was to give more vertical room for the map in landscape mode, I focused on hiding the action bar on demand, avoiding a jumping map. I have a working implementation for OSM by now, and will try to get this running for GM and UnifiedMap as well.

![image](https://user-images.githubusercontent.com/3754370/222264699-64ff606a-30ea-4a0a-9b68-6f7deacad043.png)

![image](https://user-images.githubusercontent.com/3754370/222264734-1b142c45-e2f1-48df-aa25-b71cf2c08620.png)

On tapping on a free map space, action bar hides/unhides, filterbar and distanceinfo will adjust as required, but the map itself stays in exact the same position, just unhiding the parts of the map that were hidden before by action bar / filter bar.

This is how it looks on a smaller screen:

![image](https://user-images.githubusercontent.com/3754370/222266969-e03da507-8bac-402d-b938-6b2c42f8d4e4.png)

![image](https://user-images.githubusercontent.com/3754370/222266950-8f6ad22e-e1ca-41fe-ab6d-d442578dbf73.png)

I had started implementing this for landscape only, but as it may be useful in portrait mode as well, I removed the landscape check.

If we want to gain even more vertical space, we could hide the filterbar as well, and only show a filter symbol somewhere to indicate an active filter. (One could even hide the statusbar and go into an actual fullscreen mode, but I'm not sure if I want to go that far.)

**Comment by fm-sys** [comment]
Two thoughs:
- we might want to hide the bottom navigation as well together with the action bar
- we'll need to make this gesture customizable, as many users probably won't like it (maybe even defaulting to 'off'? Can be adjusted based on beta feedback...)

BTW, back in the days when I initially suggested that gesture, it was inspired by Google Maps. However, it seems like they removed this gesture meanwhile.

**Comment by moving-bits** [comment]
> * we might want to hide the bottom navigation as well together with the action bar

I intentionally left that part out, as we do not have an issue with space in portrait mode, and in landscape mode (which this PR is mainly intended to) we have this nice navigation rail. But this can be discussed for sure.

> * we'll need to make this gesture customizable, as many users probably won't like it (maybe even defaulting to 'off'? Can be adjusted based on beta feedback...)

with "customizable" you mean enable/disable?
Yes, could be done, and if so, I would default to "no". 

But let's wait for beta feedback for both points, IMHO.

**Comment by Buntbart** [comment]
I would find a fullscreen mode for the map handy in both portrait and landscape mode. The bottom navigation could also be hidden in this.

However, I think that an unintentional activation for this function should be avoided as much as possible. 

Therefore I still plead for a dedicated button to activate and deactivate. It should be close to the zoom buttons.

**Comment by moving-bits** [comment]
I'm not confident about using a separate button for it (although I may have proposed it myself in the past):
- If we place such a button close to the zoom buttons, one may hit it accidentally while using the (frequently used) zoom buttons.
- If we place it a bit more above the zoom buttons, it takes up precious map space in portrait mode. If we place it beside the two quick settings buttons instead, it takes up more precious space in landscape mode.
- We could put it in the "quick settings" buttons row, and put those buttons to the right in landscape mode, though, similar to what we do with bottom navigation becoming a navigation rail in landscape mode. This may be a good idea for the two "quick settings" buttons anyway.

OTOH we could simply put this functionality into the "long tap" popup menu. Still easily accessible, but no risk of being hit accidentally (as in currently used "short tap" mode or as when putting it too close to the zoom controls), and no need for a separate setting. 

What do you think?

**Comment by Buntbart** [comment]
I think longpress is already in use in c:geo with other functions like routing. I turned that off for me because it happened too often by accident. The button would be a variant that people already know from other contexts like video players.

**Comment by moving-bits** [comment]
I've thought a bit more about possible solution of putting the two "quick settings" and the proposed "maximize map" button above the zoom elements in landscape mode: This will fail, as there is not enough space for all three buttons (see screenshots above), even not in the high resolution screen (especially not, if you have activated the "maximized distance view"). One or two buttons would be ok, I guess (need to test this), so either "quick settings" buttons or "maximize map" button, but not all three of them.

> I think longpress is already in use in c:geo with other functions like routing.

Currently longpress is about routing and creating user-defined waypoints/caches, but there are more things to come, e. g. hiding/unhiding of tracks. Hiding/unhiding UI elements to maximize map view would fit in well, IMHO.

@cgeo/team:
Any opinions / ideas on this? Or shall we put it into nightlies first, and wait for more user feedback?

**Comment by fm-sys** [comment]
> @cgeo/team:
Any opinions / ideas on this? Or shall we put it into nightlies first, and wait for more user feedback?

+1 for nightlys. We should IMHO test how likely it is to trigger this action accidentally before thinking about possible solutions for it.

**Comment by fm-sys** [comment]
> "maximize map" button 

In my opinion another map button for a rather irrelevant feature wouldn't be worth the map space it would cost. Especially as the original idea of this feature was to gather more map space.

**Comment by moving-bits** [comment]
Has been in the nightlies for quite some time now, so let's close here.
