### ISSUE TITLE
"Select item" popup is not shown on GMaps for closeby caches

### ISSUE THREAD

**Issue by Lomanic** [cgeo/cgeo#13332]
### Describe your problem!

When using OSM layer/Mapsforge map in cgeo, you have a popup to distinguish closeby items when tapping on them. But this useful popup is missing on GMaps.

Only because my new phone didn't have the Google Play services enabled for a while did I discover [this Select item popup](https://github.com/cgeo/cgeo/blob/4dd6f40267dd08bb5e341cbc2277027928dc545d/main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java#L1297) while using OSM.org map layer. It looks like it was introduced years ago ([even before that commit it seems](https://github.com/cgeo/cgeo/commit/f311215175cf437da7fd5ce4924232a98b92dfe0)).

### How to reproduce?

(phone needs Google Play Services enabled)

1. Go to the Map menu, enable Live map
2. Show an area with caches
3. zoom out till at least two caches or waypoints overlap or are in close proximity
4. tap their location (on both items)

### Actual result after these steps?

* using OSM/Mapsforge, the "Select item" popup, that lets one select one of a few overlapping POIs, is shown, so we can easily select one of the two overlapping caches
* using Gmaps, the Select item popup is not shown, only a CacheDetailActivity ([according to some visible strings](https://github.com/cgeo/cgeo/blob/4dd6f40267dd08bb5e341cbc2277027928dc545d/main/src/cgeo/geocaching/CacheDetailActivity.java#L2706)?) popup shows up for one of the two overlapping caches

### Expected result after these steps?

We should have the same behaviour on both OSM and GMaps, with the very practical to have "Select item" popup shown for caches in proximity on GMaps too

### Reproducible

Yes

### c:geo Version

2022.08.10-NB-4dd6f40

**Comment by fm-sys** [comment]
This inconsistency is already tracked in  #7511, please add additional information there if necessary...

**Comment by Lomanic** [comment]
I was not able to find this issue with a search, thank you @fm-sys
