### ISSUE TITLE
show loading indicator while retrieving information for logs

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13337]
### Tell us your idea!

C:geo retrieves information about available log types and TBs in inventory when opening the log screen. During this time a log can't be sent and an error dialog is displayed.

Instead of having to guess when the losing is done and repeatedly pressing the send button to get that error dialog a "loading" indicator should be shown and the send button disabled during this time.

**Comment by fm-sys** [comment]
Good idea 👍

**Comment by Lineflyer** [comment]
related to or alternative (part) solution for #13338 ?

**Comment by ztNFny** [comment]
> related to or alternative (part) solution for #13338 ?

not really. Saving offline is not an alternative in that situation - if I want to do that I just go back. I just don't want to guess repeatedly when it's done loading.

**Comment by Lineflyer** [comment]
No, I meant it in the other way around.
If that error message is no longer present due to the sending button not available, users can directly select save offline from the menu.

**Comment by ztNFny** [comment]
Actually there's a progress bar already in the code: ActivityMixin.java is calling "activity.setSupportProgressBarIndeterminateVisibility(show);"
But that one is no longer provided by AppCompat - since 2016!

**Comment by fm-sys** [comment]
> But that one is no longer provided by AppCompat - since 2016!

As you can see, c:geo's code base is quite old 😅

**Comment by fm-sys** [comment]
It's not intuitive for a user if a button is disabled and you don't know why. So adding the progress indicator is must have IMHO...

**Comment by ztNFny** [comment]
> So adding the progress indicator is must have IMHO...

Agreed. It must be a non-blocking one though (so you can write the log while the log options are loading).
https://github.com/cgeo/cgeo/issues/13341 is the correct place to implement that - that should then also fix the needs in this one.

**Comment by fm-sys** [comment]
Hi, I just tested #13339. Does it do any good? At least on my device, it is visually not clear whether the button is currently disabled or not... Which makes it feel like the button is broken. I see multiple possibilities:
- restore the previous behavior
- color the disabled icon gray instead of white
- in case of information net yet being available, show a floppy disk icon and perform offline logging instead (like suggested in #13338)

**Comment by ztNFny** [comment]
> Does it do any good? At least on my device, it is visually not clear whether the button is currently disabled or not... 

On my AOSP 13 (and emulator with Android 11) the disabled button is faded which can clearly be differentiated from the active version. 

![image](https://user-images.githubusercontent.com/1258173/187026999-696913a5-e474-4b5e-b447-c8c504458a11.png)


> in case of information net yet being available, show a floppy disk icon and perform offline logging instead (like suggested in https://github.com/cgeo/cgeo/issues/13338)

that'll interfer with muscle memory. You quickly touch the place where the button is, without even seeing which icon is shown. Then you expect the log was sent but it was only stored and you'll never know about that.

**Comment by fm-sys** [comment]
> > Does it do any good? At least on my device, it is visually not clear whether the button is currently disabled or not...
> 
> On my AOSP 13 (and emulator with Android 11) the disabled button is faded which can clearly be differentiated from the active version.

Interesting. Light mode is fine for me as well. However, this doesn't seem to work in dark mode (at least for me, android 10)

|||
-|-
![Screenshot_20220827_130714](https://user-images.githubusercontent.com/64581222/187027500-af153e18-1600-4452-8da0-a1611a5b5d69.jpg)|![Screenshot_20220827_130726](https://user-images.githubusercontent.com/64581222/187027502-b33af018-4cbd-4841-afe4-2f70f5c6f325.jpg)

**Comment by ztNFny** [comment]
> However, this doesn't seem to work in dark mode

Can confirm. So a bug in the dark theme definition.

**Comment by fm-sys** [comment]
The way it looks in light theme can be considered good to go IMHO. However, we definitely need to get the dark theme fixed.

@ztNFny are you going to look into this or do you want a TJ? ;-)

**Comment by ztNFny** [comment]
if you know whether this stuff is defined please feel free to take it - I took a quick look at the color, style, .. xmls and couldn't find anything.

**Comment by fm-sys** [comment]
At least I was involved in switching to the material theme, but basically would be try and error for me as well. Can't promise anything, but I can give it a try...
