### ISSUE TITLE
Replace no longer working `setSupportProgressBarIndeterminateVisibility`

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13341]
We had a generalized progress bar implementation in our code base. However, it seems like it does no longer work: `ActivityMixin.java` is calling `activity.setSupportProgressBarIndeterminateVisibility(show);`
But that one is no longer provided by AppCompat - since 2016!

As this is used in a number of places a global fix should be implemented - by someone with more knowledge of those standard components than me ;-)

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/13337#issuecomment-1215767195_

**Comment by moving-bits** [comment]
> I noticed showProgress(true) in the code of that class which sounds quite fitting, but not sure what it's supposed to do. Legacy stuff, broken?

Not sure. But even if it would work, it was probably designed as blocking progress identicator. However in this case, the loading indicator should not block the whole activity...

Adding a progress indicator is quite easy. Just add a `com.google.android.material.progressindicator.CircularProgressIndicator` view to the layout file and show/hide it at the same places where you disable/enable the "Send" button 

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/pull/13339#issuecomment-1216128672_

**Comment by ztNFny** [comment]
setSupportProgressBarIndeterminateVisibility() used to be non-blocking btw. A real pity it got removed
![image](https://user-images.githubusercontent.com/1258173/185796214-fc46ea92-7645-482a-86f3-31ec51819e25.png)

**Comment by fm-sys** [comment]
> setSupportProgressBarIndeterminateVisibility() used to be non-blocking btw. A real pity it got removed ![image](https://user-images.githubusercontent.com/1258173/185796214-fc46ea92-7645-482a-86f3-31ec51819e25.png)

Honestly, I can understand why they removed it. It didn't had given enough information about what is ongoing. Adding a progress spinner view directly is easy enough and can be used in a more self-explanatory way.

**Comment by ztNFny** [comment]
Suggestion:
- add https://material.io/components/progress-indicators/android#linear-progress-indicators to all layouts that need a progress indicator
- update the existing helper-method to look for a progress indicator in that layout and toggle it

**Comment by fm-sys** [comment]
Maybe it's a matter of taste, but I would prefer a circular progress indicator for indeterminate progresses. Feels more natural IMHO.

**Comment by ztNFny** [comment]
why not circle (imho): circle has a height, thereby leaving 2 options when it's shown:
- move all content down when it's shown and up again when it's hidden -> jumping of the content in page
- overlay it over other elements -> makes using the overlaid elements impossible (if it catches clicks) or at least unintuitive (if the click is still received by the covered element)

A linear progress indicator is only a few px high, it can be overlaid without covering any element

**Comment by fm-sys** [comment]
Fixed by  #13358
