### ISSUE TITLE
Next bugfix release

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13345]
After a release is before the next one... Let's collect issues relevant for next bugfix release:

- [x] https://github.com/cgeo/cgeo/issues/13343
- [x] https://github.com/cgeo/cgeo/issues/13344
- [x] https://github.com/cgeo/cgeo/issues/13356
- [x] https://github.com/cgeo/cgeo/issues/13335
- [x] https://github.com/cgeo/cgeo/issues/13366
- [ ]  #13352

Feel free to edit this item and add new issues if required.

**Comment by Lineflyer** [comment]
I opened #13370 and #13371 
Not sure however whether this is on `master` only or on `release`

**Comment by moving-bits** [comment]
According to Play Store stats, the three items #13343, #13356 and #13366 sum up to about 50% of current releases' crashes, nearly 3.000 for those three alone since its release two weeks ago - very well worth an update, IMHO.

If no one stops me I will start preparing a bugfix release (including the PR for #13343) on Sunday evening.

**Comment by moving-bits** [comment]
Starting to prepare next bugfix release:

- [ ] Check/insert correct version name in /main/res/raw/changelog_bugfix.md
- [x] Wait for a Crowdin cycle or trigger sync manually
- [x] Merge the related Crowdin translation pull requests for branch release
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting cgeo-release.apk before continuing
- [ ] Upload and publish cgeo-release.apk to Google Play
- [ ] Tag the release on Github in format market_yyyymmdd (can be combined with next step if done on Github UI)
- [ ] Publish the release on Github including upload of cgeo-release.apk to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)
- [ ] Post release info to Facebook
- [ ] Post release info to Twitter

**Comment by ztNFny** [comment]
I recently broke TB logging which is in current master (and thus the beta), https://github.com/cgeo/cgeo/pull/13398 fixes that.

**Comment by fm-sys** [comment]
> I recently broke TB logging which is in current master (and thus the beta), #13398 fixes that.

We don't have a beta running currently. The current bugfix release was based on `release` branch which tracks the state of `master` prior to 06.08.2022. BTW, betas are build from `release` branch as well... I'm quite sure TB logging is only broken in the nightlys.

**Comment by ztNFny** [comment]
Ah ok, i feared my snafu could.have made it into this. Good to knwo

**Comment by MagpieFourtyTwo** [comment]
I would really appreciate, if the bug fix release would address issue #12225, too, as this is really annoying in daily work ...

**Comment by Lineflyer** [comment]
I think this issue is already done (i.e. the targeted bugfix release is out).
Anyway bugs should be fixed ;) but lets close here.

BTW:
As posted somewhere else :I suggest to branch from `master` and push a next beta w/o language switch rather soon. So if we missed some bugs due to languages beta users will report it.

**Comment by moving-bits** [comment]
The fix for #13352 is implemented on `release` branch,  but has not been part of the current release already, Shall I create a bugfix release for it before creating a new beta? Or push a beta without a separate bugfix release?

I could go either way tomorrow evening. Today is Giga time in Essen...

**Comment by fm-sys** [comment]
> The fix for #13352 is implemented on `release` branch, but has not been part of the current release already

The fix is even not yet merged. It's still waiting in PR #13409

**Comment by fm-sys** [comment]
> Or push a beta without a separate bugfix release?

IMHO we should go with the beta. Not at least to have more time for testing https://github.com/cgeo/cgeo/pull/13409 in the field...
