### ISSUE TITLE
hillshading for VTM

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13346]
> Will hillshading also work with VTM

There is no such hillshading in VTM.

VTM is an OpenGL map library, rendering (vector) data via OpenGL in real time.
Compared to Mapsforge that converts (vector) data to bitmaps before rendering.

You can use hillshading bitmap tiles, see [MapilionMvtActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MapilionMvtActivity.java) & [DefaultSources](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/bitmap/DefaultSources.java).

_Originally posted by @devemux86 in https://github.com/cgeo/cgeo/issues/12210#issuecomment-1196774408_

**Comment by moving-bits** [comment]
Ideally we would support an offline-only version for hillshading with VTM. Not sure if it's possible, though, to combine OpenGL vector map with bitmap hillshading layer, especially as VTM supports fractional zoom factors.

**Comment by dcjkfgdjhd** [comment]
It would be great if some way to add hillshading to the unified map would be found.

Otherwise, as a mountaineer, I would continue to use the old map. The hillshading really gives you very valuable information about the structure of the terrain.

**Comment by moving-bits** [comment]
An online-based hillshading for UnifiedMap VTM has been implemented with #15415, as well as an offline-based hillshading for UnifiedMap Mapsforge (available in current nightly versions), so let's close here.
