### ISSUE TITLE
[hillshading] appearance settings required?

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13347]
Not sure about this one. Map themes, which is kinda similar, doesn't have its own section either.

I'm also not sure whether pref_mapShadingLinearity and pref_mapShadingScale really need to be user-configurable settings. I've tried to find reasonable defaults for those.
Maybe we could get some feedback during beta whether the defaults are good enough and if they are remove those settings (from GUI at least).

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/pull/13334#discussion_r950840868_

**Comment by Lineflyer** [comment]
I suggest lets first try out the new feature and see if it has customization need.

BTW:
Is there any documentation about how to use it?
Someone interested to add it to the user guide or at least to our Wiki here?

**Comment by ztNFny** [comment]
> Is there any documentation about how to use it?

I've sadly not received any positive feedback from the only "non file-hoster" based provider of dem files (that I'm aware of - http://viewfinderpanoramas.org/dem3.html)
The best (in terms of data quality and completness) source for dem files is collected by https://twitter.com/SonnyLidarDTMs (usually at opendataportal.at, but that's down right now), but the files are hosted on Google Drive which makes them inaccessible to us.
Locus is hosting the dem files on their own servers, but for c:geo I don't think that's an option with a country like germany being ~500MB (3m resolution) due to traffic costs.
That said the best bet seems to be to provide a page in Help pointing at possible sources for users to get dem files - and maybe an "import from sdcard" button in c:geo to move them to a proper directory.

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/12210#issuecomment-1189520387_

**Comment by ztNFny** [comment]
@Lineflyer how do I get an account to edit the wiki?

**Comment by ztNFny** [comment]
As I'm not sure how to add anything to documentation/FAQ I wrote some texts and am putting them here, please add them where needed (and please feel free to improve the texts):

### Hillshading
#### What is hillshading?
Hillshading is a technique for creating topographic relief maps by adding a lighting effect to the map to indicate changes in elevation. Sloped will be darkened/lightened to generate a 3D-effect.

#### How to use hillshading in c:geo?
Hillshading is available only with offline maps. To use it configure a folder containing the hilldshading definition files in "Settings > Map > Map Shading Files Folder".

#### Where to get hillshading files?
Multiple sources exist for hillshading files with different coverage and resolution. The files are required in "hgt" format and must be placed in your devices "Map Shading Files Folder".
Most sources offer them by degree-coverage with popular sizes being 1" (1x1°, resolution of 30m) and 3" (3x3°, resolution 90m).

Sources:
| URL                                                                          | Coverage                 | Resolution |
|------------------------------------------------------------------------------|--------------------------|------------|
| https://sonny.4lima.de                                                       | Europe                   | 1", 3"     |
| http://viewfinderpanoramas.org/dem3.html                                     | World                    | 3", 15"    |
| http://viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org1.htm | USA, Europe, New Zealand | 1"         |

**Comment by ztNFny** [comment]
@Lineflyer can you please add this to the docs?
And once that is done we should add the link to FAQ inside c:geo settings, same as exists for "Info on Map Themes"

**Comment by ztNFny** [comment]
Another item for the FAQ:

### Hillshading not working
If you placed the files correctly but are not seeing any hillshading it might be due to your map theme. Switch to c:geos "default" map theme to see if it's working then.
If that's the case please use another map theme or contact your map themes author to support hillshading.

**Comment by SammysHP** [comment]
@ztNFny

> If that's the case please use another map theme or contact your map themes author to support hillshading.

Why does it depend on the map theme? Isn't it a separate layer? What needs to be changed in the map theme?

**Comment by ztNFny** [comment]
> @ztNFny
> 
> > If that's the case please use another map theme or contact your map themes author to support hillshading.
> 
> Why does it depend on the map theme? Isn't it a separate layer? What needs to be changed in the map theme?

See https://github.com/cgeo/cgeo/issues/13538#issuecomment-1283449830

**Comment by dcjkfgdjhd** [comment]
> I'm also not sure whether pref_mapShadingLinearity and pref_mapShadingScale really need to be user-configurable settings.

I just tested it out, and I am super happy that I can custom configure these settings. Please keep the options in!

-----

By the way, the German explanation of the option "linearity" says "low settings hide differences in the plain". This is not at all what I experienced. I had to set linearity to near max, to hide tiny bumps in the plain showing up everywhere in the plain. See screenshots:

Minimal linearity:
![2022-10-19 11 21 15](https://user-images.githubusercontent.com/54892606/196651791-8f732f0b-bbbd-4166-9f47-dc04471b68f7.png)

Maximal linearity:
![2022-10-19 11 20 55](https://user-images.githubusercontent.com/54892606/196651889-4de8e305-d58e-4b07-b55c-ae007229b986.png)

**Comment by Lineflyer** [comment]
> Locus is hosting the dem files on their own servers, but for c:geo I don't think that's an option with a country like germany being ~500MB (3m resolution) due to traffic costs.

How much file space to cover the world?
AFAIR my web space should have no traffic limitation (only a limitation on file space).

> @Lineflyer how do I get an account to edit the wiki?

I will activate an account for you as soon as I get to it using the mail address I have on file.
You will receive a OTP to login and change your password.

**Comment by Lineflyer** [comment]
> > @Lineflyer how do I get an account to edit the wiki?
> 
> I will activate an account for you as soon as I get to it using the mail address I have on file. You will receive a OTP to login and change your password.

Correction:
You happen to have an account, if you forgot the password, try the PW-reset:
https://manual.cgeo.org/de/start?do=resendpwd

**Comment by ztNFny** [comment]
> > Locus is hosting the dem files on their own servers, but for c:geo I don't think that's an option with a country like germany being ~500MB (3m resolution) due to traffic costs.
> 
> How much file space to cover the world?
> AFAIR my web space should have no traffic limitation (only a limitation on file space).

No idea. We'd have to check with one of the authors for copyright though before we do that. I'd guess 50GB min.

**Comment by ztNFny** [comment]
> Correction:
> You happen to have an account, if you forgot the password, try the PW-reset:
> https://manual.cgeo.org/de/start?do=resendpwd

Oops, didn't know I had that... Will add the docu now.

**Comment by Lineflyer** [comment]
> No idea. We'd have to check with one of the authors for copyright though before we do that. I'd guess 50GB min.

Can you ask or connect me?
I have roughly 40GB quota free to use (maybe a bit less as the ticket system will keep growing) and the webspace is payed by c:geo anyway.

**Comment by ztNFny** [comment]
> Can you ask or connect me?
> I have roughly 40GB quota free to use (maybe a bit less as the ticket system will keep growing) and the webspace is payed by c:geo anyway.

I don't have any contacts so far and have some stuff going on right now, so if you could reach out that'd be appreciated. Sources below.
3" is - at least for me - the prefered size as the resolution is good enough for geocaching imho and each file (1°x1°) is 2,75MB, so doesn't take too much space. Its also what Locus uses.
Viewfinder 3" is the most complete source, Sonny has better quality but covers only Europe.

| URL                                                                          | Coverage                 | Resolution |
|------------------------------------------------------------------------------|--------------------------|------------|
| https://sonny.4lima.de                                                       | Europe                   | 1", 3"     |
| http://viewfinderpanoramas.org/dem3.html                                     | World                    | 3", 15"    |
| http://viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org1.htm | USA, Europe, New Zealand | 1"         |

(I don't know how I came to 500MB for Germany before, should be more like 175MB)

**Comment by Lineflyer** [comment]
I contacted Jonathan of viewfinderpanoramas via the contact data in his imprint.

**Comment by moving-bits** [comment]
Here are some more numbers:
- Sonny Germany 3" size: 70 zip files, ~63 MB (~197 MB unzipped)
- Sonny Germany 1" size: 70 zip files, ~388 MB (~1,772 MB unzipped)

**Comment by moving-bits** [comment]
Nice thing about self-hosting those files would be that we could integrate a download & update function for it as we have for routing tiles (including unzipping).

**Comment by SwissPoPo** [comment]
I don't think that the two appearance settings are needed.
What I am missing is an enable/disable option. ...or is there any?
I can remove the hgt files or change the directory to an empty one. But I don't think this is user friendly.

**Comment by ztNFny** [comment]
> What I am missing is an enable/disable option. ...or is there any?

https://github.com/cgeo/cgeo/pull/13565 adds a master-toggle

**Comment by SammysHP** [comment]
Can't this be controlled by the theme settings in the theme XML like a layer?

**Comment by ztNFny** [comment]
> Can't this be controlled by the theme settings in the theme XML like a layer?

Only if the theme offers it as an optional layer.

**Comment by SammysHP** [comment]
But the theme has to enable the hillshading layer anyway.

**Comment by SonnyLidarDTM** [comment]
Just for info:
LiDAR quality elevation files for Europe from Sonny https://sonny.4lima.de
are sized 4.8 GB (1" version) and 0.8 GB (3" version). Perhaps the 3" version is good enough regarding hillshading only.
