### ISSUE TITLE
Searching and showing an exact Coordinate on the map.

### ISSUE THREAD

**Issue by RoNoLo** [cgeo/cgeo#13367]
### Tell us your idea!

I have no idea if I am unable to find that function or it is not there. 

I was trying to solve my first Multi-Cache and the first puzzle was leading to a new coodinate - as usual. I was looking in c:geo for the map dialog were I can enter the N + E coodinates and get a (single) marker on the map thus I know were to go. 
The only dialog I was able to find was the search dialog which has the coodinates search, BUT every time I enter the N + E coodinates I get a list of geocaches which are near at that location. The switch to the map view did not helped at all, I was presented with all possible caches but no pin marker were on the map my entered coodination were.
It was very frustrating and I gave up.

The documentation of the coordinates search also says: "Search for caches around coordinates provided.". 

### What solution would you suggest?

Feature Request:
Could you ADD a map marker to a search result which was using the coodinates as search query, to show where are the entered coodinates are exactly. This would fix that problem for me and in my opinion would not require an additional dialog for a *new* functionality.

Additional idea: When I long press on the map a dialog can *show* me the coodinates I pressed and puts there a pin marker. A dialog item: "Put pin marker on coodinates." which opens an coodinates dialog where I can enter or copy from clipboard would be helpful - in my case - as well.

### Is there an alternative?

If there is, I haven't found it in the app today (2022-08-22).

### Additional Information

Awesome App. :-)

**Comment by Lineflyer** [comment]
For your use case the "normal" procedure would be:
- Open that multi cache in c:geo
- Swipe to the waypoint tab
- Create a new waypoint and enter the derived coordinates for your next stage
- And so on

**Comment by Lineflyer** [comment]
https://manual.cgeo.org/de/cachedetails#waypoint_tab

**Comment by RoNoLo** [comment]
Thank you for your quick help. It's indeed a solution to my problem. Because I never solved a multi cache I was not expecting to solve it _inside_ the cache details view. I just wanted to see it on the map view which I use all the time.

Thanks. If more newbies show up because of not finding the dialog for the exact coodinates marker in the app, you developers might consider an additional dialog in the app. 

For myself. I'm happy with the new knowledge and you could close that issue.
