### ISSUE TITLE
Use new URL scheme for openstreetmap

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13376]
According to https://github.com/openstreetmap/operations/issues/737 openstreetmap recommends some changes for downloading tiles.
We should check if we either already follow those recommendations or change accordingly.

**Comment by ztNFny** [comment]
The Mapsforge version we're using is using those URLs. But imho that should be fixed upstream.

Is there any info about openstreetmap.de? For that we implement the sources ourselves with the a., b., c. tileservers

**Comment by ztNFny** [comment]
> The Mapsforge version we're using is using those URLs. But imho that should be fixed upstream.
> (com.github.cgeo.mapsforge/mapsforge-map/org/mapsforge/map/layer/download/tilesource/OpenStreetMapMapnik.java)

Upstream fix submitted https://github.com/mapsforge/mapsforge/pull/1356

**Comment by ztNFny** [comment]
fix for .de in #13378

**Comment by ztNFny** [comment]
@bekuno could you please update https://github.com/cgeo/mapsforge and point our build.gradle at the latest commit?

**Comment by SammysHP** [comment]
Does the same really apply for openstreetmap.de?

**Comment by ztNFny** [comment]
> Does the same really apply for openstreetmap.de?

Seeing that the only documentation is the one in the wiki and that says to use it without a/b/c it's kinda implied
https://github.com/openstreetmap/operations/issues/737#issuecomment-1233134001

**Comment by SammysHP** [comment]
That is for openstreetmap.org, not .de, a completely different service.

**Comment by SammysHP** [comment]
I see, in the list they recommend the new scheme for de as well. Ok, thanks.
