### ISSUE TITLE
Import menu missing in cache list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13375]
From support mail and for now basically a question to all of you:

Why is there no menu item "Import" in the following screenshot.
IMHO it should always be shown 

Any explanations?

![SmartSelect_20220823-143243_cgeo](https://user-images.githubusercontent.com/949669/187389141-66d4721a-11d2-4fd8-929a-1a556cde0623.jpg)

**Comment by SammysHP** [comment]
You cannot import caches into the "All Caches" list because it's a special kind of list showing caches of all lists.

**Comment by Lineflyer** [comment]
Thats the solution. Thanks @SammysHP 
I did not recognize the finish equivalent.
