### ISSUE TITLE
Waypoints of a cache not being displayed on map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13383]
### Describe your problem!

A user reported on support, that for him waypoints of a cache would not be displayed, if the cache was of type user-defined or adventure lab. He provided his database, and some debugging revealed, that the waypoints in question all had the same value for "prefix". When manually manipulating the database for making the waypoint prefixes unique within the specific cache, the waypoints started to show up on the map.

The waypoints have been generated by copying them from a different cache, using the "copy waypoints", "paste from clipboard", and "delete previous waypoint" method.

So possible cause may lay either in manually creating waypoints or in copying waypoints, then giving those waypoints the same prefix.

### How to reproduce?

(see database and description above)

### Actual result after these steps?

Waypoints are listed on the "waypoints" tab in cache details, but do not show up on the map.

### Expected result after these steps?

Waypoints showing up on the map as well (if not hitting a waypoints limit set in settings => map)

### Reproducible

Yes

### c:geo Version

2022.08.21

### Additional Information

ticket 760512

**Comment by bekuno** [comment]
@moving-bits 
Is the fix for this issue part of the current beta? 
The Issue description here looks like Issue #10652, but the problem in the second one still exists.

**Comment by moving-bits** [comment]
> @moving-bits Is the fix for this issue part of the current beta? The Issue description here looks like Issue #10652, but the problem in the second one still exists.

Yes, the fix is included in current beta. But be aware that this is for a very specific use-case involving copying waypoint to clipboard, and inserting them in a different cache, so unrelated to #10652 to my understanding.
