### ISSUE TITLE
small addition in CGEO

### ISSUE THREAD

**Issue by takius92** [cgeo/cgeo#13397]
### Tell us your idea!

hello, 
I would have 2 small requests for the CGEO software

1 -
when I have caches saved locally and want them updated locally, I don't have much choice
either I have to re-register each cache locally one by one
either I have to re-record the entire thing
  
would it be possible to be able to update the caches by zones/sectors (the zone that I am currently visualizing)

2 -
for my part, I make simple caches
but the mystery caches and the earthcache do not interest me
would it be possible to hide the types of caches that we do not want to see appear?

thank you

edit : 
google translate FR > EN

**Comment by moving-bits** [comment]
For part one you have two choices:
- If you have stored your caches in lists, you can open that list and select "manage caches" => "update all" (or you can activate selection mode, mark the caches to be updated, and select "update selected")
- Alternatively you can open the map, adjust zoom level to include all the caches you want to update, select "show as list" from menu, then "manage caches" => "save offline"

For part two you could create a map filter for "cache type", and deselect the cache types you do not want to see

**Comment by ztNFny** [comment]
> would it be possible to be able to update the caches by zones/sectors (the zone that I am currently visualizing)

Adjust the map to show the caches you want to update, Menu->Store all

> would it be possible to hide the types of caches that we do not want to see appear?

Menu -> Filter -> Add criteria: Cache Type

**Comment by takius92** [comment]
1 -
the submenu that asks what to do must be recent because before the summer I did not have this screen

2 -
I had never seen this cache filter menu
can be seen without touching it

my 2 questions are solved

thank you
