### ISSUE TITLE
Trackable discover state has parsing error (german website)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13412]
### Describe your problem!

When using latest nightly without switch to English (german website), trackable which have been discovered by the user before show a strange status field.

### How to reproduce?

- Open a trackable page of a trackable you discovered before

### Actual result after these steps?

![Screenshot_20220912-185715_cgeo](https://user-images.githubusercontent.com/949669/189713043-bfb2c664-16dd-438b-b956-4c7815bf3e6b.jpg)

### Expected result after these steps?

The row Status should show: "Discovered (date)"

### Reproducible

Yes

### c:geo Version

2022.09.13-NB

**Comment by fm-sys** [comment]
> Edit: Once I change the language to english and refresh the TB page its back to "Status: Gesehen (4. Juni)". It might therefore require a trackable which has been discovered by your account before.

Yes, that was the clue. Only relevant for trackables discovered by the account.

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/13228#issuecomment-1245918546_
