### ISSUE TITLE
Automatically remove "from own position" for distance filter in some cases

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13414]
### Tell us your idea!

A user on support mail has the problem, that when using a distance filter "from own position" and performs a search for coordinates or address the result is unexpected as the "from own position" is still active in the filter.

### What solution would you suggest?

If the user performs a search by coordinates or address, the setting "from own position" in the filter could automatically be removed to show search results filtered by distance from that search center.

**Comment by eddiemuc** [comment]
Sorry, the name of current context is `LIVE` (not ONLINE as I thought)

**Comment by Lineflyer** [comment]
That is a valid argument against it.
I don't think another context will be easily understandable by users and more confuse instead of help.
So feel free to close this request.

That somehow reminds me of the "problem", that when you search by coord the result list will show the distance to your home location but not to search center. We have some issue for that here. So anyway the live filtering for distance versus the distances shown in the list will produce confusion right now.
