### ISSUE TITLE
Next beta / feature release

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13427]
As discussed in some of the recent issues, it seems to be a good time to prepare a new beta version. I'll start working on it:

- [x] empty changelog_bugfix.md on branch master / sync changelogs
- [x] fast-forward release branch to the head of master branch
- [x] Check/Import incoming Translations from Crowdin
- [x] check/insert correct version name in /main/src/cgeo/geocaching/utils/BranchDetectionHelper.java (using format YYYY.MM.DD-RC)
- [x] Build release on CI server
- [x] Perform smoke test with resulting cgeo-RC.apk before continuing
- [x] Upload and publish cgeo-RC.apk to Google Play
- [x] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)

**Comment by moving-bits** [comment]
From what I can see on support current beta seems to be running smooth, so I guess we are closing in on a new release. Let's collect issues here which should be resolved before releasing:

- [ ] #13408
- [ ] #13434
- [ ] #13448
- [ ] #13452
- [ ] #13456

Feel free to edit list list.

**Comment by fm-sys** [comment]
https://github.com/cgeo/cgeo/issues/13448 is related to the new image gallery, which is only used in the nightlies / with special hidden settings key turned on. Should the fix be targeted to `release` anyway?

**Comment by fm-sys** [comment]
> #13448 is related to the new image gallery, which is only used in the nightlies / with special hidden settings key turned on. Should the fix be targeted to `release` anyway?

I've just retargeted it to `release` now (#13455). Should be an uncritical change anyway...

**Comment by Lineflyer** [comment]
As I did not have the time to keep up with all developments lately, please allow one question:
Does the currently running beta include the feature, that the language is no longer switched?

**Comment by moving-bits** [comment]
Will start preparing release now:

- [ ] Check and merge open Crowdin translation pull requests for release
- [ ] Check/Insert correct version name in BranchDetectionHelper
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting cgeo-release.apk before continuing
- [ ] Upload and publish cgeo-release.apk to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)
- [ ] Post release info to Facebook
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment]
FYI: Release process is currently stuck. The created APK will not install correctly on my test hardware. It does not display the "grant access to files" dialog, and if I skip installation wizard on next start, and start it manually, it hangs after selecting the base folder.

Just cross-checked on a second device, updating an existing installation. This worked flawless, so it seems to affect only fresh installations, having no permissions so far. Or it may be device-specific - my testing device is an old Android 6 Samsung phone.

Can someone else cross-check with a fresh install on a different hardware? You'll find the generated APK on our CI: https://download.cgeo.org/cgeo-release.apk

**Comment by Lineflyer** [comment]
I could reproduce the problem on an Android 6 emulator (Android 5 (real device) and several emulators with Android >6) are OK.

Bisecting the problem ended up with this commit as the problematic one:

```
60d5eb72297328a3f7d940cf081981572e2f039e is the first bad commit
commit 60d5eb72297328a3f7d940cf081981572e2f039e
Author: Tiger Oakes <contact@tigeroakes.com>
Date:   Thu Jun 30 13:10:33 2022 -0700

    Use ViewModel for InstallWizardActivity (#13197)
```

Could maybe some method not supported on low Android versions?
Remark: Android 5 is without runtime permissions, thus the problematic dialog is not shown on Android 5.

**Comment by moving-bits** [comment]
Preparing the new release is postponed for now, let's wait a couple of days to gather some feedback on #13532 first.

**Comment by moving-bits** [comment]
Some additional info:
- Fresh install on Android 6 device has the problems as described above.
- Upgrading an existing install on the same device does work, though. So acquiring the rights from within the wizard seems to be the problem.
- Next I tested the working install by removing both location & files rights using the system's app manager, and then restarting c:geo. This worked without problems, c:geo asked for the two missing rights, and continued to work after that. So the problem seems to exist in context of wizard only (which is another hint at the commit @Lineflyer has bisected).
- @Lineflyer has tested other Android versions, partly on physical devices, partly in the emulator. Only Android 6 seems to be affected.

As @Lineflyer suggested it might be that `androidx.lifecycle.ViewModelProvider` might not be fully supported on Android 6 (API level 23) systems in conjunction with permission management. (Android 5 does not require us to acquire those rights, so the problematic sections may simply be skipped by the wizard.)

**Comment by moving-bits** [comment]
Starting a new run: (feature release 2022.10.17)

- [x] Check and merge open Crowdin translation pull requests for release
- [x] Check/Insert correct version name in BranchDetectionHelper
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting cgeo-release.apk before continuing
- [ ] Upload and publish cgeo-release.apk to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github
- [ ] Adapt changelog for `master`
- [ ] Adapt full changelog
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)
- [ ] Post release info to Facebook
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
Release info posted to social networks.
Seeems we are complete. Closing and thanks to @moving-bits for handling.
