### ISSUE TITLE
Should we remove the  “Identify as Android Browser” settings? 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13430]
Should we remove the  “Identify as Android Browser” settings? 

The original reason why this setting was introduced were network providers "optimizing" the transferred html. AFAIK this should no longer be possible when using the encrypted https protocol. Do we want to give a try to remove the setting?

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo-guide/issues/69#issuecomment-1251634760_

**Comment by fm-sys** [comment]
Just for reference: the setting was added in https://github.com/cgeo/cgeo/issues/1843 / PR https://github.com/cgeo/cgeo/pull/2099

Are performance-enhancing proxies (PEPs) still state of the art?

**Comment by moving-bits** [comment]
> Should we remove the “Identify as Android Browser” settings?

I've never needed that setting so far..., using c:geo for many years.
