### ISSUE TITLE
Server offline ?

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#13447]
### Describe your problem!

Since 3 days no sendtocgeo posibilities.
In Chrome and Edge:

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.38 (Debian) Server at send2.cgeo.org Port 443

### How to reproduce?

see above

### Reproducible

Yes

### c:geo Version

2022.09.14

### System information

```text
Chrome is up-to-date
Versie 106.0.5249.62 (Officiële build) (64-bits)
```

**Comment by moving-bits** [comment]
Thanks for notifying us. There seem to be server problems on send2.cgeo.org currently - we'll look into it.

Additional information: Two tickets on support as well (407155, 531176)

**Comment by mucek4** [comment]
There was no server issue with send2 server, however routing switch forgot where send2 server is.
I have restored the routing configuration and server is again visible to the outside world.

**Comment by wizard4u** [comment]
Yes, thanx for the action and solving this very useful feature of cgeo. It works again 😀

**Comment by mucek4** [comment]
Couple of days ago I was thinking of this and wonder do we still need it. Looks like we do.

**Comment by wizard4u** [comment]
Ha, am I the only one still ? 😮. I am honored for keeping it alive then. But if I am the only one using it then probably I can find way to work around it as well or the handy features are not known to other cgeo users. For offline geocaching (in expensive data roaming countries after updating mystery geocaches and adding new ones in a specific area it works perfect

**Comment by mucek4** [comment]
Don't worry. Now when it stopped working we have seen that it's still used :)
