### ISSUE TITLE
Automatic variable creation on PCN copy with formulas containing variables

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13461]
From user on support, regarding beta 2022.09.04 RC2:

### Description

für den Multi GC9Y1TQ gibt es das Pendant OC17477 bei opencaching.de.

Bei GC9Y1TQ habe ich eine Finalformel mit manuellen Nachbesserungen angelegt und wie folgt in die PN übernommen:

{c:geo-start}
@Finale (F) {CC|N48°2($c/3).($b/3)($a)($a-1)|E10°0($c).($e*3+$d)}
$a= | $b= | $c= | $d= | $e=
{c:geo-end}

Die Variablen werden also explizit genannt.

Wenn ich nun diese Formel in die PN bei OC17477 einfüge, wird nur der Waypoint mit Finalformel automatisch angelegt. Die Variablen werden ignoriert. Diese werden erst durch Aufruf des Berechnungsdialogs und Speicherung (ohne eine Änderung vorzunehmen) angelegt.

Das kann doch sicherlich verbessert werden.

Die Richtung der PN-Übernahme GCOC spielt übrigens keine Rolle.

### Additional information

ticket 508562

**Comment by eddiemuc** [comment]
Valid request.

In the meantime: Variables will be added when button "Cleanup"/"Säubern" is used.

**Comment by eddiemuc** [comment]
I read through the issue one more time and have a follow-up question before I accidentally implement the wrong thing:
* Is the request to create empty variable entries for PCN var entries with empty content (e.g. as in example above: `$a= | $b= | $c= | $d= | $e=`)
* Or is the request to auto-create variable entries for all vars used in any imported coordinate formula?

**Comment by tinkus-gc** [comment]
My request is to create all variables including emtpy ones.

**Comment by eddiemuc** [comment]
fixed with PR #13467
