### ISSUE TITLE
formula parsing: incomplete "remove spaces"

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13460]
User report on support, regarding current beta version 2022.09.04 RC2:

### Description

in der Formelberechnung werden vom Tool "Leerzeichen entfernen" nicht alle Leerzeichen gelöscht.

Beispiel:

Im Listing von GC9Y1TQ steht die folgende Finalformel:

N48 2 [ c : 3 ]. [ b : 3 ] [ a ] [ a - 1 ]     E10 0 [ c ]. [ e*3 + d ]

Eckige durch runde Klammern und ":" durch "/" ersetzt, sowie das Gradzeichen ergänzt, ergibt:

N48° 2 ( c / 3 ). ( b / 3 ) ( a ) ( a - 1 )
E10° 0 ( c ). ( e*3 + d )

Diese Formel habe ich in einen Finalwegpunkt eingefügt und "Leerzeichen entfernen" ausgewählt -  mit dem Ergebnis im angehängten Screenshot.

![image](https://user-images.githubusercontent.com/3754370/193524079-5a43e552-4b22-4d58-a39f-7cc994785321.png)

Es wurden also nicht alle Leerzeichen entfernt.

Um nun die Kleinbuchstaben als Variablen kenntlich zu machen, habe ich jeweils ein $ davor ergänzt. Im zweiten Screenshot erkennt man, dass die Variablen aber nicht automatisch angelegt werden.

![image](https://user-images.githubusercontent.com/3754370/193524113-2524db76-725e-429b-8e59-f366601053cd.png)

Wenn ich nun alle Leerzeichen manuell lösche, werden die vermissten Variablen erkannt, siehe dritter Screenshot.

![image](https://user-images.githubusercontent.com/3754370/193524170-64417e1a-b069-4f22-95aa-36aaad4dfac1.png)

### Additional information

ticket 711926

**Comment by eddiemuc** [comment]
Fixed with PR #13463
