### ISSUE TITLE
Non working variable in string for Crowdin

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13473]
This string
https://github.com/cgeo/cgeo/blob/c2d0e2814c191f10e2f91f479652c8f8c55d7e0d/main/res/values/strings.xml#L729

seems to produce problems on Crowdin as the variable is not shown, thus not allowing to place it correctly when translating.

![image](https://user-images.githubusercontent.com/949669/194144147-72940c44-8446-44d1-9f43-78b5e402d8e7.png)

Maybe a whitespace is needed after the line break?

@moving-bits  
Introduced in your PR with commit https://github.com/cgeo/cgeo/commit/c2d0e2814c191f10e2f91f479652c8f8c55d7e0d

**Comment by moving-bits** [comment]
It should work, we are using the same syntax in other places (also with the placeholder being the last characters in the string). Adding a space before the placeholder would lead to indentation in the printed text.

But anyway: I had updated the string as part of another PR today, removing the placeholder, so maybe Crowdin is simply displaying the updated string already.

**Comment by Lineflyer** [comment]
> But anyway: I had updated the string as part of another PR today, removing the placeholder, so maybe Crowdin is simply displaying the updated string already.

That might be...in that case its also a problem, because the string without placeholder requires the "subject to be downloaded" to be at the end, which is e.g. not the case in german.

**Comment by moving-bits** [comment]
Maybe we need to rearrange the string. The "subjects" will be displayed in a list (with checkboxes) following that sentence.

**Comment by Lineflyer** [comment]
Understood. Don't bother with this one, I will fix it then so you can concentrate on other things ;)

**Comment by moving-bits** [comment]
It's part of the new "pending downloads" view, which you can access via home screen's overflow menu (or which comes up automatically if you have pending paused or failed downloads). To get some content in this view, start a larger download and then cut off any network connection.
