### ISSUE TITLE
Show current elevation on start screen

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13470]
### Tell us your idea!

A user on support had following request:
In some situations (e.g. for certain caches or during hiking tours) I would like to see the current GPS reported height above sea level.

### What solution would you suggest?

Currently the start screen shows the GPS coordinates (or the location derived from those), the current height info could be appended to that line.

### Is there an alternative?

Currently I always start the c:geo compass as it seems to be the only place, where the height is reported.

**Comment by Lineflyer** [comment]
That's true, but as we show it (after user request) in the compass, we could also show it on the main screen.

On my last vacation in the alps, it would even have appreciated if c:geo would use some service to get the ground elevation based on coordinates and show it for the caches...but that's another feature request. AFAIR c:geo had this some 10 years ago, but it was removed....probably there is no free service providing such elevation info?

**Comment by SonnyLidarDTM** [comment]
If c:geo wants to display accurate elevation values, you should think about using LiDAR-based offline elevation files from https://sonny.4lima.de
Especially the accurracy of its 1"-files is much better than e.g. SRTM-files. And of course also compared to GPS-based elevation values which usually are fluctuating and/or unaccurate depending on the reception factors and quality of the GPS receiver.

**Comment by moving-bits** [comment]
FYI: New BRouter version 1.7.1 seems to support elevation queries as well, based on LiDAR data merged into their data files. (Source seems to be Sonny's data as well, at least partly, see https://brouter.de/brouter/elevation.html)
