### ISSUE TITLE
Trying to send empty log results in "unknown error"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13476]
### Describe your problem!

From a user report and reproducible also on `master`:

When trying to send a log with an empty log text c:geo reports an unknown error.

### How to reproduce?

- Open geocache
- Start log activity
- Make sure the log text is totally empty
- Try to submit the log

### Actual result after these steps?

c:geo reports an unknown error and offers to retry/store/drop.

Debug log contains:
[AsyncTask #2] GCWebAPI.postLog: No log text given {GCWebAPI.postLog:1004/GCLoggingManager.postLog:174/LogCacheActivity$Poster.doInBackgroundInternal:719/LogCacheActivity$Poster.doInBackgroundInternal:701/AbstractAsyncTaskWithProgress.doInBackground:122/AsyncTask$3.call:394/FutureTask.run:264/AsyncTask$SerialExecutor$1.run:305}

### Expected result after these steps?

c:geo should provide clear indication of the error reason or (better) not even try submitting but check this condition in beforehand and notify the user accordingly.

IMHO we had such a feature before, that blocked the sending if the text was empty....but I might be wrong.

### Reproducible

Yes

### c:geo Version

2022.09.04

**Comment by murggel** [comment]
PR #14140 will fix this

**Comment by murggel** [comment]
Just wondering, if every platform does not allow empty logs or if this has to be configurable - e.g. perhaps even per LogType? 
Does opencaching allow empty logs? Do we want to support this then?
