### ISSUE TITLE
tests/src-android not marked as source directory

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13494]
### Describe your problem!

tests/src-android/ contains tests that need to be run in Android Emulator. However unlike tests/src that folder is not marked as a source folder in Android Studio, thus not taken into account e.g. when changing methods.

Probably build.gradle needs to be adjusted.

### How to reproduce?

Load project in Android Studio

### Reproducible

Yes

### c:geo Version

-

**Comment by bekuno** [comment]
superseded by #13761
