### ISSUE TITLE
Enhance display of table headers in cache listings

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13498]
### Tell us your idea!

From user on support:

Table cells of table bodies are marked with a "|" as separator, whereas cells of table headers are not, which sometimes make them hard to read.

See GCA0MRJ as example.

### What solution would you suggest?

Separate cells of table headers with "|" like it's done for cells of table body.

### Is there an alternative?

Leave it as is

### Additional Information

Ticket 552919

**Comment by moving-bits** [comment]
With a little tweak for `<th>` elements, the named cache would look like this in c:geo:

![image](https://user-images.githubusercontent.com/3754370/195431754-0a4c3f06-a0a5-40d0-9339-97ec89acf6d9.png)

Which leads me to a follow-up question: Should we add some marker for "end of table header", eg. "-----------------------" and a newline?

**Comment by ztNFny** [comment]
Will be made obsolete by https://github.com/cgeo/cgeo/issues/12910

**Comment by moving-bits** [comment]
> Will be made obsolete by #12910

That's true, but as it's only a "half-liner" and there seem to be some prerequisites to be done before #12910 can/should be merged... Anyway, let's skip my follow-up question, though.
