### ISSUE TITLE
skip proximity notification for found caches

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13497]
### Tell us your idea!

From user on support:

(Optionally) suppress proximity notifications for found caches.

### What solution would you suggest?

Add configurable option to skip found caches for proximity notifications.

### Is there an alternative?

Leave it as is (and maybe select found caches not to be shown on map)

### Additional Information

ticket 700331

**Comment by Lineflyer** [comment]
Why not set the filter to hide found caches. This would implicitly suppress notification for found caches, I guess ;)

**Comment by eddiemuc** [comment]
If this is really wanted, we could also let the user define a "notification filter". She would then have the full capabilities of filtering available to decide on which caches she wants to be notified (e.g. only non-found traditionals with T<3)

**Comment by moving-bits** [comment]
As it hasn't come up before or after, and as there is an easy workaround for it (do not display found caches): Let's close here as "won't fix".
