### ISSUE TITLE
Revise Global Cache filter (make it checkbox based)

### ISSUE THREAD

**Issue by RevZero** [cgeo/cgeo#135]
I am not sure about how c:geo queries the data from gc.com but i think there is some room for improvement here.

For example it would be nice if it would be possible to show Traditional AND Multi instead of only one type at a time.
Even if it may require to query data from gc.com than is filtered out afterwards its worth the effort since filtering is a powerful tool.

Maybe the "hide my finds" and the "hide disabled" checkboxes from the settings menu could then be moved to the new filter dialog for better overview. 
On the gc.com page for example, you have all the filter options in one place as well.

**Comment by UniQP** [comment]
gc.com's new search allows to filter for multiple cache types at once. It's still a bunch of work, though.

**Comment by okainov** [comment]
Any updates on it? If it's now supported from the server side, it shouldn't be very difficult to implement, right?

And I'd like to notice that there are more GC services than just GC.com and if for GC.com you don't have normal API, you may have one for other services like OpenCaching, so checkbox-based filter will make sense in any case.

**Comment by eddiemuc** [comment]
For offline caches this is solved, for search queries against GC.com it is not. This is a very complex and long issue. I don't really know if it makes sense to keep it.

**Comment by Lineflyer** [comment]
Up to what I read on support mail and social media channels, this is one of the most wanted features:
Simply the same global type filter we currently have but supporting multi-selection (e.g. I am on tour and only want to see traditional, earth, but not multi, mystery, etc.)

**Comment by eddiemuc** [comment]
Understood. Luckily, to make this happen it would be enough to filter these things inside c:geo, not already when requesting caches from c:geo. This makes it substantially easier to implement.

I will take steps to integrate new filter in map view as well and to make filters storable. This should help solving this issue. I even believe that we can seriously think about removing the "global filter" then

**Comment by okainov** [comment]
@eddiemuc please keep in mind that if the service supports querying with multiple filters, I think it's much better to use this instead of filtering results in C:geo. Not to mention that search results from gc services cen be limited and if, for example, there are 1002 caches in the area and search results are limited to 1000 by gc service, then filtering in cgeo might lead to zero caches (if user sets the filter corresponding to last 2 caches only)

**Comment by eddiemuc** [comment]
Aware of this, see discussion in#10027

**Comment by eddiemuc** [comment]
Solved with PR #10622 . Be aware of limitations as mentioned in #10633 and #10621. Search limit is no longer just 20.

**Comment by fm-sys** [comment]
Sorry to reopen this issue, but the issue mainly was about the global cache type filter, which should allow multi selection... (which is not yet the case) 

![Screenshot_20210516_100624_cgeo geocaching_copy_270x585](https://user-images.githubusercontent.com/64581222/118390295-8d482b00-b62e-11eb-8f52-49ff3d3c4b47.jpg)

**Comment by eddiemuc** [comment]
@fm-sys you are right, In was too quick. I changed issue title accordingly.

**Comment by eddiemuc** [comment]
Closing this issue in favor of #10711
