### ISSUE TITLE
Hillshading not working with Freizeitkarte themes

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#13538]
### Describe your problem!

I placed some relevant HGT files (from USGS.gov) in the correct folder and am using an offline map. But I see no hillshading.

Tried different slider settings for both options in the settings dialogue, no change.

If there is something else I need to do, then c:geo does not clearly communicate that to the user.

### How to reproduce?

See above.

### Reproducible

Yes

### c:geo Version

2022.10.17

**Comment by ztNFny** [comment]
Does the map theme you're using support hillshading? c:geos "default" theme does.

**Comment by dcjkfgdjhd** [comment]
Aha, that seems to be the issue. I am using the Freizeitkarte v5 Theme.

What needs to be done to make hillshading work with Freizeitkarte and who can do it?

**Comment by ztNFny** [comment]
Please contact the author of that theme to request hillshading to be supported by it.

**Comment by SammysHP** [comment]
> Please contact the author of that theme to request hillshading to be supported by it.

Why does it depend on the map theme? Isn't it a separate layer? What needs to be changed in the map theme?

**Comment by ztNFny** [comment]
> > Please contact the author of that theme to request hillshading to be supported by it.
> 
> Why does it depend on the map theme? Isn't it a separate layer? What needs to be changed in the map theme?
>
> IMHO we should try to make it work with all themes. We can't expect dozens of authors changing something they aren't even aware of.

That's the way it is implemented in Mapsforge, it's not specific to cgeo. The theme has to define at which level the hillshading layer is placed.

[hillshading /] as defined in https://github.com/mapsforge/mapsforge/blob/master/resources/renderTheme.xsd#L274
So every theme author is in fact aware of this element (or should be if he read the documentation)

**Comment by dcjkfgdjhd** [comment]
Where in Github can I find the XML file defining the cgeo default theme? 

Maybe I can use that as an example to make the necessary changes to the Freizeitkarte theme.

**Comment by ztNFny** [comment]
> Maybe I can use that as an example to make the necessary changes to the Freizeitkarte theme.

add this line before `</rendertheme>` should do it:
`<hillshading zoom-min="9" zoom-max="17" />`

**Comment by dcjkfgdjhd** [comment]
> add this line before `</rendertheme>` should do it:
> `<hillshading zoom-min="9" zoom-max="17" />`

Yes, that's it. Thanks a lot!

**Comment by SammysHP** [comment]
Can we or mapsforge inject a default layer on top? I've read a discussion that the reason for adding a layer at a specific level was to render streets on top of the hillshading for better contrast. But in other applications hillshading is simply rendered on top of everything else.

**Comment by ztNFny** [comment]
> But in other applications hillshading is simply rendered on top of everything else.

If that other application is Locus that's because they aren't using Mapsforge.
I'm not aware of any Mapsforge-using app supporting hillshading if the theme doesn't.

Until yesterday I also wasn't aware of any mapsforge theme not implementing the hillshading-layer though - e.g. Elevate - which is provided inside c:geo - support it.

**Comment by ztNFny** [comment]
> Can we or mapsforge inject a default layer on top? 

No, there's only 1 call to addHillShadings() in the Mapsforge codebase and that's in reading the theme: https://github.com/mapsforge/mapsforge/blob/14565cccd98d6d4d53da585be04eb9c80b8779ad/mapsforge-map/src/main/java/org/mapsforge/map/rendertheme/rule/RenderThemeHandler.java#L309

**Comment by dcjkfgdjhd** [comment]
I have reported the issue to the Freizeitkarte-Android people at https://www.geoclub.de/forum/t/freizeitkarte-f%C3%BCr-android-devices.67436/post-1344457

Hopefully, they will add the missing line in the XML file in the next interation of their theme.

**Comment by Lineflyer** [comment]
Adapted the title to what AFAICS the specific issue here.

**Comment by dcjkfgdjhd** [comment]
Maybe the easiest fix for the moment would be for c:geo to just offer a fork of the Freizeitkarte Theme for download in its download manager, where the one missing line is inserted into the XML file.

**Comment by SwissPoPo** [comment]
> Maybe the easiest fix for the moment would be for c:geo to just offer a fork of the Freizeitkarte Theme for download in its download manager, where the one missing line is inserted into the XML file.
dcjkfgdjhd, are you in a hurry?
The Freizeitkarte Team has read the issue here and your comment in the forum.

**Comment by dcjkfgdjhd** [comment]
> dcjkfgdjhd, are you in a hurry? 

Nope, as I have fixed it for my own phone by manually modifying the theme.

>The Freizeitkarte Team has read the issue here and your comment in the forum.

Awesome. 😀

**Comment by wolverine007** [comment]
![IMG_20221112_082852.jpg](https://user-images.githubusercontent.com/4508228/201462838-8abc410b-8496-47e6-adf1-11a99ac01022.jpg)

working here as well, but I saved the fixed design into a separate zip-file, so I could switch between normal and hillshaded map on the fly

**Comment by SammysHP** [comment]
@wolverine007
If you use my theme frome here (but it's based on the outdoor contrast version), you can toggle hillshading from the style menu.

https://github.com/cgeo/cgeo/pull/13565#issuecomment-1304466794

**Comment by fm-sys** [comment]
@SwissPoPo do you plan to integrate a new style toggle in Freizeitkarte like explained in https://github.com/cgeo/cgeo/pull/13565#issuecomment-1304466794?

**Comment by SwissPoPo** [comment]
The hill shading feature will be integrated in the  fzk outdoor themes (release December 2022).
There will be no toggle in the theme! Because other apps have this toggle in the app and two toggle options would confuse the users.
For the original freizeitkarte theme it is not yet decided if the hill shading feature will be included.

**Comment by dcjkfgdjhd** [comment]
> For the original freizeitkarte theme it is not yet decided if the hill shading feature will be included.

I hope you will decide to include it, because I prefer the original theme (it is much prettier). Thanks!

**Comment by moving-bits** [comment]
Hillshading is available for and does work with FZK December 22 update, so let's close here.
