### ISSUE TITLE
Next bugfix release

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13537]
After publish of 2022.10.17 let's collect issues which should be part of a next bugfix release. I'll start the list with the unfinished tasks of the last version, but feel free to edit this list:

- [x] #13408
- [ ] #13434
- [ ] #11725

Does anyone have an idea how to tackle any of those?
#13434 was the most frequent error reported on Play Store for our last release.

Update after publishing 2022.11.13:

- [x] #13659
- [x] #13644 
- [x] #13674
- [x] #13682
- [x] #13677
- [ ] #13698 
- [ ] #13666 
- [ ] #13675
- [x] #13651 
- [x] #13715

**Comment by Lineflyer** [comment]
we have this issue open but meanwhile we have a new beta from `master`, see #13609.
How about those items listed above?

**Comment by moving-bits** [comment]
Currently we cannot prepare a bugfix release without porting some code (two or three PR) from current `master` to the old released state, as meanwhile Google has set Play restriction to `targetSDK=31`. Therefore a bugfix release is sort of postponed to after next feature release. I'll unpin it for the time being.

Also, nobody (me included) seems to have an idea how to get a grip on one of the three issues above. 
- From the comments in #11725 that seems to be a somewhat older issue, just brought up again; 
- for #13434 maybe @NotWoods may be able to help (as it's probably related to RxJava); 
- and the cache background downloader of #13408 got invented by @fm-sys, maybe he as an idea how to tackle the issue.

**Comment by Lineflyer** [comment]
Pinning this issue again as the mentioned issues are probably still on the ToDo list also after the recent feature release.
Additionally we can collect new issues coming in from 2022.11.13

**Comment by fm-sys** [comment]
I don't have a real clue for https://github.com/cgeo/cgeo/issues/13408 either... :-/

**Comment by Lineflyer** [comment]
I have added a list of recently solved and potentially open issue for a possible next bugfix release in the initial post of this thread. Please feel free to take a look into those.

**Comment by Lineflyer** [comment]
As we have a couple of the above issues fixed (and the remaining probably need more time) I suggest to release a bugfix release tonight.
Any objections or any more ongoing work for `release` ?

**Comment by moving-bits** [comment]
Would be ok for me as well. Haven't had much time lately, but I'll try to look into the TB issue over the weekend.

**Comment by Lineflyer** [comment]
Will prepare the release now:
- [ ] Check/insert correct version name in `/main/res/raw/changelog_bugfix.md` (using format `## YYYY.MM.DD)`) on branch `release`.
- [ ] Wait for a Crowdin cycle or trigger sync manually on [this Crowdin page](https://crowdin.com/project/cgeo/apps/system/github) to get a pull request from Crowdin with the version name in the translated files.
- [ ] Merge the related Crowdin translation pull requests for branch `release`

Common steps:

Specific for for a bugfix releases:
- [ ] Check/insert correct version name in `/main/res/raw/changelog_bugfix.md` (using format `## YYYY.MM.DD)`) on branch `release`.
- [ ] Wait for a Crowdin cycle or trigger sync manually on [this Crowdin page](https://crowdin.com/project/cgeo/apps/system/github) to get a pull request from Crowdin with the version name in the translated files.
- [ ] Merge the related Crowdin translation pull requests for branch `release`

Common steps:
- [ ] Build release on [CI server](https://ci.cgeo.org/view/Release_Nightly/job/cgeo%20release/) (Download available after build from [here](https://download.cgeo.org/cgeo-release.apk))
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play (Account required for the c:geo team Google Play account)
- [ ] Tag the release on Github in format `market_yyyymmdd` (can be combined with next step if done on Github UI)
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github (Select Draft a new release from [here](https://github.com/cgeo/cgeo/releases), enter tag name (see above), make sure to select branch `release`, C&P change log, attach APK file, release the version)
- [ ] Publish release on F-Droid by running [this job](https://ci.cgeo.org/view/FDroid/job/Publish%20FDroid%20-%20RELEASE/) This requires, that the release APK has been uploaded to Github in previous step
- [ ] Trigger notification to status.cgeo.org via [CI server](https://ci.cgeo.org/view/Notification%20system/job/Create%20release%20notification/) once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day although Google reports availability earlier. You might want to check the [cgeo status page - deployment section](https://status.cgeo.org) to check online users for that new release to get an indication.)
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

## Release checklist for beta release:

- [ ] Check/Import incoming Translations from Crowdin
- [ ] Check/insert correct version name in ```/main/src/cgeo/geocaching/utils/BranchDetectionHelper.java```  (using format `YYYY.MM.DD-RC`)
- [ ] For bugfix release: Wait for a Crowdin cycle or trigger sync manually on [this Crowdin page](https://crowdin.com/project/cgeo/apps/system/github) to get a pull request from Crowdin with the version name in the translated files.
- [ ] For bugfix release: Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on [CI server](https://ci.cgeo.org/job/cgeo%20release%20candidate/) (Download available after build from [here](https://download.cgeo.org/cgeo-RC.apk))
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play (Channel/Release type: open test) (Account required for the c:geo team Google Play account)
- [ ] Trigger notification to status.cgeo.org via [CI server](https://ci.cgeo.org/view/Notification%20system/job/Create%20release%20notification/) once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)

**Comment by Lineflyer** [comment]
Bugfix release 2022.11.25 is rolling. Will follow up tomorrow.

Open issues from above will be taken to a followup issue.

**Comment by Lineflyer** [comment]
All done here. Will take the list of still open issue to a new "bugfix release" issue for a better overview.
