### ISSUE TITLE
How to use hillshading

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13536]
We should add a "How to" of the hillshading feature to our user guide.

Can either anyone explain to me how to use / where to find the relevant menu in some short hints or append it as new chapter on https://manual.cgeo.org/en/offlinemaps directly ?

**Comment by moving-bits** [comment]
@fm-sys had prepared some info a while ago: https://github.com/cgeo/cgeo-guide/issues/68

**Comment by Lineflyer** [comment]
oh nice. Thanks for the hint. @fm-sy documented it exactly where it should be. Stupid me did not look into the right repo;)
