### ISSUE TITLE
Add "Go to here" option to the long-press menu in the map

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#13539]
### Tell us your idea!

When long pressing the map, a popup menu appears with many useful options.

But one option is missing there: Selecting that point as the current destination for routing.
(Not as in "create a multi point route" but as in "a route from my current location to that point".)

### What solution would you suggest?

Add this option to the popup menu.

**Comment by fm-sys** [comment]
You can add this point to the individual route and enable the "set route start as target" option

**Comment by dcjkfgdjhd** [comment]
Thanks a lot, that is a good temporary workaround. 

But adding the option to the menu would of course be much more elegant.

**Comment by ztNFny** [comment]
How is that a workaround? "Append to route" on a waypoint does exactly as "Set as target" on a cache - and if routing is already active "Prepend to route" does exactly that.

**Comment by dcjkfgdjhd** [comment]
Well it is a lot more clicks and very clunky to have to enable "Prepend to route" for this, and then to have to disable the option afterwards again.

Compared to two clicks if it were in the menu. Since there is still space in the menu, why not?

**Comment by ztNFny** [comment]
How is it more clicks? Once done just select the next cache and "Set as target". 2 clicks for settings the waypoint, 2 clicks for setting the cache. Would also be 2 clicks for a "Route" in map-menu.

> Since there is still space in the menu, why not?

Either what you want is already 100% there, just with a different name than the one you want, or I'm failing to understand what you actually want.

**Comment by dcjkfgdjhd** [comment]
I think there is some misunderstanding between us. I am not talking about a cache or a waypoint, but about ANY point. I am referring to the popup menu that shows up when you long tap empty space on the map.

If what I suggest would be implemented, then it would be possible to long-tap on an empty space on the map, and then chosse "Set this point as target" from the popup menu. Two taps.

Unless there is some clever trick that I am unaware of, the currently possible workaround requires
1) clearing the current route if there is one (multiple taps)
2) Adding the intended destination point to a new route (2 taps, as above)
2) enabling "Prepend to route" (multiple taps, depeding on whether you have to got through the three-dot-menu or whether the route icon at the bottom is visible)
3) Once you reached your destination: Disabling "Prepend to route" (multiple taps) and then recreating your original route if there was one (multiple taps)

Or am I missing something?

**Comment by ztNFny** [comment]
> I am not talking about a cache or a waypoint, but about ANY point.

No, that's clear

> clearing the current route if there is one (multiple taps)

No need - if you already have an active route just use "Prepend to Route" and it'll be added to that existing route as next step -> 2 taps
If you're not already in an active route then Append/Prepend will be the same.

**Comment by dcjkfgdjhd** [comment]
Or, to put it differently: "Set as target" and "Add to route" behave quite differently in c:geo, as they are inteded for different purposes.

Currently it is only possible to add an empty-space-point to a route, but not to set it as destination.

**Comment by ztNFny** [comment]
> But I don't want it to be added to the END of the route, I want to get there at once. It should be my next target. Just like tapping a point on the map on a Garmin GPS and choosing GO!.

Can you please actually try what was recommended to you? "PREpend to route" does exactly that! "APpend to route" adds it to the end.

**Comment by dcjkfgdjhd** [comment]
Oh, sorry, there was an error on my side: I am using c:geo in German and thought "Prepend to route" is the English translation of the "Routenstart als Ziel festlegen" toggle. But you were refering to an entry in the popup menu.

Okay, now I understand what you are saying. However, there is still a reason why what you are suggesting does not compare to what I suggest:

1. As I always have "Routenstart als Ziel festlegen" disabled, what you suggest would not work for me. Unless I switch it on and back off afterwards. (That is what I described above with the many taps.)

2. If I prepend a empty-space-point to the route like you suggest, there seems to be no way to remove that point from the route again, once I get there. So it "contaminates" my route. Or is there a way to remove it again? I could not find it.

**Comment by dcjkfgdjhd** [comment]
> Route management button at the bottom of the map allows you to remove targets from route and reorder them.

OK, thanks. 

It is still clunky as hell, and definitely requires lots of taps and that the "Routenstart als Ziel festlegen" toggle is enabled.
 
There is no reason why an empty-space-point should not simply be selectable as destination, but only as a route point.

More generally speaking a planned route and the current destination are two separate feature that I tend to use separately from each other. I prefer to not conflate them with each other.

**Comment by fm-sys** [comment]
I get your point @dcjkfgdjhd. What about listing "map" inside the "navigate" submenu?

> If I prepend a empty-space-point to the route like you suggest, there seems to be no way to remove that point from the route again, once I get there. So it "contaminates" my route.

I had started to work on improving this some time ago. See PR https://github.com/cgeo/cgeo/pull/13304

**Comment by Lineflyer** [comment]
After reading this thread:
I guess what the author wants is, that the (rather new) map context menu when long tapping on the map should also offer the same function as setting a cache as destination (i.e. showing the (default) red line to the position). That is IMHO a valid feature request or am I wrong.

**Comment by Lineflyer** [comment]
Addon:
Now I see, that @fm-sys addressed this in #13539. Sounds perfect.

**Comment by dcjkfgdjhd** [comment]
> I guess what the author wants is, that the (rather new) map context menu when long tapping on the map should also offer the same function as setting a cache as destination (i.e. showing the (default) red line to the position).

Yep, exactly 👍

**Comment by dcjkfgdjhd** [comment]
> What about listing "map" inside the "navigate" submenu?

Yes, of course that would work equally well.

Personally, I would find it more logical if the option were located right in the first popup menu. First because that is where all the other interaction options for the selected empty-space-point are located; and second because in other parts of c:geo "Set as destination" is *not* located under the "Navigate" menu.

But that is just a fine detail, and I have no strong preference either way, as long as the option exists.
