### ISSUE TITLE
Descriptive texts in settings missing

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13547]
Some setting screens have fake-settings, e.g. offline maps, map themes, to provide additional information by the means of descriptive texts, e.g. settings_info_offline_maps
However these texts are not shown anywhere in the UI.

my best guess is this got lost during the migration of the settings pages about 1 year ago

**Comment by moving-bits** [comment]
Preferences lib do not seem to support `android:text` attribute, only `android:summary`, see https://github.com/cgeo/cgeo/pull/13546#discussion_r1002160724
