### ISSUE TITLE
Migration to GeoKrety.org v2 - Partners testing

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#13542]
### Tell us your idea!

Hi,

I'm pleased to announce that GKv2 (GeoKrety.org rewritten from scratch) has now reached enough maturity in it's core public features to declare it as ready to be deployed. GKv2 work has been started some years ago, it's a complete rewrite, but the UI should look familiar. Sure there will be missing features but I think it's really usable.

The public staging instance is hosted at https://new-theme.staging.geokrety.org/. Database is synchronized from production every days at 2am UTC. So there will be no problem if tests are made there, just remind that everything there is volatile.

- Bugs should be reported on [GitHub](https://github.com/geokrety/geokrety-website/issues).
- Translations are hosted on [crowdin](https://crowdin.geokrety.org/).

Regarding the API and legacy URLs, I did my best to **keep same API endpoints or add redirections** so the migration should be transparent.

---

**Partners are however requested to _test their product on their staging/development environments against GKv2_ using the url above ^^** before we proceed with the migration.

---

The migration date will be set depending of the quantity, severity and time need to fix the new found bugs. :) Due to database and schema changes, the GKv1 to GKv2 migration will be one way forward. The expected downtime should be around 6h. To give everyone enough time let's plan that for February/March 2023...

# Known changes
## Rate limit system

API endpoint now have 2 types of rates limits:

- Use nginx rate-limiting and limit the number of request per second per group of endpoints
- Authenticated endpoints have requests limits calls per days.

Both of them should be quite high. Let me know if some needs tuning. For the 2nd point, for each request you'll find in the headers the current consumption, limit and count period.

## Timezone support

Historically all date times were processed as if they were UTC. Now timezone should be handled properly. On legacy API endpoints, there is now a new timezone parameter (default to UTC)

## GKM/GK fusion

On migration, the api.geokretymap.org will point to api.geokrety.org

## Pictures

- Upload is now possible via drag&drop
- Automatic image scaling
- User can have multiple avatars

## Comments

- Unicode support in titles and message body 🎉

## Missing features

- Rate Geokrety
- Races
- Users statistics
- GeoKrety statistics
- No GeoKrety altitude profile

Bests
Kumy - GK Team - France

### Additional Information

Central [issue](https://github.com/geokrety/geokrety-website/issues/754) on GeoKrety side

**Comment by bekuno** [comment]
@cgeo/team 
I think we should create a separate branch to test c:geo against GeoKrety.org v2.
What do you think?

**Comment by bekuno** [comment]
Migration is planned for February 24, 2023, see https://github.com/geokrety/geokrety-website/issues/807

**Comment by Lineflyer** [comment]
FYI:
In order to do some emulator testing I just created the branch `gkv2-staging` freshly from `master` and applied needed changes to use the staging environment as taken from the PR of @kumy for branch `kumy-gkv2-test` in 2021.

So (unless I did something wrong) the branch `gkv2-staging` can be used for testing if anyone is interested.
I will do some checks of search/grab/drop as time permits and will report to the geokrety repo if I see something unusual.

**Comment by bekuno** [comment]
New migration date is planned for **September 15, 2023**, see https://github.com/geokrety/geokrety-website/issues/807

**Comment by bekuno** [comment]
Update: New migration date is planned for **September _14_, 2023**, see https://github.com/geokrety/geokrety-website/issues/807

**Comment by Lineflyer** [comment]
@kumy 
Some months ago I tested c:geo towards the new website and found no issue.
Once you migrated, we will monitor our support tickets carefully to see whether our users experience any issues.

**Comment by bekuno** [comment]
The migration is underway - that is why some CI tests are currently failing

**Comment by moving-bits** [comment]
> The migration is underway - that is why some CI tests are currently failing

ah, just stumbled upon it...

**Comment by kumy** [comment]
Service is now online, BaseX is synchronizing in the background (xml exports may be out of date)

**Comment by kumy** [comment]
Cross posting here https://github.com/geokrety/geokrety-website/issues/850

> I can no more log Geokrets with c:geo.

**Comment by bekuno** [comment]
GK v2 is live now since few weeks.
It works so far.
New problems are reported in #14698 and #14657.
Lets handle them in the dedicated issues.
