### ISSUE TITLE
Improve contrast for archived cache title

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13541]
### Tell us your idea!

From support mail (summarized):
The archived caches show in C:Geo with a red title with strikethrough.
The problem is that this is hard to read when using Dark Theme, especially on a bright sunny day.

### What solution would you suggest?

Could we either:
Harder solution: Use a more dynamic font colour - a lighter red when using dark theme, and a darker red when using light theme, or

Easier solution: On the cache details page, keep the title as red but change the "Name" field to the default colour (white for dark theme, black for light theme).

**Comment by Lineflyer** [comment]
I agree...."Harder solution" was the users text ;)

I would like to work on this one, so assigning myself.

**Comment by Lineflyer** [comment]
See https://github.com/cgeo/cgeo/pull/13550 for draft PR with this problem.

**Comment by moving-bits** [comment]
> While in cache lists its working with the theme xml, this function in `TextUtils.java` does always return the light theme color ignoring the applied theme. Any insights?

`TextUtils.coloredCacheText` alsways used the application context instead of being context-aware, see https://github.com/cgeo/cgeo/pull/13550#pullrequestreview-1151489703
