### ISSUE TITLE
import public / shared bookmark list

### ISSUE THREAD

**Issue by wfrey-bc** [cgeo/cgeo#13566]
### Tell us your idea!

import public / shared bookmark list by URL 

### What solution would you suggest?

currently it is only possible to import private (user owned) bookmark list. 
Having the ability to import a public or shared bookmark list by providing the respective URL would really be great. 

### Is there an alternative?

Not that I'm aware of.

**Comment by wfrey-bc** [comment]
@moving-bits Hi moving-bits, 
thanks for considering and implementing my suggestion. 
Well, I see that there has been some code developed, however I wasn't able to figure out if this has yet been placed into a public release of cgeo. If so, where can I find the feature and how can I use it? 
Public or shared bookmark lists do not "appear" when querying lists for a particular user, rather than, the user would have to enter the list ID "BM..." somewhere to get the list imported. However I could not find yet any place where I can enter a BM... List name. 
Thanks.

**Comment by moving-bits** [comment]
This is https://github.com/cgeo/cgeo/pull/13960, which is yet included in our nightly developer versions only.

It was tested against the public list of upcoming events (https://www.geocaching.com/plan/lists/BM21VBT?sort=distance&sortOrder=asc&skip=0&take=10), a link which you will find at the end of gc.com newsletter emails.

If you tap on such a link (in an email etc.), c:geo will open and offer to display this list.
