### ISSUE TITLE
Add "Past Events" to status filters

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#13567]
We have a special "Solved Mysterys" status filter entry which only applies for mystery listings, even though one could use a combination of other filters as well.

I would like to propose we add a setting to filter out past events here as well.

This would help declutter the map for large agglomerations where events are a common occurrence, and where they aren't archived in a timely fashion.

It would make planning trips easier as well as help save time when looking at the listings in the vicinity spontaneously on the go.

**Comment by ztNFny** [comment]
Wouldn't an "event in X days" filter be the more useful option? If you hide past events you still get all the future events, even if they're weeks ahead - but you might only be at that location tomorrow, so everything happening today or after tomorrow is just as irrelevant as "past events".

**Comment by jakedot** [comment]
Might be a nice idea but this can already be done using the normal date filter with a end date in the future.

Using the date filter only for events in the past requires quite some acrobatics with nested filters for type and date, and afaik (at least I couldn't do it when I tried) there's no possibility yet to use a saved filter as the content of a nested filter yet (which would make it easier to use in multiple other filters).

**Comment by fm-sys** [comment]
Thanks for the feedback! Let's close as "not planned"...
