### ISSUE TITLE
[new image gallery] flickering under specific circumstances 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13586]
### Describe your problem!

The image gallery is flickering and doesn't restore the correct position. 

### How to reproduce?

- Use a cache with enough images (e.g. GC89AXV)
- scroll down quite a bit
- choose the first image visible on screen
- swipe back some images
- go back to overview
- ✨ enjoy the "party" ✨ ;-) 

### Actual result after these steps?

See video 

### Reproducible

Yes

### c:geo Version

2022.11.01

### Additional Information

https://user-images.githubusercontent.com/64581222/199184390-6b28b922-9d04-464e-83b8-c97db32a9085.mp4

**Comment by eddiemuc** [comment]
Additionally it looks in the video as if the "own images" category is not shown at the beginning of the gallery, is this true?

**Comment by fm-sys** [comment]
> Additionally it looks in the video as if the "own images" category is not shown at the beginning of the gallery, is this true?

Just checked: It is there, however initially always scrolled out of screen. Reproducible for me with all caches having more images than fitting on the screen.

**Comment by fm-sys** [comment]
@eddiemuc apart from the glitches mentioned here, do you consider the gallery ready for the next beta?

BTW, I'm pretty impressed by the recent performance boost. Thanks for keep working on the great new gallery 👍

**Comment by eddiemuc** [comment]
> @eddiemuc apart from the glitches mentioned here, do you consider the gallery ready for the next beta?

Yes, but I guess those glitches need some work first.


> BTW, I'm pretty impressed by the recent performance boost. Thanks for keep working on the great new gallery 👍

Thanks :-)

**Comment by eddiemuc** [comment]
Short update: while it is very clear (and easy fixable) that the "own" section is not displayed correctly, it is pretty unclear to me yet why the gallery scrolls up in the observed cases. 

What I have so far:
* gallery is always initialized to scroll to first image (this is why "owned" section is not seen if it doesn't contain an image)
* "scrollToPosition" on RecyclerView is called twice, which is a bug. However, making it call only once does not resolve the problem. (And calling it twice with same values might cause performance problems but should not result in the obsserved bug)
* Reading online, it is suggested to assign fixed heights to all involved views inside recyclerview. I did that. However, did not solve the problem
* Problem only occurs when "scrolling up" is needed (e.g. gallery was on image 8, now it should scoll to image 5 which is out-of-view)

I will continue investigating

**Comment by eddiemuc** [comment]
Update: it seems behaviour is caused when updating an image view in the recyclerview after image was loaded in background, and alos by applying View-visibility changed (e.g. changing a view from visible to invisible)

**Comment by eddiemuc** [comment]
I spent several hours now trying to get to the root of this problem without any result. Basically, the recyclerview just seems to scroll up "uncontrollably" in case it is scrolled upwards programmatically using scrollToPosition. Modifying the views in the list "too much" seems to increase the problem, but even if everything is made static the problem stays
