### ISSUE TITLE
Test-GeoKrety missing

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13596]
### Describe your problem!

We have now permanently CI errors:
~~~
18:30:49  cgeo.geocaching.connector.trackable.GeokretyConnectorTest > testSearchTrackable[android-30(AVD) - 11] [31mFAILED [0m
18:30:49  	java.lang.AssertionError:
18:30:49  	Expecting actual not to be null
18:31:29  
18:31:29  cgeo.geocaching.connector.trackable.GeokretyConnectorTest > testSearchTrackables[android-30(AVD) - 11] [31mFAILED [0m
18:31:29  	java.lang.AssertionError:
18:31:29  	Expected size:<2> but was:<0> in:
~~~

If I checked correctly than the used GK is missing at geokrety.org - GKB580.

@kumy You are the owner - please check it.

### How to reproduce?

See CI output, e.g. https://ci.cgeo.org/job/cgeo-CI_PR-build/3269/.

### Reproducible

Yes

### c:geo Version

2022.11.02 master

**Comment by kumy** [comment]
Everything seems fine on GK
- that lists the 2 GK: https://geokrety.org/szukaj.php?wpt=OX5BRQK
- [GKB580](https://geokrety.org/konkret.php?id=46464): has still it's last log correct
- Same for [GKB581](https://geokrety.org/konkret.php?id=46465)

Maybe it's related to GKM :thinking:

**Comment by kumy** [comment]
[GKM](view-source:https://api.geokrety.org/wpt/OX5BRQK) seems also fine

**Comment by kumy** [comment]
> Build #3269 (Nov 1, 2022, 6:26:57 PM) 

There was a GK service outage by that time yesterday

https://stats.uptimerobot.com/YnK8XSDwBw
![image](https://user-images.githubusercontent.com/176794/199599616-31b586f3-d33a-4b6d-8996-92853e667cce.png)

Anyway, thanks for reporting!

**Comment by moving-bits** [comment]
Most recent PR build today had all checks green, so seems to have been temporarily indeed. Thanks for cross-checking!
