### ISSUE TITLE
Remove GCVote

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13599]
Last days there are several reports on support mail and social media that cache loading gets stuck/slow in the phase of "Loading GCVote". Own test also shows, that the server (sometimes not always) fails to reply.

As this service is active for most users (as it defaults to "on" for retrieving votes also if the user has no login to send votes) it causes a severe regression as cache refreshes take much longer.

As the service is almost discontinued it looks like the right time to remove it (maybe even on `release` as a "bug fix").

As a successor is discussed in #9664 we should maybe not throw away the UI part of the code though.

**Comment by fm-sys** [comment]
IMHO we should rather turn off the GCVote connector for all users which are not actively registered (with possibility to re-enable it). Note that GCVote is still working (AFAIK it's just no longer possible to create new accounts). Changing the default setting (overriding the users previous choice) would already dramatically decrease server load which would make it more comfortable for those who still want to use it.

**Comment by fm-sys** [comment]
Was also discussed in #11487 last year

**Comment by Lineflyer** [comment]
> Changing the default setting (overriding the users previous choice) would already dramatically decrease server load which would make it more comfortable for those who still want to use it.

**Comment by fm-sys** [comment]
> At least at this moment the server is dead.

Who is saying this? I just entered the following line in the CMD:

```
curl https://ssl.webpack.de/gcvote.com/getVotes.php?waypoints=GC2J9J5
```
And got the expected response...
```
<votes userName='' currentVersion='3.3c' securityState='locked' loggedIn='false'>
<vote userName='' cacheId='048e2c88-14c4-4936-9020-105f3443bb0a' voteMedian='5' voteAvg='4.9031078610603' voteCnt='547' voteUser='0' waypoint='GC2J9J5' vote1='1' vote2='0' vote3='1' vote4='66' vote5='479' rawVotes='(1.0:1)(3.5:1)(4.0:29)(4.5:37)(5.0:479)'/>
<errorstring></errorstring>
</votes>
```

Response time mostly around 50-150ms, although some requests got stuck and timed out while loading...

Cannot test sending of votes though, as I have no credentials

**Comment by Lineflyer** [comment]
I tested the getVote without and with login yesterday and got a timeout from server for approx. 50% requests.
Just tested again and it seems a bit better but still sporadically failing. It especially happens to me if I make several consecutive requests in a short timeframe.

**Comment by moving-bits** [comment]
I could prepare a PR which
- sets GCVote default to "disabled" (which would only affect new users), and
- set GCVote state to "disabled" for all users

Users which want to continue using GCVote can re-enable it.
(The forced change should be mentioned in the changelog...)

This could be an intermediary step until we have decided on how to proceed with GCVote.

What do you think?

**Comment by Lineflyer** [comment]
As I still see it responds quite unreliable, we also still get complaints about slow refresh of caches and given the current unmaintained status of GCVote I think the proposal of @moving-bits is a good compromise.

**Comment by moving-bits** [comment]
See PR #13615 for the workaround

**Comment by moving-bits** [comment]
We had decided not to remove GCVote for the time being, and the workaround has been released quite some time ago, so let's close this issue.
