### ISSUE TITLE
Remember trackable actions per trackable 

### ISSUE THREAD

**Issue by fracz** [cgeo/cgeo#13590]
### Tell us your idea!

Currently the default action for trackables in your inventory is "No action". You can change in the settings that the default action should be "visited".

If you own some trackables that travel with you and some that don't, it's very tedious to select "no action" for stationary TBs and "visited" for travelling ones.

### What solution would you suggest?

Application should remember what action has been chosen for every TB in your inventory and set it as the default for the next logs. 

The new TBs you add to your inventory should have the default action set, i.e. "no action" or "visited", depending on the settings.

### Is there an alternative?

Selecting appropriate action on every log.

**Comment by Lineflyer** [comment]
Pretty similar but more generic than #495

I will close the old issue in favor of this one.

**Comment by janiesch** [comment]
Please introduce a settings option to set TBs to "no action" as a default as it was before. It is really a nuisance to me that I have to remember to turn off "visit" after I used it once.

Background: I have some marker TBs that I use for D5s etc. So it is really a pain, if I forget to turn them off right after.
