### ISSUE TITLE
Next beta / feature release

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13609]
Started preparing a new beta (as proposed in https://github.com/cgeo/cgeo/issues/13036#issuecomment-1302636857):

- [x] Check/Import incoming Translations from Crowdin
- [x] insert correct version name in /main/src/cgeo/geocaching/utils/BranchDetectionHelper.java 
- [x] Build release on CI Server
- [x] Perform smoke test with resulting cgeo-RC.apk before continuing
- [x] Upload and publish cgeo-RC.apk to Google Play
- [x] Trigger notification to status.cgeo.org via CI Server once the release is available on Google Play

---

Before we can release the following item(s) need to be fixed:
- [x] #13622 - affects all users of our current image gallery

**Comment by moving-bits** [comment]
If everything runs smooth the next days I propose to publish this release on upcoming Sunday to release the GCVote change.

**Comment by Lineflyer** [comment]
Is the GCVote change part of the current RC already or did it come later onto `release` and will only be contained in the final release?

**Comment by moving-bits** [comment]
> Is the GCVote change part of the current RC already or did it come later onto `release` and will only be contained in the final release?

It's been merged after our current RC.

**Comment by Lineflyer** [comment]
As decided in our call today, we will release now with current content of `release`.

I will prepare release next minutes after https://github.com/cgeo/cgeo/pull/13658 was merged by @moving-bits 


- [ ] Check and merge open Crowdin translation pull requests for `release`
- [ ] Check/Insert correct version name in ```/main/src/cgeo/geocaching/utils/BranchDetectionHelper.java``` (Format `YYYY.MM.DD`) on branch `release`. 
- [ ] Build release on [CI server](https://ci.cgeo.org/view/Release_Nightly/job/cgeo%20release/) (Download available after build from [here](https://download.cgeo.org/cgeo-release.apk))
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play (Account required for the c:geo team Google Play account)
- [ ] Tag the release on Github in format `market_yyyymmdd` (can be combined with next step if done on Github UI)
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github (Select Draft a new release from [here](https://github.com/cgeo/cgeo/releases), enter tag name (see above), make sure to select branch `release`, C&P change log, attach APK file, release the version)
- [ ] Publish release on F-Droid by running [this job](https://ci.cgeo.org/view/FDroid/job/Publish%20FDroid%20-%20RELEASE/) This requires, that the release APK has been uploaded to Github in previous step
- [ ] Trigger notification to status.cgeo.org via [CI server](https://ci.cgeo.org/view/Notification%20system/job/Create%20release%20notification/) once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment]
> I will prepare release next minutes after #13658 was merged by @moving-bits

merging done

**Comment by Lineflyer** [comment]
Release is rolling...Update tomorrow.

**Comment by Lineflyer** [comment]
@moving-bits 
After accidentally pushing and reverting on the wrong branch, I emptied the `changelog_base.md` on `master`. Please kindly doublecheck if everything is settled on `master`.

**Comment by moving-bits** [comment]
LGTM, we did not have changes that were exclusively on `master`, so `changelog_base.md` on `master` was indeed empty after releasing 2022.11.13 / I added to `changelog_full.md`, though, to stay up-to-date.

**Comment by Lineflyer** [comment]
Thanks for checking @moving-bits .
We are done with this release then. Thanks to all contributors!
