### ISSUE TITLE
Adventure Labs without premium

### ISSUE THREAD

**Issue by Regenhardt** [cgeo/cgeo#13608]
### Tell us your idea!

It would be nice to also do adventure labs in c:geo without a geocaching.com premium membership.

### What solution would you suggest?

Not sure why AL caches aren't shown (and on the logins overview shown as premium-only), when they can be done with the AL app by groundspeak with just the basic account, so changing that filter or whatever would be the solution I guess?

### Is there an alternative?

Currently I need the Adventure Labs app by groundspeak to do adventure labs without premium membership.

**Comment by Lineflyer** [comment]
As per agreement (and API usage conditions) adventure lab caches are only available for premium members in third-party apps (= non Groundspeak apps). So nothing we can do about that.

If you know any other third-party geocaching app providing adventure labs to basic members kindly give us a notice so we could doublecheck those conditions with Groundspeak.
