### ISSUE TITLE
Variables are lost when automatic storing is triggered

### ISSUE THREAD

**Issue by thoger** [cgeo/cgeo#13618]
### Describe your problem!

After opening a geocache that is not stored in the device, it is possible to go to the Variables tab and start adding variables.  Once any variable is added, c:geo automatically stores the cache in the device.  During that, previously set variables are lost.

### How to reproduce?

1. Open any geocache that is not already stored on the device.
2. Switch to the Variables tab and add any variable.  It should not matter if value is set.  Multiple variable can be set as well.
3. Switch to an other tab, e.g. Details.  When doing so, c:geo automatically stores the geocache in the device, adding it to the "Stored" list.
4. Switch back to the Variables tab again.

### Actual result after these steps?

Variables tab has no information.  All previously set variables were lost.

### Expected result after these steps?

Variables are preserved when automatic storing in device is performed.

### Reproducible

Yes

### c:geo Version

2022.10.17

**Comment by eddiemuc** [comment]
confirmed

**Comment by eddiemuc** [comment]
Fixed with PR #13621
