### ISSUE TITLE
Waypoint calculator view "broken"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13616]
### Describe your problem!

A user of the current new RC version reported, that the variables in the waypoint calculator view changed their position compared to 2022.10.17 and thats true. 

### How to reproduce?

Here is the screenshot of the user (and in nightlies it looks the same for me):

![image](https://user-images.githubusercontent.com/949669/200187327-77193e29-3932-4ed8-94b0-2e00083b438d.png)

### Reproducible

Yes

### c:geo Version

2022.11.05-RC

**Comment by moving-bits** [comment]
Thanks to instructions by @Lineflyer I was able to do my first `git bisect` today 🎉 and found the culprit:

Apparently it's an added hint for the variable name field, which is too long to be displayed and thus stretches the line height. Removing that hint brings variables list to regular line spacing.

```
<TextView
    android:id="@+id/variable_name"
    android:layout_height="wrap_content"
    android:layout_width="@dimen/equation_name_width"
    android:gravity="right"
    android:hint="@string/variables_varname_dialog_title"
    android:textSize="22dp"
/>
```

Removing or emptying the `android:hint` element will trigger a warning, but keeps the layout intact...
