### ISSUE TITLE
Lint QueryPermissionsNeeded

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13639]
### Describe your problem!

lint warning for the main project:

ProcessUtils.java:62,           QueryPermissionsNeeded, Priority: Normal

As of Android 11, this method no longer returns information about all apps; \ see https://g.co/dev/packagevisibility for details<p>Apps  that target Android 11 cannot query or interact with other installed  apps by default. If you need to query or interact with other installed  apps, you may need to add a `&lt;queries&gt;` declaration in  your manifest.  As a corollary, the methods `PackageManager#getInstalledPackages` and  `PackageManager#getInstalledApplications` will no longer return  information about all installed apps. To query specific apps or types of  apps, you can use methods like `PackageManager#getPackageInfo` or  `PackageManager#queryIntentActivities`.<div  style='color:#d00'><b><pre>        final  List&lt;PackageInfo&gt; packs =  CgeoApplication.getInstance().getPackageManager().getInstalledPackages(0);                                                                                           </pre></b></div></p>

### How to reproduce?

see https://ci.cgeo.org/job/cgeo-CI_PR-build/3357/androidLintResult/type.784642449/

### Reproducible

Yes

### c:geo Version

CI PR-build 3357

**Comment by moving-bits** [comment]
Does it state which packages are missing somewhere or is it just a general note?
We've added a list of packages to `AndroidManifest` some time ago already (see around line 950).

**Comment by bekuno** [comment]
> Does it state which packages are missing somewhere or is it just a general note? We've added a list of packages to `AndroidManifest` some time ago already (see around line 950).

The comment to the method `hasPackageInstalled` says: `This will find installed applications even without launch intent (e.g. the streetview plugin).`
So we want to find other apps on the smartphone.

**Comment by moving-bits** [comment]
From what I can see in the source, we only query for brouter and streetView packages using that method. Both are declared in our `AndroidManifest.xml`.

Tests query `com.android.settings` and `com.android.systemui`, which are not listed in our manifest, but the tests do not fail, so I guess the restriction gets applied for non-system packages only.

Thus I guess we can set this warning to be ignored.

**Comment by bekuno** [comment]
No such Lint Issue anymore after  #13696
