### ISSUE TITLE
Enable Powersaving when Device is turned upside down

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#13643]
### Tell us your idea!

When you are out in the wild the device is normally always on which is draining the battery massivly with an activated display.

Inside some other apps (e.g. Pokemon Go) you could activate a mode which is identifying when the device is held upside down, if this condition is true, the device is turning off the background light or the complete display, while keeping everything else active.
In our case the display should be turned off, but the proximity warning for instance should still be active.

Is it possible to introduce such a function in cgeo as well?

### What solution would you suggest?

Turn off the display when device is held upside down

### Is there an alternative?

Turn of the complete device resulting into proximity alert to be turned off as well

**Comment by SammysHP** [comment]
I'd say this is outside our control and should be handled by the system or a third-party app.

**Comment by fm-sys** [comment]
I agree that this feature shouldn't be included to cgeo.

@wolverine007 you could use an app like MacroDroid or Tasker and create a Macro/Task which changes the screen brightness depending on the orientation sensor data.
