### ISSUE TITLE
Variables: support square brackets as normal parenthesis 

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#13644]
### Tell us your idea!

For variable formulas I get feedback that people wish to support square brackets as normal parenthesis. Example Expression:

`(10-[1-4])*3`

Problem is that square parenthesis are currently used to define ranges. In example above, the square bracket expression is currently interpreted as a range from 1 to 3. However, the usage of square brackets as normal parenthesis seems to be much more frequent than the usage of ranges.

### What solution would you suggest?

Interpret square brackets as normal parenthesis in the future.

Change the way to define ranges: they can be defined using square brackets with a : following the opening square bracket. Example:

* `[:1-3]` would define a range from 1 to 3
* `[1-3]` would be simply evaluated to 1-3 = -2

### Is there an alternative?

Leave everything as is

**Comment by eddiemuc** [comment]
Implemented with PR #13693

**Comment by Lineflyer** [comment]
I think its a good change as more likely people use/copy square brackets for calculation and only a minor percentage used the range feature so far.
