### ISSUE TITLE
Variables get unsorted if wp extraction is active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13652]
### Describe your problem!

A user reported that variables from his personal note get "randomized" when refreshing the cache. He has to clean them up manually (using the "clean up" button) each time after refreshing the cache.

As soon as he switched off "WP extraction from note" for this cache the behavior is OK.

### How to reproduce?

- Have a personal note like this:
{c:geo-start}
@Finale (F) {CC|N 48° 0((X-2545)/1000)|E 011° ((X+25346)/1000)}
$A= | $B= | $C= | $D= | $E= | $F= | $G= | $H= | $I= | $J= | $K= | $L= | $M= 
| $N= | $X=A+B+C+D+E+F+G+H+I+J+K+L+M+N | $xQS=cs(X) # ==28 !
{c:geo-end}

- Refresh the cache in c:geo

### Actual result after these steps?

Variables on variable tab are not sorted alpphabetically

### Expected result after these steps?

Variables should be sorted alphabetically

Other test:
- Switch off "Waypoint extraction" for the cache
- Repeat the test steps above 
- Now the variables stay sorted alphebetically

### Reproducible

Yes

### c:geo Version

2022.10.17

**Comment by eddiemuc** [comment]
Great to see how extensive this feature is used by some users!

The bug is fixed in PR #13655

**Comment by wolverine007** [comment]
Yeah, the new variables tab is great for multis, where you have to gather a lot of answers.
Working with all the calculations and being able to stack them into each other is awesome.

At the end you could just put the calculation from the listing into the final coords and everything is gathered automatically from your variables into the calculation itself - best feature during the last month 👍🏻👍🏻👍🏻
