### ISSUE TITLE
New Image Gallery: remove legacy code

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#13653]
This is a reminder issue to remove legacy code of old image gallery once the new gallery is safe and stable in production.

List of what needs to be removed/changed:
* remove value "IMAGES" of enumeration cacheDetailsActivity.Page
* remove method Settings.enableFeatureNewImageGallery and setting var R.string.pref_feature_new_image_gallery
* Usages of above method will also lead to most places where change is needed
* remove class CacheDetailsActivity.ImagesViewCreator
* remove class/Acvitity "ImagesActivity"
*  remove class "ImagesList" (and also the vars in e.g. CacheDetailsActivity and others holding an instance to it)
* remove layout file "image_item.xml"
* remove layout file "cachedetail_images_page.xml"

**Comment by moving-bits** [comment]
@eddiemuc 
Hasn't this been completed in the meantime with #13847, #14130 and #14143 etc.?

**Comment by eddiemuc** [comment]
It is, thanks for reminding me. Can be closed
