### ISSUE TITLE
Background downloader should also be used from map popup window

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#13667]
### Tell us your idea!

c:geo now has two ways of downloading caches: In the foreground and in the background.

In some instances, foreground downloading still makes sense, e.g. when you want to actually OPEN a cache and read it immediately. However, in most (all?) other cases, background downloading should be used. 

Currently, if you select a cache on the map, and WITHOUT opening the full listing, clicking the download button in the mini popup, c:geo still uses foreground downloading. But in this case background downloading would make more sense, because you may want to quickly save multiple caches from the map to your device, one by one.

![2022-11-14 21 00 22](https://user-images.githubusercontent.com/54892606/201754624-4b9b5b8e-fee0-4691-9934-407af4a313cf.png)

**Comment by fm-sys** [comment]
@ztNFny has implemented something similar for our cache details view. Shouldn't be too hard to add it to the popup as well. 

Implementation note: Refresh should be prioritized (direct download, not adding it to the batch queue), but still should complete even if popup gets closed in the meantime.

**Comment by ztNFny** [comment]
Actually this one should be implemented like the background mass download. The single cache refresh is still using foreground download, just the UI component is no longer blocking.

**Comment by ztNFny** [comment]
> Actually this one should be implemented like the background mass download. The single cache refresh is still using foreground download, just the UI component is no longer blocking.

We might consider to put ALL cache downloads in a background thread. Currently only mass-downloads from map/list are in background, both CacheDetails and CachePopup are running on main (with different UIs)
Only exception might be the initial loading of a listing?

**Comment by moving-bits** [comment]
Storing/refreshing a cache from the popup uses background downloading meanwhile (see #15787), so let's close here.
