### ISSUE TITLE
Use GPX file generated by flopp.net as route or track

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13661]
A user on support mail used flopp.net to create a simple GPX with 20 waypoints (attached for reference). He would like to import it into c:geo either as route or maybe as a bunch of waypoints (=caches in c:geo).

It does however not work with any of our functions.
Is there a possibility we can process the file, or does the file need changes to be compatible?

Support ticket 540049

[monopoly_wilhelmshaven.zip](https://github.com/cgeo/cgeo/files/10001699/monopoly_wilhelmshaven.zip)

**Comment by moving-bits** [comment]
Tracks and routes have their own xml schemes. Tracks are defined by `<trk>`, `<trkseg>` and `<trkpt>`, routes by `<rte>` and `<rtept>`.

In contrast to this, the attached gpx file consists of a bunch of waypoints `<wpt>`, which would be close to our exported caches, but for them c:geo expects at least a `<name>GCxx</name>` (or similar) tag to identify the cache id.

Possible solutions could be:
- When using "load track" function, import `<wpt>` similar to `<trkpt>`.
- When importing caches, import `<wpt>` without `<name>` tags as user-defined caches.

**Comment by moving-bits** [comment]
I've implemented the first option with #13766:

![image](https://user-images.githubusercontent.com/3754370/208526946-0714fed8-4313-4e9e-97cf-dd5d3c1dcc69.png)
