### ISSUE TITLE
Invoke MapQuest only if no other geocoder is available

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13679]
### Describe your problem!

While debugging #13677 I also tested with a Google-enabled device.

AFAIR we are using a sequence of geocoders and only invoke the next one if the previous failed or provided no information.
The latest info I found was here: https://github.com/cgeo/cgeo/issues/5175

According to this I assume we use Google/Android and mapquest should only be used as fallback.
We do only have a 15k request quota per month.

When I however look into the logcat on my Google service enabled emulator I do still see a request to mapquest when I use the "search by address".

Someone should doublecheck the use in our code.

### How to reproduce?

- Search by Adress
- Look for network requests in logcat

### Actual result after these steps?

```2022-11-16 20:54:18.601  9646-9646  cgeo         cgeo.geocaching  D  [main] HTTP-GET: https://open.mapquestapi.com/geocoding/v1/address?location=k%C3%B6ln&maxResults=20&thumbMaps=false&key=Fmjtd%7Cluurn1u2n9%2Cbs%3Do5-9wynua {Network.request:345/Network.requestJSON:508/MapQuestGeocoder.get:52/MapQuestGeocoder.getFromLocationName:38/AddressListActivity.lookupAddressInBackground:48/AddressListActivity.onCreate:43/Activity.performCreate:8000/Activity.performCreate:7984}```

### Expected result after these steps?

Do not send request to mapquest unless no other service is available.

### Reproducible

Unclear

### c:geo Version

2022.11.13

**Comment by moving-bits** [comment]
The code responsible for this is in `AddressListActivity`:

``` 
private void lookupAddressInBackground(final String keyword, final AddressListAdapter adapter, final ProgressDialog waitDialog) {
    final Observable<Address> geocoderObservable = new AndroidGeocoder(this).getFromLocationName(keyword)
            .onErrorResumeWith(MapQuestGeocoder.getFromLocationName(keyword));
    AndroidRxUtils.bindActivity(this, geocoderObservable.toList()).subscribe(foundAddresses -> {
        waitDialog.dismiss();
        addresses.addAll(foundAddresses);
        adapter.notifyItemRangeInserted(0, foundAddresses.size());
    }, throwable -> {
        finish();
        showToast(res.getString(R.string.err_unknown_address));
    });
}
```

Although `AndroidGeocoder(this).getFromLocationName(keyword)` does return a valid result, still `onErrorResumeWith(...)` gets called - why is that?

I tried to catch any errors with `doOnError(...)` or `retry(...)`, but they did not get called.
Also the breakpoints in AndroidGeocoder`s try/catch statements were never reached.
No idea what's triggering `onErrorResumeWith(...)` here.

**Comment by Lineflyer** [comment]
thanks for taking care of those under the hood issues *Thumbs up*
