### ISSUE TITLE
splash image zoom false

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13708]
While I think the above looks more or less correct, on my Android 13 device it now looks like this (could not make a screenshot in time, so its a video of the device :) ):

https://user-images.githubusercontent.com/949669/202898570-0c3adb6d-9692-413d-b680-c0a7e304c720.mp4

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/13701#issuecomment-1321100894_

**Comment by bekuno** [comment]
This is the image extracted from the video:

![splash_defect 3](https://user-images.githubusercontent.com/32555742/203145017-9a6df150-08ed-44d6-9026-3023bed3e15d.jpg)

**Comment by moving-bits** [comment]
Was this with or without #13650?
For me c:geo did display such a super-sized logo on splash screen after #13650, which I reverted today, so it should be back to normal since then.

**Comment by bekuno** [comment]
> Was this with or without #13650?
> For me c:geo did display such a super-sized logo on splash screen after #13650, which I reverted today, so it should be back to normal since then.

@Lineflyer Can you check it with the next nightly?

**Comment by Lineflyer** [comment]
Current nightly is fine again on my device regarding the splash logo.

**Comment by moving-bits** [comment]
Thanks for cross-checking. Let's close here, then.
