### ISSUE TITLE
[unified map] Rendering performance needs improvement

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13718]
### Describe your problem!

When moving the map, VTM is always lagging and the moves are performed delayed.  It seems like the whole VTM rendering is done on main thread.

### How to reproduce?

The most impressive results you will see when there are many caches visible. However, a small delay is even noticeable if there are no caches at all.

### Expected result after these steps?

Map should move instantly and load not yet rendered tiles asynchronous.

### Reproducible

Yes

### c:geo Version

2022.11.23

### Additional Information

https://user-images.githubusercontent.com/64581222/203657352-9c0823fb-8294-4c74-9afb-07c75f829acc.mp4

**Comment by devemux86** [comment]
OpenGL rendering is in real time.

Can enable extra simplification on Mapsforge maps (useful for heavy vegetation, water)
with [Parameters.SIMPLIFICATION_TOLERANCE](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/utils/Parameters.java#L87-L91) for adjustable [zoom 8-11](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java#L188-L192).

Can test it with [Cruiser GL](https://play.google.com/store/apps/details?id=gr.talent.cruiser) (Settings | Map | Rendering | Performance).

**Comment by fm-sys** [comment]
I don't have the necessary knowledge about those insights, but why does rendering have to happen in real time? IMHO, the VTM map is completely unusable in the current state (see video above).

**Comment by devemux86** [comment]
OpenGL and hardware rendering of vector data works differently (no bitmap tiles).

> VTM map is completely unusable in the current state

VTM seems fine in [Cruiser](https://play.google.com/store/apps/details?id=gr.talent.cruiser) and the many other apps that use it.
Any maps that load them with multiple overlays will be rendered unusable.

Can debug the process and see how use the VTM map step by step,
what offline map, e.g. Germany vegetation and Netherlands water like extra simplification,
and how many overlays load on the map.

**Comment by fm-sys** [comment]
I'm using a Germany map file from OpenAndroMaps for testing on a Huawei Mate 20lite running Android 10. 

I've noticed the same laggy behavior when using Cruiser GL vs Cruiser. Two more videos attached... 

Classic Mapsforge: tile rendering is slower, however movements are performed with higher FPS

https://user-images.githubusercontent.com/64581222/203828658-57a6870c-2b27-4e27-a4d8-312e0e187619.mp4

VTM: Rendering is faster, however movements are performed with really low FPS rate (especially in busy areas). 

https://user-images.githubusercontent.com/64581222/203828645-27191705-c114-46ad-a637-c55a86b04b9b.mp4

**Comment by devemux86** [comment]
@fm-sys thanks for extra test.

Please also report it in [VTM](https://github.com/mapsforge/vtm) issues, so VTM users / developers can look into it.

**Comment by fm-sys** [comment]
I've just opened an issue, https://github.com/mapsforge/vtm/issues/982

**Comment by moving-bits** [comment]
@fm-sys 
Still happening lately?

**Comment by fm-sys** [comment]
Yes, but my primary device is already nearly 5 years ago. I assume the GPU just isn't that good and we have to live with that... (or implement the "classic mapsforge" as soon as unified map is ready for production)
