### ISSUE TITLE
Personal note of 6000 char length fails to upload on opencaching.de

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#13721]
### Describe your problem!

Upload of a long personal note to opencaching.de is failing

see download of personal note #13651

### How to reproduce?

* Open e.g. OC16E8B in c:geo
* Enter a really long personal note (e.g. 6000 char)
* upload the note

### Actual result after these steps?

Error appears: "Error uploading personal note"

### Expected result after these steps?

I thought personal note up to a length of 20k is possible

### Reproducible

Yes

### c:geo Version

2022.11.22-NB

### Additional Information

I tried to upload the downloaded long personal note from #13651 via postman and got the response 
`"414 Request-URI Too Long" 
The requested URL's length exceeds the capacity limit for this server.`

Note of 5700 char length ist working, 5800 length is not working...

The max personal length is 20k but it seems that it is not possible to upload a note of 20k via okapi

**Comment by murggel** [comment]
@teiling88 do you have any idea here?

**Comment by teiling88** [comment]
Can you send the private_note via post instead of get? Otherwise I can't do anything in this case :/

**Comment by murggel** [comment]
No, post returns the same error

**Comment by murggel** [comment]
Then we should probably set the limit to 5700

**Comment by teiling88** [comment]
Did you remove the private_note param from the url?

**Comment by murggel** [comment]
Yes, with removing the new_value from the url and putting it into the body it worked...

**Comment by teiling88** [comment]
This is not an okapi or opencaching.de issue. If the url is to long the webserver will deny the request.

**Comment by murggel** [comment]
I will try it then with a post-request in c:geo

**Comment by murggel** [comment]
implementation is done in the PR #13726, but tests are failing due to missing OC-configuration.

OC-configuration has to be set-up in the CI to run proper tests, 
see https://github.com/cgeo/cgeo/pull/13726#issuecomment-1337481783
