### ISSUE TITLE
Re-enable submenu "Options for basic members"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13724]
### Describe your problem!

When logged in as basic member the settings - Services - geocaching.com contain a menu option "Option for basic members". 

There is however nothing behind/below. 
It once was used for distance arrow setting and maybe other items we removed meanwhile.

The menu item seems superflous and should be removed unless its a bug, that it cannot be opened.

### How to reproduce?

- Login as basic member
- Go to Menu - Settings - Services - geocaching.com
- Tap on "Options for basic members"

### Actual result after these steps?

Nothing happens

### Expected result after these steps?

Either a menu should open (if its a bug) or it the item should be removed (if its really empty)

### Reproducible

Yes

### c:geo Version

2022.11.25-NB

**Comment by moving-bits** [comment]
The subsection is still in use, but got lost during settings' migration, as it was still using a nested `PreferenceScreen`, which the old Android Preference library supported, but AndroidX Prefences do not. PR #13725 fixes this.
