### ISSUE TITLE
New trackable in inventory will be set to visit automatically

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13720]
### Describe your problem!

A user reported, that despite he has not activated "Visit TB" (for automatically setting trackables in inventory to visited on logging a cache) any new trackable he add to his inventory will be set to visited.
The problem seems new to the user since we introduced remembering the visit state from last log for the next log.

Did not yet try to reproduce, but the user was quite clear in his error report.

### How to reproduce?

- Make sure "Visit TB" in Menu - Settings - Logging is switched off
- Have some trackables in your inventory (some set to "visit", some to "Do nothing") 
- Grab or retrieve a new trackable into your inventory
- Log another cache

### Actual result after these steps?

The recently added trackable in your inventory will show "Visit" 

### Expected result after these steps?

The recently added trackable in your inventory should show "Do nothing" (unless the "Visit TB" setting is active).

### Reproducible

Unclear

### c:geo Version

2022.11.13

### Additional Information

Support ticket 300248

**Comment by moving-bits** [comment]
I'll try to look into it over the weekend
