### ISSUE TITLE
Next bugfix release (after 2022.11.25)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13723]
Whether or not the next release will be a pure bugfix release or a new beta from current state of `master`, the following issues have been listed to be open bugs, we would like to fix:

- [x] #13434 <-- was the most frequent error reported on Play Store for our last release.
- [ ] #11725
- [ ] #13698 
- [ ] #13666 
- [ ] #13675
- [x] #13724
- [x] #13730
- [x] #13731

**Comment by moving-bits** [comment]
Starting to prepare a new bugfix release as discussed in https://github.com/cgeo/cgeo/pull/13768#issuecomment-1361348460:

- [ ] Check/insert correct version name in /main/res/raw/changelog_bugfix.md
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting cgeo-release.apk before continuing
- [ ] Upload and publish cgeo-release.apk to Google Play
- [ ] Tag the release on Github in format market_yyyymmdd
- [ ] Publish the release on Github including upload of cgeo-release.apk to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment]
New release is "out in the wild" for a couple of days and seems to behave ok so far, guessing from Play Console stats, so let's close here. If anything new should come up, please list under #13772.
