### ISSUE TITLE
Enable Proximity Sounds via Map Quick Settings 

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#13745]
### Tell us your idea!

Right now it is a long journey to enable the Proximity Sound feature via the settings menu and find the correct spot inside the map settings section.

It might be easier, when this feature could be enabled via the map quick settings menu:

![IMG_20221203_155541](https://user-images.githubusercontent.com/4508228/205447145-e33cd41d-4cd8-42c6-b9fb-29f3d3dde924.jpg)

### What solution would you suggest?

Add an additional button inside the map quick settings menu, to enable or disable the proximity sound feature.

In general the option to define your own sound might be cool as well.

### Is there an alternative?

See above, do it again and again via the long settings menu.

**Comment by moving-bits** [comment]
Prerequisite would be that the user has configured distances already.

Which proximity notifications should be enabled by this - general of special or both?

Proposal for this:
- in map quick settings "general proximity notifications" could be enabled/disabled
- in cache/waypoint popup "special proximity notifications" could be enabled/disabled

For both places: Add a single image button (loudspeaker symbol, toggling between enabled and disabled state).

**Comment by wolverine007** [comment]
@moving-bits Hi, found this requested feature implemented into RC 2023.08.05 - thanks for that.

But it seems not to be implemented correctly, only when the user has enabled the setting inside the config, the toggle button is shown inside the map quick settings menu:

![IMG_20230814_084419.jpg](https://github.com/cgeo/cgeo/assets/4508228/ef4eb500-4a1b-45f2-b13e-5c1715654026)

But when I am disabling the setting, the checkbox is completly disappearing from the menu again... 

That wasn't the expected result... 

Cheers, 
wolv

**Comment by moving-bits** [comment]
@wolverine007 
Good catch! Button currently gets hidden when it's disabled, so you have no chance to enable PN from within quick settings again... PR #14509 fixes this. Should be available in the next nightly version. (Not RC, though, but if nothing unexpected comes up the next days, a new release is planned for this week.)

**Comment by wolverine007** [comment]
> @wolverine007 
> Good catch! Button currently gets hidden when it's disabled, so you have no chance to enable PN from within quick settings again... PR #14509 fixes this. Should be available in the next nightly version. (Not RC, though, but if nothing unexpected comes up the next days, a new release is planned for this week.)

Awesome, thanks 👌🏼
I could check it on my other device which is running the nightly stack.
But a new RC is nice as well 😎
