### ISSUE TITLE
Donations via App / PlayStore

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#13741]
### Tell us your idea!

Would it be possible for c:geo to accept donations via the App.
I assume that would be via the PlayStore or something.

### What solution would you suggest?

Payment option in the App somewhere

### Additional Information

I have spare credit on a PAYG SIM card that I can use to pay for play store items, it'd be nice to give it to a good cause.

**Comment by fm-sys** [comment]
Thanks for your interest, donations are always welcome :)

However, cgeo's running costs are quite low, so we luckily aren't under pressure to increase our donation income. Donations via PlayStore are no priority for us, and even if they would there are many questions. Should this be done via in-app payments, a c:geo premium verion (same features just with golden app icon)? This all doesn't seem to fit to c:geo... (Not to mention that Google would receive 30% of the donation money)

Another posibitlty would be donations via G Pay (e.g. Signal Messenger supports this, no advertisement ;-)). However, I want to highlight that Google Play credits can exclusively be spent inside the play store, not externally via G Pay.
