### ISSUE TITLE
WP's fehlen nach export aus GSAK und import in CGEO

### ISSUE THREAD

**Issue by detrijesusters** [cgeo/cgeo#13740]
See [this item] (https://www.geoclub.de/forum/t/wps-fehlen-nach-export.82272/)

As far as i can see it's not the export from GSAk that goes wrong. It looks like it's the import in CGEO

The cache where i have problems with is attached

[defprio.zip](https://github.com/cgeo/cgeo/files/10112717/defprio.zip)

**Comment by SamHenkel** [comment]
Und hier das korrigierte GPX file:
[GC1ZRFZ mit korrigierten WP-Codes](https://github.com/cgeo/cgeo/files/10114511/GC1ZRFZ-BOeR.zip)

**Comment by SammysHP** [comment]
This was identified as "user error": The waypoints could not be associated with their parent cache due to their naming. The name must consist of the waypoint code which is always two characters followed by the base GC code.
