### ISSUE TITLE
creating GC lists/adding caches to GC list fails (GC bookmark web-API URL change)

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13759]
GC has changed the internal API URL for bookmark lists from https://www.geocaching.com/api/proxy/web/v1/lists to https://www.geocaching.com/plan/api/lists/
The old one still works for GET requests as of now, but POSTS already fail. The new one also requires a CSRF-Token for POSTS (not sure we're using those)

**Comment by ztNFny** [comment]
the existing calls to https://www.geocaching.com/api/proxy/web/v1/lists now require a "X-Verification-Token" header, the value of which can be obtained from cache pages: input[name="__RequestVerificationToken"]

All list management calls (add is the only one we use afaik) should go to the new URL, all cache-related calls still go to the old URL.

**Comment by ztNFny** [comment]
@Lineflyer could be worth a FAQ entry (or even a notification) before support tickets start piling in

**Comment by Lineflyer** [comment]
Our notification system is totally broken at this moment due to missing backend database. See some issue in cgeo/status repo.
A FAQ entry is doable but I can't help. I am in a bit of stress to manage logistics of car pickup, car sale, tire change and vacation preparation ;)

**Comment by fm-sys** [comment]
> @Lineflyer could be worth a FAQ entry (or even a notification) before support tickets start piling in

I don't expect that so many users really use the bookmark functionality from within cgeo. I would vote for just fixing the bug without additional notice.

**Comment by moving-bits** [comment]
FYI: AFAICS we had two reports on support for this during the last two weeks

**Comment by ztNFny** [comment]
There are 2 APIs in use currently:
https://www.geocaching.com/api/proxy/web/v1/lists
with Header: 'X-Verification-Token', the value for which is received from a cache listing page: document.querySelector('input[name="__RequestVerificationToken"]').value

https://www.geocaching.com/plan/api/lists/
with Header: 'CSRF-token', the value for which is received from https://www.geocaching.com/plan/lists/: window._csrf

At least the CSRF-token seems to be valid for a while (at least 3h), despite the page returning a new value on each reload

**Comment by moving-bits** [comment]
We have issues about this opened on support, not many (1 or 2 per week), but regularly.

**Comment by ztNFny** [comment]
In my JavaScript app i try to use the existing token (as i haven't figured out yet reliably how long they are valid - wanted to write a script to test that but didn't get around to it yet), if that falls i clear and retrieve a new one
 Wanted to implement the same in cgeo but have been hit by a bad flu for quite a while now, do if anyone wants to take a shot ...

`  function getListCsrfToken() {

1562

    if (typeof unsafeWindow._csrf === "undefined") {

1563

      const xhr = new XMLHttpRequest();

1564

      xhr.open('GET', 'https://www.geocaching.com/plan/lists/', false);

1565

      xhr.onreadystatechange = () => {

1566

        if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {

1567

          var csrf = xhr.responseText.match(/window._csrf = "([^"]*)"/)[1];

1568

          unsafeWindow._csrf = csrf;

1569

          return csrf;

1570

        }

1571

      }

1572

      xhr.send();

1573

      return xhr.onreadystatechange();

1574

    }

1575

    return unsafeWindow._csrf;

1576

  }

1577

​`

**Comment by Lineflyer** [comment]
I am just now seeing that this regression is listed here as still open. 
Are we just waiting for the situation to become stable on server side, or do we have a technical struggle to fix it?

**Comment by ztNFny** [comment]
It hasn't changed again in those 3 weeks anymore, at least my current implementation still works. However I don't have much time for coding right now, will probably not be able to tackle that in the next 6 weeks, so if someone wants to take a stab ...

**Comment by Lineflyer** [comment]
Anyone working on that?
Its still an open regression since longer time due to website change.

**Comment by ztNFny** [comment]
I'll try to find the time for this this week

**Comment by Lineflyer** [comment]
Still an open regression :(

**Comment by ztNFny** [comment]
> Still an open regression :(

Should be fixed by my PR. Is there still some issue or did it just not auto-close due to target being release?

**Comment by ztNFny** [comment]
This is working fine on both master and release, verified against the latest commits.
