### ISSUE TITLE
Needs Maintenance & Needs Archived log types renamed

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#13756]
### Describe your problem!

The **Needs Maintenance / Maintenance suggested** log type is now **Owner attention requested**.  
The **Needs Archived** log type is now **Reviewer attention requested**.

This change is currently in the App, the release note says "We will rename the Needs Maintenance and Needs Archived logs on the Geocaching.com website in early 2023"

Do you need to take account of this?
Details here...

https://forums.geocaching.com/GC/index.php?%2Ftopic%2F386306-release-notes-geocaching%C2%AE-app-report-a-problem-log-type-names-december-9-2022%2F

### How to reproduce?

Log one of the renamed types.

### Reproducible

Yes

### c:geo Version

2022.11.25

**Comment by moving-bits** [comment]
seems that they have changed this only in their app, but not in the interfaces c:geo uses, so let's close here.
Thanks for notifying us anyway.
