### ISSUE TITLE
"Hide map sources" not working

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13750]
In settings i marked some map sources to hide them but they are still listed in map selection

Nightly 2022-12-04

![IMG_20221206_204412.jpg](https://user-images.githubusercontent.com/1258173/206007493-d021c8a4-5c58-46a1-9881-6674226a0b54.jpg)
![Screenshot_2022-12-06-20-34-24-05_a916ceb0c8a82619faeb76fe6b8ae997_1.jpg](https://user-images.githubusercontent.com/1258173/206007514-e67d5cc5-d730-4f17-a769-66e142b3b958.jpg)

**Comment by moving-bits** [comment]
Are you in UnifiedMap or in CGeoMap/NewMap?

"Hide map source" is a new feature of UnifiedMap and not available for CGeoMap/NewMap. The config item will only be displayed if you have activated UnifiedMap via the hidden config setting.

**Comment by ztNFny** [comment]
I'm using the old map. Didnt realize this is a setting only for the new one.
