### ISSUE TITLE
CAPTCHA_REQUIRED

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13767]
@mucek4 
Can you have a look at the CI and try to fix the CAPTCHA_REQUIRED on the server?
Seems to be a case of https://manual.cgeo.org/en/loginproblems#login_failedcaptcha_required

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/13762#issuecomment-1358397816_

**Comment by bekuno** [comment]
It looks like you have to log out of GC first before logging back in to c:geo.

**Comment by ztNFny** [comment]
dup of #13747
