### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13772]
Following the discussion about a new folder structure, we have released a bugfix version 2022.12.21 to be able to migrate both `master` and `release` to the new folder structure. We plan to release a new beta branched from `master` in a couple of days. 

Let's collect issue/PRs here, which should (ideally) be included as well:

- [x] #13778
- [ ] #13759
- [ ] #11725
- [ ] #13698 
- [x] #13666 
- [ ] #13675
- [x] #13751
- [x] #13796
- [x] #13849
- [x] #13850
- [ ] #5599
- [ ] #10428
- [ ] #13999
...

(Feel free to edit this list)

**Comment by moving-bits** [comment]
- There has been a stab ab #13666 with #13733, let's see in the next beta whether this helps.
- For #11725 I have learned that this seems to be a pretty old issue, much older than the issue number may indicate.
- Same with #13675 (respectively display of waypoints and caches in general, which is unreliable on OSM).

**Comment by Lineflyer** [comment]
As just discussed in our team meeting:
We should issue a new beta which will include (besides a bunch of other features) the new image gallery.

In order to do this, we should pay attention to the following items:
- [ ] Fix current CI problem:
cgeo-4 failing, cgeo1 and cgeo-2 offline
@Lineflyer will ask @mucek4 for reboot and for a possible solution to reboot remotely

- [ ] Add keys for opencaching.de to the CI + define a test user
This is prerequisite to merge #13726 

- [ ] Fast-forward `release` to `master`
Important for this step:
  - [ ] Check Crowdin file structure and existing translations after merge (due to changed file structure)
  - [ ] Check CI-jobs specific for `release` whether they build properly with new file structure

**Comment by Lineflyer** [comment]
Back from business trip:
@mucek4 wanted to check the CI and the missing executors...did anything change meanwhile?

**Comment by Lineflyer** [comment]
Not sure if we are ready to forward `release` or `master`. Just tell me when and what and I will try to do the git magic.

**Comment by moving-bits** [comment]
Even though not all items of above's list are tackled yet we can start a new beta cycle, IMHO. `master` contains a lot of useful new things as well as some fixes, and AFAICS there are no urgent fixes currently being worked on. Thus I vote for starting a new beta cycle to get a broader user feedback for the changes on `master` as well as to resolve the disparity between `release` and `master`.

**Comment by Lineflyer** [comment]
One day late, but going to merge branches tonight at 9pm if no one objects (e.g. if WIP on `master`).

**Comment by Lineflyer** [comment]
Merge has been done, including changelog operation.
Checking on Crowdin now, whether the directory structure is matching and translations are still valid.

**Comment by Lineflyer** [comment]
Crowdin looks fine, have proofread some long standing translations and now waiting for sync/PR from Crowdin.
After those are checked and merged I will compile and push the RC version.

@moving-bits If you happen to be at PC: Could you crosscheck the changelogs and branch detection helper content on `release`?

**Comment by eddiemuc** [comment]
> Merge has been done, including changelog operation. Checking on Crowdin now, whether the directory structure is matching and translations are still valid.

Crowdin has created a second copy of our translated files (strings.xml, changelog_*.md) in the release branch. It did the same thing on master, I deleted there the old files after I was sure the process works with the new ones. Same needs to be done for release branch I assume:

![image](https://user-images.githubusercontent.com/6909759/215686334-3986790f-0753-4988-b035-6b4d8911387b.png)

**Comment by Lineflyer** [comment]
@eddiemuc Thanks. Done! seems to work.

What about `strings_old.xml` in folder `archive` ?

**Comment by eddiemuc** [comment]
> @eddiemuc Thanks. Done! seems to work.
> 
> What about `strings_old.xml` in folder `archive` ?

That's the outdated strings.xml of master branch. I didn't want to really delete it back then in case we need it later...

But now I guess it can be deleted too

**Comment by Lineflyer** [comment]
But that file is no longer in our repository, isn't it?

**Comment by Lineflyer** [comment]
I removed it on Crowdin, should be all matching now with our new structure.

**Comment by eddiemuc** [comment]
> But that file is no longer in our repository, isn't it?

Correct. Crowdin keeps its own "file" structure Independent of what we have in out repo (I learned this the hard way....)

**Comment by bekuno** [comment]
> * Check CI-jobs specific for `release` whether they build properly with new file structure

I fixed the job `WatchdogTests_release`.

PR #13942 should fix job `cgeo-CI_pipeline-experimental`.
@Lineflyer Please test the job with this PR.

All other jobs looks ok now.

**Comment by Lineflyer** [comment]
We have a bunch of fixes on `release` based on beta feedback of 2023.01.30-RC.
I will therefore update to a new beta tonight. Any objections?

**Comment by Lineflyer** [comment]
2023.02.05-RC is rolling.

**Comment by moving-bits** [comment]
From what I can see on support and Play Store stats there seem to be no major issues with current beta, so I propose to release this version. Any objections?

I'll start working on it later this evening if no one stops me...

**Comment by moving-bits** [comment]
Start preparing a new release:

- [ ] Check and merge open Crowdin translation pull requests for `release`
- [ ] Check/Insert correct version name in ```/main/src/cgeo/geocaching/utils/BranchDetectionHelper.java``` (Format `YYYY.MM.DD`) on branch `release`. 
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
Thanks @moving-bits for taking care of the release.
According to our status system the release seems to be available, I therefore triggered the notification.

![grafik](https://user-images.githubusercontent.com/949669/218401638-1e5cd997-8554-4525-98c3-30ad5ee2f2a5.png)

**Comment by Lineflyer** [comment]
Done here, follow up is  in #14024
