### ISSUE TITLE
Waypoints with empty space in name field not imported from GPX

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13794]
### Describe your problem!

A user contacted us with issues on importing self created GPX files:
Depending on the content of the tag `<name>` some  waypoints contained in the GPX are not imported. 

It seems as soon as a blank is contained the waypoint is not imported.

### How to reproduce?

Try to import this GPX:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gpx
 xmlns="http://www.topografix.com/GPX/1/1"
 creator="OziExplorer Version 3956f - http://www.oziexplorer.com"
 version="1.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
<metadata>
 <time>2022-12-25T09:03:59Z</time>
 <bounds minlat="55.917333" minlon="92.275015" maxlat="56.021194" maxlon="92.978554"/>
</metadata>
<wpt lat="56.0051300" lon="92.8536300">
 <time>2021-07-04T00:00:00.000Z</time>
 <name>26859 1</name>
</wpt>
<wpt lat="56.0067300" lon="92.8726700">
 <time>2021-07-04T00:00:00.000Z</time>
 <name>26859-2</name>
</wpt>
</gpx>
```

### Actual result after these steps?

Waypoint `26859 1` is not imported, waypoint `26859-2` is imported.

### Expected result after these steps?

Both waypoints should be imported.

### Reproducible

Unclear

### c:geo Version

2022.12.21

### Additional Information

Example files provided by user with following additional info:
From non-working.gpx I can migrate only 12 points, from working.gpx all 23.

[non-working.zip](https://github.com/cgeo/cgeo/files/10313812/non-working.zip)
[Working.zip](https://github.com/cgeo/cgeo/files/10313815/Working.zip)

**Comment by murggel** [comment]
I looked into this:

The name of a waypoint is used for looking for the GeoCode of a cache. A valid GeoCode exists of at least 5 letters or numbers. If a pattern is found in the name, it will be used as GeoCode / identification for the cache.

If now the first "word" of the name of a waypoint consists of at least 5 letters or numbers, it will be interpreted as the GeoCode.
A second waypoint with the same "first word" exists in the GPXt will be treated then as the same cache and therefore not imported a second time.

e.g. name = "26859 1" is read to GeoCode "26859"
waypoint with name = "26859 2" is also read to GeoCode "26859" and therefore overwrites the first waypoint.

If this is the case, a log-entry `Duplicate geocode during GPX import: 26859`  is created, (but there is no notification to the user).

**Comment by murggel** [comment]
There was already an issue #9336 for looking in description for a geocode..
I don't know, why the geocode is still read from the name for UNKONW_CONNECTOR, and not the whole name is taken as already proposed by myself in comment https://github.com/cgeo/cgeo/issues/9336#issuecomment-732392366

**Comment by murggel** [comment]
PR #13858 will fix this
