### ISSUE TITLE
Allow usage of c:geo without permission to access fine GPS location

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#13798]
# Current Status

c:geo is currently implemented such that it can't be used when accessing fine GPS location permission is not granted. As long as it is not granted, the user will be caught in a loop of popup dialogs asking him/her to grant this permission.

# Problem statement

I question this design decision. I argue that c:geo can be used meaningfully also without location information, e.g. to search caches, store offline caches and use map viewer capabilities. 

Fro a technical perspective, this "asking" for permission spoils many parts of the code because asking for this permission is implemented in almost all activities.

Last but not least, the current implementation is an actual showstopper for GUI tests using Espresso. This is because the c:geo emulator instance on CI naturally does not have the fine location permission, and c:geo activities are implemented in such a way that they will hang during onResume method in an endless loop when asking for such permission over and over again. So on CI Espresso can never get Activities into a RESUME state - which is the prerequirement for GUI tests. See #13761

# Proposed solution

I propose NOT to make the permission mandatory. Instead, if user does not give fine location permission then the GPS sensor implementation should output a fake coordinate. I propose N 45° 17.460 W 122° 24.800 (I guess you know why :-))

c:geo can then reask fine location permission once on every c:geo startup. I think that's enough.

**Comment by bekuno** [comment]
The initial implementation of the permission framework was in a time, where only @rsudev was an active developer. 
The implementation was started by @ControlTheBit, but he could not finished the work becazse of missing spare time.
Finaly the permission implementation was integrated by @rsudev and a bit by me.
This was a critical moment for c:geo, as this was necessary to meet the Google API restrivtions.

So feel free to optimize/rework the permission framework.
The idea with a default coordinate is fine. Instead of question the user on every startup we should make the location configurable. (sensor, default loc, self defined loc). This should then be prominent on the c:geo overview page.

**Comment by Lineflyer** [comment]
I do also see optimzation potential in our permission handling (from UI and usage flow perspective).
However if we allow using c:geo with coarse or no location permission there should be a really BIG RED message somewhere on the dashboard at least.

**Comment by fm-sys** [comment]
Side note - coarse permission handling was recently touched here: #13424

**Comment by eddiemuc** [comment]
> Side note - coarse permission handling was recently touched here: #13424

Thanks @fm-sys . I have a questions wrt this PR though: in Android documentation it says that one should always request fine and coarse location permission together:  https://developer.android.com/training/location/permissions#approximate-request:

> To handle this potential user behavior, don't request the ACCESS_FINE_LOCATION permission by itself. Instead, request both the ACCESS_FINE_LOCATION permission and the [ACCESS_COARSE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_COARSE_LOCATION) permission in a single runtime request. If you try to request only ACCESS_FINE_LOCATION, the system ignores the request on some releases of Android 12.


However, the PR (if i understand it correctly) does the opposite: it explicitely requests ONLY the fine location permission (without coarse permission).
So isn't it doing the opposite of what Google recommends?

**Comment by moving-bits** [comment]
Thumbs up for enabling c:geo to run without granted fine location permission. It should offer all functions even when only having been granted coarse location permission (which means: no GPS, but other means of detecting location), and most functionality without any location permission at all.

**Comment by fm-sys** [comment]
> > To handle this potential user behavior, don't request the ACCESS_FINE_LOCATION permission by itself. Instead, request both the ACCESS_FINE_LOCATION permission and the [ACCESS_COARSE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_COARSE_LOCATION) permission in a single runtime request. If you try to request only ACCESS_FINE_LOCATION, the system ignores the request on some releases of Android 12.
> 
> However, the PR (if i understand it correctly) does the opposite: it explicitely requests ONLY the fine location permission (without coarse permission). So isn't it doing the opposite of what Google recommends?

This is true, my PR isn't a good solution unfortunately. However it was helpful to prevent a crash described in #12152. However, it would be better to fix the root cause of that crash (together with the refactoring of permission management) instead of blocking to reach the problematic code.

**Comment by eddiemuc** [comment]
> It was helpful to prevent a crash described in #12152. However, it would be better to fix the root cause of that crash (together with the refactoring of permission management) instead of blocking to reach the problematic code.

Ok, understood. Thanks for explaining.

**Comment by eddiemuc** [comment]
Sorry, I have a maybe dumb question:
there seem to be 4 Location-related permissions in Android: ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION, ACCESS_BACKGROUND_LOCATION and ACCESS_LOCATION_EXTRA_COMMANDS. I understand ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION, and as far as I see ACCESS_LOCATION_EXTRA_COMMANDS is not used by c:geo.

But what about ACCESS_BACKGROUND_LOCATION? It is not defined in our manifest, so we obviously dont use it. But wouldn't that be needed by some features of c:geo? 

For example, we have a ProximityNitification-Service (which I never used). Wouldn't this require for c:geo to have the user's position even when c:geo is not in the foreground, user uses other apps or phone is in off-mode? How does this feature work currently?

**Comment by bekuno** [comment]
For ACCESS_BACKGROUND_LOCATION see #10781

**Comment by eddiemuc** [comment]
> For ACCESS_BACKGROUND_LOCATION see #10781

In the referenced issue it is said that some things can be started as foreground service (e.g. SpeechService when navigating to a cache) and then background location is not needed. This is understood.

But again, how is this solved for proximity notifications? This is configured in settings and thus should survive e.g. a restart of c:geo. Is this started as foreground service e.g. in MainActivity? (because a background service would not work, at least to my understanding)

**Comment by eddiemuc** [comment]
Also (and I really beg forgiveness for these many questions): @fm-sys in #13085 you fixed an issue about making the speech service more robust against "killing" by making it a foreground service. But I just read, in order for a foreground service to still reeive location data (which I assume is needed by speech service?) you need to declare it as `android:foregroundServiceType="location"` in AndroidManifest.xml. Got this e.g. from here https://developer.android.com/about/versions/10/privacy/changes#app-access-device-location: 

> An app is considered to be accessing location in the background unless one of the following conditions is satisfied: 
> ... 

> The app is running a foreground service that has declared a foreground service type of location

--> So I don't really understand why your fix is working :-). Do you have additional info here for me?

**Comment by fm-sys** [comment]
> But I just read, in order for a foreground service to still reeive location data (which I assume is needed by speech service?) you need to declare it as android:foregroundServiceType="location" in AndroidManifest.xml

I'm not sure about this. Maybe it works as long as the foreground service is started by a foreground activity? Furthermore the fix was developed for target API 29, does it still work at all? Anyway, adding this flag would be a good idea...

**Comment by fm-sys** [comment]
> For example, we have a ProximityNitification-Service (which I never used). Wouldn't this require for c:geo to have the user's position even when c:geo is not in the foreground, user uses other apps or phone is in off-mode? How does this feature work currently? 

@moving-bits can you add some insights? As far as I understood these notifications will only work while using the Livemap. But I haven't used the feature myself... 

In any case we shouldn't request ACCESS_BACKGROUND_LOCATION if it's not absolutely necessary:

> Note: The Google Play store has updated its policy concerning device location, restricting background location access to apps that need it for their core functionality and meet related policy requirements. Adopting these best practices doesn't guarantee Google Play approves your app's usage of location in the background.

https://developer.android.com/training/location/background

**Comment by Lineflyer** [comment]
Link to #7990 , #11029

**Comment by Lineflyer** [comment]
Removing storage permission would potentially also fix #13638

**Comment by eddiemuc** [comment]
Hm, so shall we remove WRITE_EXTERNAL_STORAGE permission completely?

I did some testing trying to pick media files created by other apps ("Camera" in my case), and it seems to work even w/o this permission in both SDK23 and SDK31

**Comment by moving-bits** [comment]
> > For example, we have a ProximityNitification-Service (which I never used). Wouldn't this require for c:geo to have the user's position even when c:geo is not in the foreground, user uses other apps or phone is in off-mode? How does this feature work currently?
> 
> @moving-bits can you add some insights? As far as I understood these notifications will only work while using the Livemap. But I haven't used the feature myself...

As with speech service (at least back then), it only works as long as the screen is turned on and c:geo in foreground mode (and a short time after that) - I've never tried to change this into a `ForegroundService`, but it certainly would be very useful to have it available even when the screen is turned off and/or other apps are in the foreground.
