### ISSUE TITLE
Visualize which filters only work offline

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13799]
> > Maybe these limited filter options should be marked somehow in the filter dialogue, or not even offered in the live map
> 
> This was discussed before and might be a good idea. However, there are some special cases to consider, and I haven't seen a concept yet which includes handling such cases. Examples:
> * A live map view typically shows both stored caches and live caches in a mixed way. Forbidding certain filters for live map would then also forbid them in cases where all shown caches are stored caches, and that would be an unnecessary restriction
> * Some filters work for some connectors and not for others, e.g. filtering by favorite percentage works for oc but not for GC.com. how to handle this?
> * Some filters work for GC.com in live mode but just for premium members e.g. attribute filters. Should those be forbidden or allowed?
> * Some filters work partially in live mode, e.g. "not found by" works with GC.com but "found by" does not. How to handle this?
> * Filters can be stored by name and then reused in other filters. Should we forbid to use named filters created in "offline mode" for usage in "live mode"? 
> 
> All in all I don't current know a good and easy concept to handle all these cases in a smooth and straight-understandable way. Some sort of filter labeling might be a good idea, but I am currently missing the overall concept.

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/13105#issuecomment-1149967019_

**Comment by murggel** [comment]
duplicate issue #14577

Suggested solution: online connector support table into handbook

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/14577#issuecomment-1712928194_

**Comment by moving-bits** [comment]
Closed as duplicate
