### ISSUE TITLE
Make membership state more transparent

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13796]
### Tell us your idea!

We had a user on support mail, who was missing the pocket query menus in c:geo.
It turned out, that c:geo failed to recognize him as premium member. This might occur on login failure (e.g. missing network coverage) or directly after obtaining a premium membership but before next login with c:geo.

While the fix (= restart c:geo or relogin) is easy, the user made a proposal for a potential improvement in such situation:

### What solution would you suggest?

User suggested:
If a basic member tries to use the pocket queries function, you should generate a message that says "premium members only feature".  Also, you should display the membership level on the login (home) screen.

### Additional Information

Support ticket 289067

**Comment by fm-sys** [comment]
> If a basic member tries to use the pocket queries function, you should generate a message that says "premium members only feature". 

Currently we hide PM only feature totally to do not advertise those. This can be discussed of course...

**Comment by Lineflyer** [comment]
IMHO this is sufficiently solved by showing the membership state on the home screen.
