### ISSUE TITLE
Support Display of GeoJson data

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#13793]
Sometimes I have caches where it would be helpful to draw geometric forms on the map (lines, polygons, circles). An example for such a cache is the Heinzel Challenge around Munich (https://coord.info/GC2YYGC)

My proposal for this is to support the import and display of geojson files. 
* GeoJson is described here: https://geojson.org/
* An online GeoJson editor can be found e.g. here: https://geojson.io 
* I would also include support for basic formatting e.g. color, line width

I am not sure, but probably mapsforge and/or VTM already support GeoJson anyway?

GUI-wise I propose something like the integration of individual route files, although there should be the possibility to import multiple GeoJson files and turn their display on and off.

**Comment by devemux86** [comment]
> I am not sure, but probably mapsforge and/or VTM already support GeoJson anyway?

Mapsforge / VTM can render marker / line / polygon overlays regardless of origin.
(VTM is more advanced with JTS geometries)

You probably need a GeoJSON reader, see:
https://github.com/cocoahero/android-geojson

(included in previous Cruiser with Mapsforge + VTM)

**Comment by Lineflyer** [comment]
Do you really thing such complex (and probably rare used) feature is something we should include in c:geo? Sounds a bit like its more for a professional mapping tools rather than for a Geocaching app. 
If its however integrated in the UI in a way, that does not increase complexity I am fine with it (e.g. the exiting route import button just also supports these files).

**Comment by eddiemuc** [comment]
> Do you really thing such complex (and probably rare used) feature is something we should include in c:geo?

I agree this can be argued. One additional (yet also arguable) reason to add this is as a prerequisite to integrate whereyougo into c:geo. If this is ever done we need support at least to draw polygons.

**Comment by eddiemuc** [comment]
Update: GUI-wise I suggest to integrate this 1:1 into the "load route/track from GPX" functionality. This feature already allows to load/display multiple routes (which are technically displayed as polylines). Basically we just need to allow also to select geojson files there (and of course there's no routing applied to points in the geojson files)

**Comment by eddiemuc** [comment]
@moving-bits while trying to extend geojson to google I noticed that current google implementation is very very slow performance-wise. I have the impression that in current implementation EVERY object on google map (routes, tracks, position, history; not the cache markers though) is first removed and then redrawn several times on every coordinate update. This leads to large redrawing lacks when having a bit more objects on the map (like i have with geojson).

Is this known? I have the feeling I have to completely rewrite the redraw and caching mechanisms for google maps if geojson should be seriously usable

**Comment by moving-bits** [comment]
Don't know in detail, but after adding some logging I have to agree: GM redraws everything (position, history, routes/tracks) every ~0.5 - 2 seconds.

Just cross-checked our VTM implementation with some logging: it repaints position and history regularly as well, but not routes/tracks.

**Comment by fm-sys** [comment]
@eddiemuc was this fully implemented already?

**Comment by eddiemuc** [comment]
Yes, can be closed

**Comment by murggel** [comment]
Asked on c:geo-booth at Event [Tanz auf den Vulkanen](https://coord.info/GCATPRH) for a short introduction / breaf instruction for handling with GeoJson.
Seems to be a nice feature, but a little complicated for the average user
https://github.com/cgeo/cgeo-guide/issues/72

**Comment by ztNFny** [comment]
The challenge is providing a source for geojsons. This would have to be a service outside of c:geo - we could ask project-gc whether they'd want to do it. Anyone have some contact to them?

**Comment by murggel** [comment]
I guess it would be sufficient for the first step, to have a list of possible sources for the user, he can look at or a guide how to create them by themselves. 
Mainly was asked for the "Landkreise"...

**Comment by ztNFny** [comment]
https://opendatalab.de/projects/geojson-utilities/
https://github.com/ztNFny/geocaching_geojson_generator

**Comment by moving-bits** [comment]
Personally I'm using the opendatalab.de site from time to time and find it quite useful.

But: This provides data for Germany only, so for many users it's not what they would be looking for.

Does anyone know of a site providing free world-wide data?
