### ISSUE TITLE
Trackable gallery still using old+new version

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13805]
### Describe your problem!

While testing other things in emulator running current `master` I stumbled upon doubled gallery tabs (old + new) still being active for trackables.
Shouldn't this be only the new one meanwhile like for caches?

### How to reproduce?

- Open trackable containing images (e.g. TB59M9P)
- Swipe to gallery
-

### Actual result after these steps?

![image](https://user-images.githubusercontent.com/949669/210133520-0be3ade1-4676-408d-9a62-02e8106add9b.png)

![image](https://user-images.githubusercontent.com/949669/210133539-a184802e-f253-4003-b5f4-94c8d099f17e.png)

### Expected result after these steps?

Only the new gallery to be shown

### Reproducible

Yes

### c:geo Version

master at 30.12.2022

**Comment by eddiemuc** [comment]
People tend to forget that the new gallery is **still** not out in production/beta, and thus I had to keep the old gallery in. This mixed usage would surely have come up (and will come up) when the new gallery was/is out in the wild and the old gallery code was/is removed. So no biggie.
