### ISSUE TITLE
Add c:geo svg logo in the repo

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#13808]
### Tell us your idea!

#11816 introduced the new cgeo icon as high-resolution png file but the original svg file is not present in the repo - or I didn't found it…

### What solution would you suggest?

Publish the svg version. As I needed it for geokrety/geokrety-website/issues/810 I took https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_send2cgeo.svg and removed the `send2` sub-icon myself.

### Additional Information

I'll push the icon in a PR

**Comment by ztNFny** [comment]
It was already there though?!

https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_background.svg
https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_foreground.svg

PR should be reverted as it doesn't add anything of value

**Comment by ztNFny** [comment]
The "wrong" svg actually is https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_send2cgeo.svg as that's the only one (but the new also-wrong ic_launcher.svg added by this PR) that has the background in the svg.

Background is provided by [ic_launcher_background.svg](https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_background.svg) and should NOT be duplicated by other resources.

**Comment by kumy** [comment]
oh sorry, feel free to revert :man_shrugging: 

@ztNFny on GeoKrety side, what do you expect as icon regarding this [issue](https://github.com/geokrety/geokrety-website/issues/810)? Am I supposed to use only the [ic_launcher_foreground.svg](https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_foreground.svg) or should I superpose the two while rendering (is there some code example please)?

**Comment by ztNFny** [comment]
> @ztNFny on GeoKrety side, what do you expect as icon regarding this [issue](https://github.com/geokrety/geokrety-website/issues/810)? Am I supposed to use only the [ic_launcher_foreground.svg](https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_foreground.svg) or should I superpose the two while rendering (is there some code example please)?

The current one is fine in terms of what it shows. But I wouldn't use THAT SVG - it's the source used for creation and contains a lot of information not required for just displaying it.

Original SVG: 25kb
Optimized SVG: 9kb
PNG 24x24px: 1kb
