### ISSUE TITLE
Change in coordination calculation

### ISSUE THREAD

**Issue by andrcoding** [cgeo/cgeo#13815]
### Tell us your idea!

If I have an coordination for N like 50° 50.134 and want to add a variable A=4000 I usually write 50° 50.(134+A) which result in a cooridnate which is not valid. Thus I change it to 50° 54.(134+A-4000). Maybe I use a wrong formulation but otherwise it would be great if this over or underflow calculation would be done by cgeo directly

PS: Personally, I find it more helpful if the calculated value of variables will be displayed as well to check values. At the moment I have always to close the waypoint creation modus and taking a view at the variable view. 

### What solution would you suggest?

Change internal calculation so that 50° 50.(134+A) results in 50° 54.134

**Comment by ztNFny** [comment]
if you formula is like that it's more likely that the A=4000 is wrong (e.g. could be A=400) and the current implementation helps you notice that error. Usually - there's no 100% correct implementation for all cases out there as every owner does what he thinks - if the variable overflows that's explicitly stated or a proper formula like N50°5(134+A)/1000 is used in the listing.

**Comment by andrcoding** [comment]
That is true that everybody has different workflows. My basis is always that I have a correct input and want that input in a most efficient way. Here in my area almos 60-70% of simple multis have values over 1000 for which you have always to fix the coordination. Finding wrong variable values I do atm at the variable view. In case, I would think that variables values over 1000 are incorrect, I can easily identify them here. Thus, imho the current formulation is not really helping to find implementation errors. However, you are one of the developer and it is of course you who have to decide what is best for all users.

PS: Is N50°5(134+A)/1000 working? I will try it out later. In this case I will use this formulation in future. Thanks

**Comment by eddiemuc** [comment]
> PS: Is N50°5(134+A)/1000 working? I will try it out later. In this case I will use this formulation in future. Thanks

It should work. If not, I would consider it a bug. Because this was meant exactly for the case you describe.

**Comment by andrcoding** [comment]
Yes, that is working. Still some adaption required but a good compromis
