### ISSUE TITLE
Change variable value at specific waypoint view

### ISSUE THREAD

**Issue by andrcoding** [cgeo/cgeo#13814]
### Tell us your idea!

At my last multis I have had the feeling that the UI could be improved a bit. Usually I open an specific waypoint and answer the question for the waypoint or calculate new coordinates. Afterward, I close the waypoint and open the cache and go the variable view. Here I add a new variable value and close the cache to come back to the map.

My idea is that I can make easy variable changes directly in the waypoint view.

Variable view: You have probably carefully the functions. Otherwise, I would add an option which sums up all variable values

### What solution would you suggest?

My idea is that in the waypoint view there is a dropdown menu to select one variable out of my predefined variable. In an editable textfield (like in the variable view), I can then directly add a new variable value (maybe including the existing function options)

**Comment by eddiemuc** [comment]
I am unsure whether I understand the issue correctly. You can edit variables directly in the calculated coordinate Dialog. As soon as you enter a new variable in either lat or lon field, it will immediately become available for edit. Isn't this what you ask for?

**Comment by bekuno** [comment]
@andrcoding You can write the answer in the waypoint "User note" field (e.g. A=1).
After that sync the personal note waypoint info (left symbol).
Then the text A=1 in the Personal note field and this is automatic used in the variables page and the calculated waypoint.

**Comment by eddiemuc** [comment]
> @andrcoding You can write the answer in the waypoint "User note" field (e.g. A=1). After that sync the personal note waypoint info (left symbol). Then the text A=1 in the Personal note field and this is automatic used in the variables page and the calculated waypoint.

That's also possible (and my personal preference :-))...

**Comment by eddiemuc** [comment]
> I am unsure whether I understand the issue correctly. You can edit variables directly in the calculated coordinate Dialog. As soon as you enter a new variable in either lat or lon field, it will immediately become available for edit. Isn't this what you ask for?

..but what I meant was this: 

![image](https://user-images.githubusercontent.com/6909759/210545122-d5420667-ba66-47a4-b466-8f2d3635a64c.png)

**Comment by eddiemuc** [comment]
> I am unsure whether I understand the issue correctly. You can edit variables directly in the calculated coordinate Dialog. As soon as you enter a new variable in either lat or lon field, it will immediately become available for edit. Isn't this what you ask for?

..but what I meant was this: 

![image](https://user-images.githubusercontent.com/6909759/210545122-d5420667-ba66-47a4-b466-8f2d3635a64c.png)

**Comment by andrcoding** [comment]
> @andrcoding You can write the answer in the waypoint "User note" field (e.g. A=1). After that sync the personal note waypoint info (left symbol). Then the text A=1 in the Personal note field and this is automatic used in the variables page and the calculated waypoint.

That would be fine but I think this is not working in my case. I usually always write A=1 in my notes but it is not transfered to the variable view. That is why I suggested an additional dropdown menu at waypoint view. I will test it again and otherwise come back with an spcific example

**Comment by bekuno** [comment]
> I usually always write A=1 in my notes but it is not transfered to the variable view.

I saw a similar situation only after I initially defined a value in the calculating dialog (see https://github.com/cgeo/cgeo/issues/13814#issuecomment-1370804749) and deleted them afterward.

**Comment by andrcoding** [comment]
I have tested it but the note A=1 is not transferred to the variable view. In case, I have to do it in a different way, help is welcome.

Thus, for an better understanding my suggestion for a waypoint view with a dropdown list for specified variables

![image](https://user-images.githubusercontent.com/78544594/210777756-181448fb-c074-4dc8-8a7d-3c4521e639c5.png)

**Comment by eddiemuc** [comment]
> I have tested it but the note A=1 is not transferred to the variable view. In case, I have to do it in a different way, help is welcome.

You have to use the cache notes, not the waypoint notes

**Comment by andrcoding** [comment]
Ok, but then it is not helpful. If I go on a multi, I start with the map. Here, I find the different waypoitnts which I open for questions or adding some notes. From here I cannot access the cache directly. Therefore, my suggestion would be helpful. Another option would be in my opinion to have the opportunity to swipe left to the variable view (which is not possible at the moment).

At least that is my workflow. However, I am happy to hear how do you do it and if I can improve my workflow through this.

**Comment by andrcoding** [comment]
What exactly do you mean by "left symbol" or the sync the personal note waypoint info? I stand on the hose, sorry.

**Comment by bekuno** [comment]
See https://manual.cgeo.org/en/cachedetails#personal_note, the "Copy waypoints" symbol.

**Comment by andrcoding** [comment]
Sorry, but I do not get it.
Starting at the map:
1. I open one waypoint and add a personal note like A=1
2. I have to go back to map as there is no other option (?)
3. I open the cache and go to the detail view (instead I can directly open the variable view what I do at the moment)
4. I click on the sync button of the cache personal notes
5. No sync happens as in front of the waypint the " prevents the correct parsing
![image](https://user-images.githubusercontent.com/78544594/211004214-74ef54a2-ec13-420f-a215-613b38cb116e.png)


My expectation is that I have finished everything when I go back to map (either by dropdown, swipe to variable view or automatic sync) after opening the waypoint in 1. Please correct me.

**Comment by bekuno** [comment]
@Lineflyer @eddiemuc Do we have a documentation for the workflow?

To your workflow:

> * I open one waypoint and add a personal note like A=1

> * I have to go back to map as there is no other option (?)

You can instead open first the cache from the waypoint preview and then switch to the waypoint.
 So you are already in the cache view.
 
> * I open the cache and go to the detail view (instead I can directly open the variable view what I do at the moment)
> 
> * I click on the sync button of the cache personal notes
> 
> * No sync happens as in front of the variable the " prevents the correct parsing

In your sample you probaly have already synced.
You see the result in the block starting with {c:geo-start}.

But - where you expect the result?
Easiest war is to scan the listing for formulas. 
Or you can create a waypoint with "calculate coordinate" in the coodinates field.

**Comment by eddiemuc** [comment]
> @Lineflyer @eddiemuc Do we have a documentation for the workflow?

There is no documented workflow, at least not from my side. I tried to recreate the same options which existed before with the "old" waypoint-specific variables. My personal workflow always goes through cache notes because I also want to "save" all calculations on server side in User note.

I think it is a valid request to also parse waypoint notes for variables though.

**Comment by andrcoding** [comment]
> But - where you expect the result? Easiest war is to scan the listing for formulas. Or you can create a waypoint with "calculate coordinate" in the coodinates field.

I expect at the end a defined variable so that I can use this variable for the calculation for other/final waypoints. Scanning the listing is for this type of caches not possible/required. Further, my point is not definig formulas, it is more about defining the variables.

Of course, I can open the cache directly, however, if it is a long cache with a lot of waypoints/variables it is much easier/faster to open the waypoint directly (Out of topic: I find it a bit annoying if I open the cache directly and it is starting in the variable view, I have always to scroll down in long variable list as it is not remembering my scroll position and starting always at the beginning).

> There is no documented workflow, at least not from my side. I tried to recreate the same options which existed before with the "old" waypoint-specific variables. My personal workflow always goes through cache notes because I also want to "save" all calculations on server side in User note.

I do not expect a documented workflow. I just wanted to know how I can improve my workflow as obviously none of you is following my workflow. Rethinking all your comments, imho the best option is if it is possible to swipe to the variable view after opening a specific waypoint (which is not possible so far) and after finishing the cache once it can be synced with the caches personal note for all notes/server sync. What do you think?

**Comment by Lineflyer** [comment]
I briefly scanned the thread and the question left for me is, why the author does not use the variable view instead of entering the variable into the waypoint note?
Maybe I overlooked the reasoning/use case for that.

**Comment by andrcoding** [comment]
That is exactly what I do/want to do. 

I try to explain it again: At the map with all the caches and waypoints, if I open a waypoint directly, I cannot access the variable view directly what I like to do. In this view I have only the option to add notes/edit waypoint or going back to map which I do so far with opening the cache details and adding the variable in variable view. As an alternative I can open the cache opening at last position (e.g. variable view) then opening the waypoint writing some note to solve/find the waypoint and then going back to the variable view to note the solution. Finally, I can go back to the map. As the map allows the direct access to open the waypoint, I can save a couple of clicks in my workflow if I can swipe to the variable view directly, extra button to open variable view or have direct access by dropdown menu at the waypoint view.
The presented workflows so far seem to be quite different not addressing my usage and require a couple of more operations compared to my suggestion. 

Remark: 
- I am in general map modus not limited to the cache specific view. Here at the cache specific view, I could work from the waypoint list view and everything is fine.
- I cannot use only the variable view as I like to write down additional notes about the specific waypoint

**Comment by ztNFny** [comment]
Workaround: on a multi always set the next stage as corrected coordinates, then you can easily access the cache there (and also get to easily use other features that only work with caches bit not waypoints, e.g. live map)

**Comment by andrcoding** [comment]
I think this workaround is not required as you can always open the cache from the waypoint directly. 
I can live with the current situation but it is not as efficient as it could be.

**Comment by murggel** [comment]
I think, in the meantime variables are created from waypoint notes (#13867)
@andrcoding can you please check, if the issue can be closed with that PR?

**Comment by andrcoding** [comment]
I have checked the current version but the creation of variables out of my waypoint notes is not working. However, I can work with the current GUI as well. 1-2 more actions are required but that is nothing what kills me.
