### ISSUE TITLE
Granting storage permission for wallpaper not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13826]
### Describe your problem!

After #13816 was fixed by https://github.com/cgeo/cgeo/pull/13817 I tried a fresh nigthly build on my device, which was previously crashing.

Now c:geo starts again and immediately the c:geo internal storage dialog comes up. Clicking on "ask again" does nothing, "Open app info" shows, that no storage permission is in the list at all.

@eddiemuc Did you maybe forgot to add it to the manifest?

### How to reproduce?

See video:

https://user-images.githubusercontent.com/949669/210852724-5f5bd2fa-f22c-4935-8be4-70f3a1f75763.mp4

### Reproducible

Yes

### c:geo Version

2023.01.05-NB1

**Comment by eddiemuc** [comment]
> @eddiemuc Did you maybe forgot to add it to the manifest?

True, I forgot this. Strange, because it worked in my emulators.

**Comment by Lineflyer** [comment]
Will you, or shall I add it again?

**Comment by Lineflyer** [comment]
I am on it now. Assigning.

**Comment by Lineflyer** [comment]
Solved with https://github.com/cgeo/cgeo/pull/13827

**Comment by eddiemuc** [comment]
> I am on it now. Assigning.

Sorry, I was unavailable tonight. Thanks for solving!
