### ISSUE TITLE
WIG: allow multiple cartridge links to the same cartridge

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13822]
### Tell us your idea!

Currently the cartridge detection is than fine, if only one entry is in the text.
But if multiple entries are found, than this is an error.

### What solution would you suggest?

Detect, that it is the same cartridge.

**Comment by ztNFny** [comment]
Looking at the code it should work if there are multiple links pointing to the same cartridge. It will however fails for multiple links to different cartridges.

Do you have an example?

**Comment by bekuno** [comment]
It was a FB entry.
Now the user owner changed the descriptions.
Only one cache is now unchanged:
![grafik](https://user-images.githubusercontent.com/32555742/210611114-43c82880-a95f-44d0-a357-489c7042eaee.png)

User-Kommentar zu der Situation:
`Das wäre natürlich der Gag ... weil mir vom Reviewer vorgeschrieben wurde, dass ich beide URLs ins Listing schreiben MUSS: die zum WIG selbst und die zum Download ... ursprünglich hatte ich nur die zum Download drin - so ist der nicht gepublished worden ...`

Btw., the code part to detect the WIG adresses is called 3 times before showing the cache.

**Comment by bekuno** [comment]
Probally we should save/check the WIG CGUID instead of the complete URL.
