### ISSUE TITLE
remember scroll position for waypoints view 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13834]
### Tell us your idea!

In long Waypoint view (e.g. for ALC with big WP descriptions) it should remember the last position when opening a WP detail view and then come back.
Currently it starts on top of this view and you have to scroll down to the position.

### What solution would you suggest?

Save the scroll position and set them when returning.

**Comment by eddiemuc** [comment]
Opening the waypoint details starts a new activity. To remember scroll position we would have to persist it in database per waypoint, then restore it on opening. Really worth it?

**Comment by fm-sys** [comment]
Actually the position is restored in the WP list as long as the activity was not destroyed since  #13617.

**Comment by bekuno** [comment]
> Actually the position is restored in the WP list as long as the activity was not destroyed since #13617.

This should be in the current release "in the wild", isn´t it?
The it does not work.

**Comment by bekuno** [comment]
> Opening the waypoint details starts a new activity. To remember scroll position we would have to persist it in database per waypoint, then restore it on opening. Really worth it?

Why per waypoint? You start from the cache waypoint view.

**Comment by eddiemuc** [comment]
> > Opening the waypoint details starts a new activity. To remember scroll position we would have to persist it in database per waypoint, then restore it on opening. Really worth it?
> 
> Why per waypoint? You start from the cache waypoint view. 

Sorry, I thought you meant remembering the scrolling position inside waypoint **details** view. Now I see you mean the position in waypoint **list** view. Correct?

**Comment by Lineflyer** [comment]
The view position of the waypoint list should already been kept since quite a while. Just tried with current nightly and it works as you desire.

**Comment by bekuno** [comment]
Checked with nightly, all is ok.
