### ISSUE TITLE
formula parser - result not as waypoint visible (initial)

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13830]
### Describe your problem!

If you use the menu point "Scan for waypoint formulas", then the result is not imedially visible as waypoint.

### How to reproduce?

1. Open cache with waypoint formula (maybe GCW5ZK)
2. call the menu point Waypoint -> "Scan for waypoint formulas".
3. Select (at least) the found waypoint with formula and save (ok)
4. Swipe to the Waypoints view.

### Actual result after these steps?

No created waypoint with formula visible.

You have to close and reopen the cache to see the result.

### Expected result after these steps?

The created waypoint(s) should be imedially visible in the Waypoints view.

### Reproducible

Yes

### c:geo Version

2022.12.21

**Comment by ztNFny** [comment]
Same as https://github.com/cgeo/cgeo/issues/13751 ?

**Comment by bekuno** [comment]
> Same as #13751 ?

correct
