### ISSUE TITLE
Error when adding cache to bookmark list

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#13837]
### Describe your problem!

I get an error message when trying to add caches to bookmark lists.

![2023-01-07 23 20 16](https://user-images.githubusercontent.com/54892606/211172403-ecae6f92-87f5-4510-a736-f68be95205a6.png)

### How to reproduce?

See above.

### Reproducible

Yes

### c:geo Version

2022.12.21

**Comment by ztNFny** [comment]
Dup of #13759
