### ISSUE TITLE
Parsing formulas without respecting spaces

### ISSUE THREAD

**Issue by andrcoding** [cgeo/cgeo#13843]
### Tell us your idea!

If the formula input contains a space after a variable and before a bracket ")" it is not working. In case this has no special reason, it would be nice if spaces are ignored:
![image](https://user-images.githubusercontent.com/78544594/211195151-2682b5de-5d32-459f-983b-86b02d798123.png)

### What solution would you suggest?

Ignore spaces in formulas

**Comment by eddiemuc** [comment]
This is a bug, I can reproduce it too. Must be fixed. Thanks for reporting

**Comment by ztNFny** [comment]
Isn't that the reason "remove spaces"exists in the formula dialog?

**Comment by eddiemuc** [comment]
> Isn't that the reason "remove spaces"exists in the formula dialog?

Not for this case, whitespacea before closing parenthesis are unambiguous
