### ISSUE TITLE
Google Streetview app to be discontinued?

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13855]
A user on support informed us about a message from his street view app about retiring the service at March 2nd, 2023.

Check whether this just means street view app does not get any updates any longer, or whether they actually close the whole infrastructure for it (in which case we can remove our street view support).

**Comment by SammysHP** [comment]
The Street View app will be discontinued. Street View is already integrated in the Maps app and will continue to be available there. That's what I heard about this topic.

**Comment by moving-bits** [comment]
No problem reports about this on support yet, so let's close here.
