### ISSUE TITLE
Jump to another cache inside c:geo when clicking on cache links

### ISSUE THREAD

**Issue by HankChow** [cgeo/cgeo#13857]
### Tell us your idea!

It's possible that a cache is mentioned in the description of other caches via hyperlinks. When clicking on these hyperlinks, I will open the cache page in the browser. It's much better to jump to the cache just inside c:geo when clicking on hyperlinks such as "https://coord.info/GCXXXXXX" and "https://www.geocaching.com/geocache/GCXXXXXX", without switching to the browser.

### Additional Information

Version: 2022.12.21

**Comment by SammysHP** [comment]
It already works as expected on my device. Probably your browser is set as a default app for geocaching URLs. Someone else will probably tell you how you can change it on your device.

**Comment by moving-bits** [comment]
See https://www.cgeo.org/faq#android12
