### ISSUE TITLE
OpenAndroMaps theme: Voluntary/Velocity

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13866]
### Tell us your idea!

I propose to include the Voluntary/Velocity themes for OpenAndroMaps in c:geos OAM downloader, in addition to Elevate.

Public site: https://voluntary.nichesite.org
Direct download URL for theme: https://ftp.gwdg.de/pub/misc/openstreetmap/openandromaps/themes/voluntary/downloads/Voluntary%20MF5.zip

Author permission: https://www.openandromaps.org/en/oam-forums/topic/voluntary-uk/page/11#post-52313

**Comment by ztNFny** [comment]
I've starting looking at this but the Map Theme downloaders area all a bunch of special-case this and special-case that, not sure how to proceed here.

Elevate is available from the same location, maybe that could be joined? https://ftp.gwdg.de/pub/misc/openstreetmap/openandromaps/themes/elevate/

@moving-bits The existing Elevate downloader class is yours. Any shots?

Partial (broken) implementation in https://github.com/ztNFny/cgeo/tree/issue/13866_voluntaryMapsTheme

**Comment by moving-bits** [comment]
I'll try to look into it. If the downloadable file comes from the same server as Elevate, it should be possible to download it. Not sure about update detection, though, as this is probably done using a different site (or not available at all?)

**Comment by ztNFny** [comment]
Update detection is hacky for both, i implemented it more or less the same as for elevate.
Only "problem" right now is that "page" is populated once but would have to be fetched twice, that's why the code doesn't work. But fixing that would result in very ugly - imho - code.... But i simply don't have the time for understanding that stuff good enough to do a full rewrite anytime soon, between work and stuff. 😟
