### ISSUE TITLE
crash when recalculating route

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13863]
### Describe your problem!

On one Test-AVD I got this crash when changing routing parameter:
~~~
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void cgeo.geocaching.models.Route.calculateNavigationRoute()' on a null object reference
W/System.err:     at cgeo.geocaching.maps.CGeoMap.lambda$routingModeChanged$7$cgeo-geocaching-maps-CGeoMap(CGeoMap.java:834)
W/System.err:     at cgeo.geocaching.maps.CGeoMap$$ExternalSyntheticLambda3.call(Unknown Source:6)
W/System.err:     at cgeo.geocaching.maps.Tracks.traverse(Tracks.java:74)
W/System.err:     at cgeo.geocaching.maps.CGeoMap.lambda$routingModeChanged$8$cgeo-geocaching-maps-CGeoMap(CGeoMap.java:833)
W/System.err:     at cgeo.geocaching.maps.CGeoMap$$ExternalSyntheticLambda10.run(Unknown Source:4)
W/System.err:     at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:91)
W/System.err:     at cgeo.geocaching.utils.AndroidRxUtils$$ExternalSyntheticLambda0.run(Unknown Source:4)
W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
W/cgeo: [RxComputationThreadPool-1] UncaughtException
    java.lang.NullPointerException: Attempt to invoke virtual method 'void cgeo.geocaching.models.Route.calculateNavigationRoute()' on a null object reference
        at cgeo.geocaching.maps.CGeoMap.lambda$routingModeChanged$7$cgeo-geocaching-maps-CGeoMap(CGeoMap.java:834)
        at cgeo.geocaching.maps.CGeoMap$$ExternalSyntheticLambda3.call(Unknown Source:6)
        at cgeo.geocaching.maps.Tracks.traverse(Tracks.java:74)
        at cgeo.geocaching.maps.CGeoMap.lambda$routingModeChanged$8$cgeo-geocaching-maps-CGeoMap(CGeoMap.java:833)
        at cgeo.geocaching.maps.CGeoMap$$ExternalSyntheticLambda10.run(Unknown Source:4)
        at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:91)
        at cgeo.geocaching.utils.AndroidRxUtils$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-1
    Process: cgeo.geocaching, PID: 8624
    java.lang.NullPointerException: Attempt to invoke virtual method 'void cgeo.geocaching.models.Route.calculateNavigationRoute()' on a null object reference
        at cgeo.geocaching.maps.CGeoMap.lambda$routingModeChanged$7$cgeo-geocaching-maps-CGeoMap(CGeoMap.java:834)
        at cgeo.geocaching.maps.CGeoMap$$ExternalSyntheticLambda3.call(Unknown Source:6)
        at cgeo.geocaching.maps.Tracks.traverse(Tracks.java:74)
        at cgeo.geocaching.maps.CGeoMap.lambda$routingModeChanged$8$cgeo-geocaching-maps-CGeoMap(CGeoMap.java:833)
        at cgeo.geocaching.maps.CGeoMap$$ExternalSyntheticLambda10.run(Unknown Source:4)
        at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:91)
        at cgeo.geocaching.utils.AndroidRxUtils$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
~~~

### How to reproduce?

I had before tested some routing things, but in this situation the routing symbol was not active.
In the log is to read:
`W/cgeo: [RxCachedThreadScheduler-1] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching/trackfiles/track-2023-01-13-18-05-03-3.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.1: could not parse XML`

- Opend "Quick settings"
- Routing: Changed to "no routing"

### Actual result after these steps?

Crash 

### Expected result after these steps?

Catch this problem.

### Reproducible

Unclear

### c:geo Version

dev build from current master

## System information

c:geo version: 2023.01.09-bd2ff23 developer build

Device:
-------
- Device type: sdk_gphone_x86_64_arm64 (sdk_gphone_x86_64_arm64, google)
- Available processors: 4
- Android version: 11
- Android build: sdk_gphone_x86_64_arm64-userdebug 11 RSR1.210722.013 7800151 dev-keys
- Screen resolution: 1080x2072px (392x750dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 20.18.17 (040800-311416286)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:83
- Set language: en_US (system default)
- System date format: M/d/yy
- Time zone: GMT
- Debug mode active: no
- Last backup: never
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Map
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Cache Type: Adv Lab ([:inconclusive=false:advanced=false]AND(type:ADVLAB;difficulty_terrain:d=-:d=-:t=-:t=-;status))
- OFFLINE: Cache Type: Adv Lab ([:inconclusive=false:advanced=false]AND(type:ADVLAB;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: dd.MM.yy
- Geocaching.com website language: de-DE
- Last successful login on geocaching.com: 2023-01-14 14-01
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions
-------
-android.permission.ACCESS_COARSE_LOCATION:: granted
-android.permission.ACCESS_FINE_LOCATION:: granted
-android.permission.READ_CONTACTS:: DENIED
-android.permission.READ_EXTERNAL_STORAGE:: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (5.1 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (5.1 GB free) v3 internal isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (5.1 GB free) v3 external non-removable isDir(429 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (5.1 GB free) v3 internal isDir(0 entries)
- Public Folders: #12
  - BASE: /Cgeo (User-Defined)[/Cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo, Av:true, files:>=0, dirs:>=9, totalFileSize:>=0 B, free space: 5.1 GB, files on device: 393216)
  - OFFLINE_MAPS: /Cgeo/maps (Default)[/Cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fmaps, Av:true, files:0, dirs:2, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - OFFLINE_MAP_THEMES: /Cgeo/maps/_themes (Default)[/Cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - OFFLINE_MAP_SHADING: /Cgeo/maps/_hgt (Default)[/Cgeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - LOGFILES: /Cgeo/logfiles (Default)[/Cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - GPX: /Cgeo/gpx (Default)[/Cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - BACKUP: /Cgeo/backup (Default)[/Cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - FIELD_NOTES: /Cgeo/field-notes (Default)[/Cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - SPOILER_IMAGES: /Cgeo/GeocachePhotos (Default)[/Cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - ROUTING_BASE: /Cgeo/routing (Default)[/Cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81.7 KB, free space: 5.1 GB, files on device: 393216)
  - ROUTING_TILES: /Cgeo/routing/segments4 (Default)[/Cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: 393216)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 5.1 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3ACgeo (Jan 5, 5:37 PM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:11.1 MB) on system internal storage

--- End of system information ---

**Comment by moving-bits** [comment]
This is strange, not sure how this can happen:

```
834      AndroidRxUtils.andThenOnUi(Schedulers.computation(), () -> tracks.traverse((key, route) -> {
835          if (route instanceof Route) {
836              ((Route) route).calculateNavigationRoute();
837          }
838          ((GooglePositionAndHistory) overlayPositionAndScale).updateRoute(key, route);
839      }), () -> ...));
```

The offending call is in line 836, route seems to have a `null` value then. But the surrounding `route instanceof Route` should prevent a `null` value inside the `if` statement. Or has this changed meanwhile?

**Comment by eddiemuc** [comment]
I believe (but have to verify in code) that the surrounding `instanceof Route` check was introduced by myself recently as part of supporting geojson. If yes then maybe this was an unintended "side-fix" for this issue too?

**Comment by moving-bits** [comment]
May very well be (git commit 433ec4e878c69d1332ad1012baa34373e6dd6ce3). I like it when you side-fix things :-)

@bekuno: Can you cross-check on your system?

**Comment by bekuno** [comment]
Checked and compared with the error -> (CGeoMap.java:834) - I used the older cade base.
Thanks for the implicit fix.
