### ISSUE TITLE
Missing the ability to insert a horizontal line in logs for GC.com

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#13870]
### Tell us your idea!

On GC.com it is possible to insert a horizontal line in a log using a button or typing "----------" (in the old log form; not sure how it works in the new log form, I don't use that one).

I use this feature a lot and it would be great if there were an easy way to do the same from within c:geo.

### What solution would you suggest?

Maybe "horizontal line" could be added the insert menu.

**Comment by Lineflyer** [comment]
The log text in c:geo as on geocaching.com can be formatted using [markdown syntax](https://www.geocaching.com/guide/markdown.aspx). A horizontal line can be achieved by `---`.

IMHO nothing which really requires a template.

**Comment by dcjkfgdjhd** [comment]
Ah, I had no idea this works inside c:geo. Thanks a lot!
