### ISSUE TITLE
Mapsforge Downloader test failing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13889]
Just seen on CI:

<html>
<body>
<p style="box-sizing: border-box; font-family: Helvetica, Arial, sans-serif; font-size: 13px; line-height: 1.4em; -webkit-font-smoothing: antialiased; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; font-weight: bold;">cgeo.geocaching.downloader.DownloaderTest.testMapsforge</span><span> </span>(from cgeo.geocaching.CgeoApplicationTest)</p><div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: right;">Schlägt fehl seit 1 Build (Seit<span> </span><a href="https://ci.cgeo.org/job/cgeo-CI_PR-build/3958/" class="model-link" style="box-sizing: border-box; text-decoration: underline; color: rgb(32, 74, 135);"><img src="https://ci.cgeo.org/static/59e45b14/images/16x16/red.png" alt="Fehlgeschlagen" class="icon-red icon-sm" style="box-sizing: border-box; vertical-align: middle; border: 0px; width: 16px; height: 16px;">#3958</a><span> </span>)</div><div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: right;"><a href="https://ci.cgeo.org/job/cgeo-CI_PR-build/3958/testReport/junit/cgeo.geocaching.downloader/DownloaderTest/testMapsforge/history" style="box-sizing: border-box; text-decoration: underline; color: rgb(32, 74, 135);">Dauer: 0.25 Sekunden.</a></div><div id="description" style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box;"></div></div>
<h3 style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Stacktrace</h3><pre style="box-sizing: border-box; white-space: pre-wrap; overflow-wrap: break-word; margin: 0px; color: rgb(51, 51, 51); font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">java.lang.AssertionError:
Expecting:
&lt;297&gt;
to be between:
[200, 250]
at cgeo.geocaching.downloader.DownloaderTest.testMapsforge(DownloaderTest.java:70)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)</pre>
</body>
</html>cgeo.geocaching.downloader.DownloaderTest.testMapsforge (from cgeo.geocaching.CgeoApplicationTest)

Schlägt fehl seit 1 Build (Seit Fehlgeschlagen[#3958](https://ci.cgeo.org/job/cgeo-CI_PR-build/3958/) )
[Dauer: 0.25 Sekunden.](https://ci.cgeo.org/job/cgeo-CI_PR-build/3958/testReport/junit/cgeo.geocaching.downloader/DownloaderTest/testMapsforge/history)
Stacktrace
java.lang.AssertionError:
Expecting:
<297>
to be between:
[200, 250]
at cgeo.geocaching.downloader.DownloaderTest.testMapsforge(DownloaderTest.java:70)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)

**Comment by bekuno** [comment]
The error in PR #13787 described above is at `master`, but PR #13890 was targeted to release.
For the `release` problem see the discussion in issue #13853.
But master was already fixed by PR  #13854.

This all around is strange - was the translation PR #13787 rebased from `master` to `release` to `master`?
Currently it shows `This branch cannot be rebased due to too many changes`.

**Comment by moving-bits** [comment]
Regarding the `DownloaderTest.testMapsforge` for changed Portugal file size:

> But master was already fixed by PR #13854.

Ah, had not remembered this. But this explains why I got a merge error on merging `release` to `master`. I did a manual conflict resolution for this, so it should be fine by now.

Good news is: git recognized the new folder location for `DownloadTest.java` on `master`, otherwise it couldn't have detected the change in the same part of the file.

**Comment by moving-bits** [comment]
> This all around is strange - was the translation PR #13787 rebased from `master` to `release` to `master`? Currently it shows `This branch cannot be rebased due to too many changes`.

Simply close that PR unmerged, and delete the branch `l10n_master`. Crowdin will recreate it with up-to-date data.

**Comment by moving-bits** [comment]
> Simply close that PR unmerged, and delete the branch `l10n_master`. Crowdin will recreate it with up-to-date data.

Done

@bekuno 
Can we close here again, then?

**Comment by bekuno** [comment]
Its fine to close.
