### ISSUE TITLE
Test error in testSearchByGeocodeBasis

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13899]
### Describe your problem!

New error seen on PR test:
~~~
java.lang.AssertionError: [description]
Expecting:
<"<img src="[http://img.geocaching.com/cache/large/1711f8a1-796a-405b-82ba-8685f2e9f024.jpg"](http://img.geocaching.com/cache/large/1711f8a1-796a-405b-82ba-8685f2e9f024.jpg)>">
to start with:
<"<img src="[http://img.geocaching.com/cache/large/1711f8a1-796a-405b-82ba-8685f2e9f024.jpg"](http://img.geocaching.com/cache/large/1711f8a1-796a-405b-82ba-8685f2e9f024.jpg) />">

at cgeo.test.Compare.assertCompareCaches(Compare.java:43)
at cgeo.geocaching.CgeoApplicationTest.testSearchByGeocodeBasis(CgeoApplicationTest.java:289)
~~~
Looks like a change on GC site.

### How to reproduce?

see e.g. https://ci.cgeo.org/job/cgeo-CI_PR-build/3983/testReport/cgeo.geocaching/CgeoApplicationTest/testSearchByGeocodeBasis/

### Reproducible

Yes

### c:geo Version

CI PR-build 3983

**Comment by bekuno** [comment]
The error is only on release.

**Comment by bekuno** [comment]
On master fixed as side change in https://github.com/cgeo/cgeo/commit/b2a586667aeb7d74a8d77dd3bfda7224e5a0a4ad#diff-36aa2685a96c554ad5ef41f80a84eab7b3c7416895135bdf9916c8e4bb5151b5
(@eddiemuc)

**Comment by eddiemuc** [comment]
...and I still vote for not changing anything on release anymore before master is merged there - due to large structure changes.

When will this be done? I am not confident enough in git to do it myself, it would result in a mess

**Comment by Lineflyer** [comment]
IMHO we can do it anytime soon (if development wise everything is settled on master).
I am not sure what happened to the open items we summarized in our last call as I did not here back from @mucek4 
See and comment here: https://github.com/cgeo/cgeo/issues/13772#issuecomment-1374912654

**Comment by bekuno** [comment]
no more relevant, as release was replaced by master
