### ISSUE TITLE
Variables prefilled with word "null"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13908]
Note from field (more details later):

- I created variables A to G for a cache and entered values for some of them, leaving the others empty
- I created a calculated waypoint using those variables
- When coming back later to that cache I noticed in the variable tab, that some (previously empty) variables had the word "null" in it.

**Comment by eddiemuc** [comment]
Fixed by PR #13914

**Comment by Lineflyer** [comment]
cool, thanks for fixing.
