### ISSUE TITLE
Some user defined waypoints not shown on cache map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13907]
Note from field (more details later):

- I created two user defined waypoints of type parking via long click on the cache map 
- After creating the second one I noted, that it was not shown after creating
- Each time leaving and reentering the cache map always only one of the two WP is shown (randomly) but never both

**Comment by Lineflyer** [comment]
I can reproduce it in the following way:
- Store any cache, which has more than 5 waypoints (e.g. GC877NF)
- Open the cache details
- Open map for the cache (tested OSM offline)
- Long tap on the map to create a custom waypoint for this cache, set the type to PARKING (not sure if required to reproduce)
- Store the waypoint
- Repeat the procedure to create a second custom waypoint of type PARKING
- Leave the map view
- Open the map for the cache again

Result:
Only one of the two parking waypoints is shown

Changing the map type to Google:Map shows both waypoints, switching back to OSM:Offline makes one of them disappear

**Comment by moving-bits** [comment]
Duplicate of #14053?

**Comment by Lineflyer** [comment]
For sure.
