### ISSUE TITLE
UnifiedMap: Items not redrawn on map resume

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13910]
### Description

Some map items (esp. geocaches) are not redrawn on resuming map.

Their layers are destroyed on `onPause` and rebuild on `onResume`, but not re-filled.

Re-filling could be done either manually in `onResume` or using a timer like `NewMap` does.

### How to reproduce

Open `UnifiedMap` with some caches on it. Put c:geo into background and resume it.
Map is redrawn, but no caches anymore.
Pausing and resuming can also be achieved by selecting theme options.

**Comment by moving-bits** [comment]
After all the architectural changes lately, let's close here and do a fresh restart with regard to bugs in UnifiedMap.

**Comment by fm-sys** [comment]
Yes, should be fixed (hopefully)
