### ISSUE TITLE
Cruiser navigation

### ISSUE THREAD

**Issue by devemux86** [cgeo/cgeo#13924]
### Tell us your idea!

Hi everyone,

I am the author of [Cruiser](https://github.com/devemux86/cruiser) map and navigation app.

You probably know me as the developer of [Mapsforge](https://github.com/mapsforge/mapsforge) and [VTM](https://github.com/mapsforge/vtm) map libraries.

c:geo can [call other apps](https://github.com/cgeo/cgeo/tree/master/main/src/main/java/cgeo/geocaching/apps/navi) for specific tasks.

Are you interested in integrating calls to the Cruiser app as well?

### What solution would you suggest?

I recently added a routing intent after discussion with WunderLINQ: https://github.com/devemux86/cruiser/discussions/25

I can add intents for navigation and other functions (e.g. GPS recording), if there is interest to call Cruiser app.

Thanks for your time!

**Comment by moving-bits** [comment]
IIRC Cruise can parse geo URI, so calling Cruiser for a specific target should be possible already by selecting "navigate" and "Other external app" or "Other external app (coords only)".

What type of integration do you have in mind? (What type of URL/intent?)

**Comment by devemux86** [comment]
Cruiser currently recognizes:

- [geo URI scheme](https://en.wikipedia.org/wiki/Geo_URI_scheme)
- openstreetmap.org links and osm.org [short links](https://wiki.openstreetmap.org/wiki/Shortlink)
- [Plus codes](https://maps.google.com/pluscodes/)
- [what3words](https://what3words.com/)

Next Cruiser will also recognize:
- OpenStreetMap Directions links
  - 2 coordinates: routing from A to B
  - 1 coordinate: routing from user location

I know that c:geo has map view and internal BRouter routing.
There is the section "Routing / Navigation" in c:geo settings to select navigation tool.

Is there interest to include Cruiser for voice navigation?
Then I can create what you need (extra intent or other).

---

Parsing of links from apps with the "open with" dialog is limited in the latest Android(s).
Many links are automatically captured by their apps or always open in the browser.

Apps (like WunderLINQ) make app specific calls using the package:
```java
intent.setPackage("gr.talent.cruiser");
```

**Comment by devemux86** [comment]
I created intents for map view, routing and navigation.
Please see if they are useful or need changes and I can enable them in the next Cruiser version.

Routing and navigation can get:
- 1 coordinate: route calculation from user location
- 2 or more coordinates: useful for passing user location if already known

**Map view**:
```java
Intent intent = new Intent();
intent.setAction("com.devemux86.MAP_VIEW");
intent.setPackage("gr.talent.cruiser");
intent.putExtra("LATITUDE", 42.514612);
intent.putExtra("LONGITUDE", 1.526773);
intent.putExtra("NAME", "Test");
startActivity(intent);
```

**Routing**:
```java
Intent intent = new Intent();
intent.setAction("com.devemux86.ROUTING");
intent.setPackage("gr.talent.cruiser");
//intent.putExtra("LATITUDE", 42.514612);
//intent.putExtra("LONGITUDE", 1.526773);
//intent.putExtra("NAME", "Test");
intent.putExtra("LATITUDE", new double[]{42.50646, 42.514612});
intent.putExtra("LONGITUDE", new double[]{1.521979, 1.526773});
startActivity(intent);
```

**Navigation**:
```java
Intent intent = new Intent();
intent.setAction("com.devemux86.NAVIGATION");
intent.setPackage("gr.talent.cruiser");
//intent.putExtra("LATITUDE", 42.514612);
//intent.putExtra("LONGITUDE", 1.526773);
//intent.putExtra("NAME", "Test");
intent.putExtra("LATITUDE", new double[]{42.50646, 42.514612});
intent.putExtra("LONGITUDE", new double[]{1.521979, 1.526773});
startActivity(intent);
```

**Comment by moving-bits** [comment]
@devemux86 
Have a look at PR #13952. It implements a rudimentary integration for navigation. I cannot really test it yet, as Cruiser app installed from Play Store does not support the new intent yet. Maybe you can point me to a dev build of Cruiser which I could test against in Android Emulator (or use the c:geo apk from the PR to test it in your environment).

**Comment by devemux86** [comment]
Thanks for the pull request, I will check it!

Cruiser has an active "Open testing" with this [join link](https://play.google.com/apps/testing/gr.talent.cruiser).
Or better contact me on the [Google Play](https://play.google.com/store/apps/details?id=gr.talent.cruiser) email to send you apk for testing?

Can you use the intent with the _2 coordinates_ and pass user location + destination for faster routing / navigation?

Also current solution to pass multiple coordinates as separate arrays of latitudes and longitudes is not very nice?
If you have a better idea I can check it. :slightly_smiling_face:

**Comment by moving-bits** [comment]
> Cruiser has an active "Open testing" with this [join link](https://play.google.com/apps/testing/gr.talent.cruiser). Or better contact me on the [Google Play](https://play.google.com/store/apps/details?id=gr.talent.cruiser) email to send you apk for testing?

I've joined beta program for Cruiser now, but it may take some time until the beta version will be distributed to me.
If you like you can send me the apk using our support system (adding it to the ticket you had opened wrt Cruiser).

> Can you use the intent with the _2 coordinates_ and pass **user location** + destination for faster routing / navigation?

I have updated the PR accordingly.

> Also current solution to pass multiple coordinates as separate arrays of latitudes and longitudes is not very nice? If you have a better idea I can check it. 🙂

For Google navigation we are passing both coordinates as url string, but I guess putting it into the intent is ok (as long as it works, haven't tested yet).
Will this feature allow to send even more coordinates, e. g. for passing a route? (This function is not available yet in c:geo, but c:geo does support routes, so this may be an interesting extension some day.)

Does Cruiser support displaying a name for the destination? If so, how to pass the name?

**Comment by devemux86** [comment]
> I've joined beta program for Cruiser now, but it may take some time until the beta version will be distributed to me.

I have not released a Beta version, 3.0.8 is the only public one.

> If you like you can send me the apk using our support system (adding it to the ticket you had opened wrt Cruiser).

Thanks, I will prepare and send you an apk there.

> I have updated the PR accordingly.

:+1: 

> Will this feature allow to send even more coordinates, e. g. for passing a route?

You can pass multiple coordinates as waypoints to calculate a route for navigation.

Or you mean passing the array of coordinates of an already calculated route?
However then Cruiser will only know this route geometry, it is like GPX track.
A route contains more data, turn instructions, street names, speed limits, ...

> Does Cruiser support displaying a name for the destination? If so, how to pass the name?

Yes, please see the samples in https://github.com/cgeo/cgeo/issues/13924#issuecomment-1413803745.
When passing 1 coordinate, can also pass its name.

This is why the multi-coordinate implementation may need improvements.

**Comment by moving-bits** [comment]
> Thanks, I will prepare and send you an apk there.

👍 

> > Will this feature allow to send even more coordinates, e. g. for passing a route?
> 
> You can pass multiple coordinates as waypoints to calculate a route for navigation.
> 
> Or you mean passing the array of coordinates of an already calculated route? However then Cruiser will only know this route geometry, it is like GPX track. A route contains more data, turn instructions, street names, speed limits, ...
> 

With "route" I only meant a bunch of geopoints as consecutive destinations, no actual route precalculated between those points. So a "route" in terms of GPX, not a "track".

Eg: Start in Munich, continue to Berlin, then to Hamburg as destination - would be given as an array of three geopoints, and Cruiser would need to calculate navigation from Munich to Berlin, and from Berlin to Hamburg.

> > Does Cruiser support displaying a name for the destination? If so, how to pass the name?
> 
> Yes, please see the samples in [#13924 (comment)](https://github.com/cgeo/cgeo/issues/13924#issuecomment-1413803745). When passing 1 coordinate, can also pass its name.
> 
> This is why the multi-coordinate implementation may need improvements.

You mean the "NAME" intent parameter? (This is commented out in the examples, so I'd skipped it.) Would this parameter be available in the multi-point variant as well? May this be extended to a String[] to support names for every point in-between? And if only one name is given, this will be the name for the destination.

**Comment by devemux86** [comment]
> With "route" I only meant a bunch of geopoints as consecutive destinations

This is already possible, you can pass an array _of any number_ of coordinates.

> May this be extended to a String[] to support names for every point in-between? And if only one name is given, this will be the name for the destination.

Thanks for the suggestions, I can implement it like that! :+1:

**Comment by devemux86** [comment]
> If you like you can send me the apk using our support system (adding it to the ticket you had opened wrt Cruiser).

I sent you a Cruiser 3.0.9 (Beta) apk via the support email (and ticket).

> May this be extended to a String[] to support names for every point in-between? And if only one name is given, this will be the name for the destination.

Done. :+1: 

I also updated above the examples in https://github.com/cgeo/cgeo/issues/13924#issuecomment-1413803745.
You can pass multiple waypoints with arrays of latitudes, longitudes and names for routing / navigation.

**Comment by ztNFny** [comment]
OT: Does Cruiser happen to be able to solve the "shortest round-trip visiting all points" problem? I'm still looking for any solution for that on Android.

**Comment by devemux86** [comment]
> Does Cruiser happen to be able to solve the "shortest round-trip visiting all points" problem?

Do you mean the [Traveling salesman problem](https://en.wikipedia.org/wiki/Travelling_salesman_problem)?
Cruiser uses offline and online routing services.

[GraphHopper Route Optimization API](https://www.graphhopper.com/route-optimization/) should be suitable for such case?
For now I have only included the normal routing API in Cruiser.

**Comment by ztNFny** [comment]
> > Does Cruiser happen to be able to solve the "shortest round-trip visiting all points" problem?
> 
> Do you mean the [Traveling salesman problem](https://en.wikipedia.org/wiki/Travelling_salesman_problem)? Cruiser uses offline and online routing services.
> 
> [GraphHopper Route Optimization API](https://www.graphhopper.com/route-optimization/) should be suitable for such case? For now I have only included the normal routing API in Cruiser.

Yes. My usecase is "a bunch of caches in an area". Coming up with a good plan of how to visit them is always a pain.
I looked into it with BBrouter, but there's no good solution there (currently)

**Comment by moving-bits** [comment]
I've updated PR #13952 to provide the destination's name to Cruiser, works fine with provided beta build of Cruiser:

![image](https://user-images.githubusercontent.com/3754370/216824239-733d4a61-c1c3-40e1-9b60-0885a617be69.png)

**Comment by moving-bits** [comment]
BTW: How about Cruiser GL?
Does it also support the new intents? How to identify if it is installed (package name)?

**Comment by devemux86** [comment]
Thanks!
If you need anything else, please let me know.

> BTW: How about Cruiser GL?
> Does it also support the new intents? How to identify if it is installed (package name)?

The map engine in Cruiser can be selected in "Settings | Map | Rendering engine".
Cruiser starts with the engine selected last time. Both engines support the intents.

**Comment by moving-bits** [comment]
> Thanks! If you need anything else, please let me know.

I guess for a basic navigation integration everything's settled with PR #13952. 
If we ever start something similar for c:geo's individual routes, we might come back to this.

> > BTW: How about Cruiser GL?
> > Does it also support the new intents? How to identify if it is installed (package name)?
> 
> The map engine in Cruiser can be selected in "Settings | Map | Rendering engine". Cruiser starts with the engine selected last time. Both engines support the intents.

Ah, I thought those were two different apps. So we have covered Cruiser GL already.

**Comment by devemux86** [comment]
@moving-bits 

I updated above the examples in https://github.com/cgeo/cgeo/issues/13924#issuecomment-1413803745 with minor improvement in action names.

**Comment by moving-bits** [comment]
@devemux86 
I've updated the action name and merged the PR. It will be part of the next nightly version as well as of the release after the currently tested beta version (so maybe app. six to eight weeks to go).

**Comment by devemux86** [comment]
Thanks!

Cruiser 3.0.9 with these actions will also be released soon.

**Comment by devemux86** [comment]
[Cruiser 3.0.9](https://play.google.com/store/apps/details?id=gr.talent.cruiser) is available with the new intents mentioned above in https://github.com/cgeo/cgeo/issues/13924#issuecomment-1413803745.
