### ISSUE TITLE
CI job `Publish FDroid - RELEASE` can not sent to IRC

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13944]
### Describe your problem!

The job tries to sent IRC messages, but without success.
~~~
21:44:20  IRC notifier plugin: [ERROR] not connected. Cannot send message to '#cgeo'
~~~
I think that can be removed.

Btw., the job `Publish FDroid - NIGHTLY` does not try to sent IRC messages.

### How to reproduce?

see eg. https://ci.cgeo.org/view/FDroid/job/Publish%20FDroid%20-%20RELEASE/99/console

### Reproducible

Yes

### c:geo Version

CI job "Publish FDroid - RELEASE" #99

**Comment by Lineflyer** [comment]
I removed the IRC notification step from the post build actions and checked all F-DROID jobs for that.
