### ISSUE TITLE
Support route optimization

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13971]
> > Does Cruiser happen to be able to solve the "shortest round-trip visiting all points" problem?
> 
> Do you mean the [Traveling salesman problem](https://en.wikipedia.org/wiki/Travelling_salesman_problem)? Cruiser uses offline and online routing services.
> 
> [GraphHopper Route Optimization API](https://www.graphhopper.com/route-optimization/) should be suitable for such case? For now I have only included the normal routing API in Cruiser.

Yes. My usecase is "a bunch of caches in an area". Coming up with a good plan of how to visit them is always a pain.
I looked into it with BBrouter, but there's no good solution there (currently)

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/13924#issuecomment-1417824295_

**Comment by moving-bits** [comment]
To my understanding this requires at least two steps:
1. calculate distance matrix (either full or for selected pairs)
2. find and/or optimize a path connecting all points and returning to start point (= TSP)

Part one could be done in multiple threads in the background. When creating an individual route, this already forms one valid path, which (after a short time) is precalculated. We need to decide if we can/want/need to complete the distance matrix or if we only fill some of the gaps. (Some algos seem to require a complete matrix to return useful results, though.)

Ideas for part 2:
- branch and bound
- genetic algorithm using either ordered crossover or edge recombining operators
- whatever algorithm: add a time constraint (30s?) and use whatever best solution has been found so far

**Comment by moving-bits** [comment]
Implemented a first WIP for this with #13974, but many questions still to be answered...

**Comment by ztNFny** [comment]
Great to see that you started digging into this. I didn't even consider this a possible feature for c:geo! Unfortunately for another month I won't really have any time to look into anything.

**Comment by moving-bits** [comment]
Initial feature request is implemented with #13974, so let's close here. For a follow-up request see #14027
