### ISSUE TITLE
List of extended filters does not get translated if c:geo language is set to non-default

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13982]
Stumbled upon a strange thing while answering support tickets and having switched c:geo's language from "default system" to "en":

The dialog box that opens when you tap on "add filter criteria" does not get translated, it still shows them in the system's default language. Only when I switch the phone's default language to eg. "English", the dialog gets translated to English. (And it stays English, even if I then configure a different language within c:geo.)

So somehow this dialog does not seem to respect the language setting configured within c:geo, but always resolves to the system's language.

Version: Release 2023.02.12

**Comment by eddiemuc** [comment]
Probably something to fix in LocalizationUtils.

**Comment by eddiemuc** [comment]
Update: seems to work on my device, but only after a system restart

**Comment by eddiemuc** [comment]
Fixed with PR #13987
