### ISSUE TITLE
GPX sharing to Whatsapp results in error message

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13983]
User report on support:

When I try to export and share a GPX via whatsapp, it gives me this message: "Failed to share. Please try again"
(Google translated)

User claims to follow this procedure (which works for me):
- open cache list
- select one or more caches
- select "export"
- and in the resulting "success" dialog you select "share", then Whatsapp?

Reported for current release 2023.02.12
Ticket 543579

Any ideas?

**Comment by eddiemuc** [comment]
Works on my device. Is a log file available for Analysis?

Does the export work for other apps (e.g. signal or a maps app)?

**Comment by Lineflyer** [comment]
Debug log file requested from user.
But it could be, that the problem happens outside of c:geo. The sharing is initiated after the file has already been written.
