### ISSUE TITLE
Image orientation detection for "own images"

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13984]
### Tell us your idea!

User request on support: 

Images stored in the "own" section of the new image gallery seem to not recognize the image's orientation. Images in landscape format are displayed in landscape format, but images in portrait format are still being displayed in landscape.

If you tap on such an image to open it in the external viewer, orientation is detected correctly.

### What solution would you suggest?

Detect correct image orientation and rotate image accordingly for display

### Is there an alternative?

Leave it as is

### Additional Information

- reproducible behavior: yes
- user's phone model: Samsung S20
- ticket 456652

**Comment by eddiemuc** [comment]
Note to self: works in Log Image view, so best to look what is different there

**Comment by SammysHP** [comment]
I have imported an image and took a picture from within c:geo, both worked fine. So it's not a general problem, but maybe more a result of way the orientation is stored in the image. That's why I asked the reporter to include a sample image with his mail.

**Comment by eddiemuc** [comment]
I can reproduce the problem and working on a fix

**Comment by eddiemuc** [comment]
Fixed with PR #13989
