### ISSUE TITLE
Repetitive ANR messages after using waypoint calc

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13995]
Quite similar to #13828 I again had the problem of the phone reporting c:geo being not responsive while it is (at least I can use it).

This time however I was able to "kind of" reproduce it.
It seems to be related to trying to use the waypoint calc while having (not interpretable) content in the clipboard.

- Open GC7360Q
- Copy the (very special) formula from the cache description into your clipboad
- Swipe to waypoint tab
- Tap on "Add waypoint"
- Tap on coordinate field
- Select "Calculate coordinate"

Result:
The app is unresponsive for several seconds until the calculate coordinate dialog finally appears.
While you now can use the app normally, still my phone reports "c:geo does not respond" with Options "Wait" or "Close". Once you select "Wait" it appears again after some seconds. The whole time c:geo seems to work normal and responsive.

Android 13
2023.02.12-NB-6418ca6

**Comment by Lineflyer** [comment]
BTW: Looks related to #13994

**Comment by eddiemuc** [comment]
> BTW: Looks related to #13994

Pretty sure this is a duplicate

**Comment by moving-bits** [comment]
Fix confirmed with upcoming bugfix release 2023.02.25, so let's close here
