### ISSUE TITLE
NPath complexity threshold 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13990]
We should seriously discuss whether the 200 threshold should be raised. It does not even nearly reflect the complexitiy of all the main classes of c:geo, and it is unrealistic to think that we will ever have time and passion to achieve this in the whole codebase.

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/13981#issuecomment-1434170545_

**Comment by moving-bits** [comment]
We are hitting this limit quite frequently, even for trivial methods, where splitting it up into submethods would only decrease readability, so I'd vote for increasing the limit as well. Just don't have a good new value to propose...

**Comment by bekuno** [comment]
We can
- increase the limit
- set the severity to e.g. info
- add to the suppression list

I propose to change the severity for now.

**Comment by bekuno** [comment]
Result from PR #14025:
By adding the value to the checkstyle configuration it activated the check with checkstyle (on CI).
Therefore instead to configure checkstyle we have to configure PMD.

**Comment by moving-bits** [comment]
How / where can this be configured?
