### ISSUE TITLE
Support changing line width for individual tracks

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14019]
### Tell us your idea!

It would be great if the "select track color" dialog would support settings an individual line width. 

### What solution would you suggest?

Add an additional slider

### Is there an alternative?

There are no alternatives to customize the line width on a per track basis. One could only change the width for all tracks currently.

**Comment by moving-bits** [comment]
Can this be done for our line preferences as well - this would reduce the list of options in map preferences? (We would need to add a second preference key to the xml description for the affected settings.)

**Comment by fm-sys** [comment]
> Can this be done for our line preferences as well - this would reduce the list of options in map preferences?

Of course. Just wasn't sure how we could display the currently selected width inside the settings properly outside the dialog. Maybe resize the color preview to fit with the select width?

**Comment by moving-bits** [comment]
> Just wasn't sure how we could display the currently selected width inside the settings properly outside the dialog. Maybe resize the color preview to fit with the select width?

Or maybe not display it at all in the list of settings?
Or just as part of textual description ("width: 5")?

**Comment by fm-sys** [comment]
> Or just as part of textual description ("width: 5")?

Done within PR https://github.com/cgeo/cgeo/pull/14022
