### ISSUE TITLE
Cannot build c:geo

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14011]
I cannot build c:geo any longer, does anyone have an idea on how to fix this?

![grafik](https://user-images.githubusercontent.com/64581222/220316357-243c5692-c223-43a6-bae3-c99cf383df36.png)

**Comment by eddiemuc** [comment]
The mentioned download link in your error message https://jitpack.io/com/github/k3b/k3b-geoHelper/v1.1.11/k3b-geoHelper-v1.1.11.jar works for me. Maybe a temporary internet access problem on your developer machine or on server side?

**Comment by fm-sys** [comment]
Indeed, now it works again. Thanks for looking into it! Internet was working fine for me at that time, so it must have been a temporary server-side problem. 

Let's close for now...

**Comment by drinkcat** [comment]
For future reference, just in case...

I had a similar issue, but on version k3b-geohelper 1.1.12 as that's what master pulls now.

Ended up adding this to `gradle.properties` (based on this [stackoverflow answer](https://stackoverflow.com/questions/65957683/gradle-sporadically-times-out-fetching-jar-from-jitpack)):
```
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000
```
and the sync step finally succeeded.
