### ISSUE TITLE
Logbook view shows incomplete date

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14014]
We had at least two users reporting, that with the new release 2023.02.12 the logbook view got truncated on the log dates / log types.

The screenshot explains (in this case the custom date format with weekday information might cause it?!):
![image](https://user-images.githubusercontent.com/949669/220379084-c83ce2a4-1763-4f1f-b4b8-9ce5b7623e8a.png)

Not sure whether there really was a change since last release, however I think we should always show the complete information but not truncate it.

**Comment by eddiemuc** [comment]
IIRC the width of the name/date/status column in the log view is hardcoded.

How can one customize the date format used there?

**Comment by Lineflyer** [comment]
IMHO its using the systems date format selected in the global phone settings.
The system information of this users shows:
```
- System date format: E, dd MM yyyy
```

**Comment by eddiemuc** [comment]
Hm doesn't seem to be possible on my phone.

Anyway, I checked in code and the width in the log view is indeed of a fixed length. This is nothing new, and too long texts always got truncated (e.g. "Nicht gefunden"). So is this really a bug?

**Comment by Lineflyer** [comment]
I asked the user and it seems he changed his device. The new one has this date setting and he also claims he cannot adjust it.
So I also assume its not new but depending on resolution, date format and string length in locale for log types.

If we would make the length flexible, it would look ugly.
One would need to cut of at the beginning instead of the end of the date...but thats IMHO not possible.

I remember we had such issue in the past and already optimized the view a bit by using `dip` instead od `dp` (or was it the other way round) to compensate different font settings.

**Comment by ztNFny** [comment]
imho close as wontfix as there's no way to make this look good in all situations

**Comment by Lineflyer** [comment]
Probably right.
What about if we give more room for the left part at least in landscape mode?

**Comment by moving-bits** [comment]
When setting widths to `wrap_content`, it will look like this:

![image](https://user-images.githubusercontent.com/3754370/221696225-d1e8bc8d-cbba-4fa9-8e4f-6172d8b63360.png)

as each row gets its own separate columns. 

Currently it depends on the log type ("Found it" or "Needs Maintenance" in this case), but depending on the specific date format, that may be the relevant factor for column widths.

Is there a way to use sort of a grid layout to get the same column widths for every row?

**Comment by Lineflyer** [comment]
The log types are not really the determining factor...those could be truncated but users might still recognize.
If we would be able to fit the width to the individual length of the date column, it would be the best option: Date always completely shown, the other items show best possible.

Anyway:
The user also stated the landscape mode shows the same problem.
At least in landscape on large devices it must IMHO be possible to show it without any truncation using the right layout.

**Comment by fm-sys** [comment]
Whatever solution we find at the end, the whole list needs to use a consistent width or it would just look messy.

**Comment by Lineflyer** [comment]
I would say, we should leave the portrait view as it is.
In the landscape view we should probably use the same ratio between log type part and log part as in portrait to make it look similar styled but offer more space.

**Comment by moving-bits** [comment]
> The log types are not really the determining factor...

I meant: In the screenshot above, where I have willingly set width of left column to `wrap_content` - which is obviously no solution.

> I would say, we should leave the portrait view as it is. In the landscape view we should probably use the same ratio between log type part and log part as in portrait to make it look similar styled but offer more space.

We have a fixed width for the left column, and the right column takes whatever space is left.

We could try:
- Set left/right column to a certain ratio (not sure whether this will give a constant width or will result in something like my screenshot above); use same ratio for both portrait and landscape mode
- Set left column to a wider, but fixed width in landscape mode - what would be a good value?
- Find something like a grid layout (variable column widths, but constant within a page)

**Comment by Lineflyer** [comment]
Here is the screenshot from the user if he uses landscape mode (same cache as in initial posting):
![grafik](https://user-images.githubusercontent.com/949669/222110399-5c7348fb-5ddb-40db-83a0-f6902f2f8a7f.png)

You can probably see, what I mean:
Lot of free space right of log text, still cluttered left column.

> Set left column to a wider, but fixed width in landscape mode - what would be a good value?

That would be probably an easy approach and sufficient for now.

**Comment by moving-bits** [comment]
> > Set left column to a wider, but fixed width in landscape mode - what would be a good value?
> 
> That would be probably an easy approach and sufficient for now.

See PR #14039. I've chosen `130dp` (coming from `100dp` in portrait mode) as mitigation value, let's see how this works out in real life.

**Comment by moving-bits** [comment]
Has been released with 2023.03.25, so let's close here
