### ISSUE TITLE
Add route optimization for linear routes

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14027]
_Originally posted by @SammysHP in https://github.com/cgeo/cgeo/issues/13974#issuecomment-1445053272_

> > There's no need to add starting point as end point manually.

> Except for this situation: a planned trip from point A to B with the plan to visit all downloaded caches in between.

---

Additional info:

Currently our optimization algorithm plans a route _beginning and ending_ with the first point of the current individual route, trying to optimize the path for the points visited in between, visiting all points of the individual route along this way.

Planning for a linear route would have to find an optimized route _beginning with the first point of the current individual route_ and _ending with the last point of the current individual route_, visiting all points in between in an optimized order.

**Comment by ztNFny** [comment]
I tested this for the first time today and while ordering points works in general there's one major item missing: there's no fixed end-point and thus even after adding my target to route to make it a round-trip after optimizing the route that point is no longer last, making it a linear route.
I suggest to just set the last point in the route as fixed.

**Comment by ztNFny** [comment]
> Currently our optimization algorithm plans a route beginning and ending with the first point of the current individual route

That doesn't seem to be the case. It just ends the route wherever it'll end up shortest.

**Comment by moving-bits** [comment]
> > Currently our optimization algorithm plans a route beginning and ending with the first point of the current individual route
> 
> That doesn't seem to be the case. It just ends the route wherever it'll end up shortest.

It does not add the starting point as last point to the visible route, but when calculating a route length it uses the starting point also as final point, making it a round trip. This is why this issue here exists, as there are currently no linear routes being calculated.

**Comment by ztNFny** [comment]
> It does not add the starting point as last point to the visible route, but when calculating a route length it uses the starting point also as final point, making it a round trip

That's definitly not what I'm seeing here (master). The route ends with the cache farthest away from my start point, this route doesn't make any sense as a round-trip.

**Comment by ztNFny** [comment]
![image](https://user-images.githubusercontent.com/1258173/230737715-e855dd2b-582b-4415-bbcb-826400369051.png)
1 is route start, 2 is the last cache after auto-sorting
red is my hand-drawn shortest round-trip-route

**Comment by moving-bits** [comment]
Thanks for the detailed illustration. Question now is: Is it a programming error or an artifact of both algorithms only being approximations and no full evaluations?

Route initialization is done like this:
```
for (int i = 0; i < routeSize; i++) {
    best[i] = i;
}
best[routeSize] = 0;
```

So as a beginning all points are in the order given by the user, and starting point ("0") is added at the end additionally, making it a round trip when calculating route length. All swapping leaves first and last entry untouched. (At least that's the way it's supposed to be, there may still be errors in the code.)

But: Both algorithms ("hill climbing" as well as "simulated annealing") are approximations only, which do not do a full evaluation of all possible combinations (which would get unfeasable pretty fast with growing number of waypoints). Both algorithms can get stuck in a local optimum, therefore we have mutations built in, probably making a route worse temporarily, but giving way for new combinations. Sometimes there aren't "the right" mutations within a single run, that's why you can start a recalculation. It _may_ (but do not have to) take five runs or so to get a relatively optimized solution, sometimes more for longer routes. The user can decide whether they want to do another run (based on already precalculated distance matrix, thus relatively fast) or are satisfied with the optimization gain already achieved.

**Comment by ztNFny** [comment]
I removed the code adding start as target in RouteOptimizationHelper. This should make it a linear route from first to last route point. So by adding a point near start as last point I can manually make it a round-trip again.

I then sorted - and the result is: Last waypoint (which per you should be fixed) jumps to position 2 in the route and the route is linear again.

So it seems the issue is that only start, not end, is fixed.

**Comment by ztNFny** [comment]
> I removed the code adding start as target in RouteOptimizationHelper. This should make it a linear route from first to last route point. So by adding a point near start as last point I can manually make it a round-trip again.
> 
> I then sorted - and the result is: Last waypoint (which per you should be fixed) jumps to position 2 in the route and the route is linear again.
> 
> So it seems the issue is that only start, not end, is fixed.

Nevermind that, didn't change all code lines that had to be changed

**Comment by moving-bits** [comment]
Did you modify calculations as well? Route of length n gets put into an array of length n+1, having the starting point "0" at positions 0 and n. All swapping happens to positions 1 to n-1 only.

If you leave out settings array position n to "0", but make the route one element longer, it has an undefined element at the last array position (probably being initialized to "0" by Java). This means, that all points in between, including your "close to start" extra point, will be part of optimization (but internally still "0" is last point of calculated route).

**Comment by moving-bits** [comment]
But this part may be an error:

```
public int calculateRouteLength(final int[] route) {
    int length = 0;
    for (int i = 0; i < route.length - 2; i++) {
        length += distanceMatrix[route[i]][route[i + 1]];
    }
    return length;
}
```

Shouldn't that read `i < route.length - 1` in the `for` loop to take the distance from last point to starting point into account?

**Comment by ztNFny** [comment]
With my "linear" routing and adding "start" manually as last waypoint I get the expected round-trip (although it's actually linear).
Reverting to the original code I again get a linear route, matching that of my "linear" routing if I don't add start as last waypoint.

So it seems it's in fact "use start as target" that's broken.

Suggestion: For now use linear routing (remove the "+1s") and have the user add a last waypoint manually to make it a round trip. At least that way it works as expected - until a "proper" dialog for round-trip vs. linear is in place.
I'll add a PR for the code that seems to be working for me now.

**Comment by ztNFny** [comment]
> But this part may be an error:
> 
> ```
> public int calculateRouteLength(final int[] route) {
>     int length = 0;
>     for (int i = 0; i < route.length - 2; i++) {
>         length += distanceMatrix[route[i]][route[i + 1]];
>     }
>     return length;
> }
> ```
> 
> Shouldn't that read `i < route.length - 1` in the `for` loop to take the distance from last point to starting point into account?

Yes, that makes it a round-trip!

**Comment by ztNFny** [comment]
> Yes, that makes it a round-trip!

However I still like "linear" a bit better. 2 reasons:
- Start is not added as a user-visible waypoint at the end, making it not apparent to the user that it's indeed a round-trip back to start
- Usually you won't want to visit waypoint 1 again but only somewhere "near" it. Depending on the route "near" might not be so close, resulting in a "wrong" route.

Another question: Is there a setting to make it calculate longer/better? For my tests I had to optimize 3-5 times to get to the best. For me it'd be acceptable to wait a bit longer and not have to click the optimize button repeatedly. I checked the code but couldn't find any setting or code for such a loop.

**Comment by moving-bits** [comment]
#14172 adds linear mode to route calculation, user can choose between "roundtrip" and "linear" mode.
Whether "roundtrip" or "linear" is set as default (= rightmost button) may be discussed. I could live with either variant.

> Another question: Is there a setting to make it calculate longer/better? For my tests I had to optimize 3-5 times to get to the best. For me it'd be acceptable to wait a bit longer and not have to click the optimize button repeatedly. I checked the code but couldn't find any setting or code for such a loop.

There's no setting so far. One could add an extra rule to start automatic repeats until at least a specific amount of time has been used (e.g.: 30s).

**Comment by ztNFny** [comment]
> #14172 adds linear mode to route calculation, user can choose between "roundtrip" and "linear" mode.
> Whether "roundtrip" or "linear" is set as default (= rightmost button) may be discussed. I could live with either variant.

My vote guess to linear but if both buttons are there i don't really care.

> There's no setting so far. One could add an extra rule to start automatic repeats until at least a specific amount of time has been used (e.g.: 30s).

Not sure a timeout will work well. At least it must not be the only condition. Maybe "return if runcount > 5 or time > 30s or thisRouteLength >= previousRouteLength"?

**Comment by ztNFny** [comment]
Playing with the PR the solution for round trip seems suboptimal to me as the last leg is invisible.
How about solving round-trip by a) duplicating start as target, using a coordinates only WP (for which to be visible there's another PR), b) calculating linear route. Would make the code easier and the result more transparent.

**Comment by moving-bits** [comment]
> Playing with the PR the solution for round trip seems suboptimal to me as the last leg is invisible. 

Understandable, that's a thing that bugs me as well.

> How about solving round-trip by a) duplicating start as target, using a coordinates only WP (for which to be visible there's another PR), b) calculating linear route. Would make the code easier and the result more transparent.

Thinking about it I see conflicting design goals:
1. Make last leg visible and keep the code simple => add starting point at the end of the route and do a linear routing
2. Keep the process repeatable (so doing another roundtrip calculation should not add another destination)
3. Allow redefining the starting point of a tour (by using context menu of an item in route edit mode) - route list should not keep auto-generated points in the middle of the reordered list in this case

Both 2. and 3. could be solved if the route itself knows it's a roundtrip, so maybe the solution to linear vs. roundtrip is an item of the route but not of the route optimization?

(This would also allow for optimizing the distance matrix to not manually calculate distances for the auto-generated extra point but duplicate them from the starting point.)

**Comment by ztNFny** [comment]
Another thought, just thrown in here, no solution yet: when doing route planning in the field start/end should be not first WP but current position.
But for preplanning it should be WP1.

**Comment by moving-bits** [comment]
> Another thought, just thrown in here, no solution yet: when doing route planning in the field start/end should be not first WP but current position. But for preplanning it should be WP1.

How could c:geo know which waypoint do you want to start from ("closest" could be an approximation), and which waypoints of the route you have already visited?

Normally you would do planning (including route optimization) in advance. And even if you decide to start at a different point of your route, this should not change your optimized order. But when you forgot to do this in advance, or when you start adding or removing points while already on the way, you may have the need to do this "on the road".

Workaround for this is:
- remove all waypoints you have already visited from route
- set "route start from here" for the waypoint you want to visit next
- optimize route

**Comment by ztNFny** [comment]
Of course the user is responsible to have only WPs he wants to visit. But i usually start planning the exact route when I'm at the parking coordinates, that's why i was thinking he might want to start at current position instead of first WP.

There's many different scenarios here, I think route planning will need an options dialog.

Suggestions:
- [ ] start at current position vs. first WP
- [ ] round trip: return to first WP vs. linear trip
- [ ] max calculation time: stop looking for a better route after max X (30) seconds or if no better route has been found in X (2) attempts 
- [ ] algorithm: (not sure it makes sense to expose this)

Then the calculation status and results could be shown in the same dialog as well.

**Comment by ztNFny** [comment]
> How could c:geo know which waypoint do you want to start from

I didn't say "closest" but "current position" - i.e. me at the parking coords.

**Comment by moving-bits** [comment]
Phew, that's a lot of options. I would prefer a more radical simplification:
- make "roundtrip" a property of the individual route (a checkbox above the route items list in edit mode, default=off)
- let the user decide which is the first item to start with (when you park at a specific location, you probably have a specific starting wp in mind) - no need for a config option for this
- set min retry time to a reasonable default value - one may optionally override this in settings manually, but not "on demand"
- algorithm: internally both are used already and best results are reported back to the user

Following this approach there would be no need for any "on demand" config options at all, making the process even easier for the average user.

**Comment by moving-bits** [comment]
FYI: Will wait with adding a "isRoundtrip" flag until https://github.com/cgeo/cgeo/pull/14159#issuecomment-1501164818 is implemented to avoid unnecessary implementation work.

**Comment by moving-bits** [comment]
Some more thoughts on it:

My idea was to add a flag "isRoundtrip" to the `IndivdualRoute`. This could have been used
- for calculation / optimizing the route: automatically take return to starting point into account, and
- for drawing the route: automatically add a line from last calculated point to start point

First question comes with exporting / importing routes: Should the flag "isRoundtrip" be stored as well? (And if so: how/where? - adding c:geo-specific field to gpx?)
Next question is along a route: You start deselecting points after having visited them. The flag has to be reset then as well after having visited the starting point (and starting point being added as destination at the same time).

Both things could be done, but start making things complicated.

An alternative could be to stay with linear mode only (as suggested by @ztNFny above), and let the user manually add their destination point of choice.

This is a bit troublesome currently, as with current UI you cannot add starting point as destination point additionally. You have to wait until you have visited the starting point, unselect it, and on selecting it again, it gets added as new point at the end of the route. (This is to keep the UI simple - long-touching a point which is not part of the route adds it to the route, and long-touching a point that is already part of the route will remove it from the route.) - This problems gets resolved automatically when implementing #13176 in the proposed way (ie: long tap always opens a context menu), as the context menu could then contain all of "append to route", "prepend to route" and "remove from route" (where appropriate).

TMALSS:
- change current implementation to "linear mode only"
- let the user add their preferred destination on their own
- helping them with that by implementing context menu on long-tapping a geocache/waypoint
- keep export/import of route "as is"

**Comment by ztNFny** [comment]
> But that would only solve the problem partially. 

What are the issues that have to be solved?

For round-trip I see 3:

- export to GPX
- what to do with the route once WPs are removed
- visualize the last leg

For linear all is working already, it's only UX optimizations that could be done to make it easier to create a round-trip (add item to route multiple times or auto-add first as last or something).

**Comment by moving-bits** [comment]
That's what I meant my "TMALSS" part:
- make calculation linear (it's roundtrip currently)
- implement #13176 to make adding a point twice to a route easier

The rest can stay "as is" then, IMHO - no changes needed for GPX route export/import, route handling on removing waypoints, visualization etc.

**Comment by moving-bits** [comment]
Meanwhile both parts are implemented, so let's close here.
