### ISSUE TITLE
Remove Jetifier from build config?

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14033]
After upgrading AS to Electric Eel, gradle proposed to remove the `android.enableJetifier=true` flag from our build config. It offers to run a check (which I accepted), and claims that no dependency need Jetifier any more:

![image](https://user-images.githubusercontent.com/3754370/221379648-793d224a-bbd1-4364-a64d-abd3ca630098.png)

(Link provided in the screenshot is [this](https://developer.android.com/jetpack/androidx/migrate#migrate_an_existing_project_using_android_studio))

@cgeo/team 
As I'm not firm with build config, can anyone cross-check whether it's ok to remove this flag?

**Comment by bekuno** [comment]
It is ok to remove the flag.
Implemented with https://github.com/cgeo/cgeo/commit/cb166b8ed0fa9918a4a01ac552e883084a79495f
(sorry, I forgot that I tested at my master)
