### ISSUE TITLE
Implement a way to view list of recently opened caches in c:geo

### ISSUE THREAD

**Issue by valentijnscholten** [cgeo/cgeo#14049]
### Tell us your idea!

I've been away from c:geo for a while, so I might have missed some new functionality in the new menu's. But my use case is this:

- Open c:geo, open map with (live) caches;
- Open some caches to see which are interesting to go and find;
- Let's see I view 10 caches in different areas of a town or country;
- I decide that that 2nd or 3rd multicache I viewed was the most interesting;
- Observe I can't easily find that multicache from c:geo or the map anymore, unless I remember where it was or maybe search for it by name or GC Code;

### What solution would you suggest?

It would be good to have a list of caches that have been opened recently in c:geo to help with the above use case.
It could be integrated into the existing History list, or a new list.
This feature request sounds a bit like #14048 , but is different because this is locally to c:geo.

### Is there an alternative?

Screenshot all the caches while viewing them :-)

**Comment by fm-sys** [comment]
This is already possible (although quite hidden):
- option 1:
  - open the search view on c:geo's main screen but don't enter anything. The suggestions will match your recently viewed caches
- option two:
  - long-click on "search" in the bottom navigation bar. You will see a list of recently viewed caches

**Comment by valentijnscholten** [comment]
Ah, nice. That's already helpful. Ideally I would long press on Search in the nav bar and then be able to perform bulk actions on those caches such as storing/refreshing them.

**Comment by valentijnscholten** [comment]
Ah nice, wasn't aware of that. Thanks! Might be nice to be able to perform bulk operations on them like storing/refreshing them. But not sure if that's a very common use case.

**Comment by fm-sys** [comment]
> Ah nice, wasn't aware of that. Thanks! Might be nice to be able to perform bulk operations on them like storing/refreshing them. But not sure if that's a very common use case. 

This could be implemented within option two:

> long-click on "search" in the bottom navigation bar. You will see a list of recently viewed caches

We could add a "show as list" button to the dialog. That would provide all common actions within the classic CacheListActivity without the need to reimplement all of them.

**Comment by fm-sys** [comment]
![grafik](https://user-images.githubusercontent.com/64581222/222891119-9bc2d4e1-b676-467a-b363-d12b30080584.png)
![grafik](https://user-images.githubusercontent.com/64581222/222891121-365c210b-1cf9-4b4f-99ea-58050644dfb6.png)
