### ISSUE TITLE
Support Google Maps terrain overlay

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14043]
### Tell us your idea!

Asked by a user on support:
Can c:geo also shown Google Maps in "terrain" mode.
He is refering to this view: [https://www.google.com/maps/@?api=1&map_action=map&center=-33.712206%2C150.311941&zoom=12&basemap=terrain](https://www.google.com/maps/@?api=1&map_action=map&center=-33.712206%2C150.311941&zoom=12&basemap=terrain&hl=de)

In contrast to the normal map and satellite map it contains hill shading as well as height lines.
More info: https://developers.google.com/maps/documentation/urls/get-started?hl=de

### Is there an alternative?

@moving-bits 
Is that somehow part of higher version of GMaps API and/or anyway included in a potential unified map?

**Comment by Lineflyer** [comment]
Further info from user (not sure if relevant/matching):

Actually, I did dive deeper. https://hatarilabs.com/ih-en/how-to-add-a-google-map-in-qgis-3-tutorial has a list of URL templates, all of which are [http://mt0.google.com/vt/lyrs=foo&hl=en&x=[x]&y=[y]&z=[z]](http://mt0.google.com/vt/lyrs=foo&hl=en&x=%5Bx%5D&y=%5By%5D&z=%5Bz%5D) where foo is replaced by:

**Comment by moving-bits** [comment]
> @moving-bits Is that somehow part of higher version of GMaps API and/or anyway included in a potential unified map?

That's indeed easy to implement in `UnifiedMaps`, will provide a PR for it.

I'll need to look into `CGeoMap`, if it can be implemented there with reasonable effort as well.

**Comment by moving-bits** [comment]
Provided PR for both `UnifiedMap` (#14051) and `CGeoMap` (#14052).
