### ISSUE TITLE
Do not "Visit TBs" on log type WA, WN, NM and NA

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14055]
### Tell us your idea!

"Visit TBs" is a useful feature, but does not really make sense in all possible contexts. Like with "Needs Archive" and "Needs Maintenance" there usually is a "Found" or "DNF" log anyway, which both make a lot more sense for a TB's visit log (although a "Visit" going along with a "DNF" may be questionable, but most probably the TB/cacher has been at the coords for real, thus it's at least arguable), however, a "Write Note" does not even pretend to have been at the coords and finally a "Will attend" is most definitely no log where TBs should be logged as "Visited".

### What solution would you suggest?

Do "Vistit TBs" on these log type only, which are connected to a real visit of the coordinates:
- Found
- DNF (tbd)
- Attended
- Webcan Photo taken
- Owner Maintenance

resp. exclude log types which do not automatically imply that one has been at the coordinates:
- Will Attend
- Write Note
- Needs Maintenance
- Needs Archive

Same applies to any other kind of owner log, where a TB visit does not really make sense:
- Update Coordinates (tbd)
- Disabled
- Enabled
- Archived
- Announcement

**Comment by moving-bits** [comment]
similar to / related to #13783

Therefore moved comment over there and close here
