### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by Korb** [cgeo/cgeo#14062]
### Tell us your idea!

Add screenshots of c:geo to F-Droid.

### What solution would you suggest?

Without a preview, only by a text description, it is difficult to decide whether to download and install the application or not. I propose to add a few screenshots that most fully describe the appearance and functionality of the application. With pictures "c:geo - contacts (add-on)" will be able to be shown on the [f-droid.org/en/packages/](https://f-droid.org/en/packages/) and on the main page of the F-Droid mobile app. More people will be able to see and find "c:geo - contacts".

### Additional Information

https://f-droid.org/packages/cgeo.contacts/ (the link works only on mobile device with the desired repository connected in the F-Droid app)

**Comment by SammysHP** [comment]
c:geo is not naively included in f-droid due to non-free extensions like some connector libraries. We provide our own f-droid repository for c:geo: https://www.cgeo.org/development#f-droid-repository

**Comment by Korb** [comment]
I know that your application is missing from the main F-Droid repository. But I found it in the F-Droid application after connecting the corresponding repository. And there are no screenshots in the application card. In this connection, I created this topic.

![Screenshot_2023_0306_111322](https://user-images.githubusercontent.com/3509797/223054473-e8355f1d-d170-478e-97a3-e583730bdcc7.png)
![Screenshot_2023_0306_111341](https://user-images.githubusercontent.com/3509797/223054502-4364fb42-7304-4008-8a21-a66d25dcc490.jpg)

**Comment by SammysHP** [comment]
Isn't the contacts plugin deprecated or was that the calendar plugin? Anyway, there are no screenshots available for the plugin because it has no GUI. It is just a proxy that was necessary before users were able to individually grant permissions.

**Comment by MagpieFourtyTwo** [comment]
Although it has no GUI, we can add the popup with the "Open contact card" menu entry (to make clear, how it works and integrates) plus perhaps even the "Multiple matches" selection popup (which I would not really suggest, as it looks kind of old-fashioned ;) ).

BTW: Love this add-on, use it A LOT :) )

**Comment by k3b** [comment]
> c:geo is not naively included in f-droid due to non-free extensions like some connector libraries. We provide our own f-droid repository for c:geo: https://www.cgeo.org/development#f-droid-repository

c:geo is also included in the izzy repo at https://apt.izzysoft.de/fdroid/index/apk/cgeo.geocaching .

In the fdroid-app (version 1.16) i can see the requested app screenshots. I donot know where they come from.

I have both repros added izzy and cgeo

@Korb is this issue still open or can it be closed?
