### ISSUE TITLE
Early feedback about action bar hiding 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14066]
### Describe your problem!

Google map:
- [x] zoom by double tap triggers action bar hiding 
- [x] zoom using zoom controls triggers action bar hiding 
- [x] compass is hidden behind actionbar 

(this does not happen with Mapsforge maps)

General:
- [x] the current animation is quite "bumpy". Such an animation IMHO must look really smooth or users will not understand what happened on the screen.
- Having tested it a bit, it indeed feels like a great improvement for small landscape layouts, however I personally won't like to see it on tablets or portrait layouts. UPDATE: I'll get used to it. Since the above bugs are fixed, I can live with this feature :)

### How to reproduce?

-

### Reproducible

Yes

### c:geo Version

NB2023.03.06

**Comment by moving-bits** [comment]
Thanks for your report. I dived a bit into the issues and have following findings:

> Google map:
> * zoom by double tap triggers action bar hiding
> * zoom using zoom controls triggers action bar hiding

- `UnifiedMap.GoogleMap` is affected as well by those two
- On doing a double tap, GM fires a single tap + an additional double tap 🤔 - because of this, a cache popup will open if you do a double tap on it!

> * compass is hidden behind actionbar

- `UnifiedMap` is not affected by this, neither in its Google Maps nor in its VTM variant, only GMv2

> General:
> * the current animation is quite "bumpy". Such an animation IMHO must look really smooth or users will not understand what happened on the screen.

Currently I have not programmed any transition explicitly. I would be happy it you could provide a smooth transition.

> * Having tested it a bit, it indeed feels like an great improvement for small landscape layouts, however I personally won't like to see it on tablets or portrait layouts.

Which could be a reason to either make it configurable, or to use the long-tap menu instead of short tap on free space (which would implicitly solve the first two findings as well).

**Comment by MagpieFourtyTwo** [comment]
I like the single tap action, TBH I would not even think about hiding the action bar, if I would have to use more than this single tap or even a sub menu to set/unset it - too much "pain" for too little gain (esp in portrait mode, which is in fact the one I use about 99 % of the time).

**Comment by Lineflyer** [comment]
Stumbled upon the new map feature just now and I agree to @MagpieFourtyTwo that it works quite intuitive with single tap and merges perfectly into the normal map interaction.

**Comment by moving-bits** [comment]
#14079 tries to resolve the following items for GMv2:

> Google map:
> * zoom by double tap triggers action bar hiding
> * zoom using zoom controls triggers action bar hiding

**Comment by moving-bits** [comment]
#14080 attempts to mitigate following issue for GMv2:

> Google map:
> * compass is hidden behind actionbar

**Comment by moving-bits** [comment]
should not have been closed by an "rel. to xxx" comment 🤔

**Comment by moving-bits** [comment]
Argh! Suddenly UnifiedMap GM shows the same problems as CGeoMap GM had before - for whatever reason. I'll dive into it...

**Comment by fm-sys** [comment]
> should not have been closed by an "rel. to xxx" comment 🤔

Problem was "Partly resolve #14066" inside the PR description, as "resolve" is one of the closing keywords.

**Comment by moving-bits** [comment]
> > should not have been closed by an "rel. to xxx" comment 🤔
> 
> Problem was "Partly resolve #14066" inside the PR description, as "resolve" is one of the closing keywords.

ah, will try to remember that

**Comment by ztNFny** [comment]
For me personally action-bar-hiding is a no-go. Toolbar has sooo many buttons I need all the time I never ever want to hide the toolbar. So after first accidentally triggering the hiding I went looking for a preference to disable it - but couldn't find any?? Is there really no such option?

**Comment by fm-sys** [comment]
>  So after first accidentally triggering the hiding I went looking for a preference to disable it - but couldn't find any?? Is there really no such option?

Not yet. But that's how evolution of new features works... Don't expect nightly builds to be usable. Personally, I can live with that feature but haven't missed it either. Anyway, I'm also in favor of a setting option. However it doesn't fall from the sky but needs to be implemented by someone first ;-)

**Comment by moving-bits** [comment]
> > I went looking for a preference to disable it - but couldn't find any?? Is there really no such option?

I'll implement one, default to disabled

**Comment by ztNFny** [comment]
> I'll implement one, default to disabled

Already done: https://github.com/cgeo/cgeo/pull/14089

**Comment by wolverine007** [comment]
Just found this new feature on my nightly version running on my tablet.

Nice function to gather more space, but why are we only hiding one bar?

Hiding the bottom nav bar will add additional space and cgeo is running like a browser in fullscreen mode.

Maybe adding a "fullscreen" button next to the settings button is an alternative to the tap? 

But just an idea...

**Comment by MagpieFourtyTwo** [comment]
IMHO even hiding the header bar makes sense in landscape mode only. cause over there it really eats up a lot of valuable space,

But in portrait mode even this is nothing but a nice gimmick, cause nowadays' displays are *so* big, that in portrait (which I use 99.999% of the time) this little bit of screen gained does not really make a difference.
To talk with numbers: On my mobile, this is 9 mm, which is just a 7.8 % gain - while even under best circumstances (driving north) you just "win" half of it, cause the position cursor is centered usually, i. e. the other gained half lies behind you, anyway.  Thus we're talking about just 3.9 % in driving direction. Maximum Cause if you go east or west, it's just null % at all.
TMALSS: Even hiding the header bar does not really add map information (apart from when you take a country road at 250 km/h ;) ).
BUT: You lose all it's valuable information. Bad trade, IMHO.

WRT the nav bar, hiding makes even less sense, IMHO. In both modes:
In portrait applies the same as for the header bar: Just another senseless 3.9 % to null % for in fact no valuable gain.  But loss of fast switching.
And even in landscape there's no real map gain, as the nav bar is on the left, anyway, where space is no real issue.
And hiding both at the same time / at the same click will even lead to less acceptance, as you cut off two valuable things.
Thus you would need an additional configuration to distinguish between the hides ... too much effort and complexity added to the program and the settings, compared to a neglectable gain.

IMHO: Let's keep it simple, stay with hiding the header bar, my be even in portrait, as it's there already.
And in landscape it's a really neat feature.
But please forget about hiding the nav bar, even more, if it would go with the same click,

**Comment by MagpieFourtyTwo** [comment]
Quoted from @Lineflyer:
> When action bar is hidden and the map is moved the loading indicator (orange running line) is still at its old position and thus free floating on the map instead of attached to the top.

Same applies to the navigation target info header row and the up to three distances.
Scenario to reproduce is the same as in comment [1472138393](https://github.com/cgeo/cgeo/issues/14066#issuecomment-1472138393), plus ...
- select a cache and use as navigation target

Would perhaps make sense to open a dedicated issue ...?

**Comment by murggel** [comment]
I was out today and used that feature, it was working nicely.
The only thing I stumbled over - I needed to use the function to center to my current position quite often.
So if there is a possibility to add this as an overlay button that would be great. Probably configurable which button to show...

**Comment by ztNFny** [comment]
> I was out today and used that feature, it was working nicely.
> The only thing I stumbled over - I needed to use the function to center to my current position quite often.
> So if there is a possibility to add this as an overlay button that would be great. Probably configurable which button to show...

I'm afraid we'll end up with the whole toolbar as overlays... I'm afraid of the effort involved in that especially in maintenance.
As an alternative to hiding the toolbar would it be possible to make its background transparent? That way it and all it's buttons would still be there but you see more of the map.

**Comment by moving-bits** [comment]
> Not sure if this is still open as an issue collector for this new feature, else feel free to move into a dedicated issue:
> 
> Problem: When action bar is hidden and the map is moved the loading indicator (orange running line) is still at its old position and thus free floating on the map instead of attached to the top.

I've created a separated issue for it for easier tracking (#14133)

**Comment by fm-sys** [comment]
Let's close here and discuss the remaining things in #14161
