### ISSUE TITLE
Add "last logs smiley row" to configurable info items

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14084]
Addition request regarding cache list info items:

> Although this is already closed:
> I would like to see the "last logs smiley row" in there :)

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/13278#issuecomment-1465049374_

**Comment by MagpieFourtyTwo** [comment]
Isn't it that live lists are built from light requests, which do not contain logs?
And in lists of offline stored caches, the last logs info is most probably not up-to-date, anyway.

My point: If the above is correct, the "last logs smiley row" is at least questionable without a full data request / update.

So, should c:geo really pretend to know them and present this IMHO important piece of information as if it's real and reliable,
although it is well known that this isn't true in most cases?

**Comment by Lineflyer** [comment]
> My point: If the above is correct, the "last logs smiley row" is at least questionable without a full data request / update.

Sure: 
It only represents the same data you have within the cache. That limitation also counts for live map popup and other places, where we visualize such data.
And you are also right, that on search results ("light caches") the information is currently not present.

Same applies for all other info shown on the list info. Of course this other data (such as D/T, size, Premium state) don't typically change over time. Also the deactivation state is not shown in lists until refresh....meaning, its probably not unexpected by the user that the need to refresh to get up to date info.

Still if you e.g. planning a cache round and collect your list for today its nice to see directly in your list, whether there is any cache potentially no longer logable.

**Comment by MagpieFourtyTwo** [comment]
IOW: "last logs smiley row" in offline lists only?
Over there the user may be aware of potentially not up-to-date data anyway (same like favos etc.)

**Comment by Lineflyer** [comment]
> IOW: "last logs smiley row" in offline lists only?

Yes, because for all other lists this might not be available or only be available for some caches (i.e. those already stored but also returned in map lists or search results, etc.).

**Comment by ztNFny** [comment]
Online-list may also contain stored caches that have this info available, so i don't see a point in differentiating between list types. If the info is not available for a specific cache just show a placeholder.

**Comment by ztNFny** [comment]
I'm thinking about how to do this in a space-saving way. Showing the full smileys from details/pop-up needs too much space IMHO.

Could be a rectangle of (numbers just examples) 8px height, 24px width and each log is represented by a 3px wide section of the log entries corresponding color.
Paint mockup attached![IMG_20230315_191906.jpg](https://user-images.githubusercontent.com/1258173/225405619-39d6b9e7-139d-4e2e-ae2f-2f875cbd2675.jpg)

**Comment by MagpieFourtyTwo** [comment]
Saving space is generally a good idea, but I'm not a fan of displaying the same information differently in different places, esp. if it's about symbols anyway.  Using different symbols just leads to confusion.

Perhaps alternate solution:  Instead of "😊😊😊😊😊" perhaps just a "5😊"?

**Comment by ztNFny** [comment]
As it's customizable anyway we could just offer 2 versions: full (same as pop-up) and compact

**Comment by moving-bits** [comment]
Supporting the compact version _can_ be done, but would be a completely separate thing, as cache list info currently is just a string, put together in a very different place than where the several info icons (tb, favos, gc vote) are build. Is it worth such a code duplication?

**Comment by ztNFny** [comment]
But the "full" version is also not just a string? So both would require a special implementation that's not covered by what's available now.

**Comment by MagpieFourtyTwo** [comment]
@moving-bits 
> Is it worth such a code duplication?

Doubt it - for the reasons already mentioned in [1468863270](https://github.com/cgeo/cgeo/issues/14084#issuecomment-1468863270). Therefore I would keep it as simple as possible.

As for me: I would place the 5 log icons (BTW: not condensed, anyway, in order to a) get a more unique column layout and b) because of faster recognition of the number of positive finds) to the very left of the 2nd row, right before the enumeration of lists (which usually leaves some unused space, anyway).
