### ISSUE TITLE
Different layout for CheckableItemSelectActivity 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14087]
### Describe your problem!

When opening the cache list info configuration for the first time, nothing is preselected. When leaving the activity again, the current state will be stored which leads to information being missing in CacheListActivity. 

### Reproducible

Yes

### c:geo Version

2023.03.12

### Additional Information

Two more things (unrelated to the main issue, sorry that I was to lazy to open separate issues):
- There could be a bit more margin at the left
- instead of having an "add" button for every element, it's IMHO more common to have two sections "selected items" and "available items" where all elements can be moved between those two sections.

**Comment by fm-sys** [comment]
> instead of having an "add" button for every element, it's IMHO more common to have two sections "selected items" and "available items" where all elements can be moved between those two sections.

MS paint draft:


![grafik](https://user-images.githubusercontent.com/64581222/224553462-f5e181d7-a2ef-4336-9737-472f3e08ba20.png)

**Comment by moving-bits** [comment]
> > instead of having an "add" button for every element, it's IMHO more common to have two sections "selected items" and "available items" where all elements can be moved between those two sections.
> 
> MS paint draft:

Do you have an idea how to achieve this?

I can add "virtual" elements into my `RecyclerView` representing category titles (maybe even apply a different layout, remove buttons no longer needed, disable dragging for those elements), but that looks quite "hacky" to me. And one can move an element above the "Available" entry, which would be no valid state. Does `RecyclerView` have an option to support categories?

**Comment by moving-bits** [comment]
I'm making some progress on the RecyclerView. Which way would be preferable?
||left|right|
|---|---|---|
||![image](https://user-images.githubusercontent.com/3754370/224836810-e8a4f82f-86c4-45be-9d7d-f8de571cfa75.png)|![image](https://user-images.githubusercontent.com/3754370/224836831-2a454847-c256-4416-a93b-2f60cfb9f724.png)|
|header|textSize_listsPrimary, colorText_listsPrimary|textSize_headingPrimary, colorText_listsPrimary|
|element|textSize_listsSecondary, colorText_listsSecondary|textSize_listsPrimary, colorText_listsPrimary|

**Comment by fm-sys** [comment]
Really cool! I would probably go with the left one...

**Comment by moving-bits** [comment]
Only thing is the first heading: I can either exclude it from the RecyclerView layout, which would make it stay at the top, even if the list below scrolls into the "Disabled Elements" part, or I can leave it as regular element, which means other entries can be dragged above. 🤔 
Or one would need to extend `ManagedListAdapter` to suppress dragging for some elements.

**Comment by fm-sys** [comment]
Seems like there isn't an easy way like listview.addHeaderView(). 

What about setting the RecyclerView to `wrap_content` and place it together with the header inside a scrollview. This should IMHO work...
