### ISSUE TITLE
User defined waypoint lost if user defined coords are set on website

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14100]
### Describe your problem!

Reported on support mail and reproducible for me:

This affects the OC connector only AFAICS.

User defined waypoints in c:geo are deleted, once you refresh the cache when there is a coordinate stored in the personal note.

### How to reproduce?

- Open OC10914 in c:geo
- There is no additional waypoint in c:geo
- Create a user defined waypoint in c:geo
- Go to the opencaching website and store a coordinate in the personal note section:
![image](https://user-images.githubusercontent.com/949669/225120946-10c721c6-c9e9-469d-a1c5-b4970b195a79.png)

- Refresh the cache in c:geo

### Actual result after these steps?

The stored coordinate from the personal note is shown in the usual way, but the previously stored user defined waypoint is gone.

### Expected result after these steps?

Retrieving coordinates from user note should not alter or remove any other waypoints of the cache.

### Reproducible

Yes

### c:geo Version

2023.03.14-NB and current release

### Additional Information

Support ticket 779643

**Comment by murggel** [comment]
Should the stored coordinate from the personal note be interpreted as new original coordinate?

**Comment by murggel** [comment]
FYI: Reproducible also for caches with owner-defined waypoints 
e.g. OC164ED

**Comment by murggel** [comment]
PR #14116 should fix that

to discuss, if the coordinates from the user-coordinates on website should be overtaken in c:geo as modified cache-coordinates
