### ISSUE TITLE
Show detailed find list on home screen

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14105]
### Tell us your idea!

User request on support: Optionally display a detailed find list on home screen.

### What solution would you suggest?

"Maybe you could add something like detailed finds instead of total finds. 

Detailed finds in settings to activate and you get a list on your home screen with every type of cache you found and the amount of it. 

This would be pretty neat and interesting for some people too."

### Is there an alternative?

- leave it as it
- make separate view for detailed found info
- with or without config setting

### Additional Information

ticket 747375

**Comment by Lineflyer** [comment]
> leave it as it

My vote

**Comment by ztNFny** [comment]
If we start integration this one statistic we'll end up with many. Not saying we shouldn't do it, but need to be aware of what this would likely lead to.
Cgeo would probably become a second project gc.
Ok, I'm saying I'm against it 😉
