### ISSUE TITLE
Have an option to show complete hint from compass

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14108]
### Tell us your idea!

A user on support mail contacted us with an improvement proposal:
When using the c:geo compass, the user can use the action bar to show the hint for the cache. Unfortunately longer hints are cut off and there is no way to show them completely.

Example cache GC3BTQD
![SmartSelect_20230316_190742_cgeo](https://user-images.githubusercontent.com/949669/225595583-1abf8c27-0b59-4bd2-b651-f8f6dac02e53.jpg)

### What solution would you suggest?

Make this toast message tap aware, which then optionally triggers a new window showing the complete hint.

### Is there an alternative?

Always show the hint in a dedicated window and not use the size limited toast message. This has the disadvantage, that the compass cannot be continuously used.

### Additional Information

Supoprt ticket 397622

**Comment by moving-bits** [comment]
Another alternative could be to use a dedicated `TextView` within the compass layout which gets activated when user requests to display the hint. (That's similar to what we do in cache popup.) That way hint text would not be cut off, and compass would still be functioning / would not be hidden by a separate cache hint popup window.
