### ISSUE TITLE
Importing via send2geo doesn't update existing 

### ISSUE THREAD

**Issue by valentijnscholten** [cgeo/cgeo#14110]
### Describe your problem!

- Update coordinates on cache 1234 on geoaching.com
- Send the cache via send2geo
- In c:geo open a list with stored caches, which inclused cache 123
- Import from send2geo
- Observe cache is imported, but details / coordinates are not updated.

### How to reproduce?

see above

### Actual result after these steps?

see above

### Expected result after these steps?

When a cache is imported via send2geo and it already exists in c:geo it should be refreshed and coordinates should be updated.

### Reproducible

Yes

### c:geo Version

2023.02.25

### System information

```text
Pixel 7 (up to date)
```

### Additional Information

According to https://github.com/cgeo/cgeo/issues/1894 this should work.

**Comment by MagpieFourtyTwo** [comment]
Same over here:
1. stored a GC offline in c:geo (this afternoon)
2. changed coords and PN on gc.com right now
3. on gc.com: ``send2cgeo``
4. in c:geo: ``Import`` => ``Import from send2cgeo``
5. cache gets imported ...
6. checking coords and PN in c:geo: nothing changed.  :/

IOW: Confirmed with today's nightly (2023.03.18-NB-f73cf2a).

**Comment by murggel** [comment]
PR #14138 should fix that
