### ISSUE TITLE
Design pattern idea for unified map 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14113]
In our last dev meeting, I had briefly discussed with @moving-bits how we could decouple parts of our unified map implementation in a better way than it is done in CgeoMap / NewMap. I had promised to think about it a bit, and that's what I came up with:

At almost all places in cgeo we currently trigger UI updates by actively calling a method after data has changed.
However, AndroidX provides many smart features to write event driven code (observer pattern), which would IMHO enable us to write code which is cleaner and easier to understand.

In short, I recommend to write a data holder class based on `ViewModel`, in which all fileds are wrapped into a `MutableLiveData`. 

Advantages:
- Moving all data into a ViewModels will allow us to cleanly decouple parts of unified map, even if they need to share data between each other 
- ViewModels are lifecycle aware, so the data will survive layout changes automatically 
- ViewModels will unregister listeners automatically when activity is shut down, which avoids memory leaks 
- MutableLiveData is a wrapper class which provides an observer based interface for listening to data changes. 

Ivve found a rather good article describing the background of using LiveData: (sample code is written in kotlin, but it works with Java in the very same way)
https://medium.com/mobile-app-development-publication/understanding-live-data-made-simple-a820fcd7b4d0

Very detailed Java tutorial:
https://betterprogramming.pub/create-an-app-that-uses-livedata-and-viewmodel-in-java-f8086ca94229

Side note: I haven't used view models myself before, but I just tried it out in one of my private projects and it was a pleasure to work with ViewModels and MutableLiveData.

**Comment by eddiemuc** [comment]
Does this mean that current development on unifiedmap should be stopped until this is sorted out?

**Comment by fm-sys** [comment]
> Does this mean that current development on unifiedmap should be stopped until this is sorted out?

Development doesn't need to stop, but at least thats the reason why I was wondering how you want to build one layer which works across all 3 map implementations (https://github.com/cgeo/cgeo/pull/14096#issuecomment-1465744333). I would suggest to use the GeoItemLayer only for unified map, so that we are free in terms of code design and don't have to fear that we'll break our current maps. Or we could backport the design pattern to our old maps, which however seems to me like quite some unnecessary additional effort...

If you are interested and we want to go with it, I could provide a MVP implementation of my idea based on the current state of unified map (as time permits of course).

**Comment by eddiemuc** [comment]
> thats the reason why I was wondering how you want to build one layer which works across all 3 map implementations.

If we want to change code design from scratch for unified map then you have a valid point here. 

In the sense of architecture the new geoitemlayer ia a pure "view" component which doesn't contain business logic and just displays geo-objects on a map. It should integrate well with the suggested pattern. If You want to do a MVP I look forward to that.

**Comment by fm-sys** [comment]
> If we want to change code design from scratch

At least I feel like development of unified map is a unique opportunity to do it better without much additional development effort.

> the new geoitemlayer ia a pure "view" component [...] It should integrate well with the suggested pattern. 

Yes, already followed your development progress on geoitemlayer. Looks really promising!

> If You want to do a MVP I look forward to that.

Ok, I'll try to find time ;)

**Comment by eddiemuc** [comment]
Just fyi: I am pausing efforts to integrate new geoitemlayer into an map until discussion about new architectural design is concluded.

**Comment by fm-sys** [comment]
Finally, I found time to finish an example implementation (PR #14159). I'd be happy to see feedback about it :)

**Comment by fm-sys** [comment]
MapsforgeVtmView and GoogleMapsView are currently not inherited from an android UI class. (Especially not extending `View` like the name would suggest.) Both classes provide custom lifecycle methods, which need to be called manually. Already since Android 3.0, there is a component called `Fragment`, which is intended to modularize parts of an Activity, and we have already used it in other places of c:geo. It seems to me, that it would be a good idea to wrap both map implementations as `Fragment`. 

Out of interest (and to avoid frustration): was there a specific reason why Fragments were not used in the first place?

If there was no reason not to use them, I would like to give it a try...

**Comment by moving-bits** [comment]
> Out of interest (and to avoid frustration): was there a specific reason why Fragments were not used in the first place?

no specific reason other than the old map implementation used a similar naming and delegation scheme, but derived their "xxxMapView" classes from map type-specific `MapView` classes with pretty different implementations

> If there was no reason not to use them, I would like to give it a try...

please go ahead. I'm glad that you guys with more knowledge of Android architecture fix those things in this relatively early stage. Thanks for diving into it!

**Comment by moving-bits** [comment]
One question came to my mind today regarding `LiveData`: 
We had a discussion recently about whether to store the individual route into a bundle in `saveInstanceState`, as it contains a list of points for the whole calculated route, which may get pretty large on longer distances, possibly breaking the transaction stack with `TRANSACTION_TOO_LARGE` error. Finally we decided to remove it from the bundle. 
Now, if individual route is included in `LiveData`, and `LiveData` handles activity states, may this error come up again for `UnifiedMap`?

**Comment by fm-sys** [comment]
To be honest, I'm not entirely sure how these components work internally. As far as I understood, the activity is only used to register und unregister observers automatically depending on lifecycle, however `LiveData` and `ViewModel` don't hold an activity reference itself and thus store data decoupled of the activity. So it should be safe to store larger amount of data there.

**Comment by fm-sys** [comment]
Info:

I'll try to do the migration towards fragments today. Please don't make changes at the unified map code for the time being. Thank you!

**Comment by fm-sys** [comment]
ToDo - things which worked before I started touching unified map:


- [ ] Re-enable Tap handling
- [ ] Re-enable actionbar hiding
- [ ] Re-enable LoadInBackgroundHandler / MapsforgeGeoitemLayer
- [ ] Re-enable distance view 
- [ ] Refactor MapsforgePositionLayer to use geoitemlayer

**Comment by fm-sys** [comment]
As discussed in the dev meeting, I summarized some of my thoughts here:
https://github.com/cgeo/cgeo/wiki/UnifiedMap#architectural-design-decisions

**Comment by fm-sys** [comment]
All suggested things have been done... So let's close this rather unspecific issue.
