### ISSUE TITLE
question, formula with 2 letter variables

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#14124]
I have a formula like N 52° ((py+px+qy-ry-sy-ty-uy
I enter the variables px,py,qx,qy...
The formula calculator is asking for values of p,q,r,..x,y.. and wants to concatenate p and x to px.
I thought, that if there is a value for px, that should overwrite p and x as separate vaiables. (That's my request)
Is there a way to show the formula the px is one variable?
Unfortunately the manual is not up to date.

**Comment by eddiemuc** [comment]
> I have a formula like N 52° ((py+px+qy-ry-sy-ty-uy

You have to prefix variables with more than one letter with $. E.g.

`N 52° (($py+$px+$qy...`

**Comment by eddiemuc** [comment]
> Unfortunately the manual is not up to date.

From https://cgeo.droescher.eu/en/cachevariables:

![Screenshot_2023-03-23-21-22-24-13_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/6909759/227344196-8c45d7f4-a6fe-4f73-bcc3-0b60e7f5cfd6.jpg)

**Comment by geocachermgo** [comment]
Thanks!
