### ISSUE TITLE
Loading indicator in wrong place when ActionBar is hidden on map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14133]
_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/14066#issuecomment-1472138393_

Problem:
When action bar is hidden and the map is moved the loading indicator (orange running line) is still at its old position and thus free floating on the map instead of attached to the top.

Reproduce:
- Open live map (affects both Google and OSM)
- Tap to hide action bar
- Pan the map to trigger loading of caches

Result:
- Action bar appears where it used to be with actionbar

Expected result:
- Action bar should be shown on top border of the map or be omitted completely (if action bar is currently hidden), which I would personally not prefer.

**Comment by MagpieFourtyTwo** [comment]
Same applies to the navigation target info header row and the up to three distances.
Scenario to reproduce is the same as before, plus ...

- select a cache and use as navigation target

**Comment by MagpieFourtyTwo** [comment]
May possibly make sense to correct the "centered map position" in the same go:
While the header bar is visible, it is not centered on the map, but centered relatively to the whole display,
which puts it put of center for about 7 mm (measured on a 6.3" display) and about another ~2 millimeters,
if the navigation target info line is shown (although this is worth discussing, as this line is semi-transparent).

**Comment by moving-bits** [comment]
The first two issues (loading indicator position and distance info positions) are being addressed by #14134.

> May possibly make sense to correct the "centered map position" in the same go: While the header bar is visible, it is not centered on the map, but centered relatively to the whole display,

This is a bit harder to address and should be put into a separate issue. The position indicator is placed into the center of the map (whether the whole map is visible (action bar hidden) or not (default). Ideally we would detect the direction of travel, rotate the map accordingly, and put the position indicator in the lower third of the screen. Currently not all map types do support auto rotation, and even on those supporting it it can be disabled, therefore position indicator is placed in the center of the map. To avoid the map "hopping around" on hiding/enabling the action bar, map location is fixed, thus the position indicator is "out of center" now if the action bar is hidden.

**Comment by MagpieFourtyTwo** [comment]
This ...

> The position indicator is placed into the center of the map (whether the whole map is visible (action bar hidden) or not (default).

... I would consider a bug, cause map center is not map center, when position is "centered" on map.  ;)
And I guess this can easily be corrected, at least way more easy than to implement the second point ...

> detect the direction of travel, rotate the map accordingly, and put the position indicator in the lower third of the screen

... which I would consider a feature request (for a feature which at least me BTW does not need at all - I like "North Up" way better, cause a rotating map makes it hard to keep track of my movement direction resp. my position in the real world; moreover the orientation sensors are kind of unreliable, and nothing is worse than a map, nervously rotating back and forth all the time).

WRT your last point:

> To avoid the map "hopping around" on hiding/enabling the action bar, map location is fixed, thus the position indicator is "out of center" now if the action bar is hidden

If it would only be like that - cause the position marker is *not* out of center if the action bar is hidden, but it's out of center in the *default* mode, i. e. if the action bar is visible. And IMO position should be correct in default mode, shouldn't it?  ;)

**Comment by MagpieFourtyTwo** [comment]
> The first two issues (loading indicator position and distance info positions) are being addressed by https://github.com/cgeo/cgeo/pull/14134.

Seems to work. Fine. Thx!  :)
