### ISSUE TITLE
Editing route sometimes leads to invalid lines

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14135]
### Describe your problem!

Stumbled upon this during my last cache tours: Editing an individual route can lead to invalid lines being drawn on the map. Closing and reopening the map fixes it. Happend with Mapsforce `NewMap`, have not yet tested against other map types.

Have observed this in both current release 2023.02.25 and current state of `master`, but do not remember having seen this in older releases of c:geo.

### How to reproduce?

Does not happen always, but some relatively safe way to reproduce it is:
- create an individual route with a couple of entries (four seems to be enough)
- edit individual route and move one point from close to one end to close to the other (eg: fourth point of a four point route to second position) and save changes

### Actual result after these steps?

- sometimes the new route shows invalid lines
- closing and opening the map fixes it (as well as opening and closing route edit does)

Example:
- created a route with four points in order 1-2-3-4
- moved the last point to second position (creating 1-4-2-3 in original numbering)
- but it looks like the route is 1-3-2-4 or 1-4-3-2 in original numbering

|before|after edit|after closing/opening map|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/227721711-1440c949-5ca6-40e2-8d4a-6bd967b48098.png)|![image](https://user-images.githubusercontent.com/3754370/227721504-686779dc-94d8-4a27-8a9c-4c06307f40ff.png)|![image](https://user-images.githubusercontent.com/3754370/227721826-3b0c728d-cf85-4617-9828-89ffcd49f173.png)
|see (a)|see (b)|see (c)|

a) numbers indicate cache order within route
b) see the extra line between (original) points 2 and 3
c) numbers indicate cache order within route; extra line is gone

### Expected result after these steps?

correctly update map lines for route

### Reproducible

Yes

### c:geo Version

2023.02.25

### Additional Information

Update: Seems to be OSM-specific, was not able to reproduce this behavior on GMv2 map

**Comment by eddiemuc** [comment]
A guess what might happen here:

I remember from code that in a multi-cache-route a route is calculated between every cache-pair along the route (so-called segments), then those segments are drawn. End of previous segment is connected to beginning of next segment via a straight line.

Using your graphical examples, original point numbering and image b):
* Segments should be 1->4, 4->2 and 2->3.
* But probably segments are 1->4, 4->2 and 3->2

Meaning: probably the segment between 2 and 3 is calculated in the wrong direction, and the wrong line is the connector line between the end of segment 4->2 and beginning of 3->2 ?

**Comment by moving-bits** [comment]
Did a `git bisect` and some addition testing:
- This bug seems to be a side-effect of #13360
- Only `NewMap` seems to be affected, but not GMv2 (which would be consistent with the commit identified by `git bisect`

I'll dig in a bit more deeply...

**Comment by ztNFny** [comment]
I have this issue pretty consistently with route optimization on old OSM map - if it helps.
