### ISSUE TITLE
Not possible to import bookmark list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14167]
While the uploading of caches to a bookmark list is broken since quite a while now (see corresponding issue), I do now also have the problem, that I cant import any bookmark list.

Once tapping the download button the gpx import starts but stops shortafter with some GPX error message.

Writing from field therefore no screenshots...

2023.04.07-NB

**Comment by ztNFny** [comment]
Very strange, cgeo receives the gpx file with
Content-disposition: attachment; filename=BMxxxx.gpx
Content-Type: application/gpx+xml
And the body is a valid gpx. So all looks good from the server response side of things.

From the error message i'd guess instead of gpx we're expecting a zip?

**Comment by ztNFny** [comment]
here's the screenshot of the error message:
![image](https://user-images.githubusercontent.com/1258173/230727266-662573c3-9949-46b9-9468-f47bc57492fe.png)

Downloading a list provides a gpx file. Not sure whether that used to be a zip before.

**Comment by ztNFny** [comment]
fixed by #14168 and #14169

**Comment by moving-bits** [comment]
> fixed by #14168 and #14169

FYI: If you put "fix #xxx" into your commit message GitHub will auto-close this issue as soon as the related PR gets merged to `master`.
