### ISSUE TITLE
Refresh all caches on live map

### ISSUE THREAD

**Issue by gustonator** [cgeo/cgeo#1416]
Hi, 
I don't know, if this was already here (I couldn't find it) but I would really appreciate, if you would to build in a function/button for refreshing all caches on the Live map:

The Problem:
I have stored a aprox. 1 year ago all caches few kilometers around the place I live. in this time, some of them didn't exist anymore, or the stored ones have and old logbook. now I need to Refresh them all, but I don't want to refresh them one-by-one. I have here aprox. 300 cashes around and it would be very time consuming. It would be great, if I have a button, and all the cashes on the Live map screen would be refreshed.

I think this isn't a big deal to build in this function. What do you think ?

Sorry for my english :)

**Comment by Lineflyer** [comment]
Currently the mentioned needed changes are donw:
- Show as list is now always enabled as soon as live loading is done
- Storing caches from live map now (optionally) asks for the list to be stored to.

Closing.
