### ISSUE TITLE
[Nightly] "Last logs smiley row" gets truncated, if the list of smileys hits EOL

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14163]
### Describe your problem!

If the row of smileys does not fit completely into the current line, some smileys get lost.

### How to reproduce?

1. Go to ``Settings`` => ``Appearance`` => ``Configure list info lines``
2. Set ``Active Elements`` in a way that ``Recent Logs`` will most probably be the last item of the line,
    *but* it should not always entirely fit in (so "normally" you would get a CR/LF somewhere inside of the smiley row).
    On my display over here, for example: ``Difficulty``, ``Terrain``, ``Size``, ``Recent logs`` ... (afterwards whatever you like)
3. Open any list containing offline stored caches with at least 8 logs (current number of smileys to be displayed)
4. Check the row of smileys ...

### Actual result after these steps?

- When the smiley row does not fit into it's configured line completely, this line will show no smileys at all,
   and the second line just shows *some* smileys.
- The few ones that will be shown, are the ones from the *end* of the "original" smiley row
   (i. e. if there are just two smileys shown, these are smiley # 7 and # 8 out of 8)
- Seems as if the *more* free space is in the "initial" line (where the first smileys should have gone to),
   the *less* smileys are shown in the second line.

### Expected result after these steps?

The "row of smileys" should ...
- *either* be wrapped correctly at the end of the line ...
- *or* go completely to the next line (which I BTW would call the better solution)

### Reproducible

Yes

### c:geo Version

2023.04.03-NB-22c32ee

**Comment by moving-bits** [comment]
I can reproduce the behavior. `SpannableString` seems to suppress all `ImageSpans` that are at the end of a visible line (which has already some other text in it) and only print those at the beginning of a new line. Need to investigate further to find a mitigation.
(Same for the second part - don't know if an `ImageSpan` can get some extra format to adjust line height.)

**Comment by MagpieFourtyTwo** [comment]
> don't know if an ``ImageSpan`` can get some extra format to adjust line height.

If not, perhaps the icons themselves can get a few extra (transparent) pixels at their top, to increase distance to the previous line?

And as we're pixel nitpicking anyway ;) ... with text before and/or after them, it's just the other way round,  Then the smileys are a little bit too low.  Perhaps you can check on the fly how it looks if ``ImageSpan`` uses ``ALIGN_CENTER`` ...?  ;)

But, this is of course *really* nitpicky. The wrap bug should of course have first priority.

**Comment by moving-bits** [comment]
Ok, found some mitigation to solve both issues:
`ImageSpan` elements need to be separated by a different span to avoid truncation on partially used line when encountering a line break, so I add a small text after each smiley, formatted in background color (to make it invisible). This text not only separates the `ImageSpan` elements, but also adjusts line height. For Android SDK versions 29+ I added vertical centering of smileys (not supported on API < 29).

Resulting look is like this:
![image](https://user-images.githubusercontent.com/3754370/230787550-6f883e6e-753c-4a67-9eb6-266dccf1558b.png)

**Comment by MagpieFourtyTwo** [comment]
Something weird happened ... faces seem to bee too happy, jumped as high as possible:  ;)

![Facejumping](https://user-images.githubusercontent.com/9889015/231724858-c2c3b2d4-1cb4-4626-aec4-67692f7988f9.jpg)

Info Line config: Difficulty, Terrain, Size, Event date, Hidden month, Newline, Recent Logs, Other lists

Same happens if I remove the "Newline". A second "Newline" does not change anything neither.
If I put s/th before the Recent logs (in the very same line), the horizontal position of the smileys seems to be correct, but they still show up in the very first line, covering the text which is displayed there:

![Facejumping 2](https://user-images.githubusercontent.com/9889015/231728642-d193ffa1-eee3-417b-bc06-f56daf9a220b.jpg)
