### ISSUE TITLE
Offline logs - make them easier to find

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#14179]
### Tell us your idea!

When the front page says "xxxxxx finds + y logged offline", the route to find the "y" offline logs is not intuitive. It should be made more obvious.

### What solution would you suggest?

Maybe you could tap on the "y offline" text to see them.

### Is there an alternative?

Just carry on telling people to go to history / filter/ "has offline log = yes"

**Comment by moving-bits** [comment]
duplicate of #12151, so let's close here
