### ISSUE TITLE
Individual route: Sorting waypoints produces pointless bee line from 2nd back to 1st waypoint

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14185]
### Describe your problem!

Had a bicycle round trip route today, like so:
1. Home
2. Cache 1
3. Cache 2
4. User defined Cache (Ice Cream Dealer ;) )
5. Point near Home (about 10 m away)

Length of the route displayed: 32 km

Then manually sorted the waypoints, in fact swapped 3. and 4., then went back to the map and noticed that the length of the route, which should have been shorter now, had *increased* to 42 km!  Simply impossible.  Took a moment till I saw that now there was an additional bee(!) line (although still in ``Bike`` mode) from "2. Cache 1" to "1. Home". TMALSS: Only chance to get rid of this senseless bee line was, to switch routing style to e. g. ``Walk`` (i. e. force a recalculation), which made the bee line disappear, and then back to ``Bike`` again.

Strange.  But to my big surprise even reproducible.

### How to reproduce?

1. Create a ``Bike`` round trip route with 5 stops
2. Swap stop 3 and 4
3. go back to map and look at route

### Actual result after these steps?

An additional bee line shows up, over here from second to first point of your trip, although there is no second occurrence of this first point.

### Expected result after these steps?

Route should be calculated and drawn correctly (and as it in fact is in the route's waypoint list).

### Reproducible

Yes

### c:geo Version

2023.04.10-NB-7033ce5

**Comment by moving-bits** [comment]
looks like a duplicate of #14135, which I have merged a fix for just today, should be in the next nightly. I'll leave this issue open here, so that you can cross-check and report back whether this fix works for you. Thanks.

If it is actually the same as #14135, then
- it should happen on OSM only, but not on GM
- should be resolvable by closing and reopening the map after route edit

**Comment by MagpieFourtyTwo** [comment]
Seems to be fixed with [7838ac8](https://github.com/moving-bits/cgeo/commit/7838ac8105522ffd6a8afa8252a660e7c610139a).
