### ISSUE TITLE
Can we rename "Jasmer" to something else?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14182]
> Can we rename "Jasmer" to "Place month" or something similar? Even knowing what the jasmer challenge is I didn't know what to expect from the item, had to add it and see it in action.

Seconded... I would choose "hidden month" instead.

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/14073#issuecomment-1502211534_

**Comment by Lineflyer** [comment]
or "Month hidden"

**Comment by moving-bits** [comment]
or "Hidden Year/Month"
or "Hidden (Jasmer)"
