### ISSUE TITLE
Refresh All Caches Shown Inside "Show As List"

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#14190]
### Tell us your idea!

A few days ago I planned to go into the wild, upfront I opened the target area to see which caches are there.

Cause I am keeping a lot of my extended Homezone offline inside cgeo, I selected the show as list entry for the caches being displayed on the live map to update them, cause the local data was really outdated for that area.

But there was no "refresh all caches" entry inside the manage caches menu available. Only the option to store all shown caches to a new list has been provided. 

### What solution would you suggest?

Offer for the "Show As List"-list entries also the refresh all caches option. 

### Is there an alternative?

Store all caches again into a temporary list

**Comment by ztNFny** [comment]
"Store caches offline -> Refresh and add to list" and add them to the list they're already in

**Comment by wolverine007** [comment]
> "Store caches offline -> Refresh and add to list" and add them to the list they're already in

I am storing them inside different lists, that's the reason for my request.

Big issue to refresh caches which are already shown inside a temporary list?
