### ISSUE TITLE
Wrong permission status for READ_CONTACTS

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14206]
The system information on my device reports:
```
- android.permission.READ_CONTACTS:: DENIED
```

I am however flawlessly using the "open contacts" function all the time, so the permission seems to be granted.
Android 12

**Comment by eddiemuc** [comment]
The cgeo contacts extension ia still active. Technically, this is an own app. This app has the contacts -read permission. Cgeo doesn't have the contacts-read permission. So the displayed System information is correct.

C:geo is prepared however to substitute the cgeo-contacts-addon as soon as minimum API level is high enough

**Comment by Lineflyer** [comment]
Interesting....I don`t habe the addon installed anymore.
So it works without on my device but without permission required...I am confused.

**Comment by eddiemuc** [comment]
Hm okay, thats interesting indeed...

**Comment by eddiemuc** [comment]
I checked AndroidManifest and READ_CONTACTS permission is still commented out there (waiting for minSDK to become 23):

![image](https://user-images.githubusercontent.com/6909759/233440690-9abdb203-7ed6-479d-8e28-44ffbc26fb38.png)

So I really don't know why @Lineflyer s installation works without the cgeo-contacts addon installed

**Comment by eddiemuc** [comment]
...and on an emulator on API Level 31 (Android 12) without the cgeo-contacts-addon installed I don't get the "open contacts" option. Which is correct since the addon should still be needed.

So I don't really know what's happening here.

@Lineflyer if you go to cgeo app settings in android settings, do you see the "read contacts" permission there?

**Comment by Lineflyer** [comment]
While looking for the app permissions I realized I still have the contacts add-on installed. I swear I checked before posting this, but it was not shown at that time.
Anyway, that solves the riddle. Closing here and sorry for the noise.
