### ISSUE TITLE
Anzeige der Landkreisgrenzen auf der OSM-Karte

### ISSUE THREAD

**Issue by emblinux** [cgeo/cgeo#14251]
### Tell us your idea!

Ist es möglich die Landkreisgrenzen (oder auch Gemeindegrenzen in der Schweiz) auf der OSM-Karte anzeigen zu lassen. Das würde mir bei meinen Cachingaktionen helfen.

In der offiziellen Geocaching APP wird das zwar schon gemacht aber mir gefällt CGeo deutlich besser und würde mich dort über so ein Feature freuen.

Ich könnte mir das auch so vorstellen, das man entsprechende GeoJson-Dateien mit den Landkreisgrenzen in einen Ordner packt, die man dann als Anzeige aktivieren bzw. deaktivieren kann.

**Comment by fm-sys** [comment]
Tatsächlich sollte das schon möglich sein. Über die "Import Track/Route"-Funktion können seit neustem auch GeoJson-Dateien angezeigt werden. Alternativ könntest du auch eine offline Karte mit einem speziellen Karten-Theme verwenden, welches die Landkreisgrenzen hervorhebt.

Lass uns bitte wissen, ob das für dich funktioniert und melde dich gerne wenn du weitere Hilfe brauchst. 

---

See also #13793

**Comment by eddiemuc** [comment]
Eine Ergänzung: Landesgrenzen-Geojsons sind vermutlich sehr groß. Das Feature wurde noch nicht für derart große Dateien und Geoobjekte optimiert (kommt mit der unifiedmap).

**Comment by emblinux** [comment]
@fm-sys : Damit hast du mir schon sehr geholfen. Damit bekomme ich genau das was ich gesucht habe. Vielen Dank.
Damit kann der Feature-Request auch geschlossen werden.

**Comment by emblinux** [comment]
@eddiemuc : Ja, da hast du recht, die Dateien sind recht groß. Zumindest, was die größeren Bundesländer angeht. Ich habe mir Deshalb Für jedes Bundesland eine GeoJson-Datei erzeugt. Diese werde ich dann jetzt laden und bei Bedarf das entsprechende Bundesland mit seinen Landkreisgrenzen anzeigen lassen. Auch dir vielen Dank.

**Comment by ztNFny** [comment]
Wo/wie kann man denn GeoJson der deutschen LKs generieren? Idealerweise direkt mit der Info ob man sie schon erledigt hat.

**Comment by fm-sys** [comment]
Just googled for "Deutsche Landkreisgrenzen GeoJson", and already one of first results looks promising:

http://opendatalab.de/projects/geojson-utilities/

You can filter for federal states, configure resolution and select whether you want to see city or county boarders.

**Comment by ztNFny** [comment]
> Just googled for "Deutsche Landkreisgrenzen GeoJson", and already one of first results looks promising:
> 
> http://opendatalab.de/projects/geojson-utilities/
> 
> You can filter for federal states, configure resolution and select whether you want to see city or county boarders. 

I was hoping for something GC-connected to avoid having to manually and again-and-again recreate the work that PGC puts in their masks.

**Comment by fm-sys** [comment]
Feel free to write your own script based on that data, should "just" be a bit of math ;-)

**Comment by ztNFny** [comment]
> Feel free to write your own script based on that data, should "just" be a bit of math ;-)

Done :-P
https://github.com/ztNFny/geocaching_geojson_generator

**Comment by emblinux** [comment]
Sehr schön, ich habe das in mal in PHP konvertiert und funktioniert auch. Wenn man kein Premium-Mitglied bei Project GC ist, dann funktioniert der erste Data-Source-Link leider nicht.

**Comment by ztNFny** [comment]
> Sehr schön, ich habe das mal in PHP konvertiert und funktioniert auch. Wenn man kein Premium-Mitglied bei Project GC ist, dann funktioniert der erste Data-Source-Link leider nicht.

Es gibt diverse Challenges die man als Ersatz nehmen könnte. Muss man halt die Regex etwas anpassen

**Comment by moving-bits** [comment]
> Sehr schön, ich habe das mal in PHP konvertiert und funktioniert auch.

Kannst Du das ebenfalls hier bereitstellen?

**Comment by emblinux** [comment]
@ztNFny : wäre es ok, wenn ich dir das Script schicke und du das in deinem Projekt mit aufnummst? Ich möchte nicht dafür extra ein Projekt anlegen.

**Comment by ztNFny** [comment]
Mach doch ein gist

**Comment by emblinux** [comment]
Ah ok, das kannte ich noch nicht. Danke.
Hier der Link: https://gist.github.com/emblinux/0fb415d4a09004f574e1a174c6eb1295

**Comment by ztNFny** [comment]
Ich hab eine PHP-Version (mit HTML Form) hinzugefügt und Counties über https://project-gc.com/Challenges/GC90TVE/56012

**Comment by ztNFny** [comment]
> Ich hab eine PHP-Version (mit HTML Form) hinzugefügt und Counties über https://project-gc.com/Challenges/GC90TVE/56012
> 
> https://github.com/ztNFny/geocaching_geojson_generator

Kleines Update, dass jetzt eine Datei für gefunden, nicht gefunden und FTF oder T5 erzeugt
