### ISSUE TITLE
Premium-only caches on map

### ISSUE THREAD

**Issue by LayanJethwa** [cgeo/cgeo#14263]
Would it be possible to show the location of PMO caches on the map? You could scrape the cache placement map online with the intersecting circles, then use the midpoints of the circles as positions for PMO caches?

**Comment by fm-sys** [comment]
> You could scrape the cache placement map online with the intersecting circles

Are your referencing to the map which is shown for selecting a position while publishing caches? It is known that the position of PM-only-caches is leaked there, however we will definitely not use this data source.

Reason: 
Actively misusing this data will most probably cause this "leak" (if it can be considered a leak at all) to be fixed, which shouldn't be our interest. The "leak" can be very helpful for basic members if they want to hide they're own caches, so let's not play with it.
Furthermore, if an owner decides to restrict the access to his cache this should IMHO be respected.
Everything else wouldn't be fair.

Please let me know if I should have misunderstood your request.

**Comment by LayanJethwa** [comment]
OK, that does make sense, thanks!
