### ISSUE TITLE
Geojson: fill color

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14264]
Geojson shapes currently show only an outline with a 12,5% fill of the same color.
It should be possible for the user to modify that fill color, just like the outline color can be customized.

An additional "background fill" should be added to the existing color dialog:

![image](https://github.com/cgeo/cgeo/assets/1258173/65b9b92d-13f3-46c3-9780-90b1659c1aa8)

**Comment by eddiemuc** [comment]
Geojson interpretation of c:geo supports styling information as defined by e.g. geojson.io. this includes line color, line width and fill color. Both line and fill color support RGB and alpha channel (e.g. graduate transparency)

**Comment by ztNFny** [comment]
Cgeo allows for defining for the outline a custom color, line width and opacity. The same should be possible for fill.

**Comment by eddiemuc** [comment]
I am not sure I follow. c:geo geojson supports all "simplestyle" attributes as defined by e.g. http://geojson.io. Those include stroke color, stroke width, stroke opacity, fill color and fill opacity. See a geojson example below with screenshot. 

Fill color is of course only applied to polygons (not to polylines).

The default fill color in c:geo however is "transparent". This can be changed to something else if wanted.

Also, there seems to be a bug wrt stroke width, it is far too thin. This must be looked into. But fill seems to be fine.

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "stroke": "#3b12ce",
        "stroke-width": 4,
        "stroke-opacity": 0.6,
        "fill": "#c01b1b",
        "fill-opacity": 0.4
      },
      "geometry": {
        "coordinates": [
          [
            [
              -16.616087218835105,
              28.29083046994647
            ],
            [
              -16.616087218835105,
              28.230549212037232
            ],
            [
              -16.557603500924984,
              28.230549212037232
            ],
            [
              -16.557603500924984,
              28.29083046994647
            ],
            [
              -16.616087218835105,
              28.29083046994647
            ]
          ]
        ],
        "type": "Polygon"
      },
      "id": 0
    }
  ]
}
```

![image](https://github.com/cgeo/cgeo/assets/6909759/dce69289-2512-406e-b504-09e5538aa530)

**Comment by eddiemuc** [comment]
BTW: using simplestyle proerties, one can of course have multiple geojson objects in one file with different stylings/colors/...

**Comment by ztNFny** [comment]
1. Get geojson without Styling Info from http://opendatalab.de/projects/geojson-utilities/
2. Load it in cgeo
Outline is shown and it's assistance can be configured in "route/track options". No fill, no options for full configuration

3. Load same geojson in other viewers
It's shown with outline and fill (in the viewers default colors)

![IMG_20230514_094421.jpg](https://github.com/cgeo/cgeo/assets/1258173/3ba82b83-d2c7-42e8-ad09-37fff0d56b80)

![IMG_20230514_094359.jpg](https://github.com/cgeo/cgeo/assets/1258173/555d3f26-8bb5-49a8-a0a8-876a359c67b0)

![IMG_20230514_094344.jpg](https://github.com/cgeo/cgeo/assets/1258173/f7033444-39c7-466e-be21-f269002b24ab)

**Comment by eddiemuc** [comment]
@ztNFny I think I understand what you mean now: you want the possibility to select the fill color through a c:geo menu correct? Something to be added maybe here:

![image](https://github.com/cgeo/cgeo/assets/6909759/a981b887-3a38-42a0-a072-6dda1cebe071)

That's not what I was talking about at all. I am talking about simplestyle support inside the geojson file.

I corrected some things in handling and also added as default that fill color is a 12,5% transparent version of the stroke color. Defaults are applied to all objects where styling is not set in geojson itself. See #14265 for an example

**Comment by ztNFny** [comment]
yes, I'm talking about those custom color settings. Didn't even know geojson was capable of defining styles before you mentioned it.

That dialog should have an additional "fill opacity" slider imho (default value tbd, both 0% as well as something like 10-20% would be ok I guess)

**Comment by ztNFny** [comment]
current is good enough
