### ISSUE TITLE
Add more and allow custom background maps

### ISSUE THREAD

**Issue by MakiWolf** [cgeo/cgeo#14272]
### Tell us your idea!

Add more and allow custom background maps

Currently only Google, Openstreetmap.org, openstreetmap.de, CyclOSM and offline OpenStreetmaps maps are supported.

But it would be great when there are more aerial images or OpenStreetmap styles are supported.
Also an option to allow custom maps like in Osmand would be nice.

I don't know exactly which ones are license compatible for cgeo or where cgeo has to ask for permission.
This would be a first step to list interesting maps where cgeo has permission to use.

### Is there an alternative?

Currently as workaround we can open in Osmand directly from cgeo to view more and custom online maps.

**Comment by Lineflyer** [comment]
What does your request have to do with background images, or am I missing something?

**Comment by Lineflyer** [comment]
Ah, now I understand. Sorry for my confusion.

Custom map tiles are already covered by this feature request: https://github.com/cgeo/cgeo/issues/3954

Regarding other built in map tile sources we would need a clue of what source specifically shall be supported and (as you wrote) whether the related license is matching our license.

Unfortunately your relatively generic request tends to be open forever if no one knows any map source, which would be applicable. Therefore please bear with me as I close it.
If you have any specific source in mind, which would be helpful and with matching license, feel free to open a specific request providing the needed details.
