### ISSUE TITLE
"keyword" field in search filled with "GC" on going back

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14280]
Go to search
Enter anything in "keyword"
Select one of the caches
Go back
Keyword is now prefilled with "GC"

I remember there being a change that filled the GC for geocode field, seems this wrongly spikes to others as well.

**Comment by moving-bits** [comment]
We are using a suggestions function for both fields (geocode and keyword), which overwrites the content with geocode of selected item. As this may confuse users, we reset this field to the connector identifier from the selected cache ("GC" for gc.com caches). While this behavior is fine for the geocode field, it is confusing for the keyword field.

Resetting the field content to the connector id can be easily suppressed for the "keyword" field, but then the geocode of the selected cache remains in the field. I've found no way yet to keep the search string in the field.
