### ISSUE TITLE
Non-PM Lab Caches: enable "mark as found"

### ISSUE THREAD

**Issue by steve8x8** [cgeo/cgeo#14281]
### Tell us your idea!

While I respect the decision to not make LCs directly accessible in c:geo (#13608), there are multiple ways to load them, even for basic members.

What is missing (now; I'm not sure it was ever there): to be able to mark a LC as "done" ("found", whatever) when all stations have been visited and logged on-line (in the original app). This feature is present for PMs but doesn't interact with Groundspeak at all.

### What solution would you suggest?

Make the LabCache menu item "mark as found" available for everyone, and possible include the LC in field notes.

### Is there an alternative?

Delete the LC, and keep a note on paper that it already has been found (?)

**Comment by ztNFny** [comment]
If you import a GPX containing a AL-Id recognized by cgeo as such you'll have the menu item already.

You didn't provide any info on how you get the AL into cgeo so anything further would be pure speculation...

**Comment by moving-bits** [comment]
To explain a bit in more detail:
When creating the GPX for import, it should contain one cache per Lab Adventure, having a geocode starting with "AL", and the lab stages should be waypoints of this cache. Then c:geo should be able to detect this as a Lab Adventure and you can mark stages as visited as well as the whole cache/Lab Adventure as found/completed.

**Comment by steve8x8** [comment]
Yep, I've found the same when digging into the code..
Please don't change the current handling of unknown connectors as I'll probably stick with that - I haven't found a drawback of that approach yet (compared with `AL` prefix) and really **like** the hexagons.
I don't upload field notes, so GS won't see any of my non-standard finds.
Still I'm wondering why just the `AbstractConnector` gets `supportsSettingFoundState()` set to `false` (ok, that's covering quite a list of cache providers), and none else... but I'm more than fine with that now. There are plenty 2- and 3-letter combos that would count as "unknown" ;)
Thanks for your attention.
