### ISSUE TITLE
load GC PQ preview from map instead of nearest.aspx

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14290]
### Tell us your idea!

For previewing PQs we're currently using https://www.geocaching.com/seek/nearest.aspx?pq= which is one of those old pages with lots of HTML, also limited to 20 results/page.

### What solution would you suggest?

There's also a "preview on map" option, loading to https://www.geocaching.com/map/default.aspx?pq= which loads the actual data as geojson from https://tiles01.geocaching.com/map.pq?pq=..&st=..
This is a "nice" data format (json) and seems to deliver up to 1000 items.

**Comment by moving-bits** [comment]
Hasn't this been fixed with #14296? Then we could close here...

**Comment by bekuno** [comment]
@ztNFny You did not use the autoclose function in your PR. For details see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue.
