### ISSUE TITLE
Message center not prefilled when used from archived cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14303]
### Describe your problem!

A user reported, that he used the "Send message" function to contact an owner of an archived caches.
In contrast to using this function on active caches, the prefilled "Regarding GCCODE: Cache name -" is missing in this case.

### How to reproduce?

- Open an archived cache
- Tap on owner name
- Tap on "Send message"

### Actual result after these steps?

Message center opens but message is empty (no prefill/prefix with geocode and name as usual).

### Expected result after these steps?

Message center opens and message is prefiledl/prefixed with geocode and name

### Reproducible

Yes

### c:geo Version

2023.05.15

### Additional Information

Support ticket 483397

**Comment by moving-bits** [comment]
I have cross-checked with an intent interceptor: c:geo calls "the same" URI for archived as well as for non-archived caches (messagecenter URL + recipientId + gcCode), so the difference comes from server-side and cannot be influenced by us. Therefore closing here.
