### ISSUE TITLE
Certitude icon not shown in listing text

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14304]
### Describe your problem!

A user reported, that on his owned cache, where he uses certitude as cache checker and the corresponding inline picture is not shown in c:geo.

### How to reproduce?

- Open GC80ECK
- Check after text "spoiler:" 

### Actual result after these steps?

The hyperlink is shown but the image after it, is missing (empty).

In your normal browser the image is shown:

![image](https://github.com/cgeo/cgeo/assets/949669/1fd24ba3-a66b-4026-aaa9-318908ce3198)

### Expected result after these steps?

Image should be shown in c:geo

### Reproducible

Yes

### c:geo Version

2023.05.15

### Additional Information

Source is:
```
<p align="CENTER" style="margin-bottom:0.5cm;"><font color="#000080"><a href="https://www.certitudes.org/certitude?wp=GC80ECK"><font color="#000080"><img src="https://imgproxy.geocaching.com/b1e761a0a93d9fb3fca80b8bc5e10d890320db3d?url=https%3A%2F%2Fwww.certitudes.org%2Flogo%3Fwp%3DGC80ECK" align="BOTTOM" width="129" height="129" border="1"></font></a></font>
 </p>
```

The missing file type ending of the linkes image looks suspicious. User fault?

**Comment by eddiemuc** [comment]
The image data delivered is SVG. Try opening this in browser:

`view-source:https://imgproxy.geocaching.com/b1e761a0a93d9fb3fca80b8bc5e10d890320db3d?url=https%3A%2F%2Fwww.certitudes.org%2Flogo%3Fwp%3DGC80ECK`

Deep down in HtmlImage, we use `BitmapFactory.decodeStream` to decode a Bitmap out of the downloaded stream data. My guess is that this method does not support SVG. See here: https://developer.android.com/guide/topics/media/media-formats#image-formats
