### ISSUE TITLE
For unknown DT show "?" in marker

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14316]

**Comment by ztNFny** [comment]
![image](https://github.com/cgeo/cgeo/assets/1258173/0d4d89d4-25e4-472e-beb8-f7385bb12e51)

**Comment by ztNFny** [comment]
@moving-bits did I get that right in the call I'm free to revert https://github.com/cgeo/cgeo/commit/3ddd3ff1 ?

**Comment by moving-bits** [comment]
> @moving-bits did I get that right in the call I'm free to revert [3ddd3ff1](https://github.com/cgeo/cgeo/commit/3ddd3ff1) ?

generally speaking: yes

But it should be combined with a configuration change to inform Codacy etc. that those resources are used, because those 10 or so errors were the reason to write the mentioned PR in the first place.

**Comment by ztNFny** [comment]
> > @moving-bits did I get that right in the call I'm free to revert [3ddd3ff1](https://github.com/cgeo/cgeo/commit/3ddd3ff1) ?
> 
> generally speaking: yes
> 
> But it should be combined with a configuration change to inform Codacy etc. that those resources are used, because those 10 or so errors were the reason to write the mentioned PR in the first place.

Before your change you already added this, didn't it work? https://github.com/cgeo/cgeo/pull/12541

**Comment by moving-bits** [comment]
> > But it should be combined with a configuration change to inform Codacy etc. that those resources are used, because those 10 or so errors were the reason to write the mentioned PR in the first place.
> 
> Before your change you already added this, didn't it work? #12541

Can't remember any more what the remaining error message was. 🤔 (Maybe complaining about using concatenated resource strings?) - Maybe just revert 3ddd3ff1 and see what's coming up. Does not really do any harm anyway, it's just to make Codacy etc. happy.

**Comment by ztNFny** [comment]
> Can't remember any more what the remaining error message was. 🤔 (Maybe complaining about using concatenated resource strings?) - Maybe just revert [3ddd3ff](https://github.com/cgeo/cgeo/commit/3ddd3ff1c7429cd8295948c27d8cfd16cb38c7d6) and see what's coming up. Does not really do any harm anyway, it's just to make Codacy etc. happy.

Seems that the wildcard here doesn't work: `<ignore path="res/drawable/marker_rating_*.xml" />`
After some attempts with other wildcards I've now replaced it with lines for each individual file.

**Comment by moving-bits** [comment]
I've searched current lint messages and here's the item I was looking for. Maybe we can add an exception for this code line:

MapMarkerUtils.java:722,           DiscouragedApi, Priority: Normal
--
Use of  this function is discouraged because resource reflection makes it harder  to perform build optimizations and compile-time verification of code.  It is much more efficient to retrieve resources by identifier (e.g.  `R.foo.bar`) than by name (e.g. `getIdentifier("bar", "foo", null)`).<p>Discouraged  APIs are allowed and are not deprecated, but they may be unfit for  common use (e.g. due to slow performance or subtle behavior).

```
return DrawableCompat.wrap(ResourcesCompat.getDrawable(res, res.getIdentifier(&quot;marker_rating_&quot; + ratingLetter + &quot;_&quot; + r, &quot;drawable&quot;, packageName), null));
```

**Comment by ztNFny** [comment]
But i already did that?

@SuppressWarnings("DiscouragedApi")
private static LayerDrawable createDTRatingMarker(final Resources res, final float difficulty, final float terrain)

**Comment by moving-bits** [comment]
From [one of the recent builds](https://ci.cgeo.org/job/cgeo-CI_PR-build/5063/androidLintResult/source.-2679454015483265956/#722) it looks like you added this for `createDTRatingMarker` but need to add it again for (or move it to) `getDTRatingMarkerSection`.
