### ISSUE TITLE
new numbers emoji category invisible with light theme

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14311]
### Describe your problem!

The new "numbers" emoji category introduced by #14262 and many of its emojis are invisible as text color = background color with light theme. This is with stock Android!

![image](https://github.com/cgeo/cgeo/assets/1258173/fb0b4705-c4d2-49f1-a673-063f1de30755)

### How to reproduce?

-

### Reproducible

Yes

### c:geo Version

2023.06.06

**Comment by moving-bits** [comment]
Light theme hadn't been mentioned so far, but even in light theme, only the emoji picker seems to be affected (at least here in the emulator). Both the emoji marker being displayed in the cache page's header as well as the one being displayed on the map are ok. So it may be an issue with the styles being used for the dialog window (to be tested).

|Cache details|Map|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/732f8d67-c598-447f-815a-a73bff3a7402)|![image](https://github.com/cgeo/cgeo/assets/3754370/2ddb6302-3157-4370-987b-e20767760147)|

Fun fact: If you select such an "invisible" emoji marker and return to the emoji picker again, the emoji will be visible in the dialog's header, but still not in the lower part: 🤔 
|First selection|Reentering selection|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/bbd769b1-08ac-4a6e-addc-eb6e037ecffa)|![image](https://github.com/cgeo/cgeo/assets/3754370/d7e91e76-1fda-43b3-9a94-450f9de9235b)|

**Comment by fm-sys** [comment]
The fix is quite easy, these newly added icons use the font color so set it to black inside the chooser for light theme.

**Comment by fm-sys** [comment]
> > The fix is quite easy, these newly added icons use the font color, so set it to black inside the chooser for light theme.
> 
> Yep, thanks. Your hint "newly added icons use the font color" was the key to fix it. Done with PR #14315

Nice that it works 👍
