### ISSUE TITLE
Decouple init tasks and make sure they are run before any other tasks

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14321]
Coming from the discussion in #14317:

c:geo's initialization and maintenance tasks are part of `MainActivity`, but there are "side-entries" to run c:geo, and #14317 will add another, leading to situations where our init & maintenance tasks are not run at all (if the user never opens the home activity) or only at a later time.

Change this behavior so those tasks are run before any other tasks, but make sure they are not executed every time an activity is started.

One solution could be to extract all init and maintenance tasks which are required for c:geo (and not specific to a certain activity) into a separate method that gets called by all startable activities, and secure this by a flag to make sure it's run only once.

"Startable activities" are (at least) those from bottom navigation:
- home screen
- cache lists ("stored")
- map
- search
- nearby

(feel free to extend this list if required)

Do other intents to be secured in this way as well? E. g. importing a GPX file, importing a downloaded map / routing tile etc.?

**Comment by eddiemuc** [comment]
Wouldn't it be easiest to put all initialization code into the application classes create method?

This would be `CgeoApplication.onCreate`

If I am not mistaken, application is always initialized first and guaranteed to be initialized only once. Regardless of which activity is used for startup.

**Comment by moving-bits** [comment]
Did a quick test by starting c:geo in different scenarios, and `CgeoApplication.onCreate` gets called every time, so this seems to be a viable place to move our global init & maintenance code to. Thanks for the pointer!

**Comment by ztNFny** [comment]
Would this also move the SAF checks to thos new timing? An issue i frequently see is that SAF folders are lost after updates and then starting cgeo from a coord.info link map is broken (due to not being able to access my offline maps). I'll then have to kill and start cgeo from launcher to get to the SAF prompt.

**Comment by moving-bits** [comment]
As discussed in yesterday's meeting:
- move "global" init & maintenance tasks to bottom navigation activities (but not for "side entries" like opening GPX file)
- leave `MainActivity`-specific tasks (like map update check) in `MainActivity`
