### ISSUE TITLE
Improve hidden date filter (for event caches)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14330]
### Tell us your idea!

On support a user wants to use the filtered search to search for events taking place today or in near future.
For this purpose we uses the "filtered search"  , adds cache type = Event and a with "relative to today"-option filter for hidden date.

Unfortunately the hidden date filter does only allow "<3 days in the past" for the hidden date and no future hidden date.

### What solution would you suggest?

For the use case of this users it would be necessary to search for hidden=Today and for hidden dates in the future using the "relative to today" option.

### Is there an alternative?

The alternative would be to use fixed dates, but as the user would like to store and reuse the filter it would only work (without the need of manual correction) if he uses the "relative to today" option.

### Additional Information

Support ticket 991014

**Comment by ztNFny** [comment]
Instead of extending the existing hidden date filter I'd propose a new "future event date" filter. Looking into the future makes no sense at all for non-events and would make the UI confusing.
