### ISSUE TITLE
Non translatable strings showing up on Crowdin

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14337]
### Describe your problem!

A translation contributor on Crowding raised some issues about strange strings showing up.
From what I can see, they are from `settings_startscreen`, and have the content 
![image](https://github.com/cgeo/cgeo/assets/949669/5081381a-53f5-4708-8eeb-559e6facec03)

I guess something went wrong here on our side or those should be into the non-translatable string file?

### How to reproduce?

-

### Reproducible

Yes

### c:geo Version

nightly version ~~2023.05.15~~

**Comment by moving-bits** [comment]
Yes, they are coming from the new startscreen configuration. Wouldn't have expected to see them in translations, as they are just references to existing strings. But anyway, I'll create a PR to add the `translate="false"` flag.
