### ISSUE TITLE
"map" navigation shows popup with parking coordinates

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14344]
In todays nightly pressing the compass icon which in my config is mapped to "map" (default navigation) opens a popup showing the cache and its parking coordinates instead of just drawing the line to the cache.

Showing where a cache is is THE main function of cgeo and this popup, requiring an additional selection - each time the button is pressed, which can be "very often" if you switch between listing and map - adds useless overhead to this.
If i want to draw a line to the parking coordinates i can go to the waypoints and select parking there.

**Comment by ztNFny** [comment]
Seems to be caused by https://github.com/moving-bits/cgeo/commit/2b1d29a48ec545ba9e49beb6036f595cf2fddc21

The only situation where this selection should be shown is DRIVING navigation. not the internal, not walking, ..

Imho that commit should be largely or completely reverted.

**Comment by Lineflyer** [comment]
I agree...its should be only when handing over to third party apps targeted to driving.

**Comment by moving-bits** [comment]
> Seems to be caused by [moving-bits@2b1d29a](https://github.com/moving-bits/cgeo/commit/2b1d29a48ec545ba9e49beb6036f595cf2fddc21)

Yes, in response to feature request #13540

> The only situation where this selection should be shown is DRIVING navigation. not the internal, not walking, ..

ok, but how to identify whether the user wants "driving navigation"?

> I agree...its should be only when handing over to third party apps targeted to driving.

So far we only have one or two navi apps explicitly named as being for "driving", while we have many more apps being used (at least also) for driving. How can we distinguish that use case without having to duplicate all menu entries?

Maybe restrict the PR to be available for the few navi apps explicitly stating "driving" in their name and for the "other external app" entries (as they are most likely an interface to other apps like "Here we go" etc.).

**Comment by ztNFny** [comment]
> Maybe restrict the PR to be available for the few navi apps explicitly stating "driving" in their name and for the "other external app" entries (as they are most likely an interface to other apps like "Here we go" etc.).

See my PR from 10 min ago:

fixes https://github.com/cgeo/cgeo/issues/14344 by offering target selection only for those navigation apps that are explictily targeted towards driving

Apps with explicit "Driving" navigation mode in cgeo:

Google Navigation (Driving)
Sygic (Driving)
Other navigation apps not implementing this right now:

Maps.me
OruxMaps
OsmAnd
Locus
**If we want to implement it for those other apps I suggest adding a second profile for them to explicitly set driving mode, then implement it for that.**

**Comment by ztNFny** [comment]
Showing it "not often enough" is IMHO waaay better than showing it once to often, considering that "once" in code means "maaaany times a day" for the user.
