### ISSUE TITLE
wrong icon from cache for 1/1 caches

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14347]
caused by https://github.com/cgeo/cgeo/issues/14346

Caches with D/T 1/1 have the same icon as caches not support D/T.

This is caused by a quirk in icon cache:

float negative = -1.0f;
float positive = 1.0f;
final int hashNegative = new HashCodeBuilder().append(negative).append(negative).toHashCode();
final int hashPositive = new HashCodeBuilder().append(positive).append(positive).toHashCode();

Results in both having the same value?!?!
hashNegative = 1828739817;
hashPositive = 1828739817;

Any ideas what's causing this and how to best work around it?

Offending line: https://github.com/cgeo/cgeo/blob/e64063285923f47e505b87ad8d226fe82ba8ce56/main/src/main/java/cgeo/geocaching/utils/MapMarkerUtils.java#L688

**Comment by ztNFny** [comment]
Converting the float into a string would work. Any better ideas?

final int hashNegative = new HashCodeBuilder().append(Float.toString(negative)).append(Float.toString(negative)).toHashCode();
final int hashPositive = new HashCodeBuilder().append(Float.toString(positive)).append(Float.toString(positive)).toHashCode();

final int hashNegative = new HashCodeBuilder().append(negative + "" + negative).toHashCode();
final int hashPositive = new HashCodeBuilder().append(positive + "" + positive).toHashCode();

**Comment by fm-sys** [comment]
> The following is the approach taken. When appending a data field, the current total is multiplied by the multiplier then a relevant value for that data type is added. For example, if the current hashCode is 17, and the multiplier is 37, then appending the integer 45 will create a hash code of 674, namely 17 * 37 + 45.

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/HashCodeBuilder.html

So probably the fact that -1 * -1 = 1 is causing problems here...??? What will happen if you multiply two different primes to each of both values?

**Comment by ztNFny** [comment]
Returning something like -11 would be an option, but isn't that even more confusing?

**Comment by fm-sys** [comment]
> Returning something like -11 would be an option, but isn't that even more confusing?

Yes, that wouldn't be a way to go...


I did some testing:

![grafik](https://github.com/cgeo/cgeo/assets/64581222/6d2f530b-8324-42a2-95db-d139fc391b38)

**Comment by ztNFny** [comment]
I think convert to strong is the least confusing option of them.
