### ISSUE TITLE
Irritating map titles

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14369]
### Tell us your idea!

From support:

---

Irreführender Text bei Kartendarstellung

In der Kartendarstellung kann ich die Aktualisierung der Caches ein- bzw. ausschalten.
Dabei ändert sich der Text oben links :
Aktualisierung ein                  Live-Karte       (Live map)
Aktualisierung aus                 Offline-Karte  (Offline map) 
Das suggeriert fälschlich, ich hätte zur Darstellung eine Online- bzw. Offline-Karte ausgewählt.
War das wirklich so gemeint oder ist nur der falsche Text eingebunden?

---

Translation (summarized):

The map titles "Live map" and "offline map" somehow makes one think, that you are looking at an online or offline map. But this does not refer to the map itself but to the data on it.

### What solution would you suggest?

We could tune the naming a bit, e.g.:

Map (Live mode)
Map (Offline mode)

Map - Live
Map - Non-Live

### Is there an alternative?

Don't change it

### Additional Information

Suport ticket 110051

**Comment by ztNFny** [comment]
How about just Live and offline? The "map" part is obvious, didn't need to be explicitly stated.
