### ISSUE TITLE
UnifiedMap: Route distance view not updated on route recalculation

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14365]
### Description:
Looking at the screenshots in #14364 (see below), (and seemingly confirmed in a quick smoke test) distance view for individual route does not get updated on recalculation of a route when using `UnifiedMap`.

It does get updated, though, if you append/prepend or remove a route item to/from the individual route.
(But only for the affected segment, not for the whole route, so adding and removing the same point reverts to 550m, taken the example described below, instead of returning to 759m after removing the additional point - which is even stranger...)

### Screenshots copied from #14364:
The two screenshots in the first column (taken from `NewMap` and `CGeoMap` respectively) show a distance of 759m, which is the calculated distance for the three route items, whereas the three screenshots from `UnifiedMap` still show 550m, which is the straight line distance. (Remember, that `UnifiedMap` currently does not calculate route on startup, see #14363, and only calculates and updates the route on going into route edit and saving the (un-)changed route. This updates the route display, but not the route distance view for the individual route.)

|NewMap|VTM before|VTM after|
|---|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/70c624c7-6ade-4507-a8b4-997e2bfed8ec)|![image](https://github.com/cgeo/cgeo/assets/3754370/b3dcdd11-abed-4d67-8ea5-a46d99addec2)|![image](https://github.com/cgeo/cgeo/assets/3754370/52fbc93b-b681-4fdf-862a-2303bb04c76d)|

|CGeoMap|Google Map Unified|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/0634ca2b-aa42-4d8c-967f-df444df56902)|![image](https://github.com/cgeo/cgeo/assets/3754370/416fd3be-d6d7-4574-b25c-e5c8f63f39f4)|

(taken on a different device, though, compared to Mapsforge/VTM screenshots)

**Comment by moving-bits** [comment]
It's even worse: Depending on some timing issues (?) you won't even get a distance view at all!

When debugging a bit while opening the `UnifiedMap`, distance view gets shown. If you just start `UnifiedMap` without debugging, no distance view is being shown for me. All inner elements of the distance view have `visibility` set to `GONE`.

![image](https://github.com/cgeo/cgeo/assets/3754370/d20b34d6-0b3b-4220-91ce-04678eaf51dd)

@fm-sys 
Can you help here?

**Comment by fm-sys** [comment]
Will have a look in the next days...

**Comment by fm-sys** [comment]
Fix was quite easy, mapDistanceDrawer just wasn't observing individual route changes. So the distance view got only updated as soon as the GPS position changes (which doesn't happen in the emulator)

see PR #14401
