### ISSUE TITLE
Build cgeo without api key again

### ISSUE THREAD

**Issue by MakiWolf** [cgeo/cgeo#14361]
### Tell us your idea!

Can't compile without api key. I remember that it was possible without one a few years ago. Some users don't want to use closed sources like googlemaps. FDROID should also not use closed source libraries.

**Comment by MakiWolf** [comment]
Found solution:
copy empty templates/private.properties in root directory and it will build without key, but it does not change anything that the closed source things from google are included in the app. So please add this to roadmap to make a variant or build script without it.

**Comment by bekuno** [comment]
Please look here: https://github.com/cgeo/cgeo#api-keys
~~~
For the full usability of c:geo you need some API keys for Google Maps and the opencaching sites. You can leave all entries in the configuration empty, but Google Maps and the Opencaching sites will not work.
~~~
It is well documented, that you do not need a Google Maps API Keyy.
