### ISSUE TITLE
"Insert last log" discarded when adding image first

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14371]
### Describe your problem!

Described by a user on support mail, not verified

### How to reproduce?

- Compose and send a log for cache 1
- Start logging cache 2
- Insert a picture to be attached to the log
- Use "Insert last log text" from the menu to get the log text of cache 1

### Actual result after these steps?

- Nothing pasted (empty)

### Expected result after these steps?

- Log text from cache 1 is pasted

This does only work if the user does add the image only **after** using "insert last log text"

### Reproducible

Unclear

### c:geo Version

2023.06.18

### Additional Information

Support ticket 235587

**Comment by murggel** [comment]
Can't reproduce, but we could save the last log only if it is not empty...

**Comment by murggel** [comment]
@Lineflyer shouldn't happen anymore with the fix in PR #14434
