### ISSUE TITLE
remove remains of details_context.xml

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14381]
We once used to have a completly custom context menu and a lot of the code around that is still in the codebase. Best starting point should be res/menu/details_context.xml

**Comment by moving-bits** [comment]
Does that mean that we are no longer using those custom context menus and can delete the menu resource as well as all calling methods? Or is this only for specific places?

**Comment by ztNFny** [comment]
Yes. That's all obsolete. I discovered it while working on #14302

**Comment by moving-bits** [comment]
AFAICS the context menu still gets called: Haven't checked all places, but at least by long-tapping on cache name on cache details page you'll get to this:

![image](https://github.com/cgeo/cgeo/assets/3754370/ffea83d6-6835-40da-b86d-d7d4a93bec41)

(I've added a new menu item "hello world" at the top to easier recognize whether it's actually that menu.)

Can we close here then, or do you have other places in mind, where this menu is no longer in use, so that we can do a partial remove?

**Comment by fm-sys** [comment]
These context menus were modern at the time of android 5/6. We should replace them by something more modern IMHO. Just my two cents...

**Comment by fm-sys** [comment]
Thinking more about it: Does someone regularly use the "share" feature for plain text?

At least for me, _copy_ is enough for petty much all cases. It makes no difference whether I copy the text, go to e.g. WhatsApp and paste it there, or if I select _share_, search for WhatsApp in the share menu, and then select the correct recipient.

Does anyone has a use case were copy-paste is not an acceptable alternative? If not, we should copy the text on long-click directly and show a toast "text was copied to clipboard". This would reduce UI complexity and saves one click.

BTW, huawei Android 10 smartphones have a bug in the OS so they sometimes don't render the context menu correctly:

![Screenshot_20240202_190305_cgeo geocaching](https://github.com/cgeo/cgeo/assets/64581222/beaae85e-7a50-47de-8988-c7deaf1559c5)

**Comment by eddiemuc** [comment]
> These context menus were modern at the time of android 5/6. We should replace them by something more modern IMHO. Just my two cents... 

What would that be?

**Comment by eddiemuc** [comment]
> Thinking more about it: Does someone regularly use the "share" feature for plain text?
> 
> At least for me, _copy_ is enough for petty much all cases. It makes no difference whether I copy the text, go to e.g. WhatsApp and paste it there, or if I select _share_, search for WhatsApp in the share menu, and then select the correct recipient.
> 
> Does anyone has a use case were copy-paste is not an acceptable alternative? If not, we should copy the text on long-click directly and show a toast "text was copied to clipboard". This would reduce UI complexity and saves one click.

I agree with reducing the long-tap on text with one action. However, I vote for this to be the Share Action (and drop "copy"). Reasons for this:
- most (maybe all?) Android systems offer "cop to clipboard" anyway as their top sharing action these days
- I assume that the whole copy-paste-hassle is not appreciated by most users. E.g. on share WhatsApp and alike immediately offers you a "send to" list of Our contacts, with "copy-paste" you have to donthat yourself and then do the long-tap-paste additionally

**Comment by fm-sys** [comment]
No strong preference from my side. Honestly I have never used the longclick action except for exploring cgeos hidden features. 😅

Your arguments seem reasonable, so let's go with "share"

**Comment by fm-sys** [comment]
See PR https://github.com/cgeo/cgeo/pull/15324

![grafik](https://github.com/cgeo/cgeo/assets/64581222/8b146bf1-2617-4b6c-a8e2-e0093327cb26)
