### ISSUE TITLE
Settings - Routing / Navigation - input field does not match slider max

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14394]
### Describe your problem!

Maximum values of calculate route value slider and manual input field do not match

### How to reproduce?

1. Go to ``Settings`` => ``Routing / Navigation`` => ``Calculate route``
2. pull the slider for maximum distance to the very right end => 999 km will be shown (and be effective)
3. tap on the "999" => the box for manual input will open
4. although 999 is possible (and it of course *should* be ;) ), the title says "Enter a value between 1 and 120" 
5. leave 999 as is (or write any value greater than 120), and click [Ok]

### Actual result after these steps?

5. Value will be reset to 120

### Expected result after these steps?

A max of 999 should be possible ...

### Reproducible

Yes

### c:geo Version

2023.07.06-NB-3ca512a

**Comment by moving-bits** [comment]
Found the bug. The maximum for routing threshold is actually 120 km, so the input box is correct, but the slider got initialized with a wrong default max. I've fixed this, but I'm unsure about a reasonable max value for routing threshold. 1000 seems way too much, even on today's premium devices. How about 250 km?

**Comment by bekuno** [comment]
It should be possible to configure a long distance routing, so would go with 999.

**Comment by MagpieFourtyTwo** [comment]
Agree with @bekuno : 250 km are way too short. Even 500 are no problem at all, routes are calculated within seconds. And sometimes I would like to do even longer ones, to e. g. get an impression of which stuff lays along my (poss. even longer) journey - calculating routes this long will of course take a while, but when somebody does so, he will for sure be well aware of this. Hence, although routes this long will of course not be recommended, they should at least be possible.

**Comment by moving-bits** [comment]
Ok, I've updated the PR to set the max to 1000 km
