### ISSUE TITLE
Filled GeoJson Polygon rings should be supported by rendering

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14391]
### Describe your problem!

Some shapes are rendered wrong

Expected:
![image](https://github.com/cgeo/cgeo/assets/1258173/d066f669-db9e-4e7c-8e6b-418450192e99)
![image](https://github.com/cgeo/cgeo/assets/1258173/d6d9b815-0867-4404-98f3-24940673f022)

Actual:
![image](https://github.com/cgeo/cgeo/assets/1258173/59ceb3fa-99f0-445c-a6cc-b3dd8250d3f1)

### How to reproduce?

Load the attached geojson:
[Belgium_regions_all.geojson.txt](https://github.com/cgeo/cgeo/files/11952287/Belgium_regions_all.geojson.txt)

**Comment by eddiemuc** [comment]
Observation is correct. GeoJson Polygon rings are not supported by current implementation. Not a bug but a known limitation/not-yet-implemented feature. Currently each ring ia rendered as two polygons instead. This limitation is only visible with filled polgon rings of course.

Reason is that I didn't find support for polygon rings in underlying map libs either (Maps-Forge, VTM, Google Maps). Without this rings are not so easy to implement.

**Comment by eddiemuc** [comment]
Changed issue title accordingly

**Comment by devemux86** [comment]
Need to fix the results from [geojson library](https://github.com/cocoahero/android-geojson).

Re-wind the inner rings of GeoJSON polygons, fixing the winding order.
Then they are rendered correctly in all map engines. See [here](https://www.javatips.net/api/OpenMapKit-master/OpenMapKitAndroid-master/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/util/DataLoadingUtils.java) for ideas.

Renderings with Mapsforge and VTM in old [Cruiser](https://github.com/devemux86/cruiser):

![cruiser](https://github.com/cgeo/cgeo/assets/3484020/e771e3c9-8e86-470b-935c-e59b36642e52)
![cruiser-gl](https://github.com/cgeo/cgeo/assets/3484020/d12a8203-a476-41a9-8a85-dbdee8af2e5d)

**Comment by eddiemuc** [comment]
Thanks @devemux86 , I think this idea would work. If I understand the algorithm correctly, it will basically create a new "polygon" where at some point the inner and outer ring are connected.

The outline of such a polygon then has to be created using two different polylines, otherwise the "connection" between inner and outer ring would be visible too.

**Comment by eddiemuc** [comment]
Polygon holes are naturally supported by VTM and Google Maps, but not by mapsforge. Since we want to move to VTM/GM anyway with unified maps I see no use for c:geo to dive any deeper in graphic-related algorithmic.

PR #14438 will implement hole support for unified map.

**Comment by devemux86** [comment]
> Polygon holes are naturally supported by VTM and Google Maps, but not by mapsforge.

In the above 1st [image](https://github.com/cgeo/cgeo/issues/14391#issuecomment-1621437213) Mapsforge shows polygon holes.

**Comment by eddiemuc** [comment]
> > Polygon holes are naturally supported by VTM and Google Maps, but not by mapsforge.
> 
> In the above 1st [image](https://github.com/cgeo/cgeo/issues/14391#issuecomment-1621437213) Mapsforge shows polygon holes.

What I meant: VTM and Google support drawing holes directly in their polygon API. 

In VTM one can simply pass rings into a `PolygonDrawable` object, and the result will be rendered correctly:

![image](https://github.com/cgeo/cgeo/assets/6909759/d35fd3a9-2ef2-49e8-b044-aeb0803217b4)
![image](https://github.com/cgeo/cgeo/assets/6909759/0a1d779a-776e-492f-a31a-667e6699efe3)

In Google one can add Holes directly to the `PolygonOptions` using the `addHole` method, will also be rendered correctly:
![image](https://github.com/cgeo/cgeo/assets/6909759/a6d39f9d-645c-433e-83ab-737ebcc19f82)

I didn't find something similar in mapsforge's `Polygon` class:
![image](https://github.com/cgeo/cgeo/assets/6909759/92b5a2ec-e978-43ec-85dc-1d9a65d511a4)

Did I overlook something? Is there a better class I can use?

**Comment by devemux86** [comment]
@eddiemuc I mentioned above how it could work.
https://github.com/cgeo/cgeo/issues/14391#issuecomment-1621437213

Need to fix the winding order of the results (it is not correct).
If it can work with less code, then it is nice too. :slightly_smiling_face:

**Comment by eddiemuc** [comment]
> @eddiemuc I mentioned above how it could work. [#14391 (comment)](https://github.com/cgeo/cgeo/issues/14391#issuecomment-1621437213)
> 
> Need to fix the winding order of the results (it is not correct). If it can work with less code, then it is nice too. 🙂

Would be super-great if this could be incorporated into mapsforge of course! Thanks for you effort!

**Comment by devemux86** [comment]
It is more an improvement of the geojson library to send the correct results.
All projects that I have seen using it, fix the winding order of the results according to the specification.

Them all map engines can work correctly.

**Comment by eddiemuc** [comment]
> It is more an improvement of the geojson library to send the correct results. All projects that I have seen using it, fix the winding order of the results according to the specification.
> 
> Then all map engines can work correctly.

I still don't understand how rewinding (alone) can solve the display problem. As of now I don't even know which IF to use to even pass the coordinates of the inner rings (holes) to the mapsforge API. Also, is the rewinding thing still valid when there's more than one hole? And will this method maintain that all holes have the same line style (width, color) which also surrounds the exterior of the polygon?

Here is a very simple example of a polygon with 4 holes (a rectanlge with 4 rectangle holes), as displayed in geojson.io. How would I display thisin mapsforge using Polygon class?

Thanks a lot!

![image](https://github.com/cgeo/cgeo/assets/6909759/d47cb28a-df55-4175-b354-f53d03287d94)

GeoJson: 
[example.json.txt](https://github.com/cgeo/cgeo/files/12136798/example.json.txt)

**Comment by devemux86** [comment]
VTM uses JTS, so it may fix the polygons winding order.

If there are possible improvements in Mapsforge Polygon rendering we can see it. :slightly_smiling_face: 

By the way https://geojsonlint.com reports this geojson as invalid?

**Comment by eddiemuc** [comment]
> By the way https://geojsonlint.com reports this geojson as invalid?

Yes it is hand-crafted, not generated :-) Would be ok if rendering works only with adjusted data. Google maps and GeoJson.io can work with it anyway. VTM seems to have problems ("holes" are filled), but I haven't investigated further.

**Comment by eddiemuc** [comment]
Hi @devemux86 ,

I decided to dive in again into this issue. I am now building a routine into c:geo to re-wind the coordinates of the polygon exterior line (counter-clockwise) as well as the holes (clockwise). This solved the issue with VTM.

However I am still struggling with mapsforge: I don't understand how to set the "holes" coordinates in the Polygon object so the polygon can be displayed. To show what I mean I created the following example code which should construct a static polygon (the one above, but only with two of the holes and this time coords are ordered correctly):

```

import org.mapsforge.core.graphics.Paint;
import org.mapsforge.core.graphics.Style;
import org.mapsforge.core.model.LatLong;
import org.mapsforge.map.android.graphics.AndroidGraphicFactory;
import org.mapsforge.map.layer.Layer;
import org.mapsforge.map.layer.overlay.Polygon;

...
    public Layer constructPolygonWithHoles() {

        //set up paint objects
        final Paint strokePaint = AndroidGraphicFactory.INSTANCE.createPaint();
        strokePaint.setColor(Color.GREEN);
        strokePaint.setStrokeWidth(ViewUtils.dpToPixel(5));
        strokePaint.setStyle(Style.STROKE);

        final Paint fillPaint = AndroidGraphicFactory.INSTANCE.createPaint();
        fillPaint.setColor(Color.argb(128, 0, 255, 0)); //50% transparent green

        //construct Polygon Layer
        final Polygon polygon = new Polygon(fillPaint, strokePaint, AndroidGraphicFactory.INSTANCE);
        polygon.setDisplayModel(getDisplayModel());
        //exterior boundary (counter-clockwise)
        final List<LatLong> points = Arrays.asList(new LatLong(47, 175), new LatLong(42,175),
                        new LatLong(42, 180), new LatLong(47, 180), new LatLong(47,175));
        polygon.addPoints(points);

        //two of the four holes (clockwise)
        final List<LatLong> hole1 = Arrays.asList(new LatLong(46, 176), new LatLong(46,177),
                new LatLong(45, 177), new LatLong(45, 176), new LatLong(46,176));
        final List<LatLong> hole2 = Arrays.asList(new LatLong(46, 178), new LatLong(46,179),
                new LatLong(45, 179), new LatLong(45, 178), new LatLong(46,178));

        //TODO: how to set the holes in the Polygon object???
        
        return polygon;
    }
```

How can I "attach/set" the two "hole"-coordinate listst to the "Polygon"-Layer-object so mapsforge displays the holes? What am I overlooking here? Is "Polygon" the wrong class to use here?

Thanks and regards
  Eddie

**Comment by devemux86** [comment]
@eddiemuc the available overlay classes can be seen [here](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/overlay).

It's been a while since I used GeoJSON with both libraries, so I can't remember all details right now. :slightly_smiling_face:

**Comment by devemux86** [comment]
Maybe it's important if we use 1 Polygon object or multiple?
With current Polygon implementation, probably the coordinates are seen as a continuous path.

**Comment by devemux86** [comment]
Maybe we need a new Mapsforge class `PolygonWithHoles` having multiple coordinate lists for the rings (exterior + interiors).

**Comment by eddiemuc** [comment]
Note to self: https://stackoverflow.com/questions/14197823/draw-path-with-hole-android explains how to draw holes in Android

**Comment by eddiemuc** [comment]
@devemux86 in PR #14460 I added a new Polygon class to c:geo code. This class is a copy of mapsforge class `org.mapsforge.map.layer.overlay.Polygon` with added support for displaying holes (method `addHole` and member var `holes` are added, content of this is handled accordingly in `draw` method). Would you be interested in me adding this feature also to mapsforge code?

**Comment by devemux86** [comment]
> Would you be interested in me adding this feature also to mapsforge code?

@eddiemuc thanks, sure we can host it in Mapsforge.
Does it change existing Polygon rendering, so it may need a new class?

Also does it work with "islands in holes" and "holes in islands in holes", etc.?

The `path.setFillType(Path.FillType.EVEN_ODD);` is not needed?

**Comment by eddiemuc** [comment]
@devemux86 I will provide a PR for mapsforge, maybe we can discuss more details on it. On this PR it will also be more easy to see what is actually changed.

To your questions:

> Does it change existing Polygon rendering, so it may need a new class?

It is not a change imho but rather an addition to it.  
 
> Also does it work with "islands in holes" and "holes in islands in holes", etc.?

It doesn't work like this. In my understanding such a polygon describes one (exterior) polygon with many holes in it. An "island" inside a hole would be it's own polygon in this sense (and this may in turn also have holes). My understanding is that this is the interpretation in all the libs (e.g. GoogleMaps and VTM) as well as in GeoJson (one Polygon has multiple rings where the first ring defines the "exterior ring" and all other rings define "holes" in this "exterior ring"), so I would recommend to apply the same understanding here.

Also as far as i understand the holes need all to be completely inside the exterior polygon and not overlap each other. This is a common restriction also for all the above mentioned libs so I assume it is also true for 

> The `path.setFillType(Path.FillType.EVEN_ODD);` is not needed?

Didn't seem to be necessary, I suspect that this setting is the default (at least in Android). But I can add it of course explicitely to the code.

**Comment by devemux86** [comment]
> Didn't seem to be necessary, I suspect that this setting is the default (at least in Android). But I can add it of course explicitely to the code.

If it is not necessary we can skip it.

Please note that the `Polygon` class works on Android + Desktop, it does not have Android specific code.
All graphics classes in `Polygon` are Mapsforge classes, like the `org.mapsforge.core.graphics.Path`.

**Comment by eddiemuc** [comment]
> Please note that the `Polygon` class works on Android + Desktop, it does not have Android specific code.
> All graphics classes in `Polygon` are Mapsforge classes, like the `org.mapsforge.core.graphics.Path`.

Yup, I am aware. Luckily the Mapsforge Path abstraction contains everything needed already (specifically the `close` method of `Path`).
