### ISSUE TITLE
Update to latest Mapsforge to support curved lines

### ISSUE THREAD

**Issue by ppete2** [cgeo/cgeo#14413]
### Describe your problem!

Since December 2022 Mapsforge is able to draw curved lines for Offline maps, especially a nice feature for contour lines or waterways:
https://github.com/mapsforge/mapsforge/pull/1371 

Please update to the latest Mapsforge source to work with Themes supporting curved lines within Offline Maps, thank you!

### How to reproduce?

Load an offline Mapsforge map and a select a theme which supports curves

### Actual result after these steps?

C:geo isn't loading/displaying this theme

### c:geo Version

2023.06.18

### System information

```text
Android 13
```

**Comment by bekuno** [comment]
mapsforge release version [0.19.0](https://github.com/mapsforge/mapsforge/releases/tag/0.19.0) in the meantime.
We should switch to this version, if no problem is identified.

**Comment by moving-bits** [comment]
A (very short) smoke test was ok, so I created #14414 to update both Mapsforge and VTM.

**Comment by moving-bits** [comment]
Done with #14414, new Mapsforge lib is availabe in the nightly versions.

**Comment by ppete2** [comment]
Thanks, it would be great if you could again update to the latest **Mapsforge version v0.20.0**, which could be downloaded here:
https://github.com/mapsforge/mapsforge/releases/tag/0.20.0

**Comment by bekuno** [comment]
> Thanks, it would be great if you could again update to the latest Mapsforge version v0.20.0,

See #14511 and #14512
