### ISSUE TITLE
Allow copying of image EXIF comment

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14415]
### Tell us your idea!

A user on support mentions a cache with (at least) one image having an image comment that gets cut off when displaying it in our image gallery, and there is no way to display or copy the full comment.

See https://coord.info/GC6RXEW

### What solution would you suggest?

Allow copying the image comment.
Optionally enable displaying the full comment.

### Is there an alternative?

Keep it as is.

### Additional Information

ticket 700870

**Comment by ztNFny** [comment]
The "comment" is not a comment but EXIF information extracted from the image
