### ISSUE TITLE
Store waypoint visited flag with personal cache note

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14428]
### Tell us your idea!

At the moment you can backup (copy + upload) any custom waypoints or additions to existing waypoints via our feature to copy those into the personal cache note.

The only helpful information, which is not covered is whether the specific waypoint has been marked as visited.

### What solution would you suggest?

Extend the feature to also copy the waypoint visited flag into the personal note, to allow backup + restore of this information

### Is there an alternative?

None

**Comment by murggel** [comment]
@eddiemuc  Do you have any idea, how this could fit into the existing syntax for storing the waypoint-infos?
I could imagine to write kind of "{x}", "{v}"  or {visited} for visited after / before the waypoint type...

**Comment by eddiemuc** [comment]
> @eddiemuc  Do you have any idea, how this could fit into the existing syntax for storing the waypoint-infos?
> I could imagine to write kind of "{x}", "{v}"  or {visited} for visited after / before the waypoint type...

I like the idea of using {v}

**Comment by murggel** [comment]
Hm, should that be somehow configurable on reading from note, because it is user-dependent and not wanted if the PN is shared between different users. 
For which scenarios? Probably as option on importing from GPX "import user-dependent info"?
