### ISSUE TITLE
Evaluate supporting a user-paid version of mapy.cz

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14423]
### Tell us your idea!

We get regular feedback from users missing mapy.cz support. We had this support in the past, but needed to remove it when mapy.cz stopped their free version.

### What solution would you suggest?

While we cannot afford the paid version by ourself, there may be users having a paid option, which may be used in conjunction with c:geo. Not sure if there is a way to link into that, meaning, letting the user enter some sort of API key (or whatever they get when they buy a paid option) - we would need to evaluate that first.

### Is there an alternative?

Keep it as is, no support for mapy.cz anymore

### Additional Information

support ticket 556331 (and others)

**Comment by Colomb-0** [comment]
Make Mapy.cz great again 🫡

**Comment by CommanderCZ** [comment]
I miss Mapy.cz a lot. Even if they were paid, I would definitely get them, because OSM is not enough/clear for me.

**Comment by Loskatos** [comment]
Mapy.cz is clearly the best map source, which would be appreciated by hunters outside the Czech Republic as well.
I'm for any option to add. Unfortunately, I think having a private API key is not financially possible.

**Comment by moving-bits** [comment]
For reference: https://api.mapy.cz/

Not sure about all details, but it looks like they make part of their data available for free under certain conditions (which we would have to check whether we comply to them), but using a different technical base as in the past (on top of Google Maps API instead of OSM tile server). Also I'm not sure whether this is for website integration only, or available for Android apps as well.
This is a quick glance impression only, needs to be investigated further.

**Comment by moving-bits** [comment]
FYI: I've started another attempt to get into contact with mapy.cz representatives, this time using their forum. Let's wait for their reaction.

**Comment by moving-bits** [comment]
Small update:

We are currently in contact with Mapy.cz product management to evaluate options. So far we have (amongst other details):
- there is no user-paid option
- there is no free option (or, to be more specific: the free contingent will not be enough for expected c:geo usage)

c:geo core team will discuss internally if there are any further options we may want to pursue.

Until then, a geo uri based-integration should be possible already (haven't tested, though), so if you install the Mapy.cz app, you can select "navigate - other external app", and Mapy.cz app should be offered by Android as navigation app.

**Comment by MakiWolf** [comment]
It also would be interesting to add OpenTopoMap. 
Faq
https://opentopomap.org/about
Contact
https://opentopomap.org/credits
@Lineflyer Do you get an answer last time? Maybe cgeo team should try to contact them again as replacement for use, since mapy.cz support have been removed.
Old issue
https://github.com/cgeo/cgeo/issues/9470

**Comment by bravewolfcz** [comment]
Interesting that the Horobraní application uses mapy.cz
 There can be cooperation somewhere.

**Comment by moving-bits** [comment]
We have been in close contact with the product manager (thanks for the quick replies), checked available API options, available data plans and even discussed other options.

Basically, Mapy.cz is a commercial service (which is fine), and they charge on a per-tile basis. They have two packages with some free usage limits (the larger one being bound to specific conditions). Tile usage packages are only available to companies / institutions etc., but not to individuals.
Mapy.cz maps are available in two flavors - there is a map tile server (the map tiles could be integrated in c:geo's maps), and a separate app (which can be called by c:geo using so-called "geo intents").

We have discussed the different options in our core team and came to the following conclusion:

﻿c:geo is an independent and open source software that prefers open source solutions naturally, and tries to not favor any specific commercial service. Also, as being a small team, we need to prioritize where to put our efforts into.

- c:geo is not eligible for the package with the larger free amount, and even if, it's very likely that the free contingent would not suffice.
- Considering an estimated map usage of c:geo and estimated user numbers with potential use of Mapy.cz within c:geo, we would run into relevant monthly costs.
- We are a non-commercial entity and will not subscribe to any commercial plan (buying tile plans etc.) or go into any commercial agreement.
- There's no tile package available to individuals, so there's no way that c:geo users being interested in Mapy.cz maps could buy their own key.

Thus c:geo integration for Mapy.cz will stay "as is" for now, supporting Mapy.cz as navigation target using geo encoded URL (as with any other app supporting geo encoded URL). This should be working already.

If there will ever be a Mapy.cz app API supporting methods to place multiple objects on the app's map or picking an item from a provided list of objects, we might consider supporting such features (as we have done for other map providers).
