### ISSUE TITLE
Display elevation above Mean Sea Level instead of above WGS84 Ellipsoid

### ISSUE THREAD

**Issue by ppete2** [cgeo/cgeo#14424]
### Describe your problem!

Right now c:geo displays the elevation of the current location within the Home-screen and Compass screen **_above WGS84 Ellipsoid (=Ellipsoidal Height)_**. (at least on my phone: Xiaomi Redmi 10 Pro, Android 13)
This is the raw elevation a GPS-receiver determines. Bus this elevation is not used in everydays life, like elevations of mountain peaks for example. Their elevations are so called **_"Elevation above Mean Sea Level"_** which both differ depending on the location on Earth. In Austria about 45 m. So if the peak of a mountain has 1000m above mean sea level, c:geo displays: 1045m by mistake.

Please correct the elevation value to be displayes as _"m above mean sea level"_ . There are correction files available in the Internet, google for "Geoid".

See: https://support.virtual-surveyor.com/en/support/solutions/articles/1000261349-the-difference-between-ellipsoidal-geoid-and-orthometric-elevations-

### Reproducible

Yes

### c:geo Version

2023-07-16

### System information

Xiaomi Redmi 10 Pro, Android 13

**Comment by moving-bits** [comment]
For reference: See https://github.com/cgeo/cgeo/issues/15838#issuecomment-2210264899
(Looks like Android 14 may have an easy way to achieve this code-wise)

**Comment by fm-sys** [comment]
@ztNFny did you downvote because you want to stay with WGS84 Ellipsoid, or cause you think it's not worth the effort to include a correction table in the c:geo APK?

If it's the second, there is a build-in Android API starting with Android 14. See https://github.com/cgeo/cgeo/issues/15838

**Comment by rhodo-dendron** [comment]
This is a bug not a feature.

**Comment by ztNFny** [comment]
> cause you think it's not worth the effort to include a correction table in the c:geo APK?\n\nIf it's the second, there is a build-in Android API starting with Android 14. See #15838

Imho it shouldn't be an apps job to adjust the information returned by the system, every app will display a different value then.
If now android provides that functionality we can use it, but we shouldn't put adjustment logic in the code
