### ISSUE TITLE
Wrong username encoding on TB page

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14442]
### Describe your problem!

If a user name contains a special character (here: `&`) its displayed wrong on the TB page

![grafik](https://github.com/cgeo/cgeo/assets/949669/d7343549-7115-45b3-bc3b-7a587eedb377)

The user name is `J&LA`

![grafik](https://github.com/cgeo/cgeo/assets/949669/e7532d8e-e6d2-42e3-b8f6-8a855916470b)

### How to reproduce?

See above
The user was not sure, whether its only wrong at this place or also at others (e.g. logbook, homescreen) but seemingly its only the TB page, where he found it

### Reproducible

Yes

### c:geo Version

2023.06.18

### Additional Information

Support ticket 435009

**Comment by moving-bits** [comment]
`spottedName` for that trackable is `J&amp;amp;LA` - which would be a double encoding.

If you look at the [trackable's page's](https://www.geocaching.com/track/details.aspx?tracker=TB3MF1N) source, you find the cause for this in the following line (which is the one being used for determining the `spottedUser`):

`<a id="ctl00_ContentBody_BugDetails_BugLocation" data-name="J&amp;amp;LA" data-status="User" href="https://www.geocaching.com/p/?guid=xxx">In the hands of J&amp;LA</a></dd>`

We need to de-HTML the parsed `spottedUser`value - I'll create a PR for it.
