### ISSUE TITLE
Twitter Authorization not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14441]
### Describe your problem!

Reported by a user and reproducible for me.
We had such issue in the past due to a change in the twitter auth process...maybe again such a change?

### How to reproduce?

- Go to Menu - Settings - Services
- Select Twitter
- Start Authorization

### Actual result after these steps?

Toast: "c:geo could not start autohrization"

### Expected result after these steps?

Twitter authorization started, Twitter login page shown, Authorization OK

### Reproducible

Yes

### c:geo Version

2023.06.18

### Additional Information

Support ticket 552241

**Comment by SammysHP** [comment]
The API was shut down months ago and it won't come back. We can remove Twitter from c:geo.

**Comment by moving-bits** [comment]
There still seems to be some free API access to v2 API (although limited to 1,500 posts/month) according to https://developer.twitter.com/en and https://techcrunch.com/2023/03/29/twitter-announces-new-api-with-only-free-basic-and-enterprise-levels.

We are currently using v1.1 API. Not sure whether this is still supported, and if so, how long it will stay at that. API documentation for 1.1 is still available (https://developer.twitter.com/en/docs/twitter-api/v1), whatever this means in those days, but there is some discussion about 1.1 API being shut down gradually (eg: https://twittercommunity.com/t/is-standard-v1-1-free/188769).

**Comment by SammysHP** [comment]
I wouldn't count on the documentation. Elon doesn't care about the proper procedure, roadmaps and documentation. He makes a decision, that's all.

**Comment by ztNFny** [comment]
Twitter is dead - even if it wasn't it's not a platform I like to support - lets remove it

**Comment by moving-bits** [comment]
Thanks for your feedback. See PR #14470 for removal.

**Comment by bekuno** [comment]
Thwitter integration is removed with #14470.
Lets close.
