### ISSUE TITLE
Add private (=cgeo internal) comments to caches

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#14463]
### Tell us your idea!

Instead of storing caches on several lists or adding comments into the official GC comment section, it might be useful to add comments directly to the cache and make them visible on the main page of each cache directly below the favorite section for instance.

This field should be indexed so searching inside the main search box should display a cache with this keyword. 

### What solution would you suggest?

See above, add a new internal comment function to each cache and make it searchable. 

### Is there an alternative?

Using hundrets of lists which is not the desired solution.

**Comment by SammysHP** [comment]
So you prefer unstructured text instead of tags/lists for sorting/filtering caches? Sounds like we have to improve our way of managing lists.

**Comment by wolverine007** [comment]
Not really, but I already suggested last year to add tags to caches, but this has been denied and everyone was referring to lists and using symbols...

If we are open now for handling tags instead, this might be fine as well.

But handling hundrets of lists and adding caches to more than one is definetly not my desired solution in this case.

**Comment by moving-bits** [comment]
I don't yet understand your use case. 
What do you want to use tags for, and how should UI for tags look like? And in what aspects should those tags be different from today's lists?

**Comment by ztNFny** [comment]
Lists and tags is just 2 representations of the same concept. No point in having both.

**Comment by wolverine007** [comment]
> Lists and tags is just 2 representations of the same concept. No point in having both.

Not really - tags are for me additional filter criterias like the different cache types - which could already be used for filtering the live map or a list for instance.

So applying tags in addition to a dedicated cache, is easily enabling another filter criteria abroad all stored caches.

The same approach is being used for instance by VMware, where you could apply tags to all available objects regardless of their type, storing location or whatever you might apply for categorizing an object in addition to a tag.

**Comment by ztNFny** [comment]
A "tag" is something you add to an object to put some information, like e.g. "important". It's different from its storage location as you say which can only be 1 place, which is why tags are popular in software that puts an item in 1 place and then make it available from other places as well.
In cgeo a cache can be in any number of lists, there's no 1 place thing in cgeo. Thus lists == tags.

You still didn't mention a single usecase where you find the existing functionality lacking.

**Comment by eddiemuc** [comment]
> > Lists and tags is just 2 representations of the same concept. No point in having both.
> 
> Not really - tags are for me additional filter criterias like the different cache types - which could already be used for filtering the live map or a list for instance.

You can filter by lists (aka "tags") in c:geo too. Use the advanced filter "stored lists".

**Comment by eddiemuc** [comment]
@wolverine007 I had a thought. Is maybe what you're asking simply an easier method to assign caches to lists/tags? E.g. something like in JIRA where you just enter tags/list-names in a free text field (with suggestions for existing tags/lists) instead of having to go through a long selection list of existing lists/tags and do an explicit "create" step for a new one?

**Comment by ztNFny** [comment]
> @wolverine007 I had a thought. Is maybe what you're asking simply an easier method to assign caches to lists/tags? E.g. something like in JIRA where you just enter tags/list-names in a free text field (with suggestions for existing tags/lists) instead of having to go through a long selection list of existing lists/tags and do an explicit "create" step for a new one?

A free-text field would be a big departure from the current setup and make working with few (or even many lists - can you remember all the names?) quite a lot more cumbersome.

How about adding a filter-field to the existing list selection dialog that can also be used to quickly create a new list (without showing a second dialog for the name input)?

**Comment by wolverine007** [comment]
> > @wolverine007 I had a thought. Is maybe what you're asking simply an easier method to assign caches to lists/tags? E.g. something like in JIRA where you just enter tags/list-names in a free text field (with suggestions for existing tags/lists) instead of having to go through a long selection list of existing lists/tags and do an explicit "create" step for a new one?
> 
> A free-text field would be a big departure from the current setup and make working with few (or even many lists - can you remember all the names?) quite a lot more cumbersome.
> 
> How about adding a filter-field to the existing list selection dialog that can also be used to quickly create a new list (without showing a second dialog for the name input)?

Like written earlier, the usage of predefined "tags" should be the preferred solution - custom text was another idea, but not useful - see the explanations above. 

So user could define a set of tags which is than available like the lists and assign them by selecting a checkbox.
Maybe this could also be linked with symbols so the attribut ladder oder climbing needed could be easily identified.

Adding a better filter into the list selection might also help, but lists and tags are still two pair of shoes from my point of view... ;)

**Comment by ztNFny** [comment]
> So user could define a set of tags which is than available like the lists and assign them by selecting a checkbox.
> Maybe this could also be linked with symbols so the attribut ladder oder climbing needed could be easily identified.

All of this - even the icon - is already with lists. You still failed to mention a single usecase where you find the existing functionality lacking!

**Comment by murggel** [comment]
> Adding a better filter into the list selection might also help, but lists and tags are still two pair of shoes from my point of view... ;)

I like the idea of filtering the stored list -> I would put that in a separate issue -> #14602
