### ISSUE TITLE
Label for bottom navigation menu customization

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14473]
Btw, i find the label "custom menu entry" quite bad. I wouldn't have known what it does had i not seen the commits.

How about "last bottom navigation item"? (Bottom is required as else it'll be confused with map routing kimd of navigation)

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/14465#issuecomment-1658958356_

**Comment by Lineflyer** [comment]
How about "Last menu bar item" as its less technically driven?

**Comment by moving-bits** [comment]
I propose to use a short, ideally non-technical, term as title in settings, and add a more detailed description below.

**Comment by MagpieFourtyTwo** [comment]
I would do either do ...
- a combination of the above, i. e. change the setting name to "Custom Menu Item"
  and add a description like "Rightmost bottom navigation menu item"
- or just use "Rightmost bottom navigation menu item" as setting name
  while the word "Custom" is not really needed, as the fact that it's listed here, already implies that it's a customization.  ;)

And, yes, the latter is pretty long,  but IMHO unmistakeably clear.

**Comment by MagpieFourtyTwo** [comment]
Although the description is implemented in the code, I can't see it in the settings dialog ... did I miss s/th?

**Comment by moving-bits** [comment]
> Although the description is implemented in the code, I can't see it in the settings dialog ... did I miss s/th?

Has been merged only this morning, will be available in next nightly version
