### ISSUE TITLE
Remove auto-download offer for maps.me

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14474]
[...] But we could (and IMHO should) remove the automatic download offer for maps.me due to them no longer being open source. [...]

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/14427#issuecomment-1650398408_

Proposal:
- Currently `isInstalled` is always set to `true` for maps.me, and a popup gets displayed which offers the download of the nowadays commercial version
- Replace this with a regular check whether the package for maps.me is installed, and grey-out the corresponding menu options otherwise, like we do for (nearly) every other navigation app c:geo supports

How to detect if maps.me is installed?
Currently the only package still provided by Play Store is `com.mapswithme.maps.pro`, but I guess there has been a free version with a different package name in the past. Shall we support both for installation detection, or the current package name only?

**Comment by ztNFny** [comment]
I wouldn't offer the "install" option for any map - unless there was an app that we specifically wanted to promote, but I'm not seeing that.

**Comment by moving-bits** [comment]
> How to detect if maps.me is installed? Currently the only package still provided by Play Store is `com.mapswithme.maps.pro`, but I guess there has been a free version with a different package name in the past. 

Found `com.mapswithme.maps.app` in `AndroidManifest.xml` as additional package name.
But: My PR relies not on package names but on intent resolver as provided by MapsWithMe API file, see #14475.
