### ISSUE TITLE
UnifiedMap: OSM map auto rotation not working

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14481]
manual map rotation does work, but auto rotation does not, and menu entry for map rotation is not yet implemented

**Comment by fm-sys** [comment]
The old "auto map rotation" mode never did really work for me properly... Instead of calculating the bearing out of the last GPS positions, I would vote to use the compass orientation instead.

**Comment by moving-bits** [comment]
> The old "auto map rotation" mode never did really work for me properly... Instead of calculating the bearing out of the last GPS positions, I would vote to use the compass orientation instead.

I've made the experience that you needed to move for some short time (half a minute or so), then it has stabilized and works fine after that (at least on my phone).

**Comment by moving-bits** [comment]
I'm currently trying to implement auto map rotation for VTM. Movement of map including rotation (tested with GM only so far) seems to work fine, when triggered by Lockito, but the heading indicator does not move at all (neither position nor heading), although PositionLayer has an observer on positionAndHeading, which does indeed get set. How come the observer does not get triggered?
