### ISSUE TITLE
Move Refresh Popup to another location

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#14498]
### Tell us your idea!

Inside the latest release a new refresh dialog with a small popup window has been added.

While focussing on the progress bar on top of the window the small popup far down below is not getting the right attention from my point of view.

So moving the dialog to the top and adjusting the size (e.g. centered dialog, with 95% of the available width as fixed size) might be a better user experience. The font size should stay like it is right now.

### What solution would you suggest?

Move the popup somewhere here:

![IMG_20230810_102637](https://github.com/cgeo/cgeo/assets/4508228/c95ad0e1-92b8-48cd-bfd0-40273f551835)

### Is there an alternative?

keep the current solution

**Comment by ztNFny** [comment]
Toasts are a standard element of Android and always displayed in the same location.

**Comment by moving-bits** [comment]
Nothing we can/should do here, so let's close as "not planned"
