### ISSUE TITLE
creation of a course (distance) before starting to do it

### ISSUE THREAD

**Issue by takius92** [cgeo/cgeo#14492]
### Tell us your idea!

Good morning,
on the application, we find plenty of routes/loops of X KM
but, it can be that this one is too big to realize it in one go by certain person (disability)

would it be possible to prepare a loop (locally on your phone) upstream to estimate the distance of this potential future loop?

would it also be possible to be able to add waypoints manually to this one (parking the car for example)?

couple to the BROUTER application, we can estimate the distance

thank you for considering the request

**Comment by eddiemuc** [comment]
Hello @takius92, 

I am not sure I understand the request correctly. Is this about routing capabilities of c:geo? 

c:geo has some powrful functions to create individual routes and trips using BRouter internally. You can add caches, waypoints (e.g. parking waypoints) as well as individual points to such a route (individual points by long-tapping a place in the map). The functions are described here: https://cgeo.droescher.eu/en/brouter 

Does this help you?

**Comment by moving-bits** [comment]
Very likely being covered by individual route feature and no further feedback, therefore closing here. Feel free to re-open, if some new questions regarding this feature come up.
