### ISSUE TITLE
Waypoint Icon of Multi Cache

### ISSUE THREAD

**Issue by flat2let** [cgeo/cgeo#14502]
### Tell us your idea!

If we do several multi-caches in the same area all waypoints have the same icon (puzzle piece). This way it is not possible to differentiate the waypoints for the different caches. 

### What solution would you suggest?

I would like to be able to give the waypoint icons (puzzle pieces)different colors to see which ones belong to a certain cache.

### Is there an alternative?

alternatively it could be different waypoint icons, other than puzzle pieces,

### Additional Information

![waypoints](https://github.com/cgeo/cgeo/assets/85786015/624e4467-977c-46ce-915e-c12159ec998f)

**Comment by flat2let** [comment]
Thanks so much for all the work you do. Geocaching would not be great without c:geo

**Comment by Lineflyer** [comment]
IMHO a valid request also just recently discussed on some social media channels.

How about when changing the cache icon itself would trigger the waypoints to have markers (e.g. in lower right) with icon chosen for the cache itself?

**Comment by Lineflyer** [comment]
Another similar feature request but different use case / realisation (feel free to split into another issue):

When going for a multi cache with multiple given waypoints in close vicinity to each other (which have to be visited in sequence) its sometimes cumbersome to find the correct next waypoint from the bunch on the map.

For this I could imagine a on-demand feature to change waypoint icons to numbers using the sequence provided by the owner (via its prefix). This could either change the icon itself or also add a marker icon with the number to it.

**Comment by eddiemuc** [comment]
How about allowing the user to connect waypoints of a cache with lines in a chooseable color in the order of their appearance in the listing? E.g. like in the image below (unlike this quickly-made-up example, lines should be BEHIND icons imho):

![image](https://github.com/cgeo/cgeo/assets/6909759/ee8ec205-55bf-47d8-8fe8-ebdabb35222d)

**Comment by flat2let** [comment]
I think the suggestion of numbering the waypoints would go well together with my idea. The lines are a good idea as well. 
I would like to be able to either color the puzzle pieces or the background. They could be connected with lines and the numbers could be added as icons. But I am happy either way whatever is the easiest to do. As long as you can differentiate.

**Comment by moving-bits** [comment]
> How about allowing the user to connect waypoints of a cache with lines in a chooseable color in the order of their appearance in the listing? E.g. like in the image below (unlike this quickly-made-up example, lines should be BEHIND icons imho):

One could extend the "individual route" feature for this to allow for
- creating multiple individual routes (similar to being able to load multiple tracks)
- assigning user-defined colors for each individual track (again similar to tracks)

Long-tap context menu could be extended then to include "Add to new route", creating a new route with this element.

If there is more than one individual route, we need to either select a "default route" where all "append/remove" actions refer to, or we need to include "Append/prepend to route #x" in the menu in that case.

**Comment by eddiemuc** [comment]
> > How about allowing the user to connect waypoints of a cache with lines in a chooseable color in the order of their appearance in the listing? ...
> 
> One could extend the "individual route" feature for this...

That's not what I had in mind. If I understand correctly, this issue is about visualizing that certain waypoints + (multi)cache belong together on a map. It is not about creating a route along them. I just thought that connecting them by a line could be a way to visualize this grouping. This could be turned off and on e.g. on a per-cache-basis in the long-tap context menu when done on the cache symbol or any associates waypoint

**Comment by flat2let** [comment]
I agree with eddie, my suggestion was not about creating a route but just to visualize which waypoints belong to which multi-cache. So turning on and off the line would be a solution. And as stated on top of marking the waypoints in different colors.

**Comment by ztNFny** [comment]
My vote goes to adding the cache icon to waypoint icons in the lower right corner. Deadwood by default enable differentiating waypoints from different cache types and if the uses to select the custom icon for a cache also between caches.

I wanted to look into an "inverted" type icon big smiley mode anyway, this could very well be combined.

**Comment by ztNFny** [comment]
My vote goes to adding the cache icon to waypoint icons in the lower right corner. Deadwood by default enable differentiating waypoints from different cache types and if the uses to select the custom icon for a cache also between caches.

I wanted to look into an "inverted" type icon big smiley mode anyway, this could very well be combined.

Different colored backgrounds will not work well - at the very least it'll only tell you which WPs being together but not too which cache they belong. Also it'll look hideous - as a GUI guy that option this gets my big no-no vote.

**Comment by ztNFny** [comment]
My vote goes to adding the cache icon to waypoint icons in the lower right corner. Deadwood by default enable differentiating waypoints from different cache types and if the uses to select the custom icon for a cache also between caches.

I wanted to look into an "inverted" type icon big smiley mode anyway, this could very well be combined.

Different colored backgrounds will not work well - at the very least it'll only tell you which WPs being together but not too which cache they belong. Also it'll look hideous - as a GUI guy that option this gets my big no-no vote.

**Comment by ztNFny** [comment]
As discussed in today call I'll implement:
- For waypoints add in upper left corner the cache icon
- For "big smiley" mode add the type icon in upper left corner
- For linear labs automatically set number-emojis as waypoint icon

**Comment by flat2let** [comment]
As stated before I am happy with any method you chose, and what you think is best for the program. 
Thanks so much for your efforts, for taking up my issue, and looking for a good solution. Can't wait to see it implemented.

**Comment by ztNFny** [comment]
step 1: show emoji on waypoints (if one is assigned)

![image](https://github.com/cgeo/cgeo/assets/1258173/7652f8e6-92e5-45d3-9bfa-aa3819cec351)

**Comment by flat2let** [comment]
Hi, to me it is not quite clear how I would differentiate waypoints for different caches? Would the ribbons have different colours?

**Comment by ztNFny** [comment]
Ribbon is list icon. You have multiple Caches on the first screenshot.

**Comment by flat2let** [comment]
I might not really understand it, but I only see the one with the blue dot, and a red smiley, but not two different caches with multiple waypoints?

**Comment by eddiemuc** [comment]
I too have problems understanding the concept from the writings in this discussion.
* Am I understanding correctly that the goal to differentiante between cache/waypoints by assigning a new symbol to each cache and display it in the upper left corner of the cache symbol? (in the given examples e.g. a blue circle and a red square)?
* Are those assigned "randomly" to each cache currently displayed on the online map? (it can't be a previously saved property of the cache because it needs to work also on online maps of course)?
* Is this only availabe in the foremost mentioned "big smiley" mode or also in "normal mode"? Is this "big smiley" mode in itself a new feature? In which issue is this discussed?
* Can I turn on/off the "differentiation" of caches/waypoints by using this new upperleft-symbol somewhere? Dependent or independent from this new "big smiley" mode?

**Comment by ztNFny** [comment]
This is the normal, long time existing, "set cache icon" functionality. If a custom icon is set *explicitly by ther user* it'll be displayed on waypoints.

**Comment by ztNFny** [comment]
> I might not really understand it, but I only see the one with the blue dot, and a red smiley, but not two different caches with multiple waypoints?

Blue dot and red square are 2 caches with custom icon set - to red square wnd blue dot.

**Comment by eddiemuc** [comment]
> This is the normal, long time existing, "set cache icon" functionality. If a custom icon is set *explicitly by ther user* it'll be displayed on waypoints.
> 
> It's not related to big smiley mode in any way.

But this then does not solve the problem described in this issue,  does it? It is about differenting on a complex map situation (like e.g. shown in the screenshot in initial post) which waypoints belong to which cache. The icon solution would require to first save all relevant caches offline and assign icons to all of them. Is this the proposed solution?

**Comment by ztNFny** [comment]
Yes, this is the approach discussed and agreed in the last team call

**Comment by flat2let** [comment]
ok - now I get that - I will have to assign a specific icon to the cache, and in future the related waypoints will have this as a small icon in the top left corner. 
I still did not understand the ribbon, so far I have never seen this. 
But I am so thankful for your help and all the new developments - it's just great

**Comment by ztNFny** [comment]
> ok - now I get that - I will have to assign a specific icon to the cache, and in future the related waypoints will have this as a small icon in the top left corner. 
> I still did not understand the ribbon, so far I have never seen this. 
> But I am so thankful for your help and all the new developments - it's just great

Ribbon = list icon. Similar to custom cache icon

**Comment by eddiemuc** [comment]
Got it now too, thanks for clarifying.

I would love to see this combined with two additional features:
* allow via setting that cache symbol is placed on right side instead of replacing/hiding the type cache icon. Loosing the visual type info is the main reason why I don't use cache symbols so far
* new setting to auto-display cache symbols to all caches with waypoints and no explicit icon set by user. Symbol should then be chosen based on last digit of coordinate from a fixed set. This would allow seeing what waypoint belongs to what cache without having to persist and modify it first

**Comment by eddiemuc** [comment]
or, alternatively, just the second (and keep this independent from cache symbols). I am opening a dedicated issue for it.

**Comment by ztNFny** [comment]
> or, alternatively, just the second (and keep this independent from cache symbols). I am opening a dedicated issue for it.

No! This is already on the todo-list, please read the notes from call

**Comment by ztNFny** [comment]
I'll refrain from posting previews of any unfinished features from now. This discussion is costing more time than the implementation and not adding any value.
Will not comment further here and just push the PR when it's ready

**Comment by eddiemuc** [comment]
> > or, alternatively, just the second (and keep this independent from cache symbols). I am opening a dedicated issue for it.
> 
> No! This is already on the todo-list, please read the notes from call

Agree, my thought would be a new feature request. Hence the dedicated issue.

**Comment by moving-bits** [comment]
We have the "set list icon", "set cache icon" and "connect by lines" options available meanwhile, thus let's close here.
Feel free to reopen (or better: open a new issue) if something is missed for this use case.
