### ISSUE TITLE
TB not visible (maybe related to special characters)

### ISSUE THREAD

**Issue by Schlauchen** [cgeo/cgeo#1450]
I have a problem with logging the TB http://www.geocaching.com/track/details.aspx?id=4079615  as visited. On the geocaching site, I see on the log page all my TBs to log visited/dropped etc, in c:geo, this TB is missing and I see only the other two ones. Maybe it's the fault of the special characters. The name of the TB is currently " Schlauchen&ravestorm=<3 ".

**Comment by TofLaBeuze** [comment]
Hi all,
it seems the problem is still there... a french geocacher had a TB with '<' character, not seen in c:geo. He removed this character and it appears now in inventory.

**Comment by samueltardieu** [comment]
Does geocaching.com correctly escape it as &lt; in the page?

**Comment by samueltardieu** [comment]
(read this as ampersand l t semicolon)

**Comment by SammysHP** [comment]
Which is `&lt;`

**Comment by samueltardieu** [comment]
Octodroid didn't seem to like it :-)

**Comment by kumy** [comment]
Did it works on nightly builds? I've changed the regexp last week...

**Comment by Bananeweizen** [comment]
Does anyone know a trackable that currently still does have the mentioned special characters in the name? Otherwise this is much guessing from our side, but not really debugging anything.:)

**Comment by TofLaBeuze** [comment]
You can play with mine, I just renamed it today http://www.geocaching.com/track/details.aspx?id=3899632

**Comment by kumy** [comment]
Just renamed my test TB too.
With c4185f9 the trackable is listed while logging a cache. But characters after (including) the `<` are not shown.

On the logging page, the html for the TB is:
```
                <tr id="ctl00_ContentBody_LogBookPanel1_uxTrackables_repTravelBugs_ctl03_row">
			<td><a href="/track/details.aspx?tracker=XXXXXX">XXXXXX</a></td>
			<td>Lili<sup>2</sup> <3 abc</td>
			<td>
                        <select name="ctl00$ContentBody$LogBookPanel1$uxTrackables$repTravelBugs$ctl03$ddlAction" id="ctl00_ContentBody_LogBookPanel1_uxTrackables_repTravelBugs_ctl03_ddlAction">
				<option value="4298146">- No Action -</option>
				<option value="4298146_DroppedOff">Dropped Off</option>
				<option value="4298146_Visited">Visited</option>

			</select>
                    </td>
		</tr>
```

**Comment by kumy** [comment]
@samueltardieu 
> Does geocaching.com correctly escape it as < in the page? 

No, character `<` isn't `&lt;` in html. This is a bug from geocaching.com, isn't it?

**Comment by samueltardieu** [comment]
One in many. They fail to correctly escape user-submitted input in their output at several places.

**Comment by SammysHP** [comment]
The funny thing is that they *do* filter the string. For example

`foo <script>bar</script>` → `foo bar`
`foo <a href="#">bar</a>` → `foo <a href="#">bar</a>`
`foo <a href="javascript:bar">bar</a>` → `foo <a>bar</a>`
`foo <a href="#" onclick="xyz">bar</a>` → `foo <a href="#">bar</a>`

http://www.geocaching.com/track/details.aspx?id=2912588

**Comment by rsudev** [comment]
They filter it, but they obviously don't html-encode it and don't tidy it either. So in principle you can enter HTML there, but it just may be broken

**Comment by kumy** [comment]
This remind me #5119 which was closed as "won't fix".
Do we report issues found on geocaching.com?
