### ISSUE TITLE
Long tap on geoitem broken for Google Maps

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14534]
### Describe your problem!

User report on support:

long tapping on a cache / waypoint is broken for current release 2023.08.16, nothing happens.
(Long tap on free map space does work, though)

### How to reproduce?

- open map with Google Maps as map provider
- long-tap on a geoitem (with "long tap on map" being enabled)

### Actual result after these steps?

nothing happens

### Expected result after these steps?

popup to add this item to a route etc. should appear

### Reproducible

Yes

### c:geo Version

2023.08.16

### Additional Information

ticket 304806

**Comment by SammysHP** [comment]
Oh, I thought that was only implemented for mapsforge. Did it work with Google Maps before?

**Comment by moving-bits** [comment]
Yes, sure. I need to `bisect` yet to find out which change broke it. Maybe the new Google renderer.

**Comment by moving-bits** [comment]
The new Google Maps renderer seems to be the culprit (see #14446):
- Long tap did work before that PR, but does no longer work since that PR, 
- except if I limit initialization to `MapsInitializer.Renderer.LEGACY`

I'll prepare a revert of that PR to get release version back working, and we can look for a working solution with the new renderer on `master`.

**Comment by moving-bits** [comment]
Fixed with #14536, reopened #12023
