### ISSUE TITLE
Bottom navigation done wrong - problems with custom bottom navigation items 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14552]
### Describe your problem!

I like the idea of having the last bottom navigation icon customizable, however it is done completely wrong. 

### How to reproduce?

- set the last item e.g. to "settings" 

### Actual result after these steps?

When clicking on the last item the bottom navigation disappears. But even worse, there is no way to get back. When using the back button cgeo gets closed completely. 

### Expected result after these steps?

- Bottom navigation should always stay visible after using it

- c:geo should guide to the dashboard first before exiting 

### Reproducible

Yes

### c:geo Version

Since July 2023 (nightly) 

### Additional Information

Introduced in  #14419

**Comment by fm-sys** [comment]
Following up with this, now the back navigation inside the settings is broken.

Pressing back will exit the settings directly and go back to main instead of navigating up inside the settings.

**Comment by moving-bits** [comment]
> Following up with this, now the back navigation inside the settings is broken.
> 
> Pressing back will exit the settings directly and go back to main instead of navigating up inside the settings.

See PR #14588 for a fix
