### ISSUE TITLE
Make "system default" theme the default 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14573]
>> I'll have to add that we still use "dark" instead of "system default" as default. This can be changed of course...
>> 
>> But if we want to change the default theme, then maybe timely align it with other design changes (#14570) so that users only get confused once ;-) 
>
> Did not remember that, but you are right. Anyway we should not play around with that default IMHO.

It has historic reasons why c:geo uses dark mode as default. Back in the days the option "system default" didn't exist at all and light mode just had looked totally ugly.

Nowadays, users who appreciate dark themes have most probably turned their whole phone dark, while there is no reason to force users to a dark theme while they actually don't like it.

My vote clearly goes to automatic theme as default. Any opinions?

(extracted the discussion from #14569)

**Comment by Lineflyer** [comment]
AFAIR we discussed that in the past as we decided to implement the automatic settings and decided to still stay with black as default as it is kind of a branding since ever in c:geo.

**Comment by fm-sys** [comment]
I also thought that there was some kind agreement about it, but couldn't find anything related. To me it seems as if we just continued to use dark as the default at the time, without any discussion. (#10794) 

That's why I opened this issue. Apart from branding and habit, there is actually no real reason why c:geo should be dark IMHO. But I'm interested how others think about it...

**Comment by moving-bits** [comment]
I propose to use "automatic" for new installations. This won't affect existing users, even not when migrating to a new device (as long as they restore their settings from backup).

(Even though I'm using dark mode myself, it looks somewhat outdated compared to more recent apps. We could think of introducing _a few_ more colors into c:geo, chosen from a harmonized color palette, to make it look a bit more up to date visually... But that's a different discussion.)

**Comment by moving-bits** [comment]
> That's why I opened this issue. Apart from branding and habit, there is actually no real reason why c:geo should be dark IMHO. But I'm interested how others think about it...

There are OLED displays out there consuming less power when using dark colors, that's _one of_ the reasons why some people are using dark mode for their system / for their apps.

**Comment by fm-sys** [comment]
> There are OLED displays out there consuming less power when using dark colors, that's one of the reasons why some people are using dark mode for their system / for their apps.

Totally agree! But these users have system-wide dark mode enabled anyway ;-)

>  looks somewhat outdated compared to more recent apps. We could think of introducing a few more colors into c:geo, chosen from a harmonized color palette, to make it look a bit more up to date visually... But that's a different discussion.

Let's discuss this in context of #14570
