### ISSUE TITLE
Show which filters can only be used for offline caches

### ISSUE THREAD

**Issue by capoaira** [cgeo/cgeo#14577]
### Tell us your idea!

There are some filters that only can be used for offline stored caches. (e.g. favorite percentage, number of Logs)
It would be nice to see directly in the list of filters which are available on live map and which are only for stored caches.

### What solution would you suggest?

Maybe an extra online icon in the list, where you can select the filter.

**Comment by eddiemuc** [comment]
That's not as easy to implement as it may sound.

First, different connectors support different online filtering methods. For example:
- GC.com does indeed not support online filtering for favorite percentage, but e.g. opencaching.de does
- GC.com.supports online Attribute filtering. But only for premium
An overview of what is supported by which connector can be found here:  https://github.com/cgeo/cgeo/wiki/%22Search-by-Filter%22-support-by-c%3Ageo-Connectors

Second, some filters can be applied client-sided if the search API of the connector returns the needed data. For example, GC.com returns region/country data for caches on online search  so a filterbto this data can be applied client-sided. For other data (not returned by online search APi) this is not possible e.g. detailed log data.

So which filters should be marked how?

**Comment by capoaira** [comment]
Hm, I understand the problem.

One solution may be using more that one icon, for different connectors one, but that could be end in a unreadable icon flood 😅

**Comment by eddiemuc** [comment]
Suggested solution: online connector support table into handbook

**Comment by murggel** [comment]
I would add the table of https://github.com/cgeo/cgeo/wiki/%22Search-by-Filter%22-support-by-c%3Ageo-Connectors to the manual-section https://manual.cgeo.org/de/cachefilter

@eddiemuc  I have some questions
* Name: What is the difference between Okapi and SU? Does SU supports simple search (like *phrase*), but not complex patterns?
* D/T combined: also only one range supported?
* Favorites: Okapi - is the maximum for relative value also not supported?
* Owner: what is exact user-id / only whole name? Does SU supports then wildcards?
* How is the remaining search done? Only for offline stored caches? Or with the "light" version of the caches of the search-result?

It could look something like that:

<img src="https://github.com/cgeo/cgeo/assets/70113341/33a60ac6-015b-46c8-9b73-76953de33cc7.jpg">

**Comment by eddiemuc** [comment]
Answered below to best of my knowledge (out of my head)

For SU: I could never really try this out in reality, comments are based on features I found in the SUConnector code.

> * Name: What is the difference between Okapi and SU? Does SU supports simple search (like *phrase*), but not complex patterns?

I believe SU supports phrases. What is supported exactly I don't know (hence the generic term "simple search")


> * D/T combined: also only one range supported?

D/T combined supports a list of D/T pairs to filter for

> * Favorites: Okapi - is the maximum for relative value also not supported?

No

> * Owner: what is exact user-id / only whole name? Does SU supports then wildcards?

GC.com and okapi support only search for whole user-ids. No idea what works on SU.

> * How is the remaining search done? Only for offline stored caches? Or with the "light" version of the caches of the search-result?

Remaining search is done locally on downloaded caches ("light version "). Offline data is not intermixed. 

Filters are designed to return either true or false or inconclusive (eg because data is missing). Whether inconclusive filter marches are included in the result is selected by the user at the top filter level

**Comment by murggel** [comment]
Thanks for the answers

**Comment by murggel** [comment]
I will try to enhance the table with the  filters which are online available for offline caches and add links to the detail-section of the specific filter.

**Comment by bekuno** [comment]
@okainov Can you answer the questions for the SU connector?

**Comment by okainov** [comment]
>Name: What is the difference between Okapi and SU? Does SU supports simple search (like phrase), but not complex patterns?

SU API is just completely different, home-baked and has nothing to do with okapi :) "Simple search" should be supported, if not, I can fix it.

>Owner: what is exact user-id / only whole name? Does SU supports then wildcards?

I believe, no wildcards. Exact username should work, not sure about partial match (it works when doing search on the website directly, but might not be available in API). I'd suggest to stick to "only full username" for now.

**Comment by murggel** [comment]
Thanks for the information, l will add it accordingly

**Comment by murggel** [comment]
Instead of creating a new table, how about enhancing the existing ones?

![grafik](https://github.com/cgeo/cgeo/assets/70113341/12f83789-e148-46ab-b8a7-15e8228b5f8d)

...

**Comment by eddiemuc** [comment]
> Instead of creating a new table, how about enhancing the existing ones?
> 
> ![grafik](https://github.com/cgeo/cgeo/assets/70113341/12f83789-e148-46ab-b8a7-15e8228b5f8d)
> 
> ...

Good idea! But you have to make visible somehow that those restrictions only apply to online searches (not searches in stored lists)

**Comment by murggel** [comment]
> 
> Good idea! But you have to make visible somehow that those restrictions only apply to online searches (not searches in stored lists)

Correct, ok I will give it a try, otherwise separate table...

**Comment by murggel** [comment]
I think a new table is more flexible.
This would be fit for example as last entry in the section
https://manual.cgeo.org/en/cachefilter#available_filter_criteria
before
https://manual.cgeo.org/en/cachefilter#filter_criteria_details

![image](https://github.com/cgeo/cgeo/assets/70113341/1db35840-db3e-48d4-91e5-175c4a05922f)

**Comment by murggel** [comment]
In addition we can enhance the table with all filters with the information, if it is available online

![image](https://github.com/cgeo/cgeo/assets/70113341/1f715fb8-4baa-430e-8f4a-ffb0bda5a94f)

**Comment by murggel** [comment]
Further discussion about the table for the manual see  [cgeo-guide #77 ](https://github.com/cgeo/cgeo-guide/issues/77)

**Comment by murggel** [comment]
I updated https://manual.cgeo.org/en/cachefilter accordingly

**Comment by murggel** [comment]
German and english manual pages are added.
Should we then close here?

**Comment by moving-bits** [comment]
We do have a very detailed description for filters now, thanks to all who contributed! ❤️
