### ISSUE TITLE
OC Found Date Not Rendered

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#14582]
### Describe your problem!

For GC caches, we show whether cache was found by the user and in brackets, the date it was found:

`Status: Found (8/31/23)`

For OC caches we just say

`Status: Found`

I have done some investigations and I believe I know why that is: It is because the OKAPI service we use to fetch the cache object gives a boolean `is_found` but the `date_found` is not provided.

I have worked a solution for this but I am not (yet) deep enough in the code to fix it myself, however, I plan to do it so I am assigning it to myself unless somebody else wants to jump right at it.

### How to reproduce?

Just open load an OC cache you already found.

### Reproducible

Yes

### c:geo Version

2023.08.24

**Comment by moving-bits** [comment]
Where do we get the OC's found state from? Don't we get the found date from there as well? If so, we need to persist it in our database, if we want to display it without having to retrieve it every time we display cache's details.

Found data is stored by setting the `found` flag to `1` and storing date/time in the `visiteddate` column, so one might investigate further, why this is not filled for OC-based caches (value seems to be `0` always for those).

**Comment by eddiemuc** [comment]
> Where do we get the OC's found state from? Don't we get the found date from there as well? If so, we need to persist it in our database, if we want to display it without having to retrieve it every time we display cache's details.

As @baiti already wrote in the issuea initial description (and U double-checked this): the OKAPI does indeed only return an isFound-Flat but not a visited-date.

I assume for GC.com we either scrape the date from the web page or we use the "friends logs" service (I haven't checked implementation). Both options are not available for oc afaik

**Comment by moving-bits** [comment]
Ok, then a different approach could be to make an extra call to the API if found state is returned as `true` and query `user_logs_only` (https://www.opencaching.de/okapi/services/caches/geocache.html), then check for the date. (Do this on updating full cache only.) Requires a [Level-3 authentification](https://www.opencaching.de/okapi/introduction.html), though, - not sure what we are doing in our OKAPI-based connectors.
This should resolve both the "not all logs downloaded" and "don't know the username to compare against" issues.

**Comment by baiti** [comment]
> Ok, then a different approach could be to make an extra call to the API if found state is returned as `true` and query `user_logs_only` (https://www.opencaching.de/okapi/services/caches/geocache.html), then check for the date. (Do this on updating full cache only.) Requires a [Level-3 authentification](https://www.opencaching.de/okapi/introduction.html), though, - not sure what we are doing in our OKAPI-based connectors. This should resolve both the "not all logs downloaded" and "don't know the username to compare against" issues.

This is exactly what I do in my own personal project as I am not at all interested in any other logs anyway ;) This way it is for sure guaranteed to get the log with the date I found it.

Ideally OKAPI should address that problem and provide this in formation as a primary field, however, as it seems, OKAPI development has ceased long time ago.

**Comment by moving-bits** [comment]
> This is exactly what I do in my own personal project as I am not at all interested in any other logs anyway ;) 

Solution for c:geo could be to do an _additional_ call to that endpoint to identify logs by the current user. 

(At least if we don't retrieve the users uuid by any other means, store it, and compare retrieved logs against that uuid - but then we are back to "have we retrieved enough logs, so that the user's one is included?".)

**Comment by baiti** [comment]
> > This is exactly what I do in my own personal project as I am not at all interested in any other logs anyway ;)
> 
> Solution for c:geo could be to do an _additional_ call to that endpoint to identify logs by the current user.
> 
> (At least if we don't retrieve the users uuid by any other means, store it, and compare retrieved logs against that uuid - but then we are back to "have we retrieved enough logs, so that the user's one is included?".)

Yes indeed. And further up it was mentioned that this needs to be a Level 3. As far as I know, A Level 1 would be sufficient **if** we pass the `user_uuid` as a parameter. 

And having said that, I would also think that when we do the oauth dance with OC.de, we should persist those values somewhere, perhaps in a way like we do it with the tokens we receive during the dance. In my environment I do a "userinfo" call after getting the tokens and that call gets me all I need to know about the user. The username and also the UUID.

**Comment by baiti** [comment]
did a new commit into the PR, forgot to reference the issue_id in the commit message. I followed the approach @moving-bits suggested and did a separate request with just asking for the user's logs so there is, in this context, no need for a username or uuid. Pls review the PR again.

**Comment by moving-bits** [comment]
fixed with #14634
