### ISSUE TITLE
show notification when GC live map is throttled (HTTP 429)

### ISSUE THREAD

**Issue by capoaira** [cgeo/cgeo#14601]
Issue from geoclub: https://www.geoclub.de/forum/t/caches-werden-nicht-geladen.82695/

When you move the map too often (about 10 times per minute) the caches doesn't load. After some time the caches load again. 
Here is a video of the behaviour: https://1drv.ms/v/s!Am4rTBGtAHyblp0PUzWb0lRh6Gqdkg 
(After 30 s and after 70 s in the video)

This is because of restrictions by GS. You can see the same behaviour on the search map on the website. 

It could be a solution to inform the user with a message about this restriction.

**Comment by capoaira** [comment]
We jad the same problem with the GClh, maybe our solution can help:
https://github.com/2Abendsegler/GClh/pull/2124

**Comment by ztNFny** [comment]
GC has been throwing plenty of HTTP 429 errors for me lately - I think they're actively trying to ruin their site :-(
We should probably show a toast in case of HTTP 429, something along the lines of "Server responded with "Too many requests", please try again in a moment"

**Comment by eddiemuc** [comment]
Question: does this happen only when map is moved too quickly/frequently to new areas (resulting in attempts to download new caches) or does it also happen when moving the map e..g. forth and back between same two areas? Reason I am asking: the later should imho **not** result in frequent server calls because c:geo should temporarily cache already downloaded caches.

**Comment by capoaira** [comment]
This happens only if requests are necessary. When I move the map for and back, the caches stay on the map. But when I do that inaccurate, it load caches (orange loading indicator at the top) and it happened again.

**Comment by Lineflyer** [comment]
I think the suggestion of @ztNFny to handle the 429 is the thing we should do. That would also give a reasonable feedback to users but not modify timestamps or alike.
