### ISSUE TITLE
List notification permission + add permission request dialog in context

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14608]
_From @moving-bits in https://github.com/cgeo/cgeo/issues/14499#issuecomment-1720069246:_

[...] When reading https://developer.android.com/develop/ui/views/notifications/notification-permission it looks like we need to list the permission in the manifest + trigger the request dialog at some useful place. It explicitly recommends not to do so on program startup (as we do for the other rights with the wizard), but to do so "in context" and "after the user got familiar with the app". I'll open a separate issue for this.

**Comment by fm-sys** [comment]
> It explicitly recommends not to do so on program startup (as we do for the other rights with the wizard), but to do so "in context" and "after the user got familiar with the app".

That applies to all other permissions as well AFAIK. IMHO wizard is still fine...
