### ISSUE TITLE
Cannot access offline data settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14603]
### Describe your problem!

With current nightly 2023.09.13 I am not able to access the settings for "offline data".

### How to reproduce?

- c:geo Home screen
- Menu
- Settings

### Actual result after these steps?

The item "offline data" is greyed out, tapping doesn't do anything

### Expected result after these steps?

Normal access to the settings behind "offline data"

### Reproducible

Yes

### c:geo Version

2023.09.13-NB

**Comment by Lineflyer** [comment]
Is this a result of the new "extended settings" option?
If yes, I suggest we should either default to extended settings=on for existing installations or at least if the user has used those settings before. Its highly unexpected and looks like a loss of functionality or a bug.

**Comment by moving-bits** [comment]
> Is this a result of the new "extended settings" option?

yes

> If yes, I suggest we should either default to extended settings=on for existing installations 

that I would like to avoid as I guess many (most?) users are sort of overwhelmed by the multitude of options c:geo offers. The "pro" user can easily activate extended settings once and c:geo will remember their choice.

> or at least if the user has used those settings before.

How to detect that? (Which setting to use as indicator?)

> Its highly unexpected and looks like a loss of functionality or a bug.

IMHO the more stringent alternative would be to hide the offline data settings at all, same as we do with all other extended settings when extended mode is disabled.

**Comment by fm-sys** [comment]
IMHO the more stringent alternative would be to hide the offline data settings at all, same as we do with all other extended settings when extended mode is disabled.

Would be more consistent!

---



A general thing: I don't like the reduced settings in the current form at all. The main problem is, that it's not intuitive enough to enable "advanced mode". IMHO it's a must have to have this switch on top of the main settings screen.

**Comment by Lineflyer** [comment]
I perfectly understand the background of the change to create a basic set of settings.
I am somehow only struggling with the consequence, that also expert users will suddenly miss some options (and see a disabled main category....but that's secondary).
 
They will need to manually find the enabled of advanced settings down in the settings sub menu.
Most apps I know offers such switch quite prominently. How about having a big switch "Basic/Advanced" on the setting menu titlebar instead of burying it deep down below?

Sorry, if this was already discussed (did not follow the initial discussion but trying to get more involved again now).

**Comment by fm-sys** [comment]
Proposal / Implementation:

(I've used a switch instead of checkbox, cause it's not a preference but a filter from user perspective. Similar to basic/advanced for filtering, all/downloadable for PQ, ...)

![grafik](https://github.com/cgeo/cgeo/assets/64581222/3ab32200-3309-4017-90a8-940e5cd9d41e)

**Comment by Lineflyer** [comment]
Same minds think alike ;)

That looks nice...it could (if technically possible) also a switch in the titlebar.

Side question:
How would you expect c:geo to behave if users modified some advanced settings and then switch back to basic mode. I guess those advanced settings should be kept. Reason: I would like to avoid that the switching causes advanced settings to be lost. On the contrary resetting all advanced settings to default in this case (after confirmation) could be helpful to eliminate accidental wrong settings. Thoughts?

**Comment by fm-sys** [comment]
> That looks nice...it could (if technically possible) also a switch in the titlebar.

Probably possible, but not that easy though. Keep in mind that there is e.g. no room for explanation texts. And it'll be conflicting with the search bar...

> Side question:
> How would you expect c:geo to behave if users modified some advanced settings and then switch back to basic mode. I guess those advanced settings should be kept. Reason: I would like to avoid that the switching causes advanced settings to be lost. On the contrary resetting all advanced settings to default in this case (after confirmation) could be helpful to eliminate accidental wrong settings. Thoughts?

It behaves just like a visual filter currently. Nothing will be changed automatically. IMHO that's fine. 

"Reset all settings" is a totally different feature request IMHO

**Comment by Lineflyer** [comment]
> "Reset all settings" is a totally different feature request...

Indeed. Just wanted to clarify. Thats fine.

> Probably possible, but not that easy though. Keep in mind that there is e.g. no room for explanation texts. And it'll be conflicting with the search bar...

You are right.

**Comment by moving-bits** [comment]
Fixed with #14606 and #14609
