### ISSUE TITLE
custom connector icon broken

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14612]
![image](https://github.com/cgeo/cgeo/assets/1258173/690b1e2b-c2c2-4d2f-90b8-c5ffd824b1de)

**Comment by moving-bits** [comment]
`background_other` is non-square, but scaling assumed drawables to be squares. I have a fix available.

**Comment by ztNFny** [comment]
I broke the drawable recently, ill post a new version..but need the pc to do that

**Comment by moving-bits** [comment]
Ok, then I'll push the fix for non-square drawables as non-closing PR, so that you can close this issue with your updated drawable.
