### ISSUE TITLE
Wrong layout of missing T/D in 81er Matrix-Filter

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#14637]
### Describe your problem!

The Layout is not perfect
On my device the right columns are cut of and I can't scroll

Even in landscape mode it looks not really good...

### How to reproduce?

Create filter "Terrain / Difficulty Matrix"

### Actual result after these steps?

Portrait-mode

![Screenshot_20230918-095612_cgeo.jpg](https://github.com/cgeo/cgeo/assets/70113341/d712e425-833f-425e-ad86-1548ff047128)

Landscape mode

![Screenshot_20230918-095912_cgeo.jpg](https://github.com/cgeo/cgeo/assets/70113341/c39eb16a-7374-45ad-91a5-c2966e9ab71a)

### Expected result after these steps?

all columns should be visible
less space on the left side

### Reproducible

Yes

### c:geo Version

2023.09.18-NB-1e435eb

### System information

Device:

Device type: SM-G980F (x1sxx, samsung)
Available processors: 8
Android version: 12
Android build: SP1A.210812.016.G980FXXSCEUL7
Screen resolution: 1080x2178px (360x726dp)
Pixel density: 3.3000002
System font scale: 1.1 / used scale: 1.1
Sailfish OS detected: false
Google Play services: enabled - 23.34.14 (190408-560151436)
Memory:  Available:2,8 GB, Total:7,3 GB, Threshold: 216,0 MB, low:false

### Additional Information

_Originally posted by @murggel in https://github.com/cgeo/cgeo/issues/14579#issuecomment-1722920555_

**Comment by eddiemuc** [comment]
Should be fixed with PR #14646 

Rotated text views are really ugly to handle...

**Comment by murggel** [comment]
Thanks - Looks good now
