### ISSUE TITLE
Can't see notifications anymore

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#14633]
### Describe your problem!

I no longer see notifications when I update a list of caches.
The notifications are blocked by Android and it's not possible to switch them on - the notification screen under 'App info' is greyed-out.

Searching for a solution, I found this page, is this the problem?
https://source.android.com/docs/core/display/notification-perm

### How to reproduce?

1. load a list of caches
2. select 'Update all'

### Actual result after these steps?

The caches do get updated but there's no notification to show what's happening

### Expected result after these steps?

There should be a notification showing progress.

### Reproducible

Yes

### c:geo Version

2023.09.13-RC

### System information

c:geo version: 2023.09.13-RC

Device:
-------
- Device type: M2101K6G (sweet_eea, Redmi)
- Available processors: 8
- Android version: 13
- Android build: TKQ1.221013.002 test-keys
- Screen resolution: 1080x2177px (392x791dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 23.34.14 (190400-560151436)
- Memory:  Available:1.8 GB, Total:5.4 GB, Threshold: 648.0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:237
- Set language: en_GB (system default)
- System date format: dd/MM/y
- Time zone: GMT+01:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: 19 Sept, 13:37
- Last auto backup: 19 Sept, 14:05
- Routing mode: Off
- Live map mode: false
- OSM multi-threading: true / threads: 4
- Map: Norway_oam.osm (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:OpenStreetMaps/Norway_oam.osm.map
  - Atts: VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023
  - Theme: ElevateTheme_V5.zip:Elevate.xml

Filters:
-------
- Hide waypoints: -
- LIVE: None ([:inconclusive=false:advanced=true])
- OFFLINE: None ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#1):
- No Advlabs: [No Advlabs:inconclusive=false:advanced=true]AND(type:WEBCAM:TRADITIONAL:USER_DEFINED:LETTERBOX:WHERIGO:MYSTERY:EARTH:EVENT:CITO:VIRTUAL:MULTI;status:exclude_archived))

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Login OK) / PREMIUM
- Geocaching.com date format: dd MMM yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2023-07-21 09-39)
- Last successful login on geocaching.com: 2023-09-19 14-05
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions
-------
- android.permission.ACCESS_COARSE_LOCATION:: granted
- android.permission.ACCESS_FINE_LOCATION:: granted
- android.permission.READ_CONTACTS:: DENIED
- android.permission.READ_EXTERNAL_STORAGE:: DENIED
- android.permission.WRITE_EXTERNAL_STORAGE:: DENIED

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (34.3 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (34.3 GB free) v3 internal isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (34.3 GB free) v3 external non-removable isDir(465 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (34.3 GB free) v3 internal isDir(3 entries)
- Map render theme path: ElevateTheme_V5.zip:Elevate.xml
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=12, dirs:>=13, totalFileSize:>=117.6 MB, free space: 34.3 GB, files on device: 13511677)
  - OFFLINE_MAPS: /OpenStreetMaps (User-Defined)[/OpenStreetMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps/document/primary%3AOpenStreetMaps, Av:true, files:9, dirs:2, totalFileSize:6.6 GB, free space: 34.3 GB, files on device: 13511677)
  - OFFLINE_MAP_THEMES: /OpenStreetMaps/_themes (User-Defined)[/OpenStreetMaps/_themes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps%2F_themes::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps%2F_themes/document/primary%3AOpenStreetMaps%2F_themes, Av:true, files:2, dirs:0, totalFileSize:948.5 KB, free space: 34.3 GB, files on device: 13511677)
  - OFFLINE_MAP_SHADING: /OpenStreetMaps/_hgt (Default)[/OpenStreetMaps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps::/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps/document/primary%3AOpenStreetMaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 34.3 GB, files on device: 13511677)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:6, dirs:0, totalFileSize:636.2 KB, free space: 34.3 GB, files on device: 13511677)
  - GPX: /My Documents/SyncedWithGoogle/GPX (User-Defined)[/My Documents/SyncedWithGoogle/GPX[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX/document/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX, Av:false, files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=10, dirs:>=6, totalFileSize:>=239.2 MB, free space: 34.3 GB, files on device: 13511677)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 34.3 GB, files on device: 13511677)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 34.3 GB, files on device: 13511677)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81.2 KB, free space: 34.3 GB, files on device: 13511677)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 34.3 GB, files on device: 13511677)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 34.3 GB, files on device: -1)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #3
  - content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps (19 Sept, 13:47):RW
  - content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps%2F_themes (19 Sept, 14:04):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (19 Sept, 13:42):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v99, Size:53.4 MB) on user storage

--- End of system information ---

**Comment by ztNFny** [comment]
probably https://github.com/cgeo/cgeo/commit/fefbac550fc0ff859c12c46911ece62605f989a6 , thus already fixed

**Comment by bekuno** [comment]
> probably [fefbac5](https://github.com/cgeo/cgeo/commit/fefbac550fc0ff859c12c46911ece62605f989a6) , thus already fixed

This is in `release`, but not in the current beta version.
@moving-bits Maybe create today a new beta and the next release on Friday?

**Comment by moving-bits** [comment]
> @moving-bits Maybe create today a new beta and the next release on Friday?

Good idea, will do

**Comment by moving-bits** [comment]
Update to beta version is on the way, will be release `2023.09.19-RC`.

**Comment by moving-bits** [comment]
After installing the new version you will need to
- either run the configuration wizard from mainscreen to add the "notifications" permission,
- or grant this permission manually by calling Android's app settings for c:geo

if you want to see notifications for downloads (or approaching caches, if proximity notifications are activated).

**Comment by alan666notb** [comment]
How do you run the "configuration wizard"?
I don't see it anywhere

**Comment by moving-bits** [comment]
> How do you run the "configuration wizard"? I don't see it anywhere

It should be displayed in the "three dot menu" on c:geo's home screen after upgrading to today's beta version.

**Comment by alan666notb** [comment]
Ah yeah - it only appears when there's something to set.
Ran it and the notifications are back.
Thanks.
