### ISSUE TITLE
Ability to Rename Downloaded Offline Map

### ISSUE THREAD

**Issue by Saloframes** [cgeo/cgeo#14638]
### Tell us your idea!

I use c:geo's offline map Downloader in addition to downloading my own maps. I noticed that when downloading a map from Mapforge, c:geo will just call it by it's location without the download source in the name (i.e. "Colorado"). However, when downloading from OAM, c:geo will include the map source in the name (i.e. "Colorado (OAM)". This can cause issues when selecting an offline map because it doesn't show which version is being used. See screenshot. 

![Screenshot_20230919-181915](https://github.com/cgeo/cgeo/assets/5899823/85667b0a-b229-4f92-8701-b6599ec6f52d)

### What solution would you suggest?

I'd suggest a function or option where you can rename the maps downloaded by c:geo to something else. This will help distinguish the downloaded maps from one another.

**Comment by fm-sys** [comment]
Hi @Saloframes, 

the map display name is automatically created based on the file name, so you can just rename the map file in your storage. Hope this helps!

If you have any further questions feel free to reach out...

**Comment by moving-bits** [comment]
Downloads normally get the same file name they have on the server. OpenAndroMaps is an exception from this, as they have a somewhat crude and longish file naming system, so we shorten that a bit automatically.

As @fm-sys mentioned you can rename the resulting map files manually. But be careful in doing so, if you want to use the map updater. Each mapfile has a so-called "companion file" (same name as the map file + extra extension "-cgeo.txt". This file needs to be renamed similarly to the map file, and within that file the entry "local.file" needs to be adapted as well to keep the map updater working.
