### ISSUE TITLE
failing test testLanguageSwitch on CI

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#14648]
### Describe your problem!

Since PR #14646 we have in our CI at least in the commit build queue 
(e.g. https://ci.cgeo.org/job/cgeo-CI_commit-build/1546/) this failure:
~~~
23:56:46  cgeo.geocaching.connector.gc.GCLoginTest > testLanguageSwitch[android-30(AVD) - 11] [31mFAILED [0m
23:56:46  	org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
23:56:46  	at java.lang.reflect.Constructor.newInstance0(Native Method)
23:58:07  Tests on android-30(AVD) - 11 failed: There was 1 failure(s).
~~~

@eddiemuc this was your PR

### How to reproduce?

see e.g. https://ci.cgeo.org/job/cgeo-CI_commit-build/1546/

### Reproducible

Yes

### c:geo Version

CI commit-build 1546

**Comment by eddiemuc** [comment]
Build for mentioned PR passed w/o any test problem. See here: https://ci.cgeo.org/job/cgeo-CI_PR-build/6037/

Unless our CI is really messed up, the mentioned PR can't be the cause of the problem

**Comment by bekuno** [comment]
> Unless our CI is really messed up, the mentioned PR can't be the cause of the problem

I don't think either of these is/was the cause.

The error should be triggered at this point:
~~~
        final String userLanguage = GCLogin.getInstance().getWebsiteLanguage();
        assertThat(userLanguage).isNotNull();
~~~

Maybe there was/is a change or problem retrieving the website language.

I restarted the last job. Now it ran successfully.
(https://ci.cgeo.org/job/cgeo-CI_commit-build/1550/)

So I will check this in the next builds.

**Comment by bekuno** [comment]
No such error anymore.
Let's close.
