### ISSUE TITLE
[Nightly] "Settings" => "Logging" => "Log Templates" - section is missing

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14658]
### Describe your problem!

Just observed a kind of strange behavior:  When entering the ``Logging`` settings the "normal" way, the ``Log Templates`` section is missing:

![01 Log Templates - gone](https://github.com/cgeo/cgeo/assets/9889015/f4e1889b-6f4c-4897-a2cd-007cd9498274)

Even after leaving the [Logging] settings and re-entering it, they are still gone.

But: After c:geo either was sent to background an re-entered via [Recent Apps] or after the display switched off and the is switched on again, the ``Log Templates`` section is there as usual:

![02 Log Templates - there they are](https://github.com/cgeo/cgeo/assets/9889015/fdf806ed-790b-4046-8078-e091e3206e3c)

Thus I guess, this may be a timing problem ...?

### How to reproduce?

1. open ``Settings`` => ``Logging`` 
2. look for the ``Log Templates`` section - it will be gone.
3. optional: leave the ``Logging`` settings via back key and re-enter them - ``Log Templates`` will still be gone.
4. send c:geo to background (e. g. by pressing Android's Home button) or switch off the display
5. get c.geo back via ``Recent Apps`` button (resp. switch display on again)
6. the ``Log Templates`` section will be there as usual.

### Reproducible

Yes

### c:geo Version

2023.09.28-NB-e8040fb

**Comment by MagpieFourtyTwo** [comment]
Additional note: Don't know for sure, but this may possibly be related to activating the option ``Offline Logging`` (and testing the results, of course) - have activated this one for the very first time, and right after I noticed the missing section ... but may as well be that this behavior existed for a longer time already, cause I haven't changed the Log Templates for several weeks now.

**Comment by eddiemuc** [comment]
Probably a problem with the new "extended settings" switch?

**Comment by moving-bits** [comment]
Bug confirmed. I'll prepare a PR.

**Comment by MagpieFourtyTwo** [comment]
Looks good - thx for fixing!
