### ISSUE TITLE
Stuck ANR after adding log pictures

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14656]
From field...to be more precisely described later:

- Using 2023.09.26-NB (but also earlier builds from some days ago)
- Adding some photos to a log via file picker
- Long time of unresponsiveness in c:geo between confirming selection and finally photos are shown attached in c:geo logging screen (it shows the logging view but c:geo is not responsive)
- When c:geo is responsive again all looks normal but ANR system messages keep popping up every some seconds although I can use c:geo normally
- This repetitive ANR messages keep showing until I forcefully close c:geo

I had such stuck ANR before (documented in some issue) but in another context AFAIR.

**Comment by Lineflyer** [comment]
Old issue was #13995  Other cause but similar symptoms

**Comment by eddiemuc** [comment]
In general: if you experience ANR problems you should turn on debug mode and search in the log for entries starting with `LooperLogger`. This should provide some clarity on where the GUI loop is waiting/hanging. 

Specific to this case: probably image loading is wrongly executed in the main loop. If this is the case, above analysis should reveal it. 

If images are large and need rotation for display, then this might take some time (probably scaling down and rotating are not done in one step).

**Comment by Lineflyer** [comment]
I was unable to reproduce it. I did however notice a device issue with my SD card, where the pictures to be added to the log have been stored. It was really slow in accessing which was resolved after unmounting and mounting the SD.

Lets close for now.
