### ISSUE TITLE
Unable to edit custom geocache created by long-tap

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#14669]
### Describe your problem!

A recent functionality in c:geo allows the creation of custom geocaches by the user, which may help with hiding. 

A custom geocache can be created by long-tap on the map. This takes it's coordinates from the finger tap.
After creation, this geocache is no longer editable (ie edit coordinates). 
My finger doesn't have fine enough precision, but I have other tools to get location coordinates to my satisfaction, but I can't use them to set the correct coordinates to the custom cache, as the UI doesn't allow editing.

### How to reproduce?

1. long-tap on map
2. create custom geocache
3. fill in the proper fields

### Actual result after these steps?

Try to adjust/correct/edit the custom geocache coordinates. I could find no UI control to do this.
Neither the name is editable.

I can long tap on cache page on name or coordinates and copy them to clipboard or open sharing dialog. 
I can single tap on coords to show several formats.

I cannot edit anything. Adding addition waypoints, where one can edit coordinates manually, might be a short term workaround.

### Expected result after these steps?

Expect custom geocache to continue to be editable after creation.

### Reproducible

Yes

### c:geo Version

2023.09.26

**Comment by moving-bits** [comment]
You can change the name of a user-defined cache by short-tapping on the cache name on cache overview page.

Changing coordinates is done like for any other cache by creating a new waypoint and setting its coordinates for the cache.
In contrast to other cache types you can then delete both the manually created "final" waypoint as well as the automatically created "original coordinates" waypoint.

**Comment by andrixnet** [comment]
Handling waypoints for regular caches is known. 
For a custom cache, IMO, the expectation would be to edit coordinates directly rather then doing a boomerang style operation.

**Comment by SammysHP** [comment]
Today I got another request for this from a user during an event. I tried it myself and staggered that it didn't work by tapping or holding on the coordinates and that there was nothing in the menu.

Changing the coordinates might show the same dialog that is used to enter waypoint coordinates. If we also allow the use of the calculator, the cache coordinates could mirror the coordinates of a special (hidden?) waypoint.

**Comment by ztNFny** [comment]
I wouldn't want to change the tap (change format) or long tap (copy) actions as they've been established for a long time.
But maybe we can add a "modify coordinates" entry to menu?

**Comment by alan666notb** [comment]
> But maybe we can add a "modify coordinates" entry to menu?

Any "modify coordinates" option needs to have a "Select current location" option.

(If fact, it'd be useful to be able to have that when you create the cache - how do you create a user-defined cache at your current location?)

**Comment by moving-bits** [comment]
PR #16345 is a draft to implement this feature

**Comment by moving-bits** [comment]
PR has been merged meanwhile, so let's close here
