### ISSUE TITLE
Lab adventures losing found state on zoom

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14672]
User report on support:

"I am very happy with the new feature that lab caches automatically become visible on the map as found.  but unfortunately that doesn't work very well for me.  When I zoom in or out on the map, the color of the smileys suddenly changes back to purple.  If I close the app and start it again, they are yellow again until I zoom in or out again"

"It happens with all foud labs ! It happens with stored and unstored labs ! And always when i start cgeo i see them as found, but when i zoom in or out on the map the labs become visible as not found yet. But when i set them as found by manual option the stay visible as found."

### Extract from system information

c:geo version: 2023.08.24

Device:
-------
- Device type: ONEPLUS A3003 (OnePlus3, OnePlus)
- Android version: 9
- Android build: ONEPLUS A3003_28_191104
- Google Play services: enabled - 23.35.15 (100400-565551795)
- Memory: Available:1,7 GB, Total:5,6 GB, Threshold: 216,0 MB, low:false

Program settings:
-------
- Settings: v9, Count:211
- Set language: nl_NL (system default)
- System date format: dd-MM-yy
- Map: Google: Satellite

Filters:
-------
- Hide waypoints: -
- LIVE: Status: Uitgeschakeld uitsluiten, Gearchiveerden uitsluiten ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status:exclude_disabled:exclude_archived))
- OFFLINE: Geen ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
- geocaching.com: Logged in (Ingelogd) / PREMIUM
- Geocaching.com Adventure Lab
- opencaching.de: Logged in (Ingelogd)
- opencaching.nl: Logged in (Ingelogd)
- Geocaching.com date format: dd/MMM/yyyy
- Geocaching.com website language: nl-NL
- Last login error on geocaching.com: communication error (2023-07-02 12-46)
- Last successful login on geocaching.com: 2023-09-21 19-38
- Routing: internal / BRouter installed: false
- Installed c:geo plugins: contacts
[...]

### additional information
ticket 581385

**Comment by baiti** [comment]
I have not been able to reproduce this problem. Not on the production version (2023.09.26) of cgeo and not on the current nightly (2023-10-07) on the emulator. Not by zooming in and out as described above.

However, I believe I have an idea why we could loose the found state of an ALC. I will be available to discuss this with the team later.

**Comment by moving-bits** [comment]
Same user has reported a second device (different brand etc.) having the same problems. 

Could it be somehow related to the user's environment?
Anything I should ask the user with regard to this?

## Extract from system information of second device

c:geo version: 2023.09.26

Device:
-------
- Device type: SM-A525F (a52qnseea, samsung)
- Android version: 13
- Android build: TP1A.220624.014.A525FXXU6DWH2
- Google Play services: enabled - 23.37.17 (190400-570218080)
- Memory: Available:1,9 GB, Total:5,4 GB, Threshold: 303,0 MB, low:false

**Comment by baiti** [comment]
I'm quite sure it is related to what API method we're using. "SearchV4" which is used to populate the map gives us the correct state. Let me call it "getAdventure()" does NOT give us the state. So the question is, why does zoom in/out cause us to use the latter method? It must have something to do with caching, perhaps some sort of a LRU algorithm if we're short on storage or heap? I am just not deep enough into the application structure. However, as already stated, perhaps the way out of it is to modify that call `getAdenture(gc_code)` such that it first uses a `SearchV4()` which will only return ONE result, the one variable we can't get otherwise.

It would be of great help if we had a clear scenario how to reproduce this bug. @Lineflyer .... in the jitsi you said you'd try to reprodue, have you been able to do so?

**Comment by ztNFny** [comment]
Could it be related to a mix of live and stored info? If the cache is stored as "not found" and live map returns "found" this could explain some toggling. At least for caches also stored caches get some info from live map applied, e.g. viewing a stored as enabled cache that's currently disabled will on live map disable the icon.

**Comment by baiti** [comment]
interesting thought. So I would try to find an ALC that I have not yet finished, store it to a list in cgeo, and then finish it via an external app. The stored version in cgeo wouldn't know this and still render the stored version as not found. I would then navigate the live map until that specific ALC comes into view, this time it comes via the `SearchV4` function, wich knows the found state, renders it accordingly and when I then zoom in, (as in flying lower), at some point the stored version would win over the searched version and the found state goes away? Is that the scenario you have in mind and perhaps the scenario that could reproduce the bug?

**Comment by ztNFny** [comment]
That's what I'm thinking *might* be it, yes. In the "zoom in/out" part I guess the stored lab then falls outside the search radius (it's no longer included in search results) which then causes the fallback to only the stored info.
The lab wouldn't have to be "really" stored for this situation as c:geo caches geocaches on viewing them, so it might be loaded from DB without having the "stored" icon.

**Comment by ztNFny** [comment]
Successfully reproduced it:
1. in cgeo view an incomplete ALC - do not save it
2. complete that ALC
3. in cgeo (in my tests it was the same session, didn't leave map inbetween) scroll/zoom map to another position
-> ALC shows as found/not found randomly

**Comment by baiti** [comment]
> Successfully reproduced it:
> 
> 1. in cgeo view an incomplete ALC - do not save it
> 2. complete that ALC
> 3. in cgeo (in my tests it was the same session, didn't leave map inbetween) scroll/zoom map to another position
>    -> ALC shows as found/not found randomly
>    unfortunately I repoduced on my actual device, not in debugger :-(

I have worked a PR, however, it "should" address the issue, however, I can't really verify this since my premium account doesn't really do ALCs and some test accounts I have, are basic and ALCs don't work with basic users.

So, may I kindly ask you to verify whether the PR actually fixes it?

**Comment by moving-bits** [comment]
A while ago I have asked the user that had opened the ticket to cross-check this, which he committed to, but haven't heard back from him yet. Let's close here for now, and reopen if necessary.

**Comment by baiti** [comment]
If that issue is fixed with the referenced PR, then I'd say we should no longer need to offer the actions called
- Set as found
- Set as did not find
from the 3-dots pull down for lab caches.

These actions were necessary at a time where the true found state could not be obtained but this is no longer the case.

If you agree, I can open a new issue and try to work a PR for it

**Comment by fm-sys** [comment]
Yes, totally agree. We shouldn't offer it anymore, especially as it could be misleading... Users might think they can log labs from within cgeo and do not notice that the lab is not logged online.

**Comment by baiti** [comment]
> Yes, totally agree. We shouldn't offer it anymore, especially as it could be misleading... Users might think they can log labs from within cgeo and do not notice that the lab is not logged online.

good point! I hadn't even thought of that. Surprises me that nobody has asked for that ... yet ;)

I need to update the studio and gradle and checkstyle and all that has been discussed lately, then I will give it a try,

**Comment by moving-bits** [comment]
> I will give it a try,

have a look at `ALConnector.supportsSettingFoundState()` (defaults to `false` in `AbstractConnector`)
