### ISSUE TITLE
Share coordinate as a maps.app.goo.gl link (to Tesla in order to navigate to a cache)

### ISSUE THREAD

**Issue by 1337v411** [cgeo/cgeo#14678]
### Tell us your idea!

Would it be possible to add "share coordinate as a maps.app.goo.gl link" in addition to the text string "N DD° MM.MMM' E DDD° MM.MMM'" when doing a long press on the coordinates in the detailed cache info.
The reason I'm asking is that it would help me send the coord's to my Tesla navigator in order to navigate close to the cache I want to visit.

### What solution would you suggest?

After a long press on the coordinate in the detailed view, either ask in what format to share or add another share icon indicating that it would be shared as a google maps link.
Or maybe add a setting where you can choose in what format you would like to share coord's.

(This is how it works from google maps when sharing a coordinate to your Tesla https://tesla-info.com/blog/tesla-send-destination-to-car.php )

**Comment by Lineflyer** [comment]
You can use "Navigate" - "Other external app" and then select the Tesla app. Works good for me.

**Comment by 1337v411** [comment]
@Lineflyer Thanks, that sounds like the feature I need (and hadn't found) - will try it out.
