### ISSUE TITLE
Routing profiles: Add "Boat" resp. "Canoe" and "MTB"

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14700]
### Tell us your idea!

In [BRouter's routing profile downloads](https://brouter.de/brouter/profiles2/) I just stumbled upon "river.brf" - and was immediately caught by the arousing possibilities, because that's exactly what we've always missed when going for boat caches so far.

BTW: Perhaps [Canua](https://play.google.com/store/apps/details?id=com.touchingcode.canua&hl=en&gl=US) may be added to [c:geo's useful apps section](https://manual.cgeo.org/en/mainmenu/utilityprograms) cause even in the free version it's extremely helpful for planning boat caches.

However: Some "dry" couch tests showed good results - thus it would be great to have a corresponding button in the map quick settings (and of course profile settings, to choose which profile to use - default should be "river.brf", of course).

And perhaps a second choice for biking may be implemented in the same go, as we often switch between road bike (for commuting) and MTB (mtb.brf - for the fun) - but being forced to always change the profile via the route settings is a bit annoying. 

Icons could be like e. g. in [Komoot](https://www.komoot.de/plan/@49.0000000,9.2149000,9.000z?sport=mtb&constitution=4) resp. a minimalistic canoe like [this one](https://www.flaticon.com/de/kostenloses-icon/ruderboot_3124366) on flaticon.com.

![Routing Icons](https://github.com/cgeo/cgeo/assets/9889015/0588f2f1-5787-4707-948b-556fd5199b71) ![Boat](https://github.com/cgeo/cgeo/assets/9889015/8e7d0ab7-044a-4f4b-a427-7c0a1d0984e3)

### What solution would you suggest?

Additional routing profile choices for "Boat" resp. "Canoe" and "MTB".

### Is there an alternative?

Switching profiles in routing settings.

**Comment by moving-bits** [comment]
I'm no fan of introducing yet another profile category for such a specific use-case. 

But there is a way by which you can use profiles like `river.brf` already today: 

Copy the file into the folder `routing` beneath c:geo's base folder you have configured, then it will be available for selection for one of the already existing profile slots. (The dialog lists all `.brf` files in that folder.)

Same approach can be used for toggling between MTB and road bike profiles.

(One might think about adding a category "user-defined", though, to get one extra slot for easier toggling. TBD)

**Comment by MagpieFourtyTwo** [comment]
> Copy the file into the folder routing beneath c:geo's base folder you have configured, then it will be available for selection for one of the already existing profile slots. (The dialog lists all .brf files in that folder.)

This is in fact the way we do it today (and which I meant to describe in "Is there an alternative?")
But it's kind of cumbersome ... esp the nearly weekly change of "trekking.brf" vs. "mtb.brf".

**Comment by moving-bits** [comment]
> (One might think about adding a category "user-defined", though, to get one extra slot for easier toggling. TBD)

See PR #14700

**Comment by MagpieFourtyTwo** [comment]
> See PR #14700

Endless loop ...?  ;)  Guess you meant PR #14703 

Thx a lot!  Will check them out.

BTW: The current version of routing profile "trekking.brf" seems to give no results anymore. 
Guess it's a profile problem, or does it work for you?
