### ISSUE TITLE
[Nightly] c:geo can't open coord.info links from notification mails anymore

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14705]
### Describe your problem!

Got some mails from watchlist and publish notifications tonight, tried to open them by just clicking on the provided link (which is s/th like e. g. http://coord.info/GCA2C3A) but non of them worked.  Instead of just opening the listing, c:geo gives the toast "c:geo can't display the geocache you want. Is it really a geocache?".   Same applies to https-links from PGC notifications.  Opening these links in Iceraven still works ...

Maybe this is a local problem, but even if, it may somehow be connected to updating to the latest nightly, because before the update this worked for sure.

Any suggestion?

### How to reproduce?

1. Open any notification mail
2. Click on the provided cache link

### Actual result after these steps?

Fail

### Expected result after these steps?

Cache should open in c:geo.

### Reproducible

Yes

### c:geo Version

2023.10.09-NB-13be1c9

### System information

Device:
-------
- Device type: VOG-L29 (VOG-L29EEA, HUAWEI)
- Available processors: 8
- Android version: 10
- Android build: VOG-L29 10.1.0.150(C431E19R2P5)
- Screen resolution: 1080x2147px (423x841dp)
- Pixel density: 2.55
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: disabled - 23.36.14 (100400-567131450)
- Memory:  Available:3,2 GB, Total:7,4 GB, Threshold: 216,0 MB, low:false

Sensor and location:
-------
- Low power mode: active
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:362
- Set language: en_DE (system default)
- System date format: dd/MM/y
- Time zone: GMT+02:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: 9 Oct, 01:30
- Last auto backup: never
- Routing mode: Bike
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: Combined (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
  - Atts: _ DE BaWü Vosges.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / _ DE Germany.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / AT CH Alps.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / BE LUX Belgium Lux.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / DK Denmark.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / ES Spain Portugal.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / FR North.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / FR South.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / IT North.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / IT Sardegna.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / NL Netherlands.osm.map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023 /  / World.map: / mapsforge-map-writer-dev-SNAPSHOT
  - Theme: Elevate5_Locus/Elevate_Locus.zip:Elevate.xml

Filters:
-------
- Hide waypoints: original visited
- LIVE: -  Live (Hide Found, Own & Archived) ({"name":"-  Live (Hide Found, Own & Archived)","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"status","config":{"values":["owned_no","found_no","has_offline_found_log_no","exclude_archived"]}}]}})
- OFFLINE: None ({"advanced":true,"inconclusive":false})

Stored Filters (#12):
- -  Live (Hide Found, Own & Archived): {"name":"-  Live (Hide Found, Own & Archived)","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"status","config":{"values":["owned_no","found_no","has_offline_found_log_no","exclude_archived"]}}]}})
- - Stored (HQ + nice stuff): {"name":"- Stored (HQ + nicestuff)","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"status","config":{"values":["found_no","has_offline_found_log_no"]}},{"type":"stored_list","config":{"values":["353","162","356","36","358","299","365","45","366","306","371","245","376","377","314","250","125","381","384","321","385","129","258","324","68","261","199","396","77","337","210","339","148","406","407","344","347","283","155","348","220","352"]}}]}})
- - Stored (no rope, no water): {"name":"- Stored (no rope, no water)","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"attributes","config":{"inverse":true,"attributesources":3,"attributes":["rappelling_yes"]}},{"type":"attributes","config":{"inverse":true,"attributesources":3,"attributes":["swimming_yes"]}},{"type":"attributes","config":{"inverse":true,"attributesources":3,"attributes":["boat_yes"]}},{"type":"attributes","config":{"inverse":true,"attributesources":3,"attributes":["hike_long_yes"]}},{"type":"status","config":{"values":["owned_no","found_no","stored_yes","has_offline_found_log_no","exclude_archived"]}}]}})
- - Stored (no T4.5, T5): {"name":"- Stored (no T4.5, T5)","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"stored_list","config":{"values":["353","226","227","356","357","101","230","358","365","366","367","368","371","245","376","121","377","250","379","125","381","254","384","1","385","129","258","386","261","263","264","396","12","18","148","277","279","283","155","156","28","31","162","163","36","167","170","171","299","45","175","176","306","57","186","314","58","188","65","321","322","324","68","197","199","72","75","77","333","336","337","210","339","84","85","344","347","348","220","93","221","94","223","352"]}},{"type":"status","config":{"values":["owned_no","found_no","stored_yes","has_offline_found_log_no","exclude_archived"]}}]}})
- - Stored (rope climbing): {"name":"- Stored (rope climbing)","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"attributes","config":{"inverse":false,"attributesources":3,"attributes":["rappelling_yes"]}},{"type":"status","config":{"values":["owned_no","found_no","has_offline_found_log_no","exclude_archived"]}}]}})
- - Stored in any list: {"name":"- Stored in any list","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"status","config":{"values":["owned_no","found_no","stored_yes","has_offline_found_log_no","exclude_archived"]}}]}})
- Boat (Attribute+T5): {"name":"Boat (Attribute+T5)","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"difficulty_terrain","config":{"d":{},"t":{"min":5.0}}},{"type":"attributes","config":{"inverse":false,"attributesources":3,"attributes":["boat_yes"]}},{"type":"status","config":{"values":["owned_no","found_no","has_offline_found_log_no","exclude_archived"]}}]}})
- Description:Leiter: {"name":"Description:Leiter","advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"description","config":{"text":"Leiter","type":"contains","matchCase":false}}]}})
- HQ + Jasmer + Matrix needed: {"name":"HQ + Jasmer + Matrix needed","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"stored_list","config":{"values":["129","162","356","36","358","365","337","371","148","245","250","283","155","384"]}}]}})

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Login OK) / PREMIUM
   - extremcaching.com: Not logged in (Logging in…)
- Geocaching.com date format: dd MMM yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2023-09-14 06-59)
- Last successful login on geocaching.com: 2023-10-09 09-25
- Routing: internal / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- READ_EXTERNAL_STORAGE: granted
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (45,0 GB free) v3 internal isDir(10 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (45,0 GB free) v3 internal isDir(10 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (45,0 GB free) v3 external non-removable isDir(2 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (45,0 GB free) v3 internal isDir(4 entries)
- Map render theme path: Elevate5_Locus/Elevate_Locus.zip:Elevate.xml
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=12, dirs:>=11, totalFileSize:>=1,7 GB, free space: 45,0 GB, files on device: 13278715)
  - OFFLINE_MAPS: Memory card/Locus/mapsVector (User-Defined)[Memory card/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector, Av:true, files:>=52, dirs:>=6, totalFileSize:>=25,9 GB, free space: 85,3 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: Memory card/Locus/mapsVector/_themes (Default)[Memory card/Locus/mapsVector/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector%2F_themes, Av:true, files:15, dirs:3, totalFileSize:6,4 MB, free space: 85,3 GB, files on device: 0)
  - OFFLINE_MAP_SHADING: Memory card/Locus/mapsVector/_hgt (Default)[Memory card/Locus/mapsVector/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 85,3 GB, files on device: 0)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:2, dirs:0, totalFileSize:60,5 KB, free space: 45,0 GB, files on device: 13278715)
- GPX: /Download/GPX (User-Defined)[/Download/GPX[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX/document/primary%3ADownload%2FGPX, Av:true, files:85, dirs:0, totalFileSize:83,0 MB, free space: 45,0 GB, files on device: 13278715)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:12, dirs:4, totalFileSize:2,2 GB, free space: 45,0 GB, files on device: 13278715)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:2, dirs:0, totalFileSize:24,5 KB, free space: 45,0 GB, files on device: 13278715)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:>=5, dirs:>=39, totalFileSize:>=1,4 MB, free space: 45,0 GB, files on device: 13278715)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:21, dirs:1, totalFileSize:225,7 KB, free space: 45,0 GB, files on device: 13278715)
  - ROUTING_TILES: Memory card/Android/media/btools.routingapp/brouter/segments4 (User-Defined)[Memory card/Android/media/btools.routingapp/brouter/segments4[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3AAndroid%2Fmedia%2Fbtools.routingapp%2Fbrouter%2Fsegments4::]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3AAndroid%2Fmedia%2Fbtools.routingapp%2Fbrouter%2Fsegments4/document/0123-4567%3AAndroid%2Fmedia%2Fbtools.routingapp%2Fbrouter%2Fsegments4, Av:true, files:15, dirs:0, totalFileSize:1,3 GB, free space: 85,3 GB, files on device: 0)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 45,0 GB, files on device: -1)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/0123-4567%3AAndroid%2Fmedia%2Fbtools.routingapp%2Fbrouter%2Fsegments4 (9 Oct, 09:30):RW
  - content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGPX (9 Oct, 09:35):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (9 Oct, 08:56):RW
  - content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector (9 Oct, 09:22):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v100, Size:547,1 MB) on system internal storage

--- End of system information ---

**Comment by struppi1963** [comment]
Opening links also doesn't work from other applications e.g. WhatsApp

**Comment by MagpieFourtyTwo** [comment]
Just downgraded to yesterday's version (2023.10.08-NB-3b28b53) and now it works again.
Thus it really seems to be an issue with latest nightly.

BTW:  While re-installing and starting c:geo for the "first" time, I first had to grant access permission for the base folder (which most probably is mandatory, even if I just want to restore a backup, in order to get access to the backup files), but then, to my very surprise, I was asked by the Assistant to enter my gc.com credentials (which would come with the restore, anyway, thus there should be no need to ask for, IMHO). In the next step I was asked for offline map configuration - and that's where I was asked to restore a backup for the first time (one step too late, I would say). So I restored it, and then ... was confronted with the very same offline map configuration screen as I got before, although the restore seemed to work (although there was no success confirmation, but there were no errors neither), and again I had the options to either click ``OFFLINE MAPS`` or ``RESTORE`` - why that?  I of course had the possibility to just ``SKIP``, but it's all but clear what the consequences of this ``SKIP`` will be ...

In fact, pressing ``SKIP`` and ``FINISH`` (plus granting access to photos and media) eventually did the job and c:geo started in my restored environment, but this behavior is kind of weird ... IMHO, if the backup has successfully been restored, c:geo should a) give a success message and b) just tell me that it has to restart ... or is there any other reason I just don't get which is hindering the "automatic" re-initialization by simply immediately restarting with the just restored environment ...?

Pls. let me know if I got s/th wrong - otherwise I would open a dedicated issue for the restore process.

**Comment by MagpieFourtyTwo** [comment]
Hmm, another issue with restoring: Map folder is not set as it was before. Guess I really have to open a dedicated issue ... will do so till noon.

**Comment by bekuno** [comment]
Maybe a side effect updating `androidx.lifecycle`?

**Comment by struppi1963** [comment]
> Just downgraded to yesterday's version (2023.10.08-NB-3b28b53) and now it works again. Thus it really seems to be an issue with latest nightly.


Unfortunately, I'm not a power user... WHERE can I find the previous version to download?

**Comment by MagpieFourtyTwo** [comment]
AFAIK previous Nightlies are not available online anymore. That's why I always store the appropriate apk along with my daily backup.
Perhaps you may check your download folder for your previous apk download.
If you need it badly, just let me know, I can put yesterday's nightly on e. g. wetransfer.com.

**Comment by struppi1963** [comment]
If you could do that, that would be wonderful!

**Comment by MagpieFourtyTwo** [comment]
But be aware that you have to uninstall c:geo first, thus your backup should be very up-to-date.

**Comment by MagpieFourtyTwo** [comment]
https://we.tl/t-GxnZPzF2c0

Gib urz Bescheid, wenn Du es runtergeladen hast, dann lösche ich den Link wieder.

**Comment by struppi1963** [comment]
Thank you, I have loaded the file. You can now delete the link.

**Comment by MagpieFourtyTwo** [comment]
Ah, pwd is "c:geo".

**Comment by MagpieFourtyTwo** [comment]
Surprisingly quiet here ...

Pretty unfortunate - because the loss of this functionality is an absolute update-stopper. At least for me.

**Comment by Lineflyer** [comment]
I cannot reproduce this. Opening coord.info links worked and works all the time for me.

Any special circumstances or preconditions for the problem to show up, which I missed to read above?

**Comment by MagpieFourtyTwo** [comment]
> I cannot reproduce this. Opening coord.info links worked and works all the time for me.

Strange - cause apart from @struppi1963, there were at least 5 others who had the same problem (and these are just the ones I did a downgraded for resp. at least supported to do so).  Maybe OS dependent?  Will add system info for more info.

> Any special circumstances or preconditions for the problem to show up

Most regretfully not - there have been no changes at all, not even any (other) app update.
I just installed yesterday's nightly and afterwards opening links of notifications did not work anymore.
Is there any way to debug why c:geo refuses to open the corresponding cache?
Although I have to admit that my enthusiasm WRT reinstalling the current version is severely limited, having yesterday's problems with restoring the settings in mind ...  :/

**Comment by struppi1963** [comment]
I also hadn't made any changes or updates. Like (almost) every morning the update was installed and then it stopped working. Not from Gmail and not from WhatsApp either. Opening it from the original geocaching app also doesn't work. The message says: cgeo cannot display this cache. Is it really a cache?
I use a Galaxy S23 Ultra with all relevant updates.

**Comment by Lineflyer** [comment]
Oh well. My device was offline and it did not show the nightly update notification.

Long story short:
2023.10.06-NB works, 2023.10.10-NB same problem.

**Comment by Lineflyer** [comment]
@moving-bits  Maybe related to Android Beam removal??

**Comment by moving-bits** [comment]
I can try to look into it later tonight

**Comment by Lineflyer** [comment]
Given the working and not working commits provided above, one of those commits is the culprit:

![image](https://github.com/cgeo/cgeo/assets/949669/abb6f9bc-2dac-4771-a607-0cd1eca768c8)

**Comment by moving-bits** [comment]
Found the bug: PR for removing AndroidBeam deleted too much (due to unforeseen side-effect in AndroidBeam code).

**Comment by MagpieFourtyTwo** [comment]
It's working again - thanks for fixing!
