### ISSUE TITLE
Automatic upload for cache note

### ISSUE THREAD

**Issue by capoaira** [cgeo/cgeo#14702]
### Tell us your idea!

It would be great if it was possible to automatically upload the personal cache note after editing (or once a day if something changed). I often forget this and have heard from others that they forget this too. Many of the notes I make in c:geo are lost.

### What solution would you suggest?

An option in the settings for an automatic upload (after every change, or once a day)

**Comment by ztNFny** [comment]
In Note edit dialog you have the option to "save and upload" the note in addition of just "save" - the "cloud"-button
