### ISSUE TITLE
Trackable search field is tagged as a password field?

### ISSUE THREAD

**Issue by brivars** [cgeo/cgeo#14710]
### Describe your problem!

All the other search fields act as normal input fields but the "Trackable identification" field brings up Google password manager offering to use saved passwords in it.
I often have to tap away the overlay that appears, when I go to search for a trackable.
Now, I'm not quite sure if this is specific to certain version of Android but it surely is a case of the search fields somehow being tagged differently because for no other fields it ever offers to use a saved password.
![Screenshot_20231010-120431](https://github.com/cgeo/cgeo/assets/26169578/9b53490f-0803-4cda-8b65-15a59827a732)

### How to reproduce?

It doesn't appear every time but if I close c:geo, then force stop it and clear the cache, next time I will open it and go to search for the trackable, it pops up again.

### Reproducible

Yes

### c:geo Version

2023.09.26

### System information

```text
Device: Pixel 4A (5G)
Android: 13, build TQ3A.230901.001
```

**Comment by Lineflyer** [comment]
@brivars 
If possible could you use our tomorrow nightly version to test, whether the problem is solved?
Else please kindly provide feedback after trying next beta or feature release.

**Comment by brivars** [comment]
@Lineflyer I tried the nightly build and it is resolved :)
