### ISSUE TITLE
Logbook (Owner)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14720]
User request on support:

Request logs from owner of a cache and present them on a separate logbook page.

This would easify process to see maintenance logs, announcements etc.

ticket 346794

(Related question: Is there a way to only retrieve logs from the owner of a cache? Otherwise it would be pure chance whether we catch some logs from the owner within the first x logs we retrieve for a cache.)

**Comment by Lineflyer** [comment]
IMHO there is no direct way to load all logs from a certain user for a certain cache.

Thus it would require us to be able to load all logs first and filter ourselves.

**Comment by Lineflyer** [comment]
But an interesting and sometimes helpful thing in general.

GClh supports that:
![image](https://github.com/cgeo/cgeo/assets/949669/6c734c77-d032-49af-9105-00fc1611e7df)

**Comment by ztNFny** [comment]
GClh fetches ALL logs of a cache to then extract the relevant ones.
Imho this is not something we want to do. It'd make the (especially on bad mobile connection) already slow cache loading even sloooower.
