### ISSUE TITLE
Waypoint actions not working on routing targets

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14728]
Single waypoint navigation targets behave different than other waypoints:
- Error 1: Waypoint popup will not open
- Error 2: "Add to route" leads to error message "error toggling waypoint" (`NewMap`) / "not available in single waypoint mode" (`CGeoMap`)

How to reproduce:
- open a cache
- swipe to waypoint view
- set one of the waypoints as navigation target by long-tapping on the symbol right of the waypoint name
- (map will then open, displaying the selected waypoint as navigation target)
- error 1: short tap on this waypoint => waypoint popup should open, but does not
- error 2: long-tap on this waypoint => context menu opens => select "add to route" => waypoint should be added to individual route, but an error message is displayed

I've debugged a bit into error 2: `IndividualRoute.toggleRouteItem()` fails, as `RouteItem` is no valid Waypoint `RouteItem`. This tracks back to instantiation of `RouteItem(GeoItemRef)`, as `DataStore.loadWaypoint()` returns null due to waypoint id being -1.

Expected behavior:
- If a single waypoint navigation target is an actual waypoint, both actions should work.
- If a single "waypoint" navigation target is just coordinates, adding to route should work.

**Comment by Lineflyer** [comment]
AFAiR the single waypoint map never had many action associated besides showing the waypoint on the map. I might be wrong though.

**Comment by moving-bits** [comment]
I guess there has never been much action possible on single waypoint map, so it would be a feature request from my side to allow the regular waypoint actions, if the waypoint is more than just coordinates (eg from a search).

Having a long tap popup with non-functioning "add to route" etc. options is a bug, though, IMHO.

**Comment by moving-bits** [comment]
Implicitly solved for UnifiedMap with #15150 - in contrast to other map types, UnifiedMap actually displays a `Waypoint` item, if a waypoint got set as target, not just a waypoint icon.

As this is a somewhat specific case, I see no need to fix this for the old maps, so let's close here.
