### ISSUE TITLE
Hide navigation options only relevant for internal routing if that's not enabled

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14721]
Some routing-related options are only relevant for internal routing, but not for external routing or when no routing is enabled.
We do hide some of the internal routing-options already, if internal routing is not enabled, but some options are still active (eg: routing profile selection). Those should be hidden as well.

- label for "route calculation distance" (in settings => routing/navigation; should only be visible if at least one routing method is active)
- routing profiles (in settings => routing/navigation; should only be visible if internal routing method is active)
- user-defined profiles and label for it (in map quick settings; should only be visible if internal routing method is active)

**Comment by Lineflyer** [comment]
Question would also be in general:
Is it worth to keep the external routing support? IMHO only very few users will actively install the native brouter app. Couldn't we drop that and focus on the internal implementation?

**Comment by fm-sys** [comment]
I'm using external BRouter for other apps and don't want having to download routing tiles twice. Furthermore, the tile download selection in the external BRouter app is _way better_ then what we currently have

**Comment by fm-sys** [comment]
> But to speak of c:geo: What are you missing / disliking in c:geo's ways of downloading the routing tiles? How can we improve?

As far as I can tell c:geo doesn't have any tile downloader at all. I have to hope that the necessary tiles get recommended to me, and deleting / updating individual tiles is not possible at all. (OK, both is actually possible but completely lacks of a proper GUI. How should I know which is the correct tile I want to delete or update?)

> Funny, for me this was probably the most annoying part of BRouter back

What's wrong with it? Cannot find a single issue with it. It shows a map and once selected, downloads are made in background... Exactly what users need.

**Comment by moving-bits** [comment]
We have two ways in c:geo for downloading tiles:
- If you try to calculate a route and routing tile data is missing, c:geo asks you if it should download the missing data. If you deny the download, c:geo will remember this decision for the current session.
- Or you can zoom in the map to cover the area you want to download routing data for, select "Check for missing routing data", and c:geo will offer you to download missing routing data. The actual download will be handled in the background.

The latter is somewhat similar to what BRouter app offers, but it's easier to zoom to the desired place.

Updating tiles is an integrated part, either automatically in a user-selected interval, or started manually.
Deleting tiles is a point, though, at least for those regularly downloading tiles for visits in foreign countries.

> > > Furthermore, the tile download selection in the external BRouter app is way better then what we currently have
> >
> > Funny, for me this was probably the most annoying part of BRouter back
>
> What's wrong with it? Cannot find a single issue with it. It shows a map and once selected, downloads are made in background... Exactly what users need.

Back then when I have used it the last time, the map was very grainy, did barely support zooming, so it was somewhat hard to find the right tiles (maybe except for your home location). Checking for updates was not possible at all in the beginning (IIRC), and later a bit cumbersome to get into update mode

**Comment by eddiemuc** [comment]
I was not aware of the "check missing routing data" function. That's actually very cool!

**Comment by eddiemuc** [comment]
> I'm using external BRouter for other apps and don't want having to download routing tiles twice. 

c:geo stores the routing data in an external folder which should also be reachable by the external BRouter. Vice versa, if external BRouter exposes it's downloaded tile data in an external folder, c:geo could use it as well. 

How does external BRouter makes the tile data accessible to other apps? If it doesn't do that this sounds like a feature lack on their side.
