### ISSUE TITLE
Next feature release 2023.10.xx

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14731]
I'll start preparing a new beta version tonight. Let's use this thread to collect any issues that arrive during beta phase that need to be fixed before final release. Feel free to edit this initial post for adding such issues:

- [ ] ?? #14736
- [x] #14681
- [x] #14729 (cherry-pick from `master`)
- [x] #14744
- [ ] ?? #14745
- [x] #14760

**Comment by moving-bits** [comment]
I'll start preparing a new beta version now:

- [ ] Empty `changelog_bugfix.md` on branch `master`
- [ ] Wait for a Crowdin cycle or trigger sync manually for branch `master`
- [ ] Merge the related Crowdin translation pull requests for branch `master`
- [ ] Delete outdated translations branch for `release`
- [ ] Fast forward `release` branch to HEAD of `master`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by bravewolfcz** [comment]
I don't know how to edit the opening post, so I'll write a new one.
The Show elevation info for current position on map option will start chopping the map when enabled. After turning off the elevation option, the map moves smoothly again.
Pixel 6 Pro Android 14
C:geo 2023.10.15-RC2

**Comment by Lineflyer** [comment]
Added #14681 above

**Comment by moving-bits** [comment]
I propose to include #14729 in beta version as well (cherry-pick from `master`). It's available in master since a couple of days, we have no complaints about this fix at all (though, admittedly, it's a specific use-case), review was fine, and it's limited to AL connector anyway.

**Comment by moving-bits** [comment]
I'll start preparing a new beta release now:

- [ ] Wait for a Crowdin cycle or trigger sync manually for branch `release`
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Cherry pick #14729 to `release`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by Lineflyer** [comment]
In general current nightlies and the beta seems to perform good.

I opened two issues as I would like to discuss them with the team before we introduce them to the users:
- #14756 
- #14757

**Comment by fm-sys** [comment]
The map elevation is not shown by default, so it's not a blocker IMHO. (Although I agree that we should do some optimization there.) Elevation on homescreen hasn't changed compared to previous versions, so this shouldn't be discussed on the release channel at all. 

=> IMHO we should release as soon as possible (and don't wait for after the weekend). If any problems should occur we can fix them via a bugfix release. It's still way better compared with breaking core features - keep in mind that it takes quite some time until the update received on the majority of devices.

**Comment by Lineflyer** [comment]
> => IMHO we should release as soon as possible (and don't wait for after the weekend). If any problems should occur we can fix them via a bugfix release. It's still way better compared with breaking core features - keep in mind that it takes quite some time until the update received on the majority of devices.

Sounds reasonable, I agree. 
Lets roll it out as soon as possible if there are no blocking items (see also info in internal discussion).

**Comment by moving-bits** [comment]
I'll start working on a feature release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by Lineflyer** [comment]
Facebook posting is done (incl. crosspost to some geocaching groups).
I can not post on X as it introduced a 2FA, but its not my mail address where they send the confirmation code to... @mucek4 Maybe you received it?

**Comment by Lineflyer** [comment]
@moving-bits You might want to have a look into support ticket 118609 
On Facebook there are several users with this issue (not showing any distance to a cache after upgrade). I did not manage to reproduce it. Not sure what setting might got lost...

**Comment by Lineflyer** [comment]
> @moving-bits You might want to have a look into support ticket 118609 On Facebook there are several users with this issue (not showing any distance to a cache after upgrade). I did not manage to reproduce it. Not sure what setting might got lost...

I took this and some other issues reported by users to dedicated issues, which is probably better to track those down.
All issues deal with the map distance infos btw.

**Comment by moving-bits** [comment]
We have several issues with regard to distance info (thanks @Lineflyer for creating the issues) - for some users info is missing completely, for others it's flickering, and some can't change from regular to super-size view. No clear reproducibility in general and no clear pattern yet, but constantly happening for the users affected.

This is very likely related to the refactoring of the distance info view. Where we had an ugly mess of quite a few dedicated views for regular and supersized views in the past, it's been consolidated to just a few remaining views / containers, which get filled dynamically. Sadly, it seems to be non-working under certain, yet unknown, conditions.

The refactoring is also the base for the new elevation info for current position, where we have a separate active discussion about.

Therefore my proposal:
- Remove the elevation info for now and revert the PR related to both refactoring the distance views (#14668, #14690) and elevation info (#14671).
- This will also require to revert the new distance info icons (#14752) sadly, but those may be implemented separately from both refacoring and elevation info.
- Postpone the refactoring of distance info for now and let's restart on `master` later, when we have a better understanding on the patterns causing problems for some users.
- Discuss the whole topic of "elevation-related info" and restart implementation of it when we have a clearer image of what we want to achieve.

**Comment by moving-bits** [comment]
I'll start preparing a bugfix release now to get a fix for #14763/#14765 out (as well as other bugfixes already included on `release`).

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by Lineflyer** [comment]
Default update notification triggered and posted to Facebook (X is still not working).

Will replace the default notification by a urgent reminder on/after the weekend.

**Comment by Lineflyer** [comment]
As we have some regressions and fixes, we might think of another bugfix release to be deployed rather soon.
Especially #14825 is kind of urgent. I merged the PR containing the fix to `release` and also back to `master`. New nightly is compiling just now.

I will use it today for caching and storing notes and report back here.

**Comment by moving-bits** [comment]
> I will use it today for caching and storing notes and report back here.

I can create a bugfix release on Monday, just drop me a note if the fix is working for you

**Comment by Lineflyer** [comment]
@moving-bits 
Its working in principle (also confirmed by @magpie) but in some corner cases there is still a problem. However much better than before.
Bugfix release tomorrow therefore appreciated, changelog has been completed and uploaded to Crowdin, you may need to trigger/fetch the translations.

**Comment by Lineflyer** [comment]
Is a502220453ad3f71c612f50410caac3ce495ee78 included for this release?
Works perfect for me and the solution looks much cleaner codewise.

**Comment by moving-bits** [comment]
> Is [a502220](https://github.com/cgeo/cgeo/commit/a502220453ad3f71c612f50410caac3ce495ee78) included for this release? 

Yes, PR #14830 has been merged to `release` this morning and thus will be included in the bugfix release.

**Comment by Lineflyer** [comment]
@moving-bits 
Rollout of 2023.11.13 was limited to 1% of users on Play Console. Was this intentional?

**Comment by Lineflyer** [comment]
I updated staged rollout to 100% as I don't see a reason for it. I guess it was a mistake.

**Comment by moving-bits** [comment]
> I updated staged rollout to 100% as I don't see a reason for it. 

Thanks

> I guess it was a mistake.

Exactly. The default value for public releases is 1% (whereas for beta releases it's 100%), and I forgot to update it to 100%.

**Comment by Lineflyer** [comment]
Notification triggered for 2023.11.13

**Comment by moving-bits** [comment]
I'll start preparing a new bugfix release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
As we have several reports on support regarding missing TB inventory I propose to create a new bugfix release including #15048 (thanks @eddiemuc for diving into this).

Will do so tomorrow morning, if no one stops me.

**Comment by moving-bits** [comment]
I'll start preparing a new bugfix release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
We have accumulated a couple of [bugfixes on `release` branch](https://github.com/cgeo/cgeo/blob/release/main/src/main/res/raw/changelog_bugfix.md), thus I propose to publish a new bugfix release.

Will do so tomorrow evening if no one objects.

**Comment by moving-bits** [comment]
I'll start preparing a new bugfix release now. This may be the last version before a UnifiedMap beta, who knows ;-)

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by Lineflyer** [comment]
I found the release to be out several days but release is still on deployment on status.cgeo.org.
I therefore set it to "release" to enforce notification for users of older versions.

**Comment by fm-sys** [comment]
Let's close in favor of https://github.com/cgeo/cgeo/issues/15200
