### ISSUE TITLE
Display problem with elevation info enabled

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14736]
_Originally posted by @bravewolfcz in https://github.com/cgeo/cgeo/issues/14731#issuecomment-1764250856_

[...]
The Show elevation info for current position on map option will start chopping the map when enabled. After turning off the elevation option, the map moves smoothly again.

Pixel 6 Pro 
Android 14

C:geo 2023.10.15-RC2

**Comment by moving-bits** [comment]
@bravewolfcz
Thanks for reporting this issue. I've created a separate entry for it, so that we can discuss things related to this issue without overflowing the aggregate issue for the beta version.

Some questions regarding this issue:
- What do you mean by "chopping the map"? Can you provide a screenshot?
- Which map type are you using (Google Maps or OpenStreetMap)? Does it happen on both map types?
- Is only elevation info affected or the other infos at the map's top (distance to target, route length) as well?

**Comment by bravewolfcz** [comment]
[https://youtu.be/D15xLNavvmU](https://youtu.be/D15xLNavvmU) 

> @bravewolfcz Thanks for reporting this issue. I've created a separate entry for it, so that we can discuss things related to this issue without overflowing the aggregate issue for the beta version.
> 
> Some questions regarding this issue:
> 
>     * What do you mean by "chopping the map"? Can you provide a screenshot?
> 
>     * Which map type are you using (Google Maps or OpenStreetMap)? Does it happen on both map types?
> 
>     * Is only elevation info affected or the other infos at the map's top (distance to target, route length) as well?

[https://youtu.be/D15xLNavvmU](https://youtu.be/D15xLNavvmU)

**Comment by moving-bits** [comment]
Thank you for providing the video. I'm still not sure if I understand the problem, though: Google Map Satellite seems to work identically with or without elevation info, and for OSM online maps there's sometimes a white tile temporarily - which is normal behavior when map tiles need to be loaded from the server and can happen with or without elevation info (as you can see at position 0:55, for example).

**Comment by bravewolfcz** [comment]
My only point was that when the altitude display is turned off, moving around the map is smoother. One more thing I discovered.
Waypoints stop displaying when zoomed out.
![Screenshot_20231019-112816~2](https://github.com/cgeo/cgeo/assets/109043292/ad742510-4733-4882-a094-4ce27a61f691)

![Screenshot_20231019-120337~2](https://github.com/cgeo/cgeo/assets/109043292/df04cbec-52ac-435e-8389-4979560b1b5c)
![Screenshot_20231019-112836~2](https://github.com/cgeo/cgeo/assets/109043292/19bf2bd5-0fbc-4d40-a61e-9a2e0f0fe0e8)

**Comment by moving-bits** [comment]
This may be due to elevation info having been retrieved from map data in the past. In the meantime we have changed to use elevation info from GPS signal, which should not cause any delays anymore.

@bravewolfcz 
Does "chopping" still occur for you with recent release, if you have elevation info enabled, or can we close this issue?

**Comment by bravewolfcz** [comment]
After the update, everything is smooth. You can close this issue.
