### ISSUE TITLE
Login failed reason not correct

### ISSUE THREAD

**Issue by HankChow** [cgeo/cgeo#14740]
### Describe your problem!

When there's no network connection, the login failed reason will be "captcha required".

### How to reproduce?

1. cut off all the network connection of the phone, including cell and WiFi
2. open c:geo

### Actual result after these steps?

the page showing "Not logged in (Failed to log in to geocaching.com due to captcha required)" under the avatar

### Expected result after these steps?

It should be like "network connection error" or something similar, but never "captcha required". Because you'll never get the captcha in this condition.

### Reproducible

Yes

### c:geo Version

2023.09.26

**Comment by moving-bits** [comment]
The error message is actually correct, as c:geo indeed does get the message "Captcha required" from the server on retrieving the data from the geocaching server. But that is something that cannot be solved from within c:geo, as c:geo cannot solve it automatically (for obvious reasons), but it also wouldn't work, if c:geo would forward the captcha to you, so there's not much c:geo can do beside presenting the error message.

But there are a couple of things you can try, see [our manual](https://manual.cgeo.org/en/loginproblems#login_failedcaptcha_required)

**Comment by Lineflyer** [comment]
@moving-bits 
Did you read the issue completly?
I could not yet test it, but the issue author says, that "Captcha Required" is shown when c:geo is started without any network connection.

**Comment by moving-bits** [comment]
Um, ok, I guess I have read "_no_ network connection" as "_bad_ network connection". If there's no network connection at all, then there should be an appropriate message. Haven't seen this error myself so far, will try to reproduce it.

**Comment by moving-bits** [comment]
@HankChow 
Can you share your system information with us? Please go to home screen => about c:geo => swipe to system tab and use "send by mail", sending the content to our support e-mail.

c:geo remembers the last connection error and displays it, when it cannot login. My assumption is, that there has been a "captcha required" failure in the past, so this error message gets displayed when the new network error happens (as a network error seemingly does not reset the connector-specific error, which is technically ok). But although it's not a connector-specific error, c:geo should notify the user of the missing connection. We need to see how we can transport this error to home screen in this case.

**Comment by moving-bits** [comment]
To reproduce this error you have to
- try to connect to gc.com and receive an error like "captcha required"
- turn off internet connection before having a successful login on gc.com
- then restart c:geo

I've prepared a fix with #14769
