### ISSUE TITLE
Consistent elevation info map/home screen

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14757]
> Some additional info:
> - elevation info on home screen got introduced with #13470 in October 2022 and is based on GPS altitude info
> - elevation info on map got introduced with #14671 three weeks ago and is based on (lidar-based) elevation info in routing tiles

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/14745#issuecomment-1773397057_

I would like to question if its meaningful to have different sources for the (from users perspective) same information. 

I suggest to decide on a single source for both places.
IMHO it would be the GPS info, as not all users will use/have brouter tiles installed.

**Comment by ztNFny** [comment]
Is the map showing the elevation for the current position or map center? I thought it was the later - which would mean that we have to use brouter to get the info.

(My 2 cents: this info is completely useless and should not be shown anywhere)

**Comment by Lineflyer** [comment]
> Is the map showing the elevation for the current position or map center? I thought it was the later - which would mean that we have to use brouter to get the info.

if this is the case you are absolutely right and I would understand the different source..

**Comment by fm-sys** [comment]
I also vote for elevation info of map center instead of current location.

Reason: As a user I have no benefit from knowing "oh, I'm on 900m" but a great benefit from knowing "the next cache is on 1500m, so I'll have to take 600 hight meters to get there"

**Comment by moving-bits** [comment]
Ok, let's try to consolidate the different threads about elevation info in this issue for the time being. IMHO we should clarify WHAT we want to display first (depending on the choice, the source for this data as well as possible differences between map and home screen may be determined by this decision). Then we can decide WHERE on the map to display elevation info.

Currently implemented for the map is displaying elevation for the current position, using brouter data as a source. Use-case for this is having permanent elevation info, like many car navigation system have. This should be visible in an unobstrusive place, and without need of further interaction other than activating it in settings once (default = off).
Although I would personally prefer brouter based info for this, I understand the confusion that may arise from different values for the same, and agree that we should use the same source for the same data. I could live with using GPS data for this info. But I would strongly vote for keeping this info in upper-right corner as we have with other location-based info to not clutter the map further.

A different use case is the one mentioned by @fm-sys above: Elevation at a specific (center?) or user-selected "random" place on the map (eg: elevation of a certain cache). Such info could only be retrieved by using routing tile data. IMHO this is more of an "on demand" information, not a information that needs to be visible permanently. Therefore I suggest to add an entry to the long tap popup for this, automatically retrieving elevation info for the selected position/cache/waypoint on opening the popup.

Therefore my proposal would be:
|Type of info | data source | activation needed? | visibility |
|---|---|---|---|
|Elevation info for current position | GPS | needs to be activated in settings | permanently visible in upper right corner, if activated |
|Elevation info for user-selected position | brouter data | no activation needed | automatically added to long-tap popup on map / cache or waypoint |

**Comment by ztNFny** [comment]
> Currently implemented for the map is displaying elevation for the current position, using brouter data as a source. Use-case for this is having permanent elevation info, like many car navigation system have.

But why? We don't even display GPS position permanently, elevation being a part of those I don't see what value this brings.

If we ALSO had elevation at selected coords (either in the maps long-tap menu or at map center) then one could at least compare those to figure out not only the distance but also the elevation difference to a WP.

**Comment by ztNFny** [comment]
> > But why? 
> 
> to judge excactly distance AND elevation, like stated by your side already:

The current implementation shows ONLY current elevation though. And that's the case I'm asking about. It doesn't allow judging elevation difference.
