### ISSUE TITLE
Distance to cache info missing on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14763]
### Describe your problem!

Frequently reported for new release 2023.10.25:

Users claim, that after updating the distance to a cache is missing when opening the map for a cache, while it was there before the update.

One user adds, that after switching routing mode to "straight" and then back, the distance gets displayed then.

### How to reproduce?

TBD
Several support tickets to be analyzed

### Reproducible

Unclear

### c:geo Version

2023.10.25

### Additional Information

Tickets 118609 (Google Satellite), 720867 (OSM offline), 563794 (OSM offline)

**Comment by moving-bits** [comment]
should be resolved with release 2023.11.01, otherwise feel free to reopen
