### ISSUE TITLE
Elevation chart for route / individual route

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14768]
### Tell us your idea!

It would be nice to see the change of elevation along a route, be it a route to currently selected target or an individual route.

### What solution would you suggest?

Add an option to display such a chart, vertical axis would be elevation, horizontal axis distance, with left-most point start point of route, right-most point end point of route.

Example:
![image](https://www.topo-gps.com/android/en/manual/html/_images/route-profile3.png)
_(Source: https://www.topo-gps.com)_

Displaying this info should be on-demand, not permanent.
This could be either a split view as shown above or a separate view.
(If we go for a split view we could use a draggable marker on the elevation chart to highlight the corresponding point on the map.)

### Is there an alternative?

don't add such a function

### Additional Information

BRouter already gives us elevation info together with routing data, we just don't store it yet.

**Comment by fm-sys** [comment]
+1 but please don't integrate it in our old map. This could be shown when clicking on a track line in unified map.

**Comment by moving-bits** [comment]
I'm looking for a lightweight lib for drawing such point charts, but that seems to be not that easy... There are some powerful libs, but adding quite a bit weight to the app, and only few others. https://github.com/Madrapps/plot seems to be such a lightweight lib, mainly consisting of four small files. But it's using Kotlin & Composables (as most of the other libs do as well). While neither Kotlin nor Composables should be a problem in itself, I have not been able yet to get it to run in context of c:geo. I can add a Composable view to an XML layout, but I don't know how to use `setContent` for this view, meaning: how to address the Composable function for it. I've tried staying with a Kotlin file for the method defining the Composable content, but our build run seems to ignore it. Any ideas?

**Comment by devemux86** [comment]
- https://github.com/PhilJay/MPAndroidChart (used by OsmAnd?)
- https://github.com/jjoe64/GraphView

**Comment by moving-bits** [comment]
Thanks, additionally I had YCharts: https://github.com/codeandtheory/YCharts

Both GraphView and MPAndroidChart seem to be wide-spread, but both are no unmaintained for four or five of years already, sadly, having > 100 open pull requests. Additionally. https://github.com/jjoe64/GraphView/issues/691 made me sceptical - don't want to blow up our apk size by four meg just for a simple chart.

Plot had no updates for two years as well, but is small enough to fully-integrate it in our code, as it basically consists of just four small files. It seems lightweight, supporting only line charts, therefore I started with that, but I may eventually look into the others as well.

But I need to figure out first how to integrate a Kotlin Composable into a Java activity.

**Comment by fm-sys** [comment]
I used `MPAndroidChart` for a school project two years ago, and I can tell it's working fine. 36,9k stars on GitHub confirm this impression.

It's IMHO absolutely no problem that it's unmaintained. As long as everything works the way it should, there is simply no need to change anything. At least it doesn't look discontinued, just no new features were developed.

**Comment by devemux86** [comment]
Or maybe there could be forks that continue the development of some of these libraries?

**Comment by moving-bits** [comment]
I went with the MPAndroidChart lib for now and have a rough implementation ready for `UnifiedMap` now:

![image](https://github.com/cgeo/cgeo/assets/3754370/ca7859f9-9ddb-4d42-a052-1139e936cf9b)

Elevation chart can be toggled using the menu and show elevation of the current individual route.
In landscape mode, elevation chart is shown right of the map.

Some things are yet to be done:
- No interaction yet between chart and map
- Device orientation change closes elevation chart
- Distinction line between chart and bottom navigation in light mode
- (and probably more)

**Comment by bekuno** [comment]
There is an active maintained fork at https://github.com/AppDevNext/AndroidChart.

**Comment by fm-sys** [comment]
I still vote for using the original MPAndroidChart lib as long as no problems arise. There is no point in using a lib which might break our integration with every new version. (Even today, we can't keep up with dependency updates)

**Comment by bekuno** [comment]
> I still vote for using the original MPAndroidChart lib as long as no problems arise. There is no point in using a lib which might break our integration with every new version. (Even today, we can't keep up with dependency updates)

You can skip every update in a maintained lib. 
But a bug will never fixed in a unmainted lib. And it is possible that such an old lib will become incompatible to a newer android version (what we already had).

**Comment by eddiemuc** [comment]
I agree 

> > I still vote for using the original MPAndroidChart lib as long as no problems arise. There is no point in using a lib which might break our integration with every new version. (Even today, we can't keep up with dependency updates)
> 
> You can skip every update in a maintained lib. But a bug will never fixed in a unmainted lib. And it is possible that such an old lib will become incompatible to a newer android version (what we already had).

I agree with @bekuno, it is always better to set upon a maintained version of a lib. At first glance https://github.com/AppDevNext/AndroidChart seems to be worth a try.

**Comment by moving-bits** [comment]
PR #14779 implements this for individual route, and #14794 for tracks/routes, so let's close here for now.
Be aware: This is currently for UnifiedMap only!
