### ISSUE TITLE
Distance info on map cant be zoomed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14764]
### Describe your problem!

Reported by several users on social media and at least one on support ticket:

I was previously able to tap the distance on map to have it zoomed.
This does no longer work.

### How to reproduce?

TBD from support tickets

### Reproducible

Unclear

### c:geo Version

2023.10.25

### Additional Information

Tickets 940080, 975516

**Comment by eddiemuc** [comment]
Confirmed by another user

**Comment by moving-bits** [comment]
should be resolved with release 2023.11.01, otherwise feel free to reopen
