### ISSUE TITLE
Using Android Java 8+ API desugaring support for c:geo

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#14784]
### Describe your problem!

By chance I found out today that my Android Studio does not warn me any more when I accidentally use Java SDK features not supported in SDK21. Most popular examples for this would be:
* `@FunctionalInterface` and its generic implementations in `java.util.function` (we have our own implementations under `cgeo.geocaching.utils.functions` as a workaround)
* Streaming API like e.g. `Arrays.asList("one", null, "three").stream().filter(s -> s != null).count()` (we have `cgeo.geocaching.utils.CollectionStream` as a workaround at least for collections)

I checked, and as expected although AS does not warn me those features are of course still not supported in SDK21 (code will fail to run on a device on SDK21).

Question is why my AS does not warn me about that any more. This could get ugly since most (Java) developers are very used to these common features like functional interfaces or streaming these days of course.

@cgeo/team: Do others in the team have the same experience? I might have accidentally changes some important setting here.  

I currently use Android Studio Giraffe | 2022.3.1 Patch 1

### How to reproduce?

Paste some code using features not supported in SDK21 into c:geo and run on a SDK21 device.

Silly code example:

```
            //execute a stream
            final List<String> list = Arrays.asList("a", "b", null);
            final long cnt2 = list.stream().filter(Objects::nonNull).count();
            //execute a functional interface
            final java.util.function.Function<String, String> f = s -> s.toUpperCase();
            final String s = f.apply("abc");
```

### Actual result after these steps?

IDE does not warn me, but code fails to execute on SDK21 device. 

Example exception for the streaming case:
`java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)`
                                                                   
Example exception for the functionalinterface case:
`java.lang.NoClassDefFoundError: cgeo.geocaching.MainActivity$$ExternalSyntheticLambda9`

### Expected result after these steps?

IDE should warn me when using functions not supported in SDK 21

### Reproducible

Yes

### c:geo Version

n/a

### System information

```text
n/a
```

**Comment by bekuno** [comment]
I have no idea to the missed warning.

At least I found this document: https://developer.android.com/studio/write/java8-support#library-desugaring.

We could try
~~~
android {
    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
    }
}
dependencies {
    // For AGP 7.4+
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'
}
~~~

**Comment by eddiemuc** [comment]
This is absolutely freakin aewsome! Finally a way to use basic JDK8/11 stuff in c:geo!

I tried it in an SDK21 emulator, seems to work.

Can we pretty pretty please use this desugaring in c:geo? 🙏🙏🙏

**Comment by fm-sys** [comment]
May I ask someone to review PR #14181 ;-)

**Comment by ztNFny** [comment]
Did you check the effect on apk size? in one project of mine it increased substantially

**Comment by eddiemuc** [comment]
> May I ask someone to review PR #14181 ;-)

Must have slipped through my messages back then. sorry for that

**Comment by eddiemuc** [comment]
> Did you check the effect on apk size? in one project of mine it increased substantially

IMHO: worth it

**Comment by eddiemuc** [comment]
Alternatively we could still switch to Kotlin of course

**Comment by eddiemuc** [comment]
Closing in favor of PR #14181
