### ISSUE TITLE
Detection of premium status unreliable?

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14789]
We got three users on support claiming missing premium status and/or premium-related functions although they have a PM.

Tickets 209979, 130825, 203204

All three users are from Germany/Austria, so it may be a temporary regional problem related to some server changes, but I cannot reproduce it yet.

**Comment by fm-sys** [comment]
I had the same temporary problem yesterday, however, closing and reopening cgeo fixed it for me.

**Comment by ztNFny** [comment]
It's been an issue since "forever" that when login is slow buttons like PQs don't show up initially

**Comment by moving-bits** [comment]
Looks like it has been a temporary issue, not some code change on server side, so let's close this issue for now.
