### ISSUE TITLE
Show controls when tapping on track/route

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14792]
### Tell us your idea!

As proposed in https://github.com/cgeo/cgeo/pull/14779#issuecomment-1793390116: Show some controls when tapping on a track / route on the map. Those controls should offer some or all of the controls given for this item in route/track popup dialog.

### What solution would you suggest?

- long tap on a route / track should open a popup menu
- options for individual route could be: edit, reverse, reload, show/hide, focus, delete, route optimization
- options for route/track could be: edit (name), set color, show/hide, focus, delete

possible addition:
- long tap menu on free map space could offer to load an individual route or a track/route file

### Is there an alternative?

- use short tap instead of long tap (but that would collide currently with enabling/disabling elevation chart)
- use a icon-based bar instead of a popup menu

**Comment by fm-sys** [comment]
I would (also?) place them inside the elevation chart. Maybe as 3-dot-menu in the toolbar, so that the elevation chart doesn't get cluttered too much.
