### ISSUE TITLE
routing data check shown although using external BRouter

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14800]
The routing data check should IMHO only be shown if internal BRouter is enabled. If external BRouter is used, either hide this option or launch external BRouter download manager when clicking on it.

![Screenshot 2023-11-05 094405](https://github.com/cgeo/cgeo/assets/64581222/bfe2af00-3dc5-4d43-b224-2c8667fba8f1)

**Comment by moving-bits** [comment]
IMHO this can still be useful, if paths are configured correctly (pointing to the folder BRouter stores its routing tile data files in).

But maybe launching BRouter download manager would be the better option for most users (but then the menu entry should be renamed accordingly).

**Comment by moving-bits** [comment]
Fixed with #14893
