### ISSUE TITLE
map downloader - mark already existing maps

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#14819]
### Tell us your idea!

The offline map downloader shows all maps available on the server.
It would be nice if you could see here whether a map is already installed locally.
Optionally, the status (current or outdated) could also be displayed here.

### What solution would you suggest?

Mark the already installed maps with a symbol and/or color.
Eg., use the map symbol in green and yellow. Or add a separate symbol for it.

**Comment by fm-sys** [comment]
I second this idea. 

I'd suggest to combine map icon with colored badge icon.

![Screenshot_20231107_112235](https://github.com/cgeo/cgeo/assets/64581222/04ab413d-9990-499b-867f-2711f242abd0)
