### ISSUE TITLE
GC.Com nearest.aspx side announced for retirement: "Found By" Search redesign needed for gc.com

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#14827]
### Describe your problem!

Update 14.11.23: apparently the nearest.aspx side was dropped by accident by gc.com, this will be reverted. However, retirement is announced for a later release, so c:geo needs to prepare for this

"Found By" search does not  work any more for gc.com when nearest.aspx is retired. In this case,  only results on other platforms (e.g. oc.de) will be found. 

Under the hood, c:geo uses the following Web page/URL to implement "found by" search: https://www.geocaching.com/seek/nearest.aspx?ul=Moun10Bike

If this URL is down (e.g. HTTP500) then feature doesn't work.
![image](https://github.com/cgeo/cgeo/assets/6909759/220df835-92ac-4dea-8e80-17d2d8f519a4)

Side note: this also leads to failure of some of our tests on CI:
![image](https://github.com/cgeo/cgeo/assets/6909759/459a9a28-5f1d-4c0f-a6ba-c38847f2d422)

Side note to side note: the failing test seem to indicate that "search by owner" and "search by coordinate" is also not working, This is however not true since the methods tested in these tests is no longer in use for productive "search by owner/coordinate". Those two tests should probably get deactivated

### How to reproduce?

Onyl reproducible if nearest.aspx is down

* Log into c:geo
* Start a "Found by" search for a gc.com user where you know he/she has finds

### Actual result after these steps?

No caches are found for that user on gc.com

### Expected result after these steps?

Caches should be found for this user on gc.com

### Reproducible

Yes

### c:geo Version

first discovered in 2023.11.01, but not relevant

### System information

```text
n/a
```

**Comment by eddiemuc** [comment]
Updated example URl in error description

**Comment by SammysHP** [comment]
This change was announced by Groundspeak recently via mail. It makes me vary sad because the old search worked much better than the new one. :cry:

**Comment by ztNFny** [comment]
https://www.geocaching.com/play/map?sa=1&hb=Moun10Bike&asc=false&sort=placedate

Should work with the same parser used for PQ live preview. I'm currently away from a PC though and can't implement it.

**Comment by SammysHP** [comment]
This change was rolled out by accident and will be reverted by Groundspeak.

**Comment by eddiemuc** [comment]
> This change was rolled out by accident and will be reverted by Groundspeak.

Will it just be reverted for a limited amount of time or will the page stay live for good after reverting? (I am asking because a few days ago you said this was an announced change)

**Comment by SammysHP** [comment]
It was announced for a later release, so eventually they will remove the old search again.

**Comment by eddiemuc** [comment]
Thanks. I will leave the issue open due to necessity of conversion for that later release

**Comment by eddiemuc** [comment]
> It was announced for a later release, so eventually they will remove the old search again.

Out of interest: where can I find these announcements from groundspeak?

**Comment by moving-bits** [comment]
> > It was announced for a later release, so eventually they will remove the old search again.
> 
> Out of interest: where can I find these announcements from groundspeak?

Probably in their forum: https://forums.geocaching.com/GC/index.php?/forum/4-geocaching-hq-communications/

**Comment by SammysHP** [comment]
It was mentioned here: https://github.com/orgs/cgeo/discussions/82

**Comment by eddiemuc** [comment]
PR #14900 will remove all usages of nearest.aspx page from c:geo

**Comment by eddiemuc** [comment]
This will have some side-effects:
* "FoundBy" search will only be available to premium users. I don't know how it was before
* "FoundBy" as well as "not found by" search will now support multiple users on gc.com side. In c:geo this can be used by adding multiple LogEntry filters to the used filter

**Comment by SammysHP** [comment]
> "FoundBy" search will only be available to premium users. I don't know how it was before

It was available to basic members previously and I think it still is on the website (not being able to view finds by another user would be a huge disadvantage for basic member).

**Comment by eddiemuc** [comment]
> > "FoundBy" search will only be available to premium users. I don't know how it was before
> 
> It was available to basic members previously and I think it still is on the website (not being able to view finds by another user would be a huge disadvantage for basic member).

With nearest.aspx gone in the near future I don't know of any way to still support this. But feel free to dig into the gc.co. website and its APIs.

**Comment by eddiemuc** [comment]
Update: I tried new interface with a basic member. To my surprise foundby search seems to work (although it is not supported via the website's GUI), at least for now.

**Comment by SammysHP** [comment]
What happens when you visit the profile of a user as a basic member and try to view their finds?

**Comment by ztNFny** [comment]
> What happens when you visit the profile of a user as a basic member and try to view their finds?

That functionality depends on whether the user has the option "allow users to view my finds" enabled - whereas using the search allows it for any user ;-)
