### ISSUE TITLE
Personal Note, downloaded from gc.com is missing CR/LF

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14825]
### Describe your problem!

When downloading a PN from gc.com, it does not contain any CR/LF anymore, but shows ``&#10;`` instead.
Moreover e. g. ``>`` will appear as ``&gt;`` in c:geo's PN ...

First thought they switched the PN to Unicode ... but umlauts still come normal.  Or is there some XML in between? Nevertheless, I would guess this happens because of a website change anyway, cause we've cross checked it with two different Nightlies (2023.10.14-NB-04446c4 and 2023.11.10-NB-0e450a) and both show this strange behavior - and I'd be really surprised if I missed this misbehavior for more than a month.  ;)

### How to reproduce?

Just download resp. refresh any cache who has a serverside PN containing CR/LFs.

### Actual result after these steps?

PN text looks scrambled.

### Expected result after these steps?

Text should be displayed "human readable".  ;)

### Reproducible

Yes

### c:geo Version

2023.11.10-NB-0e450a

**Comment by MagpieFourtyTwo** [comment]
Just checked some lately updated caches:
- everything was still fine on Nov., 9th, about 6 p. m.
- but last night, i. e. Nov. 11th, at about 1 a. m., things already went wrong.

**Comment by eddiemuc** [comment]
Confirmed also in 2023.11.01. PR #14826 provides a quickfix by parsing received personal note as quasi-HTML (replacing special HTMl chars with special special handling for line-break $#10;)

**Comment by MagpieFourtyTwo** [comment]
Could you please add at least ``>`` plus the single and double quotes to the quickfix? These are nearly as annoying as the line breaks (esp as they are used in "Save WPs to PN" a lot). ;)

Moreover just checked against a quick keyboard walk and found these to be "scrambled":

```
Euro Sign € &#8364
Ampersand & &amp
Double quote " &quot
Single quote ' &#39
Dot • &#8226
Sqrt √ &#8730
Pi π &#960
Triangle ∆ &#8710
TM ™ &#8482
Check ✓ &#10003
gt > &gt
lt < &lt
```

(trailing semicolons removed to prevent evaluation)

**Comment by eddiemuc** [comment]
The fix will handle all html-decoded characters.

**Comment by eddiemuc** [comment]
Here is the Personal Note I used for testing:
![image](https://github.com/cgeo/cgeo/assets/6909759/bf698555-01df-4e9c-8058-e45cc566e406)

**Comment by Lineflyer** [comment]
I can confirm this behavior. The question is, whether this is an intentional website change or a bug on server side.
Therefore a fix should potentially cover old and new behavior.

**Comment by eddiemuc** [comment]
> I can confirm this behavior. The question is, whether this is an intentional website change or a bug on server side. Therefore a fix should potentially cover old and new behavior.

I can't test fix against old behaviour because I don't know how it was and current server uses "new" behaviour :-)
However, to the best of my thoughts the fix shouldn't impact the "old" behaviour as well since it should only react to HTML-like constructs in the personal note (like the `$#x;`-encoded characters)

**Comment by eddiemuc** [comment]
Judging from personal feedback yesterday (during a mega) this seems to be a relevant bug for many c:geo users. Don't know about support ticket situation though.

**Comment by Lineflyer** [comment]
Some support tickets and some reports on social media.
As this problem also deems automatic formula and waypoint saving unusable, I guess we should release the fix rather soon.

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo Nightly version 2023.11.12-NB1-7b09703 should be available. Test feedback appreciated.

**Comment by Lineflyer** [comment]
Quick note:
Seems to work for most notes, but I have one rather complex note with several equations, HTML links, etc. This is still doubled on cache refresh, but I cant see a visual difference. Might check later.

**Comment by MagpieFourtyTwo** [comment]
> @MagpieFourtyTwo Nightly version 2023.11.12-NB1-7b09703 should be available. Test feedback appreciated.

WMF - Thx!

**Comment by MagpieFourtyTwo** [comment]
> Quick note:
> Seems to work for most notes, but I have one rather complex note with several equations, HTML links, etc. This is still doubled on cache refresh, but I cant see a visual difference. Might check later.

Guess a whitespace diff?

**Comment by bekuno** [comment]
Just for fun.
Groundspeak does nor handle this by themself correct.
I had to use their mail system (for a EC answer).
The mail sent page shows (this is not the full answer :))
![20231112_200508.jpg](https://github.com/cgeo/cgeo/assets/32555742/fbbfc66f-9cb6-44d9-aae7-ea556ae70537)

**Comment by MagpieFourtyTwo** [comment]
Yep, saw this a bunch of times, too. But, hey, it's gc.com - what did you expect?  ;)
Nevertheless, the mail goes out correctly formatted.

@Lineflyer 
Did you use tabs in your "complex" note?
These get lost somehow, when downloading a PN from gc.com which contains tabs. They are not even replaced by s/th, but just vanish.
I think, the issue should either be re-opened or a follow up should be filed, cause the story is not over, yet, I'm afraid.

**Comment by MagpieFourtyTwo** [comment]
BTW: Forgot to thank @eddiemuc for the quick fix - working fine again (at least in most common cases ;) ).

**Comment by eddiemuc** [comment]
I found a much easier solution (which also handles tabs) and created PR #14830 for it

**Comment by MagpieFourtyTwo** [comment]
Great - will check it as soon as it arrives in the nightly.

**Comment by fm-sys** [comment]
New nightly is building right now...

https://ci.cgeo.org/job/cgeo%20nightly/3235/

**Comment by fm-sys** [comment]
A nightly (2023.11.13-NB1) containing the new fix is now available for testing.

**Comment by MagpieFourtyTwo** [comment]
Thx!  Tabs seem to be fine now.  Checked various combinations without an issue.
Same applies for the chars I mentioned in [Comment 1806760244](https://github.com/cgeo/cgeo/issues/14825#issuecomment-1806760244).
Moreover comparison between local and server side version seems to be ok, too - at least for my test cases.

@Lineflyer 
Could you please re-test your more complex formula stuff?

**Comment by Lineflyer** [comment]
Tested my complex note (which was previously duplicated on refresh) using 2023.11.13-NB1: Works perfect now! Thumbs up!
