### ISSUE TITLE
SimpleDialog - action button not shown

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14856]
![grafik](https://github.com/cgeo/cgeo/assets/64581222/090ff32f-b637-4e0b-b945-5d4ee015692c)

There should be a delete button at the end of the dialog. However there is none although it should...

![grafik](https://github.com/cgeo/cgeo/assets/64581222/18dc0575-8478-4a1d-ac64-d93e178d19c7)

As the code looks correct, I guess it's a bug inside `SimpleDialog`.

**Comment by eddiemuc** [comment]
Correct, Most likely a bug in new simple dialog. I will look into it.

**Comment by eddiemuc** [comment]
Fixed with PR #14861
