### ISSUE TITLE
[BottomSheet CachePopup] viewing multiple caches in popup adds them to the back stack

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14868]
With the new BottomSheet CachePopup when you view multiple caches as popup, then swipe up to view the details, all those viewed caches are in the back stack and you need to go back maaany times to get back to map.

To reproduce:
1. On (old offline) map view cache 1 in CachePopup
2. On (old offline) map view cache 2 in CachePopup
3. Swipe up to get to CacheDetails
4. Back
5. 
Expected: Map Activity visible
Actual: Cache 1 opened in CacheDetails

**Comment by moving-bits** [comment]
PR #14873 attempts to fix this

**Comment by ztNFny** [comment]
I still "sometimes" have this problem. Haven't been able to identify the pattern, sometimes going back works fine, other times i have to back repeatedly.

**Comment by fm-sys** [comment]
Please retest with version 2023.11.30-NB. If it should still happen, please let me know. Haven't seen the bug anymore in the last days.
