### ISSUE TITLE
Waypoint popup: Cannot swipe up if description is too long

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14874]
New waypoint details view in maps:

If the waypoint description for a waypoint is so long that the bottom sheet is already fully expanded, you cannot swipe up to open the cache details view. Not sure if there is a mitigation for this.

**Comment by fm-sys** [comment]
No idea how to fix this easily. But at least as long as we keep the additional "open" button in, it shouldn't be a problem.

**Comment by ztNFny** [comment]
Maybe we could limit the height of the bottom sheet to max x% (60-70 maybe?)? A fullscreen BottomSheet would probably be confusing to users as well, thinking they are in CacheDetails instead.

**Comment by moving-bits** [comment]
No idea about the technical details, but cache details page supports a swipe-down even if the page is completely filled, so I guess there must be a way to do a swipe-up even on full waypoint details pages, at least if you have scrolled down to the bottom of the sheet.

> Maybe we could limit the height of the bottom sheet to max x% (60-70 maybe?)? 

This would not help with swiping up, since you still have to distinguish between "I want to see more of the text, expand the window" and "I want to swipe up". (Except if you want to keep the bottom sheet size at a maximum of x%, which would limit visibility of waypoint description.)

But with regard to this:

> A fullscreen BottomSheet would probably be confusing to users as well, thinking they are in CacheDetails instead.

such a limit on initially opening the bottom sheet would still be useful.

**Comment by fm-sys** [comment]
A fix for both problems (which would technically even be really easy to implement) would be to limit the description textview to a specific number of `maxLines`

**Comment by moving-bits** [comment]
> A fix for both problems (which would technically even be really easy to implement) would be to limit the description textview to a specific number of `maxLines`

but how to determine a reasonable number for `maxLines` across different screen sizes & font sizes?

**Comment by fm-sys** [comment]
Probably it should be possible to calculate this via screen height and font size (sp-to-px convertion)

Or we just choose something which fits on most normal devices.

**Comment by moving-bits** [comment]
Seems to have become better since introducing the "swipe handle", and it's a minor thing anyway, with having the "details" button, so let's close here.
