### ISSUE TITLE
SimpleDialog: broken cache icon

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14871]
In new simple dialog cache icons are displayed wrong. Markers are drawn on top of the main icon instead of in its corners

![Screenshot_2023-11-22-23-44-17-14_a916ceb0c8a82619faeb76fe6b8ae997.jpg](https://github.com/cgeo/cgeo/assets/1258173/15db27e7-e9ad-4a17-9366-2949ca7e685c)

**Comment by eddiemuc** [comment]
I will look into it

**Comment by eddiemuc** [comment]
Fixed with PR #14876. CacheMarker image needs to be drawn with intrinsic bounds
