### ISSUE TITLE
Missing alignment of items in SimplePopupMenu

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14894]
Items in map's long tap menu aren't aligned in a straight line anymore:

![image](https://github.com/cgeo/cgeo/assets/3754370/09bf26a7-b267-4ce5-942f-eb8f36daddf4)

Additionally the first icon should be scaled accordingly.

**Comment by fm-sys** [comment]
@eddiemuc could you take a look? Is it a general bug inside SimpleDialog?

**Comment by eddiemuc** [comment]
Does this happen only in unifiedmap or also in "old" map?

**Comment by fm-sys** [comment]
Old map (mapsforge) has the same problem. Same applies also when longclicking the search icon in the bottom nav.

**Comment by murggel** [comment]
Probably related - indentation in filter-list
![Screenshot_20231202-092508_cgeo.jpg](https://github.com/cgeo/cgeo/assets/70113341/fba6c4fa-773c-438c-90b5-287f0a5f7343)

**Comment by eddiemuc** [comment]
PR #14939 recreates the cache list item layout. The old one was a bit messy and relied on fixed icon sizes for cache markers.

The "intention" thingy in variable function list was unrelated, I increased the intent anyway
