### ISSUE TITLE
Sorting of "found by user" search results

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14912]
> As the new search returns max 1000 results afaik what sorting does this use? Is it center-based or most recent or does it follow c:geos list sorting? "Found by" is a special case where center-based might not be the prefered option but most recent.

Interesting, haven't thought about that.

I made some quick tests. It seems when searching on gc.com with one "foundBy", then the "lastFoundDate" of the response is filled with the found date of the "foundBy" user (not the actual last found date of the cache), and the result can be sorted by this using parameter sort=lastFound

Would make a lot of sense to include that in c:geo. However, may I kindly ask to move this into its own isse due to its complexity?

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/14900#issuecomment-1829549895_

**Comment by ztNFny** [comment]
New search returns max 1000 search results, so for most users it will not return the full list of finds when doing a "found by user" search. I see 2 (sensible) options:
- Sort by location, returning the closest 1000 caches to my current location
- Sort by foundDate, returning the most recent 1000 finds

Imho there are more usecases for the recent finds, but both are valid scenarios.

@eddiemuc do you know what is currently being returned?

**Comment by eddiemuc** [comment]
> New search returns max 1000 search results, so for most users it will not return the full list of finds when doing a "found by user" search. I see 2 (sensible) options:
> - Sort by location, returning the closest 1000 caches to my current location
> - Sort by foundDate, returning the most recent 1000 finds

Current situation for Gc.com
* The connector requests a maximum number of 200 items. This is limited by us in the code, I believe the service can return more. I remember this was discussed back when new filter was implemented, the limit was introduced so users are not confused by too many results (if you have multiple active connectors then results of connectors add up of course). Paging/load-more-reaults is possible already today
* Sorting by many fields is supported by the Gc.com service. However we always request sorting by distance. The connectors "searchByFilter" method does not even allow to pass a sorting argument.

This can and should be enhanced IMHO but requires some work. If no one else steps up I will put it on my to-do list (and prioritize it over the "edit log" functionality)

Questions to discuss:
- should we increase the 200 to another value?
- what should be the sort to use per live search type? We have live searches by owner, coordinate/address, keyword and finder
- if the user changes the sort in the live result list I believe this should trigger a re-querying (like it is already implemented when user changes the filter). Agreed?
- if the user changes the sort for the live filter result, should this new sort be stored and then used automatically on next live search of same live search type? (Might be put to a new issue)
