### ISSUE TITLE
[Unified map] transient vs offline vs live filter context

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14921]
Unified map should take different filter contexts into account

**Comment by moving-bits** [comment]
See PR #14941 for a (partial?) fix

**Comment by moving-bits** [comment]
@fm-sys 
Anything still open, or did PR #14941 catch all relevant places?

**Comment by fm-sys** [comment]
As far as I can tell everything works as intended, we can open a new issue if some bug should arise.
