### ISSUE TITLE
Animation flaw on cache bottom sheet

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14932]
### Describe your problem!

When returning from cache details view sometimes opening a new bottom sheet on map looks "unwanted".

### How to reproduce?

- Open live map
- Tap on a cache to open bottom sheet
- Swipe up to view cache details
- Use back to return to map
- Tap the same cache again

### Actual result after these steps?

It looks like there is a bottom sheet close animation first (sometimes I even see the "Swipe up to view details" screen for a plit second) before the new bottom sheet opens

### Expected result after these steps?

There should be no leftover of the previous bottom sheet 

### Reproducible

Yes

### c:geo Version

2023.11.29-NB

**Comment by fm-sys** [comment]
PR #14910 includes several fixes related to the bottom sheet, however it is only contained in the nightly starting with 2023.11.30-NB. May I kindly ask you to update and retest if the bug still exists?

**Comment by MagpieFourtyTwo** [comment]
> several fixes (...) starting with 2023.11.30-NB

This may be the reason why I was not able to reproduce it (anymore), cause I was already using exactly this version.  :)

**Comment by fm-sys** [comment]
@Lineflyer I will close for now, please reopen if you still experience this issue

**Comment by Lineflyer** [comment]
Confirmed fixed with 2023.12.03-NB...at least the above mentioned for me 99% reproducible case is no longer happening.
