### ISSUE TITLE
[Nightly] 'Rename list' provides an empty input field

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14933]
### Describe your problem!

In latest nightly, the input field of ``Rename current list`` does no longer default to the current list name, but it's completely empty.
This *may* be a result of my list names, containing emoticons (although that has worked quite well so far), thus a cross check by someone who uses "normal" characters only wouldn't be bad.  ;)

### How to reproduce?

- open any list
- ``Menu`` => ``Manage lists`` => ``Rename current list``

### Actual result after these steps?

List name input field is empty

### Expected result after these steps?

List name input field should contain current list name, so it can be altered (like it was up to now)

### Reproducible

Yes

### c:geo Version

2023.11.30-NB-611a561

**Comment by MagpieFourtyTwo** [comment]
Any other (input) dialogs that may also be affected (i. e. should be checked)?

**Comment by eddiemuc** [comment]
> Any other (input) dialogs that may also be affected (i. e. should be checked)?

Depends on where I introduced the bug :-) If it is in the new core SimpleDialog class then probably all dialogs with prefilling of values are affected. If I just forgot to include the value in this single instance then only that one should be affected.

I am positive that I can take a look at this on the weekend or even this evening. Should be an easy fix.

**Comment by MagpieFourtyTwo** [comment]
Same applies to slider values in e. g. setting history track length.

**Comment by murggel** [comment]
Same for renaming an image..

**Comment by eddiemuc** [comment]
Bug is in SimpleDialog, so all input dialogs are affected. Fix will follow.

**Comment by MagpieFourtyTwo** [comment]
Fine!  Thx!
