### ISSUE TITLE
[Simple Dialog] "cancel" option doesn't always make sense

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14954]
When importing a GPX, the result dialog shows ok and cancel. However, both buttons do nothing. I think one button too much slipped in... ;-)

![Screenshot_20231203_160658_cgeo geocaching developer](https://github.com/cgeo/cgeo/assets/64581222/4ead5f22-f8d3-4580-8710-64f65513b1eb)

**Comment by moving-bits** [comment]
this is no longer the case, only "OK" button gets displayed after importing a GPX file into a list, thus closing here
