### ISSUE TITLE
Reduce map scale slider range

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14965]
Currently it's possible to scale the map from 10% to 500%.

I've played a bit with these values and think that 50% to 250% would be more than enough. Reducing this range would have the advantage that it gets easier to select a specific value.

Edit: just checked, and cache markers can be scaled from 50% to 200%. Maybe we should align these ranges, and 50-200% should also be enough for map scaling.

**Comment by moving-bits** [comment]
I have no strong opinion about the slider's range, but what you can always do for easier input is tap on the number to the right of the slider. An input dialog will then open, where you can enter the desired scale value.

**Comment by fm-sys** [comment]
Well, that's true. But it still seems kinda strange to have a slider and recommend it users "please don't use it, we have a well hidden dialog where you can enter your desired value" ;)
