### ISSUE TITLE
UnifiedMap: Circles missing

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14969]
No circles are drawn for caches/stages even if "Show circles" option is activated

**Comment by fm-sys** [comment]
For WPs this is indeed missing, but for caches it is implemented:

![grafik](https://github.com/cgeo/cgeo/assets/64581222/a7b25f0b-d962-4793-a7e7-ec1729640f3f)

**Comment by fm-sys** [comment]
Never mind, even for WPs it is working. 

@moving-bits I would be really interested in the use case when it was not working for you.
