### ISSUE TITLE
Bottom sheet slide up not working in landscape mode

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14982]
### Describe your problem!

When using current nightly on my tablet the bottom sheet shows up at the right corner in full height.
It also shows "Swip up to open cache details" but this does not work.

### How to reproduce?

See above.
Can provide screenshot if needed tomorrow.

### Reproducible

Yes

### c:geo Version

2023.12.08-NB

**Comment by fm-sys** [comment]
As of now it's intended that the side-sheet cannot be swiped up, but then the text shouldn't be there of course.
