### ISSUE TITLE
Bottom sheet dismissed on rotation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15025]
### Describe your problem!

After tapping a cache and looking at the bottom sheet information I sometimes rotate the device to get a better view on map or the content of the bottom sheet.
However once I rotate the device the bottom sheet is dismissed, it should be kept.

### How to reproduce?

- Open map
- Tap on cache/waypoint
- Have bottom sheet shown
- Rotate device to/from landscape/portrait

### Actual result after these steps?

Bottom sheet removed, normal map is shown

### Expected result after these steps?

The bottom sheet should survive rotation (respectively be recreated after rotation)

### Reproducible

Yes

### c:geo Version

2023.12.14-NB

**Comment by moving-bits** [comment]
Recreation will be required in this case, as portrait mode uses a BottomSheet, whereas landscape mode uses a SideSheet.
We need to remember that a sheet is currently opened (and for what item). This info needs to survive configuration change and lead to reopening the required sheet.

**Comment by fm-sys** [comment]
All other dialogs get closed while rotating cgeo as well. Really worth the effort...?

**Comment by moving-bits** [comment]
Can confirm that implementation gets a bit nasty, and I'm still in UnifiedMap, haven't even touched the other map types. I'll postpone this for now, until we have decided whether to continue here.
