### ISSUE TITLE
Map from list opens at coords 0,0

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15021]
### Describe your problem!

When trying to map a list a seemingly empty offline map opens.
Zooming out or changing to an online map source you will note, that the map is centered on somewhere west of Africa, presumably at N0, E0.

### How to reproduce?

- Open a list with some caches at a certain area (e.g. within in Germany)
- Tap on map icon in action bar

### Actual result after these steps?

Map opens at N0, E0

### Expected result after these steps?

Map should opened zoomed to fit the area of the caches on the respective list

### Reproducible

Yes

### c:geo Version

2023.12.14-NB

**Comment by moving-bits** [comment]
No longer reproducible for me since @eddiemuc added a mitigation for the scaling bug on displaying a list when map was not ready (see PR #15026).

**Comment by Lineflyer** [comment]
Yes, seems fixed with todays nightly.
