### ISSUE TITLE
[Unified Map][VTM] "Edges" of routes/polylines produce darker regions, also when zoomed out

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15029]
(Originally discussed in #15003)

Corresponding issue in VTM: https://github.com/mapsforge/vtm/issues/1082 (with example code in PR https://github.com/mapsforge/vtm/pull/1081)

It seems that drawing polylines (e.g. Routes) with VTM with a certain thickness and a  semi-transparent color leads to "darker edges" when those line segments are overlapping on polyline points. This effect is also visible when zooming out.

To visualize the issue I deliberately selected a very broad route width and compared Unified GMap with Unified VTM:

GMap:
![image](https://github.com/cgeo/cgeo/assets/6909759/7271a3c9-7469-461f-92bf-ec445131470d)

VTM:
![image](https://github.com/cgeo/cgeo/assets/6909759/81c3cee8-fc0c-40f1-8824-69b732f68ce0)

**Comment by eddiemuc** [comment]
A mean example for my reference. Polyline of:
[N 53° 32.004' · E 010° 04.190', N 53° 32.514' · E 010° 05.445', N 53° 32.247' · E 010° 05.461', N 53° 32.463' · E 010° 05.568', N 53° 32.203' · E 010° 05.650', N 53° 32.436' · E 010° 05.019']

![image](https://github.com/cgeo/cgeo/assets/6909759/f5537f41-cd8a-468e-b9b6-37940243047c)

![image](https://github.com/cgeo/cgeo/assets/6909759/f2379963-a9bc-4333-a905-b159fe4bfe5b)

**Comment by eddiemuc** [comment]
@devemux86 I modified the vtm-android-example to include an example of this. You will find the PR here: https://github.com/mapsforge/vtm/pull/1081 

It also contains some explanations and screenshots.

This might be a very dumb config error on our side, but I don't know how to proceed here. I would be glad for some pointers...

**Comment by eddiemuc** [comment]
@eddiemuc please see my answer in the PR.

_Originally posted by @devemux86 in https://github.com/cgeo/cgeo/issues/15003#issuecomment-1857774454_

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo / team: it looks like this is a bigger issue and not resolved easily. Is this a showstopper for UnifiedMap/VTM for now?

**Comment by eddiemuc** [comment]
Corresponding issue in VTM: https://github.com/mapsforge/vtm/issues/1082 (with example code in PR https://github.com/mapsforge/vtm/pull/1081)

**Comment by MagpieFourtyTwo** [comment]
> it looks like this is a bigger issue and not resolved easily. Is this a showstopper for UnifiedMap/VTM for now?

We rely on c:geo's navigation when we're on tour - but as in some situations (with a lot of quick direction changes) it may get pretty hard to read the roads underneath the "multi layer routing line", we would most probably not use unified map at all. But that's just us ...

Nevertheless, way more important (for us) are performance and list displaying on map, I would say.

**Comment by moving-bits** [comment]
Reopened due to #15100 / #15310

**Comment by moving-bits** [comment]
Fixed with #15316
