### ISSUE TITLE
Waypoints on other lists leak onto map of list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15032]
Written while on the go on vacation:

- Stored caches of a certain owner into a new list
- Noticed, that some are archived and removed them from the list
- When mapping the list I do still see the waypoints of that archived cache on the map (grey and with red cross) although they are no longer stored on the list or anywhere (just in cache cache I assume)

2023.12.16-NB

After "removing orphaned data" the problem is gone

**Comment by Lineflyer** [comment]
More precise after some more caching:
All waypoints  of caches on other lists (or in cache cache) leak onto a mapped list.

**Comment by moving-bits** [comment]
`loadWaypoints` for UnifiedMap is currently designed as follows:
- if live mode is disabled => show only caches & waypoints from this list
- if live mode is enabled => show waypoints from all caches in that area

(no distinction made currently between map types: Plain, Target, SearchResult)

**Comment by Lineflyer** [comment]
> if live mode is disabled => show only caches & waypoints from this list

That is not the case: As stated above  waypoints of caches from other lists leak onto a mapped list (=non live map).
Maybe related to #15034 ...?

**Comment by Lineflyer** [comment]
This is no longer reproducible for me with 2024.03.14-NB
