### ISSUE TITLE
Viewport of map from list a bit to small

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15033]
Written from vacation on my mobile device:

When mapping a list of caches the shown map area is a bit to small:
Some caches are right at the edge of the screen (only half visible), some waypoints of caches even slightly outside of the shown area.

It looks like it just needs a bit "zoom further out offset".

Unified map
offline OAM

2023.12.16-NB

**Comment by Lineflyer** [comment]
Using Google map its ok, only happens on offline map for me.

Also:
With Google map the map opens at right zoom, on offline map the map is started and only then seems to zoom to fit.

**Comment by fm-sys** [comment]
> With Google map the map opens at right zoom, on offline map the map is started and only then seems to zoom to fit. 

While we should animate in/out zoom when using zoom controls, we can IMHO drop animations for `setZoomLevel`. This should fix the described behavior.

**Comment by Lineflyer** [comment]
I agree, that the animation should be removed for this case.
But the main issue here is not the animation but the fact, that the viewport is a bit to small on OSM in contrast to Google.

**Comment by moving-bits** [comment]
With PR #15092 being merged, zoom should now take your setting of "zoom includes waypoints" into consideration, either zooming to include all caches (but potentially missing some waypoints) or zooming to include both caches and its waypoints.

**Comment by Lineflyer** [comment]
Mmh...it worked also before. Just the zoom was a bit to strict on OSM, on Google it was OK.

**Comment by Lineflyer** [comment]
This is a video showing the difference between cache map including waypoints on OSM and Google with unified map.
- With OSM the map is zoomed so that the waypoints are exactly at the edge of being visible (see the two parking WPs)
- With Google the map is zoomed so that all waypoints are clearly visible (=better approach)


https://github.com/cgeo/cgeo/assets/949669/17056b87-a878-42da-be56-afc63a26a769

**Comment by moving-bits** [comment]
> Mmh...it worked also before. Just the zoom was a bit to strict on OSM, on Google it was OK.

This depends on the caches and waypoints you are mapping. My test case was a list of caches relatively close to each other, but having a couple of waypoints farther away. Then the difference before and after #15092 were quite visible.

> This is a video showing the difference between cache map including waypoints on OSM and Google with unified map.
> * With OSM the map is zoomed so that the waypoints are exactly at the edge of being visible (see the two parking WPs)
> * With Google the map is zoomed so that all waypoints are clearly visible (=better approach)

I'll add some padding to `zoomToBounds` for VTM.
