### ISSUE TITLE
Bottom sheet dismissed after screen off

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15038]
- Use (unified) live map
- Tap on cache to view bottom sheet
- Switch display off
- Switch display on

Result:
Bottom sheet disappears after display is on again

Expected:
Map conten should stay the same, i.e. bottom sheet still shown

**Comment by moving-bits** [comment]
Solution for this may be the same as for #15025 (keep a lifecycle-aware flag for opened cache/waypoint sheet, and restore sheet in `onCreate`, if flag is set)
