### ISSUE TITLE
Add ÖPNVKarte Map Layer

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#15041]
### Tell us your idea!

ÖPNVkarte.de offers a very nice way to see public transport options near you. This is very helpful for planing cache tours or to find a way home after a cache tour. Adding it to c:geo would be super useful.

### What solution would you suggest?

Adding it as a new online map layer.

### Is there an alternative?

I checked if there exists a Mapsforge version for offline use, but could not find anything.

**Comment by SammysHP** [comment]
Have you got permission from them to include it in c:geo? It can cause quite some traffic.

**Comment by dcjkfgdjhd** [comment]
No, I do not. If you want I could contact them.

**Comment by bekuno** [comment]
> No, I do not. If you want I could contact them.

That would be great.

**Comment by dcjkfgdjhd** [comment]
OK, I sent them an email. Let's see what they reply.

**Comment by moving-bits** [comment]
From the [website](https://www.öpnvkarte.de/):

"Die Karte steht unter den Bedingungen der CC-BY-SA und ODbL-Lizenzen (auch für die komerzielle Nutzung) frei zur Verfügung."

but

"Bitte bachten Sie, dass zwar der Karteninhalt frei zur Verfügung steht, dies bezieht sich jedoch ausdrücklich nicht auf die Server-Kapazität. Inbesondere bei Webseiten mit viele Nutzern ist die Karte auf eignenen Servern zu hosten."

So an explicit consent would be necessary (but I doubt that we would get one). (Technical aspects (compatibility with Mapsforge libraries) left aside for now.)

**Comment by dcjkfgdjhd** [comment]
> So an explicit consent would be necessary

I have contacted him just before Christmas, but have not received an answer so far.

> (but I doubt that we would get one).

I was not too pessimistic, because his map (using his server) is also included on openstreetmap.org, and this probably generates a lot more traffic than c:geo would. But so far it seems I was wrong.

**Comment by moving-bits** [comment]
_From https://github.com/cgeo/cgeo/issues/15686#issue-2278427682 by @moving-bits:_

User request on support (ticket 454010): Support [https://www.öpnvkarte.de/](https://www.xn--pnvkarte-m4a.de/) as map source.

According to their landing page, using their material is free of charge, only requires a copyright notice.

Unclear, though, is supported map format, whether they support either a compatible tileserver or provide a downloadable .map source. Before diving into implementation this would have to be clarified with their contact (contact data to be found on their landing page).

**Comment by fm-sys** [comment]
Tiles are available via `https://tileserver.memomaps.de/tilegen/{z}/{x}/{y}.png`, e.g. https://tileserver.memomaps.de/tilegen/17/68347/43328.png

>  Even though the map is available under an open licence, that does not mean our server capacity can be used in your project. Especially websites with a lot of traffic must be hosted on your own servers. If you need help with that, I can provide you an offer. 

Does that mean we may use it, and they'll just block us if we should cause too much traffic?

**Comment by jakedot** [comment]
It reads to me as if it's okay to mirror the tileserver, and he can assist if help doing that is needed, for which he may charge fees.

**Comment by dcjkfgdjhd** [comment]
On the official OSM website, if you switch to the transport map, the same tile server is used. Clearly, this must produce more traffic than cgeo ever would.

**EDIT: Ah, not true anymore. I just rechecked. Now the OSM transport map is hosted by Thunderforest and looks different.**

**Maybe at least the OSM transport map could be added to cgeo?**

I prefer the clear look of ÖPNVKarte, and the fact that all lines are marked with line numbers, but the OSM version would be much better than nothing.

**Comment by jakedot** [comment]
> BTW, what about allowing users to enter their own tile server URL?

that sounds like a good compromise!

**Comment by moving-bits** [comment]
PR #15714 allows you to enter a user-defined tile provider Uri, see settings => map sources in the UnifiedMap section

**Comment by moving-bits** [comment]
Seems there's no reply from the map author + we have implemented an alternative, so let's close here.

**Comment by dcjkfgdjhd** [comment]
An additional scaling option for this feature would be helpful. As the screenshot shows, currently it scales the images too large, so it looks really pixelated.

![2024-09-05 08 54 52](https://github.com/user-attachments/assets/53f346a9-65b9-4608-bcbe-e77d98817c89)

**Comment by moving-bits** [comment]
Even though UnifiedMap supports fractional scaling, the underlying map is bitmap-based in this case. So your device will scale the bitmaps (which leads to slight artifacts, as can be seen in the screenshot) until you reach the next straight zoom level, then it loads the new bitmaps prepared for that zoom level.

**Comment by dcjkfgdjhd** [comment]
I understand that this is bitmap based and that that is the cause of the pixelation. 

But is it not possible to simply scale the bitmaps smaller / load more bitmaps for a finer zoom level instead?

**Comment by fm-sys** [comment]
This would cause the labels to get way smaller though. Is this expected?

**Comment by dcjkfgdjhd** [comment]
Well right now they are too large as the screenshot shows. 

And readability depends mostly on the pixel count, so nothing would really change if the map would be displayed e.g. at the physical pixel scale of the display, because no pixel/information would be lost.

**Comment by moving-bits** [comment]
I don't think we can (want) do much here - we are using a library that displays the bitmap tiles that are delivered by the server - we don't want to fiddle with that library.

> But is it not possible to simply scale the bitmaps smaller / load more bitmaps for a finer zoom level instead?

We (the library) do/does load the tiles that the server sends for the respective zoom level.

**Comment by dcjkfgdjhd** [comment]
Actually, I now think that this might be some kind of bug?

The badly scaled images actually occur when zooming it. For example, after zooming in, it might look like this:

![2024-09-10 23 10 34](https://github.com/user-attachments/assets/d1240458-90c4-4b90-bfb4-8ad6b57f512a)

But if I then leave the map, and come back (e.g. by clicking the "stored" button and then the "map" button again), then it looks fine, **but the zoom level has changed** to something more reasonable for these bitmaps:

![2024-09-10 23 10 38](https://github.com/user-attachments/assets/1a603ef5-6ac7-4ddd-9856-210853fb5ef3)
