### ISSUE TITLE
No TB inventory for caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15043]
Reported on social media for our production version and can reproduce it with nightly as well:

Caches do no longer show any trackable inventory.
Applies to new opened caches and on stored caches the inventory vanishes on refresh.

I assume (not tested or debugged) a website change or problem.

**Comment by ThePhoDit** [comment]
I did report this on Reddit (I thought the inventory tab was just hidden or moved). Any logs I can provide with let me know.

**Comment by bekuno** [comment]
On the cache website you have a inventory list.
But the link of the TB goes in the nirvana.

Sample:
Cache with TB:
https://www.geocaching.com/geocache/GCAGK4R_wichtelwohnung
Link to the TB: 
https://www.geocaching.com/hide/details.aspx?TB=TB7ZAAK
=> Error 404: DNF

Link from the TB search site:
https://www.geocaching.com/track/details.aspx?tracker=TB7ZAAK

**Comment by bekuno** [comment]
@Lineflyer Maybe we should post an information message?

**Comment by eddiemuc** [comment]
Indeed a website change. Apparently gc.com changed the link to a trackable from something like `https://www.geocaching.com/track/details.aspx?guid=abcd-efgh-1234-5678` to something like `https://www.geocaching.com/hide/details.aspx?TB=TB7ZAAK`. Notably the link contained a guid before and contains a trackable code now. Don't know what implications this has on further c:geo logic.

For reference:

The pattern c:geo is currently using to parse trackables from an HTML inventory snippet:
`Pattern.compile("[^<]*<li>[^<]*<a href=\"[a-z0-9\\-\\_\\.\\?\\/\\:\\@]*\\/track\\/details\\.aspx\\?guid=([0-9a-z\\-]+)[^\"]*\"[^>]*>[^<]*<img src=\"[^\"]+\"[^>]*>[^<]*<span>([^<]+)<\\/span>[^<]*<\\/a>[^<]*<\\/li>");`
    
An example HTML snippt containing such an inventory (taken from HCAGK4R, same example as above):

`ctl00_ContentBody_uxTravelBugList_uxInventoryLabel">Inventory</span> </h3> <div class="WidgetBody"> <ul> <li> <a href="https://www.geocaching.com/hide/details.aspx?TB=TB7ZAAK" class="lnk"> <img src="/images/WptTypes/sm/21.gif" width="16" alt="" /><span>the gambler</span></a> </li> </ul> <div`

**Comment by Lineflyer** [comment]
If the change is persistent next days we should maybe issue a bugfix release as cache inventory is a rather important feature.

**Comment by SammysHP** [comment]
That was already reported almost a week ago, but I didn't think it would also affect c:geo:

https://www.geoclub.de/forum/t/20231213-links-zu-travelbugs-auf-geocaching-com-aktuell-defekt.82829/

**Comment by eddiemuc** [comment]
Fixed with PR #15048

**Comment by bekuno** [comment]
The linking on cache sites to TB is now changed and working.
E.g., the link to the TB on the site above is now https://www.geocaching.com/track/details.aspx?TB=TB7ZAAK
This is a mix between the old and the new link form.
