### ISSUE TITLE
Route elevation chart keeps popping up on return to c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15047]
### Describe your problem!

This one is not clearly reproducible but kept happening all day today while caching (but not yesterday in same scenario).
After leaving c:geo map and coming back the elevation chart for my individual route shows up without tapping the route.  

I repeated the scenario described below for all caches on my trail and it happend in approx. 70% of cases.

### How to reproduce?

- Had a list of approx. 20 caches
- Mapped the list
- Created an individual route along this cache trail
- Using function "Remove from route after cache is logged"
- Using function "Set destination to route start"
- Approaching cache while on map
- Opening bottom sheet and invoke external navigation (in my case: Radar)
- Radar app is opened, c:geo in background
- Press back in radar app to close it
- Returning to c:geo map

### Actual result after these steps?

Bottom sheet is dismissed (see other issue) but immediately after return to c:geo the route elevation chart appears and I need to manually close it.

### Expected result after these steps?

No unexpected appearance of elevation chart

### Reproducible

No

### c:geo Version

2023.12.18-NB

**Comment by moving-bits** [comment]
@Lineflyer 
I was not able to reproduce this error in my test environment with current `master`, using Google Maps as navigation app - does it still happen for you? And if so, which radar app are you using as navigation app?

**Comment by moving-bits** [comment]
I've found a different way to reproduce this behavior:
- create an individual route
- show the elevation chart for it, and hide it again
- add or remove an item to/from the individual route

elevation chart comes back in this case

I'll provide a fix for it, and hopefully it fixes the use-case mentioned above as well.
