### ISSUE TITLE
MapQuest 

### ISSUE THREAD

**Issue by devemux86** [cgeo/cgeo#15057]
### Describe your problem!

Do you probably use MapQuest? There is a change in their plans:

**Introducing Pay-As-You-Go Billing**: We're transitioning our previous free plan to a Pay-As-You-Go billing model. With this model, you only pay for the resources you consume, making it an ideal choice for any occasional or sporadic usage. But don't worry, you still get 15,000 free transactions with no time limit! 

**What You Need to Do**: To continue using our services, please take a moment to update your account with a valid credit card. This will ensure a seamless transition to the new Pay-As-You-Go billing model. If you do not provide a valid payment method, your account is eligible for discontinued service starting January 15th, 2024.

### How to reproduce?

Geocoding

### Reproducible

Yes

### c:geo Version

All versions

**Comment by eddiemuc** [comment]
Are we using this for address search?

**Comment by moving-bits** [comment]
> Are we using this for address search?

Yes, as a fallback for Android's internal Geocoder
