### ISSUE TITLE
Map rotation should be averaged to avoid shaking

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15050]
Not sure if this is device dependant...

When using the automatic map rotation while walking, the maps shakes a bit as there are small variations in my orientation.

While our compass should probably take every reading I wonder if we should dampen this on the map to have a better usability.

2023.12.18-NB

**Comment by fm-sys** [comment]
As Locus has a similar feature, can you check whether the map is shaking with Locus autorotation mode as well?

Currently the map rotates instantly. If you put your phone on the table and rotate it, the map feels to stay fixed. 

Averaging the values would cause the map to lag behind. So if we do averaging it should IMHO be only over a _really short_ period of time.

**Comment by fm-sys** [comment]
I think there are two use cases:
- navigating, averaging over 5 seconds or so would be fine and would provide a way more smooth experience
- use it for bearing, no averaging is wanted at all (the compass activity doesn't have averaging either)

**Comment by moving-bits** [comment]
In today's Goole Maps auto rotation ("old map"), we don't use averaging, but use a minimum deviation of 15 degree (IIRC) before we adapt the map orientation on auto rotation. 15 degree may be too much, but maybe using some sort of deviation could help here as well?

Personally I would prefer a map pointing slightly off-north temporarily over a map constantly shaking or even spinning, in both navigation mode and "just looking at the map while standing still". If I want the "exact in this second" orientation I can still use the compass.

**Comment by fm-sys** [comment]
> Personally I would prefer a map pointing slightly off-north temporarily over a map constantly shaking or even spinning, 

@moving-bits have you already tested the feature on a real device? A spinning map will never happen on a device which supports compass functionality properly (and won't happen in the emulator either if a proper device orientation is specified). And the map will not shake more than the compass would do. Is your compass significantly shaking (then this would be a general bug in c:geo and should be fixed on a global level)?

@Lineflyer could you provide some insides on how much the map is shaking on your device while walking, maybe even a screen recording? 

> in both navigation mode and "just looking at the map while standing still". If I want the "exact in this second" orientation I can still use the compass.

Not for me: From time to time I want to know in which exact orientation a town/mountain/etc is and use the map in auto-rotation mode for it. (actually, this is the only situation when I use that mode at all)

Don't get me wrong: If there are indeed significant problems, we should of course fix them, but I definitly want to avoid fixing something which never was broken.

**Comment by Lineflyer** [comment]
> @Lineflyer could you provide some insides on how much the map is shaking on your device while walking, maybe even a screen recording?

Will do as time permits. I do consider this issue as minor anyway.

**Comment by Lineflyer** [comment]
It became much better with recent builds. The energy saving mode rotation works perfect for me and no more shaking.
On my new device even the normal rotation mode works reliably. I guesss the sensors on my old device have not been that good.

Closing.
