### ISSUE TITLE
Too much semi-transparency

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#15084]
### Describe your problem!

While testing the semi-transparent WP from PR #15000 ( I love it) I discovered strange behaviours.

First, some of the found tradi caches are normal shown, but some are semi-transparent.
![grafik](https://github.com/cgeo/cgeo/assets/32555742/b2795446-02bd-43a0-b477-16ddda475fa0)

I did not found a reason for it.

Second, the smileys on the caches recent logs are every time semi-transparent.
![grafik](https://github.com/cgeo/cgeo/assets/32555742/a09e9c0e-0856-4b40-a779-725391b3a105)

### How to reproduce?

see above

### Reproducible

Yes

### c:geo Version

2023.12.23-NB

**Comment by moving-bits** [comment]
I'll look into it
