### ISSUE TITLE
Some dialogs are missing the close button

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15094]
### Describe your problem!

Since a while I noticed, that some standard messages/dialogs are missing its OK (dismiss) button.

Of course you can close it by tapping outside of it, but from usability aspect I would like to see a close button here as it was there before and users might not know what to do (or even have trouble to tap outside on smaller screens).

### How to reproduce?

- Export field notes, export GPX or perform backup 

### Actual result after these steps?

![image](https://github.com/cgeo/cgeo/assets/949669/ddc6cf81-6b89-4c64-899a-557ad45d903c)

### Expected result after these steps?

Same dialog but "close" button on lower right

### Reproducible

Yes

### c:geo Version

2023.12.24-NB

**Comment by eddiemuc** [comment]
Fixed with PR #15095
