### ISSUE TITLE
Mapping a list shows "0 caches" in action bar subheading

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15103]
### Describe your problem!

When mapping a list on unified map the action bar shows "0 caches" initially and only counts the correct number after some panning on the map

### How to reproduce?

- Open a list with x caches on
- Map the list

### Actual result after these steps?

Action bar shows list name and 0 caches as subheading

### Expected result after these steps?

Action bar should show x caches as subheading

### Reproducible

Yes

### c:geo Version

2023.12.25-NB

**Comment by moving-bits** [comment]
After cross-checking a few things:
- counting is done by retrieving the viewport and counting the caches within this viewport
- for some reason, the value retrieved for the viewport is nonsense in the beginning, eg "0/0 - 0/0" or something slightly larger, thus counting within this "viewport" returns zero
- I've stumbled upon this a couple of days ago for VTM and thought it was VTM-only, but while debugging here I can see that GM is affected as well 🤔 

I will investigate further...
