### ISSUE TITLE
Parallel installation of c:geo failing to show map & settings

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15101]
Today I tried installing a dev version of c:geo parallel to the latest release version using AS.

Installation itself worked (although AS started the wrong version after that, meaning: the release version), but the dev installation was only partially usable (no map, no settings). From the logfile gathered I can see two exceptions:

### exception 1: binding BRouter service

```
12-26 09:15:16.909 13134 13134 W cgeo : [main] UncaughtException
12-26 09:15:16.909 13134 13134 W cgeo : java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching.developer/cgeo.geocaching.AboutActivity}: java.lang.SecurityException: Not allowed to bind to service Intent { cmp=cgeo.geocaching/.brouter.InternalRoutingService }
12-26 09:15:16.909 13134 13134 W cgeo : at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3255)
12-26 09:15:16.909 13134 13134 W cgeo : at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
12-26 09:15:16.909 13134 13134 W cgeo : at android.app.ActivityThread.access$1100(ActivityThread.java:222)
12-26 09:15:16.909 13134 13134 W cgeo : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
12-26 09:15:16.909 13134 13134 W cgeo : at android.os.Handler.dispatchMessage(Handler.java:102)
12-26 09:15:16.909 13134 13134 W cgeo : at android.os.Looper.loop(Looper.java:158)
[...]
```
(and a similar one from UnifiedMap)

I remember having the same exception in the emulator before I uninstalled the previous dev version (with cgeo.geocaching as package name).

### exception 2: accessing clipboard
```
12-26 09:16:27.659 13433 13433 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()' on a null object reference
12-26 09:16:27.659 13433 13433 W System.err: at android.os.Parcel.readException(Parcel.java:1626)
12-26 09:16:27.659 13433 13433 W System.err: at android.os.Parcel.readException(Parcel.java:1573)
12-26 09:16:27.659 13433 13433 W System.err: at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:197)
12-26 09:16:27.659 13433 13433 W System.err: at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:247)
12-26 09:16:27.659 13433 13433 W System.err: at cgeo.geocaching.utils.ClipboardUtils.getText(ClipboardUtils.java:40)
12-26 09:16:27.659 13433 13433 W System.err: at cgeo.geocaching.SearchActivity.lambda$handlePotentialClipboardGeocode$4$cgeo-
geocaching-SearchActivity(SearchActivity.java:301)
12-26 09:16:27.659 13433 13433 W System.err: at cgeo.geocaching.SearchActivity$$ExternalSyntheticLambda8.run(D8$$SyntheticClass)
12-26 09:16:27.659 13433 13433 W System.err: at android.os.Handler.handleCallback(Handler.java:739)
12-26 09:16:27.659 13433 13433 W System.err: at android.os.Handler.dispatchMessage(Handler.java:95)
12-26 09:16:27.669 13433 13433 W System.err: at android.os.Looper.loop(Looper.java:158)
[...]
``` 

Not sure which one could be related to `SettingsActivity`, need to test further with AS attached (didn't have time this morning). "View settings" is not affected, though.

### system info

c:geo version: 2023.12.26-dbd08f8 developer build

Device:
- Device type: SM-G903F (s5neoltexx, samsung)
- Available processors: 8
- Android version: 6.0.1
- Android build: MMB29K.G903FXXU2BRH2
- Screen resolution: 1080x1920px (360x616dp)
- Pixel density: 3.0
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 23.48.16 (040300-590025996)
- Memory:  Available:529,1 MB, Total:1,8 GB, Threshold: 119,2 MB, low:false

Sensor and location:
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
- Settings: v9, Count:98
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: 30. Apr., 19:39
- Last auto backup: 26. Dez., 09:14
- Routing mode: Walk
- Live map mode: true
- Use unified map: true
- OSM multi-threading: true / threads: 4
- Map: Google: Karte
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:
- Hide waypoints: -
- LIVE: Cache-Typ: Mystery ({"advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{"values":["MYSTERY"]}},{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{}}]}})
- OFFLINE: Keine ({"advanced":false,"inconclusive":false})

Stored Filters (#0):

Services:
- Geocaching sites enabled:
   - geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   - Geocaching.com Adventure Lab
- Geocaching.com date format: yyyy-MM-dd
- Geocaching.com website language: de-DE
- Last login error on geocaching.com: communication error (2023-03-04 11-40)
- Last successful login on geocaching.com: 2023-12-26 09-21
- Routing: internal / BRouter installed: false
- Installed c:geo plugins: contacts

Permissions
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: granted

**Comment by moving-bits** [comment]
Accessing maps and settings will be fixed with #15106

**Comment by fm-sys** [comment]
Thanks for looking into it!

**Comment by moving-bits** [comment]
seems to be fixed by the two related PR, so let's close here
