### ISSUE TITLE
SAF problem? Downloaded map file not detected

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15129]
I've downloaded an OAM map file using the integrated downloader. Downloading and unzipping was ok, but the file did not show up in the map list.

I've tried
- removing c:geo from memory + restarting
- restarting the device
- re-setting the map folder (from "default" to "/cgeo/maps" and vice versa)

and combinations of it. Nothing helped.

(The other map file in the same folder can be read without problems.)

Then I downloaded the file from my mobile to my laptop and put it into the emulator - worked fine, so the file itself seems to be ok.
I deleted the files from the mobile, restarted the device and uploaded the files from the laptop to the mobile. Again, no look.

No errors in the log with regarding to reading the map file, SAF errors etc.

But when I open the downloader again, I get an error message that the companion file for the newly downloaded map cannot be read (which leads to crashing c:geo - oops! - but that's a different issue.) But why can't the file be read?

I tried a different OAM file - same result.
I tried a file from Mapsforge server - same result.

Seems that downloader storing the files and/or SAF routines recognizing the downloaded files is broken.

Android 14, physical Samsung device.
Cannot install dev builds on that device, but can change log level for c:geo etc.

Where else can I look / what else can I try?

**Comment by eddiemuc** [comment]
If I understand correctly the error only happens on physical device, not emulator?

Can you try to log the files currently seen by SAF in map folder before the crash happens? There should be a `list` method.

**Comment by moving-bits** [comment]
> If I understand correctly the error only happens on physical device, not emulator?

Yes. Though I've tested only one physical device and one emulator.

> Can you try to log the files currently seen by SAF in map folder before the crash happens? There should be a `list` method.

The physical device is a managed device. I can only install via app store, so no dev builds on that device. Would activating a different log level help?

**Comment by moving-bits** [comment]
Problem resolved: For some other testing I had removed "all files access" from "com.android.externalstorage". (Found this while checking logfiles for warnings with "contentstorage" in the text - thanks for putting those in!) Strange, though, that my default map (which is OAM as well) could still be read without problems, while the other maps were unaccessible.

**Comment by eddiemuc** [comment]
Ok, glad this could be resolved :-)

Do you think we should make such situations more "visible" to the user (e.g. displaying some popup saying "check if your system has all-file-access for externalstorage-service)?

**Comment by moving-bits** [comment]
I guess a reference to "external storage" would be too technical for most users (and even those who read this, associate a SD card with it, stating their device does not have one - had this on support multiple times).

For checking whether all files in the configured map folder are readable (both security-wise as being non-broken files), we could add an automated check being run in the background, that places a notification on home screen, if something's bad with those files. This notification could link to a more detailed FAQ article.

**Comment by SammysHP** [comment]
I just learned that Locus is provided in two variants now: The regular Play Store release which doesn't come with manage external storage permission and a special release that you can download as an APK from their website with manage external storage permission. Reason for that is that Google Play rejects apps with all-file-access permission.

https://support.google.com/googleplay/android-developer/answer/10467955
