### ISSUE TITLE
waypoint not shown on map

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15137]
### Describe your problem!

waypoint not shown on map

### How to reproduce?

Open waypoint list of a cache
Click on compass, right of waypoint
Click on map in top line

### Actual result after these steps?

Only symbol for cache is shown

### Expected result after these steps?

symbol for cache and waypoints are shown

### Reproducible

Yes

### c:geo Version

2024.01.02-NB-eeec2a4

### System information

```text
Routing is shown to the waypoint, so the focus on the wayloint is kept (see #15131)
```

**Comment by moving-bits** [comment]
Could not reproduce this on current `master`, waypoints were always shown. Are you sure you have experienced this with the 2024.01.02 nightly? I'm asking because of #15134 which got merged just a few days ago and 2024.01.02 might be the first nightly including that fix (which is actually for #15131, but includes loading of the waypoint data).

**Comment by geocachermgo** [comment]
yes, that happens with 2024.01.02-NB-eeec2a4 which I still run. I can send a screenshot showing the red routing line to the waypoint, but no symbol there. I can also update to today's (or tomorrows) nightly and try again. I just tried it with the manually created Limburg waypoint (picture see #15131)

**Comment by geocachermgo** [comment]
![Screenshot_2024-01-03-16-56-18-400_cgeo geocaching](https://github.com/cgeo/cgeo/assets/43813636/96a059fa-6700-4799-b052-12670d565b92)

**Comment by geocachermgo** [comment]
The same with current 2024.01.03-NB-eeec2a4
The same for manually added waypoint Limburg and Parking waypoint from the listing.

**Comment by moving-bits** [comment]
Thanks for the additional info.
Is it possible that you have set settings => map content & behavior => show waypoints to 0?
(Navigation target should still be shown despite that setting, but with that setting I was able to reproduce the issue.)

**Comment by geocachermgo** [comment]
![Uploading Screenshot_2024-01-03-17-59-49-119_cgeo.geocaching.jpg…]()

**Comment by geocachermgo** [comment]
## System information

c:geo version: 2024.01.03-NB-eeec2a4

Device:
-------
- Device type: MI 8 (dipper, Xiaomi)
- Available processors: 8
- Android version: 10
- Android build: QKQ1.190828.002 test-keys
- Screen resolution: 1080x2029px (392x737dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: disabled - 23.48.16 (100400-590025996)
- Memory:  Available:973,8 MB, Total:5,5 GB, Threshold: 216,0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:252
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: 2. Jan., 07:29
- Last auto backup: 21. Dez. 2023, 13:38
- Routing mode: Bike
- Live map mode: false
- Use unified map: true
- OSM multi-threading: true / threads: 4
- Map: Baden-Wuerttemberg (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:Locus/mapsVector/Baden-Wuerttemberg.map
  - Atts: Map data (c) OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Status: Gefunden=Nein, Eigener=Nein ({"advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{"values":["owned_no","found_no"]}},{"type":"size","config":{}},{"type":"favorites","config":{"percentage":false}},{"type":"type","config":{}}]}})
- OFFLINE: Keine ({"advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{}},{"type":"size","config":{}},{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{}}]}})

Stored Filters (#3):
- gefunden: {"name":"gefunden","advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"status","config":{}}]}})
- T5: {"name":"T5","advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"terrain","config":{"min":5.0,"max":5.0}}]}})
- T5t: {"name":"T5t","advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"owner","config":{"text":"*t*","type":"contains","matchCase":false}},{"type":"terrain","config":{"min":5.0,"max":5.0}}]}})

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd.MM.yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2023-12-14 12-59)
- Last successful login on geocaching.com: 2024-01-03 18-03
- Routing: external / BRouter installed: true
- Installed c:geo plugins:  none

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (70,9 GB free) v3 internal isDir(17 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (70,9 GB free) v3 internal isDir(17 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (70,9 GB free) v3 external non-removable isDir(1315 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (70,9 GB free) v3 internal isDir(0 entries)
- Map render theme path: 
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=1, dirs:>=14, totalFileSize:>=118,7 KB, free space: 70,9 GB, files on device: 7413760)
  - OFFLINE_MAPS: /Locus/mapsVector (User-Defined)[/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector, Av:true, files:16, dirs:2, totalFileSize:7,6 GB, free space: 70,9 GB, files on device: 7413760)
  - OFFLINE_MAP_THEMES: /Locus/mapsVector/_themes (Default)[/Locus/mapsVector/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 70,9 GB, files on device: 7413760)
  - OFFLINE_MAP_SHADING: /Locus/mapsVector/_hgt (Default)[/Locus/mapsVector/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 70,9 GB, files on device: 7413760)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:8, dirs:0, totalFileSize:3,2 MB, free space: 70,9 GB, files on device: 7413760)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:64, dirs:0, totalFileSize:23,7 MB, free space: 70,9 GB, files on device: 7413760)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=8, dirs:>=12, totalFileSize:>=179,1 MB, free space: 70,9 GB, files on device: 7413760)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 70,9 GB, files on device: 7413760)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:>=1, dirs:>=9, totalFileSize:>=118,7 KB, free space: 70,9 GB, files on device: 7413760)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:8, dirs:1, totalFileSize:81,6 KB, free space: 70,9 GB, files on device: 7413760)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 70,9 GB, files on device: 7413760)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 70,9 GB, files on device: -1)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #2
  - content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector (20. Feb. 2023, 22:40):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (30. Jan. 2021, 13:54):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v101, Size:44,6 MB) on system internal storage

--- End of system information ---

**Comment by moving-bits** [comment]
Still cannot reproduce it otherwise, but have prepared a PR which fixes the observation I've made and some other quirks. Let's see in next nightly version whether this fixes your issue as well.

**Comment by geocachermgo** [comment]
Fixed with 2024.01.04-NB-5e65b54
Thanks!

**Comment by moving-bits** [comment]
Thanks for the feedback, glad that it works now.

**Comment by geocachermgo** [comment]
Maybe it has something to do with buffets. Right now it happend again with a variant: no symbol was shown (not cache, no waypoint).
I removed cgeo from memory. Afterwards it worked normally again.

**Comment by geocachermgo** [comment]
With todays 2024.01.07-NB1-9bd14f4 it is not working. Will this issue reopend or shall I create a new bug issue? Routing goes to waypoint but waypoint is not shown.
![Screenshot_2024-01-07-12-11-13-893_cgeo geocaching](https://github.com/cgeo/cgeo/assets/43813636/accbaebb-f4d9-4a05-ae85-04c4fa53ab1b)

**Comment by moving-bits** [comment]
I'll reopen the issue

**Comment by geocachermgo** [comment]
With 2024.01.12-NB-42e636e I noticed that the waypoints appear on the map if I open the bottom gear symbol("Schnelleinstellungen").

**Comment by geocachermgo** [comment]
Still open with 2024.01.22-NB-b6c949b

**Comment by geocachermgo** [comment]
Now the waypoint is shown (before update to todays nighly). The last days the waypoints were always not shown and appeared only when opening the "Schnelleinstellungen" menue.

**Comment by moving-bits** [comment]
There have been no code changes in this area in the last two weeks, so any observed changes in behavior must have some different reasons. (That's the problem with non-reproducible or only partly-reproducible errors...)

If it happens again, can you cross-check my question, please: Does this happen on the new map only (aka "Unified Map"), or also if you disable Unified Map (as described above) and thus use the "old" map implementations?

**Comment by geocachermgo** [comment]
As mentioned 3 weeks ago it was there most of the time but not always. I will check if it happes again.

**Comment by geocachermgo** [comment]
Now its there again with 2024.01.24-NB-029ec46
No waypoint with unified map:
![IMG_20240127_185131](https://github.com/cgeo/cgeo/assets/43813636/9721f8c8-ffd2-4c62-b84d-5c28e1967c26)
If I switch off (as described obove) the waypoint is there and in the center as expected.
![IMG_20240127_185227](https://github.com/cgeo/cgeo/assets/43813636/ed774454-4409-4f14-9b73-5e2ec56c8d8b)

If I should provide any other information, please let me know.

**Comment by moving-bits** [comment]
Finally had a situation in my local emulator which showed the same behavior. I'll create a PR which attempts to fix the issue.

**Comment by moving-bits** [comment]
@geocachermgo 
Does this issues still happen for you after #15270 has been merged (about a week ago)?

**Comment by geocachermgo** [comment]
I was a little behind on the updates and was running the nighly from 29.1. Even with this version I was not noticing missing waypoints.
Just now I uddated and did a little testing. I could not reproduce a wrong behaviour. So I closed it. If it appears again I will ask for reopening.
