### ISSUE TITLE
calculation formula for substrings

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15138]
### Tell us your idea!

I suggest an additional substring calculation:
sub1( \<string\> ;i)=substring( \<string\> ;i-1;1)

### What solution would you suggest?

In the vast majority of the substring the given index is not starting with 0 but with 1 and also only 1 character is needed.
Latest example:GCAHM12, current solution see alternative

### Is there an alternative?

Add a -1 in the sub formula
{c:geo-start}
@Finale (F) {CC|N $N1$N2° $N3$N4.$N5$N6$N7|E $E1$E2° $E3$E4.$E5$E6$E7}
$C='1234567890123456789012345678901234' | $N1=sub(C;13-1;1) | $N2=sub(C;20-1;1) | $N3=sub(C;15-1;1) | $N4=sub(C;24-1;1) | $N5=sub(C;33-1;1) | $N6=sub(C;16-1;1) | $N7=sub(C;9-1;1) | $E1=sub(C;21-1;1) | $E2=sub(C;4-1;1) | $E3=sub(C;28-1;1) | $E4=sub(C;14-1;1) | $E5=sub(C;10-1;1) | $E6=sub(C;26-1;1) | $E7=sub(C;32-1;1)
{c:geo-end}

**Comment by eddiemuc** [comment]
Good idea! I added a new function `chars` in PR #15216

**Comment by geocachermgo** [comment]
Look good to me! Thanks!

**Comment by geocachermgo** [comment]
Tested and found working.
Only point: I'd love to have a 2 letter abbreviation like cs for checksum, lv for lettervalue. Is "ch" possible?

**Comment by moving-bits** [comment]
> Only point: I'd love to have a 2 letter abbreviation like cs for checksum, lv for lettervalue. Is "ch" possible?

got implemented with #15250

**Comment by geocachermgo** [comment]
Tested and working! I tried also to trick the calculation by a cyclic reference
 $A=ch('abcd';B) | $B=C | $C=lv(A)
but that was correctly shown als cyclic.
