### ISSUE TITLE
Checkstyle configuration

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15142]
I've made an update to #13573 today and only after pushing it to the CI noticed a wrong import order, detected by CheckStyle locally. So I expected the CI build to fail, but all checks got marked as green.

Wrong import order:
![image](https://github.com/cgeo/cgeo/assets/3754370/b10a67d7-e957-439e-8c86-20f414954efa)

@bekuno 
Can you cross-check and adapt the CI config?

(Commit id is [0fbd158](https://github.com/cgeo/cgeo/pull/14980/commits/0fbd158ac9423fcacc1340a4c6d1bb3ab86096a2), [Codacy run id](https://github.com/cgeo/cgeo/pull/14980/checks?check_run_id=20119363941), [build run id](https://ci.cgeo.org/job/cgeo-CI_PR-build/7231/))

**Comment by bekuno** [comment]
This CI run shows 2 checkstyle warnings, see https://ci.cgeo.org/job/cgeo-CI_PR-build/7231/checkstyleResult/.

- ImportOrderCheck:
 This is defined in checkstyle.xml as:
~~~
        <module name="ImportOrder">
            <property name="severity" value="info" />
~~~
- FinalLocalVariableCheck:
~~~
        <module name="FinalLocalVariable">
            <property name="severity" value="info" />
~~~

So both problems are detected. But as they ar has the severity `info`, the CI run does not fail.

To compare please have a look at https://ci.cgeo.org/job/cgeo-CI_PR-build/7236/.
~~~
Checkstyle: 5 Warnungen aus einer Analyse.
- 4 neue Warnungen
- eine behobene Warnung
- Plug-in Resultat: - 2 warnings of priority Normal exceed the threshold of 0 by 2
~~~
Here are 2 warnings with severity `normal`.

@cgeo/team Should we change all/some of the severity `info` change to normal? (14 occurences)

**Comment by moving-bits** [comment]
Thanks @bekuno for looking into this. I just followed the green markers for the builds and did not cross-check their details - my bad. 

Is there a way to make such non-breaking infos more visible in GitHub?
Maybe we can discuss the severity level in our next dev meeting.
