### ISSUE TITLE
CI watchdog master - createTrackableLog test error

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#15168]
### Describe your problem!

Since today the test `createTrackableLog` fails.

For details see https://ci.cgeo.org/job/WatchdogTests_master/2387/artifact/main/build/reports/androidTests/connected/flavors/basic/cgeo.watchdog.WatchdogTest.html .

### How to reproduce?

see also https://ci.cgeo.org/job/WatchdogTests_master/2387/testReport/cgeo.watchdog/WatchdogTest/testGeocachingLogTrackable/

### Reproducible

Yes

### c:geo Version

2024-01-05 Watchdog

**Comment by eddiemuc** [comment]
Fixed with PR #15164

**Comment by bekuno** [comment]
Perfect, Test rebuild is green: https://ci.cgeo.org/job/WatchdogTests_master/2388/testReport/cgeo.watchdog/WatchdogTest/
