### ISSUE TITLE
Restoring newer backup not possible

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15160]
Today I needed to test something against `release` branch while emulator was set up with a build from `master`.
`release` is on db version 100, `master` on 101 (in my local setting).

I installed the compiled version and landed in configuration wizard (probably due to different app id), so I chose "restore database" to import my existing data. That failed with the following error:

![image](https://github.com/cgeo/cgeo/assets/3754370/ce4c8c5c-2bf0-4dc2-99ef-a109535e6f37)

If technically possible this situation should also be handled by our "is version of database compatible to version expected by build" check.

Might be related to #15031/#15036.

**Comment by eddiemuc** [comment]
Update: the fix for #15031 was merged to master only (not release). This means that freshly created databases from a release build don't contain the downgradeable versions yet.

@moving-bits I guess that AS forced you to reinstall a fresh version of c:geo onto your emulator device after you switched the branch. Because since recently it happens to me frequently that AS claims it needs to install fresh versions of the app to deploy on emulator. I hadn't that before, and it is very unnerving.

**Comment by moving-bits** [comment]
Thanks for looking into it. As I tend to use those emulators over months, it's very likely that this database was created before applying the fix. (Ok, looked it up: that specific backup was from beginning of December.)

I'm back to `master` currently. Starting an "app inspection" to look into the database reveals the following value: 96,97,98,99,100,101,102,85,86,87,88,89,90,91,92,93,94,95

But that's probably not the database c:geo took for restoring a backup (as that would be in private storage under a different app id). So I downloaded the sqlite file from the backup and - voila - it has no entry for compatible versions.

I'll add the entry manually and cross-check.

> I guess that AS forced you to reinstall a fresh version of c:geo onto your emulator device after you switched the branch.

Yes, but that's probably to be expected, assuming that `release` does not contain the new app id, whereas `master` does.
What I need to remember, though, is to run a manual Gradle sync after switching between `master` and `releases` due to strange effects I get otherwise, frequently not being able to compile at all without syncing.

**Comment by eddiemuc** [comment]
> Thanks for looking into it. As I tend to use those emulators over months, it's very likely that this database was created before applying the fix. (Ok, looked it up: that specific backup was from beginning of December.)

To prevent a misunderstanding:
the check whether a db is downgradeable is done against the database installed BEFORE the backup. Not against the database target in the backup.

**Comment by moving-bits** [comment]
> > Thanks for looking into it. As I tend to use those emulators over months, it's very likely that this database was created before applying the fix. (Ok, looked it up: that specific backup was from beginning of December.)
> 
> To prevent a misunderstanding: the check whether a db is downgradeable is done against the database installed BEFORE the backup. Not against the database target in the backup.

I suspected something like that. But isn't that sort of a logic error? When restoring from a backup (especially in case of installing a new system) I want to know if the database I want to restore is compatible with what my app expects, so it should check against that database.

BTW: I uploaded the updated database to my emulator, started the `release`-based version and tried to restore that database. Now it won't detect it, even though I tried with "select a different backup" and granted full access to the modified folder...

![image](https://github.com/cgeo/cgeo/assets/3754370/87f6c2fc-d7ef-49ba-b266-afe98e1ff250)

**Comment by eddiemuc** [comment]
> BTW: I uploaded the updated database to my emulator, started the `release`-based version and tried to restore that database. Now it won't detect it, even though I tried with "select a different backup" and granted full access to the modified folder...

That looks like a different issue. Some issue with SAF perhaps?

**Comment by eddiemuc** [comment]
> > 
> > To prevent a misunderstanding: the check whether a db is downgradeable is done against the database installed BEFORE the backup. Not against the database target in the backup.
> 
> I suspected something like that. But isn't that sort of a logic error? When restoring from a backup (especially in case of installing a new system) I want to know if the database I want to restore is compatible with what my app expects, so it should check against that database.

I am sorry. The check is of course done against the backup database. It would not make sense the other way around.

**Comment by moving-bits** [comment]
> That looks like a different issue. Some issue with SAF perhaps?

Log looks ok: "[main] Folder set to 'content://com.android.externalstorage.documents/tree/primary:cgeo/backup/2023-12-02 22-59'" (marked as "warning")

**Comment by moving-bits** [comment]
I've debugged a bit into the specific folder. Problem seems to be that `DocumentContentAccessor.getFileInfo()` returns a `FileInformation` object which has a `lastModified` value set to 0 - which for the calling method `BackupUtils.getDatabaseBackupTime()` is the marker for "file does not exist":

![image](https://github.com/cgeo/cgeo/assets/3754370/6e30a0c6-a7a6-4ce5-9ef8-285097be36cf)

"lastModified == 0" may be the result of Android Studio uploading the file, but not setting a lastModified value.

Maybe the involved methods can use some other distinct value as "file does not exist" marker, which is not used by the file system itself. ("-1" ?)

**Comment by eddiemuc** [comment]
> Maybe the involved methods can use some other distinct value as "file does not exist" marker, which is not used by the file system itself. ("-1" ?)

Good idea!

**Comment by moving-bits** [comment]
I've created a PR for it. (Seems to be BackupUtils-local, no need for me to change something in SAF code.)
