### ISSUE TITLE
Settings' fragments overlapping

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15171]
_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/15120#issuecomment-1878387116_
            
Another thing I noticed, which may also be related to the Basic/Premium chaos, therefore not opened a dedicated issue yet: when leaving geocaching.com service settings (after the above crashes), c:geo shows the following:

https://github.com/cgeo/cgeo/assets/9889015/c570b0b8-8eef-46d7-b353-3809c2684824

**Comment by moving-bits** [comment]
Probably caused by the changes in #15096

**Comment by MagpieFourtyTwo** [comment]
Yep - is working correctly now. Thx!
