### ISSUE TITLE
Formula parsing on variables tab leads to ANR

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15173]
User report on support and reproducible for me with current `master`:

- open cache GCAHQ78
- swipe to variables tab
- select "scan listing"

Result: ANR

Hang seems to be occurring in FormulaUtils.scanText's call to `m.find()`:

![image](https://github.com/cgeo/cgeo/assets/3754370/ac7a8fd3-e22f-4abd-963e-3c05daf18d6d)

variable `start` gets values 0, 468, 1095, 1106, 1146 and 1162 before the hang starts.

In contrast to this, cache details page's "waypoints => scan for waypoint formulas" works instantly and gives you two results.

**Comment by eddiemuc** [comment]
Hopefully fixed with PR #15175
