### ISSUE TITLE
[info] position record interrupted

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15185]
### Describe your problem!

Between 21.12. and 7.1. the position recording did not work. Unfortunately I cannot say to which cgeo nightly version that correlates since I don't have an history of my updates. Normally I have the recording not visible on map, I only switch it on occasionally.
It looks like it started recording again since I activated "show position recording on map" and  I checked the settings and toggeled the position-recording-button off and on again

### How to reproduce?

Since recording is now working, not reproduceable.

### Actual result after these steps?

No position is shown on map and in the gpx export file for the mentioned time interval.

### Expected result after these steps?

Position recording shoud work if switched on in settings.

### Reproducible

No

### c:geo Version

2024.01.07-NB1-9bd14f4

### Additional Information

Just for info, issue can be closed.

**Comment by Lineflyer** [comment]
Sounds like a missing / non-working feature on unified map?!
As I am not using the position history I did not notice.
