### ISSUE TITLE
Calculated waypoints: Unsaved changes?

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15191]
Found a small issue with regard to the new calculated waypoints feature:

If you open a predefined waypoint, and directly close it again, c:geo asks you if you want to discard unsaved changes, even though nothing has changed.

### How to reproduce
- open a cache with at least one predefined waypoint
- open that waypoint
- directly close it again by using the small arrow in the actionbar

### More info
Interestingly: Does not happen for user-defined waypoints.

**Comment by eddiemuc** [comment]
This is probably a bug of mine because I tampered with the "change detection" logic when implementing projection with variables.

* Did you observe this on master or release?
* If master: do you have "projection with variables" currently activated (via feature switch) or not?
* Just in case In have trouble reproducing: do you have an example cache / WP at hand?

**Comment by moving-bits** [comment]
Sorry, I should have been more specific: This has been on `master` with the new feature enabled. You can take any cache with predefined waypoints, AFAICS. I'm not at my dev machine at the moment, can look up a specific code later, if required.

**Comment by eddiemuc** [comment]
> I'm not at my dev machine at the moment, can look up a specific code later, if required.

Thanks a lot for info! Don't bother much looking up a code, I just asked if you have one at hand.

I will look into this, hopefully later today

**Comment by eddiemuc** [comment]
The bug is already fixed in PR #15177. If it is all right, I would like to wait with another PR until we decide whether this one is merged

**Comment by moving-bits** [comment]
Sure, and thanks for cross-checking. The PR is already on the agenda for our next dev call.
