### ISSUE TITLE
c:geo displays RAW photos to attach to images, even though it does not support them

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#15195]
### Describe your problem!

When attaching an image to a log, c:geo displays all images in a gallery view. In this view, also RAW files are displayed (and cannot be told apart from JPG photos, at least on Android 14).

However, when (possibly accidentally) trying to attach a RAW file, c:geo then displays an error message that the file is not supported.

### How to reproduce?

See above.

### Actual result after these steps?

See above.

### Expected result after these steps?

Either c:geo should support RAW files or filter them out in the gallery view.

I prefer the second solution (filtering them out), because for the purposes of c:geo RAW files offer no advantage (and Android phones always also make a JPG file; they never make only a RAW file).

### Reproducible

Yes

### c:geo Version

2024-01-06

**Comment by eddiemuc** [comment]
When we ask the android system to let the user select an image file we set the MIME type `image/*`. So it is no surprise that raw is also selectable.

To be more restrictive we would need to set a specific list of image mime types we support. Which list would that be?

**Comment by SammysHP** [comment]
`image/jpeg` should cover almost all cases. Maybe also add `image/png` and `image/gif` in case someone wants to add a screenshot.

**Comment by eddiemuc** [comment]
PR #15219 will restrict image selection to jpg, png and gif. I put the PR onto master because changing intent parameters sometimes lead to unexpected behaviour across android versions, and I would like to have this tested in beta first. I assume the error is not too critical so doesn't have to get to prod immediately
