### ISSUE TITLE
Support "subfolders" / sublists

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15194]
### Tell us your idea!

A user on support asks for support of subfolders (sublists), which they want to use for easier organization of their tours. Basically this is meant for a better visual representation, not for changes in filtering.

Example:
- List A
  - List A1
  - List A2
- List B
- List C

List A1/A2 would become visible when tapping on List A.
Filtering for List A would only list caches which are assigned to List A, not necessarily those being stored in List A1 and/or List A2 as well (except they are stored also in List A).

### What solution would you suggest?

- support a hierarchical relationship between lists
- list selection / list spinner: visual representation for a list having sublists could be a small "+" before or after the list name. Tapping on a "+" symbol would display the sub-lists (with some indentation) and "+" changes to a "-" symbol. Tapping on that "-" symbol would remove all sub-lists from display
- when filtering for caches of a certain list or when displaying a cache list for a certain list would ONLY include caches stored in chosen list, not those stored in any of its sublists (so no changes to filtering involved)
- we would need a clever way to manage the hierarchical relationship (indent / outdent; lists within same hierarchy level would still be sorted alphabetically)
- maybe more...

### Is there an alternative?

leave it as is, do not support sublists

### Additional Information

ticket 192556

**Comment by eddiemuc** [comment]
If this is something the team deems worthy, then I would propose to implement it like the following:
* introduce "list groups". A list group for now can consist just of a group name (later maybe one can add a group icon as well)
* let users assign a list to one (and only one) group. The same GUI flow should be used which is used to assign a marker to a list
* in list selection dialogs etc, use the "list group" (if available) to group lists by it

Implementing it this way would remove the ambiguity of not having lists of "children lists" into the result when filtering for "parent lists".  

If we choose this way, then for visualization purposes we can use the already existing group features of `SimpleDialog`/`SimpleItemListView`. "Downside" is that we would only support one hierarchy level - but I think this is sufficient.

**Comment by eddiemuc** [comment]
> Suggestion: Group icons. As the groups are auto-generated maybe use the first lists icon?

Do you mean list markers?

**Comment by ztNFny** [comment]
> > Suggestion: Group icons. As the groups are auto-generated maybe use the first lists icon?
> 
> Do you mean list markers?
> 
> 

Yes. I'm currently using list names to group them (leading digits) and list icons to easily identify them on map. As you can see from attached screenshot numbers and icons are usually the same, so showing the groups with icon (only.in the dialogs listing thr lists i mean) would be perfect match here.
![IMG_20240225_202731.jpg](https://github.com/cgeo/cgeo/assets/1258173/b1ed85ff-93e6-4e7e-85b9-d482ba09573f)

**Comment by eddiemuc** [comment]
I have no preference here, thus opening this up to discussion for the team

**Comment by moving-bits** [comment]
To have this consistent, one would need to check, if all elements of a group have the same list marker. (Use default marker, if not.) 
Would be nice indeed, but don't know how much work this would be,

**Comment by ztNFny** [comment]
Imho using the first of thr group would be perfectly fine, no need to check all are the same..

**Comment by eddiemuc** [comment]
> To have this consistent, one would need to check, if all elements of a group have the same list marker. (Use default marker, if not.) 
> Would be nice indeed, but don't know how much work this would be,

I am a bit confused. A list marker is assigned to a stored list. A stored list can have exactly one (or no) marker assigned to it. And we are grouping stored lists here. So it is no problem at all to group by it w/o any complex logic. Where is my thinking error?

**Comment by ztNFny** [comment]
> I am a bit confused. A list marker is assigned to a stored list. A stored list can have exactly one (or no) marker assigned to it. And we are grouping stored lists here. So it is no problem at all to group by it w/o any complex logic. Where is my thinking error?

My interpretation: @moving-bits suggests to show the group icon only if all lists in the group have the same icon.
My suggestion is actually simpler: Use the icon of the first (alphabetically) list in the group as group icon.

Example usecase for my suggestion: A group "statistics" which has several lists, e.g. "Statistics: 81 Matrix", "Statistics: missing found dates", "Statistics: For Challenges", ... The group would use the "graph" icon (picked from the first list), then the found-dates list could use a seperate calendar icon, challenge-list another one and so on.

**Comment by moving-bits** [comment]
> I am a bit confused. A list marker is assigned to a stored list. A stored list can have exactly one (or no) marker assigned to it. And we are grouping stored lists here. So it is no problem at all to group by it w/o any complex logic. Where is my thinking error?

What I meant: We are grouping lists. Each list can have its own list marker (which may differ from list to list in this group). If we display a list marker for the whole group: Which one should we use?

(But maybe my thinking just hit an edge case. If displaying an icon for a group gets implemented, let's start with whatever is easier to implement - probably taking the icon of the first element - and see how it works out in daily usage. Could still be refined later, if need be.)

**Comment by eddiemuc** [comment]
Left to do:
- place special list types below groups
- intend stored list entries belonging to a group
- assign a marker to group headers. suggestion: use marker of first stored list in group
- make drop-down in stored list selection also use the grouped list selection dialog

**Comment by ztNFny** [comment]
> intend stored list entries belonging to a group

Maybe that could also include not repeating the part of the title already contained in the group? Not sure, just a thought...

**Comment by eddiemuc** [comment]
PR #15413 aims to handle all open points except for this one:

- make drop-down in stored list selection also use the grouped list selection dialog

**Comment by eddiemuc** [comment]
PR #15416 adresses the remaining point (make drop-down in stored list selection also use the grouped list selection dialog) for both stored lists and unified map

**Comment by moving-bits** [comment]
Proposal: Can we un-indent the group heading and put the dropdown-indicator behind the heading?

|currently|proposed|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/81ea4d54-8e6f-46a3-8981-5bf6e16e9bf4)|![image](https://github.com/cgeo/cgeo/assets/3754370/04559cd1-3611-4b2f-b441-b338ce45441d)|

Advantages (IMHO):
- distinction between heading and content is much clearer
- meaning of "(11)" vs. "[11]" is clearer
- behavior is more similar to actual dropdown

**Comment by ztNFny** [comment]
>Proposal: Can we un-indent the group heading and put the dropdown-indicator behind the heading?
 
I vote against that proposal. Reason: Collapse/Expand indicator on the left is the standard UI for groups/folders for every OS since forever. 
![image](https://github.com/cgeo/cgeo/assets/1258173/2c1d8019-7d92-47fc-88a8-68a0c6f84c33)
![image](https://github.com/cgeo/cgeo/assets/1258173/74c2cabf-26ae-4093-8637-773115879fc4)

But if the left-placement isn't liked it could be aligned with material design expand-lists and the marker moved all the way to the right:
https://m3.material.io/components/lists/guidelines#f6fe9c4e-7498-420a-b820-d12a2b59fc99
![image](https://github.com/cgeo/cgeo/assets/1258173/7394794f-3b2f-4681-81ff-32ec2dadc3b0)


> behavior is more similar to actual dropdown

it's not a dropdown though, it's a group

**Comment by moving-bits** [comment]
> Collapse/Expand indicator on the left is the standard UI for groups/folders for every OS since forever. 

ok, understood

I'm not against left-placement, but I still think that the elements of a group should be indented compared to their heading, and that a group heading should have the same indentation as other elements on that level.

Maybe something like this?

|group closed|group opened|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/56183f0f-6228-4f54-9509-164414012930)|![image](https://github.com/cgeo/cgeo/assets/3754370/67868f46-ccb9-434a-bd43-08fa5d7c837b)|

(Maybe the non-groups then need some indicator as well? How do other programs handle this?)

**Comment by ztNFny** [comment]
T:en I'd rather go for the material design versin:
![image](https://github.com/cgeo/cgeo/assets/1258173/cc0ff7d4-cda6-4ebd-b566-4ffe15c194c9)

**Comment by eddiemuc** [comment]
Never thought this topic will become so big :-)

**Comment by ztNFny** [comment]
@eddiemuc how hard would it be to remember the expanded/collapsed state? 😇

**Comment by eddiemuc** [comment]
> @eddiemuc how hard would it be to remember the expanded/collapsed state? 😇

I was actually awaiting this requirement for a while now :-)

**Comment by eddiemuc** [comment]
> @eddiemuc how hard would it be to remember the expanded/collapsed state? 😇

PR #15427
