### ISSUE TITLE
Next feature release

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#15200]
Today we decided that we want to release a new beta rather soon. As unified maps is not yet ready, it should be disabled by default, with the possibility to turn it on as an experimental feature. 

Let's use this thread to collect any issues that need to be done before the final release. Feel free to edit this initial post for adding such issues:
- cache/waypoint bottom sheet:
  - [x] https://github.com/cgeo/cgeo/issues/15120 / https://github.com/cgeo/cgeo/pull/15198
  - [x] https://github.com/cgeo/cgeo/pull/15199
  - [ ] https://github.com/cgeo/cgeo/issues/15121
- other items:
  - [x] https://github.com/cgeo/cgeo/issues/15173
  - [x] https://github.com/cgeo/cgeo/issues/15109
  - [x] #15210
- UnifiedMap (non-blocking, as UnifiedMap in current state will be disabled by default)
  - [x] #15100 / #15108
  - [x] #15205
  - [x] #15203
  - [ ] #15260
- Issues noticed during beta
  - [x] #15236
  - [x] #15239
  - [x] #15464

**Comment by moving-bits** [comment]
AFAICS all blocking items are fixed, thus: If no one objects, I will create a beta version tonight.

**Comment by fm-sys** [comment]
+1 for the beta.

Side note: Can you please install the resulting beta APK on a fresh emulator or testing device to verify that unified map is **not** enabled by default before uploading it to Google play?

**Comment by moving-bits** [comment]
yes, have that on my mind. I have a new physical test device which has the current release installed, will test on that device.

**Comment by Lineflyer** [comment]
Crowdin integration has been enabled again:

- Crowdin reported the access token being invalid (which was not the case as the same token was working for other branches on Crowdin)
- Anyway I created a new personal access token from user `cgeo-ci-bot` stored it at Crowdin and reenabled the Github integration. 
- Sync has started now and in theory it should work as before as we store all configuration in `crowdin.yml` on our branches
- Lets wait and see

**Comment by moving-bits** [comment]
@Lineflyer has fixed the CrowdIn issue with `master` (thanks!). I'll wait for the sync, then start working on beta version:

- [ ] Empty `changelog_bugfix.md` on branch `master`
- [ ] Wait for a Crowdin cycle or trigger sync manually for branch `master`
- [ ] Merge the related Crowdin translation pull requests for branch `master`
- [ ] Delete outdated translations branch for `release`
- [ ] Fast forward `release` branch to HEAD of `master`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
Phew, made some temporary mess by not pushing the updated `release` branch (which I realized only after doing online updates to `release`, which lead to conflicts...), but now everything should be fixed, and beta release is rolling...

**Comment by moving-bits** [comment]
I propose to publish an updated beta version soon, as we have quite some bug fixes new on `release`. One thing should be fixed before releasing, though, which is #15247. So if anyone could give this a try?

**Comment by moving-bits** [comment]
As discussed in yesterday's dev meeting, I'll start preparing a new beta now:

- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
We have two candidates for significant bug fixes ("info sheet removal crash" and "black boxes on UnifiedMap") (among other fixes), thus I propose to publish a new beta rather soon to get a broader feedback base for those fixes.

**Comment by moving-bits** [comment]
Starting to create a new beta version now...

- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by Lineflyer** [comment]
Just my few cents regarding current nightly performance:
I think the unified map as well as the bunch of newly introduced features work quite well.

No objection from my side for making unified map the default and for a new feature release in general (given that beta shows good performance).

**Comment by moving-bits** [comment]
I'm glad that the haunting "black boxes & blinking labels" error seems to be fixed, keep fingers crossed! But we still have some quirks in UnifiedMap, thus we discussed the following release plan in our last dev meeting:
- publish a new release (not beta) next week (if nothing relevant occurs until then)
- publish UnifiedMap as beta, but not yet as default

This way we can get a broader user base for UnifiedMap, and can make it default in a few months time, if everything runs fine.

**Comment by Lineflyer** [comment]
> publish UnifiedMap as beta, but not yet as default

I don't quite understand. You probably mean a beta version where unified map is the default?!

**Comment by moving-bits** [comment]
No, the other way around ;-)
Publish a release, including UnifiedMap as beta version (but not as default). Users can enable it manually, eg by tapping on the link in the changelog.

**Comment by jakedot** [comment]
Will you also include the Wherigo functionality in the beta or will that remain on nightly?

**Comment by eddiemuc** [comment]
> Will you also include the Wherigo functionality in the beta or will that remain on nightly?
> 
> I mean of course that it would need to be enabled [as described in the wiki](https://github.com/cgeo/cgeo/wiki/Use-the-Draft-Wherigo-Player), not enabled by default.

Wherigo is very pre-alpha, I doubt that current state would be tolerated by beta users...

**Comment by moving-bits** [comment]
> Wherigo is very pre-alpha, I doubt that current state would be tolerated by beta users...

besides that: technically the Wherigo implementation (at least the last steps) is on `master` only and will NOT be part of the upcoming release

**Comment by Lineflyer** [comment]
> No, the other way around ;-) Publish a release, including UnifiedMap as beta version (but not as default). Users can enable it manually, eg by tapping on the link in the changelog.

But isn't unified map already on `release` branch and would therefore be included into the normal release as non-default anyway?

**Comment by moving-bits** [comment]
> > No, the other way around ;-) Publish a release, including UnifiedMap as beta version (but not as default). Users can enable it manually, eg by tapping on the link in the changelog.
> 
> But isn't unified map already on `release` branch and would therefore be included into the normal release as non-default anyway?

Yes, exactly. We just decided to leave it at that publishing state for the moment and not make it our default map yet.

**Comment by moving-bits** [comment]
As discussed in our last dev meeting, I'll start preparing a feature release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by Lineflyer** [comment]
Triggered notification system

**Comment by Lineflyer** [comment]
I promoted our new release and the unified map on Facebook:

A new feature release 2024.03.19 is available for you now. It contains quite some fixes and new features as listed here:
[https://github.com/cgeo/cgeo/releases/tag/market_20240319](https://github.com/cgeo/cgeo/releases/tag/market_20240319)
We are delighted to have reached the beta status with our new map implementation "Unified Map" with this release, which combines all map sources into a common environment with a bunch of new features along with it.
We encourage you to try it via Settings => Map Sources => Unified Map.
An introduction and technical background information can be found here:  [https://github.com/cgeo/cgeo/wiki/UnifiedMap](https://github.com/cgeo/cgeo/wiki/UnifiedMap)

Also posted on X a brief release info.
