### ISSUE TITLE
c:geo does not show, in which cache the TB is currently

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15207]
> By the way: Why doesn't c:geo show, in which cache the TB is currently?

Is this a feature which was available in the past (and is now gone)?

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/14642#issuecomment-1892752935_
           
Confirmed not working anymore (regression).

**Comment by eddiemuc** [comment]
Apparently gc.com changes their web page (replaced cache GUID with geocode), fixed with PR #15215
