### ISSUE TITLE
Back arrow deletes edit w/o confirmation

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15212]
### Describe your problem!

I used the new edit log function and wrote the complete log. I wanted to get a detail from the cache description and used the top left arrow.
That took me back to the log page but all the edits were gone

### How to reproduce?

Edit Log
Use back arrrow

### Actual result after these steps?

Edit discarded

### Expected result after these steps?

Warning should appear "discard edits"

### Reproducible

Yes

### c:geo Version

2024.01.12-NB-42e636e

**Comment by eddiemuc** [comment]
Good Point, this is missing indeee

**Comment by geocachermgo** [comment]
Look good with 2024.01.22-NB-b6c949b
