### ISSUE TITLE
[Nightly] Displayed filter names lost their star

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15236]
### Describe your problem!

Named filters used to have a star after they were altered - this star has somehow gone lost.
What has already led to some astonishment on several occasions, because the filter seemed to give incorrect results.

### How to reproduce?

1. create a filter
2. save this filter with a (hopefully mnemonic) name
3. open map or any list
4. select the saved/named filter
5. the filter name will be shown in the header row
6. alter the filter
7. have a look at the filter name's end ...

### Actual result after these steps?

8. the filter name display is unchanged,
   notice that there is no star at the end of it's name, which shows that the filter has been modified
   and does no longer match the saved one 

### Expected result after these steps?

8. as soon as any criteria of the filter changes, the star should be displayed

### Reproducible

Yes

### c:geo Version

2024.01.25-NB-48ffb91

**Comment by eddiemuc** [comment]
Confirmed, happens also in beta released last night.

**Comment by eddiemuc** [comment]
Fixed with PR #15249
