### ISSUE TITLE
Allow elevation to be shown in feet

### ISSUE THREAD

**Issue by chrispt** [cgeo/cgeo#15239]
### Tell us your idea!

Can we please be able to change the elevation units to feet instead of meters on the map screen?
![Screenshot_20240125_204813_cgeo](https://github.com/cgeo/cgeo/assets/1679097/b73d53de-a489-47ff-a1f5-f49ae9fceb41)

**Comment by fm-sys** [comment]
Implementation note: This should be coupled to `settings > appearance > use imperial units`

**Comment by moving-bits** [comment]
There is a formatter function for it, I'll look into it

**Comment by moving-bits** [comment]
implemented with linked issue
