### ISSUE TITLE
calulation: trunc does not trunc but floor

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15248]
### Describe your problem!

I expected that the tunc function does truncation https://en.wikipedia.org/wiki/Truncation.
But if I use it for negative values it does floor:
Trunc(-5.4) should be -5 but is given as -6

### How to reproduce?

Swipe to variable page
Add variable
Add trunc(-5.6) as formula

### Actual result after these steps?

Variable shows -6

### Expected result after these steps?

Variable shows -5

### Reproducible

Yes

### c:geo Version

2024.01.24-NB-029ec46

**Comment by eddiemuc** [comment]
Fixed with PR #15250
