### ISSUE TITLE
waypoint projection formula missing in personal note

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15243]
Reported by user on support:

_Die neue "Wegpunkt-Projektion mit Variablen" wird nicht komplett in die persönliche Notiz übernommen. Konkret: Die Formeln/Variablen etc. fehlen. Der Wegpunkt wir nur mit der berechneten Koordinate in die Notiz eingefügt (Beispiel: "@Peilung (W) N48 54.xxx E9 08.xxx")._

ticket 206088

**Comment by eddiemuc** [comment]
Confirmed, this is simply not implemented.
