### ISSUE TITLE
Move top menu bar to the right on landscape mode

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#15255]
### Tell us your idea!

Hi.

I use c:geo in landscape mode when I'm driving, and now with unified map, when I have the zoom set to 100m or less, there little map info on screen. And if I have filters selected, even less space for info.

### What solution would you suggest?

Can the top menu be moved to the right off the screen (bottom menu is already on the left)? And remove the line indicating the there are filters applied with a number next to the filters ícon?

### Is there an alternative?

Other solution, if there was a native "driving mode", is moving the Arrow more close to the bottom off the screen.

Or, just leave it as it is.

**Comment by Lineflyer** [comment]
There is a  it of help available:
Go to map content menu in settings and activate tap to hide toolbar.

Afterwards you can hide the toolbar by single tap on the map.

**Comment by rouroni1** [comment]
Hi.

Thanks for the tip.
That helps a lot.

**Comment by Lineflyer** [comment]
I guess (to be confirmed by other devs) there is no easy option to flip such menus to another side, that is the reason we introduced this full screen mode.

**Comment by fm-sys** [comment]
In theory everything is possible, but it would be quite much effort though. Not to forget that it's not an easy task to design it in a good way UI wise. Not only the action buttons would need to be moved but also the title and the list selection spinner which will be added in unified map. Furthermore, I wouldn't want to see this on tablets only on really small landscape screens (but on these devices probably not all action bar items would fit vertically as the zoom bars already fill half of the height). 

Thus I have to agree with @Lineflyer, we IMHO shouldn't purpose this feature request further.

**Comment by fm-sys** [comment]
BTW, I really like your idea to move the position indicator to the bottom of the screen if follow my position + map rotation is enabled. I will move that suggestion into a new issue.
