### ISSUE TITLE
Repeat last log does no longer work

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15254]
### Describe your problem!

It was reported on social media by beta users, that the feature to insert the last used log into a new composed log no longer works. No details though about what happens instead. Did not try to reproduce yet.

### How to reproduce?

- Compose log for a cache
- Send log
- Compose log for another cache
- Use Menu - Repeat last log

### Actual result after these steps?

(Probably) nothing

### Expected result after these steps?

The log text of the first log is pasted into the new log

### Reproducible

Unclear

### c:geo Version

2024.01.24-RC

**Comment by murggel** [comment]
Same here.
The last log is the one, which was stored offline.
If the log was sent directly it will not be available as last log.

**Comment by eddiemuc** [comment]
Fixed with PR #15256

**Comment by comtg11** [comment]
I am having the same problem!  It only uses the log that was saved offline.  It does not bring up the last log if it was sent without saving as an offline log.
