### ISSUE TITLE
CyclOSM no longer working?

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15258]
User on support asked for further support of CyclOSM map.

On a quick test it seems that the map tiles are not loaded anymore.

We need to investigate whether it's a temporary problem, the service is discontinued, something has changed in their configuration c:geo needs to adapt to, or what else happened.

Ticket 444866

**Comment by Lineflyer** [comment]
Working for me, cannot reproduce.

**Comment by moving-bits** [comment]
Now it's working for me again as well. 

I had cross-checked on two different devices, with UnifiedMap and NewMap, and got blank backgrounds.

Seems to have been a temporary problem, so let's close here.
