### ISSUE TITLE
opencaching.nl is down

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#15262]
### Describe your problem!

Since some days the site opencaching.nl is not more offline.
Therefore our watchdog test fails.

The whois reports:
Status:      in quarantine

@andrixnet @harrieklomp
Is this a big problem or only a minor problem?

Test: https://www.opencaching.nl/

**Comment by bekuno** [comment]
opencaching.nl is back :-)

**Comment by andrixnet** [comment]
Appologies for the delay. (health). 
OCNL has uptime 730 days at this time. So the server was not down at all. 

According to whois, there may have been a problem with the domain validity, which Harrie may have solved since then.
