### ISSUE TITLE
Opening a cache from link in trackable logbook does not work

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15264]
### Describe your problem!

Reported on support mail for our beta version 2024.01.24-RC and reproducible for me on `master`:
Once the user taps on a geocache name shown in the logbook of a trackable it leads to a "cache not found" toast

### How to reproduce?

- Open GC7540G (or directly open any trackable you know and continue from there (skip next two steps then)
- Swipe to trackable tab
- Open any trackable (which has some logs with reference to caches)
- Tap on a geocache name

### Actual result after these steps?

Toast "The requested cache could not be found"

### Expected result after these steps?

Cache details should be loaded/opened

### Reproducible

Yes

### c:geo Version

2024.01.24-RC

**Comment by moving-bits** [comment]
This is actually a bug on their website:

Every cache in the logbook links to https://www.geocaching.com/geocache/GC0 (which links to a cache named "GC0", which is non-existent).

(I've dropped them a note.)

**Comment by moving-bits** [comment]
they have fixed that bug meanwhile, so let's close here

**Comment by Lineflyer** [comment]
Really...tried yesterday and just now and still had the same issue.

**Comment by moving-bits** [comment]
...okay... 
GC had reported back as "fixed" a few weeks ago upon request from us, and I haven't got any report on this on support since weeks.

But:

Just checked the website with one of my TB => links seem to be fine now
Cross-checked with today's nightly in c:geo => error message 😠 

So it may be a different cause now, need to investigate. (But strange that we did not hear anything about it on support yet.)

**Comment by moving-bits** [comment]
from a short debug session:
seems that in `TrackableLogsViewCreator.fillCountOrLocation()` we do have a gc code in the guid field, and a blank gccode field, which leads to c:geo trying to open a cache by guid, but with a gc code as guid.

@eddiemuc 
IIRC you have adapted c:geo to the trackable website changes a few months ago, can you have a look at it?

**Comment by eddiemuc** [comment]
I'll look into it as time permits

**Comment by eddiemuc** [comment]
Fixed with PR #15475
