### ISSUE TITLE
Suport scrollbar in list selection dialog

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15276]
User request on support:

This user has > 100 lists defined. When using list selection, only a couple of them are shown (depending on screen size). The user knows, that he can swipe in this list.

Still, the user is missing the scrollbar, as it would be an indicator for him where in this list of list name he is - eg. "first third", "middle" etc.

Thus the user is requesting to add a visible scrollbar to the list selection dialog.
(This might also be a good visual indicator for other users that do not know they can swipe in such a long list.)

ticket 575947

**Comment by eddiemuc** [comment]
A fix is provided in PR #15286 
By default, scrollbar is only shown for a short period of time, then it fades away. I overwrited this behaviour to show scrollbar permanently. 
Scrollbar is not shown when list of items can be displayed completely in dialog

![image](https://github.com/cgeo/cgeo/assets/6909759/faad2197-fc88-4af6-a973-2d5e59c02816)
