### ISSUE TITLE
Doubled waypoint is created from calculated projected waypoint in personal note 

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#15284]
### Describe your problem!

When exporting a waypoint with calculated projected waypoint to personal note, a second waypoint with base of the calculated waypoint is created.

### How to reproduce?

Create a waypoint with calculated projection (distance) and export to personal note
{c:geo-start}
@Finale (F) N47 08.200 E11 52.278
@Figur (W) N47 08.180 E11 52.225
@Peilung (W) N47 08.181 E11 52.229{P|BEARING|4*X+2|63,1|METER}
$X=1
{c:geo-end}

![Screenshot_20240203-231555_cgeo](https://github.com/cgeo/cgeo/assets/70113341/1887d74f-ea39-4035-a2eb-bbefb3539ce1)

### Actual result after these steps?

A second waypoint with the result- coordinates as base is created 
![Screenshot_20240203-231821_cgeo](https://github.com/cgeo/cgeo/assets/70113341/97a78767-98a4-4773-90df-69b2619ef022)

### Expected result after these steps?

No second waypoint will be created 

### Reproducible

Yes

### c:geo Version

2024.02.02-NB-150aed4

**Comment by eddiemuc** [comment]
Fixed with #15285
