### ISSUE TITLE
Downloaded offline maps cannot be selected as a map source.

### ISSUE THREAD

**Issue by ChrisWun** [cgeo/cgeo#15295]
### Describe your problem!

I have downloaded several offline maps and these are in the file system of my Android smartphone. It used to be possible to select these offline maps as the map source. This is no longer possible since an update.

### How to reproduce?

1. Download Offline Map
2. Select / Verify Offline Map Folder
3. Try to select map source -> downloaded maps are missing
![WhatsApp Image 2024-02-04 at 18 35 36 (1)](https://github.com/cgeo/cgeo/assets/7915105/192bf202-2ee9-411d-b0ce-9c05555e7542)
![WhatsApp Image 2024-02-04 at 18 35 36](https://github.com/cgeo/cgeo/assets/7915105/a3caaafb-c170-4e9c-bcb4-80990d5e985f)
![WhatsApp Image 2024-02-04 at 18 34 56](https://github.com/cgeo/cgeo/assets/7915105/ffbb4135-d737-4e99-b098-21d69477ae37)

### Expected result after these steps?

The downloaded offline maps are offered as a map source.

### Reproducible

Yes

### c:geo Version

2024.06.01

**Comment by moving-bits** [comment]
normally downloaded maps should be added automatically to the map chooser, if everything works as expected. But sometimes Android storage framework has some "hiccups".

You can try re-granting c:geo access to your configured map folder. (See second screenshot, select "Order auswählen", then select the correct map folder and confirm "allow c:geo to access this folder and all files in it" (or similar confirmation message).

**Comment by bekuno** [comment]
Other idea.
The folder size and the size of the files does not map. Maybe the map download was unfinished and the maps are therefore unreadable.

**Comment by ChrisWun** [comment]
Thank you very much for your answers!

Unfortunately, I was unable to solve the problem by setting the read permissions again. A problem with the read authorisation also seems unlikely to me, as the files could be downloaded by the app and saved in the folder. I think this would not be possible if the read authorisation is missing.

I also uninstalled the app and deleted the entire folder for the app. I then set up the app again and downloaded the offline maps. Unfortunately also without success.

The exact size of the files does not seem to fit 100%, but the specified number of folders and files fits. When selecting the folder, I can see that the files for the offline maps are located there. 

How can I check whether the files have been downloaded completely? It looks like this to me.

If the folder has been selected, some time later it will be displayed at the bottom of the snack bar that the ".txt" files could not be parsed. Could this possibly be related to this problem?

**Comment by ChrisWun** [comment]
After trying several times, I was able to solve the problem. It was actually an authorisation problem for data access.

Thank you very much for your answers! I am closing this issue.

**Comment by moving-bits** [comment]
Good news, thanks for your feedback.

Did you resolve this by re-granting c:geo access to your map folder, or was it some different action?
(I'm asking because we get similar reports from time to time, and we could improve our FAQ accordingly, if there's some general solution.)
