### ISSUE TITLE
Sending an online log additionally produces an empty offline log

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15298]
Reported on support for latest nightlies and reproducible by me:

If you send an online log from within c:geo (tested with either "found" and "write note" types), c:geo will not only send this log and add it to the local logbook, but additionally create an empty offline log.

Reproducible with today's master.

**Comment by alan666notb** [comment]
I've seen this as well, I was just about to report it.
I'm on the latest Beta 2024.01.24-RC

**Comment by eddiemuc** [comment]
Fixed with PR #15305
