### ISSUE TITLE
Bottom/side sheet is missing top bar menu in landscape

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15309]
Quick note from out in the woods:

- Using current nightly
- tablet device Android 13
- Landscape map view
-  Tapping a cache opens the info sheet (former popup) but its missing its top menu bar (e.g. to enable the direction line and further cache related functions)

Sorry if this is a duplicate, search returned nothing obviously matching issue

**Comment by moving-bits** [comment]
it's actually hidden behind the map's toolbar, so as a quick workaround you can activate "settings" => "map content & behavior" => "hide toolbar on tap"

**Comment by fm-sys** [comment]
it's actually the other way around, if you disable that settings you won't have this problems anymore ;-)

**Comment by moving-bits** [comment]
depending on what your preferred default is :-)

**Comment by Lineflyer** [comment]
Friendly reminder for that issue. Just out and about with my larger device, which I typically use in landscape  and stumbled again over this problem.
Used the workaround for now....but I doubt users will recognize the reason for the issue by themselves and find the workaround.

**Comment by moving-bits** [comment]
If we tackle this, we should then distinguish by screen dimensions - on a typical phone, forcing the info sheet's title bar to be displayed below the map's title bar would leave close to no space for actual content, whereas on a typical tablet there should be enough space for both. 

Or we simply align the info sheet to the bottom (instead of the top).

**Comment by moving-bits** [comment]
@Lineflyer 
I have created PR #15721 for this - can you test it on your tablet (should display info sheet's toolbar) as well as on a phone (should NOT display the info sheet's toolbar)?

**Comment by moving-bits** [comment]
@Lineflyer 
Can you cross-check here (as time permits)?

**Comment by murggel** [comment]
Works for me

Tablet landscape mode

![Screenshot_20240721_223641_cgeo.jpg](https://github.com/user-attachments/assets/47895291-4ede-4298-aa5b-9b03cfeb8d2f)


But also visible on my phone, but there I have to scroll more.
But otherwise it would hide more of the map....

**Comment by moving-bits** [comment]
thanks for testing, then let's close here
