### ISSUE TITLE
Upload content of variable page to personal cache notes

### ISSUE THREAD

**Issue by SchoolGuy** [cgeo/cgeo#15306]
### Tell us your idea!

As a user  
I would like to copy the variables page to personal cache notes  
so that I can save the calculation even after the cache is gone from c:geo locally.

### What solution would you suggest?

Copying the content into the cache note seems appropriate.

### Is there an alternative?

A dedicated c:geo provided service would also be cool but I think the simple solution is much more appropriate for most folks.

### Additional Information

Reported by my non-programmer dad. :)

**Comment by ztNFny** [comment]
This already exists: On [Description](https://manual.cgeo.org/en/cachedetails#description_tab) scroll to the Personal note, then use the button at the bottom left.

**Comment by eddiemuc** [comment]
Example: assue following var tab:
![image](https://github.com/cgeo/cgeo/assets/6909759/c2f0d10d-1453-490a-924e-8f75f6ea14f2)

Go to  Description, find and tap following button on left side below personal notes:
![image](https://github.com/cgeo/cgeo/assets/6909759/c53a7939-8067-4455-ac38-bca545349637)

Then you will find your variables (and waypoints, if you have any) in the personal notes like this:
![image](https://github.com/cgeo/cgeo/assets/6909759/c2db787d-ca37-43a5-a157-07829162f16a)
