### ISSUE TITLE
GC Website change: Deleting log of another user requires to give reason

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15307]
I noticed today that deleting a log of another user fails in c:geo. Reason is that gc.com website requires to give a reason text in this case.

![image](https://github.com/cgeo/cgeo/assets/6909759/c2f5d309-3b7e-4f63-ac41-1a59f8eac603)

Additionally I noticed that c:geo does not display a message when deleting a log failed

**Comment by eddiemuc** [comment]
Fixed with PR #15308

**Comment by bekuno** [comment]
Looks good:
![grafik](https://github.com/cgeo/cgeo/assets/32555742/6327b561-3352-4e41-a419-cd85058cac43)
