### ISSUE TITLE
show images linked in "personal note" in Images tab

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15300]
### Tell us your idea!

c:geo currently downloads and shows images that are included in listing, attached to listing and attached to logs in images tab.

Often a check contains a spoiler image and I copy the checker text, including image url, to personal note. I'd like those note-images to be treated like other images as well (auto-download, show in images).

### What solution would you suggest?

If personal note contains a link to an image (how to recognize those reliably? Not sure how this is done for listing. Maybe at least urls ending in .png, .jp(e)(g)?) download and show that image in images tab.

**Comment by eddiemuc** [comment]
> how to recognize those reliably? Not sure how this is done for listing. 

Listings are HTML, we scan for img tags

**Comment by alan666notb** [comment]
Hi there,  I posted #15071 a while ago that raised a problem with links in the personal note.
Will this affect how links to images are recognized?
