### ISSUE TITLE
Long Click point, chrash, no routing shown (unified map)

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15318]
### Describe your problem!

If I log click on a point on the map, 
If I chose "Als Ziel festlegen" the app chrashes.
If I chose Navigate, Compass and at the compass page click on map the routing is not activated.

### How to reproduce?

I log click on a point on the map, chose Navigate, Compass and at the compass click on map

### Expected result after these steps?

No chrash
Route and distance shown

### Reproducible

Yes

### c:geo Version

2024.02.11-NB-33a1cac

**Comment by moving-bits** [comment]
good catch, thanks for reporting it. PR #15319 fixes this issue.
