### ISSUE TITLE
Track layer displayed on top of cache layer with OSM map source

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15334]
On OSM maps (both online / offline) the track layer is displayed on top of the cache icon while with Google Maps and the old map implementations it's drawn between map and cache icon layers.

OSM:
![image](https://github.com/cgeo/cgeo/assets/1258173/6ab38ff7-8546-4002-9552-6d1854aefea7)
Google Maps
![image](https://github.com/cgeo/cgeo/assets/1258173/29720366-8400-4171-b0c1-c5cb4200ec71)

Version: Todays master

**Comment by moving-bits** [comment]
Is this UnifiedMap or "old" maps?

UnifiedMap should use the identical constants for z-index.

**Comment by ztNFny** [comment]
Another similar inconsistency exists with the text of maps vs tracks. On Google Maps the text seems to be on a seperate layer on top of tracks (geojson in this case), OSM has the text behind the tracks. Not sure whether OSM has text available as a seperate layer though.

OSM:
![image](https://github.com/cgeo/cgeo/assets/1258173/f2fcbb74-0b38-48e7-bbc1-907a00edad55)
Google Maps:
![image](https://github.com/cgeo/cgeo/assets/1258173/e8125d52-20ab-404c-9434-8cceef48a29c)

**Comment by ztNFny** [comment]
> Is this UnifiedMap or "old" maps?
> 
> UnifiedMap should use the identical constants for z-index.

Unified. All good on old maps.

**Comment by moving-bits** [comment]
> Not sure whether OSM has text available as a seperate layer though.

VTM has a separate "Label layer", but I guess that will hit *all* labels - which we probably would not want to have as top layer. Not sure if some sort of differentiation is possible with VTM.

**Comment by moving-bits** [comment]
> > Is this UnifiedMap or "old" maps?
> > UnifiedMap should use the identical constants for z-index.
> 
> Unified. All good on old maps.

Ok, then we will have to look up in the UnifiedMap-related files, if those defined constants are used in all places, or if there's something hard-coded or referencing a "wrong" constant.

**Comment by ztNFny** [comment]
PR #15337 adresses the original issue by reordering multiple layers. Map labels (https://github.com/cgeo/cgeo/issues/15334#issuecomment-1945870868) are not addressed
