### ISSUE TITLE
Unified Map: c:geos lines (history, navigation) widths are different OSM vs Google vs old map

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15343]
- c:geos lines (history, navigation) widths are different OSM vs Google vs old map
-- OSM unified: 74
-- Google unified: 62
-- OSM old: 42
-- Google old: 42
(To test this I recommend setting the line width to a very large value in Appearance Settings as any factor applied will become more apparent then)

_Originally posted by @ztNFny in https://github.com/cgeo/cgeo/issues/15335#issuecomment-1947961374_

**Comment by eddiemuc** [comment]
I wouldn't suggest not to bother too much with line widths in old maps any more. But of course line widths should be consistent across Google + OSM in Unified map.

First question I have: user can set line width for various displayed map stuff in c:geo settings to a value between 0 and 100 (see following screenshots). What unit is this value supposed to be? Pixels? Densitiy-independent Pixels? fraction-of-millimeters? Soimething else?
![image](https://github.com/cgeo/cgeo/assets/6909759/bd99aadf-348b-497d-9b17-c194c15d5553)
![image](https://github.com/cgeo/cgeo/assets/6909759/7351265a-6e48-4c34-9d5e-fa324bb6cec7)

**Comment by ztNFny** [comment]
No idea really what the width-unit is supposed to be, maybe just some arbitrary factor?
Whatever it is, we shouldn't change its meaning. So the line width should be adjusted in Unified maps to match the old (in my values given above it should be 42 as well)

**Comment by ztNFny** [comment]
To make the line-width the same in old vs unified Google Maps in MapLineUtils.getWidthFromRaw() the unifiedMap factor needs to be adjusted from 1.5f  to 2.0f. This was last modified by https://github.com/cgeo/cgeo/issues/15003#issuecomment-1866931189 and if I read it right to a value that's "more or less the same" without actually measuring it.

OSM is still too wide after this change. OSM could be "fixed" by setting rawStrikeWidth = .. / 2.0f in MapsforgeVtmGeoItemLayer.add(), but that'd screw up the polygons just fixed by #15335 again

Comparing MapsforgeVtmGeoItemLayer vs GoogleV2GeoItemLayer OSM uses 1 style for all object types whereas Google Maps uses different styles for Circle and Polygon vs Polyline (doing an additional ViewUtils.dpToPixel()). So I'd say that my original "dirty hack" from #15335 is actually the correct way to adjust OSM to the different implementations of GoogleV2.

I've got the fix ready to go, but need #15335 to be merged first before I can do a PR as it creates conflicts otherwise.

**Comment by moving-bits** [comment]
WRT to some of the map lines, there is another dirty hack in `MapLineUtils` implemented back when we started with UnifiedMap, see flag "unifiedMap" - maybe they are conflicting?

**Comment by ztNFny** [comment]
> WRT to some of the map lines, there is another dirty hack in `MapLineUtils` implemented back when we started with UnifiedMap, see flag "unifiedMap" - maybe they are conflicting?

I already adjusted that one in my fix, that's 1 part of 2.

**Comment by ztNFny** [comment]
![image](https://github.com/cgeo/cgeo/assets/1258173/1c03d988-4050-4042-b5fa-d30636a4d25c)
![image](https://github.com/cgeo/cgeo/assets/1258173/4e4bd605-a7f1-4a8e-a0d4-60d0e3fe7701)

**Comment by eddiemuc** [comment]
> Comparing MapsforgeVtmGeoItemLayer vs GoogleV2GeoItemLayer OSM uses 1 style for all object types whereas Google Maps uses different styles for Circle and Polygon vs Polyline (doing an additional ViewUtils.dpToPixel())

More likely this is a bug of mine in Google geo item layer. Should be same width style for all objects. Can't tell more from my mobile

**Comment by ztNFny** [comment]
> > Comparing MapsforgeVtmGeoItemLayer vs GoogleV2GeoItemLayer OSM uses 1 style for all object types whereas Google Maps uses different styles for Circle and Polygon vs Polyline (doing an additional ViewUtils.dpToPixel())
> 
> More likely this is a bug of mine in Google geo item layer. Should be same width style for all objects. Can't tell more from my mobile

well, it uses .width(ViewUtils.dpToPixel(GeoStyle.getStrokeWidth(item.getStyle()))) in https://github.com/cgeo/cgeo/blob/c3e94f32aaf61560c0debbde4e90f5db6de2f933/main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java#L119

So we either apply a factor of 4/3 there or the 3/4 factor in OSM. Either way it's an "random" factor being applied.

**Comment by eddiemuc** [comment]
> well, it uses .width(ViewUtils.dpToPixel(GeoStyle.getStrokeWidth(item.getStyle()))) in https://github.com/cgeo/cgeo/blob/c3e94f32aaf61560c0debbde4e90f5db6de2f933/main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/GoogleV2GeoItemLayer.java#L119

Seems that the variable strokeWidth (which is used at the other objects) is calculated the same way, just uses float instead of int. Probably a type issue with the Google objects, or float value should be applied to polyline as well. But same calculation is applied (except maybe for rounding differences). I am relieved :-)

**Comment by ztNFny** [comment]
The parameter actually supports float :-o I'll adjust that to use the same variables as the other classes.
I guess the difference really is in Googles implementation of width for PolylineOptions then.

Question is: Do we want to adjust Google or OSM?

**Comment by ztNFny** [comment]
> The parameter actually supports float :-o I'll adjust that to use the same variables as the other classes.
> I guess the difference really is in Googles implementation of width for PolylineOptions then.
> 
> Question is: Do we want to adjust Google or OSM?

I'll adjust Google - otherwise on OSM a 1 wide line would be different than a1 wide polygon

**Comment by eddiemuc** [comment]
> Question is: Do we want to adjust Google or OSM?

My preference would be that both/all map layer implementations interpret all width values as dp. That's even stricter than "just" having all maps apply same width for same value. I even named many variables like this IIRC (e.g. widthInDp and such)

**Comment by ztNFny** [comment]
I've now pushed the fix to https://github.com/cgeo/cgeo/pull/15335

With this all dimensions across old and new google/osm are equal.
