### ISSUE TITLE
[Nighlty] UM - Circle fill color different from classic one

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15353]
### Describe your problem!

Two things to mention:
- (my) setting from classic map (opaqueness 7 %) is completely invisible in UM
- slider of opaqueness can be set from 0 to 100 %, but when I enter a value manually, values go from 0 to 255
  ... should most probably be a separate issue, shouldn't it? ;)

### How to reproduce?

.

### Reproducible

Yes

### c:geo Version

2024.02.19-NB-e03e666

**Comment by ztNFny** [comment]
Should be fixed by #15335

**Comment by moving-bits** [comment]
> * slider of opaqueness can be set from 0 to 100 %, but when I enter a value manually, values go from 0 to 255
>   ... should most probably be a separate issue, shouldn't it? ;)

I'll create one - slider is using 0..255 internally (as is Android for alpha value) and it should either display that range, or should use a percentage value consistently

**Comment by MagpieFourtyTwo** [comment]
> Should be fixed by #15335

Yep. Thx!
