### ISSUE TITLE
waypoint "visited" flag is not updated on map

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15352]
### Describe your problem!

waypoint "visited" flag is not updated on map

### How to reproduce?

Open cache with waypoint on map
Click on waypoint
  Waypoint opens in lower half of the window
Toggle "visited" checkbox
click on map to close waypoint window

### Actual result after these steps?

Status (green hook) is not changed

### Expected result after these steps?

Status (green hook) is changed

### Reproducible

Yes

### c:geo Version

2024.02.18-NB-f05cfbb

**Comment by moving-bits** [comment]
is this for the new "UnifiedMap", or also happening on the "old" map types?

If this is "UnifiedMap" only, then it's likely a combination of #15349 and #15348.

**Comment by geocachermgo** [comment]
UnifiedMap only

**Comment by moving-bits** [comment]
ok, thanks. I'll cross-check when working on #15348

**Comment by moving-bits** [comment]
why did auto-close not work, although GitHub states "linked a pull request ... that will close this issue", and marks the linked PR als "merged"?

Closing manually now.

**Comment by fm-sys** [comment]
> why did auto-close not work, although GitHub states "linked a pull request ... that will close this issue", and marks the linked PR als "merged"?
> 
> Closing manually now.

Autoclosing does only work when merging to `master`. As only the commit gets merged back to `master`, not the PR itself, the "fix #xxx" needs to be contained in the commit message when creating a PR towards `release`.

**Comment by moving-bits** [comment]
Thanks, I'll try to remember that and not let me be confused by the GitHub message :-)

**Comment by eddiemuc** [comment]
> > why did auto-close not work, although GitHub states "linked a pull request ... that will close this issue", and marks the linked PR als "merged"?
> > Closing manually now.
> 
> Autoclosing does only work when merging to `master`. As only the commit gets merged back to `master`, not the PR itself, the "fix #xxx" needs to be contained in the commit message when creating a PR towards `release`.

IMHO it is good practice to include reference to fixed issue in commit message anyway (regardless of whether one merges to master or release)
