### ISSUE TITLE
Make updating caches resumable

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15378]
Feature request by a user on support:

The user is using quite large GPX files (> 1500 caches / > 120 MB) and imports those into c:geo. After a successful import the user triggers an update for all imported caches to get most recent data + log pictures etc.

### Observed problem:
If the download gets interrupted for any reason, the user has to restart "from scratch", re-downloading all caches, which not only takes quite some time, but also uses a huge part of the data plan (if using a metered connection).

### Feature request:
Make the download resumable (so remember, which caches have already been downloaded successfully, and offer an option to re-trigger the download for the rest).

### Side-question: 
What happens if we trigger a "store all" call to download caches from map in the background, and this download has a problem - won't Android's download manager download the rest automatically? 
- If so, this could be a solution to this feature request - put updating a cache list into the background, using the download manager.
- If not, then a similar functionality should be added to the "store all" function as well.

### Additional info:
ticket 868946

**Comment by jakedot** [comment]
You can set a filter on "updated by" on the list you are importing to and only update those that haven't been downloaded in a user definable interval.

**Comment by jakedot** [comment]
@moving-bits does my workaround satisfy your requirements?

**Comment by moving-bits** [comment]
> @moving-bits does my workaround satisfy your requirements?

I guess it's a valid workaround, so setting "Prio: Low" label, but the feature request is still valid, IMHO, as it's more straightforward.

**Comment by moving-bits** [comment]
closing as duplicate of #13415
