### ISSUE TITLE
Unified Map: Viewing CachePopup loads caches waypoints onto map

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15404]
I have map set to not show any waypoints (threshold 0 in settings).
View a list -> only caches are shown.
Tap a cache (with WPs, e.g. parking) so that CachePopup opens.
-> the caches WPs appear on the list map

https://github.com/cgeo/cgeo/assets/1258173/e2492167-f945-43eb-962f-8264b03e9559

Build 2024.03.01

**Comment by moving-bits** [comment]
very likely a follow-up of #15369, I'll look into it
