### ISSUE TITLE
FR: filter criteria for GCCode

### ISSUE THREAD

**Issue by HankChow** [cgeo/cgeo#15403]
### Tell us your idea!

If I want to filter some newer caches, I have to use "hidden date" for filter criteria. But I can't get this field until I've read our downloaded the cache. 
GCCode does not need to download the cache content. So it can be a filter criteria about cache's age approximately. 

### What solution would you suggest?

GCCodes are actually base-36 values start with "GC", so they can be compared. So they can be filtered with "former", "latter", or "between".
For example, "former then GCAK000", "latter than GCAGY6J", "between GCACD98 and GCAF2H7".

**Comment by ztNFny** [comment]
What do you mean with "But I can't get this field until I've read our downloaded the cache."?
Cgeos filters work online as well (if the conmector supports them, which is the case for the hidden date). Basically cgeo will perform a search on gc.com with search criteria hidden>some date, so there's no need to download the cache to be able to apply the filter.

If that doesn't match your usecase could you please describe your scenario a bit more detailed?
