### ISSUE TITLE
FR: Add menu entry "Remove caches from device" (for offline lists)

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15402]
### Tell us your idea!

From time to time users ask me how to get *reliably* rid of a bunch of caches (in the current list resp. filter).
Then I usually answer that ``Manage caches`` => ``Remove from list`` is what they are looking for.
Which in most cases is the moment when the first question marks start to appear on their faces ...
"But I don't just want to delete from *list,* I want to delete from *device*, completely ...?!"
It then usually takes some time until they understand that this is the same ...
... to immediately get even bigger question marks again, once I add that this does (of course) only work, if all these caches in question are in no other list(s) than just the current one ...
IOW: If a cache is in just the current list, it will be deleted from device, while those stored (resp. referenced) in multiple lists, live on in the other list(s) ...

And exactly that's the second when most average users are completely out.  ;)

Nevertheless, there sometimes are a few who even recover from this shock and, despite everything, ask again how this can be done reliably - and to those I then explain *my* procedure to completely delete caches from the device:
1. set a filter or select the caches in question
2. ``Manage caches`` => ``Move all`` (to an empty resp. a new list)
3. switch to this list
4. ``Manage list`` => ``Make list unique`` 
5. ``Manage caches`` => ``Remove all from list``

Maybe there is an easier way to completely and reliably delete caches from the device, but apart from the fact that even I (who can probably be considered a more experienced user) don't know how, it's honestly quite hard to argue (especially to less experienced users) why there isn't an easier resp. more intuitive way to do it.

However, none of these, not even the ones who understood, were really satisfied with my answers ... which I can fully understand. ;)

### What solution would you suggest?

Add an menu entry like ``Remove all from device`` (resp. ``Remove selected from device (n)``) to the ``Manage caches`` menu list.
And if a cache is referenced in other lists, too, don't care, just entirely delete from the device.  For real.  ;)
And WRT the ``Undo`` function - if it's hard to recover all the other list references, I would just restore it to the current list.

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo I love the way you embedded this FR into a story! Made my morning :-)

**Comment by MagpieFourtyTwo** [comment]
This story is, what these users called "Real Life".
But me, also being a programmer myself, don't even have the smallest clue, what they were talking of ... ;)

**Comment by moving-bits** [comment]
See PR #16110

**Comment by Lineflyer** [comment]
Maybe its just about a better wording for some functions?

**Comment by MagpieFourtyTwo** [comment]
Not really.  It's definitely more than just wording.  Course in fact we only have the functionality "Remove from list".  Which *may* even remove cache(s) from the device, but only by accident, i. e. when the cache(s) in question are stored in just one list.

The underlying reasons for this are of course pretty obvious - *if* you have understood the principle and implementation of lists.  But this is not the case for most users.  Some even think that they have different copies of the same cache, if they store it in more than one list ...

However, to clarify things, we first need a new function called "Remove from device" (which in fact does the same as "Remove from list", but for *all* lists, in which the cache(s) in question are stored in).  Plus perhaps the possibility to say that the cache(s or UDCs) in question should immediately be removed completely, i. e. without the grace period of 72 h. Cause sometimes the remainders of e. g. a Coordinate Joker explorer can be really annoying.

Then, if a cache is stored in just one list, the only menu entry should IMHO be "Remove from device".  And if it's (or one of the current subset) is stored in more than one list, there should be *two* menu entries: "Remove from current list" *plus* "Remove from device".  Plus a checkbox to set "Without grace period" or so ...

Hope this is more understandable ... ;)

**Comment by murggel** [comment]
In detail- view we already have that function, but only for a single cache

![Screenshot_20240924_193642_cgeo.jpg](https://github.com/user-attachments/assets/6d29c1b0-f3c6-4603-a098-5d9076e1b00b)

**Comment by MagpieFourtyTwo** [comment]
Yep - this is the way i usually do it. But you have to open every single cache to get to it. Not really use friendly. And esp with caches with a lot of pics extremely time consuming.

**Comment by Lineflyer** [comment]
Why is it important to really delete a cache? Isn't it just important to modify your lists according to your needs...

**Comment by MagpieFourtyTwo** [comment]
This primarily applies to UDCs, as these still appear in map after deletion. And if you have generated a bunch of them (look for "Coordinate Joker" for a common use case), the remainders can completely spoil the map view.

You can of course use a filter to hide them, but then you also will not see the one and only you really need ... ;)

**Comment by ztNFny** [comment]
> This primarily applies to UDCs, as these still appear in map after deletion. And if you have generated a bunch of them (look for "Coordinate Joker" for a common use case), the remainders can completely spoil the map view.
> 
> You can of course use a filter to hide them, but then you also will not see the one and only you really need ... ;)

If a UDC that was removed from all lists (= deleted) still shows on map that's a bug and should be fixed.

**Comment by fm-sys** [comment]
UDC's currently get deleted after closing and reopening c:geo. This behavior could be changed of course.

**Comment by moving-bits** [comment]
> This primarily applies to UDCs, as these still appear in map after deletion. And if you have generated a bunch of them (look for "Coordinate Joker" for a common use case), the remainders can completely spoil the map view.

For "coordinate joker" using waypoints of a single cache is probably easier to handle. Maybe even using generated waypoints...

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 

Trying to clarify the request further: Which part is more important to you?
- removing a set of caches from all lists, which means the cache gets deleted after the grace period, or
- removing a set of caches immediately (probably including related data)

Although the two are somehow related (removing caches from all lists), they show different behavior:
- With #1 a cache may still appear on a map (if not actively being filtered out), just without the "stored" symbol. Only after some grace period (72h for regular caches) they will vanish completely.
- With #2, the cache gets deleted from the database immediately (no grace period), and is using the implementation of PR #16110 also related data stored locally (like listing images etc.) will be removed.

What is it you are looking for?

Your comment in https://github.com/cgeo/cgeo/issues/15402#issuecomment-2371829632 seems to point to #1, but with a extra check box, that would lead to #2.
I would like to avoid the extra check box, so what would be the one preferred by you?

**Comment by MagpieFourtyTwo** [comment]
TMALSS: Variant 1 (remove all currently filtered resp. selected caches from device).

And this, although it bothers me personally more that a UDC does not disappear after deletion - but now that I know that this inconvenience can be avoided by a simple restart of c:geo, this appears to be way less effort than all the explanations I had to make so often to a lot of people on how to delete a cache from all lists as easily as possible. So an implemented variant 1 will for sure save me more time than variant 2  ;)

**Comment by moving-bits** [comment]
PR #16171 implements "Delete selected/all from device"
(meaning: removing it from all lists; they will be deleted from database after grace period)

**Comment by MagpieFourtyTwo** [comment]
Thx a lot! Will check ...
