### ISSUE TITLE
Cannot add own photo to cache images in special scenario

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15410]
### Describe your problem!

Today I tried several times to add an own image to a certain cache by using the button on the picture tab.
After a while I found why it was failing: If I change the phone orientation (portrait to landscape) during the operation it reproducibly fails to add the photo

### How to reproduce?

- Use c:geo in portrait mode
- Open a cache
- Swipe to picture tab
- Tap + button to take a photo
- Camera app opens
- Rotate the phone to landscape and take you photo in landscape mode
- Tap OK to confirm the photo to be taken over

### Actual result after these steps?

You return from the photo app to c:geo and can see that the activity "restarts" in landscape mode and auto-swipes to the picture tab. No photo is added however.

### Expected result after these steps?

c:geo should survive the change from portrait to landscape (or vice versa) in such scenario and take over the photo to the picture tab.

### Reproducible

Yes

### c:geo Version

2024.03.02-NB

### System information

```text
Android 14
Samsung S24
```

**Comment by brivars** [comment]
I didn't even know that this was a feature until now! 
But now I have tried and indeed have the same issue - if a new pic is taken in landscape mode for this, then it fails to add.

**Comment by eddiemuc** [comment]
Workaround:
- take photo with your camera app
- switch back to c:geo and select photo with the photo picker icon

Die to this workaround I see only a low priority. I will nevertheless loon into it as time permits.

**Comment by eddiemuc** [comment]
Fixed with PR #15426
