### ISSUE TITLE
Copy to clipboard not possible

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15439]
### Describe your problem!

In the main page of a cache copy to clipboard not possible. Eg  coodinates, name, gc code,...

### How to reproduce?

Open cache
Long click on gc-code

### Actual result after these steps?

menu for text share appears (list of other apps that use text as an input), 3 pages at my phone.
![IMG_20240310_153120](https://github.com/cgeo/cgeo/assets/43813636/e3b552fb-deb8-485b-9eff-6a508942285a)

### Expected result after these steps?

possibility to copy text into clipboard

### Reproducible

Yes

### c:geo Version

2024.03.10-NB-7871581

### Additional Information

I checked the options if the "long click" behaviour can be changed, but found nothing. As a workaround it's possible to chose a text editor and copy it into the clipboard from there.

_No response_

**Comment by eddiemuc** [comment]
Normally there should be a "copy To clipboard" action among the "share" actions too (it is on all my phones). Did you deactivate that somehow in your android system?

Maybe some clipboard manager app missing?

**Comment by fm-sys** [comment]
Some manufacturers probably don't implement the "copy" feature inside the share menu.

As a workaround, you can search for "share to clipboard" on FDroid or Google. There are numerous apps which implement this feature.

**Comment by geocachermgo** [comment]
I worked until the update of the nighlty, so I guess that something changed with cgeo.

**Comment by eddiemuc** [comment]
> I worked until the update of the nighlty, so I guess that something changed with cgeo. As written I have a workaround for me.

IIRC it was decided to remove the explicit "copy to clipboard" and leave just the "share" option to simplify GUI. Reason for this was that it was assumed that "copy to clipboard" is only seldom used and also offered in "Share with" selection by android system.

**Comment by geocachermgo** [comment]
I used it a lot and would vote for not removing it.

**Comment by fm-sys** [comment]
Personally I would also vote for CopyToClipboard and drop share instead.

Some manufacturers even offer a "share" feature if something gets copied to clipboard... Not all though.

![Screenshot_20240312-172439](https://github.com/cgeo/cgeo/assets/64581222/445da2cb-f90e-4e8e-94a2-028fc9cbb1dc)

**Comment by eddiemuc** [comment]
Reported in another support ticket:  Ticket #745357

**Comment by fm-sys** [comment]
> Just for reference: Starting with android 14, it's possible to add custom actions to the share menu...
> 
> https://developer.android.com/training/sharing/send?hl=de#custom-actions

Just noticed, there is also something which we can use across all Android versions:



```
EXTRA_INITIAL_INTENTS
Added in API level 5

public static final String EXTRA_INITIAL_INTENTS
```
*A Parcelable[] of Intent or LabeledIntent objects as set with putExtra(java.lang.String, android.os.Parcelable[]) to place at the front of the list of choices, when shown to the user with an ACTION_CHOOSER. You can choose up to two additional activities to show before the app suggestions (the limit of two additional activities starts in Android 10).*

https://developer.android.com/reference/android/content/Intent#EXTRA_INITIAL_INTENTS

IMHO this is a sufficient replacement for the old copy feature.

**Comment by eddiemuc** [comment]
> Just noticed, there is also something which we can use across all Android versions:
> 
> ```
> EXTRA_INITIAL_INTENTS
> Added in API level 5
> 
> public static final String EXTRA_INITIAL_INTENTS
> ```
> 
> https://developer.android.com/reference/android/content/Intent#EXTRA_INITIAL_INTENTS
> 
> IMHO this is a sufficient replacement for the old copy feature.

See https://github.com/cgeo/cgeo/pull/15986 for an implementation

**Comment by moving-bits** [comment]
Mitigation implemented with #15986 (available with next release), therefore closing here

**Comment by wolverine007** [comment]
@moving-bits inside which Release I will find the adjustment? Inside latest RC2024.09.18 it is not working on my phone (Xiaomi F5)...

Thanks wolv

**Comment by moving-bits** [comment]
This RC as well as current release 2024.09.19 have a new setting under settings => system => copy to clipboard action. Activating this option should add a "copy to clipboard" to c:geo's share menu.

**Comment by geocachermgo** [comment]
With the 0ption activated it looks something like this

![IMG_20240927_151624](https://github.com/user-attachments/assets/91e2bc9c-2686-4b39-8395-35f5035843de)
