### ISSUE TITLE
Bookmark list no longer importing

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15452]
Ticket from support, and reproducible for me:

- open bookmark lists from home screen
- select one to download + select list to download to
- import finishes very quickly, displaying "0 caches imported from XXXX" (code of bookmark list)
- no error in log file

reported for current release candidate (2024.02.16-RC), and reproducible with today's state of `release` branch.

edit: tickets 335559, 808620, 281387, 795912, 453437, 390006

**Comment by ztNFny** [comment]
gc.com changed the site, pretty sure our csrfToken fetching is failing

**Comment by moving-bits** [comment]
https://www.geocaching.com/plan/api/gpx/list/BMxxx returns a DNF when called via browser (even when being logged in) - maybe API change?

**Comment by ztNFny** [comment]
All list-stuff was switched to a new API on weekend:
plan/api -> api/live/v1
https://www.geocaching.com/api/live/v1/gpx/list/BMxxx

**Comment by ztNFny** [comment]
The "add to bookmarks" stuff is likely broken as well - can't test right now

**Comment by moving-bits** [comment]
> All list-stuff was switched to a new API on weekend

Thanks for the new link

> The "add to bookmarks" stuff is likely broken as well - can't test right now

Still works / works again (maybe due to switching URL in the two places I updated for downloading BM lists)

**Comment by ztNFny** [comment]
Could you check the other list code as well?

e.g. to add a list I used to call POST https://www.geocaching.com/plan/api/lists, now POST https://www.geocaching.com/api/live/v1/lists
same for GET/DELETE https://www.geocaching.com/plan/api/lists/BMxxx -> https://www.geocaching.com/api/live/v1/lists/BMxxx

**Comment by eddiemuc** [comment]
Additionally from support ticket 986900:

I noticed about a week ago that cgeo isn't downloading chaches from bookmarks. It goes through the motions, but it downloads 0 caches.

**Comment by moving-bits** [comment]
> Could you check the other list code as well?
> 
> e.g. to add a list I used to call POST [geocaching.com/plan/api/lists](https://www.geocaching.com/plan/api/lists), now POST [geocaching.com/api/live/v1/lists](https://www.geocaching.com/api/live/v1/lists) same for GET/DELETE [geocaching.com/plan/api/lists/BMxxx](https://www.geocaching.com/plan/api/lists/BMxxx) -> [geocaching.com/api/live/v1/lists/BMxxx](https://www.geocaching.com/api/live/v1/lists/BMxxx)

creating a new bookmark list does work with the mentioned change

how can I trigger a delete operation? (or do you mean adding to/deleting from watchlist? that does work as well)

**Comment by eddiemuc** [comment]
Is this issue solved meanwhile (by @moving-bits changes mentioned above)?

**Comment by moving-bits** [comment]
> Is this issue solved meanwhile (by @moving-bits changes mentioned above)?

The original issue is resolved, but I'm unsure about the things mentioned in https://github.com/cgeo/cgeo/issues/15452#issuecomment-2000581254

**Comment by ztNFny** [comment]
i have no idea whether there's a delete function in c:geo. it's just that I'm aware of those API changes and wanted to communicate those findings.

**Comment by eddiemuc** [comment]
> > Is this issue solved meanwhile (by @moving-bits changes mentioned above)?
> 
> The original issue is resolved, but I'm unsure about the things mentioned in https://github.com/cgeo/cgeo/issues/15452#issuecomment-2000581254

We have quite some support ticket for this, we should create a release soon when it is fixed

**Comment by moving-bits** [comment]
My plan was to create a feature release from `release` either tonight or tomorrow, as discussed in our last dev meeting.

**Comment by moving-bits** [comment]
> i have no idea whether there's a delete function in c:geo. it's just that I'm aware of those API changes and wanted to communicate those findings.

ok, thanks for clarifying. Then let's close here, as the original issue is fixed.
