### ISSUE TITLE
Design options menu in landscape shows settings activity next to it

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15459]
### Describe your problem!

I used c:geo on my tablet today and wanted to switch the design options of my offline map theme.
While doing so I noticed, that this setting screen looks strange.

### How to reproduce?

- Turn phone to landscape
- Open map
- Select Menu - Design options

### Actual result after these steps?

The screen shows the design options on the left and on the right side the normal Settings/Services screen is shown. Trying to use this "phantom menu" makes c:geo immediately return to the map.

### Expected result after these steps?

Only the design options should be shown

### Reproducible

Yes

### c:geo Version

2024.03.13-NB

### System information

```text
Samsung S24
Android 14
```

**Comment by moving-bits** [comment]
will be fixed with #15466
