### ISSUE TITLE
Add cache to stored lists: current lists not longer on top

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15464]
Ticket 980646

When adding a cache to stored lists using the pencil button from cache details, the lists where the cache is already in used to be on top.

Now cache lists are sorted alphabetically.

This is a side-effect of recent grouping changes and should be fixed.

c:geo version: 2024.03.15-NB-b6d2b39

**Comment by moving-bits** [comment]
IMHO this should be fixed before publishing a new release

**Comment by eddiemuc** [comment]
> IMHO this should be fixed before publishing a new release

This problem affects master/nightly only. Stored list grouping is not part of beta/release branch. Thus should be non-critical for new release

**Comment by moving-bits** [comment]
> This problem affects master/nightly only. Stored list grouping is not part of beta/release branch. Thus should be non-critical for new release

ah, sorry, have mixed this up

**Comment by eddiemuc** [comment]
fixed with PR #15468

**Comment by MagpieFourtyTwo** [comment]
Yeah! *That's* what I did not get yesterday! :)

Just thought "something is different" while logging my caches (offline) and moving them to my "Offline Logs" list (which I use to log my cache in the evening).

Did not get why it suddenly was so hard to remove the logged cache from the other lists where these caches were in before.

While your remark about "Lists in groups" draw my attention: How is "show lists of current cache at top of list" supposed to work with grouped lists? Would be a deal breaker for me if these lists would remain hidden in their folders ... I would think to see these lists at the top, too ... with their entire "coloned name" ...

**Comment by MagpieFourtyTwo** [comment]
Yeah! *That's* what I did not get yesterday! :)

Just thought "something is different" while logging my caches (offline) and moving them to my "Offline Logs" list (which I use to log my cache in the evening).

Did not get why it suddenly was so hard to remove the logged cache from the other lists where these caches were in before.

While your remark about "Lists in groups" draw my attention: How is "show lists of current cache at top of list" supposed to work with grouped lists? Would be a deal breaker for me if these lists would remain hidden in their folders ... I would prefer to see these lists at the top, too ... with their entire "coloned name" ...

**Comment by eddiemuc** [comment]
> While your remark about "Lists in groups" draw my attention: How is "show lists of current cache at top of list" supposed to work with grouped lists? Would be a deal breaker for me if these lists would remain hidden in their folders ... I would prefer to see these lists at the top, too ... with their entire "coloned name" ...

Yes, that's worth discussing. In the PR I merged this morning it is implemented such that groups with a selection in them are sorted atop, and inside any group selected items are sorted atop. If anything else is wished let's open a new issue for discussion.
