### ISSUE TITLE
Not able to use mail link from cache description

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15465]
### Describe your problem!

Not sure whether this is a problem in c:geo or with my new device, however I am unable to open my mail application by tapping an email link in a cache description.

Tried the same from browser and messenger and it correctly opened the systems "app chooser" to let me decide which mail app to use and afterwards opens a new mail with the recipient from the link.

### How to reproduce?

- Have ChromWebView active in settings
- Open GC891TD
- Within the cache description tap on the mail link in section "Vraag 4"

### Actual result after these steps?

c:geo shows a toast: "c:geo konnte keine passende Anwendung finden"

### Expected result after these steps?

Default mail app should be opened, respectively system dialog to select the desired app should be shown

### Reproducible

Yes

### c:geo Version

2024.03.14-NB

### System information

```text
Samsung S24
Android 14
Installed mail apps:
- K9 Mail
- Outlook
```

**Comment by moving-bits** [comment]
Cannot reproduce on my physical test device with current state of either `release` and `master` with default settings, but can if "use Chrome webview" in settings - cache details is enabled.

**Comment by Lineflyer** [comment]
Yes, I have Chrome Webview active as well.
Once I disable it, it works. Good catch.

We should still fix it IMHO.
