### ISSUE TITLE
Cache Logging: default action for trackables in inventory is updated on "log send" only - should be done on "log save"

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15474]
### Tell us your idea!

While working on support ticket 841995 I noticed a potentially confusing behavior of c:geo.

When logging a gc.com cache, c:geo offers to send actions for trackables in inventory (one of do nothing, visited or dropped off):
![image](https://github.com/cgeo/cgeo/assets/6909759/40eed246-ef6d-486c-a0d1-a9250c5d74c9)

Users often have different "default actions" they want to have associated with trackables in their inventory. For example, some should log a "visited" on every found cache, others should maybe not get logged ("do nothing"). To ease log creation, c:geo stores the last used action on a per-trackable-basis and pre-fills log screen with this action.

c:geo stores a new "default action" on a trackable every time a log is sent to gc.com server (not when it is just saved locally offline). This can lead to following confusing scenario:

* User creates a log, He changes the default-action-to-far "visible" to "do nothing" for an inventory tb while do so. He saves the log (not sending it)
* User creates a new log for another cache. --> now in this log the default action is again filled with "visible" (because previous log was not yet send). This is potentially confusing

### What solution would you suggest?

Update inventory-tb-default-action on log-save (not on log-send)

### Is there an alternative?

do nothing

### Additional Information

I want to put this up for discussion

**Comment by Lineflyer** [comment]
I agree. Storing the actions on log save is more consistent.

**Comment by eddiemuc** [comment]
Fixed with PR #15509
