### ISSUE TITLE
[Nightly] Lists organized in Folders => Folder Name not recognized by List name search

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15472]
### Describe your problem!

As well known, lists can be grouped into folders by adding a ":" to the list name.
As soon as there are at least two lists with the same string *before* a colon, they are grouped in a "folder".
My "problem": The "folder name" (i. e. the string before the colon) will not be found by the list search ...
Although this may even be intended, I would say, it's a regression.

### How to reproduce?

1. define (at least) two lists and name them e. g. "Region: Munich" and "Region: Hamburg"
2. in e. g. the main screen long click on the ``Lists`` icon to open the list selection popup
3. click on the magnifier (top right)
4. enter "Region" as search pattern 

### Actual result after these steps?

No List will be found (given that you do not have any list with "Region" in it's name *after* a poss. colon ;) ) as if there are no Lists containing "Region" at all.

### Expected result after these steps?

I expected to see all lists with "Region" in it's name, no matter if "Region" is before or after a colon.
In the above example I expected to see "Region: Munich" and "Region: Hamburg" resp. "Munich" and "Hamburg".

### Reproducible

Yes

### c:geo Version

2024.03.16-NB-4f30164

**Comment by eddiemuc** [comment]
That's not intended and definitely a bug

**Comment by eddiemuc** [comment]
Fixed with PR #15476
