### ISSUE TITLE
UnifiedMap: set waypoint as target sets cache as target

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15488]
1. open a cache with multiple waypoints
2. View in map mode (compass - map)
3. Tap a waypoint
4. In WP popup "set as target"

Expected: Navigation line to WP
Actual: Navigation line to cache listing

**Comment by MagpieFourtyTwo** [comment]
Duplicate of #15473?

**Comment by moving-bits** [comment]
Bug confirmed. Target gets reset as map is still in "geocode" mode (and we trigger a reload since one of the more recent changes on `release`)

**Comment by moving-bits** [comment]
see PR #15506
