### ISSUE TITLE
Cache "open in browser" only allows to select system standard browser

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15486]
Support ticket 155392

When trying to open a cache listing in browser using "Open in browser", then c:geo only allows to choose between the c:geo-internal WebView and the systems default browser (as set in Android settings). C:geo should allow to choose between all installed browsers if more than one is installed (eg chrome, Firefox, duckduckgo, ...)

This should also help with above support ticket. In that case somehow Firefox is not recognized as browser by c:geo although set as default browser in Android system. c:geo version: 2024.01.06

**Comment by Lineflyer** [comment]
Reference to https://github.com/cgeo/cgeo/issues/12209

**Comment by Lineflyer** [comment]
@eddiemuc 
New reply from user:

gestern habe ich es mit verschiedenen Browsern als Standardbrowser ausprobiert. Ergebnis: nur bei Chrome erscheint die Auswahl, bei Firefox, Samsung Internet und Bing nicht.

Jetzt kommt's: ich habe mir soeben das neueste c:geo-Update installiert, und was soll ich sagen, jetzt geht's auch wieder mit Firefox. Habe zwar im Changelog diesbezüglich nichts gefunden, aber das Problem scheint sich erledigt zu haben.

**Comment by eddiemuc** [comment]
Great to hear that this is solved for the support ticket.

Nevertheless I think the feature is worthy.

**Comment by ztNFny** [comment]
There's already 2 solutions to this:
- If you don't want to select a default but be prompted every time then don't set a default browser in Android.
- If you sometimes want to open it in another browser use Share instead of Open.
