### ISSUE TITLE
Map View: force display of at least map layer select and filter symbol on actionbar

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15494]
Support ticket 105993

On some devices it seems that in map view the action symbols for map layer select and filter are not displayed although visually there would be enough room for them.

Suggestion into force-display those two action icons (as is already implemented for the "stick to current position" icon.

**Comment by moving-bits** [comment]
Should be obsolete since moving the "follow me" icon out of the toolbar, therefore closing here
