### ISSUE TITLE
Let emulator builds from release branch behave like the actual release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15501]
I would like to get your feedback on this:
In order to reproduce user bug reports of our latest releases I fired up AS, checkout the corresponding "market_xyz" tag on branch `release` and fired up the emulator.

While checking some map issues I was expecting the "old map" to still be default after installation but got confused that instead "unified map" cam up instantly.

I guess this is due to some condition to enable it in nightly and debug builds. 
Is there any chance we could have `release` look like the customer release even when building it with AS?

**Comment by eddiemuc** [comment]
Did you use the emulator before? Afaik an existing database and settings are reused even if you install other code versions of c:geo onto it. Maybe you previously tested some version of c:geo with UM enabled?

**Comment by Lineflyer** [comment]
> Did you use the emulator before? Afaik an existing database and settings are reused even if you install other code versions of c:geo onto it. Maybe you previously tested some version of c:geo with UM enabled?

I had to run the onboarding like after a fresh install...so I guess no previous data.

**Comment by moving-bits** [comment]
Those are the relevant rules for setting UnifiedMap as default (or not) in our builds:

``` 
public static boolean useUnifiedMap() {
    return getBoolean(R.string.pref_useUnifiedMap, !BranchDetectionHelper.isProductionBuild());
}

public static boolean isProductionBuild() {
    return !(BuildConfig.BUILD_TYPE.equals("debug") || BuildConfig.BUILD_TYPE.equals("nightly"));
}
```

So all self-built APK ("debug / developer") as well as our nightly versions have UnifiedMap as default.

**Comment by Lineflyer** [comment]
Well...not sure if its worth to change something because these conditions will hopefully vanish as soon as we completely default to 'unified map', isn't it?

**Comment by moving-bits** [comment]
> Well...not sure if its worth to change something because these conditions will hopefully vanish as soon as we completely default to 'unified map', isn't it?

yes

so let's close here
