### ISSUE TITLE
Name of Saved Filter gets lost on adding criteria via Map's bottom sheet

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15514]
### Describe your problem!

In (Live) Map's header the Name of the currently active Saved Filter gets replaced by the criteria (resp. its count(s)),
as soon as you deselect a Filter relevant criterion via Quick Settings of the map.
Moreover no name will be displayed in the Filter dialog anymore.

### How to reproduce?

Create and apply an appropriate filter:

1. open (Live) Map
2. open Filter dialog page by clicking the filter icon
3. in advanced mode, create a simple filter like "Type=Tradi" and store it as e. g. "Tradis only" 
4. return to live map by applying the filter

Header now shows name of applied filter (as to be expected)

5. open Quick Settings bottom sheet by clicking the cog
6. disable "Found"
7. apply the change by click on the map

### Actual result after these steps?

8. neither header nor filter dialog will show the name of the (changed) stored filter anymore.
    Instead in Map there will be the criteria of the filter and in Filter dialog just an empty field.

### Expected result after these steps?

The name of the Saved Filter should be shown, with its "changed markers" (i. e. name in brackets, italic, plus the star).
Same applies for the Filter dialog (to be able to easily change the saved version).

### Reproducible

Yes

### c:geo Version

2024.03.24-NB-3da0a92

### Additional Information

Currently there's no way to overwrite, i. e. change the definition of a Saved Filter after such a change, other than either typing the filter's name by heart or (if it's more than just a no-brainer) discard the actual changes, re-apply the saved version of the filter in question, copy its name from the save dialog to clipboard, re-apply manual changes, open save dialog and paste the name from clipboard ... little bit cumbersome.  ;)

BTW, WRT the example above: After enabling "Found" again and then opening the filter page, the criteria group "Status" is still there, although all states are enabled - wouldn't it be better to drop the criteria group, if it does not add anything to the filter? 

Moreover, I tried the above with offline map, too (from mapping a stored list) and got curious results: Sometimes it behaved like in Life Map, sometimes the name of the filter vanished completely, although the filter was still active.

**Comment by eddiemuc** [comment]
Confirmed. Also happens in productive release unfortunately (2024.03.19)

**Comment by eddiemuc** [comment]
Should be fixed with #15515 

> BTW, WRT the example above: After enabling "Found" again and then opening the filter page, the criteria group "Status" is still there, although all states are enabled - wouldn't it be better to drop the criteria group, if it does not add anything to the filter?

Request is understood. This would however require some deeper code changes (no possibility currently to remove filter children easily) and should thus be its own Feature Request (if wanted)

**Comment by MagpieFourtyTwo** [comment]
> This would however require some deeper code changes 

Ok - most probably not worth the effort.  Thx for clarification.

**Comment by MagpieFourtyTwo** [comment]
Not only fixed, but even improved ...?  ;)

AFAIR, one couldn't get rid of the "changed markers", once they appeared due to a filter change - even if you have meticulously reverted all changes.  This is no longer the case:  On a complete (manual) revert, even the "change markers" disappear again.  Nice, nice!

Thx!

**Comment by MagpieFourtyTwo** [comment]
BTW: Just changed my "Live" filter (added "owner name contains 'post'") and expected to see the filter name in brackets, italic and with an asterisk - but there are only the brackets ... intentionally?

**Comment by moving-bits** [comment]
Not sure if it's related, but there is still some work going on here, see #15521

**Comment by MagpieFourtyTwo** [comment]
Yep - very possible. If I think about it again, this may indeed have occurred after changing a modified filter ...
Sorry to have been too fast ...  ;)

**Comment by eddiemuc** [comment]
> Not sure if it's related, but there is still some work going on here, see #15521

Indeed that's related. Behavior should "normalize" once the mentioned PR is merged.
