### ISSUE TITLE
Add help text for disabled "keyword search" field

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15539]
Since disabling the "keyword search" input field for non PM, we get support tickets for this "non functional button" (though nearly no one complained about a non-function keyword search before...).

We should add a short explanation (only on disabling this input field) that this function is available for PM only.

**Comment by eddiemuc** [comment]
Is keyword search still possible in GUI when one registers an opencaching or su account? Those also support keyword search

**Comment by moving-bits** [comment]
yes, it's only disabled if ony gc.com connectors are active and the user is a BM (see #15162)

**Comment by moving-bits** [comment]
(Assigned to "non collab" for now, see #15469)

**Comment by moving-bits** [comment]
Note: Fix should be targeted to `release` branch

**Comment by moving-bits** [comment]
removed assignment to "non collab" due to lack of response
