### ISSUE TITLE
Request for Feature: Add Map Rotation Ability for Offline Maps

### ISSUE THREAD

**Issue by anondev-sudo** [cgeo/cgeo#15536]
#### Description:
Currently, when using offline maps like OSM paws in c:geo, users are unable to rotate the map either manually with fingers or enable automatic map rotation, unlike the functionality available with online maps such as Google Street or Google Satellite. This limitation hinders user experience and map navigation, especially when orientation adjustments are crucial for efficient geocaching.

#### Proposed Feature:
Introduce the ability to rotate offline maps within c:geo, enabling users to manually rotate the map with their fingers or activate automatic map rotation. By incorporating this feature for offline maps like OSM paws, users can enjoy enhanced flexibility and improved navigation capabilities, similar to what is available with online map services.

#### Justification:
The addition of map rotation ability for offline maps addresses a significant usability gap in c:geo, providing users with essential orientation control features that are currently lacking. Enabling users to rotate offline maps enhances the overall geocaching experience, making it easier to navigate and locate geocaches effectively.

#### Expected Behavior:
Upon implementing the map rotation feature for offline maps, users should be able to manually rotate the map using gestures or enable automatic map rotation for seamless navigation. This functionality should mirror the flexibility and convenience offered by online maps, allowing users to adjust map orientation according to their preferences.

**Comment by moving-bits** [comment]
This feature is already available for the all-new "UnifiedMap", available as beta version since our current release 2024.03.19

The old map implementation for offline maps (which is still the default) does not support map rotation, though, so you will have this for Google Maps (old), Google Maps (UnifiedMap), OSM online maps (UnifiedMap) and OSM offline maps (UnifiedMap).

**Comment by anondev-sudo** [comment]
How do I enable that new beta feature? Will map rotation and auto rotation work with it with paws maps?

**Comment by SammysHP** [comment]
Unified map should already be enabled in the nightly build. So you just need to install the Nightly version available from our website: http://download.cgeo.org/cgeo-nightly.apk

**Comment by moving-bits** [comment]
Or, if you are using the current release 2024.03.19, you can enable it manually by going to settings => map sources => unified map

**Comment by anondev-sudo** [comment]
It takes so long to show map  at first there is blank screen and the map is lagging when zooming it. It's really slow on my phone. I had to switch back to old maps

**Comment by Lineflyer** [comment]
@anondev-sudo 
Can you post your system information from "About c:geo" -> Swipe to "System" and/or name make and model of your device?

**Comment by anondev-sudo** [comment]
Device type: M2003J15SC (merlinnfc_eea, Redmi)
Available processors: 8
Android version: 12
Android build: SP1A.210812.016
Screen resolution: 1080x2110px (392x767dp)
Pixel density: 2.75
System font scale: 1.0 / used scale: 1.0
Sailfish OS detected: false
Google Play services: enabled - 24.09.14 (190400-617895654)
Memory:  Available:975,4 MB, Total:3,6 GB, Threshold: 399,8 MB, low:false

**Comment by Lineflyer** [comment]
@anondev-sudo 
I took your map start issue into a new dedicated issue: https://github.com/cgeo/cgeo/issues/15545
