### ISSUE TITLE
Use compass rose on map to toggle rotation mode

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15546]
### Tell us your idea!

I am unsure, whether this an actual feature request or whether the current behavior is a bug.

I often toggle between automatic map rotation and northbound map, depending on whether I am hiking/sitting on my bike (rotation) or just want to get an overview of todays caching plan sitting somewhere (northbound as I don't know my current heading).

At the moment it seems I have to dive down into the Map Menu - Rotation to do so.
Intuitively I tried tapping the compass rose shown on top left of the map. This results in the map shown northbound and afterwards the compass rose icon vanishes and it seems only temporary as the map mode remains to be set to rotation.

### What solution would you suggest?

The compass rose icon could be the main switch to enable/disable rotation.
The Menu Map - Rotation could be limited to select the type of rotation (Energy saving or not) which is typically not changed quite often (or this setting could be moved into the normal settings area (Map Behavior) where I would expect it).

### Is there an alternative?

As said initially, I am not sure whether the current working mode of the compass rose icon might be just a bug and is already intended to work as suggested.

**Comment by moving-bits** [comment]
Our "old" Google Maps type maps work like this:
- set map rotation to "automatic" and wait until maps is rotated, compass rose is shown
- tap on compass rose
- map will be north-oriented now, rotation mode reset to "manual"

If UnifiedMap does not work like this currently (haven't checked), then it's a missing feature or bug.
