### ISSUE TITLE
Website changes: Live map no longer working

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15550]
_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/15543#issuecomment-2038033943_
            
[...]

]However, tested the following issues (which did not work for me before):

- Login: WFM - but only on third attempt: first failed, second resulted in "Login OK, Basic", eventually third worked out (after a fresh start), but took 4(!) seconds until it was done
- Live Map (download of caches) - **does NOT work** - in Live Map I only see offline saved caches, no fresh downloads,
   no matter if PM or not (scrolled map to a region I did not visit recently - no caches in Paris, e. g.)
- Download of PM cache (via GC code): WFM (even with filled logbook ;) )
- PN upload: WFM
- Change Coordinates on website: WFM
- Refresh of a offline stored cache: WFM
- Fieldnotes upload - WFM
- Posting a Write Note log from c:geo: WFM
- Logging a PM cache plus TBs as "Visited": WFM
- delete cache log: WFM
- edit cache log: WFM
- ...

WRT TB discover I'm out - do not discover anymore

**Comment by Cubly** [comment]
c:geo refuses to login for me too citing 'Failed Login page parsing'
Seems you guys are aware of the issues though!

**Comment by eddiemuc** [comment]
> Live Map (download of caches) - does NOT work - in Live Map I only see offline saved caches, no fresh downloads,
> no matter if PM or not (scrolled map to a region I did not visit recently - no caches in Paris, e. g.)

I will look into it starting now

**Comment by moving-bits** [comment]
> c:geo refuses to login to Geocaching.com for me too citing 'Failed Login page parsing' Seems you guys are aware of the issues though!

@Cubly 
This is issue #15543, fixed meanwhile with release 2024.04.05

You may need to login twice initially after the upgrade, though, due to premium membership not always being detected correctly in the first run (that's issue #14950, unrelated to the recent website changes on geocaching.com).

**Comment by moving-bits** [comment]
Seems to be fixed with a combination of #15558 and #15664, so let's close here for now. Feel free to reopen or create a new issue if problem reoccurs.
