### ISSUE TITLE
cache type block party - no special symbol after reading from gpx

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15552]
### Tell us your idea!

The cache type "block party" e.g. GCAJ960 is shown on the map with the normal event symbol. That should be changed to the party symbol.

**Comment by bekuno** [comment]
I see for this cache the `R.drawable.type_specialevent`, as defined in [enumerations/CacheType.java](https://github.com/cgeo/cgeo/tree/master/main/src/main/java/cgeo/geocaching/enumerations/CacheType.java). 
Btw., this icon is also used for `GCHQ_CELEBRATION` and `COMMUN_CELEBRATION`. 
![grafik](https://github.com/cgeo/cgeo/assets/32555742/c232145d-9f4a-4a24-8e76-8db2f88e3d12)

For event we have the symbol: 
![grafik](https://github.com/cgeo/cgeo/assets/32555742/499a04d4-43d9-4f0f-bf4b-216b2d78d40d)

**Comment by geocachermgo** [comment]
This is shown in cgeo:
![IMG_20240405_113358](https://github.com/cgeo/cgeo/assets/43813636/b806cd5f-6c0c-4d92-8743-c53e7a637df5)
This is shown by gc.com:
![IMG_20240405_113431](https://github.com/cgeo/cgeo/assets/43813636/bf24e698-bbab-4c6d-88a5-f586f7569b93)
That upper black symbol would be fine for me.
I use: 2024.04.05-NB-bf2adb3

**Comment by geocachermgo** [comment]
After reload, the correct symbol is there, so I close the issue.
I loaded the cache via gpx file, because cgeo (old nighly) was unable to log in. So maybe there is a problem reading the correct cache type from gpx file.

**Comment by bekuno** [comment]
I reopen it - someone should check, why the reading from the gpx did not honour the special cache type (icon).

**Comment by bekuno** [comment]
@geocachermgo Can you upload the gpx (maybe reduced to this cache)?

**Comment by geocachermgo** [comment]
Downloaded directly from https://coord.info/GCAJ960

[GCAJ960_gpx.txt](https://github.com/cgeo/cgeo/files/14883768/GCAJ960_gpx.txt)
contains:
...
<sym>Geocache</sym>
    <type>Geocache|Event Cache</type>
...
   <groundspeak:type>Event Cache</groundspeak:type>
      <groundspeak:container>Other</groundspeak:container>
So it looks like is a problem of gc.

**Comment by bekuno** [comment]
Confirmed.

And for fun, when you load the gpx from the map, then you have
~~~
		<name>GCAJ960</name>
		<sym>Geocache</sym>
		<type>Geocache|Geocaching HQ Block Party</type>
...
			<groundspeak:type>Geocaching HQ Block Party</groundspeak:type>
			<groundspeak:container>Other</groundspeak:container>
~~~
