### ISSUE TITLE
Compass hidden behind navigation

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15575]
![IMG_20240407_201008.jpg](https://github.com/cgeo/cgeo/assets/1258173/0485e01f-9681-4415-90e7-8790fe1eb88f)

In unified map the compass is drawn behind the navigation view, making it inaccessible. It should probably be pushed down below the view.

**Comment by moving-bits** [comment]
Same is true for "old" Google Maps

**Comment by moving-bits** [comment]
Fixed for UnifiedMap, therefore removing "Map: Unified" label and removing from "UnifiedMap" project
