### ISSUE TITLE
Variables for projection get prefilled with NULL

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15589]
Quick note from out and about:

Today I prepared a multi and added a calculated projection like E*5+1 meters and F+10 degrees.

Afterwards I synced the waypoints to my personal note.

When looking at the variable tab afterwards, that E and F (previously empty) now contain the value `null`

Current nightly

**Comment by eddiemuc** [comment]
Can't reporoduce with current release branch. When I follow the steps above, then variables E and F are not created in variable list (as expected in current state of feature implementation)

Is this still happening?

**Comment by tinkus-gc** [comment]
I can reproduce the phenomenon “$variable=null” as follows:

- choose any cache in c:geo without variables or personal waypoints, (GC6ZJVZ in my tests)

- create a new variable A without a value

- add waypoints to the personal note; result:
```
{c:geo-start}
$A=null
{c:geo-end}
```

- delete variable A

- update waypoints in the personal note; result: the above entry in the PN remains (but can of course be removed using the delete button).

- If I change the PN with the above entry and deselect the checkbox “Prevent waypoints extraction”, the variable A is created again, but this time with the value `null`.

**Comment by murggel** [comment]
Can reproduce and PR #15919 should fix this
