### ISSUE TITLE
[Nightly] {UnifiedMap] "Stay with me" survives pan, if happens during zooming

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15590]
### Describe your problem!

Usually ,I`m in Live map, OSM offline, with the "Stay with me" button ;) activated (i. e. map is set to follow my position).
And the "follow me" function is active until I pan the map.  Which is perfectly fine.
*But* when I zoom *and* pan, the setting remains active and although I (intentionally) panned to a completely different region, it takes me back to my position. Most of the times immediately, sometimes after a second or so.
Which is pretty annoying, cause then I again have to zoom out and in again to the region I wanted to go to,

### How to reproduce?

1. enter Live map
2. activate "stay with me"
3. zoom and *while zooming* pan to a different region without lifting your "zoom fingers" from the display

### Actual result after these steps?

4. map will zoom an pan as intended
5. now lift your fingers from the display
6. either immediately or a few seconds (or another zoom action) later, the map will jump back to your current position

### Expected result after these steps?

Map should stay where I have panned her, i. e. "stay with me" should also be deactivated if panning happens while zooming

### Reproducible

Yes

### c:geo Version

2024.04.13-NB-4ae1565

### Additional Information

With "classic" map "stay with me" gets immediately deactivated even on zoom actions.
Which I would consider a bit harsh ... truth lies most probably somewhere in the middle ... as usual.  ;)
So, zooming alone with just "a little bit of panning" (i. e. unintentional pan) may safely leave "stay with me" active,
but obviously intentional panning should definitely deactivate it.

**Comment by moving-bits** [comment]
Confirmed for UnifiedMap VTM, but seems to work for UnifiedMap Google

**Comment by moving-bits** [comment]
VTM seems to be a bit confusing... mapUpdateListener sends slightly different events depending on type of actions and type of invocation:

|action|invocation|fired events|
|---|---|---|
|zooming|zoom controls|multiple POSITION, but no SCALE|
|zooming (+ moving while zooming)|manually|SCALE, then one or more POSITION, but no MOVE|
|moving|manually|MOVE + POSITION|

With this "workaround" I can make VTM "manual zoom" behavior similar to UnifiedMap Google: On initiating zoom via two finger gesture (which nearly always includes a slight movement) disable "follow me". No "grace distance", though (both types).

**Comment by moving-bits** [comment]
PR #15722 implements this behavior for UnifiedMap VTM (OSM).
UnifiedMap Google already acts in this way.

**Comment by MagpieFourtyTwo** [comment]
Sounds good - Thx! 

Grace distance is not that important anyway. If one wants to keep "follow me" there's nothing to say against using the zoom controls. ;)
