### ISSUE TITLE
Option to disable map rotation

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15602]
I often manage to accidentally rotate the map - and then am confused because it doesn't look like expected anymore. This wasn't an issue with old OSM maps as they didn't support rotaiton.
I never ever want to rotate the map. North is up, period.

Thus I'd like to have an option to completely disable map rotation.

**Comment by alan666notb** [comment]
Yes, I support this idea as well.
Was just about to suggest it myself.

Maybe a long press on the compass icon to bring up a lock/unlock menu?
It would be possible to lock it in it's current rotation, not just "North up".

**Comment by moving-bits** [comment]
You can set map rotation to "off" in the map's overflow menu.

**Comment by ztNFny** [comment]
> You can set map rotation to "off" in the map's overflow menu.

Oops, I looked everywhere in settings, didn't think to check that overflow menu. Too many places to "hide" stuff ...
