### ISSUE TITLE
Github actions - Debug watchdog test failure

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15624]
Since merging the github actions none of the scheduled watchdog jobs was successful.

It looks like the run for `release` fails, which cancels the job for `master` implicitly.

![image](https://github.com/cgeo/cgeo/assets/949669/e4923719-ce50-48cb-8802-8d87ce8d19ec)

From the error message I could guess, that the root cause is, that `release` does not (yet) contain the file `.github/actions/cgeo-preferences/action.yml`. 

This is due to the fact, that the action PR was merged to `master` but `release` is still well behind `master` until our next feature release.

@kumy Is my assumption correct, that this could be the reason? If so I would take care to copy that file to release as well. Should be an easy fix then.

**Comment by kumy** [comment]
@Lineflyer how would you proceed here? Should we cherry pick the initial PR into that branch, or you have other way of managing such case?

**Comment by Lineflyer** [comment]
I will add the file via push to `release`. As it is identical to `master` it should not lead to any merge conflicts IMHO.

**Comment by Lineflyer** [comment]
Done in https://github.com/cgeo/cgeo/commit/4e78eec70cadf1c6c2f2d8a8401711a0490a1c9e

Have started a manual run of watchdog tests, which now at least runs for longer than a few seconds.
Was to tired to wait for the outcome, anyway the workflow issue itself is fixed.

https://github.com/cgeo/cgeo/actions/runs/8712790627
