### ISSUE TITLE
Logging unit test errors

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15657]
Our watchdog tests still show the same error.
The fix has not taken effect.

See for master eg. https://ci.cgeo.org/job/WatchdogTests_master/2712/testReport/cgeo.watchdog/WatchdogTest/testGeocachingLogTrackable/, 
and for release eg. https://ci.cgeo.org/job/WatchdogTests_release/5414/testReport/cgeo.watchdog/WatchdogTest/testGeocachingLogTrackable/ and https://ci.cgeo.org/job/WatchdogTests_release/5414/testReport/cgeo.watchdog/WatchdogTest/testGeocachingLogCache/.

_Originally posted by @bekuno in https://github.com/cgeo/cgeo/issues/15633#issuecomment-2068313298_

**Comment by ztNFny** [comment]
The fails for release branch are during the login process, not in actual logging: 
 Response{protocol=http/1.1, code=403, message=Forbidden, url=https://www.geocaching.com/account/oauth/token} 

As this doesn't happen in cgeo but there are/were login issues recently maybe the tests need to be adjusted? 

TB logging works from UI, so why does the test fail? 🧐

**Comment by ztNFny** [comment]
> See for master eg. https://ci.cgeo.org/job/WatchdogTests_master/2712/testReport/cgeo.watchdog/WatchdogTest/testGeocachingLogTrackable/,

addressed by #15658

> and for release eg. https://ci.cgeo.org/job/WatchdogTests_release/5414/testReport/cgeo.watchdog/WatchdogTest/testGeocachingLogTrackable/ and https://ci.cgeo.org/job/WatchdogTests_release/5414/testReport/cgeo.watchdog/WatchdogTest/testGeocachingLogCache/.

The fails for release branch are during the login process, not in actual logging:
Response{protocol=http/1.1, code=403, message=Forbidden, url=[https://www.geocaching.com/account/oauth/token}](https://www.geocaching.com/account/oauth/token%7D)

The WatchdogTests are working fine for me, running from my local dev env. My best guess is that there was a login error during the automated test run - which should disappear on its own on next run.

**Comment by bekuno** [comment]
The `testGeocachingLogTrackable` error is fixed by PR #15658, the `testGeocachingLogCache` disappeared automatic.
