### ISSUE TITLE
Find count not updated after found log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15650]
### Describe your problem!

Users on FB report, that loggin works fine with 2024.04.18 but some(?) of the users have the issue, that the find count on home screen and thus also the signature placeholder is not updated after logging the find.
The workaround is to reboot/restart c:geo to get an updated find count.

It seems c:geo is able to retrieve the find count during the login process but not on/after logging a cache.

### How to reproduce?

- Find count on home screen = x
- Log a found on a geocache

### Actual result after these steps?

Find count on home screen still = x

### Expected result after these steps?

Find count on home screen = x+1

### Reproducible

Unclear

### c:geo Version

2024.04.18

**Comment by moving-bits** [comment]
one more ticket on support for this issue: 721371

**Comment by fm-sys** [comment]
Team meeting 09.06.: After a quick test it seems to be working in version 2024.06.04
Let's wait for support feedback before closing.

**Comment by moving-bits** [comment]
Feedback from user: Seems to be working again.
Thus let's close here for now (and reopen if problem reappears).
