### ISSUE TITLE
[Nightly] [UnifiedMap] Change of routing style shows no effect - until GPS position changes

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15652]
### Describe your problem!

Admittedly, it may be a bit hard to reproduce, but after using c:geo for a while, changing the routing style seems to show no effect at all anymore. After a few hours the background re-routing (because of style change) takes up to 60(!) seconds until the new route is displayed on the map. And this applies even to style "straight line".

Even worse: Sometimes it does not appear at all, even after several minutes. And even after a fresh restart it takes extraordinary long, especially if you change the style multiple times. Over here, already the third change took 15 seconds to recalculate - while "route" is even kind of exaggerated, as the currently tested target is just 2 km away ...

### How to reproduce?

1. Open Unified Life Map
2. chose any cache and route to it by clicking the bottom sheet's nav button
3. after route is displayed, use bottom sheet to change the routing style
4. repeat 3. for a few times ...

### Actual result after these steps?

5. no matter which routing style will been chosen, even "re-calculation" of "straight line" will take really long at some point (about 30 seconds up to ... uncounted)

### Expected result after these steps?

Re-Routing should take place within seconds.  And in my tested distances within a fraction of a second.

### Reproducible

Yes

### c:geo Version

2024.04.21-NB-be2d1b4

**Comment by moving-bits** [comment]
have not been able yet to reproduce this in the emulator, even though I have a pretty slow one today, and I switched routing style about 20 times between the four modes for a route of app. 6 km (three items + route from current position)

**Comment by MagpieFourtyTwo** [comment]
Although routing was extremely "stubborn" that day, it hasn't happened since.
I'll keep an eye on it, maybe I can get a more reproducible scenario.

**Comment by MagpieFourtyTwo** [comment]
New finding: Recalculation (resp. refresh in map) will not happen, *until current GPS location changes.*

Of course it doesn't matter if the change has happened because of signal hopping or real position changes, but if you (or your signal) don't move, you will wait forever, the route will not be updated in map.

Absolutely reproducible scenario (at least over here): 
1. Open unified map and route to any cache
2. Either stand still :) or disable GPS
3. Change routing style 
4. Toast of background recalculation will appear, but apart from the routing style symbol no updates will happen in map, neither routing line nor distance will change
5. Move a bit :) or enable GPS 
6. After a few seconds the new route will be displayed 

BTW: Performing the same with individual route between two manual targets works perfectly fine. Guess there is an explicit refresh after changing the routung style.

**Comment by MagpieFourtyTwo** [comment]
New finding: Recalculation (resp. refresh in map) will not happen, *until current GPS location changes.*

Of course it doesn't matter if the change has happened because of signal hopping or real position changes, but if you (or your signal) don't move, you will wait forever, the route will not be updated in map.

Absolutely reproducible scenario (at least over here): 
1. Open unified map and route to any cache
2. Either stand still :) or disable GPS
3. Change routing style 
4. Toast of background recalculation will appear, but apart from the routing style symbol no updates will happen in map, neither routing line nor distance will change
5. Move a bit :) or enable GPS 
6. After a few seconds the new route will be displayed 

BTW: Performing the same with individual route between two manual targets works perfectly fine. Guess there is an explicit refresh after changing the routung style.

Addendum: With GPS active and de facto no (real) position changes at all, there are a lot of unneeded refreshes (and most probably even route recalculations, I guess) which make the route flicker (and most probably waste a lot of energy, too).  Looks as if there is a recalculation on every single location change, even after the smallest. Wouldn't it be possible to add a minimum location delta until next recalculation or update takes place? The way it is now looks a bit ... nervous. :)  And in the very most cases a few meters plus or minus will not change the route in a senseful way anyway, IMHO.

**Comment by moving-bits** [comment]
PR #15736 addresses the last finding: Route to current navigation target does not update on changing routing mode if GPS is disabled

**Comment by MagpieFourtyTwo** [comment]
Seems as if this one is fixed meanwhile, at least had no obvious scenarios like the described anymore, thus let's close here.
