### ISSUE TITLE
Invalid signature for method java.util.function.BiFunction

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#15660]
seen at CI for the release build in https://ci.cgeo.org/job/cgeo%20release/147/console:
~~~
22:29:29  > Task :main:l8DexDesugarLibBasicRelease
22:29:29  Info: Invalid signature '<V:Ljava/lang/Object;>(Ljava/util/function/Function<-TR;+TV;>;)Ljava/util/function/BiFunction<TT;TU;TV;>;' for method java.util.function.BiFunction java.util.function.BinaryOperator.andThen(java.util.function.Function).
22:29:29  Validation error: A type variable is not in scope.
22:29:29  Signature is ignored and will not be present in the output.
~~~

**Comment by bekuno** [comment]
The `Task :main:l8DexDesugarLibBasicRelease` was new on CI build 143 with the error visible in https://ci.cgeo.org/job/cgeo%20release/143/console. 
The update of `com.getkeepsafe.dexcount:dexcount-gradle-plugin:4.0.0` was already before buil 142.

**Comment by bekuno** [comment]
Intruducing the `coreLibraryDesugaring` and update to the current version was before build 142.

**Comment by eddiemuc** [comment]
No idea what this means. But it seems to be an info only, what errorness effect is caused by it?

We can try to replace all usages of class `java.util.function.BiFunction` with our own `Func2` class if there's a problem.

**Comment by moving-bits** [comment]
@bekuno 
Can we close here?
