### ISSUE TITLE
Quick filter not working properly on mapped lists

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15661]
### Describe your problem!

Reported on support mail and reproducible for me with nightly build 2024.04.24-NB

When changing visible cache types via quick filter on a mapped list only the first change seems to be applied.

### How to reproduce?

- Have a list with at least one found cache, one offline logged cache, one archived caches and one unfound cache
- Map the list
- Open quick settings and e.g. disable archived caches (not to be shown)
- The archived caches is filtered out correctly
- Open quick settings and enable archived caches again (to be shown)

(Same sequence applies also to other filters (found, offline logged))

### Actual result after these steps?

Archived caches still hidden

### Expected result after these steps?

Archived caches should be shown again corresponding to the quick filter setting

### Reproducible

Yes

### c:geo Version

2024.04.18

### Additional Information

Problem is specific to mapped lists and does not happen on a live map as fas as I tested

Support ticket 300052

**Comment by murggel** [comment]
Probably fixed with PR #15659
