### ISSUE TITLE
UnifiedMap: create UDC dialog missing checkbox for list selection

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15662]
### Tell us your idea!

A user requested to have the ability to store a newly created UDC via long tap on live map into his "last used list".
As I guess this can be can be complex to implement and maybe undesired for other users, I suggest a slightly different but IMHO logical approach.

### What solution would you suggest?

If a user maps a list and on that mapped list creates a UDC via long tap on map, this UDC should be stored onto the list, which is currently mapped instead of onto the default list.

### Is there an alternative?

Leave as is

### Additional Information

Support ticket 707514

**Comment by ztNFny** [comment]
there should be a "use current list" checkbox in the UDC-creation dialog to do just that?
![image](https://github.com/cgeo/cgeo/assets/1258173/170eadc7-c8ab-41a1-8f95-e0f244cfedcf)

**Comment by ztNFny** [comment]
UnifiedMap bug, the checkbox is ok on old maps, missing on Unified
![Screenshot_2024-04-26-14-30-43-39_a916ceb0c8a82619faeb76fe6b8ae997.jpg](https://github.com/cgeo/cgeo/assets/1258173/1070a618-f173-4770-827b-76e65572bfcb)

**Comment by ztNFny** [comment]
> There is no dialog at all on creation via long tap on the map.

Dialog is there for me

**Comment by moving-bits** [comment]
"use current list" dialog is shown when map is displaying a list currently. Due to different data structures (and using an empty default placeholder in UnifiedMap) this does not work for UnifiedMap currently. PR #15663 will fix this.

**Comment by moving-bits** [comment]
fixed with #15663
