### ISSUE TITLE
Compact icons not working

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#15679]
### Describe your problem!

Compact icons are not working, even when forced. (unified map)

### How to reproduce?

1. Open map
2. Enable compact icons

### Actual result after these steps?

Regular large icons shown.

### Expected result after these steps?

Compact icons shown.

### Reproducible

Yes

### c:geo Version

2024.05.01-NB-458499f

**Comment by SammysHP** [comment]
Apparently the setting (even automatic switching) is only applied after restarting the app.

**Comment by moving-bits** [comment]
- not reproducible for me with current release 2024.04.25 or current state of `release` branch
- but reproducible with current master as of today

According to `git bisect`, 72c70310e81d4977fbea1ef7ce1009a6be047c52 seems to be the first "bad" commit, although I have no idea ad hoc, what's causing it to fail.
