### ISSUE TITLE
Have a setting to disable sleep if c:geo is active

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#1568]
Yesterday evening I left my fully charged phone in another room after checking something in c:geo. This morning it was off, battery completely empty. I now found what was going on: I left it with a cache list opened. We disable display timeout there, so it used display and gps the whole night.

If technically possible we should put the display disabling into the long running operations (import, download, ...) instead.

**Comment by Lineflyer** [comment]
This is rather old.
I think we should transform this into the general issue "Have a setting to disable sleep if c:geo is active" in general. This would be a straight forward setting like also other apps are using it.
Otherwise we should close this issue.

**Comment by Lineflyer** [comment]
Changed topic as suggested above.
