### ISSUE TITLE
Elevation chart for tracks exported from Garmin Basecamp does not get drawn

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#15683]
### Describe your problem!

When exporting a GPX track form Garmin Basecamp these contain elevation data (via the "ele" tag).

When importing such a track into c:geo, and then clicking on it, c:geo says that there are no elevation data available in this track.

### How to reproduce?

See above. Example file attached.
[Basecamp Export.zip](https://github.com/cgeo/cgeo/files/15188815/Basecamp.Export.zip)

### Reproducible

Yes

### c:geo Version

2024.04.25

**Comment by eddiemuc** [comment]
I assume this is because the elevation info for the chart is not taken from the gpx but from the loaded BRouter tile data (if there is one). Don't think the idea of taking elevation info from GPX files into account has crossed our collective minds yet :-) But it would be a valid FR imho.

**Comment by dcjkfgdjhd** [comment]
Ah, that makes a lot of sense then. 😉

Yes, it would make a lot of sense to support embedded height data from the GPX files.

As a temporary fix, how can I get such BRouter tile data? I am using Freizeitkarte. Does BRouter need to be installed for this to work?

**Comment by moving-bits** [comment]
No, BRouter does not have to be installed, c:geo comes with its own. But you need to
- activate internal routing (by going to settings => routing/navigation => use internal routing)
- and download the routing tile data (at least once initially) by using the map's menu entry "check for missing routing data"

If you prefer the external BRouter, skip those steps and open external BRouter to download the appropriate tile data manually.

**Comment by dcjkfgdjhd** [comment]
I meet all these requirements for internal (I just rechecked to make sure) and I still don't get an elevation chart.

**Comment by dcjkfgdjhd** [comment]
Ah, it only works for routes, NOT for tracks.

**Comment by moving-bits** [comment]
PR #15691 adds reading of elevation data on GPX track import

**Comment by dcjkfgdjhd** [comment]
Thanks a lot for the quick fix! 😀
