### ISSUE TITLE
Support öpnvkarte.de as map source

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15686]
User request on support (ticket 454010): Support https://www.öpnvkarte.de/ as map source.

According to their landing page, using their material is free of charge, only requires a copyright notice.

Unclear, though, is supported map format, whether they support either a compatible tileserver or provide a downloadable .map source. Before diving into implementation this would have to be clarified with their contact (contact data to be found on their landing page).

**Comment by dcjkfgdjhd** [comment]
I had suggested that some months ago  #(15041) and had even written to the person running this project but never received a response.

I agree that it would be super useful, and also encourage environmentally friendly geocaching.

**Comment by moving-bits** [comment]
Thanks for the cross-link, had missed that. So let's close here as duplicate.
