### ISSUE TITLE
Outdated c:geo Version on Malavida

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15688]
Through a spam-like support ticket I became aware that a very outdated spanish version of c:geo is available on a website called Malavida. See link:

https://www.malavida.com/es/android/s/c:geo

Is that someething we can safely ignore?

**Comment by fm-sys** [comment]
> Our team at the University of Cambridge are looking into modded Android apps. We are contacting you as our research has uncovered modded versions of one or more of your apps on third-party markets. Further information on your apps can be found at the end of this email. [...]

I've probably got exactly the same mail a few days ago for one of my apps, also claiming that it was listed on Malavida.

We definitely don't support that store for c:geo officially.

**Comment by bekuno** [comment]
The APK for download at malavida is the (nearly) same as our APK at github.
The only difference I found is the file in the APK with the APK name, which is really not the same.

We can contact them via their contact form https://www.malavida.com/en/contact and refer them to our apk source at https://github.com/cgeo/cgeo/releases to ensure they are using the latest version.

**Comment by eddiemuc** [comment]
Seems not to be too much interest in this :-) I will close here, feed free to open any time.
