### ISSUE TITLE
Strange double track segment in GPX export

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#15684]
### Describe your problem!

When exporting a GPX track from c:geo, the code is strange, for example:

```
<trk>
    <name>c:geo individual route 2024-05-02T03:16:57Z</name>
    <trkseg>
      <trkpt lat="47.50146" lon="11.137798">
        <name>COORDS! N47 30,088 E11 08,268</name>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="47.501479" lon="11.137816" />
      <trkpt lat="47.501514" lon="11.137737" />
      <trkpt lat="47.501573" lon="11.137696" />
      <trkpt lat="47.501622" lon="11.137606" />
      <trkpt lat="47.501724" lon="11.137559" />
```

I don't understand why there is this strange first track segment with only one point.

**One big issue with this is, that Garmin Connect cannot import such GPX files.
Either it only imports the first, quasi empty track segment. Or it bugs completely and does not import at all.**

I experimentally removed this first track segment, and now Garmin Connect can import. 

_(I just got my first Garmin GPS watch, so I am not yet sure if this is the only reason why c:geo exports fail in Connect, but in this one example, the extra track segment definitely was the cause, and it worked after removing that.)_

### How to reproduce?

See above.

### Reproducible

Yes

### c:geo Version

2024-04-25

**Comment by moving-bits** [comment]
this is actually the first item of your individual route. c:geo stores a route internally by segments, with one segment per item of your individual route. The first segment contains of the route's first item only, then each following segment has the next item as last point of that segment, and the points from the last point of the previous segment to the last point of this segment as points of that segment.

I'll look into it, whether I can merge the first near-empty segment into the second segment.

One follow-up question, though, before I dive into that: If you create and individual route with, let's say, five items, the resulting GPX will have five segments. If you delete the first one (single point only) - will then your Garmin cope with the rest (four segments)? Or can it handle single-segment GPX tracks only?

**Comment by dcjkfgdjhd** [comment]
> One follow-up question, though, before I dive into that: If you create and individual route with, let's say, five items, the resulting GPX will have five segments. If you delete the first one (single point only) - will then your Garmin cope with the rest (four segments)? Or can it handle single-segment GPX tracks only?

OK, I tested this. Garmin Connect (the Android app used for connecting to the watches, not the watch itself) will always just see the first track segment and ignore the rest.

**Comment by moving-bits** [comment]
PR #15719 will change c:geo to use only a single track segment on exporting an individual route as track
