### ISSUE TITLE
Undo New Log-Symbol in Current Nightly

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#15709]
### Tell us your idea!

The former pencil has been replaced with a smiley in one of the last nightly releases.

Why?

Not all logs you will provide for a cache will result in a Found It = Smiley.

Placing a note or something else is not being reflected by a smiley, while an universal pencil is relfecting any log type. 

### What solution would you suggest?

Switch smiley back to former pencil

### Is there an alternative?

no, the smiley is just irritating

**Comment by bekuno** [comment]
See #15619 and #15646

**Comment by rouroni1** [comment]
My two Cents about this subject.

And why not:
Revert to the pencil to do a log (found, dnf, etc...), and the option to select a list, use one icon with list with pencil?
Example:
https://pictogrammers.com/library/mdi/icon/playlist-edit/

After all when we press the bottom pencil icon, it's to change the list where we want to assign the geocache.

**Comment by fm-sys** [comment]
I agree that using the same icon for two actions is quite confusing. However, the "change lists" icon is the one which is confusing IMHO.

![grafik](https://github.com/cgeo/cgeo/assets/64581222/78017263-3389-41b1-8c51-6ff7e5c28b26)


While the perfect material icon doesn't exist out of the box, I would recommend a mixture of those two material icons for "edit lists":

![contract_edit_24dp_FILL0_wght400_GRAD0_opsz24](https://github.com/cgeo/cgeo/assets/64581222/236fa08a-dd7a-434d-9a4c-6bbc71ee9cbb)

AND

![playlist_remove_24dp_FILL0_wght400_GRAD0_opsz24](https://github.com/cgeo/cgeo/assets/64581222/9b4c26b5-5dd2-4224-8582-bb1c48c708c8)![playlist_add_check_24dp_FILL0_wght400_GRAD0_opsz24](https://github.com/cgeo/cgeo/assets/64581222/d70c6821-a11b-4630-b3e2-4fc7da0f4d50)![playlist_add_24dp_FILL0_wght400_GRAD0_opsz24](https://github.com/cgeo/cgeo/assets/64581222/866059d2-cb3d-4a75-9a40-ad910d4b10e1)

___

As a second step, we can discuss which icon to use for logging. May it be the old icon, a totally different one, or stay with the current one.

**Comment by fm-sys** [comment]
Edit: The material icon I was thinking of does actually exist, had just used the wrong keyword:

![edit_note_24dp_FILL0_wght400_GRAD0_opsz24](https://github.com/cgeo/cgeo/assets/64581222/797e24c6-674d-4f08-8549-d27d43b7edfb)

**Comment by wolverine007** [comment]
> Edit: The material icon I was thinking of does actually exist, had just used the wrong keyword:
> 
> ![edit_note_24dp_FILL0_wght400_GRAD0_opsz24](https://github.com/cgeo/cgeo/assets/64581222/797e24c6-674d-4f08-8549-d27d43b7edfb)
> 

like the new variant for list management.

So we could stay with the well known pencil at both locations.

**Comment by wolverine007** [comment]
> The pen icon has always been used for different buttons (log and "edit" for several things (offline lists, note, ..)). On most devices there's no room for 4 toolbar icons which have been visible in CacheDetails for long time, so the use of the icon for logging is not that visible.
> 
> As for the icon, I'm using a smiley instead of the pen in my builds:
> ![image](https://github.com/cgeo/cgeo/assets/1258173/639e0481-80ca-4f70-88ef-019139f4b79f)
> 

Maybe a different topic, but somehow linked with each other...

Any clue what is the magic number to get 4 icons in the pop up?

My device is offering a screen resolution of 2400x1080px, while a friend of mine is able to see 3120x1440px on his device.

He could see 4 icons (top pic), while my device is only able to show 3 icons.

But if you compare the two screens, you will see that there is plenty of room for a forth icon on my device as well:
![PhotoCollage_20240508_132835203.jpg](https://github.com/cgeo/cgeo/assets/4508228/b7b4597d-444a-4a8d-aead-5d87fd0d6023)

**Comment by Lineflyer** [comment]
> Any clue what is the magic number to get 4 icons in the pop up?

AFAIK the Android system decides based upon criteria unknown to me (seemingly not only the resolution).
From your screenshots I guess also the text size is a bit different.

**Comment by fm-sys** [comment]
BTW, the TB activity still uses the old icon, which is pretty inconsistent. However, a Smiley wouldn't make sense for TB's...

![grafik](https://github.com/cgeo/cgeo/assets/64581222/4f8c28cf-c757-409f-afa6-11951cca84cb)

**Comment by fm-sys** [comment]
what about this icon?

![grafik](https://github.com/cgeo/cgeo/assets/64581222/9882c00d-bc05-41ca-a911-20531e844684)

**Comment by fm-sys** [comment]
Let's do a quick poll (please vote for one or more icons):

please react with
- 🎉 comment icon
- 🚀 pencil icon
- 😃 smiley icon

**Comment by moving-bits** [comment]
additional remark from my side: icon for log action should be the same for "log cache" and "log trackable", IMHO

**Comment by moving-bits** [comment]
Discussion & decision in today's dev meeting: There are pros and cons for both variants, so let's stay with the variant users of today's release are used to: pencil icon.
