### ISSUE TITLE
PN: "Save PN" and "Add/Update Waypoints" result in annoying window scroll

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15705]
### Describe your problem!

After editing and saving a Personal Note, the listing always scrolls up - seems as if c:geo tries to find the beginning of the PN (or any other seemingly meaningful place to scroll to), but fails completely in doing so and ends up in a seemingly random place. Especially in Multis with a lot of stages, thus long listings (which usually even end up in longer PNs, making the problem even worse), this is extremely annoying, cause after every single stage of the Multi you have to scroll three times through the whole listing plus the whole length of the PN to note down, save and upload your new findings:
1. scroll down to PN, to write your new findings down and, then save ... c:geo jumps up 
2. scroll down to use ``Add/Update Waypoints`` ... and after you pressed the button, c:geo jumps up again
3. scroll down to finally upload PN

Did a Multi with 24 stages this weekend - now count the many senseless scroll actions ... ;)

### How to reproduce?

Just do a long Multi with a bunch of stages and ...
a) keep your stage findings as well as the newly calculated coordinates in the PN 
b) store waypoints (and perhaps calculation variables and formulas) into the PN
c) upload all this after each stage, to have it saved on the server, just in case your phone breaks

### Actual result after these steps?

You have to scroll, scroll, scroll ...

### Expected result after these steps?

On save of PN and after saving waypoints to PN, window position should just stay where it is: At eh very end (cause there are the buttons that matter, plus recently added text will be at the end anyway.

### Reproducible

Yes

### c:geo Version

2024.05.07-NB-e2cd809

**Comment by bekuno** [comment]
duplicate of #15673 ?

**Comment by MagpieFourtyTwo** [comment]
Yep,you're right. Although #15673 misses the ``Add/Update Waypoints`` it is in fact the same issue.
