### ISSUE TITLE
GC website change: Coordinate entry and parsing experience

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#15715]
From https://forums.geocaching.com/GC/index.php?/topic/401570-release-notes-website-coordinate-entry-and-parsing-experience/:

This release addresses ongoing community feedback that inaccurate coordinates are an obstacle to a positive game experience, both for cache hiders and finders.

This latest web release improves the following experiences:
- The cache submission process
- The cache edit page
- The Update Coordinates log type

**Comment by eddiemuc** [comment]
I believe those changes only affect owner functions (e.g. creating a new or editing an owned cache listing). Thus they should not affect c:geo?

**Comment by moving-bits** [comment]
Yes, that's owner-related only, thus not affecting c:geo

**Comment by bekuno** [comment]
Ok, then we can close the issue.
