### ISSUE TITLE
storage.DataStore::loadTrackable() bug

### ISSUE THREAD

**Issue by rapotek** [cgeo/cgeo#15727]
### Describe your problem!

`storage.DataStore::loadTrackable` method retrieves from db: "updated", "tbcode", "guid", "title", "owner", "released", "goal", "description" fields only, then calls `storage.DataStore::createTrackableFromDatabaseContent` which requires additional "log_date", "log_type", "log_guid" fields. This leads to an `IllegalArgumentException`: column (...) does not exist.

### How to reproduce?

1. Activate debug log
2. Select f.ex. opencaching geocache with non-empty inventory
3. Choose a trackable from inventory to see its details
4. The message about c:geo can't find trackable is displayed
5. Generate  logfile

### Actual result after these steps?

In logcat there is `java.lang.IllegalArgumentException: column 'log_type' does not exist. Available columns: [updated, tbcode, guid, title, owner, released, goal, description]`

### Expected result after these steps?

No exception generated, details about trackable displayed.

### Reproducible

Yes

### c:geo Version

2024.04.25

**Comment by moving-bits** [comment]
Thanks for the detailed info. PR #15728 adds the missing columns to the database query.
