### ISSUE TITLE
multiple titles for areas with titles (minor)

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#15734]
### Describe your problem!

If I zoom into areas with a title (here "KGV Braunschweiger Schrebergartenverein"), in the offline map the title appears multiple times. At the online OSM map this is better.

### How to reproduce?

go to map
zoom into area (e.g. lake)
the title quite often and distributed over the area.
i do not know this is from an external library or explicitly programmed in cgeo.
![IMG_20240519_134121](https://github.com/cgeo/cgeo/assets/43813636/bbe14577-ac4d-4036-aaee-f1fd686dafc0)
The user defined cache is at N 52° 14.903' E 010° 34.060'

### Expected result after these steps?

Title of area is only shown once or twice

### Reproducible

Yes

### c:geo Version

2024.05.11-NB-c926353

**Comment by moving-bits** [comment]
This is part of the external library, Mapsforge VTM in this case (UnifiedMap). If you start zooming in/out or rotating the map, you will notify more or less labels being displayed, depending on available space and number of elements being displayed. It also depends on the theme and theme settings being used (which influences the number of elements of the map).

**Comment by moving-bits** [comment]
Closing as "can't fix" (at least not by the c:geo team).

Also UnifiedMap VTM might be removed in the near future, being replaced by UnifiedMap Mapsforge (which is already available in the nightly versions as alternative).
