### ISSUE TITLE
Move "Delete log" menu item away from more often used menu items

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15749]
### Tell us your idea!

Feature request by several users on support and Facebook.
E.g. ticket 181948:

please move the "delete" menu to avoid unwanted action when writing in my journal if I'm on a bus or in the back of a 4X4 car. THANK YOU very much Best messages

### What solution would you suggest?

![grafik](https://github.com/cgeo/cgeo/assets/949669/7108a694-1ef3-44fa-ba63-0504d941c608)

### Is there an alternative?

Have a "Are you sure?" confirmation when trying to delete the log.

**Comment by moving-bits** [comment]
Decision from today's dev call: Leave item position as is, but add a confirmation dialog

**Comment by fm-sys** [comment]
Just realized there already is a confirmation dialog!?

**Comment by eddiemuc** [comment]
> Just realized there already is a confirmation dialog!?

Sure there is :-) I wouldn't implement a "delete" function w/o a confirmation dialog

I thought the request was about "moving" the position of the delete in the menu

**Comment by fm-sys** [comment]
I would vote to close as "won't fix" in this case. This issue was about accidentally deleting logs, which seemly cannot happen. Maybe the used on support was just afraid there amy be no confirmation with out trying it?
