### ISSUE TITLE
Waypoint projection does not instantiate variables

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#15756]
### Describe your problem!

Using variables in waypoint projection (see #12600) does not create variables.

### How to reproduce?

1. Create a new waypoint
2. Set starting coordinates
3. Select "projection"
4. Enter variables in heading/distance
5. Save waypoint

### Actual result after these steps?

No variables were created in the variables page.

### Expected result after these steps?

Variables should be created in the variables page like it's done for the regular waypoint calculator. Additionally it would be nice to have the same quick access to variables as in the waypoint calculator.

### Reproducible

Yes

### c:geo Version

2024.05.11-NB-c926353

**Comment by murggel** [comment]
I will give it a try to look into it

**Comment by murggel** [comment]
Showing the variable in the EditWaypoint-Activity does not work correctly - I will check for it

**Comment by murggel** [comment]
Will be fixed with PR #16042
