### ISSUE TITLE
Lock map to true north orientation

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#15761]
### Tell us your idea!

I often accidentally rotate the unified map when zooming.

### What solution would you suggest?

It would be great if somewhere in the map settings box, there would be a "lock map to true north" option.

**Comment by murggel** [comment]
There is an option to disable the rotation in the menu - maprotation

![Screenshot_20240604-121311_cgeo.jpg](https://github.com/cgeo/cgeo/assets/70113341/fa472bd9-0b32-4027-aecb-4ea09fc546c5)


![Screenshot_20240604-121311_cgeo.jpg](https://github.com/cgeo/cgeo/assets/70113341/3e3eefc1-2a80-4869-aae2-85c935f533ef)

**Comment by dcjkfgdjhd** [comment]
Oops, thank you. I looked, not sure how I missed it.
