### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#15773]
Let's collect things which need to be done:

- [x] #15748
- [x] #15618
- [x] #15749
- [x] #15679
- [ ] #15502
- [x] #14424
- [x] #15900
- [x] #15904
- [x] #15925

Can probably be closed:
- [x] #15567

**Comment by moving-bits** [comment]
We have a couple of bugfixes pending on `release`, and `master` and `release` have diverged quite a bit over time, leading to merge conflicts quite regularly.

Therefore I propose to release a last bugfix update for the current series at the end of this weekend, and then start a new beta release from `master` a few days later. Will start with the bugfix release tomorrow evening if no one objects.

**Comment by moving-bits** [comment]
I'll start working on a new bugfix release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
I'll start preparing a beta version now:

- [ ] Empty `changelog_bugfix.md` on branch `master`
- [ ] Wait for a Crowdin cycle or trigger sync manually for branch `master`
- [ ] Merge the related Crowdin translation pull requests for branch `master`
- [ ] Delete outdated translations branch for `release`
- [ ] Fast forward `release` branch to HEAD of `master`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by Lineflyer** [comment]
@moving-bits 
We get support mails for a 2024.07.07 version. This version is however not listed on https://status.cgeo.org (neither deployment, nor production).
Is this version officially published, then we should fix the release status.

**Comment by moving-bits** [comment]
2024.07.07 got released as regular version, I have triggered notification now.

For beta version 2024.07.14 it took them more than two days to publish it, but now it's out in the wild as well. I just started reconfiguring some of the list names, love that new grouping function!

**Comment by moving-bits** [comment]
Starting an update for current beta:

- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
FYI: #15908 adds two more foreground service permissions to `AndroidManifest.xml` to fix #15900. I guess I will have to create separate videos of how we use that service types in c:geo (as I had to do for the first of them), so I will start a new beta version rather soon, probably tomorrow evening.

**Comment by moving-bits** [comment]
Starting to prepare a new beta version...

- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
FYI: Currently it takes between 1.5 and 2 days until a release gets published, probably due to the manual checks involved for some new API 34 Play Store requirements.

Current beta 2024.07.26-RC is now online. Still some quirks involved, though, but we still have about one month time until API 34 requirement sets in for new updates (meaning: we would not be able to publish an update based on current release [not beta] starting September 1st).

**Comment by moving-bits** [comment]
I'll start a new beta version:

- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
I'll start working on a new beta version:

- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Check/insert correct version name in `BranchDetectionHelper.java` on branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play on beta channel
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
As discussed in our last dev meeting:
If no one objects, I'll start preparing a new release (not beta update) this evening.

**Comment by bekuno** [comment]
I have proofread many languages, will do no more now.

**Comment by moving-bits** [comment]
Thanks. I will then start synchronization and work on preparing the release now:

- [ ] Check/insert correct version name in `BranchDetectionHelper.java`
- [ ] Wait for a Crowdin cycle or trigger sync manually
- [ ] Merge the related Crowdin translation pull requests for branch `release`
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter/X

**Comment by moving-bits** [comment]
Let's close here after today's release of 2024.08.19 feature release, and start a new cycle

**Comment by bekuno** [comment]
On the last CI release job, the ftp step did not work, see https://ci.cgeo.org/job/cgeo%20release/160/console.
~~~
00:20:36  + ftp
00:20:36  ftp: connect: Connection refused
~~~
@mucek4 Please check the ftp server.
