### ISSUE TITLE
Handling of Google Maps Styling Options

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15770]
### Tell us your idea!

While working on a ticket and creating PR #15768 I realized that Google Maps offers a wide range of very detailled styling options, including visibility and coloring for all sorts of elements on the map. Details can be found eg via Google's Map Style editor at https://mapstyle.withgoogle.com/:

![image](https://github.com/cgeo/cgeo/assets/6909759/240d2d87-ebfc-4214-87c9-14ad78aeff40)
![image](https://github.com/cgeo/cgeo/assets/6909759/3d447af8-1e9f-49e4-8a0f-bd00165984c2)

There are also some predefined themes available, which howeber seems to be just preconfigured using the same advanced option set.

As of today c:geo offers for GM a bunch of "Themes" which are technically just complete configuration sets out of the vast options available. Those are Default, NIght, Retro and High Contrast. Probably those were copied at the time from the then-available preconfigured themes? PR #15768 adds a new theme "Details" to this set.

It might be worth discussing whether we want to transport more detailled GM config options into c:geo, as we already do for OSM maps in Theme options.

### What solution would you suggest?

One suggestion would be to allow "theme options" for GM as we do for OSM to turn features of the map "on" or "off". OPtions would be e.g. "Attractions", "Business" etc. In contrast to OSM we would have to offer a three-way-select (visibility "on", "Off" or "inherit from theme"). Also we would have to respect the hierarchy of GM (e.g. an option "Point of interest" sets visibility for all POIs while "Business" may override this with another visibility setting for Business-POIs)

We could also allow to set different colors, fills and such for different elements, but this would go too far IMHO. Up to discussion of course

### Is there an alternative?

Not to do anything

**Comment by moving-bits** [comment]
Although I'm rarely using GM maps (*) this sounds reasonable to me. Quick thoughts:
- let's try to find some categories (reasonable sets of config options) instead of offering every single option
- stay away from colors (except for high contrast / color blind options)

(*) missing offline option + not enough details (ways etc.) compared to OSM. But maybe the second issue could be resolved by those options?

**Comment by eddiemuc** [comment]
I am not using GM much too, except for satellite map. But other c:geo users may have different preferences

> (*) missing offline option 

Google Maps offers offline support. Does anyone now if our Google Map API automatically uses offline stored GM data too if it is available on the device?

> not enough details (ways etc.) compared to OSM. But maybe the second issue could be resolved by those options?

You can try out the new theme "Details" I created with PR above. But I doubt it.
