### ISSUE TITLE
Move "follow me" button on map from toolbar to map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15774]
Idea from today's dev meeting:

Move the "follow me" icon from the toolbar to the map area, below or beside the compass rose.

Seems to be a more logical position, and gives more space in the toolbar for the "live mode" button (which seems to be forced to the overflow menu since the list chooser changes).

**Comment by ztNFny** [comment]
I'm all for it. But before doing it maybe we should come up with a plan for what the map screen should look like - there's been repeated discussions about where/when to show compass and about the map options buttons, as well as bugs (compass being hidden behind navigation).

I highlighted some of the problems in this image:
![image](https://github.com/cgeo/cgeo/assets/1258173/389545dd-0a10-4ffc-bbfe-37ae7b8cf1db)
(For compass I submitted a PR some time ago but it wasn't merged https://github.com/cgeo/cgeo/pull/13063)

**Comment by moving-bits** [comment]
Here's a proposal for further discussion:

|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Screenshot&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|Proposed changes|
|---|---|
|![image](https://github.com/user-attachments/assets/e7eecf4c-d303-4e3b-9693-d43575f28733)|(Screenshot at the left is just a rough sketch, see description below for details)<br /><br /><ul><li>Scalebar and copyright notice stay as is<br />(left + bottom aligned; same left padding as zoom controls have as right padding)</li><li>zoom controls move a bit down<br />(same paddings as scalebar)</li><li>"map quick settings" and "route/track quick settings" move to the right<br />(same bottom padding as the others, but keep some distance to zoom controls for easier handling)</li><li>"follow me" button is moved from toolbar to the map, above zoom controls<br />(same distance to zoom controls as they have to the quick settings buttons)</li><li>this makes room in the toolbar to always display the "toggle live mode" button</li><li>"compass rose" (if [rotation features are enabled](https://github.com/cgeo/cgeo/issues/15775#issuecomment-2227273920)) would appear at a fixed position above the "follow me" button<br />(same right padding as zoom controls / "follow me" button; same padding to "follow me" as the two quick settings' buttons have between each other)</li><li>distance infos stay as is</li><li>all those buttons have the same size, form and color</li></ul>|

**Comment by fm-sys** [comment]
For reference: compass rose is jumping in Google Maps as well. I don't see a real problem with it...

![grafik](https://github.com/user-attachments/assets/9dcef185-a817-437b-ac47-f4b50bca179f)

**Comment by moving-bits** [comment]
As discussed in our last dev meeting: Here are some more mockups:

|mockup 1|mockup 2|
|---|---|
|![image](https://github.com/user-attachments/assets/e7eecf4c-d303-4e3b-9693-d43575f28733)|![Mockup1](https://github.com/user-attachments/assets/6ba567de-d5f6-4569-acb0-a38a8e4ba116)|

|mockup 3|mockup 4|
|---|---|
|![Mockup2](https://github.com/user-attachments/assets/393a4a3c-f646-4d3b-825c-37da4567473e)|![Mockup3](https://github.com/user-attachments/assets/631aeffa-0a18-40fd-a95a-4ff4fe854cd9)|

|mockup 5|-|
|---|---|
|![Mockup4](https://github.com/user-attachments/assets/50053f13-7775-4d88-92b4-7721c6ee05bf)|

- mockup 1
  - see above: https://github.com/cgeo/cgeo/issues/15774#issuecomment-2227302028
- mockup 2
  - similar to mockup 1, but move compass rose + "follow me" button up
  - pro: buttons are relatively close to where they are now
  - con: cannot be used one-handed
- mockup 3
  - move +/- buttons a bit up
  - position compass rose + "follow me" button at the left, same height as new position of +/-
  - keep quick settings buttons at today's positions
  - pro: symmetrical view; reachable with one hand
  - con: unusual position especially for "follow me"
- mockup 4
  - position compass rose + "follow me" button at same height as "+" button, but to the left of it
  - pro: compact action block
  - con: grouping of unrelated buttons (compass rose + "follow me" close to quick settings buttons)
- mockup 5
  - position all action buttons at the map's bottom, move scalebar a bit up to make room for it
  - keep quick settings buttons at today's positions
  - pro: very compact, leaves maximum map space
  - con: some buttons probably hard to reach one-handed

**Comment by ztNFny** [comment]
I vote for 2. The con i don't see - the buttons are closer to bottom right than they are today and the more frequently used toolbar is further away.

**Comment by murggel** [comment]
My favorite is mockup 2, let's see, if the mentioned  cons are bothering someone

**Comment by fm-sys** [comment]
+1 for mockup 2

**Comment by SammysHP** [comment]
From these I also vote for 2.
