### ISSUE TITLE
Sorting "nearby" caches by "hidden date" leads to caches very far away

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15788]
Reported by support Ticket #669494, reproducible for me.

When you use "nearby" search from main screen, then sort the result by "hidden date" in ascending order, then results are shown which are very far away (and also very old, in my case eg GC30 hidden in the year 2000).

I assume the underlying issue is that we don't set a "distance limit" for nearby search. Question is: what should that limit be? 2 kilometers maybe?

**Comment by fm-sys** [comment]
Funny side effect :)

But I would say this is intended. Imagine being in Africa and the next cache is 300km away... Not every region is as dense as Europe. 

I honestly really much like the fact that there is a way in cgeo to list the oldest still active geocaches.

**Comment by eddiemuc** [comment]
> I honestly really much like the fact that there is a way in cgeo to list the oldest still active geocaches. 

Me too. But there is an intended way of doing things like that in c:geo:
- go to "search"
- choose " search by filter"
- leave the filter empty and start search
- in the result list, sort by "hidden date" 

Not sure if this intended behavior of "nearby" search tough. But I have to admit I wouldn't know any other "easy" solution than to pass a distance limit with the search request.

If you are in an area where nearest cache is eg 100km away, couldn't it be argued that there is simply no cache "nearby"? I guess it depends how the term "nearby" is defined.

**Comment by fm-sys** [comment]
> > I honestly really much like the fact that there is a way in cgeo to list the oldest still active geocaches.
> 
> Me too. But there is an intended way of doing things like that in c:geo:

I believe both ways are not really intuitive for Jon Average :)

And I never use "Nearby" myself, so I cannot really say for sure how people are using it. Why should someone sort the result by "hidden date" at all?

**Comment by eddiemuc** [comment]
> However I never use "Nearby" myself, so I cannot really say for sure how people are using it. Why should someone sort the result by "hidden date" at all? 

User on support claims to use this to check for new caches in his area

**Comment by fm-sys** [comment]
Still the question remains what's considered "his area"...

**Comment by moving-bits** [comment]
Somewhat related to #15696

**Comment by eddiemuc** [comment]
While attempting to fix this "bug" I found out (via code...) that we already have a setting to set the nearby max distance:

![image](https://github.com/cgeo/cgeo/assets/6909759/cd569033-6bd2-47d4-b0da-a981553e4166)

Again what learned...

I will close here and inform the user on support
