### ISSUE TITLE
Strange overlay artefacts on openstreetmap.org 

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15793]
Support Ticket #352703 

The user sees strange overlay artefacts when using openstreetmap.org using the OLD map (not unified map). See following screenshots. I can reproduce this.

![image](https://github.com/cgeo/cgeo/assets/6909759/5b8a411a-f9be-4f29-93b7-276cc2d3559a)
![image](https://github.com/cgeo/cgeo/assets/6909759/e01b0f40-7a68-4c90-be21-89bec4233a93)
![image](https://github.com/cgeo/cgeo/assets/6909759/39605805-54b2-41d5-a52b-2ae196cf93e1)

* cgeo-Version: 2024.06.02
* happens since around two days
* only for openstreetmap.org (not in eg openstreetmap.de)
* reproducible for the user on another device
* happens only on certain zoomlevels (around 6th if you start counting when zooming out from most-zoomed-in state)
* happens on many places e.g. around GC4ETB1

Probably related to failures on server side on openstreetmap.org. I file this issue to keep an eye on this.

Anyone has another idea what is happening here?

**Comment by bekuno** [comment]
Yesterday I saw the same on a web based map.
So probably errors in the OSM database.

**Comment by devemux86** [comment]
https://community.openstreetmap.org/t/the-osm-standard-tile-layer-looks-wrong-white-lines-abusive-comments-etc/111583

**Comment by eddiemuc** [comment]
Wow, thanks for the info. I think I can close here.

**Comment by SammysHP** [comment]
This is part of a wave of vandalism in OSM. They kindly asked to not share screenshots of the vandalized maps because of the included insults.

https://community.openstreetmap.org/t/update-13-06-2024-neue-vandalismuswelle-strassen-kreuz-und-quer-teilweise-namen-geandert/113287
