### ISSUE TITLE
Copy-pasting listing text with embedded images is incomplete and produces "[OBJ]"

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#15797]
### Describe your problem!

When copying a listing text that includes images, and pasting it into the personal cache note, this happens:

![2024-06-16 11 18 36](https://github.com/cgeo/cgeo/assets/54892606/d1d41f36-b09d-4a0c-9a96-14155a8e694f)

You only get the text _after_ the last image, everything else is missing. And the image becomes "[OBJ]".

### How to reproduce?

See above.

### Reproducible

Yes

### c:geo Version

2024.06.02

**Comment by eddiemuc** [comment]
I can confirm that images are copied as "OBJ" signs. This is nothing we can solve but just the way images are represented in the internal "text form" of the cache listing.

I cannot confirm that text above image(s) is not copied. I tried with listing of GC2KA8P and copy/paste seems to work as expected.
![image](https://github.com/cgeo/cgeo/assets/6909759/58de2290-4049-4b90-9a8e-1d1f641c0370)
![image](https://github.com/cgeo/cgeo/assets/6909759/7daa3167-4406-4856-be03-b0a92b620082)

**Comment by dcjkfgdjhd** [comment]
Strange. 

As you can see in the screenshot above, it did not work for me with the listing of https://coord.info/GCR3HV

But testing it again now, it works correctly for me as well now, also for that same listing.
