### ISSUE TITLE
Indicate selected cache on map

### ISSUE THREAD

**Issue by TrollBlox** [cgeo/cgeo#15801]
### Tell us your idea!

When a cache is selected in the map view, it should indicate which one is selected (when the bottom panel is open). It can get confusing if a lot of caches are loaded on the map. The official Geocaching app has this, where the circle icon switches to a pin.

### What solution would you suggest?

It could grow larger, change the color, or get an outline. Basically anything would work.

**Comment by TrollBlox** [comment]
That's a good question, and something I should have clarified. I meant when the bottom window is open showing a preview of the cache details. I'll edit my issue.

**Comment by TrollBlox** [comment]
That's a good question, and something I should have clarified. I meant when the bottom window is open showing a preview of the cache details. I'll edit my issue.

**Comment by moving-bits** [comment]
We had an orange marker in the past, circling (surrounding) the main cache marker symbol. This could be used here as well. We would need three of them, though, to match the three variants of cache markers (round, square, hexagonal).

**Comment by TrollBlox** [comment]
I thought there used to be something like this. Why was it removed?

**Comment by ztNFny** [comment]
> We had an orange marker in the past, circling (surrounding) the main cache marker symbol. This could be used here as well. We would need three of them, though, to match the three variants of cache markers (round, square, hexagonal).

The orange marker used to indicate imprecise coordinates as a basic member. Nothing to do with active. 

I am against modifying the marker, it would double the number of markers in cache and we already have huge performance problems because if to many markers already today

**Comment by moving-bits** [comment]
I was thinking of having three (*) new files (ring, outlined square, outlined hexagon) which will be put on the map in addition to the cache marker (z-index TBD). So no new markers, but just the colored outline that marks the active cache.
(* Ok, if we want to supoprt compact icons as well, we'll have six new files)

**Comment by ztNFny** [comment]
> I was thinking of having three (*) new files (ring, outlined square, outlined hexagon) which will be put on the map in addition to the cache marker (z-index TBD). So no new markers, but just the colored outline that marks the active cache.
> (* Ok, if we want to supoprt compact icons as well, we'll have six new files)

If that works? They have to be placed exactly below the marker, if it's possible to get that position ok. You can implement with dummy images, ping me once you have an implementation and I'll add the "nice" markers.

**Comment by moving-bits** [comment]
I have created a "quick & dirty draft", see #15870, indeed running into the positioning problem, as my icon gets bottom-aligned to the cache marker's outline, above the visual part of the pin - something I would have expected different. Need to investigate further, if a centered outline is preferred.

**Comment by MagpieFourtyTwo** [comment]
Just recognized the new "outline" resp. highlighting in the changelog - nice idea, but the outline should take the icon size into account. Just played around with ```Cache Icon Scaling`` and ``Map Scale Factor`` and with MSF=140 (due to high resolution display) I had to set CIS to 95 to see at least a small glow.  Perhaps the highlighting can refer to current icon size plus 20 % ... or so? And if it's a bit out of center ... hey, who really cares?  ;)

**Comment by moving-bits** [comment]
> the outline should take the icon size into account

Good point, I'll look into it

> Just played around with `Cache Icon Scaling` and `Map Scale Factor` and with MSF=140 (due to high resolution display)

MSF should not affect it - MSF is available for "old" Mapsforge only, item highlighting for UnifiedMap only

> And if it's a bit out of center ... hey, who really cares? ;)

me :-)

**Comment by moving-bits** [comment]
Scaling issue + crash for highlighting waypoints fixed with #15920

**Comment by MagpieFourtyTwo** [comment]
> crash for highlighting waypoints fixed

Hihi - that's exactly what I noticed this morning - and in the very moment I wanted to file an issue (after I finally managed to nail the reason), your fix comment arrived.  Guess you finally reached the stage where errors are fixed right when they occur?  Big deal!  Please let me know the item number of your crystal ball - must have one of these!  😎 😉

TMALSS: Thx a lot!  😉👍🏼

**Comment by moving-bits** [comment]
🤣 

It's been you who triggered my crystal ball by pointing out the scaling issue - which has separate settings for caches and waypoints, so I needed to test both - crash!

PR has been merged and will be included in next nightly

**Comment by MagpieFourtyTwo** [comment]
Waypoint selection is working again, thx, but IMO the aureole is a bit unobtrusive, I would like it better if it would be bigger.

WRT "out of center":  Perhaps calculation of a bigger aureole could be based on the current one,
i. e. calc the circle based on the lowest point of the icon (like it seems to be right now),
then take it's center and draw the bigger one from this center ...?
This way the radius/diameter of the aureole could perhaps even be configurable ... 😎

**Comment by MagpieFourtyTwo** [comment]
Thx 4 clarification. And, no, didn't want to create any unnecessary effort, of course.  If it's too tedious, just forget about enlarging the aureole.  Esp. if a more contrasting color would be possible - which would most probably already solve the "problem".

**Comment by moving-bits** [comment]
Do you have some specific color in mind which would help with contrast?

**Comment by ztNFny** [comment]
It's on the map which might have *any* color at that point. So there's no colour which will guarantee a high visibility. 
I'd propose to just stick to what we have. Using our highlight colour makes sense from a design point, any other alternative will not guarantee a better experience - and this feature didn't exist for the last 10 years, so the requirement for it can't be that big 😉

**Comment by ztNFny** [comment]
> It's on the map which might have any color at that point. So there's no colour which will guarantee a high visibility.

Btw, that's the reason for cache markers to have 2 borders! With just the black or just the white outline or even without any border at all contrast won't be good enough in all situations.

**Comment by MagpieFourtyTwo** [comment]
> It's on the map which might have _any_ color at that point. 

That's of course pretty much true, but there are colors which are more and some less likely.
A strong red for example is pretty seldom.
Or the grey from the bottom sheet header, if you prefer to visualize the connection to the bottom sheet ... ;)
IMHO it should at least contrast the typical cache icon colors ...

BTW: What do you thing about moving the map upwards if the selected cache would be hidden behind the bottom sheet?
Plus of course moving the map back to it's previous view port after closing the bottom sheet?
I'm pretty undecided, don't even know if I like the idea ;) (there are pros and cons), only just noticed that the icon in question may not even visible at all ...

**Comment by ztNFny** [comment]
> That's of course pretty much true, but there are colors which are more and some less likely.
> A strong red for example is pretty seldom.
> Or the grey from the bottom sheet header, if you prefer to visualize the connection to the bottom sheet ... ;)
> IMHO it should at least contrast the typical cache icon colors ...

A "strong red" is the color of events ;-) The current highlight color is already quite far from most cache icon colors - only not from custom caches, but I guess those should be the most seldomly used ones.

> BTW: What do you thing about moving the map upwards if the selected cache would be hidden behind the bottom sheet?

Nooooo! Don't "randomly" move the map!

**Comment by ztNFny** [comment]
> Yep, you're right, Hmm. Nevertheless, a darker color would still be better - just have a look at what I mean:
> Although the cache is the topmost, the aureole color itself is nearly not noticeable.

Please use at least half-realistic usecases for evaluating it. Mapping thousands of caches on a few cm of screen has no real use.

![image](https://github.com/user-attachments/assets/efd7a726-6ecc-4bed-ba5c-acca05fa85e3)

**Comment by MagpieFourtyTwo** [comment]
If there is just one cache in sight, the light aureole is of course fine.
But if there are caches around resp. partly "under" the selected one, things get harder.  And that's what I wanted to show.

**Comment by fm-sys** [comment]
> BTW: What do you thing about moving the map upwards if the selected cache would be hidden behind the bottom sheet?

Google Maps does that and IMHO it doesn't feel unexpected. The movement needs to be animated properly of course...

I would go for it, but don't have a strong opinion.

**Comment by moving-bits** [comment]
> > But if there are caches around resp. partly "under" the selected one, things get harder.
> 
> In that case it'll get impossible to spot the selected cache no matter what color is used as it'll most likely be partially or completly covered by other cache markers:

Since #15920 the highlighting marker is placed on top of all other caches (highest z-level), so even in a crowded setting it should not be covered by other caches.
