### ISSUE TITLE
OKAPI OCPL: server introduced rate limit which clashes with c:geo cache update routines

### ISSUE THREAD

**Issue by pawelko-g** [cgeo/cgeo#15818]
The c:geo program does not refresh geocaches in a specific number, but only a few at a time. 
Applies to opencaching.pl
![Screenshot_20240626_185038_cgeo](https://github.com/cgeo/cgeo/assets/173948046/d2f698a5-a822-403f-9e09-aee9f494d23c)

**Comment by SammysHP** [comment]
Can you please describe your problem in more detail?

**Comment by pawelko-g** [comment]
I want to refresh many gocaches and several from the given query are refreshed.

**Comment by SammysHP** [comment]
Can you give us a step-by-step explanation of what you are doing, what you expect to happen and what actually happens?

**Comment by mzylowski** [comment]
@SammysHP, the problem is caused by API limits introduced on OCPL side (it is undocumented change) only on OCPL server. Please take a look here: https://github.com/opencaching/opencaching-pl/issues/2405 
Let's wait for @deg-pl answer who is head admin of OCPL server and who was responsible for those changes.

**Comment by eddiemuc** [comment]
Interesting discussion going on there on OCPL side. If those rate limits are really introduced for good, we need to discuss for c:geo whether we are willing and able to spend the effort to still support this caching server I'm afraid. Let's wait for the end of discussions on OCPL side before doing anything.

For now I will adapt issue title and set to feature request (I can't see any wrong behavior of c:geo as of now)

**Comment by mzylowski** [comment]
The issue can be closed. It was caused by the misconfiguration of limits of requests to the OC server, which should be transparent for end-users, but unfortunately, it was limited too much due to a mistake.
