### ISSUE TITLE
Mapsforge offline map is showing areas in blue but is no water

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#15822]
### Describe your problem!

Offline Mapsforge map (e.g the Netherlands 2024-06-21 06:49 | 851M ) is showing land areas in blue colour See red arrows in attached file). This is very confusing as it looks like a water area. Is this a setting in c:geo or should I raise the issue at Mapsforge ?
![blue](https://github.com/cgeo/cgeo/assets/1834022/8458c614-49cf-4d02-8132-dc55a778a1b7)

### How to reproduce?

just see downloaded offline map

### Reproducible

Yes

### c:geo Version

2024.06.02

**Comment by devemux86** [comment]
There was a problem with land polygons in Mapsforge maps creation.

We will need to recreate these maps.

**Comment by SammysHP** [comment]
Then I'll close it here.

**Comment by devemux86** [comment]
https://github.com/mapsforge/mapsforge/issues/1489

**Comment by devemux86** [comment]
Mapsforge maps with the problem were all updated.

If you see anything else, please let us know.
