### ISSUE TITLE
Can't modify offline lists from cachepopup

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15824]
The lists a cache is stored to can no longer be modified from CachePopup after https://github.com/cgeo/cgeo/pull/15787

To repoduce:

1. Store a cache
2. Open Popup for the cache
3. Open list selection dialog
-> No lists selected

**Comment by ztNFny** [comment]
new StoredList.UserInterface(context).promptForMultiListSelection(R.string.lists_title, selectedListIds -> downloadCachesInternal(context, Collections.singleton(cache.getGeocode()), selectedListIds, cache.isOffline(), true, onStartCallback), true, cache.getLists(), fastStoreOnLastSelection);

**Comment by MagpieFourtyTwo** [comment]
Just wanted to file the very same issue.  ;)
Additional stuff over here: Assigning a list from bottom sheet does not have any affect on list assignment of the cache.
Instead, after "adding" the cache to a list, the cache gets downloaded in the background.

**Comment by moving-bits** [comment]
That's bad, indeed. Root cause is that clicking on "edit lists" uses the same function as "store cache", and this function did not check whether the cache was already downloaded. I'll create a fix for it.

**Comment by MagpieFourtyTwo** [comment]
Working again - thx!
