### ISSUE TITLE
Sort lists by datetime of offline log

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15837]
Taken from support ticket 977052:

I tend to cache offline, and when I do I will usually do an offline log, maybe with a few words to help remind me what cache it was and what I saw there. If the cache is not already in a C:Geo list, then the process of doing an offline log will add the cache to the "Stored" list. It would certainly help if I could order the list by date and time that I found the cache, this would also help in identifying the cache and what was there, what I saw etc, because I could then properly log the caches in the order that I found them.

Although we can sort by date, this does not always mean that the time is sorted correctly. I suspect that it is a datetime variable that is used here, and that the time is forced to the same value, probably 00:00.00. Note that even if this proposal is adopted, the field header and sort by option should still just show "Date Logged".

If the date and time could be saved with any log type and sorted based on that date/time this would help quite a bit when it comes to properly logging the caches, by identifying which order they were found in.

I suspect that this is probably only a single line of code change (removal of the force time to 00:00.00) and everything else will simply work.

I appreciate that there is a bit of a problem here, that Geocaching.com intentionally does not log times - it might be the case that times will have to be forced back to 00:00.00 for the posting to geocaching.com process - I am not sure here. And lastly - I would not mention anywhere that log dates are stored with times.  Outside of better sorts for the lists, it is simply not relevant

**Comment by eddiemuc** [comment]
Addendum:
I misunderstood how cgeo behaves here. Turns out Log Date is is the last online log date. A more accurate request would be:

Add a new list sort called "Own log date" that sorts by date/time. Should include all log types but most especially offline logs.

**Comment by moving-bits** [comment]
Would sort by "date stored on device" help? 
(Would require that the user does not touch an offline log or any other aspect of that cache as soon as another offline log has been created)

**Comment by murggel** [comment]
For offline logs we already have the time stamp of the offline log, it will be exported to the field notes.

So sorting for log-date does currently not consider offline-logs?

In my case the logs were sorted correctly, but I already had the caches stored in a list.

**Comment by murggel** [comment]
Also for unsaved caches the sorting seems correct to me.

Can the user probably provide a video?

**Comment by murggel** [comment]
Codewise the visited date is stored for offline logs for all log-types (GeoCache.logOffline), whereas for online-logs only for "found" and "did not found" logs the visited date is stored (LogUtils.adaptCacheCommonsAfterLogging)

**Comment by murggel** [comment]
I will have a look into it...

**Comment by murggel** [comment]
Note to myself:
The sorting criteria "Log Date" is also used for the "History"-List, so if we change some logic, it will be reflected to the History-list as well

**Comment by eddiemuc** [comment]
User on support claimed this is not needed after all. Thus I am closing this issue
