### ISSUE TITLE
[Nightly] Menu => Settings => Crash

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#15831]
### Describe your problem!

After updating to current nightly, I can't open settings anymore - c:geo immediately crashes.
What can I do (other than restoring a working backup, which usually is a big hassle ...)

### How to reproduce?

Open c:geo, then select Menu => Settings

### Actual result after these steps?

c:geo immediately crashes - and does not even restart, as usual.

### Expected result after these steps?

Guess what ...  ;)

### Reproducible

Yes

### c:geo Version

2024.06.30-NB-3528e7a

**Comment by MagpieFourtyTwo** [comment]
Managed to create a logfile (via logproperties.txt) - seems as if the class ``cgeo.geocaching.settings.ProximityPreference`` could not be found ...

[cgeo-log-support-2024-06-30-22-01-10-2.txt](https://github.com/user-attachments/files/16045994/cgeo-log-support-2024-06-30-22-01-10-2.txt)

**Comment by MagpieFourtyTwo** [comment]
Funfact: Although c:geo does not pop up again after the above crash (at least not in foreground), it seems as if it nevertheless tries to restart ... cause right after the above posted logfile it even generated another one: 

[cgeo-log-support-2024-06-30-22-01-29-2.txt](https://github.com/user-attachments/files/16046011/cgeo-log-support-2024-06-30-22-01-29-2.txt)

**Comment by eddiemuc** [comment]
Assumingly fixed with https://github.com/cgeo/cgeo/pull/15825

**Comment by MagpieFourtyTwo** [comment]
Yep, looks more than similar - so chances are to find this fixed in today's nightly ... thx for pointing to this, will sleep way better now. [;)]

**Comment by moving-bits** [comment]
yes, #15825 is the fix for this crash

**Comment by MagpieFourtyTwo** [comment]
Thx to you, too, of course, for fixing it.  ;)

**Comment by MagpieFourtyTwo** [comment]
Working again - thx!
