### ISSUE TITLE
Strange triangle in Google Maps

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15839]
Support Ticket 248370

A user in support claims to see a strange triangle using c:geo with Google Maps. See screenshot.

![Screenshot_2024-07-04-19-23-25-61_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/cgeo/cgeo/assets/6909759/32789959-84b9-426b-a451-a131635b6b1d)

Place is near N 50° 39.960' E 003° 04.826'. I could not reproduce the issue. I ruled out individual routes tracks or geojson files. 

Does anyone have an idea what could cause such a triangle?

**Comment by moving-bits** [comment]
Looks like location history

**Comment by eddiemuc** [comment]
This is embarassing, I could have thought of this myself...
Thanks a lot guys, I will close here
