### ISSUE TITLE
Change coordinate for user-defined geocaches

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15842]
Support ticket 205820

A user asks forma Feature to manually change the coordinate of a user-defined cache.

As of now, user-defined caches can only be created via tap on the map, thus created coordinates can't be entered in a very precise way. The key wish behind the request would be to have this kind of control so a UDC can be placed exactly to mark other spots e.g. landmarks

**Comment by moving-bits** [comment]
Duplicate of #14669
