### ISSUE TITLE
use new features from play-services-maps v19.0.0

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#15846]
### Tell us your idea!

See Release Notes at https://developers.google.com/android/guides/releases#june_25_2024:

The latest updates to play-services-maps (v19.0.0) include support for the following new features:

-    Configuring map color scheme to dark, light, or to use system settings. For details, see [Configure a map](https://developers.google.com/maps/documentation/android-sdk/configure-map).
-    Use of default colors for maps to match the new colors that are already available in the Google Maps app. For details, see [New map style for Google Maps Platform](https://developers.google.com/maps/new-map-style-opt-in).

**Comment by ztNFny** [comment]
> * Configuring map color scheme to dark, light, or to use system settings. For details, see [Configure a map](https://developers.google.com/maps/documentation/android-sdk/configure-map).

We already have that?

> * Use of default colors for maps to match the new colors that are already available in the Google Maps app. For details, see [New map style for Google Maps Platform](https://developers.google.com/maps/new-map-style-opt-in).

Personally I just HATE those new colors, but that might be just me. If the new ones are adopted we should consider also offering a "classic" color theme for Google Maps.

**Comment by eddiemuc** [comment]
Looks like the new map style is already active for our `master` branch (assumingly because we use play-services-maps version 19.0.0 since yesterday):

![image](https://github.com/cgeo/cgeo/assets/6909759/4a20d227-0556-48bc-b5d7-c670ace15ef8)

**Comment by ztNFny** [comment]
> Looks like the new map style is already active for our `master` branch (assumingly because we use play-services-maps version 19.0.0 since yesterday):

I'll try to add a "classic" theme asap :-)

**Comment by ztNFny** [comment]
I started looking into a "classic" theme, but actually Google Maps makes soooo many adjustments to map display based on zoom level I guess it'll only be possible to get there like 60% of the way - at least I wouldn't know how to get further (zoom-specific display).

Leaving my current WIP for https://mapstyle.withgoogle.com here, in case someone wants to work on it:
```
[
  {
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#e8eaed"
      }
    ]
  },
  {
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#523735"
      }
    ]
  },
  {
    "elementType": "labels.text.stroke",
    "stylers": [
      {
        "color": "#f5f1e6"
      }
    ]
  },
  {
    "featureType": "administrative",
    "elementType": "geometry.stroke",
    "stylers": [
      {
        "color": "#c9b2a6"
      }
    ]
  },
  {
    "featureType": "administrative.land_parcel",
    "elementType": "geometry.stroke",
    "stylers": [
      {
        "color": "#dcd2be"
      }
    ]
  },
  {
    "featureType": "administrative.land_parcel",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#ae9e90"
      }
    ]
  },
  {
    "featureType": "landscape.natural",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#a8dab5"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#a8dab5"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#098591"
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "geometry.fill",
    "stylers": [
      {
        "color": "#a8dab5"        
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#188038"        
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#ffffff"        
      }
    ]
  },
  {
    "featureType": "road.arterial",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#ffffff"        
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#feefc3"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "geometry.stroke",
    "stylers": [
      {
        "color": "#fbbc31"
      }
    ]
  },
  {
    "featureType": "road.highway.controlled_access",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#fde293"
      }
    ]
  },
  {
    "featureType": "road.highway.controlled_access",
    "elementType": "geometry.stroke",
    "stylers": [
      {
        "color": "#f9ab00"
      }
    ]
  },
  {
    "featureType": "road.local",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#4e5256"
      }
    ]
  },
  {
    "featureType": "transit.line",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#bdc1c6"
      }
    ]
  },
  {
    "featureType": "transit.line",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#185abc"
      }
    ]
  },
  {
    "featureType": "transit.station",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#bdc1c6"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "geometry.fill",
    "stylers": [
      {
        "color": "#9cc0f9"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#2161c0"
      }
    ]
  }
]
```

**Comment by ztNFny** [comment]
> > * Configuring map color scheme to dark, light, or to use system settings. For details, see [Configure a map](https://developers.google.com/maps/documentation/android-sdk/configure-map).
> 
> We already have that?

I looked into that and the new lib offers a native dark theme which is better than the "static" one we were using so far. I'm preparing a PR to adopt the new dark theme in favor of our old Night theme.
