### ISSUE TITLE
Add link when exporting. 

### ISSUE THREAD

**Issue by troNpo** [cgeo/cgeo#15859]
### Tell us your idea!

It would be very very interesting if when sharing or exporting the cache (gpx) the output waypoint would attach to the description a clickable link to the page of the cache itself (Locus Maps does this)

**Comment by ztNFny** [comment]
I don't understand the request. 

Using the share feature a link is shared.

GPX contains the info that it's a geocache so the app you open the GPX with can easily open the website without a link being embedded. (Modyfing the listing on export by appending anything to it that's not originally there I'd actually consider a bug, not a feature)

**Comment by eddiemuc** [comment]
> I don't understand the request.

I suspect that some apps where GPX is imported don't have the logic to create such a link themselves out of the give. Information. So it would be practical for users to have one pre-createe by c:geo on export

**Comment by troNpo** [comment]
It seems to be the last thing you are commenting on, I see that the url is in the gpx code, for Oruxmaps to identify it it must be encoded as <desc>
Thanks for the clarification

**Comment by murggel** [comment]
> It seems to be the last thing you are commenting on, I see that the url is in the gpx code, for Oruxmaps to identify it it must be encoded as "desc" In this way, for example, 
> Thanks for the clarification 
> 

But the url-tag is the "right" location in gpx-format, so probably oruxmap should read it from there.

**Comment by troNpo** [comment]
Ok thanks, I'll talk about it with the developer of Oruxmaps, maybe I can give an easy solution, and improve this small inconvenience
Thanks a lot.
