### ISSUE TITLE
Support ticket: address search not working for specific user - searching for a cause

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15856]
Support ticket [912249](https://cgeosupport.droescher.eu/scp/tickets.php?id=8176)

Asking for help in #15854 worked so nice, I try it a second time :-)

I have a user on support claiming that her address search stopped working a couple of weeks ago on several different phones (Pixel 6A, Huawei P20 Lite, Xiaomi redmi 13c). I can't reproduce and I assume it is user-specific because we would get a lot more tickets if it isn't. Indeed I can find in her logfile the following log message:

`[main] [cgeo.geocaching.address.AddressListActivity].showToast(c:geo konnte keine Koordinaten fÃ¼r diese Adresse ermitteln)`

User uses up-to-date-cgeo (2024.07.07), problem seems to exist also in previous versions though.
Google play services are enabled for the user: `Google Play services: enabled - 24.23.35 (190400-646585959)`

No more information available to get to the cause of this (or I am overlooking something), I especially found that we are not logging exceptions thrown in this case unfortunately (I added PR #15849 to address this in the future).

In the meantime: any idea what happens here and what I might tell the user?
@moving-bits @Lineflyer again I mark you because you have access to the support ticket :-)

Thanks and regards
  Eddie

**Comment by moving-bits** [comment]
This is strange, not only are all locations mentioned in the ticket working flawlessly for me, I also tried using our fallback geocoder (in case there was some problem with Google reverse geocoding on the user's machine), but also for that all locations did work.

**Comment by eddiemuc** [comment]
Haven't heard back from user. and can't reproduce the problem Let's close here for now and reopen if new information arises.
