### ISSUE TITLE
SAF access w/o access to map files (support ticket)

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15854]
Support Ticket 514358 https://cgeosupport.droescher.eu/scp/tickets.php?id=8175

I have an open support ticket where I have no idea how to proceed.

The user claims and verifies through screenshots that he can successfully map folders. However, c:geo can't access downloaded map files in these folders (log file verify this).

I asked everything I could think of: full disk, external drive, missing system permission etc w/o success.

Does anyone here have additional ideas on what to check?

@Lineflyer @moving-bits feel free to take a look at the ticket yourself 

Thanks a lot!

**Comment by Lineflyer** [comment]
> missing system permission

Really?
It sounds like the user revoked some permissions from system apps.
We had such cases.

See help text "_DE_Systemzugriff_SAF_fehlt"

**Comment by Lineflyer** [comment]
sent answer in the ticket.

I am back alive BTW ;)

**Comment by eddiemuc** [comment]
> I am back alive BTW ;) 

Good to hear :-)

**Comment by eddiemuc** [comment]
And many thanks @Lineflyer
