### ISSUE TITLE
Allow selection of images stored on cache when writing a log entry

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15857]
### Tell us your idea!

Feature Request is from another user

Sometimes, when you store own images on a cache, you want to use one or several of those images also on a log file you write for that very same cache. As of now, c:geo does not allow for an easy selection of those images (one would have to navigate manually down the very non-intuitive directory structure of the GeocachePhotos folder in her file system).

It would be nice to have an easy way to select such images in a log file

### What solution would you suggest?

I suggest to add a third "image select" button (next to "select image" and "take photo") which will open the image selection file dialog in the GeocachePhotos-subfolder of that cache. Button should only be available if there are any photos stored for the cache.

### Is there an alternative?

Do nothing

**Comment by ztNFny** [comment]
I'd suggest to the user to just create an offline log and take the photos there instead of taking them from the cache itself. Almost the same workflow and achieves the requested result already today.

**Comment by eddiemuc** [comment]
> I'd suggest to the user to just create an offline log and take the photos there instead of taking them from the cache itself. Almost the same workflow and achieves the requested result already today.

Then the user won't have the photo stored on the cache. It will be gone after posting the log. Also, I assume that users store photos on caches usually was before they write a log

**Comment by ztNFny** [comment]
It will not be gone, it'll even be available online. 
And if course you don't have to write a log to store an image, just create sn empty offline log with just the image. Then you can later add more images to that and even later text.

**Comment by murggel** [comment]
At the time I took the picture, I probably didn't even know which one I will take for the log.
And adding an offline log just for saving an image for later use, doesn't seem very intuitive. 
So having the option to select easily the folder of the current cache would be a nice feature

**Comment by eddiemuc** [comment]
Fixed with PR #15949
