### ISSUE TITLE
Geocaching ignore function not working?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15863]
Support ticket 660540

A user claims that caches on his gc.com ignore list are not ignored in c:geo. I have never used the ignore feature myself, so I tried it out by ignoring a random cache.

My impression is though that even geocaching.com website does not ignore my ignored caches :-) Eg ignored cache is still found in searches and shown on map.

Am I missing something here or is this feature really currently broken?

**Comment by ztNFny** [comment]
works for me - my only ignored caches shows neither on GC nor in c:geo (unless I store it there of course). Maybe you still have it stored in c:geo (72h after deletion)?

**Comment by eddiemuc** [comment]
Works now for me again. Could have sworn that it didn't work on GC.com either for a while
