### ISSUE TITLE
Downloading cache from info sheet should not trigger system notification

### ISSUE THREAD

**Issue by Meybux** [cgeo/cgeo#15881]
### Describe your problem!

![inbound8858115251638970239](https://github.com/user-attachments/assets/6b71fbdd-ed9f-451b-b47a-6d9990c8b79d)
Just a littel bit scrolling.
Es ist nervig und man kommt nicht vorwärts.

Jeder angesehene Cache wirde runtergehen mit Status Meldung 

![inbound8008992340342407447](https://github.com/user-attachments/assets/75a1e14e-ed2a-453e-91e9-6cc60ab4aa5a)

### How to reproduce?

Nur suchen auf der Karte 

### Reproducible

Yes

### c:geo Version

2024.07.14

**Comment by moving-bits** [comment]
For the first part, please see #15882.

I'll change the issue title to reflect the second part here.

(Downloading a cache from cache info sheet should not trigger a system notification, toast + disabling/enabling download buttons is just fine.)

**Comment by alan666notb** [comment]
I've noticed this as well,
There's a new notification each time I refresh a cache page.
