### ISSUE TITLE
List selection: down arrow and list symbol should be white in light mode

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15883]
Support 792919
C-geo version 2024.07.14-RC

Reported by user, reproducible for me:

New beta update for a List View has a contrast issue. If in Light or Default appearance, the down arrow (used to change lists) is black. Needs to be white to offer contrast. If in Black appearance, it is correct.

![Screenshot_2024-07-18-09-52-40-40_a916ceb0c8a82619faeb76fe6b8ae997.jpg](https://github.com/user-attachments/assets/eb4432fe-9b8a-46cb-a42a-06f4f95863bd)

**Comment by moving-bits** [comment]
Seems to affect list icon as well
