### ISSUE TITLE
Custom parameters for user-defined tile provider URL

### ISSUE THREAD

**Issue by IiroP** [cgeo/cgeo#15884]
### Tell us your idea!

The newly added support for user-defined tile provider URLs (#15714) is a great start. However, the current implementation is somewhat limiting as it only supports defining the base URL. Some tile servers (e.g. Trailmap.fi) require an API token as query parameter (`?key=XXX`). 

### What solution would you suggest?

I can see at least two potential solutions for this problem:
1) New setting field for URL parameters that are appended to calculated URL (i.e. user inputs `https://tile.openstreetmap.org` to one field and `key=XXX` to another)
2) Allowing the user to type full URL with X/Y/Z wildcards (e.g. `https://tile.openstreetmap.org/{z}/{x}/{y}.png?key=XXX`)

Option 2 is more versatile, as it would also allow the user to change image format etc.

**Comment by fm-sys** [comment]
I would also vote for option 2

**Comment by wasu-code** [comment]
Yes, some maps can have additional parameters - both query parameters (mostly API keys) and path parametes (map themes).

So it would be perfect to provide map URL in format of:  
```url
http://tile{server|stripe}.example.org/cycling/{z}/{x}/{y}.png?key={apikey}&showPOI=never
```

`{z}` - Zoom

`{x}`,`{y}` - Tile number

`{stripe}` - Cycle server number (1..4)

`{server}` - Cycle server char (a,b..c)

`{quadkey}` - [Quadkey numbering system](https://learn.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system#tile-coordinates-and-quadkeys)

`{ln}` - Map language (en,it,fr...)

It's also worth noticing that different maps can have different **max zoom**

**Comment by moving-bits** [comment]
For documentation purposes: Our nightly versions support customizing the Uri, supporting parameters `{X}`, `{Y}` and `{Z}`, but you can add your own api key etc. to the address. 
For migration purposes: If c:geo does not find both `{X}` and `{Y}` parameters, it automatically adds `/{Z}/{X}/{Y}.png` to the given address (as before the recent change).
