### ISSUE TITLE
Hint cannot be rotated if "encode hint" setting is unset

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15887]
User report on support: (ticket 592519)

Cache GC9G3NA has an unencrypted hint (cache owner seems to have done the ROT13 already).
Hint gets displayed encoded in c:geo, and user cannot tap on the hint to decode the hint.

---

I can reproduce the behavior if I disable the "encode hint" option in settings. Hint gets displayed encoded in this case, and I taps on the hint get ignored.

This brings up two questions:
- Why does c:geo encode the hint at all even with this option not being set?
- Any why does it offer rotation only if that option is enabled?

(Not sure whether this would be a bug report or a feature request - probably both.)

**Comment by SammysHP** [comment]
"Encrypt hint" does exactly what it says: If enabled, it will encrypt the hint with ROT13. This is the default on geocaching.com. It will then provide a method to decrypt the hint by tapping on it.

> Why does c:geo encode the hint at all even with this option not being set?

It doesn't. ROT13 is completely symmetrical and c:geo can only assume that the hint it parses from geocaching.com is encrypted. On this cache the owner manually encrypted the hint and geocaching.com encrypted it again, i.e. decrypting it.

> Any why does it offer rotation only if that option is enabled?

Because there is no reason to encrypt a clear text hint once it was shown. If the option is not enabled, the user will always see the decrypted text.

**Comment by moving-bits** [comment]
> "Encrypt hint" does exactly what it says: If enabled, it will encrypt the hint with ROT13. This is the default on geocaching.com. It will then provide a method to decrypt the hint by tapping on it.
> 
> > Why does c:geo encode the hint at all even with this option not being set?
> 
> It doesn't. ROT13 is completely symmetrical and c:geo can only assume that the hint it parses from geocaching.com is encrypted. On this cache the owner manually encrypted the hint and geocaching.com encrypted it again, i.e. decrypting it.

I guess this does depend on what the functions we use deliver as default (not sure where we get the hint from currently, would need to look that up). If we parse the webpage, it's "encrypted" by default, so c:geo needs to do the rotation if the "show encrypted hint" option is unchecked. This would explain the behavior. (My - probably false - assumption was that we get the unencrypted string, then we would not have to rotate it, if that option is unchecked.)


> > Any why does it offer rotation only if that option is enabled?
> 
> Because there is no reason to encrypt a clear text hint once it was shown. If the option is not enabled, the user will always see the decrypted text.

I understand that from a logical side, but if we see this just as a toggle (as ROT13 is), then it would be useful to always offer to do the rotation. (This is the "feature request" part of this issue.)

**Comment by ztNFny** [comment]
> I understand that from a logical side, but if we see this just as a toggle (as ROT13 is), then it would be useful to always offer to do the rotation.

Somehow this doesn't feel right to me. In case of this specific cache the hint is encoded twice, once by GC, once by owner - which in the specific case of rot13 makes it decoded.
The setting we have is a "decode the GC encoding of hint" to me and if I say as a user I don't want to have that there's also no reason to have it on click as there's simply no usecase to decrypt a hint I already read.
No other double-encoding than this specific one will be encrypted this way (e.g. a rot13, rot5), so this "fix" is for 1 specific cache only.

**Comment by moving-bits** [comment]
Problem is that we do not have a way to detect whether the string in the list is already encoded or not. 99% of the time it's either encoded or excepted from being encoded by being put into square brackets (IIRC), so everything is fine.

For that specific cache, the text in the listing gets transferred "unencoded" to us (actually: encoded twice), but c:geo thinks it's encoded. So if the user does not have the "show hint encoded" checked, c:geo will encoded the actually decoded string, and the user has no easy way to decode it. This is no problem, if the user has checked above's setting, as they can then use tap as a toggle. 

Problem here is (or better: was, as @bekuno already has merged the PR), that the tap function only got added to the text field, if the setting was checked. The PR simply changes that to "apply tap listener even if setting is unchecked". No harm done, IMHO.

**Comment by SammysHP** [comment]
Overall there's also no reason to show a ROT13 encrypted text in c:geo at all. Nobody will decrypt it by hand. We could simply add a "show hint" button as we already got in the popup. The option in the settings would then be "show hint by default".

**Comment by ztNFny** [comment]
The default for the hint option is already to show it un-encoded. I doubt many people re-enable that option.

> Problem here is (or better: was, as @bekuno already has merged the PR), that the tap function only got added to the text field, if the setting was checked. The PR simply changes that to "apply tap listener even if setting is unchecked". No harm done, IMHO.

The "harm" is that this fix works only for a tiny fraction of those hints that are double-encrypted. It doesn't work for rot-5, rot-8, reverse (which I've personally seen quite frequently) but only rot-13. So imho this is a non-feature and shouldn't exist.

**Comment by ztNFny** [comment]
> The PR simply changes that to "apply tap listener even if setting is unchecked". No harm done, IMHO.

The harm is: In addition to not working most of the time it now also does something completly useless for those caches without a double-rot13: It rot13-encodes the string, adding no value at all but causing harm in that the user is unable to read it (without having to click again).
So it's a feature that's harmful in 95% of cases (no double-encryption), useless in 4% of cases (double-encryption with non-rot13) and only useful for the remaining 1% (or specificially GC9G3NA)

**Comment by bekuno** [comment]
I had no harm with reactivating the ROT13 by tapping on the text.

On the other site I understand, that is normally useless, as the owner can avoid the encryption bei using ther barckets [ and ].
It would be also ok for me to set it back as it was before the PR.

**Comment by moving-bits** [comment]
I don't think the PR is harmful at all - it doesn't make things worse compared to today, but it helps for the few cases of ROT13 double encryption. The PR does not add anything new, it just makes the already existing ROT13 available in the hint field even if the "show encrypted hint" setting is off.

**Comment by eddiemuc** [comment]
I agree with @moving-bits and vote for merging
