### ISSUE TITLE
NPE when posting log with password on opencaching.de

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15899]
### Describe your problem!

Support mail:
User tries to log an Opencaching Germany cache, which requires a log password.

**I cannot verify, whether he uses the right password (but he is very sure), anyway the shown error message looks like its not related to the password itself.**

### How to reproduce?

- Start logging for OC11AC8
- Enter log text and password
- Try to send the log

### Actual result after these steps?

![image](https://github.com/user-attachments/assets/2be3e13a-2232-4c14-a7f8-9f2e01580f10)

### Expected result after these steps?

PW is correct: Log should be posted
PW is wrong: Log should not be posted and user properly being informed about the reason

### Reproducible

Unclear

### c:geo Version

requested from user

### System information

```text
requested from user
```

### Additional Information

Support Ticket #123216

**Comment by eddiemuc** [comment]
Looks like there's a parsing error of our message on server side. Unfortunately I can't reproduce (and thus analyze) the problem w/o knowing the password....)

Trying to post a log using a wrong password seems to work fine, at least it returns the expected answer "wrong password":
![image](https://github.com/user-attachments/assets/7d568a42-a789-4767-ab05-31d66bbacc08)

**Comment by Lineflyer** [comment]
@eddiemuc 
Please feel free to use OC1120A for testing.
As this cache is not very often logged, I temporarily setup a password as logging requirement.
The correct password is `cgeotest`

**Comment by eddiemuc** [comment]
> Please feel free to use OC1120A for testing. As this cache is not very often logged, I temporarily setup a password as logging requirement. The correct password is `cgeotest`

Logging this cache with this password was possible w/o any problem. So no luck...

**Comment by Lineflyer** [comment]
I will contact the user and ask for the correct password for OC11AC8.
@eddiemuc You will potentially find it then under the above mentioned ticket number.

I will remove the password from my owned cache then.

**Comment by Lineflyer** [comment]
Addon: @eddiemuc You already contacted him again....so I will do nothing.

**Comment by eddiemuc** [comment]
> I will contact the user and ask for the correct password for OC11AC8. 
> Addon: @eddiemuc You already contacted him again....so I will do nothing.

Correct. I asked the user if problem was resolved. If it was not I will ask the cache owner for the password (I don't want to "sneak" the password from a cache finder, the owner should know what we are doing. Hope he/she is a fan of c:geo :-))

**Comment by eddiemuc** [comment]
Haven't heard back from user and can't reproduce. Let's close here for now and reopen if necessary.
