### ISSUE TITLE
Appending cache to route on map: new route segment not drawn (need to hide/unhide route to draw it)

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15904]
Support ticket 689214

Reported on Support and reproducible for me on both unified and non-unified map for 2024.07.14-RC

Something was changed in the "on screen route" generation? I _was_ able to select a cache and append it to route. Then the route would immediately be updated and shown on screen. 

Now the "new" route is not shown. I need to select the route and hide it. Then I can un-hide it and the (updated) route shows on screen. 

Support ticket contains a video showing the problem.

**Comment by moving-bits** [comment]
culprit seems to be 326121ae1b according to `git bisect`, I'll investigate further...
