### ISSUE TITLE
New overlays for live map

### ISSUE THREAD

**Issue by blafoo** [cgeo/cgeo#1592]
At the moment there are four overlays in the live map
- caches (online + stored + waypoints)
- other cachers (Go4Cache)
- position
- scale

I'd like to add/splitt additional overlays resulting in overlays for
- online caches (limited to 500 (?) caches)
- stored caches (unlimited)
- waypoints (unlimited)
- challenges (see #1591)
- circles
- other cachers (Go4Cache)
- position
- scale

The user could enable each overlay seperately the same way he chooses the kind of map.

**Comment by Lineflyer** [comment]
As this feature request if quite broad and we have meanwhile changed a lot this is IMHO outdated.
