### ISSUE TITLE
Validation cgeo fails at geocaching.com

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#15923]
### Describe your problem!

Validation as geocaching.com user login fails repeatedly.
Unable to validate authorisation at geocaching.com. Cgeo is not visible in my authorisation list

### How to reproduce?

Not working anymore at 2 Android devices. Followed all checks and remedies in FAQ 

### Actual result after these steps?

Also reported issue to support team of Groundspeak (not reponded yet; after 4 days)

### Expected result after these steps?

unable to validate (received numerous mail to validate via emailaccount

### Reproducible

Yes

### c:geo Version

2024.07.07

**Comment by SammysHP** [comment]
But you can log in on the website, right? What is the exact error message in c:geo?


> Also reported issue to support team of Groundspeak (not reponded yet; after 4 days)

They are not responsible for third-party apps and cannot help you.


> ### System information
> 
> _No response_

:question:

**Comment by wizard4u** [comment]
Yes, I can log in on the website.
Last month the same validate issues and receiving 30+ emails to validate my emailaccount (without success). Also no coords visible on Cache pages (just question marks). Then they reset something and it worked again (no response to question how to prevent future occurrence).

Update 2 minutes ago: I can use cgeo on my devices. Something that Ground speak did ? No feedback but it is working again. So I expect the issue is either at my devices and / or Groundspeak

Suggest to close issue here unless other users have same issue

**Comment by wizard4u** [comment]
close
