### ISSUE TITLE
Projection/Offset do not create variables

### ISSUE THREAD

**Issue by DaTechniker** [cgeo/cgeo#15922]
### Tell us your idea!

I am using extended formulas a lot.
There are some caches, that simply need a projection or offset from some waypoint
This words fine, except, I manually need to create variables. When Opening a waypoint, and I add a formula with vars, the these are created automatically

### What solution would you suggest?

automatically create variables when formulas are added to projection/offset

### Additional Information

Tested with: c:geo version: 2024.07.20-RC

**Comment by Lineflyer** [comment]
Confirmed. IMHO a bug as it AFAIR worked already before.

You are able to enter variables or formulars for distance/direction but the corresponding variables are not automatically created on the variable tab.

**Comment by eddiemuc** [comment]
Variables entered as part of distance and/or bearing of a projection were never created automatically. Valid feature request but not a.bug imho

**Comment by SammysHP** [comment]
Duplicate of #15756.
