### ISSUE TITLE
HIerarchically structured lists: introduce more hierarchy levels

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15938]
Feature request by a support user [Ticket #324796](https://cgeosupport.droescher.eu/scp/tickets.php?id=8313)
c:geo version  2024.07.26-RC

Thank you for introducing the new feature to structure lists hierarchically ! This seems very promising !

![image](https://github.com/user-attachments/assets/3878d08a-c429-45ec-b602-966428f2b260)

One more question, potentially a Request for Change

Could the feature be extended to support more hierarchical levels ?

Example :
one:A:blue
one:A:white
one:B:green
one:B:red
...

Through several successive colons in the Lists names, or any other distinct character, I leave that to your technical investigations.

That could allow to build an entire structure with sub-sub-Lists !

**Comment by MagpieFourtyTwo** [comment]
Is it possible that this change changed the sort order of lists?
Till yesterday lists starting with "_" were sorted before "."
But with latest nightly "_" suddenly dropped to the end of the list ... 
Not a big deal, but will for sure cause some confusion (and extra work).

And perhaps some can explain how sorting order is (or will be) ...?

**Comment by eddiemuc** [comment]
> Is it possible that this change changed the sort order of lists? Till yesterday lists starting with `_` were sorted before `.` to the very start of the list. But since latest nightly `_` suddenly dropped to the end of the list ... Not a big deal, but will for sure cause some confusion (and extra work).
> 
> And perhaps someone can explain how sorting order is (or will be) ...?

Could be a bug indeed. Do you have a screenshot?

**Comment by eddiemuc** [comment]
> And perhaps someone can explain how sorting order is (or will be) ...?

The intended sorting order (if no bugs are in code :-)):

//Stored list sorting:
            // A. If displayed: "Create new"
            // B. If displayed: "Stored",
            // C. If multiselect: preselected lists in alphabetic order (those are not grouped)
            // D. Grouped and ungrouped user lists w/o selected items (each level sorted alphabetically, groups and lists intermixed)
            // E. If displayed: "All"
            // F. If displayed: "History"

**Comment by moving-bits** [comment]
> Could be a bug indeed. Do you have a screenshot?

Even worse (for me): Lists starting with an underline used to be sorted before alphabetical entries, but are now sorted after them:

![image](https://github.com/user-attachments/assets/6d3f1a59-2b0b-4add-b822-4538fe90f9ea)

(Prepending a list name with "_" was an easy and unobstrusive way to make sure a list was visible at or near the top.)

**Comment by MagpieFourtyTwo** [comment]
> Even worse (for me): Lists starting with an underline used to be sorted before alphabetical entries, but are now sorted after them:

That is exactly what I tried to express.  ;)
Thanks for the explanation of the sorting, but in fact I did not mean the hierarchy of list types, but the alphabetical sort order, i. e. which character comes first, which last. And I especially had the non-alpha numeric characters in mind, like for example the changed sort position of the underscore.

**Comment by eddiemuc** [comment]
This is definitely a bug. I can't fix not right now but will attempt to this evening

**Comment by MagpieFourtyTwo** [comment]
And would be great to get an idea of the character's sort order.  Perhaps even in the docs - spent a while to learn that currently only the dot seems to comes prior to the letters.  Nevertheless, would be good to have some more (not so intrusive) non alphanumeric chars, to "prioritize" lists in an inconspicuous way.

**Comment by eddiemuc** [comment]
I think I know what the problem is: lists are currently sorted strictly alphabetic. @MagpieFourtyTwo to be very precise: according to UTF-8-character-codes, which for the most important characters is identical to ASCII. 

I see that _ is after uppercase and before lowercase. 

The bug is that c:geo used to sort list names using a collator which de facto sorts case-insensitive. E.g. uppercase is treated as lowercase. Then all letters are after the _

**Comment by moving-bits** [comment]
Current beta version (2024.08.09-RC) sorts "_" prefixed strings _before_ those starting with an uppercase letter. 
Lowercase and uppercase seem to be treated equal (umlauts included, but haven't checked for other non ASCII-chars).

**Comment by eddiemuc** [comment]
> Current beta version (2024.08.09-RC) sorts "_" prefixed strings _before_ those starting with an uppercase letter. Lowercase and uppercase seem to be treated equal (umlauts included, but haven't checked for other non ASCII-chars).

that's what I tried to express above :-)

**Comment by eddiemuc** [comment]
@moving-bits 
I get following erro when trying to build master locally:
```
Configuration cache state could not be cached: field `importDirs` of task `:main:compileBasicDebugAidl` of type `com.android.build.gradle.tasks.AidlCompile`: error writing value of type 'org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection'
> Could not resolve all files for configuration ':main:basicDebugCompileClasspath'.
   > Could not resolve com.github.moving-bits:datatables:-SNAPSHOT.
     Required by:
         project :main
      > Skipped due to earlier error

```

I everything in place server-sided to build master from scratch?

**Comment by moving-bits** [comment]
> I everything in place server-sided to build master from scratch?

You can always cross-check using [Jitpack](https://jitpack.io/#moving-bits/datatables). I guess I should create a numbered release, should make things easier. I'll create the release and will update c:geo accordingly.
