### ISSUE TITLE
Map: Cache Quick View: tapping and holding "navigate" and swiping up will open dozens of identical popups

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15937]
Support Ticket #679403
c:geo problem report (2024.07.26-RC)

Bug reported by user and reproducible for me.

* Open a cache on map in the quick view (half screen)
* press and hold the "navigate" button. 
* When the navigate popup show, keep pressing and swipe up. 

--> You will end up with tens of popups asking HOW to navigate. (on top of each other)
![image](https://github.com/user-attachments/assets/2c855d48-eee9-4873-a601-f5d3394a0e8a)

![image](https://github.com/user-attachments/assets/47e72708-e952-4ef0-b3f1-3636a5f0f2db)
(it is a bit hard to see, but what we have here is many many identical popups on top of each other)

Desired behaviour: popup should only be opened once.

**Comment by moving-bits** [comment]
see PR #15981 for a fix
