### ISSUE TITLE
FAQ-site is down

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#15931]
### Describe your problem!

I can't reach the FAQ-site from my mobile device. 

### How to reproduce?

Try to open faq.cgeo.org

### Actual result after these steps?

![Screenshot_20240729_175446_Chrome](https://github.com/user-attachments/assets/ef353429-80db-4a13-89b8-8a85640c35da)

### Expected result after these steps?

Show content with FAQ

### Reproducible

Yes

### c:geo Version

2024.07.29-NB-bbbcdb5

### System information

```text
Android 13
```

**Comment by murggel** [comment]
I will check when I am back home if it works f3om the PC

**Comment by SammysHP** [comment]
Also https://cgeo.org/ does neither work nor redirect (and never did), while https://www.cgeo.org/ works fine.

**Comment by murggel** [comment]
But manual.cgeo.org does work

**Comment by murggel** [comment]
Links from inside app

![Screenshot_20240729_193713_cgeo.jpg](https://github.com/user-attachments/assets/55182bab-f463-4a06-af1f-ffd4ff22df28)

**Comment by moving-bits** [comment]
Probably caused by the server changes @mucek4 has done before his vacation. Will try to get in contact with him, but I'm not sure if he's able to change config currently.

**Comment by Lineflyer** [comment]
@mucek4 has already been informed but he is on vacation right now.

**Comment by moving-bits** [comment]
@mucek4 has fixed the server configuration for `faq.cgeo.org`, it does redirect to `www.cgeo.org/faq` again.
