### ISSUE TITLE
Cache Details - Icons Showing Wrong Pixels

### ISSUE THREAD

**Issue by wolverine007** [cgeo/cgeo#15947]
### Describe your problem!

Inside the last RC 2024.08.02-RC. some icons are not centered, therefore some pixels on the right side of the three top icons are displayed:

![Screenshot_2024-08-04-01-17-41-221_cgeo geocaching-edit](https://github.com/user-attachments/assets/a3c1ee16-1fbe-4d55-8b27-c81ae491fb9f)

### How to reproduce?

Open Cache Popup or Cache Details Page

### Actual result after these steps?

Icons not centered correctly

### Expected result after these steps?

Icons centered - no pixels on the right side

### Reproducible

Yes

### c:geo Version

2024.08.02-RC

## System information

c:geo version: 2024.08.02-RC

Device:
-------
- Device type: 23049PCD8G (marble_eea, POCO)
- Available processors: 8
- Android version: 14
- Android build: UKQ1.230804.001 release-keys
- Screen resolution: 1080x2176px (393x791dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 24.26.32 (190400-650348549)
- Memory:  Available:1,6 GB, Total:7,0 GB, Threshold: 216,0 MB, low:false

Sensor and location:
-------
- Low power mode: active
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: orientation

Program settings:
-------
- Settings: v9, Count:299
- Set language: de
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: never
- Last auto backup: 1. Aug., 10:39
- Routing mode: Bike (shortest.brf / fastbike.brf / car-fast.brf / fastbike.brf / shortest.brf)
- Live map mode: true
- Use unified map: false
- OSM multi-threading: true / threads: 4
- Map: Deu+ost (FZK) (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:cgeo/maps/Deu+ost (FZK).map
  - Atts: (c) Map: FZK project (free for private use); Map data: OpenStreetMap contributors; Contour data: U.S. Geological Survey and J. de Ferranti
  - Theme: fzk-outdoor-soft-v5.zip:fzk-outdoor-soft-v5/fzk-outdoor-soft-v5.xml

Filters:
-------
- Hide waypoints: visited
- LIVE: Cache-Typ: Virtual, Status: 3 Elemente ({"advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{"values":["VIRTUAL"]}},{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{"values":["owned_no","found_no","exclude_archived"]}}]}})
- OFFLINE: Keine ({"advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{}},{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{}}]}})
- Additional stored filters: 11

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd.MM.yyyy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error //  (2024-07-10 07-23)
- Last successful login on geocaching.com: 2024-08-04 01-08
- Routing: internal / BRouter installed: false

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (138,2 GB free) v3 internal isDir(10 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (138,2 GB free) v3 internal isDir(10 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (138,2 GB free) v3 external non-removable isDir(3356 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (138,2 GB free) v3 internal isDir(9 entries)
- Map render theme path: fzk-outdoor-soft-v5.zip:fzk-outdoor-soft-v5/fzk-outdoor-soft-v5.xml
- Public Folders: #13
  - BASE: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo (av:true, files:>=23, size:>=5,1 GB, free:>=138,2 GB)
  - OFFLINE_MAPS: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/maps (av:true, files:>=18, size:>=5,1 GB, free:>=138,2 GB)
  - OFFLINE_MAP_THEMES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/maps/_themes (av:true, files:>=8, size:>=1,4 MB, free:>=138,2 GB)
  - OFFLINE_MAP_SHADING: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo (av:true, files:>=23, size:>=5,1 GB, free:>=138,2 GB)
  - LOGFILES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/logfiles (av:true, files:>=0, size:>=0 B, free:>=138,2 GB)
  - GPX: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/gpx (av:true, files:>=5, size:>=258,1 KB, free:>=138,2 GB)
  - BACKUP: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/backup (av:true, files:>=4, size:>=577,1 MB, free:>=138,2 GB)
  - FIELD_NOTES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/field-notes (av:true, files:>=0, size:>=0 B, free:>=138,2 GB)
  - SPOILER_IMAGES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/GeocachePhotos (av:true, files:>=0, size:>=0 B, free:>=138,2 GB)
  - ROUTING_BASE: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/routing (av:true, files:>=13, size:>=665,1 MB, free:>=138,2 GB)
  - ROUTING_TILES: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/routing/segments4 (av:true, files:>=5, size:>=665,1 MB, free:>=138,2 GB)
  - WHERIGO: content://com.android.externalstorage.documents/tree/primary:cgeo/document/primary:cgeo/wherigo (av:true, files:>=0, size:>=0 B, free:>=138,2 GB)
  - TEST_FOLDER: file:///data/user/0/cgeo.geocaching/files/unittest (av:true, files:>=0, size:>=0 B, free:>=138,2 GB)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary:cgeo (19. Nov. 2023, 16:41):RW

Database
-------
- File: /data/user/0/cgeo.geocaching/databases/data (v103, Size:290,7 MB) on system internal storage
- Data: {cg_attributes=96863, cg_caches=14438, cg_caches_lists=16436, cg_categories=0, cg_extension=74, cg_filters=11, cg_lists=55, cg_logCount=45677, cg_logImages=37314, cg_logs=412749, cg_logs_offline=1, cg_logs_offline_images=1, cg_logs_offline_trackables=4, cg_route=0, cg_search_destination_history=0, cg_spoilers=11422, cg_trackables=1043, cg_trail_history=1077, cg_variables=3778, cg_waypoints=12724}
- Extension Data: {DBEXTENSION_DOWNGRADEABLE_DBVERSION=1, DBEXTENSION_EMOJILRU=10, DBEXTENSION_FOUNDNUM=1, DBEXTENSION_LAST_TRACKABLE_ACTION=40, DBEXTENSION_ONE_TIME_DIALOGS=6, DBEXTENSION_POCKETQUERY_HISTORY=16}

--- End of system information ---

**Comment by Lineflyer** [comment]
Same here with current nightly

**Comment by moving-bits** [comment]
See #15944 for a fix
