### ISSUE TITLE
Make password edit fields visible optionally

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15950]
Support [Ticket #250728](https://cgeosupport.droescher.eu/scp/tickets.php?id=8336)
c:geo Version 2024.08.02-RC

A suggestion from user on support: make the password field of the geocaching.com connector authentification page "visible" optionally

In case this gets implemented I would suggest to extend this option to all password edit fields of course. Eg by using an "eye" icon on right side of text edit box (tapping toggles between "password visible"  and "password hidden")

**Comment by Lineflyer** [comment]
Is that an android supported option / supported input box type or would we need to customize such solution?
In the second case I would not invest the effort, but if its just like switching a style option...fair enough.
