### ISSUE TITLE
GPS Location refreshes every 10-30 seconds

### ISSUE THREAD

**Issue by wasu-code** [cgeo/cgeo#15951]
### Describe your problem!

Location updates in very long interval causing location indicator arrow to jump every few hundreds meters.

---

Issue seems to be present for me for a longer time now. Cgeo displays that accuracy is hight (eg. 3m) yet location arrows doesn't move. I belive it works as expected for a short while after lunching the app, then it starts to get worst.

Other apps (like Maverick or Google Maps) works with no issue. Additionally i noticed that launching split screen with cgeo and one of working apps makes cgeo update location correctly. (Doesn't work with those apps in background though).

Currently I have Google Play Store disabled, but Google Play Services are fully operational.

I tried to change "Use google play services" and "low energy mode" in cgeo settings, but with no improvement.

### How to reproduce?

1. Lunch cgeo
2. Center on user location
3. Use app for at least few minutes 

### Actual result after these steps?

Location updates every 10-30s. Location arrow stuck in place, then jumps to new location amd gets stuck again

### Expected result after these steps?

Location updates in real time

### Reproducible

Yes

### c:geo Version

2024.07.07

### System information

```text
## System information

c:geo version: 2024.07.07

Device:
-------
- Device type: M2004J19C (galahad_eea, Redmi)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.011
- Screen resolution: 1080x2220px (392x807dp)
- Pixel density: 2.53
- System font scale: 0.86 / used scale: 0.92
- Sailfish OS detected: false
- Google Play services: enabled - 24.16.16 (150400-629452829)
- Memory:  Available:880,4 MB, Total:3,7 GB, Threshold: 498,0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:166
- Set language: pl_PL (system default)
- System date format: dd.MM.y
- Time zone: GMT+02:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: 23 maj, 21:08
- Last auto backup: 1 sie, 14:28
- Routing mode: Bike (shortest.brf / trekking.brf / car-eco.brf / - / -)
- Live map mode: true
- Use unified map: false
- OSM multi-threading: false / threads: 1
- Map: Poland (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:D811-1621:AppStorage/CGEO/maps/Poland.map
  - Atts: Map data (c) OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: original parking visited
- LIVE: 🧭 Serwisy źródłowe ({"name":"🧭 Serwisy źródłowe","advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{}},{"type":"origin","config":{"values":["opencaching.pl","Internal","Geocaching.com Adventure Lab","Unknown caches","geocaching.com"]}},{"type":"NOT","children":[{"type":"AND","children":[{"type":"stored_list","config":{"values":["29"]}}]}]}]}})
- OFFLINE: Brak ({"advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{}},{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{}}]}})
- Additional stored filters: 8

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Nazwa użytkownika OK) / BASIC
   - opencaching.pl: Logged in (Nazwa użytkownika OK)
- Geocaching.com date format: M/d/yyyy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error //  (2024-08-04 15-04)
- Last successful login on geocaching.com: 2024-08-05 16-57
- Routing: internal / BRouter installed: false

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (2,9 GB free) v3 internal isDir(9 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (2,9 GB free) v3 internal isDir(9 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (2,9 GB free) v3 external non-removable isDir(349 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (2,9 GB free) v3 internal isDir(0 entries)
- Map render theme path: 
- Public Folders: #12
  - BASE: content://com.android.externalstorage.documents/tree/primary:AppStorage/CGEO/document/primary:AppStorage/CGEO (av:true, files:>=13, size:>=103,2 KB, free:>=2,9 GB)
  - OFFLINE_MAPS: content://com.android.externalstorage.documents/tree/D811-1621:AppStorage/CGEO/maps/document/D811-1621:AppStorage/CGEO/maps (av:true, files:>=8, size:>=1,3 GB, free:>=49,8 GB)
  - OFFLINE_MAP_THEMES: content://com.android.externalstorage.documents/tree/D811-1621:AppStorage/CGEO/maps/document/D811-1621:AppStorage/CGEO/maps/_themes (av:true, files:>=6, size:>=2,1 MB, free:>=49,8 GB)
  - OFFLINE_MAP_SHADING: content://com.android.externalstorage.documents/tree/D811-1621:AppStorage/CGEO/maps/document/D811-1621:AppStorage/CGEO/maps/_hgt (av:true, files:>=0, size:>=0 B, free:>=49,8 GB)
  - LOGFILES: content://com.android.externalstorage.documents/tree/primary:AppStorage/CGEO/document/primary:AppStorage/CGEO/logfiles (av:true, files:>=5, size:>=15,5 KB, free:>=2,9 GB)
  - GPX: content://com.android.externalstorage.documents/tree/D811-1621:AppStorage/CGEO/gpx/document/D811-1621:AppStorage/CGEO/gpx (av:true, files:>=0, size:>=0 B, free:>=49,8 GB)
  - BACKUP: content://com.android.externalstorage.documents/tree/primary:AppStorage/CGEO/document/primary:AppStorage/CGEO/backup (av:true, files:>=10, size:>=17,6 MB, free:>=2,9 GB)
  - FIELD_NOTES: content://com.android.externalstorage.documents/tree/primary:AppStorage/CGEO/document/primary:AppStorage/CGEO/field-notes (av:true, files:>=0, size:>=0 B, free:>=2,9 GB)
  - SPOILER_IMAGES: content://com.android.externalstorage.documents/tree/primary:AppStorage/CGEO/document/primary:AppStorage/CGEO/GeocachePhotos (av:true, files:>=2, size:>=3,9 MB, free:>=2,9 GB)
  - ROUTING_BASE: content://com.android.externalstorage.documents/tree/primary:AppStorage/CGEO/document/primary:AppStorage/CGEO/routing (av:true, files:>=8, size:>=87,7 KB, free:>=2,9 GB)
  - ROUTING_TILES: content://com.android.externalstorage.documents/tree/D811-1621:AppStorage/CGEO/routing/document/D811-1621:AppStorage/CGEO/routing (av:true, files:>=1, size:>=76,2 MB, free:>=49,8 GB)
  - TEST_FOLDER: file:///data/user/0/cgeo.geocaching/files/unittest (av:true, files:>=0, size:>=0 B, free:>=2,9 GB)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/D811-1621:AppStorage/CGEO/maps (24 maj, 16:51):RW
  - content://com.android.externalstorage.documents/tree/D811-1621:AppStorage/CGEO/gpx (24 maj, 16:54):RW
  - content://com.android.externalstorage.documents/tree/primary:AppStorage/CGEO (23 maj, 21:06):RW
  - content://com.android.externalstorage.documents/tree/D811-1621:AppStorage/CGEO/routing (24 maj, 16:54):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v103, Size:9,4 MB) on system internal storage

--- End of system information ---
```

**Comment by Lineflyer** [comment]
That would not be the first time users have issues with location service on Redmi phones :(

@wasu-code
Can you please try to switch off Google Play services in c:geo Menu - Settings - System and see whether anything changes?

**Comment by wasu-code** [comment]
I already tried, sadly that doesn't help

**Comment by Lineflyer** [comment]
In order to further analyze your problem, we need your help:

- Go to c:geo Menu - Settings - System und activate the "Debug Log" function
- Repeat the problematic function/action (e.g. move from your position and wait some update cycles of your position)
- Go again into c:geo Menu - Settings - System and select "Create Logfile"
- Send this logfile to us on support@cgeo.org and mention this issue number
- After creating the logfile you should disable the "Debug Log" function

Not sure if we can see anything in there, but lets try.

**Comment by wasu-code** [comment]
I already sent log to support mail. For context, that's how it looks on the map:  

<img src="https://github.com/user-attachments/assets/0dd27f1d-c8bd-42de-a5be-44183e6face5" width="500px"  />

It "jumps" every few seconds. It is possible that it jumps at the same intervals; so if the first jump took 17s next in this series will also take 17s (or at least that's what happened now). After a random number of "jumps" it may or may not unlock and show live location as expected. And then it will eventually get stuck again for some other amount of time.

<img src="https://github.com/user-attachments/assets/37b94377-4e43-4a16-8dc3-cfb2c94b4a00" width="500px"  />

When it's stuck amount of available satellites and gps accurracy is frozen until next jump happens.

**Comment by wasu-code** [comment]
...or i did not send it. After a few hours i received this error message from:

> We are sorry to inform that your mail message was not delivered to one or more recipients. Its fragment is attached to this e-mail.
You can find the error message below.
> `<support@cgeo.org>: connect to gorenc.org[193.95.241.239]:25: Connection timed out`

Is everything ok with your mail server?

**Comment by eddiemuc** [comment]
> ...or i did not send it. After a few hours i received this error message from:
> 
> > We are sorry to inform that your mail message was not delivered to one or more recipients. Its fragment is attached to this e-mail.
> You can find the error message below.
> > `<support@cgeo.org>: connect to gorenc.org[193.95.241.239]:25: Connection timed out`
> 
> Is everything ok with your mail server?

I sent a test message to support@cgeo.org. This was received in our ticket system. I also sent a.twst answer from the ticket system back to myself, this also worked fine. Also we received other tickets last night. So system and email server seem to work. 

Although indeed I could not find a ticket matching the GPS problems described in this issue. 

Maybe this was a temporary problem. Can you try again?

**Comment by Lineflyer** [comment]
It might be the attachment was too big to get through. Can you send it via some file hoster or upload it here:
https://cgeosupport.droescher.eu/_upload and send the provided link via mail

**Comment by Lineflyer** [comment]
now your log arrived.
Unfortunately it is completely empty. Are you sure you enabled "debug logging" and kept it running while the problem occurred before you exported it and send it to us?

**Comment by wasu-code** [comment]
1. Check "✅ Activate debug log"
2. Return to map and move to another position (until issue happen a few times)
3. Go back to settings and "Generate logfile"
4. Send log
5. Uncheck "🔲 Activate debug log"

If this is the right order then yes, I am sure of it

**Comment by Lineflyer** [comment]
Yes, its the right order.
Probably there is just nothing in the log as the map was in "non live" mode and additionally there is just no error event.

@eddiemuc 
Does "extended log" make any difference and let us see more?
Or maybe a debug log of the c:geo startup sequence to see whether there is an issue connecting to the location providers?

**Comment by wasu-code** [comment]
In the "beginning of main" section of both general and extemded log contnet was the same

**Comment by Lineflyer** [comment]
Not sure what you mean.
The log we received has this content, nothing else. Is there any more content in your log?
```
--------- beginning of system
--------- beginning of main
08-06 11:11:31.093 24887 26959 I cgeo    : [RxCachedThreadScheduler-16] [LogCat]Issuing command: [logcat, -d, AndroidRuntime:E, cgeo:D, cgeo.geocachin:I, *:S, -f, /data/user/0/cgeo.geocaching/cache/cgeo_tempfile_5269489362681032134.tmp] {DebugUtils.lambda$createLogcatHelper$4:100/DebugUtils.$r8$lambda$k2i1lIY1xmaeW1vUjc05PtMUJJY:0/DebugUtils$$ExternalSyntheticLambda1.run:0/AndroidRxUtils.lambda$andThenOnUi$2:93/AndroidRxUtils.$r8$lambda$bqzWo9nlvU86BvboB-9jhDWp5vc:0/AndroidRxUtils$$ExternalSyntheticLambda0.run:0/ScheduledRunnable.run:65/ScheduledRunnable.call:56}
```

**Comment by eddiemuc** [comment]
> Not sure what you mean. The log we received has this content, nothing else. Is there any more content in your log?
> 
> ```
> --------- beginning of system
> --------- beginning of main
> 08-06 11:11:31.093 24887 26959 I cgeo    : [RxCachedThreadScheduler-16] [LogCat]Issuing command: [logcat, -d, AndroidRuntime:E, cgeo:D, cgeo.geocachin:I, *:S, -f, /data/user/0/cgeo.geocaching/cache/cgeo_tempfile_5269489362681032134.tmp] {DebugUtils.lambda$createLogcatHelper$4:100/DebugUtils.$r8$lambda$k2i1lIY1xmaeW1vUjc05PtMUJJY:0/DebugUtils$$ExternalSyntheticLambda1.run:0/AndroidRxUtils.lambda$andThenOnUi$2:93/AndroidRxUtils.$r8$lambda$bqzWo9nlvU86BvboB-9jhDWp5vc:0/AndroidRxUtils$$ExternalSyntheticLambda0.run:0/ScheduledRunnable.run:65/ScheduledRunnable.call:56}
> ```

Looks like the logcat command somehow does not work on the device

**Comment by Lineflyer** [comment]
Not new such problems on XIaomi devices up to my experience.
Some of them really have issues with obligatory feature sets of Android (or even a lack of supporting them).

**Comment by eddiemuc** [comment]
> @eddiemuc Does "extended log" make any difference and let us see more? Or maybe a debug log of the c:geo startup sequence to see whether there is an issue connecting to the location providers?

Unfortunately I know close to nothing about how logcat works...
In code there's a flag `fullInfo` which is set to true for extended log and false for standard log. This is then used in code as follows:
```
 if (fullInfo) {
                        builder.command("logcat", "-d", "*:V", "-f", file.getAbsolutePath());
                    } else {
                        builder.command("logcat", "-d", "AndroidRuntime:E", "cgeo:D", "cgeo.geocachin:I", "*:S", "-f", file.getAbsolutePath());
                    }
```

**Comment by wasu-code** [comment]
> Not sure what you mean.
> The log we received has this content, nothing else. Is there any more content in your log?

No, there was nothing more in standard log.

In extemded log there is more in "beginning of system" section, but there were no errors or warnings

**Comment by wasu-code** [comment]
I tried mocking location with some ćfake gps app" and then I wasn't able to reproduce this issue.

I would say it's a device issue if not for the fact that the it is happening only in cgeo

**Comment by Lineflyer** [comment]
Sorry for not having any better idea:
Did you already try a clean reinstall of c:geo?

**Comment by wasu-code** [comment]
No, I only tried cleaning cache or force stopping the app. But i guess there is nothing left to try but to make a backup and reinstall.

I will reinstall cgeo, do some testing and get back to you (probably tomorrow)

**Comment by wasu-code** [comment]
✅ Issue Solved

So the issue was more or less on my side. I was using [Trailblazer](https://play.google.com/store/apps/details?id=org.games4all.trailblazer.prod) app (it works in background and uncovers the part of the map you already visited).
Among settings in the app there was "Tracking speed" that allows for changing the value in range 1-10 and defaults to 5, to lower battery usage:

> Lower values reduce battery usage but might cause missed sectors, higher values increase accuracy at the expense of higher battery usage.

I guess Trailblazer was setting intervals of how often location should be updated in system or something like this. Probably other apps request this themselves and therefore receive correct location and c:geo is just using intervals that Trailblazer has set (?)

When moving faster than 18 km/h this tracking speed wasn't enough and that caused "jumps".

Of course disabling Trailblazer or changing "Tracking speed" in its settings solves the issue. 
Thank you for your time 🙏

**Comment by eddiemuc** [comment]
Glad that a solution was found. I will close here.
