### ISSUE TITLE
Spoiler images no longer loaded

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15959]
Spoiler images are no longer loaded. 

Example cache: GC2JVEH. This cache has 3 spoiler images, but they are no longer loaded.
This error makes the following test case fail: [cgeo.geocaching.CgeoApplicationTest.testSearchByGeocodeBasis](https://ci.cgeo.org/job/cgeo-CI_PR-build/9151/testReport/junit/cgeo.geocaching/CgeoApplicationTest/testSearchByGeocodeBasis/)

This seems to be caused by a HTML change from geocaching.com

**Comment by eddiemuc** [comment]
Fixed with PR #15955

**Comment by moving-bits** [comment]
I tried a test build on CI, which worked out fine (build green + APK downloadable) - seems that the runner for release builds is not affected from current CI problems. I'll start working on a new beta then.

**Comment by bekuno** [comment]
> I tried a test build on CI, which worked out fine (build green + APK downloadable) - seems that the runner for release builds is not affected from current CI problems. I'll start working on a new beta then.

The job `cgeo release candidate` does not install on a virtual device and does not run tests.
Therefore, we don´t have the error `Could not create ADB Bridge` there.

**Comment by moving-bits** [comment]
Play Store is crunching a new beta now. Last time it took app. 36 hours...

**Comment by moving-bits** [comment]
PRelated PR has been merged, but auto-close did not work, so let's close manually.
