### ISSUE TITLE
Geocaching.com login does not seem to work any more

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15969]
Geocaching.com Login does not seem to work any more. Result ends in "communication error" and/or "failed login". Premium members are shown as "Basic":

![image](https://github.com/user-attachments/assets/a8c3ec55-706c-45a0-a24d-35a6fc253a5f)

There is already about half a dozen of tickets on support, and I can reproduce the problem on my personal phone as well.

My first guess is a change on the gc.com website.

**Comment by eddiemuc** [comment]
## System information

c:geo version: 2024.08.12-4557188 developer build

...

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Not logged in (Login failed)
- Geocaching.com date format: dd.MM.yyyy
- Geocaching.com website language: UNKNOWN
- Last login error on geocaching.com: communication error //  (2024-08-12 14-58)
- Last successful login on geocaching.com: 2024-08-11 06-30
- Routing: internal / BRouter installed: false

...

**Comment by murggel** [comment]
In debugger I can see a `java.net.ProtocolException: unexpected end of stream` but don't know where the culprit is...

![image](https://github.com/user-attachments/assets/471ee04b-34d5-46d1-883d-9c0629d45b0e)

**Comment by murggel** [comment]
Seems to work again - just re-authenticate

**Comment by moving-bits** [comment]
Same here - did not work about an hour ago (even when trying to reauthenticate), but is working again since a couple of minutes.

**Comment by eddiemuc** [comment]
Same here. Looks like we ditched a bullet on this one :-)

I will close and inform users on support.
