### ISSUE TITLE
Log images in remote locations cannot be used any more

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15972]
c:geo version: 2024.08.09-RC
Support [Ticket #715663](https://cgeosupport.droescher.eu/scp/tickets.php?id=8387)

In log image picker, images from remote locations cannot be opened any more.

I believe this is caused by one of my changes: https://github.com/cgeo/cgeo/pull/15949

I believe that the statement `intent.addCategory(Intent.CATEGORY_OPENABLE)`; has to be removed in method `ImageActivityHelper.getMultipleItemsFromStorage()`

**Comment by moving-bits** [comment]
Another observation, maybe related:
When selecting images during "edit log", I'll get a file selector only, whereas in the past I got an image selector (IIRC). A file selector can be used to select images as well, but you'll have to navigate to /DCIM/camera manually, then revert sort order - and repeat those steps for every image. Also, only a very tiny thumbnail will be displayed, which can make selecting the correct image quite hard. - Those effects may be device- or vendor-specific, though, haven't cross-checked yet.

**Comment by eddiemuc** [comment]
> Another observation, maybe related: When selecting images during "edit log", I'll get a file selector only, whereas in the past I got an image selector (IIRC). A file selector can be used to select images as well, but you'll have to navigate to /DCIM/camera manually, then revert sort order - and repeat those steps for every image. Also, only a very tiny thumbnail will be displayed, which can make selecting the correct image quite hard. - Those effects may be device- or vendor-specific, though, haven't cross-checked yet.

It is possible that Android behaves differently because I now use the Intent ACTION_OPEN_DOCUMENT instead of ACTION_GET_CONTENT. This is because only the former allows setting of a directory to open (yet another Android flaw...). Anyway, on my device I can still select "Images" and then get all the images in the usual fashion. Should I switch back the action? In that case the "open own images" is not quite possible...

**Comment by moving-bits** [comment]
> Should I switch back the action? In that case the "open own images" is not quite possible...

Can this be differentiated between the buttons?
To my understanding, the new ACTION is only required for "open own images", thus the right-most button, whereas selecting an image from Android's image gallery is behind the first button (at least that's the button I was referring to).

**Comment by eddiemuc** [comment]
> Can this be differentiated between the buttons?\nTo my understanding, the new ACTION is only required for \"open own images\", 

Good idea, I applied this to the PR

**Comment by moving-bits** [comment]
> > Can this be differentiated between the buttons?\nTo my understanding, the new ACTION is only required for "open own images",
> 
> Good idea, I applied this to the PR

Thanks for adding this. I can test this only after releasing it with a new beta or release, as the affected device cannot install nightly versions (and my "unrestricted" test device does not have the described issue).

**Comment by moving-bits** [comment]
> Thanks for adding this. I can test this only after releasing it with a new beta or release, as the affected device cannot install nightly versions (and my "unrestricted" test device does not have the described issue).

fix confirmed with 2024.09.01, thanks
