### ISSUE TITLE
"Start talking" not translated in French

### ISSUE THREAD

**Issue by Corona21** [cgeo/cgeo#15982]
### Describe your problem!

My phone is in French.
All texts in cgeo are in French, except the "Start talking" menu item (in English)

### How to reproduce?

- open a cache
- click on the 3 dots icon (top right)
==> the menu is open

### Actual result after these steps?

the second menu item is "Start talking"

### Expected result after these steps?

the second menu item is in French (ex: "Commencer à parler")

### Reproducible

Yes

### c:geo Version

2024.07.07

### System information

```text
on all tested phones.
Ex: Samsung A15
```

**Comment by SammysHP** [comment]
Translations are managed via Crowdin:

https://crowdin.com/project/cgeo

If you find a missing translation, it was either not translated yet, or just not translated in time for the latest release. You can help by suggesting new translations on Crowdin. Afterwards they have to be approved by a proofreader.

**Comment by Corona21** [comment]
@SammysHP, thanks for pointing to crowdin.
The translation is already present in crowdin (for 9 months, translated but not approved)
But I am almost sure it has worked some time ago (maybe 1 year ago).

**Comment by SammysHP** [comment]
It's possible it got invalidated due to changes in the original text. Then the translation must be approved again.

**Comment by Corona21** [comment]
ok. 
I have added new proposals for cache_menu_speechActivate and cache_menu_speechDeactivate.
Hope something will be approved soon :)

**Comment by bekuno** [comment]
I approved.
Now the last two entries have to be translated.

**Comment by Corona21** [comment]
@bekuno , I have translated the 2 remaining items (init_coordsearchlimit_description and fav_points_remaining)
