### ISSUE TITLE
Logging from popup keeps cache highlighted

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#15998]
### Describe your problem!

Logging a cache from the popup closes the popup, but the cache stays highlighted.

### How to reproduce?

Log a cache from the popup. 

### Reproducible

Yes

### c:geo Version

2024.08.18-NB-80abca2

**Comment by moving-bits** [comment]
Can reproduce this with current `master`, but cannot explain it:

How to reproduce:
- Add a log message to `MapMarkerUtils.addHighlighting` and a different one to `MapMarkerUtils.removeHighlighting`
- Open UnifiedMap and select a cache
- Use overflow menu => log visit => return to map without sending log (an offline log gets created)

Result: map still shows highlighting indicator

But: In logcat you can see messages like this:
```
addHighlighting: cgeo.geocaching.unifiedmap.geoitemlayer.GeoItemLayer@9bb5710
removeHighlighting: cgeo.geocaching.unifiedmap.geoitemlayer.GeoItemLayer@9bb5710
removeHighlighting: cgeo.geocaching.unifiedmap.geoitemlayer.GeoItemLayer@9bb5710
```

So the methods get called as expected, but the map seems to not remove the related items. Anything I'm missing here - e. g.: do we need to call some "update" function after calling `layer.remote(...)`?

**Comment by eddiemuc** [comment]
No call of any additional method should be necessary for the removal to be processed. But there might be a bug in the GeoItemLayer too of course?

If you turn on debug mode you should find messages like ADD '<key>' and REMOVE '<key>' in the log as well?

**Comment by eddiemuc** [comment]
> No call of any additional method should be necessary for the removal to be processed. But there might be a bug in the GeoItemLayer too of course.
> 
> If you turn on debug mode you should find messages like `ADD '<key>'` and `REMOVE '<key>'` in the log as well. Are those there?

**Comment by eddiemuc** [comment]
No call of any additional method should be necessary for the removal to be processed. But there might be a bug in the GeoItemLayer too of course?

If you turn on debug mode you should find messages like ADD '<key>' and REMOVE '<key>' in the log as well?

One thought: "log visit" creates a new activity, thus I assume the original map activity is destroyed. When going back from log to map, then the map activity is assumingly recreated:
- I assume the map activity also recreates all geoitem layers in this case
 Correct?
- then could the highlighting be a result of a stale saved-state of the map activity?

**Comment by moving-bits** [comment]
Thanks for your thoughts. I've added "ADD" and "REMOVE" messages to `MapsforgeVtmGeoItemLayer.add` and `remove`, but log seems to be fine:

```
10:20:51.438 cgeo            cge...developer  E  [main] addHighlighting: cgeo.geocaching.unifiedmap.geoitemlayer.GeoItemLayer@819789e {MapMarkerUtils.addHighlighting:898/UnifiedMapActivity.handleTap:1065/UnifiedMapActivity.onTap:1007/AbstractMapFragment.onTapCallback:181/MapsforgeVtmFragment.access$000:67/MapsforgeVtmFragment$MapEventsReceiver.onGesture:460/Layers.handleGesture:266/Map.handleGesture:429}
10:20:51.520 cgeo            cge...developer  E  [main] ADD MARKER:,icon[N 52° 31.000' · E 013° 24.000']:bm:99x99px, hash:101085360, angle:0.0, x/yAnchor:0.5/1.0, flat:false,zLevel:100 {MapsforgeVtmGeoItemLayer.add:187/MapsforgeVtmGeoItemLayer.add:53/GeoItemLayer$MapWriter.add:143/GeoItemLayer$MapWriter.add:115/AsynchronousMapWrapper$MapChangeRunner.processAddCommand:362/AsynchronousMapWrapper$MapChangeRunner.processQueue:309/AsynchronousMapWrapper$MapChangeRunner.run:373/HandlerScheduler$ScheduledRunnable.run:123}
10:20:51.520 cgeo            cge...developer  E  [main] ADD MARKER:,icon[N 52° 31.000' · E 013° 24.000']:bm:99x99px, hash:193132136, angle:0.0, x/yAnchor:0.5/1.0, flat:false,zLevel:101 {MapsforgeVtmGeoItemLayer.add:187/MapsforgeVtmGeoItemLayer.add:53/GeoItemLayer$MapWriter.add:143/GeoItemLayer$MapWriter.add:115/AsynchronousMapWrapper$MapChangeRunner.processAddCommand:362/AsynchronousMapWrapper$MapChangeRunner.processQueue:309/AsynchronousMapWrapper$MapChangeRunner.run:373/HandlerScheduler$ScheduledRunnable.run:123}
```

and later on:

``` 
10:20:55.573 cgeo            cge...developer  E  [main] REMOVE MARKER:,icon[N 52° 31.000' · E 013° 24.000']:bm:99x99px, hash:193132136, angle:0.0, x/yAnchor:0.5/1.0, flat:false,zLevel:101 {MapsforgeVtmGeoItemLayer.remove:263/MapsforgeVtmGeoItemLayer.destroy:357/GeoItemLayer$MapWriter.destroy:201/AsynchronousMapWrapper.lambda$destroy$6$cgeo-geocaching-utils-AsynchronousMapWrapper:180/AsynchronousMapWrapper$$ExternalSyntheticLambda6.run:2/HandlerScheduler$ScheduledRunnable.run:123/Handler.handleCallback:942/Handler.dispatchMessage:99}
10:20:55.573 cgeo            cge...developer  E  [main] REMOVE MARKER:,icon[N 52° 31.000' · E 013° 24.000']:bm:99x99px, hash:101085360, angle:0.0, x/yAnchor:0.5/1.0, flat:false,zLevel:100 {MapsforgeVtmGeoItemLayer.remove:263/MapsforgeVtmGeoItemLayer.destroy:357/GeoItemLayer$MapWriter.destroy:201/AsynchronousMapWrapper.lambda$destroy$6$cgeo-geocaching-utils-AsynchronousMapWrapper:180/AsynchronousMapWrapper$$ExternalSyntheticLambda6.run:2/HandlerScheduler$ScheduledRunnable.run:123/Handler.handleCallback:942/Handler.dispatchMessage:99}
10:21:00.162 cgeo            cge...developer  E  [main] removeHighlighting: cgeo.geocaching.unifiedmap.geoitemlayer.GeoItemLayer@819789e {MapMarkerUtils.removeHighlighting:918/UnifiedMapActivity.clearSheetInfo:1107/AbstractNavigationBarMapActivity.sheetRemoveFragment:155/AbstractNavigationBarMapActivity.sheetManageLifecycleOnStart:194/UnifiedMapActivity.onStart:1162/Instrumentation.callActivityOnStart:1543/Activity.performStart:8330/ActivityThread.handleStartActivity:3670}
```

(I'd searched for occurrences of `101`, which is z-level for the marker)

So the marker gets actually removed before calling `MapMarkerUtils.removeHighlighting`, but does not get added again (as this is done by calling `MapMarkerUtils.addHighlighting`, which is called only by `UnifiedMapActivity.handleTap`).
