### ISSUE TITLE
On the CI release job, the ftp step did not work

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#16007]
On the CI release job, the ftp step did not work, see e.g. https://ci.cgeo.org/job/cgeo%20release/160/console.
~~~
00:20:36  + ftp
00:20:36  ftp: connect: Connection refused
~~~
@mucek4 Please check the ftp server.

_Originally posted by @bekuno in https://github.com/cgeo/cgeo/issues/15773#issuecomment-2298296290_

**Comment by moving-bits** [comment]
@Lineflyer 
Do you know why we upload the release apk to cgeo.org (as it seems)? We could not find a reference on the homepage to it, and official release builds are available on Github meanwhile. Maybe this (no longer working) step can be removed from our CI scripts.

**Comment by fm-sys** [comment]
There is the download link https://download.cgeo.org/cgeo-release.apk

However, it indeed seems to be not used anywhere

**Comment by kumy** [comment]
IIRC I think this is (also)the source for the f-droid repo. Nightly builds are taken from there as of main releases. Scripts can be updated to use GH releases. Are NB uploaded on GH too?

**Comment by moving-bits** [comment]
> Are NB uploaded on GH too?

No, only release apk get uploaded to GH (manually on publishing a release on GH)

> > However, it indeed seems to be not used anywhere
> 
> It's used there https://github.com/cgeo/cgeo-fdroid-base/blob/master/scripts/fdroid-update.sh#L9C1-L9C8

If I understand the script correctly, it reads nightly apk from cgeo.org, but release apk from GH.

**Comment by kumy** [comment]
> If I understand the script correctly, it reads nightly apk from cgeo.org, but release apk from GH.

[right](https://github.com/cgeo/cgeo-fdroid-base/blob/master/scripts/fdroid-update.sh#L96C10-L96C105)

**Comment by mucek4** [comment]
Yes. FTP server was stopped and it no longer works. It's replaced by SFTP and I have fixed the nightly build, but looks like I forgot the release one. Will take a look.

**Comment by mucek4** [comment]
Should be done. SFTP was already there, just nobody disabled FTP.
