### ISSUE TITLE
Some spoiler images are not showing up, even not under the images tab.

### ISSUE THREAD

**Issue by todeit02** [cgeo/cgeo#16003]
### Describe your problem!

Sometimes when you open the listing on geocaching.com you see there is a spoiler image provided.
However in the images tab this image is not even displayed as a regular image.

### How to reproduce?

Open a Geocache with rather old spoiler image.

### Reproducible

Yes

### c:geo Version

2024.07.07

**Comment by SammysHP** [comment]
This is already fixed and will be included in the next release.

See https://github.com/cgeo/cgeo/issues/15959 for more details.
