### ISSUE TITLE
Edit image should set "Caption" field with focus

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#16011]
### Tell us your idea!

Upon entering the "Edit image" dialog one sees this screen: 
![Screenshot_20240825-195255_cgeo](https://github.com/user-attachments/assets/380441f9-712b-43ac-be46-e2c0786942ab)

### What solution would you suggest?

Since (at least IMO) the most likely action would be to edit image caption, it would be in the user's advantage to alraedy have focus on the "Caption" field such that the soft keyboard pops up.

Like this: _(ie without the additiona user interraction to set focus to the field)_
![Screenshot_20240825-195258_cgeo](https://github.com/user-attachments/assets/9a88655e-ee55-46ea-887c-9fb024aee56c)

**Comment by moving-bits** [comment]
See PR #16107
