### ISSUE TITLE
different strategy for downloading static maps?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#1602]
When downloading new caches, I also let c:geo create static maps for caches and waypoints. I often run into the Google static maps limitation after a low number of caches, because we still download those maps to fast. This leads to having all 5 static maps for some caches (and waypoints) and no static maps for all other ones.

I was thinking if it would help to first download one zoom level (the highest one) for _all_ caches, then the next zoom level and so on. That way one would have at least something for all caches, even if the throttling of Google kicks in.

Any thoughts on that?

**Comment by Lineflyer** [comment]
Closing this issue as obsolete, as Google static maps are no longer available (without payment).
So whatever replaces them needs a new implementation anyway.
