### ISSUE TITLE
Compass / GPS temporary lock's direction on c:geo WheriGo

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#16035]
### Describe your problem!

Hi

I know that the integration of Wherigo's in c:geo is still under development. However, as I recently created a new cartridge, I detected a bug in c:geo. I'm not sure were to report the bug, but since the development it's beeing done in c:geo, here it goes:

Sometimes c:geo dosen't use my current position when playing a whereigo cartridge. After I enter a zone, the compass keeps assuming the previous orientation. And the recovery to the correct the position and orientation is slow.

### How to reproduce?

The bug I detected is as follows: I have two zones, A (North) and B (South), separated by 100 meters. When I move from Zone A to Zone B, the distance to A increases, and the distance to B decreases. But when I reach Zone B and return to A, sometimes it doesn't assume the correct orientation and distances itself from both A and B, as if I were still heading South when I am actually heading North. It's like after enter a zone, it locks the orientation, and when I move detects moving, but goes to the wrong direction.

The quickest solution is to turn the GPS off and then on again on the phone. The alternative is to stop, and after about 20 seconds, the distance gradually starts to correct itself, as if there were a buffer, as it recovers about 2/3 meters per second.

### Actual result after these steps?

My current position isn't correct, and the recovery is slow.

### Expected result after these steps?

The compass / gps always use my current position

### Reproducible

Yes

### c:geo Version

2024.08.31-RC

**Comment by SammysHP** [comment]
So this is already a problem with c:geo and not related to WIG at all? Sounds more like a device issue to me.

**Comment by rouroni1** [comment]
Next saturday I will make a video of the issue.

The issue is present on my phone (Poco F4 GT), but also exist on OnePlus phone also.

**Comment by rouroni1** [comment]
I managed to make the video, I'll put a link to YouTube.

https://youtu.be/7RQ6QFg_Ofs

4:00 - 4:30 distance to the right bank should decrease
5:00 - 5:10 turning GPS off and on resolved the error
6:40 - 07:10 despite moving away from the right bank, it assumed I was going in the opposite direction
07:40 - 07:55 it again assumed I was returning to the right bank, when I was going in the opposite direction
08:00 - 08:10 turning GPS off and on resolved the error
10:10 - 10:30 assumes I'm going to the left bank, when I'm actually going to the right bank
The anomaly persisted several times.

From minute 18:40 onwards, I decided to always turn GPS off and on when entering a Zone
18:46 - GPS Off/On - Load Sheep on the Boat, and go to the left bank - Ok
20:11 - GPS Off/On - Return to the right bank - Ok
21:31 - GPS Off/On - Load Wolf on the Boat, and go to the left bank - Ok
22:50 - GPS Off/On - Load Sheep on the Boat, and go to the right bank - Ok
24:05 - GPS Off/On - Load Lettuce on the Boat, and go to the left bank - Ok
25:26 - GPS Off/On - Return to the right bank - Ok
26:45 - GPS Off/On - Load Sheep on the Boat, and go to the left bank - Ok
28:05 - GPS Off/On - Leave the boat and go to the Farm - Ok
33:05 - Enter Farm / End of cartridge, Ok

**Comment by fm-sys** [comment]
I wonder how you were able to activate the by far not yet completed cgeo internal WIG implementation at all. 😅

This functionality should be invisible for users, we know that probably many things are not yet working, and we cannot provide support for it at this point in time. Sorry!

**Comment by rouroni1** [comment]
I usually keep an eye on what's being developed in c:geo, and since Wherigo are geocaches that I really enjoy doing, I saw on the wiki how to activate them.

Yes, I'm aware that there's still a lot to be developed, so if you think it's best, feel free to close this case.

Thank you. 🙂

**Comment by eddiemuc** [comment]
@rouroni1 
While Wherigo-Support in c:geo is indeed not even at alpha-state, I appreciate anyone who plays around with the current version of it to give insights where there are still bugs. This is why I put up the Wiki page on how to activate it (which I assume you have found). So thanks a lot for your effort!

The behaviour you describe should NOT happen at current stage of development. I can't access the video unfortunately so I can't check it, it is marked as "private".

One last thing: Wherigo-support in c:geo is not called WhereYouGo. WhereYouGo is and will remain a separate app.

**Comment by rouroni1** [comment]
@eddiemuc 

As I thought there would be no follow-up, I disabled the video, but I've just made it visible again.

Thank you, and if any testing is needed, I'm available.

**Comment by rouroni1** [comment]
Today I've tested again the same wherigo cartridge with version 2024.10.05-NB-33b5ab3 and the GPS issue was gone.

So I'll close this issue.
