### ISSUE TITLE
[Nightly] Crash on waypoint projection

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#16041]
### Describe your problem!

When trying to add a projection to a waypoint, c:geo crashes as soon as you try to enter the very first numeric value

### How to reproduce?

1. create a new waypoint
2. set wp's coordinates to e. g. cache coordinates
3. add projection => Bearing (you can also chose Offset, makes no difference)
5. try to enter a number into either distance or bearing field ...

### Actual result after these steps?

6. c:geo immediately crashes

### Expected result after these steps?

Guess what.  ;)

### Reproducible

Yes

### c:geo Version

2024.09.07-NB-d93f2b2

**Comment by murggel** [comment]
Can reproduce  - I will look at it

**Comment by murggel** [comment]
Will be fixed with PR #16042

**Comment by MagpieFourtyTwo** [comment]
Thx for the quick fix! Will crosscheck as soon as it arrives in nightly.

**Comment by MagpieFourtyTwo** [comment]
Working again - thx!
