### ISSUE TITLE
No "set as found" functionality on adventure lab stages

### ISSUE THREAD

**Issue by campdave** [cgeo/cgeo#16055]
I've downloaded adventure lab stages from lab2gpx for several years (saving them as AL as specified in the documentation)

In an area where there are lots of adventure labs, being able to mark them as found is really helpful.

I noticed today they weren't appearing on the live map. I had to go into my stored list and click the map button from the list to show them on a map.

When I clicked on an adventure lab stage, the option to "mark as found" was no longer there.

I was able to fudge usual functionality by redownloading from lab2gpx and selecting the stages as virtual caches rather than adlabs.

### How to reproduce?

1 click on adventure lab stage
2 click on three arrows at top right of window
3 mark as found is not there

### Actual result after these steps?

1 click on adventure lab stage
2 click on three arrows at top right of window
3 mark as found is not there

### Expected result after these steps?

1 click on adventure lab stage
2 click on three arrows at top right of window
3 mark as found is able to be selected, marks the stage with a found icon

### Reproducible

Yes

### c:geo Version

2024.09.01

**Comment by campdave** [comment]
![Screenshot_2024-09-08-19-10-58-987](https://github.com/user-attachments/assets/fffa75d8-8ca3-4bf8-a216-128dc6684e85)
The yellow circle is where this used to appear

**Comment by eddiemuc** [comment]
c:geo is now able to detect the Adventure Lab found state from the server (if you use the Lab connector). If you want to use the manual found state instead, go to c:geo Settings -> Services -> geocaching.com Adventure Labs and turn on the "Manual Found State":
![image](https://github.com/user-attachments/assets/e0fd2ca7-b23f-48da-a832-2408fa3a19fd)

**Comment by campdave** [comment]
Thanks, that's great. Even though I had completed the stage, my stages were not showing up as found in cgeo.

I've set it back to the way I'm used to doing it 🙂
