### ISSUE TITLE
OrganicMaps intent wrong

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16054]
The intent to navigate with Organic Maps requires another confirmation in that app (use as  "navigate to", "navigate from" or "add stop"). Let's see if there's another intent that enables a direct "navigate to".

**Comment by SammysHP** [comment]
Do we even want to change that? It would allow the user to extend their route in the current implementation.

**Comment by ztNFny** [comment]
It's implement as direct "set as target" for all other apps. And to me the current behaviour is annoying as ...
I use c:geo in connection with Android Auto, selecting the next cache as navigation target. Then I have to switch OM from AA to Phone mode, on the phone confirm I want to use it as target, then switch back OM to AA mode - this takes about 20s as opposed to 2s with every other navigation app.

**Comment by ztNFny** [comment]
OrganicMaps currently doesn't provide intents required to offer any other routing modes, closing here.
