### ISSUE TITLE
Wishlist: background service to auto-download caches

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#1605]
Hi, yesterday I had an idea, because downloading caches in terrain takes long time, it could be very usable to have OPTIONAL background service which (when certain conditions are met) will download/update caches from predefined locations and optionally in some diameter around device.

Conditions which may be checked by this service are charging/battery level, connection type (possibility to set wifi only).

I know, that implementing this may take long time, but it could be very useful.

I think, that in long term period I can implement this. Please say me your suggestions, how to do this as best as possible.

**Comment by Lineflyer** [comment]
Meanwhile we implemented cache downloading/refreshing in a background thread. 
So IMHO this very old feature request should mostly be covered by that.
