### ISSUE TITLE
Logbook Regeneration - Add ability to export cache logs in a tabular form

### ISSUE THREAD

**Issue by kaminskimk** [cgeo/cgeo#16068]
### Tell us your idea!

The idea is to give users ability to export cache logs (Finds, DNF, Notes, etc.) to a tabular form, for example CSV file with following columns:

- Username
- Entry Type
- Date
- Text

One of the ways how it can be used is for logbook regeneration when the original cache/logbook gets damages or is lost. Using this feature, the (reactivated) cache owner can export all the logs, filter them to "Found" type, sort by date and print a new logbook with a list of all historical finds instead of empty paper. 

### What solution would you suggest?

In the cache details view, click on three dots button -> Share/Export -> Logbook Entries (CSV)

**Comment by SammysHP** [comment]
This is easy to do with GSAK for example, but not a feature I'd want or need in a portable app that is intended for finding caches. Also c:geo only knows about the 30 or so recent logs.
