### ISSUE TITLE
Buggy track elevation graph pops up sometimes

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#16064]
### Describe your problem!

Regularly, but not all the time, this happens:

A track elevation graph pops up (and I don't know why), and it **has no controls so cannot be closed again**.

![2024-09-06 12 54 56](https://github.com/user-attachments/assets/bb7b56a2-821b-4405-8a01-05efef8cee36)

### How to reproduce?

Unclear to me what triggers it. It has something to do with me tapping the screen, but it is not reproducible. But happens quite often.

### Reproducible

Unclear

### c:geo Version

2024-09-01

**Comment by moving-bits** [comment]
Elevation charts are being displayed for individual routes and tracks/routes loaded from GPX files only.

Do you have composed an individual route (default color: blue) or loaded a GPX track/route (default color: green) and maybe hidden one of those? (Although that would not explain the missing UI elements.)

**Comment by dcjkfgdjhd** [comment]
Yes, absolutely, the red line in the screenshot is a GPX track and the length of 400km is correct.

But I do not understand why it sometimes suddenly shows up like this and without UI elements.

(Additionally, the elevation chart looks very suspicious. Notice the sudden vertical drops. I think this is a bug caused by the fact that one GPX file contains multiple tracks. At the end of each track, there seems to be a drop, when it really should be continuously going up.)

**Comment by moving-bits** [comment]
ok, tapping on a track brings up the elevation chart as well. And tapping on the track again will remove the chart.

The sudden drops in the elevation chart may be due to the data in the GPX file - is elevation info provided for every single point in the GPX file?

This still leaves the question open why the UI elements are missing. Could you provide us with the GPX file (either here or by sending it to our support email, with reference to this GitHub issue)? Then we would be able to debug into it.

**Comment by dcjkfgdjhd** [comment]
> ok, tapping on a track brings up the elevation chart as well. And tapping on the track again will remove the chart.

I know, but it sometimes happens in unexpected circumstances and then the UI is missing. 

But I have not discovered a pattern yet. Will report back if I notice any regulartity.

By the way, I would consider replacing "tapping" by "long pressing" as method to open the chart. Currently I accidentally open the chart too often.

> The sudden drops in the elevation chart may be due to the data in the GPX file - is elevation info provided for every single point in the GPX file?

I tested this, it is a real bug, I created a separate issue for it: #16082

**Comment by moving-bits** [comment]
> By the way, I would consider replacing "tapping" by "long pressing" as method to open the chart. Currently I accidentally open the chart too often.

Long-tap opens a context menu for the track/route. So you propose to add a "show elevation chart" to the context menu and remove the short tap on track/route?

> > The sudden drops in the elevation chart may be due to the data in the GPX file - is elevation info provided for every single point in the GPX file?
> 
> I tested this, it is a real bug, I created a separate issue for it: #16082

Thanks, I'll look into it.

**Comment by dcjkfgdjhd** [comment]
> So you propose to add a "show elevation chart" to the context menu and remove the short tap on track/route?

That sounds like a good solution to me.

**Comment by moving-bits** [comment]
> > So you propose to add a "show elevation chart" to the context menu and remove the short tap on track/route?
> 
> That sounds like a good solution to me.

See PR #16105
