### ISSUE TITLE
Edit signature dialog should have focus and bring up keyboard

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#16072]
### Tell us your idea!

Under settings / Logging, one can edit a default signiture to be appended to each log entry. 
When tapping on it, a dialog opens to edit the signiture text. 
When this dialog opens, it has no focus and the soft-keyboard is not up. User must additionally tap on the input field to start typing.

![Screenshot_20240904-092228_cgeo](https://github.com/user-attachments/assets/bc9c7e25-603a-4b35-94fd-872bab44658c)

### What solution would you suggest?

Since the most logical action is to start typing something, I suggest that the text input to have focus and thus soft-keyboard is automatically brought up.

**Comment by moving-bits** [comment]
It's easy to set the focus on the right field of a `TemplateTextPreference` instance, but I was not able to make it open the soft keyboard yet:

in `TemplateTextPreference.launchEditTemplateDialog()`, add after `dialog.show()`:
``` 
ViewUtils.showKeyboard(dialog.getContext(), isSignature || StringUtils.isNotBlank(editTitle.getText()) ? editText : editTitle);
```

This new method being defined as:
```
public static void showKeyboard(final Context context, final View view) {
    view.requestFocus();
    final InputMethodManager imm = (InputMethodManager) context.getSystemService(Context.INPUT_METHOD_SERVICE);
    if (imm != null) {
        imm.showSoftInput(view, InputMethodManager.SHOW_IMPLICIT);
    }
}
```

I also tried some other solutions proposed on StackExchange, like using `toggleSoftInputFromWindow()` or different flags in the method call, but nothing did work so far.

**Comment by andrixnet** [comment]
Since this appears in what looks like a modal dialog, probably behaves differently from let's say the log page. 
One thing I noticed (end-user): 
Opening "default caption for log images" sets focus and brings up soft-keyboard. 
The only difference is that here it's like a HTML input type="text", while the signiture dialog shows a HTML like textarea.

**Comment by moving-bits** [comment]
Thanks for pointing me to the different behavior of "default caption for log images" and signature dialog.

Found a working solution now, see PR #16106.
