### ISSUE TITLE
Option to disable "3D buildings" in unified map.

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#16073]
### Tell us your idea!

The new "unified map" brings new features and functionalities, including "3D rendering" of buildings at high zoom levels. 

While I am sure this has either use or attractiveness to some, it can also be somewhat confusing. 
It is after all ... a map.

### What solution would you suggest?

My request is for a setting to enable/disable the "3D rendering".

### Is there an alternative?

At this time only using legacy map engine.

**Comment by Lineflyer** [comment]
Didn't we discuss and include that just a few weeks ago?

**Comment by SammysHP** [comment]
Yes. Closing as duplicate of #15723.
