### ISSUE TITLE
logging: long-tap on date to set "previous date"

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16085]
The date picker in log dialog defaults to today. But sometimes there's the need to log several caches for another date, e.g. because you forgot to mark them as found yesterday. We could make the access to "previous log date" easily accessible by implementing it as long-tap action on the date picker.

Would require 2 changes:
- on sending a log remember the log date
- long-tap listener on the button

**Comment by moving-bits** [comment]
How about remembering the last used log date for current session? No need for a "hidden" function (long tap) then. 
This would be #11890.

**Comment by ztNFny** [comment]
> How about remembering the last used log date for current session? No need for a "hidden" function (long tap) then. 
> This would be #11890.

For me cgeo is often running multiple days without restart, so I'd have to fix the date quite often. IMHO non-today should be a manual action.

**Comment by moving-bits** [comment]
> For me cgeo is often running multiple days without restart, so I'd have to fix the date quite often. IMHO non-today should be a manual action.

Understood (and similar for me), but if I understood the linked discussion correctly, it would not remember "last used log date" "forever", but only for a certain amount of time (like an hour or so, or until current date changes).
