### ISSUE TITLE
Parse for Geocheckers not successful for GC88878

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16081]
From support ticket 316620
Version 2024.09.09

The cache GC88878 contains a Geochecker. However, this checker is neither displayed in the cache listing nor does c:geo displays a link to it underneath the listing.

The former is probably due to the strange HTML being used: the geo checker image is displayed using the style attribute "background image" which I guess is not supported by Androids HTML parsing.

The later is strange though. Maybe we haven't included the pattern of this geo checker into c:geo yet?

Relevant HTML Source snippet:

`<br> <center> <a href="https://geocheck.eu.org/geo_inputchkcoord.php?gid=63949208bba8f11-a3d6-4ddb-8a96-897e2ed3b1c4"><div style="background-image:url(https://geocheck.eu.org/geocheck_small.php?gid=63949208bba8f11-a3d6-4ddb-8a96-897e2ed3b1c4);height:40px;width:150px;"></div> </a></center> <br>`

**Comment by ztNFny** [comment]
there's a strange "eu" in the domain: https://geocheck.EU.org/
That domain works, but I've never seen it.... It's usually just https://geocheck.org/

**Comment by MagpieFourtyTwo** [comment]
I'm surprised that an image of geocheck.eu.org made it into the listing at all ...
Cause since [16.09.20](https://forums.geocaching.com/GC/index.php?/topic/358532-release-notes-website-upload-image-to-cache-trackable-description-hosted-images-going-forward-september-15-2020) only domains listed in [approved domains](https://www.geocaching.com/help/index.php?pg=kb.chapter&id=97&pgid=956) (here: only geocheck.org) should actually be allowed.
But in fact https://geocheck.eu.org/geo_inputchkcoord.php just redirects to geocheck.org - maybe the image proxy first resolves redirects to check the URL's legitimacy ... don't know ... but if so, it should be checked if there are even more allowed redirects, to implement a solution which works with all possibilities ...?

**Comment by ztNFny** [comment]
> but if so, it should be checked if there are even more allowed redirects, to implement a solution which works with all possibilities ...?

the detection mechanism scans the listing as is, it doesn't load every resource to check where it ends up.

I'd say as that's not a permitted checker and probably the only listing out there -> close.

**Comment by MagpieFourtyTwo** [comment]
Agreed, in principle.
But, most regretfully, it's not the only one: [List of Global Geocaching](https://www.geocaching.com/plan/lists/BM6FNA6) - seems as if they all use eu.org.  :(
However - the image made it into several listings, worldwide, with several owners, thus c:geo should be able to show the checker.

**Comment by fm-sys** [comment]
Maybe using 

```
style="background-image:url(...);"
```
allows getting around that restriction? 🤔

**Comment by ztNFny** [comment]
the image is irrelevant, you can put any image, they are just proxied by GC. Relevant for c:geo here is the link:

Would produce the same:
<a href="https://geocheck.eu.org/geo_inputchkcoord.php?gid=63949208bba8f11-a3d6-4ddb-8a96-897e2ed3b1c4">checker</a>

**Comment by MagpieFourtyTwo** [comment]
Yep, that's what I thought, too, but the [release notes](https://forums.geocaching.com/GC/index.php?/topic/358532-release-notes-website-upload-image-to-cache-trackable-description-hosted-images-going-forward-september-15-2020) tell a different story: "all new cache and trackable pages can only contain images that are hosted on Geocaching.com or one of the approved domains". Intention was to block tracking. But, would not be the first time that a program has not read it's own documentation.  ;)

**Comment by ztNFny** [comment]
"all NEW cache" ... these caches are older - and those old ones are proxified. And I think the check is only in create page, not in the edit listing page.

**Comment by MagpieFourtyTwo** [comment]
Listing: 27 Dec 20 
Release Note: 16 Sept. 20

**Comment by MagpieFourtyTwo** [comment]
Nevertheless, Reading coffee grounds.
Fact is, checker is there, so c:geo should show it.  My 0,02 $
Cause the user has no chance to decide or recognize why one is shown and others are not ...

**Comment by eddiemuc** [comment]
Just so we are on same page here: we can (and should IMHO) recognize this "new" geo checker pattern and show it as available geochecker under the listing. @ztNFny provided a PR for that (thanks a lot!) and I just merged it.

But this will still not show the geochecker's image in listing or gallery. Because our HTML scan doesn't recognize the style-background-image-syntax. And it might be tricky to get into that. Don't know if it would be worth the effort honestly.

**Comment by MagpieFourtyTwo** [comment]
In the [Global Geocaching Series](https://www.geocaching.com/plan/lists/BM6FNA6) the listing of [Beijing](https://coord.info/GC81NYW) is the first (resp. oldest), thus most probably the initial source which then has just been copied - and it already uses geocheck.eu.org. It's owner is the same as GC88878. And he owns [Wrocław](https://coord.info/GC8ZMTF) as well, in which the style-background-image-syntax has been "invented".

So I simply asked him how he came up with these unusual implementations.  Perhaps we get some clarification and can then decide if it makes sense to go further than just showing the URL (which IMO is already sufficient, esp. if it's just "individual stuff" and not geocheck.org's script output at this time).
