### ISSUE TITLE
Multiple tracks in single GPX cause wrong elevation plot

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#16082]
### Describe your problem!

This is an ascent to the Zugspitze in *one* track; notice how it reaches around 2900m altitue:

![2024-09-16 07 55 25](https://github.com/user-attachments/assets/e19b9481-b9e3-4c0d-9688-42978795e5ec)

Now I cut *the same* track into *two* tracks, and put it into the same GPX file:

![2024-09-16 07 54 15](https://github.com/user-attachments/assets/7d1e8b68-79c2-4a9d-a0ee-3329b8452e1c)

Notice how the second track seems to start from the same altitude as the first, and the maximal elevation is false.

### How to reproduce?

Here are the example files:

[Smartphone.zip](https://github.com/user-attachments/files/17009017/Smartphone.zip)

### Reproducible

Yes

### c:geo Version

2024.09.09

**Comment by moving-bits** [comment]
PR #16104 should fix this issue
