### ISSUE TITLE
Unified map - buildings contour too thick (default theme)

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#16096]
### Describe your problem!

Trying out several things with the new unified map I got into some problems with rendering. One of them is as folows: 

### How to reproduce?

Settings / map source / unified map = ON
use OSM offline map. use default theme, osmarender variant. (no options available)
go to map.
show a zoom level not too far, not too close, where buildings don't get the 3D look.
There are at least 2 levels where this happens.

### Actual result after these steps?

Building contours are very thick. At the smaller zoom level, actually it's too much clutter because of the thick contours. 
Also there are much less street names shown. 
Street names actually shown have a larger font. Quite too large for some streets.
Some POI symbols not shown. (I repeat, default theme with no actual options)

![Screenshot_20240920-131621_cgeo](https://github.com/user-attachments/assets/44a48ecb-cab1-4d85-a4ae-58299163fa00)

### Expected result after these steps?

Using non-unified map.
Using OSM map, default theme. (no variant available, no options available)
Showing same zoom level. 
Building contours are much thinner and map is easier to read.

![Screenshot_20240920-132612_cgeo](https://github.com/user-attachments/assets/2e97f337-65cc-41ac-aa18-d05fc67689b7)

### Reproducible

Yes

### c:geo Version

2024.09.18

**Comment by ztNFny** [comment]
cgeo doesn't implement any theme itself, that's provided by mapsforge upstream. Please direct your question there.

(VTM will probably become the default btw)

**Comment by devemux86** [comment]
I don't know if images show Mapsforge or VTM, but it does not happen in the samples of these projects.

It could be something in the app implementation, like changed size of some map elements in app settings.
Especially seeing that the labels in the 1st image have larger size than the labels in the 2nd image.

**Comment by moving-bits** [comment]
I can reproduce the behavior with our current release 2024.09.18, so "old" Mapsforge implementation (internally called `NewMap`) as well as `UnifiedMap` VTM. All scaling options (map, text, symbols) are set to 100%, using built-in "osmarender" theme in both cases.


> I don't know if images show Mapsforge or VTM

From the screenshots I would guess: The fist image (with the small orange triangle in the upper left corner) is VTM, the second image is Mapsforge.

Using a more recent build of our `master` branch, that already includes `UnifiedMap` Mapsforge, I made side-by-side screenshots:

|UnifiedMap Mapsforge|UnifiedMap VTM|"old" Mapsforge|
|---|---|---|
|![image](https://github.com/user-attachments/assets/3cbcc008-a351-48a1-8254-b5c8ba73c112)|![image](https://github.com/user-attachments/assets/5a8f38c9-a200-4542-8df1-3bbe52a9565d)|![image](https://github.com/user-attachments/assets/67b4ca4b-725c-48f9-98bf-2b8c26c2d93a)|

Building countours are much more emphasized in VTM than in the two Mapsforge variants.

**Comment by devemux86** [comment]
We cannot expect Mapsforge and VTM to have the same rendering.
They use different map engine and themes.

Anyway, what is shown with the sample apps is Mapsforge vs VTM:

<img src="https://github.com/user-attachments/assets/53bbcce1-29e7-4af6-ac10-72877c413570" width="50%"/><img src="https://github.com/user-attachments/assets/d03f677c-0392-4025-ba2a-3040c2323924" width="50%"/>

**Comment by moving-bits** [comment]
Ok, some further testing leads me to the assumption that this is map-specific:

See those two samples taken from today's snapshot of VTM sample, one with Berlin.map taken from the Mapsforge server, and one with OpenAndroMap's version of Berlin.map, both with built-in Osmarender theme:

|Mapsforge Berlin.map|OpenAndroMaps|
|---|---|
|![Screenshot_1726995598](https://github.com/user-attachments/assets/41be6995-87a1-48df-8fa0-becb932dbe6e)|![Screenshot_1726995537](https://github.com/user-attachments/assets/91f69d7a-4c82-4dc2-b331-c49f8f949948)|

(Please ignore seemingly different screenshot sizes, that's a GitHub artifact. If you download the screenshots, they have the same size. They are taken from the same emulated device, using the same build of VTM samples application, MapsforgeActivity)

Please note, that using a map from OpenAndroMaps (if that's the case for you) should be used in conjunction with one of their themes (Elevate or Elements) for best experience, whereas the map from Mapsforge is meant to be displayed with one of their built-in themes preferrably.

**Comment by andrixnet** [comment]
What I see (and prompted me to post this issue) is a significant difference in building contour rendering when only one config item changes: `map sources -> unified map` ON/OFF. 

I have Romania map downloaded via c:geo internal mechanisms. 
I have Romania OpenAndroMaps downloaded manually and "Elevate" theme added. 

Using Romania map (via c:geo) with `unified map` OFF and default theme = shows thin contours, thus a clean map.
Using Romania map (via c:geo) with `unified map` ON and default theme = shows thick contours, a cluttered map. 

Though I have Romania OpenAndroMaps, in my tests I did not use it, neither did I use "Combined".

**Comment by SammysHP** [comment]
> What I see (and prompted me to post this issue) is a significant difference in building contour rendering when only one config item changes: `map sources -> unified map` ON/OFF.

When unified map is off, the old Mapsforge library is used. If it is turned on, it uses VTM by default (a completely different engine).

**Comment by andrixnet** [comment]
Then regarding comment by @moving-bits I used the same map to highlight differences between the render engines.
Though the comment https://github.com/cgeo/cgeo/issues/15723#issuecomment-2365264808 "VTM future being usure" ... confuses me.

**Comment by andrixnet** [comment]
> That's why we plan to switch back to Mapsforge.

Understood. Then this won't matter anymore. Thanks for the info.

**Comment by moving-bits** [comment]
> Though the comment [#15723 (comment)](https://github.com/cgeo/cgeo/issues/15723#issuecomment-2365264808) "VTM future being usure" ... confuses me.

VTM has a couple of problems, some of them visible as visual artifacts in c:geo, other with regard to new requirements for Android 15, which would be hard to implement for VTM. There is a discussion on their GitHub page giving more details.
In the end, the current maintainer of both VTM and Mapsforge decided to implement the most-wanted functions available in VTM, but missing in Mapsforge, map rotation and fractional zooming, in Mapsforge, and even decided to switch from VTM to Mapsforge in his own app (Cruiser).

That's the reason why we currently support both VTM and Mapsforge in UnifiedMap (in addition to "old" Mapsforge, non-UnifiedMap) and will probably drop VTM in favor of Mapsforge in UnifiedMap as well.

**Comment by andrixnet** [comment]
@moving-bits thank you for the insight.
