### ISSUE TITLE
Downloader for hillshading data

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16113]
Mapsforge server + fast mirror now also host 3" hillshading data for the whole world.

https://download.mapsforge.org

_Originally posted by @devemux86 in https://github.com/cgeo/cgeo/pull/15415#issuecomment-2378526758_

With the hillshading data now being available on a capable server (thanks @devemux86!!) we can implement a download mechanism. Like routing data it's split into regional tiles, so probably the routing download mechanism can be reused.

**Comment by ztNFny** [comment]
Differences to BRouter tiles:
- files are stored in subfolders (1 level) instead of flat structure -> requires listing multiple dirs to get the files
- files are zipped
- updater is probably not needed as all of those files are 8 years old - won't hurt though

**Comment by moving-bits** [comment]
Thanks for looking into this. As with BRouter tile data, the complete Uri can be precalculated automatically by c:geo, no need to show the Download Manager UI here (with directory traversal & file pickup by the user etc.), just show the confirmation dialog and enqueue the required files on confirmation.
(You may want to take a look at the map's "check for missing routing data" menu entry for how it's been implemented for routing tile data.)

**Comment by ztNFny** [comment]
> (You may want to take a look at the map's "check for missing routing data" menu entry for how it's been implemented for routing tile data.)

i did, that part is already implemented. it compares it against a list of available files later on in the process though.
Will push it as soon as i have "something" working, hopefully later today.

**Comment by ztNFny** [comment]
enough for today ... https://github.com/cgeo/cgeo/pull/16116
current state:
- all directories are parsed before downloading the files -> todo: only check those directories that are really needed
- files are downloaded but verification in checkTileDataIntegrity with this error I don't understand: java.io.IOException: file of size 1499652 too short, should be 57012045766495  @moving-bits  any idea about this one?
- some strings are still pointing to routing downloader

**Comment by moving-bits** [comment]
> @moving-bits  any idea about this one?

Thanks for the implementation. I've added a few comments with regard to BRouter-specific code neither required nor working in this context.

**Comment by ztNFny** [comment]
But there's verification code also in the other downloaders that does pretty much the same?

**Comment by moving-bits** [comment]
> But there's verification code also in the other downloaders that does pretty much the same?

which code are you referring to?

AFAICS `verifiedBeforeCopying` is used by `BRouterTileDownloader` only, `verifiedAfterCopying` not at all.

**Comment by moving-bits** [comment]
For reference: See detailed discussion about downloading hillshading data in #13604.
