### ISSUE TITLE
UI for deleting routing files

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16118]
We are missing an option to delete routing data from UI. Maybe enhance the existing update dialog with a delete button?

**Comment by moving-bits** [comment]
Thinking about managing downloaded files: We have 
- maps, 
- themes,
- routing tile data and 
- hillshading tile data
 
that can be downloaded by c:geo. How about a menu that allows to manage all of them?

- List them by category, show name + size, and allow to remove them individually (checkboxes)
- Could be put on home screen. Rename "Update offline data" to "Manage offline data" add add an entry "remove downloaded data" that opens that dialog.
- Or combined handling updates and removing into one dialog with appropriate action buttons.

(Today's "delete offline maps" in map sources menu could be removed then.)

**Comment by ztNFny** [comment]
Like it. Would put the entry in settings - offline data

**Comment by moving-bits** [comment]
Ok, I'll look into it
