### ISSUE TITLE
Test referring to images failing

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16132]
(Taken from https://ci.cgeo.org/job/cgeo-CI_PR-build/9607/ test results)

- `cgeo.geocaching.connector.gc.GCParserTest.testOwnCache`:
  [First spoiler image url wrong] expected:<"http[s://img.geocaching.com]/6ddbbe82-8762-46ad-...> but was:<"http[://imgcdn.geocaching.com/cache/large]/6ddbbe82-8762-46ad-...>

- `cgeo.geocaching.connector.gc.GCParserTest.testSpoilerWithoutTitleAndLinkToLargerImage`:
  expected:<.../img.geocaching.com/[cache/large/]124a14b5-87dd-42c6-8...> but was:<.../img.geocaching.com/[]124a14b5-87dd-42c6-8...>

- `cgeo.geocaching.connector.gc.GCParserTest.testFullScaleImageUrl`:
  expected:<"http[://imgcdn.geocaching.com/track]/33cee358-f692-4f90-...> but was:<"http[s://img.geocaching.com]/33cee358-f692-4f90-...>

- `cgeo.geocaching.connector.gc.TrackablesTest.testTrackableWithLogImages`:
  expected:<.../img.geocaching.com/[track/log/large/]3dc286d2-671e-4502-9...> but was:<.../img.geocaching.com/[]3dc286d2-671e-4502-9...>

I guess this is related to recent changes in default size for downloaded images, see #15963, but this needs to be validated in code yet.

**Comment by ztNFny** [comment]
Imgcdn is not in the new code - first time i see that subdomain. The others should just be about adjusting the tests.

**Comment by ztNFny** [comment]
> Imgcdn is not in the new code

Correction - it is indeed in there

**Comment by moving-bits** [comment]
issue resolved with #16136, therefore closing
