### ISSUE TITLE
Map refresh loop if online disabled

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#16134]
### Describe your problem!

Opening the map while online is disabled causes a refresh loop.

### How to reproduce?

1. Open online map
2. Disable updates
3. Close map
4. Open map again

### Actual result after these steps?

The orange refresh bar at the top is flashing at high frequency. It stops when you enable updates again. Then you can turn off updates and it doesn't try to refresh until you close the map again.

### Expected result after these steps?

No flickering bar at the top.

### Reproducible

Yes

### c:geo Version

2024.09.28-NB-f8dcd4d

### Additional Information

Happens with all map sources in unified map (Google, OSM online, VTM and Mapsforge).

**Comment by moving-bits** [comment]
Internal caching should prevent this, but as `lastSearchResult` only gets set for online loading, this did not work for "offline only". I'll provide a fix.
