### ISSUE TITLE
event date filter

### ISSUE THREAD

**Issue by L0rdthri11** [cgeo/cgeo#16146]
### Tell us your idea!

Using the event date filter works well for events but prevents other cache types from showing on the map.

### What solution would you suggest?

I want to able to use the event date filter while other cache types are still shown on the map.

**Comment by ztNFny** [comment]
You can use OR filters to combine it with other filters

**Comment by L0rdthri11** [comment]
Yes, that works. Thank you!

However, it's not really convenient tbh. Anyway, I consider my problem solved, but you can still discuss, if you want to adjust the mechanics of the date filter.
