### ISSUE TITLE
Circles not closed on low zoom level

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#16140]
### Describe your problem!

If you zoom out far enough, circles around caches aren't completely closed. If you zoom further in, everything looks OK.

### How to reproduce?

1. Open map
2. Enable circles
3. Zoom in/out

### Actual result after these steps?

Circles not closed on some zoom levels.

### Expected result after these steps?

Circles should always be closed.

### Reproducible

Yes

### c:geo Version

2024.09.28-NB-f8dcd4d

### Additional Information

![Screenshot_2024-09-29-14-49-01-269_cgeo geocaching](https://github.com/user-attachments/assets/34a5d7d0-ccae-4ab0-8851-b24c9ae2d9f5)

**Comment by moving-bits** [comment]
which map types are affected?

**Comment by SammysHP** [comment]
OSM online maps and offline maps in unified map. Looks like a VTM issue again. Works with Mapsforge and Google under unified map.

**Comment by eddiemuc** [comment]
@SammysHP you closed this issue. Was this on purpose?

**Comment by SammysHP** [comment]
@eddiemuc
Yes, because I thought that we're moving away from VTM anyway, so it isn't worth to fix it (similar to rendering issues with lines in VTM like building contours, dashed lines on ways etc).
