### ISSUE TITLE
[Nightly] Immediate Crash on Startup

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#16144]
### Describe your problem!

Updated to today's nightly - and can not start c:geo anymore.

### How to reproduce?

Just start ...

### Actual result after these steps?

Immediate crash.

### Expected result after these steps?

No crash.  ;)

### Reproducible

Yes

### c:geo Version

2024.09.30-NB-c04e152

**Comment by eddiemuc** [comment]
Can you provide a log file?

**Comment by MagpieFourtyTwo** [comment]
Yep, will do so as soon as possible.

Interesting thing: Crash only happens if I start c:geo from Android's home screen, i. e. with c:geo's "Home" being the page to be shown. 

If I start via a notification mail, everything runs smooth - until I try to get into c:geo's Home screen (mail -> cache listing -> caches around -> map -> home), as soon as I hit "Home", c:geo crashes.

**Comment by MagpieFourtyTwo** [comment]
Uncaught exception with string resource ID #0x7f120ba9

Two logfiles: First with start from Android's Home screen, second with start via notification email - although both end up with the same error.

[cgeo-log-support-2024-09-30-10-33-47-2 - start via Android Home screen.txt](https://github.com/user-attachments/files/17186646/cgeo-log-support-2024-09-30-10-33-47-2.-.start.via.Android.Home.screen.txt)

[cgeo-log-support-2024-09-30-10-35-46-2 - start via email.txt](https://github.com/user-attachments/files/17186653/cgeo-log-support-2024-09-30-10-35-46-2.-.start.via.email.txt)

**Comment by moving-bits** [comment]
Interestingly, both log files contain the identical error message (but rest is different), so probably in one case the crash happens in the background.

Crash happens somewhere deep in Android code:

```
android.content.res.Resources$NotFoundException: String resource ID #0x7f120ba9
	at android.content.res.Resources.getText(Resources.java:556)
	at android.content.Context.getText(Context.java:888)
	at androidx.appcompat.widget.SearchView.getQueryHint(SearchView.java:631)
	at androidx.appcompat.widget.SearchView.updateQueryHint(SearchView.java:1119)
	at androidx.appcompat.widget.SearchView.setSearchableInfo(SearchView.java:416)
	at cgeo.geocaching.MainActivity.onCreateOptionsMenu(MainActivity.java:457)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4695)
	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:2027)
	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2313)
	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:281)
	at android.os.Handler.handleCallback(Handler.java:996)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9652)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
```

Calling context is `searchView.setSearchableInfo(searchManager.getSearchableInfo(getComponentName()));` in `onCreateOptionsMenu()` in `MainActivity.java`.

But at least in the emulator I cannot reproduce the crash. And the mentioned code line seems to be unchanged for > 10 years.

:man_shrugging:

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo may I ask which display language you're using?

**Comment by MagpieFourtyTwo** [comment]
System default is English.

And c:geo is running in English as well.

Nevertheless, can't say if c:geo's internal setting is set to "English" or "System default", because I cannot enter the settings dialogue.  But as this internal setting never really worked very well, I'm pretty sure that it's set to system default.

**Comment by ztNFny** [comment]
I think the only recent change to that options menu is @moving-bits manage offline data - but i don't see any issue with it

**Comment by eddiemuc** [comment]
While investigating this, I noticed that search does not work in my emulator.... (this may well be the reason why this crash does not happen in emulator):
![image](https://github.com/user-attachments/assets/314d958c-19f5-4b4e-b31b-05ccc93ea3cc)

**Comment by MagpieFourtyTwo** [comment]
Just remembered: Had a system update on Sunday morning - but it [allegedly contained September's security patch only](https://www.honor.com/global/support/bulletin/2024/9/). Moreover c:geo worked perfectly fine all Sunday long (and I started it a *bunch* of times). Problem only exists till Nighty's update this morning.

However, don't know if it's of any importance, but I have changed the rightmost button of the bottom menu to "Recently viewed". Plus there are IIRC 4 shortcuts to ... hmmm ... don't really remember ... but there's at least one for "Backup / Restore" ... current configuration is listed over [here](https://github.com/cgeo/cgeo/issues/16092#issue-2535460398) Have not changed config since then ... at least not WRT home screen ... although I can't find the shortcuts in there ...

**Comment by eddiemuc** [comment]
I am lost currently. In my emulator the search never works, and I don't believe how it ever could work.

Here is a bit of MainActivity:
![image](https://github.com/user-attachments/assets/3e700b3f-58ab-49d3-8808-644cc857d61f)

In line 457, the term `searchManager.getSearchableInfo(getComponentName())` always returns `null`. Which IMHO is correct because `getComponentName()` points to `MainActivity` which has no search associated ( `new ComponentName(this, SearchActivity.class)` works)

But if the above returns null, then the Stacktrace of @MagpieFourtyTwo can never happen...

**Comment by MagpieFourtyTwo** [comment]
> the Stacktrace of @MagpieFourtyTwo can never happen

I swear, I have not written it by hand.  ;)

**Comment by MagpieFourtyTwo** [comment]
Just installed the new Nighlty (2024.10.01-NB-22df3a7, via status page) ... and the error is gone - c:geo opens normally again!

On one hand good, of course, but OTOH bad, cause the real cause will most probably remain hidden from us forever ... 
Perhaps a compiler error ... don't know.  Installation glitch can IMO be excluded, as I did it thrice, and downloaded it twice ...
However, all that can come now is most probably just reading coffee grounds, so I'll close here.
Thx to all who have investigated!

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo is the cache search in the action bar of main screen working?

**Comment by MagpieFourtyTwo** [comment]
> is the cache search in the action bar of main screen working?

Yep, works like a charm. For GC codes and GC names as well.
Even checked TB codes and tracking numbers (I do not discover anymore) - but both are working, too.
