### ISSUE TITLE
UM: Compass Rose - change South color and hide it if Map Rotation is off

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#16151]
### Tell us your idea!

In fact I have even three things:  ;)
1. the compass rose is hard to read for people with color vision deficiency (i. e. to distinguish red North from green South),
    thus I would propose to make it more contrasting, e. g. fill the South end white or silver, with e. g. a green outline.
2. the compass rose does not really make sense if map rotation is disabled anyway,
    thus I would propose to hide it when rotation is off (which can even be understood as indicator of rotation on/off)
3. to make things easier WRT compass rose visible or not, I would swap positions of compass rose and follow me

I BTW would have put the two icons to the top left of the map, cause it would then not go up and down just because of changing number of distance fields shown ... but I missed this thread where this was discussed.  :/

**Comment by Lineflyer** [comment]
Do you really mean the c:geo compass  or are you refering to the compass icon on map or something else.

**Comment by MagpieFourtyTwo** [comment]
Sorry for being imprecise, I mean the small compass icon in the top right edge of the map, just above the moved follow me switch.

**Comment by eddiemuc** [comment]
> 1. the compass rose is hard to read for people with color vision deficiency (i. e. to distinguish red North from green South),

Agreed. I propose to do same as Google Maps. Basically the have a much lighter silvery south arrow, mich like @MagpieFourtyTwo suggested

> 2. the compass rose does not really make sense if map rotation is disabled anyway,
>     thus I would propose to hide it when rotation is off

Agree. I just tried it, and it seems this is already the case (I tried VTM on offline map). Also when clicking on the compass rose the map goes back to "north orientation" and vanishes (also the right behavior IMHO. And almost similar to gmap :-)).

> 3. to make things easier WRT compass rose visible or not, I would swap positions of compass rose and follow me

"Follow me" is in action bar. Really put compass rose in action bar?

> I BTW would have put the two icons to the top left of the map...

On VTM Compass rose is already on top left. I am confused....

**Comment by bekuno** [comment]
See here: https://github.com/cgeo/cgeo/pull/16137.

**Comment by MagpieFourtyTwo** [comment]
@eddiemuc Sorry for the confusion, I'm of course talking about the latest nightlies and there it's like bekuno already referenced.

**Comment by MagpieFourtyTwo** [comment]
Although I didn't really see the advantage of moving the follow me button from header to map, cause in at least my header this move changed nothing at all other than now having two additional icons reducing the map info.  But this is a different topic.

**Comment by ztNFny** [comment]
I have on my to-do list already to look at those 2 new icons. Something about the compass feels off to me, I'll experiment with some alternative versions.
But this week though...

**Comment by moving-bits** [comment]
> 1. the compass rose is hard to read for people with color vision deficiency

It's actually the same compass rose as before in UnifiedMap VTM/Mapsforge, just without the round border. But @ztNFny will be looking into it anyway (thanks!).

> 2. the compass rose does not really make sense if map rotation is disabled anyway,
> thus I would propose to hide it when rotation is off (which can even be understood as indicator of rotation on/off)

I'll work on this. Compass rose should be hidden if rotation mode is set to off, but be available otherwise (as it's now a quick toggle for rotation modes as well).

> 3. to make things easier WRT compass rose visible or not, I would swap positions of compass rose and follow me

I have no strong opinion about this. Others?
Technically the swap would be easy to implement.

> I BTW would have put the two icons to the top left of the map, cause it would then not go up and down just because of changing number of distance fields shown ...

It would still go up and down, as setting a target or supersizing distance info requires more vertical space. But going up and down was considered better than having the two icons in a fixed place further down, see linked discussion.

> Although I didn't really see the advantage of moving the follow me button from header to map, cause in at least my header this move changed nothing at all other than now having two additional icons reducing the map info.

We had regular reports on support that with the new list chooser there's not enough place to see the "live mode" icon anymore, which is frequently used. Today's very tall screens give us the opportunity to move some UI elements to the map space.

**Comment by ztNFny** [comment]
Re order: I felel like "current position" will be tapped more often than compass, so should be in a more accessible place > bottom

**Comment by MagpieFourtyTwo** [comment]
Sorry to have to say so, but using the new "Stay With Me" button is no real pleasure.  :/

Problem 1:  It's never where I expect it to be, there's just a very little chance to hit it “on the fly”, automatically, without looking, you always have to concentrate at the display to get it.

Problem 2: In the top right corner it's nearly impossible to reach if you hold your mobile with just one hand.

Problem 3: Even if you get to it, success is not guaranteed, cause you must hit the perfect center, otherwise (when just scratching an edge), although the button flickers, "Stay With Me" will not be activated, Therefore I sometimes have to aim three times to get it right. Even worse when I try it one-handed.

As for me, the button should go to a fixed location, where it can be "found" without thinking. Even more as this is probably the most used button of the map interface. E. g. somewhere near the zoom buttons. Over there it can even be used with just one hand.  BTW: The compass rose I would place at the top left, as over there it's not that much moving like in the top right, where it's position depends on display of active route, individual route, straight distance, big numbers ...

And WRT to hitting it: Would be great if the "active" area would be increased to at least the outer borders of the button, like it is with the zoom controls.

**Comment by moving-bits** [comment]
Thanks for your feedback!

> As for me, the button should go to a fixed location, where it can be "found" without thinking. Even more as this is probably the most used button of the map interface. E. g. somewhere near the zoom buttons. Over there it can even be used with just one hand. BTW: The compass rose I would place at the top left, as over there it's not that much moving like in the top right, where it's position depends on display of active route, individual route, straight distance, big numbers ...

Current position of those buttons was the result of the related discussion ("place it in top right corner, and 'jumping with the distance views' was considered acceptable, as GM does it as well) - but that does not mean that we could not change it after getting some real world feedback. I'll put it on the agenda for the next dev meeting.

> And WRT to hitting it: Would be great if the "active" area would be increased to at least the outer borders of the button, like it is with the zoom controls.

This I would regard as a bug. I'll try to look into it over the next days.

**Comment by ztNFny** [comment]
After a week of using the new location button i have to agree with the above points.
There are some easy to fix things like the hit area of the button being way too small.
But the dynamic position of the button is an absolute deal-breaker. Due to the routing info it's always in a different place and it requires a lot of attention to actually hit it.

Options:
- place routing info of the left of the button (so not whole width anymore)
- draw location button over routing info
- move it to one of the bottom corners
- return ro toolbar

**Comment by MagpieFourtyTwo** [comment]
I guess, the decision to place the "Stay with me" button where it currently is, was mainly based on optical/design reasons - which not always is best WRT usability, ;) However, this becomes apparent in the day-to-day work. And since usability is always a high priority here, I'm optimistic that this will be well received. :)

> - place routing info of the left of the button (so not whole width anymore)

With up to three vertical numbers the free space right of the routing info and below the button would look a bit strange, I guess.

> - draw location button over routing info

There are two ways to understand "over": In z-axis or in y-axis.  I guess you meant the latter, but even then this results in the same "optical break" as in the previous point, only just not vertically but horizontally.

> move it to one of the bottom corners

Yep - as these are the most constant locations. I could imagine to put it either above the zoom controls (y-axis ;) ) or left of the minus. Over there it can even be easily reached with the thumb, e. g. when operating the mobile with one hand or while riding a bicycle without letting go of the handlebars.

> return to toolbar

IMHO this would be the best solution. Esp. as the only scenario, where IMHO space may really be an issue, is when you entered the map via navigation to a cache - and then, first of all this weirdly wide ``Back`` button should become way narrower. If not even disappear completely, as IMHO it's more than superfluous anyway:

![Header buttons](https://github.com/user-attachments/assets/5d9b790c-f959-455d-858e-69ed1e4c97ce)

Don't know for what it's needed for at all - it anyway disappear as soon as you activate Live mode ... which is pretty funny as in Live mode there's even more room in the header.  ;)

So, does anybody really use resp. need it? I guess most of the users use the "standard" back function anyway ...

If decision is to remove it, please do the same in the cache listing page, over there it's superfluous, too, IMHO.

And if this is still not enough, perhaps even the icons on the right may become a bit narrower ...? These are anyway way bigger than e. g. the zoom controls, and these already seem to be big enough, otherwise there would have been complaints, I guess.

**Comment by MagpieFourtyTwo** [comment]
> I meant the z-axis 😉

Really? Hmm. Apart from covering information I would not overlay two touch action areas. Cause if you "mis-hit" the "Stay with me" button, the big numbers will appear, which may lead to confusion ... esp. as aou ma need three more touches to get rid of the big numbers again.

> back arrow, this is a standard design element 

Thought so, but then, why isn't it present in Live mode?  And why were there no complaints about it's absence?  There are even more places without ``Back`` button (e. g. lists, ``Recently viewed``, ``Search`` (via bottom menu) ...), and apart from that I know a bunch of apps where's no back button at all ... but the only place where room is a real issue, there it must be ...?  Hmm ...  :)

But, anyway, at least it could be way narrower ... then there would be enough room for the "Stay with me" again.

**Comment by moving-bits** [comment]
> first of all this weirdly wide `Back` button should become way narrower.
> 
> ![Header buttons](https://private-user-images.githubusercontent.com/9889015/375685653-5d9b790c-f959-455d-858e-69ed1e4c97ce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjAzMDEsIm5iZiI6MTcyODcyMDAwMSwicGF0aCI6Ii85ODg5MDE1LzM3NTY4NTY1My01ZDliNzkwYy1mOTU5LTQ1NWQtODU4ZS02OWVkMWU0Yzk3Y2UuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMDgwMDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZiMjVmM2ZlNDgyNzU1YmEyODlhYTVjZGY0NzEyNjYwNGZkMjVmNWJlMzAzMDMyYjU2ODRkZTg0ODg5OGI4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BPu4CUGtrKKjmefdZeIWiGpGka-IbJh8QNU7cCftPSo)

This is due to some Material Components' default settings. But finally found a way to reduce the white space after back button significantly, see #16204

**Comment by moving-bits** [comment]
> And WRT to hitting it: Would be great if the "active" area would be increased to at least the outer borders of the button, like it is with the zoom controls.

Fixed with #16205

**Comment by moving-bits** [comment]
> I guess, the decision to place the "Stay with me" button where it currently is, was mainly based on optical/design reasons

The decision was made due to increased traffic on support from people that can no longer see the "enable live button", which has moved to overflow menu for them, as the new cache list chooser needs more space than the old solution.

**Comment by MagpieFourtyTwo** [comment]
Yep, that's clear. I meant the decision to put both to the top right.

However, although I would still prefer to just drop the superfluous back button, perhaps plus decreasing the width of the other buttons, which will give even more space than the follow me button would need, the new solution with follow me near the zoom controls is a pretty good solution, too.

**Comment by MagpieFourtyTwo** [comment]
BTW: The compass rose is still red/green, thus still hard to distinguish. Lost track of a possible change - is there s/th going on?

**Comment by ztNFny** [comment]
> 1. the compass rose is hard to read for people with color vision deficiency (i. e. to distinguish red North from green South),
>    thus I would propose to make it more contrasting, e. g. fill the South end white or silver, with e. g. a green outline.

Could you clarify which compass rose you're refering to? There's no green in the one used on map.

**Comment by MagpieFourtyTwo** [comment]
This one ..,

![Compass Rose](https://github.com/user-attachments/assets/09d6bc68-cddb-4473-82bb-2c80f070d540)

... and,yes, you're right, it's not green ... not anymore.  ;)
It once was, but with one of the latest nightlies the southern end suddenly changed to signal grey.
I guess @moving-bits has changed it on the fly while fiddling around with the icon positions ...

Already wanted to comment the change, thx for the reminder! ;)

My opinion: Grey is of course already way better, but still not perfect.
Perhaps it's possible to make the southern end white with a black or whatever border ...?
Then it would even be distinguishable with a sideways glance, e. g. while driving ...

**Comment by fm-sys** [comment]
> My opinion: Grey is of course already way better, but still not perfect.
Perhaps it's possible to make the southern end white with a black or whatever border ...?

We may chose a slightly lighter gray, but I'm fine with the current color as well.

**Comment by MagpieFourtyTwo** [comment]
Guess this would already be fine.  Just let's give it a try.
