### ISSUE TITLE
Wherigo: clicking notification does not open Wherigo activity sometimes 

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16165]
One issue we had ... was coming back to the WIG once you've returned to c:geo's home screen or even left c:geo by pressing ``Back`` too often. 🙄😜
In this case, although the mentioned notification was still there (and the player obviously still running), it's not possible to get back to the WIG by clicking the notification. Sometimes after the notification click just nothing happened, sometimes c:geo's home screen was shown, but we did not manage to get back into the WIG to correctly terminate the player. Most regretfully I can now reproduce just one scenario: Play the WIG, then press ``Back`` till you're in c:geo's home, then click the notification ... and you will just be put back to c:geo's home page. To get back to the player, you have to press ``Back`` once more, to get to Android's home screen, and then the notification tap will take you back to the WIG (which for sure did not work in the field neither, but now is does ...)

Only way then was, to open the WIG listing and press the "new" WIG icon. After pressing ``New game`` the message appears that there is a WIG currently running, asking if you want to end it - then press ``Cancel`` and you're back. Guess this should be a bit more intuitive ... 😎

...

Ah, just got the second scenario reproduced, when it was not possible to come back to the WIG once you're in Android's home screen: This happens, if you leave the WIG by pressing ``Back`` till you are in c:geo's home screen, and then you press Android's Home button - if you now press the notification, you will just get back to c:geo's home. ;)

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/10087#issuecomment-2394716814_

**Comment by MagpieFourtyTwo** [comment]
Just tried to reproduce this for another scenario, but first did not get it to "work" (i. e. fail ;) ) again. But after IIRC three times going through home/home, it "worked" again, thus you may have to be a bit stubborn while testing. ;)

The scenario that worked pretty reproducible:

1. from player go ``Back`` to c:geo's home
2. press Android's Home
3. click notification 
4. if notification took you back to player (like it should), 
    go to 1. and repeat the steps - after the second or third iteration c:geo will just show you it's home screen

Intermediate workaround: It is very helpful to have the player quick launch icon configured, cause even in this scenario it will immediately bring you back to the player. ;)

**Comment by eddiemuc** [comment]
I have trouble reproducing this. @MagpieFourtyTwo are you able to provide a log for this scenario?

**Comment by MagpieFourtyTwo** [comment]
Maybe I missed a step in the above description. Don't know if I was really "necessary", but this time I could also not reproduce it until I went ``Back`` not only to c:geo's home, but at least once to Android's home. After that I again had the effect that the notification just led me to the described effect. Please find the log enclosed ...  ;)

To make it easier to retrace, here the steps I took (from memory):
1. opened the WIG's lsiting and started it via the new WIG icon
2. opened a location and centered on it 
3. went ``Back`` to c:geo's home screen, then touched Android's home button
4. touched notification and ... was back in the WIG (like it should be)
5. then 3. and 4. again, for I would say two or three times, where each brought me back to the WIG (like it should be)
6. then used ``Back```until I was in Android's home screen ...
7. from now on touching the notification just brought me to c:geo's home screen
8. then used the new WIG icon which brought me right back into the WIG
9. now ``Back`` again till Android's home screen, click on notification ... brought me to c:geo's home
10. then I opened the listing again, clicked the WIG icon and answered the question if the running game should be cancelled wit ``Cancel``
11. after that I "normally" ended the game via the ``X``

[cgeo-log-support-2024-10-05-23-35-24-2.txt](https://github.com/user-attachments/files/17267533/cgeo-log-support-2024-10-05-23-35-24-2.txt)

**Comment by eddiemuc** [comment]
I couldn't reproduce the problem, but something else caught my eye:
when Wherigo Service is running, even when I ended c:geo on the device (via Android task management), the service kept running and tapping on it still got me back to the WIG screen....

I guess I need to make sure to end the service properly when c:geo is ended.

@MagpieFourtyTwo I am at the point of guesswork here, but maybe on your device ending the process and clicking the item somehow starts on home screen again...

**Comment by eddiemuc** [comment]
I believe (hope) this is fixed with PR #16210
