### ISSUE TITLE
Wherigo: symbols and ixons

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16166]
I could use some help deciding/creating good icons and symbols for Wherigoplayer.

Here is how the player looks like today while playing a game:

![text](https://github.com/user-attachments/assets/1062e34e-2a19-41e4-a8a6-585cf8346b11)

I would need both good icons for the action buttons at the top and icons representing the different kinds of wherigo-thinga in the table below.

Action items mean (from left to right):
- "get details about locally stored cartridges and optionally start a game with them"
- "save game progress for currently.running game"
- "end currently running game"
- ",manually download a cartridge (cguid needed)"
- show all visible zones of currently running game on map

Wherigo thing types mean (from top to bottom):
- zones/locations
- things in your inventory 
- tasks to perform
- things you can see
- all things visible to you

@ztNFny already suggested some icons in another thread for the types which I liked

**Comment by eddiemuc** [comment]
NB: the screenshot above is in debug mode. To a real player, only the blue items would be visible

**Comment by ztNFny** [comment]
I'll also take a look at that top bar. It's not very clear to me without the tooltips, so definitely needs some better icons and grouping.

**Comment by rouroni1** [comment]
My two cents about the top bar:

Start: a Simple play button 
Save: The Floppy disk is pretty standard
Stop: The Square like the Stop version
Download: The folder, but with a arrow from the top
Map: Perfect as it is

About the Thing:
I wonder if it's really necessary. It duplicates everything what you can already see on the other options.
