### ISSUE TITLE
Restored coordinates not updated in c:geo

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#16175]
### Describe your problem!

When corrected coordinates are restored to the original location on geocaching.com, c:geo does not detect that change. Even after refreshing the cache manually, it shows the corrected coordinates and the "original coordinates" waypoint.

### How to reproduce?

1. Change cache coordinates on geocaching.com
2. Open cache in c:geo, notice that it shows a "original coordinates" waypoint
3. Go back to geocaching.com and restore the original coordinates
4. Back to c:geo, refresh the cache

### Actual result after these steps?

Cache coordinates in c:geo are still corrected and the cache has the "original coordinates" waypoint.

### Expected result after these steps?

c:geo shows the cache at the original location and the "original coordinates" waypoint gets removed.

### Reproducible

Yes

### c:geo Version

2024.10.06-NB-fff53c4

### Additional Information

Slightly related to #15735.

**Comment by murggel** [comment]
Can reproduce it with a not saved cache.
But even if the cache was saved before, the restored coordinates will only be shown after a second refresh.

Will look into it.

**Comment by moving-bits** [comment]
I see a possible collision here: I frequently change coordinates locally in c:geo, not always uploading them to the server. So we have a similar situation as above: Changed coords locally, original coords on the server. I would not want c:geo to remove my changed coordinates locally on updating the cache listing. - But how can c:geo distinguish between the two cases?

**Comment by murggel** [comment]
I was wondering the same, but at least for not stored caches we can fetch the last state and not merge with the CacheCache, what currently leeds to the "problem"
