### ISSUE TITLE
Transparency of map buttons

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16212]
One additional note: I noticed that the zoom controls have a different transparency compared to the buttons at the bottom.

_Originally posted by @SammysHP in https://github.com/cgeo/cgeo/issues/16207#issuecomment-2408566691_

**Comment by ztNFny** [comment]
The resource files are using the same color definitions though, but in different ways.

Quick settings is ImageButton with @style/map_quicksettingsbutton which uses @drawable/white_bcg which uses @color/osm_zoomcontrolbackground
Follow locationis ImageButton with @style/map_quicksettingsbutton which uses @drawable/white_bcg which uses @color/osm_zoomcontrolbackground
Zoom button is a path with fillColor @color/osm_zoomcontrolbackground

Seeing as Quick settings and location are defined in the same way, how are they different??!

**Comment by SammysHP** [comment]
Maybe differences in a parent container?

Btw, a few more nitpicks:

- Location button uses slightly different foreground color than the zoom controls
- location button misses the rounded corners at the top

![Screenshot_2024-10-15-06-17-07-452_cgeo geocaching](https://github.com/user-attachments/assets/c93da3cf-b3be-47d6-9a7a-59ffcb7fda7e)

**Comment by ztNFny** [comment]
> * location button misses the rounded corners at the top

This is because after the latest change there's now 2 ImageButtons on top of each other - I guess a workaround to increase the hit area - I think we should look for a better solution
