### ISSUE TITLE
Wherigo Player: add an optional Geocache context

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16219]
The current Wherigo Player in c:geo is "Cartrdige-centric". It allows one to download cartrdiges, play a cartridge, saving a game's state and loading a previously stored state.

When used from within c:geo, Cartridges are most often associated with a Geocache. 

1. In most cases this is a 1:1 relation (A Wherigo Geocache is linked to exactly one Wherigo Cartridge)
2. There are also Cartridges linked to many geocaches eg the famous [Reverse Wherigo Cartridge](https://www.wherigo.com/cartridge/details.aspx?CGUID=dcdcd2ff-c171-4487-93bc-678f6d03ac4f) and cartridges linked to NO geocache. 
3. The other way around, there are definitely many Geocaches w/o a cartrdiges and probably some with multiple cartridges associated too (don't know an example for the later one though)

Question is whether it is useful to establish a "link" between geocaches and cartridges in c:geo in any way. Possible use cases:

- a user may want to "see" what geocache he is after while playing the Wherigo (for case 1 above)
- a user may want to store/load geocache-specific savefiles for a cartridge (for case 2 above)

Second question would be how this can be achieved. Ideas:
- c:geo could store in a local database all associations between cartridges (identified by cguid) and geocaches (identified by geocode) that it is aware of
- whenever a geocache listing is opened and parsed, such a connection could be made and stored
- when a cartridge is opened via a cache detail page, then the cartridge by default is "played" in the context of this cache
- on starting to play a cartridge (either new game or load game), a "cache context" could be prefilled as best as possible, but changed by the user
- save files could be context-specific (eg filename contains geocache code)

Thoughts?

**Comment by ztNFny** [comment]
I think it'd be nice to have inside a cache a WIG tab (just like variables, waypoints), would make it easier to switch between multiple caches.
For the reverse connection (from WIG to cache) I don't see so many usecases, but I'm sure there might be some ;-)

**Comment by eddiemuc** [comment]
> I think it'd be nice to have inside a cache a WIG tab (just like variables, waypoints), would make it easier to switch between multiple caches.

A whole tab is more than I thought of, but I like the idea. What should this tab show? The cartridge detail page with option to start a game? If cartridge not locally available a download option?

**Comment by ztNFny** [comment]
I was thinkinh to have the actual wig activity in there. Start button in details activity, then a new tab shows up with the wig on play.

(Haven't fully thought this through, just s spontaneous Idea)

**Comment by eddiemuc** [comment]
> I was thinkinh to have the actual wig activity in there. Start button in details activity, then a new tab shows up with the wig on play.
> 
> (Haven't fully thought this through, just s spontaneous Idea)

Understood.

My feeling is that while playing a game users want/need one-tap-access somewhere to see this information. A cache details tab might be "too far away" for them (too man clicks and swipes).

(As said in the past, I personally use a custom menu item for this one-tap-access)

**Comment by ztNFny** [comment]
The custom menu item is only available on a few screens though, like it's not on offline maps.

**Comment by eddiemuc** [comment]
> The custom menu item is only available on a few screens though, like it's not on offline maps. So it's also not a 1 tap way to access the wig again.

That would make the feature unusable for me, but at least in my installation navigation bar (including custom menu item) is also visible for offline maps. Has this changed in master?

![Screenshot_2024-10-16-07-51-04-28_a916ceb0c8a82619faeb76fe6b8ae997.jpg](https://github.com/user-attachments/assets/f2d9b0a5-19ce-4c53-9344-3a795c8ee595)




> However there are actually very few WIGs these days, so question is how relevant a quick access way is at all.

I think it can be argued that someone right in the middle of playing cartridge might be interested in accessing the player during playing time :-)

**Comment by ztNFny** [comment]
sorry, I was mistaken.
It is visible with offline lists - however it's not visibile when mapping PQs (which I've been doing a lot lately and which is quite similar in result to offline list mapping). But I guess it should then be changed for the later case to show the bottom bar.

**Comment by eddiemuc** [comment]
I have some ideas on how to add an "geocaching context" to a wherigo game, but I am unsure whether this makes handling too complex for "normal" users.

Idea is:
* whenever the wherigo player is opened from a cache detail page, then the wherigo player is now in the "context" of this cache. This can be shown somewhere on the screen
* If a new game is started, this game is then assicoated with this cache as it's "context".
* when the forementioned game is saved, the cache context is saved with it
* when later the user wants to load an existing game, the cache context it was stored with is shown in the save file list. WHen a save game associated with a cache was loaded, then the game again is "in the context" of this cache

Because users may want to "escape" this pattern some additional stuff might be necessary:
* whenever the player is in a "cache context" and the user wants to start a new game, we should offer TWO "new game" slots: one where the game is started with the cache in context and one without a context
* question arise whether a game in a cache context may overwrite save slots with other caches contexts
* question arise whether user needs a button to actively remove the existing context from the player

Does this make sense or shall we just leave this out for now?

**Comment by eddiemuc** [comment]
Mockup on how a "load game" dialog with contexts could look like:
![Image](https://github.com/user-attachments/assets/e2348def-c2ee-489b-beae-031dcd3b9024)

**Comment by ztNFny** [comment]
I would add the cache context to have an easy possibility to switch between cache and Wig. However the above suggestion taking into account WIGs that are reused seems to be overkill.
The most reused WIG is the reverse one and for that the cache connection makes little sense (and who plays those anyway). It seems to me the effort for this multi-link would be too high for the benefit.

**Comment by eddiemuc** [comment]
What about following idea:
- allow users (optionally) to give their save files an individual name (users may or may not use this to eg remember an associated cache)
- allow to set one cache as "wherigo context" and show a link to this cache on wherigo player. This Cache is auto-set when player is opened from cache details. It can be manually set via long-click-context-menu on map and maybe cache list.

**Comment by moving-bits** [comment]
Do we have the cartridge name? "GCAEHTP Wo ist Balthasar?" in the example above? Or does a cartridge have a "title"/"name"? Then we could simply use this name + a consecutive number to name the save files + sort the save file list in "newest first" order.

**Comment by eddiemuc** [comment]
Some facts about Wherigos and cartridges:
- A cartridge file has a name and a (secret) code. Both are not mandatorily unique and the later is secret. So both can't be used as unique identifier.
- A cartridge uploaded to wherigo.com gets a unique cguid by this server. In lack of any other possibilities we use this as unique identifier. We store it in the local cartridge filename. In theory it would be possible that two identical cartridge files are uploaded to wherigo.com as different Wherigos. They would then get two different cguids. But we neglect this edge case (worst that could happen is that the same cartdi5is available twice locally).
- There is NO technical connection between a cartridge and a Geocache other than wherigo caches usually have a wherigo.com download link for a cartridge in their cache listing ! However, since very often cache owners create a cartridge specifically for one of their caches, they often give the cartridge the same name as the cache where it is used.

With this in mind:

> Do we have the cartridge name "GCAEHTP Wo ist Balthasar?" in the example above? Or does a cartridge have a "title"/"name"? 

A cartridge has a name, but the mock screenshot supposedly shows cache names (the "context cache") for users convenience. However, I am now with @ztNFny that this idea was far too complex.

> Then we could simply use this name + a consecutive number to name the save files + sort the save file list in "newest first" order.

This is exactly how it is done today (have to doublecheck the ordering). But this does not give any cache context info to user which is what this issue is about
