### ISSUE TITLE
Wherigo Player: Missing Icons in dark theme

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#16227]
### Describe your problem!

In the dark theme, the new icons for Locations, Inventory, Tasks, You see, are missing.

### How to reproduce?

Open cartridge and goto the main menu

### Actual result after these steps?

The icons are missing only in the dark theme for: Tasks, Inventory, Locations and You see.

![1729150463677](https://github.com/user-attachments/assets/329d3a7c-3ec0-4740-aa51-13149b227e49)
![1729150463682](https://github.com/user-attachments/assets/992a86a5-cb0c-4616-af4f-1e980005e238)

### Expected result after these steps?

To be like light theme

### Reproducible

Yes

### c:geo Version

2023.10.17-NB-e48cd66

**Comment by ztNFny** [comment]
Icons are there, just black on black 😉
