### ISSUE TITLE
WIG item list popup display issues

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16223]
Opening the item list in a WIG there are 2 issues:
- Status bar is hidden
- the dialog has a black bar at the bottom

![image](https://github.com/user-attachments/assets/52f3304b-011c-42db-847d-07df617e601b)

**Comment by eddiemuc** [comment]
> Opening the item list in a WIG there are 2 issues:
> - Status bar is hidden
> - the dialog has a black bar at the bottom

I can see that the black bar is an issue (never tried the light mode...).

But what is meant with "status bar"?

**Comment by ztNFny** [comment]
Android status bar, with clock and stuff
