### ISSUE TITLE
Wherigo Player: The possibility to select what to delete

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#16220]
### Tell us your idea!

At the moment, in Wherigo Player, when you select the delete button, there is only the option to delete the cartridge (the cartridge name does not appear) along with the existing savegames.

It would be good to have the option to choose what to delete: everything, only the savegames, or a specific savegame.

### What solution would you suggest?

If feasible, an example would be to use checkboxes to select what should be deleted.

If I recall correctly the autosave always replace the previous autosave with the new one, so it would be 1 check box to the autosave if present + 4 checkboxes for the saves if they exist, 1 for the cartridge, and 1 for all.

![Screenshot_2024-10-15-22-12-31-915_cgeo geocaching](https://github.com/user-attachments/assets/ce25fea2-cb40-4e8b-9df1-863f96eec455)

### Is there an alternative?

Keep as it is

**Comment by eddiemuc** [comment]
Makes sense

**Comment by ztNFny** [comment]
Is there really a usecase for partial deletion? Save games are only a few byte large, so hardly any point in deleting them. Even cartridges are usually in kb or small mb.
I think the common scenario is that after finishing the WIG you want to delete everything.

**Comment by rouroni1** [comment]
> Is there really a usecase for partial deletion? Save games are only a few byte large, so hardly any point in deleting them. Even cartridges are usually in kb or small mb. I think the common scenario is that after finishing the WIG you want to delete everything.

I can only speak from my experience  and I have two diferent use cases, as a wherigo cartridges maker, and wherigo cartridges player.

As a wherigo player:
Usualy I don't delete the savegames, unless there is a new version of the cartridge, and when I download it, I have to start again, so I have to delete the savegames.
The other time need I delete the savegames is when I lend my smartphone to my better half, to let her play the wherigo.

And, when I'm really done with a wherigo, I guess you are right at this point, I ust delete everyting, cartridge and savegames.

As a wherigo maker:
Even before publishing the cartridge I test it with emulator, but after I test it fakegps and in the real world several times. I often need to save before going in to another zone or do a task, and then when something dosent go as expected, I have to load a savegame to prevent from start again. (Maybe and just maybe it's the old  RTS player inside me that dosen't want to play the same level from de start :) )

**Comment by ztNFny** [comment]
I understand from your message the need to be able to load savegames (or not load one to start from scratch) - but I'm missing you why you need to selective want to delete them?

**Comment by rouroni1** [comment]
It dosen't but, if I want to start without any savegames, or a specific savegame, on my device, in Wherigo Player I have to delete everything, download the cartridge again.

Or go to the file explorer to the wherigo folder and delete them manually.

**Comment by ztNFny** [comment]
> It dosen't but, if I want to start without any savegames, or a specific savegame, on my device, in Wherigo Player I have to delete everything, download the cartridge again.

You don't need to delete anything to start from scratch. Both in WherYouGo and c:geo when loading a WIG you can choose to load a save game or start from scratch:
![image](https://github.com/user-attachments/assets/ebd98a9c-530f-4353-be39-c84a222e04e4)

**Comment by rouroni1** [comment]
I know. 
The question is not start from scratch, but having the option to start a cartridge without having any or to many savegames.

Taking the example of whereyougo, if you longpress a savegame you can delete it.

**Comment by ztNFny** [comment]
Sorry, but I still fail to understand the usecase and the value that'd be added by implementing this. Why would you like to have a clean state when nothing forces you to load a savegame? Whether none are available or they are and you don't load them gives exactly the same result.

In terms of disk usage those savegames are irrelevant as they're tiny.

You have to understand that every feature in c:geo will result in additional lines in the codebase, in this case probably somewhere around 50 + the layout changes and that's something that needs to be maintained.
And then it'd mean for every user to be faced with a dialog asking them what they want to delete, so they first have to understand and think about that - when the 99,99% usecase for deleting WIGs is to delete everything.

**Comment by fm-sys** [comment]
I agree with @ztNFny that we shouldn't add UI complexity for this feature. A delete via long click wouldn't hurt though.

**Comment by eddiemuc** [comment]
> I agree with [@ztNFny](https://github.com/ztNFny) that we shouldn't add UI complexity for this feature. A delete feature via long click wouldn't hurt though.

There are two places where the user is displayed a list of currently stored savegames: when she starts/loads a game and when she saves a game. It would be very easy to add a "delete" option for single savegames to both of them (trash symbol at end of line, like for named filters). WOuld that be ok?

**Comment by rouroni1** [comment]
For me it would be Ok.

**Comment by eddiemuc** [comment]
Fixed with PR #16253
