### ISSUE TITLE
GC website change: Event time not in listing

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16229]
GC events no longer include the event date and time at the top of the listing. The info is still available below the cache name.

This means that nowhere in c:geo the start and end times of an event are visible.
This also breaks event date recognition for adding events to the calendar.

**Comment by ztNFny** [comment]
https://forums.geocaching.com/GC/index.php?/topic/410241-release-notes-website-and-geocaching%C2%AE-app-event-start-and-end-times-october-17-2024/

**Comment by ztNFny** [comment]
The event start/end times are now only contained in the head of the page - which is not stored as of now. So we'd need to add new DB fields to store this info on loading a cache.

**Comment by Lineflyer** [comment]
There have been reports on support mail as well...so: Confirmed.

**Comment by MagpieFourtyTwo** [comment]
Polite question: When will this be merged to master?

**Comment by moving-bits** [comment]
> Polite question: When will this be merged to master?

I've merged the change to `master`, CI is currently building a new "nightly" - might take half an hour or so.

**Comment by MagpieFourtyTwo** [comment]
Great - thanks! 

BTW: My cachemate has just updated to today's nightly, too - but although this change works absolutely fine on my phone (Honor Magic6 Pro, Android 14), she can not load events anymore now (Huawei P30 Pro, Android 12): Already stored events can not be refreshed anymore (hangs forever), opening new events immediately crashes c:geo ... we'll keep an eye on it and may provide a logcat this evening.

**Comment by ztNFny** [comment]
Which language is the GC website set to for the crashing account?

**Comment by MagpieFourtyTwo** [comment]
For manual access it's set (resp. reset on a regular basis) to German. But AFAIR, first thing c:geo does, is to set the website to English ...?

**Comment by ztNFny** [comment]
> For manual access it's set (resp. reset on a regular basis) to German. But AFAIR, first thing c:geo does, is to set the website to English ...?

Cgeo doesn't change the language for like 2-3 years. German I definitely tested.
Will need the crash log.

**Comment by fm-sys** [comment]
> we'll keep an eye on it and may provide a logcat this evening.

That would be great. Please don't forget to provide the System information as well, which e.g. contains the GC website language ;)

**Comment by ztNFny** [comment]
Might have found the issue. With (at least) Espanol the regexp doesn't match. PR coming in a few min

**Comment by ztNFny** [comment]
GC has an annoyingly large number of variants to write the time string :-(
Espanonal: without ":" before the time
Korean: PM before instead of after time
Finish: . instead of : as divider

https://github.com/cgeo/cgeo/pull/16240 adjusts the regexp to now work for all languages (I've tested them all with 2 events each) and adds a additional try-catch to limit the impact of possible future website changes

**Comment by MagpieFourtyTwo** [comment]
When will this be available in the market? Just to calm down the others on the event we are just heading to ... ;)

**Comment by MagpieFourtyTwo** [comment]
Just had a short look at the regexps - good job, respect! And thanks for the immediate implementation!

**Comment by ztNFny** [comment]
> When will this be available in the market? Just to calm down the others on the event we are currently heading to ... ;)

From the start of release process until availability it's usually around 2-3 days, sometimes longer i case Google decides to have some funky review process on top of the normal stuff.

**Comment by MagpieFourtyTwo** [comment]
Just checked with some events - and it now even seems to work with gc.com set to German.
Nevertheless, found another issue with older events, which much to my surprise do not lose this first line with date and time.
In these listings, after refreshing the listing, the date/time string appears twice now - one from c:geo and one from the original listing:

![DoubleDate](https://github.com/user-attachments/assets/842d32ce-04ce-4127-9688-98df522f79d8)

As this looks a bit confusing, I would either check the first line of the listing if it already contains *the* date or at least add a line break.  This would not only preserve old listings from looking ugly, but we would additionally be prepared if GC.com realizes its mistake and reverts the whole thing. Ok, admitted, this is highly unlikely as GS is constantly trying everything possible to make its website even less usable and this change fits perfectly into this strategy, but you never know ... ;)

A second possibility could be to move the c:geo-generated time line to the details page, right under the date, like this:

![Details page](https://github.com/user-attachments/assets/6fc5e481-a4b3-4e50-b996-851fdbcacb14)

**Comment by ztNFny** [comment]
GC has updated all current event listings afaict. We shouldn't introduce workarounds for past events imho.
(Btw, GC has also not updated the text for some events where the time was changed, so even if the text exists in the listing it might be wrong)

**Comment by ztNFny** [comment]
Maybe we could overwrite instead of appending short description though .

**Comment by MagpieFourtyTwo** [comment]
> overwrite (...) short description

In the forum they wrote that some event owners used the short description to put info there, thus unconditionally overwriting it may lead to information loss,  Moreover rumors are that GS may be planning to remove the short description completely ...

**Comment by moving-bits** [comment]
FYI: The fix (#16240) has been released today with release 2024.10.27 (which is available already on Play Store)

**Comment by MagpieFourtyTwo** [comment]
Yep, thx for the hint - already seen at least one happy fellow on the event yesterday evening, who wanted to tell me that there is no date/time anymore. He unintentionally refreshed the listing and - boom - there it was again.  Will never forget the look on his face.  🤣🤣🤣

However - would say we can close here, can't we?
