### ISSUE TITLE
Wherigo: add "quick access actionbar" to all activities while wherigo is in play

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16238]
This is an idea which came up in some discussion about Wherigo Player which I want to keep track on.

Idea is to display an "action bar" below the real action bar on all c;:geo activities in case a Wherigo is currently playing. Placement shall be like the "filter bar" in map view/list view, UX view to be discussed. Tapping on this "wherigo bar" would bring the player to the Wherigo activity and/or open any pending dialogs.

**Comment by moving-bits** [comment]
Link to discussion mentioning this idea: https://github.com/cgeo/cgeo/discussions/16172#discussioncomment-10930291

**Comment by eddiemuc** [comment]
Fixed with PR #16274
