### ISSUE TITLE
Wherigo: add "quick access button" in map view

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16237]
This is an idea mentioned in some discussion about Wherigo (can't find it right now) which I want to keep track on.

Idea is to add a button on bottom of map view next to "quick access" and "route options" while a Wherigo is being played. This button shall open a popup (like quick settings) containing an overview of played wherigo (Inventory, tasks and such) and allows direct access to these options

**Comment by moving-bits** [comment]
Link to discussion mentioning this idea: https://github.com/cgeo/cgeo/discussions/16172#discussion-7280583
