### ISSUE TITLE
Add a filter for "original waypoint" (don't consider filled final waypoint)

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#16247]
### Tell us your idea!
I use "set as corrected coordinates" for those mysteries, where I already verified the final position, otherwise I am not quite sure, if the position of the final waypoint is correct.
With current implementation of the filter I cannot distinguish those mysteries.

### What solution would you suggest?
I would like to have a filter "has original coordinate" for mystery, which does not consider any filled final waypoint for mysteries.

### Is there an alternative?
No

The filter "corrected coordinates" counts mysteries also, if they have a valid final waypoint set (without setting it as "corrected coordinates").

### Additional Information

related to #11940

**Comment by murggel** [comment]
I was thinking about the same, but this means to change an existing behavior which others probably don't see as a bug.
And currently I don't see a combination of filters to get the same (current implementation) result, if we change the "corrected coordinates" filter.

**Comment by murggel** [comment]
Besides  - sometimes the filter works as implemented (show mysteries with filled final waypoint) and sometimes not (doesn't show the same mysteries with filled final waypoint)

I will have a look at this - probably related to calculated waypoints...

**Comment by ztNFny** [comment]
The "corrected coordinates" filter is quite new (I know because I added it some weeks ago), so I'd say modifying that one is probably ok. And actually I'd consider the current behaviour a bug as a Mystery with Final WP doesn't ahve "corrected coordinates" - I just didn't notice that when I implemented the above filter as such caches simply don't exist for me ;-)

**Comment by murggel** [comment]
@ztNFny 
Ok - then it be OK, when I change the filter or do you want to do it by yourself?

**Comment by murggel** [comment]
> Besides  - sometimes the filter works as implemented (show mysteries with filled final waypoint) and sometimes not (doesn't show the same mysteries with filled final waypoint)
> 
> I will have a look at this - probably related to calculated waypoints...

I think I found the culprit of my wrong behavior with calculated final waypoints - the flag 'finalDefined' is not updated when the variables are changed.

**Comment by ztNFny** [comment]
Please go ahead, I don't have time the next week
