### ISSUE TITLE
Log view: long date format overflows available space

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16249]
Ticket #778348 https://cgeosupport.droescher.eu/scp/tickets.php?id=8678
c:geo version: 2024.09.18

A user on support has problem with date display in log view: the year is displayed with 4 digits (format dd/mm/yyyy) which leads to truncation on his screen (he sees only the "20" part of a year eg "2023").

His system delivers format string "dd/MM/y" which explains this behavior. However, currently there is no chance to "overwrite this inside or outside of c:geo.

My suggestion is to always use an abbreviated year for display in log view, even if the system returns a "4-digit-year" as short date format.

Original user request:
is there a setting I can change so that everyone's logs for a cache appear with date format dd/mm/yy instead of dd/mm/yyyy please? On my screen, all I see is dd/mm/20 and the rest of the year is missing. 

- c:geo version: 2024.09.18
- Set language: en_GB (system default)
- System date format: dd/MM/y

**Comment by SammysHP** [comment]
I'm not sure the date format is to blame here. The layout just doesn't use the screen space efficiently. What about making the log text almost full-width (with a bit of margin on the left side) and give name, date and type its own full-width header?

**Comment by eddiemuc** [comment]
> I'm not sure the date format is to blame here. The layout just doesn't use the screen space efficiently. What about making the log text almost full-width (with a bit of margin on the left side) and give name, date and type its own full-width header?

That could be done, but it would not be what the user requested. He wants an abbrevated year format

**Comment by SammysHP** [comment]
> but it would not be what the user requested

Sure, but we are dealing with an [XY problem](https://en.wikipedia.org/wiki/XY_problem) here.

**Comment by eddiemuc** [comment]
> > but it would not be what the user requested
> 
> Sure, but we are dealing with an [XY problem](https://en.wikipedia.org/wiki/XY_problem) here.

I can't look the user in the head of course. But if I were the user I would want an abbrevated date instead of displaying a superfluous "20" in front of every year in every log date. This is totally independent from any layout discussions of the log view

**Comment by SammysHP** [comment]
> I can't look the user in the head of course.

Fortunately that is not necessary.

> But if I were the user I would want

It does not matter what the user wants. They might have a proposal for how to achieve their goal, but that is neither a description of the problem nor the only way to fix it. There might be an alternative.

> an abbrevated date instead of displaying a superfluous "20" in front of every year in every log date.

Is it superfluous? That's completely the choice of the locale. We cannot modify a locale without knowing the design of the locale and possible side effects. If we don't want to use the user locale, we should fall back to ISO 8601.

> This is totally independent from any layout discussions of the log view

Problem: User date format does not fit in view.

Context: User date format is defined by Android and the user's locale. c:geo uses whatever format is provided by the system. The date format is heavily influenced by the locale, including the order and type of the elements.

"Modifying the locale" is just one possible solution. I presented another solution.

**Comment by SammysHP** [comment]
This was already discussed here: #14014
