### ISSUE TITLE
Unified map buttons with weird touch animation

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#16255]
### Describe your problem!

Since the latest map buttons update, touch animations appear as a black animation filling the whole button for a second.

### How to reproduce?

Open unified map, touch buttons.

### Actual result after these steps?

Black, long touch animation.

### Expected result after these steps?

Shorter, less obtrusive animation.

### Reproducible

Yes

### c:geo Version

2024.10.21-NB-02fb30f

**Comment by ztNFny** [comment]
For the zoom buttons I changed it to that - as the other buttons (like quick settings) already were like that. 

For the zoom buttons there's a ripple element defined, changed it from grey to black.

**Comment by ztNFny** [comment]
The current touch effect design has been like this since forever - I checked many old releases. I guess it became more visibile when the zoom button touch effect was aligned to those other buttons.

Let's look into improving the touch effect for all buttons!

**Comment by moving-bits** [comment]
@SammysHP 
Can we close here after the latest changes introduced with #16296?

**Comment by SammysHP** [comment]
Yes, it looks better and more consistent now.
