### ISSUE TITLE
Support portal access denied

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16262]
My browser refuses to let me access the URL of our support portal. I get net::ERR_CERT_COMMON_NAME_INVALID error.

Is this a problem on my side or is there some problem to fix on server? @Lineflyer are you aware of any issues here?

**Comment by moving-bits** [comment]
It's a server-side problem, the provider is working on it.
Seems to be something bigger, as they estimate "a couple of days" (it's broken since Wednesday already).

**Comment by moving-bits** [comment]
FYI: Service seems to be up and running again, therefore closing here for now.
