### ISSUE TITLE
"Archived" log does not update cache status

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#16283]
### Describe your problem!

On geocaching.com when a cache owner posts "Archive" log, the cache status is changed to "Archived". 

### How to reproduce?

Have a cache you own.
Post an "Archive" log through c:geo.

### Actual result after these steps?

Log is posted, but after returning to the previous screen, cache status, as shown by c:geo was not updated.

![Screenshot_20241027-090428_cgeo](https://github.com/user-attachments/assets/4ab9bb90-ca73-45c6-8458-4d9125812b2c)

### Expected result after these steps?

Cache status to be updated, both "Status" field and title rendering.

### Reproducible

Yes

### c:geo Version

2024.10.14

**Comment by SammysHP** [comment]
I don't think this is a bug. An archive log and the archive status of the cache are different things. You could delete the archive log and the cache would still be archived. c:geo doesn't know how the log affects the cache status, it can only be determined after updating the cache.

OTOH something similar is done with found logs, but also that causes some issues from time to time.

**Comment by andrixnet** [comment]
I disagree with both previous comments. 
1. when "Archive" log is posted (ie submitted to geocaching.com, not saved offline), this has additional consequences = cache status -> archived. 
This should be immediately reflected in the cache page as shown by c:geo as a direct mirror to how the website presents information to the user. 
2. the act of posting the log has nothing to do with whatever may happen to it later (ie delete it?).
Thus such logic has no bearing here.
3. c:geo already does the right thing: posting "disable" log, upon returning to the cache page, it is shown with status disabled and title styled accordingly. Same when posting "enabke" log.

**Especially based on point (3) I request that the behaviour of posting "arhive" log be made to mirror all the changes to the cache.**

**Comment by fm-sys** [comment]
Actually this was working in the past and therefore should be a regression.
