### ISSUE TITLE
"Owner" marker to lower-right corner of cache icon

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#16284]
### Tell us your idea!

On the map there are additional visual markers added to cache icons to indicate various information. 
- found / DNF / offline logs are placed in upper-left
- stored is placed in upper-right
- list color is placed in mid-left
- personal note is placed lower-left
- owner marker is placed in upper-left, obscuring any log marker. 

For cache owners who saved offline logs this is an issue, because there is no visual cue to show those logs exist.

### What solution would you suggest?

Move the "owner" marker to lower-right, so far apparently unused, or at least with all the combinations that I have with caches I haven't seen it used.

![Screenshot_20241027-104713_cgeo owner marker (2)](https://github.com/user-attachments/assets/359971d3-b83e-420f-a3f7-16032031a3ec)

If it is used, then a solution should be found to illustrate both "owner" and logs, especially offline logs. 

### Is there an alternative?

None at the moment. (2024.10.14)

**Comment by ztNFny** [comment]
Lower right corner is corrected coordinates, one of the most important markers.

There are very few reasons to write logs on own caches, so this issue is very rare. Filtering by offline logs is also easily possible, so I don't think this needs a solution.

If anything a solution should be for the offline-log-marker to have higher priority than the owner one.

**Comment by Lineflyer** [comment]
The strategy of placing the markers was toroughly discussed and fine-tuned. 
I vote for bit changing it for the edge case of owners writing offline logs and not remembering them.

We could let offline log "win" over owner marker to have a compromise.

**Comment by ztNFny** [comment]
Current logic:
1. isOwner()
2. isFound()
3. hasOfflineLog()
4. isDnf()

Questions:
- Should Offline log "win" over isOwner()? - This Feature Request
- Should Offline log "win" over isFound()? - This would cause a lot of interferences with caches logged from outside c:geo, e.g. when exporting Field Notes. In that case there's still an offline log in c:geo and the user would have to manually delete them.

**Comment by andrixnet** [comment]
Since all these share the same marker place ... 
I would recommend :


1. hasOfflineLog()
2. isOwner()
3. isFound()
4. isDnf()

Regarding the second question: I see it more important to let the user know (since these markers exist) that an offline log exists for the cache, then the static information "isFound() = true". 

User can see difference between caches that have and do not have offline log via these markers in the advantageous context of having both states shown and differentiated. Filtering hides caches. It may be useful to see both. 

Exporting field notes case: it would highlight to the user that there are still stale offline logs. 
There is a bulk remove offline logs in "stored" section and I would rather recommend using this with appropriate filtering then hiding "hasOfflineLog()" behind "isFound()".

**Comment by andrixnet** [comment]
> the edge case of owners writing offline logs and not remembering them.

it's not the case of "not remembring them" but rather going through a set of owned caches and having the offline log marker would clearly show those which have been checked. It's easy when maintaining 2-3 caches, it's a whole different story when having 40 on your schedule.

**Comment by anondev-sudo** [comment]
Hello, for some of my caches owned marker/icon isnt show and only traditional/mystery cache without FI state is shown, owner marked isnt there. What could be the issue?

**Comment by ztNFny** [comment]
> Hello, for some of my caches owned marker/icon isnt show and only traditional/mystery cache icon is shown, owner marker isnt there. What could be the issue?

Imported or fetched from cgeo? In case of import: reload
