### ISSUE TITLE
Bottom navigation: when should it be shown and when not?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16287]
It is (to me) unclear under which circumstances a bottom navigation shall be shown or not shown depending on whether the current activity is in bottom navigation or not and how a "follow" activity is reached (and whether this is in bottom navigation or not.

I tested with Settings as a custom item. I observed and concluded:
- if an item is NOT part of bottom navigation then it should also never open with bottom navigation. 
- if it is at bottom nav and reached by clicking the bottom nav then bottom nav shall appear/stay
- a bit unclear: if we are in an activity with bottom nav but the item is selected by means other than the bottom nav (eg quick launch, button, menu item), shall the bottom nav stay or not? (in case of Settings as custom item, the nav bar will go away when selecting Settings from menu in main activity. This felt unexpected to me but might have a deeper reason?)
- if we jump to the item from within an activity without a bottom nav (by means like buttons, menu, tap,...) then the item too shall not have a bottom nav

Then I looked at the fixed navigation bottom items (stored lists, map, search) but found some inconsistencies:
- when executing a Search, the search result is displayed still in the bottom navigation - although it is another activity. Moreover when I tap ",search" in bottom nav then I go back to the search screen. Shouldn't bottom nav be gone for search result view?
- when I tap the map symbol in former search result then map is shown and bottom nav goes away. So reaching a bottom nav activity from another bottom nav activity by means other than bottom nav should hide the bottom nav?
- on the other hand, when in a stored list and tapping the "map" symbol in action bar, then we jump to map a d navigation bar stays. So the behavior is different than for search 

I am now not sure anymore what the rules shall be, so I opened this issue for discussion and advise.

**Comment by ztNFny** [comment]
one of the "funniest" cases: map a cache -> no bottom nav. Now in this view enable live -> bottom nav shows up.
Maybe because it's not live map? But it isn't really a live map, it's still the cache map .

**Comment by fm-sys** [comment]
> one of the "funniest" cases

This is actually an explicitly implemented behavior which was discussed in some team meeting long ago. Could be improved of course if someone comes up with a better concept...

**Comment by eddiemuc** [comment]
This issue will be closed for now. For Wherigo Player a behavior has been found, new issues may be opened when something is wrong there.
