### ISSUE TITLE
"Maintenance performed" log does not remove attribute

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#16282]
### Describe your problem!

On geocaching.com, the "Needs maintenance" attribute is used as a flag. 
Once a "Maintenance performed" log is submitted, this attribute is automatically removed.
When submitting a "Maintenance performed" log through c:geo, the "Needs maintenance" attribute remains.

### How to reproduce?

Have your cache with "Needs maintenance" attribute. 
Submit via c:geo a "Maintenance performed" log. 

### Actual result after these steps?

After sumitting the log, the "Needs maintenance" attribute is still present in c:geo. 

![Screenshot_20241027-084315_cgeo maintenance](https://github.com/user-attachments/assets/bc037426-7136-47cc-b10b-a9010797ce17)

### Expected result after these steps?

Expected c:geo to mirror the cache state on geocaching.com, ie the "Needs maintenance" attribute to be removed.

### Reproducible

Yes

### c:geo Version

2024.10.14

**Comment by SammysHP** [comment]
Is it fixed after updating the cache in c:geo?

**Comment by ztNFny** [comment]
Dup of #16283 - both are about c:geos internal state not being updated after a log
