### ISSUE TITLE
Features (potentially) missing in UnifiedMap Mapsforge

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16307]
_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/16214#issuecomment-2409095961_

Features (potentially) missing in Mapsforge:
- [x] 7ffd55603277dde31d800a877e5f063d56f693a3
- [x] 6b43cbbfa02d4e35400f31b720b5367dcebb29c2 
- [x] acbe6d610e78aac721163699e1f1638e6946e623 
- [x] 2343b705fd7b79e3793c2534b5f33accaa15bc05

**Comment by ztNFny** [comment]
I noticed a difference in geojson rendering on VTM vs Unified MF. Seems VTM is drawing less points - maybe for performance optimization??
MF:
![image](https://github.com/user-attachments/assets/b05f1418-1cf6-4583-a930-829203f83514)
VTM:
![image](https://github.com/user-attachments/assets/9c4ba789-fbff-4614-8c51-4c7439669824)

**Comment by ztNFny** [comment]
> * [ ]  [6b43cbb](https://github.com/cgeo/cgeo/commit/6b43cbbfa02d4e35400f31b720b5367dcebb29c2)
> * [ ]  [acbe6d6](https://github.com/cgeo/cgeo/commit/acbe6d610e78aac721163699e1f1638e6946e623)

can't spot a difference between VTM and MF, so seems ok

**Comment by fm-sys** [comment]
Thanks for testing!


---
For 2343b70 - z-layers

Vtm|mapsforge
-|-
![Screenshot_20241102-091002](https://github.com/user-attachments/assets/d4bac685-a4a1-4c1e-9c31-5cbb74c13a37)|![Screenshot_20241102-091023](https://github.com/user-attachments/assets/b80b80cd-41a5-49ed-b16a-2b4d552070cc)

---
For 7ffd556 - Position indicator isn't rotated properly when rotating map.

Example looking to East at both pictures 
|Northerned|rotated so that east is up|
-|-
![Screenshot_20241102-091417](https://github.com/user-attachments/assets/041e07b1-ecc3-4435-ad37-3a2d8ff51537)|![Screenshot_20241102-091434](https://github.com/user-attachments/assets/b9afcab2-16bc-4d1d-8f2f-3f3e7778df2e)

**Comment by moving-bits** [comment]
> For [7ffd556](https://github.com/cgeo/cgeo/commit/7ffd55603277dde31d800a877e5f063d56f693a3) - Position indicator isn't rotated properly when rotating map.

Fixed with #16318

**Comment by eddiemuc** [comment]
Whoever works on Geo item layer thingies for UnifiedMap Mapsforge might find the follow feature interesting:
* When you create a property `feature_unified_geoitem_layer` of type `boolean` and set it to `true`
* Then navigate to location `N40 00.0000 E010 00.000` (which is somewhere between Italy, corse and sicilia)
*  Then zoom out and look around

--> you will see a lot of artificially created geoitems, ready to test various things that can be done with geoitemlayer:

![image](https://github.com/user-attachments/assets/bcd55007-df05-4feb-b863-de80e43a47d0)

These geoitems are created by class `cgeo.geocaching.unifiedmap.geoitemlayer.GeoItemTestLayer` and were designed to test whether `cgeo.geocaching.unifiedmap.geoitemlayer.IProviderGeoItemLayer`-implementations can handle all kinds of features across maps.

**Comment by moving-bits** [comment]
Looks partly different with UnifiedMap Mapsforge:

![image](https://github.com/user-attachments/assets/6abfba02-54a1-4340-9145-483d8fba7ca9)

(lines at the bottom have round caps instead of straight ones)

**Comment by fm-sys** [comment]
Although I would consider round caps even preferable...

**Comment by ztNFny** [comment]
> Looks partly different with UnifiedMap Mapsforge:
> 
> ![image](https://github.com/user-attachments/assets/6abfba02-54a1-4340-9145-483d8fba7ca9)
> 
> (lines at the bottom have round caps instead of straight ones)

Layer order is quite different as well

**Comment by fm-sys** [comment]
> For [2343b70](https://github.com/cgeo/cgeo/commit/2343b705fd7b79e3793c2534b5f33accaa15bc05) - z-layers 

> Layer order is quite different as well 

Yes, I reported some comments above as well that the z-layers order is not working correctly.

@eddiemuc are you able to take a look at it? I tried but the layer management seemed too confusing for me...

**Comment by eddiemuc** [comment]
> @eddiemuc are you able to take a look at it? I tried but the layer management seemed too confusing for me... 

Layer management of mapsforge is confusing for me as well. I fear their interfaces are not really designed for our use case (in contrast to eg GMap where z-level-handling is simply done by assigning one to each object placed on the map).

I don't mind anyone taking a look at this and work out a z-level-concept for mapsforge from scratch. If no one steps in I can take this on my virtual list. But I will prioritize the Wherigo Player which I want to see out there urgently.

**Comment by fm-sys** [comment]
> I fear their interfaces are not really designed for our use case 

I believe to remember that you said the same about VTM and found some clever workaround at the end? 

> But I will prioritize the Wherigo Player which I want to see out there urgently.

Well, a fully functional unified map activated per default is probably a prerequirement for the Wherigo Player, isn't it? :)

**Comment by eddiemuc** [comment]
> > I fear their interfaces are not really designed for our use case 
> 
> I believe to remember that you said the same about VTM and found some clever workaround at the end? 

"Clever" is a strong word. I would call it a bunch of hacks.

> > But I will prioritize the Wherigo Player which I want to see out there urgently.
> 
> Well, a fully functional unified map activated per default is probably a prerequirement for the Wherigo Player, isn't it? :)

The player works well also with GMap or VTM via Unified map :-) And Unified map is out there in production anyway

**Comment by devemux86** [comment]
> I believe to remember that you said the same about VTM and found some clever workaround at the end?

VTM layer z-order was written same as Mapsforge, so just need to use a similar API.
The only difference was the _optional_ y-order in 3D.

**Comment by eddiemuc** [comment]
PR #16377 should fix the zlevel issues with unifiedmap mapsforge

**Comment by moving-bits** [comment]
All the initial issues are fixed meanwhile, and line endings are not yet in use on maps (AFAICS), so let's close here for now and open separate issues if something else comes up.

**Comment by fm-sys** [comment]
> and line endings are not yet in use on maps (AFAICS)

Well, they are in use (AFAIK) but one could argue that rounded line endings are the preferred way to go. IIRC rounded line endings were disabled at VTM just because they were causing rendering artifacts.

**Comment by ztNFny** [comment]
Lines are in use e.g. for routing

**Comment by eddiemuc** [comment]
> > and line endings are not yet in use on maps (AFAICS)
> 
> Well, they are in use (AFAIK) but one could argue that rounded line endings are the preferred way to go. IIRC rounded line endings were disabled at VTM just because they were causing rendering artifacts.

Correct. VTM didn't handle round caps well, this is why it was disabled in favor of butt caps. Old Map's mapsforge still uses round caps as far as I can remember. 

It should be noted though that Google Maps also currently uses Butt Caps. We should make ine decision for both.

Should we make a poll on whether to use round or butt caps?  
(for completeness sake: there would be a third option to use square caps)

**Comment by moving-bits** [comment]
> Lines are in use e.g. for routing

ah, you are right. I've set those lines small enough that I did not relate them to those bulky blocks in the screenshot above.

> Should we make a poll on whether to use round or butt caps?

From a quick glance at Google Maps / NewMap / UnifiedMap VTM in current release I would prefer round caps, they look smoother, IMHO.

**Comment by eddiemuc** [comment]
After this issue seems to be fixed, what is still open before we can do a new beta release?
