### ISSUE TITLE
Wherigo Player: wherigo icon(s) used on various screen. New icon wanted/needed?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16333]
As of now I used existing icons to display "Wherigo" across c:geo. Is there the need or the wish to design an own new icon for these purposes? And if yes, would there be someone willing to do so?

As of now I am mainly using `R.drawable.type_marker_wherigo`, except for starting a wherigo from cache details. Here's a table of usages:

| Place         | Screenshot | Currently used | Code Reference |
| ------------- | ------------- | ------------- | ------------- | 
| Quick Launch Item / Custom Menu item | ![image](https://github.com/user-attachments/assets/51723369-664b-4ebd-9517-d40b548d03cc) | `R.drawable.type_marker_wherigo` | https://github.com/cgeo/cgeo/blob/adefb488719089287935a99c36eae7752a31b1e9/main/src/main/java/cgeo/geocaching/enumerations/QuickLaunchItem.java#L70 |
| Wherigo start (in cache details) | ![image](https://github.com/user-attachments/assets/329a317e-8b9c-4fd5-bc56-62edffde95b9) | `@drawable/ic_menu_select_play` | https://github.com/cgeo/cgeo/blob/adefb488719089287935a99c36eae7752a31b1e9/main/src/main/res/layout/cachedetail_details_page.xml#L160 |
| Wherigo related notification | ![image](https://github.com/user-attachments/assets/5d250c3c-0acf-48d4-9886-b190adfb8f41) ![image](https://github.com/user-attachments/assets/5bab67fb-0a44-4e75-8bea-7bf769e9422a) | `R.drawable.type_marker_wherigo` | https://github.com/cgeo/cgeo/blob/adefb488719089287935a99c36eae7752a31b1e9/main/src/main/java/cgeo/geocaching/wherigo/WherigoGameService.java#L51 https://github.com/cgeo/cgeo/blob/adefb488719089287935a99c36eae7752a31b1e9/main/src/main/java/cgeo/geocaching/wherigo/WherigoDialogManager.java#L236 |

**Comment by ztNFny** [comment]
The drawable needs some tweaking to have the correct size though... Will look into it.

**Comment by ztNFny** [comment]
> Wherigo start (in cache details)

Should we add a separate section to CacheDetails to "Play with c:geo internal WIG player"? This section would in the beta period be opt-in, then additional (with the "old" one maybe being hidden behind a setting) and then finally the old one being removed.

The current setup is ok for developers but as soon as it goes user-facing there'll be quite some confusion why there are 2 buttons and why the c:geo internal is next to a text about a 3rd party app.

**Comment by ztNFny** [comment]
> The drawable needs some tweaking to have the correct size though... Will look into it.

see [PR](https://github.com/cgeo/cgeo/pull/16335)
