### ISSUE TITLE
WIG map shows caches (by default)

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16338]
Mapping a WIG, no matter whether it's the "global" map button or an individual waypoint, show's a map with all offline stored caches (no matter whether live mode is enabled or not).
I'd expect the map to show only the WIGs zones.

**Comment by eddiemuc** [comment]
Current implementation just opens the map in it's "current mode" (no parameter istransported to the map) with the viewport set to either a single zone (if a zone is selected) or zoomed out to display all zones (if "global" is selected).

The request made here would require a new "wherigo map mode" or similar. 

I am open to this discussion but personally don't have a use for a map view which is "wherigo only". I require however a way to turn the map back to "live" quickly if this feature should be implemented. (current "live" button is enough for that).

**Comment by ztNFny** [comment]
I'm not asking for a new mode, just the mode that's already existing for e.g. viewing a single cache. Mapping a WIG or a WIG zone is identical to mapping a cache or a single waypoint of it from a usecase point of view - but the implementation is different - thus it's a bug.

**Comment by eddiemuc** [comment]
Currenty the (unified) map has following types (sorry, it is not called "mode"). Which one would be the one to use?

![image](https://github.com/user-attachments/assets/adee2964-81f4-4783-b890-ad2ee44bb519)

**Comment by ztNFny** [comment]
Found it - GeocacheFilterContext.FilterType

        LIVE(R.string.cache_filter_contexttype_live_title),
        OFFLINE(R.string.cache_filter_contexttype_offline_title),
        TRANSIENT(R.string.cache_filter_contexttype_transient_title);

**Comment by ztNFny** [comment]
Only selected cache shown:
            final UnifiedMapType mapType = new UnifiedMapType(geocode);
            mapType.filterContext = new GeocacheFilterContext(GeocacheFilterContext.FilterType.TRANSIENT);
            mapType.launchMap(fromActivity);

All caches shown:
            new UnifiedMapType(geocode).launchMap(fromActivity);

**Comment by ztNFny** [comment]
PR coming in :-)

**Comment by eddiemuc** [comment]
> Found it - GeocacheFilterContext.FilterType
> 
> ```
>     LIVE(R.string.cache_filter_contexttype_live_title),
>     OFFLINE(R.string.cache_filter_contexttype_offline_title),
>     TRANSIENT(R.string.cache_filter_contexttype_transient_title);
> ```
> 
> Live = Offline + Live Offline = Offline only Transient = none at least that's how I read it

Really sorry... 
If "map mode" logic is currently implemented based on filter context then this implementation in the map is wrong. Filter Context and "map mode" are and shall be two independent things. If anything, then the choosing of the correct filter context has to be based on the map mode, not vice versa.

Background: GeocacheFilterContext implements the (complex but wanted...) logic on how many cache filters we should persist in cgeo and in which context which stored filter shall be reused. I remember the huge discussions, I even painted slides for this stuff back then... GeocacheFIlterContext is used throughout c:geo in map, stored lists and search (and probably in other places as well) And of course those filters are purely Geocache-based and have nothing to do with other things displayed on map like eg routes, tracks, geojson or wherigo-objects.

**Comment by ztNFny** [comment]
tbh I find the current implementation to involve a lot of black magic that I don't understand...
But from what I can tell that is the logic that's currently being use for mapping from cache activities, e.g. from InternalMap.navigate()

As mentioned in the PR it's probably worth a rewrite or at least better documentation?

**Comment by ztNFny** [comment]
OT: What is "Locate on center" doing? Other than setting the text and "revoke fixed location" button I'm not seeing any effect.

**Comment by moving-bits** [comment]
> Found it - GeocacheFilterContext.FilterType

That is part of the filter configuration for the map - stored live map filter, stored offline (list) filter, or unstored (transient) filter context. Which filter context gets applied is part of the map type configuration set by using a `UnifiedMapType`.

**Comment by ztNFny** [comment]
> > Found it - GeocacheFilterContext.FilterType
> 
> That is part of the filter configuration for the map - stored live map filter, stored offline (list) filter, or unstored (transient) filter context. Which filter context gets applied is part of the map type configuration set by using a `UnifiedMapType`.

That's not what I'm see in the existing implementations for mapping a single cache/waypoint though - there this is used to control whether to display only the single point(s) or all, see: DefaultMap.startActivityGeoCode which is called from InternalMap.navigate()

**Comment by eddiemuc** [comment]
> OT: What is "Locate on center" doing? Other than setting the text and "revoke fixed location" button I'm not seeing any effect.

Those are only available/used in "cartridge-debug" mode.

**Comment by moving-bits** [comment]
> > That is part of the filter configuration for the map - stored live map filter, stored offline (list) filter, or unstored (transient) filter context. Which filter context gets applied is part of the map type configuration set by using a `UnifiedMapType`.
> 
> That's not what I'm see in the existing implementations for mapping a single cache/waypoint though - there this is used to control whether to display only the single point(s) or all, see: DefaultMap.startActivityGeoCode which is called from InternalMap.navigate()

This is a misunderstanding: The "magic" happens in the line before: `final UnifiedMapType mapType = new UnifiedMapType(geocode);` which calls a specific constructor, which sets `type = UnifiedMapTypeType.UMTT_TargetGeocode;`.

The next line in `DefaultMap.startActivityGeoCode`. which sets a specific filter context, is needed, as we want to have a different filter context (TRANSIENT) here instead of the default LIVE.

**Comment by moving-bits** [comment]
If we want to have some specific map behavior when being called for WIG zones, then we should create a new `UnifiedMapTypeType` and add the desired behavior to `UnifiedMapActivity` to be used with this map type.
