### ISSUE TITLE
Add Small Window feature

### ISSUE THREAD

**Issue by Korb** [cgeo/cgeo#16347]
### Tell us your idea!

The Small Window (aka **picture-in-picture** mode) feature allows you to display a window overlaying other apps and pin it to the edge of the screen as an always-on small label. The label can be freely moved along the side edges of the screen.

### What solution would you suggest?

Android Developers / Develop / Core areas / UI / Guides / [Support multi-window mode](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-multi-window-mode)

### Is there an alternative?

Split-screen

### Additional Information

![Screenshot_20241115_234212](https://github.com/user-attachments/assets/a906484e-5633-41c3-9908-108a47cc0280)

**Comment by ztNFny** [comment]
That's an OS-level feature, apps don't need to support something explicitly but can opt out of being resizable - which c:geo doesn't do.
Different phone manufacturers expose the split screen / floating app UI in different ways and it may be that yours exposes it in limited ways or doesn't do it at all.
![image](https://github.com/user-attachments/assets/2f1fbb35-5423-44c6-b493-98abda7f1c4e)

**Comment by ztNFny** [comment]
> OS version: Funtouch OS 14

that "Small window" menu item is something that doesn't exist in Android but is implemented by your phones manufacturer. How they decide to display it is not something that c:geo has any influence on. c:geo supports multi-window mode.

**Comment by Korb** [comment]
Very interesting behavior of the PiP function, which works in some applications and does not work in other applications.

> In the OS I'm using it's available for any app, including c:geo

What OS do you have?

**Comment by Korb** [comment]
> What OS do you have?

@ztNFny?

> that "Small window" menu item is something that doesn't exist in Android but is implemented by your phones manufacturer.

This isn't true.

`Small Window` is a standard Android feature—`Picture-in-Picture` (`PiP`), available since Android 7.0 (for multi-window) and Android 8.0 (API level 26) for PiP in its current form. Vivo simply **calls** it `Small Window` in its FuntouchOS interface. Developers must explicitly declare PiP support in the app manifest by setting the `android:supportsPictureInPicture` attribute to `true`. Google, naturally, implements support for the standard Android API in all its apps where it makes sense (YouTube, Maps, Meet, etc.). Therefore, `Small Window` is available in all Google apps that I tested. And this function works properly in all cases.

I currently have `c:geo 2025.09.19 f-droid` installed and PiP is still not available.

**Comment by ztNFny** [comment]
PiP is something completly different. Unfortunately there are many related things and the developer docs on Android are not really user-friendly in explaining that. 
PiP is a special mode - it's what you get e.g. on YouTube when playing a video in background. Small window/Floating window/Split screen is just showing the normal app window in a subset of the screen - same as resizing a window on a desktop OS.
