### ISSUE TITLE
Buttons with and without accent color

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16341]
While working on Wherigo Player and triggered by a rightful comment of @ztNFny I wondered what the " design rule" is in c:geo for buttons and usage of ascent color. It seems that:
* pure text buttons are in ascent color
* pure icon buttons are NOT in ascent color
* buttons with both icon and text are in ascent color

I concluded the above "rules" from the way I found it in c:geo as of now. There are however also exceptions to some of these rules nowadays. Question is:
* should those be the button ascenting rules? If not, how should they be changed? Or are there no such rules?
* if we have rules, should we enforce them to existing screens?

Example for icon buttons (NOT in ascent color, taken from cache details):
![image](https://github.com/user-attachments/assets/16b04775-8b75-4176-8da9-1a31482ab8f4)

Example for text buttons (in ascent color, taken from waypoint tab):
![image](https://github.com/user-attachments/assets/b5a249b5-7b8e-4df8-b93c-d2a2eb89f7c2)

Example for icon + text buttons (in ascent color, taken from waypoint details):
![image](https://github.com/user-attachments/assets/778cb2e3-c1a7-4502-98ca-63999f81dfe5)
![image](https://github.com/user-attachments/assets/291e3caf-0aa2-4ea9-a114-5b63dc41f384)

And then there's the variable tab with all-ascent buttons. BUT according to the rule at least the first button (the one with the "plus"-icon only) would have to be turned into a non-ascent button wouldn't it? That would look strange though
![image](https://github.com/user-attachments/assets/cf32b5dd-3712-4f2c-847f-8b6387a02484)

And here is the Wherigo player with both icon buttons and a text button (taken from wherigo activity whilst a dialog was paused):
![image](https://github.com/user-attachments/assets/fa436eb9-62e2-4002-a63e-4da5bb462e5e)

Finally, I just saw that the icons in the Wherigo buttons are now no longer in ascent color but only the texts are (taken from cartidge detail dialog):
![image](https://github.com/user-attachments/assets/5d75c3eb-b5e9-484c-b125-bc2a7812b9ee)
(this looks kinda nice. Should all buttons with text and icons be changed into this format?)

**Comment by ztNFny** [comment]
I like the white icon + orange text style.
Having different icon color for "icon only" vs "icon with text" as "proposed" in the sentence about variable tab seems to be a really confusing approach.

**Comment by eddiemuc** [comment]
With PR #16353, buttons will now look like this (like in wherigo player):

![image](https://github.com/user-attachments/assets/b40a8b9d-e036-4a0a-8748-39c821c42015)
![image](https://github.com/user-attachments/assets/f9572e54-51dd-4482-841a-05ba55b05a1d)
![image](https://github.com/user-attachments/assets/7f37a288-723d-4582-800a-46a48b0a984b)

**Comment by eddiemuc** [comment]
Light mode:
![image](https://github.com/user-attachments/assets/b4a23697-3466-4b47-a334-9a9688635e2e)

**Comment by ztNFny** [comment]
Hm, the variables tab buttons look strange ...

**Comment by eddiemuc** [comment]
> Hm, the variables tab buttons look strange ...

MIght be, but that happens when the pattern "icon in text color" is applied. I assume you don't want to switch to icon buttons in ascent colors either. So what to do?

**Comment by ztNFny** [comment]
Is variables tab the only place using buttons like that? If so maybe it's possible to enhance those buttons to be icon-only. I can try to create some icons.

**Comment by eddiemuc** [comment]
> Is variables tab the only place using buttons like that? If so maybe it's possible to enhance those buttons to be icon-only. I can try to create some icons.

At least the button with + symbol and the A also transports some information (A in this example would be the name of the variable which is created when button is clicked).

I believe it would be a big challenge to find icons where a user can associate intuitively complex things like eg "scan listing" or "create a variable with name A" or "sort variable list and remove empty entries".

I thought there's a chance to unify button design very easily. If this all creates too much work then we can also abandon here and leave everything as is.

**Comment by ztNFny** [comment]
I really love the idea of unification and think it's the right direction. However with how c:geo is grown organically over the years, sometimes without clear guidance, it's unfortunately not always trivial to achieve that. Also for those full-width button it's a good way to go imho.
Right now I think variables is the only place using that mixed icon+text style, so as a first step we could unify it for all places but that one - and then look into a solution for that one as time permits.

**Comment by ztNFny** [comment]
see https://github.com/cgeo/cgeo/pull/16359
