### ISSUE TITLE
Wherigo: Missing the name of Cartridge when deleting

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#16351]
### Describe your problem!

The name of the Cartridge that is beeing deleted is represented as "_"

### How to reproduce?

Open Wherigo Player
Select Cartridges
Select delete

### Actual result after these steps?

The text indicates:
" Do you really want to delete cartridge "-" including 1 savegame? "
![1000045044](https://github.com/user-attachments/assets/84f28401-0768-4859-9f36-514a802456eb)

### Expected result after these steps?

Do you really want to delete cartridge "cartridge name" including 1 savegame? "

### Reproducible

Yes

### c:geo Version

202024.11.16-NB-4050839

**Comment by eddiemuc** [comment]
will be fixed with PR #16350
