### ISSUE TITLE
Offline Map management issues

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16357]
Ticket 899787 on support:
- ~Bug: User has four offline maps configured, but only two are shown in "home screen" => "Manage offline data" => "Delete offline data"~ => fixed with PR #16404
- ~Feature request: User requests to have the "delete offline data" available in map context~ => fixed with PR #16369

**Comment by ztNFny** [comment]
> * Feature request: User requests to have the "delete offline data" available in map context

you could pull the "Manage offline data" from https://github.com/cgeo/cgeo/pull/16127

**Comment by moving-bits** [comment]
WRT to the first part, not all maps being offered for deletion: This may be caused by maps installed manually, as we check for the downloader's companion file. I've asked the ticket issuer for a cross-check.
