### ISSUE TITLE
Event time display follows users timezone, not event

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16367]
After https://github.com/cgeo/cgeo/pull/16302 the event time display in c:geo now follows the time zone the user has set in https://www.geocaching.com/account/settings/preferences while previously it was in the events local timezone.

Both versions have their pros and cons:
- Event timezone: I guess that's what users expect to see when viewing a listing. Also it's what GC shows at the top of the listing and what was previously added in short description field - the users timezone setting in preferences is just ignored.
- Users timezone: Actually correct in relation to the user, but maybe unexpected. Calendar entries for an event in another timezone will be correct

(Option 3 would of course be to do both, but that'd require additional DB fields for the times)

I vote for changing it back to event timezone - opinions?

PS: users timezone is of course not available in the json ...

**Comment by ztNFny** [comment]
any feedback on the current solution? would be nice to discover potential issues before another release this time ;-)

**Comment by moving-bits** [comment]
The fix has been released as 2024.11.22, and I have asked two users on support if the problem they had reported has been resolved, which they confirmed. So I guess we can close here for now.
Thanks for adapting the fix.
