### ISSUE TITLE
Additional icons

### ISSUE THREAD

**Issue by ianfhunter** [cgeo/cgeo#16371]
### Tell us your idea!

There are a few cache icons that I would like to have in the app. Obviously I can use others in the meantime, but it would be nice to not have to make a mental mapping 

### What solution would you suggest?

- 💰 or 🪙  (helpful to indicate if a cache requires paid entry) 
- ~~✅ and ❎ (helpful for solved puzzles, etc)~~ (Actually these are already there)
- other cache types (e.g. a mystery cache that is really more like a multicache)

### Additional Information

As a programmer myself, I'm happy to try add these (pointers to places in code would be appreciated). But the readme says to file a ticket rather than begin hacking.

If I do so I might look to include some other icons like 🤷 👪 🐕 for others' benefit. But for now the ones I want are listed above

**Comment by fm-sys** [comment]
Hi @ianfhunter, thanks for your suggestion. Code contributions are always welcome! :) 

You may take a look at https://github.com/cgeo/cgeo/blob/master/main/src/main/java/cgeo/geocaching/utils/EmojiUtils.java
