### ISSUE TITLE
Integrated map downloader is hiding some maps

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16383]
While looking into some ticket on support I noticed that our integrated map downloader is not showing some of the files provided by "Mapsforge" server. It looks like it's hiding all files ending on "-" + number, eg. "New-zealand-1.map", see [this server listing](https://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/v5/australia-oceania/) and compare it to what c:geo shows.

**Comment by devemux86** [comment]
We now split the maps and pois that are around the 180th meridian.
