### ISSUE TITLE
Wherigo: Identify Wherigo player as c:geo and not openWIG

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#16398]
### Tell us your idea!

I was playing with a Waldmeister Wherigo reverse cartridge, and after completing it,  in the inventory in the Statistics object, it's indicated that the wherigo-player is: openWIG.

![1000045811](https://github.com/user-attachments/assets/4b06b655-225a-4ecd-84f3-7a7334474abd)

### What solution would you suggest?

Replace the wherigo player form openWIG to c:geo

### Is there an alternative?

Keep as is.

**Comment by rouroni1** [comment]
I've tested with WhereYouGo and there it identifyed as: Android/WhereYouGo.

The cartridge retieve the DeviceID information from: "Environment.DeviceID"

Here's a screenshot of it in Urwigo
![image](https://github.com/user-attachments/assets/2f83b6e4-f3d5-4925-9161-ac493af70011)

In my cartridge I use it also to detect where the cartridge is being played (prevent emulation on a serie of devices...)

Here's the sample of the lua code of that part, where I've defined that the devices "webwigo", "emscripten", "browser" and "Desktop" are emulators:

"	elseif Wherigo.NoCaseEquals(input, "English") then
		if Wherigo.NoCaseEquals(Env.DeviceID, "webwigo") then
			Wherigo.PlayAudio(obj00YouShallNotPassAudio)
			_Urwigo.MessageBox{
				Text = "Web browser / emulator usage detected. This cartridge is designed to be played on devices GPSr, Android, and iOS. Thank you.", 
				Media = obj00YouShallNotPass
			}
		elseif Wherigo.NoCaseEquals(Env.DeviceID, "emscripten") then
			Wherigo.PlayAudio(obj00YouShallNotPassAudio)
			_Urwigo.MessageBox{
				Text = "Web browser / emulator usage detected. This cartridge is designed to be played on devices GPSr, Android, and iOS. Thank you.", 
				Media = obj00YouShallNotPass
			}
		elseif Wherigo.NoCaseEquals(Env.DeviceID, "browser") then
			Wherigo.PlayAudio(obj00YouShallNotPassAudio)
			_Urwigo.MessageBox{
				Text = "Web browser / emulator usage detected. This cartridge is designed to be played on devices GPSr, Android, and iOS. Thank you.", 
				Media = obj00YouShallNotPass
			}
		elseif Wherigo.NoCaseEquals(Env.DeviceID, "Desktop") then
			Wherigo.PlayAudio(obj00YouShallNotPassAudio)
			_Urwigo.MessageBox{
				Text = "Web browser / emulator usage detected. This cartridge is designed to be played on devices GPSr, Android, and iOS. Thank you.", 
				Media = obj00YouShallNotPass
			}
		elseif Wherigo.NoCaseEquals(Env.Device, "Win32") then
			Wherigo.PlayAudio(obj00YouShallNotPassAudio)
			_Urwigo.MessageBox{
				Text = "Web browser / emulator usage detected. This cartridge is designed to be played on devices GPSr, Android, and iOS. Thank you.", 
				Media = obj00YouShallNotPass
			}
		else
			_Urwigo.RunDialogs(function()
				Wherigo.GetInput(obj00ParqueEcologicoEN)"

**Comment by eddiemuc** [comment]
Fixed with PR #16400 

I peeked into WhereYouGo code and saw that it sets deviceId to app name ("WhereYouGo") and version string. I applied same to c:geo.
I also set "platform" to "Android" + android version + build

**Comment by rouroni1** [comment]
With today nightly instead of OpenWIG, now shows "?"

If neaded I can open a new Issue...

![Screenshot_2024-12-01-19-09-28-999_cgeo geocaching](https://github.com/user-attachments/assets/5a0a7771-9698-4c9a-8f8f-b766bf0d1d28)

**Comment by eddiemuc** [comment]
I don't know the inner logic of the Wherigo in question. Is it possible that it doesn't show the device ID directly but has some internal decision logic about this? I have no idea where else the "?" should originate from.

**Comment by rouroni1** [comment]
I don't know if any of this helps, I'm just an IT guy without any programming knowledge :( , but here's wath I just tried:

Created a cartridge with input: Any awnser is Ok

Tested with old DesktopWIG (jar), got the result for DeviceID: dsktpwig

Then searched in the java code for the work DeviceID with the following powershell command:
PS C:\Users\Julito\desktop\b> Get-ChildItem -Recurse -Filter *.java | Select-String -Pattern "DeviceID"

Results:
DesktopWIG (decompiled the jar file)
cz\matejcik\openwig\desktop\Main.java:33:      WherigoLib.env.put("DeviceID", "dsktpwig");

Github repository of WHereYouGo
src\main\java\menion\android\whereyougo\MainApplication.java:144:        // set DeviceID for OpenWig
src\main\java\menion\android\whereyougo\openwig\WUI.java:120:    public String getDeviceId() {

Github repository of c:geo

main\src\main\java\cgeo\geocaching\wherigo\WherigoGame.java:101:        //core Wherigo settings: set DeviceID and
platform for OpenWig


[DesktopWIG-0.3.zip](https://github.com/user-attachments/files/17970033/DesktopWIG-0.3.zip)
[test_device.zip](https://github.com/user-attachments/files/17970041/test_device.zip)

**Comment by eddiemuc** [comment]
@rouroni1 : following your request I put code into c:geo to set the deviceid for c:geo's Player to "c:geo <version>", e.g. "c:geo 2024.11.22". Here is the code for that:

![image](https://github.com/user-attachments/assets/1c6bade6-12d0-418b-8962-d69de867a8a4)

In this I followed 1:1 the approach of WhereYouGo which is doing exactly the same (App name, which is "WhereYouGo", followed by the apps version). Here is the code from WhereYouGo for this:

![image](https://github.com/user-attachments/assets/deff7f9e-5297-414c-90a3-a4d9207ff6c7)

What I don't know is what a cartridge (in this case the Reverse Cache Cartridge) makes out of this information. If it would plainly display it it should read "c:geo <version>".

It is possible that the cartrdige actively try to discover a known Wherigo Player from the string but doesn't know about c:geo yet (that wouldn't be very surprising :-)). E.g. something liek the following (this is pseudo-code, I don't know Lua or the Wherigo framework in it):

```
if Wherigo.NoCaseContains(Env.DeviceID, "whereyougo") then
   DisplayText = "WhereYouGo"
elseif Wherigo.NoCaseContains(Env.DeviceID, "browser") then
   DisplayText = "Browser"
elseif Wherigo.NoCaseContains(Env.DeviceID, "browser") then
   DisplayText = "Browser"
else
  DisplayText = "?"

//then display value of DisplayText to user
```

But I don't know the source code of the cartridge, so I can't tell what is done there.

**Comment by rouroni1** [comment]
@eddiemuc 

You are completly right. I made the quick cartridge to test the retrieval of the DeviceID, but I didn't test on c:geo (I'm feeling so dumb right now...)

I'll try to ask wadmeister, if I don't get any info, then I'll try to reverse engineer the cartridge.

But one thing is right, it's not a c:geo issue :)

**Comment by rouroni1** [comment]
Hi,

To conclude.

After submitting the cartridge to reverse engineering, I found that the method used to identify the "player" is a function "getDeviceName()" that is executed and then stores the resulting value to be used later.

The function is:
function getDeviceName()
  local platform = "*"
  if Env and Env.Platform then
    platform = Env.Platform
  end
  local deviceId = "*"
  if Env and Env.DeviceID then
    deviceId = Env.DeviceID
  end
  if platform == "Vendor 1 ARM9" then
    return "Garmin"
  end
  if string.sub(platform, 1, 8) == "PocketPC" then
    return "PocketPC"
  end
  if string.sub(deviceId, 1, 10) == "WhereYouGo" then
    return "Android/WhereYouGo"
  end
  if platform == "J2SE" then
    return "DesktopWIG"
  end
  if platform == "MIDP-2.0/CLDC-1.1" then
    return "OpenWIG"
  end
  if string.sub(Env.Platform, 1, 6) == "iPhone" then
    return "iPhone"
  end
  if deviceId == "Desktop" then
    return "Emulator"
  end
  return "?"
end

And since cgeo still doesn't exist on the list of devices, the latest info that the funtion returns is "?".

Thank you.

**Comment by eddiemuc** [comment]
If code like this is exemplary, would it be better if c:geo's Wherio Player "emulated" an existing device? (e.g. "WhereYouGo"). Because otherwise cartridges restricting "unknown" device ids would not work with c:geo player?
