### ISSUE TITLE
Make UnifiedMap the new default map for all users

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16399]
This issue is meant to collect all tasks that need to be done for making UnifiedMap the new default map.

Proposal:
- publish a beta / next release with current state of `master`
- then implement the tasks listed in this issue on the new state of `master` to become part of the next feature release

Tasks:
- settings => map sources
  - [x] move items from today's section "Unified Map (Beta)" to "Map Data" section
    (Select Map Source, Hide Map Source, UnifiedMap Variants, User-defined Tile Provider)
  - [x] add checkbox "use legacy map"
  - [x] make today's "select map provider" dependent from it
  - [x] enable/disable map sources-related items depending on this switch's value

- settings => appearance
  - [x] rename "Unified Map (beta)" to "Unified Map (VTM only)" (or something like this)
  - [x] Make clear, that those scaling options are for VTM only
- internal settings
  - [x] remove flag "use UnifiedMap"
  - [x] new flag "use legacy map", default `false`
  - [x] make "UnifiedMap (Mapsforge)" default variant (instead of "UnifiedMap (VTM)")
  - [x] remove calls to "showUnifiedMap" setting
- [x] adapt system information
- [ ] (optional) migrate map provider settings to tile provider settings

**Comment by ztNFny** [comment]
Thinking about the preferences UI, wouldn't it be more accessible to users to have 1 dropdown "Map source" with options:
UM MF
UM VTM
UM MF+VTM
Legacy

**Comment by ztNFny** [comment]
> * Make clear, that those scaling options are for VTM only

Couldn't see that in your PR, but the setting should be disabled unless VTM is selected

**Comment by moving-bits** [comment]
> Thinking about the preferences UI, wouldn't it be more accessible to users to have 1 dropdown "Map source" with options: UM MF UM VTM UM MF+VTM Legacy

I did not want to invest into that as I regard the legacy maps as temporary, which should be removed in a couple of months or so.

> > * Make clear, that those scaling options are for VTM only
> 
> Couldn't see that in your PR, but the setting should be disabled unless VTM is selected

It's in the preference's summary string, but disabling the section totally if VTM is not available is even better. => will add this to my PR
