### ISSUE TITLE
Wherigo: Better handling of multiple cartridges in listing

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#16415]
### Describe your problem!

Some old geocaching listings have the cartridges link with http instead of https.
c:geo only detects https links.

### How to reproduce?

Open GC7CAGJ 

http://www.wherigo.com/cartridge/details.aspx?CGUID=673530dd-1a0c-4bab-8939-46ba6a8093b8

### Actual result after these steps?

If the cartridge link is with http, then:
There's only the option to open with WhereYouGo 
There's no option to download and plasy with c:geo

### Expected result after these steps?

To be able to download and then play the cartridge with c:geo

### Reproducible

Yes

### c:geo Version

2024.12.06-NB-89f5c8b

**Comment by ztNFny** [comment]
The problem with that cache is not the http-Link but the fact that multiple WIGs are linked:
0 = "673530dd-1a0c-4bab-8939-46ba6a8093b8"
1 = "6d64418c-9d4c-4af3-8a4e-89f7c2cb41e6"

**Comment by ztNFny** [comment]
we could ask the user which cartridge he wants to download in this case. However as only the IDs are available it'd be quite hard to show a reasonable GUI in this case. maybe a "multiple cartridges deteceted, refer to the listing" popup?

**Comment by rouroni1** [comment]
Found a other with two cartridges, but on this one c:geo dosen't show option to download, even to WhereYouGo.

HTTPS://coord.info/GC6N9WZ

**Comment by eddiemuc** [comment]
Another example:  https://coord.info/GC7XABX

**Comment by eddiemuc** [comment]
I will tackle this issue
