### ISSUE TITLE
support callback in CoordinatesInputDialog

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16413]
as part of https://github.com/cgeo/cgeo/issues/16361 I'll need the possibility to add a callback method to CoordinatesInputDialog.

Usecase:
Click the "coordinates" button which opens the CoordinatesInputDialog. On confirming that one (using the Checkmark in upper right) search should be triggered with the provided coords.
Going back / using the X should not do anything

**Comment by eddiemuc** [comment]
I look into it

**Comment by eddiemuc** [comment]
@ztNFny CoordinatesInputDialog is implemented as a Dialog fragment which requires the using activity to implement interface `CoordinatesInputDialog.CoordinateUpdate`. The method `public void updateCoordinates(@NonNull final Geopoint gp)` is called whenever the user confirms the dialog (checkmark in upper right). This might be all you need.

* To open the coordinate selection dialog: call `CoordinatesInputDialog.show(getSupportFragmentManager(), null, null);`
* To do something when user confirms this dialog: implement it in method `public void updateCoordinates(@NonNull final Geopoint gp)` of `SearchActivity`

Can't say I really like the design choices made for that dialog, but to change it would mean a big deal of redesign....

**Comment by ztNFny** [comment]
@eddiemuc  thanks for this great explanation! I tried to figure out how that dialog worked but always got lost - despite it being so simple (now with your explanation!). With that it took me <5 min to adjust the search accordingly.
Probably worth adding that explanation in the javadoc of CoordinatesInputDialog?
