### ISSUE TITLE
Wherigo issues reported on support

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16418]
Let's use this issue as a pointer to issues with the new Wherigo player reported on support:

- [ ] Engine Error: you hit a bug! [...] java.lang.RuntimeException: attempted index of non-table: null (ticket 929523)
- [ ] Cartridge download link in listing not detected (ticket 929523)

**Comment by eddiemuc** [comment]
Cache in question: https://coord.info/GC7XABX

First problem seems to be cartridge internal and not fixable by us (only by cartridge owner). The user used an older version of the WherigoPlayer, in current version (beta) there won't be a pop-up for such errors.

Second problem seems to be similar to #16415

**Comment by eddiemuc** [comment]
Please don't collect different (wherigo-related) problems in same issue but create separate issues. Otherwise fixing is hard to track.

**Comment by eddiemuc** [comment]
Closing in favor of #16415
