### ISSUE TITLE
Permanent warning on map

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#16423]
### Describe your problem!

After updating c:geo to the latest nightly, a warning icon permanently appears on the map. And I have no idea what it wants to tell me.

### How to reproduce?

Open map

### Reproducible

Yes

### c:geo Version

2024.12.08-NB-89f5c8b

### Additional Information

![Screenshot_2024-12-08-10-36-52-533_cgeo geocaching_1](https://github.com/user-attachments/assets/ae636052-8329-44a4-9055-be16d92b6c08)

**Comment by moving-bits** [comment]
Fixed as part of #16419
