### ISSUE TITLE
Adaptive hill shading

### ISSUE THREAD

**Issue by devemux86** [cgeo/cgeo#16438]
### Tell us your idea!

A new adaptive hill shading algorithm was recently contributed to [Mapsforge](https://github.com/mapsforge/mapsforge) by @Sublimis.

### What solution would you suggest?

You can read more details and see the screenshots here:
- https://github.com/mapsforge/mapsforge/pull/1592

An example of its use can be found in [HillshadingMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/HillshadingMapViewer.java) sample.

**Comment by ztNFny** [comment]
I tested on 4 different zoom levels and on the smaller ones there's no observable performance impact, but zoomed out (viewport of about 80*135km) the loss in performance is significant (times are stopped using stopwatch, so not too accurate):
Without HS: 2,7s
StandardClasyHillShading: 4s
AdaptiveClasyHillShading(false): 4,1s
AdaptiveClasyHillShading(): 5,8s

**Comment by ztNFny** [comment]
also AdaptiveClasyHillShading hides the HS layer on zooming in for some reason I don't understand. AdaptiveClasyHillShading(false) hides it around zoom level 500m, AdaptiveClasyHillShading(true) around 200/100m. StandardClasyHillShading keeps it no matter the level.
Hiding the layer on zooming in is quite unexpected and very annoying, just this is a showstopper imho. This shouldn't be default behaviour of the default/recommended HS implementation.

**Comment by devemux86** [comment]
About the adaptive hillshading @Sublimis can answer better.

Hillshading algorithms (except adaptive) use the zoom levels of render themes.
All known render themes have:
```xml
<hillshading zoom-min="9" zoom-max="17" />
```

This can be overridden via code by `RenderThemeHandler.HILLSHADING_ZOOM_MIN` / `HILLSHADING_ZOOM_MAX`.

**Comment by ztNFny** [comment]
> Hillshading algorithms (except adaptive) use the zoom levels of render themes.

Well, with the same theme there's different behaviour depending on the implemenation used. In the Adapative code I'm seeing a max level 17 to which them some math is applied. But it definitily stops way before Standard (which i understand it's supposed to replace) does.

Need to look into the specific levels when I'm at my dev machine.

**Comment by ztNFny** [comment]
Did some more testing:
- Hiding of HS layer is independent of the map theme used
- couldn't figure out how to get the current zoom level easily, so am stating the last zoom level where HS is still visibile:
-- AdaptiveClasyHillShading(false): 500m
-- AdaptiveClasyHillShading(true): 200m
-- StandardClasyHillShading: 50m

Afaict this is because of this method of which the purpose I don't understand https://github.com/Sublimis/mapsforge/blob/54e50fdefd7731302e3933ecf0ee6762f4e25035/mapsforge-map/src/main/java/org/mapsforge/map/layer/hills/AdaptiveClasyHillShading.java#L132

**Comment by devemux86** [comment]
It's supposed to be with `AdaptiveClasyHillShading.setAdaptiveZoomEnabled`.

Then it should respect the hillshading zoom levels of the render theme (9-17).

**Comment by ztNFny** [comment]
.setAdaptiveZoomEnabled(false); / .setAdaptiveZoomEnabled(true); doesn't make a difference

**Comment by devemux86** [comment]
As a general rule:

- Hillshading algorithms should use the zoom levels of the render themes (e.g. 9-17)

- Adaptive hillshading should use all zoom levels, unless `setAdaptiveZoomEnabled(false)`

- Hillshading zoom levels can be overridden by `RenderThemeHandler.HILLSHADING_ZOOM...`

cc @Sublimis

**Comment by ztNFny** [comment]
In AdaptiveClasyHillShading getZoomMax() reduces the zoom level to 16 if HQ is not enabled and further to 15 depending on inputAxisLen.

Replacing that with a hardcoded 17 creates the same behavior as StandardClasyHillShading
    public int getZoomMax(HgtFileInfo hgtFileInfo) {
        return 17;
    }

**Comment by devemux86** [comment]
Testing easily with Mapsforge desktop samples where can check the zoom level:

- `StandardClasyHillShading` works correctly, it shows hillshading for zoom levels 9-17

- `setAdaptiveZoomEnabled(false)` displays the hillshading instead of zoom levels 9-17:
  - `AdaptiveClasyHillShading(true)` zoom levels 9-15
  - `AdaptiveClasyHillShading(false)` zoom levels 9-14

**Comment by ztNFny** [comment]
> * `setAdaptiveZoomEnabled(false)` displays the hillshading instead of zoom levels 9-17:

I get those results regardless of setAdaptiveZoomEnabled() - and that's the bug imho

**Comment by Sublimis** [comment]
> Did some more testing:
> 
>     * Hiding of HS layer is independent of the map theme used
> 
>     * couldn't figure out how to get the current zoom level easily, so am stating the last zoom level where HS is still visibile:
>       -- AdaptiveClasyHillShading(false): 500m
>       -- AdaptiveClasyHillShading(true): 200m
>       -- StandardClasyHillShading: 50m
> 
> 
> Afaict this is because of this method of which the purpose I don't understand https://github.com/Sublimis/mapsforge/blob/54e50fdefd7731302e3933ecf0ee6762f4e25035/mapsforge-map/src/main/java/org/mapsforge/map/layer/hills/AdaptiveClasyHillShading.java#L132

The purpose of limiting the maximum zoom level for hill shading is (probably) to prevent patches of gray overlay that have limited value at high zoom levels (when other types of details are sought) as shown in the screenshot below. The adaptive hill shading algorithm decides the maximum zoom level based on the input resolution of the HGT data (3" data will lower the maximum zoom level by 2 notches) and whether high resolution, i.e. bicubic upscaling, is enabled or not (using bicubic upscaling raises the maximum zoom level by 1 notch).

Limiting the hill shading zoom levels (anti)feature has been around forever, and when the adaptive algorithm was developed we just tried to follow that convention as much as was practical. If there were to be a debate about whether to remove the maximum zoom level limit, we would definitely vote for it! It might also be possible to make a compromise solution, in which the algorithm could gradually reduce the opacity of the hill shading as the zoom increases above maximum, for example.

![image](https://github.com/user-attachments/assets/d2861012-3210-401a-856e-7d5493ab89bb)

**Comment by Sublimis** [comment]
> .setAdaptiveZoomEnabled(false); / .setAdaptiveZoomEnabled(true); doesn't make a difference

If this doesn't make a difference, then you're probably using a 1" HGT data (kudos!) and `isHqEnabled=true`, so the max zoom level calculated by the algorithm is exactly the same as in the render theme (17).

**Comment by ztNFny** [comment]
> > .setAdaptiveZoomEnabled(false); / .setAdaptiveZoomEnabled(true); doesn't make a difference
> 
> If this doesn't make a difference, then you're probably using a 1" HGT data (kudos!) and `isHqEnabled=true`, so the max zoom level calculated by the algorithm is exactly the same as in the render theme (17).

No, I'm using 3". HQ makes a differnence of 1 level as described above - but both level 15 and 14 are way too early. It shouldn't be hidden before 17!

**Comment by Sublimis** [comment]
> > > .setAdaptiveZoomEnabled(false); / .setAdaptiveZoomEnabled(true); doesn't make a difference
> 
> No, I'm using 3". HQ makes a differnence of 1 level as described above - but both level 15 and 14 are way too early. It shouldn't be hidden before 17!

Can you share the code please, or explain in more details what exactly do you mean by the first statement above? We just tried `setAdaptiveZoomEnabled(false)` and `setAdaptiveZoomEnabled(true)` and it's working as expected... Something like:

```java
            final AdaptiveClasyHillShading algorithm = new AdaptiveClasyHillShading();
            algorithm.setAdaptiveZoomEnabled(false);
            MemoryCachingHgtReaderTileSource hillTileSource = new MemoryCachingHgtReaderTileSource(anyDems, algorithm, AndroidGraphicFactory.INSTANCE);
```

**Comment by ztNFny** [comment]
> > > > .setAdaptiveZoomEnabled(false); / .setAdaptiveZoomEnabled(true); doesn't make a difference
> > 
> > No, I'm using 3". HQ makes a differnence of 1 level as described above - but both level 15 and 14 are way too early. It shouldn't be hidden before 17!
> 
> Can you share the code please, or explain in more details what exactly do you mean by the first statement above? We just tried `setAdaptiveZoomEnabled(false)` and `setAdaptiveZoomEnabled(true)` and it's working as expected... Something like:
> 
> ```java
>             final AdaptiveClasyHillShading algorithm = new AdaptiveClasyHillShading();
>             algorithm.setAdaptiveZoomEnabled(false);
>             MemoryCachingHgtReaderTileSource hillTileSource = new MemoryCachingHgtReaderTileSource(anyDems, algorithm, AndroidGraphicFactory.INSTANCE);
> ```

What is "as expected"? I'm not seeing any difference at all with it set to true or false.

**Comment by Sublimis** [comment]
As expected = when `true` the algorithm decides zoom levels, when `false` the render theme decides zoom levels for hill shading. What's the value of `zoom-max` attribute of the `<hillshading>` tag in the render theme you use?

**Comment by ztNFny** [comment]
> As expected = when `true` the algorithm decides zoom levels, when `false` the render theme decides zoom levels for hill shading. What's the value of the `zoom-max` attribute of the `<hillshading>` tag in the render theme you use?

It's 17 or undefined for all themes i've ever encountered. Which explains why I'm not seeing any difference as I'm not testing with a custom theme.

**Comment by devemux86** [comment]
> when false the render theme decides zoom levels for hill shading.

@Sublimis I have not seen this. Please see my report above using the Mapsforge desktop samples:
- https://github.com/cgeo/cgeo/issues/16438#issuecomment-2558439766

**Comment by Sublimis** [comment]
> It's 17 or undefined for all themes i've ever encountered. Which explains why I'm not seeing any difference as I'm not testing with a custom theme.

Can you confirm that when using `setAdaptiveZoomEnabled(true)` the zoom level when hill shading disappears is 14/15, as opposed to 17 when using `setAdaptiveZoomEnabled(false)`? So at least we can stop calling this a bug and focus on other issues.

**Comment by devemux86** [comment]
@Sublimis The `setAdaptiveZoomEnabled` does not seem to work.
True or false, the zoom levels remain the same, 9-15 and 9-14.

**Comment by Sublimis** [comment]
> > when false the render theme decides zoom levels for hill shading.
> 
> @Sublimis I have not seen this. Please see my report above using the Mapsforge desktop samples:
> 
>     * [Adaptive hill shading #16438 (comment)](https://github.com/cgeo/cgeo/issues/16438#issuecomment-2558439766)

What do you mean? The above comment is okay, just the minimum zoom levels are not correct.

**Comment by ztNFny** [comment]
> > It's 17 or undefined for all themes i've ever encountered. Which explains why I'm not seeing any difference as I'm not testing with a custom theme.
> 
> Can you confirm that when using `setAdaptiveZoomEnabled(true)` the zoom level when hill shading disappears is 14/15, as opposed to 17 when using `setAdaptiveZoomEnabled(false)`? So at least we can stop calling this a bug and focus on other issues.

It always disappears at 14/15, no matter the adaptive setting! This is why i call it a bug.

**Comment by devemux86** [comment]
> the minimum zoom levels are not correct.

@Sublimis The render theme has hillshading zoom levels 9-17.
So the min zoom levels are correct. The max zoom levels are not correct.

**Comment by Sublimis** [comment]
> @Sublimis The `setAdaptiveZoomEnabled` does not seem to work. True or false, the zoom levels remain the same, 9-15 and 9-14.

Ok, I found the source of the problem. There should be another check of this flag, otherwise for e.g. 3" data and zoomLevel=16 it happens that the render theme allows hill shading (in `checkZoomLevelCoarse()`), but the algorithm still limits it later (in `checkZoomLevelFine`).

**Comment by devemux86** [comment]
@Sublimis To clarify, when `setAdaptiveZoomEnabled(false)`,
will the max zoom level be the theme max zoom, i.e. 17 regardless of `isHqEnabled`?

> What about those max zoom levels when the adaptive algorithm decides?

These are now 15/14 depending on the `isHqEnabled` for 3" dem files.

**Comment by ztNFny** [comment]
I'd ask for max level to be 17 with 3" files and HQ on/off - otherwise adaptive can't be a replacement for Standard.

**Comment by Sublimis** [comment]
> @Sublimis To clarify, when `setAdaptiveZoomEnabled(false)`, will the max zoom level be the theme max zoom, i.e. 17 regardless of `isHqEnabled`?

Yes, it was envisioned to behave that way, i.e. not to decide on zoom levels at all when `setAdaptiveZoomEnabled(false)` is used. One remark though, note that it could still *use* bicubic upscaling ("hq") if quality requirements dictate it at the zoom level allowed by the rendering theme (by quality requirements we mean matching the dpi of the device used). The point is that `isHqEnabled` doesn't actually have anything to do with zoom levels, except that it happens to be used while heuristically deciding on the maximum zoom level (it doesn't *have* to be used, but it makes sense to use it there).

> These are now 15/14 depending on the `isHqEnabled` for 3" dem files.

Yes, but should we increase this or perhaps remove the limit altogether (when the algorithm decides)? @ztNFny ?

**Comment by Sublimis** [comment]
> I'd ask for max level to be 17 with 3" files and HQ on/off - otherwise adaptive can't be a replacement for Standard.

So 18 for HQ on? Or 16 for HQ off? No one is actually forcing the adaptive algorithm on anyone, ultimately you use what works best for you, regardless of whether we end up changing the zoom levels on the adaptive algorithm or not. The standard algorithm will be slower on lower zoom levels, as it doesn't skip through data, though.

**Comment by devemux86** [comment]
@Sublimis Hillshading code must use the render theme hillshading zoom level limits.

There is a way to override then via `RenderThemeHandler.HILLSHADING_ZOOM...`.

**Comment by Sublimis** [comment]
> I tested on 4 different zoom levels and on the smaller ones there's no observable performance impact, but zoomed out (viewport of about 80*135km) the loss in performance is significant (times are stopped using stopwatch, so not too accurate): Without HS: 2,7s StandardClasyHillShading: 4s AdaptiveClasyHillShading(false): 4,1s AdaptiveClasyHillShading(): 5,8s

How does your dem folder looks like? Do you use ZIP files downloaded from mapsforge server (every HGT in its own ZIP ‡‡), or viewfinderpanoramas.org (several HGT files inside one ZIP ‡)? Or do you unzip HGT files (‡‡‡)?

‡‡‡ Fastest performance
‡‡ Moderate performance
‡ Slowest performance

**Comment by ztNFny** [comment]
> > I tested on 4 different zoom levels and on the smaller ones there's no observable performance impact, but zoomed out (viewport of about 80*135km) the loss in performance is significant (times are stopped using stopwatch, so not too accurate): Without HS: 2,7s StandardClasyHillShading: 4s AdaptiveClasyHillShading(false): 4,1s AdaptiveClasyHillShading(): 5,8s
> 
> How does your dem folder looks like? Do you use ZIP files downloaded from mapsforge server (every HGT in its own ZIP ‡‡), or viewfinderpanoramas.org (several HGT files inside one ZIP ‡)? Or do you unzip HGT files (‡‡‡)?
> 
> ‡‡‡ Fastest performance
> ‡‡ Moderate performance
> ‡ Slowest performance

Hgts are unzipped

**Comment by Sublimis** [comment]
> @Sublimis Hillshading code must use the render theme hillshading zoom level limits.
> 
> There is a way to override then via `RenderThemeHandler.HILLSHADING_ZOOM...`.

And it does use them, only for the adaptive algorithm one needs to call `setAdaptiveZoomEnabled(false)` first by default.
The original motivation for limiting the zoom levels for hill shading (especially the minimum zoom levels, by reading some old discussions) seems to be that it was both slow and ugly at low zoom levels (and it was), which is no longer the case. If anyone still thinks that's the case, it's easy to again force limit the zoom levels (if using the adaptive algorithm), as explained here. If the adaptive algorithm is not used, everything is the same as before anyway (but the performance benefits of the adaptive algorithm, both in memory usage and processing time, are given up).

**Comment by eddiemuc** [comment]
> > How does your dem folder looks like? Do you use ZIP files downloaded from mapsforge server (every HGT in its own ZIP ‡‡), or viewfinderpanoramas.org (several HGT files inside one ZIP ‡)? Or do you unzip HGT files (‡‡‡)?
> > 
> > ‡‡‡ Fastest performance
> > ‡‡ Moderate performance
> > ‡ Slowest performance
> 
> Hgts are unzipped

Performance might be impacted on Android due to low performance of opening files using SAF. This might lead to better performance when all HGTs are in one ZIP.

**Comment by Sublimis** [comment]
Let us explain the performance benefits of the adaptive algorithm in more detail.

\
Imagine you want to display hill shading at, say, zoom level 1, on a device screen that displays 12x12 pixels per degree of latitude/longitude at that particular zoom level, using 3" HGT files which contain 1200x1200 elevation points each.

### New (adaptive algorithm) way

* Read every 100th elevation point from every 100th line of the file, skipping the rest of the data. A hill shading bitmap of size 12x12=144 px (~bytes) is rendered from the read data and cached for eventual reuse. Scaling of the bitmap does not occur in this example (if scaling occurs, it is usually by a factor of less than 2, which also contributes to efficiency).


### Legacy way

* Read every single elevation point, whether it will be needed or not. A hill shading bitmap of size 1200x1200=1'440'000 px (~bytes) is rendered from the read data and stored in the cache for possible reuse. The bitmap must be scaled down from 1200x1200 px to 12x12 px to display on screen (!).

\
As you can see, the savings in memory usage and processing times are by a factor of about 10'000, assuming file skipping is implemented efficiently (which is usually the case when files are not compressed). And that's just for a single HGT file, you'll usually need many more.

\
The example may be considered somewhat simplified and extreme, but the principle is the same for all zoom levels, screen dpi, and HGT file sizes, only the benefit factor changes.

It's also possible to combine HGT files of different sizes to optimize benefits. For example, one could use 1" data for an important area and 3" data for the rest.

\
@eddiemuc Putting all HGTs in a single ZIP is not a good idea. ZIPs are not good for multithreading, so this would effectively make reading HGT files single-threaded, which would greatly impact performance. Putting each HGT in a separate ZIP in another story, as then each ZIP can be processed by a separate thread, for example.

**Comment by ztNFny** [comment]
> Let us explain the performance benefits of the adaptive algorithm in more detail.

Thanks for that explanation. The performance gain I'm not seeing in my tests (https://github.com/cgeo/cgeo/issues/16438#issuecomment-2557842910), however I guess that's because the min level is 9 and there it has too little impact to be noticable.
Is the performance impact of HQ on zoomed in levels as per your expactiation?

**Comment by Sublimis** [comment]
> Is the performance impact of HQ on zoomed in levels as per your expactiation?

What do you mean? There are some benchmark data here: https://github.com/mapsforge/mapsforge/pull/1561#issue-2627528245, does this help?

The performance impact of HQ vs. standard on multi-core devices is smaller than would be expected from the math alone, i.e. it is not 4x but much less, since the algorithm easily saturates even a CPU with many cores.

**Comment by ztNFny** [comment]
> > Is the performance impact of HQ on zoomed in levels as per your expactiation?
> 
> What do you mean? There are some benchmark data here: [mapsforge/mapsforge#1561 (comment)](https://github.com/mapsforge/mapsforge/pull/1561#issue-2627528245), does this help?

In my tests - see the link - HQ is about 50% slower with high zoom levels. This makes it way too slow for real world use imho. I was wondering whether that much of an impact is really expected.

**Comment by Sublimis** [comment]
Also note that at high zoom levels (just to be clear, this means zoomed in, not zoomed out), it usually only takes one HGT file to display the map in full**, and processing one HGT file happens quite quickly, in less than a second even for 1" data.

** Unless you happen to zoom right into the intersection of 4 HGT files.

**Comment by ztNFny** [comment]
> Also note that at high zoom levels (just to be clear, this means zoomed in, not zoomed out), it usually only takes one HGT file to display the map in full**, and processing one HGT file happens quite quickly, in less than a second even for 1" data.

That is clear. However reading your explanation above I was expecting that zoomed out (zoom level 9) should only read a few lines of each HGT, so rendering should be a lot faster. In my tests it's the same speed as Standard with HQ=false, with HQ=true it's ~50% slower. For zoom level 15 there's no measurable difference between HQ=true/false.
If that result is per your expectations all good, I was just trying to match it woith your explanation.

**Comment by Sublimis** [comment]
So yes, a factor of 1.5x slower is expected and quite impressive for an algorithm that has to process a bitmap that is 4x larger (and so does at least 4x more work, in reality more because the formulas are also more complicated). For the real world use you should test on as many devices as you can, and base your decisions and implementation configuration on data collected from those tests.

We have done our best to make the algorithm(s) as fast as possible, however we cannot anticipate every use case, nor do we claim that the HQ bicubic algorithm should run blazing fast on every device in existence; however, our testing shows that even moderate and/or old Android devices run it smoothly, and quite efficiently, especially with the 3" data.

**Comment by Sublimis** [comment]
> That is clear. However reading your explanation above I was expecting that zoomed out (zoom level 9) should only read a few lines of each HGT, so rendering should be a lot faster. In my tests it's the same speed as Standard with HQ=false, with HQ=true it's ~50% slower. For zoom level 15 there's no measurable difference between HQ=true/false. If that result is per your expectations all good, I was just trying to match it woith your explanation.

It really depends on the dpi of the screen. The decision on how much skipping will be done is almost entirely based on how many pixels there are per degree of latitude, which basically boils down to the dpi of the screen. The higher the dpi, the more processing will be done in either algorithm. HQ/bicubic upscaling is only triggered if the current resolution/dpi is such that one degree of latitude on the screen requires more pixels than the width of the HGT file (1200px for 3", 3600px for 1").

**Comment by Sublimis** [comment]
There was an idea to introduce another "quality factor" (but with a better name) that would allow control of dpi decisions behavior, and fine-tune the trade-off between performance and quality. For example, tell the algorithm to skip some data even when the pixels-per-latitude value match that of the screen. If you think it would be useful, we could consider it.

**Comment by ztNFny** [comment]
> There was an idea to introduce another "quality factor" (but with a better name) that would allow control of dpi decisions behavior, and fine-tune the trade-off between performance and quality. For example, tell the algorithm to skip some data even when the pixels-per-latitude value matches that of the screen. If you think it would be useful, we could consider it.

For me personally the main issue is performance at low (8-10) zoom levels. Zoomed in (e.g. 14) the amount of data is small enough that no performance hit from HS is noticable. If those lower levels could be further optimized that'd be greatly benefitial. However it's clear that they can never be as fast as with HS disabled due to the additional data loading and rendering required.

**Comment by ztNFny** [comment]
https://github.com/cgeo/cgeo/pull/16441 overrides the max zoom level bug/restriction in current mapsforge master and adds an user-facing option to enable HQ HS

**Comment by devemux86** [comment]
> It really depends on the dpi of the screen.

@Sublimis Shouldn't it depend on the map tile size?
Mapsforge adjusts the map tile size based on screen dpi.

**Comment by devemux86** [comment]
Mapsforge latest `master-SNAPSHOT` contains important map rendering performance and hill shading improvements.

**Comment by moving-bits** [comment]
> Mapsforge latest `master-SNAPSHOT` contains important map rendering performance and hill shading improvements.

Thanks for notifying us of those improvements and fixes. PR #16464 updates c:geo to current state of `master` branch of Mapsforge.

**Comment by ztNFny** [comment]
@Sublimis after merging https://github.com/mapsforge/mapsforge/pull/1605 getZoomMax() still returns 14/15 instead of the expected 17, I thought the PR was supposed to fix that???

**Comment by devemux86** [comment]
@ztNFny It should be https://github.com/mapsforge/mapsforge/pull/1597:

> Fix: `AdaptiveClasyHillShading.setAdaptiveZoomEnabled(false)` not entirely respected

**Comment by Sublimis** [comment]
> @Sublimis after merging [mapsforge/mapsforge#1605](https://github.com/mapsforge/mapsforge/pull/1605) getZoomMax() still returns 14/15 instead of the expected 17, I thought the PR was supposed to fix that??? (I've seen setZoomMaxOverride() but I understood from the discussion above the default would be changed)

We haven't understood it that way. Since it wasn't a bug there was nothing to "fix". There's nothing special about zoom level 17. If it works so well for you, it shouldn't be a problem to use `setZoomMaxOverride()`?

**Comment by ztNFny** [comment]
We haven't understood it that way. 

> As a general rule:
> 
> * Hillshading algorithms should use the zoom levels of the render themes (e.g. 9-17)
> * Adaptive hillshading should use all zoom levels, unless `setAdaptiveZoomEnabled(false)`
> * Hillshading zoom levels can be overridden by `RenderThemeHandler.HILLSHADING_ZOOM...`

I understood those points from @devemux86 should be the guideline, but these rules are not fulfilled even after https://github.com/mapsforge/mapsforge/pull/1605

* Default settings (setAdaptiveZoomEnabled(true)): HS stops at 14/15
* setAdaptiveZoomEnabled(false) shows it until level 17
* setZoomMaxOverride() allows setting it to a custom level

**Comment by ztNFny** [comment]
Also this one really suggests it should show until 17:

> @Sublimis Hillshading code must use the render theme hillshading zoom level limits.
> 
> There is a way to override them via `RenderThemeHandler.HILLSHADING_ZOOM...`.

**Comment by devemux86** [comment]
> Hillshading algorithms should use the zoom levels of the render themes

Adaptive hill shading is probably an exception, because it is "adaptive".
Unless using the `setAdaptiveZoomEnabled(false)` to work like the others.

**Comment by ztNFny** [comment]
> > Hillshading algorithms should use the zoom levels of the render themes
> 
> Adaptive hill shading is probably an exception, because it is "adaptive".
> Unless using the `setAdaptiveZoomEnabled(false)` to work like the others.

It's a hillshading *algorithm*, I would expect the adaptive part to be about the algorithm, so about the way HS display is calculated - not about the way it's applied. Imho isAdaptiveZoomEnabled(true) as default is a bug

**Comment by Sublimis** [comment]
Much fuss about nothing. @ztNFny No one is forcing you to use the adaptive algorithm. You are welcome to make your own better one, subclass, or use the legacy Diffuse one and enjoy the performance and the features you like.

**Comment by ztNFny** [comment]
@Sublimis as mentioned above the workarounds are clear and already implemented.

However this is something that everyone implementing that class - which was mentioned as the recommended standard class - needs to figure out again and again. There were some rules stated by @devemux86 that i understood should be general. If that understand it's false ok, but then it should be clearly documented how and why it behaves that way, otherwise the question why HS disappears that early will come up again and again - or that implementation simply not be used as it shows "broken" behaviour by violating above rules.
Behaving - by default - completely different than all other implementations is, if you don't want to call it a bug, at least very very unexpected.

**Comment by Sublimis** [comment]
Simply put, years of neglecting hill shading are now taking their toll. From 2017 to 2024, there was basically only one not-so-good algorithm available, and people realized that hill shading was slow and/or ugly, with no prospect of any improvement, so the only simple solution was to limit zoom levels. This paradigm needs to go.

Yes, it’s time to learn that hill shading is much more than the legacy Diffuse algorithm.

**Comment by Sublimis** [comment]
Why limit the maximum zoom level at all, have you ever wondered? Why stop at 17? AFAIC, the maximum zoom level shouldn't be limited at all. But then someone will shout: "Hey! Since 2017 there was a zoom level where hill shading disappeared, why not anymore???" 🤦 🙂

**Comment by ztNFny** [comment]
I very much appreciate your work on a better HS rendering - which is why i want to adopt it. However i fail to understand how that statement is related to the above discussion on which zoom level the HS layer is hidden. 
Right now with the default settings - which should be sensible, fitting for most purposes - the HS layer disappears before the user can really recognize anything on the map, thus making it quite useless.

**Comment by ztNFny** [comment]
> Why limit the maximum zoom level at all, have you ever wondered? Why stop at 17? AFAIC, the maximum zoom level shouldn't be limited at all. But then someone will shout: "Hey! Since 2017 there was a zoom level where hill shading disappeared, why not anymore???" 🤦 🙂 

Yes, why limit it at all?
If your implementation wouldn't hide it at all I wouldn't see any problem with that.
But right now the limit is a very small level - 14 - at which you can't make out any details yet. For hiking, skiing, ... zoom level 14 is not very useful.

That's why I'm saying it should stay longer - if it stays on all levels, perfectly fine.

**Comment by Sublimis** [comment]
> thus making it quite useless.

*for you. Please use 1" HGT files for more detail at high zoom levels, or any of the easy-to-implement foolproof methods provided by the algorithm itself.

**Comment by Sublimis** [comment]
> Yes, why limit it at all? If your implementation wouldn't hide it at all I wouldn't see any problem with that. But right now the limit is a very small level - 14 - at which you can't make out any details yet. For hiking, skiing, ... zoom level 14 is not very useful.

The reason was already mentioned [above](https://github.com/cgeo/cgeo/issues/16438#issuecomment-2558501301):

> Limiting the hill shading zoom levels (anti)feature has been around forever, and when the adaptive algorithm was developed we just tried to follow that convention as much as was practical. If there were to be a debate about whether to remove the maximum zoom level limit, we would definitely vote for it! It might also be possible to make a compromise solution, in which the algorithm could gradually reduce the opacity of the hill shading as the zoom increases above maximum, for example.

**Comment by fm-sys** [comment]
+1 for removing the limit totally (by default)

**Comment by ztNFny** [comment]
> Limiting the hill shading zoom levels (anti)feature has been around forever, and when the adaptive algorithm was developed we just tried to follow that convention as much as was practical.

So you actually think "there should be no limit" but instead of removing the limit or using the "convention" limit you introduced a new, arbitray, way lower limit of 14? Sorry, that doesn't make any sense at all...

> Please use 1" HGT files for more detail at high zoom levels

1" vs 3" adresses a completly different issue and is unrelated. 3" data quality is good enough for most hiking usecases. However at the default max level 14 the map is zoomed out so far that a lot of hiking relevant info is not yet usable.
So *with default settings* the user can either have a usable hiking map or hillshading data, but not both.
You're "forcing" everything implementing that algorithm to overwrite the default with sensible values, making it harder than neccessary to adopt it. But defaults should be sensible - that's the whole point of defaults.

**Comment by Sublimis** [comment]
> So you actually think "there should be no limit" but instead of removing the limit or using the "convention" limit you did the opposite by reducing the limit to a new, arbitray, way lower limit of 14? Sorry, that doesn't make any sense at all...

It's 17 for 1" files, and 15 for 3" files by default, please don't manipulate the facts. And it's not "the opposite". The zoom level was already hard-limited, so this hard limit was relaxed in a more advanced way now that the algorithm has better knowledge of the quality of the input files than the person who wrote the render theme (which is universal for all HGT files, 1", 3", or the 15" ones). Yes, the priority was appearance, not preserving the hard-limited maximum zoom value that was introduced for **appearance** in the first place!

> 1" vs 3" adresses a completly different issue and is unrelated. 3" data quality is good enough for most hiking usecases. However at the default max level 14 the map is zoomed out so far that a lot of hiking relevant info is not yet usable. So _with default settings_ the user can either have a usable hiking map or hillshading data, but not both. You're "forcing" everything implementing that algorithm to overwrite the default with sensible values, making it harder than neccessary to adopt it. But defaults should be sensible - that's the whole point of defaults.

You update a library to a new version. You notice that there are some changes (it's a new version, duh). You try it out. You don't care about the fancy new features. So you adjust the thing to behave like before, because it's possible.

This is how it usually works. You can't really expect anything to ever change.

**Comment by Sublimis** [comment]
And yes, the hill shading (including zoom 17) hasn't changed since 2017, but that's not because it was such a good implementation, but because no one cared enough to improve it...

**Comment by ztNFny** [comment]
> so this hard limit was relaxed

Going from 9-17 to 9-14 / 9-15 is NOT relaxing but REINFORCING the hard limit - that's 100% the meaning of the word OPPOSITE. I doubt anyone would speak up if it was relaxed.

As you're apparently not open to reevaluate the default values to make them more sensible I'll stop trying to give my arguments now.
https://github.com/cgeo/cgeo/pull/16467 removes the max limit for the implementation in c:geo now, setting it to "theme minimum"/9-20 (which is usually the max zoom level maps allow). Thanks for your improvements to the hillshading algorithm that at least allows parameterizing it in a sensible way.

**Comment by Sublimis** [comment]
See, your only argument was "I want things the way they were before without lifting a finger". Not giving screenshots or anything and manipulating facts. You can open a discussion (you don't have to do it *right now*) on mapsforge to expand the visibility of this "problem" so everyone can give their opinion. The current code is not a be-all-end-all implementation, you know.

**Comment by SammysHP** [comment]
Please keep this a respectful discussion. I think both sides have described their standpoint, now it's time for [mapsforge](https://github.com/mapsforge/mapsforge) (@devemux86) to find a consensus for sensible defaults.

If someone likes to open a discussion/issue there, I'll add my opinion about it there.

**Comment by ztNFny** [comment]
> "I want things the way they were before without lifting a finger"

Very very far from it. As stated a plethora of times I had already implemented a custom class in c:geo to work around the - in my eyes - unreasonable defaults.
I was suggesting to you to make the DEFAULTS more reasonable and thereby improving the implementation. If I had wanted everything to stay the same I wouldn't have adopted the class. However I think a new implementation should not be *worse* than the previous one - so *at least* zoom level 17.

> manipulating facts

I never manipulated anything. Fact is, 3" disappears at 14 without HQ and 15 with HQ (per https://github.com/cgeo/cgeo/issues/16438#issuecomment-2558506338), but HQ is very slow (per https://github.com/cgeo/cgeo/issues/16438#issuecomment-2558647277) and thus 14 is the relevant number.
I didn't re-state all those points again and again in every comment - but you've been part of the discussion, so I didn't think I'd have to repeat everything already said for you to know it.

**Comment by SammysHP** [comment]
See https://github.com/mapsforge/mapsforge/issues/1606 for a follow-up of this discussion.
