### ISSUE TITLE
wrong layer order on Unified MF

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16435]
Circles are drawn on top of cache icons
![image](https://github.com/user-attachments/assets/feb1bd47-784a-4ecf-b876-0cf50550e38d)

**Comment by moving-bits** [comment]
This also applies to lines, eg. "history track" etc.

And if I set zLayer level for position marker and elevation info to a value lower than cache marker (in code), they still get drawn on top of geocaches.

Seems that zlevel ordering of UnifiedMap Mapsforge is still mostly broken.

Reproducible for me with both current release 2024.12.01 and current state of `master`.

@eddiemuc 
Could you have a look at it (as time permits)? Thanks.

**Comment by eddiemuc** [comment]
Mapforge layer can currently not handle zLevels across different layers, and is sensitive to order of adding layers. Current implementation adds layer for "clickable" things before adding layer for "non-clickable" things. This leads to all "non-clickable" things be drawn on top of "clickable" things. PR #16454 reverses that order.

Is this enough? E.g. are all "non-clickable" things always under "clickable" things in the map? If not a more in-depth fix needs to be done.

**Comment by ztNFny** [comment]
> Is this enough? E.g. are all "non-clickable" things always under "clickable" things in the map? If not a more in-depth fix needs to be done.

I remember for VTM doing a lot of detailed "which layer goes on to of which" stuff, so i doubt a 2-layer approach will be sufficient.

**Comment by eddiemuc** [comment]
ok then it takes a little more effort...
I will take care of it

**Comment by eddiemuc** [comment]
PR #16455 redesigns mapsforge layer to be zlevel aware across layers

**Comment by eddiemuc** [comment]
@devemux86 Tom fix this issue I created class https://github.com/cgeo/cgeo/blob/release/main%2Fsrc%2Fmain%2Fjava%2Fcgeo%2Fgeocaching%2Funifiedmap%2Fgeoitemlayer%2FMapsforgeV6ZLevelGroupLayer.java

This is a group layer which is aware of z Levels of contained child layers. Would you be interested in having such a class (in a cleaned up format) inside mapsforge library?

**Comment by devemux86** [comment]
> Would you be interested in having such a class (in a cleaned up format) inside mapsforge library?

@eddiemuc Sure, we can include it.

Please add some documentation, so users can understand the parameters and how to use it.
Also the levels order: is level 1 above or below level 2.
