### ISSUE TITLE
wrong date in history after online log

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#1657]
Yesterday I did an offline log.today I did an online log for the same cache with the date of yesterday.that changed the history.while it was correctly shown yesterday before the online log, it is now shown with the date of today.

**Comment by pstorch** [comment]
I think this is resolved in the meantime. I saved some offline logs yesterday and made a real log today. The sort order in history was not changed. 
Can someone double check?

**Comment by Lineflyer** [comment]
Doublechecked. Seems OK to me as well.
