### ISSUE TITLE
Double tap (zoom in) opens cache pop-up as well

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#1688]
If I double-tap on the map to zoom in, the cache-popup opens if I happen to hit a cache with this double-tap as well.
Tested with OSM and Google on 0034e35866 (current release build)

**Comment by Lineflyer** [comment]
I retested this and from the practical experience I don't have a problem to zom in by doubletap without in parallel opening the popup (tested with mapsforge beta on 2017.02.12-NB)
