### ISSUE TITLE
Caches may be not be loaded on map - without any UI indication of failure, when on a flaky connection

### ISSUE THREAD

**Issue by ikajaste** [cgeo/cgeo#1697]
When I open the live map or move it to a new area, c:geo starts loading all the caches available on the visible area. There is a spinner to indicate it's still loading caches, and that the map doesn't show all the caches yet.

However, if the connection is flaky (which mobile data connections sometimes are) the request for caches may fail and the spinner stops, just like it would if request had been completed. This causes a problem on an area where there are few caches around (and those areas probably correlate with somewhat remoter areas that may have a flaky mobile data connection).

**The user may be left looking at a map empty of caches without knowing if 1) the visible map area is fully loaded and there just are no caches on the area, or 2) if the connection failed and there would indeed be caches in the area.**

_One possible solution:_ When the connection fails, instead of disappearing the spinner would turn into a red "refresh" icon that could be used to retry the retrieval.

_Another possible solution:_ All map area where caches haven't yet been retrieved succesfully is overlaid with some sort of slightly red colour, to indicate the area isn't "ready" yet. This could however be distracting when browsing already stored caches, so it would have to be easily toggleable off from the quick option menu.

**Comment by Lineflyer** [comment]
Lets close this as outdated for the moment. After #7514 was merged the live map loading generally changed, which does not mean, that this problem is gone but maybe have other manifestation or solution possibilities.
