### ISSUE TITLE
Integrate ACRA for better error reporting

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#1732]
[ACRA](https://code.google.com/p/acra/) would let us share crash reports with the whole team in a Google Docs, and may be extended to include more information than what is currently available in the Google Play interface.

**Comment by Lineflyer** [comment]
@samueltardieu Is the mentioned tool still available and useful for us?

**Comment by Lineflyer** [comment]
This has been kind of solved by the ability for the user to export logs directly.
