### ISSUE TITLE
Support "Ignore Listing"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#1750]
It would be useful if c:geo would support "Ignore Listing".
Some cachers use this features to hide out caches they are not able to do (e.g. T5) from search results.

Currently the search already does not show caches which are on the ignore list, it should additionally be possible to add caches to the ignore list.

**Comment by Lineflyer** [comment]
@Bananeweizen  You recently implemented this. Correct?

**Comment by Bananeweizen** [comment]
Yes. The user interface needs to be improved, but the general functionality for ignoring a cache is working now.
