### ISSUE TITLE
field notes are not stored in cgeo directory

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#1764]
I used field notes for the first time now and I found that we store them in a separate directory below the root, instead of using our cgeo directory. I favor having all our files in one directory, so it is easier for the app and the user to clean up.

**Comment by Lineflyer** [comment]
I would like to put all of these discussions (#3950, #706 and others) into a new issue dealing with the overall file structure of c:geo. We surely have to find a solution for the offline cache (/.cgeo) but IMO as well include those random dirs we are using (e.g. /field-notes / GPX) into that discussion.

A lot of the discussion in those issues was about the right strategy and -even more important- about a migration strategy from the current to a possible new strategy.

Independently of whether there is someone willing to implement this, I would like to ask if you agree with starting from scratch and at first outlining the current situation and our target and afterwards define the ways towards it in a new issue.
The example from Locus posted in https://github.com/cgeo/cgeo/issues/3950#issuecomment-67784999 seems like a very good option also for c:geo.

Feedback?
