### ISSUE TITLE
Allow to import caches from Bookmark-list

### ISSUE THREAD

**Issue by pilhuhn** [cgeo/cgeo#1765]
To prepare for seeking abroad, I add stuff to a bookmark list on the gc.com web site. It would be good if I could import the caches from the list into c:geo. Import could have a checkmark "full fetch" that would make c:geo not only fetch the GC codes from the bookmarks and store them as saved caches, but would also fetch the full details (and perhaps even a map snippet).

**Comment by frodeseverin** [comment]
Now, for us freebies, it would also be possible to use
http://www.gpsvisualizer.com/
to convert a .LOC file to .GPX
