### ISSUE TITLE
Can we support trekbuddy tarred atlas offline map format ?

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#1789]
Sometimes it could be very convenient, when caches could be displayed on hiking maps (here in czech and slovakia we have realy precies maps provided by army ... today sold by shocart company). Theese maps are easy to obtain by mobile atlas creator (and there are many sources of raster maps available all over the world).

Is it possible to implement using new offline map type ? I'had searched for android project that could display this type of maps ... and they are mostly closed-source freeware, but format of maps is documented.

**Comment by samueltardieu** [comment]
Closing as the standard way of communicating directions to another Android application is standard.
