### ISSUE TITLE
remove self made input dialogs

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#1791]
There have been additions to the code which use self made dialogs just for very small input (using a text view or checkboxes and so on). Those dialogs don't fit the remaining visual appearance and are not the recommended way of implementing this in Android. Instead we should use an alert builder with a custom view:

http://developer.android.com/reference/android/app/AlertDialog.html#setView(android.view.View, int, int, int, int)
http://stackoverflow.com/questions/9763643/how-to-add-a-check-box-to-an-alert-dialog

**Comment by Lineflyer** [comment]
@Bananeweizen Do we still have those custom dialogs somewhere?

**Comment by Bananeweizen** [comment]
Seems that all dialogs are now replaced by DialogFragments or AlertDialogs. Closing.
