### ISSUE TITLE
include ohloh widget on web page

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#1795]
I suggest to include an ohloh widget on the cgeo home page. I always find that a good way of attracting potential new contributors to a project, if I see it on a web page of another project. It also allows outside people to "judge" the project a little bit (e.g. we currently list 49 contributors which is huge!)
I suggest to use the last one on this page: https://www.ohloh.net/p/cgeo2/widgets

Any comments?

**Comment by Lineflyer** [comment]
Moved to https://github.com/cgeo/cgeo.github.io/issues/22
