### ISSUE TITLE
"Last found" date on detail-view

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#1801]
From support mail:

Would be very happy if it was possible to see the date when a cache was last found already in the information page, just below hidden date.

**Comment by kumy** [comment]
From @mjarmstr in #5230 

>My normal mode of operation for using c:geo is as follows:
- Use the map to find my area of interest.
- Scale the map to select an appropriate number of caches and store offline.  
- Peruse the list for caches to target.
  - Open the cache details
  - Go to the logs and look at the recent ones to see when it was last found

>This is because where I live it isn't uncommon for a cache to go unfound for months and often the last years worth of logs are DNFs and/or needs maintenance.  I usually will just skip these.  It would be nice to have some sort of indication on the list page and/or the first details page of the last time cache was found and/or what the type of the last few logs are.  

>My initial spit-ball of an implementation would be to have a colored/dashed line duplicating the colors from the last few log entries on the list page, one log per dash.  Then that could be duplicated along with a last found date on the details page.

**Comment by mjarmstr** [comment]
Just another data point on this one.  The new app from geocaching.com apparently puts and exclamation point next to the cache name of the last log was a DNF.  Would be a minimally intrusive yet useful UI enhancement.

**Comment by samueltardieu** [comment]
Add screenshot from Locus Map Pro.

![screenshot_20160803-142018](https://cloud.githubusercontent.com/assets/44656/17400539/cf198f98-5a48-11e6-9bbf-649218486c81.png)

**Comment by rsudev** [comment]
This is for stored caches, right? (otherwise we don't have the information, I guess). We might also want to check how fresh the information is before showing (I sometimes have caches on my device which I updated 100+ days ago last time)

**Comment by fm-sys** [comment]
With #11676, the latest offline logs will be displayed as icons in cache details and map popup. Let's close here...
