### ISSUE TITLE
Update web site

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#1857]
The web site needs to be updated:

- a link to the Google+ page should be added, with icons similar to Facebook and Twitter (do we have the templates?)
- a link to the status page should be added
- the reference to the "partner app" GCC should be removed, there isn't even a backlink to c:geo

**Comment by Lineflyer** [comment]
Moving to dedicated issues in https://github.com/cgeo/cgeo.github.io/issues/
