### ISSUE TITLE
Ordnance Survey maps for the UK

### ISSUE THREAD

**Issue by smmudge** [cgeo/cgeo#1869]
A feature request, if possible. The Ordnance Survey (OS) have made their maps available for online usage now and these are particularly helpful in the UK. When you have a spare moment (;-) would it be possible to include these as one of the map types please? Keep up the great work you are doing. Thanks.

**Comment by Lineflyer** [comment]
MIght be followed up in #6641 if technically possible to use this in a configurable tile downloader.
