### ISSUE TITLE
Cyclestreets.net maps

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#1890]
One from support. I don't know this app and if it's possible

It would be helpful if I could use the maps produced by Cyclestreets.net to tie in with c:geo.
This is especially as they have made an offline UK Map Pack available as an Android app.

Unfortunately, when I am using c:geo, the map pack doesn't appear under the list of available options.
Can you advise how I can integrate the two?

**Comment by Lineflyer** [comment]
Might be followed up in #6641 if technically possible to use this in a configurable tile downloader.
