### ISSUE TITLE
Updating cache using send2cgeo does not update coords

### ISSUE THREAD

**Issue by speedy-1702** [cgeo/cgeo#1894]
When correcting the coords at gc.com and then using the send2c:geo everything works fine.
But, when the already in c:geo stored cache gets corrected at gc.com and then again using send2c:geo the coords in c:geo are not being updated.
You have to push update to do this.
Is this a bug?

Edit Lineflyer: Topic changed

**Comment by Lineflyer** [comment]
A retest with 2015.01.01-NB2 showed that this is bug is no longer existing:
- Have a stored multi
- Enter corrected coords on gc.com website
- User send2geo to (re)transmit it to c:geo

Opening the cache afterwards shows it have the corrected coords in the listing in cgeo.
