### ISSUE TITLE
Formula solver for multi

### ISSUE THREAD

**Issue by ludoo0d0a** [cgeo/cgeo#1941]
Would it possible to implement a such feature based on GCBuddy app : http://www.btstsoft.nl/apps/gcbuddy/ ?

I already had this idea a few months ago and did something on javascript. It works perfectly for me but it is not usable on a mobile device :(

Here are the required steps (from my own point of view) :
- add 1 field "formula" in waypoint
- add a page for each cache to enter values (A,B,C) and a "compute" coordinates button.

User enter values as soon as he gets a new value during the hike.
Click "generates" button calculates new coord values for child waypoints with formula (if all required values are present).

Technically, javax.script.ScriptEngineManager (or JEXL) could manage eval job.

From my experience, user should input himself the formula because extract formula from text's cache is really hard.
Used format is not always the same. (x or \* for multiplication, ( or [ for input...)

**Comment by Lineflyer** [comment]
Although this is closed...maybe someone is still interested in implementing something like this (received as a request via support mail):

Locus Solver Addon:
https://plus.google.com/communities/113063786196810493588
