### ISSUE TITLE
Send2cgeo clean queue

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#1985]
Hi,

today I had realised that it will be great when send2cgeo could be able to clean queue, by  "magic button". I have two testing phones. And I had sent about hundred of caches via send2cgeo to one of them some time ago (about 4 days). When clicking import from web on the other one phone ... it was downloading the same hundred of caches and after them new added caches. There should be a possibility to clean that queue, because it is really time consument and sometimes uneccessarry to download caches to all users phones.

How this should be solved ? And how send2cgeo works ? What is the structure of queue storage ?

**Comment by Lineflyer** [comment]
This issue was moved to cgeo/send2cgeo#11
