### ISSUE TITLE
Data service

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#2068]
This is related to #330, but I think it is better to discuss my draft in a new issue to keep the other one clean.

![Draft](http://i.imgur.com/PIz2b.png)

**Comment by Lineflyer** [comment]
@SammysHP 
@samueltardieu 

IMHO this is a quite generic issue. I see references to RxJava which has been implemented meanwhile.
Shall we keep this issue open?

**Comment by samueltardieu** [comment]
You can close it.

**Comment by SammysHP** [comment]
Btw: I just thought about how annoying it is to press "store" on the map and then wait until the cache is stored. Would love to have this in the background. :)

**Comment by okainov** [comment]
Was there any update on the implementation for this? Still would be really nice to have this functionality
