### ISSUE TITLE
remember logging date for next logs

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2071]
If you want to log multiple caches, the date is initially set to "today" for each of those caches. That's annoying when logging a cache series for yesterday or any other day than today. It might be more convenient to remember the logging date (similar to how the website does it).

If this is implemented, we somehow need to invalidate the remembered date also, because an Android app might live for very long times (and therefore could remember this date for weeks).

**Comment by SammysHP** [comment]
I just thought that I found another bug while logging caches from the m yesterday. For every log I had to change the date again and I was absolutely sure that c:geo is able to remember the date during a "session".

**Comment by Lineflyer** [comment]
Closing in favor of #11890 as this has recent discussions about possible implementations
