### ISSUE TITLE
Use API 17 for building and as target

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2083]
During a chat session we agreed to make our app target level 17. Necessary changes are at least:

- [ ] change target version in manifest
- [ ] select correct build target at each developer
- [ ] Android support library latest version
- [ ] Indicator library latest version
- [ ] Deprecated API must go into the compatibility classes
- [ ] exceptions thrown if using network on the UI thread
- [ ] new permission http://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE
- [ ] optional: use http://developer.android.com/reference/android/net/ConnectivityManager.html#isActiveNetworkMetered()

**Comment by Lineflyer** [comment]
@Bananeweizen 
I do see that we know use `android:targetSdkVersion="21"` so I think this can be closed?

**Comment by SammysHP** [comment]
Yep.
