### ISSUE TITLE
Parcel state of search list to avoid re-search on coming back from details

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#2100]
On devices with tight memory the list activity of an online search may be thrown out of memory when opening details from it. On coming back from details the same search is done again which takes time and causes unwanted extra traffic, especially on 3G.
If the list state (cache codes) was properly parceled this would be unnecessary.

**Comment by fm-sys** [comment]
> avoid re-search on coming back from details

This is no longer happening in our current version. Probably, much has changed since 2012...
