### ISSUE TITLE
Upload 32x32 logo on website for use in send2cgeo

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2116]
Greasemonkey scripts can have an icon. We currently use the high resolution image of the send2cgeo website which looks not that well in the addons list. Therefore we should have a 32x32 logo somewhere on the server and afterwards have the script point to that new image.

**Comment by Lineflyer** [comment]
@mucek4 Reminder ;)

**Comment by Lineflyer** [comment]
This issue was moved to cgeo/send2cgeo#10
