### ISSUE TITLE
Font problem 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2119]
Since some weeks I have a strange problem with the nightly builds:
On my SGS2 it is supported to replace the default font by a custom user font. I did this a long time ago and installed a quite thin font to save space on the display. 

All apps including c:geo used to use this font without problems.
Since some weeks I do only see the device default font instead of the custom font throughout c:geo.
Only on the first start of c:geo after a device restart the custom font is used.

Any idea or might this be a system bug (as I also did a upgrade from 4.0.3 to 4.0.4). But in fact c:geo is the only app which has this problem on my device.

**Comment by akkatracker** [comment]
Can anyone confirm whether this still happens?

**Comment by Lineflyer** [comment]
I did not see this bug again since I changed my device to another model. I therefore consider this a device specific bug (or it was implicitly fixed meanwhile).
Feel free to reopen if you have other clues on that.
