### ISSUE TITLE
Clear/Optimize Database

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#212]
I noticed something: I stored 1000 caches from a gpx, the database was ~3.5 MB large. Then I deleted all caches (btw: takes a lot of time, see other issue) and the database-size was the same. Is there an optimize-command like in MySQL or is the data cached like caches that you have opened sometime?

**Comment by Lineflyer** [comment]
The foreign key idea is covered by #6227. How about the vacuum. AFAIR we tried to implement it some time ago not knowing, that we breach the minsdk (some devices did not support that). No we have 4.0 minimum for `master`. Does this change anything or is this issue anyway outdated?
