### ISSUE TITLE
Set current position (in absence of GPS)

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#2139]
It is perhaps related to #1039 but has a different angle IMHO (and I could not find a similar request).
Just recently there was a question on geoclub if it is possible to set your 'current' or 'home' coordinates in c:geo. While the latter is discussed in #1039 I think the former would be a useful feature especially when without GPS (either no signal indoors or switched off). I f we allow to enter (or better select on the map) the current location, everything (like cache distances, nearby search, etc.) could be displayed in relation to that.
Edit: corrected referenced issue (typo)

**Comment by samueltardieu** [comment]
We now retrieve the home position from geocaching.com.
