### ISSUE TITLE
Include some basic custom themes into c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2187]
As discussed on IRC:
Making it easier to use the advantages which come with custom themes for mapsforge maps we should think about including some basic themes in c:geo.
This could include a theme suitable for usage at night (e.g. red style) and others.

There are tow possible ways:
1. Making our own themes 
2. Get some theme with appropriate license and include it

Currently some users (e.g. on locus forums) build their own themes.
Maybe it is possible to find a user willing to participate here / share his theme for usage in c:geo.

Link:
http://forum.locusmap.eu/viewtopic.php?f=40&t=1753#p11534

**Comment by andrixnet** [comment]
subscribe

**Comment by SammysHP** [comment]
@andrixnet You can subscribe to issues using the button in the sidebar. Please don't comment on issues just to get notifications.

![20161102_191135](https://cloud.githubusercontent.com/assets/922874/19941382/2fc31548-a130-11e6-8176-7a7717975fbd.png)

**Comment by moving-bits** [comment]
Mapsforge maps come with a decent built-in default theme, and many other map providers need their individual theme anyway, as there is a relation between info included in the map file and theming instructions.

Therefore I don't think we should implement any map themes on our own and propose to close this issue.

**Comment by fm-sys** [comment]
> Therefore I don't think we should implement any map themes on our own and propose to close this issue.

@moving-bits last comment got +3 up votes, so let's close the issue.

We meanwhile also offer themes via our downloader...
