### ISSUE TITLE
Support Proxy

### ISSUE THREAD

**Issue by RobinAllen** [cgeo/cgeo#2249]
HTC One X / Android 4.0.x

Reading my gmail, I see a published cache notification.

I click the link in the email - http://coord.info/GC4xxxx.
What do you want to complete this action with - cgeo, chrome, etc - I choose cgeo
cgeo spins for a while on 'Loading cache details'
Error 'cgeo failed to download the cache.  Unknown communication error'

Same result if I try to load the cache using the GC code in the 'Search' tool.

Live map with 'live' enabled also doesn't display the cache.

Hmmm. I'm going to struggle to FTF this one if cgeo won't load it. I add a waypoint manually and hop in the car.  I got it ten minutes after publication.  Job done ;-) 

Now I'm trying again back at the office later on to see why I couldn't download it.  This is on wi-fi with manual proxy settings.  My proxy server logs show no connection attempts being made by my android. It's like cgeo isn't going through the proxy properly. 

Normal browser pages load fine in chrome or in other browsers on my android.  My gmail loads fine over the wifi.  But cgeo? Nope.

I'm about 85% sure this used to work on the office wifi with the proxy, but I could be wrong.  Either way, it ought to work fine through a proxy.  I have full access to the company proxy server, so I know what is/isn't being blocked at the proxy level; I can see no evidence of cgeo even connecting to the proxy.

Is cgeo using the wifi proxy settings properly?

**Comment by Lineflyer** [comment]
There was no other request or report by users in th past 3 years that would need a proxy configurable for c:geo. Closing as "not needed". Feel free to reopen if you disagree,.
