### ISSUE TITLE
Confusing by different DirChooser dialog

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#2257]
Left from #2208

If there is nothing inside the text field, the selection leads to the FileChooser introduced by @Bananeweizen .
(attention: after deleting contents of this field change to another field first to set value)
If the directory is set, my implementation of SimpleDirChooser is used.

This behaviour with NB could confuse the user.

**Comment by Lineflyer** [comment]
As I stumbled upon this while makeing the offline map tutorial, I will summarize the current situation in a new issue instead of using this well outdated one.
