### ISSUE TITLE
Add option to keep GPS active while screen locked

### ISSUE THREAD

**Issue by twouters** [cgeo/cgeo#2262]
There have been a lot of requests to disable GPS when it's not needed, to save battery.
I would like to request the opposite, I don't mind if my battery is drained by the GPS function but I do mind having to wait 2 minutes (exaggerated) for a new GPS fix.
I've got a habbit of quickly checking my location and then locking the screen and putting the device in my pocket. This action takes a lot more time if GPS is being disabled as soon as e.g. the screen is locked.

**Comment by Lineflyer** [comment]
Continued in #4575.
