### ISSUE TITLE
Make website editable

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2270]
Looking at the many recent comments on website related issues, I feel it would make sense to make it possible for every c:geo team member to edit the website sources. I don't demand that everyone can publish them on the server, but just editing the files (and having them published regularly by mucek4) would be helpful as some issues related to the website are lying around for a long time already.

As I don't exactly know what is used to generate the site, I can't really say if it makes sense to host the files directly as yet another repository under the c:geo github account.

**Comment by SammysHP** [comment]
*push*

We should really try the GitHub Pages approach. I think once we have the design ("a" design, because there is much room for improving the current one) the content should be really easy.

We can use cgeo.org instead of cgeo.github.io.

**Comment by Lineflyer** [comment]
DONE! :-)
