### ISSUE TITLE
Allow direct logging of PM-only caches also for basic members

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2288]
From support mail, I did not verify this but it sounds reasonable:

Groundspeak guidelines generally allow also BM-users to log PM-only caches:

"Basic Members can log finds for Premium Member Only caches when the physical logbook has been signed. Basic Members may have access to PMO caches through various means, including when they geocache with PMs. Groundspeak encourages Cache Owners to allow these logs..."

Currently it is not possible to do this in c:geo because as a BM you are not able to open a PM-cache. However a direct logging possibility could still be offered (e.g. directly from list view or live map popup).

It is possible as a BM to log a PM-cache by using e.g. http://www.geocaching.com/seek/log.aspx?WP=GC2F2VF 
As c:geo already knows the GC-code of the PM-only cache it should be possible for c:geo to post a log in this case.

---

If this information is correct, it could also be used for generally enabling logging without the need to previously open the cache (which is AFAIK the current implementation).

If I currently try to log a cache directly from map it tells me 'c:geo does not have enough information to log...' (or similar).

**Comment by KeyWeeUsr** [comment]
+1 for implementing this. I made myself a userscript just for this case because typing the url is annoying. [Here you go](https://openuserjs.org/scripts/KeyWeeUsr/GeocachingPremiumOnlyLOG) ^^

**Comment by fm-sys** [comment]
Logging a PM cache is possible by long click in list view, so this issue could be closed...
