### ISSUE TITLE
Replace confirmation by undo

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2326]
We had discussions about confirmation dialogs in several issues already. I want to suggest to not have confirmation dialogs at all, but to implement the "Gmail style" undo actions instead as described over here: http://www.vogella.com/articles/AndroidListView/article.html#listview_undoaction

I'm aware that an undo will not always be possible (but in those cases we might even just defer the _real_ action until the undo notification has gone).

Your thoughts?

**Comment by Lineflyer** [comment]
Just for the records:
Undo has been implemented by @Bananeweizen for some actions on the cache lists already.
I think he does not consider this done with that, but just a starting point, so I will leave the issue open.
