### ISSUE TITLE
Bike mode for map

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#2329]
Hi all, I often use c:geo on bike ... and there are some specific problems related to limited precision of control when you ride ... so I created this issue to gather all recommendations and point of view for using cgeo on bike.

My biggest concern:
Map .. it is very hard to click on cache icon when you can not be precise - solution can be very easy, we can create some bike mode ... when enabled, there will be menu option "select"  which should open popup of cache which is nearest to center.

The second problem of map is, that it is sometimes difficult to turn on autocenter (this should be too as option in menu in bike mode)

Map ZOOM ... it is very problematic to zoom without picking some cache or not moving map center when you ride ... if it will be possible, we can use volume buttons for zooming too.

Please provide me your point of view and some other improvements that we can do.

**Comment by Lineflyer** [comment]
Closing due to lack of feedback.
Additionally it should probably split up into different issues (which are partly already existing),
