### ISSUE TITLE
App description in Playstore - New text and more translations

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2339]
Update:
If you want to contribute please add your translation to the wiki pages linked below and leave a comment here for us to bring your update to the PlayStore.

Languages translated and published (main app):
https://github.com/cgeo/c-geo-opensource/wiki/App-description-for-PlayStore
- [x] English
- [x] German
- [x] French
- [x] Swedish
- [x] Dutch
- [x] Italian
- [x] Polish
- [x] Hungarian
- [x] Japanese
- [x] Spanish
- [x] Czech
- [x] Portuguese
- [x] Danish
- [x] Catalan
- [x] Romanian
- [ ] Lithuanian
- [ ] Slovenian
- [x] Russian (c:geo not yet available in this language but translation in progress)
- [ ] Icelandic  (c:geo not yet available in this language but translation in progress)
- [ ] Latvian 
- [ ] Hebrew (c:geo not yet available in this language but translation in progress)
- [ ] Norwegian
- [ ] Turkish
- [x] Chinese

Languages translated and published (contacts plugin):
https://github.com/cgeo/cgeo/wiki/Contacts-Plugin-description-for-PlayStore
- [x] English
- [x] German
- [x] French
- [x] Swedish
- [x] Dutch
- [x] Italian
- [x] Polish
- [ ] Hungarian
- [x] Japanese
- [x] Spanish
- [x] Czech
- [x] Portuguese
- [x] Danish
- [ ] Catalan
- [x] Romanian
- [ ] Lithuanian
- [ ] Slovenian
- [ ] Russian (c:geo not yet available in this language but translation in progress)
- [ ] Icelandic  (c:geo not yet available in this language but translation in progress)
- [ ] Latvian 
- [ ] Hebrew (c:geo not yet available in this language but translation in progress)
- [ ] Norwegian 
- [ ] Turkish

---

Original issue:
As discussed on IRC today the description for c:geo in the PlayStore should be updated/revised to offer updated and more detailed information about the functionality.

I suggest to do this in two steps:
1. Find a common agreement on a new english description
2. Translate this into as many languages as possible

I created a wiki page containing what we have today:
https://github.com/cgeo/c-geo-opensource/wiki/App-description-for-PlayStore
https://github.com/cgeo/c-geo-opensource/wiki/Plugin-description-for-PlayStore

I already modified the english description to a first draft of my proposal for a description.
I am no marketing expert, what I did was simply to write a short introduction to get users curiosity for installing it, followed by a brief listing of main features and a slightly more detailed list of how it works and what is possible. It ends with some reference to the  FAQ and the requested permissions.

Feel free to discuss it here or modify directly in the wiki. The version control should allow comparison of different versions.
If the English description is final, the contributors for translation are invited to translate it.

**Comment by AngelSM** [comment]
@Lineflyer I have just finished translating the Spanish version for the c:geo app and plugins. 
I'm afraid that some of the break lines seem to have disappeared after saving the changes; i tried to fix it by editing it again but got the same result. I hope it can be easily fixed :)
Best regards,

**Comment by Lineflyer** [comment]
Published some unpublished translations (Spanish, Danish, Hungarian) and marked them as done in this issue.

@AngelSM 
Thanks for your prompt reply to my request and many thanks for contributing the transaltion. It is highly appreciated.

**Comment by Lineflyer** [comment]
I send a mail via crowdin to the translators previously participating in Romanian, Lithuanian and Slovenian with a link to this issue and asking for help in translation those languages, as they are available in c:geo but we do not yet have a PlayStore description localized for them.

Sorry to the devs with crowdin account. You will probably receive all of them but I was not able to opt-out specific users.

**Comment by GodfatherThe** [comment]
Added Russian translation for app description

**Comment by Lineflyer** [comment]
@GodfatherThe 
Russian description has just been published to GooglePlay (may need some hours)

**Comment by andrixnet** [comment]
Added Romanian translation for each of the three apps.

**Comment by Lineflyer** [comment]
Thanks @andrixnet 
Romanian pubsliehd for all three applications.

**Comment by Lineflyer** [comment]
Turkish added above and informed our turkish translators on Crowdin accordingly to help also here.

**Comment by quidje** [comment]
Hi, i've just updated the dutch section of the playstore text in consultation with Lineflyer.

**Comment by Lineflyer** [comment]
Thanks @quidje . I have update Google Play with your translation.
Note: Changes might take 24h to get visible on Google Play.

**Comment by Lineflyer** [comment]
Closing here in favor of #4316 (which still needs manual copy to Google Play though).
