### ISSUE TITLE
Strategy of OC/GC duplicate handling

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2349]
This was discussed a little bit in #2254 or #2311 already.

If I look into the current implementation of oc.de on live map and in searches, I see a lot of caches which are listed double (OC and GC). What to do with these duplicates ?

Several strategies (from users perspective) could be used IMO:
1. Evaluate the `waypoint gccom` field and/or the OC-attribute `OC-only` and filter out caches which are listed on geocaching.com. (This means: Show only OC-only caches)
2. Evaluate the `waypoint gccom` field and combine both data into one cache description (and one cache icon, one search result), where the gc.com listing is the master and the OC-wapoint is additionally shown in that listing.

I suggest to at least implement solution 1 as an optional setting if technically possible.

**Comment by Lineflyer** [comment]
Just a side note:

> So i propose to not try a heuristic duplicate detection that will fail in many edge cases anyway, but just look at the locations of icons and offer a selection dialog when a user taps somewhere where more than one icon is painted on the map (at least in the highest zoom level). 

This has meanwhile been implemented in the mapsforge beta map by @rsudev for any kind of overlapping waypoints.

**Comment by MacGyver-NRW** [comment]
Just for information:
In January 2018 we start with a campaign to link the double caches with the respective G$ code. That could be interesting in this context. We hope for a good activation rate. So in fact, we hope to deliver a parameter which could be made our life easier ;)

**Comment by SammysHP** [comment]
This doesn't fix old (probably archived) caches, of course. This is an important feature that got lost with geolog/ocprop.

**Comment by bekuno** [comment]
For me it makes no sense to build a somehow "merged" cache. Instead we have since a while the possibility to have a selection list.
So I think we should close this issue.

**Comment by Lineflyer** [comment]
I agree. As posted above we do have a visual solution for the map in order not to miss duplicates. That should be implemented for GMaps as well which is another issue (which should be already listed here somewhere).
