### ISSUE TITLE
Store original website and show as additional details view

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2362]
Today I was thinking about the "This cache description contains table elements and may..." label that we add to caches where we are not sure if we got it right. To work around this we could store the original webpage in the cache directory (where we also store log images) and then offer an additional page in the details activity view pager where the user can look at the original stored web page (offline, not accessing the URL at that time).

Do you think that would be of value? I don't have a full list of pros and cons myself yet.

**Comment by Lineflyer** [comment]
Closing due to lack of feedback,
