### ISSUE TITLE
Special logging types for owned caches not available from nearby result

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2372]
I am not sure if 
- this is a new bug (since the change of the ownership icon)
- we never supported it
- It was already in for a long time

Procedure:
- Be sure to have non of your owned caches saved or cached
- Perform nearby search where one of the results is a cache owned by yourself
- Start logging view for your owned cache directly from result by long press on the cache

Result:
You will see that only the default log types but not the owner specific log type are shown
Only if you open the cache details the owner logs are available (Deactivate, Archive,..)

This probably means one of the following:
1. The nearby search parsing does not return the ownership status since the change.
2. We did never parse it from search results
3. Its a bug elsewhere in the code that when accessing the log view from list the log types are not shown

**Comment by Lineflyer** [comment]
Testing with 2015.01.01 according to the above mentioned procedure I could no longer reproduce the problem.

**Comment by SammysHP** [comment]
I can still reproduce it more or less. When starting the logging activity, the list is populated only with common types. Once the website is loaded the list is replaced by all actual available types.

**Comment by Lineflyer** [comment]
I think this is the "normal case". The original problem was, that the list was **not at all** populated with the owner specific log types in the mentioned scenario.
As the cache is not saved and not opened before in c:geo we can only obtain the log types when loading the log page.

But that makes me thinking now, if I performed the retest correctly as my owned cache might have been cached in c:geo already. I will retest again.

**Comment by SammysHP** [comment]
Store the cache, disable network, open logging activity. Do you see owner specific logtypes?

**Comment by Lineflyer** [comment]
Yes.


Von Samsung Mobile gesendet

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: SammysHP <notifications@github.com> </div><div>Datum:02.01.2015  20:17  (GMT+01:00) </div><div>An: cgeo/cgeo <cgeo@noreply.github.com> </div><div>Cc: Lars <gc@droescher.eu> </div><div>Betreff: Re: [cgeo] Special logging types for owned caches not available from
  nearby result (#2372) </div><div>
</div>Store the cache, disable network, open logging activity. Do you see owner specific logtypes?

**Comment by Lineflyer** [comment]
@SammysHP Please reopen if you disagree and have more detials (see test results and last comments above).
