### ISSUE TITLE
Improving selection in lists and map

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#2378]
Hi all,

I have an idea what about creating some possibility to select caches from ... to  ... in lists it should not be that difficult to implement.

In map this should work by rectangle selection such as used in crop image tool in android default gallery.

This will make it more easy to manage big cache lists.

**Comment by Lineflyer** [comment]
Have to read this through. Assigning myself.

**Comment by Lineflyer** [comment]
Closing here as there was not much supporters of such feature in the last years.
