### ISSUE TITLE
Replace list of contributors

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#2386]
Because the list of contributors in our "about" view gets longer and less maintainable I suggest to replace it with the output of

```
$ git shortlog -s -n
```

Currently this is

```
   953  Samuel Tardieu
   922  Bananeweizen
   291  SammysHP
   247  blafoo
   219  rsudev
   181  Lars
   144  mucek4
    98  campbeb
    85  Marco Jacob
    69  bananeweizen
    50  Karsten Priegnitz
    41  RomNexus6
    40  YraFyra
    39  Pavol Babincak
    38  keith.paterson
    35  Torsten Keil
    32  Portree-Kid
    29  Stephan Merker
    28  cachapa
    24  koem
    23  Andreas Scharf
    23  Joachim Wilke
    21  Sven Karsten Greiner
    19  Lineflyer
    18  c:geo
    17  Rainer
    14  Brian
    14  Florian Moesch
    14  Michiel Korthuis
    13  Gerald Barker
    13  M@®k
    13  Ralf Hubert
     8  Nelson Correia
     8  triakcz
     7  Ondřej Kunc
     6  Heiko W. Rupp
     5  BudBundi
     5  LudoO
     5  Ray
     4  Bazsy
     4  Libor Tvrdík
     4  Ricardo Seromenho
     4  italian-geocacher
     3  Bc. Jan Kaláb
     3  Sven Greiner
     3  inkantis
     2  BestHafr
     2  Buuhuu
     2  David Hrbáč
     2  Mieczyslaw
     2  ludoo0d0a
     2  patrick
     2  seromenho
     2  teschi
     1  Fernando Coello
     1  Francesco Sacchi
     1  Gacksi
     1  Kai Stempfle
     1  Marc
     1  Matthias Büchner
     1  Michael Keppler
     1  Stefan Breunig
     1  jenda^^
     1  mieczyslaw
     1  rasch
     1  runehl
     1  serenity182
     1  tm0702
     1  unknown

```

This can be done on Jenkins as we already process dynamic content. A few duplicate entries (because of different names as author) should be ok.

**Comment by akkatracker** [comment]
Any update on this, was going through the outdated contributors list in the app and was wondering if it had been brought up yet.

**Comment by SammysHP** [comment]
I suggest to

- manually filter the current list of contributors in c:geo and remove everyone that is not obviously included in git (we can remove people with the addition "translation" because we do not attribute translators anymore)
- during build create a list via git, merge it with the manual selection and sort it alphabetically
- use this list in "about c:geo".

The question is what we should do with duplicates/aliases.

**Comment by akkatracker** [comment]
There won't be too many duplicates (most people have already noted them on the ohloh page. 

I suggest maybe simply overriding for the cases (if there are others fix on a case by case basis)

**Comment by geocachermgo** [comment]
Can be closed?

**Comment by Lineflyer** [comment]
IMHO it can be closed as we - over the last years - from time to time manually updated the contributor list. This mode works rather good and new contributors good even present a PR to add themselves as contributor.
