### ISSUE TITLE
have link to nearest cache on home screen

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#242]
One button is free: The type-selection on the home screen. The filter is already present in lists (but we must refactor them, so that you can select more than one). We only need to add this filters to the map.

The free type-button should be replaced with a "Nearest cache"-button, that brings you directly to the nearest available (not found) cache. Maybe you can configure persistent filters (type, size, difficulty) in a long-click-context-menu or in the settings.

**Comment by Lineflyer** [comment]
Could this be an idea for our new dashboard?
Otherwise we should probably close here as outdated as the old main screen is gone.

**Comment by fm-sys** [comment]
> Could this be an idea for our new dashboard? Otherwise we should probably close here as outdated as the old main screen is gone.

Let's close. I have opened  #12309 as follow up...
