### ISSUE TITLE
Provide settings backup as part of database backup

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#2425]
When https://github.com/cgeo/c-geo-opensource/issues/2380 will be implemented, it should be easy to add there user settings too, because google backup agent is not working on all devices and it is annoying to change all settings when using more phones.

I have an idea ... when backing up ... to have dialog where you can just select what all you want to backup (caches, images, static maps, settings). I think that according to our policy we will NEVER backup passwords, but all other settings we can.

And for import ... there should be the same possibility to select just part of backup to be restored.

**Comment by Lineflyer** [comment]
This has meanwhile been implemented.
