### ISSUE TITLE
Use waypoint prefix (or lookup code) instead of id

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#2431]
Right now, we use an "id" to identify the waypoint, which is the row id in the database. Not only this will not survive a backup/restore which does not copy the database, but also it duplicates information: the prefix and lookup code are both unique for a given geocode.

We should use a couple (geocode, prefix) (or (geocode, lookup)) to identify a waypoint uniquely.

**Comment by Lineflyer** [comment]
@samueltardieu Didn't you recently change something with respect to the prefixes used for custom waypoints? Did this also solve this issue?

**Comment by Lineflyer** [comment]
@pstorch As you are familiar with the current DB. Can you make a comment about this?

**Comment by pstorch** [comment]
@Lineflyer I think this got fixed by c75f89dba2712cba5bc8cec02479cac43197e65c. All waypoints have a unique prefix assigned.
