### ISSUE TITLE
Not deleting field note (offline log) after submitting online

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#2449]
Hi, I'm using self compiled version (now it is same as yesterdays master) and I have discovered one inconsistency (I don't know if it is regression or not, never noticed before).

When you create field note (just by log offline -> Found) from list, active map popup, cache details ... it works correctly, but when you try to submit that field note ...

Log visit offline -> log visit -> (loggging window) -> Send log button
it depends where you start this sequence ...
- when it is started from cache detail activity it is ok ... it deletes associated field note (cache is not visible in list where you put filter status->offline log prepared)
- if it is started from list (long press) or map (cache popup) it sends log online, but never removes that associated field note

additionally - field note is not clearable in that case by clicking on clear in offline logging menu

**Comment by Lineflyer** [comment]
No longer reproducible with the steps mentioned above.
Tested on 2017.08.26-NB.
