### ISSUE TITLE
Replace send2cgeo links

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2458]
Currently we host the user script directly on the website. Therefore it must be manually copied from the repository to be up to date. Shouldn't we instead use https://github.com/cgeo/c-geo-opensource/raw/master/send2cgeo/send2cgeo.user.js everywhere as link to our script? That way it is always up to date (while it is not updated for weeks right now).

**Comment by Lineflyer** [comment]
This topic will be taken care of with the new website and will be tracked on cgeo.github.io.
