### ISSUE TITLE
<hr> is not rendered

### ISSUE THREAD

**Issue by caigner** [cgeo/cgeo#2476]
`<hr>` is not rendered.

**Comment by Lineflyer** [comment]
I have a question regarding this issue:
Recently another user contacted us on support with the fact that his cache listings do not work with repect to `<hr>`. 
However I do not fully understand the reference by @SammysHP to #2477, can someone explain this limitation to me? For me this is neither a color problem nor a CSS problem, isn't it?

**Comment by kumy** [comment]
Maybe the relevant information from #2477 is "b), because the text is rendered by Android."

On February 12, 2016 7:09:05 PM GMT+01:00, Lars <notifications@github.com> wrote:
>I have a question regarding this issue:
>Recently another user contacted us on support with the fact that his
>cache listings do not work with repect to `<hr>`. 
>However I do not fully understand the reference by @SammysHP to #2477,
>can someone explain this limitation to me? For me this is neither a
>color problem nor a CSS problem, isn't it?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/2476#issuecomment-183434388

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
