### ISSUE TITLE
Ability to toggle size of map marker

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#2509]
Sometimes when using the satellite view the cache marker is in the way and covers essential areas. Especially when zoomed in to the max.

It would be great if you could be able to toggle the cache marker so it just becomes a tiny dot/crosshair.

**Comment by Lineflyer** [comment]
The arrow will never have the accuracy to cover this use case (making it smaller would only raise the uncertainty circle around) and (together with the uncertainty of the sat view) never deliver a useful information.
I recommend using the compass instead.
