### ISSUE TITLE
Backup/Restore filename with date

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#2547]
Hi,

today I had accidentally restored my old backup of database which was nearly empty ... and I just wondered ... why we havent implemented some confirmation dialog there ... and one idea came ... what about backing up to files with suffix date and then have possibility to restore user selectable version of DB ?

For example we can restore in files with names similar to GPX exports (cgeo.backup_20130305_225412.sqlite).

Do you think that it makes sense ?

**Comment by fm-sys** [comment]
fixed in a slightly different way with #9179
