### ISSUE TITLE
Waypoints of hidden owned caches shown on live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2558]
Today I have seen that the live map behavior changed.
I am not quite sure about the exact behavior, however I can see the following which is unusual:
- I activated "Hide own/found"
- I use to have my owned caches (and some found as well) saved on list

Today I have seen that the waypoints of my owned caches are shown on live map although the cache itself is not shown.
I am sure, that this constellation never happend before, however I am not sure if we previouly hide also owned/found caches stored locally.
However if the cache is hidden due to setting/filter its waypoints should be hidden as well.

**Comment by Lineflyer** [comment]
Problem still present for all maps but solved on Mapsforge beta

**Comment by Lineflyer** [comment]
@rsudev 
I somehow had the hope that your recent rework of the map code (PR #7657) would implicitly also fix this. The first look on my homezone showever shows, it is not solved. It happens on all map types.

Can you take a look at it...I guess it is only some missing condition somewhere?!

**Comment by rsudev** [comment]
@Lineflyer I was a bit surprised reading your comment, as I had expected the same (but did not check specifically). Unfortunately is it not so easy, as ownership is nothing we store in the database AFAICS. In other places it is checked on cache object level by asking the connector.
In the case of displaying the waypoints I don't even bother to retrieve the caches, so this is a bit trickier.

**Comment by Lineflyer** [comment]
oh. My easy thinking was, that when you manage to hide owned caches (which works fine) it should be easy to also hide their child objects...but seems its not so easy.
 
How does hiding of owned caches work, if we cant identify them from the DB info?

**Comment by rsudev** [comment]
There is a filter method, that checks the ownership by asking the cache object which in turn calls into the connector to check whether user and cache owner are the same. As the list of caches is built for display anyway, not such a big deal.
For waypoints, as we want to show all of them, even if the owning cache is 'far' away, I check for those within the viewport and filter out the ones of found and disabled caches by joining into the cache table.
Meanwhile I tried to filter the waypoints through their owning cache objects, will see how the performance is.

**Comment by rsudev** [comment]
> The first look on my homezone however shows, it is not solved. It happens on all map types.

Can you please cross-check? Or describe in more detail? According to my tests this only happens on the new mapsforge map.

**Comment by rsudev** [comment]
@Lineflyer Not sure what I was looking at, but now found the same issue on the old map...

**Comment by jakedot** [comment]
Isn't this an old long known bug? At least I have seen it for quite a long
time, and haven't there already been issues and PRs? Sorry I don't have
proper internet access to check, with my broken phone...

**Comment by Lineflyer** [comment]
Yes, this issue you commented on actually is this old issue :)
