### ISSUE TITLE
Easy setting of visited state to wpt from popup

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#2592]
What about setting visited state directly from wpt popup ? Button or checkbox ?

I did one multi today ... and I felt it uncomfortable to mark wpts by clicking edit, checking that checkbox than saving and getting back to map.

**Comment by Lukasdoe** [comment]
Especially when you are in the "Map-View". When you see a waypoint on the map, you have to first hit "Edit" in the point description, then you are able to mark it "Visited" by scrolling down and trying not to alter any information stored in the waypoint data. This is somewhat tricky when you are using the app while moving. How about adding an option in the page you get, when clicking on a waypoint on the map. Probably a good point would be the menu (that appears to be the cache menu) in the upper right corner of the opening card.
