### ISSUE TITLE
convert complex dialogs to activities

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2611]
Today I was completely confused by our user interface. When I edited coordinates in the wild and afterwards tried to save them, I thought the application was hanging.

In reality what happened was that the editing dialog was consuming 2/3 of my screen, with the waypoint activity still visible in the background. But the foreground and background are really hard to distinguish, which is why I tried to scroll down (below the radio buttons of the background waypoint activity) to see the save button of the dialog.
(will attach screenshot)
That's why I suggest to convert the coordinates dialog into an activity instead.

**Comment by Lineflyer** [comment]
@Bananeweizen From my knowledge I would assume this to be done (at least for the described case).
Feel free to reopen.
