### ISSUE TITLE
Find a way to reenable StaticMapsProviderTest

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#2643]
The `StaticMapsProviderTest.java` test has been disabled in 512ae6d23112bf9ce0de2782adab0b9874f69b31. It was failing very often and prevented other failures (or successes) from showing up in the test results.

The test should be re-enabled but should attempt to download static maps for real.

**Comment by Lineflyer** [comment]
It seems that this file is no longer used at all.
@samueltardieu Please reopen if this is still an issue.
