### ISSUE TITLE
Incorect user cache count shown in log (language specific)

### ISSUE THREAD

**Issue by bubi-luka** [cgeo/cgeo#2670]
When I read log of a cache, I found a user claiming his 100 cache, but his count show "one cache". Should it be "one hundred and one cache" and the string did not fit on my screen, or is it a bug?

**Comment by Lineflyer** [comment]
> minSdkVersion to 11 or higher. We surely don't want to do that (as it would make run cgeo on Android 3.0+ only).

We have done this meanwhile :)
