### ISSUE TITLE
OSM:Offline: After selecting new map it is opend at map center but not at the previous location

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2687]
- Open details of a cache
- Select Navigate -> Map
- Given the case that you previously used a not-matching map (e.g. Germany, Bavaria but the cache you want to view is in NRW)
   you then select Menu -> Map and select the appropriate map
- The new map is opened but centered to the map middle (?) so the cache is no longer in view

or

- Open live map
- Your current position is shown by the marker
- Given the case that you previously used a not-matching map (e.g. Germany, Bavaria but you are in NRW)
   you then select Menu -> Map and select the appropriate map
- The new map is opened but centered to the map middle (?) so your position is no longer in view

After selection of a new map the view should be initialized at your position (live map) respectively the cache coords (cache map)

**Comment by Lineflyer** [comment]
+1 from support mail.
He described that for users living in border regions between countries this bug can be quite annoying.

**Comment by rsudev** [comment]
I'll try to tackle this, as I have an idea what is amiss

**Comment by Lineflyer** [comment]
It can be broken down to: Last position and zoomlevel are lost if map source changes.

**Comment by rsudev** [comment]
Assigning for field test.

**Comment by Lineflyer** [comment]
Confirmed working with 2015.01.18-NB.
I vote for inclusion into `release` branch.

**Comment by Lineflyer** [comment]
Has been merged to release meanwhile.
