### ISSUE TITLE
oc.de GPX contains unknown / wrong attribute ids

### ISSUE THREAD

**Issue by koem** [cgeo/cgeo#2690]
I exported OCD30F. It contains:

```
      <groundspeak:attributes>
          <groundspeak:attribute id="106" inc="1">Only loggable at Opencaching</groundspeak:attribute>
          <groundspeak:attribute id="10" inc="1">Difficult climbing</groundspeak:attribute>
          <groundspeak:attribute id="62" inc="0">Seasonal access</groundspeak:attribute>
      </groundspeak:attributes>
```

They try to export with groundspeak ids.

106: this is a non existent GC-ID. They invented a new one. OC-ID is 6

10: they use 10 here which is also wrong. on their site its 28 and called 'easy climbing' which doesn't exist in GC. They should export it with ID 128

**Comment by Lineflyer** [comment]
Isn't that one closed by the mentioned commit?

**Comment by samueltardieu** [comment]
I don't know. It needs checking.

**Comment by Lineflyer** [comment]
I checked the export of the mentioned cache. It does not contain the <groundspeak:attributes> tag.
