### ISSUE TITLE
Separated cachestatus filter

### ISSUE THREAD

**Issue by electronaut** [cgeo/cgeo#2703]
It would be great to have all the cache statuses in separated checkboxes.
So instead of only "exclude own and found caches" and disabled caches, have one for everyone:
own, found, disabled, archived.

I often want to be able to see my own caches to keep track of them, but not the ones i have found, 
And the archived ones probably never comes back, so i dont want to see them either.

**Comment by okainov** [comment]
There are other services and they may allow to have separated filter "own"/"found". For gc.com it could be simple fallback "if any option is checked, show neither found nor own", when for other services it can work as expected
