### ISSUE TITLE
Deleted waypoint on GC.com is not removed in c:geo (when refreshing a cache)

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#2704]
Hello,

Here is the pb and the way to reproduce it.
Pre-requisite : be an owner for a cache

1. on gc.com: delete a cache waypoint
2. in CGeo: download cache (or remove it then download it again)

=> the deleted waypoint is here!

See cache: http://coord.info/GC3WRQT where there are only 2 waypoints on GC.com and 3 downloaded and displayed in CGEO.

**Comment by Lineflyer** [comment]
Has been solved with  115ead6
