### ISSUE TITLE
Upload multiple images with a log entry

### ISSUE THREAD

**Issue by dgw** [cgeo/cgeo#2734]
Currently, c:geo supports uploading only one image with a log, requiring the user to add additional image(s) later (via the website, AFAIK). Instead of changing the "Add Image" button to "Edit Image", c:geo should allow adding another image and managing the image(s) already attached.

**Comment by kumy** [comment]
I'll work on that. From first code analysis, I'll first refactor the 3 variables representing an image (url/title/description) found in some activities (`LogCacheActivity`, `ImageSelectActivity`, `AbstractLoggingActivity` and some connectors) by usage of `Image` class. Issues #4109 #5078 will also benefit of that.

**Comment by naoliv** [comment]
@kumy any news about this, please?

**Comment by kumy** [comment]
I ve removed my assignment on this issue one year ago, I don t plan to work on this, sorry. Maybe @pstorch as he worked recently on picture upload for OC connectors.

**Comment by pstorch** [comment]
Maybe, but it has not a high priority for me. I first want to finish the new logging page implementation and some other issues.

**Comment by nimirCZ** [comment]
Something new?

**Comment by SammysHP** [comment]
Nope, otherwise you would see something here. ;)
