### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#2797]
I added an SVG version of our logo. It is slightly different from our old logo (especially the font) and thus I recommend to update it everywhere (Google Play, app, cgeo.org, ...)

**Comment by Lineflyer** [comment]
@SammysHP Do you know whether this has been done?

**Comment by SammysHP** [comment]
No, nothing changed yet.

**Comment by samueltardieu** [comment]
Has this been taken care of?

**Comment by SammysHP** [comment]
Not that I know of.

**Comment by Lineflyer** [comment]
Fixed by #8559
