### ISSUE TITLE
Replace "post task" notification

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#2875]
<bananeweizen> I would like to remove that "post task" completely
<bananeweizen> and replace it by a conditional build step if possible
<bananeweizen> which depends just on the current build state
<bananeweizen> instead of detecting the build state itself

**Comment by samueltardieu** [comment]
Should this issue be kept open?

**Comment by Bananeweizen** [comment]
I think this can be closed. I think all the conditional logic was removed by now.
