### ISSUE TITLE
Support .obf offline maps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2913]
From support mail (don't know whether it is feasible):

Hello !
Is it possible that you implement the support of    .obf files (Osmand) for offline maps? Up to now you only can use .map files from mapsforge.

**Comment by RalfJung** [comment]
OsmAnd can store their maps on the SDcard, accessible for every App. "All" it would take is supporting their format, which I obviously have no idea how hard it would be. Even if they are not a library, you could obviously use their source-code. I could of course understand if you said you didn't want to support their format, but I can't follow your argument of why you can't.

Right now, I have all the maps stored twice on my device, which is kind of a waste. Even worse, when I travel, I have to remember to download the new maps twice - and for the c:geo maps, there's no auto-update or nice download UI. So, usability wise and in terms of disk usage, supporting the OsmAnd map format would be a great step ahead.

**Comment by SammysHP** [comment]
Programming is not as simple as "get that code, put it in our code and done". Without a proper library that handles everything related to the map (so that we only need to add a view) we can't support it.

**Comment by rsudev** [comment]
@RalfJung Simply put does "can't" in this context not mean 'is technically not possible' but 'is with respect to effort, benefit and resources not feasible'.
Supporting a map format which is not explicitly tailored to be used by other parties means, it might change anytime in unexpected ways without any compatibility promises - this is something you might consider if the format is *extremely* valuable and you have plentiful resources at your disposal - which just is not the case...

**Comment by rsudev** [comment]
Small update: I took a look over at OsmAnd. We can't include it in the legal sense, as OsmAnd is licensed under GPL, which is incompatible with Apache IMO.
I think it would be possible if there is a library under LGPL, but even there I am not sure.

**Comment by RalfJung** [comment]
Thanks a lot for your detailed replies!
