### ISSUE TITLE
Geocaches not showing up on c:geo app on phone

### ISSUE THREAD

**Issue by hobbsmt** [cgeo/cgeo#2945]
First, I am new to geocaching, so this could be some mistake with settings, etc. that I do not understand about the app.  

Many geocaches are not showing up on the map on my phone although they show in the list of Nearby geocaches (I even stored most of them).  They do show up on the map on the geocaching.com website.

No geocaches between geocache NRT Octopus (GC44ZEP ) and NRT Mile 11.75 (GC42XVB) show up on the map.  There are 20 missing geocaches icons that show up on the geocaching.com website.  A few of them are NRT Stumper (GC44ZCP), NRT Riverside (GC44ZEE), and Beyond Buffaloe (GC4528).

**Comment by sallysomd** [comment]
I just started having the same prob. Uninstaller, reinstalled, cleared cache and data
 Maps show and work, but no caches show. Show as logged in i am premium member. Would certainly love this to work again.

**Comment by moving-bits** [comment]
If you are logged in successfully and still have that problem: Can you cross-check that you haven't set any filters on your map that might filter out caches? (You may want to open a support ticket with us and send us your system information + log file for further analysis.)

Additionally, we have received lots of complaints about the geocaching.com's servers responsiveness throughout the last weeks. Some of their servers seem to work normally, while others are running into timeouts frequently. If you happen to get directed to a "bad" one by the servers' load balancer, you have bad luck. Sadly, we cannot influence that from c:geo side. If you get caught by that, a change between mobile and WiFi might help (but is no guarantee) to get a new, better connection.

**Comment by sallysomd** [comment]
Yes, all my filters are correct. How do I start a ticket?

**Comment by moving-bits** [comment]
> How do I start a ticket?

Basically, send an email to support@cgeo.org. To include system info and logfile, please follow those steps:

You will find the c:geo system information in: c:geo Start -> Menu -> About c:geo -> Swipe to "System".
It might take some seconds for the system information to be shown on that page.
At the end of that page, there is a button "send logfile" - tap this, select "standard", then "send per email" - this will open your email program with pre-configured email address.
