### ISSUE TITLE
Search by keyword not available anymore for gc

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2950]
Gc changed the searching for caches a while ago. Now it is no longer search by keyword, it is only search beginning with keyword. We need to make this more transparent in our user interface.

**Comment by Lineflyer** [comment]
The keyword search in gc.com seems to be back to a real keyword search now (part of the site update end of March 2015).

**Comment by Bananeweizen** [comment]
@Lineflyer Nope. At least the search used in cgeo still only searches for the term at the beginning of the cache name, e.g. "klause" will not find any "XYZ Klause" cache.
