### ISSUE TITLE
check calendar before adding event

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#2971]
I just got 5 reminders for an event cache due to 5 entries for it in my calendar. Probably from some debugging. To avoid this, c:geo should check for existence of a calendar entry with the same name and time.

**Comment by Lineflyer** [comment]
A while ago, we changed the mode to access the calendar to an intent method and thus got rid of the calendar plugin.
I assume interacting with the calender is no longer possible now, which means this feature is no longer possible to implement.

@Bananeweizen Feel free to reopen if I interpreted this wrong.
