### ISSUE TITLE
Support GeoKrety

### ISSUE THREAD

**Issue by Cu8eR** [cgeo/cgeo#3007]
Hi,
I am just curious... Is possible to show GeoKrety trackables in Geocaching caches? I think it is not implemented yet because I didnt see Geokret which was in my last cache in cgeo in trackables... but it was shown on GC.com websites with GeoKrety plugin...¨

Thank you

**Comment by Lineflyer** [comment]
Thanks to @kumy this feature has now been implemented.
Bugs and additional feature requests will be tracked seperately.
