### ISSUE TITLE
Background cleanup needs to be indicated

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3010]
I just opened the app and opened an offline stored list with 4 caches. That took roundabout 30 seconds. I know that I deleted some 2000 caches at the start of the week, so this has probably been the cleanup of those in the database and on disk. 

However, a casual user will only experience the delay without knowing this and think the app is broken. I suggest to have some kind feedback during the cleanup operation, but I have no idea how to make it in such a way, that it is not intrusive and does not block the user from using c:geo.

**Comment by Lineflyer** [comment]
Did not come across this problem for a long time.
Its still there and might arise if clean up is done on a high amount of cache data (e.g. deleted many caches) in combination with a low performance device. However devices and storage kept improving over time making this issue obsolete IMHO. Feel free to reopen.
