### ISSUE TITLE
Mixed usage of "send2c:geo" and "send2cgeo"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3015]
As found in review of #3011 we currently have a mixed usage of these two terms in our strings and also on the website.

How is our tool officially called?

My preference goes to "send2cgeo", but I can't tell why...just subjective

**Comment by ldmpub** [comment]
Done for french translation (send2cgeo everywhere). Is there a way I could also make this change for master language english in crowdin or only a developer can do a search & replace in Eclipse (or in an other dev tool)?

**Comment by Lineflyer** [comment]
@ldmpub 
Thanks for your effort.
But it was kind of the wrong way around. This should be done in the string master here on Github at first as it will anyway invalidate all translated strings.

I will have a look whether I can change it today in the source.
