### ISSUE TITLE
Make user aware of non precise location in compass

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3066]
Today I was in the woods, using the compass often, but switching the display on and off often. When I switched my display on, the compass rose would start nervous movement immediately (due to the magnetic sensor). At the same time, the distance label would often need several seconds to start updating (due to GPS sensor). This can lead to estimating the distance totally wrong (it still shows the distance from the time you switched the display _off_) because the compass rose movement makes one think the data is current.

To avoid this, I thought we could record the latest time of getting a GPS update and show the distance label in red color, when a certain amount of time has passed without update (e.g. 5 seconds). This would lead to the label being red immediately when switching the display on after a longer time and it would go back to white with the first GPS data coming in.

Comments? Other suggestions?

**Comment by Lineflyer** [comment]
Obsolete with the new GS map.
