### ISSUE TITLE
Live map should start at last position if not fixed to current position

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3078]
A feature request from support mail which I fully agree to:

- Open the live map
- Move it manually to the desired location (which means "fix to current position" is off)
- Leave the live map
- Enter the live map again

Result:
- It starts at the current position ("fixed to current position" is on again)

Desired behaviour:
- In case the map was moved to another position before it was closed it should open again on this very position (right now we only store the last zoom but it seems not the last position)

**Comment by Lineflyer** [comment]
Information taken from #4551:

in older versions one came back to the last position at the maps when opening 'live maps', in the new version c:geo forgets the last position and always starts at the center of the actual city.
This means scrolling every time when opening 'live maps'.
Is this to be a feature? To me it behaves more like a bug - is it posible to re-configure c:geo to old behaviour?

Before, with GPS on, it always showed the present position. With GPS off, it memorized the place that was last shown/chosen. In this state, there was an issue. After I turned off GPS, I needed to remove app from memory and restart it, otherwise, it still showed the map from last GPS known point.

Now, even with GPS off, it always show the map from my home position, even if I'm not at home. I have turned off WiFi also, but it still shows the map at my home location.

For example, I select a directory "Faro" where there are caches from a certain area and choose the map icon to show them on the map. Then I go back to the main page and select the Live Map. It shows at my home location, instead of "Faro" location, as it was before.

Also, following your instructions to select the "active Live Map" in the "Faro" area, all found caches also appear, despite the option is set to hide them.

In my opinion, I think the previous behavior is much better, because in any map location there's always the option to go to the present location, by clicking in the "target" icon at the top, right? The opposite is not possible.

**Comment by samueltardieu** [comment]
@Lineflyer I'll rebuild a -NB for you to test. Please tell me when this is done if you want it in `release`.

**Comment by Lineflyer** [comment]
Due to limited amount of testing time I would prefer to keep it on `master` for now but test it later and probably merge to `release` for another bugfix release shortafter.

**Comment by Lineflyer** [comment]
Looking at the small functional changes made here I revert my previous comment.
I will test it and we can merge to release afterwards.

**Comment by samueltardieu** [comment]
Done.

**Comment by Lineflyer** [comment]
Confirmed working as expected in 2015.01.12-RC.
The map position will be remembered during the whole session and only gets back to the current position if the user enabled the "follow me"-function. That is IMO really good.
