### ISSUE TITLE
visitedDate wrongly set to zero

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3081]
On Saturday and Sunday I went for around 25 caches. All of them have been logged offline. Those logs are complete (i.e. exporting field notes or just looking at the logs in cache details is fine). But for 2 of the 25 caches the visitedDate in the cache table is zero. This leads to those 2 caches missing in the history.

I've now looked back and forth through the code to find how the visitedDate might become zero. But I don't really have any clue as all the places accessing that variable seem to be fine.

Therefore it would be good if someone else could watch for the same to happen. I also don't know anymore what version I used at the weekend, as it has been updated in the meantime.

**Comment by Lineflyer** [comment]
The reason has been found: #4086
