### ISSUE TITLE
send2cgeo Firefox add-on

### ISSUE THREAD

**Issue by JavaJens** [cgeo/cgeo#3094]
Hi,

is there a reason why there is no Firefox AddOn?
The idea I have is to remove the need for Greasemonkey, as I find this to be cumbersome for novice users.

It would be fairly simple to do this, 5 lines with the AddOn builder and page-mod.
Though, one possible issue I see with this is the update mechanism, as for each change of the script the addon would need to be updated as well, but then Firefox would update the app automatically.

Furthermore I have one off-topic question, is the server side code for send2cgeo publicly available as well?

Looking forward for feedback.

**Comment by Lineflyer** [comment]
This issue was moved to cgeo/send2cgeo#8
