### ISSUE TITLE
Grammatical mistakes and layout issues on the website.

### ISSUE THREAD

**Issue by johnvansickle** [cgeo/cgeo#3114]
Hello,

Thanks for the wonderful app! While reading more about it I noticed some grammatical mistakes and possible layout issues, so I thought I would offer some help. I'll list the specific page and underneath, the issues that I think need addressed.

----http://cgeo.org/  (main page)

The following are at the top of each page:

Under "Send 2 c:geo":  "Easy transfer caches to your device ..."  --> "Easily transfer caches to your device."  (grammar, use a period)

Under "F.A.Q.": (First, I would lose the dots in that acronym. In my opinion it would look cleaner)  "Frequently Asked Questions by Users." (I would omit "by Users" here, again- my opinion)

Under "Report Bug / Issue":  "You found one of them? Let use know!"  --> "Did you find one? Let us know!"  (personal opinion here)

Under "Contact":  "For questions, wishes and support."  --> "For questions, wishes, and support." (missing comma, maybe "requests" is more suitable than "wishes") 

In the main description:

"c:geo is simple yet powerful unofficial geocaching client for Android devices." Why is it unofficial? Unless there's some legal reason for this I would remove "unofficial."

"In contrast with other similar applications, c:geo doesn't require web browser nor exports."  -->  "In contrast with similar applications, c:geo doesn't require a web browser or exports."  (remove "other", added an "a" before "web browser", doesn't + nor = double negative)

"You can just go geocaching with your phone and without any home preparation or worries. Of course, you can go without paying - it's free."  --> "You can go geocaching with your phone without any home preparation or worries, and, of course, it's free!" (omit "just" and "and", combine the two sentences, personal opinion)

"Try it! Use the barcode, search for "cgeo" on Android Market or download and install .apk file manually." --> "Try it! Scan the QR code using your device or search for "cgeo" in the Google Play Store, or download and install .apk file manually."  (It's a QR code, not a bar code. It's the Google Play Store and no longer referred to as the Android Market. Comma before "or download)

Before I get too carried away, that's all for now.

**Comment by Lineflyer** [comment]
Will be superseeded by a new homepage currently under development in https://github.com/cgeo/cgeo.github.io/
