### ISSUE TITLE
Strange sequence when import *.loc 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3126]
Importing a GPX works normal but importing a *.loc shows a strange behaviour:

After the file has been selected the progress immediately jumps to 100%.
In the log I can see that the data is being imported but at the same time the static map download is triggered for each cache.
After importing is done (acc. to log) the progress for static map download is shown normally and it seems the maps are downloaded once again.

So the fault is:
- Static maps should not be downloaded during the file import but seperately
- Progress indicator is wrong

**Comment by akkatracker** [comment]
Can you confirm this still happens?

**Comment by Lineflyer** [comment]
@akkatracker Any specific reason for this question?

**Comment by akkatracker** [comment]
I tested some .loc s yesterday and didn't see anything wrong with the progress indicator.

**Comment by Bananeweizen** [comment]
Closing as not reproducable then.
