### ISSUE TITLE
Use different coloured smilies for found/dnf/etc

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#3129]
Feature request: It's sometimes a bit irritating if all caches with offline-logs gets the same red smiley on the map, whether I loged a found or a dnf. Whould be nice to see a difference, for example different colours for the smiley.

**Comment by kumy** [comment]
I've also added some new icons for "notes/needs maintenance/needs archived".

**Comment by SammysHP** [comment]
This will work only as long as we support only a single offline log per cache, right?

**Comment by kumy** [comment]
Right

**Comment by Lineflyer** [comment]
Tested and working with 2015.08.23-NB but one remark @kumy:

IMHO the icons for "found offline" and "not found offline" do only differ in the face of the smiley but not in color. This makes it almost not distinguishable in list views.

Any good idea to improve it?
I suggest a bright red for "not found" and more orange (like the vertical line) for "found offline"...

**Comment by kumy** [comment]
I'll see what I can do. Hacking this icon was not easy.

If someone would propose new icons?

**Comment by Lineflyer** [comment]
Perfect now IMHO.
