### ISSUE TITLE
Beta phase of waypoint formula tool

### ISSUE THREAD

**Issue by Ichabod** [cgeo/cgeo#3135]
Hi folks,

just for your information: like mentioned in #3027 the android app startet an open beta phase these days. Have a look at www.cachelab.net if you want to participate.

CacheLab will be published under a closed source commercial licence. There is a JSON webservice (already active) and an open source API library (comming soon, after the beta has been finished), that can be used by other programs which want wo make use of the waypoint database of CacheLab.

**Comment by Natureshadow** [comment]
I'm totally against providing this as a closed service. Please only include it if the service is publicly accessible, provides data unser OSI licenses and is open source Software.
