### ISSUE TITLE
Do not retrieve static maps while testing

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#3190]
In test mode, we should not hammer Google servers with static map requests. Moreover, this is counter-productive as we saturate the free quota in less than one run.

One solution would be to mock the corresponding setting to prevent static maps from being retrieved.

**Comment by Lineflyer** [comment]
Closing this issue as obsolete, as Google static maps are no longer available (without payment).
So whatever replaces them needs a new implementation anyway.
