### ISSUE TITLE
Parse DNF

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3206]
With the new cache details page we would have the possibility to parse, that a user posted a DNF log for a certain cache.
This could be shown as a status in cache details ("Not found") and additionally be shown by a blue(?) smiley on the map.

See also #3129

**Comment by Lineflyer** [comment]
After following a discussion on this topic in combination with recent icon changes in c:geo it came to my mind, that it would be quite easy to track and show a DNF status without the need of parsing any additional information from the webpage:

As we have the logbook (own/Friend) all logs of the user are contained there.
So it could be as simple as:
If the cache detail parsing does not return that the cache is found, we could check the parsed own logbook of that cache if it contains a DNF entry. If so, we could set the status to "Did not find" (which is already partly implemented for offline logs (blue smiley)).

Opinions?

**Comment by Lineflyer** [comment]
To be complete for this issue:
Meanwhile the webpage provides the DNF status clearly in the users cache detail page, so parsing should be possible without additional network communication (or analyzing the logbook).

**Comment by MagpieFourtyTwo** [comment]
Stumbled upon this issue, when I was going to open a Feature Request for showing the blue DNF frowny in lists and map ... are there any chances to get it?

It's possibly not that much of a deal, as the frowny already shows up in lists and live map anyway - *if* you have an *offline* saved DNF log.  But, unfortunately, as soon as you submit the log, not just the blue frowny disappears, even the vertical "I have logged something" bar vanishes, and the cache will be listed as if you never ever dealt with it. :/

So my objective would be:
When I logged a DNF, but no (newer) Found Log (which can be cross checked in e. g. friend logs page), the blue DNF frowny should be shown in lists and map (like it already does right now if I have an offline saved DNF log). And perhaps even the vertical bar can be shown in blue ...? And possibly even the "State" field may be set to "DNF (at \<date>)"?

Any chance to get there?

**Comment by eddiemuc** [comment]
I put this one on my list too, but I am afraid it is already quite a long one. So if someone wants to start inbetween, don't hesitate (just give me a short notice please)

**Comment by fm-sys** [comment]
@eddiemuc Are you already working on this one or shall I take it over?

**Comment by eddiemuc** [comment]
Please take over
