### ISSUE TITLE
Cache-Popups open several times

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#3213]
In the newest nightly-builds I noticed that the same cache-popup on the livemap sometimes opens a few times.

Sometimes it needs a second or two until that popup is open. When I touch on the cache icon again and again in that time (because I don't know if the device had realised my touch) the popup opens again after I touched the dark map to to close it. So in some cases I have to touch the map three or four times to go back to the map.

**Comment by Lineflyer** [comment]
According to my experiences this problem does no longer happen on the live map popup.
Feel free to reopen if you disagree.
