### ISSUE TITLE
PQ - Not all stored-caches are displayed on the map if there are to much

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#3215]
Sometimes not all stored caches will be shown on the map. I noticed this much times when I zoom out from a center of an imported PQ with 500 or more caches. The round circle full of caches seem to be cutted at the half and the eastern part is missing. If the shape of imported PQ is round that is easy to recognize but if it is rectangular (for example from gsak) that can be really irritating. If its really not possible to display all caches I whould like to get a short error-message.

**Comment by gcPhil** [comment]
I don't saw this problem any more in the in recent months. Maybe its just my current smartphone that have more performence than the older one but I guess the problem is solved in the meantime.

**Comment by Bananeweizen** [comment]
In fact, this looks _somewhat_ like the Mediatek bug: http://www.cgeo.org/faq.html#osm-mediatek-problem. When this was reported previously, all caches were shown on a vertical line in the middle of the screen. Maybe yours was a variation of that, where coordinates were not clipped to a single value, but instead were clipped to an open (left side) interval.
