### ISSUE TITLE
PQ-import dont work if "include name" is enabled at gc.com and the name contain a german umlaut

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#3221]
Hope this is not a duplicate, - i found nothing in the old issues.

I created a PQ named "Rügen Auswahl" at gc.com and marked the option " Include Pocket Query name in download file name" there. 
But I was not able to import it to c:geo. I get the Error Message "Bad bite at 10".

 It worked with two workarounds: 
- open the zip and rename the gpx-files so that the umlauts are gone
- create a PQ without this name-option.

Here the not-working file: http://db.tt/WUkVQ9Hu

**Comment by pstorch** [comment]
During development and testing I came across this bug.
I have a Pocket Query with Umlauts in it:
![2016-01-13 21 49 01c](https://cloud.githubusercontent.com/assets/5598124/12309019/ae9a8768-ba48-11e5-82b0-27016b462e69.png)

The option "Include Pocket Query name in download file name" it checked.

When importing I get this error:
![2016-01-13 21 49 25](https://cloud.githubusercontent.com/assets/5598124/12309025/b3d25ed6-ba48-11e5-9ea4-77952a97411c.png)

It doesn't matter if I download/import it via HTTP (the new function) or via ES FileExplorer and open with c:geo.

**Comment by Lineflyer** [comment]
Reopening as it is now directly relevant to c:geo with the new PQ import.

**Comment by pstorch** [comment]
I don't know if this is an option, but the [Apache Commons Compress](https://commons.apache.org/proper/commons-compress/) library supports an encoding in the [ZipArchiveInputStream](https://commons.apache.org/proper/commons-compress/javadocs/api-1.10/index.html) class.
It's compatible with Java 5. I don't know if it's possible to use in an Android environment.

**Comment by pstorch** [comment]
I give the Apache Lib a try. Let's see if it can be used.

**Comment by pstorch** [comment]
Hier is a test with Apache Commons Compress library. As a developer I can say "it works on my machine" ;)
Please feel free to test it and give feedback.

**Comment by pstorch** [comment]
I should document my findings here, too. 
The cp437 encoding for the PQ filename is only used when the PQ is based on a Bookmarklist which contains Umlauts. 
If you create a PQ without a Bookmarklist, the Umlauts in the PQ name are encoded with HTML entities. Maybe that's why @Lineflyer couldn't reproduce this issue anymore.
