### ISSUE TITLE
Feature request: Talking list

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#3232]
This was already mentioned in #417. 

A lot of request are on support email and facebook to implement talking list in addition to talking compass.
Talking list would give you spoken instructions to the next cache. Like for power trails for example. The question just remains what is the next cache.
- Caches that are "in front of you" (9 o'clock - 3 o'clock)
- Caches that are not found (and do not have stored log)
- Only caches that have a strage there (would it make sense to talk for misteries?)
- Shall it work only on stored lists or also on nearby, etc...

I have also selected feedback to get feedback.

**Comment by Lineflyer** [comment]
Closing due to lack of feedback and interest in such a feature.
