### ISSUE TITLE
Replace "Go to" by waypoint view

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3288]
Couldn't we replace the any screen by an invocation of the waypoints screen and just put all these waypoints to some artificial cache ID?

This would increase the usability of that feature and at the same time reduce our code.

**Comment by Lineflyer** [comment]
To bring up this again:
In a discussion with some users it came up, that they would prefer to have to `Go to` menu look like the waypoint screen.
Then I found this long existing issue and want to emphasize again, that it would be a good idea to completely replace the `Got to` by a waypoint screen of a virtual cache in our database. That would just be perfect.

**Comment by Lineflyer** [comment]
Implemented by using the user defined cache approach
