### ISSUE TITLE
have Pocket Query Creator in import menu

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3291]
During the recent presentations I gave and also during events I notice that nearly no one knows about the Pocket Query Creator app, although it is listed in our helpers apps screen. I was wondering if we could increase the visibility by having a new menu item besides the import GPX file and import from web menu items, which would always be visible and would either invoke the pocket query creator or redirect to the market page (if not installed yet).

Comments? Other ideas?

**Comment by Lineflyer** [comment]
We implemented a direct PQ import meanwhile.
So I think we can close this one...the only remaining functionality of PQC which c:geo does not have is the ability to create new PQ. But IMO this is what PQC should be used for as it is quite special for c:geo.

Feel free to reopen if you disagree.
