### ISSUE TITLE
Add Google+ to the web site template

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#3292]
Icons for Google+ [have been generated](https://www.dropbox.com/sh/v69ndzp830g6hpn/cArgra4vhk) by @SammysHP for our web site.

The link should include the `rel="publisher"` attribute, as in:

```html
<a href="https://plus.google.com/105588163414303246956" rel="publisher">…</a>
```

so that ownership of cgeo.org is linked to the Google+ account.

**Comment by Lineflyer** [comment]
Moved to https://github.com/cgeo/cgeo.github.io/issues/19
