### ISSUE TITLE
Map settings only accessible from map view

### ISSUE THREAD

**Issue by dl1ely** [cgeo/cgeo#3301]
The map settings are only accessible when the map is displayed. This leads to an vicious circle when due to misconfiguration c:geo crashes when displaying the map: The faulty setting cannot be reset, as the menu cannot be reached before the crash. I propose to include the map settings in general app settings as a separate sub page.

**Comment by Lineflyer** [comment]
Closing due to lack of interest and need (no problems reported to access the map).
