### ISSUE TITLE
ANR in Mapsforge

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#3316]
Required: Slow connection

1. Prepare Mapsforge to use online map
1. Open cache list
1. Press "Map". The (empty) map appears and map tiles are loading.
1. Press "back"

c:geo is not responding anymore (ANR after some seconds after user interaction) until all tiles are loaded in the background or a timeout occurs.

**Comment by Lineflyer** [comment]
Fixed as documented in #4001
