### ISSUE TITLE
GPX import dialog only closes with a delay after succcess

### ISSUE THREAD

**Issue by Pitel** [cgeo/cgeo#3344]
I'd expect to have the dialog closed, and return to list. Instead, dialog  with 100 % is still there and I have to click Cancel button (which is confusing, because I don't want to cancel import).

**Comment by Lineflyer** [comment]
Assigning myself for a retest.

**Comment by Lineflyer** [comment]
I retested this with 2018.05.07-NB with an import of a PQ with 1000 caches with and without static maps loading.
There was no remarkable delay during or after the import steps any more.
Closing for now.
