### ISSUE TITLE
Limit static map loading to 50 requests per minute

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3406]
Moved from #1602 to a separate issue:

I just analyzed a report from a user saying that he imports 120 caches but fails to get static maps for most of them. I I rarely use static maps I gave it a try using the GPX of this user.

What I can see from the log is, that for the first 9 caches all static maps are fetched successfully. This means approx. 45 requests.
After that the server returns a 403 error most probably due to the fact that the consecutive requests are made too fast (as assumed by @Bananeweizen above).

The 403 starts at timestamp 12:15:40 and lasts for 316 requests, first successful load after that is at 12:16:18. The next 48 requests are successful until timestamp 12:16:38, where again a 403 error is returned.
This tells me that running into the server throttle makes most requests fail resulting in only a few maps been downloaded OK.

Besides the discussion in this thread about a general new strategy for static map loading isn't there a quick fix possibility by throttling the requests on our side ?
IMHO it would make more sense for those users relying on the maps, that the download lasts longer instead of not having the static maps.

The particular user which contacted us, often has to use c:geo offline (and knows about the 1000 request limit from Google) but currently has no easy means to make sure all his imported caches have static maps.

**Comment by hashstat** [comment]
I've been hitting this issue lately as well. Perhaps my network speed has improved and maps are downloading faster, but refreshing only adds static maps for about 10 caches, which makes grabbing static maps for pocket queries a real pain. Until recently I was getting many more and I'm not sure what changed.

[This Google maps API](https://developers.google.com/maps/documentation/staticmaps/) page confirms the limit of 50 requests per minute and [this page](https://developers.google.com/maps/documentation/business/articles/usage_limits) details how to determine if the per-minute or daily rate has been exceeded.

Perhaps this issue could be solved by adding a function which only updates static maps slow enough to avoid the per-minute limit?

**Comment by Lineflyer** [comment]
> Perhaps this issue could be solved by adding a function which only updates static maps slow enough to avoid the per-minute limit?

This was exactly the intention for this issue.

We already have a mechanism to update those caches first which are missing static maps.
If we would know limit to an appropriate rate for refreshing and additionally (I think this is in another issue) just skip updating of existing maps (those rarely change over time) we could end up still being faster and more complete with the static maps.

**Comment by samueltardieu** [comment]
It means using background services for downloading. Which we don't do right now. But that could be an option.

**Comment by Lineflyer** [comment]
Closing this issue as obsolete, as Google static maps are no longer available (without payment).
So whatever replaces them needs a new implementation anyway.
