### ISSUE TITLE
Avoid synchronous saving

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#3442]
Blocking the UI while saving to the DB makes using c:geo tedious in several areas:
- working with the personal note
- working with waypoints
- offline logging
  it should be possible to synchronously update the cache object/UI state and do the saving to db in the background.

**Comment by Lineflyer** [comment]
@rsudev We do this in background meanwhile, don't we?

**Comment by samueltardieu** [comment]
@rsudev Do you have a particular scenario in mind? I don't think we do block anymore.

**Comment by Lineflyer** [comment]
Closing due to comments above and mising feedback.
