### ISSUE TITLE
Possibility to disable touch when map is active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3454]
From support mail:
While the map (live, fom cache, etc.) is active it would be helpful to have a menu to disable/enable touch events.
It often happens while outdoors that the screen is accidentally moved, zoomed at times where I just want it to follow my position.

**Comment by samueltardieu** [comment]
I do not think this is worth adding in cgeo while other map applications do fine without it. You are always one click away from activating again the "follow me" mode.

**Comment by moving-bits** [comment]
Agree with @samueltardieu, won't "fix" this pretty old issue.
