### ISSUE TITLE
Mark saved events which have been logged "Will attend"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3455]
From support mail:
I usually have quite some event caches saved and it is hard to remember where I already posted a "Will attend".
It could be an improvement to somehow mark this state in the cache list or at least the cache details (Status not "Found" but "Will attend")
## 

Remark:
The feature request to include your own logs in the Friends-log tab could also be an option, as the user has a quick possibility to check what he already logged for these caches.

**Comment by Lineflyer** [comment]
See above: The Friends log meanwhile contains own logs fro a quick reference to your Will Attend.

**Comment by Bananeweizen** [comment]
Even the details page has the "Will attend" state now, if this is detected from the logs. So it is basically implemented as requested.
