### ISSUE TITLE
Suppot Garmin offline .img maps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3456]
From support mail:

Oruxmaps app support Garmin offline .img maps. I hope that c:geo support this map file some day because im from Finland and the National Land Survey (NLS) has made its topographic datasets available to the public and to companies.

http://www.maanmittauslaitos.fi/en/opendata
http://translate.google.fi/translate?sl=fi&tl=en&js=n&prev=_t&hl=fi&ie=UTF-8&u=http%3A%2F%2Fkartat.hylly.org%2F&act=url

And this map is very accurate ( more accurate than OpenStreetMap)

**Comment by Lineflyer** [comment]
MIght be followed up in #6641 if technically possible to use this in a configurable tile downloader.

**Comment by SammysHP** [comment]
This is absolutely not related to online tiles. But I'm fine with closing this issue because it is not something that we would be able to implement.
