### ISSUE TITLE
OX caches opened from map/coordinate search are missing details

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3511]
2014.01.04-NB:

Steps:
- Activate oc.com as cache source
- Open live map
- Select an OX cache and open it from the popup
- Description is empty and no logbook is shown
- Select "Refresh"
- All details are shown

This is not intuitive..It took me some minutes to realize, that I have to refresh manually to get the needed details.
We should directly send the request for complete data if the cache is opened from the popup.

**Comment by Bananeweizen** [comment]
closing as this connector is gone
