### ISSUE TITLE
Open webpage when logging caches without log support

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3520]
For caches where our connector doesn't implement logging support, we might simply open it's web page when using the logging menu.

**Comment by samueltardieu** [comment]
We don't present the logging menu if the connector does not support logging. The users can use the "Browser" menu entry to get to the web page.

**Comment by SammysHP** [comment]
IMHO we **should** present the logging menu for all caches, but open the web page as suggested (with "Open log page" instead of "Log found").
