### ISSUE TITLE
Google+ cache find sharing

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#3524]
On Google+, someone requested an automatic way of sharing the found caches on Google+ as we do on Twitter and (indirectly) Facebook.

**Comment by madankumarbaskaran** [comment]
May I work on this feature request?

**Comment by Lineflyer** [comment]
AFAIR we agreed some time ago not to implement more dedicated social network support but to just keep Twitter (as it was there and also offers crossposting to other social networks). So, I vote for not implementing this.

**Comment by SammysHP** [comment]
Additionally I'm of the opinion that G+ is not the right platform for such automated status updates.
