### ISSUE TITLE
Remember map position per session

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3526]
A discussion on facebook brought up this proposal:

Do not open the map on the current position by default, but on the last remembered map position (which is not the last remembered device position!). Because people sometimes switch between map and lists (or settings, or...) and then have difficulties finding the previous (non center) location again.

As a lot of people would expect the map to open at the current position normally, this somehow needs to be tied to a "session". Such that if you use c:geo on Monday, it does _not_ reopen at the old position on Tuesday, but on the current position.

As Android does not really support this "session" concept well, I suggest to use the time delta as criteria. If the map is opened again in a time span of 1 hour, reopen the map at the last position, otherwise at the current position.

**Comment by Lineflyer** [comment]
Was implemented recently as proposed by @samueltardieu
