### ISSUE TITLE
Filter/sort - Do not sort by localized names

### ISSUE THREAD

**Issue by ludoo0d0a** [cgeo/cgeo#3604]
I just fix and review some texts in Crowdin for french translations.
And I just see that "Filter by" and "Sort by" items are sorted by localized names.

I don't understand why, because most common filters are in the top down of the list.
Type Size Terrain ... 
I use a lot thess filters and i should scroll down every time...

I suggest to remove this comparator, and to decide a priority order, common to all languages.

in cgeo.geocaching.filter.FilterUserInterface(final Activity activity)

```
// sort by localized names
        Collections.sort(registry, new Comparator<FactoryEntry>() {
            @Override
            public int compare(final FactoryEntry lhs, final FactoryEntry rhs) {
                return lhs.name.compareToIgnoreCase(rhs.name);
            }
        });
```

**Comment by Lineflyer** [comment]
Closing due to lack of submitters feedback and general interest in this change.
