### ISSUE TITLE
Terrain filter goes up to T7,5

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3619]
AFAIK the highest T-rating currently is T7.
However the filter selection offers the following filters:
![2014-02-20 15_59_27-c_geo](https://f.cloud.github.com/assets/949669/2219381/a8cdcb5e-9a3f-11e3-888a-fd5c174ff619.png)

This is either a issues of incorrect strings or also a code problem?!

**Comment by Lineflyer** [comment]
Still open with 2016.01.19

**Comment by samueltardieu** [comment]
@Lineflyer Include in `release`?

**Comment by samueltardieu** [comment]
Assigned to @Lineflyer for testing and possible later inclusion in `release`.

**Comment by Lineflyer** [comment]
Tested and OK to merge in 'release'. Tested with 2016.04.03-NB
