### ISSUE TITLE
Map zooms out when it shouldn't

### ISSUE THREAD

**Issue by darekkay** [cgeo/cgeo#3637]
This bug occurs only using OSM and offline maps. 
Tapping with two fingers on the screen causes the map to zoom out (I assume this is a feature). The problem comes while pinching, which normally zooms in/out the map. But if it's done too quickly, the screen either zooms out or doesn't zoom at all. This depends on how big the pinch movement is. Fast and short pinch = zoom out, fast and long pinch = nothing happens (i.e. the map zooms in while pinching, as any map would, but it returns to the same zoom level after releasing).
It seems like the two-finger-tap is triggered, if a pinch movement is too quick. This would explain the behavior: 
- quick short pinch = "nothing" from map + "zoom out" from tap => zoom out
- quick long pinch = "zoom in" from map + "zoom out" from tap => nothing happens

Since Google Maps doesn't have this two-finger-tap feature, it doesn't occur there.

**Comment by Lineflyer** [comment]
No more feedback or reports like this. Closing for now.

**Comment by SammysHP** [comment]
I still have this problem but it will be obsolete with the new map.
