### ISSUE TITLE
Translation to new languages

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3644]
Instead of having separate issues for new languages to include from crowdin I created this issue with a list of ToDo:

The following languages have been created for translation on crowdin and need to be added to the source code if a sufficient coverage of translation is reached:
- [ ] Icelandic
- [x] Lithuanian
- [x]  Russian
- [x] Catalan
- [x] Romanian
- [x] Latvian
- [ ] Hebrew
- [x] Finnish
- [x] Korean
- [ ] Greek
- [ ] Chinese Simplified
- [x] Turkish
- [ ] Filipino
- [ ] Tagalog
- [x] Cebuano

**Comment by rsudev** [comment]
Finnish reached the proofread level (50%, actually it is 68%) we required for inclusion. Should I add it?

**Comment by Lineflyer** [comment]
It crossed the border as I approved a lot of strings which had been translated for almost a year (but without proofreadings so far).
Maybe we should still add FInish now as it might draw attention to finish users for helping to complete the translation...so IMO Yes!

**Comment by rsudev** [comment]
Finnish included

**Comment by GodfatherThe** [comment]
How can I get the c:geo with Russian translation? I've translated more that 50% of the strings on Crowdin (https://crowdin.com/project/cgeo/ru) and I would like to check it "in real life" on my smartphone.

**Comment by SammysHP** [comment]
We have to import the translations and build a new version of c:geo (nightly).

@rsudev

**Comment by rsudev** [comment]
I can see to it, so it will be available with next nightly

**Comment by Lineflyer** [comment]
@GodfatherThe  Additionally I will set you as a proofreader for the russian translation. So you can validate your translations (and also set your translation as the correct one. I have seen some issue, where you state that existing translations are not meaningful).
Please note, that only proofreaded translations will be contained in the nightlies once @rsudev has downloaded them.

**Comment by GodfatherThe** [comment]
@Lineflyer thanks.

**Comment by Lineflyer** [comment]
@GodfatherThe 
Proofreading role is now assigned. You should validate your translations, so that they are included in the next upload. I also answered all your issues.

There are a few other persons who contributed some russian strings.
You can refer to this page: https://crowdin.com/project/cgeo/ru/activity

**Comment by GodfatherThe** [comment]
@Lineflyer, Russian translation is mostly done, please update the translation in the repository. Thanks.

**Comment by rsudev** [comment]
Russian added.

**Comment by GodfatherThe** [comment]
@rsudev please update again, I fixed some issues after trying it on my smartphone.

**Comment by rsudev** [comment]
Korean was added in the meantime

**Comment by Lineflyer** [comment]
Reminder to myself:
Check languages with >50% translations but no proofreadings and try to find proofreaders.

**Comment by Lineflyer** [comment]
Greek translator invited to proofread strings.

**Comment by Lineflyer** [comment]
Added Turkish as language on Crowdin (and in the list on top) due to request on FB.

**Comment by rsudev** [comment]
Turkish is now included in release and master
Added Filipino and Tagalog as per request on Crowdin

**Comment by rsudev** [comment]
Added Cebuano as per request on Crowdin.

**Comment by Lineflyer** [comment]
Greek translation is at nearly 100% but not being proofread.
I asked the major contirbutors if they would like to proofread the translation.

**Comment by Lineflyer** [comment]
Cebuano has been translated and proofread 100% by now.
Can someone please upload from Crowdin and add the new language to the repo?

**Comment by rsudev** [comment]
I have done so. But I don't have a device that offers Cebuano as a language selection, so I couldn't test it.

**Comment by Lineflyer** [comment]
Lets close here and open a new issue each time a new language has sufficient coverage.
We can now monitor this rather easy by looking at the strings.xml file content in the translations.
