### ISSUE TITLE
Have "Use GPS only" setting session based

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3675]
Current situation:
If the user enables "Use GPS only" in the compass menu, this setting is persistent. It affects not only the compass but also other directional views (e.g. pointer on live map).
There are quite a number of users on support mail with "compass problems", where it turns out this settings was active (either accidently or because it was once needed for a special purpose and forgotten afterwards).

I suggest to change this settings to be "session based" and defaults back to "Use Compass and GPS" (only if the device has a compass sensor of course).
The other option would be to have a clear indication somewhere, that the magnetic sensor is disabled.

**Comment by Lineflyer** [comment]
@samueltardieu 
Please correct me if I am wrong: The active sensor setting has meanwhile been implemented transient/session based, so we can close this issue?

**Comment by samueltardieu** [comment]
Yes, this has been made transient since dce71fa22dc6ebeeca837edf5db0fe68cf28ed0a.
