### ISSUE TITLE
Hanging log sending blocks cgeo

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#3676]
On my bike tour today I had problems with logging. Although the mobile data connection shows best quality H+ it sometimes fails to send logs. But not only. cgeo was blocked until I killed it.

Users should have a chance to either try sending log in background or make this a cancelable dialog. I know that this will increase the chance of double log entries. Maybe something like "send to background"? But then we would need a feedback interface, don't we?

**Comment by Lineflyer** [comment]
We do now have a log sending progress message implemented since some time.
Additionally we implemented a timeout and screen with Save/Retry/Abort once log sending timed out.

Feel free to reopen if these items do not cover this issue.
