### ISSUE TITLE
option for filtering archived caches on the map

### ISSUE THREAD

**Issue by aiomaster** [cgeo/cgeo#3683]
Hi there,
I think it would be usefull, if you could keep archived caches in your list, but filter them out for example in the map.
I think about an option like hiding own and found caches from the map.
What do you think?
Is there a reason why there is not such a feature?
I read in #3583 that it is wanted behaviour that unfound archived caches are shown to the user. I think it should be configurable.

**Comment by andrixnet** [comment]
+1

**Comment by andrixnet** [comment]
Current cache icon looks like disabled icon (grey background) but with a pencil icon, which makes no sense. Should be reddish background (as archived caches are marked) without that pencil.

**Comment by moving-bits** [comment]
Filtering archived caches on the map has been implemented with #8101
