### ISSUE TITLE
Homescreen Suggestion

### ISSUE THREAD

**Issue by yellowduck** [cgeo/cgeo#3684]
Following the introduction of support for pocket queries, I feel that the homescreen is a little awkward to use. We currently have six icons for various functions (and I only use _stored_ to any great extent, the others are seldomly used). 

My proposal is to add (or modify the)  icons to include _settings_, _pocket queries_ and _about c:geo_, because I find myself using these on a regular basis, and it would be more convenient to have them with direct access on the home screen (rather than via the menu).

**Comment by Lineflyer** [comment]
We have quite some other issues dealing with an overhaul of the main menu. This would be implicitly cover this topic then. Therefore closing.
