### ISSUE TITLE
Add ability to add waypoint from map view

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#3693]
I would love a feature to add a waypoint from the map view by long pressing on a position on the map and choose "Navigate to" or "Add waypoint" in a context menu.

The only way to add a waypoint today is to enter the coordinates manually or read from the Notes.

This feature would be particularly useful when trying to navigate to a suitable parking place.

**Comment by Lineflyer** [comment]
+many

according to user feedback on the GIGA and messages on FB.

**Comment by Lineflyer** [comment]
Related to #1141

**Comment by Lineflyer** [comment]
@rsudev  BTW: Didn't we have a discussion some time ago, that you planned (or already implemented) a (similar) feature on the mapsforge beta?

**Comment by Lineflyer** [comment]
Found it:
On the mapsforge beta map, when you opened it for a single cache, you can long click on the map to add a waypoint for this cache.

I think this feature request is completed by that just still in a beta phase.
A more generic approach (whithout the need to have the map opened for a single cache) is much more difficult to implement. For this more generic use case I propose to cover that by the existing feature request to transform the "Go to..." menu to a waypoint view. From there you could again open a map and create a waypoint.
