### ISSUE TITLE
Remember zoom level in List Map view

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#3738]
I find it very annoying that the map zooms out to show all caches in the current list every time I press the Map Icon in the list view. I have to zoom in to a more suitable level to locate a nearby cache, only to get all the caches again after pressing the Map icon later.
It would be great if the zoom level should be remembered from time to time when viewing the list map. You could add a "Remember Zoom Level/Show all caches" option in the Map settings menu.

**Comment by Lineflyer** [comment]
@MrYaz 
I don't think we are going to implement a change here for now.
You wrote:

> EDIT: Ok, looks like it will only show the caches if you zoom in to the area far enough. Maybe it's workable, let me play with it.

So I will close that one for now. Feel free to reopen.
