### ISSUE TITLE
Map not centered

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3815]
Normally when we use the "my position" button in our maps then it becomes centered on my position and stays there also in other zoom levels. Yesterday I sometimes was not in the screen center when using this button. Zooming in could then even lead to moving the blue arrow to outside the screen, on pressing the button.
This only happened, when I opened a map for a list of about 1000 caches and had very bad network. So bad that the Google map background would not load at all.

**Comment by Lineflyer** [comment]
This is a side effect of #4365 according to my experience and your description.
Let us continue in that issue.
