### ISSUE TITLE
Ability to copy only a part of the description

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#3819]
I often want to copy only a part of the description to use in other apps.
It might be a coord, a word that I want to google, a cipher in a mystery cache that I want to decipher etc.
But when I long press the description there are only an option to copy all of the description.

I would love if there was a possibility to select and copy a part of the description or part of the hint.

Suggestion:
Add a "Select text" option in the longpress menu
Use standard text selection to select a part of the text.
Like in the mockup below.

![Select text](https://cloud.githubusercontent.com/assets/1811963/2881887/250759f6-d488-11e3-8e53-c3f59bc45f20.png)

**Comment by Eselter** [comment]
Also text should be striped from html tags ;)

**Comment by rahu** [comment]
Is it a key feature to copy short and long description together? If not it's simple using android:textIsSelectable="true" and remove the addContextMenu stuff for short and long description. You have the ability to copy only a part and there is also a select all button selecting all text from the TextView.

**Comment by SammysHP** [comment]
Can you try do implement it?

**Comment by rahu** [comment]
Implemented for both views.

You are right: As long as there is no visible separation between short and long description it's not clear why you can't select "the other" text. Next I'll try to merge those views.

**Comment by rsudev** [comment]
An alternative could be to introduce a visible distinction between them.

**Comment by rahu** [comment]
this would be more easy. :+1:

**Comment by rahu** [comment]
Now I have a solution for the missing translation problem. To get it working I needed to remove the android.support.v7.view.ActionMode and use android.view.actionmode. Will this cause any problems? 

The situation now is: you are able to select a part of the text and copy it. But if you use translate or share you still get the complete text. IMO the behavior should be to translate or share only the selection?

Btw: "Translate to Deutsch" ?? 
![screenshot_2015-12-31-14-44-30](https://cloud.githubusercontent.com/assets/937126/12064841/33f77708-afcd-11e5-81e3-bc2468ec3f99.png)

**Comment by rsudev** [comment]
Regarding 'Translate to Deutsch': I suppose you are using c:geo on a German device with forced English?

**Comment by rahu** [comment]
correct.

**Comment by MrYaz** [comment]
When will this feature be verified and ready for release?

**Comment by rsudev** [comment]
I started looking into it, but assume we will keep it for the release after the one that's currently brewing. As we expect another one end of this month (due to site changes) it might be ready then (or might not)

**Comment by samueltardieu** [comment]
@Lineflyer Please test

**Comment by Lineflyer** [comment]
Tested and working with 2016.02.22-NB using GC5H5TZ. Tried copying the whole text and parts of it, shared it to different apps and tried the translation feature (also working for part of the text now).
