### ISSUE TITLE
Field note export/upload progress not correct

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3824]
2014.05.07-NB:
- Compose an offline log for e.g. 3 caches
- Selecte Manage -> Export -> FieldNotes
- Select "Upload" and "Since last export"
- Upload progress is shown correct
- Select again  Manage -> Export -> FieldNotes
- Select again "Upload" and "Since last export"

Result:
- Same progress (with same cache count) as before
- Field-note file is empty, nothing is uploaded (or maybe an empty file)

Expectation:
- If there is no new offline log since the last export, this should be reported to the user instead of a wrong count and upload an empty file

**Comment by pstorch** [comment]
Just stumbled on this one. I could only partly reproduce. 
The progress is showing on second upload, but the count is zero.

**Comment by Lineflyer** [comment]
No longer reproducible.
