### ISSUE TITLE
Font size too small on map

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#3830]
I find the street names on the maps much too small to be readable.
Both on Google maps and on OSM.
If I compare with the Google Maps App the street names are much bigger.
As a result you have to zoom more to show more street names.

I have a nexus 5 with a resolution of 1920x1080 and 445 ppi
Is there a way to customize the font size depending on the unit's resolution?

There should be a map font size setting if possible.

The "Scale Map Text" option does not seem to have any effect for online maps.

**Google Maps in C:geo**
![image](https://cloud.githubusercontent.com/assets/1811963/2939666/cae0da62-d953-11e3-8352-70a2408e6140.png)
**Google Maps App**
![image](https://cloud.githubusercontent.com/assets/1811963/2939669/e86c4a3a-d953-11e3-9bec-d4f66e17d3b7.png)

**Comment by tato-lx** [comment]
Hello! I disagree. I tested the same thing with another application ViewRanger GPS for OpenStreetMap. It seems Viewranger GPS uses one zoom up'ed version of the map making the letters bigger and more clear. Here are the screenshots:

C:Geo:
![screenshot_2016-01-14-09-27-21](https://cloud.githubusercontent.com/assets/16700880/12324039/ef7c4284-bab7-11e5-8b36-1fd15dd3543a.png)

Viewranger GPS:
![screenshot_2016-01-14-09-27-56](https://cloud.githubusercontent.com/assets/16700880/12324049/fe846d06-bab7-11e5-817a-853eeadbbb75.png)

I suggest this could be fixed.

Thanks

- Renato

**Comment by rsudev** [comment]
If you have any detailed insights or code to contribute, we might consider it. As this such a rare use case (all people I know personally use only offline maps if they switch to mapsforge), we rather direct our interest elsewhere.

**Comment by Lineflyer** [comment]
@MrYaz Did you test the setting?

**Comment by rsudev** [comment]
@Lineflyer This is about online maps - there the setting has no influnce
