### ISSUE TITLE
Waypoint "Visited" option too small

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3857]
The checkbox and font size of the "Visited" option in the waypoint edit dialog became quite small. 
It can easily happen to select "Save" accidently when trying to mark the WP visited.

**Comment by rsudev** [comment]
I think this request is no longer relevant, as the save option moved to the action bar. Right?

**Comment by moving-bits** [comment]
Closing due to rsudev's comment and #2592 being implemented meanwhile.
