### ISSUE TITLE
Support favorites on oc.de

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3879]
I do not know whether this is possible via the API:
Currently OC-caches show the amount of favorties but the user is unsable to set the cache as favorite while logging or afterwards.

**Comment by Lineflyer** [comment]
Just for information:
According to http://www.opencaching.de/okapi/services/logs/submit.html this is supported by the latest API version (but requires to be done while submitting the log itself (so this would need #4347 to be implemented at first).

**Comment by SammysHP** [comment]
+1 from OC newbe event.

**Comment by Lineflyer** [comment]
Due to the fact that there were quite some fantastic OC-only cache at the location of my latest vacation I stumbled over the problem, that c:geo still cannot assign favorite points (OC speak: Empfehlungen) to OC-caches.

Once this issue was opened the problem was, that it need to be submitted with the log, which was  ot supported back then.

I somehow thought it was done while implementing the fav setting in logging view...but seems it was only done for GC at that time.

This is a real missing "basic" feature in c:geo. If anyone is interested in closing this gap, I would highly appreciate it.
