### ISSUE TITLE
Switching lists animation

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#3883]
Switching from any list except for "history" to "history" uses an animation. Switching from any list to any list except for "history", no animation is shown.

**Comment by Lineflyer** [comment]
Seems this animation is no longer used (or at least I cant spot any difference when changing lists between "history" and other lists.
Tested with 2016.08.27

**Comment by Bananeweizen** [comment]
that was never an animation, but just an activity restart. :)

**Comment by kumy** [comment]
@Bananeweizen is right, and there isn't any app restart since resolution of #4969
