### ISSUE TITLE
Different font sizes in similar menus

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#3887]
From the german geoclub.de
Some menus now have a smaller font which is more pleasant to read, some still have the former, larger font.
Sample is the cache list view
Sorting: new, nicer
Filter: old, bigger, not so nice
Reasons? Opinions? Possible to make uniform?

**Comment by Bananeweizen** [comment]
At least if we are talking about the _current_ implementation, then both are two different things. Sorting is an ActionBarContribution (therfore using action bar styling), filtering is a normal popup menu. The filter also cannot be easily converted to an action bar contribution, as this would require 3 levels of menu item nesting (one for the filter item, 2 for the actual filter selection), but Android only allows 2.

**Comment by SammysHP** [comment]
![screenshot_2015-02-14-15-30-04](https://cloud.githubusercontent.com/assets/922874/6199901/88e6c248-b45e-11e4-950f-0174fcf04b29.png)
![screenshot_2015-02-14-15-30-24](https://cloud.githubusercontent.com/assets/922874/6199902/88e9736c-b45e-11e4-817c-0f525b31e3ad.png)

**Comment by Bananeweizen** [comment]
This has become obsolete with the latest code. Filters are now an expandable list view in a new activity. The intention is to replace parts of that activity by better fitting controls over time (i.e. sliders etc.).
