### ISSUE TITLE
Android 2.3: Duplicate title in Actionbar 

### ISSUE THREAD

**Issue by schwabe** [cgeo/cgeo#3898]
This seems to be only on Android 2.3:

![bildschirmfoto 2014-05-23 um 10 06 08](https://cloud.githubusercontent.com/assets/1038539/3064325/274a55ac-e251-11e3-921e-0a781b1ee98c.png)

**Comment by Lineflyer** [comment]
Assigned myself for restet.

**Comment by Lineflyer** [comment]
I can reproduce that with version 2015.03.31 on Android 2.3.
However I think it is not worth a fix because of the the low Android version and it is only occuring if the popup is opened

**Comment by Lineflyer** [comment]
As we change to Android 4.0 as minsdk for 'master' this wont get fixed.

**Comment by Lineflyer** [comment]
Wont get fixed as mentioned above.
