### ISSUE TITLE
Input dialogs don't use correct style

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3906]
Use the "new list" menu in the cache lists. The EditText input field is not looking holo-ish.

Related code is in /cgeo/src/cgeo/geocaching/ui/dialog/Dialogs.java

**Comment by Lineflyer** [comment]
@Bananeweizen Is this still valid?

**Comment by Bananeweizen** [comment]
I'd say yes, even though I'm not 100% sure. Compare the input dialog text field with the signature input in the settings. Signature input has background similar as dialog background, and a blue holoish separator underneath the multiline input. The new list input on the other hand has black background instead of the dark grey holo dialog background and it has a visible 1 pixel border.

**Comment by Lineflyer** [comment]
Meanwhile this will be outdated due to several style changes and necessary adaptions.
