### ISSUE TITLE
Replace popups

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3932]
Looking over the existing issues, I feel like we currently get into a lot of trouble with the cache and waypoint popups. We have to emulate an action bar there, we have to re-implement a lot of the logic of its menu, and still there are some bugs or inconsistencies (when compared with the real actionbar).

Instead of trying to fix all that in the popups, I suggest we instead remove them. By that, I do not mean to remove the _content_ of the popups, but instead just the popup around the content. Basically take the layout contained in the popup and show it as a _non modal_ box at the top or bottom of the map. Look at Neon, GeOrg or the GC app to see what I mean.

The action bar menus could then either be related to the map (if no cache is selected) or to the selected cache/waypoint. You have all seen this already with the contextual action bar, when selecting something in an app. 

And that has multiple benefits:
- popup code can be removed
- users can switch between caches _without_ needing to press "back" in between
- we can expand that concept more easily to show more than 1 cache, e.g. by just stacking 3 of those boxes onto each other.

Comments please?

**Comment by moving-bits** [comment]
we have switched cache/waypoint popups to non-modal bottom sheets meanwhile, so let's close here
