### ISSUE TITLE
number of caches wrong in footer bar

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3934]
Start a search. Activate a filter. Hit "more caches". Afterwards the footer shows the filtered number, while it showed the overall before.

We could either fix this or get rid of the numbers (as they are already at the top in the spinner). Anyone with strong opinions about that?

**Comment by Lineflyer** [comment]
Tested again with 2015.04.07-NB

Header and footer information is now consistent in the case described above.
