### ISSUE TITLE
Navigation drawer

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3937]
Now that we have the actionbar, I've also started implementing a navigation drawer: https://developer.android.com/design/patterns/navigation-drawer.html

Now you may ask yourself, why on earth do we need yet another fancy new UI thingy, isn't the action bar sufficient? And the answer is: No. The action bar is solely for actions, while the navigation drawer is for improving the navigation. Currently you can only navigate forward/backward along the pathes of the activity hierarchy, but you cannot easily "jump" between them. E.g. if a cache was opened from a list and you now want to start a search, you have to go back twice and then click search, 3 navigation commands overall. With the navigation drawer you can jump to any top level activity from (almost) anywhere.

Might take another day or two...

**Comment by akkatracker** [comment]
@Bananeweizen are there any updates on the Navigation drawer?

**Comment by moving-bits** [comment]
I guess that after such a long time (and the related branch being more than 6.000 commits behind current master) no more work is done on this, so let's close here for cleanup (and open a new issue, if needed).
