### ISSUE TITLE
Feedback needed: Setting Cache Directory

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#3950]
**I need feedback:**

* Do you / we want the setting "set cache directory" or not?

**If yes:**
* Where should we add the check / warning dialog stating the cache directory path is not accessible any more? AbstractActivity, CgeoApplication? onCreate, onResume?
* Should we transfer the files ourself?
* Should we move or copy the files (user might not be able to access internal cgeo dir)?

**Comment by Lineflyer** [comment]
I would like to put all of these discussions (#3950, #706 and others) into a new issue dealing with the overall file structure of c:geo. We surely have to find a solution for the offline cache (/.cgeo) but IMO as well include those random dirs we are using (e.g. /field-notes / GPX) into that discussion.

A lot of the discussion in those issues was about the right strategy and -even more important- about a migration strategy from the current to a possible new strategy.

Independently of whether there is someone willing to implement this, I would like to ask if you agree with starting from scratch and at first outlining the current situation and our target and afterwards define the ways towards it in a new issue.
The example from Locus posted in https://github.com/cgeo/cgeo/issues/3950#issuecomment-67784999 seems like a very good option also for c:geo.

Feedback?
