### ISSUE TITLE
Cache beacon app no longer available (replace it by ANT+ Plugin Sampler)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3951]
I installed the app "Cache Beacon" (for chirps) some days ago, however looks like it recently has been removed from the PlayStore.
I will try to contact the author.

If it is decontinued we should remove/replace this Navigation method.

**Comment by Lineflyer** [comment]
Let me reopen this one. The link to the old app has been removed. 
If it is technically possible we should add a link to the above mentioned "ANT+ plugin sampler"

**Comment by Lineflyer** [comment]
Alternatively we could probably also directly retrieve chirp data with their SDK:
https://www.thisisant.com/developer/ant/ant-in-android/

Depending on the amount of code that would be an option for a plugin if someone is interested in such things.

**Comment by Lineflyer** [comment]
Or link to this (free) app:
https://play.google.com/store/apps/details?id=nl.wlsoft.chirp

**Comment by pyrog** [comment]
@Lineflyer I tested this app. It worked fine, but it lack of a direct link to c:geo. We need to manually create a waypoint (new stage, final location…) in c:geo and manually set the coordinates (without errors).
So the user experience is not very good.

Could add an intent in [chirp](https://play.google.com/store/apps/details?id=nl.wlsoft.chirp) app or directly support chirp in c:geo ?
See #4588

**Comment by pyrog** [comment]
> Alternatively we could probably also directly retrieve chirp data with their SDK:
> https://www.thisisant.com/developer/ant/ant-in-android/

Yes, the SDK provide sample code the retrieve and *set* _Chirp_ datas.
See this [video](https://www.youtube.com/watch?v=MkZ3TKbeDpI) about using the [ANT+ Plugin Sampler](https://play.google.com/store/apps/details?id=com.dsi.ant.antplus.pluginsampler) app.

PS: The [thisisant.com](http://www.thisisant.com) website is down (today ?) but the [ANT-Android-SDKs](https://github.com/ant-wireless/ANT-Android-SDKs) is available on GitHub.

**Comment by Lineflyer** [comment]
@pyrog If you are able to program such thing, feel free to contribute to c:geo. :)

**Comment by Lineflyer** [comment]
See #8883
