### ISSUE TITLE
Map flickering

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#3998]
The map (for offline stored caches) flickers when moving.

**Comment by Lineflyer** [comment]
@SammysHP Still happening?

**Comment by SammysHP** [comment]
Yes.

Open live map, wait until caches are loaded, disable live update (to prevent further update requests), move map.

**Comment by Lineflyer** [comment]
@SammysHP Still happening? :)

**Comment by SammysHP** [comment]
Meanwhile I switched to another device (Xiaomi Redmi Note 4) and it is still happening with v3. But it works fine with 0.9, thus closing.
