### ISSUE TITLE
Waypoints disappear when turning device

### ISSUE THREAD

**Issue by Lining30** [cgeo/cgeo#4010]
When I use the livemap an zoom in to 100m and turn the device, the waypoints/stages disappear. When turning back, the waypoints appear again.
When zooming to 50m, 20m or 10m the stages disappear after turning and do not appear again since I zoom out to 100m.
The configured number of caches to show waypoint was above the shown waypoints.

**Comment by Lineflyer** [comment]
Not reproducible for me anymore.
