### ISSUE TITLE
Improve Stored List Menu

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#4020]
The menu of the stored lists can be optimized. We should differ between select mode and normal mode.

I would prefer to have the menu items for selected items right at the main menu instead of a manage submenu. Others can be removed in select mode like show on map, delete list, rename list, new list (can create one on move selected).

What do you think? What's written in the actionbar specs?

**Comment by Lineflyer** [comment]
AFAICS we do not have a manage sbument anymore.
Feel free to reopen if I understood this wrong.
