### ISSUE TITLE
Log ID in GPX export

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4023]
From support mail:

Hello cgeo team,

I'm using export from cgeo and import to Locus. I noticed this issue

Log IDs differ from original log IDs

A log in c:geo export looks like this

```
<groundspeak:log id="">
<groundspeak:date>2014-06-07T00:00:00Z</groundspeak:date>
<groundspeak:type>found it</groundspeak:type>
<groundspeak:finder id="">Silent-Wolf</groundspeak:finder>
<groundspeak:text encoded="False">... TFTC</groundspeak:text>
</groundspeak:log>
```

The same log on the web appears in this way

```
initalLogs = {
"status":"success", 
"data": [{
"LogID":414148679,
"CacheID":952425,
"LogGuid":"4cca75f2-51d0-40a7-8949-05bed4246fef",
"Latitude":null,
"Longitude":null,
"LatLonString":"",
"LogType":"Found it",
"LogTypeImage":"2.png",
"LogText":"... TFTC",
"Created":"07/Jun/2014",
"Visited":"07/Jun/2014",
"UserName":"Silent-Wolf",
"MembershipLevel":3,
"AccountID":7327898,
"AccountGuid":"56c25237-d0e2-4195-a3cc-bfc41ea31734",
"Email":"",
"AvatarImage":"0c67df8e-d2b0-47d9-b337-702d7b798d56.bmp",
"GeocacheFindCount":2004,
"GeocacheHideCount":0,
"ChallengesCompleted":0,
"IsEncoded":false,
"creator":{
"GroupTitle":"Premium Member",
"GroupImageUrl":"/images/icons/prem_user.gif"},
"Images":[]
}, 
```

...When I use the c:geo export in other application (Locus) it may result in duplicate log entries. This happen when I access the Groudspeak data also in other way then through importing data from c:geo (e.g. by the live API).

**Comment by fm-sys** [comment]
@eddiemuc can you take a look at this issue? As you are introducing the parsing of LogID currently, this issue should be easy to solve now...

**Comment by eddiemuc** [comment]
> @eddiemuc can you take a look at this issue? As you are introducing the parsing of LogID currently, this issue should be easy to solve now...

Will do

**Comment by eddiemuc** [comment]
With PR #9065 9065, log id parsed from GC log code is now used as log id in GPX as well. If GC log code is not available, then c:geo-internal log id is used (as before)
