### ISSUE TITLE
Adding support for external  GPS receivers

### ISSUE THREAD

**Issue by mrvdb** [cgeo/cgeo#4032]
When geocaching I often use an external GPS receiver (in my case a BT-359) to improve my tablets battery life and have better positioning results. 

Using the 'mock locations setting' and a bluetooth GPS provider (like: https://play.google.com/store/apps/details?id=googoo.android.btgps ) this is doable but has a number of drawbacks.

- I'm not sure if the 'mock locations' setting is available for everyone.
- some apps do not allow 'location spoofing' which they equate to having set the 'use mock locations' setting to true.
- the system works when the bluetooth gps provider replaces the internal GPS, which confuses a lot of other apps apparently. 
- i'm not sure what is happening with the other internal location providers (network, gsm) when the internal gps is replaced by the bluetooth provider, but I'd like these things to be undisturbed if possible.

Ideal situation:
1. Let the bluetooth gps provider create a new location provider instead of replacing the gps
    (https://play.google.com/store/apps/details?id=com.globalsat.android.gps.bluetooth.provider claims to support both these methods )
2. Have a setting in cgeo where I can select which gps provider to use.
   (Walhalla: have cgeo use multiple providers)

I understand this is far from trivial to implement. 

Questions:
1. Is there an alternative which gives me roughly the same results?
2. What would need to be done to implement this? For example: would the implementation be able to borrow from existing implementations or would I have to start from scratch?
3. Are other people interested in this?

**Comment by Lineflyer** [comment]
Do we see any need for changing the strategy here or can we close this "Feedback" issue?

**Comment by akkatracker** [comment]
Just going through old issues to see if any can be closed or worked on. I suspect @Lineflyer may want to close this one.

**Comment by Lineflyer** [comment]
As originally written this can be closed.
