### ISSUE TITLE
Refresh a cache on a filtered list removes filter

### ISSUE THREAD

**Issue by ludoo0d0a** [cgeo/cgeo#4053]
Steps to reproduce :
  * Go in a list.
  * Filter items (like type unknown)
  * Only unknown items appear and filter's title is showing
  * Long press a cache to refresh it.

After refresh, a list reload occurs without filter, but filter's title is showing is still there.

**Comment by Lineflyer** [comment]
This is still reproducible with 2015.04.07-NB

**Comment by kumy** [comment]
Fixes for #4834 solved this too.
Feel free to reopen if needed.
