### ISSUE TITLE
Show the number of people having a cache on watchlist

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#4058]
I have a feature request that I think many users are missing.
As a die-hard FTF hunter it would really be great to be able to see how many that are having a cache on their watchlist. Many FTF hunters tend to place newly published caches on watchlist to be notified via email if/when the race is lost.

The text in the Watchlist section might read 
"Cache is on your watchlist (7 in total)" or
"Cache is not on your watchlist (7 in total)"

**Comment by Lineflyer** [comment]
Assigning "Non-collab" as @ThibaultR started working on this.

**Comment by samueltardieu** [comment]
Merged.
