### ISSUE TITLE
Add support for Android Wear

### ISSUE THREAD

**Issue by jhbruhn** [cgeo/cgeo#4063]
Adding support for Android Wear would be a really great feature. I'm thinking of using it's integrated compass to show to the geocache together with the phones GPS sensor. I'm not sure though how well developing for Android Wear works with Eclipse.

**Comment by Lineflyer** [comment]
@culmor30 Would it be the right time and would you be ok if we post a link to your app on our facebook page? If yes, any special information we should post along with it? You can also answer via IRC.

**Comment by culmor30** [comment]
I'd be honored :)

Can't think of any special information that should be included other than the [gplay link](https://play.google.com/store/apps/details?id=com.javadog.cgeowear). Feel free to use any of [my image assets](http://imgur.com/a/bbmHY) if you like. I'll also be releasing an update with watch compass support soon, so you can mention that if you want to.

Thanks for your help everyone!

**Comment by Lineflyer** [comment]
@culmor30 

Posted!
https://www.facebook.com/android.geocaching/posts/10152942865430091
