### ISSUE TITLE
Global type filter change → live map not updated

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#4091]
Enable the global filter for "traditional caches", start the live map and look around. Only traditional caches are shown. Go back, disable the filter, back to live map again. For tiles, that were loaded during the previous live map session, the data is not refreshed, only traditional caches are shown. Zooming in or out and other types are shown as expected.

**Comment by Lineflyer** [comment]
I can no longer reproduce as things changed meanwhile (maybe the new GS map or some other structural changes). Works for the mentioned scenario for me.
