### ISSUE TITLE
Wrong division with MediaTek CPUs

### ISSUE THREAD

**Issue by murmeltier4** [cgeo/cgeo#4097]
After Updating Yoga Tablet Lenovo B6000-H to Android-Version 4.4.2 the offline installed OSM Maps are not displayed correctly. Sometimes only some parts of the map are displayed, but mostly nothing is shown. Zoom in and out makes it more worse. If in Map the option "Enable live" is selected, symbols for geocaches were displayed (if at all) in one single column in the middle of the map. Similar problem by using online "OSM: Mapnik" and "OSM: Radfahrerkarte". "Google: Map" and "Google: Satellit" is working correctly.
See attached image for example.
![cgeo_osm_map](https://cloud.githubusercontent.com/assets/1106079/3713593/46164736-1576-11e4-86de-230f04e4903f.jpg)

**Comment by cerisara** [comment]
Another affected device: Wiko Goa.
I uninstalled the Google play version, and installed the latest non-jit build link above, and it's working fine.
Could you please give an update about what's the plan for the future releases/builds ? What about systematically distributing another application: c-geo-nonjit.apk ?
Thanks !

**Comment by SammysHP** [comment]
We cannot simply distribute a special version via the Play Store. The only possibility (as posted above) is to add a warning for affected devices and provide a special version on our website.

@rsudev said that the build is working - so let's check it… I don't know if you can access this deep link, but try it.

http://ci.cgeo.org/job/c-geo-nightly-nojit/ws/main/bin/cgeo-release.apk

**Comment by cerisara** [comment]
Thanks, I can access the link, I installed the non-jit-march version, and it works.
I personally don't care about play store. So your solution is fine. I'm just pushing for this non-jit build to be
indeed systematic (by adding it alongside the normal build in the standard maven/gradle/... release target) and that it is also automatically deployed on your website with a visible link. If so, then I'm more than happy ;-)

Btw, does just-in-time compilation *really* make a difference ? Did anyone evaluated the gain in speed ? Well, I guess so, otherwise, people wouldn't ask for it...
Thanks a lot !

**Comment by SammysHP** [comment]
Yes, there is a difference, but I have not measured it for c:geo.

The link to the non-jit version stays valid, a version is built automatically every night (in Europe).

**Comment by SammysHP** [comment]
OK, let's close this. We have the non-jit nightly build running and that's all we can do. If it works in the future, it will be a side effect of other changes (e.g. Mapsforge update, ROM update etc.).

**Comment by cerisara** [comment]
Too bad the link to the no-jit version is not working any more... :-(

**Comment by kumy** [comment]
@cerisara Official link are on page http://www.cgeo.org/development

http://download.cgeo.org/cgeo-nightly-nojit.apk
http://download.cgeo.org/cgeo-nojit-legacy.apk
http://download.cgeo.org/cgeo-nojit-release.apk

**Comment by cerisara** [comment]
Thanks a lot !
