### ISSUE TITLE
No visible indication that picture has been selected for logging

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4109]
Before we shifted all actions of the logging view to the actionbar the user was able to see, that he succesfully selected a picture for the log before sending it by the on screen button "Send log & Picture".  
As this button is no longer implemented there is no visual indication whether or not a picture will be send with the log. 
It would be good to indicate this somewhere or even show the preview of the picture somewhere on the logging screen, so that a user can review his complete log before sending it.

**Comment by kumy** [comment]
I imagine we can reuse the `AbstractViewPagerActivity` to present image((s) #2734) in a different tab.
User should also have the possibility to edit/remove attachment(s) before sending.

**Comment by rsudev** [comment]
Sounds good to me

**Comment by Lineflyer** [comment]
This has been solved implicitly by the new logggin dialog with picture selection including preview.
