### ISSUE TITLE
Support log pictures for OC

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4137]
Users wish:
Support uploading of a picture with the log like for gc.com.

Don't know if OKAPI supports it.

**Comment by Natureshadow** [comment]
OKAPI does not seem to support this feature currently.

**Comment by following5** [comment]
we are working on it: https://github.com/opencaching/okapi/issues/360

**Comment by following5** [comment]
Log images are now supported by OKAPI:

* **services/logs/images/add** appends a new image to a log entry.
* **services/logs/images/edit** changes the properties of a log image.
* **services/logs/images/delete** deletes a log image.
* **services/apisrv/installation** tells you the maximum filesize and recommended max. dimensions of uploaded images.

**Comment by following5** [comment]
Sad to see that one and a half year later, Opencaching log image upload is still not implemented in c:geo. This means that neither Webcam nor Safari caches can be logged "Found" using c:geo.
