### ISSUE TITLE
HTML tags shown in logs on OC.pl

### ISSUE THREAD

**Issue by Kucharskov** [cgeo/cgeo#4139]
Device: Xperia SP
Android: 4.3
C:geo: 2014.08.06-NB-e50fbb4

Bug description: Last time i make an log with some enters. When i check my log at webpage i see many `<br />` tags.
In my opinion thats "/" mark cus `<br>` is correct.

Regards!

**Comment by Lineflyer** [comment]
According to https://code.google.com/p/opencaching-api/issues/detail?id=324 the problem should be fixed.
