### ISSUE TITLE
Login error message while still logging in

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4153]
Starting with 2014.08.09 or 10:

On startup of c:geo while c:geo is still logging in to geocaching.com (Logging in shown in status bar) the toast for ¨c:geo can not login and works offline...¨ is shown.
Log will follow later

**Comment by Lineflyer** [comment]
Assigning myself for a retest.

**Comment by samueltardieu** [comment]
Confirmed. The message is too broad, and should just say that login on a platform failed, not that it implies offline mode.

**Comment by fm-sys** [comment]
@Lineflyer I never noticed it. Is this issue still reproducible?

**Comment by Lineflyer** [comment]
There have been quite some changes at this point in the past. AFAIK the toast mentioned in the inital post is no longer used but replaced by another permanent message. 

I cannot retest it, as this would require to force a login fail on one platform while the other is OK. Would require some firewalling or similar.

**Comment by fm-sys** [comment]
Today, I tried to log in to extremcaching with some random credentials. Indeed, the error message is obviously wrong and the bug still exists. 

![Screenshot_20210105_125120_cgeo geocaching_copy_270x585](https://user-images.githubusercontent.com/64581222/103643368-d8518380-4f54-11eb-932e-0c47d4e2bec9.jpg)

**Comment by Lineflyer** [comment]
nope...that is because of #9652

**Comment by fm-sys** [comment]
Sorry, you are right. Will have to do a retest when #9652 is fixed...

**Comment by fm-sys** [comment]
> On startup of c:geo while c:geo is still logging in to geocaching.com (Logging in shown in status bar) the toast for ¨c:geo can not login and works offline...¨ is shown.

@Lineflyer IIRC you are using extremcaching. Did you saw/see such a toast in the current version? 

Otherwise the original issue is most likely fixed...

**Comment by fm-sys** [comment]
OK. I have checked it in code, but as error messages are nowadays handled as per connector this issue was fixed indirectly and does no longer exist...
