### ISSUE TITLE
Doubled restore dialog after fresh install

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4170]
2014.08.13-NB:
- Install c:geo
- Start c:geo
- Enter userdata for gc.com
- Press back to get to the main menu
- Restore dialog for exisiting backup is shown
- Select OK
- Confirmation is shown, select OK
- Restore dialog is shown again

**Comment by Lineflyer** [comment]
Still open with 2019.11.28

**Comment by fm-sys** [comment]
Confirmed. I will (try to) fix this with #8959...
