### ISSUE TITLE
Database should be cleared when changing username

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4197]
When changing the username in the application, some information in the database becomes obsolete (found, favorite, friends, etc.) and cannot be easily rebuilt without doing many requests to the various connected sites.

The user should have the choice to partially erase the database (connector dependent) when switching from a valid logged in user into another one on any connector.

**Comment by Lineflyer** [comment]
I would not recommend to do that. As we do not support multiple users quite some users just change the username (e.g. to another family member) and redo their logging. 
Therefore closing this.

**Comment by samueltardieu** [comment]
People should learn to use multiple *phone* accounts, especially since cgeo is free they don't have to pay several times for it to install it on multiple user instances.

**Comment by Bananeweizen** [comment]
Side note: You can share paid apps between multiple accounts on the same device, as far as I'm aware. http://android.stackexchange.com/questions/60087/how-do-i-share-apps-between-users-in-android-4-4-kitkat
