### ISSUE TITLE
Location lookup

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4198]
When looking up a location, cgeo then requests the closest 20 caches per connector. I would like to see two buttons instead of one in the search activity, one of them switching to live map around the looked up point.

Right now, my process when I'm going somewhere remote is: search by location, then when I get the list map this location then enable live map. I'd like this to be one step.

**Comment by Lineflyer** [comment]
This has been implemented as described in #7228 as a fix of #6400
