### ISSUE TITLE
zoom map so that all waypoints are visible initially

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#421]
When opening a map, the last zoom level is used. For caches with waypoints this means that sometimes not all waypoints are visible. I suggest to reduce the zoom level in those cases in such a way, that all waypoints of that cache are initially visible. As long as I don't invoke the map for only one certain waypoint of the cache, I generally want to have an overview of the complete "waypoint network" of the cache. E.g. last week I had a multi where the numbered waypoints where ordered very bad to reduce the overall way and I nearly didn't notice that starting with waypoint 9 instead of 1 would be better, because I didn't see all the waypoints first.

Does this sound reasonable for others or do you have different strategies how to work with the map for multis or other caches with waypoints?

**Comment by Lineflyer** [comment]
See #7949
