### ISSUE TITLE
waypoint name imported from personal note

### ISSUE THREAD

**Issue by michag86** [cgeo/cgeo#4228]
At the moment there is no way to specify the name of a waypoint that is imported from personal note.
But specifying the waypoint type works good if I have a Personal note like "PARKING Nxx°xx.xxx Exxx°xx.xxx
Stage Nxx°xx.xxx Exxx°xx.xxx"
But in some cases I have a cache with more than three waypoints in my personal note, what sometimes is very confusing, if they are just named "personal note 1, personal note 2,...". 

If I can create an personal note like:
"PARKING Nxx°xx.xxx Exxx°xx.xxx Parking
Stage Nxx°xx.xxx Exxx°xx.xxx Stage 1
Stage Nxx°xx.xxx Exxx°xx.xxx Stage 2"
it would be very nice if the string after the coordinates are imported as waypoint name.

But there would be a problem: What is the end of the string?
I think a line break and a maximum string length, if there is no line break, would be a good idea.

**Comment by Lineflyer** [comment]
@Bananeweizen Didn't you tell last weekend, that this feature is already implemented. Seems it is not.

**Comment by KoalaBear84** [comment]
At least some functionality is implemented, I guess I've seen it working for at least a year. But it only detects "Final" for me. Didn't test anything like stage. But did test "Park", "Parking" which unfortunately looks like not working, at least not marked as parking.

Would be nice. I don't care which solution is taken / accepted.

Coords WaypointType = N 12 34.567, E 1 23.456 Park
Coords (WaypointType) = N 12 34.567, E 1 23.456 (Park)
or
WaypointType Coords = Park N 12 34.567, E 1 23.456

Luckily my used coords notation is working perfectly :)

**Comment by rsudev** [comment]
The waypoint type is guessed from the characters *before* the coordinates as mentioned above. It is tried to match with the phone locale specific and the English type name. So for a parking spot you can use 'Parking', but also on a German phone 'Parkplatz'

**Comment by KoalaBear84** [comment]
Hmm, indeed. This is strange, tested it multiple times. Maybe needed to drop & refresh. Thanks

This now works:
Parking: N 12 34.567, E 1 23.456

**Comment by michag86** [comment]
Nothing new here? There is still no way to define the Waypoint name (not the type) that is created from personal note?

**Comment by SammysHP** [comment]
We have 467 open issues. We have 2-8 developers (depending on activity). So please don't expect instant issue resolving. ;)

**Comment by okainov** [comment]
BTW currently there is already at least one type parsing: if you type `final` before the coordinates - it will be added as final.

**Comment by Lineflyer** [comment]
@okainov Yes, as written above in https://github.com/cgeo/cgeo/issues/4228#issuecomment-111717557 several waypoint types are already supported if written before the coordinates.

**Comment by okainov** [comment]
@Lineflyer it would be nice to mention this somewhere apart of random Github issue comment :) Because I found this by pure luck and was really surprised.

**Comment by Lineflyer** [comment]
Waypoint type support from personal note has meanwhile been documented here:
https://manual.cgeo.org/en/notecoords

**Comment by Lineflyer** [comment]
Yes, that is more than sufficient.
