### ISSUE TITLE
Direction arrows cut off in lists

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4239]
Just seen this while producing screenshots:

Don't know if it is worth to fix at it might strech the lists and thus have less caches shown at once.

![6](https://cloud.githubusercontent.com/assets/949669/4062425/b4384696-2dff-11e4-8e7c-81338b816366.png)

**Comment by Lineflyer** [comment]
Still reproducible with 2017.02.12-NB

**Comment by Lineflyer** [comment]
Outdated, respectively mentioned in other issues after UI overhaul.

**Comment by moving-bits** [comment]
This got fixed with #11131
