### ISSUE TITLE
On devices with white skin our menu is completely white

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#4242]
See attached screenshots. 
HTC Explorer with Android 2.3.5 and HTC Sense 3.5.

![p8270135](https://cloud.githubusercontent.com/assets/832407/4065212/ae8d21c6-2e18-11e4-8daa-a43a20a9cd8a.JPG)
![p8270136](https://cloud.githubusercontent.com/assets/832407/4065210/adfb20b4-2e18-11e4-8198-f628620b7b2f.JPG)
![p8270137](https://cloud.githubusercontent.com/assets/832407/4065211/ae08ab58-2e18-11e4-8671-1c1ffe3ec534.JPG)

**Comment by Lineflyer** [comment]
Assigned myself for a retest.

**Comment by Lineflyer** [comment]
With version 2015.03.31 on a HTC WIldfire S A510e running Android 2.3.5 I can not reproduce the issue.
The menus shown in the screenshots as well as all others I have tested (main menu, lists) are shown well in white on black.

I also assume that investing more time here for Android 2.3.5 would be not meaninful, so closing this.
