### ISSUE TITLE
Context menu not updated when selecting caches

### ISSUE THREAD

**Issue by engycz** [cgeo/cgeo#4256]
On my phone Samsung SII (4.1.2) when on Stored screen enabling select mode by sliding the cache or selecting the caches, the menu is not updated - remains "Select mode" instead of "Exit select mode" and the count for deletion is also not updated. On my Samsung Galaxy Tab this works as expected (4.4.4)
c:geo updated to latest 2014.08.28.

Android 4.1.2 on Samsung Galaxy SII
![sgs2](https://cloud.githubusercontent.com/assets/6651271/4082775/f1dfb308-2ef4-11e4-9b4f-ccb8fe958357.png)

Android 4.4.4 Cyanogenmod 11
![sgtab](https://cloud.githubusercontent.com/assets/6651271/4082778/f9aa7c26-2ef4-11e4-9e9b-807a9f434932.png)

**Comment by Lineflyer** [comment]
Not reproducible anymore with 2016.01.19.
