### ISSUE TITLE
Bottom bar - Android guidelines

### ISSUE THREAD

**Issue by ludoo0d0a** [cgeo/cgeo#4259]
I'm happy to see this new action bar. Great work !

But now menu is really long and full of text (no icon).

Why not to use a bottom bar? 
As said in Android guidelines (https://developer.android.com/design/patterns/actionbar.html#considerations-split-action-bars) ,

> To display actions and, if necessary, the action overflow, use the bottom bar.

All selection copy/move stuff can be moved into this contextual bar.
Long press on item (here the cache) to activate selection mode is a common pattern.

A really good example is EsFileExplorer . There are plenty contextual actions with icons without lost usability.

**Comment by akkatracker** [comment]
Considering this is not really a part of the design spec anymore should this be closed? @lineflyer
