### ISSUE TITLE
Close search on click in main screen

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4261]

**Comment by Lineflyer** [comment]
Assigning "non-collab", See #4736

**Comment by Lineflyer** [comment]
Removing assignment.
@Bananeweizen In fact the search result closes if I click outside of it on the main screen. However the search field (and keyboard) remain open.
Do you consider this issue still open?

**Comment by Lineflyer** [comment]
See my previous comment. As the main issue has been solved with #4736 and no objections came in, lets close this as well.
