### ISSUE TITLE
Auto disable HW acceleration on phones

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#4265]
Devices incompatible with HW acceleration

When you add one, put it to the end of the list, do not set a "fixed in code" date or check mark (unless you fixed it already). The "Model number" must match exactly what it is "Settings/About the phone/Model number".

Device | Model number | type of problem | Fixed in code
--------- | ------------------ | ------------------ | ------------------
HTC One X | HTC One X | Blurred fonts | :white_check_mark: (2014.08.28)
Samsung Galaxy S3 mini | GT-I8190 | Blurred fonts | :white_check_mark: (2014.08.28)
Samsung Galaxy Young | GT-S6310L |  | :white_check_mark: (2014.08.28)
Samsung Galaxy Tab 3 | GT-P5210 | Blurred fonts |  :white_check_mark: (2014.09.18)
Sony Xperia U | ST25i | Main screen not visible |  :white_check_mark: (2014.09.18)
bq Aquaris 5 | bq Aquaris 5 | Blurred fonts |  :white_check_mark: (2014.09.18)
HTC One S | HTC One S | Blurred fonts |  :white_check_mark: (2014.09.18)
Samsung Galaxy Trend Plus | GT-S7580 | | :white_check_mark: (2014.09.18)
Samsung Galaxy SII Plus | GT-I9105P | Blurrend fonts | :white_check_mark: (2014.09.18)
Unknown | A1-810 | Blurred fonts | :white_check_mark: (2015.07.08)
Samsung Galaxy S4 mini | GT-I9195 | Blurred fonts | :white_check_mark: (2015.07.08)
Samsung | GT-I8200N | Blurred fonts | :white_check_mark: (2015.07.08)

**Comment by Lineflyer** [comment]
@samueltardieu Did you (or someone else) add the remaining models to the code?

**Comment by Lineflyer** [comment]
Added one device.
Can someone include those devices (not yet checked as done) to the exclusion list for HW-acceleration?

**Comment by Lineflyer** [comment]
Done

**Comment by Lineflyer** [comment]
No new exceptions for quite a long time and no complaints like this on support. Closing for now.
