### ISSUE TITLE
Option to download PQ from list

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#4267]
Currently we have PQ reader, that displays 20 at the time.
The most seen usecase I see from users is. They make PQ, download it, import it and then "refresh all" as PQ just does not contains all the informations a normal cacher needs in c:geo.

The request is. Have an option to directly download all caches from PQ reader. Not just 20 at the time.

**Comment by samueltardieu** [comment]
The code from @pstorch is merged. Two minor issues: the prompt text looks a bit long and goes out of the box on my Nexus 5, and the success message at the end references `downloadpq.ashx` which should not be exposed to the user.

**Comment by pstorch** [comment]
Maybe the prompt text can be shortened. The context (pocket queries) should be clear at this point. 
What about:
Title = "Download available" 
Message = "View cache list or import?" 
Buttons = "View list" and "Import" 

The success message is a little bit buried. The name of the PQ is last know when creating the intent for the CacheListActivity. Then only the uri is passed. 
The success message uses the getSourceDisplayName() from ImportGpxZipAttachmentThread which returns LastPathSegment from the uri. 
The ideal solution would be to pass the name along, but would cause some more changes along the call hierarchy. A quick fix would be to filter getSourceDisplayName() for http uris.

**Comment by Bananeweizen** [comment]
Since I have converted the selection dialog to a list, it would now be possible to have dedicated buttons for preview or download directly on each list item, thereby avoiding the first dialog completely.

**Comment by Lineflyer** [comment]
Will relocate the open improvement to a new issue.
