### ISSUE TITLE
Longpress cache icon on map to directly load details

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4295]
From Facebook and may be interesting?!

May it be possible to show the detailed informations for a cache through longpressing (about 400ms) an icon of a cache on the livemap?

**Comment by Lineflyer** [comment]
I do still really like this idea. But seems no one else.

**Comment by Lineflyer** [comment]
Stumbled upon this old issue and still think its a great shortcut....just in case someone wants to take a look into it :)

**Comment by moving-bits** [comment]
@Lineflyer 
This clashes with "add to individual route" meanwhile, so I propose to close this issue.

**Comment by Lineflyer** [comment]
Jepp.
