### ISSUE TITLE
Our main screen remains transparent

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#4310]
On nexus5 Android 4.4.4 stick rom. Disabling HW acceleration does not help.

![screenshot_2014-09-03-20-22-24](https://cloud.githubusercontent.com/assets/832407/4139236/ad9f7ac2-3398-11e4-814e-7c57c1590656.png)

**Comment by Lineflyer** [comment]
No feedback from this user on support and no more occurences. Closing.
