### ISSUE TITLE
Add PlayStore description to Crowdin 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4316]
Splitted from #3602 

Currently the translations for the PlayStore description of c:geo and the plugins are done manually (See #2339 for current approach).

Recently Google introduced an API which should allow to automate description syncronisation and therefore might enable us to include these strings on crowdin:
https://developers.google.com/android-publisher/

**Comment by Lineflyer** [comment]
Assigning myself here:

After the new integration to Crowdin has been set up, it should be easy enough to include the description for translation.

I consider the synchronization between our repository and Google Play as optional, as these texts usually do not change so much over time. So its more or less a one time work.

**Comment by Lineflyer** [comment]
This issue is now on my todo list.
Looking at the directory structure of this repository I am unsure where to place the sources and translations for the playstore description.

I am a friend of a rather structured approach of directories...but the current structure became quite confusing over time as I cannot see a clear structure. Maybe its another task to clean this up a but..

However, where to place such supporting files?
I suggest to create a new directory on root level where we could additionally to the playstore descriptions also collect all resources which are used outside of building/maintaining the app itself (such as app icon for playstore, description for playstore, screenshots for playstore, title pictures from social media, raw image storage, etc.)
Any suggestions for naming and structure?
What about `/assets/` with subsequent subdirectories for each topic (e.g. `assets/playstore/description/`)?

I would then create this while working on this issue and we could later on also clean up a bit by moving similar files to this structure?

Thinking of the contacts-plugin which is part of this repository. Shall we have a desperate structure for these kind of resources below the contacts directory or put everything in one structure?

Sorry to ask such "simple" questions, but I do not want to increase the mess by just adding other random directories to the repository and my understanding of all the existing structure is still rather low.

**Comment by bekuno** [comment]
We have in the project structure 3 subprojects, no project tree in the root folder.
These are (see settings.gradle)
- /main
- /cgeo-contacts
- /mapswithme-api

The play store description reffers to a dedicatd project. Therefore I suggest to use a folder structure below this folders.
We can for c:geo use the folder /main/project as base for aditional project informations. Here reside already some other additional information.

**Comment by Lineflyer** [comment]
BTW: A potential interface from our repo to Google Play could be this one: https://github.com/googlesamples/android-play-publisher-api/blob/master/v3/java/src/com/google/play/developerapi/samples/UpdateListing.java

**Comment by Lineflyer** [comment]
@cgeo/team 
For easier overview I suggest to switch off the feature, that Crowdin uses the english (source) placeholders for untranslated strings.  
Especially when it comes to playstore texts it makes no sense at all. AFAIK there should also be no technical issue for the app strings as the system will fallback to english for all strings not contained in localized files. Any objection?

BTW:
This mode is already in use on the WhereYouGo repo.

**Comment by Lineflyer** [comment]
> For easier overview I suggest to switch off the feature, that Crowdin uses the english (source) placeholders for untranslated strings.

As I did not get any general objection I will switch it off now for further testing.
