### ISSUE TITLE
Add changelog to Crowdin

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4317]
Splitted from #3602:

It would be helpful if the release notes could be made available in several languages instead having it only in english.

**Comment by Lineflyer** [comment]
As discussed in #3601 we could now theoretically add `changelog_master.xml` and `changelog_release.xml` to be translated on Crowdin.

There might still be some obstacles:
- The strings are flagged as `translatable=false`. This needs to be removed
- Is there any other prerequisite or just let them translate and place localized files into the appropriate `values-*` folder?
- `changelog_release.xml` is only maintained on `release` branch. It needs to be checked if it makes sense to add this branch to the Crowdin workflow just for this single file.

**Comment by moving-bits** [comment]
If we want to use Crowdin for translation of changelog, we should save every changelog entry as separate string. This can easily be done by using a `<string-array ...>` entry, then every changelog entry is an `<item>...</item>` element within this array. (See WhereYouGo:strings_mapsforge.xml for an example.) Crowdin can handle this and will present each `<item>` as separate string to translate.

I'll give it a try as test. (Transforming the master changelog and updating the routine to display the changelog.)


As for the timelag rsudev had mentioned: This should be mostly fine for `master` branch, as normally things evolve over a longer period of time, and with our new automized Crowdin integration we are much more in time with translations.

For release branch I would skip translations, if it gets too complicated. Most of the texts come from master branch anyway and is translated already.

We still need to define the workflow for handling the changelogs when we have `master` and `release` branches in parallel. Maybe it's the same as today, haven't thought through it yet.

**Comment by Lineflyer** [comment]
> If we want to use Crowdin for translation of changelog, we should save every changelog entry as separate string. 

Not necessarily. We could also enable the crowdin feature `content segmentation`, which will automatically divide them into translation portions.
I have applied that to the Playstore description of WhereYouGo already and it works rather good.

**Comment by Lineflyer** [comment]
Will most likely be implemented in https://github.com/cgeo/cgeo/pull/10640

**Comment by Lineflyer** [comment]
This has been implemented meanwhile (see above).
