### ISSUE TITLE
Direction in compass-view

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#432]
I noticed a strange behavior in compass-view:

- select using of compass for direction
- while standing and walking the compass is used
- while driving (>20 km/h?) the gps is used (rotation of the phone doesn't change the direction of the arrow, on standing it jumps back to compass mode), the selections in the menu stays the same

I don't know if this is a "feature" of android or a bug in our access to the location-service.

**Comment by Lineflyer** [comment]
Quite some time ago a manual selector has been added to the compass view to distinguish between GPS+Compass or only GPS.
