### ISSUE TITLE
History should not include old finds, just recently found caches.

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#4334]
This is a bug #2906 that once was fixed but now has occured again in recent nightly builds.
This was confirmed as a bug by @Lineflyer and fixed by @samueltardieu 
Today I use NB-398ff09 

The History page sometimes include caches that you have found a long time ago, if you have recently viewed their cache description.

I will try to reproduce when this occurs
1. Let's first empty the History by pressing Overflow->Clear history->Confirm
2. Next pick a cache that you have not logged yet, i.e. from the Nearby page
3. Log your visit but only save an Offline Log
4. Go back to the History page and the recently logged cache should be listed.
5. Next pick a cache that you already have logged for a long time ago, i.e. from the Nearby page
6. Open up the cache description page
7. Go back to the History page and both the newly offline logged cache and the old cache are listed

**Comment by MrYaz** [comment]
I have talked to a lot of friends lately about this behavior and it seems like they all agree with me that it is more a bug than a feature. You should try to fix it if possible.

**Comment by MrYaz** [comment]
It seems like this issue has been fixed in 2015.05.02-NB-341c4a1.
Can anyone confirm?

**Comment by MrYaz** [comment]
Unfortunately I celebrated too early...

I have created an offline list with all of my founds.
If I view one of the caches in my offline list, it does not appear in the History list.
But as soon as I refresh the cache details the cache reappears in the History list.
Also if a old found cache is not stored in any offline list the cache appears in the History list as soon as you view the cache.

So it seems like as soon as an old found cache is downloaded or refreshed from gc.com it reappears in the history list again.

**Comment by SammysHP** [comment]
Link to #3891.

**Comment by Lineflyer** [comment]
@pstorch: You are now very familar with the conditions under which a caches shows up in the history. 
AFAIR it is still the case that loading a found cache will make it show up in history because (in my basic words) we store the users found dat in the same field that we use to collect caches for the history.
Correct?

Can we split that....recently I had users not understanding why the c:geo local history shows "old found" caches out of nothing.

**Comment by pstorch** [comment]
@Lineflyer yes, you are right. Logging via c:geo (online or offline) sets the `visiteddate`. Reading a geocache from the website or GPX we set the `visiteddate` for found logs.

But splitting? It is still the found date. So semantically it is the same attribute. 
We could define the history as "recently logged". But what is "recently"? Last 7 days? Last 100 Caches? What if a user keeps an offline log longer and then the cache drops out of the history?

It would make more sense if we split up the semantics like proposed in #4672:
- recently viewed (in cache details)
- offline logged (fieldnotes)
- found caches
- trash can (recently deleted)

**Comment by Lineflyer** [comment]
Closing in favor of #4672
