### ISSUE TITLE
Sorting selector sometimes not prefilled

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4335]
2014.09.08.-NB:

Followup of #3914 and #4260 

Steps:
- Clean start c:geo (no sorting set for this session)
- Open list with non-event caches 
- Check sorting menu, sort by distance is active
- Change to a list of event caches
- Default sorting changes to event date (=hidden date) automatically
- Check sorting menu 
--> No entry is selected but should be "Hidden date"

Also related to #4321

**Comment by Lineflyer** [comment]
@kumy If I read the commit and PR history correct, your fix proposal wasn't really merged, was it?

**Comment by kumy** [comment]
IIRC merging #4321 would fix this issue.

**Comment by Lineflyer** [comment]
But #4321 is no PR. I think you provided that fix in your local repo but did not send us a PR until now.

**Comment by kumy** [comment]
You're right.
It's still on branch issue-4221-bis in my repo. As I 
I'll propose the pull request. On which branch am I supposed to merge ? master ? release ? I don't want  make a mistake again...

**Comment by rsudev** [comment]
I figure we should go to master with this as we prepare a new feature release? Then you should rebase this on current master and re-test. Thereafter either force push to the same branch or push a new one and issue a PR from there.
I figure @samueltardieu has already made a review?

**Comment by kumy** [comment]
Here is the PR rebased uppon `master`
