### ISSUE TITLE
GPX import file scan does not return all possible matches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4343]
2014.09.10-NB
- I set the GPX import dir to a dir where downloads of the system are saved
- I downloaded the same PQ (via pocket query generator) multiple times
- The files are named 14080613.zip, 14080613(1).zip, 14080613(2).zip, and so on
- If I select "Import" on a list the directory is scanned but only 14080613.zip is listed, the other files not.

Addition:
- If I only have the file 14080613(1).zip no file is listed on the import selection
  --> Seems we have a problem with the `(` ?

**Comment by fm-sys** [comment]
@eddiemuc will this issue still be relevant together with SAF?

**Comment by eddiemuc** [comment]
> @eddiemuc will this issue still be relevant together with SAF? 

Is this about an import dialog for PQ-files? Haven't seen such a dialog so far, maybe I missed something to migrate here?

I am not sure I understand the issue. If this is about which files are shown to be selected in the file picker dialog: this can only be restricted by mime type with scoped storage.

**Comment by Lineflyer** [comment]
No, this is no longer of relevance:
While the initial problem might still be there, it will be superseeded by the file picker via SAF shortly.
@eddiemuc That is where you removed "Import GPX" and replaced it with "Import from Android".
