### ISSUE TITLE
Create parameterizable script for ftp upload

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#4344]
Instead of the current hardcoded ftp upload script there should be a version that takes the source and target file name for the upload as parameters.
(Already discussed with mucek4 on IRC today)

**Comment by rsudev** [comment]
Update: As I am personally seemingly not able to create the script itself I sent my proposal to @mucek4 last Friday

**Comment by mucek4** [comment]
Sorry @rsudev I have seen the email. Ont thing bothers me that it deletes the file on FTP that is passed as parameter to the script. That could be problematic.

**Comment by rsudev** [comment]
You are right @mucek4, I didn't think of that. This could be mitigated by having all the apks in a special folder and restricting write permissions for the upload user to that folder.

**Comment by Lineflyer** [comment]
@mucek4 Is that script in place and we can close here? I think it is...

**Comment by kumy** [comment]
We don t have any problem for a long time. I think we can close.
