### ISSUE TITLE
Show favorite point percentage in cache details

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4346]
From support mail:
It would be nice to show the favorite point percentage (next to the absolute favorite points) on the cache details page. As it is already possible to sort by percentage the info should be there.
## 

As far as I know we use a self calculated value (all logs over favorite points) to calculate the sorting (?!).
We could/should instead parse the value shown on gc.com which is more accurate (i.e. only counting premium logs AFAIK).

**Comment by Lineflyer** [comment]
+1 from support mail yesterday.

**Comment by gcPhil** [comment]
Also I like to see the favorite percentage on the cache details page.

It is even possible to sort for favorite percentage, so why isn't it possible to display it? (And wasn't it even possible in the past?)

(If there is any limitation that makes this impossible, maybe it could be a solution to display it only after a tap on the favorite point number.)
