### ISSUE TITLE
Allow adding favpoint in logging activity

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4347]
From support mail:
Right now I have to first log the cache and afterwards add it to my favorites on another page of c:geo. It would be better to have the option to add it, right on the logging screen like it is realized on the website (and in c:geo for voting on gcvote). It somehow makes sense, to decide about favoriting the cache while logging it, rather than having to do it manually afterwards.

**Comment by Lineflyer** [comment]
Quick note for this:
Quite often people on support mail ask for a feature to add favorite points to a cache. This shows to me, that people don't realize that the functionality is already there as they probably expect to find it while logging (like on the website and in other geocaching apps)...so +xx from support mail

**Comment by Lineflyer** [comment]
The last weeks we received several mails on support and also on the Playstore rating system from people unaware that c:geo is already supporting favorite points as it is only on the detail page but not possible to add them while logging. 
So our current implementation seems to be an example of a not user friendly implementation.

Just as a reminder for this issue.

**Comment by Lineflyer** [comment]
+many from talks on GeoXantike

**Comment by Lineflyer** [comment]
@madankb 
In case you look for more requests you are willing to work on, I would really like to see this being implemented as many users fail to recognize that c:geo can mange favorite points due to our current implementation.
So...just a small hint in case you are interested in this.

**Comment by madankb** [comment]
@Lineflyer I can work on this request. Just recap of the issue, add to favorites option is available in detail page, it will be user friendly to include add to favorites in "log visit" (may be below log text and rating). Please correct me if my understanding is different.

**Comment by Lineflyer** [comment]
That is correct.
IMHO a good option could be not to apply the current server side implementation (apply the fav point via the cache details page) into the logging activity but to "use" the checkbox which is available on the logging page of gc.com (checkbox below log text window) and just send the request alongside with sending the log.

**Comment by madankb** [comment]
![screenshot_2015-07-30-22-31-15](https://cloud.githubusercontent.com/assets/2402373/8995744/4e6621ec-370b-11e5-8c19-90a82300eac2.png)

Thanks for clarification. Please find the UI for adding cache to favorites, I believe server side part needs to handled in LogCacheActivity.java to send favorite option while logging. Please share your thought.

**Comment by Lineflyer** [comment]
UI is looking good for me (the screen for sure needs a general redesign but thats another issue).
If you retrieve information from the webpage you could also include the amount of favorite points available from there and show it inline (e.g. "9 remaining").

For the question where the server side needs to be implemented I can not help you but someone else needs to tell. It should be IMHO at the same place where also the log page is loaded from the server and send back to the server.

**Comment by SammysHP** [comment]
Regarding "n remaining": The option should be disabled if no favorite points are left.

**Comment by madankb** [comment]
Regarding "n remaining", Is that text message shown when check box is selected?. I believe it should be hidden after sometime (Just like "Personal messages successfully uploaded"). Please correct me if I my understanding is not right.

**Comment by madankb** [comment]
Is favorite points mean number of favorites for the cache? Eg:- GC2KYH6 has 2 users added to favorite. Is it number of favorite points of premium user?. Please clarify about favorite points. Appreciate your help.

**Comment by kumy** [comment]
I think it's the number of favorites point a premium member has left to distribute.

(The number of attributed favorites points to a cache is already displayed in lists and caches details)

**Comment by Lineflyer** [comment]
Thats how it looks like on gc.com:

http://i.imgur.com/b3u2Tru.png

**Comment by madankb** [comment]
@Lineflyer Thanks for the clarification. I am not sure what is the http request to find favorite points of premium users. Is there any API document like http://www.opencaching.de/okapi/introduction.html for Geocaching?. Appreciate your help.

**Comment by SammysHP** [comment]
We parse the website.

**Comment by madankb** [comment]
Thanks Sammy. I believe we haven't parsed the favorite points available to premium users before . Do we have sample source code containing favorite points of premium user? I can code based on it to parse the favorite points. Appreciate your help. I tried to upgrade my account to premium in Geocaching.com and find how favorite points are available , but it is quite costly upgrade I can't afford.

**Comment by SammysHP** [comment]
I think a premium membership is necessary to implement this feature. You cannot test it without a premium membership.

**Comment by madankb** [comment]
I can work on this request. Someone with premium membership can test it before deploying it in production. If I have source code sample of favorite points, it will be helpful to implement parsing.

**Comment by madankb** [comment]
Please review my pull request. I upgraded my account to Premium and tested, it is working fine. I believe my pull request has merge conflict, I will work on rebase.

**Comment by kumy** [comment]
@Lineflyer code is merged, I reopen and assign to you for testing.
@madankb Thanks again ;)

**Comment by madankb** [comment]
@Lineflyer Is everything fine with testing?. Please let me know for any other significant issues or feature request to work on.

**Comment by Lineflyer** [comment]
@madankb Had no time to test this expicitly until now. I will inform if something is not OK.

**Comment by Lineflyer** [comment]
Tested with the last weeks nightly. Working ok, except the "problem" I documentd in #5264
