### ISSUE TITLE
Always scale up log images

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4349]
We should always scale up log images if they are smaller than the display width (and are bigger than a certain minimum size, to avoid smiley images and the like). I'm just looking at the logs of some caches in Sardinia and I can always see more on the image opened in an external gallery.

**Comment by Lineflyer** [comment]
@Bananeweizen 
I know your intention with this issues, however meanwhile I see picture source getting higher resolution alongside whereas the device develop a bit slower. In fact most log pictures look reasonable sized to me when opening them also without involving opening in an external app.
Should we keep it open?

**Comment by andrixnet** [comment]
If image DPI not known from metadata, just assume 72dpi like a lot of software does.

**Comment by moving-bits** [comment]
> meanwhile I see picture source getting higher resolution alongside whereas the device develop a bit slower. In fact most log pictures look reasonable sized to me when opening them also without involving opening in an external app.
> Should we keep it open?

I've the same impression about log images getting larger, and wrt to opening in an external program (gallery) we've made some improvements meanwhile (opening in separate window), which makes it more usable. So let's close this old issue.
