### ISSUE TITLE
Incomplete attributes for cache on opencaching.ro

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#4350]
I have noticed that not all attributes of a cache are displayed by c:geo (using information obtained online).

http://www.opencaching.ro/viewcache.php?wp=OR00C1 has 4 attributes. c:geo displays only 2. 
I will attach screenshot. 

I am the administrator of OCRO. It is based on OCPL code and has the same attribute set as OCPL and OCNL. If there is something related to the data export, please let me know. 

Thank you.

**Comment by rsudev** [comment]
@andrixnet Checked again today and didn't see a change in the cache attributes. Do you still have this on your radar?

**Comment by andrixnet** [comment]
Yes, it is. I've been out of comission for a long time, coupled with too much catching up at work and sadly had to leave behind a lot of other projects, including OC. I am now restarting and catching up with recent changes in opencaching-pl branch, then handle this issue as well. Thank you. 
I will return with details as I have them.

**Comment by rsudev** [comment]
Fixed on oc.ro site. Now four attributes are returned. One is missing an icon, will open a follow up.
