### ISSUE TITLE
cache icon on map for archived caches

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#4351]
I suggest the following visual adjustments be made for archived caches: 
- cache icon on map to have reddish background, similar to the  grey background disabled caches have

**Comment by andrixnet** [comment]
Current cache icon looks like disabled icon (grey background) but with a pencil icon, which makes no sense. Should be reddish background (as archived caches are marked) without that pencil.

**Comment by SammysHP** [comment]
It has a pencil icon because there is a personal note.

**Comment by andrixnet** [comment]
ok. still, bg should be IMO reddish.

**Comment by andrixnet** [comment]
I think the part of the code handling cache display on the map is `createCacheMarker` in utils/MapUtils.java, unfortunately I only have a very basic understanding of Java and can't do more :(

**Comment by Lineflyer** [comment]
@moving-bits 
Thanks for implementing this. The new color however looks a bit like the c:geo orange. How about using mainly the same red tone as the cache title is also colored in case of archived caches. That might make it more recognizable (or it may look ugly, not sure).

**Comment by moving-bits** [comment]
@Lineflyer 
Using the same color as the "archive strike-through" color would look like this:

![image](https://user-images.githubusercontent.com/3754370/105399277-afeba980-5c23-11eb-8020-85ca8f84dd5f.png)

(That's just a quick & dirty version, will need to redo the markers from scratch to get smooth transistions)

**Comment by andrixnet** [comment]
How about something in the lines of the unavailable. Less harsh. 
#FFBCBC or #FFA0A0

![Untitled-1](https://user-images.githubusercontent.com/3382777/105536340-dc252a00-5cf8-11eb-93c5-29d258245a58.jpg)
(edited example above)

**Comment by moving-bits** [comment]
Using the slightly darker tone it would look like this:

![image](https://user-images.githubusercontent.com/3754370/105539916-b2b6cf00-5cf5-11eb-97a2-e6086aeeb48c.png)

(Also added a UDC for comparison purposes)

**Comment by Lineflyer** [comment]
I am unsure...what about grey like disabled but icon with a strike through or crossed out?
That would not conflict with other colors and maybe intuitive as users would understand its a more worse status than just grey.

**Comment by moving-bits** [comment]
@Lineflyer 
Have you noticed the variation with the dark red color (same color as strike-through text for archived caches), or would you prefer the "no parking" strike-through variant?

![image](https://user-images.githubusercontent.com/3754370/105553614-fe717480-5d05-11eb-87df-e44fc17673dc.png)

**Comment by bekuno** [comment]
The strike through is for me more logic, good idea.
How about using the red color here?

**Comment by Lineflyer** [comment]
Seen both, but I think the strike through is more intuitive.
Compared to your latest picture maybe more a dark grey singe line from down left to up right with more width (or something like the speed-limit-removed sign on german autobahn).

**Comment by eddiemuc** [comment]
For what it's Worth, I like the dark gray approach better. But I'm finde with a strike through approach as well. As people before, I would suggest darkness color and a thicker line

How will the strike through look on a real phone? (Meaning: not so enlarged as in the screenshot)

**Comment by moving-bits** [comment]
I'm fine with strike-through version instead of colored background as well. Just a few last things:

We should use a crossed version (as in the screenshot above) instead of a single line, as we have the map quick settings where we use a single line for disabled caches, and a crossed version for archived caches:

![image](https://user-images.githubusercontent.com/3754370/105573401-9ea6b800-5d5d-11eb-8e73-45c1368ae23c.png)

I've created both a grey and a red version, see here:

![image](https://user-images.githubusercontent.com/3754370/105573518-766b8900-5d5e-11eb-9ff7-50cdb0946c70.png)

(Red is the same color we use as strike-through in cache title for archived caches.)

**Comment by fm-sys** [comment]
I like the gray one with a red cross most...

**Comment by Lineflyer** [comment]
The red one. Thanks for reworking it :)

**Comment by eddiemuc** [comment]
Into vote for the Red one. Thanks for all the work!

**Comment by moving-bits** [comment]
PR is on the way. Will look like this:

![image](https://user-images.githubusercontent.com/3754370/105575412-c7ce4500-5d6b-11eb-8bc8-7743065e8cdc.png)

One cache (Mega event in Bonn this year) is archived, along with its three waypoints, and one other cache is disabled.
