### ISSUE TITLE
"new list" in list selector drop down (new UI)

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#4352]
I am not sure about the thought evolution regarding lists, I have read an older bug in may this year on this topic. 

Since c:geo changed interface recently, I find it much easier to change my lists, but I strongly miss the "new list" at the end of that drop down. 
![img_0632](https://cloud.githubusercontent.com/assets/3382777/4268620/53f76a08-3cb1-11e4-8155-c7524ecf34af.JPG)

**Comment by Lineflyer** [comment]
Meanwhile we have a multiple list support awhich made the UI different in major parts. Closing therefore due to lack of interest and other UI.
