### ISSUE TITLE
Picture comments not shown 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4379]
From support mail:

I have a cache where I failed due to the invisibility of an addtional info.
Cache: GC47DP5
The hint picture "Hinweis wie du zu A kommst" contains a subheading. I can't find it in c:geo.

--
I did not check where this subtitle is coming from but can confirm that we do not seem to support this.

**Comment by rahu** [comment]
not able to reproduce this with latest build.

**Comment by kumy** [comment]
Isn't it the same as recently closed issue #5200

**Comment by Lineflyer** [comment]
No, as this is dealing not with the title but with the subtitle (description)

**Comment by Lineflyer** [comment]
Oh sorry... I have just seen that this now works as requested in this issue.
Must have been implemented or corrected recently.
