### ISSUE TITLE
Have better wording for location status

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4385]
As mentioned in #4184 right now the status on the lower right is now showing "Fused" or "Low-power" if PlayServices (respectively low power mode) are used.

While on the main page this is more or less a cosmetic issue, it may simply be wrong in the compass screen (i.e. if low power it opt-in and I start the compass I am in high accuracy mode but the lower right still shows low-power).

**Comment by samueltardieu** [comment]
Please suggest better wording.

**Comment by Lineflyer** [comment]
As no complaints by users are given, lets close this.
