### ISSUE TITLE
Scale map text disabled by changing theme

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4398]
From FB...not yet retested:

Although scaling the map text is enabled in the settings, after changing the map theme for OSM:Offline the fonts are small until I disable and reenable the setting.

**Comment by moving-bits** [comment]
Setting "Scale map text" is no longer used in code (probably only for old Mapsforge), therefore closing this issue and preparing a PR to remove the GUI part for this setting.
