### ISSUE TITLE
Inputfield gets focus after closing waypoint coordinates input

### ISSUE THREAD

**Issue by dl1ely** [cgeo/cgeo#4402]
When editing a waypoint, i go to the waypoint details. The input field for the projection direction has the focus (blinking cursor), but keyboard does not slide up. I need to tap the input field explicitly to get the keyboard.

But after entering new waypoint coordinates by tapping on the north or east coordinats, and dismissing the input dialog with "Fertig", again the projection direction input field gets the focus, but now also the keyboard slides up. To get back to the waypoint list, i have to use the back button twice: Once for closing the keyboard, and a second time to get back to the list of waypoints. This starts to annoy me.

It is present still in 2014.10.06-NB-34905d5, and i notice that for about 3 or 4 weeks now, updating my nightly builds quite regularly. I am sure the behaviour was different back then (no keyboard slide up after dismissing the dialog where new waypoint coordinates can be entered.

**Comment by Lineflyer** [comment]
After implementing the new waypoint coord input dialog the keyboard doe no longer slide up after waypoint editing. So the usability and the described problem should be solved.
