### ISSUE TITLE
The "send to c:geo" action isn't available in the gc map if the site is not in english

### ISSUE THREAD

**Issue by SnarkBoojum** [cgeo/cgeo#4411]
I was using send2cgeo since a while, with everything working perfectly. Then I discovered I could have the site in english... and that half-broke send2cgeo: I still have the "send to c:geo" in each cache page, but not anymore on the short description mini-page when I click on a cache on the map.

I also checked that going back to english fixes the problem, and going to german makes it reappear, so it's really an i18n issue.

**Comment by Lineflyer** [comment]
This issue was moved to cgeo/send2cgeo#5
