### ISSUE TITLE
Select mode by slide right sucks

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#4422]
If I slide right on a list to select one item and switch to select mode, the context menu opens up and I need to press back every time.

Context menu should open only by longer touch or select mode should not start by slide rigth an entry anymore.

**Comment by Lineflyer** [comment]
I can no longer reproduce the faulty behaviour. With 2017.02.12-NB I can trigger the selection mode always without having the context menu open at the same time.
