### ISSUE TITLE
Include an activity for geocheck

### ISSUE THREAD

**Issue by ludoo0d0a** [cgeo/cgeo#4431]
Today I just a found bonus on a serie and it required a geocheck confirmation.
It could be great if this verification could be done inside cgeo, because input is not easy on geocheck web page.

Detection of the included js and interaction with web page should be feasable.
Html display with spoilers images could be harder...but already done for long description, isn't it ?

**Comment by Lineflyer** [comment]
No checker seems to have an API. So the current implementation of offering a direct link to open the webpage is the best we can do.

**Comment by SammysHP** [comment]
Btw: Only some "big" checkers are allowed by gc.com. See https://forum.geoclub.de/viewtopic.php?f=136&t=76684
