### ISSUE TITLE
Still OOM crashes on rotation of offline map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4453]
Today I attended an event, where a user showed me the following crash scenario on his Samsung Galaxy Note 2 (running Android 4.4.2) with c:geo version 2014.09.18:

- Open live map using OSM:Offline map
- Rotate 3 times
- On fourth rotation c:geo crashes

The specific play report shows only this:
```
java.lang.OutOfMemoryError
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
at org.mapsforge.android.maps.overlay.Overlay.changeSize(Overlay.java:411)
at org.mapsforge.android.maps.overlay.Overlay.run(Overlay.java:246)
```
This can not be the multiwindow bug as it should be disabled in that version.
I can contact the user. What else would we need to find the reason? 
Possibly a memory dump...but AFAIR this is not automatically created in the release version isn't it?

**Comment by Lineflyer** [comment]
@rsudev Might this be something to take a look at alongside the mapsforge 0.5 implementation (or maybe it gets solved implicitly with it)?

**Comment by rsudev** [comment]
I am not sure. I took a look today and didn't get any issue with either of the implementations. Perhaps can the aforementioned user re-check if the behaviour still exists on current master?

**Comment by Lineflyer** [comment]
Assigning for retest with a version containing b6c823a (as soon as I meet the user)

**Comment by Lineflyer** [comment]
Not happening anymore on that users device.
Seems to be fixed as well by increasing heap size.
