### ISSUE TITLE
List of caches - multiline title

### ISSUE THREAD

**Issue by bubi-luka** [cgeo/cgeo#4455]
Hi!

There are some caches, that have really long names and are part of the trail (eg.: A really, really long cache name that is part of this beautifull trail No. 11). In a list of all saved caches c:geo only shows first XY characters (I have a small phone screen). Since the cache number is usually on the end, I can not find a specific cache easily. If I sort by name I have to count where the desired one will be, that is quite hard. The proximity sort is also of no use in some cases, when the trail is circular and the returning path is nearing the curent one, so the closest caches are not always the next ones.

I wish there was an option to have multi-line title names, to switch them on and off. Is that possible to implement?

Regards; Luka

**Comment by Lineflyer** [comment]
Closing due to lack of feedback and possible workaround.

**Comment by bubi-luka** [comment]
I am sorry, but I do not understand. What kind of lack of feedback? What possible workaround?
