### ISSUE TITLE
Filter cache sources on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4469]
From FB:
Hello, I have a wish. Since I am logged in at the same time to multiple services, it is sometimes very full of caches on the map. For this reason I would wish that I have a fast selection in the menu that only the caches of a single service may be visible on the display.

**Comment by GodfatherThe** [comment]
Any update on it?

**Comment by Lineflyer** [comment]
No, otherwise it would be mentioned here.
AFAIR we also not received any other request like this from users.

**Comment by Lineflyer** [comment]
Should be possible now with new filter implementation.
