### ISSUE TITLE
Follow my location does not always recenter the view

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4475]
With Google Maps only.

If on the map you drag it fast to make it and remove your finger, the map continues to move for a bit. If you activate the "follow my location" button in the action bar while the map is still in movement, the button will get checked but it will not recenter the map onto your location.

I have not checked if it follows you when you move as I am indoors right now and my location does not change.

**Comment by Lineflyer** [comment]
Not reproducible for me on GMapsV1 or GMapsV2.
