### ISSUE TITLE
Cache rendering has massive delay or leads to ANR

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4481]
Opening this cache

Geocache GC49CQC - Das Nest der Hedwigeule - zum 5000. - http://coord.info/GC49CQC

is obviously problematic. On my Galaxy S4 the whole app gets quite unresponsive and sometimes runs into an ANR.

**Comment by Lineflyer** [comment]
Another one from support mail (did not have the time to check it):

User message:
http://coord.info/GC5DHCD
A recent log entry has 320 smilies in it causing c:geo to crash

**Comment by rsudev** [comment]
On my device I do not see all the smilies, only a handful, but no crash

**Comment by samueltardieu** [comment]
Yes, I'll address this as well.

**Comment by samueltardieu** [comment]
@Lineflyer and others: please test before inclusion on `release`.

This can be tested on all the caches included in the report (GC49CQC, GC5GMTZ, GC35RQ4, GC57MPB, GC1P71J, and GC5DHCD [in log entry]).

**Comment by samueltardieu** [comment]
On emulator and on Nexus 5, everything loads with reasonable delays. On HTC Hero (Android 2.3.x), the poor device still has a lot of difficulties.

**Comment by rsudev** [comment]
On my Sony Xperia Z1 (Android 4.4):
GC5DHCD - I see all smilies in the log entry, no issues
GC49CQC - took some seconds to download/render all the smilies, little laggy in that time, everything OK
GC57MPB - Opening the description has a little lag, scrolling starts with a little lag as well. Given the number of images the performance is very good :)
GC5GMTZ - no issues at all
GC35RQ4 - only two seconds delay to pen the images tab - brilliant
GC1P71J - no issues at all

Overall: looks very good!

**Comment by Bananeweizen** [comment]
GC49CQC takes around 4 seconds to open description on my Note1, every other cache is more fast. GC35RQ4 crashes whenever I try to go away from the images tab (and this should probably be solved completely independent of this issue, by using an actually gallery, where we slide through the full size images). Otherwise all seems fine.

**Comment by samueltardieu** [comment]
@Bananeweizen GC49CQC really contains hundredths of different images, so nothing can be optimized there. And +1 for an actual gallery, as long as its retrieval and caching system can be integrated with our framework.

**Comment by samueltardieu** [comment]
> I remember there was one cache like this with 1000+ images that lead to OOM.

@mucek4 Do you still have a reference for this cache?

**Comment by mucek4** [comment]
Not really but it should be somewhere in our issues afaik

**Comment by Lineflyer** [comment]
@samueltardieu I think @mucek4 was refering to #3146

I will also test this today but the results of others so far look promising already.

**Comment by Lineflyer** [comment]
I wanted to test with 2015.01.14-NB on my Samsung S4, Android 4.4.2 but it seems I have massive connection problems to gc.com.
I will need more time to investigate...but right now I assume the problem on server or network side and not in c:geo.

**Comment by mucek4** [comment]
Not really @Lineflyer. I remember we had a cache that had a matrix of like 1000 images downloaded from various places of internet to make a mosaic

**Comment by Lineflyer** [comment]
2015.01.15-NB on my Samsung S4, Android 4.4.2:

Cache | Comment | Result
-------- | ------------ | ---------
GC5DHCD | No issues at all, all smilies in log | OK
GC49CQC | A bit laggy while rendering the view during download progress, but without any lag afterwards while viewing and scrolling through the listing | OK
GC57MPB | Laggy while swiping to the description tab and while scrolling the first time, then OK | OK
GC5GMTZ | No issues at all, all listing pictures shown | OK
GC35RQ4 | Loading OK, description ok, gallery ok, No crash when leaving the gallery | OK
GC1P71J | a Bit laggy when first time accessing description and gallery, then OK | OK

Overall:
You are still able to see some delays (i.e. a little slower and unresponsive for max.1 second) but compared to before it is much better. So I vote for merging the improvement to `release`.

**Comment by samueltardieu** [comment]
Merged to `release`.

**Comment by Lineflyer** [comment]
Just for future reference:

Test with a quite old Android 2.3.5 device HTC Widlfire S:
GC49CQC

Loading time with current release 2015.01.12:
11 minutes until app gets responisve again and shows cache listing

Loading time with 2015.01.15-NB:
3 minutes until app gets responsive, according to log pictures keep loading in the background but app is usable.

Well done...
