### ISSUE TITLE
Use google drive API for creating/reading cache notes documents

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#4486]
Hi, I'm using this extension to chrome http://koalabear.nl/geocaching/, which provides embedded google docs in cache listings. Where I'm writing notes to specific partially resolved caches. It will be nice to have same feature in c:geo. Sometimes I'm using personal cache note which is present in cgeo, but when swapping phone and tablet I don't have such notes anymore. What do you think about such plugin ? Should I try to investigate, if we can do that, or you think that it is useless ? It can be at best made in same manner as calendar plugin, so when users don't want it, they just don't install it.

**Comment by Lineflyer** [comment]
As this is labeled as "Feedback required" and no supporter of this idea came up, lets close this for now. Feel free to comment and/or reopen.
