### ISSUE TITLE
Sort by found date

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4500]
Feature request from support mail:
I would like to sort my list of found caches by found date. That seems to be not yet possible.

**Comment by Cappa-d** [comment]
@Lineflyer 

Hmm do I miss something here? 

I have a folder where I store my finds in. Tap the menue within that folder and select Sort -- Date Logged isn't this exactly what is aked for here?

**Comment by Lineflyer** [comment]
Thats perfectly right.
I don't know if I missed to see that or had other thoughts in my mind. 
Closing for now, thanks for the hint.
