### ISSUE TITLE
Including GooglePlay rating link 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4519]
We do "only" have 26k ratings but most probably much more regular users of the app. As the popularity ranking and also the decision of users to install the app might be based on reading other users opinion we should kindly ask users to rate the app.

I am not thinking of anything annoying like blocking the app until it is done or actively declined, but something like our new release notification.
Maybe we could use that very implementation also to show a question like "You will support us by rating the app on Google Play".

Opinions?

**Comment by Lineflyer** [comment]
FYI:
Due to the recent bad rating peak due to people trying to use c:geo without valid login (see internal board message) I pushed a notification - mainly to test the reaction of users - via our notification system.

See https://status.cgeo.org for details

**Comment by Natureshadow** [comment]
Please don't advertise spyware in free software. Thanks.

**Comment by Lineflyer** [comment]
> Please don't advertise spyware in free software. Thanks.

We advertise to get a feedback from our users over the channels we have.
It is not mandatory to click on it.

**Comment by Natureshadow** [comment]
>We advertise to get a feedback from our users over the channels we
>have.
>It is not mandatory to click on it.

It is not mandatory to buy anything from any advertisement. Still, people do, because... that's the intention of ads.

There sure are other ways, like a pre-filled e-mail, which can easily be opened on Android.

**Comment by Lineflyer** [comment]
Let me close here.
The recent trial has shown, that a temporary message is enough to 
1. motivate some people to leave feedback
2. get a broad feedback regarding problems

For this trial I made we received approx. 3000 new ratings up to now.
Most of them good but also those people having a login problem now contacted us with a bad rating and I have been able to reply and help.
The feedback also confirms, that (very probably) we do not have any generic problem (that is what I wanted to find out), but lot of people just worked with c:geo without login in the past.

**Comment by SammysHP** [comment]
The "generic problem" is that we have no first-start assistant. ;)
(There should be an issue somewhere about that topic.)

**Comment by bekuno** [comment]
The current 1* ratings came from active users without active (GC) account. We did not loud enough inform that they need it after the change.
Maybe we should check this (every time?) when showing the map and present a message.

**Comment by Lineflyer** [comment]
> The "generic problem" is that we have no first-start assistant. ;)

At least we do now have a first start screen, from which I hope that it at least give a bit guidance to first time users.

> Maybe we should check this (every time?) when showing the map and present a message.

Might be a good idea but needs to be implemented with greatest care, so that it really only get triggered if no connector is active respectively if the GC-connector is active but has no login information stored.
