### ISSUE TITLE
Blue arrow does not appear on map

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4533]
This has been reported by a user using a Wiko Cink Peax2 running Android 4.1.2 with cgeo 2014.12.12.
The arrow does not appear when the user rotates the device.

**Comment by samueltardieu** [comment]
Could a user with the problem try 2015.01.01-NB1 (or later)?

**Comment by Lineflyer** [comment]
First feedback for this was positive:
OnePlus One  on Android 4.4.4
Version 2015.01.02-NB
