### ISSUE TITLE
GPS disconnects after getting a fix

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4535]
A user with a Samsung Galaxy SII running Android 2.3.6 writes to support that cgeo 2014.12.12 does not cope well with the GPS. The icon blinks, cgeo gets a fix, then the number of satellites falls back to 0 and the GPS icon blinks again. Default options (Google Play services, no powersave).

**Comment by mortenvf** [comment]
I am experiencing this issue with Android 4.1.2 and Google Play Services 7.0.99 on Sony Xperia Go (ST27i). Disabling Google Play Services within c:geo restores GPS precision and update rate as described in the original issue.

**Comment by paolof** [comment]
Same issue with Android 4.1.2 and Google Play Services 8.3.00 on Samasung GT-I8730 (Galaxy Express, European version). As soon as the first fix ("rough" position) is reached, the GPS is switched off and then on again. That means that the GPS is switched off and on again every few seconds, without getting an accurate position.

I confirm that the workaround is to disable Google Play Services in c:geo configuration.

**Comment by samueltardieu** [comment]
@mortenvf and @paolof : could you please check in cgeo/preferences/system that you haven't enabled low-power mode?

**Comment by paolof** [comment]
@samueltardieu : I confirm that low power mode is not enabled

**Comment by mortenvf** [comment]
Tested it again and the problem is still there in c:geo version 2015.10.30
Low power mode OFF, Google Play Services ON
