### ISSUE TITLE
create premium account for emulator

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4542]
I was just checking the emulator state and noticed it runs as mucek4. I suggest that we create an additional premium account at GC specifically for running the emulator. I want to automate (that is script) the emulator setup and don't want to share other peoples passwords for that.

**Comment by Lineflyer** [comment]
Similar to #4276 with the only difference, that the user should be premium. We can continue in that other issue

**Comment by mucek4** [comment]
Not exactly Lars. Here we are talking about GC.com username. Right now emulators runs tests under my name. Are we willing to give 30€ a year to GC.com for this? After that I can change my well-known password :)

**Comment by jakedot** [comment]
I would sponsor those 30 € per year if it is still needed.

**Comment by SammysHP** [comment]
@jakedot If you like to donate something, feel free to use the PayPal link at our website https://www.cgeo.org/ :wink:

**Comment by jakedot** [comment]
Oh it's not the first time, I've donated € 50 in February 😉
