### ISSUE TITLE
Add summaries in Settings - Services menus

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4545]
It looks like some users aren't clear on where to configure their login / password for geocaching.com and other services. Adding a summary in the settings under "Services" might help with that.

**Comment by Lineflyer** [comment]
The feedback for this new summary on the menu item `Services` was quite positive. 
If someone has some minutes spare time it would be cool to also have subtitles for the other menu items e.g. like suggested above.

**Comment by samueltardieu** [comment]
Unassigning myself so that someone else can take care of the rest of those descriptions.

**Comment by Lineflyer** [comment]
Yes please....that would be brilliant of someone can add those.

**Comment by eletap** [comment]
Hello, could I start working on this issue? I'm new here and this seems to be a relatively easy pick

**Comment by konpapa** [comment]
Hello, could I start working on this issue? I'm new here and this seems to be a relatively easy pick

**Comment by Lineflyer** [comment]
Sure.
Please kindly read the information about the project here: https://github.com/cgeo/cgeo/blob/master/README.md

If you have questions don't hesitate to ask here or (better) in our developer chat.

**Comment by Lineflyer** [comment]
Adapted the title.

**Comment by Lineflyer** [comment]
@konpapa Please ignore that comment from @samueltardieu regarding branch  `issue-4545`. I think this branch is well outdated. Just create a PR towards `master` once you are done.

**Comment by SammysHP** [comment]
`release` might be the better choice. What do you think?

**Comment by rsudev** [comment]
As we are more or less in the process already, I am not sure we would like to generate such a bunch of untranslated strings right now.

**Comment by Lineflyer** [comment]
Thats why I suggested `master`

**Comment by Lineflyer** [comment]
@konpapa Thank you very much for your contribution which I just merged!
