### ISSUE TITLE
Log statistics sometimes missing when downloading from live-map

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#4547]
This issue was raised by SammysHP. It is not fully deterministic, but I was able to produce at least one affected cache with every try with the following recipe:
- Start c:geo, open live-map, switch off 'live'
- move to a region where no caches are stored, select a zoom level so that you expect >~20 caches in the view
- switch on 'live', wait for the caches to be displayed
- select 'store offline' to a new list
- when the download is finished, the caches are still displayed as unreliable (I would have expected an update here)
- directly start opening caches and checking the log page for missing statistics

I assume some sort of timing, but couldn't find any clues to that in the log

**Comment by samueltardieu** [comment]
Can it still be reproduced with current versions? Some things regarding synchronization while storing logs have changed in the last few days.

I wasn't able to reproduce it on my side.

**Comment by SammysHP** [comment]
I'll test it tomorrow.

**Comment by SammysHP** [comment]
Yep, it's fixed.
