### ISSUE TITLE
Live map does not remember last position

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4551]
I know that recent changes are the cause of it, so this is to discuss if any improvement is necessary/possible.

From support mail:

--

in older versions one came back to the last position at the maps when opening 'live maps', in the new version c:geo forgets the last position and always starts at the center of the actual city.
This means scrolling every time when opening 'live maps'.
Is this to be a feature? To me it behaves more like a bug - is it posible to re-configure c:geo to old behaviour?

--

Before, with GPS on, it always showed the present position. With GPS off, it memorized the place that was last shown/chosen. In this state, there was an issue. After I turned off GPS, I needed to remove app from memory and restart it, otherwise, it still showed the map from last GPS known point.

Now, even with GPS off, it always show the map from my home position, even if I'm not at home. I have turned off WiFi also, but it still shows the map at my home location.

For example, I select a directory "Faro" where there are caches from a certain area and choose the map icon to show them on the map. Then I go back to the main page and select the Live Map. It shows at my home location, instead of "Faro" location, as it was before.

Also, following your instructions to select the "active Live Map" in the "Faro" area, all found caches also appear, despite the option is set to hide them.

In my opinion, I think the previous behavior is much better, because in any map location there's always the option to go to the present location, by clicking in the "target" icon at the top, right? The opposite is not possible.

**Comment by samueltardieu** [comment]
I'm not sure this is that new a behaviour: see #3078 for which this issue seems to be a duplicate, and has been open (by @Lineflyer) since July 2013.

**Comment by Lineflyer** [comment]
Independently of whether part of this issue is new or not, I have to agree that the proposal in #3078 would be the solution for it.
So I think we consider this as a duplicate.

The raised attention to this problem might be caused by the split of live map and cache/list map with repsect to zoom settings which was recently introduced.

**Comment by Lineflyer** [comment]
Addition just for info.
THe following support mail made me aware about the difference to before: If we use the homelocation.

---
You changed the behaviour of setting the map location some versions ago.
Without known location, the map is always centered to my home location now. Previous it was centered to the previous center position position when opening the map.

I often use the live map to prepare a caching session. During the preparation I often leave the map view - to select a cache by GC-code or look something up in a cache list - and when returning to the map, I first have to sroll back to the target region. This is very anoying. I would very much prefer c:geo to store the "centered to actual position"
flag when leaving the map and restore the last center position when returning to the map.
---
