### ISSUE TITLE
Compass shows random direction

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4552]
We have some users on support mail which have problems using the compass starting with 2014.12.09:

- The distance is correct but the direction is randomly changing.
- "Use GPS and Compass" is active. If the users select "Use GPS only" the direction gets stable and correct (while moving)
- Disabling GooglePlayServices makes no difference
- Compass in other apps (Groundspeak, GPS Status, etc.) works without a problem

Devices:
- Sony Xperia SP (C5303), FW.205, Android 4.3
- other model informations requested (will be added later)

**Comment by Lineflyer** [comment]
Another user via support mail:

Hi did check everything without success:
- Compass calibrated
- All other compass apps are working
- "GPS and Compass" is active
- Google Play and/or energy saving mode does not make a difference
- On live map the blue arrow is jumping around the same way as in the compass

HTC One Mini, Android 4.4.2.

**Comment by Lineflyer** [comment]
@Eingehirner 
Funny thing: I just got the very same device here: HTC Wildfire S, HTC Sense 2.1, Android 2.3.5
The compass in c:geo is working without a problem on my device with c:geo 2014.12.22.

One time there was a problem of the compass showing 180° wrong, but this happend the same in the "GPS Status and Toolbox" which I started right after occurence, which makes me think, that this is a device specific problem. In the 180° scenario it helped to calibrate the compass to make it working again (i.e. turn the phone around all axis several times).

**Comment by arteos** [comment]
I have the same issue in c:geo on my HTC one M7 with Android 4.4.3
The compass is jumping 180 degress and the blue arrow does the same.

I tried a separate compass app and it works there and when I open google maps the blue arrow on that map is correct.

Also, the "radar" navigation in c:geo works correctly with the built in compass when navigating to a cache.

**Comment by Lineflyer** [comment]
I shared a link to a video to the closed cgeo-dev mailing list for the very problem @arteos has described. A user send it to our support.
HTC One M7 ANdroid 4.4.3

I asked the user to try the RC-version. 
@arteos Can you please also try the release candidate version http://www.cgeo.org/cgeo-RC.apk ?

**Comment by arteos** [comment]
I tried the RC and unfortunately it didn't work. I also tried with 2015.01.07-NB1-3fe1dd9 since I had it installed from previous debugging but no luck there either.

**Comment by Lineflyer** [comment]
This issue contains IMHO different problems. Major part of them are somehow device caused (sensor decalibrated or broken, bug in Firmware). 

Some of them seem to be solved with a reinstallation of c:geo which sounds quite strange but was also reported several times now. 

At least for two devices I see a pattern which looks like a problem in c:geo:
- HTC One (M7) Android 4.4.3 
- Sony Xperia SP (C5303), FW.205, Android 4.3

In order to get this clearer and avoid a pool of different issues to be listed in a single issue I will open three new dedicated issues and close this one.

**Comment by erichryan** [comment]
I'd been having this issue with my Samsung Galaxy SIII - I was recently pleased to see that the most recent update to c:geo (on 1/12/15) completely fixed the problem for me!

**Comment by Lineflyer** [comment]
@erichryan Thanks for the feedback/confirmation!
