### ISSUE TITLE
Detect if website language was changed during runtime

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4555]
I just know see the problem, that on updating my stored caches each of them looses the size information. 2014.12.22-NB

Can someone reproduce it?

**Comment by Birdy2404** [comment]
Is it possible to check and if necessary change the language every time you make a requested and after that set it back to the previous language? So this would make the actions a bit longer, but will take care for correct data and should be fine for the usablilty of the Website.
Or will this take too much time especially with slow transfer rates?

**Comment by Lineflyer** [comment]
@Birdy2404 
I can't truly judge the exact effort needed for such approach, but I guess its quite time consuming at least in our current implementation, as we would trigger a a new login then at multiple points and it takes several seconds each. And additionally there is no clear end/begin of communication, so implementation wise it would probably be a huge effort at many places.

At the end its more meaningful to either get independent of the language with more clever parsing methods (so we can drop the switch to English) or get into an API access.
Until one of these two things happen, we will most probably stay with the current approach. In fact there are currently only a few users complaining about this drawback.

**Comment by Birdy2404** [comment]
So for the parsing you need somebody to find the necessary infos in every language, don't you?
Even I'm not able to write the lines of code, I can do research stuff in codes, if some ode show me short, what I need to do (e. g. Teamviewer/Skype) and give me a list, what I need to search for 😉

**Comment by fm-sys** [comment]
Almost everything in cgeo is language independent meanwhile (see https://github.com/cgeo/cgeo/issues/13228#issuecomment-1243052166), so this issue isn't relevant anymore...
