### ISSUE TITLE
Refresh all without progress

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4563]
At least six users report, that from time to time the refresh of several or all caches does have no progress, i.e. it is stuck at 0%.
At the same time updating single caches work.

As we recently changed the network operation in this area I open this issue for further investigation.

**Comment by samueltardieu** [comment]
I'd be interested by a new test starting with 2015.01.01-NB2.

**Comment by Lineflyer** [comment]
I tested 2015.01.01.-NB2 with following scenarios on the same device as above:

1. List of 15 caches (same like above) 20 refresh cycles with static maps and log picture loading without any hanging download.
2. Refresh a list of 89 caches 10 cycles without a problem
3. Refresh a list of 4 caches 30 cycles without a problem.

It looks stable now despite further occurences of #4569 .
