### ISSUE TITLE
Simple way to vote with GCVote

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4566]
There should be a way to vote from the cache details screen, without the need to use the logging activity. It should encourage users to vote more often. E.g. we could _always_ display the row with the own rating (instead of only when he/she already voted), and ask the user for his vote on tapping that row.

**Comment by Lineflyer** [comment]
For what has been implemented in  896f0bd7d1c6b4096fb37594e5d879f0f49ed3af I think we should move it to the last position of the overflow menu (or at least further down).
Right now it shows up in the menu bar on my tablet and more important options like "Caches around" are now in the overflow.
