### ISSUE TITLE
Ask for bonus mystery clues on logging

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4567]
I sometimes do cache series, where you get a clue (like a character to number mapping) in each of the caches, and using all together you can find a bonus mystery of that series. I typically store that clue as personal note in the cache where I found it, but sometimes I forget to write it down after logging.
I envision that the app could ask me with an input dialog after logging automatically, given the following conditions:
- A setting for this feature has been activated.
- A certain text is found in the cache description, in German a typical word would be "Bonuszahl".
- The personal note is empty.

What do others think of this? A drawback is the dependency to pattern matching, without knowing the language of the cache description. We would basically need to search for all language patterns at once (e.g. English, French, German,...), without making this a translatable string.

**Comment by Lineflyer** [comment]
@Bananeweizen Do you think we should keep this open?
