### ISSUE TITLE
c:geo crashes constantly on HTC Wildfire S with Android 2.3.5

### ISSUE THREAD

**Issue by Eingehirner** [cgeo/cgeo#4568]
I have HTC Wildfire S, HTC Sense 2.1, Android 2.3.5 with c:geo 2014.12.22 installed and 1196 caches in offline storage. 
- The update section says (in German) "No updates available for this phone. This phone is at the most recent status".
- The SQLite c:geo database seems to be OK (no errors reported with PRAGMA integrity_check) but I have used c:geo for quite a while so it may be that some entries do not comply with the current version's requirements...
- I use a prepaid card so c:geo is used exclusively offline (except when having a WiFi around and loading new caches).

However, using c:geo I get crashes ("Tut uns leid! Die Anwendung c:geo...") almost everywhere:
- opening the offline map (using OSM maps)
- logging in when first starting c:geo (rare and difficult to reproduce)
- when starting c:geo and Wireless has recently been disabled but c:geo still thinks it's logged in (shown in the bottom line "login OK")
- when moving the map around or starting map view for a cache waypoint that had been opened from the map view already
- <b>most importantly: when downloading one or several caches for offline use</b>

The last issue is very reproducible: Downloading more than three caches at once is a gamble with less than 5% chance of luck. More than four hasn't happened more often than once or twice in the last two years. It seems to increase when the GPS is on but this may only be a subjective impression.

Downloading a single cache from the map view also leads to a definite crash in few cases, the most recent one being GC4Z71P (Jura-Höhenweg Teil 1).

Map movement crashes are also easy to cause: Zoom out until more than ~200 caches are shown at once and simply move the map around a few times. Crash guaranteed.

After a crash, sometimes c:geo reopens the map view automatically (rare case) or reopens itself automatically (frequent) or doesn't reopen at all (also frequent). Nothing else (except for sometimes BatteryBot Battery Indicator and sometimes Llama) is running in the background.

I have debug logging enabled so there should be a few memory dumps. Is anyone interested in solving this issue so that I can send them in? I reject Google Play Services so reporting doesn't work (unfortunately).

Best regards,
Eingehirner

**Comment by Eingehirner** [comment]
Can it be attributed to the old Android version I have? The Wildfire S does apparently not support a higher version. Anyway, I was able to provoke a crash and have uploaded dump and log here:
https://www.dropbox.com/sh/ntfx2lhinfefo9r/AAC1bDJJjSjKWiAkWVxgkVG2a?dl=0

**Comment by Eingehirner** [comment]
I opened c:geo (with internet connection but using the OSM offline map of Switzerland which I always do), went directly to the live map, zoomed out to a view where I had ~20-30 caches on the screen and selected menu -> Store for offline use. As I said, this is guaranteed to cause a crash. I have to admit that before managing this crash c:geo simply crashed one time because there were too many caches visible on the live map. I didn't grab a log then but a dump is available if interested.

**Comment by Lineflyer** [comment]
OK...To say it simple:
Your device simply has not enough RAM to support this operations.
Reason is foremost the offline map which consumes a lot of memory. The additional network requests when downloading cache or doing other interactions simply bring it over the limit.

It is not so relevant how much memory the device has as such, but how much of it the OS offers to a certain app. You will see that using online maps will reduce the amount of memory needed and therefore the usage will be better.

Sorry, that I dont have any better news...but your Wildfire S may need to be replaceed to use all features of cgeo.
While tracking this issue I used the Wildfire and I really have to say that using a more recent device will bring you a huge benfit in speed and usability of c:geo.

**Comment by Eingehirner** [comment]
I had suspected something like this but what I find strange is that OSMAnd+ which uses offline maps all the way as well and it has never, not even once, crashed, even with favorites, GPX tracks and contour lines, overlay and underlay maps... Why do they use up so much space in c:geo but not in OSMAnd+?

The second problem is that c:geo also crashes if I use online maps and try to download caches.

You're right, though, I now use a Lenovo A7-40 in parallel to the Wildfire and it works like a charm... still, I'd like to keep my Wildfire ;)

**Comment by SammysHP** [comment]
OSMAnd does not use Mapsforge maps but an own format.
