### ISSUE TITLE
Inconsistency of pictures in image tab

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4570]
I was happening to me recently and two users on support mail reported that:
Opening a saved cache and looking at the image tab sometimes shows pictures of a different saved cache.
On next access (or on next refresh) it is solved (not sure about the conditions).

**Comment by samueltardieu** [comment]
We use SQLiteStatement from several threads at the same time, and this is not allowed and will mix up data. From the documentation of `SQLiteDatabase#compileStatement(String)`:

    No two threads should be using the same SQLiteStatement at the same time.

and

    Returns: A pre-compiled SQLiteStatement object. Note that SQLiteStatements are not synchronized, see the documentation for more details.

We need to either synchronize the use to ensure single-thread access at any time, or stop precompiling statements.

**Comment by samueltardieu** [comment]
Synchronizing the use of statements on the statements themselves (which is easy now that they are organized as an enum) should be quite easy to do.

**Comment by samueltardieu** [comment]
@Lineflyer : please confirm that this is fixed in 2015.01.06-NB, and I'll merge this into release as well.

**Comment by Lineflyer** [comment]
I will do my very best....but as it was kind of unpredictable I can probably do not more than continous refresh and look at some random samples to see whether something is mixed up.

I would therefore suggest to merge it to release now, so that I (and some users) can test in an RC-version over a longer period of time. We could revert it if something goes really wrong with it.

**Comment by samueltardieu** [comment]
Done.

**Comment by SammysHP** [comment]
What do you think how it will affect performance?

**Comment by samueltardieu** [comment]
It won't be noticeable. Synchronization should have been done from the start (it was half-done already for some of the statements), and contention will be quite rare.
