### ISSUE TITLE
Test fails because item is not in overflow menu

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4574]
`LogTrackableActivityTest` fails on my Lollipop emulator because the "add" action is not in the overflow menu, but is present directly in the action bar which is large enough to hold two items.

Tentatively assigning to @Bananeweizen as he is the one who used Espresso in the first place.

**Comment by Lineflyer** [comment]
@samueltardieu @Bananeweizen Still open?

**Comment by Bananeweizen** [comment]
Espresso tests have been disabled for more than 2 years now. Closing, since I also don't see them coming back soon.
