### ISSUE TITLE
Import loading bar changes colour

### ISSUE THREAD

**Issue by akkatracker** [cgeo/cgeo#4581]
![Screenshot](http://i.imgur.com/LJ30poG.png)

The bar goes from blue (where I'm at) to a shade of grey to another shade of grey. This hasn't existed in any previous release

**Comment by samueltardieu** [comment]
@akkatracker Please provide a description for the issue.

**Comment by akkatracker** [comment]
http://m.imgur.com/LJ30poG

The bar goes from blue (where I'm at) to a shade of grey to another shade of grey. This hasn't existed in any previous release

**Comment by akkatracker** [comment]
@samueltardieu sorry the Github app played up on me. This has been rectified

**Comment by samueltardieu** [comment]
It looks like you are using a custom theme / icons. I cannot reproduce this on the standard theme.

**Comment by akkatracker** [comment]
OnePlus one Stock Cyanogenmod 11

I've been using CM before without issue though.

**Comment by samueltardieu** [comment]
I just tried on a OnePlus one, and got the same kind of progress bar at the beginning, but it ends up normally when the bar progresses. 

Did you report this as a problem or as something puzzling only?

**Comment by akkatracker** [comment]
More as a ui error, unless this is intended

**Comment by akkatracker** [comment]
I haven't seen this again for a while so I'm closing this issue as likely been fixed.
