### ISSUE TITLE
Compass not working

### ISSUE THREAD

**Issue by erichryan** [cgeo/cgeo#4582]
I love c:geo - have been using it ever since I got a smartphone, but I've recently encountered a rather annoying issue. The compass no longer works. The distance to the cache updates fine, but the compass does not function properly. It seems to only want to bounce between 2 different headings (between 0-30 degrees and between 180-210 degrees). This only became an issue within the past few weeks; I'm not sure if it was after an update or not. I check the compass in other apps, and it works fine elsewhere. I've also tried it both using GPS and compass and GPS only, and neither one works. Is there something I can do to fix this issue? I've uninstalled and reinstalled the app with the same issue still present.

I use a Samsung Galaxy S3 (SPH-L710) running Android version 4.4.2

**Comment by SammysHP** [comment]
There are already other issues about this topic. You can try to disable Google Play Services in the c:geo preferences as long as we don't know the reason.
