### ISSUE TITLE
New phone unable to log in

### ISSUE THREAD

**Issue by Thewinfieldwonders** [cgeo/cgeo#4583]
Hi,  I acquired a Samsung Galaxy S5 mini today and I have downloaded cgeo but it is not recognising my login details.  It told me they were fine but is unable to log me in.

Any ideas?

**Comment by SammysHP** [comment]
"It told me they were fine" – where?
"is unable to log me in" – where?

**Comment by Thewinfieldwonders** [comment]
When I first set up cgeo it took me to the login page and said user name
onk password ok and logged in. On the cgeo home page it tries to log me in
then comes up as login failed. It is also not showing any caches at all.

**Comment by samueltardieu** [comment]
@Thewinfieldwonders When you go to Settings / Services / geocaching.com / Check Login, does it tell you that the login is ok?

If you log in on the site directly using a browser, does it work? Have you accepted geocaching.com terms of service already?

**Comment by Thewinfieldwonders** [comment]
Have logged into geocaching.com on my browser and all seems to fine now.
Thank you
