### ISSUE TITLE
Static map loading might be nearly completely skipped on GPX import

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4586]
Recently a limiter for static maps loading was introduced by @samueltardieu (If a 304 error is received the download is suspended for 30 seconds).
While this is good to speed up the refresh process of caches it might be considered not useful for GPX imports while static maps loading is active.

More precise: 
When importing a GPX the last import step is the download of static maps for the previously imported caches. This means in contrary to the refresh of caches the static maps download requests are bundled at one point, which means, that on the first occurence of a 304 the static map loading for all imported caches is skipped.

While this is the current intended behavior I do see it as a problem for users who would like to use the static maps (e.g. offline after importing a GPX).
How to find a useable solution for this....maybe only by implemting #3406?!

**Comment by samueltardieu** [comment]
Well, before this change, GPX did not store many more static maps, it just tried and received errors.

**Comment by Lineflyer** [comment]
Let me try this on a new day without prior requests...seems no I also exhausted my quota.

**Comment by Lineflyer** [comment]
So I checked now before and after the change with an import of 45 caches via GPX.

Before the change:
- 270x Requests (6 per cache)
- 50x Return code 200
- 220x Return code 304
- i.e. 50 maps loaded

After the change:
- 60x Requests (6 per cache for 10 caches and 35 caches ignored due to previous 304 error)
- 53x Return code 200
- 6x Return code 304
- i.e. 53 maps loaded

So funny thing:
It is just the opposite or lets say nearly the same as before. My subjective feeling was wrong.

Due to the fixed ignore time it will get little worse if the import contains more caches (as more requests will be tried during the ignore time and probably the server might already allow downloads again before end of the ignore time).

But the only improvement possible here seems to be #3406 which is not wise for batch refresh at least as it will slow down the overall progress.
