### ISSUE TITLE
c:geo not provided for "geo:" links

### ISSUE THREAD

**Issue by TravelingGeek** [cgeo/cgeo#4588]
**Feature request:**  Support RFC 5870 geo: uri links.  
**Description:**
c:geo should be a client that can undertand and take appropriate action when an Android device encounters a uri formatted as a geo: link.

An example uri to groundspeak’s HQ would look like this:  geo:47.64897,-122.34812  

**Example use:**  I as a geocache owner, I would like to publish caches that use NFC (Near Field Communication) tags to satisfy the Groundspeak definition of a Beacon Geocache attribute (http://support.groundspeak.com/index.php?pg=kb.page&id=303).

The NFC Tag can be programmed to display a message that may include the coordinates of the next or final stage of a multi or mystery cache.  The tag can also be programed to pass a geo: uri link that will allow client applications such as Map and Locus etc. to launch an app and use the passed coordinates.  c:geo should be able to handle the geo: link by prompting to add the coordinates as a new waypoint or corrected coordinates for the current cache or a nearby cache.
geo: links can also be coded into bar codes and QR codes.

The IETF defines the geo: link in RFC 5870 here: https://tools.ietf.org/html/rfc5870

The uri also supports passing altitude, uncertainty, and alternate coordinate reference systems (WGS84 is the default).  Supporting anything other than lat and lon is a lower priority.

The inclusion of Beacons such as the Garmin Chirp has created an interesting possibility for Geocaching, but due to the costly ($22USD) and proprietary hardware (the chirp) and relative rareness of the ANT+ receivers (other than expensive GARMIN GPS units), the Chirp based geocaches are rear and far in-between.   NFC Tags which are a fraction of the cost (approximately $1.30USD in small volumes) and most modern phones and tablets can now or will soon be able to read them.  

The following screen shot illustrates how the NFC Tag is programmed (See records 0 and 1 at the bottom of the screen):

![screenshot_2015-01-06-00-28-32](https://cloud.githubusercontent.com/assets/7775378/5625302/db80261a-953d-11e4-9938-c3fb255b11a1.png)

The following screen shot illustrates what my phone displays when the tag is discovered.  The record 0 (geo: uri link) above can be handled by 5 different applications on the phone (but not c:geo).  The record 1 text  is also displayed at the bottom of the phone screen.

![screenshot_2015-01-06-00-27-44](https://cloud.githubusercontent.com/assets/7775378/5625303/e8b6d2a2-953d-11e4-9227-8bf0bffb6325.png)

**Comment by Lineflyer** [comment]
What would you suggest as an appropriate action for c:geo?
It could IMHO be creating a waypoint from it, starting the compass, etc.For the beginning maybe we could just pass the coords over to the anywhere screen?

**Comment by TravelingGeek** [comment]
I would think it would be used most often when you are already in the geocache details screen or possibly in the compass.  In that scenario, the new coords would most likely be the next waypoint in a multi or the final, so I think the most benefit would be to allow the user to add a waypoint with the standard existing options, including updating geocaching.com.   

The secondary scenario of a new geo: waypoint when the users is not currently in details of a cache, or potentially not having c:geo open is clearly a possibility.  I think going to the anywhere screen would make sense.  The user could then find a cache and go into the details and then scan the tag again to add a waypoint to the now open cache.

**Comment by Bananeweizen** [comment]
@TravelingGeek I believe your previous comment makes a wrong assumption. If we were directly supporting the geo intent, the app would be selectable as intent target in almost all cases, where a navigation selection occurs in Android nowadays. That is when clicking on coordinates in an appointment in the calendard, when invoking a navigation intent in nearly any software, when running some app that wants to invoke Google Maps and so on.

Therefore I believe that the majority of use cases of calling this intent in c:geo would be some workflow, where c:geo was not open at all or where the coordinates are not related to a cache at all. E.g. people just thinking: "Okay, let's use c:geo for navigation, it has a nice map" (and I've heard such statements in real life).

That's why I imagine that a (popup) selection would be the best thing to do if c:geo is invoked for a c:geo intent, and that popup would need to list the above workflows (add as waypoint, show on map, show caches around, ...) as explicit selection. With making assumptions we would just make our life very hard and people very unhappy, as c:geo would just "do something".

**Comment by TravelingGeek** [comment]
@Bananeweizen you are right.  Prompting the user for where to go is a good design.

**Comment by HolgerJeromin** [comment]
My use case for that would be. I plan a trip and have the region open in osmand map or http://osm.org. Both have links to open external apps via the geo: intent

If c:geo would listen for this intent i could jump to c:geo. It should show "caches at this coordinate" or the map view of this coordinate.
And yes, i want this in "almost all cases, where a navigation selection occurs on android":
I have an appointment in my calendar. I click on the location to quick check if there are nice caches around.
For example the OSM Editor vespucci responds to the geo intent and so i can quick load the area to improve the map.

**Comment by fm-sys** [comment]
This should be implemented with #8934, but while testing I noticed that c:geo is not listed in the navigation intent chooser on my device... Looks like we have a bug here
