### ISSUE TITLE
DNF log counts as found cache

### ISSUE THREAD

**Issue by reuenthal** [cgeo/cgeo#4589]
I believe I have found a minor issue with c:geo.  When logging in, cgeo gives you the number of your found caches, in my case 424.  Now, using c:geo, I submit a DNF log for a cache.  When I return to the initial screen, the number of found caches is now 425 -- cgeo mistakenly has counted the DNF as a find.  Only when cgeo has to go to the GS server (e.g. when I ask for nearby caches) does the number drop back to the correct value of 424.
I have seen this issue when reporting DNFs (as usual) on caches hidden by others, but I have also tested it by reporting a DNF on one of my caches -- same problem.

**Comment by Lineflyer** [comment]
This is another manifestation of the problem described in #593.
Therefore I merged the information to that issue.

Thanks for reporting!
It is a long-time known bug.
