### ISSUE TITLE
Favor cgeo over other ways to handle cache URIs transmitted via NFC

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4590]
When cgeo is used to beam a cache to another device, we do not explicitly request that cgeo is open if present. One one of my devices, this leads to a browser being opened instead of cgeo, because I once opted out for Firefox instead of cgeo on this tablet. However, here the intention is clear: beaming from cgeo should favor opening cgeo on the remote device. We need to add an AAR (Android Application Record) to the Ndef message.

I propose to include one commit (57c41e935ea98738fec5bcdd79ccf854d98cb8af) as soon as possible in the release, as it will not change the behavior but will ensure that explicit requests to use cgeo will be handled properly. The second commit (525d94c31353d81760b73cf79682dd1988fa407e) will then be added to the master branch only.

While this way of doing is not strictly necessary, that would allow people with version *N-1* of cgeo to receive explicit beams sent by version *N* as well.

Thoughts?

**Comment by Bananeweizen** [comment]
Sounds reasonable to me, especially given that you tested the changes.

**Comment by SammysHP** [comment]
Sounds good.

**Comment by samueltardieu** [comment]
Merged as indicated and closing. Thanks @Bananeweizen and @SammysHP for the feedback.
