### ISSUE TITLE
Refreshing without progress and ANR afterwards

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4591]
2015.01.06-RC1

- Open a list of saved caches (50 caches in my case)
- Select Menu - Refresh all
- Progress will get stuck at some point, no more messages in the debug log
- Abort the refresh
- Trying to open a saved cache afterwards => Stuck on loading cache-details and ANR short after
- Trying to start another refresh of the list => No progress and ANR short after

As discussed on IRC this might be caused by a possible race condition introduced in cdf5c657ef5168018a5c4805778876dfeb5343e5

**Comment by samueltardieu** [comment]
Note for ANR : "W/SQLiteConnectionPool(29624): The connection pool for database '/data/data/cgeo.geocaching/databases/data' has been unable to grant a connection to thread 1 (main) with flags 0x5 for 30.000002 seconds."

**Comment by samueltardieu** [comment]
The problem was that a thread with a transaction first locks the database, then the statements it will use, while a thread without a transaction locks the statements and execute them (which locks the database). We then get deadlocks.
