### ISSUE TITLE
Request static maps only if they are missing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4592]
Thinking about the speed improvement we recently made by skipping static maps download if we get a 304 error I came to the following proposal:

Currently we refresh static maps on each refresh of a cache.
While this might be not so relevant for single cache refresh, it is a huge portion for refreshing (large) lists.

IMO in most cases the refresh of those maps will just have no relevant information. I do only see special cases in which a new download is meaningful:
- New waypoints have been added to a cache (in case static maps for WP is enabled)
- Cache coordinates have changed (quite rare condition)
- Map content might have been updated (quite rare condition)

In order not be generate a lot of conditions I would simply suggest to skip all already existing static maps on batch refresh of caches. They should be reloaded still on refresh of a single cache. 

I think in most cases the maps won't need any update, additionally a great percentage of users will not actively use them (except the map preview in cache details) and even if they use them a need for update will be minimal.

**Comment by samueltardieu** [comment]
When refreshing caches, we already start with caches which don't already have static maps so that they get a better chance at being refreshed before the limit is reached: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/CacheListActivity.java#L1188-1191

Isn't that what you are wanting?

**Comment by Lineflyer** [comment]
Basically yes. That is already a good strategy and should stay.
But I was also thinking about a further improvement of the refresh speed by not refreshing exisiting static maps **at all** (As said above: The chance that the redownload has new information is really small).

Of course, there might be a few users who batch update caches explicitly to get the static maps updated, but I doubt that there are so many of them. As long as the static maps are there, most users will be fine with it.

The optimum case would be to have a functionality which allows refresh of only parts of the cache data (e.g. only static maps, only logbook)....but anyway skipping existing maps completely would allow short term speed improvement.

**Comment by marco-dev** [comment]
Just update not existing maps on batch update should be doable.

**Comment by Lineflyer** [comment]
Closing this issue as obsolete, as Google static maps are no longer available (without payment).
So whatever replaces them needs a new implementation anyway.
