### ISSUE TITLE
cgeo should be able to read trackable URI from NFC

### ISSUE THREAD

**Issue by arteos** [cgeo/cgeo#4595]
I have written a URL for a trackable to an NFC tag but when I scan it I only get the option to open it in one of my two browsers.

If I click the same link in for example an email I get the option to also open it in c:geo.

As I understand this is because Android doesn't detect c:geo as capable of opening NFC url:s.
I also tried writing the URL for a geocache to a NFC tag with the same result, I only get to chose one of my two browser for opening it when scanned.

(I would be really neat to have this feature since the NFC tag in question is implanted in my hand and I want people to be able to log it easily with c:geo when scanning it)

I found something related to this issue here: http://android.stackexchange.com/questions/84173/how-to-set-default-browser-used-by-nfc

**Comment by samueltardieu** [comment]
Can you please with today's nightly build (see http://www.cgeo.org/nightly.html)? If this still doesn't work, please describe the exact content of the tag.

**Comment by TravelingGeek** [comment]
arteos, can you post the url (change the code if you want) you are using and how you stored it on the NFC?   I would like to replicate the behavior here.

**Comment by arteos** [comment]
Thanks for quick response.

With the night build one of my tags programmed to open http://coord.info/GC1AT39 opens directly in c:geo.

But the other one programmed to open the travel bug at http://www.geocaching.com/track/details.aspx?tracker=38k2tv does not open in c:geo, I only get the choice to open it with chrome or built in browser when scanned from the tag. But if I click it in gmail I get the choice to open it in c:geo.

I stored the URL as a URL record with NFC Tools.

**Comment by samueltardieu** [comment]
I added the logic to open a geocache from a NFC URI yesterday to cgeo. This has not yet been added for trackables. I'll rename this issue and assign it to myself.

**Comment by samueltardieu** [comment]
This has now been implemented, and will be present in the next nightly build (which might happen before tomorrow, your cgeo will propose to auto-update if you are running a nightly).

**Comment by TravelingGeek** [comment]
Thank you. I will verify it on multiple tags/ devices when the build is available.

**Comment by samueltardieu** [comment]
It is available now.

**Comment by TravelingGeek** [comment]
Hi,

I tested in 2015-01-07-NB1 and it did not work on either HTC One M8 or Moto
Razzr Maxx HD.
The HTC had c:geo previously installed and was power cycled after the
nightly build was upgraded.
The Razzr had the c:Geo NB was the first time install on that device.

In both cases, other applications were identified as geo: applications.

Please let me know if there is other information that would help.

**Comment by arteos** [comment]
Worked perfectly for me =) HTC One M7 with Android 4.4.3

**Comment by TravelingGeek** [comment]
My mistake, I posted above in error.  The nightly build works perfect for me for the url to a trackable.  Nice implementation.

**Comment by arteos** [comment]
Thanks for superfast response and action btw =) Never seen the like.
Donation sent.

**Comment by SammysHP** [comment]
Thank you!

**Comment by samueltardieu** [comment]
Thanks @arteos :)
