### ISSUE TITLE
HTC One (M7): Compass rotates in 180° steps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4599]
Split up from #4552 

Following the above mentioned issue and the reports we get on support mail and Facebook we can break down current compass problem to this specific one:

Device: HTC One (M7)
Android: 4.4.3

Description:
- When rotating the phone the compass does not turn steady but will jump by 180° as soon as this angle is reached
- Same bevavior with the arrow on map
- Independently of Google Play Service settings
- Not yet tested if Low-power mode On/Off makes any difference
- At the same time other compass apps are working normal (i.e. the sensors itself seem to work fine)
- Current RC-version 2015.01.07-RC does not solve the problem

I sent a video from a user showing that issue to the cgeo-dev mailing list on 07.01.2015. 

@arteos
- Can you kindly test if enabling "Low power" in c:geo Menu - Settings - System makes any difference for this issue?
- Can you please fall back to version 2014.11.04 (Download from here: https://github.com/cgeo/cgeo/releases/tag/market_20141104) and check if the compass is normal in this version?

There are also reports with HTC One Mini, Android 4.4.2 but sadly without a clear description whether it is the same problem (jumping by 180°). I will ask those users via support mail to describe in more detail.

**Comment by arteos** [comment]
Low power mode didn't solve it.
But the older version solved it, seems to work as it should with 2014.11.24

**Comment by arteos** [comment]
I also tried https://github.com/cgeo/cgeo/releases/tag/market_20141209 now
and it doesn't work.

Reverting back to 2014.11.04 makes it work.

**Comment by samueltardieu** [comment]
@arteos Could you please try the latest -RC or the latest nightly (both were just built) and copy the information given in "About/System" (this is a new page in "About" that I just added) here?

**Comment by arteos** [comment]
Sure. Couldn't copy the text but I've attached a screenshot.

**Comment by Lineflyer** [comment]
Attachments wont work via mail. You have to visit the github page and insert it there or send a link.

**Comment by samueltardieu** [comment]
Moreover, the text should be copiable…

**Comment by arteos** [comment]
Yeah it was, my bad.

--- System information ---
Device: HTC One (htc_europe, htc)
Android version: 4.4.3
Android build: KTU84L release-keys
Cgeo version: 2015.01.08-NB1-ab3f96d
Play services: present
Use Play services: yes
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
--- End of system information ---

**Comment by Lineflyer** [comment]
Where does this come from:

> Compass capabilities: yes

**Comment by samueltardieu** [comment]
@Lineflyer From the nightly build.

**Comment by Lineflyer** [comment]
Ah, you changed it again.

**Comment by samueltardieu** [comment]
Well, yes, because it doesn't have the same significance.

**Comment by samueltardieu** [comment]
@arteos Could you try the compass with the -NB2 (just built) to see if it makes things better?

**Comment by arteos** [comment]
It works! Well done!

**Comment by Lineflyer** [comment]
Thanks to you @arteos for your willingness to test on short term.

Assigning to me for regression test on my available devices.

**Comment by Lineflyer** [comment]
I have here an HTC One Mini with Android 4.2.2 / HTC-Sense 5.0 / HTC SW 1.32.401.2 / HTC SDK API Level 5.41. (An update is available but I will keep this version to be able to test an non working rotation sensor).

I can reproduce this problem on that device using 2014.12.22.
Furthermore I can also confirm that the problem is solved with 2015.01.08-NB3

**Comment by Lineflyer** [comment]
HTC Wildfire S A510e
Android 2.3.5
2015.01.08-NB4-8d8a9d9
Play=present and used
Low power=Off
Compass=yes
Rotation=present
Geomagnetic=absent
Orientation=present

Compass was working with 2014.12.22 and is still working with 2015.01.08-NB4.

**Comment by Lineflyer** [comment]
--- System information ---
Device: C6903 (C6903, Sony)
Android version: 4.4.4
Android build: 14.4.A.0.157
Cgeo version: 2015.01.08-NB4-8d8a9d9
Play services: present
Use Play services: yes
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
--- End of system information ---

Compass working normal with 2015.01.08-NB4

**Comment by samueltardieu** [comment]
Since you have a geomagnetic rotation sensor on the C6903, can you also please try in low-power mode?

**Comment by Lineflyer** [comment]
Device=GT-P3100
Android= 4.2.2
Play=present and used
Low power=Inactive
Compass=yes
Rotation=absent
Geomagnetic=absent
Orientation=present

Compass working normal with 2014.01.08-NB4

**Comment by Lineflyer** [comment]
Device=Z30 (Blackberry)
Android: 4.2.2

Play=absent 
Low Power= inactive
Compass=yes
Rotation=present
Geomagnetic=absent
Orientation=present

Compass working normal with 2015.01.08-NB4

**Comment by Lineflyer** [comment]
> Since you have a geomagnetic rotation sensor on the C6903, can you also please try in low-power mode? 

Will order the test...its crowd testing (all my fellow geocachers are activated :) )

**Comment by Lineflyer** [comment]
Here is the low power version:



--- System information ---
Device: C6903 (C6903, Sony)
Android version: 4.4.4
Android build: 14.4.A.0.157
Cgeo version: 2015.01.08-NB4-8d8a9d9
Play services: present
Use Play services: yes
Low power mode: active
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
--- End of system information ---

Compass working normal!

**Comment by Lineflyer** [comment]
Device=GT-i9305 (S3)
Android=4.3
Play=present and used
Low power=inactive
Compass=yes
Rotation=present
Geomagnetic=absent
Orientation=present

Compass working normal with 2015.01.08-NB4

**Comment by Lineflyer** [comment]
Device=ZTE Grand Memo LTE
Android=4.1.2
Play=present and used
Low power=inactive
Compass=Yes
Rotation=present
Geomagnetic=absent
Orientation=present

Compass working normal with 2015.01.08-NB4.

Thats all folks! :)

**Comment by samueltardieu** [comment]
So, would you like the `master` branch to be merged into `release`?

**Comment by Lineflyer** [comment]
We need this fix on release, so if that is the best option to have it: Yes, please.

**Comment by samueltardieu** [comment]
Done.
