### ISSUE TITLE
Sony Xperia SP (C5303): Compass rotatation sluggish

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4600]
Split up from #4552

Device: Sony XPeria SP (C5303), FW.205
Android: Android 4.3

Description:
- If the phone is rotated normally the arrow is only reacting very sluggish and never reaches the correct direction. If the phone is rotated fast the arrow aso moves really fast but also ends up in a totally wrong direction.
- Independently of using "Google Play Services"

It is currently unclear whether this happens with and/or without "low power mode".
I asked via support mail but got no feedback up to now.

**Comment by samueltardieu** [comment]
Please ask the user to try a recent nightly build, send the About/System information, and report if it changes something to use low-power/regular modes.

**Comment by Lineflyer** [comment]
2 users asked for installation of NB.

**Comment by Lineflyer** [comment]
Received a feedback from one user, that with 2015.01.08-RC1 it is working again.

**Comment by Lineflyer** [comment]
Second user also confirmed, that the problem is fixed with 2015.01.08-RC1.
