### ISSUE TITLE
Compass problems solved by pure reinstallation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4601]
In #4552 and also on support mail an unusual amount of people are describing that a pure deinstallation + new installation of version 2014.12.22 solved their compass problem.

All of them had the problem, that the compass was randomly moving or fixed to a random position and it was working normal in other compass apps at the same time.

I was wondering if there is any "default value", "compass state" or alike we store somewhere which is incorrect / out of range and might only get cleared on a new installation. 
This is the only reason I could imagine where a reinstallation could make any difference.

**Comment by samueltardieu** [comment]
@Lineflyer Can you ask them to test a recent RC?

**Comment by Lineflyer** [comment]
Closing as it neither can be reproduced nor did we get more of these occurences on support mail.
I guess there might have been some device caused effects.
