### ISSUE TITLE
Add system information in "about" and mails

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4602]
We should add more specific system information that would help us debug problems tied to specific models.

**Comment by Lineflyer** [comment]
Very good. Thanks.


Von Samsung Mobile gesendet

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Samuel Tardieu <notifications@github.com> </div><div>Datum:08.01.2015  14:48  (GMT+01:00) </div><div>An: cgeo/cgeo <cgeo@noreply.github.com> </div><div>Betreff: Re: [cgeo] Add system information in "about" and mails (#4602) </div><div>
</div>Closed #4602 via c5076ec.
