### ISSUE TITLE
System information can not be copied 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4605]
While on my Samsung S4 I can copy the system information to the clipboard using 2015.01.08-RC I am unable to do so with an HTC One Mini using 2015.01.08-NB3.
Not sure whether it is caused by the different c:geo versions or just a bug of the HTC?

**Comment by Lineflyer** [comment]
Same on HTC Wildfire, Android 2.3.5 and ZTE Grand Memo LTE, Android 4.1.2 all with 2015.01.08-NB4. But Samsung S4 with 2015.01.08-NB4 is still working.

So either something device specific or I am too stupid to use this function on the other devices (simply long press on the sys info text).

**Comment by Bananeweizen** [comment]
Please check with the next nightly. I've set the attribute explicitly again at runtime. Nevertheless, this will only work for > 3.0 generally, as that attribute was only introduced in that API level.

**Comment by mucek4** [comment]
I didn't find a way to copy it no matter what I tried. Can't we just add 2 buttons (copy to clipboard, send via email)?

**Comment by Lineflyer** [comment]
@mucek4 Send via mail is not needed as it is contained when using the mail link already now. What device is not working for you?

I tested with the ZTE Grand Memo LTE, Android 4.1.2 again with current NB and it has still the mentioned problem.
I guess a copy button might be a good idea.

**Comment by samueltardieu** [comment]
Don't hesitate to change the style if it isn't right.
