### ISSUE TITLE
Unable to parse home location warning

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4606]
Happend when logging in as basic member with 2015.01.08-NB4:
```
21:41:03.405 Warning cgeo 7992  [main] Unable to parse home location Dusseldorf
21:41:03.405 Warning cgeo 7992  cgeo.geocaching.location.Geopoint$ParseException: Could not parse coordinates as LAT: "Dusseldorf"
21:41:03.406 Warning cgeo 7992  	at cgeo.geocaching.location.GeopointParser.parseHelper(GeopointParser.java:136)
21:41:03.406 Warning cgeo 7992  	at cgeo.geocaching.location.GeopointParser.parse(GeopointParser.java:59)
21:41:03.406 Warning cgeo 7992  	at cgeo.geocaching.location.Geopoint.<init>(Geopoint.java:57)
21:41:03.406 Warning cgeo 7992  	at cgeo.geocaching.sensors.GeoData.getInitialLocation(GeoData.java:95)
21:41:03.406 Warning cgeo 7992  	at cgeo.geocaching.playservices.LocationProvider.<init>(LocationProvider.java:127)
21:41:03.406 Warning cgeo 7992  	at cgeo.geocaching.playservices.LocationProvider.getInstance(LocationProvider.java:44)
21:41:03.406 Warning cgeo 7992  	at cgeo.geocaching.playservices.LocationProvider.get(LocationProvider.java:65)
21:41:03.407 Warning cgeo 7992  	at cgeo.geocaching.playservices.LocationProvider.getMostPrecise(LocationProvider.java:91)
21:41:03.407 Warning cgeo 7992  	at cgeo.geocaching.sensors.Sensors.setupGeoDataObservables(Sensors.java:64)
21:41:03.407 Warning cgeo 7992  	at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:75)
21:41:03.407 Warning cgeo 7992  	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
21:41:03.407 Warning cgeo 7992  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4684)
21:41:03.407 Warning cgeo 7992  	at android.app.ActivityThread.access$1400(ActivityThread.java:159)
21:41:03.407 Warning cgeo 7992  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
21:41:03.407 Warning cgeo 7992  	at android.os.Handler.dispatchMessage(Handler.java:99)
21:41:03.408 Warning cgeo 7992  	at android.os.Looper.loop(Looper.java:137)
21:41:03.408 Warning cgeo 7992  	at android.app.ActivityThread.main(ActivityThread.java:5419)
21:41:03.408 Warning cgeo 7992  	at java.lang.reflect.Method.invokeNative(Native Method)
21:41:03.408 Warning cgeo 7992  	at java.lang.reflect.Method.invoke(Method.java:525)
21:41:03.408 Warning cgeo 7992  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
21:41:03.408 Warning cgeo 7992  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
21:41:03.408 Warning cgeo 7992  	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by samueltardieu** [comment]
Interesting, it looks like the home location on geocaching.com web site can be set to a string which does not directly represent coordinates. I don't know how to do it.

**Comment by Lineflyer** [comment]
This is how it looks on this account. Don't know how the user managed to set it:

![2015-01-08 21_55_21-home location](https://cloud.githubusercontent.com/assets/949669/5670547/248bf574-9781-11e4-8257-f1d3106152b4.jpg)

**Comment by samueltardieu** [comment]
I don't know how they manage to save it, as soon as I press "enter" or "Search" (also tried with a basic member), it stores it as a set of coordinates.

I'd like to know if this is a common occurrence (and how to test it), using a geocoder wouldn't be a big deal here.

**Comment by Lineflyer** [comment]
Maybe it was asked as a string during account creation and never modified by the user afterwards or something alike.

Is there any feature on the website itself which uses this? So I can test if gc.com itself understands it or if it is just a website burb.

**Comment by samueltardieu** [comment]
How was the account created? Using the website or the application from geocaching.com?

I think this is used on the home page for pre-filling the search box.

**Comment by Lineflyer** [comment]
I do not remember :(

**Comment by Lineflyer** [comment]
However from the location we retrieve it, seems it can somehow either be coords or a string (which represents the location).
Using a geocoder has also a disadvantage in this case...if it matches wrong we might get user reports which are not easy to debug....better than to default to Paris because for this we have at least a FAQ entry telling to activate GPS and/or set home coords on the website.

**Comment by samueltardieu** [comment]
Yup. Let's close this with won't fix.
