### ISSUE TITLE
Have a "Check password" function for GCVote in settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4607]
Currently the user can enter his password put it will only be checked later on when placing the first vote.
And feedback on a wrong password is then only shown in a toast message.

I suggest to have a menu item "Check login" in the GCVote settings which sends a request to check whether the password is ok and returns an appropriate result to the user.

I tested how this could be done and found that we can easily check by a simple request ommitting the parameter ```cacheID```:
```
http://gcvote.com/getVotes.php?version=cgeo&userName=Lineflyer&password=test
```
If the password is wrong we receive:
```
<votes userName='Lineflyer' currentVersion='3.2b' securityState='locked' loggedIn='false'>
<errorstring></errorstring>
</votes>
```
If it is correct we get:
```
<votes userName='Lineflyer' currentVersion='3.2b' securityState='locked' loggedIn='true'>
<errorstring></errorstring>
</votes>
```

**Comment by Lineflyer** [comment]
This could also "solve" #4248

**Comment by samueltardieu** [comment]
The proposed check is not that simple from an UI point of view: if it fails, it does not mean that the password is wrong, it may mean that the *username* (which comes from the GC configuration) is wrong. It might happen when people switch accounts (for example to log on the field when only one of the persons has a smartphone) but don't think about gcvote.

We might need to present the user using the settings with the username that will be used for GCVote.

**Comment by madankumarbaskaran** [comment]
May I work on this feature request?

**Comment by samueltardieu** [comment]
Sure!

**Comment by samueltardieu** [comment]
(assigning myself as point of contact)

**Comment by madankumarbaskaran** [comment]
Small brief of #4607 and solution for it - "Incorrect password in GCVote is informed to user only after first vote in GCVote.com; To prevent it, Check login (like Geocaching.com services) need to be created with username and password, so user can verify the credentials after entering there username/password". Can you please let me know if my understanding is correct?. Your help is appreciated.

**Comment by rsudev** [comment]
The username for gcvote shouldn't be set explicitly, but taken from the settings for geocaching.com (IMO). But it should be presented to the user, so she is aware fo the name used.
The check part is clear I think. The possibility for setting the password already exists.

**Comment by Lineflyer** [comment]
This is done.
THanks to @madankumarbaskaran for your contribution
