### ISSUE TITLE
Own rating is also saved if placing the vote was not succesful

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4608]
2015.01.08-RC1

- Be sure your gcvote password is wrong in settings
- Open a saved found cache
- Select Menu - Vote
- Select a score (in case it already has an own vote, select a scrore different to the existing) and send it
- An error toast is shown about the wrong password but still the new own rating is saved to the cache

**Comment by samueltardieu** [comment]
@Lineflyer Please test and ask for inclusion in `release`.

**Comment by Lineflyer** [comment]
I would prefer (due to version handling) to have it in the release branch now and have a new RC to test it, if it is possible to revert this in case it fails.

**Comment by samueltardieu** [comment]
Merged in release.

**Comment by Lineflyer** [comment]
Confirmed working with 2015.01.11-RC.
