### ISSUE TITLE
Integrate retrolambda to our development tools

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4612]
[Retrolambdda](https://github.com/orfjackal/retrolambda) lets one use lambda expressions from Java 8 in Java 6, which is currently the target we use for Android.

Integrating Retrolambda into our compilation chains would let us have clearer, shorter code at many places. It would need to be done:
- [ ] for Gradle build (which itself is not polished at all and would need to get migrated to a more recent Gradle version)
- [ ] for ANT build (unless we deprecate it to use the Gradle build)
- [ ] for Eclipse
- [ ] for Intellij IDEA / Android Studio (although those could use the Gradle build)

**Comment by Bananeweizen** [comment]
I'm not sure if I like that. This requires to completely disable the Eclipse internal incremental build, thereby throwing away one of its most useful features. I suggest that we first create a hello world project only, which needs to run in these different environments, before actually starting on our real sources. Just to get a better impression if this works out at all for the different developers. A tutorial for Eclipse is at https://hakanyamanyar.wordpress.com/2014/07/08/using-java-8-lambda-expressions-in-android-developer-tools/, which basically relies on gradle.

I assume that when going this way, the Ant build could be removed in favor of Gradle.

**Comment by samueltardieu** [comment]
Since I'm no longer concerned and was the one pushing for it, let's close it indeed!
