### ISSUE TITLE
"c:geo review" in GooglePlayBooks

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4614]
I have just seen that there is a booklet offered in Google Play called "c:geo review" using our logo.
Is that something agreed with us:
https://play.google.com/store/books/details/c_geo_Booklet_c_geo_Review?id=L3vwBQAAQBAJ

Is is sold by "Google Ireland Ltd".

**Comment by SammysHP** [comment]
https://support.google.com/legal/answer/3110420?rd=2

**Comment by mucek4** [comment]
Just to let you know
```Sorry! Books on Google Play is not available in your country yet.```

**Comment by Lineflyer** [comment]
The form to complete at Google in order to alert them (link behind the URL posted by @SammysHP) requires quite some information where I would be unsure about what to enter here.
It would be best if @mucek4 would complete it, because they probably doublecheck if the owner of the c:geo PlayStore account contacted them. 

But yes, I think we should do that.
I think there is nothing to be afraid, this booklet is just a new method of spam to gain money from it. I am sure there is no one behind it but a "bot" or something similar.

**Comment by mucek4** [comment]
@Lineflyer I can't see anything as I can't acces Books at google play.

**Comment by Lineflyer** [comment]
@mucek4 Can you read that: https://support.google.com/legal/contact/lr_dmca?product=books

**Comment by mucek4** [comment]
I can see this, but I have no idea what is beeing problematic about book I can't get

**Comment by SammysHP** [comment]
@mucek4 See mailing list (in a few minutes).

**Comment by Lineflyer** [comment]
The main thing is, that he is using our logo (for which we have the copyright)...most probably to try to gain money from clueless people who trap into this.

**Comment by SammysHP** [comment]
The logo and the name.

**Comment by Lineflyer** [comment]
I almost forgot about this.
I submitted a report to Google for that "c:geo Review" stating illegal use of name and logo.

**Comment by Lineflyer** [comment]
```
Hi,

Thanks for reaching out to us!

We have received your legal request. Please note that Google will only email you about this notice if we need additional clarification. If we process and remove all of the identified content from the URLs you provided and do not receive a counternotice, you will not receive any further e-mails about it from Google.

Regards,
The Google Team
```

**Comment by Lineflyer** [comment]
>Hello,
>
>Thanks for reaching out to us.
>The material in question has been found to violate our policies, and we are working to remove it from our services. Although the reported URL(s) is still active, the book(s) in question can no longer be purchased or found in a search on Google Play. We appreciate your assistance in maintaining the quality of our products and hope you will contact us if you encounter other issues in the future.
>
>Regards,
>The Google Team
