### ISSUE TITLE
Status of a cache to be exportable?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4615]
Version 2015.01.12:
- Open live map
- Set live map strategy to fast 
- Scroll to an area without any saved caches
- Select Menu - Show as List
- Select Menu - Export - GPX

The resulting GPX is empty (besides the header). 
It seems meaningful, that nothing is exported because we have nothing but the name, the type and the geocode of those caches.

On the other hand:
If I perform a nearby search and export it to the GPX, the caches are actually exported with what we have (in this case D/T, favpoints, coords but still no description).

I don't know what conditions apply for the cache to be exportable.
Mabye we should gnereally disable exporting if the caches are not stored?

**Comment by Bananeweizen** [comment]
Caches without coordinates are skipped in the export, therefore your's is empty.

**Comment by Lineflyer** [comment]
OK, without coords an export would be meaningless, therefore "Wont Fix".
