### ISSUE TITLE
Wrong location when on "Home coords"

### ISSUE THREAD

**Issue by Krakapouet** [cgeo/cgeo#4620]
Concern 2015.01.12
Now I'm located 3000 km from my home ! My coordinates didn't change in geocaching.com so there is a bug for sure.
More enoying is the fact that when opening cgeo the map shown is not the one on the screen when closing the app.
Better to stay on 2014.12.22 at the moment ;-)

**Comment by Lineflyer** [comment]
Can you please post more details:
1. the system information shown in About c:geo - System
2. What is shown on the lower right in c:geo main screen in the case your location is wrong (e.g. "Fused", "Network", "Last position",...)

**Comment by Lineflyer** [comment]
There is another user on FB and support telling, that she is located in "Ukraine" as soon as GPS is disabled and "Home coords" is shown on the lower right.
I asked to doublecheck the home location setting on gc.com and are waiting for feedback. But she confirmed already before, that the home location is set to a position in England.

**Comment by Lineflyer** [comment]
Ok, I can now somehow reproduce that on 2015.01.22-NB:
- Disable Google Play Location Services, Disable GPS and all other location sources
- Set home coords to Dublin on gc.com
- Start c:geo

Result:
- "GPS disabled" and "home coords" is shown on the mainscreen
- The Geoprovider reports another (random?) location, in my case: "Germany, Essen" (which is also different from my current or last location)
- Nearby search returns results around this wrong location
- Live map opens at this wrong location

From the log you can see that
- Home coords are used due to absence of GPS
- The home location from gc.com is retrieved OK (Dublin coords)
- The following nearby search is started for a wrong location

```
16:07:21.158 Info cgeo 15352  [main] Google Play services are available
16:07:21.158 Debug cgeo 15352  [main] OrientationProvider: sensor found
16:07:21.158 Info cgeo 15352  [looper callbacks] No last known location available, using home location
16:07:21.158 Debug cgeo 15352  [looper callbacks] GeoDataProvider: starting the GPS and network listeners
16:07:21.268 Debug cgeo 15352  [network-1] GET http://status.cgeo.org/api/status.json?version_code=30150122&version_name=2015.01.22-NB-c0bddd3&locale=de_DE
16:07:21.378 Info cgeo 15352  [main] Starting cgeo.geocaching 30150122 a.k.a 2015.01.22-NB-c0bddd3
16:07:21.378 Debug cgeo 15352  [RxCachedThreadScheduler-2] Database clean: started
16:07:21.378 Debug cgeo 15352  [looper callbacks] GpsStatusProvider: starting the GPS status listener
16:07:21.378 Debug cgeo 15352  [RxCachedThreadScheduler-2] Database clean: removing 0 geocaches from listId=0
16:07:21.378 Debug cgeo 15352  [RxCachedThreadScheduler-2] Database clean: removing obsolete log images records
16:07:21.378 Debug cgeo 15352  [network-2] GET https://www.geocaching.com/login/default.aspx
16:07:21.378 Debug cgeo 15352  [network-3] GET http://www.opencaching.de/okapi/services/users/user?fields=username%7Ccaches_found&langpref=de%7Cen&oauth_consumer_key=deleted
16:07:21.378 Debug cgeo 15352  [RxCachedThreadScheduler-2] Database clean: finished
16:07:21.598 Debug cgeo 15352  [network-3] 200 (211 ms) GET http://www.opencaching.de/okapi/services/users/user?fields=username%7Ccaches_found&langpref=de%7Cen&oauth_consumer_key=deleted
16:07:21.708 Debug cgeo 15352  [network-1] 200 (459 ms) GET http://status.cgeo.org/api/status.json?version_code=30150122&version_name=2015.01.22-NB-c0bddd3&locale=de_DE
16:07:22.368 Debug cgeo 15352  [network-2] 200 (1064 ms) GET https://www.geocaching.com/login/default.aspx
16:07:22.478 Info cgeo 15352  [network-2] Already logged in Geocaching.com as Lineflyer (Premium Member)
16:07:22.478 Info cgeo 15352  [network-2] Geocaching.com language already set to English
16:07:22.478 Debug cgeo 15352  [network-2] GET http://www.geocaching.com/email/
16:07:23.018 Debug cgeo 15352  [network-2] 200 (552 ms) GET http://www.geocaching.com/email/
16:07:23.238 Debug cgeo 15352  [network-2] GET https://www.geocaching.com/account/settings/preferences
16:07:23.238 Debug cgeo 15352  [network-6] GET https://www.geocaching.com/account/settings/homelocation
16:07:24.548 Debug cgeo 15352  [network-6] 200 (1318 ms) GET https://www.geocaching.com/account/settings/homelocation
16:07:24.548 Info cgeo 15352  [network-6] Setting home location to N 53° 20.966′ W 6° 15.606′
16:07:24.658 Debug cgeo 15352  [network-2] 200 (1421 ms) GET https://www.geocaching.com/account/settings/preferences
16:07:28.258 Debug cgeo 15352  [looper callbacks] GpsStatusProvider: stopping the GPS status listener
16:07:28.368 Debug cgeo 15352  [looper callbacks] OrientationProvider: starting the orientation provider
16:07:28.368 Debug cgeo 15352  [network-9] GET http://www.opencaching.com/api/geocache.gpx?log_limit=0&hint=false&description=none&limit=20&center=51.507317%2C7.000000&Authorization=CgdDaUb9EHGug3Ac
16:07:28.478 Info cgeo 15352  [network-7] Skipping caches found or hidden by user.
16:07:28.478 Debug cgeo 15352  [network-7] GET http://www.geocaching.com/seek/nearest.aspx?lat=51.50731666666667&lng=7.0&tx=9a79e6ce-3344-409c-bbe9-496530baf758&f=1
16:07:28.588 Debug cgeo 15352  [network-8] GET http://www.opencaching.de/okapi/services/caches/shortcuts/search_and_retrieve?langpref=de%7Cen&oauth_consumer_key=deleted
16:07:28.808 Debug cgeo 15352  [network-8] 200 (231 ms) GET http://www.opencaching.de/okapi/services/caches/shortcuts/search_and_retrieve?langpref=de%7Cen&oauth_consumer_key=deleted
16:07:28.808 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC8AE8]) returned no results
16:07:28.808 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC10FE7]) returned no results
16:07:28.808 Debug cgeo 15352  [network-8] DataStore.loadCaches([OCA89A]) returned no results
16:07:28.808 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC8AF6]) returned no results
16:07:28.808 Debug cgeo 15352  [network-8] DataStore.loadCaches([OCB0FB]) returned no results
16:07:28.808 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC8AD3]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC8B4A]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC7C89]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC9DCB]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC8764]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OCDAE5]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC1016B]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC8ABE]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OCEABC]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OCB31B]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OCEAD1]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC91BF]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OC529C]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OCFA73]) returned no results
16:07:28.918 Debug cgeo 15352  [network-8] DataStore.loadCaches([OCA43D]) returned no results
16:07:29.788 Debug cgeo 15352  [network-7] 200 (1282 ms) GET http://www.geocaching.com/seek/nearest.aspx?lat=51.50731666666667&lng=7.0&tx=9a79e6ce-3344-409c-bbe9-496530baf758&f=1
16:07:30.228 Debug cgeo 15352  [network-7] DataStore.loadCaches([GC5C9BV, GC2DA6F, GC18HT6, GC555CC, GC5BAFR, GC3Q2MH, GC31ZZG, GC2AEX5, GC36HHM, GC439P6, GC5FB94, GCW06T, GC2YYDG, GC536NM, GC3N7K4, GC44EV6, GC3EMFR, GC3Q2PV, GC324N3, GC55A08]) returned no results
16:07:30.228 Info cgeo 15352  [network-7] Trying to get .loc for 20 caches
16:07:30.228 Debug cgeo 15352  [network-7] POST http://www.geocaching.com/seek/nearest.aspx
16:07:31.208 Debug cgeo 15352  [network-7] 200 (961 ms) POST http://www.geocaching.com/seek/nearest.aspx
16:07:31.318 Debug cgeo 15352  [network-7] Coordinates found in .loc content: 20

```

Something seems to be wrong with storing the home coords?

**Comment by Lineflyer** [comment]
Additional remark:
After some restarts of c:geo it suddenly is located correct at the home coords set on gc.com.
So maybe the information is stored but not used immdeiately.

**Comment by samueltardieu** [comment]
That is indeed the case, and has been documented (in the commit message?).

**Comment by Lineflyer** [comment]
I am not aware of that, but I guess it is still not intentional, that some random location is used instead?
Additionally it needed quite some restarts until the home location was used in my case and if the problem on support mail is caused by the same it seems to be possible that it might even take longer.

**Comment by Lineflyer** [comment]
Update:
Users feedback on support mail is:
- The problem keeps happening
- The user is located at a position which looks rather random

I sent a mail to cgeo-dev mailing list with an example.

**Comment by Lineflyer** [comment]
I think I found the problem...it is in fact a problem on gc.com:
On the screenshot send to cgeo-dev a screen is showing the home coords of the user.
The home coords are shown as (slightly changed to anonymize but same principle) ` N 51° 23.123' W ° 17.123'`
Note the wrong `°` in the longitude!

In c:geo the user is in this case located at `` N 51° 23.123  E 17° 17.000`.
So I assume parsing of the longitude fails due to the syntav fault on the webpage?!?!

**Comment by samueltardieu** [comment]
Good detective work @Lineflyer.

Please have people test the nightly build starting 2015.01.27-NB and tell if the fix is satisfactory for merging to `release`.

**Comment by Lineflyer** [comment]
In informed the user and wait for feedback.
Additionally I tested it myself with 2015.01.27-NB and it it passed:
- Test with latitude `W00`   OK
- Test with logitude `S00`   OK
- Test with latitude and longitude combination `S00 ... W00` OK
- Test with my own home location `N51...:E007`        OK

**Comment by Lineflyer** [comment]
@Krakapouet 
Please check on https://www.geocaching.com/account/settings/homelocation whether your home coordinates are either at South 0° or West 0°, which shows up wrong on that page (i.e. the 0 is ommited). If this is the case you are affected by the bug just identified here and it will be solved in the next version.

If not, please:
- Please send a screenshot of this webpage and a screenshot of the coords shown on c:geo homescreen (switch off Menu - Settings - Appearance - Show Adress first) to support <at> cgeo.org

**Comment by Lineflyer** [comment]
@samueltardieu The user also confirmed the fix with the nightly version 2015.01.27-NB.
Ok from my side to merge the fix to `release`

**Comment by samueltardieu** [comment]
Done.

**Comment by Krakapouet** [comment]
@Lineflyer 
You're right,  on GC https://www.geocaching.com/account/settings/homelocation the 0 is omitted ! 
But now in v2015.01.20 the coordinates of my location in c:geo are roughly 7 km west of my home only instead of 2000 km which is much better !

**Comment by samueltardieu** [comment]
@Krakapouet: can you please send on support@cgeo.org the location exactly as displayed by geocaching.com, so that we can check why it is still 7km off? (please add that you are @Krakapouet and reference issue #4620 so that we know what you are talking about :)

Are the coordinates on geocaching.com correct btw?

**Comment by Ute01** [comment]
I have the same problem. 
Two android smartphones.
The elder one has correct home coords.
The new one shows N00°00.000 E00°00.000.
Identical settings.
Home coords on geocaching . com are correct.
I tried some hours to fix the problem, but does not work.
What can help ?

**Comment by Lineflyer** [comment]
Can you provide the system information of the device, which does not show correct home coordinates please?

**Comment by Ute01** [comment]
HUAWEI Mate 10 lite
Modell:  RNE-L 21
Build-Nummer:  RNE-L21C4328137
EMUI:  5.1
Android:  7.0

**Comment by Lineflyer** [comment]
I was refering to the sysinfo shown in Menu - About c:geo - Swipe to "System".
Sorry for being not more precise.

**Comment by Ute01** [comment]
System information ---
Device: RNE-L21 (RNE-L21, HUAWEI)
Android version: 7.0
Android build: RNE-L21C432B137
c:geo version: 2018.06.26
Google Play services: disabled - 11.9.75 (440-182402865)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (42,5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (42,5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (42,5 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (98,8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy

**Comment by Lineflyer** [comment]
Can you please enable google play services in menu - settings - system and try again. Double restart kight3be required until home coords show up in cgeo afterwards.

**Comment by Ute01** [comment]
Now it is enabeld.
But the same as before.
No GPS and no WLAN = N00°00.000 E00°00.000
With GPS or WLAN = my actually position, but not the home coords from geocaching . com

I can live with that, but I wonder if the functions of two Huawei with the same c:geo-versions are so different.
At the older Huawei, the Google Play service is disabled and it shows my correct home coords without WLAN or GPS.

**Comment by Ute01** [comment]
While trying a lot of things, for some short moments, it shows the correct "home coords", but after switch off and on they are gone and it turned back to "combined" or N00°00.000 E00°00.000 .

**Comment by Lineflyer** [comment]
@Ute01 Sorry for coming back to you really late. Is this still an issue?

**Comment by Ute01** [comment]
I solved the Problem.
I had to activate "Entwickleroptionen" and there klick on "App für simulierte Standorte".
