### ISSUE TITLE
Shortcut menu to fast log offline disappeared ?

### ISSUE THREAD

**Issue by ludoo0d0a** [cgeo/cgeo#4621]
Last version saw a new "really useful" feature : a menu to fast mark as found without enter into the log.

But now, feature has gone. What is the status of this feature ?
I really loved this one.

**Comment by SammysHP** [comment]
The feature isn't gone, but the setting in the preferences is now checked correctly. If "log offline" is selected, then there is an item "write log" at the end of the list of possible log types.

In other words: Go to preferences, Logging, enable "log offline".

There are plans to remove this option and provide an UI that merges both ways into a single item. Btw: This option is present at least for two years. ;)

**Comment by ludoo0d0a** [comment]
Thanks for answer ! It helped me.
