### ISSUE TITLE
Test failing due to GC3XX5J beeing archived

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4622]
Seems tests on CI are failing as the cache http://coord.info/GC3XX5J has been archived recently.

**Comment by mucek4** [comment]
Can we replace it with something newer, that will not be hacked twice or three times.

**Comment by samueltardieu** [comment]
You must be kidding, right?

**Comment by mucek4** [comment]
This cache should not ve found by me (and it was), not it's archived, ... There is I think an issue to change this cache for testing.

**Comment by samueltardieu** [comment]
That's why I asked :)
