### ISSUE TITLE
Problem with nightly download

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#4625]
On android i can't download nightly release from https url (link directly from app). I must first edit link and delete "s" from it.
It's not a big problem but maybe you can change link in app from https to http ;)

**Comment by Lineflyer** [comment]
I am expierencing the same (i.e. one of my phones is not accepting the SSL certificate).
Something seems to have changed while @mucek4 worked on the website yesterday. Before that day the download link for the nightly build was AFAIR not forwarded to https.

**Comment by mucek4** [comment]
Nothing was changed in our certificate. SSL certificate was signed with "StartCom Class 1 Primary Intermediate Server CA"
SSL is enabled just for send2cgeo (as firefox and Chrome supports Startcon Class 1). It's not intended to run our webpage on SSL (or even download application from it).

There are two options:
- Download apk files from http
- Buy Class 2 (60$) or Class 3 (200$) certificate.

**Comment by samueltardieu** [comment]
I'll remove the https (this belongs to https://github.com/cgeo/cgeo-status/) right away.

**Comment by mucek4** [comment]
So from next nightly It should work? Class1 is still OK for https for send2cgeo

**Comment by samueltardieu** [comment]
No, it should work right now if you restart the application.
