### ISSUE TITLE
OSM - storing filtered viewport caches causes stop

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#4631]
Yesterday I was in a town nearby and wanted to store all traditional caches in viewport for offline.
Steps:

1. Start c:geo
2. Open live map (which is OSM 0.3)
3. Show as a list
4. Filter type only showing traditional
5. Store for offline

After storing c:geo was stopped.

SG3
2014-12-29-NB-c3d85fc

My SG3 seemed slow to me, so maybe there was less memory. However, maybe after storing we don't return to the previous map instance? Will try it at another location with newest NB.

**Comment by marco-dev** [comment]
Not reproducable at home with wifi.

**Comment by Lineflyer** [comment]
@marco-dev Close?
