### ISSUE TITLE
Update all caches from the list of all stored caches

### ISSUE THREAD

**Issue by SnarkBoojum** [cgeo/cgeo#4632]
The stored caches can be updated one-by-one or list-by-list, but not globally.

It would be nice to  add this action.

**Comment by Lineflyer** [comment]
We intentionally left it out on the "virtual" list of all caches to avoid excessive load to the server.
We guess most of the time it may be sufficient for users to update a single list (e.g. matching their cache plans for the day).

Is there a special usecase for you behind it?

**Comment by SnarkBoojum** [comment]
Ah, indeed, the idea of avoiding loading the server too much is sound.

I have no particular use case : I have lists for specific places around, lists for specific events, etc... I don't let my lists grow, but I let their number go up, so updating them one by one is cumbersome.

But now I'm quite convinced the right choice was made : it's not that cumbersome when you put the server well-being in the balance.

Thanks for your quick feedback : I suggest to close the issue.
