### ISSUE TITLE
Spoiler picture link missing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4633]
2015.01.25-NB (also present in 2015.01.20 as reported on support mail).
Happens also in other scenarios where the cache is opened directly from map.
Not sure whether it is a regression, but I think so as I never noticed it before.

- Search for GC5K2A1
- Open the cache details
- Note that the cache has a spoiler pic which is correctly indicated on the description tab
- Open the spoiler picture, is is shown normally. It is also visible on the image tab
- Select Navigate - Map
- Click on the cache to open popup
- Select more details

Result:
The link to the spoiler pic is missing on the description tab and the picture is not shown on the image tab. Selecting "refresh" will show it again until the next test cycle (unless the cache is saved).

**Comment by Lineflyer** [comment]
Corrected the sequence to reproduce above.

**Comment by samueltardieu** [comment]
Please test for inclusion in `release`.

**Comment by Lineflyer** [comment]
Can you tell which areas are modified by the fix?
Why did the problem only show up in this strange procedure?

Understanding this might help for retesting the sourrounding areas.

**Comment by samueltardieu** [comment]
To complete a cache information to display in the info box, an incomplete view was loaded, without the spoilers. Once merged, this view was saved into the database, thus clearing the spoilers.

**Comment by Lineflyer** [comment]
Using the above mentioned scenario I was able to verify the fix in 2015.02.02.-NB.
Up to now I did not see any regressions coming along, so its good to go for inclusion into `release`.

**Comment by samueltardieu** [comment]
Done.

**Comment by Bananeweizen** [comment]
This one has a bad impact on performance, as I just noticed during measurements. It leads to always loading spoilers. Even in the case of the cache list activity, where they are surely not needed.

**Comment by samueltardieu** [comment]
@Bananeweizen Feel free to fine-tune it. However, that would require remembering not to erase unloaded information from the database when updating a cache (from what I've seen, cache is removed from the database then stored again).
