### ISSUE TITLE
Crash on GPX export

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4634]
A user on support mail reported that c:geo crashed when exporting his stored caches.
I recevied the DB-backup and can reproduce the issue with 2015.01.25-NB.

It crashes after approx. 250 caches and shows this log:
```
00:03:12.018 Error cgeo 25109  [AsyncTask #3] UncaughtException
00:03:12.018 Error cgeo 25109  java.lang.RuntimeException: An error occured while executing doInBackground()
00:03:12.018 Error cgeo 25109  	at android.os.AsyncTask$3.done(AsyncTask.java:300)
00:03:12.018 Error cgeo 25109  	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
00:03:12.018 Error cgeo 25109  	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
00:03:12.018 Error cgeo 25109  	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
00:03:12.018 Error cgeo 25109  	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
00:03:12.018 Error cgeo 25109  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
00:03:12.018 Error cgeo 25109  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
00:03:12.018 Error cgeo 25109  	at java.lang.Thread.run(Thread.java:841)
00:03:12.018 Error cgeo 25109  Caused by: java.lang.IllegalStateException: getCacheUrl cannot be called on unknown caches
00:03:12.018 Error cgeo 25109  	at cgeo.geocaching.connector.UnknownConnector.getCacheUrl(UnknownConnector.java:19)
00:03:12.018 Error cgeo 25109  	at cgeo.geocaching.Geocache.getUrl(Geocache.java:727)
00:03:12.018 Error cgeo 25109  	at cgeo.geocaching.export.GpxSerializer.exportBatch(GpxSerializer.java:111)
00:03:12.018 Error cgeo 25109  	at cgeo.geocaching.export.GpxSerializer.writeGPX(GpxSerializer.java:83)
00:03:12.018 Error cgeo 25109  	at cgeo.geocaching.export.GpxExport$ExportTask.doInBackgroundInternal(GpxExport.java:142)
00:03:12.018 Error cgeo 25109  	at cgeo.geocaching.export.GpxExport$ExportTask.doInBackgroundInternal(GpxExport.java:104)
00:03:12.018 Error cgeo 25109  	at cgeo.geocaching.utils.AsyncTaskWithProgress.doInBackground(AsyncTaskWithProgress.java:136)
00:03:12.018 Error cgeo 25109  	at android.os.AsyncTask$2.call(AsyncTask.java:288)
00:03:12.018 Error cgeo 25109  	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
00:03:12.018 Error cgeo 25109  	... 4 more
```

DB backup available on request

**Comment by rsudev** [comment]
From the call-stack it looks like there is a cache with a code we do not have a connector for.
IMO ot should be possible to export those as well...
If you send me the DB, I'll have a look.

**Comment by Lineflyer** [comment]
Sent to cgeo-dev mailing list.

**Comment by samueltardieu** [comment]
@rsudev We have some choices. We can:
- prevent creation of such caches (with possible troubles with legacy databases)
- not barf on the absence of such attribute if it is not mandatory for the GPX (catch the exception while writing GPX)
- add a dummy URL for those unknown connector caches (yuk)

**Comment by Lineflyer** [comment]
What kind of cache is it in this case?

**Comment by rsudev** [comment]
I checked the database and there are in fact twelve caches that don't have real geocodes (likely imported from a manually created gpx).
My stance would be to support them and just don't fill in the missing information in this case

**Comment by Lineflyer** [comment]
Do you have a name for one of them so that I can see it in my restore.

**Comment by rsudev** [comment]
"ANDULKA"
"CERNOHORSKY EXPRESS"
"CIMRMANOVA VYHLIDKA"
"FJORD HREBCIN"
"HODINY FYZIKY SV ROH DRÁTKOBETON A TERÉN"
"KRYSTOF HARANT"
"KŘÍŽOVÁ NOVA PAKA"
"LEHKÉ FANTASTICNO"
"MOTOROVÝ VŮZ POD VELKOU VĚTVÍ"
"PEKELSKE RYBNIKY"
"PO VETROV"
"SPINDL4 ZAČÁTEK ZAVORA QR"

**Comment by Bananeweizen** [comment]
Actually, one can easily reproduce this. Import the "giga_lab_caches.gpx" and export them again. Boom. :)
