### ISSUE TITLE
Cache count missing in new restore dialog

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4635]
2015.01.26-NB:

![screenshot_2015-01-26-09-29-07](https://cloud.githubusercontent.com/assets/949669/5896922/ff3c25da-a53d-11e4-9c84-c2ae512ae7e9.png)

**Comment by samueltardieu** [comment]
Link to #3082.

**Comment by Lineflyer** [comment]
@Bananeweizen
In case you did not see this issue, which is probably caused by your fix for #3082.
