### ISSUE TITLE
Compass reversed on Nexus 6

### ISSUE THREAD

**Issue by uklad** [cgeo/cgeo#4636]
I`m running the latest version 2015.01.20 but I had this problem since getting my Nexus 6 the compass is always reversed when using cgeo a temp fix I have found is open Google maps then cgeo and it seems to correct it until next time i use it

**Comment by Lineflyer** [comment]
You mean an offset of 180° or is it shown upside down?
Does this happen in portrait and landscape mode?

**Comment by uklad** [comment]
Offset by 180 
Happens in both portrait and landscape

**Comment by samueltardieu** [comment]
@uklad Can you please copy here the information present in Menu/About c:geo/System.

**Comment by Lineflyer** [comment]
@uklad Friendly reminder.

**Comment by uklad** [comment]
--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 5.0.1
Android build: LRX22C
Cgeo version: 2015.01.20
Play services: present
Use Play services: yes
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
--- End of system information ---

**Comment by uklad** [comment]
This may well not be a c:geo problem 

http://forum.xda-developers.com/nexus-6/help/compass-issues-t3006641

It seem the only thing i can do for now is to spin the phone in 3 axis when i first fun c:geo 
Strange thing is I have no issue with Google maps while navigating

**Comment by samueltardieu** [comment]
@uklad Does the problem persist when you activate low-power mode in cgeo system settings? (this will cause the use of the geomagnetic rotation sensor instead of the orientation sensor)

**Comment by uklad** [comment]
YES it does..

Just restarted my phone loaded cgeo with low power mode 180 offset right away just done the figure of eight calibration and its find now

**Comment by samueltardieu** [comment]
Strange. So either the compass hardware is very badly calibrated, or our way of telling the screen rotation is very badly calibrated.

**Comment by Lineflyer** [comment]
Looking at the last replies I am unsure whether this is solved by calibrating the device or if there is still something to be done on our side?!

**Comment by Lineflyer** [comment]
@uklad Is your problem solved meanwhile by recalibrating?
We did not get any similar reports on our support channel, thus I think it can not be a systematic fault.

Please reopen if you disagree.
