### ISSUE TITLE
SD Card Problem on my Samsung Galaxy 4 Mini

### ISSUE THREAD

**Issue by Kalle6565** [cgeo/cgeo#4639]
The SD card is not shown in the file selection of C:geo. So I can not, for example, select the location for the Off-line map. I can only access the internal SD memory. I using a Samsung Galaxy S4 Mini.

Thanks for your help.

**Comment by Kalle6565** [comment]
A other big problem is, If I set the database location on external storage. The database is not transferred to the external SD-Card. it will be only transferred to the internal Device storage and not to the external SD-Card.

**Comment by rsudev** [comment]
Regarding your first question (not sure if you closed this issue accidentally), when you select 'Directory with offline maps' in the settings you should find 'choose directory' at the top of the result screen. This should allow you to navigate to any folder on your device, even to the external sd-card (I use offline maps like that on my phone).
Regarding you second remark, please consult the correspondinge FAQ-entry (http://faq.cgeo.org/#1_67). If you are interested you might also want to read the discussion in #3950 or #706 and related topics.

**Comment by Kalle6565** [comment]
Yes I closed this issue accidentally..My first question the problem is solved. The second one, I understand now. But i still have no solution to the problem,.like many others too.
Will be there for a foreseeable future a solution?

**Comment by SammysHP** [comment]
Closing because that topic is part of other issues and the FAQ.
