### ISSUE TITLE
Wrong sort in caches filter 

### ISSUE THREAD

**Issue by Surfoo** [cgeo/cgeo#4641]
Hello, 

In french, the list of caches in the filter is wrong. It's not a natural order and the type "Event Cache" (Événements in French) is at the bottom of the list.

Here a screenshot:
![export](https://cloud.githubusercontent.com/assets/553659/5991562/009ac036-a9f7-11e4-85e6-131b72ebde20.jpg)

**Comment by samueltardieu** [comment]
Note that the filter names in the cache list may exhibit the same problem (although not in French as no accented letters are located at the beginning of the filter).

**Comment by samueltardieu** [comment]
This has been fixed in our codebase and will be present in our next release. Thanks for the report @Surfoo.

**Comment by SammysHP** [comment]
IIRC we had a similar issue already some months ago.
