### ISSUE TITLE
Slovak translation mistake

### ISSUE THREAD

**Issue by redbeam** [cgeo/cgeo#4642]
In Slovak translation of the app, there is a mistake in "Dogs allowed" attribute: "Psi povolené" should be   "Psy povolené".

**Comment by Lineflyer** [comment]
Thanks for reporting.
I corrected it on our crowdsourced translation project: https://crowdin.com/project/cgeo

If you like you can participate on this page for translations.
If you encounter more incorrect translations please suggest your own correct translation and use the "Raise issue" function to mark the current translation as wrong.

**Comment by redbeam** [comment]
Thanks!
