### ISSUE TITLE
Export more info to Locus

### ISSUE THREAD

**Issue by auricgoldfinger** [cgeo/cgeo#4644]
Hi,
First of all: thank you for your great work. While geocaching, c:geo and Locus is a winning team.
Today I stumbled upon an issue while exporting a [multicache](http://www.geocaching.com/geocache/GC3F7A8_eksterheide?guid=efed2501-92d1-45d5-96bf-0bda5e0b2726) to Locus. The waypoints don't have coordinates but do have a lot of useful information in them. After the export to Locus, the waypoints were lost. Also, the trackables aren't exported and neither are the logs.

The fix is quite easy so I have a proposition here:
https://gist.github.com/auricgoldfinger/1b91bc6cb7aa70c15b15

This way, I hope I helped you a little. Hopefully you can add this fix to c:geo in the near future.
Kind regards,
Auric

**Comment by SammysHP** [comment]
It would be easier for us to review your changes if you commit it into your fork and maybe send us a pull request. But there are some issues that should be fixed first.

```
if (waypoint.getCoords() == null) {
    waypoint.setCoords(new Geopoint(0,0));
}
```

I don't like this. This would mean that the waypoint has coordinates and this is simply wrong.

```
// TODO this doesn't work as expected. And if it works, it might get configurable (slow process?)
final Trackable fullTrackable = GCParser.searchTrackable(null,trackable.getGuid(),null);
```

Network access. Don't do this.

```
final List<LogEntry> logs = cache.getLogs();
for (LogEntry log : logs) {
    …
}
```

We don't export logs currently? Interesting.

**Comment by auricgoldfinger** [comment]
Fair enough. I updated the code following your remarks and created pull request #4650.
There's indeed no need to set the coordinates of a waypoint. Locus accepts waypoints without coordinates.
