### ISSUE TITLE
Offline map not rendered properly

### ISSUE THREAD

**Issue by kukukk** [cgeo/cgeo#4645]
Hi,

I'm using c:geo, and I'm happy with it. Thanks for your work! However, I found some bugs. Here is the first.

The offline map is not rendered properly. Depending on the zoom level, some portions are not displayed. I'm using offline map downloaded from mapsforge website, suggested in c:geo's FAQ. I don't know if the problem is with the c:geo or with the map. It's up to you to check it :} 

This bug is also present in one of my friends phone.

You can find attached  a screenshot how it looks.
![screenshot_2015-02-02-09-29-35](https://cloud.githubusercontent.com/assets/616786/5997078/d1755d7a-aabe-11e4-80fd-2914071b12c1.png)

Best regards,
kukukk

**Comment by rsudev** [comment]
HI @kukukk , thanks for the report. From the look of your screenshot it might be an issue with the map or with the free space on your internal memory/sd-card (it is used for caching the map tiles). I can cross-check this if you tell which map and which location you used here :)

**Comment by kukukk** [comment]
Hi rsudev,

Thanks for the quick reply. I have 6.59 GB free space on the internal memory and 11.95 GB free space on the SD Card. I think it should be enough. The map is for Romania, and I downloaded it from here: http://download.mapsforge.org/maps/europe/romania.map (Note: I have an older version downloaded. I will also check with the latest version). To find the location where this bug appears, search for this cache GC5ER0D and modify the zooming level.

**Comment by kukukk** [comment]
Upgrading the map seems to solve the problem.

**Comment by rsudev** [comment]
Thanks for the quick feedback! So I assume rater an issue with the map itself, therefore closing here.
