### ISSUE TITLE
Spoiler photo from hint not downloaded for offline use

### ISSUE THREAD

**Issue by kukukk** [cgeo/cgeo#4646]
Sorry, It seems that it was already reported and it's fixed: https://github.com/cgeo/cgeo/issues/4633

Hi,

When I store the caches for offline use, images from hint are not downloaded. Even if I refresh all stored caches, the images is still missing. If I refresh the cache itself, the image appears. But it is stored only temporarily. If I leave cache details, go back to the map and select the cache again and lick on "More details" the image is missing.

I hope you can fix it as soon as possible, because I had some bad lucks with it, being in a zone where there was no mobile internet and the only hint was that photo.

Best regards,
kukukk

**Comment by rsudev** [comment]
@kukukk , thanks for double-checking and closing here. One small remark: it is easier to follow an issue in the notifications if you don't edit the initial description but close with an additional comment.
