### ISSUE TITLE
Crash on startup on an Android 3.2.1 device

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4647]
There is a report on support mail from a user with a device running Android 3.2.1 where c:geo crashed on startup. Various clean reinstallation did not solve the problem, I am unable to test because I don't have a 3.x device.

A log has been send to cgeo-dev some minutes ago.

**Comment by rsudev** [comment]
As discussed in cgeo-dev it might be a possible issue with appcompat under Api 13, perhaps with some interference from showcaseview.
So for testing, showcaseview was disabled for < 14 in 0a80a87 instead of < 11 as it was before.
Awaiting user feedback on next NB.

**Comment by Lineflyer** [comment]
Just an info: The user did not reply up to now.
I suggest to leave showcaseview disabled as it is now.
