### ISSUE TITLE
Compass on MotoG (XT1068) not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4648]
From support mail:

Compass starts spinning around until c:geo is killed and restarted.

I would interprete:
It starts malfunctioning at some point during usage and is working again for some time after a restart.

--- System information ---
Device: XT1068 (titan_retgb, motorola)
Android version: 4.4.4
Android build: KXB21.85-23
Cgeo version: 2015.01.20
Play services: present
Use Play services: yes
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
--- End of system information ---

@samueltardieu This is the case from support where you asked for more information.

**Comment by samueltardieu** [comment]
@Lineflyer Can you ask the submitter to try with low-power mode active? This should use the geomagnetic rotation sensor instead of the orientation sensor.

**Comment by Lineflyer** [comment]
I thought the same and therefore already asked for this and additionally a test without play services and without low power mode (but I assume that is changing nothing). Furthermore I asked about a simple test to disable the compass in the active sensors menu and look what happens.

**Comment by Lineflyer** [comment]
No reply from user. Closing.
