### ISSUE TITLE
Add more system information

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4649]
We should add more information to the system information which could be relevant for debugging/support and do not contain personal information.

Here is my wish list:
- [x]  PM/BM status
- [x] List of active connectors
- [x] Last login result of each connector
- [x]  Installation status of plugins (calendar/contacts)
- [x] Setting of "Hide Owned/Found"
- [x] Used map strategy
- [x] Language used on device
- [ ] Status of HW-acceleration

Lineflyer:
Removed one item

**Comment by Lineflyer** [comment]
Sorry...issue updated now.

**Comment by Lineflyer** [comment]
Here is my wish list:
- [ ]  PM/BM status
- [ ] List of active connectors
- [ ]  Installation status of plugins (calendar/contacts)
- [ ]  Setting of "Active Sensors" (in case it is still a persistent setting - I don't remember right now)
- [ ] Setting of "Hide Owned/Found"
- [ ] Used map strategy
- [ ] Amount of stored caches (x caches on y lists)

**Comment by Lineflyer** [comment]
I would be really happy if someone can implement some or all of that for the next release.
It would be helpful in case of support mails.

**Comment by samueltardieu** [comment]
I have added some of the information.

Is the rest really needed? In particular, the number of caches requires a database operation, while the language used on the device might not be easily available if the user set cgeo to English-only.

**Comment by Lineflyer** [comment]
Number of caches is not really required, used language would be helpful to know in which language to answer and/or refer to the menu items in that language when responding.

**Comment by samueltardieu** [comment]
Closing issue.

**Comment by Lineflyer** [comment]
@samueltardieu Would you mind to implement one more thing here:

HW-acceleration enabled/disabled ?

**Comment by rsudev** [comment]
Closed by 842302e9bc2d5ef0f25e4dc4b038ab384e273c2c
