### ISSUE TITLE
Crash on export GPX from imported benchmark *.loc

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4651]
From support mail:

A *.loc file of US benchmarks as selected and downloaded from Geocaching.com, with no modifications, will import fine. But then try to export, c:Geo crashes and an empty export file is created.

Version 2015.01.20

**Comment by rsudev** [comment]
Isn't this the same as #4634?

**Comment by Lineflyer** [comment]
Maybe. I'll check with current master to verify.

**Comment by Lineflyer** [comment]
Seems to be solved by ac5a1d5
