### ISSUE TITLE
Modified GPX not imported

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4652]
From support mail:
If I modify the loc file at all and save it as a gpx, adding description info using Basecamp for example, it will not import into c:geo - I see that as a separate issue that may simply not be supported by c:Geo.  (But Locus does support it, and so I am asking if c:Geo would also.)

---

Example file requested...

**Comment by Lineflyer** [comment]
Example file sent to cgeo-dev. Seems valid on the first look but I am no XML expert, so might be useful if someone else can take a look.

**Comment by rsudev** [comment]
The file seems to contain valid xml - but it does not contain caches from our perspective, just waypoints. While we assume all waypoints in a .loc to be caches we look in the gpx (besides them having coordinates and a geocode somewhere) for type:geocache or sym:geocache or sym:waymark. The gpx contains type:user and sym:blue flag - so no caches...
Locus is a generalized map application and therefore imports all kinds of waypoints.

**Comment by Lineflyer** [comment]
Closed as discussed on IRC.
The GPX does only contain waypoints but no caches.
