### ISSUE TITLE
Show more information if multiple contacts found

### ISSUE THREAD

**Issue by michag86** [cgeo/cgeo#4655]
If a search returns more than one contact with the searched alias (name of gc-user), a dialog shows all results. In this dialog only the alias is shown, so no distinction is possible.

It would be nice if more information here would be shown, for example additional first name and last name or something like displayname

**Comment by Lineflyer** [comment]
Thats a valid request IMHO.
![screenshot_2015-02-05-09-20-27](https://cloud.githubusercontent.com/assets/949669/6056946/57c1b33c-ad18-11e4-9cae-659db71ca9bd.png)
