### ISSUE TITLE
De-colorize logbook on request

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4657]
Just had a dark blue log entry which was not readable. We already have an option to show logs in white. Would be nice to also provide that on request directly in the action menu of the log entry.

**Comment by Lineflyer** [comment]
Sounds good.
(Your probably mean "on request" instead of "in request", Topic changed)

**Comment by Lineflyer** [comment]
In 2016 geocaching.com disallowed HTML and UBB formatting in logs, thus there is no possibility to colorize logs any longer. AFAIK also OC sites do not allow such text customization.

Despite looking at old logs this feature request is therefore no longer needed.
