### ISSUE TITLE
Both navigation options are compass

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4658]
Just noticed that on my new phone the primary and secondary navigation are both the compass. I'm not completely sure, but very much that I did not touch that setting yet.

**Comment by rsudev** [comment]
I am not so often installing c:geo newly, but now you mention it I recall having made a similar observation.

**Comment by Lineflyer** [comment]
Yep, I can confirm (because I often reinstall it). I suggest the second option could be "Map"?!

**Comment by Bananeweizen** [comment]
Actually the code looks like it would use the map as default. I'm not sure what is going wrong there...

**Comment by Lineflyer** [comment]
Now that you are saying this, I agree and it was like that some months ago. Don't know what might have changed in the meantime.
