### ISSUE TITLE
Disallow future logs

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4661]
from facebook: avoid accidentially logging December 2015, when creating December 2014 logs in January 2015.

**Comment by Bananeweizen** [comment]
I was looking at the different log types, but I didn't see any need to be able to log one of them with a future log date. If someone knows contrary (e.g. that logging a note is possible with a future log date), then please comment on this issue.

**Comment by Lineflyer** [comment]
We should maybe allow a tolerance of +1 day here as in the past we already had some strange issues with different time zones on device and website, etc.

**Comment by Bananeweizen** [comment]
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/utils/DateUtils.java#L40

:)

**Comment by Lineflyer** [comment]
:)
