### ISSUE TITLE
Direction line overlays cache icon

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4663]
Come from north to a cache. The direction line overlays the cache icon. Seems the layering order needs to be changed.

**Comment by SammysHP** [comment]
That's a problem. The direction overlay is merged with the position overlay to save memory. That overlay is always on top.

**Comment by Lineflyer** [comment]
@moving-bits As you recently worked on that area of the app. Still valid?

**Comment by moving-bits** [comment]
Does work on both Google Maps and OSM NewMap, therefore closing the issue.

![image](https://user-images.githubusercontent.com/3754370/88459330-deffa900-ce94-11ea-998a-d7315a4ed8da.png)![image](https://user-images.githubusercontent.com/3754370/88459333-e45cf380-ce94-11ea-8a63-98b7a65c5950.png)
