### ISSUE TITLE
Add shortcuts to caches

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4666]
We can already create shortcuts on request from the standard widget creation of android. If our app had an additional permission then we could create  home screen shortcuts to caches directly from the menu of a cache.
What do you think about that?

**Comment by samueltardieu** [comment]
Does it correspond to a need? How often does one want to create a shortcut to a cache on the home screen instead of e.g., using cgeo lists?

**Comment by Bananeweizen** [comment]
I'm not sure myself. I'm just seeing how many people ask for being able to bookmark caches from the app (meaning the bookmark functionality of the website). However, this could be a replacement for that bookmarking, even if it only works on that device and for a small number of caches...

**Comment by Lineflyer** [comment]
I do also think that a support of bookmarking on the server would be more helpful in this case. Homescreen shortcuts for specific caches are not really good organizeable, so IMO the shortcut to lists as we already support it should be sufficient as a local functionality.

Once when we might have a new main menu it be be helpful to have the possibility to add a specific cache as direct access to the homescreen (e.g. the cache planned for todays trip).

**Comment by SammysHP** [comment]
Shortcuts on the home screen have nothing to do with bookmark lists.
