### ISSUE TITLE
deletion of offline log not in context menu

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4667]
An offline log can only be deleted when in selection mode, but not directly from the context menu.

Edit: This bug only happens, if there is an offline log, but the cache has already been deleted.

**Comment by Lineflyer** [comment]
Your comment means, that you are looking at it on the history list then?! Otherwise I don't understand.

**Comment by Lineflyer** [comment]
With the recent change of the history this should work again.
Follow up problems are still there and listed in #6186
