### ISSUE TITLE
URLs for most opencaching.* sites are not recognized by cgeo

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4670]
opencaching.{de,fr} is supported, but opencaching.us is not for example. They should be added to the `AndroidManifest.xml` and handled properly.

**Comment by Bananeweizen** [comment]
I'm wondering if there is a more efficient way than having 3 (different paths/hosts) times number-of-OC-sites intent filters...

**Comment by Bananeweizen** [comment]
geocaching.com.au, their swaggies, and probably other supported connectors are also missing

**Comment by Bananeweizen** [comment]
If someone wants to test this: Be aware that several opencaching nodes do not support the opencaching.tld/geocode URL of their own caches. Also be aware that there are geocache links containing purely numerical IDs (like ...cacheid=123456) which we are also registered for, but cannot open correctly in c:geo. This is because ANdroid does not allow to differentiate on the URL parameters.

**Comment by rsudev** [comment]
I think we might need to revisit this topic. AFAIK is opencaching.no (and .se) as dead.
But opencaching.ro is seems to be missing

**Comment by Bananeweizen** [comment]
Good catch. I was rather confused, as even the German webpage does not list all of the countries.

**Comment by Cu8eR** [comment]
what about opencaching.cz ?

**Comment by Bananeweizen** [comment]
It's included in the change, however, it will probably not work. On the webpage of CZ I only see links which use the numeric cacheid, but our code only works for actual geocodes. In the case of CZ we might even add a transformation, as it seems to be straightforward int to hex conversion, but with the other countries the same does not work (e.g. the DE caches use IDs starting at around 103000 and not being linear).

**Comment by Bananeweizen** [comment]
Even the mapping between cacheid and geocode will not bring us forward. CZ does not support OKAPI (the interface for opencaching sites) and also does not have a GPX download link per cache. So even though we know which URL points to what cache, we cannot get the geocache data.
