### ISSUE TITLE
offline map menu even without any installed offline map?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4673]
Sometimes I'm wondering about how to make people recognize features they don't use yet. One possibility is to have UI elements visible even if they cannot work correctly yet, and then telling the user. One such case would be to add a menu item for offline maps, which just redirects the user to our settings page for offline maps.

What's your thought?

**Comment by fohlsso2** [comment]
Offline maps is a common question so I like that idea, but instead of just pointing to the setup frame it would make more sence to show a short instruction how to get starting (at least in the case of offine maps, for other simpler things its probably not needed).

**Comment by Bananeweizen** [comment]
The same thought also occurred to me when voting was not possible right now on my device. There was no voting bar in the log screen. But having it there with an overlay click to configure voting would have made that more easy to understand.

**Comment by Lineflyer** [comment]
I agree that linking to the menu would be a good idea as a first step.
Linking to a manual or alike can still be done at a later point if we have a strategy for that.

**Comment by Lineflyer** [comment]
@moving-bits Just as a side idea for onboarding offline maps. Otherwise feel free to close here.

**Comment by moving-bits** [comment]
With the new map downloader (which I will integrate after merging branches for the upcoming release) there will be a new menu entry in the map selector, labelled "Download offline map", which opens the new map downloader. Therefore closing this old issue here for now.
If we want to have more visibility for other "hidden" features we can/should open separate issues for each of them.
