### ISSUE TITLE
Scrolling title in cache details?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4678]
There is some attribute that makes texts scroll in android if they don't fit. I wonder if we should use that. Just had a cache I opened from mail and could not read the full title afterwards.
This would also be possible in cache lists.

**Comment by SammysHP** [comment]
IIRC

```
android:ellipsize="marquee"
android:marqueeRepeatLimit="marquee_forever"
android:singleLine="true"
```
and
```
view.setSelected(true);
```

**Comment by Lineflyer** [comment]
I would NOT do it in the lists as it may make several caches on a list scrolling simultanously which does not look good IMO.
However in the cache details it could be helpful depending on how smooth it looks in reality.

**Comment by Lineflyer** [comment]
This issue is set to "Feedback" and there seems no big need for scrolling cache titles.
Closing for now, feel free to reopen.
