### ISSUE TITLE
Different Max zoom

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4680]
When zooming fully in then Google displays about 100 meters in screen width, but osm shows 400 meters. Too little details there...

**Comment by Bananeweizen** [comment]
Probably related to this: WHen opening a map for a list of caches, the bounding box of those caches is less than half as wide as my screen (when using OSM), therefore not zooming far enough. The same list opened with Google as map provider nearly fills the full screen.

**Comment by rsudev** [comment]
I am not sure that those are related, as we calculate the zoom-level to fit the bounding box ourselves with OSM, but use built-in functions for Google.
The other question is, what OSM map you talk about. Online I get to a zoom that gives me a scale of 100m, while I get to 10m for offline.

**Comment by Bananeweizen** [comment]
I was talking about online.

**Comment by Lineflyer** [comment]
retesting this.

**Comment by Lineflyer** [comment]
Following up in #7750
