### ISSUE TITLE
Some Smiley's not transparent

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4682]
Looking at GC2W90G, I see non transparent icons in the log of Sandy&Mod.

**Comment by Lineflyer** [comment]
Why should they?
IMHO those smilies look like all of the smilies in the log entries...or am I wrong here?

**Comment by samueltardieu** [comment]
![Illustration of the problem](http://i.imgur.com/tDpDyFv.png)

**Comment by Lineflyer** [comment]
OK fo me on my S4, Android 4.4.2 even after deleting the stored smilies:
http://imgur.com/kBZqYCt

**Comment by Lineflyer** [comment]
Content of shared folder:
[Shared folder](http://i-imgur.com/AolEVyt.png)

**Comment by samueltardieu** [comment]
It looks like there is a difference between Android versions in their way of handling transparent gifs.

Content of shared folder:

![Shared folder](http://i.imgur.com/Rdk6kHu.png)

**Comment by Lineflyer** [comment]
Any new conclusions on that?
@samueltardieu What Android version are you using?

**Comment by Lineflyer** [comment]
@samueltardieu How to continue with this? Seems to be Android related and nothing to fix in c:geo...

**Comment by samueltardieu** [comment]
Yes, let's close this.
