### ISSUE TITLE
Caches marked as offline logged by theirselves

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4683]
This is unreproducible right now, but while caching today I realized two times, that caches I was currently dealing with suddenly got marked as "stored log" while I did not actively do this.
The offline logs contained my autoinserted signature.

Trying it lateron I could not reproduce it.

2015.02.15-NB
Option "Log offline" activated.

Did anything change which could cause that?

**Comment by Bananeweizen** [comment]
Open log activity, go back. Log is automatically stored, even though you may think you did not store it.

**Comment by Lineflyer** [comment]
I am well aware of that function, but I am sure I did not start the log activity.
Will monitor this over the next days.

**Comment by Lineflyer** [comment]
No more occurence of this problem. I guess it was a user fault.
