### ISSUE TITLE
Heading line also shown in "waypoint view"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4684]
If I go for e.g. a multi cache I add waypoints on the waypoint tab of the cache and then use the map icon in the actionbar to open the map and get an overview of all waypoints.
Now this will also show the heading line and distance overlay to the cache coords. While this is meaningful when starting the map from cache details it is not meaningful for mapping a bunch of waypoints of a cache.

Couldn't we either disable it for this view or automatically set it to the latest waypoint which has coords?

**Comment by Lineflyer** [comment]
Now I am confused a little. I just wanted to reconfirm what I described above, but with 2015.02.15-NB1-f35ca24 the map icon vanished on the waypoint tab.

**Comment by Lineflyer** [comment]
Forget my last comment. Updated the issue accordingly, yesterday it seems I was confused by menus which I should know better :)

**Comment by Bananeweizen** [comment]
I would not want to have the target automatically set to an arbitrary waypoint of a multi cache when opening it. I guess your use case would be better handled by making the "select target" menu from the compass also available in the map (of a single cache).

**Comment by Lineflyer** [comment]
Target selection has been included in the "new map" already. Behaviour will most likely not be changed in the current/old map.
