### ISSUE TITLE
Actionbar content changed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4685]
While with yesterdays version (2015.02.14-NB) the actionbar on the waypoint tab of a cache contained a map icon, it now (2015.02.15-NB1) has the same structure as on the cache detail tab. 
I would strongly suggest to have the map icon located at first position as implemented before.

**Comment by Bananeweizen** [comment]
I'm sorry to say this, but the behaviour you describe has never been implemented. The actionbar is completely independent of the tab currently being active, in all of our activities.

**Comment by Lineflyer** [comment]
I rechecked this and you are right indeed. Seems I had a bad day yesterday. Sorry for bothering.
