### ISSUE TITLE
Use second line in map title

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4694]
When opening a map with a real action bar then we should move the cache numbers into a second line similar to the cache list.

**Comment by rsudev** [comment]
There is a small glitch in the implementation. In case of partial cache display (x/n) the total count is displayed twice (appended explicitly and as part of the plurals string).
I will correct it right away.

**Comment by Bananeweizen** [comment]
Thanks for catching. I only introduced the plurals string later without thinking about now to remove the standalone number.
