### ISSUE TITLE
Cache not added to history if offline logged from popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4698]
2015.02.21-NB

Not sure if this is a duplicate of a still open issue or a returning error.
Today I managed to log a cache offline (I think via live map popup) and it was not showing up in the history afterwards.
Looking at the cache list it had a orange maker, looking at its details it had the status "Saved log" BUT it did not have the date written behind that.
I performed again  Menu - Log offline - Found and afterwards the date was shown in details and it showed up in the history.

Reproducing this problem failed up to now, so mainly a reminder for myself or anyone interested in trying to reproduce that.
If its indeed a duplicate, feel free to close it.

**Comment by MrYaz** [comment]
I reproduced the behavior in duplicate issue #4086

**Comment by Lineflyer** [comment]
Yes...that was the issue I was looking for. So closing here and continue in #4086. 
Thanks @MrYaz
