### ISSUE TITLE
Cache not removed from history after offline log deleted

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4699]
2015.02.21-NB

- Log a cache offline
- Verify it is added to the history
- Open the cache again and delete the offline log by Menu - Log offline - Delete (or whatever the menu is called in english)

The cache keeps showing up in the history permanently (also after app restart)

**Comment by Lineflyer** [comment]
@pstorch Might also be related to #4086

**Comment by rsudev** [comment]
I guess the ```visiteddate``` is just not cleared alongside...

**Comment by pstorch** [comment]
@rsudev you are right, setting `visiteddate = 0` is missing.

**Comment by samueltardieu** [comment]
Maybe we should stop calling "history" something which is in fact "caches with offline logs" then.

**Comment by pstorch** [comment]
Good point, I was wondering about the exact purpose or meaning of "history" myself. But it's not only about offline logs, right? The normal logs (posted via c:geo) show up in "history", too.

**Comment by Lineflyer** [comment]
In another issue I suggested to name it "Last logs" instead.

**Comment by pstorch** [comment]
That would be more explicit. 
On Geocaching.com there is also some kind of History, the "Recently Viewed Caches". I mixed up this one with the cgeo History in the beginning. 
So, a +1 for renaming to "Last logs" or "Recent logs".

**Comment by pstorch** [comment]
"Last logs": #3891

**Comment by pstorch** [comment]
There is also #4672 to make the "history" more intuitive
