### ISSUE TITLE
[Feature request] Add view of recently opened caches

### ISSUE THREAD

**Issue by geziefer** [cgeo/cgeo#4700]
I know that one can save caches for offline use and that there's a list of what I logged, but there should be a list of recently opened caches, just like it is on geocache.com profile main page. 
It would be very helpful for a typical usage scenario where I visit several caches but don't want to fiddle around with the smartphone for writing the log text, but log at home in peace and comfortably. And for that I'd need a view of the visited caches in the order of opening. 
I assume it should be quite easy to implement, there would be no need to synchronize with the geocache.com list, but only store locally in c:geo the last x caches which were opened in detail.

**Comment by SammysHP** [comment]
Currently there is one way to do it: On the main screen press the search button and a list with recently viewed caches will be shown.

We also plan to extend the history to include and distinct between offline, online logged caches, viewed caches and deleted caches.

**Comment by Lineflyer** [comment]
For your described usage scenario it would also be possible to activate offline logging in cgeo settings. Afterwards you can log the caches as found or not found with one click and they will show up in the history of cgeo.
Afterwards you can either log them manually on the website and delete the offline logs or you can upload them as field notes directly to the website and continue with it on the website.
