### ISSUE TITLE
new version (2015.02.23) won't open on Samsung Galaxy SII

### ISSUE THREAD

**Issue by louisehandy** [cgeo/cgeo#4701]
Installed the new version yesterday and it won't work at all

**Comment by Lineflyer** [comment]
Could you be more specific please:
What happens if you start it?
Any error message?
Is it offered to send a crash report? Did you send it?
What Android version are you using?

**Comment by louisehandy** [comment]
HiThanks for replying. I am not a teccy but i have just sent a report and also attach two screen shots for you of the message i get after it doesn't start and of my phone settings.Hope that helpsThanksLouiseSent from Samsung Mobile 

 Lars  wrote: 

Could you be more specific please:
What happens if you start it?
Any error message?
Is it offered to send a crash report? Did you send it?
What Android version are you using?

**Comment by rsudev** [comment]
Hi @louisehandy 
Unfortunately do the screenshots not come through if you reply via email. You need to go to the github website to attach them.
Regardless would it be very relevant for any investigation to get the information mentioned by @Lineflyer above. You can get these infos if you go to the phone settings and then to the last entry ('about this phone' or similar). When you select this, there is an entry 'model number' (or similar), I'd like to get this item and another entry 'Android version', I'd like to get this as well.
A general remedy for these kind of issues can be, to uninstall and re-install the app, as this behaviour can emerge if the upgrade by the Android system does not fully work, But beware, that stored settings and caches will get lost when doing this.

**Comment by samueltardieu** [comment]
@louisehandy You can get the requested information from cgeo: "About cgeo" / "System" contains a block of data that can help us pinpoint the problem.

**Comment by samueltardieu** [comment]
Oh, if it doesn't start at all you will be unable to get them from within cgeo of course, and will have to proceed as indicated by @rsudev.

**Comment by Lineflyer** [comment]
No feedback from the user.
Looking at the Play Console it could be this one here:
```
java.lang.RuntimeException: Unable to create application cgeo.geocaching.CgeoApplication: java.lang.NoSuchFieldException: sHasPermanentMenuKey
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3283)
at android.app.ActivityThread.access$2200(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3691)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoSuchFieldException: sHasPermanentMenuKey
at java.lang.ClassCache.findFieldByName(ClassCache.java:446)
at java.lang.Class.getDeclaredField(Class.java:666)
at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:57)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3280)
... 10 more
```
Happend on an S2 with Android 2.3.3 - 2.3.7

**Comment by rsudev** [comment]
From the timing it doesn't seem to fully fit (the user report is from 7 days ago, the playstore report from 5 days ago) and that report is even more strange, as it states that it crashes on the very exception and line we are catching specifically to handle exactly this case...

**Comment by louisehandy** [comment]
HiSorry for delayed response-was trying to get to a pc to log back into yr site and send details but been in middle of a house move. Decided to try uninstalling and reinstalling on my phone( and risk losing my saved caches) and it worked so i am operational again and i have no idea why!Thanks for trying to help tho-appreciate itLouiseSent from Samsung Mobile 

 rsudev  wrote: 

From the timing it doesn't seem to fully fit (the user report is from 7 days ago, the playstore report from 5 days ago) and that report is even more strange, as it states that it crashes on the very exception and line we are catching specifically to handle exactly this case...

**Comment by louisehandy** [comment]
Oh and re the reporting timeliness they probably were both me as i didn't send the report from my phone till someone asked if i had which would have been about two days later.Thanks againLouiseSent from Samsung Mobile 

 rsudev  wrote: 

From the timing it doesn't seem to fully fit (the user report is from 7 days ago, the playstore report from 5 days ago) and that report is even more strange, as it states that it crashes on the very exception and line we are catching specifically to handle exactly this case...

**Comment by Lineflyer** [comment]
Closing then.
@louisehandy Thanks for your feedback. I guess your database was corrupted in some way....
