### ISSUE TITLE
Caches not visible in TB log entries

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4702]
2015.02.22-NB

If I am not completely wrong the TB logbook normally contains the geocache name alongside with dropped, retrieve and visit logs.
However for me the TB TB4TXR0 does not show them in the logbook.

Did not check if only this one or all TBs are affected. Maybe a website change or I just remember incorrect.

**Comment by Lineflyer** [comment]
This issue seems not clearly reproducible. On some TBs ist ok, others keep failing

**Comment by rsudev** [comment]
I can see the cache names in the logs of the TB you mentioned...

**Comment by rsudev** [comment]
Cross-checked with TB11CTV - works as well

**Comment by Lineflyer** [comment]
I will monitor this for a few days and also try again once I am back home. It keeps happening for me.

**Comment by Lineflyer** [comment]
Did not show up again.
Some roaming and/or login issue I guess.

**Comment by Lineflyer** [comment]
I can now reproduce this issue as follows:
- Open TB11CTV
- Swipe to logbook to verify all information is shown
- Swipe back to Details
- Leave the screen by either clicking on the owner name and select e.g. "Hidden caches" or click on the last seen cache and open its details
- Press back to return to the TB
- Swipe to the logbook again

Result:
- Cache info is missing in logbook now

**Comment by samueltardieu** [comment]
@Lineflyer Are you positive this is a regression?

**Comment by Lineflyer** [comment]
I will test with current release and report back. Not sure why I set the regression label here...maybe I already tested it and forget to write it down.

I am however sure it used to work in older releases.

**Comment by Lineflyer** [comment]
This problem is happening with:
- 2015.03.12
- 2015.02.23
- 2015.01.12 (Feature Release)
- 2014.12.22

Thus it is no regression.

**Comment by samueltardieu** [comment]
@Lineflyer Please test and advise whether this should go on `release` or not.

**Comment by Lineflyer** [comment]
Due to the current conditions I would prefer an implementation into `release` right away to include it in testing the RC version.

**Comment by samueltardieu** [comment]
Done.
