### ISSUE TITLE
GPS not deactivated sometimes

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4704]
2015.02.24-NB

This is not reproducible, but there seems to be a possibility that GPS remains active while c:geo is in the background.
Last days I had several occurences of the problem.
I will try to puzzle out the conditions once I return home next week.

Right now it seems that it has something to do with 
- Having no GPS fix since startup of c:geo
- Changing between cache details and other tabs of the same cache
- Let the device timeout or put it in standby
- Google Play Services deactivated & energy saving deactivated

**Comment by samueltardieu** [comment]
I cannot reproduce this from the description.

**Comment by SammysHP** [comment]
Sometimes c:geo shows up at the top of the power statistics with 100% GPS active.

**Comment by samueltardieu** [comment]
@SammysHP: no Google Play services either?

**Comment by Lineflyer** [comment]
@SammysHP In my case I did not look onto the power statistics but I have seen the GPS fix in the status bar of my mobile. It only disappeared after opening recent apps and killing c:geo manually.

**Comment by SammysHP** [comment]
@samueltardieu I'm not using Google Play services currently. No icon is shown in the notification bar.

**Comment by samueltardieu** [comment]
@SammysHP Are you saying that Android pretends that cgeo uses GPS 100% of the time and does not display the GPS icon?

**Comment by SammysHP** [comment]
Correct. It shows 100% GPS but GPS is disabled (independent of the precise location setting in Android).

**Comment by Lineflyer** [comment]
The original issue happend to me twice today while testing the geokrety stuff.
I am still not able to find a reproducible way, but it is somthing like:
- Play services active, energy saving off
- Leave c:geo in a state where GPS is active (e.g. cache detail screen)
- Wait for automatic standby of the phone
- Unlock the phone after a longer time (10-20min) to return to c:geo
- Press home button immediately after unlocking the phone to leave c:geo

This resulted in GPS staying active (GPS icon shown on notification bar). When I returned to c:geo and explicitly left it again, the GPS was still active. ADB log did not show any c:geo messages like usual (`Stopping GPS....`). The only way out was force closing c:geo.

**Comment by Lineflyer** [comment]
No longer occuring to me. Maybe it was a problem in GoogelPlayServices fixed by a newer version. Will reopen if I get new occurences.
