### ISSUE TITLE
backup to / restore from cloud

### ISSUE THREAD

**Issue by webmicha** [cgeo/cgeo#4705]
I had to reset my phone and of course I made a backup within c:geo. But it was not possible to copy the database to an external storage. So, I suggest to connect c:geo with cloud storage like dropbox or gdrive to save a backup of the database outside the phone. That would also help transfering c:geo data from one phone to another in a very easy way (from users view), because there's no hazzle with finding data. Nice to have is to manage up to three versions of the backup, in case some thing goes wrong or to administrate different devices.

**Comment by rsudev** [comment]
Some thoughts.
* Question: why couldn't you copy the backup to somewhere external?
* Having a backup history (some versions) sounds like a good idea to me
* Cloud storage: I am not to fond of that. Which provider to choose? There is a good chance we end up having to maintain quite some of them, a feature-set quite remote from our core intererst - geocaching. I would rather expect the cloud storage providers to allow you to set-up syncing/storing for some files instead (I am not much into this area...)

**Comment by webmicha** [comment]
to answer your question: a normal file explore can't see ".cgeo" directory in internal storage. Using "File Manager" you can access it, select "cgeo.sqlite" and copy the file. But it is not possible to copy it to external sdcard, because Android don't allow 3rd part apps to do so. What I didn't had in mind, is the opportunity to use "sharing" and upload it this way to gdrive. My fault ;)

Anyway, this is something a normal user is not able to to, since he can't acces the file. And that would be the reason to add such a function to c:geo.

Maybe, it could at least implemented as a "share with" dialogue, directly after the backup is created. 
A sharing option is already implemented in the action menu of a cache description.

More elegant and comfortable, of course, would be an automated upload to a predefined storage. As most Android users have a Google account, Goggle drive would be the most prefered service.

**Comment by SammysHP** [comment]
Sounds like we need a solution for users who are not aware of the file system at all. :/ As a developer I've never thought about such "simple" tasks, but many users think like "photos are in gallery app, texts are in docs app, mp3 in media player app and caches in cache app".

**Comment by webmicha** [comment]
Yep, u r right Sammy ;)

**Comment by madankumarbaskaran** [comment]
May I work on this request?

**Comment by SammysHP** [comment]
Sure, but please explain your ideas here first.

**Comment by madankumarbaskaran** [comment]
@SammysHP I read the requirement and thought to implement it. My understanding is to create a backup of CGEO database in google drive and  it can be implemented using Google drive API. Please correct me if I am wrong. Happy to take other ideas for adding cloud feature.

**Comment by SammysHP** [comment]
It is not only the database, also the data directory. Also there might be more than one database file.

Please explain a little bit more how you want to implement it. Classes, necessary modifications, …

**Comment by Lineflyer** [comment]
Maybe this should be postpones until we have a clear view on planned restructuring of the storage mechanisms? I am refering to #4957 and associated issues.

@marco-dev @madankumarbaskaran 
Maybe it makes sense (given that you are interested) that you work together on these storage things (#4957)?

**Comment by madankumarbaskaran** [comment]
@Lineflyer Sounds good. Happy to work with @marco-dev on storage issue

**Comment by webmicha** [comment]
👍
Am 14.07.2015 21:21 schrieb "MadanKumarB" <notifications@github.com>:

**Comment by valentijnscholten** [comment]
Just adding my vote here. People are getting more and more used to being able to backup to the cloud.
No more hassle with moving (invisible) folders around that take forever to copy to PC or external sd card.

**Comment by JochenJung** [comment]
I would love to see this feature as well

**Comment by fm-sys** [comment]
> Having a backup history (some versions) sounds like a good idea to me

Already on the go... ;-)

> a normal file explore can't see ".cgeo" directory in internal storage, because of th "." in directoryname.

That was changed some time ago, so the cgeo folder is now easy to find.

Reading the thread there were two main problems in the past: slow USB transfer speed and missing android framework / permissions for writing to the SD card. Both is much better today.

Also it is critical to store the login credentials on a cloud-server, so we would need some kind of secure encryption.

Of course it would be a nice feature, but the needed work isn't worth it in my opinion...

**Comment by Lineflyer** [comment]
> Of course it would be a nice feature, but the needed work isn't worth it in my opinion...

At least we could offer a "share option" after completing the backup, so user can select what to do with the created backup file(s). So one could easily share it with Dropbox or alike to store it there.
