### ISSUE TITLE
live state not remembered on switching map provider

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4706]
Open a map for a stored list of caches. Enable "live" from the menu. Switch to another map provider. Live is disabled again (which can lead to no caches visible at all, if you scrolled out of the area of stored caches).

**Comment by samueltardieu** [comment]
I cannot reproduce this.

**Comment by Lineflyer** [comment]
I can also not reprocude this.
@Bananeweizen Feel free to reopen and provide more details to reproduce.
