### ISSUE TITLE
Dont save log if unedited

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4708]
Current behaviour if auto signature is enabled is:
- Start logging activity (happens to me accidently sometimes)
- Press back

Result:
The cache is saved as offline logged found because the log already contains the automatically inserted signature
If it would be empty instead it would not be saved at this point.

Expectation:
Only save the log automatically on pressing back if the log content was edited manually

**Comment by rsudev** [comment]
I am not sure I agree here. I personally used this exact behaviour many times to just quickly 'mark' a cache as found. I would rather suggest to have a 'cancel' or 'discard' button in the action bar.

**Comment by Lineflyer** [comment]
I know your usecase, thats why I proposed #3856

Anyway the way you use this function is probably not the way we intended.
That why I somehow dislike that the "offline log" has to be activated somewhere deep in the settings instead of havin it always present somewhere.

**Comment by olpp** [comment]
I like Lineflyers "expectation" since this scenario happens to me more than just sometimes.

Mostly not accidentally but because cgeo sometimes "forgets" the actual number of found caches and then doesn't fill the auto signature correctly.

**Comment by Lineflyer** [comment]
Lets close this as practice did not show any complaints by users and behavior has slightly been changed meanwhile.
