### ISSUE TITLE
ActionBar tooltip bubbles on main screen have wrong size

### ISSUE THREAD

**Issue by Pitel** [cgeo/cgeo#4710]
Hold your finger on any button in action bar and the tooltip appears with wrong size. On other screens, the tooltip seems ok.

![Bad tooltip](https://cloud.githubusercontent.com/assets/113248/6438619/41bd53cc-c0cb-11e4-86fc-f1c3023eaba2.png)

**Comment by akkatracker** [comment]
I was mucking around with this mainly for the purposes of education (am learning android). 

Could someone tell me what is actually causing the tooltip to appear in the first place - I have found it's related to the android:title attribute but is it an inherant feature that menu items will show a tooltip with text of the title? 

Also to whoever ends up fixing this, the bug also appears on the login screen when it says c:geo can't log in.

**Comment by rsudev** [comment]
The tooltip is an inherent feature of the action bar (should work in every app). I thiml we have some style/theme setting only effective on the main screen that is causing this.

**Comment by akkatracker** [comment]
@rsudev Thanks, its really interesting what you can learn by playing around with the source code

**Comment by Pitel** [comment]
Now, on Nexus 5X with Android 7.1.1, it look ok.
