### ISSUE TITLE
Ignore cache should have a confirmation 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4711]
As there is currently no way to undo the ignore action from within c:geo I think it would be wise to show a confirmation dialog explaining the meaning of that function, how it can be undone and let the user confirm the action.

**Comment by Bananeweizen** [comment]
There is. Just hit the same menu a second time. At least for me that works, although I did not implement anything for that. :)

**Comment by samueltardieu** [comment]
@Bananeweizen It doesn't seem to work for me.

**Comment by Lineflyer** [comment]
Just a small reminder that we should solve this before we can do a feature release (as it would be time for a release quite soon IMHO).

**Comment by Bananeweizen** [comment]
While I was implementing this, I thought about the local copy of the cache. I think it would be useful to also remove the local copy of that cache automatically, to be aligned with the ignore settings from the website.

This also would make the implementation a bit easier, as it would not be necessary anymore to find out whether a local cache is currently ignored or not (we don't have that information). And, as usual, we could implement "5 seconds undo" for the ignore function to be totally safe.

Comments?

**Comment by Lineflyer** [comment]
Removing the local copy as well is a good idea. Otherwise users might ask why they still see the cache in lists/on map after ignoring it. We should make sure to also clear it from the "3 days cached" list to have it no longer showing up on the map.

I think we should have a confirmation dialog + 5 seconds undo to make the usage totally safe.
