### ISSUE TITLE
Ignore cache should provide result

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4712]
As far as I could see there i no UI indication after ignore cache has been selected whether the action was succesful or not. Nothing can be seen in the UI after selecting that menu item.

**Comment by samueltardieu** [comment]
Confirmed. Also, we need a way to unignore all caches, or bug reports will start raining :)

**Comment by Lineflyer** [comment]
Just a small reminder that we should solve this before we can do a feature release (as it would be time for a release quite soon IMHO).

**Comment by Lineflyer** [comment]
The "ignore cache" function meanwhile shows a warning and explanation as well as the cache being removed also locally if the operation was succesful.
So this issue has implicitly been solved.
