### ISSUE TITLE
Smilies in waypoint description shown incorrect

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4713]
2015.02.23:

- Open GC5NBMH
- Swipe to the waypoints

Waypoint "Cafe Times" shows a block instead of the smilie.

**Comment by samueltardieu** [comment]
@Lineflyer Please tell whether you want this in `release` or not.

**Comment by Lineflyer** [comment]
@samueltardieu Sure!

**Comment by samueltardieu** [comment]
Done.
