### ISSUE TITLE
Remove mapsforge 0.24

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4715]
We still have two mapsforge libraries in our code. I'd like to remove the 0.24 version. We introduced that to enable people to use their 0.24 maps instead of just showing an error, because our 0.3 library cannot load them.

That was 2.8 years ago, and people should have new maps by now.

Any good reason not to remove the 0.24 support?

**Comment by samueltardieu** [comment]
Agreed.

**Comment by rsudev** [comment]
Agreed as well. On a side note, I finally started seriously on getting mapsforge 0.5 into our codebase. It is not as far explored as I want in order to start a discussion around that, but the current state is available on https://github.com/rsudev/c-geo-opensource/tree/mapsforge-5b

**Comment by Bananeweizen** [comment]
@rsudev 
In that case I will not touch this area now and instead either let you remove it in your branch directly or do that after your changes have been merged. I assume there might otherwise be conflicting changes in that package.

**Comment by rsudev** [comment]
You don't need to hesitate, I started my 'exploration' more or less decoupled from the current map, integrating it as a new internal navigation app, so I don't expect any conflicts.

**Comment by Bananeweizen** [comment]
Okay, done with 76156d12f1c1f2eb49eea5f63b7a34e0bb4fef0b

**Comment by Lineflyer** [comment]
Removed from new FAQ as well :)
