### ISSUE TITLE
Mystery Personal Cache Note 

### ISSUE THREAD

**Issue by dramyFB** [cgeo/cgeo#4716]
Hello Team,
i have a question about a Mystery and the Personal Cache Note. If i have saved the final Coordinates in the mystery cache (online Gecaching) and i save the cache offline i must ever open before i can see the final waypoint on the map. Why i have to open it again, because if i have now internet the waypoint isn't avaiable in my case. What is the reason?

You can answer in germany ;-)
DramyFB

**Comment by Lineflyer** [comment]
Hallo,

vielleicht kannst du dein Problem nochmal auf Deutsch beschreiben.
Hast du das FInal nur in der Personal Note gespeichert, oder auch die Funktion auf der Webseite genutzt die FInal-Koordinaten im Listing anzupassen (kleiner Stift neben den Listing-Koordinaten auf der Webseite)?

**Comment by dramyFB** [comment]
Hallo lars,
puh ok Deutsch ist besser ;-) Also ich löse einen Mystery und die Finalkoordinaten tragen ich in meine Personal Cache Note  ein. Dann sehen ich diese nicht, wenn ich den Cache per Pocket Q. auf das Gerät laden und öffne. Erst wenn ich dann den Mystery erneut öffne, sehe ich meine Notes als Waypoint bzw. Finale auf der Karte. Ich wünsche mir das die Notes beim Offline speichern direkt angezeigt werden ohne das ich erneute diesen Mystery aufrufen muss.
LG
DramyFB

**Comment by rsudev** [comment]
Da können wir wohl leider nichts machen, da die personal cache note in der PQ schlicht nicht enthalten ist...

**Comment by Bananeweizen** [comment]
Deshalb statt dessen entweder auf der Webseite die Funktion zum Anpassen der Koordinaten verwenden (Stift neben den Koordinaten) oder alternativ in c:geo einen neuen Wegpunkt vom Typ Final anlegen, Koordinaten reinkopieren und ganz unten "Cache-Koordinaten lokal und auf Webseite ändern".
