### ISSUE TITLE
Consuming libraries as submodules?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4718]
I'm more and more stumbling over an issue: I want to use Android libraries in cgeo, which can only be consumed as source or via gradle. Using Eclipse I therefore must go with the source option for now (this is also nice because often we need tiny fixes in the library). Instead of copying the library verbatim, can git submodules be used to actually just refer to their github repo? From the description of it in the git documentation, it sounds fitting very well

Example: The showview library currently exists as verbatim copy in our repo, so we will probably not update it. If it were a submodule, this would be easy to do.

@samueltardieu You probably have the most experience there.

I'm rather sure we discussed this or a related submodule question already, but I can't find this anymore.

**Comment by SammysHP** [comment]
e.g.
http://krul.finf.uni-hannover.de/~sammyshp/cgeo-logs/2014-04-21.txt
http://krul.finf.uni-hannover.de/~sammyshp/cgeo-logs/2014-05-17.txt

**Comment by samueltardieu** [comment]
No problem for me. I use submodules in other projects, and as I had a chance to state before, only merges may be a bit more complicated (but not that much). And changing branches might require two commands to update the submodule after the branch switch, but that's it, one has to be careful in what they commit.

**Comment by SammysHP** [comment]
:+1:
