### ISSUE TITLE
coord.info links with additional parameters not opening

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4719]
From support mail.
- Using a we.de mail app it is not possible to open a TB-link (e.g. http://coord.info/TB392FV) from a geocaching watchlist mail in c:geo.
- c:geo is selectable as target app but just comes back with an error toast "c:geo can not show this trackable. Is it really a trackable?"
- Manually opening the TBcode from c:geo search bar is OK
- Opening the mail link in a browser (Chrome) is also OK

The user now installed intent intercept and send me the content of the intent after clicking the link:
```
intent://coord.info/TB392FV#Intent;scheme=http;action=android.intent.action.VIEW;launchFlags=0x3000000;end 

ACTION: android.intent.action.VIEW 
DATA: http://coord.info/TB392FV 
TYPE: null 

FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

3 ACTIVITIES MATCH THIS INTENT:
c:geo (cgeo.geocaching - cgeo.geocaching.TrackableActivity)
Internet (com.sec.android.app.sbrowser - com.sec.android.app.sbrowser.SBrowserMainActivity)
Chrome (com.android.chrome - com.google.android.apps.chrome.Main)
```

If I try it myself I see a difference (a additional category and extra info):
```
intent://coord.info/TB6RRG3#Intent;scheme=http;action=android.intent.action.VIEW;category=android.intent.category.BROWSABLE;launchFlags=0x3080000;S.com.android.browser.application_id=com.android.email;end 

ACTION: android.intent.action.VIEW 
DATA: http://coord.info/TB6RRG3 
TYPE: null 
CATEGORIES:
android.intent.category.BROWSABLE 

FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

EXTRAS:
EXTRA 1:
Class: java.lang.String 
Key: com.android.browser.application_id 
Value: com.android.email 

3 ACTIVITIES MATCH THIS INTENT:
c:geo (cgeo.geocaching - cgeo.geocaching.TrackableActivity)
Internet (com.sec.android.app.sbrowser - com.sec.android.app.sbrowser.SBrowserMainActivity)
Chrome (com.android.chrome - com.google.android.apps.chrome.Main)
```

**Comment by Lineflyer** [comment]
Just received another complaint for the same (this time using the GMX Mail-App).
Did we recently change the behaviour here?

Cache-links from Groundspeak mails are working for both users.

**Comment by rsudev** [comment]
@Lineflyer Are you on release or on NB? There seem to have been chnages in this area recently (on release) and also again changes on master. I could not see any apparent problems, but if it works for you on release as well, we need rather to research the influencs of the inten content, while otherwise tho changes between master and release get interesting.

**Comment by Lineflyer** [comment]
I am on master, will test on release and report.


Von Samsung Mobile gesendet

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: rsudev <notifications@github.com> </div><div>Datum:05.03.2015  19:23  (GMT+01:00) </div><div>An: cgeo/cgeo <cgeo@noreply.github.com> </div><div>Cc: Lars <gc@droescher.eu> </div><div>Betreff: Re: [cgeo] TB link from mail not opening from some mail app (#4719) </div><div>
</div>@Lineflyer Are you on release or on NB? There seem to have been chnages in this area recently (on release) and also again changes on master. I could not see any apparent problems, but if it works for you on release as well, we need rather to research the influencs of the inten content, while otherwise tho changes between master and release get interesting.

**Comment by Lineflyer** [comment]
Tested with release version 2015.02.23 and working normal on two different devices.
On the additional device I used I can furthermore confirm that the intent also contains the 
```
CATEGORIES:
android.intent.category.BROWSABLE 
```

So I think we should investigate the influence of the intent content in this case.

**Comment by Lineflyer** [comment]
OK, additional test:

Device with release version 2015.02.23.
Open link from system mail app is OK
Open link from GMX mail app is not working.

So the cause is the different intent.

Additionally:
Users stated, that "some" versions ago it was also not working with cache links, now cache links are OK with the latest version, but TB links are not OK.
Sorry, I did not get a more precise information from the users :(

**Comment by Lineflyer** [comment]
Forget what I wrote above, the test still wasn't complete:

Let me summarize completely:
Version 2015.02.23:
Intent with `Browsable`: OK
Intent without 'Browsable`: NOK

Version 2015.03.05:
Intent with `Browsable`: OK
Intent without 'Browsable`: OK

So it looks like a problem on current release which is solved on master meanwhile.

**Comment by Lineflyer** [comment]
All seems well with master but release has a problem with TB links

**Comment by Lineflyer** [comment]
Affected user with GMX Mail-App confirmed that 2015.03.05-NB is working again for him.

**Comment by Lineflyer** [comment]
I have to come back to this, as we get more support mails for this problem.

We know, that the current release has this problem and it is fixed on master (was tested above).

Does anyone see a possibility to extract the fix from the difference of both branches and cherrypick a fix to the release branch? Or do we have to wait until we release from master?

**Comment by Lineflyer** [comment]
Reopening due to some users report on support and FB.
More details under investigation.

Does anyone have a clue what was changed here recently (see above).

**Comment by Lineflyer** [comment]
More infos coming in that it fails from various mail apps to open
http://coord.info links for caches and TBs.

Any ideas??

**Comment by Bananeweizen** [comment]
Just as a note: For me opening coord.info links from the GMX app has always worked (it is the one and only app for all my cache notifications).

**Comment by Lineflyer** [comment]
GMX is working for me too. I suspect the manifestation of this issue changed again after the original report.
At the moment most of the people mention, that they are using the gmail app which does not work.
I will also try to reproduce it with gmail.

**Comment by Lineflyer** [comment]
This time it could also be a problem of the hyperlinks used in some of Groundspeaks mails. They appended some parameters to the URL.

I was able to reproduce it with my Samsung Galaxy S4 mail client.

Trying to open this hyperlink fails with the mentione error message:
http://coord.info/GC5PMR2?utm_source=newsletter&utm_medium=email&utm_content=events&utm_campaign=4-6-15

**Comment by Lineflyer** [comment]
@samueltardieu More people than expected seem to use those weekly mailers of Groundspeak which have this problem. Any chance of backporting to release?

**Comment by samueltardieu** [comment]
Done.

**Comment by Lineflyer** [comment]
Cool thanks!

**Comment by Vike91** [comment]
I think this issue should be reopened.
