### ISSUE TITLE
Apply latest fix also to cgeo-legacy or abandon it

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4721]
If I am not wrong, the legacy version still has the problem described in #4691.

We should either fix it and release it or decide to drop legacy.
Opinions?

**Comment by samueltardieu** [comment]
I'd vote for unpublishing the legacy version.

**Comment by SammysHP** [comment]
:+1:

**Comment by Bananeweizen** [comment]
which version do we loose then?  These are the user counts from the play store, at least if I interpret the data right:

Android 2.2
30.044
2,12 %

Android 2.1
2.828
0,20 %

others
1.601
0,11 %

**Comment by Lineflyer** [comment]
We will loose API levels 7-8, so Android 2.1 and 2.2
The current "normal" version start with API 9 (Android 2.3).

On the usage statistics on status.cgeo.org it is below 2% most of the time.

**Comment by Lineflyer** [comment]
I vote for fixing it as the fix looks rather easy and the amount of 2.2 users it still quite "high".

**Comment by samueltardieu** [comment]
@Bananeweizen You should look at the number of users on http://status.cgeo.org/ instead. The Play Store figures are for installed software as far as I understand it, which might not be used anymore.

**Comment by samueltardieu** [comment]
@Lineflyer You can test whether this has been correctly fixed or not.

**Comment by Bananeweizen** [comment]
My thinking is the same as for @Lineflyer. We can easily fix _this_ issue, so we should ship it. If another issue comes, where the effort is high, then let's stop the legacy version.

**Comment by Lineflyer** [comment]
will do

**Comment by Lineflyer** [comment]
I tested the current legacy market release and was able to reproduce #4691. Afterwards I installed 2015.03.06-legacy and confirmed that spoilers are working again.

Tested on
BASE lutea
Android 2.2.2

Basic regression test was also OK.
So I guess we can just publish it?!

Note:
Please do not tag it as a new release as it will probably show up as latest release then?!
I would rather just upload the APK to the existing latest release later on.

**Comment by samueltardieu** [comment]
Yes, publishing it as-is should do the job.

**Comment by Lineflyer** [comment]
Uploaded, will wait a little and then push the release notification and close here.

**Comment by Lineflyer** [comment]
Release is available on Play, status.cgeo.org update. 
Release uploaded to Github release page. Closing.
