### ISSUE TITLE
Hiding out found/own cache no longer reliably working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4726]
2015.03.07-NB

On maps other than the live map (map for a list, single cache map with activated live) I had problems to day to hide found/owned caches if I toggle that setting directly from the map.

Need to look deeper into this to provide more details.
On the live map it seemed to be OK.

**Comment by rsudev** [comment]
I am not sure if it even should work on those (or ever worked), as IIRC we disable that filter in order to show all caches that are in the list (or the one selected), regardless of the owned/found status.

**Comment by Lineflyer** [comment]
Initially you might be right.
But if I enable live on that map I would expect that the filters are used for newly loaded caches on that map.

Still have to test this.Might need some more days.

**Comment by rsudev** [comment]
Agreed. But this would not be easy in our current implementation - and its already in my current mapsforge 0.5 prototype.

**Comment by Lineflyer** [comment]
Are you sure it was like that ever since on maps of a cache which are "live enabled"?
I cant remember seeing this before.

**Comment by Lineflyer** [comment]
I just tested with release 2014.12.22 and it is the same. No fault. Closing.
