### ISSUE TITLE
Embedded images in short description not shown in image tab

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#4727]
@samueltardieu added the ability to view and open embedded images under the "Images" tab after my posted issue #3661

Really great and useful!

But far from all caches shows the image under the "Images" tab.

These does include the image:
http://coord.info/GC5NHA1
http://coord.info/GC4TZMH

These does not include the image:
http://coord.info/GC1EH4K
http://coord.info/GC5NV7Q

I suspect it has something to do with the file size of the image. That it does not show images below a certain file size to filter out language flags, smileys and other "unwanted" images.

If I'm right that filter should be removed so that all images are shown. Or the file size threshold should at least be lowered.

**Comment by SammysHP** [comment]
For http://coord.info/GC1EH4K these images are shown in the images tab:

![1](http://dl.dropbox.com/u/9402254/geocaching/GC1EH4K/coordinates.png)
![2](http://dl.dropbox.com/u/9402254/geocaching/general/e.bmp)
![3](http://dl.dropbox.com/u/9402254/geocaching/general/lurvan.jpg)

**Comment by MrYaz** [comment]
Yes, I see that now...
Should have had triple checked my examples...
I also see now that my theory about file sizes was completely wrong.

Well, another example:
For http://coord.info/GC54VVW these images are shown in the images tab:
https://dl.dropboxusercontent.com/u/8736483/geocahing/geocaching%20canarias02.jpg
http://www.geocaching.com/static/js/CKEditor/4.4.0/plugins/smiley/images/wink_smile.png

but not this one:
https://dl.dropboxusercontent.com/u/8736483/geocahing/Casa-Lercaro-La-Laguna.jpg

These caches also does not include the image in the images tab:
http://coord.info/GC5NR2P
http://coord.info/GC5NW95

**Comment by SammysHP** [comment]
Verified. Maybe because it's in the short description.

**Comment by Lineflyer** [comment]
Subject changed accordingly.

**Comment by samueltardieu** [comment]
@Lineflyer Please test and tell if this should be included in `release` or not.

**Comment by Lineflyer** [comment]
Working for me with 2015.03.09-NB
I did not see any regressions regarding other pictures (from log or long description) for now.

@samueltardieu If you also consider the risk for regressions to be low, you can merge it to release.

**Comment by samueltardieu** [comment]
Low risk.
