### ISSUE TITLE
Rename "Any destination" to "Coordinates"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4729]
In #4290 we discussed that the current name is quite irritating.
I suggest to rename that main menu to "Coordinates" for the time we have it, as this is exactly what is behind that menu...you can enter coordinates.

Opinions?

Remark:
If that is OK, some could do the favor to replace it by the already existing string `search_coordinates` as it would not require new translations then.

**Comment by samueltardieu** [comment]
I tried it briefly earlier today, and "Coordinates" in English (or "Coordonnées" in French) is still too long and gets abbreviated with "…". This doesn't look better than "Any destination".

Is there a shorter word to use there?

**Comment by SammysHP** [comment]
Goto

**Comment by samueltardieu** [comment]
Indeed, "Go to…" looks better.

![Screenshot](http://i.imgur.com/Xspar4p.png)

**Comment by samueltardieu** [comment]
And it looks even better without the "…" (no screenshot).

**Comment by SammysHP** [comment]
Android, are you kidding me?! ".." is smaller than "s"?!

**Comment by samueltardieu** [comment]
I had the same WTF moment as you did :)

**Comment by Lineflyer** [comment]
Before we get into a discussion about the main menu as whole (because I do not see why all those items need to be truncated on big screens) I also vote for "Go to".
I guess this would be a new string then, but I still would favor to put it in `release` as we can give us some time to wait for incoming translations.

**Comment by SammysHP** [comment]
What's with the translation?

**Comment by samueltardieu** [comment]
Yup. In fact, that would be the same string identifier, with a different content, which needs to be retranslated on crowdin.

I'll do the change.

**Comment by samueltardieu** [comment]
Fixed with f31d72bb8ba49878b7996b7f9defb8f7eebc4556.
