### ISSUE TITLE
Search function broken

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4730]
The new advanced search just went live.
some functions seem broken by this.

**Comment by Lineflyer** [comment]
I think the loc file download is gone ... not so good

**Comment by rsudev** [comment]
I tried to manually trigger the old search in the browser and it worked, including waypoint download.
I don't think they can abandon that, it is a crucial feature to really be able to get the result of your search onto your device...

**Comment by rsudev** [comment]
My anaylsis for today seems to indicate, that they require a change to the request for the .loc-file.
- they have two headers we do not address: __LASTFOCUS and __VIEWSTATEGENERATOR
- the url seems to require additional query parameters, which we can read out of the <form action="" /> attribute.
Will continue tomorrow.

**Comment by Lineflyer** [comment]
Remark:
The fix was tested with a RC-version. Tests are OK.
A new release 2015.03.12 has been published.

Lets see if this fix is long lasting...

**Comment by Lineflyer** [comment]
ToDo:
- [ ] Tag release on Github
- [ ] Upload APK to Github
- [ ]  Clear warning on notification system
- [ ] Create release notification on notification system
- [ ] Post to social networks

**Comment by mucek4** [comment]
I updated notification.

**Comment by rsudev** [comment]
(tag done by @samueltardieu)

**Comment by Lineflyer** [comment]
All tasks done.
