### ISSUE TITLE
Fix #4730 on legacy branch

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4731]
@rsudev suggested to also apply the fix for #4730 to legacy and release a new version.

**Comment by rsudev** [comment]
Fix applied, build started. Waiting for smoke-test.

**Comment by Lineflyer** [comment]
Will do a smoke test this evening.

**Comment by Lineflyer** [comment]
Problems with the battery of the 2.2 device...stay tuned.

**Comment by Lineflyer** [comment]
Smoke test of 2015.03.13-legacy OK.
Published on Play, waiting for some hours then I will update status.cgeo.org as well.

**Comment by rsudev** [comment]
Thanks @Lineflyer !

**Comment by Lineflyer** [comment]
Notification sent. We are done.
