### ISSUE TITLE
Search result filter 

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#4741]
I can't use filter to searched results it always return me to saved cache instead of search results.

Steps to reproduce:
Open c:geo
Click search 
Type ex. Warszawa in address
Display results
Use filter

Result:
Filtered stored cache not searched cache

--- System information ---
Device: LG-D802 (g2_open_com, lge)
Android version: 4.4.2
Android build: KOT49I.D80220h
Cgeo version: 2015.03.16-NB-bab02fe
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: false
Map strategy: detailed
HW-acceleration: enabled (Disabled by default: no)
geocaching.com: logged in (Login OK) / Basic Member
System language: pl_PL
Installed cgeo plugins: none
--- End of system information ---

**Comment by Lineflyer** [comment]
Confirmed with 2015.03.16-NB1 with the scenario described above.

**Comment by rsudev** [comment]
Fixed directly on release - my local tests showed no issues. Assigned for re-test to lineflyer.

**Comment by samueltardieu** [comment]
This has been closed by merge to master, reopening.

**Comment by Lineflyer** [comment]
Fix confirmed with 2015.03.23-NB1. 
I will build a new RC and also test there.

**Comment by Lineflyer** [comment]
Working in 2015.03.23-RC as well. Closing
