### ISSUE TITLE
Eclipse: make missing `final` a fatal error for cgeo sources

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4745]
I have made missing `final` qualifiers in parameters, fields and local variables a fatal error in IntelliJ IDEA. Some Eclipse user should do the same there.

Best done in the `release` branch, then merged into `master`.

**Comment by Bananeweizen** [comment]
There is no option for that. But the formatter already adds "final" wherever possible, so at least just "not declaring final although it can be final" will be okay. We would need checkstyle or a similar source code based static code analysis tool to check this (and it would still depend on the developers to have it actually installed).

**Comment by Bananeweizen** [comment]
I'll close this one, since there is still no possibility to have this as a native setting in Eclipse. Nevertheless I feel that "final" is more often forgotten by non eclipse users. :)
