### ISSUE TITLE
Fill ratings questionnaire on Google Play

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4747]
See [this blog post](http://android-developers.blogspot.com/2015/03/creating-better-user-experiences-on.html) which explains why the rating systems will be used everywhere in Google Play store.

@Lineflyer should probably be the one who fills it, while giving the cgeo-dev address as the contact address.

**Comment by Lineflyer** [comment]
I will read this through and try if I can fill it.
@mucek4 Is c:geo currently published in the category "Entertainment" or "Game"?

**Comment by Bananeweizen** [comment]
It's entertainment as you can see directly on the app play store page: https://play.google.com/store/apps/details?id=cgeo.geocaching&hl=de

**Comment by mucek4** [comment]
We send position to go4cache.

**Comment by Bananeweizen** [comment]
> We send position to go4cache.

Actually not anymore.

**Comment by Lineflyer** [comment]
> > We send position to go4cache.
> Actually not anymore.

And if this comes back anytime in future we should handle it as a plugin.

This brings me to the question why in the Console we can not select c:geo to be on the "All" rating?

**Comment by samueltardieu** [comment]
2015-03-18 12:28 GMT+01:00 Lars <notifications@github.com>:

>  We send position to go4cache.
> Actually not anymore.
>
>  And if this comes back anytime in future we should handle it as a plugin.
>
> This brings me to the question why in the Console we can not select c:geo
> to be on the "All" rating?
>

As far as I understand, we do not choose the rating anymore.

**Comment by Lineflyer** [comment]
New rating sytem filled for c:geo and both plugins.
