### ISSUE TITLE
Device can't establish https connection

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4750]
While c:geo on my Android 2.3.x device was able to login in the last weeks it suddenly stopped working.
In the log I can see this:
```
11:41:17.193 Debug cgeo 839  [network-8] GET https://www.geocaching.com/login/default.aspx
11:41:21.779 Warning cgeo 839  [network-8] Failure (4603 ms) GET https://www.geocaching.com/login/default.aspx (javax.net.ssl.SSLPeerUnverifiedException: No peer certificate)
11:41:21.779 Error cgeo 839  [network-8] Login.login: Failed to retrieve login page (1st)
```

If I open a browser on that device and try to open the gc.com webpage I get the same error message.
Now I am wondering what happend here. Did they introduce this force to https recently or did I accidently delete some certificates on my device (I think not).

Can someone tell if this might be a general problem on rather old devices?
Is there any way to force back to http or accept all certificates for our login?

**Comment by samueltardieu** [comment]
GeoTrust, who signed their certificate, should be recognized by Android 2.3+: https://www.geotrust.com/support/system-compatibility/

I am against accepting all certificates or using HTTP, that defeats the purpose of HTTPS completely.

**Comment by SammysHP** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=geocaching.com&hideResults=on

Hehe…

**Comment by Lineflyer** [comment]
False alarm:
The problem was not that the Root CA was missing, but that my device lost the date and started back with 1st January 1980. So the certificate was judged as not yet valid.
That might be an addon for the FAQ then.
