### ISSUE TITLE
Calendar end time not detected

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4753]
For GC5PQD9 the end time is not detected.

**Comment by Hauwertlhaufn** [comment]
Same problem for [GC5QEHB](http://www.geocaching.com/geocache/GC5QEHB_22-rmk-stammtisch-grill-edition).

**Comment by Bananeweizen** [comment]
Seems like I confused myself here. The end time has never been available for calendar entries, so this would rather be a feature request.

**Comment by Lineflyer** [comment]
Superseeded by #7243
