### ISSUE TITLE
mapshortlinkicon in cachepreview

### ISSUE THREAD

**Issue by Slini11** [cgeo/cgeo#4754]
Please include the shortlink icon of the map into the preview window of a cache.
![screenshot_2015-03-22-13-15-30](https://cloud.githubusercontent.com/assets/5831333/6769354/0da8e1d2-d098-11e4-9ca7-adc64c76d1f9.png)

**Comment by rsudev** [comment]
You can achieve this already by assigning the map as secondary navigation tool on the settings and doing a long press on the compass icon.

**Comment by Lineflyer** [comment]
@Slini11 
I think I dont fully understand your proposal...  Why go to a map while you are currently in a popup window of the map. That would open another instance of the map which seems unnecessary in that case (and additionally causes memory problems with OSM offline maps).

**Comment by Lineflyer** [comment]
Closing due to lack of feedback (see also comments above regarding a workaround).
