### ISSUE TITLE
Search owned caches does not work

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4756]
2015.03.17-RC:
A user on FB reported that loading his owned caches using the "Show owned caches" function in the search menu does return nothing.

I can not reproduce this but asked for more details about what is showing up and the step-by-step.

**Comment by rsudev** [comment]
When I tried several searches for the filter fix I also experienced some hiccups when searching by owner. For some owners it was no problem, for others I didn't get results, but as I was focused on something else I didn't look any further.
I did now some more test. The user that doesn't work is BM, the other that I tried and worked are PM (I only now one BM with hidden cache), perhaps does this help for further research.

**Comment by rsudev** [comment]
Ok, forget the topic of BM - I had 'hide found' active and have found the caches in question. So from my perspective this functionalso works fully.

**Comment by Lineflyer** [comment]
The setting "hide owned and found" should be ignored when using the "Search my caches" function and it works like that for me.
So it seems BM+ Setting active is the problem here?! I will test that.

**Comment by Lineflyer** [comment]
I checked all combinations of membership type and hide settings but the search own function works flawless.
Tested with 2015.03.27-RC1
