### ISSUE TITLE
Add menu icon for showing hint in compass/cache map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4757]
As discussed on IRC on 2015.02.11:
Proposal: http://thenounproject.com/term/new-idea/104277/

**Comment by rsudev** [comment]
I had to fiddle a little around to get there IMO. What do you think about this?
![ic_menu_hint](https://cloud.githubusercontent.com/assets/780005/6813529/3dbf33d2-d276-11e4-9f29-f9e64a8dff44.png)

**Comment by rsudev** [comment]
I had to fiddle around a little to get there. What do you think?
![screenshot_20150324](https://cloud.githubusercontent.com/assets/780005/6813546/67e4cc08-d276-11e4-9492-82472a10791e.png)

**Comment by Lineflyer** [comment]
Its looks blurred in your screenshot.

And other thoughts:
Without the icon the meaning was really visible and everyone would stumble upon that new function. Now with the icon its more hidden (and not everyone knows that he can long press to get the function). So wouldn't this be another thing for a showcase for a new feature?

**Comment by Bananeweizen** [comment]
Showcase sounds good to me.

**Comment by rsudev** [comment]
My bad - created initially only the mdpi icon. Better now:
![screenshot_20150325](https://cloud.githubusercontent.com/assets/780005/6819378/7988bdee-d2c0-11e4-8089-b426dd5330e1.png)

**Comment by Bananeweizen** [comment]
I hereby point to https://github.com/cgeo/cgeo/wiki/How-to-create-custom-icons for a workflow...

**Comment by rsudev** [comment]
I am not sure how and if I can use this site in a sensible fashion to create nice icons in all resolutions from an svg. But knowing the necessary dimming value allowed me to create better fitting variants:
![device-2015-03-25-101635](https://cloud.githubusercontent.com/assets/780005/6821588/6a227bb6-d2d8-11e4-8e25-542288f817ec.png)

**Comment by Lineflyer** [comment]
Look good!
@rsudev Do you know how to add a showcase for that?

Not sure whether it is a good idea at this point of time:
On one hand it would be extremly helpful for a new feature, on the other hand we would need to delay the relase as we need translations for the showcase before releasing.

We do not have any hurry to release right now, so we could add the showcase and wait some more days IMO.
Opinions?

**Comment by rsudev** [comment]
I already tried that, as it looked quite straight-forward, but my first attempt didn't work.
I definitely think that this would be the time for adding that, even if we took some more days to release (calling for translation should yield very fast results)

**Comment by rsudev** [comment]
What do you think?
![device-2015-03-25-174158](https://cloud.githubusercontent.com/assets/780005/6829840/590cae44-d316-11e4-86d8-7a327eb8e7e7.png)

**Comment by Lineflyer** [comment]
Very good if it looks the same in portrait mode.

**Comment by rsudev** [comment]
If nobody object I put it to release then...

**Comment by Lineflyer** [comment]
Sure

**Comment by Lineflyer** [comment]
You should merge and upload strings now as we probably need to release soon due to the site change.

**Comment by rsudev** [comment]
I am currently blocked on failing to detect if the item in question is not in the action bar (which can happen on 480*800 screens in portrait), everything else is ready.

**Comment by Lineflyer** [comment]
As written on IRC:
I suggest to make "hint" the topmost icon in order to prevent it from being hidden in the overflow (as the showcase would be not shown in this case).

**Comment by rsudev** [comment]
Strings uplaoded to crowdin, german strings ready for review.

**Comment by Lineflyer** [comment]
I can see in the history, that the new strings have been present and you suggested a translation. However now they seem missing on crowdin...did something went wrong?
