### ISSUE TITLE
Views not displayed

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4759]
Sitting in HMC in Vietnam. Home coordinates in Germany. Searching for keyword Metzger. In the result list some views are missing. Switching to other apps and back adds some of the missing views. Rebooted phone and still the same. Source of March 9.

**Comment by Bananeweizen** [comment]
![screenshot_2015-03-24-08-01-26](https://cloud.githubusercontent.com/assets/406876/6802069/e1e81fee-d25f-11e4-8b7f-0b4ab2262c93.png)

**Comment by rsudev** [comment]
I would say this is #4730 - they changed the link to get the coordinates. Fixed around the 12th

**Comment by Lineflyer** [comment]
Yes, it is.
The GC-caches which are not offline are missing coordinates due to the reasond mentioned by @rsudev

**Comment by Lineflyer** [comment]
Greetings to Vietnam...and why is our actionbar red?

**Comment by Bananeweizen** [comment]
Red action bar is because of using a theme on my phone. I would recommend doing that during testing also every now and then as it shows where we have fixed sizes in layouts, which suddenly don't fit the themed fonts anymore.
