### ISSUE TITLE
Data on external SD

### ISSUE THREAD

**Issue by Megachip** [cgeo/cgeo#4760]
Looks I got some problems to get the data dir (.geo) to my external sd card on a Xperia Z2 (Android 4.4.4).
Wen choosing this option the dir is set to /storage/emulated/0, which is the internal storage. The external is located on /storage/sdcard1.
This is almost the problem described in faqs (http://faq.cgeo.org/#1_67)

Possible this dialog/feature would be working on more phones if the user could choose the directory like for external maps.

**Comment by SammysHP** [comment]
This is a known problem (thus the FAQ entry).

Please see #706 and #3921.

Short answer: It is not easy, maybe too hard.
