### ISSUE TITLE
Personal note upload has disappeared

### ISSUE THREAD

**Issue by g-o-caching** [cgeo/cgeo#4765]
The Personal notes upload button has disappeared.  Could be linked with the geocaching.com website update of 25th March 2015 

--- System information ---
Device: SM-G900F (kltexx, samsung)
Android version: 5.0
Android build: LRX21T.G900FXXU1BOC7
Cgeo version: 2015.03.12
Play services: present
Use Play services: yes
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
--- End of system information ---

**Comment by SammysHP** [comment]
Another issue that is caused by #4763.

**Comment by Lineflyer** [comment]
Solved implicitly with  fb8a006 and tested in 2015.03.26-RC
