### ISSUE TITLE
Strings missing on Crowdin

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4768]
According to my history view on Crowdin the strings for the new showcase have been present but have been deleted this morning by an additional upload to Crowdin.

Can someone crosscheck what happend here?

If this has been clarified I would send out another mail to the translators asking for help.

**Comment by samueltardieu** [comment]
I uploaded the up-to-date strings to crowdin as you requested on IRC. If some strings have disappeared, it probably means that they were previously uploaded from a side branch, not release or master.

**Comment by Lineflyer** [comment]
I am stil missing these strings:
https://github.com/cgeo/cgeo/blob/16b220db35235ed028ff7c323904cb4643dbbb5f/main/res/values/strings.xml#L1324

**Comment by samueltardieu** [comment]
Indeed this is strange. I'll reupload the strings.

**Comment by Lineflyer** [comment]
@samueltardieu 
I don't see any difference.
I am out for today. If you upload them, can you also ping the translators, because IMHO we should release tomorrow.

**Comment by rsudev** [comment]
I have again updated from master, the showcase strings are again present. Translators have been notified.

**Comment by Lineflyer** [comment]
Thanks, excellent!
