### ISSUE TITLE
reCaptcha unreadable or nonfunctional

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4770]
It might be only me, but while testing basic member functions today, I was not successful entering the right letters as it looks really blurred for me.

I will check in the website later, whether it is really that unreadable or we habe an issue while showing it.

There is also a chance, that I entered it correct but the function behind is no longer working...I am not sure if the same loc file procedure is called as for premium members or it was forgotten to adapt it at this point.

**Comment by Lineflyer** [comment]
Strange:
When I look on the waypoint download on the website (basic member), I can see a reCaptcha of a single well readable word like here:
http://www.geocaching.com/seek/nearest.aspx?lat=51.340933&lng=7.046483

In c:geo I always see two words with graphical underlay elements.

**Comment by Lineflyer** [comment]
This is how it looks in c:geo
http://i.imgur.com/svEkFf0.png

This is the reCaptcha on the website for the same user:
http://i.imgur.com/DcG1nH7.png

Explanation?

**Comment by rsudev** [comment]
You should disabla javascript (for google.com) in your brwoser, than you see the same (basically unsolvable) captcha as in c:geo.
So the noscript variant is practically useless - not sure if we can address the script-based variant, which at least gives the user a chance...
Or if we abandon that alltogether, as apparantly nobody is using it anyway (or do we have complaints about that in support?).

**Comment by Lineflyer** [comment]
> Or if we abandon that alltogether, as apparantly nobody is using it anyway (or do we have complaints about that in support?).

Yes, we should remove the possibility to enable the Recaptcha.
If there are complaints on support mail they are always about the unreadable captcha...not about not having the features behind.

**Comment by Lineflyer** [comment]
Link to #4304

**Comment by Bananeweizen** [comment]
I'm also in favor of removing it. Nobody of us developers uses this and therefore it is basically always untested. If I remember right, this would also remove one architectually rather confusing callback in the connectors, which is only for recaptchas.

**Comment by Lineflyer** [comment]
@Bananeweizen If you find the time: Remove it!

**Comment by Bananeweizen** [comment]
I've not removed the related strings, since that should rather be done in a generic cleanup of no longer used strings.
