### ISSUE TITLE
Adapt legacy or abandon it

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4773]
Shall we apply the adaptions for the gc.com change to legacy or depublish it?
I can't estimate the effort....so others have to judge this.

**Comment by mucek4** [comment]
Didn't really follow the fix, but I expect changing regex shall not be a problem

**Comment by mucek4** [comment]
@Lineflyer can you check what does not work in Legacy. What needs to be fixed?

**Comment by Lineflyer** [comment]
I did already, it is:
#4763 and #4761 (and of course other issues caused by this)

**Comment by mucek4** [comment]
The search change (and loc file downlod) from about 14 days ago is not affected there?

**Comment by rsudev** [comment]
This fix was already released on the 13th of March :)

**Comment by rsudev** [comment]
legacy updated, briefly tested and built. @Lineflyer can you do a smoke test as well?

**Comment by Lineflyer** [comment]
No, as I am off for the easter days.
I would say we should just release it.



Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: rsudev <notifications@github.com> 
Datum:02.04.2015  23:33  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu> 
Betreff: Re: [cgeo] Adapt legacy or abandon it (#4773) 

legacy updated, briefly tested and built. @Lineflyer can you do a smoke test as well?

**Comment by rsudev** [comment]
Uploaded to play and release on github.

**Comment by Lineflyer** [comment]
We forgot the update status.cgeo.org accordingly.
I have done this now. 
@rsudev Thanks for maintaining the legacy version.
