### ISSUE TITLE
Map view of "nearby caches" only shows only saved caches

### ISSUE THREAD

**Issue by dl1ely** [cgeo/cgeo#4774]
I am at my parent's place. "nearby caches" lists 19 caches. One of them is a solved mystery that is saved in a list and has a changed "final" waypoint. When i press the "map" icon in the "nearby" list, the subtitle changes to "1 cache" instead of "19 caches" and the map view only shows 2 waypoints, the original and the newly set of that stored solved mystery. 

Then i saved another cache from the nearby-list, and now map view shows this 2 caches.

Happened with NB 2015-03-19, still present in 2015-03-28.

**Comment by Lineflyer** [comment]
Are you Basic Member?

**Comment by dl1ely** [comment]
No, premium…

**Comment by Lineflyer** [comment]
Can you post a picture of the search result please.
I was wondering whether those other 19 caches might have no coordinates (as it is for basic members unless they are saved).
That would perfectly explain your experience.

**Comment by rsudev** [comment]
@dl1ely There has been a website-change from gc.com which would explain this behaviour for NB from 19.03., but should have been fixed since version from 27.03. ...
Quite strange

**Comment by dl1ely** [comment]
While taking the screenshots, i could not reproduce. Perhaps getting the coordinates took longer than normal initially, so that only the saved caches were visible, and i left map view too quickly to see the other caches appear? Sorry for the wrong alarm. Closed.
