### ISSUE TITLE
Recognize geocache imported from GSAK as "with corrected coordinates"

### ISSUE THREAD

**Issue by valentijnscholten** [cgeo/cgeo#4775]
Hi,

I am working on solving a series of 139 mystery caches in GSAK.
When exporting the solved caches to a GPX and importing them in c:geo, it would be nice if c:geo would recognize the caches are solved i.e. it recognizes that there are corrected coordinates.

The export from GSAK does contain the original coordinates, so I think the import could recognize this?

Sample waypoint with corrected coordinates:

```
 <wpt lat="51.223033" lon="6.027767">
  <ele>24.0</ele>
  <time>2014-05-10T08:00:00Z</time>
  <name>GC4PGTG</name>
  <desc>RGGG 012 - Remunjs Rundje - Historische figuren by rggg (2/1,5)</desc>
  <url>http://www.geocaching.com/seek/cache_details.aspx?guid=555c3068-63c7-4c53-8e31-2473203d2f1f</url>
  <urlname>RGGG 012 - Remunjs Rundje - Historische figuren by rggg</urlname>
  <sym>Geocache</sym>
  <type>Geocache|Unknown Cache</type>
    <gsak:wptExtension xmlns:gsak="http://www.gsak.net/xmlv1/6">
      <gsak:UserFlag>false</gsak:UserFlag>
      <gsak:Lock>false</gsak:Lock>
      <gsak:DNF>false</gsak:DNF>
      <gsak:Watch>false</gsak:Watch>
      <gsak:UserData></gsak:UserData>
      <gsak:LatBeforeCorrect>51.223032</gsak:LatBeforeCorrect>
      <gsak:LonBeforeCorrect>6.026147</gsak:LonBeforeCorrect>
      <gsak:StateBeforeCorrect>Limburg</gsak:StateBeforeCorrect>
      <gsak:CountyBeforeCorrect></gsak:CountyBeforeCorrect>
      <gsak:FirstToFind>false</gsak:FirstToFind>
      <gsak:User2></gsak:User2>
      <gsak:User3></gsak:User3>
      <gsak:User4></gsak:User4>
      <gsak:County></gsak:County>
      <gsak:UserSort>0</gsak:UserSort>
      <gsak:SmartName>RGGG012R</gsak:SmartName>
      <gsak:LastGpxDate>2015-03-19</gsak:LastGpxDate>
      <gsak:Code>GC4PGTG</gsak:Code>
      <gsak:Resolution>90m</gsak:Resolution>
      <gsak:IsPremium>false</gsak:IsPremium>
      <gsak:FavPoints>2</gsak:FavPoints>
      <gsak:GcNote></gsak:GcNote>
      <gsak:Guid>555c3068-63c7-4c53-8e31-2473203d2f1f</gsak:Guid>
      <gsak:CacheImages>
      </gsak:CacheImages>
      <gsak:LogImages>
      </gsak:LogImages>
      <gsak:CustomData>
Custom_Start:cCode:Custom_Data:GC4PGTG:Custom_End

      </gsak:CustomData>
    </gsak:wptExtension>

```

If the following tags are present, c:geo could create a child waypoint "Original Coordinates" ?

```
      <gsak:LatBeforeCorrect>51.223032</gsak:LatBeforeCorrect>
      <gsak:LonBeforeCorrect>6.026147</gsak:LonBeforeCorrect>
```

The final/solved coordinates are exported by GSAK in the "standard" coordinate fields.

```
 <wpt lat="51.223033" lon="6.027767">
```

Does this sound like a good addition to c:geo? feasible?

It would be even more nice if c:geo could upload the final/solved coordinates to gc.com.

Valentijn

**Comment by Lineflyer** [comment]
Sounds reasonable, I only wonder why we did not ever get such a request before.
Is this the "default" way GSAK exports solved mysteries?

**Comment by valentijnscholten** [comment]
I think it is the default way.

A) 
- Correct the coordinates for a cache on gc.com
- Load the cache into GSAK using API or PQ function
- GSAK will detect the corrected coordinates and flag the cache as having corrected coordinates.
- the GPX export will look like the above.

B)
- Load a cache with no corrected coordinates into GSAK using API or PQ function.
- Right click on cache
- Select "corrected coordinates"
- Enter corrected coordinates
- The cache is now flagged in GSAK as having corrected coordinates.
- GPX export will look like the above.


The is also the possibility to create child waypoints in GSAK. One of the types you can create is "Final location". This however doesn't influence the coordinates of the cache itself in the GPX. It also doesn't set the "corrected coordinates" flag in GSAK and also doesn't put any "BeforeCorrect" values in the GPX. There's also no possibilty to create a child waypoint of type "Original Coordinates", as you can have in c:geo.

**Comment by nagisml** [comment]
I can not see that working on version 2015.03.31 should it be in?

**Comment by rsudev** [comment]
No, it is only on our master branch and will be part of the next feature release (2015.03.31 was a bugfix release)
