### ISSUE TITLE
Geokrety login UI should be easier

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4778]
Currently the user enters his login and password and additionally has to select "Retrieve API key".
This could be redesigned to make it look likt e.g. the authorization to Opencaching sites.
Just enter a username and password and select "Authorize" to complete it.

Not yet sure however about how this thing works.

**Comment by kumy** [comment]
Note: Opencaching sites connector use OAuth authentication. This is not supported on Geokrety.org.

**Comment by Lineflyer** [comment]
@Kumy:
Can you explain the working mode in more detail:
- The user enters username and password. Is it mandatory to click on "Retrieve API-key" afterwards?
- If optional, what is the difference without retrieving it?

My goal would be to design the user interface as easy as possible at this point: Asking for credentials and maybe some button to check them and give a feedback.. Retrieving an API-key could be done in the background without bothering the user with a decision he does not understand.

**Comment by kumy** [comment]
Retrieve the API is mandatory.
I've started a rework of this activity yesterday.
I'll check if I can do the retrieve action automatically after the user entered his login/password.
Does this correspond to what you expect ?

**Comment by samueltardieu** [comment]
Why don't you do it when it is needed unless it has been retrieved already? And erase it as soon as the user changes its credentials?

**Comment by kumy** [comment]
Good idea too.
But I think we should try to retrieve the key as soon as the user fill both credentials fields. Otherwise, if a bad credential was entered, log may fail and user may not understand why.

BTW, geokrety.org provides SSL support, but they're certificate is self signed.. :/
Should I try to 'auto-accept' the "bad" certificate, or continue to not use SSL?

**Comment by samueltardieu** [comment]
You may accept it if you find a way to include it in the application, and only for this site (that should not allow someone stealing GK CA root certificate to sign certificates that we would accept for other sites such as geocaching.com). I would prefer that we do not pretend that we properly use https when we don't.

**Comment by samueltardieu** [comment]
@kumy: even if geokrety.org does not use OAuth, why not mimic it and present the same process for the user as is done for opencaching sites (ask for login/password and check immediately as you propose, but don't store the password at all afterwards)?

From the user point of view, retrieving their API key is similar to retrieving a OAuth access token, except that we will ask for the username and password in an application page instead of on a web page.

**Comment by rsudev** [comment]
I would definitely vote for trying to use SSL, because even with a self-signed certificate we get encryption. And with certificate pinning we can even minimize the risk of MITM-attacks. Both of these are better than sending passwords in clear text always.

**Comment by kumy** [comment]
Ok for SSL, I'll try do that later.

So, to sum up, the GK preference screen should show.

1) activate checkbox (off by default) (used only for user log, not for lookup #4796)
2) show an "Authorize c:geo" button, that present a new page, asking the user to enter his credentials.
3) once credentials entered, lookup is done automatically.
4) secid is stored and credential forgotten.

I'am right? ;)

**Comment by samueltardieu** [comment]
@rsudev: only if it doesn't make us accept any certificate, because we check the certificate for a number of sites already (extremcaching.com, geocaching.com, open.mapquestapi.com) and I would not want to allow MITM for those.

**Comment by samueltardieu** [comment]
@kumy: yup, that would be great.

**Comment by rsudev** [comment]
@samueltardieu For sure. It should only affect connections to this specific server, we should not 'trust' this certificate in any other context and we need to pin it after first connect (store the fingerprint in preferences for example) to mitigate somebody setting up a fake server and manipulating DNS or such.

**Comment by kumy** [comment]
#4823 opened for SSL subject ;)

**Comment by kumy** [comment]
Is this visually what's expected?

![screencap](https://cloud.githubusercontent.com/assets/176794/6969813/bb4ebf46-d971-11e4-9eb1-6aa1b58f17d6.png)
![screencap2](https://cloud.githubusercontent.com/assets/176794/6969829/d6cd910c-d971-11e4-9b05-13f0122a164f.png)

**Comment by kumy** [comment]
Questions:
* if the user has authenticated, but then disabled the connector. Should we allow them to log a Kret, or redirect them to the concerned settings activity?

* Should the secid be removed from the device when the connector is disabled?

Found that the Travelbug Connector allow to log a TB, while GC connector is marked disabled...

**Comment by kumy** [comment]
Would someone have a look at PR #4846 please.

**Comment by Lineflyer** [comment]
@kumy 
The design is good. It also solves quite some issues test users had today with the current implementation, i.e. none of them did recognize that "Retrieve API-key" is mandatory to make it work.

Regarding your questions:
1.
This behavior is IMHO wuite inconsistent with the different connectors of c:geo. In most cases we still allow data transfer although it is deactivated. So in this case deactivating the connector would just disable the automatic loading of data but on demand activities are still possible. 
This is user friendly somehow although not really consequent but I prefer this.

2.
According to what I wrote in 1. it should stay stored (as it does for OC connectors AFAIK).
