### ISSUE TITLE
Wrong GC TB inventory 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4780]
With 2015.03.28-NB1 (incl. Geokrety PR) I see the following problem:

Each cache does only list one TB in the inventory list independently if GK connector is active or not.
For example:
GC3TCGP contains 2 TBs (as of 28.03.2015 - Might change!)
Open it with 2015.03.28 --> 2 TBs shown in list, both TBs are shown in Inventory-Tab
Open with 2015.03.28-NB1 --> 2 TBs shown in list, only one TB shown in inventory

Another example (with mixed TB/GK):
GC3FJ5F contains 2 TB and 1 GK (as of 28.03.2015 - Might change!)
Open it with 2015.03.28 --> 2 TBs shown in list, both TBs are shown in Inventory-Tab
Open with 2015.03.28-NB1 --> 2 TBs shown in list, only one TB and one GK shown in inventory

It seems that now only 1 TB is shown

**Comment by kumy** [comment]
I'll try to find what's wrong...

**Comment by kumy** [comment]
25ba598 introduced the bug.

**Comment by Lineflyer** [comment]
Tested and working with 2015.03.30-NB
