### ISSUE TITLE
TB count in list wrong for OC with GK

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4781]
2015.03.28-NB1:
- Open OC10E19
- Save it for offline use
- In the list of caches 7 TBs are shown
- Open the cache
- Look at the inventory 

--> 6 GKs are listed for this cache.

**Comment by kumy** [comment]
Cannot reproduce in the current master. 052dc9a

**Comment by kumy** [comment]
Doesn't seem related to c:geo.
But more to a non up-to-date response from OKAPI server.

OC10E19 has really 6 GK.

* GKAB67 is not in this cache anymore http://geokrety.org/konkret.php?id=43879

Data is good in GK/GKM exports:
* http://geokrety.org/export2.php?wpt=OC10E19
* http://geokretymap.org/export2.php?wpt=OC10E19

With the debugger, I can see 7 GK from the OkapiService response...

**Comment by Lineflyer** [comment]
@kumy You are right. Do you have an idea at what frequency OC data is updated/synced with GK?
I do still see the difference

**Comment by kumy** [comment]
@Lineflyer I'm sorry I don't know about the frequency.
OC service should have missed an update.
I think it'll be corrected on the new GK move.

**Comment by Lineflyer** [comment]
So anyway no issue here but good to know.

**Comment by following5** [comment]
Geokret data inconsistencies at OC.de are a well known [issue](http://redmine.opencaching.de/issues/18) for years. I will have a look at it now.
