### ISSUE TITLE
Copy functions not working on Nexus 7

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4782]
From support:

User long tapped on the geocache name.
This should result in a headline being shown with "Name" and the Copy,Done and share buttons.

However for him it looks like this:
Note that "Name" is not shown and "Translate to %s" is shown.
If the user tries to copy the clipboard content is empty.
![20150328_210545](https://cloud.githubusercontent.com/assets/949669/6884776/2cf147c8-d601-11e4-9deb-b414e6b61cc1.jpg)

System information:
--- System information ---
Device: Nexus 7 (nakasi, google)
Android version: 5.1
Android build: LMY47D
Cgeo version: 2015.03.28
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: false
Map strategy: detailed
HW-acceleration: enabled (default state)
geocaching.com: logged in (Login OK) / Premium
System language: en_US (cgeo forced to English)
Installed cgeo plugins: none
--- End of system information ---

**Comment by Lineflyer** [comment]
Further down a better screenshot.
Can this be Android version specific (5.1!)...

![screenshot_2015-03-29-07-56-49](https://cloud.githubusercontent.com/assets/949669/6886631/181c2032-d644-11e4-85fc-5baca6a4a374.png)

**Comment by rsudev** [comment]
Same as #4835, closing here.
