### ISSUE TITLE
String not localized

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4784]
2015.04.29-NB:
- Open GKC240
- Start logging
- Enter a wrong tracking code
- Send the log

A toast is shown `[No such Geokret!]` which is not contained in `strings.xml`

**Comment by samueltardieu** [comment]
Strings uploaded to crowdin.

**Comment by Lineflyer** [comment]
Thats good, but the mentioned string is not contained but seems hardcoded (or retrieved from the server?).

**Comment by samueltardieu** [comment]
Probably retrieved by server. The language should be set while retrieving data.

**Comment by kumy** [comment]
Error message comes from the upstream service.

The (optional) `mobile_lang` variable in the POST should be set to one of these : http://geokrety.org/rzeczy/lang/

I remember we've briefly talk about this variable on IRC.
The actual implementation use `Locale.getDefault().toString()`

**Comment by samueltardieu** [comment]
Will that work even when the user selects English as the cgeo language or will it return the system language? Shouldn't we get `Resources#getConfiguration().locale` instead?

**Comment by kumy** [comment]
I'll try your suggestion, soon.
Thanks for the hint.

**Comment by kumy** [comment]
PR  #4800
