### ISSUE TITLE
Own coordinates not retrievable for Gk visit log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4785]
2015.03.28-NB1:
- Enter GKC240 in the search field on main screen
- Start logging the GK
- Select "Visit"
- Click on the coordinate field
- Click on "My coordinates" in the coordinate window

Error toast: "c:geo could not retrieve the current location" although GPS is active and fixed.

**Comment by kumy** [comment]
Verified

**Comment by kumy** [comment]
PR #4815
