### ISSUE TITLE
Coordinate field in GK logging has no preset

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4786]
2015.03.28-NB1:
- Open GKC240
- Start logging 

All fields have a preset indicating their meaning (e.g. "Geocode", "Log-Text") however the coordinate field is empty, so it's meaning is unclear unless you click on it.

**Comment by kumy** [comment]
PR #4795

**Comment by Lineflyer** [comment]
Tested and working  with 2015.03.31-NB2
