### ISSUE TITLE
GK visit should be possible without geocode

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4787]
2015.03.28-NB1:
- Open GKC240
- Start logging
- Select log type "Visit"
- Enter valid coordinates, tracking code and log text
- Try to send the log

Error toast: `Geocode missing...`

Comparing to the geokrety.org website it should be possible to post a visit log just with coordinates without the need for a geocode.

**Comment by kumy** [comment]
PR #4797.
Would an "You're about to send a log without a cache Geocode. It's encouraged to set one. Do you really want to proceed?" Yes/Cancel dialog be useful?

**Comment by kumy** [comment]
Any thought about about the message ?

**Comment by Lineflyer** [comment]
Solved with PR #4797 which is merged already.

@kumy 
Can you put the remaining question into a new issue?
