### ISSUE TITLE
Problems logging TB with newest NBs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4788]
Reported on Support with 2015.03.29-NB:

- Trying to discover a TB
- When sending the log there is an error message "Logging from c:geo cannot be anonymous...".

I guess the user did not even touch the GK-settings and his action does not involve GKs.
Will try to reproduce later.

**Comment by kumy** [comment]
I'll try to reproduce here.

**Comment by kumy** [comment]
Verified.
I'll dig into the problem.

**Comment by kumy** [comment]
PR #4791

**Comment by Lineflyer** [comment]
Confirmed working (tested some TB discover logs) with 2015.03.30-NB
