### ISSUE TITLE
String for "log_post_not_possible" is weird

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4790]
In the context of ̀`LogTrackableActivity`, the text "Loading Log Page…" doesn't fit well.
I've got the message displayed when trying to log a TB while not connected to the GC service.

Something like "Logging is not possible…" would fit better in the context.

This string is also used in `LogCacheActivity`.

I propose to:
* Create a new string for the `LogCacheActivity`, saying "Loading Log Page…"
* Change the text to "Logging is not possible…" for the `LogTrackableActivity` (which fit better to the string name)

**Comment by Lineflyer** [comment]
Yes, we had this dicussion in the past. Good idea to clean this up.
I would rather suggest something like "Loading data..." or "Please wait..." for both activities.

**Comment by Lineflyer** [comment]
AFAIK we changed the dialogues here and on one hand replaced the progress dialog by a progress spinner in the actionbar. On the other hand if the user tries to send the log while the background loading is still running an improved text is shown.
