### ISSUE TITLE
Crash using new Hint Option on go to coordinates

### ISSUE THREAD

**Issue by MarcusMaximi** [cgeo/cgeo#4801]
When not actually viewing a geocache but simply selecting coordinates from the history list in the goto destination (bottom middle icon on cgeo home screen) you still have the new hint option at the top of the screen (even though there obviously isn't a hint)

selecting this crashes cgeo - unfortauntely c:geo has stopped

**Comment by rsudev** [comment]
Thanks for the report, will take a look.

**Comment by Bananeweizen** [comment]
Shouldn't this go to release instead?

**Comment by Bananeweizen** [comment]
Sorry, this was on release, but the github UI shows only the master related changes in the notifications, as it seems.
