### ISSUE TITLE
Geocache with Trackables can not be loaded or updated

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#4803]
I cannot open any cache containing a Travelbug or Geocoin except if it is stored offline.
I just get a error message saying "c:geo can't find that geocache"
If I open an offline Geocache that has TBs, I cannot view the Trackables Tab or Update the cache.

Examples of caches that are affected:
http://coord.info/GC500Q5
http://coord.info/GC25QD6
http://coord.info/GC422Q5

Using version 2015.03.30-NB-052sc9a on a Nexus 5

**Comment by Lineflyer** [comment]
@MrYaz 
Thanks for the report.
Before investing more time in debugging this, can you please retest this with the freshly made 2015.03.30-NB1 ?

**Comment by fohlsso2** [comment]
ah.
I was struggling with the exact same issue, but I did not associate it to trackables, I could not understand why two caches published at the same time and only one of them would load in c:geo.

First noticed it 
regards/F

**Comment by fohlsso2** [comment]
Tested 2015.03.30-NB1 and it seems to be ok with the first three caches i tried.

**Comment by Lineflyer** [comment]
We are currently changing a lot with respect to trackables (implementing geokrety support).
So I guess this has been fixed by todays corrections.
If you notice problems again do not hesitate to open another issue (or reopen this one if the problem is not solved).

**Comment by MrYaz** [comment]
It works fine with 2015.03.30-NB1 for me as well.
