### ISSUE TITLE
GK description truncated (geokretymap.org)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4804]
2015.03.30-NB:

- Enable Geokrety and cached loading from geokretymap.org
- Open GKC240
- The trackable description is shown as `Bitte ignorieren.` which is truncated.

The xml result of geokretymap.org contains the complete description:
```
<description>
Dieser Geokret dient zum Testen von c:geo.<br />
Er befindet sich nicht wirklich im gelisteten Cache. <br />
<br />
Bitte ignorieren.
</description>

**Comment by kumy** [comment]
Hum, the xmlparse see only the last line...

For reference: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/connector/trackable/GeokretyParser.java#L123

**Comment by kumy** [comment]
PR #4807

**Comment by Lineflyer** [comment]
Tested and working with 2015.04.07-NB.
