### ISSUE TITLE
Login failed on main screen

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#4809]
Login failed on main screen but all feature working fine. 
![screenshot_2015-03-31-02-03-02]
(https://cloud.githubusercontent.com/assets/8573382/6909822/a0525d3e-d74a-11e4-9464-f83ef128a5af.png)
In settings login shows up as OK
![screenshot_2015-03-31-02-03-26](https://cloud.githubusercontent.com/assets/8573382/6909841/e6079f6a-d74a-11e4-9253-87e07462bd49.png)
Strange behavior, but all is working so bug is not important 😉

--- System information ---
Device: LG-D802 (g2_open_com, lge)
Android version: 4.4.2
Android build: KOT49I.D80220h
Cgeo version: 2015.03.31-NB-d137393
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: false
Map strategy: detailed
HW-acceleration: enabled (default state)
geocaching.com: not logged in (Login failed)
System language: pl_PL (cgeo forced to English)
Installed cgeo plugins: none
--- End of system information ---

**Comment by richlp** [comment]
Having the same problem, wife hasn't done latest update and is not.

**Comment by Itsjoma** [comment]
I'm having same issue. In settings it says I'm logged in. Home screen says login failed.  Can't send logs. Liked in playtime for update .. none since last on 3/28 which I have.
