### ISSUE TITLE
Parser only tests in cron job

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4810]
I suggest that we create a very small test suite of existing or new tests, which are only related to the parsing of the website. This test suite can then be scheduled to run every 30 minutes in a new job on Jenkins. That way we would get a much better overview of the times where the website is down or has changed the output again. So we can eventually react even more timely than now.

**Comment by samueltardieu** [comment]
Seconded.

**Comment by Lineflyer** [comment]
AFAIK this has been implemented on CI already (Jobs: `Website tests master` and `website tests release`)

**Comment by Bananeweizen** [comment]
The website tests only check whether the homepage of the different geocaching sites are available. Parsing real data is not tested yet.
