### ISSUE TITLE
Consistent naming of GeoKret/GeoKrety

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4811]
When looking at the website www.geokrety.org I do see, that the names are used like:
`GeoKret` for one of the trackables
`GeoKrety`for the service itself

The current strings do not always follow that:
- We are mostly missing the capital letter `K`
- I am not sure if we refer to a `GeoKret` when speaking of a GK trackable. AFAIR I did see something like `Geokrety not found` or similar.

This is not really important but still a thing which should be made consistent before the feature is release and before too much translations have been returned (which need to be translated again).

@kumy: Can you provide a PR making this consistent? You probably know GK best and for what purpose the separate strings are used.

**Comment by kumy** [comment]
You're right.
I've also seen `GeoKret` for singular and  `GeoKrety` for plural.

I'll do this evening. :)

**Comment by kumy** [comment]
PR #4814
