### ISSUE TITLE
Clarify status of askForConfirmation parameter

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4817]
In `CacheListActivity#removeList`, the parameter `askForConfirmation` is always false (at the only point of call).

However, the logic in the method seems dubious, as the first test should likely be a `||`, not a `&&`. Here, we always ask for confirmation if the list is not empty, in spite of `askForConfirmation` being false.

Preventively assigning to @Bananeweizen as the editor of the surrounding code.

**Comment by Bananeweizen** [comment]
has been refactored with introduction of undo operations, therefore closing
