### ISSUE TITLE
Support SSL for GK connection when possible.

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4823]
GeoKrety.org provides SSL support, but they're certificate is self signed.. :/
Should I try to 'auto-accept' the "bad" certificate, or continue to not use SSL?
GeKretyMap.org provides SSL, but our current Network library doesn't support SNI (#4991).

Note: Already discussed on #4778

To sum up.
@rsudev: I would definitely vote for trying to use SSL, because even with a self-signed certificate we get encryption.
@samueltardieu: only if it doesn't make us accept any certificate, because we check the certificate for a number of sites already (extremcaching.com, geocaching.com, open.mapquestapi.com) and I would not want to allow MITM for those.

- [x] GeoKrety.org
- [ ] GeoKretyMap.org

**Comment by kumy** [comment]
Need #4991 for that

**Comment by kumy** [comment]
Nice, geokrety.org just started to use letsencrypt.org

**Comment by kumy** [comment]
@Lineflyer may you please be vigilant, with this merge (in master). It works fine for me, but I can only test on Android 6.0.1. Thanks

**Comment by samueltardieu** [comment]
kumy: did you forget to create a PR?

**Comment by kumy** [comment]
@samueltardieu I've followed the procedure at https://github.com/cgeo/cgeo/wiki/How-to-get-a-bug-fix-into-the-release#procedure-for-direct-committers-who-want-to-work-directly-into-the-main-repository
I've created a branch and pushed it on upstream https://github.com/cgeo/cgeo/tree/issue-4823
Then merged into master and push.
Sorry, what am I doing wrong?

I was about doing the same for #5332.
Please advise.

**Comment by SammysHP** [comment]
IMHO it's enough to have this in master. Not really a bug fix.

**Comment by samueltardieu** [comment]
@kumy I hadn't realized you merged it in master already. Of course, when a change is intended for master only, you don't need to follow the procedure for bug fixes.

**Comment by Lineflyer** [comment]
@kumy Thanks for the heads up. As I normally use the current master (NB) and do have some test GK I will test this implicitly in any case. 
If time permits I will do some explicit testing like initial Auth to GK, etc.

Assigning myself for fieldtest then.

**Comment by Lineflyer** [comment]
2016.02.22-NB: Normal GK operations like posting logs, retrieve, drop do work normal.
Will keep this open for explicit testing of Auth, etc. as mentioned above.
