### ISSUE TITLE
Be more explicit in system information when no connectors are active

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4824]
The absence of any active connector shows in the system information by not showing anything. It should be more explicit and says that no connector has been enabled.

**Comment by samueltardieu** [comment]
@Lineflyer Tell me if you want this in `release` or not.

**Comment by Lineflyer** [comment]
Its perfect (Tested in 2015.04.02-NB), if you consider the risk low (I think so) feel free to put it into release.

**Comment by samueltardieu** [comment]
Done.
