### ISSUE TITLE
c:geo crashes when loading an event following update

### ISSUE THREAD

**Issue by yellowduck** [cgeo/cgeo#4826]
Since the website changes, the app crashes each time I try to load an event cache. This happens through pocket queries and also via email notification links.

**Comment by SammysHP** [comment]
Cannot reproduce. Please post the information from *Menu → About c:geo → System*.

**Comment by Lineflyer** [comment]
And please post the GC code of the event which causes this.

**Comment by yellowduck** [comment]
Nightly 30.03
GC5Q0CG
Unfortunately, c:geo has stopped.

The comment on Facebook where they mention a link failing to load is also an event cache.
UK date/time settings.

**Comment by Lineflyer** [comment]
Please udpate to the newest nightly.
The mentioned nightly version could have had problems opening a cache with trackables.

**Comment by rsudev** [comment]
The mentioned cache does not contain any trackables...
Regardless, I couldn't reproduce either.
The date/time settings you mention - is this the website or your device?

**Comment by yellowduck** [comment]
With the latest nightly, event caches now load.

Just for the record, this issue occurred with the new version shortly after the website update, and was present in at least two nightly versions. 

This issue can be closed. Many thanks.
