### ISSUE TITLE
Navigation with Sygic no longer working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4827]
From support mail and confirmed by a test with 2015.03.30-NB:

- Open a cache
- Select Navigate -> Sygic
- Sygic will open but no navigation action is started

According to users info it was working before and stopped with the recent feature release 2015.03.28.

**Comment by Lineflyer** [comment]
Referer to #956 for the initial implementation and infos about the needed intent.

**Comment by miloshavlicek** [comment]
(y)

**Comment by miloshavlicek** [comment]
:+1:

**Comment by rsudev** [comment]
Currently I cannot see any change in the code that could explain this (can't test it myself, don't have Sygic).
Would it be possible to verify that it still works for the same cache with the previous version on the same device?
Could you check with intent spy whether the intent changed between versions?

**Comment by kumy** [comment]
The [documentation](http://developers.sygic.com/documentation.php?action=customurl_android) describes 3 types of navigation:
* 'show' (actual)
* 'drive'
* 'walk'

I've checked code around, and it's easy to split the actual menu entry to "Sygic (drive)" and "Sygic (walk)" like it's done for "Navigation (XXX)".

Code is ready, I can merge it if wanted.

**Comment by Bananeweizen** [comment]
Splitting sounds okay to me. Users can still remove navigation entries, if they find them not so useful.

**Comment by kumy** [comment]
I thought once I was in bed, that I this fix should have been committed on the release branch as we're in phase of releasing.
Do I have to cherry-pick this commit?

@Bananeweizen should the "split Sygic" be committed also in release branch?

**Comment by Lineflyer** [comment]
We are planning to relase master anyway. So I would keep it on master to avoid additional work.

Regarding the split:
Maybe we should use an approach with a submenu (first Sygic, then select Walk, Drive, Bike) if technically possible as we will get quite a lot of menu items otherwise which makes it confusing.

**Comment by Bananeweizen** [comment]
There are no nested sub menus in Android. I.e. you have 2 levels max, which are 1. Navigate, 2. Sygic (or whatever).

**Comment by kumy** [comment]
@Bananeweizen if I understand code correctly, "Navigate" launch an `AlertDialog`, not a menu?
So it could be possible to implement something there, and for example display items in an `SimpleExpandableListAdapter` like for the filters in `CachelistActivity`.

**Comment by kumy** [comment]
And thanks for for the "no nested sub menus in Android." tip ;)

**Comment by Lineflyer** [comment]
Assigning for Test

**Comment by Lineflyer** [comment]
Tested and working with 2015.05.26-NB-f67a78d  (Driving and Walking) with Sygic version 15.1.5 (loaded from PlayStore on 30.04.2015).
