### ISSUE TITLE
list nearby-caches without premium-caches

### ISSUE THREAD

**Issue by t-m-z** [cgeo/cgeo#4830]
At the Moment the nearby-cache-list lists all Caches, also the premium-caches.
I suggest to implement a checkbox Werner to include premium&Caches vor not.

**Comment by SammysHP** [comment]
AFAIK you can sort and/or filter PMO caches. But we include them because

a) we don't always know whether it is a PMO cache or not and
b) you can still log it via the context menu as a basic member.

**Comment by t-m-z** [comment]
Hi,
Thank you for the quick reply. But AFAIK it is not possible to filter PMO - I did not found this feature.
However, most oft my nearby-caches are PMO and this is disturbing.
Becauae the description says "for premium members only" I think it is possible to filter them.

kind regards
Thomas


-----Original Message-----

**Comment by rsudev** [comment]
Technically we cannot filter them on the server side, this option is not offered by the website (on the search function we use).
You can already filter them 'after the fact' by using Filter - Status - All Member Access.

**Comment by t-m-z** [comment]
Thank you for this quick reply. Unfortunately I was not aware of this filter.
Hence my request can be closed.
I apologize for this discussion.

Kind regards
Thomas


-----Original Message-----
