### ISSUE TITLE
Write note for GC trackable no longer possible without tracking code

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4833]
2015.04.03-NB

- Open any GC trackable (for me it was a TB listed in a cache and I opened it from the inventory)
- Select log type NOTE
- Enter log text
- Try to send the log

Result:
Toast is displayed, that the tracking code is missing.

It seems the tracking code is needed for GKs but it is not needed for GC TB (and was working without before implmentation of GK support)

**Comment by kumy** [comment]
PR #4837 should fix the issue.
