### ISSUE TITLE
Filter lost after opening cache details

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#4834]
Hi,

Steps to reproduce:
- open stored caches list
- apply a filter (in my case Status > With trackable)
- open a cache to display the cache details
- when going back from cache details to the list of caches ... the filter is gone (ie all caches are displayed).

It seems to be a regression link to the introduction of the new "categorized filters".

best regards,

**Comment by Lineflyer** [comment]
This sounds familiar.Pretty sure it is a duplicate but can not find it on my mobile view right now.

**Comment by ldmpub** [comment]
Before opening this one, I have checked / searched wihtout success in "opened issues".

**Comment by Lineflyer** [comment]
It was mentioned in #3140 which originally described another problem.
I closed #3140 as the problem seems solved.

@ldmpub 
I can also not reproduce your issue with 2015.04.07-NB.
Which version are you using? 
Is the problem reproducible for you?

**Comment by ldmpub** [comment]
Hi,

Bug is still there in 2014-04-11-NB.
I can reproduce the "loose of filter" when from a filtered list I enter in cache details then I go back to the list (which is not filtered anymore).

This occurs on lists: Nearby / List caches from map
When I use the filtrer Status -> With Trackable.

Hope this helps to reproduce,

PS : It's funny how often developpers are not able to reproduce a bug or how users are not able to explain clearly steps to reproduce a bug ;-)

**Comment by ldmpub** [comment]
Hi again,

I have made a brief screen cast showing: 
1. cgeo version
2. list without filter
3. apply filter
4. show cache details
5. back to list => filter lost.

https://www.dropbox.com/s/7gliqnyv5vpry4c/cgeo_bug_with_filters_in_lists%20-%20After%20rotate.mp4?dl=0

**Comment by kumy** [comment]
With the operations from the video, I m not able to reproduce too on current master.

**Comment by Lineflyer** [comment]
Interesting. I also tried as shown in the video and cant reproduce (also tested as a basic member as for @ldmpub who is a basic member).

Question to @ldmpub 
Does this happen on a list of saved caches as well?
For the nearby search: Is any of the caches returned by that search already savd onto your device?

Please post the complete system information shown in About c:geo - System

**Comment by ldmpub** [comment]
Hello,

Lost of filter seams to occurs in all the lists.
Yes nearby search contains saved caches.

cgeo info attached.
[screenshot cgeo info](https://cloud.githubusercontent.com/assets/1452146/7131153/aee766e6-e27b-11e4-819e-308c22f82f2d.png)

**Comment by kumy** [comment]
I'm still unable to reproduce.

@ldmpub did you test on a clean install?

**Comment by ldmpub** [comment]
Hi,

Sorry but the bug is still there for me ;-(.
Tested on 2 devices : Smartphone + Tablet, both running Android 4.4.

I have removed the app and made "fresh install" from Google Play Store or the last nightly build => the bug is still there.

How can I remove all the "datas" ie what are the cgeo folders I can deleted to be sure to perform a 100% fresh install?

Notice: I use alternativly 2 gc.com users.

**Comment by kumy** [comment]
Looked at the involved code, and can't find what could be wrong.

@ldmpub Could you build the app by yourself?
Maybe we could 'git bisect' to get clues...

**Comment by ldmpub** [comment]
I'm sorry ;-( but even if I'm working in computer science; I'm not a developper.

I once installed all google packages to build the test apk "hello world" with success; my experience was basic and at that time Eclipse was still used as IDE (now Google recommands IntelliJ IDEA!).

**Comment by kumy** [comment]
I was able to get something similar:

* open a stored list
* filter
* long press on a cache
* choose `refresh` item in the menu

Once the cache is reloaded, filter is lost.
However, clicking a cache then back, the filter is re-applied

**Comment by kumy** [comment]
I've found a fix for the case I described.
With luck it could fix your case, but I will not bet on it...

**Comment by ldmpub** [comment]
No pb, I will try the next nightly build and let you know (if I'm the only one who's suffering this issue ... it's not that important).

**Comment by kumy** [comment]
I've missing the NB by 20min... hope someone could launch a new build tomorrow so we can test it "soon" ;)

**Comment by kumy** [comment]
@ldmpub If you're still around... I've found how to launch a new build. It should be ready soon.

**Comment by kumy** [comment]
@ldmpub could you test with [2015.05.23-NB1-1b4ff80](http://www.cgeo.org/c-geo-nightly.apk).
thanks

**Comment by ldmpub** [comment]
Hi,

New NB installed. I have noticed that my "stored" caches have vanished so I have stored new one to reproduce.

Unfortunatly the bug is still there for me:
1. open stored list
2. apply filter
3. open any cache details
4. back to list => filter lost.

I have applied different "filter types" (size, with TB, ...) it's always reproductible on my side.

From a user point of view it's similar to your scenario but ... I don't nedd to perform the "cache refresh" step.

Good luck if you have time to investigate further ;-).

**Comment by rsudev** [comment]
I can reproduce this issue if I activate a setting in developer options, to not keep activities in memory. When I then come back from the cache details, the filter is no longer present, as we do not store the filter state when the activity is stopped.
I have no idea why this should happen so consistently for you, but could be an explanation and is IMO anyway a gap in our implementation.

**Comment by kumy** [comment]
Ok the same here.
@ldmpub do you have this option enabled in your system preferences?

**Comment by ldmpub** [comment]
Waouh ... You've got it!
This option is enabled on my devices. I desactivated it and reboot Android => everything is working fine now.

**Comment by kumy** [comment]
@rsudev congrats!!!
What should we do now?
Do we try to store the filter somewhere in a stronger manner?

**Comment by rsudev** [comment]
IMO the pressure to solve this soon is somewhat relaxed. Nevertheless should we correctly serialize filter (and other activity) state in onSaveInstanceState. We do this already in some other activities, but not here.

**Comment by kumy** [comment]
So we could unset this issue for next Feature release?

(This is the direction I've stated to looked at ;))

**Comment by rsudev** [comment]
Sure. I also adjusted the labels accordingly.

**Comment by ldmpub** [comment]
Thank to all devs for the great job!

**Comment by kumy** [comment]
Should be ok with and without the system setting :)

**Comment by kumy** [comment]
* OriginFilter
* DistanceFilter

doesn't serialize correctly

**Comment by kumy** [comment]
Added 2 more commits 1c47dfe ce8b30c
Feel free to revert if necessary.

**Comment by kumy** [comment]
Arghh!
11 new FindBugs warnings...

**Comment by kumy** [comment]
I really don't like updating so many files, but seems necessary...
6d82792

**Comment by Lineflyer** [comment]
Assigning for Test

**Comment by Lineflyer** [comment]
Tested and working with 2015.05.26-NB

**Comment by ldmpub** [comment]
Hi devs,

The fix works perfectly for "stored cache list" which was my initial report ... but ;-( ... I have noticed a strange behaviour when I use filter in other lists.

For instance:
1. Nearby caches
2. Add a filter
3. Open a cache to see details
4. go back => there a "partial list" of previous filtered caches is displayed. It looks like the filter is still there but not on the same list of caches. I was expecting that the "full filtered list of cache" was stored then restored. Am I wrong?

If my explainations are not clear enough I could post a new video.

PS: of course these tests have be done with developer options > Don't keep activities in memory set to ON.

**Comment by kumy** [comment]
Even if I cannot reproduce it, I think it's similar to #4969, and PR #4983 may fix it.

**Comment by Lineflyer** [comment]
I agree.

@ldmpub 
Please kindly retest your scenario after PR#4983 is merged (might take some days) and open a new issue if it is not solved by this.
