### ISSUE TITLE
Copy coords from waypoints

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#4836]
It is possible to paste coords to wayponts. See #3799
But there is no way afaik to copy cords FROM waypoints. 
I find a need for this very often when I want to share coordinates with friends on the fly.
One possible implementation of this might be to add a "Copy coords" option to the long-press menu of a waypoint.
Another would be a "Share coords" option that presents a list of possible Share providers like on the Share Cache option.

**Comment by Lineflyer** [comment]
Assigning for Test

**Comment by Lineflyer** [comment]
Tested copy from waypoints and paste into new waypoint + paste into plain text field with 2015.05.26-NB.
