### ISSUE TITLE
remove nesting of map settings menu

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4843]
We have the map settings in an submenu (probably because the main menu was historically limited to 6 items). With the action bar this is no longer necessary, so the sub menu items should be added directly in the top level menu.

**Comment by konpapa** [comment]
I know this might not be a new issue, but I thought I'd give it a try. Please check this if you'd like and give me a feedback. Here's a screenshot.
![map](https://cloud.githubusercontent.com/assets/6809229/8021778/bedd6e14-0cb6-11e5-9452-124dd8589804.JPG)

**Comment by Lineflyer** [comment]
@konpapa IMHO there are some items missing in your preview (e.g. Strategy menu, Map themes menu)?

**Comment by Lineflyer** [comment]
Given the amount of entries in the menus below the map on the actionbar I consider it reasonable to keep the current structure of items and submenus. If I have overlooked an essential point here, feel free to reopen.
