### ISSUE TITLE
wrong find count when logging something else than found

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4844]
From facebook:
I like c:geo a lot, but why does it (usually temporarily) count a NM log or a note as a find?
Hi. It's strange, it's only a short term thing, but it increases the number of finds on the front page by one. It usually rectifies after logging out and in a couple of times. It obviously doesn't register on the gc.com site, as the count remains correct on there. Thanks for a great app though, and thanks for looking at a very minor niggle!

Actually, we increase the find count on logging, independent of the type of the actual log. See GCParser 1176.

**Comment by Lineflyer** [comment]
This is already listed in an old issue AFAIR. So this could be closed as well if someone finds it.

**Comment by Bananeweizen** [comment]
I only remember something about the number being 1 to high in a specific template or the signature under certain circumstances.
