### ISSUE TITLE
Position jump on live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4845]
2015.04.04-NB

Live map active
Put phone on standby
Switch phone on again

After a few seconds the GPS is fixed and my position and the uncertainty circle shows up again, but it is sometimes up to approx. 50-100 meter wrong...far outside the shown uncertainty.
After about 7-10 seconds it suddenly jumps to the correct position.

Google services active
Energy saving off

I described this already some months ago...have to look also for the old issue to get a clue.

Not clearly reproducible.

**Comment by basti2k** [comment]
The same thing happens with me also, but it is because the GPS receiver turns off with the off the display.
If the display is activated again, this also remains off until you unlock the phone again.
I can live with this, because the GPS receiver does not work even when the display is off.

**Comment by Lineflyer** [comment]
@basti2k
 I know about this switch off and the uncertainty of the position before the GPS fix is derived again. But in fact, for me the wrong position continued for 7-10 seconds also after a GPS fix is available. I used the Samsung Multi window feature (c:geo with another location app) to see that the position shown in c:geo for this 7-10 seconds is simply wrong and the other app does it right (i.e. it jumps to the correct position directly after GPS fix is aquired).
Can you take a look if you can confirm that as well?

**Comment by Lineflyer** [comment]
Unable to reproduce. This might be depending on certain environment conditions which seems to trigger a wrong positioning with GooglePlayServices in c:geo.
Will keep it open as a reminder.

**Comment by Lineflyer** [comment]
I spent a little more time to get clues on this as it recently keeps happening to me (not only after standby but also while constantly using c:geo).

Here is what happens and what I figured out:
- While walking around having the live map active my position sporadically jumps to a position which is wrong by 100-500m (sometimes even worse) and stays like that for 5-10 seconds.
While the position is wrong the arrow still follows my position changes and rotation correctly (means: The arrow keeps moving and rotating as I do but at the wrong initial position).

The following shows a comparison (made with Samsung multi window feature) between c:geo and Locus Pro (c:geo with activated GooglePlayServices, Locus AFAIK does not use them) when the problem is happening:
![screenshot_2015-10-08-17-20-16](https://cloud.githubusercontent.com/assets/949669/10388578/8d71cff2-6e6b-11e5-8620-ded915058b84.png)
Locus shows my correct position, c:geo is wrong. GPS fix was obtained and acucracy excellent all the time.

Here is another example (same setup as above). This time c:geo reports less accuracy (bigger circle) than Locus which is not correct and shows me at a wrong position (even outside the uncertainty circle):
![screenshot_2015-10-08-18-03-33](https://cloud.githubusercontent.com/assets/949669/10388626/e984aefe-6e6b-11e5-940e-4c8b003bedaf.png)

As a next step I deactivated GooglePlayService usage in c:geo and spent a lot more time walking around at the coords where this happend. The result was, that without GooglePlayServices c:geo and Locus are show identical positions and accuracy all the time.

As a next step I activated GooglePlayServices in c:geo again and took GoogleMaps (which for sure also relies on GooglePlayServices) as a comparison.
The result is quite unambiguous (i.e.: Google Maps and c:geo show the same wrong position). I was walking on the street but not inside buildings.
![screenshot_2015-10-08-18-46-04](https://cloud.githubusercontent.com/assets/949669/10388689/55502f1e-6e6c-11e5-960f-dcf50a1eed0b.png)

So my conclusion would be:
GooglePlayServices are not working correctly on my device (or a general bug in the current GooglePlayServices version). @samueltardieu Would you agree?

GooglePlayServices: 8.1.15 (2250156-238)

System information:
--- System information ---
Device: GT-I9505 (jfltexx, samsung)
Android version: 5.0.1
Android build: LRX22C.I9505XXUHOH2
Cgeo version: 2015.10.08-NB-1b7237f
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
- opencaching.de: not logged in (Anmeldung…)
Installed cgeo plugins: calendar, contacts
--- End of system information ---

**Comment by samueltardieu** [comment]
Indeed, if Google Maps and cgeo both return the same wrong position, the bug is likely to lie inside Google Play services.

It would be interesting to turn WiFi off completely (i.e. does not allow its use for positionning). Maybe the jump is due to a temporary lack of GPS signal, which would fall back on network location for a very short time, that Locus would not use.

**Comment by Lineflyer** [comment]
I could not see any difference with/without Wifi allowed. However this is a bug outside of c:geo, so this is just for documentation,
