### ISSUE TITLE
Remove APK download from (old/current) website

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4849]
@mucek4 
Can you please remove the APK from the server and instead set the target for this hyperlink to 
https://github.com/cgeo/cgeo/releases/latest ?

We get quite some mails argueing about the outdated version on our homepage.

**Comment by SammysHP** [comment]
Or let us switch to the new website in the next few days.

**Comment by Lineflyer** [comment]
That would be even better.

**Comment by mucek4** [comment]
I have fixed the apk on webpage.
