### ISSUE TITLE
"Auto visit" not always working for GKs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4850]
2015.04.07-NB:

- Have TBs and GKs in your inventory
- Activate "AutoVisit" in Settings - Logging
- Open a saved cache
- Select "Log visit"
- On the logging view sometimes the GKs are set to `No Action` instead of `Visit`

This seems to depend on the time needed to load the inventory from GK.
I have seen that sometimes the AutoVisit also works for GKs, it seems to fail only if the answer from GK is coming in quite late.

**Comment by kumy** [comment]
Interresting. I'll look later.

**Comment by kumy** [comment]
Confirmed
