### ISSUE TITLE
Log type field to small when logging a GK

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4852]
I attended an opencaching event today and presented the upcoming GK feature.
While the feature is considered as really great from the audience some of them suggested to have a better logging view.
Due to the fact, that there is a new field for the time in the first row, the log type field became rather small, so that only a few letters are visisble.
The proposal was to somehow rearrange the view to give more room for the log type.

I currently do not have any great idea how this could look like.
Maybe we can move the date and time to a separate row below the log type?

**Comment by kumy** [comment]
If having log type field and date on separate lines when logging TB. This should not be a problem.

What do others think?

**Comment by kumy** [comment]
![device-2015-04-09-194558](https://cloud.githubusercontent.com/assets/176794/7073355/2415578e-def3-11e4-965b-44bd3d80cffe.png)
![device-2015-04-09-195951](https://cloud.githubusercontent.com/assets/176794/7073356/2417bb3c-def3-11e4-8b1b-ac8655efe4f0.png)

**Comment by Lineflyer** [comment]
Yes, why not. It looks good to me and that screen has enough space.

By the way:
Is this title new `Touch:...` or did I just not recognize it up to now?

**Comment by Lineflyer** [comment]
One addition:
For reaons of symmetry I would set the same size for the two boxes on the second and third line

**Comment by kumy** [comment]
@Lineflyer `Touch:` wasn't set by me.
I've looked quickly at the symmetry, but it seems to come from the `style`. It should be used everywhere. I don't wan't to break things... :/

**Comment by kumy** [comment]
All boxes have weight of 1

**Comment by Lineflyer** [comment]
Fine for me, never change working things.

**Comment by kumy** [comment]
PR #4864
