### ISSUE TITLE
Do not show GK owner as "Unknown" when no information is present

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4853]
I attended an opencaching event today and presented the upcoming GK feature.

Users have been wondering why we show the "Unknown" in the owner field of a GK.
AFAIK we don't get the information via the API, but "Unknown" was misunderstood by users.

Can't we just ommit the field completely as long as this function is not implemented?

**Comment by kumy** [comment]
IIRC, this is the case if you don't use the GKM "proxy".

I have some code never pushed (thanks to @samueltardieu for notify this on https://github.com/cgeo/cgeo/commit/ae4f135905cdf15787ca8a334e3eb6a5c2cdd0d0#commitcomment-10531438)..

In the pending PR, if the username is the user id (which is the response from GK), the field is filed with "userid: " + owner

Would this help? Should the username be hidden completely in this case?

**Comment by kumy** [comment]
@Lineflyer, would PR#4857 do the job?

![device-2015-04-08-194216](https://cloud.githubusercontent.com/assets/176794/7051387/4ec239d2-de28-11e4-9c19-5b93eaf1f909.png)
