### ISSUE TITLE
Direct users to settings if they try to log a GK without login

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4854]
I attended an opencaching event today and presented the upcoming GK feature.
A big challenge for many users was, that they did not know what to do when they tried to log a GK for the first time and ended up in the info window telling that anonymous logging is not possible.

Instead of having just OK as an option we should have a second button to open the geokrety settings directly in that info window.

Furthermore we should slightly adapt the text not only to say "Please register" but "Please register or login with your existing account from geokrety.org".

**Comment by kumy** [comment]
This is already implemented in PR#4846

**Comment by kumy** [comment]
Should now be fixed with #4846

**Comment by Lineflyer** [comment]
Will test

**Comment by Lineflyer** [comment]
Let me reopen this:

After testing in 2015.04.10-NB I think the new implementation goes into the right direction.
However I would recommend not to jump automatically into the settings and only show a small toast with the reason for that, but first show a window with the "Anonymous logging is not..." and have two button with "Cancel" and "Open Settings":
Doing so the user has time to understand the message and decide whether he wants to activate or not.

**Comment by kumy** [comment]
No problem

**Comment by kumy** [comment]
@Lineflyer, what about that?
any concerns about the messages?

![device-2015-04-10-183323](https://cloud.githubusercontent.com/assets/176794/7092260/74f656ae-dfb0-11e4-8943-032fcc8e7f38.png)

**Comment by Lineflyer** [comment]
Looks good IMHO.
Regarding the string I would suggest:
"Logging GeoKrets from c:geo cannot be done anonymously. Do you want to open the settings to fill in your credentials from GeoKrety.org?"
