### ISSUE TITLE
Improve design of compass button

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4855]
The "visual compass state" added in 4723c5ad2366e996861bfcab162a7e4fcfcdc6ec should help the user distinguish between "compass mode" and "GPS only mode".

At this stage, the design is very basic, and the strings that have been reused (`@string/attribute_compass_yes` and `@string/attribute_compass_no`) are not appropriate and are ambiguous in some languages.

The design should be improved if needed, and new strings should be defined and used.

**Comment by Lineflyer** [comment]
Did not see this one. Lets continue in #4862 as I just opened a PR for that (but using the existing strings with new wording).

**Comment by Lineflyer** [comment]
Reopening for the design

**Comment by Lineflyer** [comment]
Despite the fact that the whole compass might need a redesign (other issue) the design of this button is OK for me as an interim solution.
I am however no expert in android design guidelines...

**Comment by Lineflyer** [comment]
There is another issue regarding rework of the compete compass view.
