### ISSUE TITLE
error when using support library v21

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4860]
I've downgraded again after using support lib v21 for a short test. We are hit by this directly on start of the app: https://code.google.com/p/android/issues/detail?id=81215

I have no idea what that is related to, so I didn't see any way to fix this. If someone is more friends with the theme stuff, maybe you can find a workaround.

**Comment by rsudev** [comment]
Seemingly does v22.1 not have this issue any more. (see discussion in #4903). Closing.
