### ISSUE TITLE
Search bar should close properly on back key (Android 5.0+)

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#4861]
I open a new issue instead of commenting on the closed issue #4725. Is this the right way to do it?

I think that the fix by @Bananeweizen did only solve half of the problem though.
The behavior is still illogical when trying to deselect the search bar by pressing the back key.

When you first press the search bar, the last shown caches are shown in the dropdown and the keyboard is shown, allowing you to enter a search query.
![image](https://cloud.githubusercontent.com/assets/1811963/7057541/eef501d6-de56-11e4-9ae8-86bf3ce3ddb6.png)

When you select a cache from the list the search bar gets deselected in the correct way. Showing the default controls in the action bar next time you come back to the home page. Perfect!

But when you press the back button instead, the first state is like the below screenshot, This step is unnecessary since you cannot enter anything in the search field anyway when the keyboard is hidden 
![image](https://cloud.githubusercontent.com/assets/1811963/7057634/05960f6a-de58-11e4-9777-2e05f1e50bbb.png)

When you press the back button a second time this action bar is shown:
![image](https://cloud.githubusercontent.com/assets/1811963/7057680/7c98b72a-de58-11e4-8467-bbba12af1772.png)

...instead of the default action bar setup below that should be shown instead:
![image](https://cloud.githubusercontent.com/assets/1811963/7057693/a8ae8ab0-de58-11e4-9fbc-fa44a36254ce.png)

So my suggestion is that you should only have to press the back button once to deselect the search field.

**Comment by Hauwertlhaufn** [comment]
When you press the back button, while the search bar is selected and the keyboard is shown, Android just hides the keyboard. Thats normal. (Its better to understand, when you own a Nexus, where the back button gets into a "down" button while the keyboard is shown.) So I don't know, if it is fixable, or a "Android-problem".

**Comment by MrYaz** [comment]
You are right @Hauwertlhaufn!
It is the same behavior in Facebook, iMdb and Spotify app's search functions as well.
Very strange behavior IMHO.

But it still should return to the default action bar instead of the one above without the "c:geo" title and History icon.

**Comment by Lineflyer** [comment]
@MrYaz 
Interesting. I have never seen this status like shown in your second last screenshot. For me the search field stays open as in your second screenshot.

**Comment by MrYaz** [comment]
@Lineflyer
Even if you press the back button a second time?

**Comment by Lineflyer** [comment]
Yes:

First back = Hides keyboard and list of recent caches shown
Second back= Search closed, normal menu shown

2015.04.10-NB

**Comment by MrYaz** [comment]
This is a screen recording of my device
A Nexus 5, Lollipop 5.1
https://www.dropbox.com/s/e5hcnljuji230re/search_field_back_button.mp4?dl=0

**Comment by Lineflyer** [comment]
@MrYaz 
By chance I updated my Galaxy S4 from 4.4.4 to 5.0.1 this weekend and now I can reproduce the behavior as you described it.
Seems to be limited to Android 5.0+ then.
