### ISSUE TITLE
Wrong strings used in new magnetic compass button

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4862]
Looking at 4723c5ad2366e996861bfcab162a7e4fcfcdc6ec wrong strings seem to be used for the new button.
We misuse the stings `attribute_compass_yes` and `attribute_compass_no`which are intended for the text form of cache attributes.
I just changed them to match the new function not recognizing, that they are used also in other places.
I will revert that commit in a minute.

We should either use the original strings `use_gps` and `use_compass` or create new strings for this button.

**Comment by samueltardieu** [comment]
Isn't that a duplicate of #4855? You should close one or the other.

**Comment by Lineflyer** [comment]
You are right, I did not see the one you recently opened. Lets continue here as I just opened a PR referencing this issue (but using the existing strings with new wording...that should trigger a retranslation on crowdin as well AFAIR).

**Comment by Lineflyer** [comment]
Autoclose did not work. PR is merged.
