### ISSUE TITLE
Show logbook of GK trackable

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4865]
Of course this feature request was mentioned by OC-users looking at the new Geokret functionality:

The logbook of GK trackables should be loaded as well (like for GC trackables).
I don't know whether the API supports that currently, so I just want to file that as a Feature Request here.

**Comment by kumy** [comment]
Unfortunately, the upstream doesn't provides this with the day to day API.
But, GKM synchronise db with another method once a day, and get _last_ moves (no log messages).
That could be presented to the user from GKM.

**Comment by Lineflyer** [comment]
Last moves without log message is only a "half" solution IMHO.
Maybe this should go onto the pile of API improvements for GK. No need to hurry here.

**Comment by kumy** [comment]
@filipsPL if you have time could you please implement this feature in GeoKrety API?
