### ISSUE TITLE
GPS off mode should be tied to "Use Low power" in TB activity

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4870]
as it has been done recently in 944f4e59b750786a916e77f1a3754249aa2a983a for the CacheDetailActivity.

See #4575

**Comment by samueltardieu** [comment]
Please test and advise.

**Comment by Lineflyer** [comment]
Tested with 2015.04.12-NB and working.
Still (as for the other commit) I think it should stay on master only.to give more time for testing.

**Comment by Lineflyer** [comment]
Reassigned to @samueltardieu as he might want to delete the issue branch
