### ISSUE TITLE
Allow upload of personal note to OC server

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4873]
This seems to be supported with the OKAPI and should be implemented identically to the gc.com feature:
http://www.opencaching.de/okapi/services/caches/save_personal_notes.html

**Comment by Natureshadow** [comment]
Issue #2930 asked for and implemented download of the personal note and the personal coordinates. This feature request compeltes this work. Please also make changing the personal coordinates work, as for GC.com.

**Comment by SammysHP** [comment]
> This feature request compeltes this work.

That's why we have this issue.

> Please also make changing the personal coordinates work, as for GC.com.

Do you mean upload of corrected coordinates? That is another issues.

**Comment by rsudev** [comment]
> Do you mean upload of corrected coordinates? That is another issues.
Which currently seems not to be supported by the OKAPI, unfortunately.

**Comment by madankumarbaskaran** [comment]
Can I work on this request (Upload of personal note to OC server)?

**Comment by SammysHP** [comment]
Sure!

**Comment by madankumarbaskaran** [comment]
For GC.com, personal notes are enabled for premium users. I believe for opencaching.de does not have basic or premium users, so upload should be enabled to all the users of opencaching.de? Please comment.

**Comment by SammysHP** [comment]
Yes.

**Comment by rsudev** [comment]
@madankumarbaskaran Furthermore does this not only affect opencaching.de, but all OKAPI-enabled sites which support the latest OKAPI version. IN the current code there are two levels of OKAPI-support defined, and the sites initialize the connector with the appropriate level. So for an implementation it is necessary to check:
* which sites currently support which version (resp. which feature-set, the exact version is not so relevant)
* how many support levels do we need in the future (are two still sufficient, because all 'current' sites also support the new feature) or do we need more
* report this through the capabilities in the connector and enable the upload button based on that only.

**Comment by madankumarbaskaran** [comment]
@rsudev two levels of OKAPI-support, do you mean authentication level for OKAPI?. I am beginner to Android and CGEO, please elaborate on the above requirement. Appreciate your help.

**Comment by rsudev** [comment]
@madankumarbaskaran Sorry for not coming back to you earlier (too much work right now). Authentication levels are one crucial ingredient (without level 3 authentication, you cannot upload personal notes), but what I was referring to was the OKAPI version that specific sites have deployed, which might differ in supported features (and the upload for personal notes is a relatively recent addition). The main site for OKAPI is opencaching.pl (see http://opencaching.pl/okapi/introduction.html) currently on revision 1076 (see upper entry in the navigation box). There you also have links to most of the other OKAPI sites, and when clicking through you can see, that only the US is trailing somewhat (being on rev 901). Missing from this list is the uk (http://www.opencaching.org.uk/okapi/introduction.html), which still is on rev 511.
Be sure to understand the basic interaction pattern for the OKAPI and how it is implemented inside c:geo (in OkapiClient.java), than you can add the extension for the upload there and wire it through from there to the connector.

**Comment by madankumarbaskaran** [comment]
@rsudev Appreciate your clear explanation. I implemented to upload the notes and tested on opencaching.de; it is working fine. But I could not find a solution to identify the opencaching sites which supports upload note feature. Should we need to hardcode to check for opencaching sites and show upload if it is .de,.pl and  hide if it is .us?  Please share your thought.

**Comment by rsudev** [comment]
@madankumarbaskaran Unfortunately I didn't have time to come back to you earlier. In a sense the capabilities of the opencaching sites are 'hardcoded', but only at initialization time.
In the ```ConnectorFactory``` you can observe the last parameter for the ```OCApiLiveConnector``` instances. It is either ```ApiSupport.oldapi``` or ```ApiSupport.current```. This setting is stored in the base class, and you can use it to drive the override for ```supportsPersonalNote``` from the ```IConnector``` interface to trigger the availability of the upload button.
BTW: opencaching.us updated to OKAPI 1076 in the meantime, so we still have the current grouping of 'oldapi' and 'current'.

**Comment by rsudev** [comment]
@madankumarbaskaran to answer you question from IRC:
- All sites which support the 'current' api should also support personal notes (AFAIK)
- in order to see how this is used, you can look at the watchlist feature

perhaps more tomorrow

**Comment by madankumarbaskaran** [comment]
Thanks rsudev. Got your point.

**Comment by madankumarbaskaran** [comment]
@rsudev Please review my PR.

**Comment by madankumarbaskaran** [comment]
@rsudev Updated as you suggested. I raised the new PR. Sorry for the confusion. Please advice for any changes.

**Comment by Lineflyer** [comment]
Implemented into `master` and tested and working in 205.07.21-NB.
@madankumarbaskaran Thanks for your contribution!
