### ISSUE TITLE
attachments (e.g. images) for caches

### ISSUE THREAD

**Issue by Slini11** [cgeo/cgeo#4880]
It would be great to attach data e.g. images to a cachelistings in c:geo. Locus owns this feature already and I think c:geo needs it too.

**Comment by samueltardieu** [comment]
Can you give us a cache geocode for which you don't get the images in cgeo?

**Comment by Slini11** [comment]
I search for a feature like the one on the photo. Or does it exist already?
![screenshot_2015-04-13-16-31-44](https://cloud.githubusercontent.com/assets/5831333/7117947/5868811c-e1fc-11e4-9f41-5ce21188f0d9.png)

**Comment by samueltardieu** [comment]
Oh, you mean attach data coming from the user, not from the cache owner?
No, we do not have that.

**Comment by Slini11** [comment]
But you have it perhaps in the future :) ?

**Comment by samueltardieu** [comment]
If someone implements this, maybe one day.

**Comment by SammysHP** [comment]
Wait – you can't upload these attachments, can you? So it's similar to "add note".

#817
#4486

**Comment by Lineflyer** [comment]
@Slini11 From which app is the screenshot you posted?

Apart from that I think your issue is covered by those of mentioned by @SammysHP, isn't it?

**Comment by samueltardieu** [comment]
@Lineflyer Locus

**Comment by Lineflyer** [comment]
This is similar to the issues mentioned by @SammysHP .
Please reopen if you disagree.
