### ISSUE TITLE
Heading line has wrong target when started from compass

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4884]
Somehow linked to #4684 but another scenario which I consider a bug:

2015.03.31:
- Open cache details of a saved cache with waypoint
- Open waypoint tab
- Start compass for a waypoint
- Use title bar map icon to switch to the map

Result:
Heading line is targeting to the cache coordinates but not to the waypoint previously selected for Navigation

**Comment by Stapvoetje** [comment]
My only way to get the heading line bearing to the chosen waypoint is:
- Open the waypoint tab
- Long press on the waypoint that you want to go to
- choose navigate
- display on map
- You end with the heading line has the right target on the screen
- It should be much easyer, that when you are in compass mode, you reach the same result if you press on the little map symbol.

**Comment by rsudev** [comment]
@Stapvoetje: Not sure what you want to say here. Right now it is like you describe finally, albeit yet only in the current development version. You can either try out that version (nightly build) or wait for our next feature release.

**Comment by Stapvoetje** [comment]
What I try to explain is that when you are on the waypoint tab and choose for a waypoint by pressing on the compass symbol right after that waypoint, you will be guided to that waypoint.

But when you are already in compass mode and you press on the little map then you get the heading line coupled on the coördinates displayed on top of the cache listing.

For most traditionals is that no problem, but surely for multies and misteries.

**Comment by rsudev** [comment]
And what I wanted to point out is, that this is already solved (therefore this bug entry is closed), but it is not yet released. Have you checked the nightly and still see this problem? Or did you want to emphasize that the release version has this problem?

**Comment by Stapvoetje** [comment]
I'm a newby here. I wanted to emphasize that the release version (2015.03.31) has this problem? I will wait for the new release! Thanks for your explanation.

**Comment by SammysHP** [comment]
This was fixed on 19 Apr 2015, so it's not in the release version yet, of course.
