### ISSUE TITLE
c:geo tries to import .kdbx-file

### ISSUE THREAD

**Issue by dargoel** [cgeo/cgeo#4890]
I have keepassdroid and c:geo installed in my android phone. When I try to open .kdbx (keepass password file), it is taken to c:geo and tried to be imported as waypoint-file (import GPX to list). There are no defaults set for c:geo so I don't find any way around this.

**Comment by Bananeweizen** [comment]
From where do you try to open the file? If from an email app or similar then that app might add a mime type. That sometimes leads to such confusing results. Therefore please try to use another app also to open the file.

**Comment by dargoel** [comment]
Thanks for your comment. I had it in my downloads -folder. I have keepassdroid also, but it seems to have problem, too, as it doesn't accept those files at all. I don't know if there is file type assignment -setting in android?

**Comment by Hauwertlhaufn** [comment]
I've tried it on my device, and for me it seems like it is an Android-related problem, 'cause GCDroid is suggested too, when I try to import a .kdbx.

**Comment by SammysHP** [comment]
Then we cannot fix it.
