### ISSUE TITLE
TB log has wrong date on website

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4892]
2015.04.16-NB

We had such an issue on support mail (or even here as an issue) but I was not able to reproduce or find a hint in our code:

- This morning at approx. 06:30am CEST I logged two TB (retrieve log)
- I am quite sure that the log date shown in c:geo was 17.04. (which would be correct) but I did not explicitly verify it , at least I did not change it manually
- Looking this evening at the website I see that those logs have the date 16.04. (e.g. http://www.geocaching.com/track/log.aspx?LUID=58d79e3f-56d5-4595-bbbe-326b8add5390)

The time zone settings of my device (Galaxy S4, Android 5.0.1) is set to factory value, i.e. derive from mobile network. Checking the world clock app it confirms the timezone used as GMT+2 (which is correct).

Can someone check if we send the log with just the absolute date or do we try to transmit a time and time zone info as well?

**Comment by kumy** [comment]
@Lineflyer only the date as (year, month, day) is submitted.

https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/connector/gc/GCParser.java#L1072-L1079

**Comment by Lineflyer** [comment]
In this case it is a bug on geocaching.com (while I still dont understand how this can be possible).
