### ISSUE TITLE
Starting c:geo from another application

### ISSUE THREAD

**Issue by kraul** [cgeo/cgeo#4893]
Does c:geo support receiving outside intents with coordinates as extras, to start a new waypoint / open the compass with those coordinates?

I'm very new to the android programming scene and due to lack of experience cant yet grasp your source code just by looking at it. I'm working on an application that has an option to share coordinates and i would love to give the users an option to open them on c:geo.

If this is possible, i hope you can point me to the right intent + class name.

**Comment by rsudev** [comment]
No currently does c:geo not support such an intent.
What would be your use-case for such a feature?

**Comment by kraul** [comment]
Okay :/

In my case, the application i'm creating is a coordinate converter. The idea was, that when the user gets their converted coordinates, one of the options would be to open them in c:geo(if installed, and when it is not, they would be directed to the Play store @ c:geo download).

**Comment by rsudev** [comment]
And where would those coordinates come from? Currently I can not fully envision what is the need you want to fulfill/problem you want to solve.
Already currently you could place those coordinates in the clipboard and then launch c:geo and paste the coordinates there e.g. in a waypoint dialog.

**Comment by SammysHP** [comment]
What should be possible? Creating a waypoint? Updating an existing one? How to select the corresponding cache? Or waypoint? Anywhere navigation?

**Comment by kraul** [comment]
rsudev: My converter app converts coordinates from L-EST(a geo format only used in Estonia) to wgs84 and backward. I would like to offer the user a possibility to directly start c:geo from inside my app, with destination coordinates set to the conversion result from my app. Sure, i also provide an option to copy the result and they could paste it in if they want, but that means extra work from the user, when i could make this more intuitive for them. I belive most people using my app would be geocachers and they will be using c:geo for their geocaching navigation.

This would need c:geo to listen for outside intent, marked for this purpose, taking for example dd.dddd coordinates as default extras to set the waypoint. I'm not sure if this would be useful for anybody else, i was just asking if this was allready supported / there would be others seeing potential in this option.

SammysHP: I'm only talking about creating a waypoint, with no cache attached to it. Manually i would do this by: Go to -> Insert the coordinates i need -> click on the compass/map to start navigating

**Comment by SammysHP** [comment]
Then I see no reason for this. There are better apps for waypoint handling and navigation.

Also see #4588 (and there is also another issue IIRC, but I cannot find it).
