### ISSUE TITLE
C:geo always exporting blank field notes

### ISSUE THREAD

**Issue by deusy** [cgeo/cgeo#4894]
I use c:geo for offline caching, but lately I've been having an issue where any field notes it exports are blank. At first I thought it was an error in uploading to geocaching.com, but I checked the field notes folder on my HTC's drive, and all the recent ones are blank. 

At the moment I am just logging my caches offline, then going into history and exporting them. This has been working perfectly for several months, but on my last holiday it stopped and I have had to log everything manually, which has been a huge hassle. Is this a bug, or do I need to be doing something different?

**Comment by Bananeweizen** [comment]
By blank, do you mean that the complete field note file is empty, or that only the log message for each single field note is empty (but the file as such exists)?

**Comment by deusy** [comment]
A field note file (.txt) exists for the export (the name of the file being the date and time), but it just a blank document with absolutely nothing in it.

**Comment by Lineflyer** [comment]
I just used this feature today and could not see any problem.
@deusy 
Can you describe how you offline log the cache and how you export them (step by step)?
Are these caches saved on your device?

**Comment by Bananeweizen** [comment]
I also could not reproduce the issue over the last 2 weeks.

**Comment by Lineflyer** [comment]
Closing due to lack of feedback.
Feel free to reopen if you can provide more details for reproduction of this issue.

**Comment by grzesztof** [comment]
I've got the same problem. Exported files with field notes are empty (the size of files is 0 bytes)

**Comment by rsudev** [comment]
Hi @grzesztof, can you fillin where @deusy didn't come back with feedback anymore. I also use this feature all the time and did not have any issue with it.
Questions:
* Are you trying FieldNotes for gc.com caches?
* Are the caches saved on your device (offline)?
If the answer to both is 'yes' please attach here your c:geo system info and describe step-by-step what you do to export the field notes.
