### ISSUE TITLE
cgeo not offered for opening coord.info links 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4897]
2015.04.18-NB

...if gc code is in small letters

e.g. http://coord.info/gc77

**Comment by rsudev** [comment]
did you create this link manually, or was it in some 'official' source (gc.com web or email link)?

**Comment by Lineflyer** [comment]
I have seen them on a uaer blog...self written.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: rsudev <notifications@github.com> 
Datum: 19.04.2015  22:02  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu> 
Betreff: Re: [cgeo] cgeo not offered for opening coord.info links  (#4897) 

did you create this link manually, or was it in some 'official' source (gc.com web or email link)?

**Comment by Bananeweizen** [comment]
Actually, that works for me on all devices and the emulator, opening the above link directly.

**Comment by rsudev** [comment]
If I click this link, either in the github notification mail or in octodroid, the browser opens directly. If I click a link in a gc.com notification (capital letters), c:geo, Lotus and the browser are offered (Sony Xperia Z1, Android 4.4.4). This is also what I would expect according to the android:pathPrefix documentation.

**Comment by SammysHP** [comment]
Android 4.4.4, open the link shows a menu that includes c:geo.

**Comment by rsudev** [comment]
@SammysHP: Device/ROM? (I have Sony stock ROM, rooted)

**Comment by Lineflyer** [comment]
Me: Android 5.0.1. on Samsung Galaxy S4 Stock, not rooted. From Samsung web browser.

**Comment by SammysHP** [comment]
@rsudev: Nexus 4, CM 11

**Comment by kumy** [comment]
For me it open default navigator
CM-12, Android 5.1 on HTC M8

**Comment by kumy** [comment]
All those link should work:
    http://coord.info/gc77
    https://coord.info/gc77
    http://www.coord.info/gc77
    https://www.coord.info/gc77
    http://coord.info/GC77
    https://coord.info/GC77
    http://www.coord.info/GC77
    https://www.coord.info/GC77
