### ISSUE TITLE
Include offline finds in total finds on home screen

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#4900]
As you might have noticed by now I am a die hard offline user of c:geo.
That is one of the reasons I want issue #4334 to be dealt with.
I definitely see it as a bug rather than a feature by design.

Anyhow...

I have another feature request that might help us off-liners to keep count of the total finds in another way.

Today it says like this on the home screen:
geocaching.com • MrYaz (2233) • Login OK

What if the offline founds would be listed as well like this:
geocaching.com • MrYaz (2233+48) • Login OK
...where 2233 are the online founds and 48 are the offline founds

Or even:
geocaching.com • MrYaz (2233+48=2281) • Login OK
...to help doing the math for you.

If you don't make any offline logs the found count are listed exactly like it is today.

**Comment by Lineflyer** [comment]
That would be good as soon as the way we count offline logs is dealed with in general:
https://github.com/cgeo/cgeo/issues/987

**Comment by fm-sys** [comment]
Anything new on this?

What about `GC • geoFM1 (180 + 10 offline) • Login OK` ?
Which style is prefered? We also should also store the last received number of found caches to use it in #987
I think it should be realy simple to implement this... What about adding it to [Beginner topics](https://github.com/cgeo/cgeo/projects/7)?

**Comment by Lineflyer** [comment]
@fm-sys 
Was out caching today and it worked excellent without the need to change anything in my usecase (I use [NUMBERS] in my signature and it now counts up as expected for my offline logs).

Thanks, brillant!
