### ISSUE TITLE
Can't see offline logs / offline logs only on the map visible

### ISSUE THREAD

**Issue by flasher1979** [cgeo/cgeo#4901]
If I make offline logs during a geocacheing session, I can't see them in c:geo. Only on the map, when i scroll to the position of the cache, the cache with the red smiley is shown.

I think it would be usefull, if a cache is logged offline, that the cache will automatically saved on the default list or on a list like 'offline logs'.

**Comment by SammysHP** [comment]
These caches are shown in the history (except that there is a known bug currently that not stored caches are not included).

**Comment by SammysHP** [comment]
... When logging from the map popup. Can't edit via phone.
