### ISSUE TITLE
Switch to Android support library 23.2.1

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4903]
http://android-developers.blogspot.com/2015/04/android-support-library-221.html

**Comment by Bananeweizen** [comment]
Is #4860 solved by that?

**Comment by samueltardieu** [comment]
I haven't tested.

**Comment by Bananeweizen** [comment]
I don't get that to work. Overriding the compat project is fine, when setting the compile level to 21, but afterwards I have 2 theme errors in our theme definition and there I'm just lost.

**Comment by rsudev** [comment]
I think I was able to locate the adequate replacements for the missing themes and also for three missing drawables.
But after that I get a crash in CGeoMap, as seemingly no ActionBar is present anymor in the map activities (MapsForge and Google).
I did some fiddling with requesting window features but to no avail. Of course is it possible to switch back to the old action bar in the map for all versions, but that looks really ugly...
I will continue my research tomorrow.

**Comment by Bananeweizen** [comment]
That is with the current maps implementation, right? I thought that it might be the best strategy to first focus on your new mapsforge map, a new Google map and only afterwards to switch the support library.

**Comment by rsudev** [comment]
I think switching to a new map implementation is a while down the road still, so it might nevertheless be worthwhile to dig a little deeper here. I assume that there is just some fiddling with themes/styles necessary to make this work.
That said is of course the other question what we gain from switching (besides perhaps looking more 'material').

**Comment by rsudev** [comment]
I tried back and forth with layouts and window features to no avail.
My current state of things is available under https://github.com/rsudev/c-geo-opensource/tree/issue-4903 for other to continue if so wished, I'll lay it aside for the moment.

**Comment by kumy** [comment]
new version v23.2.1 is available. I tried an upgrade this week end and failed at the same point as @rsudev on 24 Apr 2015.
(Just found this issue today :))

**Comment by Lineflyer** [comment]
@kumy Aren't we now on a newer version already?

**Comment by kumy** [comment]
@Lineflyer I don't think we've upgraded the dependency and mostly the code. We're still using [com.android.support:appcompat-v7:20.0.0](https://github.com/cgeo/cgeo/blob/master/main/build.gradle#L254)

**Comment by bekuno** [comment]
@kumy @rsudev 
In the meantime we use androidx.appcompat:appcompat:1.1.0 .
So can we close this issue or should it be renamed to "Migrate to AppCompat" instead?

**Comment by jonas-koeritz** [comment]
This should be closed. AndroidX and the Support libraries are mutually exclusive so this is no longer applicable.

**Comment by moving-bits** [comment]
c:geo itself does not use the old Support libraries anymore, but the viewpagerindicator does (in several files). Would this be a problem? Can we either upgrade the viewpagerindicator to AndroidX or replace it (there is already an issue for that one)?

**Comment by bekuno** [comment]
The article describes two main points - the Support V4 Library and the AppCompat Support Library.
The first one is wide used in c:geo, but the second one only partly.
Both are now part of androidx.

Using the AppCompat library should using older android versions as the current.
The AS Task "Migrate to AppCompat" shows 610 references in 112 files.
When testing the proposed changes only in cgeo contacts (2 files, 16 references) it does not work on my Samsung S6 (Android 7.0) (app crash).
Therefore I propose also to close this issue now and switch to AppCompat within other planed changes.

**Comment by moving-bits** [comment]
Thanks for the replies. Then let's close this issue.
