### ISSUE TITLE
Cache inventory should be smarter ;)

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4911]
With the coming of generic trackables, having the inventory stored as a simple list in the `cache` object start to be limited...

Problems:
* Grouping trackables from different sources
* Merge GK from OC connectors and GK connector (duplicates)

Using a `HashMap` may be an idea...

**Comment by SammysHP** [comment]
Using a hashmap doesn't solve the problem of merging duplicates. You'll lose one or the other. But can you describe in which circumstances duplicates are even possible?

Is there a real benefit for not using a simple `List`? I don't think that there are any performance reasons for such small lists.

**Comment by kumy** [comment]
@SammysHP you are right, transforming to another type is not necessary. However, having some helper functions would help.
I'll upload a PR, let me your comments.

**Comment by kumy** [comment]
PR #4913
