### ISSUE TITLE
API 22 on the CI

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4920]
@mucek4 Could you please install API 22 on the CI? We need this to restore the nightly builds.

**Comment by Lineflyer** [comment]
@mucek4 Don't know how much effort this is, but it would be good to get it running again to restore the nightly in order for me (and interested users) to continue testing the development version.

IMHO also our tests builds are no longer working now.

**Comment by SammysHP** [comment]
5 min effort. :/

**Comment by mucek4** [comment]
Don't know why replay over email didn't work. I was absolutely sure I updated everything on CI couple of days ago when samuel asked on IRC. Will check asap.

**Comment by mucek4** [comment]
This is installed on CI from couple of days ago. Am I missing something?
![brez naslova](https://cloud.githubusercontent.com/assets/832407/7537366/9b99822e-f598-11e4-821c-a83c35c75f46.png)

**Comment by rsudev** [comment]
Build tools 22.0.1 are required (third line).
Additionally was it necessary to add the two new libs to the nightly jenkins configuration, as this does not use the preparation build

**Comment by mucek4** [comment]
Build tools also installed. 

I know it's 5 minutes, but it's not my fault for CI not functioning.

**Comment by Lineflyer** [comment]
No problem.
Maybe we should define the rule, that the one changing the build target should also take care of the CI (if that is possible from remote)?

**Comment by Lineflyer** [comment]
Nightly build is working. Cannot judge if this issue can be closed though.

**Comment by mucek4** [comment]
I added SDK 22 as soon as samuel asked me. However I missed new build tools and didn't posted here anything. Managing CI on remote is possible if one has static IP (to allow single IP to access it)
Issue is fixed and can be closed.
