### ISSUE TITLE
In cache details: button are too small for labels

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#4923]
Hi,

I'm reviewing the french translation and I have noticed a button in cache details (see screen capture) which can not exceed 6 caracters ... it's very very short (I would like to translate this button to "Recharger" a word only 9 caracters long)
![bouton size](https://cloud.githubusercontent.com/assets/1452146/7502703/4c7d46ae-f43e-11e4-8976-f0e03704fc45.jpg)

Note: I think there is enough place here to put a bigger button and I'm sure I'm not the only user/translator who found this "6 caracters limit" too short for a button label.

Thanks for your attention,

**Comment by rsudev** [comment]
Thanks for highlighting. In fact, this button is too small also in German :)
I'll try to check the layout for this.

**Comment by Lineflyer** [comment]
Isnt it possible to make the size of the box adaptive to the content defining a maximum?
There are quite some places in c:geo here this might be helpful...




Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: Nam <notifications@github.com> 
Datum:06.05.2015  22:27  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Betreff: [cgeo] In cache details: button are too small for labels (#4923) 

Hi,

I'm reviewing the french translation and I have noticed a button in cache details (see screen capture) which can not exceed 6 caracters ... it's very very short (I would like to translate this button to "Recharger" a word only 9 caracters long)


Note: I think there is enough place here to put a bigger button and I'm sure I'm not the only user/translator who found this "6 caracters limit" too short for a button label.

Thanks for your attention,

**Comment by rsudev** [comment]
Adapting to the content is kind of a default in Android, but only within some constraints, depending on the surrounding layouts. Therefore it is necessary to check where this limit emerges from and if it e.g. makes sense for small screens or something similar. In that case we would need to find a compromise.

**Comment by Lineflyer** [comment]
I think we should not change anything here for this specific button but rather but this on the To Do of the more generic issues for a new design of the cache detail activity (e.g. #4319).

So I would like to close this issue unless someone is willing to dig into this and make some adaptions to the current layout?!

**Comment by kumy** [comment]
![english](https://cloud.githubusercontent.com/assets/176794/7737123/12f46406-ff49-11e4-88f8-4a52dbb85367.png)
![french](https://cloud.githubusercontent.com/assets/176794/7737125/12f79658-ff49-11e4-8a85-09ba2d130c2e.png)
![german](https://cloud.githubusercontent.com/assets/176794/7737124/12f6b60c-ff49-11e4-865f-90ec1ec56908.png)

What do you think? Should I merge?

**Comment by Lineflyer** [comment]
Sure..looks like a good workaround.
