### ISSUE TITLE
c:geo not registered for Mainz lab cache links

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4927]
The app does not recognize the gpx links on this page: http://www.gutenberg-2015.de/index.php/en/labs

**Comment by rsudev** [comment]
Not sure if it gets the chance...
What browser do you use?
The server does return them as 'text/plain', so AFAICS e.g. Firefox does not offer them to Android at all for viewing (to be picked by the pathPattern in the intent filter)

**Comment by Bananeweizen** [comment]
Using Chrome here. I've successfully added yet another intent filter which completely ignores the mime types and just goes for the path pattern, so it will accept any GPX file from a URL. But that needs some additional tweaking in the import code, as we need to download the content ourselves then. Will create a PR for review, if I get it working.
