### ISSUE TITLE
Hint not shown in compass when started from live map

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4930]
Today I used the compass on a cache which had a hint. In the compass it was always shown as "no hint available".

**Comment by Lineflyer** [comment]
This seems no generic issue as it was working for me today. 2015.05.10-NB

**Comment by Eselter** [comment]
Sometimes I have this problem also. When I back to previous screen like map or cache desc and return to compass hint working again corectly.

**Comment by Lineflyer** [comment]
@Bananeweizen @Eselter 
Can you remember on which way you started the compass (or opened the cache before starting the compass).
I think it could depend on the way you opened that cache (e.g. from live map, from list, from nearby search,...)

**Comment by Eselter** [comment]
Ofc hint not working when we open compas from map directly without loading cache details. I think there should be a diffrent message like cache detail not loaded please refresh cache or sth like that.
But if I remember correctly I have this problem also when cache is stored in memory but I can't reproduce this.

**Comment by Bananeweizen** [comment]
As I was on a bike trip that day the chance is very high I opened that cache from the live map without having it stored locally. That would also generally fit, as for caches from the map some data can be missing.

**Comment by Lineflyer** [comment]
I can reproduce the live map case:
If a cache is only loaded on live map but not yet detailed we do not have the hint and thus it is not available in the compass.
This could only be "solved" by showing a message that the hint is not available as the cache is not loadad instead of assuming that there is no hint.

**Comment by Lineflyer** [comment]
Link to #1317 somehow

**Comment by Lineflyer** [comment]
In the live map case for unstored caches its clear we do not have the hint information
