### ISSUE TITLE
Project fail to build on Idea since inclusion of undobar

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4931]
Required modules for `undobar` are not declared in idea configurations.

**Comment by Bananeweizen** [comment]
Are you by chance good in gradle? cause the gradle build also breaks at the undobar. Normally we could just fetch the dependency Maven-style and ignore the local files, but in this case the artifact has a classifier, and I haven't found a way to tell gradle to respect that classifier.

**Comment by kumy** [comment]
@Bananeweizen, see if cc82df1 works for you, after playing a bit this diff allowed me to get a "BUILD SUCCESSFUL".

**Comment by Bananeweizen** [comment]
Sorry for not reporting back earlier. The change looks good to me, however I only sporadically try building with gradle without really knowing what I do. :)

**Comment by kumy** [comment]
@Bananeweizen hehe, same for me... Idea was a big help for the gradle part
