### ISSUE TITLE
Provide a F-Droid repo for the apk

### ISSUE THREAD

**Issue by jspricke** [cgeo/cgeo#4933]
Hi,

would it be possible to provide a simple F-Droid repository for the cgeo apk? There is a Howto here: https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo. This would allow all F-Droid users to get updates automatically, even if cgeo is sadly not part of F-Droid.

Thanks!

**Comment by kumy** [comment]
+1

**Comment by Bananeweizen** [comment]
The c:geo APK includes lots of stuff (e.g. Google Maps, Google Play Services) which are not accepted by the F-Droid guys. That's why in the past they rebuilt c:geo with modifications to exclude those. And that in turn led to the F-Droid APK to be always out of date. Therefore we explicitly requested to _remove_ our app.

I still see these issues valid, therefore I tend to reject this request.

**Comment by jspricke** [comment]
It's not about adding it to F-Droid but rather providing your own repository on your webserver which could be added to the F-Droid client (like you provide the apk already from there).

**Comment by SammysHP** [comment]
@jspricke is correct, as well as @Bananeweizen. The official f-droid repository is a no-go. They do not want us and we had long discussions.

But an own repository which can be included in the f-droid store app might be possible.

**Comment by rsudev** [comment]
I took a short look into the supplied howto. technically it seems not much work and possible to integrate with our processes (e.g. automatically posting our release through a Jenkins job).
But this would direct some load at our server, for checking versions and downloading updates by users. Not sure how much this would be and what the possible limits are on our hosting.

**Comment by SammysHP** [comment]
Maybe there is a repository that is willing to include us.

**Comment by jspricke** [comment]
I'm not aware of any bigger third party repo (apart from the guardian project), but there some projects providing their own repo already. You can find a list here: https://f-droid.org/forums/topic/app-repositories-list/.

**Comment by kumy** [comment]
Maybe we could provide two distinct repos, one for the mainline, and the other for nightly builds.

If you are ok, I'll play a bit with the fdroid tools to see how all that works. (As a starting point, I'll host it on the GKM server.)

**Comment by mucek4** [comment]
For servers it's not a problem. We have some of them that can be used for this.

**Comment by kumy** [comment]
@mucek4 great :)

**Comment by kumy** [comment]
For the testing purpose here are _**NON OFFICIAL**_ repos:

```
mainline: http://cgeo.geokretymap.org
nightly builds: http://cgeo.geokretymap.org/nightly

fingerprint: 370BB4D550C391D5DCCB6C81FD82FDA4892964764E085A09B7E075E9BAD5ED98
```

--
Descriptions are simple copy/paste.
Didn't see any multilingual support.

Deploying a new version is as simple as put the new apk in the directory and launch the index update.
I suppose we don't need the "build" functionalities, so not tested.
But this imply no archive functionality (to be verified)

**Comment by jspricke** [comment]
Just tested both of them, working great. For the official version, https would be great, btw. I guess you can rename the apk according to the version code to get archive functionality.

**Comment by kumy** [comment]
I've wrote a [script](https://github.com/GeoKretyMap/Scripts/blob/master/cgeo/fdroid-update.sh) to auto-update repositories via cron.

Mainline/Nightly builds are up to date.

Repositories contains :
* c:geo
* c:geo Calendar
* c:geo Contacts (but didn't find any NB for this one)

How can I help more on this issue?

**Comment by jspricke** [comment]
@mucek4 can we get an official version of this?
@kumy thanks for the work!

**Comment by kumy** [comment]
As the nightly build are updated every nights in the repo, I've just manually launched update for the mainline. :)

**Comment by rsudev** [comment]
Thanks :)

**Comment by jspricke** [comment]
Are these now considered official? Could we get https for them?

**Comment by kumy** [comment]
@jspricke ssl is now enabled ;)

**Comment by kumy** [comment]
Closes: GeoKretyMap/nginx-config#3

**Comment by jspricke** [comment]
Awesome thanks! I've posted it here as well: https://f-droid.org/forums/topic/app-repositories-list/#post-16307

**Comment by mucek4** [comment]
@kumy if you would like to maintain the repo I can create cname or redirect to domain?

**Comment by kumy** [comment]
@mucek4 I would be happy to. :)
I could also give you a CSR to be signed by your CA (StartSSL?)

**Comment by kumy** [comment]
A CNAME to `cgeo.geokretymap.org.` would be perfect.

**Comment by kumy** [comment]
New release included.

That would be good, if CI can `ping` me so updates are automatic.
Cron (for NB) is scheduled at around 1h am. For example, if multiple NB are build in a day I'll miss some.

**Comment by rsudev** [comment]
Just specify how this ```ping``` should look like (http put or post or similar, like status) then it would be easy to put into the jobs as an additional step.

**Comment by kumy** [comment]
@rsudev ok thanks. Not here this WE, I'll work on that next week.

**Comment by kumy** [comment]
@mucek4 did you had time to create the DNS entry?

**Comment by kumy** [comment]
Thanks to @mucek4 we've set up a new url on `cgeo.org` domain.
Note, this doesn't support SSL **yet**.
```
mainline: http://fdroid.cgeo.org
nightly builds: http://fdroid.cgeo.org/nightly

fingerprint: 370BB4D550C391D5DCCB6C81FD82FDA4892964764E085A09B7E075E9BAD5ED98
```

**Comment by kumy** [comment]
@rsudev I've wrote an very simple Api to trigger the update.
See https://github.com/GeoKretyMap/api-fdroid

I've allowed ci.cgeo.org IP to access the script.
Let me know how to transfer the secret code securely :)

**Comment by mucek4** [comment]
OK @kumy I have send you SSL certificate you just need a key. Meet me on IRC.

**Comment by kumy** [comment]
@mucek4  thanks

New SSL certificate is installed.
```
mainline: https://fdroid.cgeo.org
nightly builds: https://fdroid.cgeo.org/nightly

fingerprint: 370BB4D550C391D5DCCB6C81FD82FDA4892964764E085A09B7E075E9BAD5ED98
```

@jspricke may you test the new urls please?

**Comment by jspricke** [comment]
Working fine, thanks a lot guys!

**Comment by kumy** [comment]
Still need to implement:
* trigger update from CI side
* maybe put the repo information on the website?
* fill the FAQ

**Comment by Lineflyer** [comment]
@kumy 
> fill the FAQ

What would need to be added to our FAQ for that, I don't understand?

**Comment by kumy** [comment]
@Lineflyer Could be some lines explaining how to add the repository ; ex: http://geokretymap.org/configure-f-droid-for-cgeo-repo/

**Comment by kumy** [comment]
Trigger automatic updates is on the way.
I've added a new shell command to the Nightly CI job.

Need @mucek4 to create a new file on the CI server. (Informations passed by PM to @mucek4)

**Comment by mucek4** [comment]
File created. Just tell me what have you done on CI to keep in loop.

**Comment by kumy** [comment]
@mucek4 thanks

I've added a new "Execute shell" at the end of the job `c-geo-nightly`: 
```
# Force update of the f-droid repository
curl https://fdroid.cgeo.org/update-fdroid.php --data @/srv/statusSecretFdroid -d "REPO=nightly"
```
I'm testing with the newly created file, then add the same script to `c-geo-RELEASE`

**Comment by kumy** [comment]
seems ok for nightly job.

I'll add the same to `release` job once current update to CI job has been approved.

**Comment by kumy** [comment]
hum, multiple NB cannot be indexed in the repo, as the build number doesn't change (NBx, not part of the build number?).

```
duplicate versions: 'cgeo-nightly-2015.08.06-NB-c204c6b.apk' - 'cgeo-nightly-2015.08.06-NB1-c204c6b.apk'
```

**Comment by SammysHP** [comment]
Version is always an integer. We use the date + some 1\d+.

**Comment by kumy** [comment]
Here are the `aapt dump` for today's builds.

I think that the matched field is `versionCode`. If another package comes with the same version (eg NBx), he isn't indexed. (and old builds are even rotated! (bug?))
Would it be possible to set `versionCode` the same as `versionName` ?

```
fdroid@cinco:~/www/nightly/repo$ /opt/android-sdk/build-tools/22.0.1/aapt dump badging cgeo-nightly-2015.08.06-NB-c204c6b.apk | head -n1
package: name='cgeo.geocaching' versionCode='30150806' versionName='2015.08.06-NB-c204c6b' platformBuildVersionName='5.1.1-1819727'
fdroid@cinco:~/www/nightly/repo$ /opt/android-sdk/build-tools/22.0.1/aapt dump badging cgeo-nightly-2015.08.06-NB1-c204c6b.apk | head -n1
package: name='cgeo.geocaching' versionCode='30150806' versionName='2015.08.06-NB1-c204c6b' platformBuildVersionName='5.1.1-1819727'
fdroid@cinco:~/www/nightly/repo$ /opt/android-sdk/build-tools/22.0.1/aapt dump badging cgeo-nightly-2015.08.06-NB2-c204c6b.apk | head -n1
package: name='cgeo.geocaching' versionCode='30150806' versionName='2015.08.06-NB2-c204c6b' platformBuildVersionName='5.1.1-1819727'
```

**Comment by SammysHP** [comment]
`versionCode` is an integer as I said above.

**Comment by PanderMusubi** [comment]
What libraries is cgeo using at the moment (April 2018) that makes it a problem to be included directly into the official F-Droid repo?

**Comment by kumy** [comment]
@PanderMusubi It's in the [third comment](https://github.com/cgeo/cgeo/issues/4933#issuecomment-101585553) of this thread

> The c:geo APK includes lots of stuff (e.g. Google Maps, Google Play Services) which are not accepted by the F-Droid guys.

**Comment by PanderMusubi** [comment]
I was wondering if that is still the case. Thanks for the update. So the solution with an own F-Droid repo is indeed the best.

**Comment by kumy** [comment]
> I was wondering if that is still the case.

"Sorry" yes :disappointed:. And I'm quite sure it will not change anytime soon.

**Comment by kolAflash** [comment]
> You can find a list here: https://f-droid.org/forums/topic/app-repositories-list/.

Dead link.

New link:  
_Known Repositories_  
https://forum.f-droid.org/t/known-repositories/721

Archived:  
_App Repositories List_  
http://web.archive.org/web/20170226011347/https://f-droid.org/forums/topic/app-repositories-list/
