### ISSUE TITLE
Add fan group link

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4934]
In addition to the normal Facebook link we should add the link to the German user group.

**Comment by SammysHP** [comment]
In c:geo or on the website?

**Comment by Bananeweizen** [comment]
I meant in the app. But it could be useful on the website too?

**Comment by moving-bits** [comment]
Is that group still existing and active?
If someone provides me the link, I can add it to the app.

**Comment by bekuno** [comment]
Probally https://www.facebook.com/groups/cgeo.fangruppe

**Comment by moving-bits** [comment]
ok, thanks, will add it
