### ISSUE TITLE
c:geo revert geocaching.com website language settings back to English

### ISSUE THREAD

**Issue by geokoodi** [cgeo/cgeo#4935]
Hi,

I left the following message to the geocaching.com site:
"How can I store my user interface language more permanently.
Apparently, this option uses cookies to store language?
I don't want to store cookies permanently, because I also use public computers.
If I close browser and logged in again, the user interface language setting is returned back to original."

..and geocaching.com answer:
"Hello,
Thank you for contacting Geocaching HQ.
Do you use the Android app c:geo? There is a bug currently in the app that is reverting your language settings back to English on our website. Since this is third party website, we have no control over fixing it. You will have to reach out to c:geo for additional support.
Please let us know if you have further questions.
Kindly,
Janelle Geocaching Community Manager"

**Comment by rsudev** [comment]
Hi geokoodi, this is not a bug, but by design. Please take a look at our faq: http://faq.cgeo.org/#1_39
