### ISSUE TITLE
alternative domain for send to cgeo

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4936]
Currently we use send2.cgeo.org for the scripts. I suggest to have sendto.cgeo.org in addition. Writing the "to" as "2" might be common in techy English speaking communities, but for the general average user (that is typically a non English native) the explicitly written "to" might be more easy to read.

**Comment by Lineflyer** [comment]
Assigning to @mucek4

**Comment by Lineflyer** [comment]
@mucek4 Can you do this as alternative subdomain which targets the same page?

**Comment by mucek4** [comment]
I think easier thing would be redirect. Would a redirect be ok?

**Comment by Lineflyer** [comment]
Sure. I thought of that. Replacing the URL would need us to change it in many places.
