### ISSUE TITLE
Refresh option not avaible from menu in history

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#4938]
When I go to history and open any cache from there I don't have refresh option in menu (3 dot menu).

**Comment by Lineflyer** [comment]
Confirmed with 2015.05.17-NB.
I don't think this is intentional as we still have the button for refresh shown in the cache details. So I consider this as a bug.

**Comment by kumy** [comment]
This happens at https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/CacheDetailActivity.java#L553

`cache.isOffline()` is False in this context

The first implementation appeared in 6d1d6599ed0 (31 May 2014).

**Comment by kumy** [comment]
PR #4956
