### ISSUE TITLE
Moving caches by selection mode

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4939]
This should not be possible

**Comment by Lineflyer** [comment]
@Bananeweizen: Can you explain in more detail what the problem was and what you changed. I don't get the difference.

**Comment by SammysHP** [comment]
It was possible to move caches from one list to another by selecting them and then switching the list. Looks like it was intended.

**Comment by Bananeweizen** [comment]
Selection mode, select some caches, switch list, and by magic the selected caches were moved to the switched list.

This is from the very old days of c:geo and can be _very_ confusing if you don't intentionally do it.

**Comment by mucek4** [comment]
It was intended in early days and it was the only option to move caches around. @Bananeweizen found that wrong and remove it asap :)

**Comment by Lineflyer** [comment]
Thanks for the explanation, I wasn't aware of this "feature".
