### ISSUE TITLE
Spotted field is wrong for GKs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4942]
2015.05.18-NB

- Open GKC240

The "spotted" field shows "in GC1HKWQ" but in fact the GK was only visited there and is still with a user (with myself).
For a GC trackable the user name of the curent holder is shown in such a case.
Not sure whether this is a bug or a different function at GK.

**Comment by Lineflyer** [comment]
I understand and I think your proposal of the logic would be reasonable.
Let us take this as a "Feature request" (meaning I do not see this as mandatory for relasing that feature, but as an improvement for the future).

btw:
Is there any possibility to unarchive a GK or is it unarchived by just moving it?

**Comment by kumy** [comment]
>Is there any possibility to unarchive a GK or is it unarchived by just moving it?

Archive doesn't block moves. Status is updated with the youngest logtype.

**Comment by kumy** [comment]
Here are some (active) GK for testing:

* GKC1D4: Archived
* GKC240: Travelling
* GKB65C: in cache
* GK8C12: in cache and missing
* GKC614: Visiting + 0 km
* GKC225: Visiting
* GKC576: Seen
