### ISSUE TITLE
Display an alert when submitting log without cache Geocode?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4943]
This follows #4787 "GK visit should be possible without geocode".

Now, it is possible to log a GK without specifying a cache Geocode, but (IMHO) this may not be a "good practice" as GC coordinates are not automatically imported in GeoKrety service database, this make logging on the GK website difficult for newbies.

GC/coordinates are 1st stored when user log GK ; next GK log in same GC cache will prefill coordinates from last input.

In #4787, I proposed to show a message to users when no Geocode was filled. Text could be:
"You're about to send a log without a cache Geocode. It's encouraged to set one. Do you really want to proceed?"
We could also add a "remain choice" checkbox to not annoy users...

**Comment by Lineflyer** [comment]
Help me please to get the current working mode:

This will only be applied if someone opens a GK and manually adds a log of the type `Visited`, `Retrieved` or `Placed`, correct?
But I also remember that you prefilled some fields in some cases (was it only the coordinates or more)?

**Comment by kumy** [comment]
> This will only be applied if someone opens a GK and manually adds a log of the type Visited, Retrieved or Placed, correct?

Exactly (except "will" -> should")

> But I also remember that you prefilled some fields in some cases (was it only the coordinates or more)?

Absolutely, coordinates _are_ looked up when geocode is filled.
Maybe you were also thinking about #4789 `Tracking code should be prefilled when GK is in user's inventory`

**Comment by Lineflyer** [comment]
> Absolutely, coordinates _are_ looked up when geocode is filled.
Maybe you were also thinking about #4789 `Tracking code should be prefilled when GK is in user's inventory`

mmh. I remember that I opened the logging activity for a GK and coordinates and geocode have been prefilled already...how might this happen?
I don't remember right now whether it was a GK I had in my inventory or if it was in a cache.

**Comment by kumy** [comment]
You're right, this could happen if you open the GK (then log) from a cache inventory

**Comment by Lineflyer** [comment]
OK understood.

Coming back to your proposal:
I think it would be good (including the "remain choice") to have this as it helps GK to populate its database.

**Comment by kumy** [comment]
ok, I'll work on it.
(Have to find how such a "remain choice" have to be implemented... ;))

**Comment by Lineflyer** [comment]
You could also implement a counter and auto dismiss it after three(?) times showing it like we do fo the live map warning.

**Comment by kumy** [comment]
Good idea too, I'll try to find that part of code.

**Comment by kumy** [comment]
Hope this is what is expected ;)
