### ISSUE TITLE
Introduce Groundspeak API

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4944]
Assuming that c:geo would be able to get API access from Groundspeak:

1. Which points of the existing [API license agreement](https://www.geocaching.com/mobile/api_license_agreement.aspx) would need to be discussed and/or modified to match our requirements?

2. Can we keep all existing functions if we change to the API or what technical modifications would be needed for the API to achieve this? I found [this help page](https://staging.api.groundspeak.com/Live/v6Beta/geocaching.svc/help) via Google, but don't know if this reflects the current API.

**Comment by Lineflyer** [comment]
See also [IRC log 18.05.2015](http://irclogs.cgeo.org/?year=2015&month=5&day=18)

**Comment by SammysHP** [comment]
See also #167.

**Comment by Lineflyer** [comment]
Oh, didn't know that issue. Lets continue there as it also has all the history.
