### ISSUE TITLE
Change Trackables icons?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4946]
This follows PR #4859.

Actual icon for TB doesn’t seem to suit for everyone...

Current icons for Trackables are:
Unknown:
![trackable_all](https://cloud.githubusercontent.com/assets/176794/7165356/86d87028-e3a7-11e4-9fcb-a0502eec7bbb.png)
TravelBug:
![trackable_travelbug](https://cloud.githubusercontent.com/assets/176794/7700187/1c32b310-fe1d-11e4-8f1f-f3782afbe645.png)
GeoKrety:
![trackable_geokrety](https://cloud.githubusercontent.com/assets/176794/7165363/91640da4-e3a7-11e4-839b-111e5bdb5630.png)
Swaggie:
![trackable_swaggie](https://cloud.githubusercontent.com/assets/176794/7165357/86df1536-e3a7-11e4-8eb5-74a5c0ad6e3f.png)

New proposed icon for TB:
![trackable_tb](https://cloud.githubusercontent.com/assets/176794/7165404/d44da7b0-e3a7-11e4-89ac-1ffa8b390d23.png)

-----

Extracted exchanges from old PR.

![68dcde60-e2f8-11e4-832a-e5021079c217](https://cloud.githubusercontent.com/assets/176794/7700423/ebb2a61c-fe1e-11e4-9ab4-592ba63f4101.png)
![e0dc7218-e2f8-11e4-9eda-488a9d879423](https://cloud.githubusercontent.com/assets/176794/7700426/ebc21854-fe1e-11e4-9b47-ad4ee3e5b81a.png)
![device-2015-05-19-115930](https://cloud.githubusercontent.com/assets/176794/7700425/ebbb605e-fe1e-11e4-82ca-d4fcc47bed7c.png)

@SammysHP said:
> I'd prefer the first one. Why? Because it shows "Travelbug and Geocoin" – you can't distinguish between them. What we need is this first icon and an icon for Geokretys.

@kumy said:
> I've hacked the existing icon a bit to build the TravelBug icon.
![trackable_tb](https://cloud.githubusercontent.com/assets/176794/7165404/d44da7b0-e3a7-11e4-89ac-1ffa8b390d23.png)

@SammysHP said:
> I'd use a question mark for unknown, in your draft unknown and travelbug are rather similar.

@Lineflyer said:
> I would currently not like to use a question mark for an unknown brand, because in our current way of loading all GC-trackables are unknown as long as you only look at the inventory of a cache.

>If the standard GC-only user opens a GC cache it would be OK and correct if he would see this icon IMO:
![trackable_tb](https://cloud.githubusercontent.com/assets/176794/7165404/d44da7b0-e3a7-11e4-89ac-1ffa8b390d23.png)

**Comment by Lineflyer** [comment]
Let me have a look at the recent change you did to learn when which icon is currently used. Then I will come back to this issue with a proposal.

**Comment by Lineflyer** [comment]
@kumy 
Have a look into GC4TB1G please.
I would like to understand why that inventory shows me this icon ![trackable_travelbug](https://cloud.githubusercontent.com/assets/176794/7700187/1c32b310-fe1d-11e4-8f1f-f3782afbe645.png) whereas other cache do only show this icon ![trackable_all](https://cloud.githubusercontent.com/assets/176794/7165356/86d87028-e3a7-11e4-9fcb-a0502eec7bbb.png)

**Comment by kumy** [comment]
@Lineflyer I suppose you did your test with latest NB. In the cache you cite, I see the TB icons, but (with yesterday patches) I cannot see the "generic" icon on other caches. I've tested on GC2DX0V.
Do you have an example cache where you still see "generic" icon?

**Comment by Lineflyer** [comment]
You are right, that was because of your changes.

But now I do always see this icon  ![trackable_travelbug](https://cloud.githubusercontent.com/assets/176794/7700187/1c32b310-fe1d-11e4-8f1f-f3782afbe645.png) also on items which could still be a geocoin. So i guess this icon should be used everywhere around instead:![trackable_tb](https://cloud.githubusercontent.com/assets/176794/7165404/d44da7b0-e3a7-11e4-89ac-1ffa8b390d23.png)

This brings me to the next question:
Where would this icon ![trackable_travelbug](https://cloud.githubusercontent.com/assets/176794/7700187/1c32b310-fe1d-11e4-8f1f-f3782afbe645.png) then be used at all?

**Comment by kumy** [comment]
The proposition was to _replace_ ![trackable_travelbug](https://cloud.githubusercontent.com/assets/176794/7700187/1c32b310-fe1d-11e4-8f1f-f3782afbe645.png) by ![trackable_tb](https://cloud.githubusercontent.com/assets/176794/7165404/d44da7b0-e3a7-11e4-89ac-1ffa8b390d23.png) as suggested originally by @SammysHP ("Because it shows "Travelbug and Geocoin" – you can't distinguish between them.").

**Comment by Lineflyer** [comment]
> The proposition was to replace trackable_travelbug by trackable_tb as suggested originally by @SammysHP ("Because it shows "Travelbug and Geocoin" – you can't distinguish between them.").

That would be a good solution IMO. Feel free to change it accordingly.
