### ISSUE TITLE
Refreshing stored list resulted in incorrect display

### ISSUE THREAD

**Issue by djtooley** [cgeo/cgeo#4947]
Summary: Refreshing all caches in a list caused repeated caches to be displayed on screen with different information.

I had 14 caches stored in my "Found List" and I was logging them on my computer.
When I completed my logging (on the computer)  I did a "Refresh All" in c:geo and the caches refreshed. (I wanted to verify that I hadn't missed logging any.)
What was displayed after that was a combination of "unfound" caches and "found" caches of the same name.  It appeared to have not cleared the previous state properly before reloading the cache. 

To clarify: Some caches were displayed twice, once with the "Cache Found" green bar, and once without.  See attached screen shot.

Exiting the list and re-entering refreshed the display correctly.

![sgn3d_screenshot_2015-05-19-10-49-52](https://cloud.githubusercontent.com/assets/3218325/7706104/6cabe606-fe16-11e4-9dc2-40da3b31f7ab.png)

**Comment by Lineflyer** [comment]
Wow..thats strange.
Can you please post your system information from c:geo Menu - About c:geo - System?

**Comment by djtooley** [comment]
Sorry for the late reply...
Email was miss-filed.
C:geo version number has probably updated since then.

--- System information ---
Device: SM-N900W8 (hltevl, samsung)
Android version: 5.0
Android build: LRX21V.N900W8VLU2DOC4
Cgeo version: 2015.03.31
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: true
Map strategy: auto
HW-acceleration: enabled (default state)
geocaching.com: logged in (Login OK) / Premium
System language: en_CA
Installed cgeo plugins: none
--- End of system information ---

**Comment by Lineflyer** [comment]
@djtooley 
Did this problem reoccur in the current version of c:geo 2015.07.08?
Otherwise I would like to close this, as I assume some database corruption (or just an issue displaying the list) happend, which is not reproducible.

**Comment by Lineflyer** [comment]
Feel free to reopen if it occurs again.
