### ISSUE TITLE
Possibility to set single trackables to "Always visit"

### ISSUE THREAD

**Issue by sejtam** [cgeo/cgeo#495]
The current 'set trackabled to automatically visit' assumes that I'd want to visit all of the trackables in my inventory. That is not true.
I have exactly ONE that I want to automatically visit. So with this option on, I have to even do more work (turn the others off) when logging. I think there should be a separate list (not automatically updated!) that I describe in which trackables should automatically visit, and that should then be added to whatever actions I might take on others when logging.

Alternatively, allow an action 'visit always', which will set that trackable to 'visit' and remeber that, as long as that trackable is in my hands, so that it comes up preselected as 'visit always' the next time. c:geo should alert me if it finds a trackable marked as 'visit always' that is no longer in my hand (which would mean someone grabbed my trackable tattoo and I'll have to re-gram it from them, they cannot have really taken it!). It would be nice if c:geo could allow me to re-grab that trackable straight from the app, but as that would happen much less often it won't be so much of a pain to do it through the browser.

**Comment by Lineflyer** [comment]
See #13590
