### ISSUE TITLE
Have a better string for send2cgeo import

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4950]
Currently this item is named "Import from web" (german: "Aus dem Internet importieren").
Why not be more precise like "Send2cgeo".

**Comment by ldmpub** [comment]
Hi,

Two original english strings are containing the word "web" and not "Send2cgeo", see the following keys:
- web_import_title
- web_import_waiting

It's was translated in french by the same words => I think you're suggestion is better and I have updated the french translation.

Thanks,

**Comment by Bananeweizen** [comment]
Semantic changes like this one should not be done by simply changing the translation string. Because no translator will recognize the change. In such cases you have to modify the _key_ of the translation (in Java source) to invalidate all existing translations.

**Comment by Lineflyer** [comment]
No. We have learned meanwhile that Crowdin automatically resets the translations is the source is changed (or our script for Corwdin does it?)
