### ISSUE TITLE
Strange double final Points (in a menu)

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#4952]
Hi,

It looks like c:geo adds ".." to 2 translated strings (see screen capture attached) because these 2 points are not in my translations.

Details:
- translation keys are: caches_refresh_selected / caches_move_selected
- to reproduce => this menu is displayed when: in cache list, activate "selection mode" then select some caches and finally open the "contextual" menu.

Regards,

![strange final points](https://cloud.githubusercontent.com/assets/1452146/7720082/63a26446-fec9-11e4-9ff6-b245e43b640b.png)

**Comment by samueltardieu** [comment]
The strings are probably too long.

**Comment by Lineflyer** [comment]
I agree. @ldmpub Can you find shorter ones, because I think we can't change that window size in an easy way. Also then on devices with less resolution it might still be too long.

**Comment by ldmpub** [comment]
Ok I will shorten these translations but I'm wondering where does this strange behaviour comes from? Is there a rule to automaticly add points to translations in some cases?

**Comment by samueltardieu** [comment]
I guess that's the default Android behaviour.

**Comment by ldmpub** [comment]
I have never seen this before in any Android app.
Does someone else has an idea: where do these additionnal points are coming from? or in other words: who adds these points to long labels / what is the exact limit ?

**Comment by mucek4** [comment]
There additional points comes from Android itself. Exact limit is probably depended in device size / resolution / font / maybe some things more.

**Comment by Bananeweizen** [comment]
I had a similar issue once: After I upgraded my device to Android 5, this appeared at several places in c:geo. Only after I additionally upgraded the currenlty used _theme_ on the device, those dots were gone.

@SammysHP once had a similar screenshot from the main menu, if I remember right.

**Comment by ldmpub** [comment]
Thank you all for your answers.

**Comment by ldmpub** [comment]
Hi,

I have checked this morning with new build: 
- you were right: the french translated strings were too long
- but the origin of the dots / points seems to come also from c:geo code: instead of dots its meant to be "numbers" => compare the new following screenshot with the one from the first comment
 ![dots are numbers](https://cloud.githubusercontent.com/assets/1452146/7742458/e752292c-ff8f-11e4-96bc-6d908f5628c9.png)

**Comment by mucek4** [comment]
Dots comes from Android. we add those numbers to mark how many caches are in selection.

**Comment by ldmpub** [comment]
Okay.

What I was meaning in my former post: originaly one of the french translations (the 2de one I pointed out) was not too long (in number of caracters) but because c:geo adds parenthesis and number of selected caches this new string exceeded the available place and thus Android adds 2 dots.

**Comment by Lineflyer** [comment]
Please try to keep these strings as short as possible so that also higher number of digits will fit.
