### ISSUE TITLE
check gpx export directory

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4961]
from user group: when the export directory doesn't exist, then the export doesn't work, but there is no useful error message

**Comment by Lineflyer** [comment]
I have just seen that the default value after installation is now empty for that dir. AFAIR it used to be set to a default before...

**Comment by Meybux** [comment]
In the FQA is written : "You can specify the GPX import and export folders in the settings of c:geo: 
Menu → Settings → System → “GPX Export Directory” / “GPX Import Directory” "

This is not possible because there is no button to verrify the change

**Comment by Lineflyer** [comment]
As soon as a directory is selected the OK button should appear.

**Comment by Lineflyer** [comment]
Problem no longer existing.
