### ISSUE TITLE
New target folder for backups

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#4963]
In order to disentangle the relatively important database backup from the less relevant cache file storage in .cgeo, it should be stored in a new location.
The location should still be the external storage (which is sdcard on old Android versions and internal storage on modern ones).
Suggestion:
- (external storage)/cgeo/backup

**Comment by marco-dev** [comment]
@rsudev 
Let me ask you to clarify that "external storage" is the __emulated__ sdcard
* (external storage)/.cgeo for cache directory
* (external storage)/cgeo/backup for database backup files

Correct?

**Comment by rsudev** [comment]
@marco-dev 
Yes and no. As I said, on older devices there is no emulated sdcard and even no internal one (which also was a design option at one time.
Here I refer to the Android Api term, the directory returned by ```getExternalStorageDirectory()```

**Comment by Lineflyer** [comment]
Yes, we have to do that before doing any approachs of migrating the cache directory to other (possibly not user accessible locations which are potentially deleted upon uninstallation).
The suggestion of `getExternalStorageDirectory()/cgeo/backup` sounds like a good starting point, where we could add other files there later on (e.g. GPX export, Field note export) but that another issue.

**Comment by marco-dev** [comment]
We have to keep in mind to move existing backup files on migration.

**Comment by Lineflyer** [comment]
Just to inform that now we released and thus are at the beginning of a new phase on `master`. Might be the right time to do some preparation work.

@marco-dev 
Maybe we should create a Wiki to draft a new directory structure for all non-system filed (like Backup, GPX Exports/imports,...)?

**Comment by marco-dev** [comment]
Added a Wiki RFC.
https://github.com/cgeo/cgeo/wiki/Request-For-Comments#rfc-new-directory-structure

**Comment by Lineflyer** [comment]
@marco-dev 

Good idea.
We started something similar already in the Wiki:
https://github.com/cgeo/cgeo/wiki/Data-storage-structure-of-c%3Ageo

Maybe we just continue there...you could move the last paragraph of the wiki page to there.

You should add GPX import/export directories into the RFC as well.
IMHO those should also go below /cgeo/ then.

**Comment by marco-dev** [comment]
I removed RFC and wrote the content of page 

https://github.com/cgeo/cgeo/wiki/Target-disk-usage-structure

I'm not familiar with the current thoughts about GPX import / export so maybe someone else can add this?

**Comment by marco-dev** [comment]
Do we prefer to change the structure step by step? 

First move backup from <externalStorageDirectory>/.cgeo to <externalStorageDirectory>/cego/backup,
then move dbOnSd file to <externalStorageDirectroy>/cgeo/database, then moving cache directory?

**Comment by SammysHP** [comment]
Do you mean if it should happen in different releases? A user might skip a release, so there is no benefit.

**Comment by marco-dev** [comment]
I guess it is best to move .cgeo to cgeo. But I don't know where to put it best for update.
It is not a database migration and no setting migration.

Where should this change from .cgeo to cgeo go to? 
The next step IMO would be to move backup and db file to subdirectories.

**Comment by Lineflyer** [comment]
@marco-dev 
Sadly I was offline when you sent the question on IRC.

I am unsure if moving will be a fast operation on all devices (i.e. only a renaming) or a long running copy process. IMHO we need to test, or does anyone know?

Additionally if `/.cgeo` is renamed to `/cgeo` we should in any case put a `.nomedia` file into that new base directory as otherwise media scanners will be triggered and all the media data (log pictures) will show up in the users gallery. That should be avoided.

I don't fully understand your question "where to put it best for update". What do you mean with that?

**Comment by marco-dev** [comment]
@Lineflyer My question is where to put the rename code to. We have a DataStorage for db update and settings for settings update. I suggest to add an update function to LocalStorage. But where should I call that update from?

**Comment by Lineflyer** [comment]
This has been implicitly implemented meanwhile during the latest data storage strategy cleanup.
