### ISSUE TITLE
Field notes work only with GC

### ISSUE THREAD

**Issue by Czarodziej** [cgeo/cgeo#4965]
I can't save my offline log to field notes when waypoint of my cache is "OPxxxxxx". Need fix it for opencaching.

**Comment by SammysHP** [comment]
Does it support uploading field notes?

**Comment by Czarodziej** [comment]
For garmin file schema, yes:
http://opencaching.pl/log_cache_multi_send.php?lang=en

2015-05-22 17:21 GMT+02:00 SammysHP <notifications@github.com>:

> Does it support uploading field notes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgeo/cgeo/issues/4965#issuecomment-104688488>.
>



-- 
-------------------------------------------------------------------
Michał Żyłowski
http://mzylowski.pl
tel: 508057316

**Comment by Lineflyer** [comment]
Duplicate of #3941 ?

**Comment by rsudev** [comment]
Exactly. Closing here or there?

**Comment by Lineflyer** [comment]
Here.
