### ISSUE TITLE
Translation Request - need 2 different strings

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#4968]
Hi,

The same string is displayed in 2 different contexts in the app and it's make them hard to translate because: the meaning are slightly different and the available space is also quite different.

See screen captures  attached:
![context 1 - login ok](https://cloud.githubusercontent.com/assets/1452146/7782733/97ce785e-0126-11e5-9c2e-f66630571293.png)
![context 2 - status on line](https://cloud.githubusercontent.com/assets/1452146/7782734/97d18846-0126-11e5-8754-cd298a1e93ea.png)

- Context 1 in parameters: results displayed when checking login/password
- Context 2 on the home: connection status with gc.com.

**Comment by Lineflyer** [comment]
Do we really need to separate these strings. 
I would instead suggest a shorter string in general. More or less both field should give the same information, i.e. that the Login was OK.

**Comment by ldmpub** [comment]
I was expecting feedback from other translators but I'm Ok to set a unique / short label (I have done it in the french translation with a word equivalent to "Connected").
