### ISSUE TITLE
Inconsistencies between lists

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4969]
Starting with 2015.05.22-NB1 I seem to have extreme inconsistencies on my lists of saved caches.

Example:
- I open a list named GdH with 15 caches
- I open one of them and close it again
- Returning to the list I do see that all caches shown belong to the history list but not my list
- The header still shows GdH as name but a count of 81 caches (which is the amount of caches in the history list)
- Leaving and reentering the lists solves it

Trying to explitcitly reproduce it was not succesfull, but it keeps happening in various ways.

**Comment by kumy** [comment]
Confirmed

**Comment by kumy** [comment]
I can reproduce it by :

* open stored caches lists activity
* select "History" list
* select another list
* open cache
* press back

**Comment by kumy** [comment]
I think this comes from
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/CacheListActivity.java#L1348-1348

This update the Intent, and is never set back

**Comment by kumy** [comment]
PR #4983 opened.
This could fix the issue for the next feature release.

**Comment by kumy** [comment]
@Lineflyer reopen for testing

**Comment by Lineflyer** [comment]
Tested OK with the given scenario above in 2015.08.23-NB.
I will keep an eye on the consistency of lists with coming NBs as well but right now it looks ok.
