### ISSUE TITLE
Visual feedback for logging activity

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#4970]
Some people do not know how to drop a TB because they do not see the list under the log text input field. Some sort of visual hint (aka loading circle) might help in this situation.

**Comment by Lineflyer** [comment]
You mean a loading circle while the list is being populated?
That would not help to find it if it is already loaded....wouldn't it?

**Comment by mucek4** [comment]
Problem imo is keyboard as it covers TB list.

**Comment by SammysHP** [comment]
> You mean a loading circle while the list is being populated?

Correct. Currently there is no indication whether something is loading or not.

**Comment by kumy** [comment]
Extracted from #5412, the calls to `super.onCreate()` in `LogTrackableActivity` and `LogCacheActivity` call a constructor which doesn't initialize progress indicator. Moreover, progress indicator in `LogCacheActivity` is never shown.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Progress indicator is shown for GC-trackable logs and GC-cache logs in 2016.02.22-NB.
Looks good to me, further implicit field tests will be done until next feature release. Will open a dedicated issue if I do see a problem.
