### ISSUE TITLE
C:geo will not recognize my premium member upgrade

### ISSUE THREAD

**Issue by willingheart1** [cgeo/cgeo#4972]
I have tried checking login and re-entering username and password in settings, uninstalling and reinstalling c:geo app, refreshing geocaching.com, rebooting my phone, and maybe more, and it still refuses to show me premium caches and says they are only open to premium members.

**Comment by Lineflyer** [comment]
Can you please post the system information shown in Menu - About c:geo - System here?

When you go to Menu - Settings - Services - geocaching.com and select "check login", what is the response?
Is the menu "options for basic members" in that menu selectable or "greyed out"?

**Comment by Lineflyer** [comment]
Closed due to lack of feedback.
Issue not reproducible for me.

**Comment by josandgeo** [comment]
Mine is the same.....
--- System information ---
Device: SM-G930F (heroltexx, samsung)
Android version: 7.0
Android build: NRD90M.G930FXXU1DQEF
c:geo version: 2017.07.24
Google Play services: enabled - 11.3.02 (448-161239932)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (11.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (11.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (0 B free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (148.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (No Login information stored)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by SammysHP** [comment]
>  geocaching.com: Not logged in (No Login information stored)

**Comment by josandgeo** [comment]
I am logged in to geocaching.com and premium member

**Comment by SammysHP** [comment]
The system information dump says that you haven't provided your credentials to c:geo. Please go to *Settings → Services → geocaching.com* and select "Authorize c:geo again".

**Comment by josandgeo** [comment]
Have logged in in geocaching .com.
C:geo says enter credentials with username and password. Have entered both
my geocaching credentials and checked authentication but keeps saying
failed...unknown error....

Kindest Regards

John

**Comment by Lineflyer** [comment]
@josandgeo Please kindly follow the instruction in our [FAQ](http://faq.cgeo.org/#login-failed) to reset the login and try again.

**Comment by Bananeweizen** [comment]
There was a [server outage yesterday](https://twitter.com/GoGeocaching/status/892837800256708608), and I bet this was causing the issue.

**Comment by josandgeo** [comment]
I think you are correct.....today all is ok.
Thx for your cooperation.

Kindest Regards

John
