### ISSUE TITLE
Request to gc.com tile server sent for caches from unknown sources  (e.g. lab caches)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4976]
2015.05.26-NB:

- Import lab caches from Main GIGA to a new list
- Open list and select Map icon to show a list
- Click on one of the lab caches

Result:
In fact we send a request to the GC.com tile server for it which should not happen because 
a) The cache is saved and has never been loaded from the server
b) It is not even a valid GC-cache
c) Live mode is not enabled on a map of stored caches

If the stored caches are not lab caches but normal GC-caches I do not see any request.

Log:
```
18:06:36.364 Debug cgeo 16964  [Thread-24861] GET http://tiles.geocaching.com/map.details?i=ALTES+RATHAUS+%28STELE%29-MAINZ+GUTENBERG+2015+-+DAS+IST+GIGA&_=1432656427925&app=cgeo
18:06:36.804 Debug cgeo 16964  [Thread-24861] 200 (383 ms) GET http://tiles.geocaching.com/map.details?i=ALTES+RATHAUS+%28STELE%29-MAINZ+GUTENBERG+2015+-+DAS+IST+GIGA&_=1432656427925&app=cgeo
```

**Comment by Lineflyer** [comment]
Setting label "Medum" as we get the same question via support mails and people suffer from the resulting delay when trying to open the caches.

**Comment by Lineflyer** [comment]
More complaints received by users who I met on Luxemburg MEGA for this.
Those users have been in roaming mode (no data connection) which leads to a delay of quite some seconds when clicking on an offline stored lab caches for that event.

**Comment by Lineflyer** [comment]
More complaints coming in on support mail:
In fact this is not only happening for lab caches but it seems for all unknown caches (e.g. also self created GPX with waypoints in it).

Renaming the issue accordingly.

Without knowing the code at that point, it seems that the "filter" used to check for which caches a request to gc.com shall be send is faulty in a way that it lets cache from unknown sources pass instead of dropping it for those. That should be easy to solve, shouldn't it. 
I would be thankful if someone can take a look into it.

**Comment by kumy** [comment]
I've quickly looked at the issue, and proposed two way of fixing.
May someone have a look at those commits? Which one do you prefer?

https://github.com/kumy/cgeo/commit/800f15b6507fd5538c895325dae21820a7d01018
https://github.com/kumy/cgeo/commit/3c8bf180c02571d2f5045e7877f4b4dcae74af70

**Comment by Lineflyer** [comment]
@samueltardieu 
Any opinion from your side regarding the proposals by @kumy ?
I cannot judge the code based things however the first one is quite straight forward.

**Comment by samueltardieu** [comment]
I prefer https://github.com/kumy/cgeo/commit/8c5dcd3128c7eb7a3242151c36b156b48c331f27 with maybe `size() == 0` replaced by `empty()` if that is available.

**Comment by kumy** [comment]
Thanks, I'll update patch this evening.

**Comment by kumy** [comment]
@Lineflyer assigning for testing

**Comment by Lineflyer** [comment]
With 2015.07.17-NB1 I do no longer see requests send for lab caches.
The normal requests for GC-caches are still send. Looks fine for me to merge into release.

**Comment by Lineflyer** [comment]
@kumy Is this patch mergeable to `release`? That was the reason why I reassgined you. If not, please feel free to close this (as it has been fixed on master).

**Comment by kumy** [comment]
@Lineflyer diff should apply on `release`. To merge into release, should I `cherry-pick` the commit, or is there a better way?

**Comment by rsudev** [comment]
@kumy Normally the flow for a bugfix to be expected on release is, to develop it on a branch created from release and first merge to master for testing. Then it can be easily merged back into release anytime.
When this was not done (for whatever reason), cherry-pick onto release and then merging into master (resolving any upcoming conflicts) is the only way.

**Comment by kumy** [comment]
@rsudev thanks. I didn't mind this would be included in `release` when coding, that's why I've worked on `master`. @Lineflyer Maybe we could in the future set the `milestone` field accordingly on bug creation?

I'll try the method you mentioned.

**Comment by kumy** [comment]
@rsudev done. Could you please check if I've done things right? (Hope that's the case ;))Thanks

**Comment by rsudev** [comment]
@kumy Everything looks fine! Thank you :)

**Comment by Lineflyer** [comment]
@kumy I don't think setting the milestone according to the desired branch is meaningful. At the end the one debugging and fixing it has to decide whether it is suitable to be based on `release` or not. We probably can not judge this by the symtpoms itself.

Here is some info about the normal working mode we apply:
https://github.com/cgeo/cgeo/wiki/How-to-get-a-bug-fix-into-the-release

So fixing bugs should be based on `release` except the bugfix ends up in a larger code rewriting or introduction of new features/functions whereas it is considered too dangerous without a longer period of testing (which is more likely to be done with `master`).

**Comment by kumy** [comment]
Ok, thanks both.

**Comment by kumy** [comment]
I forgot. I didn't update the `changelog_*.xml`. Am I right if I add the line only in `changelog_release.xml`?

**Comment by Lineflyer** [comment]
Correct.
