### ISSUE TITLE
Link to cache from Groundspeak newsletter email does not work

### ISSUE THREAD

**Issue by bocktus** [cgeo/cgeo#4980]
The link to a cache from the Groundspeak newsletter email on recent geocaches does not work.
here is an example link from the mail:
http://coord.info/GC5VV08?utm_source=newsletter&utm_medium=email&utm_content=caches&utm_campaign=5-26-15

**Comment by SammysHP** [comment]
Duplicate of #4719. The fix will be included in the next release.
