### ISSUE TITLE
OpenCaching authorisation fails on Jolla

### ISSUE THREAD

**Issue by kattalunikes** [cgeo/cgeo#4981]
On Jolla (Sailfish 1.1.4.29), i can't authorize c:geo to use opencaching.

When I press the "Starte Authorisierung"/"Neustarten"(=restart) button the web browser opens and asks me, if i want to authorize c:geo. I click yes, and openCaching remembers that c:geo should be authorized. The app itself still tells me it was not authorized to use opencaching.de

**Comment by Lineflyer** [comment]
Did you check the possible problems mentioned here?
http://faq.cgeo.org/#6_73

Especially the correctness of date and time settings on your device?

**Comment by rsudev** [comment]
I would rather assume that the Android layer in Jolla does not support our callback urls, so the server response never reaches c:geo,

**Comment by Lineflyer** [comment]
Closed due to lack of feedback.
