### ISSUE TITLE
Date selector shows wrong week

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4982]
From support mail and I can reproduce it:

![2015-05-22 00 01 57](https://cloud.githubusercontent.com/assets/949669/7840264/d2ef62fe-0496-11e5-812b-169295f5c0d0.png)

Could still be a device problem as I use the very same device on same version.
Can someone please crosscheck with another device?

--- System information ---
Device: GT-I9505 (jfltexx, samsung)
Android version: 5.0.1
Android build: LRX22C.I9505XXUHOD5
Cgeo version: 2015.03.31
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: false
Map strategy: fastest
HW-acceleration: enabled (default state)
geocaching.com: not logged in (Anmeldung…)
System language: de_DE
Installed cgeo plugins: calendar
--- End of system information ---

**Comment by kumy** [comment]
Works fine here.

--- System information ---
Device: One M8 (cm_m8, htc)
Android version: 5.1.1
Android build: cm_m8-userdebug 5.1.1 LMY47V 7217217ff6 test-keys
Cgeo version: developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins:  none
--- End of system information ---

**Comment by Lineflyer** [comment]
AFAIK we call some android standard thing here and this dialog is not part of c:geo, isn't it? 
This would sound like it is most probably a device specfic proble?!

**Comment by samueltardieu** [comment]
No problem for me either.

![screenshot_2015-05-28-20-30-20](https://cloud.githubusercontent.com/assets/44656/7867987/8d1ff89a-0579-11e5-961a-8df4ee3bdd08.png)

**Comment by Lineflyer** [comment]
Seems to be a device specific problem. Wont fix.
