### ISSUE TITLE
Cache not added to history when logged in a particular scenario

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4984]
Version 2015.03.31.

I was not able to reproduce it with 2015.05.26-NB although I am not aware that anything changed in that area.

Here is a video showing the problem (provided by a user and published with his approval):
https://www.dropbox.com/s/1v2i0xtq5z9ti8a/Offline.mp4?dl=0

Could be related to #4086

**Comment by Nicole1338** [comment]
I stumbled today over this bug. I imported an pocketquery and I didn't open the complete cache page. I just opened the overview (the small popup if you click on an cache on the map view) and then i pushed "One click offline log"->"Found It" or "One click offline log"->"Log Visit->"Save offline". A few minutes later I get back to the history and the last caches I logged didn't show up there.
Now I'm at home and I tried to reproduce this, but it worked correctly. I'm not sure why, but a reason could be that I haven't a mobile connection on the road..

I'm using the latest nightly build (2015.06.14-NB-8ec5465) on an Google Nexus 5 with Android 5.1.1

Best Regards,
Nicole

**Comment by Lineflyer** [comment]
Could reproduce this issue with current release 2015.09.28.

I made an observation (which was IMHO already reported here somewhere) which might give the cause of this problem:
If I store an offline log while the cache details are opened the status is changed to "Logged offline (date)". These caches seem to show up normal in the history.
If I open a cache identified as missing in the history the status shows "Logged offline" but the date which normally shows up as well is missing.
That looks like to be the reason it is not in the history, beacuse the log date information is not stored!

Can someone use this info to find our why this happens?

**Comment by Lineflyer** [comment]
Here it was mentioned already: https://github.com/cgeo/cgeo/issues/4086#issuecomment-131582684

**Comment by Lineflyer** [comment]
Looking again at this issue I think we can close it:
1. The video is no longer available
2. The additional info provided by @Nicole1338 is the problem described in #4086 
3. My addition is also covered in #4086
