### ISSUE TITLE
Back from waypoint editor should not save automatically

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4985]
I know we discussed this briefly somewhere.
Now I crosschecked with current release and new relase candiate (with modified waypoint layout):

- On the current release 2015.03.31 pressing back while editing the waypoint discarded the changes.
- With 2015.05.29-RC pressing back will save changes made

I think we should either adopt the old working mode (don't save on back) or preferably show a dialog with "Save" or "Discard" options.

**Comment by Lineflyer** [comment]
As asked in #4792 I trapped into one problem with that today:
I stored a new WP and saved it. Afterwards I opened it again to edit the coords. After editing I realized that I opened the wrong WP for editing, so I pressed back and it was saved and has overwritten coords I would have needed ...

**Comment by konpapa** [comment]
Hi I just thought I'd give this issue a try. Please check the commit and give me some feedback if you'd like. 
By the way I was thinking if the same behavior (keep a dialog box or not save changes) should be used for the home button as well.

**Comment by Lineflyer** [comment]
@konpapa I may be not the right one to judge code quality and correctness (as I am no programmer myself) but at least one remark: For all strings please use strings which can be localized instead of direct text strings in the code.

**Comment by rsudev** [comment]
I have created an implementation which does not save on leave, but shows a toast if changes are discarded. This seemed to me a feasible balance between no feedback at all and pestering the user with unwanted dialogs.
Nevertheless this requires a new string...
@Lineflyer Should I put this to release for testing in a new RC?

**Comment by Lineflyer** [comment]
@rsudev: Yes, please. 
Regarding the string: As it is only a toast which does not require user interaction, I am even fine with having it untranslated in some languages.
