### ISSUE TITLE
Avatar no longer shown on "Check Login" on some devices

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4986]
Strangely with 2015.05.29-RC the user avatar is no longer loaded when using the function "Check Login" in Menu - Settings - Services - geocaching.com.

With production release 2015.03.31 it is working normal (also tested today...so not website change related)
Edit: Test with production release was done on another device (see comment from 03.06.2015).

Log does not show any error.

**Comment by samueltardieu** [comment]
I had noticed this as well some times ago. It may be due to the increase of SDK version.

**Comment by samueltardieu** [comment]
On my Nexus 5 / CM 12.1 / Android 5.1.1, I get the avatar.

**Comment by Lineflyer** [comment]
I happening for me on my Samsung S4, Android 5.0.1

**Comment by Lineflyer** [comment]
When testing this I do see a `304`error in the log, which should mean, that the picture is already locally stored. Still it is not shown to me.

```
09:36:12.597 Debug cgeo 25380  [network-5] GET http://www.geocaching.com/my/
09:36:13.367 Debug cgeo 25380  [network-5] 200 (734 ms) GET http://www.geocaching.com/my/
09:36:14.568 Debug cgeo 25380  [network-1] GET https://img.geocaching.com/user/large/e3afdf64-7188-464e-ac80-8474501d9352.jpg
09:36:16.098 Warning cgeo 25380  [network-1] 304 [Not Modified] (1580 ms) GET https://img.geocaching.com/user/large/e3afdf64-7188-464e-ac80-8474501d9352.jpg
```

If I manually delete it from `/.cgeo/shared` and try again the picture is loaded again (but still not shown):
```
09:38:03.605 Debug cgeo 25380  [network-10] GET https://img.geocaching.com/user/large/e3afdf64-7188-464e-ac80-8474501d9352.jpg
09:38:05.679 Debug cgeo 25380  [network-10] 200 (2028 ms) GET https://img.geocaching.com/user/large/e3afdf64-7188-464e-ac80-8474501d9352.jpg
```

**Comment by Lineflyer** [comment]
Retested this on my device (Samsung S4, Android 5.0.1) with the current market release 2015.03.31. Also on this device the image is requested and stored locally but not shown.

So at least this is no regression but something else device and/or Android version depending.
Removing "Regression label" and changed title.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Solved implicitly with the new UI design for authentication.
Avatar now shown embedded in the settings.
