### ISSUE TITLE
Question / Improvement: is there a way to check its personal TB/GK inventory within cgeo?

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#4989]
Hi,

I'm wondering if it's possible for a user to check is personal TB/GK inventory within the apps?
As far as I know yet, you could only simulate to log a cache and there you see inventory.

Thanks,

**Comment by kumy** [comment]
Isn't it the same as #3695 which is a duplicate of #420?

**Comment by ldmpub** [comment]
I see, it's an improvment request and there is already issues on this topic => I close this one.
