### ISSUE TITLE
GitHun issu usage: is there a way to subscribe to a tag?

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#4990]
Hi,

I want to be emailed each time tag "Translation" is added to an issue. Is it possible in GitHub ?

regards,

**Comment by Bananeweizen** [comment]
Nope, unfortunately it isn't. Notifications are only for new repos, conversations, and issues. See your notification settings in the account details. Maybe you could try to use a website change monitor with https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3ATranslation

**Comment by ldmpub** [comment]
Thanks for your answer. I will try to monitior this page using "VisualPing" service.
