### ISSUE TITLE
No SNI support for network requests

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4991]
The current Apache httpclient library doesn't support SNI connexions.

**Comment by kumy** [comment]
@samueltardieu assigning to you as you plan to experiment with OkHttp

**Comment by Natureshadow** [comment]
> The current Apache httpclient library doesn't support SNI connexions.

So? What would c:geo need it for?

**Comment by kumy** [comment]
To be able to connect with services that rely on SNI, like GKM over ssl :)
