### ISSUE TITLE
Warn about "don't keep activities" settings

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4995]
Since #4834 I've enabled "don't keep activities" settings in System -> developer options

Last time I opened "Locus", I got this warning.

Should we implement something similar in c:geo?

![screenshot_2015-05-28-12-37-50](https://cloud.githubusercontent.com/assets/176794/7898556/e11c2d7a-0703-11e5-9905-f6b1219eed12.png)

**Comment by SammysHP** [comment]
IMHO the user should know the consequences when he enables that option.

**Comment by kumy** [comment]
In #4834 that was not the case.
This may "reduce" user complaints, no ?

**Comment by SammysHP** [comment]
> PS: of course these tests have be done with **developer options** > Don't keep activities in memory set to ON.

That says everything: The average user won't enable that option. It's more for testing to see if the developer took care of saving all information when the activity is destroyed.

**Comment by Lineflyer** [comment]
This is a developer options...whoever activates it should be prepared for unpredictable consequences. So I wouldn´t implement any warnings...otherwise we also have to include several more of these which makes so sense at all for 90%+ of our users.

**Comment by SammysHP** [comment]
Ok, let's close this issue. That option is designed to create trouble. :)
