### ISSUE TITLE
Relocate cgeo-RC.apk and cgeo-release.apk to download.cgeo.org

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5000]
While all nightlies are already available on download.cgeo.org we have to adapt the upload script also for cgeo-RC.apk and cgeo-release.apk to have it still available once the new website is live.

@mucek4 or @rsudev Can you do that configuration on the CI?

**Comment by mucek4** [comment]
I'll see what shall be done.

**Comment by mucek4** [comment]
cgeo-RC and cgeo-release is done. Anything else?

**Comment by Lineflyer** [comment]
Not that I am aware of.
Thanks!
