### ISSUE TITLE
Update URLS in send2cgeo script

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5007]
`@downloadURL` and `@updateURL` need to be updated to target the github repo directly.
We also applied this strategy to the new website.

This would mean that release is directly controlled via commit to master.

**Comment by Lineflyer** [comment]
Thinking about it:
Wouldn't it be wise to have all send2cgeo stuff in a separate repo, which also has two branches (like master and release)?  Afterawards we just link to the script on release branch.

Doing so we would have dedicated version control for send2cgeo.

Comments?

**Comment by SammysHP** [comment]
As I suggest several times already…

For example on our mailing list or in our IRC channel.

**Comment by Lineflyer** [comment]
Just do it?
Or was there any objection to that time...I honestly don't really remember-

**Comment by SammysHP** [comment]
e.g. https://groups.google.com/forum/#!searchin/cgeo-dev/clean$20up/cgeo-dev/cDca5juKwKs/AegUDjZ0HMUJ

**Comment by Lineflyer** [comment]
While I understand from that thread that it might be a technical problem for the plugins I guess it won't be a problem for the send2cgeo stuff...
Shall we split that into another repo?

**Comment by Lineflyer** [comment]
So, here would be my proposal:

- [ ] Merge #5045 
- [ ] Split up send2cgeo in another repository
- [ ] Change `@updateURL` and `@downloadURL` in script
- [ ] Change URLs on web page
- [ ] Raise version number of script
- [ ] Place the new version of the script to the old URL  https://send2.cgeo.org/send2cgeo.user.js for a last time

Will this work?

**Comment by Lineflyer** [comment]
Issue will be transfered to cgeo/send2cgeo
