### ISSUE TITLE
Sharing has unexpected results

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5010]
Similarly to a bug we discussed long ago I again experience funny stuff when using the share menu. When I select the "show all" from the android share menu provider then locus opens with the cache.
This is surely a faulty way through the switch case of the onOptionsItemSelected of the cache details activity.

**Comment by akkatracker** [comment]
This bug has been fixed through another issue. 

@Lineflyer can we close?

**Comment by pstorch** [comment]
The other/similar issue was #5643 and has been fixed.
