### ISSUE TITLE
Customizable icon sizes

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#5012]
On some devices cache icons are shown rather large, taking up much of the mapspace, especially when you have many caches in your lists (device tested on is Samsung Galaxy Note 3).

Wish is to be able to switch between (eg) two different icon sizes - "large" (= todays icon size) and "small" (about half the size). This would be very helpful for better orientation on packed maps.

**Comment by Lineflyer** [comment]
Please kindly refer to #4098 for a similar approach.
