### ISSUE TITLE
High battery usage even on GPS turned Off, and when not using C:GEO

### ISSUE THREAD

**Issue by amikot** [cgeo/cgeo#5014]
Im using C:GEO from weeks on my mobile (Huawei Ascend G510), and few days ago I installed C:GEO on my wife's mobile (Motorola Moto-E). She reported high battery usage of something, but I did'nt check that then. Last evening I fully charged up bettery of my Huawei and after night i realised that battery is almost empty again, and 40% of that consumption is caused by C:GEO (Using GPS). Durring night I had localisation switched to inacurate (GPS off), and C:GEO was not closed (was not on screen - is there any "exit" button?)

I tried to set diferent options in C:GEO (use or not Google Play Services, save or not battery when sleep mode etc.) and C:GEO is showing on screen`s bottom that GPS is off but it didnt helped ... battery usage menu in android is still schowing huge consumption of C:GEO app and its consumed by GPS

C:GEO that im using is version: 2015.03.31

On Huawei im using Cyanogen Mod 11 - Android 4.4.4
On Moto-E my wife is using Branded by Motorola Android - I guess its 4.4 or something. 

Regards
Albert

**Comment by SammysHP** [comment]
Please uninstall c:geo and compare battery runtime.

Sometimes I can see c:geo with high battery usage in the battery stats myself but that's simply wrong. There is no way to measure the exact battery usage per app. It is only possible to guess (by CPU time, sensor usage etc.). Sometimes Android thinks that c:geo is still registered for GPS but it isn't (no icon in the status bar). Also "c:geo used 60% battery" never reduced my runtime.

**Comment by amikot** [comment]
After uninstalation battery usage looks diferent. Before there was Display, and than C:GEO (Using GPS) ... amd than the rest.
Now I have Display on top (80-90%) and than System, Google Services and rest.

After reinstalation problem gone. That looks realy strange. 
Anyway, its strange that there is no option "exit" in c:Geo - to switch it off at all.

**Comment by SammysHP** [comment]
I'm not talking about the shown values but about the real battery runtime. It is possible that it shows c:geo with 80% and the battery will run the same time as without c:geo installed at all.

This is a known bug in Android and c:geo, but only cosmetic.
