### ISSUE TITLE
Hint of a cache not shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5016]
From support mail for version 2015.03.31, reproducible also in 2015.06.03-RC1

http://coord.info/GC5K34R

This cache has hint "<--4"
In cgeo it doesnt show up.(empty space in field Hint)

**Comment by SammysHP** [comment]
See #1135 and #2757.

**Comment by samueltardieu** [comment]
The HTML generated by geocaching.com is invalid:

```html
<div id="div_hint" class="span-8 WrapFix">
            <-- 4</div>
```

**Comment by SammysHP** [comment]
Urgh… Firefox Inspector fixes that on-the-fly:

![20150608_164222](https://cloud.githubusercontent.com/assets/922874/8037328/6dbe9164-0dfd-11e5-9d04-a9bafb788bd8.png)

That's why I haven't noticed it. Suggest to close it with "won't fix".

**Comment by Lineflyer** [comment]
Won't fix then.
