### ISSUE TITLE
Raise target sdk for plugins

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5018]
Main issue: the READ_CONTACTS permission is interpreted as requesting CALL_LOG as well, if targetSdk is < 16, and we don't want this permission for our plugin.

**Comment by Bananeweizen** [comment]
I was also wondering several times already if we should have the exact same target, compile and minimum SDK. The only drawback I saw: legacy users cannot install the plugins anymore.

**Comment by rsudev** [comment]
I don't see an immediate necessity to raise the minSdk, as the excess permissions are bound only to the targetSdk.

**Comment by UniQP** [comment]
Just stumbled about the minSdk when looking for some code cleanups. c:geo currently has minSdk=9 (providing `String.isEmpty()`) and the plugins have minSdk=7 (not providing `String.isEmpty()`). In my opinion, it makes no sense to have a lower minSdk for the plugins than for c:geo itself.

**Comment by Lineflyer** [comment]
What ia the minSdk of cgeo-legacy?

**Comment by UniQP** [comment]
@Lineflyer It's also inconsistent: cgeo-calendar: 4, cgeo-contacts: 5, cgeo: 7. Since cgeo-legacy is a own branch, updating minSdk on master has no direct influence on cgeo-legacy.

**Comment by Bananeweizen** [comment]
To me it is fine to update all plugins to 9. 9 is already rather old, and I estimate the number of _plugin_ users, which cannot upgrade to that Android version anymore to be a single or two digit number. :)

**Comment by Lineflyer** [comment]
As the `legacy` branch\version has been depublished from GooglePlay it should be OK to align minsdk of all plugins to minsdk of c:geo itself.

**Comment by UniQP** [comment]
@Bananeweizen Can you take care of that?
