### ISSUE TITLE
Add ability to search address and goto that address on livemap

### ISSUE THREAD

**Issue by opperpanter** [cgeo/cgeo#5019]
My usecase:
- I have different locations at which I geocache, sometimes far away for a holiday.
- I save lots of caches offline into c:geo, in different lists.
- I use livemap to explore the caches in a certain area.
- I have the live function disabled, so I see only offline stored caches.

I'd like an easy way to enter an cityname and jump to that location on the livemap quickly.

Possible solutions I see:
- Add city/address search to Goto screen && add livemap button/menu item to activate livemap
- Add menu item on livemap to "search address".

Current "workaround":
- Open livemap
- Zoom out
- Scroll close to desired location
- Zoom in
- Scroll some more
- Zoom in more
- Scroll some more
- Zoom in
- ...

Any thoughts?

**Comment by Lineflyer** [comment]
It should be possible by:
- Search for city/adress
- On the result list press the map icon in the titlebar
- Select the map menu -> Enable live

**Comment by opperpanter** [comment]
Comes close, but:

- Will use data to retrieve search results, while I already have the caches offline.
- Will use data because switched to live mode.
- Will show caches that I haven't stored and maybe even don't want to see.

**Comment by Lineflyer** [comment]
Oh, offline case...sorry, missed that part of your explanation.

Ever thought of just having those offline lsits divided by geographical regions?
That would mean you just need to map the list of the location you want to see on the map.

It is impossible to search for an adress when offline, only search based on coords would be meaninful in this case (but would need to be implemented...at the moment all searches in the search menu are purely online related).

The idea to add city search to Go to... is interesting indeed (besides that it needs online connection as well). However we are currently unsure what to do with the Go to... menu. Last idea was to transform it to quite the same as the waypoint tab of a cache (whereafter your proposal would not be an option). Mmh.

**Comment by opperpanter** [comment]
I have considered seperating the geograhic areas into separate lists, but found it too much effort to maintain. Also some areas are adjacent/overlapping/etc.

Maybe I should look to it more in general. Searching by address/city is just a solution. Bookmarks on the (live)map may be another solution. Just looking for a quick way to jump to a certain location on the live map (but with live disabled haha).

**Comment by Lineflyer** [comment]
> Just looking for a quick way to jump to a certain location on the live map (but with live disabled haha).

As I said:
Search by adress, and open map from the result. If you then just enable live and disable it again afterwards it will show all your saved caches as well and then stop updating the map.

**Comment by opperpanter** [comment]
Thanks, that comes close. Still think it might be  a useful addition to make it easier?

**Comment by opperpanter** [comment]
Just tried it, but enabling live will *not* show saved caches. It shows the 20 caches from the search result and then starts loading caches from GC.com

**Comment by opperpanter** [comment]
Or maybe  it does but only after a while.

**Comment by jonas-koeritz** [comment]
The "Map" action should just jump to the location you search for in the first place. If you search for a city and select the map button you just jump to your current location on the map.

**Comment by Lineflyer** [comment]
Recently implemented (see #6400)
