### ISSUE TITLE
Navigate -> WhereYouGo option missing if cache is found

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5023]
Unverified, taken from FB:

> wherigo option is available when the cartridge is not yet completed. Else this option is not there.

**Comment by SammysHP** [comment]
> wherigo option is available when the cartridge is not yet completed

How can c:geo know if the cartridge is completed?

**Comment by Lineflyer** [comment]
I guess this refers to found status of the cache (my assumption) therefore I selected the title of this issue.
However I need to check, therefore "Unverified". Assigning myself.

**Comment by Lineflyer** [comment]
Not reproducible.
Navigation option is visible in cache details and cartridge is downloadable in WhereYouGo.
