### ISSUE TITLE
View all waypoints of a cache in an external app

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5024]
From support mail:

Currently I can map a list of caches in an external app (like Locus or maps.me). Great feature!
(Map - Menu - Show on map - <Select the app>)

The same thing should be possible from the waypoint tab of a cache to get all its waypoints shown on the external app.

**Comment by SammysHP** [comment]
When you choose Locus the cache and all waypoints should be included (using the navigate function on the cache itself).

**Comment by Lineflyer** [comment]
The user was especially interested in maps.me where this does not seem to work in this scenario (but does work via the show on map menu from a cache list).

**Comment by madankumarbaskaran** [comment]
I just tried to get waypoint in maps.me, selected waypoint - Navigate - Maps.me; waypoint is shown in maps.me. Is this what user wants?

**Comment by SammysHP** [comment]
No, the original request was to show all waypoints of a cache on the external map. Which is not possible unless there's a special API. For Locus it should be already implemented.
