### ISSUE TITLE
Combine send2cgeo scripts into one script

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5025]
I just recognized that we did not yet officially publish the send2cgeo script for OC.
While thinking about how to do that, I had the idea that there might be no need to have to seperate scripts but just one which triggers for both websites. Is that technically possible?

Having a combined script would minimize the effort (one version handling, one send2cgeo.html page on the website, etc.).

**Comment by mucek4** [comment]
I think it is possible. Right now we have 1 script that serves map and search.

**Comment by rsudev** [comment]
The initial script for gc.com was created by taking advantage of the node.js-code already loaded into the page by gc.com. As this is not the case for the opencaching sites, the oc-version was somewhat hacked together without using these functions.
A common version would in my book have to refrain from using node.js, which might make some things a little more complicated, but still doable.
and BTW - we have three scripts...
The one for sites deriving from the oc.pl code (oc.pl, oc.nl) is different again.

**Comment by Lineflyer** [comment]
This issue was moved to cgeo/send2cgeo#3
