### ISSUE TITLE
Read cache notes from GSAK

### ISSUE THREAD

**Issue by Willabee** [cgeo/cgeo#5026]
It is good that we can use corrected coordinates made on the GC Cache page in PQ's or updated when refreshed (The little red indicator makes these very visible on the map. It would be nice if all corrected coordinates from PQs had this indicator without the need to refresh in c:geo.

I also make a lot of notes on the GC cache page. In GSAK, these notes are available through the 'GcNote' database field. It would be a great feature to be able to see this data when viewing the cache in c:geo. Is this possible?

**Comment by rsudev** [comment]
If you download the cache with c:geo, the personal notes are available for sure (and can also be edited and uploaded). Not sure of they are part of a PQ and if we load them from there if.

**Comment by Willabee** [comment]
Thanks. I did not know that. My next step is for GSAK to download them as part of exported PQ.

**Comment by SammysHP** [comment]
Regarding your first paragraph: There's no indication in the PQ if the coordinates are corrected or not.

**Comment by Willabee** [comment]
Would I need to approach gc.com to try and get them to add a corrected coordinates indicator and the GC Notes to the XML .gpx file so that apps like c:geo could extract the information?

**Comment by Willabee** [comment]
A chap has just sent me a GSAK macro that copies the GC Note (Downloaded into GSAK directly using the GC API) to create a new log entry as the first log (and does not duplicate it if the macro is re-run).

This means you can export the GPX file to c:geo (or any other app or GPSr) and it will have the corrected coordinates and the Note available when you check the logs.

A great solution for my particular problem.

**Comment by Bananeweizen** [comment]
You don't need to create fake logs in GSAK. c:geo understands the gsak:GcNote field during import of a GPX and populates the personal note with it. c:geo also understands the GSAK specific fields for changed coordinates. So as long as you export the GPX with the GSAK extensions, everything will be fine.
