### ISSUE TITLE
Watchdog fails for OC-sites

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5028]
The job keps failing constantly since yesterday but the websites seem up and running from my users perspective:

```
	Websites which failed testing

    OpenCachingDE
    OpenCachingNL
    OpenCachingPL
    OpenCachingRO
    OpenCachingUK
    OpenCachingUS

```

**Comment by rsudev** [comment]
I took a preliminary look, but could not deduce anything.

**Comment by rsudev** [comment]
Locally it works, so it seems an issue with the environment. @mucek4 Can you have a look at logcat? Or can I see that?

**Comment by Bananeweizen** [comment]
I assume it might be a similar issue like 2 weeks ago. To many open files on the host of the emulator.

**Comment by mucek4** [comment]
Yeap. Server reported to many open files and crashed emu. Looks like new bug in emu. As this started from last update.

**Comment by Lineflyer** [comment]
Running again, so we can close here?

**Comment by mucek4** [comment]
Probably.
