### ISSUE TITLE
Use Google Cloud Test Lab

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5033]
While using the Play Console I noticed a new offer to use a cloud test service.
From what I have read it offers free testing on 20 physical devices and provides a report back to the developer account. It is combined with the alpha/beta channels on GooglePlay (so tests will probably run as soon as an APK is placed there).

That could be a useful additional test (although I am not sure how deep this service can test by using random clicks in the app).
There is a possibility to "early sign up" for this upcoming service. Shall we do that?

https://developers.google.com/cloud-test-lab/
http://arstechnica.com/gadgets/2015/05/google-announces-the-cloud-test-lab-a-free-automated-testing-service/

**Comment by Bananeweizen** [comment]
That sounds nice. However, this doesn't come free for us. We have to find ways to enable testing without actually interacting with the geocaching platform.

**Comment by Lineflyer** [comment]
We can anyway just try it out to see what happens on these testing machines even without an account.

**Comment by Lineflyer** [comment]
Outdated. Meanwhile we at least have basic device testing for the beta channel free from Google.
