### ISSUE TITLE
Regular crashes on Sony Xperia devices on Android 5+

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5034]
There seem to be many users (judged by the amount of support mails and bad GooglePlay ratings) having stability problems with c:geo after upgrading their devices to Android 5.0.x.
This seems to be an issue which is maybe independend of #4921 

For some of them the problem seems solved after a factory reset, but a lot others keep having problems. I have the chance to get a Sony Xperia Z3 tomorrow and will try to see if I can reproduce the general instability.

@rsudev What was that device you are using? Did you see any regular crashes of c:geo on it?

**Comment by rsudev** [comment]
I have an Xperia Z1 and don't experience regular instability WRT c:geo. The system is not that stable in itself (but I don't have the latest update from end of May installed yet) and needs regular (every 3-4 days) reboots to free up memory it seems. I don't use GMS in c:geo or other apps and have no issues (had a nice test run about a week ago in Stockholm :) )

**Comment by Lineflyer** [comment]
Assigning to me to test with an Z3

**Comment by Lineflyer** [comment]
The tested Z3 is working normal with c:geo...no clue here.

**Comment by Lineflyer** [comment]
While there was an initial high amount of users reporting problems in this scenario, it has now dropped to zero.
I assume (without having it seen myself) that this was a general problem on some devices caused by the Lollipop upgrade but later solved (maybe either by another update or users making a factory reset).
I have recently added a short info to our FAQ and don't think any other activity is required.
