### ISSUE TITLE
Crash on Google Map

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5036]
This is another round of crashes which might be contrary to initial believe something new (the only older report is from an NB version)

```
java.lang.NoSuchMethodError: org.apache.commons.lang3.reflect.MethodUtils.invokeMethod
at cgeo.geocaching.maps.google.v1.GoogleMapView.displayZoomControls(GoogleMapView.java:83)
at cgeo.geocaching.maps.CGeoMap.onCreate(CGeoMap.java:503)
at cgeo.geocaching.maps.google.v1.GoogleMapActivity.onCreate(GoogleMapActivity.java:37)
at android.app.Activity.performCreate(Activity.java:5248)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2247)
at android.app.ActivityThread.access$800(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5050)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rsudev** [comment]
What baffled me initially was, that we catch this very thing in the place that is in the stacktrace. Looking better right now i see that we catch ```NoSuchMethodException``` but not ```NoSuchMethodError```.
But why this pops up right now I have no idea...

**Comment by Lineflyer** [comment]
We got a mail on support also dealing with not being able to start the live map any more after upgrade.
Description is like:
With Google Maps it crashes instantly
When I select OSM it take some more seconds and opens initially but then crashes

I am not aware that we change anything in the maps area...
DId we increase any target versions, external libraries or something similar which might influence the bhaviour in this case?

**Comment by rsudev** [comment]
Ten weeks ago we updated commons-lang3, which is used in this case. But from what I see in that library, this newly cropping up issue is not motivated.

**Comment by Lineflyer** [comment]
Another user:
```
Julito
--- System information ---
Device: MI 4LTE (cancro_wc_lte, Xiaomi)
Android version: 4.4.4
Android build: KTU84P
Cgeo version: 2015.06.15
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: pt_PT
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins:  none
--- End of system information ---
```

Error description:
cgeo 2015.06.15 exits at opening live map or when in a list is pressed the map icon to show caches in a map

**Comment by Lineflyer** [comment]
Another user wrote this:

The live map in c:geo with version 2015.06.15 was not working with Android 4.2 (crash when trying to open it)  but I now upgraded the device to 4.4 and c:geo is working again.
I've got a rooted Xiaomi Redmi Note smartphone (Mediatek processor).

**Comment by rsudev** [comment]
Lineflyer: Do we have somebody on support we can ask to try the next nightly build for a cross-check before we put this to release?

**Comment by Lineflyer** [comment]
Not yet.I will keep eyes open to find someone on support mail or FB.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: rsudev <notifications@github.com> 
Datum: 18.06.2015  07:26  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu> 
Betreff: Re: [cgeo] Crash on Google Map (#5036) 

Lineflyer: Do we have somebody on support we can ask to try the next nightly build for a cross-check before we put this to release?

**Comment by Lineflyer** [comment]
@rsudevAssuming I find a user it will be preferable to hand over a RC instead of a NB, due to later upgradibility.So I suggest to merge to release already now.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: rsudev <notifications@github.com> 
Datum: 18.06.2015  07:26  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu> 
Betreff: Re: [cgeo] Crash on Google Map (#5036) 

Lineflyer: Do we have somebody on support we can ask to try the next nightly build for a cross-check before we put this to release?

**Comment by Lineflyer** [comment]
Feedback of acffected user mentioned above 
```
Device: MI 4LTE (cancro_wc_lte, Xiaomi)
```
for testing 2015.06.18-RC:

It works perfectly.
Thank's for the quick support.
