### ISSUE TITLE
mark caches as too hard / need equipment / riddle solved / ...

### ISSUE THREAD

**Issue by koem** [cgeo/cgeo#5037]
I'd sometimes like to have more info on some caches in the map view. Eg. for caches like "this one is a T5 - I can't do that" or "riddle not solved - too hard" or "need equipment - can't do" or "riddle solved - go get it".

a) add a marker (as the disk marker for stored caches) from a list of markers - like choosing from a list of emoticons: Ladder, water, evil smiley, book, padlock, key, magnifying glass, lightbulb, musical notes, clock, question mark, exclamation mark, ellipse, ... - what they are used for is up to the user
b) use a simple little round dot instead of a cache icon
c) just hide the cache icon
d) make cache icon 60% transparent

I'd vote for a), b), and c)

Tags: marker

**Comment by SammysHP** [comment]
e) Use a filter.

**Comment by Lineflyer** [comment]
a) We already discussed additional markers in several issue. AFAIR most of the times the outcome was, that we should not overcrowd the map with cache markes (also as all edges are already occupied). However I still somehow like your approach as it would be customizable acc. to users needs
b) c) d) I think that is too much

and let me add:
In your usecase you should just divide the caches into different lists (according to their requirements) and simply only map the list you want to look for (similar to the filter proposal of @SammysHP )

**Comment by SamuelPlentz** [comment]
I also like option. (a)

Filters or lists have disadvantages on the live map that I use 90% of the time. The cache is either completely hidden [filter] or shown [list] on the live map. I want to decide for each tour I make if I have a ladder, a boat, other equipment, the time, etc. for the cache.

**Comment by Lineflyer** [comment]
Covered by #5798 and #3523 and maybe others. Lets close this old one.
