### ISSUE TITLE
Try to minimize OOM problems by requesting larger heapsize

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5038]
As discussed on IRC:
I would like to test if requesting a larger heapSize in our manifest could help minimizing the OOM problems (caused by large bitmaps and mapsforge library) for the time being.
I am aware it is no solution but still maybe helpful until we get more memory optimizations (like e.g. a new mapsforge library).

Reference:
http://developer.android.com/reference/androi/R.styleable.html#AndroidManifestApplication_largeHeap

I suggest to change it on `master` and do some comparisons on some devices.

**Comment by mucek4** [comment]
S3 is the main cause of crashes

**Comment by Lineflyer** [comment]
Reopening for testing and providing feedback here.
Main retest could be to see how many recursive OSM-maps can be opened before an OOM appears with and without this setting to get a comparison which probably allows an estimation if anything has changed.

Main tasks:
- [ ] Test on Samsung S3 as it is highly affected (possibly due to low RAM availability on this device)
- [ ]  Test on pre-Honeycomb device (e.g. 2.3.x)
- [ ] Test on some other devices/Android versions

**Comment by Lineflyer** [comment]
Just to let you know:
First small test on my S4 shows that this makes a huge difference!
With yesterdays NB I ran into an OOM at the second instance of a map, with the current NB I stopped testing at eight instances and it was still working normal.
I will also test some of the caches with huge amount of pictures (as mentioned in some issues here).

**Comment by Lineflyer** [comment]
Test result for Samsung S3:

Test case:
1. Open live map using OSM:Offline - Germany v0.3 (downloaded 10.05.2015)
2. Open popup of a saved cache
3. Open Cache details
4. Select Navigate -> Map
5. Keep repeating the sequence starting with step 2 and count iterations

Results:
2015.03.31   -> Crash on step 4 without any iterations
2015.06.15   -> Crash on step 4 without any iterations
2015.06.18-NB-b6c823a  -> Crash on step 4 after 8 iterations

```
--- System information ---
Device: GT-I9305 (m3xx, samsung)
Android version: 4.4.4
Android build: KTU84P.I9305XXUFNL1
Cgeo version: 2015.06.18-NB-b6c823a
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / Basic
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Test result for Samsung S4:

Test case:
1. Open live map using OSM:Offline - Germany v0.3 (downloaded 10.05.2015)
2. Open popup of a saved cache
3. Open Cache details
4. Select Navigate -> Map
5. Keep repeating the sequence starting with step 2 and count iterations

Results:
2015.03.31 -> Crash on step 4 after 1 iteration
2015.06.15 -> Crash on step 4 after 1 iteration
2015.06.18-NB-b6c823a -> Crash on step 3 after 11 iterations

```
--- System information ---
Device: GT-I9505 (jfltexx, samsung)
Android version: 5.0.1
Android build: LRX22C.I9505XXUHOD7
Cgeo version: 2015.06.18-NB-b6c823a
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
- opencaching.de: logged in (Login OK)
Installed cgeo plugins: calendar, contacts
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Test result for HTC HTC Wildfire S (Android 2.3.5):

Test case:
1. Open live map using OSM:Offline - Germany v0.3 (downloaded 10.05.2015)
2. Open popup of a saved cache
3. Open Cache details
4. Select Navigate -> Map
5. Keep repeating the sequence starting with step 2 and count iterations

Results:
2015.06.15 -> Crash on step 4 in the first try
2015.06.18-NB-b6c823a -> Crash on step4 in the first try

Log shows no warning or error and c:geo is starting up normal with the 2015.06.18-NB

```
--- System information ---
Device: HTC Wildfire S A510e (htc_marvel, htc_europe)
Android version: 2.3.5
Android build: GRJ90
Cgeo version: 2015.06.18-NB-b6c823a
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (default state)
System language: de_DE
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Basic
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Summary for me:

It is not a fix for our memory problems but seems to be a valid workaround which will solve most of the OOM issues on Android 3+ while it seems to not affect anything on 2.x

Now here it comes:
I do see a risk with that (no idea if any pre-Honeycomb device might hick up with that setting) but still would like to see it released as soon as possible.
If we would keep it in master this would offer more time to test but I already tested all I can, so it could only be some coincidental feedback from NB users come in. I do not expect much more info while waiting.
Thus after thinking about it, I would like to see it on release branch. For sure this might be risky...so I want to know your opinion as well please!

**Comment by mucek4** [comment]
Test result for HTC Desire Cyanogen mod (Android 2.3.7):

Test case:
1. Open live map using OSM:Offline - Slovenia
2. Open popup of a saved cache
3. Open Cache details
4. Select Navigate -> Map
5. Keep repeating the sequence starting with step 2 and count iterations

Results:
2015.06.15 -> Crash on step 4 in 3rd iteraion
2015.06.18-NB-b6c823a -> Crash on step4 in 3rd iteration


I vote for merging this in release. I don't know if we have any Chinese phones to test, but it looks fantastic.

**Comment by Lineflyer** [comment]
Merged to `release`as well as agreed on IRC.
