### ISSUE TITLE
have send2cgeo work on project-gc.com 

### ISSUE THREAD

**Issue by simrebel** [cgeo/cgeo#5040]
I would like to have send2cgeo to work on project-gc.com

**Comment by Lineflyer** [comment]
AFAIR there was some discussion about this with @ganjs1447 some months ago and AFAIR he already prepared at least a menu item in the V-GPS for it for later use.

**Comment by Lineflyer** [comment]
@ganja1447

**Comment by Lineflyer** [comment]
This issue was moved to cgeo/send2cgeo#2
