### ISSUE TITLE
Additional waypoints in GSAK GPX not recognized on import

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5044]
Follow up of #4733.

Will complete details next days.

**Comment by Lineflyer** [comment]
Details have been sent to @Bananeweizen via mail. (GPX example file from GSAK).
Might indeed be related to the general issue #5065 and therefore caused by 56cefb30ade3425a0a45a266a5a4f90bb4399c30 as @rsudev mentioned in https://github.com/cgeo/cgeo/commit/56cefb30ade3425a0a45a266a5a4f90bb4399c30#commitcomment-12003270

**Comment by Bananeweizen** [comment]
I think this is fixed with the reversal. At least in my current version I can import the test file I got via mail, and have final location waypoints at some of the mysteries (assuming this is what was previously missing).
