### ISSUE TITLE
Inventory Order when logging a cache

### ISSUE THREAD

**Issue by javthrowr** [cgeo/cgeo#5046]
Previously Inventory was in alphabetical name order when you were logging a cache. Since the last update, a new little icon is next to them, but it is no longer in alphabetical order. This makes it very time consuming to scroll thru and find the ones you want.

**Comment by Lineflyer** [comment]
This seems to be a bug introduced by the recent changed for Geokrety support

**Comment by Lineflyer** [comment]
@kumy Any idea if that might be connected to your changes?

**Comment by kumy** [comment]
@Lineflyer Probably ;)
(On the phone)

**Comment by Lineflyer** [comment]
It seems to be in reverse alphabetcial order (of the TB name) now. I don't remember the old sorting...I guess it was alphabetical by name, so its now just reversed.

**Comment by Bananeweizen** [comment]
I saw this issue only after I had already fixed the bug in my version. @kumy I hope you didn't waste time now for duplicated efforts. Sorry if so.

**Comment by kumy** [comment]
Thanks. Don't worry i m not at home!
