### ISSUE TITLE
mapsforge lib update

### ISSUE THREAD

**Issue by pr0vieh** [cgeo/cgeo#5047]
Update mapsforge for better performance and new futures
The current stable release is 0.5.1.

**Comment by SammysHP** [comment]
We already have some issues about updating the map activity. But that is not an easy task. Some people are working on an implementation, but that is in a very early stage. At the same time we must update the Google API, because it will be easier with some refactoring.

If you can help (you suggested this technical task), please contact @rsudev or wait for a response. I am sure he also knows the other issues, because I cannot find them with my phone.

**Comment by rsudev** [comment]
I did a search for an existing issue covering that and found nothing. That said, it is in the works (ongoing prototyping can be found here: https://github.com/rsudev/c-geo-opensource/tree/mapsforge-5b), but still not even 'alpha' IMO, as there are still some fundamental architectural topics to be solved.
If you (by chance) are a developer, feel free to contact me as suggested by SammysHP!

**Comment by SammysHP** [comment]
Hmm, then let us keep this issue open. :)

**Comment by sfontene79** [comment]
Upgrading to mapsforge 5.1+ would also enable access to cool features such as displaying multiple map files at the same time (see [MultiMapDataStore](https://github.com/mapsforge/mapsforge/blob/master/docs/MapDataStore.md#multimapdatastore)) !

**Comment by rsudev** [comment]
Unfortunately did not change too much since June...
But I am still trying to carve out time here and there to get this further. As always, helping hands, coding ideas (reference to current state see above), etc. welcome

**Comment by Lineflyer** [comment]
FYI:
More people contacting us that some up-to-date maps and some themes (source ?) are no longer working with c:geo.
I assume this is because the source changed to a newer version which seems not backwards compatible.

**Comment by SammysHP** [comment]
Also Freizeitkarte will switch to a theme with mapstyles with the next update in some weeks. This requires 0.6.

**Comment by Lineflyer** [comment]
@SammysHP Is Freizeitkarte some offline map file or do you refer to the OSM online tile-servers we implemented in c:geo?

**Comment by SammysHP** [comment]
http://freizeitkarte-osm.de

One of the best OSM maps.

**Comment by kurly1** [comment]
The current mapsforge implementation in c:geo has also at least one bug which cusses a crash of c:geo. So moving to a newer mapsforge version would also increase the stability of c:geo. The performance should also be much better with the new version.

**Comment by Lineflyer** [comment]
@rsudev 
On current master the navigation target "New Map" does only show an empty map (no tiles) for me.
How to configure it?

**Comment by rsudev** [comment]
You need an offline map configured in settings for the new map to work.

**Comment by rsudev** [comment]
Experimental map with 0.6.0 is avilable. Closing.
