### ISSUE TITLE
Need to select title/caption text on images

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#5049]
Hi there, 

I've discovered a problem. I was caching in Switzerland using cgeo last week. It's quite common there to give 'photo hints' with a detailed caption or title to the spoiler photo. 

I can't find any way to select the title text of a photo in order to translate it to English. Long-pressing on the caption text does nothing (it works on the normal log text).  Is this possible? if not, it's badly needed.

Also, On the 'log images' page, it's not even possible to read the full title or caption if it is longer than the page width!

Example, on GCGC77 see the log entry for 13/8/2011

**Comment by moving-bits** [comment]
With refactoring of the image tab some time ago it's now possible to select the image captions for copy & paste, so let's close here.
