### ISSUE TITLE
Filter/search by text on cache name

### ISSUE THREAD

**Issue by ludoo0d0a** [cgeo/cgeo#5056]
It would be valuable to add a filter by text to retrieve caches of a serie.

A serie is commonly named :
#1 Serie Mickey - Cache A
#2 Serie Mickey - Cache B
#3 Serie Mickey - Cache C
#4 Serie Mickey - Bonus

or Mickey #1, Mickey #2,Mickey #3.

Filter using 'mickey' as keyword would be great !

I think we could add it in search panel too.
Search by keyword is not really pertinent and could be replaced by a simple search.

**Comment by rsudev** [comment]
I don't understand the last paragraph. Could you elaborate on that?

**Comment by ludoo0d0a** [comment]
My first idea / requirement was about filtering only.

But after thinking a litle bit I saw that main search panel includes search by coords, address, code, keyword, finder, owner, tb ; but not by text (on cache name)
Since I still do not clearly understand what is a keyword, I think 'search by text/name' would be more useful.

**Comment by rsudev** [comment]
It is named 'Search by Keyword', because in the context of gc.com this is what is behind that function (including all restrictions that come with it). It might be slightly different in case of opencaching sites (OKAPI), but that I would have to look up in detail. So this is something we currently IMO cannot really implement.

**Comment by ludoo0d0a** [comment]
After I remember GC api features
and looked after [cgeo connector](https://github.com/cgeo/cgeo/blob/a4efdd23c6516e6ee5add3b7eec3c0570f454068/main/src/cgeo/geocaching/connector/ox/OpenCachingApi.java#L134), I could understand.

I just understood too that search is always online.
And since i'm currently offline, i can see autocomplete in 'search by keyword' field and I receive an empty list as result instead a warning . I thought search could be performed offline too (on already stored caches of course).

So may be simply add "filter by cache name" in the filter menu should be possible, isn't it ?

**Comment by rsudev** [comment]
Offline search is facilitated by the search bar on the main screen and a text filter on cache name should certainly be possible.

**Comment by ludoo0d0a** [comment]
So obvious that I never used this search feature !! thanks for this tip.

I confirm autcomplete / inline search is working offline , but click 'search' gives an empty list.

**Comment by TofLaBeuze** [comment]
It would be interesting to have this filter by cache name with the other filters in the offline lists menu.

**Comment by jakedot** [comment]
can this be closed? doesn't seem to be a relevant request (anymore).

**Comment by moving-bits** [comment]
If you enter some text in main screen's search bar, there are two limitations, IMHO:
- If you enter a six letter word, search is done for trackables only (IIRC).
- Search only works for beginning of a cache name, not for some text within.

(But both of it may be fixed more easily than introducing a name filter function to `CacheListActivity` might be.)

**Comment by eddiemuc** [comment]
Solved with #9081
