### ISSUE TITLE
Split send2cgeo into a separate repository

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5057]
Taken from #5007:

Reason:
With the new webpage we link directly to mater on cgeo/cgeo repository.
Having a separate repository for send2cgeo would allow
- Separate bugtracking
- Having branches for release/master separate to c:geo app
=> Allowing a separate release management for the script without need for any other hosting,etc.

So, here would be my proposal:

- [x]  (Merge #5045 - if ready to merge)
- [ ] Create a dedicated repository for send2cgeo in organization cgeo
- [ ] Change `@updateURL` and `@downloadURL` in script
- [ ] Change URLs on web page
- [ ] Raise version number of script
- [ ] Place the new version of the script to the old URL  https://send2.cgeo.org/send2cgeo.user.js for a last time

Will this work?
Who could support this by creating the new repo (this won't work easy with UI only).

**Comment by Bananeweizen** [comment]
Seems quite reasonable to me. However, I have no clue if any of that will break the existing scripts from updating or introduce other related issues.

**Comment by Lineflyer** [comment]
It should not break anything IMHO:

The currently released script targets to the (old) webpage (and not to our repo) for updating/downloading. So moving the script to a new repo should not harm (only the link on the new webpage needs to be adjusted in time).

**Comment by Lineflyer** [comment]
Can someone split send2cgeo into a separate repo please?

**Comment by SammysHP** [comment]
I can do it.

**Comment by Lineflyer** [comment]
@SammysHP Go for it.
The only thing which needs to be done at the same time would be to change the link on our homepage to the `release branch` of the new repo.

**Comment by SammysHP** [comment]
I will do it when I am back home (~19:30).

**Comment by SammysHP** [comment]
See https://github.com/cgeo/send2cgeo.

**Comment by Lineflyer** [comment]
This issue was moved to cgeo/send2cgeo#15
