### ISSUE TITLE
New button "Move" in already stored cache pop-up window

### ISSUE THREAD

**Issue by Dezerterzy** [cgeo/cgeo#5059]
Hi. It is a kind of usability improvement. When I click a cache on map that is already stored on some list I wish to have "MOVE" button. I do not need to click "More details" then, in order to move cache from one list to another.
![screenshot_2015-06-24-13-31-35 - kopia](https://cloud.githubusercontent.com/assets/13032367/8329121/1d1d328e-1a77-11e5-92f4-d2b36bdc4a6c.png)

**Comment by Lineflyer** [comment]
We do have a manage button (pencil) right now.
