### ISSUE TITLE
Suggestion: need a way to manage/switch between several gc.com accounts easily

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#5064]
Hi,

For personnal reasons I use 2 differents gc.com accounts. My request is to:
- store these 2 differents accounts in c:geo simultaneously
- provide an easy way to swicth between them.

Notes: 
- the best I think is to ask/select the account to use at c:geo startup 
- this need of several "c:geo profils" on the same device may be usefull for other c:geo settings (for instance background color ...)
- don't forget to manage other "linked" accounts like (geokrety, GV vote ...): some accounts could be shared between these new "c:geo profils".

What do you think?

**Comment by SammysHP** [comment]
Once we decided against it because stored caches contain information about the account (e.g. found it status).

Using different profiles for everything in c:geo is possible by using the account functionality in recent versions of Android.

**Comment by Lineflyer** [comment]
This would requite major reworks as all the information storage is bound to a spcific user account (as already mentioned by @SammysHP) and might be useful only for a minor percentage of users.
I vote against it.

**Comment by samueltardieu** [comment]
I vote against it too. I propose closing this issue as this is solved easily by creating several accounts on the phone as indicated by @SammysHP. Please team reopen if you don't agree.

**Comment by murggel** [comment]
@eddiemuc That's one issue which deals with accounts for more than one person.

For me it would be sufficent to have that for logging (so I could use a easy way to log the same caches for different users - me and my children), whether with same log-entry or store different (offline) logs for different accounts.

Probably I open a new issue and I will think of some ideas for a solution...

**Comment by eddiemuc** [comment]
> For me it would be sufficent to have that for logging (so I could use a easy way to log the same caches for different users - me and my children), whether with same log-entry or store different (offline) logs for different accounts.

Same for me. And for exactly the same use case :-)
