### ISSUE TITLE
Child waypoints of exported GPX missing on reimport

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5065]
I got several independent users on FB and support who report, that they export a GPX from c:geo for caches with waypoints and some (or all) of these waypoints are missing  when reimporting it on another c:geo installation.
Both versions 2015.06.19

Did not have time to retest this yet.

**Comment by Lineflyer** [comment]
Confirmed!
I created some custom waypoints on a saved cache, then exported it with c:geo and reimported it on another installation.

All of those waypoints are missing although they are contained in the exported GPX.
Log on import device shows no error.

This is a "major regression".

**Comment by SammysHP** [comment]
I think this is related to #5044.

**Comment by Lineflyer** [comment]
@Bananeweizen I don't know exactly what's going on here but from what was written in other issue and commit message this seems somehow related to those terracaching import changes you made earlier. Can you take a look on that? We keep getting complaints for this regression as of course a basic function of GPX importing is affected.

**Comment by LeXeRLV** [comment]
Yes, I agree with this problem too!
We thus week go for cache with hand written in 42 waypoints and it is
stupidly for now, that I can't give others my saved logs through GPX export
file of the cache, so each of them need to write points by himself.
Too old school :-D

-
Best regards,
LeXeR_LV

**Comment by rsudev** [comment]
I basically reverted the change in GPXParser as discussed in 56cefb3 based on release but first merged to master as a preemptive measure to allow broader testing while this is still under consideration.

**Comment by Bananeweizen** [comment]
To me this looks okay with the reverse by @rsudev. I've not seen such issues since then.

**Comment by Lineflyer** [comment]
THanks for testing @Bananeweizen. Is was missing the time for that.
@rsudev You could/should merge that to release as well then.

**Comment by Lineflyer** [comment]
Reopening and assigning to @rsudev for merging into `release`

**Comment by Lineflyer** [comment]
This is no longer relevant as we released from master since the point where the fix has been introduced.
