### ISSUE TITLE
Automatically sort by name

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5067]
We already sort lists by date if they contain only event caches. We could sort by name automatically if we recognise a common prefix in all caches of a list.

**Comment by Lineflyer** [comment]
Title corrected :) That was a good one ;)

**Comment by kumy** [comment]
This remind me something...
Isn't it a duplicate of #4707 ;) ?

**Comment by Lineflyer** [comment]
Yup, it is.
