### ISSUE TITLE
Upload strings from master to Crowdin

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5068]
I do see some untranslated strings on `master` which would need to go to Crowdin to get translations.

**Comment by rsudev** [comment]
Just yesterday I was thinking whether now is the time to switch back to translating master...
I can do this today evening.

**Comment by rsudev** [comment]
Upload done, German ready for proofreading...

**Comment by Lineflyer** [comment]
Proofread german (but adapted some strings...feel free to review again if needed).
