### ISSUE TITLE
Owner related log types not always available on own caches

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#5070]
I have found on several occasions that I cannot post a Owner Maintenance log on my own caches.
The log types Archived and Disabled are also missing in the log type dropdown list.
But sometimes the log options are available.
I have not figured out yet when they are available and when they are not.

**Comment by MrYaz** [comment]
I just noticed that it helped to rotate the device to landscape mode and back to get all log types back againn.
Se attached screenshots.

Before rotating the device:
![screenshot_2015-07-01-01-07-59](https://cloud.githubusercontent.com/assets/1811963/8444246/fab0cfcc-1f8e-11e5-8f2f-c4303afb4386.png)

After rotating the device:
![screenshot_2015-07-01-01-08-09](https://cloud.githubusercontent.com/assets/1811963/8444245/fab07572-1f8e-11e5-9143-425a43929ee1.png)

**Comment by Lineflyer** [comment]
That is strange and not reproducible for me.
Can you please complete the following information:
1. c:geo Version
2. Was this owned cache saved in your lists?
3. Did you have network coverage when starting when invoking the log window?

**Comment by MrYaz** [comment]
1. Nightly build 2015.06.30-NB-51ac2bc, but this bug has occured to me for several months ago as well. I always run the latest NB
2. Yes, it was saved in a list
3. Yes I have network coverage and it happens at home as well with wifi connection.

It is very random behavior and occurs on approx. 30% of my tries.
It also seems like it's device dependent because on my Z3compact it doesn't happen at all. 
Only on my Nexus 5

--- System information ---
Device: Nexus 5 (hammerhead, google)
Android version: 5.1.1
Android build: LMY48B
Cgeo version: 2015.06.30-NB-51ac2bc
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: sv_SE
Geocaching sites enabled:
 - geocaching.com: logged in (Inloggning OK) / Premium
Installed cgeo plugins: calendar, contacts
--- End of system information ---

**Comment by Hauwertlhaufn** [comment]
I've tried it on my device for about 20 times now, but it never happened.
Owned Caches are also saved in list and
mobile data is also avaliable.

--- System information ---
Device: Nexus 5 (hammerhead, google)
Android version: 5.1.1
Android build: LMY48B
Cgeo version: 2015.06.30-NB-51ac2bc
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: true
Map strategy: auto
HW acceleration: disabled (manually changed)
System language: de_DE
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins: calendar
--- End of system information ---

**Comment by Lineflyer** [comment]
I was also not succesfull in reproducing this.

**Comment by Lineflyer** [comment]
@MrYaz 
Did you gain any new clues on this?
For me the most probable reason is, that the network connection was instable when opening the logging view (but that would also only be of any importance if the cache is not saved to your device, so we may now know that it is an owned cache).

**Comment by Lineflyer** [comment]
Closing as not reproducible and no new cloues on it up to now.
Feel free to reopen if you have new facts.
