### ISSUE TITLE
Support import of GGZ files

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5072]
From support mail:

Some applications (like GSAK and Garmin tools) support a compressed GPX format named GGZ.

While this officially is a propriertary solution for Garmin devices, it seems to be just a zipped GPX with a small folder structure inside (containing a XML file specific to Garmin(?) and a normal GPX).
As it seems to be a valid ZIP archive, might it be possible to enable c:geo to import that on the same way as GPX (and zipped GPX).

Advantage for the user:
Have only one small file valid for his Garmin and c:geo (which is in fact the same device=Monterra).

Example file:
https://www.dropbox.com/s/xbl6ma64f6dcpg2/test.ggz

If you just remane that to *.zip you will be able to open it.

**Comment by mucek4** [comment]
.zip or .gz?

**Comment by SammysHP** [comment]
```
$ file test.ggz 
test.ggz: Zip archive data, at least v2.0 to extract
$ file -i test.ggz 
test.ggz: application/zip; charset=binary
$ unzip -l test.ggz
Archive:  test.ggz
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-07-02 08:22   data/
    50247  2015-07-02 08:22   data/test.gpx
        0  2015-07-02 08:22   index/
        0  2015-07-02 08:22   index/com/
        0  2015-07-02 08:22   index/com/garmin/
        0  2015-07-02 08:22   index/com/garmin/geocaches/
        0  2015-07-02 08:22   index/com/garmin/geocaches/v0/
     2589  2015-07-02 08:22   index/com/garmin/geocaches/v0/index.xml
---------                     -------
    52836                     8 files
```
