### ISSUE TITLE
Many crashes on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5074]
Each time i want to open a cache from the map cgeo crashes.
No further details as I am on the road.

At least nighty users are affected. No idea if release is also affected.

**Comment by Hauwertlhaufn** [comment]
Same here. It only happens, when I try to open a cache, that isn't saved offline.

**Comment by mucek4** [comment]
You can open a cache from map in release.

**Comment by Lineflyer** [comment]
I did now reach a state where I can no longer open any unsaved cache.
Falling back to release for this weekend.
Can someone provide a log for this...I can only do that next week

**Comment by rsudev** [comment]
Probably caused by side-effect of implementation for #4978, should be fixed in next nightly as I reverted the change.

**Comment by Hauwertlhaufn** [comment]
With the newest nightly the problem is fixed on my device.

**Comment by rsudev** [comment]
So I close this issue, needs to be considered when testing the next implementation for #4978
