### ISSUE TITLE
Managing fav points not possible

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5082]
From FB and verified with current nightly:
Not possible to add or remove favorite points.
An error toast is shown.

**Comment by Lineflyer** [comment]
Seems to be a website change:

```
14:53:40.803 Debug cgeo 2942  [network-5] POST http://www.geocaching.com/datastore/favorites.svc/update?u=4OB3GFHLRR3CG77BJPYEHLBBAXWDBIYBMJF5WVL6CGUAUI5H6UK6SYMMADER2IQ22L6FBKPMT7TBS65J47RKAPP4CY3TYPFI73ICMJZ47E3ZFH2YRJLSM4MOHJ5IT4WIL4QQGC2JXA5ITT3BN7TSNAWKLBUEL277XVSW65FGUCSCBS4EUIURQD7RPQLCC64EL6MJMT47J4A5UD3JOTVDUVM2O5XVOWK6UTEED5WA5XMIWGS5EL6A&f=false
14:53:41.130 Warning cgeo 2942  [network-5] 404 [Not Found] (406 ms) POST http://www.geocaching.com/datastore/favorites.svc/update?u=4OB3GFHLRR3CG77BJPYEHLBBAXWDBIYBMJF5WVL6CGUAUI5H6UK6SYMMADER2IQ22L6FBKPMT7TBS65J47RKAPP4CY3TYPFI73ICMJZ47E3ZFH2YRJLSM4MOHJ5IT4WIL4QQGC2JXA5ITT3BN7TSNAWKLBUEL277XVSW65FGUCSCBS4EUIURQD7RPQLCC64EL6MJMT47J4A5UD3JOTVDUVM2O5XVOWK6UTEED5WA5XMIWGS5EL6A&f=false
14:53:41.130 Error cgeo 2942  [network-5] GCParser.changeFavorite: cache not added/removed to/from favorites
```

**Comment by Lineflyer** [comment]
OK...some minutes later its working again for the same cache on the same device in the same session:
It seems not to be a stable thing.


```
15:14:22.501 Debug cgeo 2942  [network-8] POST http://www.geocaching.com/datastore/favorites.svc/update?u=4OB3GFHLRR3CG77BJPYEHLBBAXWDBIYBMJF5WVL6CGUAUI5H6UK6SYMMADER2IQ22L6FBKPMT7TBS65J47RKAPP4CY3TYPFI73ICMJZ47E3ZFH2YRJLSM4MOHJ5IT4WIL4QQGC2JXA5ITT3BN7TSNAWKLBUEL277XVSW65FGUCSCBS4EUIURQD7RPQLCC64EL6MJMT47J4A5UD3JOTVDUVM2O4SGRSKO5CN7LZX4YHU4HYA33T4A&f=true
15:14:22.941 Debug cgeo 2942  [network-8] 200 (405 ms) POST http://www.geocaching.com/datastore/favorites.svc/update?u=4OB3GFHLRR3CG77BJPYEHLBBAXWDBIYBMJF5WVL6CGUAUI5H6UK6SYMMADER2IQ22L6FBKPMT7TBS65J47RKAPP4CY3TYPFI73ICMJZ47E3ZFH2YRJLSM4MOHJ5IT4WIL4QQGC2JXA5ITT3BN7TSNAWKLBUEL277XVSW65FGUCSCBS4EUIURQD7RPQLCC64EL6MJMT47J4A5UD3JOTVDUVM2O4SGRSKO5CN7LZX4YHU4HYA33T4A&f=true
15:14:22.941 Info cgeo 2942  [network-8] GCParser.changeFavorite: cache added/removed to/from favorites
```

**Comment by Lineflyer** [comment]
Keeps happening randomly but 90% it fails

**Comment by rsudev** [comment]
It really looks like a server-side issue to me. This morning I tried - fail. Right now it works on the same cache...
Taking a look at the actual communication of the website, it still is the same AFAICS.
Not sure what we can do here...

**Comment by Lineflyer** [comment]
Strange is that it seems to work reliable on the website itself at all times....mmh.

**Comment by rsudev** [comment]
I tried to research a little more this evening and it really looks kind of strange.
Sometimes the userToken (after the ```u``` in the above log) stays the same, sometimes it changes within the page when requesting the fav-points or setting them.
And  right now I even had an instance, where the request failed on the website - the page came from the cache and the userToken was seemingly wrong and I got a 404 already when retrieving the score.

**Comment by SammysHP** [comment]
I observe this behavior already for some weeks. Most of the time the favorite statistics are not loaded.

**Comment by Lineflyer** [comment]
I think in this cas ewe should just wait and see how this develops. Also on FB people report, that the website has the same problems.

**Comment by samueltardieu** [comment]
Does it still occur?

**Comment by rsudev** [comment]
I shortly checked again today, everything fine for me. I consider this to be a temporary glitch on the website, therefore closing.
Feel free to re-open with up-to-date information.
