### ISSUE TITLE
Quick search with 6 characters interpreted as trackable

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5083]
In 71629eecbed3793ec62f1e769927d52b773e27a0 @Bananeweizen fixed #1036 unintentionally. Now every six character word is interpreted as a secret trackable code.

The downside of this (as remarked by @rsudev) is, that you cannot search for a keyword (that is no secret trackable code) with six characters anymore.

**Comment by mucek4** [comment]
In this case I vote for doing 2 requests. If trackable is find display TB or show results.

**Comment by akkatracker** [comment]
@mucek4 that is probably the best way. If you're unlucky and the secret code is what you're looking for then I don't know.

**Comment by kumy** [comment]
In #4822 we have a similar problem. @Bananeweizen proposed: "I suggest not to do something automatically, but just to present a list selection to the user, where he needs to choose the wanted connector in case of multiple possible ones, and then we continue as of now."

**Comment by alan666notb** [comment]
Anything happening on this issue?
I discovered it while trying to find 'London' caches.

**Comment by rsudev** [comment]
Seemingly not :)
Reading it again, I still do not have a real good idea how to move forward.

**Comment by alan666notb** [comment]
I would suggest removing the 'search for trackable' logic from this location completely.
I wouldn't do that if I wanted to find a trackable, I'd use the trackable field on the search page.

**Comment by kumy** [comment]
I would not remove the search trackable here (I personally use it regularly). It remind me #4822 and #7476

One idea was that when some connectors overlap, the search bar should propose to select which network we want to lookup.

BTW I already said that above in [2015](https://github.com/cgeo/cgeo/issues/5083#issuecomment-120831303)

**Comment by Lineflyer** [comment]
No, dont remove the TB search from this place. 
@alan666notb In fact searching for a location like London was never intentional at this place. If no connector is triggered it searches for caches starting with on gc.com only. IMHO this could be removed and keep it to look for text of saved caches, cache codes, trackable codes.
