### ISSUE TITLE
Use one dialog for username and password

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5092]
For services which need username and password, we should use a single dialog combining both. This should help in getting the credentials right for new users.

**Comment by Lineflyer** [comment]
@madankb 
SIngle dialog means, that the user does not need to select one menu item to input his username and just another menu item for the password, but have one dialog which offers two input fields for username and password and can be ended by the user by pressing "Check Login" (see #5093).

If implemented it should be the same method for all services.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Implemented implicitly with the new authentication screens. Closing.
