### ISSUE TITLE
Automatically check login after first credentials supplied

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5093]
For a new installation, we should automatically trigger the "check login" functionality after the login credentials for geocaching.com have been supplied. The login needs to be executed anyway during the next steps to get some data, but it would be good to detect errors early, while the user is still in the settings.

**Comment by Hauwertlhaufn** [comment]
Imho that is a good idea, 'cause many users may think, that if there is no problem after you saved them, any problem afterwards couldn't be 'caused by the login-information.

**Comment by madankb** [comment]
May I work on this request?

**Comment by Lineflyer** [comment]
@madankb I think so if not @Bananeweizen already started something?!

**Comment by samueltardieu** [comment]
This should be done after #5092 or at the same time.

**Comment by madankb** [comment]
Just to confirm, after user supplies credentials for geocaching, Check login should be triggered automatically. I believe same needs to be done for GCVote and Extremcaching. For #5092, please clarify what is single dialog for both username and password. Appreciate your help.

**Comment by samueltardieu** [comment]
Please ask questions you might have about #5092 in the corresponding issue.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Tested with a clean installation of 2016.04.03-NB to see the sequence for new users.
- App jumps to gc.com login screen
- User selects Authorize
- Enters his credentials (or can click "Create an account")
- Press check authentication will perform a login check automatically.
