### ISSUE TITLE
Don't "flag" as solved if final loc is zero

### ISSUE THREAD

**Issue by steve8x8** [cgeo/cgeo#5101]
After importing a (crafted) GPX that contains a lat=0 lon=0 "Final Location" waypoint for a mystery cache (which is required because there's a note containing a hint and a formula), the blue symbol gets a flag added - despite the fact that the coordinates of the waypoint are zero. This is misleading. Can the flagging condition be changed to exclude wpt stubs like this?

**Comment by rsudev** [comment]
lat=0/lon=0 is a fully valid coordinate, so I am personally reluctant to introduce such a special case. Can't you put the information into the personal note instead? Or leave out the coordinates (I assume c:geo is able to at least import such a gpx)

**Comment by steve8x8** [comment]
OK, this seems to be related to issue 5100 - in a sense that there must be a difference between an undefined location (??? in GC cache listing) and a (0, 0) location (something that fits into a GPX properly).
Would c:geo be able to read a <wpt> that doesn't come with lat="..." and lon="..."? (In that case, it should also be able to write one!) Trying... indeed, that seems to work! (and gpsbabel doesn't complain, so it seems to be sufficiently close to the standards?)

**Comment by steve8x8** [comment]
Since importing waypoints without coordinates (using &lt;wpt&gt; tags without lat and lon info) works, I'd agree to close this issue.
Since exporting waypoints without coordinates doesn't work yet, it might rather be merged into issue 5100?
Thank you for your patience.

**Comment by Lineflyer** [comment]
One question while reading this:
Why do you need a waypoint of the type `Final Location`. Would any `Reference Point` do the job here (which would also avoid the cache from being flaged as "Final coords available")?

Anyway closing upon request.

**Comment by steve8x8** [comment]
It was the existence of (zero) coordinates that made c:geo believe it had final coordinates. A "final" waypoint without coords would not result in a flag (e.g. if loaded from GC).
I agree that the gpx specs don't allow such wpts, but: As long as c:geo accepts "locationless" waypoints on import, everything is fine with me. I don't want to lose wpt notes!
