### ISSUE TITLE
Unavailable picture URL blocks cache refresh/loading

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5104]
This is somehow similar to #4074:

2015.07.18-NB

- Open GC2G9AJ or OCF19C
- "Render view" takes 30 seconds to complete because of:

```
11:44:55.261 Warning cgeo 22067  [network-5] Failure (30162 ms) GET http://team-jerichow.de/uploads/kurzlog4.JPG (ch.boye.httpclientandroidlib.conn.ConnectTimeoutException: Connect to team-jerichow.de:80 timed out)
```

Couldn't we do this in the background not blocking the UI?

Looking back at #4074 I tend to remember that the unavailable pictures was not blocking the UI in the past but did "only" prevent all other pictures from beeing shown. So I would assume (although I did not explicitly test this before) that the blocking behaviour is new.

**Comment by samueltardieu** [comment]
I'm not quite sure I understand what you would want. Right now, such an error would not prevent other caches from refreshing when you refresh in batch (other caches will still progress, as this is done in paralllel). But we indicate the end of a refresh to a user only when everything is finished. Here, clearly, we cannot do that while it is still trying.

If some day we implement background refresh, we might do what you want, but this is far from implemented.

**Comment by Lineflyer** [comment]
OK.. I was not precise enough.
Actually if you make a single refresh for this cache or store it initially, the UI will be blocked until that timeout occurs. My question is: Was it like this ever since or is this a new behaviour? Can we do something about it or do we have to stick with it until we have something like you mentioned (full background refresh)?

**Comment by samueltardieu** [comment]
I think we have to stick with it.

**Comment by Lineflyer** [comment]
Closing due to latest comments.
