### ISSUE TITLE
opencaching.us: Error when retrieving cache

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5106]
Currently there seems to be an issue in the oc.us OKAPI.
Login and search seems to work, but when downloading a cache I get:
```
Oops... Something went wrong on *our* part.
Message was passed on to the site administrators. We'll try to fix it.
Contact the developers if you think you can help!; line: 1, column: 5
```

**Comment by rsudev** [comment]
I sent a note to the oc.us team, asking for comments here...

**Comment by Lineflyer** [comment]
@rsudev Did you get any feedback or shall we post here:
http://forum.opencaching.us/viewforum.php?f=31&sid=b5ef87200c85a1fb12406982c94e3800

**Comment by rsudev** [comment]
I got a response from one of the oc.us admins and asked for more detailed information and that he responds here as well.

**Comment by Opencachingna** [comment]
Sorry, this is now fixed. When we updated OKAPI a couple weeks ago, we were missing a table in the database, cache_mod_coords. We had to await guidance from OCPL, and they solved the issue for us.

**Comment by rsudev** [comment]
Thanks for the feedback! Cross-checked, works.

**Comment by Opencachingna** [comment]
I apologize again for not coming here sooner. I imagine you can close this issue. Thanks!
