### ISSUE TITLE
Microsoft Android emulator

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5109]
If any of our devs is running Windows 8.1 64 bit, you may want to try Microsofts new Android emulator: https://www.visualstudio.com/msft-android-emulator-vs.aspx I don't meet those requirements, so I can't test myself, but I would expect it to be a fast emulator.

**Comment by ecornely** [comment]
It looks really good, thanks for the information.

I'm running Windows 8.0 64bit and started the emulator with cgeo in it this morning. It's much faster than the android sdk emulators I tried.

**Comment by Bananeweizen** [comment]
Have you ever run a genymotion emulator? Because that is what I used since a while instead of the default Android emulator. Both genymotion and the Microsoft emulator are x86 native executables, while the standard emulator is really emulating ARM code (using qemu, if I remember right).

I guess I might have another machine in 2 weeks, so I might be able to report back on the differences, too.

**Comment by ecornely** [comment]
I never heard about Genymotion before but it seems to be based on VirtualBox which I know can be in conflict with my existing and used Hyper-V virtual machines.

I wonder if you wouldn't encounter problem having both the Microsoft Hyper-V VM and a VirtualBox installed at the same time especially with networking, but you'll see
