### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by smico** [cgeo/cgeo#5112]
The cache-icons on the map look a little frayed. Sharper modern icons would be great.

The icons on startpage also look like from 1990s.
c:geo works great but i think it needs a bit more stylish 2015 design.

**Comment by mucek4** [comment]
You know any designer?

**Comment by Lineflyer** [comment]
If you can contribute for that, please feel free to provide proposals.

**Comment by martinluhrman** [comment]
I know google has a library of free-to-use icons, not sure if it contains what you are searching for:

https://www.google.com/design/icons/

**Comment by SammysHP** [comment]
Nope. We talk about specific cache icons.

**Comment by IiroP** [comment]
Have you asked Groundspeak about using their icons? Or does it conflict too much against the open-source norms?

**Comment by SammysHP** [comment]
c:geo is a cross-platform client. Also Groundspeak changes the icons sometimes.

**Comment by Lineflyer** [comment]
Closing here due to no acceptable way of implementing and IMHO the cache icons are fine.
