### ISSUE TITLE
Log counts not updated

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5117]
Gc5w7ag. We have just refreshed this cache on 3 devices. Only on one of them the log counts at the to of the log book were correctly updated.

**Comment by samueltardieu** [comment]
Cannot reproduce on my device.

**Comment by Bananeweizen** [comment]
On my device it also worked fine. But at 2 friends, for one of them the numbers were not shown at all after refreshing, for the other one the "old" numbers from before the refresh remained, such that the numbers were smaller than the actual number of log entries.

I wonder whether our regex is not fitting sometimes.
