### ISSUE TITLE
Favorite point can be added although no favorite point left

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5119]
From support mail (2015.07.08):

Trying to add a fav to a cache with c:geo while there a no favorite points available on my account it returns a sucesful outcome and only after refreshing the cache I do see that the button again says "Add".
There is no error message

--

This used to work i.e. a error toast is shown (I remember I tested it some months ago). Currently I have 12 favs remaining, maybe someone else can give it a try to verify this problem.

**Comment by kumy** [comment]
Able to reproduce.
When posting, response code is 200, which we detect as a success...

**Comment by kumy** [comment]
The "bug" seems to exists also on GC website. I don't know how we can workaround this...

**Comment by SammysHP** [comment]
If we get the same result, we can't do anything. (Well, we could send a bug report to Groundspeak.)

**Comment by kumy** [comment]
Linking to #4348

**Comment by Lineflyer** [comment]
I am sure it used to work (as I remember that I spent all my favorites to random caches to perform this test case in the past). So this is a clear bug on the website.
