### ISSUE TITLE
Dropped caches are not deleted from device if an offline log is associated with the cache

### ISSUE THREAD

**Issue by yellowduck** [cgeo/cgeo#5124]
I have many caches in c:geo that have long been deleted from my device, yet remain as persistant when I select live mode. The images below show a before and after when selecting live mode (without any access to the website - both wifi & data connectivity disabled).

All of the caches in the second view without a 'saved' icon are finds, so they should not be visible because the 'hide finds' is set, yet because they reside somewhere in my device they are displayed. A quick view showed that most of them are at least a year old (find dates) - so long past the 3 day limit for purging deleted files.

I found issue #4357 which appears to discuss something similar, yet it was closed without any further action taken. I have tried the 'delete orphaned files' option without any success.

(There are occasions when this behaviour is useful, but it has got to the point where it is now more of a problem).

![2015-08-06-17-34-23 1](https://cloud.githubusercontent.com/assets/1512344/9117620/69a0c554-3c63-11e5-9a24-675a3299f8f5.png)
![2015-08-06-17-34-51 1](https://cloud.githubusercontent.com/assets/1512344/9117627/72868f28-3c63-11e5-935a-70cca1e2439f.png)

**Comment by SammysHP** [comment]
AFAIK caches with an offline log are never deleted (or is only the log kept?). Nevertheless I never observed such a situation.

**Comment by Lineflyer** [comment]
I think those might all have an offline log stored.
@yellowduck Can you please check the histors if those are listed there and some of them still have an orange (or an orange/green) marker?

**Comment by yellowduck** [comment]
Yes, I use offline logging, however as a user I have 'dropped' the caches, so they should be removed from the database and storage.

**Comment by SammysHP** [comment]
With loosing all your offline logs before you are able to upload them?

**Comment by Lineflyer** [comment]
My assumption would be that if you now go to the history and select Menu -> Clear offline logs all those cache should vanish after three more days. Can you test and confirm?

**Comment by yellowduck** [comment]
I see that as an unsatisfactory workaround. As a user, I have requested that the caches be 'dropped', and I should not need to be aware of subtleties like being aware that offline logs cause different behaviour. If I remove all offline logs, then I also lose information that I may want to keep (for caches that I have not yet 'dropped').
I use offline logs to mark that I have found a cache. I then log them on the website at a later time, sometimes by exporting them as field notes either to the website or through GSAK.

**Comment by Lineflyer** [comment]
So the real problem is here, that found caches are not hidden in this case..isn't it?

**Comment by yellowduck** [comment]
No, I don't believe it is. The problem, as stated, is that old caches that have been dropped are not removed form the device - either database or file cache.
By hiding found caches, the data is still present (which may also be a reason for cgeo to run very slowly when switching lists).

**Comment by gcPhil** [comment]
I can confirm problems, that some caches/data don't seem to be deleted from the device correctly. Before a week I deleted my cgeo-folder with over 3,5gb data again. After that I restored and updated all backuped caches of my lists - and the folder now have only 1gb. I must do that two or thee time a year to keep my phone working with c:geo because of limited internal storage.

**Comment by Lineflyer** [comment]
@yellowduck 
> I see that as an unsatisfactory workaround. As a user, I have requested that the caches be 'dropped', and I should not need to be aware of subtleties like being aware that offline logs cause different behaviour. If I remove all offline logs, then I also lose information that I may want to keep (for caches that I have not yet 'dropped').

Understood.
Can you still test what I mentioned here:
> My assumption would be that if you now go to the history and select Menu -> Clear offline logs all those cache should vanish after three more days. Can you test and confirm?

This would be helpful for a root cause analysis of this problem, as my assumption is, that the known behaviour (caches are kept in history even when they are deleted) is the root cause here.

The map showing all those caches is not a bug at all as it is the "Live map". The only feature to be added here could be to optionally hide offline logged caches (same as for found caches).

**Comment by yellowduck** [comment]
At the risk of repeating myself, the issue is that *dropped caches are not dropped*. I have chosen to remove a cache from my device, and because of an offline log, it is not deleted. If you choose to hide it from display, the cache remains on the device (I assume in both the database and any extra files on the file system).

If I do as you ask, I am going to lose information that I want to keep. I have offline logs indicating information for caches that I have chosen to remain on the device. If I clear all of them I will lose that information.

I also disagree with your comment that the live map behaviour is not a bug. The caches have been found and are not stored on my device - therefore, they should not be displayed. It is not a feature to be added, because it already exists, so we therefore have two issues to contend with:

1. Dropped caches are not dropped if they contain an offline log
2. Dropped caches with an offline log are displayed on the map when 'live' data is displayed despite the check box for not showing found caches being selected.

**Comment by kumy** [comment]
For 1. couldn't we ask the user if he want to also delete the offline log associated with caches being deleted?
For 2. I confirm that offline log are displayed on the map. We should clarify if it's the wanted behavior or not.

**Comment by Lineflyer** [comment]
OK, lets try to puzzle this out together then:

> Dropped caches are not dropped if they contain an offline log

They are dropped from your list but not dropped from the internal cache in c:geo in this case.
Caches without offline logged are completely deleted by our housekeeping after three days, caches with an existing offline log are excluded from this housekeeping mechanism on purpose.
You are right, that they still consume storage space but this is necessary as (as you also agreed) we don't want to lose the offline log information kept within the data set.

> Dropped caches with an offline log are displayed on the map when 'live' data is displayed despite the check box for not showing found caches being selected.

That is caused by the simple fact, that c:geo does not treat "offline logged" caches as "found" caches. So this is more a strategic decision which was made here in the past to make it easier for users to reaccess those caches also from the map without having the need to toggle the setting each time (as offline logged caches are more likely to be needed by a user e.g. to send his log whereas found caches are really not needed any longer).

So what could be a desireable solution for "solving this"?

**Comment by yellowduck** [comment]
I realised after my last post, that I could find an old cache with an offline log, and delete it to see if the cache is eventually cleaned up. (Without the need to do it to all of them.

For the live map scenario:
* Cache stored && offline log==found -> display cache. The fact that the cache is stored will mean this is displayed anyay, so the && is not necessary.
* Cache not stored && offline log==found -> do NOT display cache. For the majority of the caches, they will have been logged online as found, so there is a potential  ordering/priority issue here as well. It appears that because the cache is found in the database, no further checks are made on the downloaded info associated with the cache.
Please remember that I use live data when *offline* as well to show caches from different lists together (but not any that have not been downloaded)

For the drop cache question - is a warning sufficient, "Warning, all offline logs will be deleted". Personally, I do not like this because it adds an extra click to the process.
Aditionally, I use the on-click offline log, and do not add extra comments to the offline logs. In that case is it possible to detect if data has been stored as part of the log, or if it is just a flag to indicate found/not found/attended.

**Comment by yellowduck** [comment]
I removed the offline log from a handful of caches and waited three days as suggested, and indeed the caches are no longer loaded - I had to disable 'hide own/found caches' in order to see them (na dthen with a yellow (not orange) smiley.

I maintain that because I have requested the cache to be 'dropped' it should be regardless of whether an offline log exists or not. For reasons I have previously stated, the offline log for stored caches is useful history (to me), and I do not like the proposal to remove all offline history as a workaround.

**Comment by Lineflyer** [comment]
I could imagine this is a suitable solution then:
> For the drop cache question - is a warning sufficient, "Warning, all offline logs will be deleted". 

So if you drop a cache from a list which has an offline log we should also delete the offline log.
So the cache wont be "hanging" without the user knowing it.

**Comment by yellowduck** [comment]
Hmm! Does this require an extra 'click' to close the dialogue? If so, it will be a nuisance.
I have chosen to 'drop' the cache, and hence any info associated info with it, so I am not sure of the need to present a warning.

**Comment by Lineflyer** [comment]
@yellowduck 
> I have chosen to 'drop' the cache, and hence any info associated info with it, so I am not sure of the need to present a warning.

That is about the different understanding of "Drop" as I tried to explain to you. You drop it from the list, and then it is up to c:geos housekeeping to delete the underlying data. I am sure most people would claim missing offline logs if those are deleted implicitly.

So my proposal was, that if a cache is "dropped" and has a pending offline log we could present a window asking if the offline log should be deleted as well.
If the user accepts, c:geo housekeeping will delete all info after three days. If not the cache will be caches internally in order to preserve the offline log (current default).

**Comment by yellowduck** [comment]
I still think this is a bug and not a feature request (sorry)!

Let's not confuse low-level technical implementation detail with user design.

If I choose to 'drop' a cache from the device, I expect it to be removed. (User view)

(Technical view) Additional data exists, so what choices should we make?

As a user I do not want additional dialogues every time  I perform an action. This would (in my opinion) be bad user design for this feature.

You could argue the same position about dropping a cache that has additional waypoints associated with it - as far as I am aware we do not ask for additional 'permission' before removing the cache.

**Comment by yellowduck** [comment]
Are there any new developments around this issue? I believe it is still happening as described.

**Comment by Lineflyer** [comment]
I wonder that this is still open.
It can be easily "solved" by the user by going to the history and clearing the offline logs....or not?

**Comment by gcPhil** [comment]
No, you can delete the cache from history and must delete the cache from lists as well but it's data seem to stay on the device. It's waypoints keep displayed on the map and if you enable live map this caches get immediately shown with the offline-log icon. I use a workaround by deleting the cache-folder by hand every few months so that it don't become to big by old unused data. It's often several GB of space I get back this way.

**Comment by Lineflyer** [comment]
This is about caches already deleted from lists but still their offline log keeps showing.
Therefore I wrote that this remaining data should get deleted by clearing the offline logs.

**Comment by gcPhil** [comment]
It should, but it will not be deleted in the moment. Clearing the history don't delete the logs it only clear the history list. You can delete the offline-log of each cache manually but that would need much time and there are still other data like the waypoints that don't get deleted if you don't clear the folder in a file manager.

**Comment by rsudev** [comment]
Clearing offline logs is somerhing different than clearing the history. But I think, it is not possible to clear the offline log of a deleted cache.
BTW - waypoints are not stored on disk, only images and static maps.

**Comment by gcPhil** [comment]
Hmm, added waypoints and offline logs of deleted caches disappear when I clear everything in the .cgeo folder. So they must be stored there, don't they?

**Comment by rsudev** [comment]
In a sense they might be, as the database can be stored there, in that case it could make sense - but that would mean all caches are deleted.

**Comment by gcPhil** [comment]
Yes, I am deleting all geocache-data that way. Not a nice solution but the only one I found to remove all the trash-data of already deleted geocaches and save the phones storage somehow.

**Comment by yellowduck** [comment]
I will re-iterate that clearing history is not an acceptable solution for a user. There are times when I want to retain information - after all I saved it initially for a reason - and having to clear everything is both brute force and an additional step.

I will also re-iterate that you do not ask for permission to drop a cache if it has a waypoint that has been entered by the user. If I take a decision to drop a cache, I accept that such information will be lost, why not adopt the same approach for offline logs?

**Comment by WulfmanDo** [comment]
How i can delete the offline Logs after i delete the caches & lists in cgeo.

 I hate a list with 200 caches for a trip, we found 150x i marked it offline on the trip as found,  at home i export all caches that was found  as fieldnote.  Move the unfound to an other list and then i delete the list with all caches (found) and clear the history.
But wen i open the live map the cacheicons mit red smiles are shown. 

I also have a list with the caches and offlinelogs  i  go to filter in the list by personalnote -> offline log an then i selct the shown caches and delete it, but the same problem.

the offline logs are not delete.  the only way i found is to save the cache again at cgeo, and refresh it, now it is shown as onlinefound loged and a yellow smile, know the filter "don't show found caches on map" is working.

**Comment by gcPhil** [comment]
I am sure it is a bug if you  delete a geocache but its data (waypoints ect) stays in the database and cgeo needs more and more storage as longer you use it. Don't you agree? Why don't you mark it as a bug again?

**Comment by Lineflyer** [comment]
Meanwhile we placed in a workaround so that those caches with pending offline logs will show up again in the history. This allows the offline logs to be deleted by the user and to delete the cache itself after that.

Further improvement will be done under #6186,
