### ISSUE TITLE
Caches lost in history list after version upgrade

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5125]
Two user from support mail:
- History list contains caches stored on the device and caches no longer stored on the device
- Perform version upgrade via Google Play
- History has lost all non-stored caches, only stored caches are still displayed

**Comment by Lineflyer** [comment]
Again users on support mail with this problem on support mail.
Also I could reproduce it myself on version upgrade....made me loose some only offline logged caches as well :(

**Comment by Lineflyer** [comment]
And again a user on support with this problem:
He made offline logs of unsaved caches, after upgrade those were lost.

**Comment by pstorch** [comment]
I'm wandering if the offline logs are really lost or just not visible. Are they still gone when the user searches/loads the geocache again? Getting access to the sqlite file would be good, but not feasible, I guess.
Maybe #6050 could help here. It's not yet in the release, right?
Searched for a while in the DataStore class but couldn't find an obvious place where this can happen.

**Comment by SammysHP** [comment]
After an update a database maintenance / garbage collection is performed. This deletes caches that are not stored, basically the same problem as with the three day delay.

**Comment by Lineflyer** [comment]
This problem was not reported anymore and on recent upgrades I could not confirm such problem. Closing for now.
