### ISSUE TITLE
Wrong position of showcase

### ISSUE THREAD

**Issue by Kucharskov** [cgeo/cgeo#5127]
Hi!

--- System information ---
Device: C6603 (C6603, Sony)
Android version: 5.0.2
Android build: 10.6.A.0.454
Cgeo version: 2015.08.08-NB-c204c6b
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: pl_PL
Geocaching sites enabled:
- geocaching.com: logged in (Nazwa użytkownika OK) / Basic
- opencaching.pl: logged in (Nazwa użytkownika OK)
  Installed cgeo plugins: none
  --- End of system information ---

I can't describe this, please see screenshoot and check c:geo titlebar ;)
![screenshot_2015-08-08-23-50-32](https://cloud.githubusercontent.com/assets/2500114/9152437/8dd38e04-3e28-11e5-9b21-40904a3a39b4.png)

**Comment by SammysHP** [comment]
This might be a problem with the showcase library. Is it the same every time you open the compass?

**Comment by Kucharskov** [comment]
Every time i open compass with each cache

**Comment by Lineflyer** [comment]
That looks familiar to me, but I cannot find any issue reflecting it...

**Comment by rsudev** [comment]
There are two things I note here:
* the titlebar shows fragments of the showcase
* it is partially overlayed by the system header bar
Questions:
* is the overlay of the system header and the c:geo title bar like that everywhere in c:geo?
* what happens if you try that in landscape mode?

**Comment by Kucharskov** [comment]
First answer: No, for example in main menu system header not oberlay c:go title bar
Second answer: Landscape mode in "last cachces"
![screenshot_2015-08-21-23-45-25](https://cloud.githubusercontent.com/assets/2500114/9419815/5da92522-485f-11e5-8a6e-8d0d56e621d7.png)

**Comment by Lineflyer** [comment]
Showcase has been removed.
