### ISSUE TITLE
c:geo only a single process now?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5128]
This might be more a question than an issue:

Sine some weeks (cant tell the time where this behavior started) I do see a different behavior with c:geo in interaction with cache links.

What I was used to:
1. Start c:geo and do something
2. Exit c:geo by pressing home button
3. Open some webpage or an email which contains coord.info links and click on it to open it in c:geo
4. Press back to return to the webpage/mail client

What is different now:
At step 4 I do not always get back to the appwhere I clicked the link but instead return to the session I started in 1.. Only if I repeatedly press the back button until I return to c:geo main menu and press once more on back to leave c:geo I get back to the originating app.

Any thoughts whether I am wrong or what might cause the difference?
To myself the old behavior was more user friendly: I click the link and see the result and can press back to return to where I came from. In parallel I would expect the ¨original session¨ to be kept in the background until I start c:geo itself again.

**Comment by Bananeweizen** [comment]
I'm not sure if this is related to c:geo or the other app. To me it sounds like you experience something like  #1935.

**Comment by Lineflyer** [comment]
I will have to take a look again if it depends on the calling app.
For some reason the behvaiour looks new to me...but might also be the case as I switched from the stock browser to Google Chrome on my tablet recently.

**Comment by Lineflyer** [comment]
This is not reproducible any longer on my device (as I myself described it above).
Right now the beahviour is again as I expected it to be (tested with 2016.02.22-NB).
