### ISSUE TITLE
offline-logged cache don't apear in history

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#5129]
I have searched a Event-Cache over the live-map and logged a "attendet"-Log . It got stored in standart-list (I guess automatic because I forgot to save it before logging) and its red-marked as logged there. But it don't apear in the history and don't got submutted to field-notes.

**Comment by Lineflyer** [comment]
DId you start the logging from the live map popup?
In this case it is a known issue like #4984 or #4086.

**Comment by gcPhil** [comment]
I can not remember if I logged from the popup or opened the cache from popup and logged than. It's possible that I used the popup so you can close this case as a duplicate.
