### ISSUE TITLE
rxandroid incompatible changes

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5130]
The current release 1.0.1 introduces several non compatible changes. Maybe @samueltardieu can investigate?

**Comment by samueltardieu** [comment]
I'll deal with this at the end of the month. Thanks for noticing.

**Comment by Lineflyer** [comment]
We do not use this yet in c:geo, do we?

**Comment by kumy** [comment]
For me since 492bd44 I get `Error:Android Pre Dex: [jackson-databind-2.6.0-javadoc.jar] java.util.zip.ZipException: zip file is empty`
I'll push commit 1a859f1, as a workaround. @samueltardieu please remove if you find that inappropriate.

**Comment by Bananeweizen** [comment]
I have seen the same problem when trying to update rxandroid, so your workaround seems fine to me.

**Comment by samueltardieu** [comment]
@Bananeweizen The problem with RxAndroid is different: it is now offered as an AAR file, and split into several packages.

**Comment by Bananeweizen** [comment]
If you can list all the AARs, I volunteer for converting them to normal libs and inclusion in our repository. However, we generally need to switch to Gradle as main build really soon, as that is not the only place, where this makes trouble...

**Comment by Bananeweizen** [comment]
@samueltardieu Can you please look at this again? I just tried for an hour to get my head around the changes, but I can't make much out of it.

**Comment by samueltardieu** [comment]
Don't sweat over it. RxJava 2.0.0 will be released very soon (RC3 in progress), and while upgrading to it we'll get a new RxAndroid (if needed) as easy to use as RxJava.

**Comment by samueltardieu** [comment]
We use RxAndroid 2, closing.
