### ISSUE TITLE
Log failures from GPX imported by GDAK

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5131]
A user on FB stated that his logs for caches previously imported via GDAK resulted in online logs for wrong caches.

I received a GPX and I assume the following:
The GPX contains wrong(?) IDs like `<groundspeak:cache id="3" available="True" archived="False">`.
The cache is showing up normal in c:geo without any indication that something might be wrong, however when trying to post a log for this cache I can see the following in the debug log:
`22:44:24.704 Warning cgeo 3477  [ModernAsyncTask #3] 404 [Not Found] (739 ms) GET http://www.geocaching.com/seek/log.aspx?ID=3`

So it seems we try to load the log page with the given ID (which is not the real cache ID).
In this case it results in an error as there is no cache with that ID, however as the IDs from GDAK seem to be just counting up from 1 some caches might accidently match an existing ID.

@Bananweizen As seen on FB!

**Comment by Lineflyer** [comment]
@Bananweizen As seen on FB!

**Comment by Bananeweizen** [comment]
We could fix this by always setting the ID derived from the geocode (after importing a GPX). We have that code available at GCConstants.gccodeToGCId().
