### ISSUE TITLE
Support loading existing log pictures 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5132]
According to http://www.opencaching.de/okapi/services/logs/entry.html it should be possible to load the picture associated to log entries of a cache.
@rsudev 
I wonder a little bit, that I did not notice that we don't support this some time before. Is something wrong here or is it really that we never supported it?

**Comment by Lineflyer** [comment]
@rsudev Any feedback?

**Comment by rsudev** [comment]
I'll give it a check

**Comment by Lineflyer** [comment]
@rsudev   Did we support that before....I chatted with a user who also thinks that it worked in the early days of OKAPI support in c:geo.
