### ISSUE TITLE
Support links encoded in some GeoKrety QRCode

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5135]
GK labels sometimes contains QRCode, with encoded http link *(of course I didn't talk about scanning inside c:geo, there are tons of good dedicated applications out there)*.
Link gives access to a page, where user can choose to 'view details' or 'log grabbing'.

Format is: `http://geokrety.org/m/qr.php?nr=<TRACKING_CODE>`

a) We could support those urls as an intent to `LogTrackableActivity` having `Tracking Code` pre-filled with value of `nr`.

b) GKM Api provides a conversion tool to obtain `GK number` from `Tracking Code`.
`http://api.geokretymap.org/nr2id.php?nr=<TRACKING_CODE>`
Response contains only an integer (the `GK number`), or `0` if no match is found.
We could use this to do a lookup then open the `TrackableDetailsActivity` (and remember what was the `Tracking Code`). The user can view the GK goal and decide to take it with him. He could then hit the log button, `LogTrackableActivity` will be shown having `Tracking Code` pre-filled with (remembered) value of `nr`.

**Comment by Bananeweizen** [comment]
I'm in favor of b). Not sure if it is just me, but I would want to see the trackable details first, and would not like to immediately see the logging screen without first verifying the trackable details.

**Comment by kumy** [comment]
In a test I vr done, a) & b) are not incompatible. We can configure two activities supporting the same intent. User can then choose "display or log".
Overall code is ready but I still get issues with displaying a "user's notification" that something is happening in background. Rx & blocking IO stuff... I will need some help there, maybe when @OneEyed is back. I'll publish a new branch soon.

**Comment by OneEyed** [comment]
Hey guys, I think you have the wrong person.  I'm not assigned to this
project.

-Joel

**Comment by rsudev** [comment]
@oneeyed right. Wrong alias context. This is directed rather @samueltardieu

**Comment by kumy** [comment]
PR #5168

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by kumy** [comment]
Reopen for testing

**Comment by Lineflyer** [comment]
@Kumy: can you provide a test case/information for testing. I could myself create a QR with the above mentioned URL in it. Is this correct and what would be the expected behaviour?

**Comment by kumy** [comment]
@Lineflyer you can generate such GeoKrety label using, for example, this link http://geokrety.org/labels.php?id=46684&nr=ISC1YD

The Qr code contains only a link as described in the original message.

**Comment by Lineflyer** [comment]
Tested and OK some weeks ago.
