### ISSUE TITLE
Enable refresh in map based list

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5136]
Enable the refresh menu item in cache lists coming from the map.

**Comment by moving-bits** [comment]
We do have "Manage caches" => "Store offline" already (or meanwhile) - is that what you mean?

**Comment by Lineflyer** [comment]
Almost..
I guess it was about the use case:
- You see stored caches on your live map (e.g. zoomed to the one you will tackle today)
- You select "Show as list"
- You should be able to refresh those

What I can see is, that you can "Store offline"  which will probably do the job.
IMHO OK.
