### ISSUE TITLE
Own geocaches should be marked in lists

### ISSUE THREAD

**Issue by theSeppi** [cgeo/cgeo#5138]
When I have a list of geocaches, the caches I have found are marked by a green border to the left. I think own caches should be marked in a similar way, e.g. a dark green bar, like on found logs.

In below screenshot, the uppermost multi, "Saurierpfad" is owned by me. The green ones I've found so far.
![screenshot_2015-08-14-00-32-44](https://cloud.githubusercontent.com/assets/5564491/9263365/b0efea70-421c-11e5-8ca8-804ce3a04fd9.png)

***
Android 4.4.2, c:geo 2015.08.03

**Comment by Lineflyer** [comment]
Duplicate (or very imilar) to #1528.
We used to have this marking and it was lost during a redesign some time ago.
