### ISSUE TITLE
Is the star overlay well placed?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5139]
While working on #1210 I realized that the the "star" (own cache) overlay hide the "floppy" (saved offline cache) overlay.

I would have placed the "star" icon on the upper left with the "found" group instead of upper right.

Do you agree?

**Comment by Lineflyer** [comment]
AFAIR I had the same thought but someone had an argument to convince me...I just dont remember. Personally I have some found owned caches as I adopted them....maybe that was the thought behind it?

**Comment by kumy** [comment]
Will there be more case of:

* stored and owned caches
Or
* found and owned and stored caches

?

I think the first. However having two different yellow icons at the same place may be difficult to differentiate...

**Comment by Lineflyer** [comment]
I think we should not do any changes here, because:
- There is no real need and users get used to the current look
- As mentioned by @kumy two yellow icons might be more hard to differentiate.

**Comment by kumy** [comment]
So close it for now.
