### ISSUE TITLE
Fieldnote-Upload to gc.com shows "successfull" even if there is no connection

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#5141]
When I export and upload my fieldnotes to gc.com I always get the popup-mesage "upload to geocaching.com successfull" - even if there is no internet-connection and nothing could be submitted.

Sometimes the mobile data connection is not so good and I lost my fieldnotes this way. I can reproduce the bug when I disable wifi and mobile-data and try to upload the fieldnotes!

Even an error-message-popup displaying for one second would not be the best solution because it is easy to overlook and there is now possibility for a second try because the last-upload-date was updated. But an success-message in case of failure is really bad.

**Comment by SammysHP** [comment]
You can't loose your field notes – the file is stored before it is uploaded.

**Comment by rsudev** [comment]
I could reproduce the issue in my phone.
But IMO this is not that severe, as you can:
* redo the upload (when you disable the checkbox for the date check)
* manually upload the stored field notes

**Comment by gcPhil** [comment]
You are absolutely right with both points. In my special case I deleted the fieldnote.gpx after upload because I trusted the success message. And redo the upload would had uploaded hundred old history entry.

**Comment by rsudev** [comment]
You don't need to export field notes from history, you can do so from any list and this will only upload saved logs from that list.

**Comment by gcPhil** [comment]
Oh, that is nice and helpful! I don't knew that. 

It can also be used to get around history limitation: deletion of multiple selected caches.
