### ISSUE TITLE
C-geo available on F-Droid

### ISSUE THREAD

**Issue by sbernard31** [cgeo/cgeo#5143]
Hi,
  Could there any chance to see c-geo available again on F-droid ? 
Thx

**Comment by Lineflyer** [comment]
See #4933 for the ongoing process.

**Comment by sbernard31** [comment]
it seems this is not really the same issue.
The #4933 propose to create an alternative repo which should be added to F-Droid app.
My question is about having c-geo in main F-droid repo.

**Comment by kumy** [comment]
@sbernard31 I  don't think it will come again, see https://github.com/cgeo/cgeo/issues/4933#issuecomment-101585553

**Comment by sbernard31** [comment]
It's a pity :'(. A good open source application with openstreetmap compatibility should be in F-droid.
The google dependency should be optional (if it's not already the case).

**Comment by rsudev** [comment]
To clarify: The google dependencies were an obstacle, but not the final roadblock. They finally refused c:geo due to the API-keys we embed compile-time (for twitter and the various OKAPI-sites). Those are required for the app to work, but not part of the (open) source.
While it is understandable that they don't want to sign up for all those APIs, it is IMO equally understandable that we did not want to open source those keys either. And making this a user-level configuration option (to supply those keys) is no good idea either.

**Comment by sbernard31** [comment]
I see API-Keys and F-droid is a general issue. (not a c-geo problem only)
I'm tempted to say that API-Key on public distributed application is the real issue.
I suppose this must not be so difficult to extract this from the apk.
As keep it secret is just an illusion, several project choose to commit their API-Key.
(If you want to make it no so easy to get,  you could store it in a crypted way, this avoid that anyone could get it just by reading github. they will need to get the code and run it, almost also complicated than search it in the distributed APK)

**Comment by sbernard31** [comment]
OKAPI and Twitter seems to support oauth and if I well understand no API key is needed with oauth.

**Comment by kumy** [comment]
I doubt, you need to "declare" an application to use OAuth and obtain an application private key.

**Comment by Bananeweizen** [comment]
We are not trying to make it impossible to get our keys. We are just trying to avoid that someone can easily use them for other purposes, as there is some effort involved in replacing "burned" keys.

The format of the keys in the Android manifest and properties cannot be encrypted.

And finally, please accept our decision. You can still create a copy of c:geo with _your_ keys and maintain that one for the official F-Droid repo. We will not.

**Comment by SammysHP** [comment]
Sadly f-droid deleted the discussion.

@rsudev said:
> To clarify: The google dependencies were an obstacle, but not the final roadblock.

AFAIR it was one of the blocking issues. The others are: Locus API library, other closed source API libraries we use, keys for the services (Google, Twitter, OKAPI). The problem with Google was one of the main issues: While c:geo runs on devices without Google API, it is required during compile time. There's no easy way to remove all Google dependencies (and some people failed while doing it).

**Comment by sbernard31** [comment]
@kumy, you're right about oauth there is a customer_key and customer secret which is pretty the same thing than API key. But in the [getting started guide] (http://hueniverse.com/oauth/guide/terminology/), they are pretty agree to say that this kind of key _"cannot be trusted and can only be used for informational purposes only, such as in desktop application clients."_

@SammysHP Ok :( ! Too bad there is no way split the project in two parts. One fully freesoftware and another one with proprietary dependencies. For a F-droid user point of view, Locus/google API and others closed source API libraries is surely not needed.

@Bananeweizen strange way to handle a open source discussion... I just try to understand and try to eventually propose solution for blocker issue ...

I hope you guys will keep this idea in mind and maybe one day we will have c-geo back on F-droid, or maybe a fork with no proprietary dependency.

Thx for your time.

**Comment by Buntbart** [comment]
Please put the latest update to the F-Droid-Repo.
TIA!

**Comment by kumy** [comment]
@Buntbart I'll do, thanks for pointing this :)

**Comment by kumy** [comment]
@Buntbart `cgeo 2016.08.27` should be available
