### ISSUE TITLE
transfer all offline logs function

### ISSUE THREAD

**Issue by basti2k** [cgeo/cgeo#5145]
It would be good if you all offline logs that written without an internet connection, can be transfer with once command.

If you select this point, I can  see the cache and the log again, before I executing then this command.
This function could be accommodated in the menu with the three dots on the main screen.

**Comment by SammysHP** [comment]
You can use field notes via the export menu from lists. Some time ago we decided against a batch logging functionality that logs all offline logged caches automatically. Maybe there's even an open issue.
