### ISSUE TITLE
Collapse the searchBar on submit from virtual keyboard

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5146]
Using the searchBar to open a cache/trackable AND validate using the keyboard, then coming back to the main activity.

It's rather annoying to still have the searchBar open with keyboard shown. It would be better to have the main screen clean.

(That's already the case, when you select a cache/trackable from the proposed results.)

**Comment by kumy** [comment]
@Lineflyer reopen for testing

**Comment by Lineflyer** [comment]
Verified the issue with 2015.08.18-NB and retested sucesfull with 2015.08.23.-NB.
Closing!
