### ISSUE TITLE
Overlay not changed while logging from lists

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5149]
* Open a list
* long press a cache, choose "log"
* select a logtype ex: found
* save offline.

Activity "list" shown again, and good overlay is displayed.

Without quitting "list", start the procedure again, just change the log type. When back in " list", overlay is not refreshed.

Quit "list", or open a cache, then back to " list". Good overlay is shown.

**Comment by Lineflyer** [comment]
Retested with 2015.11.29-NB:
This seems to have been solved implicitly while fixing #5225.

**Comment by Lineflyer** [comment]
No longer reproducible with 2016.01.19 release (see also last posting above)
