### ISSUE TITLE
Filter could not be removed

### ISSUE THREAD

**Issue by tobivan79** [cgeo/cgeo#5151]
My list is filtered by type "Earth cache". Clicking onto the recycle bin does not clear the filter settings. 
Setting another condition will not change the filter.

**Comment by kumy** [comment]
@tobivan79 may you provide us your c:geo version and more informations about your current configuration? See "About" -> "System".
Thanks

**Comment by tobivan79** [comment]
--- System information ---
Device: HTC One X (htc_europe, htc)
Android version: 4.2.2
Android build: JDQ39
Cgeo version: 2015.08.03
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: true
Map strategy: auto
HW acceleration: disabled (default state)
System language: de_DE
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins: calendar, contacts
--- End of system information ---

**Comment by kumy** [comment]
Can't reproduce here.

Don't you have a general filter enabled? Could you please "long press" on the most right icon on the second line of the main screen? (the icon representing a switch)

**Comment by tobivan79** [comment]
There's only shown "Event Cache" (not Earth Cache as I wrote at the beginning) in the filter panel above the list. 

The switch button solved my problem. Now I can see all caches again. 
So I think the "recycle bin" icon is not supposed to clear the filter if it was set on the main screen?

**Comment by kumy** [comment]
> The switch button solved my problem. Now I can see all caches again. 

Good :)

> So I think the "recycle bin" icon is not supposed to clear the filter if it was set on the main screen?

Exact, but seem unclear.

I'll close, @ c:geo team, please reopen if you feel we should update something.

**Comment by SammysHP** [comment]
That should not be a "recycle bin" icon, but a switch icon.

**Comment by kumy** [comment]
@SammysHP are you sure to want an icon change?

>Exact, but seem unclear.

I meant, _unclear_ that "there are two level/types of filter", I remember to have been also troubled before, with the exact same case.

**Comment by SammysHP** [comment]
![switch](https://cloud.githubusercontent.com/assets/922874/9477893/e17b8cce-4b74-11e5-83e6-5593140f7eae.png)

**Comment by kumy** [comment]
ho ok, just select the filter icon, then you'll see the recycle bin

**Comment by SammysHP** [comment]
Oh, that one. :)
