### ISSUE TITLE
New smile icons

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5156]
I can't remember where we've talked about the red smile icon that was to "much like the orange" one.

As we don't have the original images as vector format, I've chosen to start over.

Here are the proposed new icons.
![marker_found](https://cloud.githubusercontent.com/assets/176794/9530092/1e77dcb0-4cfe-11e5-968f-f1c0f10bf932.png) ![marker_found_offline](https://cloud.githubusercontent.com/assets/176794/9530093/1e7b825c-4cfe-11e5-9cf4-0feec3dfcf0f.png) ![marker_not_found_offline](https://cloud.githubusercontent.com/assets/176794/9530214/bc78b22c-4cfe-11e5-83c7-4fd0942cc132.png)

Original icons from [Tango Desktop Project](http://tango.freedesktop.org/Tango_Desktop_Project)

> Though the tango-icon-theme package is released to the Public Domain, we ask that you still please attribute the Tango Desktop Project, for all the hard work we've done. Thanks. 

Can I go with this? Someone has better resources?

**Comment by SammysHP** [comment]
DNF is blue on gc.com.

**Comment by kumy** [comment]
I've found the related issue #3129.
See thrid comment for colors.
It easy to have DNF icon as blue. I'll create one but we have to make a choice :)

**Comment by kumy** [comment]
New:
![marker_found](https://cloud.githubusercontent.com/assets/176794/9530092/1e77dcb0-4cfe-11e5-968f-f1c0f10bf932.png) ![marker_found_offline](https://cloud.githubusercontent.com/assets/176794/9530093/1e7b825c-4cfe-11e5-9cf4-0feec3dfcf0f.png)
![marker_not_found_offline](https://cloud.githubusercontent.com/assets/176794/9531578/e8b3d79c-4d06-11e5-84ff-919010b3ebe7.png) ![marker_not_found_offline-blue](https://cloud.githubusercontent.com/assets/176794/9531498/6e717f98-4d06-11e5-95e1-59a5fb296d99.png)


Old:
![marker_found](https://cloud.githubusercontent.com/assets/176794/9531441/3d58616a-4d06-11e5-84fb-5e9de58fb6e2.png) ![marker_found_offline](https://cloud.githubusercontent.com/assets/176794/9531442/3d5ac252-4d06-11e5-9061-38f99deae07a.png)
![marker_not_found_offline](https://cloud.githubusercontent.com/assets/176794/9531443/3d5e375c-4d06-11e5-93cd-07cf5024e5de.png)

**Comment by samueltardieu** [comment]
I like the proposed ones.

**Comment by kumy** [comment]
Let's see how it goes as blue.

Wait for comments.

**Comment by kumy** [comment]
While creating icons overlay for mdpi resolution ;
* icons looked too much complicated for such icon size (12x12 px)
* no vectorized images for the new icons

I've created missing ones, and simplified the icons to make them more compliant with Android [recommendations](https://www.google.com/design/spec/style/icons.html)


xhdpi (22px): ![marker_archive](https://cloud.githubusercontent.com/assets/176794/9723103/cd77c3a0-55ba-11e5-8f25-39e3691a2fc1.png)![marker_found](https://cloud.githubusercontent.com/assets/176794/9723101/cd74d79e-55ba-11e5-8444-504c99ec2fa5.png)![marker_found_offline](https://cloud.githubusercontent.com/assets/176794/9723102/cd770e42-55ba-11e5-9b88-2da006a8b5f3.png)![marker_maintenance](https://cloud.githubusercontent.com/assets/176794/9723105/cd7d217e-55ba-11e5-96c4-f4f3e4a147fa.png)![marker_note](https://cloud.githubusercontent.com/assets/176794/9723104/cd7a3806-55ba-11e5-8614-a832c69eddcb.png)![marker_not_found_offline](https://cloud.githubusercontent.com/assets/176794/9723106/cd7da306-55ba-11e5-8a12-9a3c11ee92e8.png)![marker_owner_maintenance](https://cloud.githubusercontent.com/assets/176794/9723107/cd932500-55ba-11e5-903c-3fee1bff6b55.png)![marker_unknown_offline](https://cloud.githubusercontent.com/assets/176794/9723108/cd955226-55ba-11e5-8013-336c94ec0889.png)

hdpi (16px): ![marker_archive](https://cloud.githubusercontent.com/assets/176794/9723114/f59d3a86-55ba-11e5-91e3-8f26b110469a.png)![marker_found](https://cloud.githubusercontent.com/assets/176794/9723116/f5a6ed10-55ba-11e5-9008-a1c35b386e7d.png)![marker_found_offline](https://cloud.githubusercontent.com/assets/176794/9723117/f5a9f226-55ba-11e5-8d02-478e78aa4fa0.png)![marker_maintenance](https://cloud.githubusercontent.com/assets/176794/9723115/f5a3bb4a-55ba-11e5-8531-1399a16466c7.png)![marker_note](https://cloud.githubusercontent.com/assets/176794/9723118/f5ab2ab0-55ba-11e5-930c-e48cd519522e.png)![marker_not_found_offline](https://cloud.githubusercontent.com/assets/176794/9723119/f5ad761c-55ba-11e5-9c5b-ac607ff861fe.png)![marker_owner_maintenance](https://cloud.githubusercontent.com/assets/176794/9723120/f5bb4abc-55ba-11e5-84bb-ee9297a77974.png)![marker_unknown_offline](https://cloud.githubusercontent.com/assets/176794/9723121/f5c3a84c-55ba-11e5-9dbe-0b38883bddad.png)

mdpi (12px): ![marker_archive](https://cloud.githubusercontent.com/assets/176794/9723125/0d3faa02-55bb-11e5-8bba-895b1037f0a9.png)![marker_found](https://cloud.githubusercontent.com/assets/176794/9723128/0d4c27aa-55bb-11e5-80a4-5754a898bfee.png)![marker_found_offline](https://cloud.githubusercontent.com/assets/176794/9723129/0d4cd0f6-55bb-11e5-9b69-ec756336511c.png)![marker_maintenance](https://cloud.githubusercontent.com/assets/176794/9723126/0d46209e-55bb-11e5-9df7-e26dade130e5.png)![marker_note](https://cloud.githubusercontent.com/assets/176794/9723127/0d4aa286-55bb-11e5-8dc9-36b46d3b7be6.png)![marker_not_found_offline](https://cloud.githubusercontent.com/assets/176794/9723130/0d4f6c58-55bb-11e5-8b67-f483a413f21a.png)![marker_owner_maintenance](https://cloud.githubusercontent.com/assets/176794/9723132/0d73a924-55bb-11e5-88cf-c0fee91de121.png)![marker_unknown_offline](https://cloud.githubusercontent.com/assets/176794/9723131/0d62c14a-55bb-11e5-8617-70952aefc892.png)

@Lineflyer what do you think about such icons?

If someone would like to hack, see commit https://github.com/kumy/cgeo/commit/030d814a51761d0f485a5c2fd5f5a8d3ea91a281 for original vector images.


![screenshot_2015-09-07-23-56-24](https://cloud.githubusercontent.com/assets/176794/9723198/3db6ec62-55bc-11e5-8ad7-e979b990afa6.png)![screenshot_2015-09-07-23-53-35](https://cloud.githubusercontent.com/assets/176794/9723197/3db029a4-55bc-11e5-9d70-803c50824a4b.png)

**Comment by Bananeweizen** [comment]
I like those new proposed icons, as they are better recognizable on that screenshot. Any chance you could also have a look at the star icon? It is different from the other ones in that it does not have a sharp, dark border. Therefore in some places of the screenshot the upper part blends with the white background, making it harder to recognize.

**Comment by Lineflyer** [comment]
Really nice!!

What is that? "Needs archive"? https://cloud.githubusercontent.com/assets/176794/9723103/cd77c3a0-55ba-11e5-8f25-39e3691a2fc1.png

**Comment by kumy** [comment]
@Bananeweizen Easy! Here is a star icon:
![marker_own](https://cloud.githubusercontent.com/assets/176794/9729933/53d02732-5613-11e5-8e33-3f1a2d0fee03.png)![marker_own](https://cloud.githubusercontent.com/assets/176794/9729921/41c59e6e-5613-11e5-88a4-720ec5ba41f9.png)![marker_own](https://cloud.githubusercontent.com/assets/176794/9729928/4844f03c-5613-11e5-8829-9399a67c4de3.png)

@Lineflyer ![cd77c3a0-55ba-11e5-8f25-39e3691a2fc1](https://cloud.githubusercontent.com/assets/176794/9729974/b3458a7c-5613-11e5-88c4-fa6a7f3f8df7.png) is for `NEED_ARCHIVE`, or `ARCHIVE` LogType (Howerever, I'm not 100% satisfied with it, it's a bit twisted, and borders are too fat)

**Comment by Lineflyer** [comment]
We can change that "archive" icon again later on if needed. For the start it will do.
The star icon does also look ok.

Can you apply these changes.
So we could go for merging `master` into `release` afterwards.

**Comment by kumy** [comment]
@Lineflyer New icons pushed to master.

**Comment by kumy** [comment]
Closing for now.
