### ISSUE TITLE
TB logging does not remember last log type

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5159]
This was implemented in the past, but now the default log type does always seem to be ¨Retrieve¨ although I posted a ¨Note¨ log for another TB before.
2015.08.26-NB

**Comment by samueltardieu** [comment]
Interesting: I just committed (9a081eff0b00d6c04b28bf2a24cd0c5946bf7eb8) a few hours ago a patch to not retrieve the default log type from the settings because it was *never* set there and always returned "Retrieve". I guess the commit should then be reversed and the root cause fixed.

**Comment by samueltardieu** [comment]
It looks like one call to `setTrackableAction()` was removed in 707c30a52b36063c76cb0370ddcd1fb3d82dffa1 on September 21. @kumy, do you want to have a look?

**Comment by kumy** [comment]
@samueltardieu ok, I'll look

**Comment by kumy** [comment]
@Lineflyer assigned for testing.

**Comment by Lineflyer** [comment]
Tested and working with 2015.08.30-NB1
