### ISSUE TITLE
Wrong progress prompts when sending log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5160]
2015.08.26-NB

After implementing the new log sending progress prompts, there seems t obe an issue either in programming or at least in (german) translation:
When sending a log with picture and GCVote I doo see:
1) Sende Log und Bild (or similar)
2) Bild wird gesendet
3) Sende Bewertung

It seems in step 1 only the log is sent, so the string or the general calling of this string should be adapted.

**Comment by kumy** [comment]
Exact, that don't make sense.

Should I instead update the dialog title when there is an attached image?

**Comment by Lineflyer** [comment]
If the picture progress is now reported separately we could just use the normal string (the one which is used if there is no log picture) in step 1

**Comment by kumy** [comment]
That s what i ve prepared. Btw I ve found that uplaoding picture fails. I ll publish a patch soon. (Not at home right now)

**Comment by kumy** [comment]
@Lineflyer assigning for testing.

Upload pictures also repaired as for caption/description were not saved/displayed until cache refresh

**Comment by Lineflyer** [comment]
Tested and OK with 2015.08.30-NB1.
New heading for progress window shown and sequencce OK.
