### ISSUE TITLE
static code analysis not working

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5161]
It seems that the static code analysis in the IDEA/AndroidStudio configuration of our project is not running automatically. I have just been fixing
* unused imports
* Android lint warning
* nullable contradictions

All of those should be found in IDEA/AndroidStudio too, without _explicitly_ running an analysis, i.e. during normal compilation. Can one of the experts for those tools please check? Take 17dac8af539894a170b7ef142f1f5ab88a123779 for reproduction and the following 3 commits to see the violations shown in Eclipse.

**Comment by kumy** [comment]
* unused imports
Are already configured to be shown but they doesn't prevent building.
@samueltardieu should we activate the `Optimize imports on the fly` option? However, I'l unsure it will solve the root problem.

* Android lint warning
As an example, the `parcel.recycle();` you've added at the end of `Imagetest.java` doesn't provide a warning (if I remove it). However, `Missing recycle() calls` is configured as a warning.

* nullable contradictions
`@NotNull/@Nullable problems` is activated.

@samueltardieu may you also have a look please?

**Comment by Bananeweizen** [comment]
summarizing discussions from chat, it simply seems not possible to have all those checks run automatically all the time like in Eclipse. :(
