### ISSUE TITLE
Location not updated properly

### ISSUE THREAD

**Issue by RalfJung** [cgeo/cgeo#5162]
It seems that c:geo does not update what it thinks it my current location after it has been started.

Two things that happened yesterday:
* Start c:geo wth location still turned off
* Turn on location
* Wait until OsmAnd sees me in my current location
* Select "Nearby", "Current location" in c:geo
* c:geo selects caches on the wrong continent, it seems to use the previous location I have been searching...

Later, I restarted c:geo. Then at least it had me in the right city, but
* Select a cache
* Click the circle with the four bars at the top, so that there's a circle filling it
* Walk around
* c:geo does not update my current location
The "location service" icon does not even appear in Android's status bar. When I switch to OsmAnd, it does appear, and the blue spot follows my walking.

This is using c:geo 2015.08.03 on a device without play services, but with open-source replacements for some of them. (Not that I think that matters, but who knows^^).

**Comment by samueltardieu** [comment]
Can you please test again by disabling the use of Google Play services in cgeo Settings/System, so that those open-source replacements are not used at all?

**Comment by RalfJung** [comment]
Will do today when we try the next caches :)

I have UnifiedNlp installed, so it should be able to get non-GPS
positions - but then wifi/cell tower is not nearly good enough for
geocaching anyway, so whatever

**Comment by Lineflyer** [comment]
And please kindly attach your system information from About c:geo - System

**Comment by RalfJung** [comment]
Indeed, this worked out perfectly. Thanks a lot!

Which Google Play Services functionality are you using? I should probably report this against the open-source replacement.

**Comment by samueltardieu** [comment]
We use the location provider, but we often change the kind of precision we require (GPS-based or not-GPS-based) depending on what we obtained before. All this is located in https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/playservices/LocationProvider.java if you want to have a look.
