### ISSUE TITLE
Logging progress: GEOKRETY should not be all uppercase

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5163]
but instead we should use one of the localized strings we already have (was unable to find the uppercase version in the strings... hard coded?)

**Comment by kumy** [comment]
The string comes from what the connector "pretend to be". I ll use a string from localization.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Tested OK with 2015.08.30-NB1
