### ISSUE TITLE
GK name truncated while logging cache

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5164]
I've seen that multiple times, in `LogCacheActivity` with, say, long list of GK in inventory.

Some GK have their name truncated, most of the time this happens with the first characters.

This not always happens on the same item.

![screenshot_2015-08-30-20-38-59](https://cloud.githubusercontent.com/assets/176794/9568868/ce8b640e-4f57-11e5-87ce-3d9c0e20b3f0.png)

Here, the name is "Mickey plane".

**Comment by Lineflyer** [comment]
Maybe some special character in the name?

**Comment by samueltardieu** [comment]
@kumy: can you reproduce this reliably? Does it happen also without the Geokrety proxy?

**Comment by kumy** [comment]
> Does it happen also without the Geokrety proxy?

No, it was specific to GK

I don't hit this bug anymore. Let's close
