### ISSUE TITLE
Have cache menu items in single cache map

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5169]
Open a map directly from a cache. As long as it contains only this single cache (is not switched to life map) it should also contain the menu items for the cache, e.g. for logging.

**Comment by Lineflyer** [comment]
Let us disregard this:
If you have the single cache map you may click on the cache icon or any waypoint icon to afterwards perform cache related actions.
I somehow prefer to have the map menu always look the same as the user potentially does not understand the difference between cache map and other maps.
