### ISSUE TITLE
Edit log by invoking browser

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5170]
I've been asked multiple times of log editing is possible. While I don't want to implement that directly in the app, we could still link to the browser page for editing.

**Comment by akkatracker** [comment]
How would you do this - on a long press of your own log?

**Comment by sternli** [comment]
Good idea! Thank you!

**Comment by moving-bits** [comment]
Wouldn't that be superseded by #2012?
So if @eddiemuc plans to work on #2012 I would close this issue.

**Comment by eddiemuc** [comment]
This is actually already implemented and released: log entry context menu has option to open log in webpage. Thus this can be closed.
