### ISSUE TITLE
Add to calendar missing for past events?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5172]
2015.08.30-NB1

It seems either there is a problem with event cache GC60RZK or it is not possible to add an event which is in the past?

If this is intentional I vote for removing that restriction. The missing option is not really intuitive and it should be up to the user whether he wants to add an event in the past.
Additionally there seem to be problems with users on some timezones (maybe erratically set on their phone) leading to fail to add it due to the missing menu.

**Comment by Bananeweizen** [comment]
What would be the use case for that? It is possible to add events of today and the future to the calendar. And I believe that is sufficient. I rather believe that more people would complain, if we changed this to allow useless calendar entries.

**Comment by SammysHP** [comment]
I also vote for removing this limitation. Sometimes I forget to add an event to the calendar, but want to do it later, after the event.

**Comment by Lineflyer** [comment]
FYI: Another request with @SammysHP argumentation came in last week on support mail.

**Comment by samueltardieu** [comment]
I would also prefer to be able to add past events to the calendar, for reference purpose. We could add a warning dialog with a confirmation ("You are adding an event in the past / Confirm  /Cancel").
