### ISSUE TITLE
Nearby search result lost after c:geo was in background

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5173]
2015.08.30-NB1
- Perform nearby search
- Result contains unsaved and saved caches
- Press home button to ¨exit¨ c.geo
- Open c:geop again

The shown search result is now only containing the saved caches. Unsaved caches are no longer shown.
I am not sure how it was in the past, but the fact that only saved caches are left is new to me. I assume, that either the list was still there or a the search equest was repeated.

**Comment by samueltardieu** [comment]
When you say "Perform nearby search", you mean use the top-middle icon on cgeo home screen? I cannot reproduce this.

**Comment by rsudev** [comment]
I was able to reproduce this (using the nearby button on the home screen). As I have two sources active, 40 caches were shown initially.
After pressing 'home' and then coming back to c:geo some caches are missing (I observed specifically non-stored ones that are now gone). The title still says 40 caches, the footer reads 'load more (currently: 37)'

**Comment by Lineflyer** [comment]
I do also have two sources active (geocaching.com and opencaching.de). @rsudev exactly describes my scenario.

**Comment by Lineflyer** [comment]
No longer reproducible with 2017.08.26-NB (two sources active as described above).
