### ISSUE TITLE
Remove gc-based address search

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5175]
Groundspeak has asked us to remove gc-based address search, as they will get charged for that in the future (see mail in g+ developer group).
Already since some time we primarily use Android or Mapquest for geocoding, but gc is still there as a fall-back.

**Comment by SammysHP** [comment]
Please note that Mapquest (didn't know we use it) closed their free API.

http://devblog.mapquest.com/2015/08/17/mapquest-free-open-license-updates-and-changes/

**Comment by samueltardieu** [comment]
We use if as a fallback if there is an error with Android geocoder, for direct and reverse geocoding.

**Comment by SammysHP** [comment]
Regarding the request by Groundspeak: We do not use their API key, but we use their website (to search by address). We always use their website like a normal user would do. And a normal user would use the search on their website. Consequently it makes no sense to remove the address search as long as they provide it on their website.

**Comment by samueltardieu** [comment]
@SammysHP That was my initial reaction to their request, but our users have other ways of looking up addresses as they are on Android. Let's be nice.

**Comment by SammysHP** [comment]
We need at least one fallback for people who do not use Google on their phones. (I assume that the geocoding functionality is only available with Google API / GPS / etc. installed.)

**Comment by samueltardieu** [comment]
We have MapQuest as a fallback (for 15000 requests a month starting September 15). And the geocoder comes with Android, not with Google Play Services. I suppose people not using Google have another source installed.

**Comment by SammysHP** [comment]
Is there a way to see our used quota?

**Comment by samueltardieu** [comment]
Yes, with my account (I created the key). Our users do a lot of requests…

```
Aug 27, 2015 	22243
Aug 28, 2015 	24287
Aug 29, 2015 	34609
Aug 30, 2015 	34631
Aug 31, 2015 	18007
Sep 1, 2015 	16686
Sep 2, 2015 	17664
```

**Comment by mucek4** [comment]
Is there's way to see how many requests we do on GS?

**Comment by SammysHP** [comment]
So less than one day and the Mapquest provider won't work anymore. Is it possible that there is a problem with the Android provider?

**Comment by samueltardieu** [comment]
> Is it possible that there is a problem with the Android provider?

Maybe, but there is a unit test to check that it is working well.

**Comment by SammysHP** [comment]
It might work well on the emulator, but you won't notice a failure in the field as long as there's a fallback.

**Comment by Lineflyer** [comment]
Which geocoder do we use to obtain the location name of the current coordinates displayed on the main screen. Does this also fall back to Mapquest?

**Comment by rsudev** [comment]
We use AndroidGeocoder with fallback to Mapquest there

**Comment by Lineflyer** [comment]
This fallback could be removed IMHO as the feature can be considered optional.

**Comment by rsudev** [comment]
Looking at the behaviour of my phone after the change I can clearly see that the android geocoder runs through the google play services (so it does not work for me as I block those in my firewall)

**Comment by samueltardieu** [comment]
it runs through Google servers, but it is not part of the Google Play Services *per se*, it is an Android API.
