### ISSUE TITLE
Remove mapquest geocoding for current location

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5177]
Follow up of #5175 

I wonder a little about this high amount of requests to mapquest mentioned in that issue depsite the fact that it is only the fallback option in a user initiated procedure.

My assumption would rather be that this is not caused by geocoding for adress search but by the geocoding done for showing the current location on the start screen. This is more likely to happen than a user initiated search by adress IMO.

In this case I suggest to remove the mapquest fallback at this place but keep it for adress search to maybe extend the 15000 limit.

**Comment by samueltardieu** [comment]
:+1:
