### ISSUE TITLE
Wrong date of saved log on cache details screen after refresh

### ISSUE THREAD

**Issue by kia71** [cgeo/cgeo#5180]
version 2015.09.04-NB

I am watching the details screen of a previously found cache.
I see 'Found' with its date in status row.
I enter a log to the cache and save it.
I return to the details screen.
I see 'Saved Log' with the current date and 'Found' in status row.
I press the Refresh button.
Date of 'Saved Log' is replaced with the date of 'Found' on cache details screen.

**Comment by rsudev** [comment]
Did a short cross-check, confirmed.

**Comment by rsudev** [comment]
It looks like we currently have only one storage for this date, so the found date retrieved again through the refresh overwrites the visited date set when logging offline. The date the stored log is associated with seems to still be correct, though.

**Comment by Lineflyer** [comment]
I don't see the real problem here. Found date is overruling the offline saved date which is, given the normal usage/logging flow, perfectly fine.
