### ISSUE TITLE
Duplicate filter for offline logs

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5183]
As noticed by one of our translators, the filter for offline logs is actually implemented twice.
https://crowdin.com/translate/cgeo/80/en-hu#14917:drl:531:kia71

**Comment by rsudev** [comment]
Technically yes, conceptually do they address a different context, so I am not sure if I see this as an issue...

**Comment by Bananeweizen** [comment]
I'm still hoping to find the time to finally rework the filter UI, where the current categories would mostly vanish. So take it as a small step towards that rework. :)
