### ISSUE TITLE
Update Wiki about "Low power mode"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5185]
@samueltardieu Just a reminder: This is now almost outdated and needs an udpate: 
https://github.com/cgeo/cgeo/wiki/Low-power-mode

I would appreciate if you could add the new methods for direction and its priorities as well to that or another Wiki entry.

**Comment by samueltardieu** [comment]
Original entry updated, and [Heading](https://github.com/cgeo/cgeo/wiki/Heading) entry added.
