### ISSUE TITLE
switch to gradle as main build system

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5187]
Right now our main build is still Ant based, as that is supported in Eclipse, IDEA/AS and on Jenkins. I propose that after our current release we switch to a Gradle based main build and remove the Ant one.

Reasons:
* More and more Android libraries are not packaged as JAR anymore, but as AAR only. For Ant or Eclipse based builds those have to manually be repackaged. I've done this since quite some time for the Google play services and similar libs in our repository, but this task is getting harder every time due to no easy identification of the right source artifacts, transitive dependencies, classes occuring multiple times in repackaged libs and so on.
* The (currently still experimental) Java to Dalvik bytecode compiler for Android requires Gradle. We can expect that tool chain to replace the Java to class to DEX to... toolchain of today in the near future.
* The current state slows down our adoption of other new technologies, e.g. lots of small libraries on github, which could easily be consumed with gradle, the most recent compat libs with Material design back port and so on.

Of course this has consequences. I actually expect us not to be able to have a working compilation inside of Eclipse anymore due to it not understanding the gradle dependencies, thereby potentially requiring every Eclipse user of our developers to switch to Android Studio.

I'd be happy about feedback of whether you feel we should take that step, especially if you are using Eclipse (like myself).

I guess that we can replace additional functionality of our Jenkins build (coverage measurement and such) with gradle based functionality, but I'm a noob in Gradle. So this surely would require some team effort (and maybe lead to some days of Jenkins not building anything).

**Comment by samueltardieu** [comment]
This is definitely the way to go!

**Comment by rsudev** [comment]
Even though my previous experience with Android Studio is not too satisfactory (I already had to use it another project I came across recently), I deem this change inevitable, as the additional burden to keep the deprecated environment going is not worth it.

**Comment by rahu** [comment]
anybody working on this?

**Comment by Bananeweizen** [comment]
I feel we should now switch to the gradle build as the only build and disable the ant based builds on CI. What we have:

* application is fully build, either as release (including signing) or debug version
* tests are running fine
* keys are handled nicely (private.properties and keys.xml) and error messages are given if not available
* user login is automatically restored by the build script when running tests
* normal version and NOJIT version
* version names and codes are calculated based on date/commit ID
* dependencies of the gradle build are more recent than those in the ant build (which means there really _are_ differences in build outputs)

My latest commit just broke the compilation in the Ant/Eclipse build because they both miss to generate some piece of code, that is automatically generated during the build (but only with recent Android tooling). We can temporarily fix that by commenting a small piece of code in AboutActivity.java. We could also fix it by injecting some ant code into the "-precompile" task of the build script to fake this generation step, but I'm getting tired of such workarounds.

What's missing:
* no support for release candidate naming scheme, but that should be easy
* copying nightly builds and similar "publishing" actions not yet available
* no code coverage report yet
* no connection between CI and github yet (reporting build result on commit/PR)

I might have missed further things. Nevertheless I suggest that we disable all the existing ant jobs, and start creating new jobs (or better even: extensions to the main build script) for everything missing.

Just as a note: We can still build a release from the release branch with the old job.

Comments?

**Comment by mucek4** [comment]
As CI is really wacky after update (and still 32 bit) I also suggest upgrading it. I promised a long time ago to do that but still didn't :(
Would it be wise to move everything to new CI with Gradle or it does not matter?

**Comment by samueltardieu** [comment]
Since the builds produced right now on the CI are different from what the
developers build, I think it is more urgent to switch the CI to Gradle.
Then once things are working the

**Comment by Lineflyer** [comment]
One question:
Seems there is no nightly build since some days.
Is it possible to reenable the CI to build nightlies?

**Comment by Lineflyer** [comment]
Also the nightly for nojit seems no longer working (see mail to cgeo-dev)

**Comment by rsudev** [comment]
The normal nightly build should be up and running again (sort of). nojit will likely follow in the next days.

**Comment by Bananeweizen** [comment]
closing this quite broad issue, as the general switch is complete
