### ISSUE TITLE
Remove orange circles for lists?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5188]
While testing the RC version I noticed a big visual difference for basic members:
While the nearby results looked like the saved lists in the past now every (unsaved or previously unloaded) cache will have orange circles.
While this is technically correct it looks strange and users might be confused by that.
What do you think?

Here is how it looks:
![screenshot_2015-09-12-12-29-18](https://cloud.githubusercontent.com/assets/949669/9831113/0e3cab34-594a-11e5-9017-61549f1c539b.png)

**Comment by SammysHP** [comment]
:+1: Yes, it makes sense, but looks really bad and should be removed before the release.

**Comment by kumy** [comment]
How does it looks like on the map? I think they also have the orange circles. So they may also get confused by that? The FAQ already have an entry for that [circles on the map](http://www.cgeo.org/faq.html#map-orange-circles), couldn't we add one entry for the circles in lists? Maybe we could add a setting to disable them in lists?

However, a pending fix is ready for disabling them: https://github.com/kumy/cgeo/commit/162668510d51076c4ee768d6e833f80126ad9b07

**Comment by SammysHP** [comment]
It works well with the map UI, but not in the list.

**Comment by Lineflyer** [comment]
This is not worth a setting IMO.
I am still in favor to leave this out in the lists completely but only keep it on the map.

Regarding the UI @SammysHP is right:
For the map the orange circle alerts the user, that the icon is not shown at the precise position.
On the list the information, that the cache has no coords is not relevant at this step.

**Comment by kumy** [comment]
If so, let's merge https://github.com/kumy/cgeo/commit/162668510d51076c4ee768d6e833f80126ad9b07 :)

Ok to commit that change on release?

**Comment by Lineflyer** [comment]
Yes, please do.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: kumy <notifications@github.com> 
Datum: 14.09.2015  16:50  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu> 
Betreff: Re: [cgeo] Remove orange circles for lists? (#5188) 

If so, let's merge kumy@1626685 :)

Ok to commit that change on release?

**Comment by kumy** [comment]
@Lineflyer assigned for testing.

**Comment by Lineflyer** [comment]
Tested and OK with 2015.09.14-RC.
