### ISSUE TITLE
Cache icons in lists on low res device mispositioned

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5189]
While testing the RC version I do see some mispositioning of the icons. Also the orange circle looks a bit clustered.
This is from a HTC Wildfire S510 (Android 2.3):
![20150912_120519](https://cloud.githubusercontent.com/assets/949669/9831119/4137daea-594a-11e5-9142-0411af0ead11.jpg)
![20150912_121031](https://cloud.githubusercontent.com/assets/949669/9831120/41420984-594a-11e5-8791-d820b4b3bd07.jpg)

Sorry, only pictures of the device as it has no built in screen capture.

**Comment by kumy** [comment]
Effectively, this a bit ugly.

**Comment by kumy** [comment]
Here are pictures of what it looks like in:
xxhdpi / xhdpi / hdpi / mdpi / ldpi
![xxhdpi](https://cloud.githubusercontent.com/assets/176794/9833663/0a4eba34-59a0-11e5-904e-ad2934c4779a.png) ![xhdpi](https://cloud.githubusercontent.com/assets/176794/9833665/0c0da83a-59a0-11e5-83c3-07a3d067f343.png) ![hdpi](https://cloud.githubusercontent.com/assets/176794/9833667/0f1d33e2-59a0-11e5-9520-4c45f58e3d06.png) ![mdpi](https://cloud.githubusercontent.com/assets/176794/9833668/1141f95a-59a0-11e5-885d-58f8bca674c2.png) ![ldpi](https://cloud.githubusercontent.com/assets/176794/9833671/2c418220-59a0-11e5-8945-c72f2e3776c3.png)

In **mdpi** and **ldpi** the cache icon move down.
I think values at https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/utils/MapUtils.java#L26-L31 are wrong for the two first quadruplet.

**Comment by kumy** [comment]
In **ldpi** there is two different marker sizes, one for the cache, the other for the additional waypoints. This explain the icon drift in list view.

Is this really the wanted behaviour?
![ldpi](https://cloud.githubusercontent.com/assets/176794/9833699/621016fe-59a1-11e5-8c1e-08ba0f40cd40.png)

**Comment by rsudev** [comment]
I took a short look and failed to find where this behaviour emerges (which IMO is not wanted).

**Comment by kumy** [comment]
What about something like that?
![all](https://cloud.githubusercontent.com/assets/176794/9838710/491b15c2-5a64-11e5-8371-6fbb561a2ae6.png)
![screenshot_2015-09-13-21-43-42](https://cloud.githubusercontent.com/assets/176794/9838711/4cd387ee-5a64-11e5-9234-68b5ab98d301.png) ![screenshot_2015-09-13-21-45-03](https://cloud.githubusercontent.com/assets/176794/9838713/4d0da424-5a64-11e5-8d98-9c3ce7ee22c6.png) ![screenshot_2015-09-13-21-45-18](https://cloud.githubusercontent.com/assets/176794/9838714/4d12df7a-5a64-11e5-9ab7-f6e2a2bd1ff7.png) ![screenshot_2015-09-13-21-46-32](https://cloud.githubusercontent.com/assets/176794/9838712/4d022f22-5a64-11e5-9680-feb0eb4f42f3.png) ![screenshot_2015-09-13-22-11-51](https://cloud.githubusercontent.com/assets/176794/9838729/986f2730-5a64-11e5-821a-ef3788859d77.png)

**Comment by Lineflyer** [comment]
@kumy: This apporach only for ldpi or in general for the icons in lists?

**Comment by kumy** [comment]
@Lineflyer this was for a general purpose... it would be too complicated to change that based on resolution

**Comment by Lineflyer** [comment]
I suggest to postpone this proposal for the next release to review on all devices.
So basically we could merge to `master` if others agree.

**Comment by kumy** [comment]
I think I fixed it on all resolutions...
https://github.com/kumy/cgeo/commit/364771cc6402cf07814408e185364d4e5b5e15d3

![result](https://cloud.githubusercontent.com/assets/176794/9858871/6ee9e67e-5b23-11e5-8ccc-ff59e4344c11.png)

**Comment by Lineflyer** [comment]
Your last screenshot should be OK. I vote for using this.
If we want to include it into this release we should merge right away so that we can get it out before I leave to vacation if you want to crosscheck it.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Looks very good on my devices and especially on the problematic HTC Wildfire S510.
Tested with 2015.09.14-RC1
