### ISSUE TITLE
Missing "Offline" text in lists

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5190]
With the redesign of cache overlay icons the textual note "Offline" has been removed.
While this is OK in the search results (as the disk icon is shown) now the saved caches list does not have any indication, that those caches are stored for offline.

While this is implicit and should not lead to any uncertainty, still some users of the RC version are confused by the missing "Offline" in the lists.
I suggest to either introduce it again or also show the disk icon in the saved lists (while I prefer the first in order not to clutter the saved list by always the same overlay).

Opinions?

**Comment by Bananeweizen** [comment]
Actually, in stored lists the "Offline" text was not shown, even before the recent change in 0ae89a81fa9c3140cbf78b82804d623bb5385627. Nevertheless I also vote for re-introducing the text, as I'm one of those people who scan the text, but not the image, when reading a list. And the space used by that part of the text is otherwise unused, anyway.

**Comment by kumy** [comment]
I am to not add it. As said by @Lineflyer "this is implicit and should not lead to any uncertainty".

However, it's very easy to re-add the "offline" text for every offline cache.
https://github.com/kumy/cgeo/commit/02340399c44b0dfedbee9f0076e8e12a742dcace - Add missing "Offline" text in lists

`History` also miss the offline message, but here, the floppy icon is present.
https://github.com/kumy/cgeo/commit/1b2adbda7aa32d3b234d3c492d7700e58f75ac5a - Add offline text in History list

**Comment by Lineflyer** [comment]
Let`s use kumy@0234039 for `release` branch and postpone the discussion whether to add the disk to all lists later on (maybe after redesign as suggested in #5189).

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Tested and OK with 2015.09.14-RC.

**Comment by Lineflyer** [comment]
Opening new issue for final discussion about disk icon.
