### ISSUE TITLE
Replace "Offline" by disc icon in lists to be consistent throughout c:geo?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5192]
The title says it all.
Refer to discussion in #5190 

Pro:
- Consistency of icons throughout the app (map and lists)

Contra:
- As "lists" are offline per definition (besides history and search results where the disc icon is used) the icon does not provide any information.

Your votes please? :)

**Comment by kumy** [comment]
I'm to not show the floppy in offline lists. As lists are "stored" by definition, icon will always be there, so not more information will be provided.

**Comment by Lineflyer** [comment]
Forgot my vote:
"Offline" instead of disc icon on lists (as currently implemented in version 2015.09.15).

**Comment by Lineflyer** [comment]
No comments or objection here. So we close it with "Wont change" and keep the current implementation.
