### ISSUE TITLE
Icon size in lists different with/without overlay

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5193]
In releas version 2015.09.15 there is a remaining bug in the frontend design:
Icons with overlays are larger as icons without overlays.

**Comment by kumy** [comment]
PR #5194

**Comment by Lineflyer** [comment]
@kumy 
I try to get an overview about recent activities while I was absent.
If I got it right I assume this issue can be closed as also  #5194 is closed?!

**Comment by kumy** [comment]
@Lineflyer if I'm not mistaken, this issue is still present. PR #5194 may be a potential fix even after #5199. What about @rsudev thoughts?

**Comment by Pitel** [comment]
Just noticed it, after upgrading to Nexus 5X. I never noticed it on my Nexus 4 but now I know about it, it's there too, just less noticable. So I guess it's display density related.

![Nexus 4](https://cloud.githubusercontent.com/assets/113248/18352195/b549c870-75dd-11e6-8353-e70e218709f2.png)

![Nexus 5X](https://cloud.githubusercontent.com/assets/113248/18352196/b54a2202-75dd-11e6-88bd-45722100cef9.png)

**Comment by moving-bits** [comment]
Two reasons found so far lead to ragged boundaries:
- icons using up varying space
- marker line to the left (offline logs) shown or not shown

I'm preparing a fix for both. Current state is:
![grafik](https://user-images.githubusercontent.com/3754370/62706227-68516d80-b9ef-11e9-9e08-c870db469546.png)

Next step is to test it with different screen densities.
