### ISSUE TITLE
Bad overlay sizing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5195]
From german geoclub.de as announced by @SammysHP on IRC.
Look at the overlay for "final available" near middle of the screen.

http://show.picr.de/23125480nr.jpg.html

On current nighlties as well as on release.

**Comment by Lineflyer** [comment]
https://geoclub.de/forum/viewtopic.php?f=155&t=67870&start=510#p1231183

**Comment by kumy** [comment]
@rsudev I've rewritten an equivalent script than the one I've made last week. https://gist.github.com/kumy/3289cb775c5de6457a71 . A little over-scaling of `over_br` will enlarge the overlay for "final available".

**Comment by rsudev** [comment]
@kumy Thanks for that.
The initial change leading to the small markers was: fe1cc6cf4a563dbaed6909c7f3946de66c7f9a6d
Additionally was ldpi introduced (which is good) and xxxhdpi dropped (which is not so good) from our inset calculations in aa588774033fb35a9bb5a19af369728513bf6b58
As the bottom icons have less 'visual weight' than the upper ones, which occupy more of the icon area, I deliberately introduced the overscaling there, so probably the best solution is, to directly incorporate the calculation into MapUtils, to be prepared for all possible densities.

**Comment by kumy** [comment]
@rsudev good catch for fe1cc6c I didn't remembered that!
