### ISSUE TITLE
Have confirm selection also in coordinate input on top

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5196]
From support mail:

While in waypoint adding the "OK" has been moved to the top the coordinate input window still ahas an "Ready" button at the bottom which might be blocked by the keyboard.
It would be much more convenient to also have an "Ready" button on the top of the window.

See explanation:
![_20150915_074707](https://cloud.githubusercontent.com/assets/949669/9891774/353ef7a2-5c09-11e5-9833-638e5b4e5edc.JPG)

---

I like this suggestion!

**Comment by SammysHP** [comment]
The difference is that waypoint editing is an activity with an action bar while the coordinate dialog is a dialog that does not have an action bar.

**Comment by Lineflyer** [comment]
Ah, ok. 
But couldn't we place the "Done" box just on the top right and replace "Done" by a tick mark to make it look alike?

**Comment by rahu** [comment]
+1 - don't know how often I cried because of this.

**Comment by rahu** [comment]
what du you think about 9b67fa17cee3a2c3f1539d21470784a98faf8e4e ?

-> looks like this

![screenshot_2015-10-17-13-17-46](https://cloud.githubusercontent.com/assets/937126/10558519/d8e06374-74d1-11e5-8e7c-1b915b271d49.png)

and works great. 
(can someone please tell me the name of the correct drawable...)

**Comment by rsudev** [comment]
In the waypoint edit action bar we use android:icon="@drawable/ic_menu_done_holo_dark" (see edit_waypoint_options.xml in res/menu)

**Comment by rahu** [comment]
thanks.. 

what about adding a cancel button as well?

**Comment by rsudev** [comment]
For consistency it surely is helpful, even though I mostly use the back button anyway in this case.

**Comment by rahu** [comment]
![screenshot_2015-10-17-20-52-09](https://cloud.githubusercontent.com/assets/937126/10560639/216a8f2c-7511-11e5-86b4-ed09ab706104.png)

**Comment by Lineflyer** [comment]
So the Done button could be removed...or shall we keep this redundancy?

**Comment by rsudev** [comment]
Done button should be removed!

**Comment by rahu** [comment]
ok - done button is now hidden. 

BTW: Is it really necessary to check if the NO_TITLE feature is supported? I belief there is no phone outside which isn't supporting this? But I haven't found any further information on this.

**Comment by Lineflyer** [comment]
I can't judge the code, however the screenshot looks good. You should sent a PR to allow review of the changes by other contributors.

**Comment by samueltardieu** [comment]
PR merged
