### ISSUE TITLE
UI improvment when filtering cache list

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#5197]
Hi,

I use filters and it would be convinient to change "filtre icon color" when a filter is applied (let the user know if a filter is on or not).

Best regards,

**Comment by Lineflyer** [comment]
Can you step by step describe the point where you would like to see this (we have more than one filtering possibility within c:geo, therefore I am asking)?

**Comment by Lineflyer** [comment]
Closing due to lack of feedback.

**Comment by ldmpub** [comment]
Hi,

Sorry for the late answer: here is the filter icon I suggest to change color when filter is active.

Best regards,

![screenshot_2016-02-15-13-45-15](https://cloud.githubusercontent.com/assets/1452146/13049064/8cadf3ae-d3ea-11e5-9dd3-e64ad7640809.png)

**Comment by rsudev** [comment]
In this situation you have already the filter bar to signal the filtered state, even detailing the kind of filter. Should that perhaps get better visibility instead? The filter button itself might even not be visible on devices with a low resolution.

**Comment by ldmpub** [comment]
Hi,

Thanks for your reply.

I'm sorry but I don't see as you state any "filter bar to signal the filtered state, even detailing the kind of filter".

I made a video of the current behaviour on my device in landscape mode:
- first: no filter at all (all types of caches)
- then filter are activated => I see no change
- then filter is removed => I still see no change.

Video available there: https://app.box.com/s/lamdw7ivp6c96qrnditilzqm2y46k41p (I'm not able to upload the video directly in this issue even in zip format).

Hope my improvment request is more clear,

**Comment by SammysHP** [comment]
The bar is visible in your screenshot.

**Comment by ldmpub** [comment]
@SammysHP: would you be nice enough to show me within a screen capture what do you call the "filter bar"?

My initial request is to have a status / a way to inform user if a filter is active or not when displaying a cache list.

**Comment by kumy** [comment]
@ldmpub see the red arrow
![8cadf3ae-d3ea-11e5-9dd3-e64ad7640809](https://cloud.githubusercontent.com/assets/176794/13091050/97dbfd60-d4f9-11e5-89c5-86eaadda1e4e.png)

**Comment by ldmpub** [comment]
Tanks, I finally see the filter bar ;-), Sorry for this bad comprehension.

"rsudev" is right: "Should (filter bar) perhaps get better visibility instead?". I sugges for exemple to change its backgound color.
