### ISSUE TITLE
Icons in lists have inconsistent sizes

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5199]
Icons without overlays are smaller than icons with overlays in lists.

cc @rsudev @kumy

**Comment by SammysHP** [comment]
Duplicate of #5193?

**Comment by samueltardieu** [comment]
Indeed.

**Comment by kumy** [comment]
I'm not sure this is really a duplicate.
 #5199 refer to cache icon in list whereas #5193 refer to marker size in map. At least as I understand them...

**Comment by SammysHP** [comment]
@kumy
"Icon size in lists different with/without overlay" of #5193 does not sound like map. ;)

**Comment by kumy** [comment]
@SammysHP you're right! I mix many issues.. So tired !!

**Comment by rsudev** [comment]
@kumy It is a duplicate, and your 'workaround' implementation would be what I would come up with as well now after deeper understanding how the list icons and overlays were integrated. The only change is, that my insets are based on a 34x34 marker size for the list (see my extended version of your gist: https://gist.github.com/rsudev/d5619e493a406365666f)
But in general this should be reworked by creating svg-versions of the other overlay markers and the map markers, by introducing a consistent scaling across all densities and better separation of the map and list compound icons.

**Comment by rsudev** [comment]
(you were faster :) )

**Comment by kumy** [comment]
> and your 'workaround' implementation would be what I would come up with as well now after deeper understanding how the list icons and overlays were integrated.

Glad to hear that ;)
