### ISSUE TITLE
oc.de: Ignored caches displayed in c:geo

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5201]
When ignoring a cache on oc.de and searching e.g. at the coordinates, the cache is shown nevertheless.
While this could be a bug in the OKAPI, we should ensure that we properly authenticate (level 3) in this case, to enable filtering of ignored caches.

**Comment by rsudev** [comment]
A short survey of our code and OKAPI documentation showed, that we have to actively deselect ignored caches (the default returns them).
I propose to filter ignored caches in all 'regional' queries (map, lists), but to return them for queries by owner, finder or geocode.

**Comment by Lineflyer** [comment]
> I propose to filter ignored caches in all 'regional' queries (map, lists), but to return them for queries by owner, finder or geocode.

Sound good to me.

**Comment by Lineflyer** [comment]
Addition to this issue:
It is also not possible to mark a cache as ignored for oc.de with c:geo. I will open a new issue for that

**Comment by Bananeweizen** [comment]
I've implemented it now such that the ignored caches are always not retreived. This is the normal behaviour on both GC and OC. Ignored caches are basically only listed in the ignore list or on direct geocode search. We should not change that.
