### ISSUE TITLE
Clipboard copy of cache description sometimes contains HTML code

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5202]
From FB and also noticed this myself recently with current market release 2015.09.15

When copying the cache description the clipboard content is sometimes plain text (as expected) but sometimes it contains also all HTML codes as well (so its more or less the source code of the description)

**Comment by rsudev** [comment]
Do you have a sample for text only? Or is it varying for the same cache? (All I tried had html in the clipboard...)

**Comment by Lineflyer** [comment]
GC5H5TZ is text only



Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: rsudev <notifications@github.com> 
Datum:23.09.2015  22:05  (GMT-07:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu> 
Betreff: Re: [cgeo] Clipboard copy of cache description sometimes contains
  HTML code (#5202) 

Do you have a sample for text only? Or is it varying for the same cache? (All I tried had html in the clipboard...)

**Comment by rsudev** [comment]
For me even this description contains all the html which is also used in the description on gc.com. It is just less prominent (only some <p> tags). If you don't see those, the question would be what your paste target is.

**Comment by Bananeweizen** [comment]
I'm wondering whether we might need 2 different copy actions, as probably sometimes it is desired to have the text only, sometimes it might be desired to have the HTML. Can we put both to the clipboard or can we decorate the object with a mimetype? At least on Windows, copying rich text to the clipboard would still allow to paste it as plain text. I would assume similar abilitities on Android...

**Comment by Lineflyer** [comment]
@rsudev 
You are right. My example also contained HTML.
It seems we always export HTML here... I am quite sure it was text only somewhen in the past and only recently this behaviour changed. 

I agree to @Bananeweizen that both options can be useful.
I suggest that if something is changed in this context we should also check the possibility to copy only part of the description as mentioned in #3819.
So the final implementation could offer two options:
1. Copy complete description as HTML (as currently implemented)
2. Copy text only but allow text selection

**Comment by samueltardieu** [comment]
I'm not sure we need two options. We could just set the proper mime type on the data we put in the clipboard. If an application can handle HTML, it will get HTML, otherwise I guess it will get plain text data converted from HTML.

**Comment by samueltardieu** [comment]
Or let's implement that for API >= 16 (Android 4.1.x, +80% of our users base).

**Comment by samueltardieu** [comment]
It should have been fixed at the same time as #3819. Please test.

**Comment by Lineflyer** [comment]
Tested and working with 2016.02.22-NB using GC5H5TZ by coping the whole description. I could not see any html tags in the pasted text.
