### ISSUE TITLE
Multicaches are not displayed on map

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5203]
From support mail (related to cgeo 2015.09.23):

> I received the latest update to c:geo last night and immediately noticed one problem: when I use the "Live Map" to view caches, even though I have all cache types selected, multi caches that I haven't found are not displayed . There are several night cache (which display as multis) that I have not saved for off-line use. None of these caches are displayed.
 
> I normally do not save night caches for off-line unless I intend to attempt them in the near future.
 
> Let me know if others have had this problem. I am using an Android phone (Samsung Galaxy S5).

I cannot reproduce this (launch cgeo without any filter, live map, I can see multicaches, including in areas where I have no caches stored). Can other developers check if they can reproduce this problem?

**Comment by kumy** [comment]
No problem here.

**Comment by samueltardieu** [comment]
Followup from support mail:

> I misstated what I thought was the problem. It is actually a bit more exotic than I realized. On the home screen, if i open the "Live Map," the program loads caches, but then quits before it has loaded all within an area. If I open one of the caches and the bring up the map on that cache page followed by "Enable Live" it will now display many more caches than were shown on the original Live Map. I indicated multi in my original letter because those are the most noticeable when absent. It may also be a function of distance from my house. I am not sure about that.

**Comment by samueltardieu** [comment]
Closing as this does not look like a bug.

**Comment by rsudev** [comment]
Probably a temporary glitch in the communication with groundspeak but perhaps also an issue in our threading/async commnication. We really should put in a log readout, so we can get back information in such cases.
