### ISSUE TITLE
Crash when check gcvote with empty string 

### ISSUE THREAD

**Issue by akkatracker** [cgeo/cgeo#5205]
Possibly only if service is active and you press check.

**Comment by rsudev** [comment]
Doing a short cross-check I was not able to reproduce this directly.
Did you enter valid credentials in your case?
Could you please post your system info (about c:geo - system tab)?

**Comment by samueltardieu** [comment]
I could reproduce this. The credentials need to be empty.

**Comment by samueltardieu** [comment]
Let this stay on `master` for a few weeks, then if there are no problems we can merge it to `release`. The change touches all kind of username/password credentials, so it needs to be field tested over some time.

Assigning to @Lineflyer for testing.

**Comment by akkatracker** [comment]
I presume you don't need system details anymore?

**Comment by rsudev** [comment]
Right :)

**Comment by Lineflyer** [comment]
@samueltardieu 
Any special test case you would think of for this change.
If I read the code I should probably verify that entering and verifying credentials is possible for all connectors as well as checking the reaction on empty fields.

**Comment by Lineflyer** [comment]
User management seems to work flawless with this change.
I also tried several things like empty usernames and passwords and the reaction was always appropriate.
Due to the wide scope of this change I would still leave it on `master` only for the next feature release.
