### ISSUE TITLE
Wrong requests to geokrety?

### ISSUE THREAD

**Issue by filipsPL** [cgeo/cgeo#5209]
We are observing large number of requests from various sources:
`"GET /export2.php?inventory=1&secid HTTP/1.1"`
(the secid value is not set)
I suspect c:geo - could you verify this hypothesis?

**Comment by kumy** [comment]
@filipsPL I'll check. I presume those requests comes from `LogCacheActivity`. Thanks for the report.

**Comment by kumy** [comment]
@filipsPL How urgent is the fix needed? Could we wait for the next c:geo release? New version was just released this week...

**Comment by filipsPL** [comment]
Not very urgent as I applied some pre-filter. So take your time, we can wait until the next release.
