### ISSUE TITLE
New bugfix release?

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5210]
We currently have fixes for #5204, #5200, #5208 and #5209 on release branch.
Does this warrant a new bugfix version (also depending on feedback from @filipsPL)?

**Comment by akkatracker** [comment]
What would be the con of having a bugfix release now? (aside from the fact that there are a few other patches getting tested iirc)

**Comment by samueltardieu** [comment]
@akkatracker We have noticed that frequent bugfix releases have upset some users in the past, so we try to space them a bit when possible if they are not urgent.

**Comment by samueltardieu** [comment]
@rsudev I would be in favor of releasing a bugfix release, at least to reduce the bad requests on GK servers and to let users post GK logs.

**Comment by akkatracker** [comment]
Far out, some people are hard to please. 

I cannot see how someone would get angry if a bug fix was well tested and helped improve the *free* application that is provided to them. 

Each to their own I guess.

**Comment by rsudev** [comment]
@samueltardieu Agreed, even though @filipsPL didn't comment yet. @Lineflyer is still on the move I guess, so the question is who could do some smoke testing on a release version.
I could do some tests tomorrow morning the earliest to at least cross check core areas and the fixed functionality.

**Comment by filipsPL** [comment]
From my point of view (geokrety.org) we had/have two issues:
1) enormous amount of bad requests causing big load on databases - FIXED on our side
2) bad requests cause users can't post GK logs - to be fixed at c:geo app.
So I think the sooner new release will be published, the better.

**Comment by kumy** [comment]
> at least to reduce the bad requests on GK

:+1:  to release soon

> let users post GK logs.

Fix was on GK side. Posting is now working

**Comment by filipsPL** [comment]
> Fix was on GK side. Posting is now working

true! :-)

**Comment by samueltardieu** [comment]
Please give a try to 2015.09.28 (see http://www.cgeo.org/status.html for a link).

**Comment by samueltardieu** [comment]
(deployment set to 20%, please rollback if there is a problem with the recent fixes)

**Comment by samueltardieu** [comment]
Done
