### ISSUE TITLE
Crash on BlackBerry 10

### ISSUE THREAD

**Issue by pavelschon** [cgeo/cgeo#5215]
Application starts, map loads, shows nearest caches and positioning works.
After a minute the application crashes.

Model: Classic
OS: 10.3.2.2474
Location: on
Google Play Services: n/a

I was in touch with Carnero and he suggested it might be problem with missing Google Play Services.
If that's the case, it would be nice if the app could work in some fallback/compatibility mode.

**Comment by rsudev** [comment]
I cross-checked in an Android Emulator without Google Play Services - no issue there. Are you running the latest version? Are you able to provide more information about the issue (logs, crash reports, anything)? Unfortunately is nobody in the team with Blackberry background, so I cannot direct you how and where to find such info.

**Comment by pavelschon** [comment]
I picked up c:geo from Google Play (a version available last week).
I will try the latest now and provide report here.

**Comment by samueltardieu** [comment]
Also, please provide us with the full information from "About c:geo" / "System". In cgeo "Settings" / "System", you can activate the debug mode. After the crash, you will the need to send us the logs from your device (you can use `adb logcat` to retrieve them) so that we can pinpoint the location of the crash.

**Comment by pavelschon** [comment]
Currently running the latest version with enabled debug log and the application is not crashing now. I will stay focused on this and let you know if something happens. Thanks!

**Comment by pavelschon** [comment]
The application keeps crashing as before. To extract logs from BB 10 is a bit tricky, but I will have more time over weekend to do that. Please be patient, thanks.

**Comment by pavelschon** [comment]
--- System information ---
Device: Classic (BlackBerry, BlackBerry)
Android version: 4.3
Android build: 10.3.2.231
Cgeo version: 2015.09.28
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / Basic
Installed cgeo plugins:  none
--- End of system information ---

Log will extract later.

**Comment by pavelschon** [comment]
Backtrace here!

E/cgeo    (82538738): [main] UncaughtException
E/cgeo    (82538738): java.lang.IndexOutOfBoundsException: Invalid index 74, size is 65
E/cgeo    (82538738):   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/cgeo    (82538738):   at java.util.ArrayList.get(ArrayList.java:308)
E/cgeo    (82538738):   at com.google.android.maps.ItemizedOverlay.getItem(ItemizedOverlay.java:207)
E/cgeo    (82538738):   at com.google.android.maps.ItemizedOverlay.drawSafe(ItemizedOverlay.java:132)
E/cgeo    (82538738):   at com.blackberry.osmdroid.views.overlay.SafeDrawOverlay.draw(SafeDrawOverlay.java:85)
E/cgeo    (82538738):   at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.superDraw(GoogleCacheOverlay.java:101)
E/cgeo    (82538738):   at cgeo.geocaching.maps.AbstractItemizedOverlay.draw(AbstractItemizedOverlay.java:44)
E/cgeo    (82538738):   at cgeo.geocaching.maps.CachesOverlay.draw(CachesOverlay.java:104)
E/cgeo    (82538738):   at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.draw(GoogleCacheOverlay.java:70)
E/cgeo    (82538738):   at com.blackberry.osmdroid.views.overlay.OverlayManager.onDraw(OverlayManager.java:160)
E/cgeo    (82538738):   at com.google.android.maps.MapView.dispatchDraw(MapView.java:1197)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12854)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12901)
E/cgeo    (82538738):   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12796)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12901)
E/cgeo    (82538738):   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12796)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12901)
E/cgeo    (82538738):   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12796)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12901)
E/cgeo    (82538738):   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12796)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12901)
E/cgeo    (82538738):   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3060)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12796)
E/cgeo    (82538738):   at android.view.View.getDisplayList(View.java:12901)
E/cgeo    (82538738):   at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411)
E/cgeo    (82538738):   at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359)
E/cgeo    (82538738):   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2369)
E/cgeo    (82538738):   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2241)
E/cgeo    (82538738):   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1874)
E/cgeo    (82538738):   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1006)
E/cgeo    (82538738):   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5550)
E/cgeo    (82538738):   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/cgeo    (82538738):   at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/cgeo    (82538738):   at android.view.Choreographer.doFrame(Choreographer.java:532)
E/cgeo    (82538738):   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
E/cgeo    (82538738):   at android.os.Handler.handleCallback(Handler.java:730)
E/cgeo    (82538738):   at android.os.Handler.dispatchMessage(Handler.java:92)
E/cgeo    (82538738):   at android.os.Looper.loop(Looper.java:137)
E/cgeo    (82538738):   at android.app.ActivityThread.main(ActivityThread.java:5121)
E/cgeo    (82538738):   at java.lang.reflect.Method.invokeNative(Native Method)
E/cgeo    (82538738):   at java.lang.reflect.Method.invoke(Method.java:525)
E/cgeo    (82538738):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
E/cgeo    (82538738):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/cgeo    (82538738):   at dalvik.system.NativeStart.main(Native Method)

**Comment by SammysHP** [comment]
That sounds like an issue with the Google API that is used by your phone. (I wonder that BB actually provides that API.) I think that we cannot fix it inside of c:geo.

You can use OpenStreetMap instead of Google maps.

**Comment by rsudev** [comment]
Not to sure about that we once had #309, but this should be fixed long ago. Additionally #3209 comes to mind, even though it does not lead to a crash there.
It might be a timing issue that can occur on your device, as (AFAIK) the Android part is not 'native' to the device,
Is this reproducible for you? Can you describe in more detail, how this happens?

**Comment by pavelschon** [comment]
This is easily reproducible on my device. I just start application, select "Live map", then little playing with map: move around, zoom in, zoom out, etc. After a minute the application crashes. I will try to reproduce also on BB emulator on my PC.

I confirm that Open Street Map works perfectly,, so I will stick with this workaround. Thanks for your help!

**Comment by Lineflyer** [comment]
As this is dealing with Blackberry devices there is possibly not much we can do. Furthermore the user found a workaround and we do not have any more reports like this I am closing this issue.
@pavelschon Feel free to reopen in case you have more clues which help us solving the problem.
