### ISSUE TITLE
F-Droid repo is unavailable

### ISSUE THREAD

**Issue by Ceremony64** [cgeo/cgeo#5219]
https://fdroid.cgeo.org response with `403 Forbidden`. F-Droid reports `Error getting index file`.
Has it been shutdown, moved or is there maintenance being done?

**Comment by samueltardieu** [comment]
Cc @mucek4 @kumy

**Comment by kumy** [comment]
Repo is up. and up to date. Don't use your browser, but the fdroid app.

**Comment by Ceremony64** [comment]
Its not just when visiting via browser, but also when trying to fetch within F-Droid:
`Error getting index file https://fdroid.cgeo.org`

**Comment by kumy** [comment]
Strange. It works for me...
I m not at home, I cannot check the logs.

**Comment by Ceremony64** [comment]
Strange... all other Repos (e.g. Antox and I2P repos) I have work flawlessly. Just cgeo repo runs into an error...

**Comment by kumy** [comment]
I ll look deeper tomorow night

**Comment by mucek4** [comment]
I only keep cname record in dns. Will take a look when I get to pc

**Comment by kumy** [comment]
@Ceremony64 I can't see where the problem is.
Could you share your IP? contact at geokretymap dot org
Could you also test without SSL? http://fdroid.cgeo.org
Thanks

**Comment by Ceremony64** [comment]
HTTP works! No errors whatsoever. HTTPS still results in the issue above. I also just sent you a mail with my current IPv4

**Comment by mucek4** [comment]
Could it be issue with cert or some firewall mtu? Can you try on any other network?

**Comment by kumy** [comment]
As said in my reply, I didn't found your Ip in the logs, And since 22h00 I just got 2 requests on IPV6.
May you share your device info, Model/Android version. Which fdroid app version do you use? (mine is fdroid 0.92 ; Android 5.1.1)

**Comment by kumy** [comment]
Hum, maybe an SNI problem...

**Comment by Ceremony64** [comment]
I am running a Custom Rom (Euphoria-OS) which is based on Android 5.1.1 as well. F-Droid is 0.97-alpha4

**Comment by kumy** [comment]
With F-Droid 0.97 I get the same error as yours

**Comment by Ceremony64** [comment]
Issue seems to be occuring starting with 0.97-alpha2. Fetching apks from the server still works, but updating the server index does not.

**Comment by kumy** [comment]
There is an open issue: [SNI missing after upgrade to 0.97-alpha2 ](https://gitlab.com/fdroid/fdroidclient/issues/431)

**Comment by kumy** [comment]
I think we may close this issue, as the problem seems on the fdroid side.

**Comment by Ceremony64** [comment]
Yep. Guess I'll stick to the stable 0.96.x release for now. Thanks for helping me out!
