### ISSUE TITLE
Spoiler images of owned caches are missing the description

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5221]
From support mail (but not yet verified):

With Version 2015.09.28 you fixed "Spoiler image descripritions". This is working now for each Cache of other Cachers. But descriptions of *OWNED* caches are still missing. I think the reason is that the HTML-code of owned caches is slightly different

the following code is additional for owned caches:

```
<span class="minorDetails"> | <a href="/seek/image.aspx?imgid=......" 
title="Edit">Edit</a></span>
```
Maybe you can make image descriptions of owned Caches working too, thanks :-)

**Comment by Lineflyer** [comment]
Confirmed for my owned cache GC352Y3.
I added a description to the spoiler to test it and can't see it.
If I access the cache as another user with c:geo the description is shown.

**Comment by Bananeweizen** [comment]
Can you send the HTML page of your own cache to my account or the list? I don't want to fiddle with the regular expressions without having a test case.

**Comment by Lineflyer** [comment]
Sure, will do next minuted.

**Comment by Bananeweizen** [comment]
please test that with a nightly, since I had quite some trouble to get my unit tests running

**Comment by Lineflyer** [comment]
Tested and OK with 2016.04.24-NB1

Tested using my owned cache, same as initially.
