### ISSUE TITLE
Remove attribute filter options in lists of unsaved caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5222]
Scenario:
- Have no caches stored
- Search "nearby caches"

Opening the filter function from the menu in the search results offers also filtering methods which are only applicable to stored caches (i.e. filter by attributes). These won't work as expected as long as the cache is not completely loaded/saved and thus should not be offered to the user at this point.

**Comment by stevebeavey** [comment]
Is it possible that this filtering of unsaved caches (by attributes for instance) will be possible in some of the newer versions of c:geo? it would be great tool

**Comment by Lineflyer** [comment]
@stevebeavey As said on IRC (I guess that was you) this is not possible as long as the caches are not fully loaded (and they are not on search results) this is technically impossible.
Reason is, that the details loaded on live map or nearby search do not yet contain the attribute information.

**Comment by stevebeavey** [comment]
yes,that was me,tnx for answering so quickly:)

**Comment by eddiemuc** [comment]
With new filtering framework I try to go a different way by introducing the option to include (or not include) inconclusive results. In other words, if a filter cannot check for a cache whether it is true or false (e.g. attribute filter on non-stored cache) this setting decides if such caches shall be included in result list or not.

This aims to have one and only one filtering solution for all cases and not activate/deactivate certain filters for specific cases.

I must note tough that this is not (correctly) implemented yet.

**Comment by eddiemuc** [comment]
Attribute filter now correctly implements "inconclusive", so let's close here
