### ISSUE TITLE
Icon overlay for "final defined" not shown in lists

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5223]
2015.10-04-NB (and also 2015.09.28):
- Store a multi or mystery cache to a list
- Open cache and go to waypoint tab
- Add a waypoint of type "Final" with valid coordinates
- Save the waypoint
- Return to the list

Expectation:
Cache icon should be shown with overlay icon on lower right for "defined final" instead of no overlay.

The overlay does only seem to work if the function "replace listing coords by final waypoint" has been used while creating the waypoint. This should not be necessary for the overlay to appear in the list.

I assume the bug was introduced with recent changes to the overlay design in lists as it used to work with older c:geo versions.

**Comment by Lineflyer** [comment]
Is someone able and available to tackle this? We keep getting questions regarding the missing marker.

**Comment by kumy** [comment]
Faulty commit was f449df9

**Comment by kumy** [comment]
@Lineflyer assigned for testing.

**Comment by Lineflyer** [comment]
Confirmed working with 2015.10.19-NB-17c1217

@kumy:
Can you apply this change to `release`?
