### ISSUE TITLE
Broken string in progress bar for moving caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5224]
![cgeo2015-10-05 14 42 05](https://cloud.githubusercontent.com/assets/949669/10284689/96fc54ae-6b85-11e5-9330-43ffcc9012db.png)

2015.09.28

**Comment by rahu** [comment]
what is the expected behavior? 
"Moving cache to list <listname>"  or just "Moving cache to list"

**Comment by olpp** [comment]
I would expect "Moving cache[s] to list <targetlistname>"

**Comment by samueltardieu** [comment]
@Lineflyer, please test and advise on inclusion into `release`.

**Comment by Lineflyer** [comment]
I just tested it with 2015.11.29-NB1 and it looks fine to me.
Good to include on `release`
