### ISSUE TITLE
Found status not refreshed in list after one-click offline log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5225]
2015.09.28:
- Activate one-click offline log in Settings - Logging
- Open a list of saved caches
- Long click a cache and select "One click offline log" - Found it

Result:
When returning to the list the cache is not marked as offline logged (orange bar, orange smiley)
Only after scrolling the list or close/open the list the new status is shown

Expectation:
The status change should be visible when returning to the list without further action required.

Note:
In case "One click offline log" is not active, it works as desired.

**Comment by kumy** [comment]
linking to #5149

**Comment by Lineflyer** [comment]
Tested and working with 2015.11.29-NB
