### ISSUE TITLE
Auto suggest to delete empty list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5226]
Some time ago the menu item "Delete caches&list" has been removed (AFAIR to reduce the amount of menu items).

The drawback is, that if a user now wants to delete a list of caches including the list itself (common use case) he has to perform to separate actions which is not user friendly:
1. Menu - Delete all caches
2. Menu - Delete list

I suggest to show a prompt asking for deletion of the active list if after a delete or move action it is detected that the list is empty. This would be a convenient solution without need for another menu item.

**Comment by tobiasge** [comment]
Hello,

I have a proposal for the implementation of this feature. Please leave you comments here:
https://github.com/tobiasge/cgeo/commit/1117f9c72783443b91d8e67779421dec0d7251cf

**Comment by Lineflyer** [comment]
You could also send us a PR. That might be easier to see for everyone and if it is fine it could directly be merged.




Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: Tobias Genannt <notifications@github.com> 
Datum:20.11.2015  22:11  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu> 
Betreff: Re: [cgeo] Auto suggest to delete empty list (#5226) 

Hello,

I have a proposal for the implementation of this feature. Please leave you comments here:
tobiasge@1117f9c
