### ISSUE TITLE
Add "Move" menu item in map popup menu of saved caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5227]
From support mail:

It happens that I would like to resort caches to different lists while looking at them on the (live) map.
Currently I have to change to the cache details (open the popup, select More details, etc.) to change the list where a cache is saved on.

It would be a better user experience if the three-dot menu of the popup would contain the possibility to move a cache to a different list.

**Comment by pstorch** [comment]
I think this is obsolete now. With the Edit Lists button on the map popup.

**Comment by Lineflyer** [comment]
> I think this is obsolete now. With the Edit Lists button on the map popup.

Agree
