### ISSUE TITLE
Include image description in c:geo gallery of a cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5228]
From support mail:

I'm missing the image DESCRIPTION of log photos. Sometimes they contain important or interesting additional explanation of a log photo.

For example:

Cache: http://coord.info/GC1Z9J1
Log: http://coord.info/GLFD2GY6
Logimage-Name: 20140831_123209
The missing description of this image is: "Holzschuhe"

Even if the image description isn't displayed on the Caches' Website (just if you click on the image), it's already there within the HTML-code of the Caches' Website:
```
"Images":[{"ImageID":24259208,"ImageGuid":"5be12ac4-7c29-4543-9176-4e88bbc7b558","Name":"20140831_123209","Descr":"Holzschuhe","FileName":"5be12ac4-7c29-4543-9176-4e88bbc7b558.jpg","Created":"2014-08-31","LogID":441107781,"CacheID":1415339,"ImageUrl":null}]}
```

**Comment by Lineflyer** [comment]
As seen in #5200 we seem to display the subtitle already for spoiler pictures but not for log pictures...why is that?
@rahu Maybe this is interesting then for you instead of #4379 to work on?

**Comment by rahu** [comment]
jep - i'll have a look at this....

**Comment by kumy** [comment]
@Lineflyer assigned for testing.

BTW discovered #5245 while testing this PR.

**Comment by Lineflyer** [comment]
Confirmed working with the initially mentioned cache/log.
2015.10.19-NB-17c1217
