### ISSUE TITLE
Indicate the last time a cache was found / type of recent logs

### ISSUE THREAD

**Issue by mjarmstr** [cgeo/cgeo#5230]
My normal mode of operation for using c:geo is as follows:
- Use the map to find my area of interest.
- Scale the map to select an appropriate number of caches and store offline.  
- Peruse the list for caches to target.
  - Open the cache details
  - Go to the logs and look at the recent ones to see when it was last found

This is because where I live it isn't uncommon for a cache to go unfound for months and often the last years worth of logs are DNFs and/or needs maintenance.  I usually will just skip these.  It would be nice to have some sort of indication on the list page and/or the first details page of the last time cache was found and/or what the type of the last few logs are.  

My initial spit-ball of an implementation would be to have a colored/dashed line duplicating the colors from the last few log entries on the list page, one log per dash.  Then that could be duplicated along with a last found date on the details page.

**Comment by kumy** [comment]
This remind me #1801

**Comment by mjarmstr** [comment]
@kumy, agreed.  I didn't find that one when I looked through the requests.  Seems like similar ideas on implementation as well.

**Comment by kumy** [comment]
So let's close this one :)
