### ISSUE TITLE
User name for GCVote can not be deleted

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5231]
2015.10.08-NB:
- Open Settings/Services
- Open GCVote settings
- Click on username and replace the existing user by an empty field
- Select OK
- Select "Verify login"

This will return "Check OK" and I do see in the log that the previously stored username is still in use
- Close c:geo / Force close
- Start c:geo again
- Go to Settings/Services/GCVote

You will see, that the previous username has been restored.

As the username of GCVote and geocaching.com need to be identical we most probably derive it from the settings for geocaching.com.
However couldn't we just disallow editing of the username in the GCVote settings and just show it for informational purposes.

**Comment by GodfatherThe** [comment]
>However couldn't we just disallow editing of the username in the GCVote settings and just show it for informational purposes.

I've just tried to set android:enabled="false" attribute for EditTextPreference for GCVote username and it seems to be exactly what you mentioned. Is it ok?
![screenshot_2015-12-01-00-24-47](https://cloud.githubusercontent.com/assets/918446/11484954/249f70b2-97c2-11e5-9a00-e4eabc77179f.png)

**Comment by kumy** [comment]
@Lineflyer assigned for testing.

Revoke is initialize by a long press on "Authorize Again" preference.

**Comment by Lineflyer** [comment]
Confirmed no longer appearing due to the new UI solution.
Tested with 2016.04.03-NB
