### ISSUE TITLE
Log image upside down

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5234]
See log image of GC502P1 from today, by user Lou_mary. When watched in the app, then it is upside down. Opening the image in the gallery by just clicking the image in cgeo, it shows correctly. So why does the gallery rotate the image and why don't we?

**Comment by SammysHP** [comment]
I guess that the gallery reads the EXIF orientation tag and c:geo does not.

**Comment by Lineflyer** [comment]
I had one such case in the past, whereas now I do see that c:geo and external apps are inline.
This might be caused by the fact, that AFAIK geocaching.com now strips the complete EXIF information from log pictures (to prevent spoilering by EXIF coords).
