### ISSUE TITLE
Day and Month switched

### ISSUE THREAD

**Issue by Bugsy1905** [cgeo/cgeo#5235]
I have recently upgraded my phone to an Xperia Z3 Compact (D5803) running Android 5.1.1 and the dates on the log pages are reversed, i have checked my settings on Geocaching.com and can confirm i have selected dd/MMM/yy. Is this a bug in the system.

**Comment by SammysHP** [comment]
Possibly, yes. I had the problem of wrong date formatting after an upgrade of ROM. It was caused by a wrong system configuration.

But first please clarify the issue:

1. The date is wrongly recognized by c:geo, e.g. 05/03/2015 as 3rd May instead of 5th March.
2. The date is wrongly displayed, e.g. 03/05/2015 instead of 05/03/2015.

**Comment by Bugsy1905** [comment]
I think the date is wrongly recognised, once the screen is refreshed all
the dates on the logs change. They would normally show 08/10/2015 (8th
October) but it has switched to American format 10/08/2015 (October 8th).

The setting on Geocaching.com is set correctly, its onky ever since i have
changed my phone from an Xperia Z to an Xperia Z3 Compact.

I hope this helps.

**Comment by SammysHP** [comment]
Please write a log and store it offline. It should be visible in the log section of the cache details. Is the date shown correctly?

**Comment by Bugsy1905** [comment]
When i select a date, it appears correctly from wheel menus (day month
year), but after selected it shows the date back to front (month day
year)......

**Comment by rsudev** [comment]
I tried some things (including setting my date format to the value you mentioned) but I couldn't observe any inconsistencies.
Can you try to change and set back again the date format of your device?
Can you post a screenshot the demonstrates the faulty display?

**Comment by Bugsy1905** [comment]
Its a new device for me but there doesn't appear to be a way of changing
the date format on the device.
I have attached screenshots of the issue together with my system
information.

--- System information ---
Device: D5803 (D5803, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.200
Cgeo version: 2015.09.28
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Orientation sensor: present
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB (cgeo forced to English)
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins: calendar
--- End of system information ---

**Comment by rsudev** [comment]
Unfortunately does it not work to post images through a reply mail. You need to attach them on the website.
Another check I'd like you to make would be to switch of the 'force to english' setting (and restart c:geo) and see whether this changes anything.

**Comment by SammysHP** [comment]
This is a system-wide problem on your device. It was introduced with Android 5.1 (at least in Cyanogenmod) when the date format preferences were removed (yes, you cannot change the format anymore, @rsudev).

To fix this issue, install this app and delete the "date format" preference.
https://play.google.com/store/apps/details?id=de.SmartDyne.Free.DisplaySystemSettings

**Comment by SammysHP** [comment]
In case the fix does not work, please check as many other apps as possible. I saw the bug on my device in many locations. If it is c:geo only, we can reopen the issue. But I checked the code of c:geo when I saw it happen on my device and I was sure that its code is ok.

**Comment by Bugsy1905** [comment]
Thanks for that. I have switched off 'forced to English' and restarted and
this seems to have fixed the issue.
Thanks for all your help

**Comment by Lineflyer** [comment]
@SammysHP 
Do you have any link describing this bug which I could add to a new FAQ entry?

**Comment by SammysHP** [comment]
@Lineflyer 
In this case it was "forced to English" in c:geo preferences, not the bug. IMHO it's not worth to add a FAQ entry for this specific bug as it happened only under some circumstances after a CM update.
