### ISSUE TITLE
Can see GCVote for OB caches?!

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5236]
2015.10.11-NB:
- Have oc.nl connector active
- Have gcvote active
- Search for caches by address "Stadtkyll"
- The result should include OB148D (and others from same owner)
- Open cache details of OB148D

Result:
Rating is shown in cache details (i.e. 3 of 5 stars with 3 votes).
This can not be true, as:
1. I cannote see any request to gcvote for that 
2. GCVote is not supporting OB* caches

I am a little puzzled here..can someone confirm?

**Comment by rsudev** [comment]
I can verify the behaviour you observe

**Comment by rsudev** [comment]
The explanation is easy: oc.nl supports cache rating on its own and we download and display it - so no GCVote, but rating nevertheless...

**Comment by Lineflyer** [comment]
Still I learn something new :)
I checked some random OB cache by searching with its code...that did not return a rating. Obviously it had no rating yet. But for others I do also see the rating.
Do you have any documentation about that? What is the scale for these ratings?

**Comment by Lineflyer** [comment]
@rsudev: Friendly reminder (see above)

**Comment by rsudev** [comment]
I cite the OKAPI documentation here:
```
rating - float (between 1 and 5), an overall rating of the cache, or null when the geocache does not have a sufficient amount of votes to have a rating.

Please note: some OC installations do not use the rating/voting system. The rating will always be null on such installations.
```
This should clarify the matter, right?
Supporting sites are (AFAICS, not directly tested) oc.nl, oc.pl, oc.us, oc.ro (though they seem to have problems right now) and oc.org.uk

**Comment by Lineflyer** [comment]
Thanks!
