### ISSUE TITLE
Display cache info (found, saved, offline etc) in MapsMe map

### ISSUE THREAD

**Issue by kw217** [cgeo/cgeo#5239]
Stored > Show on map > Maps.me shows a pink circle for each cache. It should show more information. Compare with Stored > Show on map > Map, which shows an icon for each cache. The icon shows whether the cache is found, stored offline, has offline log, cache type, etc.

I have raised https://github.com/mapsme/omim/issues/238 against Maps.me to allow specifying the point style when using the mapswithme API. If that is implemented, then all that is required is to enhance MapsMeCacheListApp to pass the additional optional parameter to the MWMPoint constructor.

We would need to decide which styles to use for the points; the [options](https://github.com/mapsme/omim/blob/a1a299eb341603337bf4a22b92518d9575498c97/map/bookmark.cpp#L215) are the eight standard KML styles, i.e., "placemark-red", "placemark-blue", "placemark-purple", "placemark-yellow", "placemark-pink", "placemark-brown", "placemark-green", "placemark-orange", plus the existing default (a small violet circle). Currently all caches show up as violet circles.

I propose the following:
- Default: red flag
- Found: small violet circle (the symbol used for all points currently)
- Disabled: brown flag
- Offline log: yellow flag

but all suggestions welcome!

**Comment by kw217** [comment]
MAPS.ME now has this support - see https://github.com/mapsme/omim/issues/335 . I am in the process of adding it to the MAPS.ME Android API - see https://github.com/mapswithme/api-android/pull/16 .

Please can someone review my proposal above?

**Comment by rsudev** [comment]
To me this looks good (even though I never used maps.me myself yet).
Regarding the maps.me Api: As the possible styles seem to be fixed in code, wouldn't it make sense to expose them as an enumeration in the Api?

**Comment by moving-bits** [comment]
Maps.me do no longer support their own API, connection is broken for all versions > 12. Also it's no longer open source, thus let's close this issue.
