### ISSUE TITLE
Hint picture is not refreshed when switching to different cache

### ISSUE THREAD

**Issue by arminus** [cgeo/cgeo#5240]
Not sure if this is the same as #4570 but I have a clear repro with the 2015.09.28 (Lollipop on Galaxy S5 neo):

2 saved caches (repro with GC26F8R and GC57JEX), open the GC26F8R, tap the hint picture -> rendered picture is ok
go toGC57JEX, open the hint picture there -> rendered picture is still from GC26F8R

**Comment by Lineflyer** [comment]
Confirmed.

**Comment by Lineflyer** [comment]
I was able to see that more than once in the recent nightlies. I guess some inconsistency similar to #4570 was reintroduced recently with one of the fixes for  spoiler image title loading.

**Comment by rsudev** [comment]
I tried to reproduce this with the information given above, but failed. @Lineflyer: As you were able to reproduce it, could give a more detailed (step-by-step) description with clear preconditions?
I searched both caches by GC code, looked at the images (to check them), Saved them to a list and then opened them one after the other from that list. In this case, the hint pictures shown were correct for both caches.

**Comment by arminus** [comment]
Here's a repro video: https://drive.google.com/file/d/0B8VgeF6unGgiN2s1UEoxXzAybHc

I think the cause is at 0:08 - tapping the < button drops me out of the app (another bug?), after that, the effect happens. If I use the devices back button at that point all is fine.

The scenario could be reproduced differently, too, though. e.g. I might leave the app by other means and come back and load another cache, in which case the same happens I think...

**Comment by rsudev** [comment]
Thanks for the video, that really makes it clear. There seems to be an issue in how we handle the activity stack here. If I for example press the 'Home' button when on the hint images page, I get shown the main cache details when coming back to the app.

**Comment by Lineflyer** [comment]
That video might somehow by equal to my case, where I could confirm that.
AFAIR I put the phone to sleep and then tried over with another cache with the same result.

**Comment by Lineflyer** [comment]
Thinking of "Activity stack". Some months ago I have seen a different behaviour, which might have something to do with this?! See #5128

**Comment by samueltardieu** [comment]
Do not hesitate to reopen if the problem persists.

**Comment by Lineflyer** [comment]
Confirmed working with 2016.02.22-NB.
