### ISSUE TITLE
send2cgeo button not showing up  with https URLS

### ISSUE THREAD

**Issue by schertha** [cgeo/cgeo#5242]
If I use
https://www.geocaching.com/geocache
instead of
http://www.geocaching.com/geocache
The Userscript is not triggered and I don't see the send2cgeo Button in Cache-Details.

Easy Fix: Add 
// @include        https://www.geocaching.com/geocache/*
in line 10 :)

**Comment by Lineflyer** [comment]
Moving issue to send2cgeo
