### ISSUE TITLE
Toggle "Stored in Device" between "X Days" and "the actual Date"

### ISSUE THREAD

**Issue by djtooley** [cgeo/cgeo#5243]
I suggest a "Toggle" (by pressing on the the text itself), between the approximate date and the actual date of "stored in device".  This way the current functionality is also preserved.

Detail:

I use my "Stored in Device" date as a way of knowing when I actually "found" the cache.  (which I then log from the geocaching.com website)   I do this together with putting the cache into a "Found" List.

So displaying the date, instead of the approximation, would be invaluable for me, so I don't have to figure out which day I was at the cache location.

**Comment by SammysHP** [comment]
Instead of adding a new (mostly unused or unknown) feature, why not simply use offline logs? That way the cache is marked as found (or DNF or whatever), added to the local history and you can also export Field Notes.

**Comment by djtooley** [comment]
Looking....
That COMPLETELY solves my request!

Thanks for pointing that out, SammysHP!
