### ISSUE TITLE
Have file name in GPX import window

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5246]
From support mail:

I use to import large GPX files (and sometimes several of them).
Sadly while the import is running it does not show which file I am currently importing. This would be helpful in order not to accidently the same file again after a long importing time.

So the name could be shown in the import window header or at least the "import done" window should state the file name which has just been imported.

**Comment by olpp** [comment]
Thanx. Just updated. Looks fine :-)
