### ISSUE TITLE
Have OK/Cancel also on top for personal note editing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5253]
From FB after users tried our nightly which included the fix for #5196 

Also the personal note input window should have the Done/Cancel selection on top sue to ease of use and design consistency.

@rahu In case you are interested and it is technically possible...

**Comment by rahu** [comment]
I'll look at this. 

Within this context my wife pointed me to 2 other details:
- after writing a field note listing scrolls back to top
- you have to scroll down to write a field not
Usually she want's to write the field note after you have found the solution for a task which is not at the end of the listing. -> you have to scroll down, write the note, an then have to scroll to the last position in the listing again.  I think it's worth to look into it and maybe avoid these scroll actions. (write Fieldnote from context menu and remember position)

**Comment by rahu** [comment]
![screenshot_2015-10-23-22-00-42](https://cloud.githubusercontent.com/assets/937126/10703641/9e6cdc36-79d1-11e5-8224-1494d1219052.png)

just a preview - still need to do some code cosmetics...
