### ISSUE TITLE
All suport mail end up in spam on gmail.com

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5254]
We got replies from several users (all gmail) that our replies to them are always sent to their spam folders on gmail.
I suspect it has something to do with the identification of the host (like the one we had with IPV6).

@mucek4 Can we do something about that?

**Comment by mucek4** [comment]
Is it still happening? Like in past couple of days? I get email delivered to me without a problem. But I'll take a look during weekend.

**Comment by Lineflyer** [comment]
@mucek4 
No idea. Maybe you can send a test mail from support to your personal gmail to check.
The reports I got have been in the replies of 2 days ago when I opened this issue.

**Comment by Natureshadow** [comment]
I have seen Google mark false positive spam with IPv6 a lot. I had to pin Gmail.com down to v4 on several mail servers.

Nothing you can really do about it. Google is not about e-mail, it's about vendor lock-in.

**Comment by mucek4** [comment]
Currently I locked v6 down. If there will be no other way I'll move my server to different IP

**Comment by Lineflyer** [comment]
No more problems reported from users on support. Closing until further notice.
