### ISSUE TITLE
Filter by Location (country)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5257]
From support mail:

Hello guys. Please add filter by Location (country). Could be very usefull to sort stored caches to different lists. Thanks.

**Comment by rsudev** [comment]
Hmmm - any ideas how this could look like in our current filtering UI? I currently cannot picture it for me.

**Comment by Lineflyer** [comment]
In the current UI it should most probably be another main item in Saved list -> Menu -> Filter.
But maybe this should only be done once we have a new filtering approach...

**Comment by jakedot** [comment]
Is there a different approach to filtering now? I could try to do it, doesnt seem too difficult.

**Comment by moving-bits** [comment]
No, it hasn't changed in terms of structure AFAIK, only a few filters got added.

If you want to add this filter, have a look at the `filter` subdir, the `FilterRegistry` class, and see if it can be added to one of the filter types mentioned there, or if you have to add a completely new filter type.

**Comment by jakedot** [comment]
Is it already possible to have a second layer in filter selection? Like the lists, only the countries could have the states etc as selectable subdivisions.

**Comment by jakedot** [comment]
I would just query the available locations from the database, it probably doesn't make sense to have a static list of ~250 countries / US states pop up when a user only has caches in 3 countries stored.

**Comment by moving-bits** [comment]
> I would just query the available locations from the database, it probably doesn't make sense to have a static list of ~250 countries / US states pop up when a user only has caches in 3 countries stored.

I don't know if it's technically possible, but maybe you can show only values existing in the current list?

**Comment by moving-bits** [comment]
> Is it already possible to have a second layer in filter selection? Like the lists, only the countries could have the states etc as selectable subdivisions.

Don't think so, but: Here are a few examples from a quick look into a sample database. There is no distinction between country, county, city etc., just one plain text field (cg_caches.location):

| location |
| --- |
| Nordrhein-Westfalen, Germany ||
| Niedersachsen, Germany ||
| Berlin, Germany ||
| Lorraine, France ||
| Luxembourg ||
| Saarland, Germany ||
| Liège, Belgium ||
| Rheinland-Pfalz, Germany ||
| Tirol, Austria ||
| Bayern, Germany ||
| Hamburg, Germany ||
| Hessen, Germany ||
| Thüringen, Germany ||
| Gelderland, Netherlands ||
| Denmark ||
| Flevoland, Netherlands ||
| Noord-Holland, Netherlands ||
| Zuid-Holland, Netherlands ||
| Friesland, Netherlands ||
| Noord-Brabant, Netherlands ||
| West-Vlaanderen, Belgium ||
| Utrecht, Netherlands ||
| Drenthe, Netherlands ||
| Limburg, Netherlands ||
| Overijssel, Netherlands ||
| Netherlands ||
| Limburg, Belgium ||
| Antwerpen, Belgium ||
| Vlaams-Brabant, Belgium ||
| Hawaii, United States ||
| Washington, United States ||
| Brandenburg, Germany ||
| São Paulo, Brazil ||
| Steiermark, Austria ||
| California, United States ||

**Comment by jakedot** [comment]
I will start by restricting it to country names then. We could extend it later, if users want it. Or should I just use all distinct location contents?

**Comment by jakedot** [comment]
> 
> 
> > I would just query the available locations from the database, it probably doesn't make sense to have a static list of ~250 countries / US states pop up when a user only has caches in 3 countries stored.
> 
> I don't know if it's technically possible, but maybe you can show only values existing in the current list?

Yes that's exactly what I was trying to say with the comment you quoted!

**Comment by jakedot** [comment]
Is there a way to get an iterator over all stored caches? I'm guessing via the "All Caches" virtual list? Or is there something more low level?

**Comment by moving-bits** [comment]
> > > I would just query the available locations from the database, it probably doesn't make sense to have a static list of ~250 countries / US states pop up when a user only has caches in 3 countries stored.
> > 
> > I don't know if it's technically possible, but maybe you can show only values existing in the current list?
> 
> Yes that's exactly what I was trying to say with the comment you quoted!

Question is where to retrieve the data from. I thought you meant to create a list of all locations available in the database - and a comfort feature could be to reduce this to the locations existing in the caches of the currently displayed list. 
This list can be virtual, even have unsaved caches, so you need to query the in memory list of caches for their locations at least in some cases. (In other cases, when it's a manifested list, you may ask the database to do it for you.)

**Comment by moving-bits** [comment]
> Is there a way to get an iterator over all stored caches? I'm guessing via the "All Caches" virtual list? Or is there something more low level?

See my last comment - I wouldn't retrieve locations of all caches in the database, but only of those displayed in the current list the filter is to be applied onto.

Example: I tend to have something between 5.000 and 10.000 caches stored in c:geo, resulting from many different countries, nicely sorted into separate lists. A "give me all" approach probably would result in a list of 50 or more different locations, whereas a "displayed only" approach seldom would give more than 5 or 10 different locations - much easier to handle as a user.

**Comment by jakedot** [comment]
I'm currently looking around how this is implemented. Something like this, but with an additional query parameter for the list id, yes? Or do I need to look somewhere else, too? 

> in memory list

Where would I find that? Is it the CacheCache?

I would have done something like this in the DataStore:

```
public static List<String> getStoredLocations() {
        final List<String> locations = new ArrayList<>();

        init();

        try {
            Cursor cursor = database.rawQuery("SELECT DISTINCT c.location FROM " + dbTableCaches + " c", new String[0]);

            if(cursor.moveToFirst()) {
                do {
                    locations.add(cursor.getString(cursor.getColumnIndex("location")));
                } while (cursor.moveToNext());
            }

        } catch (final SQLiteDoneException ignored) {
            // Do nothing, it only means we have no information on the cache
        } catch (final Exception e) {
            Log.e("DataStore.getStoredLocations", e);
        }

        return locations;
    }
```

And in the new CountryFilterFactory, I'd call this and parse out the countries. (SQLite doesn't seem to have a nice way for string manipulation...)

**Comment by jakedot** [comment]
I don't see where I can query the current list inside a filter... So I made a preliminary PR.

**Comment by moving-bits** [comment]
> I don't see where I can query the current list inside a filter... So I made a preliminary PR.

That's probably not possible as a "cache list" in memory is just a set of geocodes, IIRC. Those "cache lists" can be search results (having no equivalent in the database at all), manifested lists (its collection being stored in the database) etc.

Thus if you want to restrict your query to the caches in the current cache list you need to query every cache for its location, using the Geocache object model.

**Comment by jakedot** [comment]
The question then is where I can get those geocodes of the current cache list at the point where the filter is created? I've not yet found anything on it.

**Comment by jakedot** [comment]
I have implemented a function for querying all distinct locations for a set of geocodes now. What is still missing, is obtaining that set when creating the filter. IMO, this set should be passed in from outside? Seems cleaner to me than having to get it from some static instance or some such inside the filter factory...
