### ISSUE TITLE
Switch everything to https

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5260]
There are still a lot of places where we use http instead of https. We should switch to https or when this is not feasible document why (for example, the certificate for coord.info is invalid as GroundSpeak uses the same one as *.geocaching.com/geocaching.com).

**Comment by Lineflyer** [comment]
Does anyone know if there is still a place we use unencrypted http?

**Comment by mucek4** [comment]
On some of our services, but it's a separate issue.

**Comment by Lineflyer** [comment]
You are right. Such kind of generic issue will probably never be closed. I will close this and everyone can open issues dedicated to certain affected services then.
