### ISSUE TITLE
Cleanup gc.com log posting

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5261]
When we post logs on gc.com, we send too many fields, using their `Old` scheme. We should switch to the `New` scheme (the one used by web browsers) and limit the fields we send to those which are requested. Trackable log post should be cleaned up as well.

**Comment by SammysHP** [comment]
> 30.10.2015 00:19:04 <SammysHP> I only see that we have some "legacy code" in line 1075 of cgeo/geocaching/connector/gc/GCParser.java

**Comment by Lineflyer** [comment]
Link to #6519

**Comment by Lineflyer** [comment]
@pstorch I assume this is obsolete due to the usage of the new logging page? Else please kindly reopen.
