### ISSUE TITLE
Coordinate dialog broken in landscape mode

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5262]
2015.10.31-NB on my tablet Samsung SM-P600 as well as on my Samsung Galaxy S4:

In landscape mode the new input dialog is missing the OK/Cancel and the buttons "Cache Coordinates" and "My Coordinates". Switching to portrait mode it looks ok.

![screenshot_2015-10-31-22-22-12](https://cloud.githubusercontent.com/assets/949669/10865996/8c900b02-801e-11e5-8f9f-6271f7345222.png)

**Comment by rahu** [comment]
thanks for testing this. I haven't recognized the landscape layout for coords input dialog :-(

**Comment by Lineflyer** [comment]
Reopening for field test

**Comment by Lineflyer** [comment]
Working with 2015.11.08-NB
