### ISSUE TITLE
Retire legacy version of c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5263]
With the changes on gc.com on October, 29th (see #5258) the legacy version will no longer work (posting logs not possible).

I suggest to retire the legacy version by publishing a new release without functionality but a notification on the main screen showing that c:geo no longer supports this Android version and afterwards depublish it form Google Play.
This would be the same procedure as the one which was done for the non-opensource version of c:geo AFAIR.

Another option would be to just remove it from Google Play and push a permanant notification via status.cgeo.org to *-legacy versions.

**Comment by SammysHP** [comment]
I suggest to release a final version that has a permanent notification (also without internet) that the version is not maintained anymore. After that it should be removed from Google Play. But we should keep it on our website because some people might want to use it on old devices because c:geo with pocket queries on old devices are still great for caching (and costs less if one breaks his phone).

**Comment by Lineflyer** [comment]
AFAIR there is already such an notification but it is only shown on the first 3<x<5 starts of c:geo.
If someone could make this permanent we could more or less immediately release from `legacy` branch.

**Comment by Lineflyer** [comment]
Can someone do as suggested? We should get rid of that non working version asap.

**Comment by mucek4** [comment]
If I understand it right Legacy does not work because of "https" or?

**Comment by samueltardieu** [comment]
@mucek4 We know that the online posting will not work at least because of this. AFAIK nobody is testing the other features yet.

**Comment by samueltardieu** [comment]
@Lineflyer I thought that the `status_closeout_warning` was displayed every time. Are you sure there is such a counter?

**Comment by Lineflyer** [comment]
This is just as far as I remember. If you can confirm it is displayed all the time it is ok.
If this is the case...what shall we do?
Just revoke from Google Play and thats it or anything else?

**Comment by Lineflyer** [comment]
From IRC today:
```
[21:37] <Lineflyer> I think we should retire it somehow...like keep it as an offline version
[21:41] <rsudev> That sounds feasible - you can still use it on old devices and use whatever tooling to get your caches as gpx to the device. Not as convenient as doing live geocaching, but maybe better than nothing
[21:52] <Lineflyer> Can we disable it somehow? So we should adapt the closeout warning to "...only offline" and remove online function for gc.com
[21:52] <Lineflyer> and make the warning clickable to FAQ (as it is now but to a certain entry)
[21:53] <Lineflyer> seems the current anchor got invalid
```

**Comment by Lineflyer** [comment]
As discussed on IRC the legacy version has been disabled on GooglePlay just now.
This means that at least no new installations will happen, still we need to find a final retirement solution.

**Comment by Lineflyer** [comment]
As a first step to make users aware we could change the string `<string name="status_closeout_warning">` to a sentence like 
"Your android version is now longer supported. This c:geo version will not work online anymore"

/cc @rsudev Could we get this translated via Crowdin and pushed to `legacy`branch afterwards?

**Comment by Lineflyer** [comment]
This will no longer happen. We just keep the existing installations for devices with SDK<7.
