### ISSUE TITLE
Amount of favorite points not updated when awarding a favorite point in logging view

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5264]
2015.10.31-NB:
- Open a cache
- Select "Log Visit"
- Post your log and select (the new) checkbox for "Add to your favorites"

When returning to the cache details afterwards the state is not updated:
- The amount of favorite points for the cache is not incremented
- The button still shows "Add to your favorites"

Expectation:
If posting the log was OK, the information of the (stored) cache should be updated in cache details accordingly to avoid user confusion.

@madankb

**Comment by madankb** [comment]
I will check this issue.

**Comment by samueltardieu** [comment]
@madankb Any news on this?

**Comment by madankb** [comment]
Sorry for the delay.. Got held up in other works.. I will fix it as soon as
possible.

**Comment by madankb** [comment]
Can someone please review my code for the PR#5367?.
