### ISSUE TITLE
Ignore Cache

### ISSUE THREAD

**Issue by Bugsy1905** [cgeo/cgeo#5268]
When you select ignore cache from the cgeo menu on the selected cache, it states that if you need to see this cache again you need to restore it from Geocaching.com. However, this doesnt work - i have chose two different caches to ignore, but they still appear on my map and nearby list.

**Comment by Lineflyer** [comment]
@Bugsy1905 
Can you please post the system information shown in About c:geo -> System?

**Comment by Bugsy1905** [comment]
--- System information ---
Device: D5803 (D5803, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.232
Cgeo version: 2015.10.30
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins: calendar
--- End of system information ---

Cheers

Matt

**Comment by samueltardieu** [comment]
By reading the code, I can see that the cache is dropped from the CacheCache but is not dropped from the database. This is likely to be incorrect.

**Comment by procount** [comment]
This still seems to be an issue in version 2016.002.03.
Ignoring a cache will add it to the geocaching ignore list and remove it from offline storage.
But when the map is refreshed, the cache re-appears again and its details can be viewed.
It appears to me that C:Geo is ignoring the ignore list on groundspeak.com.
