### ISSUE TITLE
Add possibility to copy raw text from cache description

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5270]
Now when I'm trying to select and copy some text from cache description, I have only upper bar with "Copy" and "Share" buttons. So, the first problem is - I cannot select custom text from description.
Then, when I click "Copy" button it copies all the raw content with HTML tags and so on, so it's really useless in such form. Suggestion to copy only meaningful text.

**Comment by SammysHP** [comment]
Duplicate of #5202 and #3819.
