### ISSUE TITLE
Multiple select in GPX import

### ISSUE THREAD

**Issue by olpp** [cgeo/cgeo#5273]
To keep my homezone list up-to-date I let groundspeak create about 10 PQs once or twice a week and import the GPX files one after another.

How about to invent a multiselect mode in the GPX import window to select multiple GPX files and let cgeo import them one after another without further interaction?

**Comment by triakcz** [comment]
This is good idea, I'm using same approach (but I have just 4 PQs), still it is a lot of manual work to import all of them one by one. Also it will be great if it will automatically select destination list for such GPX.

Related to #5959, combined with "Update" feature as described it will be very useful improvement.

**Comment by Lineflyer** [comment]
Meanwhile we use the storage access framework to read GPX files and this also allows to select mutiple files for import in one step. Tested and working with 2022.10.06-NB on Android 12.
