### ISSUE TITLE
Coord handover to mapy.cz no longer working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5275]
A lot of people contacted support mail because of this.
The problem started after update to a newer version of this mapy.cz app, however I sill want to share this here as I don't know whether mapy.cz has a bug or we do use a special implementation for this app which is no longer valid for some reason now.

Here is a good problem description from support.

I have set as secondary navigation external source - application mapy.cz. The connection between c:geo and mapy.cz worked well until last big update of mapy.cz. Now, when I want to show cache in mapy.cz, it doesn't work. Through c:geo is opened application mapy.cz, but coordines are no shown (this worked before).

It only works when I copy coordinates in format DD.DDDDD from c:geo to mapy.cz and I have to change "," for "." because it is copied from c:geo with ",", but it doesn't work in mapy.cz with ",".

**Comment by SammysHP** [comment]
Once we discussed whether coordinates should respect the locale or not.

If there's no special API that we use, then c:geo calls a standardized URI.

**Comment by Lineflyer** [comment]
Update:
mapy.cz release an update today where the release note state that "connection to c:geo" is fixed.
So it was a problem on their side and fix is confirmed by users on support mail.
