### ISSUE TITLE
Inconsistency of notes in user defined waypoints 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5276]
Current market version 2015.10.30 and current master (NB):

- Open a saved cache without waypoints
- Add a new waypoint of type "Stage with question" (others might produce the problem as well, however "Reference point" is working)
- Enter the note (NoteA) for this waypoint in the note field
- Save the waypoint
- Verify that the waypoint is stored and the note is shown correctly
- Add another waypoint of type "Stage with questions" 
- Enter the Note (NoteB) for this waypoint in the note field
- Save the waypoint

Result:
Both waypoints shown with correct coords but both waypoints show "NoteA", the string "NoteB" is lost.

**Comment by rsudev** [comment]
I did a test on my device as described - could not reproduce.
Could you re-check? What do you mean with 'verify' - just look at the information shown in the WP list?

**Comment by Lineflyer** [comment]
@rsudev 
verify= just look
Did you make sure you select the correct WP type as described above?

Will try to reproduce with current master as soon as time permits.

**Comment by Lineflyer** [comment]
I just retested it on current master and can no longer reproduce it.
Strange, as I tested it twice with the current master from the date where I opened this issue.

Lets keep it open for some weeks. Will see if I can reproduce it once again.

**Comment by Lineflyer** [comment]
Refer to  #5366
