### ISSUE TITLE
Reload all saved caches and update all descriptions at once

### ISSUE THREAD

**Issue by bioinf-ice** [cgeo/cgeo#5277]
Thanks for the app!

Recently, I was thinking about a new feature. Usually, I save the geocaches for one city before I go for hunting.

After a while, many caches are in a list and many of them I saved weeks ago. It would be nice have a button to reload all saved geocaches and make the description up-to-date. At the moment, you have to click on each individually to update them.

**Comment by samueltardieu** [comment]
No you don't :-) There is a "refresh all" item in the list menu (the tree dots).

**Comment by bioinf-ice** [comment]
Thanks for the help. 

Now I found it. I have to click 'Auswahlmodus' (select modus) first, then 'refresh all' appears.

**Comment by SammysHP** [comment]
"Refresh all" is missing in the "all" list. @Lineflyer is this a known issue?

**Comment by samueltardieu** [comment]
This is a known feature.
