### ISSUE TITLE
Versioneye not working anymore

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5279]
Since we use properties

**Comment by Bananeweizen** [comment]
I'm actually thinking of removing the properties for version numbers completely. There are only 2 or 3 which occur multiple times (like JDT null annotations). And for update checks we can use the gradle tasks, which work fine independent of whether we use properties or not. Also the android plugin will tell us if we mix up version numbers in the app and the test bundle.

So basically I don't see much value anymore in the extracted version properties and would rather like to inline them.

Any objections?

**Comment by samueltardieu** [comment]
No objections.

**Comment by Bananeweizen** [comment]
I have played around some more with versioneye over the last days. The gradle internal mechanisms for checking updates are surely more stable, and even more easy to. I've already removed versioneye from the project page readme file. If anyone has links to the old project, please expect them to be deleted in the near future.
