### ISSUE TITLE
TB missing in inventory if name contains special characters

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5280]
From support mail and tested by temporarily grabbing the affected TB:

2015.10.30:
- Have a TB in your inventory which contains the character `²` (Example: TB5AHKB)
- Start logging activity for a cache

The inventory list is populated with all TBs in inventory except the problematic one. It is completely missing.
No error or info shown in adb log when starting logging.

**Comment by kumy** [comment]
Tested with TB532BT. Cannot reproduce.

**Comment by Lineflyer** [comment]
Then something else than ² is causing it.
I send you the tracking code to grab and test.

Grab this initially mentioned TB with this code: HG8D8W
The holder will grab it back tomorrow. (and I will delete this part of my reply after posting).

**Comment by kumy** [comment]
@Lineflyer thanks

**Comment by kumy** [comment]
Confirmed broken with the original mentioned TB.

**Comment by Lineflyer** [comment]
Perfect. Please save any needed raw data. 
The holder will grab it back tomorrow.

**Comment by kumy** [comment]
Problem should be `<sup>`

```
			<td><a href="/track/details.aspx?tracker=xxx">xxx</a></td>
			<td>HGCS People: WTT- B<sup>2</sup></td>
			<td>
                        <select name="ctl00$ContentBody$LogBookPanel1$uxTrackables$repTravelBugs$ctl02$ddlAction" id="ctl00_ContentBody_LogBookPanel1_uxTrackables_repTravelBugs_ctl02_ddlAction">
				<option value="4521332">- No Action -</option>
				<option value="4521332_DroppedOff">Dropped Off</option>
				<option value="4521332_Visited">Visited</option>

			</select>
                    </td>
```
vs
```
			<td><a href="/track/details.aspx?tracker=xxx">xxx</a></td>
			<td>Lili²</td>
			<td>
                        <select name="ctl00$ContentBody$LogBookPanel1$uxTrackables$repTravelBugs$ctl04$ddlAction" id="ctl00_ContentBody_LogBookPanel1_uxTrackables_repTravelBugs_ctl04_ddlAction">
				<option value="4298146">- No Action -</option>
				<option value="4298146_DroppedOff">Dropped Off</option>
				<option value="4298146_Visited">Visited</option>

			</select>
                    </td>

```

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Confirmed working with 2015.11.15-NB
