### ISSUE TITLE
Personal note doubled

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5286]
Folllowing info from support mail (and I have also seen this happening once in a while).
It seems that the process is triggered which should merge the notes between local and server although there is no server communication involved.

Here is the info from support mail:

Problem's scenario:
  - save a cache offline, add a personal note, save it and leave the cache
  - return to the cache with the previously saved personal note
  - re-edit the note (change some stuff, perhaps use copy 'n paste) and save it
--> the personal note is duplicated, with a "--" line between the copies

Most sadly this is not deterministic.  And although I tested and checked a lot, I cannot say which steps lead to this behavior, nor which conditions "must" be fulfilled to let it happen.  Moreover it does not happen with every cache, but if it happened once, it happens every time I change the note of this cache.
What I can say: It does not matter if I have previously uploaded the personal note or not; it does not matter where the cursor stands in the text; it seems to not matter if I use copy 'n paste or not.

**Comment by GodfatherThe** [comment]
Hmm, reading your description I understood I met such an issue when I was caching in BCN. Yes, it was sighting issue and it was not reproducible, but I definitely remember I saw it..

**Comment by Lineflyer** [comment]
Refer to #5854 (Closing as this is more or less a duplicate)
