### ISSUE TITLE
Watchlist total not visible on own caches

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#5288]
So nice to get another of my feature requests (#4058) fulfilled!
Thanks a lot @ThibaultR for the coding!

But I just discovered that the feature is missing on caches that you own.

**Comment by Lineflyer** [comment]
I can not confirm that.
@MrYaz: Please note, you might need to refresh already stored caches to retrieve the new information.

**Comment by Lineflyer** [comment]
By the way:
@ThibaultR  What is your opinion about changing the strings a little: `total: x` might be confused with the total amount of caches on your watchlist, but it is the number of people watching the particular listing. So I would suggest `Watchers: x` instead.

**Comment by Lineflyer** [comment]
I changed the strings as described above.

**Comment by ThibaultR** [comment]
@Lineflyer "Watchers" is much better, you are right :)

**Comment by MrYaz** [comment]
Sorry, you are right. I had not refreshed the stored cache.
Problem solved.

Regarding the term "Watchers" I am a bit sceptical about introducing a new term that is not normally used in geocaching. Except for the mugglers looking through their windows wondering who is lurking around their neighbourhood. :-)
It is also hard to translate into something natural in Swedish and maybe in other languages as well?
I think it is better to leave it as `(total:x)` or simply `(x)` like it is on geocaching.com. No explanation is needed there. And I think that users will understand from the context what the number stands for.

**Comment by Lineflyer** [comment]
Thanks for feedback regarding the issue.

Will think about the wording.
