### ISSUE TITLE
Add instruction for beginners how to configure build environment

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5289]
There are instructions how to contribute, but there is no info how to configure all the stuff to build c:geo (IntelliJ Idea, SDK, Gradle, etc.), . It can be helpful for beginner developers...

**Comment by samueltardieu** [comment]
What would you need in addition to what is already in `README.md`? https://github.com/cgeo/cgeo/blob/master/README.md

**Comment by GodfatherThe** [comment]
- What IDE do you use\recommend: Android Studio or IntelliJ IDEA? AFAIK they're pretty similar, so which one should I choose?
- I had some troubles with Gradle, but it seems because I didn't read readme carefully and missed the "Building with gradle" bullet - I tried to install Gradle manually and met a couple of minor issues in IDEA.
- And minor addition: is Eclipse still actual? It stands on the first place and it can be confusing.

**Comment by samueltardieu** [comment]
- Use the one IDE you like most. Some developers use Android Studio, I use IDEA.
- You don't need to install Gradle, just use the Gradle wrapper in the repository, for example: `./gradlew packageDebug`. Everything (including Gradle) will be downloaded for you.
- It is not actual and marked as obsolete, but it still works, and some developers still use it, but we will remove this section soon.

**Comment by GodfatherThe** [comment]
Ok, thanks, you can close the issue
(A bit of off-topic - do you know what's with Crowdin? I cannot open the cgeo page for the last few hours...)

**Comment by samueltardieu** [comment]
Crowdin may be really slow from time to time.
