### ISSUE TITLE
PlayServices Android 6.0 compatability?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5290]
Does anyone have experience with c:geo on an Android 6.0 device?

From support mail:

My "guess" is that "something" within my recent update to Android v6.0 Marshmallow has changed how the state of Google Play Services "appears" to the C:Geo app.  (appears to be disabled). [...] MAPS and CALENDAR seem to work fine...........but C:Geo still displays "GPS disabled" when I have your System/Use Google Play Services enabled (checked).  So I'm "guessing" that Play services may well be active, but it appears to C:geo to be disabled. Alternatively, there may be something unique about my Android v6.0 and Nexus 7 (2013) which is disabling c:Geo's access to that service.  Who knows?

**Comment by samueltardieu** [comment]
Works fine for me. Could you ask for the system information (with Play services enabled)?

**Comment by Lineflyer** [comment]
Will do.
btw: Isn't the french support mail you answered about the same topic maybe?

**Comment by kumy** [comment]
It's also okay for me.

**Comment by samueltardieu** [comment]
@Lineflyer: nope

**Comment by Lineflyer** [comment]
Symptoms from that user are:
Left side of main menu in c:geo shows "GPS disabled", right side shows "Fused". GPS system icon not active. He verified by disabling, factory resetting and updating that GooglePlay Services are installed in newest available version (he did not tell me the version number yet however).

**Comment by samueltardieu** [comment]
It may be a bug on our side, but he also needs to check that he selected GPS in Android location services.

**Comment by kumy** [comment]
I would also check if permission to access the location hasn't been disabled.
Settings -> Apps -> c:geo -> Permissions -> Location

**Comment by Lineflyer** [comment]
@kumy In this case I would assume that it also (or only?) fails if Play Services are not used...

@samueltardieu Does it make sense (and is it possible) to add the installed version of Google Play Services to our system information?

**Comment by kumy** [comment]
@Lineflyer right, disabling like this will prevent accessing the GPS with and w/o Google Play Services.

Another possibility (at least on CyanogenMod) would be to prevent Google Play Services from accessing the location (it happens to a friend on CM11) some applications like Google Map or Waze successfully got a location, probably by an automatic fallback to using the GPS directly. (We've found this thanks to c:geo :sunglasses:)
This could be checked from:
Settings -> Privacy -> Privacy Guard -> ... (3 dots menu) -> Show built-in apps. Then disable/enable Google Play Services

**Comment by Lineflyer** [comment]
No more feedback from that affected user and no other complaints on support mail.
Closing without changes.

**Comment by PaulieS** [comment]
Hi. I've this same problem on my Moto G 2 with Android 6. C:Geo says that "GPS is disabled". I've gave permision for location to app. GPS starts working when i turn on Google Maps in background. When google maps are in backgroud C:Geo app says that GPS is on and it's working.

**Comment by drjobec** [comment]
I have the same bug on my Moto G 3 (2015) with Android 6.0. With Google Play Services enabled, c:geo says "GPS disabled", but disabling the Services results into a functioning system.
From system information:
Device: MotoG3 (osprey_reteu_2gb, motorola)
Android version: 6.0
Android build: MPI24.65-33
Cgeo version: 2016.06.09

**Comment by Bananeweizen** [comment]
While I do not have the same symptoms with my device, I remember that same behaviour from emulator images (showing GPS disabled, fused), so maybe debugging with an emulator gives some hints.
