### ISSUE TITLE
Crash when adding personal note from WP or Images tab

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5296]
Found this strange issue during Russian localization testing. Here is the test case:

0. Store a cache for offline use.
1. Open Cache details
2. Slide to page with Waypoints or Images
3. Press button with 3 dots
4. Press 'Personal notes" 
5. Enter some text
6. Press "OK"

Application will crash.

Some notes:
- The case is not reproducible from Description or Details or Logbook pages, only from Images and WP
- I found that I cannot add a personal note to a cache if it wasn't stored. Button "Personal notes" just does nothing. I assume this as a separated FR to allow to write personal notes for non-stored caches (or add error message for such case)

My phone is Xperia Z3 Compact, Android 5.1.1
C:geo 2015.11.29-NB1-a4faa8b

**Comment by rahu** [comment]
Thanks for testing. I think the crash is related to #5253 - I'll check this.

**Comment by Lineflyer** [comment]
Huh...is this menu item a new feature. I have just seen it for the first time.

**Comment by rahu** [comment]
correct this is a new feature. The intent was to edit the note from every other view - and to stay on this view after saving the note. 

Unfortunately this crash is not so easy to fix. When sliding to Waypoints View the DescriptionView get's destroyed -> personalNoteView is bind to this view -> ButterKnife.findById(this, R.id.personalnote) returns null in CacheDetailActivity::onFinishEditNoteDialog and c:geo crashes in CacheDetailActivity::setPersonalNote. Of course I can add a null - check in onFinishEditNoteDialog, but the feature is still broken from Waypoints and Images. 

I have no idea how to fix this right now...

**Comment by Lineflyer** [comment]
Was this added in the commits made for #5253 ?
If yes:
We should really seperate one new feature from another and make an explicit announcement (=Issue) for that. I was not aware and therefore did not test anything related to this.

From my opinion we should remove this feature as long as no solution is available.
Adding this issue to the ToDo for next feature release.

**Comment by rahu** [comment]
I agree with your first point.

The fix is available now - removing the feature is not necessary.

**Comment by rahu** [comment]
For the second issue I see two possible fixes:
1) don't show the personal note buttons if cache is not saved
2) make the note editable even if the cache is not saved. It should be possible to save the cache afterwards or upload the note without saving.

I would prefer the second solution, maybe with some hint saying the note is not saved. What do you think?

**Comment by GodfatherThe** [comment]
I would prefer second way or
3) Show message like "You cannot add personal note to online cache. Do you want to store it?" with "Yes\No" buttons.

Regarding the 2) - probably it will be more difficult to implement. The easiest way is just store cache offline, then it won't break any existing logic, but it might be confusing to the user because he\she could be not aware of saving cache. With 3) and warning message it will be clear, I think.
