### ISSUE TITLE
Wrong error toast after deleting cache from list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5297]
Market version 2015.11.29:
After selecting delete on cache detail page some users see a toast message "cgeo could not find the cache" (or similar) when returning to the list.

**Comment by samueltardieu** [comment]
Confirmed with development version.

**Comment by samueltardieu** [comment]
Is it important to get it fixed on `release`, or would `master` be enough?

**Comment by Lineflyer** [comment]
I am not sure what is happening here.
Is it only a "wrong" toast or is the cache not deleted or any other more serious malfunction?

**Comment by samueltardieu** [comment]
The code to delete a cache is shared with the code to ignore a cache. To ensure that a cache which is ignored is immediately hidden, I made it removed not only from the DB but also from the in-memory cache. Unfortunately, that has the side effect of totally removing the cache even when pressing "Delete", which means that the cache can no longer be displayed.

I have a fix for the `master` branch already, but many changes in packages and split classes make it difficult to use the same fix in `release`. But I have also a fix ready for `release`, so I'll test that and put it there and manually merge it into `master`.

**Comment by Lineflyer** [comment]
@samueltardieu Thanks for explaining.
As this is very present to the user I would also suggest to solve it on `release` altough it is technically not really critical.

**Comment by samueltardieu** [comment]
Now the popup is shown only when the cache is ignored. I could have avoided the popup and returned to the list, but it is not necessarily bad to see "cgeo cannot find this cache", this illustrates the ignore in action.
