### ISSUE TITLE
Add self-links to FAQ

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5304]
It would be useful to be able to click on a FAQ title (in the full version of the FAQ) and get a link to the anchor of the entry, so that we can easily send it when answering a support question without looking for the right link again in the summary.

**Comment by SammysHP** [comment]
Wrong repository. ;)

Fixed in https://github.com/cgeo/cgeo.github.io/commit/23bd5982882da405b6085f459f51f96c0d3b2976.

**Comment by Lineflyer** [comment]
Has been implemented.
