### ISSUE TITLE
remove swaggies

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5305]
they are deprecated by now: http://forum.geocaching.com.au/viewtopic.php?f=1&t=18878&start=0&hilit=swaggies

**Comment by samueltardieu** [comment]
Will you do it? Otherwise, I will. I love deleting code :)

**Comment by kumy** [comment]
`/main/res/drawable-hdpi/trackable_swaggie.png` file could also be removed.

**Comment by samueltardieu** [comment]
Done.
