### ISSUE TITLE
Add localized versions for distance units

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5307]
Now distance units are not being localized

```
   <!-- distance units -->
    <string name="unit_m" translatable="false">m</string>
    <string name="unit_km" translatable="false">km</string>
    <string name="unit_ft" translatable="false">ft</string>
    <string name="unit_yd" translatable="false">yd</string>
    <string name="unit_mi" translatable="false">mi</string>
```

But they can be easily translated, so why not do so?

**Comment by SammysHP** [comment]
Can you give an example for a translation? AFAIK they are the same in every language.

**Comment by GodfatherThe** [comment]
For Russian:
м
км
фут
ярд
мил

For the last two ones (yd and mi) I'm not sure because we do not have official translations for the short names (because no one use it today here)

**Comment by Lineflyer** [comment]
Sure. For non latin languages this is required. What is missing to make them translateable? Something in the code ot just Crowdin translation setting?

**Comment by SammysHP** [comment]
We must remove `translatable="false"`, then upload to Crowdin.

**Comment by Lineflyer** [comment]
@SammysHP But they are split from the other strings located in `strings_not_translatable.xml`. That will probably not work with the current scripts and implementation of Crowdin?!

**Comment by rsudev** [comment]
They also need to be moved to the normal resources file - I can take care of that.
