### ISSUE TITLE
Localization issues in GPXImporter

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5308]
There are some strings in GPXImporter, which are not correctly localizable or not localized at all
- R.string.gpx_import_caches_imported_with_filename; 203: Needs plural
- Most of the other messages in the importStepHandler ar not localizable at all

**Comment by Lineflyer** [comment]
@rsudev 
Do you know, whether this is stil the case. I did not recently see any english strings when importing files.

**Comment by Lineflyer** [comment]
Is this still valid?

**Comment by moving-bits** [comment]
I'm not sure about GPXImporter specifically, but I remember having some lint issues pointing into the same direction. So even if we would close this issue, we still have the lint reminders.

**Comment by Lineflyer** [comment]
@moving-bits Fixed with #8538 ?

**Comment by moving-bits** [comment]
> @moving-bits Fixed with #8538 ?

Yes, `GPXImporter` should be fine now, therefore closing this issue.
