### ISSUE TITLE
Bug: Suggestion to delete filtered list with empty result

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5312]
Small glitch in the implementation for #5226:
If I have a filtered list (e.g. 'Status -found') and I remove the caches that are in the result (e.g. moving those to another list or deleting them), I get the suggestion to delete this allegedly empty list in spite of the number of filtered out caches still present on it.

**Comment by Lineflyer** [comment]
Good finding...this is more than "low" from my perspective..so I raised to "medium" and add it to the ToDo for the next feature release.
