### ISSUE TITLE
On Live MAP in the direction of travel

### ISSUE THREAD

**Issue by birdy1966** [cgeo/cgeo#5314]
A very funny feature would be in "Live MAP" on klick a button -> see all in the direction of travel

**Comment by SammysHP** [comment]
What should that button do?

**Comment by birdy1966** [comment]
When I use the LiveMAP it shows every time to: NORTH
But when I can push a button -> ist shows the live direction

At this time I must rotate the smartphone in the direction I walk

**Comment by SammysHP** [comment]
So you want a rotating map. We have already an issue for that.

**Comment by SammysHP** [comment]
See #1006
