### ISSUE TITLE
On Live MAP select/unselect Mysterys

### ISSUE THREAD

**Issue by birdy1966** [cgeo/cgeo#5315]
Also a very funny feature would be select/unselect Mysterys in the Live Map

**Comment by SammysHP** [comment]
Already possible with filters.

**Comment by birdy1966** [comment]
Sorry for my bad english :-(
I mean:
I want see ALL Caches but NO Mysterys.
That is not possible with the filters.
When I use filters,  I see ONLY Tradis, ONLY Multis, ONLY Mysterys, ONLY Events etc.
But better solution:  I see Tradis, AND Multis, AND Events, NO Mysterys.
or I see Multis, AND Mysterys, NO Tradis etc.

**Comment by SammysHP** [comment]
I thought it is possible to invert filters, but it seems like it's only possible with sorting. (See also #2508)

Anyway I think this is something that is related to issue #135 and #995.
