### ISSUE TITLE
Show name of caches on map

### ISSUE THREAD

**Issue by birdy1966** [cgeo/cgeo#5316]
And a funny feature would be to see/unsee the Names of the Caches on the LiveMap

**Comment by SammysHP** [comment]
Please don't prefix all issues with "IDEA -> ->".

For most caches we don't know the name of the cache when it's shown on the live map. Also it would clutter the UI (if there are more than three caches on the map).

**Comment by birdy1966** [comment]
c:geo is the greatest programm for Geocaching ! and I use this every day since about 3 years and 2000 Caches.
I never want to miss it.

This feature works perfekt in the App: "CacheSense"....but I do not want to use CacheSense :-(
And the WalkDirection also works very good

**Comment by Lineflyer** [comment]
Couly you provide a screenshot of the implementation you mentioned in (CacheSense)?

**Comment by birdy1966** [comment]
no problem
![cachesense](https://cloud.githubusercontent.com/assets/16198248/11680948/166b9782-9e5c-11e5-9b2d-499a3d41ca6f.jpg)
when I soom in (nearer) it shoes better
when I soom out its automaticly disabled

**Comment by SammysHP** [comment]
I see a lot of overlapping text and have problems to see the map.

PS: You can also write in German if it's easier for you.

**Comment by birdy1966** [comment]
Sobald ich näher reinzoome sind die Überlappungen fast verschwunden :-)
Allerdings wäre auch hier die Funktion "Mysterys ausblenden" sehr von Vorteil.
Wer will schon draussen in der Natur auf Mysterysuche gehen?
Die muss man ja zuerst zuhause lösen.
Multis und Tradis reichen ja für die LIVEMAP aus !

**Comment by rahu** [comment]
I like this suggestion. But it should be configurable for the user. I'm also thinking about using the gyro to fade in/out the names when phone is wiggled. It's much faster than clicking menu -> setup -> show names.

**Comment by Lineflyer** [comment]
My personal opinion:
I do not like that and it is seems nearly impossible to adapt this to all the different screens. The screenshot above shows a device with quite large resolution, the cluttering will increase on small screens or the text gets unreadable.

Moreover I guess it will be a lot of work to implement this in a good way. This effort should more importantly be spent to a general map rework (New Google version, rotating maps, etc.)

**Comment by rahu** [comment]
I'm often looking for a cache not knowing the exact name and position. I only remember its near to X and title is something like Y.  Searching on a map showing the names would be great in this case.

**Comment by SammysHP** [comment]
And please don't forget:

> For most caches we don't know the name of the cache when it's shown on the live map.

**Comment by Darwould1** [comment]
I suggest using only the first letter of up to the first 5 words in the cache name...to simplify the layout and would remind you which cache is which.

**Comment by Lineflyer** [comment]
I stay with my opinion, that I don't see the usefulness. I can switch to a list view anytime in c:geo or simply click on the cache to see its details. Furthermore there are other issues dealing with a better/new implementation of the map info popup when clicking a cache (like a split screen).

**Comment by Lineflyer** [comment]
Closing as new supporting posts came in.
