### ISSUE TITLE
"own and found" filter in search result list

### ISSUE THREAD

**Issue by birdy1966** [cgeo/cgeo#5317]
The great Function: "Own and findet Caches" show on MAIN-Site!! 
.....not in properties/cache-details/own and findet Caches/ select/deselect

**Comment by GodfatherThe** [comment]
Why do you need own and found caches on the main screen? AFAIK usually people want to hide these caches, but not to have easy access to them.

**Comment by SammysHP** [comment]
I assume he means the filter. It is available not only from the preferences, but also directly from the map. I couldn't find it in lists, though.

**Comment by SammysHP** [comment]
This issue was mentioned at the OC HQ event.

In the past I was against adding more filter options to the menus before we switch to a more complex filter system, but because this was delayed it might be better to add a checkbox to the list like we did for the live map in #2234.

**Comment by eddiemuc** [comment]
Solved with #9081
