### ISSUE TITLE
Filter Selection - 2 or 3 or 4 etc. possible to select

### ISSUE THREAD

**Issue by birdy1966** [cgeo/cgeo#5320]
Sorry for my bad english :-(
I want to select Tradi AND Multi AND EarthCaches
Now only one thing is possible or ALL Cacheforms

I mean:
I want see ALL Caches but NO Mysterys.

That is not possible with the filters.
When I use filters, I see ONLY Tradis, ONLY Multis, ONLY Mysterys, ONLY Events etc.
But better solution: I see Tradis, AND Multis, AND Events, NO Mysterys.
or I see Multis, AND Mysterys, NO Tradis etc.

**Comment by Lineflyer** [comment]
Duplicate and/or contained in #135 and #995
