### ISSUE TITLE
pull request build

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5323]
CI should build pull requests. The job has already be defined and works fine on a test pull request of mine, but it does neither report back to github nor does it detect new requests yet. Seems the authorization token in CI needs to be re-created.

**Comment by rsudev** [comment]
It seems they now report back (see my latest translation PR).
@mucek4 I think I found the reason for the build fails: platform-tools 23.1 is not compatible with linux-32bit
You probably need to downgrade (see e.g. http://askubuntu.com/questions/714653/adb-android-studio-ubuntu-error-unable-to-detect-adb-version-adb-output-hom)

**Comment by mucek4** [comment]
Downgraded.

**Comment by kumy** [comment]
I think it's okay now. Let's close.
