### ISSUE TITLE
alternative control concept for cgeo

### ISSUE THREAD

**Issue by rahu** [cgeo/cgeo#5325]
Yesterday it was cold (~0°C and windy). Since I don't have gloves for touchscreen use I got cold fingers while using cgeo - I don't like cold fingers. 

So thinking about how it could be possible to use cgeo with gloves the motion sensor came into my mind:
For CacheDetailView:
 - tend to the left / right ^= wipe to the left / right
 - tend to the top / bottom ^= scroll up / down

For Map:
 - maybe we can add crosshairs which can be moved by tending the phone. to select fast move forward and back. But this can also be added later. 

For Lists / mainmenu:
 - highlight the current selected item. move selection by tending the phone. select in the same way like map-select. 

Back:
 fast move left / right.

**Comment by SammysHP** [comment]
Uhm… that sounds a little bit too exotic. The touchscreen is the primary interaction method for a smartphone. This would require a lot of work to get a not intuitive interaction method. Have you tried a stylus? (These cheap pens with a rubber dome.)

**Comment by rahu** [comment]
I know there are some solutions available. stylus is only one of them. My one was @ home...
