### ISSUE TITLE
List not updated after import of cache from GPX

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5327]
Today I experienced the following issue:
- open a list
- select import - gpx
- select the file to import
- A popup tells that one cache was successfully imported
- go back from the file selection to the list - number of caches unchanged
- leave the list and re-enter - the new cache is there

**Comment by Lineflyer** [comment]
What version?

**Comment by rsudev** [comment]
My developer build which basically is latest master

**Comment by alan666notb** [comment]
I also see this on the latest version .. V2016.01.19

**Comment by Lineflyer** [comment]
According to #5441 this does also happen when importing a PQ (which is in fact a GPX-import).

**Comment by Lineflyer** [comment]
No longer reproducible with 2017.08.26-NB.
List gets updated without the need to leave and reenter.
