### ISSUE TITLE
App invite configuration

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5329]
I'm trying to create an app invite configuration since a while. However, the Google server never finishes displaying a page for me. Can another developer please follow the "get config" button at https://developers.google.com/app-invites/android/guides/app

**Comment by rsudev** [comment]
I am currently 'on the road', but can try today evening if nobody else jumps in.

**Comment by rsudev** [comment]
Same result for me (firefox 42.0 on linux).

**Comment by Bananeweizen** [comment]
got this working a while ago
