### ISSUE TITLE
Unable to load a certain trackable with secret code starting with GC

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5332]
Open the search function and search for the secret code GCxxxx (TB4W8Y6).
An error message is returnes almost immediately, although the code is known (refer to search on gc.com)

Could it be the fact, that it is starting with GC?

**Comment by kumy** [comment]
@Lineflyer that could be the problem, I'll look soon, unless someone treats it before.

**Comment by SammysHP** [comment]
I edited the post from @Lineflyer and removed the secret code (and added the public code). Please post the code to the mailing list if necessary.

**Comment by kumy** [comment]
The "problem" comes from an [explicit check for TB not starting with 'GC'.](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java#L36)

It has been introduced by [b4952210](https://github.com/cgeo/cgeo/commit/b495221082012e0fae252090d71a1e0f50b288c6#diff-48d5750b92bf6aaaab78461e76009167R24) @Bananeweizen do you recall the consequence to not having that check?

**Comment by Lineflyer** [comment]
I would have also assumed that GC... is not used as secret code to keep the namespaces separated and avoid misunderstandings. Thats in fact the first time I see a secret code starting with GC.

**Comment by Lineflyer** [comment]
@Bananeweizen Can you take a look at what @kumy asked?

**Comment by Lineflyer** [comment]
@Bananeweizen: Can you remove this restriction? Seems there are some trackable items recently release with secret code starting with GC as we get more complaints.

**Comment by kumy** [comment]
I'll do.

**Comment by rsudev** [comment]
You need to take the search bar into account here. That is likely the reason why this was introduced. When we search there, we cannot know if it is a trackable or cache, therefore all connectors get queried.
So IMO it should work in the trackable-specific search on the search page, but must not interfere with the global search on the main screen.

**Comment by kumy** [comment]
@rsudev good catch! I see what you mean. Thanks

**Comment by kumy** [comment]
@rsudev First I thought you've caught the reason of such limitation, but while looking at the search bar code [[1](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/SearchActivity.java#L147-L169), [2](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/SearchActivity.java#L73-L85)], I've found that the search is sequential. First the Caches then Trackables...
Any objection to simply remove [that condition](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/connector/trackable/TravelBugConnector.java#L36) and invert [the test](https://github.com/cgeo/cgeo/blob/release/tests/src-android/cgeo/geocaching/connector/trackable/TravelBugConnectorTest.java#L53-L54)? Am I missing something?

**Comment by kumy** [comment]
@Lineflyer as told on IRC, is it "so urgent that it needs to be fixed on release"?

**Comment by Lineflyer** [comment]
@kumy No, IMO this is OK to be limited to master.

**Comment by kumy** [comment]
So let's merge into master.

@Lineflyer maybe you could set the `Milestone` when you open such issue, that would help (me) :)

**Comment by Lineflyer** [comment]
Tested and working with the secret code of TB4W8Y6 using the dedicated trackable search (2016.02.22-NB).
Of course searching for the secret code in the main menu action bar is not OK, as this will open the geocache with the very same GCxxxx code. But thats fine IMO...no need to change something here for this quite special case.
