### ISSUE TITLE
FR: Gear Watch / Smartwatch support

### ISSUE THREAD

**Issue by datranquil** [cgeo/cgeo#5334]
I would love to see support for Samsung Gear 2/ Android Wear support. (Select next nearby cache, start navigation, mark selected cache as found/ not found/ needs maintanance for further detailed logging.

**Comment by rsudev** [comment]
There is already a companion app to allow naviagtion using an Android Wear device (see https://github.com/culmor30/cgeo-wear). It is probably the best idea to trigger a discussion around the features you suggest over there.
