### ISSUE TITLE
Wrong link to cache owners profile from cache details

### ISSUE THREAD

**Issue by bocktus** [cgeo/cgeo#5335]
Viewing the cache details of GC5QQEW in c:geo and opening the owners profile page in browser shows the profile of an user named mr.listel who has no caches hidden. 
Doing the same in Browser the link goes to the profile of user listel which is correct.

**Comment by bocktus** [comment]
This is no duplicate of #5237

**Comment by SammysHP** [comment]
I just tried it and c:geo opens the profile page of "listel" with 435 hidden caches.

Which version of c:geo do you use?

**Comment by SammysHP** [comment]
Another idea: How have you downloaded the cache in c:geo? Directly via c:geo or from a GPX file? I assume that the GPX file contains only one name, in this case the displayed name "mr.listel".

**Comment by bocktus** [comment]
my version of c:geo is 2015.11.29 on htc one (m7)
I opened it thru the found list in GCWatch-OS. (version 1.1)

**Comment by rsudev** [comment]
I could also not reproduce the issue. Perhaps you can export the cache to gpx and then post the result here (or send it to our support eMail, referring to this issue). We might learn something from that (as my export showed both listel and mr.listel in the gpx)

**Comment by bocktus** [comment]
After reloading the cache details in c:geo I also cannot reproduce it. Then I exported several different listings to gpx and all exports showed both fields. I opened them just like the above thru GCWatch-OS 

So I guess this is not a c:geo issue but a GCWatch-OS issue.

**Comment by Lineflyer** [comment]
AFAIK this app has been depublished from Google Play recently. I don't know the reason, however it could be some incompatability with recent site changes.
