### ISSUE TITLE
Live map misbehaving 

### ISSUE THREAD

**Issue by marcomatto** [cgeo/cgeo#5336]
I've been an appreciative user of c:geo for 16 months. Found 50+ caches in 5 countries and placed 16 of my own. This week on holiday in Cape Town South Africa, about 6 weeks since I last used c:geo, in Italy, I find the following:

Live Map loads with my location arrow in the centre of the screen, with nearby caches flickering  on and off, in their correct locations. The number of caches currently shown is reported at the top. By the time the map is fully loaded no caches are shown. Then a whole bunch of cache symbols appears along a vertical line down the middle, passing through my location arrow. Finally everything on the right of this centre line gets replaced by a uniform light blue.

I have tried the following:
Uninstalled c:geo and installed the latest version.
Upgraded from basic to premium membership and restarted my device to log in again.
Tried repeatedly over 24 hours.

Other c:geo functions seem to work normally as far as I can tell.

**Comment by rsudev** [comment]
That sounds quite strange. The behaviour you describe is something we know of. It is in the incarnations we found so far bound to a documented bug in the JVM that is distributed with MediaTek CPUs. I have not yet heard about such a case, where it first worked and than failed as you describe.
Might it be, that there was some update to your smartphone in the meantime?
Regardless, you can find our faq-entry with some background and a link to an alternative version where we try to work around this issue at the expense of some performance loss here: http://www.cgeo.org/faq.html#osm-mediatek-problem

**Comment by marcomatto** [comment]
Yes, this Media Tek problem looks just like the problem I have in terms of having all the cache symbols lined up down the middle. My smartphone is an Alcatel (though it doesn't say so) bought from Vodafone. I don't know if it has a Media Tek CPU. But yes, there was a phone update since I last used c:geo so maybe the equivalent problem was created. And finally, I installed alternative version of c:geo and hey, live map seems to work normally again. So thanks for the prompt assistance, and I hope the next phone update fixes the problem. Hope my information is helpful!

**Comment by rsudev** [comment]
Could you possibly post your system information (everything in c:geo - about - system) here, so we can deduce whether it is the well-known MediaTek issue or a new incarnation of it?

**Comment by marcomatto** [comment]
About phone
Model: Vodafone 785
Android version 4.4.2
Baseband version 6180
Kernel version: 3.4.67
Build Number: KitKat
Custom Build Version: 330HDG1

c:geo - about -system:

--- System information ---
Device: Vodafone 785 (Vodafone_785, Vodafone)
Android version: 4.4.2
Android build: KitKat
Cgeo version: 2015.12.06-NB-NOJIT-d90449f
Google Play services: enabled
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: fastest
HW acceleration: enabled (default state)
System language: en_GB
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins:  none
--- End of system information ---

**Comment by rsudev** [comment]
Thanks for the info. According to gsmarena (see http://www.gsmarena.com/vodafone_smart_4_mini-6295.php) its a Mediatek MT6572 chipset, so it is the known issue (and I wouldn't hold my breath waiting for an update to fix this one...).
Closing.
