### ISSUE TITLE
Allow switching off coord parsing from personal note

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5338]
..or improve it to make it more reliable.

Several users contact us regularly having problems with strange waypoints automatically created by parsing of the personal note. There seem to be cases, where we parse nonsense.

One example I received today:
Personal note content:

```
   A=6 B=0 C=5 D=4 E=13

   N 48° 53.(A*C*E)+194   E 009° 11.((D*71)-0)-1
   N 48° 53.(6*5*13)+194  E 009° 11.((4*71)-0)-1
   N 48° 53.(390)+194     E 009° 11.((284)-0)-1
   N 48° 53.584           E 009° 11.283
```

c:geo creates the following waypoint as parsing result:

```
N 48° 53,000  E 006° 00,000
```

This means users might see a lot of incorrect waypoints on their map without a possibility to permanentely remove them.

So I suggest to either improve the parsing or add an option to disable it in general so that affected users have a solution.

**Comment by rahu** [comment]
I would expect cgeo solves the formula in the given example. :-)

**Comment by SammysHP** [comment]
A formula solver is an often requested feature. Damn, I hate these "number of stairs = A" caches… :D 

What about a keyword to turn on the parsing explicitly? I heard of users who discovered this feature by pure luck, but it also reacts strange in some situations (like here).

Anyway I'd favor a per-cache solution (e.g. `NOWAYPOINTS` keyword in the note).

**Comment by rahu** [comment]
I would prefer the other way round. A "parse waypoints" button in personal notes section. Maybe next to clear waypoints.

Is there any reason why there is no solver?

**Comment by SammysHP** [comment]
A keyword has the advantage that the user can control the behavior of c:geo from the computer (where the user edits the note).

> Is there any reason why there is no solver?
Time and it's not easy – think about all the different kinds of formulas. It would require a complex and flexible parser and an interpreter.

**Comment by samueltardieu** [comment]
I also think a "parse waypoints from note" button would give the user more flexibility. The user is going to use cgeo anyway to find the cache, and having them in control of the waypoints parsing also lets them check that everything went fine. A keyword would need to be cgeo-specific; if every geocaching application did this, the user would have to include all the keywords in the description instead of pressing a button in the one application they are eventually using to find the cache.

**Comment by rahu** [comment]
for the solver: there are several expression parsers and solvers available. I'd like to evaluate some of them and maybe integrate one into cgeo. Is there a issue for this or should I create a new one?

**Comment by SammysHP** [comment]
#75 #1941 #2038 #2137 #3027 #3135

**Comment by UniQP** [comment]
Back to the original problem: What happens is that the parser sees `N 48° 53.(6*5*13)+194`, treats `N 48° 53` as latitude, skips the `.(` and then parses `6` as longitude. I think that we should only skip whitespaces, which is fine according to http://www.cgeo.org/faq.html#coords-format. On the other hand our tests contain coordinates like `N 49° 56.031 | E 8° 38.564` or `N51 21.523 / E07 02.680`, where latitude and longitude are also separated by non-whitespace characters.

Now my question is: What characters should we allow between latitude and longitude?

**Comment by LeXeRLV** [comment]
As a user I know many of people, who don't know about personal note
coordinates, which importing to waypoints. If the will need to add some
special character between both, they will never find out.

This is my opinion. An this is Your problem, if You want to add some
formalas to personal note - You should think, maaybe to add them in to
[N51....] [E07....]?

On 3 June 2016 at 20:30, Sebastian Buchwald <notifications@github.com>
wrote:

> Back to the original problem: What happens is that the parser sees N 48°
> 53.(6*5*13)+194, treats N 48° 53 as latitude, skips the .( and then
> parses 6 as longitude. I think that we should only skip whitespaces,
> which is fine according to http://www.cgeo.org/faq.html#coords-format. On
> the other hand our tests contain coordinates like N 49° 56.031 | E 8°
> 38.564 or N51 21.523 / E07 02.680, where latitude and longitude are also
> separated by non-whitespace characters.
>
> Now my question is: What characters should we allow between latitude and
> longitude?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cgeo/cgeo/issues/5338#issuecomment-223641967>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AIoMW6FDBqu1LazE_q2jWowjwzUrSMJpks5qIGSsgaJpZM4G7kTr>
> .
>



-- 
Ar cieņu,/С уважением,/Best regards,

Dmitrijs Līvmanis
GSM.: +371 26 54 45 54
E-mail: dmitry.livmanis@gmail.com

**Comment by Bananeweizen** [comment]
> then parses 6 as longitude

That is actually the bug. Parsing an integer number (without any additional character!) as latitude/longitude doesn't make sense.

**Comment by Lineflyer** [comment]
There have been some other users in the meantime having trouble with them.
E.g.:
```
S1: N 49 27.253 E 9 12.DEF
```

results into two waypoints:
```
S 01° 00,000 E 049° 27.253
N 49° 27,253 E 009° 12,000
```
(Untested)

Furthermore while discussing with the user I noticed that you can select (long press) to delete the created waypoints but nothing happens (is not deleted).
So the user has no possibility to surpress such wrong parsings; neither with an option to completely switch if off nor by deleting them after autocreate.

**Comment by pstorch** [comment]
Saw this behavior recently, too. Not to the same extend, but I could reproduce the above steps.
After correcting the coords in the personal note and replacing `DEF` with numbers, you get a third (correct) waypoint and then it is possible to delete the one with `N 49° 27,253 E 009° 12,000`.
A first guess why the coords reappear after deletion is that we refresh the view and this causes the personal note to be parsed again.

At the moment I'm in favor of an extra button to extract coords from personal notes.

And we should check why we have false positives.

**Comment by Lineflyer** [comment]
@UniQP 
I do see, that you declared your PR as fix for this issue. 
Just for my understanding:
We did not implement switching off the parsing from personal note, but improved it to avoid wrong parsed coords. Correct?

**Comment by UniQP** [comment]
@Lineflyer Exactly.
