### ISSUE TITLE
Upload of Personal Note fails, but says it did

### ISSUE THREAD

**Issue by Cotta-R** [cgeo/cgeo#5339]
If one tries to upload a personal note, despite not connected to the internet, one still get a success message "Personal note uploaded".

reproducable: always
occurs since: quite a while ago
Device/Android: HTC One m7, Android 5.1 (Google Play Edition)

**Comment by rsudev** [comment]
Could not reproduce using current master.
Could you post your system info (c:geo - about - system) ?

**Comment by Cotta-R** [comment]
--- System information ---
Device: HTC One (m7_google, htc)
Android version: 5.1
Android build: LMY47O.H11 release-keys
Cgeo version: 2015.12.06-NB-d90449f
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins:  none
--- End of system information ---

**Comment by Cotta-R** [comment]
I've captured a screenshot. Please note, Wifi off, Airplane Mode, not connected to PC or anything else:
https://www.dropbox.com/s/cn1vh04e236yxy9/Screenshot_2015-12-27-18-11-54.png?dl=0

**Comment by rsudev** [comment]
That was the detail I overlooked when reading your entry - no connection.
I can confirm this behaviour...

**Comment by rsudev** [comment]
It has to be noted, that this affects besides geocaching.com also OKAPI (at least oc.de)

**Comment by pstorch** [comment]
In CacheDetailActivity line 1556: the return value of con.uploadPersonalNote(cache); ist not evaluated. 
I can fix it, if no one else is already at it.

**Comment by SammysHP** [comment]
Sure, just do it. :)
