### ISSUE TITLE
Maps.me no marker

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5340]
For me when opening a cache in maps.me it shows the right area, but no marker. And it seems to be in a search mode somehow. Not sure if we changed something or maps.me did...

**Comment by dcj99b** [comment]
Yes, a serious problem.
Maps.me loaded an update 3 days ago. Version 5.4 Google.
On  two different Android phones, the same problem, no pink dot markers.

**Comment by Lineflyer** [comment]
@dcj99b 
You mean it started with the new maps.me version?

**Comment by pjnsoares** [comment]
Hello,

The same to me, when i choose navigate in cgeo with maps.me it opens correctly the aplication, but no dots to chose and navigate, i only checked the problem yesterday on my Samsung Galaxy Note3

Best Regards

**Comment by Lineflyer** [comment]
Attached a mail sniplet which I received today on support by a user affected by this problem, who contacted the maps.me team:

---

Hello!

Thank you for the report! 

We’re not sure what exactly cause the issue and we’ll investigate it. Hope we could find a reason of the behaviour and fix it in one of our future updates. You can also install previous version (5.2.1) of MAPS.ME via direct link – http://maps.me/apk/.

Best regards,

XXX
MAPS.ME team

---

So seems it is a bug in their current version.

**Comment by therramats** [comment]
We are two users having the same problem: NO PINK DOTS on the maps.me map. C:Geo version 2015.11.29. Maps.me version 5.4.1-Google. Serious problem! ONe HTC One, One Sony phone.
PLEASE fix asap (or ask maps.me to fix)

**Comment by rsudev** [comment]
@therramats You have read Lineflyers entry just above yours?

**Comment by therramats** [comment]
Thanks!





On Mon, Jan 4, 2016 at 6:17 AM -0800, "rsudev" <notifications@github.com> wrote:





@therramats You have read Lineflyers entry just above yours?

---

**Comment by pjnsoares** [comment]
Hi all,
I've just downgraded MAPS.ME to version (5.2.1) as advised by the MAPS.ME team it's working fine now.
Will wait for the fix to this issue to upgrade.
BR

**Comment by therramats** [comment]
Downgrade Worlds för me tio. Thanks!





On Mon, Jan 4, 2016 at 6:58 AM -0800, "pjnsoares" <notifications@github.com> wrote:





Hi all,
I've just downgraded MAPS.ME to version (5.2.1) as advised by the MAPS.ME team it's working fine now.
Will wait for the fix to this issue to upgrade.
BR

---

**Comment by Lineflyer** [comment]
This was just reported to be solved with the latest update of maps.me as of January 10th, 2016.
