### ISSUE TITLE
Map broken

### ISSUE THREAD

**Issue by rahu** [cgeo/cgeo#5342]
Yesterday I was caching in cz. I used the offline map from mapsforge download page and stored caches. 
After a short time map was broken. Only a small amount was updated when adjusting zoom level. The other visible area remains in it's old drawing or a gray rectangle was visible.

I made two screenshots:

![screenshot_2015-12-28-11-24-19](https://cloud.githubusercontent.com/assets/937126/12031706/a1b52f66-ae0f-11e5-83c1-54ea453bfdbc.png)
![screenshot_2015-12-28-11-23-35](https://cloud.githubusercontent.com/assets/937126/12031707/a1d9a9a4-ae0f-11e5-850e-abf6e8c747fa.png)

2012.12.06-NB-d90449f

I don't know what causes the issue and I can not reproduce this @ home. :(

**Comment by SammysHP** [comment]
Was the map opened for a long time? I noticed this behavior often after using it for a while. This is a bug in the old version of Mapsforge and should be fixed when we use the latest version.

**Comment by rahu** [comment]
I moved into cache detail view and back to map again and again. After 30minutes glitches occured and remained until we went back home.

**Comment by SammysHP** [comment]
Yep, that's the known bug. I think we should move to the new version of Mapsforge first.
