### ISSUE TITLE
Nightly builds are not updated.

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#5344]
I have not got any updated nightly build since dec 6.
The download link on http://www.cgeo.org/development.html also points to version 2015.12.06-NB-d90449f.

I read on facebook that you were changing the build environment, but that should be done by now?

What is the current status for the nightly builds?
I cannot find any info on github, facebook or on the official page.

**Comment by SammysHP** [comment]
Current status is: broken. Details are on IRC (see http://irclogs.cgeo.org/).

**Comment by Lineflyer** [comment]
@rsudev and @Bananeweizen are working on this. Currently we are still in the middle of a rework but are aware of this problem.

**Comment by MrYaz** [comment]
I got a message in the app about a new NB yesterday and downloaded it. 
Will the NBs be updated regularly from now on or was it a temporary one?

Unfortunately Google maps does not work in the 2015.12.31 version.

**Comment by Lineflyer** [comment]
Yes, a new NB has been established. I assume the missing google maps is a remaining issue. Will open a new issue here for that.

**Comment by Bananeweizen** [comment]
I've reopened the issue, as the Jenkins job really was disabled and I'm not sure if it is working right now. We need to have another job for the new nightly.

**Comment by Bananeweizen** [comment]
Sorry, did not notice the new job. Leaving closed.

**Comment by rsudev** [comment]
I think we should keep it open (unless we have another one), as some stuff is still missing
- nojit
- plugins
- FDROID notification

@Bananeweizen I'd appreciate if you look over the changes to the gradle build file I did in order to enable the nightly

**Comment by MrYaz** [comment]
I have not got any updated nightlies since 2015.12.31
It still does not seem to work as it should.

**Comment by rsudev** [comment]
For some reason unknown to me the timer based trigger did not pull. Jenkins now lists the next nightly due this night, we'll see.
Regardless were there no changes, so functionality-wise nothing lost.
The Google maps glitch is still under investigation.

**Comment by MrYaz** [comment]
Still no new nightly built...

**Comment by Lineflyer** [comment]
Strange. The scheduled job is still there and now scheduled for tonight...but it did not execute.
I just manually triggered a NB. Lets see what happens.

**Comment by Lineflyer** [comment]
@rsudev If you take a look at the history of the other scheduled job "Website tests" you will see that this is also not running since 26.12.2015.
Seems to be some general problem rather than a a problem with the nightly job.

**Comment by Lineflyer** [comment]
@mucek4 Can you please restart this Jenkins machine?

**Comment by mucek4** [comment]
Restarted.

**Comment by Lineflyer** [comment]
This seems to have solved the concrete problem. Lets see if it keeps working.

**Comment by Lineflyer** [comment]
Moving remaining items to a new issue
