### ISSUE TITLE
In-app "Send message" (mail to owner)

### ISSUE THREAD

**Issue by Pr0gy** [cgeo/cgeo#5346]
When tapping on the owner name in the cache listing view, you can already call by context menu the Groundspeak web site to send a private message to the cache owner.
While running with bad internet connection throw the forest and not liking to load a web page first, it would be nice to be able to type in the message content directly in the c:geo app and the app will automatically send it via Groundspeak to the owner.
Also nice then, if the app will show a prefilled edit box with {cache owner name}, {cache name}, {GC code} and {my nick name} in the following format:
Hello {cache owner name},
“{cache name}” ({GC code}).
Regards,
{my nick name}
So you can directly post your concerns, without coping or typing boring standard content.

**Comment by SammysHP** [comment]
See also #1593 and #4917.

> While running with bad internet connection throw the forest and not liking to load a web page first

But this is exactly what c:geo does: It loads the webpage and simulates a user. A browser with server-side compression (like Opera Mini) should be a lot faster than sending a mail via c:geo.

IMHO "send message to user" is not a feature of a geocaching field app, i.e. the current solution is fine and does not add complex code (we have already too much of it).

But like #4917 it is a possible feature for another app as addition to the message center.

**Comment by Pr0gy** [comment]
I give you right, the app loads the page in browser, so I save the time to pick out the user on geocaching.com, which is already nice!
What I would say is, if I have a slow (=bad) internet connection (GPRS or Edge) it takes a long time to load the page in browser, which would be not needed if the app provides a message box and send the message in background. Especially if there is a communication problem and I have to reload the page and enter the text again.
Most of time I use the mail option in the field, when I could not find a cache box or there is a problem, e.g. broken cache box, and I like to reach the owner or other cachers soon.
Of course it makes the application more complicate and - also as a software developer - I don’t know how complicate this would be to add. For logging of found, DNFs, will attends, this seems possible ;-).
And I like to have this feature also in the log book view, to contacting the cachers, who posted already a log, DNF, write note, … 
At least I have to try “Opera Mini” - I use currently “Firefox” and the build-in android “Browser”.

**Comment by Lineflyer** [comment]
Superseeded by the idea in #5352 (so if one of these two should get implemented it is more likely to use the messaging system which has been deployed by gc.com since this issue was created)
