### ISSUE TITLE
Global text operation?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5347]
https://medium.com/google-developers/custom-text-selection-actions-with-action-process-text-191f792d2999?linkId=20000019#.2e9okahhl shows how to add an item to every text selection menu. Does anyone see a truly useful application for this in our app? While the technical possibility seems nice, I don't really see a useful integration use case right now.

**Comment by rsudev** [comment]
I can think of useful scenarios to get coordinates or snippets from looking up information into the personal note or the waypoint description, but it is likely not the feature I am missing most :)

**Comment by Bananeweizen** [comment]
Ah, you mean by declaring exported=false and restricting the functionality to our own app. That sounds very useful indeed. Thanks for making me aware.

**Comment by Lineflyer** [comment]
Isn't that into the same direction to what is currently discussed in #5351

**Comment by Bananeweizen** [comment]
No. This is about adding new menu items to the text selection menu itself, not about the way how the text is selected. And this is possible inter-app wide.

**Comment by moving-bits** [comment]
Let's close this rather old issue, as it looks like no use cases have come up for it.
