### ISSUE TITLE
Idea: Change waypoint storage

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5353]
In order to untangle the current mess with changed waypoint descriptions and such, I would suggest to separate the waypoint description as loaded from the source (website, OKAPI, gpx) from the user additions. Than we can clearly detect website changes and update the local waypoint accordingly without endangering user-entered data.
As a migration path I would suggest to treat the current description as user supplied and remove if it is identical to the website description on next update.
Comments?

**Comment by Lineflyer** [comment]
You are refering to our internal database but not to the UI, are you?

**Comment by rsudev** [comment]
I am referring to both. The fixed description would be just a textfield, user-notes would be an editable text underneath.

**Comment by pstorch** [comment]
While reading #5636 again, I thought about the same: separating user defined texts from original ones.
So, a +1 from my side.
