### ISSUE TITLE
Use Crowdin branch management support

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5355]
That would let us clean up strings in the `release` branch or modify them in the `master` branch much more easily.

See https://support.crowdin.com/articles/versions-management/

**Comment by rsudev** [comment]
I took a quick look - sounds promising +1

**Comment by rsudev** [comment]
Started experimenting...

**Comment by rsudev** [comment]
Current state of things:
- I created a release branch on crowdin
- I reworked the scripts (locally) to upload to release from a release branch and to root from master
- I reworked the scripts to download from release branch on release and from root on master

There are some caveats I came across.
- as free users, we can only 'build' every half an hour
- regardless of the branch I address for download, the package from the last build is returned
- the package from root contains also the files from release

I would try if these issues could be handled better, if I move the translations from root to a new branch 'master'. This likely would mean that there are some days where the scripts are not working at all.

Any objections to that from anybody ( @samueltardieu @Bananeweizen @Lineflyer )?

**Comment by samueltardieu** [comment]
I trust you in your judgment on this issue.

**Comment by Lineflyer** [comment]
I have some questions related to that:
- Will this require double effort for the users as they need to translate strings in both branches if we use them in both?
- What about the translation for the plugins, they should also be contained in the branches, or not?
- Will we loose any existing translations?

And another side note:
When doing manual uploads there should be a selection if contributors shall be informed by mail about new strings uploaded (so they can start translation). If this can be triggered by your scripts as well, that would be good.

**Comment by rsudev** [comment]
No, the advantage of the branch management is (in principle) that we can have two sets of strings, and the users have only to translate the union.
This gives us the possibility to omit old strings from master (while keeping them on release) and also to not pollute release with new or changed strings from master.
Will will not loose existing translations by that.
Regarding the notification, I think when we talked about this last time, it was not possible. But in the course of these changes, I can re-check with the latest API documentation.

**Comment by rsudev** [comment]
@Lineflyer I re-checked the API docs. Translator notification through the API while updating is not possible.
