### ISSUE TITLE
Remove GC-only menu items when GC not enabled

### ISSUE THREAD

**Issue by Natureshadow** [cgeo/cgeo#5356]
I disabled the GC.com service (because they banned me for linking to an OC listing in a log), but I still do have the Pocket Queries menu entry.

Strange enough, it also successfully loads pocket queries ... (whut?)

Menu items that make only sense for the commercial locked-in service from overseas should be hidden if only open services are enabled.

**Comment by Lineflyer** [comment]
Yes, we have AFAIR some other issue dealing with the "problem" that c:geo was initially a single connector app for geocaching.com and afterwards got other connectors without consequently dealing with the fact, that people might use it without geocaching.com.

Those program parts you mention have not been adapted to this multi platform support...thats the reason that in many places geocaching.com is accessed even without credentials or while disabled.

**Comment by Lineflyer** [comment]
Link to #3509 #3097 #3779
