### ISSUE TITLE
CI server configuration

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5360]
Taken from #5344:

ToDo on the CI:
- [x] nojit
- [ ] plugins
- [x] FDROID notification

**Comment by kumy** [comment]
I've updated the `Publish FDroid - NIGHTLY` job. This job is now triggered after a successful build of `cgeo nightly`.

I left the other job `Publish FDroid - RELEASE` as is. As we decided some month ago to trigger  this one manually. That was added to the [wiki](https://github.com/cgeo/cgeo/wiki/Prepare-a-release#trigger-publish-to-f-droid-repository) on Sep 2015.

**Comment by Lineflyer** [comment]
@kumy Sorry..I am not up to date with FDROID. Can the item in the list be considered as done then?

**Comment by kumy** [comment]
@Lineflyer I think yes. I'll check the last item.

**Comment by mucek4** [comment]
CI is still 32bit machine. I'll try to do something about it.

**Comment by rsudev** [comment]
nojit meanwhile added by @Bananeweizen

**Comment by SammysHP** [comment]
Link to #5187.

**Comment by Lineflyer** [comment]
The CI server functionality is IMHO complete in the meantime looking at the above mentioned items.
