### ISSUE TITLE
automatically kill gradle deamon

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5362]
Take over (and adapt) the code from https://github.com/eclipse/buildship/blob/master/build.gradle#L290. That kills the deamon from inside the build, so we don't need to add this to every job on Jenkins (more fault tolerant)

**Comment by samueltardieu** [comment]
What do you mean? Why not start gradle with `gradle --no-daemon` in scripts, or use a gradle settings file?

**Comment by Bananeweizen** [comment]
>  Why not start gradle with gradle --no-daemon

Because at least I will tend to forget that when creating new jobs. So I'd like to do it once, and have it the right way for all new jobs. If this can also be done with a settings file on the server, then that's fine. Will you create it? :)
