### ISSUE TITLE
Allow new users to register an account on opencaching platforms directly from the app

### ISSUE THREAD

**Issue by ebillen** [cgeo/cgeo#5364]
New users, who do not yet have an account on one of the various geocaching platforms should be able to register directly on one of the opencaching platforms (or maybe all opencaching-platforms in parallel) from the c:geo app.
I'm member of the german opencaching.de team and could act as contact person for the communication - there will also be some developing effort on the side of the opencaching-platforms to realize this.

**Comment by SammysHP** [comment]
So does the OKAPI support account registration? In that case it should be possible. If not, I suggest to add another link to the registration webpage (currently there's only a "Open website" link).

**Comment by Bananeweizen** [comment]
@SammysHP That's exactly what I've started locally already. I also believe just *pointing* to the existing registration forms is a solution that is sufficient for the typical geocaching beginner (and is also way more cheap in the implementation).

**Comment by Bananeweizen** [comment]
Not sure if we can do much more than the implemented link to the account creation for now. I tend to close the issue...

**Comment by Lineflyer** [comment]
@ebillen might be capable to implement such a function into OKAPI or alike. Maybe he can give more background info regarding his request.

**Comment by Lineflyer** [comment]
Otherwise I would also tend to think that providing a link to the registration page is a good solution with less effort.

**Comment by ebillen** [comment]
Thanks for your comments.
I opened this feature request to see wether there is a general interest in providing such a registration functionality. OKAPI support for that is a prerequisite, I'll open an issue there too and come back here when (if) OKAPI has implemented that.
In the meantime, providing a link to the registration page is a good solution.

**Comment by ebillen** [comment]
Hi, the OKAPI (apisrv/installation) now returns the URL to the registration page - so c:geo can now ask the site for it's current registration URL and point the user to that.

**Comment by Lineflyer** [comment]
@Bananeweizen  AFAIR you implemented the link to the caching page for registration in settings. Do we use that function of the OKAPI to retrieve the target URL already?

**Comment by Lineflyer** [comment]
This feature seems to be implemented:
- Activate an OC connector
- Select "Authorize c:geo"
- Select "Creater user account"
