### ISSUE TITLE
Subtitles not shown

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#5365]
OC has subtitles which are per-language and separate.

I just imported http://opencaching.de/OC1299A and the subtitle “An der Löwenburg” is not visible anywhere in c:geo (NB from a few nights ago).

**Comment by Bananeweizen** [comment]
this has been fixed in #3339 just today, so please wait for another nightly build

**Comment by mirabilos** [comment]
Ah… I searched for subtitle and short description in the existing bugs, but these keywords only occurred in duplicates you already closed, so no wonder I didn’t find anything.

Thanks!
