### ISSUE TITLE
Graphic problems Nexus 5 / Android 6.0.1

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5372]
Some menus have graphical problems (reported by a user).

```
--- System information ---
Device: Nexus 5 (hammerhead, google)
Android version: 6.0.1
Android build: cm_hammerhead-userdebug 6.0.1 MMB29T 2a23616bec test-keys
Cgeo version: 2016.01.11-NB1-f1ec8b2
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Basic
- opencaching.de: logged in (Login OK)
Installed cgeo plugins: none
--- End of system information ---
```

![glitches](https://cloud.githubusercontent.com/assets/949669/12245859/6d92f5dc-b8ab-11e5-84fd-e3f410b0bd82.png)
![glitches2](https://cloud.githubusercontent.com/assets/949669/12245860/6da7f702-b8ab-11e5-9a28-e95931c6ed9a.png)

**Comment by martykan** [comment]
Happens on every Marshmallow device.

**Comment by rsudev** [comment]
On the emulator I could only see the first glitch - likely a bug either in our themes/styles or in AppCompat

**Comment by akkatracker** [comment]
Was this 100% fixed in https://github.com/cgeo/cgeo/issues/5371 ? 

If so @Lineflyer you may want to close this.

**Comment by Lineflyer** [comment]
I can not reproduce it on Marshmallow devices, also the user who raised this via support mail did not report back later on.
Therefore lets close this for now.
