### ISSUE TITLE
Put more information in the cache-icons on the map

### ISSUE THREAD

**Issue by Cotta-R** [cgeo/cgeo#5373]
I'm thinking since some time, it would be nice to have more information within the cache-icons on the map.

Currently we have the type of the cache via the icon itself, the platform the cache is hosted on via the shape of the icon, the status of the cache being active or disabled/archived via the background color and with some overlay-icons there is further information about the status: Found, corrected coords, stored on device and having a personal note all have a small additional icon. Further there is a orange ring around the icon on the live map, when coords are not exact.

In my opinion, it would be helpful to have some more information displayed without the need to check each cache.

With the help of different shades of grey could be displayed, if a cache was still found after being archived or disabled (lighter grey) or not found (darker grey), and maybe it would be even helpful for active caches to display the icon after one or more DNF-logs a little grey than white.

Another information I would like to get is about the T-rating. Sometimes for T 4.5 and mostly always for T5 one extra equipment is necessary. So background color or color of the outer ring could went to red for example with T>=4.5 maybe. This would be very helpful when planning a trip.

**Comment by SammysHP** [comment]
IMHO the icons already have too much information (lots of small icons around the marker). I really don't know what we can do to show even more information without making it too difficult to understand.

> different shades of grey

Not visible in many situations (sunlight, low display brightness, some types of display).

> So background color or color of the outer ring could went to red

Color mappings are mostly not intuitive.

**Comment by Lineflyer** [comment]
There a quite a bunch of issue discussing this.
At the end most of them cam to the conclusion, that all of these might be useable for "experts" but too much not intuitive info  for the major percentage of users.
AFAIR only the option of having a marker for caches of a certain list has remained open as useful.

**Comment by Cotta-R** [comment]
I think displays even in low end devices nowadays are good enough to make at least a few different shades of grey distinguishable. And if someone under some circumstances cannot decide, which grey is displayed, he doesn't lose anything. He still sees grey and knows: disabled/archived (if we skip the idea of having a light grey for active, but with recent DNF-logs). All others can see, these caches are maybe good to go (lighter grey) and some others are maybe not (darker grey). Especially in Czech Republic as far as I know they go quite often for archived caches, example GCZ2M8.
And about color-mappings, red always stays for "Attention", also international. And this would be the case for higher T-rating.
I forgot, what about a blue ring for caches with a good favorite points percentage? As blue is the color of the ribbon, this should be meaningful as well.
The idea of having a marker for caches in a certain list could be somewhat a workaround to flag caches with high T-rating, if one puts all of these in that list (I personally sort caches in lists by area at the moment). But it would involve more management done by the user with filtering and moving caches to that list always after storing new caches.
Anyway, just think about it or discard it, I just wanted to give some ideas.

**Comment by Lineflyer** [comment]
> And about color-mappings, red always stays for "Attention", also international. And this would be the case for higher T-rating.

This is a good example of why this won't be intuitive for all users. Some would think it says the cache needs maintenance, other think it means many favorite points, T5-cachers won't understand why those are marked different at all.
This would IMHO lead to a less intuitive UI and is therefore not meaningful.

All I could imagine is usage of meaningful icons, but -again- space is limited.

**Comment by Cotta-R** [comment]
I think everybody could find out at a glance whats the meaning of the markup. I mean, I found out what's the meaning of grey caches, on my own ;-).

**Comment by sdennler** [comment]
I think it would be useful and easy to understand to be able to put a bookmark star on the icon. That way its possible to mark on the map which caches are really interesting/planned to do while still see all the caches which can be picked up on the way if there is time.
The marking could be done by putting the cache in a special "Bookmark" list.

**Comment by moving-bits** [comment]
Implemented (in a slightly different way) with #7761, therefore closing this one.
