### ISSUE TITLE
Delete all images/pictures/photos from caches in a specific folder

### ISSUE THREAD

**Issue by Cotta-R** [cgeo/cgeo#5374]
The caches I have stored at the device are organised in folders. For some specific folders I still want to keep the caches on the device, but as I'm running slowly out of memory (who thought, 640 kB won't be enough for some time :-P), I would like to delete all pictures from caches in any specific folder.

It's maybe a quite strange request, but maybe somebody else would support this request ;-).

**Comment by SammysHP** [comment]
You can delete them manually with a file manager, but next time you open the cache they'll be downloaded again.

**Comment by Lineflyer** [comment]
More precise: 
Log pictures will only de reloaded and stored if you update the cache but else I agree to the suggestion of @SammysHP.

More over you can optimize storage consumption by turning off not required options in c:geo Menu - Settings - Offline-Data.
