### ISSUE TITLE
restrict cache type to "traditional" for new installations

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5376]
I've been able to watch 2 people using our app, which had no clue of geocaching at all ("let's just download and try this, it must be good if Michael was involved"). Of course, they all tried to search for the nearest cache, which in both cases was a mystery or other "more complicated" cache.

I therefore suggest to restrict the cache type to "traditional" in the default settings for new installations. I'm quite confident that "veteran" geocachers will figure out that restriction and remove it on their own.

Comments?

**Comment by rsudev** [comment]
I see your point, there are likely quite a number of people coming across our app with only little to no knowledge about geocaching.
As they in this case likely also have no registration at any geocaching site, we might want to direct them there (IMO without giving gc.com an undue preference).
I would also suggest to think of ways to make the current filter status (and how to change it) more visible, e.g. by super-imposing the currently selected cache type on the filter button on the main screen.

**Comment by Lineflyer** [comment]
I would more tend to provide a good introduction and guidance on first startip (as discussed in another issue) rather than filtering something.
Additionally we could link to our FAQ where at least some basic things are explained: http://www.cgeo.org/faq.html#newbie

**Comment by Lineflyer** [comment]
I think we should more go into a direction of a good introduction or reference on first startup.
