### ISSUE TITLE
Do not simply hide the "Refresh all" option on the "All caches" list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5377]
...but make it depending on the sum of caches on that list.
Quite often user complain that they are unable to refresh all saved caches. Reason is always, that this menu item is hidden on the all caches list indepently of the number of caches on that list.

This "feature" was initially introduced to avoid unnecessary refresh of a large amount of caches.
However I have seen many cases where users have something like e.g. 6 lists with 5 caches each and would like to refresh all 30 on the all caches list which wont work but require to seperately refresh each list.

I instead suggest to use a hardcoded limit for the amount of caches on the "All caches" list where the "refresh all" option is hidden. My suggestion would be >500 caches and not to simply hide the option but display a info toast when it is selected. On other lists there should stay no restriction.

Another option would be to allow it on all lists but only present a warning if the amount of caches is >500.

Opinions?

**Comment by SammysHP** [comment]
> This "feature" was initially introduced to avoid unnecessary refresh of a large amount of caches.

Are you sure? I remember that they were all put on the wrong list. Some people have lists with > 1000 caches. I don't see any sense in such a limit.

**Comment by Lineflyer** [comment]
Yes...knowing that it is no "perfect" solution. But the thought behind that was just, that a common use case is to have seperate lists per location and it might be sufficient that users refresh only one list at a time.

But you are perfectly right, that it is not meaningful.
So how about removing the restriction generally but generally implement a warning dialog if the amount of caches refreshed is high?

**Comment by SammysHP** [comment]
Sounds good.

**Comment by Lineflyer** [comment]
Who can implement that? Shouldn't be a big deal, just remove the general hiding and place a dialog "This action may lead to high network traffic. Are you sure you want to batch refresh all caches?" Yes/No.

**Comment by pstorch** [comment]
Maybe it's another small task for me.

**Comment by Lineflyer** [comment]
Sure. Go ahead. Setting myself as stand-in for assignment.
