### ISSUE TITLE
Add "Hide disabled caches" to map menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5378]
From support mail:

Additionally to the "Hide found/owned caches" the option "Hide disabled caches" should be available also from the map menu.
See mock up screenshot:
![current_map_options](https://cloud.githubusercontent.com/assets/949669/12276103/28b5e586-b974-11e5-9541-26358288c0d6.jpg)

**Comment by rsudev** [comment]
There are some issues with that feature. First of all (AFAICS) there is no possibility to exclude those on the server side (unlike own/found for PM).
Currently we also do not detect them (so you only get the info of you have a 'detailed' strategy or look at the popup). This makes the information somewhat volatile and the result therefore unreliable.
What do you think about these technical boundary conditions?

**Comment by SammysHP** [comment]
The option is already present in the preferences.
