### ISSUE TITLE
Prepare for site change - Markdown for logs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5379]
As posted on IRC:
http://forums.groundspeak.com/GC/index.php?showtopic=336750

Possible effects:
- Logbook reading might need to be adapted
- Posting logs might need to be adapted
- Smilies no longer supported in the current mode
- others?

**Comment by Lineflyer** [comment]
Addition: Smilies will be kept supported as they are (according to the posting linked above).

**Comment by Lineflyer** [comment]
Side note (offtopic): I will not be available to test anything around Feb 2nd (until Feb 8th)

**Comment by Bananeweizen** [comment]
I'd prefer us to release from master before that date. Otherwise we have to make the log changes from release branch without CI.

**Comment by rsudev** [comment]
Right now the log changes arrived for me. A short cross-check showed, that log posting still seems to work.

**Comment by Bananeweizen** [comment]
For me everything seems to work fine with my last change. Just committed a log, and read multiple caches and trackables.

**Comment by rsudev** [comment]
I still have an emulator image with Android 2.3. I'd like to try to run the tests and the current version on it, as a safeguard.

**Comment by rsudev** [comment]
My tests on the 2.3 emulator also did not show any roadblocks, so we can go for a staged release, as usual.

**Comment by rsudev** [comment]
Staged release of version 2016.02.03 started...

**Comment by Bananeweizen** [comment]
Set to 100 percent by now.

**Comment by kumy** [comment]
Fdroid release job launched.
