### ISSUE TITLE
opencaching.org.uk: cache download fails

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5383]
Due to the addition of short_description does the cache download from oc.uk fail, as the site is sitting on a very old okapi version.

**Comment by Bananeweizen** [comment]
Where can that be seen? There is no version information in the OKAPI documentation, or did I miss it? I want to avoid similar errors the next time.

**Comment by rsudev** [comment]
The documentation itself is tied to the version the respective site has deployed. So on opencaching.de/okapi you can see ```ver. 1133 (54ad2cf)``` in the upper left and the cache field list names the short_description.
On opencaching.org.uk/okapi you see ```rev. 515``` and no mentioning of the short_description field.
So in essence you have to check all sites you want to call WRT their ApiSupport level.
In our code we currently have only two levels (current and oldapi) as luckily most of the sites nowadays update regularly with only oc.uk staying behind.
