### ISSUE TITLE
Reneable watchdog tests for failing sites

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5385]
Due to the current (and more permanent) offline status of these sites the watchdog tests for these connectors have been disabled in b9c96fc
Once the servers (or rather redirections to oc.de) are up-and-running again, these tests should be re-enabled as well.
Likely will the operating status of the sites be announced in the oc.de forum in http://forum.opencaching.de/index.php?topic=4421
Failing sites:
- [x] oc.it
- [ ] oc.es
- [x] oc.nl
- [x] gk.org

**Comment by rsudev** [comment]
Watchdog test for oc.it re-enabled, as the site is online again.

**Comment by rsudev** [comment]
opencaching.nl became unavailable today. Re-enable the tests when it is online again.

**Comment by rsudev** [comment]
geokrety.org is down since yesterday afternoon...

**Comment by rsudev** [comment]
Re-enabled oc.nl, disabled geokrety.org

**Comment by rsudev** [comment]
Re-enabled geokrety.org

**Comment by kumy** [comment]
Shouldn't we also monitor `api.geokretymap.org`?

**Comment by Bananeweizen** [comment]
If you have an idea for how to test it, sure, go ahead. Good idea. We might actually want to include gcvote, too.

**Comment by rsudev** [comment]
oc.es is avilable again, so we could re-enable the test. OTOH we do not use the site at all as far as I can see, so we even might ditch the test altogether...

**Comment by Bananeweizen** [comment]
Well, the app might open the URL of an OC.ES cache using the browser, so being able to know whether this is possible or not still seems useful to me. I'm aware that we are not doing any data fetching or similar from the site.
