### ISSUE TITLE
Switch to english not working 

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5386]
There are multiple reports on our facebook page where people can login, but their cache counter remains at zero and the live map only shows question mark caches. A local friend of mine says this is since 3 days (Thursday 2016-01-14)  for him.

I can't reproduce the issue myself. Did anyone notice similar strange behaviour or a website change related to that date?

**Comment by rsudev** [comment]
I recall seeing this yesterday (but was looking for something else, so I didn't pursue it further). I assume it has to do with the website language not being in English and we fail to detect/switch it.

**Comment by kalvdans** [comment]
I also experienced it yesterday. c:geo couldn't login because of an "unknown error" and when I tried to log in on the website using a web browser I was challenged with a captcha.

Later in the evening c:geo could login as usual and I could login on the site without captcha.

**Comment by Lineflyer** [comment]
It could be, that they switched some users to a new version of the website as a test of the upcoming changes.
They did similar some months ago.






Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: kalvdans <notifications@github.com> 
Datum:17.01.2016  10:38  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Betreff: Re: [cgeo] Login not working correctly? (#5386) 

I also experienced it yesterday. c:geo couldn't login because of an "unknown error" and when I tried to log in on the website using a web browser I was challenged with a captcha.

Later in the evening c:geo could login as usual and I could login on the site without captcha.

**Comment by notspecified** [comment]
Im one of those wo has this issuses since 2 days! Beside the thing that the cache count remains at 0, all new loaded caches didn't have the description of the cachesize anymore.

My solution for this problems: change the language on the geocaching homepage from German to English.
Now I have my cachecount an the cachesize! :-)

**Comment by Lineflyer** [comment]
so maybe it is as easy as that our switch to english is really broken. Let me check if I can find something.

**Comment by Lineflyer** [comment]
Confirmed with 2016.01.16-NB (will probably be the same as in current market version):
- Switch to english failing which causes login problems as well as some followup problems (missing cache details, unable to post log, cannot determine membership status)

``` 
12:41:45.708 Debug cgeo 12284  [network-2] 200 (1548 ms) GET https://www.geocaching.com/login/default.aspx
12:41:45.708 Info cgeo 12284  [network-2] Already logged in Geocaching.com as Lineflyer (Premium)
12:41:45.708 Debug cgeo 12284  [network-2] GET https://www.geocaching.com/my/souvenirs.aspx
12:41:46.924 Debug cgeo 12284  [network-2] 200 (1220 ms) GET https://www.geocaching.com/my/souvenirs.aspx
12:41:49.561 Debug cgeo 12284  [network-2] POST https://www.geocaching.com/my/souvenirs.aspx
12:41:52.182 Debug cgeo 12284  [network-2] 200 (2627 ms) POST https://www.geocaching.com/my/souvenirs.aspx
12:41:52.182 Info cgeo 12284  [network-2] changed language on geocaching.com to English
12:41:52.182 Debug cgeo 12284  [network-2] GET https://www.geocaching.com/login/default.aspx
12:41:53.383 Debug cgeo 12284  [network-2] 200 (1265 ms) GET https://www.geocaching.com/login/default.aspx
12:41:53.601 Info cgeo 12284  [network-2] Already logged in Geocaching.com as Lineflyer (Premium)
12:41:53.601 Debug cgeo 12284  [network-2] GET https://www.geocaching.com/my/souvenirs.aspx
12:41:55.021 Debug cgeo 12284  [network-2] 200 (1424 ms) GET https://www.geocaching.com/my/souvenirs.aspx
12:42:01.354 Debug cgeo 12284  [network-2] POST https://www.geocaching.com/my/souvenirs.aspx
12:42:03.211 Debug cgeo 12284  [network-2] 200 (1793 ms) POST https://www.geocaching.com/my/souvenirs.aspx
12:42:03.211 Info cgeo 12284  [network-2] changed language on geocaching.com to English
12:42:03.211 Debug cgeo 12284  [network-2] GET https://www.geocaching.com/account/settings/preferences
12:42:03.211 Debug cgeo 12284  [network-6] GET https://www.geocaching.com/account/settings/homelocation
12:42:03.211 Debug cgeo 12284  [network-7] GET https://www.geocaching.com/account/settings/membership
12:42:04.194 Debug cgeo 12284  [network-7] 200 (1012 ms) GET https://www.geocaching.com/account/settings/membership
12:42:04.194 Debug cgeo 12284  [network-6] 200 (1027 ms) GET https://www.geocaching.com/account/settings/homelocation
12:42:04.412 Debug cgeo 12284  [network-2] 200 (1241 ms) GET https://www.geocaching.com/account/settings/preferences
12:42:05.395 Warning cgeo 12284  [network-7] Cannot determine member status
```

Changed title and set labels accordingly.

**Comment by rsudev** [comment]
The target item to initiate the switch changed its id

**Comment by rsudev** [comment]
Put only to master, as I agree with Lineflyer on hsi remark in #5251

**Comment by Lineflyer** [comment]
Triggered a new NB

**Comment by Lineflyer** [comment]
Seems to work fine again with 2016.01.17-NB1.
