### ISSUE TITLE
Text missing in dialog

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5388]
2016.01.17-NB1:
- Enter c:geo Settings - Services - geocaching.com
- Deactive that connector
- Activate it again.

A window titled "geocaching.com" opens but contains no text, just the selectors "More" and "OK".
![screenshot_2016-01-17-18-21-21](https://cloud.githubusercontent.com/assets/949669/12378724/68699fe8-bd47-11e5-823f-3faa7c438eaf.png)

**Comment by Bananeweizen** [comment]
This should be the "you hereby confirm the usage conditions of groundspeak" dialog

**Comment by Lineflyer** [comment]
Strange...this is also the german version. Let me check that again.

**Comment by Lineflyer** [comment]
Nothing...not in german and also not when forced to english.

**Comment by Lineflyer** [comment]
Still happening to me with 2016.01.19

**Comment by Lineflyer** [comment]
Still happening with 2016.02.14-NB

**Comment by samueltardieu** [comment]
Confirmed on `master` on device (French, 6.0.1) and emulator (English, 6.0.1).

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by SammysHP** [comment]
See 8d72c5509edd03d0fb6f21e2758e2f053bb46195.

**Comment by Lineflyer** [comment]
Confirmed working with 2016.03.13-NB
