### ISSUE TITLE
OC.org.uk: Attribute icons wrong

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5389]
2016.01.17-NB1:
- Activate opencaching.org.uk and autorize
- Search for OK02A4
- On the cache details page the attribute icons are all a red "?!"
- If you click on the icons to see the textual version this looks OK

- Not reproducible on opencaching.de caches

Picture
![screenshot_2016-01-17-18-25-54](https://cloud.githubusercontent.com/assets/949669/12378741/1f4d11b8-bd48-11e5-9a2b-d3dd2787b0f1.png)

**Comment by Bananeweizen** [comment]
This has never worked there. Their OKAPI version does not return the standardized attribute names, which is why our mapping from attribute to image does not work.

As a workaround I suggest that we detect at runtime, if all icons are not mapped, and if so, we provide only the text view.
