### ISSUE TITLE
"Unknown error" shown as log type for TB instead of "Move to inventory"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5395]
version 2016.01.18 

- Open an owned TB via search for its tracking code from main menu action bar
- Start logging activity for this TB

For me there are two available log types "Bemerkung" (Note) and "Unbekannter Fehler" (Unknown Error).

Trying to send this log with type "Unbekannter Fehler" or "Note" both  lead to long time progress indicator until timeout with error toast "Login fehlgeschlagen".
(I cannot take a debug log at the moment)

For not owned TBs I could not find any problem up to now.
See screenshot:
![screenshot_2016-01-18-16-37-14](https://cloud.githubusercontent.com/assets/949669/12395476/2427fcba-be02-11e5-90bd-94453bb158f7.png)

**Comment by Lineflyer** [comment]
Note:
I will retest this, as it may be conincident with problems of site reachability I am currently experiencing.

**Comment by Lineflyer** [comment]
Update:
Interesting.
Once I reproduce this issue, I keep having communication problems towards the website afterwards until I reboot my device.
How can that?

```
16:54:11.209 Info cgeo 4552  [AsyncTask #4] Trying to post log for trackable #<removed> - action: UNKNOWN; date: 2016.1.18, log: Test
16:54:11.210 Debug cgeo 4552  [AsyncTask #4] POST https://www.geocaching.com/track/log.aspx?wid=06060e39-51bc-42c2-9a94-d8a801fc46ab
16:54:43.714 Info cgeo 4552  [AsyncTask #4] Trying to post log for trackable #<removed> - action: UNKNOWN; date: 2016.1.18, log: Test
16:54:43.714 Debug cgeo 4552  [AsyncTask #4] POST https://www.geocaching.com/track/log.aspx?wid=06060e39-51bc-42c2-9a94-d8a801fc46ab
16:54:44.540 Warning cgeo 4552  [AsyncTask #4] Failure (30913 ms) POST https://www.geocaching.com/track/log.aspx?wid=06060e39-51bc-42c2-9a94-d8a801fc46ab (java.net.SocketTimeoutException: Read timed out)
16:54:44.540 Error cgeo 4552  [AsyncTask #4] Login.checkLogin: No page given
16:54:44.540 Debug cgeo 4552  [AsyncTask #4] GET https://www.geocaching.com/login/default.aspx
16:55:13.221 Warning cgeo 4552  [AsyncTask #4] Failure (31037 ms) GET https://www.geocaching.com/login/default.aspx (java.net.SocketTimeoutException: Read timed out)
16:55:13.222 Error cgeo 4552  [AsyncTask #4] Login.login: Failed to retrieve login page (1st)
16:55:13.222 Info cgeo 4552  [AsyncTask #4] Working as guest.
16:55:13.222 Error cgeo 4552  [AsyncTask #4] Login.checkLogin: No page given
16:55:13.222 Error cgeo 4552  [AsyncTask #4] GCParser.postLogTrackable: Cannot log in geocaching
16:55:54.763 Debug cgeo 4552  [main] LocationProvider: requesting most precise locations

**Comment by Lineflyer** [comment]
Update 2:
The communication problem until reboot is no longer happening, but kind of reproducible is, that my session seems to be invalidated or blocked afterwards.

**Comment by Lineflyer** [comment]
As this problem seems to be limited to operations with owned TBs (which at least in my case are also in my collection and not in the inventory) I tend to postpone fixing this isssue (given that it can be verified at all) for a later bugfix release.

I just tested normal "everyday" TB operations like retrieving, grabbing and discovering which seem to work normal.

Meanwhile also @rsudev was able to reproduce for the owned TB in collection case.

**Comment by rsudev** [comment]
This was likely introduced as a side-effect of 9427ee493f546db2fb861f573367582b123f87d6 in March 2015. So it seems not really urgent :)
Seems to be not complicated to fix, but as I would need to research a little on gkid first, I'll come back to this later.

**Comment by kumy** [comment]
I've started looking at this issue, but I (still) cannot reproduce...

**Comment by kumy** [comment]
I cannot reproduce.
That said, if you get `Unknown error` as a `TrackableLogType` label, then the listbox in the GC Log Trackable page may have a entry with an id we doesn't recognize.
I would suggest to add a debug message so we can see what's behind.
Actual [known codes](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/enumerations/LogTypeTrackable.java#L14-L21) are 4, 5, 13, 14, 19, 48, 1001

May I commit such thing right now as we are in a release process?
```
$ git diff main/src/cgeo/geocaching/enumerations/LogTypeTrackable.java
diff --git a/main/src/cgeo/geocaching/enumerations/LogTypeTrackable.java b/main/src/cgeo/geocaching/enumerations/LogTypeTrackable.java
index 0085dc0..980faa4 100644
--- a/main/src/cgeo/geocaching/enumerations/LogTypeTrackable.java
+++ b/main/src/cgeo/geocaching/enumerations/LogTypeTrackable.java
@@ -6,6 +6,7 @@ import android.support.annotation.StringRes;
 import cgeo.geocaching.CgeoApplication;
 import cgeo.geocaching.R;
 
+import cgeo.geocaching.utils.Log;
 import org.eclipse.jdt.annotation.NonNull;
 import java.util.ArrayList;
 import java.util.List;
@@ -55,6 +56,7 @@ public enum LogTypeTrackable {
                 return logTypeTrackable;
             }
         }
+        Log.e("LogTypeTrackable.getById(): Failed to lookup id:" + id);
         return UNKNOWN;
     }
 

```

**Comment by rsudev** [comment]
The missing logtype is
```<option value="70">Move To Inventory</option>```
you get it, if you have a trackable in your collection

**Comment by kumy** [comment]
@rsudev thanks, didn't knew about the collectible feature ;)

**Comment by kumy** [comment]
Reopen for testing

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Confirmed working with 2016.01.19.

Thanks @kumy
