### ISSUE TITLE
Storing some caches from search result lead to a "refresh all" popup

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5396]
When using `store Offline` menu from `CacheListActivity`, a popup called `Refresh all` is shown. I'm not refreshing any caches, but storing new ones. This is a bit confusing.
The message is displayed even if I choose to store only one cache.
I think it's related to PR #5381.

```
Subject: Refresh all
Message: This action may lead to high network traffic. Are you sure you want to batch refresh all caches?
```

**Comment by Bananeweizen** [comment]
Same here. Just opened the nearest list and tried storing them.

**Comment by Lineflyer** [comment]
Yes, I overlooked that while testing. But at least it does not block the function...just a not matching warning.

**Comment by pstorch** [comment]
Sorry didn't know that the "refresh All" menu item is reused for "store offline".

**Comment by Lineflyer** [comment]
AFAIR this was solved but autoclose failed due to missing # in commit message.
