### ISSUE TITLE
Refresh all warning also for low amount of caches on list or selected caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5400]
With version 2016.01 19
I consider this as small issue to be fixed with the next bugfix release

**Comment by SammysHP** [comment]
IMHO the dialog should be shown whenever more than n caches are stored or refreshed.

**Comment by Lineflyer** [comment]
You are right, that was the initial idea and would solve this case.
I suggest n=100 or 200

@pstorch As you did the initial commit, can you add that function?

**Comment by pstorch** [comment]
Yes, I just need a decision about n.
50, 100 or 200?

**Comment by pstorch** [comment]
I used n=100 for now. You can test and tell me if it's ok or needs to be increased or decreased.

**Comment by samueltardieu** [comment]
Fixed by @pstorch and assigned to @Lineflyer for field testing before inclusing in `release`.

**Comment by Lineflyer** [comment]
OK to be included in release.

**Comment by Lineflyer** [comment]
@samueltardieu Can you include this fix into release?

**Comment by Lineflyer** [comment]
Don't know if this has been done explicitly, but at least it is now done implicitly by merging `master` to `release`.
