### ISSUE TITLE
Strange progress info when starting logging a TB

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5406]
2016.01.20-NB1

If I open a TB via search on main screen I do see the normal loading data indicator until the tb info is shown.
If I start logging it however the very same loading data indicator is shown again with a not yet complete logging view in the background.

There is no functional problem but I would just like to ask if this was changed intentionally.

**Comment by kumy** [comment]
@Lineflyer I have added this while implementing #5135. I admit the message should be adapted, from "Loading trackable details..." to something more relevant to what is going on in background. ex: "Loading necessary informations to post a log..."

**Comment by rsudev** [comment]
In my opinion it shouldn't be a foreground item, rather a progress item somewhere within in the log activity or on the action bar. The same should then also be applied to the cache log activity, for consistency reasons.

**Comment by Lineflyer** [comment]
I don't know what you prepared right now with your PR.

The current situation before was, that we load the page in the background. If the user selects to send the log before completion of loading we show a prompt (at least for the cache log activity...for TB I am not sure).

I agree with @rsudev that we should not block the UI as the user can already compose his log in the meantime.
But there are some important usability things which should be covered:
- As soon as the user tries to send the log and this is (not yet) possible, he should be informed (like the current message displayed in the cache log activity)
- If the log type was "autochanged" as the selected was not available for that TB the user should be clearly informed (we currently have a toast message for this, which seems appropriate) and we should try to take care that the autoselected new log type is nothing crucial (e.g. "Post note" selected by default, but never "Grabbed").

**Comment by Lineflyer** [comment]
FYI: Somehow linked to #4970 if this is solved by a progress indicator on both cache and TB log acitivity.

**Comment by Lineflyer** [comment]
And link to #2916

**Comment by kumy** [comment]
Thanks.
I'm just preparing to solve first #4970 (just closed #5412 as duplicate), then this one by removing added code for displaying the popup.
From what I've seen, the two points you've listed are kept intact.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Progress indicator is shown for GC-trackable logs and GC-cache logs in 2016.02.22-NB.
Looks good to me, further implicit field tests will be done until next feature release. Will open a dedicated issue if I do see a problem.
