### ISSUE TITLE
Inconsistent list of saved lists

### ISSUE THREAD

**Issue by MisterAlea** [cgeo/cgeo#5407]
I can organize my saved caches in lists. There are two ways to select which list I want to see:
- Long tap the icon for lists in the c:geo home screen. Then a list can be selected from the list of lists. This opens the list itself.
- Short tap the icon for lists in the c:geo home screen. This opens the last used list. Now the list of lists can be opened from a dropdown on the top of the screen.

The two lists of lists are different. The first one does not contain the entries "history" or "new list" but the other one does. OK, I can open the history list from another icon on the home screen but I needed a discussion with rasch to recognize this. ;-)

My expectation is that the two lists of lists are consistent. 

Best Regards,

MisterAlea

PS: Thanks for improving and maintaining this great piece of software.

**Comment by Lineflyer** [comment]
I agree.

**Comment by Lineflyer** [comment]
setting for recheck. Assigning myself.

**Comment by moving-bits** [comment]
As of today (release 2020-01-10) status is:
- on long press in homescreen you'll get all persisted lists + entries "new list" and "all"
- from within a list, using the drawer in the action bar, you'll get all persisted lists + "all" and "history"

On homescreen, the history is available using the "history" (clock) symbol in the action bar, and from within a list, creating a new list is done using "manage lists" => "new list".

Do we need to add the missing entries to the two lists?

**Comment by MisterAlea** [comment]
> Do we need to add the missing entries to the two lists?

I would appreciate if you would do it.

**Comment by moving-bits** [comment]
Done with #9830 and #9836, both lists do contain the same entries now.
But be aware that we added "history" entry to mainscreen, but removed "new list" from it, as this would break workflows for many people if added to the cache list's list spinner.

**Comment by Lineflyer** [comment]
> "history" entry to mainscreen, but removed "new list" from it

Now I am confused....but maybe I need to look at the result in tomorrows nightly:
IMHO we had "Create new list" ever since when using the long press on lists on c:geo main screen. I suggested only to not add it to the dropdown selection in the top bar while already inside a list.

**Comment by moving-bits** [comment]
The original issue here was to make both lists the same (long press on "store" on mainscreen and list spinner in cache list). Thus I added "history" to mainscreen and "new list" on cache list list spinner at first.

You asked whether "new list" would be the first item in the cache list list spinner, which would have been true, so I made some proposals how to continue. One of which being to remove "new list" from both lists (https://github.com/cgeo/cgeo/pull/9836#issuecomment-764921585), which we agreed upon and which I implemented with #9836.

I can restore the "new list" entry on homescreen's selection, no problem, but that would break the original request in this issue here.

**Comment by Lineflyer** [comment]
I am sorry, that I might have not understood the issue/PR at first sight..or I mixed things up.

Let me try to summarize my proposal once more:

1. On long press list icon on home screen
IMHO this function should combine list selection and list management. So the user has fast access to a certain list and also to the function to create a new list. 
--> So coming from the current state, we should add the missing History list here.

2. On list dropdown in the top bar of a list
It should for sure show all existing lists (as it does already) and we might add the shortcut to "Create a new list" also here, to allow users to bypass to find "Create new list" in the menu. The only concern I had was, that it would break usage flow if you want to return to the default list (first entry).
--> Can it be added at the end? If it helps (and makes things consistent) we could also move "Create new list" to the end for case 1.

**Comment by moving-bits** [comment]
Thanks for clarifying. If the list on homescreen shall include list management, we need to re-add "new list" there.

IMHO "new list" is not necessarily needed in cache details, though, as I understand the list spinner over there being a selector of existing lists, not including management functions.
Putting "new list" at the end of that spinner would be inconsistent as well, as for our regular list selection boxes (e. g. on storing a cache) we explicitly moved the "new list" to the top (which is a good idea over there, IMHO).

So my proposal would be:
- re-add "new list" to homescreen's long-press on "stored" list
- leave out "new list" on cache list's list spinner
- and thus only partly fulfill this issue (but live with the difference and close anyway)
