### ISSUE TITLE
Add cache name to Orux app

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5411]
It seems to be possible to transfer the name of the waypoint:

```
putExtra("targetName", String);
```

See e.g. http://www.oruxmaps.com/foro/viewtopic.php?f=3&t=2490

**Comment by rsudev** [comment]
This sounds interesting (using Orux myself as well), but the official docs are not aligned with what we do right now...

**Comment by SammysHP** [comment]
Is there an official documentation at all?

**Comment by rsudev** [comment]
There is a documentation pdf with some intents documented on the last page: http://oruxmaps.com/oruxmapsmanual_en.pdf

**Comment by rsudev** [comment]
But the problem is - it doesn't work as documented. Except for one thing: if you use the VIEW_MAP_OFFLINE intent, Orux directly jumps to the offline map and doesn't try to load an online map as with our current intent.

**Comment by rsudev** [comment]
Reading everything again and checking it out, I found a way to implement this - thanks for highlighting.
