### ISSUE TITLE
support encrypted logs

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5419]
from facebook: Does cgeo automatically decode encrypted logs?
I have permanently encrypted a log entry on one of my caches as it gave clues to the cache location. On the web page the entry appears encrypted but cgeo shows it in plain text. 

GC59E5Z, log entry for 27 Aug 15

This is because we use the "Decrypt" button functionality when fetching logs. It should be possible rather easily to instead fetch the non decrypted JSON. I'm just wondering if we would need a new database column for log entries. To my mind it should in principle not matter for our app whether the stored log text is actually encrypted or not. Clicking it in the UI will just toggle, independent of whether we _known_ its state.

Am I right with that concept? If so, we could probably just pimp the JSON parser.

**Comment by rsudev** [comment]
To me it sounds reasonable and a good way to go forward to
