### ISSUE TITLE
CgeoApplicationTest.testSearchByOwner() test now fail

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5421]
This test is failing, the request `https://www.geocaching.com/seek/nearest.aspx?u=blafoo&tx=40861821-1835-4e11-b666-8d41064d03fe` now return 4 results instead of 3. A new cache (GC69H34) published on Jan 22 2016 is now shown.

May someone please confirm ?

**Comment by rsudev** [comment]
Confirmed. blafoo was a highly contributing member of the team quite some time ago (and author of this test :) ) and seemingly decided to publish another cache.

**Comment by kumy** [comment]
Thanks, I'll fix the test, by setting an attended value of 4.

**Comment by rsudev** [comment]
attended? you mean expected...

**Comment by kumy** [comment]
Yes :) sorry
