### ISSUE TITLE
Found status no longer detected on gc.com

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5422]
On master (only) currently it is not correctly detected if I have found a cache. @Bananeweizen Can that be related to your work on the detection patterns?

**Comment by Bananeweizen** [comment]
While this was not intended, there might be further broken things with the patterns I changed. So if any other information seems missing, please also direct the bug report towards me.

(If someone is wondering why the patterns are changed: My local application runs without switching to English, and seems to be parsing most things correctly, aside from trackables and status messages).
