### ISSUE TITLE
Action bar icon for PQ

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5424]
I just used c:geo in landscape mode and wondered what the icon with the key means. It is the "Pocket Queries" button. IMHO the icon should be replaced with something better.

**Comment by pstorch** [comment]
What about the file download icon?
https://design.google.com/icons/#ic_file_download

**Comment by Bananeweizen** [comment]
Not sure. Especially since many users might not even have downloadable PQs, but just browsable ones.

But for sure I'd use that icon instead of the floppy disk icon in the PQ list.

**Comment by pstorch** [comment]
What about simply the Letters "PQ"?
I know it's not really internationalized, but should be understandable by most Cachers. At least better than an arbitrary icon.

![2016-02-23 21 09 45](https://cloud.githubusercontent.com/assets/5598124/13266903/89298cde-da7a-11e5-8d77-c0403627336f.png)

**Comment by Lineflyer** [comment]
I kind of like that simple but matching proposal.
+1 from my side. If you provide a PR (maybe based on `release`branch if this is doable) we could include it right away if no one objects.

**Comment by rsudev** [comment]
For many languages it might work, with some exceptions (e.g. Russian, Latvian). Another idea could be to use something similar to the lightning symbol that is used (albeit not very prominent) to represent pocket queries on the website.

**Comment by pstorch** [comment]
The website has three different icons for PQs. One for each type: Standard, Bookmarklist and Route. And yes, not very prominent. 
Locus uses a Cache symbol with a down arrow above and the PQ Creator App has this kind of Stopwatch. 
Couldn't find any other. Most other applications have just a Text menu entry for PQ, if at all.

**Comment by SammysHP** [comment]
I don't like text in icons and I think there is also an Android UI guideline that says the same.

**Comment by pstorch** [comment]
Another Idea.
What about a combination of a suitcase (a pocket) and a magnifying glass?

![2016-02-24 22 13 07](https://cloud.githubusercontent.com/assets/5598124/13302862/72e8abc6-db4c-11e5-9b9d-3ea2c817d994.png)

**Comment by Lineflyer** [comment]
The latest proposal is also fine for me.
