### ISSUE TITLE
Error while write a note for a travelbug 

### ISSUE THREAD

**Issue by notspecified** [cgeo/cgeo#5427]
Im on 2016.01.25-NB-66ed060 and I get an error message when I want to write a note for a tb. It says that the note might not be sent, and that I should check the website. When I do so -or when I reload the tb site in cgeo the log exists. Can anyone reproduce that? When I discover a tb with the trackingcode I dont get any error.
![_20160129_221407](https://cloud.githubusercontent.com/assets/5119558/12688415/6595e978-c6d6-11e5-886a-f743a7905a3a.JPG)

**Comment by rsudev** [comment]
Confirmed, same behaviour for me.
