### ISSUE TITLE
website tests from last release tag?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5432]
Right now we run the website tests from the master branch. I was wondering if we should change this to work from the last release tag. Otherwise we might miss changes like reported yesterday, where the master branch is actually fault tolerant, but the release doesn't work.

Any comments?

PS: Implementation might look like http://julienrenaux.fr/2013/10/04/how-to-automatically-checkout-the-latest-tag-of-a-git-repository/, assuming we current don't create other tags than for releases.

**Comment by samueltardieu** [comment]
We should run both. Maybe even from three sources: the latest tag, the release branch (the problem may have been fixed there), and the master branch.

You can assume that tags starting with "market_" and not ending with "-legacy" are for releases. The other "proper" way of doing this is to have a branch which is only moved when a tag is created ("published" for example). The top of the branch would always be the latest release tag.

**Comment by Bananeweizen** [comment]
I've now added a job to build from release branch.

**Comment by Lineflyer** [comment]
AFAICS the "website test release" is using the `head` of `release`.
Do we have the neccesity to let it build by release tags as well and keep this open?
