### ISSUE TITLE
New permission requirement?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5434]
When installing 2016.02.04-NB coming from a nightly of a couple of days before the installation dialog shows a new permission requirement "Surpress standby mode" (Standby-Modus verhindern).
Is that intentionally (despite the fact that IMHO we aleeady surpress standby in the past).

**Comment by notspecified** [comment]
I can confirm this new permission request!

**Comment by SammysHP** [comment]
No new permissions from our side: https://github.com/cgeo/cgeo/commits/master/main/AndroidManifest.xml

Maybe an updated version of Google Play Services.

**Comment by notspecified** [comment]
Btw. Where is the newest version 20160203 here: https://github.com/cgeo/cgeo/releases/ I can't find the apk download!

**Comment by SammysHP** [comment]
Here it is: https://github.com/cgeo/cgeo/releases/tag/market_20160203

Our release manager is currently not available, so it will take a few days.

**Comment by Bananeweizen** [comment]
I'm not sure, but I think this is a permission coming from play-services-measurement, which itself is a transitive dependency of play-services-appinvite, that I included recently. Seems there are other people not so happy about this: https://twitter.com/osipovas/status/667556657090707456 But I'm not aware of a workaround (or how to exclude this transitive dependency correctly).

**Comment by rsudev** [comment]
Mhhh - maybe we should just use the already existing 'share' functionality to send a play store link instead of this app invite? It might be better suited if we would like to send 'deep links' or want to analyse the sharing patterns, but that would be out of scope IMO.

**Comment by Natureshadow** [comment]
NEVER link to Play Store directly, but to the package name, so other app stores like F-Droid can pick it up!

Google Play is *not* part of Android, it is optional third-party software.

**Comment by rsudev** [comment]
If this is possible/feasible, even better. Do you have a sample/background info?

**Comment by SammysHP** [comment]
@Natureshadow 
Do you mean `market://details?id=cgeo.geocaching`?

**Comment by Bananeweizen** [comment]
Guys, would you please first try for yourself, what app invite is? That is way more than sending a link to the app. It doesn't make sense to re-invent the wheel here.

And while I completely support the idea of using c:geo on Android phones without Google, we should still target the majority 99% of users, that actually _have_ Google Play services installed, and provide useful functionality for them.

**Comment by rsudev** [comment]
I didn't actually try it out, only read the material available (it will never work on my phone due to the restrictions I placed on gms in general).
I see that there are many possibilies around that in principle, but I could not see where they would apply to our scenario besides conviniently forwarding someone to the install itself.

**Comment by SammysHP** [comment]
I just tried it. It opens a list with my contacts and I can choose contacts and the method (E-Mail, SMS), enter a custom message and send a message to those contacts. The only difference compared to the classic "share" is a special GUI and the possibility to select different ways of communication.

But the downside is that it works only with Google, requires another permission and adds unnecessary code.

**Comment by Lineflyer** [comment]
My few cents:
I tried it and don't see the real benefit instead of sharing a link to the PlayStore via conventional methods.
From my experience on support mail I know, that new permissions (and in this case they are even not really good explainable) are always a point of discussions. So I would prefer to remove this function. under the given circumstances.

**Comment by Lineflyer** [comment]
This is now part of the release branch and about to be released.
Any decision regarding removing this feature which needs an extra permission....?

**Comment by Bananeweizen** [comment]
I actually want to have this feature in and I totally accept the new permission. I want us to get to a state where we can use current technology, current libraries etc. I strongly question the need to have a minimized set of permissions, as that limits us in getting forward. E.g. I also would like to have vibration (new permission!), access to Google drive (new permission!) and potentially other things which are all useful for the app.

**Comment by Lineflyer** [comment]
OK. Then lets try and monitor users reactions.
Anyway I am wondering about this new permission as we already surpress standby mode within c:geo AFAICS.

**Comment by rsudev** [comment]
I am generally wary of introducing not necessarily new permissions and libraries, but new service dependencies, especially with privacy implications.
So in this case I just wonder, what this AppInvite Api possibly collects (if anything) and what we therefore need to tell our users up-front about that (this is part of the general Api Terms of service of Google as far as I could understand that). That it has an 'unlcear' dependency on google-measurement (which is the AFAIK the Android version of Google analytics) does not really instill trust from my perspective.
Google drive would IMO be an entirely different beast and should be delegated to a plugin, like calendar and contacts access.

**Comment by rsudev** [comment]
Should we open a reminder to add the explanation for this new permission to the website (or do we have that also in the app itself?)

**Comment by samueltardieu** [comment]
We should switch to API 23 anyway and use dynamic permissions.
