### ISSUE TITLE
Selection for adding to fsvorites no longer shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5435]
2016.02.04-NB

The logging view does no longer show the option to add a cache to your favorites, although I am PM and favorite points are available.

Already noticed this some days (nightlies) ago...or a site change?

**Comment by rsudev** [comment]
Was a side-effect of fb31b6b06fc6b141d356f82d3bf6700422090e3f on master only. As I am no regex expert, please review if this is a sensible change.
