### ISSUE TITLE
Nightly Build: unable to install (apk corrupted?)

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#5437]
Hi,

I'm used to run c:geo Nightly Build, I install it by clicking on "the home message" but today after download the install failed.

Maybe the generated apk is "broken"?

Best regards,

**Comment by Bananeweizen** [comment]
works for me with the same nightly and the same update procedure.

**Comment by ldmpub** [comment]
After app removal, re-install of the apk still fails.
Is there a way to debug / log the install?

**Comment by SammysHP** [comment]
Have you tried to download it again?

**Comment by ldmpub** [comment]
Yes just now from the website: http://download.cgeo.org/cgeo-nightly.apk.

**Comment by Bananeweizen** [comment]
There is a new permission required by the APK since about 5 days. Do you have any mechanism enabled, which intercepts the installation in such a case?

**Comment by ldmpub** [comment]
I have no particular security / anti-virus app.
I'm running Android 4.4.4.

regards,
