### ISSUE TITLE
Endless downloading of TB page

### ISSUE THREAD

**Issue by ldmpub** [cgeo/cgeo#5438]
Hi,

I'm online and I'm trying to view TB details: the usual popup is displayed but c:geo is stucked there ... the TB page is never displayed (see screen capture below).

Best regards,

![endless downloading of tb page](https://cloud.githubusercontent.com/assets/1452146/12868273/412f71d4-cd03-11e5-862a-c1df41b88ba0.png)

**Comment by Bananeweizen** [comment]
Please install the update from February 03. It contains a fix for that issue.

**Comment by ldmpub** [comment]
Perfect TB page works again!

Many thanks,
