### ISSUE TITLE
Allow to update Header-Coordinates for Letterbox and Wherigo Caches

### ISSUE THREAD

**Issue by blochi79** [cgeo/cgeo#5439]
The finals of a Letterbox and Wherigo Caches could have other coordinates as the header coordinates from their listings. So it should be possible to enter these coordinates so that g:geo treat them as header coordinates. At the moment it is also possible to send these coordinates to geocaching.com as corrected coordinates for the listing. These seems to be a breach in the website. 

The impementation of this feature request is a simple one-liner in the source file EditWaypointActivity, in the current revision the line 207 have to be changed.

**Comment by mucek4** [comment]
Duplicate #4391

**Comment by Lineflyer** [comment]
We should implement this for the local header coords but not allow sending to the website (as it is not offically supported).

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Working as expected in 2016.02.22-NB for Letterbox and Wherigo.

**Comment by blochi79** [comment]
Now we have a follow problem. ;-( The local header coordinates are overwritten if the cache is refreshed. The method for refreshing a cache needs also to be adapted for the case that the local header coordinates have been corrected. Then the original coordinates in waypoints must be updated with the Listing coordinates instead of the header coordinates.

**Comment by Lineflyer** [comment]
@blochi79 
I can confirm, however that is the wanted current behaviour once updating caches where the header change was local only (i.e. also for Multi, Mystery). Server changes have priority in this case.
You really think this should be handled in another way?

**Comment by blochi79** [comment]
I often perform bulk refresh of mixed lists that contains also traditional caches. In this case I don't want to lose the corrected coordinates of letterbox or Wherigo caches. I did not know that it is the default behavior of c:geo to overwrite the local corrected coordinates with the listing coordinates. I think the current issue can be closed and the behavior of overwriting corrected coordinates while refreshing a cache may be discussed as subject of another issue. Sorry for the confusion.

**Comment by Lineflyer** [comment]
That seems logical as also in other places user modified data will never be replaced by server data. Will take this to a new issue.
