### ISSUE TITLE
Support for mapsforge 0.5.0 themes

### ISSUE THREAD

**Issue by notspecified** [cgeo/cgeo#5440]
Afaik Supports cgeo at the Moment only 0.3.0 themes. Sadly these themes are not longer maintained at openandromaps.org. 
The current version they offer is 0.5.0, which seems not supported by cgeo!

Will this issue be fixed?

**Comment by rsudev** [comment]
This refers to #5047
If you are a developer, you might be able to check #5354

**Comment by notspecified** [comment]
I see! Sadly im no Dev...

**Comment by rsudev** [comment]
My goal is to have a version which is including this as an experimental feature in the not too distant future (1-2months at most)

**Comment by SammysHP** [comment]
Just a note that also Freizeitkarte will switch to a theme with mapstyles with the next update in some weeks.
