### ISSUE TITLE
Improvements for c:geo support mailbox

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5442]
Given the fact, that I currently go through the support mails of the last weeks (due to my absence) some improvement ideas came to my mind:
1. Couldn't we have some webmail client running to on one hand allow more flexible access to mails while on the road and on the other hand have some more team members available to take a look and answer them if time permits?
2. Could we have an auto reply feature which can be activated if needed (e.g. in case of absence or in case of known problems)?

**Comment by SammysHP** [comment]
Roundcube, please. :)

https://roundcube.net/

**Comment by samueltardieu** [comment]
We could either install a request tracker indeed, or just forward mail (as it is forwarded to me) to a list of individuals. This way, everyone would see the answers at well a along as everyone responds to all (thus keeping support in cc).

I guess it is standard in many clients, but with Gmail, responding to a support message uses the right address (support) and inserts the right signature.

**Comment by mucek4** [comment]
Roundcube is installed for couple of years. Just nobody asked for it.

**Comment by samueltardieu** [comment]
> Roundcube

Why install a mail server when we all already have ours (personal, hosted, or shared)? Let's not force people to use web interfaces when they can answer with their regular (possibly web-based) client.

**Comment by SammysHP** [comment]
Roundcube is not a mail server, it is just a web-based client for IMAP servers. How is it handled currently? Do you use the same imap/smtp account or are all mails forwarded?

**Comment by samueltardieu** [comment]
AFAIK, Lars & Tomaž connect to the same web-based client. This way they see which mails have received no answers using the "unread" indicator.

I receive a copy of mail sent to support. I use "reply to all" when I reply so that Lars & Tomaž know I have replied. However, I do not see when they do (as they don't keep support@cgeo.org in cc).

**Comment by Lineflyer** [comment]
I do access via IMAP and hold the mail on my local client (PC). Quite ok for me....the suggested webmail was just in case some more could access if needed. But this could also work with local IMAP clients of course.

More important for me would be an auto reply feature. Somewhere I did already suggest a default reply some months ago.

**Comment by Lineflyer** [comment]
@samueltardieu You should be able to see mails sent by us in the IMAP folder for sent mails..or not?

**Comment by samueltardieu** [comment]
I don't use the shared IMAP folder (I don't like shared accounts in general), mails get *forwarded* to me.

**Comment by SammysHP** [comment]
Then we should try a ticket system like osTicket.

**Comment by samueltardieu** [comment]
Yes, or [RT](https://www.bestpractical.com/rt/) which can be interacted with via e-mail. Is that the case with osTicket as well? I can't find that in the features list.

**Comment by SammysHP** [comment]
AFAIK osTicket works via mails as well (tested the demo and it looked email-like).

**Comment by Lineflyer** [comment]
@mucek4  Could you as a first step set up a webmail for the support mailbox? Due to technical reasons I will be no longer able to access support mail via IMAP from my work and at home I can only set it up on my tablet which is not the optimimum case.

**Comment by samueltardieu** [comment]
Why not use a mailing-list to dispatch the mail? That way, everyone on the list would be able to use their own tools instead of having to log in to another web site.

**Comment by mucek4** [comment]
@Lineflyer I have send you URL to roundcube.

**Comment by Lineflyer** [comment]
Due to my upcoming vacation I want to push this thread up once again:

1. Roundcube access is working fine

2. The auto-reply feature was the other thing I asked for.
@mucek4 It seens not possible to set it up on the server via Roundcube right now, however I have seen, that there are server plugins available for that purpose...so I could set it up via the webmailer. Can you check?

**Comment by Lineflyer** [comment]
@mucek4 Is autoreply possible? Else lets close this.

**Comment by mucek4** [comment]
Autoreply is possible, but currently I have to set it up. If you need autoreply, message me.
