### ISSUE TITLE
crash while opening / viewing images from GC1NBJH

### ISSUE THREAD

**Issue by rhubert** [cgeo/cgeo#5445]
I'm unable to open GC1NBJH in cgeo. 

For me it's not deterministic when the crash occurs. On one of my phones it crashes when I try to open the cache. On the other after moving to the Images-tab. 

NB 2016 02 05 - NB 2428cb0 and
NB 2016.02.14 - NB 11ae549

**Comment by SammysHP** [comment]
Maybe because there are hundreds of pictures in the listing…

**Comment by rahu** [comment]
Sure, but maybe we can avoid the crash anyway?

**Comment by rsudev** [comment]
It looks like an OOM in the downloader/display threads. Of course it would be good to avoid it, but I deem that this is not easy...

**Comment by Lineflyer** [comment]
There was something similar in the past in #3146 and in general those issues did only occur very rarely after implementing #5038.

**Comment by Lineflyer** [comment]
Opening the mentioned caches does now work for mw with 2016.08.27.
It takes rather long and scrolling might be not smooth due to the high amount of data (but you can work with it, at least on my device).

**Comment by Lineflyer** [comment]
Seems I need to reopen...seconds after I wrote it I experienced the crash while going to the image tab of that cache.

**Comment by okainov** [comment]
doesn't seem to crash for me, however the cache is really heavy, that's true

**Comment by Lineflyer** [comment]
Problem no longer reproducible with 2020.09.23-NB
