### ISSUE TITLE
Distance field missing in waypoint screen

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5447]
From support mail and not reproducible for me.
I asked the user to try in english and try on white theme.

```
--- System information ---
Device: SM-G357FZ (heatqltexx, samsung)
Android version: 4.4.4
Android build: KTU84P.G357FZXXU1ANL1
Cgeo version: 2016.02.03
Google Play services: disabled
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: lv_LV
Geocaching sites enabled:
- geocaching.com: logged in (Pieteikšanās izpildīta veiksmīgi) / Basic
Installed cgeo plugins:  none
--- End of system information ---
```

![screenshot_2016-02-14-05-20-14](https://cloud.githubusercontent.com/assets/949669/13058583/6552c57a-d424-11e5-885f-d12df99c8952.png)

**Comment by Lineflyer** [comment]
More info from that user:

>> Can you please try to switch c:geo to English using c:geo Settings –> Appearance -> Force English (afterwards reboot c:geo or even your whole device).
>> Does it work in english? 
>
> In english it works!! :)


>> Please do also try to switch to the white theme in c:geo Settings -> Appearance (restart required).
>
>> Does this change anything in the problem. Can you please provide a screenshot of the problem using the white theme? 
>
> In white theme it isnt changing..

**Comment by Lineflyer** [comment]
I guess I found the culprit, the translations are broken/incorrect causing a too long field in the UI:
https://github.com/cgeo/cgeo/blob/master/main/res/values-lv/strings.xml#L1341-L1343

Will correct via crowdin in a minute.

**Comment by Lineflyer** [comment]
Corrected on Crowdin, will be solved with next download from Crowdin.
@rsudev Please incorporate the download from Crowdin into `release` branch if possible to solve it for the next bugfix release.

**Comment by rsudev** [comment]
This will be possible (for these cases we started the branch handling), but as I am still fighting with the undocumented peculiarities of crowdin here, it might happen tomorrow or the day after

**Comment by rsudev** [comment]
Done with 9add2f4

**Comment by Lineflyer** [comment]
Closing as solved with the new translation. Thanks @rsudev
