### ISSUE TITLE
Horizontal line in markdown logs not supported

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5448]
While with version 2016.02.03 all markdown formattings usable in the log editor on the website seem to work good in c:geo (tested), the horizontal line is not shown.

Example:
```

Horizontal line

----------

```

**Comment by SammysHP** [comment]
Duplicate of #2476.

**Comment by Lineflyer** [comment]
@SammysHP  Interesting. PLease refer to my refently posted question in #2476...so that means it is a fault in the android functions we use?

**Comment by SammysHP** [comment]
Seems like Android does not render hr-tags.

**Comment by Lineflyer** [comment]
Closing then
