### ISSUE TITLE
Compass freeze when talking compass is active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5450]
2016.02.03 (reported on support mail and reproducible for me):

- starting compass
- starting talking compass function
- switching to another app or blanking the screen by pressing the power button
- switching back to c:geo
- now the compass is frozen and does not react when changing the bearing of the device
- the compass and talking compass react to changes in distance but not to changes in bearing

This behaviour ist 100% reproducable but does NOT appear, when
- using compass wihtout the talking function
- leaving the compass screen on while using talking compass (i.e not switching to another app)
- downgrading c:geo to v2015.11.29

**Comment by alex7654** [comment]
The issue does not appear in version 2016.03.06 anymore. I tested it on my Samsung Galaxy Note 2 (Android 4.2.2) and my Samsung Note 10.1 2014 Edition (Android 5.1.1) and it seems to be resolved :-).

**Comment by Lineflyer** [comment]
Still reproduible for me with current nightly 2016.04.03-NB

**Comment by samueltardieu** [comment]
I can't seem to reproduce this on my Nexus 5 with CyanogenMod nightly and today's master.

**Comment by Lineflyer** [comment]
I also cannot reproduce it anymoe with current master.
