### ISSUE TITLE
Back button in spoiler view leaves the app

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5452]
2016.02.03:

- Open a cache which has spoiler pictures
- Open spoiler pictures by clicking on the icon in cache details
- Use the action bar back button to leave the spoiler picture view

Result:
Instead of returning to the cache detail screen c:geo is ended.

**Comment by notspecified** [comment]
Can not confirm this with 2016.02.14-NB-11ae549!
I've a normal behaviour, which leads me back to the listing.

**Comment by rsudev** [comment]
To me this sounds similar to another issue we recently had (but cannot find it right now) where images from the previously viewed cache where shown on a second opened one.

**Comment by Lineflyer** [comment]
@notspecified 
Strange. I can reproduce this with 2016.02.13-NB. Will try a newer one.

@rsudev 
This is not about wrong images, but just about a "wrong" activity stack I guess.

**Comment by rsudev** [comment]
The wrong images were (IMO) caused by a wrong activity stack, therefore my assumption that there might be a relation. Unfortunately I still can't find that other issue.

**Comment by Lineflyer** [comment]
Probably #4570 but here an failure in the way we access the database was the root cause and it was fixed.

**Comment by rsudev** [comment]
Thanks for the link. It led me to the issue I had in mind here (#5240), which sounds similar and is still open.

**Comment by samueltardieu** [comment]
Some code explicitly manipulated the stack (for almost 4 years now, from https://github.com/cgeo/cgeo/commit/ed354de82bbfb61c9a1d9c2f8ce2c7cbe33a8cc9). Removing it will probably make things much smoother.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Confirmed working with 2016.02.22-NB.
