### ISSUE TITLE
Feature Request: My own Caches & My own Trackables

### ISSUE THREAD

**Issue by caigner** [cgeo/cgeo#5454]
For owners of Geocaches and Travelbugs/Geocoins it would be a great new feature if you could add two more buttons on the start screen of c:geo:

1. A button for "**My own Geocaches**"
2. A button for "**My own Trackables**"

This would make managing your own Geocaches and Trackables a little bit easier.

Thank you for your great work!
Christian

**Comment by SammysHP** [comment]
"My own Geocaches" is already available in the search activity. IMHO it is not used often enough to include it on the start screen.

**Comment by rsudev** [comment]
I would like to ask what you expect from these buttons. Shortcut to a special list (for the caches)? Online search?

**Comment by kumy** [comment]
Isn't it related to #420?

**Comment by Lineflyer** [comment]
This is indeed a duplicate of the mentioned issue.
Please kindly continue in #420 to discuss this.
