### ISSUE TITLE
Feature Request: Ability to store geocaches on more than one list

### ISSUE THREAD

**Issue by caigner** [cgeo/cgeo#5455]
Right now a geocache can be downloaded and stored on a list. And only on one list.

If I have a list of "**the best caches in my area**" and a list of "**all the caches in my area**", then the second list will not be complete, because some of the caches will be on the first list. And if I create a third list with "**only caches with D>3 and T<5**' then probably some of the caches on the first list will change to the third list which would be (actually: is) annoying. At least two of my lists would not be complete.

Would it be a great difficulty to have an **m:n** relationship between geocaches and lists?

Thank you for taking the time to think about it!
Christian

**Comment by rsudev** [comment]
Closed as duplicate see #87
