### ISSUE TITLE
Move tests from 'src' to 'src-android'?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5457]
I've found that tests are split in:
* tests/src/cgeo/...
* tests/src-android/cgeo/...

When launching 'all tests', only the one in `src-android` are run.
There is some inconcistencies too, see the 2 files for `CacheSizeTest`...

Should we move them from `src` to `src-android`?

**Comment by samueltardieu** [comment]
`src` tests are run *without* Android, directly on the host (instead of the emulator). This is much faster.

You can run them using: `gradle testBasicDebugUnitTest` I think. They are run as part of the CI tests.

**Comment by Bananeweizen** [comment]
Have a look at the available tasks in the cgeo category of the gradle task list. There should be one called testdebug or so which invokes both kinds of tests with the debug build.

**Comment by kumy** [comment]
I'll now launch tests from the command line. Thanks
