### ISSUE TITLE
remove option to load description on demand

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5462]
I suggest we remove the above mentioned option. This might have been useful at times of slow devices, but nowadays I see more potential for users complaining that they always need to hit that button, than I see benefits by not automatically loading the (long) description.

Comments?

**Comment by Lineflyer** [comment]
Some time ago we set the option to active as default...so the next step would now to remove it. I agree.

**Comment by SammysHP** [comment]
Then we should move the hint and note sections to a different location. Some listings are really long.

**Comment by Lineflyer** [comment]
That is a valid argument: So people wanting fast access to hint and note may currently use the option to hide the long description.

I think the hint should be bound to the description somehow (like on the website and people currently expect it there also in c:geo) but the note could for sure be another tab if more are possible (suggest: left of waypoint).
For the hint which is usually quite short I would not invest any separate page/tab but a clever method from somewhere in cache details or description to jump or open it on demand....

If we do any changes to the existing UI location of information we should consider carefully if and how users will understand and find it on the changed UI.

**Comment by SammysHP** [comment]
Adding quick scroll to the description/hint page might be enough (compare log page).

**Comment by Lineflyer** [comment]
> Adding quick scroll to the description/hint page might be enough (compare log page).

Agree.
@Bananeweizen Could you combine removal of the option with inclusion of this feature. That would be a good compromise if no one objects,

**Comment by Bananeweizen** [comment]
fastScroll is only available for lists. The description page is no list, so I don't see how this could work. Am I missing something? I'm currently in favor of just removing the option and to wait for feedback with the next release.

**Comment by Lineflyer** [comment]
In this case I also vote for removing it.
Lets seen if better ideas come up

**Comment by samueltardieu** [comment]
Please test the PR in https://github.com/cgeo/cgeo/pull/5567 before we merge it.

**Comment by samueltardieu** [comment]
@Bananeweizen I hadn't seen that it was assigned to you, feel free to close the PR if you want to implement this differently.

**Comment by samueltardieu** [comment]
I have merged the PR in `master`. Do not hesitate to report any problem by reopening this issue.
