### ISSUE TITLE
Add trackable brand to activity

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5463]
Right now it is impossible to tell if a trackable opened from search is either travel bug or geokrety or geolutin. As far as I can see the "type" line might distinguish coins (if travel bug connector), books (if geokrety) and similar, but it does not tell which company/website manages this trackable. As there are users which don't want to register at all sites, we should make it possible to recognize very easily to which site/brand this trackable belongs.

@kumy maybe this is of interest for you, since you changed a lot around trackables?

**Comment by kumy** [comment]
@Bananeweizen how would you like represent that? Just another text line
`Brand: Travelbug`?
For GK and GL, this is a special icon in the navbar. TB load internal icon if they have.
