### ISSUE TITLE
Native crash at /system/lib/libskia.so

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5466]
I have someone at support mail where the mapsforge implementation (i.e. OSM:Online as well as OSM:Offline) crashes as soon as he starts zooming in/out reproducibly since upgrading his device to Android 6.

(Incomplete) system information:

```
--- System information ---
Device: MotoG3 (osprey_retes, motorola)
Android version: 6.0
Android build: MPI24.65-33
Cgeo version: 2016.02.03
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer 
```

I could find his crash report on the Play Console, but what does it mean.
Could someone give me a feedback I can send to the user? Is this our problem, or a device problem.

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'motorola/osprey_reteu_2gb/osprey_u2:6.0/MPI24.65-33/36:user/release-keys'
Revision: 'p2b0'
ABI: 'arm'
pid: 14005, tid: 14005, name: cgeo.geocaching >>> cgeo.geocaching <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xa2db5000
r0 a2db5000 r1 a2db4ffc r2 f5d0f000 r3 00003ff0
r4 b8cad1a8 r5 01e5eaa0 r6 0000bfd0 r7 000001e5
r8 000002d0 r9 000001e6 sl 00004000 fp 00000000
ip 000001e6 sp befdfb08 lr 00000004 pc b6ababe8 cpsr 20070010

backtrace:
#00 pc 001febe8 /system/lib/libskia.so (NofilterDXExecutionBuffer565::GenerateUpscaleProgram(int, int, int, int)+128)
#01 pc 001ff604 /system/lib/libskia.so (NofilterDXExecutionBuffer565::GenerateProgram(int, int, int, int)+132)
#02 pc 001ff704 /system/lib/libskia.so (NfDXEB565Cache::prepareShaderProc32(int, int, int, int)+232)
#03 pc 001fd4b0 /system/lib/libskia.so (SkBitmapProcState::beginRect(int, int, int)+336)
#04 pc 001fdcb4 /system/lib/libskia.so (SkARGB32_Shader_Blitter::blitRect(int, int, int, int)+1568)
#05 pc 0011ec33 /system/lib/libskia.so
#06 pc 0011ecfb /system/lib/libskia.so (SkScan::FillIRect(SkIRect const&, SkRegion const*, SkBlitter*)+194)
#07 pc 0011edc5 /system/lib/libskia.so (SkScan::FillRect(SkRect const&, SkRegion const*, SkBlitter*)+138)
#08 pc 0011eeb5 /system/lib/libskia.so (SkScan::FillRect(SkRect const&, SkRasterClip const&, SkBlitter*)+56)
#09 pc 000f9f83 /system/lib/libskia.so (SkDraw::drawRect(SkRect const&, SkPaint const&, SkMatrix const*, SkRect const*) const+522)
#10 pc 000fb5db /system/lib/libskia.so (SkDraw::drawBitmap(SkBitmap const&, SkMatrix const&, SkRect const*, SkPaint const&) const+452)
#11 pc 000f2d19 /system/lib/libskia.so
#12 pc 000f2e29 /system/lib/libskia.so (SkCanvas::onDrawBitmap(SkBitmap const&, float, float, SkPaint const*)+184)
#13 pc 00051edf /system/lib/libhwui.so
#14 pc 0008a617 /system/lib/libandroid_runtime.so
#15 pc 02a64181 /system/framework/arm/boot.oat (offset 0x1fde000)
```

In general I do see some strange crashes only occuring on Moto G according to the Play Console.

**Comment by rsudev** [comment]
I cannot say for sure, because it might be due to some wrong parameter from our (mapsforge) side, which is tolerated/handled by other implementations, but I am pretty sure it is rather a (compatibility ?) bug on the Moto G.
Perhaps it can help to switch of hardware acceleration.

**Comment by Lineflyer** [comment]
@rsudev 
Funny thing. HW acceleration was switched off on the users device. After turning it on the crashes disappeared.
Question is, why it was deactivated. The user did not manually do this according to his explanations. 
According to https://github.com/cgeo/cgeo/issues/4265 this device is not on our list. Is there any version detection in place which might fail for Android 6?

**Comment by samueltardieu** [comment]
Might the settings from the old device have been saved on Google servers (they're supposed to be) and restored on the new phone? In this case, the "use hardware acceleration" has been transported from a device to another.

Maybe some preferences ought to be in a non-Google-backed-up file.

**Comment by Lineflyer** [comment]
Closing this as no more reports like this came in.
Additionally we are about to change the mapsforge library version.
