### ISSUE TITLE
Twitter authorization does not work

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5468]
While the signatures are correct, the authorization process fails right at the beginning, at least on Android 6.0. It might be due to the use of HTTP/2 (h2).

**Comment by samueltardieu** [comment]
@Lineflyer Could you confirm that Twitter authorization is working with the current release?

**Comment by Lineflyer** [comment]
Will do.

**Comment by Lineflyer** [comment]
Tested with 2016.02.22-RC and Android 5.0.1 (Samsung S4):

I have to admit I did not perform this for a longer time..however it does not seem to work.
I can start the process, Chrome opens and I am directed to the Twitter API login page, I can succesfully login and can read on the webpage "You are directed back to the application. This might take some time"(Free translation from German). 
But Chrome stays open and does not return to c:geo (also after waiting for several minutes).
Manually closing the browser I get back to c:geo but are not authorized.

I guess this is a different problem as you see with HTTP/2?

I will have a look into the logs later today.

**Comment by samueltardieu** [comment]
Yes, in my case the request seems to fail without even opening the browser and return a `401 Unauthorized` prematurely.

**Comment by Lineflyer** [comment]
Tried with the default browser instead of Chrome and this works normal. I get authorized and posting works. So I would say: No problem on `release` but a problem on `master` or related to Android 6

**Comment by samueltardieu** [comment]
When you say "problem on master", have you also tried on `master` and get it to fail?

**Comment by Lineflyer** [comment]
@samueltardieu 
I am now back on `master` for my daily usage and did not have any problem with Twitter so far.
