### ISSUE TITLE
<hr/> tag in log is not rendered

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5470]
Android does not render `<hr/>` HTML tags in log entries.

**Comment by samueltardieu** [comment]
I've replaced this with a string of 30 striked-through blanks.

@Lineflyer Please tell me if you want this in `release`.

**Comment by Lineflyer** [comment]
Yes, this looks good as a workaround for release as well.

Link to #2476 and #5448 for documentation of the workaround.

**Comment by Lineflyer** [comment]
Tested and **not working**  in 2016.02.23-RC. I compiled a new RC (IMHO after your merge of the HR-workaround). Still it does not show up in my RC version also after refreshing the reference cache (from above).

**Comment by Lineflyer** [comment]
FYI: 
I did now also include `<hr/>` within the listing text of GC352Y3 for testing purposes.

**Comment by samueltardieu** [comment]
Does regular striked through text get rendered on your device?

**Comment by samueltardieu** [comment]
![Cache description](https://cloud.githubusercontent.com/assets/44656/13260952/2a6b2854-da5e-11e5-954f-3e7960c88e2a.jpg)

**Comment by Lineflyer** [comment]
Yes. I added a `<strike>` element to the listing (at the very end) for testing.

**Comment by Lineflyer** [comment]
And the RC should contain the fix: 
http://ci.cgeo.org/job/cgeo%20release%20candidate/5/

**Comment by samueltardieu** [comment]
What's your Android version? On 6.0.1, everything works as expected.

**Comment by Lineflyer** [comment]
5.0.1 on Samsung S4

**Comment by Lineflyer** [comment]
oh well... you will not like to hear that:
If I disable HW-acceleration it works.

**Comment by samueltardieu** [comment]
Well, too bad for you then :)

**Comment by Lineflyer** [comment]
Guess there is nothing we can do here although I am wondering what HW-acceleration has to do with it.

**Comment by Lineflyer** [comment]
@samueltardieu Funny fact: After upgrading from current release to NB the strikethrough is woking on the same device also with HW-accel. enabled.

**Comment by samueltardieu** [comment]
So be it.
