### ISSUE TITLE
Auth to Geokrety fails on Android 2.3 device

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5473]
###### Detailed steps causing the problem:
- Open c:geo settings
- Go to Services -> geokrety.org
- Enter valid credentials and start the authorization process

###### Actual behaviour after performing these steps:
Error is returned, log shows:
```
21:38:18.805 Debug cgeo 1307  [network-7] POST https://geokrety.org/api-login2secid.php
21:38:21.647 Warning cgeo 1307  [network-7] Failure (2783 ms) POST https://geokrety.org/api-login2secid.php (javax.net.ssl.SSLPeerUnverifiedException: No peer certificate)
```

###### Expected behaviour after performing these steps:
Auth should work normal like without https (in earlier c:geo versions)

###### Version of c:geo used:
2016.02.23-RC

###### Is the problem reproducible for you:
Yes (on this device)

###### Attach system information if available (see c:geo menu -> About c:geo -> System):
Device: HTC Wildfire S (htc_marvel, htc_europe)
Android version: 2.3.5

###### Other comments and remarks:
Using the phones default browser I can access https://geokrety.org/api-login2secid.php without a problem and also login and get a key provided back. 
Still it might be an issue specific to this device and missing root certificates (although I am wondering that the browser does not report any security issue)

**Comment by kumy** [comment]
I don't know why the default browser doesn't have any problem with this ssl chain.
Should we disable GK SSL for android version lower than X.X.X (2.3.5)?

**Comment by Lineflyer** [comment]
Can someone else test with a 2.3 device?

**Comment by kumy** [comment]
Cannot test, the phone I got was Android 2.2, which is SDK 8... :/

**Comment by andrixnet** [comment]
I have encountered a similar problem on my Android 4.2.1 phone. 
I enter valid credentials and I get "Authorization has failed". 
I tried to generate logs as instructed in the wiki, although my phone is rooted, I got nothing in aLogcat.

**Comment by kumy** [comment]
Maybe Settings -> System -> Activate debug log?

**Comment by andrixnet** [comment]
I did that. Followed all instructions. Installed aLogcat, rebooted, started c:geo, activated debug...

**Comment by Lineflyer** [comment]
Did you gice aLogcat root rights?
You could also try other apps available on GooglePlay for logging or check aLogcat whether it has some setting for root access.

**Comment by andrixnet** [comment]
I haven't been able to locate any setting for root in it. It did not ask for root rights.
I got alogcat by Jeffrey Blattman, same as sugested in the wiki.

I will try another app and get back to you.

On 31 March 2016 10:22:44 EEST, Lars <notifications@github.com> wrote:
>Did you gice aLogcat root rights?
>You could also try other apps available on GooglePlay for logging or
>check aLogcat whether it has some setting for root access.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5473#issuecomment-203794142

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by SammysHP** [comment]
aLogcat doesn't work anymore for me (already for 1-3 years). Last time I used [Logcat](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat).

**Comment by andrixnet** [comment]
In that case this page https://github.com/cgeo/cgeo/wiki/Send-log-to-developers needs to be updated.

**Comment by andrixnet** [comment]
This is the log as recorded by catlog app. 
I held only lines containing "cgeo". 

[2016-03-31.txt](https://github.com/cgeo/cgeo/files/198022/2016-03-31.txt)
[device_info.txt](https://github.com/cgeo/cgeo/files/198019/device_info.txt)

This shows one attempt with wrong credentials, followed by one attempt with correct credentials.

**Comment by Lineflyer** [comment]
The log still does only contain some system messages but not the debug messages created by c:geo itself. Strange. Let me check later on with my rooted device and the mentioned apps.

Afterwards we may adapt the Wiki page accordingly.

**Comment by Lineflyer** [comment]
I did now user [Catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat) on my rooted device.
Without giving the app root rights it shows a toast stating this....so if this is the case it should show it to you on first start app.
For me my superuser app (Cyanogenmod 13) then popsup and asks if I want to grant root rights to this app. After answering yes, I do see the log without a problem.

**Comment by andrixnet** [comment]
I have another phone, Huawei P7 with Android 4.4.2 and it works. 
On my Allview P5 (same as XOLO 800) with Android 4.2.1 it doesn't. I also tried the nightly non-JIT build. 
I will try other log reading apps. (maybe my device has a ROM with some logging features disabled?)

**Comment by Lineflyer** [comment]
@andrixnet Any success in getting a log or can we close this issue?

**Comment by andrixnet** [comment]
Still unable to login to geokrety from c:geo, including after the recent update. 
I have the geokrety logger app working though. 

There are still some other ways I want to try to obtain a system log. 
Meanwhile, would a packet log (captured with tcpdump) be useful?

**Comment by kumy** [comment]
For me the problem should be the ssl certificate chain at geokrety.org which isn't trusted on older devices. In https://github.com/cgeo/cgeo/issues/5473#issuecomment-188458604 I proposed to disable SSL for older devices. Should we prefer functionality over security?

https://www.ssllabs.com/ssltest/analyze.html?d=geokrety.org&hideResults=on

**Comment by andrixnet** [comment]
Results show A- which is a pretty good grade for SSL.

I understand there may be a problem for Android 2.3 devices, considering the history of SSL in recent years, however :
My problem happens using a device with Android 4.2.1... 

I'm not sure how much of GeoKrety Logger code was shared with c:geo (I've been collaborating with it's author for translation and testing), and how it does the auth on geokrety, but this app works for me on the same device, while geokrety inside c:geo does not.

**Comment by kumy** [comment]
I'm quiet sure GeoKretyLogger doesn't use SSL. I'll have a look at code.

On September 1, 2016 11:47:22 AM GMT+02:00, andrixnet <notifications@github.com> wrote:
>Results show A- which is a pretty good grade for SSL.
>
>I understand there may be a problem for Android 2.3 devices,
>considering the history of SSL in recent years, however :
>My problem happens using a device with Android 4.2.1... 
>
>I'm not sure how much of GeoKrety Logger code was shared with c:geo
>(I've been collaborating with it's author for translation and testing),
>and how it does the auth on geokrety, but this app works for me on the
>same device, while geokrety inside c:geo does not.
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5473#issuecomment-244030425

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
I've have checked GKLogger code, and I can now confirm they are not using SSL at all for accessing GeoKrety.org service (https://sourceforge.net/p/geokretylog/code/HEAD/tree/trunk/src/pl/nkg/lib/gkapi/GeoKretyProvider.java#l54) even for authentication :'(

That explain why it's still working on older devices.

**Comment by kumy** [comment]
It can be easy to add an (advanced) option in GK service settings to "force disable SSL usage". Doing so, user will know his credentials are send in clear text over the net. That is IMO a good compromise over security / feature and doing things on behalf of the user. What do you think?

**Comment by andrixnet** [comment]
IMO is just fine. 
Geokrety website by default presents a non-SSL login page as well: 
type geokrety.org, go to login and you are here: http://geokrety.org/longin.php 
A plain and simple page.

**Comment by samueltardieu** [comment]
Would not it be much better to tell the geokrety people to fix their certificate chain by putting the intermediate certificate before the site certificate? As shown by https://www.ssllabs.com/ssltest/analyze.html?d=geokrety.org&hideResults=on they don't use the right order.

**Comment by kumy** [comment]
> fix their certificate chain by putting the intermediate certificate before the site certificate? As shown by https://www.ssllabs.com/ssltest/analyze.html?d=geokrety.org&hideResults=on they don't use the right order

Damned, how could I have missed that! I'll ping @filipsPL

**Comment by andrixnet** [comment]
If that is the problem and solution, then it would be great. 
Hope it works, I haven't been able to get in touch the the people behind GK this year for some opencaching.ro related stuff :(

**Comment by filipsPL** [comment]
Sorry for that issue, should be OK now:
> Chain issues: 	None

https://www.ssllabs.com/ssltest/analyze.html?d=geokrety.org&hideResults=on

**Comment by kumy** [comment]
@andrixnet may you please, check the behavior, with the updated configurations from geokrety.org?
@filipsPL Thanks!

**Comment by prmtl** [comment]
I had the issue with geokrety.org and now, after changes to the ssl certificates it works like a charm - I'm able to authenticate within application again. Awesome!

**Comment by kumy** [comment]
@prmtl Thanks.

Let's close.

**Comment by andrixnet** [comment]
I have successfully authorized geokrety in c:geo.
Thanks to the c:geo and geokrety team for the help.
