### ISSUE TITLE
Translation missing in current RC version

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5474]
The current RC is at least missing one string (i.e. string name="cache_found_last_30_days") and I cant find it on crowdin either. Outdated upload or problem with the branching?

@rsudev

**Comment by Lineflyer** [comment]
Missing strings have been uploaded to Crowdin by @rsudev 
Issue will be closed once translations are downloaded to Github.

**Comment by rsudev** [comment]
@Lineflyer OK to close now?

**Comment by Lineflyer** [comment]
Sure
