### ISSUE TITLE
New default page on geocaching.com test phase 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5475]
According to the latest Groundspeak release notes they are conducting a test where 50% od users do receive the search view as landing page (when logged in) instead of the default page.

I am wondering if this has any consequences for c:geo.
Can all of you check what page you receive when opening http://www.geocaching.com and if you have the new behaviour do some smoke tests with your account in c:geo?

Not sure however if this test is bound to 50% of users or 50% of calls to the URL...

**Comment by kumy** [comment]
Normal page for me.

On February 23, 2016 10:01:32 PM GMT+01:00, Lars <notifications@github.com> wrote:
>According to the latest Groundspeak release notes they are conducting a
>test where 50% od users do receive the search view as landing page
>(when logged in) instead of the default page.
>
>I am wondering if this has any consequences for c:geo.
>Can all of you check what page you receive when opening
>http://www.geocaching.com and if you have the new behaviour do some
>smoke tests with your account in c:geo?
>
>Not sure however if this test is bound to 50% of users or 50% of calls
>to the URL...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5475

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rsudev** [comment]
For me as well. If anybody lands on the new page, please take note of the url to better understand what they are doing.
In general I don't see a big issue here for us. AFAIK we do not use the entry page and call all others specifically.

**Comment by samueltardieu** [comment]
Home page.

**Comment by UniQP** [comment]
For me https://www.geocaching.com/ redirects to https://www.geocaching.com/play/search .

**Comment by Lineflyer** [comment]
@UniQP DId you see any problems while using c:geo since this is the case?

**Comment by Lineflyer** [comment]
BTW: 
If I open the website on a mobile browser I do now see a dedicated mobile homepage (with sliding sidebar). May it be wise to remove the "Identify as Android browser" option?

**Comment by UniQP** [comment]
@Lineflyer Unfortunately, I have no possibility to test c:geo. However, I noticed the change since today, so maybe it just wasn't active when you opened the pull request, and some of the other developers now also sees the redirect.

**Comment by Lineflyer** [comment]
When opening the homepage I do only see some appended stuff in the URL (e.g. `?utm_expid=3682814-52.M5jt3yuaSgKdQuFyd_YmNQ.0`) but still only the homepage.

**Comment by Lineflyer** [comment]
No problems reported up to now on support or FB. Closing for now.
