### ISSUE TITLE
Locally changed coords replaced by listing coords on refresh

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5476]
###### Detailed steps causing the problem:
- Open a saved cache
- Create a waypoint, select to change coords locally to listing coords
- Refresh the cache
###### Actual behaviour after performing these steps:

The local change is lost and replaced again by the listing coords retrieved during refresh
###### Expected behaviour after performing these steps:

As the user defined change was done, it is not correct that this data is lost by refreshing. 
Not all users will understand this in beforehand and loss of data will appear.
###### Version of c:geo used:

2016.02.23-RC
###### Is the problem reproducible for you:

Yes
###### Attach system information if available (see c:geo menu -> About c:geo -> System):

Not relevant
###### Other comments and remarks:

Follow up of #5439 

Comment by @blochi79:
Now we have a follow problem. ;-( The local header coordinates are overwritten if the cache is refreshed. The method for refreshing a cache needs also to be adapted for the case that the local header coordinates have been corrected. Then the original coordinates in waypoints must be updated with the Listing coordinates instead of the header coordinates.
[...]
I often perform bulk refresh of mixed lists that contains also traditional caches. In this case I don't want to lose the corrected coordinates of letterbox or Wherigo caches. I did not know that it is the default behavior of c:geo to overwrite the local corrected coordinates with the listing coordinates. I think the current issue can be closed and the behavior of overwriting corrected coordinates while refreshing a cache may be discussed as subject of another issue. Sorry for the confusion.

**Comment by pstorch** [comment]
For this we have to check the `coordsChanged` field of the cache and keep it. We then would have to look for the WP of type `original` and update the newly received header coords there (they are not updated currently).

But what if the user has also changed the header coords on the server? Then we have a conflict: locally changed and server changed!

**Comment by Lineflyer** [comment]
@pstroch Is this somehow affected/changed in behaviour by the new separation of user defined and server waypoints we do now have implemented?

**Comment by pstorch** [comment]
@Lineflyer yes, we won't allow changing coords of server defined waypoints. Only if the server defined waypoint doesn't have coords.

**Comment by pstorch** [comment]
Ah, wait. This is for changed header coords. Let me think.

**Comment by pstorch** [comment]
This is still the case.
We could preserve the locally changed coords as long as the server coords are not overwritten by the user as well. Because then we would have a conflict and can't decide which one to use.
