### ISSUE TITLE
Map not appearing on Cache Details view

### ISSUE THREAD

**Issue by JGrouchy** [cgeo/cgeo#5479]
###### Detailed steps causing the problem:
- When I open a cache in c:geo, the map view that typically appears on the 'Details' tab no longer loads.
- Refreshing does not solve the problem

###### Version of c:geo used:
2016.02.03

###### Is the problem reproducible for you:
Yes

###### Attach system information if available (see c:geo menu -> About c:geo -> System):
```
--- System information ---
Device: LGLS990 (g3_spr_us, lge)
Android version: 5.0.1
Android build: LRX21Y
Cgeo version: 2016.02.03
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by kumy** [comment]
I'm unable to reproduce on master Android 6.0.1

**Comment by samueltardieu** [comment]
Isn't this a quota exceeded problem? Did you a mass refresh shortly before
for a chance?

**Comment by JGrouchy** [comment]
I didn't do anything different before or after.  Just opened it as usual.  One day the maps showed...the next they did not.

**Comment by Lineflyer** [comment]
You might also have deactivated the option Settings -> Offline-date -> Static Maps ?

**Comment by Lineflyer** [comment]
@JGrouchy 
DId you check that setting?

As written by @samueltardieu: Are you sure you did not batch refresh some caches (in which case you could easily exceed your daily quota on Googles static map server).

**Comment by Lineflyer** [comment]
@kumy: 
Thanks for the new label, nice idea.

**Comment by kumy** [comment]
@Lineflyer I must admit, I've seen it on pull requests. Rewards comes to @samueltardieu :)

**Comment by JGrouchy** [comment]
That setting was not deactivated and I did not batch refresh.  No anomalous activity...just my typically day-to-day usage.  It actually resolved itself...then happened again on and off over the last couple of days.

**Comment by SammysHP** [comment]
It might be a shared IP. Not sure how that is handled by Google.

**Comment by Lineflyer** [comment]
This is probably a problem in accesibility of Google static maps server.
Plese feel free to reopen if a systematic problem shows up or the bug stays reproducible.
