### ISSUE TITLE
Line feeds missing for own logs in logbook view after posting it

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5491]
2016.02.27-RC:

- Open a cache
- Compose log which contains some line feeds and empty lines between each test block
- Send the log
- Go to the logbook tab

The log is shown but missing all line feeds. Only after refreshing the cache (thus getting the log from the server) it is shown in a normal way.

**Comment by kumy** [comment]
I'm not sure we can do something for that, as it's rendered without line feeds at geocaching.com

This is how GC render the log which was with 3 empty lines between text.
```
<span id="ctl00_ContentBody_LogBookPanel1_LogText"><p>Test</p>
<p>Test2</p>
<p>Test3</p>
<p>Cgeo</p>
</span>
```

Closing. Feel free to reopen if you disagree.

**Comment by Lineflyer** [comment]
@kumy 
You understood this wrong.
I am not talking about data from server but about the log book view immediately after posting the log online, in which case we insert the log manually into the logbook in c:geo.

So the problem is there after posting the log and will be corrected once the cache is refreshed.

**Comment by kumy** [comment]
You're right, I've understood it in the opposite. Sorry for the noise.

**Comment by Bananeweizen** [comment]
I cannot reproduce this. I just posted logs like

```
line 1

line 3
```
or

```
some text with 2 empty


lines in between
```
and those were shown perfectly fine afterwards in my local log view.

**Comment by Bananeweizen** [comment]
not reproducable for me. I posted this note to one of Lineflyers caches
```
line 1

line 3
```
and that was shown exactly the same in my local view.

**Comment by rsudev** [comment]
When following the example of @Bananeweizen I get the same result (linefeeds preserved in local view as entered).
Could you post a more detailed counter-example?

**Comment by kumy** [comment]
Post:

```
line 1


line 4
```

At the log tab, the appear exactly as posted.
Then refresh the cache.
GC.com removed the 'line3' and log now appear as:

```
line 1

line 4
```

**Comment by Lineflyer** [comment]
@kumy That is for me only cosmetic.

@Bananeweizen @rsudev 
I should have been more detailed when posting the original issue... I tried to reproduce but also failed. I did also crosscheck the 14 caches I logged with c:geo yesterday and those are also OK.
So I am sure this happened, but cannot reproduce right now. 

Closing until I get a clue on this.

**Comment by kumy** [comment]
I agree this is cosmetic. (I'm still able to reproduce)
