### ISSUE TITLE
Problems with "Nearby" sorting 

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#5497]
Since some days sorting in "Nearby" list by "Date Hidden" does not work correctly anymore.
Caches that are not saved (and premium caches if you are a basic member) are always sorted as "newest".

###### Detailed steps causing the problem:
- Open "Nearby" list
- Load more caches until you have "Not stored" entries in your list
- Sort by "Date Hidden"

###### Actual behaviour after performing these steps:
The "Not stored" entries appear as newest entries even if there are newer stored entries in the list.

###### Expected behaviour after performing these steps:
All entries are sorted by "Hidden Date" regardless if they are already stored in c:geo or not.

###### Version of c:geo used:
Latest nightly build: 2016.03.03-NB-46936b1

###### Is the problem reproducible for you:
Yes, since a few days. Might be caused by geocaching.com changes since I am almost sure that I didn't update c:geo in between.

Attach system information if available (see c:geo menu -> About c:geo -> System):
--- System information ---
Device: D5503 (D5503, Sony)
Android version: 5.1.1
Android build: 14.6.A.1.236
Cgeo version: 2016.03.03-NB-46936b1
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE (cgeo forced to English)
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / BASIC
Installed cgeo plugins: none
--- End of system information ---

**Comment by rsudev** [comment]
I can confirm that there is something amiss here, even though the search result on the page looks fairly innocuous.

**Comment by rsudev** [comment]
That's the new html in question:
```
<td style="width:70px" data-dateplaced="01/28/2016">
    <span class="small">2016-01-28</span>
</td>
```
I might try a simple pattern adaption, but it looks promising to possibly have the date in a setting-independent format.

**Comment by Matze2** [comment]
This looks good and plausible. Thanks!
Will try with the next NBs.

**Comment by Matze2** [comment]
With 2016.03.04-NB-d8a3db9 sorting works again. Thank you very much!
