### ISSUE TITLE
"Nearby" list sometimes forgets number of caches loaded (truncates to 40 entries)

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#5498]
This is another one which is a little bit annoying if you want to explore "Nearby" caches with c:geo.
This issue exists since a long time.
###### Detailed steps causing the problem:
- Open "Nearby" list
- Load at least 60 caches in the list
- Select one entry to see the details
- Go back
###### Actual behaviour after performing these steps:

List shows only 40 caches and not the original list.
If you select an entry again to see the details and go back you might get back to the original number of entries.
###### Expected behaviour after performing these steps:

The already loaded list is always kept and not truncated to 40.
###### Version of c:geo used:

Latest NB.
###### Is the problem reproducible for you:

Yes, almost always.
###### Attach system information if available (see c:geo menu -> About c:geo -> System):

Device: D5503 (D5503, Sony)
Android version: 5.1.1
Android build: 14.6.A.1.236
Cgeo version: 2016.03.03-NB-46936b1
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE (cgeo forced to English)
Geocaching sites enabled:
geocaching.com: logged in (Login OK) / BASIC Installed cgeo plugins: none 
--- End of system information ---

**Comment by Lineflyer** [comment]
Confirmed (also happening with 2016.03.03-RC)

**Comment by Matze2** [comment]
Now that I am slowly getting warm with the Android development tool chain I tried to debug this issue.

Since I am not able to work on that topic in the next days I just want to share my findings. Unfortunately with the current knowledge I am not able to judge what is correct or not. So here are just the facts for now.

Starting with clicking on "Load more caches" the LoaderManager of CacheListActivity contains two loaders: CoordsGeocacheListLoader and NextPageGeocacheListLoader.
After the first "Load more caches" they point to the identical search result. This seems correct to me.

With the second click on "Load more caches" the NextPageGeocacheListLoader gets restarted (CacheListActivity:1523) and as a consequence a new instance replaces the old one.

Now after having loaded 60 caches enter one cache (this is what happens to me by accident when I miss the "Load more caches" button and this makes this issue so annoying) and go back to the list.

Going back calls start() for all loaders (LoaderManager.doStart()) and because the list is iterated with reverse order NextPageGeocacheListLoader is called first and CoordsGeocacheListLoader is called second. And because CoordsGeocacheListLoader contains an old search object with 40 entries, this old list is shown.

My guess is that both loaders should always refer to the same search object, or the CoordsGeocacheListLoader must be deactivated or removed from the loader manager or ...

That*s is for now. Maybe somebody sees immediately what is wrong now. I will also continue my research.

**Comment by Matze2** [comment]
Ok. Just gave it a try an destroyed the CoordsGeocacheListLoader as soon as the NextPageGeocacheListLoader takes over an this seems to fix the problem.

My CacheListActivity.MoreCachesListener now looks like this:

```
    private class MoreCachesListener implements View.OnClickListener {

        @Override
        public void onClick(final View arg0) {
            showProgress(true);
            showFooterLoadingCaches();

            getSupportLoaderManager().restartLoader(CacheListLoaderType.NEXT_PAGE.getLoaderId(), null, CacheListActivity.this);
            if (type == CacheListType.NEAREST) {
                getSupportLoaderManager().destroyLoader(CacheListType.NEAREST.getLoaderId());
            }
        }
    }

```

**Comment by Matze2** [comment]
Ok. After having the debug APK running for a couple of days I pushed the branch for review.
Feedback welcome since this is my first serious dealing with Android Studio, gradle, git and github (up to now I worked with Eclipse, maven and svn).

To check the behavior before and after place breakpoints in
- LoaderManager.doStart()
- AbstractSearchLoader.loadInBackground()

Repeat the steps according to the issue description and you will see that two loaders are called - NextPageGeocacheListLoader and CoordsGeocacheListLoader - with different SearchResult objects. CoordsGeocacheListLoader with an outdated search object usually wins and therefore the Nearby list falls back to 40 entries after coming back from a selected cache.

The fix removes the CoordsGeocacheListLoader as soon as the NextPageGeocacheListLoader takes over. Therefore no conflict anymore.

**Comment by Matze2** [comment]
Now it should be ok.

**Comment by pstorch** [comment]
@Matze2 do you want to send a PR for this change?

**Comment by Matze2** [comment]
It's not that urgent. Should I wait after the release?

**Comment by pstorch** [comment]
It's easier to review if we have a PR. And if it's fine it can be merged to `master` without interfering `release`.

**Comment by Matze2** [comment]
Ok. I think I need to redo the branch from scratch. Somehow I completely screwed it up. At least when I look in the commit history in github.
It started when I fixed the commit message using "--amend" and forgot that I had another file in staging which also was added then. 
The local git log looks good but remote 👎 .
Never mind. I'll do everything from scratch and create a PR.
