### ISSUE TITLE
Nightly Build: unable to install for days

### ISSUE THREAD

**Issue by msebald** [cgeo/cgeo#5499]
###### Detailed steps causing the problem:
- downloaded the nightly build apks for at least 5 days now
- tried to install these builds
- installation did not work, I get "App wurde nicht installiert", that's it, no further information visible

###### Version of c:geo used:
The current nightly builds, tried for at least 5 days

###### Is the problem reproducible for you:
Yes

###### Other comments and remarks:
- all other apps, doesn't matter if from Play Store, F-Droid or manual install with the apk work on my device

**Comment by SammysHP** [comment]
Which device do you have? Can you post a system log after the installation attempt?

**Comment by msebald** [comment]
OnePlus One on the latest official CM build, rooted.

Sure I can post a log. Where do I find it?

**Comment by SammysHP** [comment]
Either

```
$ adb logcat
```

from your computer or with https://play.google.com/store/apps/details?id=com.nolanlawson.logcat

**Comment by msebald** [comment]
Thanks! :-)

`03-03 14:05:24.240 I/ActivityManager(823): START u0 {dat=file:///storage/emulated/0/Download/cgeo-nightly(1).apk cmp=com.android.packageinstaller/.InstallAppProgress (has extras)} from uid 10068 on display 0
03-03 14:05:24.292 W/InstallAppProgress(30124): Replacing package:cgeo.geocaching
03-03 14:05:24.501 D/DefContainer(30153): Copying /storage/emulated/0/Download/cgeo-nightly(1).apk to base.apk
03-03 14:05:25.328 D/PackageManager(823): Renaming /data/app/vmdl295018557.tmp to /data/app/cgeo.geocaching-1
03-03 14:05:25.340 I/ActivityManager(823): Force stopping cgeo.geocaching appid=10143 user=-1: uninstall pkg
03-03 14:05:25.537 I/PackageManager(823): Package cgeo.geocaching codePath changed from /data/app/cgeo.geocaching-2 to /data/app/cgeo.geocaching-1; Retaining data and using new
03-03 14:05:25.537 W/PackageManager(823): Package cgeo.geocaching desires unavailable shared library com.sec.android.app.multiwindow; ignoring!
03-03 14:05:25.558 W/PackageManager(823): Package couldn't be installed in /data/app/cgeo.geocaching-1
03-03 14:05:25.558 W/PackageManager(823): com.android.server.pm.PackageManagerException: Can't install because provider name com.google.android.gms.measurement.google_measurement_service (in package cgeo.geocaching) is already used by de.gelbeseiten.android
03-03 14:05:25.699 W/PackageManager(823): Package cgeo.geocaching desires unavailable shared library com.sec.android.app.multiwindow; ignoring!
03-03 14:05:25.879 I/PackageManager(823): Successfully restored package : cgeo.geocaching after failed upgrade
03-03 14:05:27.453 I/InstallAppProgress(30124): Finished installing cgeo.geocaching`

**Comment by SammysHP** [comment]
> Can't install because provider name **com.google.android.gms.measurement.google_measurement_service** (in package cgeo.geocaching) is already used by de.gelbeseiten.android

Just uninstall Gelbe Seiten. ;)

No, I wonder where the provider comes from. IMHO it's a more complex issue because not only c:geo exports it unintentionally, but Gelbe Seiten does exactly the same. Might be a bug in one of the Google dependencies.

**Comment by msebald** [comment]
I tried and uninstalled Gelbe Seiten. And was able to install/upgrade c:geo. Now I cannot install/restore via Titanium Backup the Gelbe Seiten app anymore. No surprise there.

Well, now what? You will run into this problem for many people as soon as a new stable version will be released to the Play Store.

**Comment by mucek4** [comment]
We are not the only one https://github.com/kotmyrevich/analytics-issues/issues/784

**Comment by SammysHP** [comment]
So we just need to add

```
android {
    defaultConfig.applicationId = "cgeo.geocaching"
}
```

to our gradle file?

**Comment by rsudev** [comment]
Sounds sufficiently easy. So we would need 'gelbe seiten' to cross-check. Release is likely affected as well.

**Comment by Lineflyer** [comment]
Reopening for Fieldtest.
@msebald Please kindly report back if you can now install both.
I also have one user on FB "c:geo Fangruppe" with installation problems. I asked her to test the freshly build RC-version once again.

**Comment by Lineflyer** [comment]
Confirmed by FB-user that the new 2016.03.03-RC version is installing without a problem

**Comment by msebald** [comment]
After installing todays nightly build I was able to restore Gelbe Seiten via Titanium Backup.
