### ISSUE TITLE
Support all OpenCaching URLs

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5508]
This works:
- https://opencaching.de/OC10DA9

This does not work:
- https://www.opencaching.de/viewcache.php?wp=OC10DA9
- https://www.opencaching.de/viewcache.php?cacheid=172122

**Comment by kumy** [comment]
This should already work, SSL should be the problem.
https://github.com/cgeo/cgeo/blob/master/main/AndroidManifest.xml#L422-L436

**Comment by kumy** [comment]
BTW, the first link doesn't work for me (c:geo not proposed)

**Comment by kumy** [comment]
Seems to work on `release` but not on `master`

**Comment by kumy** [comment]
Ok, my links were broken (always containing SSL).
For me just adding a new supported scheme for OC site with support them should be sufficient.
