### ISSUE TITLE
Twitter: Needed revalidation not detected

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5512]
###### Detailed steps causing the problem:
- For some reason (maybe as I used c:geo on several devices and authorized them) Twitter denies posting a tweet via the API
- This seems to be indicated by a 403 error (see attached log

###### Actual behaviour after performing these steps:
No special UI indication.
Twitter still shown as authorized in settings

###### Expected behaviour after performing these steps:
This should be detected (if possible), the user notified and the stored authorization should be revoked

###### Version of c:geo used:
2016.02.03

###### Is the problem reproducible for you:
Yes (under the mentioned conditions)

###### Other comments and remarks:
Log:
```
22:09:15.248 Warning cgeo 7216  [AsyncTask #5] 403 [Forbidden] (403 ms) POST https://api.twitter.com/1.1/statuses/update.json
22:09:15.248 Error cgeo 7216  [AsyncTask #5] Tweet could not be posted. Reason: HTTP/1.1 403 Forbidden [cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0, content-disposition: attachment; filename=json.json, content-type: application/json;charset=utf-8, date: Sun, 06 Mar 2016 21:09:15 GMT, expires: Tue, 31 Mar 1981 05:00:00 GMT, last-modified: Sun, 06 Mar 2016 21:09:15 GMT, pragma: no-cache, server: tsa_o, status: 403 Forbidden, strict-transport-security: max-age=631138519, x-access-level: read-write, x-connection-hash: b19230bade95cc6affd2b3181485e2af, x-content-type-options: nosniff, x-frame-options: SAMEORIGIN, x-response-time: 136, x-transaction: baed1ecc1b734226, x-tsa-request-body-time: 0, x-twitter-response-tags: BouncerCompliant, x-xss-protection: 1; mode=block]
```

**Comment by Lineflyer** [comment]
Don't take this as verified...at the moment Twitter reacts quite strange.
Although I reauthorized after experiencing this issue I keep getting 403.

**Comment by samueltardieu** [comment]
That may be linked to #5507.

**Comment by samueltardieu** [comment]
Closing as Twitter signature handling has been rewritten in master. Open a new one if the problem happens in master again.
