### ISSUE TITLE
Can no longer select text on cache page.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#5516]
On my Nexus 7 running 4.1.2 I can no longer select text from the cache page  for translation/copying.
If I long-press on text in the cache page, nothing happens.
However, if I long-press on the hint text, or on log entries, the two blue arrows appear and I can select that text as expected.

Note that it works fine on my Xperia Z3 running 5.1.1

###### Detailed steps causing the problem:
- Step 1
Use a Nexus 7 running 4.1.2
- Step 2
Open a cache page
- Step 3
Long-press on some text on the cache page.

###### Actual behaviour after performing these steps:
Nothing.
###### Expected behaviour after performing these steps:
I expect to be able to select text for translation / copying.

###### Version of c:geo used: 

2016.02.03

###### Is the problem reproducible for you:
Yes

###### Attach system information if available (see c:geo menu -> About c:geo -> System):
```
--- System information ---
Device: Nexus 7 (nakasi, google)
Android version: 4.1.2
Android build: JZO54K
Cgeo version: 2016.03.06
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (default state)
System language: en_GB
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
```

###### Other comments and remarks:
Works fine under android 5.1.1

**Comment by rsudev** [comment]
Sounds like the same issue as #5471, but we were not aware that it also affects Android 4.x

**Comment by alan666notb** [comment]
Note that in the previous version of cgeo, it worked properly under 4.1.2,
i.e. a long press on the cache page would select all the text on the page for copying.

**Comment by rsudev** [comment]
I know. It was one of the features of this version to allow partial selection of the description, which apparently broke it for some more versions of Android as expected.

**Comment by alan666notb** [comment]
But it works on the hint - the two blue arrows appear there and the text can be part selected, so the functionality is obviously available under 4.1.2.
On log entries the two blue arrows don't appear butthe entire text of an entry is copied.

**Comment by rahu** [comment]
Working on the hint but not on the description? Strange..

Can you give more information's about the cache(s) you used for testing? Is it the same for all caches or only for those with HTML descriptions?  Can you test the description from GC67B56? Also please test with a nightly build. Maybe this is related to #5490

**Comment by alan666notb** [comment]
Tried it on GC67B56, same result - cache page does nothing / hint works with blue arrows / logs select entire text of a single log entry.

I don't know how to run a "nightly build", can you point me in the right direction?

**Comment by kumy** [comment]
@alan666notb Nightly builds could be downloaded from http://www.cgeo.org/development.html. You have to allow "Unknown sources" from `System Settings`  -> `Security`

**Comment by alan666notb** [comment]
Downloaded 2016.03.08-NB-23d7229, exactly the same result.

**Comment by kumy** [comment]
Reproducible on Android Emulator 4.1.2

logcat show
`
03-08 22:48:33.983    1526-1526/cgeo.geocaching W/TextView﹕ TextView does not support text selection. Action mode cancelled.`

**Comment by kumy** [comment]
Bisecting show commit `5449a1d2` as the fist commit who introduce the message `TextView does not support text selection. Action mode cancelled.`

#3819: make description text selectable

If someone will go further...

**Comment by rahu** [comment]
But selection is working for the hint? It's also only a text view...?

Am 8. März 2016 22:50:33 MEZ, schrieb kumy <notifications@github.com>:
>Reproducible on Android Emulator 4.1.2
>
>logcat show
>`
>03-08 22:48:33.983    1526-1526/cgeo.geocaching W/TextView﹕ TextView
>does not support text selection. Action mode cancelled.`
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5516#issuecomment-193982591

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rahu** [comment]
I'll look at this. Should be possible to get the old behaviour back on this devices. 

Am 9. März 2016 00:50:53 MEZ, schrieb kumy <notifications@github.com>:
>Bisecting show commit `5449a1d2` as the fist commit who introduce the
>message `TextView does not support text selection. Action mode
>cancelled.`
>
>#3819: make description text selectable
>
>If someone will go further...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5516#issuecomment-194028538

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Lineflyer** [comment]
Marked as "Assigned-non-collab" as @rahu is working on it.

**Comment by rahu** [comment]
After hours of debugging into the Android sources I now understand why it is not working an API 16...

```
--- a/android-16/android/text/method/LinkMovementMethod.java
+++ b/android-22/android/text/method/LinkMovementMethod.java
@@ -36,6 +36,11 @@ public class LinkMovementMethod extends ScrollingMovementMethod {
     private static final int DOWN = 3;
 
     @Override
+    public boolean canSelectArbitrarily() {
+        return true;
+    }
+
+    @Override
     protected boolean handleMovementKey(TextView widget, Spannable buffer, int keyCode,
             int movementMetaState, KeyEvent event) {
         switch (keyCode) {
```
this is needed to get `http://www.programcreek.com/java-api-examples/index.php?source_dir=android-15-master/android/widget/TextView.javaTextView::textCanBeSelected` returning true, which is the needed in `Editor::prepareCursorControllers` to get `mSelectionControllerEnabled=true`. With this `Editor::canSelectText ` returns true and this is needed in `Editor::startSelectionActionMode`:

```
  if (!canSelectText() || !mTextView.requestFocus()) {
            Log.w(TextView.LOG_TAG,
                    "TextView does not support text selection. Action mode cancelled.");
            return false;
        }
```

**Comment by kumy** [comment]
@alan666notb could you please try the latest Nightly Build?

**Comment by alan666notb** [comment]
Downloaded 2016.03.10-NB-da0060c and the selection on both the main cache page and the hint now works - i.e. you get the two blue arrows.

Log entries still work but select the entire text of an entry, you don't get the two blue arrows.

BTW, it would be nice if you could also select the caption text on images

**Comment by SammysHP** [comment]
Great! This was never implemented for logs which should be a new issue.

**Comment by rahu** [comment]
And also for trackables description... But before this we should solve this issue on android 2.3  #5471

Am 10. März 2016 20:22:58 MEZ, schrieb SammysHP <notifications@github.com>:
>Great! This was never implemented for logs which should be a new issue.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5516#issuecomment-195008563

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by kumy** [comment]
@alan666notb Thanks for the feedback
@rahu Thanks for your work
