### ISSUE TITLE
Selection on Cache description does not provide "translation" menu

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5517]
###### Detailed steps causing the problem:
- Open cache GC5ZZZZ
- Slide to description tab
- Long press to activate selection
- Contextual Popup menu appear

###### Actual behaviour after performing these steps:
The contextual menu display "copy/share/select all"

###### Expected behaviour after performing these steps:
The contextual menu should propose "Share / Translate to English / ... [-> "copy/share/select all"]"

###### Version of c:geo used:
2016.03.06

###### Is the problem reproducible for you:
Yes

###### Attach system information if available (see c:geo menu -> About c:geo -> System):
```
--- System information ---
Device: LG-D855 (g3_global_com, lge)
Android version: 5.0
Android build: LRX21R.A1445306351
Cgeo version: 2016.03.06
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR
Geocaching sites enabled:
- geocaching.com: logged in (Connecté) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
```

###### Other comments and remarks:
Works "**most**" of the time on my phone (Android 6.0.1)

```
--- System information ---
Device: m8 (cm_m8, htc)
Android version: 6.0.1
Android build: cm_m8-userdebug 6.0.1 MMB29U 1921d5ed9d test-keys
Cgeo version: 2016.03.06-223b663 developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: none
--- End of system information ---
```

**Comment by kumy** [comment]
On my phone:

Behavior 1:
- long press to select a work -> contextual menu show "Translate..."
- without closing the context menu, long press on another word -> contextual menu show "Copy..."

-> Expected for the second selection -> contextual menu should show "Translate..."

Behavior 2:
- long press to select a work -> contextual menu show "Translate..."
- tap somewhere to close the contextual menu
- long press to select a work -> contextual menu show "Translate..."

**Comment by kumy** [comment]
On another phone:
```
--- System information ---
Device: GT-I9305 (m3xx, samsung)
Android version: 4.4.4
Android build: cm_i9305-userdebug 4.4.4 KTU84Q b439e38a45 test-keys
Cgeo version: 2016.03.08-NB-23d7229
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR
Geocaching sites enabled:
- geocaching.com: logged in (Connecté) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
```

1. The contextual menu is not "floating", but displayed "on" the action bar (not a problem)
2. In both cases, the good workflow on contextual menu is shown (however, when it is displayed at the action bar level, "Copy" menu appear first and "Translate" is in submenu ; not really a problem too)

**Comment by Lineflyer** [comment]
On my Samsung S4 on Android 5.0.1 all is working normal (also after multiple selection changes). 
When long tapping on a new word the context menu is closed automatically...so "Behavior 1" as described above is not applicable.

**Comment by kumy** [comment]
This is a video of "Behavior 1" on "Device: m8 (cm_m8, htc) ; Android version: 6.0.1"
https://www.dropbox.com/s/bjw9c50u2bx2yrq/device-2016-03-08-202233.mp4?dl=0

**Comment by kumy** [comment]
Only "Behavior 1" is fixed at the moment, still have to re-check on friends phone

**Comment by kumy** [comment]
Updated friend's system information

**Comment by kumy** [comment]
Tested on 20160310 nightly, same result.
I've seen an LG overlay (mobile branding) for clipboard on his phone.
I think we may close it as `won't fix`.
