### ISSUE TITLE
Filter (for Found in last 30 days) seems to trigger ANRs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5523]
###### Detailed steps causing the problem:
- People using the filters for found in last 30 days (probably this matches to all filters needing to analyze the logs) report, that filtering a huge list (>1000) leads to an unresponsive device
###### Actual behaviour after performing these steps:

On 1450 caches list the user waited 15min but did only see a blank screen
###### Expected behaviour after performing these steps:

Progress message or faster response
###### Version of c:geo used:

2016.03.06
###### Is the problem reproducible for you:

I can see by own test that the time needed rises with the amount of caches on the list to be filtered, however I did not yet have the time to test huge lists.
###### Attach system information if available (see c:geo menu -> About c:geo -> System):

n/a

**Comment by Lineflyer** [comment]
I retested this with 2016.111.19-NB and still see the unresponsiveness on a list of only 200 caches.

**Comment by Lineflyer** [comment]
Still reproducible with 2019.04.15-NB.
It takes 6 sec to apply this filter on a list of 250 caches on my Samsung S10 (Android 9). During this time the app is unresponsive.

Adding Prio-low label anyway.

**Comment by eddiemuc** [comment]
Should be solved with load limit introduction. Also 
filter will be replaced in-time with an SQL-aware variant.

@Lineflyerr can you verify whether ANR is solved?

**Comment by eddiemuc** [comment]
Should be resolved as stated above, thus I will close. Feel free to reopen if problem still occurs.

Note that fixes in the old filter system will probably no longer carried out. Instead, issue to include missing things into the new filter system should be created.
