### ISSUE TITLE
Attach images to logs not supported for The Opencaching network. Why?

### ISSUE THREAD

**Issue by Opencachingna** [cgeo/cgeo#5525]
Something with OKAPI? File upload size limits on the individual servers?

**Comment by rsudev** [comment]
Not available on OKAPI yet: https://github.com/opencaching/okapi/issues/360

**Comment by Opencachingna** [comment]
Thanks! Close it, if you like. Didn't come up on my search.

**Comment by SammysHP** [comment]
Duplicate of #4137.
