### ISSUE TITLE
Own coords not updated in waypoint screen

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5526]
###### Detailed steps causing the problem:
- Open s saved cache
- Go to the waypoint tab
- Start creating a new waypoint
- Tap on the coords to open the input dialog
- Start moving from your position so that your own coords are changing
- Press the "Own coordinates" button repeatedly to obtain updated coords

###### Actual behaviour after performing these steps:
The coords are never changing in the input dialog,
You have to leave the dialog and open it again to get an update.

###### Expected behaviour after performing these steps:
The button "Own coordinates" should update the fields with the actual coordinates.

###### Version of c:geo used:
2016.03.10-NB (but probably since we introduced the new input dialog)

###### Is the problem reproducible for you:
Yes

**Comment by samueltardieu** [comment]
@Lineflyer Tell me if you want this in `release` after testing on `master`

**Comment by Lineflyer** [comment]
@samueltardieu 
Test and working with 105.03.23-NB
Please include into `release`

**Comment by samueltardieu** [comment]
Merged into `release`.
