### ISSUE TITLE
webcam caches not detected as found

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5527]
Tbc
Sent by mobile

**Comment by rsudev** [comment]
Condirmed. I luckily had a wbcam cache I found not stored on my device. The details view does not show it as found, even though my log is there.

**Comment by Lineflyer** [comment]
Thanks for fixing even before I was able to provide a detailed description ;)

**Comment by Bananeweizen** [comment]
I had changed that code before, so I already knew what to look for when I read your message.
