### ISSUE TITLE
Failed to post release notification

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5534]
I just tried to post a release notification via cgeo/status (which we obviously missed for the current release).
The CI job reports a success but status.cgeo.org does not reflect the update.

Looking into the CI console output I do see:
```
Warning: Couldn't read data from file "/srv/statusSecret", this makes an empty 
```

That is likely the reason.

@samueltardieu

**Comment by kumy** [comment]
@Lineflyer that is caused by the new executors don't having the key.
I'll restrict this job to `master` executor

**Comment by Lineflyer** [comment]
That sounds logical. Please restrict all `Notification` jobs.

**Comment by kumy** [comment]
I just removed the `status-keys` label from "external" executors.
@Lineflyer Please try again.

**Comment by Lineflyer** [comment]
Worked! Thanks @kumy
