### ISSUE TITLE
Cannot move right selection anchor - Cache Description

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5535]
###### Detailed steps causing the problem:
- Open a cache
- Slide to Description tab
- Long press a word
- Try to move right anchor
###### Actual behavior after performing these steps:

The anchor jump to left anchor + 1 character
###### Expected behavior after performing these steps:

The anchor should be freely movable
###### Version of c:geo used:

`2016.03.15-b452a33 developer build`
###### Is the problem reproducible for you:

Yes
###### Attach system information if available (see c:geo menu -> About c:geo -> System):

```
--- System information ---
Device: m8 (cm_m8, htc)
Android version: 5.1.1
Android build: cm_m8-userdebug 5.1.1 LMY48Y a4d1ba3b73 test-keys
Cgeo version: 2016.03.15-b452a33 developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: none
--- End of system information ---
```
###### Other comments and remarks:

Left anchor move well

**Comment by kumy** [comment]
@rahu would you like to hack it? :)

**Comment by rahu** [comment]
I'll try to find the missing workaround... :-/

Am 15. März 2016 17:37:08 MEZ, schrieb kumy <notifications@github.com>:
>@rahu would you like to hack it? :)
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5535#issuecomment-196912394

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rahu** [comment]
https://github.com/Calsign/APDE/issues/9 ... unfortunately they don't have a solution for this :-(

**Comment by Lineflyer** [comment]
I tired to reproduce this on my 5.0.1. device.
For what I can see the right anchor jumps to the left anchor +1 character but afterwards I can freely move it to select text.
@kumy: Is this also your experience or are you never able to move the right anchor to select text?

**Comment by kumy** [comment]
@Lineflyer effectively, after some tries, I can get it "working". In fact the caption zone isn't centered in the bottom part of the anchor, but _just below_.The 2 anchors are affected.
Let's see this video which compare selection in K9 mail and c:geo.
https://www.dropbox.com/s/ys01vlbln2yyczb/device-2016-03-17-220942.mp4?dl=0

**Comment by Lineflyer** [comment]
@kumy 
You are right, same for me. I thought it would be a convenience feature so that my (fat) finger does not cover the selection itself allowing a better targeting.
I am not into the programming details..I thought it would be some android default things we reuse in c:geo but obviously each app needs to implement its own methods?

BTW: Which app do you use to create those videos?

**Comment by kumy** [comment]
@Lineflyer I use `Idea` for that, but that's an `adb` feature
http://developer.android.com/tools/help/shell.html#screenrecord

**Comment by rahu** [comment]
todays debugging ended up in 
```
at android.text.Layout.getLineForVertical(Layout.java:1022)
at android.widget.TextView.getLineAtCoordinate(TextView.java:8895)
at android.widget.TextView.getOffsetForPosition(TextView.java:8875)
at android.widget.Editor$SelectionEndHandleView.updatePosition(Editor.java:3732)
at android.widget.Editor$HandleView.onTouchEvent(Editor.java:3480)
```

There the line for a y-position is calculated - and it's simply on less than the line I've touched. 

In `SelectionEndHandleView.updatePosition` they check if you're trying to move the right anchor before the position of the left (which indeed is true if you moved them one line up). In this case the new position is startHandle + 1. 

I'm not sure why `getLineForVertical` is returning the wrong position, but thats the reason why selection is working fine only for the first line... 
Any ideas?

**Comment by akkatracker** [comment]
I can't reproduce this anymore. @kumy can you?

**Comment by rahu** [comment]
On my phone issue is still existing.

**Comment by Lineflyer** [comment]
Not reprodusible on my Samsung S7 (Android 7.0) with todays NB 2017.03.14.
Can anyone still reproduce? Is this a device related issue or might it have been implicitly solved in the meantime?

**Comment by Lineflyer** [comment]
@kumy Still reproducible for you (see question above)?

**Comment by kumy** [comment]
It's good for me :) Problem has disappeared.

Let's close.
