### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5536]
Just a reminder for me to test this and maybe clean install before retesting.

I noticed today with 2016.03.14-NB that cgeo is laggy in responding to clicks.
Especially after pressing the three dot button in cache details or popup may take a few seconds to open the menu.

**Comment by Bananeweizen** [comment]
Seems not reasonable, looking at the latest commits. I'd suspect this to be a local issue.

**Comment by Lineflyer** [comment]
Well I reinstalled without restoring the DB and the specific problem mentioned above does no longer appear, however c:geo is still laggy in usage.
Might still be my device...I will keep an eye on this and eventually close this issue lateron.

**Comment by Lineflyer** [comment]
I still do see a laggy behaviour.
E.g. open the lists from main menu may take more than a second to open although there are only 10-20 caches on the list.

**Comment by SammysHP** [comment]
Just to confirm this:

> (13:57:57) SammysHP: I have the feeling that the lists in c:geo became slow
(13:58:29) SammysHP: when you open the stored caches from the homescreen it takes almost a second until the list with 5 (!) caches is shown

**Comment by Lineflyer** [comment]
@SammysHP  Can you please check the responsiveness of the three-dot menu while on cache details?
I also have some delayed response there on the first access.

**Comment by SammysHP** [comment]
Not sure if there's a delay. But on my first try, the action bar itself had a short delay (the buttons/menu were missing for a second).

**Comment by Lineflyer** [comment]
I do still have this delays every.
The most noticable delay is when I open the lists coming from the main screen. However I have no clue how to analyze this, at least the log is not showing anything related.

**Comment by pstorch** [comment]
A quick performance analysis when clicking on the **stored** button on the main screen:
![selection_003](https://cloud.githubusercontent.com/assets/5598124/14190198/c08f16b0-f791-11e5-9e26-eb649daa46bb.png)

Looks like `loadSpoilers()` and `loadLists()` are the main cpu-time consumers. The call to `loadLists()` is new, that's for sure. But I'm not sure why we need to load **Spoilers** and **Lists** it at this point in time. I try to understand the `LoadFlags`. Maybe creating a special Select with only the data needed in the CacheListActivity?

**Comment by Lineflyer** [comment]
@pstorch Are you experiencing the delay?

i.e.: There should be a noticable difference between first opening of the list (afer new start of c:geo) and leaving and reopening. (Second access is faster).

**Comment by Lineflyer** [comment]
Is there a way I can use that tool @pstorch used to measure on my device?
Or does this need a special setup?

I can connect the ADB but have no development environment installed.

**Comment by pstorch** [comment]
The delay on my device is not so much, but I think it is faster the second and following times. 
I used the tools available in Android Studio: http://developer.android.com/tools/performance/traceview/index.html#WorkingWithTraceview

**Comment by pstorch** [comment]
@Lineflyer can you check if your sqlite DB contains the index *in_list_geo*?

**Comment by SammysHP** [comment]
It is available in my DB.

(But I noticed that there are many logs from caches that are not stored in the DB. Do we have an issue for that?)

**Comment by samueltardieu** [comment]
Time to add foreign keys and triggers to the database? Those were included in sqlite 3.6.19 and sqlite on SDK 9 is 3.6.22.

**Comment by Bananeweizen** [comment]
Spoilers: https://github.com/cgeo/cgeo/issues/4633#issuecomment-76589042 and I also don't like the fact they are loaded at this time.

Cache list: https://github.com/cgeo/cgeo/pull/5521#discussion_r56459539. Since the symptomes fit what I expected (scanning the complete cachelist table to filter those with the right list_id) I suggest that one of the developers experiencing the issue adds an index and increments the database version locally to compare the time before and after.

**Comment by pstorch** [comment]
Foreign Keys: I like to have them too. Then we could simplify the cleanup of the relationships with "on delete cascade". But then we have to get rid of the customListIdOffset. The ids need to be the same then in both tables. 

The query on the list table takes long because it is a N+1 select problem. For each geocode it selects the lists. For the CacheListActivity this is not necessary, because we search by current list.

**Comment by pstorch** [comment]
I should post my findings here, too.

I replaced the N-Selects of the dbTableCachesLists Table with one select with a where in clause.
Now the main remaining performance issue is loadSpoilers().

![selection_004](https://cloud.githubusercontent.com/assets/5598124/14235016/6cc1be9e-f9f2-11e5-96cb-6b2c32da81a7.png)

If this helps, I could change the `loadSpoilers()`, too. Then we have gained some time to discuss and analyse this further.

**Comment by Lineflyer** [comment]
Thanks for the optimization you are trying...I think it can only be good.
However what I am wondering about:
This only started for me somewhere in middle of march on `master`. There should be a reason for that...corresponding to a change done on master.
Could it be the multiple list feature....although I think it was only merged later in time?!

**Comment by pstorch** [comment]
The multiple lists feature was merged 17 days ago. Do you think this issue started earlier?

**Comment by pstorch** [comment]
The loading of Spoilers was introduced in #4633 over a year ago. 
I tried to find another way (loading the Spoilers at a later time), but wasn't successful yet. When debugging the case from the missing Spoilers issue, the Geocache is saved and loaded several times in the DB. Still a bit weird.

**Comment by samueltardieu** [comment]
The loading/saving/caching of geocache information should be completely rethought. The `CacheCache` and lazy loading was introduced by a former member of the team, and although it increased performances, it led to very convoluted scenarios which could surely be simplified.

I often feel that a proper ORM (such as greenDAO) would probably be a better solution than our home-cooked solution.

**Comment by pstorch** [comment]
Yes, an ORM layer would be good.
Why do we temporarily store Caches in the DB? Is it to allow switching between different Activities?

**Comment by samueltardieu** [comment]
IIRC we inherited this when cgeo became open source. I cannot remember any conscious choice from the team (it may have been done during the weeks before I joined though).

**Comment by SammysHP** [comment]
Yes, it was inherited. But it is very helpful. Often I open a cache, go back, open another cache, then switch back. We cannot rely on the assumption that the data will be kept in memory. We are already short on memory and users might have a break (lunch) and continue using c:geo an hour later.

**Comment by rsudev** [comment]
Initially every cache object was stored in the database (even the snippets downloaded from the old live map). When this became to slow the so called 'CacheCache' was introduced. On the one hand should it buffer caches in memory for faster  access, on the other hand does it solely hold incomplete caches from search results or the live map.
Unfortunately is it not as transparent as one could wish for.

Regarding 'proper DAO': I am not too fond of those, as I mainly remember them falling short when stuff started to get interesting when had to use one some years ago. But I am not against using one, if there is somebody willing to switch and is confident that it helps.

**Comment by Lineflyer** [comment]
FYI:

I just retested on the very same device with current market release 2016.03.06.
Although 500 detailed caches stored there is no significant delay for the actions described above.
So this supports the theory that the issue only came in some weeks ago.

@pstorch 
Could you repeat the performance analysis using `release` branch if this is feasible for you to get a good measureable comparison?

**Comment by pstorch** [comment]
@Lineflyer and the current master with my first optimisation? Does it make
a difference for you?
Do you experience the delay in the release branch, too?
I'll try to compare.

**Comment by Lineflyer** [comment]
Release branch= No delays
Currenst master = Smaller delay than before (so it seems to be better now)

**Comment by pstorch** [comment]
I tested again, but besides the unnecessary `loadSpoilers()` which I addressed in #5640, I can't find anything else which could cause a delay. But maybe I got confused while switching between branches. When switching from master to release one has to clean install c:geo because of needed DB downgrade.

**Comment by SammysHP** [comment]
Yes, it is slow. Not only opening a list, but also opening a cache (or go back to the list), rendering map tiles etc. So basically the whole app feels slow.

**Comment by Lineflyer** [comment]
I have the feeling (but could get it more clear until now) that after a fresh installation of the NB everything is fine, but at a certain point the laggy behaviour starts.
Don't know if it could be related to the amount of caches stored, or maybe a specific cache, or a certain setting.

**Comment by SammysHP** [comment]
I had the laggy behavior with only 10 stored caches.

**Comment by pstorch** [comment]
I'm looking around a bit, but can't find "the one" place which might cause the performance issue.

I stumbled upon the quite complex CacheDetails Layout. I don't know if this is the problem, but it looks very interesting:
![selection_008](https://cloud.githubusercontent.com/assets/5598124/14656023/82752010-0685-11e6-938e-ac218a944e80.png)

**Comment by Lineflyer** [comment]
Will try after next week to use the current release to find out if it is device related or version related. I can also get no new clues on why this is happening.

**Comment by Bananeweizen** [comment]
At one point of time (maybe a year ago) I experienced a laggy feeling app, but that was simply the "clean up cache directories" algorithm running in the background. Maybe that is somehow running a lot more often for @Lineflyer ?

**Comment by Lineflyer** [comment]
As far as I know the cleaning should be visible in the log but I did not see anything there. Furthermore it happened at several places not only on startup.

Meanwhile I own a new main device (Samsung S7) and the problem is gone.
I installed cgeo from scratch on that device (nightly with new empty DB).
So either it was related to a database problem on the old installation or the new device is just couple of times faster.

Just a guess: Can someone crosscheck if the DB migration from pre-multi list DB to multilist DB is errorfree?

**Comment by pstorch** [comment]
I once again tested a clean install of the store version, imported 1700 Caches, then migrated to the nightly. 
The biggest performance issue (on my device) is loading the map with that amount of caches. Offline map is faster than online map. 
The I did a clean install of the nightly with the same amount of caches. I can't "feel" a huge difference. 
Maybe my device (OnePlus One) doesn't care much and this issue only affects some smaller/older devices. 
I didn't do exact measures, just moved around in the app and tried to "feel" a difference. 

There is one user on Facebook who has a "several seconds" delay opening the Cache Popup on the map when he is offline. I can't reproduce that.

**Comment by Bananeweizen** [comment]
> There is one user on Facebook who has a "several seconds" delay opening the Cache Popup on the map when he is offline.

GCVote?

**Comment by Lineflyer** [comment]
>> There is one user on Facebook who has a "several seconds" delay opening the Cache Popup on the map when he is offline.
>
> GCVote?

AFAIR the rating can arrive async and we insert it while the popup is already shown.

**Comment by samueltardieu** [comment]
@Lineflyer Is it still an issue on master branch (or nightly builds)?

**Comment by samueltardieu** [comment]
> AFAIR the rating can arrive async and we insert it while the popup is already shown.

Confirmed.

**Comment by Lineflyer** [comment]
@samueltardieu Not for me right now, but I also changed my phone to a new one (Samsung S4 to S7). Not sure if tracking this any further make sense, because we might not get a real clue.

**Comment by Lineflyer** [comment]
Lets close it for now.
We might reopen once we get new clues when the release is out (hopefully not).
