### ISSUE TITLE
Implement 'needs maintenance' for Opencaching

### ISSUE THREAD

**Issue by following5** [cgeo/cgeo#5539]
All Opencaching sites now support 'needs maintenance' logs. Opencaching.de additionally has the feature of a 'needs maintenance' cache state (similar to the GC attribute 42) and of logging 'cache is ok' (does not need maintenance) by any user. All this is available through OKAPI, and it would be nice if it was added to c:geo.

First the basics. There are two different paradigms on 'needs maintenance' logs:
1. The GC way, which uses a dedicated log type "Needs maintenance" and is implemented also on OCPL sites (all OC sites except OC.de) and in c:geo.
2. The OC.de way, which uses a 'needs maintenance' = true / false / not-specified flag, which can be combined with any log type. This is also the way it is implemented in OKAPI, even when submitting logs to OCPL sites; OKAPI then will translate the logs to OCPL/GC logic.

I think the easiest way to implement submitting and displaying OC 'needs maintenance' in c:geo may be this:

**Submit 'needs maintenance'**

Enable log type 'Needs maintenance' for OC, and translate it to `logtype=Comment&needs_maintenance2=true` in the OKAPI request.

**Displaying 'needs maintenance' logs**
- Besides of the log type, also query the field `needs_maintenance2`.
- For logs which are not of type "Needs maintenance" (this is returned only by OCPL sites) and have `needs_maintenance2` = `true`, display an additional needs-maintenance-symbol besides of the log type symbol.
- For any log with `needs_maintenance2` = `false`, display a symbol for "cache is ok" or "cache does not need maintenance" besides of the log type symbol. This is the symbol displayed at OC.de: ![cache is ok](https://www.opencaching.de/resource2/ocstyle/images/log/16x16-needs-maintenance-no.png) This may be omitted for "Ready for search" logs, which imply that the cache is ok and always have `needs_maintenance2` = `false` at OC.de.

**Displaying the 'needs maintenance' cache state**
- Request the field `needs_maintenance`, and handle the value `true` like the GC attribute 42.

**Lose ends**

What is still missing now is submitting "cache is ok" (which is only supported by OC.de, other OC sites will ignore it and return the (localized) message: _Your cache log entry was posted successfully. However, your "does not need maintenance" flag was ignored, because Opencaching.XX does not yet support this feature._)

This would need a change through the whole log-submitting logic of c:geo, either adding an OC-only log type "cache is ok" which will be translated to OKAPI `logtype=Comment&needs_maintenance2=false`, or adding an additional input field for the geocache's maintenance state.

@rsudev 
We have already bin in talk about this issue; maybe you already prepared an implementation for the first step - submit OC 'needs maintenance'?

**Comment by rsudev** [comment]
@following5 I have not yet really 'prepared' anything, but the infrastructure is ready for the 'base case'. Unfortunately is my free time very limited right now, but I will see what I can do for the first steps (if nobody else jumps in, of course...)

**Comment by andrixnet** [comment]
On OPENCACHING-PL based websites: 

As owner of a geocache, via the website, one can: 
- write note
- maitenance performed
- temporarily disable

Via c:geo:
- found it
- didn't find it
- write note

------------------

As non-owner, via the website, one can: 
- found it
- didn't find it
- write note
- needs maintenance
- maintenance performed ***

*** On OPENCACHING-PL based website any user can log he/she helped with the maintenance of a cache

Via c:geo:
- found it
- didn't find it
- write note

**Comment by andrixnet** [comment]
Also, this issue / feature request should be retitled
"implement correct log types for OPENCACHING"

**Comment by SammysHP** [comment]
If I cannot log an own cache as found I consider this as a bug.

Is the list based on the OKAPI or the website?

**Comment by andrixnet** [comment]
Why log my own cache as found? I own it. I know where it is. I placed it. Just for statistics?

The list is based on OPENCACHING-PL based website.
I do not know the internals of OKAPI, if need be, please open an issue with OKAPI and relevant technical information.

**Comment by SammysHP** [comment]
Team accounts, events, ...

**Comment by andrixnet** [comment]
I have opened a discussion issue at OPENCACHING-PL here: 
https://github.com/opencaching/opencaching-pl/issues/412

**Comment by following5** [comment]
> Also, this issue / feature request should be retitled
> "implement correct log types for OPENCACHING"

No, this issue is about enabling "needs maintenance" logs for all Opencaching sites. All the other things you requested currently are NOT available via OKAPI, so they cannot be added to c:geo.

**Comment by following5** [comment]
The thing about "found it" and "dnf" logs by the owner also is no c:geo issue but an OKAPI issue. That's off topic here.

**Comment by andrixnet** [comment]
Does the "maitenance performed" log type come as a pair with needs maitenance?

**Comment by following5** [comment]
OCPL "maintenance performed" logs can be retrieved via OKAPI, and I assume that they are already displayed by c:geo.

Submitting "maintenance performed" currently is not implemented in OKAPI, so it can't be implemented in c:geo.

**Comment by andrixnet** [comment]
Actually, c:geo does not show "maitenance performed".

**Comment by Lineflyer** [comment]
@andrixnet Do you have an example geocode where a "Maintenance performed" log is missing in c:geo?

**Comment by andrixnet** [comment]
OR007F. I am owner. I can log a found, a dnf, a note.

OR011A: I am NOT owner. I can log a found, a dnf, a note.

**Comment by following5** [comment]
> OR007F. I am owner. I can log a found, a dnf, a note.
> OR011A: I am NOT owner. I can log a found, a dnf, a note.

As I wrote above, _submitting_ "maintenance performed" logs is not supported by OKAPI and therefore cannot be implemented in c:geo. If you would like to have this feature added to OKAPI, please open an issue for that in the OKAPI project.

What _is_ supported by OKAPI is _retrieving_ "maintenance performend" logs. When there is such a log, you should be able to see it with this log type in c:geo.

**Comment by andrixnet** [comment]
Posted issue: https://github.com/opencaching/okapi/issues/400

**Comment by SammysHP** [comment]
See also #4134.

**Comment by following5** [comment]
Logging NM has been implemented by #6973. For the rest, it's better to create separate issues.
