### ISSUE TITLE
Tag/Label vs List

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5540]
Follow-up of #87:

https://github.com/cgeo/cgeo/pull/5521#issuecomment-197906335:

> list vs tags is indeed 'just a naming thing', but IMO one that can make a difference when it comes to understanding the feature easily.
> When you 'store' something on a list, remove/delete becomes somewhat ambiguous and you need to consider namings like 'delete from all lists' to describe a complete removal.
> When you organize your caches with tags, the two operations are distinct. You add/remove tags from a cache or store/delete a cache on/from the device.
> (…)

https://github.com/cgeo/cgeo/pull/5521#issuecomment-197933007:

> - "All caches" are all caches with or without a tag. Furthermore it might contain caches without tags at all. This makes an "default" tag/list obsolete.
> - You can select/deselect tags, e.g. "vacation" and "must-do". This might be possible with "multiple lists" as well, but is more intuitive.
> - Tag selections and filters can be mixed via the same UI, they are more or less on the same level while lists and filters are on different levels.

**Comment by Lineflyer** [comment]
Mmmh. I do well understand the concept of tags and agree that this is what is just implemented in principle.
The question for me is: 
The long time user of c:geo is used to the lists to manage his caches. Therefore we could keep the wording as is, but make it well aware to the user with the UI that he can select multiple of them to store a cache.

But there is one thing I could image which could irritate the user once we have a cache on multiple lists:
It might look like these instances of the cache are totally independant of each other, but in fact they are not (e.g. if he refreshes the cache on one list it will have new data on all lists as we do only have one database behind it). In that case a tag concept would make more clear that we are dealing with the very same cache.

Also the arguments of @SammysHP regarding further consequences for some wordings and functions of the lists are to be considered.

I will start using this once it is in the NBs and try to get an impression how to improve the UI for the user.

**Comment by pstorch** [comment]
PM users know the concept of lists on Geocaching.com: Bookmarklist, Watchlist and Ignorelist. 
If you add a personal note or correct the coordinates of one cache it will show up everywhere. Regardless of which lists the cache is referenced. 
But the concept of Tags would fit here well, too.

**Comment by Bananeweizen** [comment]
Just imagine we had a UI using this: https://github.com/whilu/AndroidTagView People would immediately understand what tags are.

**Comment by andrixnet** [comment]
+1

**Comment by Lineflyer** [comment]
Maybe a first step would be to implement the lists like suggested in this issue #5550 (checkbox based) and at some point of time replace it by something like suggested by @Bananeweizen (which looks really nice)

**Comment by Lineflyer** [comment]
We do now have
- Caches can be on multiple lists
- Caches can be tagged with a color

Lets close this broad issue.
