### ISSUE TITLE
don't reload after adding to list

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5541]
###### Detailed steps causing the problem:
- Open cache details activity, scroll down
- Add to list

###### Actual behaviour after performing these steps:
Details activity refreshes, we jump to the top of the screen

###### Expected behaviour after performing these steps:
No reload/refresh of the activity, but just refreshing the view containing the list names

**Comment by Lineflyer** [comment]
This is a regression after #87 has been implemented, isn't it?
I do have 2016.03.15-NB (old list style) and can't reproduce.

**Comment by pstorch** [comment]
This is the problem when no list is associated with the cache. The the isOffline() method returns false, even if the cache was saved before.
I thought about loading the "_id" column from the DB into the Cache Model class. Then we could correctly determine if the cache is in the DB or not.
What do you think?

**Comment by SammysHP** [comment]
What is with caches that are in the database, but not stored? (= cached)

**Comment by Lineflyer** [comment]
I just wanted to mention the same as @SammysHP  
Since the recent changes a caches opened in full detail level still needs another redownload once I trigger to save it to a list. Before those changes IMHO the save procedure was almost not noticeable since it was already cached.

**Comment by pstorch** [comment]
Ah, I think I found it. I'm further investigating.

**Comment by pstorch** [comment]
@SammysHP, @Lineflyer your questions led me to the right place.
The searchByGeocode() method didn't recognize anymore if the Geocache was already there (e.g. in the Cache). This was due to the wrong interpretation of the empty/not empty list.
