### ISSUE TITLE
Add exif target navigation to picture context menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5542]
###### Detailed steps causing the problem:
- IOpen a gallery tab of a cache containing georeference pictures (Having our new overlay)
- Long press on the picture

###### Actual behaviour after performing these steps:
Only some "Open with..." options are shown in the menu

###### Expected behaviour after performing these steps:
As a click on the overlay can "only" trigger the prefered navigation I would suggest to include the full navigation menu offering all methods in the context menu after long press

###### Version of c:geo used:
2016.03.15-NB

###### Other comments and remarks:
This will also make the feature more usable as the user might fail to recognize that clicking the overlay on the picture triggers an navigation action

**Comment by Lineflyer** [comment]
@UniQP (as you implemented the basic function) maybe you are interested in this improvement proposal

**Comment by UniQP** [comment]
@pstorch implemented the basic function. I just proposed the functionality in #5483.

**Comment by pstorch** [comment]
I can look at it.

**Comment by pstorch** [comment]
Thanks for the idea. The usability is much better.

**Comment by Lineflyer** [comment]
let me test this.

**Comment by Lineflyer** [comment]
Nice, works flawless for me with 2016.04.01-NB. Tested with spoiler picture of GC276PG.
Thanks @pstorch
