### ISSUE TITLE
Upload of personal note only if cache is saved

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5543]
###### Detailed steps causing the problem:
- PM-user
- Open a unsaved cache in c:geo
- Edit the personal note

###### Actual behaviour after performing these steps:
There is no upload button shown as long as the cache is not saved in c:geo

###### Expected behaviour after performing these steps:
I don't see a reason why we can't upload the note for unsaved caches?! (Not sure if it worked before)
Else the upload button should be shown and the user should be asked to save the cache before uploading the note (like in other places if data is added).

###### Version of c:geo used:
2016.03.15-NB

###### Is the problem reproducible for you:
Yes

**Comment by MrYaz** [comment]
For me the cache is saved locally as soon as I edit the personal note.
As I remember it has always been like that for me but I could be wrong.

Version used:
2016.03.18-NB

**Comment by Lineflyer** [comment]
@MrYaz 
You are right, but after "autosave" the "upload" button is still not shown which made me think it is not working.

@pstorch Is that what you fixed in your PR?

**Comment by pstorch** [comment]
Yes, my PR fixes the "upload" button and the refresh of the lists on the detail page after upload.
