### ISSUE TITLE
Filtering within a list for "favorites" does not work properly

### ISSUE THREAD

**Issue by diskostu** [cgeo/cgeo#5544]
###### Detailed steps causing the problem:

- Created a pocket query. It will return 749 results at the moment.
- I downloaded the results with the app "Pocket Query Creator"
- I chose "Open with" and the GPX was imported to c:geo
- the list appears just fine, I have 749 results just like on the web page
- Now I want to apply a filter to this list:
  - "Favorite % is > 10": It only shows me 1 cache out of the 749. This **must** be wrong, although I cannot say what the expected number is. But certainly more than 1.
  - "Favorite count is > 10": that filters the list in c:geo down to 44 caches. But, when I look at the search results on the webpage and sort it by "Favorite points", it becomes clear that there are 276 caches which have more than 10 favorite points.

###### Actual behaviour after performing these steps:
The filtered result shows less caches than expected.

###### Expected behaviour after performing these steps:
More results are expected, see the steps above.

###### Version of c:geo used:
2016.03.06 (LG G4, Android 6.0.1)

###### Is the problem reproducible for you:
Yes

###### Attach system information if available (see c:geo menu -> About c:geo -> System):
Device: LG-H815 (g4_global_com, lge) Android version: 6.0.1 Android build: cm_h815-userdebug 6.0.1 MHC19J f75420fde9 test-keys Cgeo version: 2016.03.06 Google Play services: enabled Low power mode: inactive Compass capabilities: yes Rotation vector sensor: present Orientation sensor: present Magnetometer & Accelerometer sensor: present Direction sensor used: rotation vector Hide own/found: true Map strategy: auto HW acceleration: enabled (default state) System language: de_DE Geocaching sites enabled: - geocaching.com: logged in (Login OK) / PREMIUM Installed cgeo plugins: none

**Comment by pstorch** [comment]
Unfortunately PQs don't contain Favorites. I guess you have to refresh all caches in cgeo (initiates a new download) before this filter can be used correctly.

**Comment by diskostu** [comment]
Thanks for the info. I'll try refreshing all caches.
But if the PQs don't contain any info about the favorites, how was it possible for c:geo to give my 44 results for the filter "more than 10 favorite points"?

**Comment by pstorch** [comment]
Have you had some of these caches loaded on your device before? c:geo remembers the extra info it downloaded before.

**Comment by diskostu** [comment]
That could be the reason. It must be after all, since there is no favorite info in the GPX file ;) Thanks again for the clarification.
