### ISSUE TITLE
Lists panel is not updated when editing Personal note

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#5546]
###### Detailed steps causing the problem:
- Open a cache that is not currently stored in the device
- Go to the Description tab
- Press "Edit" under Personal note
- The message  "The cache has been stored locally" is shown.
- Enter something in the Personal note field and save the changes by pressing the checkmark
- Go back to the Details tab

###### Actual behaviour after performing these steps:
The cache does not seem to be stored in any List since the Lists panel is empty.
You have to refresh the cache details for it to appear in the List view in the List "Stored"

###### Version of c:geo used:
2016.03.19 NB

###### Is the problem reproducible for you:
Yes

###### Other comments and remarks:
Bug related to the newly implemented feature #87

**Comment by samueltardieu** [comment]
It has been fixed by https://github.com/pstorch/cgeo/commit/a5d3196a8072a7e4675666880b885221817bec9f.
