### ISSUE TITLE
Finalize multi list UI (first step for release)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5550]
In order to optimize the usability of the possibility to have a cache on more than on list:

Instead of the new multiple buttons for ¨Remove from list¨ couldn`t we just make the list selection dialog checkbox based and keep the remaining UI elements on cache details as they have been before?

IMHO this would have some advantages:
- Moving a cache from one list to another currently got more complicated than before
- No cluttering of buttons on cache detals page
- Simultanous storing to multiple lists possible in one dialog

Doing it like this would also bring it more into the direction of the discussed ¨tag¨ strategy

**Comment by Bananeweizen** [comment]
I'm thinking more along these lines:
![tags](https://cloud.githubusercontent.com/assets/406876/14233161/d557f86a-f9c0-11e5-9232-e717da1c133c.png)

Replace the buttons I used for the tags with something like the tags from here (and allow users to choose a color, when creating a new tag): https://github.com/mcharmas/android-tagview

**Comment by pstorch** [comment]
I think this could be a good solution. 
Should we open a new tab for this or keep it on the Details page. Showing all available Tags could need some space.

**Comment by SammysHP** [comment]
Keep it on the overview page. This shouldn't take more than one or two lines (most users will use only one, maybe two tags). Editing of tags should open a new activity/popup.

**Comment by Lineflyer** [comment]
In general this is a good way forward.
But I would also like to keep it on the overview (cache details) page if possible.
Also the create new tag should in a first approach still be in the current mdoe (like "Create list") at the place where the user is used to it in the UI.

**Comment by Lineflyer** [comment]
I don't know the efforts of effectively changing the list UI into a tag UI.
In order not to have so long release cycles I suggest in a first step to optimize the multi-list as it is now (e.g. with the initially mentioned changes) and later on move forward to a tag based UI.

What do you think?
IMHO the checkbox based selection would make is more usable for now and might be easier to implement on short term.

**Comment by pstorch** [comment]
I think the Checkboxes can improve the usability a lot. But I don't have a clear picture yet.
Having the buttons as they were before is not 100% suitable.
The old buttons were:
- Refresh: is always there -> no problem
- Move: was only shown when the Cache was stored on a List
- Store / Drop: were exchanged depending on current offline state

I think instead of "Move" and "Store" we would have "Lists" or "Manage Lists" which opens the Checkbox based Listselection dialog.
"Drop" is shown when the Cache is on at least one List. (related to #5638)

**Comment by Lineflyer** [comment]
> I think instead of "Move" and "Store" we would have "Lists" or "Manage Lists" which opens the Checkbox based Listselection dialog.
"Drop" is shown when the Cache is on at least one List. (related to #5638)

- Store can be shown as long as not saved and will open the checkbox based list selection.
- Drop should be shown 
- If saved "Manage" should be shown opening the checkbox based selection again.

Special case still would be if the user deselects all checkboxes (which should be equally handled like "Drop")
IMHO this would be perfect for the firs step then and can easily be transfered into tag based management later on (just by replacing the checkbox based list selection by a tag manager and some more wording changes).

**Comment by Lineflyer** [comment]
Renamed this issue to be a single point of discussion for finalizing the curerntly implemented multi list feature from UI perspective.

Future developments can go to #5540.

**Comment by rsudev** [comment]
In my opinion the easiest and most understandable approach would be, to separate store/drop from list assignment.
So every 'stored' cache would automatically be on the 'default list' and dropping a cache would remove it from all lists quite naturally. When we than add a check-box based list selection (as a first step), I see all operations covered. And if you remove all check-boxes, the 'default list' might get enabled automatically.

**Comment by pstorch** [comment]
No worries, it's not implemented yet, just for discussion ;)

![2016-04-07 21 09 28](https://cloud.githubusercontent.com/assets/5598124/14366997/ecf5546a-fd15-11e5-81bb-842c3fc9c00d.png)

Following @rsudev s proposal we should remove the default "Stored" List from the list selection dialog and just use it in the background for the general "store/drop" buttons. 

But for the Listselection dialog on the long press MainActivity button, we would still offer "Stored" as a list selection? As well as the CacheListActivity dropdown menu, right?

When I see it correctly we need to have two variants of the Listselection Dialog `StoredList.promptForListSelection()`:
- single select (as is): when selecting which list to show
- multi select (new): when managing the lists/labels of a cache

**Comment by Lineflyer** [comment]
> Following @rsudev s proposal we should remove the default "Stored" List from the list selection dialog and just use it in the background for the general "store/drop" buttons.

But for the Listselection dialog on the long press MainActivity button, we would still offer "Stored" as a list selection? As well as the CacheListActivity dropdown menu, right?

I would keep it for now as it is (i.e. show "Stored" in normal list selection and on long press). Otherwise people only using the stored list would not see their saved caches (given they do not know of / use the longpress. Its well hidden).

**Comment by rsudev** [comment]
Regarding the 'stored' list I agree with @Lineflyer We should keep it for this version, but might consider renaming it into 'not categorized' and remove it from the list assignment dialog.
I have some ideas/remarks to throw into the discussion regarding list assignments. For one thing, the amount of lists to consider. I currently have 34 lists in use... The list picking dialog would therefore benefit from having the already selected at the top always. and it could be good to have a 'deselect all' button (or other UI element).
When selecting list for executing actions in the context of multiple selected caches, we could have three states - deselected for all, selected for some, selected for all. If there is a list with an initial 'selected for some' state, tapping should cycle through all three, with 'selected for some' implying no change to the caches for this particular list.
This are of course by no means 'requirements', just ideas.

**Comment by pstorch** [comment]
A select "all" or "none" function is a valid feature. And I also like the step-wise approach to keep the "Stored" list visible/selectable for now.

I'm not sure with the three-state-checkboxes. At the moment we have "Move", "Copy" and "Remove" in the CacheListActivity menu. 

- `Move`: remove cache(s) from this list and store on other list(s). Maybe some caches are on some of the target lists already. Should not be a problem.
- `Copy`: store cache(s) on other list(s), too. Same here: maybe some caches are on some of the target lists already. Should not be a problem.
- `Remove`: remove cache(s) from this list.

I wouldn't introduce an overall "manage lists" where we collect all lists from all/selected caches and merge the selected/partly selected lists.
And technically I started using the `MultiChoiceItems` in the `AlertDialog` which doesn't support tristate checkboxes. ;)

What do we do with #5627 ? Should this be merged first (when it's ready)?

**Comment by pstorch** [comment]
As a first proposal I implemented a MultiChoice Dialog for the ListSelection.
I think it's easier to discuss, if we have something to play with.

While implementing and testing I observed some details:
- I think it doesn't make sense to change the CacheListActivity commands `Move` and `Copy`. When moving to another List I want to move to exactly one other List not many. Same with copy. Other opinions?
- The "deselect all" feature is not as usefull I think. On how many lists is a cache on average? 2 - 3?. I've sorted the already selected lists to the top (as @rsudev proposed). With this sorting it is very easy to deselect those at the top. Any other opinions?

**Comment by Lineflyer** [comment]
I consider the latest list picker as a very good approach! Thanks @pstorch .
From my point of view this is a very good first step, thus we could close this issue. 
If there are remaining problem we should track them in dedicated issues.

Is there already an issue to migrate to tags or shall we open a new one (is it necessary at all or is the current implementation already fitting this use case??).
