### ISSUE TITLE
Crash when using OSM maps + rotation

### ISSUE THREAD

**Issue by jovars** [cgeo/cgeo#5551]
##### Detailed steps causing the problem:
- Open C:geo with google -maps
- Switch map-type to open-cycle-map
- Turn the device ( rotate from "portrait" to "landscape"-view  ...
- C:geo crashes... do not respond, wait a couple of minutes and must be restarted

Note - If I tell the device to "not automatic turn picture from portrait to landscape", the problem does not exist, so it is just the "turn-thing" that makes c:geo crash 
##### Actual behavior after performing these steps:

Wait until android ask if I want to close the hanging app.
##### Version of c:geo used:

2016.03.06 , but this has been a problem for several months maybe more than a year. 
##### Is the problem reproducible for you?

Yes, every time I use cycle-map and forgets to turn off the "auto-turn-picture" the app crashes an I have to wait for 2-5 minutes. 
##### System information:

```
Version 206.03.06, 
sony z1 compact, D5503
android-version: 5.1.1
```

**Comment by Lineflyer** [comment]
Not reproducible for me.

@jovars 
It might be helpful if you post your complete system information from About c:geo -> System.
Additionally please kindly check of this also happens while rotating with Google Maps and OSM:Mapnik map.

**Comment by Matze2** [comment]
I can also reproduce it when I turn the device before the cycle map is completely rendered on the display.
My system information is attached to #5498.
It is not fully reproducible for me. But it helps to switch between different maps and turn the device during rendering.
I also got it with Mapnik once but not with Google maps. I also never had problems OSM offline maps which I usually use.

**Comment by jovars** [comment]
My c:geo never crashes because of this when using google-maps or google-satellite. When using mapnik it is possible to provoke it to crash, but with cycle-map it occurs every single time that i switch from "portrait to landscape", or from "landscape to portrait". 

--- System information ---
Device: D5503 (D5503, Sony)
Android version: 5.1.1
Android build: 14.6.A.1.236
Cgeo version: 2016.03.06
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: sv_SE
Geocaching sites enabled:
- geocaching.com: logged in (Inloggning OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---

/Jovars

**Comment by samueltardieu** [comment]
I can reproduce it with the `master` branch. Use OSM, turn the phone several times, cgeo will lock up.

**Comment by Lineflyer** [comment]
I can still not reproduce it on my device.
@samueltardieu @jovars Any difference if you switch off Settings -> System -> Hardware acceleration?

**Comment by jovars** [comment]
Its the same when hardware acceleration is off. When i switched to mapnik and then turned the device twice,  c geo hangs...  he says that Android has found a hanging app, could it be possible to find the reason for crashing in any android-logg, somewhere?  / Jovars

**Comment by mortenvf** [comment]
I am seeing this issue also:

When using OSM map, c:geo will hang after rotating the device one or more times. Usually, when c:geo hangs, the map appears to have been rotated, but aspect ratio has not been adapted to the new screen rotation, so part af the screen is blank and part of the map extends outside the screen.

I cannot reproduce with Google maps.

c:geo version 2016.03.06 on Sony Xperia Z3 Compact (E5823) running Android 6.0

**Comment by rsudev** [comment]
When you send a report to google for this hang (and tell as when and your device here) we can take a closer look onto the background.

**Comment by LeXeRLV** [comment]
I had the same problem last week, but now it is gone.
Problem was, that using OSM, when screen is rotating or first time showing
map it hanged for a long time. Also sometimes icons of the caches became
unscalled - bigger and inactive on pressing on them.
I tried to turn on experimental map showing theme in Settings-System and
turn standard map back, all became normally.
I don't really know, if problem solved by newest Nightly build or because
of turning in to the new map theme and than back..

My Android System information:
--- System information ---
Device: GSmart Sierra S1 (GSmart Sierra S1, GSmart)
Android version: 4.2.1
Android build: Sierra_S1_V1.39.14@GSmart
Cgeo version: 2016.04.12-NB-5be00cb
Google Play services: unavailable
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Debug mode active: yes (cgeo forced to English)
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---

On 11 April 2016 at 16:32, rsudev <notifications@github.com> wrote:

> When you send a report to google for this hang (and tell as when and your
> device here) we can take a closer look onto the background.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cgeo/cgeo/issues/5551#issuecomment-208344489>
>



-- 
Ar cieņu,/С уважением,/Best regards,

Dmitrijs Līvmanis
GSM.: +371 26 54 45 54
E-mail: dmitry.livmanis@gmail.com

**Comment by mortenvf** [comment]
Issue is still present in c:geo version 2016-04-12.

I submitted a report to Google at approximately 16:16 CEST today.

**Comment by rsudev** [comment]
I was able to find your report right away. Will start to look at it.

**Comment by davebiffuk** [comment]
I am experiencing this ANR with c:geo 2016.04.12 on a Nexus 5, Android 6.0.1, latest patchlevel. I submitted a crash report a few minutes ago referencing this issue number (5551).

**Comment by Lineflyer** [comment]
@rsudev Any conclusions on this. There are meanwhile two other users having that problem.

**Comment by mortenvf** [comment]
Problem still present on c:geo version 2016.06.09 on Sony Xperia Z3 Compact (E5823) running Android 6.0.1.
It seems to be harder to provoke the problem. I had to rotate 20-30 times before c:geo freezes.
New error report submitted @11:19 CEST

**Comment by real-or-random** [comment]
I can reproduce this pretty reliably, really super annoying.

It almost always freezes on first attempt in OSM (in MapsforgeMapActivity), never with google maps. Does not matter if rotating from landspace to portrait or the other way around.

**Comment by ulfk** [comment]
I have the same problem when using OSM:Mapnik and rotating my phone from portrait to landscape or vice versa. I need to kill and restart c:geo to get it working again.
When using Google-map setting it works fine.

Device: LG-H870  (G6)
Android version: 7.0
Andoid build: NRD90U
c:geo version:  2017.10.10

**Comment by mortenvf** [comment]
Rotating the device while OSM map tiles are still being loaded seems to be the way to reproduce this problem.

**Comment by real-or-random** [comment]
I can confirm that: It almost always crashes while tiles are being loaded, and it never seems to crash when the tiles has been fully loaded.

Interestingly, all tiles are reloaded after rotating, which is unnecessary.

**Comment by Lineflyer** [comment]
This issue seems long outdated as a lot of code and mapsforge version has changed since then. Feel free to reopen if this is still happening (it is still OK for me).
