### ISSUE TITLE
cgeo.org should handle redirections better

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5563]
http://cgeo.org/status.html redirects to http://www.cgeo.org/. It should redirect to http://www.cgeo.org/status.html. Ideally, http://cgeo.org/XXX should be redirected to http://www.cgeo.org/XXX (for any XXX).

**Comment by samueltardieu** [comment]
Ping @mucek4

**Comment by Lineflyer** [comment]
ping @mucek4 once again ;)

**Comment by mucek4** [comment]
The problem is bulky made old webpage. I managed to made *.html redirects, other redirects does not work.

**Comment by Lineflyer** [comment]
so lets close and live with that...
