### ISSUE TITLE
send2cgeo - cache is not properly stored

### ISSUE THREAD

**Issue by Nicole1338** [cgeo/cgeo#5564]
If you send a cache from the web browser, via the "Send to c:geo" button to c:geo, then the cache is not properly downloaded and saved.

I think it has something to do with the new list management and the possibility to save on cache to several lists.

--- System information ---
Device: Nexus 5 (hammerhead, google)
Android version: 6.0.1
Android build: MMB29V
Cgeo version: 2016.03.22-NB-97330f6
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar
--- End of system information ---

Best regards,
Nicole

**Comment by Lineflyer** [comment]
@Nicole1338  Thanks for reporting this.
Confirmed!

**Comment by samueltardieu** [comment]
Cc @pstorch

**Comment by pstorch** [comment]
I'll have a look.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by haarspalter** [comment]
Importing from send2cgeo works as expected with latest nightly. Cache is added to the current list

**Comment by Nicole1338** [comment]
I also tried it yesterday and it worked perfectly. Thanks for the fast bug fix. :)

**Comment by Lineflyer** [comment]
Closing as retested by @Nicole1338 
Thanks!
