### ISSUE TITLE
Translation not complete 

### ISSUE THREAD

**Issue by notspecified** [cgeo/cgeo#5569]
Since I've updated my phone to lollipop some of the translations in the app are missing. I don't know exactly if everything was ok with kitkat, cause I didn't use the same cgeo built... Anyway, now I've this issue.
As an example I attach one Screenshot, the point I'm talking is highlighted.
Some basic Infos:
--- System information ---
Device: C5503 (C5503, Sony)
Android version: 5.1.1
Android build: 10.7.A.0.228
Cgeo version: 2016.03.22-NB-97330f6
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_AT
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK)
Installed cgeo plugins:  none
--- End of system information ---
Root: yes 
#
![_20160322_185647](https://cloud.githubusercontent.com/assets/5119558/13962532/b8dae5b6-f061-11e5-9b1d-9f7b3214a34b.JPG)

**Comment by rsudev** [comment]
These are new strings from the cache on multiple lists feature. I was slightly reluctant to put them up for translation already, as I expect them to change if we decide to move towards a 'tags' semantic instead.

**Comment by SammysHP** [comment]
Translations are done via https://crowdin.com/project/cgeo
