### ISSUE TITLE
Heads up: Website update

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5580]
Geocaching.com updated their website and introduced some new fields into the lists of caches (at least in the new search)

No idea yet if cgeo might be affected. Maybe someone can check. I am unavailable at the moment.

**Comment by rsudev** [comment]
I let the integration build run - all green

**Comment by rsudev** [comment]
Short 'smoke-test': search nearby, open cache details (unstored) - seemingly everything fine.

**Comment by rsudev** [comment]
Logging a note and refreshing the cache worked as well

**Comment by rsudev** [comment]
Anything on FB or Support regarding issues in c:geo? Otherwise we probably can close this.

**Comment by Lineflyer** [comment]
Closing. All functions seem to work normal
