### ISSUE TITLE
Switch IntelliJ project format?

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5581]
The other day I switched to the offered new version of IntelliJ:

IntelliJ IDEA 2016.1
Build #IC-145.258, built on March 17, 2016

It seems to have a different project format with all files stored in the .idea folder only. Should we switch to this version in general? Should I upload these files in addition?

**Comment by Bananeweizen** [comment]
If I get it right, Android Studio 2.0 is also based on that version. However, Android Studio 2.0 is not yet released (1.5 is current).

On the other hand, I always use just "import from gradle" when checking out on a new machine (and I basically ignore all changes in those many IDE related files).

So, I can't really give advice...

**Comment by pstorch** [comment]
I tried Android Studio 2.0 today, but got this build error:

`Error:A problem was found with the configuration of task ':main:packageBasicDebug'. > File ... specified for property 'resourceFile' does not exist.`

**Comment by Bananeweizen** [comment]
I've switched the gradle build to Android 2.0 on Saturday, and at least the gradle tasks I normally use (testBasicDebug and similar) work fine for me. I've never used the non gradle run configurations in AS before, so I can't say whether they changed for worse or not.

Summary: I can work with AS 2.0 currently.

**Comment by kumy** [comment]
For me, on Idea 2016.1, just opening the project and click `sync gradle` removes `.iml` files and create `.idea/` directory structure... This is quiet annoying while commiting to see all those diff not related to the work going on. For me we should migrate.
I've opened a PR #5656 for others to test with their respective IDE.

**Comment by kumy** [comment]
That will not be easy to have a consistent project layout as we all use different tools. Couldn't we simply not share the .idea directory at all? What would be the consequences?

**Comment by pstorch** [comment]
I can help testing. We could remove and gitignore the `.idea` directory.
But I'm not an AS poweruser. I don't have special settings to keep there.

**Comment by kumy** [comment]
I've just tested to copy my workdir, then remove `.idea` directory and `.iml` files. The project can still be successfully imported into Idea. The "non gradle run list" is empty, but this is expected. Users can add configurations themselves if they prefer to use them. So, it seems technically feasible to not distribute Idea project files and add `.idea/` to `.gitignore`.
What's the global opinion here?

**Comment by Bananeweizen** [comment]
I believe those have mainly been checked in to share the same settings for code analysis, formatting and so on (for the same reason we have the Eclipse .settings folder checked in). It would be nice to still have that, but I have no knowledge of the file formats of IDEA, so I cannot say if you might be able to have a kind of selective gitignore.

**Comment by pstorch** [comment]
At work I prefer Eclipse, but we have colleagues using IntelliJ and they've put `.idea` and `.iml` into the `.gitignore` file right away. So I guess we should remove them. At the moment it's rather annoying to have these modified files all the time.

BTW: I can use AS 2.1 now without errors.

**Comment by rsudev** [comment]
As we currently seemingly do not have any of those settings active or aligned with eclipse, I guess the least issues would be generated by removing and ignoring all these project stuff.

**Comment by Lineflyer** [comment]
Is this issue still relevant. AFAICS we moved to Android Studio and retired Eclipse?!

**Comment by moving-bits** [comment]
AFAIK all active c:geo devs use IntelliJ (Android Studio) nowadays. And we have removed the Eclipse-related files a while ago, so I guess we can close this issue here.
