### ISSUE TITLE
Weird scrolling on Marshmallow

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#5582]
##### Detailed steps causing the problem:
- Step 1
Use a Moto-G 2nd gen phone that has just been updated to 6.0
- Step 2
Load a cache, swipe to the logs page and try scrolling

##### Actual behavior after performing these steps:
It goes "all weird", well that's my best description.
I made a short video and posted it on youTube...

https://www.youtube.com/watch?v=-kFU26Bu71M

##### Expected behavior after performing these steps:
It should scroll normally.

##### Version of c:geo used:
2016.03.06

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: XT1072 (thea_retgb, motorola)
Android version: 6.0
Android build: MPB24.65-34
Cgeo version: 2016.03.06
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (manually changed)
System language: en_GB
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

##### Other comments and remarks:
No other Apps exhibit this behaviour

**Comment by rsudev** [comment]
What happens, if you enable the hardware acceleration (in c:geo - settings - system)?

**Comment by alan666notb** [comment]
Aha - yes. That fixes it.
Thanks.

**Comment by rsudev** [comment]
This is than a system-issue, maybe the interaction between our appcompat level and the not-enabled HW-acceleration (we have several kinds of such weird behaviour specifically for the Moto G2 with Marshmallow).
Closing.
