### ISSUE TITLE
Wrong count of stored caches

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5583]
##### Detailed steps causing the problem:
- Look at text balloon on `Stored` main screen icon

or

- Open `Stored` activity
- Open cache list drop-down menu

##### Actual behavior after performing these steps:
In my case, it display 321 stored caches but there is really 12 caches stored.

##### Expected behavior after performing these steps:
* 12 caches should be displayed on main screen
* drop-down list should also display 12 caches for 'All caches' entry.

##### Version of c:geo used:
Current master 3f5c1c9

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: m8 (cm_m8, htc)
Android version: 5.1.1
Android build: cm_m8-userdebug 5.1.1 LMY48Y a4d1ba3b73 test-keys
Cgeo version: 2016.03.25-3f5c1c9 developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: fastest
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: none
--- End of system information ---
```

##### Other comments and remarks:
In cache list activity, the number 312 move from entry "All caches" to "Stored" and vice-versa, while selection a list or the other.

See this [video](https://www.dropbox.com/s/e9nhs3ejq6u3gk2/device-2016-03-25-223414.mp4?dl=0) 

Should be related to #87

**Comment by kumy** [comment]
CC @pstorch

**Comment by pstorch** [comment]
Just a quick check. I couldn't reproduce on my device at the moment. But I remember I had this behavior some time ago, too. In the meantime I started over with a blank DB. 
I need some more time to investigate.

**Comment by pstorch** [comment]
Is it possible to have a look at your sqlite DB file? At least the cg_caches_lists Table?

**Comment by kumy** [comment]
@pstorch you can find my table content on [pastebin](http://pastebin.com/pcU1t1VA)

**Comment by pstorch** [comment]
Looks like there are geocodes in it which are Waypoints not Geocaches. That was the phenomenon I had, too. But I don't know, how they got in there.

**Comment by kumy** [comment]
Maybe that come from the unit tests?
`TCDG4` appear in `./tests/res/raw/terracaching_gpx.gpx`

**Comment by pstorch** [comment]
Yes, they are from the unit tests. We also have to cleanup the lists after we cleanup caches. Fix is coming.

**Comment by kumy** [comment]
Assigned for testing

**Comment by kumy** [comment]
Confirmed fixed for me.
Thanks @pstorch
