### ISSUE TITLE
Can't delete cache from "All list"

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5588]
##### Detailed steps causing the problem:
- Open Stored activity
- Select "All caches" from the drop down selector
- Long press a cache, select `Drop`

##### Actual behavior after performing these steps:
The cache is still present in list

##### Expected behavior after performing these steps:
The cache should be removed

##### Version of c:geo used:
Current master

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: m8 (cm_m8, htc)
Android version: 5.1.1
Android build: cm_m8-userdebug 5.1.1 LMY48Y a4d1ba3b73 test-keys
Cgeo version: 2016.03.27-dfbd95b developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: fastest
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / PREMIUM
- opencaching.de: logged in (Login OK)
Installed cgeo plugins: none
--- End of system information ---
```

##### Other comments and remarks:
It works fine on other list than "All caches" (untested on other special list like "History").

See this [video](https://www.dropbox.com/s/asidwvcf1enb4u8/device-2016-03-27-210447.mp4?dl=0)

**Comment by kumy** [comment]
CC @SammysHP, @pstorch

**Comment by pstorch** [comment]
I started looking into this issue. 
The deletion itself can easily be fixed, but I stumbled upon the correct message and more important the "undo" feature. 
The correct undo would be a bit more complicated. Remember all lists from all selected caches.
Easier would be to undo to the "default list" only or don't support undo at all in this situation (then the warning message should be clear enough).
What was the previous behavior? I'll have to check the released version.

**Comment by pstorch** [comment]
Just tested with "release" branch. The message was "Do you want to remove all ... caches from **current** list?", which is misleading on the "All caches" list. And the undo command restored all caches to the last selected concrete list. Not necessarily the list the caches have been before.

What should we do?

1. New message "Do you want to remove all ... caches from your device? WARNING: this action cannot be undone!" and remove undone support.
2. New message "Do you want to remove all ... caches from your device? WARNING: this action can only be undone to the default list!" and restore only to the default list.
3. New message "Do you want to remove all ... caches from your device?" and implement proper undo.

3 would be the most comfortable for the user.

**Comment by SammysHP** [comment]
There is only one solution: restore the exact state from before (3). But we don't need a alert dialog when there's the possibility for an undo.

**Comment by pstorch** [comment]
@SammysHP: while reading your comment again, I'm not sure if you mean we should remove all confirmation dialogs wherever we have an undo function. Or just without the strong "WARNING" in the message.

**Comment by SammysHP** [comment]
I wonder that there's a dialog at all because the action can be undone. Usually there's only one of the two.

**Comment by pstorch** [comment]
Just checked the other undoable Actions. None has a confirmation dialog. So, let's remove it here, too. Will simplify the code a bit.

**Comment by pstorch** [comment]
I've removed the confirmation dialog. 

There is one tricky situation. When removing all caches from a specific list, then another dialog pops up and asks to remove the (now empty) list itself.
This dialog is visible at the same time as the Popup with the undo button. It's still possible to click the undo button, but if the user first confirms the other dialog (to not delete the list), then the undo is gone.

Any ideas how to improve this?

**Comment by SammysHP** [comment]
I think it is better to do this in two commits. Let's first fix this issue, then discuss and/or fix the behavior of the dialog/undo bar.

**Comment by pstorch** [comment]
Agree

**Comment by Lineflyer** [comment]
Confirmed working with 2016.04.03-NB
