### ISSUE TITLE
HW acceleration switched off on Android 6.0

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5598]
##### Detailed steps causing the problem:
There are numerous users on support mail, who have graphical problems and stability problems.
All of them have in common:
- They either have a new device with Android 6.0 or recently upgraded to Android 6.0
- In all system informations I do see that HW-acceleration is switched off (`HW acceleration: disabled (manually changed)`)
- After enabling it, the problems are gone 

##### Expected behavior after performing these steps:
The users do say that they did not manually change this setting before.

Is there any problem in the code, which may lead to the effect, that it is disabled on Android 6.0?
Is this setting contained in any (google) backup and might be wrongly restored on a users new device?

##### Version of c:geo used:
2016.03.06.

**Comment by UniQP** [comment]
#5582 looks like an example.

**Comment by Lineflyer** [comment]
@UniQP Exactly. 
What I am wondering is, that all users stated that they did not actively change this setting.
So it would be nice if someone can check the code...the default should be enabled except for some specific devices.

**Comment by samueltardieu** [comment]
This is probably in their settings which have been restored automatically on the new device.

**Comment by Lineflyer** [comment]
Is there a way of excluding this setting from the Google backup?

**Comment by kumy** [comment]
Without knowing in details. I doubt as we use the "Android settings framework". (I may be wrong)

On March 31, 2016 12:41:52 PM GMT+02:00, Lars <notifications@github.com> wrote:
>Is there a way of excluding this setting from the Google backup?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5598#issuecomment-203874472

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by samueltardieu** [comment]
Yes there is. We could use another file, only the default one is backed up (this is configured in `CentralBackupAgent.java`).
