### ISSUE TITLE
Cause string missing on login failure 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5600]
##### Detailed steps causing the problem:
- Go to Menu -> Settings - Services - geocaching.com
- Try to authorize with correct username but wrong password

##### Actual behavior after performing these steps:

The following prompt is shown:
![screenshot_2016-03-29-18-21-33](https://cloud.githubusercontent.com/assets/949669/14115510/989c93f6-f5db-11e5-9457-51a97359420b.png)

##### Expected behavior after performing these steps:

The cause string "Wrong username and/or password should be shown"

##### Version of c:geo used:
2016.03.29-NB

##### Is the problem reproducible for you?
Yes

##### System information:
not relevant

##### Other comments and remarks:
Happens since the implementation of the new authentication menus

**Comment by kumy** [comment]
I'll look.

**Comment by kumy** [comment]
@Lineflyer the "old" message should should have been displayed (it was "Login information incorrect") if you were using English.

The string `init_login_popup_failed_reason` has been  updated by 1d9326d. We should wait for translations to come.

BTW PR #5607 update the string to you're formulation. Merge or Discard it as you wish.

**Comment by Lineflyer** [comment]
Nope...still not working for me with 2016.04.01-NB.
In any case if the german string is not found the english one should be display here or am I wrong.
It still looks like in the screenshot above.

**Comment by Lineflyer** [comment]
Related to https://github.com/cgeo/cgeo/issues/5388?

**Comment by kumy** [comment]
string exists but had changed.

On April 1, 2016 5:04:04 PM GMT+02:00, Lars <notifications@github.com> wrote:
>Assigned #5600 to @kumy.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5600#event-611389772

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by UniQP** [comment]
Looks like crowdin still has the old string.

**Comment by samueltardieu** [comment]
Ping @rsudev

**Comment by Lineflyer** [comment]
I don't understand the problem here. At least I should see the existing english string although my installation is running on german language, or not?

**Comment by UniQP** [comment]
@Lineflyer: As @kumy explained 1d9326d89377d710815d6e19ff00f91426a161de appended an ` %s` suffix to `init_login_popup_failed_reason` to display the cause string. Before this change, there already exists a german translation of the string. Thus, if your language is german, you get the old german string (without ` %s`) instead of the new english string (with `%s`).

**Comment by Lineflyer** [comment]
@UniQP Now you left me behind completely.
For me in the current nightly 2016.04.03-NB it still looks like in the above screenshot. Independently of the selected language,

**Comment by rsudev** [comment]
I was on vacation the last week, will sync crowdin right away.

**Comment by Lineflyer** [comment]
@UniQP Reading it through again I got what you mean. Thats logical.

**Comment by UniQP** [comment]
In theory, this should be fixed due to 3e528c3040960bed71655e5059f1e7aea05797e2.

**Comment by kumy** [comment]
Only .de translation has the new string translated. ie: all other languages should see the default/english one.

**Comment by kumy** [comment]
@rsudev @Lineflyer when in our process is sent the mail to ask for translators to work?

**Comment by rsudev** [comment]
Usually around a week before the intended release date.
Currently I would definitely wait until the lists topic is really finalized

**Comment by Lineflyer** [comment]
Showing up as intended now once new strings have been up/downloaded to/from Crowdin.
2016.04.05-NB
