### ISSUE TITLE
No back navigation on action bar in Setting sub menus

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5602]
##### Detailed steps causing the problem:
- Open Menu -> Settings
- Open any of the sub menus below (e.g. Services)
- Press the c:geo icon on the top left
##### Actual behavior after performing these steps:

Nothing happens (also no back indicator displayed)
##### Expected behavior after performing these steps:

Go back one level
##### Version of c:geo used:

2016.03.29-NB
##### Is the problem reproducible for you?

Yes
##### Other comments and remarks:

Probably not a new bug

**Comment by kumy** [comment]
I confirm, this isn't a new bug.

However, I've used c:geo for the first time on a tablet this week-end. Our design is not tablet friendly at all. I would love to see that change. We could use `v7 Preference Support Library` (Gradle: `com.android.support:preference-v7:23.2.1`) (I think this would need upgrading to `com.android.support:appcompat-v7:23.2.1` #4903). Then we could display nice settings UI like http://developer.android.com/images/ui/settings/settings-headers-tablet.png / http://developer.android.com/images/ui/settings/settings-headers-handset.png

More generally, migrating technically to `Fragments` could help us going to a new design... ie #5111

See also:
http://developer.android.com/tools/support-library/features.html
http://developer.android.com/guide/topics/ui/settings.html

This would need to be discussed on another use (I'll open it later)

I propose not to pass much time here (unless a quick fix is available...)
