### ISSUE TITLE
Create account menu is doubled for some connectors

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5603]
##### Detailed steps causing the problem:
- Open Menu - Settings - Services - geocaching.com
- You will see an "Create account" menu entry in the section "Information"
- Open the authentication screen
- You will see another "Create account" menu item

- Go to Menu - Settings - Services - opencaching.*
- You will see an "Create account" menu entry in the section "Information"
- Open the authentication screen
- You will **not** see  "Create account" menu item

##### Expected behavior after performing these steps:
We should clean this up to have it only at one place.
For me having it in the authentication screen rather than in the "information" section looks more straight forward.

##### Version of c:geo used:
2016.03.29-NB

##### Is the problem reproducible for you?
Yes

**Comment by kumy** [comment]
Assign to me

**Comment by Lineflyer** [comment]
@Kumy:
No more doubled "Create Account" fields, however my proposal would have been the other way around, see above:

> For me having it in the authentication screen rather than in the "information" section looks more straight forward.

Anyway I am fine with closing this as it is?!

**Comment by kumy** [comment]
ho sorry. don t close. I ll update all of them.

On March 31, 2016 12:35:19 PM GMT+02:00, Lars <notifications@github.com> wrote:
>@Kumy:
>No more doubled "Create Account" fields, however my proposal would have
>been the other way around, see above:
>
>> For me having it in the authentication screen rather than in the
>"information" section looks more straight forward.
>
>Anyway I am fine with closing this as it is?!
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5603#issuecomment-203873191

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
just seen that one button is still present on GK service setting. I have to remove it.

**Comment by Bananeweizen** [comment]
I just removed that button in https://github.com/cgeo/cgeo/commit/cf84ff27382441f4a80c895413f5bba69e4f0428. Used the wrong issue number...

**Comment by kumy** [comment]
Thanks.
I've also dropped remaining `fake_pref_keys`

**Comment by Lineflyer** [comment]
@kumy Thats perfect now. A small remark: Wouldn't it be meaningful to reuse the (already translated) string for "Create account" as it was used in the upper menu before instead of creating a new one which will again need translation?

**Comment by Lineflyer** [comment]
Will take that into a new issue.
