### ISSUE TITLE
cgeo doesn't build on android Studio

### ISSUE THREAD

**Issue by morice-net** [cgeo/cgeo#5612]
##### Detailed steps causing the problem:
Launch a build on android studio with the current master

##### Actual behavior after performing these steps:
Build failed (for missing files):
/.idea/modules/cgeo.iml
/.idea/modules/cgeo-calendar/cgeo-calendar.iml
/.idea/modules/cgeo-contacts/cgeo-contacts.iml
/.idea/modules/main/main.iml
/.idea/modules/mapswithme-api/mapswithme-api.iml
/.idea/modules/showcaseview/showcaseview.iml

##### Expected behavior after performing these steps:
cgeo build succeeds

##### Version of c:geo used:
Any pull after the commit f2ef045 (03-20-2016)
master

##### Is the problem reproducible for you?
Yes

##### System information:
Android studio, Open SuSE KDE

##### Other comments and remarks:
Build was working before the move of the missing files and is still working if I jump back before the commit f2ef045 (03-20-2016)

Many thanks in advance

**Comment by UniQP** [comment]
Does it work when you install the "Local Maven repository for Support Libraries" via the Android SDK Manager?

**Comment by Bananeweizen** [comment]
Thanks for this report. You saved my day. I just tried building on a new laptop with a mixture of 3 different Android Studio versions installed, a broken Android SDK and this problem. Reading the issue made me finally separate those 3 problems.

I reverted the mentioned commit.
