### ISSUE TITLE
Importing from send2cgeo does not add caches to the current list

### ISSUE THREAD

**Issue by haarspalter** [cgeo/cgeo#5613]
##### Detailed steps causing the problem:
- Select a list
- Perform an import from send2cgeo, Cache already exists in another list

##### Actual behavior after performing these steps:
Cache is download, but not added to the list

##### Expected behavior after performing these steps:
Cache should be added to the currently opened list

##### Version of c:geo used:
nightly 2016.03.24-NB-1ec1adc

##### Is the problem reproducible for you?
Yes

##### System information:
Device: D6503 (D6503, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.264
Cgeo version: 2016.03.24-NB-1ec1adc
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present Direction sensor used: rotation vector Hide own/found: true Map strategy: auto HW acceleration: enabled (default state) System language: de_DE Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM Installed cgeo plugins: calendar

**Comment by Lineflyer** [comment]
Duplicate and already solved.
@haarspalter Could you please update to the newest nightly and report back in #5564 if it is fixed for you.
