### ISSUE TITLE
Navbar covering bottom of screen

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#5614]
On latest version application  navbar is covering bottom of screen with nickname and GPS info etc.
See screens:
![screenshot_20160331-205336](https://cloud.githubusercontent.com/assets/8573382/14187621/3599e9ca-f784-11e5-9a2a-c13d15673949.png)
![screenshot_20160331-205441](https://cloud.githubusercontent.com/assets/8573382/14187622/35b9d758-f784-11e5-9501-e161bd59cbcd.png)

##### Version of c:geo used:
2016.03.31-NB-68ea5ac

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: LG-D802 (exodus_d802, LGE)
Android version: 6.0.1
Android build: MHC19J release-keys
Cgeo version: 2016.03.31-NB-68ea5ac
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: pl_PL
Geocaching sites enabled:
- geocaching.com: logged in (Nazwa użytkownika OK) / BASIC
Installed cgeo plugins:  none
--- End of system information ---

**Comment by pstorch** [comment]
Might be related to #5594.
Maybe we have to put the attribute I removed onto the  mainactivity layout file.

**Comment by kumy** [comment]
Didn't saw I was impacted by this bug ;)
Confirmed fixed for me.

**Comment by Eselter** [comment]
Great. Waiting for new nightly ;)
