### ISSUE TITLE
Squash on merge?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5617]
https://github.com/blog/2141-squash-your-commits

I'm in favor of only allowing squash merging. That way our history no longer contains "sprinkled" commits, if someone worked over multiple times and commits on a feature that was later merged via pull request (and where some other commits where done over the same time span on master).

(The problem isn't that big in our repository, since most of the time there isn't much overlap. At work we are pushing up to 200 times per day on my current project in multiple parallel feature branches, and developers basically got insane trying to read the history before we activated cherry-pick-merging in our gerrit review system)

What's your opinion?

**Comment by kumy** [comment]
As we have the choice at the merging stage, we could activate it and test it for some pull requests.
I m in favor of it.

On April 1, 2016 9:01:39 PM GMT+02:00, Michael Keppler <notifications@github.com> wrote:
>https://github.com/blog/2141-squash-your-commits
>
>I'm in favor of only allowing squash merging. That way our history no
>longer contains "sprinkled" commits, if someone worked over multiple
>times and commits on a feature that was later merged via pull request
>(and where some other commits where done over the same time span on
>master).
>
>(The problem isn't that big in our repository, since most of the time
>there isn't much overlap. At work we are pushing up to 200 times per
>day on my current project in multiple parallel feature branches, and
>developers basically got insane trying to read the history before we
>activated cherry-pick-merging in our gerrit review system)
>
>What's your opinion?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5617

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by UniQP** [comment]
I'm totally against squashing all commits of a pull request into a single commit. If I submit a pull request containing multiple commits, the changes are in separate commits for a reason.

**Comment by samueltardieu** [comment]
I would rather be against using this, for many reasons:
- commits may represent incremental steps which are easier to re-read later and more useful when bisecting to find a bug (and to revert);
- we already request that people clean up their pull requests when it makes sense;
- people might be working on top of someone else work (or their own work in another branch), and cherry-picking commit breaks this.

You might want to do that for contributors who do not group small unrelated changes and you do not want to spend time educating them or arguing with them, but do not make it the only option as I think it encourages bad practices instead of educating people.

**Comment by pstorch** [comment]
I practiced squashing of commits here the first time. Previously I just read about it and tested it in a tutorial. 
Now I got used to it and squash before opening a PQ. 
I don't know if it is necessary to enforce or automate it.

**Comment by kumy** [comment]
From my point of view, enforcing is not good. But having the possibility to do it is not bad.

**Comment by Bananeweizen** [comment]
Okay, I take that as a sign to have both options enabled (which is the new default anyway). Developers doing the merge can then decide to squash in case they see this necessary. Thanks for the discussion.
