### ISSUE TITLE
When logging a cache, move cache to a specific list

### ISSUE THREAD

**Issue by haarspalter** [cgeo/cgeo#5627]
##### Feature Requst/Suggestion:
A configuration option could be added to define, if a cache should be move to a specific list right after logging it (offline/online). The target list could either be a configurable one, or a fixed/predefinged one that is supposed to contain finds (when logging online) or caches to log online when doing offline logging.
After moving the cache to the target list, it would be removed from all other lists.

**Comment by Lineflyer** [comment]
I do think this is too specific (a usecase for only some users). Generally there are lot of other ways where this can be done, e.g.:
- Look at history to see your finds
- Filter a list for Status/Found or Status/Not Found
- Select all found after your caching day and move them manually

Aditionally this would require some checks: What do do if the user deleted the list he selected as target.

**Comment by haarspalter** [comment]
I agree that it might be quite a quite specific issue, this is why I would make it configurable. Use case here is that I have two lists imported from GSAK, and maybe another TODO list. Once logging a cache, I am currently moving it to a "finds" list, and removing it manually from others.
It is not mainly about seeing the finds, but more about keeping the lists in good shape.

If the list does not exist, I would just not do the move, maybe showing a message. User could then fix the configuration issue,

**Comment by SammysHP** [comment]
I'm also of the opinion that this is too specific.

**Comment by haarspalter** [comment]
What would also help, and might be much less specific, would be to have a button "move" next to the new "store in list" button that moves the current cache to a list, removing it from all others.

**Comment by Bananeweizen** [comment]
I think this is a useful feature request if we modify it slightly. I would only add the found cache to a certain list, but not delete it from others. That is exactly the use case of adding a tag.

Additionally we might need a new command in the cache list view to remove all other tags from the selected caches.

**Comment by haarspalter** [comment]
hmm, I am starting to wonder if i might use the new list/tag feature in a wrong manner. So I will try to explain my current setup:

- I am using GSAK to manage most of the caches, and my main database currently has about 4500 entries
- From that DB, I export two different gpx files. 

1. everything, except unsolved mysteries and 
2. a subset of 1. limited to the area between home and work
 

- Both gpx files are imported into c:cgeo, in two different lists (I got two lists for performance reasons, as I mainly use list 2., and having a smaller list seems to be much faster)
- In addition to those to lists, a got another one called something like "todo", where I put (or tag) caches that I would like to visit soon
- At this point, some caches might be stored in all of those 3 lists
- When I found a cache, I am doing an offline found log, and I would like to move it to a "found" list (which was easier with the old lists, even though I like the new approach much better)
- Now with the nightly build I have to store it in the "found" list, and remove it from up to 3 others

So what I would like to have, is a way to perform the "final list clean up" with less clicks.

My 1st idea was what I described in the initial feature request. Another options is described in my 2nd comment (additional move button). And in the meantime, I got another idea which would have basically  no impact on the UI, and fom code perspective, it might be quite easy to implement: Was it ever thought to support long clicks on buttons? For example, a "normal" click on the "store" button would trigger the current functionality, but a long click on the same button could trigger a "move".
If this a potential way to go, I could try to implement the required changes, and send a pull request.

**Comment by kumy** [comment]
What about the possibility to configure in settings an action/tag (or nothing) to be done for a found/not found?

On April 5, 2016 9:33:18 PM GMT+02:00, haarspalter <notifications@github.com> wrote:
>hmm, I am starting to wonder if i might use the new list/tag feature in
>a wrong manner. So I will try to explain my current setup:
>
>- I am using GSAK to manage most of the caches, and my main database
>currently has about 4500 entries
>- From that DB, I export two different gpx files. 
>
>1. everything, except unsolved mysteries and 
>2. a subset of 1. limited to the area between home and work
> 
>
>- Both gpx files are imported into c:cgeo, in two different lists (I
>got two lists for performance reasons, as I mainly use list 2., and
>having a smaller list seems to be much faster)
>- In addition to those to lists, a got another one called something
>like "todo", where I put (or tag) caches that I would like to visit
>soon
>- At this point, some caches might be stored in all of those 3 lists
>- When I found a cache, I am doing an offline found log, and I would
>like to move it to a "found" list (which was easier with the old lists,
>even though I like the new approach much better)
>- Now with the nightly build I have to store it in the "found" list,
>and remove it from up to 3 others
>
>So what I would like to have, is a way to perform the "final list clean
>up" with less clicks.
>
>My 1st idea was what I described in the initial feature request.
>Another options is described in my 2nd comment (additional move
>button). And in the meantime, I got another idea which would have
>basically  no impact on the UI, and fom code perspective, it might be
>quite easy to implement: Was it ever thought to support long clicks on
>buttons? For example, a "normal" click on the "store" button would
>trigger the current functionality, but a long click on the same button
>could trigger a "move".
>If this a potential way to go, I could try to implement the required
>changes, and send a pull request.
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5627#issuecomment-205960306

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by haarspalter** [comment]
If one of the actions is e.g. "assign tag xyz, and clear other tags", this would be quite close to perfect. And if tag/list does not exist, it could be created automatically, which should match quite well the "tag" metaphor

**Comment by pstorch** [comment]
I think, when we implement the #5550, then this use case would be much easier.
Just open the List selection dialog and tick the "found" list and untick the others.
