### ISSUE TITLE
Changed Waypoint Title overwritten on Refresh

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5636]
##### Detailed steps causing the problem:
- Step 1: Have a cache stored with at least one waypoint
- Step 2: Edit the waypoint and change the title
- Step 3: Refresh the cache

##### Actual behavior after performing these steps:
Title is reverted

##### Expected behavior after performing these steps:
Changed title is kept

##### Version of c:geo used:
Master from two weeks ago with mapsforge change

##### Is the problem reproducible for you?
Yes

**Comment by SammysHP** [comment]
People told that this also happens with the description.

**Comment by SammysHP** [comment]
Some people complain that changes to a listing waypoint are not updated, so that they didn't notice a change of the listing. This might be related.

**Comment by Lineflyer** [comment]
Mmh.. is that a new behaviour if you change a waypoint which is server defined?
IMHO not. What must not happen: If the listing on server contains a waypoint without coords and the user enters coords, they should be kept.

**Comment by SammysHP** [comment]
The description was modified by the user and later changed by the owner (new question).

**Comment by Lineflyer** [comment]
OK.. Now we have three fields of the waypoint in this discussion: Title, Description and coords.
Which one is now restored to server values on refresh and which shall and which not?
Shall I test it?

**Comment by rsudev** [comment]
Here I specifically mention the name field, as it was reported. I think coords and description are left alone always.

**Comment by Lineflyer** [comment]
I retested it with current release 2016.03.06:
- Title is always replaced by server data
- Coords are always replaced by server data
- Description is kept as used modified it

I think quite some time ago this was what we did intentionally.

Do I need to test with `master`as well?
I assume there should be no changes?!

**Comment by pstorch** [comment]
Interesting:

Add something to the description text and hit refresh. The modified description stays as I edited it.
Remove half the original description, hit refresh and the original description is restored.

**Comment by pstorch** [comment]
Just verified in the codebase. The longer description text wins:

```
        if (note != null && old.note != null && old.note.length() > note.length()) {
            note = old.note;
        }

```

**Comment by pstorch** [comment]
Should we make the title readonly to prevent confusion? At least as long as we haven't decided about #5353. The user can still add some information to the description field if needed. But we should really separate the user content from server content, to be able to refresh properly.

**Comment by Lineflyer** [comment]
According to the last clue and the test results above...I think its fine like it is to prevent the user from using modified data.
The remaining issue should be covered with #5353 

Feel free to reopen if you disagree.
