### ISSUE TITLE
Prompt user when unassigning cache from last list?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5638]
##### Detailed steps causing the problem:
- Save a cache
- Make it belongs to multiples lists
- Open cache details tab
- Select "Remove from list" one by one.
##### Actual behavior after performing these steps:

I can remove the cache from all list. The cache details is still shown. If I press back the cache isn't listed anymore.
##### Expected behavior after performing these steps:

This may be confusing.

I would imagine:
a) A popup ask me if I'm sure to do that? -> "Your cache will not be attached to any list... And will be removed from device. Are you sure?"
b) Can't remove the last list
c) ?
##### Version of c:geo used:

master branch
##### Is the problem reproducible for you?

Yes
##### System information:

N/A
##### Other comments and remarks:

I'm wondering what is the future of this stored cache not belonging to any list? Will it be dropped/purged after 3 days(?) expiration time?
Is this different from using the "Drop" button?

**Comment by Bananeweizen** [comment]
Please no additional prompts. B is the obvious solution that just restores the previous handling before introduction of multiple lists. At least that is how I think about it. Other opinions?

**Comment by Lineflyer** [comment]
B is good.

**Comment by kumy** [comment]
b) is ok for me.

On April 5, 2016 9:14:34 PM GMT+02:00, Michael Keppler <notifications@github.com> wrote:
>Please no additional prompts. B is the obvious solution that just
>restores the previous handling before introduction of multiple lists.
>At least that is how I think about it. Other opinions?
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5638#issuecomment-205953870

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pstorch** [comment]
The `DataStore.cleanIfNeeded()` removes Caches which are not on any List after 3 days. Drop button just removes from all Lists. `Drop` removes from Cache and DB immediately.
If we agree on `b)` then the user has to use the `Drop` button. Which is ok for me.

**Comment by SammysHP** [comment]
> Drop removes from Cache and DB immediately.

That did not happen before the introduction of multiple lists. If you hit drop by accident it was possible to store it again without network. If this is not possible anymore we must either restore this behavior or add a dialog (but I'd be not happy with that).

**Comment by Lineflyer** [comment]
Agree to @SammysHP

**Comment by pstorch** [comment]
I'll check the current Drop behaviour and correct if needed.

**Comment by pstorch** [comment]
No need to change anything. If Drop is clicked, the Cache is just "marked" as dropped and removed from CacheCache. When clicking "Store in list" afterwards it's **not** downloaded and parsed again.

**Comment by SammysHP** [comment]
@pstorch 
I tried exact these steps and the cache was downloaded again.

**Comment by Lineflyer** [comment]
>  If Drop is clicked, the Cache is just "marked" as dropped and removed from CacheCache.

Thats the point...it should **not** be removed from the CacheCache, or am I wrong?

**Comment by pstorch** [comment]
Coming back to this one.

At the moment there are two cases:

1. when "drop" is selected, the cache is "marked" as deleted (removed from all lists) in database **PLUS** removed from CacheCache. I compared it with the version before the implementation of the multi list feature and it hasn't changed. So it behaves like before.

1. when "manage" ist selected and all checkboxes are cleared: the cache is removed from all lists (same as above), but **NOT** removed from CacheCache.

In both cases we have the automatic cleanup after some days.

Is there any need to change the current behavior?

**Comment by Bananeweizen** [comment]
Do we have to do anything here or can we close it? I'm personally perfectly fine with the cache vanishing. I don't think we _have to_ put every deleted cache into that 3 days hidden trashbin. To my understanding this hidden storage is mostly needed for caches which are opened in cache details (but never stored) or used from the live map (but never stored).

**Comment by SammysHP** [comment]
There should be some kind of rollback mechanism in case the user did something stupid like accidentally deleting a cache (and no network). We even thought about adding another history page with recently deleted caches in another issue.

**Comment by Lineflyer** [comment]
Without having a clear view on the current function under the hood I would say it this way:
Regarding this issue, we should probably make the case of "Removing from last list" the same behaviour as explicitly selecting "Drop". 

By doing so, we probably won't get any new side effects which we do not think about right now.
If other general changes are required (e.g. regarding CacheCache) we can discuss and decide seperately.

**Comment by SammysHP** [comment]
If we add another history page with recently deleted caches (as suggested in another issue), we can add a "remove from device" button there. Thus it had a trash semantic (move to trash, trash can be emptied or will be emptied automatically after 3 days). This might solve also some other issues like a way to remove all cache data if wanted.

**Comment by Lineflyer** [comment]
I will remove this issue from the ToDo for next release as I don't consider it critical.
Lets however keep it open in general as I can't see a majority for leaving it as it is.
