### ISSUE TITLE
Android 6 specific: Only c:geo itself offered for "Open in Browser"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5641]
##### Detailed steps causing the problem:
- Android 6 device
- Open cache details
- Select "Open in browser" from menu
##### Actual behavior after performing these steps:

Only c:geo and "c:geo internal browser" are offered as an option
##### Expected behavior after performing these steps:

All apps supporting the URL should be listed
##### Version of c:geo used:

2016.03.06
##### Is the problem reproducible for you?

Don't own a Android 6 device but reported on FB and support mail
##### Other comments and remarks:

The solution is to go to the Appmanager of the device, go to c:geo and deselect to open Supported URLs only within the app.
The question is, can we influence this setting to have another default (i.e. allow opening with other apps) or do we have to live with it and e.g. add a FAQ-entry?

**Comment by Eselter** [comment]
I have only c:geo and chrome (default browser for me)  I don't see stock browser.

**Comment by Eselter** [comment]
For me default setting in app manager is ask every time. But I never choose c:geo as default app for this links.

**Comment by Eselter** [comment]
When I clear defaults for chrome I see other browser and c:geo app.

**Comment by Eselter** [comment]
I think this is not a bug.

**Comment by Lineflyer** [comment]
@eselter Are you on Android 6?

**Comment by Eselter** [comment]
Yes (CM13)

**Comment by Lineflyer** [comment]
You are right. I retested a clean installation of c:geo 2016.03.06 with CM13.
The default setting is that it shows all available apps.

The user might have changed the "Supported URL" setting manually. Closing.

**Comment by Lineflyer** [comment]
This seems more complicated than I thought at first:

I did some more play around on Android 6.
Don't know the exact technical difference compared to older Android versions, however to me it looks as if Android 6 does no longer distinguish between different supported URLs.

Test case:
1. Clear all defaults for c:geo in your app manager
2. Open browser and enter the URL http://coord.info/GC77 
3. When prompted select c:geo as default (you may have to do step 2 twice in order to be able to do so)
4. Open c:geo
5. Open a cache and select "Open in browser"
6. Only "c:geo" and "c:geo internal browser" are offered

AFAIR on Android <6 the default was only valid/used for one type of URL, so one could set c:geo as default for coord.info/* but still be asked for www.geocaching.com/seek/cache* .
This is no longer the case in Android 6

**Comment by Hauwertlhaufn** [comment]
On my Nexus 5 with Android 6.0.1 and 2016.04.24-NB-44c7085 I can open the link  http://coord.info/GC77 in c:geo via default. When I now select "Open in browser", it automaticly uses chrome.
But when I go to the system-settings and set "App-Links" for cgeo as "open in this app" (I don't know if it is exactly the name, because I use it in german) I can reproduce the problem.

**Comment by Lineflyer** [comment]
I do now own a new Android 6 device and could reproduce this instantly after clean new installation of c:geo and all other apps.

Share will only present "c:geo internal browser" and "cgeo" until I manually change the mentioned setting in the device app manager.
Isn't there a way to influence this behaviour or modify our "open in browser" NOT to use the own app?

**Comment by Lineflyer** [comment]
As there are still quite some requests on support mail I created a FAQ entry: http://www.cgeo.org/faq.html#open-in-browser

**Comment by Lineflyer** [comment]
Nothing we can do about that. Its a system problem.
Recently I changed the target URl to avoid doubled app selection.

Fact is, that if a user does not assign c:geo to be default to be opened all works normal
