### ISSUE TITLE
Sharing a cache opens Locus automatically

### ISSUE THREAD

**Issue by haarspalter** [cgeo/cgeo#5643]
##### Detailed steps causing the problem:
- Open details of a cache
- Select "Share Cache"
- Short list of share targets opens, select "view all"

##### Actual behavior after performing these steps:
- Locus opens, and displays the cache
- After pressing Back and leaving Locus, the list of all share target is shown in c:geo

##### Expected behavior after performing these steps:
- List of all share targets should be shown, allowing to select Locus
- Locus should not be triggered automatically

##### Version of c:geo used:
2016.04.07-NB-8b891da

##### Is the problem reproducible for you?
Yes

##### System information:
Device: D6503 (D6503, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.264
Cgeo version: 2016.04.07-NB-8b891da
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present Direction sensor used: rotation vector Hide own/found: true Map strategy: auto HW acceleration: enabled (default state) System language: de_DE Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM Installed cgeo plugins: calendar

**Comment by rsudev** [comment]
I was able to reproduce this right away...

**Comment by Lineflyer** [comment]
Can reproduce this issue on my device (Samsung Galaxy S4, Android 5.0.1):

**Comment by akkatracker** [comment]
https://youtu.be/iW72bnJMZUY

In case someone cannot reproduce here's what it looks like
