### ISSUE TITLE
Android 6: Completely selected text can not be translated

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5647]
##### Detailed steps causing the problem:
- Open cache details
- I start selection mode by tapping on a word
- I can select all options in the floating menu (Translate, Copy, Share, Select all)
- From this menu I select "Select all"
##### Actual behavior after performing these steps:

Now the context menu only shows Copy and Share (no more Translate)
##### Expected behavior after performing these steps:

All options like initially offered should also be offered after selecting "Select all"
##### Version of c:geo used:

2016.03.06
##### Is the problem reproducible for you?

Yes
##### System information:

Samsung Galaxy S3
CM13 Android 6.0.1
##### Other comments and remarks:

On my S4 with Stock ROM Android 5.0.1 this is working as intended

**Comment by Eselter** [comment]
True. Custom transaltion option like "Transalte to english" and "Transalte to system language" is not avaible anymore after selecting all text but stock option to translate from android 6.0.x is still avaible.

**Comment by Lineflyer** [comment]
setting for restest. Assigning myself.

**Comment by Lineflyer** [comment]
Closing this outdated issue.
