### ISSUE TITLE
Send2cgeo PIN not showing up (finish locale)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5650]
##### Detailed steps causing the problem:
- Finish language
- Use "Register" in send2cgeo service to obtain a PIN from our server

##### Actual behavior after performing these steps:
Instead of the PIN `###` is shown.
![sen2cgeo problem](https://cloud.githubusercontent.com/assets/949669/14389289/41f570c0-fdb2-11e5-9121-cbf20f746b74.jpg)

##### Expected behavior after performing these steps:
PIN is shown.

##### Version of c:geo used:
206.03.06

##### System information:
Finish language

##### Other comments and remarks:
I suspect the problem might be that the translation is wrong. The english original contains `####` as a placeholder while finish misses on `#`
Can someone confirm this reason, then I will correct it on Crowdin.

**Comment by kumy** [comment]
I ve seen that replacement in code not long time ago. You re assumption seems good for me.

However this part of code should be replaced by %s... I ll do, unless someone do it before me.

On April 8, 2016 5:50:56 PM GMT+02:00, Lars <notifications@github.com> wrote:
>##### Detailed steps causing the problem:
>- Finish language
>- Use "Register" in send2cgeo service to obtain a PIN from our server
>
>##### Actual behavior after performing these steps:
>Instead of the PIN `###` is shown.
>![sen2cgeo
>problem](https://cloud.githubusercontent.com/assets/949669/14389289/41f570c0-fdb2-11e5-9121-cbf20f746b74.jpg)
>
>
>
>##### Expected behavior after performing these steps:
>PIN is shown.
>
>
>##### Version of c:geo used:
>206.03.06
>
>
>##### System information:
>Finish language
>
>##### Other comments and remarks:
>I suspect the problem might be that the translation is wrong. The
>english original contains `####` as a placeholder while finish misses
>on `#`
>Can someone confirm this reason, then I will correct it on Crowdin.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5650

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rsudev** [comment]
This targets release, right? So we need to run a crowdin and manual re-translation cycle once it is fixed. Or should we fix finnish on crowdin for release and do the real fix on master only?

**Comment by Lineflyer** [comment]
We should fix the string as is on Crowdin for release and only apply the real fix on master.

**Comment by Lineflyer** [comment]
AFAICS finnish translation has been updated to fix this bug.
@rsudev Can you doublecheck and eventually import the fix to `release`?

**Comment by rsudev** [comment]
String was changed, imported to release and master

**Comment by Kuitsi** [comment]
I managed to update Finnish translation before version 2016.04.12 was released, so this has been fixed already in that version.
