### ISSUE TITLE
Strange date format in logbook

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5651]
##### Detailed steps causing the problem:
- Open Logbook of a cache

##### Actual behavior after performing these steps:
Dates are truncated as there is a prepended weekday
![screenshot_2016-04-05-15-27-56](https://cloud.githubusercontent.com/assets/949669/14389453/f96ccf6e-fdb2-11e5-8cd2-02f9186348fc.png)

##### Expected behavior after performing these steps:
Date should fit

##### Version of c:geo used:
2016.03.06

##### Is the problem reproducible for you?
Reported on support mail for the device mentioned below

##### System information:
```
--- System information ---
Device: RAINBOW JAM (s5254, WIKO)
Android version: 5.1
Android build: ALPS.L1.MP6.V2_TINNO6580.WE.L_P4
Cgeo version: 2016.03.06
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
Geocaching sites enabled:
- geocaching.com: not logged in (Anmeldung…)
Installed cgeo plugins: contacts
--- End of system information ---

```

##### Other comments and remarks:
Is this a device specific issue?
I have never seen this type of date format in c:geo before.

**Comment by Bananeweizen** [comment]
#1713
#4688
and maybe others

To my mind that is _always_ an issue with the Android system on that device, using some wrong combination of locale and date format settings.

**Comment by rsudev** [comment]
Should we add a sample of the Android date format in use to system information, to verify this? Should we provide some setting to override the system format, in case the user has no chance to do anything about it?

**Comment by samueltardieu** [comment]
@rsudev Done

**Comment by samueltardieu** [comment]
Probably due to Wiko bug. Closing.
