### ISSUE TITLE
Offline map folder can not be manualy selected

### ISSUE THREAD

**Issue by kurly1** [cgeo/cgeo#5652]
On my Android 6 HTC phone I cannot select manually a map folder.

##### Detailed steps causing the problem:
- going to Menu -> Settings -> Map -> Directory with offline maps
- select "Choose Directory"

##### Actual behavior after performing these steps:
In the opening directory chooser I can only select the top directories like /sdcard, /sdcard2 and the second Level in the folder /storage such as /storage/emulated, /storage/ext_sd or /storage/6164-6562. Below this level I see no other directories of the directory tree.

##### Expected behavior after performing these steps:
In the opening directory chooser I should see the full directory tree of the phone down to the directory holding the offline map files.

##### Version of c:geo used:
2016.03.06

##### Is the problem reproducible for you?
Yes, I even reinstalled the app

##### System information:
Device: HTC One_M8 (vodafone_ch-de, htc)
Android Version: 6.0
Android build: MRA58K release-keys
Cgeo Version: 2016.03.06
Google Play Services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: Rotation vector
Hide own/found: flase
Map strategy: Auto
HW acceleration: enabled (Default state)
System language: de_DE
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: none

**Comment by Lineflyer** [comment]
Can you pleast post a screenshot of the directory chooser unable to select the directory?
AFAIK we use dirchoosers offered by the system (so they might be different from device to device) and I am not sure if one of them might be buggy.

**Comment by rsudev** [comment]
@kurly1 Any update on this? Unsure how to create a screenshot?
Don't hesitate to come back with further questions if something is unclear.

**Comment by kurly1** [comment]
Hi rsudev

Sorry, I didn't found the time to create a screenshot. Meantime the issue is fixed, most likely with a update of the HTC file manager.

Thanks anyway.

**Comment by polarbearing** [comment]
Using 2016.06.09, I have the same issue. More specifically, I cannot select the any folder in a directory tree. I can tap into sub-folders as long as they are not the last one. Thus I never get the map file. Same behaviour for external SD card and internal memory, however in internal the map is found automatically. 
Samsung Tab A, Android 5.1.1
Screenshot follows.

**Comment by Lineflyer** [comment]
@polarbearing You have to select the folder not the file. Your screenshot looks perfectly fine.

Please update to the latest version nontheless.

**Comment by polarbearing** [comment]
I cannot select the final folder, mapsforge_for_cgeo, in which the map file resides.

**Comment by Lineflyer** [comment]
Why not?
According to your screenshot you should simply select the tickbox in front of it and press OK.

**Comment by polarbearing** [comment]
Interesting, there are tickboxes indeed. They are nearly invisible. Now that I know they are there, and I pump up the brightness, I can figure them out. Now I can set the green tickmark in front, and get an OK button.

Please consider to make the tickboxes more visible.
