### ISSUE TITLE
Introducing the OKAPI changelog

### ISSUE THREAD

**Issue by following5** [cgeo/cgeo#5654]
This is no c:geo issue, but an information to all c:geo developers. If there is another way to do this (e.g. a mailing list), please let me know.

A changelog has been added to OKAPI, to keep the application developers informed: http://opencaching.de/okapi/changelog.html

You may also subscribe to the RSS feed on that page.

**Comment by rsudev** [comment]
Thanks for the info. I will look for a place to link this in our wiki or ReadMe

**Comment by Bananeweizen** [comment]
Closing (just to make scanning open issues easier).
