### ISSUE TITLE
Coverity - static analyse tool 

### ISSUE THREAD

**Issue by Hadatko** [cgeo/cgeo#5655]
Hi,
we started use Coverity for analyse code at work. This tool is also available for open-source projects. For more information: https://scan.coverity.com/github

I was wondering how much bugs it will found for cgeo application.
I tried it on assembleDebug target and it found only 49 defects in code. So thanks, you are doing great job ;)

If you agree cgeo can use coverity time to time (it can be executed in periods). And we can fix these issues ;)

This tool use famous project like python, perl, ruby and another ...

**Comment by rsudev** [comment]
What does it offer in addition to codacy, which we started to use recently?
In general, as c:geo is open-source, you of course may let the source-code get scanned and you also anytime can create issues based on those scan results.
If there are critical issues you would not like to publish, you can also reach us through our support mail or IRC channel (details see http://cgeo.org)

**Comment by Hadatko** [comment]
Here are results: https://scan.coverity.com/projects/cgeo
I can made result public, or add you to view details.

**Comment by mucek4** [comment]
If you have time, you can create pull request(s) with fixes.

**Comment by Bananeweizen** [comment]
I just checked it with my own account. To me that tool is not attractive:

- I have to download a local tool, which then uploads builds for analysis. No "where your is git url, let me do that for you"
- scans are limited to 3 or 4 per day

There are so many more alternatives out there which are more easy to use and produce up to date results after each commit. 

So by now we use Findbugs, Checkstyle, Android Lint and Codacy. I see no need to add coverity.

**Comment by Hadatko** [comment]
Ok i will try fix them time to time. Right now i am new in android and in this application. It will be good start if i will understand it...
