### ISSUE TITLE
Mapsforge 0.6: Several themes not rendering

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5664]
##### Detailed steps causing the problem:
As written also in this [comment](https://github.com/cgeo/cgeo/issues/5047#issuecomment-208069617) for me the "New map" kept showing nothing. 
At the end I found out that some of my installed themes do not work.
Have to take a deeper look but a quick test shows that only the predefined "Standard" seems to work.

@rsudev Should user defined themes already be supported?

##### Version of c:geo used:
2016.04.11-NB

##### Is the problem reproducible for you?
Yes

**Comment by rsudev** [comment]
All themes I have on my device (andromaps_*, ele* old variant, ele* svg) work with the Openandromaps Germany file from two weeks or so ago.
So in order to analyze it, it would be good to reproduce it with a small map file (like berlin) and than bundle the file and theme folder in a package to try it on my device.

**Comment by Lineflyer** [comment]
@rsudev 
Here we go: https://www.dropbox.com/s/tr7uq0w8y0i88ix/issue_5664.zip?dl=0

This is a up to date Hamburg.map from openandromaps.org and a hiking theme from openandromaps.org (non elevate) downloaded February, 19th 2016.
The combination works well in current mapsforge implementation but shows an empty map on the new implementation.

**Comment by Lineflyer** [comment]
Additional info:
This seems a little strange on my device.
When changing the theme will on the new map sometimes themes do not work which worked just some minutes before on the same map instance.
So it could also be some bug in the file selection or alike.

**Comment by rsudev** [comment]
I was now able to reproduce this issue on the emulator. Looking into the generated errors and the mapsforge sources, I wonder now why it works on my device...

**Comment by rsudev** [comment]
Mystery hopefully solved.
There exists two variants of the andromap themes: orux and locus
The locus variant (used by lineflyer) contains an attribute in the initial rendertheme tag, that the official version of mapsforge 0.6 don't recognises and therefore fails the theme with an exception when building it. The orux variant (what I tested) does not contain this attribute, and therefore works.
Locus:
```
<rendertheme ... version="1" map-background="#F8F8F8" fill-sea-areas="0">
```
Orux:
```
<rendertheme ... version="1" map-background="#F8F8F8">
```
The same is also true for the elevate family of themes - the Locus variants likely will not work. So we should see whether we are able to detect the fact that the theme does not work and report back to the user in an understandable fashion.

**Comment by SammysHP** [comment]
https://geoclub.de/forum/viewtopic.php?p=1246527#p1246527

**Comment by Bananeweizen** [comment]
If this is only related to the content of the theme file we should simply override org.mapsforge.map.rendertheme.ExternalRenderTheme.getRenderThemeAsStream(), and filter out that attribute.

Does that sound reasonable or am I missing something?

**Comment by rsudev** [comment]
I would assume that the locus version does contain more specialties besides attributes on the main tag. And even just filtering might lead to undesired results, if the overall style relies on them being adhered to.

**Comment by SammysHP** [comment]
AFAIK there are three different themes involved:

1. Mapsforge <0.6, the "old" format
1. Mapsforge 0.6: Contains layer information. You can enable and disable map features in the app. AFAIK each app must include a GUI for this itself.
1. Mapsforge 0.6 Locus: Locus uses a different layer definition.

This is only what I have heard and it might be incorrect.

**Comment by rsudev** [comment]
What I see in the theme definitions is, that the old ones (andromaps_*) have version 1. Even there is a Locus and a standard version, but the older mapsforge lib seemingly does not check the theme as strict as the current one.
The current themes have version 4, which seemingly implements (in conjunction with version 0.6 of the library) the layer level customization capabilities. Even in that version there are Locus and standard themes. Mapsforge 0.6 standard rejects (likely with good reasons) to work with the Locus themes, so we just need to detect that in a good fashion. As theme loading is asynchronous I am currently not sure where I can get the information that the theme is bad.
The level-activation feature is on my radar, but I don't have a good idea yet where and how to place that selection in a good way.

**Comment by Bananeweizen** [comment]
For just avoiding a crash, I think we could subclass ExternalRenderTheme, read the XML ourselfes on creation, and in the invalid case we redirect every further method call to one of the internal render themes. Afterwards we could query the invalid state and show a message box at some sensible point of time.

**Comment by rsudev** [comment]
The app itself does not crash, just the map tiles are not rendered. I would like to avoid trying to determine the validity of a render theme on our side, so I have posted a question to the mapsforge-dev google group. If I don't get something usable from there, checking the file on our side likely is the best solution.
