### ISSUE TITLE
Support mail problems

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5670]
Two users had problems lately to contact the support mail address.

Reason:
```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its recipients. This is a permanent error. The following address(es)
failed:

support@cgeo.org:
SMTP error from remote server for RCPT TO command, host: mail.cgeo.org (193.95.241.239) reason: 550-X-Warning: 212.227.15.14 is listed at dnsbl.sorbs.net (127.0.0.15:
550 Virus Transmitting Server See: http://www.sorbs.net/lookup.shtml?212.2
27.15.14)
```

Anything we can do about that?
They reached us now, so the problem might have been temporary...but still I don't know.

**Comment by mucek4** [comment]
Server has spam checking (free version) installed. The mail was sent from the server who was listed. I can remove checking but get ready for spam.

**Comment by Lineflyer** [comment]
Seems to be only a single issue last days. Closing.
