### ISSUE TITLE
More editors for c:geo G+ account

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5671]
To whomever administrates the c:geo Google+ account:
Could you make myself an editor (or whatever role is appropriate there) in order to share posts we do to other social networks also on G+?

The information and pictures there are well outdated (2014) and I can offer to align it at least with the facebook postings.

**Comment by samueltardieu** [comment]
I am an administrator there, but only the owner can add new administrators. Assigning to @mucek4.

**Comment by mucek4** [comment]
I think it's @SammysHP account.

**Comment by samueltardieu** [comment]
Nope, it's yours @mucek4.

**Comment by Lineflyer** [comment]
@mucek4 Can you add me?

**Comment by mucek4** [comment]
Tomorrow. I am away from computer.

**Comment by mucek4** [comment]
Done.
