### ISSUE TITLE
Cannot log OC (Event) cache

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#5672]
##### Detailed steps causing the problem:
- Get an eMail
- Click on link http://opencaching.de/OC12D5C
- Try to log a Will Attend

##### Actual behavior after performing these steps:

It says “Can’t load data required to log visit”, when trying anyway a dialogue pops up:

Download of data in progress… Please try again in some seconds or check your internet connection.

##### Expected behavior after performing these steps:

Log the Will Attend.

##### Version of c:geo used:

Nightly build, first a few days old, but then just updated today to see if the error persists (it does).

##### Is the problem reproducible for you?

Yes

##### System information:

```
--- System information ---
Device: HTC Desire (htc_bravo, htc_wwe)
Android version: 4.4.4
Android build: liquid_bravo-userdebug 4.4.4 KTU84Q c5fea05051 test-keys
Cgeo version: 2016.04.15-NB-8fb79d3
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   opencaching.de: Logged in (Login OK)
Installed cgeo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:

The event is dual-listed; logging a GS cache appears to work (it loads TB data, at least; I didn't submit there).

**Comment by SammysHP** [comment]
Cannot reproduce.

**Comment by mirabilos** [comment]
In case it’s important: there were no logs before mine, and the tab Logs in c:geo is also missing (I’ve it stored on device in the state before I logged with the desktop).

Maybe if you can find an OC event with 0 logs, while having GS and OC accounts active (and holding at least a TB in the inventory, and having the option “preselect all TBs as Visited” enabled)?

**Comment by rsudev** [comment]
A look into the source code suggests, that the oc-connector did not see you as logged in at that time (for whatever reason).
Can you still reproduce the issue? I would assume it was a temporary glitch, especially as your system info indicates a successful login at that time.

**Comment by mirabilos** [comment]
rsudev dixit:

>A look into the source code suggests, that the oc-connector did not
>see you as logged in at that time (for whatever reason).

OK. Weird, I did see the login messages for all platforms.

>Can you still reproduce the issue? I would assume it was a temporary
>glitch, especially as your system info indicates a successful login at
>that time.

Interestingly enough, yes, I now can.

bye,
//mirabilos
-- 
<ch> you introduced a merge commit        │<mika> % g rebase -i HEAD^^
<mika> sorry, no idea and rebasing just fscked │<mika> Segmentation
<ch> should have cloned into a clean repo      │  fault (core dumped)
<ch> if I rebase that now, it's really ugh     │<mika:#grml> wuahhhhhh

**Comment by rsudev** [comment]
This sounds really weird. Do you have the capabilities to get logs (rooted device and catlog or Android Platform tools and abd logcat)?
If the login theory is true, it also should affect ANY log on an opencaching.de cache. Could you cross check some other cache after reproducing the issue with your primary test case?

**Comment by mirabilos** [comment]
rsudev dixit:

>This sounds really weird. Do you have the capabilities to get logs

Yes, logcat, but…

>reproducing the issue with your primary test case?

… as I said, I cannot reproduce this any more, at least not with
that one cache. I can try to do the same on another OC event with
0 logs, if I find one, and appease the owner…

**Comment by rsudev** [comment]
I interpreted your
>Interestingly enough, yes, I now can.
as that you can still reproduce it. If not, I assume a temporary login issue.
The messages are misleading, as they mainly address the context of logging on gc.com, where we really need to load the log page before being able to log. In the context of opencaching, they are only triggered by the login-status of the connector and have no relation to anything in the cache or interaction with the network at the time of logging.

**Comment by Lineflyer** [comment]
Closing due to lack of feedback / reproducibility
