### ISSUE TITLE
Locked Trackables show a wrong error message when trying to log

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#5673]
##### Detailed steps causing the problem:
1. Enter Tracking Code for a locked Trackable in Search. Example: FGY7CV
2. Try to log a "Discover"
3. Error message appears that "Download of data in progress...", even when on WLAN.

##### Actual behavior after performing these steps:
- You just can't log it (which is correct), but you have the wrong impression that your internet connection is messed up, wich is not true, because of the wrong error message.

##### Expected behavior after performing these steps:
- It should either not let you open the "log"-screen when logs are disabled for a trackable or it should tell you why you can't send this log.

##### Version of c:geo used:
2016.04.12

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 6.0.1
Android build: MMB29V
Cgeo version: 2016.04.12
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---

##### Other comments and remarks:
I love your app since 2011! Thank's for the hard work!

**Comment by rsudev** [comment]
This special case we did not yet come across. It should be easy to detect the locked status, either already on the trackable page or when loading the log page and act accordingly.

**Comment by wargarw** [comment]
I would like to work on this issue.

**Comment by Lineflyer** [comment]
@wargarw Feel free to work on this and sumbit a PR. If there are questions you should ask here or on our IRC channel.

**Comment by Lineflyer** [comment]
@prudemar Are you still working on that issue?

**Comment by samueltardieu** [comment]
Fix in #5826
