### ISSUE TITLE
Android N: Map circles not placed correct

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5676]
Reported by a user using Android N, preview 2
He wrote, that it working normal until recent udpate 2016.04.12.
##### System information:

```
--- System information ---
Device: Nexus 6 (shamu, google)
Android version: N
Android build: NPC91K
Cgeo version: 2016.04.12
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / BASIC
- opencaching.us: logged in (Login OK)
Installed cgeo plugins: calendar
--- End of system information ---

```
##### Other comments and remarks:

![androidn1](https://cloud.githubusercontent.com/assets/949669/14588396/f32d1f06-04c8-11e6-83b6-b0f563fad759.png)
![androidn2](https://cloud.githubusercontent.com/assets/949669/14588398/f671f966-04c8-11e6-94aa-907fb6207d67.png)

**Comment by akkatracker** [comment]
I tried playing around with this on my phone. Could not reproduce. 

Is there an exact sequence of actions that lead to this or is it always present?

**Comment by Lineflyer** [comment]
@akkatracker The user said it is always present and most probably started after upgrading his device to "N preview". You are also on Android N?

**Comment by akkatracker** [comment]
I've just tested on an N device and can't get it either.

**Comment by notspecified** [comment]
I can confirm the Problem! Device is Pixel C with Android N.

**Comment by akkatracker** [comment]
Hmm your comment decided to make me dig around a bit more and I can
reproduce.

Looks to be a very serious bug.

**Comment by Lineflyer** [comment]
The reported details by @notspecified are also confirmed by the user on support who sent us the original report with the screenshots:

FYI, I noticed circles work OK with offline maps, but not with Google maps. Using today's nightly.

**Comment by Lineflyer** [comment]
Meanwhile my Samsung S7 received Android N upgrade and I cannot reproduce.
Furthermore no other reports on Play.
Closing.
