### ISSUE TITLE
Remove code duplication in jenkins jobs

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5677]
We have 3 build jobs, which already differ slightly in the (script) code they use. I want to avoid that. At work we have solved this by having just one real build job, which is parameterized and all other jobs then trigger this one with a set of matching parameters. However, that has the drawback that this single job is run in different contexts, leading to jumps in every graph you create from the build.

Therefore I'm thinking that we should only extract the main shell script part from all the 3 jobs. If we create another job just for this script, and then execute it _in the workspace of the calling job_ then we should be able to have all other things remain as before, but still avoid the code duplication.

Other ideas?

**Comment by rsudev** [comment]
If this idea is feasible I cannot judge, as my knowledge of Jenkins is too limited. But the objectives I fully support (consolidate the commonalities of the build 'script' while keeping the statistics/checks separate).

**Comment by Bananeweizen** [comment]
I actually found another solution: I've extracted the main shell script into a [managed script](https://wiki.jenkins-ci.org/display/JENKINS/Managed+Script+Plugin). So if someone needs to modify that shell script, you have to go to the "Managed files" section of the global Jenkins configuration now.
