### ISSUE TITLE
Map popup multi-list issues

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5679]
##### Detailed steps causing the problem:
- Store a cache on the map
- Tap on the icon to open the popup

##### Actual behavior after performing these steps:
There are two buttons: <kbd>Refresh</kbd> and <kbd>Store</kbd>, both with only the first few characters visible and ending with "…"

##### Expected behavior after performing these steps:
The <kbd>Store</kbd> button should be something like "Manage lists". It is not possible to delete the cache (the <kbd>Store</kbd> button changed to <kbd>Drop</kbd> previously).

##### Version of c:geo used:
master (915fd8cdda437fdc2f98633d907b82289e4d3dc5)

**Comment by pstorch** [comment]
This is under development in #5550 multi list ui. 
In my PR #5658 I changed this Popup, too.

**Comment by SammysHP** [comment]
Then I'll close it as a duplicate.
