### ISSUE TITLE
Minor UI issue on main screen menu

### ISSUE THREAD

**Issue by akkatracker** [cgeo/cgeo#5680]
##### Detailed steps causing the problem:
On menu button press some of the lines run past the menu (I'll attach a picture). This may not be a cgeo problem but worth a look

##### Version of c:geo used:
Latest 

##### Is the problem reproducible for you?
Yes

##### System information:

--- System information ---
Device: A0001 (bacon, oneplus)
Android version: 6.0.1
Android build: MMB29V
Cgeo version: 2016.04.12
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_AU
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar, contacts
--- End of system information ---

**Comment by akkatracker** [comment]
![screenshot_20160420-112150](https://cloud.githubusercontent.com/assets/2032746/14660805/c2b3f5c8-06eb-11e6-9c94-73d9f3ddf636.png)

**Comment by pstorch** [comment]
I think this is related to #5371 and fixed in *master*.

**Comment by akkatracker** [comment]
@pstorch thanks fixed.
