### ISSUE TITLE
Add the possibility to allow personal notes waypoint import after changing the personal notes

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#5683]
This is a feature request for the possibility to allow personal notes waypoint import after changing the personal notes.

##### Use case example:
1. Go on a multi cache hunt
2. Store the cache locally
3. Write down A, B, C, etc. in the personal notes section of the multi cache
4. Calculate the final coord by switching between personal notes and a calculator app back and forth. When done, you have the final coord written down in your personal notes.
5. Now you have to swipe left twice and hit the "Add waypoint" button to add the final coords. The little window opens and you have to put in the numbers. My personal problem here is that I can't kepp more than 5 numbers in mind, so I enter the North coordinate, hit the tick symbol, go back to personal notes, read the East coord, go back to waypoints and enter the East coordinate.

(You see, this workflow works and the app does what it should, but it could be easier for the user I think.)

##### Expected behavior:
I personally see two possible improvements:

1. Expect the app to parse my personal notes after saving for something like "Final: N 47.123 E 8 33.123" and create the waypoint accordingly.
2. Highlight the coord in the personal notes and allow the user by clicking on it to choose "Add to waypoints" or "Update existing waypoint"... something like that

##### Version of c:geo used:
Not relevant

##### System information:
Not relevant

##### Other comments and remarks:
I love caching and your app since 2011 - big thanks to you guys!

**Comment by pstorch** [comment]
Actually cgeo already parses the Coordinates in the personal notes field after editing and is creating waypoints. The view is just not updated.
