### ISSUE TITLE
Performance issue caused by AsyncTask.execute

### ISSUE THREAD

**Issue by llweifall** [cgeo/cgeo#5685]
Developers of c:geo,

I have found that `AsyncTask.execute` has been widely used in the project.
However, this API is relatively slower on devices with system version higher than 3.0 because " AsyncTasks were executed serially on a single background thread" for systems newer than 3.0. (This is found in the [API guide](http://developer.android.com/intl/zh-cn/reference/android/os/AsyncTask.html#execute(Params...)))
While using c:geo, users can easily trigger multiple AsyncTasks and influence the performance, so I think it will help to improve the performance by changing `execute` to `executeOnExecutor` to enable real multi-thread execution.

Thanks a lot.

**Comment by samueltardieu** [comment]
We are moving away from `AsyncTask` in many places to use RxJava instead, which gives us the parallelism you're talking about.

**Comment by llweifall** [comment]
Thanks a lot for your quick explanation.
