### ISSUE TITLE
Cannot select folder for _themes in setting section.

### ISSUE THREAD

**Issue by pavelvanecekcz** [cgeo/cgeo#5687]
![vyber umisteni _themes wrong](https://cloud.githubusercontent.com/assets/10035093/14743774/9459c392-08a3-11e6-8c3b-1362e520b1ac.png)
![vyber umisteni map ok](https://cloud.githubusercontent.com/assets/10035093/14743773/94549fe8-08a3-11e6-89bd-65911c72aaee.png)
![menu ok](https://cloud.githubusercontent.com/assets/10035093/14743772/9453f7a0-08a3-11e6-8141-799ae6932a26.png)

##### Detailed steps causing the problem:
- I can select maps source folder in section offline map sources
- But i cannot select folder _themes. Only options for creating a new folder is available.

##### Is the problem reproducible for you?
Yes

##### System information:
Huawei Mate 8, Android 6.0. , allowing apps to access SD card (installed as external storage)

**Comment by rsudev** [comment]
Would you mind illustrating that with a series of screenshots? The folder selection shown might be specific to the device, so we need to see whether it is our fallback component or one provided by the system.
A test could also be, to rename the folder _themes, removing the underscore in the beginning. Some folder selectors might treat such folder names specally.
You could also check whether the map file selection dialog allows you to navigate to that folder, to verify that access permission issues are unlikely.

**Comment by pavelvanecekcz** [comment]
Hi, 

 

Later I already attached 3 screenshots. Please read them from below to top.

1.       Main setup menu .. O.K.

2.       Selection od maps folder  … O.K.

3.       Selection od _themes folder … WRONG  / there are no option to go level up 

 

Suggested workaround should be to allow type the whole path by hand.

 

Thanks for Your effort

 

 

Pavel Vanecek

**Comment by Lineflyer** [comment]
Does anyone have an idea which dirchooser is invoked here?
AFAIK we use what the device offers (mine looks completely different...same as in Locus).

**Comment by rsudev** [comment]
No idea. I am also not sure that the one for the map file would be different, as the screenshot (IMO) shows the map file selection before opening the actual file picker intent.
@pavelvanecekcz As a workaround you might try to install the 'OI File Manager' app. It should then be presented as possible choice when you click the button for file choosing in the theme selection.

**Comment by pavelvanecekcz** [comment]
Is it possible to edit some configurtion file – I mean changing path directly by typing it into configuration (INI file)?

The aim is that the themes path is the same as the map path with appended „/_themes“   string.

 

P.V.

**Comment by rsudev** [comment]
@pavelvanecekcz Even though there is a technical wormhole, the straight answer is: No, you can't (if you need to ask).

**Comment by pavelvanecekcz** [comment]
Problem solved!
After displaying the folder selection form (1st picture), I need to wait some time, then folders and folder navigation structure was displayed as usually. No idea for such long delay, but finally works the selection of folder quickly.

Thank for the support.

![screenshot_2016-05-04-10-43-25](https://cloud.githubusercontent.com/assets/10035093/15009224/93e4766e-11e5-11e6-9a54-0d4bf51479d3.png)
