### ISSUE TITLE
Live map does not open at current position

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5691]
##### Detailed steps causing the problem:
- move from your previous position for at least 100 meters
- open live map
##### Actual behavior after performing these steps:

Live map shows the previous position
##### Expected behavior after performing these steps:

Live map shows current position
##### Version of c:geo used:

master, with new map enabled

**Comment by Lineflyer** [comment]
@Bananeweizen I struggle to reproduce that...can you add more details like e.g. Did you open the live map also before step 1, is c:geo running and GPS active between step 1 and 2, is the "follow" option on the map shown as active once you open it, Does only the map remain on the old position or your position marker as well?

**Comment by rsudev** [comment]
I'd like to chime in here as well. Is suspect there might still be cases, where map state is not handled correctly or according to expectations, but I fear I also need a more concrete sequence of actions to fix this specifically.
I cross-checked the base case (after having found how to send locations to the emulator):
* open live map at location 1, check that follow my location is enabled
* close live map
* move to location two
* open live map - here it is centered around the new location

**Comment by Bananeweizen** [comment]
I'm not sure if this is especially related to the new map. My new test case is as follows:
* Open live map, scroll somewhere (such that auto-center is off).
* Close and kill cgeo.
* Restart the app and open live map.

I expect to be centered now, since my understanding was that we store the "auto-center" state with the user session and reset to "you are centered" when starting the app from scratch. For me that does not happen.

**Comment by Lineflyer** [comment]
Confirmed with the scenario described by @Bananeweizen with todays NB using mapsforge beta.
Using Google Maps the problem is not there: After new start the live map started centered on location again.
