### ISSUE TITLE
Better analysis of login problems

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5693]
Currently it is diifcult to impossible to analyze login problems on support mails or it needs quite an effort.

I could imagine different improvements:
- Currently I do always ask the users to use "Check Login" in Settings -> Services -> geocaching.com and tell me the response shown. Could this be done "automatically" and the result be included in the system information (currently it only shows Login OK or Login failed)?
- I wonder if it may be possible to get more output on login failures with "other reason" (i.e. all cases where we don't clearly detect wrong username or password). Normally this is the end of remote analyzing as long as I don't have hands-on the device. 
  In the few cases where I can get a log (because the user is able to do so and Android <4.1 is used), this does not give a clue either:

```
D/cgeo    (  808): [network-6] 200 (1022 ms) GET https://www.geocaching.com/login/default.aspx
D/cgeo    (  808): [network-6] POST https://www.geocaching.com/login/default.aspx
D/cgeo    (  808): [network-6] 200 (953 ms) POST https://www.geocaching.com/login/default.aspx
I/cgeo    (  808): [network-6] Failed to log in Geocaching.com as **** for some unknown reason
```

Any ideas?

**Comment by UniQP** [comment]
Considering the second point: What about adding `loginData` to the log?

**Comment by Lineflyer** [comment]
Implicitly solved as we do now have log files available from within the app.
