### ISSUE TITLE
Delayed restart Application

### ISSUE THREAD

**Issue by frankFic** [cgeo/cgeo#5695]
Hello developers of c:geo,

I have found that `AlarmManager.set()` is used in  `CgeoApplication` to set a `PendingIntent` to restart the MainActivity in 0.5 seconds.
But this API may not send the intent in time on devices newer than KitKat. As I found in [API guide](http://developer.android.com/intl/zh-cn/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent)), alarm set by this API may be deferred sometime so that the activity will not be restarted in that small time interval as expected.

Using API `setExact` will make sure to send the alarm at that exact time.
Hope this information is useful for you. :)

Thanks a lot.

**Comment by samueltardieu** [comment]
This is not a problem for us as this is used to restart the application in the case the user changes some settings such as the language to use. In this case, we know that the device is not idle as the user is using it, and the alarm should be triggered just fine.

Thanks for the report anyway.

**Comment by Bananeweizen** [comment]
@frankFic Do you have any tooling that helps you in identifying these API constraints? Just wondering, since you reported 2 times issues related to API versions.

**Comment by frankFic** [comment]
@Bananeweizen I would say, a very good guess. :)
The fact is that I am attempting to develop a tool to detect issues related to API level constraints and other potential issues related to special devices. And that's exactly the reason I reported two issues of this kind.
The number of APIs included in the tool is limited now, but I will continue to improve it.
