### ISSUE TITLE
Android Studio 2.1, Jack compiler

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5696]
This is to collect feedback how to deal with the recent changes in the Android tool chain. Please refer to the 2.1 release notes described in http://developer.android.com/tools/revisions/studio.html

If I got it right, this means for us:
* We cannot use Java 8 due to the target level restriction.
* We can upgrade to Studio 2.1, this is still the same underlying IDEA version.
* We can upgrade the android gradle plugin to 2.1, since that will also work for other IDEs.
* We should try to enable the new experimental compiler (via PR), since I expect it to be more performant than the tools used before. Or do you consider this to be to unstable? Or do you currently use the Instant Run feature (which doesn't work with the new compiler yet)?
* We should switch to in-process-dexing for better performance (http://developer.android.com/tools/revisions/gradle-plugin.html , section for release notes 2.1). However, that seems to require more memory than our current docker slaves are configured for. Shall we just try it nevertheless? Shall we go with 8 GB minimum RAM per slave? @samueltardieu and @kumy , would that still fit for you?

Anything I missed or where I might be completely wrong?

**Comment by kumy** [comment]
For `kumy-2` host has only 4G of ram. For `kumy-1` I have 16G, but it's also my desktop.

**Comment by UniQP** [comment]
> Although Android Studio 2.1 is now stable, the Jack compiler is still experimental [...]
Sounds unstable to me.

@Bananeweizen Why do you think the Jack compiler is faster? Are there any benchmark results?

**Comment by rsudev** [comment]
I updated AS some days before (still 2.0) and used the 'Instant run' feature by accident. It leads to the same dex limit as debugging in Eclipse :P 
So instead of trying to find a way around I resorted to debugging with IntelliJ. If you know how to switch it off, I'll be glad to know.
Do you know if the project format of AS is now again aligned with IntelliJ (or is there a way to align those?)?
Regarding Jack, I wouldn't experiment too much unless there are tangible benefits.
Dexing in process could also be used just locally, as IMO the performance of the integration builds is sufficient.

**Comment by samueltardieu** [comment]
> We should switch to in-process-dexing for better performance (http://developer.android.com/tools/revisions/gradle-plugin.html , section for release notes 2.1). However, that seems to require more memory than our current docker slaves are configured for. Shall we just try it nevertheless? Shall we go with 8 GB minimum RAM per slave? @samueltardieu and @kumy , would that still fit for you?

Where does that 8GB figure come? Did you test it and this was necessary for cgeo?

I'm not willing to commit more ressource per executor than the 4GB I already gave them. However, if needed I can add swap space, but I would say that 4GB is probably enough.

**Comment by Bananeweizen** [comment]
@UniQP 
Jack should be faster because it reduces the number of processes involved, which is basically the main reason to create it, if I got it right. https://source.android.com/source/jack.html

@samueltardieu 
Why not? Is the host limited in that regard or do you feel that such a build should generally always be possible with small amount of RAM? Generally to me this seems like another good reason to also have the slaves run on servers which we pay for.
I have no direct reason for the 8 GB number. From reading https://developer.android.com/intl/zh-cn/tools/revisions/gradle-plugin.html I see that we require at least 2 GB max heap, but they also throw around 3 GB of max heap (and that's the part I don't understand, the relation between java and gradle heap). Since we already ran into out of memory when checkstyle was running in the same gradle build as the test, I just assumed that yet another increase in memory usage due to this new tooling might again cross the limit of the current slave configuration. But that's just a hypothesis, maybe the current slaves are able to handle it.

**Comment by Bananeweizen** [comment]
Summary: gradle and google service plugins upgraded, in-process-dexing enabled, Jack still disabled. Closing. We should re-investigate when jack becomes non experimental.
