### ISSUE TITLE
Message notification on login

### ISSUE THREAD

**Issue by jan-svab** [cgeo/cgeo#5699]
It may be useful and inexpensive (in terms of cosumed resources and also implementation effort) to add a small notification to main screen that the user has some unread messages in messaging center.
Real world usage example - me personally, I use c:geo for nearly all geocaching tasks, so I log to geocaching.com website just once a month or even once a few months. Such a feature would vastly improve my message response time.

The feature request #4917 for integrating message center into c:geo was closed with following reasoning:
- integrating message center is expensive and not a main 
- it is possible to develop another application that would notify user that he has a new message

Eventhough both is undoubtly true, I would like to ask for reconsidering the second point - it seems to be not-so-very-clever to develop another standalone application that would have to do exactly the same as c:geo does on each start (log in to geocaching.com), let the user keep login credentials to geocaching.com in two distinct applications etc. On the other hand, for c:geo it would mean just adding another regexp to parse the login screen at startup and show a simple orange dot somewhere on main screen (or do I get it wrong and it would be more effort than I expect?)
#4917
#5352
#5346

**Comment by Lineflyer** [comment]
Interesting idea, but just showing a marker if unread messages are present does not help so much.
How shall the user read the message and how shall he even understand the meaning of that marker?

**Comment by jan-svab** [comment]
Maybe other users would welcome more elaborate feature, but for me, it is sufficient as described. It would just tell me "now it's time to go to website". I don't have problems using geocaching.com to read/write my messages, I just don't need it for anything else (I use c:geo for all other tasks) so I simply usualy forgot to do it. Such a reminder would be completely sufficient for me.

Making the marker understandable is a matter of graphical design, but I would suggest to use the same orange dot as appears on top of the letter icon on geocaching.com, when you have unread messages. However, I'm not sure where to locate it on the screen so that it would be completely clear that it means unread messages.

**Comment by Natureshadow** [comment]
Telling people to just send a frigging e-mail just as they always did and ignore everyone who is too dumb for that is an even simpler solution.

I never read messages on GC.com and I do not want an irritating notification about it anywhere.

**Comment by SammysHP** [comment]
AFAIK c:geo does not use system notifications yet. I suggest to simply show a notification for new messages, checked on every parsing of a gc.com page.

> **New message on geocaching.com**
> Open in browser

**Comment by moving-bits** [comment]
I've analyzed the necessary calls to retrieve a message counter. (Data will be provided in XML format.)

Can someone point me to a code snippet how to poll an external https source every 5 minutes in `MainActivity`, extracting a certain value from the retrieved XML?

Probably something like this, but I cannot get this to run:

in `onCreate()`:
``` 
resumeDisposables.add(
	  Observable.interval(0, 2, TimeUnit.SECONDS)
	        .map(value -> getMessageCenterState())
	        .takeUntil(Observable.timer(1, TimeUnit.SECONDS))
	        .observeOn(AndroidRxUtils.networkScheduler)
	        .subscribe(result -> Log.e("received: " + result))
);
```
with `getMessageCenterState()` being the function doing the actual https call, and returning a byte value.

**Comment by ztNFny** [comment]
Is this still a required feature? The official GC app seems to do a quite good job at message center, I don't see that cgeo could add any value there.

**Comment by Lomanic** [comment]
I would appreciate this feature yes. With this implemented, I think I wouldn't have any reason to keep the proprietary app with its broken maps and message notifications on a device without Google Play services.

**Comment by ztNFny** [comment]
But you do get email notifications about message center messages already? 
This issue is not about implementing messager functionality but just about notifying about new messages.

**Comment by moving-bits** [comment]
I have the polling code ready now, and it's working in general. Only thing missing is that the request seems to require setting a specific cookie with a value I can extract from some earlier call as HTML field. How can I inject this text as a cookie into the https call?

**Comment by moving-bits** [comment]
Implemented a non-intrusive (and optional) solution with #14407
