### ISSUE TITLE
New map: Filter info missing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5700]
##### Detailed steps causing the problem:
- Have new map active as default
- Apply global type filter (e.g. Traditional only)
- Open live map

##### Actual behavior after performing these steps:
No filter info shown below the action bar

##### Expected behavior after performing these steps:
The notfication about an active filter should be shown directly below the action bar (compare to old map)

##### Version of c:geo used:
2016.04.27-NB

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

**Comment by rsudev** [comment]
It's not a bug, is a missing feature (like some others e.g. the circles) :)
