### ISSUE TITLE
Manage lists button not working 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5701]
##### Detailed steps causing the problem:
- Disable the setting -> Offline-Data - Ask for list
- Open saved list
- Open cache details of a cache
- Click on "Manage"

##### Actual behavior after performing these steps:
If the cache is not on the standard list it will be moved to standard list. No list selection dialog is shown.

##### Expected behavior after performing these steps:
The "Ask for list" setting should not have any influence on the "Manage" function but should always open the list selection dialog

##### Version of c:geo used:
2016.04.27-NB

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
Confirmed, I'll take it.
