### ISSUE TITLE
cgeo failed to download cache details. Unknown error

### ISSUE THREAD

**Issue by stirlingstew** [cgeo/cgeo#5702]
I recently bought a 'new' Nexus 7 (2013) tablet and downloaded the c:geo app to use when caching.
cgeo version 2016.04.12   Android version 6.0.1

I logged into my geocaching.com account and used the Check Login option to confirm. When I go to the Live Map page and try to look at cache details, I receive this error
: cgeo failed to download cache details. Unknown error

##### Expected behavior after performing these steps:

I should be able to see and also to store caches on my device

##### Is the problem reproducible for you?
Yes

##### System information:

Device:Nexus 7(razor,google)
Android version 6.0.1
Cgeo version 2016.04.12
Google Play services: enabled
Low power mode: inactive
Compass capabilities:yes
Rotation vector sensor:present
Orientation sensor:present
Magnetometer & Accelerometer sensor:present
Direction sensor used: rotation vector
Hide own/found:false
Map strategy:Auto
HW acceleration:enabled (default state)
System language: en_GB
Geocaching sites enabled:
   geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: none

##### Other comments and remarks:

I have another Nexus 7 (2012) Android version 5.1.1 that runs cgeo fine but gets a poor battery life so the intention had been to use two tablets when out caching for a full day but cannot get cgeo working on the newer tablet  . Any help or advice would be much appreciated.

Regards

Stewart Wilkie

**Comment by akkatracker** [comment]
The other nexus 7 is on the same build right?

**Comment by stirlingstew** [comment]
My apologies, that's the one piece of information that I missed from the system information above

Nexus (2013) Android build is MOB30D

System Information for the other Nexus 7 is :

Device:Nexus 7(nakasi,google)
Android version 5.1.1
Android build: LMY47V
Cgeo version 2016.04.12
Google Play services: enabled
Low power mode: inactive
Compass capabilities:yes
Rotation vector sensor:present
Orientation sensor:present
Magnetometer & Accelerometer sensor:present
Direction sensor used: rotation vector
Hide own/found:false
Map strategy: fastest
HW acceleration:enabled (default state)
System language: en_GB
Geocaching sites enabled:
geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: none

So the answer to your question is NO, it's a different build.

**Comment by stirlingstew** [comment]
I don't know what changed but cgeo is now working om my new Nexus 7 :)

**Comment by akkatracker** [comment]
Great to hear but strange. 

Thanks for the report
