### ISSUE TITLE
Login issues?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5706]
I just saw that the Pocket Query Creator app was updated yesterday with the comment "Login fix". Did we have any recent increase in reported login problems? I'll try to get some info about what was the problem there.

**Comment by rsudev** [comment]
I used c:geo yesterday and today in conjunction with gc.com without any issues.

**Comment by rsudev** [comment]
I let my daughter (BM) also cross-check (she has 2016-03-29 right now) - login ok as well.

**Comment by UniQP** [comment]
In april, there were three complains in Google Play: [1](https://play.google.com/store/apps/details?id=cgeo.geocaching&reviewId=Z3A6QU9xcFRPRkNUaEV1Z05HQWlFZ3lOWkVxYXlkZzVZUjlRTU1GeGlnVzE5OEg3RHl5V2hDOWsyVTBvNlBnVHdTbEhtU09oQmR6bWtjcTNPeklGUy11T2Ew), [2](https://play.google.com/store/apps/details?id=cgeo.geocaching&reviewId=Z3A6QU9xcFRPR29VMFhFUnlPZXZjbGMwdlN6dV9Fc0hRZ0d6bGxsRUFQMHUyaVI5YkJlRUpKVE1MU0VZQVJoQXMyNm1sRWxxSGxRTVZvc1IwYUpmeGhiaWNB), [3](https://play.google.com/store/apps/details?id=cgeo.geocaching&reviewId=Z3A6QU9xcFRPSHpVeEUzOWdhQ2QwRjdFWWpQUTZSXzRMbl9HU01jbDBaNWloT1hrTUZveHBVcEJEQzBMOXJWeHFDZ2Q3ZnIxWVBqSjJ1b3pRVXlkWmVabzZ3)

I think #5693 also originates from login problem reports.

**Comment by Lineflyer** [comment]
There are always a lot of login problems reported on our channels. In a major percentage they are caused by user or device. I recently opened #5693 as I noticed something strange at some users...but no general problem in sight right now.
However maybe Bananeweizen can investigate something useful from pqc.

**Comment by Bananeweizen** [comment]
> Hello. I am away on holiday at the moment but from what I can remember Geocaching changed the way I need to http post the login form. They seem to have disabled non https login at some point, and added some Google advert stuff (but as far as I can tell they both don't affect login)
>
> I think this is the basis of what I do now 
> Try to get pocket query page
> If not logged in post login info to login page
> Check if page says logged in ok.( This page should be a 304 redirect page)
> Try to get pocket query page again
>
> I can't really remember but I think what has changed is I now need to manually get the page for a second time after login

To me that sounds as if there is no immediate action necessary on our side. I think @samueltardieu at one point changed most/all URLs to https, and we read the login result page for state variables anyway.
