### ISSUE TITLE
Outgoing support mail problem

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5714]
@mucek4 Over the last days I do see >100 delay and bounce notifications.
As I did not send out any mails last days due to vacation I assume this is already older. Can you check whats going on?

**Comment by SammysHP** [comment]
> 08:27:39 <mucek4> A large number (estimated 20k) mail was send out from "Agatha"<support@cgeo.org> from our server
08:30:37 <mucek4> due to configuration error on server :(
09:49:58 <OneEyed> mucek4: siht, I hope they just used our email address as a sender, I didn't think they went through the actual server…
09:50:28 <mucek4> Well. They did

http://krul.finf.uni-hannover.de/~sammyshp/cgeo-logs/2016-04-29.txt

**Comment by mucek4** [comment]
The problem was solved.
