### ISSUE TITLE
Login failure with emulator

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#5717]
##### Detailed steps causing the problem:
- Start the emulator
- Provide username/password in main/cgeo.geocaching_preferences.xml
- Run ./gradlew testDebug
##### Actual behavior after performing these steps:

:main:connectedBasicDebugAndroidTest

cgeo.geocaching.CgeoApplicationTest > testPreconditions[Nexus_5X_API_23(AVD) - 6.0] FAILED 
    org.junit.ComparisonFailure: [User must be premium member for some of the tests to succeed] expected:<[tru]e> but was:<[fals]e>
    at cgeo.geocaching.CgeoApplicationTest.testPreconditions(CgeoApplicationTest.java:59)
:main:connectedBasicDebugAndroidTest FAILED
##### Expected behavior after performing these steps:

No failure
##### Version of c:geo used:

0df7710cc43a663d704b4a30480467dab9b91e6e
##### Is the problem reproducible for you?

No
##### System information:

Executing ./gradlew installBasicDebug after the second (successful) run:
![cgeo](https://cloud.githubusercontent.com/assets/1321557/15021891/7afcd68e-1229-11e6-9295-c637d773a0c4.png) 
##### Other comments and remarks:

Running ./gradlew testDebug again (without chaning anything) works fine.
Since this is at least the second time I noticed this behavior, I don't think it happens by coincidence.

**Comment by Lineflyer** [comment]
@UniQP How shall we proceed with this issue? Still a problem for you?

**Comment by UniQP** [comment]
The problem did not occurred again.
