### ISSUE TITLE
Rendering of log images

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5719]
Fork-off from the last 3 comments here: https://github.com/cgeo/cgeo/issues/5562#issuecomment-211001205

I suggest to render the log images below the log text as following:
* If it is one image, then stay as of now: (icon) (image title)
* For more than one image (e.g. 3): (icon) 3 images

That takes away the necessity to have humans really read (and split) the concatenated titles. Since we open all images of the given log anyway, I also don't feel is any value in reading all the titles directly below the log text (instead of only in the image list).

Opinions?

**Comment by SammysHP** [comment]
> I also don't feel is any value in reading all the titles directly below the log text (instead of only in the image list)

If you have a bad connection, titles might be helpful to find a helpful image.

**Comment by Lineflyer** [comment]
Sometimes I use these titles to locate a needed picture (e.g. looking for titles which contain GZ, spoiler, the box) thus I consider it helpful to see them right away in the logbook. 
Maybe a compromise would be to have one line of concetenated titles as a maximum and if more pictures are attached to fall back to your suggested method.

**Comment by pstorch** [comment]
What about a simple Bulletpoint List?

![2016-05-05 20 01 05](https://cloud.githubusercontent.com/assets/5598124/15055451/fb5dd2d6-130c-11e6-8f20-dbbae6954aee.png)

**Comment by rsudev** [comment]
This looks very good (IMHO)

**Comment by UniQP** [comment]
@pstorch How hard is it to move the icon to the top of the list (instead of having it vertically centered)?
If it's easy, can you post an screenshot for comparison?

**Comment by pstorch** [comment]
@UniQP I'll try, wait a moment

**Comment by SammysHP** [comment]
One reason to concatenate all titles was because tapping the titles opens all images in one view. Previously – when we had one line per image and each with the camera icon – only one image was opened.

**Comment by pstorch** [comment]
@UniQP took longer than I thought and still have some layout problems:
![2016-05-06 20 24 26](https://cloud.githubusercontent.com/assets/5598124/15085271/90df7298-13d9-11e6-9cd6-3232619f0a30.png)

@SammysHP didn't know that. At the moment the list would still have one click target: the Image Activity with all Images of the log.

**Comment by Bananeweizen** [comment]
And I would like to have it remain opening all images. I believe that are much more users who don't care about data transfer and want to see images as easy as possible than users who want to click through each image separately to save data. I cannot remember that anyone ever requested opening single images, so obviously there is no need.

**Comment by pstorch** [comment]
I'm fully with you. I didn't change that behaviour in my proposal, just the presentation of the list.

**Comment by UniQP** [comment]
I would prefer the variant with the top-aligned icon, because you see the icon first when reading line by line. Thank you for providing the variant.

Regarding the image opening: If we want to provide both functionalities (opening one image and opening all images) for some reason (I don't know what the typical use case is), we can open all images when clicking on the icon and specific ones by the corresponding description.

**Comment by SammysHP** [comment]
Opening all images of a log at once is absolutely ok IMHO.

**Comment by samueltardieu** [comment]
Assigning to @pstorch as it looks like he might have some code ready for this.

**Comment by pstorch** [comment]
The rendering of log images was already merged via #5721.
But it was the version with the middle aligned icon. I couldn't get the top aligned icon to work.

**Comment by Lineflyer** [comment]
Closing. Implemented.
