### ISSUE TITLE
New request : pocket queries in GGZ

### ISSUE THREAD

**Issue by incogneeto** [cgeo/cgeo#5726]
I was told to ask in here and I have to admit I am out of my league in here, but I have a request/idea. I have the C:GEO app on a couple of devices. Is there any way to build pocket queries in GGZ format and either use them in the app or export them so they can be used in a Garmin gps? A lot of places I go geocaching does not have cell phone coverage and even though I could use the phone offline I find the gps to work better. I am also asking for bigger pocket queries than GS allows like whole states if needed. A lot of people are traveling and the size of pocket queries are very limiting and they don't want to be adding new ones all the time.
- Step 1
- Step 2
- ...

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

**Comment by SammysHP** [comment]
That is something you should ask Groundspeak. c:geo only displays data that it gets (either via import from pocket query or directly downloaded from gc.com). If you download a whole state with c:geo (or maybe even "only" a few thousand caches at once) you might get banned by Groundspeak.

You can export GPX files with c:geo (this is limited by the list of stored caches, of course). GGZ is simply a zipped GPX file. For your Garmin there should be no difference between a GPX and a GGZ file.

**Comment by Lineflyer** [comment]
I wouldn't think you will get banned or something else by Groundspeak.
But the basic essence is correct: GGZ is simply a zipped GPX ,not much of a difference when exporting/importing it. For normal use cases like exporting and transfering some(!) caches from c:geo GPX should do the job without much difference to GGZ (zipping also needs time).
