### ISSUE TITLE
Sorting saved offline records are not listed correctly

### ISSUE THREAD

**Issue by efrts** [cgeo/cgeo#5728]
##### Detailed steps causing the problem:
- I have found and saved offline several caches
- Applied a filter by Personal Notes > With offline records
- Tried to sort them by registry date
##### Actual behavior after performing these steps:

Saved offline records do not get listed by date of found and get mixed
##### Version of c:geo used:

2016.04.12
##### Is the problem reproducible for you?

Yes
##### System information:

Device: C6603 (C6603, Sony)
Android version: 5.1.1
Android build: 10.7.A.0.228
Cgeo version: 2016.04.12
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: pt_PT
Geocaching sites enabled:
- geocaching.com: not logged in ()
  Installed cgeo plugins: calendar
  --- End of system information ---

**Comment by pstorch** [comment]
I could reproduce it with current master `fb50e95` the sorting by `Date logged` seams to be wrong.

**Comment by chicogh** [comment]
The same problem also happens to me.
I found 72 Geocaches in c:geo and save them offline when I trying to sort by Log date they appear disordered.

**System information**
--- System information ---
Device: SM-N910F (trltexx, samsung)
Android version: 6.0.1
Android build: MMB29M.N910FXXS1DPG1
Cgeo version: 2016.08.16
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: pt_PT
Log date format: 19/08/16
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---

**Comment by Lineflyer** [comment]
Just retested this with the new filter framework. I could see no wrong sorting with different filters I tried (including the case of filter on existing personal note and sorting by hide date).
