### ISSUE TITLE
How c:geo determine if a waypoint belongs to an cache?

### ISSUE THREAD

**Issue by Megachip** [cgeo/cgeo#5732]
especially it is not a GC.

Thx a lot,
meg

**Comment by SammysHP** [comment]
This is not a bug report but a support question.

c:geo does the mapping like any other app: The GC code without the two character platform prefix is the common id to link caches and waypoints.

GCAB123 - 01AB123, PKAB123
OC12345 - 0112345...

This is no good solution, but that's what Groundspeak invented 16 years ago and sadly it is still the only widely compatible way. AFAIK there is also a GSAK schema extension for GPX that is supported by c:geo.

**Comment by Megachip** [comment]
@SammysHP thx. Not a but, right. But did not know where to ask this. 

But seems not working. But found a workaround using the gsak schema (parent) - which works fine.

**Comment by SammysHP** [comment]
Can you give us a sample GPX which does not work?

**Comment by Megachip** [comment]
Good question... Tried an OC today and it works. But can remember that it didn't a year ago. Will see what happens when changing the prefix...

**Comment by Bananeweizen** [comment]
Look for all references to parentCacheCode in https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/files/GPXParser.java, if you need the details. We check at least for the naming conventions of Geocaching.com, Extremecaching.com, Terracaching.com and the GSAK parent tag.

**Comment by Megachip** [comment]
@Bananeweizen GSAK working fine (Independent of cache source).
@SammysHP here is an modified GPX which will not work: https://drive.google.com/open?id=0B6m0IpjzbummQmRKdHNZYjdKa1E 

So for caches outside of GC, TC and EC using the gsak schema will result in a proper waypoint to cache mapping.
