### ISSUE TITLE
FC in file manager

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#5733]
##### Detailed steps causing the problem:
- Go to c:geo Settings
- next to Map
- and select Map Themes Directory.

##### Actual behavior after performing these steps:
App crash

##### Expected behavior after performing these steps:
Open file manager

##### Version of c:geo used:
2016.05.11-NB-bf27824

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: LG-D802 (cm_d802, LGE)
Android version: 6.0.1
Android build: cm_d802-userdebug 6.0.1 MOB30J 52a1141cf0 test-keys
Cgeo version: 2016.05.11-NB-bf27824
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: pl_PL
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Installed cgeo plugins:  none
--- End of system information ---

##### Other comments and remarks:
This problem also occurs in GPX Export/Import Directory but all is fine in Direcotry with offline maps

**Comment by rsudev** [comment]
The map selection tries to select a file, not a directory - that's the difference here.
When selecting the directory we try to call an external app before resorting to an internal implementation. Could you try again after (for this test) installing the OI filemanager?

**Comment by Eselter** [comment]
With OI File Manager working. With stock CM13 file manager and Solid Explorer not working :/

**Comment by Eselter** [comment]
For me problem is fixed in latest nightly.
