### ISSUE TITLE
Feature: Exclude/show only own, Exclude found, Exclude disabled, Exclude archived

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#5738]
In settings, Cache details, currently there are two options: 
- Exclude Own **and** Found
- Exclude Disabled

My feature request is for separate exclusions, as follows:
- [ ] Exclude Found
- [x] Exclude disabled
- [x] Exclude Archived
- [ ] Exclude Own
- [ ] Show only Own

The last two to be mutually exclusive, if one is set.
If set "show only own", the above exclusions for disabled and archived to apply.
##### Other comments and remarks:

This is aimed to help cache owners and teams working with cache owners to better manage caches without the specific need to prepare special purpose GPX files for each situation described above.

Thank you.

**Comment by andrixnet** [comment]
This request also applies to map settings on live map. (where currently you can only hide own&found caches)

**Comment by Lineflyer** [comment]
I am not sure whcih of those requests will match to the possibilities we have on the gc.com website to apply settings... AFAIR this was also the reason to combine "Found and Owned" rather than have them separate, but that was years ago.

**Comment by andrixnet** [comment]
I know on the live map partial data can be loaded and caches displayed because not enough data is known about them to filter them out.
However it shouldn't be a problem for stored caches, where _ALL_ information is known.

**Comment by moving-bits** [comment]
+1 for splitting the menu item "hide found & own caches" on live map into two separate settings - this would make my life as a cache owner much easier when on cache maintenance tour.

**Comment by moving-bits** [comment]
_However it shouldn't be a problem for stored caches, where ALL information is known._

which would be totally fine for me, if doing it would be impossible for all caches (including yet unstored ones).

**Comment by andrixnet** [comment]
With the new "Hide" menu, two points from this feature request have finally got into production.
- "Hide disabled"
- "Hide archived"

Please implement next at least: 
- Hide found
- Hide own

**Comment by jakedot** [comment]
With the new "Map Quick Settings" menu, I'm wondering if we could separate the Hide Found/Own options? Assuming that these settings will still be available in the case the advanced PR search gets merged.
