### ISSUE TITLE
List not refreshed properly after import GPX

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#5745]
##### Detailed steps causing the problem:
- creat an empty list
- import GPX file (with any number of caches, I tested with 100+)
- after import successful dialog, press ok
- press BACK from GPX files panel to return to list panel

##### Actual behavior after performing these steps:
- list is shown empty
- click on lists dropdown shows an update for the "all caches" counter
- switching lists to all caches shows proper contents
- switching lists and then back to list into which I imported shows proper content

##### Expected behavior after performing these steps:
list to be properly populated after GPX import without the need of further user interraction.

##### Version of c:geo used:
2016.05.09

##### Is the problem reproducible for you?
Yes, always

##### System information:
```
Android 4.4.2 (Huawei Ascend P7)
Android 4.2.1 (Allview P5 Quad; MTK cpu with JIT issues)
```
(tested on 2 different devices, same behaviour)

**Comment by pstorch** [comment]
Reproducible in current master `c8509d5`

**Comment by andrixnet** [comment]
I think it might be related: 
- Have some caches in History. 
- Switch to History list
- Clear history

Nothing apparently happens. 
One has to change lists and then back to history to see that history has been cleared.
