### ISSUE TITLE
send2cgeo Firefox stalls with endless "Please Wait" - https not configured properly

### ISSUE THREAD

**Issue by WayneLinton** [cgeo/cgeo#5747]
##### Detailed steps causing the problem:
appears to be identical to issue #4029 closed in 2014
Firefox 46.0.1
Greasemonkey 3.8 2-MAY-2016
Send2cgeo 0.34 16-MAY-2016
browser and device registered

- browse to geocaching.com, "Play", "View Geocache Map"
- right-mouse click on cache to download, click on "Send to c:geo"
- "Please Wait" is displayed at top and never goes away, never processes the request

##### Actual behavior after performing these steps:
- nothing happens once the "Please Wait" is displayed

##### Expected behavior after performing these steps:
- cache should be downloaded with "Success!" displayed

##### Version of c:geo used:
2016.05.09

##### Is the problem reproducible for you?
Yes, but it works fine with Chrome and Tampermonkey

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
The issue is not with c:geo, but with the send2cgeo/Firefox script


##### Other comments and remarks:
Browsing to send2.cgeo.org with https produces a Firefox error:  "The owner ... has configured their website improperly"

**Comment by WayneLinton** [comment]
It is possible to add a security exception to get past this problem

**Comment by mucek4** [comment]
I have just checked and it works. Same settings as you have. Can you please post a screenshot. You can't really open https://send2.cgeo.org/ but please go to https://send2.cgeo.org/api/

**Comment by WayneLinton** [comment]
This is what it looks like before I add a security exception:
![send2cgeo](https://cloud.githubusercontent.com/assets/15835469/15408076/9a6e9252-1dcb-11e6-943b-95f0eae9c433.PNG)

When I specifically go to the send2.cgeo.org site, this error show up:
![send2cgeo2](https://cloud.githubusercontent.com/assets/15835469/15408099/b264a9be-1dcb-11e6-84e7-4567f1a0a43e.PNG)

I then proceed to add the exception and it will now work.  Firefox complains that the certificate has a problem:
![send2cgeo3](https://cloud.githubusercontent.com/assets/15835469/15408120/c6780306-1dcb-11e6-8710-a92d60ebf0e2.PNG)

**Comment by WayneLinton** [comment]
When you mouse-over the plugin "Send to c:geo", it does indeed want to go to "https://send2.cgeo.org/add.html?cache=....".  It is therefore expecting a valid certificate.

**Comment by rsudev** [comment]
send2.cgeo.org has a valid certificate that is signed by StartCom. My Firefox (Version 46.0, Linux) recognizes StartCom as trusted built-in token.
Firefox on my mobile seemingly does not recognize StartCom.
Maybe they start to phase out that CA.

**Comment by WayneLinton** [comment]
This is on my Win7 desktop, but I have the same problem with my Win7 laptop.  Perhaps this is a Firefox upgrade issue (46.0.1).  Chrome has a valid StartCom certificate and I have no issues with this browser.

**Comment by WayneLinton** [comment]
Firefox does list a number of CA line-items for StartCom.  It just doesn't seem to recognize it.  I'll start checking the Firefox forums ...

**Comment by mucek4** [comment]
Heartbleed is not likely to be a problem, since certificate is new. Please do next two things to help me investigate the problem:
a) On above screen "Add security exception" click "View certificate" and please paste screen of "General information"
b) Run your Firefox with clean profile (or better idea - try Firefox portable). I suspect some plug-in or misconfigured profile.

**Comment by mucek4** [comment]
Ok. I re-checked all configuration and has to replace intermediate certificate on server. Despite the old one was still valid till October 14, 2022. Please re-check if it's working. If it's working please close the issue.

**Comment by WayneLinton** [comment]
yes, the replaced certificate on the server did the trick. Thanks!


On 20/05/2016 12:05 AM, mucek4 wrote:
>
> Ok. I re-checked all configuration and has to replace intermediate 
> certificate on server. Despite the old one was still valid till 
> October 14, 2022. Please re-check if it's working. If it's working 
> please close the issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cgeo/cgeo/issues/5747#issuecomment-220524763>
>

--
