### ISSUE TITLE
Close on first start after providing credentials 

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#5752]
While testing different versions of c:geo I had to start over several times and stumbled upon this quirky behaviour. 
##### Detailed steps causing the problem:
- Install c:geo from scratch 
- Start
- GC Credentials Settings are shown 
- enter credentials and authorise
- start using the app
##### Actual behavior after performing these steps:
- c:geo shows some Showcase Views,  depending on how fast you click, you see more or less
- suddenly c:geo closes silently
- when you start again c:geo asks again for credentials but has remembered that it already showed the Showcases. 
##### Expected behavior after performing these steps:
- c:geo keeps running and remembers credentials 
##### Version of c:geo used:

2016.05.23-15b04f1 developer build
##### Is the problem reproducible for you?

Yes
##### System information:

```
Attach system information here if available (see c:geo menu -> About c:geo -> System)

--- System information ---
Device: A0001 (bacon, oneplus)
Android version: 5.1.1
Android build: bacon-userdebug 5.1.1 LMY48W e111449243 test-keys
Cgeo version: 2016.05.23-15b04f1 developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar, contacts
--- End of system information ---

```
##### Other comments and remarks:

I think the Showcases and Settings Activity interfere somehow. Could not yet find out what is wrong.

**Comment by Bananeweizen** [comment]
I've been looking for a replacement of the showcaseview library for some time already, but I only found alternatives with a much higher minsdk. Anyone else?

**Comment by pstorch** [comment]
Is a showcaseview still "state of the art"? I don't see it much in new apps.

**Comment by Lineflyer** [comment]
IMHO we can remove quite some of them as we used it to make existing users aware of changed functions.
That does not mean that I prefer to remove the libs completely as we might need it again some time later if we change some UI relevant options which might need a hint.

**Comment by pstorch** [comment]
Maybe https://github.com/PaoloRotolo/AppIntro is an alternative.

**Comment by SammysHP** [comment]
Maybe we should not need it at all. Usually I try to skip these things as fast as possible. An app must be self-explanatory. A short 5 page tutorial on the start is OK, permanent showcases are annoying.

**Comment by akkatracker** [comment]
Using appintro could be the first step on the road to material

**Comment by Lineflyer** [comment]
@pstorch How to proceed with this one?
Its listed as an unverified bug, but the discussion turned more into replacing or removing ShowCase. I suggest to open a new issue or change this issue as a feature request to remove or replace Showcase.

**Comment by pstorch** [comment]
@Lineflyer yes, I'll open a new issue for it
