### ISSUE TITLE
Dropping caches in list created from map doesn't work

### ISSUE THREAD

**Issue by Cotta-R** [cgeo/cgeo#5757]
- view the map in any area with some stored caches
- tip on menu, select "Show as list"

Now the caches, which were on the map, are shown as list.

Now do a long press on any cache to get the context menu. Select "Drop".

Expected behavior: Cache should be dropped from device.
Actual behavior: Cache is not dropped.

System: Nightly from last week, Android 5, HTC One m7

The issue does not exist only recently, the Nightly I just had on my device was a few months old and had the same problem.

**Comment by Lineflyer** [comment]
@pstorch 
You added the Bug label. Are you able to reproduce it?
Otherwise please kindly add "Unverified" at the same time or explicitly state you reproduced it. 
That is helpful to sort the issues for me.

**Comment by pstorch** [comment]
@Lineflyer yes, I could reproduce it.

**Comment by samueltardieu** [comment]
As far as I can tell, "Drop" is only offered if the cache has been stored in a concrete list. What would you expect "Drop" to do in this case?

I would rather prevent "Drop" from showing up in such a dynamic list as it does for cache that are not stored onto the device.

**Comment by Cotta-R** [comment]
The cache is stored on my device. I want to drop it, and I expect it to get dropped just as every where else, where that function is available.
I guess, when a cache is stored on my device and in some cases, when I view it, "drop" is available and in other cases not, just as a matter from where I started to view this cache, this would be irritating.
Anyway, more important for me would be a solution of #5758 instead of a fix for this issue.
