### ISSUE TITLE
Dropping all caches in list created from map at once

### ISSUE THREAD

**Issue by Cotta-R** [cgeo/cgeo#5758]
Feature request: When creating a list of caches from the map, I miss the feature to be able to drop all these caches from the device at once.

**Comment by pstorch** [comment]
I think it's because it is first a temporary list. If you store the caches from the map as a list, it is still shown as a temporary list. 
When you go back to the main screen, then to the offline list you just created, then you have the menu entry to "Remove all" caches.

**Comment by Cotta-R** [comment]
Of course, but I miss the feature to be able to drop caches from a selected area (where I probably don't go the next half year) and not from a list (despite my lists are organized by region).
