### ISSUE TITLE
New map: "Store Offline" not shown

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#5759]
##### Detailed steps causing the problem:
- Enable new map
- Open live map
- wait till all visible caches are loaded
- Open menu

##### Actual behavior after performing these steps:
- No "Store Offline" menu entry is shown

##### Expected behavior after performing these steps:
- Menu "Store Offline" is shown

##### Version of c:geo used:
Reported via `2016.05.29-NB-fb50e95

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

##### Other comments and remarks:
Reported by a user via c:geo Fanpage on Facebook. I can reproduce it.

**Comment by Lineflyer** [comment]
Also reproducible for me!

**Comment by rsudev** [comment]
Its not a bug but a missing feature (I think I listed it in the PR), but regardless its good to have it highlighted. I'll take it.

**Comment by rsudev** [comment]
based on release and merged to master for testing
