### ISSUE TITLE
cancelling storing leads to wrong markers

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5760]
##### Detailed steps causing the problem:
- Start downloading an online search result list
- Cancel at some point in between

##### Actual behavior after performing these steps:
The online search result list is refreshed and _all_ caches have the offline marker. But in fact, not all have been stored. When randomly clicking caches from the list now, some open immediately, and some will be downloaded first (the ones we cancelled).

**Comment by Bananeweizen** [comment]
This seems to be related to the new list management, since the lists are applied outside of the storing routine (and therefore cannot know which caches have actually been stored).

**Comment by pstorch** [comment]
@Bananeweizen yes, you were right. The assignment of the lists did take place outside the store and wasn't in sync when the process was canceled.
