### ISSUE TITLE
In offline list, stay at the last position after moving a cache in another list

### ISSUE THREAD

**Issue by TofLaBeuze** [cgeo/cgeo#5763]
Hi c:geo team,

##### Detailed steps causing the problem:
- Go into an offline list with tens of caches
- Go to the end (for example), select a cache, move the cache in another list by using the "move" button (or long press the cache, select "move in another list" choice in the menu)

##### Actual behavior after performing these steps:
- After moving the cache, we are back to the beginning of the list

##### Expected behavior after performing these steps:
- Stay to the last known position in the list before moving the cache

##### Version of c:geo used:
- 2016.05.09

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

##### Other comments and remarks:

Thanks,
Tof

**Comment by Lineflyer** [comment]
Confirmed also with current `master`
