### ISSUE TITLE
Numeric trackable secret code or five digit code not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5765]
##### Detailed steps causing the problem:
- Select Search 
- Enter tracking code which is numeric only and has five digits 

##### Actual behavior after performing these steps:
Immediate response toast "c:geo konnte diesen Trackable nicht finden"

##### Expected behavior after performing these steps:
Open trackable page

##### Version of c:geo used:
2016.05.09

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
From support mail and verified
Secret code available on request

**Comment by rsudev** [comment]
There is no trackable connector claiming codes with 5 digits. I think at some point we came to the conclusion, that secret codes always have 6 characters (numbers or letters). Seems this is not true...
