### ISSUE TITLE
Crash when opening cache details

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5766]
From support mail with permission to post it here:

Hi, I'm for years on the nightly version, but this season I am not able to open listings anymore. App FC sometimes, but almost every time simple hangs on caching data. And it's no way to kill it. Sometime it reboot my phone. I try wipe data, reinstall app, many options in settings but still same. In every new build 😢
Can someone look at it?
Many thanks! With this bug is app useless.

```
--- System information ---
Device: MI 2S (aries, Xiaomi)
Android version: 5.0.2
Android build: LRX22G
Cgeo version: 2016.05.30-NB-fb50e95
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: cs_CZ
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
```

```
java.lang.NoSuchMethodError: No static method containsAny(Ljava/lang/CharSequence;[Ljava/lang/CharSequence;)Z in class Lorg/apache/commons/lang3/StringUtils; or its super classes (declaration of 'org.apache.commons.lang3.StringUtils' appears in /system/framework/framework.jar:classes2.dex)
at cgeo.geocaching.models.Geocache.getNonStaticImages(Geocache.java:1813)
at cgeo.geocaching.CacheDetailActivity.getOrderedPages(CacheDetailActivity.java:2191)
at cgeo.geocaching.activity.AbstractViewPagerActivity.reinitializeViewPager(AbstractViewPagerActivity.java:279)
at cgeo.geocaching.CacheDetailActivity.notifyDataSetChanged(CacheDetailActivity.java:788)
at cgeo.geocaching.CacheDetailActivity.access$500(CacheDetailActivity.java:166)
at cgeo.geocaching.CacheDetailActivity$LoadCacheHandler.handleRegularMessage(CacheDetailActivity.java:741)
at cgeo.geocaching.utils.CancellableHandler.handleMessage(CancellableHandler.java:51)
at android.os.Handler.dispatchMessage(Handler.java)
at android.os.Looper.loop(Looper.java)
at android.app.ActivityThread.main(ActivityThread.java)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

**Comment by UniQP** [comment]
The method is part of [StringUtils (3.4 and later)](https://commons.apache.org/proper/commons-lang/javadocs/api-3.4/org/apache/commons/lang3/StringUtils.html#containsAny(java.lang.CharSequence,%20java.lang.CharSequence...)). Since we provide StringUtils 3.4, the method should exist.

A possible workaround would be to use a cgeo version prior to 92ca76ff7ccd831b9019bd63f6c336ebcac5bd24.

**Comment by samueltardieu** [comment]
The missing method is `java.lang.CharSequence#containsAny(java.lang.CharSequence[])`. Could it be that Xiaomi has an incomplete standard Java library?

**Comment by Lineflyer** [comment]
With the ongoing staged release of 2016.08.14 we get more of this via Google Play.
Affected devices are also Xiaomi (MI 4c, MI 3w, Redmi 3s, HM Note 2) with Android 4.4, 5.0, 6.0

**Comment by Lineflyer** [comment]
Another user from support mail with this device and same problem:
```
--- System information --- 
Device: Redmi Note 2 (hermes, Xiaomi) 
Android version: 5.0.2 
Android build: LRX22G 
Cgeo version: 2016.08.14
 Google Play services: enabled 
Low power mode: inactive 
Compass capabilities: yes 
Rotation vector sensor: present 
Orientation sensor: present 
Magnetometer & Accelerometer sensor: present 
Direction sensor used: rotation vector 
Hide own/found: false 
Map strategy: auto 
HW acceleration: enabled (default state) 
System language: cs_CZ 
Log date format: 15.08.2016 
Debug mode active: no 
Geocaching sites enabled: 
geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
 Installed cgeo plugins: none 
--- End of system information ---
```

**Comment by UniQP** [comment]
Should I create a workaround?

**Comment by Lineflyer** [comment]
Well...no idea how many devices are affected.
But as the app is useless with this device bug, we should IMHO consider a workaround.

I found something here:
https://github.com/AntennaPod/AntennaPod/issues/884
http://stackoverflow.com/questions/29491443/xiaomi-hm-1sw-java-lang-nosuchmethoderror

**Comment by samueltardieu** [comment]
Thanks @UniQP for the fix. Merged in `release`.

@Lineflyer You may want to cut a new release.

**Comment by Lineflyer** [comment]
I found a user on support mail, who might be willing to test the workaround.
I produced a RC version and will send the APK to him for testing.

**Comment by Lineflyer** [comment]
We mailed to two users, we have now feedback from one of them:
> Ok! Thanks for the help. I have downloaded and installed the version of the link and it works perfectly.

So it seems to look good.
I will wait until this evening to check if there is more feedback and then push the new release in case it is OK. Until then I stay with 20% staging.

**Comment by Lineflyer** [comment]
I just learned that Google Play allows to freeze the staged release, which I now activated.
This means, that no more new installations of 2016.08.14 will happen but already upgraded users stay with the version until we release a new one.

**Comment by Lineflyer** [comment]
New release 2016.08.16 pushed to 50%
