### ISSUE TITLE
Mobile app unable to log visits

### ISSUE THREAD

**Issue by Bobbycharlton1** [cgeo/cgeo#5769]
##### Detailed steps causing the problem:
- logging a visit 
- 
- ...

##### Actual behavior after performing these steps:

If I select logging a visit I get the message download of data in progress please try again in some seconds.  

##### Expected behavior after performing these steps:

Expected it to log my visit

##### Version of c:geo used:

2016.05.09

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
``device Sm-n9005
Android version :5.0
`


##### Other comments and remarks:

**Comment by SammysHP** [comment]
Please post your system information as requested in the issue template.

Posting a log requires a download of additional information. Depending on your network this might take a while.

**Comment by Bobbycharlton1** [comment]
--- System information ---
Device: SM-N9005 (hltexx, samsung)
Android version: 5.0
Android build: LRX21V.N9005XXUGBOK6
Cgeo version: 2016.05.09
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Geocaching sites enabled:
 - geocaching.com: not logged in (Login failed)
Installed cgeo plugins:  none
--- End of system information ---

**Comment by UniQP** [comment]
> geocaching.com: not logged in (Login failed)

I guess that's the reason.

**Comment by Lineflyer** [comment]
@Bobbycharlton1 
Please refer to our FAQ: http://faq.cgeo.org/#login-failed 

Feel free to reopen if nothing helps.
