### ISSUE TITLE
waypoints from dropped and disabled/archived caches leak onto the map

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#5773]
##### Detailed steps causing the problem:
- have a list of caches, including mysteries with waypoints. And some of them disabled or archived
- remove all from that list
- import a different gpx into another list
- have "exlude own, found, disabled" caches ON
- go to map. See areas where waypoint from caches in previous list would be. Including disabled, archived, own.
- deleting orphaned files does not help
- if click on such waypoint, it shows the cache it belongs to, and then cache is also shown on map.

I would expect all waypoints from first list be removed as well, and not be visible
##### Is the problem reproducible for you?

Yes/No
##### System information:

```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

**Comment by andrixnet** [comment]
Further testing shows that it is not necessary to manipulate lists.

Remove a cache with waypoint. Delete orphaned files. Cache dissapears from map, but waypoints remain.

**Comment by andrixnet** [comment]
Note: live not enabled.

**Comment by rsudev** [comment]
Here the issue likely stems from the fact, that dropped caches are still 'cached' in the db for three days, in combination with problems correctly filtering out waypoints belonging to filtered caches.

**Comment by andrixnet** [comment]
I remember I have requested a way for the user to clear that cache here: https://github.com/cgeo/cgeo/issues/4357 ...

**Comment by Lineflyer** [comment]
In parts we have this already covered by other issues (AFAIK there is an issue about hidden owned cache waypoints leaking onto the map). I guess the root cause is the same for all type of hidden caches (like archived and disabled maybe). 
I will try to look it up to attach this issue there if the root cause is the same.

**Comment by andrixnet** [comment]
I had ~300 caches in c:geo (2017.12.17 version) on Samsung Galaxy S6, in list X (only).
- I removed all caches. 
- I cleared history.
- I even went to settings->system, delete orphaned files.
- I imported a different set of caches, into list Y.

In the screenshot below, the waypoint at my location and the 2 waypoints slightly to the east belonged to caches in list X that were removed.

It is very (extremely) frustrating and confusing to still have on the map these waypoints.

![screenshot_20180124-181212](https://user-images.githubusercontent.com/3382777/35343157-934e4df4-0132-11e8-9249-6fb6d2a12a41.png)

**Comment by Lineflyer** [comment]
I could imagine this issue is only caused by an incorrect if() (or similar) in the code when filtering what to be displayed on the map. Sadly no one was interested yet to debug and solve it.

**Comment by Lineflyer** [comment]
No after reading this issue again I realize that my comment above does not make sense.
It was refering to waypoints of owned caches leaking on to the map (another issue).

Here it is about cached deleted caches leaking onto the map.

@andrixnet 
Are you mapping the list or are you using the live map?

In any case we could make a workaround for this, if we enforce, that on deleting "orphaned files" also the caches in our 72-hour buffer (and their files) are deleted.

**Comment by pstorch** [comment]
I looked a little bit into it, but it is not easy. The map is used in different modes and filtering out waypoints from unsaved caches would remove them in modes (e.g. LiveMap or Search by Coordinates) for example where you mainly deal with unsaved caches.
I know it is not a satisfying answer, but just wait three days.

BTW the `settings->system, delete orphaned files` doesn't remove anything from the database. It just cleans up files.

**Comment by pstorch** [comment]
I should have reloaded the page before commenting ;)

> In any case we could make a workaround for this, if we enforce, that on deleting "orphaned files" also the caches in our 72-hour buffer (and their files) are deleted.

That would be a solution, I think. There was a discussion about it in #4357, but this issue is locked.

**Comment by rsudev** [comment]
I don't think 'delete orphaned files' is the right solution, as it semantically does something different. We should once and for all tackle the deletion issue consistently.
One thing is, to keep unsaved caches for some time (three days?) to avoid re-downloads unnecessarily.
The other topic is how to deal with accidental deletion (extended undo). Unfortunately some users might have come to 'rely' on this behaviour, others are seriously hampered by it (unable to delete and cleanly re-download caches, issues like this one, ...).
I meanwhile would assume, that the first group is rather small compared to the second, so we just might want to switch a 'delete right away' behaviour.
Alternatively, we could move them to a 'deleted' list, where they remain for three days. When than a cache is accessed where we have 'deleted' information, we offer to restore it, or to discard the deleted one and get it fresh.
Comments?

**Comment by SammysHP** [comment]
I think it would be enough to not show such deleted caches on the map.

**Comment by SammysHP** [comment]
> That would be a solution, I think. There was a discussion about it in #4357, but this issue is locked.

I've unlocked it again.

**Comment by Lineflyer** [comment]
> I think it would be enough to not show such deleted caches on the map.
Yes for a map of a list but no, when its a live map.


Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: SammysHP <notifications@github.com> Datum: 26.01.18  19:29  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Comment <comment@noreply.github.com> Betreff: Re: [cgeo/cgeo] waypoints from dropped and disabled/archived caches
  leak onto the map (#5773) 
I think it would be enough to not show such deleted caches on the map.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SammysHP in #5773: I think it would be enough to not show such deleted caches on the map."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/5773#issuecomment-360865493"}}}

**Comment by pstorch** [comment]
@SammysHP thanks for unlocking. 
Ok, then let's discuss the 'delete orphaned files' and the 'three days delay' in #4357 

Regarding this issue:

> >  I think it would be enough to not show such deleted caches on the map.
> 
> Yes for a map of a list but no, when its a live map.

And a user can enable/disable live mode at any time. It will get a little bit tricky to handle.

**Comment by andrixnet** [comment]
I will try to answer each remark separately in one post. 

@lineflyer I was using Live map, no hiding own/found/disabled, Live mode disabled. 
Waypoints are from both caches I own and caches I do not own or caches I have not found.

I know about the "keep deleted caches for some time to avoid redownloading" feature and I do not disagree with it. However this kind of leak is a bug.

@pstorch **regardless in which mode the map is called, such leak should not happen.**

Another workaround I found previously was to store the database on user storage, close c:geo, delete the contents of c:geo's directory with the file manager. But this isn't really a solution, just a dirty and desperate workaround.

**Comment by andrixnet** [comment]
All map views where "live=disabled", including list view and search results view, these should not show caches or waypoints from caches that have been deleted. (ie removed from all lists, removed from history).

A map view where "live=enabled" has two ways of showing caches (AFAIK mostly due to Groundspeak limitations):
1. caches with incomplete info, shown with orange circular border and only approximate coordinates
2. caches with complete info (full details have been downloaded) and precise coordinates.

Caches that have been deleted, including (?) removal from history that match the current view with "live=enabled" then can be retrieved from the local database with complete info and displayed as case 2. directly. Full details can be show for these caches and also they can be stored directly in a list without further network traffic. 

All these assume the "keep deleted caches for X days" strategy is in effect.

**Comment by pstorch** [comment]
@andrixnet 
> regardless in which mode the map is called, such leak should not happen.

Yes, I understand your point. At the moment c:geo doesn't distinguish between a cache "not saved yet" and cache which "has been deleted but is kept for 3 days". If we simply add a filter when loading the waypoints to exclude the ones from caches which are not in any list, then we would remove all waypoints from unsaved caches in the live mode. The number 2) in your last comment.

So whoever wants to tackle this issue needs to take the map mode into account. Or we implement the 'delete right away with proper undo' as mentioned in the other issue, then this one is not an issue anymore.

**Comment by Lineflyer** [comment]
AFAIK all such waypoint leakage has been fixed meanwhile.
@andrixnet 
Could you retest your scenario with a recent nightly and reopen if the case is still existing?
