### ISSUE TITLE
Embedded pictures not shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5779]
##### Detailed steps causing the problem:
- open GC61EE3
- the listing contains embedded pictures (at the end)

##### Actual behavior after performing these steps:
For me only a placeholder is shown (small rectangle with OBJ in it)

##### Expected behavior after performing these steps:

Pictures should be shown

##### Version of c:geo used:
2016.06.10-NB1

##### Is the problem reproducible for you?
Not clear but happening on several caches for me

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

**Comment by UniQP** [comment]
Confirmed. I also noticed this behavior with GC54REW on the Emulator.

**Comment by Bananeweizen** [comment]
@samueltardieu Can you take a look at this one? I suspect the ContainerDrawable to be involved in the cause, and you probably know best how to investigate it.

**Comment by Lineflyer** [comment]
Was there a recent change (in our code) causing this or something else (e.g. on the website) which could also affect the market version?

**Comment by UniQP** [comment]
I bisected the problem: 0aaee3887ce2aa37ebe445d02d54069d8a6264ba is the first bad commit.

**Comment by Lineflyer** [comment]
That is strange as this commit is quite straight forward, isn't it?

**Comment by Lineflyer** [comment]
@Bananeweizen 
see above

**Comment by UniQP** [comment]
Looks like the images are broken if the listing has a non-empty short description.

**Comment by UniQP** [comment]
I guess, prepending the "\n" implicitly applies toString() on the Spanned and this breaks the images. I prepare a PR.

**Comment by Lineflyer** [comment]
Confirmed working normal again with 2016.06.15-NB
