### ISSUE TITLE
Wrong date when logging trackables very early?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5784]
I logged a trackable this morning at 6:10 German time. When I refreshed the trackable afterwards, it was shown logged yesterday. I had not changed the date selector, so I'm somewhat sure it was not set to yesterday. Might this be a problem with the time offset of -7 hours that we use somewhere?

I can't verify this behaviour at the moment, since I have no private tracking code available. Will re-test one of the next days with my own trackables.

**Comment by rsudev** [comment]
Confirmed. Just posted a note to one of my trackables (6:30 CEST) and the date shown was from yesterday.

**Comment by rsudev** [comment]
Filing through the code it seems to me that GCParser.java,1345ff are the issue in this case. If we log a trackable 'today' we seemingly don't post the date (no idea why) and gc.com might just deduce it from its own timezone...

**Comment by Lineflyer** [comment]
I've heard of such issues for TB logs as well as GC logs but could never reproduce them, but still what @rsudev describes could be the reason why "early" logs might be on the wrong date.

**Comment by samueltardieu** [comment]
@rsudev This test seems to come from the first imported version of c:geo. I guess we could also remove the "old" way of posting logs now.

**Comment by samueltardieu** [comment]
See #5828.
