### ISSUE TITLE
Jenkins: sam-* executors failing

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5789]
sam-1 is failing tests consitently since two days, sam-2 since one day.
sam-2 reports low disk space.
I temporarily disabled them to give test execution a chance on another executor.

@samueltardieu Coul dyou check them?

**Comment by Bananeweizen** [comment]
Accordng to Jenkins, they ran out of disk: http://ci.cgeo.org/computer/

**Comment by samueltardieu** [comment]
Indeed: `/tmp` in executor was full of gradle temporary files. Cleared, I'll open an issue in our jenkins  slave repository to add something to cleanup `/tmp`.
