### ISSUE TITLE
Feature request: to be able to set a circle around a waypoint

### ISSUE THREAD

**Issue by mikgit** [cgeo/cgeo#5792]
##### Detailed steps causing the problem:
Hi,
This is yet another small feature request. 
There are lots of caches that can be found by doing triangulation. 
It would be nice to be able to set a circle of arbitrary diameter around a waypoint and show it on the map. And then to see where the intersections are.  

What I mean is that when I select add waypoint in cache dialog there could be an additional box for circle diameter. If it is empty there is no circle drawn around the waypoint. Otherwise a circle with the set diameter would be drawn. Maybe also the colour of the circle could be set by the user. 

Thanks,

**Comment by SammysHP** [comment]
This can be done with Locus which has also other nice features for geocaching.

**Comment by mikgit** [comment]
I know it is possible with Locus but the user interface is not friendly as you have to go through and select several options and manually enter the coordinates that are in c:geo. Instead of having the feature directly available in c:geo. Also you can't map additional waypoints directly to Locus. (For bogus it is possible)

**Comment by Lineflyer** [comment]
IMHO this is to specific and to far away from normal geocaching features and functions cgeo is made for.
I would prefer not to include such things but leave this field to dedicated appa specialised for that (e.g. triangulation can be done also with GCC (but not graphic)).

**Comment by Bananeweizen** [comment]
Basically there are at least some thousand repeatedly used algorithms for calculating waypoints in mysteries. For each single of those, the effort implementing it and the benefit for some seldom usage just don't fit to my mind.

BTW: I suggest this one: http://flopp.net/?c=51.158854:10.439100&z=12&t=OSM&f=h&m=A:51.163383:10.447683:2000:marker_A*B:51.182741:10.499533:3000:marker_B&d=
