### ISSUE TITLE
Stuck in batch refresh

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5794]
##### Detailed steps causing the problem:
- Have a list of 100+ caches
- Select to refresh all

##### Actual behavior after performing these steps:
At some unreproducible point of time no more network traffic can be seen and there is no more progress indicated.
Happend to me since some weeks in nightly on mobile network as well as on wifi.

##### Expected behavior after performing these steps:
Normal progress

##### Version of c:geo used:
2016.06.15-NB

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
We had this in the past and it was solved...something with DB access or static maps (cant remember exactly...have to search the issue).
The symptoms now look the same.

**Comment by Lineflyer** [comment]
I think last time it was #4591

**Comment by rsudev** [comment]
I could reproduce it.
For me it happened on log.e in HtmlImage.downloadOrRefreshCopy
As this is likely some network issue, I suggest to demote it to Log.w as well.
You could cross-check by reproducing it on your device and look for the mentioned message in logcat.

**Comment by Lineflyer** [comment]
That sounds logical as I once again have debug log enabled.As I wont be able to look at my log on short term I suggest we change to a warning here and I will keep an eye on the issue (still have the same set of caches here, so most probably a failing image URL will happen again on refresh).
-------- Ursprüngliche Nachricht --------Von: rsudev <notifications@github.com> Datum: 17.06.16  20:38  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Author <author@noreply.github.com> Betreff: Re: [cgeo/cgeo] Stuck in batch refresh (#5794) 
I could reproduce it.

For me it happened on log.e in HtmlImage.downloadOrRefreshCopy

As this is likely some network issue, I suggest to demote it to Log.w as well.

You could cross-check by reproducing it on your device and look for the mentioned message in logcat.

**Comment by rsudev** [comment]
I could in my case verify that it really was a network issue (unknown host exception), so downgrading to warning is anyway the only feasible thing to do.

**Comment by SammysHP** [comment]
Next step is to abort on a warning? Why is it so hard to avoid or correctly handle errors? If a error occurs and is not handled, then something is wrong. We shouldn't simply ignore it.

**Comment by rsudev** [comment]
I would say, because it is just hard.
What would be the right thing to do in this case in your opinion? Some log message or cache description refers to an image on a site which doesn't exist anymore. Should we abort? Inform the user? I think, logging the event and go on is what we should do in this case.

**Comment by Lineflyer** [comment]
I agree to @rsudev for that case....that will happen quite often.
Important would be to show the missing image (e.g. by a placeholder) later to the user while he is looking at that corresponding cache. We do already do so AFAIR.

**Comment by Lineflyer** [comment]
I can confirm that with 2016.06.19-NB my above described case is fixed, so most probably the cause was correctly indentified by @rsudev
