### ISSUE TITLE
Better strings for "New map"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5797]
We should replace the name "New map" by something more understandable like "Mapsforge Beta".
Additionally the setting to enable it by default is way to long to fit on screen (at least the german translation). Here I would suggest "Activate Mapsforge Beta Map".

Any other suggestions?

**Comment by Lineflyer** [comment]
@rsudev Can you implement the needed strings (maybe as suggested above) on`release`?

**Comment by rsudev** [comment]
What about this:
![device-2016-08-03-235728](https://cloud.githubusercontent.com/assets/780005/17383435/43249324-59d6-11e6-9b19-bce846cc8ed6.png)
and this:
![device-2016-08-03-235817](https://cloud.githubusercontent.com/assets/780005/17383443/4edabe0a-59d6-11e6-9aa4-037786cdfe2b.png)

**Comment by Lineflyer** [comment]
Perfect!
