### ISSUE TITLE
Feature Request: Add organizational "pins" for stored lists

### ISSUE THREAD

**Issue by SirMacArthur** [cgeo/cgeo#5798]
##### Feature Request:

One feature I would like to see would be improved organizational tools within C:Geo. My suggestion would be to add the ability to assign a pin to a stored list so that on the main map, one would see that pin color on the associated geocache. 
##### Why is this needed?

My current area map is completely littered with the pencil "note" icon, though the notes are different for each cache. The closest post I could find for this problem was #5037 which outlined the desire for icons for many different situations. Some examples are caches that you need certain tools to complete, night caches, caches that are appropriate to take certain people in your life to, etc...
##### Implementation:

The user would first have to create a stored list independently. From the list view you could tap the upper right drop down menu (the 3 vertical dots), then tap the (new) option "Assign pin." Once that is tapped a box with 5 different colored swatches would appear. One would then tap the desired color. That pin would then appear next to the stored list name wherever the name appears. Once a pin is assigned to a stored list, the entry in the upper right drop down menu would then say "Unassign pin" or something similar instead. 
##### Possible Issues and Solutions:

Some of the concerns raised with #5037 were:
- More icons may make it more difficult for new users.
  - With the implementation suggested, there would be none visible on the map for a new user. It would need to be self initiated by knowing both how to create a stored list, and how to assign a pin. Therefore one could consider this an advanced feature. 
- More icons would cause "over-crowding" of the live map
  - Stored lists without an assigned pin would still appear with the floppy disc icon on the main map. 
  - This wouldn't add additional "noise" to the baseline green ring, it would simply replace information already available with increased specificity for each user.  
- Multiple new icons on the map would be "too much." (I interpenetrated as too many icons as it was suggested to have icons such as tools, locks, etc for different circumstances.) 
  - This approach limits a large variety of possible icons by giving users a limited few that they can use however they see fit. 
  - This simplicity of the pin icon in various colors is also easy on the eye. 
  - This implementation is essentially "opt-in" only. 
##### Other comments and remarks:

Thanks to all the capable people who make this great piece of software. I use it almost everyday. 

Here is a quick mock-up of what one's map may look like with the pin's from multiple stored lists.

![screenshot_2016-06-19-07-38-49](https://cloud.githubusercontent.com/assets/20041945/16190800/fe179f3c-3695-11e6-82de-fb0c45fa2030.jpeg)

**Comment by Lineflyer** [comment]
Thanks for your idea and the combined comparison to what was suggested in #5037.

I do agree that this approach would be more minimalistic than other approaches.

If I do understand right you suggest to make the color of the pins selectable per list but not per cache?
Recently we changed our saving strategy a bit to go from a "list based" approach more to a "tag based" (i.e. it will be possible that caches are on more than one list now, one could say "They are now tagged with each list they belong to).
So if this would be a feasible approach it would be more appropriate to have it cache based rather than list based.

Would you also be able to contribute for the code implementation of such a feature?

**Comment by SirMacArthur** [comment]
Thanks for the response. 

I suppose it could be cache based (or even tag based rather). The idea was to try to simplify it as much as possible while still giving the end user a little more customization/control. The stored list method would not add additional buttons/clutter to the main cache page. Whichever is easiest to implement and/or more intuitive to the interface would still be a beneficial improvement. 

And as for contributing, I am a healthcare worker by trade and have no real ability to code (it took me a few hours to write and figure out how to format the initial post correctly, lol). I would be happy to contribute in a less technical capacity however if one exists.

**Comment by yellowduck** [comment]
I also raised a similar request #3057.
Recently, I have started using the offline log capability to mark specific caches. For example I mark caches in the UK Church Micro series with a 'needs maintenance' flag. I'll try & upload an image. (They're churches, hence the use of a cross)!
![2016-06-21 14 41 06](https://cloud.githubusercontent.com/assets/1512344/16233937/e0f21d5a-37c7-11e6-8241-0e22b0724c22.png)

**Comment by gsstark** [comment]
So I'll summarize my proposal from #6187 here:

Don't try to squeeze lots of information on the map and don't drive the UI from the map. There's not enough space there for much so you'll end up with a very limited UI. Instead, add details to the listing page and then look for how to summarize the information on the map later.

I would suggest displaying the lists the caches are in on the listing page. Either the full names, or first letter, or selected icon for each list.

For example I could have a Jasmer list and then the word Jasmer would show up after "Offline" for each missing Jasmer when I'm looking at Nearby caches or caches stored on other lists. Or maybe it would just display a J and I might use emoji characters to put a neat icon there.

Then on the map you would probably summarize that info by displaying a star or something if it's on any lists other than the currently displayed list. Display as LIst would let you see which attributes are in the area.

**Comment by GodfatherThe** [comment]
@SirMacArthur really like your suggestion since I have the same problem. So 👍 

About the contribution - I'm not an Java expert so far, unfortunately, but sometimes I'm trying to do something with it..

**Comment by moving-bits** [comment]
Implemented (in a slightly different way) with #7761, therefore closing this one.
