### ISSUE TITLE
Feature Request - Show County Cache is in

### ISSUE THREAD

**Issue by cniehaus2** [cgeo/cgeo#5801]
##### Detailed steps causing the problem:
- Step 1 - when working on a geocache county challenge it is sometimes hard to tell via the map what county the cache is in - especially if the cache is near a county line.

##### Other comments and remarks:
An added line of information stating rh county the cache is in would help those completing county challenges a lot.

**Comment by SammysHP** [comment]
You can use a map style with big borders.

**Comment by Lineflyer** [comment]
We have a similar request from @Bananeweizen AFAIR
-------- Ursprüngliche Nachricht --------Von: SammysHP <notifications@github.com> Datum: 25.06.16  09:19  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Betreff: Re: [cgeo/cgeo] Feature Request - Show County Cache is in (#5801) 
You can use a map style with big borders.

**Comment by Lineflyer** [comment]
I think this request is more or less the same as in #4457 (reverse geocoding).
Lets continue in that other issue.
