### ISSUE TITLE
Logbook entries are not loaded when viewing the cache second time

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5802]
##### Detailed steps causing the problem:
- Navigate so some SU cache using Live map
- Open details
- Make sure Logbook appeared, it's ok
- Return back to map
- Click on the same cache agin and open details again
- Make sure No logbook was loaded

##### Actual behavior after performing these steps:

No logbook was loaded

##### Expected behavior after performing these steps:

Logbook should be loaded

##### Version of c:geo used:

2016.06.27-NB-c9c941d

##### Is the problem reproducible for you?
Yes

##### System information:
-— System information —-
Device: D5803 (D5803, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.232
Cgeo version: 2016.06.27-NB-c9c941d
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Debug mode active: no
Geocaching sites enabled:
Geocaching.su
Installed cgeo plugins: calendar, contacts
-— End of system information —-

**Comment by Lineflyer** [comment]
Tested with cache MS18222 with 2016.06.27-NB-c9c941d and cannot reproduce.
Logbook is shown each time I open the cache from live map

**Comment by GodfatherThe** [comment]
I can attach screen record video to show it. For me it's reproducible with all caches. It appears again after click Refresh, but if I go back and open again - no logs...

**Comment by GodfatherThe** [comment]
Also I've found out that for GC.com caches there is some "mark"-circle around not loaded caches (and it disappears after viewing\storing, but for SU there is no such circle

**Comment by SammysHP** [comment]
Because SU provides correct coordinates. An orange circle means that no precise coordinates are available.

**Comment by GodfatherThe** [comment]
Video https://yadi.sk/i/2Q97p00HtEpKS

**Comment by Bananeweizen** [comment]
This might be one of two reasons:
* actually two instances of the cache (one from live map, one from detailed parsing)
* parsing the bounding box search overwrites existing logs in database, since the bounding box response doesn't contain any logs

have to investigate when there is more spare time

**Comment by Lineflyer** [comment]
Also in this case a debug log might help to see whats happening in the background (e.g. loading from live map is still ongoing?).

**Comment by GodfatherThe** [comment]
@lineflyer maybe I didn't catch the steps from the link (how-to-send-log), but I see nothing in logcat log. Nothing but "timeline activity idle id". So I'm not even sure that logging works... How can I check it?
