### ISSUE TITLE
Coordinates are copied with bullet

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5809]
##### Detailed steps causing the problem:
- Open a cache
- Long press on coordinates
- Select "copy to clipboard"

##### Actual behavior after performing these steps:
The copied coordinates contain a centered dot, e.g. `N 52° 36.123 · E 010° 06.456`.

##### Expected behavior after performing these steps:
`N 52° 36.123 E 010° 06.456`

**Comment by Lineflyer** [comment]
I agree that the bullet is not needed here (AFAIR it used to be like that ever since). Whoever fixes that should take care that pasting from clipboard (e.g. in waypoint creation) will still work.

**Comment by pstorch** [comment]
If it is ok to also remove the bullets from the view, than it's an easy fix, see PR #5812.
If the bullets should be kept in the view I have to think a bit more. Just tell me.

**Comment by rsudev** [comment]
I must admit I visually like the bullet in the view.

**Comment by pstorch** [comment]
I guessed that ;) 
I'll change it to only remove the dot on copy & paste.

**Comment by pstorch** [comment]
I've kept the display format and remove the middle dot now right before copying it to the clipboard.
