### ISSUE TITLE
Live Map issues - Cache icons

### ISSUE THREAD

**Issue by JGrouchy** [cgeo/cgeo#5811]
##### Detailed steps causing the problem:
- Accessing Live Map

##### Actual behavior after performing these steps:
- Cache icons on the Live Map are all showing as generic question marks.  After touching an icon, the cache pop-up appears.  I close out of this and the correct icon then shows, but if I've already found the cache it does not show the "smiley face".  I then have to refresh the listing in order for it to show as found.  This behavior is for each cache icon...they do not all appear once one is updated.  I have to go through each icon one-by-one.

##### Version of c:geo used:
2016.06.09

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
--- System information ---
Device: LGLS990 (g3_spr_us, lge)
Android version: 5.0.1
Android build: LRX21Y
Cgeo version: 2016.06.09
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: fastest
HW acceleration: enabled (default state)
System language: en_US
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---



##### Other comments and remarks:

**Comment by rsudev** [comment]
This is expected, as you have set the live-map mode to fastest (in the strategy menu). In this mode, the cache icons are not scanned to get the type. To get the desired behaviour, set the strategy to fast instead.

**Comment by Lineflyer** [comment]
As @rsudev stated the reason is
`Map strategy: fastest`

Please refer to http://faq.cgeo.org/#map-strategy for details
