### ISSUE TITLE
Fdroid SSL expiresd in 1 week

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#5817]
we need to make new certificate for Fdroid. I can sign it but I need CSR. You can send it to my email.

```use the openssl command: openssl req -newkey rsa:2048 -keyout yourname.key -out yourname.csr```

**Comment by SammysHP** [comment]
Why not Let's Encrypt?

**Comment by kumy** [comment]
@mucek4 mail send right now.
@SammysHP Sure! I already thought about it. As I already use it for GKM... I have not much time at the moment. I do it later. I plan to combine that with migrating to docker.
