### ISSUE TITLE
Add possibitity to download caches in backgound

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5819]
##### Detailed steps causing the problem:
Add possibitity to download caches in backgound. For now if I download ~100 caches or more, it takes several minutes to complete and c:geo is unusable for these minutes.

**Comment by SammysHP** [comment]
Duplicate (cannot search the issue number at the moment).

**Comment by pstorch** [comment]
I found this rather old issue #330. It has a long tail of discussion and an abandoned (?) solution.
