### ISSUE TITLE
Unify import order

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5822]
Here are my settings in IntelliJ IDEA for the order of imports. It can be changed easily. In any case, Eclipse and IDEA users should use the same order to prevent imports from going back and forth every time a file is changed:

```
import static all other imports

import butterknife.*

import cgeo.*

import all other imports

import android.*

import java.*

import javax.*
```

with blank lines between every group if there is at least one element.

**Comment by Bananeweizen** [comment]
In Eclipse we have project specific settings (but I have no idea where those come from) which say
cgeo.*
com.*
org.*
android.*
java.*
javax.*

The default sort order in Eclipse (without the project settings) would be
java.*
javax.*
org.*
com.*

All these are non static imports only.

Given that higher statements have priority in case of similar names, I'm tempted to suggest:
cgeo.*
android.*
java.*
javax.*
everything else

In Eclipse I cannot specify any options for empty lines. Will have to see if that fits.

**Comment by samueltardieu** [comment]
Works for me.

**Comment by samueltardieu** [comment]
Added to https://github.com/cgeo/cgeo/wiki/Coding-Conventions#imports-order

**Comment by Lineflyer** [comment]
@samueltardieu Does this still need to be open?

**Comment by Bananeweizen** [comment]
@samueltardieu I have no idea where this is stored in IDEA on disk, but it currently does not fit the above mentioned coding conventions. When I changed this in the project settings, I also did not notice any git change, so I fear this IDEA setting is currently not under version control.
