### ISSUE TITLE
Add .mwm maps support (Maps.Me)

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5824]
Just found out that despite c:geo has offline maps support, it doesn't work with native maps.me maps which are in .mwm format.

Steps:
- Install maps.me
- download some areas for offline use
- make sure they were downloaded in .mwm
- run c:geo, point to the folder with downloaded map files
- make sure no new maps were added to c:geo

It really makes sense, because it's the default use case - download some maps from the mobile maps app and then use it in c:geo.

**Comment by SammysHP** [comment]
It's not really the default case. You have downloaded maps for maps.me, fine. Most other apps (including c:geo) requires the mapsforge format.

Maps.me does not have a library that could be used in other apps.

**Comment by GodfatherThe** [comment]
Ok, but still - isn't it a valid feature request?

**Comment by rsudev** [comment]
The first question would be, if this is at all possible. Seemingly they published their sources under an Apache license, so in principle it is possible.
Next question, is this feasible? Here I tend to say no. If it is not desinged and documented as a reusable library, the effort to carve that out of the existing implementation is prohibiting. Just to mention on top that we struggle to keep our support for mapsforge and google maps somewhat in shape.
So, of course this is in principle a 'valid' feature - but the probability that it may get implemented this side of eternity is practically zero, so it is not sensible to keep it open.

**Comment by chstdu** [comment]
My smartphone has no more free space, so it would be great if I could use the same offline map for Maps.me and c:geo and save lots of space! Is there still no documentation and has anybody asked the staff of Maps.me about that already?
