### ISSUE TITLE
Login failed: Unknown error (Inactive account)

### ISSUE THREAD

**Issue by since80808** [cgeo/cgeo#5832]
Updated,
logging normally with my Geocaching.com accaunt "port08"
but
not logging with my other accaunt "roma shka"
with message: "Login failed: Unknown error"

Please help.
Thank you!

**Comment by SammysHP** [comment]
https://geoclub.de/forum/viewtopic.php?f=155&t=78909

**Comment by since80808** [comment]
There is no solution at geoclub.de, because people change passwords, reinstall apps and no result. Me too

**Comment by samueltardieu** [comment]
Has anyone having the problem tried with a nightly build?

**Comment by rsudev** [comment]
The problematic account name in this case contains a space (just an observation). I tried to create such account right now, but this is prevented with 'this account name contains invalid characters'.
@since80808 Can you confirm that you really have a space in your account name?

**Comment by UniQP** [comment]
@rsudev Confirmed. The account name is "Roma Shka".

**Comment by since80808** [comment]
Thanks, but no :)

Sure, there is a space in the user name and it's ok for c:geo :) The
problem was that the user was inactive at gc.com.

Resolved.

**Comment by UniQP** [comment]
https://support.groundspeak.com/index.php?pg=kb.page&id=219 says

> Inactive Member - has requested that their account be disabled

@since80808 Did you asked groundspeak to disable your account?

I think we should try to improve the error message for such cases.

**Comment by since80808** [comment]
No, I've found my account nactive and e-mailed to activate it.

15 июля 2016 г. 18:37 пользователь "Sebastian Buchwald" <
notifications@github.com> написал:

**Comment by UniQP** [comment]
Does anyone have access to an inactive account, so we can make some progress here?

**Comment by SammysHP** [comment]
You could ask Groundspeak to disable your account. ;)

**Comment by Bananeweizen** [comment]
I've asked on facebook, so maybe we get some HTML pages sent to the support mail account: https://www.facebook.com/android.geocaching/

**Comment by Lineflyer** [comment]
We have new occurence of this problem.
Seems that for some reasons a mail adress might become invalidated by gc.com (maybe also due to temporary reception problems) whereafter c:geo fails with unknown reason.

I will try to reproduce this by either changing my account to an invalid mail adress or deactivating the mail adress temporary.
What HTML page would you need to be able to follow up a better error detection for this case (actually I don't know exactly which URL we use for login).

**Comment by UniQP** [comment]
We need the page you receive after the failed login at https://www.geocaching.com/login/default.aspx (with a browser).

We should first validate whether the issue still remains, I think geocaching.com had some general login problems in the past few days:
http://ci.cgeo.org/job/cgeo%20pull%20request/784/
http://ci.cgeo.org/job/cgeo%20pull%20request/786/
http://ci.cgeo.org/job/cgeo%20pull%20request/789/

**Comment by UniQP** [comment]
We have a new occurrence of the problem: [review](https://play.google.com/store/apps/details?id=cgeo.geocaching&reviewId=Z3A6QU9xcFRPSGhmY2dSdU04RnRERkkxVllMa3p0cmVDRUtpOGNQOURLOXVFSlhDRkhFeVdJTEZZQXl5WXBSSFFzUEJxdmpNWWJRWDE0VG92WUZIQjktWWZj), [user profile](https://www.geocaching.com/profile/?guid=74373f69-9d67-4a3e-aafd-0ac3e2f83457).

Can someone ask if the user could provide the web page mentioned above?

**Comment by SammysHP** [comment]
I answered him via Google Play:

> Dein Account bei geocaching.com wurde durch Groundspeak deaktiviert. Wir würden diese Situation gerne in c:geo berücksichtigen, brauchen dafür aber deine Hilfe: Bevor du irgendetwas bei geocaching.com unternimmst, kontaktiere uns bitte über support@cgeo.org und wir werden dir weitere Schritte mitteilen.

**Comment by Lineflyer** [comment]
Refer to #8625
