### ISSUE TITLE
Debug logging doesn't work

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#5833]
##### Detailed steps causing the problem:
- Enable debug logging in settings
- do something with the app
- Open alogcat or Log Collector

##### Actual behavior after performing these steps:
I do not see any cgeo entries in the log

##### Expected behavior after performing these steps:
I assume, something should appear

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: D5803 (D5803, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.232
Cgeo version: 2016.07.15-NB-119f75b
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: en_US
Log date format: 7/15/2016
Debug mode active: yes
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   Geocaching.su
Installed cgeo plugins: calendar, contacts
--- End of system information ---

```

##### Other comments and remarks:
I cannot attach full log, but this line maybe will give a clue... At least, I do not see anything else which may be connected to cgeo..

D/*** DEBUG ***(25974): ROOT REEError running exec(). Command: [su] Working Directory: null Environment: null

**Comment by Lineflyer** [comment]
Is your device rooted and did you enable root access for the debugging app?

**Comment by GodfatherThe** [comment]
Oh, my fault, I've forgot that my phone is not rooted. Than I close it.
As soon as I'm travelling now, cannot get root until August. But don't you have possibility to write log info to a regular file which is accessible without rooting?
