### ISSUE TITLE
How to use mapsforge Themes and where to get them?

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#5834]
I know you are not the mapsforge support team, but you have the "Offline Maps" feature, which I use very often (especially abroad), so I think I'll ask here. I figured out a long time ago where to get the maps, but I still struggle on how to apply Themes to those maps.

There are pages that provide mapsforge themes, but I got them never to work in c:geo. _Is there a source for these themes or could you at least include a few more themes?_ Mapsforge (v0.6.1) does not include any other built-in themes than the default.

I don't know how many users actually use this feature, but I think it would be more users if the feature was more "_accessible_".

Some of the pages that give themes for free:
- http://www.openandromaps.org/en/legend/elevate-mountain-hike-theme
- http://openmaps.eu/mapsforgetheme

Sidenote: I also found the thread (mentioned in the help here: http://www.cgeo.org/faq.html#osm-use-themes) where user @Lineflyer asks if he could use a theme, but most of the links seem to be dead: http://forum.locusmap.eu/index.php?topic=1753.0

**Comment by Lineflyer** [comment]
This might be helpful regarding use of themes:
http://www.cgeo.org/faq.html#osm-use-themes

Regarding the source....
What kind of theme are you looking for?

**Comment by SammysHP** [comment]
Actually most maps require a theme specifically made for that map (and version). So you need to update both at the same time and use the one that was bundled together with the map.

**Comment by ControlTheBit** [comment]
@SammysHP 
I mostly download my maps from [here](http://download.mapsforge.org/maps/) or [here](http://extract.bbbike.org/) (this one has more details) and none of them requires an additional theme afaik.

@Lineflyer 
I'm looking for themes like the one from OpenStreetMap (Default) or something close to it. Also a map/theme like "Thunderforest Landscape" would be awesome, since I didn't find any offline topo maps yet...

**Comment by SammysHP** [comment]
I'll close this issue because it is not related to c:geo and issues are not for support anyway.

**Comment by ControlTheBit** [comment]
Don't get me wrong; I understand why you close this issue and I don't want to tell you how to handle your issues, but I still think it's a bit rude.

I know technically I have to ask the guys from mapsforge, but just from the users side of view, I have a problem with c:geo and therefore my proposal would be to improve the FAQ page on cgeo.org with sources for maps and themes. Currently you link the mapsforge maps mirror in the FAQ but when it comes to Themes you just say "google it". Some links would definitely be appreciated there.

I want to provide constructive feedback, so that every user can benefit.

**Comment by rsudev** [comment]
I guess one point is, that we do not have a source or standardized approach as a team in this area. Some use 'Freizeitkarte' (which comes with a mandatory theme, but AFAIK might not work on our old version of the mapsforge library) or OpenAndroMaps (which also only works well with the associated themes). So I am personally not even aware of other sources for themes or track them so I could provide an up-to-date FAQ for that.

**Comment by SammysHP** [comment]
As you can see above you got some answers (also one from me), waited for your response and only then closed the issue. You didn't ask for an improved FAQ, that would go to the website repository: https://github.com/cgeo/cgeo.github.io

I think we should list some more sources or simply link to this list: http://wiki.openstreetmap.org/wiki/Mapsforge

**Comment by ControlTheBit** [comment]
Alright, thanks for the FAQ improvement . Makes it more clear to me 👍

**Comment by pihentagy** [comment]
Isn't there a cooking guide how to use a stylemap with contour-map? Maybe one who's succeeded based on the faq?

thanks

**Comment by SammysHP** [comment]
@pihentagy
You should ask such questions in a mapsforge group.

**Comment by pihentagy** [comment]
Well, now _some_ styles are working, but not all of them. (The styles seems to be correct, verified by OruxMaps)
