### ISSUE TITLE
Update master configuration

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5838]
Master needs to include the SDK "extra-google-m2repository" to be able to get the latest Google Play Services. Nightly/RC/release builds will likely fail in the meantime.

**Comment by Lineflyer** [comment]
@mucek4 
Can you please fix this as soon as you have some minutes as we/I need the nightlies for testing. Also in the hopefully unlikely event of a needed release we need a working CI.

**Comment by mucek4** [comment]
My email didn't get trough? OK. I was on holiday without computer. What exactly I have to do? In the SDK manager I can't find m2repository.

**Comment by kumy** [comment]
@mucek4 this command should be sufficient:

`android update sdk --all --no-ui --filter extra-google-m2repository`

**Comment by mucek4** [comment]
Done. Close if it's OK.

**Comment by kumy** [comment]
Let's see how it goes. Manually launched build on master:

http://ci.cgeo.org/job/cgeo%20continuous%20integration%20-%20manual%20build/112/

**Comment by kumy** [comment]
Don't know what happens. 
```
08:51.684  :main:connectedBasicDebugAndroidTest
11:13.366  
11:13.366  cgeo.geocaching.activity.ProgressTest > testProgressWrapper[A4.1(AVD) - 4.4.4] [31mFAILED [0m
11:13.366  	java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
11:13.366  	at cgeo.geocaching.AboutActivity$VersionViewCreator_ViewBinder.bind(AboutActivity$VersionViewCreator_ViewBinder.java:10)
11:13.732  Tests on A4.1(AVD) - 4.4.4 failed: Instrumentation run failed due to 'java.lang.IllegalAccessError'
11:27.900  :main:connectedBasicDebugAndroidTest FAILED
```

**Comment by kumy** [comment]
Don't know what the problem with this test, but original issue is solved (missing library).
