### ISSUE TITLE
Improve list handling in map popup

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5839]
Short, because from mobile.
- [x] buttons in map popup are small and the text is truncated
- [ ] storing a cache requires an additional action, first select a list, then press ok (previously only select list)
- [x] you can press ok without selecting a list first, cache is stored, but not in a list

**Comment by pstorch** [comment]
The second point is because it is possible to store a cache on several lists at once. So we can't start the store action with a press on the list item only.

**Comment by SammysHP** [comment]
Yep, but a shortcut (e.g. long press on list) would be nice.

**Comment by pstorch** [comment]
Yes, this could work

**Comment by Bananeweizen** [comment]
fixed third item

**Comment by pstorch** [comment]
I have a look at the first item

**Comment by pstorch** [comment]
I'm still thinking about number 2. The list selection dialog is used in two cases, when the cache is stored the first time and to manage the lists, if it is already stored. 
The solution with the longpress on an item to select it and confirm the dialog would only make sense on the first store, when the cache is not on any list yet. It would be confusing when managing the lists.

But there is another possibility: what about preselecting the default list `Stored` in cases where the cache is not yet on any list. This would save one click for the default case. Just hit `OK`. But the users who want to put it on a different list than the default would need 3 clicks. First deselect the default, select the other list and hit `OK`.

While writing this comment and testing again the current behavior I realized that the **move** feature is also working when the cache is not stored yet. So a long press on the `Store` button allows you to store the Cache with a single click on the target list. @SammysHP does this already support your case? 
It's just a bit misleading that the title of the list selection dialog is **Move to different list** in that case.

**Comment by SammysHP** [comment]
I think this is something that one can get used to. So I'd like to get some more feedback from other users for number 2.

**Comment by pstorch** [comment]
There are some more rough edges on the **move** feature: Besides the title when the cache is not stored yet, the `Drop` button (or Trashcan) is not shown after it is stored.
And the **move** feature is missing on the map popup.
Regardless what we decide here, the **move** feature needs some polishing.

**Comment by pstorch** [comment]
Coming back to this issue. In the meantime it is possible with a long press to store a cache on the last used list. @SammysHP is it good enough to close it?

**Comment by SammysHP** [comment]
Yep, should be fine now.
