### ISSUE TITLE
c:geo crashes right on start on CM13 / Android 6.0.1

### ISSUE THREAD

**Issue by hiteo** [cgeo/cgeo#5841]
##### Detailed steps causing the problem:
- have cyanogenmod 13 (Android 6.0.1, see below)
- have current version of c:geo from google playstore
- try to start c:geo - and it immediately crashes

##### Actual behavior after performing these steps:
- c:geo briefly shows main screen for half a second and then crashes

##### Expected behavior after performing these steps:
- c:geo should start and either display main screen or setup screen for first install

##### Version of c:geo used:
- current version from playstore (2016.06.09)

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```
Unavailable since I even cannot enter the main screen.
Device: Samsung Galaxy S5 (klte), Cyanogenmod 13.0-20160717-NIGHTLY-klte

##### Other comments and remarks:
I used c;geo on this phone with cyanogenod 12.1 and it was all fine. Updated to 13 this week (clear install with wipe) and re-installed all apps from playstore. They all work fine but not c:geo. Reinstalled both the OS and c:geo but it still crashes while other apps (e.g. Locus) work fine.

**Comment by samueltardieu** [comment]
Can you please send a log?

**Comment by samueltardieu** [comment]
Also, please try installing the nightly version of cgeo (from http://download.cgeo.org/cgeo-nightly.apk) and report whether it crashes or not at launch. I use CM13 nightly to develop cgeo myself, so I know it is supposed to work there.

**Comment by hiteo** [comment]
Thank you for your quick reply. Please be patient with me since I actually set foot on new ground with all this programming, logging, debugging, console command, whatever stuff :-)
I tried to get a log with "adb logcat | findstr cgeo". This is the result:
`07-18 14:33:48.639   663  1364 I ActivityManager: Force stopping cgeo.geocaching appid=10083 user=0: from pid 6447
07-18 14:34:34.066   663  1395 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=cgeo.geocaching/.MainActivity (has extras)} from uid 10022 on display 0
07-18 14:34:34.130   663  1389 I ActivityManager: Start proc 6989:cgeo.geocaching/u0a83 for activity cgeo.geocaching/.MainActivity
07-18 14:34:34.222  6989  6989 W System  : ClassLoader referenced unknown path:/data/app/cgeo.geocaching-1/lib/arm
07-18 14:34:35.078  6989  6989 E AndroidRuntime: Process: cgeo.geocaching, PID:6989
07-18 14:34:35.078  6989  6989 E AndroidRuntime:        at cgeo.geocaching.playservices.LocationProvider.updateRequest(LocationProvider.java:55)
07-18 14:34:35.078  6989  6989 E AndroidRuntime:        at cgeo.geocaching.playservices.LocationProvider.onConnected(LocationProvider.java:141)
07-18 14:34:35.080   663   951 W ActivityManager:   Force finishing activity cgeo.geocaching/.MainActivity
07-18 14:34:35.611   663   688 W ActivityManager: Activity pause timeout for ActivityRecord{bc2444a u0 cgeo.geocaching/.MainActivity t152 f}
07-18 14:34:40.072   663  1395 I WindowState: WIN DEATH: Window{14bb5c6 u0 cgeo.geocaching/cgeo.geocaching.MainActivity}
07-18 14:34:40.098   663  1387 I ActivityManager: Process cgeo.geocaching (pid 6989) has died
07-18 15:23:50.862   663   679 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=cgeo.geocaching/.MainActivity (has extras)} from uid 10022 on display 0
07-18 15:23:50.907   663   942 I ActivityManager: Start proc 10008:cgeo.geocaching/u0a83 for activity cgeo.geocaching/.MainActivity
07-18 15:23:50.987 10008 10008 W System  : ClassLoader referenced unknown path:/data/app/cgeo.geocaching-1/lib/arm
07-18 15:23:51.560   663   703 I ActivityManager: Displayed cgeo.geocaching/.MainActivity: +664ms
07-18 15:23:51.589 10008 10008 E AndroidRuntime: Process: cgeo.geocaching, PID:10008
07-18 15:23:51.589 10008 10008 E AndroidRuntime:        at cgeo.geocaching.playservices.LocationProvider.updateRequest(LocationProvider.java:55)
07-18 15:23:51.589 10008 10008 E AndroidRuntime:        at cgeo.geocaching.playservices.LocationProvider.onConnected(LocationProvider.java:141)
07-18 15:23:51.591   663 12371 W ActivityManager:   Force finishing activity cgeo.geocaching/.MainActivity
07-18 15:23:52.116   663   688 W ActivityManager: Activity pause timeout for ActivityRecord{a7fba4 u0 cgeo.geocaching/.MainActivity t160 f}
07-18 15:23:56.969   663  1387 I WindowState: WIN DEATH: Window{ab5937d u0 cgeo.geocaching/cgeo.geocaching.MainActivity}
07-18 15:23:56.981   663  1419 I ActivityManager: Process cgeo.geocaching (pid 10008) has died
07-18 15:32:30.940   663 12371 I ActivityManager: Force stopping cgeo.geocaching appid=10083 user=0: from pid 8934
07-18 15:32:41.358   663   678 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=cgeo.geocaching/.MainActivity (has extras)} from uid 10022 on display 0
07-18 15:32:41.400   663  1387 I ActivityManager: Start proc 10710:cgeo.geocaching/u0a83 for activity cgeo.geocaching/.MainActivity
07-18 15:32:41.498 10710 10710 W System  : ClassLoader referenced unknown path:/data/app/cgeo.geocaching-1/lib/arm
07-18 15:32:42.194   663   703 I ActivityManager: Displayed cgeo.geocaching/.MainActivity: +805ms
07-18 15:32:42.220 10710 10710 E AndroidRuntime: Process: cgeo.geocaching, PID:10710
07-18 15:32:42.220 10710 10710 E AndroidRuntime:        at cgeo.geocaching.playservices.LocationProvider.updateRequest(LocationProvider.java:55)
07-18 15:32:42.220 10710 10710 E AndroidRuntime:        at cgeo.geocaching.playservices.LocationProvider.onConnected(LocationProvider.java:141)
07-18 15:32:42.224   663  1403 W ActivityManager:   Force finishing activity cgeo.geocaching/.MainActivity
07-18 15:32:42.750   663   688 W ActivityManager: Activity pause timeout for ActivityRecord{9d85b00 u0 cgeo.geocaching/.MainActivity t162 f}
07-18 15:32:45.446   663  1364 I WindowState: WIN DEATH: Window{7718a9 u0 cgeo.geocaching/cgeo.geocaching.MainActivity}
07-18 15:32:45.471   663   951 I ActivityManager: Process cgeo.geocaching (pid 10710) has died`

Furthermore, I tried to analyze that with my noobie-skills and in line 4 it says "/data/app/cgeo.geocaching-1/lib/arm". I looked that up with root access in file manager but there was no subfolder or file "arm" in the folder ".../lib/". However, there was a subfolder "arm" in "/data/app/cgeo.geocaching-1/oat/". Don't know if this is causing the trouble but maybe there is just something messed up in the folder structure?

If this is not the log you expect please tell me which log (and how) I should send you.

**Comment by hiteo** [comment]
Update:
I did a full wipe again and reinstalled CM 13 and all the apps from playstore, including c:geo (2016.06.09), again, just like I did two times before. Then some magic happened and now c:geo starts up and runs nicely. I don't know why or how, all I can say is it works now. I apologize for any inconvenience.

**Comment by samueltardieu** [comment]
No problem. Thanks for your report anyway!
