### ISSUE TITLE
CITO not listed in History

### ISSUE THREAD

**Issue by cuberik** [cgeo/cgeo#5855]
I recently attended a CITO event. Logged it in c:geo, it has a "green sign" in front. But it is not listed in the History list. My number of founds is 378 at this moment, but the History list shows a number of 377 caches and the CITO is missing in the list.

Also:
I put all caches I found in an additional "Found" list. This list holds 378 caches and shows the correct number of 378 caches, also the CITO. But when sorting it on found date, the CITO is not correctly sorted, it's always at the end of the list.

##### Version of c:geo used:
2016.06.09

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: ALE-L21 (ALE-L21, Huawei)
Android version: 5.0.1
Android build: ALE-L21C432B183
Cgeo version: 2016.06.09
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: nl_NL
Geocaching sites enabled:
 - geocaching.com: logged in (Ingelogd) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---

##### Other comments and remarks:

**Comment by Lineflyer** [comment]
- Was the related cache stored at the time of logging?
- DId you log it using the map popup instead of going to log from the cache details?

**Comment by cuberik** [comment]
Sorry, I do not remember that anymore.

I think it was not stored at the time of logging, and that I logged it online at geocaching.com, and that I stored it in cgeo after logging. But again, I'm not sure anymore.

I never had this problem with caches or other events. But I will attend another CITO in september, so I can try it again then.

Is there any prefered sequence in storing and logging?

**Comment by Lineflyer** [comment]
I was asking these questions as we do have a known bug here: #4086 

My guess is, that it is the same problem here but only a coincidence that it was a CITO.

I am closing this one for now. Feel free to reopen if there are new clues.
