### ISSUE TITLE
wheryougo downloads wrong cartridge

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5857]
##### Detailed steps causing the problem:
- Have Wheryougo installed
- open GC21X0F
- Select Navigation - Whereyougo

##### Actual behavior after performing these steps:
Whereyougo opens, logs in and offers to download a cartridge
The downloaded cartridge is not matching to the cache but belongs to another cache (of the same owner?)

##### Expected behavior after performing these steps:
Should trigger download of correct cartridge

##### Version of c:geo used:
Current nightly

##### Is the problem reproducible for you?
Yes for this cache

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

##### Other comments and remarks:
Might also be a problem within WhereYouGo??

**Comment by Bananeweizen** [comment]
Your cartridge is "Schatz vom Kölner Zoo", right? It is linked from the first Wherigo-Icon in "Lade dir den..."
