### ISSUE TITLE
"Spoiler image" not visible on c:geo

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#5859]
I have an problem were I am looking at a mystery cache which has an image containing a puzzle that needs to be solved to reveal the final co-ords. 
However, the image is not visible in c:geo - I only found it by looking at the cache in Firefox.

##### Detailed steps causing the problem:
- load GC6EYYH [ Sherlock Holmes' Retirement Cottage (East Dean) ] into c:geo
- try to view the image titled "Sherlock's Morris Men"

##### Actual behavior after performing these steps:
Only 4 images out of 5 are visible.
The image titled "Sherlock's Morris Men" is not visible anywhere.
But you can see it on the website.

##### Expected behavior after performing these steps:
All images (5 at the time of writing) should be visible.

##### Version of c:geo used:
2016.06.09

##### Is the problem reproducible for you?
Yes

##### System information:
Device: D6603 (D6603, Sony)
Android version: 6.0.1
Android build: 23.5.A.0.575
Cgeo version: 2016.06.09
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none

##### Other comments and remarks:
I also see the issue on my Nexus 7 and my partners Moto-G

**Comment by Bananeweizen** [comment]
The missing image was of "bmp" format, which we simply did not expect.

**Comment by alan666notb** [comment]
Should c:geo at least indicate that there's an image present that it can't display?

**Comment by Bananeweizen** [comment]
It did not recognize that there _is_ an image. It can display bmp formats.
