### ISSUE TITLE
Do not store last log for reuse if it is empty

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5861]

**Comment by GodfatherThe** [comment]
Maybe just do not allow to save log if it's empty?

**Comment by Bananeweizen** [comment]
At least I regularly log by storing an empty offline log and finally upload field notes with empty text. Therefore storing an empty text is surely a necessary use case. We just should not overwrite the log in the "clipboard" when mixing real log text and empty log text.

**Comment by GodfatherThe** [comment]
I just have observed the case when c:geo hanged during sending empty log. Although it was the only case, I thought that it's not allowed to send empty logs, but error handling was missed for this case.

**Comment by Bananeweizen** [comment]
I have recently seen an error message stating that I cannot send an empty log. However I don't know of that was an error message of our app or a server error message. In the latter case we should introduce a new method in the connector interface to validate logs before sending and disallow empty logs in the default implementation and in the GC implementation.

**Comment by Lineflyer** [comment]
AFAIK we have an own errormessage for that which was implemented some months ago.

**Comment by Bananeweizen** [comment]
This has been implemented with #6010.
