### ISSUE TITLE
Language change when rotating the device - again

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#5864]
Before reporting this bug I did a search on issues and found that issue #2343 seems to fit my problem as well.

##### Detailed steps causing the problem:
- Device language is Swedish
- c:geo is using device language by default
- Select "Använd engelska i c:geo" in Inställningar/Utseende ("Use English in c: geo "in Preferences / Appearance)
- Kill the app and restart it.
- Open Live Map and tap on a cache to get the pop-up window-
- Everything is in English. See Screenshot 1 below.
- Rotate the device
- Everything is now in Swedish. See Screenshot 2 below.
- Rotat the device back
- Everything is still in Swedish. See Screenshot 3 below.
- Close the live map.
- The home screen is in English, except for the filter button that says "Alla typer av cacher" instead of "All Cache Types". See Screenshot 4 below.
- Exit c:geo
- Enter c:geo again
- The home screen is now in Swedish. See Screenshot 5 below.
- Kill c:geo by swiping it off the recent apps menu
- Start c:geo
- The home screen is in English again

Screenshot 1:
![image](https://cloud.githubusercontent.com/assets/1811963/17277928/2af31b74-574f-11e6-9704-7f5a21d96630.png)

Screenshot 2:
![image](https://cloud.githubusercontent.com/assets/1811963/17277930/3a6013b4-574f-11e6-8318-4ade1918b2c9.png)

Screenshot 3:
![image](https://cloud.githubusercontent.com/assets/1811963/17277933/4b2695ec-574f-11e6-8f23-b9b0f752eeb3.png)

Screenshot 4:
![image](https://cloud.githubusercontent.com/assets/1811963/17277963/08da7e3c-5750-11e6-8ba0-01928012c695.png)

Screenshot 5:
![image](https://cloud.githubusercontent.com/assets/1811963/17277972/2d6b99a2-5750-11e6-866e-ef5cecf16b7f.png)

##### Version of c:geo used:

2016.07.31-NB-cec02b1

##### Is the problem reproducible for you?
Yes

##### System information:
```
Device: ONE E1003 (onyx, OnePlus)
Android version: 6.0.1
Android build: onyx-userdebug 6.0.1 MOB30R 7d75b40b67 test-keys
Cgeo version: 2016.07.31-NB-cec02b1
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: sv_SE
Log date format: 2016-07-31
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
   geocaching.com: Logged in (Inloggning OK) / PREMIUM
Installed cgeo plugins: calendar
--- End of system information ---
```

**Comment by kumy** [comment]
Confirmed.
Thanks for the detailed report.

**Comment by kumy** [comment]
@MrYaz did you check if this also happens on current release 2016.06.09?

**Comment by MrYaz** [comment]
Yes @kumy, it also happens on release 2016.06.09.
