### ISSUE TITLE
Own caches are not marked with a star, or hidden using "Hide own/found caches" in the map.

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#5866]
This bug has been present in the NB:s for maybe a week.
##### Detailed steps causing the problem:
- When opening any map view my own caches are not marked as a star
- They are not hidden when "Hide own/found caches" is checked.
##### Version of c:geo used:

2016.07.31-NB-cec02b1
##### Is the problem reproducible for you?

Yes
##### System information:

```
```

Device: ONE E1003 (onyx, OnePlus)
Android version: 6.0.1
Android build: onyx-userdebug 6.0.1 MOB30R 7d75b40b67 test-keys
Cgeo version: 2016.07.31-NB-cec02b1
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: sv_SE
Log date format: 2016-07-31
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
   geocaching.com: Logged in (Inloggning OK) / PREMIUM
Installed cgeo plugins: calendar
--- End of system information ---

```
```

**Comment by Lineflyer** [comment]
> They are hidden when "Hide own/found caches" is checked.

You mean **not** hidden?

**Comment by MrYaz** [comment]
> You mean **not** hidden?
Yes, sorry for the typo. Edited the post.

**Comment by Lineflyer** [comment]
It is not reproducible for me.
Are those owned caches saved on the device?

**Comment by Lineflyer** [comment]
Closing due to lack of feedback.
