### ISSUE TITLE
Option to use OpenStreetMap instead Google maps for offline storage

### ISSUE THREAD

**Issue by naoliv** [cgeo/cgeo#5880]
Could we have an option to generate the offline map using OpenStreetMap instead Google maps?

For example, this stored cache:

![](https://cloud.githubusercontent.com/assets/982338/17438676/7b51c378-5afa-11e6-98b0-bbc0117ddd70.png)

Is much better represented in OSM:

![](https://cloud.githubusercontent.com/assets/982338/17438681/8529b6d0-5afa-11e6-9f73-abcb606164f9.png)

c:geo version is 2016-08-03-RC

**Comment by rsudev** [comment]
Wouldn't be an option to use an OSM-based offline map instead? These static maps came from a time, when there were no other offline map options, which I would consider much superior nowadays.

**Comment by Lineflyer** [comment]
Is there a OSM source for static maps?

**Comment by naoliv** [comment]
Is the offline image generated in the client when the user asks to store the cache? (ie, it downloads only a small area)
I guess it's possible to use the default OSM tiles http://wiki.openstreetmap.org/wiki/Tile_usage_policy

**Comment by naoliv** [comment]
Or maybe we can see if we can get a permission to use OSM Landscape or OSM Outdoors tiles:

![](https://cloud.githubusercontent.com/assets/982338/17452266/e01b535c-5b43-11e6-8c57-125dfaa6d075.png)

They look nicer.

**Comment by pstorch** [comment]
If an offline map is available and configured I would prefer to see it there, too.

**Comment by SammysHP** [comment]
Tiles won't work. We need a static map provider with marker support. I know only mapquest and that is not free anymore AFAIK.

**Comment by naoliv** [comment]
I will see if @mapbox can help us and provide this

**Comment by SammysHP** [comment]
Free Mapbox plan has a limit of 50,000 mobile users / month (using the Mapbox Android SDK).

**Comment by andrixnet** [comment]
these maps could be generated directly from mapsforge data (same as used for the map screen with offline maps), right?

**Comment by SammysHP** [comment]
No, we talk about online services. Static maps from offline vector data does not make sense.

**Comment by Lineflyer** [comment]
Closing this due to no update.
Feel free to reopen with new relevant information.
