### ISSUE TITLE
New map, no more "show as list"?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5883]
##### Detailed steps causing the problem:
- Use the new live map
- Wait until load finish
- Open context menu

##### Actual behavior after performing these steps:
No more "show as list" menu

##### Expected behavior after performing these steps:
Show as list should be available

##### Version of c:geo used:
master from 07-31

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

**Comment by rsudev** [comment]
Another 'missing feature' of the new map. I'll see what I can do.

**Comment by andrixnet** [comment]
subscribe

**Comment by kumy** [comment]
@andrixnet no need to post to subscribe, this feature is on the right column here on github :)
![screenshot from 2016-09-01 11-17-15](https://cloud.githubusercontent.com/assets/176794/18162220/a96736ee-7035-11e6-8b8e-c778ef388640.png)

**Comment by rsudev** [comment]
based on release and merged to master for testing
