### ISSUE TITLE
Found date not shown with friends log disabled and list of logs very big

### ISSUE THREAD

**Issue by speedy-1702** [cgeo/cgeo#5884]
Found date is not shown when  found was a leap day See screenshot. 
![screenshot_2016-08-06-10-26-12](https://cloud.githubusercontent.com/assets/1996354/17455708/c68dbd58-5bc0-11e6-856f-678d9acf8abf.png)

**Comment by Lineflyer** [comment]
Can you please tell us the version of cgeo you are using?

**Comment by Lineflyer** [comment]
Not reproducible for me with 2016.08.06-RC1

Tested with GC6AQ29 which I found at 29.02.16

**Comment by speedy-1702** [comment]
2016.06.09 on samsung s4-mini 
Interesting.... 
This is the only found cache out of 1600, which resists to show me the found date. 
I guessed because of the leap day. This is the only particularity. 
Any suggestions?

**Comment by speedy-1702** [comment]
--- System information ---
Device: GT-I9195 (serranoltexx, samsung)
Android version: 4.4.2
Android build: KOT49H.I9195XXUCNK1
Cgeo version: 2016.06.09
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: disabled (default state)
System language: de_DE (cgeo forced to English)
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar
--- End of system information ---

**Comment by Lineflyer** [comment]
Did you try to refresh it?

**Comment by speedy-1702** [comment]
Yes, sure. I had it since leap day on the device and refreshed it today.

**Comment by rsudev** [comment]
The question is, whether it fails to read the date from the page or if the date is in the database and fails to get displayed.
To check this, my first suggestion would be to log-on to geocaching.com in the browser, open the cache page, save the page source and then send it to our support mail. We could then check if the parser can detect the found status and date.

**Comment by speedy-1702** [comment]
Done

**Comment by rsudev** [comment]
@Lineflyer @samueltardieu @mucek4 Could you forward the mail to the dev group? Thanks!

**Comment by Lineflyer** [comment]
Done!

**Comment by Bananeweizen** [comment]
Do you have the option for "Show own/friends logs" disabled (Preferences -> Cache details)? Can you please enable it and refresh the cache?

I currently suspect that we _only_ parse the log date from the log entries, not from the cache web page itself. Therefore this can be reproduced with the above mentioned option disabled and your own log entry not being in the first 35 shown log entries of the general log page.

For developers: Check senders of Geocache.setVisitedDate(). For online access to GC this is only found in getExtraOnlineInfo.

**Comment by speedy-1702** [comment]
option for "Show own/friends logs" is always enabled. Even disabled , refreshed, enabled and refreshed has no effect. Stall I delete my log and post a new attended log to come on top of the list?

**Comment by Bananeweizen** [comment]
That might help for confirming the root cause, although I'm confused by the option not having any effect for you. I can reproduce the missing log date for my own account using the above procedure with mega events that I attended.

**Comment by speedy-1702** [comment]
Verification is done. 
After deleting and re-entering my attended log,the found date appears. See screenshot 

Very nice workaround. Thank you for the support

**Comment by speedy-1702** [comment]
![screenshot_2016-08-07-17-28-42](https://cloud.githubusercontent.com/assets/1996354/17463412/f4172124-5cc4-11e6-9af0-4f602ddbec55.png)

**Comment by rsudev** [comment]
When looking at you your stored page I was suspecting a glitch due to the date format (on geocaching.com), but I guess you didn't change that before your final test, so this option is ruled out.
Quite strange...

**Comment by speedy-1702** [comment]
".... but I guess you didn't change that before your final test,...." 

Of course, I didn't

**Comment by Bananeweizen** [comment]
@rsudev I'm rather sure of my investigation that we simply don't parse the date from the cache page, but only from the log book. And the friends log enabled will fix this _only_ if there less than 35 friends logging after you. So even with the option enabled I still see how it could not work (while in most cases the option enabled will hide the bug).

**Comment by speedy-1702** [comment]
"...  And the friends log enabled will fix this only if there less than 35 friends logging after you.  ..."

There were less than 35 friends in the log list after me. The option was enabled as it always is, but it didn't help.

**Comment by rsudev** [comment]
@Bananeweizen Regarding the found date I came to the same conclusion in the meantime. From what I read filing through the code of getExtraOnlineInfo in the GCParser it seems to me, that own logs are requested separately from friend logs (with the same count of 35 :) ) which makes it even more mysterious.

**Comment by Lineflyer** [comment]
Closing due to lack of feedback/verification of the issue.
