### ISSUE TITLE
"Show Circles" missing

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5885]
One more thing still missing to bring the new map on par with the old one is the ability to display circles around caches and physical waypoint stages.

**Comment by samueltardieu** [comment]
This problem has been raised on support today.

**Comment by jakedot** [comment]
I'm going to see if I can get this to work on the weekend. @Lineflyer when would you be in IRC so I can call you for help on the IDE config? 😍😋

**Comment by Lineflyer** [comment]
I am the wrong one to ask regarding IDE config  as I have no idea of that.But others of the team might be around from time to time on IRC.Von meinem Smartphone gesendet.
null
