### ISSUE TITLE
Progress spinner shown also for each movement

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5892]
##### Detailed steps causing the problem:
- 2016.08.06-RC1
- Have beta map as default
- Open live map
- Wait for loading complete (spinner in action bar no longer shown)
- Start moving a short distance
##### Actual behavior after performing these steps:

On each position update/map movement the progress spinner appears for splits of seconds
##### Expected behavior after performing these steps:

Progress spinner only in case of network activity
(AFAIR thats how it works on the old map....but I might be wrong?!)
##### Version of c:geo used:

see above
##### Is the problem reproducible for you?

Yes

**Comment by rsudev** [comment]
On the old map, there might have been a larger distance to cover before a refresh was triggered or the progress. I need to re-check this.

**Comment by Lineflyer** [comment]
@rsudev 
I see you had a fix for this issue in your personal repo.
Would it be final to merge and test?

**Comment by rsudev** [comment]
According to my memory it was not yet ready for prime time. Dragged it out again and take a look.
