### ISSUE TITLE
Different arrangement of new icons in cache details

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5893]
Feedback from beta user:
Icons instead of text buttons are nice as they are bigger and clearer, however IMHO the delete button is at the wrong place (also compared to where the textual buttons have been).
I suggest to have only regresh in upper row and lower row should be edit left and delete right.
This also helps in accidently not tapping delete instead of refresh.

**Comment by Lineflyer** [comment]
I do agree.
In case of unsaved the save button is lower right. It should stay there and "change" to the delete button once saved.

So:
Upper row: Refresh
Lower row left: Edit (if saved)
Lower row right: Save / Delete

**Comment by pstorch** [comment]
I remember changing the arrangement in #5873 to make them the same in the Map Popup and the CacheDetails. Unfortunately it was the wrong way around. 
I can take this issue.
