### ISSUE TITLE
Waypoints hidden on map even below selected limit

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5900]
##### Detailed steps causing the problem:
- Use "Beta Map" as a live map
- Waypoint limit is set to e.g. 20 caches (or even more)
- Open live map showing caches and its waypoints
##### Actual behavior after performing these steps:

While scrolling on the map it often happens that the waypoint suddenly vanish even if the selected limit of shown caches is not reached.
Its not clearly reproducible but seems to be related to the cache itself being out of view on the map.
##### Expected behavior after performing these steps:

I crosschecked with the "Old map" and its working without a problem on the same occurence (same location and caches/waypoints on map)
##### Version of c:geo used:

2016.08.06-RC1
##### Is the problem reproducible for you?

Not clearly but happening often

**Comment by rsudev** [comment]
On the old map, the waypoints intially get on the map, if the cache is loaded for display as well (IIRC screen size + 20 % or so). If the cache is not on the map to begin with, the don't come up either. They stay on the map, as long as the cache is in the LRU list (and the limit is not reached of course. Normally they will not vanish at all).
On the new map the are tight to the visibility of the cache on the map. My goal is, to get them always displayed if they are in the viewport and the limit is not reached (and the cache is not filtered out), regardless of the cache location.

**Comment by Lineflyer** [comment]
> On the new map the are tight to the visibility of the cache on the map. My goal is, to get them always displayed if they are in the viewport and the limit is not reached (and the cache is not filtered out), regardless of the cache location.

That would reflect the users expectation indeed.

**Comment by Lineflyer** [comment]
Quite some beta feedback via support mail and on Google Play regardig this bug.
It seems, this is something we should IMHO try to fix rather soon to make the new map worth using for our users.

**Comment by rsudev** [comment]
Unfortunately is this not so easy (as I envision the implementation). As I mentioned is it only working 'accidentally' in a better fashion in the old implementation. I have it on my radar as one of the three major things to implement (in addition to the style menu and the missing 'circles')

**Comment by Lineflyer** [comment]
+3 from Beta Feedback and support mail (regarding the RC-version).

**Comment by okainov** [comment]
+1, interested in this one, one of killer-features why I'm not using "new map" (except impossibility to zoom out enough)

**Comment by Lineflyer** [comment]
I had the time yesterday to take a first look at the fix implemented by @rsudev. From the first look, I would say, that it working in principle, but the performance is rather low (even on my Galaxy device).

@rsudev Did you set any limit regarding the distance between the position of the cache in relation to the viewport shown on map? It seems like its crawling all my caches on each move of the map. Maybe you could explain the working mode a bit, to find out together how we could optimize that.

Furthermore it seems the appearance of waypoint is now more close to the desired behavior but nowthere seem to be cases, where waypoint kept being even above the limit (thus cluttering the map). But I need more time to test this in details.

**Comment by rsudev** [comment]
I didn't set a distance or anything in that regard, I just reused a function which was already there. Perhaps it is called with a higher frequency, need to check this out. The refresh on move code on the new map seems to have its quirks still.
If you find a cause for the overcrowding problem, please let me know.

**Comment by Lineflyer** [comment]
I think I found one "problem":
- Have caches with waypoints in same area on two different lists
- Open list 1
- Open map for list 1

- You will also see the waypoints of caches on list 2 on the map of list 1

I assume, that could be the performance problem I am experiencing here as I opened a list with only 45 caches but having a total of 2000 caches stored on all lists.

**Comment by rsudev** [comment]
And you did not 'enable live' on that map?
I will check, that should not happen.

**Comment by Lineflyer** [comment]
No, I did not.It seems to happen after the map has been zoomed and moved a bit.
It also happens, that WP from other caches  leak onto a single cache map.
null

**Comment by Lineflyer** [comment]
Beside the problem described above the fix seems to be OK as far as I could test.

@rsudev Did you have time to check the problem described above?

**Comment by rsudev** [comment]
Today I came around to check this regarding the leak of waypoints and failed to reproduce both scenarios (single cache map and cache list map with caches of same area on other list).
Sounds like something is still missing in the scenario.

**Comment by Lineflyer** [comment]
I keep having this problem all the time here on my vacation in Canada. Sometimes it needs a bit of zoom in/out before it happens.
Typical scenario here is:
- Having a list containing all caches in a certain area
- Having a list containing a subset of the other list (my ToDo)
- While mapping the second list, suddenly WP (but not the cache icons) from caches of the first list appear on the map
- WP limit is set to 30

**Comment by okainov** [comment]
Also reproducible for me, but with just one list. Sometimes zoom in-out helps, or minimizing and restoring the app

**Comment by Lineflyer** [comment]
As the main issue here is solved, but lead to a follow up problem, let us close here and track this in a dedicated issue.
