### ISSUE TITLE
Live map is not loading any caches

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5914]
##### Detailed steps causing the problem:
- Open Live map
- move...
##### Actual behavior after performing these steps:

Caches are not displayed
##### Expected behavior after performing these steps:

Caches should be shown
##### Version of c:geo used:

Lasted `release` (self build)
##### Is the problem reproducible for you?

This happens without any apparent reason
We have some reports on from Play Store comments, and also on IRC @Lineflyer 
##### System information:

```
--- System information ---
Device: m8 (cm_m8, htc)
Android version: 6.0.1
Android build: cm_m8-userdebug 6.0.1 MOB30R 702ea7c7ee test-keys
Cgeo version: 2016.08.21-6de45ba developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: fast
HW acceleration: enabled (default state)
System language: en_US
Log date format: 8/21/16
Debug mode active: yes (cgeo forced to English)
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: none
--- End of system information ---
```
##### Other comments and remarks:

As described by @Lineflyer disabling wifi (using phone operator data) solve the problem.
**May it be some sort of rate limiting?**
- However it "still" work from my desktop browser.
- Switching back to wifi, it start to work again

Here are some logs I could get:

```
08-21 22:37:49.266 30598-451/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-7] CachesToDisplay: 1, showWaypoints: true
08-21 22:37:49.267 30598-451/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-7] Layers for id 1 synced. Codes removed: 0, new codes: 0, geoEntries: 3
08-21 22:37:49.267 30598-30808/cgeo.geocaching D/cgeo: [network-5] GCMap.searchByViewport(N 43° 39.822 · E 006° 49.701,N 43° 44.468 · E 006° 54.150)
08-21 22:37:49.272 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.png?x=2126&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811869269
08-21 22:37:49.276 30598-30598/cgeo.geocaching D/cgeo: [main] DataStore.loadCaches([PK5BRQK, SE5BRQK]) returned no results
08-21 22:37:50.215 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] 200 (943 ms) GET https://tiles.geocaching.com/map.png?x=2126&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811869269 (http/1.1)
08-21 22:37:50.218 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.info?x=2126&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811869269
08-21 22:37:51.313 30598-30604/cgeo.geocaching W/art: Suspending all threads took: 19.362ms
08-21 22:37:51.431 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] 204 (1213 ms) GET https://tiles.geocaching.com/map.info?x=2126&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811869269 (http/1.1)
08-21 22:37:51.437 30598-30658/cgeo.geocaching W/cgeo: [RxComputationScheduler-1] GCMap.searchByViewport: No data from server for tile (2126/1494)
08-21 22:37:51.440 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.png?x=2125&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811871437
08-21 22:37:53.353 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] 200 (1913 ms) GET https://tiles.geocaching.com/map.png?x=2125&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811871437 (http/1.1)
08-21 22:37:53.356 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.info?x=2125&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811871437
08-21 22:37:55.845 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] 204 (2489 ms) GET https://tiles.geocaching.com/map.info?x=2125&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811871437 (http/1.1)
08-21 22:37:55.855 30598-30852/cgeo.geocaching W/cgeo: [RxComputationScheduler-2] GCMap.searchByViewport: No data from server for tile (2125/1494)
08-21 22:37:55.858 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.png?x=2126&y=1493&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811875856
08-21 22:37:58.231 30598-5111/cgeo.geocaching W/cgeo: [OkHttp] Failure (2373 ms) GET https://tiles.geocaching.com/map.png?x=2126&y=1493&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811875856 (javax.net.ssl.SSLException: Read error: ssl=0x96e69e80: I/O error during system call, Connection timed out)
08-21 22:37:58.232 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.png?x=2126&y=1493&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811875856
08-21 22:37:58.233 30598-5111/cgeo.geocaching W/cgeo: [OkHttp] Failure (1 ms) GET https://tiles.geocaching.com/map.png?x=2126&y=1493&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811875856 (javax.net.ssl.SSLException: Write error: ssl=0x96e66b40: I/O error during system call, Connection timed out)
08-21 22:37:58.248 30598-30808/cgeo.geocaching W/cgeo: [network-5] GCMap.searchByViewport: No data from server for tile (2126/1493)
08-21 22:37:58.252 30598-30808/cgeo.geocaching W/cgeo: [network-5] GCMap.searchByViewport: No data from server for tile (2125/1493)
08-21 22:37:58.254 30598-30808/cgeo.geocaching D/cgeo: [network-5] GCMap: returning 0 caches from search
08-21 22:37:58.255 30598-452/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-8] Filtering out 0 caches: []
08-21 22:37:58.255 30598-452/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-8] Live caches found: 1
08-21 22:37:58.255 30598-452/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-8] CachesToDisplay: 1, showWaypoints: true
08-21 22:37:58.256 30598-452/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-8] Waypoint PK5BRQK for id 2 not added, geoEntries: 3
08-21 22:37:58.257 30598-452/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-8] Waypoint SE5BRQK for id 2 not added, geoEntries: 3
08-21 22:37:58.257 30598-452/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-8] Cache GC5BRQK for id 2 not added, geoEntries: 3
08-21 22:37:58.257 30598-452/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-8] Layers for id 2 synced. Codes removed: 0, new codes: 0, geoEntries: 3
08-21 22:37:58.276 30598-30598/cgeo.geocaching D/cgeo: [main] DataStore.loadCaches([PK5BRQK, SE5BRQK]) returned no results
08-21 22:37:58.352 30598-30598/cgeo.geocaching D/NetworkChangeNotifierAutoDetect: Network connectivity changed, type is: 6
08-21 22:38:06.008 30598-30598/cgeo.geocaching D/NetworkChangeNotifierAutoDetect: Network connectivity changed, type is: 4
08-21 22:38:09.765 30598-451/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-7] Loading GC5BRQK Chemin de l'Escourachie from DB
08-21 22:38:09.766 30598-31703/cgeo.geocaching D/cgeo: [network-10] GCMap.searchByViewport(N 43° 40.088 · E 006° 49.554,N 43° 44.734 · E 006° 54.004)
08-21 22:38:09.768 30598-451/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-7] CachesToDisplay: 1, showWaypoints: true
08-21 22:38:09.774 30598-451/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-7] Layers for id 1 synced. Codes removed: 0, new codes: 0, geoEntries: 3
08-21 22:38:09.795 30598-30598/cgeo.geocaching D/cgeo: [main] DataStore.loadCaches([PK5BRQK, SE5BRQK]) returned no results
08-21 22:38:10.016 30598-451/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-7] Loading GC5BRQK Chemin de l'Escourachie from DB
08-21 22:38:10.018 30598-451/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-7] CachesToDisplay: 1, showWaypoints: true
08-21 22:38:10.020 30598-451/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-7] Layers for id 1 synced. Codes removed: 0, new codes: 0, geoEntries: 3
08-21 22:38:10.027 30598-30598/cgeo.geocaching D/cgeo: [main] DataStore.loadCaches([PK5BRQK, SE5BRQK]) returned no results
08-21 22:38:10.516 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.png?x=2126&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811889767
08-21 22:38:11.380 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] 200 (864 ms) GET https://tiles.geocaching.com/map.png?x=2126&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811889767 (http/1.1)
08-21 22:38:12.049 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.info?x=2126&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811889767
08-21 22:38:14.216 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] 200 (2166 ms) GET https://tiles.geocaching.com/map.info?x=2126&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811889767 (http/1.1)
08-21 22:38:15.280 30598-31703/cgeo.geocaching D/cgeo: [network-10] DataStore.loadCaches([GC5Z3ZX, GC5PDVB, GC5Q68Z, GC6JK8N, GC6B98P, GC5BYX4, GC6K9MM, GC63WGJ, GC5C0AN, GC6AAYR, GC5Z3YG, GC5PDVX, GC5BYXD, GC6FPNM, GC2TZXM, GC697DN, GC4ECCG, GC6A9J5, GC5PBJ0, GC6JK8E, GC5MN04, GC56ZHN, GC5Z3Z5, GC54YE8, GC4RY3V, GC6M0W7, GC2V058, GC5P7A1, GC5Z40F, GC5GDDC, GC6A9GN, GC5PBF5, GC40K1A, GC5PZBA, GC6M0WB, GC304VW, GC2V0AY, GC5GA4N, GC4TQ4G, GC5BYX6, GC4VMZT, GC6JBPZ, GC6A9HN, GC64F4H, GC5C09M, GC5PXW9, GC61AC3, GC5PB64, GC2V08P, GC5GQXH, GC6A9GY, GC16RRR, GC6A9HG, GC2V0F4, GC5Z132, GC6JBQ4, GC6A9J9, GC6E9NJ, GC5PDQB, GC5PDTX, GC6EJJB, GC5Z3ZG, GC6A9JH, GC5PEED, GC6A9GT, GC6A9H5, GC5PDTM, GC6A9H9, GC6CH5Q, GC5BYX0, GC5C09A, GC5C09H, GC5PDRD, GC2Q2V5, GC5PDPT, GC5Z406, GC6P4VN, GC6ATT8, GC5BYWV, GC6M6RT]) returned no results
08-21 22:38:15.287 30598-31703/cgeo.geocaching D/cgeo: [network-10] Retrieved 81 caches for tile (2126/1494), zoom=12
08-21 22:38:15.289 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.png?x=2125&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811895287
08-21 22:38:15.793 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] 200 (504 ms) GET https://tiles.geocaching.com/map.png?x=2125&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811895287 (http/1.1)
08-21 22:38:15.798 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] GET https://tiles.geocaching.com/map.info?x=2125&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811895287
08-21 22:38:16.519 30598-5111/cgeo.geocaching D/cgeo: [OkHttp] 200 (721 ms) GET https://tiles.geocaching.com/map.info?x=2125&y=1494&z=12&ep=1&app=cgeo&k=3kkw&st=YSWS34kUh5pxhp1-idIwHK1WbejINF--6OW87Yl6_6rJwDnvN2WH3DKeJ4lVPiPg4zH0skP9qZmigVgxZWL9orl_e3BKPAr45r8gaGyMwBh2MldpkQ5OCxTBsegDIiNa0&_=1471811895287 (http/1.1)
08-21 22:38:17.137 30598-31703/cgeo.geocaching D/cgeo: [network-10] DataStore.loadCaches([GC5C1PJ, GC2V0CH, GC4365K, GC5Z418, GC5Z510, GC290FW, GC697DQ, GC3KZC9, GC697DP, GC5V8D7, GC5Z40P, GC3JAMA, GC5QPBK, GC3GWK8, GC5QPA7, GC5Z41H, GC5V42B, GC3KXDE]) returned no results
08-21 22:38:17.158 30598-31703/cgeo.geocaching D/cgeo: [network-10] Retrieved 35 caches for tile (2125/1494), zoom=12
```

See also http://pastebin.com/vQCzCwvW

Cc @rsudev

**Comment by Lineflyer** [comment]
Interesting....so have been finally able to reproduce it?!

Symptoms for me have been the same. After rebooting my DSL it worked again (Change of IP?)

**Comment by kumy** [comment]
> However it "still" work from my desktop browser.

In fact, the map display correctly (via https://tiles.geocaching.com/map.png), but all other requests for map popup fail to load too (via https://tiles.geocaching.com/map.info)

**Comment by kumy** [comment]
I've forced all my traffic to pass via another route this restored the service, then back to my standard routing, and the service still works.

I suspect one of Groudspeak server behind a load balancer to be faulty... And not a bug with cgeo or rate limiting.

**Comment by Bananeweizen** [comment]
Can we specify it clearly enough to forward this issue to them?

**Comment by Lineflyer** [comment]
I remember that in the initial discussion with one member of their team we asked about that load sharing mechanism....and he told us to use another url than on the website (something like tile.geo.... instead of tile2.geo...). How is it handled on the website itself?

**Comment by Lineflyer** [comment]
As support mails and bad ratings keep coming I will add a temporary FAQ entry and a note on the main web page.

**Comment by kumy** [comment]
@Lineflyer Check lead to at least 4 urls `tiles01` to `tiles04` (it could be more) which all resolves to the same IP 63.251.163.200 (as for `tiles.geocaching.com` which we use.)

@Bananeweizen I'm not sure how can we do more test on our side. The LB should stick user on one server for a time, and can't do something to use another server (at least without changing client IP).

I wasn't able to provoke a `rate limit` by myself. So a problem with one of their server is my best clue.

Does anyone has another idea?

**Comment by kumy** [comment]
It could be nice to contact them with precise requests and time, so they can check their logs...

**Comment by Lineflyer** [comment]
Lets wait some more days to see if they also recognized the problem and are about to fix it.

Question:
I added a warning to www.cgeo.org and a [FAQ-entry](http://www.cgeo.org/faq.html#5914).
Should we additionally use the notification system to inform the users (and link to this FAQ entry).

Additionally:
If you have a better proposal for the wording of the FAQ entry...feel free to change it.

**Comment by Lineflyer** [comment]
FYI:
Notification posted after short agreement on IRC.

**Comment by kumy** [comment]
There seems to be some similar issues reported on groundspeak forum.
Main thread -> http://forums.groundspeak.com/GC/index.php?showtopic=340961

other references...
-> http://forums.groundspeak.com/GC/index.php?showtopic=340952
-> http://forums.groundspeak.com/GC/index.php?showtopic=340969

main forum page: http://forums.groundspeak.com/GC/index.php?s=b046b9510033f7615f8910ec5b62f691&showforum=139

Maybe the notification and FAQ entry should be updated accordingly.

**Comment by Lineflyer** [comment]
Interesting info.But what could we change in FAQ based on this info?Linking to that forum might confuse users as it deals only with browser issue (of course its the same technical issue but most users wouldnt understand the connection to cgeo). I would also avoid linking there in order not have cgeo discussions in the groundspeak forums,


Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: kumy <notifications@github.com> 
Datum: 22.08.2016  21:05  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu>, Mention <mention@noreply.github.com> 
Betreff: Re: [cgeo/cgeo] Live map is not loading any caches (#5914) 

There seems to be some similar issues reported on groundspeak forum.

Main thread -> http://forums.groundspeak.com/GC/index.php?showtopic=340961

other references...

-> http://forums.groundspeak.com/GC/index.php?showtopic=340952

-> http://forums.groundspeak.com/GC/index.php?showtopic=340969

main forum page: http://forums.groundspeak.com/GC/index.php?s=b046b9510033f7615f8910ec5b62f691&showforum=139

Maybe the notification and FAQ entry should be updated accordingly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kumy in #5914: There seems to be some similar issues reported on groundspeak forum.\r\nMain thread -\u003e http://forums.groundspeak.com/GC/index.php?showtopic=340961\r\n\r\nother references...\r\n-\u003e http://forums.groundspeak.com/GC/index.php?showtopic=340952\r\n-\u003e http://forums.groundspeak.com/GC/index.php?showtopic=340969\r\n\r\nmain forum page: http://forums.groundspeak.com/GC/index.php?s=b046b9510033f7615f8910ec5b62f691\u0026showforum=139\r\n\r\nMaybe the notification and FAQ entry should be updated accordingly."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/5914#issuecomment-241516416"}}}

**Comment by rsudev** [comment]
We could of course mention that all users of gc.com are randomly affected, but I think we can leave as it is for the moment.

**Comment by Lineflyer** [comment]
Mentioning that all users are affected is a good idea IMHO.Maybe you could add this to the FAQ entry as I am off for today.


Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: rsudev <notifications@github.com> 
Datum: 22.08.2016  21:41  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu>, Mention <mention@noreply.github.com> 
Betreff: Re: [cgeo/cgeo] Live map is not loading any caches (#5914) 

We could of course mention that all users of gc.com are randomly affected, but I think we can leave as it is for the moment.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rsudev in #5914: We could of course mention that all users of gc.com are randomly affected, but I think we can leave as it is for the moment."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/5914#issuecomment-241526136"}}}

**Comment by mucek4** [comment]
I still have contact to Raine shall I forward the thread to him?

**Comment by Lineflyer** [comment]
I think Raine is no longer working for them.

**Comment by rsudev** [comment]
Found some occurences of this in play console. Quite telling, if you ask me.
```
java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "tiles.geocaching.com": No address associated with hostname
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.singles.BlockingSingle.value(BlockingSingle.java:93)
	at cgeo.geocaching.connector.gc.Tile.requestMapInfo(Tile.java:237)
	at cgeo.geocaching.connector.gc.GCMap.searchByGeocodes(GCMap.java:68)
	at cgeo.geocaching.maps.CachesOverlay$RequestDetailsThread.run(CachesOverlay.java:295)
Caused by: java.net.UnknownHostException: Unable to resolve host "tiles.geocaching.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:394)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
	at java.net.InetAddress.getAllByName(InetAddress.java:214)
	at okhttp3.Dns$1.lookup(Dns.java:39)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllo
```

**Comment by kumy** [comment]
Lasted comment from an admin at GS forum

> Thanks for all the continued reports on this issue. We are still having trouble pinning down the cause and the reason why the issue is happening intermittently. We are aware that it's still occurring, though, and we are working to resolve it.

**Comment by Lineflyer** [comment]
No further occurences for me and also no new postings to the official gc-forum. 
Removing the notification for now...

**Comment by kumy** [comment]
From a Groudspeak admin:
> We believe that we finally identified the issue causing the unresponsive map problems. We released a fix on Friday. Are any of you still experiencing issues with clicking map pins? 

http://forums.groundspeak.com/GC/index.php?showtopic=340961&view=findpost&p=5609047

**Comment by kumy** [comment]
Some users on the GS forum report today that the "bug is back"

**Comment by kumy** [comment]
> All issues have been resolved and map usage has returned to normal. Thank you for your patience!

**Comment by Lineflyer** [comment]
Lets hope so.
I suggest to remove the warning from our homepage but keep the "current issues" in FAQ for some more days.

**Comment by Lineflyer** [comment]
No longer happening.
