### ISSUE TITLE
Maps.me interworking broken

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5916]
From FB and support mail:
Navigating using maps.me from cgeo is no longer working (no target shown in maps.me).

Happens if both apps are on latest available release, works again when downgrading maps.me to previous official version.

So either an API change on maps.me which we need to follow or simply a bug of maps.me.

**Comment by Lineflyer** [comment]
@Bananeweizen 
Is it possible that maps.me reverted their API change which you recently adapted c:geo to?

**Comment by dcj99b** [comment]
I'm ANNOYED YOU CLOSED THIS AS THE PREVIOUS SUPPORT ENTRY LACKED DETAIL.  I HAVE HELPED PEOPLE GET THINGS WORKING AGAIN.

**Comment by dcj99b** [comment]
Deleting Maps.me VERSION 6.3.6 and loading version 6.2.5-Web  using their downloadable .apk file restores full functionality.

**Comment by Lineflyer** [comment]
Hi @dcj99b 
The other issue was closed in order not to have a duplicate issue. As you can see above the duplicated issue is linked, so we won't miss any information.

**Comment by Lineflyer** [comment]
@Bananeweizen 
I guess maps.me reverted their change of callback format in the newest version.
So maybe we need just to revert this change: https://github.com/cgeo/cgeo/commit/147efba1615e704ef2c99bb6fb025635902e015a

**Comment by kumy** [comment]
@Lineflyer I'm not sure the commit you mention has something to do with our issue. It seems to be the way around. Click on a cache from Map.me (I didn't know it was possible).

**Comment by kumy** [comment]
The problem is on MWM side. I get the same problem with an old version of cgeo (tested with 2016.14.12).
Now let's find what has changed on their side... :(

**Comment by Lineflyer** [comment]
Not a problem on our side. Therefore closing. Still we might post updates here as soon as we know it is solved.

**Comment by Bananeweizen** [comment]
I assume it will work in 6.3.7, judging by this somewhat related comment: https://github.com/mapsme/api-android/issues/21#issuecomment-242118383

**Comment by Lineflyer** [comment]
Yes, I also received positive feedback on support mail. 6.3.7 is working again.
