### ISSUE TITLE
Livemap crash

### ISSUE THREAD

**Issue by jovars** [cgeo/cgeo#5919]
In rare cases starting the (live) map freezes or crashes c:geo permanently. This is a rare problem we were not yet able to debug.

If this happens to you please send us a log (as described in this FAQ).

##### Detailed steps causing the problem:
- Start c:geo on my xperia Z3 compact
- Enable live-map ( google-map ) 
-Zooming in or zooming out ( even occours when i turn the device from portrait to landscape )

##### Actual behavior after performing these steps:
- c:geo hangs. Must wait for "c:geo has stopped answering, do you want to close application", or I have to restart the device 

##### Version of c:geo used:
Version 2016-08-16 ( got much much worse after last upgrade ) 

##### Is the problem reproducible for you?
Will , it happens 8 times out of 10, geocaching is not so fun anymore... just getting frustrated over all device-restarts... 

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
-- System information ---
Device: D5503 (D5503, Sony)
Android version: 5.1.1
Android build: 14.6.A.1.236
Cgeo version: 2016.08.16
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: sv_SE
Log date format: 2016-08-23
Debug mode active: yes
Geocaching sites enabled:
   geocaching.com: Logged in (Inloggning OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by jovars** [comment]
Trying to log via aLogcat, but did not get a lot of info: 

Log from aLogcat

first try: 

--------- beginning of main
W/ResourceType( 7820): Found multiple library tables, ignoring...
I/Timeline( 7820): Timeline: Activity_idle id: android.os.BinderProxy@37ee0d76 time:115254


2nd try : 

--------- beginning of main
I/Timeline( 7820): Timeline: Activity_idle id: android.os.BinderProxy@37ee0d76 time:145161
I/Timeline( 7820): Timeline: Activity_idle id: android.os.BinderProxy@37ee0d76 time:177402

3rd try: 
--------- beginning of main
I( 7820) Timeline: Activity_idle id: android.os.BinderProxy@37ee0d76 time:346795  (Timeline)
W( 7820) Attempted to finish an input event but the input event receiver has already been disposed.  (InputEventReceiver)
--------- beginning of system
W( 7820) Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=56.0, y[0]=607.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=355073, downTime=355063, deviceId=6, source=0x1002 }  (ViewRootImpl)
W( 7820) Attempted to finish an input event but the input event receiver has already been disposed.  (InputEventReceiver)
I( 7820) Timeline: Activity_idle id: android.os.BinderProxy@37ee0d76 time:379279  (Timeline)
I( 7820) Timeline: Activity_idle id: android.os.BinderProxy@37ee0d76 time:393573  (Timeline)

**Comment by Lineflyer** [comment]
Please not that you have to have root access on your device and cgeo debug logging enabled in the settings.
One of these conditions seem to be missing.

**Comment by Lineflyer** [comment]
> Must wait for "c:geo has stopped answering, do you want to close application",

Do you get the option to send a crash report when this message is shown?
If yes, please do so each time it happens.

**Comment by Lineflyer** [comment]
@jovars 
Can you please test the newest beta version we published and check if it is working better?
You can receive it via normal Play update if you first register here:
http://goo.gl/g7NhzY

Alternatively you can directly download and install the app from: http://download.cgeo.org/cgeo-RC.apk

Your feedback is highly appreciated!

**Comment by Lineflyer** [comment]
@jovars Instead of the above mentioned beta/RC version you can also please retest with the latest official release 2016.08.27

**Comment by jovars** [comment]
@Lineflyer : 
I have tried the cgeo-RC.apk during this weekend, and I have had no crashes, so it seems to be working much better now, thanks!

**Comment by rsudev** [comment]
Thanks for the feedback!
