### ISSUE TITLE
GPX format issue cgeo -> Garmin etrex 10

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5920]
From support mail:

>Hello,
>
>I think there are two problems when generating gpx files with c:geo.
>In the GPS Garmin Etrex 10 the difficulty and terrain levels appear as in the image attached (GPX from CGeo.jpg), and there are no smileys in the logs.
>
>I modified the GPX file with a text editor and then they appear normally. (see attachement GPX modified manually.jpg)
>
>In the GPX files generated by Geocaching.com's Pocket Queries the markups <groundspeak:difficulty> and <groundspeak:terrain> are like this :
>
```
<groundspeak:difficulty>1</groundspeak:difficulty>
```
>and not
```
<groundspeak:difficulty>1.0</groundspeak:difficulty>
```
>and the value of the markup <groundspeak:type> is with the first letter uppercase like this
>```
<groundspeak:type>Found it</groundspeak:type> or <groundspeak:type>Didn't find it</groundspeak:type>
```
>instead of
```
<groundspeak:type>found it</groundspeak:type> or <groundspeak:type>didn't find it</groundspeak:type>
```

**Comment by SammysHP** [comment]
What is with the second issue?

**Comment by Bananeweizen** [comment]
As proven with this test https://github.com/cgeo/cgeo/commit/d7a2b965b60104c259584c6a91b91f0130bc3b5d#diff-102599b870a0d15634a96ca211cf225bR152 it works fine. Was fixed some time before.
