### ISSUE TITLE
Execution failed for task ':main:verifyCgeoKeys'. > You must provide keys in main/res/values/keys.xml for cgeo to compile successfully. You can copy from main/templates/keys.xml and just add the necessary values.

### ISSUE THREAD

**Issue by EeLingChow** [cgeo/cgeo#5923]
##### Detailed steps causing the problem:
- Step 1
- Step 2
- ...

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

**Comment by UniQP** [comment]
> You must provide keys in main/res/values/keys.xml for cgeo to compile successfully.

Please do so. See https://github.com/cgeo/cgeo/blob/master/README.md#api-keys for details.

**Comment by SammysHP** [comment]
Just read the error message, it tells you the reason and what you can do to fix it.
