### ISSUE TITLE
auto accept android licenses

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5925]
The most recent beta releases of the android tooling require to accept licenses for the SDK components even on build servers. I've implemented this by our build script automatically writing the necessary file, see http://stackoverflow.com/a/38381577/44089

That works. However, I was wondering if other developers would prefer this to be part of our gradle script directly, to make it work everywhere, not only on CI? Might be more smooth, on the other hand I'm a bit hesistant to accept licenses on behalf of every user of our gradle script.

**Comment by rsudev** [comment]
I would prefer to have to accept those licenses manually/personally.
