### ISSUE TITLE
Need graphics for developer page

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5928]
I've enabled a developer page for the team in Google Play. You can see the web version here: https://play.google.com/store/apps/dev?id=7945466068179931672. This should also be reflected after a day in the play store app.

Obviously this needs a better header image, since I just took the (old) app header image and resized it. Can someone provide a good 4096 * 2304 image representing the team (or the app)? See https://support.google.com/googleplay/android-developer/answer/6226441 for details.

**Comment by kumy** [comment]
@Bananeweizen I feel the actual picture is quiet blurry. Please find attached a temporary background image which is less pixelized than the actual one, so we can wait for a nice one from someone else (maybe from @brainscript ;) )!
![back](https://cloud.githubusercontent.com/assets/176794/18065979/a16d0758-6e36-11e6-85ce-47d5c55118fd.png)

**Comment by brainscript** [comment]
@Bananeweizen @kumy I'd be glad to help, but I have no clue how a Google Play team page should look like/normally looks like. Could you send me an example of a (good looking) team page?

**Comment by kumy** [comment]
I must admit, I have no idea of a "good dev page". Maybe browsing the Play Store to get some idea...

On August 30, 2016 8:22:31 AM GMT+02:00, brainscript <notifications@github.com> wrote:
>@Bananeweizen @kumy I'd be glad to help, but I have no clue how a
>Google Play team page should look like/normally looks like. Could you
>send me an example of a (good looking) team page?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5928#issuecomment-243344354

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Bananeweizen** [comment]
@brainscript Meanwhile it is live in the Google Play App. Just open the cgeo page in the Google Play app and scroll down below the comments. There you see a new section "c:geo team" with some background image (which is the above mentioned one). And clicking the button leads to a page with more space essentially showing the same.

You can do the same for many other popular apps, to see _their_ developer pages.

**Comment by Bananeweizen** [comment]
@kumy Your image is not big enough. The app store requires the above mentioned dimensions. And I don't want to make it blurry again by enlarging your image myself. :)

**Comment by kumy** [comment]
@Bananeweizen I thought the dimensions where recommended not mandatory. I can't produce a larger image with my tablet (maybe an emulator would help). Let's wait for @brainscript work :)

**Comment by brainscript** [comment]
@kumy I finally came up with this design (It looks way better if you look at it in full size):
![c geo-banner](https://cloud.githubusercontent.com/assets/8706734/18161105/c22d9b96-7030-11e6-8572-9271cf953f9f.png)
## Sources
[The font I used for "c:geo"](https://www.fontsquirrel.com/fonts/cantarella)
[The font I used for "Geocaching for Android"](http://www.fontsc.com/font/advent-pro)
[The background image](https://unsplash.com/@aleskrivec?photo=OmelL9tVVno)
[The screenshot](http://www.cgeo.org/images/screenshots/2_thumb.jpg)

If you want me to use a **high-res screenshot** please send me one (uncompressed and with English language settings showing similar content -> map with caches).
Feel free to leave any suggestions. :cat:

**Comment by kumy** [comment]
@brainscript I really like it! Thanks.

**Comment by brainscript** [comment]
Here's version 2:
![c geo-banner](https://cloud.githubusercontent.com/assets/8706734/18161729/80d78e38-7033-11e6-9fa1-10f338564e80.png)
I put the shine effect on top and fixed some gray borders
(caused by the screenshot that was cropped wrong).

**Comment by UniQP** [comment]
Yes, looks great (both version).

I personally don't like the "Geocaching for Android" font (especially the letters 'G', 'a', 'g' are hard to read). I would prefer the "c:geo" font (or some other font) instead.

**Comment by brainscript** [comment]
@UniQP I tried multiple fonts and this one fits perfect because when I use the "c:geo" font the text  goes over the trees of the background ... I hope you understand what I mean.

**Comment by brainscript** [comment]
Here's version 3:
![c geo-banner](https://cloud.githubusercontent.com/assets/8706734/18162882/890df3f8-7038-11e6-98ca-65ac3d6290d5.png)
I readded the phone shadow (forgot that in v3), made the "Geocaching ..." text more readable by making its color a bit darker, added a gradient to make the bottom darker and adjusted the phone's gradient to have less contrast (by changing the black color to some shade of gray).

**Comment by Lineflyer** [comment]
Nice work @brainscript 
My personal opinion: Really good, just the green text looks blurred / not sharp. Is that intentional?

Maybe we could use something similar or exactly this one also for the social networks to replace this one: https://www.facebook.com/android.geocaching/photos/a.10150686000550091.446649.297269860090/10152942996130091/?type=1&theater

**Comment by SammysHP** [comment]
@brainscript Can you try to remove the shadow from the text? Everything else looks great!

**Comment by brainscript** [comment]
@SammysHP I don't have to try. I can just do it. :smile: Here you go:
![c geo-banner](https://cloud.githubusercontent.com/assets/8706734/18184078/9bbc8028-7097-11e6-9bd9-1ddde41118c8.png)

**Comment by SammysHP** [comment]
Perfect!

**Comment by Lineflyer** [comment]
Is there any copyright for the background image? https://unsplash.com/photos/OmelL9tVVno

**Comment by brainscript** [comment]
@Lineflyer Unsplash is royalty free.
> Free (do whatever you want) high-resolution photos.

**Comment by SammysHP** [comment]
Looks like there is a layer style enabled for the background. Can you check to border?

**Comment by brainscript** [comment]
@SammysHP Do you mean that I used a simple blur filter?
Or that I added a gradient from the bottom upwards?
Or what do you mean? o.O

**Comment by SammysHP** [comment]
@brainscript There is a bright border, only a few pixels thick.

**Comment by brainscript** [comment]
This is an Inkscape bug. Maybe I can fix it somehow or I have to remove the border manually.

**Comment by Bananeweizen** [comment]
Uploaded the version with border for now. Will redo with new image.

**Comment by Lineflyer** [comment]
I did also upload the latest version to Google Play, FB and G+.

**Comment by brainscript** [comment]
@SammysHP I found the the bug report for this annoying bright border on Launchpad. They somehow released a fix in 2010 which obviously didn't solve the issue. I you have a UbuntuOne account please [follow the link](https://bugs.launchpad.net/inkscape/+bug/165529) and click on "Does this affect you?" and then on "Yes, it affects me". Thanks.

@Lineflyer Cool. I really appreciate the positive feedback the new banner received on Facebook. :smile:

**Comment by mucek4** [comment]
I like the image too, the only thing that bothers me is a tiny inconsistency between map of city and nature in background. But if we add a map of "middle of nowhere" it's not interesting :)

**Comment by akkatracker** [comment]
@mucek4 yeah I see what you are getting at but as you say a map of the middle of nowhere is boring. A background image of New York wouldn't capture the essence of geocaching either so I think it's good the way it is 😆

**Comment by Bananeweizen** [comment]
Closing since there have been no further requests regarding the image. Thanks @brainscript

**Comment by brainscript** [comment]
@Bananeweizen No problem. :smiley:
