### ISSUE TITLE
Mapsforge Offline germany.map missing some tiles for zoomlevel 5-7

### ISSUE THREAD

**Issue by k3b** [cgeo/cgeo#5930]
I am using the offlinemap germany.map from  http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/europe/ 

With zoomlevel 5-7 some tiles are left blank.

Cause: some map segments of germany.map are to large.

How to fix:

     ReadBuffer.setMaximumBufferSize(6500000);

For details see https://github.com/mapsforge/mapsforge/issues/868

I am using

* c:geo version 2016.08.16 (dowloaded via fdroid-app)
* Germany (offline)
* Android-4.4.2 (api-19) in german language

**Comment by Lineflyer** [comment]
@k3b Did you encounter this issue with the normal Mapsforage implementation in c:geo or (also) when using the Mapsforge beta map (Menu -> Settings -> System -> Mapsforge beta map)
@rsudev Did you read this?

**Comment by rsudev** [comment]
Have read this now. The linked issue states mapsforge 0.6.x, so it is the new map (but I didn't encounter it yet). I will cross-check and fix accordingly.

**Comment by k3b** [comment]
I discovered it with the non-beta but it was also visible with the beta version

**Comment by k3b** [comment]
I have just checked in my android-4.4 handset: 

* Version 201609.22
* these same issue with the old-mapsforge and with the new -mapsforge

**Comment by Bananeweizen** [comment]
however, I have no idea where to configure the buffer with the old mapsforge implementation.

**Comment by rsudev** [comment]
I browsed a little through the sources of the old mapsforge version and found there:
```
static final int MAXIMUM_BUFFER_SIZE = 2500000;
```
Should we really try to intervene here?

**Comment by Bananeweizen** [comment]
If the API was not made for changing the value in earlier versions, then I'm with you to not change anything there.
