### ISSUE TITLE
Install Java 8 on "master" slave

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5932]
Refer to IRC logs for details: http://irclogs.cgeo.org/?year=2016&month=8&day=30

By the way:
That reminds me of the plans to rent a server capable of all our needs (like Jenkins, Status, IRClogs and potentially even more (like Go4Cache)). What was the last status of that?

**Comment by mucek4** [comment]
Somewhere, somehow JAVA_HOME on Jenkins is still using java 1.7.0_04. Jenkins in current state (32 bit server, Jenkins 1.xxx) will have to be upgraded at some point. To restore building nightly builds I remove java 7 and linked on FS java 8 to java 7 folder. It would be nice if @Bananeweizen could check why we still use old java_home and where.

**Comment by kumy** [comment]
isn t it set on jenkins executor properties?

On August 31, 2016 2:40:06 PM GMT+02:00, mucek4 <notifications@github.com> wrote:
>Somewhere, somehow JAVA_HOME on Jenkins is still using java 1.7.0_04.
>Jenkins in current state (32 bit server, Jenkins 1.xxx) will have to be
>upgraded at some point. To restore building nightly builds I remove
>java 7 and linked on FS java 8 to java 7 folder. It would be nice if
>@Bananeweizen could check why we still use old java_home and where. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5932#issuecomment-243750978

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
@mucek4 I've looked at Jenkins `master executor` configuration, and it didn't contains any override of JAVA_HOME. However I imagine you could set it there, have a look at other [executor](http://ci.cgeo.org/computer/kumy-1/configure)s. Did you also updated java alternatives on your system? ex: `update-java-alternatives -l` ; `update-java-alternatives java-8-oracle`

**Comment by Lineflyer** [comment]
Its building now. Can we close this`?

**Comment by mucek4** [comment]
Technically yes, but it's a "temporary" hack. I would try to solve it so build would use Java 8 for real.

**Comment by samueltardieu** [comment]
The proper way to do it would be to remove this "special" master node. I have opened a new issue for this, assigned to you @mucek4 at the moment as some things need to be done on your side: #5944.

**Comment by samueltardieu** [comment]
Renaming so that its current purpose does not get lost.

**Comment by Lineflyer** [comment]
@mucek4 Still valid?

**Comment by Lineflyer** [comment]
@mucek4 Still valid?

**Comment by mucek4** [comment]
Java 8 already installed. Therefore closing
