### ISSUE TITLE
Support ignoring and watching caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5933]
It should be possible to watch or ignore OC cache listings with the same UI as for gc.com caches.
API: http://www.opencaching.de/okapi/services/caches/mark.html

**Comment by Bananeweizen** [comment]
Watching is possible, according to the code.

**Comment by rsudev** [comment]
And also according to the UI - was checking right now :)

**Comment by Bananeweizen** [comment]
And ignoring is possible in 5 minutes...
