### ISSUE TITLE
Czech opencaching?

### ISSUE THREAD

**Issue by frodeseverin** [cgeo/cgeo#5938]
Any chanse of adding Czech opencaching site to c:geo services?
http://opencaching.cz

**Comment by SammysHP** [comment]
AFAIK it does not use the OKAPI, so it is not possible.

**Comment by rsudev** [comment]
There seems to be some sort of API (http://opencaching.cz/articles.php?page=api) which seemingly allows to search for and download caches (looks sufficiently simple and clear, even though the description is only in czech). So some limited sort of integration seems technically possible. Whether this  is feasible is a different story of course.
Do you have any relations/contacts to opencaching.cz? Do you know whether the actually want us to integrate with them?

**Comment by SammysHP** [comment]
> 442 aktivních keší

And just three caches published this year.

**Comment by frodeseverin** [comment]
I am going to Prague this month.

I thought it used OKAPI, like the other opencaching sites. Then it would require minimal work, I suppose.

I think I shall drop this one for now. Perhaps I or someone else should contact them or opencaching network to advocate a standard API.

**Comment by Lineflyer** [comment]
> I think I shall drop this one for now. Perhaps I or someone else should contact them or opencaching network to advocate a standard API.

I agree, but I think this is an opencaching internal thing then.
Once they support OKAPI we might come back to this.
