### ISSUE TITLE
blurred text, new behaviour - or HW accel setting changed/reset by update

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#5939]
##### Detailed steps causing the problem:
- Open the map screen
- Use Google Map or Google Satellite
##### Actual behavior after performing these steps:

some or all the characters on the map scale indicator are blurred. (ie 300m)

same happens with some characters in cache description.
##### Expected behavior after performing these steps:

text is properly displayed on all OSM layers and on all offline maps.
##### Version of c:geo used:

2016.08.27
##### Is the problem reproducible for you?

Yes / always
##### System information:

```
Android 4.2.1
Hardware acceleration: enabled (default state)
```

HW accel was disabled by me 
##### Other comments and remarks:

**Important!!!** 
- My device has MTK CPU. I know there are some issues with MTK. 
- I use the Play-store distributed JIT build. (AFAIK the standard build)
- **Hardware acceleration setting was DISABLED** but somehow the _last c:geo update re-enabled it_ in the background.

It is very interesting to note that the scale indicator text is blurred only when using Google maps.
Sometimes the entire text is blurred, sometimes only some characters, I could not find a rule.

Also, the cache description text which is blurred (mainly text which has additional formatting, including <h1-h6> tags) is significantly less then it used to be in previous versions. 
In previous versions almost all <h1-h6> enclused text got blurred. Now this text is ok, but other text gets blurred, yet only one letter here, one letter there ... 

![img_6634](https://cloud.githubusercontent.com/assets/3382777/18162901/02a2ca2e-7041-11e6-9be3-fe058e28aa80.JPG)
^^^ cache description with <H1-H6> tags, no blurring
https://coord.info/GC32Q20

![img_6635](https://cloud.githubusercontent.com/assets/3382777/18162900/02a1f7b6-7041-11e6-8b28-37472fc02e35.JPG)
^^^ Google map

![img_6636](https://cloud.githubusercontent.com/assets/3382777/18162903/02a892b0-7041-11e6-8083-1fbf54f26de3.JPG)
^^^ OSM (online)

![img_6637](https://cloud.githubusercontent.com/assets/3382777/18162899/02a0867e-7041-11e6-86af-742934ed197a.JPG)
^^^ Mapsforge offline map

![img_6638](https://cloud.githubusercontent.com/assets/3382777/18162902/02a3c280-7041-11e6-819c-d38957a45ec4.JPG)
cache description text with blur
https://coord.info/GC53TJF

**Comment by Lineflyer** [comment]
The screenshot show the typical symptoms we have in c:geo ever since when using HW-acceleration on some devices.
Let me check if I can reproduce the reset of that setting during version upgrade.

**Comment by Lineflyer** [comment]
I retested this on some devices and the setting is always kept on version upgrade.
The only things I can imagine is, that:
- You upgraded your phone from a Android version 4.x to a newer version (as we disable it by default on low Android versiond below 4.something but enable it above)
- You reinstaled c:geo recently which makes the setting return to default.

@andrixnet 
Can you please give us the Device name according to the system information (first row). We might exclude it from HW-acceleration manually.

**Comment by andrixnet** [comment]
I have reinstalled c:geo after installing an optimized ROM, after my original one become troublesome. I was going from 4.1.2 to 4.2.1. I disabled then HW accel because I already knew the problems with the MTK CPU. 
However this was in early march. Since then c:geo got updated a few times.

There may also be other factors involved.
Question: if database is stored on sdcard (not internal memory), if .cgeo directory on sdcard gets deleted, could if lose this setting? (I had to change the card once).

You can exclude "P5_Quad" and "Q800" (same device, different ROMs). Manufacturer is [Allview](http://allview.ro/suport-si-service/update/telefoane/p5-quad.html)

**Comment by rsudev** [comment]
Regarding the flipping of the setting - we had some issues with it (#5582, #5598) and did a change to address some of the circumstances (seemingly different than yours) in f24b844. Perhaps this is a side-effect.
But settings are always stored in internal memory, regardless of the database position, so loosing the .cgeo-folder does not affect them.

**Comment by samueltardieu** [comment]
> Perhaps this is a side-effect.

Yes it is. The first upgrade after https://github.com/cgeo/cgeo/commit/f24b8447e944b4eb2d06c61c5e394902bc977bef might reset the default setting for the device.

@andrixnet Please provide the full system info from "About cgeo" so that we can put the exact strings in the code to disable hardware acceleration on this device.

**Comment by andrixnet** [comment]
```
--- System information ---
Device: Q800 (XOLO, XOLO)
Android version: 4.2.1
Android build: Q800
Cgeo version: 2016.10.13
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (manually changed)
System language: en_US
Log date format: Tue, Oct 25, 2016
Debug mode active: no
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / BASIC
Installed cgeo plugins: none
--- End of system information ---
```


Please also do it for device string P5_Quad.
Same hardware as Q800, different ROM. (Mine is Allview P5 Quad, known elsewhere as XOLO Q800)

**Comment by andrixnet** [comment]
--- System information ---
Device: Q800 (XOLO, XOLO)
Android version: 4.2.1
Android build: Q800
Cgeo version: 2016.10.13
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (manually changed)
System language: en_US
Log date format: Tue, Oct 25, 2016
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Installed cgeo plugins:  none
--- End of system information ---


Please also do it for device string P5_Quad.
Same hardware as Q800, different ROM. (Mine is Allview P5 Quad, known elsewhere as XOLO Q800)


On October 23, 2016 9:38:27 PM EEST, Samuel Tardieu <notifications@github.com> wrote:
>> Perhaps this is a side-effect.
>
>Yes it is. The first upgrade after
>https://github.com/cgeo/cgeo/commit/f24b8447e944b4eb2d06c61c5e394902bc977bef
>might reset the default setting for the device.
>
>@andrixnet Please provide the full system info from "About cgeo" so
>that we can put the exact strings in the code to disable hardware
>acceleration on this device.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/5939#issuecomment-255605758

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
