### ISSUE TITLE
feature request: option to allow caches in only 1 list

### ISSUE THREAD

**Issue by spinnekopje** [cgeo/cgeo#5943]
Feature request: add an option to bring back the old behaviour for the lists: each cache can only be part of 1 list. (an option, because I do understand the new way of handling lists and its advantages for lots of users.)

Use case:
create a pocket query (or run an existing one) and add the caches to a new list. A couple of days later you run the same PQ and also add those to a new list. So you get 2 lists with caches. Best after new caches became part of the new list, or other ones removed, etc.

- old behaviour:
The new list has the number of caches included in the PQ, the old one only lists those caches that aren't included anymore (disabled, found, new caches made them disappear etc.) It is easy to look at those and decide which ones to keep or remove.

- new behaviour:
You get 2 lists with no easy way of telling the difference. If you want to make sure you don't have caches on the device which are not useful anymore, you can only clear the old list. It is possible you clear caches that can still be useful for future trips.

In my case I create one using pocket query creator every couple of days, or before I go geocaching, with only the 1000 closest enabled caches that are active and haven't been found be me. With the old behaviour I ended up with up to 3-4 lists with caches, I only had to remove those I found or were disabled. I do not log with c:geo on the device I have with me on trips, so found caches are not marked as found on that device and it also doesn't have an internet connection during trips.

**Comment by samueltardieu** [comment]
Your usage is very specific. I don't think adding the complexity of another option in cgeo to handle this would be wise. Maybe this should be integrated with some pocket query tool instead.

I am against adding such an option.

**Comment by Bananeweizen** [comment]
I could rather imagine to have a command "Make list unique", which just removes the contained caches from all other list. That would fulfill the actual needs, should be simple to implement, and might be useful for others too.

**Comment by pstorch** [comment]
Maybe the already existing "move" feature can be used for that.

**Comment by Lineflyer** [comment]
I had a similar request from a user as he has special usecases to easily seperate e.g. archived caches no longer contained in a weekly imported GPX. Those remained on list A when he imported the GPX to list B as the remaining were pulled from list a to b.

**Comment by pstorch** [comment]
@Lineflyer what does he do the week after? Import to list C and check the remaining on list B, and so on? It's always interesting what different "ways of working" users evolve.

**Comment by Lineflyer** [comment]
@pstorch:

Here it is (@all sorry for no translation):

> Hi zusammen,
 
> danke für das letzte Release, das wieder eine Reihe schöne Neurungen mit sich brachte. 
Mit dem "New: Allow caches to be stored on more than one list" muss ich mich jedoch von einer lieb gewonnenen Gewohnheit verabschieden.
>
Ich habe für meine Homezone eine Liste "Home". In diese importiere ich in regelmäßigen Abständen meine 9 Homezone-Pocketquery-GPX-Dateien.
Da die GPX-Dateien keine archivierten Caches enthalten, werden diese in c:geo mit der Zeit in der Home-Liste in ihrem zuletzt importierten Zustand verstauben.
> 
Daher bin ich bisher ab und zu hin gegangen, und habe :
>
>  die GPX-Files in die Standardliste importiert.
        übrig blieben in der Home-Liste
            Archivierte Caches
            Aktuelle Caches am Rand der PocketQuery-Kreise, die aufgrund neuer Caches im Zentrum der Kreises nicht (mehr) zu den maximal 1000 pro Datei abgegebenen Caches gehörten.
            Sonstige Caches außerhalb der Pocket-Query Bereiche, die z.B. manuell in der Liste gespeichert wurden
>
>Um die nicht archivierten zu behalten habe ich in c:geo
>
>    abgelaufene Events entfernt
>    alle übrigen Caches aktualisiert (i.d.R. 50-100, also zeitlich akzeptabel) (*)
>    die archivierten gefiltert und gelöscht
>
>Übrig blieben aktualisierte aktive Caches, die ich natürlich behalten wollte.
Die frisch importierten Caches der Standardliste wurden dann als Letztes in die Home-Liste verschoben.
> 
>Mit dem neuen Feature können mehrere Listen Referenzen auf Caches enthalten, so das das Neu-Laden von Caches aus GPX in eine Liste B diese nicht mehr aus der Liste A entfernt, in der sie vorher standen.
> 
>Fällt Euch ein Weg / Workaround ein, mit dem ich auch zukünftig Karteileichen entdecken und ausmerzen kann, ohne meine 8000 Caches alle in c.geo aktualisieren zu müssen?
> 
> Falls nicht hätte ich zwei Ideen:
>
>   Einführen eines Filterkriteriums "zuletzt aktualisiert vor x Tagen/Wochen" o.ä., um diese dann gezielt zu aktualisieren als Ersatz für (*) oben oder
>        Auswahl 1 Tag, 3 Tage, 1 Woche, 2 Wochen, 1 Monat, ... oder Eingabefeld für Tage/Wochen
    Optionales Umschalten auf das alten Verhalten. D.h. löschen der in Liste A vorhandenen Referenz beim Laden des Caches in Liste B, statt eine zweite in Liste B zu ergänzen

**Comment by Lineflyer** [comment]
A perfect solution for this user would be to offer a `Pull from other lists` option during GPX import, but many other solution are also possible as discussed above.

**Comment by spinnekopje** [comment]
After reading the way the other user works I think something like "Make list unique" suggested above would certainly help us both and also make other use cases possible.
Basically we both do almost the same thing. Main difference is that he uses a 'home' list and I use the date/time that the pocket query creator app gives to the PQ by default.
