### ISSUE TITLE
Remove special "master" slave for Jenkins

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5944]
The following actions need to be performed before we can replace the special "master" slave with a regular docker slave:
- [ ] allow to upload the build result from anywhere to the website, or have it done via Jenkins if it can transfer files from a slave to the master and then upload the artifact to the website
- [ ] install file upload credentials to other slaves
- [ ] propagate master signing keys to other slaves

**Comment by mucek4** [comment]
Upload to webpage is currently done via FTP. FTP server is not opened to public network for obvious security reasons. If you have any better idea, please share it. 
Also, if you think master signing keys shall be public, then Yes, I can send them. Ok. It's not a problem of stealing them via special job on Jenkins too.

**Comment by samueltardieu** [comment]
ftps is ftp over ssl. `curl` supports file upload over ftps, and a ftps server can be opened to the public network (as a ssh server can), especially if the directory the user can upload to is restricted (as it should be).

Does your current ftp server support ftps?

**Comment by Lineflyer** [comment]
I don't see a real advantage in having the ability to build our nightlies, releases on all instances. Currently our CI builds are running on the slaves and master is taking care of building our productive builds and has access to upload the APK to the website.

I think we can close this issue unless someone sees the necessity to complete those tasks.
