### ISSUE TITLE
Samsung multi window no longer working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5946]
##### Detailed steps causing the problem:
- Use Samsung device support multi windows (e.g. all Galaxy S since S3)
- Try to start multi window mode while c:geo is running

##### Actual behavior after performing these steps:
"c:geo does not support multi window" (or similar) is displayed

##### Expected behavior after performing these steps:
Multi window mode should be started

##### Version of c:geo used:
2016.09.08-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Samsung Galaxy S7 

##### Other comments and remarks:
With the current RC version 2016.09.06-RC the multi window is working normally.

@Bananeweizen 
I suspect the recent changes to the manifest could be the cause (remove mandatory touchscreen)?

**Comment by Lineflyer** [comment]
Well, this might need more investigation because after coming back from the RC version to nightly it works again without a problem.
Setting to "Unverified" and "Fieldtest". Maybe a pure device problem.

**Comment by Bananeweizen** [comment]
Our implementation has not changed for 2 years:
        <meta-data
            android:name="com.sec.android.support.multiwindow"
            android:value="true" />

That's why I can't imagine something to be wrong on our side.

**Comment by Lineflyer** [comment]
I can confirm the bug seems to be my device not enabling the function randomly for some strange reason.
