### ISSUE TITLE
"Navigation (Driving/Walking/Bike/Transit)" use wrong destination

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#5953]
##### Detailed steps causing the problem:
- open a cache in lists or map
- tap on (menu >) navigation > Navigation (Driving/Walking/Bike/Transit)
- app Navigon Europe is starting
- Navigon wants to navigate to france instead of germany
- Each Menu entry (Driving/Walking/Bike/Transit) will navigate to a diffentent destination!

... a tap on "(menu >) navigation > Navigon" it will navigate to the right destination so it seems not to be an error in navigon
##### Actual behavior after performing these steps:

Navigation to the wrong destination
##### Expected behavior after performing these steps:

Navigation to the right destination
##### Version of c:geo used:

2016.09.06-RC
##### Is the problem reproducible for you?

Yes
##### System information:

Device: SM-G800F (kminiltexx, samsung)
Android version: 4.4.2
Android build: KOT49H.G800FXXU1ANJ2
Cgeo version: 2016.09.06-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 12/09/2016
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar
##### Other comments and remarks:

(I don't know how to set the right tags for this, isn't this possible for everyone?)

**Comment by Lineflyer** [comment]
I think Navigon does not fully support the content we deliver when selecting the general navigation menu entries (these are mainly designed for google maps). 
AFAIR this was the reason we established a dedicated Navigation menu for Navigon.
So I am not sure, it is a fault of c:geo.

**Comment by gcPhil** [comment]
Originally I was searching for the new possibility to select between navigation to cache or parking waypoint like mentioned in the release notes of Version 2016.08.16. Where can I find this? With "(menu >) navigation > Navigon" I get no selection.

**Comment by Lineflyer** [comment]
Can you provide an example GC-code?

**Comment by gcPhil** [comment]
Shure, GC6PA85 is one with parking coordinates.

I try to navigate to this event with "(menu >) navigation > Navigon" but I am not able to select between navigation to event-cache or parking waypoint then. Of course I could navigate to the parking coordinates by open the waipoint and select Navigon there but I guess that's not the new selection-support mentioned for Version 2016.08.1.

**Comment by Lineflyer** [comment]
You are right. It seems the dialog is only implemented for "Navigation*" menus but nothing else.

@Bananeweizen 
AFAIR you implemted the original feature. Could you include other navigation targets into this (like Navigon, maps.me, Google Maps Directions, Other external apps)?
Of couse not for all (IMHO it is useless for Compass, Radar, etc.)

**Comment by gcPhil** [comment]
Maybe it also make sense to rename the "Navigation *" menus to something like "Google Navigation *". I know that would a very long name but otherwise it seems to be dangerous if someone tries to use it with apps like Navigon and will end on the way to france instead of the next village.

**Comment by Lineflyer** [comment]
Navigon apps are no longer available

**Comment by gcPhil** [comment]
> Navigon apps are no longer available

The Navigon support had been integrated in c:geo's navigating-menu after your post from September 2016 - but the feature has already been deleted from c:geo again before some time. That's a bit frustrating for all people who still use the Navigon Apps. (If you once bought the App you can still download and use it. It seem to be still full functional for me. It's just not possible to buy the app.)
