### ISSUE TITLE
map popup sometimes shows incomplete or wrong information

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#5954]
##### Detailed steps causing the problem:
- open offline map OR map a list of stored caches (my list have around 3500 caches)
- zoom and scroll a bit (don't know if thats necessary to reproduce)
- tab on a random STORED cache (with floppy-icon) to watch its popup-info-box
##### Actual behavior after performing these steps:

a)
- sometimes (around every 5th try) "saving-"information of cache is missing
- There is written "Not availaible offline" and "Lists:" is empty
- (after closing box and open it again information is complete)

b)
- sometimes (every 15th try or something like that) the box shows complete information of an other far away stored cache 
- (after closing box and open them again cache is right)
##### Expected behavior after performing these steps:
- Show right and complete information
##### Version of c:geo used:

2016.09.06-RC
##### Is the problem reproducible for you?

"Yes" but not everytime and with the same caches. See comments and remarks below
##### System information:

Device: SM-G800F (kminiltexx, samsung)
Android version: 4.4.2
Android build: KOT49H.G800FXXU1ANJ2
Cgeo version: 2016.09.06-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 12/09/2016
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar
##### Other comments and remarks:

I guess its a problem related to performance. Most time when I notice this problem the app is "busy" with displaying caches and offline-map-tiles.

**Comment by Lineflyer** [comment]
@gcPhil This should not happen anymore with current master branch and also before that only under very special conditions.
Reopen if you have new clues on it.
