### ISSUE TITLE
Folder ".cgeo" keeps large amounts of data of deleted caches

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#5955]
##### Detailed steps causing the problem:
- use c:geo regularly with "many" caches (at once or over the time. I import and delete around 2500 caches/month but I always stay under 6000 on the device at the same time. Simetimes I also import log photos)
- delete every cache and every list (database contains no cache)
- just for sure: go to "settings > system > delete orphaned files"
- just for sure: wait four days because some data will be deleted only after three days
##### Actual behavior after performing these steps:
- the hidden folder ".cgeo" still contains many data
- in my case regularly over 4GB with many image-files and other data (maybe listings and stored waypoints?)
- I need to delete this folder by hand regularly so that my phone don't stop working because of small storage
- selecting "settings > system > Database location > on external storage" don't change anything, the large folder stays in the internal storage (I don't know if it should move?)
##### Expected behavior after performing these steps:

after deleting the caches in the app the folder should be empty or at least small
##### Version of c:geo used:

2016.09.06-RC (but the problem is there since long time)
##### Is the problem reproducible for you?

Yes!
##### System information:

Device: SM-G800F (kminiltexx, samsung)
Android version: 4.4.2
Android build: KOT49H.G800FXXU1ANJ2
Cgeo version: 2016.09.06-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 13/09/2016
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar
##### Other comments and remarks:

I mentioned this problem as a comment of an other bug before long time but I don't find it any more and nothing changed in the last years

**Comment by Lineflyer** [comment]
Might this be remainder of a previous installation?

**Comment by gcPhil** [comment]
No, I need to delete this folder by hand regularly once or twice a year so that my phone don't stop working because of small storage. The folder gets so big every time again.

**Comment by Lineflyer** [comment]
I tested exactly this some months ago without any finding.
Can you trace down the useless stored data to something common (e.g. all from one list, all fro
m on caching platform, etc.)?

Can you perhaps test it by storing a lot of caches in a fresh installation and afterwards deleting them, wait for >3 days and see whats remaining?

**Comment by gcPhil** [comment]
Yes, I will try this completely as soon as possible.

What I can can say today is that I use gc.com only. In ".cgeo" stays many folders which are named with gc-codes and with many image files (and others) inside. 

By the way: this three day rule is a strange solution when your smartphone gives you a massage that it can't work correct any more because of small storage after importing new caches.

**Comment by gcPhil** [comment]
I did the complete test in the meantime.
- preparation: first I deleted all caches, deinstalled the app and deleted the full .cgeo-folder
- I made a clean install and imported 1000 caches with images (after that ".cgeo" contained 1583 folders, 290,07 MB)
- I deleted all caches, deleted "orphaned files" and waited four days >> folder  contained 11 folders, 2,85 MB

**Comment by Lineflyer** [comment]
What is the content of these folders?

**Comment by gcPhil** [comment]
It's four gc-number-named folders with images inside, the folder "shared" and two files called "data" and "data-journal". Must also be sub-folders somewhere. I remember that some of the folder related caches was marked as found before, so maybe there is a relationship.

I am not sure if this can cause the large amount of "lost" data I noticed before but I have no other idea how to reproduce without month of using. 

Here are some Screenshots: https://www.dropbox.com/s/6bkvqstkgtc2eiv/Screenshots.zip?dl=0

**Comment by pstorch** [comment]
> I remember that some of the folder related caches was marked as found before, so maybe there is a relationship.

There is a rule in c:geo that Caches with offline logs are skipped from permanent removal:
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/storage/DataStore.java#L2474

**Comment by gcPhil** [comment]
> There is a rule in c:geo that Caches with offline logs are skipped from permanent removal

I see no good reason to keep found caches and all of their data (images, ...) forever. When I clear a cache from history and delete it from all list him I don't want him to stay on my device forever and let it stop working because of low storage some day. Remember: for me its regularly 3-4GB of data by this not deleted caches. **In my eyes this is a big mistake and should be changed qickly.**

**Comment by pstorch** [comment]
You have removed them from history, but not (explicitly) removed the offline log? I guess here is the problem. When a cache is removed from History, the offline log stays and prevents the cache from final removal. 
I think we should also delete the offline log, when the cache is removed from history. 
We also had the discussion to rename History to "Recent Logs" or so, to make it more clear. Then we would only have one remove action.

**Comment by gcPhil** [comment]
Yes, you are right, I just removed them from history. I can not imagine anybody is acting different because removing the offline-logs would mean very much work. you must do it separately for every cache in the moment and users can hardly know this rule and its consequences.

I can not overview all effects and say if its better to _delete the offline-logs with erasing history_ or to remove/bypass _skipping from permanent removal_. But the actual situation brings much 
unobserved problems for many users by creating large amounts of data.

**Comment by SammysHP** [comment]
You can remove all offline logs at once via the list menu.

**Comment by rsudev** [comment]
I for example act differently. I remove offline logs (after uploading field notes, logging online and updating stored caches), but not one-by-one, just using the menu-entry in the history.
While I understand that the current behaviour is a big issue for you (and I am also not too happy with it) it is not easy to just change. We have no good way to understand how many people might suffer by loosing data if we just change a behaviour which has been present for a long time (e.g. speaking of the three days).
Of course those don not come forward and voice there opinion, because they are happy.
What I right now think we might do to avoid such issues is, to make any caches that are stored, visible.
We could have a virtual list 'retained' or so, which lists those kept due to the three-days rule or due to user-data (maybe two lists). Than you can clear stuff explicitly from there (or wait the three days). What do you think?

**Comment by gcPhil** [comment]
@SammysHP OK, sorry I don't realised that. But its still not intuitive.

What you want is to simply delete the cache from the device after exporting field notes.
What you must do is to delete it from history, delete its offline log and delete it from all lists.
No user knows about that rules and the remaining data if one step is missing.

**Comment by pstorch** [comment]
I guess this "rule" was introduce to prevent a user from accidentally deleting his Logs. But currently the history is a bit confusing. See other Issues regarding history. 
In your described situation the caches are removed from history, but still have offline logs. So it is not visible anymore that the caches are kept. 
We could solve it in many ways. 
I think "remove from history" should either also delete offline logs or don't affect caches which have offline logs to prevent data loss and force the user to explicitly delete them separately.

**Comment by gcPhil** [comment]
I understand that people maybe get used to some side-effects like keeping their stored waypoints forever and that it is very difficult to change such things. But at the point when cgeo is stopping the phone working it is a big bug.

What I would like is a menu-entry in history where I can do all three deletions at one. Detete Logs, History-Entry and Stored Cache (immediately or if you prefer after three days). Maybe there should be a new name for that funktion so people understand that something reacts different than before.

**Comment by Lineflyer** [comment]
My few cents:
Couldnt we change the "Delete orphaned files" function in that way that those offline logged caches no longer saved and removed from history get revycled?

**Comment by pstorch** [comment]
@Lineflyer that is one possibility. From my point of view If the user doesn't have the cache on any list, we can assume it can be safely deleted.
And we should "cleanup" the History view as well. I think one remove action is enough here. Maybe with a warning about available offline logs, but we don't want more dialogs, right?

**Comment by gcPhil** [comment]
@pstorch Could you please explain what changed with your commit? (Sorry, I am not able to understand Code.)

@rsudev I tried to act the same way you discribed but that is not possible:
> I for example act differently. I remove offline logs (after uploading field notes, logging online and updating stored caches), but not one-by-one, just using the menu-entry in the history.
- There is no deleting menu-entry in history (at least since 2016.08.14)
- Also deleting caches one-by-one don't work (see #5949)
- In the latest RC (2016.11.21-RC) it also changed that history is getting cleared when you delete offline logs. So there is no easy possibility to delete them after deleting logs. The logs are still in the lists and even appear to be unfound until all caches getting updated.
- Only after updating all caches its possible to filter and delete them. If you prefer not to update large amounts of caches automatic but with a new PQ-import it's even more complicated to filter such caches (see #5959)

**Comment by pstorch** [comment]
@gcPhil now caches which have an offline log are also shown in history. These offline logs are preventing c:geo from deleting these caches.
You are now able to explicitly delete these offline logs by `Clear offline logs`. After that theses caches should also be deleted (incl. files in `.cgeo` directory) by the automatic housekeeping routing of c:geo (latest after 3 days).

**Comment by gcPhil** [comment]
@pstorch thank you for complaining. That should solve the issue of undeleted data (I will test it later). But there is an other little problem now: like I wrote above since 2016.11.21-RC  "Clear offline logs" is completely clearing the history and it became more complicated to really delete the caches. They remain in the lists until they get deleted. And without offline logs it's not easy to filter them for deleting.

In my opinion the best solution whould be to keep them in the history again (clear logs not history) and restore the possibility to delete all caches in history (from all lists, see #5949). 

An alternative would be to also delete caches with "Clear offline logs" but that whould be a big change and I guess the command must be renamed then.

**Comment by pstorch** [comment]
@gcPhil you are right, some of the problems where also addressed in #6181. I hope I could deliver a patch to remove some of the confusions in #6184. 
Have you in the meantime tested the remaining issue with not deleting the files? If everthing from History is gone, the corresponding files in `.cgeo` should also go after 3 days.

**Comment by gcPhil** [comment]
Sorry, I was not able to test for remaining files again until now because I had much issues with a ROM-update on my phone the last weeks.

I just had deleted all caches in c:geo before a moment and will report in three days if the c:geo folder is empty this time. 

I am not sure if #6184 will help with the new issues I described above. I will have a closer look at Sunday.

**Comment by gcPhil** [comment]
On my last test I had no more remaining data in the c:geo-folder. (Only a small subfolder of shared smily-images but that is ok.)

I will also keep a look to the folder in the future to be sure I don't oversaw any constellation that still cause lost folders there.

There is still the problem that "Clear-offline-logs" now clears up the History and makes it impossible to filter or easily delete that caches. (They are no longer marked as found but stays in the lists between unfound caches).

**Comment by Lineflyer** [comment]
Thanks @gcphil for your feedback.
The issues regarding the history are tracked in other issues already...we have recent activity there and are aware of these kinds of problems.

Let me close here for now unless you detect new problems at at later point of time.
