### ISSUE TITLE
Provide a filter for caches stored before >6 days

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#5959]
##### Feature Request:

Please provide a filter for caches stored before more than 6 days

I use a list in that I import my homezone-PQ every week. For not loosing downloaded images, markings of caches with deposited final-coordinates and other data which is not included in GC.com-PQs I don't delete the old caches before and just import the new PQ in the same List. A "problem" is that every old cache in the list that got archived or is not included in the new PQ by any other reason will not get updatet.

To filter that archived caches and delete it from my device I use the sort function in the moment. I have to sort by "Data stored on device", open a cache in the list, watch its storage date, close it, scroll down, open an other one and so on to find the fist new imported cache in the list. Than I can start select mode and select all old caches by hand to refresh or delete them.

A filter would make that so much easier! It could be something like
Filter by > Status > "Stored before >6 days"

I guess this would be helpful for many users!

**Comment by ControlTheBit** [comment]
OR it would be great to use the PQ as an "Update" instead of an "Import".

Some function like "Update caches in list", which updates existing caches and adds new ones. It should then ask you what to do with the ones that were not updated. E.g. "There are 12 caches in the list which were not updated. Do you want to keep them?" Yes/No

**Comment by gcPhil** [comment]
Yes, that would be a nice other solution for my problem. Maybe such a funktion could better be called "Update by GPX" or something like that so that it's clear that it will not do an (online)-refresh of the data.

**Comment by Lineflyer** [comment]
See #7498
