### ISSUE TITLE
Add online mode to the new Mapsforge map

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5960]
We should promote the new Mapsforge map out of beta. To do so, it needs to support online maps.

**Comment by Lineflyer** [comment]
You mean adding the ability to use the "normal" Google and OSM:Online or somethign else?

**Comment by samueltardieu** [comment]
The ability to use a tile server so that we can remove the older Mapsforge code.

**Comment by andrixnet** [comment]
:+1:

**Comment by rsudev** [comment]
While experimenting with the possible implementation, I cam across this:
http://wiki.openstreetmap.org/wiki/Tile_usage_policy
I am not sure if adding should just add online tiles again - but of course the same issue applies to the existing mapsforge implementation.

**Comment by andrixnet** [comment]
Has anyone encoutered this limit using c:geo and the existing implementation? 
I've only seen it with mass tile downloaders like mobac.

**Comment by rsudev** [comment]
I personally never use online tiles (besides testing), so I cannot really judge. But regardless whether they enforce anything they place some requirements (besides negotiating also some form of attribution has to be done) which might be legally binding.
I don't want to reject this proposal based on the article, but get some comments/viewpoints.

**Comment by SammysHP** [comment]
I haven't used online tiles for some years, but I'm working a lot with and for OpenStreetMap. An attribution is absolutely necessary (© OpenStreetMap Contributors with link to the legal page). Regarding tile limit: if it's noticeable, they'll block it. With 6000 users at the same time (and not all of them use online tiles at the same time) it should be fine. We could also think about forwarding some donations to OpenStreetMap and/or add them to our recommended apps section with a hint for donations.

**Comment by andrixnet** [comment]
- Not all users will have an offline map. (since it requires additional downloads and settings)
- IMO a lot of users will use online tiles. Google Maps and OSM.
- Some places have more detail on OSM the GoogleMaps
- Sometimes will use Google Satellite because it gives more relevant info (not strictly mapwise)

I don't know what usage metrics you have about this, but I am sharing my personal experience along with friends when we searched together.
-

**Comment by andrixnet** [comment]
Also Google data requires copyright notice to be displayed.

**Comment by kumy** [comment]
This remind me the feature hidden when you tap on the map on the bottom of cache details page. There you have multiple maps around the cache from different providers, at multiple zoom factors.
