### ISSUE TITLE
Support new map-themes with overlays/stylemenus in new map

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#5964]
I had a look on the map-beta and I noticed that it supports new mapsforge maps but until now not overlays and stylemenus which came with rendertheme-V4 / mapsforge 0.5. With rendertheme-V4 one map-theme-file can include multiple different themes with the possibility to be switched on and off.

It's already used by map-providers like OpenAndroMaps which latest renderthemes (Elevate 3&4  published from March 2016) can not be used in c:geo any more because you would see all included themes on the map at the same time.

Here are more Informations about overlays and stylemenus in rendertheme-V4:
https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#stylemenus

I have no idea if its already planed but if not please contemplate to support overlays/stylemenus and keep newer map-themes usable.

**Comment by Lineflyer** [comment]
I figured out the same today while installing maps and themes for my planned scandinavia trip.
In fact the "Elevate" theme of openandromaps is really cool but you can't use the style settings thus its overcrowded.
@rsudev Are you planning to include style selection support?

**Comment by SwissPoPo** [comment]
This issue is still a huge drawback with the new map implementation in c:geo.
The theme layers overcrowd the map if they are not handled correctly. 

As first step c:geo should only show the default layer as defined in the theme.

As second step c:geo should expand the map menu to include switching of styles and layers (as defined in the theme).

**Comment by Lineflyer** [comment]
Without having a detailed idea about the technical implementation, would you consider the current realization (show all layers) as a bug?

**Comment by SammysHP** [comment]
@Lineflyer 
With the possibility of enabling/disabling individual map layers some maps got more complex. If you enable everything, the map becomes heavily overloaded in some situations.

**Comment by SwissPoPo** [comment]
In the past theme authors have created different themes files for different topics like hiking or cycling.
Today they create ONE theme file but with different "styles" for hiking and cycling. And in addition, selectable options.
So, you have hiking and cycling route in the same theme, but you should not show these at the same time. The map becomes overloaded.

It is an unfinished implementation and makes the map unusable. Yes, you can call this a bug.

**Comment by rsudev** [comment]
I have a first very rough implementation locally, mainly based on the sample code the mapsforge team provides. Integrated into the map menu, this is how it would look like:

![screenshot_20181001-210834](https://user-images.githubusercontent.com/780005/46310297-4614e500-c5bf-11e8-91bf-0007e1a00d3a.png)

This is then the content, that mainly comes from the map theme (including localisation). In this case the elevate theme from openandromaps:

![screenshot_20181001-210854](https://user-images.githubusercontent.com/780005/46310377-7197cf80-c5bf-11e8-8e11-da69dc0b5892.png)
![screenshot_20181001-210903](https://user-images.githubusercontent.com/780005/46310379-73fa2980-c5bf-11e8-9f39-de2c752f7aab.png)

Comments?
Should I try to get it into master with this UI?

**Comment by Lineflyer** [comment]
Thanks for the reminder @rsudev 

IMHO the suggested UI is pretty straight forward and the entry point is where I would expect it.
I thought about having it under Main Menu - Settings - Map instead, but most probably users would like to see the result of their changes immediately, which is easier to achieve by changing it directly from the map menu.

So it looks fine to me. I cannot judge the naming of the options as I do not know the categories, which are defined for the themes.

**Comment by rsudev** [comment]
All the namings beneath 'Theme options' and 'Map style' come out of the theme file, so no way to influence that.
So I will give it another code review from my side (unless someone else chimes in) and than merge it.

**Comment by moving-bits** [comment]
@rsudev: This is COOL! Very useful feature, thank you!

**Comment by gcPhil** [comment]
I really like this implementation of theme styles. It is exactly what I thought about when I had once written the feature request. It makes c:geo usable with modern maps (and in the map menu it is at the right place for an easy switch).

When can this change be available in a public beta or final release? (Sorry for asking, I am not familiar with your release procedure.)

**Comment by Lineflyer** [comment]
Well, we are missing some mandatory changes to be ready for release.
Thus I cannot give a schedule,  however due to the nature of needed changes this change will most probably be in the next new version.

BTW:
@rsudev Can you upload strings to Crowdin? The commit contains quite some new strings.

**Comment by rsudev** [comment]
Oh yes, thanks for reminding. Crowdin is also something that needs a slight clean up. Unfortunately did the translation branches feature not work as well as expected.
