### ISSUE TITLE
Include information on granted/denied permissions in system information

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5971]
This is a feature requested by @Lineflyer.

**Comment by samueltardieu** [comment]
@Lineflyer Please test and advise whether you want it in the `release` branch or not.

**Comment by samueltardieu** [comment]
@rsudev Can you also confirm that you see the DENIED permission?

**Comment by rsudev** [comment]
I am on the road right now so to speak. I will cross-check as soon as possible.

**Comment by Lineflyer** [comment]
@samueltardieu Will test this as soon as the nightlies are building again.

**Comment by Bananeweizen** [comment]
For me this doesn't work. I took a Nougat emulator, installed cgeo, revoked both the fine location and disk permission in global app settings and started cgeo. Shows "granted", expected "denied".

**Comment by samueltardieu** [comment]
It doesn't for me either I should add. We should test this again when we increase the API.

**Comment by Lineflyer** [comment]
For me neither on Android 6. Also after removing permissions both show as granted.

**Comment by Lineflyer** [comment]
For me it looks like `Manifest.permission.ACCESS_FINE_LOCATION` and `Manifest.permission.WRITE_EXTERNAL_STORAGE` return true if we request those permissions (which we do) but do not carry the information, whether the user granted the information.

**Comment by Lineflyer** [comment]
In system informations sent in by users on support I have seen that these fields are working. No idea what went wrong here.
