### ISSUE TITLE
Cannot login Android app (beta)

### ISSUE THREAD

**Issue by KoalaBear84** [cgeo/cgeo#5974]
##### Detailed steps causing the problem:
- Changed password a week ago
- Get message in app that it cannot login anymore, correct
- Enter new credentials, cannot login
- Tried to make it 4 characters shorter, from 20 to 16, nope
- Tried 12 and 8 characters, no. Changed password back to old password, still no
- Cleared cache and data, still not
- Uninstalled app, reinstalled, unfortunately still cannot login

New issue, or known issue lately?

Using Samsung S6

##### Actual behavior after performing these steps:

- Cannot login

##### Expected behavior after performing these steps:

- Working login

##### Version of c:geo used:

2016.09.06-RC

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-G920F (zerofltexx, samsung)
Android version: 6.0.1
Android build: MMB29K.G920FXXU4DPHF
Cgeo version: 2016.09.06-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Log date format: 9/17/16
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
```

Funny that it says login OK

##### Other comments and remarks:

If you need any more info, let me know!

**Comment by KoalaBear84** [comment]
I removed myself from the beta program, uninstall and reinstalled and that works!

Now trying again to join beta and see if it is a problem.

**Comment by KoalaBear84** [comment]
This is very strange. Rejoined beta program. Reinstalled. Everything working again. Changed password again. Get message that it cannot login. Filled in new password, working!

And no, it wasn't a user input problem. Password is stored in KeePass and using app on Android to copy it to clipboard and paste it. So no manual input.

Strange, but solved! If anyone have this problem:
- Leave beta program
- Maybe optional: uninstall app
- Rejoin beta program
- Fill in credentials

**Comment by samueltardieu** [comment]
Your proposed solution looks like black magic, I do not advise to follow it blindly.

The user input problem may have been on the username instead of the password for example. Did you by chance retrieve and save any log from the problematic login sessions?

**Comment by KoalaBear84** [comment]
I don't think I have that. Didn't know there were logs. It will be removed when you uninstall the app I think?

**Comment by KoalaBear84** [comment]
And for the username part, also came from KeePass, unfortunately not 100% sure.
