### ISSUE TITLE
Nightly not building since 15.09.16

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5977]
CI says:
```
00:30:26  > You have not accepted the license agreements of the following SDK components:
00:30:26    [Android SDK Platform 23].
00:30:26    Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
00:30:26    Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by samueltardieu** [comment]
First assigning to @Bananeweizen as he put the approval system in place.

**Comment by mucek4** [comment]
I have seen it but I only came home tomorrow evening. Will take a look.

**Comment by Bananeweizen** [comment]
I know how to fix the issue but I can't. When opening the configuration of the nightly job, Jenkins crashes. @mucek4 Please update the plugins on Jenkins.

Afterwards, these 3 lines need to be added to the nightly job, somewhere before starting gradle.
```
# accept Android licenses. these are the MD5 hashes of the license texts, so they may need to be adapted on license changes
mkdir "/opt/android-sdk-linux/licenses" || true
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "/opt/android-sdk-linux/licenses/android-sdk-license"
```
Unrelated to this license issue, the master also has some broken files in the SDK: 
```
Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/opt/android-sdk-linux/add-ons/addon-google_apis-google-19-1' (Expected '/opt/android-sdk-linux/add-ons/addon-google_apis-google-19')
00:48.841  Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/opt/android-sdk-linux/add-ons/addon-google_apis-google-19-1' (Expected '/opt/android-sdk-linux/add-ons/addon-google_apis-google-19')
00:49.370  Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/opt/android-sdk-linux/add-ons/addon-google_apis-google-19-1' (Expected '/opt/android-sdk-linux/add-ons/addon-google_apis-google-19')
```
I've seen the same issue on my local machine after an installation of the SDK manager failed. For me it was the most easy to delete the related add-ons on disk and then to re-install them.

**Comment by mucek4** [comment]
I had to disable "Flexible Publish Plugin" in order to get to Nightly config. I can't get to plugins config as Jenkins still crashes. I'll try to update Jenkins

**Comment by Bananeweizen** [comment]
Fixed with the steps taken by @mucek4 and the accepting of licenses. If those licenses change in the future, we have to update this job and the shared build script on Jenkins separately (i.e. we have code duplication here).
