### ISSUE TITLE
Create CNAME for Crowdin page

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5982]
Just a cosmetical thing:
According to the Crowdin project settings [here](https://crowdin.com/project/cgeo/settings#general) we can use our own domain/subdomain to redirect/point to crowdin.
So we could use e.g. translate.cgeo.org to refer users to our Crowdin page if I understand this correctly. Would IMHO be a nice shortcut which can easily be recognized as I always struggle to remember the correct URL refering to our Crowdin project.

**Comment by mucek4** [comment]
Will take a look

**Comment by mucek4** [comment]
I can't see the settings page. Can any of @Lineflyer @Bananeweizen @rsudev or @samueltardieu add me to managers :)

**Comment by rsudev** [comment]
@mucek4 I have made you a manager.

**Comment by mucek4** [comment]
http://translate.cgeo.org/

**Comment by SammysHP** [comment]
Works!
