### ISSUE TITLE
Dont show final marker (on map) for final waypoints without coords

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5983]
##### Detailed steps causing the problem:
- Open GC4C67W
- It has a final waypoint without valid coords (as the owner probably decided to make it visible but hide its coords)
- Store the cache
- Open the (live) map of that region
##### Actual behavior after performing these steps:

The cache is shown with the final marker on the map
##### Expected behavior after performing these steps:

The final marker should not be shown, as the final waypoint has no valid coords
##### Version of c:geo used:

2016.08.27
##### Is the problem reproducible for you?

Yes
##### Other comments and remarks:

Up to approx. March 2016 this was implemented as suggested but changed thereafter.
Users are complaining as they are no longer able to differentiate between real modified mystery final coords and those "dummy" caches.

I have in mind, that I already have seen such an issue but can't find it.

**Comment by UniQP** [comment]
@Lineflyer Is this issue still reproducable for you? I cannot reproduce it on master and market_20160827.

**Comment by Lineflyer** [comment]
You are right. I cannot reproduce as well (both with mapsforge beta and old google maps).
Might have been solved implicitly while remodelling the waypoint storage.
