### ISSUE TITLE
Remove store offline menu

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5985]
I was just approached with the following request: In the logging activity menu the menu items for saving the log and for deleting the log are directly besides each other, therefore leading to frustrating when hitting the deletion menu item unintendedly.

I'll add undo to the log deletion operation, to take the pressure out of this.

I still suggest to actually remove the "store log offline" item, since we store the log anyway when exiting the activity. Thoughts on that?

**Comment by Lineflyer** [comment]
I do agree to remove that option.
I would even go one step further and in the same step implement that the "one-click offline log" option is always shown and no longer depending on whether "offline logging" is active in the setting. 
That would enable a faster way to produce a field note while also it requires one less option in the settings. 
AFAIR I opened an issue for that already.

**Comment by Lineflyer** [comment]
Found it: #3856
