### ISSUE TITLE
Graphical Glitch: Actions-Popup opens partially outside of the visible area depending on the cache name length

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#5988]
##### Detailed steps causing the problem:

Here is what I did:
1. Enable "Offline Logging" in the settings (problem also reproducible without this settings, but the problem can be seen better when this is enabled)
2. Open the Live View
3. Click on a cache
4. Click the three dots in the top right corner of the cache
5. Have a good look at the action-popup

(I didn't try this in landscape mode yet)
##### Actual behavior after performing these steps:

Depending on the length of the cache name, the cache popup width is different. And that difference influences the position of the action-popup that comes up when you touch the three tiny dots. (See screenshots)
##### Expected behavior after performing these steps:

The Actions-popup open always in the same spot and all entries are clearly visible and not cut off
##### Version of c:geo used:

2016.08.27
##### Is the problem reproducible for you?

Yes
##### System information:

```
--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 6.0.1
Android build: MOB31E
Cgeo version: 2016.08.27
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Log date format: 9/23/16
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---
```
##### Other comments and remarks:

(Don't worry, the map in the background is not broken, it was just still loading)

Screenshot with a long cache name:
![screenshot_20160923-090557](https://cloud.githubusercontent.com/assets/9163917/18777217/3e58cde6-816e-11e6-99cf-1c8f047c85eb.png)

Screenshot with a short cache name:
![screenshot_20160923-090549 copy](https://cloud.githubusercontent.com/assets/9163917/18777288/86bee0c0-816e-11e6-89b7-b888d9236f55.png)

**Comment by ControlTheBit** [comment]
Related to #3932

**Comment by Lineflyer** [comment]
For me this is fixed, probably due to the recent changes in minsdk, design and support library versions.
