### ISSUE TITLE
"Invite friends" in cache menu

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5991]
I just noticed that the menu of the cache details includes the "invite friends" feature. Is that intended? The menu has already many entries and IMHO the entry in the main menu is enough.

**Comment by Bananeweizen** [comment]
This is intended. Just did not implement the deep linking to the cache itself. The intention is to have a deep link to the cache details from the message.

**Comment by Lineflyer** [comment]
Closing, as that was done intentionally and a valid reason was given.
