### ISSUE TITLE
Cache name rendered multiple lines in cache list

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5992]
Have GC6T86J in a cache list. You will notice that its name is rendered in 2 lines (the second clock of that name is visible partly). Probably that happens for all caches, we just did not notice yet.

**Comment by Bananeweizen** [comment]
I should have taken a screenshot. I can't reproduce this. And I have no clue how I managed to have a cache list where the cache list items where all _not_ using the marquee=ellipsize and the maxLines=1 attributes from our XML layout.

If anyone of you ever notices that long cache names in the cache list are all not ending in "...", but instead stop after a full word and leave much space at the end, then you have run into the same bug and may want to take a screenshot (or document if something was unusual getting into that state).

**Comment by Bananeweizen** [comment]
Reproduction:
* Open any cache list with a long named cache and notice the ellipsis.
* Open a cache list that contains caches with strike-through (e.g. I use my event list with lots of expired events).
* Switch back to the first list. Abbreviation with ellipsis no longer works, instead the abbreviated name part is removed.

It seems we may need to reset some layout attribute, which is added to the cache list item view only when strike-through names are rendered.

**Comment by pstorch** [comment]
I can reproduce it. I'll have a look.
