### ISSUE TITLE
Routing breaks when switching map provider

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5993]
Switch between Google and mapsforge. Routing is broken afterwards. Only restarting navigation may fix it.
2 theories: 
the restart of the activity due to provider switching reconnects to the service to fast.
We cannot disconnect from the service fast enough of it is currently doing a routing calculation.

**Comment by moving-bits** [comment]
Cannot reproduce it. Tested it using the emulator:
- select Google Maps
- open cache details and navigate to cache
- switch between Google Maps and OSM

=> Routing line is still present, and route gets updated on location change, even after multiple changes between the two maps. (Maybe it's been an artifact of switching between two `CGeoMap` based maps, which we no longer do.)

Let's close this old issue for now, and reopen a new one, if needed.
