### ISSUE TITLE
adopt rebase strategy for pull requests

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5995]
github has finally introduced a [rebase strategy for pull requests](https://github.com/blog/2243-rebase-and-merge-pull-requests). Last time when we discussed whether squasing would be an option, most developers voted for not destroying the history of the atomic commits. Rebasing would completely fit to that requirement and still give a more clear history view.

Unfortunately there is no option to select a default, when enabling multiple strategies. I therefore suggest to disable all other merge strategies in the repository settings to basically enforce rebase on merge. For reference, this is how to the admin section looks like:
![2016-09-26_20h25_01](https://cloud.githubusercontent.com/assets/406876/18846704/87125172-8427-11e6-8463-9504197a7a79.png)

Comments?

**Comment by rsudev** [comment]
I am a big fan of rebasing when maintaining a 'single source of truth' master branch. History gets very hard to understand otherwise.

**Comment by UniQP** [comment]
I'm also in favor of making the rebase strategy our default. It leads to a clean history and does not change the proposed commits (in constrast to squashing).

**Comment by pstorch** [comment]
Yes, rebasing

**Comment by Bananeweizen** [comment]
Okay, rebasing is now the only available strategy in our repository.
