### ISSUE TITLE
Save for offline from map not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5997]
Short version as I am on mobile only:
- Current nightly
- Searched for an address
- Mapped the result
- Selected "Save for offline" from map menu

Result:
Toast is shown with something like "Nothing to save" although unsaved caches are on the map

Might be related to new map (did not test old map/google map)

**Comment by rsudev** [comment]
I cross-checked and it happens reproducible and only on the new map for me.
