### ISSUE TITLE
send2cgeo website refers/includes outdated send2cgeo script

### ISSUE THREAD

**Issue by knoepfchendruecker** [cgeo/cgeo#6000]
##### Detailed steps causing the problem:
- A user wanting to install the send2cgeo userscript may launch a google search for "send2cgeo". A Google search for "send2cgeo" does list https://send2.cgeo.org/howto.html as one of the first results.
- The "script installation with..." sections in https://send2.cgeo.org/howto.html do refer the user to https://send2.cgeo.org/script.html.
- The link "Start" on https://send2.cgeo.org/script.html refers to https://send2.cgeo.org/send2cgeo.user.js, the outdated version 0.32 of the send2cgeo script. The same version is also displayed in raw on the same page.

##### Actual behavior after performing these steps:

A user following the installation steps will install version 0.32 of the userscript, which doesn't work with the current geocaching.com website; a more recent version of the script is required.

##### Version of c:geo used:

2016.09.22

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: XT1562 (lux_reteu, motorola)
Android version: 6.0.1
Android build: MPD24.107-52
Cgeo version: 2016.09.22
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 27.09.16
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
Installed cgeo plugins: calendar, contacts
--- End of system information ---
```

##### Other comments and remarks:

https://send2.cgeo.org/howto.html seems to be outdated and not longer being maintained.

Visiting https://send2.cgeo.org does redirect to http://www.cgeo.org/send2cgeo.html.
The installation section on that page does refer to multiple scripts (geocaching.com, opencaching.de, opencaching.pl) using raw github links, e.g. https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js for geocaching.com.
This ensures the most recent (working) version 0.37 of the send2cgeo user script for geocaching.com.

Redirecting from https://send2.cgeo.org/howto.html to http://www.cgeo.org/send2cgeo.html or completely removing https://send2.cgeo.org/howto.html is probably the way to fix this issue. As the visiting https://send2.cgeo.org redirects to a different howto, the old howto document looks slightly deprecated.

Otherwise, updating https://send2.cgeo.org/send2cgeo.user.js or fixing the link and content in https://send2.cgeo.org/howto.html is also an option to resolve this issue.

**Comment by Lineflyer** [comment]
Thanks for reporting this!
@mucek4: Is there a way to enforce redirect to the github io also if users request another page than the index on send2.cgeo.org?

**Comment by Lineflyer** [comment]
Or simply remove all those old pages from the server?!

**Comment by knoepfchendruecker** [comment]
send2.cgeo.org claims to be an Apache webserver, so something like

RewriteRule   "(.*)"  "http://www.cgeo.org/send2cgeo.html"  [R,L]

should do the trick.

**Comment by mucek4** [comment]
RewriteRule was a little bit more complicated, as script itself uses same URL. I have added rewrite rule for those 3 pages mentioned. @knoepfchendruecker can you please try if everything works as expected.

**Comment by knoepfchendruecker** [comment]
@mucek4 the redirect for https://send2.cgeo.org/howto.html works fine.

I just came across a specific cornercase around the userscript, so the redirect for https://send2.cgeo.org/send2cgeo.user.js probably should point to https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js.

Why: script monkey/tamper monkey do remember the location where they originally downloaded a userscript from and offer "updating" the script by reloading the file from the same location. If a user hasn't updated their send2cgeo-script yet, script monkey/tamper monkey still has the "old" URL and is used to update the script, this update will most likely fail. A redirect to the new location should be safe.

**Comment by mucek4** [comment]
You might be right. I have redirected script as suggested. Technically scripts have download and update URL set.

**Comment by knoepfchendruecker** [comment]
Verified both https://send2.cgeo.org/howto.html and https://send2.cgeo.org/send2cgeo.user.js to be okay. Thanks for the quick fix!

**Comment by mucek4** [comment]
Thank you for reporting.
