### ISSUE TITLE
calculate routing asynchronous

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6004]
Test bigger distances and lift the 5 kilometres limit.

**Comment by Bananeweizen** [comment]
To really increase this limit, we have to change the way we call the routing service. Right now, we do a synchronous call during the drawing of the map. Of course, with longer distances, this leads to notable delays when opening/refreshing the map. I've therefore left the limit at 10 kilometers for now, that was still just a slight initial delay on my phone.

**Comment by Lineflyer** [comment]
@moving-bits This is for sure outdated,  isnt it?

**Comment by moving-bits** [comment]
Actually no, IIRC. We still do a synchronous call when calculating route to current target.

Only when recalculating a individual route (which typically consists of several segments, which get calculated separately) this is done in background, and updated only on changing an individual route.

**Comment by moving-bits** [comment]
But due to faster hardware available nowadays, we've made the limit configurable, so that users can decide on their own, which max. distance will work on their mobile.
