### ISSUE TITLE
doesn't respect big font setting

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6011]
When I enable big fonts in cyanogen mod accessibility settings, this has no effect on the app. I'm rather sure that we respected the global accessibility settings for font size before.

**Comment by Bananeweizen** [comment]
I'm out of clues here. My understanding is that using the "sp" font sizes should be sufficient to scale all our texts automatically with the system setting. However, that doesn't happen. What am I missing?

**Comment by samueltardieu** [comment]
Text in cgeo is properly scaled on my vanilla Android 7 (Nexus 5X) according to accessibility settings.

**Comment by Bananeweizen** [comment]
I know at least one other geocacher who also has this issue (since she made me aware of it) with Android 5.something.

**Comment by Lineflyer** [comment]
For me the font size defined in the device settings are applied in c:geo on all available devices I have here for testing, Closing this as outdated for the time being.
