### ISSUE TITLE
Brouter: Distance shown is not the routed distance

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6017]
- New map active
- Open live map
- Select a cache to show its popup
- Press the "route button"

The route is shown instead of the direct line (correct) but the distance shown on the upper right is not the length of the route. 
At this point I would expect to see the routing distance (if available) or we should ommit this information.

Found this today while routing to a cache on the other side of a bay (direct distance 50m, routing distance >1km)

**Comment by rsudev** [comment]
I wouldn't call it a bug, rather an implementation omission. I was thinking about showing both, as the route might not be the way you want to follow, especially in the countryside (as I observed last weekend)

**Comment by Bananeweizen** [comment]
I thought about this too, when I started exploring the feature, but I'm hesitant. All places in cgeo just deal with the straight distance to the cache. And I would rather leave it like that, especially since calculating the  correct distance gives some overhead and relatively little benefit.

And especially in a case like you described I would want to know that I _am_ near the cache already, even though the device doesn't know a good way to ground zero.

**Comment by Lineflyer** [comment]
> And especially in a case like you described I would want to know that I am near the cache already, even though the device doesn't know a good way to ground zero.

I do think different:
If the user actively decided to use the routing feature (which he did by installing Brouter) I think he would like to see the routed distance in that screen described. There are lot of other places, where the straight line distance is shown, but at this screen distance and route should be matching.
In my example I would have loved to see the routed distance instead as it was meaningful (as I said it was 50m over water to the cache and I was needing the info how long the real route would have been).

**Comment by SammysHP** [comment]
Is the distance updated when you move?

**Comment by Lineflyer** [comment]
Yes, but of course only showing the direct line distance.

**Comment by rsudev** [comment]
> If the user actively decided to use the routing feature (which he did by installing Brouter) 
Here I tend to disagree, as Brouter can be (tentatively) integrated with a number of apps, so people migth already have it installed long before c:geo was able to use it.

**Comment by Lineflyer** [comment]
@Bananeweizen 
>And especially in a case like you described I would want to know that I am near the cache already, even though the device doesn't know a good way to ground zero.

As we now have a dedicated navigation option for "straight line" I think the distance shown when routing is active should be the routed distance. That makes things consistent.

**Comment by Lineflyer** [comment]
Now also some users feedback on social media (free translated):
Using the menu on the map and the option "Routing" I can change between car/bike/straight line and I see the route on the map changing accordingly. However the distance shown does not change...I think this is a bug in the new function, isn't it?

**Comment by moving-bits** [comment]
FYI: Have a first WIP implementation for NewMap:

![image](https://user-images.githubusercontent.com/3754370/58378748-61db5a00-7f99-11e9-93c9-b1c1bb68e84e.png)

Next step is adapting it for CGeoMap as well.
