### ISSUE TITLE
WhereYouGo not listed in Navigtion for a specific cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6018]
- Open GC6B4TH

Although it contains a link to the cartridge the WhereYouGo option is missing in the navigation menu.

**Comment by Lineflyer** [comment]
Mmh...same here for me with this cache: GC6ARDT

Am I missing something or is this a general bug?

**Comment by Bananeweizen** [comment]
the link is in the short description, the check looks only in the long description
