### ISSUE TITLE
Log picture upload ends with error message although OK

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6024]
##### Detailed steps causing the problem:
- Log a cache find and attach picture with the log (GC.com)
- Send the log

##### Actual behavior after performing these steps:
An error message is shown, that sending seems failed and user shall check on website (retry/cancel/offline).

##### Expected behavior after performing these steps:
This occured to me on the last 14 days for each picture I attched, so something seems wrong while checking the result.
In all cases log and picture had been uploaded correctly.

##### Version of c:geo used:
Master

##### Is the problem reproducible for you?
Yes (at least it seems like that to me...can't do extensive tests right now)

##### Other comments and remarks:
Feel free to test with my owned caches to check whether reproducible

**Comment by rsudev** [comment]
I can reproduce this

**Comment by Lineflyer** [comment]
Setting this to "Regression" as I just looked into support mails and found quite some users complaining about the problem also with the Play version.
Can someone look into it??

**Comment by pstorch** [comment]
I can have a look
