### ISSUE TITLE
"Make list unique" menu makes cgeo crash in nearest cache list

### ISSUE THREAD

**Issue by morice-net** [cgeo/cgeo#6025]
Hello Cgeo team !!

##### Detailed steps causing the problem:
- Launch the app
- Click on "Nearest cache list"
- Click on menu (top right)
- Click on "Make list unique"

##### Actual behavior after performing these steps:
CGeo **crashes**

##### Expected behavior after performing these steps:
CGeo doesn't crash

##### Version of c:geo used:
Master

##### Is the problem reproducible for you?
Yes, systematic

##### System information:
Device: SDK build for x86
Android version 6.0
Android build: sdk_google_phone_x86-userdebug 6.0 MASTER 3287151 test-keys
Cgeo version: 2016.10.08-14bbb90 developer build
...

##### Other comments and remarks:
No

Many thanks in advance !

Morice

**Comment by Bananeweizen** [comment]
Thanks for the nice report.
