### ISSUE TITLE
Strip EXIF data from uploaded images

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6026]
I think it would be nice to have the option to strip Exif data from uploaded images, and I think it should be the default action.

I've logged a couple of FTF's recently which were the finals of puzzle caches. I usually post a picture of the logsheet in these cases. I've just realized that anyone viewing the image in the log entry can see the location where I took the photo and so deduce where the cache is without solving the puzzle.

I guess this should really be done by groundspeak, but I don't hold out much hope of getting that done.

**Comment by SammysHP** [comment]
As we already resize the image and the EXIF information is rarely needed,  I suggest to remove it always without adding an option. But then we should respect the orientation tag and rotate the image if necessary.

**Comment by pstorch** [comment]
Interesting, this Groundspeak bug is still present. I thought they have fixed it some time ago. But apparently not.

**Comment by SammysHP** [comment]
I wouldn't call this a "Groundspeak bug". Usually the user is responsible for what he uploads. ;)

**Comment by pstorch** [comment]
I know some Mystery Owner who complained at GS because of this and I think there is also a Ticket in their bug tracker.
Normally I'm with you, that the user should know what he is doing. But I doubt that in this case all users are aware of this.

**Comment by Bananeweizen** [comment]
I'm also in favor of removing that without any option. It is generally useful to avoid uploading more privacy related data then the user intended.

**Comment by Lineflyer** [comment]
After thinking about it, I would also vote for stripping EXIF during upload by default (no option).

**Comment by pstorch** [comment]
Just a comparison to other apps:
- Official GC App keeps the Exif data as is
- Locus: strips out Exif data and scales the image, too

**Comment by Bananeweizen** [comment]
I was browsing the web a little to see how this can be done. The most clean solution seems to be using yet another apache library: http://stackoverflow.com/a/31117888/44089

**Comment by samueltardieu** [comment]
Removing exif information by default is fine, however I would like to be able to keep it (using a checkbox). I have already navigated to the place where pictures were taken because there was a beautiful point of view or point of interest near the cache revealed through the photo.

**Comment by alan666notb** [comment]
Has this been included in the latest release? (I'm on the beta test release).
I've just noticed that new images uploaded to log entries don't show any meta/Exif data.
Or maybe GS fixed it for themselves?

**Comment by rsudev** [comment]
As this issue is still open, nothing has been implemented from our side yet.

**Comment by pstorch** [comment]
@alan666notb maybe the uploaded picture was very big. When I remember correctly, GS is resizing (and with it removing Exif data) when the uploaded pic is above a certain size. But don't quote me on this.

**Comment by alan666notb** [comment]
No - it's the same as images I've previously uploaded.
I'm pretty sure there's been a change on the GS website.

**Comment by pstorch** [comment]
@alan666notb I've uploaded two photos yesterday and they still contain the coordinates.

**Comment by alan666notb** [comment]
Can't explain it then...
This morning I uploaded an image attached to a log entry via cgeo - No Exif data shown,
I just tried uploading the same image via the website - Exif data is shown.

**Comment by pstorch** [comment]
@alan666notb have you enabled scaling in c:geo? If so, then coords are removed. Just tested it again. When no scaling is selected, the coords are kept.

**Comment by alan666notb** [comment]
Ah yes, that must be it, I have scaling set to 1024.
I can't remember, but I guess the images that show Exif data I must have uploaded to the log entries after I'd logged them via cgeo.

**Comment by geocachermgo** [comment]
Meanwhile in the pictures shown in the caches groundspeak removes the exif info since 2018.(see [forum](https://forums.geocaching.com/GC/index.php?/topic/350572-how-can-i-keep-exif-informations/) )
I do not know if they keep the original file with the exif.
Since it removed by cgwo when scaling it should be removed in all cases.

**Comment by geocachermgo** [comment]
The change hint of the current nightly claims "always remove EXIF data". Nightly from 6.10.is commeted
_related to #8978: fixing non-GUI-parts (img delete, remove exif, move (commit: bcc3c51) (detail / githubweb)._
@eddiemuc Can we close this issue?

**Comment by eddiemuc** [comment]
Yes we can. Thanks for the hint
