### ISSUE TITLE
No coords on nearby search

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6029]
This has major impact to our users as an important function is lost:

##### Detailed steps causing the problem:
- Premium member
- Have no caches stored/caches
- Search nearby caches
- Alternatively: Search by location (where you have no caches stored)

##### Actual behavior after performing these steps:
- Caches do not have coords (approximated distance shown)

##### Expected behavior after performing these steps:
- Caches should have coords (coming from the LOC file we load while performing the search)

##### Version of c:geo used:
Master and current Play release

##### Is the problem reproducible for you?
Yes, since today

##### Other comments and remarks:
No time yet to check the logs, but I assume the LOC download is broken.

**Comment by Lineflyer** [comment]
After a quick look on the website the "Download Waypoints" button is there on the old search but selecting it leads to an empty list to select the desired caches to be included in the LOC.

Website broken? How to adress it?

**Comment by rsudev** [comment]
I checked the search as well.
The caches to be included have to be selected before clicking the download, then it still works.
So likely rather a small change in the interface.

**Comment by Lineflyer** [comment]
At the point of time when I checked the website they also shall be selected but the table was empty after clicking once on the download button.

**Comment by Lineflyer** [comment]
Log:
```
21:10:51.187 Debug cgeo 24450  [main] LocationProvider: requesting most precise locations
21:10:51.187 Debug cgeo 24450  [OkHttp] GET https://www.geocaching.com/seek/nearest.aspx?lat=43.2630126&lng=-2.9349852&tx=9a79e6ce-3344-409c-bbe9-496530baf758
21:10:51.296 Debug cgeo 24450  [looper callbacks] RotationProvider: registering listener
21:10:51.624 Debug cgeo 24450  [OkHttp] 200 (409 ms) GET https://www.geocaching.com/seek/nearest.aspx?lat=43.2630126&lng=-2.9349852&tx=9a79e6ce-3344-409c-bbe9-496530baf758 (http/1.1)
21:10:52.388 Debug cgeo 24450  [network-4] DataStore.loadCaches([GC4NPQ2, GC4N1VD, GC5QWR3, GC1ZGNP, GC45ABY, GC5QVJW, GC6C42C, GC4N7BR, GC6N7CF, GC4NRRE, GC64HHX, GC4CRH4, GC6RH6X, GC4NJT7, GC5QWNJ, GC4N9JX, GC5E6G8, GC3WKMY, GC6ENPW, GC6N771]) returned no results
21:10:52.388 Info cgeo 24450  [network-4] Trying to get .loc for 20 caches
21:10:52.388 Warning cgeo 24450  [network-4] Loc download url not found
```

**Comment by pstorch** [comment]
Debugging it right now. The `<td>` Element with the `CID` is empty. Don't know why yet.

**Comment by Lineflyer** [comment]
Added a message to c:geo Homepage and a FAQ entry for temporary issue.
I did not yet sent any notification to the users as we might probably be able to fix it short termed.

@pstorch :
Great! If you find a solution please put it to the `release` branch.

**Comment by pstorch** [comment]
Unfortunately there are more errors. Can't login anymore via c:geo.

**Comment by mucek4** [comment]
For me c:geo says login OK.

**Comment by pstorch** [comment]
Somehow it changed my username to `c:geo` ;)
Now I'm at a point where it doesn't find the html form element to post the CIDs for loc download.

**Comment by Lineflyer** [comment]
For me all is normal with the login. Maybe you changes something to be worse during debugging?
I am also on IRC.

**Comment by pstorch** [comment]
The `name` attribute was removed from the `<form>` element on the page, so our Pattern didn't match anymore.

Old: `<form name="aspnetForm" method="post" action="..." id="aspnetForm">`

New: `<form method="post" action="..." id="aspnetForm">`

**Comment by Bananeweizen** [comment]
@pstorch Please don't create the bugfix twice in separate unrelated commits. Just commit to release, afterwards merge release into master (which @samueltardieu did after your changes).

**Comment by pstorch** [comment]
@Bananeweizen umm, that was unintentionally. I guess I know how it happened. I merged via GitHub. Opening a PR from release to master and merged it right away. And PR merging is configured to do a rebase.  I do local merging next time.
