### ISSUE TITLE
Problems with the new Mapsforge Beta

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6032]
##### Detailed steps causing the problem:
- Upgraded to version 2016.10.13
- go to settings, system, check mapsforge beta
- go to live map
##### Actual behavior after performing these steps:
1. c:geo responds horribly slow and I get the OS warning "application not responding, do you want to wait or close?"
   This happens for click on live map, until live map is actually shown.
2. Live map has only one layer: offline map via the mapsforge library. 
   The setting I checked did not imply that by checking it I will only have the offline map as available layers. 
   The phrasing implies that a new version of the mapsforge library is being used (AFAIK for offline maps) and possibly that the offline map layer is now the default one.
3. no stored caches are shown on the map. 
4. very slow response when going back to the map from cache description
5. significantly slower render time when scrolling map, especially when scrolling in large increments or jumps.
6. horribly slow UI response when showing map from cache description (using map navigation menu)
7. Pressing the route button from cache brief window only shows straight line. (BRouter service is active)
##### Expected behavior after performing these steps:
1. good response time. 
   As soon as I switched off the Mapsforge beta, I no longer had such slugish UI response.
2. Have all map layers available with this new library
##### Version of c:geo used:

2016.10.13
##### Is the problem reproducible for you?

Yes
##### System information:

```
Device: Q800
Android: 4.2.1
Google Play services: disabled
Low power mode: inactive
Compass: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & accelerometer: present
Direction sensor userd: rotation vector
Map strategy: auto
HW accel: disabled
Installed cgeo plugins: none
```

Device specs: 
CPU: Cortex-A7 Quad Core la 1,2GHz
GPU: PowerVR SGX 544/OpenGL ES 2.0
RAM: 1GB

**Comment by Lineflyer** [comment]
@andrixnet What mapfile are you using? Can you specify the URL / source?

**Comment by andrixnet** [comment]
romania.map from here: http://download.mapsforge.org/maps/europe/
I downloaded it on jan 16th 2016.

**Comment by Lineflyer** [comment]
@andrixnet Here is some more details feedback for you:

> 1. c:geo responds horribly slow and I get the OS warning "application not responding, do you want to wait or close?" This happens for click on live map, until live map is actually shown.

I cannot reproduce this with my germany.map from same source.
Currently loading the romania.map to try with that.

- Are you using any special themes?
- Do you have "debug mode" enabled in Settings. Does it make any difference if you disable?
- Can you provide a log of this ANR?

> 2. Live map has only one layer: offline map via the mapsforge library.  The setting I checked did not imply that by checking it I will only have the offline map as available layers. The phrasing implies that a new version of the mapsforge library is being used (AFAIK for offline maps) and possibly that the offline map layer is now the default one.

You are right. This is because a "Beta" is still work in progress. It does not yet have online modes.
See #5960 

> 3. no stored caches are shown on the map. 

I don't understand this item. Can you explain?
Maybe you are refering to #5929?

> 4. very slow response when going back to the map from cache description

Which menu function do you use to go to the map?
This could be related to 1.

> 5. significantly slower render time when scrolling map, especially when scrolling in large increments or jumps.

You mean the updating of the map tiles?
How does it look like? Totally empty for a longer time or some tile missing?

> 6. horribly slow UI response when showing map from cache description (using map navigation menu)

Isn't this the same as cou describe in 4.

> 7. Pressing the route button from cache brief window only shows straight line. (BRouter service is active)

This is currently limited to a maximum distance (AFAIR 5km). Could that be the reason. Please be also aware you need to download the routing info in Brouter for the specific region.
Let us not mix up the brouter function with the new map itself, so lets split this into a new issue (please open one) if this is still happening.

Thanks for your valueable feedback, but next time please think about splitting up the items into different issues (e.g. "Slow UI". This makes it easier for us to track different problems and to identify duplicates.

**Comment by Lineflyer** [comment]
Update:
romania.map is performing well on my Samsung S7. Very responsive independently of the zoom factor.
Downloaded today, stored on external SD.

**Comment by andrixnet** [comment]
With all due respect, I wouldn't even begin to compare the hardware performance of the Samsung S7 with my Allview P5...

**Comment by andrixnet** [comment]
Just updated c:geo to 2016-10-23.
Let me answer each point as best I can. 

- I am not using any themes. (default only)
- "activate debug log" = OFF (was never on while encountering these issues)
- What is "ANR"? 
Please note that I was unable to obtain debug logs on my device. (perhaps some logging features are absent from the ROM?)

Subscribed to #5960 

I have added screenshots and explanations to #5929 

Going back to the map from cache description: click on cache icon on map, see popup window, click show more to see it's description. Press back to return to the map. 

Slow response time scrolling/zooming: with the new 2016-10-23 it seems to have improved. I do however have to make more tests. 

When rendering, some tiles are missing. Details moved here : #6064

I will do more testing and get back to you.

Note: I was unaware of the 5km limit for brouter. Not documented? Anyway, seems pointless to limit like this ...
Will do more tests and get back in new issue if necessary.
Thank you.

**Comment by andrixnet** [comment]
Tested with my tablet which is a dual core 1GHz device. 
tile rendering is 2x-3x slower using mapsforge beta compared to the default one.
I can create a small video if necessary.

**Comment by andrixnet** [comment]
I have just discovered that the meaning of "enable live" changed for mapsforge beta.

- mapsforge default - enables search and download of caches on current map viewport (brief data) while all stored caches are always shown.
Mapsforge beta - enable live enables the displa of stored caches AND searching online for caches in viewport.

IMO the mapsforge beta behaviour is wrong.

**Comment by andrixnet** [comment]
As I said in a another comment, testing something like that on a very high performance device doesn't really prove anything. 
The Samsung S7 is today among the top highest performance devices one can get. And the matching price tag as well. 
One cannot expect most users of the app to have such a device.

**Comment by Lineflyer** [comment]
@andrixnet Thanks for your effort in creating dedicated issue. Although more work in the beginning it is more meaningful to discuss the different topic.

So please allow me to clsoe this overall issue. 
If you like you can create a dedicated issue regarding the map speed, however I have no clear idea how to benchmark that on different devices.

**Comment by andrixnet** [comment]
Ok, understood. 
One suggestion: get a low-end device, like a cheap, single core CPU android device. See how it works on it.

**Comment by andrixnet** [comment]
Also regarding speed, I will follow the evolution of c:geo with future releases and get back to you (separate issue) if need be. Thank you.
