### ISSUE TITLE
BRouter integration suggestions

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6033]
I've seen the info (and some new strings, as I am translator as well) for the integration of BRouter as routing service. Here are a few suggestions from user point of view: 
- [ ] Make checks that app is installed
- [ ] enable/disable BRouter functionality from Settings
  (if app not installed, disabled and control not changeble)
- [ ] configure BRouter router calculation options
  (possible under Settings -> Navigation?)
- [ ] Start BRouter service when c:geo needs it, if not started manually by user. (if possible)
- [ ] Make checks (if possible) and report proper errors if BRouter does not have data to calculate route
- [x] add "Route" button to cache brief window
- [ ] add "Route" button / menu item to cache description
- [ ] add "Route" button / menu item to cache waypoint
- [ ] "Route" button should either show a straight line or be disabled when service not available / disabled in settings
- [ ] show "Route distance" and "DTD - Direct To Destination" distances (when using route)
- [ ] offer the possibility to suggest 1-3 alternate routes, if possible (according to map), if possible (according to BRouter services) (as future enhancement)
- [ ] Add BRouter to Utility programs list
- [ ] Provide a way for user to select route calculation mode (car, bike, etc) for cache/waypoint or when displaying map (allow changing this mode to other then default set in settings)
- [ ] Document installation, configuration and usage instructions here http://www.cgeo.org/faq.html

**Comment by andrixnet** [comment]
Note: BRouter service can be started even if not running (checked using it as route provider in OSMand)

**Comment by Bananeweizen** [comment]
Requirements in software development are meant to solve _problems_ the user has, not to implement everything developers can come up with. So could you please describe the _problems_ of an end user which need to be solved, instead of listing 20 (seemingly) random implementation solutions? I don't care if Locus or any other app has these 20 items. I care about solving user problems.

Besides that, you should probably use the existing implementation first, as much of what you describe is available.

**Comment by andrixnet** [comment]
Yes, I can: 
Having routing is a good idea and I've seen the new partial features so far. 

User issues that are addressed as solution suggestions: 

1. user completely unaware of this feature and nothing from the GUI helps intuitively 
_(current GUI incomplete, hence the GUI suggestions)_
2. lack of available knowledge and guidance for the user on how to deploy the necessary dependencies
_(c:geo FAQ says nothing about this. I can write an initial text on the subject, based on my end-user experience, text which will also have to be revised by those developing this feature, for they have the best knowledge on how it is supposed to work)_
3. enable/disable usage of this feature within c:geo (if available)
_(like other features can be enabled/disabled)_
4. basic configuration options for this feature (like route strategy: car/bike/foot)
_(given the specific nature of this feature, basic configurability is a must)_
5. make this feature properly available in the UI where it is useful (cache brief window, cache details pages, waypoint pages)
6. provide meaningful information to the user
_(distance direct to destination is very significant to geocaching. also a line could be drawn from current position to target, in a different color then the route.)
(route length is also important because it designates the distance required to be traveled)_
7. c:geo as a client for BRouter service should make the proper checks the service is available and functional in order not to crash / give out [too] many error messages or otherwise clutter c:geo's usage flow (ultimately decreasing end-user positive experience)
8. offering alternate routes is a "would be nice to have" functionality
_(the value for the end-user to be determined)_

------------------
What the user currently encouters: 
- doesn't know this function exists
- doesn't know this function has external requirements and what exactly are they
- I only know about routing as a feature is because I translated a few strings about it, none of which I've actually met so far in the app.
- I actively searched the settings for navigation, then the cache navigation menu for such a feature, found nothing
- saw a new button on cache brief window (over the map) with mapsforge beta enabled and explored it (with BRouter already installed, configured and started, and tested with OSMAND)
It shows a straight line to the cache. I assume it may have something to do with routing, possibly corroborated by https://github.com/cgeo/cgeo/issues/6017
- **as a user**, I am still completely confused whether this feature is configured properly or not, if it is suffering from bugs or not, (mapsforge beta certainly does), even if the brouter code is actually present in the 2016.10.13 release or not. 

I sincerely hope my suggestions will help this feature work well, reducing various possible snags along the implementation and be well documented. 

Since the FAQ at cgeo.org isn't hosted as source code on github (or I could not find it), please let me know where and how can I submit my contribution(s) to it.

**Comment by SammysHP** [comment]
The FAQ is hosted on GitHub. The link to the source is shown at the end of the page.

**Comment by andrixnet** [comment]
I totally missed that. Thank you.

**Comment by andrixnet** [comment]
See https://github.com/andrixnet/cgeo.github.io/commit/306b543cf2a29712d0e55533d71e7563f0a63edb for an initial BRouter FAQ draft.

**Comment by Lineflyer** [comment]
FYI: https://github.com/cgeo/cgeo.github.io/pull/121 was prepared as a basic information

**Comment by moving-bits** [comment]
There has been done a lot wrt to routing integration into c:geo throughout the last years, so let's close this issue here.

Examples for what has been done meanwhile:
- we have a detailed manual, also describing BRouter
- BRouter is part of "useful apps" section and also integrated into the installation wizard
- we have an internal routing option (integrated BRouter)
- ...

So let's open new issues if something's missing from UX perspective.
