### ISSUE TITLE
Listing background not shown in gallery if hosted externally

### ISSUE THREAD

**Issue by kington93** [cgeo/cgeo#6039]
**Feature request**

Hi guys,

thanks for your great job!
It is possible to display the background-image of a cache-listing in c:geo? If the picture is in the gallery than its shown in cgeo. But often the background is not in the gallery and in this case it will not be shown.

I hope that will be possible.

Thanks and best regards
king-ton

**Comment by Lineflyer** [comment]
It should be included in the pictures link under "Hint" in the cache description AFAIR.

**Comment by pstorch** [comment]
I think it depends on whether the image is uploaded to geocaching.com or a background image from somewhere else.
As an example: https://coord.info/GC45W92 has a background image linked from external source. It is not shown on the images tab.
Here is an example with a background image from geocaching.com: https://coord.info/GC4QAFH this is shown on the images tab.

**Comment by samueltardieu** [comment]
@pstorch In GC4QAFH, I think that the background image is repeated later in the page and matched against the regular spoiler images expression.
