### ISSUE TITLE
URL in hint gets convertet to "visit link" but it is not clickable

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#6041]
##### Detailed steps causing the problem:
Some Cacheowners, especially in the US, are writing URLs in the hints of their listings. Here is an example: https://coord.info/GC4W4BP
cgeo recocnise this links and shows a blue "visit link" instead. But its not clickable. if you click on the link the whole hint is only getting en/decrypted

##### Actual behavior after performing these steps:
"visit link" in hint not clickable

##### Expected behavior after performing these steps:
"visit link" should open the link, not en/decrypt it like normal hint-text
alternativ: dont convert it to "visit link" so that it can be read or copied

##### Version of c:geo used:
2016.10.13

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
confirmed
