### ISSUE TITLE
Home coords parsing broken?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6042]
FB reports tell, that people are located in Iran by default when GPS is not available.
I can reproduce by switching off GPS and starting c:geo twice (because home coords are only used after second login AFAIR).

It seems either the home coords are not working on the website or we fail when parsing them.

**Comment by rsudev** [comment]
I assume a website change. I am on a trip right now and observed the same behaviour this morning. And I am pretty sure it was OK yesterday (same version of c:geo)

**Comment by Lineflyer** [comment]
Seems a lot if people use cgeo without GPS  or phones are behaving different. Many mails and posts regarding this problem.

Is someome available and willing to check and fix?

**Comment by samueltardieu** [comment]
I'll have a look.

**Comment by samueltardieu** [comment]
They have started to encode home location strings. Spaces are encoded as `&#32;` for example, which gets parsed as "32", giving random locations.

Fix is incoming.

**Comment by samueltardieu** [comment]
@Lineflyer Feel free to try the release branch. Merge to the master branch will happen in a few minutes, I'll trigger a new nightly build.

**Comment by Lineflyer** [comment]
Looks working in nightly!!
Thanks for the quick fix.

Will check release tomorrow.
