### ISSUE TITLE
Web translation for change log

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6049]
Provide something to invoke Google translate or similar from the change log page. Might that help non English users like my own father?

**Comment by Lineflyer** [comment]
Or enable it somehow for Crowdin...

**Comment by rsudev** [comment]
If we want to include it in Crowdin, we need to partition it into the individual entries, to avoid retranslations for the whole text on every addition. As such I think this is a good idea, especially as I assume that we might manage to get a German translation (the most crucial one IMO) better than Google translate :)

**Comment by Lineflyer** [comment]
Link to #4317

**Comment by Kebap** [comment]
seems related to #4318

**Comment by Lineflyer** [comment]
See #4317
