### ISSUE TITLE
date format parsing might be broken

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6051]
According to recent FB posts it might be that cgeo does not parse all formats from gc.com.
Can we check?

**Comment by pstorch** [comment]
I guess this pattern is not recognized by cgeo: `<option value="dd&#32;MMM&#32;yy">22 Oct 16</option>`

**Comment by samueltardieu** [comment]
Yeah, we probably have to `fromHTML` it, similar to #6042.

**Comment by Lineflyer** [comment]
And IMHO there are now more formats selectable as in the past....

**Comment by samueltardieu** [comment]
As long as they are compatible with Java date format, we are safe.

**Comment by samueltardieu** [comment]
I could not check the solution, but it should not do any harm even if it wouldn't work.

**Comment by pstorch** [comment]
I get this error:

```
10-22 23:10:31.468 12827-13440/cgeo.geocaching E/cgeo: [network-7] GCParser.loadLogsFromDetails: failed to parse log date
                                                       java.text.ParseException: Unparseable date: "22 Apr 16" (at offset 2)
                                                           at java.text.DateFormat.parse(DateFormat.java:579)
                                                           at cgeo.geocaching.connector.gc.GCLogin.parseGcCustomDate(GCLogin.java:379)
                                                           at cgeo.geocaching.connector.gc.GCLogin.parseGcCustomDate(GCLogin.java:383)
```

As I mentioned, I guess the Pattern needs to be adjusted to fetch `&#32;` as well.

**Comment by samueltardieu** [comment]
Yup, you're right. This is currently being run by the CI.

**Comment by samueltardieu** [comment]
And date formats are no longer Java compatible. This requires more adjustments on our side.

**Comment by pstorch** [comment]
@samueltardieu no, the Pattern is too broad. Now other selections are matched which are not date formats.

**Comment by samueltardieu** [comment]
Which one are you talking about? A second one has been testing for a few minutes now.

**Comment by pstorch** [comment]
I just tried with:
```
static final Pattern PATTERN_CUSTOMDATE = Pattern.compile("<option selected=\"selected\" value=\"([&#32; /.Mdy-]+)\">");
```

It works, but the Regex is not really correct.

**Comment by samueltardieu** [comment]
I prefer the one being tested right now:

```java
static final Pattern PATTERN_CUSTOMDATE = Pattern.compile("name=\"SelectedDateFormat\".*?<option selected=\"selected\" value=\"(.+?)\">");
```

**Comment by pstorch** [comment]
@samueltardieu ah, missed your update. The first one selected the Language I guess.

**Comment by samueltardieu** [comment]
Yeah, I noticed that when (finally) testing. I'll merge the current one which works well for me.

**Comment by pstorch** [comment]
@samueltardieu I tested your new pattern locally. Looks good.
