### ISSUE TITLE
Some date formats still not recognized

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6058]
##### Detailed steps causing the problem:
- Set date format on gc.com to `23.Oct.2016`
- Load a cache with c:geo

##### Actual behavior after performing these steps:
- Logbook is empty

##### Expected behavior after performing these steps:
- Logbook should show the logs

##### Version of c:geo used:
2016.10.22-RC (build at around 23pm last night)

##### Is the problem reproducible for you?
Yes

##### System information:
```
Log date format: 23/10/2016
```

##### Other comments and remarks:
We seem to fail recognizing the selected format.
Did not test all formats by now...Update follows

**Comment by Lineflyer** [comment]
@samueltardieu Might be the RC was created before your latest change, but looking at the CI I think it includes all changes. What do you think?

**Comment by Lineflyer** [comment]
Update: 
Now the problem described above is no longer happening.
I think I will go through all the date format on the website with parallel debug logging in c:geo tonight to get more clues.

**Comment by Lineflyer** [comment]
OK.
I went through all different formats offered using 2016.10.22-RC and could not find any glitch.
Forget about this issue...might be I was still logged in while changing the format.

**Comment by Lineflyer** [comment]
Have to reopen this one as we received several support mail already using the new release 2016.10.23 which have "empty logbooks".
Although I could not find any issues while testing **all** the different date format there still seems to be something wrong.

I answered to al users to check their setting on the server and inform us about the date format which is currently selected.

**Comment by Lineflyer** [comment]
First feedback from a user on support:
``` 26. 10. 2016```

**Comment by pstorch** [comment]
That is the same problematic Dateformat which @samueltardieu reported here: https://github.com/cgeo/cgeo/issues/6065#issuecomment-256167445

**Comment by Lineflyer** [comment]
Same problem. Lets continue there.
