### ISSUE TITLE
Master to Beta?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6061]
Just as a reminder.
From todays IRC discussion:

[20:53] <Lineflyer> OneEyed: What do you think? Merge release to a new old-release and master to release now? This would enable us to publish a RC as beta version on Play.  Background for me is still to enforce shorter release cycles.
[20:59] <OneEyed> Lineflyer: Sure
[21:00] <OneEyed> What about doing that tomorrow or the day after, once we ensure that this release is in ok shape?
[21:19] <Lineflyer> And we might want to think about promoting Mapsforge beta to default
[21:19] <OneEyed> Did it get online tiles?
[21:20] <rsudev> Not yet
[21:20] <rsudev> I started to collect the necessary infos, but was not yet bale to implement it
[21:20] <Lineflyer> mmh...that would be the requirement of course
[21:21] <Lineflyer> Just think about if it would be doable or wait until next cycle

**Comment by Lineflyer** [comment]
Link to #5960

**Comment by Bananeweizen** [comment]
I would not rush the mapsforge to the default implementation. Maps are a rather central part of the user interaction, and at least I feel very disturbed by the flashing effect, that we also discussed in some other issue. Even if everything else might work fine, this makes it feel broken.

**Comment by Lineflyer** [comment]
So we should then wait until the current release is running stable and then decide if we want to merge from master. Mapsforge can also stay beta then if considered to buggy.

**Comment by Lineflyer** [comment]
Now release 2016.11.05 is out on the market. If nothing special happens I suggest to move `master` to `release` in 1-2 weeks (and store `release` into `old-release` as we already did some time ago) to have a backup for emergencies).

**Comment by Lineflyer** [comment]
So what shall we do?
- Release is out and stable.
- Master (after the last days) got quite stable again and could be suitable for beta testers

I still see rapid changes on master (with new developments) and I would prefer to cut as soon as possible to `release` so that the "amount to test" will not get any bigger.
This would of course require more fixing on release from the time we merge `master` to `release`, Is this a problem for the the developers?

Opinions?

**Comment by Bananeweizen** [comment]
fine with me, since the change list is nearly a page long on my phone already.

**Comment by rsudev** [comment]
The stage for the next feature release is set.

**Comment by Lineflyer** [comment]
Thanks! 

So this is a heads up that changes important for next release should be targeted to `release` and only "new things" should go to master. This is due to the fact, that we know have the rather new situation that we have a beta out from `release` soon but not yet a release.
Alternatively we can also merge `master` to `release` once again also before release if this is needed.

Closing here.

**Comment by Lineflyer** [comment]
Milestones adapted to the normal working mode but reflecting the step we made (i.e. "Master branch" renamed to "Release branch" and created a new milestone "Master branch")

**Comment by Lineflyer** [comment]
Beta version derived from (new) `release` branch has been smoke tested succesfully and uploaded to Google Play as a beta release 2016.11.21-RC.
Upcoming feedback will be opened as an issue with label "Beta feedback".
