### ISSUE TITLE
Personal Note on own tab

### ISSUE THREAD

**Issue by sdennler** [cgeo/cgeo#6063]
I would love to have (on a per cache option) the Personal Note on a own tab (site?). Especially on long multicaches (example: GC1K0FM) it is unpractical to always scroll down to note the value of the next stage and go back and search for the description of the next stage.
Great would be to just swipe left and right to switch between the two views like switching to the logs works.
There could be a "edit in separate tab" button below the current edit button.

**Comment by SammysHP** [comment]
Just tap the menu button on a cache listing and select "personal note". A popup with your note and the possibility to edit it will open .

**Comment by sdennler** [comment]
Thank you for the hint. That makes it easier. But I still think having it in a own tab would be even more comfortable and quicker. It would be a good help for all the paperless cachers.

**Comment by SammysHP** [comment]
The question is whether it is easier to swipe a few times or tap two times. I'll re-open this issue for discussion.

**Comment by pstorch** [comment]
I think I would like the personal notes on an extra tab. I remember scrolling a lot myself.

**Comment by Natureshadow** [comment]
If I can get it from the menu, that's better. There are already too many tabs to swipe through.

**Comment by Bananeweizen** [comment]
Just a thought: If our tabs where more easily reachable without swiping, the number would not be that imporatant. E.g. right now the number of visible tab headers is 3 (since we use text), but we could show way more tab headers, if we used only icons.

**Comment by Natureshadow** [comment]
Also, no, thanks. I also don't want to figure out ten new icons every release. I had a hard time of cursing when many other parts were replaced with icons.

**Comment by Lineflyer** [comment]
Seems no clear majority on adding a new tab for the personal note (but we have the mentioned shortcut instead). 
Closing, feel free to reopen.
