### ISSUE TITLE
Mapsforge beta - missing tiles

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6064]
Moved to new issue from #6032

When rendering, some tiles are missing. And they stay missing even after scrolling/zooming in/out.
![screenshot_2016-10-25-19-14-54](https://cloud.githubusercontent.com/assets/3382777/19697815/a0e491c0-9af5-11e6-923b-9f6f45515f17.png)
![screenshot_2016-10-25-19-15-23](https://cloud.githubusercontent.com/assets/3382777/19697822/a567264a-9af5-11e6-9548-042b91805953.png)
The missing tiles never load (during current session).

![screenshot_2016-10-25-20-01-26](https://cloud.githubusercontent.com/assets/3382777/19697939/1112ab62-9af6-11e6-8e0b-ab9decbf8d2e.png)

**Comment by k3b** [comment]
Is this sub-issue related to #5930 and https://github.com/mapsforge/mapsforge/issues/868 ?

**Comment by Bananeweizen** [comment]
This has been fixed in #5930 already. We just didn't have a release from the feature branch yet.
