### ISSUE TITLE
Mapsforge beta and route as straight line

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6070]
- New map active (mapsforge beta)
- Open live map
- Enable live
- Select a cache to show its popup
- Press the "route button" (circle with angled arrow)

A direct line is shown from current position to cache. 
Top shows distance, I presume it is direct distance. 
No route seems to be calculated.
![screenshot_2016-10-26-15-12-35](https://cloud.githubusercontent.com/assets/3382777/19730296/68a2a632-9ba2-11e6-9061-665f20e7efd6.png)

BRouter is installed and configured for car-test and started in server mode. BRouter has appropriate data already downloaded. Tested and confirmed working using it within OSMAND.
- in c:geo there is no indication that BRouter is detected, or even if there is such depedency. User has no way of determining if c:geo and BRouter work together or not.
- Line visual theme (simple red with slight alpha) shown from position to cache (or presumably would be route) is visually not well represented. Assume it is shown as route properly, in sample screen, it would almost be indistinguishable over the red primary roads there. 

Could be related to https://github.com/cgeo/cgeo/issues/6017

Parts of this issue were conceptually defined here https://github.com/cgeo/cgeo/issues/6033 before being discovered.

**Comment by Lineflyer** [comment]
I cannot reproduce this.
@andrixnet Are you sure you have loaded the "tiles"/maps in Brouter for the area where you try to route?

**Comment by andrixnet** [comment]
AFAIK yes. 
I can navigate using OSMAND and BRouter as routing engine.

**Comment by andrixnet** [comment]
I have retested it and I can reproduce it on 3 very different devices (1 tablet, 2 smartphones, Android 4.0, 4.2, 4.4) using 2016.11.05 build.

**Comment by andrixnet** [comment]
Same goes for the  the slow tile render

**Comment by Lineflyer** [comment]
2016.11.05 does not contain the routing feature!

**Comment by andrixnet** [comment]
![route](https://cloud.githubusercontent.com/assets/3382777/20600250/548590f4-b25b-11e6-8cc0-28bdb9d2ecfd.png)
This button appears on the top menu of cache popup window (click on cache on map) **only** when "mapsforge beta" is activated in settings->system. 
It draws a straight line from current position to the cache.

Please forgive me, but the UI is not at all self-explanatory. Reading about routing with BRouter as a new function for mapsforge beta and this button that appears only with mapsforge beta active, well ... 

Besides, if my navigation (first choice) is set to "map", it does the same, draw a straight line from current position to the cache, so having 2 buttons doing the same thing seems contradictory. 

If I have mistakenly assumed this to be routing with BRouter, then c:geo UI design and info from the internet, in part on github, have played a major role in misleading me.
My appologies for my mistake.

**Comment by SammysHP** [comment]
Nothing new that our GUI sucks. ;)

Maybe this should replaced by a toggle switch or radio button menu.

**Comment by andrixnet** [comment]
I wouldn't say it sucks ;) Mostly it is pretty intuitive but for few details here and there. 

Anyway, what exactly is the function of that button supposed to be?

**Comment by rsudev** [comment]
This new button sets the 'navigation target' on the mapsforge beta (and was there well before brouter was integrated). On the 'old' map, you have the target mode only, if you open the map for a single item (cache or waypoint). On the beta you can open the live map or any other map) and choose any of the caches or waypoints as target, giving you the straight line or route to the new chosen target.

**Comment by rsudev** [comment]
I tried to list the main characteristics in https://github.com/cgeo/cgeo/wiki/%27New-Map%27-feature-description

**Comment by andrixnet** [comment]
Thank you. Please forgive my confusion. 
Note: did you mean "live" instead of "life" on the wiki page?

**Comment by rsudev** [comment]
Of course, thanks for the feedback :)
I wouldn't say my life depends on that map (o the caches on it)

**Comment by Lineflyer** [comment]
Can we close this issue then?

**Comment by andrixnet** [comment]
Yes. I am eagerly awaiting the release with brouter functions.
