### ISSUE TITLE
Offer alternate map themes

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6071]
Offline map currently works with a builtin theme of the mapsforge library.
There are no alternate themes to choose from. 
The [FAQ](http://www.cgeo.org/faq.html#osm-use-themes) talks only vaguely about custom map themes in the sense that one would have to create his/her own theme from scratch or download from the internet themes made by others, but without any links to: 
1. custom themes known to work with c:geo
2. a guide on how to make a custom theme
3. an initial theme one could start from and customize

Additionally, there is the unknown issue about mapsforge library version and theme compatibility.

Unlike the offline map sources, which are well documented, for custom themes the user (unless well versed in OSM rendering) is left poking with trial and error approach. 

I do not believe this is beneficial for the offline map function. 

I respectfully request that even though the initial installation of c:geo contains only a default theme, a reference be made to online info described in the 3 points above such that users can customize their maps with much greater ease. 

I respectfully request that users and contributors to c:geo that already use custom themes (and by this I do not mean themes required by specific maps) to please share them.

Thank you.

**Comment by Lineflyer** [comment]
Link to #2187

@andrixnet 
Regarding your request to share themes:
Normally a map file provider should also offer matching themes. I personally use the maps of openandromaps.org together with the elevate theme they are offering.

I am with you that the default theme needs adaption once we have the new mapsforge map comes into normal operation (non beta). Establishing a guide to create custom themes however is a bit to far for c:geo itself. 

> Additionally, there is the unknown issue about mapsforge library version and theme compatibility.

Regarding that, I don't completely understand what you mean. 

Regarding the tutorials:
Feel free to make suggestions for the FAQ (which for sure has much room for improvement) via Github,

**Comment by andrixnet** [comment]
Of course I will share my findings, once I get something fully functional.

The thing about compatibility was that themes I tried so far apparently worked for mapsforge beta only.

**Comment by SammysHP** [comment]
Because they're made for the new version of Mapsforge. You'll need a different theme for each version.

**Comment by moving-bits** [comment]
Maybe we can add a short abstract about map themes to our user guide and provide links to openandromaps and elevate theme as example. This would help users getting started with themes without having to change our source code.

**Comment by moving-bits** [comment]
Meanwhile an article concerning offline maps and themes has been added thanks to @Lineflyer, therefore closing this issue now.
