### ISSUE TITLE
Store a cache from the live map also stores it in the 0th list (saved)

### ISSUE THREAD

**Issue by morice-net** [cgeo/cgeo#6078]
##### Detailed steps causing the problem:
- Go on LiveMap
- Menu > Store a cache
- Create a new "Custom list" (whatever the name) and store in it
- Wait for the loading page to end

##### Actual behavior after performing these steps:
- On live map, click on a cache (of the stored one), it shows a popup
- On the list label is written "Custom list, Saved"

##### Expected behavior after performing these steps:
- On live map, click on a cache (of the stored one), it shows a popup
- On the list label is only written "Custom list"

For instance if you remove every thing from the custom list, the icone "is stored" still appears on the cache, the trash button doesn't appear etc..

##### Version of c:geo used:
Master

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```
--- System information ---
Device: SM-J510FN (j5xnltexx, samsung)
Android version: 6.0.1
Android build: MMB29M.J510FNXXU1APG1
Cgeo version: 2016.10.20-c5d62f2 developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR
Log date format: 01/11/2016
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Installed cgeo plugins:  none
--- End of system information ---

##### Other comments and remarks:
I think this patch would fix the bug, do you agree ?
```

diff --git a/main/src/cgeo/geocaching/maps/CGeoMap.java b/main/src/cgeo/geocaching/maps/CGeoMap.java                                                                                                                           
index 42aaee5..3b05276 100644                                                                                                                                                                                                  
--- a/main/src/cgeo/geocaching/maps/CGeoMap.java                                                                                                                                                                               
+++ b/main/src/cgeo/geocaching/maps/CGeoMap.java                                                                                                                                                                               
@@ -785,7 +785,7 @@ public class CGeoMap extends AbstractMap implements ViewFactory {                                                                                                                                          
                             public void call(final Set<Integer> selectedListIds) {                                                                                                                                            
                                 storeCaches(geocodes, selectedListIds);                                                                                                                                                       
                                     }                                                                                                                                                                                         
-                        }, true, Collections.singleton(StoredList.TEMPORARY_LIST.id));                                                                                                                                        
+                        }, true, Collections.<Integer>emptySet());                                                                                                                                                            
                     } else {
                         storeCaches(geocodes, Collections.singleton(StoredList.STANDARD_LIST_ID));
                     }

```

**Comment by Lineflyer** [comment]
@morice-net 
Thanks for your report. I tried to reproduce it but failed.
Maybe there is one point in your description I don'T understand:

> - Go on LiveMap
> - Menu > Store a cache

Which way exactly you use to store a cache from the live map?

**Comment by morice-net** [comment]
Sorry I have the french version installed, but the following screenshot should help 
![bugreport](https://cloud.githubusercontent.com/assets/1290876/19920506/63c21008-a0d9-11e6-96d1-5a588aaf55cf.png)
Is it clearer with it ? 

Let me know if you need more informations.

Cheers :-)

**Comment by pstorch** [comment]
I could reproduce it. I'll look into it.

**Comment by pstorch** [comment]
@morice-net your suggestion was right. You could've sent it as a pull request ;)

For a moment I was thinking about preselecting the default list `Stored`, but changed my mind. Because we also have an extra issue for preselecting for new caches #5975. With the PR #6080 the behavior is now the same as when storing new caches from the cache details page.

When working on #5975 we have to remember that there are two places which are affected.
