### ISSUE TITLE
Glitch in personal note coord parsing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6090]
##### Detailed steps causing the problem:
- Cache saved with empty personal note
- Edit note and insert (note the accidental empty space between minutes and seconds in latitude):
```
N12 34. 567
W001 23.456
```
- Save the note
- Swipe to the waypoint tab

##### Actual behavior after performing these steps:
A waypoint is created from the personal note but uses N12 34.567, E007 00.000

##### Expected behavior after performing these steps:
Wapoint coords should be identical to those in personal note

##### Version of c:geo used:
2016.11.05

##### Is the problem reproducible for you?
Yes

**Comment by UniQP** [comment]
Might be related to the whitespace changes of gc.com.

If it is not urgent, I can take a look in December (unfortunately too busy this month) in the context of improving the parser to fix #5338.
