### ISSUE TITLE
Routing hard to see

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6094]
With the theme I use the routing is sometimes hard to see. We need a different kind of painting.

**Comment by Bananeweizen** [comment]
Example
![screenshot_20161106-164257](https://cloud.githubusercontent.com/assets/406876/20039204/6fec96f4-a440-11e6-8515-5f70d842db68.png)

**Comment by Lineflyer** [comment]
Also mentioned in #6070
