### ISSUE TITLE
GC2CJPF has been archived: causing some tests to fail

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6095]
Cache https://coord.info/GC2CJPF has been archived and causing these tests to fail:

```
21:29:55  
21:29:55  cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeBasis[emulator(AVD) - 6.0] [31mFAILED [0m
21:29:55  	org.junit.ComparisonFailure: [Cache GC2CJPF: archived] expected:<[fals]e> but was:<[tru]e>
21:29:55  	at cgeo.test.Compare.assertCompareCaches(Compare.java:25)
21:29:59  
21:29:59  cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeNotLoggedIn[emulator(AVD) - 6.0] [31mFAILED [0m
21:29:59  	java.lang.AssertionError:
21:29:59  	Actual and expected should have same size but actual size is:
21:30:06  
21:30:06  cgeo.geocaching.CgeoApplicationTest > testSearchByViewport[emulator(AVD) - 6.0] [31mFAILED [0m
21:30:06  	org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
21:30:06  	at cgeo.geocaching.CgeoApplicationTest$6.run(CgeoApplicationTest.java:317)
21:30:15  
21:30:15  cgeo.geocaching.connector.gc.GCBaseTest > testSearchFromMap[emulator(AVD) - 6.0] [31mFAILED [0m
21:30:15  	org.junit.ComparisonFailure: [Cache GC2CJPF: disabled] expected:<[fals]e> but was:<[tru]e>
21:30:15  	at cgeo.test.Compare.assertCompareCaches(Compare.java:24)
21:31:45  :main:connectedBasicDebugAndroidTest FAILED

```

Now we have only archived Mocked Caches for tests. I think it would be good to have a new active Cache added to our Mocked Caches for testing.

**Comment by Lineflyer** [comment]
Feel free to take some of my owned caches (except GC24JDQ) if this helps.
Of course they might also change their status, but at least I know when this happens and can tell you.

**Comment by Lineflyer** [comment]
I do still see a failing test because of this cache in:
http://ci.cgeo.org/job/cgeo%20pull%20request/609/console

from today.

**Comment by pstorch** [comment]
@Lineflyer ci fails because it is a PR for branch `release`. The fix for this was done in branch `master`.

**Comment by Lineflyer** [comment]
That explains..So in case of this PR it should just be based on master, shouldnt it?

**Comment by Lineflyer** [comment]
Do we need to apply this fix to `release`?

**Comment by pstorch** [comment]
@Lineflyer if we want to have green builds on `release` branch, then yes. I could do a cherry-pick from master, if needed.

**Comment by Bananeweizen** [comment]
Since branches have been updated, the release tests are now green again. Closing.
