### ISSUE TITLE
Rounding error near "minute confluence"?

### ISSUE THREAD

**Issue by steve8x8** [cgeo/cgeo#6098]
##### Detailed steps causing the problem:
- Open a cache
- Move to  East xx° yy'.998 from West
- Swipe to waypoints
- "Add Waypoint", select DD MM.MMM format
- Now move further to East

##### Actual behavior after performing these steps:
- Display will eventually show xx yy.000 (and a WP taken will be >1 km off)

##### Expected behavior after performing these steps:
- Expected: yy gets incremented (and WP reflects current position)

##### Version of c:geo used:
2016.07.09-NB.34c95b1

##### Is the problem reproducible for you?
It's a bit tricky because is apparently only happens at xx yy.999[5-9] and with very good GPS reception

##### System information:
OnePlus (A0001, bacon)
6.0.1 MHC19Q

##### Other comments and remarks:
This looks quite similar to Issue #2624 - but this time, for minutes

**Comment by samueltardieu** [comment]
Indeed. The fractional minutes part is rounded and taken modulo 1000 indepently of the integral minutes part. It leads to a minute of yy.9995 and above to be rounded to yy.0000.
