### ISSUE TITLE
Remove fastest strategy on live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6106]
I suggest to remove the selectable live map strategy for the following reasons:

- Users I spoke with are not even aware of this option 
- Users I spoke with always prefer to see the cache type and get most information out of the map
- Networks have become faster
- There are often users on support and in ratings claiming that they only see ?? caches as they accidentally selected "Fastest" thinking it would be the same but just faster

- Make things simpler, less options

The speed dependent solution (Current default) should be the fixed strategy.

**Comment by SammysHP** [comment]
- Is incremental update used? (That means: Are caches already shown although tiles (or search) are not loaded yet?)
- Is the request aborted if the area was moved outside of the visible area?

Then it should be no problem to remove the strategies.

**Comment by Bananeweizen** [comment]
I thought of suggesting the same when I noticed that you are answering support requests by asking for that option. I've never changed it myself and also never saw the need.

**Comment by rsudev** [comment]
I am fine with removing it from the menu - I use it also only once, to switch it to fast, because that isbin my book the only sensible setting ...
So I'd like to retain the ability to not do a nearby search on the live map.

**Comment by Lineflyer** [comment]
The compromise here would be at least to remove "Fastest" as this is the mode which confuses most users. The visual and functional difference between "Fast" and "Detailed" is nothing which looks like an error for the user.


Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Michael Keppler <notifications@github.com> Datum: 12.11.16  10:14  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Author <author@noreply.github.com> Betreff: Re: [cgeo/cgeo] Suggestion: Remove live map strategies (#6106) 
I thought of suggesting the same when I noticed that you are answering support requests by asking for that option. I've never changed it myself and also never saw the need.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bananeweizen in #6106: I thought of suggesting the same when I noticed that you are answering support requests by asking for that option. I've never changed it myself and also never saw the need."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/6106#issuecomment-260111163"}}}

**Comment by Lineflyer** [comment]
If anyone has time for it:
Feel free to remove the "Fastest" strategy as this seems to be the consens here.

**Comment by pstorch** [comment]
@Lineflyer on `release` or `master`?

**Comment by Lineflyer** [comment]
As I see you already submitted a PR against `release` I am fine with that (was undecided before) ;)

**Comment by Lineflyer** [comment]
Confirmed working (including fallback from fastest to auto on upgrade) with 2016.01.09-NB1
