### ISSUE TITLE
Login fails, c:geo reports maintenance

### ISSUE THREAD

**Issue by steve8x8** [cgeo/cgeo#6109]
##### Detailed steps causing the problem:
- cannot login to GC anymore using old nightly
- upgrade to latest (2016.11.11) nightly
##### Actual behavior after performing these steps:
- still login to GC fails, main screen reports maintenance
- web interface has no hint on maintenance
##### Version of c:geo used:
2016.11.11 nightly
##### Is the problem reproducible for you?
Yes
##### System information:
A0001
##### Other comments and remarks:
Since GeoToad also fails, there seems to be a change in cookie handling(?)

**Comment by SammysHP** [comment]
There is no "change in cookie handling". It's just that gc.com is broken since 7:00 UTC this morning. Thus we enabled the notification - and still get reports.

**Comment by mucek4** [comment]
For me login started working.

**Comment by rsudev** [comment]
GS back to normal, closing here.

**Comment by steve8x8** [comment]
Login is OK again, but the maintenance message persists (I presume it's not generated by the app itself then?).
Please close.

**Comment by rsudev** [comment]
The message is generated by the app based on a status it retrieves from status.cgeo.org. The status notification has been closed, but the app might not have picked that up yet. If you close/stop the app and re-start it, the notification will vanish.
