### ISSUE TITLE
Inaccurate projection

### ISSUE THREAD

**Issue by ExTechOp** [cgeo/cgeo#6123]
##### Detailed steps causing the problem:
- create point N60° 00.000' E024° 00.000'
- project from it 45° and 1000m

##### Actual behavior after performing these steps:
- c:geo creates new point at N60° 00.382' E024° 00.763'

##### Expected behavior after performing these steps:
The following three implementations of WGS84 ellipsoid projection using different code bases seem to agree with each other and disagree with the c:geo implementation. There is an difference of 0.001'/0.003' which is already a couple of meters even at this short distance.

http://williams.best.vwh.net/gccalc.htm
Great Circle Calculator by Ed Williams (javascript)
Compute lat/lon given radial and distance from a known point, WGS84 earth model
N60:00.3808 E024:00.7605

http://gc.pitko.net/cal/gcal.pl
Spitko's GeoCalc (perl Geo::Ellipsoid)
N60 00.381 E24 00.760

http://xiit.dy.fi/gc/
GeoCalcing² by zuge (GeographicLib http://geographiclib.sourceforge.net/)
Projections
N 60 00.381 E 024 00.760

##### Version of c:geo used:
2016.11.05

##### Is the problem reproducible for you?
Yes, also on earlier releases

##### System information:
--- System information ---
Device: Jolla C (Jolla C, Jolla)
Android version: 4.4.4
Android build: KTU84Q dev-keys
Cgeo version: 2016.11.05
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Log date format: 13/11/2016
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed cgeo plugins:  none
--- End of system information ---

##### Other comments and remarks:

**Comment by SammysHP** [comment]
Our ellipsoid is a sphere. :)

**Comment by ExTechOp** [comment]
In Jamie Hyneman voice: Well, there's your problem.

Seriously, how could we improve this? The above mentioned GeographicLib code is available directly in Java, C and Python, and of course the sphere is a special case of an ellipsoid so even the original results could be selected.

**Comment by ExTechOp** [comment]
Excellent! Looking forward to seeing this code in a build version.

**Comment by samueltardieu** [comment]
Thanks for the report @ExTechOp.
