### ISSUE TITLE
Font-size too big / ignoring Android 6 size settings

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#6127]
##### Detailed steps causing the problem:
I am testing a new Android Device (BV6000, 4,7" screen, 312dpi, 1280 x 720 pixels) in the moment and several font sizes in c:geo are displayed much to big. I will attach some screenshots with overlapping texts.

Its an android 6 device and I noticed Android got a general text sice setting in the meantime (settings>display>fontsice). I am using the setting "normal" but I also noticed that c:geo is ignoring this size settings completly.

##### Version of c:geo used:
2016.11.05

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: BV6000 (Blackview, Blackview)
Android version: 6.0
Android build: BV6000_Blackview_V01_20161011
Cgeo version: 2016.11.05
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 15.11.16
Debug mode active: no
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: d.M.yyyy
Installed cgeo plugins: calendar, contacts
--- End of system information ---
```

##### Other comments and remarks:
![2016-10-31 20 49 47](https://cloud.githubusercontent.com/assets/2893036/20320131/1806b298-ab71-11e6-9d80-9395f6e991fd.png)
![2016-11-02 19 47 16](https://cloud.githubusercontent.com/assets/2893036/20320132/180b2ba2-ab71-11e6-88b1-36ef416d3bd2.png)
![2016-11-15 19 16 21](https://cloud.githubusercontent.com/assets/2893036/20320133/180f862a-ab71-11e6-9dcc-2b42492a5981.png)

**Comment by Lineflyer** [comment]
Link  to #6011

**Comment by gcPhil** [comment]
An Android 7 Update is announced to be published shortly for the bv6000. I will report if that change anything. But since all other apps I have installed use correct font size I don't guess it will be correct in c:geo then.

**Comment by gcPhil** [comment]
I received the android 7 Update. The font size in c:geo is now normal again and not to big. But it still don't change with Androids font size settings.

**Comment by Lineflyer** [comment]
The problem of not following system font size setting is in #6011 therefore I am closing this.
Feel free te reopen if you dont agree.
