### ISSUE TITLE
Have NOJIT release version

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6128]
Asked by a user on FB:
Currently we have the nojit-version only for our nightlies.
As the underlying bug is still not fixed on those devices (e.g. Lenovo) and if we want to offer a stable version also for users affected, it might be meaningful also to have a nojit version based on `release` (which each release cycle).

If this is feasible by "just" creating a new CI job I would support this request.

Note:
- FAQ needs to be adapted accordingly once it is available.
-  If we would have a nojit-version based on `release` we could stop having it for the nightly instead

**Comment by Bananeweizen** [comment]
You are only thinking of producing that additional APK, you are not thinking of somehow managing two APKs in parallel in the play store, right? I'll look into it.

**Comment by Bananeweizen** [comment]
I've changed the release job to include assembleNojitRelease and to upload cgeo-nojit-release.apk. However, since I don't want to actually trigger a release upload to the website, I've not tested this. So there might be errors to be fixed when we actually create the next release.

**Comment by SammysHP** [comment]
I think @Lineflyer meant just an additional apk on the website, but no push to Google Play.

**Comment by Lineflyer** [comment]
Yes. Same as we have now but based on release and triggered while 
building one (in dedicated or same job).
So what @Bananeweizen did seems perfectly fine.

I'll keep this open until next release as I also need to change the link 
from FAQ then.

**Comment by Lineflyer** [comment]
FAQ changed and NOJIT release version released.
