### ISSUE TITLE
DataStore.cleanIfNeeded() search for `detailed < timestampString`

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6129]
While looking through the DataStore claas I stumbled upon this code block in `cleanIfNeeded()` method:

```
                    if (version != Settings.getVersion()) {
                        queryToColl(dbTableCaches,
                                new String[]{"geocode"},
                                "geocode NOT IN (SELECT DISTINCT (geocode) FROM " + dbTableCachesLists + ")",
                                null,
                                null,
                                null,
                                geocodes,
                                GET_STRING_0);
                    } else {
                        final long timestamp = System.currentTimeMillis() - DAYS_AFTER_CACHE_IS_DELETED;
                        final String timestampString = Long.toString(timestamp);
                        queryToColl(dbTableCaches,
                                new String[]{"geocode"},
                                "detailed < ? AND detailedupdate < ? AND visiteddate < ? AND geocode NOT IN (SELECT DISTINCT (geocode) FROM " + dbTableCachesLists + ")",
                                new String[]{timestampString, timestampString, timestampString},
                                null,
                                null,
                                geocodes,
                                GET_STRING_0);
                    }
```

If we have a version upgrade, we select all caches not on any list. If it is the same version we select caches not on any list and not updated or logged since DAYS_AFTER_CACHE_IS_DELETED. Additionally in the second select there is also the `detailed` column which is also compared to the `timestampString`. `detailed` can have the values `0` and `1` and therefore is always lower than a timestamp.
I guess we can remove the `detailed` column from the where clause.

The second question is: shouldn't we always use the second version? Why should we remove temporary caches on a version upgrade faster than normal?

**Comment by Lineflyer** [comment]
Is this related to #5125 ?

**Comment by pstorch** [comment]
@Lineflyer maybe. I came across this while searching for #5125. At least this is the houskeeping method which is started when c:geo is started. 
But a few lines later, it excludes caches which have offline logs. That's why I didn't mentioned it in the other issue and opened a new one.

**Comment by samueltardieu** [comment]
Interesting, this code comes from the initial version of cgeo (when it has been opensourced).
