### ISSUE TITLE
Strings seem confused after rename of opencaching.org.uk

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6131]
While I can see that with https://github.com/cgeo/cgeo/commit/d95ffe131e21ecacd05242c6a1682a67ba8076f2 @Bananeweizen also adapted all the strings I do still see "opencaching.org.uk" shown in Menu -> Settings -> Service in my (german) installation.

Maybe its logical, but to me it looks unlogical.

**Comment by rsudev** [comment]
I guess this will be fixed by todays translation import.

**Comment by Lineflyer** [comment]
Indeed! Verified with 2016.11.17-NB1
