### ISSUE TITLE
Queue offline personal note updates

### ISSUE THREAD

**Issue by tkuhrich** [cgeo/cgeo#6139]
It would be nice when caching in remote areas where cell reception is on again off again, that when you hit upload on the personal note page, that it is queued up to send when you get back into cell reception.

Currently, the only way to know if it was sent or not, is if GC.COM is missing a personal note.

**Comment by Lineflyer** [comment]
I am afraid that this fits more into a general discussion regarding offline behaviour of c:geo. 
Let me therefore go more into the direction to ask you, why you can't see whether it is uploaded or not (e.g. on flawky network connection)?
AFAIK there should be a toast message shown with either success or failure (as it is in fact done in the background)

**Comment by Lineflyer** [comment]
Closing due to lack of feedback.
