### ISSUE TITLE
Login failed or stuck for OC sites

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6145]
Started after upgrading from two days old nightly.
In settings authentication is ok but still shown failed on main screen.

Will provide log later.

**Comment by Lineflyer** [comment]
So here are more details:

The problem is reproducible for me starting with 2016.11.19-NB

Interestingly the symptoms are different depending on whether debug logging is active or not:
- Debug logging active: On main screen the login for all OC sites seem stuck ("Anmeldung...")
- Debug logging not active: On main screen the login shows failed for all OC sites ("Anmeldung fehlgeschlagen")

The system log shows the same in both cases and for all OC-connectors:
```
20:58:40.241 Error cgeo 4662  [network--6] OkapiClient.getUserInfo: error getting user info: 'Invalid signature.'
```
My amateur idea why this is happening:
@samueltardieu changed some things from HTTP to HTTPS. Is this causing the login problems?
@samueltardieu changed something in network handling with respect to debug logging active or not. Could this cause the problem or at least the different UI status depending on debug log setting?

Side note:
Authentication to oc.us was not working at all. Maybe the site is down or it is also related. I will check and open a dedicated issue if needed.

**Comment by rsudev** [comment]
Bisecting the latest history it was straightforward to identify 085ce7319c74a8dc2ea22dedc158e258e7dde154 as the culprit. But it is not the switch to https as such which broke the OKPAPI but seemingly a side-effect on the outh-signed communication.
Investigating.
