### ISSUE TITLE
send2cgeo - Stuck on multi cache import

### ISSUE THREAD

**Issue by bockyPT** [cgeo/cgeo#6146]
##### Detailed steps causing the problem:
- On my PC I added a bunch of caches to the "send2cgeo" import queue;
- On my Android 6 phone I tried to import them to a list;

##### Actual behavior after performing these steps:
- It imported a lot of caches correctly, but is now stuck on cache GC11CPZ - maybe it's related to its name starting with a "#"?

##### Expected behavior after performing these steps:
- Every cache should be properly imported.

##### Version of c:geo used:
2016.11.05

##### Is the problem reproducible for you?
Yes

##### System information:
Browser: Chrome 54.0.2840.71 m (64-bit)
Extension: Tampermonkey 4.1.10 with Send to c:geo 0.37
Phone: Xiaomi Redmi 3S Prime running Android 6.0.1 MMB29M (MIUI 8 Global 6.9.8 Beta)

**Comment by Lineflyer** [comment]
I could not find any problem while trying to reproduce this issue.
Also GC11CPZ was handled normally using send2cgeo.

@bockyPT  
You are writing it is reproducible for you?! How many caches did you queue up in total? Did you start the import only after queueing the caches or in parallel to sending them?

Please be aware that importing depends on some external factors like network connection availability, website availability, which I would assume more likely to be the reason for such a problem.

**Comment by Lineflyer** [comment]
Closing due to lack of feedback from submitter.
