### ISSUE TITLE
Authentication and communiction to opencaching.us not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6147]
##### Detailed steps causing the problem:
- Trying to authenticate to OC.us fails with a toast, that the process can not be started
- OC.us website is up and seems working normally
- Log is showing a normal (status 200) respsonse from opencaching.us

##### Version of c:geo used:
2016.11.19-NB

##### Is the problem reproducible for you?
Yes

**Comment by Lineflyer** [comment]
Also the website tests on CI are failing for oc.us

**Comment by samueltardieu** [comment]
I cannot test right now, but if this is needed let's invite sites to switch to or properly configure https.

**Comment by rsudev** [comment]
It looks like tho OKAPI on oc.us is broken right now:
```
...
Oops... Something went wrong on *our* part. Message was passed on to the site administrators. We'll try to fix it. Contact the developers if you think you can help!
```

**Comment by Bananeweizen** [comment]
I've posted that to their forum, since there was no open topic about that yet.

**Comment by samueltardieu** [comment]
> I've posted that to their forum, since there was no open topic about that yet.

Could you share the URL? I can't find it on the forum.

**Comment by SammysHP** [comment]
That topic was deleted last night.

**Comment by samueltardieu** [comment]
Do we know why?

**Comment by Bananeweizen** [comment]
I find it rather anti-social to delete such a post from their forum without any explanation. Makes me feel like deleting the OS.US connector from cgeo without any explanation...

**Comment by Lineflyer** [comment]
I also answered in this posting, that we are able to help them with contacts to oc.pl or oc.de in case of need. Some hours after it was deleted.

**Comment by SammysHP** [comment]
Also the article in their news was replaced. Now they say that everything (including c:geo!) works again. Can someone test?

**Comment by rsudev** [comment]
Just checked it. Could authorize and get user info -> works!
