### ISSUE TITLE
Zoom factor not consistent between maps and map sources

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#6149]
When switching between mapsforge beta offline and other map sources or maps, the zoom factor is not consistent. The mapsforge beta offline is much more zoomed in.

**Comment by Matze2** [comment]
So here are my first findings. Here are three screenshots of the Live Map with the following sources:
- Google Maps
- Freizeitkarte_BAYERN with theme freizeitkarte-v5.xml
- Openandromaps Bayern with theme Elevate_Hiking_XL.xml

Here are my findings:
- As soon as the Map is switched the OSM maps do not show caches anymore
  - even moving or zooming in/out to a limited extend to force a refresh does not help
  - a big zoom out shows the caches again at a certain level
  - Google Map keeps the caches
- the zoom between the OSM based maps stays the same; it differs from Google Maps; 
  - the zoom center seems to be stable

Experimenting with extreme zoom in/out and switching maps leads to some other interesting effects, e.g. caches are shortly shown and then hidden.

Personally I see the inconsistent zoom not that critical. The fact that caches are not shown after switching maps is more annoying.

![screenshot_2018-02-15-08-53-54](https://user-images.githubusercontent.com/12542802/36246204-f1f32b9c-122e-11e8-840a-8d5db9a20f72.png)
![screenshot_2018-02-15-08-53-33](https://user-images.githubusercontent.com/12542802/36246209-f7be80e4-122e-11e8-9034-f0f6e175f220.png)
![screenshot_2018-02-15-08-53-03](https://user-images.githubusercontent.com/12542802/36246211-fb1a5e20-122e-11e8-8905-e3e381d59d12.png)

**Comment by Matze2** [comment]
The issue with different zoom levels are independent of the Mapsforge version.
The disappearance of cache icons on map source switch do not occur with the "Old Mapsforge V3" mode.

**Comment by Lineflyer** [comment]
@Matze2 

> The disappearance of cache icons on map source switch does not occur with the "Old Mapsforge V3" mode.

Thanks for your feedback. Can you open a dedicated issue for this problem please?

**Comment by Matze2** [comment]
Yes, will do tonight.

**Comment by pstorch** [comment]
BTW: we also have the new Google Maps v2 PR open: #5973 
Does it make sense to integrate it first and fix the zoomlevel then? Otherwise there might be another difference, then we have to fix it twice. On the other it might be a bigger risk.

**Comment by Lineflyer** [comment]
I have no idea about the quality of the Maps V2 PR?

My personal opinion would be, first to finish the current step (and focus on fixing the corresponding issues) and to tackle Maps V2 as next major change in the maps section only afterwards.

Still we could for now just ignore the zoom factor difference and only fix it, once the new Google Maps are in.

**Comment by GodfatherThe** [comment]
Not sure is this issue a correct place or not, but with new (==now default) maps I cannot zoom out more than for "10km" in a ruler at left-bottom. Often I want to have big view for the whole country (since I'm mostly SU user with not so big amount of caches in total) and now I cannot :(

**Comment by rsudev** [comment]
After researching for a while, I think I now know the background for this issue.
The zoom level relates to the tile the map is drawn with.
- Google map always uses tile size 256
- Mapsforge online always uses tile size 256
- Mapsforge offline uses a tile size depending on the the resolution (I tested mdpi through to xxhdpi):
  - Minimum (up to hdpi) is 256
  - xhdpi 512
  - xxhdpi 768
In addition is there an offset of 1 between Google and Mapsforge (Google starts at 1, Mapsforge at 0).
The problem now is, that the zoom levels do not fully align, depending on the tile size. For Tile size 768, the zoom level difference is 1.5 (which is not possible to achieve as it is an integer).
I think I'll stick with rounding up in this case, let's see how it looks like in action than.

**Comment by Lineflyer** [comment]
Following up in #7750
