### ISSUE TITLE
GPX format issue

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6152]
A user contacted us on support with a question I cannot answer.

He said, that a GPX file with version 1.1 would not import into c:geo (I confirmed that).
Here is an example file:
https://www.dropbox.com/s/26ute3tb35brb9p/gpx_test.gpx?dl=0

Only after converting it to version 1.0 it can be imported into c:geo.
The conversion was done with RouteConverterWindows.
Here is the resulting file which imports fine in c:geo:
https://www.dropbox.com/s/8lu084smmnz6yiw/gpx_test_10.gpx?dl=0

Can someone explain to me the difference and why we cannot import the first file?

**Comment by Bananeweizen** [comment]
It's always the same reason if gpx files cannot be imported in cgeo: It's not valid XML. Run the first one through a validator (even Notepad++ has one included) and it will complain about the file being invalid.
