### ISSUE TITLE
BRouter: UI implementation suggestion

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6154]
Beta feedback from Google Play regarding 2016.11.21-RC:

The new routing feature with BRouter is interesting and I like the concept, but the red direction lines are very choppy/blocky looking (not smooth at all) and also are not transparent, so they block street names and other map landmarks. Also, now that I downloaded this feature, I'm not sure how to get the "as the crow flies" navigation line back.

**Comment by rsudev** [comment]
I also think having straight line as an option even with brouter installed is useful.
The main question is, where to integrate the selection and how to make it understandable.
Is this something you rather select once in the settings, or something you might want to switch on and off in the map on a case-by-case basis?

**Comment by Bananeweizen** [comment]
Just a fourth option in the routing (walk, bike, car, straight line) seems most simple to me.

**Comment by rsudev** [comment]
After writing this, I came across the routing menu and had the same thought. I started implementing it directly and would suggest to put it on release, ok?

**Comment by Lineflyer** [comment]
+1

**Comment by rsudev** [comment]
I have created an implementation based on release. @Lineflyer Should I merge to master first for testing?

**Comment by Lineflyer** [comment]
Release is fine as well


Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: rsudev <notifications@github.com> Datum: 01.12.16  15:27  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Mention <mention@noreply.github.com> Betreff: Re: [cgeo/cgeo] BRouter: UI implementation suggestion (#6154) 
I have created an implementation based on release. @Lineflyer Should I merge to master first for testing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rsudev in #6154: I have created an implementation based on release. @Lineflyer Should I merge to master first for testing?"}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/6154#issuecomment-264186169"}}}
