### ISSUE TITLE
Direction line not shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6156]
Beta feedback on Play:

Direction line to cache is no longer shown

Will ask for more details.

**Comment by Lineflyer** [comment]
Confirmed with current master:
- Disable or uninstall brouter
- Open cache details
- Select Navigate - Map
- No direction line shown on map although setting is active

**Comment by Bananeweizen** [comment]
I think I accidentially broke that when I removed the artificial line from current position to first point calculated by routing. Will move the straight line part directly into the routing calculation.

**Comment by Lineflyer** [comment]
Please be kindly reminded to fix on release.
