### ISSUE TITLE
Enable brouter for distance >10km

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#6157]
##### Detailed steps causing the problem:
I tried the new BRouter feature in the latest Beta and noticed it is only working for a short distance navigation. When I try it for caches further than 8-10 km away I get a map showing the destination cache but without guiding lines.

There seems not to be a fixed reproducible distance, I guess it depends on route complexity. I have no Idea if this is a known BRouter limitation or a bug in c:geo implementation but I read that BRouter can provide "long distance cycle routes" so I guess it's the second.

A last general feedback I like to give for BRouter: I love the possibility to route to a cache inside c:geo but I also noticed that BRouter itself don't feel very user friendly in the moment. It uses a unusual UI and users have to read different readme files that can be found inside the brouter folder on the phone storage to get it work like it should.

##### Version of c:geo used:
2016.11.21-RC

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: BV6000 (Blackview, Blackview)
Android version: 6.0
Android build: BV6000_Blackview_V01_20161011
Cgeo version: 2016.11.21-RC
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 23.11.16
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: d.M.yyyy
Installed cgeo plugins: calendar, contacts
--- End of system information ---
```

**Comment by Lineflyer** [comment]
This might be the combination of two issues:
1. There is a fixed limitation of maximum route length where routing is used (@Bananeweizen will know the max. distance)
2. While you are trying to reproduce you might refer to the distance shown in the upper right (but this is the straight line distance but not the routed distance). So it might not be the trigger value used to decide whether routing is used or not
3. The fact that you dont see any guidance line (neither straight nor routed) is #6156 I guess

**Comment by gcPhil** [comment]
- When I read the BRouter Dokumentation I saw a limitation of a route around 50km cose of a timeout of 1minute calculation. That sounds much more than possible with the straight line distance of 10km. I guess something else is not working.

- Below the ~10km straight distance routing guidance lines work well for me so I am really not sure if it can be the same as #6156

**Comment by andrixnet** [comment]
One more fact: 
- I've requested a cache 400km away. No route is calculated.
- I've asked OsmAnd to route to the same destination, using BRouter as routing service. It works.

**Comment by Lineflyer** [comment]
Addon: The maximum routed distance is set to 10km at the moment.

We could consider to increase that, however we have to consider the calculation speed while doing that.

From users perspective I assume most people use this feature for rather walking or biking. For driving I think most people would rather use a turn-by-turn nav tool.

So I guess having a limit like 400km is too much.

**Comment by gcPhil** [comment]
- Isn't it possible to set a maximum of calculating-time instead of distance?
- I would prefer a status message if the calculation is not possible/aborted cos of any kind of limitation. 
- I can imagine to use this also for car navigation in a limited radius (if I don't need traffic advice for my area). Starting the BRouter navigation on the map is much faster than starting an external app like navigon for every cache.
- I am doing bike-tours up to 100km/day for geocaching. So I don't like the 10km-limitation if not absolutely necessary.

**Comment by andrixnet** [comment]
On my device render performance of mapsforge beta is a much worse annoyance factor then waiting an additional 1-2 seconds for a route calculation (which inherently is assumed to potentially take just a bit more then a fraction of a second).
BRouter performance is OSMand is excellent (tested on my example above)

- if I have this function in c:geo it seems counter productive to manually set the cache position as destination in another navigation app, as gcPhil says, assuming I don't really need things like voice guidance and such

**Comment by Lineflyer** [comment]
Renaming as a feature request to increase the brouter navigation limitation of 10km.

**Comment by moving-bits** [comment]
I did some testing with the emulator: Pushing the limit to 100 or something km is easy enough, and c:geo works as expected - drawing a straight line to the cache if more than 100 km direct distance, and calculating the route if less.

But: At least when using the emulator calculating the route for 70 or 90 km needs some time (10-20s) - I'm not sure if everybody is willing to spend this time for displaying such a cache on default. Thus I suggest making it a configuration option with default 10.0 km, upper limit 200.0 km (or so). That wise everybody could set this option according to his/her needs (and phone cpu power).

What do you think?

And if ok: Can somebody point me into the right direction how to implement a configuration setting like this? Thx.

**Comment by moving-bits** [comment]
current status: see PR 7227 for this one - technically done and working, but Codacy complains about one undocumented function
