### ISSUE TITLE
Teracaching GPX: Pictures not loaded

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6158]
- Import this file:
https://www.dropbox.com/s/ys2gaunio7p09u9/Cache%20-%20TC9KV.gpx?dl=0
- Open the imported cache TC9KV 
- Swipe to pictures tab

Pictures are not loaded
From what I can see in the GPX there are valid URLs for the pictures though.

**Comment by rsudev** [comment]
I checked two of the urls (without importing), they return 404 for me.

**Comment by Bananeweizen** [comment]
Same 404 here. Also having the host directly in the URL seems wrong to me.

Hard to find a counter example, but at least I can see that inline images work as expected in TC7UQU.
