### ISSUE TITLE
LOC files always imported to standard list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6164]
##### Detailed steps causing the problem:
- Create a new list
- Select import and select a loc file (in my case it contained 25 gc benchmarks)

##### Actual behavior after performing these steps:
Waypoints are imported to default list

##### Expected behavior after performing these steps:
Waypoint should be imported to active list

##### Version of c:geo used:
2016.11.26-NB

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
I can have a look

**Comment by Lineflyer** [comment]
Your PR looks quite general from what it looks like...as far as I know GPX imports have been OK, or not?

**Comment by pstorch** [comment]
@Lineflyer the `store()` method I changed was only used by the `LocParser`. The import of GPX files is using another method and is not affected by this change. I crosstested it anyway and GPX import is working, too (as it was before).

**Comment by Lineflyer** [comment]
Top!
