### ISSUE TITLE
Contents of 'History' tab.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6167]
Sonething odd has happened to the caches in the 'History' tab.
It used to show caches in the order that I last viewed or logged them, now it just seems to be some random collection. The caches that I have logged earlier today don't even appear in it.

I tried the 'Clear history' option, it now says 'History, 5 caches' but only show four.

![screenshot_20161129-163028](https://cloud.githubusercontent.com/assets/7459480/20718783/c34adc66-b651-11e6-9942-b985bca944dc.png)

##### Version of c:geo used:
2016.11.28-RC

##### System information:
```--- System information ---
Device: E6683 (E6683, Sony)
Android version: 6.0.1
Android build: 32.2.A.0.253
Cgeo version: 2016.11.28-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Log date format: 29/11/2016
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by alan666notb** [comment]
I just noticed that those caches also have a 'Saved log' present even though I have logged them as 'found'

**Comment by Lineflyer** [comment]
We are working on this problem in some other dedicated issues: #6185 #5949, #6186
