### ISSUE TITLE
Bug: Layout of base screen moves up after searching/selecting a listing

### ISSUE THREAD

**Issue by stephanBoehme** [cgeo/cgeo#6169]
##### Detailed steps causing the problem:
- Select the the search input field (near the magnifying glass)
- Type in a name of a cache that is saved locally
- Select a cache from the suggestions by tapping on it

##### Actual behaviour after performing these steps:
- The layout of the screen is moved half a screen length upwards
- Then the selected cache listing is opened

##### Expected behaviour after performing these steps:
- No change of the layout

##### Version of c:geo used:
- 2016.11.28-RC

##### Is the problem reproducible for you?
- Yes, behaviour is reproducible.

##### System information:
```
--- System information ---
Device: SM-G920F (zerofltexx, samsung)
Android version: 6.0.1
Android build: MMB29K.G920FXXS4DPJ5
Cgeo version: 2016.11.28-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 30.11.16
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: d.MM.yyyy
Installed cgeo plugins: calendar
--- End of system information ---
```

##### Other comments and remarks:
If nothing is typed in before selecting a listing the layout doesn't jump up.

**Comment by Bananeweizen** [comment]
This is not restricted to the search, since I've seen the same when switching activities. I'm not sure, but I think the activity transition animation is basically stopped somewhere in the middle.

**Comment by Lineflyer** [comment]
Can anyone still see such kind of activity transition?
Either my device is to fast or this might be solved implicitly by one of the many changes.
