### ISSUE TITLE
GSAK open c:geo database in macro

### ISSUE THREAD

**Issue by ubuster** [cgeo/cgeo#6172]
I can export caches or any data from c:geo in any format in text file. There is no problem.
The App GsakSqlite can open a c:geo database as well. And my question is: Is there any possibility in macro open in one step a c:geo database and in another step write data in GSAK database?

**Comment by ubuster** [comment]
I can export caches or any data from c:geo in any format in text file. There is no problem.
The App GsakSqlite can open a c:geo database as well. And my question is: Is there any possibility in macro open in one step a c:geo database and in another step write data in GSAK database?

**Comment by Bananeweizen** [comment]
We have no support of GSAK and don't plan anything there either. You should ask at their side.

**Comment by ubuster** [comment]
Don't be angry with me. Just for question to the others.

**Comment by Bananeweizen** [comment]
I'm not angry, I just mention some facts. :) With purely textual communication it is hard to get understood the same way one meant to write in the first place.
