### ISSUE TITLE
Cache type parsing from live map broken

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6175]
##### Detailed steps causing the problem:
- Open live map 
- Set Strategy to "Fast" to have a clear view on the issue (no nearby search performed additionally)

##### Actual behavior after performing these steps:
Cache type parsing is wrong in most cases:
- Mystery is detected as Wherigo
- Traditional is detected as Multi
- Multi is detected as Earth

Parsing might be unpreditable as the icons have changed on the website.
Refer to [website release notes](http://forums.groundspeak.com/GC/index.php?s=19bca112f771f2123053d249fadc8e06&showtopic=342292)

##### Expected behavior after performing these steps:
Correct parsing

##### Version of c:geo used:
2016.11.05
2016.11.28-RC
Current nightly

##### Is the problem reproducible for you?
Yes

**Comment by kumy** [comment]
Shouldn't we post a notification for that?

**Comment by rsudev** [comment]
This is the domain of @mucek4 
IIRC he generated the decision code with a neural-network based tool

**Comment by Lineflyer** [comment]
I will create a FAQ entry and post a custom notification with a link to the FAQ entry.

**Comment by samueltardieu** [comment]
It was produced by a tool from Orange. We should check if there is a free software equivalent so that we can more easily automate it in the future.

**Comment by mucek4** [comment]
Orange is free software as far as I know. I just have to remember how I did that in first place.

**Comment by kumy** [comment]
For my culture, what is this `Orange` tool please?

**Comment by mucek4** [comment]
http://orange.biolab.si/

**Comment by samueltardieu** [comment]
Nice, I've been thinking it was a proprietary tool from Orange!

We should automate the process of generating the `IconDecoder`.

**Comment by Lineflyer** [comment]
Notification posted.

**Comment by mucek4** [comment]
![untitled](https://cloud.githubusercontent.com/assets/832407/20922061/23c9851a-bba7-11e6-8f2b-11c081925bc3.png)

They still have some problems, but so far it looks we have only 2 different set of icons. zoom level 13 or less and 14+

Automating the process will not be simple. 1st we need every possible icon of both zoom levels. Can anybody help me with that?

**Comment by mucek4** [comment]
![all14](https://cloud.githubusercontent.com/assets/832407/20922583/f7deecea-bba8-11e6-8308-fa246b6a9f74.png)
I need something like this - with transparent background for all possible icons.

**Comment by Lineflyer** [comment]
On the release note page (link above) there are some pics of the icons

**Comment by SammysHP** [comment]
![](https://www.geocaching.com/map/images/menu/sprite-pins.png)
![](https://www.geocaching.com/map/images/menu/sprite-pins-retina.png)

**Comment by mucek4** [comment]
Thanks, Sammy.
The problem is, new icons are so similar, we will have to find new way of detecting the cache type.
Events are identical
Mystery, letterbox and wherigo
Virtual & webcam

I can try combining them on short notice and find a better solution on mid-term. What do you think?

**Comment by Lineflyer** [comment]
Looking at the icons we could:
- Identify Traditional (forget about APE and HQ)
- Identify Multi
- Identify Mystery, Letterbox and Wherigo all as Mystery (as Letterbox and Wherigo are more rare)
- Identify Virtual and Webcam as one of them (I would suggest Virtual because Webcam are kind of Virtual)
- Identify all Event types as normal events
- Identify Earth caches (or are they to similar to Virtual/Webcam?)

Speaking about other ways to identify them I could only think whether it is possible to gain the type info from the popup information (but I guess this would be a lot of additional requests?!).

**Comment by SammysHP** [comment]
That should be easy using template matching (as long as icons don't overlap). Finding the bounding box is no problem because of the alpha channel.

1. Find bounding box
1. Calculate center
1. Compare with templates, use best match

**Comment by mucek4** [comment]
I was speaking more about "looking" at the shape of image and not trying to identify by colors. I managed to fix IconDecoder, but I currently have no way of testing it. Who can check it out and build a new version?

**Comment by Lineflyer** [comment]
Just a small remark:
Fixes for this should go to `release` branch,

**Comment by Lineflyer** [comment]
@mucek4:
Owned caches are now green so as Traditional. Is the different green tone enough to seperate them?

**Comment by mucek4** [comment]
Yes, this it correct. I am working on a patch that will detect all possible data from images.

**Comment by Lineflyer** [comment]
First quick feedback with 2016.12.09-RC (containing the first fix from @mucek4):
- Type detection is improved
- Reliability for Multi, Traditional, Mystery and Earth seems good.
- Disabled caches are parsed as some other type (need to check details).
- Some mysteries are parsed as CITOs (I suspect there is something wrong in the code....AFAIK CITO should not be returned at all)

**Comment by Lineflyer** [comment]
Add on regarding the parsing of disabled caches:
- Some disabled Traditional are incorrectly parsed as Mystery

- Identification of found caches seems good

**Comment by SammysHP** [comment]
Template matching would result in almost no false matches in most situations. IMHO it would be really worth to try it. Does somebody know a lightweight library? Otherwise it should also be relatively easy to implement it by ourselves.

**Comment by mucek4** [comment]
I'll try to do 2x2 or 3x3 template matching next week. To see how accurate it will get. Keep in mind this If, if, if structure is to keep execution fast.

**Comment by SammysHP** [comment]
Also complete template matching with all full icons should be much faster than downloading the tiles. In this case it is really easy because we can determine the center exactly, so just one feature vector compared with n icons. We could speed it up by using generalized feature vectors and use a hashmap. Or we compare it with the original icons and get a more fuzzy score that would even match partial icons.

**Comment by Lineflyer** [comment]
@mucek4 In order to have a possible quick fix which we can release asap, could you also take a look why `CT_CITO` is returned from the icon decoder. That looks unintentional to me.

If this is corrected we have a first solution implemented (and you can work on improvement in the meantime) while we could already release a fix. Of course this requires some more regressions to be solved (see #6166)

**Comment by mucek4** [comment]
CITO is so different that shall really not be problematic. It's right that CITO is returned but I have no idea why sometimes it's parsed wrong.
If you think it's too problematic, I can remove it.

**Comment by Lineflyer** [comment]
IMHO what is currently returned as CITO should be returned as mystery. That was the case for all wrong detections I have seen.

**Comment by Lineflyer** [comment]
@mucek4 @SammysHP Is there still some work in progress?
Otherwise I would suggest to only correct the CITO problem (as mentioned above) as a first step and do further improvement later on.

As we still have some issues to tackle before being ready for release, there might be some more time.

**Comment by Lineflyer** [comment]
Is it possible to fix the misdetection of CITO as described above? If yes, I would really suggest to do so and release asap to have the live map basically fixed.

**Comment by mucek4** [comment]
Sorry Lars, I was sick. Will take a look into it this week.

**Comment by Lineflyer** [comment]
No problem. Just nudge me if you made any progress.
As mentioned earlier, the current fix is not that bad, only those CITOs are wrong.

**Comment by Lineflyer** [comment]
Another addition:
It seems we also try to parse if the cache is owned. That path should also just be disabled for now as it leads to quite some false positives.

**Comment by Lineflyer** [comment]
Right now it seems that something changed.
Using current NB which should contain the fix identifies many Traditional as Mystery. At my first tests it was more reliable.

Will try to dig deeper if time permits.

**Comment by rsudev** [comment]
I have the impression they might have again changed something. Some days ago the detection rate was seemingly better.

**Comment by mucek4** [comment]
You are right. Old vs. New
![untitled](https://cloud.githubusercontent.com/assets/832407/21382396/b877e3a4-c760-11e6-8a0a-30361f9eb2b3.png)

**Comment by Lineflyer** [comment]
Oh. Can you adapt your first fix accordingly?

**Comment by Lineflyer** [comment]
@mucek4 
Anc chance to give our users a christmas present by having the detection fixed?

**Comment by Lineflyer** [comment]
Looking at the comparison of the icons, it seems they now use the retina versions as posted by @SammysHP

**Comment by Lineflyer** [comment]
@mucek4 
As just discussed on Skype: 
For the first fix (where you go by overall color the following groups sound logical to me:
These green types should be parsed as "Traditional":
![grafik](https://cloud.githubusercontent.com/assets/949669/21486347/6b0190b4-cbb3-11e6-8fd9-e4b78bdb8d0c.png)
(Forget about APE)

These red types should be identified as "Event":
![grafik](https://cloud.githubusercontent.com/assets/949669/21486371/de85f598-cbb3-11e6-9f86-dd8f8aafa6a7.png)
![grafik](https://cloud.githubusercontent.com/assets/949669/21486381/f3e73a96-cbb3-11e6-8a47-1e0e829a23e9.png)
MEGA and GIGA are more rara and it is not entirely wrong to show them as normal events anyway.

These blue types should be identified as "Mystery":
![grafik](https://cloud.githubusercontent.com/assets/949669/21486393/1b014838-cbb4-11e6-9569-0e3a49c14faf.png)
Of course this will be wrong for Letterboxes and Wherigos but those are more rare. IMHO there might be no better solution in the current implementation of IconDecoder?!

Multi caches have a unique color and should therefore be easy to identify:
![grafik](https://cloud.githubusercontent.com/assets/949669/21486453/423fe9b2-cbb5-11e6-8be0-e6de5b72cb8c.png)

These light blue types should be identified as "Virtuals" or "Webcams"...not sure what is the best:
![grafik](https://cloud.githubusercontent.com/assets/949669/21486409/6427dd74-cbb4-11e6-875b-e650c1f714cb.png)
This is not easy to decide, in Europe Webcams are more common than Virtuals, in America it is the other way around... Still all Webcams are also Virtual, whereas not all Virtuals are Webcams.

If possible we should try to find a way to identify "Earth" caches:
![grafik](https://cloud.githubusercontent.com/assets/949669/21486428/bfdf6448-cbb4-11e6-9a93-66064d050e3f.png)
AFAIK you managed to do so in your first attempt already?!

Then we have owned caches to identify:
![grafik](https://cloud.githubusercontent.com/assets/949669/21486438/ee4afd74-cbb4-11e6-9ac1-d789c83f4952.png)
![grafik](https://cloud.githubusercontent.com/assets/949669/21486441/f7de2cf8-cbb4-11e6-8891-800a16ca7f3b.png)
Luckily the only other type with same green is HQ (which is irrelevant), so it should be possible to parse them.

And finally the found caches which have a unique yellow:
![grafik](https://cloud.githubusercontent.com/assets/949669/21486447/21bd86ea-cbb5-11e6-8d9d-21fe37ed8556.png)

For the types CITO, Maze, Locationless (or is the brown icon something else) we should try to avoid parsing them as some other type accidentally but just return them as unknown (will test this).

Remark:
This is based on the fact, that they now use the "retina" version on the map.
I don't know under what conditions this might change (as @SammysHP found two different sets as posted above). 

---
After having this first fix we can push this out to the users and have some more time to think about other clever methods to improve this.

**Comment by Lineflyer** [comment]
Thanks @mucek4. First tests show that the cache type detection is back to the quality it was before.
Also the IndexoutofBounds is gone with your second PR.

Will do some more testing tonight but will in parallel publish a RC based on this code to GooglePlay.

Let me close this issue. Will open dedicated issues if there are remaining problems.
@mucek4 @SammysHP Feel free to open a dedicated issue as well for possible detection improvements by using another parsing method.
