### ISSUE TITLE
Snackbar texts "Deleted caches from other lists" and "UNDO" overlap

### ISSUE THREAD

**Issue by stephanBoehme** [cgeo/cgeo#6176]
##### Detailed steps causing the problem:
- Go to a list of stored cache listings
- copy at least one cache listing to an other list
- select the _Make list unique_ from the options menu
- The snackbar at the bottom of the screen says _"Deleted caches from other lists"_ and _"UNDO"_

##### Actual behaviour after performing these steps:
The two texts (_"Deleted caches from other lists"_ and _"UNDO"_) in the snackbar overlap so that the first one is not entirely readable.

##### Expected behaviour after performing these steps:
Both texts are readable.

##### Version of c:geo used:
2016.11.28-RC

##### Is the problem reproducible for you?
Yes

#### Screenshot
![screenshot_20161207-121159](https://cloud.githubusercontent.com/assets/13217135/20965576/97665816-bc76-11e6-99ce-a9f0fe6c7425.jpg)

##### System information:
```
Device: SM-G920F (zerofltexx, samsung)
Android version: 6.0.1
Android build: MMB29K.G920FXXS4DPJ5
Cgeo version: 2016.11.28-RC
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE (cgeo forced to English)
Log date format: 06.12.16
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d.MM.yyyy
Installed cgeo plugins: calendar
```

##### Other comments and remarks:
It's a minor thing...
The overlapping exists at least in English and German versions.

**Comment by pstorch** [comment]
Related to #5595

**Comment by Bananeweizen** [comment]
The problem is that this _is not_ a snackbar. However, with our upgrade to minsdk 14 this should be solvable by actually switching to Snackbars.

**Comment by Lineflyer** [comment]
Solved meanwhile:
![grafik](https://user-images.githubusercontent.com/949669/116085572-40aca800-a69f-11eb-9e34-7786c9c587a6.png)
