### ISSUE TITLE
SSL related login error on geocaching.com

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6180]
Might be a transient issue as there seems to be activity on the website of geocaching.com.

However my client and CI website tests show, that we fail to login at 23:54MET today while my PC browser has no problems:
```
23:52:57.394 Warning cgeo 20609  [OkHttp] Failure (370 ms) GET https://www.geocaching.com/login/default.aspx (javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)
```

**Comment by SammysHP** [comment]
They don't send the complete certificate chain: https://www.ssllabs.com/ssltest/analyze.html?d=www.geocaching.com

So it's their fault again.

**Comment by Lineflyer** [comment]
The problem is gone now. Also SSLLabs is back to rating "A".
