### ISSUE TITLE
History not working reliably

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6181]
This is more or less a reminder to myself (and others who would like to test):

Some user reports for the current RC version (2016.11.28-RC) tell, that there are problems in the history:
- Offline logged caches not visible
- History cannot be emptied
- History is emptied but cache count in title bar still shows x caches on list

I cannot reproduce any of them right now, but as we had a change in this area I think there might be some leftover bug under special conditions.

I will try to gather more information from users and try to test some things myself.

**Comment by pstorch** [comment]
Just tested. At least a "Write Note" log didn't show up in history. I'll have a look.

**Comment by pstorch** [comment]
Ah no, it's only for found logs. Have to test again.

**Comment by pstorch** [comment]
Ok, happens with found log, too.

**Comment by pstorch** [comment]
Hmm, `visiteddate` is calculated and the `database.update()` function is called, but when I look into the sqlite db, the `visiteddate` is 0.

**Comment by pstorch** [comment]
Ahh, when a log is sent to GC, the offline logs are cleared with `clearOfflineLog()` and in this function also the `visiteddate` is set to 0.
Looks like it's my fault from #5940.
Will correct it.

**Comment by pstorch** [comment]
The confusion really starts with mixing two concepts here. History (as defined by last found logs) and Offline Logs. We should try to split this view as suggested in some other issues.

**Comment by Lineflyer** [comment]
@pstorch Can you please also merge release to master to have nightlies include all changes as well?

**Comment by pstorch** [comment]
@Lineflyer yes, can do it this evening

**Comment by Lineflyer** [comment]
and +1 for implementing as suggested in #4672. That would be a much clearer approach.

**Comment by pstorch** [comment]
@Lineflyer merged to master
