### ISSUE TITLE
Non-detailed caches incorrectly counted for amount of stored caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6185]
##### Detailed steps causing the problem:
- Remember the amount of saved caches on your lists as shown on the mainscreen as X
- Open live map
- Click on a non-detailed cache (with orange circle)
- From the popup select Log Visist 
- Enter log text and press back to save the log

##### Actual behavior after performing these steps:
- Cache icon has now markers for offline logged and saved(?)
- Saved caches amount on main screen is now x+1
- Cache is not visible in lists
- Cache is visible in history
- Opening this cache in history will show the non-detailed status: Empty description, Empty logbook
- Cache details screen shows "Saved on device 11746 days ago"

##### Expected behavior after performing these steps:
I don't know enough about the DB structure to judge the best way of fixing this.
However from a user perspective:
- It should show up in the history (as it does)
- It should not count to the amount of total caches stored in lists as it is not part of any list contained there
- It should not show up with saved icon on map

##### Version of c:geo used:
2016.12.10-NB

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
This seems to be **not** caused by the change of @pstorch (ded3fb7c41093590b2586ae7e4d756291c9ee3db) as the behaviour is the same with this fix (fresh RC) and without this fix (current nightly).

**Comment by rsudev** [comment]
This behaviour was likely introduced, when the saving of partial caches was implemented. While this is a good thing as such, seemingly there are still conceptual gaps to address. We didn't have this category of caches previously.
- they are saved, hence a download of details is not triggered when you open them, but they are not detailed, so you need to refresh them manually to get all information.
- they are saved, so the add to the stored count and are displayed as stored, but the automatic save does not place them on any list (seemingly)
- I guess you will have to delete them explicitly to remove them again

I would suggest to keep the 'stored' icon, as they are stored, don't go away by themselves and are available offline. But we should manage to try a download of the missing details automatically or make the user aware when she opens the details.

**Comment by pstorch** [comment]
Yes, this was introduced by #6012. 
But I just tried it and they show up on the default list `Stored`. I can reproduce the bug with the saved date.

And as I wrote in my comment https://github.com/cgeo/cgeo/pull/6012#issuecomment-258619917 it might confuse users to see the rather empty details page of such a cache. Either trying to reload in the background or a visible clue to reload, could help.

**Comment by pstorch** [comment]
What is the suggestion to do here? The way I tested it the partially stored cache can be found on the default list "Stored" and correctly counting to the total of saved caches.

**Comment by SammysHP** [comment]
What I noticed: History shows x stored caches, but the list is empty. Same problem?

**Comment by pstorch** [comment]
@SammysHP with the steps in the issue description the History on my device is not empty and shows the correct number. I can't reproduce.

**Comment by Lineflyer** [comment]
@pstorch If you follow the steps I described you will find the cache in history but not on the "stored" list.

**Comment by pstorch** [comment]
@Lineflyer that is strange. Then our devices work differently somehow.

**Comment by Lineflyer** [comment]
Tried on two other devices. I can reproduce it on both.

For better explanation I made a short video of the sequence:
https://www.dropbox.com/s/21bjel6laaa4lgp/20161214_220955.mp4?dl=0

**Comment by SammysHP** [comment]
https://cloud.finf.uni-hannover.de/s/zWt0TKv43psGZsG

**Comment by pstorch** [comment]
Ah ok, now I could reproduce. Let's see if I can find the cause.
