### ISSUE TITLE
Proposal: Display labels on caches for other lists

### ISSUE THREAD

**Issue by gsstark** [cgeo/cgeo#6187]
I frequently want to store all the caches in an area but also check them all to see which caches are particularly interesting. Caches can be particularly interesting for various reasons such as helping to satisfy a challenge cache, filling in holes in the Jasmer grid or the DT grid, or just being at a location that would interest me. So I add the caches that are particularly interesting to one of various lists.

However when I look at the map or the list of stored caches for the area there's no indication of what other lists the cache is on. And if I look just at the list of "interesting" caches I'm likely to miss other caches that are nearby.

What I propose to solve it is when displaying a list of caches to display small icons after the "Small Offline" for each list the cache is on. That way I can see the list of "Nearby" caches or I can look at a stored list for the area and quickly notice if I'm near a cache that I don't want to miss. This would be similar to the way mail user agents universally have a feature allowing you to "star" important emails.

I have a few ideas of how to indicate what icon to use. One option is to provide a dropdown in the "Rename List" dialog which allows you to set an icon. This has the advantage that users would see the option when creating the list and also that not every list would have to have an icon so users could choose which lists were actually important.

Another would be to simply use the first character of the list name. So caches would have a series of letters next to them. Users who want icons can put unicode emoji signs as the first character of the list name. This has the advantage that users would get the benefit even if they aren't aware of the feature and they don't have to take any explicit action to enable it.

Incidentally, I think when displaying a specific stored list it should exclude that list's icon from the listing.

I am a developer but have never poked at any Android app development so I may be able to do this and submit a pull request but may need some guidance, especially on Android environment quirks.

**Comment by SammysHP** [comment]
See also #3523, #5373 and #5798. I think these issues will cover your problem. If you have more ideas, just write a comment to the corresponding issue.

If you think that you mean something different, please leave a comment and explain the differences a bit more precisely.
