### ISSUE TITLE
Proposal: Virtual lists for common challenge properties (Jasmer and DT grid)

### ISSUE THREAD

**Issue by gsstark** [cgeo/cgeo#6188]
The various challenges people set themselves or take up from challenge caches often drive people to seek out caches that would help satisfy the challenge  If you look on project-gc.com you can see various grids and cache attributes and it's quite common for particularly nerdy cachers to want to collect all the boxes of those grids.

Two of the most common are 

a) Filling all of the DT grid -- i.e. all 81 combinations of difficulty and terrain. Oncepl filled people look to repeat the cycle, i.e. fill it with numbers >= 2 and so on.

b) filling the "Caches by hidden month" grid. The challenge caches for this are named after the person who first invented them "Jasmer". So you frequently see people talking about finding "Jasmers".

I maintain a list called "Jasmer" which has any caches in areas I'm interested in that were hidden in a month that I'm currently missing on my Jasmer grid. However this has several problems. a) I can't store all the caches around the world this way so when I go to a new area I need to add more even if I'm not planning to do much caching and expecting to have data b) it's really hard to remove caches when I fill a spot. Removing dozens of caches from a lit based on an attribute that doesn't show in the listing is laborious and error prone and some of them may still be worth storing for other reasons but some may have had no other reason to be on the phone.

What I would suggest instead is to keep an internal representation of the Jasmer grid and DT grid -- they're very small and easy to fetch from geocaching.com and/or project-gc but also fairly easy to just construct and update from stored information too. Then display an icon or word on the listing and on the cache detail page if the cache fits the property.

It would be neat to provide a virtual list for these properties too which would display all stored caches that have the property. Then my workflow for most areas would be "store all caches in the area" then "display virtual list jasmer" choose my destinations based on that and then look at all stored caches in those areas.

**Comment by SammysHP** [comment]
That sounds like you just want a filter, correct? I'm against adding these two special cases to c:geo. There are so many different challenges.

I'd like to narrow this down to some specific problems/goals:

- Allow more than one filter at the same time (#135, #995, #5877)
- Make filters persistent / allow storing filter sets

Thus you could define a filter set which shows exactly the caches you need and store that filter for later recall.

**Comment by Lineflyer** [comment]
I agree to @SammysHP that this is more a question of better filtering options in general. It is unlikely that we will implement special filter combinations for certain challenges. Once we implemented a better filtering (refer to mentioned issues) such a filtering will be possible.
More functionality might even come in if project-gc.com has some time to start some interworking with us (as discussed in some other issues).
