### ISSUE TITLE
Quick navigation not selectable in WP view

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6194]
##### Detailed steps causing the problem:
- Open GC24CQN
- Swipe to waypoint tab
- Try to click on the compass rose shown next to each WP

##### Actual behavior after performing these steps:
Scrolling is triggered

##### Expected behavior after performing these steps:
Quick navgation should be started

##### Version of c:geo used:
2016.12.19-NB

##### Is the problem reproducible for you?
Yes for this cache
At leat on one other cache it does not happen although scrolling is possible given the amount of WPs
Maybe it depends on the total amount?

**Comment by Lineflyer** [comment]
Addition:
The scrolling bar looks different for this cache than for others with less WPs.
Was this quick scroll function only introduced recently?

**Comment by rsudev** [comment]
I cross-checked by keeping adding WPs to a cache which had non initially. It seems that this 'quick-scroll-bar' starts appearing after adding around 20 WPs (the test-cache has 43).
So I guess it is some built-in Android behaviour for longer lists.

**Comment by Lineflyer** [comment]
I thought I have seen some commit regarding adding quick scrolling functions some time ago...but I might be wrong.

**Comment by fm-sys** [comment]
This was probably related to fast scroll, which is fixed since some weeks (see #8406)...

**Comment by Lineflyer** [comment]
@fm-sys Thanks for helping to clean up. Appreciated!
