### ISSUE TITLE
gradle -  SDK location not found

### ISSUE THREAD

**Issue by Hauwertlhaufn** [cgeo/cgeo#6195]
##### Detailed steps causing the problem:
Try to import a completly new Fork to Android Studio

##### Actual behavior after performing these steps:

> Error: SDK location not found. Define location with sdk.dir in the local.properties file or with an  ANDROID_HOME environment variable.

##### Expected behavior after performing these steps:
It should import the project to Android Studio.

##### Version of c:geo used:
Latest version of the Github-project.

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:

It could be fixed by adding `include ':cgeo'` to the settings.gradle file. ([stackoverflow](http://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil))

**Comment by mucek4** [comment]
you have to set location of you android sdk. That is different on every machine.
Don't believe everything on stackOverflow.
Do you have local.properties file and what it contains?

**Comment by Hauwertlhaufn** [comment]
Ok, that's strange. I 'changed it' to the exact same location it was already set, saved it and restarted Android Studio. Now it works just fine. Sorry for the inconvenience.
