### ISSUE TITLE
Allow multiple signature templates 

### ISSUE THREAD

**Issue by caigner** [cgeo/cgeo#6197]
When Geocaching, I use a template for my log entries. 

When doing maintenance as owner, I would like to use another template. 

Would it be possible to save two (or more) different templates so I can quickly switch between them?

**Comment by caigner** [comment]
As my yearly maintenance round is coming up I want to draw your attention to this issue. :-)

**Comment by Technical-13** [comment]
This would be a great feature just to distinguish between finds and DNFs, I hadn't even considered additional options for maint logs etc...

**Comment by caigner** [comment]
Any chance we will see this feature in the near future?

**Comment by caigner** [comment]
Please don't forget us Geocache-Owners when implementing new features. At least one more signature template would be very helpful.
In my case:
One signature for logging a cache as found.
One signature for a maintenance log entry.

**Comment by bekuno** [comment]
I have started implementing that feature.
Here is my proposal to configure the log settings.
What do you think?

![screenshot_20181209-222934](https://user-images.githubusercontent.com/32555742/49753482-df453380-fcb3-11e8-9f10-3d64b97bc752.png)
![screenshot_20181209-222944](https://user-images.githubusercontent.com/32555742/49753487-e1a78d80-fcb3-11e8-82ae-bc019a98e972.png)

**Comment by bekuno** [comment]
Some TODOs
- Add/implement option: "use found template for all unfilled templates"
  make this default
  then it works as before
- if option "insert automatic" is set, then the initial inserted text have to be replaced by the correct template text when changing the log type (do it only when the text is unchanged)
- implement the inserting from log "add signatue"

**Comment by caigner** [comment]
Hey, bekuno, that's great news! :-)
For the log settings I propose the following UI:
![add_signature](https://user-images.githubusercontent.com/886281/49862426-70c0bc80-fdfe-11e8-82ee-e0f649ce80df.png)
![add_signature_2](https://user-images.githubusercontent.com/886281/49862435-74544380-fdfe-11e8-874e-d4c3a60ac5f6.png)

**Comment by caigner** [comment]
And if the user decides to create two Found-templates, then a checkbox should be there so the user can decide which one is for auto-insert.

**Comment by caigner** [comment]
And sorry for the late response. Lot's of sick people in the family to take care of. :-)

**Comment by bekuno** [comment]
Thanks for your ideas. It was not too late ;-) We all have families.
I will have a look on it.

**Comment by MagpieFourtyTwo** [comment]
Was just pointed to this issue by @fm-sys - Fine! Looks pretty much the same I tried to explain [here](https://github.com/cgeo/cgeo/issues/7839#issuecomment-693741253) and [here](https://github.com/cgeo/cgeo/issues/7839#issuecomment-694106566), just plus a button on top of the logging window to choose a sig resp. replace the currently inserted one.

**Comment by MagpieFourtyTwo** [comment]
Although, as stated, I would not hardlink the signature template to a log type, as this limits possibilities, IMO, but would just allow to enter free text as signature title, which can be chosen via the mentioned sig button.

**Comment by ztNFny** [comment]
Instead of signatures linked to a specific log type I'd prefer some generic log templates that can be inserted like the current signature, just call them "Template 1-5" or something. Allows for more flexible use.

**Comment by ztNFny** [comment]
I have added 3 additional templates that work in the same way "Signature" does in defining them in preferences.
They do show up in the "insert" menu right below signature - but only if they are non-empty - from where you can insert them manually.

Limitation: You can't set the title, they show up as "Log template X"

Is there interested in having this?

![2021-11-07_18-30-13](https://user-images.githubusercontent.com/1258173/140655294-7fa78a94-6558-4a73-b0f5-68b7ae5a0959.png)
![2021-11-07_18-29-41](https://user-images.githubusercontent.com/1258173/140655292-2cd73153-1437-4512-9453-7d62c659307d.png)

**Comment by Lineflyer** [comment]
Yes, why not.
IMHO a good starting point at least, which can be enriched later on if desired.

**Comment by ztNFny** [comment]
I've improved it a bit, adding support for a template title that's shown in the insert menu.

However this is currently done in an ugly way, using one preference to store template name and text with a divider - I couldn't find any good way to have two associated preference keys (for title and text). If someone has an idea on that please feel free to pick up the code in PR. Due to this I've marked the PR as Draft for now.
(Also the number of templates is fixed now as it's using preferences, implementing title and text as some form of objects would probably allow making that dynamic)

![image](https://user-images.githubusercontent.com/1258173/140794752-79ffd2e6-cbf3-4aba-9c18-dbbcad77a683.png)
![image](https://user-images.githubusercontent.com/1258173/140794808-331ed1ed-45b2-40b0-bf00-e452598fc800.png)

**Comment by fm-sys** [comment]
> Also the number of templates is fixed now as it's using preferences, 

That doesn't work well IMHO. There will always be one who needs one more template, and others will call it unnecessary space consumption...

I can try to implement a dynamic solution if this is wanted.

**Comment by Lineflyer** [comment]
The feature request is fulfilled, but this is always the starting point for future improvement.
So feel free to open a new feature request with your improvement idea. :)

**Comment by caigner** [comment]
To all who contributed to make this feature happen: Bravo! You did a great job! I love the new log text feature! Thank you!
