### ISSUE TITLE
Offline maps not working

### ISSUE THREAD

**Issue by Sheldor2101** [cgeo/cgeo#6200]
I cannot use offline maps anymore.
--- System information ---
Device: SM-G389F (xcover3veltexx, samsung)
Android version: 6.0.1
Android build: MMB29K.G389FXXS1APK1
Cgeo version: 2016.12.09-RC
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 27.12.16
Debug mode active: yes
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / BASIC
Geocaching.com date format: dd/MM/yyyy
Installed cgeo plugins: calendar
--- End of system information ---

**Comment by rsudev** [comment]
Hi @Sheldor2101, thanks for submitting this issue. Unfortunately ist it not detailed enough to allow us to understand it or work on it.
- Where offline maps working before (and which offline map?)?
- When did they stop working? Was there a change on your side (new version of c:geo, new version of the map, ...)?
- How do they not work? Crash of the application? Error messages? Which steps do you follow in the application and what happens?

PLease give us a chance to understand your problem and possibly help you or fix it :)

**Comment by Sheldor2101** [comment]
/On my previous phone it worked./
//
/I cannot choose any offline map. The app only offers online-maps./

**Comment by rsudev** [comment]
Have you downloaded any offline maps to your new phone (see also our faq http://www.cgeo.org/faq.html#osm and related)?

**Comment by Sheldor2101** [comment]
Yes, I downloaded them as .map-data.

**Comment by rsudev** [comment]
And did you configure c:geo to use them?

**Comment by Sheldor2101** [comment]
I tried, but the app didn't offer my offline maps in spite of having selected the right directory. 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.

**Comment by rsudev** [comment]
Ok, so now we are slowly getting there. Can you tell where you downloaded the maps from and which ones? Did you already try to re-download them, in case they might have been corrupted in downloading (no call to action, just a question!)?
Can you illustrate with screenshots where the maps are on your device, how the folder selection looks like when you select the correct folder and how the settings screen looks afterward? Be aware, screenshots have to be added through the web (AFAIK), sending them as eMail-attachments will not work.

**Comment by rsudev** [comment]
I don't think that maps.me map files are compatible with c:geo. We use the mapsforge library for offline map rendering and you can download compatible maps either from the mapsforge download server or a number of other sites (e.g. openandromaps, freizeitkarte).

**Comment by Sheldor2101** [comment]
Well, MAPS.ME also uses .map- files.

**Comment by Lineflyer** [comment]
Yes, the file extension is also *.map.
But still according to all I know they use their own proprietary format (or at least some proprietary extensions). Those maps have never been compatible with c:geo.
Please use maps from sources which use the mapsforge standard (examples mentioned above).

**Comment by Sheldor2101** [comment]
Actually they are from there.
http://download.mapsforge.org/

**Comment by Lineflyer** [comment]
I can't completely follow.
If they are from mapsforge.org these cannot be the ones you mentioned earlier from maps.me.

@rsudev 
Regarding the map files from mapsforge.org:
Do we have a version problem here if the user does not use the beta implementation (which I doubt)?

**Comment by SwissPoPo** [comment]
The maps in the main folder (download.mapsforge.org/maps) are in the older version 3.
The maps below "multilingual" are in the current version 4.
V4 maps are not visible in c:geo. even if the beta map is selected.

**Comment by Sheldor2101** [comment]
I redownloaded them and actually it works now.
