### ISSUE TITLE
feature request: direction triangle floating around

### ISSUE THREAD

**Issue by bjorri** [cgeo/cgeo#6202]
In the nearby list there's a triangel pointing to the nearby caches. Most of the time it is not very reliable, pointing in all directions in seconds. Even when it would point accurate, mostly I want to go in a certain direction through the day. 

Idea is to make it possible to select pointing relative to the north in stead of pointing to the 'actual' direction.

##### Actual behavior after performing these steps:
Choose to point the actual direction or relative to north.

##### Is the problem reproducible for you?
Yes

**Comment by Lineflyer** [comment]
I am not sure, if I understand your request correctly:

So you would just like to point it as if your phone is directed to north permanently?

**Comment by Lineflyer** [comment]
Closed due to lack of feedback
