### ISSUE TITLE
Fix IconDecoder tests

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6212]
Following the recent changes to `IconDecoder.java` the corresponding tests need to be fixed as they are currently failing.

**Comment by pstorch** [comment]
I think it is important to fix the builds. If possible I would like to help here, but if I see it correctly the map images for this test are created by @mucek4 's GC account.

**Comment by mucek4** [comment]
The problem is, that we can't make exactly the same images, as caches change over years (specially in 4 years). New images have to be downloaded and new tests made based on new images. Does not really matter on witch account.

**Comment by pstorch** [comment]
Ok, at least I can give it a try, if no one else is already on it.
We need just some Map tiles with different cache types on different zoom levels (11-14), right?
And the `map_all14.png` needs to be replaced by this new `sprite-pins-retina.png`?

**Comment by mucek4** [comment]
Yes and no.
There are 3 zoom levels. <=11, 12-13 and >=14 Try couple of images, some with overlapping icons. 
map_all14 is not retina icons. Retina icons are same color, but bigger Don't know how they downsize it. And technically parser works with bots sets of icons. Retina and non retina.

**Comment by pstorch** [comment]
OK. I think I have to create a new map_all14.png with the new icons. The ones from GC are too big to fit the tile size.

**Comment by pstorch** [comment]
The "owned" color is a bit different:
RGB: 119, 156, 17
https://www.geocaching.com/map/images/menu/sprite-pins.png

RGB: 0, 178, 101
https://www.geocaching.com/map/images/menu/sprite-pins-retina.png

In the tiles the retina color is used. So have I done in the tests, see #6215

**Comment by Lineflyer** [comment]
Fix has been merged to `release`
