### ISSUE TITLE
Doesn't update distance anymore in compass mode

### ISSUE THREAD

**Issue by naoliv** [cgeo/cgeo#6217]
##### Detailed steps causing the problem:
- Open the compass to find a cache

##### Actual behavior after performing these steps:
Position/distance isn't updated

##### Expected behavior after performing these steps:
See the distance decreasing as I get closer to the cache

##### Version of c:geo used:
2016.12.28

##### Is the problem reproducible for you?
Yes

##### System information:
```
Device: XT1069 (titan_retbr_dstv, motorola)
Android version: 6.0
Android build: MPB24.65-34-3
Cgeo version: 2016.12.28
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: pt_BR (cgeo forced to English)
Log date format: 31/12/16
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: dd/MM/yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:

As can be seen here, `Sat` keeps at `0/0`. I guess that it could be related with the low power mode.
But even if I am very close to the cache, somehow it seems that c:geo isn't enabling/using the GPS to locate me.
No matter how much I move, the distance just doesn't update.

It seems to be a recent problem (maybe introduced in the last beta versions), since this used to work without any problem (I always used it with low power mode enabled)

![](https://cloud.githubusercontent.com/assets/982338/21575905/afb63bba-cf05-11e6-9e4c-082cbd05cba2.png)

**Comment by spinnekopje** [comment]
Check whether your gps is switched on, I've had similar issue some time ago.
It seems you have a location, but that can be based on wifi networks etc.

**Comment by naoliv** [comment]
It's enabled.
I can properly use any other program that uses the GPS, except c:geo

I don't know the internals, but it seems that somehow c:geo is using only using the `NO_POWER` power mode of the fused location API.

**Comment by spinnekopje** [comment]
There is a setting in android that you can change to allow the usage of gps for c:geo. I got the same problem some time ago, so I don't remember where it exactly was, but you could navigate to settings, apps, c:geo and check the rights of the app. On one device with android 6 I see location and storage. Both should be enabled. Maybe location isn't enabled, otherwise there is a setting elsewhere. Hopefully it solves your problem, but c:geo should in that case ask for the rights to use your precise location.

**Comment by Lineflyer** [comment]
According to the sys info you posted you have low power mode active. That should however not affect the compass. @samueltardieu Correct?

Please try to disable it in Settings - System anyway

**Comment by SammysHP** [comment]
The compass seems to work. But if the play services say that the position is the same, the distance won't change. I had this something during very slow movement.

**Comment by samueltardieu** [comment]
Indeed, the low power setting has no effect on the GPS mode used while displaying the compass activity.

**Comment by Lineflyer** [comment]
Closing due to lack of submitters feedback.

**Comment by naoliv** [comment]
I am actually waiting to be closer to some geocache to test this.
There is no geocache nearby here.

BTW, we don't get notified when a label `Requires submitter feedback` is included here.

**Comment by Lineflyer** [comment]
@naoliv Any new feedback regarding this. Did you come near to a geocache to test it without "low power mode" or even with "Disabled Play Services"?

**Comment by naoliv** [comment]
Unfortunately not yet.
I will be able to test it on this weekend or the next one.

**Comment by naoliv** [comment]
I could test with multiple geocaches this weekend and it seems that I was wrong when I thought that the problem was with the low power mode.
It seems to be caused by `Use Google Play Services`

What I tested:
`Use Google Play Services` **enabled**  + `Activate low-power mode` **enabled**: doesn't work
`Use Google Play Services` **enabled**  + `Activate low-power mode` **disabled**: doesn't work

`Use Google Play Services` **disabled**  + `Activate low-power mode` **enabled**: works
`Use Google Play Services` **disabled**  + `Activate low-power mode` **disabled**: works

The impression that I had when using `Use Google Play Services` was that it was working in a passive mode (like the `NO_POWER` of the fused API).

ie, if I walked with cgeo running, it didn't update the location.
If I opened another app that used the GPS and then get back to cgeo, the location was updated

Is there something else that I could try to help in debug this, please?

**Comment by Lineflyer** [comment]
It pretty much looks like the "Google Play Services" are not working OK on your device.
So either it might be outdated or some other problem (which we cannot influence).

You can check for updates in the Google Play Store and try again if there is an update available:
https://play.google.com/store/apps/details?id=com.google.android.gms

**Comment by Lineflyer** [comment]
Closing due to lack of feedback.
Feel free to reopen with feedback.
