### ISSUE TITLE
PGC Checker link not working at target site

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6224]
##### Detailed steps causing the problem:
- Open GC3RG33 (or any other challenge cache)
- Select Menu -> Search challenge checker
- In browser select "Execute"

##### Actual behavior after performing these steps:
Checker should give a result

##### Expected behavior after performing these steps:
Checker returns error

##### Version of c:geo used:
2016.12.28

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
This is a fault at project-gc.com. The checkers are not working if the page is called with https but working normal on http
Test it: https://project-gc.com/Challenges/GC3RG33 vs http://project-gc.com/Challenges/GC3RG33

Will report it to PGC but still opening here as a reminder (or for a possible workaroung to fall back to http)

Ping to @magma1447

**Comment by Lineflyer** [comment]
Bug report filed at PGC: https://project-gc.com/qa/?qa=12849/challenge-checker-wont-work-on-https

**Comment by magma1447** [comment]
https://project-gc.com/qa/?qa=12849/challenge-checker-wont-work-on-https has been answered. In short, there is a "fix" in progress at Project-GC.

**Comment by Lineflyer** [comment]
@magma1447 
I just tried and it seems to work now. Can you confirm, that you changed on your side?

**Comment by Lineflyer** [comment]
Confirmed working
