### ISSUE TITLE
Non-detailed saved caches show wrong saving date

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6231]
Not sure if this might be a duplicate...wan't there an issue about saving a non-detailed cache

##### Detailed steps causing the problem:
- Open live map, set strategy to "Fast"
- Select an orange circled (= non-detailed) cache
- From the popup select "Log Visit" and store the log offline

##### Actual behavior after performing these steps:
- In the popup you can now read "Saved on the device 17174 days ago"

##### Expected behavior after performing these steps:
- The correct saving date should be used

##### Version of c:geo used:
2016.12.28

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
on it
