### ISSUE TITLE
One-click offline log does not save cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6232]
I found a difference depending of whether or not "One-click offline log" is active.
Can someone explain:

##### Detailed steps causing the problem:
- Enable "One-click offline log" in Menu - Settings - Logging
- Open live map, set strategy to "Fast"
- Select an orange circled (= non-detailed) cache
- From the popup select "One-click offline log" and select found

##### Actual behavior after performing these steps:
- Cache does not get stored

##### Expected behavior after performing these steps:
- Should be treated in the same way as when using the online log function (see #6231)

**Comment by pstorch** [comment]
On it. I have a partly working solution. The cache gets saved, but the popup doesn't get updated properly yet. Need to find out how to update it.
In the "normal" offline log case the Logging UI starts a new Activity and the Popup updates itself in `onResume()` automatically. This is not the case in the "one-click" offline log case. There is only a Dialog which doesn't cause the `onResume()` method to be called after it is closed.
