### ISSUE TITLE
Handling of non-detailed saved caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6235]
[22:03] <Lineflyer> IMHO we should ask the user or directly download the details if he opens a nondetailed cache

This is possible from live map popup of a previously offline logged cache or from history of an offline logged caches.

Reference to #6231

**Comment by pstorch** [comment]
I think I have changed the behaviour here due to another fix. 
Can you check it?

**Comment by Lineflyer** [comment]
Confirmed working now with current master:
When opening a non-detailed cache a cache download is triggered (both from live map popup or from history).
