### ISSUE TITLE
Mapsforge site not updated

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6238]
This isn't really a cgeo issue, but I've noticed that many of the maps I download for cgeo [ from http://download.mapsforge.org/maps/europe/ ] haven't had an update since Apr 2016 or even older.

Any idea what to do or where to raise the issue?

**Comment by SammysHP** [comment]
Correct, this is not related to c:geo. Maybe you can ask Mapsforge directly: https://github.com/mapsforge/mapsforge
