### ISSUE TITLE
Only 100 waypoints shown per cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6243]
And here is comes. Another rare use case (love those).
Seems I did ust now learn that the amount of waypoint per cache in c:geo is limited to 100.

This cache http://coord.info/GC6TT3C has around 194 waypoints (If I counted correctly).

Is there any necessity to limit to 100 or just a randomly selected limit which we could raise.

**Comment by pstorch** [comment]
Looks like it's even less then hundred: https://github.com/cgeo/cgeo/blob/e6a709621702400f6a452ad2429d641036f14ba6/main/src/cgeo/geocaching/models/Geocache.java#L1364

The first 17 waypoints are reserved for `OWN_WP_PREFIX_OFFSET`.

**Comment by SammysHP** [comment]
As the prefix is only two characters long, we already use all number prefixes. But I don't believe that this method is used to find a new prefix. Instead the original prefix should be used.

**Comment by samueltardieu** [comment]
This limitation exists since the first cgeo commit. I'm removing it.
