### ISSUE TITLE
Spoiler image for GC6XYB6 not displayed

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6246]
##### Detailed steps causing the problem:
- Open cache https://coord.info/GC6XYB6
- Look for Spoiler images

##### Actual behavior after performing these steps:
- Spoiler image not visible

##### Expected behavior after performing these steps:
- Spoiler image visible

##### Version of c:geo used:
2017.01.11-10b7257 developer build

##### Is the problem reproducible for you?
Yes

**Comment by samueltardieu** [comment]
Is the image link on the page description clickable for you? It isn't for me.

**Comment by pstorch** [comment]
No, it's already the large image. I think that's why it is not clickable.

**Comment by samueltardieu** [comment]
I'm not sure I understand what you mean. Here is what I see on the web page, "Foto spoiler" being only some text without link.

![cache](https://cloud.githubusercontent.com/assets/44656/21847819/3c82510e-d7fe-11e6-811c-a7f224bed750.png)

**Comment by pstorch** [comment]
Interesting, I see it this way:
![selection_012](https://cloud.githubusercontent.com/assets/5598124/21847868/803b2006-d7fe-11e6-81ed-b5472ed77ac9.png)

**Comment by pstorch** [comment]
The Regex to recognize the Spoiler is easy to fix.

**Comment by SammysHP** [comment]
@pstorch GC Little Helper. ;)

Btw: Already the new version? https://github.com/2Abendsegler/GClh

**Comment by pstorch** [comment]
@SammysHP you're right, it's gclh. :) 
Not the new version yet, have to upgrade.
