### ISSUE TITLE
Latest nightly deleted 2/3 of my offline database

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6254]
##### Detailed steps causing the problem:
- Installed latest nightly 2017.01.13
- After startup I noticed that the "Nearby" list showed caches not marked as "stored" (but they should!)
- From my 17 lists only 6 contain entries, the others are empty.
- Probably most interesting information : it seems that the loss is list oriented: either the lists are complete or empty

##### System information:
```
--- System information ---
Device: D5503 (D5503, Sony)
Android version: 5.1.1
Android build: 14.6.A.1.236
Cgeo version: 2017.01.13-NB-f7c9466
Google Play services: disabled - 10.0.84 (236-137749526)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
Log date format: 13.01.2017
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / BASIC
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins: none
--- End of system information ---
```

**Comment by pstorch** [comment]
Can you say if the stored lost caches were on any list before?

**Comment by Matze2** [comment]
Yes, they all were on lists. I had > 1000 caches distributed over 17 lists.
The lists had sizes from 10-200 entries. Now 11 lists are empty and 6 lists seem to be complete still.

It seems that all the data is really gone. The .cgeo directory has only ~480 directories left which matches the number of stored entries reported.

Also the "data" file is only 12 MB while the last backup (unfortunately from October) had more than 30 MB.

**Comment by pstorch** [comment]
Is it possible to have a look at the 30 MB file?

**Comment by Matze2** [comment]
Just for the records: made current database and backup available.

**Comment by Lineflyer** [comment]
I just checked. Have the same problem here!! Many empty lists.

**Comment by Lineflyer** [comment]
Addon:
It looks like I also lost caches over the day today which I saved this morning. Without version upgrade in between.

**Comment by Lineflyer** [comment]
I can even save two caches again on that empty list. After force closing and restarting cgeo they are gone.

Pure guess:
It seems to depend on the list ID. Lists created at first since installation are ok, newer lists loose data.

**Comment by Matze2** [comment]
In my case it is always the same lists that get truncated.
6 lists are left untouched. And - yes - it could be the oldest lists.

**Comment by rsudev** [comment]
I checked the first statement in deleteOrphanedRecords.
Sometimes our code is just devious, but
```
public static final int customListIdOffset = 10;
```
makes it a killer...

**Comment by Lineflyer** [comment]
We also will have this problem in latest beta...or is the orphaned modification only on master?

**Comment by rsudev** [comment]
Thats only in master, as far as I can see.
Unfortunately I cannot fix it right away (its just too late), and tomorrow I'll be on the road...

**Comment by pstorch** [comment]
Yes, it's the customListIdOffset, the struck me. Have I commented somewhere that I wanted to get rid of it?
I'll fix it now.

**Comment by Lineflyer** [comment]
Great. I built a new NB1 to get rid of the problem in the nightlies.

**Comment by pstorch** [comment]
@Lineflyer thanks

**Comment by Matze2** [comment]
I can confirm the fix. With 2017.01.15 no loss anymore. Good work!

**Comment by pstorch** [comment]
@Matze2 thanks for the feedback. And sorry for the inconvenience it caused. I hope you could recover most of the lost data.

**Comment by Matze2** [comment]
Yes by accident (definitely not by intention) I had the backup from October, e.g data from unfinished multis is still there. Will do backups more frequently now :)
