### ISSUE TITLE
List not refreshed after deletion of a cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6256]
##### Detailed steps causing the problem:
- Open a list with many caches on it (enough to allow scrolling)
- Don't scroll but delete a cache from those visible on the screen by long press -> Remove
- Result 1
- Scroll down and remove a cache from those visible on the screen by long press -> Remove
- Result 2

##### Actual behavior after performing these steps:
Result 1: Cache is not removed from the list / list is not refresed
Result 2: Works as it should / list is refreshed

##### Expected behavior after performing these steps:
List should always be refreshed after modification

##### Version of c:geo used:
2016.01.14-NB1-6e9a53e

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Seems the problem only occurs if the list is not scrolled down 
@pstorch: AFAIR you changed something related to remember position on the list after deleting from history. Might you have changed the genereal bahviour unintentionally?

**Comment by pstorch** [comment]
I'll have a look

**Comment by Lineflyer** [comment]
@pstorch Was this a regression caused by recent changes or unrelated? If related, was the change on `release` or on `master` only?

**Comment by pstorch** [comment]
@Lineflyer it is a regression from #6253 on `release`
