### ISSUE TITLE
c: geo crashes when opening offline map with routing

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6258]
##### Detailed steps causing the problem:
- Open a cache
- Routing enabled and set to "Car"
- Offline map is selected
- Go to the waypoints page
- Choose a "certain" waypoint
- Show map including routing for that waypoint

##### Actual behavior after performing these steps:
c:geo crashes.
c:geo also crashes on that certain waypoint when routing is disabled (Straight line) and then changed to "Car".
It does not crash on Google Maps (GM). I guess because routing seems to be disabled with GM.

Not sure why some waypoints trigger this. But they do that reproducible.

##### Version of c:geo used:
See System Information.

##### Is the problem reproducible for you?
Yes, for certain waypoints.
As the problem is routing related the current GPS position might be also relevant for reproducing the crash.

##### System information:
```
--- System information ---
Device: D5503 (D5503, Sony)
Android version: 5.1.1
Android build: 14.6.A.1.236
Cgeo version: 2017.01.15-NB-6e9a53e
Google Play services: disabled - 10.0.84 (236-137749526)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE (cgeo forced to English)
Log date format: 15/01/2017
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Thanks @Matze2 for your report.
I am just now building a new RC version. Please kindly restart c:geo in >10 minutes from now, it should then show a new nightly notification. Please retest your issue with that version as I assume it was fixed 
Reference to #6255

**Comment by Lineflyer** [comment]
New nightly should now be available.

**Comment by Matze2** [comment]
Wow! Now the fixes are done before the report comes in :)

Using 2017.01.15.NB1 the issue seems to be gone. Well done!
