### ISSUE TITLE
ci.cgeo.org is out of service

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#6277]
> Service Temporarily Unavailable
> 
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Seems to be an aftermath of @mucek4 rebooting the CI yesterday.

**Comment by mucek4** [comment]
Ok. Network issues between web server and CI server are restored. The problem now is , that all slaves are reported "offline". If they get online in timely fashion i'll close the issue.

**Comment by mucek4** [comment]
@samueltardieu restarted slaves.
