### ISSUE TITLE
Streetview has stopped working....

### ISSUE THREAD

**Issue by Bugsy1905** [cgeo/cgeo#6278]
##### Detailed steps causing the problem:
- Since the last back up I haven't been able to use Streetview.
- If the cache was along the roadside I used to be able to check out the surroundings. It states it's not available here.
- Streetview works perfectly well when on Google Maps so I know it isn't a problem with the app itself.

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: D5803 (D5803, Sony)
Android version: 6.0.1
Android build: 23.5.A.1.291
Cgeo version: 2017.01.15
Google Play services: enabled - 10.0.84 (436-137749526)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB (cgeo forced to English)
Log date format: 22/01/2017
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd/MMM/yyyy
Installed cgeo plugins: calendar
--- End of system information ---
```

**Comment by samueltardieu** [comment]
Four attempts on `master` indeed fail for me with "no street view available at this address" (http://coord.info/GC3P604 for example).

**Comment by Bananeweizen** [comment]
Similar experience here. According to the [documentation](https://developers.google.com/maps/documentation/android-api/intents?#street_view), our intent is perfectly fine.

**Comment by Lineflyer** [comment]
Its working for me (right now) e.g. for GC3P604

**Comment by Lineflyer** [comment]
@Bugsy1905 Can you recheck?

**Comment by Bugsy1905** [comment]
I have rechecked this issue and this has seemed to have disappeared now and working fine. Not sure what has changed....

**Comment by Lineflyer** [comment]
Thanks for your feedback. Maybe a temporary at Google.
