### ISSUE TITLE
Mapsforge Beta - render performance

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6279]
I've mentioned this before, but with the recent update I feel compelled to mention it again. 

1. Go to live map. go to a certain map area. (see scroll, zoom, render speed)
2. enable live (downloading of caches on the map)
3. open a cache
4. open menu, choose navigate, choose map (mapsforge beta)

See render speed of the same area that you were being shown previously, using the older mapsforce library.

Tested on a higher performance device : Huawei Ascend P7. 
CPU: Quad-core 1.8 GHz Cortex-A9; 2GB RAM; GPU: Mali-450MP4
Not the latest top of the line smartphone, but still, pretty good performance.

The render speed is visibly slower, guestimating less then half compared to the older library.

On my regular device, Allview P5 Quad,
CPU: Quad-core 1.2 GHz Cortex-A7; 1GB RAM; CPU: PowerVR SGX544
the render speed is significantly (I'd say horribly) slower.

I presume this is either due to some integration factor, or is an issue that needs to be escalated to the authors of mapsforge. 

Note: @Lineflyer mentioned here https://github.com/cgeo/cgeo/issues/6032 during previous tests and reports by myself, that render speed looks fine on the Samsung Galaxy S7. 
I must reiterate this comment: 

> Testing such performance issues on a very high performance device doesn't really prove anything.
> The Samsung S7 is among the top highest performing devices one can get. And the matching price tag as well.
> One cannot expect most users of the app to have such a device.

**Comment by Lineflyer** [comment]
@rsudev Do you have any clues or figures on the mapsforge library performance? Did the mapsforge project itself maybe make any statement about the performance of v3 versus v6?

@andrixnet: 
As I sadly have no suitable device for having a loook at the performance (I tried with my Samsung S3 but it is still not recognized to be slower as on my S7), can you maybe post a video / screen-video of your experience on the P5 Quad.

**Comment by Lineflyer** [comment]
@andrixnet Meanwhile the nightlies are based on mapsforge libraries v9 and the "beta map" has been promoted to the default one used. Can you give any feedback regarding the performance of the map in the current nightlies on your device?

**Comment by andrixnet** [comment]
will make some tests in the next few days

**Comment by Lineflyer** [comment]
@andrixnet Any feedback with the new nightlies?

**Comment by andrixnet** [comment]
Damn it, I knew I forgot something. 
I did several tests just the day after my post a month ago, but apparently forgot to post the results.
At that time I was still able to see a significant performance difference between older and newer mapsforge. 
Test scenario was a Huawei Ascend P7 ( https://www.gsmarena.com/huawei_ascend_p7-6124.php ) with my standard geocaching setup. 
mapsforge beta took at least twice as long to generate.

I must redo the tests, I'll try to make a short video as well.

**Comment by andrixnet** [comment]
Here is a video comparison of mapsforge (old) vs. mapsforge beta render performance: 
https://youtu.be/xpxsEuZOLXI

Here is a video showing c:geo nightly build with new mapsforge (previously beta) only render performance: 
https://youtu.be/k9aKaK2dME0

As you can see, in both videos the render performance of newer mapsforge is very similar and clearly lower then that of the previous maspforge library.

Surely, on a high end device the difference is much less observable. 
But take a low to mid range device, or a good but not so new device and the difference is much higher.
Have any more load on the CPU (other then c:geo and system) and the render will be much slower.

(for example on my Huawei P7, Google Play updating apps in the background will seriously affect map render performance). 

Map file is romania.map from Official mapsforge download site, though not the latest data file.

**Comment by Lineflyer** [comment]
Thanks @andrixnet 
Especially the first video is very helpful to see the difference. Interesting enough I tested it with the germany.map file on my Samsung S3 and S4 (both rather old devices) and the tile population is still faster than in your video.

No idea, what might be causing this...seeing that also a P7 is not such a bad device.

Just a pure guess to see if something changes:
Can you try to disable HW acceleration in c:geo Menu/Settings/System just to see if this makes any remarkable difference (worse or better)?

**Comment by andrixnet** [comment]
Hardware acceleration checkbox makes no difference to me. 
Today I can even see the difference on my Samsung S6. 
Will get an S9 next month, eager to test it.

**Comment by andrixnet** [comment]
Well, the huge processing power of the S9 shows and I can barely see a difference now. 
I still need to check current version on less then high-end device(s) to be able to give a proper report.

**Comment by Lineflyer** [comment]
@andrixnet 
Could you please test the rendering speed with a nightly starting today?
We recently improved the rendering speed by finding a neat parameter within the mapsforge libraries which subjectively speeds rendering up a lot on my devices.

**Comment by andrixnet** [comment]
Will return with tests.

**Comment by andrixnet** [comment]
I made comparative tests between c:geo 2019.06.06 and 2019.08.13-NB-864825c
I used a Huawei P7 phone with the same configuration and software (but updated) that I used for a long time until early 2018. Today that phone has considerably slowed down (likely due to higher complexity of updated apps) and consequently (being slow) is a very good testbed to highlight performance issues. 

- c:geo release 2019.06.06
* mapsforge v3 performance is better
   = renders a larger area
   = rendering more tiles, faster
* mapsforge v4 performance is lower
  = renders a smaller area (same location, same map view, no user requested zoom)
  = renders fewer tiles (thus generating larger individual bitmap tiles)
  = render is overall slower

-c:geo 2019.08.13-NB-864825c
* by c:geo version comparison, both v3 and v4 behave the same
* v3 is faster
* v4 is slower, approximately the same slower speed
* I was unable to sense a percievable performance boost (as advertised)

I created 2 videos with these tests. If need be, I can share them.

**Comment by jonas-koeritz** [comment]
What's "v3" and "v4"?

**Comment by moving-bits** [comment]
> What's "v3" and "v4"?

I think it refers to the "old Mapsforge" implementation, which was v0.3 library version (and supported the Mapsforge file format v3).

The "NewMap" c:geo uses currently is v0.11 library version on master branch (v0.9 on release) and supports Mapsforge file formats up to v5 (IIRC).

**Comment by andrixnet** [comment]
Sorry about the confusions. 
v3 refers to what c:geo UI calls "Old Mapsforge v3".
v4 refers to the newer version (post v3), which I personally knew as v4 from discussion with c:geo developers soon after it's introduction. 
I do not know the internals sufficiently and this report is from end-user perspective.

Thank you.

**Comment by jonas-koeritz** [comment]
Thanks for clearing this up!

andrixnet <notifications@github.com> schrieb am Do., 22. Aug. 2019, 10:29:

**Comment by jonas-koeritz** [comment]
My device (Pixel 2 XL) definetely is not suitable to compare any performance. Could it be that this is related to the fix that handled the scaling issue? You're reporting that the loaded tiles are larger on the newer builds, rendering a larger tile could possibly take a bit longer but rendering less tiles (because the screen consists of less, but bigger, tiles) should lead to roughly the same speed to fill a screen.

I don't think we only can do so much to improve the situation, we're kind of dependent on the latest mapsforge because of the compatibility issues with later Android versions. 
Somebody should try to reproduce this on the mapsforge demo application to file a bug with them.

Maybe the options to change the theme add some additional performance penalty as well?

**Comment by andrixnet** [comment]
@jonas-koeritz would it help to show you a couple of videos ?

**Comment by jonas-koeritz** [comment]
I think so, If we could pinpoint what part of the drawing is slower that would be good to know.
I assume that the newer mapsforge versions simply add more processing steps to the map rendering but the difference is negligeble on my device, I have been profiling the offline map rendering before, when I implemented the "speed fix".

**Comment by andrixnet** [comment]
Next week I'll get hold of a Samsung J3 (2017), which is a lower end device, quite slow today.
Will return with sample videos.

**Comment by Lineflyer** [comment]
@andrixnet Any new experience or sample videos?
I had the chance to test with a Samsung A70 last month and the performance was subjectively acceptable.

**Comment by fm-sys** [comment]
Is it still relevant or can we close this issue? While we only support the _new_ Mapsforge nowadays, render performance is probably something what is out of our hands...

**Comment by andrixnet** [comment]
Didn't get that J3 after all :-( 
Anyway, given the technical context, I agree with @fm-sys

**Comment by moving-bits** [comment]
If I'm not mistaken there is a multi-thread option for Mapsforge rendering which we don't use yet, and which might speed up tile rendering significantly. I'll open a separate issue for it.
