### ISSUE TITLE
Route disappears

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6281]
##### Detailed steps causing the problem:
1. have mapsforge beta enabled
2. have BRouter installed and configured
3. have default navigation = map
4. open live map. Enable live (not really necessary if youy have stored caches)
5. click on a cache. 
6. from summary window, click circle with arrow pointing right-up
**route to cache is shown**
7. open again summary window
8. click on navigate icon
**cache is shown centered on map, with route from your position to it.**
9. click back (to return to initial map view)

##### Actual behavior after performing these steps:
- route changes to straight line
- routing dissapears from the menu
- subsequent route requests result only in straight line (like step 6 above) for any cache

you need to do this to restore routing function: 
1. go back to main screen
2. open map again

##### Expected behavior after performing these steps:
One would expect routing function to be available like any other functions.

##### Version of c:geo used:
2017.01.15

##### Is the problem reproducible for you?
Yes

##### System information:
```
Device: HUAWEI P7-L10 (P7-L10, Huawei)
Android version: 4.4.2
Android build: P7-L10V100R001C00B133SP01
Cgeo version: 2017.01.15
Google Play services: enabled - 10.0.84 (038-137749526)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: en_GB
Log date format: 2017/01/23
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / BASIC
opencaching.ro: Logged in (Login OK)
Geocaching.com date format: yyyy-MM-dd
Installed cgeo plugins: none
```

**Comment by Lineflyer** [comment]
I can reproduce the reported problem with the steps above.
However: What is the use case for opening another map instance while a map instance is already opened?

**Comment by andrixnet** [comment]
Since I have default navigation set by me to map instead of the installation default = compass, it quite frequently happen that I open a cache from the map, then perform an action that takes me to the map, though not via the BACK path.
