### ISSUE TITLE
calendar time recognition requires space

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6285]
GC6YYR8 contains "... ab 18:00Uhr (das..." and is not recognized.

**Comment by pstorch** [comment]
There are two issues here:
1. we match up to 4 different patterns, the first pattern match wins. In this example the `20:30 Uhr` end time is matched first and `18:00Uhr` start time would be the second match (but is skipped).
1. the `Uhr` is localized. My device is set to english, so it wouldn't match `18:00 Uhr` at all. This hour postfix only works if the cache description is in your configured language.


To fix the first problem we would need to analyze all matches and select the lowest time value.

**Comment by pstorch** [comment]
For 1. I've created a fix #6285.
Do we want to handle 2. here as well or open another issue?
