### ISSUE TITLE
Timezone question

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6286]
Maybe no bug, just a question:

Do we get (or assume) any time zone information when parsing an event cache?

I am asking because I had some scenario like this:
- Have phone set to GMT+1
- Save an event cache
- Event cache date is the correct date as shown on website
- Set phone to GMT-6
- The saved events date is now one day earlier

Greetings from Panama (what explains why I just discovered the problem).

**Comment by pstorch** [comment]
What is your timezone on geocaching.com? https://www.geocaching.com/account/settings/preferences

**Comment by pstorch** [comment]
BTW: only 5 caches in Panama? :scream:

**Comment by Lineflyer** [comment]
UTC+1 is set on the website, but do we consider this somewhere?

**Comment by pstorch** [comment]
Didn't see any code dealing with timezones. I guess when the server timezone preference with your device timezone, then everything should be fine. 
But to be honest I didn't look too closely.

**Comment by pstorch** [comment]
Pretty sure that GC doesn't provide timezone information with dates. To solve this we would have to read the TZ preferences as we read the date format and then convert it appropriately. I guess the API would provide TZ information. At least the other connectors have that. As far as I checked.

**Comment by Lineflyer** [comment]
>  To solve this we would have to read the TZ preferences as we read the date format and then convert it appropriately. I guess the API would provide TZ information. At least the other connectors have that. As far as I checked.

I am not sure about this:
When we store the publish date (=event date) in our database when parsing the cache it looks to me as if we assume a timezone (the current device timezone?) and save it along. So the most simple solution IMHO could be just to save the simple date w/o any time zone and don't start dealing with timezones at all.

**Comment by pstorch** [comment]
In the DB the dates are saved as long (milliseconds since 1.1.1970 UTC). Every conversation to a Java Date or Calendar uses local (device)  timezone. 

Proper Timezone handling is a programmers nightmare: https://youtu.be/-5wpm-gesOY
Had to deal with timezones in my last job.

**Comment by Lineflyer** [comment]
> Proper Timezone handling is a programmers nightmare: https://youtu.be/-5wpm-gesOY
Had to deal with timezones in my last job.

I can imagine this.
Half of my apps on my smartphone showed bugs in one or the other way after traveling through four different timezones the last weeks (e.g. step counter is completely wrong, smart watch calendar app shows garbage although all events have correct timezones in my calendar, Google location history shows me on different locations at the same time).

> In the DB the dates are saved as long (milliseconds since 1.1.1970 UTC). Every conversation to a Java Date or Calendar uses local (device) timezone.

That is probably  the reason for the problem I have seen in c:geo.
I guess we also use the device timezone to initially convert the parsed date information into the millisecond format. After changing my local time zone the reconversion into a date will give another result. No easy way to solve this (without introducing time zone handling) I guess?!

**Comment by pstorch** [comment]
> I guess we also use the device timezone to initially convert the parsed date information into the millisecond format. 

Correct. 

> No easy way to solve this (without introducing time zone handling) I guess?!

I think so.

**Comment by Lineflyer** [comment]
Thanks. Closing then.
