### ISSUE TITLE
Allow c:geo to be installed on more devices using play store

### ISSUE THREAD

**Issue by spinnekopje** [cgeo/cgeo#6290]
Feature request:
Allow c:geo to install on devices which can not install c:geo now (probably because the lack of gps) using the play store, so it can be used to plan trips or post logs with minimal data usage.

Use case:
When traveling I try to import caches at home using a PQ or create a small PQ where we are, so I have all interesting caches imported in c:geo. Using the map feature I can easily plan a (hiking/bike) trip or select a cache to log (with live off). 
When logging I do not need data usage anymore to select the cache I want to log, only for the logging itself within the app I use data. For searching I even don't need extra data usage.

I could do just that with our old tablet (transformer tf101), but after replacing it with a chromebook with play store I can not install c:geo. (Pocket Query Creator can be installed and works as expected using google location services). Since the tf101 never managed to get a gps position there shouldn't be a problem using c:geo on the chromebook, unless I'm not allowed to install in via the play store for another reason.

**Comment by SammysHP** [comment]
This was a decision we made several times, see #5980 for example.

There is always the possibility to install c:geo manually from you website (http://cgeo.org/) or f-droid. You'll receive update notifications from inside the app.
