### ISSUE TITLE
Recommendation of Cyanogenmod in FAQ

### ISSUE THREAD

**Issue by nmxcgeo** [cgeo/cgeo#6291]
##### Detailed steps causing the problem:
- Open c:geo-FAQ (http://www.cgeo.org/faq.html#legacy)

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
According to several sources (e. g. https://en.wikipedia.org/wiki/CyanogenMod) the development of Cyanogenmod is carried on under the new project name LineageOs (http://lineageos.org). The old websites are not reachable any more and no download can be performed.

Therefore a new source for customROMs should be linked. I would suggest to link to LineageOs as it's the same project under a new name.

Greetings.
Nmxcgeo

SORRY, I JUST SAW, THAT I'M IN THE WRONG REPOSITORY FOR THIS ISSUE

**Comment by SammysHP** [comment]
You can find the repository for the website here: https://github.com/cgeo/cgeo.github.io
