### ISSUE TITLE
Disable projection field in waypoint edit for WPs with coords

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6292]
Not sure if I followed all changes regarding the waypoint storage correctly, and I need some more days to understand the changes.
However I do see, that for waypoints with coords the editing of those is disabled for a good reason.
But still the fields for the projection (distance, direction) are editable and filling these and saving the waypoint will still modifiy the waypoints coords accordingly.
I think this should either be blocked as well or (preferably as it is a use case for me) offer the user to create a new waypoint with the projected coords.

**Comment by pstorch** [comment]
Oh, you are right. I overlooked these fields. 
I think we should disable/hide these fields. Or start the AddWaypointActivity with the results of of the projection. Would be more comfortable.

**Comment by Lineflyer** [comment]
After playing a bit around with the new waypoint strategy I would propose the following:
Users might previously have altered the coords or used the projection on existing waypoints. We should try to keep this usage by e.g.:
1. Remove the projection fields for waypoint with non editable coords
2a. Use this space for new buttons "Duplicate WP" (same as the context function from waypoint tab) and "Use WP for projection" (similar to duplicate but ask for projection data before creating) 
2b Instead of select buttons use a menu which opens when clikcing on the coords.

**Comment by pstorch** [comment]
From IRC logs: http://irclogs.cgeo.org/?year=2017&month=2&day=4

```
21:56:12Lineflyer: So the minimum solution for now could be: Keep the fields in user defined WPs and remove them for WPs with non editable coords. Add a menu for "Duplicate WP" and "Copy Coords" to the non editable coords.
```
