### ISSUE TITLE
Missing visual separation in cache gallery 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6293]
##### Detailed steps causing the problem:
- Open e.g. GC6CCA
-  Swipe to open the gallery tab

##### Actual behavior after performing these steps:
If a picture has no title it is directly appended below the newer pictures which makes it look like all pictures belong to the same section (=title).
Example: Section "Lineflyer@VargasPark" contains four pictures - The first picture belongs to this title, the three pictures below are from other (untitled) log photos from other logs/cachers.

##### Expected behavior after performing these steps:
Instead of ommiting the section/separation we should use the default ("Bild") or maybe change the general style by using `<Cacher name> - <Picture title>`. In this case sections for pictures without title still the cacher name would be used as the title.

##### Version of c:geo used:
2016.02.04-NB

**Comment by pstorch** [comment]
We don't have the `Cacher name` at this point in the code (would be a bigger change to have it there) and I think it would get too long. Some cachers also prefix there images with `cachername@...` so we would duplicate it.
Simply having a generic divider with `Image` would improve this view. I'll add it.
