### ISSUE TITLE
f-droid nightly job is hanging

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6294]
A user informed us by mail, that there is no new f-droid nightly since approx. 15.01.
Indeed I can see that somethink is hanging here: http://ci.cgeo.org/job/Publish%20FDroid%20-%20NIGHTLY/

**Comment by Lineflyer** [comment]
It seems the slave for fdroid is offline: http://ci.cgeo.org/computer/fdroid/
How to restart this?

@kumy

**Comment by kumy** [comment]
I ll take a look tomorow. dedicated fdroid executor is down. :(

On February 5, 2017 11:28:40 AM GMT+01:00, Lars <notifications@github.com> wrote:
>A user informed us by mail, that there is no new f-droid nightly since
>approx. 15.01.
>Indeed I can see that somethink is hanging here:
>http://ci.cgeo.org/job/Publish%20FDroid%20-%20NIGHTLY/
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6294

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
Executor was in error loop:

```
Failing to obtain http://ci.cgeo.org/computer/fdroid/slave-agent.jnlp?encrypt=true
java.io.IOException: Failed to load http://ci.cgeo.org/computer/fdroid/slave-agent.jnlp?encrypt=true: 503 Service Temporarily Unavailable
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:275)
	at hudson.remoting.Launcher.run(Launcher.java:219)
	at hudson.remoting.Launcher.main(Launcher.java:192)
Waiting 10 seconds before retry
```

I've recreated the container, but now it doesn't find the config file. I'll take a deeper look tomorrow.
I've manually disabled the job.

**Comment by kumy** [comment]
So after taking time to look what was wrong. I've finally found that my local docker image of [cgeo/cgeo-fdroid](https://hub.docker.com/r/cgeo/cgeo-fdroid/tags/) ([cgeo/cgeo-fdroid repo](https://github.com/cgeo/cgeo-fdroid)) was outdated. Moreover, there was an error in the Dockerfile from the repo (build-tools were not installed). I've probably fixed thing directly in the container without reporting changes to the git repo :(.
Everything should be ok now, please reopen if needed.
