### ISSUE TITLE
Extract waypoints menu only visible for saved caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6296]
##### Detailed steps causing the problem:
- Open an unsaved caches
- Select Menu (three dot)

##### Actual behavior after performing these steps:
No menu item "Extract waypoints" visible unless the cache is saved

##### Expected behavior after performing these steps:
We should avoid such dependencies as it also makes the feature less acessible.
Instead I suggest autosaving the cache (same as when a user edits a waypoint of an unsaved cache) as soon as the function is selected

##### Version of c:geo used:
2017.02.04-NB

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
Just realised that there are some menu entries in the Map Popup which don't work:
- extract waypoints (that I wanted to work on)
- export
  - GPX
  - Fieldnotes
  - Personal note

**Comment by Lineflyer** [comment]
IMHO the items to export and extract waypoints are not really needed in the map popup. I guess no one would require these functions from the popup but only from the cache details screens.

**Comment by pstorch** [comment]
OK, it's much easier, if I can remove them there.
