### ISSUE TITLE
Extract waypoint function should provide result

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6297]
After executing the function "Extract waypoints" it might or might not be succesful in extracting waypoints.  It also happend to me, that it took some time until the extracted waypoints finally showed up in the waypoint tab (I suspect the process was still running while swiping to the waypoint tab).

We should provide a feedback to the user about the result of the extraction.
This could be done with a small toast like "Extracted x waypoints from cache description" / "No wapoints found in cache description"

**Comment by pstorch** [comment]
While working on #6296 I realized that I miss a feedback from the extract wp function, too. So I do this first, to have it easier to test.

**Comment by Lineflyer** [comment]
Tested and working with 2017.02.06-NB1 (Tested with GCJBZX)
