### ISSUE TITLE
Waypoint tab not refreshed after extracting waypoints

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6298]
##### Detailed steps causing the problem:
- Open a saved caches which contains extractable coords in the cache description
- Swipe to the waypoint tab
- Select Menu -> Extract waypoints

##### Actual behavior after performing these steps:
Waypoint tab does not show the extracted waypoints. The user needs to swipe two screens to the right and back again to get it updated.

##### Expected behavior after performing these steps:
Screen should be refreshed to show the new waypoints after extraction process has finished.

##### Version of c:geo used:
2017.02.04-NB

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
Fixed together with #6299
