### ISSUE TITLE
Crash after inserting coords into personal note field

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6300]
From Google Play:

```
java.lang.NullPointerException: Attempt to invoke interface method 'void cgeo.geocaching.activity.AbstractViewPagerActivity$PageViewCreator.notifyDataSetChanged()' on a null object reference
	at cgeo.geocaching.CacheDetailActivity.onFinishEditNoteDialog(CacheDetailActivity.java:2367)
	at cgeo.geocaching.ui.EditNoteDialog$2.onClick(EditNoteDialog.java:101)
	at android.view.View.performClick(View.java:5201)
	at android.view.View$PerformClick.run(View.java:21209)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

User comments all like:
- Crashes after pasting coords into personal note
- Crash when saving personal note after coordinate input

**Comment by pstorch** [comment]
Is it from beta version?

**Comment by Lineflyer** [comment]
Oh, forgot to mention: 2017.01.15 (not the beta) but also older versions.

**Comment by Lineflyer** [comment]
More reports of this problem on social media and support mail.
Users say its not clearly reproducible.

**Comment by FreddieSanchez** [comment]
Do we know the exact text being added or the format of the coordinates?

**Comment by ladethub** [comment]
I also have the same issue inserting just a single texte, whitout GPS coordinates .

**Comment by pstorch** [comment]
One example of the german FB c:geo FanGroup is "N 51°49.900 E 1".
But I don't think the input String is the cause here. The code shows the `CacheDetailActivity.onFinishEditNoteDialog()` which is called when the user confirms the dialog.
Somehow the Waypoint page is null. Maybe some race conditions? Is it called twice maybe? Or is there another update/refresh process concurrently updating the pages?

**Comment by Lineflyer** [comment]
mmh...
If a note is created for an unsaved cache the cache is saved in background...but that should not be conflicting...

**Comment by pstorch** [comment]
It would be easy to check for NULL at this point, but I would like to understand the cause.

**Comment by pstorch** [comment]
Here the Screenhosts from one user:
![16649383_1106416566152131_3277393803389606370_n](https://cloud.githubusercontent.com/assets/5598124/22846929/4f124f50-efea-11e6-844a-7073f67191dc.jpg)

![16603089_1106416569485464_858858733485836929_n](https://cloud.githubusercontent.com/assets/5598124/22846927/4d7ecef2-efea-11e6-91a4-b5a30752bef4.jpg)

**Comment by FreddieSanchez** [comment]
It looks like he has a note stored already and  is editing it.

**Comment by ladethub** [comment]
I sent à crash report today throught Google Play Store regarding this issue. On the system information screen of the report, we can see thé following :
![screenshot_2017-02-11-11-37-59-339_com google android gms](https://cloud.githubusercontent.com/assets/21060045/22853182/a39e46c2-f04f-11e6-8a64-6bc0f99433af.png)

My device is Xiaomi Redmi Note 1W, MIUI 8.0.1.0 (Android 4.4.2).

**Comment by pstorch** [comment]
@ladethub thanks for the report. 
Maybe @Lineflyer can check it, if it is the same or something else. But it looks like the same from your description. 
I still don't know what could cause this. Maybe we should just check for NULL here and see if it fixes the problem.

**Comment by Lineflyer** [comment]
@pstorch Don't you also have access to the Play console?
However I quickly looked it up...its different and quite strange IMHO:
```
java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.appendIfMissing
	at cgeo.geocaching.ui.EditNoteDialog.onCreateDialog(EditNoteDialog.java:70)
	at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1026)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:493)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5328)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Lineflyer** [comment]
That reminds me of #5766 where we also had to work around a Xiaomi bug.

**Comment by pstorch** [comment]
Oh, now I see it. It is in `onCreate()`, that is different indeed. 
@Lineflyer no, I don't have access to to the Play console.

**Comment by Lineflyer** [comment]
For me it would be perfectly fine If you get access. You just need to give @mucek4 your gmail adress.

**Comment by pstorch** [comment]
@Lineflyer I've commited some code to prevent those two Exceptions. But due to lack of reproducability on my side I can't test if it really fixes those. Is it possible to build an RC and ask @ladethub and the other user on FB if they want to test it?

**Comment by Lineflyer** [comment]
Sure. Will do tonight.

**Comment by ladethub** [comment]
Thanks. I'll try as soon the new RC is available. A friend of me have the same issue on a Xiaomi device too. I'll ask him to test with me the new RC.

Thanks for your job.

**Comment by Bananeweizen** [comment]
We will probably see similar issues again and again. Something is entirely wrong with Xiaomi devices, since they crash a lot with NoSuchMethodExceptions in StringUtils in all kinds of apps, where that code is known to exist. http://lmgtfy.com/?q=xiaomi+stringutils+nosuchmethodexception

**Comment by Lineflyer** [comment]
Maybe we could report it. At least [here](http://en.miui.com/forum.php) (which I assume is the official forum) I could not find anything related with their search function.

**Comment by Lineflyer** [comment]
@ladethub A new release candidate version was built and is available for download [here](http://download.cgeo.org/cgeo-RC.apk). It would be good if you could sideload and install from there as I don't want to put it into the beta channel of Google Play right now.

@pstorch You could provide the RC download link to the affected user on FB.

**Comment by ladethub** [comment]
Tested this RC this morning ans all is working fine now. My friend has tested this new package too and all is OK for him now.

Thanks a lot for your great job.

**Comment by pstorch** [comment]
@ladethub thanks for your fast Feedback.

**Comment by Lineflyer** [comment]
@pstorch So we can close this one?

**Comment by pstorch** [comment]
@Lineflyer let's close here. We have one positive feedback. The other user from FB hasn't responded since a week.
