### ISSUE TITLE
GPS and Magnetic Compass Used box appears when rotated

### ISSUE THREAD

**Issue by FreddieSanchez** [cgeo/cgeo#6302]
##### Detailed steps causing the problem:
- Have a phone without Magnetometer (Compass) sensor (Moto G4).
- Select a cache
- open the compass
- Do not see the "GPS and Magnetic Compass Used".
- rotate the phone from portrait to landscape

##### Actual behavior after performing these steps:
- The  "GPS and Magnetic Compass Used" box appears when rotated to landscape and remains after rotated back to portrait mode.

##### Expected behavior after performing these steps:
- The  "GPS and Magnetic Compass Used" box should not appear when rotated to landscape and should not appear when rotated back to portrait mode.

##### Version of c:geo used:

2017.01.15

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: Moto G (4) (athene, motorola)
Android version: 6.0.1
Android build: MPJ24.139-64
Cgeo version: 2017.01.15
Google Play services: enabled - 10.0.84 (438-137749526)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: en_US
Log date format: 2/6/17
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d.M.yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Sadly I don't have a device for testing this scenario. But due to the precise error description I think it might really be a bug.

**Comment by FreddieSanchez** [comment]
I have this device, and can would like to try to fix it. Recently got the development environment setup.
