### ISSUE TITLE
Natural sort by geocode

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6306]
##### Detailed steps causing the problem:
- Open list of caches
- Sort by geocode

##### Actual behavior after performing these steps:
Caches are sorted lexicographically/alphabetically.

```
GC1ABCD
GC2345
GC56EFG
GC77
```

##### Expected behavior after performing these steps:
Natural sorting, for example:

```
GC77
GC2345
GC1ABCD
GC56EFG
```

**Comment by pstorch** [comment]
Interesting issue. We would need to calculate the Base 31 code to an integer and sort by this.

**Comment by pribeiro42** [comment]
Wouldn't be easier if you sort by lenght and then alphabetically?

**Comment by pstorch** [comment]
Sure, but that is boring ;)

**Comment by Bananeweizen** [comment]
BTW: You get the same result even without the change by just selecting sorting by age (assuming you are not mixing different websites).

**Comment by steve8x8** [comment]
Sorting by age may be misleading. People grab a cache GCcode, then take their time to prepare for publication. Have seen 1 yr delay myself.
Cache id (as used in gpx export) is what to look for.
