### ISSUE TITLE
Have "Add Waypoint" on top

### ISSUE THREAD

**Issue by Edje3001** [cgeo/cgeo#6308]
If you are adding a lot of waypoints for a (multi)cache newly created waypoints are at the bottom of the list with the add button below the list. To add a new waypoint you always have to scroll down (swipe up) first to access the "Add waypoinr"-button. Same goes to access (or use) a newly created waypoint.

Suggestion is to create a setting to show waypoints in reverse chronological order (newest on top), with the "Add waypoint"-button right above the list, or not (as it currently is).

**Comment by Lineflyer** [comment]
That doesn't necessarily need to be an option but we could think about adding the new waypoint button always on top. 
Another point is, that we always start at the top when returning to the waypoint tab...AFAIR this is already covered by another issue

**Comment by Edje3001** [comment]
By "AFAIR this is already covered by another issue" do you mean showing waypoints in reverse order is already requested in another FR?

BTW: the button always on top would be nice anyhow!

**Comment by Lineflyer** [comment]
> By "AFAIR this is already covered by another issue" do you mean showing waypoints in reverse order is already requested in another FR?

Yes, at least something mentioning that the need of always scrolling down (or not remembering the last position) is a pain. But cant find it right now.

However let me use this issue to adress the "Button always on top" sugestion for now.
