### ISSUE TITLE
Highlighting\selecting caches worth visit

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#6313]
It's more a topic to think about than an detailed feature request. Or maybe someone could give me a hint how to manage this situation.

Case:
- I'm arriving to a new city (i.e. San Francisco) where there are dozens and dozens of existing caches.
- I have limited time and I don't want to visit crappy caches like "It's my favorite garbage bin and I decided to create a cache here".
- When I open the map, I see hundreds of caches around, often more than one in each city block
- Problem statement: I want to visit as much as possible "good" caches in some district and as less as possible "bad" caches. Criteria for "good" and "bad" very depends on a lot of things (read as "some personal filters")

Right now I used following approach: scan caches manually and save offline log "need maintenance" for caches I wanna visit. So they became visible on the map and I can distinguish my selected caches from all caches in the area.

Important notice: I still want to see all the caches in the area, because even if it's "garbage bin cache" but it's in 5-meters radius from my location, I will visit it. I just don't want to spend extra time, but if it's near - I'll grab it.

One of possible solutions which could be enough for my purposes:
- Use filter "More than N favorite points" and **highlight** those caches
- While scanning caches around manually, have ability to "highlight" some caches manually.
- So there will be some list of "highlighted" caches. I would like to see them actually highlited on the map, i.e. having "star" symbol over the cache icon of something like this so I can easily see several caches I want to visit across all hundreds of existing caches.

As usual, sorry if duplicate or if there is already working solution, but I didn't find it by my own.

**Comment by SammysHP** [comment]
See also #3523, #5373, #5798 and #6187.
