### ISSUE TITLE
Cache description can't be shown if one image has an error

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6316]
##### Detailed steps causing the problem:
- Open Cache https://coord.info/GC59KT4

##### Actual behavior after performing these steps:
Error message: `c:geo can't load description.`
On description tab only a loading spinner is shown instead of the description.

##### Expected behavior after performing these steps:
Show description with missing image

##### Version of c:geo used:
`master`, 6b4cdbc

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
The cache description contains one errornous image tag:
`<img alt="" class="thumbimage" />`
It has no URL (no src attribute).

I don't know if we want to fix it, because the error is in the listing. But it would be more user friendly to ignore it (or show a broken image placeholder).

**Comment by Lineflyer** [comment]
Confirmed

**Comment by Lineflyer** [comment]
I am no HTML expert, however from users perspective:
I can see the listing in my browser, so I should be able to see it in c:geo.
At least showing an endless spinner is definitely not intentional...is it?

**Comment by pstorch** [comment]
Definitely not user friendly.

**Comment by pstorch** [comment]
Interesting it is working on `release` branch.
Git history shows that 59f584e60ab0a62923f3fbb2ee8ea780976c8d71 changed the behaviour and doesn't allow missing URLs. 
@samueltardieu can you have a look?
