### ISSUE TITLE
IDEA: Untrack IML files?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6317]
After upgrading the ignore plugin in Android Studio I was greeted with a suggestion to untrack all the *.iml files we have in the repository. I only know those are "somehow" related to the IDEA settings, but I have no idea of the implications of having or not having them. Can one of the IDEA experts please judge the recommendation of that plugin?

**Comment by pstorch** [comment]
There was an issue some time ago where we decided to ignore the *.iml files.

**Comment by pstorch** [comment]
See #5581

**Comment by pstorch** [comment]
Maybe we should continue the discussion from #6533 here.

I would like to try the recommendation from: https://tips.seebrock3r.me/share-the-settings-with-the-whole-team-android-studio-protip-6-3cce16eb2ea4 in a branch. Then we could try with our local installations, change some run configurations, install/configure some plugins etc. and report back what happens.

**Comment by pstorch** [comment]
I work with Android Studio 2.3.1. Would be good if we have different versions to test the branch with.

https://github.com/cgeo/cgeo/tree/6317_share_idea_settings

**Comment by Lineflyer** [comment]
@pstroch Can we delete the branch mentioned above or is it still good for anything? Just loooking into cleaning up stale branches.

**Comment by pstorch** [comment]
From my point of view it can be deleted.

**Comment by moving-bits** [comment]
can we close this old issue?

**Comment by bekuno** [comment]
The mentioned branch is deleted, IDEA is stable for us.
Let's close.
