### ISSUE TITLE
Crash when adding a waypoint 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6318]
##### Detailed steps causing the problem:
- Open GC6Y8T8
- Swipe tp waypoint tab
- Click "Add waypoint"
- Click on coordinates field

##### Actual behavior after performing these steps:
Crash

Picture of Stacktrace:
![screenshot_20170212-171633](https://cloud.githubusercontent.com/assets/949669/22863827/3bc8f2a6-f147-11e6-96ec-d3cbb1e6dd42.png)

##### Expected behavior after performing these steps:
Coordinates can be edited without crash

##### Version of c:geo used:
2016.02.12-NB

##### Is the problem reproducible for you?
Yes (on the mentioned cache)

##### Other comments and remarks:
@pstorch I guess this is a side effect of your latest waypoint handling changes?

**Comment by pstorch** [comment]
I'll have a look

**Comment by pstorch** [comment]
Are you sure this is 2017.02.12-NB? With current master I can't reproduce. And thought I've fixed this 3 days ago with 86571420e72b2b8bf910ec5d9ccdc30075e1baf6

**Comment by Lineflyer** [comment]
Ups...sorry. I downloaded the mentioned NB but missed to install.
In fact it was 2017.02.08-NB-a6ec64c and after upgrading to 2016.02.12-NB-99a78ab it works without a problem. 
Sorry for causing extra effort.
