### ISSUE TITLE
Sort trackables on log page by code rather than by name

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6319]
Received by a user:
> [...]would it be possible to list the trackable inventory by tracking code? Right now, it is listed in alphabetical order with the code below it. The only issue, especially when you move many trackables like myself, most of the time the user doesn't know the name of the trackable, only knows the code. So putting the codes alphabetically would be amazing and much faster. 

I never thought about that, but I fully agree. If I put trackables into the cache I always look for its tracking number and sorting by that would indeed make this more easy.
Maybe we could also put it into the first row (bigger font) and the name into the second row (smaller font) or make both lines with same font size.

**Comment by FreddieSanchez** [comment]
I'd like to tackle this one. 

Is this in regards to the inventory list on the Cache's inventory section, or your personal inventory when you are about to log a cache?

**Comment by rsudev** [comment]
What I wanted to just throw in is, that I most of the time only have the secret tracking code available for reference when I carry trackables - and that you can't find anywhere...

**Comment by Bananeweizen** [comment]
@rsudev This is about the secret codes in the logging activity. Those are available there.

That being said, I've never tried to lookup a trackable by code in that list, rather by the description. If it has the shape of an airplane, I look for something related to airplane or flying. To me that is much faster than trying to match 6 garbled characters. :)

**Comment by pstorch** [comment]
I think it won't hurt to show the TB-Code in the inventory of a cache and make it sortable.
Just a note: I looked into the sample databases I have. We don't always have the TB-Code. Sometimes only the GUID. Sometimes both. Sometimes only TB-Code without GUID. And we also have Geokrety with GK... code. 
And I also found (seldom) the secret code in the tbcode column.

**Comment by Lineflyer** [comment]
In my original post I was indeed refering to the logging activity. There we show the secret code but don't sort by that. 
As I am also a fan of trackables I can perfectly understand the user:
If I have a bunch of TB in my hand and decide to drop one of them standing in front of the cache, I want to select it as Dropped in c:geo. Easiest way is to look at the tag, read the secret code and search for that in the logging activity. Having it sorting in that way, it would be easier (currently I have 18 TB in my inventory).

**Comment by rsudev** [comment]
And I was just not aware that the secret tracking code indeed is part of the log page, so this feature in fact is easy to implement (and in this form makes sense)

**Comment by FreddieSanchez** [comment]
I currently do not have any trackables in my inventory. Is there an established method of mocking them up?

**Comment by pstorch** [comment]
Maybe I can send you some Trackables from me for testing.

**Comment by FreddieSanchez** [comment]
I think my friends have a couple I can borrow. Just wanted to see if there was a way of doing this programatically without a real trackable.

**Comment by FreddieSanchez** [comment]
I wrote something that sorts the trackables in the inventory by a user selection.

Any comments are welcome.

**Comment by Lineflyer** [comment]
Working as expected in 2017.02.23-NB1. Thank you @FreddieSanchez
