### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by viperbruno** [cgeo/cgeo#6324]
##### Detailed steps causing the problem:
Just open c:geo and try login with your credentials (in geocaching.com)

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by mucek4** [comment]
You will have to provide more information about this. Login works here so let's start:
- try re-typing user&pass
- try logging in directly to GC.com
- try using Wi-Fi or mobile
- c:geo updated?, ...

**Comment by UniQP** [comment]
Please also consider http://www.cgeo.org/faq.html#login-failed.

**Comment by pstorch** [comment]
I read about some general login Problems on geocaching.com this morning.

**Comment by Lineflyer** [comment]
Indeed also on support mail we had some concerns and some of them followed up and told it was a server issue.

**Comment by Lineflyer** [comment]
Closing as no submitter feedback and no similar issues reported
