### ISSUE TITLE
Feature Request: Allow option for 'low data' mode option when not on wifi

### ISSUE THREAD

**Issue by B2Pi** [cgeo/cgeo#6325]
It would be nice to have an option that would inhibit loading, at the least, log images, when not on wifi. Alternatively, a toggle that could be set manually would do. 

Cheers

**Comment by SammysHP** [comment]
@Lineflyer I'm sure that we talked about this previously, but I cannot find the issue. Maybe you can find it with your magic.

**Comment by Lineflyer** [comment]
You are right, but I could not find it right now as well.
However AFAIR the outcome was, that implementing such kind of feature would be a lot of effort for a small group of users. 
And we have a good alternative: Store caches prior of going into the field including all log images (just activate the option in Settings - Offline Data).
Anyway when opening a cache in the field we do not load any log image unless the user clicks on them or opens the gallery tab. Just don't do this, and no data will be transfered for the images.

Please feel free to correct me if I am wrong. I dont always catch all recent changes we made.

**Comment by vsandre** [comment]
If you reload a cache, do you also reload the images already saved on the device? Most time when I reload a cache, I do it to show up the latest log comments. (since my saving at home)

**Comment by SammysHP** [comment]
For partial update see #535, #1404, #1879 (and maybe more). Images should be updated only if they were changed (if ETag works).

**Comment by Lineflyer** [comment]
Closing due to lack of submitters feedback.
@B2Pi Feel free to reopen ehen answering the questions/suggestions.
