### ISSUE TITLE
c:geo - contacts plugin's User Data policy 

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#6326]
Hello Google Play Developer,

Our records show that your app, c:geo - contacts plugin, with package name cgeo.contacts, currently violates our User Data policy regarding Personal and Sensitive Information.

Policy issue: Google Play requires developers to provide a valid privacy policy when the app requests or handles sensitive user or device information. Your app requests sensitive permissions (e.g. camera, microphone, accounts, contacts, or phone) or user data, but does not include a valid privacy policy.

Action required: Include a link to a valid privacy policy on your app's Store Listing page and within your app. You can find more information in our help center.

Alternatively, you may opt-out of this requirement by removing any requests for sensitive permissions or user data.

If you have additional apps in your catalog, please make sure they are compliant with our Prominent Disclosure requirements.

Please resolve this issue by March 15, 2017, or administrative action will be taken to limit the visibility of your app, up to and including removal from the Play Store. Thanks for helping us provide a clear and transparent experience for Google Play users.

Regards,

The Google Play Team

**Comment by SammysHP** [comment]
Does anyone know a cheap lawyer? Having a bad policy might be worse than having none. ;)

Also our app has no GUI, so where should we include it?

**Comment by rsudev** [comment]
I don't think we need a lawyer for our privacy policy, because we simple need to state that the data never leaves the control of the user or the boundary of the device, or am I mistaken?

**Comment by Lineflyer** [comment]
> I don't think we need a lawyer for our privacy policy, because we simple need to state that the data never leaves the control of the user or the boundary of the device, or am I mistaken?

I agree. The provacy policy could just be this sentence or similar.
We could easily include this into the app listing, but as also @SammysHP wrote, the plugin itself has no UI. I do only see the option to (if technically possible) trigger a popup on first usage linking to the privacy policy.

**Comment by Lineflyer** [comment]
https://s2imon.github.io/pp4pp_de/#main

**Comment by Lineflyer** [comment]
How to proceed? March, 15th is not far away.

**Comment by Lineflyer** [comment]
In our FAQ we have:
> The contacts plugin needs the permission to access the contacts on your device to look up other geocachers in case you use the relevant option in c:geo. As long as you don’t use that menu option the plugin will never read any data from your contacts

I suggest to simply put this text into the Google Play description maybe with the addon, that the data will never be transfered or used outside the app.

**Comment by Lineflyer** [comment]
I read a little bit more about the requirements for a privacy policy and talked to a friend of mine who is lawyer.  I think we should be good to go with a very simple privacy policy. 
According to what I read and was told, it should answer three questions very explicitly:
1. What information is collected?
2. How is the information used?
3. With whom is it shared?

I changed the already existing section in our FAQ to reflect these statements:
http://www.cgeo.org/faq.html#plugin-contacts-privacy

I will put this link into the Google Play listing (they require a link to a privacy policy).

Regarding the in-app provision of this information:
I doubt that Google will crosscheck all apps regarding this....lets see.

Furthermore I will also add the same for the calendar plugin and report back here.

Then lets wait and see what happens.

**Comment by Lineflyer** [comment]
Done the same now for the calendar plugin, although it is not required by Google:
http://www.cgeo.org/faq.html#plugin-calendar-privacy

So let us close this.
@mucek4 Please kindly inform us if there is any follow up after March, 15th.

Regarding the in-app info I will open a dedicated issue.
