### ISSUE TITLE
Exporting single field note don't work

### ISSUE THREAD

**Issue by vsandre** [cgeo/cgeo#6329]
##### Detailed steps causing the problem:
(using Geocaching.com)
- open a Cache in the live map
- opening the menu in this **flying** window
- export -> field notes

##### Actual behavior after performing these steps:
- no message or output in the program
- no field note sent to geocaching.com
- even the flying window asking where to upload didn't show up

##### Expected behavior after performing these steps:
- Log is send to GC

##### Version of c:geo used:
2017.02.07

##### Is the problem reproducible for you?
Yes

##### System information:
Nexus 5, Android 6.0.1

##### Other comments and remarks:
-

**Comment by pstorch** [comment]
The export functions have already been removed from the Map popup in the nightlies. 
Please use the History or the Cache Details page.
