### ISSUE TITLE
Geokret inventory stay empty

### ISSUE THREAD

**Issue by boly38** [cgeo/cgeo#6337]
Problem appears since "bugfix version 2017.01.15."  or before (cf. [my comment on FB](https://www.facebook.com/android.geocaching/posts/10154646807370091))

##### Detailed steps causing the problem:
- Given a Geokret which is present in a given GeoCache
- Go to "c:geo" android app onto the same cache, swap to "inventory" tab

##### Actual behavior after performing these steps:
- The page is empty

##### Expected behavior after performing these steps:
- I expect to see my geokret

##### Version of c:geo used:
- 2017.02.07

##### Is the problem reproducible for you?
Yes

- For  example Geokret [Cocci](http://geokrety.org/konkret.php?id=60362) expected to be listed into geocache ["Le Téléski nautique"](https://coord.info/GC391JA) (WARN: this example could change over the time.. of course)

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
Keep the apostrophe at beginning and end to have it properly formatted
```
--- System information ---
Device: GT-I9505 (jfltexx, samsung)
Android version: 5.0.1
Android build: LRX22C.I9505XXUHPK2
Cgeo version: 2017.02.07
Google Play services: enabled - 10.2.98 (238-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR
System date format: dd/MM/yyyy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Connecté) / BASIC
   opencaching.de: Logged in (Connecté)
Geocaching.com date format: dd/MM/yyyy
Installed cgeo plugins:  none
--- End of system information ---

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.
My link to geokrety service is ok. Recently I had a geokret in my hand and I was able to log a "deposit" while logging a cache (geokret appears well under log entry with combo box..)

Thanks for your help. c:geo is amazing app & really usefull, I'm using it really often

**Comment by kumy** [comment]
@boly38 it may be a problem on GeoKretyMap.org cache service.
May you please try to disable GKM proxy in Settings -> Connectors -> GeoKrety?

**Comment by boly38** [comment]
@kumy I just try it (uncheck GKM) and try to reload related cache: I always got an empty inventory :(

**Comment by kumy** [comment]
GKM database semms ok:

http://api.geokretymap.org/gk/60362
http://api.geokretymap.org/gk/60362/details

**Comment by kumy** [comment]
May you send us logcat output when opening the cache?

**Comment by boly38** [comment]
could you provide steps to get "logcat output" ? sorry I dont understand that point

**Comment by kumy** [comment]
@Lineflyer around? do we have some wiki link about getting logcat logs?

**Comment by kumy** [comment]
@boly38 basically:
- activate developers option in android + adb
- connect usb
- activate debug in c:geo options (don't keep that option for daily use)
- connect via adb on your computer (linux: $ sudo adb logcat)

**Comment by SammysHP** [comment]
Getting logs is almost impossible without root. If the phone is rooted, there are many apps in the Play Store. If the phone is not rooted you'll need USB debugging via ADB as @kumy explained.

@kumy 
sudo for adb? Usually there are udev rules that change the permissions of connected devices. ;)

**Comment by boly38** [comment]
ok; I will try adb from windows host...

**Comment by kumy** [comment]
Found our wiki page about logcat: https://github.com/cgeo/cgeo/wiki/Send-log-to-developers

**Comment by boly38** [comment]
arg, got some issue with my USB, my device is 5.0.1 and not rooted, so I will retry using adb from home tonight..keep you posted. Thanks for the links

**Comment by Lineflyer** [comment]
I had a look on GC391JA (no logcast available right now...can do it tonight). I do see one strange thing: The inventory tab is visible but empty. AFAIR it should be not visible at all without inventory. So something is not OK here indeed.

**Comment by kumy** [comment]
I'm (still) on 2016.09.07-c1ccd54 developer build. Cache inventory contains one GK.

**Comment by Lineflyer** [comment]
Here is a quick ADB log screenshot. Seems the request/response work normal:
![screenshot_20170221-120258](https://cloud.githubusercontent.com/assets/949669/23162308/c75a2712-f82d-11e6-942f-257cc409be66.png)

**Comment by Lineflyer** [comment]
Forgot to mention: Just 2017.02.18-NB-cbc33ce (almost current master)
No GK in inventory, just empty inventory tab

**Comment by Lineflyer** [comment]
Seems to be a problem Note:
Despite to the ongoing plans for a feature release a fix for this should potentially be done on `release` in order also to get it fixed for the legacy version.

**Comment by boly38** [comment]
Thanks @kumy for the fix!

FYI/ I thinks it was maybe useless(you were able to reproduce and fix it too quickly! ;))
 but yesterday morning I sent a mail to 'support (at) cgeo.com' with my adb logs and this morning I just receive a mailer deamon message:

>Un problème temporaire est survenu lors de la distribution de votre message à support@cgeo.com. D'autres tentatives vont être effectuées pendant 47 heures. Vous recevrez une notification si l'échec est >permanent.

**Comment by Lineflyer** [comment]
@kumy 
Already tested this fix with the debug build from CI with the cache mentioned in this issue (geokret is shown now) as well as with another cache containing both TB and GK (all displayed).
You should merge to `release`
