### ISSUE TITLE
Static Map loading option not visible

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6343]
##### Detailed steps causing the problem:
I tried to retest #6110 and had another issue:
- Disable "Static maps loading" in Settings - Offline-Data
- Load unsaved cache (e.g. GC77)
- Select Navigate -> Save Static Maps

##### Actual behavior after performing these steps:
The menu option "Save Static Maps" is not shown

##### Expected behavior after performing these steps:
"Save Static Maps" should be shown

##### Version of c:geo used:
2017.02.21-NB1-72baaed

##### Is the problem reproducible for you?
Yes

**Comment by samueltardieu** [comment]
@Lineflyer Do you think that "Save static maps" should be shown even though the cache is not saved locally?

Right now, "download static maps" and "static maps" navigation menu entries are disabled when the cache is not stored into a concrete list.

**Comment by Lineflyer** [comment]
Did not know that.
If this has been disabled intentionally it might be for a good reason I am not aware of.

However I don't think it is needed. So lets close this as "Wont fix"/"Works as designed".
