### ISSUE TITLE
Lint Warnings may cause crash, display problem and memory leak

### ISSUE THREAD

**Issue by Acmine** [cgeo/cgeo#6344]
Hi,

I am using Lint to check for warnings in cgeo and found some warnings that can cause problems:
- [x] **Multi-catch with these reflection exceptions requires API level 19 (current min is 14) because they get compiled to the common but new super type `ReflectiveOperationException`. As a workaround either create individual catch statements, or catch `Exception`**
I found warnings of this category on [line 127 in FilterActivity.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/filter/FilterActivity.java#L127) [line 31 in CustomProgressDiag.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/ui/dialog/CustomProgressDialog.java#L31) and [line 150 in SortActionProvider.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/sorting/SortActionProvider.java#L150)
This warning may lead to crash as suggested in an [issue report of Android](https://code.google.com/p/android/issues/detail?can=1&q=153406&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&id=153406) (See comment 2)

- [x] **Format string `auth_register` is not a valid format string so it should not be passed to `String.format`**
This warning can be found in many places in the project like [line 274 in TokenAuthorizationActivity.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/activity/TokenAuthorizationActivity.java#L274).
I have checked [strings.xml](https://github.com/cgeo/cgeo/blob/master/main/res/values/strings.xml#L688). The string is really not a valid string format and the second parameter passed to the method would be ignored.

- [ ] **This Handler class should be static or leaks might occur (anonymous cgeo.geocaching.utils.DisposableHandler)**
This is a possible memory leak issue found [on line 399 in CacheListActivity.java](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/CacheListActivity.java#L399) and [line 165 in GPXImporter](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/files/GPXImporter.java#L165)
I have found some [related discussions from StackOverflow](http://stackoverflow.com/questions/11407943/this-handler-class-should-be-static-or-leaks-might-occur-incominghandler)

Hope this information can help. :)

**Comment by UniQP** [comment]
I'll take a look at the second item (format strings).

**Comment by pstorch** [comment]
Regarding the third item, there are a lot more:

![image](https://cloud.githubusercontent.com/assets/5598124/23230949/2060122c-f946-11e6-8a36-1e22d6ebb03e.png)

Maybe we should tackle them class by class.

**Comment by rsudev** [comment]
We have already been addressing this step-by-step over time (a search for WeakReference is the easiest guide to those places)

**Comment by pstorch** [comment]
Yes, I remember. Either they are leftovers or new ones.

**Comment by rsudev** [comment]
Pretty sure these are leftovers (we had many more instance Handler classes in the beginning, that was a pattern you could see in the docs and many samples in the earlier days of Android.

**Comment by pstorch** [comment]
I was just looking for if we can enable this check in codacy. Would be nice to prevent future occurrences of these. But I couldn't find anything.

**Comment by Lineflyer** [comment]
Didn't we use to have Lint on the CI? At least I remember having heard of it (sorry for the unqualified question :) ).

**Comment by pstorch** [comment]
Yes, you are right. But these "Handler reference leaks" don't show up there. Does someone know how to enable them there?

**Comment by Bananeweizen** [comment]
I was just going to say that they are enabled, since you see them in AS and in Eclipse. However, looking at the CI server lint results more closely, I'm wondering if we miss to analyze actual Java sources on the server. All the CI findings are related to resource files, not Java files. However, I have no idea if that is really the reason, and if so, why?

Regarding the general lint configuration: That has been fine tuned carefully in the many lint.xml files you find in each project. We suppress some issues which we basically not intend to fix (like having icons in all resolutions). git blame might give some useful indications about when and why issues were disabled.

**Comment by pstorch** [comment]
When run lint locally via `.gradlew lintBasicDebug` you get the same output. No issues in .java files. 
At least for the main module. But there are .java issues in the calendar or contacts module.

**Comment by UniQP** [comment]
Regarding the first item, https://developer.android.com/studio/tools/sdk/eclipse-adt.html (ADT 22.6.0) says
> Added support for Java 7 language features like multi-catch, try-with-resources, and the diamond operator. These features require version 19 or higher of the Build Tools. Try-with-resources requires minSdkVersion 19; the rest of the new language features require minSdkVersion 8 or higher.

(Adopted from https://github.com/cgeo/cgeo/pull/5482#issuecomment-188709875)

**Comment by Bananeweizen** [comment]
For the exceptions I suggest to simply catch the most nearest common parent, e.g. probably ReflectiveOperationException for the 3 mentioned occurences.

**Comment by samueltardieu** [comment]
> For the exceptions I suggest to simply catch the most nearest common parent, e.g. probably ReflectiveOperationException for the 3 mentioned occurences.

I thought that the problem was precisely that `ReflectiveOperationException` was introduced in API 19 and we must run on API 14.

**Comment by samueltardieu** [comment]
> We have already been addressing this step-by-step over time (a search for WeakReference is the easiest guide to those places)

And often the best solution is to remove the handler alltogether and use either RxJava or `runOnUiThread` to perform simple operations on the UI thread when an event completes.

**Comment by Bananeweizen** [comment]
Thanks @samueltardieu. I had quickly read the issue and only took away that multi catch leads to problems. So of course my suggestion is nonsense.

**Comment by UniQP** [comment]
I'll take a look at the third item (leaks due to non-static handlers).
