### ISSUE TITLE
Feature Request: Home Button

### ISSUE THREAD

**Issue by LosTresViajeros** [cgeo/cgeo#6346]
Problem: Hitting "back" only takes you one step back. A lot of times you want to go back right to the overview / start page .
Solution: A simple Home Button top left would solve the problem immediately.

**Comment by SammysHP** [comment]
The top left button takes you one level "up". Usually no more than two presses are necessary to get to the home screen.

**Comment by rsudev** [comment]
IIRC we once had a 'home'-button, but it was then discouraged by changed Android UI guidelines...

**Comment by SammysHP** [comment]
IIRC the "up" button was previously used as a "back" button.

**Comment by Lineflyer** [comment]
I am still in favor of using the main menu as hamburger menu while down in some other function (covered by another issue AFAIR). Still I dont know if this is still receommended in the UI guidelines.

**Comment by Lineflyer** [comment]
With hamburger menu I was refering to this: https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-content

As discussed in #4320 however I am not sure if it is depracted in the style guidelines already (however I still like it).

**Comment by Lineflyer** [comment]
I just found #3937, so I suggest to follow up this "home button" idea in that issue instead.
