### ISSUE TITLE
Feature Request: Uploading a photo when logging

### ISSUE THREAD

**Issue by LosTresViajeros** [cgeo/cgeo#6347]
Problem: uploading a picture while logging not possible right now. - Have to edit the log at home and upload there.
Solution: Option to upload at least 1 photo would be great.

**Comment by rsudev** [comment]
Uploading a photo when logging is implemented at least for some context. Please describe in more detail where you are missing this function.

**Comment by Lineflyer** [comment]
As @rsudev has written upload a photo for a cache log on geocaching.com is possible.
While composing the log, press Menu and select "Add picture".

**Comment by Lineflyer** [comment]
Closing due to lack of submitters feedback.
@LosTresViajeros Feel free to reopen when answering to the questions/suggestions.
