### ISSUE TITLE
Add checkstyle to CI

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#6353]
Running gradle's checkstyle target as part of the continuous integration would help to automatically discover some issue. See #6352 and #6350 (review comments) for examples.

**Comment by pstorch** [comment]
Checkstyle is running on CI (there I also found the missing space after comma #6352) but it doesn't report the status on Pull Requests.

**Comment by pstorch** [comment]
Should we try this Jenkins PlugIn?
https://wiki.jenkins-ci.org/display/JENKINS/Violation+Comments+to+GitHub+Plugin

**Comment by pstorch** [comment]
We can also set the `Status thresholds` in the Project checkstyle configuration on Jenkins to mark a build unstable or failed if more than `$number` violations are reported.

**Comment by pstorch** [comment]
I make a test with checkstyle threshold on the pull request builds.

**Comment by pstorch** [comment]
Ok, the build fails on Checkstyle issues. The lines are not commented on the GitHub pull request (I guess for this we would need the above mentioned PlugIn), but it is a start and we don't miss the Checkstyle issues.

What do you think?
https://github.com/cgeo/cgeo/pull/6354

**Comment by kumy** [comment]
I've just saw it was about "checkstyle", not "checklint".

"Checkstyle" is integrated into Codacy, we only have 4 actives pattern for it (121 disabled).

Is checkstyle at jenkins level necessary? (I'm not opposed to also enabling it at jenkins)

Here are some tests which seems equivalent:
* Checks for braces around code blocks
* Check that method/constructor/catch/foreach parameters are final

Didn't found a check for "',' is not followed by whitespace."

plus this one which remind me a recent PR:
* Checks that there is a newline at the end of each file

There is also #5624.

**Comment by pstorch** [comment]
That would be even better, I guess. 
With codacy we get comments in pull request changes directly.

Maybe this pattern checks for the whitespace after a `,`: `Checks that a token is followed by whitespace `

**Comment by UniQP** [comment]
Is it possible to provide a checkstyle.xml for codacy (or automatically synchronize the configuration with the checkstyle.xml in the c:geo repository)? Otherwise, we would need to adapt the codacy configuration by hand every time we change something in the checkstyle.xml.

**Comment by kumy** [comment]
Codacy supports wide range of configuration files https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns see at bottom

**Comment by pstorch** [comment]
Looks like codacy can read `checkstyle.xml`. Does it need to be in the root directory of the repository?

**Comment by kumy** [comment]
I suppose it will find it in any directory https://github.com/codacy/codacy-checkstyle/blob/master/src/main/scala/codacy/checkstyle/Checkstyle.scala#L53

IIRC we already provide `checkstyle.xml` somewhere in our code... I would say let's try it!

**Comment by pstorch** [comment]
It's here `main/project/checkstyle/checkstyle.xml`
@kumy ok, can you activate it in codacy?

**Comment by kumy** [comment]
done.

**Comment by pstorch** [comment]
Even if the checkstyle.xml is in the root, it seams that codacy doesn't pick it up.

**Comment by pstorch** [comment]
After move of the checkstyle.xml into the project root, Codacy and gradle build work with it.
Have disabled the checkstyle warning report from Jenkins, because that is duplicate now.

From my perspective this issue is solved.

**Comment by UniQP** [comment]
Yes, thanks @pstorch  and @kumy.
