### ISSUE TITLE
Duplicate waypoint from within a waypoint should open the duplicated one

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6355]
##### Detailed steps causing the problem:
- Open the details of a server defined waypoint
- Click on the coordinates
- Select "Duplicate waypoint"

##### Actual behavior after performing these steps:
A toast is shown that the waypoint has been duplicated but the screen still shows the server waypoint
While this is logical for itself, the user expectation might be different.

##### Expected behavior after performing these steps:
As the user clicked on the coords he most likely wants to enter new coords (we recently blocked this for server defined WPs for a good reason), so we should directly take him to the copied waypoint as he selected to duplicate it.
Right now he has to leave the WP detail view, scroll and search for the duplicated WP, enter the WP details and then finally edit the coords.

##### Version of c:geo used:
2017.02.23-NB1

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
I would like to get your opinion on how this should work.

**Comment by pstorch** [comment]
Would be more user friendly to open the duplicated waypoint right away. :+1:
