### ISSUE TITLE
FR: Second r/o GC.com account

### ISSUE THREAD

**Issue by Natureshadow** [cgeo/cgeo#6363]
I would like to have a second GC.com account in c:geo that is used for loading cache data. For example, I have both a separate account and a team account with my father, with the latter having premium features for us both. I would like to use one account only for loading cache listing (PMO caches) and the other for status, logging and everything else.

GS once stated that they are ok with families sharing premium features, which is why they don't check access on the log page, for example.

**Comment by Lineflyer** [comment]
This is a very special use case. Even technically it would be a huge effort to implement such a functionality as we would have to logout and login continously with different accounts while you use c:geo.
I don't think it will ever be realised by someone and it would also not be wise to browser the website in such a way which could be seen as working around BM limitations.

Regarding PMO caches please kindly consider thes workaround of e.g. exporting the cache from PMO-device, import to other device.
Furthermore we do already have a feature request to enable logging option for PMO-caches for basic members which is a valid request in any case (#2288)
