### ISSUE TITLE
Empty logbook

### ISSUE THREAD

**Issue by majkaz** [cgeo/cgeo#6366]
Just a note, because I have found the closed issue with the solution:

Downloaded beta from Google Play (version 2017.02.07), updated, and every cache - downloaded or saved and updated had empty logbook, no error message. (Shown number of found/not found etc. logs and "logbook empty" in the logbook tab.
Didn't have geocaching open anywhere, no other geocaching app running on any device. 
Solved only by reboot, closing the app didn't help. 

System language Czech, date format DD. MM. YYYY, time format HH:MM (24h). Android 5.0.2, device model F52_05

**Comment by SammysHP** [comment]
Please always show us the full system information from "about c:geo". That's why we have it and request it in the issue template.

**Comment by pstorch** [comment]
So it is resolved now by rebooting? 
Can you try to change the date format on geocaching.com next time to see if this helps?

**Comment by majkaz** [comment]
It is resolved. Happened on phone only, tablet was fine from beginning.

Full info (sorry, didn't notice the tab before):

--- System information ---
Device: F52_05 (F52_05, BenQ)
Android version: 5.0.2
Android build: LRX22G release-keys
Cgeo version: 2017.02.07
Google Play services: enabled - 10.2.98 (248-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: cs_CZ
System date format: dd. MM. yyyy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Přihlášení bylo úspěšné) / BASIC
Geocaching.com date format: d. M. yyyy
Installed cgeo plugins:  none
--- End of system information ---

**Comment by alan666notb** [comment]
I got this again this morning.
From about 9:30am - 1010am every time I refreshed a cache I got 'empty logbook'
It's resolved itself now, website troubles?

**Comment by pstorch** [comment]
Website trouble or network problems could be the cause. The log would be of help.

**Comment by Lineflyer** [comment]
Follow up in #6398
