### ISSUE TITLE
Replace calendar plugin by intent method

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6367]
As briefly mentioned in #6362 the calendar plugin might be obsolete with the possibility to send intents to a calendar to add entries which is possible starting API level 14.

**Comment by Lineflyer** [comment]
If someone is working on this I suggest to wait until the next feature release is out to cleanly finalize the minsdk change.
Anyway the calendar plugin should then stay out on Google Play for maxsdk=13.

**Comment by pstorch** [comment]
We already use the Intent method for devices with API level 14+, so it's about moving the code from the PlugIn into the main App. And yes, we need to keep the PlugIn for the legacy version.

**Comment by samueltardieu** [comment]
See PR #6369. The code for the calendar plugin is still present in the `release` and `cgeo-legacy` branches.

**Comment by Lineflyer** [comment]
Then we should in a next step release a new plugin version with corresponding maxsdk limitation in parallel to releasing the minsdk=14 version of c:geo.
