### ISSUE TITLE
Mention-bot on pull requests

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6373]
I've enabled [Mention-Bot](https://github.com/facebook/mention-bot) for our main repository. For each new pull request, it will mention the 3 committers, that had the most changes previously on the affected lines of the pull request. Maybe this improves PR reviews a bit.

Here is a live example from yesterday: https://github.com/cgeo/cgeo/pull/6372

This issue is mostly for collecting feedback. If you have any complaints, or feel this should be disabled again, please feel free to comment. Otherwise I will close the issue in some days.

And of course, this is NOT meant to stop everyone else from reviewing the PR. :)

**Comment by Lineflyer** [comment]
Nice...although I suspect that most times it will mention the same 2-3 persons right now :)

**Comment by pstorch** [comment]
Interesting feature.

**Comment by rsudev** [comment]
I saw one instance of it and I like it. IMO it adds value.
