### ISSUE TITLE
Send2cgeo certificate problem

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6374]
from chat 2017-03-01, 7:45 German Time:

```
<spinnekopje> issue with send2cgeo trying to register: The webpage at https://send2.cgeo.org/api/browser.html might be temporarily down or it may have moved permanently to a new web address.
<spinnekopje> I went to http://www.cgeo.org/send2cgeo.html to register the browser and device and when I clicked register I got that
```

**Comment by mucek4** [comment]
I tried and it works now. Could be the internet connection problem or anything. Can he try again?

**Comment by Lineflyer** [comment]
Tested and working for me right now.

**Comment by spinnekopje** [comment]
12:15 <..... Lineflyer> spinnekopje  For me send2cgeo is now working normal. Can you try again?
12:20 <... spinnekopje> Lineflyer: I get this now: http://pasteboard.co/E9gJ1NbOr.png
12:21 <... spinnekopje> I tried opera on the same chromebook and that works
12:22 <... spinnekopje> probably something to do with security things in chrome I guess
12:23 <....... OneEyed> Works for me on Firefox and on Chromium (self-compiled Chrome) here.
12:24 <....... OneEyed> Launch an network requests inspector on your Chrome browser, and see what happens
12:24 <....... OneEyed> You'll see every requests as well as the responses
12:27 <... spinnekopje> console gives me: send2.cgeo.org/api/browser.html:1 GET https://send2.cgeo.org/api/browser.html net::ERR_INSECURE_RESPONSE
12:30 <....... OneEyed> Chrome doesn't like https XHR calls from a http page? The reverse usually happens, http calls from a https page are not allowed
12:30 <... spinnekopje> When I first load the page I get what I expect (the logo and this browser / your devices), but when I click Register browser it fails
12:30 <....... OneEyed> Can you access https://send2.cgeo.org/api/browser.html directly?
12:33 <... spinnekopje> OneEyed: Aanvallers proberen mogelijk je gegevens van send2.cgeo.org te stelen (bijvoorbeeld wachtwoorden, berichten of creditcarddetails). NET::ERR_CERT_AUTHORITY_INVALID
12:34 <....... OneEyed> Do you have a proxy which could modify the data or the certificate?
12:34 <....... OneEyed> (or an antivirus for example if you're using Windows)
12:34 <... spinnekopje> I've continued anyway and that works
12:34 <... spinnekopje> no proxy
12:35 <... spinnekopje> I'm on a chromebook

**Comment by mucek4** [comment]
So looks like the browser does not have a root certificate.

**Comment by SammysHP** [comment]
@mucek4 
Your certificate is signed by StartCom. Most browsers do not trust StartCom anymore if the certificate was created after October–December 2016. You should switch to something else like Let's Encrypt.

**Comment by mucek4** [comment]
Certificate was issued in end of April. I'll try to replace it

**Comment by kumy** [comment]
be careful, startcom certificates are/will not valid in major browsers. letsencrypt may be be a good alternative, but need to be renewed often. (lego is a nice LE client)

On March 1, 2017 9:24:05 PM GMT+01:00, mucek4 <notifications@github.com> wrote:
>Certificate was issued in end of April. I'll try to replace it
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6374#issuecomment-283458768

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
oups didn t saw SammysHP comment ;)

On March 1, 2017 9:24:05 PM GMT+01:00, mucek4 <notifications@github.com> wrote:
>Certificate was issued in end of April. I'll try to replace it
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6374#issuecomment-283458768

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mucek4** [comment]
So far we had no problems with startcom except this one.

**Comment by kumy** [comment]
mine where "revoked" some weeks ago. site doesn t work anymore in FF, but still on chromium.

On March 1, 2017 9:27:38 PM GMT+01:00, mucek4 <notifications@github.com> wrote:
>So far we had no problems with startcom except this one.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6374#issuecomment-283459700

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lineflyer** [comment]
There is another user having trouble. I can reproduce by using the newest Chrome version 57.0.2987.98 (64-bit).
When trying to open https://send2.cgeo.org/api/browser.html I get a certificate error NET::ERR_CERT_AUTHORITY_INVALID

**Comment by Lineflyer** [comment]
@mucek4 Some more users complaining about Chrom+send2cgeo not work. Can we replace the certificate?

**Comment by mucek4** [comment]
I can look into it next week.

**Comment by Lineflyer** [comment]
@mucek4 Friendly reminder. We keep having users reporting it on Chrome.

**Comment by Chilebeer** [comment]
I've been getting the error "The webpage at https://send2.cgeo.org/api/browser.html might be temporarily down or it may have moved permanently to a new web address." for weeks when trying to register the latest version of Chrome browser.

**Comment by Lineflyer** [comment]
@Chilebeer Yes, we know (see initial posting). This is due to Chrome declining the root certificate of our server certificate for whatever reason.

**Comment by mucek4** [comment]
Ok. Send2 and download have new certificate. Let's test.

**Comment by Lineflyer** [comment]
@mucek4 
First test with Chrome version 57.0.2987.98 (64-bit):
When accessing https://send2.cgeo.org/api/browser.html no more error is shown. Seems to work fine.

**Comment by Lineflyer** [comment]
When trying to access https://www.cgeo.org/ with Chrome (version as mentioned above) I get an error:
`NET::ERR_CERT_COMMON_NAME_INVALID`

Not sure, if it worked before as I only tested the pages involving send2cgeo.

**Comment by mucek4** [comment]
www cannot work as it's hosted on github. 
https://github.com/isaacs/github/issues/156

**Comment by mucek4** [comment]
I accidentally deleted comment. That is expected as our pages are hosted on github:
The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

**Comment by Lineflyer** [comment]
I am no expert for SSL, so I basically out of this discussion.
But from users perspective calling https://www.cgeo.org should not lead to an error message but maybe redirected to http://www.cgeo.org in that case? 
But I guess this is not feasible, isn't it?

**Comment by kumy** [comment]
Even with a redirect, users will still have to validate the ssl exception :(

**Comment by Lineflyer** [comment]
Assigning myself for fieldtest of send2cgeo end-to-end functionality under Chrome/Tampermonkey.

**Comment by Chilebeer** [comment]
Working for me now using Chrome 57.0.2987.133  :)

**Comment by SammysHP** [comment]
I think there's no other solution than using a CDN like Cloudflare which work as a proxy.

**Comment by Lineflyer** [comment]
Confirmed working for me!
@Mucek4 How long is the certificate valid? Maybe we should make a reminder somewhere?!

**Comment by kumy** [comment]
@Lineflyer Let's Encrypt certificates are valid for 3 month, it is recommended to renew them ~1 month before expiration. @mucek4 For the reminder, I already monitor this host on my Xymon. I may easily send you notifications when status goes "yellow" (~30 days before expiration) or "red" (~7 days before expiration).

**Comment by SammysHP** [comment]
Certbot should handle this. Usually it is started with "renew" at least once a day.

**Comment by mucek4** [comment]
@kumy @SammysHP I didn't put it to autorenew yet as I need to see how it's done. I have set an alarm to do it, but if you can warn me it would be great.

**Comment by kumy** [comment]
@mucek4 Notification configured to your personal email.
