### ISSUE TITLE
Geocashing.su

### ISSUE THREAD

**Issue by mesteelrat** [cgeo/cgeo#6375]
++++ Good Very good

**Comment by UniQP** [comment]
No, that's a very very bad issue description.

**Comment by mesteelrat** [comment]
No authorization geocashing.su. it's bad

**Comment by UniQP** [comment]
Please take some time to create a detailed issue that precisely describes your wish or problem.

**Comment by SammysHP** [comment]
This is just spam for a site called "geoca…s…hing.su".
