### ISSUE TITLE
Cannot add waypoints by bearing/distance in RU localization

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#6376]
##### Detailed steps causing the problem:
- Set up Russian system language
- Run c:geo
- Open any cache waypoints tab
- Try to add waypoint by bearing/distance

##### Actual behavior after performing these steps:

- Make sure error "cgeo cannot parse distance" appears

##### Expected behavior after performing these steps:

- Waypoint should be added

##### Version of c:geo used:
2017.03.01-NB-3761122

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: D5803 (D5803, Sony)
Android version: 6.0.1
Android build: 23.5.A.1.291
Cgeo version: 2017.03.01-NB-3761122
Google Play services: enabled - 10.2.98 (436-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: ru_RU
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Вход ОК) / BASIC
   Geocaching.su
Geocaching.com date format: d. M. yyyy
Installed cgeo plugins:  none
--- End of system information ---

```

##### Other comments and remarks:
In English everything is fine, looks like some localization issue (maybe in localized units names m->м, km->км etc)

**Comment by Lineflyer** [comment]
Are you trying to add a new waypoint or modify an existing one?

**Comment by GodfatherThe** [comment]
Both cases are leading to the error

**Comment by Bananeweizen** [comment]
The parser only knows English metric and imperial units: https://github.com/cgeo/cgeo/blob/891775d79c820488226731d709ba643039210418/main/src/cgeo/geocaching/location/DistanceParser.java#L12

**Comment by GodfatherThe** [comment]
In this case you should mark units as non-translatable because I just translated them in crowdin

**Comment by GodfatherThe** [comment]
And just a note - there is normal dialog window asking for number and unit separately. Why do you need parser at all in this case? Isn't it easier to just know the bullet of units which user has selected and also the number from corresponding field

**Comment by Bananeweizen** [comment]
Good point. We should therefore modify https://github.com/cgeo/cgeo/blob/c08a4261659b0b72cd2f9ac70b2f51c65b1848c2/main/src/cgeo/geocaching/EditWaypointActivity.java#L481 and following to not use the text of the control, but the known unit behind it.
