### ISSUE TITLE
Nightly builds fail

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6386]
CI for nightlies seems broken.
Might be related to recent changes on CI as refered in other issues.

**Comment by kumy** [comment]
It seems that `aapt` tool is installed as 64bit (since `24.0.2`) whereas our ci host is 32bit.

```
root@ci:~# for i in /opt/android-sdk-linux/build-tools/*/aapt; do file $i; done
/opt/android-sdk-linux/build-tools/20.0.0/aapt: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.8, not stripped
/opt/android-sdk-linux/build-tools/21.1.2/aapt: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.15, not stripped
/opt/android-sdk-linux/build-tools/22.0.1/aapt: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.15, not stripped
/opt/android-sdk-linux/build-tools/23.0.1/aapt: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x4a693dbbf933958aa3d1a48b02fbe3b5c53bbeb8, not stripped
/opt/android-sdk-linux/build-tools/23.0.2/aapt: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0xd5de8afc5184854113f2599d4f18813efdbdd4e3, not stripped
/opt/android-sdk-linux/build-tools/23.0.3/aapt: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x4a3bb6cf2d0c1dd12903f159066711f02ef79be9, not stripped
/opt/android-sdk-linux/build-tools/24.0.2/aapt: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x586cc780fc183426e18630f1f9b4d9cf94dec49f, not stripped
/opt/android-sdk-linux/build-tools/25.0.2/aapt: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x7a75cac6784111b58ba0a3d37de461cd0b47b8ea, not stripped
```

The commands I've launched today for installing `tools` and `build-tools-25.0.2` were:
```
  506  android update sdk --all --no-ui --filter tools
  510  android update sdk --all --no-ui --filter build-tools-25.0.2
```

I don't know if there is a special procedure to install things as 32bit
@mucek4 any hint?

**Comment by kumy** [comment]
Argh, http://stackoverflow.com/a/39541779/944936 :'(
> Google dropped support for 32 bit processors starting with this version [...]

@Bananeweizen should we rollback your last insertion?
@mucek4 that may be time to have a second 64bit vm ;)

**Comment by Bananeweizen** [comment]
While we may revert the build tools upgrade for the time being, that is no solution. Only a workaround. Seems it's time to either get a new Jenkins master or to make it possible to share the build secrets with the other existing slaves in a way they remain secret. (Not sure if that is even possible)

**Comment by kumy** [comment]
I agreen, it s just a workaround. Sharing the key is ane problem, uploading via ftp is another one. Threre may be other constraints I m not aware of. I didn t search were, but I remember @mucek4 proposed to build a 64bit vm next to the first.

**Comment by SammysHP** [comment]
We talked about this already half a year ago...

**Comment by Lineflyer** [comment]
And we talked about renting a server or a CI service....

**Comment by kumy** [comment]
we may "upgrade" current server to 64 https://askubuntu.com/questions/81824/how-can-i-switch-a-32-bit-installation-to-a-64-bit-one/152798#152798.

I would also like to give a chance to @mucek4 proposition to have another fresh vm instead of renting a new server.

On March 5, 2017 11:29:43 AM GMT+01:00, Lars <notifications@github.com> wrote:
>And we talked about renting a server or a CI service....
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6386#issuecomment-284218904

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lineflyer** [comment]
Did someone deploy the mentioned workaround/rollback so that we can build nightlies, releases on CI?
Until we know the final solution it would be good to have a working CI.

**Comment by mucek4** [comment]
@kumy  I can try that. It's a virtual machine so I can snapshot it first.

**Comment by mucek4** [comment]
I installed new master. And it is 64 bit now. Please report any problems.
