### ISSUE TITLE
Automated acceptance testing for mobile apps

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6387]
I have just come across this site http://calaba.sh/.

The description say:
> Calabash enables you to write and execute automated acceptance tests of mobile apps. It’s cross-platform, supporting Android and iOS native apps. It’s also open source and free, developed and maintained by Xamarin.

There seems to also be a cloud testing (which I find quite expensive). But the open source part, may be sufficient for our needs.

I imagine @Lineflyer would love it / write tests :)

**Comment by Lineflyer** [comment]
See also #6371 
Will take a look into calabash next days

**Comment by Lineflyer** [comment]
Outdated.
