### ISSUE TITLE
Set maxsdk on calendar plugin to keep it working with legacy c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6390]
Following up of #6367 

In order to keep the plugin available for the upcoming c:geo loegacy version (SDK <14) we would need to release a new calendar plugin version with
 `android:minSdkVersion="9"` and `android:maxSdkVersion="13"`
if I understand their mechanism correctly.

This has to be done on `release` branch as the plugin is only existing there anymore (and CI builds the release from `release` as far as I know).

Afterwards we have to check where to "archive" the plugin code (as it will get deleted next time we merge `master` to `release`.

**Comment by Lineflyer** [comment]
BTW:
I have just taken a look on the CI and there is no dedicated job for the plugins.
I do not remember how we used to build a release version for them... maybe we just used the nightly job and built it from `master` last time?!

Anyway, either we need to enable the CI for building the plugin from `release` or someone simply needs to build as soon as the needed changes are in and provide the APK to me.

**Comment by Lineflyer** [comment]
Found the (depracted) CI job for it: http://ci.cgeo.org/view/cgeo%20deprecated/job/cgeo%20add-on/

**Comment by SammysHP** [comment]
> Afterwards we have to check where to "archive" the plugin code (as it will get deleted next time we merge `master` to `release`. 

We use git, nothing will be deleted. For every release we add a tag that references the corresponding code.

**Comment by Lineflyer** [comment]
> We use git, nothing will be deleted. For every release we add a tag that references the corresponding code.

I know, I just thought it might be wise to also conserve it on some branch...but I have just recognized, thaat the current code of the plugin is already conserved on `cgeo-legacy`

**Comment by Lineflyer** [comment]
`AndroidManifest.xml` has been modified on `release` accordingly.
