### ISSUE TITLE
Additional waypoints don't show up when live disabled

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6395]
##### Detailed steps causing the problem:
- have a list with caches
- make sure live is disabled 
- open new map for this list
- zoom in to a cache with additional waypoints (e.g. parking coordinates) 

##### Actual behavior after performing these steps:

- no additional waypoints show up

##### Expected behavior after performing these steps:

- additional waypoints show up

##### Version of c:geo used:
 Nightly developer version 

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: ONEPLUS A3003 (OnePlus3, OnePlus)
Android version: 7.0
Android build: ONEPLUS A3003_16_170208
Cgeo version: 2017.03.09-562efa7 developer build
Google Play services: enabled - 10.2.98 (448-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed cgeo plugins: contacts
--- End of system information ---

```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
I cannot reproduce this one as described, however I could be this similar issue: #5900 
@pstorch Can you crosscheck the behaviour again (with respect to #5900)

**Comment by pstorch** [comment]
In my case the geocache itself is in the current viewport but e.g. parking coords don't show up automatically. 
See: https://youtu.be/KJmePGsKC_Y

**Comment by Lineflyer** [comment]
Interesting. This seems to depend on the amount of caches on the list (or something similar). Its working for me with a list of 9 caches (non live, mapsforge beta).

BTW: What tool did you use for screenrecording with audio?

**Comment by pstorch** [comment]
My List is from a PQ of 1000 geocaches. 
Tool: AZ screen recorder https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free

**Comment by rsudev** [comment]
I could reproduce this (also with a larger list)

**Comment by rsudev** [comment]
The reason for this behaviour is, that the waypoint visibility threshold is active even for a map from a list. So my feature description is wrong such that the waypoint threshold is not triggered by additional 'live' caches, but still in effect for the initial caches of a map.
The question is, if I should change the implementation to conform with the expectations, or should I update the feature description to make clear how it works?

**Comment by Lineflyer** [comment]
> The question is, if I should change the implementation to conform with the expectations, or should I update the feature description to make clear how it works?

We should change the implementation.
The behaviour is now different compared to v3 maps.

And in fact it means at the moment that, when mapping a list which contains more than 50 (max setting) of caches, waypoints will never be shown. This is a real drawback of this feature.

**Comment by rsudev** [comment]
The tricky bit here is, that currently the list based map is only initialized once with all caches. So visibility is never checked/updated. This can be a performance advantage (no need to check for map moves ever so often) but has the drawback, that e.g. the showing of waypoints doesn't work as expected.
I guess I'll have to put in a timer-based visibility check even here.

**Comment by Lineflyer** [comment]
I noticed today, that when I map a list on the offline map and log caches offline  (found) from there the icon overlay is not refreshed, i.e. the smiley does not appear until I reenter the map.
No idea if this is related or even if I might have already opened a dedicated issue for this.

**Comment by rsudev** [comment]
It is related :)
