### ISSUE TITLE
Old nightly on server

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6397]
##### Detailed steps causing the problem:
- Notfication system gives prompt, that new nightly is available
- Download it from download.cgeo.org
- Install it

##### Actual behavior after performing these steps:
The APK from server is still 2017.03.08-NB 

##### Expected behavior after performing these steps:
Should be the newest nightly, which has been build

##### Other comments and remarks:
Seems build job is OK, notification is OK, but upload to server isn't

**Comment by kumy** [comment]
Relevant log lines in CI job:

```
05:21.182  + sh /srv/ftp.upload cgeo-nightly.apk cgeo-nightly.apk
05:26.222  Password:Name (webserver:jenkins): Login incorrect.
05:26.227  Login failed.
05:26.228  Please login with USER and PASS
05:26.228  ftp: bind: Address already in use
05:26.229  + sh /srv/ftp.upload cgeo-nojit-nightly.apk cgeo-nightly-nojit.apk
05:31.447  Password:Name (webserver:jenkins): Login incorrect.
05:31.451  Login failed.
05:31.453  Please login with USER and PASS
05:31.453  ftp: bind: Address already in use
```

**Comment by kumy** [comment]
I have updated the `ftp.upload` script (backup: `ftp.upload.orig`)

```
05:08.557  + sh /srv/ftp.upload cgeo-nightly.apk cgeo-nightly.apk
05:13.991  Connected to webserver.
05:13.991  220 ProFTPD 1.3.4a Server (Debian) [xxx]
05:14.011  331 Password required for xxx
05:16.261  230 User xxx logged in
05:16.262  Remote system type is UNIX.
05:16.262  Using binary mode to transfer files.
05:16.262  250 CWD command successful
05:16.262  200 Type set to I
05:16.262  local: bin/cgeo-nightly.apk remote: cgeo-nightly.apk
05:16.262  200 PORT command successful
05:16.265  150 Opening BINARY mode data connection for cgeo-nightly.apk
05:17.066  226 Transfer complete
05:17.067  7364045 bytes sent in 0.80 secs (8.7714 MB/s)
05:17.067  221 Goodbye.

05:17.068  + sh /srv/ftp.upload cgeo-nojit-nightly.apk cgeo-nightly-nojit.apk
05:22.282  Connected to webserver.
05:22.282  220 ProFTPD 1.3.4a Server (Debian) [xxx]
05:22.283  331 Password required for xxx
05:24.632  230 User xxx logged in
05:24.632  Remote system type is UNIX.
05:24.632  Using binary mode to transfer files.
05:24.632  250 CWD command successful
05:24.633  200 Type set to I
05:24.633  local: bin/cgeo-nojit-nightly.apk remote: cgeo-nightly-nojit.apk
05:24.633  200 PORT command successful
05:24.637  150 Opening BINARY mode data connection for cgeo-nightly-nojit.apk
05:24.722  226 Transfer complete
05:24.723  7364045 bytes sent in 0.09 secs (82.4381 MB/s)
05:24.723  221 Goodbye.
```

**Comment by kumy** [comment]
Hum, ftp upload was ok, but version still seems to be `2017.03.08-NB-b844198` (seen while updating [fdroid](http://ci.cgeo.org/view/Fdroid/job/Publish%20FDroid%20-%20NIGHTLY/222/console))

**Comment by kumy** [comment]
Checked build and uploaded apk, both are `versionName='2017.03.12-NB-80f0300'`. Whereas downloaded is still `versionName='2017.03.08-NB-b844198'`.

@mucek4 Do I miss something? Does the `public_html` directory has moved elsewhere?

**Comment by kumy** [comment]
ho, just found a dedicated directory called `download`. It should be there now :)

**Comment by Lineflyer** [comment]
Confirmed working. Thanks @kumy

**Comment by mucek4** [comment]
OOps. I accidentaly deleted credentials. Old upload should work and use direct download user&password. I am restoring credentials now + restoring old upload scripts.

**Comment by mucek4** [comment]
Old scripts restored and credentials put where they belong.
