### ISSUE TITLE
Install Xymon on new server

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6399]
I propose to install [xymon-client](https://en.wikipedia.org/wiki/Xymon) on our newly refreshed server so -at least- I can monitor it on my home instance.

Is this ok for everyone?

**Comment by mucek4** [comment]
What would we like to monitor here? You proposed the solution but didn't tell what problem is.

**Comment by kumy** [comment]
Sorry to not have been clear enough. There is no problem with the actual configuration. But I'm used to monitor every server I administer. Xymon is a monitoring tool. It can check many things, like packages needing update, process existence, disk/memory/cpu usage, file presence/absence, and many more.

Here are some (related to geocaching) sites I monitor:
![screenshot from 2017-03-14 10-14-39](https://cloud.githubusercontent.com/assets/176794/23893534/21733a3c-089f-11e7-92e8-277d89adaf76.png)

And here some servers from home:
![screenshot from 2017-03-14 10-16-42](https://cloud.githubusercontent.com/assets/176794/23893603/684902ca-089f-11e7-8755-c833231b7e50.png)


First things I would like to monitor would be disk usage (and inodes), and a `files` probe which would check if our downloads apk are present and fresh enough (nightly apk) (But as they are not on the same server this will be a bit complicated)

https://en.wikipedia.org/wiki/Xymon
http://xymon.sourceforge.net/

**Comment by mucek4** [comment]
for being online I use uptimerobot. If you would like to monitor it, yeah, why not.

**Comment by kumy** [comment]
Done.
