### ISSUE TITLE
Center Map to search coords after search by coords/address (Basic member)

### ISSUE THREAD

**Issue by Jorgixhallo** [cgeo/cgeo#6400]
##### Detailed steps causing the problem:
- Step 1
Search any address where you don't have saved caches.
- Step 2
Click Map Icon
- ...

##### Actual behavior after performing these steps:
Shows last location, not the location you searched

##### Expected behavior after performing these steps:
It would be nice that it could center the map on the location we have chosen. This way we could perform live search without having to save list of caches first.

##### Version of c:geo used:
2017.02.28-RC

##### Is the problem reproducible for you?
Yes

**Comment by Lineflyer** [comment]
Thanks @Jorgixhallo for the suggestion.
Addon from my side:
This feature request is very meaningful for basic members as a workaround for non existing coords in the search result list.
Still just having the map centered on search coords still requires the user to manually enable live.
Instead we should additionally enable live if the list of caches does not have coords and the user maps it.

---
This was a follow up issue from #6394 
Linked to or better idea than #4066

**Comment by moving-bits** [comment]
If you've searched for an address, you get a list "found places". How about implementing a "long press" on one of the results to jump into the live map with the selected address as center?
This is independent of member status and does not interfere with any other part of the user interface.

**Comment by Lineflyer** [comment]
Long press actions are always kind of a hidden feature IMHO.
How about offering a dialog after clicking on one the result with options for cache list or open live map?
Drawback would be, that it needs one click more to get the list result compared to the current situation.

**Comment by moving-bits** [comment]
I understand what you're saying (and agree with "long press" being sort of a hidden feature - took me quite some time to discover this in c:geo), but I'm not too fond of an extra dialog window, as well - seems too obstrusive to me. Maybe we could add a small button (icon) after each search result (icon being right aligned)? (Or can we find a different solution which is easily usable but does not make the current functionality harder to access?)

**Comment by Lineflyer** [comment]
Right aligned button is a good idea. You could use the map icon as present in the top bar of cache lists. UI wise it could be similar to the pocket query list (with the icons aligned on the right for open or import).

**Comment by moving-bits** [comment]
current status: see PR 7228 for this one - generally works, but still has some race condition with caches loading, showing for an instant, and directly vanishing

**Comment by Lomanic** [comment]
Is this feature available on the beta channel? Can't see it with 2019.03.30-RC1.

**Comment by Lineflyer** [comment]
No, currently in the nightlies only. Will be probably contained in the release after the next upcoming release.
