### ISSUE TITLE
Using c:geo itself as an unofficial api

### ISSUE THREAD

**Issue by jonnyrobbie** [cgeo/cgeo#6401]
Is it possible to use parts of cgeo as an unofficial command line interface/api? I tried to search for relevant classes or functions but I couldn't find any. For searching, retrieving, filtering caches in a pc terminal instead of in an android app?

**Comment by SammysHP** [comment]
No, that is not possible and we will not implement it.

c:geo is a plain Android app. There are many alternatives for PC usage like GSAK or CacheWolf.

**Comment by kumy** [comment]
There also for example https://pypi.python.org/pypi/pycaching
