### ISSUE TITLE
Add cache name to waypoints description in selecting pop-up

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#6402]
##### Detailed steps causing the problem:
- Enable New map in settings
- Open part of map where there are several custom waypoints
- Click on the map
- Make sure pop-up "Select item" appears

##### Actual behavior after performing these steps:

There are unknown numbers under waypoints titles
![j_74axtgqc8](https://cloud.githubusercontent.com/assets/918446/23922139/4b85f864-0912-11e7-980f-8c3616cac4ec.jpg)

##### Expected behavior after performing these steps:

I expect geocache's titles there (or at least cropped titles)

##### Version of c:geo used:
2017.03.12-NB-80f0300

##### Is the problem reproducible for you?
Yes

##### System information:
```
-— System information —-
Device: D5803 (D5803, Sony)
Android version: 6.0.1
Android build: 23.5.A.1.291
Cgeo version: 2017.03.12-NB-80f0300
Google Play services: enabled - 10.2.98 (436-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: ru_RU (cgeo forced to English)
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / BASIC
Geocaching.su
Geocaching.com date format: d. M. yyyy
Installed cgeo plugins: none
-— End of system information —-
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
From IRC:
[22:02] <Lineflyer> rsudev: I Agree. Just took a look. It shows for example also "ursprüngliche Koordinaten" Waypoint for me with just that name and a c:geo created waypoint code "176JY29" which does not really help
