### ISSUE TITLE
Replacement of ShowcaseView 

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6403]
Follow up on #5752.

ShowcaseView as an introduction to the App is kind of "outdated". What about https://github.com/PaoloRotolo/AppIntro is an alternative?

**Comment by akkatracker** [comment]
Linking to #4263

**Comment by Lineflyer** [comment]
As a first step we could remove all the existing Showcases IMHO. Those have been intended to alert users about new features which are now in place since over a year.

**Comment by akkatracker** [comment]
App Intro is nice as is Material Intro: https://github.com/HeinrichReimer/material-intro -> both would be a step towards material

**Comment by samueltardieu** [comment]
#6423 is a PR to remove showcaseview.

**Comment by Lineflyer** [comment]
Might be interesting for guiding users regarding filter changes?

Otherwise close.

**Comment by moving-bits** [comment]
We have really extensive manual and FAQ, I would not open another way of explaining things in detail - too much that needs to be maintained, IMHO.
