### ISSUE TITLE
Owned caches detection fails with username with appended empty space

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6408]
##### Detailed steps causing the problem:
Not a critical error, but one of those you will probably never find out:
- Enter Settings - Services - geocaching.com
- Append a blank to your username at the end
- Perform authentication
- List your owned caches

##### Actual behavior after performing these steps:
Login and all functions still working (as we may strip the empty space at the end of the username while logging in, which is good) but owned caches are not marked with star icon overlay as ownername<>username

##### Expected behavior after performing these steps:
Either we should cut off empty spaces at the end of the username while saving it in settings, or the check if a cache is owned should strip it before comparing with owner name.

##### Version of c:geo used:
2017.03.17-NB2

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
IMHO username can contain blanks in the middle, so don't remove all blanks from the string

**Comment by Bananeweizen** [comment]
I must admit I could not really test the fix, since I simply don't own a cache...
