### ISSUE TITLE
Release job on CI produces APK without version code

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6410]
I tried to build a release with CI using http://ci.cgeo.org/job/cgeo%20release/ .
This is the ouput which looks fine: http://ci.cgeo.org/job/cgeo%20release/26/

Still the resulting APK cannot be used for upgrading from existing release 2017.02.07:
```
12:50:33.641 Warning PackageManager 895  Can't install update of cgeo.geocaching update version 0 is older than installed version 20170207
```
Cleanly installing the APK I can see that no version code has been set:
```
13:08:28.805 Info cgeo 11694  [main] Starting cgeo.geocaching 0 a.k.a null
```

Assigning @mucek4 and @kumy. Can one of you take a look at this?

**Comment by kumy** [comment]
I may have mess up build.gradle with my last change https://github.com/cgeo/cgeo/blob/master/main/build.gradle#L85-L89

Is there some gradle expect around there?

(Can look in few hours)

I'll revert my last change

**Comment by kumy** [comment]
6435513954df27be1c59a3989ad116999e6d0fc5 reverted

**Comment by Lineflyer** [comment]
Working now! Thanks @kumy
