### ISSUE TITLE
Post release tasks 2017.03.19/2017.02.30-legacy

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6411]
### Legacy release 2017.02.30-legacy (API 9-13):

- [x] Smoke test
- [x] Upload to Play
- [x] Tag release on Github at 511b1e45bfa9d15dd98f21b015288556dca00fa5 (this has to be done for legacy first before doing it for the standard release)
- [x] Upload APK to Github and publish release 
- [x] Trigger release notification for legacy

### Release 2017.03.19 (API>=14):

- [x] Smoke test
- [x] Upload to Play
- [x] Tag release on Github at afcdc99edd8230b8487ad519a2a512861d7758b1  (this has to be done after the same has been completed for the legacy version to have it displayed as newest release)
- [x] Upload APK to Github and publish release
- [x] Adapt milestones on Github
- [x] Trigger release notification via status.cgeo.org once release is available
- [x] Publish release to Fdroid
- [x] Post on social media

**Comment by Lineflyer** [comment]
Note:
Github seems to derive the order in which releases are shown according to the date/time of the tagged commit. This currently makes cgeo-legacy been shown as "Latest release".
We need to correct that, in order to ensure that our "Download APK" targets non-legacy. Furthermore fdroid-release CI-job is based on the latest release as well.

**Comment by Lineflyer** [comment]
Releases are out. Thanks everyone for your help!

**Comment by SammysHP** [comment]
"Social media" also includes Twitter, which is not done  obviously. ;) Can you please add it to the list next time? I can also give you the password to the Twitter account.

**Comment by Lineflyer** [comment]
You are right.
I will create a Wiki page as a template for that.

**Comment by Lineflyer** [comment]
@SammysHP Created a template in our Wiki: https://github.com/cgeo/cgeo/wiki/Checklist-for-release-process

Feel free to check or add something.
