### ISSUE TITLE
Release new version of calendar plugin 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6413]
Following up on #6367 and #6390:

We should release a new version of the calendar plugin:
For API>=14 we have the intent method implemented, so we should limit the plugin to be available only for API<14.
The needed changes have already been done on `release` (see #6390), only either someone needs to build it manually for publishing or we need to reenable the depracted CI-job for this:
http://ci.cgeo.org/view/cgeo%20deprecated/job/cgeo%20add-on/

**Comment by kumy** [comment]
@Lineflyer may you check download.cgeo.org/cgeo-calendar-release.apk, I have built and signed it manually.

**Comment by kumy** [comment]
Based on release branch

**Comment by Lineflyer** [comment]
@kumy:
Google Play tells me something like (manually translated) if I try to upload this APK:

You uploaded an APK-file, which was not aligned with the zipalign-Tool. Make sure you use the zipalign-Tool on your APK-file and upload it again.

**Comment by kumy** [comment]
@Lineflyer File is now aligned.

**Comment by Lineflyer** [comment]
@kumy 
The APK is not OK. It seems to use incorrect minsdk, maxsdk values.

From the phone log:
```
19:27:44.562 Warning PackageParser 15077  /mnt/sdcard/download/cgeo-calendar-release.apk (at Binary XML file line #7): Requires newer sdk version #14 (current version is #10)
19:27:44.562 Warning PackageInstaller 15077  Parse error when parsing manifest. Discontinuing installation
```

Also Google Play console shows versions 14-13 (which would be min>max).
Ar you able to doublecheck?

**Comment by kumy** [comment]
Build was based on commit bcc511f

**Comment by kumy** [comment]
I suspect the `minSdkVersion` is inherited from project level. which is set to 14 in main `build.gradle`.

I propose to set the `minsdk` directly in `cgeo-calendar/build.gradle` file

**Comment by kumy** [comment]
@Lineflyer I have overwritten [apk](http://download.cgeo.org/cgeo-calendar-release.apk). It contains the proposed fix, is signed, and aligned:


```
$ /opt/android-sdk-linux/build-tools/25.0.2/aapt dump badging  cgeo-calendar-release.apk 
package: name='cgeo.calendar' versionCode='7' versionName='1.7' platformBuildVersionName='6.0-2704002'
sdkVersion:'9'
maxSdkVersion:'13'
targetSdkVersion:'13'
uses-permission: name='android.permission.READ_CALENDAR'
uses-permission: name='android.permission.WRITE_CALENDAR'
[...]

$ /opt/android-sdk-linux/build-tools/25.0.2/zipalign -c -v 4  cgeo-calendar-release.apkVerifying alignment of cgeo-calendar-release.apk (4)...
      50 META-INF/MANIFEST.MF (OK - compressed)
     465 META-INF/MUCEK4.SF (OK - compressed)
     943 META-INF/MUCEK4.RSA (OK - compressed)
    2060 AndroidManifest.xml (OK - compressed)
    3080 classes.dex (OK - compressed)
  307456 res/drawable-hdpi-v4/ic_launcher.png (OK)
  314564 res/drawable-ldpi-v4/ic_launcher.png (OK)
  317432 res/drawable-mdpi-v4/ic_launcher.png (OK)
  321632 res/drawable-xhdpi-v4/ic_launcher.png (OK)
  331776 resources.arsc (OK)
Verification succesful
```

**Comment by Lineflyer** [comment]
We are one step further now:
- Google Plays shows API levels correct
- I am able to install it on my API10 device

But it crashes when actually trying the function.
Sadly I never tried before. 
Will try to install the current released version to check with that.

Log shows:
```
20:28:49.219 Error AndroidRuntime 15934  FATAL EXCEPTION: main
20:28:49.219 Error AndroidRuntime 15934  java.lang.IncompatibleClassChangeError: interface not implemented
20:28:49.219 Error AndroidRuntime 15934  	at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:339)
20:28:49.219 Error AndroidRuntime 15934  	at cgeo.calendar.CalendarActivity.queryCalendars(CalendarActivity.java:122)
20:28:49.219 Error AndroidRuntime 15934  	at cgeo.calendar.CalendarActivity.selectCalendarForAdding(CalendarActivity.java:54)
20:28:49.219 Error AndroidRuntime 15934  	at cgeo.calendar.CalendarActivity.onCreate(CalendarActivity.java:39)
20:28:49.219 Error AndroidRuntime 15934  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1072)
20:28:49.219 Error AndroidRuntime 15934  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1794)
20:28:49.219 Error AndroidRuntime 15934  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1851)
20:28:49.219 Error AndroidRuntime 15934  	at android.app.ActivityThread.access$1500(ActivityThread.java:132)
20:28:49.219 Error AndroidRuntime 15934  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1038)
20:28:49.219 Error AndroidRuntime 15934  	at android.os.Handler.dispatchMessage(Handler.java:99)
20:28:49.219 Error AndroidRuntime 15934  	at android.os.Looper.loop(Looper.java:150)
20:28:49.219 Error AndroidRuntime 15934  	at android.app.ActivityThread.main(ActivityThread.java:4277)
20:28:49.219 Error AndroidRuntime 15934  	at java.lang.reflect.Method.invokeNative(Native Method)
20:28:49.219 Error AndroidRuntime 15934  	at java.lang.reflect.Method.invoke(Method.java:507)
20:28:49.219 Error AndroidRuntime 15934  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
20:28:49.219 Error AndroidRuntime 15934  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
20:28:49.219 Error AndroidRuntime 15934  	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Lineflyer** [comment]
I just realized that the change from plugin to intent method is still only on `master` but not on `release` thus I have to correct my initial statement, that we require to release it now.

We should however release it together with the next feature release.
This means we should think about either to completely prepare everything now (before next merge from `master` to `release`) or have a plan B (as the code is no longer contained on `master`)

**Comment by Lineflyer** [comment]
Just to be complete:
As I got a crash with the new compiled version I tested http://download,cgeo.org/cgeo-calendar-nightly.apk (nightly from 2015) on the very same device. With this APK it is working normal.

**Comment by kumy** [comment]
CalendarActivity.java Line 122 Idea tell : "Cast from Cursor to Closeable requires API level 16 (current min is 9)"

Commit c8a0060a "replace conditional close by IOUtils.closeQuietly".
What about reverting?

**Comment by Lineflyer** [comment]
@kumy 
As the culprit has been reverted now, could you build another calendar.apk?
So we have it "on stock" to release it together with the next feature release of c:geo.

**Comment by kumy** [comment]
@Lineflyer `cgeo-calendar-release.apk` built, signed, aligned and uploaded.

`package: name='cgeo.calendar' versionCode='8' versionName='1.8' platformBuildVersionName='6.0-2704002'`

**Comment by samueltardieu** [comment]
@Lineflyer I don't understand what you're doing there with the SDK levels. The integration of the calendar plugin in the main application is only done on `master`. The plugin is still needed for the official version of cgeo from `release`, it does not include the "add to calendar" capability yet.

**Comment by Lineflyer** [comment]
@samueltardieu I know meanwhile (see my [comment](https://github.com/cgeo/cgeo/issues/6413#issuecomment-287883445) above).

Still we can prepare the APK with discussed sdk levels now, because as soon as we do the next featureful release (coming from `master`) the preconditions are given.

**Comment by samueltardieu** [comment]
Oh, ok, I missed that comment. Perfect then.

**Comment by Lineflyer** [comment]
The calendar plugin version 1.8 for API level 9-13 has been pusblished.
This means that the calendar plugin for API 14+ has been depublished as it is no longer needed.
