### ISSUE TITLE
Next bugfix release (normal + legacy)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6416]
Due to fix of #6415 and (partly fixed) #6344 I will soon create another RC/Beta version in preparation of a next quick bugfix release.

Checklist for upcoming bugfix release:

- [x] Check/Insert correct version name as headline in ```changelog-release.xml```
- [x] Build release on CI server (normal + legacy)
- [x] Perform smoke test with resulting ```cgeo-release.apk``` (and legacy) before continuing
- [x] Upload and publish ```cgeo-release.apk```  (and legacy) to Google Play
- [x] Tag the releases on Github
- [x] Publish the release on Github including upload of ```cgeo-release.apk```  (and legacy) to Github
- [x] Publish release on F-Droid 
- [x] Rename/Create milestones on Github
- [x] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [x] Post release info to Facebook 
- [x] Post release info to G+ 
- [x] Post release info to Twitter

**Comment by samueltardieu** [comment]
You should include the fix for #6419 too.

**Comment by Lineflyer** [comment]
OK, I will build a new RC1. Have not yet pushed the RC. Wanted to test it tonight before pushing it.

**Comment by Lineflyer** [comment]
2017.03.21-RC1 has been published to beta testers.

**Comment by Lineflyer** [comment]
Added legacy release to the title, as we also need a bugfix release there (see #6445).

**Comment by Lineflyer** [comment]
2017.03.26-RC has been published to beta testers due to the new bugfixes on `release`

**Comment by Lineflyer** [comment]
I recently posted some crash reports from Google Play as issues here. If anyone knows what can be fixed easily feel free to do so: [Issues Google play related](https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22Google+Play+related%22+sort%3Aupdated-desc)

**Comment by Lineflyer** [comment]
Current RC performs normal, no news crash reports on Google Play, not support mails regarding the RC version. I propose to release a new bugfix release tomorrow eveing.

**Comment by Lineflyer** [comment]
Checklist for upcoming bugfix release:

- [x] Check/Insert correct version name as headline in ```changelog-release.xml```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Rename/Create milestones on Github
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to G+ 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
Releases 20170329 (2017.03.29) and 20170231 (2017.03.29-legacy) have been published.
Can someone tag the release on Github as follows?

market_20170329 at https://github.com/cgeo/cgeo/commit/bfe6087a6f8e7339ad996c72c769815ec0d5ebc4

market_20170231-legacy at https://github.com/cgeo/cgeo/commit/a8434f10833d794f5fdf7bad7a305cee1d21f2c2

**Comment by kumy** [comment]
I'll tag...

**Comment by kumy** [comment]
Tags done.

**Comment by Lineflyer** [comment]
This can be closed then. Thanks @all
