### ISSUE TITLE
Improve setting design

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6425]
The setting section in Settings - System for "GeocacheData" is not likely to be identified as "clickable".
I suggest to add a field below the description text showing the currently used dir and clicking on that offers the dir selection dialog.

**Comment by pstorch** [comment]
There is only a description text or the current value possible, not both in one settings element.
For example the `GPX Import Directory` settings. There we show only the value if set, but no description.
We could add a separate Info Element like in `Map/Info on Map Themes` with a Popup and Link to the FAQ. 
What do you think?

**Comment by Lineflyer** [comment]
I thought of something similar to e.g. Settings - Navigation - "Standardnavigation"

Caption: Geocache Data
   <Text with explanation>
      Clickable box: First line: "Select GeocacheData directory" Second line (smaller): Current path

**Comment by pstorch** [comment]
Ah yes, this is a good example.
