### ISSUE TITLE
Show percentage of completion while moving GeocacheData

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6426]
As the operation of moving GeocacheData from internal to external might take long, we should show a clear progress.

Test still outstanding how long it actually take with 1k or 5k cache dirs.

**Comment by Lineflyer** [comment]
Quick test performed yesterday regarding move performance:
Samsung Galaxy S4
SD-card 1GB (class tbc)

- I downloaded 1000 caches to the internal memory (incl. static maps (for some caches, due to reaching download limit, log pictures, etc.)
- I triggered move to the SD-card
- The process was ongoing for 25 minutes until it finished with "Success".
- Looking at the SD it was full (ao around 1GB was moved in 25min.)

Problems here:
- Progress indicator would really be good given that the process can take a long time
- Handling of SD-card full while moving needs either to be properly reported back to the user or we should check source size and target capacity before moving.
- Maybe an additional warning before the process would be good: "This process can take a long time, do you want to continue".

**Comment by pstorch** [comment]
I'm thinking of calculating the used space in the GeocacheData directory and also showing the available free disk space in the selection dialog (per mount point). 
Then we could prevent choosing a directory, if there is not enough space.
