### ISSUE TITLE
Handling of full SD card with GeocacheData on SD active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6427]
##### Detailed steps causing the problem:
- Have a full SD-card 
- Open nearby list
- Try to store search results

##### Actual behavior after performing these steps:
c:geo is stuck in download progress 0/20

##### Expected behavior after performing these steps:
Some (to be discussed) handling of that problem

##### Version of c:geo used:
http://ci.cgeo.org/job/cgeo%20pull%20request/816/artifact/main/build/outputs/apk/cgeo-debug.apk

##### Is the problem reproducible for you?
Yes

##### System information:
tbc

##### Other comments and remarks:
Just a quick test performed. Better test later.

Log:
```
23:28:08.896 Debug cgeo 10326  [refresh--2] Saving GC5NB80 Adneter Marmor ([]) to DB
23:28:09.006 Error cgeo 10326  [network--6] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.006 Error cgeo 10326  [network--6] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.006 Error cgeo 10326  [network--5] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.006 Error cgeo 10326  [network--4] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.006 Error cgeo 10326  [network--2] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.006 Error cgeo 10326  [network--9] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.006 Error cgeo 10326  [network--7] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.006 Error cgeo 10326  [network--2] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.006 Error cgeo 10326  [network--8] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--1] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--6] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--10] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--6] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--4] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--3] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--3] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--2] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--9] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--8] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--1] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--1] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--1] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Debug cgeo 10326  [refresh--2] Saving GC5NB80 Adneter Marmor ([14]) to DB
23:28:09.116 Error cgeo 10326  [network--6] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--4] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Error cgeo 10326  [network--7] Could not make directories /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData/GC5NB80
23:28:09.116 Debug cgeo 10326  [refresh--2] StaticMaps.downloadMap: request ignored because of recent "permission denied" answer
```

**Comment by pstorch** [comment]
What options do we have to handle this?
- stop storing geocache data, might be safe, but maybe not what the user would expect
- fallback to other storage location:
  - usage in parallel, might complicate our storage logic
  - move data to other and continue there, might be risky, too

I think the best thing is to stop and let the user take action. Cleanup or move to another storage location manually.

**Comment by pstorch** [comment]
BTW: I think it's not only realted to `NewDir` where we store Geocache data on real extSdCard. The emulated and internal storage can also ran out of diskspace, right?

**Comment by marcelorodrigo** [comment]
As a user, I agree with that "the best think is to stop and let the user take action". In a particular case, maybe the device and all other storage options are full, so the user can cancel the action too.

**Comment by Lineflyer** [comment]
> I think the best thing is to stop and let the user take action. Cleanup or move to another storage location manually.

I agree. That should be the case for both storage options and we can just display a message that saving failed as the selected volume is full and he should either free memory there or move to the other volume.

**Comment by Lineflyer** [comment]
BTW: This handling can also be used for the case where the user removed/disabled the SD while having the Geocache data directory on it. Can it?

**Comment by pstorch** [comment]
Do we want to act preventive? Means check available disk space before a download, import or refresh is initiated? Or catch disk full exception and take action then? In the first place what could be a good threshold? 5 MB?

**Comment by Lineflyer** [comment]
I assume the check could be time consuming...could it?
In this case I would not trigger it on every action but test once on startup and catch an error while saving followed by check (if technically possible).

**Comment by pstorch** [comment]
The check for available disk space is quite cheap. So we could do it on startup and give a warning. The catching of a full disk on write could be more work, because we write data at different places (Geocache data, static maps, field-notes, GPX export, DB backup, ...).

**Comment by Lineflyer** [comment]
@pstorch Is this covered by recent changes yet?

**Comment by pstorch** [comment]
@Lineflyer not yet. What should we do? Just a warning at startup? At less than how many MB left? 
Handling all write errors could be much work. There are a lot of places. But I can have another look here.

**Comment by Lineflyer** [comment]
Initially MHO presenting a warning for running low on memory is enough.
Ideally I would prefer a warning as soon as a write operation fails for whatever reason (e.g. "c:geo failed to save geoacche data. The storage might be full or not available"). If this would require a lot of effort to realize, my second preference would be a check on startup (might habe unknown effects on first startup and requires time on every startup).

The other option would be to silently fail and revert to the internal storage.
This however would require a lot of case distinctions AFAIK....What if the disk full appears on the internal storage, etc. 
So I would prefer to find a solution which just informs the user in case the whaatever currently selected storage is full,

**Comment by Lineflyer** [comment]
IMHO the recently introduced warning is a sufficient solution for this issue.
Will test it and if it works I suggest closing this issue.

**Comment by Lineflyer** [comment]
Tested with 2017.04.23-RC:

- I created a dummy file on my external SD, so that 50MB are free
- On startup the warning is shown

As a next step I moved the additional data back to internal storage (which has 2,6GB free). On next startup no warning is shown.

IMHO this warning is sufficient for this issue.
Thanks @pstorch
