### ISSUE TITLE
Not all GeocacheData elements moved

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6437]
Today I installed 2017.03.23-NB containing the NewDir onto my regular device.
I checked the condition of `/.cgeo/` after migration: It was still existing and contained a directory `TC9KV` with pictures, maps, etc.

This is the additional data of a terracaching cache I have stored on my device (imported by GPX).
It seems the TC-prefix is missing for the move operation (and maybe also on other places in c:geo where this code was derived from).

**Comment by pstorch** [comment]
That should be easily fixable. Starting here.

**Comment by pstorch** [comment]
Oh, there are more prefixes missing:

- TC:
```
PATTERN_GEOCODE = Pattern.compile("(TC|CC|LC)[0-9A-Z]{1,4}"
```

- SU:
```
    static final CharSequence PREFIX_MULTISTEP_VIRTUAL = "MV";
    static final CharSequence PREFIX_TRADITIONAL = "TR";
    static final CharSequence PREFIX_VIRTUAL = "VI";
    static final CharSequence PREFIX_MULTISTEP = "MS";
    static final CharSequence PREFIX_EVENT = "EV";
    static final CharSequence PREFIX_CONTEST = "CT";
```

- GE
```
        return StringUtils.startsWith(geocode, "GE") && isNumericId(geocode.substring(2));
```

- GA:
```
        return (StringUtils.startsWithIgnoreCase(geocode, "GA") || StringUtils.startsWithIgnoreCase(geocode, "TP")) && isNumericId(geocode.substring(2));
```

- Waymarking:
```
        return StringUtils.startsWith(geocode, "WM");
```

Are all of them still active? I don't see GA, GE and Waymarking in the Settings/Services.

**Comment by pstorch** [comment]
I think we only have to use the pattern matching on migration. Later on when changing from emulated to real extSdCard, we have a pure GeocacheData directory without other files like backups in it.
