### ISSUE TITLE
Handling of SD-card full "before" moving geocache data

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6456]
Follow up from #6426 

https://github.com/cgeo/cgeo/issues/6426#issuecomment-288357770:
- Handling of SD-card full while moving needs either to be properly reported back to the user or we should check source size and target capacity before moving.
- Maybe an additional warning before the process would be good: "This process can take a long time, do you want to continue".

https://github.com/cgeo/cgeo/issues/6426#issuecomment-288860440
I'm thinking of calculating the used space in the GeocacheData directory and also showing the available free disk space in the selection dialog (per mount point).
Then we could prevent choosing a directory, if there is not enough space.

**Comment by Lineflyer** [comment]
> Maybe an additional warning before the process would be good: "This process can take a long time, do you want to continue".

Having a warning (also independently of the free space check) is IMHO very meaningful.
As we learned in the tests the move operation can take very long and it cannot be aborted. So the user should be informed upfront of this lenghtly operation.

**Comment by Lineflyer** [comment]
Progress indication and disk space calculation seem to work well on my Samsung Galaxy S7.
@pstorch Well done!

Only one question:
I had the data stored on external SD.
After accessing the dialog is shows "282,3MB used", I continued to move it to internal SD again, which was succesful. 
Then I called the dialog another time. Now it shows "192,4MB used". Why?

**Comment by Lineflyer** [comment]
Add on:
After the steps I previously described and wanted to try one more time to move the data.
After moving the data again to external SD and invoking the dialog again it shows "0B used". There seems to be something wrong here. Will open a new issue for that.
