### ISSUE TITLE
Live map is showing unwanted caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6460]
Since approx. one week there is a rise of support mail with problems, that the live map is showing:
- Found/Owned caches although setting to hide them is enabled
- Ignored caches (caches on ignore list at gc.com)

System info for the users is showing a normal login status and some people confirmed, that showing up of found caches is not due to the "zoom limitation".

It could be either an issue on server side or somehow the login is getting invalid without us detecting it (given that we recently changed the login procedure).
I will try to keep an eye on it, if anyone else finds some clues feel free to share them here.

**Comment by rsudev** [comment]
Looks like #6464 is another sign of this behaviour.

**Comment by Lineflyer** [comment]
I could see this behaviour today on the live map while on a long bike tour:
At some point found caches show up on the map not marked as found also when you open the popup.
Most times loading cache details is stuck on "Loading page".

Going back to the main screen I still see "Login OK" and nearby search seemy to work normal, however live map is only fine again after force kiling and restarting cgeo.

**Comment by Lineflyer** [comment]
Closed as not reproducible for now.
