### ISSUE TITLE
Landkreise (resp. Gemeinden) anzeigen

### ISSUE THREAD

**Issue by real-QQI** [cgeo/cgeo#6462]
Wäre es möglich einzublenden, in welchem Landkreis (in der Schweiz = Gemeinde) ein Cache gelistet ist?
Mir wäre das sehr dienlich.

So wie beispielsweise in project-gc.com ...

Jeder Cache ist in einer Region (wird bereits angezeigt), 
einem Bundesland (je nach Land = Provinz oder Kanton...) und 
einem Landkreis (in der Schweiz = Gemeinde) zugeordnet.
Es geht darum diese niederere Ordnung zu erfassen und einzublenden.

Lg Phil
(QQI)

**Comment by SammysHP** [comment]
We can just show what is sent by the platform (GC, OC …). Usually only the county is available.

**Comment by Lineflyer** [comment]
Thanks for your suggestion.
In fact a duplicate of #5801 and #4457.
