### ISSUE TITLE
Consecutive move of geocache data has problems

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6463]
##### Detailed steps causing the problem:
- Move geocache data from external to internal
- In the dialog before moving it shows "xMB used" (x=282,2 in my case)
- Move geocache data again from internal to external
- In the dialog before moving it shows "yMB used" (y=192,4 in my case)
- Move geocache date again from external to internal

##### Actual behavior after performing these steps:
In the dialog before moving it now shows "0B used"
Actually also the progress is getting much faster now (almost instantly).

##### Expected behavior after performing these steps:
First we need to find out what actually happens here.
Is the data still moved or do we count less data and also move less data?

##### Version of c:geo used:
2017.03.29-NB1

##### Is the problem reproducible for you?
Yes

##### System information:
Samsung Galacy S7 with Android 7.0 and external SD 64GB

**Comment by Lineflyer** [comment]
After having a look onto the file systems after the above procedure I have split data:
- 137 geocache dirs with data on internal SD
- 52 geocache dirs with data on external SD

**Comment by pstorch** [comment]
That doesn't sound so good. Do you see anything in the logs? I think I have to test with a bigger set of files/directories.

**Comment by pstorch** [comment]
At the moment the copy/move process doesn't stop on error, it just continues and tries to copy whatever it can. But it doesn't delete the source file, if the copy to the target failed.

The error handling is really difficult. If we stop in between, then we also might end up with a data split. Some directories might already been moved, some not.

At least we should properly report that there are some failures and not all files were copied. Maybe with the option to retry. I need to think a bit about the options we have. Ideas welcome ;)

**Comment by pstorch** [comment]
Maybe the deletion of the directories fails sometimes and when copying back some directories are still there from the last move and got skipped. @Lineflyer can you check if there leftovers after a move?

**Comment by pstorch** [comment]
One more thing: how do we want to handle the case that there are directories and files already in the target directory? At the moment these are skipped (this might cause this issue). Is it safe to overwrite? At least directories could be merged.
We could also stop hard if the target directory is not empty. But I fear that this behavior can cause more trouble on support.

**Comment by pstorch** [comment]
@Lineflyer I've added error reporting, if some or all moving failed. I've removed the skip if the target directory exists. So leftover target directories get merged now.
I've tested with a bigger filebase (PQ of 1000 caches) and caused errors on purpose. With this test setup I ended up with 116 MB in one directory and 240 KB in the other. Then I applied this patch and was able to synchronize both directories to the full 116 MB by performing the move forth and back.
I hope it helps with your device with a real extSdCard, too. Let's see.

**Comment by Lineflyer** [comment]
I might find some time for another round of testing sunday evening.
I will report back then.

**Comment by Lineflyer** [comment]
I tested the migration path from 2017.03.29 to 2017.04.03-NB and the consecutive move of the geocache data between internal and external storage without any problem on my Samsung S4 running Android 5.0.1.

However the original issue was with my Samsung S7. I will later retest also on this device.

**Comment by Lineflyer** [comment]
Now also tested consecutuve moving with my Samsung S7 which orginally revealed this problem. This time everytime is running smooth. Seems the recent changes made it more reliable. Closing for now.
