### ISSUE TITLE
New logs not shown (login problem?)

### ISSUE THREAD

**Issue by PETERzLV** [cgeo/cgeo#6464]
##### Detailed steps causing the problem:
- I recieved som new log on my caches and some notifications about logs on caches what I am watching
- After refresh the caches in c:geo I can not see today's logs.

##### Version of c:geo used:
2017.03.29

--- System information ---
Device: SM-A500FU (a5ultexx, samsung)
Android version: 6.0.1
Android build: MMB29M.A500FUXXS1CPK1
Cgeo version: 2017.03.29
Google Play services: enabled - 10.2.98 (436-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: sk_SK
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Prihlásenie úspešné) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins:  none
--- End of system information ---

**Comment by rsudev** [comment]
We suspect, that due to recent changes, c:geo might get logged out without noticing it.
To check that, you could kill c:geo, start it again and then refresh the cache once more.
Do the logs appear?

**Comment by PETERzLV** [comment]
I have logged-out from c:geo.
Then I logged-in and I have click to "Check authorisation" ...

And now it is correct.

Thank you very much for help.
And I am sorry for this issue.
😆

**Comment by PETERzLV** [comment]
👍

**Comment by rsudev** [comment]
Today I experienced also an instance of this problem, but have to dig deeper for further analysis.
- I opened c:geo and tried to refresh an existing cache - no new logs download
- Kicking c:geo out of the app-stack, opening again (seeing 'logging in...' on the main screen) - no new logs loaded
- Force stopping c:geo (in Android settings - Apps), opening again (seeing 'logging in...' on the main screen) - new logs were loaded.

Somehow the cookies, their lifetime, renewal of the login tokens or other details around the login process are different in the new login page.
It should be noted, that AFAICS the 'stay logged in' checkbox is no longer present on that page.
Furthermore do I have no issue staying logged in on Firefox for weeks on end.

**Comment by Lineflyer** [comment]
That matches my experiences, that at some point of time the live map stops working.. 
Can someone take a look into the recent changes of the login and cookie storage? AFAIK @samueltardieu did not only change the login page but also some of the surrounding procedures.

**Comment by Lineflyer** [comment]
I ran across this error while testing some other stuff, it might...but also might not be connected to this issue:
```
20:15:05.239 Warning cgeo 4042  [OkHttp] Failure (11873 ms) GET https://www.geocaching.com/seek/geocache.logbook?tkn=4OB3GFHLRR3CGAUGOYCJ5F5VO3SCW3UC6PXUL5Z2D5GKRSGA2TAO3RL5K6RIVL6DODLPYLE4FQBZGBADI3IJNIBH6SI732SQ32CYCJYW2XVMAPXDXDHCFLYHSIVVPL4LJMAQXERKF37TDUEV7HHQTXT63IPZA2MW6NTQWD5PBGYBRMA5W377EUTHB3UFOLFPK3QOZ7QYTV4LD2JHJXIMSZZEJM2DTROBJARCCL2GQEJ6QZRA22LQ2JPYCZOV46GPWUFJTXCZIJLQ7LRYADLBMZOKMGXL7HBXSUU7YAXSJZDRLZ5QZMZOIWFG5KOXZUFJ&idx=1&num=35&decrypt=false&sp=true (javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x25011a0: I/O error during system call, Connection reset by peer)
20:15:05.239 Warning cgeo 4042  [network--2] GCParser.loadLogsFromDetails: Failed to parse cache logs
20:15:05.239 Warning cgeo 4042  com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
20:15:05.239 Warning cgeo 4042   at [Source: UNKNOWN; line: 1, column: 0]
20:15:05.239 Warning cgeo 4042  	at com.fasterxml.jackson.databind.DeserializationContext.reportMissingContent(DeserializationContext.java:1248)
20:15:05.239 Warning cgeo 4042  	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:358)
20:15:05.239 Warning cgeo 4042  	at com.fasterxml.jackson.databind.ObjectReader._bindAsTree(ObjectReader.java:1647)
20:15:05.239 Warning cgeo 4042  	at com.fasterxml.jackson.databind.ObjectReader._bindAndCloseAsTree(ObjectReader.java:1639)
20:15:05.239 Warning cgeo 4042  	at com.fasterxml.jackson.databind.ObjectReader.readTree(ObjectReader.java:1331)
20:15:05.239 Warning cgeo 4042  	at cgeo.geocaching.connector.gc.GCParser$4.subscribe(GCParser.java:1808)
20:15:05.239 Warning cgeo 4042  	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
20:15:05.239 Warning cgeo 4042  	at io.reactivex.Observable.subscribe(Observable.java:10700)
20:15:05.239 Warning cgeo 4042  	at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:39)
20:15:05.239 Warning cgeo 4042  	at io.reactivex.Observable.subscribe(Observable.java:10700)
20:15:05.239 Warning cgeo 4042  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
20:15:05.239 Warning cgeo 4042  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
20:15:05.239 Warning cgeo 4042  	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
20:15:05.239 Warning cgeo 4042  	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
20:15:05.239 Warning cgeo 4042  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
20:15:05.239 Warning cgeo 4042  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
20:15:05.239 Warning cgeo 4042  	at java.lang.Thread.run(Thread.java:864)
```

This was not reproducible but happend while batch refreshing caches on a list.

**Comment by samueltardieu** [comment]
@Lineflyer This one is unrelated but could benefit from a cleanup (being tested by the CI right now).

**Comment by Lineflyer** [comment]
@PETERzLV 
Is this issue still present?

**Comment by PETERzLV** [comment]
No.
Everything is going correctly.
