### ISSUE TITLE
Add opencaching.gr

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6466]
Not jet, but in the near future.

http://blog.opencaching.de/2017/04/pulu-uoll/

**Comment by SammysHP** [comment]
@Lineflyer, @rsudev 

Can you please enable Greek language in Crowdin?

**Comment by rsudev** [comment]
Greek as target language is now enabled.

**Comment by Lineflyer** [comment]
I thought it was some April Fool, but seems not :)

**Comment by Lineflyer** [comment]
Seems it was either a April Fool or it was never realized.
