### ISSUE TITLE
Field note file not accepted by OC.de

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6467]
Today I had the first opportunity to use cgeo field notes with OC.de
After uploading a file containing OC and GC notes, the Oc.de website declared the file as invalid.

Need to test later whether the mixed content is the problem, or something else.

**Comment by teiling88** [comment]
@Lineflyer i am a developer from oc.de. Please provide your field note file so i can check it.

**Comment by Lineflyer** [comment]
Sent by mail to the address refered to in your github account.

**Comment by teiling88** [comment]
I created a ticket in our ticket system for it: http://redmine.opencaching.de/issues/1042

**Comment by Lineflyer** [comment]
FYI after reading the forum posting linked below the mentioned ticket:
My fieldnotes also contain line feeds. My experience from GC import is, that all the text incl. the line feeds are kept after import (on contrary to what ra_sch aka @rsudev posted there with his text with the unix linefeed file).

**Comment by teiling88** [comment]
Hey thanks Lineflyer for your FieldNotes file. I created a pull request with an small fix to support breaks in field notes for the opencaching.de site :-) 

https://github.com/OpencachingDeutschland/oc-server3/pull/473

**Comment by teiling88** [comment]
This issue can be closed. All needed changes are deployed.

**Comment by SammysHP** [comment]
Thank you!
