### ISSUE TITLE
Optimize live map loading

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6468]
While doing extensive tests regarding #6460 (which I was not able to reproduce) I could see some other things on the live map which could are not optimized:

- We seem to load caches for an area which is much wider than the visible map
- There seems to be some limit(?) of 500 caches we hold on the map, which is easily reached in high dense cache area.

Let me try to explain what I see as a possible follow up of these facts:
After starting the live map in an area with many caches, I do e.g. see 12 caches on the map and the header says 12/500. Now I move the map slightly westbound until a new loading cycle is triggered. 
As soon as the new loading is finished it often happens that some of those 12 caches I have initially seen on the map (see above) suddenly disappear although they are not out of view.

My interpretation:
It seems that loading the new caches while the "buffer" of 500 caches is already filled drops some others of those 500 caches (and sometimes also those still within view on the map).

Couldn't we:
- Limit the area for which caches are loaded more tight to the map area really shown 
- Raise the limit of 500 caches or apply a better strategy of which caches are dropped out of this "buffer"

Tested with release 2017.03.29 on Samsung S4, Premium account, detailed mode, Google Maps

**Comment by rsudev** [comment]
The buffer (should) work as an LRU cache, so those 12 last displayed should stay on the map. But I also don't think, that the query area is that much larger than the displayed map, that you see only 12 caches, and 500 are loaded. Or did you move the map around, to accumulate this number of caches loaded?
Can you share the center coordinates and zoom level of your test, so I can check whether there is something amiss?

**Comment by Lineflyer** [comment]
You are right. I might have moved the map around, or zoomed out and in before I had 500 caches.
Still I can pretty good reproduce (as on my home location there is only one unfound cache) that caches disappear from view.

Maybe you could try with any location by:
- Open live map
- Set strategy "Fast"
- Zoom out or move until 500 caches are "buffered"
- Slightly zoom west/east (in my case this works best) to see whether caches go missing

**Comment by Lineflyer** [comment]
Obsolete after #7514 was merged.
