### ISSUE TITLE
Google suggests to support new aspect rations

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6469]
From Google Play recommendations:
https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html

**Comment by SammysHP** [comment]
> Note: if you don't set a value, and android:resizeableActivity is not true, then the maximum aspect ratio defaults to 1.86 (roughly 16:9) and your app will not take advantage of the extra screen space.

As we support multi-window mode (do we?) everything should be fine.

https://developer.android.com/guide/topics/ui/multi-window.html#configuring

**Comment by SammysHP** [comment]
Sorry, hit the wrong button.

**Comment by Bananeweizen** [comment]
@Lineflyer Multi-window is enabled automatically for our app due to being less than level 24. See https://developer.android.com/guide/topics/ui/multi-window.html#configuring
