### ISSUE TITLE
Translation strings - sdcard, external storage, "public filesystem"

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6470]
Recently there were some new strings to be translated. 
One example is `init_dbonsdcard` with english string : "_On public file system_"

IMO the use of the word "public" is not the best choice here. 
While from the developer perspective, the private internal storage space available for apps is one thing, and the user visible filesystems, be it internal emulated, internal partitioned, external as in SD card or external as in USB OTG mount, the latter might be considered "public" as opposed to private, no user access, 
from user point of view the semantics of the word "public" is different. 

- user knows less about internal storage and more about what he/she sees via file manager, meaning internal emulated / partitioned and SD card (where available), as filesystems in the same sense as on a desktop computer. 
- user might understand by "public" something like publicly available - that is available to anyone (not restricted to his device), including cloud like storage. Also this may raise undesirable flags in the user's mind.
- user knows about **internal storage** = internal emulated/partitioned storage as seen by file manager
- user knows about **external storage** aka **SD card** where available (device has slot and slot contains sdcard)

---
IMO what c:geo should make clear is the following: 
- c:geo storing it's database internally (same as app data and app cache; not available to user)
- c:geo storing it's database on internal/emulated storage (but user available)
- c:geo storing it's database on external/sdcard storage (user available)

P.S. 
Don't forget about newer Android versions that drastically restrict access to sdcard directories (unless rooted)

**Comment by andrixnet** [comment]
> Hi andrixnet,
> 
> regarding "public file system". That was done intentional. In fact the database will no longer be moved to the SD but from "private file system" (hidden, only accesible by c:geo (or with root))) to the publicly available file system (normally the emulated SD or internal storage).
> 
> I will review the wording of external storage once again (have to look up how it is used):
> AFAIR we now always refer to SD card intead of external storage.
> 
> Sorry for answering so late, maybe next time you can also raise questions to the translation as issue on Github.
> 
> Best regards,
> Lineflyer"

**Comment by Lineflyer** [comment]
> c:geo storing it's database on external/sdcard storage (user available)

This option is not foreseen.

You can also learn about the new approach of the file structure from our Wiki:
https://github.com/cgeo/cgeo/wiki/Target-disk-usage-structure

In short:
1. Database
Option 1: Internal (not accesible)
Option 2: on emulated (user accesible)

2. Geocache Data
Option 1: On Emulated (user accesible)
Option 2: On external SD (user accesible)

**Comment by Lineflyer** [comment]
Add on:
But I agree we should replace "public file system" by something like "user accesible path".

**Comment by Lineflyer** [comment]
@andrixnet Please review the changes I made in the mentioned commit. It should be better wording now.

**Comment by Lineflyer** [comment]
@rsudev: If @andrixnet has reviewed it, we should put another string update to Crowdin.

**Comment by Lineflyer** [comment]
I added some line comments to the linked commit.
If there are no objections I will raise another PR (and keep it open for review by @pstorch and  @andrixnet ).

**Comment by Lineflyer** [comment]
@rsudev Now, that the wording has been finalized you could upload strings to Crowdin once again if time permits. Please do not yet import from Crowdin, as the upload will invalidate some strings for retranslation.

**Comment by rsudev** [comment]
New strings uploaded.
