### ISSUE TITLE
Dialog for dir selection truncated

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6472]
Thats how it looks on my Samsung S4.
You are not able to see the free space on the target dirs:
![screenshot_2017-04-03-21-00-12](https://cloud.githubusercontent.com/assets/949669/24629391/26283eea-18b9-11e7-8cf2-5108fd24fd96.png)

**Comment by pstorch** [comment]
Spent some minutes yesterday to find a solution for it. The only thing I found so far was to squeeze the text horizontally:
![screenshot_20170404-072404](https://cloud.githubusercontent.com/assets/5598124/24643511/b8c6c74e-190e-11e7-95be-a8480ade07ad.png)
But I'm not sure if this is a good solution.

**Comment by Lineflyer** [comment]
A workaround would be to show the size first and then the target dir.
But this would still be not complete as the user might want to know the full path. Alternatively we could show the target path once again together with the complete message.

**Comment by pstorch** [comment]
What about truncating at the beginning and the ending which all mount points have in common?
This would look something like this:
- .../emulated/0/...
- .../extSdCard/...

Or just truncate the common ending:
- /storage/emulated/0/...
- /storage/extSdCard/...

The full path will still be shown in the SettingsActivity.

**Comment by pstorch** [comment]
Here is an example with truncated endings:
![screenshot_20170408-165548](https://cloud.githubusercontent.com/assets/5598124/24829956/7bb4d852-1c7c-11e7-8e49-7a030a96ab06.png)

**Comment by Lineflyer** [comment]
@pstorch If there is no system designed solution for this it is IMHO ok to truncate as shown in your example.
I don't know how you truncate, but maybe have a look into the recent issues for "New Dir" to get some different examples of mountins points (e.g. `/mnt/sdcard/` `/storage/sdcardx`) to check whether it will also work for them.
