### ISSUE TITLE
Provide an action that removes caches stored on other lists from the current

### ISSUE THREAD

**Issue by FUSSEL4** [cgeo/cgeo#6473]
### Feature request

Please, provide a action that removes caches from the current list that are stored already on other lists.

Every week, I use a downloaded gpx file generated by a PQ to find new caches. 
The PQ contains also caches that are already stored in different lists in cgeo. I want to remove caches from the import list that are already stored in cgeo on other lists.

An action like this would make it so much easier to detect new caches in an imported PQ.

(I'm going to implement this.)

**Comment by Lineflyer** [comment]
Could be a valid request, for your usecase I suggest the following workaround:
- You have your caches on list x (already stored)
- You import your PQ into list y (contains already stored + new ones)
- You go to list x and select "Make this list unique"

This will remove all caches which are on both lists x and y from list y and should result list y to show only "new" caches.

**Comment by Bananeweizen** [comment]
While this seems reasonable, it currently does not fit our filter architecture. Filters are not aware of the state of the remaining app (e.g. which list is shown). I don't see how to create such a filter, that must be updated with every switch of the current list, without breaking that clean architecture.

**Comment by Lineflyer** [comment]
@FUSSEL4 Can you live with the workaruond provided?

**Comment by FUSSEL4** [comment]
@Lineflyer The workaround works if one has all the caches only on list X.
For me, it won't work because I usually have my caches on different list. This structure would be destroyed making the caches on list X unique.

**Comment by Lineflyer** [comment]
So, then lets leave this open.
Maybe it can be realized by some standalone functionality (not within filter) like "Select all caches, which are only on this list".

**Comment by FUSSEL4** [comment]
@Bananeweizen I see your point. I wasn't aware of the fact that the filter's data is pre-calculated at every change of the list. I thought the caches are filtered right at the moment the filter is selected by looping through the list and checking the criteria.

**Comment by FUSSEL4** [comment]
@Lineflyer OK.
If it's not possible to have the functionality as a filter why not making it an operation? Something like "Remove all caches that are already stored elsewhere".

**Comment by SammysHP** [comment]
Good idea, similar to "make unique" but without affecting other lists.

**Comment by FUSSEL4** [comment]
I changed my Feature Request to request an action rather than a filter.

**Comment by FUSSEL4** [comment]
I'm going to implement that in the way like _Make Caches Unique_ is done.

**Comment by Lineflyer** [comment]
@FUSSEL4 So you are working on a contribution for this?

**Comment by FUSSEL4** [comment]
@Lineflyer Yes, I work on a contribution for this issue.

**Comment by Lineflyer** [comment]
@FUSSEL4 
I am currently checking issues, and I am unsure about the state of this request.
Did you send another PR as announced in https://github.com/cgeo/cgeo/pull/6540 ?

**Comment by Lineflyer** [comment]
This should meanwhile be possible on the new filter framework as you can filter by membership to lists.
