### ISSUE TITLE
configure gradle build cache

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6477]
gradle 3.5 will have a build cache that can span over multiple builds: https://docs.gradle.org/3.5-rc-3/release-notes.html#faster-builds-with-the-gradle-build-cache

After the release, we should have a look at the configuration to make our builds faster, and at the same time not to consume all available disk space on the generally small Jenkins agents.

**Comment by bekuno** [comment]
In the meantime we are on version 4.10.2.
I suppose to configure the build cache as active.
Maybe it is neccessary to explicitly disable this for the CI with "--no-build-cache" call.
In https://docs.gradle.org/4.10.2/userguide/build_cache.html are some samples.

**Comment by bekuno** [comment]
@kumy Is this space problem still relevant?

**Comment by kumy** [comment]
I thought cache was already active, as I only saw full downloading of libraries on first build after executor fresh creation. If option is not active, I would say, activate it and we get troubles then we can disable it later ;)

**Comment by kumy** [comment]
Oh, it's about build cache, not dependencies cache. Same idea, let's give it a try, no?

**Comment by kumy** [comment]
We have 70G free space on slave host and 389G on master. It is also viewable at http://ci.cgeo.org/computer/ as an authenticated user.

**Comment by kumy** [comment]
We could also create a dedicated `cleaning job` in Jenkins to be automatically launched at a defined interval. @bekuno do you know the command to clean the build cache?

**Comment by bekuno** [comment]
Not really, I would say 'rm -rf' . From Doc:
The built-in local build cache, DirectoryBuildCache, uses a directory to store build cache artifacts. By default, this directory resides in the Gradle user home directory, but its location is configurable.
Gradle will periodically clean-up the local cache directory by removing entries that have not been used recently to conserve disk space.
For more details on the configuration options refer to the DSL documentation of DirectoryBuildCache. Here is an example of the configuration.
Example: Configure the local cache
settings.gradle

buildCache {
    local(DirectoryBuildCache) {
        directory = new File(rootDir, 'build-cache')
        removeUnusedEntriesAfterDays = 10
    }
}

Ok?

**Comment by kumy** [comment]
@bekuno would you provide a PR? :smile:

**Comment by bekuno** [comment]
Already on the way.

**Comment by bekuno** [comment]
I have in the cache dir:
* 20 MB initial
* +10 MB in every next run (2 tests)
