### ISSUE TITLE
Manage gc.com notifications from c:geo app

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#6479]
Hi,

I'm thinking about integration of notification management into c:geo. Currently I'm using website to achieve desired settings:
https://www.geocaching.com/notify/default.aspx
But this is really incovenient method as it doesn't support any reasonable coordinate selection (like click in map or my own coords). And what's the most annoying that it can not set same notification for multiple types of caches (that could be achieved by setting it by checkboxes).

Do you think that it's a good idea to integrate this in c:geo, maybe just as plugin or it should be completely new app?

I can imagine, that at least UI for selecting coordinates by map can be reused in other parts of c:geo. And the rest is not very complicated. I would at least reuse the authentication mechanism.

Thanks for comments

TriakCZ

**Comment by rsudev** [comment]
I must admit, that I had set it once for my 'homezone' some years ago, and only two or three times had the necessity to look back.
So IMO it is too specialized for inclusion into c:geo as such. I could imagine this as a kind of plugin or stand-alone app (which could of course take advantage of the c:geo codebase).

**Comment by Lineflyer** [comment]
This is for sure something outside of c:geo IMHO.

**Comment by Lineflyer** [comment]
I am sure the message center will never been implemented into c:geo as of now.
There are other issues dealing with workarounds such as detecting unread messages and offering to open the message center in a browser. That should be the compromise here.
