### ISSUE TITLE
No SD shown as available [ZTE Grand Memo LTE]

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6480]
##### Detailed steps causing the problem:
- I had the chance to test the todays nightly on a phone which has different mounting paths than my normal Samsung devices (ZTE Grand Memo LTE)
- The device has an internal SD on `/storage/sdcard0`
- My external SD is shown on `/storage/sdcard2`

##### Actual behavior after performing these steps:
c:geo does not offer a second option for moving the data but presents onyl the current selection (after fresh install) which is `/storage/sdcard0/Android/...`

##### Expected behavior after performing these steps:
c:geo should be able to find the SD card

##### Version of c:geo used:
2017.04.09-NB

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: ZTE Grand Memo LTE (Grand-Memo, ZTE)
Android version: 4.1.2
Android build: GEN_EU_GRANDMEMOLTEV1.0.0B06
Cgeo version: 2017.04.09-NB-b85f032
Google Play services: disabled - 10.2.98 (036-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (default state)
System language: en_US
System date format: dd/MM/yyyy
Debug mode active: yes
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
I installed [SD Insight](https://play.google.com/store/apps/details?id=com.humanlogic.sdi) to see, whether other apps are able to find the SD. This tool is working without problems?

Does anyone know an easy way to output the results of `getExternalFileDirs`, etc.?

**Comment by Lineflyer** [comment]
Addon:
For debugging it might be good if we log an info when the scan is performed, to give debug info about the found or not found storage points.

**Comment by pstorch** [comment]
`getExternalFilesDirs` is API Level 19 (Android 4.4). This device is 4.1. So we can only find the emulated one given by `getExternalFilesDir`.

**Comment by Lineflyer** [comment]
Mmh. Is this reflected somewhere in the UI?
e.g. shouldn't we hide the Geocache data dir selection menu below API 19 or even generally if only one selection is available?

**Comment by pstorch** [comment]
I thought I've disabled it when there is only one option, but it looks like it's not. I'll check.

**Comment by pstorch** [comment]
I've disabled the dirchooser if only one external dir is available. Don't know if it is enough to close this issue.

**Comment by Lineflyer** [comment]
I think it should be sufficient.
I will test with this change and provide feedback.

**Comment by Lineflyer** [comment]
Tested again on the mentioned device with 2017.04.10-NB.
Now the selector is greyed out which is perfectly fine IMHO.

We should consider for the FAQ to mention that the external storage might not be available below API 19 or should we generally disable that menu in the same way if API<19?

**Comment by pstorch** [comment]
> Should we generally disable that menu in the same way if API<19?
That would be the same result. If API<19 we only have one external storage to choose from, then it's disabled.

**Comment by Lineflyer** [comment]
Perfectly fine then. Lets close this.
