### ISSUE TITLE
c:geo not shown as authorized after first login

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6482]
##### Detailed steps causing the problem:
- Fresh install c:geo
- On the given screen provide valid gc.com credentials
- Click on "Check authentication"
- Toast is showing that you succesfully authenticated to gc.com and returns to Menu - Settings - Services - geocaching.com

##### Actual behavior after performing these steps:
On this screen it is stil shown "c:geo not authorized yet" although it has been authorized.
Only after leaving and reentering the menu the correct status is shown

##### Expected behavior after performing these steps:
Correct status and user avatar should be shown direclty or after succesful authorization c:geo should return to the main page.

##### Version of c:geo used:
2017.04.09-NB

##### Is the problem reproducible for you?
Yes, not sure whether this is nightly specific or already contained in older versions

**Comment by Lineflyer** [comment]
This is already present in 2017.03.29 (productive version) and seems to irritate quite some users.
Set label "Regression".

**Comment by samueltardieu** [comment]
I can't reproduce this on `master`. When the toast is displayed and the geocaching.com page is displayed again, I can see my avatar and "re-authorize".

**Comment by samueltardieu** [comment]
@Lineflyer I'll send you a video privately which shows what I'm seeing.

**Comment by Lineflyer** [comment]
Procedure is the same I am performing. However my result as initially described. Might it be a timing issue of when the avatar images download is finished?

**Comment by Lineflyer** [comment]
This seems to be Android version or device specific.
In fact it only appears on one of my devices:
```
--- System information ---
Device: HTC One V (htc_primou, htc_europe)
Android version: 4.0.3
Android build: htc_primou-userdebug 4.0.3 IML74K eng..20120319.235315 test-keys
Cgeo version: 2017.04.09-NB-b85f032
Google Play services: enabled - 9.4.52 (034-127739847)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (default state)
System language: de_DE
System date format: dd.MM.yyyy
Debug mode active: yes
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (Anmeldung…)
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
@samueltardieu Unless you can easily retest this with the mentioned Android version, I suggest to close this issue. It seems only these rather old version (or the device) has a problem, all other devices I have do not show this issue. Feel free to retest or close as you like.

**Comment by andrixnet** [comment]
I can reproduce this issue on fresh install of c:geo.
Happens at least with geocaching.com account and geokrety.org account.

**Very first screen when starting c:geo for the first time (after installation)**
![screenshot_2017-05-10-08-54-13](https://cloud.githubusercontent.com/assets/3382777/25886128/db8e167a-3564-11e7-9e9a-f44c02018989.png)

**Authorization confirmation still showing `not connected yet`**
![screenshot_2017-05-10-08-54-48](https://cloud.githubusercontent.com/assets/3382777/25886146/effb43c6-3564-11e7-8707-8c1ccfdef8c5.png)

Either return user to services list, or update this screen.

c:geo version: 2017.03.29 (production)
Device: Allview P5 Quad / Xolo Q800 (same device, different brands)
Android: 4.2.1

**Comment by fm-sys** [comment]
> It seems only these rather old version (or the device) has a problem
---
> c:geo version: 2017.03.29 (production)
Device: Allview P5 Quad / Xolo Q800 (same device, different brands)
Android: 4.2.1
>
> Device: HTC One V (htc_primou, htc_europe)
Android version: 4.0.3

Due to the comments it seems to be only reproducible on ≤ Android 4 which we do not support anymore, so I'm quite sure can this be closed. If anyone can still reproduce it, please comment with the system information attached.
