### ISSUE TITLE
GSAK First log

### ISSUE THREAD

**Issue by ElgorGc** [cgeo/cgeo#6484]
Hi, 

Cgeo remove the first log created by GSAK when user refresh caches.
This first log contains personnal notes, it is alway the first log of the cache in the GSP created by GSAK.
The user is always GSAK.

**Would it be possible to keep this log even after a refresh ?**

##### Detailed steps causing the problem:
1) GSAK : Create some caches with personnal notes
2) GSAK : Export GPX with options
                      - include user notes in export
                      - Extra informations to show in first log = %UserNote
3) CGEO : Import the GPX (i put a gpx as attachement)
4) CGEO : You can see the notes in first log of caches
5) CGEO : Refresh all caches 
6) CGEO : The log created by GSAK as been removed

[Gpx.zip](https://github.com/cgeo/cgeo/files/912449/Gpx.zip)

Many thanks for your software
Best regards
Pierre

**Comment by pstorch** [comment]
Quick analysis:
The first log with the user note has the `id="-2"` and c:geo only accepts logs with `id > -1`.

**Comment by ElgorGc** [comment]
What do you mean by "c:geo only accept" ?

After I import GPX into cgeo the first log is displayed correctly by c:geo.
The only problem is that when i refresh caches (to upload pictures) c:geo delete this log.

So my question is it possible to c:geo to refresh caches without removing this kind of logs ?

**Comment by pstorch** [comment]
Oh no, that was too fast. It just reads the id if it is > than -1. But stores the log nevertheless.
What happens during refresh I have to debug.

**Comment by pstorch** [comment]
The problem is actually that c:geo deletes all old logs and save the new ones loaded from the webpage.
I'm not 100% sure, but maybe the problem here is that we can't match logs already loaded and don't know which ones to overwrite. 
The deletion of the old logs before saving the new ones is in the code since the beginning.

**Comment by pstorch** [comment]
Without changing too much of the current behavior of refreshing the logs and start dealing with merging and overwriting, one solution would be to import the GSAK `id="-2"` log into the usernote field in c:geo.

**Comment by Bananeweizen** [comment]
I'm not sure why this is needed at all. There are already some GSAK specific UserData1 to 4 fields, which are supported by cgeo, and which can easily take the complete user notes, without having a fake user log just for this.
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/files/GPXParser.java#L1132

If we start to not delete all logs on refreshing or re-importing a cache, we will run into many, many problems with orphaned or duplicated logs. We had all these problems with waypoints already. That's why I vote for not supporting this. If a cache is imported from the web, it has the contents from the web. If it is imported from a GPX, it has the contents of the GPX. No mixture, no trouble.

**Comment by Lineflyer** [comment]
I agree with @Bananeweizen and also prefer no change which might break the general functionality or maybe error prone. 
I think we could add a short note in our FAQ how personal notes from GSAK can be imported in a correct way. Unfortunately I have no experience with GSAK. So maybe @ElgorGc can make a proposal if the mentiones solution is satisfying.

**Comment by pstorch** [comment]
Good to know. Haven't seen that functionality before. Then I'm also in favor of not changing anything.

**Comment by ElgorGc** [comment]
First of all thank four your replies...

_I'm not sure why this is needed at all._
It is because i put there some informations about the caches principally for mysteries...

_There are already some GSAK specific UserData1 to 4 fields, which are supported by cgeo_
I tried to import a GPX with UserData1 to 4 into cgeo and i didn't see anything in cgeo...
Could you tell me where it should be ? 
I join the GPX i used 
[GpxPit.zip](https://github.com/cgeo/cgeo/files/919330/GpxPit.zip)

_and which can easily take the complete user notes_
No really because UserData1 to 4 are text fields very small and UserNotes is a comment field very large

_If we start to not delete all logs on refreshing or re-importing a cache, we will run into many, many problems with orphaned or duplicated logs._ 
Log created by GSAK are very specials id=-2 and UserName='GASK'.
So if before  importing a GPX you remove all logs except those ones,  do you really think that you will get orphaned or duplicated logs ?
There is no log with negatives id in geocaching.com.
Perhaps this could be an option not activated per default ...

_I think we could add a short note in our FAQ how personal notes from GSAK can be imported in a correct way. Unfortunately I have no experience with GSAK. So maybe @ElgorGc can make a proposal if the mentioned solution is satisfying._
GSAK handle "geocaching notes" which are exported in a GPX with the tag "gsak:GcNote" thoses notes are well read by cgeo.
GSAK handle "User notes" which are exported in a GPX as a log, there is not way to export them diffently.

**Comment by pstorch** [comment]
I've imported your GPX and I can see your notes here:

![screenshot_20170413-142359](https://cloud.githubusercontent.com/assets/5598124/25004550/31645980-2055-11e7-84c0-efc7888c6503.png)

**Comment by ElgorGc** [comment]
Those notes are notes from Geocaching.com not the GASK UserNotes.

I do a GPX with all kind of notes created by Gsak so you can see exactly what happen.

The GPX contains :
- notes from Geocaching.com : they are in Cgeo "Personnal notes"  (First line : Geocaching Notes)
- notes from Gsak UserNotes : they are in Cgeo first log    (First line : Gsak Notes)
- notes from Gask UserData1,2,3,4 : That i don't see in cgeo ( Contain : 'User 1 notes', 'User 2 notes'...)

I don't really need to use UserData1,2,3,4 in cgeo but as Bananeweizen sait it is working, i just do a test and i didn't see anything. Perhaps i miss it !

Excuse me if my english is confusing.

**Comment by pstorch** [comment]
Don't use everything in parallel. If there is a personal not c:geo ignores the UserData fields from GSAK.

**Comment by ElgorGc** [comment]
Ok i test UserData1 works fine if there is no Geocaching notes

This is a gpx with only the Gsak UserNotes
[GpxPit1.zip](https://github.com/cgeo/cgeo/files/919582/GpxPit1.zip)
