### ISSUE TITLE
Static maps marker images not available on server

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6486]
e.g. https://status.cgeo.org/assets/markers/marker_waypoint_original.png returns `Not Found`

**Comment by Lineflyer** [comment]
Actually I think it is only this image (don't remember the complete list) which is not available.
It seems to be used for "original coords" of a cache which has such kind of a waypoint.

**Comment by samueltardieu** [comment]
Where would be the source of such image? I don't know where to get it to add it to cgeo-status public resources.

**Comment by Lineflyer** [comment]
Just saw this warning again in the logs.
AFAIR these images used to be stored on www.cgeo.org in previous times. Seems we missed to transfer one of them.
@mucek4

**Comment by Lineflyer** [comment]
Contentwise it should IMHO be the combination of these two markers:
https://github.com/cgeo/cgeo/blob/master/main/res/drawable-hdpi/marker.png
https://github.com/cgeo/cgeo/blob/master/main/res/drawable-hdpi/waypoint_waypoint.png

Not sure about dimensions needed for the static maps however.

**Comment by samueltardieu** [comment]
The current markers are at https://github.com/cgeo/cgeo-status/tree/master/public/markers if you need to look at them.

**Comment by Lineflyer** [comment]
Oh, thanks @samueltardieu 
I think this one will do the job:
https://github.com/cgeo/cgeo-status/blob/master/public/markers/marker_waypoint_waypoint.png

Don't know whether this is jsut a wrong file name in the code or this one is used as well.
Can someone check the code in static maps download?

**Comment by pstorch** [comment]
The URLs for the waypoints are created like this:

https://github.com/cgeo/cgeo/blob/24e8cd8645e635e0f893c7f0375e4810f615a86d/main/src/cgeo/geocaching/staticmaps/StaticMapsProvider.java#L250

And the waypoint types are defined here (first parameter):

https://github.com/cgeo/cgeo/blob/24e8cd8645e635e0f893c7f0375e4810f615a86d/main/src/cgeo/geocaching/enumerations/WaypointType.java#L24-L31

So I guess we need to have a file on the server with the name `marker_waypoint_original.png`. I don't know the workflow for the marker files. Maybe someone with access to the server can just make a copy of the `marker_waypoint_waypoint.png`.

**Comment by pstorch** [comment]
BTW: `marker_waypoint_own.png` is missing, too.

**Comment by samueltardieu** [comment]
It needs to be integrated in cgeo-status and redeployed (we don't have access to a read-write filesystem on the server, it is redeployed from the image).

I have done the copy (waypoint_waypoint -> waypoint_original) and redeployed on Heroku.

> marker_waypoint_own.png is missing, too

If you have a source for it, I can add it as well.

**Comment by pstorch** [comment]
I'm not sure if this waypoint type `own` is really used. I couldn't create one of this type. 
Does someone know?

**Comment by Lineflyer** [comment]
Closing this issue as obsolete, as Google static maps are no longer available (without payment).
So whatever replaces them needs a new implementation anyway.
