### ISSUE TITLE
"Visited" tag in the Waypoint screen

### ISSUE THREAD

**Issue by ext666** [cgeo/cgeo#6487]
I would like to suggest a small improvement. It would be great to **tag the waypoint as "visited" directly from the waypoint screen** either by tapping on the icon [here ](http://oi66.tinypic.com/28krpxs.jpg) or via context menu braugt up by long pressing in [here](http://oi68.tinypic.com/ic32v8.jpg). It would save time a lot, cause now people have to edit and save the waypoint.

**Comment by Lineflyer** [comment]
Thanks @Bananeweizen 
Maybe you could also take a look at #2592 in this context?
