### ISSUE TITLE
Use EditorConfig?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6490]
Just found in another project a `.editorconfig` file. http://editorconfig.org/

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

Some editors are able read it without plugin, like Idea, some need a plugin, like eclipse.

What about adding such support for our project?

**Comment by Bananeweizen** [comment]
The number of settings which can actually be maintained for both Eclipse and IDEA using this approach is less than 10. The number of settings for the formatter in Eclipse alone is more than 100. I therefore doubt this will help in better aligning the 2 worlds. For Eclipse and IDEA as such we have all the formatting, editor and similar settings checked in.

**Comment by kumy** [comment]
I must admit I just read the project main page and didn't check/test anything. However IIRC `.idea` directory is not versionned anymore?

**Comment by Bananeweizen** [comment]
I see .idea/*.xml files and assume those are the settings you mean (but I don't know IDEA well enough). The Eclipse related settings are in **/.settings/*.prefs.
