### ISSUE TITLE
Translation strings of previous showcase

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6491]
Since the removal of the showcase library we are getting lots of warnings about unused strings. How do we deal with such removals with crowdin? In earlier years I simply deleted them in the source repository in all language XML files, but I'm not sure if that is still the right way.

```
01:28.337  warning: string 'showcase_cachelist_title' has no default translation.
01:28.337  warning: string 'showcase_compass_hint_text' has no default translation.
01:28.337  warning: string 'showcase_compass_hint_title' has no default translation.
01:28.337  warning: string 'showcase_logcache_text' has no default translation.
01:28.337  warning: string 'showcase_logcache_title' has no default translation.
01:28.337  warning: string 'showcase_main_text' has no default translation.
01:28.337  warning: string 'showcase_main_title' has no default translation.
```

**Comment by samueltardieu** [comment]
The clean way to do it would be to upload the string file to crowdin and download the translated files back. Removed strings in the source file will be removed from the translated files as well.

**Comment by rsudev** [comment]
The string file is already uploaded, but due to the release activity I didn't import back the master strings for some time.
And the last time I was mostly waiting for the results of storage string discussions.

**Comment by rsudev** [comment]
This should now be OK, as the updated translations were imported back three days ago.
