### ISSUE TITLE
WhereYouGo Navigation option not shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6494]
##### Detailed steps causing the problem:
- Have WhereYouGo App intalled
- Load GC383A3
- Select Menu - Navigate

##### Actual behavior after performing these steps:
Navigation option WhereYouGo not shown

##### Expected behavior after performing these steps:
Navigation option should be shown

##### Version of c:geo used:
2017.04.14-NB

##### Is the problem reproducible for you?
Yes, for this particular cache

**Comment by Bananeweizen** [comment]
2 different cartridges are linked (see end of description for the other). And then we don't show a menu.
