### ISSUE TITLE
Rework CI build to recognize all errors

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#6496]
Currently, the CI doesn't run the unit tests. Hence, it doesn't find errors that are covered by the unit tests or that are in the unit tests itself (see https://github.com/cgeo/cgeo/commit/919c415ce9219866549078c7ad89ee19533828e1#commitcomment-21778589). Thus, we should also run the unit tests during CI.

**Comment by pstorch** [comment]
Why is that? They were working.

**Comment by Bananeweizen** [comment]
Actually that is not the problem. Your change _has_ failed to build, but we did not recognize the error. See http://ci.cgeo.org/job/cgeo%20continuous%20integration/1528/console. We are triggering 2 gradle builds as separate commands, and it looks like the error in the first command did not cause the entire build to fail.
