### ISSUE TITLE
Annotate commits with CI result

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#6498]
It would be nice to get check marks on https://github.com/cgeo/cgeo/commits/master for every tested commit (as is done for example on https://github.com/samueltardieu/pathfinding/commits/master).

**Comment by Bananeweizen** [comment]
It looks like you are using Travis, not Jenkins. So the webhook on your repo is something we cannot use by copy and paste, I guess?

**Comment by samueltardieu** [comment]
Probably not (and it has been setup by Travis itself).

**Comment by Bananeweizen** [comment]
I think we just need to add the "Set the github commit status" post build action. But I will wait for the CI server upgrade before testing this...

**Comment by Bananeweizen** [comment]
I've tried both the deprecated and the universal github status post build actions. Although those are the same as in the pull request build job, I don't see any markers. The log states success for the action. So I have no clue what else to check.

**Comment by Lineflyer** [comment]
This is working now. 
The [continuous intetegration job](http://ci.cgeo.org/view/Continous%20integration/job/cgeo%20continuous%20integration/) builds on every commit and the annotation is shown on Github.
