### ISSUE TITLE
Support mails bouncing from gmail.com

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6499]
Recently we are receiving "Message delayed" messages and also "Failed to deliver" messages on support for mail addresses @gmail.com. Not sure if this is our server or the remote site.

AFAIR we had such issues due to cgeo.org listed as "spam site" in the past. @mucek4 can you check in detail what might cause it?

**Comment by mucek4** [comment]
I know. Gmail emails go over my VPS but it died, because of "hardware failure" and I'm still waiting for fix. I'll see what I can do.

**Comment by mucek4** [comment]
@Lineflyer Sending to Gmail is temporary solved.

**Comment by Lineflyer** [comment]
@mucek4 Can we consider this one permanently solved (your wrote temporary above)?

**Comment by mucek4** [comment]
I think it should be permanently solved. Emails now have SPF, DKIM signatures and DMARC policy enabled and are delivered over IPv6
