### ISSUE TITLE
Update Jenkins to the latest released version

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#6500]
We're running an obsolete version of Jenkins. @mucek4, could you update it to the latest version so that we can also update the plugins?

**Comment by mucek4** [comment]
For this I would like to have @Bananeweizen also on board to resolve issues that might pop up after update.

**Comment by mucek4** [comment]
CI has been upgraded, thanks to @Bananeweizen 
If anyone notices anything unusual we still have snapshot of server before upgrade. After couple of days it will be removed.
