### ISSUE TITLE
Logo banners on webserver

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6501]
@mucek4 
Can you provide a list of graphics, that are stored on our webser (like this one: http://www.cgeo.org/content/ad/300_100_normal.png).
I wanted to check which one to use, we could put this a list into our Wiki.

**Comment by mucek4** [comment]
https://github.com/cgeo/cgeo.github.io/tree/master/content/ad

**Comment by Lineflyer** [comment]
Oh...its in the repo...thanks.
