### ISSUE TITLE
Move database to external storage doesn't work

### ISSUE THREAD

**Issue by t0mcat1337** [cgeo/cgeo#6502]
##### Detailed steps causing the problem:
1) Verify with a filesystem explorer app that the hidden folder ".cgeo" exists in the internal storage, holds a current database and one subfolder per cache.
2) Optional: rename folder ".cgeo" to sth. else to make sure C:Geo is really using it (the next start after renaming will be without any stored cache and c:geo will create a new empty DB in a new ".cgeo" - folder in the internal storage). After that, rename the folder again to ".cgeo"; C:Geo starts with the stored caches again.
3) C:Geo Main Menu: Choose Settings / System 
4) Activate Check box "On external storage" under "Database location"
5) The message "Successfully moved the database" appears.
6) Notice that there is no ".cgeo" folder in the external storage ("real" SD Card)
7) Repeat the optional step 2 to notice, c:geo is furthermore using the internal storage.
===> Checking Database "On external storage" seems to have absolutly no effect. Wouldn't it be better to give the possibility for completely choosing a path where to store the database?

A little Background: 
When storing a large number of caches, the .cgeo folder can grow up to several gigabytes which will fill the internal storage

##### Actual behavior after performing these steps:
The database (and subfolders per cache) remains in the internal storage

##### Expected behavior after performing these steps:
The datbase (and subfolders per cache) should be on the external storage

##### Version of c:geo used:
2017.03.29

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-G900F (cm_klte, samsung)
Android version: 6.0.1
Android build: cm_klte-userdebug 6.0.1 MOB30Z dd924bc6e0 test-keys
Cgeo version: 2017.03.29
Google Play services: enabled - 10.2.99 (430-148249840)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE (cgeo forced to English)
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
Reproducable on another device (Samsung Galaxy S3 Mini, Android 4.4, C:geo 2017.03.29)

**Comment by Lineflyer** [comment]
The function you are using (Activate Check box "On external storage" under "Database location") is only moving the database file from a system internal location (where you cannot even see it without root) into the user storage, but not to an external SD card (on your Android version).
The wording within the c:geo settings might be not the best (as it was made for older Android versions).

Also you are mixing up the database with the additional geocache data.
You can find a basic explanation [here](http://faq.cgeo.org/#data-on-sd)

The usage of an real external SD card is not yet in our productive version.
But don't worry, we are working on it and with our next feature release this will be possible.

If you want to try it, you can use our nightly versions as described [here](http://www.cgeo.org/development.html)

**Comment by Lineflyer** [comment]
Not to forget:
It would be highly appreciated if you try out the nightly version and report back about your experience.

**Comment by pstorch** [comment]
We are actually working on the local storage at the moment. With the current Nightly your can move the geocache data (images, static maps...) to a "real" external SD card. But we decided to not support moving the sqlite DB there. The DB can only be moved to the emulated external storage if available.
