### ISSUE TITLE
Progress bar while importing PQ shows no progress

### ISSUE THREAD

**Issue by Cappa-d** [cgeo/cgeo#6504]
##### Detailed steps causing the problem:
- Open Pocket query menu
- Pocket Query list is loaded
- Select PQ created today (6 more days available)
- Press the Save icon
- Select list for import
- Loading screen appears

##### Actual behavior after performing these steps:

Loading screen remains at 0% while there is no progress shown and the PQ is rather small -- 49 entries only events -- this worked before
Update -- it seems that the PQ is loaded. However the progress screen never finishes or updates itself. This morning it got stuck at 9%

##### Expected behavior after performing these steps:

Complete load of PQ and end with success message

##### Version of c:geo used:

2017.04.19-NB-e90f5e1

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-G935F (hero2ltexx, samsung)
Android version: 7.0
Android build: NRD90M.G935FXXU1DQB3
Cgeo version: 2017.04.19-NB-e90f5e1
Google Play services: enabled - 10.2.98 (440-146496160)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: yes
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed cgeo plugins: contacts
--- End of system information ---
```

##### Other comments and remarks:
I am using the NB at the moment due to the testing of the move of the cache data to the real SD card. This download and update worked before...

**Comment by SammysHP** [comment]
I'm not sure what you are doing after "Select PQ created today (6 more days available)" because c:geo cannot download pocket queries directly, only show their contents.

**Comment by Cappa-d** [comment]
@SammysHP : I have updated the description and tried with todays NB -- same behaviour. Funny enough it still saves the PQ entries as intended.. 

I have the Debug-Log activated. Any sense to post this?

**Comment by Lineflyer** [comment]
> I'm not sure what you are doing after "Select PQ created today (6 more days available)" because c:geo cannot download pocket queries directly, only show their contents.

You are wrong. c:geo can import those since some months.

BTW: For me I do not have any problem. The PQs are imported (this is done via the normal GPX import function within c:geo) with correct progress indication.

**Comment by Lineflyer** [comment]
@Cappa-d Is there anything special with the PQ (e.g. special characters in PQ name)?
Can you provide us the PQs GPX (download from website)?

**Comment by Lineflyer** [comment]
> I have the Debug-Log activated since I switched to test the new Data structure. Any sense to post this?

Yes, please, if you have the tools to retrieve it from the device.

**Comment by SammysHP** [comment]
@Lineflyer 
Sorry, I tested it but forgot that there was no PQ ready for download and thus the button was missing.

**Comment by Cappa-d** [comment]
@Lineflyer I will check later at home. I think it should be possible. Just for my own convenience: Which path should I follow to find the log?

Regarding the PQs: I have not changed them in months and they were working... However I attached three  examples...
[16627771_Ger - Ghost & Cam.zip](https://github.com/cgeo/cgeo/files/942742/16627771_Ger.-.Ghost.Cam.zip)
[13153819_FT--andere.zip](https://github.com/cgeo/cgeo/files/942728/13153819_FT--andere.zip)
[15772708_FT--Events.zip](https://github.com/cgeo/cgeo/files/942730/15772708_FT--Events.zip)

**Comment by pstorch** [comment]
I could reproduce with the given PQs. Can't see anything obvious in the logs. Strange.

**Comment by Cappa-d** [comment]
I will try to retrieve the logs later..... 

Strange enough there is no change in the setting of the PQs for months

**Comment by mirabilos** [comment]
After upgrading from NB 2017-04-12 to 2017-04-21 this happens to me too.

**Comment by pstorch** [comment]
Looks like e3e6753 is causing this. I've tried with GPXImporter from a6b204e which is working.
@UniQP any idea?

**Comment by Lineflyer** [comment]
Oh yes. Now I can reproduce. My nightly was older than the mentioned commit.

**Comment by Cappa-d** [comment]
@Lineflyer ok trying to retrieve the log... is it the data-journal or which path should I check

**Comment by SammysHP** [comment]
@Cappa-d You have to use ADB but as we are able to reproduce it your log is not necessary anymore.

**Comment by UniQP** [comment]
@pstorch The `ImportStepHandler` causes the problem. If the importer finishes normally and gets garbage collected, we will not execute https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/files/GPXImporter.java#L230 anymore.

I will try to create a fix tomorrow.

**Comment by Bananeweizen** [comment]
@UniQP be aware that the fix should target the release branch now, since branches have been re-targeted in #6483.

**Comment by mirabilos** [comment]
I can confirm this is fixed now. Thanks!
