### ISSUE TITLE
remove/merge themes v11

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6506]
There is one task left from the upgrade to minsdk 14. We still have a themes definition underneath res/values-v11. To my understanding this can simply be deleted, since it will never get evaluated on any device anymore, right? Or are there any values, which need to be moved to our standard themes.xml?

**Comment by Lineflyer** [comment]
If no one knows, whether those old themes are used, I suggest we try it out on `master`. We have just merged to `release`, which offers a bit of time to fix.
