### ISSUE TITLE
update emulator of sam-2

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6507]
> Your emulator is out of date, please update by launching Android Studio

http://ci.cgeo.org/job/cgeo%20continuous%20integration%20(pipeline,%20experimental)/2/consoleFull

The pipeline based job will mark such executions with a warning in the future.

**Comment by samueltardieu** [comment]
I have restarted both my slaves from a fresh docker image. If they are not up-to-date, then we'll have to update the docker source and restart the slaves.

**Comment by Bananeweizen** [comment]
In that case I assume the docker image _is_ up-to-date, since your other slave did not show that message already before the restart.

**Comment by Bananeweizen** [comment]
reopening, since sam-2 still produces the same message.
http://ci.cgeo.org/job/cgeo%20continuous%20integration%20(experimental)/7/

**Comment by samueltardieu** [comment]
Looks better: http://ci.cgeo.org/job/cgeo%20continuous%20integration%20(experimental)/11/
