### ISSUE TITLE
Non working link in oc caches

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6509]
Load OC10406 or any other safari cache. All hyperlinks in the cache description are working, except for the 'Suche' link.

**Comment by Bananeweizen** [comment]
This is only reproducable, if the cache is imported from GPX. The link in question is relative (without base URL), and it seems we make it absolute on importing from OKAPI, but not when importing from GPX.

**Comment by mirabilos** [comment]
• report this as bug to OC? ;-)

**Comment by Bananeweizen** [comment]
@mirabilos Nope. This is cache content, not platform output. Cache owners totally don't like if their cache description is updated by the platform team, not even for fixing issues. There has been such a thing not long ago, and that caused huge discussions.

**Comment by mirabilos** [comment]
Michael Keppler dixit:

>@mirabilos Nope. This is cache content, not platform output.

Oh, okay then. This read as "all OC caches have one non-working link" to me, but if it isn't so, it's definitely the cache owner's fault.

**Comment by Bananeweizen** [comment]
This applies to all safari caches, which have been created using a template contained in the OC wiki (at maximum ~800 caches). That template was unfortunately using a relative link. So cache owners were not doing anything wrong, nevertheless they would have to change it now. A bit of a curious situation...

**Comment by MacGyver-NRW** [comment]
> perform a database query that corrects the problem (server side).
Oh - we had have a bad expierience with this way ;)
There is a database trigger which changed "last modified date".

We get now notice of this ticket and see what kind of solution will be possible offered.

**Comment by andrixnet** [comment]
@MacGyver-NRW : consider these steps: 
- use a development copy of the site (and database) to develop the exact query required
- put the site in maintenance mode
- disable (or remove) the trigger
- perform query
- enable (or add back) the trigger
- return site to normal operations. 

with the query prepared, shouldn't take more then a few minutes to perform the actual repairs, so downtime would be minimal, and `last_modified_date` will not be affected.
