### ISSUE TITLE
OSM:Cyclemap requires API key

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6512]
##### Detailed steps causing the problem:
- Use live map with OSM:Bikemap (or whatever it is called in english)

##### Actual behavior after performing these steps:
Tiles have a text overlay API key required

##### Expected behavior after performing these steps:
No warning like this

##### Version of c:geo used:
2017.03.29

##### Is the problem reproducible for you?
Yes

**Comment by SammysHP** [comment]
I think we have to remove that layer. Just too expensive. Also I doubt that we are allowed to share the key with other developers.

http://www.thunderforest.com/pricing/

**Comment by SammysHP** [comment]
Conclusion from IRC:

- Sign up for the free plan (150,000 tiles/month): https://manage.thunderforest.com/users/sign_up?plan_id=5 (note that there is no license agreement)
- Hardcode the key in the tile layer URL
- If the limit is reached we will remove the layer

**Comment by Lineflyer** [comment]
Please implement changes for this on `release` as there the "time to market" will be shorter.

**Comment by Lineflyer** [comment]
Added FAQ entry for the time being.

**Comment by Lineflyer** [comment]
Please do also think about `cgeo-legacy` when fixing this.

**Comment by Lineflyer** [comment]
BTW after reading the terms:
Do we have their copyright somewhere in "About c:geo"

**Comment by SammysHP** [comment]
#6150

**Comment by pstorch** [comment]
I'm not an expert in the map code, but I'll have a look here.

**Comment by Lineflyer** [comment]
@pstorch My testing shows that it is fixed on "normal" OSM as well as "beta" OSM. Correct?

Still I reopen as I want to suggest to implement the change also to `cgeo-legacy` branch.

**Comment by pstorch** [comment]
@Lineflyer right, it's fixed in mapsforge v3 and the new v6 (beta). Not yet on `cgeo-legacy`. I'll try to cherry-pick it.

**Comment by pstorch** [comment]
Looks like CI can't build the `cgeo-legacy`. 

```
 /home/jenkins/slave/workspace/cgeo continuous integration/main/build/intermediates/res/merged/basic/debug/values/values.xml:2038: error: Error: No resource type specified (at 'thunderforest_api_key' with value '@thunderforest.api.key@').
```
@kumy @samueltardieu is the `private.properties` needed on `sam-2`?

**Comment by kumy** [comment]
Does it means an Thunderforest api key is now necessary to build the code?

**Comment by pstorch** [comment]
Don't know, I just see this error in the build log: http://ci.cgeo.org/job/cgeo%20continuous%20integration/1573/console

But there is another error below, something with aapt. Don't know if they correlate.

**Comment by kumy** [comment]
From https://github.com/cgeo/cgeo#api-keys
> Copy main/templates/keys.xml to main/res/values/. Then edit main/res/values/keys.xml and insert several keys (see comments in the file). Most important is the Google Maps API v1 key. You can leave it empty, but then Google Maps doesn't work. Google doesn't hand out new keys for Google Maps v1, you have to use an existing one.

I suppose there is an _internal build system_ that replace @key@ in `main/res/values/keys.xml` based on values from `private.properties`. So IMHO @samueltardieu should add _at least_ an empty `thunderforest.api.key=` in `private.properties`...

**Comment by SammysHP** [comment]
The last time I worked in that area only available keys might be added to private.properties. If an entry is missing, it will be empty. Gradle should process the file only if keys.xml is missing (in case someone modified it by hand).

**Comment by Bananeweizen** [comment]
You need to have every key _defined_ in your keys.xml. You can leave the value as empty string, but it must exist. This is the same for every other key, since the Android resource compiler will otherwise fail.

**Comment by SammysHP** [comment]
That cannot be true. I made a fresh clone of the repository and added a private.properties file with the following content:

```
maps.api.key=*****
maps.api.key.market=*****

thunderforest.api.key=*****

ocde.okapi.consumer.key=*****
ocde.okapi.consumer.secret=*****

key.store=*****
key.alias=*****
key.store.password=*****
key.alias.password=*****
```

Then I ran gradle and it created the following keys.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">
    <!-- Google Maps -->
    <string name="maps_api_key" translatable="false">*****</string>

    <!-- Thunderforest OpenCycleMap -->
    <string name="thunderforest_api_key" translatable="false">*****</string>

    <!-- Opencaching.de -->
    <string name="oc_de_okapi_consumer_key" translatable="false">*****</string>
    <string name="oc_de_okapi_consumer_secret" translatable="false">*****</string>

    <!-- Opencaching.pl -->
    <string name="oc_pl_okapi_consumer_key" translatable="false"></string>
    <string name="oc_pl_okapi_consumer_secret" translatable="false"></string>

    <!-- Opencaching.us -->
    <string name="oc_us_okapi_consumer_key" translatable="false"></string>
    <string name="oc_us_okapi_consumer_secret" translatable="false"></string>

    <!-- Opencaching.nl -->
    <string name="oc_nl_okapi_consumer_key" translatable="false"></string>
    <string name="oc_nl_okapi_consumer_secret" translatable="false"></string>

    <!-- Opencaching.ro -->
    <string name="oc_ro_okapi_consumer_key" translatable="false"></string>
    <string name="oc_ro_okapi_consumer_secret" translatable="false"></string>

    <!-- Opencache.uk -->
    <string name="oc_uk2_okapi_consumer_key" translatable="false"></string>
    <string name="oc_uk2_okapi_consumer_secret" translatable="false"></string>
</resources>
```

**Comment by pstorch** [comment]
Can I manually start the `cgeo legacy` build on CI? It's a parameterized build. Not that I accidentially perform an upload or something.

**Comment by Bananeweizen** [comment]
It unconditionally uploads the APK to the server, so I would NOT run that job for anything else than trying to really create a new productive legacy version. You should be able to check the job configuration after logging in to jenkins. If not, ping me again to make that work for you.

**Comment by Lineflyer** [comment]
I will take care of building and testing legacy regarding this fix.

**Comment by Lineflyer** [comment]
Tested and working on legacy build based on branch as of today.
