### ISSUE TITLE
Make map circle preference permanent

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#6518]
##### Problem:
Users who like the circles on their map need to manually enable them every time when opening the map.

##### Comments:
- Unlike other preferences in the pop-up menu on the map activity, like direction line to cache, trail log on the map, show/hide deactivated/found/owned caches, this single preference is not permanent
- Map circles are probably not as widely used as the other preferences and additionally not expected to be permanent.

##### Suggested Implementation:
- Add a setting in the map settings menu activity where permanent/non-permanent circles can be enabled, instead of making the pop-up setting permanent.

##### Version of c:geo used:
2017.04.23-RC and before

##### System information:
```
--- System information ---
Device: GT-I9506 (ks01ltexx, samsung)
Android version: 5.0.1
Android build: LRX22C.I9506XXUDPG1
Cgeo version: 2017.04.23-RC
Google Play services: enabled - 10.2.98 (238-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_AT
System date format: dd.MM.yyyy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by jakedot** [comment]
Any updates? In connection with #5885, it might be efficient to consider this as well.

**Comment by moving-bits** [comment]
I implemented storing circle preference, but did it the same way as the other preferences are stored to keep things consistent. (Which means: The circle preference itself gets stored, not the preference whether to make the circle preference persistent.)
