### ISSUE TITLE
Use new logging page

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6519]
In todays [release notes](http://forums.groundspeak.com/GC/index.php?showtopic=344009) Groundspeak announces, that a new logging page is introduced.
You can see in the video on [this page](https://www.geocaching.com/blog/2017/04/test-a-new-logging-experience-is-coming-to-geocaching-com/) that it looks different to the old one.

I tested logging just now with 2017.04.24-NB and had no problem to post logs with and without attached photo. 
However looking into the browser I do still see the "old" logging page on my account...so might be, that the change is not yet live.

We should monitor this.

**Comment by SammysHP** [comment]
> You will still have the option of returning to the old logging page when creating a new log, but encourage you to try out the new page and provide any feedback.

So we have some time to test the new logging page.

**Comment by alan666notb** [comment]
I get the new logging page on the website every time now,
cgeo still seems to log caches OK.

**Comment by Bananeweizen** [comment]
Try logging a field note via browser. That is _different_ since it allows needs maintenance as _additional_ flag instead of as separate log, according to a thread on OC.de

**Comment by steve8x8** [comment]
Had to do exactly this: after performing owner maintenance, I couldn't submit a matching log using c:geo (03.29), had to offline write note instead and upload as field notes. Web page allowed me to change the log type.

**Comment by Lineflyer** [comment]
No need to use field notes to see the new logging page, its live now, e.g.:
https://www.geocaching.com/play/geocache/gc1pqe6/log

We should use this instead of the old one as it might be retired some day.

**Comment by Lineflyer** [comment]
We should look into using this page for logging.
However at the moment I do not see any urgent need, as the new is still under approval and it seems far away from perfect.

**Comment by johan974** [comment]
Hi, 
The good news is that GC provided the 'opt out' way as a workaround. I hope for very long ... 
When investigating the new logging HTTP sequence I saw some elements that looked like Oauth(2). 
* The old logging page points you via HTTP 302/301 redirects to something like. 
   https://www.geocaching.com/play/geocache/gc3brd4/log. Just like Lineflyer indicated. 
* I see that an access_token is needed int the actual post header. 
* Scanning beyond a lot of intermediate HTTP requests, both GET/POST requests are done for the token. 
   GET "https://www.geocaching.com/account/oauth/token". Why do they need so many of these ;-) ? 
* Then the final POST is done with the Authorization: berear ey* (access token). 
   https://www.geocaching.com/api/proxy/web/v1/Geocache/GC4Z041/GeocacheLog. 
   The post body consists of a new set of parameters. The only ones I couldn't match directly were the 
   geocache[id] and the geocache[owner][id] owner. 
* When I tried to isolated these steps in seperate code (just as a try out) I ran into an 401 code. Yep, I must have missed something on the Oauth protocol. 
* Is there an isolated test class that can be used to replay login + select a geocache + log a geocache?

**Comment by Lineflyer** [comment]
I have a maybe stupid question for this:
Do we or don't we expect problems for people using c:geo?
For example I do not have any problems logging caches with c:geo. When I am using the website with my very same account I am redirect to the new log page and did not opt-out.

**Comment by johan974** [comment]
A number of people still get from geocaching.com the old version of logging. ==> No problem. 
If you use the 'opt out' ==> No problem. 
    So if problems arise, the 'opt out' comes to the rescue.  
When scanning the HTTP traffic, the new way of logging is entirely different in HTTP calls and headers. ==> I expect a problem.

**Comment by Lineflyer** [comment]
Oh, I have to correct myself slightly:
On the first try now c:geo failed to load the logging page now (debug lof shows a redirect, whereafter we fail to parse). all subsequent requests however now don't show the redirect but I am able to log.

However this make it for me more urgent to adapt our implementation.

**Comment by Lineflyer** [comment]
> A number of people still get from geocaching.com the old version of logging. 

It has to be another logic (e.g. session based or loadshare based) as sometimes fail with c:geo to load the logging page but most times it is ok.
On the website I do always get the redirect to the new page and I did not opt-out.

**Comment by johan974** [comment]
Your question: How long will the opt-out exist? How long will they support (under water, normally invisibly) the old way of logging? The old-searching is still supported ;-)
My first c:geo logs since 28-04 kept on giving POST-errors. I searched in the messages file: <string name="log_post_not_possible">. That triggered me. I had no internet issues. 
After some time logs were allowed again without errors.

**Comment by johan974** [comment]
The specific message was not put in my previous entry:  string name="log_post_not_possible"

**Comment by johan974** [comment]
I guess GC will use (a version of) Oauth more and more. Do you have seperate tests so we can isolate this and anticipate for the future changes?

**Comment by Lineflyer** [comment]
Log of the failure case:
```
21:51:14.634 Debug cgeo 9285  [OkHttp] GET https://www.geocaching.com/seek/log.aspx?ID=3335150
21:51:17.039 Debug cgeo 9285  [looper callbacks] LocationProvider: stopping location requests
21:51:17.689 Debug cgeo 9285  [OkHttp] 200 (3099 ms) GET https://www.geocaching.com/seek/log.aspx?ID=3335150 (http/1.1) (=> https://www.geocaching.com/play/geocache/gc41q9d/log)
```

**Comment by samueltardieu** [comment]
Post data with the new logging page. The JS probably sends a lot of useless data though:

```
logTextMaxLength=4000
maxImages=1
geocache[id]=1190346
geocache[referenceCode]=GC1PQE6
geocache[postedCoordinates][latitude]=48.351728
geocache[postedCoordinates][longitude]=11.788864
geocache[callerSpecific][favorited]=false
geocache[owner][id]=4028982
geocache[owner][referenceCode]=PR4T193
geocache[geocacheType][id]=2
geocache[geocacheType][name]=Traditional+Cache
geocache[isEvent]=false
logTypes[0][value]=2
logTypes[0][name]=Found+It
logTypes[0][selected]=true
logTypes[1][value]=3
logTypes[1][name]=Didn't+Find+It
logTypes[1][selected]=false
logTypes[2][value]=4
logTypes[2][name]=Write+note
logTypes[2][selected]=false
logType=2
ownerIsViewing=false
logText=Thanks+for+the+cache.
logDate=2017-05-09
isWaiting=true
```

**Comment by Lineflyer** [comment]
```
[23:22] <Lineflyer> BTW: I still see the nice workaround (thats what I guess) gc.com made for us when trying to log a cache. First try to log after a certain time of no usage fails but subsequent tries are ok (as the server falls back to the old logpage and no more redirects to the new one)
```

**Comment by Lineflyer** [comment]
There are now some users on support and FB with the same problem (as described one posting above).
What shall we do?

**Comment by johan974** [comment]
Well, what opportunities do we have? I think buying time because sooner or later the Oauth movement will get stronger within the geocaching.com software. 
Important? I think the logging is a critical success factor of C:GEO. 

What is the time needed to port the logging to the Oauth? 
What is the expected time when more and more components move to the Oauth way of communicating? 

I just switched jobs and need time to catch up, otherwise I would love to work on this.

**Comment by johan974** [comment]
Today I spent a few hours preparing an isolated OkHttp test: from login + getting webpage + getting GPX. I hope to move on tomorrow to log a geocache. The last time I was not able to go 'passed' the Oauth stuff. Eventually I hope to get this working, I can then give the OkHttp test code so an C:GEO experience developer can add parts of the code. Fingers crossed ...

**Comment by johan974** [comment]
**Question**: how can I determine the "geocache[owner][referenceCode]"? 
This is the only info I cannot find.

**Comment by SammysHP** [comment]
base31 encoding of the numeric ID. At least something where Groundspeak is consistent. :)

**Comment by johan974** [comment]
Today I created with OkHttp (used by C:GEO, and NEW for me), an isolated test for sign-in + getting the geocache + loading the GPX + logging!!  OkHttp is really great!
My source code (with only OkHttp) is available for you guys. 
My findings: 
- Get the new logging page. Use the good old gccodeToGcID: 
Get:  https://www.geocaching.com/seek/log.aspx?ID=" +  gccodeToGCId( gcId) + "&lcn=1";
- Get an access token. Strange. Is this a new fuzzy version of Oauth? 
Post: https://www.geocaching.com/account/oauth/token. With an empty post form body. 
- Post the request. I tried also with not sending the "geocache[owner][referenceCode] and it worked!!!
https://www.geocaching.com/api/proxy/web/v1/Geocache/" + gcId + "/GeocacheLog"
The body consists of all the entries shown above by 'samueltardieu'

Yes, it worked. The first time I had an '@' and a date in the log text. I got an 422 error. 

So conclusion - piece of cake for a c:geo developer. I will contact the developers.

**Comment by pstorch** [comment]
@johan974 thanks for your input. Do you want to send a PullRequest with the proposed changes?

**Comment by johan974** [comment]
As suggested, I created a simple Class with method (apart from c:geo) in which I managed to solve the issue. I can send you that source file. It consists of easy OkHttp statement (what you also use). I can mark the specific items and then it is easy for a c:geo developer to use it.

**Comment by pstorch** [comment]
@johan974 was just asking if you wanted to take the opportunity for a contribution. Of course you don't have to. Can you post your example code here in the issue or upload it somewhere and link to it? 

@all do we have to change the logic because the integrated "NM" and "NA" in a found log?

**Comment by johan974** [comment]
Do you have an e-mail address I can post the source file to? That is easiest.

**Comment by johan974** [comment]
OK, added comments to my isolated test file. 
Contributing? Well, I switched jobs, I need to make time for that. 
This was in the mean time so much fun to solve, I couldn't leave the question unanswered.

**Comment by pstorch** [comment]
What about a Gist? https://gist.github.com/

**Comment by SammysHP** [comment]
> @ALL do we have to change the logic because the integrated "NM" and "NA" in a found log?

Yes and no. We could map a NM to "note with NM flag" (this is the only way to log a NM on the website at the moment). But new users might expect the same interface as on the website.

Btw: OC supports such flags as well (not sure about the OKAPI).

**Comment by johan974** [comment]
OK, I added the file with the [new logging](https://gist.github.com/johan974/88e09992b288560db519946ed8faf129.js). 
You can focus on the "New logging" file. The complete listing (with sign-in + get geocache html file + gpx + logging) is also provided for the context.

**Comment by johan974** [comment]
OK, I added the [gist](<script src="https://gist.github.com/johan974/88e09992b288560db519946ed8faf129.js"></script>)

**Comment by johan974** [comment]
When experimenting with the code, I see that sometimes I get a 422 on the post of the log. 
Any ideas why this happens? 
The "write note" is ok. The log may return 422.

**Comment by pstorch** [comment]
Do you log a found on your own cache or several times on the same?

**Comment by johan974** [comment]
Hmm, thank you, nice suggestion. As another user I log on my (owned) geocache. 
I tried a different one and it was ok. 
Intelligent people over there at Seattle HQ ;-)

**Comment by rsudev** [comment]
They changed this just recently

**Comment by johan974** [comment]
Thank you for the answers!

Those at Seattle HQ are having a busy time with all the code changes. 

If you like I can post also some code for MESSAGING. Using both tokens, this is now quite easy.

**Comment by Lineflyer** [comment]
How should we proceed here?
For some other changes server pages Groundspeak meanwhile removed the "return to the old page" option.
It might happen that they do alike for the logging page.
The old page might still exist and be useable though, but that would be the latest time we should have adapted to use the new one to keep c:geo working and not continue using outdated pages to access the server.

**Comment by johan974** [comment]
I did a number of experiments with the new solution, as written above. I use it in my own (private) geocaching app. 
Maybe interesting results for you guys: 
* The first log is working great. 
* The SECOND log results in an javax.net.ssl.SSLException: Read error: ssl=... I/O error during system call, Connection reset by peer
Is it an idea to work together solving this?

**Comment by johan974** [comment]
Other findings: 
* Setting the connection timeout (25s) and read timeout (50s) even to these values, didn't help. 
* Clearing the access token did not help. 
* Only removing the verification-token helped, thus a new login solved the problem. But this is of course not very useful, because many re-logins are needed for logging a batch of geocaches. It slows the logging dramatically down.

**Comment by johan974** [comment]
In normal oauth, there is 1 steady token and the other token is refreshed. Geocaching.com uses another approach. The access token cannot be saved and it should be retrieved each time.

**Comment by johan974** [comment]
OK, I solved this again. So, I you want the code, just let me know. 
CHEERS !!!

**Comment by Lineflyer** [comment]
@johan974 Maybe you could share your code/repot or a gist with your code so that we can later come back to this or use it for inspiration.

**Comment by pstorch** [comment]
@johan974 thanks for the investigation. Is your code example now different to the one provided in your comment from https://github.com/cgeo/cgeo/issues/6519#issuecomment-304434197?
I can try to integrate it in c:geo, if no one else is already on it.

**Comment by johan974** [comment]
HI, yes, it is different. 
Attached you find the logging method(s). 
[logging_basic_version_for_cgeo_devs.txt](https://github.com/cgeo/cgeo/files/1188027/logging_basic_version_for_cgeo_devs.txt)
Enjoy!

**Comment by johan974** [comment]
@pstorch - if you like, you can send me an e-mail jj974@chello.nl so I may have suggestions during coding.

**Comment by pstorch** [comment]
@johan974 I've not started yet, only had a quick look. Maybe we can work on a branch together.

**Comment by johan974** [comment]
Ok, nice meeting you on a branch ;-)
Let me know how I can reach you. 
Well, review is ok. I started looking at the code, it is not easy code.

**Comment by pstorch** [comment]
@johan974 as a first step I copied your code into the `GCParser` class and tried to fix the compile errors. But there are some things missing (e.g. `URL_ACCESS_TOKEN`) and some classes we don't have. 
I haven't touched the `GCParser` much yet, so I'm also not very familiar with it.

In your first step you access the old log page: is this still needed? They will remove it eventually, right?

There is also a (demo) PR #6548 from @samueltardieu where he already implemented some of the new web-api logic. Maybe it's better to go on from there. I'm not sure.

**Comment by johan974** [comment]
Please send me your e-mail or another way to communicate. If you like to communicate via this approach is also possible. I don't see notices. 

Answers to your questions: 
(1) URL_ACCESS_TOKEN = https://www.geocaching.com/account/oauth/token
(2) According to my knowledge, this is just a JWT approach. No real Oauth processing. 
So JWS is JSON Web Token. 
This is not the normal way of Oauth. Via Oauth you get a verification/refresh token first. Then you use this one to get an access token. The access token can be used until it expires. That was my first approach. I stored the access token and wanted to reuse it. To my knowledge you just have to retrieve the access token just before the action you need it. In this case the LOG action. In the browser traffic you see 2 x post + 1 get of the access token. Then that one is used. There may be a difference between the tokens between the first and the second ;-) Often they are the same. 
(3) The old page, you mean https://www.geocaching.com/seek/log.aspx?ID=? This one is needed. I tried to directly go to the new page, but that is not allowed. Via an automatic redirection 302/301 you are directed to that page. OkHttp has automatic redirection so no problem. They will change that in the future. No prob - we can then use that new URL. 

Hope this helps.

**Comment by johan974** [comment]
After this, you will have to add the trackables section. I hardly work with trackables, I will do this exercise maybe some dag. Just follow the browser traffic in developer mode F12.

**Comment by SammysHP** [comment]
@johan974 
Development is public via GitHub. You can contribute by committing to your fork of the c:geo repository. If you want more direct communication you can join our IRC channel #cgeo on freenode. But please note that the IRC channel does not replace the documentation in issues at GitHub.

**Comment by pstorch** [comment]
@johan974 I've recorded a log request and it worked without the first request to the old log page. I'm not sure if this is dependent on the user settings. I've selected to have the new log page as default.
I can see the POST, POST, GET to the auth token url, but it looks a bit strange to me. I've worked with JWT access tokens some time before, but it was a bit different. I need some more time to get familiar with the new log page and its request/response sequence and how to put it into the c:geo codebase.
When I have some time to work on it, I'm also available on the irc cgeo channel. Usually later in the evenings (GMT+1).

**Comment by johan974** [comment]
Great you did the first log! Then the rest is do-able. 
I think it is based on the user setting whether you need the old/new log page. Well, that does it noet making it easier for us. 
Accessing the newer page rightaway is of course better, because it is quicker. Less 302/301. 
Yes, the POST, POST, GET is strange. I hope you can prove a simpler approach, because that will also reduce time for logging. 
Which branch you are on?

**Comment by pstorch** [comment]
@johan974 can you provide the implementation of this method: `geocachingBasicServices.postRequest( finalLogUrl, logFormBody, false, false, accessToken, newLogUrl, "*/*");`?
As long as it doesn't compile, I think it doesn't make sense to push it to a public branch.

**Comment by johan974** [comment]
Please let me know how to contact you. Then it is easier to connect to you. You can find me e.g. via geocaching.com user smuggie. Then I can respond a lot quicker. 
Within the c:geo there is already a postRequest() or similar. Of course you can find mine in the attachment. 
[post_request.txt](https://github.com/cgeo/cgeo/files/1225821/post_request.txt)

**Comment by Lineflyer** [comment]
Just a remark about a behaviour I have seen today on the website:
When using the new logging page it is not possible to send the log for a webcam cache (Type: "webcam photo taken") if there is no picture attachment to the log.

**Comment by Lineflyer** [comment]
Seems to work good:
I would simply say, that I do not see any difference to the old logging (despite the missing log types (#6973 )).
I tested a found log with TB drop and visit without a problem. Will continue testing.

**Comment by Lineflyer** [comment]
For your information:

These were the tests I performed using 2018.04.10-NB1-95bcd43

- [x] Post found log
- [x] Post note log
- [x] Post DNF log
- [x] Assign favorite point
- [x] Upload picture with (found) log
- [x] Visit trackables while logging
- [x] Drop trackables while logging

All tests passed and much faster than before.

Thanks @pstorch for implementation!

**Comment by Lineflyer** [comment]
Logged 18 caches today using 2018.04.15-NB with 16 Found, 2 DNF and 1 Note. Everything OK.
Not any problem foudn up to now...so this is working as expected.
