### ISSUE TITLE
Caches sometimes not added to history if offline-logged from map popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6524]
##### Detailed steps causing the problem:
- Have "One-click offline log" enabled (not sure if this is a precondition)
- Open popup for an unsaved and not previously accessed cache on live map
- Select Menu - Offline log and save a "found" log
- Go to main menu
- Go to "History"

##### Actual behavior after performing these steps:
The cache is not listed in history
When the cache (which was autosaved while performing the log) is opened from the list, you can see, that the state is "Saved log" but the date is missing behind it. Normally it should show e.g. "Saved log (26.04.2017)"

##### Expected behavior after performing these steps:
Caches should be added to history

##### Version of c:geo used:
2017.03.29

##### Is the problem reproducible for you?
No, it sometimes works. 
I have seen this problem recently and also 2 users on support mail came along with it

##### Other comments and remarks:
This is for sure related or same as #4086, which we thought was solved already.

**Comment by pstorch** [comment]
I just tried to reproduce with the current nightly, but I couldn't.
Cache showed up in history and had a proper saved log date.

**Comment by Lineflyer** [comment]
I experienced this problem several times during my danube bike tour.
It is still not reproducible for me (happens only sometimes) and it now also affects saved caches.

My scenario:
- Have caches stored for offline use
- Open the map for a list of saved caches
- a: Log a cache by opening the popup on the map and select "One-click offline log" -> "Found"
- b: Open the cache details from map popup, Select "One-click offline log" -> "Found"

While case b seems to always work (cache is in history) case a sometimes fails (cache does not show up in history).
In the failure case I can see:
- Caches is marked as offline logged on the list, where it is stored
- Cache is not contained in history
- When opening the cache details I can see "Saved Log" as status but the normally appended date is missing.
- When I empty the offline log and log offline again, the status shows "Saved Log (xx.xx.xxxx)" and it is now showing up in the history

**Comment by Lineflyer** [comment]
Today I was out caching:
- Stored the caches I wanted to hunt on a list `_1308`
- Kept the live map running during the hunt and offline logged (one click offline log) some caches from popup and some from cache details after opening them from map

Result:
- 9 caches shown as offline logged in my list `_1308`
- 8 caches shown in history as offline logged
- Cache GC64D91 is missing in history

I did a backup of the DB in this state. Can it be helpful to analyze the problem?

**Comment by Lineflyer** [comment]
Assigned myself for retest.

**Comment by Lineflyer** [comment]
This is still happening on current `master`:

- I had a bunch of stored caches
- I viewed them on the live map 
- When I triggered the "one click offline log" from the map popup without opening the cache details, I do see "Saved log" in the status field, but not the log date, which is normally appended to the status ("saved log (xx.xx.xxxx)"). In that case the specific cache is not listed in the history of logged caches.

Could be linked to #7640

**Comment by jakedot** [comment]
Have you been able to test what happens if you refresh the cache afterwards? IIRC, it will then show up in the history.

**Comment by Lineflyer** [comment]
> Have you been able to test what happens if you refresh the cache afterwards? IIRC, it will then show up in the history.

I did not test refreshing but if you just add the offline log over again from cache details, it will appear in the history.
I am pretty sure its related to an incomplete update to the DB when logging offline from the popup. (see the refered issue above).

**Comment by Lineflyer** [comment]
I have done many caches recently and explicitly used the method described above. No missing caches in history anymore. Lets close.
