### ISSUE TITLE
Delete or move archived caches from a list

### ISSUE THREAD

**Issue by Cappa-d** [cgeo/cgeo#6528]
##### Detailed steps causing the problem:
Not truely a problem but more like a feature request. In the area of events you already have the option to delete past events with a click. Updating my various lists I came across the idea why not have a similar function for archived caches? 

e.g. I have a list with roughly 2200 caches on it. Once I update it some might be archived and therefore are no longer needed on the list / no longer of interest.

##### Actual behavior after performing these steps:
In order to remove archived caches at the moment you have to set a filter to the status archived and delete the resulsts afterwards.

##### Proposed behavior after performing these steps:
After updating the list the context menu should show an option to either move or delete caches with status archived.

##### Remark:
This is just a proposal based on how I handle it. So feel free to decline it if not feasible.

**Comment by Lineflyer** [comment]
IMHO it is feasible. The question is, of we want to include such features as it is already possible by the steps mentioned above. So we would offer a shorter way only and duplicate functions; on the other hand it is more user friendly, than using filtering options first.
I am unsure about this but tend to say,. that more menu options for functions already available via other methods will only clutter our menus.

**Comment by Bananeweizen** [comment]
>  but tend to say,. that more menu options for functions already available via other methods will only clutter our menus.

Same opinion here.

**Comment by FUSSEL4** [comment]
I'm all for new mehtod that will make life easier. To not to clutter our menues, I suggest a re-structuring of the menues using sub-menues.
(Implementing this functionality is not that difficult, I guess.)

**Comment by Lineflyer** [comment]
@FUSSEL4 Before closing this issue(as it seems no majority of the core team for this feature request), can you draft such a restructured menu as you suggest? I cannot imagine a good intuitive structure at the moment....if we have more sub menus it must be very clear structured otherwise it will be even more cluttered/complicated as currently.

**Comment by FUSSEL4** [comment]
@Lineflyer This's my suggestion for a restructured menu for caches lists:
* Sort
* Select mode
* Cashes 
** Refresh all / selected
** Move all / selected
** Copy all / selected
** Remove all / selected 
* Show on map
* Lists
** Create new list
** Remove current list
** Rename current list
** Make list unique
* I/O
** Import
** Export

That way, the main menu contains five items (Sort, Select mode, Cashes, Lists, I/O).

**Comment by Cappa-d** [comment]
Just had a look at @FUSSEL4 idea and I think it is quite a good idea.

I would just add to **Caches** the submenu item **Delete offline-logs** as this seems to be missing right now.

This approach would reduce the # of entries from 11 to just 5 main topics. However it might be a bit tricky for the items: Import, Export and Show on map as these already have sub menus, but I guess this could be doable or?

**Comment by FUSSEL4** [comment]
@Bananeweizen @Lineflyer @Cappa-d Maybe, we separate the re-structuring of the menu and make it a separate PR?

BTW, **Delete past events** will be moved to **Caches** submenu as well.

**Comment by Cappa-d** [comment]
@FUSSEL4 I guess the function I described would only appear if we have a restructuring of the menu beforehand because I take it that right now nobody would want to do it...

Chicken and egg issue ;) 

Maybe we really set this issue on hold and work on a restructuring first :)

@Lineflyer @Bananeweizen What do you think? Am I right?

**Comment by Lineflyer** [comment]
> Maybe we really set this issue on hold and work on a restructuring first :)

IMHO we should indeed optimize the menu structure first.
That restructuring however should not be the the green card for adding a lot mor functions to those menus, still it makes sense to anyhow make a new structure in beforehand.

So @FUSSEL4 I would ask you to take your menu proposal to a new issue, so that we do not miy up the topics here.

**Comment by FUSSEL4** [comment]
@Cappa-d @Lineflyer I created a new issue for restructuring the cache list menu: [#6546](https://github.com/cgeo/cgeo/issues/6546).

**Comment by FUSSEL4** [comment]
@Cappa-d @Lineflyer I opened a PR concerning the restructuring of the menu: See https://github.com/cgeo/cgeo/pull/6551

**Comment by Lineflyer** [comment]
> >  but tend to say,. that more menu options for functions already available via other methods will only clutter our menus.

> Same opinion here.

Coming back to this.
No as we have a more clear menu structure, I would look forward for such a convience function placed in the correct sub menu ("Manage caches").

**Comment by jakedot** [comment]
Is this issue still unresolved?

**Comment by Lineflyer** [comment]
Yes it is. But as mentioned in the initial posting there is a structured way to achieve this alreay.
Therefore I will close this for now as the originally there was no majority for having just another dedicated shortcut function for this seemingly rare usecase.
