### ISSUE TITLE
Event lists can become very slow

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#6530]
Version: 2017.04.28-NB-e001def
Severity: important
Justification: serious user performance degradation

After upgrading to an NB with the new data format, I observe that newly created lists (e.g. from PQ import) are **very** slow to load, whereas older pre-existing lists (even with _more_ caches in them) load almost instantly.

The difference is notable even on a modern device (Note 4 “trltexx”); old lists are there in the blink of an eye, new lists (169 caches!) take about **three seconds** to display.

**Comment by pstorch** [comment]
That sounds strange. We don't distinguish between lists and haven't changed the db schema. So all lists should be equally fast/slow. 
Can you tell a bit about where your database is (Setting extSdCard) and the Geocache data directory? 
If you like you can send me your db file for analysis.

**Comment by mirabilos** [comment]
```
--- System information ---
Device: SM-N910F (cm_trltexx, samsung)
Android version: 5.1.1
Android build: cm_trltexx-userdebug 5.1.1 LMY49H 60258113f3 test-keys
Cgeo version: 2017.04.28-NB-e001def
Google Play services: enabled - 10.2.98 (230-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   opencaching.de: Logged in (Login OK)
Geocaching.com date format: yyyy-MM-dd
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
btw: we could add the active geocache data dir to the sysinfo


Von meinem Smartphone gesendet.
null

**Comment by mirabilos** [comment]
No idea about the setting. The data directory is `/storage/emulated/0/Android/data/cgeo.geocaching/files` on the internal storage (the device has neither a µSD card nor a SIM card).

Where on the device *is* the database file, anyway? The directory only contains a subdir per cache, or so, and the System settings item in c:geo only has a checkbox “On user storage” (not ticked), no location information.

If I should send anything anywhere, do tell me an eMail address ☺

**Comment by pstorch** [comment]
> btw: we could add the active geocache data dir to the sysinfo

I just thought the same. Good idea.

**Comment by pstorch** [comment]
> Where on the device is the database file, anyway? The directory only contains a subdir per cache, or so, and the System settings item in c:geo only has a checkbox “On user storage” (not ticked), no location information.
> 
> If I should send anything anywhere, do tell me an eMail address ☺

Mail to support@cgeo.org. 
Do you have checked the option: Settings / System / Database / On User Storage? 
If not it is on the internal system storage. Simply make a backup: Settings / System / Backup
Then you see where the backup file is located.

**Comment by mirabilos** [comment]
OK, I’ve created a backup, transferred it (via vx.connectbot SSH) to the desktop, compressed and mailed it.

**Comment by SammysHP** [comment]
> Where in the filesystem is the “internal system storage” anyway?

`/data/data/cgeo.geocaching`

**Comment by Lineflyer** [comment]
DB forwarded to @pstorch

**Comment by pstorch** [comment]
@mirabilos you are talking about the CITO list with 169 Event-Caches, right?
It looks like the sorting is the problem here. If a list contains only Event-Caches, c:geo sorts by event date by default. The `EventDateComparator` takes long because it parses all cache descriptions to "guess" the event time (it calls the method `guessEventTimeMinutes()`). 
You can see the effect when you change the sorting of the list or store one Non-Event-Cache in that list, then another sorting is used.

I think we should change the title of this issue and work on optimizing this one method. Or implement some sort of caching of this expensive calculation.

**Comment by Lineflyer** [comment]
Thanks for analyzing. I will rename topic accordingly.

**Comment by mirabilos** [comment]
Peter Storch dixit:

>@mirabilos you are talking about the CITO list with 169 Event-Caches, right?

Indeed.

>It looks like the sorting is the problem here. If a list contains only
>Event-Caches, c:geo sorts by event date by default. The
>`EventDateComparator` takes long because it parses all cache
>descriptions to "guess" the event time (it calls the method
>`guessEventTimeMinutes()`).

Aaaaaaaaah!

So, not only is the sorting totally off from what I wanted
by default, but also the cause of the slowness. Phew, ok,
I read something about new database format in the issue about
the import progress bar and feared this could have been the
cause.

Where can I change the default sort for such lists, or for
one individual list? (I can see this being useful, having
a "calendar" list, but not in my case here... although the
week's passed and I removed the list already.)

>You can see the effect when you change the sorting of the list or
>store one Non-Event-Cache in that list, then another sorting is used.

OK, interesting.

>I think we should change the title of this issue and work on
>optimizing this one method. Or implement some sort of caching of this
>expensive calculation.

This sounds like an idea. Thanks!

**Comment by Lineflyer** [comment]
> Where can I change the default sort for such lists, or for one individual list? 

This is defaulted by c:geo automatically if the list does only contain event caches.
There is no option to change it.

**Comment by Lineflyer** [comment]
> The EventDateComparator takes long because it parses all cache descriptions to "guess" the event time (it calls the method guessEventTimeMinutes()).

@pstorch @Bananeweizen 
I know the event time guess is needed for adding event caches to the calendar, but for sorting the list it seem to be sufficient to sort by date. This could implicitly solve the issue here, or not?

**Comment by UniQP** [comment]
At least, the EventDateComparator can compare the date first and only call `guessEventTimeMinutes` if the dates are equal.

**Comment by pstorch** [comment]
In this special case the list contains 169 Events spread around 3 days only. So a third of them is on the same day. 
I don't know how common this situation is.

**Comment by mirabilos** [comment]
Peter Storch dixit:

>In this special case the list contains 169 Events spread around 3 days
>only. So a third of them is on the same day. I don't know how common
>this situation is.

The list originally had 500 events spread around a week.
This occurs about twice a year ;) although, for this particular purpose,
I’ll just throw in a non-event cache, as I wish for distance sort on
that list.

Not sure how common this is for others.

**Comment by Lineflyer** [comment]
> In this special case the list contains 169 Events spread around 3 days only. 

Maybe I don't understand the sorting algorithm in this case.
Does it make any difference if they are in a short period/on the same day for the speed of sorting. I thought it is about of the events in the list only.

**Comment by MichielK** [comment]
My apologies for the 2 commits (didn't think commits on my fork would show up here).

I had some spare time at my job, so I took the liberty of fixing this issue (wanted some renewed experience with Android-development ;-) ).

**Comment by pstorch** [comment]
@MichielK you're welcome ;)
