### ISSUE TITLE
Add storage settings to system information

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6531]
The system information should show the used storage directories:
- db directory 
- geocache data directory 
- public cgeo user storage 

Maybe including space left.

**Comment by Bananeweizen** [comment]
Maybe not just the absolute paths, but also what kind of setting was chosen. The naming scheme has changed multiple times over different Android versions (and maybe even customized by some manufacturers). I myself am not able anymore to tell that the SD card path on my device _is_ an SD card (just by its rather name).
