### ISSUE TITLE
Use abbreviation for login status

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6532]
Use GC, OC.de or similar in the main screen login status. For me, that status is never completely visible with the German translation.

**Comment by Bananeweizen** [comment]
Actually, it might be even better to
* not show any connector name, if only one is active
* show an abbreviation of the connector name, if multiple are active.

**Comment by Lineflyer** [comment]
+1 from my side for abbreviations like (gc.com oc.*) or even better without `.` in order not to have it look like an URL.  
I would not leave it out if only one connector is active...mainly for consistency reason. It is more logical to always have it look the same.
