### ISSUE TITLE
Introducing c:geo to new users - a fair playground

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6539]
When c:geo is freshly installed on a device and first run, it presents several suggestions about it's functions. 

One such suggestion is suggesting by default to configure your geocaching.com account.
And here comes the marketing and and P.R. problem. 

Assume one tries to introduce a new user to c:geo as an app for an opencaching service. 
Instead of having to enter (for the first time) the settings -> services menu and choosing the appropriate service, c:geo by default pushes the geocaching.com service in front. 
Now I have a BIG marketing and P.R. setback because I have to give additional explanations (some confuse the new user) about other services. 
I don't mean to exclude or prevent the user from ever accessing other services, but still. 

Just try to imagine: you are tasked with marketing Pepsi to others. When you talk to them, you pull a can out of your bag. And it's a Coca Cola. 
Ok... they are both "cola" soft drinks. But you have made a fool of yourself and in the best case have a lot of explaining to do to catch up.

Well, yes, most of c:geo users indeed are geocaching.com users. 
Still, for an open-source app, that has no affiliation and obligations (does it?) toward Groundpspeak, that offers geocaching features from many different services, doesn't seem fair, nor independent.

**Comment by Lineflyer** [comment]
That problem is quite known to the team. In fact (as can also be seen in other issues) we are open to have a new good first start experience. Feel free to contribute such code to have a better first use experience. I would greatly appreciate that.

**Comment by Lineflyer** [comment]
let us please follow up here: https://github.com/cgeo/cgeo/issues/4263

**Comment by Lineflyer** [comment]
And #5927

**Comment by andrixnet** [comment]
**Currently the very first screen shown to the user when starting c:geo for the first time:**

![screenshot_2017-05-10-08-54-13](https://cloud.githubusercontent.com/assets/3382777/25887207/bd61dba0-3569-11e7-8996-d4bbf5ac83ce.png)
