### ISSUE TITLE
remove useless log image captions

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6542]
Recent log images created with the original GC app have a standard caption "Created with ... bla bla". I intend to remove that during parsing, since it has completely no value for the user.

Example log: https://coord.info/GLQVK1TX

**Comment by ControlTheBit** [comment]
@Bananeweizen I don't think it is enough to check for "Image uploaded from". I found a log entry that has a different start and was also uploaded using the official app. Example here: https://coord.info/GLPYRJT1

I am also not sure if this solution works for all languages. I don't know it e.g. the German version of the app writes something like "Hochgeladen mit der offiziellen..." or something like that.

Maybe it is enough if the description is checked for the appearance of "Geocaching® App".

**Comment by Lineflyer** [comment]
Although I get the point of this, I do think that we should not "randomly" remove some information. Who knows if some of the c:geo users are interested to see the source of other users images.

**Comment by Bananeweizen** [comment]
Nobody. But I know of the exact opposite interest. Please let us talk more about real user needs instead of hypothetical user needs. Otherwise we want get forward at all, since every changed line of code might lead to some users being offended by how the app behaviour changed.
