### ISSUE TITLE
Localization for chinese

### ISSUE THREAD

**Issue by cr-ziji** [cgeo/cgeo#6544]
##### Detailed steps causing the problem:
There are more and more player in China. cgeo is the best app on Android. I'd like to contribute to make a localization version for Chinese. I'll try to gather more player to make sure the translate is good enough for understanding.

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by SammysHP** [comment]
I'm not really familiar with the Chinese language. Do you want simplified or traditional?

**Comment by cr-ziji** [comment]
Normally, there are simplified, traditional HongKong and traditional Taiwan. I'd like to add simplified first. Then, other two later.

**Comment by SammysHP** [comment]
I've enabled simplified Chinese for translation. All translations are done via Crowdin. You can start here: https://crowdin.com/project/cgeo/zh-CN

**Comment by cr-ziji** [comment]
OK. Thanks

**Comment by Lineflyer** [comment]
@cr-ziji In addition you may also provide a translation for the PlayStore description by editing this page (as the description iy not yet contained in Crowdin).
Just edit the page and add the chinese translation at the end.

https://github.com/cgeo/cgeo/wiki/App-description-for-PlayStore

**Comment by cr-ziji** [comment]
ok. I'll translate it and update the webpage later.

**Comment by Lineflyer** [comment]
Let me reopen this, to track the further process:
- [ ] Once translation is done on Crowdin we need to implement the new language into the code itself
- [ ] Once translation is done for PlayStore description we need to add it to Google Play.

**Comment by Lineflyer** [comment]
Will be tracked in #3644.
