### ISSUE TITLE
Compass on Samsung Galaxy S6 fails to rotate after Android 7 update

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6550]
Placeholder (to be completed with more details from support mail).

**Comment by Lineflyer** [comment]
More details. We have currently two users with this problem:

After upgrading their Samsung Galaxy S6 device to Android 7 the compass in c:geo either does not move at all or moves very slowly (report by user: After direction change of 45° it takes the compass one minute to catch up).
On of the users also reported, that the direction arrow on map has the same behaviour (either stuck or turning very slowly).

Both users tried the menu options to use orientation sensor as well as disabled Google Play Service usage without any effect.
Both users confirmed the compass is working normal in other apps like Google Maps and GPS Status & Toolbox.

System info:
```
--- System information ---
Device: SM-G920F (zerofltexx, samsung)
Android version: 7.0
Android build: NRD90M.G920FXXU5EQB9
Cgeo version: 2017.03.29
Google Play services: enabled - 10.2.98 (440-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: d. M. yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

```
-- System information ---
Device: SM-G920F (zerofltexx, samsung)
Android version: 7.0
Android build: NRD90M.G920FXXU5EQBG
Cgeo version: 2017.03.29
Google Play services: enabled - 10.2.98 (440-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd.MMM.yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Any help or steps we could take to debug this?

**Comment by murdok80** [comment]
I have the same problem with my s6.

**Comment by pstorch** [comment]
Found this:
https://geoclub.de/forum/viewtopic.php?f=114&t=79690&start=20

```
Die Funktion "mSensor = mSensorManager.getDefaultSensor(Sensor.TYPE_ORIENTATION);" Gibt es anscheinend nicht mehr!
Da muss ich erst nachlesen, wie man es jetzt machen soll!
```

We are using `Sensor.TYPE_ORIENTATION`.

**Comment by UniQP** [comment]
Nice catch. I found this blog post: http://www.codingforandroid.com/2011/01/using-orientation-sensors-simple.html

**Comment by samueltardieu** [comment]
@pstorch Strange, we use it only if it is reported as being present (and according to the system information it looks like it is).

**Comment by Lineflyer** [comment]
@samueltardieu Do we update the capabilities regularly (e.g. on startup) or do we keep them stored, in which case they might become invalid after major version upgrade of Android?

**Comment by murdok80** [comment]
Since the Update to Android 7 on my galaxy s6 i have problems with the compass at c:geo. The compass rotate verry verry slowly or it didnt rotate. Is there a fix for this problem.

**Comment by Lineflyer** [comment]
@murdok80 As you can read in the thread above we just found some clues about what the problem with Samsung S6 is. Once we have a fix this will be in this issue and the issue closed once fixed.

**Comment by murdok80** [comment]
Sorry for my bad english. Where can i download this fix?

**Comment by Lineflyer** [comment]
@murdok80 There is nothing to download yet. Once we implement a solution you will see an update in this issue. Please stay tuned.

**Comment by murdok80** [comment]
You mean i will be wait for a update in google play store?

**Comment by Lineflyer** [comment]
Once we have a fix I will inform you and probably provide you a test version if you like! We do not have any S6 for testing it ourselves, so your help would be welcome.

**Comment by murdok80** [comment]
Ok. I you have a test version i will test it.

**Comment by Lineflyer** [comment]
@samueltardieu Beside my last question above another question would be: IMHO we do by default not use the orientation sensor unless explicitly selected in settings/system by the user. Correct?

**Comment by pstorch** [comment]
Just looking into it a bit. To answern @Lineflyer s question: yes, c:geo only uses the deprecated OrientationSensor unless explicitly selected in settings/system.

But as reported in the issue description changing this had no impact?

Actually we have three Sensor types for the Compass:
```
        if (Settings.useOrientationSensor(application)) {
            sensorDirectionObservable = OrientationProvider.create(application);
        } else if (RotationProvider.hasRotationSensor(application)) {
            sensorDirectionObservable = RotationProvider.create(application);
        } else {
            sensorDirectionObservable = MagnetometerAndAccelerometerProvider.create(application);
        }
```

According to the Systeminformation in the issue description one user is using the deprecated Orientation Sensor, the other one is using the Rotation Vector Sensor (which is a combination of Accelerometer, Magnetometer, AND (when present) Gyroscope, according to https://source.android.com/devices/sensors/sensor-types#composite_sensor_types).

Should we try to increase the sensor updates with `SensorManager.SENSOR_DELAY_GAME`?

**Comment by pstorch** [comment]
For the affected Samsung users: can you try to open the device selftest page by calling `*#0*#` and try to calibrate the magnetic sensor? Does it have any effect?

**Comment by murdok80** [comment]
Yes i can do this but it has no effect. The compass is blue and signs 3.
This means the compass is well callibratet.
Am 11.06.2017 22:47 schrieb "Peter Storch" <notifications@github.com>:
>
> For the affected Samsung users: can you try to open the device selftest
page by calling *#0*# and try to calibrate the magnetic sensor? Does it
have any effect?

**Comment by pstorch** [comment]
@murdok80 thanks for trying

**Comment by murdok80** [comment]
Since a few days the compass from my s6 in combination with cgeo works. I
didnt understand it.
Am 11.06.2017 22:51 schrieb "Peter Storch" <notifications@github.com>:

**Comment by pstorch** [comment]
@murdok80 any system updates from samsung in between?

**Comment by murdok80** [comment]
No nothing.
Am 11.06.2017 22:55 schrieb "Peter Storch" <notifications@github.com>:

**Comment by VeseliMimoni** [comment]
Hello, I still have this issue. I tried all options in c:geo and also calibrated sensor. I'm happy to test any version on my S6. Let me know.

**Comment by pstorch** [comment]
@VeseliMimoni can you also provide your c:geo System information?

**Comment by VeseliMimoni** [comment]
just uploaded dump to: http://leteckaposta.cz/645388006
let me know if this is what you are looking for, if not, please let me know.

**Comment by pstorch** [comment]
No, I mean in the App under Menu About and then the Tab System.

**Comment by VeseliMimoni** [comment]
--- System information ---
Device: SM-G920F (zerofltexx, samsung)
Android version: 7.0
Android build: NRD90M.G920FXXU5EQCS
c:geo version: 2017.05.22
Google Play services: disabled - 11.0.55 (440-156917137)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: fast
HW acceleration: enabled (default state)
System language: cs_CZ
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (760,4 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (740,4 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (740,4 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (2,9 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
Geocaching.com date format: d.M.yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by murdok80** [comment]
Hello the compass error on my s6 ist the same.
I have installed the gps toolbox for radar in cgeo.
I marked a cache an navigate with the radar from gps toolbox. The radar stop or spin verry slow. If i close cgeo with system tab
, the radar works fine and i can navigate to the cache. Please make a fix for this issue.

**Comment by pstorch** [comment]
@murdok80 haven't you reported a few comments above that it's working again? Does it mean it's an on/off error? Somtimes working, sometimes not?
At least there was no c:geo release in between.

**Comment by murdok80** [comment]
No it was a mistake. It works never right. Only my last post is a chance. It is so bad i would like to go  caching but without app it is shit.

**Comment by pstorch** [comment]
@murdok80 Ok, I was just confused 😉. 
I still don't know what could cause this. Have you sent your c:geo System information?

**Comment by murdok80** [comment]
No. Where can i find the send option?

**Comment by murdok80** [comment]
I found it.
--- System information ---
Device: SM-G920F (zerofltexx, samsung)
Android version: 7.0
Android build: NRD90M.G920FXXU5EQEG
c:geo version: 2017.05.22
Google Play services: disabled - 11.0.55 (440-156917137)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (9,8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (9,8 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (9,8 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (200,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by pstorch** [comment]
@murdok80 ok, you are also using the correct sensor (rotation vector).

From my point of view the only thing we could try is increasing the sensor delay to game: `SensorManager.SENSOR_DELAY_GAME`. Should we try it in a nightly?

**Comment by murdok80** [comment]
Yes. Then give me the downloadlink and i will test. I hope it works.

**Comment by murdok80** [comment]
Yes Please make a Nightly and i will test it. I hope it works.

Andre Meschke

Am 28.06.2017 13:46 schrieb "Peter Storch" <notifications@github.com>:

**Comment by pstorch** [comment]
@murdok80 can you test the build from PullRequest #6619? http://ci.cgeo.org/job/cgeo%20pull%20request/969/artifact/main/build/outputs/apk/cgeo-debug.apk

**Comment by murdok80** [comment]
I test it and i had the same problem.

Andre Meschke

Am 28.06.2017 21:00 schrieb "Peter Storch" <notifications@github.com>:

@murdok80 <https://github.com/murdok80> can you test the build from
PullRequest #6619 <https://github.com/cgeo/cgeo/pull/6619>?
http://ci.cgeo.org/job/cgeo%20pull%20request/969/artifact/
main/build/outputs/apk/cgeo-debug.apk

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cgeo/cgeo/issues/6550#issuecomment-311755828>, or mute
the thread

**Comment by pstorch** [comment]
Ok, bad luck. Thanks for testing and the fast feedback.

**Comment by murdok80** [comment]
And what can i do now.

Andre Meschke

Am 28.06.2017 22:31 schrieb "Peter Storch" <notifications@github.com>:

**Comment by pstorch** [comment]
Unfortunately I don't know. Maybe someone else comes up with an idea.

**Comment by murdok80** [comment]
Can you whrite also in german?


Andre Meschke

Am 28.06.2017 22:38 schrieb "Peter Storch" <notifications@github.com>:

**Comment by pstorch** [comment]
Ja, ich kann auch auf deutsch schreiben. Ich habe halt im Moment keine Idee, was bei Samsung da schief läuft. Alle Kompass Beispiele, die ich bisher gesehen haben, funktionieren so ähnlich, wie es in c:geo auch implementiert ist. Ohne so ein betroffenes Gerät hier zu haben, wo man vielleicht mal debuggen könnte, kann ich nur mutmaßen. Stochern im Nebel sozusagen.

**Comment by murdok80** [comment]
Also ich bin der Meinung unter Android 6 hatt das alles noch funktioniert.
Na egal ich glaube ich habe den Fehler gefunden. Zumindest kann ich es
reproduzierbar nachvollziehen.
Bei der Samsungreihe S4 bis S7 verliert der Kompass ja bei nem Neustart die
Kalibrierung das sollte ja bekannt sein.
Wenn ich nach einem Neustart ins C:GEO gehe funktioniert der Kompass. Nur
das er halt noch nicht kalibriert ist.
Sonst bin ich dann immer über *#0*# ins Systemmenü gegangen und hab den
Kompass kalibriert. Mit dem Ergebnis das ab dem Zeitpunkt der Kompass in
C:GEO nicht mehr funktionierte.
Nun hab ich das Handy mal neugestartet bin gleich in C:GEO gegangen und
habe dort den Kompass kalibriert indem ich 8en geschlagen habe. Und siehe
da Kompass funktioniert wie er soll.
Ich werde das mal weiter beobachten und mich notfalls nochmal melden.
Getestet hab ich mit der Version aus dem PlayStore.

Grüße

Andre Meschke

Am 28.06.2017 22:46 schrieb "Peter Storch" <notifications@github.com>:

**Comment by pstorch** [comment]
@murdok80 danke für die Information, d.h. bei dir geht es wieder.

To all others: @murdok80 could solve the compass issue on his S6 via "painting" a big 8 in the air with his phone. The compass calibration via Samsung system menu `*#0*#` didn't work for him since upgrade on Android 7. And it has to be done on every restart.

@VeseliMimoni do you still have this problem? Can you solve it with this instruction?

**Comment by VeseliMimoni** [comment]
Hello, I tested. Compass is now quick, but not always showing to right direction. For example, a cache located about 2km from me on north is was after first "8" showing correctly to North, but when I turn mobile 360° it was pointing to sowthwest. After another turn it was pointing to NorthEast. 

Not solved for me. sorry.

**Comment by murdok80** [comment]
Ich muss das nochmal real an einem Cache testen.

Andre Meschke

Am 29.06.2017 09:42 schrieb "VeseliMimoni" <notifications@github.com>:

**Comment by murdok80** [comment]
Also nach nem Handyneustart funktioniert es kurz halbwegs und dann bleibt
der Kompass wieder stehen.

Andre Meschke

Am 29.06.2017 16:34 schrieb "Andre Meschke" <andre.meschke80@googlemail.com

**Comment by pstorch** [comment]
@murdok80 wenn man mal nach "Samsung s6 kompass kalibrieren" sucht, gibt es jede Menge Treffer. Neben den hier schon verschten, melden ein paar User Erfolg, in dem sie die Cache Partition löschen. Dadurch verliert man keine Daten, aber es kann doch das ein oder andere Problemchen nach einem Upgrade beheben. 

Hier eine Anleitung auf deutsch:
http://www.spickipedia.com/index.php/tipps-a-tricks/4041-samsung-galaxy-s6-wipe-cache-durchfuehren-anleitung

Vielleicht hilft das ja bei deinem Gerät.

**Comment by murdok80** [comment]
Hat nix gebracht.

Andre Meschke

Am 29.06.2017 22:18 schrieb "Peter Storch" <notifications@github.com>:

@murdok80 <https://github.com/murdok80> wenn man mal nach "Samsung s6
kompass kalibrieren" sucht, gibt es jede Menge Treffer. Neben den hier
schon verschten, melden ein paar User Erfolg, in dem sie die Cache
Partition löschen. Dadurch verliert man keine Daten, aber es kann doch das
ein oder andere Problemchen nach einem Upgrade beheben.

Hier eine Anleitung auf deutsch:
http://www.spickipedia.com/index.php/tipps-a-tricks/4041-
samsung-galaxy-s6-wipe-cache-durchfuehren-anleitung

Vielleicht hilft das ja bei deinem Gerät.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cgeo/cgeo/issues/6550#issuecomment-312091963>, or mute
the thread

**Comment by murdok80** [comment]
Hallo
Ich habe nun mein S6 neu geflasht und es läuft wieder Android 6 drauf. Damit funktioniert alles wie es soll.
I downgrade my S6 to Android 6 and the Compass  Works perfect.

**Comment by pstorch** [comment]
I would not recommend downgrading. There must be a better solution.

**Comment by murdok80** [comment]
If somebody have a fix for the Problem with the S6   Android 7 and cgeo, i will update from Android 6 to 7.

**Comment by Lineflyer** [comment]
I assume the Samsung S6 with newest manufacturer provided upgrade is a device very often used. Given that, I do see not many users on our support channels having problems .Just a few as we can see here.
 IMHO there is something special/unusual in these cases.

**Comment by Rockfiddler** [comment]
Just adding another case to this problem.  Galaxy S6 using latest Android 7.  Stock handset (i.e. not rooted).
Compass is very slow to rotate, and often stops in wrong direction.  If I rotate the the phone, the compass eventually rotates also, but only partly.  Moving phone again the same happens, but final direction will be different.
I also have 'Official' Geocaching app installed and it works correctly, as do all other mapping/compass apps I've tried.  Only c:geo is like this.

**Comment by c64datenklo** [comment]
Hi, I have the same problem with the S6. It's very annoying and I'm forced to use the bad official gc app :-/. I'm shortly before downgrading to Android6.

Can I help to debug it?

**Comment by samueltardieu** [comment]
> It's very annoying and I'm forced to use the bad official gc app :-/. I'm shortly before downgrading to Android6.

Can't you install a radar application such as "GPS status" and use the radar functionality (instead of compass) from cgeo? That would launch "GPS status" as part of cgeo radar. This is not a fix, but would allow you to not use the gc app and not downgrade your operating system version.

**Comment by michalhejl** [comment]
Same issue here. All my symptoms are similar/same to what users above have described. What I found interesting is:
#1 the issue normally is only in c:geo only and not in mapy.cz, Google Maps, GPS Status, etc.
#2 ocassionally when I switch back and forth between c:geo and GPS Status I can sometimes get c:geo compass to work (only until minimized) or GPS Status to stop working (resumes work after c:geo closed)

**Comment by Lineflyer** [comment]
Question to the affected users in this thread:
Any changes? I heard about a recent system update on S6 in November/December 2017.

**Comment by spikyxpto** [comment]
I have updated to the most recent system update (december 2017) but the problem still there. The compass is very slow to move.

**Comment by spikyxpto** [comment]
If I open c:geo and then gps status, the gps status app will have the same slow compass but as soon as I close the c:geo app the compass on gps status return to normal.

**Comment by michalhejl** [comment]
I experience the same, slow compa in GPS Status until I close c:geo.

**Comment by pstorch** [comment]
Interesting. @spikyxpto and @michalhejl is someone of you able to provide a video of that behavior?

**Comment by spikyxpto** [comment]
@pstorch Link to the video https://youtu.be/rz8VdaAvsxw

**Comment by murdok80** [comment]
Last Year i have the same problem. I Restart the galaxy and start cgeo. The i calibrate kompass only in cgeo. (Turn a 8 in the air). Sometimes it Works for a small Time correct. I solved the problem with a Downgrade to Android 6.
And Now i habe the galaxy s7 Edge wir no Problems.

**Comment by Lineflyer** [comment]
No other reports on this.
Although the last Samsung S6 official version is still Android 7 and we have quite some users with this device, we received no more complaints.
For now lets assume it was somehow a single case or fixed by Samsung with a minor update in 2018.
