### ISSUE TITLE
Make debug log setting transient or hide it somehow

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6552]
We still have some occurence of crashes reported on Google Play, which canbe tracked back to the fact that users have debug logging activated (in which case we might explicitly abort the app in some failure cases).

After thinking a bit about it (and also discussion in some issues here) I came to the conclusion, that the end user experience is the important point here. We can not blame users for accidentally activating the setting, but should take measures to avoid them running into this problem.

So mainly two ways I can imagine:

1. Make the setting somehow transient
It is not wise to disable debug logging on each start, because the startup and login process itself is likely to need debug logging during testing. But might be it is technically possible, to disable it after 24 hours?!

2. Hide the setting from normal settings menu and move it to somewhere else.
For example clicking x times on a certain icon to activate it.

**Comment by pstorch** [comment]
I'm still thinking about a visual warning when running in debug mode. And I also thought about calling an Activity via Intent which shows the error message with some explanations and possibility to share it.

**Comment by Lineflyer** [comment]
> And I also thought about calling an Activity via Intent which shows the error message with some explanations and possibility to share it.

I think this is covered by another issue regarding crash reporting in general.

For the other point:
A visual warning would not help solve the situation...if people enable it they also have not read the warning right above the menu option.

**Comment by pstorch** [comment]
I was searching for the crash report issue, do you mean #1732 ?

For the visual part, I thought about something really nagging, like a red toolbar.

We could also ask on each startup if the debug log is still needed. Would be better than silently resetting it.

But I'm also ok with hiding the option somewhere.

**Comment by Lineflyer** [comment]
Dont know the particular issue. The topic came up once in a while when I copied crash reports from Play to Github. 
Just use the Google Play Console and search for "Aborting on Log.e".
There is e.g. one crash happening to a user constantly and he reports it everytime with comments like "once again", "shitt instable", "first crash of the day as usual". And from the reports we cannot even contact him, that he is causing it himself by having debug active.

**Comment by pstorch** [comment]
> There is e.g. one crash happening to a user constantly and he reports it everytime with comments like "once again", "shitt instable", "first crash of the day as usual". And from the reports we cannot even contact him, that he is causing it himself by having debug active.

Ok, that's hard. Either turn it off automatically or nag him frequently to turn it off. I'm still in favor of nagging on each startup. But that is only my opinion ;)

**Comment by SammysHP** [comment]
A popup on every start (with the possibility to turn off debug mode) seems to be a good solution IMHO.

**Comment by Lineflyer** [comment]
> A popup on every start (with the possibility to turn off debug mode) seems to be a good solution IMHO.

Lets say every 5th or 10th start?

**Comment by Lineflyer** [comment]
If someone would be willing to implement this, please feel free to put it into `release` branch to have a smaller time to market.

**Comment by pstorch** [comment]
Starting here

**Comment by pstorch** [comment]
I've sent a PR with a confirmation dialog on startup. But I didn't implement a count of the start. So it's showing up on every start. I don't know if this is annoying for you. I myself use the debug mode very seldom.

**Comment by samueltardieu** [comment]
I didn't realize you intended to do that even when the build is in debug mode. It should be restricted to builds in release mode.

**Comment by pstorch** [comment]
@samueltardieu ah, thanks for pointing this out.
