### ISSUE TITLE
Don't connect trail at coordinate jumps

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6558]
##### Detailed steps causing the problem:
- open c:geo.
- go geocaching. Have your live map setting "show trail" ON.
- go about. Allow the screen to timeout and turn off. Continue your journey, preferrably not in a straight line. Or switch to other apps with window manager for a while.

##### Actual behavior after performing these steps:
- See your trail in c:geo and how well it matches your actual journey.
Everytime c:geo is not active in foreground (screen on, c:geo has focus) the "trail" is not recorded / remembered. When one turns the screen on or switches back to c:geo, the location jumps and the trail is prolonged with a straight line from last recorded position (which can be quite old and far away)

**Problem happens also when another app is maintaining GPS fix in the barckground (when screen is off, etc).**

##### Expected behavior after performing these steps:
- one would expect the trail to match your actual journey. 

##### Version of c:geo used:
all versions of c:geo (at least in the past year)

##### Is the problem reproducible for you?
Yes, always.

##### System information:
```
MULTIPLE DEVICES
```

##### Other comments and remarks:
Here I am describing pure user experience.
Technically it may be related to https://github.com/cgeo/cgeo/issues/6549

**Comment by andrixnet** [comment]
Several km worth of journey, with c:geo showing trail, while the screen was not always on.

![screenshot_2017-05-12-12-02-58](https://cloud.githubusercontent.com/assets/3382777/26016079/3870f5fc-376c-11e7-8d93-6b8ab895696c.png)

---------
The same journey as recorded track by Pathaway application keeping GPS fix continuously on in the background (including when screen was off and app didn't have focus) and recording track.

![screenshot_2017-05-12-12-03-31](https://cloud.githubusercontent.com/assets/3382777/26016102/5273b674-376c-11e7-9123-c36d73216bad.png)

_One can easily see that the actual journey was very different from what c:geo showed._
Such differences may be important to users and to the activity of searching for a geocache. 

Also the fact that "show trail" only actually works when c:geo has focus and screen is on practically invalidates 50% or more of it's usefulness.

Thank you.

**Comment by SammysHP** [comment]
Yes, you're right. We should either remove that feature (because its use is only very limited) or don't show a line where the recording was interrupted.

**Comment by andrixnet** [comment]
There is also a third option: implementing full GPS usage in https://github.com/cgeo/cgeo/issues/6549 should automatically fix this (or at least >90% of it)

**Comment by SammysHP** [comment]
It wouldn't fix it because c:geo might be in the background and not in use.

**Comment by Bananeweizen** [comment]
I suggested the removal already in #4886, but I was voted down. Nevertheless I suggest again to remove the feature. It is not essential for geocaching, and it will _always_ be below the standards of full featured tracking apps, even if we fix this issue (no export of the track, no import of a track to follow, ...). So people will continue to not be happy...

**Comment by pstorch** [comment]
+1 for removal

**Comment by UniQP** [comment]
Having a track is really helpful for a quick orientation and to judge whether the next stage of a (multi) cache looks reasonable.

So +1 for keeping it.

**Comment by SammysHP** [comment]
Please vote thumbs up or down on #4886 and keep this issue as a follow-up once we have decided.

**Comment by Lineflyer** [comment]
My personal opinion on tracking features in c:geo:
Since a year I am out for geocaching more often by hiking a long trail or a bike tour.
For this I personally missed the opportunity of c:geo to basically support tracks. A significant number of hiking/biking (multi)caches provide users a GPX track as assistance.
I had to use another app for the track but in parallel contantly switch to c:geo to look for the next stage onroad or even for other caches along the track.

So in my case the trail feature is not so important but importing and showing a track would be.
However if we would support showing imported tracks (which I would really like) it may make sense also showing the way the user already made.

**Comment by andrixnet** [comment]
My vote is +1 for keeping this feature and making it work properly.
If I may make a suggestion, traking functions (as described above, and then including this feature) might be implemented as a separately installable plugin? Or have it as core functionality.

**Comment by Bananeweizen** [comment]
I think the discussion is again heading in the wrong direction. I see none of the developers willing to fix all the open issues around this feature. Therefore to me it does not matter if some people want to have it (as users). If the code is not doing what the users expect and no one is willing to fix it, then it should be removed.

And the comment of @Lineflyer is exactly what I envisioned before: If we fix the trail now, someone  asks for importing a track, and for showing track directions, and for voice navigation, and for...
Let's simply stop that by removing it.

**Comment by samueltardieu** [comment]
Agreed. Let's remove it if nobody is ready to committing to fixing and maintaining it.

**Comment by Lineflyer** [comment]
I understand the point of insuficient maintenance, but judging by this we would need to remove a lot of functions (look at all the open issues).
I think this is a problem we will always have, due to the open-source principle. 

For newer features we IMHO have implicitly found a good way as we only implement them after extensive review and test.
However for older features which have problems since ever the solution can not be, just to remove them if someone asks for a solution.

**Comment by Lineflyer** [comment]
Recently the trail feature was "repaired" and also the max. distance for not connecting trail points is now adressed in a dedicated issue. 

I was not aware of this duplicate, so lets close here.
