### ISSUE TITLE
Add .nomedia to GeocacheData dir

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6562]
There are some users on social media and support mail asking us, why suddenly they do see a large amount of geocaching related pictures in their gallery apps.
It seems, that some gallery apps also scan below `/Android/data` for media files and thus show them in the overview. I am not sure, if there is any standard or guideline if these folders should be scanned for media (e.g. on my S7 the default gallery app is not showing them).

We could think about placing a `.nomedia` file into the base dir of `GeocacheData`. What do you think?

**Comment by Lineflyer** [comment]
According to https://developer.android.com/guide/topics/data/data-storage.html#filesExternal it is a possible method to place a `.nomedia` file into the folder.

**Comment by Bananeweizen** [comment]
For implementation, this should reference https://developer.android.com/reference/android/provider/MediaStore.html#MEDIA_IGNORE_FILENAME.
