### ISSUE TITLE
Routing using c geo

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#6570]
##### Detailed steps causing the problem:
- making a geocaching tour of a number of geocaching using live map
- is it possible to select geocaches and give a special coloured mark to shown the route you have designed so navigation will be more easy

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by SammysHP** [comment]
This is already covered by other issues: #3523, #5373, #5798, #6313, #6187, ...

I cannot find the issue regarding route/track loading and custom sorting at the moment.

PS: Please either fill in the template completely (for bug reports) or remove it.
