### ISSUE TITLE
Cannot open cache in external browser anymore

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#6572]
##### Detailed steps causing the problem:
- Go to cache details
- Select "Open in browser" in menu

##### Actual behavior after performing these steps:
Only two options are available:
1. c:geo internal browser
2. c:geo

##### Expected behavior after performing these steps:
First of all, why is option 2 even an option? Seems pretty pointless, IMHO.

I miss the following option
3. External browser, that opens the cache in the web browser of your choice.

I know that this option was available in the past, but I do not know when or why it was removed.

##### Version of c:geo used:
2017.05.13-NB-58da415

##### Is the problem reproducible for you?
Yes

**Comment by SammysHP** [comment]
Sadly this is a known issue that we cannot influence. Please follow the instructions in this FAQ entry: http://www.cgeo.org/faq.html#open-in-browser
