### ISSUE TITLE
Add inaccuracy to compass screen

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#6579]
Feature request from IRC:
(09:48:16 AM) Cuma: I want to ask if you can put the incurrency to the compass screen? That would be awesome.

**Comment by Lineflyer** [comment]
It is already AFAIR


Von meinem Smartphone gesendet.
null

**Comment by pstorch** [comment]
Yes, very small at the very bottom of the screen.

**Comment by Lineflyer** [comment]
IMHO that should be sufficient.

**Comment by UniQP** [comment]
Then, I'll close here. If he appears in IRC again, we can point him to this issue.
