### ISSUE TITLE
“Delete past events” and “Clear History” menu items gone

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#6583]
I recently updated to a new NB, and the aforementioned menu items are no longer there even if the current list has a past event, for example.

**Comment by SammysHP** [comment]
At least "clear history" is located in the new "manage caches" menu. I expected it to be in "manage lists", though.

**Comment by mirabilos** [comment]
SammysHP dixit:

>At least "clear history" is located in the new "manage caches" menu. I
>expected it to be in "manage lists", though.

Aaaah!

So this is both:

ⓐ a hierarchical menu (for whom it’s customary to have the menu name
  followed by … (\u2026 ELLIPSIS) or an arrow like ‣)
ⓑ a dynamic menu (not all menu entries are shown, only the activated
  ones)

This is *really* hard to use. Not showing the currently not available
menu items (in greyed-out) makes it hard for users to learn what is
where, and making it hierarchical means they have to look into several
sub menus to find things (if at all), and not even adding … or ‣ to
the menus with sub-menupoints makes it REALLY really confusing.

I kindly request something to be done about this… while I did not
like the vertical scrolling of the old non-hierarchical menu very
much it was better than having to look in all those submenus.

Thanks!

**Comment by SammysHP** [comment]
> a hierarchical menu (for whom it’s customary to have the menu name followed by … (\u2026 ELLIPSIS) or an arrow like ‣)

The initial draft contained … but it was decided to remove them because since Android N an arrow is added automatically. See https://github.com/cgeo/cgeo/pull/6567#issuecomment-302028673. "Manage …" should be enough to expect some more functionality behind the item in the menu, either a new activity or a sub menu. Anyway the user wants to "manage caches" and he will have the possibility to do so with the item.

> a dynamic menu (not all menu entries are shown, only the activated ones)

This is covered by #6578.

As both items were found I'll close this issue. For further discussion about "disable instead of hide" please comment on #6578, but I think that feature request is accepted. As I explained, it should be quite obvious that there is "something" behind the menu items. It might take a while for long-time users to adapt to the new menu, but I think that is is more structured and easier to use than the previous endless list.

**Comment by SammysHP** [comment]
PS: Just out of curiosity: Is there any other language with "dixit" except Latin?

> SammysHP dixit:

PPS: I'll delete this comment from the website and just rely on the mail notification for communication. ;)

**Comment by kumy** [comment]
Dind t followed the whole conversation, but "dixit" exists in french.

On May 28, 2017 10:49:41 PM GMT+02:00, SammysHP <notifications@github.com> wrote:
>PS: Just out of curiosity: Is there any other language with "dixit"
>except Latin?
>
>> SammysHP dixit:
>
>PPS: I'll delete this comment from the website and just rely on the
>mail notification for communication. ;)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6583#issuecomment-304539374

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mirabilos** [comment]
SammysHP dixit:

>that feature request is accepted. As I explained, it should be quite
>obvious that there is "something" behind the menu items. It might take

Probably, but without any visual hint I’d expect it to switch to
some complicated “management UI”, not just open a sub-menu.

>a while for long-time users to adapt to the new menu, but I think that

(Not actually that long-time here…)

>is is more structured and easier to use than the previous endless
>list.

**Perhaps.**

On the other hand, *casual* users will be *much* less able to
discern what the software can do and how by just looking at the
menu items and/or visually searching for things.

Imagine you cannot remember how something was named and don’t
even want to think about into what category the developer of
the software may have put a particular functionality. In those
cases, scanning a linear list, even if it’s 1¼ screen pages long,
will win.

Case in point: you thinking that “Clear history” was in the
other of the two.

Small suggestion (although I don’t know if / how much this
would actually improve the nested menu situation): make there
be only *one* menu point with a submenu, instead of multiple.

Consider websites where users often react allergic to submenus
as well (although probably for different reasons…).

Thanks!

**Comment by mirabilos** [comment]
SammysHP dixit:

>PS: Just out of curiosity: Is there any other language with "dixit"
>except Latin?

That’s Latin ☺

(OK @ deleting off-topic comments)
