### ISSUE TITLE
Empty "manage lists" in history

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6584]
##### Detailed steps causing the problem:
- Open empty history
- Open menu

##### Actual behavior after performing these steps:

Menu opens with only one sub menu - manage lists - which is empty.

##### Expected behavior after performing these steps:

Either no menu at all or only items/sub menus that contain sub items.

##### Version of c:geo used:

2017.05.28-NB-bb400f3

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: Nexus 4 (occam, google)
Android version: 7.1.2
Android build: lineage_mako-userdebug 7.1.2 N2G47O b2fb476900
c:geo version: 2017.05.28-NB-bb400f3
Google Play services: disabled - 10.5.48 (436-150087156)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: fast
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (3,9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (3,9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (3,9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (280,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Strange.
When history is not empty, "Manage lists" opens nothing for me. Are you seeing an empty submenu or also just nothing?

**Comment by SammysHP** [comment]
Yes, I see nothing. There's just this single menu item "manage lists" and when I click on it it closes. In this situation there is no action in the menu and the menu could be hidden completely.

**Comment by pstorch** [comment]
When we implement #6578 we would have a submenu here, but with only disabled entries. Would this be ok?

**Comment by SammysHP** [comment]
I'd disable a menu if all sub-items are disabled. This would propagate up to the root menu which might be hidden completely in case everything is disabled.

**Comment by pstorch** [comment]
Or, when I look at the hidden/disabled items in the "Manage lists" submenu, I could also think of enabling "Make list unique" for the History. Might this be a UseCase for someone? It would remove logged Caches from all other lists.

**Comment by Lineflyer** [comment]
> Or, when I look at the hidden/disabled items in the "Manage lists" submenu, I could also think of enabling "Make list unique" for the History. Might this be a UseCase for someone? It would remove logged Caches from all other lists.

I understand the fucntion, but this does not fit good into our lists structure, as the history is not equal to a "normal" list and probably users won't understand what this item will do.

**Comment by pstorch** [comment]
The logic has change in the meantime. Can we close here?

**Comment by Lineflyer** [comment]
Will check.

**Comment by Lineflyer** [comment]
The "Manage lists" item is no longer shown in the history (not when empty, neither when items are contained).
