### ISSUE TITLE
Some icons in "manage caches" 

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6585]
##### Detailed steps causing the problem:
- Open list
- menu, manage caches

##### Actual behavior after performing these steps:

The sub menu contains two icons. 

##### Expected behavior after performing these steps:

AFAICS these are the only items with icons. We should either add icons to all items or remove all icons to be consistent.

##### Version of c:geo used:

2017.05.28-NB-bb400f3

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: Nexus 4 (occam, google)
Android version: 7.1.2
Android build: lineage_mako-userdebug 7.1.2 N2G47O b2fb476900
c:geo version: 2017.05.28-NB-bb400f3
Google Play services: disabled - 10.5.48 (436-150087156)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: fast
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (3,9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (3,9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (3,9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (280,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
I agree. IMHO we should remove them from the submenus as it is more easy as finding suitable icons for all of them.

I guess they have been added for the case they might show up as icon instead of menu name for the actionbar. Now that they are in submenu those icons are not needed for that purpose.
