### ISSUE TITLE
Can we use a normal changelog?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6586]
I was wondering, if we could provide a changelog.md file as proposed at http://keepachangelog.com. I generally like human readable change logs in open source projects, and ours is unfortunately not very human readable (due to XML formatting and being hidden in some folder).

What's your opinion? Should we try to maintain a purely markdown formatted changelog, and include it into the app resources via gradle build automatically? I'm sure the conversion itself can be done easily, however I'm not sure yet about our separation of changelog_release and changelog_master...

**Comment by pstorch** [comment]
Maybe we don't need a conversion at all: https://github.com/falnatsheh/MarkdownView

**Comment by Lineflyer** [comment]
Why not. 
It does not matter for me whether it is HTML or markdown.

If we have two of them it should also work with the different changelogs on the branches...but you know the method better than I do.
