### ISSUE TITLE
New features process

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#6589]
Probably I should have asked somewhere in IRC, but it's more convenient from smartphone here and also it will be documented.

The question is stupid simple - how do you select which features to implement next (except bugfixing and some maintenance stuff)? Just decide witchin the evening chat in IRC? Or do you have some kinda voting for new features? Except implementing it by my own, is there some possibility to increase chance of being implemented for features I'm (and other users) interested in?
Maybe it would be useful to have issues list with "votes" so you could see what users would like to see ("users" in this context == "github users")

**Comment by SammysHP** [comment]
Well, you can vote as much as you want. The development of c:geo is a hobby and nobody is required to implement n features per week. Usually everyone does what he likes. So if you really want a specific feature, implement it yourself or find someone who does it.

**Comment by Lineflyer** [comment]
We are an opensource app. A ranking of features is helpful to learn users demands but at the end of the day, there needs to be someone interested and programming it....which is neither predictable nor demandable.
