### ISSUE TITLE
Make Mapsforge Beta default

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6594]
IMHO we already had such an issue, but I failed to find it.

Despite the [known issues](https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Map%22) for the Mapsforge Beta implementation, I would like to initiate a discussion about making it live asap.

Main reason is, that user complaints/questions are rising as they load up to date maps (I guess e.g. from openandromaps.org) which do no longer work in c:geo as they changed to a newer mapsforge rendering meanwhile (refer to mail from openandromaps admin I forwarded to cgeo-dev mailing list some weeks ago).

Besides the above mentioned small issues, the only big open point is, that once mapsforge beta is active, the google maps are no longer selectable. In case this can be solved (enabling them again as they are while the new mapsforge is active) I would prefer to switch the library rather soon.

Any opinions?
@rsudev (or anyone capable) Would you have a little time for that (and maybe for some of the small issues, which you consider a drawback)?

**Comment by rsudev** [comment]
Unfortunately I was (and partly still are) very much tied up in work for a long time, so I just managed to follow the discussions superficially.
I have an idea how to integrate the two again (we even now re-start the map activity under the hood when switching), but this will not fill the feature-gap between the two (cache selection pop-up, target-mode, waypoint through long-press) and I think we need a good way to make this distinction more prominent to manage expectations and not create to many questions from users.
I will start to work towards the integration, hopefully someone comes up with a good idea for the presentation.

**Comment by SammysHP** [comment]
The most important feature is still missing: map feature selection. Many maps do not work without it because of too many or overlapping features. There is also a discussion about multi-language. So before the beta map will be made default at least the standard mapsforge features should be implemented.

IIRC the attribution is still missing, we shouldn't make the same mistake again and add it.

Or in other words: We need someone with plenty of time to finish the new map implementation.

**Comment by rsudev** [comment]
Regarding the map feature selection: should we really just insert the huge selection menu tree into our map menu? Or is there a better idea, how to present that?
AFAIK, openandromaps work well without the feature selection, 'freizeitkarte' IIRC not really (which is IMO a design fail)

**Comment by Lineflyer** [comment]
I have no idea about the content of this feature selection. How many items are on it?
Anyway in a first step we can add it to the menu like we do for the theme selection and later improve it.

**Comment by SammysHP** [comment]
10-40 items, depends on the map.

**Comment by Lineflyer** [comment]
@rsudev 
Besides this map feature selection issue, could we promote the beta to the "normal" offline map? Do you have time for this (and ideally also tackling some of the open issues).
I know about the open issues (refered to in my initial posting) but I also see a lot of users claiming their offline map no longer working as most mapsforge map providers already compiling them with a newer version.

**Comment by rsudev** [comment]
As much as I would love to dive in right away, unfortunately it will not be possible (or fortunately - I will be on vacation in the Swedish wilderness the next ~ three weeks).

**Comment by Lineflyer** [comment]
@rsudev Enjoy your holiday....so we will postpone this unless someone can step in.

**Comment by Lineflyer** [comment]
@rsudev  
Hope you had an excellent vacation.
As I see forum threads and support mail still rising with "non working offline maps" in c:geo  (i.e. most map files offered for download are now on a higher mapsforge version) I would like to ask if you can find some time to work on this issue?

**Comment by Lineflyer** [comment]
Looking at Google Play console I seem c:geo performs very good, however most (known) crashes and ANR involves something with v3 mapsforge.
Wouldn't it be an option to use the newer library as a default? The only thing we have to solve would be to enable the user to also select Google while having activated "Mpasforge beta as default". Can this be realized?

In fact I was thinking about new version as default and change the setting option to be used as "Fallback to V3".

**Comment by Lineflyer** [comment]
According to my experience and other users feedback, all major map sources (such as mapsforge.org, openandromaps.org) meanwhile compile maps which require the newer mapsforge implementation.
At least the maps I tested from this sources always stay blank if I try to use them with the v3 implementation.

So this would mean:
All c:geo users which use offline maps (and updated their files in the last months) will already usethe beta implementation as default. I don't know the technical requirements, but wouldn't it make sense to just replace the v3 with the v6 implementation we have asap?

**Comment by Matze2** [comment]
I never had the checkbox "Mapsforge beta as default" enabled and I extensively use offline maps from openandromaps.
On one device the maps are from August, on the other from October.
As theme I installed the legacy "Elevate 2" from openandromaps and never had any problems.

**Comment by Matze2** [comment]
Excuse my ignorance: I enabled the checkbox "Mapsforge beta as default". Is there any place where I should see a difference?

As mentioned above I usually use offline maps from openandromaps (in my case Bavaria) and the "Elevate 2" theme Elevate_Hiking_XL.xml.

**Comment by Lineflyer** [comment]
> Excuse my ignorance: I enabled the checkbox "Mapsforge beta as default". Is there any place where I should see a difference?

There are a bunch of feature from the old map not working yet on the new map and some bugs of course. You can check them by filtering issues by label "New Map": [see here](https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Map%22)

Additionally Google Maps are not available while the setting is active, which is a drawback for some users. I don't know whether this is just a small glitch or anything bigger to enable it, as I don't know the programming details.

**Comment by Matze2** [comment]
Not having Google Maps is a big drawback in my opinion.
Sometimes you are in areas where no map is complete - neither OSM nor Google. But often they complement each other.

**Comment by Lineflyer** [comment]
> Not having Google Maps is a big drawback in my opinion.

I agree, but I have not idea what is required to have it included. From my amatuer thinking it would be available again if we just replace the old by the new library...but that might be to easy. @rsudev ?

**Comment by rsudev** [comment]
I personally never use Google maps ... :)
But seriously, selecting mapsforge beta as default does not fully disable the usage of Google maps. You still have it available as target navigation option e.g. for caches (and by enabling updates in this scenario even with a live view), but it certainly is not ideal.
Regarding making it work again, some background info.
The current 'main' map implementation is unified and uses a google and mapsforge 'backend' for rendering the map. This is not already optimal due to differences in the interface of the two libraries. I implemented the new map independently and only tailored to mapsforge. The 'transparent' switch between the two can still be done through a possibly unified map state implementation, but the feature disparity would stay (no circles on mapsforge beta yet, no target navigation and new waypoints on long press on google). Pulling that off is not very much work or rocket sience, but unfortunately more than I was able to pull off during the last year.
I have hopes, that I am better posed at contributing again this year, and this feature is certainly topmost on my personal to-do list...

**Comment by Lineflyer** [comment]
Would be great if you find the time to continue this topic. At least for combining Google and the new OSM into a common workflow. Open bugs and missing features can be treated seperately.

BTW, today I took a look at our ANR&Crash reports on Google Play and while we are fine in general some crashes are most prominent. Those involve v3.mapsforge. I also hope to get rid of them once we change to the new map.

Crash involving v3.mapsforge in combination with OSM:Mapnik (online):
```
java.lang.NullPointerException: 
   at android.graphics.Canvas.throwIfCannotDraw (Canvas.java:1270)
   at android.graphics.Canvas.drawBitmap (Canvas.java:1336)
   at org.mapsforge.v3.android.maps.FrameBuffer.drawBitmap (FrameBuffer.java:101)
   at org.mapsforge.v3.android.maps.MapView.redrawTiles (MapView.java:402)
   at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.onActionMove (MultiTouchHandler.java:91)
   at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.handleMotionEvent (MultiTouchHandler.java:186)
   at org.mapsforge.v3.android.maps.inputhandling.TouchEventHandler.handleTouchEvent (TouchEventHandler.java:149)
   at org.mapsforge.v3.android.maps.MapView.onTouchEvent (MapView.java:349)
   at cgeo.geocaching.maps.mapsforge.MapsforgeMapView.onTouchEvent (MapsforgeMapView.java:278)
   at android.view.View.dispatchTouchEvent (View.java:10013)
```
I think this (or something similar) is listed here #6446 

Additionally we still have these crashes and ANRs labeled with "tgkill" which according to #6669 are also related to mapsforge.

**Comment by pstorch** [comment]
Wouldn't it be feasable as a first step to put the "Betamaps Switch" into the Maps Menu? So we can easily switch between the two implementations? Maybe we have to live with the consequences to programatically restart the MapsActivity when switching, but that shouldn't be a big issue.

**Comment by Lineflyer** [comment]
I dont understand the programming background, but wouldnt it be the same to just use the new implementation as soon as somone selects OSM:Mapnik or an offline file, and in the same time keep the Google option available and switch back as soon as the user selects this? So no switch but implicitly switching....or is this nonsense?

**Comment by pstorch** [comment]
@Lineflyer do you want to get rid of the v3 version right away? Then your proposal would work.
I thought we still want to offer the v3 in case a user has an issue with the v6 version.

**Comment by Lineflyer** [comment]
A bit risky...but I use the beta exlusively for many months now without big issues (only the ones already listed somewhere here).
But (sorry for another amateur question) couldn't we turn around the current switch somehow:
Use the new implementation (but have Google available as option) by default and allow a setting to "Fallback to V3"

**Comment by pstorch** [comment]
> couldn't we turn around the current switch somehow

I guess so. But I wouldn't just negate the current setting. I would use a new setting name for this to initially set all users to the new map. So if someone wants to go back, he explicitly has to choose it.

**Comment by Lineflyer** [comment]
> I guess so. But I wouldn't just negate the current setting. I would use a new setting name for this to initially set all users to the new map. So if someone wants to go back, he explicitly has to choose it.

Yes, for sure no option as long as Google maps are not available while the setting is active. That in fact is the crucial point. IMHO a majorityof our users just uses Google Maps.

**Comment by pstorch** [comment]
Of course Google Maps should be available in the Menu even when the new Map is active.

**Comment by pstorch** [comment]
I'll have a look here.

**Comment by Matze2** [comment]
Since this week I also loaded freizeitkarte-osm together with the theme freizeitkarte-v5 on my device and now I finally understand the issue since this map works only with Mapsforge beta enabled. :satisfied:
openandromaps with Elevate2 theme also worked with the old version without problems.
Now I am looking forward to try it in the nightlies. 👍

**Comment by Lineflyer** [comment]
Thanks for taking care of this major step.
All known remaining issues of the new map should be already labeled accordingly:
https://github.com/cgeo/cgeo/issues?q=sort%3Aupdated-desc+label%3A%22New+Map%22+is%3Aclosed
