### ISSUE TITLE
String fav_points_remaining needs plurals

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6596]
Taken over from a comment of @kumy in Crowdin:

The string fav_points_remaining needs plurals to be correctly translated.

**Comment by UniQP** [comment]
@kumy Out of curiosity: Can you give an example?

I understand that `%d favorite points remaining` needs plurals but I'm surprised that `%d remaining` also needs them.

**Comment by kumy** [comment]
@UniQP, sure, it may translate in French as:

* 0 point favori restant
* 1 point favori restant
* 2 points favoris restants

**Comment by kumy** [comment]
Full sentence is: `Add this cache to favorites (%d remaining)`

Which is translated as `Ajouter cette cache à vos favoris (%d restants)`

* Ajouter cette cache à vos favoris (0 restant)
* Ajouter cette cache à vos favoris (1 restant)
* Ajouter cette cache à vos favoris (2 restants)

**Comment by UniQP** [comment]
Interesting, thanks.
