### ISSUE TITLE
Wrong CI result with pipeline-based build

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#6599]
http://ci.cgeo.org/job/cgeo%20continuous%20integration%20(experimental)/69/ tested a broken commit that does not compile, but reported SUCCESS.

Corresponding test of the other CI: http://ci.cgeo.org/job/cgeo%20pull%20request/951/

**Comment by Lineflyer** [comment]
Pipelines are still in experimental state , refer to #6587
