### ISSUE TITLE
Missing list function on "show as list"

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#6600]
##### Detailed steps causing the problem:
- show map
- select "show as list" ("Als Liste anzeigen")
- three dot menu misses functions other list menus have - most important for me would be 
   * "move all" ("Alle verschieben")
   * "delete all" ("Alle löschen")

##### Expected behavior after performing these steps:
- show above mentioned menu entries (or even more of the list functions of the "saved caches" ("Gespeicherte Caches") program part)

##### Version of c:geo used:
- current release: 2017.05.22

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Adding the above mentioned functions would it make much easer to handle saved caches based on location, like deleting no longer needed caches, splitting up into several list etc.

A use case for "delete all" would be: Before a holiday I download many caches using pocket queries. Sometimes I'm saving all those caches to a single list (my fault, I know). Currently the only way to clean up is either to manually delete the no longer needed caches one by one (not feasible with 100s of caches) or delete the whole list and reload the still needed caches.

**Comment by Lineflyer** [comment]
Basically you are right, but the problem here is, that the resulting list after "Show as list" may also contain unsaved caches. For these the relevant items like Move, Delete are not suitable.

**Comment by moving-bits** [comment]
For an unsaved cache "Move" would be equivalent to "Save in List", and "Delete" simply would be ignored, since there is nothing to delete in this case.

**Comment by mjarmstr** [comment]
I also would like similar functionality to this.  My uses case is as follows.

I have a weekly pocket query I run with 1000 caches in my area that I import.  Then I show the query on the map and zoom into the area I want to cache in today.  I show as lists and copy/move the caches to a new/current lists.  I don't want to use the store option because I don't want to wait for them to refresh.  I just want to put them in a new list.

**Comment by murggel** [comment]
@moving-bits  we now have the menu "store offline" and "delete" - so can we close here?

**Comment by moving-bits** [comment]
The extensions to the "store offline" feature are definitively a step forward, although it does not help with the use case described.

But I'd say let's close this old FR anyway (as @fm-sys already did), and if the described missing feature starts bugging me again baldy enough, I'll either reopen or create a new, more specific issue.
