### ISSUE TITLE
no images in decription

### ISSUE THREAD

**Issue by Pentatops** [cgeo/cgeo#6605]
##### Detailed steps causing the problem:
trying to watch a cache description. Online or offline (already stored on the device).
The "download images" checkbox is set
This happens only with some caches. E.g.: GC6ZPRE; GC6BHT6

##### Actual behavior after performing these steps:
I simply see no image of the cache description. Neither in the cache description tab nor in the image tab.

##### Expected behavior after performing these steps:
See the pictures on my Android device

##### Version of c:geo used:
2017.05.22

##### Is the problem reproducible for you?
Yes

##### System information:
several SAMSUNG devices, including GALAXY TAB 2 with Android 4.2.2 and S3 mini with Androis 4.1.2

##### Other comments and remarks:
same problem as #5848??

**Comment by pstorch** [comment]
I cannot reproduce. I can see the images of the cache description of both caches mentioned. Maybe temporary network problems?

**Comment by Pentatops** [comment]
Hello Peter,
thanks for the quick reply.
I did further tests:
it does not work on:
Samsung GALAXY TAB 2 7.0 (GT-P3113) with Android 4.2.2
Samsung GALAXY Note 10.1 (GT-N8000) with Android 4.4.2
Samsung GALAXY S3 mini (I8190) with Android 4.1.2
see attached pictures.

It works fine on:
ZUK Z1 with Android 7.1.2
HUAWEI nova with Android 7.0

No, network is OK on all tested systems.
A SAMSUNG related problem?

Best regards,

Gunther Boehm

**Comment by pstorch** [comment]
@Pentatops can you try with debug log enabled and see if the app crashes somewhere? It's under Settings / System. Don't forget to disable it afterwards. 

@Lineflyer do you have one of those devices available for testing?

**Comment by pstorch** [comment]
@Pentatops there are no attachments. Maybe you have to upload them via the web site. Can you also copy & paste the system information of those devices here?

**Comment by Pentatops** [comment]
I should better attach something to send attachments .... sorry!

I tried the debug mode – nothing special happens, images still not there.

Please find the screenshots of the cache description tabs and the system information of the two devices that I have on hand.

best regards

Gunther

**Comment by SammysHP** [comment]
As @pstorch explained it is not possible to attach files via mail. Please use the website of GitHub or upload them somewhere else and just link them.

**Comment by Pentatops** [comment]
Another trial to send the attachments...
![screenshot_2017-06-19-19-20-45](https://user-images.githubusercontent.com/29523481/27300477-23fd857c-5530-11e7-9907-cccdf53725c2.png)
![screenshot_2017-06-19-20-10-13](https://user-images.githubusercontent.com/29523481/27300478-23fe3d6e-5530-11e7-9a95-de783c4550e6.png)
![s3mini](https://user-images.githubusercontent.com/29523481/27300476-23fa852a-5530-11e7-9559-0ac7dde13783.JPG)
![screenshot_2017-06-19-19-20-37](https://user-images.githubusercontent.com/29523481/27300475-23f741ee-5530-11e7-861e-d6ec00203513.png)

**Comment by pstorch** [comment]
Ah, now there are images. 
But with system information I meant the ones from c:geo ☺️
Open c:geo, then the menu and click on About. Then swipe to the right, until System. Please copy this information here.

**Comment by Pentatops** [comment]
That's the system information from the GALAXY Tab 2 7.0; the one from the S3 mini looks identical, especially the Version No.
![screenshot_2017-06-19-20-54-58](https://user-images.githubusercontent.com/29523481/27300971-e690096a-5531-11e7-8325-24e12c2022cb.png)

**Comment by pstorch** [comment]
You are on the Version tab. Swipe to the right until you are on the System tab. It's a page with a lot of details as text.

**Comment by Pentatops** [comment]
THese are the system information from the S3 mini:
--- System information ---
Device: GT-I8190 (goldenxx, samsung)
Android version: 4.1.2
Android build: JZO54K.I8190XXAMG4
c:geo version: 2017.05.22
Google Play services: disabled - 11.0.55 (034-156917137)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: disabled (default state)
System language: de_DE
System date format: dd.MM.yyyy
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (1,4 GB free) internal
User storage c:geo dir: /storage/sdcard0/cgeo (1,3 GB free) external
Geocache data: /storage/sdcard0/Android/data/cgeo.geocaching/files/GeocacheData (1,3 GB free) external
Database: /storage/sdcard0/Android/data/cgeo.geocaching/files/databases/data (27,1 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

And now from the GALAXY Tab 2:
![screenshot_2017-06-19-21-02-35](https://user-images.githubusercontent.com/29523481/27301514-b95fef30-5533-11e7-96e5-8b79e7e02d55.png)

**Comment by pstorch** [comment]
Ok, thanks. Unfortunately I don't see any suspicious. 
What happens if you open the Cachelisting in the Browser on these devices?
Or one of the images directly: https://gc.hulmgulm.com/caches/ndins.png
They are hosted somewhere else, not on geocaching.com.

**Comment by pstorch** [comment]
I see they use a let's encrypt SSL certificate and when I see this document https://letsencrypt.org/docs/certificate-compatibility/ it is incompatible with Android < v2.3.6.
I guess this is your problem.

**Comment by pstorch** [comment]
A+ rating: https://www.ssllabs.com/ssltest/analyze.html?d=gc.hulmgulm.com
:+1:

**Comment by Pentatops** [comment]
On one device (S3mini) I opened the cache page with the browser (Crome) from the C:geo cache description page successfully: with pictures. pening the picture directly with crome also works.
On the other device (GALAXY TAB 2) I did the same with the built in browser (no chrome installed) and failed: no pictures. opening the pictures directly wit this browser also fails.

**Comment by pstorch** [comment]
I guess the Chrome browser has some more possibilities and comes with some newer ciphers.

**Comment by Pentatops** [comment]
Thanks for the investigation.
Is there anything I can do to make it work?

P.S.: I have to stop the conversation for tody. It's 11:30PM here in Germany.......

**Comment by pstorch** [comment]
Sorry, I was on the road before. I just realized that my comment above with let's encrypt incompatibilities with Android devices older than 2.3.6 doesn't apply to your devices. Your devices are newer than Android 4.1. 
But maybe it is related. Even 4.1 is rather old. Any chance to install a newer Android version?

Anyone else with an Android 4.1 or 4.2 device with similar problems?

**Comment by pstorch** [comment]
Ok, once again:
The server, where the image is hosted has a rather high security rating and only supports the newer protocols TLS 1.1 and TLS 1.2: https://www.ssllabs.com/ssltest/analyze.html?d=gc.hulmgulm.com
Android 4.1 and 4.2 only supports TLS 1.0 and older protocols: https://dev.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.1.1&key=59 and https://dev.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.2.2&key=60
You need at least Android 4.4: https://dev.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2&key=62

The question is why your "Samsung GALAXY Note 10.1 (GT-N8000) with Android 4.4.2" still has this problem?

**Comment by Pentatops** [comment]
I checked if updates are possible: Not on the GALAXY TAB 2 and on the S3 mini.

**Comment by pstorch** [comment]
If you are tech savvy, maybe Lineage OS is something for you: http://www.lineageosrom.com/2017/02/download-lineageos-galaxy-tab-espressowifi.html?m=1

**Comment by Lineflyer** [comment]
Just flying over this thread:
Didnt the user say, that with his browser he is able to see the images?!
In that case somehow the device can use the newer TLS or the site falls back to older version in this case.
The main question seems to be: Why can the browser load them while c:geo fails on the same device....or am I wrong.

**Comment by kumy** [comment]
This remind me #5473.
Error that case was a mis-ordered ssl certificate chain

> fix their certificate chain by putting the intermediate certificate before the site certificate? As shown by https://www.ssllabs.com/ssltest/analyze.html?d=geokrety.org&hideResults=on they don't use the right order.

**Comment by pstorch** [comment]
@kumy Certificate chain is on possible culprit, but I doubt you can change let's encrypt certificate. 

@Lineflyer the user has two devices on one he tested with internal browsers with same error and on the other device he tested with Chrome and could load the image. I suspect that Chrome brings its own ssl implementation. But the OkHttp library we are using is dependent on the system internal ssl implementation. 

I contacted the owner of the two mentioned caches and informed him about this issue. Maybe he has also an idea.

**Comment by pstorch** [comment]
Maybe we can enable TLS 1.2 in OkHttp on Android 4.1 - 4.4 with this: https://github.com/square/okhttp/issues/2372

**Comment by Pentatops** [comment]
I have already looked at Lineage OS - unfortunately not the right way for me, I think.

Yes, browsing the cache description using CROME works. Using the more simple browser that comes with the device does not work.

**Comment by pstorch** [comment]
At least I can reproduce now. I've setup an emulator with API level 16 (Android 4.1).

I'll get this error:
```
06-20 21:32:41.847 2418-2562/cgeo.geocaching W/cgeo: [OkHttp] Failure (92 ms) GET https://gc.hulmgulm.com/caches/GC6BHT6/naturdenkmal.jpg (javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb98f88b0: I/O error during system call, Connection reset by peer)
06-20 21:32:41.847 2418-2493/cgeo.geocaching W/cgeo: [network--2] Exception in HtmlImage.downloadOrRefreshCopy: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb98f88b0: I/O error during system call, Connection reset by peer
06-20 21:32:41.857 2418-2561/cgeo.geocaching W/cgeo: [OkHttp] Failure (96 ms) GET https://gc.hulmgulm.com/caches/ndins.png (javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb96875f8: I/O error during system call, Connection reset by peer)
06-20 21:32:41.857 2418-2457/cgeo.geocaching W/cgeo: [network--1] Exception in HtmlImage.downloadOrRefreshCopy: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb96875f8: I/O error during system call, Connection reset by peer
```

**Comment by pstorch** [comment]
Looks like the link to the okhttp issue has the solution to our problem.
I could successfully load the images with the given fix.

But I stumbled upon another problem, I have to treat separately.

**Comment by pstorch** [comment]
@Pentatops can you test the Nightly version of c:geo?

**Comment by Pentatops** [comment]
Will be happy to do so.
How to get it? Usually Cgeo tells me if a new update is abailable, but not today.

**Comment by pstorch** [comment]
The Nightly builds can be found here: http://www.cgeo.org/development
You have to install it manually.

**Comment by Pentatops** [comment]
I managed to download and install the file. It's now Version "2017.06.21-NB-bfdf755".
But sorry, didn't solve the problem.
However, I appreciate very much that you take care about even a single user.

**Comment by SammysHP** [comment]
That is still the old version. You'll have to wait for the next nightly build.

**Comment by Pentatops** [comment]
Then... another trial tomorrow.

**Comment by Pentatops** [comment]
Peter,
thanks a lot for your successful investigation. And also thanks to SammysHP, kumy and Lineflyer for your help to solve this issue. It works very well now!
Current version is: 2017.06.22.ND-ed34fdc
Can I expect to have this new feature in the next  or one of the following regular releases?

Regards,

Gunther

**Comment by pstorch** [comment]
@Pentatops thanks for your feedback. Great that it works now. Yes, this will be included in the next feature release.
