### ISSUE TITLE
Improve sort by rating

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6606]
Follow-up of #6601:

A cache with one 5-star rating will be ranked higher than a cache with 20 4.5-star ratings. While this commit solves a specific problem, it is not the solution for a correct rating. We get average rating and number of votes, this should be enough to sort caches in a better way.

http://www.evanmiller.org/how-not-to-sort-by-average-rating.html
https://stackoverflow.com/questions/1411199/what-is-a-better-way-to-sort-by-a-5-star-rating

**Comment by UniQP** [comment]
Regarding Wilson score: How should we handle caches without rating?

**Comment by UniQP** [comment]
Oh, and for the true Bayesian estimate, we would need the average GCVote rating of all caches. Of course, we can just approximate this value (as we currently choose 2.5 as rating for caches without any vote).

**Comment by Bananeweizen** [comment]
This one can be computed with the data we have: http://www.evanmiller.org/ranking-items-with-star-ratings.html

**Comment by UniQP** [comment]
@Bananeweizen Yes, but in the article he recommends at least 23 votes (precise number depending on the actual votes) for a 0.5 star precision.

Currently, I tend towards the true Bayesian estimate with some constant average rating. However, I'm not an expert and we should collect all possible options first.
