### ISSUE TITLE
Remove OpenCycleMap

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6610]
Since a while OpenCycleMap requires an API key to monitor and limit the use of their tiles. In #6512 we added that API key in c:geo.

Now we were contacted by Andy that we have reached the limit of the free plan. Based on the number of requested tiles we would need the "large business" plan for £395 per month. I'm still surprised that there are one million tiles requested per days on average.

We are not able to pay that money so the only solution would be to remove OpenCycleMap completely.

There would be another way, but I'm not sure if that is allowed: Make the key dynamic and let users enter their own key.

**Comment by SammysHP** [comment]
PS: I wonder how many tiles are used from OpenStreetMap. There is a chance that we produce a lot (or too much) of traffic there as well.

**Comment by mucek4** [comment]
I looked at OpenCycleMap. On my 1080p phone we request like 5x8 tiles. So 40 tiles per screen.

**Comment by pstorch** [comment]
Is it an option to provide a setting for the user to use individual keys? I mean is it possible/feasible to let the user apply for their own key? Then it is up to the user.

**Comment by SammysHP** [comment]
It is possible, sure. But I don't think that it is allowed by the terms of use (although I can't find anything about this topic in it).

**Comment by pstorch** [comment]
At least the hardcoded api key in the mapsforge v3 library is externalized. Now we can decide to:
- make a new release (from release or master) with a new api key (configured on CI server). 
- leave it empty and let the user configure a personal api key in settings (a new setting needs to be implemented)
- or remove OpenCycleMap completely

**Comment by Lineflyer** [comment]
What abou just asking them via reply to their mail how to proceed....telling we are a non profit opensource app?We could also ask about allowance of individual keys.
We should also tell them, that we are surprised by the high traffic and that it takes us some weeks to remove it from our app in tbe market if there is no solution.
null

**Comment by SammysHP** [comment]
I'd try the second option (especially after the fact that it is easy to "steal" the key) but I'm sure Andy wouldn't be happy with it.

Not really sure if it makes sense to change the key. Maybe someone uses the old key outside of c:geo, but that might happen again. Or c:geo really creates so many requests, then we have to remove it anyway.

@Lineflyer 
I'm already in contact with Andy but there's no special offer for open-source apps. He knows that we were surprised, but will not wait for several weeks. If there's no change by the end of next week he will just block our key probably.

**Comment by pstorch** [comment]
In case we decide for option 2: do we then block the usage of the OpenCycleMap as long as no key is configured? 
Otherwise we would cause unauthorized requests and the user gets the api key missing text on the map as we had a few weeks ago.

**Comment by SammysHP** [comment]
> In case we decide for option 2: do we then block the usage of the OpenCycleMap as long as no key is configured?

Yes. Isn't there already some code to enable/disable Google Maps that can be used for this?

**Comment by pstorch** [comment]
I'll have a look

**Comment by Lineflyer** [comment]
I am back from vacation and can take care of a release if someone provides the latest status or a go for release.
As mentioned earlier, we could release from `master` branch (AFAIR only incoming translations and some menu optimization was missing).

**Comment by pstorch** [comment]
The PR #6616 is working so far and could be merged. Should we go on with option 2?

**Comment by caigner** [comment]
I use Osmand. It has offline vector map. Would it be possible to use this in cgeo?

**Comment by rsudev** [comment]
Unfortunately not (see #2913 for a discussion). If you want to use offline maps (which I highly recommend), we include the mapsforge library for that and you can use e.g. maps from openandromaps or freizeitkarte (which are also usable by OruxMaps and Locus)

**Comment by caigner** [comment]
Thanks. My solution so far was to export the caches and then import them into Osmand.

**Comment by pstorch** [comment]
This issue here is about the OpenCycleMap where we had issues with the API key, which we can't afford with the amount of traffic needed. Not about alternative maps.

**Comment by Lineflyer** [comment]
My personal opinion is to remove OpenCycleMap completely. 
On one hand I am not sure, whether this is really wanted by them, that users individually aply for a key. On the other hand >90% of the users will not even use this or be not advanced enough to enable it.

**Comment by pstorch** [comment]
@Lineflyer has a point here. The percentage of users who will apply for an api key might be very low. And the usage of individual keys is at least in a gray zone.

**Comment by Lineflyer** [comment]
Is there any other comparable free OSM tile server we could add instead?

**Comment by SammysHP** [comment]
No. Even the "normal" OpenStreetMap server might not be available for us in the future.

**Comment by ControlTheBit** [comment]
Since this discussion is already about several map types; I would suggest to focus only on one or two online maps and **implement a better way to download and use offline maps**. Using offline maps currently needs a lot of reading and finding out which maps work with which themes in c:geo and where to find said maps and themes.

I can only speak for myself, but I don't use any online maps. I have downloaded all countries that I need to go geocaching and I update the maps manually as soon as I notice a difference between the map and being actually there (like missing streets, POIs etc.). I think a lot uf users would like to have something like that too, but they don't how how to use it and where to get maps.

**Comment by caigner** [comment]
I guess every geocacher has at least one or more map apps installed, which downloads map tiles.

Would it be possible to reuse those already existing map tiles?

**Comment by pstorch** [comment]
For example c:geo can reuse the offline maps from Locus.

**Comment by Lineflyer** [comment]
@ControlTheBit 
I agree, but let us not discuss implementation of download offline maps in this issue. This is AFAIR already contained in another issue and we recently chatted with openandromaps about possibilities. 

Another question:
I also remember another issue where it was requested to add a possibility to support various map tile servers by supporting a (standardized?) method for tile requests (i.e. the user only needs to enter the base URL of this server,etc.). Would that be an option as replacement for those users wanting something else than Google and Mapnik?

However let us first see what is the vote of other developers of the core team regarding complete removal of Cyclemap. Please kindly give your thumb up/down on this posting. (up=Remove, down= PR #6616).

**Comment by SammysHP** [comment]
Almost a month, what is the decision?

**Comment by ControlTheBit** [comment]
I just saw that @Lineflyer wrote something here. Must have missed the email... I'm in favor of removing OpenCycleMap.

**Comment by pstorch** [comment]
I didn't want to to vote for or against the OpenCycleMap because I implemented the per user Setting proposal. But I can see pros and cons. 
The idea from @SammysHP is also an interesting and flexible solution. But it needs more knowledge by the user on how to set up these URL templates.

**Comment by Lineflyer** [comment]
Due to upcoming decision for a next feature release (#6595) we should indeed decide what to do in a next step. 
I also prefer removing it (as already written above) and consideration the idea from @SammysHP as a good way forward. The first step would however be to remove the problematic source before issueing the next release.

**Comment by SammysHP** [comment]
We should add a note in the changelog why it was removed (and maybe link to a new FAQ entry).

@pstorch 
Yes, it requires more knowledge but we can link to a FAQ entry which describes the setup of a map source.

**Comment by Lineflyer** [comment]
> We should add a note in the changelog why it was removed (and maybe link to a new FAQ entry).

Added as https://github.com/cgeo/cgeo.github.io/issues/146

**Comment by pstorch** [comment]
Ok, so let's simply remove the OpenCycleMap for now and open another issue with @SammysHP 's idea. Maybe I can rework the PR in this direction later on.

**Comment by SammysHP** [comment]
Got another mail from Andy. He will remove the keys in the next few days so we should release the new version Thursday or Friday.

**Comment by Lineflyer** [comment]
What will happen if the key is removed?

**Comment by pstorch** [comment]
Users see an empty map
