### ISSUE TITLE
Identify in user agent

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6611]
In #1025 we decided to use a generic user agent because we didn't want to be tracked by Groundspeak and to force a desktop version of the website (for parsing).

Meanwhile we [send an "app=cgeo" parameter](https://github.com/cgeo/cgeo/blob/7b8ac7e898055878a6d645913bc2451ff2836ce2/main/src/cgeo/geocaching/connector/gc/GCMap.java#L69) for GC tile access, so we might add "cgeo" to the user agent as well. That would allow other services to measure the load that c:geo creates on their servers.

**Comment by SammysHP** [comment]
I just noticed that the user agent is used only for some connections. For example connections from Mapsforge are not routed through our OkHttpClient instance which injects the hardcoded user agent.

**Comment by pstorch** [comment]
The mapsforge libraries have their own way of downloading the tiles. Mainly through simple URL.openConnection().
Mapsforge V6 has support to set the user agent, so we could set our own user agent. The V3 library would need to be extended to support this (or we hardcode it in our fork).

I never looked into the user agent setting in c:geo.
We only distinguish between these two:
```
    private static final String PC_USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1";
    /** Native user agent, taken from a Android 2.2 Nexus **/
    private static final String NATIVE_USER_AGENT = "Mozilla/5.0 (Linux; U; Android 2.2; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1";
```

**Comment by Lineflyer** [comment]
Is this request based on a request we got from one of the services we support or just an idea?

**Comment by SammysHP** [comment]
Almost all services require some sort of identification, either API key, referer or user agent. And then there's the thing with honesty, of course.

I suggest to use standard user agents from modern web browsers (mobile and desktop) for compatibility and add "cgeo" at a proper place.

**Comment by pstorch** [comment]
Some interesting discussion about user agents using the android webview: https://mobiforge.com/research-analysis/webviews-and-user-agent-strings

Facebook for example appends its identifiers in [ ] at the end.
Normally the user agent is build like this: "product/version (comment) product/version (comment) ..." where comments and versions are optional.

So we could extend our user agent strings  and append `c:geo/2017.05.22` for example.

**Comment by Bananeweizen** [comment]
I like the suggestion of adding our own marker at the end. And I'm in favour of updating the hardcoded values to something that is more from this century. ;)

**Comment by pstorch** [comment]
I tried to determine the user agent from the webview as suggested here: https://stackoverflow.com/questions/3626071/retrieve-user-agent-programmatically/5261472#5261472

I got this:
```
Mozilla/5.0 (Linux; Android 7.1.1; ONEPLUS A3003 Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36
```

I think this is more accurate than the hard coded strings. Do we still need the `Settings.getNativeUa()` setting? It's the Android browser setting option we c:geo has.

**Comment by Bananeweizen** [comment]
I'm not sure about removal of the native setting. Remember issues like #4082 where the network proxy modifies the actual HTML data? It might behave different, depending on the user agent...

**Comment by pstorch** [comment]
Thanks for pointing to the issue with the network proxy. Interesting read. But looking at the history the issue #1843 introduced the native android user agent setting.

I would suggest to use the built in WebView user agent string as in the previous comment (+ cgeo extension) as default and provide a fallback with a PC browser user agent string. So actually inverting the current setting. The default should identify the mobile device and not emulate a PC browser. What do you think?

**Comment by Bananeweizen** [comment]
Sounds reasonable to me, as it more closely to the actual facts, and it should also be a more normal and mature use case nowadays.

**Comment by Lineflyer** [comment]
After discussion in #6624 I tend to follow @SammysHP suggestion to have a **static** mobile user agent and maybe append some identification for cgeo to that.
Would that be possible?

This keeps reproducible conditions in server communication, which would otherwise be potentially depending on the device.

**Comment by pstorch** [comment]
> After discussion in #6624 I tend to follow @SammysHP suggestion to have a static mobile user agent and maybe append some identification for cgeo to that.
> Would that be possible?

Sure, which one?

Should we still go for the reversed logic? Having a mobile user agent as default and a desktop as fallback? Or should we keep the logic we currently have? I'm not sure anymore. Maybe we should just keep it as it is (which we know it works).

**Comment by Lineflyer** [comment]
> Having a mobile user agent as default and a desktop as fallback? Or should we keep the logic we currently have? I'm not sure anymore. Maybe we should just keep it as it is (which we know it works).

I am not sure about the consequences to the page contents if we switch from desktop UA to mobile UA as I am no expert for this. From my mobile browser I can see, that GC uses a modified design when using the mobile UA, does this also mean, that the important fields for our parsing will/might change or is this totally unrelated?

**Comment by SammysHP** [comment]
What do you think about

```
Mozilla/5.0 (Linux; Android <android-release>) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.0.0 Safari/537.36 cgeo/<cgeo-release>
```

**Comment by Lineflyer** [comment]
Sounds worth a try.
