### ISSUE TITLE
GeoKrety reaching 5 digits (GKFFFF - 65535)

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6612]
GeoKrety service will reach five digits numbering soon. [about 1700 numbers left].

I think we have something to do on our side to handle 4 to 5 numbering.
I can think of:
 * int to hexa conversion function
 * (maybe) intents

**Comment by Bananeweizen** [comment]
I don't think so. The manifest doesn't contain any regular expression or similar length-indicating data (just path and URL patterns, which stay the same). The valid pattern already deals with 4+ characters, the conversion function is done as substring to int conversion.

Of course, the best way is to just add a test case to the related unit test which proves all that. :)

**Comment by kumy** [comment]
Still that function: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java#L340

**Comment by Bananeweizen** [comment]
Nope. That just adds zero padding up to 4 characters. It does not conflict with converting a number that has more than 4 characters.

**Comment by kumy** [comment]
Thanks. Let's close.
