### ISSUE TITLE
Parse DNF caches on map

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6614]
Not sure when this was introduced, but gc.com show DNF logs on the map:

![20170623_154620](https://user-images.githubusercontent.com/922874/27484898-27522d1a-582b-11e7-9451-9d30601f8844.png)

These caches are parsed as unknown, virtual, event, earth cache – mostly random.

See also #3206.

**Comment by UniQP** [comment]
> Not sure when this was introduced, but gc.com show DNF logs on the map

Corresponding release note: http://forums.groundspeak.com/GC/index.php?showtopic=344662

**Comment by SammysHP** [comment]
That's the release note for the app, here's the one for the website: http://forums.groundspeak.com/GC/index.php?showtopic=344674

**Comment by Lineflyer** [comment]
AFAIR we also have an issue for parsing it while parsing the cache details (as since >1 year the DNF status is also present on the web page). This would make sense to complete the consistency as we already have a (blue) DNF icon for offline DNF caches.

**Comment by Lineflyer** [comment]
Link to #3206

**Comment by UniQP** [comment]
After the [last update](http://forums.groundspeak.com/GC/index.php?showtopic=344929), unfound caches with changed coordinates also get an extra icon, independent of their original cache type.

**Comment by jelleruben** [comment]
Hello, my issue was duplicate. And was closed. I see that this ticket is from a year ago.

II am curious about the status of this issue.

**Comment by SammysHP** [comment]
@jelleruben http://www.cgeo.org/callfordevelopers

**Comment by eddiemuc** [comment]
I put this one on my list too, but I am afraid it is already quite a long one. So if someone wants to start inbetween, don't hesitate (just give me a short notice please)

**Comment by Lineflyer** [comment]
The wrong parsing which is the main issue here (in contrast to #3206) is no longer happening as we meanwhile do no longer use any graphical parsing by colors but use the "map API". Therefore this issue can IMHO be closed.

The parsing and showing of DNF caches is covered by #3206.
