### ISSUE TITLE
Owner cannot add "Needs Maintenance" log to his own Geocache 

### ISSUE THREAD

**Issue by caigner** [cgeo/cgeo#6620]
As owner I need to be able to add a "Needs Maintenance" (NM) log to my own Geocaches. 

This is necessary because some Geocachers report that something is wrong with a cache without adding a NM log. 

This helps to keep track of all my own caches which need some care. 

It seems, that NM was removed from the log menu. Please restore it to the state as it was before. 

Thank you! 
Christian

**Comment by pstorch** [comment]
That is not possible on geocaching.com either. As owner you can disable the cache if it needs maintenance.

**Comment by caigner** [comment]
Not possible? It was possible in the past. I know because I did it. 

So Groundspeak changed it. Sad.

**Comment by pstorch** [comment]
It was changed some weeks ago in #6465. 
Here is the announcement from groundspeak about it:
http://forums.groundspeak.com/GC/index.php?showtopic=343632

I'll close it then.

**Comment by caigner** [comment]
Ok. I guess I have to use a second account to log my own NM logs. Thanks for your answer!
