### ISSUE TITLE
Feature Request: multi user / switch user

### ISSUE THREAD

**Issue by caigner** [cgeo/cgeo#6621]
As I just learned it is not possible anymore for a owner to log "Needs Maintenance" (NM) for his own geocaches. Therefore I registered a second account on geocaching.com which I want to use only to log NM.

Also, my girlfriend has her own account, and sometimes, when she forgot to take her mobile phone with her, she wants to use my phone to log a geocache. But of course she doesn't remember her password.

Would it be possible to add a multi user feature and make it possible to switch users fast and simple by selecting a user from a list of saved users within cgeo?

Thanks,
Christian

**Comment by Natureshadow** [comment]
>Also, my girlfriend has her own account, and sometimes, when she forgot
>to take her mobile phone with her, she wants to use my phone to log a
>geocache. But of course she doesn't remember her password.

If you let another person use your phone, you of course give them a separate Android user. In that user, you would have configured c:geo with the correct account.

**Comment by rsudev** [comment]
I expected this request to come up when I saw your comment on the NM logs issue :)
While it sounds easy on the outset, I think it is not so easy in reality, as quite some data we hold in c:geo is related to the user (found status and dates, offline logs to name a few).
I have no personal experience with multiple users in Android (as per suggestion by @Natureshadow) and if this plays well with our storage layout in all cases, but it sounds like a good way forward IMO.

**Comment by caigner** [comment]
Switching Android users is not what I want to do. I prefer a solution within cgeo.
I think, if I can go to Preferences menu and change the username/password manually, then there must be a software solution as well.

**Comment by Natureshadow** [comment]
>Switching Android users is not what I want to do. I prefer a solution
>within cgeo.

Letting someone else use your phone without a separate user account is bad behaviour, be it your girlfriend or not.

Others expect communication with you to be private, and its not their girlfriend, so they do have secrets.

**Comment by pstorch** [comment]
As @rsudev pointed out, there will be a lot of hassle inside c:geo to support multi user. You will mix up your logs, field-notes, found status, ...
I strongly vote against it.

**Comment by samueltardieu** [comment]
You are asking to implement a major feature in cgeo while you have a perfectly working and cleaner solution at your disposal already. Android users have precisely been designed for this purpose (let several people share a device when necessary) and guarantee data isolation. Implementing user switching in every application would be a loss of time and energy.

To give you an example, in cgeo, that would require separating login info / found status / logged status / offline logs / friends logs / disk cache into multiple users for a very limited benefit.

Concerning your usage, I would suggest:

- using a second user on your device for your girlfriend to let her switch very rapidly to her cgeo account;
- using the website when you want to go against geocaching.com choice not to let cache owners log "needs maintenance", I don't think we should facilitate this.

**Comment by caigner** [comment]
Thank you for all your input and considerations.

Right now I use the website to log in with my second user to log NM.

I just thought it would be convenient to have this possibility inside cgeo. But well, you don't always get what you wish for, right? ;-)

Right now cgeo is the best app for geocache users. As I am also a geocache owner, I look at it from the other side as well. For me cgeo more and more becomes a tool for maintaining my 50+ geocaches. And I plan to hide a lot more in the future. So maintenance and keeping track of it is a big issue for me.

**Comment by pstorch** [comment]
As @samueltardieu pointed out, that geocaching.com 's choice is not to let owners log "needs maintenance". Maybe there is a reason behind it and you as owner should not do it. Use "disable" if the cache can't be found or write a note instead. "Need maintenance" is for cachers to inform the owners.

**Comment by samueltardieu** [comment]
Closing then.

**Comment by Tokolino** [comment]
I don't know if anyone is reading this as the topic is already closed, but I have the same requirement for a different reason:

My gf and I both have their own gc-accounts, but only hers is premium member. If I want to get the premium member caches on my device, I have to switch the connection to her account, download the pocket query, update the caches and then reconnect with my user.

So from this point of view I don't want to use it as second profile, I only want to use it to share the premium benefits inside the geocaching team.

Regards,
Thorsten

**Comment by Lineflyer** [comment]
We decided quite some time ago to not add a specific multi user support.

Regarding your use case:
Why don't you just send the pocket query GPX via other means (e.g. mail) to your device and just import it into c:geo?

**Comment by Tokolino** [comment]
> We decided quite some time ago to not add a specific multi user support.

I know, but this was based on a different use case ;-) .
 
> Regarding your use case:
> Why don't you just send the pocket query GPX via other means (e.g. mail) to your device and just import it into c:geo?
I don't think that pictures are included in the GPX? So to be able to update the cache I think I still need the premium access. 

What I have to do now is: Change the login, quit and restart completely. Then I am logged on as a different user. Anything that makes it more difficult than that is not an option. 
It would be fine for me if there was just a possibiliy to save username/password in a list or so so that I can quickly reuse them when I switch users. (And it would be great if cgeo would really log on as a different user when I do so, and not just pretending that it does ;-), but thats a different story...)
