### ISSUE TITLE
Initial position when offline should be last known position

### ISSUE THREAD

**Issue by LouisStrous** [cgeo/cgeo#6626]
When starting c.geo when it has no location fix (yet), then the map is always centered on my home location as defined in my geocaching.com account (see http://www.cgeo.org/faq#default-location).  However, it is far more likely that I am interested in the area around the last known or shown position than that I am interested in the area around my home location (if these are different).

Please adjust c.geo so that if it has no location fix then it shows the map centered on the last known (GPS) or shown (map) position, or even on the location of the last reviewed geocache (in c.geo's History list).  All three of these are more likely to be of interest to me than the area around my home location.

Some scenarios in which this matters:

1. I am on vacation in a far-away location where I have to limit roaming charges and conserve battery power.  Every time I go outside to go geocaching, I turn on c.geo and GPS.  While it has no location fix yet, c.geo shows the area around my home location, which is far from my current location.  I have to wait until it acquires a location fix before I can easily start looking at nearby geocaches -- or I have to laboriously navigate on the map from my home location to my current location again.
2. When I'm inside, I have location services turned off to conserve battery power.  When I turn on c.geo to review recent caches or to plan caches for the remainder of the day, c.geo again shows the area around my home location instead.

Navigating on the map all the way from my home location to my current location is tedious, because I need to zoom out a lot to be able to get to my current location quickly, but then the geography is obscured by all of the geocache icons covering the entire area, so it is hard to tell to where to zoom in again.  And if I want to go via the most recent cache in the "History" folder of the "Stored" caches list as a shortcut, then I have to wait until the "Stored" caches list displays, which takes a long time if it has 10,000 caches in it, as it did during my last vacation.

If the location fix is lost while c.geo is on, then c.geo seems to assume that it is still at its last known position -- at least, the map then doesn't suddenly jump to my home location.   It would be good if c.geo acted the same way if it lost its location fix because c.geo was turned off temporarily.

##### Version of c:geo used:

2017.05.22

##### Is the problem reproducible for you?

Yes, very much so.  It isn't a recent problem, either.  c.geo has acted like this for as long as I've used it.

Regards,
Louis Strous

**Comment by SammysHP** [comment]
IIRC we discussed this a few times and decided to not add additional location tracking and caching. This is already done by the Google Play Services.

**Comment by LouisStrous** [comment]
If Google Play Services took care of this then I wouldn't consistently have such an irritating c.geo startup experience when I'm far from my home location.

Are you against location caching on principle, or would you accept it if I implemented it myself?

As a (presumably) easier alternative, how about using the location of the most recent cache from the "History" list as the backup initial position, instead of the home location?  That requires no additional location caching, and is likely to be closer to my current location than my home location is when I'm out geocaching.

**Comment by Lineflyer** [comment]
IMHO we already use the last known position before falling back to home coordinates. So I think this is not a general problem but a device specific one.

@LouisStrous 
Can you please post your system information from About c:geo - Swipe to "System"?

**Comment by LouisStrous** [comment]
From the system information as reported by c:geo I see that I have
Google Play Services disabled after all.  I suppose it corresponds to
what my phone calls "Google Location History", which I have turned off
for privacy reasons -- I don't think Google (and whoever else has access
to that data) needs to know where I am. 

I've done some more experimenting.  c:geo remembers the last map
position even on my phone, but if the "center map on current location"
function is on then it immediately recenters the map on what it thinks
is the current location -- which on my phone is the home location if no
better location is yet available.  If that "center" function is off when
c:geo starts up, then it shows the map around the last map position. 
This is just what I want, except that it requires me to turn off the
"center" function just before turning off c:geo so that it is still off
when I start c:geo and open the Live Map view again, and I doubt that
I'll remember to do that every time. 

So, any one of the following changes to c:geo would make me happy: 

1. Where the current c:geo decides to use the home location, make it use
the last map position instead.  c:geo already has access to that last
map position even on my phone with Google Play Services turned off, so
this might require only a small code change. 

2. Make it possible to turn off the "center map on current location"
function before opening the Live Map. 

3. Add a configuration option to choose whether the "center" function
should be on or off or unchanged when c:geo starts up. 

The first option is by far the most desirable from my perspective, and
hopefully also the easiest to implement. 

Lars schreef op 2017-07-03 11:08:

> IMHO we already use the last known position before falling back to home coordinates. So I think this is not a general problem but a device specific one. 
> 
> @LouisStrous [1]
> Can you please post your system information from About c:geo - Swipe to "System"? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

  

Links:
------
[1] https://github.com/louisstrous
[2] https://github.com/cgeo/cgeo/issues/6626#issuecomment-312591668
[3]

**Comment by SammysHP** [comment]
Location history is not related to Google Play Services which can be enabled/disabled in the preferences of c:geo.

I'd like to close this issue if there are no objections from other devs. We decided to not implement location caching ourselves.

Btw: Just using the last position won't help. I often start c:geo only nearby caches, so it would be wrong most of the time.

**Comment by Lineflyer** [comment]
I am also in favor of closing this issue, mainly as I also don't think location caching within c:geo would be reasonable.

Nevertheless here is some feedback regarding the requested changes (also providing workaround and explanations):

> From the system information as reported by c:geo I see that I have Google Play Services disabled after all. I suppose it corresponds to what my phone calls "Google Location History", which I have turned off for privacy reasons -- I don't think Google (and whoever else has access to that data) needs to know where I am.

As you did not post your system information I cannot provide an exact answer why PlayServices are not active. However it is normally independent of "Google Location History" tracking.
Please check c:geo Menu - Settings - System if you can enable Google Play Services and test the behaviour using this option.
Note: As previously mentioned, please also check that you enabled all location services on your device (GPS, mobile network, etc.).

> So, any one of the following changes to c:geo would make me happy: 
> 1. Where the current c:geo decides to use the home location, make it use the last map position instead. c:geo already has access to that last map position even on my phone with Google Play Services turned off, so this might require only a small code change. 

Without PlayServices we do not have a last known position.
This would mean, we would have to incorporate functionality of PlayServices within c:geo which we cannot do in same quality as they do it (e.g. thousand of different device types might behave different).

> 2. Make it possible to turn off the "center map on current location" function before opening the Live Map. 

Live means its with live caches and live location.
If you do not have a location (or want to look at the map of a distant location) you could either open a map for a list of saved caches or search for a location and map the search results.
Once you are in the resulting map view you can manually enable live mode if desired.


> 3. Add a configuration option to choose whether the "center" function should be on or off or unchanged when c:geo starts up.

The center function should remember the last status (=unchanged) currently.
This was decided to be the best option to cover several use cases (btw also for the case where the device does not have a location information available).
