### ISSUE TITLE
Two instances when started from k9

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6630]
A friend just demonstrated on his phone that he can open a cache from a mail in k9 and then start cgeo normally, and afterwards there are 2 instances running (as you can verify by editing some data without storing to database in one instance). Can we prevent this by adding some flags to our activities?

**Comment by pstorch** [comment]
An Activity can have the attribute `android:launchMode="singleInstance"` in the manifest file.

**Comment by Lineflyer** [comment]
Duplicate of #6902
