### ISSUE TITLE
Offline log created while posting online log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6633]
##### Detailed steps causing the problem:
- Have an offline "found" log stored for a saved cache (maybe optional)
- Open the offline log and send it online
- While the log is being sent provoke an action to get the activity into background (e.g. change to another app, go to home screen, (maybe) rotate device)

##### Actual behavior after performing these steps:
- A toast appears "Logtype has been changed"
- Looking into the caches logbook you will see your "found" log online and an additional "did not find" log stored offline

##### Expected behavior after performing these steps:
- Online log is posted
- Offline log is removed from device

##### Version of c:geo used:
2017.05.22

##### Is the problem reproducible for you?
Yes (beside unclear about "maybe" steps)

**Comment by alan666notb** [comment]
This is something I reported earlier as issue #6171
It happens to me if I click the 'arrow' to send a log and then switch off the screen while it happens.
When I look again there is an online log plus an offline log as you also see.

**Comment by Lineflyer** [comment]
Thanks @alan666notb  Reopened the original issue.
