### ISSUE TITLE
Configurable MapTileDownloader

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6641]
Follow up from: https://github.com/cgeo/cgeo/issues/6610#issuecomment-315747226

@SammysHP:
> I'd like a flexible solution where a user can add and remove map sources in the preferences. We would need only "name" and "url", e.g.
>
> ```yaml
>name: OpenStreetMap Mapnik
>url: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
>```
>
> With this method it would also be possible to use an API key (as a GET parameter) or add Google Maps:
>
>```yaml
>name: Google Maps
>url: https://mt.google.com/vt?&x={x}&y={y}&z={z}
>```

**Comment by pstorch** [comment]
Should it be possible to configure several of them or just one?
It might be more complex to implement the Settings if we want several `name`/`url` pairs.

**Comment by SammysHP** [comment]
If we implement this, it should be possible to add several sources.

**Comment by Lineflyer** [comment]
Closing in favor of #3954
