### ISSUE TITLE
Remove all except crosslisted?

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#6642]
Does “Remove all” remove a cache from the current list from *all* lists it’s on?

While this is useful for the history, for other lists I may wish to delete only the current list, keeping caches that are _also_ in other lists on the device.

**Comment by Natureshadow** [comment]
>Does “Remove all” remove a cache from the current list from *all* lists
>it’s on?
>
>While this is useful for the history, for other lists I may wish to
>delete only the current list, keeping caches that are _also_ in other
>lists on the device.

Just tested (you could have tested that as well, eh ☺?).

No, Remove All only removes caches from the current list; cache data itself is only removed if not on any lists anymore.

**Comment by mirabilos** [comment]
Dominik George dixit:

>Just tested (you could have tested that as well, eh ☺?).

I’ve seen it remove the caches entirely when called from
the history, or at least I *think* I did, that’s why I
was confused, and for lack of manual I thought it better
to ask.

**Comment by Natureshadow** [comment]
On 19 July 2017 11:09:33 GMT+02:00, mirabilos <notifications@github.com> wrote:
>Dominik George dixit:
>
>>Just tested (you could have tested that as well, eh ☺?).
>
>I’ve seen it remove the caches entirely when called from
>the history, or at least I *think* I did, that’s why I
>was confused, and for lack of manual I thought it better
>to ask.

You are right. History is a separate thing. What remove all does for lists is called clear history in the history view. Seems a bit confusing.

Remove all in the history indeed deletes the caches entirely.

**Comment by mirabilos** [comment]
Dominik George dixit:

>You are right. History is a separate thing. What remove all does for
>lists is called clear history in the history view. Seems a bit
>confusing.
>
>Remove all in the history indeed deletes the caches entirely.

Ah okay.

The “Clear History” thing has been there before multi-list support,
so it somehow makes sense, and “Remove all” always does the right
thing, it’s just confusing enough it should be documented in the
user’s manual… wait, what user’s manual? ;-)

**Comment by pstorch** [comment]
The wording is not very clear here. Maybe the "Remove all" an a concrete list should be "Remove all from list".

**Comment by Lineflyer** [comment]
I think the wording is reasonable as it is. AFAIR we changed it from "Delete" to "Remove" while introducing multi-list.
So as for all other list actions they are only applied to the active list. Otherwise you would have to rename "Move all" to "Move all from list" which is unnecessary.

**Comment by mirabilos** [comment]
Lars dixit:

>I think the wording is reasonable as it is. AFAIR we changed it from
>"Delete" to "Remove" while introducing multi-list. So as for all other
>list actions they are only applied to the active list. Otherwise you
>would have to rename "Move all" to "Move all from list" which is
>unnecessary.

That’s fair. I even think that both the current labels and what they
do are good… except perhaps “Remove all” in History, whose label can
be confusing, but once explained makes fully sense.

I’d use “Unlink all” in all-except-history as label, except that that
would confuse all non-technical people (and some a-bit-technical ones)
which are the majority of geocachers, so I’d suggest leaving it as-is.

**Comment by Lineflyer** [comment]
> I’d use “Unlink all” in all-except-history as label, except that that would confuse all non-technical people (and some a-bit-technical ones) which are the majority of geocachers, so I’d suggest leaving it as-is.

Mmh...
At the moment I am confused myself what "Remove all" in History is exactly doing in the background.
@pstorch I am sure, you remember this.

**Comment by pstorch** [comment]
@Lineflyer "Remove all" in History removes the caches from all lists.

**Comment by Lineflyer** [comment]
@pstorch 
Oh, then the behaviour is different than on a particular list, but I guess it is using the same string at the moment?! In this case we could think about having a seperate string for this item when used on the history list, which could be "Delete from all lists".

**Comment by mirabilos** [comment]
Funnily enough, I actually think the current wording is good _if_ it’s documented well. It makes sense when viewing the history not as a regular cache list, and all alternative suggestions both that have come up here and which I could come up with would be *much* too wide for the menu even in English (not to consider translations, such as German which is usually longer).
