### ISSUE TITLE
"unusual" or "special" log type?

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6643]
Submitting "needs maintenance" log for GC cache gets a warning about submitting an "unusual" log type. 

Wouldn't "special" be a more meaningful word? 
It may also help if the text clearly stated that such "special" log type incurrs additional actions on the cache (like setting a flag, notifying owner, etc)

Thank you.

**Comment by Lineflyer** [comment]
I agree. Will change the resource string accordingly to trigger retranslation if no one objects.
