### ISSUE TITLE
Multiple cache IDs for send2cgeo

### ISSUE THREAD

**Issue by arminus** [cgeo/cgeo#6646]
##### Detailed steps causing the problem:
send2cgeo only accepts single cache IDs. This leads to possibly a lot of browser windows/tabs remaining open after a list of caches has been sent (e.g. from the respective GSAK macro or similar). Closing these windows via JS on the client side seems not possible, because the time required until the request is handled is undefined and getting the result seems impossible due to CORS issues.

##### Expected behavior after performing these steps:
additional parameter for send2cgeo to handle a ; etc. delimited list of cache IDs

**Comment by SammysHP** [comment]
Please open an issue in the send2cgeo repository. https://github.com/cgeo/send2cgeo

**Comment by Lineflyer** [comment]
My fault, I directed the user to here.  
@arminus Sorry, can you open it as requested by @SammysHP. Thanks!

**Comment by arminus** [comment]
Actually, this is a duplicate of https://github.com/cgeo/send2cgeo/issues/14 - which also contains a workable solution for me (but not for the gsak macro)
