### ISSUE TITLE
PQ import overwrites logbook

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6647]
Discussed here:
https://geoclub.de/forum/viewtopic.php?f=155&t=78575

Scenario:
- Have caches stored on device
- Import PQ which contains all/some of the stored caches

What will happen to the additional geocache data (spoilers, static maps, pictures) in this case?
Assigning myself for testing this scenario, as I am unsure how this is handled.

According to @rsudev (in the linked forum) the data should be preserved and only new/changes items added.

**Comment by Lineflyer** [comment]
I found the time to retest this case as follows:
- Search for GC-Codes and store the caches for offline use in c:geo lists
-Check all expected data is present (Complete logbook, GC-Vote, Favorite points, Pictures, Static maps,  Personal note, etc.)
- Import a PQ (Source: gc.com) via c:geo PQ-import containing the same caches into the same list
- Check all expected data is still present

Result:
Most of the above mentioned data is kept, however the logbook is overwritten by the reduced logbook (5 entries) imported from the PQ. Furthermore also the pictures associated with the (5 still existing) log entries are no longer available.

Interpretation:
Listing pictures and spoilers are not deleted (original topic from the forum), which is a good thing.
I assume, that the behaviour regarding the log entries is intentional as the import might contain more recent information, than the stored logbook infos. 
But it is however also clear, that part of the information is lost (35 most recent log entries after saving with c:geo versus 5 most recent log entries from the PQ).
I don't know whether we could or should find any better solution for merging the stored logbook with the imported logbook?!

**Comment by moving-bits** [comment]
@Lineflyer 
Is this issue still relevant?
For importing GPX (as a PQ is) we do now preserve the existing logs, but I'm not sure if that covers all scenarios and data described above.

**Comment by Lineflyer** [comment]
will check.

**Comment by fm-sys** [comment]
Initial request is implemented meanwhile, so let's close here. Can still be reopened if something is missing...
