### ISSUE TITLE
Keeping geolocation active while navigating

### ISSUE THREAD

**Issue by frodeseverin** [cgeo/cgeo#6649]
##### Detailed steps causing the problem:
- Open cache details
- Start navigating, display on internal map
- Look about an search for cache
- Lock screen for some reason
  - Use both hands to search
  - Climb
  - Hide from muggles
  - Protect from rain
  - Etc.
- Open c:geo again

##### Actual behavior after performing these steps:
Geolocation has been paused while device is locked. Thus there is a need for device to re-establish GPS-lock. This means precision/accuracy of location service is lost, and device needs time to regain wanted accuracy. This situation is more pronounced for high latitudes and sparse cell tower coverage, as is often the case in Norway. Typical radius for GPS on start of navigating is 30 metres or worse. Not so useful for Geocaching. Typical radius after ten minutes of active geolocation service >2.5 metres. Radically more useful. 

##### Expected behavior after performing these steps:
An option to keep geolocation active while navigating internally in c:geo would be very helpful. Then i would not have to keep the app active at all times whilst looking about.
A separate option to enable geolocation when running in background would also be useful for backcountry caching.

I tested this by forcing geolocation with another app in background, WhereYouGo. This app has options to keep geolocation active in background or when device is locked.

##### Version of c:geo used:
2017-07-24

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: F5121 (F5121, Sony)
Android version: 7.0
Android build: 34.2.A.2.69
c:geo version: 2017.07.24
Google Play services: enabled - 11.3.02 (448-161239932)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: nb_NO
System date format: dd.MM.y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (664,7 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (664,7 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (664,7 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (9,3 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Innlogging fullført) / BASIC
   opencaching.de: Logged in (Innlogging fullført)
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---

```

##### Other comments and remarks:
WhereYouGo has implemented the requested features.

**Comment by SammysHP** [comment]
This has been discussed in #6549.
