### ISSUE TITLE
Export to locus doesn`t tranfers listing hint etc

### ISSUE THREAD

**Issue by xpokor02** [cgeo/cgeo#6652]
##### Detailed steps causing the problem:
open saved 
from menu chosse show on map and export to Locus 

##### Actual behavior after performing these steps:
caches are transferred but without listing etc

##### Expected behavior after performing these steps:
all info should be there

##### Version of c:geo used:
2017.7.24

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
Is this bug new for you in the recent version or already existing before?

**Comment by xpokor02** [comment]
I don`t know as I tried it first time maybe it is not bug at all

**Comment by Lineflyer** [comment]
Anyone familiar with the API towards Locus?
I rarely use it, so I cannot tell about the intended functionality.

**Comment by Lineflyer** [comment]
I just retested this with 2018.08.04-NB without a problem:
- Open list (of 7 caches in this case)
- Select "Show on map" -> "Export to Locus"
- Check that listing infos are shown in Locus
