### ISSUE TITLE
Map view of List shows own/found caches when it shouldn't.

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#6653]
##### Detailed steps causing the problem:
- Create a new List with some found and some unfound caches
- Open the List
- View the List on the map by clicking the Map icon
- Select "Hide own/found caches" in Map settings
![image](https://user-images.githubusercontent.com/1811963/28646909-76070bd0-7264-11e7-82a7-750e3221f900.png)

##### Actual behavior after performing these steps:
The own/found caches are still visible

##### Expected behavior after performing these steps:
They should be hidden

##### Version of c:geo used:
2017.07.26-NB

##### Is the problem reproducible for you?
Yes

**Comment by SammysHP** [comment]
Stored caches are always shown, independent of that filter. This was by design because the user has explicitly decided to store the cache and might wonder why it isn't shown. IIRC there is already an issue about this.

**Comment by Lineflyer** [comment]
That is correct as described by @SammysHP 
Before we explicitly changed this years ago, we have often been adressed by users wanting e.g. to map a list of their found caches list stored in c:geo and wondering about an empty map returned.

AFAIR the found will vanish as soon as you set the map to live mode.
