### ISSUE TITLE
Only unstored caches on live map view are stored in selected list

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#6654]
##### Detailed steps causing the problem:
- Zoom into an area on the live map where you have both stored and unstored caches
![image](https://user-images.githubusercontent.com/1811963/28647520-088b4bb2-7268-11e7-9489-4944c59d90e0.png)

- Choose Store Offline in menu
![image](https://user-images.githubusercontent.com/1811963/28647539-2659a580-7268-11e7-999c-587ba290f74c.png)

- Create a new list or select an existing list

##### Actual behavior after performing these steps:
Only the caches that are not already stored in any other lists are added to the new list.
The cache with the offline log is also added to the new list, even if it has a "stored" icon

![image](https://user-images.githubusercontent.com/1811963/28647611-78120232-7268-11e7-82a8-e2d6758b8c82.png)

##### Expected behavior after performing these steps:
All caches in the map view should be added to the new list.
Since several lists can co-exist nowadays the already stored caches should be added to the new list as well.

##### Version of c:geo used:
2017.07.26-NB

##### Is the problem reproducible for you?
Yes

**Comment by Lineflyer** [comment]
I somehow agree, that the behaviour should be changed.
I wouldn't call it a bug, so I labeled it as "Feature Request".
