### ISSUE TITLE
Group PQs by download availability

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6659]
Currently PQs are sorted by name without respecting if the are downloadable. All PQs that are available for download should be grouped at the top.

**Comment by pstorch** [comment]
Only sort first by downloadability and then by name or also visually separate them?

**Comment by SammysHP** [comment]
I'd sort first by name and then by downloadability (assuming a stable sort algorithm). ;)

Yes, just sorting should be enough. The download button is already a good visual distinction.

**Comment by pstorch** [comment]
The other way around? First by name and then by downloadability?

**Comment by moving-bits** [comment]
Let's close here, as we have a switch meanwhile in the PQ list to display only downloadable (vs. all).
