### ISSUE TITLE
Coordinate calculator is illegible

### ISSUE THREAD

**Issue by Natureshadow** [cgeo/cgeo#6660]
On my LineageOS 14 device, using the lighttheme, the coordinate calculator is illegible. The variable names are white on a very light background.

**Comment by Lineflyer** [comment]
Confirmed in General fordern white theme.

**Comment by S-Bartfast** [comment]
Hmm, fair enough.

I actually remember being concerned about this at the time I wrote it as I wasn't able to find what the default colour for the button text was.  I ended up setting the regular background of the button to `R.drawable.button_background_kitkat` (which may very well not be quite right either) but I wasn't able to find anything even remotely appropriate for the text, so just opted for `Color.WHITE` (which looked fine with the default theme).

How do the Latitude and Longitude buttons (the "N" and "E" buttons) look?  These buttons have there colour set as:
> `<item name="android:textColor">?text_color</item>`
I wasn't able to nail down exactly what that colour was but if it works I'll look into it some more.

**Comment by S-Bartfast** [comment]
Does anyone here know how to use the environment colours properly?

The value that needs to be changed is on line 196 of `CalculatorVariable.java` but I don't know how to fine the colour that should be used.

Given 'Natureshadow' refers to the calculator in particular as being unreadable I assume the rest of c:geo does use the environment colours correctly.  Any one know how I should do it for the buttons calculator?  Also, how does one activate the 'lighttheme' in the first place?  Is this a CyanogenMod thing or is it available in regular Android as well?  I can't seem to find it.

**Comment by pstorch** [comment]
The light theme is a setting in c:geo: Settings - Appearance - Light Skin

I recently had the urge to find the correct color according to the chosen skin. It was in commit https://github.com/cgeo/cgeo/commit/f74dd3ab0b535701580cc74b466ecdd21279057f

**Comment by S-Bartfast** [comment]
![image](https://user-images.githubusercontent.com/6573522/29496023-3a61ce54-8609-11e7-9a82-757d52ab8382.png)

**Comment by Lineflyer** [comment]
Assigned for retest.

**Comment by Lineflyer** [comment]
Tested and working with 2017.08.21-NB1
