### ISSUE TITLE
Please scan coordinate formulas

### ISSUE THREAD

**Issue by Natureshadow** [cgeo/cgeo#6661]
Now that we can both scan for waypoints in the listing text and have a coordinate calculator, why not scan for coordinate formulas as well and create a waypoint with the variables pre-filled?

Once that is done, scanning the personal note for obvious variable assignments would make the feature set complete.

**Comment by Lineflyer** [comment]
That could be even more difficult to match, as there are various type and sortings of formulas and variables in users listings.
I think trying to match them will most likely fail in major percentage of cases.

**Comment by Lineflyer** [comment]
Closing as we now have the waypoint calculator and due to the variety of possible formulas it might be impossible to implement a good search and catch for that. You can easily select the text passage (new feature since then) and copy to the calculator (new feature since then).
