### ISSUE TITLE
Unable to authenticate geocaching.com

### ISSUE THREAD

**Issue by kvdveer** [cgeo/cgeo#6662]
##### Detailed steps causing the problem:
- Have an account already set up with correct credentials
- Go settings/services/geocaching.com
- Click "authorize c:geo again"
- Click "check authentication"

##### Actual behavior after performing these steps:

After a few seconds, c:geo reports "login failed: unknown communication error"

##### Expected behavior after performing these steps:

Successful authentication

##### Version of c:geo used:

2017.07.24

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-A510F (a5xeltexx, samsung)
Android version: 7.0
Android build: NRD90M.A510FXXU4CQE9
c:geo version: 2017.07.24
Google Play services: enabled - 11.0.55 (438-156917137)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (2.8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (2.8 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (2.8 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1.6 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (Login failed)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
C:Geo is not authenticated, which causes me to lose access to premium caches.

**Comment by Lineflyer** [comment]
Did you already try as suggested in http://faq.cgeo.org/#login-failed ?
Did you check that geocaching.com is reachable from your device?

**Comment by kvdveer** [comment]
At the time of reporting, I had gone through the FAQ, and I did check
geocaching.com was reachable from my phone.

In the meantime the auth started working again. So either the bug is/was
intermittent, or it was on the remote end. (although logging in via the
website did work at the time).

/close
