### ISSUE TITLE
Incorporate usage guide into WP calculator

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6664]
I am wondering if we could add a comprehensive usage guide by just adding a heading description to each "section" of the calculator view.

E.g. the coordinate view could be preceeded by something like:
"You can click on any of the coordinate digits below to replace it by a variable for further calculation"

The variable section could be preceeded with:
"For each upper case variable assigned above you can either provide a numeric value or an equation also containing new lower case variables"

etc.

**Comment by Lineflyer** [comment]
Fixes #6664

**Comment by Lineflyer** [comment]
Fixes #6665

**Comment by Lineflyer** [comment]
Closes #6665

**Comment by SammysHP** [comment]
Once a user is an "expert", such messages are annoying. I'd suggest a <kbd>?</kbd> button next to <kbd>✔</kbd> and <kbd>✘</kbd>.

**Comment by Lineflyer** [comment]
>  I'd suggest a ? button next to ✔ and ✘.

Good idea. This would allow us to put a quick guide and external links (e.g. to demonstration video) on a separate page.
Question would be if @S-Bartfast would be able and willing to implement such a help page as well or we need to find someone else to contribute this?

**Comment by SammysHP** [comment]
There is a very simple solution: Just some HTML in a (almost) fullscreen webview. This could lead to a full integrated manual (assuming we find enough people writing it).

**Comment by Lineflyer** [comment]
Are you refering to an online version (getting the page e.g. from our webpage repo) or something offline?

**Comment by SammysHP** [comment]
Both is possible, but I was talking about an offline version (html file in the APK which is displayed via a webview).

**Comment by S-Bartfast** [comment]
I'll be happy take a look at implementing a help screen.

I'd also be more than happy for the videos to be used as demonstration material but I'm thinking I'll redo them if there going to be used officially, just to make them a little more succinct and polished.

**Comment by Lineflyer** [comment]
@S-Bartfast 
> I'd also be more than happy for the videos to be used as demonstration material but I'm thinking I'll redo them if there going to be used officially, just to make them a little more succinct and polished.

I also posted this in the closed issue, but maybe its better to post it here:
I think redoing the videos would be great for later official use.
However are you ok if I link this video to a german user group on Facebook (there are quite some nightly users there and I would like to get their feedback and test): https://youtu.be/eN2y5mvJul4

**Comment by S-Bartfast** [comment]
As mentioned in #6689 I've been working on this issue.

At present I've added a question mark to the top left corner of the calculator:
![image](https://user-images.githubusercontent.com/6573522/29414161-00542094-839e-11e7-88dd-c41c06ed7569.png)

Which, when pressed, opens a simple HTML page.  I'm not really sure on what to say on this page but as a start this is what I have so far:
![image](https://user-images.githubusercontent.com/6573522/29414176-114599e6-839e-11e7-994f-dc8a3b90dfc6.png)

The HTML to create this page is as follows:
```<!DOCTYPE html>
<html>
<head>
<style>
body {
    background-color: #444444;
    color: #FFFFFF;
}
mono {
    font-family: monospace;
    font-weight: bold;
    background-color: #666666;
}
</style>
</head>
<body>
<h1>Calculator Help</h1>
Tap coordinate buttons to toggle between digits and letters<br />
<br />
Long-press on coordinate buttons to set custom a digit or letter (or space to hide)<br />
<br />
The available operators for use in expressions are:<br />
<mono>'+'</mono>: <mono>&nbsp+42&nbsp</mono> and <mono>&nbsp40 + 2&nbsp</mono><br />
<mono>'-'</mono>: <mono>&nbsp-42&nbsp</mono> and <mono>&nbsp40 - 2&nbsp</mono><br />
<mono>'*'</mono>: multiplication, <mono>&nbsp6*9&nbsp</mono><br />
<mono>'/'</mono>: division, <mono>&nbspa/b&nbsp</mono><br />
<mono>'^'</mono>: power notation, <mono>&nbsp2^4&nbsp</mono><br />
<mono>'%'</mono>: remainder after division, <mono>&nbsp54 % 13&nbsp</mono><br />
<mono>'('</mono> and <mono>')'</mono>: priority, <mono>&nbsp(1+2)/(a+b)&nbsp</mono><br />
</body>
```

Note, the example above was only made to show the idea and is in no way intended to be representative of the actual help page itself.  Please do make any suggestions you think appropriate as to what the format and text on the page should be and feel free to completely disregard the example shown.


Cheers,
Slarti.

**Comment by SammysHP** [comment]
Except of the doubled "Calculator help" heading this looks great! IIRC we have/had a question mark button in a dialog somewhere already.

**Comment by S-Bartfast** [comment]
>  IIRC we have/had a question mark button in a dialog somewhere already.

I had a look in the code for a question mark and couldn't find any.  The 'tick' and the 'cross' images are called "ic_menu_done_holo_dark.png" and "ic_menu_cancel_holo_dark.png" respectively, but I couldn't find any question mark images.

After a bit of Googeling I was able to find an image called "ic_menu_help_holo_dark.png" which looks like this:
![image](https://user-images.githubusercontent.com/6573522/29415900-a8004ed0-83a3-11e7-9a49-e76422da4654.png)
But it didn't look that great on the calculator so I just created my own in a style that I thought looked appropriate.  If anyone else is capable of making a more appropriate image by all means send it this way and I'll gladly use it instead.

**Comment by Lineflyer** [comment]
If technically possible this HTML page should be multi language supporting.

**Comment by SammysHP** [comment]
Maybe there's even a simple markdown library for Android.

**Comment by S-Bartfast** [comment]
> If technically possible this HTML page should be multi language supporting.

We can most certainly make it so.
There will have to be separate HTML pages for each supported language but we can select the appropriate page based on the devices 'local':
![image](https://user-images.githubusercontent.com/6573522/29492172-3ed9f3be-85b2-11e7-89d2-8fa768adf1b5.png)

![image](https://user-images.githubusercontent.com/6573522/29492184-7e35a422-85b2-11e7-84e1-ae53d4d61f12.png)

**Comment by Lineflyer** [comment]
Just a small remark:
I would rather place the "?" icon (or whatever icon is chosen) on the right side left of the "x" with some space seperating it from the "x".
The main reason for this proposal is, that users will potentially not identify it as a clickable icon but as a header icon for the menu.

**Comment by Lineflyer** [comment]
@rsudev and others:
Does anyone know if we can load these HTML pages on Crowdin or do we need to handle the localization on Github in this case?

**Comment by kumy** [comment]
html *is* supported.

See https://crowdin.com/page/tour/supported-formats for other formats.

**Comment by S-Bartfast** [comment]
> I would rather place the "?" icon (or whatever icon is chosen) on the right side left of the "x" with some space seperating it from the "x".

It can be done:
![image](https://user-images.githubusercontent.com/6573522/29527605-96448f52-86d8-11e7-9afa-c36761f77dd2.png)

But personally I think it looks better on the left:
![image](https://user-images.githubusercontent.com/6573522/29527802-0af5b614-86d9-11e7-913f-8b8d5d915c97.png)

**Comment by Lineflyer** [comment]
Thanks...IMHO it would be better on the right side, as there are all the other user actions: Help, Abort, OK
What do others think?

**Comment by pstorch** [comment]
In the Settings dialog we have this Infoicon which opens the help text:
![rps20170821_212534](https://user-images.githubusercontent.com/5598124/29534758-6d6f5196-86b7-11e7-87a4-411cdfef65c8.jpg)

**Comment by Lineflyer** [comment]
That is a good idea. Why create just another icon, while the user already knows one from other places within the app.

@S-Bartfast If you think the code for this help window is good, feel free to submit a PR.

**Comment by S-Bartfast** [comment]
> Why create just another icon, while the user already knows one from other places within the app.

I'll look into it on the weekend

> @S-Bartfast If you think the code for this help window is good, feel free to submit a PR.

The code is fine, but I didn't think the text of the actual help page itself is much chop.

I was hoping a better wordsmith (or at least someone with a better sense of aesthetic) would be able to formulate a page that would serve the needs of users better.  As it is the page's fine for people who already know how to use the calculator but it's not really very instructional for new users.  You know, it reads more like a Unix 'man page' than a help file ;)

While my intention has been to make the calculator itself as intuitive as possible if we're going to provide a help page we might as well use it to explain how the calculator works.  So, what I have there is fine as a mock up but I wouldn't really consider it "production ready" or anything.

**Comment by Lineflyer** [comment]
> The code is fine, but I didn't think the text of the actual help page itself is much chop.

Not a big problem I think.
Once you made the structure available there will be people around from the community with ideas for filling it.

>  You know, it reads more like a Unix 'man page' than a help file ;)

Well IMHO thats not to bad. We should not make it a whole story to read but give a compact overview.
We could still link to other sources from there.

**Comment by S-Bartfast** [comment]
Just had a look at using the "Settings Info" icon for the calculator help, and it actually looks pretty good:
![image](https://user-images.githubusercontent.com/6573522/29870686-f77e19f0-8dc7-11e7-8568-fb0c1836fa3f.png)

**Comment by SammysHP** [comment]
Still looks like an icon of the dialog and not like something you could press.

**Comment by Lineflyer** [comment]
> Still looks like an icon of the dialog and not like something you could press.

That was the reason for my proposal to have it on the right side left of "X" as this implies, that the user can interact with it.

**Comment by Lineflyer** [comment]
BTW: Why does the heading read "Coordinates" it should better be "Calculator" or not?

**Comment by S-Bartfast** [comment]
> Still looks like an icon of the dialog and not like something you could press.

That's true, but I still think it's fine.  If you're scratching your head trying to figure out how to use this feature I'm sure most users would try tapping that icon in relatively short order regardless of it's location.  Sure, if it's over the left hand-side they'll probably try clicking the "Done" and "Cancel" buttons before tapping the "Settings Info" button but I'm sure they'll 'find it' after not too much searching.

> BTW: Why does the heading read "Coordinates" it should better be "Calculator" or not?

No reason, I'll fix that.

And here is what it looks like with the "Settings Info" icon in the three locations:

![image](https://user-images.githubusercontent.com/6573522/29993507-0fa9b138-8ff8-11e7-9c58-1cc0e9ee2671.png)

![image](https://user-images.githubusercontent.com/6573522/29993508-14636bd8-8ff8-11e7-9b54-d9906292230e.png)

![image](https://user-images.githubusercontent.com/6573522/29993513-184f2bb0-8ff8-11e7-837a-495b0d147640.png)

Personally I just think it looks best with the 'help' button on the left and don't really think it needs to be made to look that much more 'pressable'.  I mean, it is right in the location that the 'hamburger menu' is typically placed and anyone lost will surely try it eventually, and it just looks good there ;)

**Comment by pstorch** [comment]
I vote for the Info icon on the right side (last picture)

**Comment by Lineflyer** [comment]
I vote for the second picture (right side, but left of cancel/ok).

**Comment by S-Bartfast** [comment]
Huh, so we have three people with three different opinions.

**Comment by kumy** [comment]
I vote for 2.

On 1 we can think of an icon illustrate an "info popup"

**Comment by S-Bartfast** [comment]
> On 1 we can think of an icon illustrate an "info popup"

Sorry, what do you mean by that?  Something lost in translation??

**Comment by kumy** [comment]
@S-Bartfast I mean, my first impression was that it wasn't a button where user can interact with, but more some sort of visual information telling that the popup is of type informational (this image ~represent~ what I have in mind https://blog-static.hieule.info/wp-content/uploads/2015/04/example-of-laravel-output-message.png)

**Comment by S-Bartfast** [comment]
RIC.

**Comment by kumy** [comment]
@S-Bartfast Sorry, what does "RIC" mean? :)

**Comment by S-Bartfast** [comment]
Hehe: "Arr, I see"
(just say it out loud)
:)

**Comment by pstorch** [comment]
If it helps, I'm also fine with the second option (info icon as the first of the right buttons) 😉

**Comment by Lineflyer** [comment]
I asked some nightly users yesterday and showed them the options.
They had another argument for not choosing option 3: In the normal WP editor "OK" is always the right most option, so the usage flow is interrupted here by having to click something in the middle.

**Comment by Lineflyer** [comment]
How shall we continue with this one.
I would love to see the help page merged into the code, to take a look and - if needed - propose corrections and improvements in a next step.

@S-Bartfast 
Is this ready to create a PR?

Regarding the location of the info button we have no huge majority, but at least some people being OK with option 2 (info icon as first button of the right buttons).

**Comment by S-Bartfast** [comment]
> I would love to see the help page merged into the code, to take a look and - if needed - propose corrections and improvements in a next step.

It can be seen and corrections proposed here in this thread, yeah?  That's what the thread is for.


> Is this ready to create a PR?

Well, not really.  The code is fine but the actual text and format of the page is far from suitable.  I've proposed a bit of an outline here but don't really have the goods to actually prepare the page itself.  As mentioned, this feature simply displays a HTML page and basically it's just waiting for a decent page to show, so anyone who cares to produce a simple HTML page is most welcome to do so ;).

Also pleas do feel free to discuss any thoughts or ideas of what should be included here.  I mean, this is what the thread's for :) :)

**Comment by Lineflyer** [comment]
@S-Bartfast 
Meanwhile I started creating a web based user guide for c:geo and its quite complete.
There is also a section about the waypoint calculator, where I tried to explain the working mode as easy as possible but hopefully still catching the main principle and possibilities:
http://cgeo.droescher.eu/en/coordinatedialog#waypoint_calculator

You are welcome to provide your feedback (or I can create you an account on that Wiki, so you can edit directly).

**Comment by S-Bartfast** [comment]
Oh, great work Lars. I am most impressed.
👍

**Comment by Matze2** [comment]
For completeness a section about coordinate input in "Plain" mode would be nice.

Some keywords here: 
* digits are limited by parenthesis
* often waypoint formulas can be copied from the listing with no or little modification
* fields for variables appear if formula is correctly parsed
* some typical traps when copying formulas from the listing
  * spaces at unexpected places in formulas
  * "em" dash or "en" dash instead of dash for minus sign
  * ":" as division sign

Unfortunately I have no time to write a complete documentation at the moment.

**Comment by Matze2** [comment]
Ok. I wrote a first draft of what I had in mind. Feel free to take it as a start.

## Coordinate input in "Plain" format

Entering coordinates or coordinate formulas in "Plain" mode works completely different compared to the fixed formats.
First change the "Coordinate format" to "Plain".
The N/S and W/E coordinate part can be now entered in a free text field in "DDD°MM.MMM" or similar format. With "Plain" it is possible to use formulas directly within the coordinate pattern: single or multiple digits of a coordinate can be replaced with formulas surrounded with parenthesis.
Often cache listings provide waypoint coordinates already in the expected format, These can be copied from the listing directly into the waypoint calculator.

### Example (from GC4QT5M):
Station 4 - N45° 5.(K)(I/N)(K+L+M+N) E14° 7.(L*L)(I/L)( K+L+M+N)

Copy&Paste the North part into the North input field. Do the same for East.
If the coordinate contains formulas with variables the corresponding variable input fields appear below.
As soon as both coordinates are entered you can fill the variable fields with values in the same way as with the fixed formats described above.

If all variable fields are filled with values the result prediction usually turns into white and shows the calculated coordinate. In some cases the result field still stays gray because the coordinate parser could not interpret the initial coordinate input correctly.
Typical problems are:
* lower case variable names
* space between digits within a group
* wrong minus sign character; there are three different dash signs in the Windows world; only the ASCII dash is taken as minus sign
* sometimes a colon (":") is taken as division sign instead of a slash ("/")
* sometimes an "x" is taken as multiplier sign instead of an asterisk ("*")

**Comment by Lineflyer** [comment]
@Matze2 
I would like to invite you to add it into the Wiki yourself.
If you provide your mail address to me (is there a PM possibility via Github?!) I create an account for you.

**Comment by Matze2** [comment]
Done. :+1:

**Comment by Matze2** [comment]
By the way. While creating the screenshots above I had a crash in the calculator when turning it from portrait to landscape. Still trying to reproduce it...

**Comment by Matze2** [comment]
I extended the existing calculator documentation with the Plain mode as described above.
Feel free to review, comment and correct.

**Comment by Lineflyer** [comment]
Thanks @Matze2 
I think it is a really good extension of the guide. I only modified some styling and changed one sentence in order not to always refer to North and East (there are also c:geo users in the S and W area ;) ).

**Comment by Lineflyer** [comment]
I think we can close this for now. The guide is in the user guide and can be advanced anytime on that Wiki
