### ISSUE TITLE
Some OC URLs not parsed correctly

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6666]
c:geo cannot handle this URL: https://www.opencaching.de/viewcache.php?wp=OC10F41&log=A#log1186982

**Comment by Lineflyer** [comment]
@SammysHP Could you do me the favor and use the labels to categorize it when you open a new issue. That helps later on to sort/filter the issues listed.

**Comment by SammysHP** [comment]
Sure, but it is not possible via the mobile version of GitHub. ;)

**Comment by Lineflyer** [comment]
Try OctoDroid :)
