### ISSUE TITLE
c:geo shown not compatible with Android O

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6667]
A user contacted us on support mail.
With the last preview of Android O (on his Pixel C) he was able to download and install c:geo on Google Play.
With the current preview version it is shown as incompatible when trying to update to the current version.

Any idea?

System information:
```
--- System information ---
Device: Pixel C (ryu, google)
Android version: 8.0.0
Android build: OPP4.170623.014
c:geo version: 2017.05.22
Google Play services: enabled - 11.3.02 (446-161239932)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_AT
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (13,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (13,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (13,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1,7 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd/MMM/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Bananeweizen** [comment]
Where can one see that incompatibility? Is that shown in the Play Store of a device with AndroidO?

**Comment by notspecified** [comment]
Exactly!
![screenshot_20170806-195218](https://user-images.githubusercontent.com/5119558/29005681-d5a91dce-7ae0-11e7-8b2d-2a6d4421a437.png)

**Comment by Lineflyer** [comment]
Yes, that is what the user reported what it looks like on Google Play.

**Comment by notspecified** [comment]
I'm 'the' user! :-D

**Comment by Bananeweizen** [comment]
I have not found any other information that explains this. Neither in the Play Store console for us developers, nor in the migration guide for AndroidO. That's why I'm a bit clueless of how to investigate further. Anyone else with ideas?

**Comment by notspecified** [comment]
Perhaps something to do with the device type, it's a tablet not a smartphone. Maybe there is another switch for several device s in the playstore console?
 Should I try to uninstall it?

**Comment by samueltardieu** [comment]
Does the tablet have a GPS?

**Comment by notspecified** [comment]
No! Only WiFi/ Bluetooth to get the Position.

**Comment by Lineflyer** [comment]
In that case installation should never have been possible via Google Play...so I wonder why you once have been able to install it...

**Comment by notspecified** [comment]
:-D

**Comment by Lineflyer** [comment]
@notspecified Did you maybe install it from our homepage (APK install) on this device?

**Comment by notspecified** [comment]
I don't think so, otherwise the system would tell it IMHO:
![screenshot_20170808-224522](https://user-images.githubusercontent.com/5119558/29093796-618a3bec-7c8b-11e7-9dbc-684cf967aa87.png)

**Comment by SammysHP** [comment]
No, Android itself doesn't check the compatibility.

**Comment by Lineflyer** [comment]
But the screenshot provides the source of installation.

**Comment by notspecified** [comment]
@Lars: exactly! ;-)

**Comment by Lineflyer** [comment]
@notspecified 
I will close this issue.
The reason for not being able to install it has been given.
Maybe for some reason during the preview phase of Android 8, the Playstore was not correctly checking the hardware requirements. Thats the only reason I could imagine.

Feel free to reopen if you have new clues.
We did however not receive any complaints from Android 8 users (with GPS-enabled devices) and I can see in the play console, that we have active users with such devices.
