### ISSUE TITLE
Strickenthrough Cache names not abreviated correctly

### ISSUE THREAD

**Issue by MichelTenVoorde** [cgeo/cgeo#6670]
In listviews, GC6KGKZ is shown in c:geo as having a name of "Patty's", instead of "Patty's verbandtrommeltje" (though it would probably be abbreviated with ellipsis). See screenshot.

![2017-08-01 21 27 24](https://user-images.githubusercontent.com/1790720/28848257-8dfe00ce-7712-11e7-905c-5cd5019adbb5.png)

**Comment by MichelTenVoorde** [comment]
In landscape, it does show the entire name. For some reason, it won't show part of the word 'verbandtrommeltje', though there's enough space for that.

**Comment by Lineflyer** [comment]
Cannot reproduce with current release 2017.07.24.
For me it shows the whole name or (depending on device) it shows `...` at the end.

Does this appear on a saved list or only on your view (which I guess is a search result)?

**Comment by MichelTenVoorde** [comment]
It appears this way in all c:geo's ListViews I can think of:
- Nearby
- Hidden By User screen (the screenshot)
- Saved List (after saving the cache in a list)
- Show As List (@ livemap)

I'm running 2017.07.24 as well.

**Comment by Lineflyer** [comment]
@MichelTenVoorde Can you please post the system information here (Menu -> About c:geo -> System)

**Comment by MichelTenVoorde** [comment]
Tested on all 3 Android devices my household owns, each device has the mentioned issue.

--- System information ---
Device: Xperia Z3C (D5803, Sony)
Android version: 7.1.2
Android build: NJH47D-crteam@crbuild
c:geo version: 2017.07.24
Google Play services: enabled - 11.3.02 (436-161239932)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_CA
System date format: y-MM-dd
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (4.7 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (4.7 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (4.7 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (5.0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd/MMM/yyyy
Installed c:geo plugins:  none
--- End of system information ---

--- System information ---
Device: HTC 10 (pmeuhl_00401, htc)
Android version: 7.0
Android build: NRD90M release-keys
c:geo version: 2017.07.24
Google Play services: enabled - 11.3.02 (440-161239932)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_NL
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (16,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (16,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (16,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (5,1 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd/MMM/yyyy
Installed c:geo plugins:  none
--- End of system information ---

--- System information ---
Device: SM-A320FL (a3y17ltexc, samsung)
Android version: 6.0.1
Android build: MMB29K.A320FLXXU1AQA6
c:geo version: 2017.07.24
Google Play services: enabled - 11.3.02 (436-161239932)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: nl_NL
System date format: dd-MM-yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (4,8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (4,8 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (4,8 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (148,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
Geocaching.com date format: dd/MMM/yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by SammysHP** [comment]
First I thought it depends on the screen size / resolution, but they are very different.

HTC 10    | Samsung Galaxy A3 | Sony Xperia Z3 compact
----------|-------------------|-----------------------
5.2"      | 4.7"              | 4.6"
1440x2560 | 720x1280          | 720x1280
565       | 312               | 319

**Comment by Lineflyer** [comment]
@MichelTenVoorde 
What is the source of this cache? Did you store it online or imported via PQ or somthing else?

**Comment by MichelTenVoorde** [comment]
I stored it online via Search -> Search by owner name.

**Comment by MichelTenVoorde** [comment]
Importing a gpx (from GSAK) gives exactly the same result.

**Comment by MichelTenVoorde** [comment]
Well, this is surprising: I set the cache to 'Available' (online, it's Temporarily Disabled), and retried importing the cache to c:geo. This time, it did show up as 'Patty's verbandtrommelt...'!

So it must have something to do with the striking-through of the cache name when it's disabled.

**Comment by pstorch** [comment]
I can confirm. It has something to do with the strike through. This reminds me of #5992.
