### ISSUE TITLE
Offline Map on "real" ext sd card not choosable (Android 7)

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6671]
##### Detailed steps causing the problem:
- Put an offline map on a "real" ext sd card
- Try to find it in c:geo or choose directory

##### Actual behavior after performing these steps:
- Map not found
- Directory on ext sd card not choosable

##### Expected behavior after performing these steps:
- Scan "real" ext sd card, too or let the user choose a directory manually on it

##### Version of c:geo used:
2017.07.24

##### Is the problem reproducible for you?
Yes

##### System information:
```
Huawai P10 Plus with Android 7
```

##### Other comments and remarks:
Got this issue reported from a friend. After moving the map to the internal storage c:geo found it.

In the last refactoring with the new storage concept we haven't touched the Maps directories. There is some special logic (device dependent?) to find the mounted devices. Maybe this needs some rework.

**Comment by moving-bits** [comment]
Tested on a Samsung A5 (2016):

I had installed an external SD card using Android 6.01, moving all map data to the external SD card. No problems with that, as far as I remember. (But this is a couple of months ago, so I may have forgotten it.)

Recently the system got upgraded to Android 7, so I did a quick test today: Now I can easily navigate to the external SD card, which is shown like xxxx-xxxx with the xes being digits, and within that to the parent directory of my maps directory. I had to enter this last part manually.

**Comment by Lineflyer** [comment]
> Directory on ext sd card not choosable

Are you sure with respect to that fact?
Why exactly is it not choosable (Not found, Greyed out, etc.)?

It is well known, that our current scan does not find maps on real ext sd (this for sure could be optimized) but manual selection should work unless it is a device issue.

**Comment by pstorch** [comment]
I chatted with him over FB messenger. He told me he got stuck in the directory chooser. Couldn't choose anything other than shown on the screenshots:
![20614773_1617592761637995_1450767007_n](https://user-images.githubusercontent.com/5598124/28890233-bd5a082c-77c6-11e7-8dfc-d0da036d3257.jpg)
![20562786_1617611891636082_1034585873_n](https://user-images.githubusercontent.com/5598124/28890237-bf8eb232-77c6-11e7-96c6-2f74170d0f45.jpg)
Permissions are granted:
![20624508_1617609144969690_1466287217_n](https://user-images.githubusercontent.com/5598124/28890249-c9c1baec-77c6-11e7-97b0-eb706a593d3d.jpg)

**Comment by Lineflyer** [comment]
mmh... The chooser is not ours but the one I know from e.g. Locus, which we use if installed.
Did he provide this app/Locus the rights to access the file system?

**Comment by moving-bits** [comment]
I need to correct my above comment:

c:geo does not find the external SD card automatically, but after chosing ".." dir entry frequently enough, external SD card is shown in xxxx-xxxx format (xes being digits).
And: the needed subdir IS selectable for me - my fault in the quick test this afternoon.

**Comment by pstorch** [comment]
Indeed, he has Locus installed and not given the external storage permission to Locus yet.
Now he can see the files on the sd cards:
![received_1618090211588250](https://user-images.githubusercontent.com/5598124/28914953-c2c9f2f0-783d-11e7-8e3c-a6847f1c601b.png)

**Comment by Lineflyer** [comment]
We should review the scanning method which searches for *.map files. Up to my experience it never finds maps on sdcard automatically. Improving it will improve the usability for a lot of users and helps avoiding a lot of support questions dealing with that "problem".

**Comment by Lineflyer** [comment]
AFAICS the problem here is solved.
The root issue, that our dirchooser/scanner needs rework is reflected already in some other issues.
