### ISSUE TITLE
Some map tiles are not displayed after viewing and exiting a waypoint map

### ISSUE THREAD

**Issue by jbenc** [cgeo/cgeo#6675]
##### Detailed steps causing the problem:

1. View the live map (it happens also with stored caches but seems to be easily reproducible with the live map). Note that there are no problems viewing the map, moving around and zooming.
2. Select a cache with waypoints and switch to the Waypoints tab.
3. Display a map with one of the waypoints (tapping on the compass icon next to the waypoint and then tapping on the map icon, or configuring c:geo to display map directly by tapping on the compass icon).
4. Move around (not sure it is necessary) and exit the map.
5. Exit the cache details.
6. Move and zoom around and notice some map tiles are not displayed. Zooming in seems to be an important part of this.

It seems not to happen with Google maps but is reproducible with "OSM: Mapnik" and offline maps.

##### Actual behavior after performing these steps:

Some tiles are missing: displayed as a grey square or as scaled up tiles from a lower zoom.

##### Version of c:geo used:

2017.07.24

This has been happening in previous versions, too.

##### Is the problem reproducible for you?

Yes, very easily, almost 100%.

##### System information:

```
Device: SM-G800F (kminiltexx, samsung)
Android version: 6.0.1
Android build: MMB29K.G800FXXU1CQA1
c:geo version: 2017.07.24
Google Play services: disabled - 11.3.02 (436-161239932)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (862.1 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (842.1 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (842.1 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (6.5 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
```

![cgeo](https://user-images.githubusercontent.com/5006725/29003305-8894a232-7ab4-11e7-8189-c81818338667.png)

**Comment by SammysHP** [comment]
Can you try rotating your device (with auto screen rotation enabled) a few times and then zoom?

**Comment by jbenc** [comment]
After rotating the device, the map is drawn correctly. Just one rotation is enough.

Btw, experimented with the bug a bit more and the easiest way to reproduce is to zoom in several times and then zoom out several times. No moving of the map is required.

**Comment by SammysHP** [comment]
I thought that it might happen after several rotations.

**Comment by jbenc** [comment]
Rotating the device several times and then zooming in/out does not reproduce the issue. The map works correctly.

**Comment by jbenc** [comment]
It's still interesting that when the problem appears, rotating the device "fixes" it. I usually have autorotation switched off, thus I did not realize it before. I guess this suggests that it may not be a cache issue? (But then, I don't know how c:geo manages its map cache.)

**Comment by notspecified** [comment]
I can confirm thus issue since the first time use check on my device (Sony c5503)! I usually use check with fixed rotation to portrait mode, because it's annoying waiting for the map to be rebuilt after ever step while walking. Also with fixed rotation this problem occurs after using cgeo for a while. Exiting and opening cgeo is the workaround for this problem so far...

**Comment by Lineflyer** [comment]
Are we talking about the old and/or the new mapsforge implementation.

**Comment by notspecified** [comment]
How to check this? What's old/new?

**Comment by jbenc** [comment]
I have the "Mapsforge beta as default" checkbox in the "experimental features" section in settings unchecked. If this is what you're asking about. When I enable that, the maps are _much_ slower (bordering on usability) but the bug is not there.

**Comment by Lineflyer** [comment]
> What's old/new?

I was refering to what @jbenc described: Having the checkbox "Mapsforge beta as default" enabled would be the new implementation being used.
So according to the feedback of @jbenc the problem seems to only exist in the old implementation.

**Comment by notspecified** [comment]
I also use the old version. When I switch to the new one (enable beta) Google maps and satellite options disappear from the map selection menu. Is this a normal behaviour?

**Comment by SammysHP** [comment]
> Is this a normal behaviour?

Yes.

**Comment by notspecified** [comment]
@sammyshp: is it also normal that stages of a multicache disappear when the header waypoint is outside of the visible map area?

**Comment by Lineflyer** [comment]
@notspecified This is still a bug of the new map implementation (refer to #5900)

This search give you an overview of the open issues for the new map:
https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Map%22
