### ISSUE TITLE
Let 'Final Location' waypoint be treated separately from other wpt types.

### ISSUE THREAD

**Issue by jonnyrobbie** [cgeo/cgeo#6678]
There is an option in Settings-Map-'Map Content'-'Show Waypoints' which directs when a waypoints should be shown. I ask you to treat 'Final Location' waypoint separately from the rest of the waypoint types. Right now, I can either bring the slider up, in which case the whole map get cluttered with less then relevant waypoints, or I can bring the slider down, but the final location wpts gets hidden that way on zoomed out map making it harder to plan a trip after mystery cache solving session.
I'd like another checkbox that would allow final location be shown on the big map together with the cache starting loc.
Thanks.

**Comment by Lineflyer** [comment]
Dis you ever think about using the option to move the cache location itself to the final coordinates?
This is both a feature of c:geo and the geocaching.com website with work hand in hand.

So you don't neeed to enable the waypoint view at all but still see the location of your solved caches.

**Comment by jonnyrobbie** [comment]
I didn't know that, thank you for pointing that out. But thinking about that, I'm not sure I like it. It feels like a bad practice. A source of confusion and impurity. I may be wrong though.

But I tried to check it out and I couldn't find this option in c:geo. Is it a premium only feature?

**Comment by Lineflyer** [comment]
This FAQ entry should explain it: [Managing solved mysteries in c:geo](http://www.cgeo.org/faq#modified-coords)
AFAIK it is not a premium feature.

**Comment by Lineflyer** [comment]
I should have read the FAQ...its a premium feature. :(
But at least you can use it from the c:geo side.

**Comment by Lineflyer** [comment]
@jonnyrobbie 
Did you get along with the suggested workaround?

**Comment by jonnyrobbie** [comment]
Hmm...yes...halfway. When considering only the final location waypoint, it is indeed a suitable workaround. But when considering other types of waypoints, it still brings on an issue. For example, I'd like to show 'puzzle' waypoints even when zoomed out, but I do not care about 'swiss knife', 'parking' or some other waypoint types.
I believe there is still a room for feature request where you would select 'important' and 'not important' waypoint types.

**Comment by Matze2** [comment]
By the way: storing the corrected coordinates in GC.com is also possible as BM. Especially the coordinate correction provided in the waypoint editor works. Also since last year (probably with the introduction of the puzzle icon) the corrected coordinates are also shown in the Map until you found it.

There is only the BM restriction that you cannot store personal or field notes.

**Comment by Lineflyer** [comment]
This should have been implicitly solved by having the ability to hide certain waypoint types thus uncluttering the map as requested.
