### ISSUE TITLE
Clarification only: Keywords for coordinate extraction from personal note

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6679]
I know, that a long while ago a feature was implemented enabling the identification of different waypoint types when coordinates are extracted to waypoints from the personal cache note.

I also remember having asked for these keyword to generate a corresponding FAQ entry. However I don't find any information while searching for it.

Maybe someone can look it up in the code and tell me the different keywords which can be used.

AFAIR its e.g. something like:
```
FINAL N12 34.345 E12 45.555
STAGE N12 34.245 E12 42.555
```

**Comment by pstorch** [comment]
It looks 15 characters back from the recognized start position of the coordinates: https://github.com/cgeo/cgeo/blob/b68e80000e841fd2a9f7f0cbb6cd234eb5191796/main/src/cgeo/geocaching/models/Waypoint.java#L283

Then it takes 20 characters from it https://github.com/cgeo/cgeo/blob/b68e80000e841fd2a9f7f0cbb6cd234eb5191796/main/src/cgeo/geocaching/models/Waypoint.java#L297
and tries to match it against the WaypointTypes https://github.com/cgeo/cgeo/blob/b68e80000e841fd2a9f7f0cbb6cd234eb5191796/main/src/cgeo/geocaching/enumerations/WaypointType.java#L23. First the localized name, then the id, then the name of the enumeration.

**Comment by Lineflyer** [comment]
Thanks...thats it. I will assign myself to transfer this info into an issue for the webpage repo and later on add a FAQ entry.

**Comment by Lineflyer** [comment]
Opened an issue for the user guide, lets close here.
