### ISSUE TITLE
Use Chrome View instead of internal browser

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6680]
Sorry, that I cannot describe any technical detail, but I just learned from using some apps, that there seems to be a possibility to "embedd" a HTML browser within our app which  works hand in hand with Google Chrome.

You might know this function if you use Google Now and it comes up with search results in a view which looks like Chrome but isn't really Chrome. From there you have the ability to open the same page in Chrome via menu.
It seems also to use Cookies and configuration stored in Chrome, which the internal browser we have implemented is not capable of.

I have now seen more and more apps using this possibility, so it might be there is easy possibility to implement it and get rid of the internal browser which has several problems and is IMHO unsuable.

**Comment by SammysHP** [comment]
Did we implement the "internal browser" ourselves? I always thought that it is something that Android adds automatically since Android 5.

**Comment by pstorch** [comment]
Looks like we are using the WebViewClient but there is also a WebChromeClient.

**Comment by Lineflyer** [comment]
And frommy opinion we are using it wrong. One can only open this web view after selecting "Open in browser". Most people either select their normal browser as a default here. It should be a dedicated menu item.

**Comment by SammysHP** [comment]
Indeed, we added this ourselves in https://github.com/cgeo/cgeo/commit/2b2a2e19e1793ae79f80c8e520fb36a56e576e29

And I told people that this is something that Android has added...

Can't we remove it and find a better way to select an external browser? There are so many reports because people have set the internal browser as default.

**Comment by Lineflyer** [comment]
Thinking about it, we could indeed add the Chromewebview directly behind "Open in Browser" without calling any intent for the URL (Which might lead to circle routing) as the chromewebview itself then optionally allows to open the shown page in a real external browser (if the user prefers that instead of the webview).

**Comment by SammysHP** [comment]
Why do we need an internal browser at all? Just because someone has set c:geo as default for some registered URLs? We could do two things:

1. Detect the loop and show a message which explains how to unset c:geo as default handler.
2. Disable the component for a specific amount of time. This prevents Android from using c:geo when it tries to find a suitable receiver for the intent (sadly it is not possible to disable an intent programmatically). This would require a new activity that receives all URLs and delegates the request to the correct activity (thus c:geo is not disabled completely).

**Comment by pstorch** [comment]
I was thinking about excluding our own app for this action and found this https://stackoverflow.com/questions/19511976/is-it-possible-to-hide-some-application-in-intent-appchooser/19512128#19512128

**Comment by fm-sys** [comment]
I would like to work on this.

There are 3 ways, how we could fix the "open in browser" problem:
- exclude c:geo from appchooser for this intent 
- get default browser and open the link there
- use Chrome View as described in the first comment

I would vote for 2/3

**Comment by Lineflyer** [comment]
Nice to hear!

I think option 1 will not work as we want such URLs also to be opened with c:geo (when triggered from another app)
Option 2 and 3 do not have the same purpose:
- Chrome View (as suggested in this topic) would allow a quick glance into the original cache description
- Option 2 would solve the problem of this "circle of death", that c:geo opens itself when selecting "Open in Browser"

**Comment by Lomanic** [comment]
When I use [Octodroid](https://github.com/slapperwan/gh4a) (which is oss, so could inspect its contents), if I click a link, it suggests me all installed apps that can open links (Firefox, AOSP browser, [Copy link to clipboard](https://play.google.com/store/apps/details?id=nl.robwu.copylink&hl=en) but not itself if it's a Github link it cannot process, and when I click one of the entries it triggers directly the given app. The menu is different from the intent menu shown when using cgeo (and not defining a default handler for URLs). Could it be implemented this way in cgeo too?

It looks to me the magic happens in IntentUtils.launchBrowser ([as seen called here for example](https://github.com/slapperwan/gh4a/blob/afa5afe138c76263eadc142b2137265d5167145f/app/src/main/java/com/gh4a/fragment/BlogListFragment.java#L60)) [and this comment is exactly about preventing Octodroid opening itself](https://github.com/slapperwan/gh4a/blob/eb1204b25b06fd3f1844b481782ab608c5421656/app/src/main/java/com/gh4a/utils/IntentUtils.java#L58-L64).

**Comment by fm-sys** [comment]
Looks like 1 would also work, as we could give a list of intents that should be shown in the intent choose dialog (see https://stackoverflow.com/questions/19511976/is-it-possible-to-hide-some-application-in-intent-appchooser/19512128#19512128)

**Comment by Narrat** [comment]
Chrome view sounds like it is tightly coupled with Chrome itself, so what about those without an active Chrome installation on their phone?

**Comment by fm-sys** [comment]
"chrome view" is officially called custom tab and is an open protocol which is supported by many browsers. But the new Firefox (and mabe other browsers) will cause a loop back to c:geo so I will limit it to Chrome. For phones without Chrome the intent chooseer will be shown as currently...

**Comment by Lineflyer** [comment]
@fm-sys 
As explained in the initial posting:
Please do also remove the "c:geo internal browser". Up to my work on support the feedback to this is 100% negative due to limited usability (no cookie storage) and intent-circle -> c:geo always opens internal browser

Furthermore as also discussed over time in this issue, we should add it as dedicated function instead of a intent which is called by the "Open in Browser" menu.

**Comment by fm-sys** [comment]
But what should we do than, when there is no chrome installed and other browsers are instantly opening c:geo again.

We will have to leave this option as fallback. But most devices will have chrome installed anyway! 

The only way I would see is to show a message that there is no chrome installed, and it should be downloaded for better usability of this feature. But I'm not sure if this will lead negative feedback...

**Comment by moving-bits** [comment]
You could use the package manager (there is a utility function in `ProcessUtils` IIRC) to check whether Chrome browser is installed.

**Comment by Lineflyer** [comment]
> But what should we do than, when there is no chrome installed and other browsers are instantly opening c:geo again.

Let me think:
If we use the intent, than it goes to the android system and offers app suitable for this intent.
As long as the users did not assign c:geo by default those alternatives should be shown.
At this point I mentioned in another issue, that other apps cleanly offer the default browser only without the problem that it might callback to the own app. We would need to implement this anyhow to prevent circles IMHO.

Otherwise:
If Chrome is not installed, then we do not have any webview option shown. That why I suggested to implement it as a menu entry rather than any intent relation.

**Comment by fm-sys** [comment]
Finally I found a way to avoid the intent-circle so internal browser is now a thing of the past... We just have to hope that it will work on **all** devices!

**Comment by fm-sys** [comment]
> At this point I mentioned in another issue, that other apps cleanly offer the default browser only without the problem that it might callback to the own app.

Today I've read in the doc that it's possible to hide specific target components when using an intent chooser. That would IMHO be a nice add-on, cause selecting c:geo when trying to open a cache with a different app from c:geo doesn't make sense for sure... What do you think?

https://developer.android.com/training/sharing/send.html#excluding-specific-targets-by-component

```
Intent shareIntent = Intent.createChooser(sendIntent, null);
// Only use components you have control over
share.putExtra(Intent.EXTRA_EXCLUDE_COMPONENTS, myComponentArray);
```

**Comment by Lineflyer** [comment]
> Today I've read in the doc that it's possible to hide specific target components when using an intent chooser. That would IMHO be a nice add-on, cause selecting c:geo when trying to open a cache with a different app from c:geo doesn't make sense for sure... What do you think?

Yes, indeed this would be helpful IMHO.
So users can register c:ego for all geocaching links but still be able to trigger other apps from c:geo.

**Comment by fm-sys** [comment]
> So users can register c:ego for all geocaching links but still be able to trigger other apps from c:geo.

This is even possible today. In my current implementation I force start the intent chooser showing all possible targets, no matter if an default app is registered for this link. It's only a graphical thing, if it makes sense to allow starting c:geo from c:geo... 

Yesterday I tried it out, but I couldn't find a way to get it working. Looks like we have to leave it as it is for now :-/
