### ISSUE TITLE
Undo option not useable when removing all caches on a list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6683]
##### Detailed steps causing the problem:
- Open a list of caches
- Select Manage Caches -> Remove all

##### Actual behavior after performing these steps:
- Caches are removed
- Undo bar is shown but not selectable (greyed out) as a dialog ("Do you also want to delete the list") is additionally shown
- Undo cannot be used until the other dialog is completed, but vanishes most probably before the user manages to close the other window

##### Expected behavior after performing these steps:
- Undo should be possible

##### Version of c:geo used:
2017.07,24

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Shall we generally make the Undo bar longer lasting (if technically possible), so that it will only vanish after approx. 10 seconds?

**Comment by pstorch** [comment]
duplicate of #5595 ?

**Comment by Lineflyer** [comment]
Yes, thanks for finding it.
