### ISSUE TITLE
Make variables available between different waypoints of a single cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6691]
This is for sure nothing easy and nothing for the first implementation of the calculator, but still I want to document the feedback from the german FB group here...for later:

The current implementation is perfect for caches where you have several predefined waypoints in the listing and collect solutions/variables on your way at these waypoints.
You can enter them into the coordinator once you get them and finally have perfectly solved final waypoint.

But quite a lot of multi caches use their variables also stage by stage, e.g.:

Remark: 
Brackets are only used to group the decimal digits in this example

| Waypoint | Coordinates | Comment |
| ------------- | ------------- | ------------- |
| WP 1  | Provided in listing  | At this WP you will get answer a |
| WP 2 | N 51 24.a(a+2)5 / E 006 53,(a*2)14  | At this WP you will get answer b |
| WP 3 | N 51 24.b(a-2)5 / E 006 53,b(a+1)(b-7)  | At this WP you will get answer c |
| Final | N 51 24.c(b-2)a / E 006 53,b(c+4)(a-2)  | - |

This currently means, that you have to enter the variables (your answers) into each waypoint seperately.
From usability point of view this case would be easier if you could either copy the lower-case variables from WP to WP or have a possibility to enter and use them globally within all WP of a cache.

A single place/menu to enter the global variables would be prefered, as this is then the screen you can keep using while stage by stage solving the cache.

**Comment by S-Bartfast** [comment]
Hmm, interesting...

I like it.  This is going to require a deep meditation though 🍻

**Comment by Lineflyer** [comment]
> This is going to require a deep meditation though

Thats why I suggested to keep this as an further evolution in the next step after users getting used to the current state.

**Comment by Matze2** [comment]
I want to support that request. As an example I can give GC75XKT or GC768Y3. The formulas can be found in the waypoints. 
These are German hiking multi-caches and the variables are reused quite often.
But I also agree that this would be second iteration.

**Comment by spinnekopje** [comment]
When opening the calculator I can use 'A','B'.. and specify those values, but on a number of caches those are calculated like 'a-2'. I can't enter that calculation easily now without actually using the found value for 'a'. That makes it impossible to use that value on other waypoints.
My suggestion would be to make a values list (on cache level) where you can enter the values for a,b,c,.. and that you can use those in the fields available to the calculator as it is now.
To make it clear which value is used it might be usefull to change the color of the capital letters used now of use different signs.
I would create a separate 'page' left to waypoints so you can quickly enter the values without the need to enter menu's or go to the calculator page. The reason for that is simple: if you create calculations for all waypoints before heading off in the field you can go to the values, enter it and switch back to waypoints where you directly start navigation.
That page could be hidden until the user goes to the calculator and enables it (something like the logs of friends page that isn't shown when there are none). I guess a checkbox with 'use values on cache level' or something like that could do the trick. If values or on waypoint level the situation stays the same, only that you still have the option beneath the input for 'A', 'B'..

**Comment by SammysHP** [comment]
Just use

```
A = a
B = a-2
a = 5
```

**Comment by kumy** [comment]
I understood he want to use the same variable in multiple waypoint calculation on the same cache and a central point to change values once for all waypoints...

On January 28, 2018 11:36:21 AM GMT+01:00, SammysHP <notifications@github.com> wrote:
>Just use
>
>```
>A = a
>B = a-2
>a = 5
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6691#issuecomment-361053114

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SammysHP** [comment]
I understood it as two parts: a) reusing variables for the same waypoint b) share variables between all waypoints of a cache.

**Comment by murggel** [comment]
> 
> I understood it as two parts: a) reusing variables for the same waypoint b) share variables between all waypoints of a cache.

My "normal" use case for this scenario is b) : for many multis there is one global set of variables for all waypoints of a cache. From stage to stage they get "filled" up and used to calculate the next stage and then the final. Therefor it would be good, to have then access to all variables, not only those which are used in the current waypoint.

So it would be helpful to have one set of variables which can be used in all waypoints of a cache.

**Comment by Billy-Wallace** [comment]
![image](https://user-images.githubusercontent.com/65713561/104012799-56f22f00-51a8-11eb-9b6b-2ac9b355413b.png)
A simple solution to meet the needs of waypoint local values and cache global values.

**Comment by Lineflyer** [comment]
@eddiemuc I think we can close this as the feature is already WIP with your new variable tab. Correct?

**Comment by eddiemuc** [comment]
Correct. Was not aware that this issue exists

**Comment by moving-bits** [comment]
Implemented with the new variables tab and cache-global variables, therefore closing
