### ISSUE TITLE
Posting saved log not always removes it

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6693]
c:geo 2017.07.24 / Samsung Galaxy S6 / Android 7

I've been to an even recently and marked all my finds with "open click offline log". Now I am at home and reopening each cache with a smiley on the map.
I go to logs page, I click on the saved offline log, the online log page loads. I write my log and post it. 
Note: I have around 30 trackables and 9 geokrety with auto-visit.
Sometimes, I can't say why, I see my posted online log **and** the existing offline log, although most of the times the offline log is deleted automatically.

**Comment by Lineflyer** [comment]
I think this issue as well as your issue #6694 are caused by the fact that either some communication problem occured or you turned the phone to landscape while the log was being posted. 
Therre exists an issue which describes this fault already. I need to look it up.

**Comment by Lineflyer** [comment]
My tests show, that this probably happening when bringing c:geo in background (switch off display, change to another app) or rotating the device while the log is still being transfered. So its most likely a manifestation of #6694 triggered by these actions.

**Comment by andrixnet** [comment]
- My device is configured with fixed portrait display always, so device rotation is not a trigger (for what I reported). 
- I never switched to other apps while encountering this issue.
- While it might have happened for the display to timeout on one occasion, when I watched out for this problem I intentionally kept the display on.
