### ISSUE TITLE
Feature request: put logs in a queue for background posting

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#6695]
Logging caches especially if one has many trackables (10+) in the inventory set to visit is a time consuming operation, even with excellent internet connection. During this time c:geo is not usable.

I request a feature to submit all online logs into a sending queue to run in the background, similar to how email programs take your letter and send it to the mailserver in the background.
There should also be a page (similar to outbox) where one can see and manage logs posted for submission but not yet sent due to internet availability or other types of  errors. 
In the list I should be able to do the following: 
- force trying to resend all in queue
- remove from queue
- re-edit log and submit online without queue (to see errors, change things if necessary)
- empty queue (all not sent logs should remain as offline logs in c:geo until they are sent successfully)

c:geo should warn upon exit (back from main screen) about unsent logs.
c:geo should attempt resending logs not sent due to internet connection problems. (timeouts and such)

**Comment by Lineflyer** [comment]
Isnt that the same as #1786 or #330 (or a combination of them)?

**Comment by andrixnet** [comment]
Rather a combination of them.
Sorry, my searches before posting didn't catch any of them.

**Comment by Lineflyer** [comment]
Closing then with reference to the above mentioned issues.
