### ISSUE TITLE
Warn before discarding unsaved waypoint changes

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6696]
##### Detailed steps causing the problem:
- Add a new waypoint
- Use the new calculator and enter some formulas
- Use the checkmark to close the dialog
- See a message with "...saved..."
- Don't realize there is another message
- Close the waypoint edit dialog with back button

##### Actual behavior after performing these steps:
- Waypoint is not saved, a toast tells me that the changes were discarded

##### Expected behavior after performing these steps:
- A warning popping up which warns the user before discarding the changes

##### Version of c:geo used:
- nightly

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Yes, I know we warn the user with the second toast after closing the calculator. But two toasts in sequence can easily be overlooked.
I think we should ask the user for confirmation before discarding any changes. It's frustrating if it is suddenly gone.

**Comment by Lineflyer** [comment]
Same happend to me on the weekend while trying to use the calculator by gradually adding solutions as they came in.

The current usage flow is a bit strange:
- Open calculator and enter some solutions (not all, so that the resulting coordinate is not valid)
- Press OK button on calculator
- Two toasts are shown:
 `Current state...has been saved to waypoint` followed by `c:geo can't parse latitude or longitude`
- Calculator remains open and has to be closed by using the `x` icon
- WP shows some coordinates (which?)
- Toast is shown: `Be sure to save the waypoint...`
- Select OK button to close and save the waypoint

There are two irritating things for me as a user:
- The calculator not close after pressing OK
- The WP shows some coordinates, although the calculation was not valid (yet)

I will think about a proposal how to optimize this UI flow next days....if possible.

**Comment by S-Bartfast** [comment]
Yeah, I've spent probably too much time thinking on this as well.
I agree the "double save" workflow is pretty clunky but I have not been able to come up with anything better.  That's not to say a better approach doesn't exist, I just couldn't find an appropriate way to allow a user to either discard or retain changes without the (admittedly cumbersome) double confirm.

Here is a note I added to a section discussing the toasts in the original Pull Request:
>Normally, when the user clicks the "Done" button, the coordinates are parsed and, if the result is valid, the result is used as the input for the way point and the calculator is closed. If however the result is not valid a toast is displayed saying "c:geo can't parse latitude or longitude." and the calculator is left open so the user can correct the malformed coordinates and try again. If the user doesn't want to repair the coordinates they can always click the "Cancel" cross to discard the malformed calculation and return to the waypoint with the values it had before —and this is exactly the same behavior that the CoordinateInputDialog itself uses.
>
>The thing to workout is when should the calculators state itself be saved. As it is now (which I think is the best way to have it) the calculators state is saved whenever the "Done" button is pressed. The issue is that if the "Done" button is clicked while the coordinates are invalid [and there were no toast about the calculator state being saved] the user is informed about the invalid coordinates but there [would be] no indication about the calculators state being saved.
>
>Another option would be to only save the calculators state if the coordinate's format is valid, however it is anticipated that people will often want to store partially computed waypoints and requiring that the coordinates be fully formatted before saving would be unnecessarily burdensome.
>
>The final option would be to save the state every time either the "Done" tick OR the "Cancel" cross is clicked. This would obviously mean though that a user would not be able cancel their erroneous scratchings and revert to their previously saved calculators state should they be uncertain about things, which doesn't seem like a good option.
>
>There would also be options of allowing the back arrow to save the state and the "Cancel" button not to (or vice versa) but neither of these seem particularly natural and would not be intuitive to the user, and adding a dedicated "Save State" button or menu item seems like even more of a kludge.
>
>After considering all these options (and even implementing most of them) I eventually settled on the "Always save when 'Done' is pressed" methodology and have elected to inform the user when this happens. As it is the message is shown even when the coordinate format is valid but I actually think it's fine like that as the message is immediately followed by the "Be sure to save waypoint if you want to keep the calculator state." message once the 'Waypoint' screen is reached, which actually does look good.

All of that is discussing saving the calculator state to the waypoint information, which to me seems all well and good.  It does however become 'clunky' when it comes to saving the _waypoint_ information itself, which is where the 'double save' comes in.  If anyone has any suggestions on how this can be improved I'll be keen to hear it.

**Comment by Lineflyer** [comment]
@S-Bartfast 
Now that we have the save button the usage flow is IMHO improved.
I click Save, I close the calc, I get a toast that reminds me to save the waypoint to keep the changes. 

I think this is now OK, isn't it?

**Comment by Lineflyer** [comment]
@pstorch As you are the issue creator: Are you fine with the new save button and the usage flow?

**Comment by pstorch** [comment]
I'm fine here. Let's close.
