### ISSUE TITLE
Username no longer shown on main screen

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6702]
##### Detailed steps causing the problem:
- Start c:geo
- Wait for completion of login on geocaching.com

##### Actual behavior after performing these steps:
At the bottom of the main screen it shows:
``` GC * (finds) * Login OK```

##### Expected behavior after performing these steps:
```GC * Username (finds) * Login OK```

##### Version of c:geo used:
2017.07.24
as well as nightly

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Most likely related to a website change
I could imagine, this might affect also other functions like (owned caches selection, own logs selection) but I did not yet test this.

**Comment by Matze2** [comment]
I can confirm that 2017.08.22-NB1-2f1a321 also fixes this issue.
Username is displayed again.

**Comment by Lineflyer** [comment]
Isseu has been fixed with 1e506cc
