### ISSUE TITLE
Emptying history implicitly deletes offline logs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6708]
@pstorch 
It was reported by a user (and I can reproduce) that on selecting "Clear history" not only the history is emptied, but also all existing offline logs from cache in history list are deleted.

I have something in my mind, that we discussed this case. Did we do this intentionally?

**Comment by pstorch** [comment]
@Lineflyer yes, I remember our rather long discussion in #6186 :)

**Comment by Lineflyer** [comment]
Thanks for clarificytion. That thread was exactly what I was looking for.
