### ISSUE TITLE
Deleting caches does not free disk space

### ISSUE THREAD

**Issue by RalfJung** [cgeo/cgeo#6709]
##### Detailed steps causing the problem:
- Download lots of caches
- Check disk usage
- Delete all the caches
- Check disk usage again

##### Actual behavior after performing these steps:

Disk usage does not decrease after caches are deleted.

##### Expected behavior after performing these steps:

Deleting caches should decrease disk usage.

##### Version of c:geo used:
2017.08.23

##### Is the problem reproducible for you?
I did not try

##### System information:
```
--- System information ---
Device: XT1524 (Moto E LTE (2nd gen), Motorola)
Android version: 6.0.1
Android build: cm_surnia-userdebug 6.0.1 MOB31K f72a7cc9e7 test-keys
c:geo version: 2017.08.23
Google Play services: enabled - 0.2.4-103-gd9e86d9
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (760,2 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (760,2 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (760,2 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (10,3 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   [REDACTED]
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
c:geo takes 1.3 GiB of disk space on my phone, which is ~20% of the internal storage. I tried reducing that by deleting half of my 800 offline caches, but disk usage remained the same.

**Comment by pstorch** [comment]
Cachedata is kept for 3 days to prevent the need of downloading again in case the user did a mistake. 
So, it's a feature. Check again after 3 days.

**Comment by RalfJung** [comment]
I see. Is there any way to enforce this? I am having some serious space issues, and cgeo is by far the biggest offender.

**Comment by pstorch** [comment]
You can manually delete files here /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData
Or set your system time to 3 days into the future ;) 
Unfortunately there is no "force delete" option in c:geo.

**Comment by RalfJung** [comment]
> You can manually delete files here /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData

How would I delete only the deleted caches?

**Comment by pstorch** [comment]
That's the challenge if you choose this manual way. You have to know which ones by yourself.

**Comment by RalfJung** [comment]
Quite a challenge.^^ Not to say, near impossible.

Changing system date seems easier, I now did that and restarted cgeo. That's not enough though to trigger the cleanup?

**Comment by RalfJung** [comment]
I found a button "delete orphaned data". That freed like 180MB, much less than I expected...

**Comment by pstorch** [comment]
Hmm, maybe it takes some time, because it is asynchronous if I remember correctly. 
The "delete orphaned data" button does the same as on c:geo startup.

**Comment by RalfJung** [comment]
I guess those 500 caches actually take 1.4GB. Not sure how taht can be, but there are no superfluous folders left. Oh well.

Thanks for your assistance!

**Comment by SammysHP** [comment]
Probably some caches with many images.

**Comment by RalfJung** [comment]
I disable downloading log images. But maybe that have lots of images even in the description...
