### ISSUE TITLE
Copy WP coordinates in selectable format

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6711]
On the main cache page, you can cycle through various formats by tapping on the coordinate 
 field.
A long press then gives you the option to copy the coordinates, in the format selected, to the clipboard.

On the Waypoints page, tapping on the coordinates cycles through the various formats but a long press does nothing.
Could the copy function be added there as well please?

**Comment by SammysHP** [comment]
Long press on the waypoint title and select "copy coordinates". We should extend this context menu to the full item.

**Comment by alan666notb** [comment]
Ah - that is not obvious!
But you still can't choose the format, it always uses N51 22.123 W000 33.456 type format.

**Comment by SammysHP** [comment]
Copying other coordinates should do the same. IIRC we decided to copy always the same format (but I might be wrong and we only talked about the decimal mark).

**Comment by Lineflyer** [comment]
>  IIRC we decided to copy always the same format (but I might be wrong

Yep, you are wrong.
It works as described by the issue creator (for the cache coordinates).

So this is a reasonable feature request for WP coordinates export in fact, whereas I consider this would not be used very often.

**Comment by Lineflyer** [comment]
To be more precise:
Like on the cache coordinates you can also tap on the WP coordinates to cycle through different formats. However in contrast to the copy operation for the cache coordinates, the WP coordinates are always copied to the clipboard in MinDec format although another format might be currently shown.

**Comment by murggel** [comment]
Yesterday I was outside and could have used the function to copy the coordinates of a waypoint. But unfortunatly it does not work.
Since I provided the PR to this function, I will check this (but it definitly worked - at least at my local branch at the time I provided the PR - did not know, what went wrong) and provide a new PR.

I don't know, how to reopen this issue.

**Comment by Lineflyer** [comment]
I would have expected, that it still works with the copy menu but now copies the shown format instead always using MinDec format. But this does not work and your PR seems also to not work, you are right...

**Comment by murggel** [comment]
> I would have expected, that it still works with the copy menu but now copies the shown format instead always using MinDec format. 

What do you mean with copy menu?
Hm with my version 2021.05.11-RC always the MinDec format is used for copying the coordinates of a waypoint from context menu.

**Comment by Lineflyer** [comment]
Looking at your PR I understood you implemented this functionality by just another menu or function (which does not work at the moment).
I would have expected, that we just always use the already existing "Copy coordinates" menu for waypoints but instead always copying MinDec we copy the format the user has selected by tapping on the coords prior to executing "Copy coordinates" .

**Comment by murggel** [comment]
> Looking at your PR I understood you implemented this functionality by just another menu or function (which does not work at the moment).
I wanted to implement the same way as the mechanism for long click on the coordinates of the cache in the cache description...

> I would have expected, that we just always use the already existing "Copy coordinates" menu for waypoints but instead always copying MinDec we copy the format the user has selected by tapping on the coords prior to executing "Copy coordinates" .
AFAIS the context menu only knows the waypoint with its coordinates but does not know the format the user has selected. So that's why the MinDec format is used.

**Comment by murggel** [comment]
Fixed with PR #10645

**Comment by Lineflyer** [comment]
This has been fixed. see above.
