### ISSUE TITLE
Fix legacy version

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6712]
Issues #6682 , #6705 and #6702 should still exist on our legacy version (API 9-13) as the needed changes have not been done on that branch.

Shall we fix it there as well?
In this case @kumy or someone else needs to apply the needed changes to branch `legacy` as well and we have to publish a new release based on that.

**Comment by kumy** [comment]
I can cherry-pick the fixes, maybe tonight...

**Comment by Lineflyer** [comment]
I would like to draw attention back on this, as today a user contacted us on support running the latest legacy but unable to login.

Can anyone cherry-pick the above mentioned fixes to the legacy branch?

**Comment by pstorch** [comment]
I can do it right now

**Comment by Lineflyer** [comment]
feel free.

Maybe we can do a combined bugfix release of `legacy`and `release` branch afterwards to get this out.

**Comment by pstorch** [comment]
Is it correct, that all three issues are solved by this one commit https://github.com/cgeo/cgeo/commit/1e506cc7b06d9f8521a7b19cce03f9f12465f916 ?

@Lineflyer I got some merge conflicts when cherry-picking this commit. Are you able to test the legacy when I push the changes?

**Comment by Lineflyer** [comment]
Yes, i should have a device to test it. Just you might need to tell me where to look at if you have some idea.

**Comment by pstorch** [comment]
Just the three issues mentioned above

**Comment by Lineflyer** [comment]
I retested #6682 , #6705 and #6702 with a legacy version build based on current branch `cgeo-legacy`. All is working. Thanks for the fix.

Will prepare a common bugfix release for both `cgeo-legacy` and `release`.
