### ISSUE TITLE
Geokrety logging starts slow

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6713]
Normally I do only have one (owned) Geokret in my inventory (for testing purposes).
Whenever posting a geocache log I set the Geokret to "visit".

The progress bar while logging clearly shows, that posting the Geokrety log takes several seconds.
I assumed, that the server is really slow (as also mentioned before by @kumy)

This weekend I used to have 3 Geokrets in my inventory.
I set all of them to "visit" and noticed that only the first Geokret log (Progress shows: Posting Geokrety 1/3 (or similar text)) takes several seconds whereas the other two logs follow within split of a second.

Is that really a server issue or does c:geo have some problem here?

Unfortunately I did not have the possibility to take a debug log and now I only have one Geokret left in my inventory.

**Comment by kumy** [comment]
From what I remember, GK are posted sequentially. Yes, server is quite low, but no real idea why log times are so different. One thing that came often is "send one post for all". This is not implemented in current api, but I m working on a complete new version of the site and api. I plan to add such feature, but it is a long road...

**Comment by Lineflyer** [comment]
I will check this again with a debug log active to see the timestamp and sequence as soon as I find time for it.

**Comment by Lineflyer** [comment]
Debugged and solved meanwhile:
It was a specific issue with my geokret having a very long log history causing performance issues on the server side.
Meanwhile the performance has been improved by code optimizations and a new faster server.
