### ISSUE TITLE
Merging the existing waypoint note with the new note in the calculator

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6715]
From #6704

> Interesting. I thought temporarily about linking the 'Calculator notes' with the 'waypoint notes' (or 'user notes') but didn't end up giving it much thought and just implemented a 3rd 'notes' field exclusively for the calculator. Would you find it more useful to have these notes merged in some way? If so I'll look at it as another ticket.

Yes, I see no benefit having two separate notes. I feel it as an disadvantage to not see the calculator notes in the waypoint overview. If the calculator is used this usually contains information (e.g. variables and formulas) which might be interesting for other waypoints, too.

**Comment by pstorch** [comment]
+1

**Comment by S-Bartfast** [comment]
That seems a fair enough request.

On the "Edit waypoint" screen, what is the intended difference between the "Note" field and the "User note" field:
![image](https://user-images.githubusercontent.com/6573522/29869749-6f571e90-8dc3-11e7-9a83-932e9c5efb58.png)

I'm thinking it makes sense to re-use one of these fields, but which one?

**Comment by pstorch** [comment]
The Note Field is the note from the server from the Cache Owner.
The User Note is editable by the user.
For waypoints created in c:geo also the normal note field is editable by the user, so I think this should be used.

**Comment by rsudev** [comment]
I have not followed this feature, so just a question: Is the calculator used only with user-created waypoints? Or can it be used with listing-provided waypoints as well? If so, user-note would seem more appropriate.

**Comment by pstorch** [comment]
It depends on whether the waypoint has (server) coordinates or not.

**Comment by Kitzibua** [comment]
>For waypoints created in c:geo also the normal note field is editable by the user, so I think this should be used.

Is there a reason why users can edit the note field for user-created waypoints?
In my opinion it would be more consistent to let the user only edit the user note field, no matter of the waypoints source. When the note field is empty (no note on server or a user created waypoint), it could be hidden completely, showing the user note field only.

Regarding the calculator, I think it should share the user note, as it should be editable for the user. 
Maybe if a server note is present, it could additionally be shown in the calculator view as read only.

**Comment by Matze2** [comment]
@Kitzibua 
👍 totally agree

**Comment by Lineflyer** [comment]
> Is there a reason why users can edit the note field for user-created waypoints?
In my opinion it would be more consistent to let the user only edit the user note field, no matter of the waypoints source.

I agree.
In fact AFAIR for server defines waypoints it should already be the case, that only the user note is editable. So we should have this regulation for all waypoints.

And yes:
The user note field of the waypoint should in fact be the same field to be used/shown in the WP Calc.
It makes no sense to just add another note field.

I would not involve the personal note field of the cache in this discussion.
The calculator is bound to a waypoint so it should only use/modify the information belonging to the waypoint.

**Comment by S-Bartfast** [comment]
Man, this is doing my head in!

So we currently have fields called "Note" and "User notes", and I take it by "normal note" and "personal note" you're referring to the "Note" field, yeah?

Is there any reason there are multiple note fields in the first place?  Would it not be clearer to just have a single field and pre-fill it with information from the server if such information exists.  If we really wanted we could make the 'server text' read only and possibly display it in a different colour or something but you know, can't we just stick that in a single universal-notes field and let the user do with it as they wish?  It would seem a lot simpler to me ;)

**Comment by rsudev** [comment]
There is a cache-level 'personal note' which corresponds to the similar named feature on the geocaching sites and essentially is not relevant in the calculator context, I would say.
For the waypoints, there is a description on the server side and of course the user wish to take notes while out caching in addition. Until not very long ago those two things were stored in one field (note), which basically prevented us from applying server-side description updates without risking the loss of local user notes on that waypoint.
So we decided to split that information (and 'note' therefore should rather be 'description' now) to be able to distinguish local and server changes and apply server updates on refreshing a cache.
How this is than presented in the UI (the description e.g. being coloured, read-only content in the same text area as the user notes) is than again a different question :)

**Comment by pstorch** [comment]
I'll look into it

**Comment by pstorch** [comment]
As mentioned in https://github.com/cgeo/cgeo/issues/6797#issuecomment-339785228 this is not a separate column, but together with the variables as a JSON in the `calc_state` column.

Let me think about options:
- just remove it from the JSON: simplest, but might cause angry nightly build users (data loss)
- migrate it on startup as other DB migrations: would need JSON logic in the DataStore
- migrate on demand: still read the `notes` field from the `CalcState` JSON and move it to the `user_note` column  (append if necessary). But then we would have to keep this logic for an undetermined while in the codebase.

Any opinions?

**Comment by Matze2** [comment]
I can live with data loss. This is the risk of nightlies. :)
I wouldn't expect that anybody puts effort writing migration code for a alpha feature.

For me the biggest missing feature in the calculator is a possibility to share variables among all waypoints (#6691). By using the user note instead of a private note field as it is now all variables can be copy-pasted between the waypoints at least.

**Comment by pstorch** [comment]
Ah, maybe we should clearify a bit:
This is about merging the note from the calculator with the user note of the specific waypoint. This is not the personal note from the geocache.

**Comment by Matze2** [comment]
Yes clear. We only talk about the waypoint page.

If this issue is resolved one can create an artificial waypoint containing all variables and copy-paste that list into the other user notes. Then open the calculator and enter the variables in the formula.
This is half way to #6691.
