### ISSUE TITLE
'Ghost' certitude checker

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6720]
This is a really odd one, maybe someone can shed some light on it...

My partner owns a trad cache 'Foxtrot 1' [ GC5WRWD ], when she views it on cgeo on her phone, the cache page has a link to a certitude checker on it.
When I view it on cgeo on my phone, or we look on it's webpage, there is no checker present.

She has never defined a checker for the cache (Why would she, it's a trad), but if you go the the certitude page it is valid - if you enter the co-ords of the cache you get a green tick. Also someone else has solved it.

The menu on her phone has an 'Open Geochecker' entry in it, mine hasn't.
Refreshing the page makes no difference.

Any ideas what's going on?

**The cache page on my partners phone ...**
![motog](https://user-images.githubusercontent.com/7459480/29998274-bb9b64fc-901e-11e7-8f96-150252f95aad.png)

**The cache page on my phone ...**
![z5](https://user-images.githubusercontent.com/7459480/29998278-c59b2bd6-901e-11e7-8fc0-aabdc5c3ff2a.png)

**Comment by SammysHP** [comment]
Definitely nothing that is added by c:geo. With "refreshing the page" do you mean refresh the cache in c:geo?

**Comment by alan666notb** [comment]
Yes, refreshing it in cgeo on her phone.
The check stays put.

**Comment by rsudev** [comment]
As she is the owner, she gets a different page served when downloading the cache (I don't have a checker on this cache as well). How does the page look for her in the browser?

**Comment by alan666notb** [comment]
Just tried that, it doesn't appear in the browser for her either.
(That's using the cgeo 'internal browser', she is logged in on it).

**Comment by alan666notb** [comment]
Just tried login her in on Chrome running on Windows and the checker still isn't there,
also I checked the page source she receives and don't see anything there either.

The only place it appears is on cgeo on her phone.

**Comment by kumy** [comment]
What happen if she log on your phone?

On September 2, 2017 10:18:03 PM GMT+02:00, alan666notb <notifications@github.com> wrote:
>Just tried login her in on Chrome running on Windows and the checker
>still isn't there,
>also I checked the page source she receives and don't see anything
>there either.
>
>The only place it appears is on cgeo on her phone.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6720#issuecomment-326767218

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alan666notb** [comment]
She just got rid of it by making a small edit to the cache page,
when she refreshed it in cgeo the checker disappeared.

But when she reverted the small edit and refreshed cgeo, the edit says put even though I can see the change on the website.

I think there maybe something wrong/corrupted with the database on her phone, is there anyway to reset/repair it without losing all her settings?

**Comment by rsudev** [comment]
This could also be a temporary glitch on gc.com side (one server still serving the old version of the page). When you refresh once more after some minutes, is the change still not present?

**Comment by alan666notb** [comment]
Hasn't updated yet, will keep trying ...

But isn't it really weird that there was a certitude checker present, 
AND it was the correct checker for that cache?

(We can't find it anymore now that the link has gone, it's not in her list of checkers on the certitude site).

**Comment by rsudev** [comment]
You can still find it by constructing the correct url: https://www.certitudes.org/certitude?wp=GC5WRWD
Perhaps it is not listed because its a traditional (to check if something is added to an owners listing I created a solution for one of my traditionals, which is also not listed under my name).
Seemingly you cannot delete a solution...

**Comment by alan666notb** [comment]
Still not updated this morning!

**Comment by Lineflyer** [comment]
Besides c:geo not updating it, the riddle is, where this checker originally came from.
Is it possible she used C&P to copy the description from another cache while creating ord editing the cache?
I once experienced, that one can paste HTML code into the cache editor on the website and parts of the code gets sucked up by the editor (not shown anymore in later edits but still in source of the page).

Can you save the HTML page of the cache details the owner sees in his browser (on PC) and  link it here?

**Comment by alan666notb** [comment]
OK, been jumping through hoops on this one, this is what I've found...

-- I asked her to edit the cache page to see if we could detect the change in cgeo
-- she put some text into the 'long description' box
-- we reloaded the cache in cgeo and saw the text appear
-- she then deleted the text in the 'long description' box (**_so it is now blank_**)
-- we reloaded the cache in cgeo, the text does not disappear.
-- I exported her database, un/re-installed cgeo, loaded the exported database.
-- the text still appears in cgeo even after refreshing the cache.

So, I think what is happening is that if the  'long description'  is blank on the website, a 'blank' field doesn't get sent to (or isn't processed by) cgeo, so the text never gets erased from cgeo's database.

Does this make sense?
Is it a bug?

**Comment by Lineflyer** [comment]
Most likely..I could imagine, that it is not foreseen the one of the description turns empty while before it was filled. That could be a bug of merging the data in c:geo. Not related to this ghost link problem of course.

**Comment by alan666notb** [comment]
I think I have an explaination for that...

She only recently started using Certitude and someone showed her how at an event.
We think they may have used this cache as a quick 'Demo', put the checker in the long description, showed her how it looked on cgeo and then deleted it.

This bug would have resulted in exaxtly what we see, a checker that appears in cgeo but not on the website and can't be cleared with a refresh.

So, certitude=red herring, I think.

I think it's best to close this one, I'll post another issue if I can reproduce it.
