### ISSUE TITLE
Display QR-code of cache

### ISSUE THREAD

**Issue by pietmarcus** [cgeo/cgeo#6723]
Would it be possible to display a QR-code of a cache in c:geo, so sharing a cache with friends is easier?

**Comment by rsudev** [comment]
If you have e.g. zxing barcode scanner installed, you can already do that (share - barcode scanner from the menu in cache details).
Is that what you are looking for?

**Comment by SammysHP** [comment]
Yes, this is already possible. Install a barcode scanner like https://play.google.com/store/apps/details?id=com.google.zxing.client.android. Then open the cache, menu, share, barcode.

**Comment by pietmarcus** [comment]
Yeah, that's what I was looking for... Sorry for the confusion 😀
