### ISSUE TITLE
Description of GC15GV4 unreadable

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6724]
Some weeks ago I stored GC15GV4 on my device using an older nightly of beginning of August.
I noticed no problem reading the description.

Meanwhile I use a newer nightly 2017.09.03 and noticed the still stored cache had now black text on black background. 
As the caches was not refresehed since original storing it, it might be the visualization might have a bug in newer version.

I might be wrong though.
Can someone check this cache with the current market release?

**Comment by kumy** [comment]
Black screen on 2017.08.23

On September 4, 2017 5:32:26 PM GMT+02:00, Lars <notifications@github.com> wrote:
>Some weeks ago I stored GC15GV4 on my device using an older nightly of
>beginning of August.
>I noticed no problem reading the description.
>
>Meanwhile I use a newer nightly 2017.09.03 and noticed the still stored
>cache had now black text on black background. 
>As the caches was not refresehed since original storing it, it might be
>the visualization might have a bug in newer version.
>
>I might be wrong though.
>Can someone check this cache with the current market release?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6724

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lineflyer** [comment]
I think it was before 2017.08.23. 
I will assign it to myself to test with an older version as well. Feel free to do the same if you find time earlier.

**Comment by pstorch** [comment]
Another example: http://coord.info/GC7B9HT

**Comment by rsudev** [comment]
Thanks for highlighting this one, it is nearby and I should get it in the near future :)
The reason why these caches are problematic lies in the fact, that the text colour is set through a style attribute, something which our algorithm to detect explicit text colours to adapt the background doesn't handle (yet). The visualization didn't change the last three years in that aspect, so I rather presume another cause for this to appear. Might be that the 'fromHtml' method in Android now handles styles on spans?
A fix (adapting the patterns to handle color:.. alongside color=) should be relatively easy.

**Comment by rsudev** [comment]
BTW: Testiing with a (virtual) 5.1.1 device: white on black (seemingly doesn't handle color styles in spans when converting html to spannable)
