### ISSUE TITLE
Variable not shown alpabetically

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6725]
##### Detailed steps causing the problem:
- Today I used the WP Calc to enter the formula given in GC2DMGW
- In this formula the variables are not appearing in alphabetical order
- I entered the formulas in the sequence as given in the cache description

##### Actual behavior after performing these steps:
The lower case variables are sorted in the order of appearance, which makes it more difficult to fill them with values later on.

##### Expected behavior after performing these steps:
The lower case variables should be sorted alpabetically.

##### Version of c:geo used:
2017.09.04-NB

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Screenshot:
![screenshot_20170905-110909](https://user-images.githubusercontent.com/949669/30054340-151bd02a-922c-11e7-8822-17f4dd6039c3.png)

**Comment by S-Bartfast** [comment]
> The lower case variables are sorted in the order of appearance

This was actually intended but I certainly can make them alphabetic if preferred.

How about the uppercase "Equations"?
Do you think these would be better listed in 'positional' or 'alphabetic' order?
Either way will be easy enough to do, it's just a matter of deciding which is wanted ;)

**Comment by Matze2** [comment]
+1, in my opinion the order of the letters is quite arbitrary. It is faster to find them if they are alphabetically sorted.

Maybe I can add another slightly related wish here instead of adding a new issue. The screenshot above is a good example how I also use the variables and formulas.
At least for the lowercase variables in most of the cases I just give a number. Can we open the numeric part of the editor by default at least for the lowercase variables?

**Comment by S-Bartfast** [comment]
> Can we open the numeric part of the editor by default at least for the lowercase variables?

Unfortunately not.  I would have liked to open the regular keyboard displaying the numerical layout to begin with with the ability to switch to the 'alpha' and 'special character' layouts but unfortunately Android does not facilitate this.  While there are several different keyboard 'profiles' available in Android (Dial Pad, Date/Time entry, Numerical Input, etc.) unfortunately the only profile that is appropriate for the expression entry is the regular "Text" profile which _must_ start with the alphabetic layout displayed.

When I first looked at this I was expecting it would be possible to open the regular keyboard with a numeric display however it seems it is not.  While the user can switch the regular "text" keyboard to different layouts (such as numerical keys and special characters etc.), when it first opens it must be shown with the 'alpha' layout displayed.  One can specify a different 'profile' (such as the number-pad profile) however if the number-pad profile is used there is no way for the user to change back to the regular layout should they want to enter other symbols.  So the numeric keypad wouldn't be appropriate even for the "lowercase" expressions as although all the numbers are available there would be no way to enter mathematical operators such as `'+'` and `'/'`.  It's a shame, as like you, I would prefer to start of showing numbers but this simply isn't possible if you also want to allow the ability to enter symbols.

**Comment by S-Bartfast** [comment]
Anyway, here's a screenshot of what it looks like sorted alphabetically:
![image](https://user-images.githubusercontent.com/6573522/30168016-51e70ee6-9427-11e7-83f5-b3e286aa718c.png)

I take it this is what you guys would prefer?

**Comment by Lineflyer** [comment]
Indeed, perfect. Feel free to submit a PR with this change :)

**Comment by Matze2** [comment]
Yes. Looks good. The capital letters are usually in alphabetic order anyway. There should not be really a difference in user experience.

**Comment by pstorch** [comment]
fixed by #8c1a4b3

**Comment by Matze2** [comment]
I installed the latest nightly and verified the issue. This looks good now. Thanks!
