### ISSUE TITLE
Add to calendar function lost

### ISSUE THREAD

**Issue by MedicineManOfSeattle** [cgeo/cgeo#6727]
Add to calendar function seems to be missing for events? Was this an additional plug in or integrated into c:geo?

**Comment by Lineflyer** [comment]
It used to be a plugin but meanwhile should work without plugin. What version of c:geo are you using and with what event cache did you try?

**Comment by MedicineManOfSeattle** [comment]
Version 2017.08.23

http://coord.info/GC7BPD5


Alex

412-215-0318
Google Voice: 412-206-9769 (for messages only)

>^..^<

http://adventureslivinginjapan.blogspot.jp/
http://medicinemanofseattle.blogspot.com/
http://medicinemanofnorwood.blogspot.com/

**Comment by rsudev** [comment]
Crosschecking with current master, the menu-entry is there. But adding to the calendar fails. Where does the problem start for you (and what is your device locale)

**Comment by MedicineManOfSeattle** [comment]
Normally I see the option right at the top of the list.

I'm in Seattle WA USA.

- Alex
412-215-0318

**Comment by pstorch** [comment]
There is a logic to determine if the "Add to calendar" menu item is shown:
https://github.com/cgeo/cgeo/blob/a8675566ac7ef5e27347d0fdaba74bb67ae8ef06/main/src/cgeo/geocaching/models/Geocache.java#L431-L434

Is the Cachetype recognized correctly as Event Cache? Is the Hidden date set?

**Comment by Lineflyer** [comment]
WIth the example provided by the issue creator adding to the calendar works for me without a problem (current master).
I guess the problem of @rsudev is another one.

@MedicineManOfSeattle Are you logged in? if not, the cache might miss information (such as hidden date).

**Comment by pstorch** [comment]
It works for me, too. 
I was asking about the cache type and hidden date because maybe the cache was loaded incomplete.

**Comment by MedicineManOfSeattle** [comment]
Finally worked after force closing the app, reloading the event from the
map, and then force reloading the event in the app.

I'm not sure why this one was giving me issues before.

Thanks!



Alex

412-215-0318
Google Voice: 412-206-9769 (for messages only)

>^..^<

http://adventureslivinginjapan.blogspot.jp/
http://medicinemanofseattle.blogspot.com/
http://medicinemanofnorwood.blogspot.com/
