### ISSUE TITLE
API to extremcaching.com not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6733]
As it can also be seen in our CI-job for the website tests, the connection to extremcaching.com is down since some days.  Also when using c:geo the client is not able to login.

Looking at the website the reason seems to be an expiry of the SSL certificate.
I dropped a mail to their contact adresss. 

The site looks a bit unmaintained, so lets see if this problem will be solved at all.

**Comment by Lineflyer** [comment]
I did not get any reply, neither per mail nor to the Facebook posting/message I did.
mmh.

**Comment by mucek4** [comment]
Let's drop it from tests, so we don't have problems with that. Later we shall remove API or add some sort of warning for any users that still uses ec.

**Comment by SammysHP** [comment]
Let's remove the tests only together with the API. There is no reason to keep untested code.

**Comment by Lineflyer** [comment]
> Let's remove the tests only together with the API.

Can we disable the extremcaching.com related tests at least for the website test builds on CI?
Its difficult to identify real problems, if they keep failing due to this reason continously.

BTW:
I sent a message now to the user who contacted me long time ago because of the API using their user private messaging system on the website.

**Comment by pstorch** [comment]
Do we have any indication on how many users might be affected? Any statistic about EC users?

**Comment by Lineflyer** [comment]
No...but I guess "a hand full" (literaly speaking!)

**Comment by mucek4** [comment]
> Can we disable the extremcaching.com related tests at least for the website test builds on CI?
> Its difficult to identify real problems, if they keep failing due to this reason continously.

This is exactly why I suggested to remove tests.

**Comment by SammysHP** [comment]
OK, then let's remove the website tests and check the site manually during the next days.

**Comment by pstorch** [comment]
The tests are temporarily disabled now, but we should keep it open as reminder.

**Comment by Lineflyer** [comment]
I meanwhile tried just another way of contacting them, now by posting public to their FB site.

I think we can for now leave it by disabling the watchdog tests. It is anyway not pur problem if login does not work due to their certificate issue.
I suggest to leave the code in unless we get notice that the site is abandoned.

**Comment by kumy** [comment]
SSL certifiate is renewed since Thu Sep 21 20:11:36 2017...

**Comment by pstorch** [comment]
Ok, I'll reactivate the test.

**Comment by Lineflyer** [comment]
Reopen as once again their certificates expired blocking the users (and our CI tests).
I suggest to remove the website tests permanently.

**Comment by pstorch** [comment]
I'll disable it. I'm more and more wondering if anyone is still using it.

**Comment by Lineflyer** [comment]
Me too.
Checked today and certificate is still outdated.

As the c:geo connector to EC was contributed by one of their admins (AFAIR) I think we should keep it in for now (as long as the service is still running "somehow") but keep the website tests disabled until further notice.

**Comment by Lineflyer** [comment]
The certificate has been renewed meanwhile. It is valid until 10.04.18. I assume, that this issue will come up again by then. 
So lets just keep the website tests disabled for now.
