### ISSUE TITLE
parse error for coordinates on integer longitude/lattitude

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6736]
Try to store OC0054 or OC533E. Both throw a parse exception. The commonality is that they use coordinates exactly on full longitude/lattitude.

https://forum.opencaching.de/index.php?topic=4912.msg61348#msg61348

**Comment by UniQP** [comment]
Interestingly, the problem does not occur with [GC1WCYF](http://coord.info/GC1WCYF), so maybe it's OC-specific.

Do you have any stack trace at hand?
