### ISSUE TITLE
"Enable live" is disabled for waypoints

### ISSUE THREAD

**Issue by gcPhil** [cgeo/cgeo#6740]
I like to use the basic internal Navigation with BRouter. It don't work for distances longer than around 10km but is very nice for reaching the next cache on a bike-tour in that distance. As a feature I would like an option to see other caches on the map while navigating. It happens that the suggested route leads you along many other caches or waypoints and it's not possible to see them if you watch the red navigation suggestion.

**Comment by martl** [comment]
+1

**Comment by rsudev** [comment]
How do you trigger the navigation? If it is from single cache map, just enable updates and you should have what you want.

**Comment by gcPhil** [comment]
I trigger brouter-navigation over "navigation>map" or with the map icon the the cache details. Your suggestion to activate map-updates could be a workaround and I will try it on the next tour.

But after a quick try I am not very happy in using much mobile data that way  without needing it (all needed caches are already stored on the device over pq-file and this map-updates can need huge amount of data/day). Also hundreds of already found caches get displayd this way ("show found caches" is turned off but that found information seems not to be downloaded immediately).

**Comment by pstorch** [comment]
@gcPhil you can disable live on the live map. Then only the stored caches are displayed.

**Comment by gcPhil** [comment]
**Thank you all for the prompt help!** @pstorch is right. I tested again and it is possible with:
_open cache details>navigate>map>enable map updates+disable map updates_

It's not that intuitive but it's working. **But what I noticed is that activating the map updates is only possible when I want to navigate to a cache. When I navigate to a waypoint that menu entry is missing!**

**Comment by pstorch** [comment]
@gcPhil you are right, the menu item "Enable live" is disabled for waypoints. I'm not sure, but it looks like this is on purpose.

**Comment by Lineflyer** [comment]
Small comment from my side:
As can be seen on the beta mapsfroge map @rsudev introduced a possibility to activate the navigation path on the map from the live map popup. So at least for the new map (once its promoted from beta) there will be an easier toggle to activate the navigation path.  I did however not yet check whether it also applies for WPs of a cache on the new map.

**Comment by fm-sys** [comment]
You can now just create "individual routes" via tap and hold a cache at the live map, so the original issue is probably solved. 

But there is one thing left:
> you are right, the menu item "Enable live" is disabled for waypoints. I'm not sure, but it looks like this is on purpose.

Why should we disable such a functionality by purpose? Users should always have the possibility to toggle live mode. I will rename the issue accordingly to better fit to the remaining issue...

**Comment by Lineflyer** [comment]
> Why should we disable such a functionality by purpose? Users should always have the possibility to toggle live mode. I will rename the issue accordingly to better fit to the remaining issue...

I know there was a reason for that, but I don't remember it.
Some kind of complex issue showing up in this special case maybe.

**Comment by fm-sys** [comment]
I guess it was due to the fact that the waypoint might get hidden if there are more caches around as the maximum defines in the settings. Anyway, I think users should have the possibility to decide their self... (but I have to admit that this is a very low priority issue)

**Comment by moving-bits** [comment]
Cross-checked with UnifiedMap: "Enable live" is available meanwhile even if a waypoint got selected as target, so let's close here.
