### ISSUE TITLE
Handling of Okapi "image_rcmd_max_pixels" when uploading photos

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6741]
Comment https://github.com/cgeo/cgeo/pull/6734#issuecomment-332884702 from @following5
> The message e.g. may tell that the image was too large to process, if the image file was broken, the image format could not be recognized, the caption was missing and so on.
> 
> So the overall best algorithm is:
> 
> Test for image_max_upload_size and abort if the image file is too large.
> Either downscale to image_rcmd_max_pixels or ignore image_rcmd_max_pixels.
> upload the image
> evaluate success
> display message if success == false
> (We should add this to Okapi docs!)
> 
> But if evaluating the Okapi result is not feasible to you, noone will complain if you ignore it. ;)
> 

I've copied it over from the merged PR to a new issue, to have a fresh discussion. The new feature is basically working. It's just a matter of Frontend Design / UX question.

Recap:
When uploading log images for OC caches there might be two restrictions:
- `image_max_upload_size`: this is a hard limit, larger images are not accepted. This is handled fine, I guess.
- `image_rcmd_max_pixels`: this is just a recommendation, the server might silently scale the image down. At the moment the `image_rcmd_max_pixels` parameter is treated as a hard limit in c:geo (I wanted to be on the safe side). But that might be too restrictive.

From my point of view we have these options:
1. just ignore this parameter: might be the easiest, we could even delete some code. But it might surprise some users, that the image is smaller than they chose. And it unnecessarily consumes bandwidth.
2.  add a confirmation dialog, so the user can chose to "don't care and upload anyway" or chose to "cancel and scale down". The only issue here: we agreed on only adding new dialog boxes, when necessary.
3. limit the scaledown dropdown box according to this parameter and preselect the largest possible value. This way the user doesn't have to do anything. Issue here: this value is stored in the preferences and reloaded when the next logimage is selected. If the next log is for a different platform without this restriction the scale down is still selected and might be to restrictive. And the predefined scaledown values in c:geo are the pixels of the longes side. The `image_rcmd_max_pixels` from OC is defined as `X*Y` pixels. For example the opencaching.de platform defines it as `786432` pixels, which represents `1024*768`. But when we limit our scaledown box to the `1024` option, then the image might still be too large, e.g. `1024*1024` pixels (yes unlikely, but possible). So preselecting the right value here is a bit tricky.

At the moment I'm in favor of 2) or 1).  
What are your preferences? Any other ideas?

Regarding the error messages: at the moment we don't read nor show possible error messages from Okapi in any other call. Not sure if we should introduce it now. Maybe facing language issues between c:geo and Okapi (there is a language parameter though).

API doc:
https://www.opencaching.de/okapi/services/logs/images/add.html
https://www.opencaching.de/okapi/services/apisrv/installation.html

**Comment by following5** [comment]
So automatic downscaling to `image_rcmd_max_pixels` is not an option? All geocaching websites do automatic downscaling, so I guess users will understand that.

Option 2 could be annoying. Most users won't care about image size or upload bandwidth, they just want to press a button and somehow see the image in their logs.

I would prefer option 3 if the two issues could be solved. E.g. storing the downscaling preselect value by-platform instead of globally, and limiting input to <= sqrt(`image_rcmd_max_pixels`) for Opencaching.

Otherwise, I would prefer option 1. And - if possible - inform the users in the image upload dialog that images larger than X megapixels will be downscaled.

**Comment by pstorch** [comment]
> So automatic downscaling to `image_rcmd_max_pixels` is not an option?

Sure it is an option. I just have some doubts about the best way of implementing it and if it fits the "philosophy" of c:geo ;)

> Most users won't care about image size or upload bandwidth

Any evidence? I heard/read a few times about users complaining about their mobile data usage. And I personally wondered more than once about some sites changing my content without notice. But this is only my opinion. 

I just want to collect some more opinions. That's why I opened a separate issue.

**Comment by following5** [comment]
> > Most users won't care about image size or upload bandwidth

> Any evidence? I heard/read a few times about users complaining about their mobile data usage. And I personally wondered more than once about some sites changing my content without notice. 

Most users upload only few log pictures. And since automatic downscaling was implemented at Opencaching.de in 2014, I am not aware that any user complained.

The OC sites do not inform the users about downscaling, they just do it. (GC informs in the upload form that "your image will be downscaled".)

**Comment by pstorch** [comment]
I'm still thinking about the best way to present this to the user and experimenting with the dialog.
Instead of an extra dialog box, we could also insert an error/warning message into the image select dialog in case one of the restrictions are violated.

- `image_max_upload_size` is violated (additionally the ok button should be grayed out):
![screenshot_20171004-224312](https://user-images.githubusercontent.com/5598124/31199008-69626b08-a956-11e7-80db-8485770aa8fa.jpg)

- `image_rcmd_max_pixels` is violated (here the user could still click on ok):
![screenshot_20171004-224426](https://user-images.githubusercontent.com/5598124/31199016-6ba60c12-a956-11e7-8775-a459a00b4a7e.jpg)

**Comment by pstorch** [comment]
I just checked what GC is doing. And they also downscale the image silently. They use 2,048 × 1,536 as fas as I tested.
Maybe I was too picky here and the users are really used to the automatic downscaling.
At the moment I'm in favor of just removing the check of the `image_rcmd_max_pixels` parameter and removing (simplifying) the code.
