### ISSUE TITLE
Log picture not attached to log immediately after posting

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6744]
##### Detailed steps causing the problem:
- Log an OC cache incl. picture 
- After log is posted, swipe to logbook

##### Actual behavior after performing these steps:
No picture shown attached to the log

##### Expected behavior after performing these steps:
Picture should be shown

##### Version of c:geo used:
2017.09.30-NB

##### Is the problem reproducible for you?
Only tested once

##### Other comments :
Compare to GC picture upload with c:geo. Picture is shown there after log has been posted

**Comment by pstorch** [comment]
That's because we don't get the image url back when uploading the image. The API https://www.opencaching.de/okapi/services/logs/images/add.html doesn't provide it.
@following5: we only get the `image_uuid` back. Is it possible to derive the URL from the image uuid?

**Comment by pstorch** [comment]
Maybe it's possible to derive like this: 
`https://www.opencaching.de/images/uploads/{image_uuid}.jpg`

**Comment by Lineflyer** [comment]
How did we solve or work around for GC.com log images?

**Comment by pstorch** [comment]
For the old GC log page we parse the URL from the result html page. For the new GC log page we get the URL as API result.

**Comment by following5** [comment]
> @following5: we only get the image_uuid back. Is it possible to derive the URL from the image uuid?

You can retrieve it via [services/logs/entry](https://opencaching.pl/okapi/services/logs/entry.html): Request the `images` field, it contains the UUID and URL of each image.

**Comment by pstorch** [comment]
@following5 thanks, I'll have a look.

**Comment by following5** [comment]
To simplify things, I will add the image URL to the return values of `services/images/add`. Well be available in ~ 1 hour at opencaching.pl, but may take some weeks to opencaching.de.

**Comment by following5** [comment]
Here we go: https://opencaching.pl/okapi/services/logs/images/add.html#arg_callback
