### ISSUE TITLE
keys on CI changed?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6748]
http://ci.cgeo.org/job/cgeo%20pull%20request/1126/console

> INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package cgeo.geocaching signatures do not match the previously installed version

Have we changed the keys on that agent (kumy-4)? I can only imagine different keys as root cause for that error message. Or is there are another root cause you are aware of?

**Comment by kumy** [comment]
I know! I have installed another version of cgeo, which hasn't been removed before plug back into CI.

**Comment by kumy** [comment]
I've uninstalled cgeo from the device.
