### ISSUE TITLE
Calculator Crashes on Older Versions of Android

### ISSUE THREAD

**Issue by S-Bartfast** [cgeo/cgeo#6751]
##### Detailed steps causing the problem:
Simply try to open the calculator

##### Actual behavior after performing these steps:
The dialogue crashes with a message:
![image](https://user-images.githubusercontent.com/6573522/31306449-ca17eb6a-ab97-11e7-991e-52f3fd502b34.png)

Although the message says 'c:geo' has crashed it is actually only the calculator dialogue itself that dies and you are returned back to the regular c:geo app once you click the "OK" button.

Officially we are meant to support back to API 14 (Ice Cream Sandwich) however the calculator crashes when run on API 15 (also Ice Cream Sandwich).  In particular it seems to be line 735 of 'CoordinatesCalculatorDialog.java' that causes the problem, which reads:
`ButterKnife.findById(view, viewId).setVisibility(visibility);`

I haven't investigated this other than to note which line the failure occurs on.

Note the calculator seems to work fine on API 19 (KitKat).

**Comment by Lineflyer** [comment]
So this means, that in the currently release version the calculator will not work below API16 ?

**Comment by Lineflyer** [comment]
Today I had the chance to test the current nightly on a device running Android 4.0.3 (which should be API 15 ?!).

HTC One V, Android 4.0.3, c:geo 2017.12.24-NB

I can start the calculator and use it normally as far as I tested.

Additionally I tested on Android 4.1.2 (API 16) and Android 4.4.2 (API 19) which also works normally.

**Comment by pstorch** [comment]
The IDE highlights incompatible API calls. There is no such case in the `CoordinatesCalculatorDialog`.

**Comment by Lineflyer** [comment]
We menwhile raised the minSDK to 16. So if this problem was relevant it is no longer.
