### ISSUE TITLE
Subtitle not updated on zoom

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6755]
When we show the map, we display the number of caches as sub title of the activity. This information is updated on all kinds of actions to reflect the number of currently visible caches.

However, with the beta map opened for multiple caches (not live map), the information is only updated on switching the display on/off (probably onResume of the activity), not when zooming in or out.

**Comment by Lineflyer** [comment]
Confirmed still existing with 2018.02.15 (nightly with new map as default)

**Comment by rsudev** [comment]
This was fixed with the fix for #6395 in faf9cbe549e0c766c45ded0db6462f6ef8424c6b
