### ISSUE TITLE
OC sites might require a caption for log images

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6771]
The `caption` field for log images is documented as `optional` in https://www.opencaching.de/okapi/services/logs/images/add.html. But as discussed here: https://github.com/opencaching/okapi/issues/395 and here https://github.com/opencaching/okapi/pull/392#commitcomment-16760872 most OC sites require it.

Currently c:geo doesn't require a caption. How should we handle it? Make it a mandatory inputfield per `Connector` or set a default value?

**Comment by Bananeweizen** [comment]
Make it mandatory per connector. If we provide a default value for sites where that is not required, we would actively sabotage (potentially) existing mechanisms on the websites to produce more useful captions. E.g. if the website can generate a default caption in a localized version fitting the language of the current user, our constant caption would not be localized any more.
(and this is also the most "simple to use" version of what we can do, which should always have high priority when evaluating alternative implementations for requirements)
