### ISSUE TITLE
Calculator Crashed on Screen Rotation

### ISSUE THREAD

**Issue by S-Bartfast** [cgeo/cgeo#6776]
This was probably introduced with #6759 and seems to be caused by a change to the 'Plain Format' text field.  The change gets triggered sometime between when the 'textListener' is added in `onCreateView(...)` and when the calculator's state is loaded in `onResume()`.

The actual crash is caused by accessing the `currentFormat` variable before it is initialised but I can't for the life of me workout what is causing the text to be changed prior to the `onResume()` call.  In any event simply protecting the reference to `currentFormat` with "if null" checks alleviates the problem but I would have preferred to isolate the cause of the text changed event in the first place but can't seem to find it.

**Comment by Lineflyer** [comment]
Labeled this one as `high` as a reminder it should be solved before going live.
