### ISSUE TITLE
New solution checker - Cache description not visible

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6787]
The description of GC7DWAB is partly invisible.

Perhaps related to the new gc.com solution checker embedded in the description of this cache?!

I did not have time and patience to search if this is related to that new checker feature.

**Comment by Lineflyer** [comment]
And btw: The checker is not shown...and of course not yet supported to be used from c:geo

**Comment by Lineflyer** [comment]
Another example: GC7DVBM

**Comment by pstorch** [comment]
There is a new `div` block included after the long description:
```
<div id="ctl00_ContentBody_uxCacheChecker" class="CoordChecker">
 ```
