### ISSUE TITLE
Option to open Android share menu after field note export

### ISSUE THREAD

**Issue by timatlee** [cgeo/cgeo#6790]
In the current version of C:Geo, I will export field notes to a text file for later import into GSAK.

It would be helpful if, after export, the Android share menu could be opened, so that the note file could be sent by email, to Dropbox, etc.

I can presently do this with personal notes (I think), but the export format is not in what GSAK expects.

**Comment by moving-bits** [comment]
Sharing after export is implemented meanwhile (don't have PR number at hand), so let's close this issue.
