### ISSUE TITLE
Support gc.com solution checker

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6792]
gc.com recently introduced an own solution checker / coordinate checker as an alternative to external geochecker solutions.

At the moment c:geo just ignores the presence of this checker and does not display it.
c:geo should support the checker in some way.

- It could be done in a combined approach also enabling #6782 (handing coords over to external geochecker).
- Implementation wise it could either be done using a dedicated menu with coordinate input or implement it somehow into the existing waypoint menu (Add waypoint and have a possibility to use the WP coords as input for the checker).

**Comment by MagpieFourtyTwo** [comment]
This topic is over half a year old now and did not even get a comment.
Will it be implemented or is it not possible?
Just asking cause it became a real issue with mysteries
and it's getting worse as more and more listings use this checker ...

**Comment by Lineflyer** [comment]
The fact, that is is listed here means, that an interested open source developer can pick it up and work on it.
I agree, that the complete lack of info about an existing checker is not ideal, however as we are a small open source team, we need to wait for someone able and willing to implement it.
So I cannot give you any time plan on that.

**Comment by Bananeweizen** [comment]
Well, we actively suppressed the checker in #6787, since it destroyed the cache description. Since there there hasn't been any effort spent to fix that. I'm also not entirely sure how to do that, but I tend to use the URL of the cache as a checker in the menu.

**Comment by Lineflyer** [comment]
If it shall be an easy minimum approach, we could show a predefined string (similar to: This listing contains table elements) which informs the user, that there is a checker only visible on the website (and optionally link to the cache page in the checker menu).

BTW: Seems the checker is also not supported via API and also not shown in API using apps.

**Comment by MagpieFourtyTwo** [comment]
The "easy minimum approach" sounds good to me.

I do not expect to see this <censored> reCAPTCHA checker working in whatever smartphone app anyway, esp. before they implement it in the API (which will be really hard, as reCAPTCHA's first target is to *prevent* access by application, thus do not understand, why they invented it at all, even against groundspeak's smartphone trend, if not to just compel people to visit the website), so a hint will be the only solution for a long time, anyway.

An additional link to the listing would be even more, would call it a "first class solution", so even DAUs, who do not know about the "open in browser" menu entry will be able to find the checker.  ;)

In any case:  Thanks a lot for doing it!

Cheers, Mag'

**Comment by pstorch** [comment]
> BTW: Seems the checker is also not supported via API and also not shown in API using apps.

Interesting, I check Geocaching4Locus and the official Groundspeak App. Both don't show anything that there is a solution checker.

**Comment by Matze2** [comment]
For me it is absolutely enough to show an indication that there is a gc.com checker on the web page.

Usually I do not use the checker within c:geo to verify coordinates but to re-open the checker page because it contains hints or further info for the final or stages.
This feature is not available in the gc.com checker anyway.

**Comment by Bananeweizen** [comment]
I have a simple approach implemented, which basically detects the checker and adds a sentence like "GC checker available at ..." to the description of the cache. But that still needs some testing since it requires being able to open the website of the cache again, which sometimes seems to be impossible (depending on what the user has chosen in the "which app to use to open this file" dialog).

**Comment by Lineflyer** [comment]
That problem is probably the same as in the case, where we append the info about the description containing table elements. It also contains a link to the cache page.
I think this solution is more than OK also in this case.
