### ISSUE TITLE
Coordinate Parser Needs Work

### ISSUE THREAD

**Issue by S-Bartfast** [cgeo/cgeo#6802]
I keep observing wacky interpretations for things being presented to the coordinate parser, particularly for the 'Plain' format parser, such as this:
![image](https://user-images.githubusercontent.com/6573522/32008762-97d43ddc-b9f4-11e7-8efd-9725af937731.png)

No real idea what's going on there but suffice to say it probably shouldn't be being parsed as a valid GeoPoint.

To play with the parser yourself create a new waypoint and open the calculator, change the format to 'Plain' and anything it considers 'valid' will be displayed in white (like above) and anything invalid will have the result displayed in grey:
![image](https://user-images.githubusercontent.com/6573522/32009009-5574e1e8-b9f5-11e7-9991-7f829ab329fa.png)

**Comment by UniQP** [comment]
I think a good next step is to extract a failing unit test.

**Comment by S-Bartfast** [comment]
Yeah, I haven't even looked at unit tests yet.  I should probably get onto that next.

**Comment by S-Bartfast** [comment]
Sorry, still haven't got to this one.

Just off the top of my head these are additions that need to me made:

* Check for non legal characters
Other than the first letter the only valid characters I can think of are `0-9`, `.`, `,`, `'` ,`"`, `°` and ` ` (space) 
(though we may want to add other min/sec characters).
* There should only be one of these characters (`.`, `,`, `'` ,`"`, `°`)
* There should be at most 3 groups (using `'` ,`"`, `°` and ` ` as delimiters)
 If we want to add `.` and `,` as delimiters there could be up to 4 groups.
* there should be only one group after the decimal point

If any of these conditions are not met the formulation should be considered invalid.

In terms of providing feedback to the user if a formulation is invalid it would be good to know which character was the first to cause it to fail.  I would like to use this information in conjunction with #6842 (Implement "Result Highlighting" in the Calculator) to help guide the user to creating valid formulations.

**Comment by Matze2** [comment]
This list is good. I compiled a similar one while I was experimenting with stricter regexp patterns.
From looking through the GeoPointParser code and its usage the problem seems to be that it combines two modes into one:
- trying to parse coordinates from text; this includes also passing latlon in one line; here it's hard to require the stricter settings
- trying to parse single coordinates (lat and lon separated); here it is possible to be very pedantic which gives the user an immediate feedback if the input is valid or not

So there could be a "precheck" phase for the second case which implements all the additional checks mentioned above.

**Comment by pstorch** [comment]
This issue was now closed automatically by 9ad01aa55999b05f9b256caf90cc6e0dff090c6c. But I don't know if it solves it completely, because there are more checks mentioned above.

Schould we keep it open?

**Comment by Matze2** [comment]
There were so many issues linked to each other that it was difficult to have an overview what is are already open, pending an done.
I would prefer to start with new issue(s) based on what is now really in master and release.
One example would be invalid input handling beyond regexp mismatch, e.g. negative variable values.

**Comment by S-Bartfast** [comment]
>This issue was now closed automatically by 9ad01aa

How did that happen.
It hasn't even been discussed yet?

> I would prefer to start with new issue(s) based on what is now really in master and release.

That's exactly what this is is it not?

**Comment by UniQP** [comment]
@S-Bartfast The commit 9ad01aa55999b05f9b256caf90cc6e0dff090c6c fixes your initial example (and many more). Thus, the question is whether you want to open new issues for remaining problems or reopen this one.

**Comment by S-Bartfast** [comment]
I'm just surprised the issue got closed without my having a chance to review it.

Are you sure it addresses the list of issues:
>* Check for non legal characters
>* There should only be one of these characters (., ,, ' ,", °)
>* There should be at most 3 groups (using ' ,", ° and as delimiters)
>* There should be only one group after the decimal point

Also, is the failing character identified?

These are the things I'd like to discuss before closing.

**Comment by UniQP** [comment]
@S-Bartfast Feel free to reopen the issue.

I'm sure the parser will make a good job in rejecting invalid coordinates now. However, since the parsers use regular expressions, you will not get a parser-defined error ("the first failing character").

**Comment by S-Bartfast** [comment]
Hmm, just ran a few checks and it certainly doesn't seem to work for me.

Just a couple of examples:
> `N 1`
`E 1`

Fails (when I should pass)

>`N 1 2.3+4`
`E 1 2.3+4`

Passes (when I should fail)

**Comment by S-Bartfast** [comment]
>@S-Bartfast Feel free to reopen the issue.

I'm not so sure that I can.
I think I need a "collaborator" to open it again.

**Comment by pstorch** [comment]
I've reopened it

**Comment by Matze2** [comment]
Hmmm.... I was so enthusiastic and installed the latest nightly but now...

![screenshot_2017-11-23-13-06-34](https://user-images.githubusercontent.com/12542802/33172267-bb5046ea-d04f-11e7-8e86-09fbe4c34b2a.png)

Maybe the pattern matching fails. When I have time I will have a look tonight.

**Comment by pstorch** [comment]
These brackets will give us some more headaches :thinking:

**Comment by S-Bartfast** [comment]
>These brackets will give us some more headaches 🤔

No, they're perfectly fine.

Not sure what's wrong with the nightly build there but in there but on my 'developer' build it works as expected:
![image](https://user-images.githubusercontent.com/6573522/33177329-29460740-d0b2-11e7-8019-8f50b7e594b8.png)

**Comment by S-Bartfast** [comment]
>Not sure what's wrong with the nightly build there

Oh, hang-on.  The feature hasn't been imported into the nightly yet.

**Comment by Matze2** [comment]
Oh, so sorry for the confusion. I mixed up the PRs. :confused:

**Comment by S-Bartfast** [comment]
>Oh, so sorry for the confusion. I mixed up the PRs. 😕

Yeah, it's all pretty confusing at the moment.
Sorry ):

**Comment by UniQP** [comment]
@S-Bartfast 
> N 1
> E 1
> Fails (when it should pass)

The `GeopointParser` parses `S1°` but not `S1`, since the latter is often used as abbreviation for “Stage 1”.

> N 1 2.3 + 4
> E 1 2.3 + 4

`GeopointParser.parseLongitude(N 1 2.3 + 4)` throws an exception, so this is not an issue of the `GeopointParser`.

**Comment by S-Bartfast** [comment]
>GeopointParser.parseLatitude(N 1 2.3 + 4) throws an exception, so this is not an issue of the GeopointParser.

Arrr, right you are!
The issue was indeed in the zero padding section I had put in the calculator, and a fix has been submitted.

>The GeopointParser parses S1° but not S1, since the latter is often used as abbreviation for “Stage 1”.

Okay.
`N1°` does indeed work, however `N 1.0°` seems to fail.

Is there any reason `N 1.0°` should not be valid?

**Comment by UniQP** [comment]
> Is there any reason N 1.0° should not be valid?

The format is currently not supported.

**Comment by pstorch** [comment]
> Is there any reason N 1.0° should not be valid?

As far as I know this is not a valid coordinate, is it?

**Comment by pstorch** [comment]
Hmm, I don't see such a format there. But I'm on mobile at the moment.

**Comment by UniQP** [comment]
Search for "HDD".

**Comment by pstorch** [comment]
I found HDD but it's not a format with a decimal number and a degree sign at the end.

**Comment by UniQP** [comment]
> I found HDD but it's not a format with a decimal number and a degree sign at the end.

Yes, but we don't support `N 1.0` either.

**Comment by S-Bartfast** [comment]
>>Is there any reason N 1.0° should not be valid?
>
>As far as I know this is not a valid coordinate, is it?

Sure it's a valid coordinate.  It's "one degree north", as in just above the equator.  It seems strange to support `"N 1°"` but not `"N 1.0°"`.  Is there any reason for this?

>Yes, but we don't support N 1.0 either.

I think we should.  I see we support '+' and '-' for coordinates such as "1.0" but I think we should support the hemisphere notation for DegDec format like we do for the other formats, even if it's not officially endorsed.  While it's not officially correct it is clear what's meant and is unlikely to be misconstrued into something else.

**Comment by UniQP** [comment]
@S-Bartfast Can you please open a separate issue to discuss the support of this coordinate format?

**Comment by S-Bartfast** [comment]
>Can you please open a separate issue to discuss the support of this coordinate format?

I'll let it go.  It's really not that important.

However, in regard to this issue, is there any reason `"N 1°"` is considered valid but `"N 1.0°"` isn't?  Surely they should either both be valid or both be invalid, or is their something I've missed?

**Comment by pstorch** [comment]
Can someone point me to a description where "N 1.0°" is a valid coordinate? I mean a degree sign after the decimal separator?

**Comment by S-Bartfast** [comment]
>Can someone point me to a description where "N 1.0°" is a valid coordinate? I mean a degree sign after the decimal separator?

I'd also be interested to see a description where "N 1°" is a valid coordinate. That is a degree sign _without_ a decimal separator.  In particular I'm wondering why "N 1°" is valid but "N 1.0°" is not.

I appreciate there was concern with possibly validating "S 1" formulations but is there a reason "S 1°" is valid and "S 1.0°" is not since neither are listed in [geocaching.com (section 4.2.)](https://www.geocaching.com/help/index.php?pg=kb.chapter&id=128&pgid=811)?

**Comment by pstorch** [comment]
Maybe my issue is that I always think in DMS and there the degree value is an integer (not a decimal). But we also support decimal degree format, so both should be valid. Very seldom, but valid.

https://tnp.uservoice.com/knowledgebase/articles/172110-latitude-longitude-formats-and-conversion

**Comment by SammysHP** [comment]
We had the same discussion some months ago when @UniQP refactored the coordinate parsing.

**Comment by S-Bartfast** [comment]
>We had the same discussion some months ago when @UniQP refactored the coordinate parsing.

Huh, maybe I should have re-opened that issue.  Didn't realise it was worked on just before.

**Comment by Lineflyer** [comment]
@eddiemuc

Maybe you can take a sidelook into this issue and judge whether this is still relevant while working on the calculator.

**Comment by eddiemuc** [comment]
Wow, a very long discussion.

This issue does not apply to the new plain coordinate parsing implementation (not merged to master yet and not finished), so if we decide to take it over then we can close it. I am sure that new, similar issues will pop up for other aspects though.

I would leave this issue open until we decide how to deal with global variables.

**Comment by fm-sys** [comment]
@eddiemuc do you know if we can close here?

**Comment by eddiemuc** [comment]
Yes we can
