### ISSUE TITLE
android-gradle 3.0

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6805]
The android-gradle plugin has been updated to 3.0. There are several breaking changes in the gradle build script. I'm preparing a pull request. This issue is mostly to make every developer aware that Android Studio must be updated to 3.0 also when that PR is merged. Otherwise your IDE will not work correctly.

You can already update Android Studio now, you don't need to wait until the PR is merged.

**Comment by pstorch** [comment]
The PR is merged and we have updated to gradle 3.0. Is there anything left?

**Comment by Bananeweizen** [comment]
I think I still have to re-enable the DEX method counter plugin.

**Comment by bekuno** [comment]
The dexcount plugin downgrade was in Rev cf69dccc44f495479caa7e985257eed0b6ca3797 (18.06.17), 
the activation with Rev 3be2e512a72e61d36227b855f582e26f32af1100 (30.06.17).

@Bananeweizen Please reopen this issue if you did not have this in mind.
