### ISSUE TITLE
HTML Tags <dl>, <dt>, <dd> are ignored

### ISSUE THREAD

**Issue by sdennler** [cgeo/cgeo#6807]
##### Detailed steps causing the problem:
The cache [OC12C6D](https://opencaching.de/OC12C6D) uses the HTML Tags dl, dt and dd to format the questions. They look fine on opencaching.de but are shown as just one text whit out any spaces in c:geo. Just open the cache OC12C6D in c:geo to see it.

##### Actual behavior after performing these steps:
Cache description in c:geo:
![screenshot_2017-10-29-13-29-32](https://user-images.githubusercontent.com/834472/32143969-f80d076e-bcb1-11e7-859c-2112bd8a6c78.png)

##### Expected behavior after performing these steps:
It would be nice to have it shown more similar to the website:
![dl screenshot oc](https://user-images.githubusercontent.com/834472/32144015-bc478c9e-bcb2-11e7-8468-cb42838f8396.png)

Or at least that they are handled like br or p tag.

##### Version of c:geo used:
2017.10.23

##### Is the problem reproducible for you?
Yes

##### System information:
One device I tested it:
```
--- System information ---
Device: KC-S701 (KC-S701, KYOCERA)
Android version: 4.4.2
Android build: 102.0.1920
c:geo version: 2017.10.23
Google Play services: enabled - 11.5.09 (036-164803921)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: yyyy/MM/dd
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (1.2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1.2 GB free) external
Geocache data: /storage/sdcard1/Android/data/cgeo.geocaching/files/GeocacheData (20.7 GB free) external
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (38.9 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   opencaching.de: Logged in (Login OK)
   opencaching.pl: Logged in (Login OK)
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by SammysHP** [comment]
The webview handles only a small set of HTML-tags. https://stackoverflow.com/questions/23641630/android-textview-display-html-with-dl-dt-tags

**Comment by sdennler** [comment]
Looks great! Thank you @moving-bits for adding this!
