### ISSUE TITLE
Log not stored when only date changed

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6812]
- open cache
- menu, log cache
- change date
- press back

=> offline log is not stored.

2017.10.27-NB-ea62d13

**Comment by Lineflyer** [comment]
AFAIR this is a side effect of a change done by @Bananeweizen a while ago to avoid storing offline logs when in fact nothing has been written into the log text field. 
IMHO a changed date or log type should also trigger saving the log offline,

**Comment by pstorch** [comment]
I just had a look at it. We could remember the old date and compare it when going back. Then save if it is changed.
But what about the other things? LogType, Favorite Points, Attached Image, Log Password (in case of OC), Trackable Actions, ...
I know, we don't even save everything in an offline log, but somehow I would expect it. What do you think?

**Comment by SammysHP** [comment]
Try to save as much as possible whenever something changes.

**Comment by pstorch** [comment]
What was the reason to not change the log if the new logtext is empty? Preventing the user from accidentally deleting the logtext?  Does it not contradict to "save every change"?

Maybe a confirmation dialog would be better here (similar to the one proposed for waypoint changes). To make it explicit what the user wants.

**Comment by pstorch** [comment]
This should be fixed by now. Can someone retest?

**Comment by Lineflyer** [comment]
Tested and fixed.
