### ISSUE TITLE
Waypoint userNote not forwarded to Calculator on first open

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6821]
Due to #6804 an existing userNote is not forwarded to the Calculator if it is used the first time. (no calculator state yet).

Since: ceb2addd0b34beb7e68d483fb5e45d0324542443

**Comment by S-Bartfast** [comment]
This is all getting very convoluted...

Given the 'notes' are no longer considered part of the calculator's state is their any reason were tagging it along with the state as a pair?  Would it not be simpler to simply set the calculators notes to be the exact same EditText as that used by EditWaypoint?

I'll see if I can't find a neater way...

**Comment by S-Bartfast** [comment]
Just thinking, while I'm here do we want to tack these notes onto the bottom of the 'Coordinate Input Dialog' as well.  Seems these notes could well be useful when entering coordinates directly too.
