### ISSUE TITLE
Calculator Notes Cleanup

### ISSUE THREAD

**Issue by S-Bartfast** [cgeo/cgeo#6823]
#6715, #6816 and #6821 are all addressing the calculator notes issue and all were closed before I was able to be involved with the changes, so I thought it would be best to open an issue of my own to provide input.

As it stands the 'calculator notes' have been removed from the 'calculators state' but seem to be tagged onto the state externally with an 'ImmutablePair' object.  In my mind if the notes field is essentially intended to be independent of the calculator itself it would be better to simply access the Waypoint's note data directly than tag it onto the calculator's state and kind of 'carry' them around together.

I have an implementation of this and are mainly creating this issue so as to have a branch in which to commit this implementation.

**Comment by S-Bartfast** [comment]
Okay, I've submitted a pull request with the implementation discussed above.

One small point to think about is what should happen to notes entered/modified in the calculator when the cancel button is pressed (or the back arrow is clicked).  Previously, when the notes were part of the calculator's state it was easy to workout when they should be modified but now that we are modifying notes that are essentially outside the calculator additional care will need to be taken.  In the implementation submitted such modifications will be discarded when the user 'cancels' the calculator.  This is to enable the user to 'Undo' an erroneous modification to the notes such as unwittingly deleting them all :eek:.

It would be easy to change this such that the 'EditWaypoint's UserNotes field is updated whenever the calculator is closed and allow the user to 'Cancel' the 'EditWaypoint' to discard the changes.  While I think this is a better option in many respects I fear it is getting a little convoluted and may cause undue stress and anxiety on out beloved users in the event that they accidentally delete the notes, 'Cancel' the calculator and find the waypoint notes blank.  In such an event they would most likely click 'Cancel' again (in the Waypoint Editor) and re-open the waypoint to discover they had not in fact lost their User Notes after all but you know, to paraphrase Douglas Adams:
>Stress and nervous tension are now serious social problems in all parts of the Galaxy and we should all do our best not to exacerbate the problem.

**Comment by pstorch** [comment]
Yes, this needs to be improved.
I'm sorry, I just hurried a bit, so that the issue is solved before the release. The solution is not ideal.
Now we have time to properly think about a better/cleaner way.

It's a bit tedious to have these three stacked dialogs `EditWaypointActivity`, `CalculatorInputDialog` and `CoordinatesCalculateDialog` sharing (partly) the state of the waypoint and have individual save actions. 

But having the notes field directly change independent of the `save` action in the calculator is not good, I think.

**Comment by pstorch** [comment]
@S-Bartfast 
> Previously, when the notes were part of the calculator's state it was easy to workout when they should be modified but now that we are modifying notes that are essentially outside the calculator additional care will need to be taken

Maybe I don't get it. Isn't it the same behavior as before, just with a cleaner solution? 
If you click on the save icon all changes (CalcState + UserNotes) are forwarded to the EditWaypointActivity. If canceled all changes (CalcState + UserNotes) are discarded.

**Comment by S-Bartfast** [comment]
>If you click on the save icon all changes (CalcState + UserNotes) are forwarded to the EditWaypointActivity. If canceled all changes (CalcState + UserNotes) are discarded.

The concern is what should happen if the user were to click "Save" on the calculator, then clicks "Cancel" after. This implementation will overwrite the waypoints "User Notes" with the calculators "Notes" when the "Save" button is clicked and if the "Cancel" button is then clicked after the user will be sent back to the "Edit Waypoint" with the now canceled notes displayed. This probably is what should be done though as otherwise their would be no way to save note changes until you have valid coordinates.

The other workflow I discuss above is to _always_ display the note changes (even if "Save" were never clicked) and allow the user to make the determination as to whether they want to keep those note modifications when they either "Keep" or "Cancel" the changes to the waypoint itself. Although I actually think this is a slightly better approach I have not implemented it this way as I was concerned it may confuse users.

Something I think may be worth doing (but I'll do it as a separate ticket) is to add the "Notes" field to the  Coordinate Input Dialog.  There are two reasons I'm interested in adding the field to the Coordinate Input Dialog.  Firstly is the fact that users may well want to be able to see their notes while entering coordinates  (currently they have to cancel their input to re-check their notes).  And secondly if the same "User Notes" field is display in all three dialogs (being the Edit Waypoint, Coordinate Input and Calculator) it will be more intuitive to users that they are in fact the same "Notes" and that modifications made in one dialog will affect the 'same' note field in the other dialogs.  Currently with "User Notes" in the Edit Waypoint, nothing in Coordinate Input and "Notes" in the Calculator it may not be readily apparent that they are in fact the 'same' notes.  Using the same nomenclature (ie. calling the field "User Notes" in the calculator rather than just "Notes") would help but it would then raise the question as to why the regular "Notes" are not shown in the calculator.

**Comment by pstorch** [comment]
I'm still thinking about why I did it so complicated with the userNotes to the calculator dialog. Maybe I just thought it must be similar to the CalcState. Then I was thinking why is the CalcState not used directly from the EditWaypointActivity like the userNotes field? It would vastly simplify the management of the state handling and the forth and back of the variables. Would have an impact on the save and cancel logic for sure.

Can we improve the three dialogs to some more extend? I'm still not sure what the best way is, just thinking:
If I once started to calculate the coordinates, the Coordinate Input Dialog is just superfluous and in the way. Wouldn't it be better to change the type of the waypoint to be a "calculated waypoint" and get rid of the Coordinate Input Dialog?
At the moment it is: 
`EditWaypointActivity -> press on the coordinates -> CoordinatesInputDialog -> press on calculate coordinates -> CalculatorDialog -> press on save -> EditWaypointActivity.
`
So on the way back the CoordinatesInputDialog is already skipped. If I want to work on the calculation again, I have to go via the CoordinatesInputDialog again.

What about having an "all in one" dialog? Once the type of the waypoint is changed to a "calculated waypoint". The read only coordinates are replaced with the calculator buttons and the variable fields show up. The two notes fields and the rest of the page are kept as is. That would also work towards #6697. You wouldn't show the read only coordinates anymore which show some arbitrary coordinates as long as the calculation is not valid.

**Comment by Matze2** [comment]
Just wrote something similar in #6697 without reading your comment here. I think the biggest problem is that we always offer both ways of coordinate input. If there would be checkbox or something similar to make a waypoint a "calculated waypoint" then things should get much easier (as you described it above).

**Comment by S-Bartfast** [comment]
We could potentially get rid of the Coordinate Input Dialog all together and just go directly to the calculator in all instances.

We would probably want to add "Use Cache Coordinates" and "Use Current Coordinate" buttons to the calculator but it could be done.

We could also potentially add some means of switching between 'buttons' and 'typing' in values but have variables available even in typing mode.

**Comment by Matze2** [comment]
Let me show what I had in mind:
![calculatemode](https://user-images.githubusercontent.com/12542802/32419940-15a4ce02-c283-11e7-9c3d-d7402452a845.png)
This is driven by the "either-or" assumption. Either you use the calculator for the waypoint or the direct coordinate input. Not both. So why showing a big dialog supporting both.

If checkbox is checked then a tap on the coordinates opens the calculator.
If checkbox is not checked then the original coordinate input dialog is opened.

Apart from that I agree in showing the waypoint notes in both dialogs (maybe read-only just like in the waypoint overview where both notes are shown concatenated).

**Comment by Matze2** [comment]
Thinking further. Shouldn't "Bearing" and "Distance" be part of the coordinate input dialog (and probably also in the calculator)?
I found it always annoying that I lost the original coordinates after I entered something there.

**Comment by S-Bartfast** [comment]
The "Either-or" idea definitely has merit.  It's probably not worth implementing before the release but I'll investigate it in due course, though at the moment I'm leaning towards @pstorch's idea of incorporating both the Coordinate Input and Calculator Dialogs into one.

By the way, the reason for the convoluted process of getting to the calculator was to provide as little disruption to the previous implementation as possible.  I was originally working on this as more or less an experimental feature and I wanted for it to be able to be adopted into the main product with as little disruption as possible.  As it is the only disruption to the existing workflow is the addition of the extra button to the Coordinate Input Dialog and the rest of c:geo functions as it did:
![image](https://user-images.githubusercontent.com/6573522/32421527-7dd74782-c2e9-11e7-9737-f4cac2548a6f.png)

Given this product is no longer 'experimental' as such it is probably worth focusing more on the usability of the feature than minimising disruption of its introduction.

**Comment by Matze2** [comment]
I understand the history of this feature. I agree with introducing a new feature in a non-disruptive way first.

Whatever will be done to improve this there should be a medium-term plan. I see the following problems with the waypoint editor:

- "Bearing" and "Distance" modify the coordinates and - even worse - you lose the original coordinates once you save the waypoint. In my opinion they should be part as the coordinate input dialog(s) and ideally the original data (original coordinates, bearing, distance) should be kept to be able to change it. Currently you need to duplicate the waypoint to keep that information.
- Global variables for the waypoint calculator formula. Currently I create dummy waypoint containing all variables and from there I copy-paste them into the calculator notes.
- The radio button group to set a waypoint as cache coordinates in c:geo and/or in website are also more actions and do not really belong to the editor.

Whatever the direction is these items should be kept in mind. But maybe it's only me that has problems with the way how the waypoint editor works. :)

Sorry this now gets off-topic.

**Comment by S-Bartfast** [comment]
I'm going to close this issue as my intention with it was just to clean up the code in regard to #6715, which has been done.

Feel free to continue the discussion of improvements to the user experience itself in #6833 if you with.
