### ISSUE TITLE
Mojibake instead of UTF-8 in device names

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#6825]
send2cgeo says: “Device 'MirDesir??e' was successfully added to browser […].”

I’d have expected an é, not two question marks ☺

**Comment by SammysHP** [comment]
Hi @mirabilos,

this repository is for the Android app c:geo. Any issues with send2cgeo can be reported at [cgeo/send2cgeo](https://github.com/cgeo/send2cgeo).
