### ISSUE TITLE
User created waypoint has two editable note areas

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6826]
##### Detailed steps causing the problem:
- Add a new waypoint
- There are two editable areas "Note" and "User Note"

##### Actual behavior after performing these steps:
Two areas where one is enough.

##### Expected behavior after performing these steps:
"Note" area which is usually read-only for imported waypoints is not visible because it makes no sense for user created waypoints.

##### Version of c:geo used:
2017.11.05-NB-cc9328b

##### Is the problem reproducible for you?
Yes

##### System information:
On demand.

##### Other comments and remarks:
Not sure if this was always the case.

**Comment by pstorch** [comment]
I'm not sure if we should hide the "Note" area for user defined waypoints. There is a possibility to duplicate an imported waypoint and this might contain a note. Wouldn't it be good, if the original description is kept visible?

**Comment by Matze2** [comment]
For "duplicate" I agree. But should be the "Note" editable in this case?
For a waypoint created from scratch it looks strange to me to have two areas and -  even more - both editable.
Now that the waypoint edit dialog is in focus anyway I just wanted to raise that question.

**Comment by SammysHP** [comment]
User defined waypoints should have only one note textarea. If a waypoint is duplicated and has a description, it should be merged with the editable field.

**Comment by pstorch** [comment]
If the waypoint is created from scratch the second note field doesn't make sense, agree.
Making the copied note field read only doesn't feel right. Why should a user not be able to edit it. It's his own copy?

OK, let's think, what we can improve here. What about copying the original note field to the user-note field in case of duplicating? And hide the note field for user defined waypoints, if it is empty?
Then we would have the original note in the field the user can see and edit and at the same time we can get rid of the superfluous field.

**Comment by pstorch** [comment]
@SammysHP looks like the same idea. I just took longer to describe it.

**Comment by Matze2** [comment]
Perfect. 👍

**Comment by Kitzibua** [comment]
I like this approach, as I always found it stange why there are two note fields and on some waypoints I can edit both, on others just one.
I would even like to go one step further and also hide the "Notes" field on server provided waypoints in case it is empty. This would probably help to avoid confusion and displaying the empty Notes box gives no benefit for the user.

**Comment by pstorch** [comment]
I'll start here
