### ISSUE TITLE
Prevent waypoints imported from GPX from being deleted on cache refresh

### ISSUE THREAD

**Issue by jeancaffou** [cgeo/cgeo#6828]
- Import GPX file with waypoints
- GPX has a custom waypoint
- Refresh cache (download and parse html)
Waypoint is deleted

##### Expected behavior after performing these steps:
Waypoint should stay added just like a custom waypoint added directly in cgeo, with waypoints from cache page being added as well.

**Comment by pstorch** [comment]
Are you sure it got deleted? Isn't it merged with some waypoint from the webpage?
Do you have an example GPX to test?

**Comment by jeancaffou** [comment]
See attached gpx file generated with custom software. Take note of the custom final waypoint. The cache in question is GC71W5D
[caches.zip](https://github.com/cgeo/cgeo/files/1445986/caches.zip)

Before refresh the cache type is traditional (generated by the software) with final waypoint coordinates
![before](https://user-images.githubusercontent.com/922860/32438699-c0748076-c2eb-11e7-9b94-e9704df8d307.png)

After refresh the cache is changed to mystery (this is ok), but the final waypoint **GH**71W5D is deleted or replaced with **FN**71W5D with no coordinates
![after](https://user-images.githubusercontent.com/922860/32438698-c059aec2-c2eb-11e7-89e3-a87503ae27a8.png)

**Comment by jeancaffou** [comment]
Importing two GPX files however does NOT overwrite / delete the waypoint, but it merges them.

**Comment by jeancaffou** [comment]
Importing two GPX files however sometimes seems to be working OK - merges waypoints

**Comment by pstorch** [comment]
The waypoint from the GPX file is not recognized as user defined. So all non-user-defined waypoints are discarded on update. 
Do you create the GPX from GSAK? Are you able to extend it?
If the `<wpt>` element contains a child like `<cgeo:userdefined>true</cgeo:userdefined>` it should work. You also need the xml namespace declared in the root element: `xmlns:cgeo="http://www.cgeo.org/wptext/1/0"`

**Comment by jeancaffou** [comment]
Yes, adding a custom child element seems to be working.

**Comment by pstorch** [comment]
Thanks for your feedback. Is the solution sufficient and can we close the issue?

**Comment by jeancaffou** [comment]
Yes, you can close the issue. Thank you!
