### ISSUE TITLE
Nearby search result missing PM caches for BM users

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6830]
Reported on support mail (did not have time to reproduce yet).

- Basic member
- With version 2017.10.10 it shows me both BM & PM caches in the nearby search result.
- With version 2017.10.23 only BM caches are returned.
- Tested on the same location with same device (uninstalled new version and tested older version).

Are there any possibly related code changes between those versions?

**Comment by Matze2** [comment]
Cannot reproduce it with current nightly and with no version in the past. And this is a feature I use quite often (home zone pocket query replacement for BMs).
