### ISSUE TITLE
Save for offline from map now also visible if all visible caches are already stored

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6831]
Reported on support mail for current beta version (2017.11.01-RC2):
On the map, with some caches visible, when opening the menu there's an option to save them for offline use. Before, that menu option appeared only if there were at least one cache not yet saved. Now it appears allways, even if all visible caches are already saved on c:geo lists.

@Bananeweizen 
Could this be related to your change 7c797390283c514240cd73ddab16c9b89aef4c85 ?

**Comment by pstorch** [comment]
I think we can close this one, as we want to be able to save all visible caches to a new list regardless of if they are already stored anywhere else, see #6654.
