### ISSUE TITLE
Support the Opencaching GPX Extension

### ISSUE THREAD

**Issue by following5** [cgeo/cgeo#6837]
All Opencaching sites except for Opencaching.US meanwhile add OC-specific information to GPX files within a new `<oc:cache>` element. Would be nice if c:geo could evaluate this and read 

- [ ] OC cache types like "Moving Cache"
- [ ] OC container sizes like "Nano"
- [x] the OC log password requirement flag

from GPX files. The last one is the most important: c:geo will currently not detect password requirement from GPX files and not prompt for a log password. This makes it impossible to log those caches as "found".

The complete documentation is here: https://github.com/opencaching/gpx-extension-v1/blob/master/schema.xsd

**Comment by pstorch** [comment]
This is already implemented, see #6777

**Comment by following5** [comment]
Oops.

What has been implemented is the log password flag and the crosslisting cache codes. So the OC cache types and container sizes are still to do.

**Comment by pstorch** [comment]
Oh, ok. I haven't looked into the details. Then let's keep this for the remaining features.

**Comment by pstorch** [comment]
@following5 I've slightly modified your issue description, I hope it is ok.
Maybe the remaining two features are issues of its own.

**Comment by Bananeweizen** [comment]
added size parsing. additional types don't fit our model, therefore this cannot be represented any better than mapping to mystery.
