### ISSUE TITLE
add D/T rating to log signature

### ISSUE THREAD

**Issue by janykey** [cgeo/cgeo#6839]
**Feature Request**

As a geocacher I want to include the D/T rating of the current Cache in my log signature as template variable. Like this I am aware of D/T rating changes between the date I found the cache  (created an offline log) and the date I log the cache. This might be important when logging several caches for a challenge cache (having stored offline logs and the rating changed afterwards).

I want to be aware of D/T rating changes between the date I found the cache (created a offline log) and the date I log the cache. This might be important when logging several caches for a challenge cache (having stored offline logs and the rating changed afterwards).

**Acceptance Criteria**

1. when I click on "settings/logging/signature/insert template" I can choose "Difficulty" from the drop down.
2. when I click on "settings/logging/signature/insert template" I can choose "Terrain" from the drop down.
3. having selected "Difficulty" "[DIFFICULTY]" has been added to my signature.
4. having selected "Terrain" "[TERRAIN]" has been added to my signature.
 5. selecting "Log visit" on a Cache inserts my signature having e.g. "[DIFFICULTY]/[TERRAIN] replaced with the according rating (e.g. "D3/T4") for a D3/T4 cache.

**Comment by SammysHP** [comment]
`RATING` might be ambiguous (GC vote, favorite, other future rating systems). I suggest to split it into `DIFFICULTY` and `TERRAIN` which has the benefit of allowing complex sentences containing difficulty and terrain in different places.

**Comment by janykey** [comment]
Yes, that would be even more sophisticated. I'll adjust the user story ...

**Comment by janykey** [comment]
Hi, 
this is my first user story here. How do I track the progress?
What are the next steps?

Thanks,
Jan

**Comment by pstorch** [comment]
Hi Jan,

the next step is that some developer picks it (if he/she has time and is interested) and  starts coding. Developers from the core team can assign it themselves, outside contributors should comment here that they want to work on it.

**Comment by Matze2** [comment]
I am more interested in the purpose of this request.
Why should one duplicate the cache attributes in the log? You said you want to track the D/T rating at the time of the log.
And what happens if the owner changes the D/T rating later?

**Comment by janykey** [comment]
Then the original values can still be seen in the log. Regarding rating or matrix related chsllenges this seems interessting.

**Comment by Matze2** [comment]
This means there is a specific pattern like "{FTF}" that challenge checkers will respect?

**Comment by janykey** [comment]
It is more like x times the T5 column or thelike.

**Comment by janykey** [comment]
I want to be aware of D/T rating changes between the date I found the cache (created a offline log) and the date I log the cache. This might be important when logging several caches for a challenge cache (having stored offline logs and the rating changed afterwards).

**Comment by Matze2** [comment]
I thought that a challenge checker is mandatory nowadays and if there is no support in the challenge checkers I do not see the gain of this feature.
Disclaimer: I am not an expert in challenge caches but I thought the proof typically works in the following ways:

- new challenge caches must provide a challenge checker
- old challenge caches usually require a proof using project GC or Groundspeak statistics

I doubt that owners will accept a personal log entry where you added the D/T rating.
Therefore if neither challenger checkers nor the built-in statistics support this D/T pattern (simlair to {FTF} marker) I do not see how this should help you in fulfilling a challenge requirement.

**Comment by Matze2** [comment]
Apart from a objective discussion if this feature is useful or not, just allow me to express my personal opinion as someone who also reads log entries from time to time.

Call me an exotic but I still believe that the purpose of a log is to share the caching experience while you were searching the cache. Individual and **useful** logs **for other cachers** get more and more rare which is a bad development in my opinion. Features like this make the situation even worse.

Just imagine how unreadable an online log will get if everybody uses this feature and every entry contains D/T rating or other information just for the 0,1% case where these attributes are changed by the owner during the cache's life cycle.

But that's just my opinion. I am sure there are enough cachers that will like that feature.

**Comment by janykey** [comment]
Dear Matze2,

I agree with the impersonal log issue you mentioned. 
I do not share "the unreadable log" issue because this is not a question of tooling but a question of attitude of the particular cachers. Neither you  nor me are in the role of allowing or denying  them to add a rather long signature making the log unreadable.

**Comment by janykey** [comment]
Hi again,

I implemented this Feature by extending the `LogTemplateProvider` and added `Difficult` and `Terrain`. A first smoke test went well.

According to [https://github.com/cgeo/cgeo/wiki/How-to-get-a-bug-fix-into-the-release#procedure-for-contributors-or-for-using-pull-requests-and-code-reviews](https://github.com/cgeo/cgeo/wiki/How-to-get-a-bug-fix-into-the-release#procedure-for-contributors-or-for-using-pull-requests-and-code-reviews) I have to create a pull request now?

Thanks and kind regards,
Jan

**Comment by pstorch** [comment]
> I have to create a pull request now?

Yes, that would be good

**Comment by janykey** [comment]
Thank you 
shall I use the master or release branch?

Thanks,
Jan

**Comment by rsudev** [comment]
As it is a new feature, master is the right base.

**Comment by janykey** [comment]
"Yippee, build fixed!"
Guys, sorry again for breaking the build!
I fixed the float->String conversion I have forgotton while I was the lazy sofa-mobile-coder :/

I have now 3 commits but I do not know how to 'squash' them into one. That's the reason I added a new pull request. Which I'm again not sure if that was right or if I could have used the first one?
Unfortunately I forgot to mention the issue number in my last commit so that does not show up above.

Nevertheless, I updated the Story again to match the current implementation.
So, what will happen next? I'm still really excited about this to happen :D

Thanks a lot,
Jan

**Comment by UniQP** [comment]
A broken build for a pull request is not a problem at all.

You can use interactive rebasing to combine your commits: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Afterwards, you can use a `git push --force-with-lease` to update the remote branch, which will also update this pull request. You don't have to open a new pull request.

If you need help, feel free to ask (here, or on IRC).

**Comment by janykey** [comment]
OK cool :D 
In fact it is good that there is this great QA automation.

Right now I'm not sure if I have to squash the rhree commits or is it just nice to have?

What else has to be done?

Thanks,
Jan

**Comment by pstorch** [comment]
> Right now I'm not sure if I have to squash the rhree commits or is it just nice to have?

It's more a "should" than a "nice to have". One Issue == One Commit. It's better this way if we need to find the changes in the commit history belonging to one issue. And it also helps when merging, cherry-picking or reverting, if everything which belongs together is together.

**Comment by janykey** [comment]
OK I'll try that tomorrow :-)
