### ISSUE TITLE
Calculator does not save state on pause

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6843]
- Add or edit waypoint, open calculator
- dd mm.mmm format, add some variables
- type some numbers
- press home or switch to another app
- go back to c:geo
- calculator still visible, but all variable buttons are numbers again
- when you tap the buttons, they will turn into variables again and still have their assigned content that you typed previously.

Nightly from today.

**Comment by pstorch** [comment]
Sounds like a bug which sould be fixed for the release #6797

**Comment by Lineflyer** [comment]
I would say its optional to have it in the next release. So whenever the fix comes in, it should be based on `release` but not necessarily before next release.

**Comment by SammysHP** [comment]
It's enough to turn the screen off and an. IMHO this must be fixed before the release.

**Comment by pstorch** [comment]
I think this is a pitfall for the user and can be annoying. I look at it.

**Comment by pstorch** [comment]
Trickier than thought. It is somehow dependent on the save button of the dialog. If save button is clicked a `savedState` variable is set. As long as this variable is not yet set, the dialog gets resetted each time `onResume()` is called. Maybe @S-Bartfast has an idea how to handle it.

**Comment by S-Bartfast** [comment]
>Trickier than thought. It is somehow dependent on the save button of the dialog. If save button is clicked a savedState variable is set. As long as this variable is not yet set, the dialog gets resetted each time onResume() is called. Maybe @S-Bartfast has an idea how to handle it.

Yes, it's a subtle issue to do with the timing of when things are initialised.
Note, "saveState" is _also_ set when 'onCreate(...)' is called with a "Bundle" that contains state data.

It's probably not worth explaining the details here but it is to do with 'onCreate(...)' having a "Bundle" supplied but not being able to call 'loadCalcState()', and 'onResume()' being able to call 'loadCalcState()' but not having the "Bundle".

The current implementation was tested using screen rotation (which works fine) but not tested with restoring from the background (which does not call 'onCreate(...)').  An additional check to the 'onResume()' method to handle the case when the dialog is 'restored' without being 're-created' is required, which I've now added 👍
