### ISSUE TITLE
Confirmation before discard waypoint changes

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6844]
It's annoying when you have entered a lot of data for a waypoint and accidentally press back. Currently everything is lost. c:geo should show a confirmation instead.

**Comment by pstorch** [comment]
What about an "undo" action (or better "restore") instead of a confirmation dialog?

**Comment by SammysHP** [comment]
Undo/restore operate on the same activity level. Dismissing the waypoint dialog returns to the list. When you undo in that situation it would start the dialog again which changes the level.

**Comment by pstorch** [comment]
Thanks for the explanation. Never thought about it. But it makes sense.
