### ISSUE TITLE
Duplicate waypoint does not duplicate calculation

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6845]
Create a waypoint with calculation. When you long-press on it and select "duplicate waypoint" then it duplicates the waypoint with the calculated coordinates, but not the calculation itself. So when you edit the copy and open the calculator, it will start without variables.

**Comment by pstorch** [comment]
Sounds like a bug which sould be fixed for the release #6797

**Comment by pstorch** [comment]
I have a look here

**Comment by Lineflyer** [comment]
IMHO this is no must have usecase, thus the fix should be on `master`.

**Comment by pstorch** [comment]
Yes, it's not one of the main usecases. On the other hand the fix for it is trivial.
