### ISSUE TITLE
Button Colours

### ISSUE THREAD

**Issue by S-Bartfast** [cgeo/cgeo#6849]
I've never been all that clear on what colours should be used in the user interface so have just hacked about till I've found something that seems to work, but I would like to know how I should be working with colours.

In particular I'm concerned about the colours used for the calculator buttons.
By default I've been setting the backgorund colour with:
>`butt.setBackgroundResource(R.drawable.button_background_kitkat);`

This has never seemed particularly good as 'Kitkat' was just an arbitrary guess but does seem to work.

However when I clear the buttons I set the background (for 'Custom' or 'Blank' buttons) like this:
>`butt.setBackgroundColor(ContextCompat.getColor(getContext(), R.color.button_default));`

While this works, one is set using `setBackgroundColor(...)`, where as the other is set using `setBackgroundResource(...)`.  This does have the benefit of including a 'border' around the button when `setBackgroundResource(...)` is used and not including the border when set using `setBackgroundColor(...)`, but it doesn't seem like this would be the 'correct' way to do things.

Also of concern, I can't workout what colour the background should be when in light mode so while visible the blank buttons do look wrong when the light theme is used:
![image](https://user-images.githubusercontent.com/6573522/33015442-ab1130c6-ce3a-11e7-8f1e-6eff0276c786.png)

If someone could clear me up on the way this should be done I'll be keen to know.

Thanks.

**Comment by Lineflyer** [comment]
My few cents:
I would not take too much effort to optimize the white theme. According to my experience on support is rarely used by our users.

**Comment by S-Bartfast** [comment]
>I would not take to much effort to optimize the white theme.

Yeah, my interest is not so much in supporting the light theme as such but more in adopting 'best practice'.
I've never felt that I was dealing with colours correctly and the light-theme example above is used to illustrate this.

So does anyone know how I _should_ get hold of the background colour, or is accessing it through `"butt.setBackgroundResource(R.drawable.button_background_kitkat);"` the way it's meant to be done?  It doesn't really pass the 'sniff test'.

**Comment by Lineflyer** [comment]
@moving-bits Outdated,  isnt it?

**Comment by moving-bits** [comment]
yes, IMHO. We've updated nearly all buttons to material theme (where possible).
