### ISSUE TITLE
Add support to copy waypoint (user) notes

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6851]
While using the waypoint calculator I wondered how I can share the variables gathered from stage to stage among the waypoints for easy transfer in the calculator formulas.

My idea was to create a virtual waypoint called "Variables" to collect all stage variables in its user notes.
From there I wanted to copy them into the stages' user notes. The user notes are also visible in the calculator so they can be copied in the variable values of the waypoint calculator.
In the following screenshot you can see virtual waypoint "Variables" from where the variables were copied into the waypoints "Stage 2" and "Stage 4".

![screenshot_2017-11-24-00-04-16](https://user-images.githubusercontent.com/12542802/33190352-1a994d8e-d0ac-11e7-9e62-cf3a08d35d53.png)

Unfortunately there is no way to copy the user notes from a waypoint. :open_mouth:

I did a rough implementation that creates a new waypoint action "Copy Notes". This action strips HTML from the waypoint note, merges with user note and copies both into clipboard.

Before I continue on the code I just wanted to ask in advance if there is interest and a chance to get this feature included.

**Comment by Matze2** [comment]
Ready for review whenever you are in the mood for it.

**Comment by pstorch** [comment]
This is similar to #6691 or at least related. I also think it would be nice to share/copy the variables between waypoints. I'm not sure if the "virtual" waypoint is the way to go. How do you sync them between the waypoints? Need to think about it. For testing and feedback a PR might be good. Even if it is a draft only. We can add a `do not merge` tag.

But before deep diving into this I would like to focus on the current release.

**Comment by Matze2** [comment]
@pstorch Thanks for having a look on it.

First of all the commit above just adds a generic feature to copy waypoint notes to clipboard. Currently, waypoint user notes are not copyable.

The motivation of course is to have at least one temporary way to share variables among calculator waypoints. An alternative would be to store this information in the "personal note" (this is copyable) but this requires switching forth and back between the waypoint page and the description page.

But I would not take a decision with #6691 in mind. It should be only based on the feature "make waypoint notes copyable" itself. If this is considered as bloating the waypoint menu then you (you as the c:geo core team) can just reject this issue. This is also fine.

I will add another screenshot to show the current state and create PR just to finalize the work here. But of course there are more important items to work on.

**Comment by pstorch** [comment]
> Currently, waypoint user notes are not copyable.

They are: long click on the text, select all, copy. Or do I miss something?

**Comment by Matze2** [comment]
Server notes that are in the read-only area: can be copied.
User notes that are in editable text area: cannot be copied.
At least not with my mobile.

Outside in the waypoint overview. The text can be only rot13'ed.

**Comment by pstorch** [comment]
Outside in the list of waypoints not, you are right.

**Comment by Matze2** [comment]
Finally it is only about the waypoint user notes which I would use to transfer the list of variables from one waypoint to the other. Currently this is not possible at all since the user notes cannot be copied.

**Comment by Lineflyer** [comment]
The waypoint notes (both server and user) can be copied while in waypoint edit mode.
Or am I wrong?

If you would like to implement the function in the waypoint context menu (long click on waypoint in waypoint tab), this is a nice addon. Is it that, what this change is about?

BTW:
The way of how to implement availability of variables across waypoint borders is another topic, which we should brainstorm in #6691 first....but anyhow this copy function might be helpful in any case.

**Comment by Matze2** [comment]
I cannot copy the waypoint user notes in the editor area. Short or long press - it just positions the cursor.
If this possible somehow of course the whole issue and the pull request can be closed immediately.

**Comment by Matze2** [comment]
Ok. Did some research. It is a speciality of  Sony Xperia Devices.
Instead of long press you need a double tap. Long press produces a magnifier.
Then there is no need to bloat the app with this. I'll close both.
I am sorry for wasting your time.
