### ISSUE TITLE
Provide a way to delete coordinates from waypoints

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6857]
This was already discussed at the end of #6697.

There are various ways you can get unwanted coordinates in a waypoint:
- you just want to add a note there
- you prepare waypoint calculator formulas in advance

In all these cases arbitrary coordinates (usually your current position) are stored into the waypoint and there is no way to get them removed again.

This has different disadvantages:
- you cannot distinguish between a waypoint with correct or incorrect coordinates
- it pollutes the waypoint map with wrongly placed waypoints

This is of course more problematic for caches with lots of stages: you get a wild mixture of valid and arbitrary coordinates. 

Therefore it would be nice to have an action to remove waypoint coordinates from a waypoint.

The implementation for this is trivial. It acts in the same way as the "Delete" action in the waypoint context menu. This means, there is no confirm dialog and there is no different behavior for user created waypoints or listing waypoints. The latter can be restored by a cache refresh again.

I will share my changes tonight.

**Comment by pstorch** [comment]
Good Idea, but I would distinguish between user and cache-owner created waypoints.

**Comment by Matze2** [comment]
Not sure what you mean. Let's take again GC768Y3.

All waypoints are cache-owner created and all but one do not have coordinates.
As soon as I touch the waypoint somehow (typically by a note change or nowadays by preparing the calculator) I get unwanted coordinates stored in the waypoint and cannot remove them.

In which respect they shall be distinguished?

Another point is that the behavior should be synchronized with the "Delete Waypoint" action.
Currently this action does not care about the origin of a waypoint.

And while really touching both actions I would also add a confirm dialog.

**Comment by pstorch** [comment]
Sorry, I was not clear enough. I just want to "protect" the server side defined coords. Server side waypoints which don't have coordinates should be possible to clear, of course.

**Comment by Matze2** [comment]
To rephrase that: if a coordinate is provided by the server it should not be possible to delete it. Hope I got it now.

I see a few problems with this requirement:
- Currently it is always possible to change any waypoint coordinates. Why do we need a restriction on delete? In both cases the original coordinate is somehow "destroyed"-
- As far as I remember there is no storage for the listing-provided waypoint coordinates. This means, a db schema extension would be needed.

**Comment by pstorch** [comment]
> Why do we need a restriction on delete?

Basically because we don't allow edit. But maybe it is not an issue as you said, because we can restore with a refresh.

**Comment by Matze2** [comment]
Aah, you're right. I was not aware of this. Then it should be doable.

**Comment by Lineflyer** [comment]
I also like the idea!

**Comment by SammysHP** [comment]
Editing the description should not add coordinates. Another bug?

**Comment by pstorch** [comment]
> Editing the description should not add coordinates. Another bug?

Yes, I think it's worth it's own issue.
