### ISSUE TITLE
Remove prefilled prefix in search by geocode if clipboard is used

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6858]
##### Detailed steps causing the problem:
From support mail:
- Have a geocode stored in your device clipboard (e.g. copied from another cache detail page)
- Open search menu
- Paste the clipboard content into the geocode search field

##### Actual behavior after performing these steps:
Geocode from clipboard is inserted after existing prefix "GC" resulting in e.g. `GCGC1234` instead of only the clipboard content

##### Expected behavior after performing these steps:
Paste operation should only paste the clipboard content and remove any default content of this field

##### Version of c:geo used:
2017.10.23

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
When I paste a geocode into this field I long press on the "GC" prefix, then Android selects this text and shows the "CUT COPY PASTE ..." popup. When I then press on PASTE the "GC" prefix gets fully replaced by the clipboard content.

**Comment by alan666notb** [comment]
How about simply checking if the search string starts 'GCGC' and correcting it?

**Comment by pstorch** [comment]
Because this prefix might be valid: http://coord.info/GCGCF8

**Comment by rsudev** [comment]
Or the pasted code might result in GCOC1234 or similar.

**Comment by pstorch** [comment]
`GCOC...` could be detected, because `O` is an invalid letter for GC-codes.

**Comment by Lineflyer** [comment]
I do not think that we should but much effort into any detection/correction algorithm or similar. I mainly opened this issue to let you evaluate if there might be an easy workaround/solution, e.g. Is it technically possible to already select the prefilled GC when the user activates the field? Or by default delete the prefilled content if a paste operation is performed (as it is unlikely, that the clipboard content has GC ommited.

**Comment by moving-bits** [comment]
When using "Search - geocode" from mainsreen and using paste, we could check if any connector accepts the string from the clipboard as valid geocode end replace the contents of the input field in that case instead of appending the string.
