### ISSUE TITLE
Sudden duplication of waypoints when using calculator

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6859]
@Matze2 (https://github.com/cgeo/cgeo/issues/6797#issuecomment-347841259) and I experienced a sudden duplication of waypoints while using the calculator.

No sure yet when it happens exactly.

**Comment by Matze2** [comment]
This was a misunderstanding of my comment. What I wanted to mention is that I no got waypoint coordinates because I touched all waypoints. This relates to issue 6857.
I never faced any waypoint duplication related to calculator.

**Comment by Lineflyer** [comment]
:)

**Comment by pstorch** [comment]
Sorry for the misunderstanding. When the glitch I experienced comes up for me again and I can reproduce, then I'll open it again.
