### ISSUE TITLE
Support of NULL coordinates in EditWaypointActivity and don't prefill with user location

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6861]
To be able to handle invalid coordinates (for #6697) and to prevent the misbehavior found in #6857 (e.g. opening a WP without coords, only updating notes and saving it), I would like to change the EditWaypointActivity to properly support NULL (a.k.a. empty) coordinates in this dialog.

At the moment, as soon as you open this dialog and the WP doesn't have any coords (the field is NULL) the coords are filled with the current location of the device.

I guess this was done for convenience when adding a new stage for a multi cache for example. But in all other cases (e.g. calculating the next stage with the calculator or just editing a user note for a waypoint without coordinates) it is confusing that the coords are set to the users location without intention. 

I propose to set the lat/lon buttons to a text like `NOT SET`, `---` or `N 00° 00.000` to clearly indicate that there are no coordinates set. Only fill the coords by explicitly using the Coordinate Input Dialog, the Calculator or the Clipboard.

**Comment by SammysHP** [comment]
Although highly unlikely, `N 00° 00.000` is a valid format. `N --° --.---` or `N __° __.___` sounds good IMHO.

**Comment by pstorch** [comment]
Yes. Maybe we should avoid all `N ...` variants. Because a fixed hemisphere could be confusing or we would have to dynamically set the hemisphere according to the users location. Which might be unnecessary complexity.

**Comment by Matze2** [comment]
In my opinion this is a big step forward. 👍 

What is still missing in my opinion (which could be also part of other issues):

1. Obvious invalid variable values should make the calculator result invalid too.
Example: E 11° 28.(A-1)(A)0 with A > 9 (leads to 4 digits) or A < 1 (leads to negative digits)

2. If calculator result is invalid exiting the calculator is not intuitive since you need to click the "disc" for saving and then exit it with the "cross". The right button (disc or check) should always save and exit the calculator. Then the "cross" will be a pure cancel button.
If this is not clear I can give more details with some UI screenshots.

**Comment by pstorch** [comment]
Thanks for your feedback.

Regarding 1. and 2. there is another issue #6855 on how the calculator should handle invalid input/results.

Regarding 3. yes, that I've missed, too. Maybe in the CoordsInputDialog or an indicator in the Waypoint itself that it is based on a calculation.

**Comment by Matze2** [comment]
Which brings us back to my opinion that a waypoint is either in "direct input" or in "calculator" mode.
But that's a different story. 😃

**Comment by pstorch** [comment]
Exactly, I would also add Projection as an own WaypointInput type.

**Comment by Lineflyer** [comment]
I used the calculator and also this new function quite a lot last days and it is IMHO working very smooth and logical. Thanks @pstorch!

The only small glitch (for my personal logic) is, that the new waypoint comes up with undefined coords, but when I go into coord edit mode it is still prefilled. Shouldn't is be displayed as NULL as well until the user enters own coords or uses one of the filling functions?

**Comment by pstorch** [comment]
Do you mean that the CoordinateInputDialog should also not prefill the coords with the users location?
So if someone wants to have it  he needs to click on "My coordinates" explicitly?

**Comment by Lineflyer** [comment]
Exactly, because: If I create waypoint to fill the calculator before going out for caching, the WP will stay with NULL coords..in fact this it working, but the dialog does not reflect it.

**Comment by pstorch** [comment]
The ideal solution would be to get rid of this dialog in case we want to calculate the coordinates. But the rework of the dialogs is a bigger thing. In the mean time we could also empty it if there are no coordinates yet. In all situations or only if called from the Edit Waypoint dialog?
That would also mean another click more in case you just want to record your current position in a waypoint.
