### ISSUE TITLE
Markdown/HTML numbering in log not supported

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6863]
From support mail:
It appears that Markdown numbered lists aren't supported. As an example, my log on https://coord.info/GC75BKC (I'm B2Pi, the log is https://coord.info/GLQYTWP1), the list shows as numbers online, but as bullet points within CGeo

My comment:
Although the logs are formatted in markdown by the users, we retrieve the converted HTML from the website (AFAIK). However in my browser the mentioned log shows up numbered, therefore I am wondering why it does not in c:geo.

**Comment by pstorch** [comment]
Interesting: this is a bug (a.k.a new feature from Android N): 
https://stackoverflow.com/questions/38935756/html-tag-handler-not-called-in-android-n-for-ul-li

I just tested in an emulator with an older Android version and there we get the numbered list.

**Comment by pstorch** [comment]
There is also an issue on the google android bugtracker: https://issuetracker.google.com/issues/37108224

**Comment by Lineflyer** [comment]
So, this looks like closing with "Wont Fix" (ourselves)?!

**Comment by Lineflyer** [comment]
Informed the user on support mail accordingly.
