### ISSUE TITLE
Check server hard disk

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6864]
Since mid-october our jenkins master server is quite slow, especially when building a new release version.

I've found system (the VM) to be low in physical memory, it has 2G of ram and our builds need about 4G of memory. System is constantly swapping.

While looking at the kern.log I saw bunch of "alarming" logs.
```
Dec  5 22:19:12 cgeoci kernel: [3801683.457687] JBD2: Detected IO errors while flushing file data on sda1-8
Dec  5 22:22:17 cgeoci kernel: [3801868.808722] JBD2: Detected IO errors while flushing file data on sda1-8
Dec  5 22:25:21 cgeoci kernel: [3802053.305830] JBD2: Detected IO errors while flushing file data on sda1-8
Dec  5 22:28:35 cgeoci kernel: [3802247.056204] JBD2: Detected IO errors while flushing file data on sda1-8
Dec  5 22:40:08 cgeoci kernel: [3802939.405791] JBD2: Detected IO errors while flushing file data on sda1-8
Dec  5 22:40:08 cgeoci kernel: [3802939.764880] JBD2: Detected IO errors while flushing file data on sda1-8
```

@mucek4
* Could you affect more ram the the VM if possible
* Could you check physical disk for smart errors and/or any other disk analyzer?
Thanks

**Comment by mucek4** [comment]
Ok. More ram shall not be a problem, I just need to reboot system. 
Writing problems are interesting. It's a virtual machine. I don't see problems on host, so this error is "interesting". I'll take a look.

**Comment by mucek4** [comment]
Ok. More memory added. 5GB currently. I'll check what I can do about HDD.

**Comment by Lineflyer** [comment]
@mucek4 Any update / can we close this?

**Comment by Lineflyer** [comment]
@mucek4 As you worked on the servers. Can we close this?

**Comment by mucek4** [comment]
We probably can. Machine is a virtual machine and I can't see why a disk would be problematic.
