### ISSUE TITLE
Waypoints of caches not parsed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6865]
##### Detailed steps causing the problem:
- Open e.g. GC6Y8T8
- Open the waypoint tab

##### Actual behavior after performing these steps:
Waypoints of the cache not shown

##### Expected behavior after performing these steps:
Waypoints shown

##### Version of c:geo used:
All

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Seems to be related to a recent website change

**Comment by Lineflyer** [comment]
Raised notification to users

**Comment by Matze2** [comment]
I just tried both fix commits.
Waypoints are now detected again in opposite to the latest nightly.
Disabled and archived caches show this status while the nightly showed them as active.
