### ISSUE TITLE
Present Disable/Archived Log at top of Geocache listing

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6868]
With this change #6866 GS presents the disabled and archived logs at the top of the geocache page.
![image](https://user-images.githubusercontent.com/5598124/33683636-d7361b56-dacb-11e7-8b20-a3c8971101c1.png)

It's a very useful information for users to see right away what's wrong with the cache.

Suggestion is that we also add this to the top of the geocache details activity. What do you think?

**Comment by SammysHP** [comment]
Can you give us a quick preview of how it might look like? I think linking the status in the overview to the latest status log is enough and doesn't clutter the UI.

**Comment by pstorch** [comment]
A preview design would be good to discuss it. I have to think about it.

**Comment by Lineflyer** [comment]
I think we present it rather good with strike through (disabled) and red (archived) cache title.

**Comment by pstorch** [comment]
The idea behind it is to have the logtext which describes the reason for disabling or archiving on top. 
So the users see it right away without scrolling through the logs to find it. 

If there is some important reason why the geocache is disabled and shouldn't be searched, e.g. cache is not available in wintertime,  construction at the final, dangerous forrest operations, a hunt takes place in the forrest, endangered animals living nearby or a dispute with the landowner. 
Normal disable status gets ignored sometimes.

**Comment by pstorch** [comment]
Just a quick sketch with an image editor:
![image](https://user-images.githubusercontent.com/5598124/33705524-ee8c7f56-db30-11e7-9dbe-a9443875f1f8.png)

**Comment by pstorch** [comment]
This didn't work out as I thought. Let's close.
