### ISSUE TITLE
Calculator state lost if device rotation is involved

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6869]
##### Detailed steps causing the problem:
- Create new waypoint
- Open calculator
- Assign some variables and enter values to have valid coords
- Leave calculator by clicking "Tick" icon
- After returning to waypoint screen rotate device (e.g. portrait to landscape)
- Open waypoint calculator again by clicking on coordinates and selecting "Calculate Coordinates"

##### Actual behavior after performing these steps:
Variables and values are lost

##### Expected behavior after performing these steps:
Variables and values should be saved

##### Version of c:geo used:
2017.12.06

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by invokergakki** [comment]
can you give me some pictures to demonstration this bug?I don't know which icon is "Tick"。Thanks

**Comment by Lineflyer** [comment]
"Tick" means the OK icon on top right of the calc window. Please be aware, that this bug is already solved on ˋmasterˋ.

**Comment by invokergakki** [comment]
oh,thank u.
