### ISSUE TITLE
"Load more caches" does not always destroy the initial loader

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6870]
Same as #5498 but for other actions like "Caches around".

This somehow slipped through because I thought that "Nearby" action is the same as "Caches around". Only the way how the start coordinates are determined is different.

But in fact, there are two different loader types:
- CacheListType.NEAREST (fixed in #5498)
- CacheListType.COORDINATE (still truncates list to 40)

Fix should be trivial. I will handle it.

**Comment by Matze2** [comment]
There is even a third type ADDRESS that uses the same loader (CacheListActivitiy around line 1900):
```
            case NEAREST:
                title = res.getString(R.string.caches_nearby);
                loader = new CoordsGeocacheListLoader(this, coords);
                break;
            case COORDINATE:
                title = coords.toString();
                loader = new CoordsGeocacheListLoader(this, coords);
                break;
            case ADDRESS:
                final String address = extras.getString(Intents.EXTRA_ADDRESS);
                if (StringUtils.isNotBlank(address)) {
                    title = listNameMemento.rememberTerm(address);
                } else {
                    title = coords.toString();
                }
                loader = new CoordsGeocacheListLoader(this, coords);
                break;
```
I assume they all have to be handled in the same way.

**Comment by Lineflyer** [comment]
@pstorch Enlighten me: How did you manage to assign the issue to a non project-member. I did not know, that this is possible. Very helpful instead of "Assigned non-colab" attribute.

**Comment by pstorch** [comment]
@Lineflyer I was supprised, too, that this was possible :wink:

**Comment by Matze2** [comment]
Me too, but it's ok 👌

**Comment by Matze2** [comment]
I am preparing an overview over (almost) all CacheListActivity types: how to call them, if they are affected by this issue and so on.
There is this special history list. I never used it. How do I get entries into that list? I need to fill it with 40+ entries.

**Comment by pstorch** [comment]
The history list contains found caches and caches with offline logs.

**Comment by Matze2** [comment]
Thanks. Just found it out myself.

**Comment by Matze2** [comment]
Here is the list of all cache list activities. The ones with "Yes" in the "Duplicate Loaders..." column are affected of the issue described in #5498.

| CacheListType | Path to Action | Load more caches footer | Duplicate Loaders with list truncation | Remarks
| --- | --- | --- | --- | --- |
| OFFLINE | Start Screen / Stored | No | No | |
| POCKET | ? | ? | ? | PM required |
| HISTORY | Start Screen / History | No | No | |
| NEAREST | Start Screen / Nearby | Yes | No | Already fixed in #5498 |
| COORDINATE | Search / Search by coordinates | Yes | Yes | Will be fixed |
| | Cache / Caches around | Yes | Yes | Will be fixed |
| KEYWORD | Search / Search by keyword | Yes | Yes | Will be fixed |
| ADDRESS | Search / Search by address | Yes | Yes | Will be fixed |
| FINDER | Cache / Click on user name / Caches found | Yes | Yes | Will be fixed |
|  | Search / Search by user name | Yes | Yes | Will be fixed |
| OWNER | Cache / Click on user name / Caches hidden | Yes | Yes | Will be fixed |
|  | Search / Search by owner name | Yes | Yes | Will be fixed |
| MAP | Live Map / Show as list | No | No |  |

**Comment by pstorch** [comment]
I tested the PQ List, it has the same problem.

**Comment by Matze2** [comment]
Ok. The defensive variant of the fix looks like this:
```
    private class MoreCachesListener implements View.OnClickListener {

        @Override
        public void onClick(final View arg0) {
            showProgress(true);
            showFooterLoadingCaches();

            getSupportLoaderManager().restartLoader(CacheListLoaderType.NEXT_PAGE.getLoaderId(), null, CacheListActivity.this);
            switch (type) {
                case NEAREST:
                case COORDINATE:
                case KEYWORD:
                case ADDRESS:
                case OWNER:
                case POCKET:
                case FINDER:
                    getSupportLoaderManager().destroyLoader(type.getLoaderId());
                    break;
                case OFFLINE:
                case HISTORY:
                case MAP:
                    break;
                default:
                    break;
            }
        }
    }
```
On the other hand it is clear that there is no MoreCacheListener in the remaining three cases:
- For MAP and HISTORY we immediately have all items in the cachelist from the beginning
- For OFFLINE the MoreCacheListener is explcitly excluded

This means that this method is only entered in the above cases and therefore we could call destroyLoader unconditionally. So the method would become
```
    private class MoreCachesListener implements View.OnClickListener {

        @Override
        public void onClick(final View arg0) {
            showProgress(true);
            showFooterLoadingCaches();

            getSupportLoaderManager().restartLoader(CacheListLoaderType.NEXT_PAGE.getLoaderId(), null, CacheListActivity.this);
            // the loader for subsequent pages takes over - therefore the initial loader needs to be destroyed
            getSupportLoaderManager().destroyLoader(type.getLoaderId());
        }
    }
```
I would prefer that solution.

**Comment by Matze2** [comment]
Create a PW with both commits in.
