### ISSUE TITLE
Possible problem areas after website change

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6871]
For your attention:

In the [Geocaching Forum](https://forums.geocaching.com/GC/index.php?/topic/346756-release-notes-website-edit-cache-listing-page-december-5-2017/) I found the release note regarding the latest site changes as of December, 6th 2017.

It is mostly dealing with the cache edit page (which does not affect c:geo) but also contains a section about other updates, which I list below with my assumptions:

| Change  | In c:geo |
| ------------- | ------------- |
| D1 is enforced for all Event Caches. Event Caches must have a 1-star difficulty rating because it is easy for geocachers to “find” events.   | Should not affect c:geo as they will be shown as D1  |
| Event Caches no longer include a container size. | This means probably, that the container information might be ommited on the website. We should check new events. |
| [...] In addition, the links “Watch” and “Add to List” are available only after publication, because we found that they were not used by COs prior to publication. | This is a rare case, but an owner of an unpublished cahe can load it in c:geo and possibly the watch option will be shown to him but not usable 
| Previously, there were two text fields to describe your cache. During the Cache Submission Process, those were the cache summary and long description. On the Edit Cache Listing page, they were the short description and long description. Going forward, there’s just one field. However, the short description field still exists for any caches that currently have a short description. If a cache owner removes an existing short description from their cache, the field will disappear. | We should doublecheck a new listing which only has one description field to check if there are problems |
| The Related Web Page field now only exists on caches that currently use that field. If a cache owner removes an existing Related Web Page, then the field will disappear. | I don't know how this was handled in the past. If a cache does not use the related web page, was this field ommited on the page in the past? |

**Comment by pstorch** [comment]
Looks like the cache size of events is all "not chosen" and c:geo doesn't show the sizes in that case.

For own caches c:geo doesn't show the watchlist button. Just a text, that this cache is already on your watchlist.

There are already caches without short description. At the moment I don't see a possible problem.

**Comment by Technical-13** [comment]
Doesn't c:geo default to [**Other (--)**](https://www.geocaching.com/help/index.php?pg=kb.chapter&id=97&pgid=815) if no size is specified?

I always load my caches before they're published.  I don't personally watch them (because I put them on a c:geo list instead), but I could see other hiders using the feature.  Maybe a fallback notification that says `Watching a page is not available through c:geo until the cache has been published.  Sorry for any inconvenience.`?

**Comment by Matze2** [comment]
Since today "nearby" and "caches around" search does not work anymore. Gives an empty list.
Same for others?

**Comment by Matze2** [comment]
Never mind. You guys are so fast. Seems to fixed with the current nightly.

**Comment by kumy** [comment]
@Matze2 The new version was just published on Google Play Store for 25% of users.

**Comment by pstorch** [comment]
This path change from `/images/wpttypes/...` to `/images/WptTypes/...` also affects trackables. But as far as I can see there is no problem with that.

**Comment by Lineflyer** [comment]
No further impacts to c:geo recognized. Lets close this.
