### ISSUE TITLE
GC search doesn't work anymore

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6884]
Parsing of the GC search result page doesn't work anymore.

First thing I found is that the parsing of `if (!row.contains("images/wpttypes")) {` because it is mixed case now. Checking for `if (!row.contains("images/WptTypes")) {` gives a search result, but all cache types are wrong (unknown).

**Comment by pstorch** [comment]
Ah, the `PATTERN_SEARCH_TYPE` in the GCConstants class needs to be corrected as well.

**Comment by Lineflyer** [comment]
Feel free to push into nightly if you think its ok. I am on Vacation and will for sure use the search.

**Comment by Lineflyer** [comment]
I mean merge to master :)

**Comment by pstorch** [comment]
I merged through release, just in case.
