### ISSUE TITLE
Waypoint type not parsed correct

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6886]
##### Detailed steps causing the problem:
- GC19EE6 should have a parking waypoint
- It was correctly stored some weeks ago on my device
- After updating it today the waypoint type changed to reference point 

Looking at other freshly loaded caches nearly all waypoints seem to be parsed as reference point.

##### Version of c:geo used:
2017.12.16-NB1 (incl. latest site change fixes)

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
Confirmed. There is another place where this pattern changed.
