### ISSUE TITLE
Picture upload ends with error message although ok

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6888]
Quick note from field:
Postinf found log with attached picture (no scaling) ends with error message in c:geo.
Checking the website log and photo have been posted sucessfully.

2017.12.18-NB

**Comment by pstorch** [comment]
I just successfully uploaded a log picture with a write note log. Maybe a temporary bad connection where the upload response wasn't retrieved correctly?

**Comment by alan666notb** [comment]
I've had this happen twice now.
Picture upload ends with a failure, I retried it without checking if it had been successful and it resulted in two logs and two pictures being uploaded.
The second log is turned into a DNF (But that's a result of #6694)

**Comment by pstorch** [comment]
But the error message says you should check it online, if your log was posted or not, right?

Anyway, is it time to move on to the new logging page?

**Comment by alan666notb** [comment]
From memory, It said something like 'posting of your image failed',
Then there were the three options - retry/cancel/save-offline.

As it was talking about the image, I wasn't expecting another log to be posted - just another attempt at uploading the image.

**Comment by pstorch** [comment]
This should be improved/clarified I think.

**Comment by Lineflyer** [comment]
Today I uploaded two other log pictures (one scaled, one unscaled) and it worked without a problem.
However the log photo, where I initially had this problem was from another source (digital camera instead of smartphone camera). It was much huger (approx. 20MB).  
I will check next time how the website reacts on such file sizes...maybe there is another response in this case.

**Comment by Lineflyer** [comment]
Could not get a clear reproduction of the issue. It might be, that bad network connection is involved here. However there does not seem to be a systematic problem behind.
