### ISSUE TITLE
NPE in CoordinatesInputDialog (buttonClear is null)

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6890]
Easy to reproduce:
- Create a new waypoint
- Open coordinates input dialog
- Rotate the device from portrait to landscape

On line 202, in master branch
`
final Button buttonClear = ButterKnife.findById(v, R.id.clear);
`

buttonClear is null on rotation redraw.

**Comment by Matze2** [comment]
If device is in landscape then the exception is immediately raised when opening the coordinate input dialog.

**Comment by Matze2** [comment]
In landscape mode the buttons are arranged horizontally which leaves space only for three buttons.
At least with my device.

**Comment by pstorch** [comment]
Oh no, CoordinateInputDialog has its own layout file for landscape mode. I missed that 🤦‍♂️

**Comment by Matze2** [comment]
Ah, this is the reason. I wondered what the code problem is.
Apart from that do we really need a separate layout?
Arranging up to 5 buttons horizontally is not real improvement. Maybe with three it was.

**Comment by pstorch** [comment]
Idk. I don't use c:geo in landscape mode. Maybe someone with a tablet can give some input.

**Comment by SammysHP** [comment]
Tablet should even be another layout. ;)
