### ISSUE TITLE
error login geocaching.com from android app

### ISSUE THREAD

**Issue by BodoBiker** [cgeo/cgeo#6896]
##### Detailed steps causing the problem:
- starting Android app standard login to geocaching.com causes an error --> offline modus
- checking authentification causes an error "unknown communikation failure"
- no changes of my password or user since it works fine (for the years)
- web login to geocaching.com works fine with the account data

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
Did you check out our FAQ already and tried the suggested fixes: http://faq.cgeo.org/#login-failed

**Comment by BodoBiker** [comment]
I checked everthing despite of deleting the account, restart phone and set the account data new. I did this now and the app logged in. It works now. But I do not understand this behavior.
Thank you for your quick answer!
