### ISSUE TITLE
Zeros inserted in coord editor when changing format

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6898]
##### Detailed steps causing the problem:
- Create new WP
- Open the coordinate editor
- It will come up empty (NULL)
- Change randomly between the possible formats

##### Actual behavior after performing these steps:
At some point some fields will be filled with zeros instead staying empty

##### Expected behavior after performing these steps:
All field should remain empty (NULL)

##### Version of c:geo used:
2017.12.31-NB

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
I cant see any functional impact, so it seems only to be a small UI glitch

**Comment by pstorch** [comment]
I saw that, too. There is a `PadZerosOnFocusLostListener` on the input fields and somehow when changing the format this is triggered on some of the fields and it fills it with 0s.

I didn't want to remove it, because I guess in other situations it is a wanted behavior, right?

**Comment by Lineflyer** [comment]
Thats right and diffcult.... Did not look into your PR yet....but if the user ommitts the decimal digits we should probably pad them with zeros.
I am also fine with not changing anything...it was only a glitch.
