### ISSUE TITLE
Build failures: build-tools license and archiving artifacts

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6899]
Happens `cgeo-nightly` build on `master` executor:
```
12:56:33  * What went wrong:
12:56:33  A problem occurred configuring project ':cgeo-contacts'.
12:56:33  > You have not accepted the license agreements of the following SDK components:
12:56:33    [Android SDK Build-Tools 26.0.2].
```

Happens with `cgeo continuous integration` build on `cgeo-1` executor:
```
12:54:26  Archiving artifacts
12:54:26  ERROR: No artifacts found that match the file pattern "*/build/outputs/apk/cgeo*debug*.apk". Configuration error?
12:54:26  ERROR: ?*/build/outputs/apk/cgeo*debug*.apk? doesn?t match anything: ?*? exists but not ?*/build/outputs/apk/cgeo*debug*.apk?
12:54:27  Build step 'Archive the artifacts' changed build result to FAILURE
```

Related to #6814, but the build for this PR was working, right?

**Comment by pstorch** [comment]
Ok, `cgeo continuous integration` build is fixed. I've applied the same artifacts filter as @Bananeweizen configured for the `cgeo pull request` build.

**Comment by Bananeweizen** [comment]
I guess you added the necessary hash in the shared script, right? And the artifacts thing is because I forgot that my PR caused the naming of the output files to be different after the android-gradle 3.0 update. Sorry for that.
To me it looks like you fixed all issues.

**Comment by pstorch** [comment]
No, the right hash for the license is still missing. Cgeo nightly job still failing. Do you mean the Jenkins job config with the "shared script"? At least there I saw something like it. I haven't looked up the right hash yet.

**Comment by pstorch** [comment]
I've added the new license hash in the jenkins script. It's building now with build tools 26.0.2. Let's see.

**Comment by pstorch** [comment]
Ok, had to fix the artifacts path in the cgeo-nightly, too. Building again ...

**Comment by pstorch** [comment]
Good, cgeo-nightly build is green again :tada:

**Comment by Lineflyer** [comment]
Thanks @pstorch, well its building, but did you test the result.

Updating from last nightly it says:
![screenshot_20180101-215210](https://user-images.githubusercontent.com/949669/34471048-69457312-ef3e-11e7-9052-1bfd89e856ae.png)

**Comment by Lineflyer** [comment]
No idea why:
The ADB log does not tell anything (in my log app), the build console does not look unusual.
Also the size is similar to the APK files from end of last year.

**Comment by pstorch** [comment]
I could install it (but I manually uninstalled my local build version before).
I'm not sure if I triggered the nightly build correctly. I just executed it with the `NB` parameter as default.

**Comment by pstorch** [comment]
It now shows me all the time that a new nightly is available, even after update. What did I do wrong :thinking: ?

**Comment by pstorch** [comment]
@Bananeweizen it looks like the version code is not set correctly in the nightly APK.
The generated file `NIGHTLY_CODE` contains the correct code `30180101`, but this is not written into the APK and causes nightlies not updating. 
Maybe you can have a look here?

@Lineflyer found this line in the build.gradle file: https://github.com/cgeo/cgeo/blob/037b65c89ef294ad6e393af4ff46202aa1cc3847/main/build.gradle#L221
Can it be that the variant `nightly` is not recognized correctly anymore?

**Comment by Lineflyer** [comment]
Thanks @pstorch 

We should then also check the other variants with special code setting, such as RC.

**Comment by Bananeweizen** [comment]
The code setting the versionCode is executed during gradle build, I can see that in the debugger. Nevertheless it seems like the APK is build without actually using the +1000 years, as this json file of the build suggests: http://ci.cgeo.org/job/cgeo%20nightly/ws/main/build/outputs/apk/basic/nightly/output.json. I'm investigating how that can be, but I also have no idea right now.

**Comment by Lineflyer** [comment]
Perfect! Thanks @Bananeweizen

**Comment by mucek4** [comment]
Is it right this issue is closed?

**Comment by pstorch** [comment]
Looks like the nightly builds are working again.
We just haven't tested the release build yet, have we?

**Comment by Lineflyer** [comment]
> We just haven't tested the release build yet, have we?

No, but for the release build we use the normal date without modification, this should work.
For RC and legacy the fix from @Bananeweizen handles them as well, so I assume, they will also work.
