### ISSUE TITLE
Changing only notes in waypoint calculator does not set the dirty state

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6903]
##### Detailed steps causing the problem:
- Open waypoint calculator; the calculator must be in "incomplete" state where the disc icon is displayed
- Press Save (disc button); disc button gets disabled
- Edit notes within the waypoint calculator

##### Actual behavior after performing these steps:
Disc button stays disabled; saving is not possible

##### Expected behavior after performing these steps:
It should be possible to edit only calculator notes and to save it.

##### Version of c:geo used:
2018.01.04-NB

##### Is the problem reproducible for you?
Yes

**Comment by pstorch** [comment]
There are no "calculator notes", these are the user notes from the waypoint and written to it immediately. It is independent of the calculator state.
I know it is confusing, but we won't really fix it until we merge the whole calculator with the Edit Waypoint activity.

**Comment by Matze2** [comment]
I know that these are the user notes.
Nevertheless with the above steps you can change the user notes but you cannot save them since changing the user notes is not included in the dirty state of the calculator editor.
It is important that the calculator must be in incomplete state where the disc icon is displayed. Only in this situation an intermediate save without closing the editor is possible. I will also update the initial report.
Based on your answer I am not sure if you are aware of this behavior or not.

**Comment by pstorch** [comment]
Ah, sorry. Now I got it. In the incomplete state, no changes in the notes field are saved.

**Comment by pstorch** [comment]
Thinking about: do we still need the distinction between the checkmark and the save icon? This was introduced, because the EditWaypointActivity couldn't handle null waypoints (which you get when having incomplete calculations). Now it is supported and I think we could simplify the design of the Calculator by just having a done action (checkmark icon) and a cancel action (X-icon). And both always enabled.
What do you think?

**Comment by Matze2** [comment]
Yes, I think this makes sense. And I like simplification in general. 👍

**Comment by Lineflyer** [comment]
Yes I agree, that the distinction between "save" and "check" is IMHO no longer needed, now that the logic of NULL coords is available for the waypoint.

**Comment by pstorch** [comment]
Ok, let's simplify. I'll have a look.
