### ISSUE TITLE
Support Mirrorlink

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6911]
This request from support mail is similar to #6684 but aims not to use Android Auto (which we learned is no real option) but support [Mirrorlink](https://mirrorlink.com/).

I did not yet take a closer look about the requirements to support this and if it may be meaningful.

**Comment by rsudev** [comment]
I gave it a short check. Even for MirrorLink there is a number of conditions to be met (regarding UI and functionality), so we would likely have to develop special UI-variants for this context.
You also have to get certified (likely in a similar fashion as for Android Auto, as this stems from the same legal framework regarding driver distraction etc.).
I'd say this would be as realistic as supporting Android Auto...

**Comment by SammysHP** [comment]
I cannot go into detail because of a NDA, but I am sure that c:geo is not qualified for this product. If this is similar to another product that I know then you need the permission from each car manufacturer (whitelist) and there is a huge list of limitations for what you can do and in which way.

**Comment by Lineflyer** [comment]
So lets close this. Not likely to happen.

**Comment by pstorch** [comment]
Interesting you need to have your app certified.
And this is not free: "CCC does not charge for the certification process, but there are fees associated with the testing at the lab."
And when there is a change the CCC needs to be informed and a new certification might be needed.

**Comment by moving-bits** [comment]
I did some research. Development info is on https://mirrorlink.com/Developers - necessary code adjustments seem to be ok (at quick glance, at least), but as pstorch cites: certification (free of charge) requires testing at the lab (not free). Sad to hear that. Would have been nice to get c:geo on the car's screen...

**Comment by Willabee** [comment]
I have been told that if you use an app on your phone to select a geocache and the navigate to it by driving, then it can automatically select android auto in the cars navigation system when your phone is connected. Android Auto currently supports Google Maps and Waze. 
When I went for a test drive in a car supporting Mirrorlink and Android Auto, I tested this using c:geo but it automatically selects 'Here' Maps. I cannot find where to change the default driving app for c:geo. If you can help me here, I will test and report back. I feel sure if Android Auto was the default app then we would have a safe way of driving to geocaches. You can install Android Auto on your phone.
Currently, I am able to enter coordinates by hand into Google Maps and it uses Android Auto to navigate. So all is not lost. But it would be great to simple select a cache in c:geo and off we go.

**Comment by Lineflyer** [comment]
@Willabee c:geo supports to invoke various navigation tools. If you open a cache in c:geo and select Navigate - Driving it should invoke Google Maps which (I assume) will keep the route once you open Android Auto...or not?

**Comment by Willabee** [comment]
When I open a cache in c:geo and select Navigate - Driving, it uses 'Here We Go' Maps for navigation. My request is to remove this app from being selected and replace it with 'Waze' or 'Google Maps'. Then I can test it in Android Auto on the car's infotainment system. How do I switch apps?

**Comment by Lineflyer** [comment]
You probably selected Waze as your default app for this intent. To change this you have to go to your device app management and delete "defaults for open with" for the Waze app.
Alternatively you can also try to use Navigate - Other external app from c:geo. This should bring up all apps with navigation support to select from. But maybe also here the default "Waze" applies, so you have to go back to the first described method first.
