### ISSUE TITLE
Feature request: actual location mystery cache

### ISSUE THREAD

**Issue by DJAxel** [cgeo/cgeo#6913]
Ability to add the actual location of a mystery cache (and save locally). Not like the notes-function does already now, but by actually displaying the cache on the map at that position. This makes it easier to figure out a route with all caches a user wants to find on a tour.

Optionally: ability to save multiple locations in case the user is unsure of the coördinates and no geochecker is available for the cache.

**Comment by SammysHP** [comment]
This can be done via waypoints. You can set the type to "final" and optionally set it as cache location on the map.

**Comment by Lineflyer** [comment]
http://www.cgeo.org/faq#modified-coords
