### ISSUE TITLE
Handling of waypoint without coordinates in GPX files

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6915]
Currently c:geo only exports waypoints with coordinates. Waypoint without coordinates (like #6883 or final waypoints read from the website) are skipped during export.
Import of waypoints without coordinates is possible by defining `lat` and `lon` as empty `""`. But this is not according to the GPX schema.

One idea was to use `lat=0` and `lon=0` which would be valid to the GPX schema but this is actually a valid coordinate. Defining this as NULL would be a "trick".

**Comment by Matze2** [comment]
Maybe there is also here a possibility to (misuse) GSAK schema extension to mark the coordinates as empty.

**Comment by steve8x8** [comment]
Several times I have found I wouldn't be able to edit imported waypoints (```<wpt>```). This may be related?
Although I agree that ```<wpt>``` is in violation of the GPX schema, it has worked for years now, and the GPX import side should still tolerate this. And yes, an export should cover "locationless" waypoints and their accompanying information - many caches provide the final formula not in the long description but in a waypoint note.
Please take into account that there may be import sources which don't know about GSAK. Thanks.

**Comment by murggel** [comment]
@Lineflyer please assign this to me
The first parts of it are already closed with #9849.
I also had the last case (don't be able to edit imported waypoint with empty coordinates) and I already had a look at it.

**Comment by Lineflyer** [comment]
> @Lineflyer please assign this to me

Done and thanks for stepping into more issues. Highly appreciated :)
