### ISSUE TITLE
Calendar entries in UTC

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6921]
Since today newly created calendar entries are in UTC instead of GMT+1 (with the start time adapted accordingly), although both my phone and the calendar app are set to GMT+1. Has anyone else seen this behaviour? I must admit I believe this to be a change in the android calendar app, since I regularly update the lineageos.

**Comment by pstorch** [comment]
C:geo set the timeZone to UTC when sending the Intent to the Calendar App: https://github.com/cgeo/cgeo/blob/24e8cd8645e635e0f893c7f0375e4810f615a86d/main/src/cgeo/geocaching/calendar/CalendarEntry.java#L119

I just tested it and on my phone: the Calendar App shows a popup with the new Event and the time in UTC. And also stating, that the timeZone is UTC. When I confirm the popup, so the event is added to the calendar, then it shows my local time.

**Comment by Lineflyer** [comment]
I am sure it was working some weeks ago when I added an event.
I was actually testing a user report on support mail (but could not reproduce).

I will retest it with a recent build on my phone and report back.

Is there a time zone information for event caches on gc.com? I guess not, as only the date is defined.
However if there is a chance to get the information in which time zone the event is taking place, we should use this time zone to create the calendar entry. 
Else we should use the mobiles current timezone setting...however that will produce wrong entries if you add an event hosted in another time zone.

**Comment by Bananeweizen** [comment]
I think we switched to UTC some years ago after we already had such trouble like events at 23 o'clock of the day before the actual event when using local timezone. I'd therefore consider this purely cosmetic and lower priority than potentially re-introducing that bug with the wrong date.

**Comment by Bananeweizen** [comment]
I switched to another calendar app, and the problem does not exist anymore. So it is really a matter of the app whether it displays the time as given in the event data or in the user locale timezone.

**Comment by gsstark** [comment]
Not sure how this could be considered a cosmetic problem. It makes the "add to calendar" feature almost unusable. It makes every event at the wrong time and requires the use to change the time zone and time manually for every event.
