### ISSUE TITLE
Replace stored 123 days ago by months and years

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6922]
We should adapt the "stored X days ago" by months (2 to 11) or years plus months for even longer periods.

**Comment by pstorch** [comment]
And don't show that it has been stored when the save date is 0 :wink: 

![image](https://user-images.githubusercontent.com/5598124/35591800-76278258-060b-11e8-934a-3ba2b0987492.png)

**Comment by Bananeweizen** [comment]
@pstorch I really hope that was just from debugging? We should never have that situation...

**Comment by pstorch** [comment]
This is from a user in the c:geo fangroup on Facebook.

**Comment by pstorch** [comment]
@Bananeweizen would you expect an exact months/year calculation?
Or just an aproximation like: > 62 days then show months (starting with 2) and > 356 days show "over a year ago"?

**Comment by Lineflyer** [comment]
Somehow I remember that we had this already. Did we remove it (accidentally)?



Von meinem Smartphone gesendet.
null

**Comment by Bananeweizen** [comment]
@pstorch I would neither print "1.0456 years", nor would I print "1 year, 2 months, 3 days, 4 hours". Basically the goal is to make the number small, such that it is easily understable (9 months is more simple for users than 275 days).

Your suggested number of days sounds fine to me. Maybe we could even use month writing for 1 month already, e.g. >1/12*365 days -> more than 1 month ago, >2/12*365 days -> more than 2 months ago, ...>12/12*365 days -> more than a year ago, >2*365 days -> more than 2 years ago...

Contrary to my initial suggestion, after reading your example, I believe there is no additional value in showing "more than 1 year, 3 months ago" (years + months) compared to the simple "more than 1 year ago" (years only).

**Comment by pstorch** [comment]
I thought about simplifying the > 1 year case: `over a year ago`
Regardless of if it is 1, 2 or more years ago.
