### ISSUE TITLE
Waypoints missing

### ISSUE THREAD

**Issue by gcey** [cgeo/cgeo#6926]
##### Detailed steps causing the problem:
Get a GeoCache with waypoints from geocaching.com to c:geo (directly, not via xml)
E.g. https://coord.info/GC6YTQM

##### Actual behavior after performing these steps:
No waypoints in c:geo

##### Expected behavior after performing these steps:
Waypoints in c:geo (as it used to be)

##### Version of c:geo used:
2017.12.17

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: D5803 (D5803, Sony)
Android version: 6.0.1
Android build: 23.5.A.1.291
c:geo version: 2017.12.17
Google Play services: enabled - 11.9.75 (436-182402865)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_AT
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (543,8 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (543,8 MB free) external non-removable
Geocache data: /storage/0000-0000/Android/data/cgeo.geocaching/files/GeocacheData (15,8 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (51,4 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: contacts
--- End of system information ---

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by pstorch** [comment]
Confirmed. Looks like waypoint parsing is broken.

**Comment by Bananeweizen** [comment]
Who can take care of preparing a new release?

**Comment by Bananeweizen** [comment]
What is the current state of the release branch? Can we simply release or do we want to cherry pick the above change onto the last tag (from December) and release that as a quick bug fix version only?

**Comment by pstorch** [comment]
I think the release branch is safe.

**Comment by Lineflyer** [comment]
Release is safe, but I am not available for releasing until mid February. Someone else needs to do it.

**Comment by pstorch** [comment]
I have access to the Google developer console, but I've never done a release. Is someone else available or is there a description on how to do it?

**Comment by Bananeweizen** [comment]
Description is available here: https://github.com/cgeo/cgeo/wiki/Prepare-a-release
I've just built a release and put it on Google Play and github. I'm just wondering whether or not to release for 100% already.

**Comment by Bananeweizen** [comment]
remaining issues in #6929.
