### ISSUE TITLE
Logs are not loaded

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6927]
Looks like that not only the waypoint parsing fails #6926, but also the Logs cannot be parsed.
Load a geocache which is not yet in your database (existing logs are kept): result logs are empty.

**Comment by pstorch** [comment]
Sorry, I'm confused. Now that I wanted to debug it I can't reproduce it anymore. Neither on release, nor on master.

**Comment by Bananeweizen** [comment]
that happens when loading a cache before the login has finished. I've been running into this with the emulator several times too.

**Comment by pstorch** [comment]
@Bananeweizen that might be an explanation.
