### ISSUE TITLE
Release 2018-02-05

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6929]
- [ ] Check/Import incoming Translations from Crowdin
- [x] Check/Insert correct version name as headline in ```changelog-release.xml```
- [x] Build release on CI server
- [x] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [x] Upload and publish ```cgeo-release.apk``` to Google Play
- [x] Tag the release on Github
- [x] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [x] Increase release to 100% on Play Store, if no trouble occurs
- [ ] Provide Play Store update notes in other languages than English
- [x] Publish release on F-Droid 
- [ ] Rename/Create milestones on Github
- [x] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [x] Post release info to Facebook 
- [x] Post release info to G+ 
- [x] Post release info to Twitter (via @SammysHP)

**Comment by Lineflyer** [comment]
I managed to load the latest nightly here on a terribly slow network on Aruba and its loading waypoints just fine. Also no other issues found so far...however I use it mostly offline at the moment.

**Comment by SammysHP** [comment]
Can someone please publish the release to f-droid?

**Comment by kumy** [comment]
Just hit play on the jenkins job :)

On February 12, 2018 7:06:57 PM GMT+01:00, SammysHP <notifications@github.com> wrote:
>Can someone please publish the release to f-droid?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6929#issuecomment-365009252

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lineflyer** [comment]
Notification to social networks done.

Translation of release notes on Google Play to German done.
Remark:
As we do not (yet) have translated release notes available, I usually only provide a manual german translation on Google Play while publishing (as this is a rather large user group).

**Comment by Lineflyer** [comment]
I think the import of translations (which is not marked as done above) is now obsolete for this release.
Thanks to the team for taking care of the release. Good to know, that it does not rely ona single team member to get the release done.

If you feel any step was undocumented or you need access to whatever platform to support the release process, pleae let us know.
