### ISSUE TITLE
geokrety tests failing since some days

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6930]
@kumy is that some server side issue?
http://ci.cgeo.org/job/cgeo%20continuous%20integration/1892/testReport/cgeo.geocaching.connector.trackable/GeokretyConnectorTest/testSearchTrackables/

**Comment by kumy** [comment]
Server seems to respond well https://geokrety.org/export2.php?wpt=OX5BRQK

I can look, but later in the week. Sorry

On February 6, 2018 9:11:48 PM GMT+01:00, Michael Keppler <notifications@github.com> wrote:
>@kumy is that some server side issue?
>http://ci.cgeo.org/job/cgeo%20continuous%20integration/1892/testReport/cgeo.geocaching.connector.trackable/GeokretyConnectorTest/testSearchTrackables/
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6930

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
Thinking about it again, geokretymap.org proxy is the problem here...

On February 6, 2018 9:11:48 PM GMT+01:00, Michael Keppler <notifications@github.com> wrote:
>@kumy is that some server side issue?
>http://ci.cgeo.org/job/cgeo%20continuous%20integration/1892/testReport/cgeo.geocaching.connector.trackable/GeokretyConnectorTest/testSearchTrackables/
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6930

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
https://api.geokretymap.org/export2.php?wpt=OX5BRQK

On February 6, 2018 9:11:48 PM GMT+01:00, Michael Keppler <notifications@github.com> wrote:
>@kumy is that some server side issue?
>http://ci.cgeo.org/job/cgeo%20continuous%20integration/1892/testReport/cgeo.geocaching.connector.trackable/GeokretyConnectorTest/testSearchTrackables/
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6930

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
BaseX database was unreachable… Also monitoring is missing for that, I'll add it later.
