### ISSUE TITLE
Turkish language not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6934]
##### Detailed steps causing the problem:
- Use current release or up to date nightly
- Set your device to turkish language
- Start c:geo

##### Actual behavior after performing these steps:
c:geo start with english strings

##### Expected behavior after performing these steps:
c:geo should start with turkish strings

##### Version of c:geo used:
2018.02.16-NB

##### Is the problem reproducible for you?
Yes

##### System information:
It shows correctly:
```
System language: tr_TR
```

##### Other comments and remarks:
Reported on Crowdin: https://crowdin.com/messages/287556

**Comment by Lineflyer** [comment]
any ideas? Can someone reproduce?

**Comment by Lineflyer** [comment]
Thanks @rsudev 
Testing and working with latest NB. Did you crosscheck if all other supported languages are contained in the config file?

**Comment by rsudev** [comment]
No (even though I had the impression they should). Will cross check.

**Comment by rsudev** [comment]
Confirmed. All currently supported languages are present in the build file.
