### ISSUE TITLE
Recent amount of crowdin proofreader requests

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6937]
I'm surely not the only one who raised an eyebrow since we recently got a request to confirm someone as proofreader on crowdin almost every second day. I think I found the reason: There is a website which claims to reward open source contributors using a blockchain currency I did not know before: https://utopian.io/.
One type of contributions are crowdin translations, so you see this is not sparked by an interest in adding translations to our project, but just to earn that digital currency there.
I have no idea whether that website is commercial, not-for-profit, good, bad or whatever. But I'm not really happy about getting such translations, since I expect low quality (in order to rush to the next "payout"). I have not approved any such crowdin request and intend to not do that as long as I'm not convinced of having an actual geocacher asking.

**Comment by rsudev** [comment]
I am sorry for having created such a mess in this context. Once I said yes to the first two, it got harder to deny the next...
I share your assumption, that the translations are likely not the best and probably do not reflect the terminology of the (if existing) local geocaching community...
I think it is a good idea to more explicitly state that we require translators to be part of the geocaching community. While I had this somehow in the back of my mind, it was not yet clearly enough stated, to prevent me from this foolishness.

**Comment by Lineflyer** [comment]
Crowdin allows to easily remove contrubtions of certain users. I suggest we leave the translations in but remove the profreads of those users.

Question would be how to judge if someone is capable of proofreading. We could kindly ask for his geocaching user name (voluntary) to check his profile. The reasoning we can give is, that this helps us to qualify if he is used to geocaching terminology.

**Comment by rsudev** [comment]
I think in general our approach worked in the past, even without formally checking for a possible geocaching.com user account (something which geocachers might not even have in all geographies), It was just my failure to raise this point sufficiently before letting people 'in'.
I also checked the activity stream and I didn't find any indications of 'vandalizing' other translations by proofreaders, so I don't see a pressing need to be more restrictive (even though it might be worthwhile to consider it going forward)

**Comment by kumy** [comment]
I have accepted some new translators, but only set them proofreader on
the "requested" language. I have no idea on the translation quality, are
they machine suggestion only? I cannot judge… I propose to downgrade
global proofreader status for those contributors to contributed language
only as proofreader.

**Comment by Lineflyer** [comment]
>  I propose to downgrade global proofreader status for those contributors to contributed language only as proofreader.

I agree. The question remains if we should remove the proofreadings (at least where proofreadings and translations have been done by the same person).

**Comment by rsudev** [comment]
I would try two things:
- contact all those people that came in lately over the next days and trying to assess their connection to the geocaching community and their translation skills (by their track record on crowdin). From there I would readjust their proofreader status
- try to assess the quality of the translation (I think even without knowing the target language it is possible in this case to see whether core geocaching terminology was handled consistently). Depending on this judgement, the inclusion of these languages into c:geo can be postponed (or reverted, in the case of Cebunao)

**Comment by Lineflyer** [comment]
Sounds reasonable. Will you go for it or shall I also take a look?

**Comment by rsudev** [comment]
Regarding the conversation, I am probably in the best position, as they mainly contacted cgeo (the project owner) and our interaction is visible in the conversations there.
If you want, I surely can give you the password as well, so you can also have a look.
Regarding the languages, I am more than happy if you help to clean up the mess I created...

**Comment by Lineflyer** [comment]
I think I also have manager role,  however start with your part first in taking a look and contacting the user. If you later tell me, which translations/proofreads you consider not suitable, I will revert or manually undo those on Crowdin.

**Comment by Bananeweizen** [comment]
@rsudev You didn't do anything wrong. In fact, you cared about new contributors, which is really good. If I were more actively involved in translations, I would probably have done the same.

**Comment by Lineflyer** [comment]
@rsudev I have to agree to @Bananeweizen. There was nothing wrong with what you did. I also received one of these requessts and approved it after having seen that the user contributed to the translation already.

I took a closer look to the crowdin status today:
- I think Tagalog, Fillipino, Cebuano, Indonesian and (possibly) Arabic translations might be pushed through this payment website. 

- I took a few examples of fixed geocaching wordings like "Wherigo" , "Geokrety", "Earthcache" (and some more) and checked them in these languages. Its anyway hard to judge without having any idea of those languages, but at least it does not look like pure use of machine translation and in most part the terminology seems consistent throughout the strings.

- From the activity log I can see that the new proofreaders stick to their native language (although the role settings might allow to also alter other languages), only one user who disapproved some French strings while translating Arabic (but he seems to speak both).

So it might be - although I am far away from being convinced - that these contributors attracted by financial benfits still give us a benefit with their new translations.

My suggestion would be to take all the translation contributions and new languages as they come but more carfully look on assignment of proofreading roles in future.
I therefore propose the following:
- Let 2 dedicated members of the team manage the role assignment on Crowdin only
- Before approving proofreaders we should check thier other contributions on Crowdin (if applicable) and/or have a short chat with them about their knowledge of Geocaching
- Don't use global roles but assign proofreading rights by language only (Project settings - Translators - Details of a user with translator role - Language permissions)

Regarding the ongoing translation/proofreadings I suggest to let it continue with the current acitivities but don't accept more proofreaders for the mentioned languages by now and change the proofreaders role setting as sugggested above.

**Comment by Lineflyer** [comment]
Any objections to review and adapt the proofreading roles as mentioned above?
If not, I will do so tonight.

**Comment by Lineflyer** [comment]
I have modified all "Proofreader" profiles to limit them to their contributed languages. This means I set the role "Translator" and case by case assigned the proofreading permission by contribution language.

In rare cases (e.g. proofreading role but never approved a string) I just selected the "Translator" role instead.

I also informed all involved users that we reviewed the roles and to contact me in case of problems.

**Comment by Lineflyer** [comment]
The Crowdin messaging system is a bit strange. In my outbox I do only see two users addressed by my mail.
Did anyone of you receive it?

**Comment by Lineflyer** [comment]
The Crowdin messaging system is a bit strange. In my outbox I do only see two users addressed by my mail.
Did anyone of you receive it?

**Comment by Lineflyer** [comment]
The Crowdin messaging system is a bit strange. In my outbox I do only see two users addressed by my mail.
Did anyone of you receive it?

**Comment by UniQP** [comment]
I received the mail.

**Comment by pstorch** [comment]
I received a mail from from Crowding with your message, too.

**Comment by Bananeweizen** [comment]
Me too. Just did not check my emails before. :)

**Comment by Lineflyer** [comment]
Thanks for the feedback.
I think we can close this topic, for now?
