### ISSUE TITLE
Travel Bug status reset with screen rotation during cache log

### ISSUE THREAD

**Issue by Lomanic** [cgeo/cgeo#6938]
##### Detailed steps causing the problem:
- Open a cache listing in cgeo, enter the menu to add a log to this cache
- (you have to have TBs in your inventory on GC.com) Change the visited/dropped status of any TB you have
- rotate the screen 

##### Actual behavior after performing these steps:

Depending of the setting at _Settings_ -> _Logging_ -> _Set trackables to "Visited"_, Travel Bug(s) status is always reset to "Do Nothing" (if setting is disabled) or "Visited" (if setting is enabled) each time the screen rotates.

##### Expected behavior after performing these steps:

TB status should not be reset if user changed a given value. Everything else (log type such as Note, Found it, Did not find…, log text, date) is kept between screen rotations.

##### Version of c:geo used:

`2018.02.05`

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: D5803 (D5803, Sony)
Android version: 5.0.2
Android build: 23.1.A.1.28
c:geo version: 2018.02.05
Google Play services: disabled - 11.9.75 (236-182402865)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (680,9 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (680,9 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (680,9 MB free) external non-removable
Database: /data/data/cgeo.geocaching/databases/data (9,4 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Connecté) / PREMIUM
Geocaching.com date format: d/MM/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:

#6869 is a very similar issue but for the <kbd>[WP Calc](https://github.com/cgeo/cgeo/labels/WP%20Calc)</kbd>

**Comment by Lineflyer** [comment]
Similar or even the same as described in #4697

**Comment by Lomanic** [comment]
I can still reproduce with `2018.10.13`, this was not fixed by the  commits above.

**Comment by bekuno** [comment]
It works only when no GK is in the inventory.

**Comment by Lineflyer** [comment]
This has been fixed implicitly by recent code changes for logging view.
