### ISSUE TITLE
Local coord reset not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6943]
##### Detailed steps causing the problem:
- Open a saved cache
- Create a new waypoint and select to use the coords as cache coords locally
- Check that coords are now set as cache coords and another waypoint "Original coords" has been created
- Long click on "Original coords" wayoint and select to reset them as cache coords (locally)

##### Actual behavior after performing these steps:
- Cache details page still shows the previously set cache coords (also after closing and opening the cache)
- Refresh of the cache is needed to have the original coords shown again

##### Expected behavior after performing these steps:
- Coords should be reset as expected

##### Version of c:geo used:
2018.02.15-NB

##### Is the problem reproducible for you?
Yes

**Comment by Lineflyer** [comment]
Can someone reproduce this?
I wonder since when we have this bug....

**Comment by Matze2** [comment]
I can reproduce it with 2018.02.14-NB1.
Until now I never used this feature to set coords as cache coords only locally.

**Comment by Matze2** [comment]
For me both cases (only in c:geo/in c:geo and on website) show the above behavior.

**Comment by CSTDev** [comment]
Same behavior with currently released version 2018.02.05

**Comment by kumy** [comment]
Same with 2018.01.10-NB-e2777be

On March 7, 2018 4:58:40 PM GMT+01:00, CSTDev <notifications@github.com> wrote:
>Same behavior with currently released version 2018.02.05 
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6943#issuecomment-371185684

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pstorch** [comment]
The `Geocache.gatherMissingFrom()` method reverts the changes before saving it. This method is responsible to load existing data from a previously stored cache in case we have a partially loaded cache, so that we don't miss any data. 
I think we have to introduce a separate save method in the  `DataStore` class to just update the `coords` and the `userModifiedCoords` flag.

**Comment by Lineflyer** [comment]
For me it would be interesting to know which previous change introduced this bug, because it used to work some time ago.

**Comment by pstorch** [comment]
It got introduced by me with the fix for #5476  :disappointed:

**Comment by Matze2** [comment]
Just tried latest nightly and both cases are fixed again.
Funny that nobody used this feature since one year...
