### ISSUE TITLE
Sync personal notes?

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#6945]
Maybe I missed it somewhere, but I was not able to find in at c:geo website in description.
There are "Personal notes" in the app, but do you support uploading them to the GC server (if allowed)? I'm not sure is it implemented on GC.com, but in general is sounds like a feasible feature to have some user notes attached to the cache. Is it supported in c:geo?

**Comment by Lineflyer** [comment]
Yes, this is supported by cgeo already. There should be an upload buttom next to the edit button.
However it might be a premium feature on gc.com, not sure at the moment.

**Comment by GodfatherThe** [comment]
Could you please provide some reference about the functionality if we'd like to implement it from our GC website? What are the API calls you're using?

And maybe too broad and a bit of off-topic, but it would be nice to have reference of typical API output which you expect, so if we add some new fields from GC side we keep consistent with common API and not invent our own formats

**Comment by SammysHP** [comment]
We use the website, so there is no user notes API used in c:geo currently.

**Comment by Lomanic** [comment]
Can confirm online cache notes are a premium-only feature on GC.com website @Lineflyer

**Comment by GodfatherThe** [comment]
So then can it be considered as FR to add support of uploading\syncing user notes with GC website, where supported then?

**Comment by SammysHP** [comment]
As Lineflyer already said it is possible to upload notes to geocaching.com if you are a premium member. I do not know any other platform that supports user notes.

**Comment by rsudev** [comment]
Okapi does support uploading user notes and I just verified that it works on oc.de.

**Comment by SammysHP** [comment]
Oh, you're right. I've never used user notes on OC. :/

**Comment by pstorch** [comment]
@GodfatherThe when you are interested in the API we are using: this is the Okapi doc for save personal notes: https://www.opencaching.de/okapi/services/caches/save_personal_notes.html

**Comment by anondev-sudo** [comment]
Hello, is there a feature to automatically sync local personal notes you set in cgeo with geocaching website?

**Comment by SammysHP** [comment]
Yes. From a list, open the menu, go to "export" and select "upload personal notes".

**Comment by anondev-sudo** [comment]
I think it should be rewrorked that it will only upload to geocahing personal note if there is some change, because when I have long list it takes long and wastes network bandwidth. Cgeo should save to database if personal note was edited locally, and only upload those changed notes to geocahing.

**Comment by SammysHP** [comment]
That raises the question: How are merges handled during upload currently? I wanted to write: "c:geo has to check all caches for changes on the server before deciding whether to upload the note or not." – but now I'm not sure if there's any check at all.

**Comment by eddiemuc** [comment]
> That raises the question: How are merges handled during upload currently? I wanted to write: "c:geo has to check all caches for changes on the server before deciding whether to upload the note or not." – but now I'm not sure if there's any check at all.

There's no such check currently. c:geo overwrites PN on server on upload without mercy. Reasoning behind this:
- for c:geo users it is assumed that c:geo is their "master system" when it comes to PN
- checking would require refetching the server data, thus an additional server call 

c:geo DOES however merge server PN and c:geo PN on cache refresh. Users worrying about overwriting server PN can thus refresh the cache before upload.

**Comment by moving-bits** [comment]
> c:geo overwrites PN on server on upload without mercy.

And if you are using the online version as your master version, you can also configure c:geo to work the other way around, always using the online version, overwriting c:geo's offline version without merging.

It all depends on your personal workflow.
