### ISSUE TITLE
checkstyle configs are broken

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6946]
Unfortunately the checkstyle configuration xml schema sometimes changes in incompatible ways. Our config schema does not fit the more recent version used in codacy by now, therefore the codacy scan seems to ignore it (and reports checks we disabled).

will upgrade the configuration

**Comment by Lineflyer** [comment]
@Bananeweizen Is this still valid?

**Comment by bekuno** [comment]
@Lineflyer Can you add me to the codacy cgeo org? I will have a look at the configuration.

**Comment by Lineflyer** [comment]
@bekuno I tried to add you. Strangely I used the mail address known to me to add you and codacy autoamtically now uses another mail address (maybe it identified your codacy account?).
Please try if it works.

**Comment by bekuno** [comment]
@Lineflyer This was ok. I changed the primary mail address on codacy. Now it was possible to join the team.

**Comment by bekuno** [comment]
Codacy should use our checkstyle/suppression.xml. 
Lets see if PR #8045 works fine.

**Comment by fm-sys** [comment]
AFAIK fixed / no longer valid
