### ISSUE TITLE
Show whether TB has already been discovered

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6947]
From support mail:
Geocaching.com now gives a status note on the top right of a trackable's page letting us know if we've discovered a TB before. It would be wonderful if that same status could be added when we pull TBs up in cgeo.  

I'd be great if in the same basic place you show "Found it" when we pull up a cache page showed "discovered it" on a trackable. We keep logging the same ones over and over between the 2 of us because we'd otherwise have to link to the web browser to see if we've logged it before or not, & that's a pain.

---
I did not yet see this feature on the webpage...seems to be pretty new.

**Comment by Lineflyer** [comment]
+1 from support mail also providing a screenshot of the web page function:
![20180605_164414](https://user-images.githubusercontent.com/949669/41085249-a9a7ad76-6a36-11e8-8979-b0b0a40225fe.png)

**Comment by bjdupuis** [comment]
I'd be up for addressing this one if there's no great objection.

**Comment by Lineflyer** [comment]
@bjdupuis Sure!Just go ahead and feel free to address any question either in this issue or use our developer chat (see https://www.cgeo.org/development )

**Comment by bjdupuis** [comment]
Excellent. Have since coded it up. Question: since the issue was created it looks like the wording has changed a bit on GC...

![screen shot 2018-09-19 at 5 39 48 pm](https://user-images.githubusercontent.com/644945/45783568-259a7180-bc34-11e8-9d4b-18a9cefce009.png)

For the in-app text, here's what I've currently got utilizing this verbiage (at least for ones the user has found). Thoughts?\
![screen shot 2018-09-19 at 5 48 29 pm](https://user-images.githubusercontent.com/644945/45783622-4e226b80-bc34-11e8-9768-6105acc93686.png)

**Comment by Lineflyer** [comment]
I assume the wording on the website has not changed but their might be two different states: Retrieved if the user realy retrieved it from a cache, discovered if the user only discovered it.

**Comment by Lineflyer** [comment]
Regarding the in app:
Looks fine to me. Would be a nice addon if the line would be clickable according to the link (to the referenced log) also provided on the webpage. So the user can open his log for that TB (in browser).

**Comment by bjdupuis** [comment]
Rock, will get the link too. Sorry, didn't see this feedback before the PR.

**Comment by Lomanic** [comment]
You could leave in a cache (or in someone else's hands) a retrieved TB and it should show as "Discovered" in its page (you could grab it back after saving the HTML of course).

**Comment by bjdupuis** [comment]
> Regarding the in app:
> Looks fine to me. Would be a nice addon if the line would be clickable according to the link (to the referenced log) also provided on the webpage. So the user can open his log for that TB (in browser).

I expected caches to already have this functionality but they do not. I'll add a separate issue for that for consistency.

I'm wondering if the best user experience is linking out to the browser or switching to the "Friends/Own Logs" page in the view pager, keeping the user in the app. Thoughts?

**Comment by bjdupuis** [comment]
> You could leave in a cache (or in someone else's hands) a retrieved TB and it should show as "Discovered" in its page (you could grab it back after saving the HTML of course).

Actually apparently once you've ever retrieved it you've always retrieved it. I have no trackables in my possession but the ones I've lifted and placed elsewhere show as "retrieved". I tried to "discover" one this morning at a nearby cache but it was missing :/.

**Comment by Lomanic** [comment]
Did not know about that, I will then upload the HTML page of one of the trackables I discovered, this weekend.

**Comment by bjdupuis** [comment]
> Did not know about that, I will then upload the HTML page of one of the trackables I discovered, this weekend.

Awesome, thank you.

**Comment by Lomanic** [comment]
[There it is](https://gist.github.com/Lomanic/49f2e1c5557e5193cc7d6fe80d553128), only difference is (as expected) that the `#ctl00_ContentBody_InteractionLogTypeText` \<span\> says _Discovered it!_ instead of _Retrieved it!_.

![image](https://user-images.githubusercontent.com/5020919/45917977-f9733080-be7f-11e8-9a9f-a4abc408d6c4.png)

**Comment by bjdupuis** [comment]
Delightful, thank you. 

The only scary part is your date. I wondered whether localization might bite me and it appears it will. Why did they have to use that particular format?

**Comment by SammysHP** [comment]
We already detect the selected date format for logs, caches etc, maybe it's the same format.

**Comment by bjdupuis** [comment]
> We already detect the selected date format for logs, caches etc, maybe it's the same format.

Aha, `GCLogin.parseGcCustomDate()`.

**Comment by bjdupuis** [comment]
So the date is doable, now on to the next niggling item. I picked a good one to start with I guess.

To show the status of either discovered or retrieved I have to parse the "Discovered/Retrieved it!" text in `ctl00_ContentBody_InteractionLogTypeText`. Fine. Perhaps unsurprisingly, that text is localized. Here's French. 

![screen shot 2018-09-25 at 2 24 12 pm](https://user-images.githubusercontent.com/644945/46034588-020d7600-c0cf-11e8-9e06-aa5e0d84651e.png)

The caches themselves get around this by basing their "found it" on the _non-localized_ strings in the log entries. The trackables don't do the same level of log parsing so I can't _easily_ do a similar trick. There's a couple of options:

1. perform similar log parsing as caches. Seemingly unnecessary aside from this functionality and a bit wasteful of network requests.
2. Just use what localized disposition comes in on the page (as depicted below) even if that localization doesn't match the c:geo local setting for language.

![screen shot 2018-09-25 at 2 29 42 pm](https://user-images.githubusercontent.com/644945/46034818-911a8e00-c0cf-11e8-8195-a67fc03703e2.png)

I'm unsure what the appropriate answer is. 

As a follow-up to this...

> I'm wondering if the best user experience is linking out to the browser or switching to the "Friends/Own Logs" page in the view pager, keeping the user in the app. Thoughts?

Given that "own" logs for trackables might not be pulled if it isn't on the first page I'm thinking this is a non-starter and that linking out to the browser is the only real answer.

**Comment by rsudev** [comment]
c:geo switches the gc.com page to English, when logging in (for similar reasons as this one). Even though we tried to get some information out of the page regardless of language setting, many places still require English. IMO you are good to assume that here as well.

**Comment by bjdupuis** [comment]
Interesting. Apparently I was "fooling it" by reloading the trackable in c:geo after setting the language to French on the web settings, hence getting the "Récupéré" in-app. Is that then just an edge case that I shouldn't necessarily worry about?

**Comment by SammysHP** [comment]
http://www.cgeo.org/faq#website-english
