### ISSUE TITLE
Opencaching Italia support

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6958]
We just received a support mail askign for support of the opencaching.it platform.
AFAIR there is some conjunction between oc.de and oc.it, isnt it?

**Comment by Bananeweizen** [comment]
Yes. OC.it is fully supported via OC.DE, see https://github.com/cgeo/cgeo/blob/c106905fb2714e51129afbb8ba78eb24c54b4fbc/main/src/cgeo/geocaching/connector/oc/OCDEConnector.java#L12
