### ISSUE TITLE
Downloaded only friends logs

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6960]
Today the GC website seemed quite slow when updating some caches (one by one) over a period of time. For one cache I noticed that afterward the page displaying the logs showed _only_ the friends logs. I assume that we failed to get the first log page but succeeded getting the friends log page. Should we try to do something about this, and if so, what? I assume this is hard to detect, occurs very seldom and I have no idea how to show this to the user in a sensible way.

**Comment by Lineflyer** [comment]
I think the site is malfunctioning today. 
However for such a case I don't know what we could do better, than show what we have.
The only thing I wonder is, why in case of updating an already stored cache is deleting(?) the already existing logs when we fail to retrieve the logs? Or did I understand this wrong?

**Comment by Bananeweizen** [comment]
No. The already existing logs were deleted. But that seems reasonable, since https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/models/Geocache.java#L199 does not look at the logs at all.
