### ISSUE TITLE
Preselected action for single TB in personal inventory

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [cgeo/cgeo#6961]
Currently you can set automaticly visitl only all tb's in inventory when logging a cache.

It would be nice if you can select the tb's for doing this

Perhaps only for own tb's selectable and a standard option for others.

Example:
I have a geocoin which should visit every cache i have found. The other tb's i own should not visit them.
The standard option for other tb's would  represent the current existing function

**Comment by Lineflyer** [comment]
Duplicate of #495
