### ISSUE TITLE
Under which license are the Geocache type symbols licensed? 

### ISSUE THREAD

**Issue by pingurus** [cgeo/cgeo#6967]
I would like to use the symbols which are used by cgeo in my own windows application. Are they licensed under Apache 2.0 like the rest of the project? 
Thank you, 
Pingurus

**Comment by Lineflyer** [comment]
@SammysHP 
The user asked me on support, I derouted him to here.
You might probably know some of the history of the icons/graphics we use in c:geo, do you?

**Comment by SammysHP** [comment]
A few days ago @rsudev and I had a short discussion via IRC. The icons were included in the original source hat carnero gave use licensed under Apache license. So I think they are Apache licensed as well.

**Comment by pingurus** [comment]
@SammysHP
Do you know who the creator of the icons is?

**Comment by Lineflyer** [comment]
I think this is as far as we can tell.
So you might use them with reference to the Apache license.
