### ISSUE TITLE
New cache icons on gc.com map?

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#6968]
Today browsing the map to search for a nice multi, I came across the following cache symbol:

![20180408_cache_map](https://user-images.githubusercontent.com/780005/38466111-65360656-3b24-11e8-9565-a250b96b053c.jpg)
The cache itself is a normal mystery, seemingly equal to the other one to the right, but it has corrected coordinates. I guess this will affected cache type parsing, but not sure whether it is something we want to take into account.

**Comment by Lineflyer** [comment]
Yes, those are either not identified (??) or identified as mystery. I have seen both already. 
AFAIR I opened an issue already...let me check.

**Comment by Lineflyer** [comment]
Closing as duplicate of #6714
