### ISSUE TITLE
(Re)implement "Report a problem"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6973]
Since the new logging function has been implemented (#6519) we have a regression;
The log types "Needs maintenance" and "Needs archived" is no longer available due to the inline function on the new logging page for these kinds of reports.

What we need is a dropdown menu in the logging activity with the following options:
Heading: Report a problem
Selections: Logbook is full / Container is damaged / Cache should be archived / Other

We should furthermore inform the user in a appropriate way, that he needs to describe the problem in his log, once he selected an option.
Here is the Groundspeak wording for that:
"Add details to your log to help the cache owner and other geocachers understand the problem."

**Comment by pstorch** [comment]
For OC, it is "just" a boolean for "Needs Maintenance": https://www.opencaching.de/okapi/services/logs/submit.html. But maybe we can use a dropdown as for GC but with only one item.

For GC: the options are dynamically inserted via Javascript with text in the users language:

```
"log:problemTypes": {
   logFullLabel: "Logbook is full",
   logFullText: "This geocacher reported that the logbook is full.",
   damagedLabel: "Container is damaged",
   damagedText: "This geocacher reported that the container is damaged.",
   missingLabel: "Cache might be missing",
   missingText: "This geocacher reported that the cache might be missing.",
   archiveLabel: "Cache should be archived",
   archiveText: "This geocacher reported that this geocache should be archived. A community volunteer reviewer has been notified.",
   otherLabel: "Other",
   otherText: "This geocacher reported that there is a problem with this cache."
  }
```

To be correct we should also load this dynamically (parse the javascript). Unfortunately there is no ID for each option, so we cannot easily translate it.

**Comment by Lineflyer** [comment]
Implementing this before we release from `master` would be desireable as we save effort to explain users the regression coming with that.

**Comment by pstorch** [comment]
I'm trying to find out the logic, because not all ProblemTypes are valid all the time. 

For example if a cache is disabled I can only choose "archive". For own caches and already archived caches I cannot report a problem at all. For Events I can only report "archive".

Found some logic here:
```
            problemTypes: [{
                value: "logFull",
                label: App.Localizations.get("log:problemTypes").logFullLabel,
                logType: 45,
                logText: App.Localizations.get("log:problemTypes").logFullText,
                checked: !1,
                excludefor: ["3"],
                excludeForGeocacheType: [4, 11, 137],
                isDisplayed: !1,
                isValid: !1
            }, {
                value: "damaged",
                label: App.Localizations.get("log:problemTypes").damagedLabel,
                logType: 45,
                logText: App.Localizations.get("log:problemTypes").damagedText,
                checked: !1,
                excludefor: ["3"],
                excludeForGeocacheType: [4, 11, 137],
                isDisplayed: !1,
                isValid: !1
            }, {
                value: "missing",
                label: App.Localizations.get("log:problemTypes").missingLabel,
                logType: 45,
                logText: App.Localizations.get("log:problemTypes").missingText,
                checked: !1,
                excludefor: ["2", "11"],
                excludeForGeocacheType: [],
                isDisplayed: !1,
                isValid: !1
            }, {
                value: "archive",
                label: App.Localizations.get("log:problemTypes").archiveLabel,
                logType: 7,
                logText: App.Localizations.get("log:problemTypes").archiveText,
                checked: !1,
                excludefor: [],
                excludeForGeocacheType: [],
                isDisplayed: !1,
                isValid: !1
            }, {
                value: "other",
                label: App.Localizations.get("log:problemTypes").otherLabel,
                logType: 45,
                logText: App.Localizations.get("log:problemTypes").otherText,
                checked: !1,
                excludefor: [],
                excludeForGeocacheType: [],
                isDisplayed: !1,
                isValid: !1
            }]

```

That means:
- "logFull" and "damaged" cannot be reported for a DNF log and not for Virtuals, Webcam or EarthCaches.
- "missing" cannot be reported for "Found It" and "Webcam Photo Taken"

**Comment by pstorch** [comment]
I don't know if it is feasible to read and interpret the javascript block inside c:geo to dynamically react to changes from the website. I would start with reimplementing the current logic in c:geo and see how often it breaks. I doubt it changes very often, but who knows.

**Comment by pstorch** [comment]
@Lineflyer sorry for the test logs at your cache.

So I found out that they don't implemented "Report Problem" as a new attribute at the log, but are just posting two logs (even from their webpage). I thought they only create two logs in the backend. :roll_eyes:

**Comment by pstorch** [comment]
Actually we could make it very simple and just add "Needs Maintenance" and "Needs Archived" back to the list of available LogTypes.

Otherwise if I continue as intended, we would have the "Needs Maintenance" also for OC (#5539) and solve #4899 (for those cases where a cacher wants to save a found and a needs maintenance offline).

**Comment by Lineflyer** [comment]
No problem with the test logs as long as you delete them afterwards.
BTW: I found a bug, that even if you delete the NM logs the NM-attribute will stay. That gave me the chance to test a "Maintenance performed" log, which worked well :)

Regarding the implementation option.
I can imagine, that reintroducing the logtypes NM and NA would be potentially easier to do, but having it available as an option while logging your find is IMHO preferable for two reaons:
1) Consistent look and feel with website 
2) Easier implementation for OC

**Comment by pstorch** [comment]
Ok, let's agree on the new way of logging problems. :+1:
