### ISSUE TITLE
Rework one click offline log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6974]
Since we implemented the new logging page (#6519) the log type "Needs maintenance" and "Needs archived" are no longer available as dedicated log types.
When activating" one click offline log" in Settings/Logging these types are still available for offline logging but will be overwritten once the online dialogues is started for that cache afterwards.

To be clarified:
The one-click offline log is mainly made for export of field notes (however it might still be used to log online with c:geo later on). The online case is described above (log type gets overwritten), however I am not sure if the mentioned log types are still supported for field notes on gc.com?!

**Comment by pstorch** [comment]
Interesting question. Didn't consider offline logging. Just tested:
When you upload a fieldnote with "Needs Maintenance" you get redirected to the old logging page: https://www.geocaching.com/seek/log.aspx?PLogGuid=....

I don't know how long they support this. Fieldnotes are not only coming from c:geo.

**Comment by Lineflyer** [comment]
This probably means, we should keep the "One clik offline log" as it is to 
a) still fully support the field note case (IMHO they have to keep it as all geocaching enabled GPSr will keep using it)
b) make it consistent again to the online logging in c:geo once we also support the changed NM/NA procedure.

This would mean, there is no need to change anything here. Correct?

**Comment by pstorch** [comment]
> This would mean, there is no need to change anything here. Correct?

I think so.

**Comment by Lineflyer** [comment]
Closing then.
