### ISSUE TITLE
Public TB code shown instead of tracking code

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6976]
Since implementation of the new logging page support the trackable list shows the public TB codes (TBxxxx) instead of the secrect codes.

It should show the secret code instead to have the old behaviour and be consistent with GK in the list.

Background:
We implemented to list the secret code years ago as this is the code printed on the TB.
So it helps when selecting the action while logging as you can identify the TB in your hand which you want to place/visit.

**Comment by pstorch** [comment]
I remember now why I changed it to the public TB code: the new cache logging page only allows logging of TBs in the inventory with the public code, not with the secret code.  Strange because on the trackable logging page you need to have the secret code. 
PR with a fix is opened.

**Comment by Lineflyer** [comment]
That sounds a bit like it might be possible to manipulate ;)


Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Peter Storch <notifications@github.com> Datum: 13.04.18  22:38  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Author <author@noreply.github.com> Betreff: Re: [cgeo/cgeo] Public TB code shown instead of tracking code (#6976) 
I remember now why I changed it to the public TB code: the new cache logging page only allows logging of TBs in the inventory with the public code, not with the secret code.  Strange because on the trackable logging page you need to have the secret code.

PR with a fix is opened.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pstorch in #6976: I remember now why I changed it to the public TB code: the new cache logging page only allows logging of TBs in the inventory with the public code, not with the secret code.  Strange because on the trackable logging page you need to have the secret code. \r\nPR with a fix is opened."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/6976#issuecomment-381254582"}}}

**Comment by Lineflyer** [comment]
Confirmed working!
