### ISSUE TITLE
UI design for NM/NA

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6983]
Nice to see the change is in. Testing is still open, however I think the current design needs optimization:

Currently users will see a button labeled  "No Problem" under the log text window.
Not all users will understand the meaning of this button.

Maybe we could make it only 50% of the current width and preceed it by a string: "Report a problem:"

BTW:
I could not test it yet: Is there still the confirmation dialog used when the users selected a problem? That would be desireable to avoid accidental logs.

**Comment by pstorch** [comment]
Umm, no. There is no confirmation dialog.
We have to add one. 

Regarding the design proposal: good idea.

**Comment by Lineflyer** [comment]
We used to have this dialog already once the user tries to send a NM or NA log. It was captioned "Unusual log type" (or similar).
So it needs to be reenabled if the selection other than "No problem".

**Comment by pstorch** [comment]
Found the code for the confirmation dialog. Will add it for "Report Problem", too.

UI Design:

Label + Button in one line is too narrow on my mobile. 
![screenshot_20180423-223533](https://user-images.githubusercontent.com/5598124/39152086-7051d6bc-4747-11e8-8ccd-c93237a04270.png)

Maybe better have two lines, like the password input field?

**Comment by Lineflyer** [comment]
Two lines might indeed be better.
I am also asking myself if it would be good to make it less prominent, i.e. to use the same selector type as we use for selecting the trackable action further down. Its somehow less intrusive (as one does not need it in >90% of logging cases I guess).
What do you think?

**Comment by pstorch** [comment]
This is now the "less prominent" version:

![screenshot_20180424-222719](https://user-images.githubusercontent.com/5598124/39213405-c48ecc38-4811-11e8-8ca9-f45d7e87b6c8.png)

It's definitely better than the first version.

**Comment by Lineflyer** [comment]
Looks really good!!
