### ISSUE TITLE
Lost message log because of executing "Repeat last log" instead of "Save offline"

### ISSUE THREAD

**Issue by Matze2** [cgeo/cgeo#6987]
This is at least the third time that this happened to me:
I create a log in c:geo, but could not finish it. Therefore I wanted to save it offline.
But instead of hitting the "Save offline" menu item I accidentally pressed the neighbour menu item "Repeat last log" which replaced my log irreversibly.

The following options come into my mind:

- Reorder the menu items. Especially items that erase an existing log ("Repeat last log" and "Clear") should be grouped together and moved to the bottom
- Add a confirmation dialog or an Undo toast for these two actions "Repeat last log" and "Clear" if the log text area is not empty

**Comment by Lineflyer** [comment]
I agree that this is not so nice, but I also wondered why I did not stumble upon this problem before.
The reason is, that I leave the log window by pressing back (which also saves the log) instead of using the menu.
So there is kind of a workaround.

**Comment by Matze2** [comment]
If we agree about the option to resolve it I might have a look on it myself.

**Comment by Lineflyer** [comment]
IMHO it would suffice to move the "Repeat last log" menu item to the second last entry above "Clear" as you suggested.

**Comment by Lineflyer** [comment]
@Matze2 Are you working on this? If so, I will set the issue to assigned.

**Comment by Lineflyer** [comment]
@Matze2 Any opinion? Shall we close or would you volunteer to change the menu order?

**Comment by Matze2** [comment]
Sorry, I am very busy at the moment. I will have a look on it but give me some more weeks.
So you can assign it at least.
