### ISSUE TITLE
Offline log not cleared if new NM function is used

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6996]
##### Detailed steps causing the problem:
- Enable quick offline logging in menu
- Log a cache offline as Found
- Later open it againa and select "Offline Log" - Log Visit
- Compose the log and select "Container is damaged"
- Send the log

##### Actual behavior after performing these steps:
- Online log is posted
- Offline log is not deleted

##### Expected behavior after performing these steps:
- Online log is posted
- Offline log is deleted

##### Version of c:geo used:
2018.04.29-NB

##### Is the problem reproducible for you?
Could not test another time yet

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by pstorch** [comment]
Is it the same or related to #6171?

**Comment by Lineflyer** [comment]
Might be. I need to retest this...just wanted to record my findings during vacation :)

**Comment by pstorch** [comment]
I think this will be fixed by #7002 as well. Please retest after merge.

**Comment by Lineflyer** [comment]
Assigned for retest

**Comment by Lineflyer** [comment]
No, this problem is till reproducible with 2018.05.08-NB according to the procedure described above.

**Comment by Lineflyer** [comment]
@pstorch Also reported by beta testers in #7039

**Comment by pstorch** [comment]
I'll have a look
