### ISSUE TITLE
Emptying log does not clear problem selection

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7000]
This is rather a question than a bug report:
When composing a log and also reporting a problem (e.g. Container damaged) and afterwards clearing the log with Menu -> Clear (german: Leeren) it will clear the log text but not the problem selection.

This results in an offline log still being stored when leaving the logging screen afterwards.
It confused me at the beginning (as I just wanted to get rid of the offline log). Should this also clear the problem selection??

**Comment by SammysHP** [comment]
IMHO the status is connected to the log. So yes, it should be cleared as well.

Congrats for #7000. :)
