### ISSUE TITLE
Add an indicator for corrected coordinates in cache details

### ISSUE THREAD

**Issue by Confectrician** [cgeo/cgeo#7004]
Hi to all,

Currently you can only tell that a cache has corrected coordinates (geocaching.com), when there is an waypoint "_original location_" present.
It would be really nice to have an indicator at the caches main view, if the cache coordinate is a corrected one.

Edit:

Screenshot for better understanding
![screenshot_20180503-211821](https://user-images.githubusercontent.com/7161177/39598082-b2e3b2ac-4f17-11e8-98df-52e191544745.png)

**Comment by SammysHP** [comment]
Caches with corrected coordinates already have a little red flag at the bottom right of the icon.

**Comment by Lineflyer** [comment]
I need to doublecheck, but AFAIR the cache icon on the top should show the little red flag in your example if the cache has corrected coords.

**Comment by Lineflyer** [comment]
Addon: There is no overlay icon in the top menu. I could swear, there was one before?!

**Comment by SammysHP** [comment]
Nope, it does not. Indeed, this could be improved.

**Comment by Confectrician** [comment]
Hi @Lineflyer,

I have tested that.
A solved mystery with corrected coordinates has the flag icon in the complete list but has no flag, when i enter the cache to its main view.

My version is 2018.02.05

**Comment by Confectrician** [comment]
Ah sorry there were already new answers and i havent reloaded github meanwhile.

**Comment by okainov** [comment]
Maybe it will be enough just to add some asterisk?
I.e. on the screenshot it could be "Koordinaten*" or something like this - should be easy to implement and visible enough?

**Comment by Confectrician** [comment]
An asterisk seems to bee very small.
I would go for underlined coordinates or something equal.

**Comment by Lineflyer** [comment]
As described above I would even prefer marking the cache icon in the title with the "final flag" as this would be inline with how we visualize the existence of modified coordinates at all other places.

**Comment by moving-bits** [comment]
current status: done as PR 7220, but deferred until the permission request changes are merged

**Comment by moving-bits** [comment]
current status: PR 7220 adapted to targetSDK26, ready to merge
