### ISSUE TITLE
Routing menu not visible for map of waypoint

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#7007]
Have brouter installed. Navigate to a way point of a cache near you. The routing is shown but the menu is missing.

**Comment by Oskar1983** [comment]
If you touch the map and the menu, can you maybe also have a look at #6970?

Thx!

**Comment by SammysHP** [comment]
@Oskar1983
That is absolutely unrelated to this issue.

**Comment by rsudev** [comment]
Fixed by 8b4644d09a93c466873ee1d0fb2437bbe90d3463 as well
