### ISSUE TITLE
GPS switches off in waypoint list and when editing a waypoint

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7014]
##### Detailed steps causing the problem:
- in c:geo change to the waypoint page
- GPS switches off

##### Actual behavior after performing these steps:
- GPS is off, no more position refinement takes place

##### Expected behavior after performing these steps:
- switch GPS on, even when in waypoint list *and* when editing a waypoint, so position calculation does not stop, which will provide better resp. more precise (averaged) position

##### Version of c:geo used:
- 2018.02.05

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2018.02.05
Google Play services: disabled - 12.5.29 (040408-192802242)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (7,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (7,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (7,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (209,0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---

Would be great if this could be fixed.

Thanks a lot in advance!

**Comment by Lineflyer** [comment]
`Low power mode: active`

According to your system information you enabled the engery saving mode in your installation under Menu/Settings/System.
If you disable it, GPS reception should be still turned on while in the waypoint screen.

**Comment by Lineflyer** [comment]
Feel free to reopen if this did not solve your problem.

**Comment by MagpieFourtyTwo** [comment]
Thanks for answering, but, not really - although this applies to the waypoint list, it dos not for editing the waypoint: GPS turns off, even if this option is deactivated.

Moreover about half a year ago GPS stayed active in waypoint list as well as on the editing page, even if energy saving mode is checked - which makes perfect sense, cause how reliable is a position set via "my coordinates" when GPS is off?

Thus switching off GPS esp. while editing a waypoint, would render "Energy saving mode" completely useless.

**Comment by MagpieFourtyTwo** [comment]
BTW: How can I reopen an issue ...?

**Comment by Lineflyer** [comment]
> Thanks for answering, but, not really - although this applies to the waypoint list, it dos not for editing the waypoint: GPS turns off, even if this option is deactivated.

You are right, just tested it.
That also looks a little strange to me, maybe someone else can check if this is done intentional or a bug?

> Moreover about half a year ago GPS stayed active in waypoint list as well as on the editing page, even if energy saving mode is checked - which makes perfect sense, cause how reliable is a position set via "my coordinates" when GPS is off?

That should not be the case (as we did not explicitly change something in the GPS handling during the last year AFAIR) unless there is really a new bug introduced.

**Comment by pstorch** [comment]
This happened since supporting null coordinates and not using the users location as default.
I'll reintroduce the GeoDirHandler into the EditWaypointActivity to keep the GPS active, even though the current location might not be needed.
