### ISSUE TITLE
Can not build and run the app in Android Studio

### ISSUE THREAD

**Issue by dcz-switcher** [cgeo/cgeo#7027]
Hello all,

I just want to run the app on an emulator from Android Studio
I followed the instructions but after 2 hours of searching and tries, I decided to ask for your help.

Best regards

##### Detailed steps causing the problem:
clone git repo
copy / paste keys.xml
remove all Strings from keys.xml

fix main/build.gradle => use "compileSdkVersion 23" instead of "Google Inc.:Google APIs:23"

then build project ...

##### Actual behavior after performing these steps:
failed download : 'https://jitpack.io/com/github/jenzz/undobar/library/1.3/library-1.3.pom
=> Received status code 401 from server: Unauthorized

And
=> can not resolve : com.google.android.maps in GoogleMapActivity.java

##### Expected behavior after performing these steps:
Build and run the app

**Comment by UniQP** [comment]
> fix main/build.gradle => use "compileSdkVersion 23" instead of "Google Inc.:Google APIs:23"

I think that causes the problem, see https://stackoverflow.com/questions/32724484/android-what-is-the-difference-between-compilesdkversion-google-inc-google-a. What happens if you don't do that?

**Comment by dcz-switcher** [comment]
Thanks for your answer.
It's not totally ok, but far better

My issue is now coming from the deprecated component "undobar"

I must have credentials to access https://jitpack.io/com/github/jenzz/undobar/library/1.3/library-1.3.pom :-(


```
Could not resolve com.github.jenzz.undobar:library:1.3.
  Required by:
      project :main
   > Could not resolve com.github.jenzz.undobar:library:1.3.
      > Could not get resource 'https://jitpack.io/com/github/jenzz/undobar/library/1.3/library-1.3.pom'.
         > Could not GET 'https://jitpack.io/com/github/jenzz/undobar/library/1.3/library-1.3.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.github.jenzz.undobar:library:1.3.
      > Could not get resource 'https://jitpack.io/com/github/jenzz/undobar/library/1.3/library-1.3.pom'.
         > Could not GET 'https://jitpack.io/com/github/jenzz/undobar/library/1.3/library-1.3.pom'.
            > Read timed out
```

**Comment by UniQP** [comment]
I cleared my gradle cache and tried to rebuild c:geo and it worked

```
Download https://repo.maven.apache.org/maven2/com/github/jenzz/undobar/library/1.3/library-1.3-api8Release.aar
```

Which git revision (`git rev-parse HEAD`) do you build?
Which gradle version (`./gradlew -version`) do you use?
How do you build c:geo?

**Comment by dcz-switcher** [comment]
I build c:geo from "run" command on Android Studio to build app and deploy to emulator (is it the answer you expected ?)

git rev-parse HEAD
`0c45cd936b73be826b8b5e5ade6da7fd5d70ab06`

./gradlew -version
```
------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Mac OS X 10.13.4 x86_64
```

**Comment by UniQP** [comment]
I can reproduce the problem with Android Studio, but can build c:geo on command line.

Try to start the emulator (e.g. form Android Studio) and to install c:geo by calling `./gradlew installBasicDebug` on command line.

**Comment by dcz-switcher** [comment]
Thanks, it works from the terminal

I can build the application with commands 
`./gradlew installBasicDebug`
or
`./gradlew assembleDebug `

And install the app on the virtual device with
```
cd main/build/outputs/apk/basic/debug
adb install cgeo-debug.apk
```

Maybe we can update documentation ?
I can make a PR if you want

Thanks again for your help

**Comment by SammysHP** [comment]
I do not see anything wrong in the readme.

**Comment by pstorch** [comment]
@SammysHP
> I do not see anything wrong in the readme.

It is not mentioned in the Readme that you have to build the project first on the command line before it can be built in Android Studio. I ran into this problem several times. Also sometimes when dependencies change. 

So I think it would be good to reflect this in the Readme.

**Comment by dcz-switcher** [comment]
For my case, even after build the project from the command line, I can not run the app directly from Android Studio.

I can build the project from Android Studio, but have to deploy it on the emulator from the command line (adb install)

I think it is useful to know it for newbies ;-)

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:transformClassesWithInstantRunForBasicDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for com/google/android/maps/GeoPoint

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
59 actionable tasks: 10 executed, 49 up-to-date
```

**Comment by pstorch** [comment]
Are there any Google libraries missing in Android Studio? I can build and run it from Android Studio just fine.

**Comment by UniQP** [comment]
> For my case, even after build the project from the command line, I can not run the app directly from Android Studio.

@dcz-switcher That seems to be an issue with Android Studio 3.1 [(stackoverflow)](https://stackoverflow.com/questions/49525708/ioexception-failed-to-find-byte-code-when-upgrade-to-android-studio-3-1/49635328#49635328). Disabeling instant run works for me.

**Comment by dcz-switcher** [comment]
@UniQP it works !!!! 
Thanks a lot
