### ISSUE TITLE
Raise of targetSDKversion to 26 required

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7031]
While preparing the beta version 2018.05.28-RC on Google Play I got the following warning (sorry, german only, did not find out how to change the language):
```
Anforderungen an die Ziel-API-Ebene ab August 2018

Warnung:

Deine App ist derzeit auf API-Ebene 22 ausgerichtet, sollte jedoch eine API-Mindestebene von 26 haben. Hierdurch soll sichergestellt werden, dass deine App den neuesten APIs entspricht, Nutzern eine optimale Leistung bietet und sicher ist.

Ab August 2018 müssen neue Apps auf mindestens Android 8.0 (API-Ebene 26) ausgerichtet sein.
Ab November 2018 müssen App-Updates auf Android 8.0 (API-Ebene 26) ausgerichtet sein.

Tipp:

Wir empfehlen dir, die Ziel-API-Ebene deiner App zu ändern. 
```

Short summary: 
The target SDK should be raised to 26. From August 2018 new apps need to target API 26. Updates of existing apps need to target API 26 until November 2018.

**Comment by pstorch** [comment]
August is for new Apps, November for updates to existing Apps.

**Comment by Lineflyer** [comment]
ups...closing as duplicate of #6905 then
