### ISSUE TITLE
NPE in mapsforge v6

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7033]
From Google Play for version 2018.05.28-RC (but also some reports with 2018.02.05):
```
java.lang.NullPointerException: 
 
  at cgeo.geocaching.maps.mapsforge.v6.NewMap$LoadDetails.run (NewMap.java:1492)
```

**Comment by rsudev** [comment]
This is rather a mitigation than a fix, as I was not able to reproduce it.
