### ISSUE TITLE
Support for Mapforge display theme styles

### ISSUE THREAD

**Issue by kyrasantae** [cgeo/cgeo#7035]
With the new Mapforge version, the old (discontinued) "andromaps" themes from [OpenAndroMaps](http://openandromaps.org) are no longer compatible. I am able to install and use the "Elevate 4" theme, but in c:geo, there doesn't seem to be a way to select between the various styles (hiking, city, cycling, etc.). Do you have plans to implement style switching?

**Comment by Lineflyer** [comment]
Yes, at the moment all layers are shown. Selecting the layers would for sure be a valuable improvement.
It is already listed here: #5964
