### ISSUE TITLE
[FEATURE REQUEST] Direct button from overview window to log a visit 

### ISSUE THREAD

**Issue by caco3** [cgeo/cgeo#7036]
One of the most used functionality in c:geo is logging a cache.
How ever this is not directly accessible from a caches overview page (the overlay window you get when clicking onto a cache). One first has to click onto the menu button (3 dots on top right corner), then select "log visit".
I suggest to add a direct access button to this page like the ones already there to refresh and save a cache to a list.

**Comment by Lineflyer** [comment]
IMHO the existing menu path is already rather easily accessible (two clicks) whereas the space for more icons is limited (at least in our current UI).

**Comment by caco3** [comment]
So currently, if a cache is already stored in c:geo, I see the following buttons:
 - update
 - Select list
 - Trash
And I must say I never used the trash button before! Is it really more important and used than writing a log? I strongly doubt this!

I must admit I don't know your UI rules, but I really wish that the trash button could get replaced by the write log button.

I am a programmer myself, so if it is is only for the sake of writing a bull request, I am happy to do so (actually it wouldn't be the first one...)!

**Comment by SammysHP** [comment]
Don't forget that there's also "compass" and "navigate". ;)

**Comment by caco3** [comment]
> Don't forget that there's also "compass" and "navigate". ;)

@SammysHP Hmm, are we speaking about the same buttons? "compass" and "navigate" are in the headings. The buttons mentioned by me are at the bottom, see red circle in screenshot below. IMO there should be space for another button there.

![screenshot_20180530-084110](https://user-images.githubusercontent.com/1783586/40704092-88d5e07c-63e7-11e8-8dae-32d7cbbc8086.png)

**Comment by caco3** [comment]
@SammysHP @Lineflyer OK, this is my proposal:
 - Replace the icon of the "select list" button with a "list icon", since that would make more sense.
 - Add another button using the "pen" icon. It then would directly open the write low window.
 
Optionally, If you guys insist on the UI layout, remove the "trash" button.

All changes to be made to the "Overview Window as well as the "Detail Window".

**Comment by Lineflyer** [comment]
I stay with my opinion, that we should only change this layout if we generally redesign the UI at this point.
For example as proposed in #3932

**Comment by pstorch** [comment]
@caco3 I would mix up these buttons mentioned by you. They are related to the storage and list handling of the geocache. I would not put a log button there.

**Comment by Lineflyer** [comment]
@caco3 Thanks for your proposal and sorry to close here. The feedback and reactions here show, that there is no majority in favor for this enhancement.
