### ISSUE TITLE
[FEATURE REQUEST] Export/share offline logs

### ISSUE THREAD

**Issue by caco3** [cgeo/cgeo#7037]
While caching, I often only add a minor note (if at all) and save it as offline log. The real log then gets written and uploaded at home on my PC (written with a proper keyboard). Also, whenever one has no mobile internet access (eg. in another country and no payable roaming) this is a VERY handy functionality!
Currently there seems to be no way to export/share the list of those offline logs to another device/computer. It would be great if there would be a functionality to export or share a textual list of the caches containing the GC code, log text, log type and log date. One then could easily send it by email or any oft the other (by Android) provided sharing methods.

My suggestion would be to add this functionality into the "recent caches" window menu. There are already entries to export the mentioned notes.

Note: I am aware of the "field notes" and "personal notes", but they do not provide this functionality in an easy way since I can not get a full list of the caches containing a note.

**Comment by SammysHP** [comment]
Field notes contain the GC code, log time, log type and log text. Why does this not work for you?

**Comment by Lineflyer** [comment]
I agree to @SammysHP, the offline log should contain what you require and c:geo also supports direct upload to the website for even easier handling on your PC.

**Comment by caco3** [comment]
@SammysHP Thank you very much for the explanations! Indeed this feature is almost what I was looking for. However it was not obvious to me that "field notes" means the same as the "offline logs". Is it maybe because I use c:geo with a German translation? "Offline logs" actually is labled German with "Offline speichern" (which seems to be a good translation), where as the other one only is called "Field notes". 

Minor feature request: Instead of providing a way to save it as a txt file, also provide a "share with" option. One then could directly insert into an email, telegram, clipboard (which is synced to my Linux PC through KDE Connect) or so.
Note. The "share with" functionality seems already be present in c.geo when using the functionality "forward to" of a cache.

**Comment by Lineflyer** [comment]
Field notes a.k.a "Feldnotizen" is kind of an official naming for standarized offline logs txt files, supported by geocaching website to upload your finds to the website.

I don't know what exactly you want to do with them, but how about directly uploading them to the geocaching website with c:geo. You can afterwards easily edit and send your finds on any machine using the website. (geocaching.com calls it "Drafts")

**Comment by caco3** [comment]
@Lineflyer You are right that I can upload them to geocaching.com directly (which is REALLY useful). But what I will not have in my hands is a list of caches still to submit the final log. AFAIK geocaching.com does not provide such a list (please correct me if I am wrong).

**Comment by Lineflyer** [comment]
Not sure what you mean with "submitting the final log", however if you upload your field notes those logs will not be submitted but just shown as a list of caches to finally edit your log and send it. Pretty much what you mean, isnt it?

**Comment by caco3** [comment]
@Lineflyer Ah, I see, you mean the "Drafts" link on geocaching.com. I never realised its existence before :(

**Comment by SammysHP** [comment]
"Drafts" was previously called "field notes" and was rename only a few years ago. "Field notes" is still used in almost all geocaching apps, Garmin devices and other platforms (like Opencaching).
