### ISSUE TITLE
Waypoints disappearing at different zoom levels.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7042]
I'm using the latest beta release 2018.05.28-RC
I have a cache with an extra waypoint (It's a 'personal-note', a solution to a puzzle cache).
When I zoom out the waypoint disappears from the map even though there are only 7 caches on display (I have the limit set to 14 before waypoints are hidden).

It works as it should if I tick the 'Old mapsforge V3' box in settings.

.##### Detailed steps causing the problem:
- load a cache with extra waypoints.
- view it on the new maps while zooming in/out.

##### Actual behavior after performing these steps:
Extra waypoint disappears as you zoom out.

##### Expected behavior after performing these steps:
Extra waypoint should be visible until the number of caches on display reaches the limit.

##### Version of c:geo used:
2018.05.28-RC

##### Is the problem reproducible for you?
Yes, but it's not consistent. Some waypoints  disappear, some don't

##### Other comments and remarks:
See attached images, the waypoint just above centre belongs to the unknown caches visible in both images.

![screenshot_20180531-132134](https://user-images.githubusercontent.com/7459480/40789087-7d39eea4-64e9-11e8-852e-c90c46d58b9b.png)

![screenshot_20180531-132142](https://user-images.githubusercontent.com/7459480/40789106-85639396-64e9-11e8-89b1-352f9bfbe2c0.png)

**Comment by Lineflyer** [comment]
Thanks for your feedback.

This is related to (or even the same as) #5900.

**Comment by Lineflyer** [comment]
As to new feeedbacks after release I think it is the same as #5900, therefore closing here to have a single issue for this problem
