### ISSUE TITLE
Open c:geo when clicking a  HTML-link containing coordinates

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7052]
From support mail:

It will be really helpful for me, if you implement geo tag intent so c:geo shows in supported apps when I click on <a href="geo:xxxxxx,yyyyyyy"> html tag in browser. Now "open with..." dialog appears with google maps, waze, locus... but not c:geo. 
It could open the (live) map in c:geo and place mark in received position with a direct line from current position (the same as you fill in "Any destinations" page).

**Comment by samueltardieu** [comment]
I am not sure I like this. cgeo is not a general purpose navigation application. What problem would adding this feature solve?

**Comment by Lineflyer** [comment]
Closing as there was no usecase behind and the user did not reply
