### ISSUE TITLE
Force to english not working on Android 8.0+

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7053]
##### Detailed steps causing the problem:
- Activate Menu -> Settings -> Appearance -> Use English
- Restart c:geo

##### Actual behavior after performing these steps:
Menu option is still active, however the UI is still shown using the phone language (in this case: german)

##### Expected behavior after performing these steps:
c:geo should use the english UI

##### Version of c:geo used:
2018.06.06-NB

##### Is the problem reproducible for you?
Yes, since my device got the Oreo update some days ago.
While on Android 7.0 the force to english was working normally.

**Comment by Beetovy** [comment]
Also doesn't work in Androind 9.0.
Is there any quick help for this issue?

**Comment by Lineflyer** [comment]
No, not that we are aware of.
What is the reason you would like to switch to english?

**Comment by Beetovy** [comment]
> No, not that we are aware of.
> What is the reason you would like to switch to english?

I'm using c:geo in English from the begining. So I'm used to have it in English. IMHO it the most readable and undestandable language in aplications like c:geo.

**Comment by bekuno** [comment]
I saw this also when testing on my device:
Device: SM-N950F (greatltexx, samsung)
Android version: 9
c:geo version: 2019.06.06
System language: en (c:geo forced to English)

Did not checked deeper..

**Comment by moving-bits** [comment]
> Is there any quick help for this issue?

I needed to switch to English for testing purposes and experienced the same problem (using Android 9 as well). I ended up temporarily switching the device's preferred language to English.

**Comment by Lineflyer** [comment]
Moved from #7673 to this issue:

@bekuno wrote:

The method resources.updateConfiguration is deprecated at API Level 25.
https://developer.android.com/reference/android/content/res/Resources#updateConfiguration(android.content.res.Configuration,%2520android.util.DisplayMetrics)
Therefore this method call in CgeoApplication.initApplicationLocale() does not work correct anymore from Android 7.1.1 (N+).
There are some solution ideas in StackOverflow, e.g.
https://stackoverflow.com/questions/40221711/android-context-getresources-updateconfiguration-deprecated
https://stackoverflow.com/questions/54774485/android-context-getresources-updateconfiguration-deprecated-how-to-resolve

**Comment by Lineflyer** [comment]
Moved from #7673 to this issue:

@bekuno wrote:
did not work without deactivating the "google play service".
see screenshot:
(headline in german, system language: en)
![Screenshot_20190703-235957_cgeo](https://user-images.githubusercontent.com/32555742/60629250-47489c00-9df5-11e9-98ed-6b94551198fc.jpg)

**Comment by Lineflyer** [comment]
see #7991
