### ISSUE TITLE
Add signature to use as automatic log for visited TBs [Feature Request]

### ISSUE THREAD

**Issue by koppan** [cgeo/cgeo#7054]
##### Detailed steps causing the problem:
c:geo already has this great feature to automatically set all my current TBs to "visible" when I log a cache.
It would be even better when I could maintain a "TB visited signature" (much like the already existing signature for the cache log entry) which is then automatically used as the log for the visited TB. An example signature could e.g. be something like "As companion of <myCacherName> I visited cache [NAME] today".

##### Actual behavior after performing these steps:
When "Visiting TB" option is turned on and I log a cache, all my current TBs are logged to have visited that cache with an empty log.

##### Expected behavior after performing these steps:
When "Visiting TB" option is turned on and I log a cache, all my current TBs are logged to have visited that cache with a log entry as created by the new "TB signature" entry.

##### Version of c:geo used:
2018.02.05

##### Is the problem reproducible for you?
Yes

##### System information:
not applicable

##### Other comments and remarks:
none

**Comment by pstorch** [comment]
c:geo can only provide the functionality which is available on the website. And a logtext for trackable "visited" is not possible there.

**Comment by Lineflyer** [comment]
Exactly. 
I have recently seen one app able to do such thing, but AFAIK even the APi to gc.com would not provide such functionality.

Anyway this request can currently technically not be realized. Sorry.

**Comment by koppan** [comment]
OK that is understandable. Thanks for the fast reply.   Eddie Am 10.06.2018 22:34 schrieb Lars <notifications@github.com>:Exactly.
I have recently seen one app able to do such thing, but AFAIK even the APi to gc.com would not provide such functionality.
Anyway this request can currently technically not be realized. Sorry.
