### ISSUE TITLE
Implement location service which works while screen is off

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#7057]
##### Detailed steps causing the problem:
- Open cache
- Start compass
- Select "start talking"
- Turn off screen

##### Actual behavior after performing these steps:
GPS turns off, phone stops talking

##### Expected behavior after performing these steps:
GPS stays on, phone talks distance to cache

##### Version of c:geo used:
2018.05.28-RC

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: MHA-L29 (MHA-L29, HUAWEI)
Android version: 8.0.0
Android build: MHA-L29 8.0.0.366(C432)
c:geo version: 2018.05.28-RC
Google Play services: enabled - 12.6.85 (040408-197041431)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (37.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (37.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (37.4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (3.1 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---```


##### Other comments and remarks:
This might not be c:geo's bug directly. Andorid 8 + EMUI is known to stop apps when not needed. Maybe we need to start service when talking is on.

**Comment by pstorch** [comment]
Maybe new energy saving options in Android?

**Comment by Lineflyer** [comment]
Interesting.
My device received the Oreo update some days ago.

It still talks while the screen is off, but it seems GPS is disabled.

**Comment by Lineflyer** [comment]
Setting for retest.

**Comment by moving-bits** [comment]
Tested today using Android 7, Samsung A5(2016) device: using compass, activated "start speech", turned off screen => worked flawlessly (GPS as well as text to speech). (Tested over a distance of app. 6 km of cycling)

Maybe depending on more aggressive power saving under newer Android versions?

**Comment by Lineflyer** [comment]
Tested with Android 9, Samsung Galaxy S10. Here the compass stops talking as soon as I switch off the display. I assume either the process is stopped or it has no location, due to Android power management?!

Not sure if and what we can do about that.

**Comment by mucek4** [comment]
Huawie Mate 9 does that for some time. We need to start some sort of activity that will still run when screen is off (e.g. putting icon on taskbar)

**Comment by moving-bits** [comment]
Found this article - can someone having a device with Android 9 try this?

> It's either the more aggressive RAM management in Android 9 or Doze kicking in. RAM management issues wouldn't be easy to resolve unless Essential changes something. Doze, on the other hand... a lot can be done here.
> Easiest thing to try it to tell those apps to ignore battery optimizations.
>    Long press the app from the app drawer (actually, it could be any app... Google really didn't make this the most efficient way to do this)
>    Tap App Info
>    Tap Battery
>    Tap Battery optimization
>    tap Not Optimized at the top (the header)
>    Tap All apps
>    Scroll to the app you want to ignore Doze (battery optimizations)
>    Tap the app, select Don't optimize
> In a nutshell, Doze tries to restrict what apps can do in the background to conserve battery. When the screen is off, Doze kicks in. By ignoring battery optimizations, you're telling the app it's OK to run freely in the background, unrestricted. This could mean worse battery performance, but that may not matter.

(excerpt from https://www.reddit.com/r/essential/comments/9gmy3q/how_to_keep_gps_active_in_background_when_running/)

**Comment by moving-bits** [comment]
Another approach would to implement a service with a notification being displayed, as suggested by @mucek4. See https://stackoverflow.com/questions/52168945/how-to-keep-gps-receiver-location-updates-when-the-app-is-in-background-google (second answer and linked source of a foreground service).

**Comment by Lineflyer** [comment]
Tested the mentioned was to put cgeo to non optimized apps. Works on my Samsung S10, Android 9.

IMHO thats sufficient and I could transfer the info to our FAQ.

**Comment by Jabolio** [comment]
My 2 cents: This issue has been dogging me for a long time.  I have a Galaxy S7 (running Android 8.0), and today I tried putting c:geo in with the non-optimized apps, but the incorrect behaviour persisted.  I also added other GPS-related side apps like "GPS Status" (maybe I should get rid of this?), but I also didn't power-cycle the phone; don't know if I have to.  The compass doesn't stop speaking completely - it speaks periodically, and only updates distance 1/4 of the time when the screen is off (or always, when screen is on).  I also have a Galaxy S4 running Android 5, and the compass/TTS for that still works perfectly.

Other tracking apps I use, like MapMyWalk, don't exhibit this behaviour when the screen is off, i.e., they continue location tracking.  I'll be watching this issue.

**Comment by moving-bits** [comment]
Don't know of any solution for Android 7 yet. For newer Android versions articles request you to implement a foreground service with an active notification window to keep newer Android versions from putting your app into doze mode when the screen is off (which effectively switches off GPS).

But: Implementing a foreground service seems to be an Android O+ specific feature, which requires Compile SDK 28 (we're currently using 24), and this clashes with Google Maps v1, which we still use. So no progress to be expected here until we switch to Google Map v2 API.

**Comment by moving-bits** [comment]
Reminder to the devs, if anyone wants to start implementing a service requesting location in the background: Starting around end of 2020 Google will implement a new policy for this, forbidding background location access without prior approval by Google. For details see those two articles:

https://android-developers.googleblog.com/2020/02/safer-location-access.html
https://support.google.com/googleplay/android-developer/answer/9799150

**Comment by Lineflyer** [comment]
I changed the title of this issue to reflect the generic feature request to implement a location service which enabled to use the talking compass as well as the proximity notification on map also when the screen if off / device is in standby.
This is for sure a bigger task.

**Comment by fm-sys** [comment]
Just some links which might be helpful in the future...

- https://github.com/android/location-samples/tree/master/LocationUpdatesForegroundService
- https://thakkarkomal009.medium.com/update-location-in-background-using-foreground-service-android-7aee9de1a6d6
- https://developer.android.com/guide/components/foreground-services

**Comment by fm-sys** [comment]
> Reminder to the devs, if anyone wants to start implementing a service requesting location in the background: Starting around end of 2020 Google will implement a new policy for this, forbidding background location access without prior approval by Google. 

Background location permission is not necessary for a location **foreground** service, see https://github.com/cgeo/cgeo/issues/10781#issuecomment-852928500 for more details...
