### ISSUE TITLE
TB image tab shows georeferenced images but no action associated

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7060]
##### Detailed steps causing the problem:
- Open TB7FP4D
- Swipe to the images tab
- You will see, the trackable image marked with a small compass rose icon in the lower left corner
- Click/Long click on the picture to invoke the context menu

##### Actual behavior after performing these steps:
There is no long click associated with the image. Short click opens the image in your default image viewer.

##### Expected behavior after performing these steps:
A long click should offer a context menu similar to the context menu shown for georeferenced images on the cache details image tab.
Of course in this case, there is no cache associated with that action, but we could enable the user to transfer the coordinates found in the image to the "Go to..." menu or at least the clipboard.

##### Version of c:geo used:
2018.06.11-RC

##### Is the problem reproducible for you?
Yes, found while creating the users manual :)

**Comment by pstorch** [comment]
Click and Long Click is working for me 🤔

**Comment by Lineflyer** [comment]
Long click is working for you in the mentioned scenario?
AFAICS there is no long click listener here as my device does not react at all.

**Comment by pstorch** [comment]
Yes, both short and long click work for me.

**Comment by pstorch** [comment]
With short click I get the compass, with long click I get to the map of the picture coordinates.

**Comment by Lineflyer** [comment]
Oh well, got it. 
You have to click on the compass symbol but not just anywhere in the picture. Sometimes there is even a feature I wasn't aware of until now.
So we can close this here...I will include the feature in the new manual.

I assume this the same is also supported in geo referenced log pictures of caches?!

**Comment by pstorch** [comment]
Ah, you clicked somewhere on the picture. Glad you found it. Yes, we have some of these "not so obvious" features.
Yes, the log pictures work the same.
