### ISSUE TITLE
Remove RMAPS from navigation menu in case it is depracted

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7061]
While writing the c:geo user guide I stumbled over the navigation method `Rmaps` in our navigation menus. 

Searching for this app I did only find this download source which declares it as depracted (last update 2013):
https://code.google.com/archive/p/robertprojects/downloads

Does anyone know, whether this is still a functioning app or can be removed from c:geo?

**Comment by moving-bits** [comment]
as nobody has reacted since I guess it is indeed deprecated and should be removed

**Comment by fm-sys** [comment]
I've just installed the app. It provides nearly no features and all API keys seem to be ddeprecated and do not longer work. With a clear conscience I think we can remove this app...
