### ISSUE TITLE
Remove NAVIGON from the navigation menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7062]
Navigon does no longer provide mobile-navigation apps and can be removed from the available navigation methods.

**Comment by olpp** [comment]
Navigon users may still use the installed app and load maps in their latest release from Navigon server.
Map and feature updates stopped. App removed from Google Play-store.
I'd not be upset if you leave it in c:geo for some time.

**Comment by samueltardieu** [comment]
You should be able to still use it from cgeo as a generic navigation application ("other external apps") even though we remove it from cgeo's menu. It's just one additional click.
