### ISSUE TITLE
inpossible log "need maintenance" online

### ISSUE THREAD

**Issue by hakuchi** [cgeo/cgeo#7065]
I can not log a cache an NM or NA if I am online(wlan or data connection).

Some time ago I had a lot of options in the first box in the top of the log window.
Now there are only "found", "not found" and "write note".

If I go offline, all the logtypes are available, but if I go back online and will change the text in my NM log, c:geo change the logtype to "found" or "write note".
I can export the offline NM log to a field note and upload this to geocaching, but logging a NM or NA should be available also online as some time ago.

**Comment by hakuchi** [comment]
I have version 2018.06.20-RC1 installed.

I can log NM and NA and all other logtypes on the website if I change to the old logging page. On the new(not so good) logging page are only the "found", "not found" and "write note" logs available and the "report a problem" selection.

Some time I have to log a NM(as a check in my home zone or as a request whether the container s stil on his place), but have just found the cache some time ago. So I have to write also a note to report that the container is missing.

I think there should be a option to chose what version of logging site a user of c:geo will using.
The new site similar to the website, or the old like before in c:geo.
I will prefer the old log site!

**Comment by pstorch** [comment]
OK, so you have the new Beta version which uses the new logging page.
There should be also a "report problem" section in c:geo. Is this missing in your case? 
GS will remove the old log page sooner or later, so c:geo has to switch to the new page as well.

**Comment by hakuchi** [comment]
There is a "report problem" section in c:geo.
But as described above, I need some time the option to select the NM log.
If I use the "report problem" selection, i have to add a additional note to submit the non editable NM log from c:geo.
Actually the geocaching site have the old and the new logging site available, so also c:geo should have the option to select the old logging site.
If GS delete the old page in the future, c:geo can check if then the app also need to change his logging system.

I think that not only for me the new site is a downgrade.

**Comment by SammysHP** [comment]
> Actually the geocaching site have the old and the new logging site available, so also c:geo should have the option to select the old logging site.
> (…)
> I think that not only for me the new site is a downgrade.

Please discuss this with Groundspeak. The old logging page exists only for legacy reasons and should not be used anymore. This was not our decision.

But the UI should be improved so that it automatically translates a "needs maintenance" into a "note + has a problem" log type, what do you think, @pstorch?

**Comment by pstorch** [comment]
> But the UI should be improved so that it automatically translates a "needs maintenance" into a "note + has a problem" log type, what do you think, @pstorch?

I thought it is this way, but obviously not. Yes, this could be improved.

**Comment by Lineflyer** [comment]
I suggest to first wait to get users feedback about the new "Report problem" function to see if there is a demand for having such kind of translation from NM to Note+Standard-NM.
In fact you can also post a note + Report problem="Other" with the new log page.

**Comment by pstorch** [comment]
I guess it is more often a case during the transition phase with converting existing offline logs. It will be less often when the users got to know the new "report problem" section in c:geo. Later on it will only happen if users log offline (I mean completely offline a.k.a. Airplane mode) in the field and use NM and NA from the main LogType selection.
As I write and think about it: maybe the LogTypes NM and NA should be removed from the main LogType selection if it is a GC cache.

**Comment by SammysHP** [comment]
Btw: How is the cache condition handled in field notes? Previously users were able to save a need maintenance offline and export it as field note.

**Comment by Lineflyer** [comment]
That is still the same when it comes to offline log + field note.
If the user logs NM offline first and afterwards re access the log to write it online it will be converted to a note + Report problem (@pstorch Correct me, if I am wrong).

**Comment by pstorch** [comment]
Old offline logs with LogTypes NM or NA are exported to fieldnotes as they are, as NM or NA.
New offline logs with ReportProblemTypes are written as two fieldnotes: the main LogType (e.g. Found It) + the corresponding LogType for the ReportProblemType (NM or NA). Resulting in two Drafts on geocaching.com.
