### ISSUE TITLE
circles option gone with latest release 2018.06.26

### ISSUE THREAD

**Issue by Tabaluga1** [cgeo/cgeo#7066]
##### Detailed steps causing the problem:
open any map with caches on it
normally there was an option to have 161m circles round the caches

##### Actual behavior after performing these steps:
the option is gone

##### Expected behavior after performing these steps:
have the option available

##### Version of c:geo used:

2018.06.26

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
Thanks for your report, however please refer to:
http://www.cgeo.org/faq#5885

#5885
