### ISSUE TITLE
2018.06.26 Not showing all the trackables in my inventory

### ISSUE THREAD

**Issue by SirJ-Oz** [cgeo/cgeo#7068]
##### Detailed steps causing the problem:
- Step 1
Update to version 2018.06.26 (because the App asked me to)
- Step 2
Log a cache

##### Actual behavior after performing these steps:
Only 20 trackables in my inventory of 37 were displayed at the bottom of the logging screen

##### Expected behavior after performing these steps:
All 37 of the trackables should have been displayed at the bottom on the logging screen

##### Version of c:geo used:
2018.06.26

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: Nexus 6P (angler, google)
Android version: 8.1.0
Android build: OPM3.171019.019
c:geo version: 2018.06.26
Google Play services: enabled - 12.8.62 (040400-199405334)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: en_AU
System date format: d/M/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (29.7 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (29.7 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (29.7 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (9.6 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins: contacts
--- End of system information ---
```

##### Other comments and remarks:
I guess to replicate you will need more than 20 trackables in your inventory

**Comment by Lineflyer** [comment]
See duplicate #7067 but I will keep this one open as it contains more details.

**Comment by Lineflyer** [comment]
If you still have more than 20 TB in your inventory, you could help us by opening the geocache logging page in your browser (e.g. https://www.geocaching.com/seek/log.aspx?ID=2511222&lcn=1) and saving the file on your PC (Save as -> HTML only (or similar)).
Also a screenshot would also be helpful from the browser view: Are all items listed on the logging page initially?

You can send the files to support[at]cgeo.org refering to this issue #7068.

**Comment by Lineflyer** [comment]
Additional info was received and forwarded to dev-list. Seems there is a "Show all" option on the logging page if the inventory count is >20, which we need to use to show them all in c:geo.

**Comment by pstorch** [comment]
I'll have a look at the files you've sent.

**Comment by Lineflyer** [comment]
I would say, that 50 should be more than enough for the average user and for our current webapi impmementation.

**Comment by pstorch** [comment]
Ok, let's go for 50.
