### ISSUE TITLE
Not all caches shown on live map

### ISSUE THREAD

**Issue by Divide-By-0** [cgeo/cgeo#7076]
##### Detailed steps causing the problem:
- Use live maps with a large zoom to a region with reasonably high cache density. 

##### Actual behavior after performing these steps:

Only shows average 80% of caches in certain higher cache density regions, such as around GC4GCWT for instance. After saving and zooming in further, more appear after a while. This tends to happen less with tighter zooms.

##### Expected behavior after performing these steps:
All caches display on map pre save.

##### Version of c:geo used:
2018.6.26

##### Is the problem reproducible for you?
Yes/No
Yes, on a second Android phone on the same account.

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```
--- System information ---
Device: SM-G950U1 (dreamqlteue, samsung)
Android version: 8.0.0
Android build: R16NW.G950U1UES3CRE2
c:geo version: 2018.06.26
Google Play services: enabled - 12.6.85 (040408-197041431)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (1.1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1.1 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1.1 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (12.6 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d.M.yyyy
Installed c:geo plugins:  none
--- End of system information ---

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
Are you using OSM / Offline maps?
If so, please retry with Google maps. 

We have a known issue on our new mapsforge implementation, which might cause this.

**Comment by SammysHP** [comment]
If you are talking about the live map with online caches this is expected. geocaching.com does not provide all caches in lower zoom levels as you can also see here: https://www.geocaching.com/map/

**Comment by Lineflyer** [comment]
Closed due to lack of response and advice given in last comment by @SammysHP

**Comment by Divide-By-0** [comment]
Ok, will repost if problem rearises with google maps. I was using offline maps.
