### ISSUE TITLE
no logentries (empty) vs number of logs being 20

### ISSUE THREAD

**Issue by luck428** [cgeo/cgeo#7077]
sorry only a german screenshot

CGEO says loogbokk is empty, despite confirming at the same time there were already 20 logs.
Cannot attach screenshot :(

**Comment by Lineflyer** [comment]
You should be able to attach a screenshot by drag and drop.
Additionally please add your system information (About c:geo - System) and if this problem is reproducible for you or not.

**Comment by luck428** [comment]
Using a script blocker. Only once allowing a special github address it works.. :(
![screenshot_2018-07-04-15-16-15](https://user-images.githubusercontent.com/40830788/42391532-020d2e3e-8150-11e8-9f40-bcec894b6545.png)
System info: Version 2018.02.05
Cache: GC7J320

**Comment by luck428** [comment]
just now went to logs screen and choose "update", still the same result.

**Comment by Lineflyer** [comment]
Strange...two points:
1. You are using an outdated version, please update. That should however not be the reason of this problem.
2. The reason yould probably be, that you are not logged in. Therefore I asked for the system info as shown in About c:geo -> Swipe to System.

Are other caches also affected, or ony the example mentioned?

**Comment by luck428** [comment]
ok sorry, here is the systems info,
I just logged in through my wifi and got the update of the logbook. 
However when i seemingly tried to update with being logged in, i got no message, just the normal sequence of popups showing downloading and building the log.
Is there some "am i online" check missing ?
Tx

**Comment by luck428** [comment]
![screenshot_2018-07-07-12-23-03](https://user-images.githubusercontent.com/40830788/42410275-7a241080-81e7-11e8-9f84-ed565a517fb1.png)
