### ISSUE TITLE
No popup when extracting waypoints

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7080]
##### Detailed steps causing the problem:
- Have some Description with coordinates
- Click Menu - Extract Waypoints

##### Actual behavior after performing these steps:
Waypoints added, no popup appeared

##### Expected behavior after performing these steps:
Popup-toast message should appear "XX waypoints were added".

##### Version of c:geo used:
latest nightly

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
I remember this was already present at some point, but for a long time I don't see it any more...

**Comment by Lineflyer** [comment]
Working normal for me with latest nightly.
Can you doublecheck, name an example GC code you used and post your system information?

**Comment by okainov** [comment]
Oh, indeed, double-checked and googled - found this answer https://stackoverflow.com/questions/14318921/toast-is-not-shown-on-samsung-galaxy-s3-latest-update-4-1-2
And for some reason in Settings I had "Blocked" for c:geo notifications. When I changed it toasts appeared again, so now it looks fine.

Then I would suggest to reformulate this issue to kind of feature request "Inform user that there will be no toasts if notifications are blocked". Probably you could check this value from the app and notify user somehow (on the main screen or additional dialog maybe). Because it was not obvious that I need to go to Notification settings for that...

**Comment by Lineflyer** [comment]
Let me close this one as too special.
The user needs to explicitly block notifications, before the mentioned issue happens. By default it should work normal, and those users intentionally blocking it, should hopefully be aware of what they are doing (and know the consequences).
