### ISSUE TITLE
Select language displayed in c:geo

### ISSUE THREAD

**Issue by Kebap** [cgeo/cgeo#7082]
##### Detailed steps causing the problem:
- Want to change language used for menu, etc. of c:geo
- Open settings, search for languages

##### Actual behavior after performing these steps:
- Find "enforce English" (yes/no)
- For me, English is not enforced, but still used in menus. 
- I want to use other languages to better help translations in Crowdin.

##### Expected behavior after performing these steps:
- Find "select language" (list of all available translations to choose from)
- Select desired language
- C:geo will now use selected language for menu texts, etc.

##### Version of c:geo used:
2018.06.26

##### Is the problem reproducible for you?
Yes

**Comment by SammysHP** [comment]
This would be rarely used. Please change your phone settings.

**Comment by Kebap** [comment]
Unfortunately that is not possible.

I can adjust my phone to English and French and some Asian languages. It is from Canada.

I would like to help translating German and Spanish as well. How can I view c:geo in these languages then?
