### ISSUE TITLE
Online Openstreetmap layer unreadable on high-res devices (mapsforge new)

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#7083]
The update of 2018.06.26 has retired the older mapsforge library, replacing it with what was previously called "maspforge beta". 

There are some new features, some drawbacks and some bugs. 

After the update, showing OSM: Mapnik layer on the map results in a virtually unreadable map. 
Only the major features are distinguishable, but all text is much too small to distinguish on a high-res smartphone screensize.

The following screenshot of my Samsung Galaxy S6 is1440x2560 pixels (the native screen resolution of the device). 
This image is reasonably readable on a 19" desktop monitor, but on a 6.5x11cm screen one would rather need a microscope. 

![screenshot_20180703-195942](https://user-images.githubusercontent.com/3382777/42641310-f503040a-85fc-11e8-87b9-695bf115cd43.png)

Furthermore, there is no way to scale up the image (by default, using a setting for adjustment for high-res displays).

Also, there is no way to zoom in beyond the shown range (in the screenshot). The "+" button is inactive. Using pinch scaling results in blank map:
![screenshot_20180703-195959](https://user-images.githubusercontent.com/3382777/42641415-2f21d5ee-85fd-11e8-887a-37c25440e5ad.png)

By comparison:
- offline OSM data is rendered well, with good readability

**Comment by andrixnet** [comment]
Also, by comparison: 

- Google Maps show marginally better readability, but still far from adequate
- Google Maps allows two higher zoom levels compared to OSM: Mapnik
- Google Satelitte show marginally better readability, but still far from adequate
- Google Satelitte allows more the two higher zoom levels
- OSM offline data allows even more zoom levels

**Comment by Lineflyer** [comment]
I could not test it yet, but is there any difference if you enable the text scaling in Settings - Maps?

**Comment by andrixnet** [comment]
Logically, from the name of the setting, one would deduce that "text scaling" would work on offline vector map, because that has text defined as text and the font can be rendered at different sizes.

However, my tests have produced identical screenshots. 
Both for online bitmap tiles and offline vector map.

Note: "Old Mpasforge V3" = OFF.

**Comment by jelleruben** [comment]
I hope, it is possible in the future. I can in OSM zoom in to  50, 20 and 10 metre.

It is possible in OSM, I saw it in the app "Locus Map Pro"

**Comment by andrixnet** [comment]
I repeat, this problem appears on my Galaxy S6 when using online tiles (pre-rendered bitmap images).

**Comment by Lineflyer** [comment]
Confirmed for "OSM:Mapnik".
I do see this on both mapsforge library versions (i.e. bug is independent of the setting of "Use Mapsforge V3").

**Comment by Adam-Ant** [comment]
Just adding +1 to this issue, also hapens on my Xiaomi Pocophone F1. Online OSM maps have really small text, and totally disappear when pinch zooming in past the 100m scale. Selecting  Old Mapsforge V3 in the settings does seem to fix the grey text issue, it instead snaps back to the maximum zoom level. However the small text doesn't seem to be affected by mapsforge setting.

**Comment by silviopen** [comment]
+1
The same for me on my Xioami Redme Note4. c:geo ver.2019.06.06
Online OSM map have really small text, and the map disappears over the 100m of zoom

![Screenshot1_cgeo](https://user-images.githubusercontent.com/44685300/61169029-23a0f680-a557-11e9-82c7-af4b631c9fce.png)

![Screenshot2_cgeo](https://user-images.githubusercontent.com/44685300/61169031-2b609b00-a557-11e9-8832-e95a166a16bc.png)

**Comment by Lineflyer** [comment]
Following up in #7750
