### ISSUE TITLE
Wear support

### ISSUE THREAD

**Issue by kbudde** [cgeo/cgeo#7086]
Hi,

there are some tickets related to android wear support.
In the past the requests were closed with a link to the companion app https://github.com/cjmoran/cgeo-wear.
Unfortunately the app was discontinued:  cjmoran/cgeo-wear#20, #6515 

My proposal is to add wear support to c:geo itself.
If it is okay for everybody (@Lineflyer, @Bananeweizen , @SammysHP ) I'll start to develop the wear integration.

**Comment by Lineflyer** [comment]
Well, I am not so familiar when it comes to the programming details and the wear app concept and if (in that background) it is better to have it integrated or as a companion app.
However getting back support for Android wear is interesting for me. As I act as a tester most of the time, I can for sure test any wear solution.

So independently whether it is a dedicated app or a seperate addon it would be desireable for me to have it in this repository under open-source license.

**Comment by derchrome** [comment]
If you need some help I can support you if I have some free time.

**Comment by kbudde** [comment]
Ok,
I've expected a bit more feedback from the core team. But it looks like it is interesting for more people. So it is worth to give it a try.

I did some tests outside with current wear solution.
So far I can say:
- Having the distance on the watch is already really nice
- The direction is wrong for me (Huawei Watch 2). But there are compass apps pointing to north
- The power consumption is a problem with current solution.

May I ask everybody interested which watch they own (with specs if known)  and if they can help testing?

BR

**Comment by Lineflyer** [comment]
I would like to help with testing. Also using a Huawei Watch 2.

**Comment by StalenBas** [comment]
I can help testing as well. I have a Ticwatch E:

Processor: MTK MT2601 1.2 Ghz Dual Core
Operating System: Wear OS 1.4; Android 8.0.0
Display: 1.4" inch OLED 400 x 400 pixels
Memory: 4 GB, 512 MB
Battery: 48 Hours Normal Usage, 120 Hours of Standby time
Sensors: Heart rate Monitor, Proximity Sensor, Accelerometer, Gyroscope, E-Compass, GLONASS, GPS

**Comment by rsudev** [comment]
Perhaps there was no feedback, because the topic itself is not really controversial (and I am not familiar with the wear concepts either, so I cannot comment technically currently)
Nevertheless I would appreciate a working wear app (GeoId and distance would be a nice start). The previous one never really worked for me, because Google is not allowed to do much on my phone...
I own an LG G Watch.

**Comment by myzocki** [comment]
If you like, I can test on my "Fossil Q Explorist"

Mobile: Android 8.1.0 (LineageOS 15.1)

Watch: TECH DETAILS
Storage: 4 GB / 512MB
Operating System: Wear OS by Google™ 
Sensors: Light, Accelerometer, Gyroscope, Optical

**Comment by Lineflyer** [comment]
@kbudde Just stumbling upon this issue from last year. Do you have anything testable and are still interested?

**Comment by kbudde** [comment]
@Lineflyer I'm sorry but I cannot provide any good example code.

I've started and got a working demo but I've faced too many issues with the old wear project. 
It is using a very old android version and the results (compass, baterry usage) were far from usable. IMO rewriting the whole project would make sense but I've never tried as I'm to unexperienced in android development

I've found a workaround. Locus Maps already has a working wear integration with navigation and is already integrated in c:geo.

**Comment by moving-bits** [comment]
Regarding distance and GeoID information: #7994 may help, if your wearable can display text notifications from c:geo. This is included in current nightlies, but not yet released.

Works generally, but only reliably as long as c:geo screen is on => needs some enhancements due to the stronger power regulations from Android 8+ (like all our GPS based functions in c:geo do).

**Comment by LeoDJ** [comment]
I can only second this.
Having wear support would be really really great and a big usability improvment during geocaching.
I hope somebody finds the passion to work on that someday.

Sadly I couldn't get the most recent version of cgeo-wear from 2015 to run at all as many things in the Android / Android Wear ecosystem seem to have changed.
