### ISSUE TITLE
(Re)include link to manual.cgeo.org

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7091]
We removed the link to this URL some years ago, as the existing manual was well outdated no longer maintained. It was present AFAIR on the help page and on many screen as a "?" icon on top.

Meanwhile a new user guide has been created and is available under this URL.

We should therefore include the link again at least on the About c:geo / Help page and (maybe) additionally with a main menu icon (Proposal: Second position right of magnifier icon).

**Comment by samueltardieu** [comment]
Note that https://manual.cgeo.org//en/start (with https) displays warnings because of insecure images loaded from your own site (cgeo.d*.eu) using http. Shouldn't those images be hosted on manual.cgeo.org to avoid the warning?

**Comment by Lineflyer** [comment]
This is the case as manual.cgeo.org is acting as reverse proxy at the moment and my site behind does not yet support tsl. 

We should therefore include non-TSL links for now, which we can change after I enabled TSL (probably next month).

**Comment by Lineflyer** [comment]
Update:
I was already able to upgrade my package. Should be end-to-end TSL now. At least I do not see any mixed content warning any longer.

**Comment by Lineflyer** [comment]
@mucek4 You might need to modify the reverse proxy a bit as now http is automatically forwarded to https therefore revealing the hosting URL at the moment.

**Comment by mucek4** [comment]
Done.
http now redirects to https
https with valid certificate serves as reverse https proxy to https://cgeo.d...../

**Comment by Lineflyer** [comment]
Thanks, confirmed working! IMHO we can keep it like that for now.

Maybe we could think about relocating the whole Wiki to your server...anyway for now I am happy I finally found a meaningful usage for my webspace :)

**Comment by rsudev** [comment]
The context sensitive help function was removed with db88f86e0756ea44414a4da9353af36e39d511dc (as far as I could deduce). It redirected to an installed manual app with a topic context. We could introduce something similar linking to the online content.
The globale reference to the online manual was removed with 0a57f812af773733a7bf6b831148fad234e089e2
Reintroducing this would be very little work.

**Comment by Lineflyer** [comment]
> The globale reference to the online manual was removed with 0a57f81
> Reintroducing this would be very little work.

Seems reasonable for the first step.

Regarding the context sensitive help:
I think it is not needed to reintroduce this at all places where it was before, but maybe in main menu and settings actionbar only.
