### ISSUE TITLE
Add language selector to settings

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7093]
Currently there is only one checkbox "Use English" in Settings to force using English instead of system language. It would be nice to have proper selector with all available languages.

Example: I'm Russian, but my system language is English and I'm fine with it, but sometimes it would be useful to change app language (i.e. to test translations or learn local language)

**Comment by Lineflyer** [comment]
I don't know what the Android guidelines recommend for language selection, however I have rarely seen a language selector in any app. 

I could be a useful testing feature, however this can be hidden from the users UI then.

**Comment by okainov** [comment]
There are quite many apps with language selector (Telegram, Instagram, ES file explorer, Firefox), although it may not be visible from the first sight :)
I think having additional logic "is it testing feature, is it enabled" will only overcomplicate stuff, IMO selector instead of currect checkbox will be perfectly fine.

**Comment by okainov** [comment]
@SammysHP then remove existing checkbox as well. 

For me it makes no difference having checkbox with 1 option or having selector with 50 available languages from internals point of view. There are already implemented functions to change language, so why restrict it to English only?

**Comment by SammysHP** [comment]
If you think it is easy, please send us a pull request.

**Comment by Lineflyer** [comment]
I think I will rather open a new issue to remove language forcing completely. The existing feature seems to have stopped working since Android 9 (on my devices at least) and it is fully selectable via the device global settings.

**Comment by Lineflyer** [comment]
See #7991 in combination with #7053

**Comment by okainov** [comment]
Yay, I missed it, but in the current nightly I finally see the selector! Thanks to whoever has implemented it :)
