### ISSUE TITLE
Geocaches and trackables shows up as "do not exist" when connected to WiFi that requires login

### ISSUE THREAD

**Issue by MrKaKisen** [cgeo/cgeo#7097]
##### Detailed steps causing the problem:
- Connect to a WiFi that has a "pop-up" with a login page before actually giving access to the internet
- Try to search for either a trackable or geocache (or update a offline saved geocache)

##### Actual behavior after performing these steps:
A message stating that the geocache / trackable does not exist pops up.

##### Expected behavior after performing these steps:
A notice to the user explaining that a connection to the actual geocaching website could not be established or something like that. The current message may be misleading.

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: ONEPLUS A6003 (OnePlus6, OnePlus)
Android version: 8.1.0
Android build: ONEPLUS A6003_22_180713
c:geo version: 2018.06.26
Google Play services: enabled - 12.8.74 (040400-204998136)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: sv_SE
System date format: y-MM-dd
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (85,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (85,3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (85,3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1,9 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Inloggning OK) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
Suggested solution: Add to error message that it could be due to a bad WiFi connection.

**Comment by Lineflyer** [comment]
Your OS should inform you, if a WiFi requires login. I don't think that this should be handled by c:geo itself.

Normally a login failure will be shown for sure in such case. In your case I assume you already logged in with c:geo (started the session) before connecting to that restricted WiFi.

**Comment by MrKaKisen** [comment]
Yes, that is correct, forgot to mention that, sorry. Maybe it should inform me, but if you exit out from that initial popup (say accidentally), your device will still let you use that wifi even though you're not connected. This is really a minor issue, close it if it's irrelevant :smiley:

**Comment by SammysHP** [comment]
If the gateway simply replaces the content of the request with the login form instead of denying the request there is nothing we can do. This is just really bad behavior (and doesn't work with HSTS and HPKP).

I vote for closing this as won't fix.

**Comment by MrKaKisen** [comment]
Very well then, close it :smiley:

The WiFi in which this occurred for me was the Dublin Airport WiFi. I'm unsure if it's misconfigured or not, but that's what happened for me.

**Comment by SammysHP** [comment]
It is not misconfigured, it is just bad design.

**Comment by MrKaKisen** [comment]
Fair enough :smiley:

Thanks for taking your time looking through my issue!
