### ISSUE TITLE
Search by address no longer working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7098]
##### Detailed steps causing the problem:
- Go to "Search" menu
- Search for a location (e.g. "Munich")

##### Actual behavior after performing these steps:
Toast message: "c:geo could not find coordinates for this location"

##### Expected behavior after performing these steps:
Result returned

##### Version of c:geo used:
2018.06.28 / Current nightly

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Pretty sure, that this is related to the new Google pricing model :(

**Comment by Lomanic** [comment]
I don't reproduce with current release `2018.06.26`.

**Comment by Lineflyer** [comment]
Seems I was tricked by a WiFi blocking part of the traffic. Cant reproduce either.
