### ISSUE TITLE
Geocoding works unreliable

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7099]
##### Detailed steps causing the problem:
- Enable Settings / Appearance / Show Address
- Go to c:geo main screen

##### Actual behavior after performing these steps:
Coordinates are shown on the bottom status bar instead of location name/address

##### Expected behavior after performing these steps:
Show address

##### Version of c:geo used:
2018.06.28 / current Nightly

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Pretty sure, that this is related to the Google pricing model :(
Related to #7098

**Comment by Matze2** [comment]
Cannot reproduce. Address is shown with recent nightly 2018.08.07.

**Comment by mucek4** [comment]
Official Play version, address is shown.

**Comment by Lineflyer** [comment]
Seems I need to look closer why it stopped working for me only.

**Comment by SammysHP** [comment]
@Lineflyer Maybe your IP was blocked due to high amount of requests.

**Comment by Lineflyer** [comment]
Seems I was tricked by a WiFi blocking part of the traffic. Cant reproduce either.

**Comment by Lineflyer** [comment]
Let me reopen this again, as I have just seen, that also on CI the "testGeocoder" keeps failing (Server did not respond). So there is either really a limitation problem or just a general server problem.

Just now its also not working on my installation.

**Comment by Lineflyer** [comment]
It seems to be stable again. So lets close once more. Keep fingers crossed.
