### ISSUE TITLE
send to c:geo does not work in Google Chrome

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#7105]
Send to c:geo in geocache page does not w rk in Google Chrome
Response is " Please Wait" 
no reception of file on android device either

Send to c;geo does work in chart mode
![image](https://user-images.githubusercontent.com/1834022/43887836-389a03a2-9bc0-11e8-8dd4-78ef857f8800.png)

Last version of c:geo installed

**Comment by wizard4u** [comment]
![image](https://user-images.githubusercontent.com/1834022/43891890-c0516a7e-9bca-11e8-9dd7-c1c77cdb90ca.png)

file is downloaded to c:geo device but comment remains Please wait

**Comment by mucek4** [comment]
"Please wait" means it's waiting for a response from server. Can you check what does say in console (Press F12 and click "console". Or network.

**Comment by wizard4u** [comment]
![image](https://user-images.githubusercontent.com/1834022/43894430-4d6c1286-9bd2-11e8-80b1-61e818a89695.png)

**Comment by Lineflyer** [comment]
Just gave it a quick try and for me it opens the "Success" messageby locading a full page (URL: https://send2.cgeo.org/add.html?cache=GCxxxx) instead of the desired inline message.

**Comment by wizard4u** [comment]
Hi, same here and have to register again after restarting chrome

**Comment by Lineflyer** [comment]
No idea whats going on here.
The full page opening instead of the message is for sure a bug.

@wizard4u 
If you need to register after restarting Chrome, this is most probably an issue with your cookie settings (deleted on close).

**Comment by ungust** [comment]
My send2c:geo crashed on me 2 dqays ago. It gave ne the "please wait" box, and ran forever whithout progress. I rebooted my computer thinking that it was my settings got corrupted somehow. Nope. Send2c:geo uninstalled it's self.  Geocaching.com was unaware of the issue. I finally decide  touninstall and reinstall the program with Firefox. I still have the same issue with the wait message. But, I now know that I can get a successful download using the map and chart workaround. It's more cumbersome than going straight in, but it works. It definetly sounds, to me, as if there is a bug in the latest update.

**Comment by Lineflyer** [comment]
Lets move this under the repository, where is belongs to.
Please continue here: https://github.com/cgeo/send2cgeo/issues/54

**Comment by mariansam** [comment]
Temporary solution: https://github.com/mariansam/gc-send2cgeo-success
