### ISSUE TITLE
Multiline text in "donation" link not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7108]
I recently changed the string `about_donation_more` from `Donate\ndevelopment` to `Support c:geo development\nMore info on our website`.

Now the button text is truncated. Seems we need to change the style or shorten the string. I am wondering if the english string worked before with the line break in it.

**Comment by mucek4** [comment]
Before it was in one line. 
![2018-08-10 08 53 31](https://user-images.githubusercontent.com/832407/43943210-fabb7726-9c7a-11e8-854c-66da66586e6d.png)

**Comment by Lineflyer** [comment]
OK, seems the `\n` linebreak never worked.
I think the length of the string is not critical. I will just shorten it to `Support us` for the next release after the current one.
