### ISSUE TITLE
Clean merging of release to master

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7113]
Due to urgent changes needed some commits and merges have been done using the Github UI.
Additionally I merged `release` to `master` some days ago via website using a PR and "Rebase and merge".

I assume this was not the clean way of doing it, so two questions:
1. Can someone clean up my mess ;) and bring `master` back to normal?
   @samueltardieu @rsudev @pstorch 

2. Is there any way to use the Github UI to do a clean merge to `master?
Currently only "Rebase and merge" is available, but there are also options "Allow merge commits" and "Allow squash merging" in the project options, whereas the first one sounds reasonable, doesn't it?

**Comment by samueltardieu** [comment]
What you've done is rewrite commits from one branch to another without recording a merge. You should not ever rebase or squash (both rewrite commits) when merging anything else but external changes. The only sensible option to perform such a merge using the UI would be "Allow merge commits" (as it is a merge between branches).

I will not be able to fix it right now and I'll be leaving very soon, so someone else will probably have to fix this. Just to make sure it will be clear to the person repairing the merge: what you've done a few days ago is merge `release` into `master` or merge `master` into `release`? When was that? (it's hard to say from the commits)

**Comment by rsudev** [comment]
I merge release to master again and resolved the conflicts accordingly. While for merging external changes the current strategy (rebase) is what we want, it doesn't work as we want it when merging release to master. Until now the developers did that locally, I'll check the project settings to see if we can make that work for us. Because if we have the two options available, the 'submitter' than needs to choose always the correct option...

**Comment by samueltardieu** [comment]
Thanks @rsudev. I have started a -NB1 build to check the merge as well as the upgrade of RxJava before leaving for vacation.

**Comment by Lineflyer** [comment]
Thanks @rsudev !!

Regarding:
> Because if we have the two options available, the 'submitter' than needs to choose always the correct option...

I don't think so. This selection is important for merging PRs, so only the team (who is allowed to merge) needs to take care to select the correct option.

**Comment by rsudev** [comment]
@Lineflyer We can definitely just give it a try (you would need to set the appropriate option as I have no access there)

**Comment by SammysHP** [comment]
I've enabled all merge methods for this repo, so make sure to select the right one. ;)

**Comment by rsudev** [comment]
For the moment I guess so.
