### ISSUE TITLE
Routing menu vanishes on changing map file on new mapsforge map

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#7118]
Opening the map (with the new mapsforge map being selected as default, on a list in this case), the routing menu is available (given the necessary preconditions).
After switching to a different map file, the menu is gone.

**Comment by Lineflyer** [comment]
Duplicate of #6281 ?

**Comment by rsudev** [comment]
@Lineflyer Very likely, but a different sequence of actions.
