### ISSUE TITLE
Login failure and 'failure to download required information for cache' error messages displayed since update

### ISSUE THREAD

**Issue by fefealabama** [cgeo/cgeo#7120]
##### Detailed steps causing the problem:
- Step 1 I have signed up to the beta app and updated the app, and now cannot log caches via the app, as i get warning messages saying 'C:Geo is only able to download partial information' or 'C:geo needs information in order to work offline' even when I have full wifi or signal. Logs will save to offline draft though but will not post.
- Step 2 I am not displaying as logged in on the home page of the app, and cannot get it to refresh or lig me in, despite showing me logged in at geocaching.com on the settings of cgeo.
- ...

##### Actual behavior after performing these steps:

as above

##### Version of c:geo used:

BETA - newest update

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
Hi,
please kindly specify the exact version number and include your system information.

**Comment by fefealabama** [comment]
--- System information ---
Device: ONEPLUS A3003 (OnePlus3, OnePlus)
Android version: 8.0.0
Android build: ONEPLUS A3003_16_180719
c:geo version: 2018.08.13
Google Play services: enabled - 12.8.74 (040400-204998136)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (37.5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (37.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (37.4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1.4 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com<http://geocaching.com>: Not logged in (Login failed)
Geocaching.com<http://Geocaching.com> date format: d/M/yyyy
Installed c:geo plugins:  none
--- End of system information ---


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SammysHP** [comment]
You are not using the latest version which is 2018.08.14. Please update and the problem should be solved.
