### ISSUE TITLE
Add possibility to add waypoint by map tap

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7121]
Sometimes it's required to add a waypoint by tapping on the map, not having exact coordinates or heading\distance. It would be useful to have possibility to click on the map for adding new waypoints.

**Comment by Lineflyer** [comment]
AFAIK this is already implemented in the new mapsforge OSM/offline version in c:geo. Only missing for Google maps.

**Comment by okainov** [comment]
Just tried - didn't really find it. How? I tried long tap on the map, short tap, was checking new bullets under "create new WP" activity - nothing...

**Comment by Lineflyer** [comment]
You have to open the map for a cache (because the new WP has to be associated to some object) and then tap on the map to create a new WP.

**Comment by okainov** [comment]
Found it.. it was a bit tricky though
