### ISSUE TITLE
Navigation to cache on the map

### ISSUE THREAD

**Issue by nimirCZ** [cgeo/cgeo#7124]
When navigating the map, there is no red line between my position and the cache.

**Comment by SammysHP** [comment]
Can you please show us the system information from c:geo → about c:geo?

I'm not able to reproduce this issue. Is the line enabled in the map settings (map menu → map preferences)?

**Comment by nimirCZ** [comment]
Oh, my fault. 
I did not notice this option. This had to cause the latest update from which this did not work. I did not see the setting before and did not change anything.
Everything is okay now.
