### ISSUE TITLE
Compass freeze if device has no sensors

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7134]
A user on support mail reported, that on his device the app freezes if he starts the compass.
According to the sysinfo the device has none of the sensors which are needed for compass capabilities.

I first was in doubt if this is true, but according to https://www.gsmarena.com/huawei_y5_prime_(2018)-9209.php it seems to be correct.

What to do in such case? Currently it seems we do not handle the situation correctly.

```
--- System information ---
Device: DRA-L21 (DRA-L21, HUAWEI)
Android version: 8.1.0
Android build: DRA-L21 1.0.0.130(C432)
c:geo version: 2018.08.14
Google Play services: enabled - 12.8.74 (040406-204998136)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (4,8 GB free) internal
User storage c:geo dir: /storage/3937-3131/cgeo (58,3 GB free) external removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (4,8 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (756,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by bjdupuis** [comment]
Check for `FEATURE_SENSOR_COMPASS` from the PackageManager and either remove the compass functionality entirely or leave the button(s) but show a toast if it's absent?

**Comment by SammysHP** [comment]
But it has GPS which can also be used to get the heading while moving.

**Comment by bjdupuis** [comment]
> But it has GPS which can also be used to get the heading while moving.

That seems like it would require a fundamentally different representation in-app than a compass view. The direction you're moving has no bearing (no pun intended) on the direction to the cache relative to the device, which is what the compass view shows.

**Comment by SammysHP** [comment]
This is the way how most GPS receivers worked before smartphones and even on smartphones you can often choose to use only the GPS (available in c:geo via the big button on the compass view).

**Comment by bjdupuis** [comment]
> This is the way how most GPS receivers worked before smartphones and even on smartphones you can often choose to use only the GPS (available in c:geo via the big button on the compass view).

Well, TIL :). 

Looking at the code, it looks like the logic for detecting the sensors is in place so now I'm not quite sure what would be freezing. Sorry for dragging us down a rabbit hole.

**Comment by fm-sys** [comment]
As this issue is over 3 years old, let's close and open a new issue if someone is affected nowadays...

**Comment by Lineflyer** [comment]
Not all people affected by such an issue might contact us.
I don`t see a reason why this issue should be gone (magically by itself), there why should we close it?

Not sure though, if there are still such devices around (and used by geocachers), still the failure is in the code as it seems.

**Comment by fm-sys** [comment]
The problem is that we simply cannot fix this issue, if there is no one who can reproduce it. If there is no magnetic compass implemented, the feature simply cannot work. But users can choose to use the GPS for estimating the direction. Nothing we can improve IMHO.
