### ISSUE TITLE
It is possible to access almost every screen in the app without being logged in

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#7137]
##### Detailed steps causing the problem:
- Freshly install the app
- Open the app and don't enter any credentials. Instead of using the "back arrow" button in the top left corner, use the "back button" of the device.
- You can enter the app normally and even try to log a cache (which results in "Download of data in progress..." error).

##### Actual behavior after performing these steps:
You can see and use almost every view in the app

##### Expected behavior after performing these steps:
You should get a big, fat message that you are not logged in and you shouldn't be able to access any caches or logs.

##### Version of c:geo used:
- 2018.09.12 local dev build

##### Is the problem reproducible for you?
Yes

##### System information:
_Not relevant I think_

**Comment by Lineflyer** [comment]
This is indeed a major issue we have mainly based by the historic original design.

**Comment by rsudev** [comment]
c:geo is to a very large extent designed to work offline as well. And if you so desire, you can use the app without supplying credentials to any geocaching site.
I strongly suggest to keep it like that, but to better react in places, where the log-in status plays a role.
E.g. coudl it be possible to just signal the missing credentials or offline status better and just store the log locally (similar for search/download where applicable).

**Comment by ControlTheBit** [comment]
@rsudev I see. I think it is cool that the app can also work without being logged in or providing any credentials. I first thought it was a bug in the ui flow, but I guess this is also fine. It is still inconsistent though that one cannot leave the login screen when using the "back arrow" in the top left corner, but it works when using the back button of the phone. The app should either allow to skip the login screen normally or prevent it at all. What do you think? :)

**Comment by moving-bits** [comment]
Regarding the "big, fat message that you are not logged in" mentioned in the original issue: This has been implemented meanwhile as a warning message on the mainscreen. Being able to access most parts of the app is intentional, as @rsudev has described, so let's close this issue.
