### ISSUE TITLE
App notification for (saved) caches in the vicinity

### ISSUE THREAD

**Issue by lavolp3** [cgeo/cgeo#7138]
I'm wondering if it isn't possible to create a notification (e.g. phone vibration) if you are close (e.g. 100m) to a (saved) cache. That would give users the possibility to stop for a cache without always having to look at their phone. I'm thinking about bike trips or hiking trips.
I guess kind of a function correlating the current position with gps data of all saved caches would already be sufficient.
Unfortunately I'm not nearly good enough in programming and especially not for Android.

**Comment by Lineflyer** [comment]
A good idea and already covered mainly by the request in #417 and other issues reference from there.
