### ISSUE TITLE
Livemap crashes on small (WQVGA) devices

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#7142]
##### Detailed steps causing the problem:
- Start an emulator with the configuration "3.4 WQVGA" (I additionally used API 16)
- Open the livemap

##### Actual behavior after performing these steps:
App crashes

##### Expected behavior after performing these steps:
Livemap should be open

##### Version of c:geo used:
current master - local build

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: Android SDK built for x86 (google_sdk_x86, generic_x86)
Android version: 4.1.2
Android build: google_sdk_x86-eng 4.1.2 MASTER 3876218 test-keys
c:geo version: 2018.09.22-aff6338 developer build
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: disabled (default state)
System language: en_US
System date format: M/d/yyyy
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (633.2 MB free) internal
User storage c:geo dir: /data/data/cgeo.geocaching (633.2 MB free) internal
Geocache data: /data/data/cgeo.geocaching/GeocacheData (633.2 MB free) internal
Database: /data/data/cgeo.geocaching/databases/data (148.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (No Login information stored)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
Quickfix here: https://github.com/ControlTheBit/cgeo/commits/livemap-wqvga-display-fix
I will create a PR for this if needed 👍

**Comment by SammysHP** [comment]
A stack trace is usually helpful.

**Comment by rsudev** [comment]
While the fix looks logical I think I would investigate a little more to really understand cause and effect here (and possibly report the problem to the mapsforge team)

**Comment by ControlTheBit** [comment]
@SammysHP yes of course. I forgot to add it to the report because it took me so long to get the system info via pastebin from the emulator to my machine...

@rsudev yes, makes sense :)

Here is the stacktrace:

```
09-22 20:44:55.650 2177-2220/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: LayerManager
    java.lang.IllegalArgumentException: scale factor must not < 1 0.75
        at org.mapsforge.core.util.MercatorProjection.getMapSizeWithScaleFactor(MercatorProjection.java:102)
        at org.mapsforge.core.util.MercatorProjection.calculateGroundResolutionWithScaleFactor(MercatorProjection.java:63)
        at org.mapsforge.core.util.MercatorProjection.metersToPixelsWithScaleFactor(MercatorProjection.java:313)
        at cgeo.geocaching.maps.mapsforge.v6.layers.PositionLayer.draw(PositionLayer.java:51)
        at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:94)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:147)
```

**Comment by Lineflyer** [comment]
@rsudev What do you think about this issue? Fix locally or open a report to mapsforge team.

**Comment by Lineflyer** [comment]
@rsudev Do you know if this is still relevant?

**Comment by ControlTheBit** [comment]
I think this is a very rarely occuring issue, since there are almost no phones that have 3.4 WQVGA and run on API level 28 (since you need to have 28 in order to push updates to an app in play store).

From my point of view, we can close this issue, unless you see this issue happening "in the real world" ;-)

**Comment by moving-bits** [comment]
> I think this is a very rarely occuring issue, since there are almost no phones that have 3.4 WQVGA and run on API level 28 (since you need to have 28 in order to push updates to an app in play store).

You don't need API level 28 to run c:geo - we currently support starting from API level 16 (Android 4.4). This is called the "min SDK".

There is a "target SDK" restriction for Play Store, which means an app has to be targeted to (supporting) this API level. This has to be level 28 at least, currently, and will be raised constantly by Google. (And there is also a "compile SDK" API level, which is loosely connected to the two others, and currently set to level 28 for c:geo as well.)

**Comment by Lineflyer** [comment]
> From my point of view, we can close this issue, unless you see this issue happening "in the real world" ;-)

Agree.
