### ISSUE TITLE
Publish notification

### ISSUE THREAD

**Issue by ueen** [cgeo/cgeo#7143]
Select point (homezone) and check for new publishes nearby (every hour/6/12/24 hours) by comparing list of nearby caches to the previous one. Should work as a background service.

**Comment by SammysHP** [comment]
c:geo is a (semi) real-time caching application designed to be used in the field. What you want is a notification for new caches, e.g. the same as provided for free by OpenCaching or in the paid Premium Member subscription by Groundspeak. This is not in the scope of c:geo, so I will close this issue, sorry.

**Comment by ueen** [comment]
Ok, would you be so kind to give me the location of the code where the list of caches around is fetched, so I can do an separate app for myself :)

**Comment by SammysHP** [comment]
https://github.com/cgeo/cgeo/tree/master/main/src/cgeo/geocaching/connector/gc
