### ISSUE TITLE
Support import of GPX 1.1

### ISSUE THREAD

**Issue by little-fish** [cgeo/cgeo#7147]
##### Detailed steps causing the problem:
- Import GPX file. See the attachment.
[GC7BFGC.zip](https://github.com/cgeo/cgeo/files/2430620/GC7BFGC.zip)

##### Actual behavior after performing these steps:
- Only basic information are imported. See the attachment.
![screenshot_2018-09-29-14-08-27-360_cgeo geocaching](https://user-images.githubusercontent.com/3481323/46245638-65f6ae00-c3f1-11e8-8076-57e39f36c610.png)

##### Expected behavior after performing these steps:
- Groundspeak and Gsak data should be imported as well

##### Version of c:geo used:
2018.09.17

Other applications have no problem with that GPX file. Am I missing something here?
Thank you.

**Comment by little-fish** [comment]
Nope, no error during parsing. Result of the import process is "1 caches imported from GC7BFGC.gpx".

**Comment by Lineflyer** [comment]
I can reproduce the problem with the attached file.

@little-fish What is the source of this file?

**Comment by little-fish** [comment]
@Lineflyer [https://github.com/little-fish/gcUnicorn](https://github.com/little-fish/gcUnicorn)

**Comment by Lineflyer** [comment]
@little-fish 
Why not using the 1.0.1 format instead? 
AFAICS from the projects README it can also support that.

**Comment by little-fish** [comment]
@Lineflyer 
For sure I could use 1.0.1 version. I simply visited the GPX exchange format's homepage, grab its latest version, checked that cgeo (and other apps mentioned in the project's readme) is "compatible" with gpx 1.1 (you already have gpx 1.1 in your tests) and went that way. There was simply no reason to use obsolete format.

**Comment by moving-bits** [comment]
Stumbled upon this issue today and did some testing/debugging. Import seems to work normally, but many data elements are not recognized. Only basic information, but no cache details, no logs etc.

Strange thing: If you change `xmlns="http://www.topografix.com/GPX/1/1"` to `xmlns="http://www.topografix.com/GPX/1/0"` without changing anything else, the file gets imported as expected, with all details and logs. Just need to find out yet what's breaking the import here...

**Comment by murggel** [comment]
It seems that the groundspeak and gsak extensions are not wrapped into the "extensions"-tag. 
![image](https://user-images.githubusercontent.com/70113341/109542591-86952780-7ac5-11eb-8efc-947ef8d05049.png)

cgeo expects the information in the extensions for V1.1 under the new extensions-tag. 
So gcUnicorn should add the correct tag as shown in the screenshot:
![image](https://user-images.githubusercontent.com/70113341/109542319-328a4300-7ac5-11eb-9194-fd592fc1b4e7.png)

**Comment by murggel** [comment]
I recognized, that the URL are expected in a new tag for V1.1, so cgeo probably needs some enhancement here, I did not checked that yet...

**Comment by murggel** [comment]
@moving-bits you can assign this to me, I can have a closer look whats missing

**Comment by Lineflyer** [comment]
@murggel Assignment done!

**Comment by murggel** [comment]
I think, it would only be necessary to register the extensions to a second node.
I will give it a try..
