### ISSUE TITLE
Use diffent inputType for GC and Trackable search EditText

### ISSUE THREAD

**Issue by lazydays79** [cgeo/cgeo#7148]
It has always been a PITA to enter gc or trackable codes into the EditText of the search activity.

Just because you have to switch between characters and digits on your screen keyboard, and almost every GC or trackable code consists of both characters and digits.

If you switch the input type from textCapCharacters to textVisiblePassword, you have instantly both characters and digits on your screen keyboard. And gc.com is accepting lower case characters in their search, so nothing will be missed if you don't use cap characters.

textCapCharacters:

![screenshot_1538244934](https://user-images.githubusercontent.com/17769242/46249173-1af68e00-c425-11e8-89ca-540c99abce24.png)

textVisiblePassword:

![screenshot_1538244990](https://user-images.githubusercontent.com/17769242/46249172-1af68e00-c425-11e8-8571-68faec8288c1.png)

I will provide a pull request within the next hour.

Regards,
Michael

**Comment by rsudev** [comment]
Done with 7aff8e5de155af144a76663158365d02df1fb794
