### ISSUE TITLE
Static maps not working

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#7150]
##### Detailed steps causing the problem:
- Enable static map download
- Open cache

##### Actual behavior after performing these steps:
Static maps are not shown.

##### Expected behavior after performing these steps:
Static maps should be shown.

##### Version of c:geo used:
2018.09.30-NB-471d205

##### Other comments and remarks:
Request to Google Maps returns 403.

**Comment by Lineflyer** [comment]
Works normal for me.
AFAIR 403 is returned if your personal quota is exceeded.

**Comment by rsudev** [comment]
Tried as well this morning. I was able to get one static map tile before it went '403'. As I don't use static maps at all normally, that would mean a VERY low personal limit...

**Comment by Lomanic** [comment]
> As I don't use static maps at all normally, that would mean a VERY low personal limit...

I'm in the same boat, I think we are maxing our quota from the single static map requested in the "Details" pane of each geocache.

**Comment by Lineflyer** [comment]
Still working for me, however we have some similar reports on our support mail.

There was some recent discussion about new Google pricing model, where I thought static maps would still be free....mmh.

Does someone know which API version we are using, I found this here:
https://developers.google.com/maps/documentation/maps-static/upgrade

> The Maps Static API v1 API deprecation period has ended. If you are a developer that already has a website using the Maps Static API version 1, these upgrade tips should help you port your current site's functionality to the Maps Static API version 2.

**Comment by Lineflyer** [comment]
According to here:
https://developers.google.com/maps/documentation/maps-static/error-messages

403 is returned when the key used is invalid.
This could have something to do with the google pricing model recently discussed on the developer mailing list.
Although static maps on mobile devices are still free and unlimited, it might be necessary to enable the wallet or migrate the account we are using.

@mucek4 Any information of how to access to account? If I use the google cloud console https://console.cloud.google.com/google/maps-apis/new?project=cgeo-trial I get forwarded to a project called "cgeo-trial", which seems mainly empty.

**Comment by Lineflyer** [comment]
I checked with ADB today and took a look what is returned together with the 403 error.
In fact we get this picture:
![staticmap](https://user-images.githubusercontent.com/949669/47288990-f5f6d480-d5f8-11e8-945c-995b9c5958a8.png)


This refers to https://developers.google.com/maps/documentation/maps-static/error-messages#key

I still don't understand the billing model of Google. As to the information I read some months ago static maps on mobile device should still be free and unlimited. 
So either we have to get them by another way(?) or we would need to setup a billing plan for 0€ bills?

**Comment by Lineflyer** [comment]
After crawling the Google pages I found my mistake:

[SKU: Static Maps](https://developers.google.com/maps/billing/understanding-cost-of-use#static-maps) are no longer free to use. In fact 100.000 maps are free only, which will not be sufficient for c:geo (as it is now limited by API-key not the formerly used daily limit by IP).

The "free static maps" I found earlier are in fact [SKU: Mobile Native Static Maps](https://developers.google.com/maps/billing/understanding-cost-of-use#mobile-static), which are a different thing. As for my understanding these seem to be the "normal" google map tiles?!

This would mean we have to remove static maps from c:geo and could think about to implement storage of some map tiles (without ability of embedding custom markers) instead. 
From the users feedback I learned, that many of them are at least missing the preview map on the cache details page which they use for easy lookup of the cache surroundings.

**Comment by Lineflyer** [comment]
For some reason the static maps are loading again in cgeo today.

**Comment by Lomanic** [comment]
I also can confirm static maps are back in cgeo for me.

**Comment by Lineflyer** [comment]
And gone again (for me).

**Comment by Lineflyer** [comment]
Closing here and opening a new issues for removing Google static maps from our code and implementing an alternative (if available).
