### ISSUE TITLE
open cache only in internal browser

### ISSUE THREAD

**Issue by mapa6** [cgeo/cgeo#7151]
- same problem like in #6572 or #5641 but...
- known solution which is described in FAQ (http://www.cgeo.org/faq.html#open-in-browser) for Android 6 not work for Android 7...
- there is no item “Set Default” and change the setting for “Go to supported URLs” for c:geo

**Comment by SammysHP** [comment]
Can you post a screenshot? My Android 7 phone has that option.

**Comment by mapa6** [comment]
Of course
![screenshot_2018-10-02-17-40-47-615_com miui securitycenter](https://user-images.githubusercontent.com/43787170/46360017-ce03f900-c66a-11e8-99bd-b815d96146c6.png)

**Comment by mapa6** [comment]
![screenshot_2018-10-02-17-40-51-593_com miui securitycenter](https://user-images.githubusercontent.com/43787170/46360138-1fac8380-c66b-11e8-97cf-ab1ca33578ec.png)

**Comment by mapa6** [comment]
2018.09.17

**Comment by mapa6** [comment]
![screenshot_2018-10-02-19-35-40-554_cgeo geocaching](https://user-images.githubusercontent.com/43787170/46366129-aae14580-c67a-11e8-8530-66fcb93eb235.png)

**Comment by mapa6** [comment]
--- System information ---
Device: Redmi Note 4 (mido, xiaomi)
Android version: 7.0
Android build: AL1512-mido-build-20180918164722
c:geo version: 2018.09.17
Google Play services: disabled - 13.2.80 (040408-211705629)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (28.2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (28.2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (28.2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (151.8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by Lineflyer** [comment]
One more reason to get rid of the internal browser sooner than later: #6680

**Comment by Lineflyer** [comment]
Closing here, as there is no new information.
I dont think we can solve this device specific problem.
