### ISSUE TITLE
Incorrect new account registration link for opencaching.pl/nl/ro

### ISSUE THREAD

**Issue by kojoty** [cgeo/cgeo#7154]
There is a small issue with registration at opencaching.pl site - just incorrect link.

##### Detailed steps causing the problem:
Settings -> Services -> Opencaching.pl/nl/ro -> Authorize C:geo -> Create an account

##### Actual behavior after performing these steps:
error page in browser

##### Expected behavior after performing these steps:
proper registration page - now this is:
https://opencaching.pl/UserRegistration

##### Version of c:geo used:
2018.09.17

##### Is the problem reproducible for you?
Yes

Best regards. c:geo is great!

**Comment by bekuno** [comment]
Also for uk
https://opencache.uk/UserRegistration

**Comment by SammysHP** [comment]
That URL is returned from the server. Can you file a bug report against OKAPI?

**Comment by kojoty** [comment]
right - now I see what's going on, sorry for bother you!
