### ISSUE TITLE
Login problems on new login

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7155]
##### Detailed steps causing the problem:
- Start c:geo
- (Re)login with existing user works
- Go to settings and delete gc.com account information (or use fresh install)
- Enter login data

##### Actual behavior after performing these steps:
Login failed - Unknown errorr

##### Expected behavior after performing these steps:
Login works

##### Version of c:geo used:
2018.09.27 and master

##### Is the problem reproducible for you?
Yes, at this moment at least (on two tested devices, accounts)

##### Other comments and remarks:
Also some users on support and FB

**Comment by Lineflyer** [comment]
```
12:27:21.386 Debug cgeo 19513  [OkHttp] 200 (1305 ms) GET https://www.geocaching.com/account/signin (http/1.1)
12:27:21.709 Debug cgeo 19513  [OkHttp] POST https://www.geocaching.com/account/signin
12:27:22.031 Debug cgeo 19513  [OkHttp] 200 (342 ms) POST https://www.geocaching.com/account/signin (http/1.1)
12:27:22.353 Info cgeo 19513  [network--2] Failed to log in Geocaching.com as Lineflyer for some unknown reason
12:27:22.353 Info cgeo 19513  [network--2] Geocaching.com language already set to English
12:27:22.460 Debug cgeo 19513  [OkHttp] GET https://www.geocaching.com/account/signin
12:27:22.782 Debug cgeo 19513  [OkHttp] 200 (336 ms) GET https://www.geocaching.com/account/signin (http/1.1)
12:27:23.212 Debug cgeo 19513  [OkHttp] POST https://www.geocaching.com/account/signin
12:27:23.534 Debug cgeo 19513  [OkHttp] 200 (387 ms) POST https://www.geocaching.com/account/signin (http/1.1)
12:27:23.749 Info cgeo 19513  [network--2] Failed to log in Geocaching.com as Lineflyer for some unknown reason
```

**Comment by Lineflyer** [comment]
Notification raised.

**Comment by Lineflyer** [comment]
If someone is around to take a closer look into it, I would highly appreciate. On the debugging level I do only see it fails although the process as such seems with good outcome.

**Comment by UniQP** [comment]
From geo-* changelog:
```
In gc-login, change:
       Username
To:
       UsernameOrEmail
```

**Comment by Lineflyer** [comment]
Fix from @UniQP confirmed working for me with PM and BM.
Building a release.

@UniQP Thanks for the fast reaction!!! Splendid!

**Comment by Lineflyer** [comment]
@UniQP Are you able to cleanly merge `release` to `master` so that our nightlies are fixed as well. Last time I tried with the website UI it was not so successful.

**Comment by Lineflyer** [comment]
Release checklist:
- [x] Check/Insert correct version name as headline in ```changelog-release.xml```
- [x] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Rename/Create milestones on Github
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to G+ 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
That was a quick one. Keep fingers crossed they don't change again. But now users can enjoy earth cache weekend at least.
