### ISSUE TITLE
'Choose file' in the c:geo internal browser doesn't work

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7158]
A couple of times I've logged a find and forgot to attach an image that I wanted uploaded. 
I tried to add it separately using the c:geo internal browser but the 'Choose file' button doesn't do anything.

##### Detailed steps causing the problem:
- In c:geo, open a cache that you've already logged
- Use  'Open in browser' from the c:geo menu
- choose 'c:geo internal browser'
- scoll down to your log entry and click 'upload image'
- Click the 'Choose file' button on the next page.

##### Actual behavior after performing these steps:
Nothing happens

##### Expected behavior after performing these steps:
Some kind of file-choosing dialogue should appear

##### Version of c:geo used:
2018.10.13

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-G960F (starltexx, samsung)
Android version: 8.0.0
Android build: R16NW.G960FXXS2BRI1
c:geo version: 2018.10.13
Google Play services: enabled - 14.3.66 (040408-213742215)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (19.7 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (19.7 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (19.7 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (25.1 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
This happens on both my Galaxy S9 running android 8.0.0 and my Nexus running 6.0.1
It's difficult to use Chrome to perform the upload as every time you click on a link it switches to c:geo.

**Comment by Lineflyer** [comment]
AFAIR we wanted to drop this internal browser feature and replace it by a webview of the cache details. 
It is most likely not capable to select files with it, same as it will not store login cookies.

So you should better us your normal web browser for such purpose. Maybe some time in future cgeo will also support attaching images to existing logs.
