### ISSUE TITLE
Backup to SD by default

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7160]
Looks like I've just lost all my saved cgeo data for 3 years of caching doing hard reset on my phone. What is the point of having backup  option when it puts backup to the very same phone memory and not to SD card???
Please put all backup to sd  by default

**Comment by Lineflyer** [comment]
Thats a difficult topic.
From my understandingt apps (such as c:geo) are not allowed to write access arbitrary folders of the SD-card but only their assigned app directory. This one gets deleted once the app is deinstalled, therefore its not an option to store the backup there.

Thats why during the last redesign of this functionality we allow additional geocache data to be stored on the SD but files you might want to keep after deinstallation are stored on the internal memory (e.g. backup, GPX exports)

**Comment by okainov** [comment]
I'm not Android expert, but there are apps writing to SD without any problems, such as Geotracker (exports gps tracks and files remain after uninstall),  ES file explorer, and many others. For sure you need permission from the user and sometimes there is this weird dialog "select root path", but still works.
https://developer.android.com/training/data-storage/files#PublicFiles this looks like official up-to-date doc, public files on external storage - that seems suitable here...

**Comment by rsudev** [comment]
Unfortunately is this a part of the documentation, which is able to trip you easily. What the Android Api primarily provides as 'ExternalStorage' is nowadays emulated and part of the built-in device internal storage and not the external SD card. In later Api versions access to the app-private directory on an sd-card is available, but from scanning the documentation it is not clear to me whether this is true for the public directories as well.
I know there are possibilities to access the sd-card on some versions of Android, but until now we were not able to find a feasible way for all Android versions we support.

**Comment by Lineflyer** [comment]
I just wanted to write the same. I remember @pstorch and myself invested quite some time, to understand and interpret the logic the API uses here.
Here is a summary:
https://github.com/cgeo/cgeo/wiki/Disk-usage-structure

However I have to admit that there are apps doing it. When first time using such an app it AFAIR invokes some third party or Android internal app and uses it to get the mounting point of the SD and the persmission to use it. So there is some kind of solution, but I guess its well overdriven to only be able to store a single file.
Our current structure is IMHO pretty straight forward (See link above). Users can easily move the backup from there to whereever they want.
