### ISSUE TITLE
Failing tests on CI

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#7161]
Currently, the Android Geocoder test always fails on CI, e.g. http://ci.cgeo.org/job/cgeo%20pull%20request/1444/testReport/cgeo.geocaching.address/GeocoderTest/testAndroidGeocoder/

In a [comment](https://github.com/cgeo/cgeo/pull/7149#issuecomment-425712144) @rsudev stated that this is due to a request limit but I don't think that's the case. I think we receive the requested address data but it just does not contain the country code anymore.

So we should check whether the country code is missing in general and either remove the country code check or use other test data that contains a country code.

**Comment by UniQP** [comment]
I tested an alternative location and got the same result: The address data contains the street name and the city but not the country code.

**Comment by Lineflyer** [comment]
Seems they just changed it. Lets leave out the country code from the test.

**Comment by UniQP** [comment]
The test passes when I run it locally on the emulator. So I'm not sure what exactly causes the problem.

I will provide an PR that adds an additional null check.

**Comment by UniQP** [comment]
@kumy Since it's a regression, maybe some CI change causes the behavior?

It would also be interesting how the test behaves on other devices.

**Comment by kumy** [comment]
The docker container were up since 3 month
```
IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                      NAMES
cgeo-executor:2.0.0        "/usr/local/bin/star…"   11 months ago       Up 3 months                                                    android-23-2
cgeo-executor:2.0.0        "/usr/local/bin/star…"   11 months ago       Up 3 months                                                    android-23-1
traefik:roquefort-alpine   "/entrypoint.sh --we…"   12 months ago       Up 3 months         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   traefik
```

I've force created them just now…

**Comment by Lineflyer** [comment]
@kumy Seems the website tests on CI are failing since your recreate of the dockers?!

**Comment by Lineflyer** [comment]
```
See <http://ci.cgeo.org/job/website%20tests%20(master)/4295/display/redirect>

------------------------------------------
Started by timer
Building remotely on cgeo-1 (has-emulator) in workspace <http://ci.cgeo.org/job/website%20tests%20(master)/ws/>
Cloning the remote Git repository
Cloning repository git://github.com/cgeo/cgeo.git
 > git init <http://ci.cgeo.org/job/website%20tests%20(master)/ws/> # timeout=10
Fetching upstream changes from git://github.com/cgeo/cgeo.git
 > git --version # timeout=10
 > git fetch --tags --progress git://github.com/cgeo/cgeo.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url git://github.com/cgeo/cgeo.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git://github.com/cgeo/cgeo.git # timeout=10
Pruning obsolete local branches
Fetching upstream changes from git://github.com/cgeo/cgeo.git
 > git fetch --tags --progress git://github.com/cgeo/cgeo.git +refs/heads/*:refs/remotes/origin/* --prune
 > git rev-parse origin/master^{commit} # timeout=10
Checking out Revision d9879ee7726a502a76706dfe089c800084ddfcc3 (origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d9879ee7726a502a76706dfe089c800084ddfcc3
 > git rev-list d9879ee7726a502a76706dfe089c800084ddfcc3 # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
[website tests (master)] $ /bin/sh -xe /tmp/hudson109754074354337307.sh
+ [ -x /home/jenkins/restart-emulator.sh ]
+ /home/jenkins/restart-emulator.sh
/home/jenkins/restart-emulator.sh: line 7: adb: command not found
/home/jenkins/restart-emulator.sh: line 8: adb: command not found
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
IRC notifier plugin: Sending notification to: #cgeo
```

**Comment by kumy** [comment]
Argh, I can check tonight only, sorry for that.

**Comment by kumy** [comment]
New docker image built and containers recreated.

Test jobs:
* http://ci.cgeo.org/job/website%20tests%20(release)/3918/console
* http://ci.cgeo.org/job/website%20tests%20(master)/4299/console
* http://ci.cgeo.org/job/cgeo%20continuous%20integration/2039/

**Comment by kumy** [comment]
`website tests` fixed, but continuous integration failed with a new error:

```
07:31.385  cgeo.geocaching.connector.su.SUParserTest > testCanHandle FAILED
07:31.385      java.lang.ExceptionInInitializerError at SUParserTest.java:34
07:31.385          Caused by: java.lang.NullPointerException at SUParserTest.java:34
```

**Comment by UniQP** [comment]
The error seems to happen during initialization of following static block: https://github.com/cgeo/cgeo/blob/d9879ee7726a502a76706dfe089c800084ddfcc3/main/src/cgeo/geocaching/settings/Settings.java#L105-L108

**Comment by kumy** [comment]
The static settings files in CI may miss the SU key?

On October 23, 2018 9:48:43 PM GMT+02:00, Sebastian Buchwald <notifications@github.com> wrote:
>The error seems to happen during initialization of following static
>block:
>https://github.com/cgeo/cgeo/blob/d9879ee7726a502a76706dfe089c800084ddfcc3/main/src/cgeo/geocaching/settings/Settings.java#L105-L108
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/7161#issuecomment-432393093

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by UniQP** [comment]
The connector has no key, it just checks whether it is enabled.

Is it possible to get the full exception stack trace?

**Comment by kumy** [comment]
> Is it possible to get the full exception stack trace?

All logs are in jenkins.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by UniQP** [comment]
The stack trace in the [log](http://ci.cgeo.org/job/cgeo%20continuous%20integration/2040/testReport/cgeo.geocaching.connector.su/SUParserTest/testCanHandle/) is incomplete:
```
Caused by: java.lang.NullPointerException
	at cgeo.geocaching.settings.Settings.<clinit>(Settings.java:104)
	... 54 more
```

**Comment by kumy** [comment]
@UniQP I've updated the script launched in Jenkins to add the `--stacktrace` option. Command is now:
```
# build everything
# re-added the clean target, since builds fail after upgrading the unmock or java plugin of gradle
# add --stacktrace temporarily for finding the root of deprecated tasks
./gradlew --no-daemon --stacktrace --scan clean testDebug createBasicDebugCoverageReport checkstyle lintBasicDebug -Pandroid.testInstrumentationRunnerArguments.notAnnotation=cgeo.geocaching.test.NotForIntegrationTests
```
Build [`#2041`](http://ci.cgeo.org/job/cgeo%20continuous%20integration/2041/) is on it's way…

**Comment by UniQP** [comment]
Looks like you need `--full-stacktrace`.

**Comment by kumy** [comment]
Let's see how it goes with [build #2042](http://ci.cgeo.org/job/cgeo%20continuous%20integration/2042/)

**Comment by kumy** [comment]
It seems the logs are not really truncated. https://stackoverflow.com/questions/437756/how-do-i-stop-stacktraces-truncating-in-logs

**Comment by UniQP** [comment]
Thanks. I got the wrong error line. The error occurs in the line
https://github.com/cgeo/cgeo/blob/d9879ee7726a502a76706dfe089c800084ddfcc3/main/src/cgeo/geocaching/settings/Settings.java#L104
because `getInstance()` returns `null`.
