### ISSUE TITLE
GCVote permanently down

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7169]
I noticed today that GCVote loading in c:geo is either hanging or the value is missing.

According to GCVote.com website the service is broken and may never return. Lets observe if it comes back or not and eventually remove it from c:geo :(

**Comment by okainov** [comment]
Is there any kind of voting on GC.com\other services? I noticed that rating is implemented only for gc.com via gcvote, which seems super weird for me - why isn't there native voting on OC\gc.com\anywhere? Is gc.su the only service with native rating?

**Comment by SammysHP** [comment]
Read access should be possible again: https://geoclub.de/forum/viewtopic.php?p=1287383#p1287383

**Comment by SammysHP** [comment]
Works again.

**Comment by Lineflyer** [comment]
Great and thanks for the link to more information.


Von Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: SammysHP <notifications@github.com> Datum: 29.10.18  22:12  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Author <author@noreply.github.com> Betreff: Re: [cgeo/cgeo] GCVote permanently down (#7169) 
Works again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SammysHP in #7169: Works again."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/7169#issuecomment-434082025"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cgeo/cgeo/issues/7169#issuecomment-434082025",
"url": "https://github.com/cgeo/cgeo/issues/7169#issuecomment-434082025",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [cgeo/cgeo] GCVote permanently down (#7169)",
"sections": [
{
"text": "",
"activityTitle": "**SammysHP**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SammysHP",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"cgeo/cgeo\",\n\"issueId\": 7169,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/cgeo/cgeo/issues/7169#issuecomment-434082025"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401823297\n}"
}
],
"themeColor": "26292E"
}
]
