### ISSUE TITLE
Unify Codacy and Jenkins code style check

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7175]
Currently both Codacy and Jenkins run some code style checks, however they seem to have somehow different scope. So typical workflow start to be like "Create PR - fix codacy issues - get Jenkins build - fix Jenkins issues". Having in mind that it's all about code style, it would be great to have all the checks in one place instead of checking several tools in different time.

Even better, is to add some Androd Studio inspection profile so everything may be checked locally before pushing

**Comment by rsudev** [comment]
There is a profile for the checkstyle-addin in AndroidStudio in the source tree. It might not cover everything Codacy does (as the checks there are more extensive AFAIK, @Bananeweizen has configured that part IIRC), but should bring you a long way towards a good first version.

**Comment by okainov** [comment]
Looks like there is already possibility to include Checkstyle checks in COdacy https://www.codacy.com/blog/codacy-integrates-with-checkstyle/

So if you enable it, there will be no need to have codestyle in Jenkins at all.

**Comment by rsudev** [comment]
Having the checkstyle settings enabled in codacy in addition is a good idea IMO. Nevertheless would I keep the checks in Jenkins as well, as the feedback from there is more near-time and will stay even if codacy at some point changes its open-source policy.
Even better would it be if the checkstyle checks could be automated in AndroidStudio, so it is not forgotten so easily (I am still spoiled by the smooth integration of these checks in Eclipse).

**Comment by okainov** [comment]
>Having the checkstyle settings enabled in codacy in addition is a good idea IMO.

I think only core team members can change Codacy, so I cannot do anything but suggest here.

>Even better would it be if the checkstyle checks could be automated in AndroidStudio, so it is not forgotten so easily (I am still spoiled by the smooth integration of these checks in Eclipse).

It is, that's what I did after your first comment above. Also great thing that it follows import order as well so automated "Optimize imports" work with Checkstyle rules (that's what I did in my PR).
However it's not directly straightforward so I (or someone else) may want to update README with steps how to set up AS inspections based on Checkstyle. In short, one needs to install plugin for AS and then select to use checkstyle.xml from the project tree.

**Comment by rsudev** [comment]
That is also my conclusion...
Strange, as codacy didn't remark on the issues that were found by Jenkins (and my local checkstyle check afterwards as well)

**Comment by okainov** [comment]
I'm not really sure, but at least Codacy triggers not always, maybe there are still some settings to tune.... See #7233

**Comment by Lineflyer** [comment]
Seems to work reliable IMHO.
