### ISSUE TITLE
Add keys for geocaching.su to the CI server configuration

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#7176]
For the new geocaching.su API implementation, oauth-keys are required. They were sent to the developer group and need to be included into the CI server conf (Thanks to @kumy for volunteering)

**Comment by kumy** [comment]
Thanks for opening the issue. I can work on it only starting on Monday, sorry.

**Comment by kumy** [comment]
New keys deployed in our `private.properties` files.

**Comment by rsudev** [comment]
Thanks!
