### ISSUE TITLE
Replace Undobar by Snackbar

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#7179]
The Undobar library is deprecated and should be replaced by [Snackbar](https://developer.android.com/reference/android/support/design/widget/Snackbar).

In 31e08ed80628d56717ae9a4957f5370b104e1bf4 @Bananeweizen already attempted to replace Undobar by Snackbar, but reverted the commit afterwards.
@Bananeweizen Do you remember why?

I rebased 31e08ed80628d56717ae9a4957f5370b104e1bf4 to current master and pushed it as a branch: https://github.com/UniQP/cgeo/tree/snackbar . That might be a good starting point to work on this issue.

**Comment by Lineflyer** [comment]
I remember something like that the snackbar turned out to be incompatible to one of the lower API versions we used to support at that time. But that would have been documented in some issue before rollback...so I might be totally wrong.

@Bananeweizen might be the only one knowing.

**Comment by Bananeweizen** [comment]
I vaguely remember it breaking the selfmade actionbar that we have/had somewhere in the maps activity or so?

**Comment by rsudev** [comment]
Hmmm, even though we don't have undo in that activity? Perhaps worth another try now since the new mapsforge is the default, where we now have an up-to-date base activity.
