### ISSUE TITLE
Cache voting: refactor to enable different voting implementations

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7182]
Somehow related to #3787.

Currently voting is very hardcoded to GCVote only. Suggestion would be to refactor it and to extract IVotable interface to make it possible to have different implementation for different services (as mentioned in #3787, there is own voting for gc.pl; also there is own voting for geocaching.su)

**Comment by SammysHP** [comment]
As per request: A new interface should be abstract enough to allow different forms of voting, like multiple scales (number of stars, thumbs up/down, whole numbers or different fractions) or multiple voting categories for the same cache, also parallel usage of different voting platforms (GC-Vote, geocaching platform specific voting).
