### ISSUE TITLE
Favorite: refactor to enable different services implementations

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7183]
Currently favorites logic is hardcored for gc.com only. It would be great to refactor it to extract interface like IFavoritable to be able to implement it for other services supporting favorites.

Similar to #7182

**Comment by SammysHP** [comment]
I thought it works already for OpenCaching.

**Comment by okainov** [comment]
From the code it looks like hardcode now. `addToFavorites` is not in any interface but implemented directly in `GCConnector` and `GCParser`, visibility of UI option explicitly depends on `isGCPremiumMember`

**Comment by SammysHP** [comment]
You're right, see #3879.
