### ISSUE TITLE
README.md unclear to newbie about API keys

### ISSUE THREAD

**Issue by DThiebaud** [cgeo/cgeo#7192]
README.me in the current master branch was unclear to me in the API keys section. Following are suggested lines to be added to the bottom of the section to clarify it for a newbie. How do I open a pull request?

For each key, replace the value starting with @ and ending with @ (inclusive) with the key. If a key is missing, remove the value and the leading and trailing @). For example, for the Google Maps v1 key, if the value of the key is "key-value", change the line:

    <string name="maps_api_key" translatable="false">@maps.api.key@</string>
to

    <string name="maps_api_key" translatable="false">key-value</string>

If the key is mising, change the line to:

   <string name="maps_api_key" translatable="false"></string>

**Comment by Lineflyer** [comment]
What is the final conclusion of this. Should we include this in our README.md or not?

**Comment by rsudev** [comment]
I had the same thoughts as SammysHP, that the keys.xml was filled from the template through the private.properties.
As I had such a filke for years, I also didn't notice that it broke.
IMO, re-instating (and documenting) that would be the preferred solution.
The private.properties approach has the advantage, that you can keep your keys stored in a file which is not in danger of getting committed and don't need to fiddle with copy/paste into the keys.xml manually.

**Comment by bekuno** [comment]
In the template are some rows with key.*= (e.g. key.store=key.keystore).
It is used in build.gradle.
Do we need a information in README.md how to configure this or is this somewhere other defined?

**Comment by Korb** [comment]
I recently installed the c:geo app via [F-Droid](https://f-droid.org/packages/com.ylightmusic.app/), and just today saw the following entry in the README.md:

> For the full usability of c:geo you need some API keys for Google Maps (...). You can leave all entries in the configuration empty, but Google Maps (...) will not work.

I don't understand why I need to get an API key at a time when Google Maps and Google Satellites are already properly displayed in my c:geo application out of the box? Perhaps the README.md file is outdated, or you need to add a brief explanation to it, how exactly the functionality of Google Maps in the "out of the box" version differs from the functionality of c:geo with the Google API key connected.

I read #2222 and #10375 threads and didn't find the answer to my question.

> ### System information
> 
> c:geo version: 2022.12.21
> 
> Device:
> -------
> - Device type: V2153 (V2154_RU, vivo)
> - Available processors: 8
> - Android version: 13
> - Android build: TP1A.220624.014 release-keys
> - Screen resolution: 1080x2324px (436x938dp)
> - Pixel density: 2.475
> - System font scale: 1.0 / used scale: 1.0
> - Sailfish OS detected: false
> - Google Play services: enabled - 22.49.55 (190400-499376822)
> 
> Sensor and location:
> -------
> - Low power mode: inactive
> - Compass capabilities: yes
> - Rotation vector sensor: present
> - Orientation sensor: present
> - Magnetometer & Accelerometer sensor: present
> - Direction sensor used: rotation vector
> 
> Program settings:
> -------
> - Settings: v9, Count:88
> - Set language: ru_RU (system default)
> - System date format: dd.MM.y
> - Time zone: GMT+03:00
> - Debug mode active: no
> - Last backup: never
> - Routing mode: Walk
> - Live map mode: true
> - OSM multi-threading: false / threads: 1
> - Map: Google: спутник
>   - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleSatelliteSource
>   - Atts: none
>   - Theme: none
> 
> Filters:
> -------
> - Hide waypoints: parking 
> - LIVE: Нет ([:inconclusive=false:advanced=false])
> - OFFLINE: Нет ([:inconclusive=false:advanced=false])
> 
> Stored Filters (#0):
> 
> Services:
> -------
> - Geocaching sites enabled:
>    geocaching.com: Logged in (Вход ОК) / BASIC
>    Geocaching.su: Logged in (Вход ОК)
> - Geocaching.com date format: M/d/yyyy
> - Geocaching.com website language: en-US
> - Last successful login on geocaching.com: 2023-01-08 08-52
> - Routing: internal / BRouter installed: false
> - Installed c:geo plugins:  none
> 
> Permissions & paths:
> -------
> - Fine location permission: granted
> - Write external storage permission: granted
> - System internal c:geo dir: /data/user/0/cgeo.geocaching (84,3 GB free) v3 internal isDir(7 entries)
> - Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (84,3 GB free) v3 internal isDir(7 entries)
> - Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (84,1 GB free) v3 external non-removable isDir(11 entries)
> - Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (84,3 GB free) v3 internal isDir(0 entries)
> - Public Folders: #12
>   - BASE: SD-карта/Maps/CGeo (User-Defined)[SD-карта/Maps/CGeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo, Av:true, files:>=11, dirs:>=9, totalFileSize:>=3,3 GB, free space: 48,3 GB, files on device: 0)
>   - OFFLINE_MAPS: SD-карта/Maps/CGeo/maps (Default)[SD-карта/Maps/CGeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Fmaps, Av:true, files:11, dirs:2, totalFileSize:3,3 GB, free space: 48,3 GB, files on device: 0)
>   - OFFLINE_MAP_THEMES: SD-карта/Maps/CGeo/maps/_themes (Default)[SD-карта/Maps/CGeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Fmaps%2F_themes, Av:true, files:4, dirs:0, totalFileSize:848,5 KB, free space: 48,3 GB, files on device: 0)
>   - OFFLINE_MAP_SHADING: SD-карта/Maps/CGeo/maps/_hgt (Default)[SD-карта/Maps/CGeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 48,3 GB, files on device: 0)
>   - LOGFILES: SD-карта/Maps/CGeo/logfiles (Default)[SD-карта/Maps/CGeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 48,3 GB, files on device: 0)
>   - GPX: SD-карта/Maps/CGeo/gpx (Default)[SD-карта/Maps/CGeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 48,3 GB, files on device: 0)
>   - BACKUP: SD-карта/Maps/CGeo/backup (Default)[SD-карта/Maps/CGeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 48,3 GB, files on device: 0)
>   - FIELD_NOTES: SD-карта/Maps/CGeo/field-notes (Default)[SD-карта/Maps/CGeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 48,3 GB, files on device: 0)
>   - SPOILER_IMAGES: SD-карта/Maps/CGeo/GeocachePhotos (Default)[SD-карта/Maps/CGeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 48,3 GB, files on device: 0)
>   - ROUTING_BASE: SD-карта/Maps/CGeo/routing (Default)[SD-карта/Maps/CGeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Frouting, Av:true, files:8, dirs:1, totalFileSize:13,9 MB, free space: 48,3 GB, files on device: 0)
>   - ROUTING_TILES: SD-карта/Maps/CGeo/routing/segments4 (Default)[SD-карта/Maps/CGeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo/document/9FC5-1A0A%3AMaps%2FCGeo%2Frouting%2Fsegments4, Av:true, files:1, dirs:0, totalFileSize:13,8 MB, free space: 48,3 GB, files on device: 0)
>   - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 84,3 GB, files on device: -1)
> - Map render theme path: 
> - PersistedDocumentUris: #1
> - UNUSED_TRACK: null
> - Persisted Uri Permissions: #1
>   - content://com.android.externalstorage.documents/tree/9FC5-1A0A%3AMaps%2FCGeo (7 янв., 10:48):RW
> - Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:508,0 KB) on system internal storage
> 
> --- End of system information ---

**Comment by moving-bits** [comment]
@Korb 
Configuring API keys in the source code is only necessary when developing for c:geo, not as a user of the app.
