### ISSUE TITLE
Raise Target SDK to 26 for contacts plugin (or reintegrate into main app)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7193]
Hello Google Play Developer, 
In October, we announced updates to our Permissions policy that will limit which apps are allowed to request Call Log and SMS permissions. This policy will impact one or more of your apps. 
Only an app that has been selected as a user's default app for making calls or text messages, or whose core functionality is approved for one of the exception use cases, will be able to request access to Call Log or SMS permissions. 
Action required 
Below, we've listed apps from your catalog which do not meet the requirements for permission requests. Please remove any disallowed or unused permissions from your app's manifest (specified below), migrate to an alternative implementation (e.g. SMS Retriever API for most cases of OTP verification), or evaluate if your app qualifies for an exception. 
Next steps

Read through the Permissions policy and the Play Console Help Center article, which describes intended uses, exceptions, invalid uses, and alternative implementation options for usage of Call Log or SMS permissions.

Update your app or submit a Permissions Declaration Form.

Option 1) If your app does not require access to Call Log or SMS permissions: Make appropriate changes to your app by removing the specified permissions from your app's manifest or migrating to an available alternative implementation by January 9, 2019. 

Option 2) If your app is a default handler or you believe your app qualifies for an exception: Please submit a request via the Permissions Declaration Form. You do not need to have implemented APK changes in order to submit a form. Declaration Forms received by January 9, 2019 may be eligible for additional time to make changes to bring their app(s) into compliance. If you have recently submitted a Permissions Declaration Form, we are in the process of reviewing your information and will respond to your application.

Make sure that your app is otherwise compliant with all other Developer Program Policies to prevent your app from being removed.

Alternatively, you can choose to unpublish the app. 
Our Developer Program Policies are designed to provide a safe and secure experience for our users while also giving developers the tools they need to succeed. That is why we will remove apps that violate our policies. In cases of repeated or serious violations of our policies, we may also terminate your developer account and any related developer accounts. 
We appreciate your willingness to partner with us as we make these improvements to better protect users. 
Affected apps 
Affected apps and permissions are listed below, up to 20; if you have additional apps, please ensure that they are also compliant with the Permissions policy. 

cgeo.contacts READ_CALL_LOG

**Comment by samueltardieu** [comment]
Now that cgeo will have to request permissions as needed, the contacts plugin could be reintegrated in cgeo and removed from the store.

**Comment by SammysHP** [comment]
But that is a different issue. READ_CALL_LOG must not be used anymore.

**Comment by samueltardieu** [comment]
Sure. So an alternative way must be found. But it would be a waste of time to code an alternative in the plugin application instead of reintegrating the functionalities in the main app.

**Comment by Lineflyer** [comment]
Found it:
> READ_CALL_LOG
> Note: If your app uses the READ_CONTACTS permission and both your minSdkVersion and targetSdkVersion values are set to 15 or lower, the system implicitly grants your app this permission. If you don't need this permission, be sure your targetSdkVersion is 16 or higher.

So here we need to raise target SDK also here. 16 will not be sufficient as (as also valid for the main app) update to Google Play need to target API 26 minimum.

**Comment by Lineflyer** [comment]
We have been reminded by Google meanwhile, that the deadline has passed regarding this topic.

I suggest to depublish to app for now to avoid further consequences until we have a solution.

Any idea how much effort it is for the plugin to bring it to targetSDK 26?  Do we have to introduce an UI or would it just work out to raise it and the user will get the permission request the first time he tries to use the function after install?

I volunteer to test the behaviour if someone raises the target and provides a test APK.

**Comment by Lineflyer** [comment]
Just tried to create a PR with just the modified targetSDK to take a look at the CI build result but it seems it is not contained in `AndroidManifest.xml` but only in `build.gradle`. So there is the end of my knowledge of the build tools ;)

**Comment by rsudev** [comment]
Gave it a quick shot in PR #7263
It builds on my machine, but I am not sure if we currently have a Jenkins job that can build this.

**Comment by Lineflyer** [comment]
Thanks, but seems we do not have any build on Jenkins for that plugin...although IMHO we used to had one.
Can you provide the resulting APK of your build for me to test?

**Comment by rsudev** [comment]
I have created a quick new Jenkins job to build cgeo-contacts from any branch (versioning currently unclear). Find the output under http://ci.cgeo.org/job/cgeo-contacts%20release/3/

**Comment by Lineflyer** [comment]
Versioning seems to be ok for upgrade as version 1.6 was never live, currently 1.5 is live.

I upgraded my install with the APK from CI and removed the permission afterwards.

Now it simply returns the "no match found" dialog but does not ask for permission.
Still need to test a fresh install.

**Comment by Lineflyer** [comment]
> As I just raised the target sdk it is no wonder that it doesn't ask for permissions :)

Oh, I thought that Android would present this dialog automatically on first time any app tries to use a method which requires a certain permission (and the app only needs to handle the failure case (no permission granted)), but it seems its not that easy?!

The current behaviour implies:
For those, who currently have the plugin installed these update is meaningless. New users could install it but need to grant the permission manually (which they do not know, that it is mandatory).
When we depublish it, we wont get in trouble with Google and existing users can still keep it installed (just not reinstall it)....seems depublish for now is the best way unless someone can implement the permission check on short term.

**Comment by Lineflyer** [comment]
Add on FYI: We currently have approx. 7400 installations on active devices.

**Comment by Lineflyer** [comment]
Update:
I depublished the contacts plugin on Google Play.

This means:
- It can no longer be installed from Google Play
- Existing installation will remain functional on users devices until they might deinstall
- Due to meanwhile changed general minimum requirements a new publication will only be possible if we target SDK 26 or higher

**Comment by bekuno** [comment]
@rsudev How do I start the jenkins job for a PR?

**Comment by moving-bits** [comment]
@bekuno: You find the Jenkins Github commands here: https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin

In this case, add a new comment with only the words "retest this please".

**Comment by Lineflyer** [comment]
@bekuno I have only recently rememberd, that there was a related commit. Does that mean we could also republish the plugin?

**Comment by bekuno** [comment]
@Lineflyer unfortunately not. We need the android.permission.READ_CONTACTS. This has to be implemented for runtime use. I plan to work on it, if I find some time.
At this moment I don't know if it is better to let them a separate addon or to integrate in the main app.

**Comment by Lineflyer** [comment]
@rsudev 
Thanks for configuring the CI job for building the contacts plugin from any branch. I am wondering, why it builds an unsigned version only?
@bekuno How come that it generates an (obviously) signed version when you use that job to build from your branch?

**Comment by bekuno** [comment]
> @rsudev
> Thanks for configuring the CI job for building the contacts plugin from any branch. I am wondering, why it builds an unsigned version only?
> @bekuno How come that it generates an (obviously) signed version when you use that job to build from your branch?

@Lineflyer 
The build handling is defined in the cgeo-contacts\build.gradle .
Therefore this should work on master in the same way as on the PR-branch.
