### ISSUE TITLE
FR: Support "export to GPSmap66" via Wifi/BT

### ISSUE THREAD

**Issue by Adorfer** [cgeo/cgeo#7198]
I am totally not familiar about the protocols used by the new devices. 
feeding data from c:geo towards the gpsmap would make c:geo the integrator of geocaching/opencaching and other platforms, in order to get this data onto the gpsmap without the need of GSAK and it's garminexport-macro. 

(if funding would help to get resources for this, i would be willing to give some € and initiate a GoFundMe or similar)

**Comment by SammysHP** [comment]
There is no direct possibility, but you can try https://play.google.com/store/apps/details?id=org.surfsite.gexporter

**Comment by Lineflyer** [comment]
@Adorfer Can you provide a link as to wich tool you are refering to with "gpsmap". I found at least three different with that name.

**Comment by SammysHP** [comment]
He refers to the Garmin GPSmap 66 series.

**Comment by Lineflyer** [comment]
OK, I don't think will be a solution from the c:geo side for this request, IMHO it is very special.

I do not know this device, but if it accepts GPX sent via BT, it should also work to export such GPX from c:geo and share it. Or not?

**Comment by SammysHP** [comment]
> but if it accepts GPX sent via BT

It doesn't, it requires a receiving app on the device. But the tool linked above accepts GPX files and transfers them to the partner app on the device.

**Comment by Lineflyer** [comment]
Then tools like this look like a good solution. I don't think c:geo will ever support proprietary communication towards specific devices.
