### ISSUE TITLE
Map reloading when popup opens

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7200]
##### Detailed steps causing the problem:
- Map a list of caches on mapsforge offline map (new libraries)
- Click on a cache to open the popup
- Close the popup
- Repeat the popup opening/closing

##### Actual behavior after performing these steps:
After some tries (sometimes already on the first try) the map tiles are reloading when trying to open a popup. In fact it looks like the whole activity is reset/restartet as also the title bars vanish for a moment.

This behavior seems to be caused by a recent change on `master` as it was working normal with a build from approx. 2 weeks ago.

##### Expected behavior after performing these steps:
No reload/restart

##### Version of c:geo used:
2018.11.25-NB

##### Is the problem reproducible for you?
Yes, see above

##### System information:
Samsung S7, Android 8

##### Other comments and remarks:
@rsudev Might be related to the new theme selector as this change came in recently?

**Comment by rsudev** [comment]
Seems so, even though I have no idea how. In the change, there is a place where the activity is restarted, but only if some preference was changed. I'll have a look whether I can reproduce it.
