### ISSUE TITLE
Pictures can't be loaded anymore 

### ISSUE THREAD

**Issue by winkamol** [cgeo/cgeo#7207]
##### Detailed steps causing the problem:
Loading a cache and swiping to the pictures site makes Cgeo load the pictures but every picture is the broken picture with the red cross. 
I didn't change a setting since it worked before I am not sure what to do. 

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: SM-G955F (dream2ltexx, samsung)
Android version: 8.0.0
Android build: R16NW.G955FXXU4CRK1
c:geo version: 2018.10.13
Google Play services: enabled - 14.7.99 (040400-223214910)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: yes
System internal c:geo dir: /data/user/0/cgeo.geocaching (14,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (14,0 GB free) external non-removable
Geocache data: /storage/FE5A-BEE6/Android/data/cgeo.geocaching/files/GeocacheData (14,1 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (801,8 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by UniQP** [comment]
Works for me with the latest nightly.

@winkamol Can you provide a GC Code that is not working correctly for you?

**Comment by winkamol** [comment]
The problem was the SD card. Even though I could access it, my camera couldn't save pictures on it too. I shut the phone off, got the SD card out, cleaned it up and started it again. It works again. Very strange, as the SD card is about one year old, not that much capacity. Thanks!
