### ISSUE TITLE
Waypoints of other lists leak onto map of a list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7209]
##### Detailed steps causing the problem:
- Use mapsforge offline map (new version)

Example scenario 1:
- Have caches with waypoints in same area on two different lists
- Open list 1
- Open map for list 1
- At some point (e.g. after panning, zooming) you will also see the waypoints of caches on list 2 on the map of list 1

Example scenario 2:
- Having a list containing all caches in a certain area
- Having a list containing a subset of the other list (my ToDo)
- While mapping the second list, suddenly WP (but not the cache icons) from caches of the first list appear on the map
- WP limit is set to 30

##### Actual behavior after performing these steps:
Included above

##### Expected behavior after performing these steps:
Only waypoints of the current list should be shown

##### Version of c:geo used:
2018.11.29-NB

##### Is the problem reproducible for you?
Yes, at least after some tries

##### Other comments and remarks:
Followup of discussion in #5900. See also comments of #5900 for more details.

**Comment by mirabilos** [comment]
Not sure if this is related, but (at least with the 2018.12.13 NB, didn’t try with today’s yet) sometimes I get addi-waypoints shown on the map even though I set the limit to 0. I set it to 0 because I just **never** want to see them except when I use the map icon in the waypoints tab (we have the luxury problem of too many caches here).

I’m pretty sure I saw this behaviour *before* the changelog entry about waypoints from other lists leaking into the view was added, though, so perhaps it’s unrelated.

**Comment by mirabilos** [comment]
OK, this also happens with the 2019.01.27 NB, with Mapsforge v4, and when navigating to ONE cache (instead of using the maps view of a list, or the live map). This is really annoying.

**Comment by Lineflyer** [comment]
@rsudev Just an an indication. Now, that this version of the new map is out this issue is one of the most mentioned on support mail. I set the label to "High" to represent this.

**Comment by ithink314** [comment]
I have the same behavior for old maps today, c:geo 2019.03.14-NB-971f289. Also, Checking old mapsforge v3 under settings/map makes a crash when a waypoint is clicked on map. It should display waypoint info/selection.

--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 9
Android build: lineage_shamu-userdebug 9 PQ2A.190305.002 66d87c2275 dev-keys
c:geo version: 2019.03.14-NB-971f289
Google Play services: disabled - 0.2.6.13280
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (38.9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (38.9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (38.9 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (548.7 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   opencaching.us: Logged in (Login OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by mirabilos** [comment]
Is there a separate issue for the crash? I can reproduce it (NB 2019-03-15)

**Comment by Lineflyer** [comment]
AFAIR the crash issue is already fixed.

**Comment by ithink314** [comment]
Both problems seem fixed for me today, with old mapsforge v3 checked.

**Comment by Lineflyer** [comment]
The issue should only be present on the new map.

**Comment by Cruiser1603** [comment]
I have the same issue with waypoints appearing on maps which are not stored in same list.
The issue appears when using OSM:Mapnik life map or an MapsForge offline map (all versions 3, 4, and 5).
The issue did NOT appear when using Google: Map or Google:Satellite.
Screenshot of display with different map selections:
![GoogleMap](https://user-images.githubusercontent.com/49304200/55614464-45872200-578d-11e9-85ef-d6bfde9ece1c.png)
![MapsForge](https://user-images.githubusercontent.com/49304200/55614465-461fb880-578d-11e9-8085-9800bb1c9383.png)
![OSMMapnik](https://user-images.githubusercontent.com/49304200/55614467-461fb880-578d-11e9-8627-99d225d34b21.png)

**Comment by Lineflyer** [comment]
I have another way to reproduce or a similar issue:
- Open map for a cache and its waypoints using new map
- Verify only WP related to this cache are shown
- Zoom out one step
- Still all normal
- Put cgeo to background
- Open cgeo again

- Now WP of other saved caches in that area are shown on the cache map
