### ISSUE TITLE
Add services usage reporting

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7214]
c:geo part of related https://github.com/cgeo/cgeo-status/issues/20

It would be great to see services usage distribution. No doubts, gc.com is leader, but the interesting point is other services.

Need to add currently enabled services with its state (authorized or not) to cgeo\main\src\cgeo\geocaching\network\StatusUpdater.java

**Comment by SammysHP** [comment]
I think we should keep this issue in the cgeo-status repository for now because it must be implemented there at first.

**Comment by okainov** [comment]
@SammysHP  it's both sides. Also I believe it can be done independently, because status can just ignore extra param if it would be there.
