### ISSUE TITLE
geocoder returns only one address

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7226]
##### Detailed steps causing the problem:
- using "search" on c:geo mainscreen
- search for city "Neustadt"

##### Actual behavior after performing these steps:
- only one result (city) is presented
- (extra info, not concern of this issue: which one seems to vary slightly: "Neustadt an der Weinstraße", when using German language settings on Android, "Neustadt" when using English language settings)

##### Expected behavior after performing these steps:
- present a list of matching cities (there are more than 20 "Neustadt" in Germany)

##### Version of c:geo used:
- current release

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
- low priority for the example given, since you can search for a more specific address or do a nearby search
- may be a little bit higher for the use case that you are searching for a city in a foreign country, don't know the exact spelling, and therefore enter only the name's beginning (like "lis" instead of lisboa/lisbon)

**Comment by moving-bits** [comment]
Did some research: c:geo requests up to 20 results (AndroidGeocoder.java), but Android returns only one result for most search strings - there seems to be a difference between the search itself and what the geocoder actually returns, as you can see in this online demo: https://google-developers.appspot.com/maps/documentation/utils/geocoder/

The search itself seems to be "google powered" and gives many possible choices, but geocoder API only returns the first of it. Try entering "San F" or "Berlin" or "Neustadt"...

![image](https://user-images.githubusercontent.com/3754370/50683385-2bb13400-1012-11e9-82dd-0e5837780433.png)

Probably not easy to circumvent for c:geo (would require a multi step approach), so lets close this issue.

**Comment by Lomanic** [comment]
From reading various Stackoverflow QAs, cgeo should use the [Places API](https://cloud.google.com/blog/products/maps-platform/address-geocoding-in-google-maps-apis) instead of Geocoding if we want numerous results to be shown. The Geocoding API is made to return a single unambiguous result. Maybe cgeo could make a request to both the Geocoding and Places APIs and display both results, say with the geocoding one in first position.

**Comment by moving-bits** [comment]
The article mentioned at least explains why there's only one result in most cases. Thanks for the link.

"Places" sounds interesting and the suggested combination of both services useful.
But from a quick scan through the documentation I think there are some caveats:

if we would use places API via https calls:
- the service is not free to use
- there are strict rules for attributions like a "powered by Google" logo which has to be displayed in the results
- it's not allowed to use a different map than google maps when displaying the results (although I'm not sure whether using just the coordinates counts as "using" in this context)

if we would use the Android API version:
- the service is free, but limited number of calls (which we probably won't reach: https://developers.google.com/places/android-sdk/usage)
- rules for attribution and displaying on google maps only apply as well (https://developers.google.com/places/android-sdk/attributions)
- there is a ready to use autocomplete component (https://developers.google.com/places/android-sdk/autocomplete)
- but I haven't found a non GUI service for full integration in c:geo's workflow.
