### ISSUE TITLE
Number of saved caches now centered over icon in main menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7229]
##### Detailed steps causing the problem:
With the changes of PR #7225 by @moving-bits I can see a (very minor) glitch on the main menu.
The amount of saved caches shown on the list icon (upper right menu item) is now shown in top-center instead of top-right of the icon.

This kind of overlaps with the long touch indicator (flip page on top left). 

##### Expected behavior after performing these steps:
Show amount of caches again on top-right corner of icon.

##### Version of c:geo used:
2019.01.07-NB

##### Is the problem reproducible for you?
Yes

**Comment by moving-bits** [comment]
@Lineflyer Yes, I did, even have tried to find a simple solution for this, but every tweak I made to the layout settings only lead to the numbers jumping to the left or to the far right, but never just "a little bit more to the right" - no combination of the different layout and alignment settings worked.
So to me it looks like we have to redo the whole start page layout someday, not just the middle part (as I did for 7225). But this might get messy, as layout settings in Android have changed a lot over the SDK versions - many new settings, a couple of deprecated ones, and new layout elements (container) as well...

**Comment by Lineflyer** [comment]
OK, agree. So IMHO we should consider this specific issue as cosmetic. I will leave it open for some weeks in case someone knows the solution. Otherwise I have no problem to just leave it like that for now and instead focus on working on a whole new thing.

**Comment by Lineflyer** [comment]
Closing as described above.
