### ISSUE TITLE
New live map version on gc.om

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7230]
gc.com is trying out a new version of the live map.

I am not sure whether this is user bound or accessible for all.
The new map is on: 
https://www.geocaching.com/play/map

Not sure whether and when they might drop the old live map but it might be worth to check the difference in terms of parsing it.

Blog report about the new map:
https://www.saarfuchs.com/2018/11/die-neue-karte-bei-der-suche-auf-geocaching-com.html

**Comment by moving-bits** [comment]
FYI: Looks like the first access to this map has to be coming through their homepage and conducting a search. In the results list you get the "Go to new map" button you have to click. From then on you can directly jump to https://www.geocaching.com/play/map, the site remembers you having selected the new map.

**Comment by jonas-koeritz** [comment]
This is super interesting, GPX download seems to possible and searching seems to be easy, maybe a new GC connector can be based on that interface?

**Comment by UniQP** [comment]
Today, Groundspeak announced that the old search map will be retired on April 25, 2019: https://forums.geocaching.com/GC/index.php?/topic/351791-pre-release-notes-website-existing-search-map-retirement-april-15-2019/

**Comment by Lineflyer** [comment]
Oh well. This will most probably break our current live map :(

**Comment by moving-bits** [comment]
I do not know how much effort ut is to adapt the parsing (I'm not deep into the current connector's parsing part), but maybe we should write to Bryan that we need more time than the remaining handful of days?

**Comment by Lineflyer** [comment]
@moving-bits 
Thanks to @jonas-koeritz we might be one step closer to solve the problem. If you are interested, feel free to take a look at the related PR.

**Comment by Lineflyer** [comment]
Reading the linked pre-release note in detail, we might have some time buffer:

> As a reminder, we are only removing the old Search map, which looks very similar to what we call the Browse map. [...] The Browse map is what you see today when you click “View Larger Map” on the cache details page, or when you select “Play” > “View Map” from the website header menu. (Those methods are changing. More on that in a minute.) The new Search map and the Browse map will still be available after the old Search map is retired.  

and

> Browse map (Will be accessible with a toggle from the new Search map as of April 25).

This sounds like the old map is still in background but only the defaults change.
Anyway it might be wise to change asap.

**Comment by Lineflyer** [comment]
Implemented by #7514
