### ISSUE TITLE
LOC file download might fail on coord search (PM)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7238]
We have got some sporadic reports, that e.g. the nearby search only returns approximated coords also for premium members.
We use to load precise coords by downloading the associated .LOC file from the search result page.

Maybe something changed on the serverside here....however for me its working well.

Can someone advise which source page is used to download that .LOC file (AFAIK its part of the "old search")?

**Comment by rsudev** [comment]
The page we use for searching by coordinates is https://www.geocaching.com/seek/nearest.aspx
From the result the url to download the .LOC-file is taken and used.
In case of not finding the -LOC url, a warning is logged. If the .LOC is not parsable (but not empty), an error is logged. When the license has not been accepted, an error message should be displayed to the user.

**Comment by Lineflyer** [comment]
Thanks, will check.

**Comment by Lineflyer** [comment]
When using this page (i.e. entering a coordinate and performing the search) the search result page shows a recaptcha just above the "Download Waypoints" button.
But it seems to be non functional....at least I can download the waypoints without using it prior.

@rsudev or others: Do you also see this? Can you load a .LOC without checking the recaptcha?

**Comment by Lineflyer** [comment]
Not reproducible , might reopen if new info comes in regarding the occurence of this problem.
