### ISSUE TITLE
Two ways of disabling brouter not consistent

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7239]
##### Detailed steps causing the problem:
- Using the new setting for the max distance for routing it is also possible to disable it (Distance=0km)
- There is another switch for disabling the routing via Map - Menu - Routing - "Direct line"

##### Actual behavior after performing these steps:
Those two possibilities currently do not work hand in hand.
This leads to the problem, that if the user selected "Direct line" he will never see a routing although the diance is set >0. Vice versa if the disance is set to 0 and the user selects routing e.g. "Bike" no routing will happen.

##### Expected behavior after performing these steps:
Either 0 should not be valid as distance setting (no deactivation via this setting) or we should move the routing method selection from the map menu into the settings.

##### Version of c:geo used:
2019.01.16-NB

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
@moving-bits

**Comment by moving-bits** [comment]
Since the menu option not only allows disabling routing but gives a choice of different types of routing I suggest to keep this option and to limit the settings slider to a certain minimum (could be either one or the minimum value below which we don't calculate a route, whichever is more).

**Comment by moving-bits** [comment]
created a PR for this. I had to choose from
- simply remove the "0 km check" while routing, changing nothing else => this could lead to irritation when setting threshold to zero and get no routing (although consistent behavior)
- keep slider range minimum at zero, but add a constant (eg 1km) for display and all calculations => recommended in some online solutions, but would have to be implemented in several locations (not my preferred solution)
- restrict minimum slider value close to but greater than 0

and took the last option (choosing a minimum of 1 km) + removing the "0 km check"
