### ISSUE TITLE
Logging sporadically has error result with big amount of TB in inventory

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7249]
Since several months I am chatting with a user on support, who keeps experiencing error messages when trying to send a geocache log to gc.com sporadically. The failure rate is varying from permanent to no problem during a day of caching.
The failure started for him with the release, where we changed to the new logging page (2018.08.14).

The exact problem is:
- Send composed log 
- Sending time is high 
- c:geo reports, that log might not have been sent
- Browser check shows, that log in fact has been posted

We checked and sorted out many causes over time, from what I remember it was:
- Reinstallation did not help
- Factory reset did not help
- Logs with or without picture make no difference
- Favorite point assignment makes no difference
- Parallel usage of other apps/website in browser not existing
- Parallel usage of same account on other device not existing
- Length of log makes no difference
- Not depending on "Report problem" selection

Current questions I gave to the user:
- Any trackables in inventory
- Any special characters in log text or signature

Does anyone have any other idea of
a) what could cause this issue
b) what could be done to track down the root cause

Not any high priority but just that I am clueless....

@pstorch In case you read this: As you implemented this logging, maybe you have some idea?

**Comment by pstorch** [comment]
Hmm, sounds like a timeout. Any difference between WIFI and mobile data? 
An extract of the logfile would be great, but I guess it is hard to get from the user.

**Comment by Lineflyer** [comment]
> Hmm, sounds like a timeout. Any difference between WIFI and mobile data?
 No.

> An extract of the logfile would be great, but I guess it is hard to get from the user.
Impossible to get due to no ability of the user and no physical meeting possible.

**Comment by pstorch** [comment]
As far as I can see the error message is deeply buried down the callstack. Would need some redesign to carry this up to the UI. What about the debug log setting? This would cause c:geo to crash. Do we see the error message then? Is the user able to send it to play console?

**Comment by Lineflyer** [comment]
I puzzled out the likely reason for the log submitting fail:
He carries currently 43 trackables and sets them to visit. For such log c:geo runs into timeout for him while logging, while the log has ben successfully posted by c:geo. As soon as he leaves them on ""no action" the log process in c:geo runs smoothly

I asked for HTML capture of the logging page (will sent via cgeo-dev mailing list).
What else could be helpful?

**Comment by pstorch** [comment]
That could be the cause. 43 is a lot. Did he check if the "visited" log is also successfully on all 43 trackables or are there some missing?
The trackable log is a separate request. Would be interesting how geocaching.com handles it on their own website. Maybe they split it and make several calls. C:geo could do that also. Say make a request for each 20 trackables.

**Comment by pstorch** [comment]
I'm not that familiar with Javascript, but it looks like they group by 10 Trackables:

![image](https://user-images.githubusercontent.com/5598124/52122733-33212880-2624-11e9-9f27-e5d24c181763.png)

**Comment by Lineflyer** [comment]
Meanwhile I have a second user with this problem, also here the following applies:
- User has large amount of TB in inventory (>60)
- Logging always OK if there is no action selected for those TB
- Logging sporadically reports error, although log is posted, when TBs are set to "Visited"

Changed labels and title of this issue accordingly.

**Comment by moving-bits** [comment]
side note - may be unrelated: I had massive problems with gc.com website regarding TB over this weekend. When logging a cache the list of TB in my inventory either did not show up at all (about 10% of the time) or my log for the cache got saved, but not the movements of my TB (about 40% of the time) - so about only 50% of all log activities worked without flaws. And this involved only four travelling TB.
So if c:geo is using the same web pages it might have been influenced by this as well.

**Comment by Lineflyer** [comment]
From social media channels I did now find even more users with this problem.
Also for them it seems to be related with carrying a high amount of TB in their inventory (92, 63, 25).
I also get some indication, that in such described error cases not all of them appear as "visited" later on.

@pstorch 
I interpret your comments the following way:
We are currently sending the TB logs while logging a cache one by one??
That might probably cause a timeout while logging depending on gc.com server response time. IMHO 30 seconds is our default for timing out the logging. 
That would perfectly fit the symptoms experienced by the user (log is sent, part of TBs are sent).
If we can group it by10 (and know the syntax, we should perhaps fix this).

@pstorch 
Could I ask you to step in here if you find some free minutes, as you are probably the only one around knowing the "new" logging code in detail? That would be really great.
I "collected" 25 TBs in my inventory...which is still not enough to provoke this problem, but at least I would be able to test if grouping works.

**Comment by pstorch** [comment]
> We are currently sending the TB logs while logging a cache one by one??

No, all in one request (> 60 in this case). This might need a long time for GC to process and the timeout of c:geo applies.

I can have a look here and implement the grouping by 10, but I cannot test it myself.

**Comment by Lineflyer** [comment]
> I can have a look here and implement the grouping by 10, but I cannot test it myself.

I can use my 25 TB to test regression and have at least two users willing to test with 50+ TB.
Would be great if you could help out here. Feel free to change on release branch.

**Comment by Lineflyer** [comment]
Thanks @pstorch for the fix.
Lets reopen here, so I can test it first.

My current tests at least show no regression for normal operation.

**Comment by Lineflyer** [comment]
No more logging problems reported since we introduced this fix. Lets close here.
