### ISSUE TITLE
More details button on cache popup too small

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7252]
##### Detailed steps causing the problem:
- Open map
- Click on cache to open popup

##### Actual behavior after performing these steps:
The "More details" button got smaller compared to before the targetsdk raise

##### Expected behavior after performing these steps:
It should be at least the height as before the targetsdk change (i.e. same height as the disk icon below)

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

##### Other comments and remarks:
Image from @okainov 
![2019-01-09 19 01 08](https://user-images.githubusercontent.com/918446/50918608-015fdc00-1441-11e9-8ede-c4f6c8607a86.jpg)

**Comment by bekuno** [comment]
@Lineflyer Are you satisfied with the visual solution at https://www.moving-bits.net/cgeo/targetsdk26/ ?
