### ISSUE TITLE
Action buttons on dialogs too big

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7253]
##### Detailed steps causing the problem:
- Open one of the following screens:
  - Refresh cache progress
  - Manage list selection
  - GPX import progress
(List might not be complete)

##### Actual behavior after performing these steps:
The available buttons (such as Cancel, OK, etc.) have a huge font size compared to the remaining dialogs

##### Expected behavior after performing these steps:
Use fitting font size compared to the other fonts used on that screen

##### Version of c:geo used:
2019.02.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

##### Other comments and remarks:
Picture from @okainov 
![2019-01-09 19 01 15](https://user-images.githubusercontent.com/918446/50918620-07ee5380-1441-11e9-890b-ee8a6fa1e31f.jpg)

**Comment by Lineflyer** [comment]
Side note:
The action buttons and the whole dialog in e.g. Menu - Settings - System- Select Geoache Data Dir looks much more consistent from its style.

**Comment by Lineflyer** [comment]
In general everything within and below the Settings seems to have another style (font, color, text size)...looks somehow nicer than some other parts of the frontend.

**Comment by moving-bits** [comment]
Is reducing font size from 20sp to 16sp enough?

![image](https://user-images.githubusercontent.com/3754370/51769185-aab1fd80-20e2-11e9-8407-e9fa1984cf01.png)

**Comment by rsudev** [comment]
While this fix seemingly adresses the issue for certain Android versions, it leaves open the question where it might have side-effects in other UIs (and on other Android versions).
I started to look through a select set of versions before and after (but didn't come very far). For Api version 17 it is not an issue to begin with.
So this text size was designed initially for a different context (likely, Api version 26 didn't exist back then), which we need to find and cross-check.

**Comment by Lineflyer** [comment]
Ups...maybe I was too fast. Problem is also, that I do not have so many API versions available on physical devices.

**Comment by githubber2222** [comment]
Actually not hard at all. Just needs proper planning. Thanks to all the compat libs you can use basically everything down to very low API levels... Not using AppCompat makes it harder.
