### ISSUE TITLE
Personal note dialog looks broken

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7254]
##### Detailed steps causing the problem:
- Open cache details of a cache
- Swipe to description tab
- Click on "modify" for the personal note

##### Actual behavior after performing these steps:
There is a free space above the text field, the text input is not starting on top of the available space.
Additionally there is a blue line at the bottom of the dialog window.

##### Expected behavior after performing these steps:
Text field starting below the title. No blue line or blue line aligned as footer of window title (do not remember how it used to be).

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

##### Other comments and remarks:
Picture from @okainov 
![2019-01-09 19 03 21](https://user-images.githubusercontent.com/918446/50918718-48e66800-1441-11e9-85f3-35e263fa1222.jpg)

**Comment by bekuno** [comment]
I have s solution, will create a PR
