### ISSUE TITLE
Context menu on image tab stopped working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7255]
##### Detailed steps causing the problem:
- Open cache details
- Swipe to image tab
- Click on an image

##### Actual behavior after performing these steps:
Nothing happens

##### Expected behavior after performing these steps:
Picture related context menu should open

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

**Comment by moving-bits** [comment]
You refer to the "open as file / open in browser" context menu (after a long press on the image)?
This is still shown in the sdk26-version on my emulated API 23 device.
_(actually with a headline in white color in contrast to my physical device with API 24, which has dark grey text color for headline on slightly lighter background, which is close to unrecognizable)_

**Comment by Lineflyer** [comment]
To be more precise about the problem:
- Short click on image used to open it in image app but does nothing for me
- Long click still opens the context menu but "open as File" does nothing for me

**Comment by rsudev** [comment]
This is due to a 'FileUriExposedException' thrown underneath. With the new targetSdk we have to share the files in a different fashion through a FileProvider, likely not a quick fix.

**Comment by Lineflyer** [comment]
Oh..interesting. Things always get more complicated but more secure :)

**Comment by moving-bits** [comment]
see PR #7307

**Comment by Lineflyer** [comment]
From looking at the commits I assume the part of the PR fixing this issue was not merged?!

**Comment by moving-bits** [comment]
Of course, fixing this was part of the PR which got merged - see changes in file ImagesList.java (changes in ShareUtils.java are the fix for GPX sharing).

A couple of questions:
- is this merge included in the nightly build? (what is the time slot for commits getting part of the next nightly build?)
- can you send me a debug log of c:geo for the part of trying to open an image?
- does GPX sharing work for you?
Thx.

**Comment by Lineflyer** [comment]
> is this merge included in the nightly build? (what is the time slot for commits getting part of the next nightly build?)

NB are built 00:30MET each night from current master 

> can you send me a debug log of c:geo for the part of trying to open an image?

Can try on the weekend. I am not at home until Saturday.

> does GPX sharing work for you?

Yes, just tested. The file gets exported as it should be.

**Comment by Lineflyer** [comment]
Addition:

Opening image works on my tablet (Android 8.1) but not on my phone (Android 8.0).
Can only test more systematically on the weekend at home, where I have additional devices.

**Comment by Lineflyer** [comment]
Damn....I could not resist to find out whats going on :)

I found a logcat app on my mobile and made a debug log.
The point seems to be the location of the image to be opened.

On my phone - where its does not work - I have the additional geocache data on my external SD. That seems to be the problem (log follows)

**Comment by Lineflyer** [comment]
Unformatted log (feel free to clean up if needed):

02-21 19:32:47.826 31491 31491 E cgeo    : [main] ImagesList.viewImageInStandardApp

02-21 19:32:47.826 31491 31491 E cgeo    : java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/3239-6230/Android/data/cgeo.geocaching/files/GeocacheData/GC7XHMJ/355faf83ac7586cbf137a08f39af9087.jpg

02-21 19:32:47.826 31491 31491 E cgeo    : 	at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:678)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:377)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at cgeo.geocaching.ui.ImagesList.viewImageInStandardApp(ImagesList.java:313)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at cgeo.geocaching.ui.ImagesList.access$200(ImagesList.java:59)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at cgeo.geocaching.ui.ImagesList$3.onClick(ImagesList.java:165)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at android.view.View.performClick(View.java:6897)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at android.view.View$PerformClick.run(View.java:26101)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at android.os.Handler.handleCallback(Handler.java:789)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:98)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at android.os.Looper.loop(Looper.java:164)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:6944)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)

02-21 19:32:47.826 31491 31491 E cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

02-21 19:32:47.826 31491 31491 E AndroidRuntime: Process: cgeo.geocaching, PID: 31491

02-21 19:32:47.826 31491 31491 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/3239-6230/Android/data/cgeo.geocaching/files/GeocacheData/GC7XHMJ/355faf83ac7586cbf137a08f39af9087.jpg

02-21 19:32:47.826 31491 31491 E AndroidRuntime: 	at cgeo.geocaching.ui.ImagesList.viewImageInStandardApp(ImagesList.java:313)

02-21 19:32:47.826 31491 31491 E AndroidRuntime: 	at cgeo.geocaching.ui.ImagesList.access$200(ImagesList.java:59)

02-21 19:32:47.826 31491 31491 E AndroidRuntime: 	at cgeo.geocaching.ui.ImagesList$3.onClick(ImagesList.java:165)

02-21 19:32:47.827 31491 31491 W cgeo    : [main] UncaughtException

02-21 19:32:47.827 31491 31491 W cgeo    : java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/3239-6230/Android/data/cgeo.geocaching/files/GeocacheData/GC7XHMJ/355faf83ac7586cbf137a08f39af9087.jpg

02-21 19:32:47.827 31491 31491 W cgeo    : 	at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:678)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:377)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at cgeo.geocaching.ui.ImagesList.viewImageInStandardApp(ImagesList.java:313)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at cgeo.geocaching.ui.ImagesList.access$200(ImagesList.java:59)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at cgeo.geocaching.ui.ImagesList$3.onClick(ImagesList.java:165)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at android.view.View.performClick(View.java:6897)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at android.view.View$PerformClick.run(View.java:26101)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:789)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:98)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at android.os.Looper.loop(Looper.java:164)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:6944)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)

02-21 19:32:47.827 31491 31491 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

02

**Comment by SammysHP** [comment]
> (feel free to clean up if needed)

Done. ;)

**Comment by moving-bits** [comment]
> The point seems to be the location of the image to be opened.

good catch, thanks for the info.

Each path has to be configured one by one to be accessible => will look into it

**Comment by moving-bits** [comment]
I created PR #7320 for this, so that @Lineflyer can test it with a nightly (if merged into release)

**Comment by Lineflyer** [comment]
Cool, thanks. Will merge if CI finished testing. Bute someone (@rsudev) needs to merge release to master to have in nightlies as well.

**Comment by Lineflyer** [comment]
Just tested with fresh brewed nightly: Working perfect now on the device previously failing (SD card). Perfect.
