### ISSUE TITLE
Icons missing in top bar of several screens

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7256]
##### Detailed steps causing the problem:
- See actual behaviour

##### Actual behavior after performing these steps:
- c:geo main screen top bar does no longer show c:geo icon on top left
- Cache details screen does no longer show cache type icon on top left

##### Expected behavior after performing these steps:
Icons should be shown

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

##### Other remarks:
Considering as `high` priority as in the cache detail view this is somehow influencing the usability as the cache type was previously visible "at first look". Now users have to scan the details list.

**Comment by moving-bits** [comment]
method call to `getDrawable` returns an empty string, although `resources` and `markerId` are set:

geocaching/compatibility/Compatibilty.java#33:
```
    public static Drawable getDrawable(final Resources resources, final int markerId) {
        return resources.getDrawable(markerId);
    }
```

called by geocaching/activity/AbstractActivity.java#234:
```
    private void setCacheTitleBar(@NonNull final CharSequence title, @Nullable final CacheType type) {
        setTitle(title);
        if (type != null) {
            getSupportActionBar().setIcon(Compatibility.getDrawable(getResources(), type.markerId));
        } else {
            getSupportActionBar().setIcon(android.R.color.transparent);
        }
    }
```
