### ISSUE TITLE
Icons on useful apps screen not aligned to text

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7258]
##### Detailed steps causing the problem:
- Open "Useful apps" from main menu

##### Actual behavior after performing these steps:
Screen is shown but icons are not aligned to text 

##### Expected behavior after performing these steps:
Usable screen with all icons and texts inline

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

**Comment by moving-bits** [comment]
Actually it's even more than that: Each entry (program) gets a full screen's height for image and text, and the image is center-aligned to this height.
I'll create a PR for this.
