### ISSUE TITLE
Text/Icon alignment and size incorrect in map settings menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7272]
##### Detailed steps causing the problem:
- Open live map Google
- Select three-dot -> Map settings

##### Actual behavior after performing these steps:
Icons and text misaligned
Icons too small compared to text (or text to big)
Style different to other submenus of this menu

##### Expected behavior after performing these steps:
Correct size and alignment, consitent style

##### Version of c:geo used:
2019.01.26-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Tablet, Android 8.1

**Comment by moving-bits** [comment]
Example screenshot:

![image](https://user-images.githubusercontent.com/3754370/64905359-660dbd80-d6d7-11e9-9f09-76e96b60456f.png)

The icons involved (ic_menu_myplaces, ... disabled, ... goto, ... circle, ... trail and ... dot_mode) are inconsistent in terms of resolution. Also, not all icons are provided for all densities.
In the screenshot provided "disabled" is too small, and "circle" and "trail" are too big.

I'll prepare a fix for this.

**Comment by moving-bits** [comment]
See #7849 for the icon related part

**Comment by Lineflyer** [comment]
On my device (in german locale) it looks even worse as the icon and text are also overlapping.

**Comment by moving-bits** [comment]
@Lineflyer
Does it still happen? Test with current master on a low res device gives this for me:

![image](https://user-images.githubusercontent.com/3754370/66144433-1c92fd00-e609-11e9-8e92-b386ed8898b2.png)

(Settings menu extends to full screen width, and texts get truncated if too long)

**Comment by Lineflyer** [comment]
On a lower res device (in this case Android 5.0.1) it looks OK as in your screenshot.
However on my Android 9 Samsung S10 it still overlaps...no big deal, so no high priority:

![Screenshot_20191003-213639_cgeo](https://user-images.githubusercontent.com/949669/66158780-de0c3b00-e626-11e9-89cd-b4b79a5da718.jpg)

**Comment by andrixnet** [comment]
Problem persists in c:geo 2019.11.11 on Samsung S9+ (high res device), en locale.

Google map provider; Map settings menu
![Screenshot_20191117-113839_cgeo](https://user-images.githubusercontent.com/3382777/69737149-8c6ec100-113c-11ea-9fbe-1b3baf919214.jpg)

OSM map provider; Map settings menu
![Screenshot_20191117-113853_cgeo](https://user-images.githubusercontent.com/3382777/69737173-985a8300-113c-11ea-89a9-71631ffc2844.jpg)

**Comment by moving-bits** [comment]
Indirectly solved by the new map quick settings popup
