### ISSUE TITLE
Mapsforge v4: unsaved caches go away after viewing them on live map

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#7276]
##### Detailed steps causing the problem:
- Disable the old Mapsforge v3 API due to #7275
- Start the Live Map
- Hit “Enable Live”
- Wait until new caches show up
- Click on one, to get the popup with the preview info
- Click on the map background to make the popup go away again after having read it

##### Actual behavior after performing these steps:

- The cache icon is no longer shown on the map

##### Expected behavior after performing these steps:

- The cache icon was still shown (it was in 2018.12.13 with Mapsforge v3)

##### Version of c:geo used:

2019.01.27 NB

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: HTC Desire (htc_bravo, htc_wwe)
Android version: 4.4.4
Android build: liquid_bravo-userdebug 4.4.4 KTU84Q c5fea05051 test-keys
c:geo version: 2019.01.27-NB-4ff734d
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: yyyy/MM/dd
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (964.0 MB free) internal
User storage c:geo dir: /storage/sdcard0/cgeo (4.4 GB free) external
Geocache data: /storage/sdcard0/Android/data/cgeo.geocaching/files/GeocacheData (4.4 GB free) external
Database: /storage/sdcard0/Android/data/cgeo.geocaching/files/databases/data (26.0 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   opencaching.de: Logged in (Login OK)
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by SammysHP** [comment]
AFAIK there is another issue describing this problem. I noticed it also after moving the map. Sometimes caches disappear and appear again after moving the map again.

**Comment by Lineflyer** [comment]
Yes, there is still such faulty behaviour on the new map. But I can currently not find the issue which I AFAIR opened for that.

**Comment by Lineflyer** [comment]
I cannot reproduce this problem anymore using 2019.11.28
