### ISSUE TITLE
Icons and text in cache inventory out of alignment

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7281]
Similar to the problem on "Useful apps" also icons and text of the cache inventory tab are out of alignment.

2019.02.01-NB

Android 8.0

I am on mobile phone only, therefore I had to keep it short.

**Comment by moving-bits** [comment]
after changes in PR7282 trackables list on cachedetails page looks like this again (API 23):

![image](https://user-images.githubusercontent.com/3754370/52169545-753c8e00-273a-11e9-9d81-9b8c277716d4.png)
