### ISSUE TITLE
background color in dialogs and activities too bright (targetdsk26)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7285]
I've made a couple of screenshots for a comparison of release version and current master (as of today, February 08) to get a visual reference for the targetsdk26 layout issues, see https://www.moving-bits.net/cgeo/targetsdk26/index.php

As you can see in many of the screenshots, the background color for several layout elements has changed from complete black to a lighter color, which is a visual issue (since it is inconsistent across dialogs and layout elements) as well as more power consuming on AMOLED screens.

This is no blocker for a targetdsk26 release, but should be corrected after that release anyway.

---

examples are:
- settings activity
- cache popup window on map
- action bar (cache details page)

to name a few.

**Comment by Lineflyer** [comment]
@moving-bits 
I think meanwhile we even target the light black background and the pure black background is the old one. Is this issue still relevant?

**Comment by fm-sys** [comment]
IMHO the dark gray looks way more modern as the pure black. I would also vote for closing as "won't fix"

**Comment by moving-bits** [comment]
I would leave it as is now, and tackle a possible change with #9373 (as I would do with all other non-obvious, non-easy-to-fix theming issues).
