### ISSUE TITLE
TB inventory not saved

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7286]
During my tests for targetsdk26 I stumbled upon that the cache inventory does not get saved (or at least does not survive an emulator's cold reboot):

- open cache details of a certain cache which has TB
- reload cache => TB inventory gets loaded and is visible on the Inventory subpage
- close c:geo and shutdown emulator

then:
- reopen emulator with a cold reboot
- open the same cache's detail page

=> no subpage "Inventory" anymore

Is this a bug or done by design?

##### Version of c:geo used:
release 2018-10-13 as well as developer build 2019-02-09

##### Is the problem reproducible for you?
Yes (tested with API 22, 23, 26 in Android Studio VM)

**Comment by Lineflyer** [comment]
I think, I have seen the same bahviour in real life during my recent vacation:
- I saved some caches onto my lists (for offline use during vacation)
- The list shows the TB-icon for some of them, however if I open these saved caches , there is no inventory shown

@moving-bits Is that what you mean?

**Comment by moving-bits** [comment]
@Lineflyer Welcome back!

Yes, looks like the problem I'd encountered during my tests, just a different way to reproduce the symptoms.

**Comment by Lineflyer** [comment]
@moving-bits I was not able to reproduce. Could you reproduce it on a real device?

**Comment by moving-bits** [comment]
I have not encountered this on a real device anymore, so let's close this for now.
