### ISSUE TITLE
Loading progress spinner missing on live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7289]
No progress spinner shown on live map title bar any more.

More details when I am back home, but might be self explanatory.

**Comment by rsudev** [comment]
It is clear. I observed it  as well when testing the marker clustering.
I saw it missing on the new mapsforge map. Google maps and old mapsforge map need to be confirmed.

**Comment by Lineflyer** [comment]
Tested: It is missing on all map types.

**Comment by moving-bits** [comment]
@rsudev Seems like progress spinners are deprecated in newer API levels (starting from 24), if I understood the following links correctly:
- https://stackoverflow.com/questions/27788195/setprogressbarindeterminatevisibilitytrue-not-working
- https://developer.android.com/reference/android/view/Window (see parts about several constants for progress spinner, e. g. FEATURE_INDETERMINATE_PROGRESS)

**Comment by Lineflyer** [comment]
BTW: The progress spinner is also missing while the list of search results is being loaded..however in that case there is a spinner in the list window itself. Don't know if we need to address this issue...

**Comment by okainov** [comment]
There should be for sure an indicator that caches loading is not finished. Whatever spinner or not, but it should be in place

**Comment by moving-bits** [comment]
Looks like we need to replace the old actionBar (or AppCompat.actionBar) with the new Toolbar / AppCompat.Toolbar to regain a progress spinner, see here: https://www.vogella.com/tutorials/AndroidActionBar/article.html

**Comment by Lineflyer** [comment]
> ooks like we need to replace the old actionBar (or AppCompat.actionBar) with the new Toolbar / AppCompat.Toolbar to regain a progress spinner, see here: https://www.vogella.com/tutorials/AndroidActionBar/article.html

That sounds like a bigger change required, right?

**Comment by moving-bits** [comment]
> > Looks like we need to replace the old actionBar (or AppCompat.actionBar) with the new Toolbar / AppCompat.Toolbar to regain a progress spinner, see here: https://www.vogella.com/tutorials/AndroidActionBar/article.html
> 
> That sounds like a bigger change required, right?

To my understanding: Yes.

**Comment by okainov** [comment]
Can you make it whatever indication of loading which is simpler to implement? I mean, really whatever - changing title, showing toast "loading completed", changing some color of some UI element. The problem is not a spinner, but indication. Spinner is nice, but if you're saying it requires deeper refactor - can we just get simple fix to eliminate the problem and properly refactor spinner later?

**Comment by moving-bits** [comment]
assigned myself for implementing a workaround (show toast after loading of caches is finished)

**Comment by MagpieFourtyTwo** [comment]
Perhaps this can be coupled to the addition/enabling of the menu entry "show as list", which seems to appear in this very moment,  i. e. when loading has finished.

Would be great if there could additionally be a persistent change (to UI or whatever is possible), to be able to recognize loading is ready even if you missed the toast ...

**Comment by bekuno** [comment]
Maybe we find a way to place the ProgressBar on a menu without change to Toolbar?
Se also
https://abhiandroid.com/ui/progressbar
http://androidideas.com/android-loading-spinner-tutorial/

**Comment by moving-bits** [comment]
@bekuno Thanks for the links. I added a PR to implement a centered circular spinner for CGeoMap (Google / old Mapsforge) and NewMap (new Mapsforge)

**Comment by Lineflyer** [comment]
Oh nice. Can you post a screenshot?Von meinem Smartphone gesendet.
null

**Comment by moving-bits** [comment]
Currently it's like this:

![image](https://user-images.githubusercontent.com/3754370/58366475-09418980-7ed3-11e9-90e3-7c4b02b90e68.png)

But I've just seen that we already do have a circular spinner when waiting for the results of an address search. Maybe I can adapt this one.

**Comment by MagpieFourtyTwo** [comment]
Thx a lot for the solution, highly appreciate it - but would it be possible to make it a little bit more visible?

Perhaps it's related to the "actitivity bar", perhaps there has been implemented a limit for the number of caches shown on live map in the meantime, but with exact the nightly where the activity bar came into play, I do no longer see all caches in live map. This is very visible when zooming out: The outer regions of the map remainm empty, although loading has finished (and they even do not appear after several minutes). Moreover, even in areas which are not that "polluted" with caches, still "new" ones appear on zooming in ... kind of strange ... s/b else seen this?

**Comment by moving-bits** [comment]
> Perhaps it's related to the "actitivity bar", perhaps there has been implemented a limit for the number of caches shown on live map in the meantime, but with exact the nightly where the activity bar came into play, I do no longer see all caches in live map. This is very visible when zooming out: The outer regions of the map remain empty, although loading has finished (and they even do not appear after several minutes). Moreover, even in areas which are not that "polluted" with caches, still "new" ones appear on zooming in ... kind of strange ... s/b else seen this?

Is this "free zone" just at the top of the map, directly beneath the action bar, or is there a free zone on all sides of the map? Can you provide a screenshot?

**Comment by rsudev** [comment]
I would assume it is related to what I want to fix in #7657

**Comment by bekuno** [comment]
I also vote to make it more concise.

**Comment by MagpieFourtyTwo** [comment]
> I would assume it is related to what I want to fix in #7657

I would say, this is different. In scenarios concerning #7657 the caches are just not displayed and will be shown once you zoomed in and out again.  In this case the number of caches remains the same after zooming.

It seems more like a limitation of the number of caches to be displayed (and/or downloaded).  First thought this could be approx. 500 per service (I am using two services, geocaching.com and extremecaching.com), but sometimes not even 300 are displayed in total. And in other cases (e. g. when zooming to show complete South America, it shows several thousands. Probably a download time limit ...?

> Is this "free zone" just at the top of the map, directly beneath the action bar, or is there a free zone on all sides of the map?

Nop, "fresh" caches are displayed in the center of the map only, outer regions remain "nearly" free, apart from offline saved caches, which will always be shown.

Even more strange: Once you got this cluster of ~500 caches, just move the map so that the cluster goes to a corner of the screen - surprise, surprise: the old cluster disappears and a new one will be shown around the "new" center of the map.

> Can you provide a screenshot?

![Zooming out](https://user-images.githubusercontent.com/9889015/59275563-d6322080-8c5c-11e9-9d63-faababc1302a.jpg)

**Comment by MagpieFourtyTwo** [comment]
Just another observation: When I open a cache popup from the live map (after map refresh has ended, i. e. the progress bar is gone) and then close the popup, the progress bar starts to run again ... is this intended / correct?

**Comment by Lineflyer** [comment]
AFAIR there is a limit of the cachecache of 500 caches. This will be the circle of loaded caches you are seeing.  It was like that ever since. I do not consider c:geo as the main tools to map >500 caches at once.

> And in other cases (e. g. when zooming to show complete South America, it shows several thousands.

According to what I described above this should not be the case..

**Comment by okainov** [comment]
> I do not consider c:geo as the main tools to map >500 caches at once.

Proposal from users side - please reconsider this. There were a lot of comments in previous issues, we do use the app in the areas with high caches density. If you're in Germany, you could just zoom out of your city (or region) - I'm pretty sure there will be much more than 500 caches around.

**Comment by MagpieFourtyTwo** [comment]
Ok, a 500 caches cache would explain this behavior. Haven't seen (or at least not been hampered by) this before, as I usually use way smaller map segments anyway. It's just a little bit confusing in situations where you slightly hit this limit without recognizing, then zoom in, and suddenly even more caches pop up in regions where before have been way less or even none at all.

As for the bigger count in e. g. South America, just try and find out: Disable live map refresh, then pan and zoom e. g. the Google map until it displays the entire "island" and then enable refresh - as for me 942 caches pop up right away. And after moving the map "down" until the first cache in the south hits the lower screen boundary, even 1476 caches will shown up. Moving it back "up" until the northmost cache hits the upper boundary of the screen, even 1905 are shown.

And of course I don't want to visit all Brazilian caches in one day, this is just an example. But in other areas, 500 caches are reached *way* faster, but *there* the 500 caches limit hits - and there it hits even harder.

![942](https://user-images.githubusercontent.com/9889015/59283199-78a4d080-8c6a-11e9-8978-4a1b5b80b7e5.jpg)

![1476](https://user-images.githubusercontent.com/9889015/59283207-7e021b00-8c6a-11e9-8825-57061f6110bb.jpg)

![1905](https://user-images.githubusercontent.com/9889015/59283215-8195a200-8c6a-11e9-85e2-f15a4e6d7aa1.jpg)

**Comment by MagpieFourtyTwo** [comment]
But to come back to where I wanted to go: This example seems to show that this 500 caches cache may at least not work as expected - if it exists at all ...

**Comment by moving-bits** [comment]
> AFAIR there is a limit of the cachecache of 500 caches. This will be the circle of loaded caches you are seeing. It was like that ever since. I do not consider c:geo as the main tools to map >500 caches at once.
> 
> > And in other cases (e. g. when zooming to show complete South America, it shows several thousands.
> 
> According to what I described above this should not be the case..

I'm not sure about cachecache, but map behaviour on gc.com also has changed: With the old map, even "thousands" of caches were shown, like "the whole of Canada". (And I'm unsure, if we really limited loading to 500.)
But with the new map, gc.com website only shows 500 caches by default. This limit can be lifted to up to 1.000 caches, but have not tried whether this setting is permanent (and therefore visible to c:geo without actively setting it).
