### ISSUE TITLE
Add Cache to List on GC-Website

### ISSUE THREAD

**Issue by Uli001** [cgeo/cgeo#7292]
Ich arbeite an verschiedenen Geräten (Tablet, Tablet, Telefon, PC) um eine Tour. Vorzubereiten oder einfach ein paar Caches zu lösen. Ich würde mir einen einfachen Weg wünschen den Cache zu einer Liste auf GeoCaching.com hinzuzufügen. Damit ist das Teilen mit Freuden die auch mit auf Tour gehen einfacher und alle können die Liste gleich als GPX nutzen. Auch gelöste Mysterys oder erfüllt Challenge lege ich auf einer Liste ab. Ich würde es mir wünschen wie beim "Add to Watchlist". Klar gibt es mehrere Listen aus denen noch ausgewählt werden muss. Absoluter Luxus ist es wenn auch neue Listen angelegt werden können.

VG Uli

**Comment by SammysHP** [comment]
Duplicate of #118.
