### ISSUE TITLE
Missing images on special cache site (GC7B79F)

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7296]
##### Detailed steps causing the problem:
- open Cache GC7B79F on website and in c.geo
- compare it: the 3 images are not visible in c.geo

##### Actual behavior after performing these steps:
the 3 images are not visible in c.geo

##### Expected behavior after performing these steps:
the 3 images are visible in c.geo

##### Version of c:geo used:
2019.02.16 developer buils (with PR #7295)

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
testet with patch from PR #7295

**Comment by Lineflyer** [comment]
@bekuno 
I tested this issue with a new NB (incl. your PR #7295) and it is working for me.

It does not look nice in c:geo (which might be caused by the fact, that the pictures are part of the hyperlinks) but it works. 

Can you doublecheck?

**Comment by bekuno** [comment]
I mean this part:
<img src="https://thumbs.jigidi.com/embed.php?t=sq_EU3T5O8F_192" alt="Jigsaw puzzle - 1) Das Tor" style="display:block;border:none;margin:5px 0 0 0;" />
Possibly this works as before the website change.

**Comment by bekuno** [comment]
Sorce whithout brackets:
 img src="https://thumbs.jigidi.com/embed.php?t=sq_EU3T5O8F_192" alt="Jigsaw puzzle - 1) Das Tor" style="display:block;border:none;margin:5px 0 0 0;"

**Comment by Lineflyer** [comment]
But can you confirm you can see the images in c:geo?
I do see them.

**Comment by yoursunny** [comment]
I can see the pictures of this cache on c:geo 2019.02.17-RC, but they are placed to the right of text, while the website places them below the text.

**Comment by bekuno** [comment]
Strange. I tested with my latest build from master and with 2019-08-18-NB on my S6.
No Images.
![screenshot_20190218-204124](https://user-images.githubusercontent.com/32555742/52973452-80402100-33be-11e9-845d-ed07cb0ae8ce.png)

And on the cgeo images site it shows error:
![screenshot_20190218-204150](https://user-images.githubusercontent.com/32555742/52973485-95b54b00-33be-11e9-95bf-7888f8031c66.png)

open them in the browser is ok.

**Comment by Lineflyer** [comment]
Mmh.. the "??"-cache type from your screenshot makes me think, that you are not logged in or something else is wrong with your installation.

**Comment by bekuno** [comment]
It was the same after loged in to GC. :-(

**Comment by okainov** [comment]
Works fine for me in master + gc.su, images are ok both in description and on Images tab

**Comment by okainov** [comment]
>Mmh.. the "??"-cache type from your screenshot makes me think, that you are not logged in or something else is wrong with your installation.

@Lineflyer  this seems like separated issue, I have the same

**Comment by bekuno** [comment]
I have this problem only on one device - a Samsung S6 (Android 7.0), not on 2 other with higher/lower Android version.

**Comment by Lineflyer** [comment]
IMHO it could be some sort of problem with the images being corupted or unaccesible from the geocache data directory c:geo is using.

**Comment by bekuno** [comment]
I deleted the image directory (Android/data/cgeo.geocaching/files/GeocacheData/GC7B79F).
on the problematic device and on another.
After updating the cache, the directory was recreated.
There are now 6 files in the OK device, but only three in the problematic one.
These missing files are the missing images (checked by "Open as image" in X-plore in the OK device).

Does anyone have any idea where I should look at this with the debugger?

**Comment by Lineflyer** [comment]
This happens to me sometimes when the storage directory seems to be not accessible for c:geo for whatever reason.
On my previous device I stumbled upon this issue at some point. After rebooting the device or reinserting the SD (cant remember) it was resolved after refreshing the cache.
So at that time it was an issue that the location was - for whatever reason - not accesible.

**Comment by bekuno** [comment]
Strange.
The folder was completly deleted, and fresh created and partly filled by c:geo.
And this is the internal storage.

No change after rebooting the device.

**Comment by moving-bits** [comment]
@bekuno  Is this still reproducible for you? Works for me with current release version. Change might be due to the fix for #7889 (allowing http connections, see #7892).

**Comment by bekuno** [comment]
It's unchanged.
But only happens on this one device.
I should really debug it.

**Comment by bekuno** [comment]
her it is:
```
2019-11-30 17:23:01.586 21776-13557/cgeo.geocaching W/cgeo: [OkHttp] Failure (386 ms) GET https://thumbs.jigidi.com/embed.php?t=sq_LCLNO197_192 (javax.net.ssl.SSLHandshakeException: Handshake failed)
2019-11-30 17:23:01.587 21776-12093/cgeo.geocaching W/cgeo: [network--9] Exception in HtmlImage.downloadOrRefreshCopy: java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Handshake failed
```

**Comment by bekuno** [comment]
Hmm, did not find a true reason in the deep of OkHttp (RealCall.java).
Maybe this reason: "The latest protocols installed on a device are not necessarily enabled on its default SSLSockets!" (see https://medium.com/tech-quizlet/working-with-tls-1-2-on-android-4-4-and-lower-f4f5205629a)

By the way, we can currently not upgrade OkHttp to a higher level, because okhttp:3.13 needs at least Android5 (minSdkVersion 21). (https://cashapp.github.io/2019-02-05/okhttp-3-13-requires-android-5)

**Comment by fm-sys** [comment]
Whats the current state of this issue? @bekuno Is it still reproducible for you? 

> By the way, we can currently not upgrade OkHttp to a higher level, because okhttp:3.13 needs at least Android5 (minSdkVersion 21)


We had increased the minSdkVersion to 21, so we could upgrade okhttp (if it isn't done already) ...

**Comment by moving-bits** [comment]
> We had increased the minSdkVersion to 21, so we could upgrade okhttp (if it isn't done already) ...

After the minSDK raise to 21 we also upgraded okhttp to version 4 (see #8435).

**Comment by bekuno** [comment]
@fm-sys 
Thanks for reminding me of this issue. I checked it - it is fine now.
