### ISSUE TITLE
Trackable description missing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7297]
##### Detailed steps causing the problem:
- Open TB59M9P
- Compare to website

##### Actual behavior after performing these steps:
"Current goal" is shown, "About this item" section is missing

##### Expected behavior after performing these steps:
All information shown

##### Version of c:geo used:
2019.02.17-NB / 2018.10.13

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
I found this while looking at the failed tests on our CI

**Comment by rsudev** [comment]
I saw it as well, fix attempt in bd7e0df

**Comment by Lineflyer** [comment]
Confirmed (and tested) to be solved with #7295.
