### ISSUE TITLE
Archive of nightlies could be helpful

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7301]
While testing today it came to my mind, that an archive of recent nightlies could be helpful.
I would think of the latest 3 months.

IMHO it could be achieved by modifying the CI nightly job to copy the resulting APK additionally to a file named cgeo-nightly_`versionCode`.apk to the very same server.

Additionally we would need a housekeeping to delete older files.

**Comment by rsudev** [comment]
This can be achieved relatively easy within Jenkins (analogous to the pr builder). I can take a look.

**Comment by mucek4** [comment]
Technically I could extract them from backups if we need them for some days ago.

**Comment by Lineflyer** [comment]
Not needed for now.
I wanted to test if Google Play would still accept old targetSDK versions, but I already finally clicked on publishing the RC, which means there is no way back to older SDK now.

But for future it would be nice to have it.

**Comment by bekuno** [comment]
As now we have a problem in #8876 it would helpfull to test if there is really a problem in c:geo or in the databas archive.

@rsudev 
Can you have a look a the jenkins configuration?

@mucek4 
Can you extract the 2020.08.23 nightly?

**Comment by mucek4** [comment]
https://download.cgeo.org/cgeo-nightly-22-8.apk
https://download.cgeo.org/cgeo-nightly-23-8.apk

**Comment by bekuno** [comment]
Now that the need for an older Nightly build was addressed in #9793, I configured the apk archiving as in the PR configuration.
The test with rebuild the last nightly was sucessful.
Lets wait until the next planned nightly is also fine.

**Comment by bekuno** [comment]
The regular nightly worked as expected.
Lets close the issue.
