### ISSUE TITLE
Compile error: cannot find symbol class StaticMapsActivity_ (with gradle 3.3.0)

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7309]
##### Detailed steps causing the problem:
- set "classpath 'com.android.tools.build:gradle:3.3.0'" in build.gradle
- set "distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip" in gradle-wrapper.prpeeties
- sync, build, and start
- the buils stops at :main:compileBasicDebugWithJavac -> Execute compile
  with "error: cannot find symbol class StaticMapsActivity_"
  at file cgeo/main/src/cgeo/geocaching/apps/navi/AbstractStaticMapsApp.java

##### Actual behavior after performing these steps:
c:geo does not run

##### Expected behavior after performing these steps:
it compiles and c:geo runs

##### Version of c:geo used:
source from current master

##### Is the problem reproducible for you?
Yes

**Comment by rsudev** [comment]
The StaticMapsActivity_ is seemingly generated during the build by processing the annotations on StaticMapsActivity.
Why the change in the gradle-plugin or gradle version stops doing that and whether it might be possible to mitigate by referencing a different Annotation version needs to be investigated.
