### ISSUE TITLE
Coord input dialog broken for DMS format

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7311]
##### Detailed steps causing the problem:
- Open "search" menu
- Click on coordinate fields
- Change format to DMS (DDD° MM'SS.SSS'')

##### Actual behavior after performing these steps:
The N/E prefixes are not shown, once you click on them the window is resized and shown normal.
Besides that the whole input got smaller than before.

##### Expected behavior after performing these steps:
Window should be shown complete initially. 
Size of window and all elements could be a bit higher.

##### Version of c:geo used:
2019.02.17-RC

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

##### Other comments and remarks:
Reported on support mal

**Comment by bekuno** [comment]
It is no data problem, but a visibiliy problem.
The text is visible in landscape mode.
