### ISSUE TITLE
Usage of your Geocache and Attribute Symbols in QMapShack

### ISSUE THREAD

**Issue by pingurus** [cgeo/cgeo#7314]
I am currently improving the Geocaching support of [QMapShack ](https://bitbucket.org/maproom/qmapshack/wiki/Home)and would like to use the Geocache Icons and the Attribute Symbols that are used in c:geo.

The licensing should be fine, as the Icons are under Apache 2.0 (see my earlier issue #6967  ) and the Attribute Symbols either under Public Domain or CC0, if I got that correctly.

Is this okay with you?

**Comment by Lineflyer** [comment]
I did not find anything which objects to your statements and would therefore say it is fine to use those under the terms you propose.

Feel free to contact us/me if you have a remaining question.
