### ISSUE TITLE
Some 'live' caches appear 'disabled' in lists

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7317]
I've found some live caches appear as disabled (i.e. with a line through them) in lists.
I can't find any pattern in which caches appear this way, it seems to be event caches, but not all of them.

##### Detailed steps causing the problem:
- load GC82J45  [ Puzzle Club - I ❤️ Puzzles ]
- Add it to a list
- Observe the status in both the list and the cache page.

##### Actual behavior after performing these steps:
Cache is 'live' on the cache page (Which it currently is)
Cache is 'disabled' in the list.

##### Expected behavior after performing these steps:
Cache should show as 'live' in the list.

##### Version of c:geo used:
2019.02.18-RC

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
I'll attach screenshots in a separate post.

**Comment by alan666notb** [comment]
![screenshot_20190220-091312_cgeo](https://user-images.githubusercontent.com/7459480/53080585-e6c55c00-34f0-11e9-919c-a3a6e9fc43b6.jpg)




![screenshot_20190220-091252_cgeo](https://user-images.githubusercontent.com/7459480/53080590-ea58e300-34f0-11e9-955e-0292681d0387.jpg)

**Comment by Lomanic** [comment]
I think this black strikethrough just shows that the event is over, this is a red strikethrough for a disabled cache.

**Comment by Lineflyer** [comment]
Yes, the strikethrough of past events is a feature of cgeo. 
As it was introduced I did not like it, as it is inconsitent usage of strikethrough. However it might be helpful to see if the event is of any interest or not.
