### ISSUE TITLE
Go to menu is missing its title bar menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7324]
Despite the fact, that "Go to" needs a general rework (see #3288) there seems to be a problem since targetsdk26.
##### Detailed steps causing the problem:
- Start c:geo
- Open "Go to"
- Enter valid coordinates

##### Actual behavior after performing these steps:
There are no button on top right of the action bar, so its not possible to start navigation to the coordinates. 
This seems either to depend on the Android version or on some other depedency:
On my Android 8.0 phone I have seen this once but cant reproduce now
On my Android 5.0.1 phone its reproducible.

##### Expected behavior after performing these steps:
Full menu should be available (buttons + overflow)

##### Version of c:geo used:
2019.02.24-NB

**Comment by Lineflyer** [comment]
Also reported by another user now, don't know his Android version yet.

This is how it looks like for him (same as for me on the Android 5 device):
![grafik](https://user-images.githubusercontent.com/949669/53397495-8b3f1680-39a7-11e9-9426-766d8d561989.png)

**Comment by Lineflyer** [comment]
Here we go with the user info:
```
--- System information ---
Device: Redmi 4A (rolex, Xiaomi)
Android version: 7.1.2
Android build: N2G47H
c:geo version: 2019.02.23
Google Play services: enabled - 15.0.90 (040406-231259764)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: pl_PL
System date format: dd.MM.y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (784,8 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (784,8 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (784,8 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (284,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Nazwa użytkownika OK) / BASIC
   opencaching.pl: Logged in (Nazwa użytkownika OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Quite some users now on our support mail and social channels with this problem.
Any idea around?

Or should we even try to finally replace this menu by: #3228

**Comment by Lineflyer** [comment]
Forgot to assign matching labels to this one and raise prio to high as the feature (how wide or rare it might be used) is totally not working.

**Comment by Lineflyer** [comment]
Can reproduce it also now on my Android 9 Samsung Galaxy S10

**Comment by Lineflyer** [comment]
A lot of support mails regarding this problem recently. Still I think this is the best occasion to get rid of this old part of c:geo. 

I would really appreciate if someone, who has time and ability, replaces this function by a waypoint screen as described in #3288

**Comment by moving-bits** [comment]
made obsolete by #7946
