### ISSUE TITLE
No offered Link to the App HexEditor

### ISSUE THREAD

**Issue by balu2003** [cgeo/cgeo#7330]
##### Detailed steps causing the problem:
before Version 2019.02.23 and before the Nightly Build 2019.02.03 the following was possible:
(I have installed the Apps FX (filemanager) and HexEditor) on my both systems, smartphone and tablet
- open any  cache 
- swipe to right until you see the page pictures (of the Listing)
- tap on any picture
- a dialog appears 
- Open With: Galerie, FX Viewer, HexEditor
- choose "Open only once" and e.g. the HexEditor
- The Picture will be opend with Hexeditor
##### Actual behavior after performing these steps:
But now, sinnce 2019.02.23 (in release and in nightly Build) after tapping on the picture the dialog "open with" does no longer offer the hexeditor, but only Galerie and FX viewer.

##### Expected behavior after performing these steps:
 dialog "open with" offers galerie, FX Viewer, HexEditor

##### Version of c:geo used:
--- System information ---
Device: SM-G930F (heroltexx, samsung)
Android version: 7.0
Android build: NRD90M.G930FXXU2DRC1
c:geo version: 2019.02.23
Google Play services: disabled - 15.0.90 (040408-231259764)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (16,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (16,3 GB free) external non-removable
Geocache data: /storage/0001-4880/Android/data/cgeo.geocaching/files/GeocacheData (37,8 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (10,3 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---

##### Is the problem reproducible for you?
Yes

**Comment by Lomanic** [comment]
Related to #7255?

**Comment by Lineflyer** [comment]
As far as I understand the recent inteoduction of the file provider, we now tell the system, that the file is mime-type image/JPEG.
That could be the reason your hex editor is no longer offered by the system.

Not sure though why it worked before?!
@moving-bits

**Comment by moving-bits** [comment]
Nothing changed in this regard - c:geo always has set the MIME type for the selected file.

The only change was that instead of publishing a link into the local filesystem directly - which isn't allowed any longer due to our switch to a more recent target API level - we now use the official mechanism Android provides us for such things (which is a FileProvider).

Maybe the new API version is more strict in interpreting which app can open which MIME type, or has a different mechanism in identifying and selecting the target apps.

We had to switch to the new API level due to Google Play Store restrictions, and the new API level does not provide the old mechanism any longer, so there is no way for us to still provide the old mechanism.

**Comment by balu2003** [comment]
It seems that my HexEditor is not able to open items by "Content URI". I dont know why it was working with formerly versions of cgeo, It may depend on the API level as moving-bits wrote above.
Because it seems to be a special problem for me , i would close the issue?
(And because cgeo is not a puzzle-solving-tool, there is no really need for launching a hexeditor from cgeo,  But it was a nice feature :-) )

**Comment by Lineflyer** [comment]
Thanks for your feedback. I also think we close this issue, unless there are more people coming up with such a problem, which could indicate there is something wrong on our side.
Maybe you also find another hexeditor, which supports all file types.
