### ISSUE TITLE
Remove Google static map feature

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7332]
Google stopped offering static maps for free. This is the reason, why the feature stopped working in c:geo. Details can be found here: #7150

The non working feature should be removed from c:geo as I don't expect Google to change its mind or c:geo team to be able to pay for such maps.

An alternative source (if there is any) could be implemented at the same step or afterwards.

Please be aware:
Currently all user installations will still send request to Google for static maps as the feature is still in and the default value is "Active". So removing it, might also a bit increase the performance.

**Comment by bekuno** [comment]
I could not find that the offering is stopped. I assume that the free limit 
https://cloud.google.com/maps-platform/pricing/
is exhausted.
Maybe a limit per user could implemented in c:geo?

**Comment by Lineflyer** [comment]
> I could not find that the offering is stopped. I assume that the free limit
https://cloud.google.com/maps-platform/pricing/
is exhausted.
Maybe a limit per user could implemented in c:geo?

Thats correct and this limit is per key, not per user.
Obviiously 100000 maps seems not enough, as the maps are no longer working....or maybe we need to activate something on the Google account bound to our key before even the 100.000 maps are available.
Good question.

**Comment by bekuno** [comment]
I mean a limit per device controlled by c:geo.

**Comment by moving-bits** [comment]
We could circumvent this by giving the user a way to enter their own key. But IMHO users who are able (and willing) to apply for their own Google Maps API key would be fit enough to install an OSM offline map as well (and by this avoiding the problem completely).

**Comment by bekuno** [comment]
> We could circumvent this by giving the user a way to enter their own key. 

The problem is not only the key "as such" - you have to specify a bank account.

**Comment by moving-bits** [comment]
> The problem is not only the key "as such" - you have to specify a bank account.

Yes, I know. And you can't even set a limit to always stay within the "free" limit. That's why I have switched my web projects away from Google Maps during the last months.

**Comment by Lineflyer** [comment]
> We could circumvent this by giving the user a way to enter their own key.

We discussed this some time ago, when we had to remove OpenCycleMap and decided against it. Maybe OK for some real "teccy" users, but IMHO not suitable for Google Maps...or do you know any other app, which requires users to add a bank account to their Google account and generate keys, etc.

**Comment by SammysHP** [comment]
You can't even get a v1 key anymore. ;)

**Comment by moving-bits** [comment]
In today's master static maps generation is only disabled to get the version out to market.
The feature still needs to be removed completely, so I reopen this issue.
[Reopening is for completely removing all static maps generation features only. If we want to implement a different provider for static maps, this should become a separate issue.]
