### ISSUE TITLE
Navigation with maps.me not starting

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7340]
##### Detailed steps causing the problem:
- Have maps.me installed
- Open cache details of a cache
- Select Navigate -> maps.me

##### Actual behavior after performing these steps:
Nothing happens, maps.me not starting

##### Expected behavior after performing these steps:
maps.me should be started with cache coordinates as destination

##### Version of c:geo used:
2019.02.23

##### Is the problem reproducible for you?
Yes (for me) and reported via FB

##### System information:
Tested on my Samsung S7, Android 8.0

**Comment by Lineflyer** [comment]
Reason could(!) be, that targetSDK of the API code is different to the main app:
https://github.com/cgeo/cgeo/blob/master/mapswithme-api/build.gradle

**Comment by Lineflyer** [comment]
Well, the alignment of the sdk versions does not solve it, I changed it nontheless.

Interesting enough it work from the list view (Cache list -> Show on map -> Maps.me) but not from cache details (Cache details -> Navigate -> Maps.me). The debug log simply tells nothing.

Maybe someone with more code insights can take a look regarding the difference between the mentioned menu items/methods.

**Comment by bekuno** [comment]
I did not have this problem on devices Android 7.0 (Samsung S6) and Android 9 (samsung Note 8).
Maybe a system specific problem? Or only when there is no downloaded map in maps.me?

**Comment by Lineflyer** [comment]
> I did not have this problem on devices Android 7.0 (Samsung S6) and Android 9 (samsung Note 8).

Really? Also from cache details Navigation menu, not only from cache list?

**Comment by Lineflyer** [comment]
Addon:
Different from the sequence initially described, there is no need to have maps.me installed to see a problem. Even without this app being installed, there should be a message shown (see the API code of maps.me we are using) but it doesn't. 
So I guess the problem is within c:geo and not a problem of intent sending, etc.

**Comment by Lineflyer** [comment]
Could it be, that this line of code
https://github.com/cgeo/cgeo/blob/1fcabfb076b5b0ccc15992005c12d7013cc53849/main/src/cgeo/geocaching/apps/navi/MapsMeApp.java#L57

is somehow since SDK26 preventing maps.me being called at all?

@bekuno 
You wrote, that you do not have this problem on some devices...can you please doublecheck? I can reproduce the problem on Android 7 and 9.

**Comment by bekuno** [comment]
Here is a video showing my workflow: https://c.web.de/@321545400471263653/8GpOMPt4TBiKt1hDEvsI8A

**Comment by Lineflyer** [comment]
Thanks.
Indeed from map popup its working also for me. But please try from cache detail view.

**Comment by bekuno** [comment]
Here it does also for me not work. :-(

**Comment by bekuno** [comment]
> Could it be, that this line of code
> 
> https://github.com/cgeo/cgeo/blob/1fcabfb076b5b0ccc15992005c12d7013cc53849/main/src/cgeo/geocaching/apps/navi/MapsMeApp.java#L57

This is exact where the problem resides.
I haven't found anything that has changed since the last change in/at the call. (But maybe far away in the code ...)
So I assume the error already exists since then.
