### ISSUE TITLE
c:geo shows hidden divisons in cache description

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7344]
##### Detailed steps causing the problem:
- Open [GC83Z70](https://coord.info/GC83Z70) in c:geo and in browser

##### Actual behavior after performing these steps:
Comparing it you can see, that c:geo shows some elements of the cache description which are not shown in the browser.
These are division with e.g. the following syntax:
```divstyle="visibility:hidden;">N1247E2107</div>```

##### Expected behavior after performing these steps:
c:geo should show the same as the browser

##### Version of c:geo used:
2019.02.23

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Reported on support mail.
Other than with white text I am not sure, what is the reason c:geo is showing is.
Maybe someone can help to explain here or confirm it is a bug.

**Comment by rsudev** [comment]
c:geo does still only support a subset of html in displaying the cache description. So we had already cases where such things were visible easily in c:geo (e.g. white text). I consider this a feature...

**Comment by balu2003** [comment]
I agree with rsudev, it is not a bug it's a feature. If you want to solve nysteries, it is a great help that cgeo shows hidden elements, white text ...
Please don't fix it.
