### ISSUE TITLE
no cache list selection dialog 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7349]
##### Detailed steps causing the problem:
- open map (google or osm)
- select cache
- save to list

##### Actual behavior after performing these steps:
- cache is saved to default list without list selection dialog

##### Expected behavior after performing these steps:
- the list selection dialog should open

##### Version of c:geo used:
- latest from master
- 2019.02.23

##### Is the problem reproducible for you?
Yes.
Only on the Android 7 device.

##### Other comments and remarks:
Can one put me to the right place in the code to check it?

**Comment by rsudev** [comment]
There is a setting for this (in the offline data section). 
Are you sure it was set (which is the default, but nevertheless)?

**Comment by bekuno** [comment]
It was initial set.
After uncheck and check the dialog is back.
I will check the problem in the initialization.

**Comment by bekuno** [comment]
I don't know if it something works now other then before.
The situation is:
in preferences.xml the button is set:
        <CheckBoxPreference
            android:defaultValue="true"
            android:key="@string/pref_choose_list"
But in Settings.java the default value is false:
    public static boolean getChooseList() {
        return getBoolean(R.string.pref_choose_list, false);
    }
Later in 
Boolean v = (Boolean)mMap.get(key);
it searchs for defaults in mMap, but there are only 10 values, but nothing for pref_choose_list.
So it returns false.

@rsudev Can you check this with an older c:geo version?

**Comment by Lineflyer** [comment]
I cannot reproduce this, even with a freshly installed c:geo.

**Comment by bekuno** [comment]
Did you authorized to on of the GC services before testing it?
The problem is for me reproducible in the situation without authorization.
Now I tested with autorization and the list question occurs.
I will test the difference.

**Comment by Lineflyer** [comment]
> Did you authorized to on of the GC services before testing it?

Yes, probably I was already authorized.
