### ISSUE TITLE
update references to other APIs

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7350]
I did some research which of the referenced libraries could be updated.

The result was not great. (I expected nothing less).

Do we have a documentation for the dependencies? I found nothing in the wiki.
I think it would be easier to see what is necessary for Prepare for targetSdkVersion 28 (#7321).
Should I create such an overview, if yes - where?

**Comment by Lineflyer** [comment]
> Should I create such an overview, if yes - where?

I think the wiki might be the right place for such an overview.

**Comment by bekuno** [comment]
Many work is now already done by @Bananeweizen
