### ISSUE TITLE
Raise compile SDK version to 27

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#7354]
In general, the compile SDK version (currently 24) should greater or equal to the target SDK version (currently 26).

Which currently prevents us from directly updating the compile SDK version is the Google Maps v1 API.

**Comment by Lineflyer** [comment]
This is a task which should be done now inline with changing our targetSDK

**Comment by bekuno** [comment]
The targetSdk was updated to 27 with commit 3110366ca0550474b27dbd09109f31956501582d

**Comment by UniQP** [comment]
Then, we should raise the compileSdk to 27 as well. I adapted the PR title accordingly.

**Comment by moving-bits** [comment]
We are planning to move to targetSDK 28 soon (as it's required by Play store starting from November 2019), so maybe we should go to compileSDK 28 directly. (Don't know which referenced libraries are affected by this as well.)

**Comment by UniQP** [comment]
I would prefer the minimal solution first. We can still raise the compileSdk when we raise the targetSdk.
