### ISSUE TITLE
Icons not clickable on Google map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7358]
Found with a RC test version I created with the current state of the `release` branch on my Android 5.0.1 test device. Not tested other devices, but tested with release 2019.02.23 where the bug is not present.

##### Detailed steps causing the problem:
- Open Live Map / Google maps
- Click on any cache icon

##### Actual behavior after performing these steps:
Nothing happens, but error in debug log:
```
14:00:59.075 Error cgeo 5919  [main] GoogleMapView.onTouchEvent
14:00:59.075 Error cgeo 5919  android.view.InflateException: Binary XML file line #123: Error inflating class <unknown>
14:00:59.075 Error cgeo 5919  	at android.view.LayoutInflater.createView(LayoutInflater.java:640)
14:00:59.075 Error cgeo 5919  	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
14:00:59.075 Error cgeo 5919  	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
14:00:59.075 Error cgeo 5919  	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
14:00:59.075 Error cgeo 5919  	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
14:00:59.075 Error cgeo 5919  	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
14:00:59.076 Error cgeo 5919  	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
14:00:59.076 Error cgeo 5919  	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
14:00:59.076 Error cgeo 5919  	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
14:00:59.076 Error cgeo 5919  	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
14:00:59.076 Error cgeo 5919  	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:435)
14:00:59.076 Error cgeo 5919  	at com.android.internal.app.AlertController.installContent(AlertController.java:235)
14:00:59.076 Error cgeo 5919  	at android.app.AlertDialog.onCreate(AlertDialog.java:356)
14:00:59.076 Error cgeo 5919  	at android.app.ProgressDialog.onCreate(ProgressDialog.java:224)
14:00:59.076 Error cgeo 5919  	at android.app.Dialog.dispatchOnCreate(Dialog.java:463)
14:00:59.076 Error cgeo 5919  	at android.app.Dialog.show(Dialog.java:288)
14:00:59.076 Error cgeo 5919  	at cgeo.geocaching.activity.Progress.show(Progress.java:46)
14:00:59.076 Error cgeo 5919  	at cgeo.geocaching.maps.CachesOverlay.onTap(CachesOverlay.java:213)
14:00:59.076 Error cgeo 5919  	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.onTap(GoogleCacheOverlay.java:61)
14:00:59.076 Error cgeo 5919  	at com.google.android.maps.ItemizedOverlay.onTap(ItemizedOverlay.java:453)
14:00:59.076 Error cgeo 5919  	at com.google.android.maps.OverlayBundle.onTap(OverlayBundle.java:83)
14:00:59.076 Error cgeo 5919  	at com.google.android.maps.MapView$1.onSingleTapUp(MapView.java:358)
14:00:59.076 Error cgeo 5919  	at com.google.android.maps.GestureDetector.onTouchEvent(GestureDetector.java:562)
14:00:59.076 Error cgeo 5919  	at com.google.android.maps.MapView.onTouchEvent(MapView.java:685)
14:00:59.076 Error cgeo 5919  	at cgeo.geocaching.maps.google.v1.GoogleMapView.onTouchEvent(GoogleMapView.java:160)
14:00:59.076 Error cgeo 5919  	at android.view.View.dispatchTouchEvent(View.java:8981)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2698)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2410)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
14:00:59.077 Error cgeo 5919  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
14:00:59.077 Error cgeo 5919  	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2568)
14:00:59.077 Error cgeo 5919  	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1776)
14:00:59.077 Error cgeo 5919  	at android.app.Activity.dispatchTouchEvent(Activity.java:2866)
14:00:59.077 Error cgeo 5919  	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2529)
14:00:59.077 Error cgeo 5919  	at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.dispatchTouchEvent(MultiPhoneWindow.java:538)
14:00:59.077 Error cgeo 5919  	at android.view.View.dispatchPointerEvent(View.java:9186)
14:00:59.077 Error cgeo 5919  	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4706)
14:00:59.077 Error cgeo 5919  	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4544)
14:00:59.077 Error cgeo 5919  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
14:00:59.077 Error cgeo 5919  	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
14:00:59.077 Error cgeo 5919  	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
14:00:59.078 Error cgeo 5919  	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4201)
14:00:59.078 Error cgeo 5919  	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
14:00:59.078 Error cgeo 5919  	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4258)
14:00:59.078 Error cgeo 5919  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.ja
```

##### Expected behavior after performing these steps:
Popup should open

##### Version of c:geo used:
2019.03.11-RC
This problem does not exist with 2019.02.23 on the same device

##### Is the problem reproducible for you?
Yes, at least on the device mentioned below. Other Android versions not yet tested.

##### System information:
Samsung Galaxy S4 (GT-I9505)
Android 5.0.1

**Comment by Lineflyer** [comment]
@bekuno Could this be caused by setting `compileSdkVersion "Google Inc.:Google APIs:24` in https://github.com/cgeo/cgeo/commit/03e26776873fe1b2a00cc3d9d906c8982e07e585

**Comment by Lineflyer** [comment]
@bekuno 
As asked on IRC:
Android 6.0.1 (CyanogenMod) on Samsung S3 has the same problem.

Android 8 to be tested based on nightlies (where the change has been merged meanwhile) tomorrow.

**Comment by bekuno** [comment]
I testet with the latest nightly (2019-03-11) on Samsung Galaxy S6 (SM-G920F, Android 7.0) and Samsung Galaxy S3 (GT-I9300, Android 4.3). No problem, the cache description will open.

I don't know if this is raised by the compileSDK setting or another change. 
Or only a problem on this device/Android version or so. :-(

**Comment by bekuno** [comment]
Now a test with a HTC Desire 820 (Android 6.0.1).
No problem.

Is there a difference between nidhtly an RC?

**Comment by Lineflyer** [comment]
From IRC:

[22:45] <Lineflyer> bekuno Yes, your change will only be in tomorrows nightly as changes on release have only recently been merged to master
[22:45] <Lineflyer> So, retest tomorrow please.

**Comment by Lineflyer** [comment]
Same problem with freshly build nightly 2019.03.11-NB1 on my Samsung S7 with Android 8.0.

So it needs to be some change on branch `release` since last official release which is causing it.

**Comment by bekuno** [comment]
Same problem now on my test devices. :-(

**Comment by Lineflyer** [comment]
A user on version 2019.03.12-NB-0484cce also confirmed on social media, that caches on Google map are no longer clickable for him (Android 8).

**Comment by Lineflyer** [comment]
Reopened as the commit was reverted. It was not fixing the issue.

**Comment by Lineflyer** [comment]
@moving-bits Other changes on `release` are style fixes from your side.
Any idea?

**Comment by rsudev** [comment]
For me the fix for #7342 (pr #7348) is the first commit showing the problem

**Comment by Lineflyer** [comment]
@moving-bits See comment from @rsudev above.

**Comment by moving-bits** [comment]
> @moving-bits Other changes on `release` are style fixes from your side.
> Any idea?

Nothing springs to my mind instantly - need to diff the sources. But I won't be at my dev PC before tomorrow evening.

What PR 7348 in combination with PR 7357 does is:
- provide a new button styling for borderless buttons, based on our standard button styling
- provide a new AlertDialog theme based on Theme.AppCompat.Dialog.Alert with the new borderless button styling and our standard background
- switch progress dialog theme from being based on Theme.AppCompat.Dialog to the newly created AlertDialog theme [progress dialog theme is used for GPX Import eg]
- use this new AlertDialog theme for StoredList [which is used for the cache list management]

I don't see any direct relation to Google Maps functions, but maybe StoredList class is one, so if someone finds time to dive into this before tomorrow evening, this may be a starting point.

**Comment by moving-bits** [comment]
> For me the fix for #7342 (pr #7348) is the first commit showing the problem

PR 7348 was partly changed by PR 7357 due to some bottons not having borders any more after 7348.
I cannot retest this step by step as I don't have any v1 keys :-(

**Comment by bekuno** [comment]
You can test with the apk generated by a PR.

**Comment by rsudev** [comment]
You don't need real v1 keys to test anything. The map will just not show any map tiles if the keys are not real or do not match the signing key of the apk (AFAIK)

**Comment by rsudev** [comment]
The call stack shows that cgeo fails in creating an alert dialog due to an issue with inflating the (changed) alert dialog theme. The change itself does look innocuous enough but somehow seems to be the culprit nevertheless. It might be worth noting, that the google map activity does not derive from AppCompat (in contrast to the new map), not sure if this might play a role. If so, should the old mapsforge map probably exhibit the same behaviour.

**Comment by moving-bits** [comment]
@rsudev
Thanks for the additional analysis & hints. AppCompat may indeed be the problem in this case. I will dive into this tomorrow.

Is there any specific reason why Google Maps is not derived from AppCompat?

**Comment by mucek4** [comment]
I have 20y debug signing certificate with APIv1 keys. PM me if needed

**Comment by Lineflyer** [comment]
@moving-bits 
For better overview of who is investigating on what issue, feel free to use the assign feature of Github to assign you to the issue. So other people know you are working on it. 

I assigned you for this.

**Comment by moving-bits** [comment]
> You don't need real v1 keys to test anything. The map will just not show any map tiles if the keys are not real or do not match the signing key of the apk (AFAIK)

Thanks, but sadly, this does not work for me: I don't even get the choice for Google Maps when using the "map select" button. Neither with no key nor with a fake key. Will try with NB APK for now.

**Comment by moving-bits** [comment]
created a PR to fix the problem

Cause for the layout inflating problem was, that gmap uses a layout theme which is not derived from the standard c:geo theme and is incomplete (some attributes, see attr.xml, have no values in the gmap themes). This has not been a problem yet, as the undefined attributes have not been used in the gmap themes so far.

The new Alert_Dialog styling, introduced to fix other layout issues, makes use of the button styling, which itself needs two of those layout attributes. => This PR adds values for those two attributes in the two cgeo_gmap themes.
