### ISSUE TITLE
Backup created in sysinternal folder in first session

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7366]
##### Detailed steps causing the problem:
- Run c:geo
- Save some caches
- Perform backup
- Backup will be saved, according to the message, to "/data/user/0/cgeo...". 

User cannot find this path (no access from ES explorer), before it was creating backup in "/storage/emulated/0".

So there is not possibility to restore custom backup saved before.

##### Version of c:geo used:
Nightly, su, google market version. Seems like in every version after TargetSDK change

##### Is the problem reproducible for you?
No

##### System information:
```
--- System information ---
Device: MI 6 (sagit, Xiaomi)
Android version: 8.0.0
Android build: OPR1.170623.027
c:geo version: 2019.01.21
Google Play services: enabled - 15.0.90 (040408-231259764)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: ru_RU
System date format: dd.MM.y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (3,9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (3,9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (3,9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (19,8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   Geocaching.su: Logged in (Вход ОК)
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
Issue reported by friend of mine, he is getting this on his device. For me it seems fine, however due to potential impact, I'd like to report it here for further investigation.

**Comment by Lineflyer** [comment]
Did you grant c:geo the permission to access your storage?

**Comment by okainov** [comment]
According to my friend, c:geo hasn't asked him about storage permissions, because "it was ok".

Also from the system information I can see `Write external storage permission: granted`, so it should be fine

**Comment by Lineflyer** [comment]
> Also from the system information I can see Write external storage permission: granted, so it should be fine

This is not yet proven to work reliably after we added it some time ago.
Better check the app manager permission settings for c:geo.

**Comment by okainov** [comment]
Just got the very same issue on my device with build (su+master). However since I have root, I was able to access /data/user/0, but it's really weird. And I was asked about permissions and I did answer "Yes" for storage.

After couple of tries to backup\restore, backup switched for some reason back to /storage/emulated/0 and I was able to restore it successfully.

**Comment by okainov** [comment]
Still reproducible for master, maybe it happens only after first app run (when app asks for permissions), if one restarts app after that, seems to be ok

**Comment by Lineflyer** [comment]
@pstorch 

Seems our new permission request system somehow influences your implementation of how the default storage is selected. Maybe it is checked before the user actually gave his permission thus falling back to the system internal storage?!

**Comment by pstorch** [comment]
Yes, If the public directory is not writable (e.g. due to missing permission) it will fallback to the internal. See: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/storage/LocalStorage.java#L250

**Comment by okainov** [comment]
@pstorch  shouldn't be this line executed *after* dialogs with permissions?

**Comment by pstorch** [comment]
@okainov probably yes. As you see the variable "externalPublicCgeoDirectory" is cached. I guess this should be reevaluated after c:geo got the external file permission.
