### ISSUE TITLE
F-droid nightlies hung up after US time change

### ISSUE THREAD

**Issue by ithink314** [cgeo/cgeo#7367]
##### Detailed steps causing the problem:
- Step 1 Open F-droid, nightly repository
- Step 2 refresh
- view c:geo version list

##### Actual behavior after performing these steps:
Newest version is 2019.3.10-NB-...

##### Expected behavior after performing these steps:

New version every night, even after US clocks spring forward (2am 3/10/2019).

##### Version of c:geo used:

N/A

##### Is the problem reproducible for you?
Yes, every day since

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

See #6294 #5219 
##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
I can see no clue about why it would not work.
Is the packet source for the nightly the same like for the normal release (fdroid.cgeo.org) ?

**Comment by ithink314** [comment]
Permissions issue?

Repository links/locations:

https://fdroid.cgeo.org
https://fdroid.cgeo.org/nightly

1 in browser gives message about not for browsing.
2 gives 403 forbidden?

**Comment by Lineflyer** [comment]
https://fdroid.cgeo.org/nightly is working for me in f-droid.
I can see version 2019.03.15-NB1-1dbfca6 as newest version.

**Comment by ithink314** [comment]
I've been using f-droid 1.6-alpha1. I'll downgrade to 1.5.1 and see if that helps.

**Comment by ithink314** [comment]
Did Force Close and Clear memory of f-droid, then re-add c:geo nightly repository. Now it shows the newest.

Apparently this was a problem with f-droid client. Sorry for the distraction.

**Comment by Pitel** [comment]
I just nticed that. Disabling and reenabling cgeo nightly repo in fdroid solved the issue.
