### ISSUE TITLE
custom task named 'wrapper' has been deprecated

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7382]
in "Configure project "

Creating a custom task named 'wrapper' has been deprecated. This is scheduled to be removed in Gradle 5.0. You can configure the existing task using the 'wrapper { }' syntax or create
 your custom task under a different name.
        at build_w5tx7p2bosgsq4d6b4f13ifv.run(C:\StudioProjects\cgeo\build.gradle:186)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

**Comment by Lineflyer** [comment]
@bekuno 
It would be helpful if you also set an appropriate label when opening an issue. That's not mandatory but helps a bit to keep the overview and sort/filter later on, therefore I would recommend it.
I set label "Build tools" as it seems matching.

Also not forget to assign yourself if you plan to work on it or are already working on it. This helps to avoid someone else picking it up at the same time.

If you can't set labels or assignment, let me know. Then something with your repo access rights is not ok. :)
