### ISSUE TITLE
Open map from address search shows routing line

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7386]
Testing the change from #7228 (Add icon to address search to show on map) I noticed that on the opened map the routing line with beginn or target(?) to map center will be shown on the opened live map.

I don't think this is useful and helpful and maybe not even intentionally done?!

**Comment by moving-bits** [comment]
Whether the red line is shown or not depends on your map settings "show direction line". That's a line from your current position to the position you have selected after your search by location. AFAIK I cannot influence this when calling the map.

**Comment by Lineflyer** [comment]
IMHO it was so far always bound to an object (WP, cache) but not just purely on coordinates on the map.
