### ISSUE TITLE
Starting from live map widget crashes the app

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7391]
##### Detailed steps causing the problem:
- Create a new widget on your device "desktop" with the function "live map"
- Make sure c:geo is not running in background (exit completely / hard close)
- Click the live map widget

##### Actual behavior after performing these steps:
Immediate crash

##### Expected behavior after performing these steps:
Live map shall be started.
(It works only if c:geo was active before and is still in background tasks)

##### Version of c:geo used:
2019.02.23

##### Is the problem reproducible for you?
Yes

##### System information:
Samsung S7, Android 8.0

**Comment by Lineflyer** [comment]
Can provide a debug log tonight.

**Comment by okainov** [comment]
Solution - remove any widgets support from c:geo as outdated? Less legacy code =)

**Comment by Lineflyer** [comment]
Why do you call them legacy? I use them quite often (for list access) and a lot of users use them.

**Comment by okainov** [comment]
@Lineflyer for sure I'm maybe exaggerating, but I personally haven't ever used any widgets from c:geo and I barely can see a reason for it, since c:geo doesn't do any notifications (which one may want to see on a widget), it requires the full app to do any meaningful actions... 
Or maybe it's just yet another argument to have\implement\check usage statistics on more detailed level, so you can be certain about number of people using features X and Y.

**Comment by Lineflyer** [comment]
Understood.
In fact these "widgets" are actually no real widgets but shortcuts to start c:geo directly into a certain activity. Quite handy feature IMHO.

**Comment by Lineflyer** [comment]
Here is the debug log of the action described above:
```
14:51:13.203 Warning cgeo 6791  [main] UncaughtException
14:51:13.203 Warning cgeo 6791  java.lang.RuntimeException: Unable to resume activity {cgeo.geocaching/cgeo.geocaching.maps.google.v1.GoogleMapActivity}: java.lang.NullPointerException: source1 is null
14:51:13.203 Warning cgeo 6791  	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
14:51:13.203 Warning cgeo 6791  	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434)
14:51:13.203 Warning cgeo 6791  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
14:51:13.203 Warning cgeo 6791  	at android.app.ActivityThread.access$900(ActivityThread.java:177)
14:51:13.203 Warning cgeo 6791  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
14:51:13.203 Warning cgeo 6791  	at android.os.Handler.dispatchMessage(Handler.java:102)
14:51:13.203 Warning cgeo 6791  	at android.os.Looper.loop(Looper.java:145)
14:51:13.203 Warning cgeo 6791  	at android.app.ActivityThread.main(ActivityThread.java:5951)
14:51:13.203 Warning cgeo 6791  	at java.lang.reflect.Method.invoke(Native Method)
14:51:13.203 Warning cgeo 6791  	at java.lang.reflect.Method.invoke(Method.java:372)
14:51:13.203 Warning cgeo 6791  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
14:51:13.203 Warning cgeo 6791  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
14:51:13.203 Warning cgeo 6791  Caused by: java.lang.NullPointerException: source1 is null
14:51:13.203 Warning cgeo 6791  	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
14:51:13.203 Warning cgeo 6791  	at io.reactivex.Observable.combineLatest(Observable.java:433)
14:51:13.203 Warning cgeo 6791  	at cgeo.geocaching.sensors.GeoDirHandler.start(GeoDirHandler.java:111)
14:51:13.203 Warning cgeo 6791  	at cgeo.geocaching.sensors.GeoDirHandler.start(GeoDirHandler.java:77)
14:51:13.203 Warning cgeo 6791  	at cgeo.geocaching.maps.CGeoMap.onResume(CGeoMap.java:528)
14:51:13.203 Warning cgeo 6791  	at cgeo.geocaching.maps.google.v1.GoogleMapActivity.onResume(GoogleMapActivity.java:68)
14:51:13.203 Warning cgeo 6791  	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
14:51:13.203 Warning cgeo 6791  	at android.app.Activity.performResume(Activity.java:6412)
14:51:13.203 Warning cgeo 6791  	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3392)
14:51:13.203 Warning cgeo 6791  	... 11 more
```

Of course resuming fails, as there is nothing to resume....why is it trying to resume when using this widget?

**Comment by rsudev** [comment]
Resume is always a step in the lifecycle of any activity. The issue is, that the location provider likely is not started on this shortcut into the app. I thought I checked all of those when addressing the open issues for targetSdk26, but obviously I missed some.
