### ISSUE TITLE
Add usage statistics

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7393]
Surprisingly, I was not able to find it across other open issues.

Since c:geo is quite a big app with dozens of different features and activities, I think it makes a lot of sense to have some kind of "usage statistics" implemented to be able to certainly discuss about removing old features \ directions of implementing new ones. Not always app is used in the same way as developers thought, often it can be quite opposite :)

From recent examples, it can be #7332 or widgets usage - the decision to remove feature X or Y will be much more deliberate if you definitely know that 0 users are using feature X.

**Comment by Lineflyer** [comment]
I remember discussions about using GoogleAnalytics and some other similar service, but finally the team decided against it. 
I think if it is based on our status-server we could technically do it without to much concern. 
However I do not see the need to remove features based on user statistics at the moment. Not sure if I would be a friend of such a concept, although I get your point of understanding how users use the app.

**Comment by moving-bits** [comment]
It's also about where we should put our effort in. If there is a complicate to support feature, which is seldom used, we may drop or ignore it. OTOH if a feature is widely used, we should priorize bugfixes for that etc.
Only example from the younger past is dropping Android 4.0 support. We got to know by measuring that only 113 users were affected (out of > 10.000 at peak times), so it was fair to do so.

**Comment by okainov** [comment]
>but finally the team decided against it.

@Lineflyer  do you remember the reasoning behind? Except of "don't be evil and don't spy on users". Do you want to reconsider this in the nearest future?

**Comment by Lineflyer** [comment]
The reason was one one hand the "dont spy" thing but also when it came to Google Analytics we considered it to be problematic to give such kind of data to third parties. With an own implementation at least the second argument is no longer valid.

**Comment by rsudev** [comment]
I think such a usage tracking is more work than it is worth. As we are no profit-oriented company which needs to report strategies to grow the user base to the board of investors, but a volumteer-driven open-source effort, in the end WE as the contributors decide what we implement and what we leave out. And the feedback we receive through issues, social media and direct interaction with fellow geocachers is in my opinion sufficient feedback and is 'free'.

**Comment by bekuno** [comment]
I am no friend of (user) tracking. So let the data for the statistics be small.
Maybe cool things are unused because user find not the point or the way to use it.
Better is to have a good documentation. (so we can say: RTFM :-))
(By the way - is the extended support for gc.su on the way to the documentation?)

**Comment by Bananeweizen** [comment]
When you add such a logging framework to the tool, you suddenly have quite some additional work:
* host a backend for the analytics (you don't really want to have facebook or google store that data)
* update privacy policy and similar things to correctly reflect what you do
* have users agree in a legally correct way
* make it GDPR compliant
* trigger it in your code to actually record import values (In the very beginning, cgeo had such logging. When we removed it, that was a 4 digit number of lines of code.)
* actually aggregate the collected data and draw some conclusions

Really don't underestimate the effort. And then compare that to the expected benefit. Also, do you really think that there were some technical issue, where we would decide _different_ when having such data, compared to what we decide based on gut feeling?

**Comment by Lineflyer** [comment]
There seems to be no majority here for such an approach, therefore closing.

> By the way - is the extended support for gc.su on the way to the documentation

Will open an issue on the website repo to add it to the user guide (which itself is not hosted on Github)

**Comment by fm-sys** [comment]
I just stumbled across this (rather old and closed) issue and would like to voice one more idea. Not that it is in any way urgent but more for the sake of completeness: 
Instead of tracking user behavior (which I wouldn't support in any way), we could think about creating voluntary surveys for the usage of certain features. This doesn't even require changes to the source code. We would just need to post a message via c:geo's notification system linking to the survey.
