### ISSUE TITLE
cache list selector does not respect light theme setting

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7394]
##### Detailed steps causing the problem:
from IRC: List selection dialog (when saving a cache) should respect the dark or light theme setting in all aspects.

##### Actual behavior after performing these steps:
Currently it always does have a dark background, and only button text coloring adjusts to theme setting.

![image](https://user-images.githubusercontent.com/3754370/54558020-e9ff1b00-49bc-11e9-9b06-ae2843cdf767.png)

##### Expected behavior after performing these steps:
Theme setting should be honoured to full extend.

![image](https://user-images.githubusercontent.com/3754370/54558122-2f234d00-49bd-11e9-81ee-e75081c2f066.png)

##### Version of c:geo used:
release 2019-02-23 works / current master doesn't

##### Is the problem reproducible for you?
Yes

**Comment by Lineflyer** [comment]
@moving-bits Feel reminded to apply labels to new issues. I did it for this one up to my best knowledge.

**Comment by moving-bits** [comment]
> @moving-bits Feel reminded to apply labels to new issues. I did it for this one up to my best knowledge.

@Lineflyer Thanks for adding. I'm still not used to all those extra functions GitHub offers me now :-)
