### ISSUE TITLE
GCVote ratings shown fot gc.su caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7396]
##### Detailed steps causing the problem:
- Save gc.su caches
- List shows colored items representing gcvote ratings
- Open a certain cache which has rateing color in the list

##### Actual behavior after performing these steps:
The cache details show a gcvote rating (stars) and amount of users voted behind

##### Expected behavior after performing these steps:
Not sure...but IMHO gcvote only supports gc.com up to now

##### Version of c:geo used:
2019.03.18-NB1

##### Is the problem reproducible for you?
Yes

##### System information:
Samsung S7, Android 8.0

**Comment by okainov** [comment]
>Not sure...but IMHO gcvote only supports gc.com up to now

I'm neither =) Anyway, we have our own voting on SU and cache rating from SU should be shown

**Comment by okainov** [comment]
Oops, sorry, I misread the text somehow. We *do* show rating of the cache, because we *do* have rating at gc.su. However this rating is *not* gcvote rating.

**Comment by Lineflyer** [comment]
Ah...then it works good.
Does this rating system have the same parameters as gcvote.com (i.e. rating between 0 and 5, etc.). In that case IMHO the implementation is nice.. One could confuse it with gcvote but I guess the technical background is not important for most users.

Is posting rating already suported with your implemenation?

**Comment by okainov** [comment]
>Is posting rating already suported with your implemenation?

No, see https://github.com/cgeo/cgeo/issues/7182

**Comment by Lineflyer** [comment]
Thanks!
