### ISSUE TITLE
Does geokrety suport gc.su waypoints?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7398]
Sorry for this issue.
Just want to record what comes to my mind when first testing the new gc.su implementation:

I do see, that if the GeoKrety connector is active there are requests sent to it for gc.su caches (e.g. get inventory, list the GK inventory in logging window to interact with those caches).

I did not yet try to send a POST to geokrety.org with these waypoints, however the GET with gc.su waypoints respond normally.

@kumy

**Comment by kumy** [comment]
gc.su and GK should not be a problem. @okainov and I already worked together to fix some cache synchronization. It was in https://github.com/geokrety/geokrety-website/issues/138.

@Lineflyer thanks for taking care of this :+1:

**Comment by Lineflyer** [comment]
Indeed..works nice:
![grafik](https://user-images.githubusercontent.com/949669/54566354-e8d7e900-49d0-11e9-83f5-a48397ee390b.png)

**Comment by kumy** [comment]
I was in doubt and double checked, but hopefully it was already documented https://geokrety.org/help.php#fullysupportedwaypoints

> TR/VI/MS/EX.... -- GeoCaching Russia -- updated every two hours (lat, lon, cache name, link, owner)

**Comment by okainov** [comment]
@Lineflyer general Geokrety support is in place and should work fine.
However from c:geo point of view, it would be really nice of you if you could try test **placing** geokrets **from c:geo into su cache**. I was not doing anything from code point of view there and I'm even not sure that it will work, but if it will (by some magic), it would be really great.

**Comment by kumy** [comment]
FI, current GK implementation in c:geo uses GK API to post logs and not "caches-connectors" features.

**Comment by Lineflyer** [comment]
@okainov 
Dropped one of my GK to one of your caches without a problem.
I will leave it there for some time in case you want to test something.

https://geokrety.org/konkret.php?id=64629

**Comment by okainov** [comment]
@Lineflyer Thanks. But seems there is no "Inventory" feature, right? Probably will need to take a look and implement this in connector?

**Comment by Lineflyer** [comment]
I will answer next days. reopen for now. Now off to bed :)

**Comment by Lineflyer** [comment]
@okainov 
If you have the geokrety connector active the inventory works fine also with gc.su caches.
Please be aware, that by default it uses a proxy (geokretymap.org) due to its better performance. But this proxy has a bit delay compared to geokrety.org itself (needs some minutes-hours to reflect the new inventory).
If you take a look at MS21372 now, it will show my Geokret on the inventory tab.

So IMHO all works as intended here. Great!
