### ISSUE TITLE
Cache status not reset after found log deleted

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7399]
##### Detailed steps causing the problem:
- Post find log for a cache on gc.su
- Open the website and delete the found log
- Refresh the cache in cgeo

##### Actual behavior after performing these steps:
Found log is deleted also in cgeo, but status in cache details is still "Found"

##### Expected behavior after performing these steps:
Cache status should no longer be found

##### Version of c:geo used:
2019.03.18-NB1

##### Is the problem reproducible for you?
Yes  - not sure if any caching on server side is involved

##### System information:
Samsung S7, Android 8.0

##### Other comments and remarks:
Not very realistic, but still it should be working

**Comment by Lineflyer** [comment]
FYI: Total find count on main screen does also not correct (after new login).

**Comment by okainov** [comment]
@Lineflyer Server side is involved. In contrast with gc.com, where log **is** the main thing, on su you can mark cache as found without log. ATM our log is something secondary. And when you remove log, "found"status is not removed. You can check it by clicking on happy yellow star on cache page - this will show you list of all people who've found the cache.

To remove cache from found you need more complicated actions:
- Go to "account" page https://geocaching.su/members/
- Click "Found caches" / "Найденные мной тайники"
- Find the cache you want to remove in the list, put a checkbox on the left
- Scroll to the bottom and click "Unmark selected as found"/"Удалить отмеченные тайники из списка/

**Comment by Lineflyer** [comment]
Thanks, understood. An unusual approach but fair enough :)
I will try to find a page translator to navigate around there....a bit difficult if you dont speak/read Russian.
