### ISSUE TITLE
inconsistent distance calculation when using multiple connectors

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7400]
##### Detailed steps causing the problem:
- have gc.com and oc.nl connectors active (may work with other combinations as well)
- do a "search by location" from main screen for a location which is far away from your current location [my emulator is set to N37.6 W122.8, and I was searching for "Köln"]

##### Actual behavior after performing these steps:
- found caches from gc.com connector show a distance relative to the center of the search ("Köln")
- whereas caches returned by the oc.nl connector show the distance relative to my current location [N37.6 W122.8 in the example]

##### Expected behavior after performing these steps:
- I don't know which way is the more expected way, but at least it should be consistent

##### Version of c:geo used:
- today's master

##### Is the problem reproducible for you?
Yes

##### System information:
- Android Studio emulator / API 26

![image](https://user-images.githubusercontent.com/3754370/54587886-b60a1100-4a21-11e9-9e33-53907fc3f866.png)

**Comment by Lineflyer** [comment]
This is kind of a "false find":
You seem to be using gc.com as basic member, which means, that the search result will not contain coordinates (BM restriction as they cannot access the *.LOC file on the search result page, which we use to obtain the caches coordinates).
Instead c:geo uses the distance information and direction graphic shown on the search result (that why it is preceded with `~`).

In general (and for PM users) the result window in c:geo will always show the distance from current location.

There is already some feature request out here to instead relate to search center in case the list view is opened from a location search....but that's a different story.

**Comment by moving-bits** [comment]
Ah, yes, you're right. I was using my developer BM account in the VM.
Thanks for clarification, I'm always learning something new.
