### ISSUE TITLE
Wrong field notes encoding

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#7404]
##### Detailed steps causing the problem:
- Export logs as field notes

##### Actual behavior after performing these steps:
File is encoded as UTF-16 Big Endian.

##### Expected behavior after performing these steps:
File should be encoded as UTF-16 **Little** Endian.

##### Version of c:geo used:
unknown

##### Other comments and remarks:
Report from user with sample field notes file.

**Comment by Lineflyer** [comment]
> File should be encoded as UTF-16 Little Endian.

Just out of curiosity....why should it be little endian?

**Comment by SammysHP** [comment]
Not easy to answer as there is not much documentation available.

https://forums.geocaching.com/GC/index.php?/topic/241595-field-notes-file-format/

We should also check what older Garmin GPS receivers use.

**Comment by Lineflyer** [comment]
From FB:

Just now getting around to posting an issue I ran into back in February involving the Export Field Notes function.

Without going into all the gory details (which can be found in the thread I posted on the GSAK FB page on Feb 10th) it would appear that on about February 10th, c:geo began encoding these exports as Unicode big endian.  

This is probably transparent to most users, but in my case it rendered the files unusable as imports to GSAK, owing to all the 00 bytes (clearly visible when using a hex editor to examine the files). 

At first I suspected it might be the result of an Android update (I have a Galaxy S9) but I was able to recreate the problem using my old Galaxy S5 as well. Finally, I ruled out the Android as the problem when I was able to export files from other apps on the phone and they were not encoded as Unicode big endian. 

If this behavior is indeed the result of a change within c:geo, I hope it can be reversed. The only reason I can think of that it is now this way is to allow emoji or foreign language character support, but I do understand there could be other reasons.

**Comment by Bananeweizen** [comment]
Since I have no debugger at hand right now, I only checked the related files. There are no changes I can correlate. FieldNotes, FieldNoteExport, FileUtils are all unchanged since a long time. commons-io as library doing the file writing also unchanged since 2017. Seems someone needs to really debug into this...

**Comment by Lineflyer** [comment]
Could be related (from support mail today):

With the update to pie, c:geo is no longer exporting a valid Field Notes txt file.  Everything looks like it did yesterday, but it is not recognized by GSAK as a valid txt file.  I have uploaded the Field Notes to GSAK for the last 4479 days in a row and today with the new Android update, it doesn't work.

**Comment by jakedot** [comment]
Little/big endian encoding? UTF-8 BOM? Probably not if you already checked, but smart editors can be deceiving...

**Comment by Lineflyer** [comment]
For documentation:

Some people contacting our support with a similar or the same(?) problem:
They used c:geo field notes in conjunction with GSK in the past without problem, but since changing their devices to a more recent Android version (Android 8.1, Android 9) they are not able to import the field note file to GSAK (GSAK Error 307).

**Comment by Lineflyer** [comment]
I tried to take a closer look into it (without being any expert for file encoding), but I got no real clue.

According to @SammysHP our field note file should at the moment be encoded as UTF-16 BE. However with whatever method I transfer it to my PC, my smart editor (PS Pad Pro) on the PC is always showing me, it is a UTF-8 file.

**Comment by Lineflyer** [comment]
I received two field note files which the user produced on two different devices (with same content).
A basic (windows) file compare shows the "expected" difference:
```
Vergleichen von 20190626172443.txt und 20190626172551.txt...
Unterschied festgestellt bei OFFSET 0
Datei1 = FF
Datei2 = FE
Unterschied festgestellt bei OFFSET 1
Datei1 = FE
Datei2 = FF
Unterschied festgestellt bei OFFSET 2
Datei1 = 47
Datei2 = 0
Unterschied festgestellt bei OFFSET 3
Datei1 = 0
Datei2 = 47
Unterschied festgestellt bei OFFSET 4
Datei1 = 43
Datei2 = 0
Unterschied festgestellt bei OFFSET 5
Datei1 = 0
Datei2 = 43
Unterschied festgestellt bei OFFSET 6
Datei1 = 37
Datei2 = 0
Unterschied festgestellt bei OFFSET 7
Datei1 = 0
Datei2 = 37
Unterschied festgestellt bei OFFSET 8
Datei1 = 30
Datei2 = 0
Unterschied festgestellt bei OFFSET 9
Datei1 = 0
Datei2 = 30
10 Unterschiede - Vergleich beendet
```

**Comment by Lineflyer** [comment]
Devices used for the field note creation in my previous post:
Device 1 (Field note not working with GSAK):
```--- System information ---
Device: SM-M205FN (m20lteeea, samsung)
Android version: 8.1.0
Android build: M1AJQ.M205FNEEU1ASD3
c:geo version: 2019.06.06
Google Play services: enabled - 17.4.55 (040400-248795830)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (44,4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (44,3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (44,3 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (8,0 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

Device 2 (Field note working with GSAK):
```
--- System information ---
Device: T03 (T03_emea_gen1, acer)
Android version: 5.1
Android build: Acer_AV0L0_T03_1.030.00_EMEA_GEN1
c:geo version: 2019.06.06
Google Play services: enabled - 17.4.55 (020306-248795830)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.y
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (1,4 GB free) internal
User storage c:geo dir: /storage/sdcard0/cgeo (1,3 GB free) external non-removable
Geocache data: /storage/sdcard0/Android/data/cgeo.geocaching/files/GeocacheData (1,3 GB free) external non-removable
Database: /storage/sdcard0/Android/data/cgeo.geocaching/files/databases/data (152,0 KB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: d. M. yyyy
Installed c:geo plugins: contacts
--- End of system information ---
```

I requested the information which field note file is from which device, but I suspect (according to the BE / LE discussion above) that File 2 (DATEI 2) is from the problematic device (i.e. using BE).

**Comment by Lineflyer** [comment]
> I requested the information which field note file is from which device, but I suspect (according to the BE / LE discussion above) that File 2 (DATEI 2) is from the problematic device (i.e. using BE).

Confirmed by the user.

**Comment by Lineflyer** [comment]
In this code line
https://github.com/cgeo/cgeo/blob/1fcabfb076b5b0ccc15992005c12d7013cc53849/main/src/cgeo/geocaching/utils/FileUtils.java#L413

we explicitly set UTF16 to be used which implies BE according to https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/Charsets.html#UTF_16

We could set it to LE according to http://commons.apache.org/proper/commons-lang/javadocs/api-3.9/org/apache/commons/lang3/CharEncoding.html

but in fact all of that is listed as depracted.

Still the question remains why older Android versions deliver LE and if we make things worse on other devices by changing the encoding to LE.

**Comment by Pprime1** [comment]
I am no programmer, so shan't be adding much in the way of a solution - but I can confirm this issue. On my Samsung Note 10 the text file of field notes created for exporting shows up with two spurious characters at the beginning. And the file does not load into GSAK (307 error - no data found). But if I copy the actual text out of the file into a fresh text file (on a PC) and then try to load that one ... success! This was not an issue on my old Samsung Note 4 (which I no longer have access to sadly). I would have had an older release of c:Geo back then, but I would concur it seems to be a phone issue (since Android Pie makes sense to me here).
I tried just re-saving it (in Notepad) to any other format (It starts as Unicode Big Endian as stated above). But just changing the encoding to the other options made no difference, I also find the idea of copying the text to a new file also usually fails. I have to retype parts of every line usually.
I would support testing of any proposed solution anyone cleverer than I can come up with.

**Comment by moving-bits** [comment]
Also see https://github.com/cgeo/cgeo/issues/8230#issue-602787872

**Comment by UniQP** [comment]
@SammysHP Can you test whether the issue still exists in the latest nightly?

**Comment by SammysHP** [comment]
@UniQP 
As far as I remember I didn't have this issue on my device. Someone who was able to reproduce this should check it again.

**Comment by Lineflyer** [comment]
According to feedback in #8230:

nein leider klappt es nicht, es erscheint der gleiche Fehlercode wie unten bei der Release Version von Anfang Juli.

Bug still present in 2020.07.26-RC which should contain the charset library changes done by @UniQP already.

**Comment by Pprime1** [comment]
I can confirm this is still an issue for me, although i have a bit of a routine now. I export the field notes, i then use file manager in the phone to copy the text file to my cloud drive (onedrive ... wonder if i could log a feature request to export direct to a predefined location?). 
Then on my PC I open the text file and then File-save-as, change the encoding from UTF-16BE to ANSI, and replace the file.  It all works in gsak now.
If we could force save the export as ANSI (even if only when saving to a custom location?) ... i would be even happier than I am usually.

Hoping this little bug is bumped up the list for one of you clever programmers.

**Comment by eddiemuc** [comment]
I am confused.

Looking into code I can see that field notes are exported explicitely using UTF 16 encoding:

https://github.com/cgeo/cgeo/blob/485e4f99ec60e51d7d50709e1a0824d2a8c8313b/main/src/cgeo/geocaching/export/FieldNotes.java#L50-L60


According to @Pprime1 UTF-16 is not working though.

Is there anyone knowing which encoding is actually needed for field notes? Maybe @UniQP ?

**Comment by bekuno** [comment]
In `FileUtils.writeFileUTF16` we call
`org.apache.commons.io.FileUtils.write(file, content, StandardCharsets.UTF_16);`
If you see at https://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html
the byte order for UTF_16 is defined by `Sixteen-bit UCS Transformation Format, byte order identified by an optional byte-order mark`. Hmm. But we can instead use the explicit UTF_16LE format.

**Comment by eddiemuc** [comment]
@bekuno sorry for my dumb questions, but where is it defined that the format has to be UTF_16LE (or which other encodings are allowed)? Tried to google it but was not successful.

**Comment by bekuno** [comment]
@eddiemuc 
No dumb question.
Please see the first 4 comments in this issue.
No one knows a documentation for the field notes format, but all comment say that the big endian format does not work.

**Comment by eddiemuc** [comment]
If field notes are working in UTF16LE then PR #9491 will solve this problem

**Comment by Lineflyer** [comment]
A beta user confirmed that field note import from c:geo to GSAK is working again with 2020.12.22-RC.

**Comment by rsudev** [comment]
Just to complete the picture (and preserve the information): In spite of the API documentation did the various file write methods we used in the past store the data as UTF16-LE on older Android platforms (I have Android 7.1 and a collection of field notes files from 2017 up to last year December. All of them are stored as UTF16-LE with BOM).

**Comment by gcbor** [comment]
I am on Android 9 and with c:geo 2021.02.14 the field notes are now getting stored as UTF-16 LE without BOM.
It would really be good to add the BOM U+FFFE for UTF-16 LE at the begging of the field notes.
