### ISSUE TITLE
Cache refresh window has no borders anymore

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7434]
Since the recent layout change of the cache refresh window (shown after you e.g. selected to refresh a cache) and other similar dialogs their are looking better in general, but they do no longer have any visual border.

This makes them look melted into the (also black) background. A visual seperation in form of a small greyish border would be appropriate.

This is only an optical issue.
2019.03.29-NB
Android 8.1

Can add a screenshot later, if the meaning is unclear.

**Comment by moving-bits** [comment]
Meaning is clear, I've seen it as well, meanwhile.
