### ISSUE TITLE
"Sort Caches by Favorite [%]" gives weird result

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7436]
##### Detailed steps causing the problem:
- Open Live Map at any point (caches NearBy may end up with same result)
- wait until "Show as List" is active
   (BTW: Anything new concerning the busy spinner in Live Map? - I'm missing it *really* badly, esp. as newly loaded caches still have the tendency to vanish after half a second, so you have to stare at the map all the time, otherwise you miss the moment to realize that loading has finished)
- select "Show as List"
- sort by "Favorite [%]"

##### Actual behavior after performing these steps:
- the order of the list seems to be completely messed up (see attached screenshots)

##### Expected behavior after performing these steps:
- caches with 0 favos should not be listed above caches that already have favorite points (although number of logs is poss. not available at this very moment)
- when there are offline saved caches in the list, these should be listed first, as their favo % can be calculated based on (real) offline data (can not reproduce right now, but I'm pretty sure that I already had offline saved caches somewhere in the middle of the list and even beneath 0 favo caches)

##### Version of c:geo used:
- 2019.03.30-NB1-4c5da32

##### Is the problem reproducible for you?
- Yes

##### System information:
```
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2019.03.30-NB1-4c5da32
Google Play services: disabled - 15.0.90 (040408-231259764)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (6,9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (6,9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (6,9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (235,8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

##### Other comments and remarks:
I know that the order by favo % can just be a guess as long as the number of logs is unknown, but as long as the possibility of sorting by favo % is given (and I would leave it as it is, for the same reasons, Bananeweizen has already stated in #3400), it should at least be an educated guess and esp. comprehensible by the user (who would not expect a cache with 20 favos sorted to the end of a list, where all others [seemingly] have 0 favos).

Possible improvement: Show [?] favos instead of [0], as long as the real number is unknown (perhaps the favo count can be initialized with -1, which then shows  up as "?" in the list).

**Comment by MagpieFourtyTwo** [comment]
![Sort 1](https://user-images.githubusercontent.com/9889015/55277839-bc8f6700-5304-11e9-9923-0e9074ba8d45.jpg)
![Sort 2](https://user-images.githubusercontent.com/9889015/55277840-be592a80-5304-11e9-81ac-58910ecf0015.jpg)

**Comment by okainov** [comment]
>Possible improvement: Show [?] favos instead of [0], as long as the real number is unknown (perhaps the favo count can be initialized with -1, which then shows up as "?" in the list).

As for me this makes perfect sense, I wonder why wasn't it fixed long time ago. See #7439

Also I played with the order a bit, looks like list sort is not being updated after saving some new caches, thus it can lead to weird order (as shown on your screenshot)

**Comment by Lineflyer** [comment]
The problem here could AFAIK be, that for those caches not saved offline we have the amount of favorite, but we do not have the amount of finds (as we do not have logbook info at this point).

**Comment by Lineflyer** [comment]
> we have the amount of favorites

Have to correct myself:
We do not have them, only in case of implicit nearby search is performed while map is being populated.

**Comment by Lineflyer** [comment]
@okainov This should be implicitly solved by defining an unknown favorite count, right?

**Comment by okainov** [comment]
@Lineflyer yep, it should have been fixed :)

**Comment by MagpieFourtyTwo** [comment]
Sorry, but I don't get it - perhaps you can explain to me, why this is considered to be solved ...

Cause as far as I would say right now (with current nightly), sort by favo % still looks strange (with caches, not saved offline, of course), as some caches with no favos at all are still listed above caches that have one or even a bunch of favos - which is definitely wrong. And can even be said without knowing the effective number of logs, cause even 1 favo *always* gives a higher percentage than 0 favos, no matter how many logs there are.

So, if the improper sort, which I currently see, is for real a consequence of the unknown number of logs, I would suggest to introduce the favo count as second sort key, to at least get the ones with favos listed above the ones without favos at all - which may be a little bit more comprehensible to the users looking at this list.
