### ISSUE TITLE
App crashes on specific OC caches

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7437]
##### Detailed steps causing the problem:
- Enable oc.de service
- Try to search by geocode for OC134AC
- App crashes\hangs during loading

##### Version of c:geo used:
master

##### Other comments and remarks:
Crash is at line 524 in `OkapiClient.java`, line
`            cache.setAttributes(parseAttributes((ArrayNode) response.path(CACHE_ATTRNAMES), (ArrayNode) response.get(CACHE_ATTR_ACODES)));`

Exception

     Cannot cast 'com.fasterxml.jackson.databind.node.ObjectNode' to 'com.fasterxml.jackson.databind.node.ArrayNode'

`response.get(CACHE_ATTR_ACODES).toString()` is 
`{"0":"A19","1":"A33","2":"A34","3":"A37","5":"A30","6":"A58","7":"A39","8":"A44","9":"A47","10":"A13","11":"A71"}`

Seems pretty obvious that dictionary cannot be casted to array/list. I wonder, am I the first one who noticed?

**Comment by okainov** [comment]
From OKAPI doc https://www.opencaching.de/okapi/services/caches/geocache.html

> attr_acodes - unordered list of OKAPI geocache-attribute IDs (A-codes) with which the cache was tagged. Use the attrs module to retrieve information on these attributes.

Suspicious....

**Comment by Lineflyer** [comment]
Are you sure about the OC-code? For me its not existing.

**Comment by Lineflyer** [comment]
> Are you sure about the OC-code? For me its not existing.

Nevermind....seems cgeo or the API have a problem. Any OC code gives no result.

**Comment by okainov** [comment]
>Are you sure about the OC-code? For me its not existing.

Pretty sure =) But yes, very high probability that reproducible with some others as well

https://www.opencaching.de/okapi/services/caches/geocache?attribution_append=none&cache_code=OC13213&fields=code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cowner%7Cfounds%7Cnotfounds%7Crating%7Crating_votes%7Crecommendations%7Cdescription%7Chint%7Cimages%7Clatest_logs%7Calt_wpts%7Cattrnames%7Creq_passwd%7Ctrackables%7Cis_found%7Cmy_notes%7Cgc_code%7Cattribution_note%7Cattr_acodes%7Cwillattends%7Cshort_description%7Cis_watched&langpref=en&log_fields=uuid%7Cdate%7Cuser%7Ctype%7Ccomment%7Cimages&lpc=all&oauth_consumer_key=uKvUaP6TkbzSGab2UD5X&oauth_nonce=d053a11e1e85904b62b1679d73a07a32&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1553962884&oauth_token=7SSF9F6PrZcgUQxkJMpY&oauth_version=1.0&oauth_signature=q3eZ34VH3n7KLMKileR3z9WfQw0%3D

**Comment by Lineflyer** [comment]
Also reproducible for OC15134.
IMHO it also affects caches previously working flawless with c:geo, so I suspect some change on OC.de side in the API.

@OpencachingDeutschland

**Comment by Lineflyer** [comment]
Not sure if mentioning a whole team works, so lets try to mention @teiling88 instead for this issue.

**Comment by okainov** [comment]
@Bananeweizen why? I mean, what c:geo library has to do with inconsistent API replies from OC website? Even more weird that for some caches the reply contain proper list, but for some it's not

**Comment by teiling88** [comment]
@Lineflyer what kind of result is expected? The last okapi update was for 1 - 2 month iirc.

**Comment by okainov** [comment]
@teiling88 

>attr_acodes - unordered list of OKAPI geocache-attribute IDs (A-codes) with which the cache was tagged. Use the attrs module to retrieve information on these attributes.

See

https://www.opencaching.de/okapi/services/caches/geocache?attribution_append=none&cache_code=OC13213&fields=code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cowner%7Cfounds%7Cnotfounds%7Crating%7Crating_votes%7Crecommendations%7Cdescription%7Chint%7Cimages%7Clatest_logs%7Calt_wpts%7Cattrnames%7Creq_passwd%7Ctrackables%7Cis_found%7Cmy_notes%7Cgc_code%7Cattribution_note%7Cattr_acodes%7Cwillattends%7Cshort_description%7Cis_watched&langpref=en&log_fields=uuid%7Cdate%7Cuser%7Ctype%7Ccomment%7Cimages&lpc=all&oauth_consumer_key=uKvUaP6TkbzSGab2UD5X&oauth_nonce=d053a11e1e85904b62b1679d73a07a32&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1553962884&oauth_token=7SSF9F6PrZcgUQxkJMpY&oauth_version=1.0&oauth_signature=q3eZ34VH3n7KLMKileR3z9WfQw0%3D

vs 

https://www.opencaching.de/okapi/services/caches/geocache?attribution_append=none&cache_code=OC134AC&fields=code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cowner%7Cfounds%7Cnotfounds%7Crating%7Crating_votes%7Crecommendations%7Cdescription%7Chint%7Cimages%7Clatest_logs%7Calt_wpts%7Cattrnames%7Creq_passwd%7Ctrackables%7Cis_found%7Cmy_notes%7Cgc_code%7Cattribution_note%7Cattr_acodes%7Cwillattends%7Cshort_description%7Cis_watched&langpref=en&log_fields=uuid%7Cdate%7Cuser%7Ctype%7Ccomment%7Cimages&lpc=all&oauth_consumer_key=uKvUaP6TkbzSGab2UD5X&oauth_nonce=e52881787f061a41bc196baa7bbbd5f1&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1553961225&oauth_token=7SSF9F6PrZcgUQxkJMpY&oauth_version=1.0&oauth_signature=%2FD8A3JX9DcYDCAe2AA6owHq3css%3D

**Comment by okainov** [comment]
@teiling88 probably you know better which is correct =) I was referring to opencaching OKAPI documentation above, so does current c:geo behavior.

> attr_acodes - unordered **list** of OKAPI geocache-attribute IDs (A-codes) with which the cache was tagged. Use the attrs module to retrieve information on these attributes.

**Comment by teiling88** [comment]
Ok, hopefully the guys from pl will merge it soon :-)

**Comment by Lineflyer** [comment]
@teiling88 Do we need to change anything from our side, else I would close the issue here?

**Comment by teiling88** [comment]
@Lineflyer I have no direct impact on the okapi development. Let us wait until my pr is merged. Then it is 100 % save that c:geo has nothing do to fix this issue. 
I will take care to watch my pr on okapi!

**Comment by bekuno** [comment]
@following5 Please have a look at the PR from @teiling88

**Comment by teiling88** [comment]
this issue can be closed cause of the "merging" from @following5 https://github.com/opencaching/okapi/commit/e79c12fc1d548d818ababd41259027fd3892fbdb
