### ISSUE TITLE
Obtain GMaps V2 key

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7449]
As explained in #2222 the "c:geo team" should obtain a GMaps V2 key asap and correspondingly also find out, what requirements arises with that (e.g. having a payment method in place, etc.).

I already synced with @mucek4 about this and he has taken the point to investigate the current key owner and find out the best way to obtain an official key.

Once we have the key it should be configured in our CI to allow building working builds with GMaps V2.

**Comment by Lineflyer** [comment]
For information:

I configured a [new job](http://ci.cgeo.org/job/cgeo%20nightly%20GMapsV2/) which builds a nightly from current `GoogleMapsV2` branch each night at 01:30 and places it on http://download.cgeo.org/cgeo-nightly-GM.apk 
As for the standard nightly job, you can also trigger a manual build on CI as needed over the day.

For better distinction between our default nightly the version name contains "-NBGM-" instead of "-NB-".
The version code however is the same as the default nightly of the same day, which means that you should be able to install this nightly over older nightlies from master and vice versa.  The new install only has to be newer or same day as the installed one on your device.

This should enable us to switch between those nightlies as needed on our test devices.

**Comment by mucek4** [comment]
The first thing what google says is:
Reminder: To use the Maps SDK for Android, you must get an API key and you must enable billing. You can enable billing when you get your API key (see the Quick guide) or as a separate process (see Billing). 

I have to see how "billing" works. As I don't intend to place my credit card "on the line" google API might take some more time.

**Comment by Lineflyer** [comment]
@mucek4 
Out of curiosity:
What happens if you access https://console.cloud.google.com/apis/library  

I do see a project "c:geo trial", not sure whether I created it myself or this is a project bound to the app already somehow?!

I clicked on "Activate" for Maps SDK for Android and it just came back with "Activated".
No idea though for whom or what I activated...mmh

If I look on https://console.cloud.google.com/google/maps-apis/api-list I do see, that its active.
And on https://console.cloud.google.com/google/maps-apis/apis/maps-android-backend.googleapis.com/credentials I do see some keys now.

**Comment by moving-bits** [comment]
Seems like you can create a key without having to enter billing information. At least for development purposes this works for now.

Key can be bound to c:geo app, but for the necessary fingerprint info see the logcat information on first run with activated Google Maps v2 - the fingerprint seems to differ from what keystore outputs.

**Comment by Lineflyer** [comment]
@mucek4 Any success in retrieving a key which can be used on the CI (and later for c:geo)? Can I be of any assistance?

**Comment by mucek4** [comment]
Ok. I have the key. But if I set it to "maps.api.key" on Jenkins current mapsV1 will stop working.
Under what name shall I put it on Jenkins?

**Comment by moving-bits** [comment]
I've a similar problem locally. => I'll create a PR to make the v2 key variable name unique, so that both keys can coexist.

**Comment by mucek4** [comment]
Great. So mapsv2.api.key will be? I'll put the key also on 3rd and 4th executor.

**Comment by moving-bits** [comment]
> Great. So mapsv2.api.key will be? I'll put the key also on 3rd and 4th executor.

ah, saw this too late - key is now named maps.api2.key (maps_api2_key in template file)

**Comment by Lineflyer** [comment]
@mucek4 Will you adapt on your side then to `maps.api2.key` as changed in #7502?

**Comment by Lineflyer** [comment]
> I'll put the key also on 3rd and 4th executor.

Do the executors also have the V1 key and the OC-keys?
As far as I have understood it, having them on master should be enough (as we build e.g. nightlies from there). I might be wrong though.

**Comment by mucek4** [comment]
Ok. I renames to maps.api2.key. 
Executor4 and 5 have all the keys as I just copied private key to executors. I didn't knew I need to "remove" them for executors.

**Comment by Lineflyer** [comment]
Not sure regarding the keys but probably @kumy knows.

**Comment by Lineflyer** [comment]
Addon: The new GMaps-nightly job I configured has the same config as the normal nightly job, meaning it will only run on Jenkins master.

**Comment by kumy** [comment]
If the unit tests make use of the keys, then they need to be deployed on every slave.

**Comment by kumy** [comment]
@mucek4 do we have different keys for production builds and PR builds? Can I copy the one from master?

**Comment by Lineflyer** [comment]
IMHO the only difference for production builds is the APK signing (i.e. the signing key from Google should be kept secret on master).

**Comment by kumy** [comment]
The signing keys are the same on each slave too, else you cannot switch from prod <> nightlies without uninstall first. I'll copy map api keys…

**Comment by kumy** [comment]
key added to `cgeo-1` and `cgeo-2`

**Comment by Lineflyer** [comment]
> The signing keys are the same on each slave too, else you cannot switch from prod <> nightlies without uninstall first. I'll copy map api keys…

I am no so familar with it, but I remember that the signing keys are not on the slaves. When first starting to use the slaves, we discussed this topic and came AFAIR to the conclusion that we use exclusively master to build production and nightlies and therefore have no need to distribute those important keys.

The cgeo-debug.apk use their own key (and icon) AFAIK.

**Comment by mucek4** [comment]
Lars, as far as I remember we said like that. However tests requires password for GC too and that one needs to be distributed also. So distributing one or two files does not make difference.

**Comment by Lineflyer** [comment]
Mission accomplished!
I could not resist to build another nightly-GM.apk via CI. And in my hands I have a working GMapsV2 c:geo nightly. Perfect.

http://download.cgeo.org/cgeo-nightly-GM.apk

I encourage all to give it a try and document existing problems or regressions to Github issues. I will do the same next days/weeks.
