### ISSUE TITLE
upgrade okhttp to 3.12.2

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#7453]
We could upgrade okhttp to 3.12.2 with our current target settings. However, it behaves differently in encoding query parameters then and ParametersTest.java fails.

@samueltardieu can you check that, since you added explicit encoding in the Parameters.toString() method? I suspect that can be removed with the new version, but I'm not sure.

**Comment by samueltardieu** [comment]
It looks like they encode more characters than before. One has to check that this does not break the OAuth process. I've opened #7455 to check this.
