### ISSUE TITLE
Don't activate gc.com connector on install

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7461]
As mentioned in #4263 we need to improve the "first start flow" anyhow, so this issue is more or less a workaround until then:

Since last release c:geo does not directly jump to the gc.com credentials settings anymore (due to the permission request handling now implemented) but starts up on the main screen.
I already got quite some support mail from first time users (or users reinstalled the app) which have not been aware, that something essential is missing to use c:geo.

The problem here is, that the gc.com connector is still by default set to active even though no credentials are stored. That leads to the "problem", that users can use live map, nearby search, etc. delivering them some unreliable data so they potentially do not notice they are working without being logged in.

If we could - as a workaround - simply disable the gc.com connector at first start it would at least be very visible to the user, that he needs to do something to get it working; i.e. if no connector is active click on "nearby" will return "None of the active services is supporting this function", live map will not show any unreliable caches, etc.

**Comment by Lineflyer** [comment]
@okainov 
Thinking about the upcoming first release incl. gc.su:
I could imagine some gc.su users first time installing c:geo when we issue the release with support for gc.su.
I did not test it yet, but I assume this issue could cause an issue as follows:
- Install c:geo
- Login to gc.su connector only (leave gc.com untouched)
- Use c:geo

AFAIK this could result in caches from gc.com being shown as well (and with incorrect information as user is not logged on there).  
Do you think this is a relevant issue for gc.su users (or do most users anyway use gc.com in addition to gc.su)?

**Comment by Lineflyer** [comment]
Will test this scenario maybe tomorrow.

**Comment by bekuno** [comment]
I propose to jump after installation to an initial site (simular to jump to "Changes" on updates) with "First steps". Then we could initial deactivate gc.com like the other services. 
As text I suggest the text from "https://manual.cgeo.org/en/firststeps"
(after updating to the latest changes)

**Comment by bekuno** [comment]
The start site as additional tab in the "about c:geo" area.

![Screenshot_20190420-133258](https://user-images.githubusercontent.com/32555742/56456777-752f5000-6371-11e9-9724-49490c92d2e7.png)

**Comment by okainov** [comment]
At this stage user has ready granted all the permissions to the app, correct? So spending half of the screen to explain permissions has no sense.

I would propose to try to fit all GS into one screen putting only important essentials there like

1. Register on one of GC platforms (maybe list with links here)
2. Click here to select platforms you want to use
3. Enjoy

**Comment by bekuno** [comment]
A optimized dialog (not full implemented yet):
The text is devided in parts. (3 heradines, 3 text parts)
The text for permissions is shortened.
A button added to directly jump to the services page in c:geo.
@okainov the site is presented as first action, before you got an permissions dialog.

![Screenshot_20190422-142055](https://user-images.githubusercontent.com/32555742/56500420-0259dc80-650b-11e9-8ad0-b66bf4a20e5d.png)

**Comment by bekuno** [comment]
Refresh the services page - split section Geocaching to "Geocaching provider" and "other"

![Screenshot_20190422-214058](https://user-images.githubusercontent.com/32555742/56523884-9302dd80-6548-11e9-8eba-9fd5e03403e9.png)

**Comment by okainov** [comment]
Probably you want to unify the word used all across the app: either "services" or "providers"or "platforms" for different geocaching platforms.

As for the big button, I'd suggest something like "configure my geocaching platform/service/provider" to make it more clear that we expect users to click and go there right now.

**Comment by Lineflyer** [comment]
@bekuno 
As mentioned in the PR you should open a PR for the deactivation as fix for this issue.
Additionally you can use #4263 as reference for your first-start proposal and also submit this.

**Comment by bekuno** [comment]
@Lineflyer Ok. Here ist the first PR.

**Comment by Lineflyer** [comment]
I really appreciate this change after testing:
Now after a new installation the user really knows, that something needs to be done:
- Nearby search is showing "no active connector supporting this search" (or similar)
- Live map is just empty

However it also reveals some parts of the app are ignoring this (e.g. search for GC code)
I will open a new issue as time permits...because this might be helpful to modify all functions, where c:geo does not treat gc.com in the same way as any other connector
