### ISSUE TITLE
Align other windows to new cache refresh window style

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7463]
Thanks to @moving-bits we do now have an IMHO nice looking progress window for cache saving/refresh.

However some similar dialogs are still old/broken style:
- Progress window when batch deleting (all) caches from a list
- Loading window while opening pocket queries
- Anything else?

**Comment by moving-bits** [comment]
>     Progress window when batch deleting (all) caches from a list

You mean "Stored caches => Manage Caches => Remove all" menu point? How can you test this? I had a list of about 1.700 caches, and using this menu entry they get deleted in an instant (in my VM)...

The dialog that flickers looks ok to me on a first glance (it's visible for less than a second in my testing environment). But this is on master branch only, not in yesterday's release version, as the progressdialog styling fixes had not been merged to release branch.

**Comment by Lineflyer** [comment]
Have a list of 5000 caches and use a old HTC :)

**Comment by moving-bits** [comment]
ok, maybe I can slowdown the emulator for this one :)

On which branch have you tested this - release or master?
I had followed the source code of this function (deleting caches from list) down to where the progressdialog gets its styling, and there the new progressdialog styling IS given, so it should look ok (on master branch) - or there are other side effects I haven't found yet.

**Comment by Lineflyer** [comment]
The progress windows for the mentioned cases above look normal to me in 2019.11.28 at least on Android 10. Don't know about older versions, however lets leave it like this for now.
