### ISSUE TITLE
Make cache popup more flexible

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7468]
When tapping on a cache icon in map view, a popup window opens. It shows a couple of information and offers action buttons. Generally ok. But...

- It shows a lot of information I either don't need or which could be displayed in a more compact way.
- It misses some pretty important information while being on a caching tour: the hint. (*)

Simply adding the hint to this popup would make it even larger and therefore too big on some devices. So here a some ideas to condense this view a little bit:
- Cache type is already shown by the logo, thus could be left out. The size information could be printed after the distance.
- Difficulty, Terrain and favorites info could be printed in a condensed way after GC code.
- "last saved" info could be condensed into a one-liner
- list info could be left out
- hint could be added besides the the buttons (refresh / edit lists / delete)

I do understand that personal preferences on what infos to show in this popup vary widely. So I suggest to make it somewhat configurable, the defaults being set in a way that the current layout is shown.

---

(*) Why the hint should be available on the cache popup IMHO:

Currently my workflow while being on a longer tour is:
- tap on cache icon on map
- select cache from marker list
- swipe to details page
- swipe down to end of page
- tap on hint
- tap on back to return to map
- tap on cache icon on map again
- select cache from marker list again
- and follow distance info to final

This could be reduced to:
- tap on cache icon on map
- select cache from marker list
- tap on hint

**Comment by moving-bits** [comment]
A somewhat simpler approach for a non intrusive way to just add the hint to the popup could be this one:

Show an additional button on the popup, if a hint is available:
![image](https://user-images.githubusercontent.com/3754370/55668899-8b68e680-5870-11e9-8043-8cd78a695300.png)

If this button is pressed, the popup extends to show the hint:
![image](https://user-images.githubusercontent.com/3754370/55668907-a0de1080-5870-11e9-8a0e-2e51c885284d.png)
The "hint" button is a toggle, which switches between showing and not showing the hint.

If no hint is available, the button is not shown:
![image](https://user-images.githubusercontent.com/3754370/55668917-b5220d80-5870-11e9-8253-91abf46c3733.png)

**Comment by Lineflyer** [comment]
Not so bad IMHO.

AFAIR there is also already an issue about showing hint on map. I might be wrong though.

**Comment by alan666notb** [comment]
what happens when the CO writes a novel in the hint, like in GC64R4X

**Comment by moving-bits** [comment]
> what happens when the CO writes a novel in the hint, like in GC64R4X

The view is scrollable:
![image](https://user-images.githubusercontent.com/3754370/55671244-61beb800-588e-11e9-93c1-4f2ecf027eab.png)
(so the rest of the hint becomes visible when you swipe up)

**Comment by bekuno** [comment]
From the button logic - the place right aside the "more details" button seems more logical to me then in the store info area.

**Comment by moving-bits** [comment]
I see two possible solutions to this:

a) Put the button aside the other detail information:

![image](https://user-images.githubusercontent.com/3754370/55687575-b6d1fb00-596e-11e9-96d9-57b659fa59de.png)

advantage: close to other details info
disadvantage: far away from the hint field

b) swap the buttons on the lower area so that the two storage related buttons are side to side, and the "hint" button is close to the hint field:

![image](https://user-images.githubusercontent.com/3754370/55687571-ab7ecf80-596e-11e9-9af6-ef8c0e51306a.png)

advantage: close to the hint field, close to other action buttons, does not distract from "more details"
disadvantage: far away from other details + not really logical in storage related area (although I'm not sure if that one is recognized by the user as that)



What do you think?

**Comment by bekuno** [comment]
If it is not possible to set it in the same row as the more details button then my favorite is the first one. The button is next to the cache information and user can realize easier that extra information.

**Comment by Lineflyer** [comment]
I firstly agree somehow, that the new icon makes no sense in the save/move/list specific section to be intuitive.
So I would also favor the first option...however I keep thinking about if there is a more intuitive icon to show, that this is the hint behind it....mmh.

**Comment by bekuno** [comment]
How about this:
https://www.materialui.co/icon/highlight
or a other "light" (lamp, sun)

**Comment by rsudev** [comment]
IIRC we have already a hint icon for the compass view...

**Comment by Lineflyer** [comment]
Indeed: https://manual.cgeo.org/_media/ic_menu_hint.png
