### ISSUE TITLE
Maps activities have different style depending on map source

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7470]
##### Detailed steps causing the problem:
- Open Map Activity, select some mapsforge offline map
- Check the style of the activity / title bar / menus
- Change to Google Map source
- Make sure style is very different: blue dots and back button, rounded corners for  popup, whole title bar is more narrow.

It should be one style for all map sources

(I can add screenshots in the evening)

**Comment by Lineflyer** [comment]
Yes, this is known...and I asked in some issue about that.
In fact it also depends on the Android version.

**Comment by Lineflyer** [comment]
Lets continue in #7587
