### ISSUE TITLE
Trackable search should support GK secret codes

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7476]
##### Detailed steps causing the problem:
- Have a valid GK tracking code (=secret code)
- Try to open the GK to log it with c:geo

##### Actual behavior after performing these steps:
The trackable search seems only to query gc.com but not GK even if the service is activated.
With only the tracking code its not possible to log a random GK with c:geo (you need to look up the public code first). On the GK website its no problem to log it with only the secret code.

##### Expected behavior after performing these steps:
This search should scan all activated services supporting trackables

##### Version of c:geo used:
2019.04.04

##### Is the problem reproducible for you?
Yes

##### Remark
Found, while checking my new GK trackable shirt ;)

**Comment by Lineflyer** [comment]
This applies for the explicit trackable search field in the search menu as well as for the quick search on the main screen top bar.

**Comment by bekuno** [comment]
Also it is not possible to find the GK with the Reference Number, when they are not in the Inventory, but only in the own GK list. Maybe this could be a regression in the API.
(found it when I showed my "Contributor GK" to friends. :-) )

**Comment by bekuno** [comment]
@kumy I don't found the search parameter with tracking conde in the GK api documentation. Is it not possible on this way? (on the log website you can verify the tracking code with an ajax call)

**Comment by bekuno** [comment]
this is a duplicate to #5206 .
Maybe we should close here and leave the old issue open?

**Comment by Lineflyer** [comment]
Makes sense. 

Remark from old issue:
I think #4822 should be solved before full activation of search by tracking code for GK
