### ISSUE TITLE
c:geo crashes with "no such table: cg_trail_history" after fresh install

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7482]
##### Detailed steps causing the problem:
- fresh install of current (April 10) master brach on a new device
- run c:geo and open Map

##### Actual behavior after performing these steps:
- c:geo crashes with log message "no such table: cg_trail_history"

##### Expected behavior after performing these steps:
- show map

##### Version of c:geo used:
- today's (April 10) master

##### Is the problem reproducible for you?
Yes

##### System information:
- tested under API 21 (Android 5.0) with Google API enabled

##### Other comments and remarks:
- table "cg_trail_history" got introduced by fix for #2958
- why is the database update routine not called before opening the map / what has to be done that it gets called before?

**Comment by rsudev** [comment]
The new table needs to be handled in DataStore.onCreate as well, AFAICS

**Comment by moving-bits** [comment]
good catch, thanks. Created a PR for this.
