### ISSUE TITLE
Dialog "Store Unsaved" (caches_store_unsaved) missing button "Last Selection" (cache_list_select_last)

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7484]
##### Detailed steps causing the problem:
- prepair:
  - open map (testet with offline and osm online map)
  - wait until loading caches
  - open one cache detail
  - save cache to list(s)

- save single cache:
  - open another cache detail
  - save cache to list(s)
  - Dialog with headline "Pick the lists"
  - Button "Last Selection" occures

- save caches from menu "Store Unsaved":
  - menu "Store Unsaved"
  - Dialog with headline "Pick a list"
  - no Button "Last Selection"

##### Actual behavior after performing these steps:
Button "Last Selection" missing

##### Expected behavior after performing these steps:
Button "Last Selection" should be visible

##### Version of c:geo used:
2019.04.04

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Maybe it is sufficient to replace the dialog with the one used when storing a single cache?

**Comment by Lineflyer** [comment]
Confirmed. IMHO it was never there.

> Maybe it is sufficient to replace the dialog with the one used when storing a single cache?

Most likely. I wasn't even aware, that these dialogs are different.
