### ISSUE TITLE
List selection dialog text color black on dark gray

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7485]
##### Detailed steps causing the problem:
- c:geo light theme
- map, select cache, save
- list selection dialog with black text (see image)
![Screenshot_20190410-143054_cgeo](https://user-images.githubusercontent.com/32555742/55879390-ccc60280-5b9e-11e9-9160-4764d807fb8b.jpg)

##### Actual behavior after performing these steps:
the text is nearly not readable

##### Expected behavior after performing these steps:
complete black text on white background

##### Version of c:geo used:
2019.04.04

##### Is the problem reproducible for you?
Yes

##### System information:
Android 9 (Samsung Note 8)

##### Other comments and remarks:
On Android 7 (Samsung S6) (c:geo 2019.04.08-RC) this is ok.
Or was this fixed already?

**Comment by Lineflyer** [comment]
IMHO this was fixed already on `master`

**Comment by Lineflyer** [comment]
Yes, #7394
