### ISSUE TITLE
Update Jenkins to new version

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7487]
We currently use Jenkins 2.150.1 and newest available is 2.164.2, which also fixes some vulnerabilities. Furthermore it might be, that the current IRC bot problem is also caused by some compatability issue with the version mixes of plugin(s) and jenkins itself. 

Anyway it might be wise to update Jenkins from time to time.

According to https://www.thegeekstuff.com/2016/06/upgrade-jenkins-and-plugins/ it should not be a big deal and easily revertible, in case there are issues after upgrade.

No idea, if something needs to be adapted on the executors as my knowledge about Jenkins is still only basic.

@kumy Could you help or assist with your knowledge? I do not even have console access, so I cannot try myself....and I also don't want to crash the whole thing as I have never done install/upgrade of Jenkins.

**Comment by mucek4** [comment]
CI runs in virtual machine. We can snapshot it, update it and revert it if anything goes wacky.
I'll be in servers over weekend, I'll update it.

**Comment by Lineflyer** [comment]
Cool! You might also take a look in updating the plugins.

**Comment by Lineflyer** [comment]
BTW:
HTTPS for the CI is not working as the certificate is for your other domain. Any chance to get this working as well while you are on it?

**Comment by mucek4** [comment]
Stage one is done. Jenkns and plugins are updated. Now let me see what I can do with https.

**Comment by Lineflyer** [comment]
https seems to work fine on CI for the last days.
If the slave configuration is also OK we can close this.

**Comment by mucek4** [comment]
@Lineflyer shall I force redirection to HTTPS?

**Comment by bekuno** [comment]
@Lineflyer @mucek4 This problem is resolved, isn't it?

**Comment by mucek4** [comment]
Probably. But in 4 months there is for sure new version :)
