### ISSUE TITLE
improve map cache name and distance layout

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#7489]
On a map showing a single cache we show the distance in the upper right corner, the name in the upper left. There are several design issues here:
* On my device the texts are not vertically centered in the half transparent area (but more to the top). We should have them centered vertically.
* The right hand corner (distance) seems to have a fixed width (or a huge left and right margin/spacing). That wastes a lot of space, when the distance is small, and the name of the cache is long (and cut off). The view should grow and shrink as necessary.

**Comment by Lineflyer** [comment]
Additionally the content of the field is wrong in case the routing line is using brouter but we keep showing the direct line distance....just remarking here (covered in another issue AFAIR). Just in case someone starts working on this ;)

**Comment by moving-bits** [comment]
> Additionally the content of the field is wrong in case the routing line is using brouter but we keep showing the direct line distance....just remarking here (covered in another issue AFAIR). Just in case someone starts working on this ;)

This part is solved on current master.
