### ISSUE TITLE
Crash when trying to store cache list (Android 4.x)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7491]
##### Detailed steps causing the problem:
- Perform nearby search
- Select Menu - Manage caches - Save offline

##### Actual behavior after performing these steps:
Crash
```
12:10:40.798 Warning cgeo 14363  [main] UncaughtException
12:10:40.799 Warning cgeo 14363  java.lang.NoClassDefFoundError: java.util.Objects
12:10:40.799 Warning cgeo 14363  	at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4624)
12:10:40.799 Warning cgeo 14363  	at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4707)
12:10:40.799 Warning cgeo 14363  	at cgeo.geocaching.settings.Settings.putStringList(Settings.java:334)
12:10:40.799 Warning cgeo 14363  	at cgeo.geocaching.settings.Settings.setLastSelectedLists(Settings.java:544)
12:10:40.799 Warning cgeo 14363  	at cgeo.geocaching.list.StoredList$UserInterface$OnOkClickListener.onClick(StoredList.java:361)
12:10:40.799 Warning cgeo 14363  	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
12:10:40.799 Warning cgeo 14363  	at android.os.Handler.dispatchMessage(Handler.java:99)
12:10:40.799 Warning cgeo 14363  	at android.os.Looper.loop(Looper.java:137)
12:10:40.800 Warning cgeo 14363  	at android.app.ActivityThread.main(ActivityThread.java:4797)
12:10:40.800 Warning cgeo 14363  	at java.lang.reflect.Method.invokeNative(Native Method)
12:10:40.800 Warning cgeo 14363  	at java.lang.reflect.Method.invoke(Method.java:511)
12:10:40.800 Warning cgeo 14363  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
12:10:40.800 Warning cgeo 14363  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
12:10:40.800 Warning cgeo 14363  	at dalvik.system.NativeStart.main(Native Method)
```

##### Expected behavior after performing these steps:
Normal operation

##### Version of c:geo used:
2019.04.12-RC (found while smoke testing before planned beta release)
That RC represents current release branch as of today

##### Is the problem reproducible for you?
Yes, on Android 4.1.2 device 

##### System information:
ZTE Grand Memo LTE
Android 4.1.2

**Comment by Lineflyer** [comment]
Could not reproduce on 4.4.2

**Comment by Lineflyer** [comment]
The reason could be because of:

> The exception is thrown because all static methods of java.util.Objects are available above API 19 (Android 4.4.+).

found on stackoverflow

**Comment by Lineflyer** [comment]
@Bananeweizen: As you are familiar with a lot of code check tools: Isn't there a tool available (e.g. for our CI) which checks if the code is compatible down to our minSDK?

**Comment by rsudev** [comment]
Additional contexts for the same issue: CacheDetailActivity when showing a PO, disabled or archived cache.
