### ISSUE TITLE
Progress window has strange colors on white theme (Android 4.x)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7492]
With 2019.04.12-RC (release branch as of today after merging  7d0dcf8d1681c0210850ad00f65e049fa13ccf9e)

It looks like this on white theme:
![Screenshot_2019-04-12-12-06-08](https://user-images.githubusercontent.com/949669/56031202-0de52080-5d1f-11e9-9262-bc1692c6234f.png)

On black theme it looks reasonably OK (enough for legacy support those old Android versions):
![Screenshot_2019-04-12-12-32-56](https://user-images.githubusercontent.com/949669/56031266-3bca6500-5d1f-11e9-92d3-9cf1e2f15fb1.png)

**Comment by moving-bits** [comment]
Ah, I love those layout inconsistencies across different Android versions and between emulator and real devices...
Will have a look at it...

**Comment by Lineflyer** [comment]
Yes, this is hard to test as well. When it comes to Android 4.x I will probably in future limit the testing to just see its not crashing and basic functions are working normal...effort for this old stuff should be kept at a minimum IMHO.

So I consider also this as a minor issue.

**Comment by moving-bits** [comment]
I do have a fix ready for this, just could not finish testing yesterday :-)

**Comment by moving-bits** [comment]
Created PR #7496, smoke tested with API 16, 19 and 24, light and dark theme for each.
