### ISSUE TITLE
Upgrade to mapsforge 0.11.0

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#7494]
Upgrade to the latest mapsforge library version (0.11.0 from 2019-03-25).
Doing it now on master allows the longest test cycle to find issues/regressions.

**Comment by rsudev** [comment]
As the upgrade was reverted due to unclear performance issues showing up, this has to be addressed again.

**Comment by Lineflyer** [comment]
@rsudev Thanks for reverting.
To be on the safe side I built a fresh nightly and tested again (i.e. current master reverted back to 0.9.1). The problem described in #7523 is gone.

I suggest to close #7523 for now and potentially discuss next steps in this issue instead.

**Comment by jonas-koeritz** [comment]
The currently used Mapsforge 0.9.1 doesn't work on Android 9, couldn't find any issues with 0.11.0 so far.
