### ISSUE TITLE
Filter by time of last update (to limit refresh of caches)

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#7498]
Often, I want to refresh “all” caches except those I refreshed within the last
- 8 hours
- 24 hours
- week
- month
… to save traffic. If we could have a filter, that would be easier.

**Comment by Lineflyer** [comment]
Similar to #5959 and #2590 however this proposal here is more aligned to the current working modes and features and provides a solution proposal which covers the mentioned issues. I therefore close the other ones in favor of this one.
