### ISSUE TITLE
Do not draw trail line between consecutive points if distance is high

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7506]
With todays NB I tried to check out the recent changes to the map trail by @moving-bits .
I noticed, that the history is kept also between several sessions (i.e. close of app and restart of app. I know, that it is intended to work like this, but in normal daily use this has shown some problems for me.

Example:
- Drive to location A, go caching and use c:geo trail function
- Drive to location B, go caching and use c:geo trail function
- On the next day start c:geo at location C
- Know I have a bunch of trail worms on my map connected with a straight line (last and first position after app restart) which I need to clear manually using the "Clear trail" function.

My proposal would be to keep it running while the app is in use but not between "sessions" or autoclear it after 24 hours or alike.

**Comment by jonas-koeritz** [comment]
An easy solution could be to just limit the distance between two trail points. If the previous point is more than x km away, start a new trail. The trails could be shown indefinitely and the irritating jumps are gone.

**Comment by moving-bits** [comment]
c:geo can be removed from memory for several reasons automatically by the Android system, so a "restart" / "new session" etc. does not necessarily mean a new geocaching session has begun for the user. Saving the trail to survive such forced restarts was the reason to implement this feature in the beginning...

But I do understand your use case, just a different solution needs to be found.
One approach could be a certain distance limit. If two points are more distant from each other than this limit, no connection line gets drawn (between those two points).
A different approach could be "no line, if two consecutive points are from different days", but that would require adding a timestamp to the trail history, so I'm in favour of the first approach.

**Comment by Lineflyer** [comment]
> But I do understand your use case, just a different solution needs to be found.

Indeed...now my map is full of lines between the different locations I used c:geo last days. Looks like a plate of spaghetti ;)
A limit for a connection line to be drawn sounds reasonable.  Something like 5-10km?

**Comment by moving-bits** [comment]
> > But I do understand your use case, just a different solution needs to be found.
> 
> Indeed...now my map is full of lines between the different locations I used c:geo last days. Looks like a plate of spaghetti ;)

:-)

But you have seen the menu entry "clear trail history"?

> A limit for a connection line to be drawn sounds reasonable. Something like 5-10km?

I've prepared a PR with a limit of 10 km, but still testing - my AS sometimes behaves flaky, does not stop at breakpoints etc. ...
