### ISSUE TITLE
Map popup progress info has transparent background

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7508]
##### Detailed steps causing the problem:
- User GmapsV2 nightly
- Open live map - Google
- Click on an unsaved caches with orange circle
- Data is being loaded online and loading progress window is shown

##### Actual behavior after performing these steps:
This progress window is completely transparent

##### Expected behavior after performing these steps:
It should have black background

##### Version of c:geo used:
2019.04.15-NBGM1

##### Is the problem reproducible for you?
Yes

##### System information:
Android 6.0.1 - CyanogenMod
Samsung S3 LTE

##### Other comments and remarks:
The google maps V2 branch is not aligned with latest style changes. So maybe this issue itself is outdated when using the styles applied to master?!

**Comment by moving-bits** [comment]
We should test this again with the recent styling fixes for ProgressDialog included.

Which leads to your test-PR on how to keep the ongoing changes on master in sync for GoogleMapsV2 branch. Should be open a team discussion for it to clarify the procedure?

**Comment by Lineflyer** [comment]
> Should be open a team discussion for it to clarify the procedure?

Same thinking, I just opened a normal issue to discuss that.

**Comment by Lineflyer** [comment]
It could be, that this is not related to GMapsV2 but a general issue when using white theme on certain Android versions. I think I have just seen it on `master` as well but cannot check right now.

**Comment by Lineflyer** [comment]
Yes, this is also on master branch with Android 6.
@moving-bits I tend to close it as its not a regression and no functional deficit (and for a rather old Android version). Feel free to reopen.
