### ISSUE TITLE
Harmonize maps - Support waypoint selector also on Google Maps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7511]
##### Detailed steps causing the problem:
- Use GoogleMapsV2-NB
- Open a map of saved caches also incl. waypoints or caches close to each other
- Click on a bunch of overlapping cache/waypoint icons

##### Actual behavior after performing these steps:
Popup is shown for one of the overlapping icons 

##### Expected behavior after performing these steps:
It should be aligned with "new map" where a dialog for selecting the desired waypoint is shown

##### Version of c:geo used:
2019.04.15-NBGM1

##### Is the problem reproducible for you?
Yes

**Comment by moving-bits** [comment]
With `UnifiedMap` in the works, and `UnifiedMap` supporting waypoint selector for all supported maps, I propose to close this issue here.

**Comment by moving-bits** [comment]
Is implemented for UnifiedMap GM already & won't be implemented for GMv2 anymore, therefore closing this issue.
