### ISSUE TITLE
Use hybrid map as satellite map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7512]
If you compare the GMapsV1 satellite map and the GMapsV2 satellite map:
- V1 is showing the hybrid version, where street names, POI, etc. are drawn
- V2 is showing the pure satellite images without any other layers

IMHO the hybrid version is the one to use or (if technically possible) both variants should be offered.

**Comment by moving-bits** [comment]
> IMHO the hybrid version is the one to use or (if technically possible) both variants should be offered.

I've changed MAP_SATELLITE to MAP_HYBRID, but more variants could be integrated at a later time.

**Comment by moving-bits** [comment]
@Lineflyer  Hm, why did this issue not get closed automatically after merging PR #7517?

**Comment by Lineflyer** [comment]
Because its only closed if the commit / PR is merged to the base branch, which is master.
