### ISSUE TITLE
Found status not correctly merged between Live Map and Database

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#7527]
When the Live Map loading code is setting the found status it's value prevails. This leads to caches not getting marked as found on the map when the API the caches are loaded from is lagging behind on the latest status.
The live map code added in #7514 does set the found property of the caches.

There are two possible solutions to this:
- Set the status of the map provides this information and fix it in the merging code
- Don't set the status in the love map code and leave the merging code alone

How should this be handled to get the latest found status possible on the map?

**Comment by rsudev** [comment]
I would suggest to address this in the live map loading code. If the status there possibly lags behind, I would leave the found status untouched unless it is 'found' on the live map.  Thereby the local information can prevail if there is any, and a found we now about from the map is always taken into account.

**Comment by jonas-koeritz** [comment]
That's a very nice solution. It's not wasting the info from the map but fixes the problem for all cases!

**Comment by Lineflyer** [comment]
Todday I might have experienced this issue?!

After logging some cache finds with  geo (saved caches) I started the live map just for looking up somehting different.

Afterwards the logged caches showed up in my list as not found (list view) but as found after opening the details and after closing again also now as found on my list view.

Is this the same issue?

Indeed the solution suggested by @rsudev sounds good to me.

**Comment by jonas-koeritz** [comment]
This might be the same root cause. The solution should be easy to implement, maybe I can spend some time tomorrow to fix this.
