### ISSUE TITLE
Support direct offline map download links

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#7529]
When recently discussing the current evolution of c:geo mapsforge support the maintainers of openandromaps suggested that c:geo should support a special url scheme to trigger download of map files from their site. Besides the orux and locus specific ones they do have 'generic' ones we could tie into. This sounds to me like an easier to implement first step for #6072

**Comment by rsudev** [comment]
Link to the forum discussion: https://www.openandromaps.org/oam-forums/topic/cgeo-unterstuetzt-elevate-4-und-aktuelle-kartenformate#post-28215

**Comment by Lineflyer** [comment]
On http://www.freizeitkarte-osm.de/android/de/impressum.html
I have also just seen, that they support a XML repository to load files and themes.

**Comment by Lineflyer** [comment]
No longer very important but still a think which could be evaluated as advanced option.

**Comment by moving-bits** [comment]
FYI: c:geo has full OpenAndroMaps download support meanwhile:
- #9851 (map downloader support for OAM)
- #9921 (map scheme trigger)
- #9945 (theme scheme trigger)

Regarding freizeitkarte: From reading their "Impressum" I guess we are free to use their maps in our downloader. I'll put that on my TODO list.
