### ISSUE TITLE
Trackable "status" seems not localized

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7531]
Since some months the status of the trackable is parsed (i.e. if the user has already discovered/ retrieved/ placed it). As the translation into german is completed on Crowdin but I still see e.g. "Retrieved it (20. April)" I assume its not localized.

**Comment by bekuno** [comment]
The text "Retrieved it" is not localized, it is generic text for enum LogType element RETRIEVED_IT. The localized text is strings.xml:log_retrieved, in german "Mitgenommen", english "Retrieved".
And we have the enum LogTypeTrackable with the same element name RETRIEVED_IT.
Maybe there is some mixed ...

**Comment by bekuno** [comment]
Can you provide a screenshot with such a value?

**Comment by Lineflyer** [comment]
Screenshot:
![Screenshot_20190422-143956_cgeo](https://user-images.githubusercontent.com/949669/56608267-ad9d8b00-660a-11e9-8a3f-fbfa98b2f3c8.jpg)

**Comment by bekuno** [comment]
The output is in this format since the first implementation in PR #7141 from @bjdupuis and change from @UniQP  (17./18.11.18)

**Comment by Lineflyer** [comment]
Looking at the code it only uses the string and date as parsed from the webpage without localization, correct? Then this issue should stay open to be fixed.
