### ISSUE TITLE
Create account option not working for some OC platforms

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7536]
##### Detailed steps causing the problem:
- In the menu for each geocaching service we have the option to authorize.
- In the following menu we have a button to create an account for this platform.
- for some opencaching provider then we got the error err_application_no ("c:geo can't find any suitable application.")
- Ok for opencaching.de, .us
- KO for opencaching.pl, .nl, .ro, .uk

##### Version of c:geo used:
current master on Samsung S6 / Android 7
2019.04.16 on Samsung Note 8 / Android 9

##### Is the problem reproducible for you?
Yes

**Comment by Lineflyer** [comment]
AFAIK we get the needed URL for account creation directly from the API.
So we might need to check if this is caused by the API itself.

**Comment by Lineflyer** [comment]
See #7154. Is it the same problem?

**Comment by bekuno** [comment]
> See #7154. Is it the same problem?

I assume yes.
The button auth_again ("Start again") opens the login credential web page, but the button auth_register ("Create an account") brings the message err_application_no ("c:geo can\'t find any suitable application.")

There are different data now from the api,
eg. https://www.opencaching.de/okapi/services/apisrv/installation 
  => okapi_version 1908
  => registration_url "https://www.opencaching.de/register.php"
or https://www.opencaching.de/okapi/services/apisrv/installation 
  => okapi_version 1910
  => registration_url "/UserRegistration"

The current implementation is from #5620, @Bananeweizen 

@following5 Is this a bug or a feature?
I didn't seen a change in the OKAPI description for registration_url between the both versions.
If it is a feature - how to get a full url?

**Comment by bekuno** [comment]
Current state:

https://opencaching.pl/okapi/services/apisrv/installation
okapi_version_number | 1917
registration_url | "/UserRegistration"

https://www.opencaching.nl/okapi/services/apisrv/installation
okapi_version_number | 1917
registration_url | "/UserRegistration"

https://opencache.uk/okapi/services/apisrv/installation
okapi_version_number | 1917
registration_url | "/UserRegistration"

https://opencaching.us/okapi/services/apisrv/installation
okapi_revision | 1076

With 
  registration_url | "/UserRegistration"
we must combine with
  site_url | "https://opencache.uk/"
to 
  https://opencache.uk//UserRegistration
as additional address.

**Comment by bekuno** [comment]
see opencaching/okapi#589

**Comment by bekuno** [comment]
is fixed now in OCPL
