### ISSUE TITLE
Merging of disabled status between map and saved caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7539]
The new live map implementation now also (correctly) parses disabled status of caches. 
On the old map we did not have the needs to merge anything as the disabled status has not been parsed explicitly.

This means, that we now have the new need to merge the data in some way.
One typical scenario I experienced this weekend with the new map was:

- Have a cache saved (status at time of save was "Enabled")
- Browsing the live map you will see the cache as "Saved"/"Enabled"
- Once you click on the popup it shows "Disabled" in the popup information
- If you open the cache details it will still be "Enabled" there
- if you close details and/or the popup the live map will still show it "Enabled"

What could be a clever way to merge this information and/or make is consistent?
As a user I would not expect, that using the live map alters anything on my saved caches.
At the same time I would like to see the live map with real live information (i.e. the cache should be shown disabled there).

Maybe its the best idea to show the saved caches as disabled on the map (to be implemented) and in the popup (already working) but just keep the saved cache untouched. Once the user clicks on "More Details" in the popup he will see in the cache details, that this information was stored xxx days ago.

**Comment by jonas-koeritz** [comment]
I just experienced this exact problem.
Marking stored cache information as automatically updated would be an option, if the app already knows that a cache has been deactivated I would expect it to show me right upfront.
A saved cache that has been deactivated in the meantime is of no value to me.

**Comment by Lineflyer** [comment]
> A saved cache that has been deactivated in the meantime is of no value to me.

From the past I have not a good relation to data coming from the live map and I have now get used to the fact, that the data should be reliable (beside the time lag).

So probably you are right with the argument, that the user should have this useful information.
Can you implement this merging or do you need help from someone here (no idea where this kind of merging to the database needs to be done)?

**Comment by jonas-koeritz** [comment]
I can have a look at the code and try it on my own. If I need any information I will post to this issue and ask for help.

**Comment by Lineflyer** [comment]
Set as "assigned-non-collab" and set me as standin.

**Comment by jonas-koeritz** [comment]
I had a go on this but caches I have stored don't get disabled that often. Could you have a look at my "solution"?

https://github.com/jonas-koeritz/cgeo/commit/cc56964b4d8bd77fa60e97335d69e974ad6a3262
