### ISSUE TITLE
HTML background color within Listing not rendered 

### ISSUE THREAD

**Issue by ppete2** [cgeo/cgeo#7547]
##### Detailed steps causing the problem:
open https://coord.info/GCQBJ2

##### Actual behavior after performing these steps:
text is rendered without HTML background color

##### Expected behavior after performing these steps:
within point 6.) of the Listing's instructions some words are highlighted using yellow background color. This background color should be visible too in c:geo. In dark skin and in light skin. 

##### Version of c:geo used:
2019.04.16

##### Is the problem reproducible for you?
Yes

**Comment by MagpieFourtyTwo** [comment]
As for me (using latest nightly), the yellow text background *is* rendered, although with white text (which makes it pretty hard to read, thus "automatic text color" should switch to black on e. g. yellow [or any light] background).

**Comment by fm-sys** [comment]
Seems to be fixed...
