### ISSUE TITLE
About c:geo: "Back Arrow" displays release notes only

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7558]
##### Detailed steps causing the problem:
- in latest nightly: menu -> "about c:geo"
  (not needed after fresh update, as c:geo opens in "about c:geo" / "changes" anyway)
- click back arrow in upper left corner

##### Actual behavior after performing these steps:
- "about c:geo" / "changes" will be (resp. will remain) displayed

##### Expected behavior after performing these steps:
- "about c:geo" should be closed and start page should be displayed

##### Version of c:geo used:
- 2019.04.26-NB-fee04a0

##### Is the problem reproducible for you?
- Yes

##### System information:
```
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2019.04.26-NB-fee04a0
Google Play services: disabled - 16.0.91 (040408-244116403)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (5,9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (5,9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (5,9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (238,7 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---

```

##### Other comments and remarks:
Android's back arrow works as expected and allows me to go back to c:geo's start screen

**Comment by MagpieFourtyTwo** [comment]
Oops - the latest nightly seems to *always* start with "about c:geo / changes" ... which is a little bit annoying ... ;)

**Comment by bekuno** [comment]
Copy/Past error, I will fix it.

**Comment by Lineflyer** [comment]
@bekuno
Did not test it yet, but sounds related to your getting started

**Comment by Lineflyer** [comment]
That was at the same time :)

**Comment by ithink314** [comment]
FWIW, Seeing this in 4/27/19 version too. 

--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 9
Android build: lineage_shamu-userdebug 9 PQ2A.190405.003 a12fd289c3 dev-keys
c:geo version: 2019.04.27-NB-80ee79d
Google Play services: disabled - 0.2.6.13280
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (32.2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (32.2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (32.2 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (551.5 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   opencaching.us: Logged in (Login OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by ithink314** [comment]
Except back arrow and display are stuck on About cgeo pages. :(
