### ISSUE TITLE
c:geo shows less satellites

### ISSUE THREAD

**Issue by Beiri22** [cgeo/cgeo#7560]
##### Detailed steps causing the problem:
Start c:geo and wait for a fix
Start "gps test" app and wait for a fix
compare the results 

##### Actual behavior after performing these steps:
c:geo shows 19/22 satelites
gps test shows 24/32 satelites

##### Expected behavior after performing these steps:
c:geo also shows 24/32 satelites

##### Version of c:geo used:
installed yesterday via play store

##### Is the problem reproducible for you?
Yes

##### System information:
Using a Huawei Mate 20 Pro, that utilizes gps, glonass, beidou and galileo satelites.

**Comment by UniQP** [comment]
Can you provide a screenshot of the list of satellites shown by GPSTest (and the corresponding c:geo count)? Since your phone can receive L1 and L5 frequencies from the same satellite, I can imagine that GPSTest counts them separately while we don't.

**Comment by SammysHP** [comment]
Just to make it clear: c:geo uses exactly the same satellites as other apps because the location is provided by Android (and that comes from the receiver hardware). Just the reported number of satellites might be different.

**Comment by Beiri22** [comment]
Here they are. Taken with a delay of <10s.

![Screenshot_20190427_124129_com android gpstest](https://user-images.githubusercontent.com/8210233/56867248-7e5c9480-69e3-11e9-9f89-a6af777942b6.jpg)
![Screenshot_20190427_124140_cgeo geocaching](https://user-images.githubusercontent.com/8210233/56867249-7e5c9480-69e3-11e9-9832-da9f21d12e57.jpg)
