### ISSUE TITLE
Add option to prevent map rotation on device rotation

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7565]
When cycling & geocaching I frequently face the problem that my mobile is slightly off-angle and the screen changes its orientation. This not only takes time for screen refresh but reduces overview. (Same happens when holding my mobile in my hands while moving around etc.)

So I'm looking for an feature to lock map rotation optionally. I know that I can do this system-wide, but I want to have this for c:geo only (even better: map only), and I don't want to have to switch this on and off manually each time.

I've created a PR for this, which works fine in the emulator and on my testing device, but I want to field test this.

**Comment by moving-bits** [comment]
Starting with Android 9 such a feature is built into the OS, so let's close here.

**Comment by SammysHP** [comment]
There is an option to set the screen orientation in Android as long as I remember. And since Android 4 (?) it's available in the quick settings tiles.

**Comment by moving-bits** [comment]
@SammysHP  You're describing the system-wide setting. My use case was about an app-specific setting: Leave screen orientation toggling on as default, but prevent c:geo from rotating.
This is not possible without extra tools, but Android 9 introduced a change, which led to something similar as the intended behaviour: If you set screen orientation to portrait and rotate your device, the system asks you whether you want to rotate your app.
By this you can still rotate your specific app if you like to, but avoid that all apps rotate like in standard mode. And you don't have to manually toggle that setting before going outside to cache.

**Comment by anondev-sudo** [comment]
Can this feature be implemented?

**Comment by SammysHP** [comment]
No, because it should already be a system setting since Android 9.

**Comment by anondev-sudo** [comment]
I have xiaomi redmi note 9, how do I set rotation screen settings per app?

**Comment by anondev-sudo** [comment]
I have android 12 and there isn't such option

**Comment by murggel** [comment]
> I have android 12 and there isn't such option 

I have a Samsunf with Android 12 and with automatic rotation off I get a symbol I  the lower right corner to rotate the current screen manually when I rotate the phone. 

![Screenshot_20240331-211246_cgeo.jpg](https://github.com/cgeo/cgeo/assets/70113341/34cac236-06bf-4f86-9fb0-2a4b40859ca5)

**Comment by murggel** [comment]
That is not really an option "rotate per app" it's a manual option to rotate

**Comment by fm-sys** [comment]
> I have a Samsunf with Android 12 and with automatic rotation off I get a symbol I the lower right corner to rotate the current screen manually when I rotate the phone.

This is device specific feature, not all devices have it. 

But isn't it enough to disable screen rotation globally on the device?

**Comment by moving-bits** [comment]
> > I have a Samsunf with Android 12 and with automatic rotation off I get a symbol I the lower right corner to rotate the current screen manually when I rotate the phone.
> 
> This is device specific feature, not all devices have it.

Isn't that a plaon AOSP feature? Even the emulator has it. But, as mentioned above, it's a global setting - disable automatic rotation for all apps, then decide individually whether to rotate in a specific situation. Personally, this is a perfect solution for my use-cases, but YMMV.

Before that feature got introduced (with Android 9, IIRC) we had experienced with some c:geo-internal detection and prevention, but it was pretty hacky and not very reliable back then, so when the Android feature got published, we were happy to abandom that hack (which never reached a published state, BTW).

**Comment by anondev-sudo** [comment]
Why you cant implement that lock screen rotation setting into cgeo? I have seen more apps have it.
