### ISSUE TITLE
Caches vanish from map after rotation of device

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7567]
##### Detailed steps causing the problem:
- Open live map (new google map) in e.g. portrait mode
- Wait until cache loading is finished
- Rotate device

##### Actual behavior after performing these steps:
- Map layer is refreshed but caches vanish and only (re)load after moving the map

##### Expected behavior after performing these steps:
- Caches should be kept showing after rotation

##### Version of c:geo used:
2019.04.28-NBGM-ccdf59f

##### Is the problem reproducible for you?
Yes

##### System information:
Android 5.0.2

**Comment by moving-bits** [comment]
@Lineflyer
Cannot reproduce on either emulator and physical device running Android 5.
Maybe it got fixed by #7846 as well?

**Comment by Lineflyer** [comment]
AFAIR this was not really Android version specific, however on my Android 9 device with current master its fine.
Also ignore this until I find the time to test the nightly on more (older) Android versions.

**Comment by Lineflyer** [comment]
No longer reproducible on the device originally tested with (Android 5.0.2), neither on my Android 9 device.
I assume this was fixed somewhere in between testing on the GmapsV2 branch and the final result on master branch.
