### ISSUE TITLE
Crash on multiple rotations

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7568]
##### Detailed steps causing the problem:
- Open live map (new Google map)
- Rotate device to landscape
- Rotate device back to protrait

##### Actual behavior after performing these steps:
- Crash

##### Expected behavior after performing these steps:
- Normal operation

##### Version of c:geo used:
2019.04.28-NBGM-ccdf59f

##### Is the problem reproducible for you?
Yes

##### System information:
Android 5.0.2

**Comment by moving-bits** [comment]
@Lineflyer
Cannot reproduce on either emulator and physical device running Android 5. Got a single crash in the beginning (c:geo back to main menu), but none after that, even after a couple of dozens of screen rotations. - Can you still reproduce it with current master?

**Comment by Lineflyer** [comment]
@moving-bits 
Could not reproduce with todays nightly on Android 9. My Android 5 device is at home (and I am not). Just ignore this issue until i had the chance to retest it on the original device.

**Comment by Lineflyer** [comment]
No longer reproducible on the device originally tested with (Android 5.0.2), neither on my Android 9 device.
I assume this was fixed somewhere in between testing on the GmapsV2 branch and the final result on master branch.
