### ISSUE TITLE
Map zoom buttons z-order not ok

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7569]
##### Detailed steps causing the problem:
- Open live map (new Google map)
- Move the map so that some caches are shown underneath the +/- zoom buttons
- Typ on + or - button to zoom in or out

##### Actual behavior after performing these steps:
- Cache popup of cache shown "below" the button might open

##### Expected behavior after performing these steps:
- Zoom buttons should have piority

##### Version of c:geo used:
2019.04.28-NBGM-ccdf59f

##### Is the problem reproducible for you?
Yes, most of the time at least

##### System information:
Android 5.0.2

**Comment by MagpieFourtyTwo** [comment]
Hmm, works for me (using latest nightly).

Nevertheless, concerning +/- I had another effect yesterday:  Tapped (-), which then stayed(!) selected, i. e. the color did not change back to white, and the map zoomed out more and more ... really strange.  De-selecting by e. g. tapping (-) again or tapping on (+) did not work, zooming in via pinch neither (just stopped zooming as long as I left pinching fingers on the display, but as soon as they lift off, zooming out went on), had to leave the map page to stop it.

**Comment by Lineflyer** [comment]
This is not a fault on master/nightly but specific for the new google map implementation which is on branch GoogleMapsV2.

**Comment by rsudev** [comment]
It sounds like an effect that I have seen occasionally on all of our map implementations over the years. As we don't really 'control' the zoom buttons and when/how they react to taps (they are built-in to the map) I guess we cannot do much here.

**Comment by MagpieFourtyTwo** [comment]
> This is not a fault on master/nightly but specific for the new google map implementation which is on branch GoogleMapsV2.

Yep - already thought so on re-reading my answer ... ;)

**Comment by moving-bits** [comment]
Zoom control are always displayed in front of map markers for me, but a tap on them sometimes get routed to the zoom control only, and other times to the zoom control AND the map marker.

So far I have not found any documentation on setting a z-order for the controls or prevent the click/tap event cascading.
