### ISSUE TITLE
Cache/WP icons not shown on cache map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7570]
##### Detailed steps causing the problem:
- Open cache details of a cache
- Select Navigate -> Map (new Google map)

##### Actual behavior after performing these steps:
- Map is shown at correct location, direction line is shown, but cache (and associated WP) icons are not shown initially. Only if you slightly move/zoom the map, they appear

##### Expected behavior after performing these steps:
- Cache/WP icons shown instantly

##### Version of c:geo used:
2019.04.28-NBGM-ccdf59f

##### Is the problem reproducible for you?
Yes

##### System information:
Android 5.0.2

**Comment by Lineflyer** [comment]
Same problem, when mapping a list of caches

**Comment by moving-bits** [comment]
seems to be fixed by #7846 as well
