### ISSUE TITLE
Issue while switching between geocaching.com accounts

### ISSUE THREAD

**Issue by king-ton** [cgeo/cgeo#7581]
Hy guys,
first thanks for your great work!

##### Detailed steps causing the problem:
- Login with an pm account on geocaching.com
- Logout and login with another pm account
- A new log will be posted with the first account

##### Actual behavior after performing these steps:
Log will be posted with first account and also TB's from first account will be shown.

##### Expected behavior after performing these steps:
Log should be posted with the second account.

##### Version of c:geo used:
2019.04.16

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: ONEPLUS A5000 (OnePlus5, OnePlus)
Android version: 9
Android build: ONEPLUS A5000_24_190222
c:geo version: 2019.04.16
Google Play services: disabled - 16.0.91 (100400-244116403)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (69,1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (69,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (69,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (141,8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / BASIC
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins: contacts
--- End of system information ---

```

##### Other comments and remarks:
The problem exists since this year. I think since release 2019.02.23 but I'm not sure.

**Comment by rsudev** [comment]
This is a usage scenario which in principle is not well supported by c:geo, as all the locally stored information has the 'perspective' of the user at the point in time when the information was obtained (found status, friend logs, ...).
Besides that is your description not fully clear, as in contrast to your statement the system information depict:
> Geocaching sites enabled:
>   geocaching.com: Logged in (Anmeldung OK) / BASIC

When you write 'logging in with pm account on geocaching.com', do you mean logging in on the website or actually changing the authorisation within c:geo?

**Comment by king-ton** [comment]
The scenario you described is not the main point: found status, friend logs, ...
I know to implement that is not easy and not the point I mean.

> When you write 'logging in with pm account on geocaching.com', do you mean logging in on the website or actually changing the authorisation within c:geo?

Yes, that is what I mean. I changed the geocaching.com authorization to another premium member account. Now I want to post a new log on a cache. The log will be created with the first account and not with the new account which is authorized in the settings. I also closed the complete app and updated the cache where I want to post a log but it does not effect anything.

What I forget to write is that this problem exists since this year. Before it was possible without any problems.

**Comment by Lineflyer** [comment]
Even though I agree to @rsudev, that this is a scenario c:geo is not designed for, I did not see such kind of problem in the past using different testing accounts.

@king-ton 
After you changed the login in c:geo, does the main screen show the correct user name (the new one) and "Login OK"?
When you then post a log for a cache, how does it show up (directly after logging without refreshing anything) in the logbook of this cache in c:geo. Correct or with the wrong user name?

**Comment by king-ton** [comment]
The main screen shows the correct username also "Login OK".

If I post a new log (Owner logs are not possible. There will be shown a message that was not possible to publish the log) the correct username in the logbook in cgeo is shown. After Refreshing the cache the wrong/old username is shown. Also an the website the old username is shown.

I think that cgeo used some cached data for logging. Under the log input fields there will be shown the trackables from the old account.

**Comment by Lineflyer** [comment]
Interesting.

How do you change the account in c:geo?
Do you just go to Menu - Settings - Services - geocaching.com and enter the new users login?

What happens if you instead prior to entering the new users login use the long press on "Authorize c:geo" to remove the existing login data? I know, that this feature is kind of undocumented. :(

**Comment by king-ton** [comment]
Sorry guys, I forgot to reply. With your second trick my problems are solved. Thank you!
The only scenario I have sometimes is that I can't upload Cache notes after changing the account because the button is missing. But this is not related to my original question.

Thanks for your help and your great work!
