### ISSUE TITLE
Remove contacts plugin from useful apps list

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7582]
Prompted by the recent addition of 'GPS Locker' to the utility programs, I had a quick look at some of the others available. I only looked at a couple, but....

"Contacts plugin" - doesn't exist in playstore anymore.
"PQ Generator" - hasn't worked for about 6 months.

Maybe an audit of all utils is in order?

**Comment by Lineflyer** [comment]
> "Contacts plugin" - doesn't exist in playstore anymore.

Indeed, we should remove it for now.
We had to depublish it due to Google requirements not being met. If it ever returns, then most probably reintegrated into the main app.

> "PQ Generator" - hasn't worked for about 6 months.

From time to time it might stop working due to website changes. However currently its working (used it last week) and it is maintained. So we should keep it.

The remaining apps are available and usable AFAICS. I have to admit, that I did not test "Bluetooth GPS" as I do not have an external receiver anymore.

**Comment by rsudev** [comment]
I use Bluetooth GPS whenever I am out caching, for me it works fine.

**Comment by rsudev** [comment]
Regarding the Contacts Plugin: As long as we support Api versions without permission requests, we IMO cannot integrate it into the main app based on the same arguments we had for the separation initially.

**Comment by Lineflyer** [comment]
> Regarding the Contacts Plugin: As long as we support Api versions without permission requests, we IMO cannot integrate it into the main app based on the same arguments we had for the separation initially.

Good point. Somehow I remember, that the situation still changed...but I can't find the failure in your argumentation. Needs to think about it or look up what I wrote in another issue.

**Comment by MagpieFourtyTwo** [comment]
What about just pointing the link to a version hosted outside of the market (which, of course, should still be maintained)?  Like e. g. http://download.cgeo.org/cgeo-contacts-nightly.apk?  Perhaps with a short explanation of "allow external sources"?  As for me:  I use the contacts plugin a lot and would highly appreciate being able to install it on my next phone, too ... ;)

**Comment by SammysHP** [comment]
rsudev wrote:
> As long as we support Api versions without permission requests, we IMO cannot integrate it into the main app based on the same arguments we had for the separation initially.

You are not allowed to ask for these permissions as long as you don't have permissions from Google.

MagpieFourtyTwo wrote:
> What about just pointing the link to a version hosted outside of the market

Linking or even describing the way to externally hosted APKs results in removal of the app from the Play Store and block of the account. Happened several times recently.
