### ISSUE TITLE
Confirm before batch uploading coordinates

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7585]
##### Detailed steps causing the problem:
User feedback for beta version 2019.04.29-RC
- I imported a PQ of my solved mysteries (which for some reason had a bad formatting regarding final and original coords, might be the PQ from Groundspeak does not include the modified coords?!)
- I wasn't sure about the meaning of batch uploading coordinates (new in the beta version)
- I tried it and it has overwritten all my solved mysteries on the server with listing coords :((

##### Expected behavior after performing these steps:
I would wish this function would have a confirmation screen explaing what is transfered from where to where and doubleconfirm before executing. Besides my problem there might also be other scenarios in which the function is accidentally started and could create a data loss, which can not be undone in an easy way.

##### Version of c:geo used:
2019.04.29-RC

**Comment by moving-bits** [comment]
prepared a PR for this, based on today's release branch

**Comment by moving-bits** [comment]
@Lineflyer  Besides having created a PR for the confirmation dialog: Can we get the PQ ZIP file the user has imported, for testing? Batch upload should only take caches for which the "modified coords" flag is set, so if in that user's case all cache coordinates got overwritten by listing coords, something went wrong - either in the PQ or in detecting "modified coords" by c:geo.

**Comment by Lineflyer** [comment]
Will try to. But AFAIR it was some GPX self compiled via GSAK.
