### ISSUE TITLE
Align theme design of GMapsV2 to "rest of app"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7587]
The GMapsV2 implementation currently still uses a different style (on my Android 8 device) which is different to most other places in c:geo.
Maybe we can use the work on GMapsV2 to align styles/design to what is used e.g. for mapsforge.

I will post some screenshots next weeks to make clear, what I am referring to (e.g. while the map is open it change the color of my status bar (above the app) to light blue and text in top bar is also in this color.

**Comment by okainov** [comment]
Isn't it a duplicate? :) https://github.com/cgeo/cgeo/issues/7470

**Comment by Lineflyer** [comment]
Yes, kind of.
Will close the other one as it might be wise to focus on GMapv2 to fix it rather than on the old stuff, whereas I assume its the same technical wise.

**Comment by Lineflyer** [comment]
Taken from https://github.com/cgeo/cgeo/pull/8782#issuecomment-671879598:

To name just a few things:
- action bar is black instead of grey
- if you open the "three dot menu" it has round edges
- and some menu entries crash into each other (eg.: map settings)
- colorAccent not being applied
- ...
