### ISSUE TITLE
TB search not possible

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7592]
At least two users report on FB, that with beta version 2019.04.29-RC they cannot search for trackable codes.

They get the error message "No platform supports this type of search" (or similar). I know there was a related change but for me it works normal.

Users confirmed, that they see "Login OK" on main screen, which means they have a platform active....

**Comment by moving-bits** [comment]
Message probably comes from #7555 (PR #7561), which checks for active "trackable connectors". Which services do they have activated? Which TB codes did they search for?

**Comment by alan666notb** [comment]
I was just about to raise this as well.

I type a tracking code into the search page and I get "No currently activated geocaching services provide this type of search"

I'm logged-in to geocaching.com as normal.

**Comment by alan666notb** [comment]
I tried TB3QFD5 & TB7EYQP and the corresponding tracking codes.
If I go to a cache that has a TB in it and swip across to the TB page and click on it, it loads fine.

**Comment by Lineflyer** [comment]
The codes mentioned by @alan666notb are working fine for me.

Still another two users on support mail. Each of them logged into gc.com normal acc. to sysinfo. And problem is persistent even after reboot/relogin.

The new code looks kind of straight forward to me...what can cause this?

**Comment by alan666notb** [comment]
@Lineflyer : anything I can do to help diagnose the fault?
One of my devices (Nexus 7) is rooted.

**Comment by Lineflyer** [comment]
Can you check whether this problem is bound to your account (happens on all devices) or on device (only faulty on one device)?

**Comment by alan666notb** [comment]
If fails in the same way on both my devices (Nexus 7 and Galaxy S9)
Any my partner's Motorola G6 (Obviously a different account)

We're both running 2019-04-29-RC

**Comment by alan666notb** [comment]
@Lineflyer - I just noticed something, If I type a six character TB tracking code into the 'quick-search' field (i.e. at the top of the 'six tiles' initial screen), it works.
But the same code typed into the search page fails.

**Comment by Lineflyer** [comment]
Thats as expected as we do not check active connectors when using this field, but we only introduced this check within the search menu.
So it seems for whatever reason this check turns out as if you have no geocaching platform enabled....but you have..

I guess someone needs to look up where this is malfunctioning deeper into the code.

**Comment by moving-bits** [comment]
TrackableConnector does not implement the `isActive()` method, thus is always counted as being not active. I'll create a PR for this.

**Comment by Lineflyer** [comment]
@alan666notb 
We have just published a new beta 2019.05.13-RC (should be available via Google Play soon). It should fix this TB problem. Could you please retest this after upgrade and provide feedback as I cannot reproduce the problem myself?

**Comment by alan666notb** [comment]
@Lineflyer - yes, just tried 2019.05.13-RC, works fine now.

**Comment by Lineflyer** [comment]
Thanks @alan666notb for your feedback.
Also users on support mail confirmed, that the problem is solved with 2019.05.13-RC

**Comment by alan666notb** [comment]
@lineflyer - I have just raised  #7617 which was almost certainly a result of this fix.
