### ISSUE TITLE
Wrong saving time stamp in live map popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7593]
##### Detailed steps causing the problem:
- Have a list of saved caches (e.g. saved 4 days ago)
- Open live map of the area, where also the stored caches are located
- Open popup for one of the saved caches

##### Actual behavior after performing these steps:
The popup states "saved a few minutes ago", whereas when you open the cache details it still says "saved 4 days ago"

##### Expected behavior after performing these steps:
Show the real save date also in the popup

##### Version of c:geo used:
2019.05.02-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Tested on Android 8 and Android 9

##### Other comments and remarks:
Side effect of the new live map loading?

**Comment by bekuno** [comment]
It's that way for years.

**Comment by Lineflyer** [comment]
Really?I am almost sure i used the popup information often in the past to checked how old the saved cache info is?Von Samsung-Tablet gesendet
null

**Comment by bekuno** [comment]
Yes.
Mostly I saw it after showing the second cache on the map.

**Comment by SammysHP** [comment]
If that is for years, is there another bug report somewhere?

**Comment by bekuno** [comment]
Normally I use offline maps.
Maybe it is only in the new map implementation.
I'm pretty sure that this was already before I joined the project.

**Comment by jakedot** [comment]
Can confirm that I have seen this as well. It seemed to be related to PQ download for me.

**Comment by Lineflyer** [comment]
Duplicate of #8733
