### ISSUE TITLE
Live map not loading when started from adress search

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7602]
New Google Map issue:

##### Detailed steps causing the problem:
- Search for adress "New York"
- Click on map icon in resulting list

##### Actual behavior after performing these steps:
Map opens but only shows a waypoint marker in center but does not load or show any caches

##### Expected behavior after performing these steps:
Normal live map activated

##### Version of c:geo used:
2019.04.30-NBGM1-55e41a4

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.1

**Comment by jonas-koeritz** [comment]
Might be related to #7584.

**Comment by Lineflyer** [comment]
@jonas-koeritz 
In this case I don't think so as I tested as premium member.
Please note, it also only affects the GMapsV2, but not the current GMapsV1.
The problem there seems to be that caches are not drawn to map initially but only after the map has been moved for the first time.
