### ISSUE TITLE
move "Getting Started" in front of "Help"

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#7607]
The "Getting Started" page should be left of "Help" to make it more easily accessible for new users.

**Comment by bekuno** [comment]
Mmm, I'm unsure about it.
When I created PR #7543, I asked myself where this information should be placed. I then decided to put this after the help page. This seemed to me to be in a logical position. 
But I don't have a problem with a position closer to the about page.
@Lineflyer  ?

**Comment by Bananeweizen** [comment]
I'm thinking of someone exploring the help menu on his own. In that case he really has to navigate through the pages from left to right. And then I would expect "Getting started" before "Help".

**Comment by Lineflyer** [comment]
I agree to @Bananeweizen, that it should change places with "help".
