### ISSUE TITLE
GK search with no result when not searchable in GKmap 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7610]
##### Detailed steps causing the problem:
Search for a GK which is not in the users inventory 

##### Actual behavior after performing these steps:
Not found

##### Expected behavior after performing these steps:
Should be found

##### Version of c:geo used:
master

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
see #7476

**Comment by bekuno** [comment]
We search with 
https://api.geokretymap.org/export-details.php?gkid=...
with no result, but the original source
https://geokrety.org/export2.php?gkid=...
finds him.
@kumy Is this a bug or a feature?

**Comment by kumy** [comment]
@bekuno The way GKM start syncing a GK is when a GK has been moved. So, yes, when a GK has never moved, it doesn't appear in GKM database :( In your case, you said the difference seems to be "when a GK is in user inventory". May you please share a GK id having such problem?

**Comment by kumy** [comment]
@bekuno BTW such endpoints are deprecated - on GKM only . It's now preferred to use `https://api.geokretymap.org/gk/<id>/details`. But it's not a big deal and can be a pain to implement 2 different endpoints. So don't worry about this, it's just for information ;)

Please see https://github.com/GeoKretyMap/Api/wiki/Api-endpoints for list of endpoint ;)

Or source code:
https://github.com/GeoKretyMap/gkm-api-nginx/blob/898ba57e0695370f99e9ed73d85a1d8c4bf4e7e1/conf.d/api.geokretymap.org.conf#L127-L142

**Comment by kumy** [comment]
@bekuno GKM should now include "GK that never moved" too.

**Comment by Lineflyer** [comment]
@bekuno Can you retest with your GK and close here if solved?

**Comment by bekuno** [comment]
Unfortunately I can't test with the original GK anymore, because it was changed in the test in the meantime.
With newly created GK the query works.
