### ISSUE TITLE
replace deprecated GKM endpoint by new one

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7615]
From Conversation in #7610

https://api.geokretymap.org/export-details.php?gkid=...
Such endpoints are deprecated. It's now preferred to use 
https://api.geokretymap.org/gk/<id>/details. B

Please see https://github.com/GeoKretyMap/Api/wiki/Api-endpoints for list of endpoint ;)

**Comment by kumy** [comment]
https://github.com/GeoKretyMap/gkm/wiki/Api-endpoints seems to be the right doc

**Comment by kumy** [comment]
Also, `https://api.geokretymap.org` will be deprecated and replaced by `https://api.geokrety.org` (Fusion of GKM and GK projects)
