### ISSUE TITLE
GK trackable test failing on CI

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7616]
TestSearchTrackable for Geokrety is failing in our tests.
It seems GKB580 is no longer existing in the GK database.

@kumy 
AFAIR you created this GK explicitly for c:geo testing

**Comment by kumy** [comment]
Sorry GKM is crashed today :gun: please wait until this afternoon

**Comment by kumy** [comment]
Service crashed while synchronizing, I've restarted the service, sync is ongoing.
https://github.com/geokrety/geokrety-website/issues/325
