### ISSUE TITLE
Distance to caches wrong in "Own caches" search (Flag button)

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#7618]
##### Detailed steps causing the problem:

- In the search screen there is a button on the top right in the menu bar which searchs for owned caches (I think it's always using online results)
- The default sort for the results is by distance
- loaded more caches until all my owned caches were visible, am not sure if the problem started before or after that (108 caches, so 5 additional loads needed)

##### Actual behavior after performing these steps:

- First I saw caches sorted differently to what I would expect from those near me, but wasn't sure of the displayed distances
- Then I saw other caches that were clearly wrong (e.g. an event in Oslo displayed as 160km away even though I am in Austria)
- Yet other distant caches were displayed with actual distance, but not sorted correctly even though sort by distance is set

- opening the same caches in an actual list where they are saved offline displayed correct distances

##### Expected behavior after performing these steps:

- correct distances displayed and caches sorted correctly

##### Version of c:geo used:

2019.05.13-RC

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: P6000 (P6000, Blackview)
Android version: 7.1.1
Android build: P6000-Blackview-V0.1-20171021
c:geo version: 2019.05.13-RC
Google Play services: disabled - 17.1.22 (040408-245988633)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_AT
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (32,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (32,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (32,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (55,0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins: contacts
--- End of system information ---
```
![Screenshot_20190518-014336](https://user-images.githubusercontent.com/12250212/57961522-c9e1ce80-790f-11e9-8541-42ac5646e596.png)
![Screenshot_20190518-014025](https://user-images.githubusercontent.com/12250212/57961579-3957be00-7910-11e9-8cba-ede7378bf6af.png)
![Screenshot_20190518-011851](https://user-images.githubusercontent.com/12250212/57961582-3d83db80-7910-11e9-8c58-276318b33546.png)
![Screenshot_20190518-013958](https://user-images.githubusercontent.com/12250212/57961583-3f4d9f00-7910-11e9-8121-32b7918dc90e.png)
![Screenshot_20190518-014006](https://user-images.githubusercontent.com/12250212/57961585-41176280-7910-11e9-92ad-3ccdd72b64fc.png)

**Comment by Lineflyer** [comment]
Thanks for your report.
It would be nice to know

> loaded more caches until all my owned caches were visible, am not sure if the problem started before or after that (108 caches, so 5 additional loads needed)

if this is the case or not.

**Comment by jakedot** [comment]
I just tried again and it also happens in the fresh release (updated from apk on github), on first opening the activity by click on the button. Additionally, it shows only 6 active caches and 14 archived events, with all of them very wrong distances (event in Aland 839m away while event actually 3km away is shown with 1249km). Some of the events don't show any distance at all, with one near home and two far away (in Jersey, Morocco). Added new screenshot!
![Screenshot_20190520-225942](https://user-images.githubusercontent.com/12250212/58051960-d191b500-7b53-11e9-98e5-f0ba038d3c7a.png)

**Comment by jakedot** [comment]
Huh interesting, the distance labels are not stable. Well, the location may also be instable as I'm currently indoors. Seems some distance is copied to other listings, or it may be a rendering problem within the list.

 See here:
![Screenshot_20190520-230630](https://user-images.githubusercontent.com/12250212/58052111-4238d180-7b54-11e9-80a3-bf01213db1da.png)

**Comment by jakedot** [comment]
What I also find kind of strange, didn't this search feature return only active caches first at some time in the past?

**Comment by jakedot** [comment]
The active caches look to have correct distances to me.

**Comment by jakedot** [comment]
The active caches seem to have the distances correct.

**Comment by jakedot** [comment]
Ok, so after thinking on it a bit I'm convinced the problem is that the archived events are not stored offline. Can it be a problem with caching the unsaved but at some time opened caches' data?

**Comment by Lineflyer** [comment]
@jakedot 
You might be right.
It seems the server returns no possibility to retrieve coordinates for archived caches.
See here: https://www.geocaching.com/seek/nearest.aspx?u=Lineflyer

I have no idea why c:geo in this cases uses some random(?) coordinates or maybe the users home coordinates (that would at least match in my case).

Anyway as this old server method is depracted more or less on the website and this case is quite special, I guess it will not be worth fixing but instead work on other newer/better method to perform searches on the server (which are already mentioned in other issues and tasks).

**Comment by Lineflyer** [comment]
Closing here due to reasons mentioned in my last posting.

**Comment by jakedot** [comment]
maybe remove Unverified, because you saw it as well?
