### ISSUE TITLE
Offline log checkmark barely visible

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#7630]
##### Detailed steps causing the problem:
- mark a cache with one-click-offline-log (e.g. found it)
- later, return to that cache, open the one-click-offline-log menu. 

##### Actual behavior after performing these steps:
The checkmark is barely visible as slightly changing shades of grey

##### Expected behavior after performing these steps:
The checkmark to be clearly visible

##### Version of c:geo used:
2019.04.16

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
![Screenshot_20190520-215416_cgeo](https://user-images.githubusercontent.com/3382777/58045034-000a9280-7b4a-11e9-9111-01b46ebca67e.jpg)

**Comment by Lineflyer** [comment]
Confirmed also with current master

**Comment by okainov** [comment]
Wow, what is this "one click log" feature? I never heard of it :)

**Comment by Lomanic** [comment]
https://cgeo.droescher.eu/en/offline#offline_logging (also discovered this great functionality with this issue).

I don't reproduce on Android 7.1.2, looks to depend on font used/installed.

**Comment by moving-bits** [comment]
Could not reproduce in the emulator with Android 7 or Android 9.
@andrixnet  @Lineflyer  Which device & which Android version were you using? Emulated or physical device?

**Comment by andrixnet** [comment]
Physical device, Samsung Galaxy S9 plus, Android 9, Samsung One UI version 1.0

**Comment by Lineflyer** [comment]
Physical device, Samsung Galaxy S10, Android 9

**Comment by Lineflyer** [comment]
Culprit in the code seems to here, where it is simply appended to the text, which somehow does not survive with the desired color during styling:
https://github.com/cgeo/cgeo/blob/442a4cb003a524ac4241866ca785190cbadd6e96/main/src/cgeo/geocaching/log/LoggingUI.java#L49

**Comment by SammysHP** [comment]
✔ is U+2714 "Heavy Check Mark", implemented as emoji on most modern platforms. Emojis do not use the text color but rather their own color (compare with all the colorful icons you will find in messengers).

**Comment by fm-sys** [comment]
Easy solution would probably be to use „✓“ (U+2713) instead...

**Comment by okainov** [comment]
Maybe just replace it either to some more ascii-friendly symbol or to emoji with more colours like ✅?

**Comment by Lineflyer** [comment]
I have an affected device (Samsung S20) and tested using U+2713 instead of U+2714 and its visible again. 
Will provide a PR.
