### ISSUE TITLE
Check if icon change is needed due to updated Google specs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7631]
Google Play informed, that there is a new specification for app icons:
https://developer.android.com/google-play/resources/icon-design-specifications

There will be a legacy (smaller) version used as of June,24th 2019 if nothing is changed. So it is not urgent, and I even do not know if any changes to our icon might be recommended due to these updated specifications.

Maybe a topic for @SammysHP to take a look at?

**Comment by jakedot** [comment]
I have seen some icons in major apps revert to the standard "Anrdoid app" icon on some devices. E.g. the GS Geocaching app on my BV P6000, the WhatsApp on a CAT S30, ... and I think it is related to this change. 

I hope that c:geo is not affected, but I agree it doesn't seem urgent.

**Comment by Lineflyer** [comment]
This is the preview of options on Google Play Console:
![grafik](https://user-images.githubusercontent.com/949669/58128012-fbf87680-7c16-11e9-896f-04e79d43f49e.png)

**Comment by bekuno** [comment]
Did we have any changed icons?
I didn't really notice anything of it.

**Comment by Lineflyer** [comment]
No, otherwise this issue would probably be closed.

**Comment by moving-bits** [comment]
fixed with 37f0a9c
