### ISSUE TITLE
api.geokretymap.org replaced by api.geokrety.org

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7638]
From @kumy in #7615 & https://github.com/GeoKretyMap/gkm-api-php/issues/13
https://api.geokretymap.org will be deprecated and replaced by https://api.geokrety.org (Fusion of GKM and GK projects)

**Comment by kumy** [comment]
Isn't it a duplicate of #7615 ?

**Comment by bekuno** [comment]
No, this was only for the export-details.php script.
