### ISSUE TITLE
Not saved caches not shown in history

### ISSUE THREAD

**Issue by mortonfox** [cgeo/cgeo#764]
I have the latest c:geo (ver. 31.10.2011) running on Android 2.2.

I posted some geocache found logs over the weekend using c:geo but when I checked the History list, not all of those geocaches are in the list. I think the History list is missing about half of the geocaches that I logged, even though those geocaches show up in Quick View on the geocaching website. What could be going wrong?

**Comment by Lineflyer** [comment]
Duplicate of (the newer) issue #4086.
