### ISSUE TITLE
cache.logCounts is  lost when cache is cached

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7640]
##### Detailed steps causing the problem:
- Open Live map
- Click on non-saved cache
- From CachePopup click "save" and save the cache
- If you put a breakpoint somewhere aound `getCacheFromCache` method, you will see that the cache contains `logCount` - everything is good.
- Return back to the map, click on the same cache again
- If you check breakpoint around `getCacheFromCache` then you can find out that cache doesn't contain proper `logCount` any more.

This also leads into `getFindsCount` reporting zero even if the cache was stored.

##### Other comments and remarks:
I observed this when trying my PR #7441, apparently logCounts are not cached as expected

**Comment by bekuno** [comment]
The same reason as on #7593 & #7634 ?

**Comment by Lineflyer** [comment]
> The same reason as on #7593 & #7634 ?

Most probably for my understanding. I already suspected the cacheCache to be the reason for it.

If someone wants to take a deeper look into these issues I recommend to use extreme caution as I remember from the past that changes to this cacheCache logic almost always had unexpected consequences.

**Comment by fm-sys** [comment]
Cannot reproduce the issue, or at least it has no visual impact. Let's close this stale issue...
