### ISSUE TITLE
Can't log in to geocaching.com

### ISSUE THREAD

**Issue by ahstro** [cgeo/cgeo#7643]
##### Detailed steps causing the problem:
- Install c:geo
- Enter correct info in auth fields
- "Check authentication"
- "Login failed: Unknown error"

##### Actual behavior after performing these steps:
A popup saying "Login failed: Unknown error" shows up

##### Expected behavior after performing these steps:
Should authenticate with geocaching successfully

##### Version of c:geo used:
Tried with `2019.05.20`, `2019.04.16`, and `2019.04.04` from fdroid.cgeo.org

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: ONEPLUS A3003 (lineage_oneplus3, OnePlus)
Android version: 9
Android build: lineage_oneplus3-userdebug 9 PQ3A.190505.002 7583abdac0 dev-keys
c:geo version: 2019.05.20
Google Play services: enabled - 0.2.6.13280
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (9.7 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (9.7 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (9.7 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (4.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (No Login information stored)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
No errors or warnings show up in logcat

**Comment by mucek4** [comment]
Well. the log you posted says: 
Geocaching sites enabled:
   geocaching.com: Not logged in (No Login information stored)

**Comment by Lineflyer** [comment]
@mucek4 Thats normal after the login failed as incorrect login does not get stored.

@ahstro 
Did you try to reset the login (via long click) as described in our FAQ:
https://faq.cgeo.org/#login-failed

**Comment by ahstro** [comment]
@Lineflyer Thanks for trying to help 😊 I tried that, but nothing seemed to happen when long pressing. I've also tried clearing storage, and even uninstalling and downgrading the app, which I assume would offer similar benefits as just resetting login info.

**Comment by Lineflyer** [comment]
Are you able to read out an adb log? That would help to analyze these random "unknown errors" some users have.

**Comment by Lineflyer** [comment]
Additional questions:
- Does this unknown error occur on WLAN and on mobile network?
- Do you have any anti virus or firewall SW installed on your device?
- Can you check on geocaching.com via PC whether you can login normal there and whether your mail address is validated?
- Can you check if enabling "identify as Android Browser" in Menu - Settings (Last option on the page) changes anything?

**Comment by ahstro** [comment]
Alright, figured it out (kinda). For some reason, [AdAway](https://github.com/AdAway/AdAway) was messing with the authorization. I disabled it and could log in after rebooting.
