### ISSUE TITLE
github: add bot removing repeating Codacy comments

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7652]
It's so nice when extra Codacy comments get removed. See geokrety-website repo where they implemented bot to leave only the last Codacy comment. 

Especially helpful for long PRs with several review iterations

**Comment by jakedot** [comment]
Hi, good idea, while considering changes to bots a little personal question:

There is a bot associated with the phrase "retest this please" (and I hope
it doesn't do anything here now :D) - I think it does a Jenkins build,
right? What about having it provide feedback when it's finished, while
removing old feedback just like codacy bot should?

**Comment by jakedot** [comment]
If it already does just that and I'm simply too tired to remember sorry and
please mentally change the above to: Good idea, I'd like to try help doing
it if I were on the team!

**Comment by fm-sys** [comment]
Probably this issue is outdated as today Codacy removes old comments automatically. Or did I misunderstood the issue?

**Comment by moving-bits** [comment]
This is already in place meanwhile, if I'm not mistaken. Closing this issue for now.
