### ISSUE TITLE
open single GC cache does not finish

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7655]
From FB:

GC5RWXD

Dieser Multi lässt sich mit c:geo nicht öffnen und nicht speichern. Weiss jemand, woran das liegt?

Bei mir hängt er im Schritt "verarbeite Wegpunkte"

**Comment by jakedot** [comment]
The LOOKUP code fields are empty. I'm not sure if that's allowed.

**Comment by Lineflyer** [comment]
I have never seen a cache with empty lookup codes... strange.
Anyway we should handle this somehow.

**Comment by Lineflyer** [comment]
I have to correct myself.
Also for my cache GC7VB9J I do see, that several waypoint do not have a lookup code. The (new) owners editor does not have any explicit field for the lookup code but only for the prefix. The lookup code gets however auto filled for some of the waypoints but I do not see a rule for that.

**Comment by jakedot** [comment]
Sorry that I didn't mention it before: I cannot say if this is the cause, I didn't debug it or anything as I still haven't managed to set up the IDE correctly...

Did your cache have the same problem?

**Comment by Lineflyer** [comment]
> Did your cache have the same problem? It loaded correctly for me, so if the cause has something to do with lookup codes it might be when there are no waypoints with one at all.

Yes, my cache loads fine also for me with c:geo.

I don't think it related to the lookup code as this is missing also in other caches, e.g.:
https://coord.info/GC87REZ

**Comment by bekuno** [comment]
After check the code and the website and then with the debugger - there is a false line in the website.
We search for the table with the parsing the string "id="ctl00_ContentBody_Waypoints"".
In the problematic site are two such code points.
The first, false one is before "Dann los zum Start und viel Vergnügen :-)"
Here our parser stops.

@Lineflyer Maybe we should open a bug report at GC?

**Comment by jakedot** [comment]
It's probably not their fault, but more likely that the user unknowingly copied that link into the description, as the surrounding code is part of the user supplied content... I'll reply to the original raiser of the issue on Facebook to advise the owner. Thanks for investigating!

**Comment by jakedot** [comment]
After some thinking about it: Shouldn't we ensure this doesn't happen again? Seems to be a mistake that is easy to make (inexperienced users copying part of HTML for their new listings)...

Maybe it's really also worth a bug report to GS, they could filter such IDs pretty easily...

**Comment by bekuno** [comment]
Make our current string based parser harder for such problems is not easy. We could implement regex to check - but we don't know wich part will be copied in the user field.
Other solution would be to implement the parser completely new with based on the site xml tree or use the GS API, both has other disadvantages.

**Comment by Lineflyer** [comment]
IMHO this is not a clear bug at Groundspeak, while its still strange, that they do not check IDs are contained in the user description, which are in conflict with their site design elements.

However I would not change anything on our side, seems a very rare case to me.

**Comment by Lomanic** [comment]
@bekuno I'm curious, what do you think are the disadvantages of using a real parser (say, jsoup) to query an HTML document instead of homegrown regexes as currently in cgeo? That would notably make it more reliable (to site changes, to this kind of bugs) and easier to develop on (regexes are quite known for being write-only).

**Comment by jakedot** [comment]
I've used Jsoup before and my experiences were that yes, it makes such stuff quite easy. Would recommend. But I don't kbow about the current code and if there are foreseeable issues with replacing it.

**Comment by bekuno** [comment]
@Lomanic The statement was more general in nature. A complete reimplementation with an html parser should be an improvement. Probably the problem would not have occurred in this case. The challenge is that c:geo is a complete leisure project. Even though all developers are enthusiastically working on it, the time budget is limited. Therefore such large rebuilding measures are not easy to accomplish and therefore prone to errors again.

**Comment by bekuno** [comment]
@jakedot see also the discussion in #7305

**Comment by bekuno** [comment]
@jakedot You are welcome to make a code change. There are many open issues.

**Comment by Lomanic** [comment]
Thank you @bekuno for your reply. Looks like replacing regexp parsing by jsoup or similar is what #1806 or #6054 is about. One day I would like to take some time spinning up an Android dev environment and work on this, this is an historic issue of cgeo.

**Comment by jakedot** [comment]
@bekuno @Lomanic well I'm in the same situation I'd really like to start working but I can't get the config of Android Studio and git to play like I want them to...

**Comment by Lineflyer** [comment]
@jakedot @Lomanic 
If you need assistance you should try to reach some of the team on our IRC channel (freenode.net #cgeo). Best time is evening hours (europe) or weekends.
Else feel free to open an issue here with details about your setup and the problem you are having to get it working.

**Comment by Lineflyer** [comment]
Rereading this bug report, there is at least one thing we should do better:
If we fail to read the waypoint data after finding the (in this case wrong) identifier, we should at least silently fail after a timeout and show the cache without the waypoint data IMHO.

**Comment by bekuno** [comment]
> @jakedot @Lomanic
> If you need assistance you should try to reach some of the team on our IRC channel (freenode.net #cgeo). Best time is evening hours (europe) or weekends.
> Else feel free to open an issue here with details about your setup and the problem you are having to get it working.

Hint: You can use our IRC history on https://irclogs.cgeo.org to see answers if you were offline in the meantime.

The cgeo README.md should answer most question, but sometimes AndroidStudio is kind of bitchy.

**Comment by jakedot** [comment]
Thanks mates, unfortunately I'll have to delay the hacking because of
severe case of travel fever. I was at the train station waiting for my
train back home but then at the same platform, 5min before my scheduled
one, a late night train was squeezed in... So lomg story short, I'm now en
route to Zagreb and will come home on Sunday at the earliest. Let's see how
many cointry points I can grab! 😂😇

**Comment by moving-bits** [comment]
You'll also find some information in our README:
https://github.com/cgeo/cgeo/blob/master/README.md

as well as in our c:geo Wiki:
https://github.com/cgeo/cgeo/wiki/Android-Studio
https://github.com/cgeo/cgeo/wiki/git-beginners

which might be helpful to you (depending on where you got stuck).

But, as mentioned earlier:
> sometimes AndroidStudio is kind of bitchy.

Then restarting AS or even reinstalling AS or some of its components (SDK, emulator etc.) helped :-(

**Comment by Lineflyer** [comment]
this topic has never shown up again and the original reported cache is either fixed or c:geo copes with it now.
