### ISSUE TITLE
Next feature release - 2019.08.18

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7665]
Quote from #7661:

After a review of recent changes on both branches I suggest the following:

- ~Release from current `release` to have the fix for #7647 out on the market asap~
- Merge the following PRs (if considered OK) to `master` next days:
  - [x] PR #7659
  - [x] PR #7657
  - [x] PR #7641 
  - [x] PR #7669
  - @cgeo/team Any others?
- [x] Some days smoke testing with nightly builds
- [x] Merge `master` to `release` and publish beta version

Doing this way we can have a new release (with minimum risk and fix for OSM) asap and the longest possible beta testing period for the reviewed changes and a new playground for fresh changes.

**Comment by jakedot** [comment]
When do you want to do the release? Ok, the listed PRs should probably all be done before the release, but maybe I can patch in the circle stuff in time if it's supposed to be, say, mid to end of next week.

**Comment by moving-bits** [comment]
As for the last step with the "more experimental" PR: What about merging the GMv2 branch as well, to bring it more into our focus and start fixing the open issues?

**Comment by Lineflyer** [comment]
> As for the last step with the "more experimental" PR: What about merging the GMv2 branch as well, to bring it more into our focus and start fixing the open issues?

Well, why not if someone feels a bit engaged to work on it and fix the remaining bugs.
But then in the last step (as described above) to maximize our time for getting it clean.

**Comment by Lineflyer** [comment]
Added PR #7669 to list of PRs to be merged before branching.

What about PRs #7612, #7575, #7441 ?
I labeled them with "Feedback required" and assigned the team members which have outstanding feedback/review there.

**Comment by moving-bits** [comment]
Please replace #7625 by #7690 in your list.

**Comment by Lineflyer** [comment]
All PR mentioned in the initial posting (and some more) have now been merged to `master`.
I suggest to wait for some days of testing in nightlies and maybe fine tune some things (as e.g. mentioned in #7699) and then merge to `release` to be able to issue a beta release.

I did not follow recent activities (e.g. regarding OC attributes), so feel free to mention here if things should come into `master` before branching.

**Comment by Lineflyer** [comment]
Just FYI:
I merged some recent PRs as I am currently on a longer bike trip and have the chance to use and test the newest nightlies.

After my return I will review and propose the further progress on next release and branching.

**Comment by moving-bits** [comment]
@Lineflyer  Thanks & have a nice trip!

**Comment by Lineflyer** [comment]
Back from trip and I think current `master` is working quite reliable.

So from my side we could continue with the next step to merge `master` to `release` and push a beta version to the users.

Anyone available to perform the needed merging operation (and maybe upload strings to Crowdin)?

**Comment by Lineflyer** [comment]
@rsudev Do you have time to fast-forward the release branch?
AFAICS you might be the only one around capable of this.

**Comment by rsudev** [comment]
@Lineflyer: What do you think about @moving-bits proposal? I can merge maser to release today.

**Comment by Lineflyer** [comment]
Sorry...was out caching quite long today. Well I did not test the PR. But I can do that also on release.

@rsudev 
I will merge that PR now and you can merge brnaches right away as time permits.

**Comment by rsudev** [comment]
Merge done.

**Comment by Lineflyer** [comment]
Thanks. Will doublecheck and do whats needed.

**Comment by Lineflyer** [comment]
@rsudev 
Merging looks good. I will give `release` build a try and publish a beta version next days.
Can you also upload strings to crowdin? There should be a big bunch of new strings.

**Comment by rsudev** [comment]
I will do it tomorrow (will get home too late tonight)

**Comment by Lineflyer** [comment]
@rsudev 
While on it, could you write a manual into our Wiki to enable others to do that as well? Or is there already a manual?

My dream would be a CI job for this purpose ;)

**Comment by rsudev** [comment]
There is a page for this on our wiki (https://github.com/cgeo/cgeo/wiki/Translation-%28L18N%29) and also some explanations in the associated folder in the source. You need to be a manger in the crowdin project to get the necessary access key.
Unfortunately this is not as smooth as I would wish for, especially due to the crowdin branches feature not fully working as expected (you still can get different translations on different branches for the same string from the API, but you normally would not see them in the UI).

**Comment by rsudev** [comment]
crowdin update done.

**Comment by Lineflyer** [comment]
FYI:
A new beta version 2019.07.25-RC has been published on the Google Play beta channel.

**Comment by Lineflyer** [comment]
The next release is now IMHO well prepared if it survives the beta testing.
On `master` however we could/should proceed asap with all the needed changes to get a working version with targetSDK28.

I follow recent discussions but I am not very clear of what needs to be done in which sequence:
- Raise the targetSDK 
- Implement mapsforge 0.11
- Use GoogleMaps V2

To get some experience with those changes (without knowing the technial required depedencies) I suggest to merge Google Maps V2 as fast as possible to `master`.
Thanks to the dedicated branch used up to now I was able in the past months to report some issues I found (which needs to be fixed IMHO) but also found, that GMapsV2 is basically working.

Can someone enlighten me regarding the required steps and sequence or provide his ideas for it?

**Comment by moving-bits** [comment]
We do need to get targetSDK 28 running by November this year, so this is a "must have" and should be started "asap".

If mapsforge 0.9 does not work with targetSDK 28, it has to be upgraded first (whether to 0.10 or 0.11 is TBD).

Regarding Google Maps v1 I do not remember whether this works with targetSDK 28. If yes, it can be number three, if not, it should be number one or two. - A step to prepare for this could be to update the GoogleMapsV2 branch to the current master.

**Comment by jonas-koeritz** [comment]
GoogleMapsV2 should work with both the old, and the new targetSdk. Jumping
to API 28 would be priority number one.
Mapsforge needs to be updated as well because of compatibility issues.
The performance of mapsforge 0.11 seems to be "not good, not terrible",
someone should investigate that or open a bug with mapsforge.

moving-bits <notifications@github.com> schrieb am Fr., 26. Juli 2019, 10:24:

**Comment by Lineflyer** [comment]
OK, mf.011 is merged and working.

What about GMapsV2?
As stated earlier the implementation currently on branch `GoogleMapsV2` works for me with some regressions (already [documented in issues here](https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Map+Google%22) ). So if someone dares to migrate it to master and would also be available for bugfixing we could do that.
Alternatively we could work the branch by bringing is closer to `master` and fixing some regressions  on the branch. As we have [nightlies for that branch](https://download.cgeo.org/cgeo-nightly-GM.apk) its relatively easy to try it out.

**Comment by Lineflyer** [comment]
BTW: We should continue Google Maps V2 specific discussion in #2222 as this issue is more about the state we do now have on our `release` branch.

**Comment by Lineflyer** [comment]
Did a quick check on Google Play console:
Seems the RC/beta is doing good so far. At least I do not see any significant new crashes or bad feedbacks yet.

**Comment by Lineflyer** [comment]
Just pushed a new RC version 2019.08.01-RC to Google Play beta channel.
Changes from last RC is the map scaling improvement for OSM online maps and the fix for proximity notification in compass.

**Comment by Lineflyer** [comment]
Now the beta version is out for roughly two weeks without significant negative feedback, which I know of.

We still have #7460 which changed somehow with the beta but is also present in the current stable release out there (see also my recent comment in that issue).

My suggestion would be to release tonight, to bring us one step nearer to the work to do on `master`.

**Comment by rsudev** [comment]
Unfortunately only today I managed to put up the small and simple mitigation for #7460 (that might reveal the next level of quirks - but perhaps silence it).
Independently of that did I pull in some translations that arrived lately.
So two PRs which can be merged to release if it seems sensible at this stage - or I cancel them and re-issue for master.

**Comment by rsudev** [comment]
@Lineflyer what do you think?

**Comment by Lineflyer** [comment]
Feel free to merge to release!

**Comment by Lineflyer** [comment]
About to start the release process based on current beta version + 2 changes (translation and mitigation of exception issue) as reference by @rsudev above.

## Release checklist for full release:

- [ ] Check/Import incoming Translations from Crowdin
- [ ] Check/Insert correct version name as headline in ```changelog-release.xml```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
Release has been pushed to Google Play and its digesting it now.
Will follow up tomorrow with the remaining steps.

**Comment by Lineflyer** [comment]
Release 2019.08.18 is out and working smooth up to now.
Thanks all for your contributions.
