### ISSUE TITLE
Opencaching.de Auhorization not working

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#7666]
A user reports on FB that their [Authorization with opencaching.de stopped working](https://m.facebook.com/groups/1417362088562367?view=permalink&id=2103055236659712&anchor_composer=false) with the new update.

Was there something involving that?

Also, Google Maps don't work anymore and are not even displayed in the selection menu.

Old android version, probably 4.4.2 - is that even still supported by us?

**Comment by Lineflyer** [comment]
No change in those areas.
4.4.2 is supported. Reboot will help probably.

Regarding OC authorization the user should also check his time and date settings.

**Comment by jakedot** [comment]
As we have issue #7668 now about general failures for Authorization on all
services in release, you may want to close this one @Lineflyer - I can't,
am almost offline because of broken phone. Can't access github login, only
email. Thanks!

**Comment by bekuno** [comment]
No, not so fast.
That's an other problem.
The latest official version, beta version and nightly work correct.
The problem in #7668 references to the development version an my machine.

**Comment by jakedot** [comment]
Oh, alright then, I thought that was it. Then maybe remove the unverified
label if you think it is sufficiently the reverse? ;)

**Comment by jakedot** [comment]
Sorry but as I was on the go with broken phone I could not ask the user very well about the state of the problem, checking now, they haven't reported any new errors, nothing about it getting better also though.

So I will wait a bit longer for updates, if there are none, feel free to close the issue if you cannot reproduce / have fixed related stuff and it isn't observed anymore.

**Comment by jakedot** [comment]
No luck, user reports persistent problems now, @Lineflyer can you "take it from here"? I'm not going to be any help in the next days, too much to do, sorry.

**Comment by Lineflyer** [comment]
@jakedot I just see this old open issue. AFAIR the problem was resolved by the user already.
