### ISSUE TITLE
Make filtering map by unsaved caches easier

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#7667]
**Is your feature request related to a problem?**
A user [feature request / [bug] question](https://m.facebook.com/groups/1417362088562367?view=permalink&id=2102994996665736&refid=18) from FB:

The orange map circles are gone, which once signalled incomplete cache data. The user always used those to quickly find new caches in their region or wherever else they already had a lot of saved caches.

Now that the new map implementation doesn't have inaccurate coordinates anymore, this useful "feature" isn't there anymore. 

**Describe the solution you'd like**
Thus, we should:
- think about reusing the orange circles for just any unsaved caches, or
- implement a new map filter option for `unsaved caches`,
- or both,
if we want to continue supporting this use case.

**Additional context**
Screenshots of discussion on FB as of now:

![Screenshot_20190608-024027](https://user-images.githubusercontent.com/12250212/59140136-2463cd00-899a-11e9-9c7a-c5991bfc8626.png)
![Screenshot_20190608-024057](https://user-images.githubusercontent.com/12250212/59140137-24fc6380-899a-11e9-8891-7dbaec37c7ac.png)
![Screenshot_20190608-024102](https://user-images.githubusercontent.com/12250212/59140138-2594fa00-899a-11e9-9670-bd2e40d0a8cb.png)

**Comment by jakedot** [comment]
Workaround I posted on FB:

1. Select wanted map area
2. Menu -> Show as list
3. List filter by "Status - Unsaved"
4. for remaining list, use "show on map"

This is a bit too complicated for my taste...

**Comment by moving-bits** [comment]
I would also prefer orange circles for unsaved caches over some menu filter options.

**Comment by Lineflyer** [comment]
I would prefer not to reuse a visualization which was used for another purpose over years.When I see orange circles I know, that the position on map is not correct,  but this is now no longer the case.Also for users not using saved caches all caches on map would have it. How about making saved caches more visible instead?Von meinem Smartphone gesendet.
null

**Comment by jakedot** [comment]
I know it is probably a choice of flavor (sorry for German proverb) but I
would, as the user discussion argues, prefer a more visible unsaved one.
The saved caches are already shown with the Discette icon, but as you say
it is a bit small and new users might not notice it.

Well yes, in areas you haven't any saved it would be obtrusive, but the
same can be said about an area with saved ones if they are to be made more
visible.

**Comment by moving-bits** [comment]
> I would prefer not to reuse a visualization which was used for another purpose over years.When I see orange circles I know, that the position on map is not correct,  but this is now no longer the case.

Understood. So maybe a different color?

> Also for users not using saved caches all caches on map would have it. How about making saved caches more visible instead?

Hm, probably depends on the way you are using c:geo. Normally I use saved caches only. Sometime I enable live map to see if there are new caches. So the saved/unsaved ratio is >>1 for me - therefore I would favor highlighting unsaved caches over making saved caches more visible.

**Comment by SammysHP** [comment]
I already answered this at geoclub.de several days ago: https://geoclub.de/forum/viewtopic.php?p=1297206#p1297206

The origin of this request is a misunderstanding of the (now non-existent) orange circle that marked *inaccurate coordinates* previously, but not the save state. Whether a cache was stored offline or not was always visualized by the little floppy disk icon, similar to "has corrected coordinates".

I would not highlight non-saved caches, as @Lineflyer already described. I'm also not sure about highlighting saved caches as this would emphasize a single feature that might not even be the most important feature in this context. I admit that the little floppy icon might not be visible enough (especially with high cache density), but it's the same with other attributes. I suggest to improve filtering capabilities instead.

**Comment by moving-bits** [comment]
> The origin of this request is a misunderstanding of the (now non-existent) orange circle that marked _inaccurate coordinates_ previously, but not the save state.

I know that this was a misunderstanding. But a very common one. So the question is: Are _unsaved_ caches visible enough? (It's not about saved caches.)

**Comment by SammysHP** [comment]
You can always use the "store unsaved caches" feature just to make sure all visible caches are stored for offline use.

**Comment by Lineflyer** [comment]
I think @SammysHP conclusion might be the best. Just have a filter or switch on the  app to toggle hiding depending on save state: Show saved / Show unsaved / Show none (hiding all is another issue listed here somewhere but fits perfectly to be included for such kind of filtering).

**Comment by jakedot** [comment]
> You can always use the "store unsaved caches" feature just to make sure all visible caches are stored for offline use.

I disagree, and this is part of the reason I created the issue in the first place, else I would have been perfectly fine with just finding the workaround for them.

The users work case never was to just throw all unsaved caches into one big melting pot and save them, make them equal to the other ones, no, for them it is about selecting stuff they're interested in - guarding their collection if you will. They may have many caches saved as a percentage of total caches in an area, but it i about control of which ones get added when they pop up by getting published e.g. It runs contrary to that goal in the most basic sense to just save all and be done with it.

**Comment by jakedot** [comment]
BTW: Why are feature request issues taggesd as "Unverified" as well? Is that a team/non-team difference?

**Comment by SammysHP** [comment]
Previously there would have been a cache with orange circle. The user opened it, but didn't store it. Now the orange ring is gone but the cache is not stored. After a few days the cached data is removed and the orange ring appears again. The ring also disappeared if only the coordinates are known (detailed map mode). I still do not understand how this helped.

With the new filter system it should be easier to select a filter to hide stored caches.

**Comment by jakedot** [comment]
well, as far as I understand it it is a work flow that this one user had
with some important constraints:

1. they used it more for regions they don't regularly cache in, but have
many stored
2. they want to check before leaving/already en route/just because they do
so regularly, but
3. not frequently
- if there are new caches there worth FTFing or just looking at, but
4. without saving all of those considered to the device (many valid reasons
to do so, and just having the option to save or not implies that this is a
valid use case).

Now that I think about it, even I have done this unwittingly, e.g. when
going to Vienna or Bratislava which I do just as described:

- Somewhat regularly, so warrants saving caches long term
- infrequent enough that the unsaved, "session-cached" data disappears
between use,
- saving all caches could be pretty time and data intense!! Not to mention
having to weed out the "bad apples" you're just not interested in.

----

I do realize that most of the stuff described above can already be done
quite well with filters, but still feel like highlighting unsaved caches
might be a good idea. Maybe make it a configurable setting if you think
users will be confused by new colour/icon/whatever?

Thanks for all the input so far, I feel *almost* like a productive *member*
of this project!

**Comment by okainov** [comment]
>The origin of this request is a misunderstanding of the (now non-existent) orange circle that marked inaccurate coordinates previously, but not the save stat

I can be wrong, but I think it was like this for **you, dev team who knew the background**. For all the users it meant something like "new cache, not saved, not viewed. And in 99% of the cases it had nothing to do with the cache position, because I saw "jump" of the cache very few times, it was not anyhow important. And TBH I was also a bit confused when I saw no more orange caches after PR changing way of retrieving caches, I got used to see it as "new" caches.

**Comment by SammysHP** [comment]
That's why the first few starts of the live map opened a popup explaining what the color means. ;)

**Comment by jakedot** [comment]
> I can be wrong, but I think it was like this for you*, **dev team who
knew the background*.**

100% my thinking

**Comment by SammysHP** [comment]
Then it's good that we have finally removed this misunderstood visualization.

**Comment by rsudev** [comment]
To add to the confusion for those who never read the popup, in default settings there was a search started in the backgroud to retrieve a bunch of caches around the center of the map with correct coordinates. So those never showed the orange circle in the first place while still being 'new, never looked at before...'

**Comment by jakedot** [comment]
Well now people (at least original issue on FB, me and other commenters
here) are "misunderstanding" the new behaviour.

If you all think the current state is fine, then we should at least update
FAQ a bit with regards to this confusion, if not already happened.

**Comment by rsudev** [comment]
I think the current state is fine regarding the absence of orange circles and imprecise coordinates.
Instead of discussing how a feature over the years was completely misinterpreted (for those interested in the background, the issues and discussions around the website-change which triggered this implementation are still available), I would suggest to rather try to describe a use-case originating from the need users tried to solve with the misinterpreted orange circles.
For me personally (after a short time of adaption) is the distinction between stored/non-stored caches by the indicator good enough and I also normally just store all caches I do not have yet stored on a newly created 'scratch list', maybe moving them to somewhere else later.

**Comment by jakedot** [comment]
@rsudev: Yes of course, good point on the discussion (I'm not sorry to have
started it).

On the use case: I would personally use it like you describe, lists are
great. Filtering them also works good. But still I feel the user's way of
doing things is valid as well - if just to avoid unnecessary data, time and
organization consumption/effort.

Maybe for this there would need to be a way to selectively only download
the bare minimum cache details (no logs, no pictures) as an ultra low
data/load time saving. But caches downloaded in such a mode would again
need to be really visibly marked, just like the old orange circle.

I think this was the intention of the old behaviour, and it was pretty
good. Sorry I don't have the time and technical ability right now to read
through the old discussions, as I'm still without functioning phone (can't
even install c:geo and go out caching T_T)

**Comment by Lineflyer** [comment]
> BTW: Why are feature request issues tagged as "Unverified" as well? Is that a team/non-team difference?

This is the default for newly created issues (since some days) which should signal, that someone of the team should review the new issue and judge, whether it is a valid request.
At least this was my thinking when creating those new templates. We will see, if this is a good process or not.

**Comment by jakedot** [comment]
I was just thinking, semantics, how can a `feature request` be `Unverified`?

The author should usually be quite sure about what they wanted.

Not an issue at all with the process from my side.

**Comment by SammysHP** [comment]
What about "triage"?

**Comment by jakedot** [comment]
Is that proper english? "triage" makes me think of "triad" or "triumvirat".

Am Mo., 10. Juni 2019 um 21:56 Uhr schrieb SammysHP <
notifications@github.com>:

**Comment by rsudev** [comment]
> I was just thinking, semantics, how can a `feature request` be `Unverified`? The author should usually be quite sure about what they wanted. Not an issue at all with the process from my side.

My experience is to the contrary. Users usually are not very good in expressing what they want. Most of the time the omit crucial information, or describe a solution in terms of their fragmentary understanding of the technical background and constraints instead of the real problem they have or what they want to achieve.

**Comment by jakedot** [comment]
Alright, that explains the current usage and the meaning of the tag,
perfectly valid then... I don't have too much to do with users at work, my
position is probably too junior / seperate from pro[du|je]ct management...

>

**Comment by SammysHP** [comment]
@jakedot Yes, triage is an English word / word used in English. Some bug trackers use it or a similar form.

**Comment by jakedot** [comment]
@rsudev 
> Users usually are not very good in expressing what they want. Most of the time the omit crucial information

Well yes, but still, how many "users" do we have here posting feature requests? The errors in such a submission may be more likely be a bug report issue, if somebody submits a feature request in the correct meaning of the word, I feel it can't be unverified. But alas, that's deep semantics. Just ignore me here, it's not like distinctions like this matter for the project.

**Comment by jakedot** [comment]
This isn't very relevant as the discussion showed. And there are the "store unsaved" menu options as well as the filter menu when showing the map as a list.
