### ISSUE TITLE
Positioning problem on some devices

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7673]
**Describe the bug:**
On support mail we have an unusual high amount of people having problems with localization, i.e. c:go shows "GPS not active" and/or own position is not shown on map and/or location is shown in Paris, France (our default if all methods fail)

**To Reproduce:**
Not clear, cant reproduce.
Seems to be related to some devices and/or Android versions

**Version of c:geo used:**
Starting 2019.05.20
I assume  28baa5ebc51891d27323adeaab8502bc829be5bd could be the problem somehow
@UniQP 

**Is the problem reproducible:**
No

**Comment by Lineflyer** [comment]
Users feedback is, that it works again after deactivating "Use Google Play Services" in c:geo settings, but they also confirmed it worked with Google Play Services on releases prior to 2019.05.20

**Comment by Lineflyer** [comment]
> I assume 28baa5e could be the problem somehow

I think my assumption is wrong, because the mentioned commit has not yet been released.

**Comment by bekuno** [comment]
did not work without deactivating the "google play service".
see screenshot:
(headline in german, system language: en)
![Screenshot_20190703-235957_cgeo](https://user-images.githubusercontent.com/32555742/60629250-47489c00-9df5-11e9-98ed-6b94551198fc.jpg)

**Comment by bekuno** [comment]
The method resources.updateConfiguration is deprecated at API Level 25.
https://developer.android.com/reference/android/content/res/Resources#updateConfiguration(android.content.res.Configuration,%2520android.util.DisplayMetrics)
Therefore this method call in CgeoApplication.initApplicationLocale() does not work correct anymore from Android 7.1.1 (N+).
There are some solution ideas in StackOverflow, e.g.
https://stackoverflow.com/questions/40221711/android-context-getresources-updateconfiguration-deprecated
https://stackoverflow.com/questions/54774485/android-context-getresources-updateconfiguration-deprecated-how-to-resolve

**Comment by Lineflyer** [comment]
@bekuno 
I think you misinterpreted my issue title (or I chose a bad title). This issue is about problem to localize the device position.
But there is another issue (which I cannot find) where this is the root cause. Something with not being able to switch to english?!

**Comment by Lineflyer** [comment]
Found it: #7053 might be what you wanted to comment on.

**Comment by bekuno** [comment]
@Lineflyer You are right.

**Comment by Lineflyer** [comment]
Comments moved to #7053 and deleted here :)

**Comment by Lineflyer** [comment]
Lets close this rather old issue, as there are no such user complaints since a long time.
