### ISSUE TITLE
Use menu entry for TTS in popup rather than button

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7674]
Having just tested the new TTS feature on the popup #7670 I am a bit unsure about the activation method:
The activation via the button is simple and easy but maybe still not the best way, because:
- It clutters the relatively small popup window
- The TTS feature might be relatively rarely used compared to the other frequently used buttons like Details, List Management and Refresh.
- It might happen easily to accidentally activate it
- Its not placed consistent with other navigation options from that point

Due to the reasons mentioned above I would suggest to have it as menu option behind the three-dot-button instead (same as in compass activity).

It would be even more consistent to instead have it implemented as an additional generic navigation method. This would have the additional benefit, that it becomes available in all places where the Navigation menu is offered. But I guess, this might require some thinking about a user interface as there has to be a method to stop the navigation.

@moving-bits 
-

**Comment by moving-bits** [comment]
Although I liked the handy way to access tts function in cache and waypoint popups I do understand your concern. I created PR #7680 to switch from buttons to menu entry. Let's see how this works out.

**Comment by Lineflyer** [comment]
Thanks for providing the new PR.
Regarding the preference to have it as button or in menu I would have expected also feedback by others. However as you agree to my concern, lets go with the menu then.
