### ISSUE TITLE
Mystery message

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#7675]
I get a weird message I can’t fully read, which says something about Google on my Google-free Android, and which overlays the one I normally use to d/l a newer nightly.

![_20190612_221915](https://user-images.githubusercontent.com/861078/59383791-f1865400-8d60-11e9-8cf3-2a2c5756a1ec.JPG)

**Comment by Lineflyer** [comment]
This is a custom message we issued to our users to get feedback on Google Play as there are quite some users which are trying to use c:geo without login.
Your display resolution is relatively small, which makes it run into the menu.

No need for any action. We will remove it after some days.
We have no technical solution to only issue this notification to users, who downloaded from Google Play.

New nightly notifications should IMHO have prio, so you will see them.

**Comment by Lineflyer** [comment]
BTW: You might be able tofully read it when rotating your device.

**Comment by mirabilos** [comment]
Lars dixit:

>New nightly notifications should IMHO have prio, so you will see them.

No, this is a nightly a week or two old, so…

>BTW: You might be able tofully read it when rotating your device.

“Live map take a second to raNearbyo on Google Play by cStored on this”

Almost ;-)

Why those messages are overlaid by icons instead of all of the
content laid out well on the screen, I’ll never know.

>We have no technical solution to only issue this notification to
>users, who downloaded from Google Play.

Ah, too bad then. You should have a different codebase for them,
as it’s a proprietary service. At least some identifyer.

But thanks for clearing it up.

**Comment by jakedot** [comment]
I agree some identifier should probably be there, if only to not confuse users. If I download the apk directly, (and maybe don't have play store installed,) I wouldn't expect to be told to rate the app / some other message regarding play store. Maybe the (jenkins?) build could be modified so there is different APK files for the different distribution channels (Play, FDroid, Website)? I'd assume that nightly and other test builds are already different from stable(beta)/release...
