### ISSUE TITLE
Enable oc.us in our (website) tests

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7676]
In social media I have read, that oc.us had severe problems during their site maintenance.
While the frontend (webserver) is online, the backend (database) is still dead, you cant even login.

They did not give a good indication how long it may take to repair. Maybe we should therefore disable the oc.us related (website) tests to make our CI return reliable test results.
Especially for the cyclic website tests of master and release branch I would like to get a real picture.

I tried with a method I used in the past (in PR #7672) but failed.
Maybe someone with a better understanding can temporary disable them and also provide a PR to reenable them (which can be merged later).

**Comment by rsudev** [comment]
There is one more test depending on oc.us (OkapiClientTest.testGetOCCache) which tries to download a cache from oc.us.
We can disable that one as well.

**Comment by Lineflyer** [comment]
Tests have been temporarily disabled with 88afe1cba0d1029628f4d2cc6a62125f8fc137f4 and 42e98f300cd26c379696c798d2d2872de666012f

Leaving this issue open and assigning myself to check site availability and eventually enable the tests again.

**Comment by Lineflyer** [comment]
Most probably we can enable those tests again.
I am away from PC, so if someone else could step in and revert the change...
Else I might do it in two weeks.
