### ISSUE TITLE
Unable to select a map theme for offline maps

### ISSUE THREAD

**Issue by ControlTheBit** [cgeo/cgeo#7681]
**Describe the bug:**
I updated my phone to Android 9 and I am having this issue since then.

When I go to Settings --> Map and click on "Map Themes Directory", I only get the following screen: 
![Screenshot_20190615-074923_Locus_Map](https://user-images.githubusercontent.com/9163917/59549214-ba26cb80-8f49-11e9-8bf1-c628ce16c376.png)

I cannot navigate out of this screen or choose a folder anywhere. Therefore I cannot select a map theme.

**To Reproduce:**
Steps to reproduce the behavior: As described in the "Describe the bug" section above.

**Expected behavior/state after performing these steps:**
I would like to get a similar menu like the one that you get when you choose a file. You an also choose which app you want to use to choose the file, so maybe something like that would also be possible to select a folder?

**Version of c:geo used:**
2019.06.06

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 9
Android build: lineage_shamu-userdebug 9 PQ3A.190605.003 0e7958dac7
c:geo version: 2019.06.06
Google Play services: enabled - 17.4.55 (100300-248795830)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (47.9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (47.9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (47.9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (684.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
You seem to be stuck in some empty directory.
If you click in either the three dot button or the button next to it, you should be able to jump to the base directory of your device and start selectin the directory from there.

**Comment by ControlTheBit** [comment]
You are right. I was able to navigate to the SD card, select the SD card
and then manually enter the path to the Themes folder. Thank you, solved!
