### ISSUE TITLE
show hidden waypoints of OWN caches

### ISSUE THREAD

**Issue by McKirni** [cgeo/cgeo#7683]
When i'm outside, controlling my own multis and mysteries, i always wonder, why the hidden waypoints of my caches are not downloaded.

first solution:
cgeo checks, if a GC-number is MY cache and download the hidden waypoints automatically
(i think, it's the same, as cgeo "knows", that an unpublished GC-number is MY cache and download the listing)

second solution:
on the "waypoint-page" there is a new button to download hidden waypoints manually

**Comment by Lineflyer** [comment]
Its technically not possible for c:geo to access hidden waypoints of owned caches, i.e. to get this information from the server on the normally accesible way.

Workaround would be to store coords of your hidden waypoints manually with creating new waypoints in c:geo.

**Comment by jakedot** [comment]
Another possibility for a workaround is to store the waypoints as a Geocaching.com Note, that should be downloaded in c:geo when accessing the cache first time / whenever you update the listing, and automatically generates the waypoints  for you. See [manual - notecoords](https://manual.cgeo.org/de/notecoords)

This should be easier as you can do the "waypoint management" that needs to be done manually on the website, in one central place.
