### ISSUE TITLE
Hide list content from live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7686]
Taken from a support mail:

**Is your feature request related to a problem?**
I use the live map and see caches, which are not suitable for me (e.g. T5 caches)

**Describe the solution you'd like**
As a user I would like to be able to mark one or more of my lists to be hidden in a way that all caches that are saved to that list will not be shown on any map at any zoomlevel so that I can make a selection of caches that I would like to ignore (for any reason. i.e. out of reach because I'm not able to climb trees) and these caches won't show up anymore (as long as I retain the list - of course).

**Comment by SammysHP** [comment]
This can be done with the "ignore cache" feature of geocaching.com (AFAIK premium member only).

I think the benefit of implementing our own blacklist is too small. It's not only the map, but also search results etc. It would require a huge refactoring (maybe using our filter system, but that would require multiple filters at the same time, which is another big unresolved topic).

**Comment by fm-sys** [comment]
> I use the live map and see caches, which are not suitable for me (e.g. T5 caches)

This is possible with the new filter framework. 

> As a user I would like to be able to mark one or more of my lists to be hidden in a way that all caches that are saved to that list will not be shown on any map.

This should be possible as well. The new filter framework is currently in beta... So let's close here.
