### ISSUE TITLE
Unicode in cache title is not handled properly [SU]

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7688]
**Describe the bug:**
All modern unicode symbols.have to be handled.properly (I.e. emojis)

**To Reproduce:**
1. Enable geocaching.su
2. Search for SU23215
3 Make sure question marks are in the title instead of "🐭🎶"

**Version of c:geo used:**
2019.06.19-NB-dcdb0bc

**Is the problem reproducible**
Yes

**Comment by moving-bits** [comment]
Wouldn't say so generally, see GC83CNF:

![image](https://user-images.githubusercontent.com/3754370/59826738-2a14c780-9337-11e9-9127-5ea959d66ac1.png)

Maybe Unicode chars get lost somewhere in the connector?

**Comment by okainov** [comment]
Could be, thanks for heads up. Then I rename it to su-specific and will check later

**Comment by Lineflyer** [comment]
I can confirm unicode is working with gc.com and oc. 
However for the mentioned cache I do neither see ?? nor emojis both not im cgeo and browser?!

**Comment by okainov** [comment]
False alarm, indeed problem was on our side (API was setting DB encoding to `utf8` instead of `utf8mb4`, just deployed a fix, should be good now.
