### ISSUE TITLE
Images are not stored/restored with backup

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7692]
**To Reproduce:**
1. Save some caches with images
2. Disconnect internet
3. Make a backup
4. Clear database/reinstall cgeo
5. Restore backup
6. Progress reported as succesfull, however no images restored.

Probably images are not backed up at all for some reason.

**Comment by Lineflyer** [comment]
The backup function only performs a backup of the sql databsse, but not of the additional cache data.
Additionally the geocache data dir will be removed by the system upon deinstall.

If you want to keep the additional data you have to manually save it somewhere before deinstall at the moment.

Its not part of the backup as it can be retrieved again by refreshing the caches after restore of the backup, and as it might be several GB depending on the amount of pictures/caches stored.

**Comment by okainov** [comment]
>and as it might be several GB depending on the amount of pictures/caches stored.

Yes, exactly, that's why I want it to be stored with backup :)

**Comment by SammysHP** [comment]
You can create a database backup as the database might not be easily accessible. But there shouldn't be a problem with additional data because it is stored in the same area as the database backup.

**Comment by Lineflyer** [comment]
Yes, AFAIR this was the reason we did it like that. 
For the additional data we are using the system default file directories now, which should even make it compatible for clever third party backup tools.

**Comment by okainov** [comment]
@SammysHP  @Lineflyer as a developer I fully understand you. However as a user I would expect backup to make a backup. Full stop. Either you implement two versions "light backup: text only" and "full backup: with images", or make one full - TBH it doesn't really matter. Saying "users can make backup by going to some filesystem folder and copying it manually" - you as developers should know it better than anyone else - not a single normal user ever would do this, it's too complicated workflow. You're not making app for developers but for usual people ;)

**Comment by Lineflyer** [comment]
I admit it would be convenient. What would you expect to be the result of such kind of backup. A zipped archive of the additional geocache data?

Some of my devices would not be able to handle this, as they do not have enough free disk to store such thing. That would then also require to add some other storing options for such backups IMHO.

**Comment by okainov** [comment]
>A zipped archive of the additional geocache data?

As a user I don't really care :) Yes, I would expect some blob-file like "cgeo_backup_20190101.tar.gz" or something like this. Maybe zip, maybe some binary format. Just one file.

> That would then also require to add some other storing options for such backups IMHO.

That's what I said - it could be just two versions "lite backup" (same as now) and "full backup" with some warning like "Full backup may take up to several GBs. Please make sure you have free space".

**Comment by SammysHP** [comment]
Let's just add a hint that this function creates only a backup of the database without additional data.

**Comment by moving-bits** [comment]
Just for completeness: above mentioned PR 7707 adds a hint regarding cache images not being backed up by the current backup routine, so if we are not going to implement a function for image backup, this issue can be closed when PR 7707 has been merged.

**Comment by geocachermgo** [comment]
> Additionally the geocache data dir will be removed by the system upon deinstall.

Sorry if this is a dumb question: where is this data dir?

> If you want to keep the additional data you have to manually save it somewhere before deinstall at the moment.

Is it possible to "reconnect" the pictures from the manual backup and after deinstall, install and database restore they are visible in the corresponing cache in cgeo?
