### ISSUE TITLE
Resort menu items after tts has been added

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7693]
Just a quick field note, will explain later in more detail:

TTS menu is insertes quite early in the menu. Now e.g. logging is one entry later than before.

That at least triggered me today several times to accidentally activate tts instead of start logging.

**Comment by moving-bits** [comment]
Hm, this depends on the screen space you have available. I'd inserted the "toggle tts" menu entry directly after the navigation options (as it's somehow related).
- In cache popup view you get the menu entries in the order of compass, navigate, toggle talking, log visit etc.
- In cache details view you get compass and navigate as buttons, so toggle talking becomes the first menu entry, just before logging.

I could place "tts toggle" directly after "log visit". Ok?

**Comment by Lineflyer** [comment]
> I could place "tts toggle" directly after "log visit". Ok?

Thats sounds like a better place, as afterwards there are only the items which are perhaps not so frequently used. So it will not "break the flow" for using quick navigation, navigation and logging.
