### ISSUE TITLE
Icon not updated on change of waypoint visited state

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7695]
- Open new mf map for a cache with waypoints
- Click on a waypoint
- Select Modify
- Set it to "Visited" (or vice versa)
- Return to the map

Result:
The waypoint icon is not updated (transparent background) but only after leaving reentering the map

Expected:
Icon should be instantly updated
Works on GoogleMaps

**Comment by moving-bits** [comment]
Reopening, as it is fixed only partially: It works the first time you are closing the waypoint editor, but not on subsequent calls.

**Comment by Lineflyer** [comment]
Was unable to reproduce this on 2021.03.01-NB1 with my worst case theme scenario, while it was easily reproducible before. I guess the dependency to ongoing background operation is still there but is now unlikely to occur. 
Lets therefore close until we might get new clues or other scenarios producing such problem.
