### ISSUE TITLE
Charter member unable to see PM-only caches on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7703]
**Describe the bug:**
On support mail a charter member contacted us, that he does not see any PM-only caches on the map.

**To Reproduce:**
I asked the user to provide more details (only map or also search affected)

**Actual behavior/state after performing these steps:**
No premium caches visible

**Expected behavior/state after performing these steps:**
Premium caches should be shown also to charter members

**Version of c:geo used:**
2019.06.06

**Is the problem reproducible:**
Cannot be tested

**System information:**
```
--- System information ---
Device: SM-N920P (nobleltespr, samsung)
Android version: 7.0
Android build: NRD90M.N920PVPS3DRH1
c:geo version: 2019.06.06
Google Play services: enabled - 17.4.55 (040400-248795830)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (8.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (8.3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (8.3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (392.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / CHARTER
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Additional context:**
@jonas-koeritz Can this be somehow related to the new live map implementation (either server side or client side)?

**Comment by jonas-koeritz** [comment]
What's the difference between a charter member and a premium member? This could definitely be related, I think there is a check that branches based on the account type.

**Comment by Lineflyer** [comment]
Charter member are basically premium member, which became and stayed premium since the first year of Groundspeaks premium option. The difference should only be the member type name on the website, but technically identical to premium members.

Therefore I more suspect, that the live map might do something wrong on server side, but I don't know if there might be anything in the detail of the parameters we send to request data from the map.

**Comment by jonas-koeritz** [comment]
Has any charter member tried to access the new map on the website?
Is a charter member marked as premium in c:geo?

**Comment by Lineflyer** [comment]
> Is a charter member marked as premium in c:geo?

According to the system information above we even recognize the status "CHARTER", but I don't know how we handle this member type throughout the app.
Theoretically we can just map it to "PREMIUM".

@jonas-koeritz 
Can you remind me of the correct URL of the new map, so I can ask this user to try it.

**Comment by jonas-koeritz** [comment]
It's the default map on the website already:
https://www.geocaching.com/play/map/

Lars <notifications@github.com> schrieb am Di., 16. Juli 2019, 23:50:

**Comment by Lineflyer** [comment]
I asked the user to check the website map.

**Comment by Lineflyer** [comment]
@jonas-koeritz In your new map API code is there any filtering or change in request to the server depending on the member type recognized by c:geo? In this case it might be, that you missed to handle charter as member type?

**Comment by jonas-koeritz** [comment]
The only change to the request is done when "hide caches owned/found" is
enabled and Settings reports the user is a premium member. The search query
will be sent with the filters already set (not filtered by c:geo after the
search):
https://github.com/cgeo/cgeo/blob/9134f4f64dd6acac054bb966ac4b0126dd954fe2/main/src/cgeo/geocaching/connector/gc/GCWebAPI.java#L391

Premium caches get sent to the store and cache with their "premium only"
flag set and the rest is handled by the map view.

Am Mi., 17. Juli 2019 um 22:48 Uhr schrieb Lars <notifications@github.com>:

**Comment by jonas-koeritz** [comment]
We need a charter member to have a look at the web version of the new map and report back if premium caches are visible.

**Comment by Lineflyer** [comment]
I do now have a charter member again on support with this problem.

@jonas-koeritz What data would be needed to debug this problem.

BTW:
His system info shows
Geocaching sites enabled:    geocaching.com: Logged in (Login OK) / CHARTER

**Comment by Lineflyer** [comment]
The user reported back, that the map is missing those caches also in some cases...after scrolling around, etc. So I assume a failure on gc.com for the time being. The user will file a bug towards Groundspeak.

**Comment by jonas-koeritz** [comment]
I would have asked that. If they're missing from the map on the page we can't do much about it.

**Comment by Lineflyer** [comment]
https://forums.geocaching.com/GC/index.php?/topic/354895-map-fails-to-display-premium-caches-for-charter-members/&tab=comments#comment-5813249
