### ISSUE TITLE
Support new GC cache types

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7704]
**from GC Blog**
For 2020, we’re bringing bring back two cache types that were previously available only in 2010. We feel it was a mistake to create cache types for one-time use only, so we’re excited to make these available again to the community and Geocaching HQ.

The Groundspeak Lost and Found Celebration is renamed the Geocaching HQ Celebration. This will be the cache type for the Geocaching 20th Anniversary Celebration in Seattle. We intend to host an event every 10 years with this icon.

Also, the Lost and Found Event Cache is now the Community Celebration Event, with a new look. This is the icon for events that enable cachers to commemorate the 20th anniversary around the world during 2020. We’ll share information about those events later this year.

**Describe the solution you'd like**
Support the new cache types

**Additional context**
see
https://www.geocaching.com/blog/2019/06/log-your-will-attend-for-the-geocaching-20th-anniversary-celebration/

**Comment by bekuno** [comment]
I can implement the code change in c:geo, but I'm no picture artist.
So we need 2 nice icons suitable to the current pictures.in c:geo.

**Comment by SammysHP** [comment]
Do we really need new icons or can we just map these rare cache types to existing ones like we did in the past?

**Comment by bekuno** [comment]
We can/should (eg. EVENT, HQ), when we have no fresh designed icons.

**Comment by Lineflyer** [comment]
Do we really need new types? I understood it in that way, that former types are just renamed and reused?!
If also archived caches of that type will get the renaming, then its quite clear, that we only need to change the name and thats it, or am I overlooking something?

**Comment by moving-bits** [comment]
We do have "Lost and found Event Cache" type, so let's see what happens when the first new cache with type "Community Celebration Event" appears.

The other type, "Groundspeak Lost and Found Celebration", has not been implemented in c:geo yet, so the above PR directly introduces the new "Geocaching HQ Celebration" type as successor.

**Comment by bekuno** [comment]
We have a "Community Celebration Event" - 
https://www.geocaching.com/geocache/GC25FHC
It is already renamed bei GCHQ. This maps to lostandfound.

Will change ma PR accordingly.

**Comment by Lineflyer** [comment]
> The other type, "Groundspeak Lost and Found Celebration", has not been implemented in c:geo yet, so the above PR directly introduces the new "Geocaching HQ Celebration" type as successor.

For my understanding:
How do you identify/parse the "Geocaching HQ Celebration" in this PR as we do not have any such event by now? Did you implement based on the old type renamed?

Is the corresponding PR already mergeable (beside missing icons) or shall we wait?

**Comment by bekuno** [comment]
The "Geocaching HQ Celebration" are renamed by GCHQ and now exists two such events:
https://www.geocaching.com/seek/nearest.aspx?tx=af820035-787a-47af-b52b-becc8b0c0c88&u=Geocaching%20HQ

The PR is mergable from my side.
The icons are mapped to the default event icon.

**Comment by Lineflyer** [comment]
I merged and tested the PR. Looks good to me.
For the missing icons I don't think we should take this effort to implement them.
The reused icons for Event (Community Celebration) and HQ (HQ Celebration) are perfectly fine.

@bekuno 
Thanks for your contribution!
