### ISSUE TITLE
Implement new OC attributes

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7705]
This is a follow up to #7671 
There we had some OC attributes not mapped to GC attributes.

Furthermore, some OC attribute definitions of 
https://wiki.opencaching.eu/index.php?title=Cache_attributes
are not implemented in c:geo.
At the moment these are the following OCPL only attributes:

ID | text_short | text_long | id | gc_id | icon | name | gc_inc | ACODE | OCGS
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
214 | Handicaching | Rated on Handicaching.com |   |   |   |   |   | A76 | 214
215 | Munzee | Contains a Munzee |   |   |   |   |   | A77 | 215
216 | Ads | Contains advertising |   |   |   |   |   | A78 | 216
217 | Military training area | Military training area, some access restrictions - check before visit |   |   |   |   |   | A79 | 217
218 | Video surveillance | Caution, area under video surveillance |   |   |   |   |   | A80 | 218
219 | Trackables | Suitable to hold trackables |   |   |   |   |   | A81 | 219
54 | Ruin | Abandoned structure / ruin |   |   |   |   |   | A82 |
48 | UV light | UV light required |   |   |   |   |   | A83 |
9015 | NOT in winter | NOT available during winter |   |   |   |   |   | A84 |  
9001 | No dogs | Dogs not allowed |   |   |   |   |   | A85 |  
46 | Truck / RV | Truck / RV allowed |   |   |   |   |   | A86 |
220 | Historic | Officially designated historical monument |   |   |   |   |   | A87 | 220

**Comment by andrixnet** [comment]
Please take another look at https://wiki.opencaching.eu/index.php?title=Cache_attributes
OCDE attribute wwwlink (id 107, acode A82) has been completely removed. OCDE has eliminated this attribute because of incompatibility with their ToS. 

All new acodes >82 have been renumbered accordingly.

**Comment by bekuno** [comment]
> All new acodes >82 have been renumbered accordingly.

done in list above

**Comment by andrixnet** [comment]
Attributes deployed tonight at OKAPI master and OPENCACHING-PL based sites.
OCPL, OCNL, OCUK, OCRO, OCUS.

All according to documentation here: https://wiki.opencaching.eu/index.php?title=Cache_attributes which as of now is current.

**Comment by bekuno** [comment]
In the meantime some changes were integrated, and now this is active on all OC instances.

These are the new icon-IDs (acode) whithout correspondending GC-ID and their OC instance where it is used:

name | acode  | de | ro | uk | us 
  -|-|-|-|-|-
 Rated on Handicaching.com | 76  |     |      |  214 |     
 Contains a Munzee | 77  |     |      |  215 |     
 Contains advertising | 78  |     |      |      |  216 
 Military training area | 79  |     |      |  217 |      
 Video surveillance | 80  |     |  218 |      |      
 Trackables | 81  |     |  219 |      |      
 Historic | 87  |     |  220 |      |      
 Handicap: Blind | 89  |  62 |      |      |    

The other new attributes are mapped to GC attributes:

 name | gc id | acode | nl | ro | uk | us 
 -|-|-|-|-|-|-
 Ruin |  54 | 82 |      | 54 |    |       
 UV Light Required |  48 | 83 |      | 48 |    |       
 NOT available during winter |  15 | 84 |      |    |    | 9015  
 No dogs |  1 | 85 | 9001 |    |    |       
 Truck / RV |  46 | 86 |      |    |    |   46  
 Treeclimbing |  64 | 88 |      | 64 | 64 |      				  

And these are the proposed icons:
![grafik](https://user-images.githubusercontent.com/32555742/95037798-79b60880-06cc-11eb-9ef3-d17877844725.png)

**Comment by bekuno** [comment]
@andrixnet Did I missed something or is this ok?

**Comment by bekuno** [comment]
@andrixnet Can you provide some caches with such a new attribute? (At least for opencaching.ro)
