### ISSUE TITLE
"Import Pocket Query" disabled for premium user

### ISSUE THREAD

**Issue by hakan42** [cgeo/cgeo#7706]
**Describe the bug:**
I have reinstalled c:geo (version 2019.06.06) on a new mobile and authorized with geocaching.com. Even though I am a premium user (my membership is due to be renewed on 2.5.2020), the "Import Pocket Query" option is greyed out

**Actual behavior/state after performing these steps:**
"Import Pocket Query" is not possible

**Expected behavior/state after performing these steps:**
I want to be able to import pocket queries again :)

**Version of c:geo used:**
2019.06.06

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: SM-G973F (beyond1lteeea, samsung)
Android version: 9
Android build: PPR1.180610.011.G973FXXU2ASF3
c:geo version: 2019.06.06
Google Play services: enabled - 17.7.85 (100400-253824076)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (85.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (85.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (85.4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (152.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   extremcaching.com: Logged in (Login OK)
   opencaching.de: Logged in (Login OK)
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: contacts
--- End of system information ---
```

**Comment by Lineflyer** [comment]
According to your system information c:geo does not recognize you as premium but as basic member.
In case your membership status only changed recently, please reboot your device and start c:geo again (to enforce a new login). Afterwards c:geo should again recognize your PM status.

**Comment by hakan42** [comment]
Thank you for the hint with "Restarting". After rebooting the mobile, suddenly I was recognized as PREMIUM and all the menu items for the pocket queries. were enabled.

And about the "recently"... I am near constantly a premium member since 2005 and the latest renewal was (according the geocaching.com membership details page) on 02.05.2019. So, there might be something interesting going on with freshly installed applications.

Maybe that could be added to the documentation. Should I create a pull request against _data/faq.yml on the cgeo.github.io repository?

**Comment by Lineflyer** [comment]
I think the help is already listed here:
https://www.cgeo.org/faq#no-premium

On fresh installs it might be, that its only recognized on the second login. AFAIR there is a bug listed somewherw here.
However I do lot of fresh installations  while testing and never run into this problem.

**Comment by hakan42** [comment]
o.k., thanks.
