### ISSUE TITLE
Opencaching.us authorization not starting

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7709]
**Describe the bug:**
It is currently not possible to start the oauth process to login to oc.us with c:geo

**To Reproduce:**
1. Go to Settings - Services - opencaching.us
2. Click on Authorize

**Actual behavior/state after performing these steps:**
Error toast, that c:geo could not start the process

**Expected behavior/state after performing these steps:**
opencaching.us authorization page being shown

**Version of c:geo used:**
2019.06.06

**Is the problem reproducible:**
Yes

**Additional context:**
The opencaching.us site was down for maintenance for several weeks as they upgraded their site. According to a recent facbook posting they are back online meanwhile (and I checked, that I can login and use the website normally), however I suspect something in the OKAPI is still broken.

Does anyone have a contact to oc.us to clarify this problem?

**Comment by bekuno** [comment]
The migration of OCNA is tracked in https://github.com/opencaching/opencaching-pl/issues/2013

@harrieklomp @kojoty @andrixnet Please have a look at this problem.

**Comment by harrieklomp** [comment]
I think the problem is that cgeo use httpS in their links. For this moment OCUS uses http.
@Andrixnet is planning to add the S to http as soon as possible.

**Comment by Lineflyer** [comment]
Really?
It not really meaningful to perform oauth without transport encryption.

**Comment by bekuno** [comment]
@Lineflyer The migration to the new site was not planned in this way, see
https://github.com/opencaching/opencaching-pl/issues/1973#issuecomment-503262477

We should give them some time to really migrate and consolidate the installation.

**Comment by Lineflyer** [comment]
Thanks for the info.
I have just read the Facebook posting where it was said, that they are back online and only having some remaining issues.

I did not expect completely missing OKAPI function was part of these issues.

**Comment by andrixnet** [comment]
During database migration OKAPI database version (as imported) was very old and OKAPI code did not automatically update it. OKAPI database updated manually since then and OKAPI should be working.
See https://github.com/opencaching/opencaching-pl/issues/2023

OCNA site is not up and running on current opencaching-pl codebase and with automatic updates on.

**Comment by harrieklomp** [comment]
Now it is possible again to start the oauth process for OCNA.

**Comment by Lineflyer** [comment]
Thanks @andrixnet  Tested and working for me.
