### ISSUE TITLE
Personal note in calculator does not support new line

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7710]
**Describe the bug:**
When entering notes into the waypoint calculator its not possible to add a new line / line break.
This draws this rather large text field almost unusable.
Not sure whether this is a regression from a recent change, but I only just now noticed and I would have noticed earlier if this problem was there from start of that feature.

**To Reproduce:**
1. Open a cache
2. open waypoint tab
3. Create new waypoint
4. Click on coordinates
5. Select "calculate coordinates"
6. Go into the note text field

**Actual behavior/state after performing these steps:**
You can enter text but no line feed
If you copy several lines of text into that field, the line feeds are removed and all text appears in one line

**Expected behavior/state after performing these steps:**
Text field should support line feed and also show copied multi line text in the original formatting

**Version of c:geo used:**
2019.07.02-NB

**Is the problem reproducible:**
Yes, since some weeks

**Comment by Lineflyer** [comment]
This seems to be the culprit: 
6516610f5e09178e50096902a203e3bf23bade70

@Bananeweizen

**Comment by bekuno** [comment]
By the way, this effect is not with version 2019.06.06 on a Android 9 device.
I could reproduce it with a Android 7 device.

**Comment by Lineflyer** [comment]
2019.06.06 should not have the problem at all, as the relevant change is only on master. Maybe your Android 7 device was on a newer version? Else there seems to be a different handling of the text field as long as no input type is given.

**Comment by bekuno** [comment]
You are right, the Android 7 device runs with a dev installation.
I forgot that the PR was not in the market version.

**Comment by Lineflyer** [comment]
Reopen due to remaining issue of related PR.
