### ISSUE TITLE
Login fails through orbot

### ISSUE THREAD

**Issue by ithink314** [cgeo/cgeo#7713]
**Describe the bug:**
From 30+ days ago, until a few days ago, logins to GC with cgeo using orbot VPN worked OK.
Now logins fail.
Previous note:
https://github.com/cgeo/cgeo-fdroid/issues/8#issuecomment-496773703

**To Reproduce:**
1. Install and setup cgeo with GC account
2. Install and setup orbot VPN and select cgeo in vpn settings, start circuit
3. Start cgeo (login fail)
4. Change orbot setting to unselected cgeo in VPN
5. Start cgeo (login OK)

**Actual behavior/state after performing these steps:**
Login to GC fails with orbot vpn

**Expected behavior/state after performing these steps:**
Login OK

**Version of c:geo used:**
2019.07.04-NB-310e73c

**Is the problem reproducible:**
Yes 

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 9
Android build: lineage_shamu-userdebug 9 PQ3A.190605.003 c4e7170834
c:geo version: 2019.07.04-NB-310e73c
Google Play services: unavailable
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (9.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (9.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (9.4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (559.0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   opencaching.us: Not logged in (Login failed)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---


```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

https://github.com/cgeo/cgeo-fdroid/issues/8#issuecomment-496773703

**Comment by SammysHP** [comment]
This is because geocaching.com detects Tor connections / requests from Tor exit nodes and requires the confirmation of a captcha. Nothing we can change.

**Comment by ithink314** [comment]
@SammysHP Btw. your system information says that you are logged in successfully with your geocaching.com account, but the OCUS login failed

Yes, login to GC works when not through orbot. Actually today they are again working with orbot. :)

And, I know cgeo support knows OCUS is fubar now. :(

**Comment by SammysHP** [comment]
Depends on the exit node. Not all exit nodes are known to the usual blocklists so sometimes you have luck and it is not recognized as Tor. If you have problems, you can try to use another Tor route, but it might require several attempts and is not the best way to use Tor.

---

Btw. this might also explain some other login issues (@Lineflyer). If Groundspeak detects many requests from the same IP (either because of several users at the same WLAN hotspot or shared IP as it is common in some (most?) mobile networks) they might show a captcha for these users.

**Comment by ithink314** [comment]
@Lineflyer , As of about Dec.1, GC logins are failing again for me. I understand there was a captcha option somewhere in cgeo previously, but I cannot find it in latest daily version. Would it be feasible to have login captcha display/handling (or could you tell me where to find the setting)?

**Comment by Lineflyer** [comment]
The login captcha was used in another context in the past and has been removed quite some years ago.

For login we did never use it and I doubt that we can implement this easily. Furthermore this only affects users with some IP-ranges which are blacklisted for whatever reason.
At the moment we identified TOR endpoints as well as a single provider in New Zealand.
