### ISSUE TITLE
Temporary disable proximity tone or make it follow device settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7724]
Currently the proximity notification is always enabled, once its enabled in the settings.
In some situations users might want to temporary disable the notification (e.g. in situation where silence is required). 

This could either be done by some kind of silence toggle or (maybe preferably) by letting is follow some device global setting (like ringtone off or "do not disturb" modes).

I have no idea whether this is feasible, and it for sure not an urgent feature/improvement request, but maybe more a base for further discussion if such function is desirable at all.

**Comment by moving-bits** [comment]
PR 7731 suppresses proximity notification if device's silent mode is set to quiet.

If silent mode is set to vibration (device dependent) it tries to vibrate. (Could not test this part, as I currently don't have a physical test device available.)

**Comment by moving-bits** [comment]
I rate the described scenario higher, setting prio to medium therefore.
IMHO the PR #7731 for this should be included in the next feature release, see #7665.
