### ISSUE TITLE
Should favorite point display use "x" or not

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7727]
I remember there was a discussion within an issue or PR for the favorite percentage feature (which has been merged meanwhile) regarding whether there should be an "x" used behind the amount of favorite points or not.

After having used current `master` for several days I always recognized this now missing "x".
The reason is quite simple. The corresponding line is titled "Favorite" not "Favorite points" or "Amount of favorite points".
As it now also shows the percentage in the same line, the title "Favorite" is more correct than "Favorite points" anyway, but somehow I would expect the "x" to be used to clearly indicate the absolute amount from the new relative amount.

So, what do you think which format is "better":

- Favorite     94 (24%)
- Favorite     94x (24%)

Not a big issue, just want to get feedback.

**Comment by bekuno** [comment]
I do not really prever one of them.
55:45 for the second form

**Comment by moving-bits** [comment]
Me neither. But maybe the first form to save some space.

**Comment by Lineflyer** [comment]
OK, lets drop this topic :)
