### ISSUE TITLE
API to extremcaching.com not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7732]
Reason is, that their website SSL certificate has expired (once again).

I disabled the corresponding watchdos tests already in 9d36811a57d525909624312922fa0dd94c796108 as I expect at least some days (given to the experience of last time this happend) to install a new certificate.

This issue is just to inform and as a reminder to enable those tests again if the API is functional again.

**Comment by okainov** [comment]
Seems certificate is valid now, probably should be re-enabled and closed :)

**Comment by Lineflyer** [comment]
Funny side note, the website is offline, the API works and delivers data.

**Comment by moving-bits** [comment]
I have a PR ready for reactivating, but we should not merge it for now:

Reactivating the tests still break for EC, as their site currently returns a HTTP 503 error - "service temporarily unavailable".

If someone can give me a valid EC cache URL I can adapt the test to use this instead of their homepage.

**Comment by bekuno** [comment]
Currently no login, only this text:
![grafik](https://user-images.githubusercontent.com/32555742/82705695-70c21e80-9c78-11ea-9570-e0ef3444f719.png)
(https://extremcaching.com/index.php)

**Comment by Lineflyer** [comment]
The API was functional although the website landing page was blocked.
But now qdditionally their SSL certificate again expired.

**Comment by bekuno** [comment]
@moving-bits 
Here are some cache URL:
http://extremcaching.com/output-2/1226-t5-baumcache-nr-172
http://extremcaching.com/output-2/1218-01-brenz-14
http://extremcaching.com/output-2/1107-the-yellow-roppe

**Comment by bekuno** [comment]
> But now qdditionally their SSL certificate again expired.

It's now sign by Let's Encrypt. The certificate is valid until "24.9.2020, 19:28:26 (Mitteleuropäische Sommerzeit)"

**Comment by moving-bits** [comment]
@bekuno 
Thanks for the links. The last one is accessible without login, so I chose that one as new test URL for ec adapter, see updated #8365.

**Comment by moving-bits** [comment]
Site is back running. Can we close this issue?

**Comment by Lineflyer** [comment]
I think so.
