### ISSUE TITLE
Can't log in to geocaching.com when using VPN

### ISSUE THREAD

**Issue by Adakar** [cgeo/cgeo#7734]
**Describe the bug:**
Can't authorize connection to geocaching.com when VPN connection(NordVPN) is used.

**To Reproduce:**
1. Connecto to VPN
2. open c:geo
3. Open Settings -> Services -> Geocaching.com
4. Authorize with proper credentials

**Actual behavior/state after performing these steps:**
"Login failed because of Unknown error" pops up

**Expected behavior/state after performing these steps:**
Authentication performed successfully

**Version of c:geo used:**
2019.06.06

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: FRD-L09 (FRD-L09, HONOR)
Android version: 7.0
Android build: FRD-L09C432B416
c:geo version: 2019.06.06
Google Play services: enabled - 17.7.85 (040408-253824076)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: pl_PL
System date format: dd.MM.y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (3,3 GB free) internal
User storage c:geo dir: /data/user/0/cgeo.geocaching (3,3 GB free) internal
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (3,3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (156,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: DENIED
Geocaching sites enabled:
   geocaching.com: Not logged in (Logowanie nie powiodło się)
   Geocaching.com date format: MM/dd/yyyy
   Installed c:geo plugins:  none
   --- End of system information ---
```

**Additional context:**
After turning the the VPN connection off I was able to log in.

**Comment by Lineflyer** [comment]
Depending on the target network of your VPN it could be, that geocaching.com considers it suspicious and requires a manual recaptcha to login in which case cgeo fails to login.
This happens e.g. in some cases of TOR network endpoints.

Can you try with your normal browser on phone and check whether the website requires a recaptcha to login to geocaching.com?

**Comment by Adakar** [comment]
Thanks for your response. 
Yes, it requires. Is there any workaround for that? I tried different VPN servers in different locations, including the country I'm currently in.

**Comment by Lineflyer** [comment]
No, sorry. Not at this moment.
