### ISSUE TITLE
Setting backup location not shown and not findable

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7736]
**To Reproduce:**
1. Go to Menu - Settings - Backup / Restore
2. Click on "Backup settings"

**Actual behavior/state after performing these steps:**
Backup is performed but only a small toast "Settings saved" is shown. There is however no corresponding file in `/cgeo/backup/` where I would have expected it.

**Expected behavior/state after performing these steps:**
We should inform the user about the location of the backup file to give him a chance to manually backup this file. Ideally we should use the same dialog which is used for the (old) backup of the cache database.
We should store the file in `/cgeo/backup/` where also the sqlite backup file is located.

**Is the problem reproducible:**
Yes

**Comment by moving-bits** [comment]
Currently the file is written to `/Downloads/cgeo-settings.xml`.

I will look into the mechanism used for the caches database (didn't even know that dir `/cgeo/backup` exists...).

**Comment by Lineflyer** [comment]
@pstorch might be able to give you a hint regarding the dir structure and how it is used in the code.
There should be also some documentation in our Wiki.

**Comment by pstorch** [comment]
The different Directories are accessible via `main/src/cgeo/geocaching/storage/LocalStorage.java`.

The wiki document about the directories is this one: https://github.com/cgeo/cgeo/wiki/Disk-usage-structure

Hope it helps.

**Comment by MagpieFourtyTwo** [comment]
I know, it's off topic, of course, but it *must* be said: Great work, guys, your commitment is a real bummer! Stumbled over the problems described in issues #7736 and #7735 yesterday night, but did not even find time to open a case - and today there is already a fix in progress. Thanks a lot! :)

**Comment by moving-bits** [comment]
@pstorch  Thanks for the pointer, rebased settings backup creation on cgeo's backup dir

**Comment by Lineflyer** [comment]
@moving-bits This is solved, isn't it?

**Comment by moving-bits** [comment]
> @moving-bits This is solved, isn't it?

@Lineflyer: Yes, should be closed with PR 7743. Don't know why I didn't get closed automatically.
