### ISSUE TITLE
Show a information toast/snackbar if live map is disabled

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7741]
We still have a significant amount of users contacting our support who have the problem, that for them the live map is "not working".
After some conversation it turns out they accidentally disabled the live mode and due to unawareness thought the map stopped working as this disabled status is kept even after app restart.

AFAIR we discussed this somewhere here, but I cannot find it.

I suggest to make this setting transient, i.e. after restart of the app it should always be in live mode.
As we call the function "live map" on the mainscreen this is, what the users expect.

**Comment by Lineflyer** [comment]
If someone wants to approach this issue, it could be based on release branch to have it out soon.

**Comment by rsudev** [comment]
I'll try to give it a shot tomorrow (I actually like it the way it is, but accept the reason for the change).
But you should actually be aware, that 'restart of the app' is much less clearly defined in terms of user perception than you would expect.

**Comment by Lineflyer** [comment]
> But you should actually be aware, that 'restart of the app' is much less clearly defined in terms of user perception than you would expect.

I am aware of that. But at least this problem will then somewhen resolve itself. And for support mails I can just ask "Did you try turning it on and off again?" ;))

**Comment by alan666notb** [comment]
Careful here - my normal method of caching is with offline caches loaded from GSAK and live maps disabled.
In fact, I very rarely enable it.
I don't want the live map option keep getting switched on.

**Comment by Lineflyer** [comment]
Mmh...that could be the point we discussed in the past already (see my comment above).
Thats a valid usecase and might indeed by important in case you want to save data transfer, etc.

How about an information dialog informing, that live mode is disabled (with options to leave it or enable it) once per session when opening the live map from main menu?

**Comment by moving-bits** [comment]
> How about an information dialog informing, that live mode is disabled (with options to leave it or enable it) once per session when opening the live map from main menu?

That looks to me like a reasonable way to go.

I've a similar usecase as alan666notb: preload caches and maps using pq etc., "live mode" disabled (and only enabled shortly on demand, since it has unwanted side effects).

**Comment by alan666notb** [comment]
How does "once per session" work?

E.g. I don't use cgeo's compass for navigation, I have it configured to open the GPS Status 'Radar' screen.
I don't want a warning popping-up every time I go back to the map.

**Comment by moving-bits** [comment]
It's probably hard to match the technical view and user expectation due to Android memory management.

A simple solution could be to present this info once per day max (and only when opening live map), and to store the last viewing date in our settings.

**Comment by jonas-koeritz** [comment]
How about shortly showing a snackbar everytime the user enters the live map
without live mode enabled, with the option to turn it on directly attached.
Making the snackbar optional (toggle in settings to disable it) should make
everybody happy.

moving-bits <notifications@github.com> schrieb am Fr., 26. Juli 2019, 13:52:

**Comment by Lineflyer** [comment]
Snackbar is a nice unintrusive idea if it is shown for some seconds.
IMHO it would ot be worth an option to disable it....our setting menus are crowded enough already ;)

**Comment by alan666notb** [comment]
I'd like the option to disable the warning

**Comment by moving-bits** [comment]
Just stumbled upon this accidentally: As we do have the nice `OneTimeDialog` now, this could be an easy solution for this.
