### ISSUE TITLE
`isEqualTo()` gives false negatives

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#7742]
https://github.com/cgeo/cgeo/blob/cc7473347850b435c4824e7f231a3dd141daff6e/main/src/cgeo/geocaching/models/Geocache.java#L417-L418 compares attributes and waypoints using `==`. While debugging I noticed that two empty lists of attributes or waypoints would make this return `false`. This will return false negatives, ending in unneccessary roundtrips, for example in DataStore.

**Comment by jonas-koeritz** [comment]
The `LazyInitializedList` can't be compared that way, using `ObjectUtils.equals()` seems to be giving correct results.

**Comment by Lineflyer** [comment]
What consequence (from users perspective) would this problem have? Maybe it maps to some known issue.

**Comment by jonas-koeritz** [comment]
This might be related to some race conditions regarding logging and similar
"cache modifying" actions. Caches get overwritten more often than they
should.

Lars <notifications@github.com> schrieb am Do., 25. Juli 2019, 23:41:

**Comment by bekuno** [comment]
@jonas-koeritz You are right. 
LazyInitializedList is based on AbstractList.
We should use its equals method (or overide it).

**Comment by jonas-koeritz** [comment]
Would be interesting to see what else is affected by this.
