### ISSUE TITLE
Slightly "dancing" GPS location triggers syncLayers

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#7745]
When the devices GPS location is hovering around due to inaccuracy and the map viewport is tied to the user location `overlay.updateTitle()` is triggered very often (leading to a `syncLayers()` call), wasting performance and energy.

https://github.com/cgeo/cgeo/blob/28b96982271221688548014fbbb628ec3ca6b50d/main/src/cgeo/geocaching/maps/mapsforge/v6/caches/LiveCachesOverlay.java#L81 checks if the viewport is the same, further above `mapMoved` is used to check if the map moved. `mapMoved()` accounts for slight inaccuracies, `equals()` does not. Can someone clarify why these two variants have been made independant?

Top reproduce: Visit the Live Map, stand still and let GPS drift, watch the Logcat output showing that the layers get synced over and over again.

**Comment by jonas-koeritz** [comment]
I can also trigger continious `syncLayers()` calls when not following GPS position just by scrolling around the map sometimes. The coordinates look like they're ever so slightly misaligned between layers.
Looking at the commit that created this code (https://github.com/cgeo/cgeo/commit/f3f1e86dfb85ddb6989646e4529f5354987c334d) this might have been an oversight.

**Comment by Lineflyer** [comment]
@rsudev Your commit f3f1e86

**Comment by rsudev** [comment]
The line mentioned above serves to prevent the scenario you claim is happening - discriminate between a real 'move' that warrants a load and sync and small movements, which should just update the title (caches move in and out of visibilty) and handle waypoint display on/off.
From code inspection and testing I could not see that ```overlay.updateTitle()``` is triggering ```AbstractCacheOverlay.syncLayers()```.
Could you elaborate, what you were doing/seeing, so I can reproduce?

**Comment by jonas-koeritz** [comment]
`updateTitle()` calls `handleWaypoints()` https://github.com/cgeo/cgeo/blob/28b96982271221688548014fbbb628ec3ca6b50d/main/src/cgeo/geocaching/maps/mapsforge/v6/caches/AbstractCachesOverlay.java#L221, which will eventually call `showWaypoints()` that triggers `syncLayers()`.

**Comment by rsudev** [comment]
Correct. But this should be an extreme edge case (the 'dancing' flips the visible caches between below and above the show-waypoints limit), nothing I would worry about.

**Comment by jonas-koeritz** [comment]
The triggering of `syncLayers()` happens even when there is not a single
visible cache on the map. I might have to investigate further but maybe
there is an oversight in any of the `if` statements.

rsudev <notifications@github.com> schrieb am So., 28. Juli 2019, 14:49:

**Comment by rsudev** [comment]
Thanks for insisting. Now I see the problem. Fix on release or only master? Try on master first?

**Comment by jonas-koeritz** [comment]
Let's try on Master first. Shouldn't be that much of a problem to push so
fast towards release.

rsudev <notifications@github.com> schrieb am So., 28. Juli 2019, 17:13:
