### ISSUE TITLE
Move to AndroidX

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#7748]
I think c:geo should move from the Android Support libraries to AndroidX as soon as possible, maybe we should even create a GitHub project for that.
The Support Libs won't be there forever and AndroidX offers cleaner interfaces for development.

Switching to AndroidX is also a required prerequesite for using the Room persistence library, which would be a good fit for a complete rewrite of the DataStore backend which, according to checkstyle, currently contains some of the most complicated and error prone code in c:geo.

**Comment by bekuno** [comment]
from https://developer.android.com/jetpack/androidx :
If you want to use AndroidX in a new project, you need to set the compile SDK to Android 9.0 (API level 28) or higher and set both of the following Android Gradle plugin flags to true in your gradle.properties file.

Because we use Google Maps v1 the maximal compileSdkVersion is
    compileSdkVersion "Google Inc.:Google APIs:24"
(not: 24 !)
So we can use the Branch "GoogleMapsV2" also to implement AndroidX.

**Comment by jonas-koeritz** [comment]
That's exactly what I've done. I started with the MapsV2 branch and worked
my way to AndroidX from there. This issue should be approached when we
already have a stable GoogleMapsV2 release.

Bernd <notifications@github.com> schrieb am So., 28. Juli 2019, 23:03:

**Comment by andrixnet** [comment]
What minimum version of OS would then be required for the  user to have on their device to use c:geo?

**Comment by Lineflyer** [comment]
No change planned for the minimum supported version up to now.

**Comment by moving-bits** [comment]
> I think c:geo should move from the Android Support libraries to AndroidX as soon as possible, maybe we should even create a GitHub project for that.
> The Support Libs won't be there forever and AndroidX offers cleaner interfaces for development.

From https://developer.android.com/topic/libraries/support-library/revisions:
> Revision 28.0.0 Production (September 21, 2018)
> This is the stable release of Support Library 28.0.0 and is suitable for use in production. This will be the **last feature release** under the android.support packaging, and developers are encouraged to migrate to AndroidX.

So with our recent move towards SDK28 we're getting close to being able to move to AndroidX and should start this step as soon as we've merged #7653, IMHO.

**Comment by jonas-koeritz** [comment]
Development has been quite fast paced towards getting c:geo up to current standards. I'm looking forward to working with AndroidX inside c:geo. LiveData, Room etc. could potentially bring nice improvements to the app.

**Comment by bekuno** [comment]
Other infos.:
https://developer.android.com/jetpack/androidx/migrate
https://developers.google.com/android/guides/releases#june_17_2019

**Comment by bekuno** [comment]
@jonas-koeritz Have fun with AndroidX now :-)
