### ISSUE TITLE
Crash on Theme options change

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#7752]
I didn't investigate much of it yet but I noticed that changing anything in "Theme-Options" leads to a crash with my current debug build (Mapsforge 0.11). I will have a closer look and see what's the cause. Just wanted to document my finding.

**Comment by Lineflyer** [comment]
Cannot reproduce with 2019.07.28-NB.
Do you have a theme in use?

I use openandromaps files with elevate4 theme. No error here so far.

**Comment by jonas-koeritz** [comment]
Cannot replicate reliably anymore.
