### ISSUE TITLE
Logs not loading for basic members

### ISSUE THREAD

**Issue by McKirni** [cgeo/cgeo#7758]
**Describe the bug:**
As a basic member, when loading a new cache or refreshing a saved cache, no logs are loading.
Only the log-counters are updated.
As a premium-member, everything is working fine.

**Version of c:geo used:**
2019.06.06

**Is the problem reproducible:**
Yes

**System information:**
Android 4.4.4
Cyrus CS30

**Comment by Lineflyer** [comment]
Confirmed!

**Comment by jonas-koeritz** [comment]
The current build running on my phone doesn't have any problem at all. I'm a basic member too.

**Comment by Lineflyer** [comment]
I could instantly reproduce with logging in as basic member and loading a not saved caches from nearby search result.

Will test a bit more.

**Comment by Lineflyer** [comment]
For me reproducible for all caches, which have not be stored/opened with c:geo.
It looks like existing logbooks are kept on refresh but (perhaps) only not updated, but for new loaded caches the logbook is empty only showing the statistics.

**Comment by jonas-koeritz** [comment]
What build are you running? I just moved totally away from my Homezone,
tapped a random cache and its loading flawlessly.

Lars <notifications@github.com> schrieb am Mi., 31. Juli 2019, 14:27:

**Comment by Lineflyer** [comment]
I am running 2019.07.28-NB-df849dd

**Comment by McKirni** [comment]
Same bug with 2019.04.10-NB.f8f1886
Samsung SM-A520F
Android 8.0.0

**Comment by jonas-koeritz** [comment]
Still can't reproduce, can somebody else confirm this too? There shouldn't be any code changes that have anything to do with that between versions 2019.04.10 and my dev branch from yesterday (master based).

**Comment by Lineflyer** [comment]
History showed, that sometimes site changes only appear for a percentage of users at a time, maybe because they try ot out on a part of their load shared servers or something like that.

Normally the problem either disappears or gets static after some hours / a day.
So maybe @jonas-koeritz is not (yet) affected.

**Comment by jonas-koeritz** [comment]
That's a good possible explanation. Can you save a cache details page as
HTML and attach it for comparison?

Lars <notifications@github.com> schrieb am Mi., 31. Juli 2019, 16:11:

**Comment by Lineflyer** [comment]
[GC2BJ6M.zip](https://github.com/cgeo/cgeo/files/3452438/GC2BJ6M.zip)

**Comment by jonas-koeritz** [comment]
Must be related to the server yo're connecting to, and your browser doesn't get the same one. Structure looks identical to me, so it's not user based.

**Comment by Lineflyer** [comment]
Will try to take a look at the cgeo debug log tonight.

**Comment by Lineflyer** [comment]
Well arrived at home I cannot reproduce this on any of my devices which I am able to connect to ADB.
Only my Galaxy S10 (Android 9) is still showing the issue also from my home network. But on this one I failed to connect to adb due to some driver issue. :(

**Comment by jonas-koeritz** [comment]
Did you switch to MTP or PTP mode? My Pixel won't connect to ADB when not
in any USB "Data Mode".

Lars <notifications@github.com> schrieb am Mi., 31. Juli 2019, 21:10:

**Comment by McKirni** [comment]
> History showed, that sometimes site changes only appear for a percentage of users at a time, maybe because they try ot out on a part of their load shared servers or something like that.
> 
> Normally the problem either disappears or gets static after some hours / a day.
> So maybe @jonas-koeritz is not (yet) affected.

Problem disappeared ...

**Comment by Lineflyer** [comment]
Yes, also on the device where I could reproduce the problem it disappeared.
Lets close until it might reappear.

Thanks @McKirni for your feedback.
