### ISSUE TITLE
support tags for caches

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7761]
Currently the main feature to organize caches is lists. This is working pretty well, but it is one-dimensional. I'm looking for an additional / orthogonal way for organizing caches, which can be combined with lists. Therefore I suggest to add a tagging feature to c:geo.

Tagging would work similar to managing lists:
- tags itself are a flat list of user defined names, no hierarchy
- tags and caches are n:m-related
- unlimited number of tags
- each cache can have an unlimited number of tags, tags can have an unlimited number of caches

The following things would have to be added:
- Cache list
  - [x] Filter cache list by a specific tag - _(done with PR #7764)_
  - [x] Show comma separated list of tags assigned to a cache - _(done with PR #7769)_
- Cache popup and cache detail view
  - [x] Manage assigned tags - _(included with lists management)_
  - [x] Show comma separated list of tags assigned to a cache - _(included with lists management)_
- Tag management (from cache list view)
  - [x] Add tag - _(included with lists management)_
  - [x] Rename tag - _(included with lists management)_
  - [x] Delete tag - _(included with lists management)_

(and maybe more)

Example use case:
- Being on vacation I've put all the caches I would like to do in a separate list.
- As there is currently a promo running for which you need to collect certain clues first, then specific jewels etc., I would like to be able to assign this information to the specific caches (eg: "which cache has which type of jewel") and filter accordingly.

(Today I'm helping myself by saving this information by using a couple of extra lists and additionally storing infos in my personal notes, but handling this is clumsy and personal notes get convoluted.)

(A follow-up feature could be to assign specific symbols to a tag and show this symbol in map view, but that's something for a separate issue - let's do the basic things first.) - _(done with PR #7775)_

**Comment by rsudev** [comment]
Not sure why you want an additional categorisation category. The only thing missing to do what you describe is a filter for list membership.

**Comment by Lineflyer** [comment]
See also #5540

**Comment by moving-bits** [comment]
Thanks for your links. Hm, you are right - lists and tags basically would be the same, just independant from each other. So let's start with a list membership filter and try out how far I'll come with that.

**Comment by moving-bits** [comment]
After the switch to use lists as tags, I created the above listed three PR to implement the different aspects. With those you can:

- create lists to tag caches according to your choice, maybe for "T5 only caches", "must do today" etc.,
- see those "tags" in your cache list
- filter your cache lists by any "tag"
- assign a visual marker to your "tag"
- and display this marker on your map

Using tags and tag marker icons is a generalized approach for the many requests for very specific filtering and visualization in the maps. Vizualization is non obstrusive, the concept of tags / lists easy to understand and easy to adapt for the individual needs.

**Comment by Lineflyer** [comment]
I know we discussed this here in several issues in the past.
AFAIR the arguments against such additional markers was always, that they would clutter the map and be obtrusive and we additionally we did not find a good way to include them in the cache details.

From what I see in your screenshots however I like the implementation, while I would need to test it out / work with it to get a better understanding.

I have no problem to merge this on `master` to try it out in the nightly builds, but only two things:
- As you made several PR, which might depend on each other you should just tell the sequence for merging these
- If someone else from @cgeo/team is available for a code review, I would appreciate it. Else we should still merge this in some days (if you consider it ready to be merged).

**Comment by moving-bits** [comment]
> As you made several PR, which might depend on each other you should just tell the sequence for merging these

The three PR referring to this issue can be merged in no particular order: #7764 #7769 #7775. Best user experience for the "tag" feature is if you merge all three.

If you just want to see how the map markers for lists look like you only need #7775.

---

There is another issue in c:geo already present (#5193) which affects #7775 as well - icon size varies if overlays are added. The fix for #5193 requires some changes in #7775 as well, that's why I have marked #7775 as "WIP". So if you start with #5193, I need to do some change in #7775, and if you start with #7775 I need to adapt #5193.

If the varying icon sizes (which we do have already) do not harm you for testing the map list markers, you can start right away by merging #7775. (I will adapt #5193 then to work with #7775.)

Alternatively you could merge #5193 first, let me adapt #7775 to work with #5193, and merge this (or all three PR mentioned above) then.

**Comment by moving-bits** [comment]
> From what I see in your screenshots however I like the implementation, while I would need to test it out / work with it to get a better understanding.

I've implemented three things to support "tagging". Each PR can be used independently from each other, but also in conjunction:

### add list membership filter #7764
- allows you to filter for caches which have been assigned to a certain list
- example use case: you want to go on a Biltema tour and have assigned a couple of Biltema caches to a list "Biltema" - then you filter by this list, press on "show on map" and have your route for the day...

### optionally show additional list memberships in cachelist #7769
- shows the list memberships of a cache as an additional line in the cache list
- can be enabled / disabled (default) via the dot menu
- only shows those lists other than the list currently being shown (if any)
- example use case: during the recent promotion "mystery at the museum" you had to look for caches with certain additional attributes which c:geo does not save. Now you could research those attributes (eg: "has emerald", "has footprints") in advance of a tour, create a list for each attribute needed and store the caches accordingly. With those additional attributes being shown in the cache list it's easier to have a total overview

### optionally assign icon marker to lists #7775
- this is for visual representation of list memberships, especially in the map
- assign a colored "dot marker" to a list (optional)
- on the map (and the caches list) up to two colored dots are shown on the icon, if one of the assigned lists have a dot marker assigned
- example use case: easily get an visual overview of certain attributes
- as the lists names can be chosen individually, the attributes (tags) displayed can be very individual, like specific promotion attributes, certain cache attributes ("T5"), a certain priority etc.
- list markers can be assigned in caches list via the dot menu: manage lists => set list marker

Screenshots for those are in the respective PR.

**Comment by Lineflyer** [comment]
Thanks @moving-bits for the detailed explanations (never seen so many issue/PR references in one posting ;) )

I think we should go forward with #7775 first for testing unless the team objects for the feature itself. But as I heard no one screaming stop I would merge at first #7775 for testing. We could revert or modify later on anyway.

For #7764 I don't yet understand the use case completely. That is in fact the same than just opening a certain list, isn't it?

For #7769 I understand the use case. In fact it is just taking the information which is present in the cache details (=list membership) also into the list view. The optional enabling is also good to maintain "normal" view for users, who do not need this special information.

**Comment by Lineflyer** [comment]
After merging #7775 I played around a bit with this feature in our nightly. Looking quite good to me, nice work.

I also posted a "sneak preview" of this function on our social channels to get some user feedback and ideas. Some feedback I read there or got via PN for discussion:

- Most people seem to understand the idea behind and the possibilities this gives to them
- We could fill the color tags with their ID (1-5) as some people recall numbers better than colors and vice versa. But somehow I doubt, that this would be readable at all?!
- We could replace the disk icon by color tags to save space (as tagged implies saved). I have no clear preference here...anyway we probably need more space if several tags are active.

@moving-bits 
Reading your above posting, you would now need to adapt #7779 (fix for #5193) which I would also see as next step for merging and testing.

**Comment by moving-bits** [comment]
Hi @Lineflyer,

thanks for taking the time to playing around a bit with this feature.

> We could fill the color tags with their ID (1-5) as some people recall numbers better than colors and vice versa. But somehow I doubt, that this would be readable at all?!

I had started implementing something like this as well, not to get rid of the colors, but to offer some way to display prios. So there would be colored dots with the numbers 1 - 5 in them, in addition to the currently available numbers.
But so far I have no solution which is readable in all screen resolutions & densities.
For now I would prefer to stay with the colored dots only, and maybe add the numbered dots later.

> We could replace the disk icon by color tags to save space (as tagged implies saved). I have no clear preference here...anyway we probably need more space if several tags are active.

No preference on my side yet, either. As for the space for tags: Currently I have limited the visual tags display to a maximum of two tags - one on the left side, and one on the right side.
Reasoning behind this is:
- I could display more tags in top middle and bottom middle position as well, but that would lead to visual clutter IMHO.
- I could display a line of dots from middle left to middle right, but that would overlap the base icon's center.
- I could move the tags display to an additional line at the bottom (expanding today's icon space), but that would take up more space and the visual tag markers might stay in thin air, if no other marker is displayed at the icon's bottom.

In the end I decided to stay with two tags for now, at middle-left and middle-right positions, under the assumption that two visual markers will work in most cases.


> Reading your above posting, you would now need to adapt #7779 (fix for #5193) which I would also see as next step for merging and testing.

Will do.

**Comment by moving-bits** [comment]
> For #7764 I don't yet understand the use case completely. That is in fact the same than just opening a certain list, isn't it?

You open "list a" and filter for "list b": The result contains all caches which belong to both lists ("logical and connected").

**Comment by Lineflyer** [comment]
> You open "list a" and filter for "list b": The result contains all caches which belong to both lists ("logical and connected").

Yes, indeed interesting for several use cases.

**Comment by moving-bits** [comment]
> > You open "list a" and filter for "list b": The result contains all caches which belong to both lists ("logical and connected").
> 
> Yes, indeed interesting for several use cases.

Hm, I did not mean to say that it's logical and that it's connected, but in a boolean sense of "logical 'and' connected" in contrast to "logical 'or' connected" ;-)

**Comment by okainov** [comment]
@moving-bits do you consider the whole feature as c:geo-specific? What I mean, what do you think of such stuff from GC service directly? I.e. on gc.com they already have some "lists". Do you think can those lists be in sync at some point?

**Comment by moving-bits** [comment]
> @moving-bits do you consider the whole feature as c:geo-specific? What I mean, what do you think of such stuff from GC service directly? I.e. on gc.com they already have some "lists". Do you think can those lists be in sync at some point?

Currently lists are c:geo only, we're not syncing to any platform, and the feature is platform-agnostic.

IIRC there once has been an issue for syncing lists with gc.com, and we decided against it, not sure. But anyway, this would be a separate issue.

**Comment by moving-bits** [comment]
Closing this issue as all three related PR have been merged to master.
