### ISSUE TITLE
Show a permanent overlay on Live Map for users that aren't logged in to anything

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#7770]
I just read the PlayStore comments and this would prevent much confusion. This would be faster/easier to implement than the new onboarding UI.

**Comment by SammysHP** [comment]
Not only on the live map, but everywhere.

**Comment by jonas-koeritz** [comment]
Everywhere should be okay too ;)

**Comment by Lineflyer** [comment]
Yes, that would be a helpful think to make my fingers stoo bleeding from writing answers to these Playstore comments :)

Clicking could bring users to the recently implemented first steps page.

**Comment by SammysHP** [comment]
Just keep in mind that some people use c:geo entirely offline via GPX files. So the notification should be shown only if the live map is enabled or if the cache has no coordinates.

**Comment by jonas-koeritz** [comment]
Good point, the overlay could be show if the database has no caches whatsoever. That would make it disappear when caches get imported.

**Comment by SammysHP** [comment]
Sometimes it happens that the login didn't work or users forget to update their password in c:geo. Thus I think it would be better to always check if there is a valid login when data is requested and show a warning if it was missing.

**Comment by moving-bits** [comment]
@Lineflyer
Is this issue still relevant?

**Comment by Lineflyer** [comment]
Yes, why not.

**Comment by moving-bits** [comment]
> Yes, why not.

I thought maybe support requests for this have become less frequent and thus this warning not needed anymore.

Anyway, I created a workaround (see PR #7883):

![image](https://user-images.githubusercontent.com/3754370/66250980-8830b380-e74a-11e9-8d76-52e3810eaba1.png)

This message gets presented until at least one connector was able to log in.
