### ISSUE TITLE
Restore not working

### ISSUE THREAD

**Issue by luck428** [cgeo/cgeo#7774]
Requirement:
Migrate from old device to new device via backup restore
**Describe the bug:**
A clear and concise/summarized description of what the bug is.

1.) Backup create on old dewvice
2.) db file cgeo.sqlite copy to PC and from there to CGEO/backup on new device.
3.) Cgeo on new device recognices the DB back file in location 175505
4.) cgeo confirms import of backup was successfull 175516 
5.) returning to main screen. Cgeo knows DB is empty and finds the backup for restore and offers to restore again...hmmm 175526
6.) cgeo confirms again restore was successful 175531
7.) entering the save cache menu confirms zero cahces 175538
8.) return back to main menu cgeo offers again to restore and confirms 175544 & 175550. which of course fails again...sorry.

link to DB file 38 mb https://www11.zippyshare.com/v/SOLpKxIt/file.html
**To Reproduce:**
Steps to reproduce
![Screenshot_20190806-175538](https://user-images.githubusercontent.com/40830788/62556845-0cafa480-b876-11e9-9868-3aa30853d727.png)
![Screenshot_20190806-175544](https://user-images.githubusercontent.com/40830788/62556846-0cafa480-b876-11e9-8049-e527cf8e097e.png)
![Screenshot_20190806-175550](https://user-images.githubusercontent.com/40830788/62556847-0cafa480-b876-11e9-825e-5a2f327cd1f0.png)
![Screenshot_20190806-175505](https://user-images.githubusercontent.com/40830788/62556848-0cafa480-b876-11e9-9d3f-dbfbb6aaca75.png)
![Screenshot_20190806-175516](https://user-images.githubusercontent.com/40830788/62556849-0d483b00-b876-11e9-9930-73b91e53561b.png)
![Screenshot_20190806-175526](https://user-images.githubusercontent.com/40830788/62556850-0d483b00-b876-11e9-994a-1b6fdc7d64ae.png)
![Screenshot_20190806-175531](https://user-images.githubusercontent.com/40830788/62556852-0d483b00-b876-11e9-95a4-890ba286c543.png)

 the behavior:

**Actual behavior/state after performing these steps:**
Describe the actual issue/problem/behavior in detail.

**Expected behavior/state after performing these steps:**
Describe what you expected to happen instead.

**Version of c:geo used:**
2019.05.16

**Is the problem reproducible:**
Yes

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
This looks to me like a version conflict between the installed versions on both devices.

Please make sure both devices run the same version before starting any backup/ restore.

**Comment by luck428** [comment]
Both are on 2019.04.16. 
- Is the CGEO version number stored somewhere in the cgeo.sqlite file ?
- Is what i tried to do a supported way to migrate between devices or is this not supposed to work as tried ?
CGEO tells me multiple times the restore was ok which it was not....
Maybe you can try to import the DB file into your cgeo version link is provided...to verify
Generally users trust and rely on a restore to work. if it is version dependent some warning or docu updated would help...

**Comment by Lineflyer** [comment]
> Both are on 2019.04.16.

Are you sure, because you wrote 2019.05.16 already above. And when your "new device" is really fresh installed you will receive 2019.06.16 from Google Play Store.

> Is the CGEO version number stored somewhere in the cgeo.sqlite file ?

No, only the version of the database.

> Is what i tried to do a supported way to migrate between devices or is this not supposed to work as tried ?

Yes, see https://faq.cgeo.org/#replace-device 
It also mentions, that same version should be preferably used.

> CGEO tells me multiple times the restore was ok which it was not....

The multiple dialog is a known issue but not related to your problem.
The strange thing here seems to be, that it reports OK but has empty lists afterwards.
Are really all lists empty?

> Maybe you can try to import the DB file into your cgeo version link is provided...to verify

I wanted to try this already, but your link gives 403

> Generally users trust and rely on a restore to work. if it is version dependent some warning or docu updated would help...

As mentioned its documented in our FAQ.
It should(!) also work if the restore device has a a version >= old device. But as this is untested I wrote above you should better use the same version.

**Comment by luck428** [comment]
reupped on dropbox 
https://www.dropbox.com/s/5ngymkdmlbw1rc8/cgeo.sqlite?dl=0
I was not looking for "replace device", but rather for "backup and restore"  and not under FAQ where no version issue is mentioned. ok..

**Comment by moving-bits** [comment]
I tried to reproduce, but c:geo did not import any data from the DB. I tried to check with an SQLite browser to see what data is contained in the database, but my SQLite browser was not able to open the file:

![grafik](https://user-images.githubusercontent.com/3754370/62767171-6097d480-ba94-11e9-8027-9102c781cd66.png)

It looks like the SQLite file is corrupted. @luck428: Can you cross check?

**Comment by Lineflyer** [comment]
Yes, that seems to be the problem he is experiencing. cgeo reports its done but the stored lists are empty.
Any chance ti find out whats causing the corruption?

**Comment by moving-bits** [comment]
The "success" message is shown just by successfully having copied the sqlite file to the new location. Opening the database happens after that.

I went through the restore process step by step in the debugger:
- SQLite notices the corrupt database in LogCat:
  - E/SQLiteLog: (11) database corruption at line 63507 of [0c55d17973]
  - E/SQLiteLog: (11) database disk image is malformed
  - E/DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/user/0/cgeo.geocaching/databases/data
  - E/DefaultDatabaseErrorHandler: deleting the database file: /data/user/0/cgeo.geocaching/databases/data
- By recreating the new DB by the driver it gets internal version code 0, which leads to c:geo recreating all tables and indices.

I don't know if we have the means to catch the "DB corrupt" exception, but at least we recognize c:geo recreating an empty DB and should show some info message "DB initialized successfully" or something like that.

**Comment by moving-bits** [comment]
> Any chance ti find out whats causing the corruption?

Reason for this could be anything...
- error in c:geo (although creating a backup is not much mora than copying the DB file to a new location)
- OS error while creating the backup file
- error on the user's SD card
- error in drivers used to connect either the source or the target mobile device
- ...

**Comment by moving-bits** [comment]
I created PR #7778 to emit a warning message, if a restore silently failed due to a corrupt backup file.

But in the long run we probably should try to avoid the possible data loss (your current database gets overwritten by a corrupt database, and reinitialized after that). Possible solutions could be to create a separate backup before performing a restore or by pre-checking the backup file before restoring it.

**Comment by Lineflyer** [comment]
AFAIR we had such issue with corrupted DB here already in an issue. The problem there was, that the database got reproduicibly corrupted when performing a backup due to some content on the database being not valid. 

@luck428 Do you have the chance to do the backup again and check whether the database might got corrupted while transfering it?

**Comment by luck428** [comment]
new backfrom just one hour ago 
https://www.dropbox.com/s/u2txgtiagctrnjy/cgeo_20190809.sqlite?dl=0

**Comment by luck428** [comment]
screenshot of SQLlite 3 integrity check of the latest Backup

**Comment by luck428** [comment]
https://www.dropbox.com/s/awuz8mboo3rwyc7/Screen_%202019-08-09_01.jpg?dl=0

**Comment by luck428** [comment]
above DB Backup file was created by CGEO version 2019.04.16,. just to reconfirm !

**Comment by Lineflyer** [comment]
> above DB Backup file was created by CGEO version 2019.04.16,. just to reconfirm !

And this file is not restoreable on your other device?

**Comment by moving-bits** [comment]
Thanks for providing a new backup file. I retested with that file on current master version:

- uninstalled c:geo
- installed current master version of c:geo
- copied sqlite file to cgeo/backup directory
- started c:geo, authentificated against gc.com
- c:geo did not recognize the backup file automatically, so I manually started the restore process via dot menu on main screen => backup / restore => restore
- c:geo finished the backup successfully
- main screen shows 2299 caches total, 601 in default list "stored"

So restoring's fine with this database, at least when using the current master.

**Comment by moving-bits** [comment]
> Is the CGEO version number stored somewhere in the cgeo.sqlite file ?

No, only the internal DB scheme version number, which most of the time stays the same over a couple of c:geo versions, as DB changes are relatively seldom.

Also: Normally it should work to use a DB backup of an older version of c:geo and restore it with a newer version, even if DB scheme has changed in between - c:geo will upgrade your DB. So in your case you can try to restore your DB with the current (release) version of c:geo.

But be aware: What definitely won't work is a database downgrade. So a DB backup of a newer version of c:geo cannot be read by an older version of c:geo if the database has changed in the meantime.

**Comment by moving-bits** [comment]
@luck428
Is this issue still relevant / open?
