### ISSUE TITLE
Log (discover/grab) trackable produces error

### ISSUE THREAD

**Issue by msebald** [cgeo/cgeo#7780]
**Describe the bug:**
When I try to log (discover or grab) a trackable it produces an error. But it works on geocaching.com as I have discovered or grabbed the TB when I check there on the website.

The error messages led to several tries until I found it.

I experience this error for months now and also I did not find it here (maybe used the wrong search terms), so I am opening a bug report now.

**To Reproduce:**
1. Open a trackable, e.g. by searching for it.
2. Click on the pen in the upper right corner.
3. Discover or grab it, write something into the text box and send it.
4. See the error as an overlay in the bottom part of the page.

**Actual behavior/state after performing these steps:**
Error is shown but log is done on the geocaching.com website/database.

**Expected behavior/state after performing these steps:**
No error. ;-)

**Version of c:geo used:**
2019.08.05-NB-864825c (but I am experiencing this error for months and lots of older versions now)

**Is the problem reproducible:**
Yes

**Screenshots:**
I can produce screenshots if you like, at the moment I do not have any.

**System information:**
```
--- System information ---
Device: Mi A2 (jasmine, xiaomi)
Android version: 9
Android build: PKQ1.180904.001.V10.0.12.0.PDIMIXM
c:geo version: 2019.08.05-NB-864825c
Google Play services: enabled - 18.3.82 (100408-260264002)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (14,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (14,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (14,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1,6 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Comment by SammysHP** [comment]
What is the error message?

**Comment by Lineflyer** [comment]
I succesfully grabbd a TB 2 days ago with nightly build 2019.08.09-NB. Seems not to be a generic problem.

**Comment by msebald** [comment]
Just checked, here's the German error message:

"Der Log-Eintrag wurde scheinbar nicht gesendet. Bitte auf der betreffenden Geocaching-Webseite prüfen."

Sound like pretty generic/basic text.

But I found out something: Yes, it is not a generic problem. It seems to be related to Twitter Publish ("Diesen Eintrag auf Twitter veröffentlichen"). If I uncheck this a comment on the TB (I could not check "Discover" and "Grab" on my own TB) went through without any error back to the main page of the TB.

**Comment by Lineflyer** [comment]
@msebald 
Coming back to this stale issue. According to your last posting it was related to your twitter posting. Maybe it was a problem, that your authentication towards Twitter was not correct/active.

Is the problem still happening?

**Comment by msebald** [comment]
@Lineflyer No idea, did not grab another TB through cgeo. As tweeting found geocaches always works without any problems (before and after I posted this issue) I would say that there is not a general problem with Twitter here.

**Comment by eddiemuc** [comment]
Twitter publish was removed meanwhile. Does the problem still occur?

**Comment by eddiemuc** [comment]
Closing for now. Please reopen if problem still occurs.
