### ISSUE TITLE
Outdated icon tags shown in list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7786]
**Describe the bug:**
I encountered the problem, that I do see wrong color tags in cache lists.
However as I played around a lot I am not sure if this is reproducible.

**To Reproduce:**
1. Assign tag 1 to list A
2. Have list B which is a subset of list A (i.e. all caches of list B are also part of list A)
3. Assign tag 2 to list B
4. Remove tag 2 from list B
5. Open list A

**Actual behavior/state after performing these steps:**
Icons in list A showing two color tags (1 and 2)
Only after opening closing respective cache on the list the tags get updated (only tag 1 shown)

**Expected behavior/state after performing these steps:**
It seems the icons are only updated if the cache details are opened.
The icons should be updated when opening the list to ensure correct status of the tags

**Version of c:geo used:**
2019.08.15-NB1

**Is the problem reproducible:**
not tested

**Comment by moving-bits** [comment]
Good catch, thanks! I prepared a fix for this, see #7788.
