### ISSUE TITLE
Icon overlays too small on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7792]
**Describe the bug:**
After recent changes the overlays for cache icons (final, note) are smaller than before and too small to identify on my device.

**Version of c:geo used:**
2019.08.17-NB

**Is the problem reproducible:**
Yes

**Screenshots:**
![Screenshot_20190817-125037_cgeo](https://user-images.githubusercontent.com/949669/63210414-32e30900-c0ee-11e9-8f77-f9a528c17af4.jpg)

**System information:**
Samsung Galaxy S10, Android 9

**Additional context:**
@moving-bits

**Comment by Lineflyer** [comment]
Also waypoints of caches (e.g. parking, trailhead, reference point) look strangly different to before the recent change. IMHO the icon itself (e.g. the P for parking) does no longer fill in the white circle as good as possible but got smaller within.

**Comment by moving-bits** [comment]
That's probably due to different ways of scaling before and now. I think I'll need to rescale the overlays to make them fit.

Does anyone have the high resolution original images for me?

**Comment by moving-bits** [comment]
Another reason is that there are _some_ icons missing for some higher densities, so Android upscales them from lower densities (eg: personalnote, stored, usermodifiedcoords overlays).

There are more inconsistencies. - I will open a separate issue for this.

**Comment by moving-bits** [comment]
Fixed with #7806
