### ISSUE TITLE
Use compact icons apparently does not always work for waypoint icons

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#7799]
Just tested against known crashes of previous version release, after upgrade to 2019.08.18.

Using map with "old mapsforge v3" disabled. 

As I switch "map settings" -> "use compact icons", the icons for waypoints do not change. 

Steps to reproduce: 
1. open map
2. map settings, check "use compact icons".
waypoint icons are unchanged.

if at this point I go back to main menu, then return to map, now all icons are the same (as they should be displayed correctly). 

3. uncheck "use compact icons"
waypoint icons remain unchanged (compact). 

again, if I go to main menu, then back to map, now I see icons correctly. 

**Expected behavior/state after performing these steps:**
All icons should change consistently. 

**Version of c:geo used:**
2019.08.18

**Is the problem reproducible:**
Yes

**Screenshots:**
![Screenshot_20190822-122352_cgeo](https://user-images.githubusercontent.com/3382777/63503293-dd38a300-c4d7-11e9-900f-1b84a3c5b048.jpg)

**System information:**
![Screenshot_20190822-122532_cgeo](https://user-images.githubusercontent.com/3382777/63503343-f5102700-c4d7-11e9-877d-2c37375fc4ba.jpg)

**Comment by moving-bits** [comment]
This might be related to #7695 - while debugging into that issue I found out, that the cache icon gets updated, but not the waypoint marker belonging to it. (Just have not found the reason for it yet.)

**Comment by rsudev** [comment]
I guess I have already seen this on machine while tackling a different issue. 
I think I have a fix ready (will test and push this evening)

**Comment by moving-bits** [comment]
> I guess I have already seen this on machine while tackling a different issue.
> I think I have a fix ready (will test and push this evening)

Thanks, this would be cool - spent a couple of hours debugging the last days to get to this point, but couldn't get hold on the last step.

**Comment by andrixnet** [comment]
Could this also be in any way related to the issue about waypoint icons of removed caches still shown? (maybe this: https://github.com/cgeo/cgeo/issues/4357 )
