### ISSUE TITLE
Google maps/satellite use old mapsforge v3?

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#7800]
When using Google: Map and Google: Satellite, these are shown using "old mapsforge v3" library, apparently, even though this has been disabled in Settings->Map. 

I deduce this from the following: 
- map settings menu is the old style menu 
(AFAIK show circles is not available in the newer library)
- the new tile scaling for high res displays is not applied.

**To Reproduce:**
1. have "old mapsforge v3" disabled in settings->maps
2. open map. choose a google layer.
3. open map settings (for confirmation)

**Expected behavior/state after performing these steps:**
There is room for a lot of discussion and what should be done, I think. 
- hide unsupported layers according to settings? 
- it would be a settings consistent behaviour to show only supported layers by selected map library. 
- it is detrimental to the user to prevent google layers usage if newer library selected (also default setting), but results in inconsistencies (such as presented here). 
- it would mean complicating the life of the user to show him error message and instructions to change library setting to see google layers
- it would be vary bad policy towards users to simply hide the google layers and only make some reference in the docs about it (bad PR).

I presume this is because the newer library does not support google layers or other technical or legal reasons and solving these problems would automatically resolve this issue as well. 
_Can it be solved in the not too distant future?_

I also suspect this mixup has caused many crashes in the previous release. (I experienced and reported some myself).

**Version of c:geo used:**
2019.08.18

**Is the problem reproducible:**
Yes 

**System information:**
Same as described for https://github.com/cgeo/cgeo/issues/7799

**Comment by SammysHP** [comment]
The Google map uses the Google library, of course. There are several issues related to that part of c:geo.

**Comment by andrixnet** [comment]
Current behaviour seems to switch between mapsforge (new) and something like mapsforge v3 when showing Google maps because the menu is the same as v3. 
End user confusion. Sorry.
