### ISSUE TITLE
Illegal Argument Exception in mapsforge V6

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7804]
**Describe the bug:**
Tonight I tried to debug a user problem online on Facebook looking into the real time crash reports.
The user problem was, that c:geo crashed immediately after invoking any map action (live map, map of a cache). The user was using an offline map. 
After changing to Google Maps in settings the problem was gone. After changing back to OSM, no matter if offline or online, the crashes have been back.

I think I have tracked down the relevant report on Google Play.
This seems to be a rather special case as it affects only two users at the moment.

Still I would like to know whats going on here

Stack trace:
```
java.lang.IllegalArgumentException: 
 
  at org.mapsforge.core.util.LatLongUtils.validateLongitude (LatLongUtils.java:317)
 
  at org.mapsforge.core.model.LatLong.<init> (LatLong.java:53)
 
  at cgeo.geocaching.maps.mapsforge.v6.layers.HistoryLayer.draw (HistoryLayer.java:78)
 
  at org.mapsforge.map.layer.LayerManager.doWork (LayerManager.java:94)
 
  at org.mapsforge.map.util.PausableThread.run (PausableThread.java:147)
```
**Version of c:geo used:**
2019.08.18

**Is the problem reproducible:**
I cannot reproduce

**System information:**
Samsung S9
Android 9

**Comment by jonas-koeritz** [comment]
I'm tempted to call this a "Samsung" problem. Maybe their OS returns invalid GPS coordinates when GPS is off or still looking for a fix? And c:geo records these invalid coordinates into the history. Mapsforge crashes when trying to draw them.
Would be good to know if GPS was on or off on the device while trying this.

**Comment by rsudev** [comment]
IMO this is a bit of a conceptual problem in the NewMap history layer. The coordinates are checked and stored according to a our own validation logic (in PositionHistory), but then assumed to be conformant to the boundary conditions of the LatLong class from mapsforge (I didn't check, but generally I would not assume that those to items share a common understanding of 'valid').
In that sense should the HistoryLayer generally 'check' the coordinates (or prevent a conversion/drawing problem from crashing the app).

**Comment by Lineflyer** [comment]
Looking through issue least recently updated with label "Unverified":

This crash report "Illegal Argument Exception" is not seen any longer on Google Play Console.
Closing here.
