### ISSUE TITLE
new "Long press" hint in services menu needs a reformat.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7805]
The new "Long press to remove...." hint in the services menu gets truncated if the users profile picture is too big. 
See attached screenshot.

![Screenshot_20190823-151824](https://user-images.githubusercontent.com/7459480/63599614-dda96a80-c5b9-11e9-86df-0a785bd7fdfa.png)

**Comment by Lineflyer** [comment]
I thought we would either scale this image for display or the server already scales it. Seems I was wrong. What file format and pixel size does your avatar picture have?

**Comment by alan666notb** [comment]
> What file format and pixel size does your avatar picture have?

I can't answer that, that's not my account - I was trying to explain to someone how to reset their login.

**Comment by Lineflyer** [comment]
I played around with different sized avatar images, however they all have been rescaled properly (probably already on server side). So right now I could not find a way to reproduce.

**Comment by Lineflyer** [comment]
@alan666notb 
Any idea if this is still existing. As written some time ago I was not able to reproduce at that time and have never seen it afterwards either.
