### ISSUE TITLE
Wrong event end date for calendar

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7814]
Open GC8CWFZ
Select to add to calendar

On my samsung calendar app it shows start date and time correct but end date on Aug.31st.

Not sure if its my calender app or cgeo causing this

**Comment by Lomanic** [comment]
cgeo 2019.08.18 on LineageOS 14.1 (Android 7.1.2), the calendar event is at the right time and day for me.

**Comment by Narrat** [comment]
Experience similar symptoms. But they differ in such a way, that the end date is set to the current day and time. And I thought it is due to the used calendar app.

**Comment by bekuno** [comment]
Maybe it is related to #7645.

**Comment by Lineflyer** [comment]
More reports like this:
Start date and time is OK, but end date is always "today"

**Comment by Lineflyer** [comment]
Another report like this, where start date + time is correct but end date is always the date at which the entry is created.
```
--- System information ---
Device: SM-A202F (a20eeea, samsung)
Android version: 9
Android build: PPR1.180610.011.A202FXXU3ASL4
```

I suspect a problem of the calender app on those devices, as it is working flawless with my test devices.

Closing for now.

**Comment by Lineflyer** [comment]
Addition:
The recent user with this problem confirmed, that the problem was solved by updating his (Samsung) calendar application.
