### ISSUE TITLE
Add "location" to log template menu

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#7817]
In the logging activity you can insert various elements like date, time, number, owner name etc. Sometimes the log requires to post a location. I suggest to add another entry to add the current position, maybe with the help of the coordinates popup to modify them and optionally select a position on the map.

**Comment by spacemonkey1101** [comment]
Hello There! 
I think I would be able to do this with some help.

**Comment by fm-sys** [comment]
@spacemonkey1101  Very Wellcome!

You can use `Sensors.getInstance().currentGeo().getCoords()` `from cgeo.geocaching.sensors.Sensors` to get the current coordinates. For adding a new log template you can take a look at [#9064](https://github.com/cgeo/cgeo/pull/9064/files)

**Comment by eddiemuc** [comment]
I hope users are turning off this feature actively when they log a mystery cache while still nearby it...

**Comment by fm-sys** [comment]
Maybe we can hide this template in the signature settings and only show it in the drop down list while logging

**Comment by fm-sys** [comment]
Otherwise, if we want to use the coordinate popup (which would be a really nice feature) it will not work with the log template architecture.

>and optionally select a position on the map.

Btw this is tracked here:  #7811

**Comment by Lineflyer** [comment]
> I hope users are turning off this feature actively when they log a mystery cache while still nearby it...

I doubt that many users wil use such feature by default in their signature.
Furthermore its anyway users responsibility not to spoil in their logs. No need for us to block any function.

**Comment by sophiastr** [comment]
i want to deal with this issue.
I am interested in contributing to the project you are developing.
Do you still need help?
I'm a beginner but I will try really hard.

**Comment by eddiemuc** [comment]
Hi  @sophiastr , welcome to c:geo. We are always thankful for new contributors, so it is great that you want to get involved!

The first step would be to set up your local development environment. How to do this is described in the readme page (https://github.com/cgeo/cgeo#readme). If you plan to make a contribution, make sure to fork the cgeo repo, then clone your fork to your local machine (do not clone cgeo repo directly to your local machine). You should come as far as compiling and running cgeo from branch master as-is in an android phone emulator (those come with the IDE, Android Studio).

As for the issue you chose, the code entry point would probably be class `cgeo.geocaching.log.LogTemplateProvider`, method `getTemplatesWithoutSignature() `. See #9064 for an examppe. You will probably need to get the current user location at some point when implementing this, you will get this via `Sensors.getInstance().currentGeo().getCoords()` from class`cgeo.geocaching.sensors.Sensors`

**Comment by ztNFny** [comment]
What's the usecase for this? Like when wouldnyou want to include your coords in a log? Either it's a tradi and the listing already has the info about coords - no added value - or it's a mystery/multi and you definitely don't want to post the coords.

**Comment by fm-sys** [comment]
> What's the usecase for this?

Sadly, there are quite some Tradis with coordinates 20m off or even more...

>or it's a mystery/multi and you definitely don't want to post the coords.

That's why it would be good to not show it in the signature settings but only in the drop down list while logging. (https://github.com/cgeo/cgeo/issues/7817#issuecomment-699451008)

**Comment by eddiemuc** [comment]
> >or it's a mystery/multi and you definitely don't want to post the coords.
> 
> That's why it would be good to not show it in the signature settings but only in the drop down list while logging. (https://github.com/cgeo/cgeo/issues/7817#issuecomment-699451008) 

If a user really puts this into her signature (which I doubt many will do) then it is also her responsibility to delete it from log before sending it out when currently in a sensitive place (e.g. final of a mystery/multi).

**Comment by nmrsmn** [comment]
Hi all, I would like to solve this issue, but I'm not sure if @sophiastr has already started working. 

I'm new to this repo. I've been using c:geo for some time now and I would like to get involved in the community as a contributor to this great project. I'm a professional Android (and iOS) developer and I love to work on project in my spare time.

**Comment by Lineflyer** [comment]
@nmrsmn 
Thanks for your interest in c:geo and you are welcome to work on the project!! 

Regarding this issue I am not sure, whether @sophiastr is already working on it. Maybe we give her a chance to provide feedback whether there is already work in progress, I have however not seen any activity here or in pull requests regarding this topic.

If you need any help for setting up the project, feel free to ask here (or open a dedicated issue).

**Comment by sophiastr** [comment]
I am not working on it. Thanks for asking. I am working on a different issue.
Good luck!

**Comment by moving-bits** [comment]
implemented with #12932
