### ISSUE TITLE
Smoothen Trail History

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7830]
**Is your feature request related to a problem?**
Switching screen off when it's not needed (in order to save battery life) with GPS switching off when screen is off (same goal, of course), produces GPS position jumps, as first GPS reading seems to either give no position at all (that given, c:geo jumps to home position) or a random one (seemingly where GPS has been a short while ago).

These jumps are stored without any filtering in the trail history and may result in a sometimes extremely weird track, which becomes nearly unreadable, even over short periods of time, in extreme situations even the map cannot be read properly anymore.

**Describe the solution you'd like**
A GPS position resp. it's movement may only be stored in the trail history, when reliability of GPS position is high enough and distance to last x number of readings is below a predefined or even configurable value. BTW: a trail history, jumping around the home position just because the GPS does not give reliable readings or is even switched off, is not really meaningful anyway. ;)

**Describe alternatives you've considered**
Alternatively trail history should be smoothed afterwards (using e. g. Ramer–Douglas–Peucker algorithm)

**Comment by moving-bits** [comment]
There are several issues with trail history drawing:
- error in trail history routines of our Mapsforge map implementation, which prevented a correct distance calculation and also caused the current position to be connected with the beginning of the trail history
- trail history routines of Google Maps v2 implementation did not respect the maximum distance at all (as well as ignored the trail color setting)

**Comment by moving-bits** [comment]
fixed with #7895
