### ISSUE TITLE
replace viewpagerindicator

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7834]
The original viepagerindicator is archived, the in c:geo integrated fork was only a bugfix.
This version uses the com.android.support:support-v4 library in the maximal supported version 25.2.0.
With switch to compileSdkVersion 27 we have to use a compatible supportLibraryVersion, the latest is '27.1.1'.
This difference could lead to runtime crashes or other problems.
One possible replacement could be https://github.com/hackware1993/MagicIndicator

**Comment by bekuno** [comment]
We can now use 
https://developer.android.com/jetpack/androidx/releases/viewpager
and
https://developer.android.com/jetpack/androidx/releases/viewpager2

How about these?

**Comment by Lineflyer** [comment]
This has been done with implementing a new material tabs.
