### ISSUE TITLE
Add "Hide archived" option to map settings

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7848]
**Is your feature request related to a problem?**
I like to keep all of my own caches in cgeo, even the ones that have been archived.
However, these are all shown on the map making it unusable.

**Describe the solution you'd like**
Under map-settings, there could be a "Hide archived" option (There is a "Hide disabled" option but I still want to see live caches that are disabled).

**Describe alternatives you've considered**
There could be a flag added to each list to say "Don't show caches in this list on the map".

**Comment by MagpieFourtyTwo** [comment]
Would be great to have filters in live map, anyway. E. g. "Just show offline saved caches" ...

**Comment by Lineflyer** [comment]
Relevant feature request....also refer to linked issues.
