### ISSUE TITLE
map insets are too large on Android 9+ after switching to targetSDK 28

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7854]
After switching targetSDK from 27 to 28 map overlays are drawn way too big:

![image](https://user-images.githubusercontent.com/3754370/64913690-eb7b8700-d744-11e9-95eb-285bec802056.png)

This is happening on both Google Maps v2 and NewMap (OSM).
(Switching between compileSDK 27 and 28 does not seem to have any influence on this.)

**Comment by MagpieFourtyTwo** [comment]
Same same in cache lists.

**Comment by Lineflyer** [comment]
Oh yes. At least when it comes to most obvious bugs this is the only regression I could see after updating my nightly when returning from vacation.It kins of makes the overlays unusable. Is someone workin on it?

**Comment by moving-bits** [comment]
> Is someone workin on it?

Yes and no. I did some analyzing, but got stuck. What I have so far is:

- regression got introduced by setting targetSDK to 28
- it is visible on Android 10, but not under Android 8 and below (have not tested 9 yet)
- regarding the routine preparing the overlays:
  - base marker image size is correct (ie: code retrieves the same dimensions in px which the file for the current density has on disc), same for overlay image size
  - diff and positioning: px are calculated correctly
  - but for some reason the overlay gets scaled, whereas the base marker image does not
- it's not dependent on the overlay's dpi setting (which vary widely from overlay to overlay, and is mostly different from base marker image's dpi setting)
- I haven't found any obvious change between Android 8 and 10 regarding overlays, and no stackoverflow article mentioning this (but maybe didn't use the right search keywords for the latter)

Any other ideas?

**Comment by Lineflyer** [comment]
Visible also on Android 9.
Can test other versions on the weekend.

**Comment by Lineflyer** [comment]
On my Android 5.0.2 device it looks totally normal using 2019.10.02-NB.

Either depending on Android version or (maybe more likely) on dpi level used depending on device resolution/screen density?!

**Comment by moving-bits** [comment]
Thanks for cross-checking.

> Either depending on Android version or (maybe more likely) on dpi level used depending on device resolution/screen density?!

My test were based on the same (emulated) device, so having identical resolution and density, but different Android versions. Several older versions (up to Android 8) were fine, Android 10 showed the artifacts.

**Comment by jonas-koeritz** [comment]
I haven't tested the latest nightly yet but the problem is showing on my
Pixel 2 XL on Android 10.

moving-bits <notifications@github.com> schrieb am Do., 3. Okt. 2019, 10:53:
