### ISSUE TITLE
Android gradle plugin 3.5.x - failure "Could not find the AndroidManifest.xml file"

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7858]
With the gradle plugin 3.5.0 the compilation fails.

~~~
Execution failed for task ':main:compileBasicDebugJavaWithJavac'.

error: Could not find the AndroidManifest.xml file, using  generation folder 
[C:\Users\xxx\StudioProjects\cgeo\main\build\generated\ap_generated_sources\basicDebug\out])
~~~

Maybe it is related to 
https://developer.android.com/studio/known-issues#manifestOutputFile 

(testet on top of PR #7855)

**Comment by bekuno** [comment]
@Bananeweizen Can you check this please

**Comment by bekuno** [comment]
It is unchanged with AS 3.5.1 and plugin 3.5.1

**Comment by moving-bits** [comment]
Reproducible with current master, therefore removing "unverified" label.
