### ISSUE TITLE
Person notes vs. waypoints

### ISSUE THREAD

**Issue by j0ckser** [cgeo/cgeo#7859]
**Coordinates entered into Personal notes become Waypoints:**
If a set of coordinates is entered into Personal notes, they are picked up by Waypoints and cannot be changed in any way, or deleted.

**To Reproduce:**
1. Go to 'Description' tab of any geocache. Scroll down to 'Personal note'.
2. Enter a complete set of coordinates; any coordinates will do. I only use decimal minutes, and have not tested other coordinate formats (N 53 33.333' W 113 33.333') [N.B. I cannot show degree symbol here].
3. Back out to the main dashboard.
4. Return to the cache page.
5. Go to Waypoints tab and the coordinates will be listed as a waypoint with the name "Personal note 1'
6. Any attempt to edit this waypoint will fail.

**Version of c:geo used:**
2019.09.08

**Is the problem reproducible:**
Yes

I find this issue to be a nuisance with no redeeming value. The best solution is to remove the link between 'Personal note' and 'Waypoint'. I use Personal note to keep thoughts about the cache. Waypoints are important for stages in multicaches and for final locations for mystery caches. Since the Personal note coordinates in Waypoints cannot be edited or changed, they have no value.

**Comment by UniQP** [comment]
I do not understand the reason behind the issue. Can you give an example of a coordinate that should not show up as waypoint?

You can change the coordinate by changing your personal note.

**Comment by mucek4** [comment]
This is basically how awesome c:geo is.

**Comment by j0ckser** [comment]
GC194KV in my profile will show that the CO set up an empty Final Coordinates waypoint to be filled when I solve the puzzle. I now have a PN waypoint with the final coords and an empty FC waypoint. While I can fill the FC waypoint with coordinates, I cannot remove the PN or edit the name to FC. If I edit, calling it FC, then the PN is recreated and I have yet another PN waypoint.
