### ISSUE TITLE
Live Map: "Switch on Map Update" while looking at Map View of a Waypoint

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#7862]
**Is your feature request related to a problem?**
With the latest version of BROUTER you will get no "Car"-route when the target point is too far away from an official road. In order to get a route anyway, you have to manually set an additional waypoint (e. g. "Parking") and let BROUTER route thereto - and everything seems to be fine.

But unfortunately you are now not able any more, to see other caches on your way to this waypoint, as the "Switch on Map Update" (or whatever the correct name of this option is, can not check, as c:geo can still not be switched to english) is disabled while displaying a waypoint on the map (waypoint has been selected from navigation button in waypoint list).

**Describe the solution you'd like**
Enable menu entry "Switch on Map Update" even when "just" a waypoint from of the waypoint list is shown.

**Describe alternatives you've considered**
When checking "Set as cache coordinates locally" in the waypoint, you can activate Map Update anyway, but this is not really comfortable and sometimes hard to reset resp. confusing ...

**Comment by Lineflyer** [comment]
AFAIK there was some technical reason why we did not implement the "enable live" on a single waypoint map.
That was the reason we implemented that you can show the additional waypoints also on the "normal" live map, where you can do all this.

**Comment by MagpieFourtyTwo** [comment]
Ok - would be nice if s/one could (re)check feasibility again, cause not being able to switch on map update in single waypoint's context is not really straight forward nor consistent. BTW: Same applies to creation of a waypoint by tap on a single waypoint's map ... ;)

Nevertheless, thx a lot for your suggestion, cause it led me to a way to get what I "need":

1. go to cache's waypoint list (with e. g. parking lot waypoint)
2. open map for the complete list, using the compass rose in the header line
3. if necessary: create a waypoint where you want to (resp. BROUTER is able to) navigate to (via longpress on the map)
4. tap on the map icon of your newly created navigation target (Hint: do NOT leave the map in this very moment, as in the waypoint list you will not see the newly created waypoint yet - to make it visible in the list, too, from the list tap "Add waypoint" and just cancel this action by tapping the [X] - now you will see the new waypoint - and then proceed at 2. ;) )
5. tap the "Arrow" symbol (do NOT use the compass rose!)
6. Et voilá! Now you have the BROUTER route to your waypoint *and* the menu entry "enable live", thus see caches next to your route while navigating to other than cache coordinates. :)

Nice. Although I don't really see why it should not be possible to do resp. achieve this by a simple tap on a menu entry ... ;)

**Comment by Lineflyer** [comment]
Looking through issue least recently updated with label "Unverified":

@MagpieFourtyTwo 
Seeing not a high demand to implement that (and having in mind some discussion in the past, why enabling live in contect of a single waypoint was difficult): Are you fine with the workaround provided and we could close this?

**Comment by fm-sys** [comment]
Meanwhile, another workaround is to reselect "map" in the bottom navigation...

**Comment by MagpieFourtyTwo** [comment]
Jep.
