### ISSUE TITLE
test framework changes cause tests to fail (compileSDK28 / targetSDK28)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7866]
**Describe the bug:**
Tests fail when run using compileSDK28. See https://ci.cgeo.org/job/cgeo%20pull%20request/2307/console

eg:
```
14:07:29  > Task :main:compileBasicDebugAndroidTestJavaWithJavac FAILED
14:07:29  63 actionable tasks: 58 executed, 2 from cache, 3 up-to-date
14:07:29  /home/jenkins/slave/workspace/cgeo pull request/tests/src-android/cgeo/CGeoTestCase.java:9: error: package android.test does not exist
```

**Possible reason**
There are relevant changes to the Android testing framework with Android 9 / API 28, see https://developer.android.com/about/versions/pie/android-9.0-changes-all#android-test-changes

**Comment by Bananeweizen** [comment]
I think the AndroidX testing infrastructure can be introduced independently of changing to SDK 28. If I remember right, that is basically the default testing library since about 2 years, where we still use an old pre-AndroidX lib.

**Comment by moving-bits** [comment]
> I think the AndroidX testing infrastructure can be introduced independently of changing to SDK 28.

It depends on **compile**SDK. As soon as we switch compileSDK from 27 to 28, our tests (using the old Android testing framework) fail with `error: package android.test does not exist`.

As we want to keep compileSDK and targetSDK at the same level, updating our tests to the current testing framework become a prerequisite for switching to targetSDK28, although the switch can (and should) be done before.

Who has knowledge of the Android testing framework and can do the update?

**Comment by UniQP** [comment]
> As we want to keep compileSDK and targetSDK at the same level, updating our tests to the current testing framework become a prerequisite for switching to targetSDK28, although the switch can (and should) be done before.

It's fine to update the compileSDK before updating the targetSDK.

**Comment by Bananeweizen** [comment]
What I meant with my previous statement is that the testing lib upgrade can be done _before_ the SDK level changes, separately.

**Comment by bekuno** [comment]
@Bananeweizen done :-)
