### ISSUE TITLE
Log pictures of OC.de caches not loaded

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7884]
- Open OC15754
- Open logbook
- There is one log entry with picture attached

It does not load/open for me, but only shows default placeholder for image.
On the website it shows normal.

Other caches also affected for me (geocode is just an example).

Did not further test yet whether it is reproducible.

**Comment by bekuno** [comment]
It loads fine on my note 8 (Android 9)

**Comment by MagpieFourtyTwo** [comment]
Perhaps this is related to issue #7889 which I've just filed ...?

**Comment by moving-bits** [comment]
This is related to #7889 and fixed by #7892 as well.

**Comment by Lineflyer** [comment]
Could be related. Need to retest after #7889 is fixed.
