### ISSUE TITLE
 Feature Request - Show County on Map

### ISSUE THREAD

**Issue by Uli001** [cgeo/cgeo#7900]
**Is your feature request related to a problem?**
Auf meinen Touren suche ich mir gerne Caches aus die in einem neuen Landkreis liegen. Leider ist es mir nun wiederholt passiert, dass der Cache nicht in dem gewünschten Landkreis liegt. Ich haben diesen also verpasst und müßßte noch einmal dorthin. 
On my tours, I like to search for caches that are in a new county. Unfortunately, it happened to me repeatedly that the cache is not in the desired district. So I missed it and would have to go there again.

**Describe the solution you'd like**
Es wäre auf der Karte die Landkreise zu sehen. In GcDroid ist diese Funktion z.B. implementiert.
It would be on the KArte the counties to see. In GcDroid this feature is implemented.

Grüße Uli
Greetings Uli

**Comment by moving-bits** [comment]
c:geo is already able to show border lines, even county borders, but it depends on which map and which map theme you are using.

For Mapsforge maps you can use the maps provided by download.mapsforge.org (IIRC) and use a map theme like Elevate (don't have the URL at hand for this one right now). After installing those you can set "Kartendarstellung wählen" to use this theme, and "Themen-Optionen" to activate the map elements you want to see (like borders).

**Comment by Uli001** [comment]
Danke für die Antwort,

Ich habe mich schon immer gewunder wofür die Option "Kartendarstellung wählen" ist. Bei mir steht dort immer nur "Standard". "download.mapsforge.org" scheint  aktuell nicht erreichbar zusein. Meine Offline Karte kommt aber noch von dem Server. Ich habe http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/ als eine alternative gefunden. Die Karten helfen mir aber nicht. 

Thanks for the answer,

I have always wondered why the option "Kartendarstellung wählen" is. With me there is always only "standard". "download.mapsforge.org" seems currently unavailable. My offline card is still coming from the server. I found http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/ as an alternative. The maps do not help me.

**Comment by moving-bits** [comment]
The map file alone is not enough, you also need to install a map theme. Search for "Elevate.xml map theme", install and select it in c:geo.
This worked for me with the map of Germany and the borders between the Bundesländer. Or do you mean Landkreise etc.? (Sorry, have not read your first post thoroughfully enough.) I don't know of a map which includes the data for this, but if you find one, the way to show them should be as described. Maybe you can find out which map file GCDroid is using.

**Comment by Uli001** [comment]
Ich habe mir jetzt von hier (https://www.openandromaps.org/kartenlegende/elevation-hike-theme) die Elevate 4 (4.3.3.1, 30.09.19) geholt und installiert. Jetzt kann ich wirklich bei "Karteneinstellung wählen" zwischen verschiedenen Darstellungen wählen. Für meine 
aktuelle Karte scheinen jedoch die Landkreise nicht angezeigt zu werden. Ich hole mir gerade von der selben Quelle neue Karten. 
Ich möchte wirklich die Landkreise sehen und nicht die Bundesländer. Ich war bereits in allen Bundesländern in 24 Stunden.

Danke für deine Hilfe

I have downloaded from here (https://www.openandromaps.org/kartenlegende/elevation-hike-theme) the Elevate 4 (4.3.3.1, 30.09.19) and installed. Now I can really change by "Karteneinstellung wählen" to choose between different representations. For my current map the counties do not appear to be displayed. I'm getting new maps from the same source.
I really want to see the districts and not the federal states. I was already in all federal states in 24 hours.

Thank you for your help

**Comment by jakedot** [comment]
A map including county level boundaries and also a theme with the options
to display them would be Freizeitkarte - it works properly for me.

>
https://www.freizeitkarte-osm.de/android/de/index.html

**Comment by jakedot** [comment]
A map including county level boundaries and also a theme with the options
to display them would be Freizeitkarte - it works properly for me.

You will need to go to Theme Options (Themen-Optionen) and select the proper boundaries you want to display too, just having the theme installed is not enough.

[Freizeitkarte ](https://www.freizeitkarte-osm.de/android/de/index.html)

![Screenshot_20191017-143411_cgeo](https://user-images.githubusercontent.com/12250212/67009286-9f2cb980-f0eb-11e9-9620-e641b438b589.jpg)
![Screenshot_20191017-143426_cgeo](https://user-images.githubusercontent.com/12250212/67009287-9fc55000-f0eb-11e9-9f52-e6f14ca36cbd.jpg)

**Comment by moving-bits** [comment]
Should be resolved by the way mentioned. Otherwise feel free to reopen.
