### ISSUE TITLE
Feature request - Add geocache manually

### ISSUE THREAD

**Issue by Uli001** [cgeo/cgeo#7901]
**Is your feature request related to a problem?**
Für die Lab-Caches (Adventure Caches) gibt es nur noch selten eine GPX-Datei um die Caches in CGeo oder GSAK einzufügen. In GSAK kann man einen Cache kopieren und ansdchließend anpassen. Die Koordinaten richtig zu setzen ist dabei sehr aufwendig. Aktuell lege ich mir in einem beliebigen Cache einen Wegpunkt mit den Koordinaten des Lab-Caches an. Diese kann ich dann in GSAK übertragen. Schöne währe es direkt in CGeo einen neuen Cache anlegen zu können und sowohl die Antwort als auch die Koordinaten gleich abzuspeichern und später zu exportieren.
For the lab caches (Adventure Caches), there is rarely a GPX file to insert the caches in CGeo or GSAK. In GSAK you can copy a cache and adjust it accordingly. To set the coordinates correctly is very expensive. Currently I put in any cache a waypoint with the coordinates of the lab cache. I can then transfer these to GSAK. It would be nice to be able to create a new cache directly in CGeo and to save both the answer and the coordinates and export them later.

**Describe the solution you'd like**
Neuen Cache in CGeo anlegen
GC-Code händisch festlegen
Typ festlegen
Koordinaten über aktuelle position setzen
Bemerkungen
ggf. noch einen Standart log einfügen da diesen GSAK benötigt 

Create new cache in CGeo
Set GC code manually
Set type
Set coordinates above current position
Remarks
If necessary, also insert a standard log because this GSAK is required

Grüße Uli
Greetings Uli

**Comment by SammysHP** [comment]
Duplicate of #132.
