### ISSUE TITLE
F-droid nightly updates hung after Lineage OS update

### ISSUE THREAD

**Issue by ithink314** [cgeo/cgeo#7902]
> **Describe the bug:**

No new nightly versions are seen in f-droid (nightly repo) since 2019.10.14-NB-43d21a1. LineageOS was also updated on 10/14 (and 10/17 and 10/18). 

**To Reproduce:**
1. Install LineageOS, f-droid, and cgeo from nightly repo.
2. Update cgeo ~nightly, Lineage ~weekly.
3. After an update of LineageOS, on 10/14, cgeo version in f-droid stops changing.
4. Disable/enable repo. No help.
5. Uninstall/reinstall f-droid (and add repo). No help.

**Actual behavior/state after performing these steps:**
Stuck on old cgeo version. Note 3 versions shown in f-droid. 2 have same dates, but different "added" dates.

**Expected behavior/state after performing these steps:**
New cgeo versions every day.

**Version of c:geo used:**
See above

**Is the problem reproducible:**
Unsure. And may be an f-droid bug.

**Screenshots:**
See attached
![IMG_20191018_174810](https://user-images.githubusercontent.com/843769/67132961-439d2180-f1fa-11e9-8a6f-323ad1cf8f5d.jpg)

**System information:**
```

--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 9
Android build: lineage_shamu-userdebug 9 PQ3A.190801.002 1a4a1d229b
c:geo version: 2019.10.14-NB-43d21a1
Google Play services: unavailable
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (10.0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (10.0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (10.0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (562.2 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   opencaching.us: Logged in (Login OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

```

**Additional context:**

**Comment by Lineflyer** [comment]
Looking at the CI this seems to be a generic problem with the fdroid node. Its offline since some days.
AFAIK its a virtual node hosted on the CI server itself...but I am not sure.

@mucek4 Can you take a look...see here: https://ci.cgeo.org/computer/fdroid/

**Comment by mucek4** [comment]
Lars, F-Droid executor is not in CI itself. It was hosted by someone else. I don't remember who.

**Comment by rsudev** [comment]
IIRC it was @kumy

**Comment by kumy** [comment]
@rsudev thanks for notify me.

The serveur was rebooted this week, it may be related, let me check.

**Comment by kumy** [comment]
The service fail to connect to jenkins, it loop on error:
```
 [Fatal Error] slave-agent.jnlp?encrypt=true:1:1: Invalid byte 1 of 1-byte UTF-8 sequence.
 Failing to obtain http://ci.cgeo.org/computer/fdroid/slave-agent.jnlp?encrypt=true
 java.io.IOException: http://ci.cgeo.org/computer/fdroid/slave-agent.jnlp?encrypt=true doesn't look like a JNLP file; content type was text/html; charset=iso-8859-1
 #011at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:525)
 #011at hudson.remoting.Launcher.run(Launcher.java:322)
 #011at hudson.remoting.Launcher.main(Launcher.java:283)
 Waiting 10 seconds before retry
```

**Comment by kumy** [comment]
Let's wait be bit for docker hub to build the new images, then I'll redeploy the stack

**Comment by kumy** [comment]
F-Droid Executor is back, but there is an error:
```
11:58:47  I: Updating F-Droid index
11:58:47  Traceback (most recent call last):
11:58:47    File "/usr/bin/fdroid", line 170, in <module>
11:58:47      main()
11:58:47    File "/usr/bin/fdroid", line 140, in main
11:58:47      if system_encoding.lower() not in ('utf-8', 'utf8'):
11:58:47  AttributeError: 'NoneType' object has no attribute 'lower'
```
Error is raised by fdroid itself, need to check what's wrong. Until then, I disable the executor manually.

**Comment by kumy** [comment]
env var `LANG=en_US.UTF-8` is now necessary. reenabling executor

**Comment by kumy** [comment]
`2019.10.19-NB-452dcd4` has been downloaded and indexed.

**Comment by Lineflyer** [comment]
Thanks @kumy

**Comment by ithink314** [comment]
I got 10/19 version. Thanks!

**Comment by syaifudin85** [comment]
join

**Comment by Lineflyer** [comment]
@syaifudin85 
Should be working again, or not?
