### ISSUE TITLE
Direction line always visible

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7908]
Beta feedback for 2019.01.22-RC2 from FB:

Mit einem S10, das unter der Beta von Android 10 läuft, sehe ich auf der Google Karte und der SAT Ansicht die Richtungslinie.
Diese ist bei mir unter den Einstellungen aber deaktiviert.

Translation:
On my S10 running Android 10 beta version, I do see the direction line on Google Map/Sat although it is deactivated in my settings.

**Comment by alan666notb** [comment]
I get this as well, only on Google maps, I'm running Android 9.

**Comment by Lineflyer** [comment]
@moving-bits As this was a fix for a fault in our beta-release it should go to `release` branch. Can you still revert or change that?

**Comment by moving-bits** [comment]
> @moving-bits As this was a fix for a fault in our beta-release it should go to `release` branch. Can you still revert or change that?

@Lineflyer 
A bit messy, as we had already more commits on master, but done.
