### ISSUE TITLE
Delay "not logged in" message on first start

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7909]
Beta feedback 2019.10.22-RC2

Many beta users are confused by the new "not logged in" warning as it may be shown on start of c:geo while it is performing the login.

We should target to only show this message in cases where it is likely, that some kind of malfunction or error occured.

I suggest to delay the warning by x seconds after the not logged in status is detected to avoid unnecessary warnings while logging in is still in progress or during short connection interruptions.

x=30 seconds ?

**Comment by moving-bits** [comment]
Hm, the current implementation works the other way around: The "not logged in" warning is presented as default message directly at startup (without any checking) and cleared as soon as a successful login is detected. Don't know how to delay this initial message...

**Comment by SammysHP** [comment]
But there are three states: logging in, not logged in and logged in.

**Comment by moving-bits** [comment]
The current info message is informative, but quite long and blocky. Besides possibly changing the logic behind the message, maybe we can shorten the text to something like "Not yet logged in. c:geo will only show caches already stored offline."?
