### ISSUE TITLE
Waypoint calculator: ignore (or remove) whitespace

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7910]
Using the waypoint calculator (wpc) a couple of times during my recent vacation I've stumbled upon a few things I think could be improved to ease using the wpc. I'll open separate issues for it to make tracking easier.

First little annoyance happens when copying a formula via copy and paste into the wpc field (mode simple). If there is whitespace (like blanks) in the formula, wpc considers this as invalid formula and you have to delete those characters manually - which can be pretty difficult on a mobile device.

So the feature wish here is that the wpc either ignores whitespace or removes it automatically from the formula.

**Comment by Lineflyer** [comment]
@eddiemuc 
Also something to consider/check for the new WP calc / variables.

**Comment by eddiemuc** [comment]
Example would be good here

**Comment by eddiemuc** [comment]
The new formula parser is designed to ignore whitespaces. There's one particular place where it is NOT ignoring whitespaces - which is concatennation.

For example the following formula is parseable:

`  3 * A + (       B * 8)+ ABA  `
But the following is not (note the spaces inbetween ABA):

`  3 * A + (       B * 8)+ A B A   `

Problem here is if these whitespaces are ignored then parsing of coordinates becomes difficult. For example, consider the following coordinate

`N 48 12 345`

Currently, this would be parsed as `N48°12'345"`. If whitespaces are ignored within concatennation it is parsed as `N4812345°` (which does not make much sense).

Is there any change wanted nevertheless?

**Comment by eddiemuc** [comment]
I would consider this resolved with the new "remove spaces" button:
![image](https://user-images.githubusercontent.com/6909759/148641699-0d9f4c93-8a6d-4197-b540-f1dad2871dcc.png)

Please feel free to reopen if I missed something.
