### ISSUE TITLE
Waypoint calculator: have a single field for latitude and longitude in simple mode

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7913]
Many listings with formulas for final coordinates have latitude and longitude part together, so it would be easier to copy both parts in one move into the waypoint calculator and not having to switch twice between listing and calculator. (This is meant to be in combination with automatically removing whitespace when copying formulas, see my separate feature request.)

**Comment by eddiemuc** [comment]
See #9633

**Comment by fm-sys** [comment]
Additional note: It's nearly impossible to "split" the coords automatically. Therefore we implemented a paste feature some time ago, which does the splitting if it's "easy enough" (not perfect but works in most cases)
