### ISSUE TITLE
c:geo can no longer be "ended" using back from main screen

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7915]
I just updated my Samsung S10 to Android 10 beta.

With current master I am not able to press the "back" key to put c:geo into background from main screen. A procedure I used regularly in the past.

It looks a bit like something happens (screen flickers, background gets grey) but the main screen remains. Other apps on my device dont have this problem.

**Comment by moving-bits** [comment]
Hm, it does work in the emulator (tested while researching the "direction line always visible" bug). Any specific things you needed to use in c:geo to get this behavior, or does it always happen?
Only on Android beta for S10, or do you have a different device with Android 10 final version which shows the same behavior?

**Comment by Lineflyer** [comment]
- Does always happen=reproducible
- At the moment I do not have any other Android 10 device. Its a beta...but c:geo is the only app with this problem on my phone.

**Comment by IiroP** [comment]
Can't reproduce using OnePlus 3 with Android 10 (unofficial LineageOS 17). 

I don't currently have Google Services installed on that device, if that matters.

**Comment by jonas-koeritz** [comment]
Works flawlessly on Android 10 on Pixel 4 XL. Can't reproduce.

**Comment by moving-bits** [comment]
Cannot reproduce on S10 with Android 10 release (no beta). - @Lineflyer can you cross check?

**Comment by Lineflyer** [comment]
Now on Android 10 final with my Samsung S10 and the problem is gone.
Thanks for reminding.
