### ISSUE TITLE
switching "show direction" setting does not repaint the map (GMv2)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7917]
**Describe the bug:**
After toggling the "show direction" setting the map does not get redrawn automatically when using GMv2 (current Mapsforge does work). 

**To Reproduce:**
- select a cache
- open Navigation - Map to display this cache on a map
- toggle the "map settings" - "show direction" setting

**Actual behavior/state after performing these steps:**
On current Mapsforge the map gets redrawn and the direction line drawn or removed according to the now current setting.
On GMv2 the setting's change only gets visible after manually closing and reopening the map. (Or by a Android-system induced redraw of the map.)

**Expected behavior/state after performing these steps:**
Should work with GMv2 the same way as it does with current Mapsforge map.

**Version of c:geo used:**
Today's (2019-10-24) master.

**Is the problem reproducible:**
Yes, but sometimes need to switch a couple of times between on and off state.

**Comment by moving-bits** [comment]
@matej116 
This is probably due to method `repaintRequired()` in `maps/google/v2/GoogleMapView.java` not yet implemented, there's an unresolved `FIXME` comment instead. I've tried, but did not find a way to make it work. Can you have a look at it?

**Comment by fm-sys** [comment]
Cannot reproduce with current master. Seems to be fixed...
