### ISSUE TITLE
Make trail with numbers to follow 

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#7931]
Idea 34:
Preparing a trip with selected and ordered geocaches in c:geo. Consecutive numbers show up in map making a trip / trail easy in the field. Numbers next to or in icon so seeing which cache is next on the prepared trip. Looking forward to it

**Comment by IiroP** [comment]
I think that would be nice feature, but a bit hard to implement since the formatting of those titles varies. Some trails are like _"Trail #n"_ while others are _"Trail n - Name"_ etc.

**Comment by wizard4u** [comment]
![InkedScreenshot_20191104-222728_LI](https://user-images.githubusercontent.com/1834022/68159776-bb857e80-ff52-11e9-9b41-5480b7aaf750.jpg)

Hi, sorry for my poor explanation.
My idea is if it can be arranged to make a list in c:geo with selected caches in a selected order so I can see where the next geocache is during a trip

**Comment by wizard4u** [comment]
showing a consecutive number on map

**Comment by moving-bits** [comment]
could be implemented on top of #6971

**Comment by Lineflyer** [comment]
I am really unsure if the live map icons can/should present even more info cluttering. However it depends on implementation proposals.
Some months ago I thought the same about additional markers, however the implementation of those markes has been done really nice.

**Comment by moving-bits** [comment]
> Preparing a trip with selected and ordered geocaches in c:geo. Consecutive numbers show up in map making a trip / trail easy in the field. Numbers next to or in icon so seeing which cache is next on the prepared trip. Looking forward to it

@wizard4u 
A somewhat different solution is the implementation of individual routes, see #8158, now available in the nightlies. Does this help you for your use case?

**Comment by wizard4u** [comment]
Yes, even better than my thoughts put in my request. I am curious to test it. Thanx
