### ISSUE TITLE
WP not shown on cache map if limit setting exceeds amount of cache WP

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7948]
**Describe the bug:**
The setting of the waypoint limit (Settings - Map) should only affect the live map but not the mapping of a single cache (which should always show all its waypoints). This works on GMv3 but not on (new) OSM.

**To Reproduce:**
1. Use OSM map (offline or online) , new library (not tested on v3)
2. Go to Settings - Map and set waypoint limit to 0
3. Open a saved caches which has several additional waypoints with valid coords
4. Press the map icon in the top bar to show cache+waypoints on map

**Actual behavior/state after performing these steps:**
Only cache icon is shown, but not the additional waypoints

**Expected behavior/state after performing these steps:**
The cache position and all its waypoints should be shown

**Version of c:geo used:**
2019.11.11 and 2019.10.05

**Is the problem reproducible:**
Yes, on OSM.
Its working as expected with Google Maps.

**Comment by moving-bits** [comment]
Additional info: Seems to happen only if you set the waypoint limit to 0. As soon as you set it to a non-zero value it works as expected.
