### ISSUE TITLE
Strategy for handling of user defined caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7952]
Recently @moving-bits implemented "user defined caches" as new feature (see #7918 and #7946). This is a nice feature, especially as replacement for the long time orphaned "Go to" menu. Thanks for that!!

However I think we should discuss some ideas about the implementation details to improve usability.
As base for discussion here are my thoughts after trying the feature in our nightlies (also summarizing some other comments I made for the mentioned PRs):

1. First of all a generic idea: At the moment new user defined caches (from map or "Go to") are stored into the default list. I suggest to use a dedicated new default list for those caches instead (users cann still move/copy afterwards if desired). The reason is mainly the "Go to" cache, which will be automatically created and might confuse the user, when showing up on the default list.

2. Using the waypoint screen of a "user defined" caches as "Go to" screen is really perfect. Our users are used to that UI, so they will most probably be able to understand and use it.
However the "Go to" now also presents all the menus and options, which belong to a cache and this might either be irritating or at least meaningless in that special "Go to" use case. But IMHO the users will get used to that, once they learn about the "user defined cache" feature I guess. Not sure about any optimization possibilities for this special "Go to" case.

3. I guess the "user defined cache" feature is targeting power users/experts, rather than beginners and normal cachers. For this very reason I suggest to discuss again, whether it should be really associated to "long click" on the live map. E.g. it happened to me several times recently, that I accidentally triggered this dialog while clicking or moving the map. 
I could imagine using a setting (in map menu or settings or both (linked)) to optionally turn this behavior on but keeping it off as default. 

4. At the moment other attributes of the cache cannot be assigned (e.g. D/T, size, etc.). Would this be something for future improvement of the feature or not needed?

Additionally some questions to @moving-bits for clarification of the functionality:

- After creating an UDC (nice new abbreviation) from the list menu it has no coordinates. To assign coordinates to it, you have to create a waypoint and set this as listing coords. Is that the intended way or is there any other option I did not see yet. 
While this is perfectly fine as it fits in our normal UI, the only drawback is, that it will always also assign a final marker to the cache.

- How did you implement the geocode assignment? I first guessed you use the next free code in that name space (ZZ*) but also after deleting older UDC the numbers are not reused (or was it only the internal caching after deletion which has tricked me?).

- Shall we keep the prefix with ZZ or any better idea? Are there any reserved prefixes for such use case...is there any regulation for this at all? 

Thanks again @moving-bits for implementing it. This issue shall not trigger you to change it all once again, but just to discuss how to move forward and optimize. :)

**Comment by moving-bits** [comment]
> However I think we should discuss some ideas about the implementation details to improve usability. As base for discussion here are my thoughts after trying the feature in our nightlies (also summarizing some other comments I made for the mentioned PRs):

Very welcomed, thanks for giving your feedback!

> 1. First of all a generic idea: At the moment new user defined caches (from map or "Go to") are stored into the default list. I suggest to use a dedicated new default list for those caches instead (users cann still move/copy afterwards if desired). The reason is mainly the "Go to" cache, which will be automatically created and might confuse the user, when showing up on the default list.

We already have a couple of "virtual lists" - maybe we can create its own reserved list "user defined caches" as default for this.


> 3. I guess the "user defined cache" feature is targeting power users/experts, rather than beginners and normal cachers. For this very reason I suggest to discuss again, whether it should be really associated to "long click" on the live map. E.g. it happened to me several times recently, that I accidentally triggered this dialog while clicking or moving the map.
> I could imagine using a setting (in map menu or settings or both (linked)) to optionally turn this behavior on but keeping it off as default.

Yes, good idea. We would just need to communicate this somehow, to make it known to the power users.


> 4. At the moment other attributes of the cache cannot be assigned (e.g. D/T, size, etc.). Would this be something for future improvement of the feature or not needed?

IMHO we can add those later on a "per need" basis. I wanted to keep the feature set as small as possible for the time being.


> Additionally some questions to @moving-bits for clarification of the functionality:
> 
> * After creating an UDC (nice new abbreviation) from the list menu it has no coordinates. To assign coordinates to it, you have to create a waypoint and set this as listing coords. Is that the intended way or is there any other option I did not see yet.
>       While this is perfectly fine as it fits in our normal UI, the only drawback is, that it will always also assign a final marker to the cache.

Um, need to look up this. I wanted to use the current GPS coordinates as default for this, but I'm unsure whether I've already implemented it that way.


> * How did you implement the geocode assignment? I first guessed you use the next free code in that name space (ZZ*) but also after deleting older UDC the numbers are not reused (or was it only the internal caching after deletion which has tricked me?).

No, I'm storing a sequence for the ZZ namespace, assigning a consecutive number for the new UDC, without reusing any numbers. User created UDC start with 1000. "0" is reserved for the "go to" targets, 1-999 are reserved, but unused for now.


> * Shall we keep the prefix with ZZ or any better idea? Are there any reserved prefixes for such use case...is there any regulation for this at all?

Any two letter abbreviation will do. I chose one I hope no official geocaching connector will ever happen to use. I wanted to use something like "!!" first, but it's limited to "A-Z" only.


> Thanks again @moving-bits for implementing it. This issue shall not trigger you to change it all once again, but just to discuss how to move forward and optimize. :)

No worries, that's what I wanted to start with this MVP.

**Comment by Lineflyer** [comment]
> > 1. First of all a generic idea: At the moment new user defined caches (from map or "Go to") are stored into the default list. I suggest to use a dedicated new default list for those caches instead (users cann still move/copy afterwards if desired). The reason is mainly the "Go to" cache, which will be automatically created and might confuse the user, when showing up on the default list.
> 
> We already have a couple of "virtual lists" - maybe we can create its own reserved list "user defined caches" as default for this.
> 

Good idea, that would be what I would expect.

> > 1. I guess the "user defined cache" feature is targeting power users/experts, rather than beginners and normal cachers. For this very reason I suggest to discuss again, whether it should be really associated to "long click" on the live map. E.g. it happened to me several times recently, that I accidentally triggered this dialog while clicking or moving the map.
> >    I could imagine using a setting (in map menu or settings or both (linked)) to optionally turn this behavior on but keeping it off as default.
> 
> Yes, good idea. We would just need to communicate this somehow, to make it known to the power users.

Changelog and social media channels is what we have. That also worked out for the WP calculator at the time it was new.

> > * After creating an UDC (nice new abbreviation) from the list menu it has no coordinates. To assign coordinates to it, you have to create a waypoint and set this as listing coords. Is that the intended way or is there any other option I did not see yet.
> >   While this is perfectly fine as it fits in our normal UI, the only drawback is, that it will always also assign a final marker to the cache.
> 
> Um, need to look up this. I wanted to use the current GPS coordinates as default for this, but I'm unsure whether I've already implemented it that way.
> 

Don't think its already in, but that would be a good starting point.
For editing them later on, we could use the coordinate input dialog by clicking on the listing coords....but that would not fit all cache sources...mmh. Maybe better as a cache menu item (which is only available for ZZ).

> > * Shall we keep the prefix with ZZ or any better idea? Are there any reserved prefixes for such use case...is there any regulation for this at all?
> 
> Any two letter abbreviation will do. I chose one I hope no official geocaching connector will ever happen to use. I wanted to use something like "!!" first, but it's limited to "A-Z" only.
> 

ZZ seems fine, I have no better idea. I first thought about CG for cgeo but its easy to be mixed up with GC.

**Comment by bekuno** [comment]
I had already wished for this functionality several times.
For example, to make a own birthday round, or on holiday a round of the local tourist information.

I also think that a separate list should be used for such caches.

I searched a bit for rules or a platform to define a cache identificator but found nothing.
So let's use ZZ.

How about contacting "Saarfuchs"?
He wrote already some articles about c:geo (https://www.saarfuchs.com/tag/cgeo)

**Comment by Lineflyer** [comment]
> How about contacting "Saarfuchs"?
> He wrote already some articles about c:geo (https://www.saarfuchs.com/tag/cgeo)

Good idea. I wanted to contact Jörg anyway as he asked several years ago, whether there is a user guide, which was the initial trigger for me to create one. I also had the idea to send him our special contributor gift.

**Comment by Lineflyer** [comment]
@moving-bits 
Regarding the own list for UDC. I have seen your related commit, however what would I suppose to see in the app? I checked todays nightly build but could not see a difference.

**Comment by moving-bits** [comment]
> @moving-bits
> Regarding the own list for UDC. I have seen your related commit, however what would I suppose to see in the app? I checked todays nightly build but could not see a difference.

The difference is that ZZ0 UDC isn't stored to the default list any longer, but to an new virtual list. If you open the default list "stored", ZZ0 is not listed anymore, you can only find this special cache if you open the "All caches" virtual list.

(It's a bit tricky, though, insofar, as the new virtual list is purely virtual and not listed in the list of cache lists - that would have created the need for much more changes (and is not necessary IMHO, as the main goal was to somewhat hide the special ZZ0 UDC).)

**Comment by moving-bits** [comment]
Regarding the old "go to" function and its switch to a dedicated UDC:
Shall we migrate the "go to" history (or part of it) to UDC waypoints, or can we throw them away?

**Comment by moving-bits** [comment]
Closing this issue, as many of the things discussed above are either implemented already or outdated meanwhile.
If there are any new issues about UDC we should open separate issues.
