### ISSUE TITLE
Release info: Contacts plugin

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7954]
Thanks to @bekuo we have a working contacts plugin again which should also fulfill the Google Play requirements. 
I tested this new version and it works for me:
- Tested on Android 9 and 10
- Permission handling working fine
- Contact matching works

Given the fact, that this is no crucial part of c:geo itself and we do not have that many installations via Google Play I will publish it tonight. Lets see if Google Play accepts the PK and if there is any (negative) user feedback.

**Comment by Lineflyer** [comment]
I had to update the play store entry completely also due to other changed requirements to the description. However finally the APK is uploaded and the app republished. It might take a while to show up again on Google Play.

When it is active I will check the installation from Google Play and afterwards also promote it on our channels.

**Comment by bekuno** [comment]
The new strings are not yet uploaded to Crowdin.

**Comment by Lineflyer** [comment]
I know, but as the current process is so slow I did not want to wait for that.
If someone could look into how to automate this or include into CI...would be great.

**Comment by Lineflyer** [comment]
Released and promoted also on FB and Twitter. Thanks again @bekuno
