### ISSUE TITLE
Widget shortcut for GoTo function opens old view

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7959]
To Reproduce:
- Create a c:geo widget shortcut on your homescreen and use the GoTo function
- Click the widget

Result:
- The old view is shown

Expected result:
- The new UDC waypoint view should be shown

BTW:
Why is the old view still available at all?

Version:
2019.11.20-NB-2b05a2b

**Comment by moving-bits** [comment]
Oops, never have seen this way before - I always use "show on start screen" (or so), which opens c:geo directly, without a popup. Have to go to homescreen's widget menu first, add c:geo and only then get the popup. => Will look into it.

> Why is the old view still available at all?

As mentioned in https://github.com/cgeo/cgeo/pull/7946#issue-339607126: Haven't cleaned up the code yet, as we're still in a sort of experimental state here...
