### ISSUE TITLE
Harmonize maps - Add target selector to Google Maps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7969]
New OSM map features an icon on the cache/WP popup to trigger setting this cache/WP as target (showing direct/routed line from position to cache). 

This is missing on Google Maps.

**Comment by MagpieFourtyTwo** [comment]
AFAICS the two icons "Compass rose" and "Route to icon" do the same.
So IMO there are two alternatives:

- If there is a difference between them (although not obvious to me), 2. should be added to GM & GSat, too, ... OR ...
- If they are in fact identical, one of both can safely be omitted,
  and additionally the corresponding menu entry may be removed, too.

**Comment by Lineflyer** [comment]
> AFAICS the two icons "Compass rose" and "Route to icon" do the same.

That depends on what function you choose for the Compass rose. The default is, that short click opens the compass, long click the map.

So IMHO the "route to icon" should be added to keep consistent (its a missing feature on our GMaps implementation).

**Comment by MagpieFourtyTwo** [comment]
Yep, you're right - I'm so used to the map as first navigation tool that I completely forgot the alternatives.  ;)

> IMHO the "route to icon" should be added 

👍

**Comment by moving-bits** [comment]
I'll give it a try. But it's woven deeply into the different map logic...
