### ISSUE TITLE
Default to OSM:Map if Google Map cant be used

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7975]
Follow up of #7875:

If Google Play Services are not available the Google Map does not work (see #7875).
While the corresponding crash has been fixed, we still default to Google Maps also in this case.

This means, if a user installs c:geo and starts the Live Map first time, he will see an error instead of a working map.
While for some users it might be fixable by using the provided install/update button, for others it wont work (e.g. they do not have a Google account on their device to udpate/install Play Services).  For such cases it would be better to give them some kind of hint or redirect them to OSM:Map instead.

**Comment by moving-bits** [comment]
If I understand GMS docs & SO articles as well as our code right, then
- the message to update play service comes from within GMS lib and cannot be influenced by us
- the check for correct min version of play services cannot be done from a static context (which is what we currently use in `MapProviderFactory` which is the base for our map provider selection)

Thus probably the only solution is to start GMv2 map, detect the wrong version of play services by ourself and offer to switch to a different map type. (approach not yet tested)

**Comment by Lineflyer** [comment]
Well I opened this with low priortiy anyway as I think there are not so many users out there with such problem. At least no such mail on support.
So don't invest to much time into it.
