### ISSUE TITLE
Delete stale branches / branches no longer used

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7976]
Looking at the branches list of c:geo there are a couple of branches I think we no longer need any more. Before deleting them I want to make sure I don't delete anything that's still in use :-)

![image](https://user-images.githubusercontent.com/3754370/69889444-4870ed00-12f1-11ea-95c0-41e68b641d9a.png)

To my understanding the following branches could be deleted safely:
- `GoogleMapsV2` -> is merged; further development on master branch only
- `issue_7289_spinner` -> has been merged as separate PR to master as part of targetSDK26 work
- `revert-7639-issue_7289_spinner` -> is marked as merged
- `contacts_sdk27` -> contacts app is back to Play Store
- `fix_5900` - is marked as merged

I'm unsure about `old-cgeo-legacy`.

If no one objects I will delete the first five branches next week.
What about the last one?

**Comment by bekuno** [comment]
For the leacy - see https://github.com/cgeo/cgeo/issues/7836#issuecomment-559604005
do not delete

**Comment by Lineflyer** [comment]
old-cgeo-legacy can be deleted too. Thats was a fallback backup no longer needed.

Also cgeo-legacy is stale, but might be reused at some point in future. It should be kept.

**Comment by SammysHP** [comment]
We can tag such branches like cgeo-legacy and create the branch later if necessary.

**Comment by moving-bits** [comment]
Branches deleted.
