### ISSUE TITLE
Strange Google satellite view

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7984]
From support mail:

Looking at the vincinity of GC6VXW6 using Google Satellite view you can see some kind of strange mixture of sat view and normal map view. This seems to be triggered by the selectable floor plan somehow.

However I was not able to see the same kind of view when using the Google Maps app. Is this a bug or a feature?

c:geo:
![Screenshot_20191201-165225](https://user-images.githubusercontent.com/949669/69919763-c1eb1580-1480-11ea-9f1c-7c282680cbfb.jpg)

Google Maps:
![Screenshot_20191201-212642_Maps](https://user-images.githubusercontent.com/949669/69919832-68371b00-1481-11ea-9238-b55c58c07dcb.jpg)

**Comment by moving-bits** [comment]
In the doc about API v3 I linked recently (https://developers.google.com/maps/documentation/android-sdk/v3-client-migration) there is one new feature which might explain this:
> Business POIs are now visible in indoor maps.

As API v3 is mainly about being a separate library, maybe this has found its way into current version of the GM lib as well.

**Comment by Lomanic** [comment]
I can confirm this, I think it can be disabled with https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#setIndoorEnabled(boolean)

**Comment by moving-bits** [comment]
Question is: what do we prefer?

**Comment by jonas-koeritz** [comment]
> Question is: what do we prefer?

I would prefer to set indoor to enabled on the Map type view and to disabled on all sattellite type views.
