### ISSUE TITLE
Google Maps v2: disable screen rotation

### ISSUE THREAD

**Issue by Lomanic** [cgeo/cgeo#7986]
**Is your feature request related to a problem?**
This is quite the opposite of  #7507 (linked to that issue at least): I find this an anti-feature, while zooming in or out with two fingers, to have the map rotated quite frequently because my fingers were not moving exactly the right way to have the map not rotated. This of course not only occurs with cgeo and its new Google Maps v2, but with many other applications (original Google Maps, Citymapper for example), and I always have to put the map back to north-oriented afterwards (by clicking the compass in the upper left corner for cgeo).

Also, and this is similar to #7953, when you switch from rotated Google Maps to OSM: Map (online), the orientation is then set to north as it can't (currently?) be rotated. Switching back to Google Maps, the map is then pointing north.

**Describe the solution you'd like**
I would like map rotation to be disabled ([simple to achieve according to this SO answer](https://stackoverflow.com/a/13700449)) to keep the same user interactions as before the migration to Google Maps v2, or at least to have a setting to disable or enable this feature.

**Describe alternatives you've considered**
Toggle switch to enable this feature.

**Comment by Lineflyer** [comment]
I think its somehow related to #7507. Once such function is there, you would implicitly need a way to turn it off.
