### ISSUE TITLE
Different dir chooser dialogs in use

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7988]
We have several menus where a dir chooser is used to let the user configure directories:
- GPX Import/Export directories
- Offline map directory
- Offline theme directory

Depending on installed third-party apps/plugins an external chooser might be used or we use our own dir chooser implementation. This is fine so far, however although a third-party chooser is available we still don't use it everywhere:

- GPX-Import/Export -> Internal chooser is used
- Offline map directory -> External chooser is used
- Theme directory -> Internal chooser is used

At least this is the experience on my device (Samsung S10, Android 10, Locus installed (which most probably provides this external plugin, which we use).

As our internal chooser is not really nice looking and easy to use, we should prefer the external one throughout IMHO.

See also #2257 for history.

**Comment by moving-bits** [comment]
No longer relevant after our switch to SAF.
