### ISSUE TITLE
Visualize "cache health" when saved offline

### ISSUE THREAD

**Issue by jonnyrobbie** [cgeo/cgeo#7989]
It hapens more often than it is comfortable that I download cacehs for offline use and then when I go out for the hunt I can't find them, only for me to check the few latest logs, which show red did not find logs of previous users.

I could check the last logs of evely last one cache I've saved for offline use, which is unconfortable brute force solution. Better solution would be to have C:GEO change color of the floppy disk icon based on the ratio of Found/DNF over last few logs. For example, it would look at last five logs and color the icon green if all were found, lime if one logged DNF, through yellow, orange and to red when all the latest five logs were DNF.

That way one could see at glance if the cache is worth pursuing even when the owner did not have a chance to disable the cache yet.

**Comment by jonas-koeritz** [comment]
There needs to be a (maybe user controlled) threshold for cache health then. Sometimes high difficulty caches have lots of consecutive DNF logs too, I would not call them unhealthy but really challenging.

Maybe an indication of the last log would be a more general solution? Showing the last log type could at least give you a hint which caches to look at in your use case.

**Comment by bekuno** [comment]
But what about a e.g. 6 month old saved cache? The data _may_ be outdated, nobody knows.
Or this can also be a problem already after 2 days. Schould this extra color go to transparent in any steps, or ...?

**Comment by jonnyrobbie** [comment]
@jonas-koeritz 

> Sometimes high difficulty caches have lots of consecutive DNF logs too, I would not call them unhealthy but really challenging.

That's true. I guess the solution would be to not call this feature "cache health" as the cache could be healthy, but call it something like "cache discoverability". Ok, that is a pretty cumbersome name, I admit - it is a subject to change, but the spirit of feature is still there.
I might agree with the threshold thing too. I just said 'five' because that's the number I thought might work by default for me, but for sure, this could be user selectable.

@bekuno 

> But what about a e.g. 6 month old saved cache?

I think this is quite irrelevant. If your cache save is old, then it is outdated with or without this proposed feature. This doesn't change anything.

**Comment by SammysHP** [comment]
Somewhere we have an issue about showing the type of the last five found/DNF logs as a summary (or icon). This is also done by OpenCaching.

**Comment by fm-sys** [comment]
With #11676, the latest offline logs will be displayed as icons in cache details and map popup. Let's close here...
