### ISSUE TITLE
"Caches hidden" fails to load with customized "cache owner" name

### ISSUE THREAD

**Issue by john-magnus** [cgeo/cgeo#7998]
**Describe the bug:**
When viewing cache details, selecting "Caches hidden" from the CO name menu, fails to load when CO have specified a custom username for the currently displayed cache.

While I'm not sure, it seem as though "Caches hidden" tries to load the caches of a user with the username displayed for av given a cache. The displayed **name** for a CO, isn't necessarily the same as the username associated with a cache. The CO name is a free form name, on a cache by cache basis. All caches are still associated with a specific account/user, this should be used to load the caches hidden.

**To Reproduce:**
1. Open cache details for a cache with customized CO name
2. Click cache owner and select "Caches hidden"

**Actual behavior/state after performing these steps:**
c:geo tries to load caches hidden by a user with the displayed name. 

**Expected behavior/state after performing these steps:**
Caches hidden by the proper CO should be loaded.

**Version of c:geo used:**
2019.11.28

**Is the problem reproducible:**
Yes

**Additional context:**
This bug was introduced some time back, maybe a couple of months.

**Comment by Lineflyer** [comment]
Can you please provide a specific example to test this?

**Comment by john-magnus** [comment]
Take one of our caches; GC3HJ8Q. Here the displayed cache owner name is displayed as "Cecilie & John Magnus". This is not my real username, witch instead is "john.magnus". 

When selecting "Caches hidden", c:geo (at least visually) tries to load caches from a with the displayed name and thus fails to load any more caches.

**Comment by Lomanic** [comment]
Maybe it's linked to #7818 and #7125, but I'm not sure if it was not broken this way before.

**Comment by bekuno** [comment]
Maybe its a side effect of the first one, will check it later.
The second was only OC relevant.

**Comment by rsudev** [comment]
It once was working, so it is a regression and the candidate issue seems a likely culprit

**Comment by bekuno** [comment]
The problem is a result of the fix for #7125.
We have to find a way to distiguish between OC and GC.
On OC we have user numbers and user names and on GC user names and user text.
But they are both linked to userName and displayName.

**Comment by MagpieFourtyTwo** [comment]
Was a little bit astonished as the functions "Open Profile in Browser" and "Send Message" even work with customized Cache Owner Names ... what about porting the way these two work to the functions "Open Contact", "Hidden Caches" and "Found Caches" (which all do not switch from Displayed to Real Owner Name before starting their search) ...?

**Comment by Lineflyer** [comment]
I am quite sure, that this is a regression from a fix some time ago, where we fixed the unability to use the owner name on OC.

**Comment by moving-bits** [comment]
@bekuno 
Do you have time to look into it? AFAICS you've been the last person working on that part of the code.

**Comment by bekuno** [comment]
The parameters user.userName and user.displayName are used in different (opposite) ways for GC and OC caches. Therefore I see 2 possibilities:
- define a third parameter e.g. user.realName when parsing the source data. Then we can use this parameter for the user search
- check the data source (GC/OC/...) before the search and use then the correct source from userName/displayName for the search

My favorite is the first variant. 
I do not have much free time for c:geo programming at the moment. :-(

**Comment by Lineflyer** [comment]
Friendly reminder for this regression.
If there is no time to fix / to complicated to fix, I suggest to revert the change which lead to this regression. (This way it would work again on GC but fail on OC. Not nice, but GC is used way more often).

**Comment by bekuno** [comment]
I will prepare a PR to at least revert the change.
