### ISSUE TITLE
 GitHub will discontinue password authentication to the API

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8004]
From GitHub https://developer.github.com/v3/auth/#via-username-and-password:
> Deprecation Notice: GitHub will discontinue password authentication to the API. You must now authenticate to the GitHub API with an API token, such as an OAuth access token, GitHub App installation access token, or personal access token, depending on what you need to do with the token. For more information, see the blog post.

And from personal mail:
> You recently used a password to access an endpoint through the GitHub API using git-credential-manager. We will deprecate basic authentication using password to this endpoint soon:
https://api.github.com/user/subscriptions
We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

At least the crowdin scripts are using this method.

**Comment by Lineflyer** [comment]
@bekuno 
The new Crowdin integration as well as connection towards our CI and Crowdin was done using a PAT of the user `cgeo-ci-bot`.  You this should be solved, or is there anything still using password-auth?

**Comment by bekuno** [comment]
Are your sure to configured password authentication?
Or did you configured the token authentification, which should be the standard?

**Comment by Lineflyer** [comment]
Exactly: Using personal access token (PAT) of `cgeo-ci-bot` now.
