### ISSUE TITLE
Live map cache count can get wrong

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8009]
Just noticed on current master, but not yet reproduced.

My scenario:
- Map a list of 1000 caches (originally to test the fixed ANR problem)
- Scroll to somewhere where no cache of this list is on the map
- Activate live
- Live caches are loaded and appear on map
- Scroll around a bit to trigger new caches to be loaded

- Suddenly the cache count on the title shows an obvious wrong amount of caches 
- In my case approx. 20 caches are shown on map, but the title shows 4 caches
- If I open "Show as list" only 4 caches are shown in this list

- After some scrolling the count reaches 0 and stays there independently of the amount of caches shown on the map

Others:
- Using mapsforge offline
- 2019.12.16-NB

**Comment by jonas-koeritz** [comment]
I did also observe this. I would like to question the subtitle of the activity in general, to me it was never clear what the two numbers meant until I had a look at the code, and I still find myself counting caches manually to get an idea of what the numbers might be representing at the moment.
Maybe the UX could be improved on.

**Comment by Lineflyer** [comment]
Looking through issue least recently updated with label "Unverified":

I tried according to the steps above but could no longer reproduce.
Closing now. Feel free to reopen if such thing occurs again.
