### ISSUE TITLE
Support new locationless cache type

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8010]
https://coord.info/GC8FR0G

Remark:
At this moment the cache is locked, which is visualized as archived in c:geo (intentional).

**Comment by moving-bits** [comment]
I'd already started a PR for that, but where do I get the guid and wptTypeId from?

**Comment by bekuno** [comment]
I took such info from the cache website.
Here it is:
guid=bba552b0-484e-4e4d-b1c3-27857d86a22c&amp;WptTypeID=12

Also see https://www.geocaching.com/about/cache_types.aspx for the cache type description.

**Comment by SammysHP** [comment]
This will be the only cache of this type.

https://www.geocaching.com/blog/2019/12/find-signal-the-frog-in-2020/

**Comment by moving-bits** [comment]
> I took such info from the cache website.
> Here it is:
> guid=bba552b0-484e-4e4d-b1c3-27857d86a22c&WptTypeID=12

@bekuno  Thanks for pointing me into the right direction. At first guid did not work as expected for me (= not detecting GC8FR0G as "Locationless (Reverse) Cache", but then I discovered the line `"/seek/nearest.aspx?tx=8f6dd7bc-ff39-4997-bd2e-225a0d2adf9d` as link to nearby caches of the same type. Using this guid the new cache type gets detected as expected now.
