### ISSUE TITLE
Support trails

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8020]
We have a couple of feature requests regarding something like "trails" in the meaning of "an ordered list of waypoints / caches which someone wants to do something with (eg: following the trail one by one, measure distance etc.).

I therefore propose to implement trails in c:geo:

A trail is an ordered list of waypoints and/or caches.
- This list is displayed in a similar way as cache lists are today.
- Reordering the waypoints works by drag & drop.
- The "show on map" button works in a similar way as with lists.
- Optional features when displaying a trail on the map:
  - The points can have little numbers at their side, starting with 1 and being consecutive.
  - The points can be connected by a line and (if brouter is installed) the calculated route distance is shown.
  - Points of a trail can be marked as visited. Routing starts from the first unvisited point and only includes unvisited points.
- Adding waypoints or caches to a trail can be done by either long pressing on a waypoint/cache in map display or by a menu point in cache list view. If no trail exists yet, c:geo asks for the trail's name, otherwise a list of existing trails is shown (+ option to create a new one) => similar to list management.

This would integrate / implement the following feature requests:
- #7931 Make trail with numbers to follow
- #6971 Create ordered list
- #7914 measure distance / calculate route between two arbitrary points on map

It could also be a base for implementing #2469 "Support visualisation of tracks on map (GPX-format)" (using a user defined cache per track imported).

I'm undecided yet whether a trail is something new (but very similar to the lists we already have), or if we can implement it by a small extension to the existing lists (which I would prefer).

**Comment by Lineflyer** [comment]
It is somehow interesting, but again tending to have potential to overcrowd menus and maps. We need a good strategy of implementing such a feature (i.e. good to use, but not interfering with users who do not want to use it).
I have to think about it and will post another feedback next days.

**Comment by moving-bits** [comment]
> We need a good strategy of implementing such a feature (i.e. good to use, but not interfering with users who do not want to use it).

Agreed. That's one of the reasons why I would prefer to implement it reusing/extending lists and not as a separate "trail" feature, if technically possible.

We also need to think about what should be configurable (and what not), and whether a configurable item should be shown in a local menu or in the global settings.

**Comment by moving-bits** [comment]
I did a first (and partial) implementation for NewMap:
- add/remove caches/waypoints by long tapping on its icon
- route gets drawn with a blue line (to distinguish it from already existing routing)
- route distance is shown top right, below the currently shown distances
- routing calculation is done for involved segments only, and only when adding/removing a geoitem

![image](https://user-images.githubusercontent.com/3754370/76682010-9556a600-65f8-11ea-8fe6-a67380cdacd2.png)

Works with either waypoints of a single cache as with several caches or mixed geoitems.

This is WIP - NewMap only, no reordering of items, and no persistence so far. See branch "routes" in my fork.

**Comment by moving-bits** [comment]
I've created PR #8158 for a basic implementation. Added to the functionality described in my last post here (https://github.com/cgeo/cgeo/issues/8020#issuecomment-599053385) is persistence for a single route with automatic storing and loading, and implementation for Google Maps v2. For implementation details see https://github.com/cgeo/cgeo/pull/8158#issue-395153263.

**Comment by dcjkfgdjhd** [comment]
More important than routing would be the possibility to display a track from a GPX file.

I already do import GPX files from Basecamp into c:geo. These contain both a track and caches. Unfortunately, c:geo ignores the contained track. It would be immensely helpful if the track would appear as an item in the "saved caches list" together with the caches and would get drawn on the map whenever you show a cache list on the map.

This should be easy to implement, as c:geo already draws routes from BRouter etc. on the map, so drawing an arbitrary GPX track should be an easy modification of that.

**Comment by Lineflyer** [comment]
> More important than routing would be the possibility to display a track from a GPX file.

See #2769.
I would meanwhile also love to see this feature, as I started doing a lot of hikes and bike tours with given tracks.

**Comment by moving-bits** [comment]
Proposal for a basic implementation for loading / displaying / removing a track:

- Add a new menu item "load track" which opens a file choser to load a gpx file.
- If that file contains a track it will be displayed.
- An existing track can be removed from display by either choosing a new track or via menu item "Hide -> track".
- (c:geo itself stores only the last track's filename and its display status, nothing else.)

Would this be sufficient?

**Comment by moving-bits** [comment]
And: Can someone provide me with a few test files for tracks?

**Comment by dcjkfgdjhd** [comment]
I think there is no need for a new track import menu item. We already have a GPX import menu item. 

If that GPX contains caches, the caches are added to the cache list. The same happens already in the current version with non-cache waypoints in the GPX. And I propose that the same should in a new version also happen to tracks contained in the list.

Yes, I suppose it would be nice if you could select a track in the cache list and choose "hide track". Not essential for me personally, but certainly nice.

**Comment by dcjkfgdjhd** [comment]
I'd be happy to provide "real world" GPX files containing tracks and geocaches. Source: Garmin Basecamp.

Do you have an email address, so we can take this off this forum?

**Comment by UniQP** [comment]
[Track](http://www.spbgh.de/caches/GC8NWHX/GC8NWHX-Track.gpx) for [GC8NWHX](https://coords.info/GC8NWHX)

**Comment by Lineflyer** [comment]
> I think there is no need for a new track import menu item. We already have a GPX import menu item.

Might really be a good idea to reuse it on one hand. But on the other hand the internal flow for importing caches and visualizing a track is different. You would need a menu to remove the track anyway.

And how to handle GPX which contain caches AND a tracks or contains several tracks.

**Comment by moving-bits** [comment]
> I think there is no need for a new track import menu item. We already have a GPX import menu item.
> 
> If that GPX contains caches, the caches are added to the cache list. The same happens already in the current version with non-cache waypoints in the GPX. And I propose that the same should in a new version also happen to tracks contained in the list.

Our cache list can only hold caches - internally it's just a set of cache geocodes. I'm trying to avoid having to implement all the management functions required to select / store / manage lists of tracks, therefore I proposed a more minimalistic approach of reading / displaying a single track.

> Yes, I suppose it would be nice if you could select a track in the cache list and choose "hide track". Not essential for me personally, but certainly nice.

The "hide track" function therefore would not be in cache list menu but in map menu.

**Comment by moving-bits** [comment]
> I'd be happy to provide "real world" GPX files containing tracks and geocaches. Source: Garmin Basecamp.
> 
> Do you have an email address, so we can take this off this forum?

Thanks. You can reach me by "github@" (Accountname) ".net".

**Comment by dcjkfgdjhd** [comment]
> And how to handle GPX which contain caches AND a tracks or contains several tracks.

Well they should ALL get imported into the same cache list.

**Comment by dcjkfgdjhd** [comment]
> 
> 
> > I think there is no need for a new track import menu item. We already have a GPX import menu item.
> > If that GPX contains caches, the caches are added to the cache list. The same happens already in the current version with non-cache waypoints in the GPX. And I propose that the same should in a new version also happen to tracks contained in the list.
> 
> Our cache list can only hold caches - internally it's just a set of cache geocodes. I'm trying to avoid having to implement all the management functions required to select / store / manage lists of tracks, therefore I proposed a more minimalistic approach of reading / displaying a single track.
> 
> > Yes, I suppose it would be nice if you could select a track in the cache list and choose "hide track". Not essential for me personally, but certainly nice.
> 
> The "hide track" function therefore would not be in cache list menu but in map menu.

If it is easier to implement that way, sure, no problem.

**Comment by dcjkfgdjhd** [comment]
> 
> 
> > I'd be happy to provide "real world" GPX files containing tracks and geocaches. Source: Garmin Basecamp.
> > Do you have an email address, so we can take this off this forum?
> 
> Thanks. You can reach me by "github@" (Accountname) ".net".

SENT.

**Comment by Lineflyer** [comment]
> 
> Our cache list can only hold caches - internally it's just a set of cache geocodes. I'm trying to avoid having to implement all the management functions required to select / store / manage lists of tracks, therefore I proposed a more minimalistic approach of reading / displaying a single track.

That should do the job.

**Comment by moving-bits** [comment]
I started working on track loading and display. For current state and further discussion refer to #2469.

**Comment by Lineflyer** [comment]
This is all done isn't it @moving-bits ?

**Comment by moving-bits** [comment]
> This is all done isn't it @moving-bits ?

Not for all aspects in the way originally described and intended, but as far as it will go for now. So I'm fine to close this issue.
