### ISSUE TITLE
Rotating map not rotating as expected

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8021]
Recently @moving-bits implemented the rotation for GMapsV2 (see #7507).

Up to now I only had very limited time to test this feature, however I have instantly seen something unusual (at least on my Samsung S10, not yet tested with any other device):

As the map shall rotate according to the device compass orientation I would have expected, that the position arrow on the map (which in fact shows my device orientation related to the map) is now always pointing upwards on the display.  This would be logical as the map is now rotated acc. to my orientation upwards.
However on my device there is a delta between map orientation and pointer orientation most of the time. I cannot yet say what exactly is happening here, however for me it looks like the position arrow rotation is more accurate than the map rotation.

Looking forwards for other testers and feedbacks.

**Comment by moving-bits** [comment]
There is a difference between the angle the map is displayed at (orientation) and the blue triangle's direction (heading). Seems they are out of sync - with a rotating map the blue triangle should point to the top of your device (or at least close to it). => Will look into it.
