### ISSUE TITLE
Better UI for rotating maps feature

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8022]
If I compare the new c:geo rotating map with the equivalent Google Maps feature, I think we should have possibility to directly turn on/off manual and/or auto rotation directly in the map view (and not even in a sub menu below).
I can imagine many situations where users would probably like to turn it on/off frequently as the compass is likely to get uncalibrated or simply wrong under certain circumstances.
My usecase would e.g. be to only turn the feature on for some seconds to get better orientation and then switch it off again until after the next crossing or cache stop.

Looking at Google Maps I have a maybe stupid question:
On Google Maps users can interact with several on-screen buttons (i.e. click on compass rose to disable/rest manual rotation, double click on "center on position" icon to turn on/off auto rotation). Aren't these buttons part of the GMapsV2 library?

**Comment by moving-bits** [comment]
@Lineflyer  Thanks for your feedback.

> If I compare the new c:geo rotating map with the equivalent Google Maps feature, I think we should have possibility to directly turn on/off manual and/or auto rotation directly in the map view (and not even in a sub menu below).
> I can imagine many situations where users would probably like to turn it on/off frequently as the compass is likely to get uncalibrated or simply wrong under certain circumstances.

Hm, I'm unsure about how frequently this would be used. So far I did not want to reserve extra map space for it, but let's wait for more feedback coming in.

> My usecase would e.g. be to only turn the feature on for some seconds to get better orientation and then switch it off again until after the next crossing or cache stop.

Why not always leave it on? (Ok: use case may be a compass going havoc. - But this normally only happens directly after switching GPS on and standing still. As soon as you start moving, map normally stabilizes soon. Additionally a 15° minimum change barrier is already built-in to avoid the map always rotate.)

> Looking at Google Maps I have a maybe stupid question:
> On Google Maps users can interact with several on-screen buttons (i.e. click on compass rose to disable/rest manual rotation, double click on "center on position" icon to turn on/off auto rotation). Aren't these buttons part of the GMapsV2 library?

Currently I know of the following interactions already available:
- tap on compass rose (only gets displayed if map is not north-orientated): switch between north-orientation and actual orientation
- double tap on any empty space of the map: zoom in to this position

**Comment by moving-bits** [comment]
Re-reading my own words, the solution to your use case is already implemented:

While using map rotation, GMv2 automatically adds a small compass rose at the upper left as soon as the map orientation isn't north orientated any longer. By tapping on this rose you can easily switch between north orientation and actual orientation, without having to change the general c:geo setting.

And if a user doesn't like map rotation at all, he/she can disable it completely via the c:geo setting.
