### ISSUE TITLE
Fix remaining lint issues and define baseline

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8029]
Due to several PR we recently brought the number of lint issues from about 300 down to app. 130. Now the somewhat trickier issues remain :-)

At least for some issue classes I'm unsure how to tackle them, therefore I open this issue with the (in terms of number) most relevant issues to discuss possible solutions. The following issues are listed in no particular order:

1) lint message: "Possible overdraw: Root element paints background `?background_color` with a theme that also paints a background (inferred theme is `@style/cgeo`)"
- source: several layout files
- code sample: `<LinearLayout ... android:background="?background_color" ...> ... </LinearLayout>`
- lint explanation: "If you set a background drawable on a root view, then you should use a custom theme where the theme background is null. Otherwise, the theme background will be painted first, only to have your custom background completely cover it; this is called "overdraw". NOTE: This detector relies on figuring out which layouts are associated with which activities based on scanning the Java code, and it's currently doing that using an inexact pattern matching algorithm. Therefore, it can incorrectly conclude which activity the layout is associated with and then wrongly complain that a background-theme is hidden. If you want your custom background on multiple pages, then you should consider making a custom theme with your custom background and just using that theme instead of a root element background. Of course it's possible that your custom drawable is translucent and you want it to be mixed with the background. However, you will get better performance if you pre-mix the background with your drawable and use that resulting image or color as a custom theme background instead."

---

2) lint message: "The resource `@attr/dropdownListPreferredItemHeight` is marked as private in androidx.appcompat:appcompat"
- source: several layout files
- code sample: `android:layout_height="?attr/dropdownListPreferredItemHeight"`
- lint explanation: "Private resources should not be referenced; the may not be present everywhere, and even where they are they may disappear without notice. To fix this, copy the resource into your own project instead."

---

3) lint message: "`@id/distance` can overlap `@id/heading` if @null, @null grow due to localized text expansion"
- source: several layout files
- lint explanation: "If relative layout has text or button items aligned to left and right sides they can overlap each other due to localized text expansion unless they have mutual constraints like `toEndOf`/`toStartOf`."

---

~4) lint message: "Do not concatenate text displayed with `setText`. Use resource string with placeholders."~
- ~source: many occurrences, but probably easy to fix (for most of them)~
- ~lint explanation: "When calling `TextView#setText` * Never call `Number#toString()` to format numbers; it will not handle fraction separators and locale-specific digits properly. Consider using `String#format` with proper format specifications (`%d` or `%f`) instead. * Do not pass a string literal (e.g. "Hello") to display text. Hardcoded text can not be properly translated to other languages. Consider using Android resource strings instead. * Do not build messages by concatenating text chunks. Such messages can not be properly translated."~
- ~code sample: `offlineHintText.setText((hintGiven ? hint + (personalNoteGiven ? "\r\n" : "") : "") + (personalNoteGiven ? personalNote : ""));`~

done with #8065

---

5) lint message: "This `AsyncTask` class should be static or leaks might occur (anonymous android.os.AsyncTask)"
- lint explanation: "A static field will leak contexts. Non-static inner classes have an implicit reference to their outer class. If that outer class is for example a `Fragment` or `Activity`, then this reference means that the long-running handler/loader/task will hold a reference to the activity which prevents it from getting garbage collected. Similarly, direct field references to activities and fragments from these longer running instances can cause leaks. ViewModel classes should never point to Views or non-application Contexts."
- code sample: `new AsyncTask<Void, Void, Boolean>() { ... }`

---

6) lint message: "Overriding method should call `super.onCreate`"
- lint explanation: "Some methods, such as `View#onDetachedFromWindow`, require that you also call the super implementation as part of your method."
- code sample: `public void onCreate(final Bundle savedInstanceState) { onCreate(savedInstanceState, R.layout.compass_activity); ... } `
- specific problem: I tried to fix some of those occurences by calling `super.onCreate(savedInstanceState);` followed by `setContentView(R.layout.compass_activity);` but this crashes :-(
- other case (with GoogleMapActivity and MapsforgeMapActivity): it's calling `basemap.onXXX()` instead of `super.onXXX()`

---

7) lint messages: "Custom view ``Button`` has `setOnTouchListener` called on it but does not override `performClick`" - and: "Custom view `MapsforgeMapView` overrides `onTouchEvent` but not `performClick`"
- lint explanation: "If a `View` that overrides `onTouchEvent` or uses an `OnTouchListener` does not also implement `performClick` and call it when clicks are detected, the `View` may not handle accessibility actions properly. Logic handling the click actions should ideally be placed in `View#performClick` as some accessibility services invoke `performClick` when a click action should occur."
- code sample 1: `startButton.setOnTouchListener(null);`
- code sample 2: `public boolean onTouchEvent(final MotionEvent ev) { ... }`

---

8) lint message: "Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with `checkPermission`) or explicitly handle a potential `SecurityException`"
- lint explanation: "This check scans through your code and libraries and looks at the APIs being used, and checks this against the set of permissions required to access those APIs. If the code using those APIs is called at runtime, then the program will crash. Furthermore, for permissions that are revocable (with targetSdkVersion 23), client code must also be prepared to handle the calls throwing an exception if the user rejects the request for permission at runtime."
- code sample: `geoManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0, 0, gpsListener);`
- sources: GeoDataProvider and GnssStatusProvider

---

9) lint message: "Do not place Android context classes in static fields; this is a memory leak"
- lint explanation: "A static field will leak contexts. Non-static inner classes have an implicit reference to their outer class. If that outer class is for example a `Fragment` or `Activity`, then this reference means that the long-running handler/loader/task will hold a reference to the activity which prevents it from getting garbage collected. Similarly, direct field references to activities and fragments from these longer running instances can cause leaks. ViewModel classes should never point to Views or non-application Contexts."
- code sample: `private static Activity startingActivity;`
- source: speech/SpeechService

---

10) lint message: "This field leaks a context object"
- lint explanation: "A static field will leak contexts. Non-static inner classes have an implicit reference to their outer class. If that outer class is for example a `Fragment` or `Activity`, then this reference means that the long-running handler/loader/task will hold a reference to the activity which prevents it from getting garbage collected. Similarly, direct field references to activities and fragments from these longer running instances can cause leaks. ViewModel classes should never point to Views or non-application Contexts."
- code sample: `@Nullable protected final Activity activity;`
- source: utils/AbstractAsyncTaskWithProgress

---

If you know how to fix those please prepare a PR for that or leave a comment explaining how to resolve the issue. Thanks 👍

**Comment by Lineflyer** [comment]
Just a small amateur comment:
Are we sure, that these issues are all valid? Is the lint checker we use up to date and matching our environment? From the past I know, that we once fixed a code issue not taking into account that our minSDK also includes Android versions, where certain more sophisticated methods are not yet available, still some code checks suggested them.

Just a side note, no idea whether one of these issue might have relation to it.
Anyway: Thanks to  for tackling those issues, which I guess might implicitly solve a lot of problems we have.

**Comment by moving-bits** [comment]
> Are we sure, that these issues are all valid? 

I'm (pretty) sure that NOT all issues are valid - but for the invalid ones I would like to suppress the lint message. It's easier for us to detect new problems if we're down to a handful of lint messages than if we have a few hundreds, so my goal is to fix (or suppress, if appropriate) as many of them as possible with reasonable effort.

> Is the lint checker we use up to date and matching our environment?

No idea :-(

> From the past I know, that we once fixed a code issue not taking into account that our minSDK also includes Android versions, where certain more sophisticated methods are not yet available, still some code checks suggested them.

That could happen, but should lead to warnings / errors from the compiler.

**Comment by Lineflyer** [comment]
In #10155 we recently discussed about configuration and severity of lint checks. This reminded me on this issue.

If my investigation is correct we can avoid false positives by carefully adding exceptions to `main/lint.xml`. This has already been done in the past as you can see in the file.
At the same time we could probably also set other severities (e.g. promote a warning to an error) if we want to avoid missing a new issue introduced with a PR/commit. I am however not sure if severity=error will also make the whole build marked as Failed on our CI but I assume so.

**Comment by Lineflyer** [comment]
Taken from https://github.com/cgeo/cgeo/pull/10161#issuecomment-798888478 by @eddiemuc 

Hi @Lineflyer I am looking into the same thing right now. Problem is that we currently have about 80 Lint errors in code which would immediately lead to failing build if we apply this.

Lint however provides the option to give it a so-called "baseline" file which lists errors (or warnings) Lint should ignore for now. Providing such a baseline file together with turning on abortOnError 8as you did) should imho give us the wanted result.

I would prepare an own PR for this, if that's ok? (Sharing PRs usually involved git-magic which I am not so comfortable with...)

**Comment by eddiemuc** [comment]
PR #10162 (if merged) would let the build fail if there are Lint errors found (Lint Warnings will NOT fail the build).
Since current master contains 84 Lint errors, in order to let the build pass, a "lint-baseline" was added to ignore exactly those 84 errors. Any new error will fail the build

**Comment by Lineflyer** [comment]
Thanks @eddiemuc for working on this topic. Having a proper warning for newly introduced errors is important and will make the usage of lint more meaningful.
Idea: Maybe you should document in our Wiki how this was set up and how to adapt the baseline in case of need (e.g. if we fix some existing errors in future)?

**Comment by eddiemuc** [comment]
@Lineflyer I added documentation for Lint (and also for checkstype and codacy/jenkins quality checks) to https://github.com/cgeo/cgeo/wiki/Coding-Conventions

**Comment by Lineflyer** [comment]
@eddiemuc Thanks, great!
I made some comments to your PR as I guess we can/should use this opportunity to tackle those string related issues right now and can hopefully remove them from the baseline right away. Please kindly take a look at my comments.

**Comment by fm-sys** [comment]
AFAIK this issue is fully solved
