### ISSUE TITLE
checkstyle configuration for static imports

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8032]
The checkstyle definition for imports is defind by the module ImportOrder.
See https://checkstyle.org/property_types.html#importOrder

The current checkstyle configuration defines static imports as "top". There is no definition for grouping the static imports. This means that all static imports are in one group on top of all imports, but the non static imports are separated in groups.
I suggest to include the static imports in the non static import section, my favorite is "under".

What do you think?

**Comment by moving-bits** [comment]
Sounds reasonable. I can see no reason why to put all static imports at the top and separate imports from the same source file group.

**Comment by bekuno** [comment]
@rsudev @SammysHP You where involved on creating this "Coding convention". What do you mean to this change?

**Comment by bekuno** [comment]
@jonas-koeritz Do you have a preference?
