### ISSUE TITLE
Hint field for coordinates incorrect?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8037]
Followup as discussed in #8036

The text hints used for coordinate input fields might be IMHO wrong:
- The MinDec (DD° MM.MMM) has fractions of minutes behind the decimal point but the hint says "seconds".
- The DegDec (DD.DDD°) uses fractions of seconds but the hint says "minutes" behind the decimal point

**Comment by moving-bits** [comment]
I just cross-checked: Yes, the fields are reused and have different meanings, depending on the format selector. So I need to set different hints depending on the format setting.

Proposal:

|format|hints|
|------|-----|
|plain|latitude / longitude|
|DDD.DDDDD°|degrees / fraction of degrees (each with prefix latitude or longitude)|
|DDD°MM.MMM|degrees / minutes / fraction of minutes (each with prefix latitude or longitude)|
|DDD°MM SS.SSS|degrees / minutes / seconds / fraction of seconds (each with prefix latitude or longitude) |
