### ISSUE TITLE
List view broken for unsupported languages

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8043]
Taken from a user on FB.....I am a bit clueless.

![FB_IMG_1577746929344](https://user-images.githubusercontent.com/949669/71604199-d9d9b600-2b60-11ea-8ceb-4eb0fcc1ec56.jpg)

Waiting for details and system information as I asked the user to contact us.

**Comment by Lineflyer** [comment]
Related system information provided by the user:


--- System information ---
Device: SM-A520F (a5y17ltexx, samsung)
Android version: 8.0.0
Android build: R16NW.A520FXXUBCSI2
c:geo version: 2019.12.30
Google Play services: disabled - 19.8.31 (040408-284611645)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: iw_IL
System date format: d.M.y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (2.3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (2.3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (2.3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (3.4 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d/MM/yyyy
Installed c:geo plugins:  none
--- End of system information ---

Can this be related to the language "iw_IL" ?

**Comment by bekuno** [comment]
Did it worked before or is this a new cgeo user?

**Comment by bekuno** [comment]
> Can this be related to the language "iw_IL" ?

@Lineflyer Can you test such situation with a system set to a language which is not contained in c:geo?

**Comment by moving-bits** [comment]
I had set the emulator to hebrew (although probably not iw_il, as current ISO code is different), but c:geo stays at en_US (which was set as second language).

**Comment by Lineflyer** [comment]
It is an existing user.. Problem started "a few months ago"

After adding english as second language he says, its working now. Not sure whether in english or hebrew. I asked the user.

**Comment by Lineflyer** [comment]
> @Lineflyer Can you test such situation with a system set to a language which is not contained in c:geo?

Yes, indeed I can reproduce the problem, when settings Hebrew as single language on my Samsung S10.
Without having everything checked in detail, it seems only the list view is affected (as shown in the screenshot above). Rest of the app is english and looks normal (or course right to left formatted, which is quite irritating :) )

**Comment by Lineflyer** [comment]
From timing perspective it could be related to our switch to new SDK levels

**Comment by jonas-koeritz** [comment]
Maybe the layout of the list items breaks when switching to Right-to-Left. Can somebody test this using the "Force Right to Left" switch in the developer options and a supported device language?

**Comment by Lineflyer** [comment]
> Maybe the layout of the list items breaks when switching to Right-to-Left. Can somebody test this using the "Force Right to Left" switch in the developer options and a supported device language?

After learning that the affected language is right-to-left I think the layout is ok, but there are no strings shown. BTW: Its only the list view, other parts are working fine and shown in english. 

Summary:
User activated Hebrew as only language on his device --> List view looks like above, rest is working in right to left and using english
User activates Hebrew+ English (secondary) on his device -> List view is OK in english, rest is still working in english (as above)

**Comment by Lineflyer** [comment]
Did we meanwhile include hebrew?

**Comment by Lineflyer** [comment]
Tested and no longer showing up with 2021.07.06-RC.

Although some styles are a bit strange in RTL format.
@If you want to be really confused, set your emulator/device to Hebrew and enjoy. Good work, only some minor issues...despite that everything  mirrored does look really strange.
