### ISSUE TITLE
Cannot load OC15847

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8044]
2019.12.30-NB

OC15847 is listed in nearby results but loading details fails. "cgeo cannot find this cache"

The listing looks rather normal on the OC webpage.

Reproducible for this cache, others work normal.
No idea yet, whether the problem is in c:geo or on OC.

**Comment by rsudev** [comment]
Quickly checking the log I find:
12-31 12:15:20.974 E/cgeo    (12553): java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode

Likely the internal structure of some item is not as expected.

**Comment by bekuno** [comment]
Today the cache is loadable.

**Comment by Lineflyer** [comment]
No idea what caused it, but seems to be solved though.
