### ISSUE TITLE
Black bar crossing screen when closing popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8048]
- Open live map (Google or OSM does not matter)
- Click on cache or waypoint to open its popup
- Discard popup by clicking the back key or tapping outside of it

Result:
- Popup closes but a black bar/line runs through the screen from top to bottom

Expected Result:
- No such graphic glitch

Device/Config:
-Samsung Galaxy S10 (was also reported for other Samsung models at least)
- 2019.12.31-NB (but seems also on 2019.11.28 according to user mails)

No functional problem, but an interesting glitch, which I did not actively notice until some user made me aware of it.
100% reproducible on my Samsung S10

**Comment by bekuno** [comment]
Visible also on Samsung Note8 (Android 9), but not on Samsung S6 (Android 7.0)

**Comment by moving-bits** [comment]
Do we have reports coming in for non-Samsung devices running Android 9 or 10?
(To see whether it's a general Android 9 or 10 "feature" or if it's Samsung Android 9 or 10 specific.)

**Comment by Lineflyer** [comment]
No, no other reports yet.
And all my other devices are below Android 7 and do not have the problem. We might have to wait to get more clues.

**Comment by Lineflyer** [comment]
According to social networks it also appears on Huawei P30, so potentially not limited to Samsung.

**Comment by jakedot** [comment]
It happens on my Samsung as well.

--- System information ---
Device: SM-J415FN (j4primeltecis, samsung)
Android version: 9
Android build: PPR1.180610.011.J415FNXXS4BSI4
c:geo version: 2019.12.30
Google Play services: enabled - 19.8.31 (100300-284611645)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_AT
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (16,9 GB free)
internal
User storage c:geo dir: /storage/emulated/0/cgeo (16,9 GB free) external
non-removable
Geocache data:
/storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (16,9
GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (7,7 MB) on system
internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins: contacts
--- End of system information ---

**Comment by Lineflyer** [comment]
I was made aware by a user today, that the problen is gone. No idea why, but I can confirm.
Any idea what changed?

**Comment by moving-bits** [comment]
AFAICS we have no code change for either introducing or fix this, so it's probably a fix in Android support libs...
