### ISSUE TITLE
Caches disappear after consecutive  map source change

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8049]
- Open live map with OSM online or offline map
- Deactivate live function so that only saved caches are shown
- Leave live map
- Reenter live map (still deactivated)
- Saved caches are shown
- Change map source to Google
- Caches still shown
- Change map source to OSM online or offline

Result:
- No caches shown anymore on map. On further change of map source no caches are shown until live is enabled/disabled again

Expected Result:
- Caches should be shown as before regardless of the map source

**Comment by moving-bits** [comment]
Reproducible on current master even without entering live map first.

@Liveflyer: Do you happen to know since when this bug occurs? Is it for nightly only, or release as well?

**Comment by Lineflyer** [comment]
I noticed it without really realizing the problem IMHO after introduction of GMaps v2.

**Comment by moving-bits** [comment]
So it might be already a few months old? Or more or less introduced by the last couple of merges? (Just trying to narrow it down a bit before starting to check with old builds.)
