### ISSUE TITLE
Implement different Map Types as Fragements

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#8056]
Currently there are several Layers of abstraction involved in the Map Activities.
Given that the Map Activities are very similar in nature they should be merged into one MapActivity and the different types of maps should be put into interchangeable Fragment classes extending an abstract MapFragment class that handles the common functionality.
The MapActivity and child Fragments can be wired up using a ViewModel to provide all necessary data to the Map view as LiveData.
The Activity sets all user controllable parameters for the underlying query (comparable to the current MapOptions) and the MapFragment implementations wire up the LiveData to the Map views using their specific APIs.
The ViewModel will be shared between the MapActivity and the MapFragment and serve as a single source of truth for the visible caches and any interaction with them.

**Comment by jonas-koeritz** [comment]
This would be a step towards #5606.

**Comment by moving-bits** [comment]
@jonas-koeritz
FYI: In #5947 you'll find some more history of the map dependencies, just stumbled upon it.

**Comment by jonas-koeritz** [comment]
Can somebody give me a hint on where the Cache markers for the map are actually created?

**Comment by moving-bits** [comment]
> Can somebody give me a hint on where the Cache markers for the map are actually created?

Have a look at `utils/MapMarkerUtils`, methods `getCacheMarker`, `createWaypointMarker` etc.

**Comment by jonas-koeritz** [comment]
Creating CacheMarkers works like a charm.
![Screenshot_20200107-210724](https://user-images.githubusercontent.com/6485387/71925665-d615e700-3191-11ea-9383-706cb5505e78.png)

**Comment by jonas-koeritz** [comment]
Just for reference: #7969

**Comment by jonas-koeritz** [comment]
Implentation Detail: #7984

**Comment by jonas-koeritz** [comment]
Implementation Detail: #8022

**Comment by jonas-koeritz** [comment]
Potential addition: #7977

**Comment by jonas-koeritz** [comment]
This has been abandoned in favor of getting the backend done first.
