### ISSUE TITLE
Create a ViewModel backed Cache Pop-Up

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#8057]
The current cache Pop-Up seems to have some code and responsibilities that should be moved to a ViewModel and an underlying Repository.
The Layout and implementation of the Cache Pop-Up should be changed to allow for better dynamic updating of the contents. And to be a bit more consistent looking. Currently Pop-Ups vary in size and available buttons, there should be sensible defaults and disabled states chosen to make them feel more consistent.

**Comment by jonas-koeritz** [comment]
This can be implemented inside of the MapActivity (see #8056) referencing the ideas from #3932.

**Comment by jonas-koeritz** [comment]
The layout could potentially be expanded to provide a Google Maps like user experience, where sliding up the quick info reveals the cache details.
In the quick info (non-expanded state) we could put action buttons for commonly used cache interactions.

**Comment by jonas-koeritz** [comment]
Google Maps is IMO a good role model for what we are doing, it provides a quick overview, a detailed page with information and easily invokable actions as well as reviews (Logs).

This won't be easy to implement in one go, so during the transition this could use the existing details Activity instead of a complicated expanded state.

**Comment by jonas-koeritz** [comment]
Just a quick update/peek, I implemented a BottomSheet in backed by a ViewModel as well is general zoom controls in my replacement Map Activity.
Don't mind the generic markers, I just haven't had the time to port the marker generation yet.

![Screenshot_20200106-154458](https://user-images.githubusercontent.com/6485387/71825170-9076f280-309b-11ea-8b2e-99b6965a77b0.png)

What do you think, what information and which actions should be available without expanding the BottomSheet?

**Comment by Lineflyer** [comment]
Looks like a nice replacement for the popup.

> What do you think, what information and which actions should be available without expanding the BottomSheet?

Compared to the current popup the following info is missing:
Distance, Favorites, GCVote

Distance could IMHO be shown in something similar to the current style when a cache is set as a target (below the title) if this is still feasible and meaningful in your implementation.

Favorites should be added to the bottom sheet IMHO.

GCVote might not be that mandatory, however it could be abbreviated (like D and T) and would fit.
So the bottom sheet would not miss any of the information we currently have on the popup.

**Comment by Lineflyer** [comment]
Forgot actions:
I think the quick navigation button should be there at least, maybe also the "Set as target" button.

**Comment by moving-bits** [comment]
Like your proposal!

Things I would like to see additionally in this first small fragment are:
- distance
- cache or waypoint type (symbol only)
- action buttons: compass & navigation, hint & save/reload
This should still fit into the same size as you've proposed.

Something like this:
![image](https://user-images.githubusercontent.com/3754370/71848028-be295f00-30ce-11ea-986e-8d1c59118e90.png)


Expanding this tiny fragment to the next size (intermediate) could additionally display the other info from the current popup, like
- favorite count
- GC vote
- cache/waypoint type as text (could be left out in the first window IMHO, if space becomes too small)
- list names
- action buttons for list edit, delete
- for waypoints: "visited" checkbox
- three dot menu

Expanding the fragment further would lead to the current cache details page.

**Comment by jonas-koeritz** [comment]
I implemented a little transparent circle to show mark the currently selected cache. Since there is no cache Pop-Up blocking the view of the map this seems necessary. Have you got any other ideas on how to make it clear wich one is selected? This might clash with the "show circles" feature...
![Screenshot_20200107-212913](https://user-images.githubusercontent.com/6485387/71927090-0317c900-3195-11ea-916f-3743ca7bbcab.png)

**Comment by jonas-koeritz** [comment]
"Quick Actions" proposal 1: Google Maps Style.
The buttons could be dynamically added with respect to the cache type etc. The row of buttons is horizontally scrollable. Needs some icons, but I don't think it's the perfect solution yet.
![Screenshot_20200107-225030](https://user-images.githubusercontent.com/6485387/71932526-46c40000-31a0-11ea-95bc-a8b604358cac.png)

**Comment by moving-bits** [comment]
> I implemented a little transparent circle to show mark the currently selected cache. Since there is no cache Pop-Up blocking the view of the map this seems necessary. Have you got any other ideas on how to make it clear wich one is selected? This might clash with the "show circles" feature...

We once had an orange circle around the cache marker (then marking "unreliable coordinates"), which we don't longer use since you implemented the new map parsing. We could reuse that:

![image](https://user-images.githubusercontent.com/3754370/71932761-d10c6400-31a0-11ea-8428-854e8e488e8c.png)

**Comment by moving-bits** [comment]
> "Quick Actions" proposal 1: Google Maps Style.
> The buttons could be dynamically added with respect to the cache type etc. The row of buttons is horizontally scrollable. Needs some icons, but I don't think it's the perfect solution yet.

IMHO this takes up too much space for this first-level fragment.
Why not reuse the action buttons we currently have in use? (Just a bit larger than in my screenshot above.) There should be enough space right beside the currently shown info to add up to 2x2 buttons.

**Comment by jonas-koeritz** [comment]
> We once had an orange circle around the cache marker (then marking "unreliable coordinates"), which we don't longer use since you implemented the new map parsing. We could reuse that

The orange circle marker could be a bit confusing for users that are familiar with the unreliability marking but seems like a good solution, maybe we could use another color?

> IMHO this takes up too much space for this first-level fragment.

It looks really huge on the screenshots when viewed on a PC. On the actual device it's really comparable to G-Maps.

On the plus side:
* we could reorder these buttons dynamically to react to e.g. different cache types.
* horizontal scrolling allows for "unlimited" actions
* big touch targets
* Text on the Buttons (See [From icons perception to mobile interaction](https://annals-csis.org/proceedings/2011/pliks/36.pdf))

On the minus side:
* Wastes space in the bottom sheet
* Transition to the expanded state might be a bit tricky to implement

I'd like to hear additional opinions on this. Both solutions don't seem to be optimal.

**Comment by moving-bits** [comment]
> > We once had an orange circle around the cache marker (then marking "unreliable coordinates"), which we don't longer use since you implemented the new map parsing. We could reuse that
> 
> The orange circle marker could be a bit confusing for users that are familiar with the unreliability marking but seems like a good solution, maybe we could use another color?

Good idea, +1

> > IMHO this takes up too much space for this first-level fragment.
> It looks really huge on the screenshots when viewed on a PC. On the actual device it's really comparable to G-Maps.

Ok, acknowledged. And it's definitely still more compact than today's popup.


> On the plus side:
> * we could reorder these buttons dynamically to react to e.g. different cache types.

I fear that this might be confusing, IMHO it's better to always use the same (expected) order of buttons / touch points.

> * horizontal scrolling allows for "unlimited" actions

Hm, we should discuss advantages and disadvantages of scrolling. I'm personally not a fan of having to scroll for menu points, at least not for a short menu of only a handful of entries. (That's why I favor small buttons + an overflow/"hamburger style" menu.)

> * big touch targets

This is an important point (and a mistake in my proposal above - the buttons I rendered were too small compared to the text; I meant them to be the same size as in c:geo today).

> * Text on the Buttons (See [From icons perception to mobile interaction](https://annals-csis.org/proceedings/2011/pliks/36.pdf))

This is double-edged:
(+) Labels, when well-chosen, might transport the meaning clearer
(-) Buttons, once learned what they stand for, are faster to recognize
(-) Label length varies significantly depending on the translation, so some people might have to scroll much more than others...

> On the minus side:
> * Wastes space in the bottom sheet

Ok, following your explanation above, we probably need to have a prototype which we can test to see, if it's really that much space.

> * Transition to the expanded state might be a bit tricky to implement

No idea for this one, you're the technical guru ;-)


Please don't get my feedback wrong - I really appreciate what you're doing here, and I see it as a big step forward in modernizing the UX of c:geo, thanks for that!

**Comment by jonas-koeritz** [comment]
You're right, always presenting the same actions is the way to go. Developing something to predict the most used action etc. would just complicate things as well.

I planned on showing an Icon on the button next to the text to make them a bit more recognizable, this would grow them even further and limit the number of actions that can be shown.
Maybe just two to three a, well chosen actions should be shown as "quick actions" and everything else can be placed somewhere else, for example in an overflow menu.
This would also limit horizontal scrolling to really unfortunate translations ;).

**Comment by Lomanic** [comment]
Re: the marker highlight, did you check how it's implemented on the official Geocaching app? That looks really good to me.

**Comment by jonas-koeritz** [comment]
I've just installed it to have a look. I like that one too, but our current implementation does allow the user to choose between dots and markers, there won't be much of a difference anymore. I would be okay with that.
Swapping a marker on selection wouldn't be too hard to implement too.

I haven't looked into that app in ages. Looks like their quick info is very similar to my first iteration (without quick action buttons) 😅.

**Comment by jonas-koeritz** [comment]
I've abandoned the Pop-Up redesign in favor of getting the Backend to work first.
