### ISSUE TITLE
Implement a Room Database, Repositories, Entities and DAOs

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#8058]
The base for all changes related to Room are the Database, Entities, Repositories and DAOs.
I will be creating these as I go to enable the functionality of the rewritten and/or new parts of the app discussed in this project.
The current monolithic Geocache Class will be broken down a little to allow for easier queries.
To allow for a soft migration there will be code in place to sync all relevant user data between both worlds.

**Comment by jonas-koeritz** [comment]
Implementation Detail: #7998

**Comment by Lineflyer** [comment]
@jonas-koeritz Really #7998 ? (looks unrelated)

**Comment by moving-bits** [comment]
Maybe the following issues can be solved with this change as well: #8009, #7634 (I suspect them to be caveats of our internal caching mechanism)

**Comment by jonas-koeritz** [comment]
@Lineflyer I'm just collecting info on where to pay special attention when implementing the entity classes.

**Comment by jonas-koeritz** [comment]
I've made a lot of progress so far and will push to my personal fork soon to get some feedback. As I already stated in the mailing list, there are some breaking changes but it doesn't seem to be that bad at the moment.

**Comment by jonas-koeritz** [comment]
I pushed some code to my fork (https://github.com/jonas-koeritz/cgeo/tree/next_generation_backend), it's super unfinished and needs loads of adjustment but some parts are already working as expected. Many little bodges currently exist to stick the old parts (relying on the DataStore, CacheCache etc.) to the new code.
Also I haven't even touched the Google map yet.

This push is just to show some progress and what my approach might look like when finished.

**Comment by eddiemuc** [comment]
Looking forward to this

**Comment by jonas-koeritz** [comment]
I will close this issue for now in favor of the "bigger picture".
https://github.com/cgeo/cgeo/issues/9094#issuecomment-895090132
