### ISSUE TITLE
Google offline map already downloaded

### ISSUE THREAD

**Issue by Birdy2404** [cgeo/cgeo#8060]
Usecase:
For navigation I use Google maps already. Therefore I downloaded some maps for the offline navigation (Menü > Offlinekarten).
If I'm using the Google maps in Cgeo, it needs to download the same information again, even if it is stored already.

![IMG_20200106_075851](https://user-images.githubusercontent.com/34218281/71801221-8d0f4700-305a-11ea-80b9-263a13b71fef.png)

![IMG_20200106_075816](https://user-images.githubusercontent.com/34218281/71801241-98fb0900-305a-11ea-8128-38486c51130f.png)

Solution:
If the Google maps are stored offline already, they should be used. After I move out of this area the online map/tile should be downloaded.

I'm not sure if this is possible with the new version of the Google maps, but would be great to see, as I'm using a second simcard instead of a micro-SD 😉
Best regards from South Germany 
Andreas

**Comment by jonas-koeritz** [comment]
Hi,
The Google Maps SDK currently does not use the offline data stored by the Google Maps app. As an alternative you could download map files for the Mapsforge based map and store them on your phone.
