### ISSUE TITLE
send2cgeo server down ?

### ISSUE THREAD

**Issue by wizard4u** [cgeo/cgeo#8061]
I cannot use sendtocgeo and at the cgeo site the registration is down

**Comment by mucek4** [comment]
You were right. For some reason firewall was blocking the server from reboot last week. I enabled firewall and I'll investigate.

**Comment by moving-bits** [comment]
@mucek4   Thanks for fixing this. It also seems to have fixed the error with the CI not being able to trigger a build for a PR, which we had for the last couple of days.

**Comment by mucek4** [comment]
That was other issue, but I noticed it when I was solving send2. You should tell me.

**Comment by Lineflyer** [comment]
This seem solved. Feel free to reopen if not.

**Comment by wizard4u** [comment]
It works again. Thanx for the action

**Comment by Narrat** [comment]
@wizard4u so your reported problem #8064 is resolved? If so, you can close it :)

**Comment by wizard4u** [comment]
This is closed.  #8064 is not and is another issue
