### ISSUE TITLE
improve handling of automatic waypoint creation from notes

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8078]
_(taken from: https://github.com/cgeo/cgeo/issues/8068#issuecomment-575601703 by @MagpieFourtyTwo)_

Nevertheless this "AutoZoom" (i. e. showing all defined waypoints of a cache) still renders the map view useless in some (but regrettably not really rare) cases, like e. g. in combination with c:geo's stubborn way of creating completely senseless waypoints from the personal note.

Example? Just create a personal note like this:

```
12-a-c=7	=> a+c=5	=> a=2 / c=3
36-b-d=26	=> b+d=10	=> b=2 / d=8

a.b.c.d@gmx.de
2.2.3.8@gmx.de (don't try, doesn't exist anyway ;) )

Final (doesn't exist, neither):
N48 51.234 E9 01.234
```
From this personal note two waypoints will be created automatically:
1. N48 51.234 E9 01.234 - which is perfectly fine
2. N02 12.000 E3 48.000 - which is *very* obviously *complete* rubbish

Usually you can suppress the automatic generating by putting a colon after the "N" like 
```
Calculation
N:48 51.234+17 E9 01.234-22
```
but in the example below even colons do not help ... :(

So, can we *please* invent a way of suppressing at least these completely senseless waypoints?
Perhaps it would be at least a quick'n dirty workaroud to suppress automatic generation when the extracted waypoint data gives a result which is more than let's say 10 km away from the base coordinates?  I guess, WPs more than 10 km away are rare, and if there is one, the user can create it using copy'n paste?

Which BTW at least for me would be the preferred way anyway, hence it could also be a solution to be able to switch this automatic extraction completely off by a config flag ...?

**Comment by moving-bits** [comment]
So we have two suggestions (which may be combined):
a) Check to-be-created waypoints whether they are within a 10 km radius of the cache coordinates
b) Add an option to disable automatic waypoint creation at all

(And maybe a) can be switched on/off via a setting as well)

**Comment by bekuno** [comment]
I think that a) is a very good solution. And ~10 km looks ok.
I'm not sure if the other two are necessary.

**Comment by MagpieFourtyTwo** [comment]
> (And maybe a) can be switched on/off via a setting as well)

Or perhaps both combined by setting the max. "allowed" radius for automatic creation of new waypoints directly, whereas 0="disable check" ...?

**Comment by MagpieFourtyTwo** [comment]
> I'm not sure if the other two are necessary.

As for me (and in fact this is a general programming rule) "an automatism is a good automatism, if it can be switched off".  ;)

**Comment by Lineflyer** [comment]
I am not a fan of a limit not visible and thus not understandable by users. Additionally I often do bike caches with a length of sometimes up to 200km. For sure I store some waypoints in the note after completing e.g. half of them, which is always >>10km from base coords.

Another setting might be possible but I am also not a fan of to many settings, which a normal user might never need.

Why not first find out whats going on in the mentioned example and how the detection code can be improved to avoid it?

**Comment by moving-bits** [comment]
> Why not first find out whats going on in the mentioned example and how the detection code can be improved to avoid it?

That would be preferable, indeed. If someone wants to give that a try: I think the file to look at is `/location/GeopointParser.java` and there the `parseAll()` method of the `GeopointParser` class.

**Comment by MagpieFourtyTwo** [comment]
> Why not first find out whats going on in the mentioned example and how the detection code can be improved to avoid it?

This would of course be the best way, but - most regretfully - the scenarios, where c:geo fails to extract coordinates resp. "successfully" extracts (senseless) coordinates from just normal text, which does not even look like a coord, are in fact countless. I tried to male a collection of phrases where it usually fails, but I don't come to an end.

BTW: Another one is "10, 20, 100, 200, ja 300 Häuser = QS=9" which will end up in "N10 12.000 E100 12.000".

I guess, a profound analysis of this problem and then developing a bullet proof algorithm for coord extraction, which will probably even take all thinkable notations into account, will take ages and ages and ages - so, *please*, at least till then: Please make this automatism configurable, Or let it happen on explicit keypress (menu selection) only (like "Extract waypoints" from the listing). Or at least do not (automatically and immediately) recreate waypoints, which once have been extracted automatically, but then have been explicitly deleted by the user ...

**Comment by moving-bits** [comment]
It's probably impossible to "fix" this, as the above mentioned `parseAll` method evaluates all available Geopoint parsers and chooses the one which matches at the earliest position in the text. "All available" parsers means eight parsers for the different formats, so it's pretty likely that at least one of them matches...

Generally this works ok, or at least the results do not harm, but sometimes it gives you unwanted results. Therefore let me add a different approach:

c) Let automatic waypoint parsing be blockable on a per cache basis.

So in the dot menu of a cache details page there would be an entry "block automatic waypoint extraction" (or similar). This could be combined with b), but would also work on its own.

Extra bonus: Since
> do not (automatically and immediately) recreate waypoints, which once have been extracted automatically, but then have been explicitly deleted by the user ...

is not possible (at least not without some major rework), as deleted waypoints are ... deleted, with c) being implemented you could then load a cache, delete unwanted waypoints, and block further extraction for this cache, if needed.

If implementing c) alone without b) there would be no need for an additional global setting.

**Comment by MagpieFourtyTwo** [comment]
> It's probably impossible to "fix" this

Yep, had the same thought.

> c) Let automatic waypoint parsing be blockable on a per cache basis.

Yep, this would do the trick.

> Extra bonus: Since

Since?

>> do not (automatically and immediately) recreate waypoints, which once have been extracted automatically, but then have been explicitly deleted by the user ...
> is not possible (at least not without some major rework), as deleted waypoints are ... deleted, with c) being implemented you could then load a cache, delete unwanted waypoints, and block further extraction for this cache, if needed.

I thought of kind of "hidden" waypoints ... but in fact c) would be perfectly fine.

> If implementing c) alone without b) there would be no need for an additional global setting.

Agreed (as in some cases the automatic extraction is a nice thing).

**Comment by MagpieFourtyTwo** [comment]
> Additionally I often do bike caches with a length of sometimes up to 200km.

Then, I guess, you are a fan of this "show all waypoints at a glace", described in #8112, too ...? ;)

**Comment by MagpieFourtyTwo** [comment]
Thanks a lot! :)

**Comment by MagpieFourtyTwo** [comment]
[...]
> c) Let automatic waypoint parsing be blockable on a per cache basis.
[...]
> with c) being implemented you could then load a cache, delete unwanted waypoints, and block further extraction for this cache, if needed.

This in fact works really good - with one issue, I just stumbled upon: On refreshing the offline saved listing, this flag seems to get lost and waypoints are automatically created again, thus on every refresh (to e. g. see newest logs), the intended effect gets lost and you again will have the whole bunch of annoying useless waypoints.

TMALSS: Would be great if this flag would be permanent, i. e. survive refreshes, thus lives until it will be explicitly unset by the user again (as I wold expected it anyway).
