### ISSUE TITLE
Portuguese  language not working (beta)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8080]
We have several users of beta version 2020.01.16-RC which claim, that c:geo is no longer using portuguese language but english.
Did not verify yet.

**Comment by moving-bits** [comment]
Searching the commit tree it seems to have come in via crowdin import in commit 1089fab4920b0b04af9bf594f0ea507cf006bddb - although Crowdin itself still shows the Portugese translations. @Bekuno  Can you have a look at the import script?

**Comment by Lineflyer** [comment]
Once corrected please kindly push into ˋreleaseˋ branch.

**Comment by bekuno** [comment]
@moving-bits Thanks to find the problematic commit.

The error was introduced by adding additional languages.
In this case it conflicted to "Portuguese, Brazilian" (pt-BR), which was transfered instead of "pt-PT" to c:geo as "pt".

**Comment by moving-bits** [comment]
According to https://stackoverflow.com/questions/24654574/how-can-i-have-both-res-values-pt-pt-and-res-values-pt-br-on-android we can have both:
The dir `values-pt` needs to be renamed to `values-pt-rPT`, the Brazilian file goes into a dir named `values-pt-rBR`.

**Comment by bekuno** [comment]
The first challange is that we get only short name folders from crowdin. Here: values-pt.
For now it is no problem as long no one want to translate such conflicting language (e.g. "German, Austria" :-) )
I did not find a point to change that.
@ rsudev Any idea?

**Comment by moving-bits** [comment]
Hm, if we can't make Crowdin to deliver long lang codes for conflicting languages - can we block those languages then (allowing pt-PT only, but blocking pt-BR)?

**Comment by bekuno** [comment]
pt-BR is now removed at crowdin.

**Comment by bekuno** [comment]
fixed by #8084
