### ISSUE TITLE
Localize name of ZZ0 cache and provide more explanation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8082]
Some beta testers are confused about the ZZ0 cache showing up on their default list.
While the description explains the meaning (also localized AFAIR), the title " 'Go to' targets" seems to be in english only.

Maybe translating it will help a bit.

Additionally in contrast to the first planning this cache is now on the default list.
If there is no possibility to make it "invisible" we could at least provide a more detailed info text in its cache description (which describes why it is there, how to handle it, and that it can be deleted and will be autocreated if the Go to menu is used).

**Comment by moving-bits** [comment]
> Some beta testers are confused about the ZZ0 cache showing up on their default list.
> While the description explains the meaning (also localized AFAIR), the title " 'Go to' targets" seems to be in english only.
> 
> Maybe translating it will help a bit.

That's the weak spot of migration: During the database operation I cannot access the translated strings (or at least I haven't found a way to do so, as no `Context` object is available to this background task, but is necessary to translate strings).
So if we want to migrate the old history targets, we have to stay with English in the beginning.

If you delete ZZ0, and create new "go to" targets a couple of days (\*) later, a new ZZ0 will be created automatically, and this time it will be in localized strings.
((\*) "A couple of days" being at least three days, as this is our tolerance limit after which a deleted cache gets actually removed from database.)

> Additionally in contrast to the first planning this cache is now on the default list.
> If there is no possibility to make it "invisible" we could at least provide a more detailed info text in its cache description (which describes why it is there, how to handle it, and that it can be deleted and will be autocreated if the Go to menu is used).

Do you have a proposal for the explanation?
Or shall we simply add a link to the online manual for further explanation. (By this it would be easier to change explanation details. OTOH we would have less translations, probably.)

Additionally we can create an individual list for this cache (alas non-translated as well), "ZZ history of 'go to' targets" or something like this.


A more radical way would be to not migrate any historic "go to" targets. By this, ZZ0 would be created in a localized version. (And we can still decide whether to put it into a new list and/or add some more explanation or a link to its description.)

**Comment by moving-bits** [comment]
> Some beta testers are confused about the ZZ0 cache showing up on their default list.
> While the description explains the meaning (also localized AFAIR), the title " 'Go to' targets" seems to be in english only.
> 
> Maybe translating it will help a bit.

That's the weak spot of migration: During the database operation I cannot access the translated strings (or at least I haven't found a way to do so, as no `Context` object is available to this background task, but is necessary to translate strings).
So if we want to migrate the old history targets, we have to stay with English in the beginning.

If you delete ZZ0, and create new "go to" targets a couple of days (\*) later, a new ZZ0 will be created automatically, and this time it will be in localized strings.
((\*) "A couple of days" being at least three days, as this is our tolerance limit after which a deleted cache gets actually removed from database.)

> Additionally in contrast to the first planning this cache is now on the default list.
> If there is no possibility to make it "invisible" we could at least provide a more detailed info text in its cache description (which describes why it is there, how to handle it, and that it can be deleted and will be autocreated if the Go to menu is used).

Do you have a proposal for the explanation?
Or shall we simply add a link to the online manual for further explanation. (By this it would be easier to change explanation details. OTOH we would have less translations, probably.)

Additionally we can create an individual list for this cache (alas non-translated as well), "ZZ history of 'go to' targets" or something like this.


A more radical way would be to not migrate any historic "go to" targets. By this, ZZ0 would be created in a localized version. (And we can still decide whether to put it into a new list and/or add some more explanation or a link to its description.)

**Comment by moving-bits** [comment]
I'm trying to break that down into separate blocks:

a) The base question is whether we want to migrate "go to" target history at all, knowing that all explanation texts for b) and c) won't be localized but in English during that migration. (Those texts will be localized if we don't migrate, and the user creates new target waypoints later on, which will automatically create ZZ0 then.)

b) Independently from that we need to decide what info we want to add to the ZZ0 cache that gets created - just a link (pointing to the online user manual) or some additional text. "Just a link" has the advantage of not having to be localized now (and is more update friendly), but it's one step more for the user.

c) And last but not least whether we want to store the ZZ0 into standard list or into a newly created list (visible for and deletable by the user), getting a name which is either localized (if not migrated) or non-localized (when migrating "go to" target history).

What do you think?

**Comment by Lineflyer** [comment]
> a) The base question is whether we want to migrate "go to" target history at all, knowing that all explanation texts for b) and c) won't be localized but in English during that migration. (Those texts will be localized if we don't migrate, and the user creates new target waypoints later on, which will automatically create ZZ0 then.)

The experience I have from meeting with users and support chats is, that only quite few people use the "Go to" frequently. I also guess, that they do not store any coordinates there, which they want to keep long termed. Anyway people using the function will have their reasoning and might need these coords. So migration is somehow a plus.

> b) Independently from that we need to decide what info we want to add to the ZZ0 cache that gets created - just a link (pointing to the online user manual) or some additional text. "Just a link" has the advantage of not having to be localized now (and is more update friendly), but it's one step more for the user.

I think some additional text (needs then to be localized for sure) is the best way. The manual has significantly less languages available. IMHO we need only few sentences like "This cache saves your recent "Go to" targets. It is automatically created once you have used the "Go to" function in the main menu. The coordinates entered there will be stored into waypoints of this cache. If you do no longer need these coordinates you can safely delete this cache for now or move it to any other list of your choice."

> c) And last but not least whether we want to store the ZZ0 into standard list or into a newly created list (visible for and deletable by the user), getting a name which is either localized (if not migrated) or non-localized (when migrating "go to" target history).

I only recently realized, thanks to our beta testers, that this "strange cache" in their default list bothers them. There seem to be a lot of users only using the default list with a few caches in it, which is suddenly "disturbed" by the appearance of this ghost cache. A dedicated list might be more wise.

Summary:
I have no preference of migration/no migration, but we should use local strings in description and a dedicated list with localized name (e.g. "Internal caches").
That looks to me like the best approach.

BTW: I am still wondering, that we cannot localize during auto-creation...

**Comment by moving-bits** [comment]
@Lineflyer  Thanks for your detailed feedback.

> BTW: I am still wondering, that we cannot localize during auto-creation...

Opening the database is done in a background task during startup. As far as I have seen from the docs there is no `Context` object available in background tasks, but without a `Context` object I cannot localize strings. - I may be wrong, though, so if anyone knows of a way to circumvent this, please tell me.

So to summarize:
- If we don't find a way to localize strings during database migration phase, we would do no migration, as we value localized strings higher than migration in this case.
- ZZ0 should be created in a new dedicated list, given some default name.
- ZZ0 should get some additional explanation.

I'll start working on it...

**Comment by moving-bits** [comment]
Another idea came across my mind:

___If___ we want to migrate the history, and do so in a localized form, the following might work:

- do not create ZZ0 during opening the database, and do not create any waypoints from "go to" history then, as it seemingly cannot be localized there
- when opening the "go to" menu we already perform a check to see if ZZ0 exists. Extend this check: If ZZ0 does not exist, do
  - create ZZ0 (with localized texts)
  - if "go to" history table still has entries: migrate up to 5 of them into (localized) waypoints, and clear the history table

We would then have an empty "go to" history table for some time - can remove that at a later point in time, maybe in a year from now or so, and at the same time remove the check described above as well.

Strictly speaking, it's not as clean as a regular DB schema change is, but it's more user friendly as it leads to localized texts in the cache and waypoints created.

What do you think?

**Comment by moving-bits** [comment]
Another thing we should decide on is the db scheme change:

The migration we have now changes the db scheme from 77 to 78. If we don't use this migration (by either simply removing it or by replacing it in the way described above), we would not need the scheme change to 78. We have two options:

a) Simply remove it. db scheme stays at 77 => Users of the nightly version would need to restore the database from a backup having the old db scheme.
b) Stay at scheme 78 , with an empty migration routine => Looks somewhat odd in the source code, but does not harm otherwise - end user experience is the same as with other changes in c:geo involving a db scheme change.

As I'm unsure how many users of the nightly versions are prepared for variant a) I propose to go with b)

What do you think?

**Comment by Lineflyer** [comment]
The on-demand migration seems to be a reasonable idea, however I don't know if there could be side effects. But I guess the Go to function is quite isoated and only accessible in a single way. So why not.

Don't to much care about nightl users, maybe only about beta users...

**Comment by moving-bits** [comment]
Nightly and beta users are being taken care of with the updated version of #8095, on demand migration is implemented with #8099.

**Comment by moving-bits** [comment]
Fixed with the combination of #8088, #8095 and #8099.
