### ISSUE TITLE
test error: Integer.toString(Calendar.YEAR) = "1"

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8086]
see https://ci.cgeo.org/job/cgeo%20pull%20request/2516/consoleFull

errors in
 cgeo.geocaching.log.LogTemplateProviderTest.testApplySignature(LogTemplateProviderTest.java:42)
 cgeo.geocaching.log.LogTemplateProviderTest.testApplyTemplates(LogTemplateProviderTest.java:26)

Why is:
~~~
   Integer.toString(Calendar.YEAR) = "1"
~~~
And if an error for year 2020, why not before??

**Comment by Lineflyer** [comment]
I thought while seeing the result it test if year contains "1" which passed until 2020

**Comment by bekuno** [comment]
Should I fix this based to release or master?

**Comment by bekuno** [comment]
> I thought while seeing the result it test if year contains "1" which passed until 2020

And today: "Signature January 20, 2020" no "1", but yesterday 19th :-)

**Comment by Lineflyer** [comment]
Test fixes always on release which we will merge back to master.

**Comment by bekuno** [comment]
"8086" - a intel issue :-)

(https://usb-ids.gowdy.us/read/UD/8086)
