### ISSUE TITLE
send2cgeo button has disappeared from cache page

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#8090]
Hi guys,

I've posted this on the send2cgeo issues page, not sure if you need to know about it here as well.
Apologies for the duplication if not.

I no longer see the send2cgeo button on a cache page.
I'm running Chrome 79.0.3945.130
TamperMonkey v4.9
send2cgeo 0.46

**Comment by bekuno** [comment]
The issue https://github.com/cgeo/send2cgeo/issues/72 is enough.
