### ISSUE TITLE
Map themes don't work on Mi 9T

### ISSUE THREAD

**Issue by Gatarron** [cgeo/cgeo#8093]
Some time ago I changed to a Redmi Mi 9T smartphone and installed c:geo, and offline maps and themes as well. This always worked well in my previous smartphones, but not on this one. Although I had set the themes folder, the themes won't load. I was upset because I couldn't see the contour lines (the ones that show the variation in altitude) and blamed it on the smartphone.

However, I recently tried to use the same theme on the Locus app, and it worked perfectly, which made me realize that the problem should be in the c:geo app. Maybe ther is an issue with this specific smartphone model or Android mount.

Do you have any ideas on what may cause this bug and how to solve it?

This happened on every c:geo version since about 6 months ago.

Attached are images of my smartphone specs and of cgeo with the themes folder selected, as I had done previously, without problems.

![Screenshot_2020-01-22-14-44-22-562_com android settings](https://user-images.githubusercontent.com/54314831/72906653-73dcea80-3d2a-11ea-9934-4c525646e485.jpg)
![cgeo temas](https://user-images.githubusercontent.com/54314831/72906675-81927000-3d2a-11ea-85d6-0a44c22f343d.jpg)

**Comment by Lineflyer** [comment]
Can you please share s screenshot of the content of the folder you marked?

**Comment by Gatarron** [comment]
Here's the screenshot:

![Screenshot_2020-01-23-20-02-55-966_cgeo geocaching](https://user-images.githubusercontent.com/54314831/73020127-e5956100-3e1c-11ea-9258-f8db98e34cff.jpg)


I should add that, since my first post, I've managed to bypass the problem by uninstalling Locus Map Pro. At first, nothing happened, but then I noticed that the maps folder was set to the Locus map offline folder, although I kept setting it to the maps folder. In other words, the Maps folder you see in the previous screenshot ("Pasta de Temas de Mapas") was actually the Locus offline map folder when you opened it.

Still, I had Locus Map Pro app installed in my previous phones, and this never happened.

**Comment by Lineflyer** [comment]
> I should add that, since my first post, I've managed to bypass the problem by uninstalling Locus Map Pro. At first, nothing happened, but then I noticed that the maps folder was set to the Locus map offline folder, although I kept setting it to the maps folder. In other words, the Maps folder you see in the previous screenshot ("Pasta de Temas de Mapas") was actually the Locus offline map folder when you opened it.

I am sorry, I can't follow the changes you describe
In your first screenshot you set the maps folder to "sdcard/Mapas" and the theme to "...../0/Mapas/fzk-outdoor-contrast". It should be impossible that these settings change just by uninstalling Locus.
What exactly happend?

Regarding the screenshot of the folder:
Please post what is inside "fzk-outdoor-contrast". The shown dir does not help in debugging.

**Comment by bekuno** [comment]
I think you installed the theme automatic from https://www.freizeitkarte-osm.de/android/de/design.html .
On my device locus installed the theme(s) in the folder _themes as subfolder of the vectorMaps folder.
You can the set the _themes folder as theme folder in c:geo.
![20200123_230613](https://user-images.githubusercontent.com/32555742/73028254-71b38280-3e35-11ea-8797-93944a723599.jpg)

c:geo presents you all found themes (the xml files) to you.
![20200113_231845](https://user-images.githubusercontent.com/32555742/73028237-695b4780-3e35-11ea-8a09-8ff10dc76753.png)

**Comment by Lineflyer** [comment]
@bekuno 
Thats implicitly what I wanted to ask with my question for the dir content. :)

BTW: What kind of file explorer is this in your screenshot or is it a manual composition?

**Comment by bekuno** [comment]
@Lineflyer 
This is X-plore File Manager.
My favorite explorer, with 2 windows,...

@Gatarron 
is in the map settings the check box "old mapsforge V3" activated? This is not compatible with the Freizeitkarte themes.

**Comment by Gatarron** [comment]
> 
> @Gatarron
> is in the map settings the check box "old mapsforge V3" activated? This is not compatible with the Freizeitkarte themes.

Before unistalling Locus and deleting the Locus' themes folder, that was irrelevant, it didn't work either old mapsforge V3 was activated or not.

Also, I didn't installed the theme automatically, I copied several different themes (from several sources) for as many different folders in the phone memory, and selected each one successively as the theme folder, but none worked.

I am still puzzled why it always ended up on Locus map them, but unfortunately Iam unable to reproduce the steps that led me into this.
