### ISSUE TITLE
Ability to manually update spoiler images

### ISSUE THREAD

**Issue by RomNexus6** [cgeo/cgeo#810]
Hello,

after loaded a cache list from a GPX file, it should be useful to manually add some spoiler images inside the folder sdcard/.cgeo/cachename

unfortunately, after this operation, cgeo doesn't seem to use/see the new images stored.

please add some kind of feature/command that will allow cgeo to update caches spoiler/reference adding or updating them taking the files from inside the folders

thanks

**Comment by Lineflyer** [comment]
> is it like \GeocachePhotos\M\4\GC51Z4M\spoiler.jpg

@speedy-1702 
Sorry for the late reply, it should be:
`/cgeo/GeocachePhotos/M/4/GC51Z4M/spoiler.jpg`

See also here: https://manual.cgeo.org/en/spoilersync

**Comment by jakedot** [comment]
Wow, you never stop learning! I think I will do a c:geo seminar next, now that my local friends are all busy programming wherigos 👍
