### ISSUE TITLE
Handling of cache with corrected coords on server when using live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8100]
I noticed an interesting difference (triggered by a user on support mail):

- Have a cache where corrected coords are stored on the server side
- This cache is not previously loaded or stored in c:geo

Case A:
- Open the live map on the website for this area. The cache will be shown on the corrected coords (incl. a puzzle marker)

Case B:
- Open the live map in c:geo for this area. The cache will be shown at the listing coords.

With our current live map implementation I would have expected that for case a and case b the cache is shown at the corrected coords. Only the marker in Case A is not supported. However this seems not to be the case.

Therefore the feature request is:
- Use this information about corrected coords on our live map
- If possible also use our corrected coords marker to identify those caches on the map

@jonas-koeritz: Do you have an explanation for this difference?

**Comment by jonas-koeritz** [comment]
My code currently doesn't handle the user corrected coordinates. I will prepare a pull request, this looks easy.
