### ISSUE TITLE
Google Map and Caches with more than one coord/wp

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8111]
**Describe the bug:**

If you view a cache with at least one waypoint (with coordinates other than the cache's main coordinates) in Google Map or Sat view, it seems as if the cache coordinates displayed in the map change to the center of all waypoints of this cache: E. g. the red line to the cache does not end at the cache's (final) coordinates anymore, but in a kind of weighted center of all it's waypoints. Moreover the shown distance to the cache will no longer be calculated to the final, but to this imaginary center point.

**To Reproduce:**

1. open any cache with e. g. a changed final or even a parking waypoint
2. tap compass rose above waypoint list or at the top of the listing page
3. change to Google Map

**Actual behavior/state after performing these steps:**

Map will open with all waypoints in view (which is pretty senseless, anyway), the red line to the cache will end up in nowhere land in the middle of all waypoints and distance to cache will no longer be the distance to the cache but to this point.

**Expected behavior/state after performing these steps:**

Red line should end up at the final coordinates, distance should be calculated to the final coords.

**Version of c:geo used:**

2020.01.30-NB-a4abfda

**Is the problem reproducible:**

Yes

**Screenshots:**

Example for Google Sat with a cache with "normal" waypoints (screenshot has been taken while standing at the cache coordinates - and these have not been modified!):
![Wasser fällt](https://user-images.githubusercontent.com/9889015/73501387-113cbc00-43c6-11ea-9122-b70b1c0c9fd8.jpg)

Even worse: Google Sat with a cache with waypoints "automatically extracted" from a mystery solved in the personal note (one of these wps sits in Kapstadt, South Africa, thus not visible on the screenshot, but nevertheless pulling the red line's end to the south even more):
![Mystery](https://user-images.githubusercontent.com/9889015/73501640-d0917280-43c6-11ea-9d46-74b3206e9165.jpg)

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.0.0.178(C431E19R2P5)
c:geo version: 2020.01.30-NB-a4abfda
Google Play services: disabled - 20.1.04 (120400-288960190)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (25,1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (25,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (25,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (261,2 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Additional context:**

If you want to see a nice example (one picture tells more than 1000 words) of "automatic extraction of waypoints" in combination with "show all waypoints at a glance", just take any cache, add e. g. "10, 20, 100, 200, ja 300 Häuser = QS=9" to the personal note, then display this cache on any map you like ... and have fun zooming like hell while trying to approach the final ...  ;)

**Comment by moving-bits** [comment]
related to #8096
