### ISSUE TITLE
"Show all waypoints" in map - even from listing page?!?

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8112]
**Describe the bug:**

If you tap on the compass rose above the waypoint list, you will see all waypoints in the map. Which seems pretty logical. But when tapping on the compass rose at the top of the listing page, c:geo tries to show all, too - which is pretty senseless (as the context of this tap contains just one coordinate) and even more annoying, as the map zoom is way too big in a lot of cases.

**To Reproduce:**

1. Create some waypoints, or, even better, let c:geo extract one or more automatically from personal notes like "10, 20, 100, 200, ja 300 Häuser = QS=9"
2. Click on the listing page's compass rose
3. map view will start with a completely useless zoom level

**Actual behavior/state after performing these steps:**

Map zoom will end up at a level which renders map view completely useless.

**Expected behavior/state after performing these steps:**

When opening the map from a context where just one coordinate is shown (like on listing page), exactly *this* coordinate should be shown in the map. Centered. If there are more waypoints on the map tile shown, then display them, of course, but they should never ever have any influence on map zoom level nor center.

**Version of c:geo used:**

2020.01.30-NB-a4abfda

**Is the problem reproducible:**

Yes

**Screenshots:**
One of the WPs of the displayed cache sits in Kapstadt, South Africa, thus is not visible on the screenshot, but is nevertheless changing zoom to level making map view completely useless:
![Mystery](https://user-images.githubusercontent.com/9889015/73502378-2109cf80-43c9-11ea-9671-7dfee7f4a08a.jpg)

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.0.0.178(C431E19R2P5)
c:geo version: 2020.01.30-NB-a4abfda
Google Play services: disabled - 20.1.04 (120400-288960190)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (25,1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (25,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (25,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (261,2 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Additional context:**

There is no way to avoid stuff like this, as c:geo tries to automatically extract WPs from the personal note - and you can't stop it to do so. Which is already annoying, but one could live with it - till this "show all WPs at a glance feature" came into the game.

**Comment by MagpieFourtyTwo** [comment]
Sorry for repeating myself and for probably being a bit offensive, but had some Multis this weekend and again:  This "Show all waypoints at a glance from listing page" is biggest crap ever. And extremely annoying. Renders the listing page's compass rose completely useless. While doing a Multi you're zooming all day long. There was even more zooming then walking today ... :(((

**Comment by MagpieFourtyTwo** [comment]
I know, I'm repeating myself, but please, *please,* ***please,*** is there **any** way to go back to the previous - context based - actions for the compass roses as they were some time ago?

Had an MTB cache series today and every single time I hit the compass rose to see the way to the next cache, it displayed not just the cache, but the parking place too ... and the further we got, the bigger was the map zoom, and the more we had to pinch and zoom and the more action it took to get to the information needed, cause the distance to the parking place increased, of course. This strategy of determining the map sector is not just pretty senseless, as you don't need it this big at all, moreover it's even *extremely* annoying, cause every single time you have to zoom in, which is no fun at all, especially when the smartphone is sitting behind the protecting foil of the bike frame bag ... and all that while you're busy enough fighting the environment anyway. ;)

So, please, *please,* ***please,*** can we get it back as it was, thus show just the coords of the current context, when the compass rose is pressed, in fact:
- from listing page: just show the cache coordinates, with an appropriate zoom level (200 m would sound reasonable for me, to get an impression of the cache's surroundings)
- from waypoint page: all waypoints currently defined (like it is right now)

And last but not least: Have I already said that the current behaviour is extremely, *disturbingly* ***annoying*** ...?  ;)

Thanks a lot for reading and considering! :)

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 

Have you noticed #8127? It's not "back to before", but it makes the change optional, disabled by default.
Also, there is #8101 and #8128 upcoming on master branch to allow hiding certain waypoint types.

**Comment by MagpieFourtyTwo** [comment]
Already knew #8101 and #8128 - but as these options seem to *generally* disable *all* e. g. Parking waypoints, this would not be a real solution for the problem described above. And, to be honest, I don't even understand why [P]s should be hidden at all, cause while driving to a location by car, you of course want to see all parking lots nearby (thus you have to enable them), while walking to the cache, you do not need to see them (esp. if they influence zoom level, thus you have to disable them again), but after you finished your search, you want to go back to the [P] (and have to activate them again). Too much de/activation actions, I would say. But, YMMV.

Anyway - #8127 is indeed new to me, and it's ***really*** good news! Thanks **a lot** for pointing me to it, you really made my day!  :)

BTW: While I wondered how (and why) a feature/option goes to cgeo:release without being in the nightly, the message for a new nightly appeared, and guess what: It contained the new option(s)! Great! Played a bit around with it - and it is in fact what I dreamed of. Zoom level is the latest used, I guess?

Ok, displaying all waypoints from the waypoint list is currently not possible without changing the global option, but in fact this is the *way* less important point. And perhaps context sensitivity may come back one day anyway ... but doesn't really matter, as the scenarios where (at least I) must see *all* WPs are really rare, so the current solution is **way** better than before!

Thanks a lot! :)))

**Comment by MagpieFourtyTwo** [comment]
Just an idea: What would you think about a (maybe semi transparent) icon list, where one can see the enabled resp disabled (e. g. crossed out) waypoint types?

Moreover I would prefer if the hide menu would not to disappear on the very first tap, so one can enable/disable more than just one type in one go? Same applies to the Map Settings menu ... so one can set more than one option at a time - and a tap on the map, resp outside of the menu's area closes it ...?

**Comment by moving-bits** [comment]
> Just an idea: What would you think about a (maybe semi transparent) icon list, where one can see the enabled resp disabled (e. g. crossed out) waypoint types?
> 
> Moreover I would prefer if the hide menu would not disappear on the very first tap, so one can enable/disable more than just one type in one go? Same applies to the Map Settings menu ... so one can set more than one option at a time - and a tap on the map, resp outside of the menu's area closes it ...?

I created a separate issue for those feature requests, for easier tracking of feedback, see #8138.

**Comment by moving-bits** [comment]
> BTW: While I wondered how (and why) a feature/option goes to cgeo:release without being in the nightly

If I'm not mistaken, nightlies are built from master branch, where development of new features is being done on.
Currently we are in preparation of a new release, which is done from release branch. Any bugfixes for features already on release branch will be done on release branch as well (at least normally).
