### ISSUE TITLE
Make new "Goto" system less click-intensive

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#8114]
Hi there,

I was out today and encountered the new 'Goto' system for the first time, I use this to record coordinates when I'm out setting caches. I have to say it isn't very nice to use.

To record a new point, I have to
1) tap 'Add waypoint'
2) tap on co-ordinates
3) tap on 'My coordinates'
4) tap on the 'tick'
5) tap on another 'tick'
6) scroll to the bottom on the list
7) tap on navigate to check I've got it right

On the old system, it was (IIRC)
1) tap on 'My coordinates'
2) tap on navigate to check I've got it right (which also saves the waypoint)

Can something be done to reduce the workload?

At least. can new waypoints be named to that they appear at the top of the list instead of having to scroll all the way to the end of the each time.

**Comment by moving-bits** [comment]
Proposal 1 (for discussion):
Add a second button at the top which creates a new waypoint without any further need for confirmations. Waypoint will be at the current coordinates, type "reference point" and named accordingly.
If needed the waypoint can be edited later on by the user to change name, type etc.

Proposal 2 (for discussion):
Make the waypoint list user sortable by name (as today) and by last modified (newest first). Selection will be remembered.

**Comment by alan666notb** [comment]
> Proposal 1 (for discussion):
> Add a second button at the top which creates a new waypoint without any further need for confirmations. Waypoint will be at the current coordinates, type "reference point" and named accordingly.

Yes, that would make life a great deal easier.

> Proposal 2 (for discussion):
> Make the waypoint list user sortable by name (as today) and by last modified (newest first). Selection will be remembered.

I'm not sure how the sorting is done at the moment, my list of waypoints goes 5,4,3,2,1,6,7,8,9 (I think the first five were copied from the old system). New waypoints always appear at the bottom.

**Comment by jakedot** [comment]
Could we also have an option like the long-press on map to create a new user-defined cache which instead adds a waypoint to ZZ0? Maybe have the long-press pop up a choice menu to create a new cache or waypoint, or otherwise make it customizable? AFAIK there is already a menu option to enable or disable the long-press gesture to create a new UDC.
