### ISSUE TITLE
New entries in "Hide" menu do not work

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8125]
**Describe the bug:**
After checking one of the new "Hide" menu entries like "[X] Hide original waypoints", "[X] Hide parking waypoints" or "[X] Hide visited waypoints" the corresponding waypoints do not vanish from map.

**To Reproduce:**
1. Open a cache with changed coordinates, parking waypoint and/or visited stages
2. Display on map
3. Use menu "Hide" to activate an appropriate Hide option
4. Watch waypoints on map ...

**Actual behavior/state after performing these steps:**
Nothing happens at all.

**Expected behavior/state after performing these steps:**
The appropriate waypoints should appear resp. disappear, at least as I understand this feature.

**Version of c:geo used:**
2020.02.09-NB-ca725cd

**Is the problem reproducible:**
Yes

**Screenshots:**
The parking and visited waypoints shown in the map should not be visible anymore:
![Hide ,,, nothing](https://user-images.githubusercontent.com/9889015/74107545-8bf99a00-4b71-11ea-98c1-975e8dc60eed.jpg)

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.0.0.178(C431E19R2P5)
c:geo version: 2020.02.09-NB-ca725cd
Google Play services: disabled - 20.1.04 (120400-288960190)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (23,5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (23,5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (23,5 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (263,5 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Comment by moving-bits** [comment]
Yes, you are right - waypoints don't vanish if you are in "display cache" or "display list" mode. It works, though, if you are in "live map" mode (with either "live map" enabled or not).

That's one of the inconsistencies we currently have regarding map display, see #8102 for a related example.

IMHO we need some discussion of what map parameters are influenced by the map mode, some straightening between the different map sources, and a proper documentation.

**Comment by MagpieFourtyTwo** [comment]
Ok - but this coherence can of course not be seen by the user.
Nevertheless: Why does it not "just" work in "display cache" mode?
If so, it could possibly be at least a temporary workaround for this extremely annoying "Show all WPs at a glance" stuff (#8112).

But, wait, just tried to verify your statement by enabling "Map update" (i. e. "Live map") in the example shown in the screenshot above ... but the WPs are still shown ... even zooming out and in does not make a difference, they are still (re)displayed ... have I still misunderstood the intention of these options?

**Comment by moving-bits** [comment]
> But, wait, just tried to verify your statement by enabling "Map update" (i. e. "Live map") in the example shown in the screenshot above ... but the WPs are still shown ... even zooming out and in does not make a difference, they are still (re)displayed ... have I still misunderstood the intention of these options?

That had worked. As soon as the switch is set to "hide xxx" the waypoints matching that got filtered out. Also when opening the map with switches already set.

What is the exact setting you're testing? Are the caches which still display waypoints that should be filtered out coming from stored caches or are they loaded dynamically through live map?

**Comment by MagpieFourtyTwo** [comment]
As we're talking about e. g. "visited waypoints" the caches *have* to be saved offline, right? ;)

**Comment by moving-bits** [comment]
Hm, cannot reproduce: I've a cache with a couple of waypoints, some of them visited, some not. In "live map" mode, with either live enabled or disabled, the visited waypoints toggle instantly with toggling the "hide visited" menu item. Also, it acts accordingly when opening the live map.

Did you open the map from c:geo main menu, using the button "live map"? (That's the mode I'm referring to.)

**Comment by MagpieFourtyTwo** [comment]
Nop ...

> by enabling "Map update" (i. e. "Live map") in the example shown in the screenshot above

In detail:
1. opened listing page
2. clicked on compass rose to open cache map
3. menu -> "Enable map update"
4. menu -> "[X] Hide <whatever>"
5. nothing happens

While doing 4. and 5. after using "Live Map" button on start page to enter map, it indeed seems to work.

So, there is even a difference between "Initially started" and "Subsequently activated" Live Map ...?

Sorry, but which "normal" user will ever understand that the way, he entered a scenario, decides between "Works" and "Does not" ...? Esp. in times of WYSIWYG resp. well defined, consistent GUIs? Even worse, when seen from the point of programming: Functions, modules and libs (not to speak of inheritance) are standard for ages, and they are for a very good reason. But over here it seems as if every single menu entry does his stuff on it's own ... to be honest: I'm a little bit surprised ... or in fact shocked ...

**Comment by moving-bits** [comment]
> In detail:
> 1. opened listing page
> 2. clicked on compass rose to open cache map

you're in cache map now

> 3. menu -> "Enable map update"

that does not change it, you're still in cache map, not in live map

> 4. menu -> "[X] Hide "
> 5. nothing happens

That's expected behavior, then, as you're still in cache map.

> While doing 4. and 5. after using "Live Map" button on start page to enter map, it indeed seems to work.

Ok, that's good to hear. Thanks for testing.


> So, there is even a difference between "Initially started" and "Subsequently activated" Live Map ...?
> Sorry, but which "normal" user will ever understand that the way, he entered a scenario, decides between "Works" and "Does not" ...? 

It's actually quite easy to see which map type you're currently in:
- Coming from c:geo main menu you enter the so called "live map" (with or without map update),
- coming from a single cache you'll enter "cache map" (with or without map update), and
- coming from a cache list you'll enter "list map" (no official terms).

In the heading above the map, you can always see which map mode you're in:
- "live map" has a heading of "map" or "live map", depending on whether map update is enabled or not;
- "cache map" shows the cache's name, and
- "list map" shows the list's name as heading.

It's actually the same map implementation in all three cases, but depending on the map mode there are some differences in details. Maybe those need to be documented more clearly. One example is that currently all map modes list all hide functions, although they are not active in all modes (this is #8102) - that needs to be decided on whether to either implement them for all modes, make them configurable, or correct the menu items' visibility.

Further inconsistencies come from two different technical implementations we have for "Google Maps v2" / "Mapsforge old" vs. "Mapsforge new" due to technical and historical reasons. Bad enough for technical and resource reasons, but the consequences nevertheless need to be straightened out. Documentation process for this has been started, but fixing will take some time.

> Esp. in times of WYSIWYG resp. well defined, consistent GUIs? Even worse, when seen from the point of programming: Functions, modules and libs (not to speak of inheritance) are standard for ages, and they are for a very good reason. But over here it seems as if every single menu entry does his stuff on it's own ... to be honest: I'm a little bit surprised ... or in fact shocked ...

It's a bit different, as explained above. Without diving too much into the details of c:geo's architecture: c:geo of course is modularized, uses inheritance etc. Please have a look at the source first before making such generalizations. OTOH it's an open source project nearly ten years old, having seen many different developers donating their time to bring c:geo forward. It's very hard to keep c:geo as consistent as it is today, with all the team changes, technical advances and internal changes of the Android platform or the libraries involved throughout time. Having said that: If you have an background in software development, you're welcomed to join the team and add your experience to c:geo 👍

**Comment by MagpieFourtyTwo** [comment]
First of all: I of course did not want to belittle the work done with c:geo. I *highly* appreciate the work that has been (and will be) done to give this extremely helpful piece of software to us, Without c:geo the geocacher's universe would be a really poor one and in fact I'm not even sure if I would still cache at all without it. So, sorry for this misunderstanding and being not as clear as I had to be.

What I wanted to express is, that the approach in #8102 leads - at least as I have understood it - into a wrong direction: IMHO the efforts should not be invested into an increased (or "better") distinguishment between different types of Live Maps (whereas the main difference is the way to get to them), thus driving it's versions even more apart than they are anyway right now, but to unify them, thus using the same Live Map, from wherever the user may have come to it.

IMHO this should be seen more from the normal end user's perspective: He just sees a map, titled "Live Map" - and that's it. And as soon as you see a specific window title, you of course expect the well known and usually used functionality, wherever you meet it. And it is not just hard to explain, but even harder to understand (as an end user), why this may not be the case, and, even worse: the end user does not even care for these differences. He sees "Live Map" and expects a "Live Map".

Just put yourself into "his" position: For example open a Word document from an empty instance, thus starting the program from it's icon, then "File" -> "Open" -> and chose whatever docx, docm, dotx or dotm file ... This should be compared to starting c:geo from scratch, then open "Live Map" via dedicated button ... and the Hide menu is fully loaded.

But then, when you open c:geo, open a cache listing, display it on the map, activate "Live Map" ... and suddenly the Hide menu does not work as expected ... or offers just half of the options. That would be as if you can not open any .docm files in Word any more, just because you first opened a .docx file ... the problem: There is no obvious reason for this limit.

c:geo already has some of these "hard to understand" limitations, like e. g. opening the cache's map via a waypoints compass rose and suddenly not being able to set an add. waypoint on map anymore (although you still are in a well defined cache context), or having no "Activate Live Map" in the very same context. Or ... and even more special scenarios make the program harder to use.

To make a long story short: I would suggest to not create more of these hard to understand special scenarios, but effort should be trying to decrease the number of existing scenarios, thus using existing ones, as the end user will not be able to understand them. Apart from that different ones are usually harder to maintain, anyway.

So, when e. g. activating map update, I would prefer a solution where c:geo "just" switches back to the already existing function(ality) of the "normal" Live Map, with "just" keeping the route to the previously active cache, instead of creating a special Live Map scenario ... 

I hope my point went out clearer now ...  ;)

**Comment by MagpieFourtyTwo** [comment]
> In the heading above the map, you can always see which map mode you're in:
>     * "live map" has a heading of "map" or "live map", depending on whether map update is enabled or not;
>     * "cache map" shows the cache's name, and
>     * "list map" shows the list's name as heading.

Nop, I can't - at least not in the German version, where it is always betitled as "Live.Karte", as soon as I activate map update. And I can't see how it looks like in English, cause the setting "In English" (still?) doesn't work.

Or have I got s/th wrong?

**Comment by moving-bits** [comment]
> > In the heading above the map, you can always see which map mode you're in:
> > * "live map" has a heading of "map" or "live map", depending on whether map update is enabled or not;
> > * "cache map" shows the cache's name, and
> > * "list map" shows the list's name as heading.
> 
> Nop, I can't - at least not in the German version, where it is always betitled as "Live-Karte", as soon as I activate map update. And I can't see how it looks like in English, cause the setting "In English" (still?) doesn't work.

My bad - didn't know that title switches to "live map" even when coming from cache map. (Need to recheck in the emulator, though, don't think I've seen that before, but I can reproduce it now on a physical system.)

**Comment by moving-bits** [comment]
> What I wanted to express is, that the approach in #8102 possibly leads - at least as I have understood it - into a wrong direction:

#8102 is meant as a reminder to make the UI more consistent - available menu entries should do what they say. It's driving me nuts (sometimes) to have visible menu entries not doing anything.


But your point is very valid - I don't see a reason to not offer waypoint filtering in the other map modes as well. I gave it a first try, see #8128.

**Comment by MagpieFourtyTwo** [comment]
Seems as if this one can be closed (tested in latest nightly, and it worked at least most of the times ;) had just one situation where it didn't but was not able to reproduce the failure - may be a variation of #7136, as it worked after closing and reopening the listing)
