### ISSUE TITLE
Branch conflict release -> master

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8130]
Hi all,

just returned from vacation I checked whats going on here.
According to Github `release` is 5 commits ahead of `master`, which means commits have been added to `release` (I assume some bugfixes which are explicitly targeted to `release`) but the `release` branch has not been merged upstream (into `master`) up to now.
While trying to do this I get a merge conflict, as the file has been edited meanwhile on `master`:
```CONFLICT (content): Merge conflict in main/res/xml/preferences.xml```

Could one of you please merge branches and resolve this conflict while doing this?

Please be reminded in future to short term merge `release` into `master` after you pushed changes to `release`.

**Comment by moving-bits** [comment]
I'll look into it

**Comment by moving-bits** [comment]
Closed with 72488e0
