### ISSUE TITLE
AS 3.6

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8141]
The AndroidStudio 3.6 is out.
It needs the gradle plugin 3.6.0.
And for this gradle has to updated at least to 5.6.4.

I think we should stay at the current AS 3.5.3 at least until the next c:geo release is released.

**Comment by moving-bits** [comment]
> I think we should stay at the current AS 3.5.3 at least until the next c:geo release is released.

@bekuno 
Do you expect (or experience) any problems with AS 3.6 if we would build another release based on current release branch? (Which might happen, as we have one fix already waiting on release, and #8157 in the pipeline.)

**Comment by moving-bits** [comment]
@bekuno 
Thanks for preparing #8161. I'm still at AS 3.5 currently, and my question above was whether it's safe already to switch to AS 3.6? (As in the past I frequently had minor problems for  the first weeks after each major AS release.)
So do I understand you correctly that you successfully switched to 3.6, still being able to prepare builds for release branch?

**Comment by bekuno** [comment]
@moving-bits I work with AS 3.6. For release we need at least the changes in PR #8161. The change for master update gradle to 6.2.2 and has for it further changes.

**Comment by moving-bits** [comment]
Thanks @bekuno for clarifying - will try to upgrade my local environment then.
