### ISSUE TITLE
Doublecheck if ZZ0 cache should get coords on creation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8142]
As recently discussed with @moving-bits while meeting at an event:

Assigning coords to the ZZ0 cache will make a virtual cache icon appear on the live map at this location.
As to my experience on the support channels I guess we will have many users wondering about such an icon suddenly appearing.

IMHO it only clutters the map and has no additional benefit.
We should revisit the previous situation and check again what to do.
I do not deem it mandatory to have an option available to show all GoTo targets on the map. You still always have the option to map each waypoint.

**Comment by moving-bits** [comment]
I cross checked: Without getting default coords applied, the cache detail page lacks map functions (as there aren't any cache coordinates to deal with):

![image](https://user-images.githubusercontent.com/3754370/75633261-afa98080-5c03-11ea-8b6b-6056bd06999b.png)

But on the waypoints page you still have the navigation rose available for each single waypoint:

![image](https://user-images.githubusercontent.com/3754370/75633271-cea81280-5c03-11ea-9576-c5dba8c325bc.png)

AFAICS no "ghost cache" (= UDC) appears, but couldn't test all conditions, as c:geo still displays my 6000 deleted test caches... (just without the "saved" icon)

So you only lack the function to map all waypoints - which is ok for the "history cache", IMHO. I'll create a PR, targeted to release.
