### ISSUE TITLE
Solved mysteries jumping on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8146]
Reported for current RC version 2010.02.24-RC

Bug:
Solved unknown caches, with changed coordinates jump from the old coordinate to the new coordinate on the map when scrolling and panning.

Comment: 
I asked the user for permission to post his screengrab here. 

--- System information ---
Device: SM-A405FN (a40eea, samsung)
Android version: 9
Android build: PPR1.180610.011.A405FNXXU3ATA4
c:geo version: 2020.02.24-RC
Google Play services: enabled - 20.04.14 (100408-294335909)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
HW acceleration: enabled (default state)
System language: nl_NL
System date format: dd-MM-yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (27,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (27,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (27,2 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (2,3 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins:  none
--- End of system information ---

**Comment by Lineflyer** [comment]
Video of the problem:
https://files.droescher.eu/public/20200229_093613.mp4

**Comment by Lineflyer** [comment]
Looking at this video I do miss the "final flag overlay" being shown.
So I suspect, the saved caches are modified in another way or by another tool (e.g. GSAK) just replacing the listing coords by different ones, thus leading to a "data conflict" between coords coming in from live map and our internal database?!

**Comment by jakedot** [comment]
Could this be related? https://github.com/cgeo/cgeo/issues/8126#issuecomment-593132615

**Comment by Lineflyer** [comment]
This should implicitly be solved by the change to make use of the modified coords delivered by the live map interface to gc.com. So there should no longer be a difference in coordinates between saved caches with modified coords and the coords delivered by the live map for the same caches (making them jump).
