### ISSUE TITLE
Automatically upload offline logs when an unmetered network becomes available

### ISSUE THREAD

**Issue by jonas-koeritz** [cgeo/cgeo#8147]
This would be a nice addition for people that do not have mobile data. Could be implemented very cleanly using WorkManager.

**Comment by Lineflyer** [comment]
See #1786 for a list of obstacles and things to be considered. Mainly its a duplicate.

**Comment by jonas-koeritz** [comment]
Thanks for pointing that out. This could be closed then I think? Or keep it as an additional feature for #1786?

**Comment by Lineflyer** [comment]
We can use #1786. Its the same feature I think.

**Comment by fm-sys** [comment]
I think we shouldn't go for such a feature because many people use offline logs for quickly mark caches as found and to write the full log text later

**Comment by jonas-koeritz** [comment]
I will close this for now. There are valid points to be cleared up beforehand, and It might be possible to revisit this in the future, maybe differentiating between "found, write later" and "found, no network to log instantly" could be an option.
