### ISSUE TITLE
Support other OSM based online map sources

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8148]
WhereYouGo supports more tile severs then only what we called "OSM:Mapnik":

- OSM:Mapnik
- OSM.de
- CyclOSM (could be a good replacement of the retired OpenCycleMap)
- Public Transport
- Esri world street
- Esri world Imagery (alternative to Google Satellite)

Tile source info can be found in cgeo/WhereYouGo code.

I have no idea whether these tile sources can really be freely used, but if this is the case we should support those (or a subset) also in c:geo.

**Comment by moving-bits** [comment]
CyclOSM is available under a "fairuse tile policy":
https://operations.osmfoundation.org/policies/tiles/
linked from https://www.cyclosm.org

**Comment by moving-bits** [comment]
> https://operations.osmfoundation.org/policies/tiles/

That's the same policy openstreetmap.de is linking to.

**Comment by moving-bits** [comment]
Wikimedia is also providing (limited) access free of charge:
https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use

**Comment by moving-bits** [comment]
Thunderforest is providing several different themes (transport, landscape, outdoors, and more), but their free service is way too limited for us, see https://www.thunderforest.com/pricing/ - would be feasible only, if every user open its own account (if at all).

**Comment by SammysHP** [comment]
Thunderforest maps were removed in the past because with more than one million tiles per day we couldn't afford the licensing costs. I don't think there's any other source free of charge for us except openstreetmap.org Carto (as long as they allow us).

The OpenStreetMap ecosystem got very popular in the last few years and times where tiles could be used for free are over. Google provides free access to promote their maps in Android. But apart from that any major project will have to pay at some time.

**Comment by jakedot** [comment]
maybe we could add a hint that these maps are not free and ask for donations?

**Comment by SammysHP** [comment]
I think 400 $ per month and per map is a common price. Also we would have to drop a map immediately if we don't collect enough donation for a month. No, that's not possible with a free app.

**Comment by jonas-koeritz** [comment]
Optimal solution would be our own tile server. I have the computing power available without any doubts but the bandwidth would be impossible to provide from that location. Maybe after clearing up our local caching problems we could ask a tile provider for a good deal. Better caching will definitely cut our bandwidth by a huge margin.
