### ISSUE TITLE
Arrow on google map not rotating

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8150]
**Describe the bug:**
Since version 2020.03.07 (where we introduced the rotating google map) some users claim, that the arrow on map does no longer rotate

**To Reproduce:**
- Switch off rotating maps (the affected users don't use this feature)
- Open live map with Google maps
- Rotate the device slowly

**Actual behavior/state after performing these steps:**
The arrow always points to a stationary direction on the map (seems not the identical direction for all affected users) and does not follow the device rotation.
When users switch to OSM the arrow rotation is OK.

**Expected behavior/state after performing these steps:**
The arrow should follow the device rotation/orientation

**Version of c:geo used:**
2020.03.07

**Is the problem reproducible:**
No, I can't reproduce on my device. Not sure what prerequisites are needed to have this problem.

**System information:**
Will try to get more detail, but does not seem clearly related to a certain device type or Android version.

**Additional context:**
@moving-bits AFAIR you changed something in this part, due to my problem, that the arrow does not show conclusive direction while the map is rotating. Maybe we should revert and go back to the old code at this place (as we never had such issues reported before).

**Comment by moving-bits** [comment]
> @moving-bits AFAIR you changed something in this part, due to my problem, that the arrow does not show conclusive direction while the map is rotating. Maybe we should revert and go back to the old code at this place (as we never had such issues reported before).

@Lineflyer 
You mean #8031? I could either revert this or write a PR that uses the new code if auto map rotation is enabled, and the old one, if not.

**Comment by Lineflyer** [comment]
> @Lineflyer
You mean #8031? I could either revert this or write a PR that uses the new code if auto map rotation is enabled, and the old one, if not.

I guess, thats the one I suspect to be the problem.
I suggest to revert completely (via `release`) and test again how it behaves with rotation and reevaluate whether changes are needed. My last test was only done in a hurry and one few/one device(s).
