### ISSUE TITLE
Maps keeps rotating endless on device without needed sensors

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8151]
**Describe the bug:**
A user reported, that on his device (which does not facilitate a magnetometer) the rotating map (when activated) keeps rotating endless.

**To Reproduce:**
1. Enable rotation feature
2. Open live map with Google maps

**Actual behavior/state after performing these steps:**
Either it moves randomly or it starts rotating in one direction and keeps rotating forever.

**Expected behavior/state after performing these steps:**
Feature should be disabled for devices without the needed HW

**Version of c:geo used:**
2020.03.07

**Is the problem reproducible:**
Yes, for this user on his device

**System information:**
```
--- System information ---
Device: SM-J330G (j3y17ltedx, samsung)
Android version: 9
Android build: PPR1.180610.011.J330GDXU3CSL1
c:geo version: 2020.02.24-RC
Google Play services: enabled - 20.04.14 (100306-294335909)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
HW acceleration: enabled (default state)
System language: nl_NL
System date format: dd-MM-yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (1,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1,2 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (91,8 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
Geocaching.com date format: dd/MMM/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Additional context:**

**Comment by moving-bits** [comment]
Which sensors would be responsible in this case - Orientation and Magnetometer?

What would be the expected reaction if both are not present?
- If maprotation is set to auto
  - re-set to manual
  - display an info
- Disable the menu entry Map rotation => auto

?

**Comment by Lineflyer** [comment]
> Disable the menu entry Map rotation => auto

I guess disabling the entry would be the way to go.
This is a rare case, so do not spend any additional effort with dialogs, etc.

If a user contacts support, we can easily identify the reason by looking into the sys info.

Regarding which sensors are needed for the map to rotate properly...I don't know.

**Comment by moving-bits** [comment]
> This is a rare case, so do not spend any additional effort with dialogs, etc.

If it's a rare case, and with the new easy-to-reach rotation settings: Do we need to do anything at all?

**Comment by Lineflyer** [comment]
I would totally agree if the rotation could somehow be disabled using that on-map compass rose. 
Believe me...on support channel we have quite some mails where people want to stop it but don't find how to do it.
I guess this is mainly due to the fact that our google map looks like the maps app but misses exactly that feature. 
Sure, that this is not somehow possible with their library to facilitate the compass rose for this?

**Comment by moving-bits** [comment]
Ok, understood. AFAICS from the docs there is no official way to detect a tap on the compass rose, but there are some suggestions on SO how to indirectly detect it, which we could try.

But we need to decide then under what conditions a tap on the compass rose should trigger deactivating the automatic rotation (and whether it should do so with or without confirmation dialog and/or toast message). Obviously, one condition would be that rotation mode is set to auto.

**Comment by Lineflyer** [comment]
I have no good idea...I really thought the map itself could somehow support it. Whatever we try manually will potentially interfere with the default function of the compass rose.

I will take a look how other apps solve this.

**Comment by moving-bits** [comment]
Let's close here, as a sufficient workaround exists.

**Comment by Lineflyer** [comment]
We should at least have some open issue to remember the "To Do" that the GMaps rotation does not work correctly. But I think we have one, where I also linked a video I did with a comparison of Locus and c:geo.
