### ISSUE TITLE
irclogs are empty

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8160]
Normally IRC logs builds being processed, and also you can find the names of persons entering / leaving the channel in the log, but starting from March 27 the logs are empty. Connection lost?

**Comment by SammysHP** [comment]
Bot restarted. Not much lost, though. There were no discussions on IRC for months.

I'd also like to switch off the bot, but we can host it somewhere else if you want. The source code is ancient and has lots of old dependencies. And it runs in a JVM.

**Comment by moving-bits** [comment]
Thanks for restarting.
