### ISSUE TITLE
Errors on CI also when final "SUCCESS" result

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8165]
~~~
> Task :main:minifyBasicDebugWithR8
R8: Missing class: java.lang.instrument.ClassFileTransformer

> Task :main:shrinkBasicDebugRes
> Task :main:packageBasicDebug
[adb]: process hasn't exited

> Task :main:installBasicDebug FAILED

... 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:installBasicDebug'.
> com.android.builder.testing.api.DeviceException: Could not create ADB Bridge. ADB location: /opt/android-sdk-linux/platform-tools/adb
~~~

**Comment by bekuno** [comment]
The problem comes from
~~~
[adb]: process hasn't exited
~~~

The problem is on cgeo-3

**Comment by Lineflyer** [comment]
@mucek4 What needs to be done if ADB/emulator fails on one of the slaves?

**Comment by mucek4** [comment]
When we added 2 libraries to CI for whereyougo it failed to start emulator. Therefore 3 is not running emulators and 4 and 5 are running old Docker Image. I think I asked @kumy to look at it.
c:geo build shall not run on emulator 3

**Comment by Lineflyer** [comment]
OK, I set the option to reserve "cgeo-3" exclusively for bound projects. So I guess cgeo-3 should now no longer be used for cgeo CI-builds although it has the attribute "has-emulator".

**Comment by Lineflyer** [comment]
See: https://github.com/cgeo/cgeo-executor/issues/15
