### ISSUE TITLE
Logging with photo upload still broken for gc.com

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8172]
It seems I have missed testing an important scenario:

Users of the new 2020.03.30 report that while logging works in general it still fails if a photo shall be attached.

@jgoestl

**Comment by jgoestl** [comment]
I'll have a look

**Comment by WeinWalker** [comment]
Since last update, the one that solved the trackable issue

**Comment by jgoestl** [comment]
I tested it and photo upload with 2020.03.30  is working fine.

@Lineflyer can you reproduce this?

**Comment by Lineflyer** [comment]
No, for me it works. Thats why I set unverified label.

@WeinWalker Can you reproduce this?

**Comment by moving-bits** [comment]
Cannot reproduce so far. What part of logging fails? Uploading image or acquiring the image before uploading? If the latter: new or existing image? Can we get a LogCat?

**Comment by Lineflyer** [comment]
I reached out to the three users, who contacted our support mail and asked for details. Lets see.
One already noted, that the log is send OK but the picture is not attached to the log on the website.

**Comment by moving-bits** [comment]
> I reached out to the three users, who contacted our support mail and asked for details. Lets see.

Thanks

> One already noted, that the log is send OK but the picture is not attached to the log on the website.

Seems to be some special circumstances required. During my tests with the emulator log pic has been attached and was visible on the website.

**Comment by Lineflyer** [comment]
All three users reported back, that it works now.
So kind of false alarm or a temporary problem on the server side.

**Comment by moving-bits** [comment]
@Lineflyer  Thanks for cross-checking
