### ISSUE TITLE
Some strings should not be included for translation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8206]
Some strings do not need a localization or should not be localized to avoid confusion.

Examples:
- Proper names of apps/tools like "Pocket Query Creator" , "Locus"
- Fixed names like "carnero" and "c:geo"

As discussed in #3601 those should be moved from `strings.xml` to `strings_not_translatable.xml` and attributed with `translatable=false` in this file to have a clear distinction.

There might be other strings, where we should discuss whether or not to localize:
- Units, e.g. "m", "km", "ft", "yd", "512px", etc
  Those might still be different at least if the characters are different (e.g. greek, cyrillic), or not?
- Cache sizes, e.g. "Small", "Regular"
  AFAIR we discussed to keep them in english, however now I think while in German the English descriptions might be commonly used, in other languages it might be different?

Remark:
Up to now this translation blocking was done on Crowdin by manually hiding some strings. Due to the new integration this list was implicitly reset and not reinitialized up to now as it should be solved in the source rather than in the tool.

I leave this issue up to someone else, until I might find time to make a proposal.
You probably have the better tools to sort these items, I would do it with an editor only.

**Comment by moving-bits** [comment]
I'll start with it.

We have a lot of strings containing website or product names, e. g. `Export to Locus`. Those will probably have to stay in the "to be translated" section, right?

**Comment by Lineflyer** [comment]
> We have a lot of strings containing website or product names, e. g. Export to Locus. Those will probably have to stay in the "to be translated" section, right?

Yes, those should stay in the translation.
I will also add glossary terms on Crowdin for such proper names, stating that they should stay untouched as part of the string.

**Comment by Lineflyer** [comment]
The corresponding PR #8211 has been merged. Thanks to @moving-bits 

I will keep this open to monitor the next push from Crowdin, which should reflect those changes.

**Comment by Lineflyer** [comment]
Changes came back via Crowdin. LGTM.
