### ISSUE TITLE
Publish new contacts add-on release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8215]
Reminder to myself:
Publish a new contacts release, due to new translations

**Comment by bekuno** [comment]
Currently the language list is the same as in c:geo. But we have the translations not in all languages done. It's not easy at crowdin to see the tranlation state for an dedicated file.
What do we want here?

**Comment by Lineflyer** [comment]
You can see the progress of each file on Crowdin by going to Settings - Files, then three-dot menu - Progress.

**Comment by bekuno** [comment]
> 
> 
> You can see the progress of each file on Crowdin by going to Settings - Files, then three-dot menu - Progress.

Fine, very hidden.
12 of 32 languages are greater than 50%. We should wait a while, I would say.

**Comment by Lineflyer** [comment]
Meanwhile translation has good progress.
Shall we release a new contacts plugin version before merging #8832 ?
@bekuno

**Comment by Lineflyer** [comment]
I assume we could release a version of the plugin now.
Long term goal (or the goal after the release) could be to reintegrate it into the main app....unless someone is willing to reintegrate now?!

**Comment by bekuno** [comment]
The alowed translations in the plugin are the same as in c:geo with now the aditional language "zh-rTW".
But the languages and translation state differs between both.
Should we change this and integrate only languages with min ~50% translation in the plugin or leave that as is? 

I would implement the reintegration, but not now.
(We need also changes in the name selection gc/oc on this point and the cgeo authorization code needs some work.)

**Comment by Lineflyer** [comment]
@bekuno 
I guess we have no need to have dedicated language inclusion setting for the contacts-plugin.

I will just test and publish an update next days with the translation state we have, as AFAICS all prerequisites are OK.

**Comment by bekuno** [comment]
replaced by #15208
