### ISSUE TITLE
Open images from the image-tab in an extra instance

### ISSUE THREAD

**Issue by Narrat** [cgeo/cgeo#8217]
**Is your feature request related to a problem?**
I hope the title is halfway clear. If not I hope the following text makes it clearer :D But I'm not really firm with the Android specific expressions for those features which makes it kinda difficult. So please bear with me :)
There is one point, which kinda annoys me (at least in the way I'm using the app). If there is an image added, it will be listed in the image-tab. A simple short tap on this picture will result in c:geo displaying the picture via the default image-viewer, but embedded within c:geo.
So I can either look at the picture or navigate/do whatever. 
Or I would need to find the location where those pictures are stored.

**Describe the solution you'd like**
Dunno if it is easily achievable, but the way URLs are treated would make me happy. As tapping on an URL (or the long-press action on a image and choose "Open in browser") will result in an extra instance of said browser and it is possible to switch between c:geo and the browser.
The solution via open the image in the web-browser is not everytime a solution, as I'm regulary without reception :D

**Comment by moving-bits** [comment]
I have this (sometimes annoying) behavior on my mobile as well, so I started investigating a bit today:

This seems to depend on the image viewing app: In the emulator I tested this with, Google Photo and FX file explorer come up when I tap on an image from the images pane of cache details, but they behave differently:
- FX explorer opens the image separately (I'm able using the task view button to return to c:geo without closing the image),
- whereas Google Photo opens it within the c:geo process (no separate window).

(I can switch between c:geo and FX explorer processes, but as soon as I open a different image from c:geo, display in FX explorer switches at once, so even there it's not really a separate instance.)

Up to now I haven't found a flag or something to control this behavior.

Source is in `ui/ImagesList:viewImageInStandardApp()`, if someone wants to investigate further.

**Comment by Lineflyer** [comment]
Dont be that fast with fixing:
I dont really get the exact problem here.

Please note, that there is already a long press option with some possibilities to trigger external apps.

@moving-bits Not sure whats in your fixing commit, but did you see that options already in place?

**Comment by moving-bits** [comment]
> I dont really get the exact problem here.

Problem is, that depending on the app you use for displaying images, the image is either displayed in a new process or not. If it's displayed in the same process, you cannot switch back to c:geo without closing the image.

> Please note, that there is already a long press option with some possibilities to trigger external apps.
> 
> @moving-bits Not sure whats in your fixing commit, but did you see that options already in place?

I haven't introduced any new UI behavior, just added the flag for the (already existing) intent to start that intent as a new task.

**Comment by Narrat** [comment]
Some pictures, which I should have posted while creating the first post:
![Screenshot_20200502-201331](https://user-images.githubusercontent.com/2787518/80872974-ac8b4900-8cb5-11ea-8419-9b724ae7ea61.png) versus ![Screenshot_20200502-202950](https://user-images.githubusercontent.com/2787518/80872981-b7de7480-8cb5-11ea-9939-acd7f6ef79bf.png)

And as I wrote in the initial post, the second option via open with browser cannot be used everytime as a workaround as it loads the url.
But great, that this inconsistent behaviour is fixable :)
