### ISSUE TITLE
Add new "Goto" waypoints at top of the list

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#8219]
**Is your feature request related to a problem?**
The new "Add current location" makes adding new waypoints to the "Goto" screen much easier, but the newly added waypoint always goes at the bottom of the list so you have to scroll all the way down to see it.

**Describe the solution you'd like**
The new waypoint should appear first, either by naming them suitably (Maybe using date/time?) or by sorting the list in a different order. 
(Mine currently go in a very strange order - Reference point 5,4,3,2,1,6,7,8,9.....etc. )

**Additional context**
Also, it would be nice to be able to "Delete all" waypoints, or maybe delete some of them using the "Select mode" feature that appears in other lists in cgeo.

**Comment by moving-bits** [comment]
Currently waypoints have a fixed order in which they are displayed (see `models/Waypoint:WAYPOINT_COMPARATOR` and `enumerations/WaypointType`):

parking: -1
trailhead: 1
puzzle, stage, waypoint:reference point: 2
final: 3
original: 4
own:reference point: 5

They are sorted from low to high according to above order (parking first, then trailhead etc.), with no specific sorting within each group.

We should discuss if we want to introduce a new comparator for the "goto" page (aka "goto history UDC").

**Comment by moving-bits** [comment]
> **Additional context**
> Also, it would be nice to be able to "Delete all" waypoints, or maybe delete some of them using the "Select mode" feature that appears in other lists in cgeo.

Please add a separate issue for that - makes tracking and discussion easier. Thx.

**Comment by jakedot** [comment]
> We should discuss if we want to introduce a new comparator for the "goto" page (aka "goto history UDC").

Is there a defined order for the waypoints from geocaching.com? They could be sorted by their codes, couldn't they?

**Comment by moving-bits** [comment]
> Is there a defined order for the waypoints from geocaching.com? They could be sorted by their codes, couldn't they?

I'm not sure, and I couldn't find any documentation on this. It even looks like you cannot enter prefix and lookup codes anymore when creating a new cache.

A different approach for the "goto history UDC" might be to simply sort them by internal id descending, under the assumption that newly created waypoints get a higher internal id, thus having all new waypoints at the top of the list. (Needs to be verifyed.)

**Comment by moving-bits** [comment]
> A different approach for the "goto history UDC" might be to simply sort them by internal id descending, under the assumption that newly created waypoints get a higher internal id, thus having all new waypoints at the top of the list.

see PR #8229

**Comment by moving-bits** [comment]
Closed with #8229
