### ISSUE TITLE
Provide a way to delete all waypoints on the "Goto" page.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#8224]
**Is your feature request related to a problem?**
I'd like to be able to remove all (or a large subset) of the waypoints on the "Goto" page.

**Describe the solution you'd like**
An option to "Delete all" waypoints, or maybe delete some of them using the "Select mode" feature that appears in other lists in cgeo.

**Comment by moving-bits** [comment]
Closed with #8232
