### ISSUE TITLE
Live map sending too many calls to gc.com

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8225]
It seems our current live map implementation does send too many calls to gc.com, respectively it also sends requests in situations where no request might be needed.
If we can do anything to minimize this, we should do so.

For details please refer to internal mail on our cgeo-dev mailing list.

Despite having a beta feature release out just now, we could also easily revert release branch to the last release status and apply any fix on top of that. That would also be my proposal, otherwise we would be forced to publish a new feature release rather untested.

If you agree, I would revert `release` branch back to the status before fast-forwarding in a first step, so we can apply a patch on it.

Any idea, where this problem might come from?

**Comment by jonas-koeritz** [comment]
Can somebody verify if this is the case for both the OSM and the Google Live Map?
We could fix this by requesting bigger regions at once and make the map query less often.

This is something I have worked on before while implementing the Room stuff.
Better caching of Geocaches would also cut down on data usage as well.

One of the problems is that the current DataStore and CacheCache stuff doesn't work as a single source of truth for the app. So many components just write to the database without caring for any side effects.

**Comment by jonas-koeritz** [comment]
The problem might be caused by the use of timers to check for a moved map, there might be cases where the map has "moved" when it really didn't move at all. Maybe Google Maps rotation is a problem as well? Auto rotation might trigger lots of reloads.

**Comment by jonas-koeritz** [comment]
As a short term solution we could just implement rate limiting and make the "map moved" code more generous.
Mid to long term it could be possible to check if we already have complete data for a region in cache and not load it at all, this would require some changes to the Backend and how we handle cache loading and stuff.

A possible hard-cut could be made by disabling the live feature completely until we have come up with a really good solution.

**Comment by Lineflyer** [comment]
I think a combination of 
- more generous move map check
- disable rotation

could be a first quick step.

I will try to find time tonight to check whether I can see anything obvious going wrong by doing some tests.

**Comment by Lineflyer** [comment]
> If you agree, I would revert release branch back to the status before fast-forwarding in a first step, so we can apply a patch on it.

That will not be so easy, as AFAIK the database version changed and the beta version is already out. So we would potentially crash all beta users by publishing an upgrade which contains a db downgrade.

**Comment by bekuno** [comment]
we could also additionally
- save the possition and refresh only when changed more than 20% of screen 
- avoid refresh at zoom in

**Comment by Lineflyer** [comment]
Refresh on zoom in was important in the past where we had approximated coords. Nowadays this should be unnecessary. So if this is still the case it should be removed.

**Comment by moving-bits** [comment]
> > If you agree, I would revert release branch back to the status before fast-forwarding in a first step, so we can apply a patch on it.
> 
> That will not be so easy, as AFAIK the database version changed and the beta version is already out. So we would potentially crash all beta users by publishing an upgrade which contains a db downgrade.

It should be possible: After reverting release branch I can write a small routine for db downgrading (Android framework has standardized methods for this as well, not only for upgrading). The last two db changes consisted of adding a field to an existing table, and to add a new table - both of which could be reverted easily.

**Comment by moving-bits** [comment]
> disable rotation

If our boundary box for the search is large enough, it should be able to include a rotated map's area as well.

**Comment by moving-bits** [comment]
Some quick observations regarding `ConnectorFactory:searchByViewport()` (which ultimately calls `connector/gc/GCWebAPI:searchMap()`):

- it's called even when zooming in, although caches are already loaded
- GMv2 rotating map leads to multiple search calls
- slightly panning the map does NOT result in extra calls, so the search bounding box is already a little larger than the viewport, and this extra area is respected
- this extra factor is 1.2 for NewMap (`maps/mapsforge/v6/LiveCachesOverlay` and `maps/mapsforge/v6/StoredCachesOverlay`) but 0.8 for the old maps (`maps/CGeoMap`)? - don't understand why there's a difference, but both seem to work - haven't digged more deeply into this
- while panning across the whole map the search functions gets called multiple times (some timer?)
- when not moving the map, the function does NOT get called

**Comment by Lineflyer** [comment]
I did some tests on my Galaxy S4 (Android 5.0.1) running the current 2020.03.30 market release:

**First of all:**
They are applying the announced throttling already from server side by returning error 429 (too many requests) for subsequent requests within a short time frame. Live map loads, but after moving it might fail to populate in the first step but only on next user interaction. 

The I collected some experience based on the comments above:

**Google Map Rotation Feature:**
Testcase:
- Enable rotation
- Zoom in to show a single cache
- Rotate the device slowly
- Monitor debug log

Result:
I do see requests going out nearly every second while rotating the device.
Even while not actively moving the device a small compass irritation already triggers another request.
As the rotation feature seems not working good on that device, I even managed somehow that the map constantly rotated sending endless requests like a load generator for the server...not good :(
--> We should fix that

** Zooming out / in:**
Testcase:
- Open Live Map (Google Map) on a fixed location
- Disable rotation
- Start zoomed in (e.g. 100m/unit)
- Zoom out one step by clicking "-"
- Monitor debug log
- Zoom out one step by clicking "-"
- Monitor debug log
- Zoom in one step by clcking "+"
- Monitor debug log
- Zoom in one step by clcking "+"
- Monitor debug log

Result:
Each zoom out triggers two(!) requests.
Each zoom in triggers one request.
--> Two requests on zooming out should be reduced to one request with appropriate coverage
--> Request on zoom in to an area already covered by previous requests in the same session should be avoided completely, as they don't carry new information

**Random exploring of the map:**
Testcase 1:
- Open Live Map (Google Map) with typical zoom (e.g. 1km/unit) to explore caches
- Monitor debug log
- Move the map to the right until the previous right edge is on the left edge
- Monitor debug log
- Move the map back to previous position
- Monitor debug log
- Move the map until the previous lower edge is on the upper edge
- Monitor debug log
- Move the map back to original position

Result:
Moving the map to the new position triggers two subsequent requests, moving the map back triggers again two subsequent requests 
--> Same problem principle as for zoom out / in (requesting data we have + two requests)

Testcase 2:
- Open Live Map (Google Map) with typical zoom (e.g. 1km/unit) to explore caches
- Continuously move the map in circles not covering any new map area over time
- Monitor the debug log

Result:
After several initial requests while starting the move there are no more new requests after some time.
--> Good so far, but it seems we could potentially reduce the amount of calls in general by requesting a larger area initially rather than only what is shown on the screen to avoid new expensive requests. I could imagine one request around the center coords of the map with a fixed huge area covered. 

---

So overall I think there is some potential for (hopefully) rather easy improvements, at least my results/conclusion could point out relevant sources of this problem. The root cause and solution however needs to be evaluated by people with more insights of the code.

My guess is that we should at first try:

1. To make each request cover a significantly larger area as we currently do. At the moment my feeling is it covers around 150% (an additional half screen in each direction). If so I suggest to raise this to 300% (two additional screens in each direction). This could implicitly solve a lot of the problems stated above.

2. I am nor sure if fixing 1. will fix the continuous requests on rotation. Else we should temporarily disable the rotation feature.

3. Not send a request on zoom in operation (that should be totally obsolete and a remainder of old needs).

**Comment by Lineflyer** [comment]
Addition with regard to the current state of `release` branch:
Lets just take the current state and fix on top of that.

I will take a look about the performance of the beta version on Google Play and if there is something suspicious we need to fix this as well.

**Comment by moving-bits** [comment]
I'm currently experimenting with the following approach:
- Don't resize search viewport in the calling maps (see above) but one step deeper in `ConnectorFactory:searchByViewport()`
- there: apply a viewport factor of 3 (as proposed by Lineflyer)
- cache the search result
- for every new search request: check, if the requested viewport (without resizing) is included completely in the cached viewport; if so: return the cached result

After some smoke testing this
- reduced the overall requests a lot
- no requests any more for zooming in
- no requests any more for rotating map
- no requests any more for panning half a screen up or down
Don't know though, what this caching means for memory consumption.

@Lineflyer  If I create a PR from that, would you be able (and have the time) to do a cross check along your testsuite?

**Comment by Lineflyer** [comment]
> @Lineflyer If I create a PR from that, would you be able (and have the time) to do a cross check along your testsuite?

Yes, I can test the PR build on the same device.

If you can (no idea of whats possible in the code), could we try just to apply a viewport factor in the current code? Or does that make no sense without further refactoring?

Maybe two PRs with minimum and optimum proposal (both based on `release`)?
Thanks for diving into this.

**Comment by bekuno** [comment]
> It should be possible: After reverting release branch I can write a small routine for db downgrading (Android framework has standardized methods for this as well, not only for upgrading). The last two db changes consisted of adding a field to an existing table, and to add a new table - both of which could be reverted easily.

What about the way in the other direction - add the both changes on release?

**Comment by Lineflyer** [comment]
> What about the way in the other direction - add the both changes on release?

For the moment I would like to keep it simple by just working on top of the beta.
I have no indication, that it shows significant problems in the field up to now besides one new issue I just created: #8226 . If this issue turns out to be a big trouble we can rethink it.

**Comment by moving-bits** [comment]
> Maybe two PRs with minimum and optimum proposal (both based on `release`)?

I've created two PR for that (#8227 and #8228), both playing with the viewport factor, #8227 additionally with caching.

Both do not yet address yet
- test suite (test viewport)
- search being called repeatedly during panning.

Also, both are for testing only, no "production ready" code.

**Comment by Lineflyer** [comment]
Tried the above test using OSM maps:
Seems to have very comparable results, so it does not (so much) depend on used map.

BTW:
I get "Unknown host" error for *.tile.openstreetmap.org. So OSM:Map is empty. Anyone else having this issue or just me.
DNS returns unknown host.

**Comment by Lineflyer** [comment]
> I've created two PR for that (#8227 and #8228), both playing with the viewport factor, #8227 additionally with caching.

Thanks, will take a look and comment in the respective PR.

**Comment by moving-bits** [comment]
> I get "Unknown host" error for *.tile.openstreetmap.org. So OSM:Map is empty. Anyone else having this issue or just me.
> DNS returns unknown host.

Currently same here, on emulator as well as with physical mobile or web browser. `tile.openstreetmap.org` already leads to DNS error. Haven't found any notice so far about changing their tile server.

**Comment by Lineflyer** [comment]
@moving-bits 

I would go into the next phase of testing by merging #8227 and #8231 and building another RC for my personal testing only. If that works as intended we go either go into another beta phase or push it out directlz for a quick first step to reduce the impact of this issue. 
Do you consider these PR ready for merging?

**Comment by Lineflyer** [comment]
> Currently same here, on emulator as well as with physical mobile or web browser. tile.openstreetmap.org already leads to DNS error. Haven't found any notice so far about changing their tile server.

It started working again...seems to be a temporary problem on their side.

**Comment by moving-bits** [comment]
> Do you consider these PR ready for merging?

#8231 is ready for merging (although I do not know if it fixes #8226 as I'm still unable to reproduce, so I'm only following SO advice here).

#8227 can be used for testing by you, but it's not ready for officially merging to release. There's some debug code in there which (hopefully) helps with testing, and I need to fix the test which checks the viewport.

**Comment by Lineflyer** [comment]
The main reason I would like to test it in a RC version is, that for these versions our CI will add the GMaps key so that I am able to test on that map. The PR builds on CI do not have a GMaps key :(.
Mmh...OK. I will try to test #8227 based on PR-build first to see if I still see any repetitive requests or some other problem. Then we will see, what to do next.

**Comment by Lineflyer** [comment]
Is it possible to write a unit test which checks requests to server (not) happening depending on dedicated different viewport changes?

**Comment by moving-bits** [comment]
I've updated the existing viewport tests to adapt to the automatically enlarged area and added some new tests to check if caching of searchresult works as expected.

**Comment by moving-bits** [comment]
> The main reason I would like to test it in a RC version is, that for these versions our CI will add the GMaps key so that I am able to test on that map. The PR builds on CI do not have a GMaps key :(.

You can build a RC from that, no problem. We only should remove some debug code before releasing the next final version.

**Comment by Lineflyer** [comment]
Done

**Comment by Lineflyer** [comment]
I tested #8227 with the RC version 2020.04.21-RC and some of the most urgent items seem fixed:
- No requests on rotation
- More "buffer" for scrolling around

In some situation the caching of viewport information might lead to the map only being loaded too late. I will investigate and open dedicated issue for this (=improvement of viewport caching, etc.).

Although the live map might have some bugs or not ideal solution, I still would like to get the release out rather soon as it reduces the amount of requests significantly, thus fixing this issue towards gc.com.

The fix provided by @moving-bits is IMHO enough to close this issue. As stated above I will open new issues for remaining problems next days.

**Comment by moving-bits** [comment]
> In some situation the caching of viewport information might lead to the map only being loaded too late. I will investigate and open dedicated issue for this (=improvement of viewport caching, etc.).

Easiest option would be to adjust the factor, if needed. Currently it's set to 300%, the old value was 120%, IIRC. Searching a large area in highly cache-populated areas might lead to incomplete results (due to the limit of 500 caches being returned), but let's see how the implemented workaround for this works.

> Although the live map might have some bugs or not ideal solution,

Like: Why is the search requested twice on zooming out - haven't looked for this so far. Currently this is catched indirectly by the enlarged viewport for search, but maybe we find the root cause of this.

> I still would like to get the release out rather soon as it reduces the amount of requests significantly, thus fixing this issue towards gc.com.

agreed

> As stated above I will open new issues for remaining problems next days.

Thanks for testing.

**Comment by Lineflyer** [comment]
Approx. 50% of sessions already run on 2020.04.25.
I will sent a final reply to Bryan....and request his feedback on the load.

Next days I will try to phrase new issues for the problem scenarios I still see.
