### ISSUE TITLE
Fieldnotes Textfile can't be imported to GSAK

### ISSUE THREAD

**Issue by winkamol** [cgeo/cgeo#8230]
After offline logging in cgeo I tried to load the textfile in GSAK and import the file. But it didn't work. I found a solution on the following page, but it would be nice not to have a workaround like this.
http://forum587.rssing.com/chan-16809329/all_p2060.html (see failure Code 307)

**To Reproduce:**
1. Verlauf
2. Exportieren
3. Fieldnotes

**Actual behavior/state after performing these steps:**
Describe the actual issue/problem/behavior in detail.
No import in GSAK available

**Expected behavior/state after performing these steps:**
Describe what you expected to happen instead.

**Version of c:geo used:**
You will find the c:geo version in c:geo Menu -> About c:geo
2020.04.15-RC

**Is the problem reproducible:**
Yes

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
--- System information ---
Device: SM-G955F (dream2ltexx, samsung)
Android version: 9
Android build: PPR1.180610.011.G955FXXS8DTC6
c:geo version: 2020.04.15-RC
Google Play services: enabled - 20.09.14 (100400-300565878)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (13,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (12,9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (12,9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1,0 GB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

**Comment by moving-bits** [comment]
Thanks for the additional infos.

Closing this issue as it's a duplicate of #7404.

**Comment by Lineflyer** [comment]
@winkamol 
Can you please check whether you can still reproduce the problem?

**Comment by winkamol** [comment]
Hallo Lars, 

ja ich erhalte folgenden Fehler in Gsak:

Es wurden keine Geocaches zum Abruf ausgewählt. 
Eventuell muss das Datum "Ignoriere..." angepasst werden. 

Fehler 307

⁣Viele Grüße

Patrick ​

**Comment by Lineflyer** [comment]
Verwendest du aktuell die c:geo Version 2020.07.02 oder die Beta-Version 2020.07.26-RC?

**Comment by winkamol** [comment]
Erstere Version vom 02.07.2020

⁣Viele Grüße

Patrick ​

**Comment by Lineflyer** [comment]
Vielleicht könntest du dich für das Beta-Programm von c:geo anmelden (Link: https://play.google.com/apps/testing/cgeo.geocaching ) und danach über Google Play einmal unsere neue Beta-Version ausprobieren. Es gab eine Änderung, die das Problem evtl. behoben haben könnte. Es würde uns sehr interessieren, ob es nun funktioniert.

**Comment by winkamol** [comment]
Hallo Lars, 

nein leider klappt es nicht, es erscheint der gleiche Fehlercode wie unten bei der Release Version von Anfang Juli. 
Dabei kommt mir eine Idee, die Fieldnotes zukünftig direkt an Gsak zu schicken. Ähnlich wie es möglich ist auf GC.com hoch zu laden könnte man eine Verbindung zu Gsak herstellen. 

⁣Viele Grüße

Patrick ​

**Comment by Lineflyer** [comment]
@winkamol 
We recently hopefully solved this issue and right now a beta version 2020.12.22-RC is available with this fix.
Can you give it a try ans report back?

Wir haben den Fehler hoffentlich behoben und es ist eine BetaVersion 2020.12.22-RC mit diesem Fix verfügbar.
Kannst du es probieren und rückmelden, ob es nun funktioniert?

**Comment by winkamol** [comment]
Hallo Lars, 

ich habe soeben das Update durchgeführt und werde es bei nächster Gelegenheit testen sowie eine Rückmeldung geben. 
Danke euch allen für die Mühe und tolle Arbeit, sowie vorab ein frohes Fest, einen guten Start in 2021 und bleibt gesund! 

⁣Viele Grüße

Patrick ​

**Comment by eddiemuc** [comment]
Short comment: the fix mentioned by @Lineflyer changed the file encoding from UTF-26 Big Endian to UTF-16 Little Endian. This is assumingly the "official" encoding used by gc.com when uploading the file (or so the community told me).
I don't know, however, which format is expected by GSAK. Standard windows encoding would be CP-1252 afaik.

**Comment by Lineflyer** [comment]
A beta user confimed that field note import from c:geo to GSAK is working again with 2020.12.22-RC.

**Comment by winkamol** [comment]
Hallo Lars, 

die Field Notes werden nun in GSAK eingelesen. Vielen Dank fürs Implementieren! 

⁣Gruß

Patrick ​
