### ISSUE TITLE
Make individual routing optional

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8235]
Some beta users contacted us as they accidentally triggered the new individual route function.
It seems some people do not distinguish between short and long click or just click to long on a cache on map.

The support reports contain things like:
- The popup is not opened but only the message "added to route"
- Sometimes when clicking a cache it says "added to route"

I believe only experienced users might want to use individual routing (and it only makes real sense if brouter is installed). For the broad user base we should avoid such accidental triggering of advanced feature. 

What to do? Make it opt-in or can we make the long press really long?

**Comment by moving-bits** [comment]
Let's make it optional like we did with the "create user cache" long tap on free map space.

**Comment by Lineflyer** [comment]
Fixed by #8236

**Comment by moving-bits** [comment]
@Lineflyer 
Do you have an idea why this issue didn't get auto-closed? #8236 has the "fix ..." in the title.

**Comment by Lineflyer** [comment]
Because only the PR title contained the fix keyword but as the PR was merged to `release` it did correctly not auto close at this point. While merging branches (already done) only the commits are analyzed for keywords as the PR is out of the game at this point.

Long story short:
To make it work you need to have the keyword in the commit message rather than or additonally to having it in the PR title.

**Comment by moving-bits** [comment]
Ok, thanks for clarifying. Will try to keep that in mind when preparing PR for `release`...
