### ISSUE TITLE
Better handling of newly created waypoints

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8239]
User feedback for 2020.04.21-RC:

The new add current location button works, however since we now have 40 saved go to locations formerly buried in other caches, it might be nice to have a little "waypoint created" note to let you know it completed the request. 

Also an option to arrange by alphabetical waypoint name or newest waypoint on top might also be nice to have to complement this new button.  It's a pain in all of cgeo when you have large numbers of saved waypoints to scroll all the way down to the bottom all the time.  I'd love a arrange newest to oldest button on all waypoint screens.

**Comment by moving-bits** [comment]
> Also an option to arrange by alphabetical waypoint name or newest waypoint on top might also be nice to have to complement this new button. It's a pain in all of cgeo when you have large numbers of saved waypoints to scroll all the way down to the bottom all the time. I'd love a arrange newest to oldest button on all waypoint screens.

We already have PR #8229 in the queue for the "go to" history as automatic sorting.

Adding an menu option "sort by newest on top" for all caches' waypoint page would be easy.

Implementing a sorting system similar to what we have in caches list is probably much more effort, but I'm not sure if that's really needed here.

**Comment by Lineflyer** [comment]
> We already have PR #8229 in the queue for the "go to" history as automatic sorting.

OK lets ignore this part then, as it is covered already.
So this issue remains with:

> The new add current location button works, however since we now have 40 saved go to locations formerly buried in other caches, it might be nice to have a little "waypoint created" note to let you know it completed the request.

**Comment by moving-bits** [comment]
> So this issue remains with:
> > The new add current location button works, however since we now have 40 saved go to locations formerly buried in other caches, it might be nice to have a little "waypoint created" note to let you know it completed the request.

done with #8243
