### ISSUE TITLE
Google maps crashing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8241]
Quite a lot of reports on all support channels, that c:geo crashes when opening the live map with GMaps.
Some users additionally reported, that also the native Google Maps app crashes on start, which makes me think its not our problem. 

I can't reproduce, but lets monitor this.

-----------
Edit:

Seems to be a bug on side of Google Maps, according to their issue tracker: https://issuetracker.google.com/issues/154855417

You may want to set c:geo to use OpenStreetMap (OSM) until that's fixed - see "Settings" => "Map" => "Select Map Source" => "OSM: Map"

**Comment by bekuno** [comment]
I could reproduce.
Open google maps mit live map enabled, some map moves, than it crashes.
Now I cant change anymore to google map. OSM online and offline maps are working.
Failure: 'ArrayIndexOutOfBoundException'

**Comment by lazydays79** [comment]
Couldn't reproduce on my Google Pixel 3XL with Android 10 and the latest Android updates (Security update 2020-04-05 and Google Play system update 2020-03-01). 

Even moving, scrolling and zooming the live map using gmap for more than 5 minutes, I couldn't provoke a crash.

**Comment by Schwengelito** [comment]
I also have a problem with Google Maps using c:geo. I have the issue since like 12 hours or so. From one second to the other, c:geo jumps straight to the homescreen of my smartphone when I try to get the live map startet using Google Maps. When I go into my setting and switch to OSM, there is absolutely no problem and the live map works.

Google Maps itself works fine, it's just c:geo crashing when trying to use Google Maps for the live map.

I didn't change anything in the settings I think. The problem just suddenly showed up.

**Comment by Lineflyer** [comment]
For me also everything stable.

The reports are still significant and state that c:geo immediately crashes when starting LiveMap.
There seems to be some kind of an issue coming in from Google itself I assume.

@bekuno 
What c:geo version are you using? Your problem sounds like on of the issues we recently already tried to solve and not neccesarily related to this problem.

**Comment by bekuno** [comment]
> What c:geo version are you using? Your problem sounds like on of the issues we recently already tried to solve and not neccesarily related to this problem.

Android 9 (Samsung Note 8).
After the first crash the state is now as described: immediately crashes when starting Google LiveMap. It is like in the description from @Schwengelito : "From one second to the other, c:geo jumps straight to the homescreen of my smartphone ..."

**Comment by Lineflyer** [comment]
And c:geo version?

**Comment by bekuno** [comment]
latest prod - 2020.03.30

**Comment by moving-bits** [comment]
> I also have a problem with Google Maps using c:geo. I have the issue since like 12 hours or so.

Are you using the release version of c:geo, or a nightly or beta version?

**Comment by moving-bits** [comment]
> For me also everything stable.

same here - stable with release version 2020.03.30, Android 10, Samsung device

**Comment by Schwengelito** [comment]
> > I also have a problem with Google Maps using c:geo. I have the issue since like 12 hours or so.
> 
> Are you using the release version of c:geo, or a nightly or beta version?

I use the 2020.03.30 version.

**Comment by Lineflyer** [comment]
Now I also see the crash reports on Google play...quite massive 10000 reports yesterday.
The stack trace is short and Google Play says, that it need deobfuscation data from ProGuard.

java.lang.ArrayIndexOutOfBoundsException: 

at com.google.maps.api.android.lib6.gmm6.vector.ct.<init> (com.google.android.gms.dynamite_mapsdynamite@201216061@20.12.16 (100300-0):9)

at com.google.maps.api.android.lib6.gmm6.vector.cv.a (com.google.android.gms.dynamite_mapsdynamite@201216061@20.12.16 (100300-0):23)

at com.google.maps.api.android.lib6.gmm6.util.m.run (com.google.android.gms.dynamite_mapsdynamite@201216061@20.12.16 (100300-0):14)

at java.lang.Thread.run (Thread.java:764)

**Comment by Lineflyer** [comment]
Happening on several/all Android versions but (assuming the list is complete) only on Samsung and Huawei devices.

**Comment by lazydays79** [comment]
> Happening on several/all Android versions but (assuming the list is complete) only on Samsung and Huawei devices.

I know someone facing this issue, but he uses a ZTE Blade V10. So I assume the list isn't complete.

**Comment by lazydays79** [comment]
> > Happening on several/all Android versions but (assuming the list is complete) only on Samsung and Huawei devices.
> 
> I know someone facing this issue, but he uses a ZTE Blade V10. So I assume the list isn't complete.

And he just told me, that he didn't install any system or app updates. The issue just suddenly appeared, during using cgeo.

**Comment by moving-bits** [comment]
- Is this Live Map only, or all of Google Maps (within c:geo)?
- Are we hitting some usage limit? (Is there a limit for using Android GMS?)

**Comment by moving-bits** [comment]
> Now I also see the crash reports on Google play...quite massive 10000 reports yesterday.
> The stack trace is short and Google Play says, that it need deobfuscation data from ProGuard.

The latter is to be expected, if it's related to some GMS internal functions.

Are there no c:geo routines popping up in the stack traces?

**Comment by Schwengelito** [comment]
> * Is this Live Map only, or all of Google Maps (within c:geo)?
> * Are we hitting some usage limit? (Is there a limit for using Android GMS?)

It's not just the live map here, it's also when trying it from the cache list and from any other way I try to use GM via c:geo.

I'm hitting no usage limit, as far as I know.

**Comment by bekuno** [comment]
the problem is also on Google: Satellite

**Comment by bekuno** [comment]
the latest entry in the event log with cgeo fefore the crash info is
`set_resumed_activity: cgeo.geocaching/.maps.google.v2.GoogleapActivity,minimalResumeActivityLocked`

Maybe this is a file created in the file system?

**Comment by bekuno** [comment]
If I understand the text in https://news.ycombinator.com/item?id=22961916 correct, then it is a generally problem at google.

**Comment by bekuno** [comment]
an other discussion to this problem:
https://github.com/flutter/flutter/issues/55506

**Comment by Lineflyer** [comment]
Oh, yes: https://issuetracker.google.com/issues/154855417

**Comment by bekuno** [comment]
We could implement the workaround in our beta/nightly:
~~~
see https://issuetracker.google.com/154855417#comment232. In Application.onCreate():

SharedPreferences googleBug = getSharedPreferences("google_bug_154855417", Context.MODE_PRIVATE);
if (!googleBug.contains("fixed")) {
        File corruptedZoomTables = new File(getFilesDir(), "ZoomTables.data");
        corruptedZoomTables.delete();
        googleBug.edit().putBoolean("fixed", true).apply();
}
~~~

But I'm not sure how long we have to wait for the publish, or let's wait for a fix from google.

**Comment by bekuno** [comment]
@Lineflyer can you trigger a message in c:geo?

**Comment by Lineflyer** [comment]
Mmh...we are about to release, so we could easily include this workaround.
The question would be if there is any risk in implementing it. 

Out of curiosity: Is getting a bug status from Google in this way a standard method in Android?

**Comment by moving-bits** [comment]
> Mmh...we are about to release, so we could easily include this workaround.
> The question would be if there is any risk in implementing it.

According to the first statement in their bug tracker (https://issuetracker.google.com/issues/154855417) it should be save:
> For Android, multiple developers mentioned a workaround consisting in deleting the ZoomTable.data file directly from their application. After review, this fix seems safe, and you could try it in your application. 

I'll give it a spin, targeted to release.

**Comment by moving-bits** [comment]
> Out of curiosity: Is getting a bug status from Google in this way a standard method in Android?

Not that I know of. They're probably simply creating a private file to store a marker that zoom data file has been reset (to only reset it once).

**Comment by Lineflyer** [comment]
Workaround #8244 has been merged to `release` and `release` merged upstream.
I am just now running new nightly builds.

**Comment by Lineflyer** [comment]
On all my test devices the problem does not show up, so I cannot test if the workaround catches it.
However I tested with the new nightly on all devices and could not see any negative effect (and no catched exception). So I assume it works.

Anyone, who has a affected device and could test using
http://download.cgeo.org/cgeo-nightly.apk

**Comment by Lineflyer** [comment]
I wil be out now for the afternoon. When returning tonight I could continue the release process unless we have a reason to wait.

**Comment by Lineflyer** [comment]
Workaround is implemented. Release is rolling out, refer to #8207.

Closing here hoping that this issue is solved.
Will monitor crash reports though.
