### ISSUE TITLE
Rotating map active after fresh installation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8242]
IMHO we decided to make this opt-in, but as I just freshly installed c:geo on my Android 5 device the feature is on (and making the map rotate randomly as it does not work so good with device).
Do I remember wrong or is there a bug?

**Comment by moving-bits** [comment]
Automatic map rotation should be deactivated by default - will look into it tonight.
(Manual map rotation is on by default, but requires active user interaction.)

**Comment by moving-bits** [comment]
Default value for fresh installs is set correctly in `Settings.isMapAutoRotationDisabled()`:
`return getBoolean(R.string.pref_map_autorotation_disabled, true);`

This gets called during map creation by `GooglePositionAndHistory` via a call to `updateMapAutoRotation()`.

Need to dig in deeper...

**Comment by Lineflyer** [comment]
Can you reproduce the problem at least....or was it maybe a user error on my side...

**Comment by moving-bits** [comment]
> Can you reproduce the problem at least....or was it maybe a user error on my side...

No, cannot reproduce on my Android 5 device.

Did you delete app data after before doing a fresh install? (app manager => c:geo => delete data, then uninstall c:geo)

**Comment by Lineflyer** [comment]
> Did you delete app data after before doing a fresh install? (app manager => c:geo => delete data, then uninstall c:geo)

I just now tried to reproduce this and failed.
Maybe during installation I stumbled upon my bad thinking at which point settings have been stored or nor stored. So I guess the problem was on my side. 

Let me close this, will reopen if it shows up again.
