### ISSUE TITLE
Add closeout warning for Android versions <5.0

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8246]
As we are planning to cut off a legacy version for devices running Anrdoid <5.0, we should activate the closeout warning for those versions before releasing.

There should be some code for this already present in the app. I don't know the details however and only found this:
https://github.com/cgeo/cgeo/blob/c766f182b2d7f68b04272ed9dbc000949ef85b0a/main/src/cgeo/geocaching/network/StatusUpdater.java#L40

Tasks:
- [x] Activate this closeout warning for the relevant Android versions and update string
- [ ] Merge incoming translations
~~- [ ] Update https://www.cgeo.org/faq#install-fail accordingly~~
- [x] Update https://www.cgeo.org/faq#legacy accordingly

**Comment by Lineflyer** [comment]
"Problem" here is, that the message itself (`status_closeout_warning_41`) needs to be localized, which needs time.
So how about continue the upcoming release "as is" and issue another small release afterwards with activated closeout warning. We would need to do the changes based on `master` to get new translations and then again merge it to `release`.

**Comment by moving-bits** [comment]
Thanks for the pointer, and, yes, let's do it that way. We've a couple of more things in the queue already, so another version is upcoming already anyway.

**Comment by Lineflyer** [comment]
Let me reopen this for the remaining items above.

BTW: The install fail only needs adaption in FAQ if we drop the legacy version.

**Comment by moving-bits** [comment]
> BTW: The install fail only needs adaption in FAQ if we drop the legacy version.

Do we still have a version available for Android 4.0? (legacy?)
Current release supports starting from Android 4.1 (API level 16), that's why I thought we might need to update that part as well.

**Comment by Lineflyer** [comment]
You are perfectly right. It needs a bit of adpation indeed.

**Comment by Lineflyer** [comment]
The issue is solved, let me take the remaining FAQ adaption to a dedicated issue.

**Comment by Lineflyer** [comment]
Correction: We can correct this FAQ item right away, as we should already refer to 4.1 there.
