### ISSUE TITLE
Next feature release (after 2020.04.25)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8252]
As discussed in several issues we might plan to prepare cutting out a legacy version.
Steps needed for that:
- Merge #8247 to update and activate the closeout message ~~, but do not yet merge any functional changes~~ and test new features in nightlies
- Wait for incoming translations for the adapted strings and monitor performance of current release 
- In case of need: Apply other bugfixes to `release`
- Merge `master` to `release` again
- Release a new version

After this, we can cut off a new legacy version based on `release` and raise minSDK on `master` (see #8250 

Correct sequence or can this be optimized?

**Comment by Lineflyer** [comment]
As @moving-bits now already merged functional changes to master (which is fine btw), we should widen the sequence described above a bit:
In fact we need to complete round of testing the new features before releasing them. Will take a bit more time then. Item added above.

**Comment by moving-bits** [comment]
> but do not yet merge any functional changes

Sorry, saw this too late. We can still do that, if we want to, as I've merged the closeout warning message first. - I'm currently merging those features only, which seem to be "uncritical" to me. (But still we need some beta time for them.)

I would give the new release one or two weeks anyway before branching legacy version (if we want to branch from current master), or a few weeks after the release created from current master (which was my original intention).

**Comment by moving-bits** [comment]
So, I've merged every open PR I see fit for a next minor release (except for Crowdin - let's wait a couple for days for the Crowdins to translate the new strings).

If the nightly from this as well as current release behave well, we can prepare another release from that. (Sequence described above is perfect ;-))

After that we can branch legacy, and merge #7856 and #8180 to master then, for more intensive testing of those two larger PR.

**Comment by Lineflyer** [comment]
Well.
Right now it seems we are in the middle of interesting new changes.
However - may I suggest we either...
1. Stop merging new features on `master` and tackle regressions of those already merged. Later decide to merge `master`to `release` and continue with beta, release, creating legacy
2. Merge `master` to `release` now, fix regressions on `release` and then as described above

Advantage of option 2 would be that we can continue as we like on `master`. Disadvantage is, that we `release` will (temporarily) contain known regressions thus when forced to release we have them in. For that reason I prefer option 1.

**Comment by moving-bits** [comment]
IMHO we have four categories currently:
1) a couple of bug fixes, which should be included in the next release
2) new features which should not be included at this time (#7856 and #8183) as well as the breaking change minSDK raise (#8250)
3) some features not yet finished (#7199, #8139)
4) and a few features I'm unsure of: #8332 (logcat), #8326 (compass rose handling for autorotation)

I would prefer option 1 as well, extended it a bit:
- merge cat 1, maybe some of cat 4
- stabilize the version, beta test, and release
- branch legacy
- raise minSDK on master
- merge cat 2 and remaining cat 4 to master, stabilize if necessary
- fix issues in release version on release branch (if necessary)

After that we should decide how to continue. I could imagine a temporary stop of new features and other larger refactorings to allow @jonas-koeritz some stability on master branch to implement the switch to Room and a new caching mechanism. 

@jonas-koeritz  Does this sound reasonable, and if: How long should this feature freeze be?

**Comment by jonas-koeritz** [comment]
I've come to some conclusions about how we might be able to pull this off without a real feature freeze.
I'm still playing around with the codebase to see where the side effects are hitting me hardest. Having a stable release on a reasonably new API level was the main hurdle.
Going the full-on room in one release way won't work in any case. Migration, regressions etc. would make this too much to be done at once.
Has the fallout of the Logging errors and map limitations been fully cleared up yet?

**Comment by Lineflyer** [comment]
>1. a couple of bug fixes, which should be included in the next release

Shall we list those here, so we have an overview of when to merge branches and go for beta?

>2. new features which should not be included at this time (#7856 and #8183) as well as the breaking change minSDK raise (#8250)

Agree to handle them only later.

> 3. some features not yet finished (#7199, #8139)

These should also be handled only later.

> 4. and a few features I'm unsure of: #8332 (logcat), #8326 (compass rose handling for autorotation)

Logcat already merged (I need to check/test), I suggest to wait with #8326 for later.

**Comment by Lineflyer** [comment]
Addon:

Looking at the issue I do see following bugs / regressions, which I guess should be solved:
- [ ] #8333
- [ ] #8151 (maybe)
- [ ] #8300 
- [ ] #7998 

As soon as these (or the agreed set) is solved we should go for a beta to potentially reveal undiscovered regressions.

**Comment by Lineflyer** [comment]
Added #8260 to the list above.

**Comment by moving-bits** [comment]
Would #8326 be enough for #8151?

**Comment by Lineflyer** [comment]
> Would #8326 be enough for #8151?

Assuming that such kind of devices without any matching sensor capability are rare, and even rarer to be used in conjunction with Geocaching, I think it would be sufficient.

**Comment by Lineflyer** [comment]
Marked #8260 as fixed.

So the last open issue is #7998.

**Comment by moving-bits** [comment]
> So the last open issue is #7998.

As @bekuno does not have time at the moment I started digging a bit into #7998, diving deeply into the source - and find it pretty confusing for now. (But it's an area I'm not really firm with.) We have a userName and a userId, sometimes called displayName and userName (to make it a bit more interesting), and all variants are used pretty much mixed up.

Therefore I propose to leave this issue out of the upcoming version and try to fix it later. (#7998 is in the code for at least half a year and several versions already, so no new regression to be fixed urgently.)

Having said this, we would be ready to pack a beta version then, IMHO. @Lineflyer  What do you think?

**Comment by Lineflyer** [comment]
We are only volunteers and can only fix something if someone is capable and available. So lets leave it open for now and lets go for beta.

I will prepare as soon as time permits

**Comment by moving-bits** [comment]
#8394 should be included as well, IMHO, as it is a regression introduced after the 2020-04-25 release.

**Comment by Lineflyer** [comment]
Yup, feel free to merge when ready.I will probably find time to merge branches only tonight.

**Comment by moving-bits** [comment]
> Yup, feel free to merge when ready.

#8394 is included now => master branch is ready for preparing a beta

**Comment by Lineflyer** [comment]
Wilco :)

**Comment by Lineflyer** [comment]
Branches merged, changelog adapted.
Will build and test RC.

**Comment by Lineflyer** [comment]
Running smoothly on my Android 5.0.1 and Android 10 device. Basic test also done Android 4.1, starting and showing closeout warning.

2020.05.31-RC pushed to Google Play.

@moving-bits @bekuno 
Just a side note: In case you update the changelog (which I encourage in principle) please keep in mind, that we want to show the diff to the last release. Right now the changelog seems to contain bugs fixes which resulted from a regression while developing on master but not released on the market. Thus those would not be included in the changelog.

**Comment by moving-bits** [comment]
> Just a side note: In case you update the changelog (which I encourage in principle) please keep in mind, that we want to show the diff to the last release. Right now the changelog seems to contain bugs fixes which resulted from a regression while developing on master but not released on the market. Thus those should not be included in the changelog.

Oops, probably my fault. Have you stripped it down already, or shall I cross-check the merged PR with release notes?

**Comment by Lineflyer** [comment]
> Oops, probably my fault. Have you stripped it down already, or shall I cross-check the merged PR with release notes?

Needed to strip down anway for Google Play as they support max 500 chars. However you might downstrip it anyway (based on release branch).

**Comment by moving-bits** [comment]
How to proceed from now (besides beta version)?
- We have #8399 to disable Geolutins watchdog test
- We want to cut off a legacy version
- We have a couple of new PR, smaller and larger ones (intended for non-legacy version only)

What is the right order in which to merge those?
And should #8399 be merged to master or to release?

**Comment by Lineflyer** [comment]
#8399 should be merged to release first and then release should be merged to master. So we have the test disabled on both branches and history is clean.

**Comment by bekuno** [comment]
I think we should wait to see if there are any problems with the new version. In the meantime, we could integrate bug fixes and non-critical fixes.
So we can create a bugfix release in ~3 weeks (?). This would then become the legacy version.

**Comment by Lineflyer** [comment]
I assume the beta version 2020.05.31-RC is running fine so far. We did not receive any complaints on support channels up to now for approx. 8000 installations.
We however have two crash reports flagged as new for this version by Google Play:
- [ ] #8401
- [ ] #8402

**Comment by bekuno** [comment]
PR #8419 and #8422 are bug fixes and should go to release.

**Comment by Lineflyer** [comment]
What about #8402?
I cannot judge how frequent the occurrence might be, what triggers it and how this problem shows up to the user?

**Comment by moving-bits** [comment]
We're going to prepare the next release starting this weekend, thanks to @Lineflyer.

Therefore we can unlock master branch now. I'll restart merging the PR, beginning with the minSDK raise and dependency updates today. Other PR will follow throughout the next days. I'll distribute the merges over the days to not put too much new into the version on the same day.

**Comment by Lineflyer** [comment]
I will prepare the release now based on current status of branch `release`.

Afterwards we can check performance and apply fixes if needed.
Once we have a reached a stable state, we can then start over with cutting of the state to branch `cgeo-legacy` to prepare a legacy version for Android 4.1 - 4.4. Will open a dedicated issue for this topic.

Release checklist:

- [ ] Check/Insert correct version name as headline in ```changelog-release.xml```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
Release of 2020.06.14 is done so far...now waiting for Google Play to push it out on the market.

**Comment by Lineflyer** [comment]
All done! Thanks to all contributors!
