### ISSUE TITLE
Country filter list contains empty element

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8258]
**Describe the bug:**
While trying the new country filter I do see one empty line within the list items.
I guess this might be due to having OC.de caches on my lists, where the location field is not used.

**To Reproduce:**
1. Save some gc.com caches, save some oc.de caches
2. Open the list
3. Select Filter, Country

**Actual behavior/state after performing these steps:**
The list contains the countries matching the caches on my list, but also one empty line
When activating this empty line as a filter, it seems to return all caches

**Expected behavior/state after performing these steps:**
Empty lines should be hidden as they do not deliver a valid filter result

**Version of c:geo used:**
You will find the c:geo version in c:geo Menu -> About c:geo

**Is the problem reproducible:**
Yes / No

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

**Comment by moving-bits** [comment]
Another source of this "locationless" cache might be the "goto history" UDC (see InternalConnector.GEOCODE_HISTORY_CACHE - this contains the Geocode of this special cache.)

Maybe we should either exclude an empty location or name it "empty location" (or something like that).

**Comment by moving-bits** [comment]
Currently the empty line results in no filtering at all. I'll create a PR to filter to empty location field, if the empty filter line is selected.
