### ISSUE TITLE
Switch from/to compact icons depending on cache density

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8261]
Just an idea, not sure whether such automatism is what users want:

We already have a "compact icon" mode but users would need to manually activate/deactivate it. Some users might not even be aware of that function.

If you compare to other apps visualizing locations on a map, you typically see an automatic switch to a more compact layout if you reach the limit where the original layout stops providing meaningful information (in our case e.g. when icons are massively overlapping). Implementing an automatic switch could help with this.

But what could be the triggering condition?

Remark:
It might be useful to solve #8260 first, before implementing such function as it makes no sense if the map is not properly filled.

**Comment by moving-bits** [comment]
I would make this behavior user selectable, e. g. `compact mode = off | on | auto` with default to `auto`.

A triggering condition could be the amount of caches returned on live map / searchResult, divided by some indicator of screen size & pixel density. (But still need to put this into a reliable and useful formula...) So on a tablet of reasonable size and resolution you would be able to see more caches in standard size as on a low res 3.5" mobile.

**Comment by moving-bits** [comment]
see #8389

**Comment by moving-bits** [comment]
Closed with #8389.
