### ISSUE TITLE
NPE at calculateRouting

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8262]
Reported new for 2020.04.25 . Android 9 on a Huawei device

ˋˋˋ
java.lang.NullPointerException: 

at cgeo.geocaching.maps.routing.Routing.calculateRouting (Routing.java:173)

at cgeo.geocaching.maps.routing.Routing.getTrackNoCaching (Routing.java:152)

at cgeo.geocaching.maps.routing.Route.calculate (Route.java:231)

at cgeo.geocaching.maps.routing.Route.toggleItemInternal (Route.java:193)

at cgeo.geocaching.maps.routing.Route.loadRouteInternal (Route.java:164)

at cgeo.geocaching.maps.routing.Route.lambda$loadRoute$1$Route (Route.java:157)

at cgeo.geocaching.maps.routing.-$$Lambda$Route$Z4Rt7blQIC_R2Lt8x1KTZV8ad5A.run (Unknown Source:2)

at io.reactivex.Scheduler$DisposeTask.run (Scheduler.java:578)

at io.reactivex.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java:66)

at io.reactivex.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java:57)

at java.util.concurrent.FutureTask.run (FutureTask.java:266)

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)

at java.util.concurrent.ThreadPoolExecutor.processTask (ThreadPoolExecutor.java:1187)

at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)

at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)

at java.lang.Thread.run (Thread.java:784)

ˋˋˋ

**Comment by moving-bits** [comment]
I don't understand this error. `Routing.java:173` reads `final String gpx = brouter.getTrackFromParams(params);`, so a NPE in this line means that `brouter` has a null value. But in the calling method `getTrackNoCaching()` this is explicitly checked... What am I missing here?

**Comment by Lineflyer** [comment]
I doublechecked on Google Play.
In fact it goes only back to a single user up to now with 18 identical stack traces.

BTW: @moving-bits Do you have access to the Play Console?

**Comment by moving-bits** [comment]
> BTW: @moving-bits Do you have access to the Play Console?

No, I don't currently. I did have some time ago, but somehow the assignment of my account to the Play Console got lost.

**Comment by Lineflyer** [comment]
> > BTW: @moving-bits Do you have access to the Play Console?
> 
> 
> No, I don't currently. I did have some time ago, but somehow the assignment of my account to the Play Console got lost.

@mucek4 Can you enable him again?

**Comment by MagpieFourtyTwo** [comment]
Huawei with Android 10 over here, with Brouter working flawlessly. 

Is there a special scenario to reproduce the NPE or should it happen in all circumstances?

Already tried to clear Brouters cache, delete downloaded tiles and reinstalled/reload again?

**Comment by moving-bits** [comment]
Deducing from that line in LogCat `cgeo.geocaching.maps.routing.Route.loadRouteInternal (Route.java:164)` it is related to the new function "individual routes" at the stage where a route is loaded (e. g. when starting a new map view).

**Comment by MagpieFourtyTwo** [comment]
WFM, no problems with individual routes at all.

**Comment by Lineflyer** [comment]
I was able to crash it recently, no idea whether it was exactly this NPE.

It seems to have something to do with having only the starting point of an individual route defined and using different types of map (live map, list map, cache map, single waypoint map). Still struggeling to reproduce.

**Comment by MagpieFourtyTwo** [comment]
Checked all scenarios I can think of with only the starting point set, but was not "able" to crash c:geo.

Nevertheless, although I don't really believe, BRouter will be called with just one point (as this makes no sense at all), but if so (reaching for a straw), it could probably be a fix for this ungrabbable NPE, to call BRouter for two or more points only ...?

BTW: How do you get an individual route, when being in a single waypoint map context? All I get by trying so is "Error while changing the waypoint".

**Comment by moving-bits** [comment]
> Checked all scenarios I can think of with only the starting point set, but was not "able" to crash c:geo.

Thanks for cross checking.

> Nevertheless, although I don't really believe, BRouter will be called with just one point (as this makes no sense at all), but if so (reaching for a straw), it could probably be a fix for this ungrabbable NPE, to call BRouter for two or more points only ...?

This is already being taken care of.

> BTW: How do you get an individual route, when being in a single waypoint map context? All I get by trying so is "Error while changing the waypoint".

Huh, what's that? Never used that before...
Thanks for the info - need to check how I can disable the individual route UI in this mode.

**Comment by moving-bits** [comment]
Haven't seen this error lately. Also internal representation of routes has changed significantly after 2020.07 release, therefore closing this issue. If the error should come up again we can open a new issue.
