### ISSUE TITLE
Zoom in (+) Button is greyed out in combined map

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8263]
**Describe the bug:**
Zoom in (+) Button is greyed out in combined offline map at quite coarse zoom level:
scale line showing 50km in Germany, 100km in India.

**To Reproduce:**
Chose combined map
go to live map or display a cache on the map
Zoom in / out with the  - / + buttons bottom left, 
or zoom in by two finger spread.
With Indian map (+) button dissapears at 5m scale line

**Actual behavior/state after performing these steps:**
Zoom in (+) get grey out and cannot be used any more, Finger Spread still works

**Expected behavior/state after performing these steps:**
Zoom in (+) stay functional

**Version of c:geo used:**
2020.04.24-NB-79a985d

**Is the problem reproducible:**
Yes

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
--- System information ---
Device: MI 8 (dipper, Xiaomi)
Android version: 10
Android build: QKQ1.190828.002 test-keys
c:geo version: 2020.04.24-NB-79a985d
Google Play services: disabled - 20.12.16 (120400-306753009)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (93,9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (93,9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (93,9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (7,7 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins: none
--- End of system information ---
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.
![Screenshot_2020-04-24-12-41-32-013_cgeo geocaching](https://user-images.githubusercontent.com/43813636/80314768-b3b4e180-87f3-11ea-9aab-cb7092ceccb4.jpg)
![Screenshot_2020-04-24-12-41-53-255_cgeo geocaching](https://user-images.githubusercontent.com/43813636/80314773-bc0d1c80-87f3-11ea-807f-c691ea8cf4b4.jpg)
![Screenshot_2020-04-24-12-42-16-047_cgeo geocaching](https://user-images.githubusercontent.com/43813636/80314776-c29b9400-87f3-11ea-8c0d-6203972fa7fe.jpg)

**Comment by geocachermgo** [comment]
My idea was , that maybe the level of a more coarse map is used. I have included a world map thats stops with 50km scale line to show the + button greyed out.  So the limit must be diffenet one.

**Comment by geocachermgo** [comment]
Actually the world map has different zoom level between India and Germany, so the guess maybe is right.

**Comment by MagpieFourtyTwo** [comment]
Same over here - but only with the map mentioned above.

**Comment by moving-bits** [comment]
Yes, currently maxZoom of a combined map is the lowest maxZoom value of any of the maps involved. I'll create a PR to change this to max. Mapsforge lib seems to be able to handle this, at least a quick test with world map works as intended.
