### ISSUE TITLE
Waypoint view not updated

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8266]
**Describe the bug:**
Waypoint view gets not updated after creating a new waypoint, in certain conditions.

**To Reproduce:**
- Go to "live map"
- tap on an unsaved cache
- go to details
- swipe to go to waypoints page
- tap "add current location"

**Actual behavior/state after performing these steps:**
- cache gets saved
- new waypoint gets created
- but waypoint view does not get updated immediately - you have to close the cache page, re-open it, and go to waypoints page again to see the newly created waypoint

**Expected behavior/state after performing these steps:**
- update waypoints page immediately after creating the new waypoint

**Version of c:geo used:**
current master

**Is the problem reproducible:**
Yes

**Comment by geocachermgo** [comment]
May this has the same cause as #8237?

**Comment by moving-bits** [comment]
I'm not sure - #8266 is about a sub page of cache detail activity, whereas #8237 is about map view.

**Comment by Lineflyer** [comment]
> I'm not sure - #8266 is about a sub page of cache detail activity, whereas #8237 is about map view.

I think its different, only the title wording is similar.

**Comment by geocachermgo** [comment]
Yes, I (wrongly) assumed that "view" is on the map and not the list you get by swipe right.
I too think its different.

**Comment by MagpieFourtyTwo** [comment]
Same happens (for ages) when adding a waypoint in waypoint list by [add waypoint] or esp. via long tap on map (at least until the setting of "add icon to individual route" vs. "create user defined cache" made it impossible to add a waypoint via long tap on map, which I BTW badly miss - any chance to get this back?): waypoint list did not get updated until you either close the cache and reopen it or - and this is our workaround - you again tap [add waypoint] and then close this dislog by [X] again.

AFAIR there was an issue dealing with thus refresh problem, but right now I can not check ...

**Comment by MagpieFourtyTwo** [comment]
What about those new Waypoints created by long tap in map, which do not immediately appear in WP list, too?
I know, it's a different scenario, but issue title would fit this problem, too, and perhaps even the solution can be kind of similar ...? ;)

**Comment by moving-bits** [comment]
> What about those new Waypoints created by long tap in map, which do not immediately appear in WP list, too?
> I know, it's a different scenario, but issue title would fit this problem, too, and perhaps even the solution can be kind of similar ...? ;)

Let's keep those issues separate, it makes it easier to track them. I have adapted the title of this issue to clarify which problem source is being addressed.

Please open a new issue for the scenario you have in mind, and describe the way to reproduce it.
