### ISSUE TITLE
Implement adding waypoint via long tap on map also for GMv2

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8269]
**Describe the bug:**
Triggered by a remark in https://github.com/cgeo/cgeo/issues/8266#issuecomment-620489114:
Creating new waypoints via long tap on map is no longer possible when using Google Map. It still works as expected on NewMap.

**To Reproduce:**
- Open a cache details page
- Open Google Map for this cache
- Long tap on a free space on map

**Actual behavior/state after performing these steps:**
- Depending on the setting of Settings => Map => Long Tap either nothing happens or the "create UDC" dialog opens

**Expected behavior/state after performing these steps:**
- Independently from above mentioned setting a "create new waypoint" dialog should appear (as it does in NewMap)

**Version of c:geo used:**
current master

**Is the problem reproducible:**
Yes

**Comment by Lineflyer** [comment]
mmh...was it ever implemented for GMaps?

**Comment by moving-bits** [comment]
I'm not sure, either. Certainly, I've not cut it off willingly :-)
Will leave this issue open as a reminder for either fixing it or as a feature wish.

**Comment by moving-bits** [comment]
Just cross checked: Adding a waypoint via long tap on map hasn't been available for GMv2 so far - changed title and label accordingly.

**Comment by MagpieFourtyTwo** [comment]
Stumbled upon another scenario where "Create UDC" appears, while I have expected to get "Add Waypoint":

1. open any cache (with at least one waypoint)
2. switch to Waypoint List
3. display one of these waypoints on map via tap on compass rose of the waypoint
4. tap on any free space on map
5. "Create UDC" appears, although we're in a cache's context, thus I would have expected to get "Add Waypoint" ....

Or am I wrong?

BTW: This happens with GM *and* OSM (at least in current nightly 2020.05.03-NB-2f22d9e)
