### ISSUE TITLE
Developer Build Switch

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#8299]
**Is your feature request related to a problem?**
This is not relevant for the users. But I had this idea and would like to hear your thoughts.

**Describe the solution you'd like**
I'd like a kind of drop-in possibility to switch to a developer build. This should take care of backups of cache/settings, install the dev build, and restore the caches/settings. Once you switched to a developer build, you can then test/do whatever, and switch back to the main version with another button. The solution could take an APK file (maybe check for a signature/idk) and do all those steps for the developer/user that just wants to try that new feature still in development, and would be enabling a step of user testing before beta and nightly. Implementation in settings activity near the backup/restore options.

**Additional context**
This would complement the Play Store beta program for users not using Google.

**Comment by Lineflyer** [comment]
I personally do not see any need for such construction/tool as I think the existing mechanisms and separations are sufficient.

**Comment by SammysHP** [comment]
Dito. Also please keep in mind that Google does not allow apps to sideload additional executables or executable code.

**Comment by moving-bits** [comment]
Personally I wouldn't have a use case for this - the current tools are fine for me.
Maybe one can add a wiki page for it to explain the steps, and we can link to that page from the appropriate places.

**Comment by Lineflyer** [comment]
I would say, that writing a wiki page for the restrictions and guideline when changing between builds should do the job then.
@Jakedot  Can you check whether you have the permission to edit the Wiki of this repo? Not sure, if it is open for everyone.

**Comment by jakedot** [comment]
I should have some edit button, right? Doesn't look like I have permissions.

**Comment by jakedot** [comment]
Should I clone the wiki and PR changes? Or is that overkill? I'd also be honoured to become part of the team ;)
