### ISSUE TITLE
"Hide ..." does not work properly with GM in single cache context

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8300]
**Describe the bug:**

"Hide ..." will not work as expected, when ...

**To Reproduce:**
1. open any not yet found cache
   (best: with several waypoint types like parking, start and reference point as well as stages)
2. display in map
3. switch to Google Map or Sat view (if not already set)
4. enable map update

**Actual behavior/state after performing these steps:**

Found caches will be displayed, no matter if "Hide found" is enabled or not.
Setting "Hide found" does not hide the found caches, even toggling *seems* to do nothing,
*but* when "Hide found" is activated, cache waypoints (esp. parking and starting points) will appear - and disappear, as soon as you set "Hide found" again, while other waypoint types like stages and reference points just remain displayed (like the caches themselves, too)

To me this looks as if just the wrong elements get hidden ... or this possibly interacts with the setting in "show waypoints if this many caches are displayed", although I was not able to proof this. Nevertheless even these waypoints disappear if I zoom out enough ...

**Expected behavior/state after performing these steps:**

Hide settings should work as expected

**Version of c:geo used:**

2020.05.04-NB-e808ff0

**Is the problem reproducible:**

Yes

**System information:**
```
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.0.0.190(C431E19R2P5)
c:geo version: 2020.05.04-NB-e808ff0
Google Play services: disabled - 20.15.15 (120400-306758586)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (17,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (17,3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (17,3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (266,7 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Not logged in (Anmeldung…)
   extremcaching.com: Not logged in (Anmeldung…)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
```

**Comment by Lineflyer** [comment]
Partly confirmed.
To me it looks like only saved and own caches are shown but live map loading considers the filter correctly.

**Comment by MagpieFourtyTwo** [comment]
That's quite possible ... as all my found caches are indeed saved offline. Was not aware that this would make any difference.
Nevertheless even saved found caches are found caches and should not show up when "Hide found" is set. :)

**Comment by moving-bits** [comment]
This is `MapMode.SINGLE`, maybe with `mapOptions.isLiveEnabled == true`.

In Google Maps code we currently only apply the filtering when in `MapMode.LIVE` (which is: started "Live Map" from home screen).

What would be the consequences of applying the filtering in other map modes than just `LIVE`? Other map modes are `SINGLE`, `COORDS` and `LIST`.

Proposal:
- For `SINGLE` we should at least make sure the current cache is always displayed and apply filtering only to its waypoints, IMHO.
- `COORDS` is sort of a virtual waypoint having just coords, IIRC, so no filtering should be applied. 
- What would be the user expectation for `LIST`?

=> @Lineflyer ?

**Comment by Lineflyer** [comment]
How is it different in OSM? We should apply the same in both map types.

**Comment by moving-bits** [comment]
Haven't checked yet, and, yeah, we'll probably have to adapt both.

But what would the user expectation be in the `LIST` case - see all caches, as we're mapping a specific list, or filtering being applied 'as always'?

**Comment by rsudev** [comment]
The current implementation (at least OSM when I wrote it) has decidedly the concept of always showing all caches from a list on the list map (and that even regardless of live mode being activated as well or not). I assume (at least existing) users will expect it like that.

**Comment by Lineflyer** [comment]
Spontanous answer...personal opinion:
Those filters have mainly the intention to reduce cluttering on the map,so:

In a map for a single cache I would like to see all information about this cache even though filters are set. We handle it the same for filtering found caches: If I map a found cache it would make no sense to show nothing on that map.

For a list these filters make a lot of sense...e.g. a typical list of solved mysteries, where I dont care about the original listing coords waypoint.

So, I would apply these filter only to instances potentially showing a bunch of caches = List and Live

IMHO this mininizes the need for users to modify the filtering manually depending on map type. Else his can get annoying. 

We had a similar discussion years ago, where hiding of own and found was applied to mapping a list and finally removed to make users happy. This now is the same in principle but talking about a subset of cache internal information rather than a subset of caches. So we should apply the same principle but one level "lower". Difficult to describe, I hope you understand, what I mean.

**Comment by Lineflyer** [comment]
@moving-bits 
Can you help me identifying the different map modes you are naming above, e.g. by a screenshot or the steps activating them, so all can provide a tabular proposal of how to handle each of them?

**Comment by moving-bits** [comment]
Without looking in the code I would say:
- `SINGLE` is cache map called from a cache detail page
- `LIST` is mapping either a cache list or a search result
- `COORDS` is mapping a waypoint or coming from compass
- `LIVE` is coming from home screen -> "live map"

(but there may be more use cases)

**Comment by moving-bits** [comment]
Thanks for your replies. Not sure, if I understand them fully, though...

> The current implementation (at least OSM when I wrote it) has decidedly the concept of always showing all caches from a list on the list map (and that even regardless of live mode being activated as well or not). I assume (at least existing) users will expect it like that.

I do understand the existing users' expectation, but personally tend to disagree - I would like the filters still being applied. (At least I think so, would need to test this in "real live" on a few tours.)

> Those filters have mainly the intention to reduce cluttering on the map,so:

agreed

> In a map for a single cache I would like to see all information about this cache even though filters are set. We handle it the same for filtering found caches: If I map a found cache it would make no sense to show nothing on that map.

I do agree for the cache itself, but for "original waypoints" I still wouldn't want to see them. Use case is a solved mystery, having it's original waypoint far away. When I'm approaching GZ mapping this cache including all its waypoints would lead to a large area being shown.

> For a list these filters make a lot of sense...e.g. a typical list of solved mysteries, where I dont care about the original listing coords waypoint.

I would not want to see those even when I'm mapping a single cache, at least in 99% of all cases.

> So, I would apply these filter only to instances potentially showing a bunch of caches = List and Live

What about the original issue here - mapping a single cache, but activating "live mode"? Map mode is still `SINGLE` in this case, but with `mapMode.isLiveEnabled == true`.

> IMHO this mininizes the need for users to modify the filtering manually depending on map type. Else this can get annoying.

> We had a similar discussion years ago, where hiding of own and found was applied to mapping a list and finally removed to make users happy. This now is the same in principle but talking about a subset of cache internal information rather than a subset of caches. So we should apply the same principle but one level "lower". Difficult to describe, I hope you understand, what I mean.

That's the point where you start to confuse me ;-)
To my understanding you propose to apply filtering to mapped lists, but I read your example that for "own and hidden caches" an exception has been made. So what to do here?

Maybe a solution could be to make it user-selectable, something like "apply filters to mapped lists" (default=no) and "apply filters to mapped single cache" (default=no, and the cache itself always being displayed)? Or do it the other way around, stating "apply filters to live map only" (default=yes)?

**Comment by Lineflyer** [comment]
> That's the point where you start to confuse me ;-)
> To my understanding you propose to apply filtering to mapped lists,

Sorry for the confusion...Its not so really related. Bad comparison.

> Maybe a solution could be to make it user-selectable, something like "apply filters to mapped lists"...

We already added a lot of new settings over the last month. I am still not really lucky with so much customization generally...makes it complex. 
Also in this case it would already be really difficult to describe as users probably are not so aware about different map types.

Let me sleep about it...

**Comment by moving-bits** [comment]
Ok, here's a proposal if we do *not* want to add additional settings:

- activate filtering in `SINGLE`, `LIVE` and `LIST` modes, but not in `COORDS` mode
- with the exception for `SINGLE` mode, that the cache from which that map got opened always will be displayed (but not necessarily its waypoints)
- make it the same for Google Maps and NewMap

---

*IF* user settings would be fine, my preferred proposal would be to introduce the following settings:
- "auto apply filters for live map" [which would include `SINGLE` mode with `isLiveEnabled == true` as most users probably do not distinguish between the two] [default=yes]
- "auto apply filters for mapping cache lists" [default=no]
- "auto apply filters for mapping single caches" [default=no]

The default values would mimick today's behavior.

Those three would go into a separate group of settings on the "map preferences" page. I would put those in preferences only, not in map menus, as I think that those are more generalized personal preferences, not something you would need to change on the fly.

---

What do you think?

**Comment by Lineflyer** [comment]
> activate filtering in SINGLE, LIVE and LIST modes, but not in COORDS mode
> with the exception for SINGLE mode, that the cache from which that map got opened always will be displayed (but not necessarily its waypoints)

Why not their waypoints? This issue is dealing with the waypoints. IMHO the SINGLE map should always display all information of the cache unless live mode gets enabled. 

> IF user settings would be fine, my preferred proposal would be to introduce the following settings:
> "auto apply filters for mapping cache lists" [default=no]

AFAICS it should be default=yes to mimick the todays behaviour.

> "auto apply filters for mapping single caches" [default=no]

OK...refer also to my comment above for the non-setting solution.

> make it the same for Google Maps and NewMap

That in any case.

**Comment by moving-bits** [comment]
> > activate filtering in SINGLE, LIVE and LIST modes, but not in COORDS mode
> > with the exception for SINGLE mode, that the cache from which that map got opened always will be displayed (but not necessarily its waypoints)
> Why not their waypoints? This issue is dealing with the waypoints. IMHO the SINGLE map should always display all information of the cache unless live mode gets enabled.

Mostly to get rid of the "original waypoints" as default ;-)
(But I could probably live with that - would need to test in real live.)


> > IF user settings would be fine, my preferred proposal would be to introduce the following settings:
> > "auto apply filters for mapping cache lists" [default=no]
> AFAICS it should be default=yes to mimick the todays behaviour.

At least for "hide own" today's behavior for displaying a list is, that they do not get filtered (have not tested for other geoitems), that's why I set default to no in this case.

> > "auto apply filters for mapping single caches" [default=no]
> OK...refer also to my comment above for the non-setting solution.

default=no would mimick today's behavior.

Much of this is a matter of taste, IMHO, therefore I propose the new settings.

But if we do not want to introduce new settings for it, I would propose filtering as described at the beginning of my last comment - which would introduce some changes to today's behavior.

So the magical question is: New settings or not?

**Comment by MagpieFourtyTwo** [comment]
> This issue is dealing with the waypoints. 

Sorry if I understand "waypoint" in a different way or if I'm out of sync with your discussion (you lost me when it came to "automatically apply filters", did not have enough time to work through it completely - but I in fact have no clue why filtering should not just be like set in the "Hide" menu, which would be, as far as I would say, the most comprehensible, traceable and plausible for the standard user), but just to clarify my initial problem: the issue (at least as I intended it), was not about a cache's waypoints (like Parking, Stage or Initial Coords), but about the displayed caches themselves: I just like to have a possibility to "declutter" the map (as lineflyer named it), i. e. to set that e. g. found caches should not be displayed, which is not possible at all in the described scenario right now.

So, all at least I wanted to say is, that the options set in the Hide menu do not have the effect I was expecting. As far as my problem is concerned, I think there's no need of automatisms, no further intelligence, no additional options, just set "[x] Hide found" and \*plopp\* - found caches disappear. That's all. ;)

Sorry, if I misunderstood or overlooked s/th or missed some behind laying complexity - if so, please just ignore my post. As long as at the end we get a possibility to hide found caches, like it is already possible in OSM. 

Thanks! :)

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
You are right. Your initial issue did not deal with waypoints of a cache but just about the hiding of found caches. And you are also right, that wenn you enable map update it should behave like the normal live map and respect the hide settings.

We then used this issue trying to align on how to behave on hiding in different map contexts.
And the most important point for me is, that it cannot be the same on every map type. Most prominent example: If you enabled to hide your found caches, open the cache details of such found cache and open the map for this cache only. You will for sure still expect it to be shown on this map, else you will just see a map without anything. But (and now your initial issue comes in), as soon as you enable live mode on such map, it should hide the cache (as it is found).

**Comment by MagpieFourtyTwo** [comment]
Ok, thx for getting me back - I'm in again (hopefully).  ;)

In order to get a grip on it, I will try to see this from the point of view of a "standard user". And the very first problem I stumble upon is, that this guy has not even a chance to distinguish between the different map types, cause no matter if he entered `Live Map` from main menu (`LIVE`) or `SINGLE` cache context (which underhandedly has the add. possibility of `COORD`) or `LIST` context (each by activating "enable live update"), it will always be titled `Live Map`. So how should he know how "Hide found" will work in this very moment, if - following the ideas mentioned above - it's effect depends on current Live Map context?

As for the discussed rules and options: They are of course all valid and logically correct, if you look bool'sch at them, but, I'm afraid, the standard user would not be able to follow them. Cause he does not even know that these are different modes. Moreover he (of course) does not know the basic principle of the underlaying programming strategy. And even if he would, booleans will usually only be understood if they are simple AND or OR. Even EXCLUSIVE OR will overstrain most of them. Not to talk about parenthesized resp. nested expressions ...  :)

Even I - who is using c:geo for ages now - was not aware about the different modes until we talked about them over here on github about half a year ago. And - while hoping not to appear arrogant - I think I can claim to be a bit more elaborated than the standard user ... so, please, TMALSS, let's keep it *really* simple. Even if we have to sacrifice a bit of perfect correctness.  ;)

Therefore I would strongly prefer *no* additional options (as most probably no standard user will understand them anyway). Perhaps we can agree on some rules, the user can easily recognize by trial&error - or which can at least be explained in a few easy words.

As for me this could look like:
1. Give `Live Map` a traceable title, like e. g.
   - `Live Map` - when "true live", i. e. entered from main menu
   - `GCxxx (+Live)` - when live in single cache context
   - `WPxxx` ... most regretfully has no "enable live", but if, in future or any not yet seen context, it should be like `GCxxx`
   - `List name (+Live)` - when coming from a list.
2. The root (`SINGLE` or `LIST`) should be the absolute master,
   thus *always* be displayed, no matter which Hide option is set (what would match at least my expectation - YMMV)
3. If `[X] Hide found` will be (or already was) set,
   I would expect found caches to be hidden (apart from master, of course).
   And with the right title for `Live Map` it can easily be understood, why exactly *this* GC will *not* be hidden, although it may be a found one, and even if `[X] Hide found` will be set.

But, to come back to the opening point, no matter if the master will stay or not, I would *never ever* expect that *nothing* changes when activating `[X] Hide found`, apart from suddenly appearing the cache (sub) waypoints (like Parking etc.) of the only displayed non found cache (together with several dozens found ones - most probably because the number of caches displayed *would* drop below my configured limit for "Show waypoints if nor more than x caches are displayed" *if* the found ones would be hidden for real ...  ;) ). And that these (sub) waypoints will disappear again, if I "unhide" found ones by setting `[_] Hide found` ...  :)

So what I would recommend is, not to look for perfect correctness of all matching rules, but first of all for the most recent action of the user, as this most probably represents his current intention. And if he says `[X] Hide found`, he most probably does not want to see the (other) already found ones ... at least as far as I would say.  ;)
