### ISSUE TITLE
Geocaching.com authorization broken after RxJava upgrade

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#8313]
**Describe the bug:**
Geocaching.com authorization doesn't work anymore after upgrade to RxJava3 (c1385e68df3f22cc2c92d8b8c1abc5ea510b8011).

**To Reproduce:**
1. Start Settings → Services → Geocaching.com
2. Active and Authorize c:geo
3. Enter credentials

**Actual behavior/state after performing these steps:**
c:geo is not authorized.

**Expected behavior/state after performing these steps:**
c:geo is authorized.

**Version of c:geo used:**
The bug occurs since c1385e68df3f22cc2c92d8b8c1abc5ea510b8011.

**Is the problem reproducible:**
Yes

**Comment by UniQP** [comment]
I will try to track down what exact change causes the problem.

**Comment by Lineflyer** [comment]
With 2020.05.09-NB-10018fa I cannot even enter the service settings for geocaching.com. The app crashes as sonn as I click on geocaching.com in Menu - Settings - Services.

**Comment by moving-bits** [comment]
closed with #8315
