### ISSUE TITLE
Rounding Error at Waypoint from Cache Coordinates

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8314]
**Describe the bug:**
A created waypoint with the cache coordinates has not the cache coordinates

**To Reproduce:**
Open https://coord.info/GC3P25A
Go to the waypoint page,
New Waypoint, Cache coordinates.
East value is 9°1.999 instead of 9° 2.000 

I use the format degree° m.mmm

**Is the problem reproducible:**
Yes

--- System information ---
Device: MI 8 (dipper, Xiaomi)
Android version: 10
Android build: QKQ1.190828.002 test-keys
c:geo version: 2020.05.09-NB-10018fa
Google Play services: disabled - 20.15.16 (120400-309763488)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (94,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (94,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (94,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (8,1 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins: none
--- End of system information ---

**Comment by Lineflyer** [comment]
Sound similar but not same as #6098

**Comment by UniQP** [comment]
Could reproduce the problem.

**Comment by geocachermgo** [comment]
Just a note to myself: #8237 is another issue by me regarding waypoints. Done around 7.9.20

**Comment by geocachermgo** [comment]
longitude of cache in database 9.03333.
Created waypoint "with cache coordinates"  9.03332
Waypoint with manual entered cache coodinates: 9.03333

**Comment by geocachermgo** [comment]
I created a gpx with several closeby coordinates:
In the gpx the coodinates are stored as decimals with 6 digit precision eg:
"49.000001" and rounding:
49.0000005 is imported as 49.000001
49.0000004 is imported as 49.000000 and exported as 49.0
Even if 49.000001 is displayed as 49 00.000 the higher precision is shown when toggeling the display format.
The waypoints created "as cache coodinates" don't depend on the waypoint format during input (dd.dddddd vs dd mm.mmm).
For increased coordinates the cache has 49.000000 until 49.000009 which is displayed as 49 00.001.
The waypoint has 49.000017 as a coordinate (49 00.001= 49.000016666).
The waypoint stays at this value until 49.000025. Then the cache is displayed as 49 00.002 and the waypoint has 49.000033 as coordinate.

**Comment by geocachermgo** [comment]
In the example GC3P25A it depends on the chosen waypoint format:
If you chose dd.ddddd you get 9.033333 which is the same as the cache (display is 9°2.000 or E 009° 01' 59.999")
If you chose d mm.mmm you get 9.033317 (displayed as 9°1.999 or E 009° 01' 59.941)
If you chose dd mm ss.sss you get 9.033333 (display is 9°2.000 or E 009° 01' 59.999")
The dialog box shows 59.998 (see screenshot)
![IMG_20200929_162348](https://user-images.githubusercontent.com/43813636/94571369-32fd8400-0270-11eb-9637-cafefaccf40f.jpg)

**Comment by geocachermgo** [comment]
Solution suggestion: the coordinates in the dialog window should be rounded to the closest value and not rounded down.
So for d m s the suggestion/prefilled value should be 9° 01' 59.999
and for d mm.mmm 2.000

**Comment by geocachermgo** [comment]
Rounding instead of rounding down needs just to add half an increment of the target resolution.
 0.0005/60 for d mm.mmm
 0.0005/60/60 for d mm ss.sss
before transfering into other format.

**Comment by geocachermgo** [comment]
main\src\cgeo\geocaching\CacheDetailActivity.java  around  line 1928: 
`add_waypoint_currentlocation;
R.id.add_waypoint_fromclipboard`

main\src\cgeo\geocaching\EditWaypointActivity.java around line 406:
`private class CoordDialogListener implements View.OnClickListener
buttonLat.setText(gp.format(GeopointFormatter.Format.LAT_DECMINUTE));`

main\src\cgeo\geocaching\location\GeopointFormatter.java
 `case LAT_DECMINUTE: {
                final Geopoint rgp = gp.roundedAt(60 * 1000);
                return String.format(Locale.getDefault(), "%c %02d° %06.3f\'", rgp.getLatDir(), rgp.getLatDeg(), rgp.getLatMinRaw());`

main\src\cgeo\geocaching\location\Geopoint.java
`    Geopoint roundedAt(final long factor) {
        final double df = 1e6d / factor;
        return new Geopoint((int) Math.round(Math.round(getLatitudeE6() / df) * df),
                (int) Math.round(Math.round(getLongitudeE6() / df) * df),
                this);`

This looks ok to me,  so I dont understand why its not working.

**Comment by geocachermgo** [comment]
Meanwhile proven by Excel.
@UniQP do you agree?
With this change roundedAt would change from "get the closest internal point to the desired resolution grid" to "get the internal point that closest if truncated to the desired resolution grid". Maybe this is unwanted in other uses of roundedAt.

**Comment by UniQP** [comment]
@geocachermgo 
The particular case works fine, because the format specifier `%06.3f` will print the `1.99998` as `02.000`. The rounding problem occurs if we use `Geopoint.getLonMin()` and `Geopoint.getLonMinFrac()` separately.

I think a viable solution is to
- get rid of the `Geopoint.roundedAt` method
- provide two methods that implicitly handle the rounding:
  - a method to get the minutes for the decimal minutes format (**xx**.xxx')
  - a method to get the minutes for minutes + seconds format (**xx**' xx.xx")

**Comment by geocachermgo** [comment]
I think cgeo has no clear concept of the quantisation of the caches and waypoints: At some occurences it's limiting to d mm.mmm (m.3) (e.g. input of waypoint position in d m s.sss, waypoint to notes) at others  (e.g. import of GPX, waypoint projection) to d.6.
This makes it difficult to clone/copy a position (this issue) and to identify waypoints with the "same" position  (#7429). Is "same" identical in m.3 format or in d.6?

**Comment by geocachermgo** [comment]
@UniQP : is now everything restricted to m.3?

**Comment by UniQP** [comment]
@geocachermgo The PR fixes some rounding issue when formatting a `Geopoint`. Internally, the `Geopoint` still uses d.6 (stored as `int`) to represent latitude and longitude.

**Comment by geocachermgo** [comment]
Will e.g. the result of a bearing result have the m.3 or d.6 resolution?
Will the waypoint from a cache have the same coordinates as the cache (even if the cache coordinates have not a value with the d.6 value close the next m.3 value)?
I'll check with the new nightly.

**Comment by geocachermgo** [comment]
The new nightly is deleting caches. I'll open a bug issue.

**Comment by UniQP** [comment]
@geocachermgo  Can you open new bugs for the deletion and the Z..4 problem (with the gpx file attached).

**Comment by geocachermgo** [comment]
I tried, but could not find how to attach it at the phone. (In the menu are only pictures).
![IMG_20201004_103555](https://user-images.githubusercontent.com/43813636/95010979-94857000-062d-11eb-869e-3edf2a0ee385.jpg)


But I can send it to the PC and attach it there.

**Comment by fm-sys** [comment]
@geocachermgo You will have to zip the gpx file, otherwise github will not accept the upload...

**Comment by geocachermgo** [comment]
Thank for the hint. As a try:
[Z00004.zip](https://github.com/cgeo/cgeo/files/5322904/Z00004.zip)
