### ISSUE TITLE
Cache Images list is void after writing note

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8324]
**Describe the bug:**
In the cache details you can show the images list.
From menu you can open the personal note dialog and write/save a note.
After saving no images are shown.

**To Reproduce:**
1. Open Cache Details
2. Navigate to "Images"
3. Open "Personal note"
4. Save "Personal note"

**Actual behavior/state after performing these steps:**
No Images shown

**Expected behavior/state after performing these steps:**
Images are shown as before.

**Version of c:geo used:**
2020.04.25

**Is the problem reproducible:**
Yes

**Comment by moving-bits** [comment]
Currently after personal note edit the whole viewpager gets reinitialized, and since the image page has lazy loading (which isn't triggered) that page stays empty.

I'll create a PR that only refreshes the description page, where the personal note is being displayed on.
