### ISSUE TITLE
Waypoints of own caches hidden on cache map (OSM)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8333]
I noticed the following behaviour with 2020.05.12-NB which I consider to have changed only recently.
(Somehow connected to #8300 )

Steps:
0. Use OSM map
1. Enable hiding of own and found caches in c:geo settings
2. Open an owned cache which has waypoints with coordinates
3. Open map for this cache

Actual result:
Cache icon is shown, waypoints are missing

Expected result:
As also discussed in #8300 I would expect all cache information being shown in the map for a certain cache. With Google Maps this function works as expected, problem only on OSM.
I am pretty sure, that this worked on OSM few weeks ago.

**Comment by moving-bits** [comment]
@Lineflyer 
How to proceed with waypoints hiding? Have you seen https://github.com/cgeo/cgeo/issues/8300#issuecomment-626227004?

**Comment by Lineflyer** [comment]
Well, this issue is about another thing. Not speaking about any hiding of special waypoint types but a general regression for me, which should be fixed. Of course somehow strategically related to #8300. I will also take a look at your commt there.
