### ISSUE TITLE
[Nightly] c:geo crashes while filtering a list (Transaction too large)

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8343]
**Describe the bug:**

c:geo crashes on filtering large lists

**To Reproduce:**

1. open list "All caches" (as this may be of reasonable size - mine has 15220 caches right now)
2. select "Filter" and set any filter (over here e. g. "Not Found" which would result in about 9k)

**Actual behavior/state after performing these steps:**

Most of the times filtering takes a few seconds ... even some seconds with black screen ... but then c:geo just crashes. Sometimes it even shows the filtered list, and in very rare cases you can even show the listed caches on map, but after a few seconds c:geo eventually crashes anyway.

**Expected behavior/state after performing these steps:**

Show (and let me work with) the filtered list instead of simply crashing.  ;)

**Version of c:geo used:**

2020.05.14-NB-6ec80da

**Is the problem reproducible:**
Yes

**System information:**
```
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.0.0.190(C431E19R2P5)
c:geo version: 2020.05.14-NB-6ec80da
Google Play services: disabled - 20.15.16 (120400-309763488)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (17,4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (17,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (17,4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (267,1 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
```

**Additional context:**

line 103 in attached logcat reads "Transaction too large" ...
In this very second 2020.05.15-NB-21c408d appeared - tested - same same.

[logs-2020-05-13-21-20-21.zip](https://github.com/cgeo/cgeo/files/4631361/logs-2020-05-13-21-20-21.zip)

**Comment by Lineflyer** [comment]
Probably realted to #5860

**Comment by MagpieFourtyTwo** [comment]
Yep, maybe - although the way it happens now is definitely younger than four years, cause I already used this way of displaying interesting caches several times in the last years, without crashing.

But OTOH the count of offline saved caches has increased and has now possibly crossed the border ...

**Comment by Lineflyer** [comment]
Related to #9188?

**Comment by MagpieFourtyTwo** [comment]
Unlikely. Although effect and error message look similar (transaction too large), there are different reasons:

Over here it's just because of the "intentional" (mis)use of too much memory (the routine is trying to deal with all caches of a list in memory, which is not a good idea with "huge" data masses in limited environments), while over there I guess we have a data/db problem which leads to massive increase of memory allocation - unintentionally, of course.

So, in contradiction to #9188, where we seem to have a bug related to history track data, over here it's "just" a problem of concept.  ;)

**Comment by eddiemuc** [comment]
Should be solved with newest nightly, @MagpieFourtyTwo can you please verify?

**Comment by MagpieFourtyTwo** [comment]
Filtered several lists, but the ``Transaction too long`` did not appear again - IOW: WFM.  ;)
Ok, there are some crashes from time to time, esp. when leaving a list, but I guess this is not related.
Thanks a lot for re-working the filter stuff!
