### ISSUE TITLE
org.apache.commons.io.IOUtils.closeQuietly() is deprecated as of version 2.6

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8345]
Currently we can not update (or maybe remove) org.apache.commons.io because of deprecated/failing functions. 
Suggestions is:
- Please use the try-with-resources statement or handle suppressed exceptions manually.

see http://commons.apache.org/proper/commons-io/javadocs/api-release/deprecated-list.html

**Comment by feuerbeere** [comment]
UPDATE: Per the [Release Notes](https://commons.apache.org/proper/commons-io/changes-report.html), it was un-deprecated in 2.9.0 (2021-05-22).

**Comment by bekuno** [comment]
@feuerbeere Many thanks for this information. I was not aware, as we have to stay on version 2.5 - commons-io 2.6 uses java.nio.file.Path - which is first contained in Android API26.
