### ISSUE TITLE
FIlter for caches which I favorited myself

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8377]
**Is your feature request related to a problem?**
I want to see which caches on my found list I gave a favorite point to

**Describe the solution you'd like**
There should be a filter in Filter/Favorites or Filter/With own information for this

**Describe alternatives you've considered**
None in c:geo

**Additional context**
From support mail

**Comment by jakedot** [comment]
Could this also be implemented by introducing a new virtual list, like the History list? Then you could filter by list with it, if I didn't confuse the virtual/real list concepts here...

**Comment by eddiemuc** [comment]
PR #10913 adds a filter for caches I favored myself. It also adds the ability to OC connector to set this attribute on caches
