### ISSUE TITLE
GooglePlay: targetSdkVersion 29 (Android 10) necessary from Nov 2, 2020

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8382]
From https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

API level requirement | Starting date
-- | --
Android 10 (API level 29) | August 3, 2020: Required for new apps <br />November 2, 2020: Required for app updates

The Google Play migration guide https://developer.android.com/distribute/best-practices/develop/target-sdk.html targets today version 28, but there are guides for Android 10 e.g. at 
https://developer.android.com/about/versions/10/migration
https://developer.android.com/about/versions/10/behavior-changes-10

**Comment by okainov** [comment]
Isn't it the same as  https://github.com/cgeo/cgeo/issues/8120?

**Comment by bekuno** [comment]
> 
> 
> Isn't it the same as #8120?

No. 
Google Play does not require a minSdkVersion.

**Comment by moving-bits** [comment]
closed with #8436
