### ISSUE TITLE
Search uses filter/hide settings from map

### ISSUE THREAD

**Issue by ReeseSebastian** [cgeo/cgeo#8383]
**Describe the bug:**
When using the search (e.g. all caches of one owner) the filter/hide settings from map are used but cannot be changed in list view.

**To Reproduce:**
1. Go to 'Map -> menu -> hide -> hide own/found'
2. Go back and go to 'Search'
3. Search for caches from one owner or type in address.

**Actual behavior/state after performing these steps:**
Found caches are not listed. Setting of hiding/showing caches is not reachable.
No hint, that result list is being filtered by settings made on map.

Must go back to map, disable hiding of found caches, go back to search and perform search again (re-enter search term)

**Expected behavior/state after performing these steps:**
Found caches are listed or setting of hiding/showing caches should be reachable from list view.
Instead: visible hint of activated filters made on map.

**Version of c:geo used:**
2020.04.25

**Is the problem reproducible:**
Yes

**Comment by Lineflyer** [comment]
I perfectly understand the problem, however in that case the map setting is only a "shortcut" to the global setting in Settings - Cache-Details - "Hide own/found".
So changing it on the map menu will change the global setting. This is however special to this particular setting.

At the end all the filtering in c:geo needs to be reworked into a new concept (which is already addressed here in some old issue).

**Comment by Lineflyer** [comment]
Closing here, see posting above. It needs to be redesigned as part of the filter concept.

**Comment by eddiemuc** [comment]
It would actually help me to keep this as a reminder that this needs to be done as part of filtering concept. I hope it is ok to reopen?

**Comment by Lineflyer** [comment]
Sure...I was in cleanup mode :)

**Comment by eddiemuc** [comment]
After some thinking, my proposal would be to leave the hide-flags in c:geo (maybe make four out of it, e.g. hide-own, hide-found, hide-disabled, hide-archived) but **solely** for usage in Map Viewer. Reason is that I can see here the practical usage of having such "quick select flags".

In contrast, all other searches (including e.g. keyword search, owner search) would not use these flags any more. Consequently, their setting could be moved out of the Settings as well - setting them in the map viewer would be enough.

The new "search by filter" function does already not include the hide-flags in its query.

Would this be an acceptable solution?

**Comment by Lineflyer** [comment]
I am still thinking about the optimum solution to combine/seperate/remove old and new filters and the hierarchy between them.

My current idea would be:

- Have an instance of the new filter in lists which is effective on lists only (already implemented)
- Have an instance of the new filter on map which is effective on map only (already implemented)
- Also replace the current global cache type filter by an instance of the new filter methods which then sets both of the above mentioned instances to the filtering defined here

So various use cases could be covered:
- Global filter is still in main menu but offers more options which are applied to the whole app (as users are used to even today)
- Alternatively users can setup a filter for the map only or for lists only by (instead of using the global filter). 

Would that be technically feasible and understandable/meaningful for users?

**Comment by Lineflyer** [comment]
I will take the above comment into a new issue (its offtopic for this specific issue).

**Comment by eddiemuc** [comment]
> I will take the above comment into a new issue (its offtopic for this specific issue).

Ok, I will answer in new issue then :-)

**Comment by eddiemuc** [comment]
@Lineflyer what about my original proposal wrt future of the "hide"-flags in map viewer?

**Comment by eddiemuc** [comment]
I am against wiring the hide-settings to the global filter. They are really specific to map viewer, they don't make sense in this form anywhere else. This is the only place I would apply them.

What about placing the Filter icon at the bottom of the map screen, to left or right to quick settings icon?

**Comment by fm-sys** [comment]
@eddiemuc I guess we can close here. Or is there anything which still needs to be done?

**Comment by eddiemuc** [comment]
Please leave Open for now, I want to take a closer look

**Comment by eddiemuc** [comment]
Sorry, I confused this issue with another. This one I think we can close
