### ISSUE TITLE
geolutins.com down

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8385]
Our website test showing geolutins.com service is unavailable since a few days.
@kumy Can you contact the owner and notify him / ask for status?

The website is returning a 403 error.

**Comment by kumy** [comment]
mail sent to David.

**Comment by Lineflyer** [comment]
Could someone temporary disable the watchdog tests as well?

**Comment by moving-bits** [comment]
> Could someone temporary disable the watchdog tests as well?

will do

**Comment by Lineflyer** [comment]
The website is up again, so I assume the API is up as well.
We could tackle #8392
