### ISSUE TITLE
Variables cropped and unreadable in Waypoint Calculator

### ISSUE THREAD

**Issue by bammerlaan** [cgeo/cgeo#8388]
**Describe the bug:**
When I use the waypoint calculator, any variables or subvariables I enter are cropped and unreadable. Hard to explain, this image should show you:
![Screenshot_20200530_145942_cgeo geocaching](https://user-images.githubusercontent.com/3306437/83329314-0c5f1a80-a289-11ea-904b-3076d33b733c.jpg)

**To Reproduce:**
1. Go to Add Waypoint
2. Press on the unfilled coordinates
3. Press on "Calculate coordinates"
4. Press on one of the numbers to change them into variables. These variables are not shown but rather cropped to show only their right sides.

**Version of c:geo used:**
2020.04.25

**Is the problem reproducible:**
I checked on my wife's phone, but the problem does not occur there. She uses a Fairphone 3, for what it's worth.

**System information:**
```
--- System information ---
Device: BLA-L09 (BLA-L09, HUAWEI)
Android version: 9
Android build: BLA-L09 9.1.0.345(C432E6R1P12)
c:geo version: 2020.04.25
Google Play services: enabled - 20.15.16 (100408-309763488)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: disabled archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (18.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (18.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (18.4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1.4 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   extremcaching.com: Logged in (Login OK)
   opencaching.nl: Logged in (Login OK)
Geocaching.com date format: d.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by moving-bits** [comment]
Currently both parts (upper case variables and lower case variables) are two-columned. We could make this either fixed 1-column each, or we could try to make it flexible, depending on available space and amount of variables (1+1, 1+2, 2+1, 2+2 column layout).

**Comment by Lineflyer** [comment]
@bammerlaan Did you set any kind of custom font, custom resolution or similar screen setting? The font looks a bit non-standard to me.

**Comment by bammerlaan** [comment]
Ah, you're right! Well, in a way - Huawei lets you change fonts between a number of options, but changing to the first option (probably standard Android) fixes the problem. So yeah, whether the c:geo team needs to take into account such situations is questionable. 

(On the other hand, this is the first app to give me trouble, but I wouldn't blame you if you don't want to go to the trouble of trying to fix this.)

**Comment by Lineflyer** [comment]
AFAIK there are some style options which could be the culprit here. We seem to often used fixed pixel sizes instead of relative. Just guessing however.

The problem with those styles is the unability to test it on a large variety of devices with all their customization possibilities. Meaning...is we try to fix we could break it on other devices....unless we find a clear cause.

**Comment by Lineflyer** [comment]
Will become obsolete once we the new waypoint calculator is ready, respectively the new dialog will hopefully have a better structure.
Therefore closing here as "wont fix" as in some of the next releases the current dialog is planned to be replaced.
