### ISSUE TITLE
Codacy failing

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8395]
We recently have Codacy failing to analyze a PR:

![image](https://user-images.githubusercontent.com/3754370/83349518-c4e29800-a335-11ea-9588-18e0a434054f.png)

Happened at least twice this weekend. AFAICS there's no further hint to the cause for this error, and the log is empty.

**Comment by Lineflyer** [comment]
No idea...trying to view the analyze logs it reports back "Server internal error", so I guess and hope its a codacy internal temporary problem. Lets monitor it.

**Comment by Lineflyer** [comment]
I have no idea why its failing. It does not provide any clue.

Either I readd the integration via cgeo-ci-bot or someone can tell me how we can instead use the Codacy GIthub app.

**Comment by Lineflyer** [comment]
I reintegrated Codacy and it seems to work now, but only partly.
For some reason it fails to analyze the PRs provided by @bekuno 
I have no idea why...maybe it only affects the existing old PRs. Let see.

**Comment by Lineflyer** [comment]
It tells me "bekuno is not part of your authors list". But I can see you as member of the organization. Maybe a changed mail address?

**Comment by bekuno** [comment]
I'm connected to codacy with my GitHub-Account.
In Codacy I am member of two cgeo organizations - one with the GitHub icon, the other with a building symbol. In the second I see other user from the core team.

**Comment by Lineflyer** [comment]
Yeah...I also see two of them. Do your commits contain your mail adress?

**Comment by bekuno** [comment]
No, a mail adress should not contained in commit messages.

**Comment by Narrat** [comment]
Not in the message, but it is formally part of a commit as it includes user.name and user.email

**Comment by moving-bits** [comment]
@Lineflyer 
Thanks for re-integrating Codacy

@bekuno 
email address and username are part of your Git configuration, see the variables @Narrat mentioned

**Comment by Lineflyer** [comment]
> @bekuno
email address and username are part of your Git configuration, see the variables @Narrat mentioned

Yes, it would be my guess, that user.mail is missing, which Codacy uses to identify if those should be tested.

**Comment by bekuno** [comment]
I set now in my git config the same mail address as in GitHub.
(although I am no friend of presenting this)

**Comment by bekuno** [comment]
But now my commit to a own PR was rejected...
... will try it with the next PR.

**Comment by bekuno** [comment]
My default GitHub mail settings are:
![grafik](https://user-images.githubusercontent.com/32555742/84082299-ea2f7000-a9df-11ea-81d0-2b78992726de.png)

**Comment by bekuno** [comment]
Now a tree state:
![grafik](https://user-images.githubusercontent.com/32555742/85933896-5fee7380-b8dc-11ea-99fe-9e82b6373630.png)

I asked the codacy help - will wait for the answer.

**Comment by bekuno** [comment]
The crowdin team trys to find a reason.
This was a one time problem, so closing now.

**Comment by bekuno** [comment]
Update from Codacy:
~~~
Ivo (Codacy)
Jul 13, 2020, 11:31 AM GMT+1

I'm happy to tell you that the issue stoping your PRs has been fixed. Please let me know if any of your new commits display this behaviour again.
~~~
