### ISSUE TITLE
Exclude external code from Codacy

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8396]
A huge portion of issues remarked by Codacy come from external code we integrate, namely
- MapsWithMe API, and
- viewpagerindicator

Can we configure Codacy to ignore those files / directories / libs?
This would help to focus us on those Codacy issues we can do something about.

**Comment by Lineflyer** [comment]
I logged into Codacy via cgeo-ci-bot and set the directories for mapswithme and viewpagerindicator (incl. all subs) to the ignore pathes.
Not sure if we could also a codacy.yaml config file...

Lets first see if the setting works.

**Comment by moving-bits** [comment]
Seems to work, Codacy does not list files of those two projects any longer, issue count is down to < 800.
