### ISSUE TITLE
Remember flag to not create waypoints from note on cache update

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8415]
Taken from https://github.com/cgeo/cgeo/issues/8078#issuecomment-639836684 by @MagpieFourtyTwo:

[...]
> c) Let automatic waypoint parsing be blockable on a per cache basis.
[...]
> with c) being implemented you could then load a cache, delete unwanted waypoints, and block further extraction for this cache, if needed.

This in fact works really good - with one issue, I just stumbled upon: On refreshing the offline saved listing, this flag seems to get lost and waypoints are automatically created again, thus on every refresh (to e. g. see newest logs), the intended effect gets lost and you again will have the whole bunch of annoying useless waypoints.

TMALSS: Would be great if this flag would be permanent, i. e. survive refreshes, thus lives until it will be explicitly unset by the user again (as I had expected it anyway).

**Comment by moving-bits** [comment]
@MagpieFourtyTwo
Should be fixed with #9739 since a couple of months - does it work for you?

**Comment by MagpieFourtyTwo** [comment]
Thx for the reminder (and of course for the fix) - yes, it works, can be closed.

**Comment by moving-bits** [comment]
Thx for cross-checking.
