### ISSUE TITLE
Deactivation of rotation only after map restart

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8425]
- Enable auto rotation on GMaps
- Click compass rose
- Select OK to disable auto rotation

Result:
After the dialog is confirmed the map is set northbound once but still rotates, only after leaving and reentering the live map its northbound again permanently

Same seems to apply if you use the map rotation menu to change from Auto to Off (unverified)

Expected:
No map restart needed or restart triggered automatically

Device:
Samsung Galaxy Tab S4, Android 9

2020.06.07-NB

**Comment by moving-bits** [comment]
Note to myself for the first issue: Deactivating via compass rose is done in `GoogleMapView`. Updating settings is done, but we need to set an additional flag in `GooglePositionAndHistory`.

Setting to "off" seems to work for me - no more map rotation then. (But map does NOT get reset to northbound.)
