### ISSUE TITLE
Kartenthemeverzeichnis kann nicht geändert werden

### ISSUE THREAD

**Issue by winkamol** [cgeo/cgeo#8426]
**Describe the bug:**
Beim Umzug auf ein neues Smartphone konnten keine Kartenthemes installiert werden. Bei den Offline Karten kann ein Verzeichnis ausgewählt werden, bei den Kartenthemes jedoch nicht, selbst wenn manuell der Pfad eingetragen wird, kann kein Theme geladen werden.

**To Reproduce:**
Gehe zu Einstellungen - Karten - Kartenthemes

**Actual behavior/state after performing these steps:**
Das Verzeichnis kann nicht ausgewählt und Themes nicht ausgewählt werden.

**Expected behavior/state after performing these steps:**
Es hätte ähnlich wie bei den Karten ein Verzeichnis ausgewählt werden sollen und dieses aktiviert werden.

**Version of c:geo used:**
2020.05.31-RC

**Is the problem reproducible:**
Yes 

**Screenshots:**
Das Verzeichnis zeigt keine Ordner und nur ein leeres Kästchen mit Punkten daneben. Es wird auch in sämtlichen darüber liegenden Ordnern nichts angezeigt.

**System information:**
```
No data availlable.
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
Kann es eine Fehlbedienung sein:
Du musst bei der Auswahl nicht in das Verzeichnis mit den Themes sondern eine Ebene darüber das Verzeichnis auswählen, in dem sich die Themes befinden.

**Comment by winkamol** [comment]
Ich hatte die Ordnerstruktur von meinem alten Gerät, das funktioniert hat übernommen, dennoch funktioniert es nicht. Screenshot ist anbei. 

⁣Viele Grüße

Patrick ​

**Comment by Lineflyer** [comment]
Man kann leider keinen Screenshot per Mail an Github senden. Du kannst ihn allerdings auf der Webseite hochladen.

**Comment by winkamol** [comment]
Hallo Lars,

Ich habe es inzwischen geschafft es einzubinden, wenn auch nur durch
Installation der nicht beta Version und wiederherstellen meiner alten
Sicherung mit den Einstellungen.

Möchtest du dennoch den Screenshot?

Danke dennoch für die schnelle Rückmeldung und viele Grüße

Patrick

Lars <notifications@github.com> schrieb am Mi., 10. Juni 2020, 10:15:

**Comment by Lineflyer** [comment]
Danke für die Rückmeldung, ich schließe das Ticket.
Ich konnte bei der aktuellen Beta-Version kein Problem in der Themenauswahl feststellen.

Ich vermute der Fehler lag wirklich darin, dass du bei der Auswahl nicht in das Verzeichnis mit den Themes gehen musst,  sondern eine Ebene darüber das Verzeichnis selbst auswählen musst, in dem sich die Themes befinden.
