### ISSUE TITLE
Invalid link to Google Maps SDK

### ISSUE THREAD

**Issue by Logiisch** [cgeo/cgeo#8430]
**Describe the bug:**
The link for getting an API key for Google Maps doesnt work anymore.

**To Reproduce:**
1. Go to 'readme.md'
2. Click on Link "Maps SDK for Android: Get an API Key"

**Actual behavior/state after performing these steps:**
You will get an HTTP 500 error

**Expected behavior/state after performing these steps:**
The link should redirect to a form for applying to a API Key

**Comment by okainov** [comment]
It would me much easier if you provide the correct link, so maintainers (or even you) could just replace the link instead of wasting some time searching it :)

**Comment by moving-bits** [comment]
See #8417, seems to be a temporary problem of the websites involved. Currently both links mentioned in the linked issue do work.
