### ISSUE TITLE
Feature request  to show adventure labs on map 

### ISSUE THREAD

**Issue by simrebel** [cgeo/cgeo#8433]
Anyway to display adventure labs on the live map ? 
no other functionality  needed,  unless you can clock on it and it would open the AL app 
with so many of them coming out i  usually forget to check the AL app to see if any are around

**Comment by Lineflyer** [comment]
Nope, that is not possible as Groundspeak AFAIK limits the availability of this data to their app.

**Comment by Lineflyer** [comment]
I doublechecked again:
- Those "caches" are neither available via their website nor or there any kind of exports possible (like GPX)
- As adventure labs have an event/position triggered component you will anyhow need a dedicated app to play/solve them.

A (not nice) workaround is, to just add a c:geo internal cache by visual copy&paste from the Adventure Lab app to have a waypoint reminder for those lab caches you are interested in.
