### ISSUE TITLE
Terracaching browser/export link wrong

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8449]
Indeed received this one on support mail:

- Import a GPX from Terracaching.com
- Open details of an imported cache (in this case TC9B2)
- Select Menu - Open in Browser

Result:
404 in browser

Expectation:
Cache webpage should be shown

Analysis:
The generated link is `http://www.terracaching.com/Cache/TC9B2`
It seems the scheme changed on the website and is now `https://play.terracaching.com/Cache/TC9B2`  (Play instead of www is the problem, http will be redirected to https anyway).

**Comment by moving-bits** [comment]
@Lineflyer 
Can you provide me a GPX file to test a potential fix?

**Comment by Lineflyer** [comment]
In your inbox now.
