### ISSUE TITLE
Live map cache count not localized for french

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8450]
Form beta feedback:
Issue: in french, when only one cache in the map , the label is "one cache" instead "une cache"

Comment:
I could not find a missing translation for one cache, so I am not sure where this issue comes from?!

**Comment by Lomanic** [comment]
I confirm this behavior.

**Comment by bekuno** [comment]
The string "cache_counts" is missing in the french strings.xml both for master and release.

**Comment by bekuno** [comment]
The french strings.xml was not updated until now. The approval of this string was 5 days ago.

**Comment by Lineflyer** [comment]
I manually translated and approved it again on Crowdin, but seems it is just not transmitted.

Coincidentally another strange thing was reported today on support mail:
- Have a list A which contains one geocache
- Have a list B which contains no geocache
- For both lists A and B the title shows "One cache" if you are using french language in c:geo

Not sure if this is related, but its strange. I would think, that for amount "other" also the english string should be used and so result in "0 caches" be shown for an empty list.

**Comment by Lineflyer** [comment]
After manually deleting the file in the repo the update from Crowdin looks better (#8453). 
I have no idea, what happened here. I also manually downloaded the translated file from Crowdin and it contained `cache_counts` but at another position within the file. 

I will merge #8453 to fix this issue and also try to backport this rather important strings to the `release` branch. 

If something like this happens again a possible (but not satisfying) solution is to remove the affected strings.xml and wait for the Crowdin integration to push it again.

**Comment by Lineflyer** [comment]
Correction:

As `cache_counts` is a rather important string for a rather often used langauge I will backport the missing strings to `release` manually, then merge upstream to `master` and let only then Crowdin create a new commit, which is hopefully OK.
