### ISSUE TITLE
[Nightly] Crash when opening map

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8451]
**Describe the bug:**
Just installed the very latest nightly as of 15.06. - and opening [Live Map] or map from Listing page immediately crashes c:geo.

More tomorrow - if necessary.

**Comment by MagpieFourtyTwo** [comment]
Version used: 2020.06.15-NB-88d7f11

Map does not matter, *every* map crashes, no matter if "Show history line" is activated or not. Tested "Adjust text size" too, no effect neither.

**Comment by MasterPlexus** [comment]
I could confirm the behavior. See attached log.
[Log_2020-06-15_06-05-40.txt](https://github.com/cgeo/cgeo/files/4777995/Log_2020-06-15_06-05-40.txt)

**Comment by moving-bits** [comment]
I'll look into this.

Did you load a GPX track before the crashes started?
If so, you could try the following:
- go to preferences => system => view settings (at the end of the page)
- activate edit mode
- look for "trackfile" entry and delete it

**Comment by MagpieFourtyTwo** [comment]
No trackfile entry over here.
To be honest, I have not even found the menu entry to import GPX files ... ;)

**Comment by Lineflyer** [comment]
Same here. Did nothing else than upgrading from yesterday's nightly to todays nightly.

**Comment by MasterPlexus** [comment]
Same for me:
- no GPX-Load (also did not see the menu point for that?)
- just updated to latest Nightly

**Comment by MagpieFourtyTwo** [comment]
> Same here. Did nothing else than upgrading from yesterday's nightly to todays nightly.

Me2.

Do you need any further info from (my) crashing c:geo?
If not, I would go back to yesterday's nightly now ...

**Comment by moving-bits** [comment]
Thanks for your replies. Won't be able to dive into this until tonight.

> Do you need any further info from (my) crashing c:geo?

No, thanks. I need to debug into this and see where the missing validity check is.

**Comment by MagpieFourtyTwo** [comment]
> If not, I would go back to yesterday's nightly now ...

Way easier said than done, as the restore of today's backup (performed with crashing 2020.06.15-NB-88d7f11) did not work after downgrade to yesterday's apk.

Lucky me had several backups and even matching apks (once bitten, twice shy), but still had to go back till 11.06.20 until I was able to restore database and settings. Newer versions just ignored my backup, claimed that there are no backups yet, or they eventually recognized and listed the backup, even pretended to restore - but effectively did nothing.  :/

My downgrade procedure:
1. stop c:geo, remove from memory and uninstall
2. re-install from saved apk
3. start c:geo, end it, remove from memory, restart ...
4. ... until it asks for allowance to access storage and position
5. hope for the automatically asked "db is empty - do you want to restore"
5a. if the restore question does not appear: go to 1. and use older backup and/or apk
6. end it, remove from memory, restart
7. restore settings
8. end it, remove from memory, restart
9. check db and setting ...

Anything wrong and/or optimization potential?

**Comment by Lineflyer** [comment]
> Way easier said than done, as the restore of today's backup (performed with crashing 2020.06.15-NB-88d7f11) did not work after downgrade to yesterday's apk.

That should have worked.

I checked this as well and I think just discovered an unrelated bug(i.e. c:geo is using the fallback storage instead of the default `/cgeo/` directory in the user accesible internal memory).
I will look into it and open a dedicated issue.

**Comment by MagpieFourtyTwo** [comment]
Maybe - but if so, why did it accept the backup/apk combination as of 11.06. ...?  Moreover I already performed several restores w/o any problem.  Or was the bug "invented" on 12.06.?
My guess was a possible db change due to GPX import and track data storage ...

Nevertheless, I would greatly appreciate an additional (prominent) hint when db layout changes, which de facto renders older backups useless. Easiest would of course be in the changelog, but this could be too late (for the optimistic not-so-frequent-backuppers ;) ) so even better would be to have such a warning in the update notification ... would this be possible?

This way one can keep at least one backup and appropriate apk dated before the db change. Although my loss of data was bearable this time, but it would be more of a big deal, if everything will pass over Jordan ...

Or, would it even be possible to copy the apk to the backup directory when performing a backup ...?

**Comment by Lineflyer** [comment]
There seem to be several problems involved here, which I still need to investigate.
For your case, please try the following:
- Install nightly 2020.06.13-NB (or before)
- Start and provide permissions
- Upgrade to 2020.06.14-NB (the last before the crash problem)
- Restore settings and cache database

That should get you going.

**Comment by MagpieFourtyTwo** [comment]
Ok - but can someone please revert the current nightly's apk download to yesterday's version?
To prevent additional hassle ... thx!

**Comment by moving-bits** [comment]
> Maybe - but if so, why did it accept the backup/apk combination as of 11.06. ...? Moreover I already performed several restores w/o any problem. Or was the bug "invented" on 12.06.?
> My guess was a possible db change due to GPX import and track data storage ...

I "invented" the bug yesterday with merging #8376, see the fix in #8459.

There is no db change involved with track visualization, as the track's filename is stored as shared preference.

> Nevertheless, I would greatly appreciate an additional (prominent) hint when db layout changes, which de facto renders older backups useless.

Anyway, a db change should not prevent you from using an older backup, as we carefully maintain the upgrade path within the db. Theoretically it should be possible to start with a three year old c:geo db with current nightly program version (although I've never tried it).
But this is one way - you cannot downgrade (as the older version of c:geo does have no idea of what got invented by later versions and how to revert the data). So if you have the need to downgrade to a c:geo version with an earlier db scheme, you need to uninstall c:geo, copy the old db backup file to your mobile device and install the old c:geo version. But this is only necessary when db changes are involved.

Would it help you, if we include the current db's scheme version number into the release notes? (Db scheme number of a c:geo db backup can be viewed with tools like `HeidiSQL` or `DB browser for SQLite`.)

> Or, would it even be possible to copy the apk to the backup directory when performing a backup ...?

Don't think that this file is accessible to us on a non-rooted device.

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
Regarding the nightlies: Please be aware, that those are alpha versions without any warranty. Its always work in progress and might have issues. 
We do not plan to have any archives or special downgrade mechanisms for those. 

If you want to be prepared just store some of the latest NB and their backups on your device (as you did).

In normal cases such severe problems will be solved shorttermed. Righr now I merged the fix and build a new (extra) NB.
It should be ready to download while I am writing or in a few minutes.

**Comment by Lineflyer** [comment]
NB is built and on server.

**Comment by moving-bits** [comment]
> NB is built and on server.

Thanks.

**Comment by moving-bits** [comment]
> And, of course: Thanks A LOT for this immediate fix! It is always a real pleasure to see how quickly help is provided here again and again.

I can mirror this: Thanks for consistenly using our nightlies and providing feedback to us - this helps a lot in finding bugs at an early stage before we could deliver them as part of an official release.

**Comment by moving-bits** [comment]
> Yep, I'm pretty aware of the risk - and it's in fact the reason why I make a backup nearly every day

Would it help you if we automatically add a datestamp to the db backup, like `yyyy-mm-dd cgeo.sqlite`? It would prevent overwriting an existing backup file, and it would give you an idea how old a db backup is. (This automatic adding of datestamp could be made optional, default no, to be activated by power users only.)

**Comment by MagpieFourtyTwo** [comment]
I greatly appreciate your effort, but I guess this (alone) would not make much of a difference, as I add. backup the settings (full mode) and the matching apk, too. Right now I simply take the entire backup folder, copy it to external storage as `yymmdd_backup` and (sometimes) add the matching apk, in order to definitely be able to restore the entire installation (after moving back the backup dir, of course). And in very rare cases (like yesterday) I even have several backup folders for the same day.

So, if you still wish to make my life easier (while I think, these few clicks of mine are nothing, esp. compared to your work, so I would have no problem if things just stay as they are ;) ), you could rename the entire backup folder to `yymmdd_hhmm_backup` prior to storing a new backup (`hhmm` to distinguish "before" and "after" an update, to be able to find an appropriate backup, which, although in the most cases is younger than the apk version one just tries to restore to, but OTOH should be a few minutes older than the non working apk ... ;) ). And poss. put an option or Menu entry to backup both (db and settings (full)) with one click, which would save another two clicks (moreover folder renaming would not work really good without saving both in one go, anyway ;) ).

And - as I don't like automatisms which can not be disabled, esp. if they don't work perfect (and we all know, perfection is an illusion :) ) - it would poss. be a good thing to just ask the user if he wants to select a particular backup to be restored, esp. if the automatic routine does not find (the right) one ... or the selection dialog may open on every restore and just defaults to the directory where c:geo would have taken the backup from anyway ...?

**Comment by moving-bits** [comment]
Ok, pretty much to be considered for a very specific use case... As you have a well established way to handle this I think we'll stay with the current implementation for now.

**Comment by MagpieFourtyTwo** [comment]
As for the creation of backups: Agreed.

As for restore: Would this "Select Backup Destination" dialogue be an option?
