### ISSUE TITLE
Empty list has wrong cache count in French

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8456]
The fix for #8450 did not fix this strange bug:

- Have a list A which contains one geocache
- Have a list B which contains no geocache

Result:
For both lists A and B the title shows "Une cache" (=One cache)  if you are using french language in c:geo

Expectation:
- List A : "Une cache"
- List B : "0 caches"

**Comment by Lineflyer** [comment]
It might be, we need to add a quantity "zero" for certain languages:
https://stackoverflow.com/questions/27824170/in-french-plural-system-treats-0-as-other-instead-of-one

**Comment by Lineflyer** [comment]
I guess we have this problem also for other language which are equally handled and in more places, where we replaced things like "1 cache" with "One cache".

How about the easiest solution:
- Change the string for "one" on release branch for french to "%1d cache" as a first fix in french
- Change all such occurences in our plurals strings in the english source from using a number word to using a variable.

The only other (perfect) solution is to introduce all non used quantities like "zero" and "many" for all the plurals we are using in the app.

Any opinion?

**Comment by bekuno** [comment]
Is it possible to add the "zero" value direct in crowdin without add them in the english template? I did not found this possibility, but maybe it is possible.

**Comment by Lomanic** [comment]
I find it weird to have "2 caches" with digits but "Une cache" in full letters, I opt for "%1d cache" for 0/1 cache.

**Comment by moving-bits** [comment]
From a reader's perspective I would prefer strings like "One cache", "2 caches", "42 caches" etc. - but from reading https://developer.android.com/guide/topics/resources/string-resource#Plurals I think that's not what the `<plurals>` mechanism is meant to be. It looks like its intention is solely meant for pure numbers. And the rules for those numbers seem to vary a lot from language to language, according to the docs we need to support `zero`, `one`, `two`, `few`, `many` and `other`, although most languages only use one or two of those identifiers. And `one` does not necessarily mean "1", but some group related to ones (could include 21, 31, 41 as well, for example) - depending on language.

So we should stick to numbers, and offer the other groups as well, although English will only use groups `one` and `other` (and never `zero`, BTW).

**Comment by Lineflyer** [comment]
@bekuno No, we have to change the source.

@moving-bits Exactly. So I think we can fix it as proposed above for now and open a "longterm" issue to use all quantities throughout all plurals string. I remember we had a similar problem in the past with russian as this language also has different usage of plural forms.

**Comment by moving-bits** [comment]
Added myself to assignees - I'll tackle the multiple `plurals` part.

**Comment by Lineflyer** [comment]
@moving-bits 
Seems the addition of all quantities worked fine.
FYI: Crowdin seems to filter the quantities you see for translation depending on the language (e.g. in german it stays with one/other while in russian you will see one/few/many/other, etc.)
Sadly for french zero is not shown as I would have expected...but not a problem as you also replaced everything with numbers instead of words (e.g. "%d cache" instead of "1 Cache"). Should be fine and safe for all languages now.
