### ISSUE TITLE
Crash on map while track is shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8478]
- Using Mapsforge Offline
- Had a track loaded which was shown normal
- Moved around the map

- Map crahes and I am back on main menu
- Happens randomly after moving the map for a while

- 2020.06.20-NB

Logfile:
------- beginning of crash
06-20 11:25:35.581 10150 15165 E AndroidRuntime: FATAL EXCEPTION: LayerManager
06-20 11:25:35.581 10150 15165 E AndroidRuntime: Process: cgeo.geocaching, PID: 10150
06-20 11:25:35.581 10150 15165 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
06-20 11:25:35.581 10150 15165 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.layers.AbstractLineLayer.draw(AbstractLineLayer.java:66)
06-20 11:25:35.581 10150 15165 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.layers.TrackLayer.draw(TrackLayer.java:6)
06-20 11:25:35.581 10150 15165 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
06-20 11:25:35.581 10150 15165 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
06-20 11:25:35.790 15270 15270 E cgeo.geocachin: Not starting debugger since process cannot load the jdwp agent.

**Comment by Lineflyer** [comment]
Addition:
Seems to happen when closing a popup window on map.

**Comment by moving-bits** [comment]
I've received the same error randomly on map startup, but was not able to reproduce it yet. - Probably a race condition between track set/update and drawing. Will try to fix with a bit of synchronization on `pixelTrack` object.
