### ISSUE TITLE
GPX track: Crash on loading invalid GPX track file

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8480]
Taken from https://github.com/cgeo/cgeo/issues/2469#issuecomment-646968107:

after choosing an incorrectly formatted file (like the one exported with the previous track export version, with two lat but no lon tag) c:geo first stutters, then hangs, and finally crashes

**Comment by moving-bits** [comment]
@MagpieFourtyTwo:
From a first debug view: `GPXTrackImporter` handles missing `lon` attribute correctly by ignoring those trackpoints. When trying to load one of the misformatted track files produced by the first trail exporter, it simply returns null  (as signal "track could not be loaded").

What you may have encountered is the "infinite loop problem" described in https://github.com/cgeo/cgeo/issues/8481#issuecomment-647008318 and (hopefully) fixed with #8485.

**Comment by MagpieFourtyTwo** [comment]
Yep, seems so - with the latest nightly it works, c:geo does not crash anymore in both scenarios (misformatted and/or missing GPX file).

Would be perfect if a toast can be displayed, cause without a success or failure message you sometimes may feel a bit left alone in the dark. Esp. as even a valid GPX (e. g. found by automatic scan) may result in displaying nothing at all (if it e. g. contains a cache export). So, perhaps the toast can say s/th like "Trail: Loading GPX {failed|succeeded} (x trackpoints)"

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 
Thanks for testing. Closing this issue then.
For the status toast see #8498.
