### ISSUE TITLE
Routed distance no longer shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8486]
2020.06.20-NB, Brouter installed

- Open cache map on OSM offline map
- The routed line to the cache is shown

- on top right it shows only the straight line distance but no longer the routed distance below that (zick-zack line)

**Comment by MagpieFourtyTwo** [comment]
Works for me.
NB 2020.06.21

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
Oh, you are right. Seems I deactivated the setting to also show the straight distance...or was the setting lost?
Do you use the display of both distances or only one of them?

**Comment by MagpieFourtyTwo** [comment]
Both

**Comment by Lineflyer** [comment]
so...I guess my fault during all the deinstallations / reinstallations, that I turned off to show both which confused me.
