### ISSUE TITLE
Line feeds in log text missing in log view after submit

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8490]
I just saw this today while logging a cache and am quite sure, that I did not see it before. I need however doublecheck it, so this is more a reminder to myself:

- Write a log for a gc cache
- Make sure the log has some newlines / linefeeds in it
- Submit the log
- Switch to logbook tab

- The submitted log is shown without any linefeeds...all in one block.
- After refresh from server the formatting is fine

No idea which recent change could cause this regression...or maybe I did something special in my log without noticing it.

**Comment by Narrat** [comment]
Imo this shouldn't be something new, as I noticed such a behaviour in the past. But as it was something cosmetic, after confirming with the website that the text appeared as it should, it didn't bother me that much. Just wanted to let you know

**Comment by Lineflyer** [comment]
Yes, it was IMHO the case with some formattings used in this special bbcode which we only display correct after getting it as HTML back from the server.
However I cannot remember, that it was all in one line without any linefeeds before.

**Comment by Lineflyer** [comment]
Well, logged 10 caches today. This time all as expected. Closing for now.
