### ISSUE TITLE
History trail active on GoogleMaps altough deactivated

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8510]
Just seen tonight while changing between Google Maps and OSM using 2020.06.20-NB:

- History trail is deactivated in settings
- Open live map OSM, no trail shown
- Change map to Google Maps, trail is shown

Note:
I did not really have a trail at this point, as I was at home. But anyway on Google Maps I can see it due to the position jumps around my home while being indoors

**Comment by MagpieFourtyTwo** [comment]
Same over here, although just "half of the truth".  ;)
IMHO the points are not displayed, but the shadow line is ...
