### ISSUE TITLE
[Nightly] Changing width of customized lines behaves weird

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8512]
**Describe the bug:**

Although setting the width of customized lines works on our Huawei (Android 10.1), it seems to be impossible on our Sony (Android 7.1.1): On the latter you can slide and increase/decrease the value (as well as you can enter a new value numerically), but as soon as you lift your finger (resp. tap [Ok]), the slider jumps back to the previous position and the numbers show the old value again, too.

But: This just seems to be kind of a display problem, as the configuration changes have nevertheless taken place. After switching back to map you will recognize that the lines are now drawn with the new (and seemingly rejected) settings. And after re-entering the settings, the new values are shown now (although sometimes you may have to remove c:geo from memory first).

**To Reproduce:**

1. Go to Settings -> Map -> Width of ... any line
2. Move the slider to a new value (or enter one via keyboard) ...
3. Lift your finger (resp. click [Ok] ...

**Actual behavior/state after performing these steps:**

The change seems to be rejected, cause the previous value will be displayed again.

**Expected behavior/state after performing these steps:**

The new value should be displayed by slider and numeric value,

**Version of c:geo used:**

You will find the c:geo version in c:geo Menu -> About c:geo

**Is the problem reproducible:**

Yes

**System information:**

```
--- System information ---
Device: E6853 (E6853, Sony)
Android version: 7.1.1
Android build: 32.4.A.1.54
c:geo version: 2020.06.21-NB-f7b3600
Google Play services: disabled - 20.21.17 (040408-316502805)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (3,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (3,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (3,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (113,1 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Additional context:**

I would suggest to use the same names for the lines in all dialogues and settings. Esp. the "Individual route" (as it is called in map page menu), should be called the same in the settings to avoid confusions.

Moreover I would appreciate to be able to enter opacity by keyboard, too.

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 
Can you have a look, if this weird behavior also exists when you try to change the "proximity notification" distances or the "waypoint threshold"? They are also using the same technical component "under the hood", but with different parameter settings. Thanks.

**Comment by MagpieFourtyTwo** [comment]
These two (resp. three) work as expected.

**Comment by Lineflyer** [comment]
I have the described problems also with the other sliders (probably fingers to fat ;) ) Therefore I appreciate the textual input.

> I would suggest to use the same names for the lines in all dialogues and settings. Esp. the "Individual route" (as it is called in map page menu), should be called the same in the settings to avoid confusions

Valid and important point. Just a friendly reminder: One problem per issue, otherwise it might get lost. I will take this point into a dedicated issue.

**Comment by MagpieFourtyTwo** [comment]
> I have the described problems also with the other sliders (probably fingers to fat ;) ) Therefore I appreciate the textual input.

Just to clarify: textual input has the same problem on the 7.1.1. Sony, it jumps back as soon as you click [Ok].

> Just a friendly reminder: One problem per issue

Urgs - I stand corrected! ;)

**Comment by moving-bits** [comment]
Verified on Android 7 emulated device, although you can see the new value only after removing c:geo from memory completely and restarting it.
