### ISSUE TITLE
Whereyougo links not recognized

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8514]
Taken from https://github.com/cgeo/cgeo/issues/8472#issuecomment-647181770 by @MagpieFourtyTwo:

BTW; Recognized some WIGs today, which have no WYG-Launch-Button in the overview page.
Examples: GC1MPVZ, GC356P2, GC5VEYE, GC461KF
First thought was, this may be because (most of) the listings are written in two languages, thus offering two cartridge links, and as c:geo then can't decide which to take, it just displays none at all ... possibly.
But the last one (GC461KF) contains just one cartridge link ... that's where I ran out of theories. ;)
Is there an reason for this or is this a bug?

**Comment by MagpieFourtyTwo** [comment]
Possibly the dedicated WYG launch button can even be removed completely, as starting links from cache listing has been corrected with #8472 anyway ...?

**Comment by moving-bits** [comment]
Analyzed above caches:
- GC1MPVZ: Uses "download.aspx" in the link instead of "details.aspx" => need to adapt regexp
- GC356P2: Has two different cartridge links => won't work with the button, neither with the menu entry
- GC5VEYE: same as before
- GC461KF: same as the first one

I will adapt the regexp accordingly.

As for
> Possibly the dedicated WYG launch button can even be removed completely, as starting links from cache listing has been corrected with #8472 anyway ...?

This should probably answered by @Lineflyer as the original request came from him (maybe due to support activity).

**Comment by Lineflyer** [comment]
> This should probably answered by @Lineflyer as the original request came from him (maybe due to support activity).

I would like to keep the activity button there (to promote WhereYouGo and allow more easy handling).
