### ISSUE TITLE
Nearby screen is unusable on RTL devices

### ISSUE THREAD

**Issue by zartom** [cgeo/cgeo#8515]
![Screenshot_2020-06-22-18-43-09-051_cgeo geocaching](https://user-images.githubusercontent.com/1769078/85307177-3dadbd80-b4b8-11ea-8f9f-52bea1335358.jpg)

**Comment by Lineflyer** [comment]
Duplicate of #8043 ?

**Comment by Lineflyer** [comment]
As a workaround please try to add a second supported language to your phone settings (if supported by your device).

**Comment by zartom** [comment]
Adding English as a second language is not an option on the Pocophone F1

**Comment by Lineflyer** [comment]
Sorry to hear. We are however aware of this problem, but as you can read in that other issue, we are still investigating.
