### ISSUE TITLE
Consistent naming of different track/trail/line functions

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8517]
Taken from another issue:

I would suggest to use the same names for the lines in all dialogues and settings. Esp. the "Individual route" (as it is called in map page menu), should be called the same in the settings to avoid confusions

---
We should indeed doublecheck the namings between different menus.
Are there more different wordings in this context? Please report here.

I will assign myself to align this next days.

**Comment by MagpieFourtyTwo** [comment]
> Esp. the "Individual route" (as it is called in map page menu), should be called the same in the settings to avoid confusions.

Moreover it's name should poss. point out the difference to the BRouter direction line more clearly ... but to be honest, I don't really have an idea for a striking name ... maybe s/th like "selfmade route" (in German: Selbst kreierte/gemachte/erstellte), "manual route", "free route" ...? Or perhaps I just have to get acquainted with "individual route" ...?  :)

Nevertheless, another place where the individual route's name should be extended is the toast which appears after adding/removing vias.

**Comment by Lineflyer** [comment]
How about:

1. Individual route
2. History trail
3. Imported track

**Comment by MagpieFourtyTwo** [comment]
Yep. Although the "history trail" is not really a "trail" (in my wording), but in fact the very first meaning of "track" (as it is called in at least Garmin's world for three decades now) ... and additionally you're "tracking" your trail or trip ... ;)

**Comment by MagpieFourtyTwo** [comment]
Ah, perhaps the "Show history trail" entry in "Map settings" should poss. go to the submenu "History trail" ...? (to be honest, a few days ago I searched for the "Hide history trail" entry in the "Hide" menu ...  ;) )

**Comment by MagpieFourtyTwo** [comment]
As for me it's just the last mentioned move of the menu item "Show history track" from "Map settings" to the sub menu "History track".

And perhaps the Map menu entry "Hide" may be renamed to "Hide icons" ...? 

Or may this better be put into an own issue/feature request?
