### ISSUE TITLE
Exports of track (aka 'history line') should be importable on openstreetmap.org

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8519]
**Is your feature request related to a problem?**

Main reason for the (thankfully fulfilled) feature request "Export history trail as GPX" #8424 was to be able to import these track files to openstreetmap.org, in order to use them as templates for improving OSM maps by adding missing tracks or refining incorrect ones.

Most regretfully, osm.org additionally needs the tags `<ele>` and `<time>`, otherwise file upload will be refused.

**Describe the solution you'd like**

Please add the tags `<ele>` and `<time>` (while the value of these does not really matter.  ;) )

**Additional context**

For testing I edited a c:geo history export (created with current nightly) and was afterwards able to successfully import it. The `<trkpt>` section looked like:

```
<trkpt lat="48.42424242424242" lon="9.424242424242424">  <ele>142.42</ele> <time>2006-12-24T18:00:00.000Z</time> </trkpt>
```

Would be great to get these tags added, whereas *real* elevation and time would be nice to have, but do not really matter (at least for the purpose of these OSM imports).  ;)

Moreover (I hope it's ok to put this in here instead of opening an extra issue, as these things are kind of connected), an XML validation (performed by Notepad++) still reports:

```
Validation of current file using XML schema:
ERROR: Element '{http://www.topografix.com/GPX/1/1}gpx', attribute 'version': The value '1.0' does not match the fixed value constraint '1.1'.
ERROR: Element '{http://www.topografix.com/GPX/1/1}time': '2020-06-22 08-30-59' is not a valid value of the atomic type 'xs:dateTime'.
```

First error is because of the not matching GPX declation `<gpx version="1.0"`
and the second because of the misformatted time `<time>2020-06-22 08-30-59</time>` which should be like `<time>2020-06-22T08:30:59Z</time>`

**Comment by Lineflyer** [comment]
Are you sure <ele> is not evaluated somehow be osm.org?

**Comment by MagpieFourtyTwo** [comment]
AFAIK not even the date is checked for plausibility (there was a guy who imported with year 20120 ;) ).
I imported my track with a most definite wrong ele and there were no complains at all.

**Comment by moving-bits** [comment]
I've created a PR #8520 which adds dummy values (set elevation to 0.0, timestamp to current date/time) to the export file.

@MagpieFourtyTwo 
Before merging this: Can you check with osm.org how they react to invalid (or implausible) value for elevation/time, or if there is a way to let them ignore those values on import? I would rather not like c:geo get blamed for erasing all of osm.org's elevation values... ;-)

A more complete solution would be to store elevation and timestamp values while creating the trail, but that would require additional db fields. => This would be a separate task & issue.

**Comment by MagpieFourtyTwo** [comment]
> I would rather not like c:geo get blamed for erasing all of osm.org's elevation values... ;-)

No reason to be afraid, as tracks uploaded to OSM.org are nothing else than just map elements you can select as overlay to be displayed with their map. There is no automatism to automatically integrate track data into map data ... at least as far as I know ... <gd&r> ;)

Anyway - just created another track (with BTW 1094 points, which is a little bit more than I expected, as said the other day, 700 is the current limit) and manually formatted it like so (coords masked and stripped to one line for this posting, of course):

```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="c:geo - http://www.cgeo.org/" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<metadata>
		<name>c:geo history trail</name>
		<time>2020-06-24T01:05:20Z</time>
	</metadata>
	<trk>
		<name>c:geo history trail 2020-06-22 08-30-59</name>
		<trkseg>
			<trkpt lat="49.4242424242" lon="9.4242424242"> <ele>0.0</ele> <time>2020-06-24T01:05:20.000Z</time> </trkpt>
			[...]
		</trkseg>
	</trk>
</gpx>
```

GPX appeared within a minute after upload with no complaints at all and it even displays properly on OSM map:

![cgeo history trail summary an osm org](https://user-images.githubusercontent.com/9889015/85476918-91540000-b5b9-11ea-9694-2291f17ab0fc.jpg)

**Comment by MagpieFourtyTwo** [comment]
Tested in current Nightly - works! :)

Thx!

**Comment by moving-bits** [comment]
> Anyway - just created another track (with BTW 1094 points, which is a little bit more than I expected, as you said the other day, 700 is the current limit)

Just for information: c:geo strips the saved data to 700 points on startup, then adds more points while you're on the move. Thus as long as you're not closing c:geo (either willingly or due to Android memory management) you can have longer trails. - And we still have the option to set this limit to a higher value.

**Comment by MagpieFourtyTwo** [comment]
For at least me this appears to be sufficient in most cases, thus no real need for enlargement. At least not yet.  ;)
But, although I know it's like shouting "Jehova", but what would you think of making this value configurable?
Would perfectly fit as third line following the (hopefully) coming color and width of the history line ...  ;))
This way everybody could decide himself how long (and memory consuming) his history line should be.

**Comment by moving-bits** [comment]
> what would you think of making this value configurable?
> Would perfectly fit as third line following the (hopefully) coming color and width of the history line ... ;))
> This way everybody could decide himself how long (and memory consuming) his history line should be.

I created a separate issue for that, see #8565
