### ISSUE TITLE
[Nightly] Import track from GPX file: Changing directory does not work

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8523]
**Describe the bug:**
If you want to load a track from another directory than the default or last or even automatically found one, you click `[Chose file]`, then search for the directry, tag it with `[X]` and click `[Ok]` - afterwards the content of this directory should be shown to be able to select the GPX to be imported, but ...

**Actual behavior/state after performing these steps:**
... after clicking `[Ok]` the map is there again ...  :/

**Expected behavior/state after performing these steps:**
The content of the chosen directory should be shown to be able to select the GPX to be imported.

**Version of c:geo used:**
Current nightly.

**Is the problem reproducible:**
Yes

**Comment by moving-bits** [comment]
Can reproduce, when c:geo uses the internal `SimpleDirChooser`. Therefore removing the "unverified" label.

Workaround: If you have a file manager installed which supports the `open intents` for directory or file browsing, c:geo automatically opens that file manager. One example of this is `Total commander for Android`.

**Comment by moving-bits** [comment]
Another workaround, without the need of a separate file manager like `Total commander`: Tap on the textbox showing the directory name - it's an editable path:

![image](https://user-images.githubusercontent.com/3754370/85920663-d441fc00-b875-11ea-851e-f95ff4b8f185.png)

**Comment by MagpieFourtyTwo** [comment]
As for me, this issue has been closed a little bit to fast, as there still seem to be two things to be changed:

Scenario: If you want to load a track, a list of automatically found GPX files is shown - this list has a button titled `Chose file`.
But after clicking it, the appearing `SimpleDirChooser` is suddenly titled `Chose directory`.
And if you really chose a dir, which is pretty allowed, clicking `Ok` just closes the `SimpleDirChooser`, map appears and, of course, no track has been loaded.
Just seeing this, the issue still seems to be unchanged.  ;)

Although, if you instead chose a GPX *file*, it works, but this is not obvious to the user.

So, 1. the button text should be changed to `Chose file` and 2. selection of a dir should not enable the `Ok` button.

**Comment by moving-bits** [comment]
> As for me, this issue has been closed a little bit to fast, as there still seem to be two things to be changed:

Thanks for finding those cases. I've created a separate issue for them.
