### ISSUE TITLE
Wrong error message if login to gc.com fails due to wrong credentials

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8528]
- Delete stored login information for gc.com
- Start authorizing again, enter correct username but wrong password

Result:
c:geo reports "Unknown error....consult FAQ"

Expected:
c:geo should report "Wrong user name or password"

I assume that our parsing fails due to changes on the website.
This is not such a minor issue, as many people with wrong credentials contact support not knowing that just their password is wrong.
Furthermore I can no longer distinguish between credential problems and other problems.

Tested with 2020.06.24-NB but assumingly also present on market release

**Comment by moving-bits** [comment]
I'm somewhat lost - there seems to be no error message in the retrieved HTML any longer, that's why our parsing fails and falls back to the general "unknown error" message.

**Comment by Lineflyer** [comment]
Yepp. I have also seen this 200 response in the log.
Lets first wait a bit if they might change it back. Else we just change the string of this message on our side to incl. possible credential failure...not nice but we probably cant do more.

**Comment by UniQP** [comment]
But there's a error message shown on the website, so it should be possible to recognize the wrong credentials.
![image](https://user-images.githubusercontent.com/1321557/85893517-4f160300-b7f3-11ea-9cbc-977d4c11f05e.png)

**Comment by moving-bits** [comment]
Wherever you got it from ;-) this string works perfectly - will prepare a PR. Thanks!
I caught the retrieved HTML using AS debugger, and there have been no visible error messages. Strange.

**Comment by Lineflyer** [comment]
Fixed with 392a4ecb08d055c7175a2d1d1bdf356c228399bc
