### ISSUE TITLE
Caches not updated when storing "all" from live map

### ISSUE THREAD

**Issue by Oskar1983** [cgeo/cgeo#8556]
**Describe the bug:**
Choosing "Store all" on live map does not update previously stored caches.

**To Reproduce:**
1. Go to live map
2. Enable refreshing
3. Click Store all

**Actual behavior/state after performing these steps:**
Previously stored caches are not updated. They keep the "old" stored state. Only new caches are stored, but there is another option for storing only new ones.

**Expected behavior/state after performing these steps:**
All caches on the chosen map area should be stored and previously stored ones should be updated to the current state.

**Version of c:geo used:**
2020.06.14

**Is the problem reproducible:**
Yes

**Comment by MagpieFourtyTwo** [comment]
> All caches on the chosen map area should be stored and previously stored ones should be updated to the current state.

Pay attention: This may lead to possibly unwanted effects with the offline stored Personal Notes, as there are still some issues with duplication and even overwriting or deletion of PNs stored in c:geo, so I would really appreciate if #5854 would be solved prior to bulk updating offline saved caches.  At least the comparison of server's and c:geo's PN should be cut and dried ...

**Comment by Oskar1983** [comment]
Indeed, a warning about personal notes that differ in c:geo and geocaching.com would be very helpful in this context. On the other hand in my opinion it is even more annoying to update an area via live map and if you are on site, you recognize an outdated version of the cache.

**Comment by MagpieFourtyTwo** [comment]
It's not really about a warning, but about keeping both versions - if they differ.  Unfortunately c:geo constantly fails while "comparing" the offline stored PN (mostly to itself) and assumes differences where in fact are none at all.  Then the note gets duplicated frequently.  Or there will be a previous version added (separated by a "--" line).

Which is at least annoying (as you never know which one is the correct one), and in worst case really bad, as you possibly lose the work you've done while the last few edits.  Or - in some very rare cases (esp. when updating a cache which has had no PN on the server yet) - you may even lose the entire note.  Or - if the server's note already contained a "--" line, your possibly more up-to-date offline note in c:geo will be overwritten by the old server's one.

Just have a look at the mentioned issue and you will get an impression of the problem (and a possible workaround).

Nevertheless, even this workaround does only work with a lot of discipline (upload offline changed PNs as soon as possible and esp. before any refresh), thus implicit updates are not a good idea as long as this problem is not solved.

**Comment by hsbofb** [comment]
I agree with you regarding the personal notes.

If no satisfying solution can be found, the "store all" should be removed as long as there is no solution, since it is misleading now.

**Comment by MagpieFourtyTwo** [comment]
Really ...?  It says "*Store* all" - and that's what they are, afterwards ... stored.  ;)

No, totally agreed.  And to make things even worse:  If on "Store all" you select a different list than the one(s), the already stored one(s) are already in, they don't even get linked to this (for them new) list.  Seems as if "Store all" just skips the already stored ones completely.

**Comment by Oskar1983** [comment]
Yeah, unfortunately this is quite a mess atm...

**Comment by Lineflyer** [comment]
Lets try to sort this out and separate it from other problems already known and documented.

1. If you select to store all caches on map and select a target list all visible caches should for sure be part of this list afterwards. -> Bug 

2. As said before by someone, caches already stored will not be refreshed as they are already stored. This would then be more a feature request to have an option to refresh all stored on map. -> Feature request

Shall we split it up that way? Would solving those two points solve the initial issues...I think so?!

**Comment by Oskar1983** [comment]
Yeah, that are two points. Regarding the second one: I'm pretty sure some time ago those stored ones where updated. So I'm not sure anymore if it is a bug oder a feature request.

**Comment by moving-bits** [comment]
I started debugging into it and get confused the more the deeper I dug into it...

First of all, there is a difference between `CGeoMap` and `NewMap` when selecting the "Store all" menu entry:
- `CGeoMap` says `Geocache.storeCache(null, geocode, listIds, false, handler);` in its `LoadDetails` class, whereas
- `NewMap` has the additional condition of `if (!DataStore.isOffline(geocode, null)) { ... }` around it - which to my understanding prevents that a "store all" has ever worked for OSM NewMap, but just loaded the unstored caches.

Then, a bit deeper into the `storeCache()` method, it does a `searchByGeocode()` call with parameter `forceReload` set to false, leading to the cache saved in database being returned (if existing).

I'm really confused, but I may have missed relevant bits.

@Lineflyer Do you know when "Store all" has worked the last time (if ever)?

**Comment by Oskar1983** [comment]
Is there any news on this? So maybe it really only worked with the old map. But then it would be helpful to reactivate it - maybe with a confirmation message, that local notes might be overwritten for previously stored caches.

**Comment by moving-bits** [comment]
@fm-sys 
Looks like this issue is obsolete since implementation of the new background downloader for cache with it explicitly asking what to do with already existing caches. Can we close here?

**Comment by fm-sys** [comment]
Yes, should be solved...
