### ISSUE TITLE
Adaptive icon

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#8558]
Follow up on:
https://github.com/cgeo/WhereYouGo/pull/190#issuecomment-650730442

I tried to also come up with an adaptive icon for c:geo. The current icon is not really suitable for the new specification with an opaque background and different shapes. 

First I tried it with a solid blue background as for the WhereYouGo icon (white background was too boring):

![cgeo-launcher-map-blue](https://user-images.githubusercontent.com/5598124/85952251-311ddf00-b968-11ea-9b6a-2efe90036df4.png)

![20200628_180109](https://user-images.githubusercontent.com/5598124/85952455-b786f080-b969-11ea-9590-e99069c57638.gif)

Then I tried something different and removed the shape of the background map and scaled it to fill the full icon background and a bigger box as the foreground:

![cgeo-launcher-map-orange](https://user-images.githubusercontent.com/5598124/85952280-4bf05380-b968-11ea-9283-a016e231a344.png)

![20200628_175945](https://user-images.githubusercontent.com/5598124/85952411-62e37580-b969-11ea-8fa0-8f6ee61a33d9.gif)

What do you think?

*The GIFs are a bit grainy. On the real device it looks clean.

**Comment by Lineflyer** [comment]
Some time ago we had a proposal. It looked similar and I also like this one.

IMHO much better as the current legacy icon GooglePlay enforces on new Android versions.

**Comment by pstorch** [comment]
@Lineflyer ok, then I'll send a PR

**Comment by Lineflyer** [comment]
This also fixes #7631

**Comment by moving-bits** [comment]
Thumbs up! I do like the new look.

**Comment by bekuno** [comment]
> Some time ago we had a proposal. It looked similar and I also like this one.

It was PR #8076

**Comment by moving-bits** [comment]
I prefer this one over #8076 as this one keeps the box's shadow and does not try to keep the 3D map effect (which does not work well without the map's borders).

**Comment by SammysHP** [comment]
I think the version with the map filling the background should work. We'll done! 👍

**Comment by Lineflyer** [comment]
@pstorch Sorry to bother you on this: May you find the time to do the same perfect graphic artistic with the logo of our contacts plugin?
