### ISSUE TITLE
NPE in RouteLayer.draw()

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8568]
**Description:**

NullPointerException in `RouteLayer.draw()` as in:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
 	at cgeo.geocaching.maps.mapsforge.v6.layers.RouteLayer.draw(RouteLayer.java:70)
	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
```

Happened several times during today's tour as well as infrequently during development.

**To Reproduce:**

Not yet tested if it's reproducible, but today it happened several times when doing the following steps:
- starting point was OSM offline map with the caches of today's tour combined as a individual route
- move a visited cache from list A to list B
- long tap on cache to remove it from individual route
- in about 25% of the time the map then crashed / c:geo main screen shown; - after restarting the map the cache removed from individual route *is* removed
- in the other cases cache is removed from individual route without the map crashing

**Version of c:geo used:**
2020.06.14

**Is the problem reproducible:**
Not yet sure, but happened 5 times today (according to log) out of 20.

**Comment by MagpieFourtyTwo** [comment]
I guess, you used the cache popup to move the caches to a new/different list?
Cause apart from that I was not able to remove the moved cache from the individual route,
as there simply is nothing left anymore to long click on it:

- open a list of caches
- display entire list on map (using map symbol in the list's header)
- connect the caches via individual route
- go back to list of caches
- move a cache to another list
- display the listed caches on map again 
- route is unchanged, even the moved cache will be touched by the route,
  but there is no symbol anymore to remove the via ...

Nevertheless, no crash.  Or do you use a different approach?

I tried it via popup, too, with about 10 caches, but even if doing it this way was not able to reproduce your crash.

**Comment by MagpieFourtyTwo** [comment]
Version used: 2020.07.02

**Comment by moving-bits** [comment]
I've been on live map (with deactivated "live"), and had formed the caches to an individual route.
After each logged cache I moved the cache via cache popup to my "visited" list, removing it from the current list, and removed it from my individual route as well to get the remaining distance updated. This could be either in this order or the other way around. Mostly it worked, but in about 1/4 of the cases it lead to the crash.

Apart from that I'd this error sometimes during development, but too infrequently to gather useful information from it.

**Comment by MagpieFourtyTwo** [comment]
Ah, so you removed the caches from the beginning of the route ... during my tests I unconsciously picked them from somewhere in the middle, as I realize now ... perhaps that is the nub of the matter ...?

**Comment by moving-bits** [comment]
Closing this issue, since internal representation of routes have changed widely after release of 2020.07.x and 2020.08.04 versions. Will reopen a fresh issue, if this error occurs again.
