### ISSUE TITLE
Use new app icon also in top bar on main menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8571]
Just a question:
Seeing this nice new app icon...shouldn't we also use it (in appropriate size) on top left of our top bar in main menu?

**Comment by moving-bits** [comment]
That would look like this:

![grafik](https://user-images.githubusercontent.com/3754370/86469794-706a7800-bd3a-11ea-9613-1266de635bdf.png)

Nice side effect is the additional spacing between logo and "c:geo" title.

**Comment by bekuno** [comment]
It`s nice but I would like to see  more square variant (eg. rounded square) and a shorter height.

**Comment by moving-bits** [comment]
My hope was, that the form was somehow dependent on the system setting for the icons, but that does not seem to be the case, at least not in the tested emulator Android 9 version. But with some tricks I managed to get a squircle version into the application bar:

![grafik](https://user-images.githubusercontent.com/3754370/86509611-8a16c880-bde9-11ea-9a03-a03fae949ca4.png)

I'm undecided though, which one I prefer. The squircle version looks more familiar, the larger round version more modern, IMHO.

**Comment by Lomanic** [comment]
Personally I prefer the last proposition (smaller square with round corners).

**Comment by SammysHP** [comment]
Yes, the squircle version. This also matches the other icons. Maybe bigger padding to "c:geo".
