### ISSUE TITLE
database restore fails on Android 6 (for current dev version)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8587]
**Describe the bug:**
Tried to restore a c:geo database on an Android 6 system with current dev. version. c:geo stops without any recognizable error message.

After some debugging an error message appears in the log:

```
Caused by: java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
        at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1303)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:797)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:747)
        at cgeo.geocaching.utils.FileUtils.copy(FileUtils.java:205)
```

Downgrading to apache.commons.io Version 2.5 helps. Have not tested 2.6 yet. 
Could not find any dependencies to Android SDK mentioned on apache commons website at a quick glance, needs to be investigated further.

@bekuno, can you have a look at this?

**To Reproduce:**
- Use a device running Android 6 (in my case: a physical device running Android 6.0.1)
- Make a database backup with a release version of c:geo (in my case: 2020.03.30)
- Install current dev version, accept requested rights, and try to restore the database backup

**Version of c:geo used:**
- DB backup created with 2020.03.30 release version
- Trying to restore backup with current master branch dev version

**Is the problem reproducible:**
Yes

**Comment by bekuno** [comment]
Is this problem also on Android 7? (Could not test until now)

**Comment by bekuno** [comment]
From commons-io 2.6 the `java.nio.file.Path` is used. But this is first contained in Api26 (Android 8.0).
Therefore I revert the change.

If we are using the Storage Access Framework in c:geo then we should also replace the calls of `org.apache.commons.io.FileUtils`.

**Comment by moving-bits** [comment]
@bekuno 
Ok, thanks for checking and for preparing the downgrade.
