### ISSUE TITLE
Wrongly parsed coords from user note

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8589]
From support mail for version 2020.07.02

Using this in your personal note results in three waypoints being automatically created:
```
Answer questions
6, 12, 16, 29, 54, 3, 36, 5, 3, 47, 45, 43
```

---

I informed the user that he can turn this feature of for this particular cache, however we should analyze if this can be optimized without any disadvantages while parsing.

**Comment by moving-bits** [comment]
I fear this type of problems will persist as long as we do not add hints regarding the coordinate format (or restrict it to a certain format). Parsing all supported types of coordinate formats without any additional hints will always have some side effects and edge cases.

**Comment by UniQP** [comment]
In the example, we parse `6, 12` and `16, 29` as floating-point numbers and both together as a coordinate.
This would not happen, if we introduce one of the following restrictions:
- Floating-point numbers should not contain spaces (parses `6,12` but not `6, 12`)
- Only whitespace characters are allowed between the floating-point numbers (parses `6,12 16,29` but not `6,12 and 16,29`)

IIRC there are examples in the tests where we don't want the restrictions. So there is no right answer.

**Comment by MagpieFourtyTwo** [comment]
I think we all agree that it is simply impossible to always find *all* coordinates in *all* possible notations (and it's variants, i. e. with or without degree symbols, zeros and whitespaces) *without* any false positives. Whereas I still don't get, why c:geo wants (resp. should be able) to scan for *all* notations, anyway ... most of the users use exactly *one* format and that's it. Then, why should c:geo look for stuff, this very special user will never ever use (or know) anyway? And if he does not know all these formats, he will for sure not write it in his notes ...

So, why not simply limit the search to an at least kind of manageable subset, i. e. to the format, this user most probably will use in his personal(!) notes, thus the one, which is configured in his waypoint display format ...?

**Comment by Lineflyer** [comment]
I dont think we should enforce any format restrictions. In a high percentage of cases I guess the parsing functions well.

This issue is only about evaluating a possible optimization as suggested by @UniQP 
We should IMHO limit the existing parsing.

**Comment by MagpieFourtyTwo** [comment]
Au contraire - the parsing fails *very* often.  And this over here is by way not the first issue dealing with this topic.
The more you use PNs to e. g. solve mysteries or keep track of you multi stations, the more false PN waypoints are produced.
That was in fact the reason why #8078 came up - and resulted in the option to prevent automatic waypoint extraction.
And, BTW, both examples given in #8078 still result in the same wrong coordinates - just give it a try:

```
10, 20, 100, 200, ja 300 Häuser = QS=9
```

Gives "N10 12.000 E100 12.000" - but ... why?

```
12-a-c=7	=> a+c=5	=> a=2 / c=3
36-b-d=26	=> b+d=10	=> b=2 / d=8

a.b.c.d@gmx.de
2.2.3.8@gmx.de (don't try, doesn't exist anyway ;) )

Final (doesn't exist, neither):
N48 51.234 E9 01.234
```

Results a. o. in "N02 12.000 E3 48.000" - any guess about a matching coordinate notation ...?

Consent was, that it is simply impossible to make the complex parsing foolproof - so why not help `parseAll()` and limit the set of "allowed" resp. possible waypoint notations to the ones, the user really knows and uses?  Cause others then the ones *he* knows, he will for sure not use in his own, handwritten notes (consciously)?
