### ISSUE TITLE
Export Own Waypoints/Stages and their notes as Personal Note

### ISSUE THREAD

**Issue by S-Man42** [cgeo/cgeo#8609]
Use case:

On a multi cache I always use the waypoint lists. I add new waypoints or edit the coordinates or notes of given stages. 

However, when I remove the geocaches from my device, clean up or change my device, all this information get lost. It would be great to store them on GC.com in the Personal Notes section. 

The idea is to export all waypoints and their additional information as list/text, maybe:

```
Waypoint name 1
N 52 12.123 E 009 11.123
Note: A = 11, under stairs

Waypoint name 2
...
```

This simple text can be easily added to the PN field and, therefore, uploaded to GC.com before cleaning up the device.

Currently I do this manually: Copying the coords and texts from the waypoints into the PN section and upload. But this seems to be a very simple function with huge impact. Saving all multi stage information with one click.

**Comment by Lineflyer** [comment]
Duplicste of #5688
