### ISSUE TITLE
Ease onboarding with offline maps, part 2

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8610]
This is part two to ease onboarding with offline maps for new users of c:geo, in addition (or as partial replacement) of #8180/#8183:

- add a link to the map selector: "Download offline maps"
- which opens a directory listing of the Mapsforge server (actually its mirror at fh-esslingen.de)
- You can browse through the directories up and down and select a file (map) to download.
- Map file gets downloaded in the background using Android's download manager.
- On completion the map file gets copied into c:geo map directory and activated as current map. (as in #8183).

This is how it looks like:

New menu entry "Download offline map" in map selection menu:
![image](https://user-images.githubusercontent.com/3754370/87226999-05531e00-c398-11ea-9d42-85145273d8b3.png)
(the thin separator line is available on Android 10+ only)

Retrieved the initial listing of the v5 map directory:
![image](https://user-images.githubusercontent.com/3754370/87227020-26b40a00-c398-11ea-9ec2-e234ba27754c.png)

Retrieving a sub directory, "Australia-Oceania" in this case:
![image](https://user-images.githubusercontent.com/3754370/87227029-39c6da00-c398-11ea-829b-9ca4bfc50327.png)

For downloadable map files size and date of last change are shown:
![image](https://user-images.githubusercontent.com/3754370/87227043-4cd9aa00-c398-11ea-86d0-2c00b121423f.png)

When you select a map for downloading, you get a short notification that the download starts in the background. You can continue to work with c:geo until the download has finished:
![image](https://user-images.githubusercontent.com/3754370/87227066-6c70d280-c398-11ea-9ad5-68d65904680c.png)

When the download has finished the file gets copied to c:geo map dir automatically:
![image](https://user-images.githubusercontent.com/3754370/87227074-83afc000-c398-11ea-8080-44cea75b8ea3.png)

Finally you get a confirmation that the download has succeeded:
![image](https://user-images.githubusercontent.com/3754370/87227079-96c29000-c398-11ea-9017-c679019f186c.png)
The newly downloaded map gets activated as current map automatically.

---

Current state of this PR is beta. Next steps are:
- creating and merging the "extension table" PR, which is a prerequisite
- a bit of minor roundup on this, then creating "map download" PR
- testing, testing, testing, ...

Any feedback is very welcome.

**Comment by fm-sys** [comment]
Wouldn't it make more sense to move the downloaded map to the map directory instead of copying it?

This would be faster and save memory space...
