### ISSUE TITLE
Cgeo will be used for telefonenumbers

### ISSUE THREAD

**Issue by MasterPlexus** [cgeo/cgeo#8618]
See the attached Screenshot. It looks like cgeo was now also set as an telefone service? 

Using Pixel 4XL Android 10
Cgeo self compiled 11.06.2020 22:00

![IMG_20200712_184215](https://user-images.githubusercontent.com/942153/87251985-ff307080-c46f-11ea-9e2e-54a03535f973.jpg)

**Comment by Lineflyer** [comment]
Link to #8467, @moving-bits  See what I mean...its nearly everywhere.

@MasterPlexus You seem to be using our nightlies. We will remove that implementation next days in new nightlies. It did not work as expected.

**Comment by MasterPlexus** [comment]
Ah, right. So I'll close this here, as there is no need to follow it several times.
