### ISSUE TITLE
Filtering attributes for opencaching.de caches does not work

### ISSUE THREAD

**Issue by dhebbeker** [cgeo/cgeo#8620]
**Describe the bug:**
Filtering for caches stored from opencaching.de does not give the expected results in stored caches list.

**To Reproduce:**
1. Go to a list of stored geocaches where a cache with OC-only attribute exists
2. Filter by attribute "Only loggable at Opencaching"

**Actual behavior/state after performing these steps:**
No cache is listed. I know to have at least one cache with OC only in that list (for example [OC11EB4](https://opencaching.de/OC11EB4)).

**Expected behavior/state after performing these steps:**
At least that known cache should be listed in the list after applying the filter.

**Version of c:geo used:**
2020.07.02

**Is the problem reproducible:**
Yes

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
[system-information-G8441.txt](https://github.com/cgeo/cgeo/files/4909265/system-information-G8441.txt)

**Additional context:**
I understand that [attribute filtering can only be applied to offline caches](https://manual.cgeo.org/en/mainmenu/lists#filtering). I used a list of stored caches in this issue.

Also I have tried other attributes as well in the same manner ("Ticks", "Hilly area") with the same result.

**Comment by bekuno** [comment]
Could reproduce.
Our filter searches for "oc_only_yes", but we have "oc_only".

**Comment by bekuno** [comment]
The implementation for OC attributes (and probaly all not GC attributes) does not work in the current implementation.
This needs a bigger rework.

**Comment by eddiemuc** [comment]
PR #10646 fixes this for new filters
