### ISSUE TITLE
History list: Avoid deleting instead of clearing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8622]
A user on support mail accidentally used Menu - Manage Caches - Delete all to clear the history, which did what it is itended to do: Delete the caches rather than only the history list content. 
He has just missed to find the menu item "Clear history" in the same menu.

As "Clear history" is only shown on the history list I suggest to put it into the top level instead of under "Manage caches" to separate it from actions, which potentially modify the caches as such.

**Comment by Narrat** [comment]
Didn't try this menu entry and therefore I do not know if such a thing is already in place. But what about a confirmation dialogue with explicit message if someone attempts such a mass change?
