### ISSUE TITLE
gpx files containing routes, rather than tracks

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8627]
> Would it also work with gpx files containing routes, rather than tracks.
> I know the format is different, don't know how.

Should be technically possible, but if I understand [this Wikipedia article](https://en.wikipedia.org/wiki/GPS_Exchange_Format) right, there would be an additional step of calculating a route from each route point to the next.

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/2469#issuecomment-633276367_

So maybe use Brouter (if installed) to calculate the routes from point to point... Would be great if gpx routes could be implemented!

**Comment by moving-bits** [comment]
@fm-sys 
Can you provide me with some sample files containing GPX routes? Preferably with different combinations of the allowed attributes / generated by different tools. Thanks.

**Comment by fm-sys** [comment]
I've created 2 example files using two different online tools and than I found some more files on github. All files you find listed in this [repository...](https://github.com/fm-sys/sample-gpx)

**Comment by moving-bits** [comment]
Thanks for providing the files. Will put routes into my personal backlog...

**Comment by moving-bits** [comment]
Let's discuss some possible implementation alternatives:

- Do we need to distinguish between track and route in terms of UI? (eg.: separate menu entries for loading/unloading, map line colors, ...)
- If not: in what order should gpx files be analyzed - track first, then route?

**Comment by fm-sys** [comment]
> Do we need to distinguish between track and route in terms of UI?

I would say no. Let's keep the UI as simple as possible...

> If not: in what order should gpx files be analyzed - track first, then route?

Yes, that would be ok. Otherwise if a file contains multiple tracks/routes a selection list like the "hide items" on livemap whould be cool to select which of the tracks/routes should be shown. But i think this szenario is quite rare...

**Comment by fm-sys** [comment]
During my search for suitable example files I also noticed tracks that are not routes but still have a very large distance between the individual points. Therefore a threshold would probably be useful, so that these tracks are treated like routes
