### ISSUE TITLE
Voice navigation with Brouter

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8630]
Brouter is a very useful tool to calculate bicycle routes in c:geo.  But as a cyclist you can't constantly look at your mobile phone so voice announcements would be very useful.

Of course there are other apps for this purpose, but they either have no offline support or use a lot of memory, because they need their own offline map data.
In addition, geocaching would require you to switch between the apps all the time. Therefore, a function like the one in the compass would be very useful for offline navigation. 

However, it will probably be difficult to implement such a function. But here are two approaches:
- Does Brouter itself offer the data in its interface where intersections are located and how to turn there?
- Or is it possible to search in the Mapsforge offline map for crossings and turns (turn left, turn sharp right, follow the road for x km...)

**Comment by Lineflyer** [comment]
I dont think we should go for such features.
c:geo is a geocaching app. We should leave the turn-by-turn navigation to other apps specialized on that.

**Comment by MagpieFourtyTwo** [comment]
> there are other apps for this purpose, but they either have no offline support or use a lot of memory, because they need their own offline map data.

[LocusMAP](https://www.locusmap.eu) uses the same offline maps as c:geo (resp. vice versa, to be honest ;) )

> In addition, geocaching would require you to switch between the apps all the time

[LocusMAP ... for real paperless hunt](https://www.locusmap.eu/geocaching) - haven't tested it yet, but the promises on website sound really good.  Will for sure give it a try.

For bike tours I am using my Garmin Oregon 750t so far, but even with "Geocaching Live" it's a little bit fiddly. And doing Multis is a real pain on the Oregon, Last but not least planning tours with Basecamp has always been really annoying, and it add. needs the Windows detour, thus not really possible "on the fly".

But after reading the links above, I could imagine a new workflow: use c:geo to look for caches (on the map etc.), put them in a list, finally export the list to GPX and import it to Locus ... sounds pretty comfortable and is straight forward, as all this can easily be done underway on the smartphone ...

Maybe this can be a solution for your (comfort) problem ...?  ;)

**Comment by moving-bits** [comment]
IIRC you can even combine the two: Select a cache in c:geo and open Locus as navigation target.

**Comment by fm-sys** [comment]
@MagpieFourtyTwo 

Thank you very much! Hadn't tested Locus before... 

Even though it would still be cool to have navigations directly in c:geo, I realize that even if we would try an implementation, the results will never be as good as with other apps.

Since I like the map Theming of c:geo very much, it is great that I can use the same map in Locus as well.

For searching geocaches i will still use c:geo, but since locus is well integrated it's perfect for the navigation part!

**Comment by fm-sys** [comment]
Even though there was a lot of opposition to this topic a few months ago, I would like to bring it up again. c:geo has gained significantly more routing functionality in the last few months and I found out that BRouter even comes with the possibility to generate turn instructions.

I will play around with it a bit, and if it works well I'd love to implement the function in c:geo :-)

**Comment by fm-sys** [comment]
@moving-bits just a short note: I don't know how much you plan to rebuild BRouter during the integration process, but please do not remove the classes `VoiceHintProcessor.java`, `VoiceHint.java`, etc. while implementing BRouter into c:geo, as I plan to integrate "BRouter voice navigation" for c:geo's live map in the near future (already started)...

I also took the liberty of adding this feature request to the new BRouter project board.

**Comment by moving-bits** [comment]
@fm-sys 
Don't worry, I'd seen your message from a week ago, and made a mental note to not remove the turn-by-turn-navigation & voice hint related classes. Also I'm using a folder structure which resembles the original folder structure, and I'm currently not renaming any classes or methods (except when Codacy / CheckStyle force me to do so), so even if I should accidentally remove a class, it should be relatively easy to re-add it.

**Comment by moving-bits** [comment]
@fm-sys 
Basic BRouter integration is now integrated into c:geo, so feel free to start playing around with the voice functions ;-)
If you want to restrict this function to the embedded routing engine for whatever reason, you can do the distinction with `Settings.useInternalRouting()`

**Comment by fm-sys** [comment]
No priority for me anymore... Thus let's close this feature request which was solely requested by myself
