### ISSUE TITLE
[Nightly] Fast scroll crashes in long lists

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8633]
**Describe the bug:**
I have a list "All finds" which contains about 6k caches. If I use fast scroll to go to it's bottom, c:geo sometimes crashes as soon as I swipe over the end of the cache list, i. e. when I cross the border between c:geo's cache list and Android's (resp. Nova Launcher's) menu bar. This happens in another list, too, which has just about 1,1k caches - but not that frequently. Nevertheless, if you "go wild" (i. e. swipe up and down rapidly across this border a few times), the crash happens there (and in even way shorter lists), too.

**To Reproduce:**
1. open a list containing at least 1000 caches (maybe the farthest away should additionally have a distance of more than 1000 km)
2. sort list by distance
3. fling up to activate fast scroll
4. grab fast scroll bar and swipe down to the very end of the list and go all the way down to the end of the display
5. if c:geo does not crash immediately, keep finger tapped and rapidly move up and down a few times

**Actual behavior/state after performing these steps:**
c:geo crashes and restarts with main page.

**Expected behavior/state after performing these steps:**
Guess what ...  ;)

**Version of c:geo used:**
2020.07.14-NB-f2e3a34

**Is the problem reproducible:**
Yes

**Additional context**
Please find a logfile, generated with this really great new function, enclosed.  :)
[logcat_2020-07-14_12-46.log.txt](https://github.com/cgeo/cgeo/files/4918520/logcat_2020-07-14_12-46.log.txt)

BTW: Github refused to upload my ".log" files - thus c:geo should possibly rename it to ".txt" to make it easier for Joe Public?

**Comment by moving-bits** [comment]
Interesting: Android queries the section info for an entry it knows (should know) it doesn't have... Will add a manual range check.

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 
I cannot reproduce this error on my emulated API 29 device. Maybe it's version- or device-specific.
I tried to find a mitigation (manual bounds check) - please crosscheck if this works for you.

**Comment by MagpieFourtyTwo** [comment]
Tested - works. At least in in the above mentioned scenarios.  ;)
Great - thx!
