### ISSUE TITLE
Logfile confirmation dialog should use "Ok" button instead of "Cancel"

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8636]
Currently the confirmation dialog after writing a logcat logfile reads "Logfile written - Cancel - Send E-Mail".

![image](https://user-images.githubusercontent.com/3754370/87463350-8bc66480-c611-11ea-922a-c74dc1f29331.png)

IMHO "Send E-Mail - Ok" would be more plausible.

**Comment by Lineflyer** [comment]
Yep, stumbled upon that as well when first using it.
