### ISSUE TITLE
[Nightly] History line draws senseless connection

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8648]
**Describe the bug:**
When you open the map and history line recording *continues(!)* to log your track, a senseless line will be drawn (and stay fixed) from the position you have been in the moment you opened the map to the very first point of your entire history line.  After that, recording goes on as expected, but when you leave the map for a short time and re-enter it, there will again be such a line from your current position (which of course should have changed in the meantime, at least for this test ;) ) to the very start of your history line, while the previously displayed "current to start connection" is gone.

**To Reproduce:**
1. open map view (which one does not matter, checked against GM, GM Sat View and OSM v5)
2. activate "Show history line"
3. for a better experience you may want to delete current history line
4. MOVE!  ;)  (but not just in a straight line, you may take at least one corner)
5. watch your history line growing ...  :)
6. leave map
7. re-enter map ...
8. a line will be drawn from current to first position
9. MOVE!  ;)  (but again not just in a straight line)
10. leave map
11. re-enter map ...
12. a new(!) line will be drawn from your new current to first position, while the one drawn at step 8. will not be there anymore

**Expected behavior/state after performing these steps:**
There should not be any direct connection from my current position to the first point of my history line.

**Version of c:geo used:**
2020.07.17-NB-7278598

**Is the problem reproducible:**
Yes

**Comment by MagpieFourtyTwo** [comment]
Just updated to 1b61537 - same same.

**Comment by MagpieFourtyTwo** [comment]
Noticed this afternoon: To "create" a new "connection" (like in step 10 to 12). it's even sufficient to just switch the phone's display off and on again.

**Comment by Lineflyer** [comment]
This is the limitation we have had ever since. If the map or your GPS is off it wont record the track.
Once its active again it continues drawing from present position.

Maybe we could find a way to stop drawing these connections.

**Comment by moving-bits** [comment]
This has been there ever... since storing the history track to the database:
- Adding a new location to the track was done at the end,
- but at reloading the track got returned in reverse order.

This explains the superflous connection line (as the first added point after reloading was the current location, which was also the last point saved, thus now being at the beginning end at the end of the restored track), 

and also explaines the weird behavior after deleting some parts at the beginning of a restored track (which after reloading was the end of the track stored so far), as described in #8631. So #8642 fixed what lead to cutting out a part of the track, but the root cause for the weird thing, that newer part of the track got cut off, wheras older parts remained, was the same error responsible for this issue.

See PR #8649

**Comment by MagpieFourtyTwo** [comment]
Works - thanks!

But now I have the effect that the position marker constantly looses the connection to the track ... i. e. the position marker moves forward, but leaves a gap between current position and the most recently recorded (and poss. stored) point ...
This may be considered as a minor issue, but in fact it looks as if recording is interrupted.
Would IMHO be better, to always additionally draw the line from the current position to the latest recorded one.
Is this understandable?
And can it be done easily or should we open a new issue for this?

Moreover, from time to time the history line will not be drawn in live map at all ... in such a case I have to at least change map context, sometimes even restart c:geo completely (sometimes even with removing from memory).
Most regretfully I was not able to reproduce neither failure nor the way to get it back ... really strange.
If I get a grip on it I will file a new issue ... but like it is right now ... do you have an idea?

**Comment by moving-bits** [comment]
> But now I have the effect that the position marker constantly looses the connection to the track ... i. e. the position marker moves forward, but leaves a gap between current position and the most recently recorded (and poss. stored) point ...

Ah, I probably deleted too much from the old code. I create a PR "to close the gap".

> Moreover, from time to time the history line will not be drawn in live map at all ... in such a case I have to at least change map context, sometimes even restart c:geo completely (sometimes even with removing from memory).
> Most regretfully I was not able to reproduce neither failure nor the way to get it back ... really strange.
> If I get a grip on it I will file a new issue ... but like it is right now ... do you have an idea?

Cannot reproduce it here. Feel free to open a separate issue if you find a way to reproduce it.
Is there anything in the log files?
