### ISSUE TITLE
App has stopped working

### ISSUE THREAD

**Issue by GeoGhostHunter** [cgeo/cgeo#8650]
The App has stopped working.
when I run the app and then pick Live Map. It dose not display any caches, only found ones and they are marked with a circle with question marks inside. It will not display any type of cache.
It will show my location.
When I click on Nearby it says no caches here.
When I go to search and enter in cords it says nothing here.
It also says I am not logged in and GC login fail. buy yet it shows I am not in Off line mode.
I also can not find the login so I can not verify I'm logged in.
I have gone to the reconfigure services and Geocaching.com is selected and it says "Active".
GCvote.com selected. 

I don't know what else to do or look for.
Thanks

**Comment by Lineflyer** [comment]
That sounds as if you use a really very old version of c:geo. Please update first.

**Comment by moving-bits** [comment]
To see which version you are using currently go to c:geo's main screen, three dot menu, "About c:geo".

**Comment by bekuno** [comment]
For this message see the FAQ point https://www.cgeo.org/faq#login-failed

**Comment by bekuno** [comment]
> I have gone to the reconfigure services and Geocaching.com is selected and it says "Active".

Please hit this point and then (re)authorize.

**Comment by moving-bits** [comment]
@GeoGhostHunter 
Any news on this from your side?

**Comment by moving-bits** [comment]
Closing due to lack of feedback.

Feel free to reopen and provide new info if problem persists.
