### ISSUE TITLE
Add "old version" warning

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8651]
From time to time we get reports which seem to be related to very old versions of c:geo, like feedback on Play Store or (maybe) #8650. I would like to avoid (or at least reduce) this in the future, therefore

I propose to add a warning message showing up when you c:geo version is more than one year old (to be detected by comparing our version string against system date). This could be shown in the same screen area where we show our "Android too old" warning.

Message could be "You are using a version of c:geo which seems to be older than one year. Please try to upgrade.", linked to either play store or a special entry on our faq page. The latter would be more universal as we can explain upgrading for more ways than just play store, on the other hand the address may be volatile throughout the years.

**Comment by bekuno** [comment]
I would additional add a version check. If no newer release exist than the message is senseless.

**Comment by moving-bits** [comment]
I would like this message to be able to work offline. Also, for a full version check you would need to take Android version into account etc. And even if there is no new version available for your specific device you should get to know that your version is pretty old, possibly making some things fail.

Version check should check for "more than one year", eg.
- version string is `2018xxxx` and system year is `2020` => display a message
- version string is `2019xxxx` and system year is `2020` => do not display a message

**Comment by bekuno** [comment]
The text needs carfully defined to cover 'legacy' devices.
Can we request somehow which c:geo release supports a specific android version?

**Comment by moving-bits** [comment]
> The text needs carfully defined to cover 'legacy' devices.

Currently I have this one, which should cover `legacy` devices as well:

![image](https://user-images.githubusercontent.com/3754370/87850114-ea2f6380-c8ed-11ea-867d-2351f4e1deee.png)
(Text is linked to c:geo FAQ)

> Can we request somehow which c:geo release supports a specific android version?

Not that I know of.

**Comment by Lineflyer** [comment]
Why should we need that?
Only for offline cases? We do already have a version check and message system.

**Comment by moving-bits** [comment]
> Why should we need that?
> Only for offline cases?

- Offline use cases
- Add some "sense of urgency" by explaining what may happen

> We do already have a version check and message system which works pretty well.

it's integrated into that message system as extra default message (like the "Android 4 closeout message" was)

**Comment by Lineflyer** [comment]
mmh...This probably means it will be overwritten by the status system as a new version will most likely be available in "online case" and only be shown in "offline case". Thats how I would prefer it, as the trigger to update is more accurate, than just saying "Your version does not work".

**Comment by moving-bits** [comment]
That's the way it's implemented.

If an online message is available, take it.
If none is available (yet), check for deprecated version, then for Android system version.

**Comment by Lineflyer** [comment]
> If an online message is available, take it.
> If none is available (yet), check for deprecated version, then for Android system version.

Thumbs up!
