### ISSUE TITLE
Replace logo in About section?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8661]
Shall we also replace the logo in "About c:geo" with the new one?
While I also like the "old" it would only be consistent to also use the new one here.

**Comment by bekuno** [comment]
+1

**Comment by moving-bits** [comment]
Easiest way would be to replace `android:src="@drawable/cgeo_logo" />` in `about_version_page.xml` with a different but existing logo. If we choose the new `@mipmap/ic_launcher` result depends on the system version and configuration.

New logo gets shown on API 26+ only, and it's shape depends on the system settings:

![image](https://user-images.githubusercontent.com/3754370/87979187-f6741600-cad1-11ea-9518-8f00aa61c49b.png)![image](https://user-images.githubusercontent.com/3754370/87979213-fd9b2400-cad1-11ea-8157-f153df55e07f.png)
Images are very crisp, as they are drawn from a vector resource.

On older systems you get the predefined png:
![image](https://user-images.githubusercontent.com/3754370/87979295-1efc1000-cad2-11ea-98e7-ee0baef65e41.png)
Image gets scaled, may be blurry. But only here the "debug" badge gets added.

**Comment by fm-sys** [comment]
Or we could use the design of our website... 

![Screenshot_20200725_084351](https://user-images.githubusercontent.com/64581222/88450939-1ea5a100-ce53-11ea-965c-c3ed7f9a1402.jpg)

**Comment by Lineflyer** [comment]
I think the proposal of @fm-sys looks even better. Any more opinions?

**Comment by Lineflyer** [comment]
@fm-sys Feel free to provide a PR for this.
This would then be the last commit before merging branches.

**Comment by moving-bits** [comment]
I was already working on it. PR follows.
