### ISSUE TITLE
[Nightly] crash with any OSM v5

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8664]
**Describe the bug:**
c:geo crashes in map view with any OSM v5
Guess it's related to latest history line fix ...?

**Version used**
2020.07.21-NB

[logcat_2020-07-21_03-19.txt](https://github.com/cgeo/cgeo/files/4950729/logcat_2020-07-21_03-19.txt)

**Comment by MagpieFourtyTwo** [comment]
FYI: Downgraded to 2020.07.20-NB-33a57ef (which BTW worked like a charm ;) )

**Comment by moving-bits** [comment]
Very strange. I can see the errors in the logfile, but I cannot find a clear cause, code looks inconspicuous. And cannot reproduce in the emulator - map is stable there and works like a charm.

Can you describe the specific steps you did, until that error occurred?
Does it happen directly on map startup, or when moving pretty fast/slow, or anything other "special"?

Besides that: I adapted the algorithm for Mapsforge NewMap to that from Google Maps v2 - let's see if that's better (see #8665).

**Comment by MagpieFourtyTwo** [comment]
Perhaps because of a different constellation of options and/or data?
Over here there's nothing special, piece of cake:

With OSM activated ...
- open c:geo, open live map - crash.
- open cache detail page, show cache on map - crash.
- set map to GM (in options), open live map, switch to OSM - crash.

Maybe deletion of history track may "fix" this, but I did not try yet, cause a) did not want to destroy test data and b) "old" tracks should work with the new strategy, too, otherwise Joe Public must clear history line prior to update, too ... which will for sure lead to massive increase of support inquiries ... would like to protect @Lineflyer as much as possible ... ;)

**Comment by moving-bits** [comment]
I had tested with both a grown history track as well with a freshly cleared one - made no difference. Maybe it's some timing thing, which does not happen in the emulator, because that one's so slow...

**Comment by MagpieFourtyTwo** [comment]
> I adapted the algorithm for Mapsforge NewMap to that from Google Maps v2 - let's see if that's better (see #8665).

Ok so I should re-check the crashes with this night's nightly?

BTW: You have in mind that #8663 happens with GM, too?

**Comment by moving-bits** [comment]
> Ok so I should re-check the crashes with this night's nightly?

yes, please

> BTW: You have in mind that #8663 happens with GM, too?

no, hadn't. but #8663 confuses me anyway :-)

**Comment by MagpieFourtyTwo** [comment]
> no, hadn't. but #8663 confuses me anyway :-)

Then, please let me know what I can do to eliminate (or at least shrink) confusion ... ;)
The scenario itself is clear?  Or is there even need of add. explanation?

**Comment by moving-bits** [comment]
Scenario is clear, but could not reproduce until I had set max. length to minimum allowed value (100).

Meanwhile I've debugged much deeper, and I think I have an idea what's happening. Trail gets truncated on startup only, but reloaded frequently on map restart/resume. So let's imagine you have accumulated A-B-C-D-E, but max length set to three, then on resume it will load A-B-C only (after #8649). So I think I will need to load in reverse order and max. length (giving E-D-C) and reversing that (to receive C-D-E). Will try that.

**Comment by MagpieFourtyTwo** [comment]
Sounds elaborated enough to possibly be correct and perhaps even work. ;)
Good luck!

**Comment by moving-bits** [comment]
Thanks :-)

Added this + a second fix with #8667, which in conjunction try to fix #8663. Will merge to master after successful tests in CI.

**Comment by MagpieFourtyTwo** [comment]
Looking forward ...  ;)

BTW: I'm pretty sure I wrote that the crashes don't happen anymore with 2020.07.22-NB-26fd1cb ... but I can't find it anymore. Strange.

Nevertheless, let's close this issue now ...
