### ISSUE TITLE
Brouter - Routing mode "Car" draws straight line

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8666]
Can someone check if there is a problem with brouter integration in c:geo or my device has some problem:

Whenever I select "Car" as routing mode on cgeo map options it draws a straight line only.
Other routing modes (bike, walk) work normal, which proofs that the navigation tile is available im brouter.

2020.07.19-NB

Sorry for the brevity, only on mobile.

**Comment by moving-bits** [comment]
At least with current master and OSM offline map routing works in all modes for me (tested only this combination; in emulator on API 29 with freshly installed brouter and routing file containing NRW).

Maybe wrong routing information in brouter files? You could try to update them.

**Comment by Lineflyer** [comment]
Already updated.
Will check back at home end of this week.

**Comment by MagpieFourtyTwo** [comment]
WFM, too - is one of your points possibly too far away from a car-allowed point?

**Comment by MagpieFourtyTwo** [comment]
Perhaps you can provide two points which do not work for you, so we can test these ...

**Comment by Lineflyer** [comment]
The issue is not present in my homezone but only during my vacation in NoordHolland.

@MagpieFourtyTwo 
If you still offer to verify:
Take GC55Y23 as target and N52° 53.489 E004° 43.646 as starting point

I currently assume some failure in the corresponding brouter data (which you might need to download before testing this).

**Comment by MagpieFourtyTwo** [comment]
Yep, your starting point is on a classified road ("open voor bewoners"), at least as OSM says. And Brouter does not route in or through roads that are not allowed for public use with the chosen strategy.

Use a starting (or additional via) point at e. g. N 52° 52.944' E 004° 43.572' (best with an individual route) and everything will be fine.

This is BTW the same over here in .de - just look in OSM for blueish crossed roads and try to route to it with strategy car ...

**Comment by Lineflyer** [comment]
> This is BTW the same over here in .de - just look in OSM for blueish crossed roads and try to route to it with strategy car ...

I thought it would just draw a straight line until the next suitable road and route from there (at least I have seen this in the past AFAIR).

**Comment by MagpieFourtyTwo** [comment]
That's right - but therefore the point in the "forbidden" area must be close enough to the next "allowed" point.

In these cases I usually look for the best entrance to the "forbidden" area, set a waypoint there (via long click on map), and then use the new waypoint's popup to let Brouter route me to this point.

**Comment by Lineflyer** [comment]
Indeed, I never noticed before. Thanks for helping to clarify this.

**Comment by MagpieFourtyTwo** [comment]
You're welcome. Glad to be able to support our brilliant support.  ;)

Nevertheless, you're right in a kind of way, as this *was* different some versions ago ... maybe a year ago ... till then it has *always* routed up to the nearest "allowed" point and from there it just draw a straight line.
When this changed, I first was disappointed, too, but in the meantime experience showed that it is better this way, cause the former way resulted in wrong routes very often (as you oftenly ended up at a position, from where you don't get a good route to the final point). Nowadays you will immediately be warned and can set an appropriate via point yourself *in time*.

This change BTW was AFAIR the reason for one of my very first bug reports, as it was (and still is) not possible to enable life map from a waypoint map context ... this I how I learned the advantages of the "create waypoint on map" feature and it's "route to" button in the popup.  ;)
