### ISSUE TITLE
certificate expired on ci.cgeo.org

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8668]
eg.: https://ci.cgeo.org/job/cgeo%20pull%20request/3210/

Browser reports "Warning: Potential Security Risk" and on pressing "advanced" reveals that our certificate is outdated:

`Websites prove their identity via certificates, which are valid for a set time period. The certificate for ci.cgeo.org expired on 7/22/2020.`

**Comment by Lineflyer** [comment]
I informed @mucek4

**Comment by mucek4** [comment]
I have fixed it. Sorry.

**Comment by moving-bits** [comment]
@mucek4 
Thanks for fixing it.
