### ISSUE TITLE
GC: Changed attribute description texts

### ISSUE THREAD

**Issue by steve8x8** [cgeo/cgeo#8673]
**Describe the bug:**
Groundspeak changed the description texts for a couple of cache attributes.
For example, "available during winter" became "available in winter", and "hike shorter than 1km" became "<1 km hike".
This may result in translation issues.

**Comment by SammysHP** [comment]
Why will this result in translation issues? We use our own text.

**Comment by Lineflyer** [comment]
@steve8x8 
As @SammysHP wrote, we use our own texts. I do assume, that the sense of the attributes will not change, only the wording.
Or do you have another reasoning for expecting problems here?

Another question would be, if they also changed the attribute IDs in their GPX.
But I don't think so as it would break compatibility with a lot of devices.

**Comment by steve8x8** [comment]
Attribute IDs have been stable for quite long (which is surprising), also I haven't seen a new one for some time.
Thanks for clarifying c:geo's handling of attributes (based on IDs, not texts).
