### ISSUE TITLE
New UDC created from map should be saved to "User-defined caches" list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8678]
AFAIR new user defined caches should be stored on the dedicatd "Internal caches" list upon creation by long clicking on the map.
For me they are always stored on the default list.

BTW:
Shouldn't we also rename the list "Internal caches" to "User defined caches" to be consistent?

@moving-bits 
In case this is no bug it could be considered as a feature request. I meanwhile use the UDC quite a lot to remember locations or plan caches and I always need to search for the UDCs as I expect them on the "Internal caches" list.

**Comment by moving-bits** [comment]
Current behavior is as follows:
- During migration of the "go to" history create a new list called "Internal caches" and store an internal "Go to history" cache in that list. (This will be one cache with several waypoints.) The id of this list may vary from installation to installation, depending on the amount of lists already stored on that device.
- If the user creates a user defined cache coming from the map, it is stored in the STANDARD_LIST,
- whereas if the user creates a user defined cache coming from a cache list, using the hamburger menu, it is stored in that list.

To implement this feature request we could
- store the list id for UDC as internal value in our settings.
- Upon retrieval, if the value does not yet exist, try to infer the id from the list name,
- and if that is not successful, fall back to STANDARD_LIST.

**Comment by Lineflyer** [comment]
I changed the topic accordingly. 
In fact its my usecase causing this as I always start by long click on map to create an UDC. 
So UDC created from map should end up in "Internal caches" list.

**Comment by fm-sys** [comment]
I changed the title, because the list now is named "User-defined caches" and should be used also here...
