### ISSUE TITLE
OSM online maps not working with legacy version

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8679]
Found while smoke testing legacy version:
OSM.org and OSM.de tiles are not loading. CyclOSM however works.

Tested on Android 4.4.2 device.

Need to check logs tomorrow to find the problem. My guess would be a SSL issue if we use https here.

**Comment by moving-bits** [comment]
All three map sources use https, but there may be differences in the type of certificate their servers use, and the encryption protocols they support.

**Comment by Lineflyer** [comment]
Seems like that, ADB log shows:

```
21:25:39.174 Error TileDownloadThread 32551  javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x645b1198: Failure in SSL library, usually a protocol error
21:25:39.174 Error TileDownloadThread 32551  error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5d9bf004:0x00000000)
21:25:39.174 Error TileDownloadThread 32551  javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x645b1198: Failure in SSL library, usually a protocol error
21:25:39.174 Error TileDownloadThread 32551  error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5d9bf004:0x00000000)
```

Can we use HTTP instead for legacy?

**Comment by Lineflyer** [comment]
Additionally we seem to continue the failing requests continously according to the ADB log.
The log is flooded with these exceptions and does not stop, although I do not even move the map.

**Comment by Lineflyer** [comment]
Obsolete as the legacy version for API 16-20 was removed from publication.
