### ISSUE TITLE
Change to line color accepted although cancelled

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8681]
User report for 2020.07.26-RC:
- Go to Settings - Map
- Open color picker for one of the lines
- Click on a new color (which is then indicated in a circle instead of square)
- Press "Cancel"

Result:
The menu still shows the old color, however after leaving and entering the Map settings the cancelled selection is active

Expected:
Don't change the color if the user cancels the dialog.

**Comment by moving-bits** [comment]
AFAICS the color actually does not change, but on reopening the dialog it still shows the old selection. Seems to be some kind of dialog caching. I'll try to intercept the cancel process to reset the selection to the original value.

**Comment by Lineflyer** [comment]
Not sure what you mean.
When trying to reproduce this report I had the impression that "Cancel" works like "OK", i.e. the new selected color is used but should not be used.
The fact, that the old color is still shown is a second problem IMHO.

**Comment by moving-bits** [comment]
I did the following steps:
- open settings => map
- chose color picker for direction line (current value is red)
- change this color to yellow, but close the dialog with cancel
- open the map
- chose a waypoint or cache and start navigation
- direction line is still drawn in red

but when instead of those steps I reopened the color picker directly after cancelling the previous dialog, the color is still set to yellow within the dialog, although the actual current value is red.
(I thought this was it what you had described in your opening post.)

**Comment by Lineflyer** [comment]
well, seems you are right at the end. I did not check the result on the map but made the failure to trust the menu content.

**Comment by Lineflyer** [comment]
BTW: How about a menu option to reset the line settings to "factory default". I just played around and really messed it up and don't remember the default values.

**Comment by moving-bits** [comment]
Behind the scenes all preferences objects get instantiated on opening the settings menu and live until the settings menu is closed, so on reopening a single color preference multiple times, it's always the identical object, not a newly instantiated one. I have prepared a small workaround for this, PR follows.

**Comment by moving-bits** [comment]
> BTW: How about a menu option to reset the line settings to "factory default".

Good idea.

> I just played around and really messed it up and don't remember the default values.

:-)

The default values are stored in `res/values/colors.xml`:

```
    <color name="default_trailcolor">#80000000</color>
    <color name="default_routecolor">#800000FF</color>
    <color name="default_trackcolor">#80008000</color>
    <color name="default_directioncolor">#80FF3333</color>
    <color name="default_circlecolor">#44BB0000</color>
    <color name="default_circlefillcolor">#66BB0000</color>
```

You can re-set them manually using settings => system => view settings, but you will have to convert them to an signed int first. Entries start with prefix `mapline_`:

![image](https://user-images.githubusercontent.com/3754370/88490149-bf05dd80-cf99-11ea-82fe-db55fc74b04d.png)

(Not sure how many of those values are still default, as I've played with them a bit already, but you may use them as a starter.)
