### ISSUE TITLE
Add option to reset mapline colors to default values

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8683]
Taken from https://github.com/cgeo/cgeo/issues/8681#issuecomment-664042399 by @Lineflyer:

How about a menu option to reset the line settings to "factory default". I just played around and really messed it up and don't remember the default values.

**Comment by moving-bits** [comment]
@Lineflyer 
Should this be prepared for release branch (as time permits), or for master anyway?

**Comment by Lineflyer** [comment]
Lets stay to the principle that release is reserved for bugfixes at this moment. So it should go to master.

I also always tend to provide such things faster, but we are changing and adding a lot of things in the past, so we should not forget quality. ;)

**Comment by moving-bits** [comment]
I know, and I really appreciate our focus on quality - that's one of the fundamentals for c:geo!

In this case I came from a user's perspective. Defining colors is a new feature, and you are probably not the only one who will start playing around a bit with it. So it might be useful to have a "reset to default" function integrated in the same release - that's why I asked for release branch.

Proposal for a two step way: 
- We could add a menu entry "Reset colors to default" beneath the GM/OSM "Map settings" menu. This would be targeted to release.
- And for master branch I could additionally look for a way to add a "default" button to the ColorPreference. (Not sure whether this is possible.) - This would be the more comfortable, color-specific way, but, from an implementation side, possibly a bit more risky. - Therefore target this to master branch.

What do you think?

**Comment by Lineflyer** [comment]
We wont get translations into release from Crowdin. Thats another argument for going to master with this change. 
But now you already merged it to release. So lets keep it in and add strings later.

IMHO no need for any second solution. The global reset entry should be fine.

**Comment by Lineflyer** [comment]
Correction:

I mixed up the PRs... All is well, just merge a fix for this one to master.

**Comment by MagpieFourtyTwo** [comment]
What about widths and opacities?
Have seen in the diff that something happens to line width, too, but had not enough context to see where it came from ...
So, if not done anyway, I would suggest to add a possibility to revert the other values to default, too.

**Comment by Lineflyer** [comment]
Yep, as mentioned in my comment which lead to this issue I would also prefer that this reset button resets all the line parameters to defaults.

**Comment by moving-bits** [comment]
Sorry, coming from the specific context I was too "color minded". I will open a separate issue to add line widths as well. (Opacities are already covered, as they are part of the color.)

**Comment by MagpieFourtyTwo** [comment]
BTW: When looking for the reset "Button", I first checked the map settings region ... was a little bit astonished, to finally find it in the map menu. YMMV, but I would say, settings would be the better place, cause a) you don't need this function every day and b) in the map menu it can easily be hit accidentally (although there's the "do you really" question).

**Comment by moving-bits** [comment]
See #8721 (removal of this option) and #8720 (alternative implementation, integrated into `ColorpickerPreference`)
