### ISSUE TITLE
After "Loading individual track" there should be a way to scroll to the track.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#8687]
**Is your feature request related to a problem?**
Once you have loaded an individual track, there should be a way to easily find it on the map as the track may not be where you 'are'.

**Describe the solution you'd like**
A menu option to scroll+zoom the map to show the complete loaded track.
Maybe this should happen automatically on loading a track.

**Comment by MagpieFourtyTwo** [comment]
+1

As workaround till it hopefully will be implemented:
- set track color and width to *really* visible values
- load track
- select a map tile to be displayed which does most definitely *not* cover the region of the loaded track 
- select one cache to be displayed on map (to declutter the map)
- zoom out ... and find the *really* visible track  ;)

HTH
