### ISSUE TITLE
Replace contacts plugin icon in "Useful apps"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8688]
The "Useful apps" screen still uses the old cgeo contacts icon. Should also use the new icon.

**Comment by Lineflyer** [comment]
Same for WhereYouGo.

**Comment by bekuno** [comment]
We need also an updated icon for send2cgeo ,
see also https://github.com/cgeo/cgeo.github.io/issues/235

**Comment by Lineflyer** [comment]
This has been done except send2cgeo, which is a dedicated issue.
