### ISSUE TITLE
GoTo waypoints lost after version upgrade

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8694]
A betwe user contacted our support with this statement:

```
I have stored a lot of waypoints in "GoTo" for planning my next hide. My phone automatically updated to version 2020.07.26-RC, now the GoTo waypoints are gone.
```

I am waiting for feedback for more details (e.g. if all waypoints are gone or only 5 remaining).

**Comment by moving-bits** [comment]
On migration of the old goto history we migrate only up to 5 waypoints, see `migrateGotoHistory()` in `DataStore.java`. But this is already some time ago, wonder if this can still be the cause, if the system got upgraded these days to a beta version...

**Comment by Lineflyer** [comment]
I will additionally ask from what version the user updated to the current beta...maybe...

**Comment by moving-bits** [comment]
@Lineflyer 
Any news on this?

**Comment by Lineflyer** [comment]
No, the user did not report back.
I would guess a generic problem of database upgrading?!.

Whatever lets close here until we get any new similar report.
