### ISSUE TITLE
Reactivate and retarget "map download link" in settings to new map downloader

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8695]
According to our changelog

https://github.com/cgeo/cgeo/blob/b07ecda8ae59dc06734fb895f5f0a1e7cdd5468e/main/res/values/changelog_release.xml#L9

we should have that feature now in our beta. A user asked me, what is behind this change.

I somehow lost the overview regarding this enhancement: Where can the user find this?

**Comment by moving-bits** [comment]
This is in Settings => Map (the "map button" symbol)
In its current form it only opens a browser with the link to the Mapsforge server.

Second part of this change - c:geo local file handler - has been deactivated for now due to its side effects.

Upcoming in release (if I ever get #8611 merged :-)) is the new map downloader which offers a new menu entry in map view's map source selector, downloads the map using the internal download manager, and stores the downloaded file in c:geo map directory. As soon as this is merged, we can link the above button to this functionality as well.

**Comment by Lineflyer** [comment]
Does this map button have some condition to be shown. Call me stupid....I don't see it. @moving-bits If you find time, could you provide a screenshot for stupid me ;)

**Comment by moving-bits** [comment]
Oops. It should have looked like this:

![image](https://user-images.githubusercontent.com/3754370/88711551-9fe18a00-d118-11ea-9877-77aa6745593f.png)

But it looks like I have disabled this as well when disabling the c:geo local file handler. Sorry for the confusion!

Two choices:
- either reenable this (by uncommenting a few lines of xml)
- or deleting the line in changelog regarding the download link

**Comment by Lineflyer** [comment]
Oh...I am happy, that I am not totally off my mind :)
I know I tested it once but now was unable to find.

Lets reenable this on release branch and we can push another RC some time afterwards.

**Comment by moving-bits** [comment]
Maybe I understand now why I had disabled it:

![image](https://user-images.githubusercontent.com/3754370/88713819-28155e80-d11c-11ea-9580-c5e1589ab950.png)

We would need to shorten the text, as the part beginning with "When downloading has completed" is no longer true after having disabled c:geo file handler. It should read now something like "Move the downloaded file to the map directory, rename it to have a file extension of ".map" and activate it by selecting it in c:geo settings" or such...

Alternatively we can disable this dialog, and directly open the browser after tapping the map icon.

**Comment by Lineflyer** [comment]
Ah yes, you are right.
Then we probably go for option 2. Remove it from changelog and elaborate an improved implementation on master.

**Comment by moving-bits** [comment]
Ok, updated release changelog accordingly.

I'll rephrase this issue to
- either remove this link and related code completely
- or target this link to the upcoming map downloader.

(Second option being preferred)

**Comment by moving-bits** [comment]
See #8724.

**Comment by moving-bits** [comment]
Fixed with #8724
