### ISSUE TITLE
colorAccent at mainActivity

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8701]
@moving-bits implemented the new colorAccent in the logo's orange tone (see #8606) 

So the blue line at the startscreen should be in orange to...

![signal-2020-07-29-003927](https://user-images.githubusercontent.com/64581222/88729357-fb6d4100-d133-11ea-8374-6a010168a24a.jpg)

**Comment by moving-bits** [comment]
There are a couple of more places in c:geo where the default colorAccent is still visible. 

Challenge is to find out, which style or theme is responsible for a certain layout element.
Only then I can add something like `<item name="colorAccent">@color/colorAccent</item>` to it.

**Comment by fm-sys** [comment]
I found that: https://stackoverflow.com/questions/18736300/android-change-color-of-line-below-actionbar

**Comment by fm-sys** [comment]
I will do a PR for this...
