### ISSUE TITLE
GPS and cgeo always on

### ISSUE THREAD

**Issue by Swoddler** [cgeo/cgeo#8704]
I'm sure this might be battery intensive but I believe cgeo can now have permission to access GPS even when the phone is asleep. Is it possible to keep the GPS always on so that cgeo can give proximity warnings even when the phone is asleep in the pocket?

**Comment by Lineflyer** [comment]
The ntofication in background requires more than just the location permission but also a programmed mechanism to perform actions in the background. 

If it is just about avoid to keep loosing your GPS precision please consider GPS Locker as listed in the useful apps list of c:geo.

**Comment by Swoddler** [comment]
No, it was the proximity alert which is the only real area where a Garmin
GPS outperforms cgeo when on a trail

**Comment by Lineflyer** [comment]
@moving-bits 
Do you know, whether we already have an issue for the fact, that proximity notification only works if the device is active?
If not, we could take this one as a feature request.

**Comment by moving-bits** [comment]
Not that I know of, but we have related issues, eg. "talking stops when screen is off". AFAIK we need to implement a foreground service (with permanent notification and associated rights), and activate it in the right places (probably depending on config setting, as not everyone needs this function, and it's more battery consuming than standard).

**Comment by Lineflyer** [comment]
Lets use #7057 for this as it contains already some ressource links. I will close this as a duplicate and change the title of #7057 accordingly.
