### ISSUE TITLE
Index creation issues in test cases

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8706]
Taken from https://github.com/cgeo/cgeo/pull/8611#issuecomment-665906109 by @moving-bits:

> > Let's see if it works if I leave out index creation for now
> 
> The test ran fine now :-)

That's good news. I missed this, as I ran the code first (which created the table and the index fine), and run the test later (so table did already exist).

There seems to be a difference in test management compared to a regular installation - `createIndices()` called before db upgrade routines during testing, leading to the error. I only wonder when this has changed, as we have earlier db changes with the same order I've used - create new table, then call `createIndices()` during the same update step...

---

- Investigate + fix
- re-create the index for extension table

**Comment by Lineflyer** [comment]
I have no clear idea, as I know to less about emulator testing.
However as far as I understand the emulator freshly installs the app. So no DB upgrade should be involved here but an initial creation. Or do we provide an existing config and DB to the emulator while initialising tests?
