### ISSUE TITLE
Fraction input field cut off when using Polish language

### ISSUE THREAD

**Issue by Eselter** [cgeo/cgeo#8708]
**Describe the bug:**
Coordinates popup cut off piece of fraction input field when using Polish language.

**To Reproduce:**
1. Set Polish language,
2. Click on 'Go to' (PL: Idź do),
3. Click on 'Add Waypoint' (PL: Dodaj punkt nawigacji),
4. Click on coordinates field.

**Actual behavior/state after performing these steps:**
Fraction input field is cut off with ' mark.

**Expected behavior/state after performing these steps:**
Whole input field should be visible with ' mark after it.

**Version of c:geo used:**
2020.07.26-RC

**Is the problem reproducible:**
Yes

**Screenshots:**
![Screenshot_2020-07-30-02-10-27-100_cgeo geocaching](https://user-images.githubusercontent.com/8573382/88866088-e9f66880-d209-11ea-99f3-c51aec95af57.jpg)

**System information:**
```
--- System information ---
Device: MI 6 (sagit, Xiaomi)
Android version: 9
Android build: PKQ1.190118.001
c:geo version: 2020.07.26-RC
Google Play services: enabled - 20.26.14 (100408-320008519)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (1.5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1.5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1.5 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1.0 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
I will alert our polish translation contributors to shorten the string.

@eselter
Do you have a proposal for a shorter polish word for this field. I am referring to the grey prefilled text in that field.

**Comment by Eselter** [comment]
"cz. ułamkowa" or "cz. ułamk." we sometimes use these abbreviation in math, nothing better comes to mind.

**Comment by Eselter** [comment]
But I think placeholder string length shouldn't determine how long is field and cause overflow in layout.

**Comment by Lineflyer** [comment]
@Eselter 
Did the modification on Crowdin solve this problem for you? 
In case not, please feel free to reopen.

**Comment by Eselter** [comment]
Yes, thanks for fix :)
