### ISSUE TITLE
Evaluate moving downloaded file instead of copying

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8712]
For the map downloaded (#8610/#8707) see if downloaded file can be
- either moved to target destination (check this first)
- or copied + deleted (use this as fallback)

see discussion in https://github.com/cgeo/cgeo/pull/8707#pullrequestreview-457922739 and following article

**Comment by fm-sys** [comment]
What about this issue? All my map downloads made some weeks ago are still in the public download directory, so it looks like they aren't deleted automatically by Android (even if disk space is low!). 
Some/most users will probably even not know that they have duplicated map files at their storage, so this feature would be really helpful!

**Comment by moving-bits** [comment]
I found no way to actually move the temporary file, as I do not have a `File` object but an `InputStream` (and a file based solution would not work as soon as we have to switch to API level 30 storage framework anyway), but I added explicitly deleting the temporary file after a successful copy operation, see #9261.
