### ISSUE TITLE
Using android language codes for translations?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8715]
Recently I have seen, that Crowdin reports a problem, that not all target languages will be transferred due to a mapping problem.
As we use the "two letter code" for the language Crowdin states, that some dialects/language may not be transferred as this "two letter code" would be the same.
Crowdin recommends to use the "android code" instead.

This would result in this structure:
![image](https://user-images.githubusercontent.com/949669/88983495-7a48b200-d2cb-11ea-9c19-2db539987737.png)

Can the build engine support that?
If yes, I would like to change it accordingly.

**Comment by rsudev** [comment]
Do you know which languages would be affected?
In general I assume that such a structure would work, but we have to rename the folders in git to keep the history properly (and to avoid duplicate resources).
Generally I am not sure if this is a good idea, as this would IMO leave eg an Austrian user (de_AT) with c:geo in English.

**Comment by Lineflyer** [comment]
I am not sure why Crowdin now claims this problem.
For WhereYouGo I had a similar problem and solved it by adding a manual language mapping for Brazilian.

Maybe its related to the two Chinese dialects, in that case I could also try to add manual mapping of one of them. But I have no idea how those are mapped.

**Comment by bekuno** [comment]
A sample is at https://developer.android.com/guide/topics/resources/providing-resources#BestMatch
but the de_AT problem above is not covered.

**Comment by Lineflyer** [comment]
@rsudev 
I think the probable reason for the Crowdin warning is, that since you enabled "Chinese (Traditional" we have two chinese variants not having separate two-letter-codes:

Chinese | zh
Chinese (Simplified) | zh-Hans
Chinese (Traditional) | zh-Hant

**Comment by Lineflyer** [comment]
I tried to crawl for possible solutions to the doubled Chinese problem, but I have no idea.
Most sources are anyway using the "android language code", thus not having this conflict.

So I do somehow get back to the initial question:
Can our build system support the initially mentioned language code as string directories?
AFAIR we can resolve the de_DE vs de_AT problem on Crowdin. There is some option like "Use main language translations for dialects".

**Comment by moving-bits** [comment]
> So I do somehow get back to the initial question:
> Can our build system support the initially mentioned language code as string directories?

Yes and no. Tricky and slippery area, I would say after a quick glance at the following resources:
- https://developer.android.com/training/basics/supporting-devices/languages
- https://gist.github.com/amake/0ac7724681ac1c178c6f95a5b09f03ce
- https://developer.android.com/guide/topics/resources/multilingual-support

**Comment by Lineflyer** [comment]
@moving-bits 
Reading through the links you provided, what would be the solution to cover traditional chinese in addition to simplified chinese (currently mapped to `values-zh`).
I could create a mapping on Crowdin, just need to know the code to use so that it works on recent devices.

**Comment by moving-bits** [comment]
The mapping we currently use (`values-zh-rTW`) seems to work fine AFAIK.
Is this all we needed to mollify Crowdin, so that we can close this issue?

**Comment by Lineflyer** [comment]
Yes, I think it is solved by adding the exception rule on Crowdin.
