### ISSUE TITLE
Custom cache icons support

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#8719]
Feature request for being able to use custom icons for geocaches.

Currently the icons are included in the apk only. Instead they could be loaded from a user-specific directory with predefined filenames.
This would allow users to set their own cache icons and shapes and allow the community to create icon packs.

Advanced custom icons could also include additional information as is currently possible in Locus, e.g. to include D/T-rating or size in the icon itself.

References:
https://forum.asamm.cz/doku.php?id=manual:advanced:customization:icons&s[]=icons#geocaching_icons
https://forum.locusmap.eu/index.php?topic=3048.0

**Comment by jonas-koeritz** [comment]
This would require a complete rewrite of how we do cache map markers. The current solution is map view specific and kind of hard to grasp. Maybe someone wants to have a try on creating a central cache map marker factory or something like that.

**Comment by Lineflyer** [comment]
IMHO this would be some kind of overkill regarding the needed coding effort and the amount of users with need for it.

**Comment by Lineflyer** [comment]
We implemented a similar solution with a bunch of custom icons. IMHO that is a good compromise to full self defined icons.
See #9523 and #9666

**Comment by ztNFny** [comment]
@Lineflyer I fear this feature request was misunderstood. I wasn't asking for icons for invididual caches as implemented in #9523 but for the ability to change icons based on the cache type. So instead of the current green cgeo "Traditional" icon every traditional instead has "my" custom icon shown.

I'm attaching a screenshot of my current Locus setup to illustrate. Cache icons should be clear, the info on the left ot the icon is D, T, size.

I fully understand if there's no interest/capacity to implement this, but I feel this issue has been wrongly closed due to a misunderstanding now.

![Screenshot_20210106-150608__01](https://user-images.githubusercontent.com/1258173/103777637-7adf3480-5031-11eb-88f0-dd40d6b0d580.jpg)

**Comment by Lineflyer** [comment]
I understand, but as written above it was considered as too much effort for potentially small base of advanced users. So my posting was more to signal, that the now implemented approach is all we plan to do on this topic.

Sorry for that.

**Comment by ztNFny** [comment]
@Lineflyer Ok, thanks for the clarification.
Do you think a request not for custom icons bit for more info in the standard icons (like d,t) would be considered? That quick overview is a major feature I miss from Locus - it avoids those situations where you walk to a cache only to realize there it's a T5
