### ISSUE TITLE
Support for OBF offline maps

### ISSUE THREAD

**Issue by apachler** [cgeo/cgeo#8728]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Do you have any plans to support the OBF map format that OsmAnd is using for offline maps?

**Comment by moving-bits** [comment]
Seems like OBF is a completely different file format for OpenStreetMap maps, which is not supported by the renderer library we use (Mapsforge), so chances are we won't support them (won't be able to).

**Comment by SammysHP** [comment]
There is no library for OBF rendering, so we cannot add support for it. Please see #2913 for more information.

**Comment by vaxul** [comment]
@SammysHP is it an option to contact OsmAnd developers to find a solution for this issue. Maybe some kind of corporation? 
For me personally OsmAnd is the best offline map solution. I have some GBs of maps which would be nice to use in c:geo.

Best regards
