### ISSUE TITLE
Cannot store waypoints into empty personal note

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8729]
**Describe the bug:**
Cannot store wapoints into empty personal note - will receive an error message "Waypoints could not be stored in note due to size limits":

![image](https://user-images.githubusercontent.com/3754370/89116644-af553000-d496-11ea-9a57-9bdc3a5cdcd2.png)

**To Reproduce:**
- open a cache (GC2BG6B in my case)
- go to waypoint page
- create a new waypoint (it's the only one in this case)
- return to cache details page and press "Store Waypoints"

**Actual behavior/state after performing these steps:**
Error toast "Waypoints could not be stored in note due to size limits"

**Expected behavior/state after performing these steps:**
Waypoints being stored into note as described in #8608

**Version of c:geo used:**
Today's master including #8608

**Is the problem reproducible:**
Yes, have also tried with different waypoint types and numbers.

@eddiemuc 
Can you look into this?

**Comment by eddiemuc** [comment]
I will handle this. 

Retested this and works in my local emulator. So probably something is different in the envronment.
This function depends on the value delivered by provider-connector in the CacheDetailActivity. I might have made wrong assumptions about it. 

@moving-bits  some questions so I can analyze this better:
* is your test device/emulator online and are you connected and logged-in to the GC backend?
* was the cache in question locally stored before (it is auto-stored when creating a waypoint, but was it stored before too?)

**Comment by moving-bits** [comment]
> @moving-bits some questions so I can analyze this better:
> is your test device/emulator online and are you connected and logged-in to the GC backend?

I'm using an emulator running on Android 7 in this case.
Emulator is connected, c:geo logged in as basic member.

> was the cache in question locally stored before (it is auto-stored when creating a waypoint, but was it stored before too?)

Yes, it was stored ("16 hours ago"). But just retested it, and it still happens.

Can I help you with further information?

**Comment by eddiemuc** [comment]
Same setup as on my device. I am a bit stumped currently. My guess is that in some situations the maxPersonalNoteSize in CacheDetailActivity is not initialized when I use it, but I can't currently see how that can happen.
I wrote a fix (see linked PR) which either resoles the problem (if my guess is correctly) OR will give me more information in case it happens again.

**Comment by eddiemuc** [comment]
@moving-bits  in case PR does NOT solve the issue, I would ask you about more info how you create your waypoint (with or without coordinate, do you modify name/usernote etc). I think a screenshot for one example waypoint would do.

**Comment by moving-bits** [comment]
The fix seems to work for the scenarios I'd tested it against - thanks for fixing.

As for how I created the waypoints: Nothing special involved:
- open waypoint page of a cache
- variation a)
  - "add waypoint"
  - click on coordinates
  - click on "cache coordinates"
  - change the content of one field and save
  - either do or do not change the waypoint type
  - save waypoint
- or variation b)
  - simply hit "add current location"

Error occurred even with only one waypoint, but also with two or three.
