### ISSUE TITLE
Cannot login to opencaching.de on 4.4.2

### ISSUE THREAD

**Issue by Skinoku** [cgeo/cgeo#8749]
Dear developers,
I was trying to log in to opencaching.de on Android 4.4.2 and it is not working showing this error message.
"c:geo failed to initialize authorization process"
I repeated the test on multiple devices and VMs running kitkat with no success.
Are you aware of this issue and is it planned to be fixed?
Thanks this great app!
Cheers

**Comment by Lineflyer** [comment]
This is a known issue due to server SSL configuration not supporting older Android devices. We have plans for a workaround in future. See #7497
