### ISSUE TITLE
Legacy version on F-Droid

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8750]
Followup of #8602 

We should add the newly established legacy version (and future updates to it) also into our F-Droid repository.

Mention @kumy

**Comment by kumy** [comment]
I have to setup a new repository for the `legacy` versions. We only have `release` and `nightly` at the moment.

**Comment by kumy** [comment]
@Lineflyer done. I hope I did not forget anything ;)

And a new CI job has been created https://ci.cgeo.org/view/FDroid/job/Publish%20FDroid%20-%20LEGACY/
