### ISSUE TITLE
Osm.de and CyclOSM not available for a user

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8766]
From Facebook:

A user on 2020.08.04 posted some screenshots which definitely miss those twonmaps in the selection menu.

On another device it works for the same user. I asked to contact us.
Any ideas?

**Comment by moving-bits** [comment]
Use Old Mapsforge in settings?

**Comment by Lineflyer** [comment]
Thats it. Thanks, lets leave it like that....
