### ISSUE TITLE
Coordinates in note as a waypoint

### ISSUE THREAD

**Issue by karelkilian** [cgeo/cgeo#8771]
**Is your feature request related to a problem?**
In earlier versions, if I had coordinates in a note, the application displayed them as waypoints. This is not the case now.

**Describe the solution you'd like**
If possible, please display the coordinates from the notes as waypoints.  Maybe optional.

**Additional context**
I used the coordinates in the note to save my own parking point, that I selected from Google Maps on web. Then I could navigate to them using navigation (Waze, etc.)

Thank you very much!
Karel

**Comment by Lineflyer** [comment]
This should still be the case, except if you explicitly disabled this feature with the checkbox under the personal note window.

What coordinate format are you using in your note (can you give an example)?

**Comment by karelkilian** [comment]
Hi,

thank you very much for your reply! I think, that I have not disabled this feature (I am attaching a screenshot).
I did this by putting a note on the Geocaching website: **Parking N 49 ° 50.670 ', E 18 ° 25.647'**
I then refreshed the geocache in the application c:geo and saw this point as a waypoing to which I can navigate. I don't have it as a waypoint now.

Karel
![2020-08-09 13 20 34](https://user-images.githubusercontent.com/69420072/89730985-cf12c800-da43-11ea-88b6-024eae51a321.jpg)
![2020-08-09 13 25 44](https://user-images.githubusercontent.com/69420072/89730989-dafe8a00-da43-11ea-83f2-4ce9d5e95772.jpg)
![cache](https://user-images.githubusercontent.com/69420072/89731008-f8335880-da43-11ea-939b-33b9968b97eb.png)

**Comment by karelkilian** [comment]
On the second screenshot are only parking points from owner, but not mine "parking point" at N 49°58.17493', E 18°6.00290'.
Earlier versions of c:geo did it right - converts my personal parking point from personal cache note to waypoint.

**Comment by eddiemuc** [comment]
Hi @karelkilian , I tried this and can confirm your described haviour. As a possible workaround: it seems parsing works fine when you leave out the comma between lat and lon (Like this: N 49°58.17493' E 18°6.00290')

**Comment by karelkilian** [comment]
Thank you very much! I can confirm, that if i write coordinates withnout coma between lat and lon, that it works :-)
Excellent workaround - thank you!

**Comment by Narrat** [comment]
This sounds like a result of https://github.com/cgeo/cgeo/pull/8597
Changed behaviour because otherwise there was the possebility of non-existing coordinates being parsed.

**Comment by karelkilian** [comment]
@Narrat Yes, it looks like a result of this fix.
OK, I can accept it. I will use in personal cache note coordinates without coma.
