### ISSUE TITLE
Implement recording Debug Logs to file (as with Crash Logs)

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8777]
**Is your feature request related to a problem?**
When it comes to crashes, Debug Logs are (way more than just) pretty helpful. This is where the new function ``Create logfile`` comes into play. Great stuff, but seemingly not helpful, when trying to analyze weird app behavior *with no crash at all*, cause ``Create logfile`` seems to record crash scenarios only. Thus: No crash, no (current) log (at least I was not able to get a usable one while testing for #8632 and #8682).

**Describe the solution you'd like**
c:geo should start to build a logcat itself (like it does when clicking ``Create logfile``) as soon as I set ``[X] Activate Debug Log`` and ask for save or share, as soon as I remove the ``[X]`` again.

**Describe alternatives you've considered**
Had to create the Debug Logs with a third party app, but for Joe Average this is not really a suitable way.

**Additional context**
Maybe a special sequence of setting ``[X] Activate Debug Log`` and pressing ``Create Logfile`` may lead to the same result, but I was in fact not able to get there ... if it was just my mistake, I guess we need a more detailed instruction in the menu ...?

**Comment by MagpieFourtyTwo** [comment]
BTW: The locgcat's name contains ``hh`` in 12-hour notation, but no day/night indicator, so it would probably be better to use ``localtime()`` (or android equivalent) for the hour, in order to get 24-hour notation ...

**Comment by moving-bits** [comment]
c:geo does not store its own logfile, but queries the system to extract c:geo related messages from the system logfile when hitting the "Create logfile" button. This is currently filtered to the following message classes:
- AndroidRuntime:E
- cgeo:D
- cgeo.geocachin:E

catching error messages from system and c:geo's internal debug & error messages.
Maybe this needs to be extended to (optionally) include lower message levels like "info".

**Comment by MagpieFourtyTwo** [comment]
> c:geo does not store its own logfile

Yep, nevertheless the extracted data have to be written to a separate file - that was what I had in mind with "build a logcat itself". ;)

> Maybe this needs to be extended to (optionally) include lower message levels like "info".

That would be perfect, as with the help of their timestamps one can determine where e. g. time gets lost ...

**Comment by moving-bits** [comment]
> BTW: The locgcat's name contains `hh` in 12-hour notation, but no day/night indicator, so it would probably be better to use `localtime()` (or android equivalent) for the hour, in order to get 24-hour notation ...

Good catch! Probably the format string should read `yyyy-MM-dd_HH-mm` instead of `yyyy-MM-dd_hh-mm`. => I'll create a PR for this.

**Comment by Lineflyer** [comment]
I dont get the reasoning behind this feature request:

IMHO if you activate debug logging in c:geo and later on save the logfile as currently implemented it will also contain a big portion of the history. In fact as I tried it using c:geo all the day with activated debug log, the logfile I saved afterwards was several megabyte and covered some hours.

**Comment by moving-bits** [comment]
Logging is done automatically by the system (always), there's no "start/stop mechanism" in c:geo for this. Hitting "generate logfile" only extracts the messages from this existing system logfile and writes it to a separate file, applying certain filters along the way. (Though there is a "start/stop mechanism" for generating _additional c:geo-internal_ log info - that's the "activate debug log" checkbox under settings - system.)

PR #8779 adds an option to apply less restrictive filters during this process to receive a more detailed logfile.

**Comment by MagpieFourtyTwo** [comment]
Ok, my fault, not exact enough:
- start/stop was meant as lower and upper bound for the logcat extract in terms of the timestamps of these two moments
- so, the moment I set ``[X] Activate Debug Log`` should be the start of the interval, c:geo's ``Write Debug Log`` should write it's messages to "our" file
- and the moment I set ``[_] Activate Debug Log`` should be the end of the interval to be extracted
That's because I assume, a logcat file which contains even Info messages, and will poss. reach back to the last system restart, will most probably become *way* too big to interpret it resp. to find the really important parts. Thus limiting the extract to the interval between these two timestamps will most probably catch the really important parts.

**Comment by MagpieFourtyTwo** [comment]
Or is there a(nother) possibility to "set" the start of an extract?

**Comment by MagpieFourtyTwo** [comment]
> IMHO if you activate debug logging in c:geo and later on save the logfile as currently implemented it will also contain a big portion of the history. 

As described above, the current implementation just extracts "error messages from system and c:geo's internal debug & error messages" - which is not sufficient, if there were no errors at all, but e. g. just "hangers". Or extremely time consuming operations. Or several restarts of an operation ... as with #8632: Although there is a delay of several seconds, the currently implemented c:geo logfile was empty. But for a deeper insight, you possibly want to know how much time the single steps have taken - although they exited with a "good" exit code (thus not generating an error message to system's logcat).

**Comment by moving-bits** [comment]
> * start/stop was meant as lower and upper bound for the logcat extract in terms of the timestamps of these two moments
> * so, the moment I set `[X] Activate Debug Log` should be the start of the interval, c:geo's `Write Debug Log` should write it's messages to "our" file
> * and the moment I set `[_] Activate Debug Log` should be the end of the interval to be extracted

You can't really control this behavior, as the logfile is managed by the system only.
Somewhere in the developer settings you can set the maximum size for the logfile, but I doubt that many people have changed this.

Filtering by time is only available on recent Android versions (or at least: it does not work on older versions, and it's not documented since when what parameters of `logcat` are supported).

> That's because I assume, a logcat file which contains even Info messages, and will poss. reach back to the last system restart, will most probably become _way_ too big to interpret it resp. to find the really important parts. Thus limiting the extract to the interval between these two timestamps will most probably catch the really important parts.

The sequence to go would be:
- activate the additional log info in settings
- do whatever you want to have a protocol for
- then write an "extended logfile" (see #8779)
- deactivate the additional log info in settings

Whether this logfile will contain useful information for a release version varies widely, as most parts of c:geo currently do not write debug/info messages, but only exceptions. So probably in the event of trying to trace down something tricky, additional logging would have to be programmed specifically for that case, then our testers can use that version with the sequence above, and then the devs can try to analyze the logfile(s).

**Comment by MagpieFourtyTwo** [comment]
> You can't really control this behavior

So it's not possible, to drop messages before or after a given timestamp? Ok, thought you could at least parse the records and check against a timestamp.  Hmm.  Would have helped to focus on the critical passage. Ok.  Bummer.

> additional logging would have to be programmed specifically for that case

I guess, having the info messages' timestamps at hand (resp. the time inbetween) may probably at least give a hint for the region to investigate deeper, where then the devs can finally add some debug info, which will then be written to syslog. And this perhaps even depending on the setting of ``[X] Activate Debug Log`` (which is in fact pretty much my way of debugging, if I can not get my fingers on an issue).

**Comment by Lineflyer** [comment]
As generic information for you @MagpieFourtyTwo 

c:geo can produce debug information at various stages, where developers included them. This information is only written to the syslog if "Activate debug log" is activated. Without this only exceptions are included.

@moving-bits 
I think it might be wise to expand the filter to type Information and Warning for our package name? Is that, what you included in your proposed enhanced logging?

**Comment by moving-bits** [comment]
> I think it might be wise to expand the filter to type Information and Warning for our package name? Is that, what you included in your proposed enhanced logging?

Yes, even a bit more:
```
if (fullInfo) {
    builder.command("logcat", "-d", "*:V", "-f", file.getAbsolutePath());
} else {
    builder.command("logcat", "-d", "AndroidRuntime:E", "cgeo:D", "cgeo.geocachin:E", "*:S", "-f", file.getAbsolutePath());
}
```

`AndroidRuntime:E", "cgeo:D", "cgeo.geocachin:E"` is filtering on certain prefixes and message levels (debug/error), whereas `"*:S"` suppresses all the rest. If using the new `fullInfo` we don't do this filtering but include everything starting with the lowest level (view): `"*:V"`.

**Comment by moving-bits** [comment]
> > You can't really control this behavior
> 
> So it's not possible, to drop messages before or after a given timestamp? Ok, thought you could at least parse the records and check against a timestamp. Hmm. Would have helped to focus on the critical passage. Ok. Bummer.

Exactly, at least not with the current way of calling `logcat`. We could include sort of post-processing, but IMHO that's a bit too much for this use case.

> I guess, having the info messages' timestamps at hand (resp. the time inbetween) may probably at least give a hint for the region to investigate deeper, where then the devs can finally add some debug info, which will then be written to syslog. And this perhaps even depending on the setting of `[X] Activate Debug Log` (which is in fact pretty much my way of debugging, if I can not get my fingers on an issue).

Timestamps are less important in most cases than one might think, as we are talking about a multi threaded environment with many parallel tasks (from other apps) happening in parallel - the exact order and timing nearly always will be quite different. More of importance is the source of a specific error, which we get on crash exceptions or if we write something to the log explicitly.
