### ISSUE TITLE
Issues with offline logs

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8781]
taken from https://github.com/cgeo/cgeo/pull/8776#issuecomment-671519602 by @moving-bits:

I have an imported database having caches from geocaching.com and opencaching.de. c:geo shows "4+228" and "85+1" as found counter, but when I go to "all caches" list (> 6.000 caches) and filter "With personal data => With offline log" it lists only two caches at all. Strange.

---

Querying the database directly reveals the expected amount of offline logs entries, and the caches being referenced in those logs are available in `cg_caches` table as well.

Difference may arise from the fact, that the caches not being shown by the filter are not sorted into any list. Also they are not shown even in "All caches" list even without any filter. Cache counter of "All caches" list and actual number of caches in database differ by the same amount.

---

This gives us (at least) the following options:
- Caches are ignored intentionally (1)
  - either: offline logs and accompanying caches could be deleted (1a)
  - or: offline logs are preserved intentionally for possible later usage, and therefore the referenced caches need to be stored as well (1b)
- "All caches" list and "offline log filter" are wrong and should show those caches. (2)
- "Offline found counter" should exclude caches which are not sorted into any list. (3)

I tend to (1b) + (3), but maybe someone with more background on the history of c:geo can explain whether caches without lists are to be ignored intentionally, and which of the above options (if any) are ok?

**Comment by Lineflyer** [comment]
I only remember two things which IMHO might be related:

- Caches may stay 72 hours in our database after deletion as caching mechanism until housekeeping clears them completely.
- We had an issue some time, that offline logs might be lost if the user accidentally deletes the caches. The user (unaware of our data structure) expected to still see them in the history. There was a related code change to (somehow...I dont remember) solve this problem. AFAIR in this case the cache is no longer on any list but still visible in history with its offline logs until the offline log is explicitly removed or the cache cleared from history.

**Comment by moving-bits** [comment]
My bad: I had missed the "history list" - which includes the missing caches which have an offline log, but do not show up on any other list. See https://github.com/cgeo/cgeo/pull/8776#issuecomment-673071699.
