### ISSUE TITLE
Update Playstore Images

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8786]
As there where some more or less major UI changes in the last weeks, months and years I would like to update the screenshots shown at Google Play

Some of the UI changes:
- new icon
- new colorAccent
- no more orange circles on live map
- cache details activity - buttons have icons instead of text
- cache details activity - map section is no longer shown
- action bar has no more blue line except main screen, here the color was changed
- and so much more...

Question: In which languages are the screenshots currently available and need to be updated? 
Edit: Looks like they are provided in [German, English and French](https://github.com/cgeo/cgeo/tree/master/main/project/playstore/screenshots)...

And when we're on the go, the [Feature graphic](https://raw.githubusercontent.com/cgeo/cgeo/master/main/project/playstore/icons/cgeo_functional_graphic.jpg) should also be updated as well and could then be integrated also as first (first two) screenshots ...

---
And (if it's OK) I would like to make these pictures a little more modern, like other apps are doing it as well. For example like Threema is doing it:

![Screenshot (Aug 11, 2020 5 37 09 PM)](https://user-images.githubusercontent.com/64581222/89918287-20fd4e80-dbfa-11ea-9b7a-7cf998b3fe7f.png)

**Comment by Lineflyer** [comment]
This would be more than welcome. Great idea.

You can find the existing assets here:
https://github.com/cgeo/cgeo/tree/master/main/project/playstore/screenshots

You can also place your suggestions as a PR in that directories.

**Comment by fm-sys** [comment]
The pictures could look like this...
![c;geo playstore bilder](https://user-images.githubusercontent.com/64581222/89953385-448ebc00-dc2f-11ea-8807-bf4ea2dc2a42.jpg)

What do you think?

**Comment by Lineflyer** [comment]
Looks good in principle. I would tend to use a non transparent background (activate corresponding setting in c:geo) to make it look more neutral.

The file specifications for Google Play are:
JPEG oder 24-Bit-PNG (kein Alpha). Mindestlänge für eine Seite: 320 px. Maximale Länge für eine Seite: 3.840 px.
Minimum 2 Screenshot, maximum 8 screenshots pro Sprache

As it is a too big amount of work to maintain screenshots for all languages, I suggest to strip it down either to use only English or maximum to 3-4 countries with most users. These are Germany, US, Czech Republic, France.

**Comment by Lineflyer** [comment]
While you are on it and if you are able, you could also try to make a new version of the functional graphic:
https://github.com/cgeo/cgeo/blob/master/main/project/playstore/icons/cgeo_functional_graphic.jpg

**Comment by fm-sys** [comment]
> Edit: I would recommend to use it in a logged in state (and erase the user name) instead of having the error shown.

I will patch the App for the screenshots, so that it will show "Max Mustermann / John Doe" instead of my user name ;-)

**Comment by fm-sys** [comment]
So I would provide the screenshots in English and German first, if it's ok. 

Also I want add some text above the screenshots. I will upload the PowerPoint for the Images to, so that someone else could translate the text into other languages as well...

**Comment by fm-sys** [comment]
![entwurf](https://user-images.githubusercontent.com/64581222/90169146-7d996e80-dd9e-11ea-813a-4a4029e39720.jpg)

The picture will be split up into its individual parts when it is completely finished. Of course it is far from being finished, but is that something we can work with?

And please ignore that the texts are English but the c:geo translated to German ;-)

Whould you leave out the "c:geo - Geocaching for Android" including the background picture and leave everything orange? Then everything whould be like on the right side... What do you think?

**Comment by Lineflyer** [comment]
IMHO the background change is nice and makes it "living". I would replace the "over x supported" by something like "Multi platform support" or "Supporte multiple geocaching services".

But really nice from its principle.

**Comment by Lineflyer** [comment]
Some idea (feel free to find better ones) for the headers:
- Interactive live map (sounds good already)
- Save and manage caches in lists
- Log found finds online or offline
- Full offline support incl. maps
- Full support of trackables

**Comment by eddiemuc** [comment]
* Go caching on all major platforms in just one app: Geocaching.com, OpenCaching, GCVote and many more

**Comment by Lineflyer** [comment]
You should enable an oc platform to have multiple platform caches in screenshots.

**Comment by Lineflyer** [comment]
Maybe also "Community driven" or "Free and opensource", "Made by Geocachers" ...just thinking loud.

**Comment by Lomanic** [comment]
https://github.com/cgeo/cgeo/issues/8786#issuecomment-673631302 the orange text "Geocaching for Android" is hard to read for me, lacks some contrast against the background.

Great work otherwise 👍

**Comment by eddiemuc** [comment]
Really great work, thank you for this contribution! 👍

**Comment by eddiemuc** [comment]
Some more possible headlines (Just thoughts):
* One for all: Cache across all platforms (Show screenshot of map with gc-caches and OpenCaching caches in same Screen)
* Navigate to Caches the way you want (Show screenshots of compass, some satellite map View and map with Route to Cache)
* Never miss a cache in your route again (Show screenshot with notification settings for nearby Caches)
* Always stay on the right track (Show individual routes as well as GPX import/Export )
* Create your own waypoints (Show self-created waypoints on a map)

**Comment by fm-sys** [comment]
Is there maby a c:geo website trackingcode or a trackable I could use for the last screenshot?

**Comment by fm-sys** [comment]
![c;geo playstore images - screenshots](https://user-images.githubusercontent.com/64581222/90237616-dad80300-de24-11ea-87cc-9edc787b9a8b.jpg)

My pictures have reached beta status ;-) Feedback is very welcome!

**Comment by Lineflyer** [comment]
Looks really good, some small comments:
- Use English screens (AFAIK you already said you will change them later)
- live map instead of live-map
- For the last screen you could use what I sent to you (did it arrive?)

**Comment by Lineflyer** [comment]
Given the effort I would suggest to produce english and german only for now?!

**Comment by fm-sys** [comment]
> For the last screen you could use what I sent to you (did it arrive?)

Nothing has reached me yet...

**Comment by fm-sys** [comment]
@Lineflyer Ignore my comment above... I was waiting for an email 😂 
What you sent me arrived yesterday. Thanks for it at this point - very cool, I like it!

**Comment by eddiemuc** [comment]
Looks really cool!

**Comment by moving-bits** [comment]
Thanks @fm-sys for this contribution, your "beta version" looks really good!

**Comment by moving-bits** [comment]
One tiny idea: How about showing some routing (navigation) line and/or a track on the map screenshot?

**Comment by moving-bits** [comment]
As for the "Navigate to caches" screenshot: I'm unsure whether the user expectation would be a compass rose or something like Google Maps navigation (or whatever else navigation software is installed).
@Lineflyer Ccoming from support questions or talks on events: What do you think?

**Comment by fm-sys** [comment]
I think showing the compass rose is better then showing a screenshot from eg. google maps... If you have a better text please tell me. Otherwise I would vote for leaving it as it is. The pictures are there to show how the app looks like. Not to give a complete functional overview

**Comment by eddiemuc** [comment]
Regarding "Log your finds offline or online": I think it would be nice if the screenshot contains the Rating Stars (visible when GCVote is enabled), simply because it looks kinda fancy

**Comment by fm-sys** [comment]
@eddiemuc isn't GCVote currently broken? http://gcvote.com/ Because I wouldn't like to show features wich users can't use...


![c;geo playstore images - screenshots_hoffentlich final -transparent](https://user-images.githubusercontent.com/64581222/90284672-9d9a6200-de72-11ea-9ff8-2aefab4a7555.png)
I will use English screens if you accept it as "release candidate" ;-) 
 --> means no more graphical changes needed except maby GCVote

**Comment by eddiemuc** [comment]
> @eddiemuc isn't GCVote currently broken? http://gcvote.com/ Because I wouldn't like to show features wich users can't use...
> 

I was not aware of that. Strange, I used GCVote rating during last years without noticing this.
But in this case, of course it doesn't make sense to include it in the screenshots

**Comment by Lineflyer** [comment]
The GCVote API worked last time I used it. Seems the website is not maintained. This status was a year ago, but finally the owner managed to get it working again. AFAIR the website was again working after that. Strange.

**Comment by fm-sys** [comment]
Ok, I've mailed the GCVote developer to create an account for me... Let's see if he answers.

**Comment by eddiemuc** [comment]
Do these screenshots help you?
![Screenshot_20200815-165331.jpg](https://user-images.githubusercontent.com/6909759/90315029-5ff01480-df18-11ea-8f9c-69eca1509b54.jpg)![Screenshot_20200815-164531.jpg](https://user-images.githubusercontent.com/6909759/90315034-63839b80-df18-11ea-8ad8-92033bb56592.jpg)

**Comment by fm-sys** [comment]
@eddiemuc thanks for the images! I used them because I still have no GCVote acount... But I edited them a bit ;-)

![c;geo playstore images - screenshots - deutsch_](https://user-images.githubusercontent.com/64581222/90370173-414f6200-e06d-11ea-85d9-0e6ff7738252.png)
Final German Version
---
Can we keep it that way?

**Comment by moving-bits** [comment]
Great work, like it! Thanks @fm-sys for putting all the effort into this.

Two little questions:
- Do we want to include an actual trackingcode into one of the screenshots?
- For the live map I would appreciate if we could include a routing line (having BRouter activated), if it's not too much effort. Having in app navigation using BRouter is a great feature that too few people know of, sadly.

**Comment by fm-sys** [comment]
> Do we want to include an actual trackingcode into one of the screenshots?

It already is ;-) Take a look at the 6. image...

>For the live map I would appreciate if we could include a routing line (having BRouter activated), if it's not too much effort. 

Yes you're right! I will include it. 


![Screenshot_2020-08-17-10-59-53_framed (Phone)](https://user-images.githubusercontent.com/64581222/90378117-3f8b9b80-e079-11ea-90c6-f1a7f989f3b5.png)


Also I was thinking about individual track, but we should not overload the screenshots...

**Comment by Lineflyer** [comment]
Small comment:
You could add the new c:geo logo or even a photo of the coin as avatar picture to the trackable in order to show, that we also include pictures in TB listings.

**Comment by moving-bits** [comment]
> > Do we want to include an actual trackingcode into one of the screenshots?
>
> It already is ;-) Take a look at the 6. image...

I had seen this, but my comment was meant the other way around: If we include an actual tracking code, the person that TB belongs to might get many logs for it. Question is if this is intended or at least accepted by the owner of that TB. If yes, then I'm fine with including an actual TB code.

> > For the live map I would appreciate if we could include a routing line (having BRouter activated), if it's not too much effort.
>
> Yes you're right! I will include it.
> [...]
> Also I was thinking about individual track, but we should not overload the screenshots...

Yes, agreed, and thanks for including the routing line.

You might set a different color for the routing line (near-solid blue?), to make it more visible in the screenshot. There's much red currently :-)

**Comment by fm-sys** [comment]
> You might set a different color for the routing line (near-solid blue?), to make it more visible in the screenshot. There's much red currently :-)


I already tryed so but my emulator crashes: see  #8813 / #8816
>You could add the new c:geo logo or even a photo of the coin as avatar picture to the trackable in order to show, that we also include pictures in TB listings.

I also tryed so but c:geo doesn't show the image: https://geokrety.org/konkret.php?id=81241

**Comment by Lineflyer** [comment]
> I also tryed so but c:geo doesn't show the image: https://geokrety.org/konkret.php?id=81241

You have to open the gallery for this Kret and select it as Avatar. When done, it might take 30 minutes to show up (refresh in c:geo).

**Comment by moving-bits** [comment]
> > You might set a different color for the routing line (near-solid blue?), to make it more visible in the screenshot. There's much red currently :-)
> 
> I already tryed so but my emulator crashes: see #8813 / #8816

I can look into this in the evening, maybe create the screenshot.

Or as a workaround, you can set the color manually using Settings => System => View Settings and then set the value for `mapline_directioncolor` to `-1073741569` (which is blue with opaqueness set to 192) or any other color in signed 32bit decimal format (which in Android is a 32 bit value, the leftmost bits for opaqueness, the other RGB).

**Comment by fm-sys** [comment]
Maby your PR will help, but can't test this as the backup database function seems to be broken at API level 21 too and I can't update to the Jenkins apk from some reason. So thanks for showing me the workaround!

**Comment by fm-sys** [comment]
> 
> 
> > I also tryed so but c:geo doesn't show the image: https://geokrety.org/konkret.php?id=81241
> 
> You have to open the gallery for this Kret and select it as Avatar. When done, it might take 30 minutes to show up (refresh in c:geo).

Deosn't work for me for some reason, but I think it doesn't matter. Nobody will look at this picture and say: "Ok, if it show no trackable images I will not download c:geo..."

**Comment by fm-sys** [comment]
![Folie1](https://user-images.githubusercontent.com/64581222/90389743-67cfc600-e08a-11ea-9007-1f5a25745d6d.PNG)
![Folie2](https://user-images.githubusercontent.com/64581222/90389754-6a322000-e08a-11ea-9331-147b3b7b30cc.PNG)

These are the final versions. If everything is fine (no misspellings, etc), I don't really want to make any more changes...

**Comment by Lineflyer** [comment]
Looks brilliant to me. Thank you for your efforts.

**Comment by eddiemuc** [comment]
Really great!

**Comment by fm-sys** [comment]
@Lineflyer Could you make a final check again, because once the pictures are disassembled into their individual pieces (quite time intensive) it is almost impossible to make changes anymore...

**Comment by moving-bits** [comment]
Really cool from graphics perspective, thanks!

I'm no expert in English, but some spellings look suspicious to me:
- graphic #1: "Made by geocachers" (should use a lower-case "g")
- graphic #2: "Multi platform" or "Multiplatform"? (I'm not sure)
- graphic #5: "Navigate to caches" (should use a lower-case "c")
- graphic #8: "Full support for trackables" (instead of "of")

**Comment by Lineflyer** [comment]
I will also take a final look tonight.

**Comment by Lineflyer** [comment]
Did take a final look:
- The tracking code looks strange to me. It is a GK tracking code but has a GC-TB logo in front of it. Did you mock this or do we have a bug in c:geo?
- Instead of "Suche Geocaches" I would use "Navigiere zu Geocaches" (because the first one more sounds like crawling the database of geocaches (e.g. keyword search) which does not match to the compass screen)
- "Unterstützung von Trackables" could also be "Volle Unterstützung von Trackables" but both are fine IMHO

Also the items mentioned by @moving-bits I do consider valid:
- "Made by geocachers"
- "Multi platform" should be correct
- "Navigate to caches"
- I would avoid for/of and use "Full trackable support"

Else, just really perfect :)

**Comment by Lineflyer** [comment]
@fm-sys 

Feel free to let your PR contain any additional data which might be useful for archiving (such as the original huge pictures or fonts (if allowed according to license)).

**Comment by fm-sys** [comment]
> The tracking code looks strange to me. It is a GK tracking code but has a GC-TB logo in front of it. Did you mock this or do we have a bug in c:geo?

Thats because I used the pictures from @eddiemuc and edited them. But I think not normal user will ever realize it ;-)

> "Unterstützung von Trackables" could also be "Volle Unterstützung von Trackables" but both are fine IMHO

The second is to long so I shortened it a bit.

So I will change the last few things and then create the Pull Request.

---

Thanks for all your positive feedback and for reviewing the images!!! Together we made c:geo a bit more modern... 👍

**Comment by fm-sys** [comment]
> 
> 
> > > I also tryed so but c:geo doesn't show the image: https://geokrety.org/konkret.php?id=81241
> > 
> > 
> > You have to open the gallery for this Kret and select it as Avatar. When done, it might take 30 minutes to show up (refresh in c:geo).
> 
> Deosn't work for me for some reason, but I think it doesn't matter. Nobody will look at this picture and say: "Ok, if it show no trackable images I will not download c:geo..."

24 hours later the avatar suddenly is applied... strange! So I will change this since I haven't finished the pictures anyway.

**Comment by Lineflyer** [comment]
Thanks @fm-sys 
Pictures have been taken to Google Play just now (might take some hours to be live) and posted to our Facebook page into an album (just for fun).
