### ISSUE TITLE
[Nightly] Change "Personal Note" popup to a (replacing) window

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8793]
**Is your feature request related to a problem?**
Since #8773 the Personal Note popup grows vertically, if you put more text into it. Great stuff, But although the additional editing space catapults working with PNs to a completely new level, the popup behaves weird in some scenarios:

1. while editing e. g. the first line and scrolling down until the selected line leaves the window, the cursor position will change to the *now* first line in sight (after scrolling). This sometimes makes it hard (or at lest annoying) to find the original editing position (i. e. prior to scrolling). Even more annoying: If you did not recognize the change of cursor position, just start to type ... the mess is ready. Thus would be *way* better, if the cursor position would just stay where it has been set manually, prior to scrolling.
2. while editing e. g. the last line on the first page of a multipage text, and then scroll up a few lines, the cursor will move down and then will show up *between the letters of the keyboard.* Looks pretty buggy, at least awkward.
3. when (keyboard still active) scrolling down more than a page (to be exact: until the cursor described in 2. crosses the lower border of the keyboard), the title row will move upwards, over the upper border of the display.
4. sometimes it's not possible to scroll anymore, as after some (not reproducible point) every swype action immediately selects text.

All these issues do not happen (AFAIK) in e. g. the log window. So: Would it be possible (with a reasonable amount of effort) to switch the Personal Notes popup to a (replacing) window, like the one for logs is?

This way perhaps we can even get additional space for buttons like ``Store waypoints`` or ``Store lists`` or whatever ...

**Comment by Lineflyer** [comment]
I also recognized the problem of the headline of the personal note going out of range while editing when a lot of text is involved.
Couldn't we keep the headline on screen and scroll the content?

**Comment by MagpieFourtyTwo** [comment]
Another problem which we stumbled upon this weekend: If the text is about a page long or even longer, and you've started to edit somewhere in the upper half of the page, it's pretty tricky to reach the last lines, cause these will now be covered by the keyboard.
Only chance: Close keyboard and select text somewhere at the end, but as soon as you go one lint to far up, the line below will be hidden and unreachable again. Or you grab the cursor (if it already shows the copy/paste indicator) and draw it down ... but eventually this immediately selects all the text ... high risk of loosing your note ... and - as far as I would say - nothing to give it to John Average ...

So, as there a too many problems, I would still suggest to forget about the popup and instead implement a dedicated window.

**Comment by fm-sys** [comment]
Mainly we have two bugs:
1. headline of the personal note going out of range while editing when a lot of text is involved
2. if started to edit somewhere in the upper half of the page, the last lines are covered by the keyboard

If we can fix these two bugs, i will vote to keep the popup, because it was already useful for me to have a look at the cache description while editing

**Comment by MagpieFourtyTwo** [comment]
> it was already useful for me to have a look at the cache description while editing

Don't see any difference compared to a replacing window, cause while editing the PN, the cache description is nearly completely covered by the popup anyway ... but that's possibly just because of my personal vision of "replacing window" , which I in fact have not really described, as I have to admit.

But first, if you're thinking of "temporarily close the popup to have a quick glance at the description", this is already now just possible by closing PN and a) scrolling up or b) using the menu entry ``Personal note``, thus even nowadays takes several clicks or scroll moves.

Nevertheless, I see your point and like to have this quick jump to the listing, too, and perhaps we are not that far away from each other anyway ... so, having this objective in mind I see at least two variants:

1. An entirely own page for the PN, like ``Logbook``, with editing like ``Log Visit``, which would give the advantage to be able to horizontally swype to the listing, thus being able to compare/lookup texts by always keeping scroll position in listing text *and* PN text, which would be a big advantage, esp with looong listings.

2. PN placement, buttons and stuff remain where they are right now, and just on click of ``Edit`` a replacing window opens up (instead of the current popup) - so it's pretty like a popup, but just using all the screen space, but behind the scenes it's in fact a window, which as a side effect would solve the scroll and edit problems of the current popup ...

I hope this may describe my idea more comprehensible ...?

**Comment by fm-sys** [comment]
Reading your comment a 3rd variant crossed my mind:

| always shown. A short swipe will open the second view, a long swipe to the top will open editing mode (3rd view). The PN would not be shown at the bottom of the listing anymore, because we have the 2nd view for this. | Compare both views. Scrolling should be possible at the top and the bottom of the screen for longer texts (this view is not available in the github app). Clicking on the text will open editing mode (3rd view). | Here you can edit the PN in a replacing window. PN will be autosafed when swiping to the second or first view. |
|-|-|-|
| ![Screenshot_20200819_144935_com github android](https://user-images.githubusercontent.com/64581222/90638356-89b57e00-e22d-11ea-9bdb-8ebd4634d5d0.jpg) | ![Screenshot_20200819_144902_com github android](https://user-images.githubusercontent.com/64581222/90638378-8f12c880-e22d-11ea-983e-caeaa069e0c7.jpg) | ![Screenshot_20200819_144916_com github android](https://user-images.githubusercontent.com/64581222/90638424-9934c700-e22d-11ea-9d19-26240c70c08b.jpg) |

What do you think?

**Comment by eddiemuc** [comment]
> Mainly we have two bugs:
> 
> 1. headline of the personal note going out of range while editing when a lot of text is involved
> 2. if started to edit somewhere in the upper half of the page, the last lines are covered by the keyboard
> 
> If we can fix these two bugs, i will vote to keep the popup, because it was already useful for me to have a look at the cache description while editing

PR #8843 provides a fix for those two problems, which might be enough for upcoming release? However, since this issue discusses much deeper extension of current note popup, it should probably stay open.

**Comment by MagpieFourtyTwo** [comment]
> What do you think?

I'm not sure if I really understood how it works, so please let me recapitulate:
1. at the bottom of the ``Description`` page there will be just a bar titled ``Personal note``
   (where I would suggest to add s/th like "swype up to open", if possible)
2. as soon as you swipe the bar up, the PN will appear in the lower half of the screen
    and in this mode both halves can be scrolled independently
3. as soon as you tap on the PN's text, the lower half will expand to whole screen
4. now you can edit the PN
5. to save and finish, you swipe up/down/left/right(?) or just use the back arrow

Additionally there's the "shortcut" with a long swype up in step 2, which will in fact skip step 3.

Assuming I've got this right. it in fact sounds not just good to me, but even like "Platin Version framed in diamonds".  ;)

**Comment by fm-sys** [comment]
The only problem is to find someone who has time and the will to implement this...

**Comment by MagpieFourtyTwo** [comment]
> The only problem is to find someone who has time and the will to implement this...

This was a pretty cold shower ... I silently/implicitly assumed you already have a (possibly even quick) solution in mind ...

**Comment by fm-sys** [comment]
Mabe I can work on it later, but I have some other issues in my backlog first. If someone other is interested, it would also be very welcome!
