### ISSUE TITLE
coordinate format of waypoint changed during scrolling

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8795]
**Describe the bug:**
Display format of a waypoint changed back during scrolling

**To Reproduce:**
Use a cache with log (e.g. 10) list of waypoints
Tap to the coordinates of a lower waypoint to change display format from dd mm.mm to dd.ddddd
Scroll up, so that the lower waypoint is pushed out at the bottom.
Scroll down again, so that the waypoint becomes visible again.

**Actual behavior/state after performing these steps:**
Depening how far out the waypoint was scrolled out, the format of the coordinates changes back to dd mm.mmm

**Expected behavior/state after performing these steps:**
changed format should not be changed by scrolling

**Version of c:geo used:**
2020.08.13-NB-a233cd3

**Is the problem reproducible:**
Yes

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**Comment by geocachermgo** [comment]
Is not there only at nighly. Same for 2020.08.04-legacy

**Comment by moving-bits** [comment]
IMHO this behavior is to be expected as XX XX.XXX is the default format c:geo uses (IIRC), and changing a format for display is only temporary. As soon as a displayed entry is scrolled away from the current screen, the entry gets recycled by Android, and the default format is used for displaying the next entry again.

So implementing this feature request would have to store the currently selected coord format and reuse it for every entry. Maybe even updating all entries currently shown. Not sure if I would like to have c:geo behave like this, but I'm open to discussion.

Any other opinions?

**Comment by MagpieFourtyTwo** [comment]
> changed format should not be changed by scrolling

Why not? As for me: I (have to) use the coord tap to change the output format too, but just when navigating to a cache with the built-in car navi, cause this one only knows "DD MM SS" - and I'm glad that c:geo switches back to "DD MM.MMM" afterwards, cause this is the format we're working with most of the time.

So, most interesting question to me is, why should the coord format be different at all, why probably just the format of *one* WP, and why should this even be permanent?

**Comment by geocachermgo** [comment]
I still see it as a bug: Scrolling should not change anything but only shift the display. To the question "why" of @MagpieFourtyTwo :  If users changed the display, they have done this because they want it to be displayed differently. So cgeo should keep it.
I do not think that a change is urgently neccessary.
As a feature I would not support it. The reason I raised this issue is that i think that they way it works now is not a straight and clear behaviour.

**Comment by eddiemuc** [comment]
I would differentiate as follows:
* As long as I stay on the waypoint list screen, when I change display format for single waypoints then simply scrolling the list up and down should keep that format. If this is not happening I would consider it a bug
* If I leave the waypoint list however and then come back (e.g. swiping right to Cache details and then go back again) then I would consider it ok that coordinate format resets (changing this behaviour would be a Feature request)

**Comment by geocachermgo** [comment]
First dit is what is happening: as long as the line (orange dot) stays on the screen the changed format stays. If the line is scolled out the the format changes.
![IMG_20200816_131430](https://user-images.githubusercontent.com/43813636/90333104-21636400-dfc3-11ea-8c34-0b3e8197667c.jpg)
![IMG_20200816_131522](https://user-images.githubusercontent.com/43813636/90333106-288a7200-dfc3-11ea-94a7-c745cb66ccf6.jpg)

**Comment by geocachermgo** [comment]
Works with 2020.08.19-NB-e1750ec, even with leaving the waypoint page. Reset if cache is reloaded. Thanks.
