### ISSUE TITLE
[Nightly] Make display of "+ OfflineLogs" configurable

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8796]
**Is your feature request related to a problem?**
On start page there is this new addition to the number of caches found, represented as "FoundCount + OfflineLogCount" - which may be helpful, if you want to be reminded of what is still open to do (although I have a list called "Offline Logs" which does this job perfectly fine already).

But OTOH this counter can produce a lot of stress to users, who do not want to be reminded of an open task, which they do not really like at all. Reasons may be e. g. orthographic problems, shyness, or whatever.

Point is: These guys have massive problems with logging anyway, and they try to focus on being outside and they do everything to forget about this task, which makes caching really hard for them sometimes - and in some cases ending up in giving up caching at all.

These guys for sure do not need an app that reminds them of this stressy task on every single start.

(And, yes, these really exist, as I can say from personal experience)

**Describe the solution you'd like**
Add an option to suppress display of OfflineLogsCount

**Comment by Lineflyer** [comment]
IMHO those people could just stop doing offline logs if they anyhow dont plan to log online.

OTOH isnt it even better to show the correct find count releasing the pressure to log online?
If you have 0 finds but know you found 50, you before had (0) but now have (0 + 50). So no need to do anything.

**Comment by MagpieFourtyTwo** [comment]
Please, just believe me.
As I'm not guessing nor wildly assuming, but in fact experiencing it in real life.
You have absolutely no clue, how immense the impact of such a number can be to the psyche of someone, who is fighting such problems anyway.
So, please, *please*, *PLEASE* make it configurable.
Moreover, with a configurable option like this, you can leave the decision regarding your of course highly appreciated thoughts to the one, who is really affected by it's effects.
And, to be honest, *they* are the only ones, who can really assess these effects. But you and me, we can't make this decision - and (as far as I would say) we should not even try to make it for them ...

**Comment by Lineflyer** [comment]
If the contributor wants to implement to enable optionally turn it off, I have no problem with that.
I just would like to suggest to enable this by default.

Still I dont get the difference between offline and online logging when it comes to psychological reasoning. No one hinders you to just find caches and simply dont log them at all. So why applying stress by initially logging them offline thus generating stress and demand to log them online.
I also know some cachers, who just sign the logbook and thats it.

**Comment by geocachermgo** [comment]
Difference: Logging online is interacting with others.
I have a +4 display. How do I filter to find this 4 caches?

**Comment by fm-sys** [comment]
> I have a +4 display. How do I filter to find this 4 caches?




Go to history list and filter for "With personal data => With offline log"




Mit freundlichen Grüßen


Florian Meyer 







On Fri, Aug 14, 2020 at 9:50 AM +0200, "geocachermgo" <notifications@github.com> wrote:















Difference: Logging online is interacting with others.

I have a +4 display. How do I filter to find this 4 caches?

**Comment by fm-sys** [comment]
> I have a +4 display. How do I filter to find this 4 caches?




Go to history list and filter for "With personal data => With offline log"

**Comment by geocachermgo** [comment]
Thanks

**Comment by fm-sys** [comment]
> These guys have massive problems with logging anyway [...] So, please, please, PLEASE make it configurable.

@MagpieFourtyTwo Wouldn't it then be the best to hide both counters, online & offline?

**Comment by MagpieFourtyTwo** [comment]
Seeing already done (achieved) stuff helps a lot.
So for this "problem" would be better to see them.
Problem is just the pressure from not yet done stuff.
It's like visiting dentists, for others: You really *want* to, but the barrier to cross is pretty high for some people. And even if they finally have an appointment, they do not want to be reminded of it every day till then ... but seeing the number of already done visits even helps, as this shows, they survived these, so the upcoming one is probably not so hard, too ... ;)

**Comment by MagpieFourtyTwo** [comment]
> Still I dont get the difference between offline and online logging when it comes to psychological reasoning. No one hinders you to just find caches and simply dont log them at all. So why applying stress by initially logging them offline thus generating stress and demand to log them online.

Ok, did not want to go that deep, but as you asked for it, here's some background (at least as far as I have understood - I'm not a psychologist): They in fact *want* to log, cause this makes the experience complete. Especially when you liked a cache, you of course want to say thanks and stuff, to give a little bit back - and so do they want to do as well. But then there are these deficits ... so they always struggle to overcome them ... and in "good phases" they can build up enough self-confidence to write ... but in "not so strong phases", they just feel the pressure, when they are reminded ...

As for me, I can not judge, how bad the feelings are for real and what this pressure does to them, but I have seen the look in his eyes, when he got aware of this Offline Logs Counter ... and it was close to panic. So for these guys this is obviously a problem. Which we can probably not understand - but we can help to make their (cacher) life a little bit easier. :)

**Comment by fm-sys** [comment]
I will implement this when I have time...

**Comment by MagpieFourtyTwo** [comment]
Thx!

**Comment by fm-sys** [comment]
Could someone close this issue (or give me the permission so that I could close issues as well, because I noticed that there are some more outdated issues that are already fixed or outdated)

**Comment by Lineflyer** [comment]
It should get autoclosed once the PR has been merged (if you used the keyword fix #1234)

**Comment by bekuno** [comment]
@fm-sys 
Details for auto-close are here:
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by fm-sys** [comment]
yeah, I did that with my previous PR's as well but this time I had added the fixes-part to the title of the commit what doesn't seem to work...
