### ISSUE TITLE
Replace functional graphic

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8804]
On:
- [x] Google Play

- [x] Facebook

- [x] Support Ticket System

@fm-sys Did you see my question regarding c:geo Fangruppe in your PR?

- [ ] Fangruppe (Hand over to moderator)

**Comment by fm-sys** [comment]
> Did you see my question regarding c:geo Fangruppe in your PR?

No, I missed that. You could use this one:

![2020-08-15 13_33_12-PowerPoint-Bildschirmpräsentation  -  c;geo playstore images - functional graphi](https://user-images.githubusercontent.com/64581222/90311556-4c36b500-defc-11ea-8022-fa9f994c9e8a.png)

**Comment by Lineflyer** [comment]
Thanks, forwarded that one.

And for the other spots: All updated.

@fm-sys Thanks again!

**Comment by fm-sys** [comment]
@Lineflyer the functional graphic needs to be updated also on Twitter...

**Comment by Lineflyer** [comment]
@fm-sys Thanks for the hint. Done!
