### ISSUE TITLE
Map file downloads fails if maps dir not writeable

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8821]
**Describe the bug:**
Map download fails with message "Receive map file - Error while receiving map file". I in fact tried this several times, even some time ago, but was always unsuccessful. Just forgot to report as I'm using different sources anyway.

**To Reproduce**
1. Go to map view
2. Open map list
3. Tap "Download offline map"
4. Select one (over here: Europe => Germany => Baden-Wuerttemberg)
5. Download starts and seems to finish
6. Error message appears

**Version of c:geo used:**
 2020.08.17-NB-2c47d82

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.1.0.140(C431E19R2P5)
c:geo version: 2020.08.17-NB-2c47d82
Google Play services: disabled - 20.30.19 (120400-326531024)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: visited
HW acceleration: enabled (default state)
System language: en_DE
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (76,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (76,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (76,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (284,1 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Additional context:**
As the download seems to work (progress bar in notification bar comes completely to it's end), I would guess there maybe either an unzip or storage (access) problem. Question: Where will c:geo put it's map files?

Already generated a log file, internal and with Logcat reader, but there are no errors in it, and even extended log with Debug Log active just contains two entries for mapdownloader, with get token and release token. In Logcat reader I additionally found these entries (while filtering for "mapdownload"):

```
[08-17 14:21:20.319 2103:2442 E/DollieAdapterService]
notifyActivityState pkg:cgeo.geocaching/cgeo.geocaching.settings.MapDownloadSelectorActivity state:2 fg:true mUid:10313

[08-17 14:21:20.423 760:1465 W/BufferQueueProducer]
[cgeo.geocaching/cgeo.geocaching.settings.MapDownloadSelectorActivity#0]:1368: disconnect: not connected (req=1)

[08-17 14:21:20.428 1279:2157 E/InputDispatcher]
Window handle Window{ab00288 u0 cgeo.geocaching/cgeo.geocaching.settings.MapDownloadSelectorActivity} has no registered input channel

[08-17 14:21:20.432 1279:1306 E/WindowManager]
win=Window{ab00288 u0 cgeo.geocaching/cgeo.geocaching.settings.MapDownloadSelectorActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
```

Any idea how I should create a more informative debug log?

**Comment by moving-bits** [comment]
IIRC that can happen if the download manager notifies c:geo with an unknown download ID or unknown state, but I'll look into it.

Downloading and receiving map files work in several steps:
- selecting a file and triggering the download
- downloading in background using the system's download manager; file is stored in your download manager's default dir (typically `/Downloads`)
- when download has finished c:geo gets notified of this and copies the file to c:geo's map dir (which typically is `/cgeo/map`, or, written as full path in your case `/storage/emulated/0/cgeo/map`, see `User storage c:geo dir` in your system info above)
- when moving the map file has been completed, the new map file gets set as default map file

**Comment by MagpieFourtyTwo** [comment]
Yep - that's how I expected it to work. Apart from the target dir ... as I (of course) already configured a map file directory (/storage/0123-4567/Locus/mapsVector) ... so, will ``/cgeo/map`` *additionally* be scanned for map files or how does this work out?

BTW: Neither the downloaded map file nor the directory ``/cgeo/map`` exist at all, although I would have expected that the .zip file will still be there and that at least the target dir has already been created (that's what I would have done, prior to downloading, to check in advance, if the destination is writable) ...

**Comment by fm-sys** [comment]
> as I (of course) already configured a map file directory (/storage/0123-4567/Locus/mapsVector) ... so, will /cgeo/map additionally be scanned for map files or how does this work out? 

If you have defined an other map file directory, the maps should be safed there

**Comment by moving-bits** [comment]
> Yep - that's how I expected it to work. Apart from the target dir ... as I (of course) already configured a map file directory (/storage/0123-4567/Locus/mapsVector) ... so, will `/cgeo/map` _additionally_ be scanned for map files or how does this work out?

My description was a bit short-cut: `ReceiveMapFileActivity` is using `Settings.getMapFileDirectory()` (which is the map file dir currently set) and only defaults to `LocalStorage.getDefaultMapDirectory()` (the dir described above) if necessary.

**Comment by moving-bits** [comment]
From a short view into the source I say it happens somewhere in step three:

> * selecting a file and triggering the download
> * downloading in background using the system's download manager; file is stored in your download manager's default dir (typically `/Downloads`)
> * when download has finished c:geo gets notified of this and copies the file to c:geo's map dir (which typically is `/cgeo/map`, or, written as full path in your case `/storage/emulated/0/cgeo/map`, see `User storage c:geo dir` in your system info above)
> * when moving the map file has been completed, the new map file gets set as default map file

as the error message you've described fires only in step three, and only if you don't cancel moving the file. This error is a signal that one of the two following exceptions have occurred: `IOException` or `FileNotFoundException`.

Does a black window with "Receving map file" appear (even shortly) after downloading has finished? This would be a visual sign for the download. Related activity (if there's something in the log) would be `ReceiveMapFileActivity`.

I can create you a debug version with a bit more logging to try to tackle this error.

**Comment by moving-bits** [comment]
> I can create you a debug version with a bit more logging to try to tackle this error.

See the APK that will be generated with #8824.

**Comment by MagpieFourtyTwo** [comment]
> Does a black window with "Receving map file" appear (even shortly) after downloading has finished?

Nop. After clicking the diskette icon of the selected map file a toast appears ``Downloadng started in background``.
And immediately after download has finished, the black popup ``Receive map file - Error while receiving map file`` appears.
*If* there is another popup, it may immediately be overlayed/replaced by the described one.

> This would be a visual sign for the download. Related activity (if there's something in the log) would be ReceiveMapFileActivity.

Although there is no popup, there seems to be some activity ... foll. LogCat filtered by "receivemapfileactivity":
[logcat_08-17-2020_19-34-51.txt](https://github.com/cgeo/cgeo/files/5085935/logcat_08-17-2020_19-34-51.txt)

> See the APK that will be generated with #8824.

How do I get this apk? Could not find it ...

**Comment by fm-sys** [comment]
> How do I get this apk? Could not find it ...

View the site of the PR in desktop version (if youre on mobile) and follow the link to the test cases... Or use this one: https://ci.cgeo.org/job/cgeo%20pull%20request/3388/

**Comment by MagpieFourtyTwo** [comment]
Hmm, can't find the test cases ... but got it via your direct link - thx!
Will nevertheless take a bit, as I obviously have to uninstall c:geo first to be able to install the cgeo-debug.apk ...  :/

**Comment by Lineflyer** [comment]
Did not yet read all today comments but my guess:

If @MagpieFourtyTwo has defined a folder on SD c:geo will most probably not be able to write something there. Or does the download manager do this for us?

**Comment by moving-bits** [comment]
> Hmm, can't find the test cases ... but got it via your direct link - thx!

It's a bit hidden: Click on "Show all checks"...

![image](https://user-images.githubusercontent.com/3754370/90432743-388d7900-e0cb-11ea-83f0-bc1878d46c24.png)

... and then on "Details" link of the "default - build finished" line:

![image](https://user-images.githubusercontent.com/3754370/90432929-54911a80-e0cb-11ea-937f-e0db1e204631.png)

which is the link @fm-sys had posted. There you can download the APK from the "cgeo-debug.apk" link:

![image](https://user-images.githubusercontent.com/3754370/90433115-9d48d380-e0cb-11ea-8aa2-c39c89dbe548.png)

> Will nevertheless take a bit, as I obviously have to uninstall c:geo first to be able to install the cgeo-debug.apk ... :/

I can merge the version with the additional debug info to master, then it would be included in the nightly version.

**Comment by moving-bits** [comment]
> Did not yet read all today comments but my guess:
> If @MagpieFourtyTwo has defined a folder on SD c:geo will most probably not be able to write something there. Or does the download manager do this for us?

I'm using the currently set map folder, or use default map folder as fallback. First step is to check if this folder is writable. Then I'm copying (not moving) the file - which should work for SD card as well.

**Comment by moving-bits** [comment]
> Or does the download manager do this for us?

Sadly: no, due to missing access rights. That's one of the reasons why I download first, and then let c:geo copy the file to its map folder.

**Comment by Lineflyer** [comment]
> Sadly: no, due to missing access rights. That's one of the reasons why I download first, and then let c:geo copy the file to its map folder.

So, we found the reason as @MagpieFourtyTwo stated somewhere above, that he set up a folder on his SD.
In that case we should (if possible) detect this non-writeable destination and inform the user, that he has to copy/move the file himself as c:geo can only read from this folder but not write into it and tell him where to find the file.

**Comment by moving-bits** [comment]
> > Sadly: no, due to missing access rights. That's one of the reasons why I download first, and then let c:geo copy the file to its map folder.
> 
> So, we found the reason as @MagpieFourtyTwo stated somewhere above, that he set up a folder on his SD.
> In that case we should (if possible) detect this non-writeable destination and inform the user, that he has to copy/move the file himself as c:geo can only read from this folder but not write into it and tell him where to find the file.

The folder the download manager uses should be write-accessible to the download manager.
The map folder for c:geo may be on SD card, but as we use the current map folder from c:geo, this should be write-accessible as well (in most cases at least; and on Android < 11 only).

Which is no reason not to present an correct error message if a write error occurs... => Will put that on my list.

**Comment by MagpieFourtyTwo** [comment]
> That's one of the reasons why I download first, and then let c:geo copy the file to its map folder.

But when you're just copying - why is there no map file in /download ...?
Or do you delete it, not matter if copy was successful or not?

**Comment by moving-bits** [comment]
> > That's one of the reasons why I download first, and then let c:geo copy the file to its map folder.
> 
> But when you're just copying - why is there no map file in /download ...?

That's one of the mysteries of Android download manager: Downloads started programmatically from within an app do not seem to be listed in the download dir, although they exist. They can only be retrieved using the internal ID given by the download manager on triggering the download.

> Or do you delete it, not matter if copy was successful or not?

No, neither nor, that's done automatically by the download manager - sort of a "garbage collection" to free disk space.

**Comment by MagpieFourtyTwo** [comment]
> See the APK that will be generated with #8824.

BTW: Which API version is this built with, i. e. will database restore will still work (#8819)?

**Comment by moving-bits** [comment]
> > See the APK that will be generated with #8824.
> 
> BTW: Which API version is this built with, i. e. will database backup/restore work (#8819)?

API versions (targetSDK and compileSDK) are always 29 (Android 10), but the error seems to occur on devices running on API level 21 (Android 5.0) only. (At least we do not have any other reports except for Android 5.0)

**Comment by Lineflyer** [comment]
I think @MagpieFourtyTwo means, the DB version not the API version.
The DB version of the developer build in a PR usually equals the DB version on master, which usually equals the DB version of nightlies. Exception of course if the PR itself contains a DB upgrade or the DB got upgraded on master after the PR has been build.

**Comment by fm-sys** [comment]
> Exception of course if the PR itself contains a DB upgrade or the DB got upgraded on master after the PR has been build.

This should currently not be the case...

**Comment by MagpieFourtyTwo** [comment]
Bingo ...
```
[...]
08-17 22:06:19.865 10594 10746 D cgeo    : [AsyncTask #1] start receiving map file: /storage/0123-4567/Locus/mapsVector/baden-wuerttemberg.map
08-17 22:06:19.867 10594 10594 I DecorView[]:  old windowMode:0 new windoMode:1
08-17 22:06:19.868 10594 10594 D ActivityThread: add activity client record, r= ActivityRecord{a1f3a37 token=android.os.BinderProxy@6e5056f {cgeo.geocaching/cgeo.geocaching.settings.ReceiveMapFileActivity}} token= android.os.BinderProxy@6e5056f
08-17 22:06:19.872 10594 10746 E cgeo    : [AsyncTask #1] IOException on receiving map file: /storage/0123-4567/Locus/mapsVector/baden-wuerttemberg.map: open failed: EACCES (Permission denied)
08-17 22:06:19.874 10594 10746 I QarthLog: [PatchStore] createDisableExceptionQarthFile
08-17 22:06:19.874 10594 10746 I QarthLog: [PatchStore] create disable file for cgeo.geocaching uid is 10320
08-17 22:06:19.875 10594 10594 I ToolbarWidgetWrapper: Progress display unsupported
--------- beginning of crash
[...]
```
[logcat_2020-08-17_22-06.txt](https://github.com/cgeo/cgeo/files/5086554/logcat_2020-08-17_22-06.txt)

**Comment by MagpieFourtyTwo** [comment]
BTW, if add. data is needed: I have already uninstalled the debug version - was not able to use Google Sat view anymore (got just a grey page). Guess Leak and Debug was more than my poor little P30Pro could cope with ...  :/

;)

**Comment by Lineflyer** [comment]
>  was not able to use Google Sat view anymore (got just a grey page).

The reason is, that the debug version does not use our Google maps key (due to security reasons), thus they are not available.
So, this is normal.

**Comment by MagpieFourtyTwo** [comment]
Ah, ok, glad to hear I won't have to look for a more powerful SP after all ...  ;)
