### ISSUE TITLE
Replace icon of "GPS Status and Toolbox" in useful apps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8829]
It meanwhile has an updated icon:
https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus

**Comment by moving-bits** [comment]
Are you sure you're talking about GPS Status program? Looks identical to me:

![image](https://user-images.githubusercontent.com/3754370/90563614-6b577000-e1a4-11ea-8c65-44d576b608dc.png)

**Comment by Lineflyer** [comment]
You are looking a plugin, the main app has this:
![grafik](https://user-images.githubusercontent.com/949669/90565891-de161a80-e1a7-11ea-8c44-4cb3b1f91ffe.png)

**Comment by moving-bits** [comment]
I'd just followed the link provided...

Ok, I'll look into it.

**Comment by Lomanic** [comment]
You linked to the plugin
 Here's the app https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2
