### ISSUE TITLE
Track end point gets connected to start point

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8831]
AFAICS the linked GPX track file ends some kilometers away from its start.
It shows up like that when viewed in an online viewer or in Locus.

In c:geo however the end gets connected to the start with a straight line.
Is this a bug?

https://www.dropbox.com/s/04ye4qfg0lri5sd/Hide%26Bike%2011.%20Rund%20um%20Bochum.gpx?dl=0

**Comment by moving-bits** [comment]
The trackfile you've linked to consists of two track segments (`<trkseg>`), the second only containing a point pretty close to the starting point of the first segment. As c:geo reads all segments, the circuit gets (nearly) closed.

beginning of track and first segment:
![image](https://user-images.githubusercontent.com/3754370/90565113-a6f33980-e1a6-11ea-9a3c-cfe89f4d9599.png)

end of first segment / complete second segment and end of file:
![image](https://user-images.githubusercontent.com/3754370/90565200-ce4a0680-e1a6-11ea-8d07-bea7561c450d.png)

**Comment by Lineflyer** [comment]
OK...so its a "problem" of the track file.
