### ISSUE TITLE
[individuell route] Better UI implementation of sorting way points 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8836]
The current UI is not really User friendly, so i whould surgest that Sorting individual route should use an UI that looks similar to this:

![Screenshot_20200818_081908](https://user-images.githubusercontent.com/64581222/90477386-9a7dcb00-e12b-11ea-8264-3acd8085786b.jpg)
I think the behavior should be clear so far. Click and hold one of the symbols on the right side to drag its waypoint to a new position...

**Comment by moving-bits** [comment]
AFAIK there is no built-in drag & drop functionality available in Android, at least I haven't found any, so we would need to look for some library for it.

**Comment by fm-sys** [comment]
I found this one: 
https://github.com/bauerca/drag-sort-listview

Also it looks like this also could be done just with android support libraries using the ItemTouchHelper:
See https://github.com/iPaulPro/Android-ItemTouchHelper-Demo 


Both is licensed under the Apache License, Version 2.0

**Comment by moving-bits** [comment]
@fm-sys 
Thanks for the research. Do you have time to prepare a PR for this?

**Comment by fm-sys** [comment]
I will try. But I'm not sure if I will manage it... Also do we want to re-enable the swipe gesture for deleting waypoints using this library?

**Comment by moving-bits** [comment]
> I will try. But I'm not sure if I will manage it... 

Thanks

> Also do we want to re-enable the swipe gesture for deleting waypoints using this library?

That would be nice, and it will make some users happy, but let's start with sort by drag & drop, as this is the more urgent issue, IMHO.

**Comment by fm-sys** [comment]
![Screenshot_20200825_075045](https://user-images.githubusercontent.com/64581222/91128110-dd015380-e6a7-11ea-95fc-511082ca7b66.png)
Finished! The delete option is implemented as a button first...
