### ISSUE TITLE
remove PlayStore description from Wiki

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8839]
After migration the PlayStore information to crowdin the wiki entries are no more necessary:
https://github.com/cgeo/cgeo/wiki/App-description-for-PlayStore
https://github.com/cgeo/cgeo/wiki/Contacts-Plugin-description-for-PlayStore
https://github.com/cgeo/cgeo/wiki/Calendar-Plugin-description-for-PlayStore-(obsolete)

**Comment by bekuno** [comment]
And then we need an update to the main document.

**Comment by Lineflyer** [comment]
Will do

**Comment by Lineflyer** [comment]
Done
