### ISSUE TITLE
import GPX, identify cgeo

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8844]
If I open a .gpx file, I get 4 cgeo options to chose with the same icon.

Is it possible to make them different and mark the right one?
![Screenshot_2020-08-19-18-50-09-256_android](https://user-images.githubusercontent.com/43813636/90667871-74e9e200-e24f-11ea-81fc-498b184dbee8.jpg)

Is there a way to open a gpx file from cgeo?

**Comment by Lineflyer** [comment]
Can you please report the version of c:geo and the device details/version?

**Comment by moving-bits** [comment]
Additionally: Can you describe how you try to open a gpx file? (Which program are you using for that action?) Thanks.

**Comment by geocachermgo** [comment]
Version: 2020.08.19-NB-e1750ec
Sequence: Show Cache Page with Firefox, Chose "Download GPX". Then there is a display on bottom of the screen:  downloaded, open. If I click "Öffnen" then I get the first screenshot.
![Screenshot_2020-08-19-22-59-48-452_org mozilla firefox](https://user-images.githubusercontent.com/43813636/90689168-e46fc980-e26f-11ea-83c5-23e3fcb9b4cc.jpg)


--- System information ---
Device: MI 8 (dipper, Xiaomi)
Android version: 10
Android build: QKQ1.190828.002 test-keys
c:geo version: 2020.08.19-NB-e1750ec
Google Play services: disabled - 20.26.14 (120400-320008519)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (90,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (90,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (90,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (10,8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

**Comment by Lineflyer** [comment]
Just tried with Samsung S10, Android 10 but with Chrome. For me it does not even offer c:geo just other apps like Locus, Relive, Komoot. Strange...

**Comment by geocachermgo** [comment]
the bahn Navigator has also several option but most of them have distinctive names:
See page 2 of app that can be used to open the gox files.
![Screenshot_2020-08-20-07-20-40-839_android](https://user-images.githubusercontent.com/43813636/90720028-13109300-e2b6-11ea-9dbd-85d893d0c0c0.jpg)

Any ideas how to open a gpx file from cgeo menu?

**Comment by geocachermgo** [comment]
AFAICS its not really related to c:geo and there is the workaround to directly import gpx files from the menu in a list view. So I close this issue.
