### ISSUE TITLE
Check coordinate parsing for the format used by Locus Map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8845]
Taken from a discussion in https://github.com/cgeo/cgeo/pull/8597#issuecomment-676570462 an follow-up article by @baiti:

>> We now forbid all special characters of the coordinates to occur between the coordinate parts.

> This is not good. The waypoint dialog's coorindate entry pull down provides a function to take coordinates from the clipboard. A very popular application that can put coordinates into the clipboard is Locus Map, however, Locus Map uses the format:
>
> Nxx° yy.zzz', Exx° yy.zzz'
> 
> This format was parsed by c'geo correctly until the referenced change was made. Now since the colon between Lat / Lon part makes the parser  reject these coordinates, the effect is that the menu entry "Use coords from clipboard" is not even displayed anymore.
>
> This change breaks coordinate parsing when coordinates come from Locus Map via the clipboard. Please backout this change. Coordinates in the form of "Nxx° yy.zzz', Exx° yy.zzz'" should be parsed corrextly as valid coordinates. The only other option I see is to convince the Locus Map folks to remove that colon as it is "ugly" in the first place and doesn't really make sense, however, as a matter of fact, that colon happens to be there since a very long time and c'geo was indeed able to process it correctly

**Comment by Lineflyer** [comment]
That matches some user feedback after recent release. We should revert that at least when it comes from clipboard but better even for personal note parsing.

**Comment by geocachermgo** [comment]
I support this request.
