### ISSUE TITLE
Recommend app: pocket query generator

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8847]
Since a while the pocket query generator is not usable since the log-on is not working any more (Android 10 only?). Last update was 2018. If this is persistent, it should be removed form the "Recommend App" list in cgeo.

**Comment by Lineflyer** [comment]
Works flawless for me on Android 10.

**Comment by Lineflyer** [comment]
Please report to https://github.com/robneild/pocket-query-creator if you keep having problems.
But for me it logs in, syncs my existing PQ and is able to generate a new one.

**Comment by geocachermgo** [comment]
I wrote a mail. There are comments in the Playstore that some other persons have the same issue, so I was aasuming its a general problem.

**Comment by geocachermgo** [comment]
Deinstalled and installed the same (2018) version, is now working.
