### ISSUE TITLE
Find count on home screen not updated

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8863]
Using 2020.08.22-NB:

- Started c:geo with 6350 finds
- Cached during the day and saved log offline (not sure if it depends on that)
- Logged all 10 offline finds with c:geo in the evening
- Refreshed one of the logged caches and the  logbook shows my correct find count (left below the user name) with 6360 finds

- The homescreen still shows 6350 finds however. It seems the counter is no longer updated when logging finds online with c:geo

**Comment by Lomanic** [comment]
This could be reopened, the proper number is shown on the personal profile at https://www.geocaching.com/p/default.aspx while the number in the upper right corner next in the green bar menu lags behind, quite a lot.

**Comment by Lineflyer** [comment]
But it is still a (hopefully temporary) bug on the website. I dont think we should work around from our side.

**Comment by Lomanic** [comment]
Looks like a fix was recently deployed today in fact https://forums.geocaching.com/GC/index.php?/topic/357996-bug-inconsistency-between-number-of-finds/#comment-5850195

**Comment by Lineflyer** [comment]
Thanks for this info.
Seems I need to watch that forum.

**Comment by Lomanic** [comment]
I could confirm that this is indeed fixed.
