### ISSUE TITLE
[Nightly] copy coordinates of waypoint

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8870]
**Describe the bug:**
If the coordinates of a waypoint are copied to the clipboard , the content is independend of a changed display (tap toogles dd mm.mmm, dd mm ss, dd.dddd, UTM)

**To Reproduce:**
1. Go to waypoint page
2. Tap on coordinates to change format
3. Log Click on waypoint, chose copy coordinates
4. Paste to check content of clipboard

**Actual behavior/state after performing these steps:**
The copied waypoint is always in dd mm.mmm format

**Expected behavior/state after performing these steps:**
In the clipboard the coordinates should be in the displayed format. This was the case in earlier versions

**Version of c:geo used:**
2020.08.23-NB-213c70b

**Is the problem reproducible:**
Yes

**Comment by eddiemuc** [comment]
I can confirm the described behaviour. But the same happens also with my regular installed version of c:geo from play store. Can't tell how it was in earlier versions though. I also checked the current code and the described behaviour is coded there very explicitly, I can't imagine that someone accidentally changed something here.

However, I think this would be a nice feature, and also one maybe suitable for new developers. Thus I suggest assignment of "Good first issue" label

**Comment by Lineflyer** [comment]
IMHO it was like that ever since, so more a feature request instead of a bug.

**Comment by geocachermgo** [comment]
I'm very sure it worked the way I proposed with one of the previous nightly builds. I tested it with an old release version: There also dd mm.mmm is at the clipboard.

**Comment by geocachermgo** [comment]
I just saw  #6711. Maybe I copied successfully the toogled coordinates of a cache and not a waypoint.
So this can be closed since it is a duplicate to the 2017 request?

**Comment by Lineflyer** [comment]
Yes, you are right.
