### ISSUE TITLE
Bug in wording of changelog

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#8871]
**Describe the bug:**
It reads "Option to globally deactive waypoint extraction from personal notes"

Should read "Option to globally deactivate waypoint extraction from personal notes"

I will use this issue to learn the process, so I am trying to fix it, do a push, and open a pull request under this issue, hope it works as I think it might

**Comment by baiti** [comment]
Actually, while at the subject: I noticed that throughout c'geo, the entity in question is called "Personal Note" oder "Personal Notes". On the entity we sometimes refered to as "The Platform" (aka geocaching.com), it is called "Personal Cache Note". Do we want to coin and use our own terms? Or better stick with what "The Platform" uses?

**Comment by moving-bits** [comment]
Fixed with #8872
