### ISSUE TITLE
reintegrate contacts plugin into main app

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8877]
The contact plugin has a working permissions management, also perfect at runtime.
It should work in the same way as direct integrated function in c:geo compared to the current situation c:geo plus contacts addon.
No need anymore for the external solution.

see also #7193

**Comment by Lineflyer** [comment]
indeed.

**Comment by bekuno** [comment]
We have to wait until the project sets
        `minSdkVersion 23`
This is Android 6. 
Starting with this release the new app permissions control is possible.

**Comment by bekuno** [comment]
@moving-bits 
Can you update the API matrix (https://github.com/cgeo/cgeo/wiki/Playstore-statistics)?

**Comment by bekuno** [comment]
Lets close here in favor of https://github.com/cgeo/cgeo/issues/13777.

**Comment by moving-bits** [comment]
> @moving-bits Can you update the API matrix ([cgeo/cgeo/wiki/Playstore-statistics](https://github.com/cgeo/cgeo/wiki/Playstore-statistics))?

done

**Comment by eddiemuc** [comment]
> > @moving-bits Can you update the API matrix ([cgeo/cgeo/wiki/Playstore-statistics](https://github.com/cgeo/cgeo/wiki/Playstore-statistics))?
> 
> done

Thanks a lot! According to these stats we are takling about 0,5% of users with SDK 21 or 22
