### ISSUE TITLE
Test Traditional Chinese in contacts plugin

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8878]
As discussed in #8875:

- Approve strings for contacts in chinese traditional
- Merge to repo and enable the language
- Either release the plugin version (planned anyway) or provide test apk to translator to check if its shown in that language

- Set translator(s) as proofreader

**Comment by Lineflyer** [comment]
I have set the existing translations as proofreaded in a first step.

Secondly I will contact a chinese friend and ask for translation of the screenshots provided by @bekuno in #8875.

**Comment by Lineflyer** [comment]
@bekuno 

Here we go, that should enable you to select the correct language:

![grafik](https://user-images.githubusercontent.com/949669/91166166-37afa500-e6d2-11ea-9838-cd831ca4cb6c.png)


![grafik](https://user-images.githubusercontent.com/949669/91166197-45652a80-e6d2-11ea-950f-9d99131eac06.png)

**Comment by moving-bits** [comment]
> Here we go, that should enable you to select the correct language:

Thanks for the images. If I interpret the docs correctly, zh-rTW is Chinese traditional. Do you have the translations for their sub-regions as well? (See the last image in https://github.com/cgeo/cgeo/pull/8875#issuecomment-679320657)

(Adding some string to the strings.xml file in zh-rTW dir did not show up when setting system language to Chinese traditional and selecting one of the locales. Will try contacts plugin next.)

**Comment by bekuno** [comment]
> Thanks for the images. If I interpret the docs correctly, zh-rTW is Chinese traditional. Do you have the translations for their sub-regions as well? (See the last image in [#8875 (comment)](https://github.com/cgeo/cgeo/pull/8875#issuecomment-679320657))

Yes, zh-rTW is Chinese traditional. This is mainly spoken in Taiwan.
In China the Chinese simplified is the main (central) language (as far as I know).
I can select "all regions" as sub region for zh-rTW.
Interesting: open the addin (search user) - change the language - right after save the addin is shown in the new language.
![20200826_224308](https://user-images.githubusercontent.com/32555742/91354851-9e75b100-e7ed-11ea-9953-2b320385f3cb.jpg)

**Comment by moving-bits** [comment]
> I can select "all regions" as sub region for zh-rTW.

Maybe I could, too - but as I get shown only Chinese signs, I don't know which entry is what... :-(

**Comment by bekuno** [comment]
![Screenshot_20200826-225812_Settings](https://user-images.githubusercontent.com/32555742/91356341-cbc35e80-e7ef-11ea-8a91-e862085396fb.jpg)

**Comment by moving-bits** [comment]
@bekuno 
Thanks. Don't have the sub-headings here. But thanks to your screenshot I was able to select the "All regions" version for later use.

**Comment by bekuno** [comment]
Test was successful.
The translation for contacts was completed. 
We can stay with this little language difference between the main app and contacts, imho.

**Comment by Lineflyer** [comment]
This means we can use zH-rTW as lanuage code. Fine.
