### ISSUE TITLE
Add Chirpwolf as useful app (and link to it for beacon caches)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8883]
Some while ago we had to remove a useful app, which supported chirp receiving (see #3951).

There is a free app now which works quite good (for me):
https://play.google.com/store/apps/details?id=de.wolffire.chirpwolf

We should probably add this to our useful apps and (if desired) we could add a link to this app into cache details (similar to whereyougo for Wherigo caches) when the cache has the beacon attribute set.

**Comment by moving-bits** [comment]
I'll e-mail the author and ask if we can use their logo.

**Comment by moving-bits** [comment]
Received a reply from the author:
> yes this is ok for me.
> I grant you the rights to use my logo for your c:geo list.

I'll create a PR.

**Comment by Lineflyer** [comment]
@moving-bits 
Let me reopen this as the second part would IMHO also be useful:

We could add a link to this app into cache details (similar to whereyougo for Wherigo caches) when the cache has the beacon attribute set. 

This would allow users to directly launch the app or get linked to download the app in case not installed.
