### ISSUE TITLE
Use smaller font size while editing PN and Logs

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8894]
**Is your feature request related to a problem?**
Currently the font while editing PN or Logs is about three times bigger than the font for displaying PN and Logs
(at least over here, where ``System Font Size`` is set to ``Normal`` and ``Display Size`` to ``Small``).
Apart from the uncomfortable switch in sizes the way too big fonts are waste of space.

**Describe the solution you'd like**
Font sizes while editing should be smaller, resp. the same as the font size of displayed PN and Logs.

**Comment by Lomanic** [comment]
Could you post a screenshot? For me the font size to write a log is OK, it's a little bit bigger than the one in the AOSP SMS app, could you compare with it?

**Comment by MagpieFourtyTwo** [comment]
Sorry for the delay, was AFK for some days (caching & testing in real life ;) ).

Comparison of Logbook (display) and Log edit:
![0 - Logbook](https://user-images.githubusercontent.com/9889015/92060161-60e7c980-ed93-11ea-8901-0c6c899b4897.jpg) ![1 - Log edit](https://user-images.githubusercontent.com/9889015/92060172-6513e700-ed93-11ea-82b0-648b4a516aea.jpg)

Personal Note display vs. edit:
![2 - PN display](https://user-images.githubusercontent.com/9889015/92060398-f420ff00-ed93-11ea-941e-2b9d4c032380.jpg) ![3 - PN edit](https://user-images.githubusercontent.com/9889015/92060404-f71bef80-ed93-11ea-9d9d-cb98d7dd8c32.jpg)

**Comment by MagpieFourtyTwo** [comment]
I would suggest to use the same font sizes for display and edit.

**Comment by eddiemuc** [comment]
> I would suggest to use the same font sizes for display and edit.

Right now the same (bigger-than-display) font size seems to be used for every edit action in c:geo (personal note, logging, waypoint editing etc). Is your suggestion to decrease the font size only for editing PN or for all other text editing places as well?

**Comment by MagpieFourtyTwo** [comment]
Hmm, At least visually the font sizes of PN- and Log-edit seem to be different (as seen in the screenshots, which all four have exactly the same crop size and resolution), but probably these are context sensitive, too?

As for the other edit windows: You're right, the font in WP edit and TB log etc. is big, too, but over there I haven't noticed it as annoying yet, cause there typically is not that much text.

Nevertheless, I would appreciate if the edit font size would be the same in all edit windows and popups, as having too many different fonts and sizes looks kind of bumbling. Moreover it should be based on system font and display size settings (don't know how it is on other brands, but with Huawei these are two different settings, and changes in each of it result in different sizes of elements *and* font), even if, for any reason, edit font size may be (slightly) bigger than display font size by default ... although I would be happy with the same size for display and edit ...

**Comment by fm-sys** [comment]
Things have changed since our switch to material. So let's close here...
