### ISSUE TITLE
ribbonizer does not work with adaptive launcher icons (from Android 8.0)

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8896]
After changing our icon to an adaptive icon it does not show the "debug" overlay created by the Ribbonizer.
This addon seems not to be further developed - latest release is from August 2017.

Therefore I suggest to switch to another plugin.
I found easylauncher-gradle-plugin - should work for now, but also not in active development (latest from October 2018).

An alternative would be to have own images for the build flavers as described in https://stackoverflow.com/questions/19528063/android-app-icon-for-debug-and-release-mode.

Any ideas?

**Comment by moving-bits** [comment]
Or shall we simply leave out the "debug" ribbon at all?
You can still use the "about" page to see whether you are running a debug build (and most people having installed a debug version know that anyway).

**Comment by bekuno** [comment]
The start icon on android is the more interesting one to see before starting c:geo what type is installed.
But you are right, normally you know what you start ....

The now used adaptive-icon can not changed at compile time (has alredy forground and background layer).
So I propose to let the state for older devices until we change the minSdkVersion to 26 or we have another solution.

I will prepare an PR to change the ribbon collor to blue, because the current yellow is bad to distinct from the icon backgroud.
![Screenshot_20200830-171426_1](https://user-images.githubusercontent.com/32555742/91662811-0d505400-eae5-11ea-939e-757a5d9d720c.jpg)
![Screenshot_20200830-171438_1](https://user-images.githubusercontent.com/32555742/91662815-0fb2ae00-eae5-11ea-923d-78b7a55ea726.jpg)

**Comment by Lineflyer** [comment]
Would it make sense to also add it for our nightlies (if possible in the current flavor configuration).
From time to time users started using it without being aware, what it is and that they are still using it after a while. Therefore it could be helpful (also for my testing).

**Comment by bekuno** [comment]
Should be possible for the nightlies.
My short test however was not yet successful.

**Comment by bekuno** [comment]
would this ribbon be ok (RGB FF00FF)? 
![grafik](https://user-images.githubusercontent.com/32555742/91764185-26393200-ebd7-11ea-8c63-9198cc2e380e.png)

Idea for legacy - grayScale:
![grafik](https://user-images.githubusercontent.com/32555742/91767525-8e3e4700-ebdc-11ea-9ebb-574aa881ec23.png)
Or is that too much change?

Should I also implement it for rc?
Are these colors ok?

**Comment by Lineflyer** [comment]
IMHO we could stay with blue all the time just changing the text.

Regarding RC and legacy I am unsure.
Theoretically it would be a nice addon to make users aware they use such versions: especially for RC as the beta come and go when users are subscribed to the beta channel. The question is if updating the app also changes the icon reliably (when users udpate via Play from RC to normal release)?

**Comment by moving-bits** [comment]
> The question is if updating the app also changes the icon reliably (when users udpate via Play from RC to normal release)?

I cannot answer this for all use cases, but at least updating c:geo release to newer versions (including the new app icon) did change the icon in the "all apps" view, but *not* on homescreen.

**Comment by Lineflyer** [comment]
Lets try it out after this beta/release.
For me the icon updated everywhere after change to the new icon.

**Comment by bekuno** [comment]
> For me the icon updated everywhere after change to the new icon.

For me also, but I used only Samsung devices.

**Comment by Lineflyer** [comment]
> For me also, but I used only Samsung devices.

Same.

**Comment by bekuno** [comment]
What is the procedure for a beta release at google play?
(did not find it in the wiki)
Do we use the rc apk?
Do we set the apk to the release one after it is released?

**Comment by bekuno** [comment]
Info: the text could be changed from "rc" to "whatever".

**Comment by Lineflyer** [comment]
We do use the RC apk for the beta. When releasing we use a fresh release build, but not set RC to production (as this would also "break" the version codes). So its completely inline with the build flavors.
The text for rc should be "Beta".

**Comment by bekuno** [comment]
Changed all ribbuns to blue.
For rc/beta:
![ic_launcher](https://user-images.githubusercontent.com/32555742/91774590-75885e00-ebe9-11ea-8e18-291daf60f5cd.png)

**Comment by Lomanic** [comment]
> Idea for legacy - grayScale:
> ![grafik](https://user-images.githubusercontent.com/32555742/91767525-8e3e4700-ebdc-11ea-9ebb-574aa881ec23.png)
> Or is that too much change?
> 
> Should I also implement it for rc?
> Are these colors ok?

Android grays out app icons (and disables them) when there are issues accessing their data (insufficient space as I encountered recently, but could be also [when it can't access SD card for apps moved to it](https://forums.androidcentral.com/ask-question/767079-why-my-apps-greyed-out.html)) and [some themeing issues in launchers cause grayed out icons](https://forum.xda-developers.com/galaxy-s8+/help/greyed-app-icons-appdrawer-t3825717), so I would suggest not using this color (or absence of).

**Comment by bekuno** [comment]
@Lomanic 
I changed it already back to the original icon for legacy.

**Comment by Lineflyer** [comment]
@bekuno 
Did you already merge the general update to the new ribbonize mechanism?
In that case we should probably merge the latest color change so that we can see/test this with the upcoming beta.

**Comment by Lineflyer** [comment]
Just merged your latest change.
But if I understand correctly it will not be effective on devices >= Android 8.0 due to the original issue.

**Comment by bekuno** [comment]
> But if I understand correctly it will not be effective on devices >= Android 8.0 due to the original issue.

That is correct.
And additional there is no chance for a dynamic solution with our adaptive-icon.

**Comment by Lineflyer** [comment]
I aam personally not involved so much into the "developer" flavor, but I somehow would like to see the ribbons for "beta" and "nightly". Not necessarily for myself, but for users handling those versions and sometimes not being aware what they use.

As I read in your inital post you found a library applicable for now (although not maintained)...or what do you mean regarding "no chance"?
