### ISSUE TITLE
Reorder Personal Note buttons

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8898]
I would like to reorder the buttons below the PN:

-  "add/update waypoints" button on the left side and "delete waypoints" button on the right side (both in one and the only horizontal button line) 
- remove the edit button and instead open the edit pop-up when clicking on the PN or the personal note headline.
In case PN is empty, we could show a text like "[click to create personal note]" to explain users how editing then will work (but clicking on a text to edit it should be quite intuitive) 
- remove the line above the buttons 

I would like to make these changes, because the current UI doesn't look really well designed:
![Screenshot_20200829_084658](https://user-images.githubusercontent.com/64581222/91630761-772d0880-e9d4-11ea-82da-bb653351730b.jpg)

Whould this be fine or should we mabe integrate an icon based edit button into the headline? What do you think about?

**Comment by eddiemuc** [comment]
For what it is worth: this would be fine by me.
But don't forget the "Upload" button (currently placed under "Edit" button, visible e.g when connected to geocaching.com as a premium member and very important for me personally :-))

**Comment by fm-sys** [comment]
> But don't forget the "Upload" button (currently placed under "Edit" button, visible e.g when connected to geocaching.com as a premium member and very important for me personally :-))

So maybe we could place the  "upload" button in a second row below the waypoint buttons filling the total screen width

**Comment by eddiemuc** [comment]
> So maybe we could place the  "upload" button in a second row below the waypoint buttons filling the total screen width 

Also fine by me. I would however wait a bit whether there are other opinions (my sense for good user design is not the best, unfortunately)

**Comment by moving-bits** [comment]
I'm undecided:
- Yes, we could leave out the line above the buttons, if there's currently no personal note. But it looks cleaner with line IMHO, if there's some text. You could make it depending on whether personal note has some text.
- Buttons for "Add/update waypoints" and "Remove waypoints" have relatively much text, so it may happen (depending on specific translation) that they would not fit into one line.
- Also, the other two buttons "Edit" and "Upload" have a much shorter text. Having one of those buttons below the other two may look awkward as well.
- Currently we have the two buttons with long text beneath each other (also, they are related in terms of what they are working on), and we have the two buttons with the short text beneath each other, which gives a visually calm expression. For me that's a fit.
- I'm undecided about the edit button. In most places we have an explicit edit button, if there's something to edit. It's easier to see that there is a specific action involved. - But it may work without button as well.

To make a long story short: I do not see a real advantage in the proposed changes (except maybe hiding the extra line above the buttons for an empty note). Maybe switching the two lines of textual buttons for four icons will work, if the buttons are self-explaining. - But I'm in no way a UX designer, I have to admit!

**Comment by fm-sys** [comment]
> Yes, we could leave out the line above the buttons, if there's currently no personal note. But it looks cleaner with line IMHO, if there's some text. You could make it depending on whether personal note has some text. 

That would be fine.

> I'm undecided about the edit button. In most places we have an explicit edit button, if there's something to edit. It's easier to see that there is a specific action involved. - But it may work without button as well.

We could enable this onclick method, but leave the button first. This is helpful, when you have a long personal note and don't want to scroll down to the end for editing.

> Maybe switching the two lines of textual buttons for four icons will work, if the buttons are self-explaining

Upload and edit whould be easy to read icons, but the waypoint buttons are hard to explain... But the German text "Wegpunkte hinzufügen/aktualisieren" is way to long doesn't fit into the button currently. Are there ideas, how we could make this text shorter? Maybe switching the text between "add" and "update" depending on if there are already imported waypoints

**Comment by eddiemuc** [comment]
> Upload and edit whould be easy to read icons, but the waypoint buttons are hard to explain... But the German text "Wegpunkte hinzufügen/aktualisieren" is way to long doesn't fit into the button currently. Are there ideas, how we could make this text shorter? Maybe switching the text between "add" and "update" depending on if there are already imported waypoints

What about a label (not a button) reading something like "Waypoint Information" and under it two icon buttons, one for "add/update" and one for "remove"?

**Comment by moving-bits** [comment]
> > I'm undecided about the edit button. In most places we have an explicit edit button, if there's something to edit. It's easier to see that there is a specific action involved. - But it may work without button as well.
> 
> We could enable this onclick method, but leave the button first. This is helpful, when you have a long personal note and don't want to scroll down to the end for editing.

Yeah, sounds reasonable.

> > Upload and edit whould be easy to read icons, but the waypoint buttons are hard to explain... But the German text "Wegpunkte hinzufügen/aktualisieren" is way to long doesn't fit into the button currently. Are there ideas, how we could make this text shorter? Maybe switching the text between "add" and "update" depending on if there are already imported waypoints
> 
> What about a label (not a button) reading something like "Waypoint Information" and under it two icon buttons, one for "add/update" and one for "remove"?

Good idea. Maybe label the "add/update" button as "sync", to make it shorter and more universal.
We should then use a label for the other two buttons as well, maybe "Personal note".

Something like:

|Waypoints|Personal note|
|---------|-------------|
|[Sync]|[Edit]|
|[Remove]|[Upload]|

Or maybe we find appropriate icons, maybe:
- Sync: two horizontal arrows
- Remove: Trashcan
- Edit: Pencil
- Upload: up arrow

The first two icons left-aligned, the other right-aligned, to show that they have different focus/targets.

**Comment by fm-sys** [comment]
I've create a first PR to be integrated into the current release.

As replacing the texts with icon buttons may cause some more discussion, let's wait for the second part until release is done...

**Comment by Lineflyer** [comment]
I am sorry, that I did not have time to follow this issue.
Let me just give you my opinion to the original issue without knowin the current progress/status:
After first seeing the new buttons (together with the old buttons) make this section look pretty overfreighted. Even more for people with less ability or just thicker fingers it will get difficult. Besides that, it looks kind of ugly.

I do however not have a constructive proposal as I do not know whats technically possible here. Something like a on demand expanding menu (like the three-dot-button)?

**Comment by eddiemuc** [comment]
We could go the easy way and stuff the two new options in the all-powerful cache detail context menu, maybe in a new sub-context-menu "Waypoints" (and also move "extract waypoints" (what is the meaning of this btw?) and "prevent waypoints from extraction" there)

![image](https://user-images.githubusercontent.com/6909759/91799229-ef8b0800-ec26-11ea-8b4c-b12c8ed89db5.png)

**Comment by fm-sys** [comment]
For the waypoint icons we could do something like this:
![delete](https://user-images.githubusercontent.com/64581222/91868520-1a03b200-ec75-11ea-9893-14645cc526a4.png)
![sync](https://user-images.githubusercontent.com/64581222/91868524-1a9c4880-ec75-11ea-980e-9502459a4a1c.png)

or this one's:
![delete_alternativ](https://user-images.githubusercontent.com/64581222/91869738-86cb7c00-ec76-11ea-81f3-26e0a479a16d.png)
![sync_alternativ](https://user-images.githubusercontent.com/64581222/91869742-87641280-ec76-11ea-863f-6a83827a110f.png)


This would be quite clear so we don't need headings for the icon categorys. Or we move the waypoint stuff to the context-menu as written by @eddiemuc. And if we are working on the context-menu we should categorize the other enterys as well (for example "Store", "Refresh", "Remove" into "Manage cache") to make it more clear.

For upload I would like to use this icon:
![cloud_upload-black-24dp](https://user-images.githubusercontent.com/64581222/91872483-36551e00-ec78-11ea-8337-441a3d365f64.png)
...and the edit icon is already used in other places.

Only "problem" is that they do not realy fit with the other icons used in c:geo, but there is another PR (#7856) for upgrading all the other icons as well...

**Comment by eddiemuc** [comment]
Hi @fm-sys , I really like your icons (would personally prefer the second set). I would definitely prefer a icon-button solution over stuffing functions into the context-menu (which, imho, is already quite overloaded).
Regarding the "fitting" of the icons: I stumbed across this page in the wiki: https://github.com/cgeo/cgeo/wiki/How-to-create-custom-icons . I don't know if this is still the current way of doing this though.

**Comment by moving-bits** [comment]
We do have both the "trashcan" icon as well as the "sync" icon already in c:geo which we can reuse here:

ic_menu_delete:
![image](https://user-images.githubusercontent.com/3754370/91902631-50a3f180-eca2-11ea-81d2-05674067350b.png)

ic_menu_refresh:
![image](https://user-images.githubusercontent.com/3754370/91902664-5e597700-eca2-11ea-8850-3d9c0a27d730.png)

Then we could stay within the current style of c:geo.

**Comment by fm-sys** [comment]
But then we would need the additional label under the buttons which I tried to avoid...

**Comment by moving-bits** [comment]
We can still combine those icons and the marker idea. Just wanted to say that we don't have to start from scratch.

**Comment by Lineflyer** [comment]
I just saw the new icon approach PR. 
Does anyone know if its possible to have a drop down menu with three dot button (like the cache overflow menu button) which is placed in the personal note section (e.g. top right of it).
This could then contain the options.

The reason why I would prefer this over the icon solution:
- Supports also adding more actions for the note in future without having the same problem again
- Less space consuming
- Could be more easy to access as currently the user needs to scroll below the note to get to the icons/options.

**Comment by eddiemuc** [comment]
I think the icons are a great improvement when compared to the current state with all the text buttons, and I would vote for keep this improvement.
@Lineflyer your points are valid though, maybe this could be done in a later PR? (actually, maybe one of these days we could think about some kind of global c:geo GUI guideline)
@fm-sys I would be interested in how you managed to create the new icons. They look really good.

**Comment by Lineflyer** [comment]
> @Lineflyer your points are valid though, maybe this could be done in a later PR?

Sure. We can use the icon solution first. I just wanted some feedback what solution is prefered by others here and whether someone knows if its technically possible to implement a dropdown here.

**Comment by fm-sys** [comment]
> Does anyone know if its possible to have a drop down menu with three dot button (like the cache overflow menu button) which is placed in the personal note section (e.g. top right of it) 
This could then contain the options.

Should we also place the edit option there? Users can also edit the PN by clicking on the text, but I'm not should if we should hide the edit button this way...

We could also think of placing meanfull icons (left to the text) into the context menu's everywhere in c:geo to make them easier to use. But I'm not sure if this is really helpful or more annoying...

> @fm-sys I would be interested in how you managed to create the new icons. They look really good.

I used GIMP to edit and color the icons. Let's explain it in German (easier for me):
1. Ebene duplizieren
2. Duplizierte Ebene invertieren
3. Die schwarze Ebene in den Hintergrund schieben
4. (die schwarze Ebene ist immer noch ausgewählt) 
5. Filter Verzerren > Verteilen. Weniger Transparent auswählen und filter mit Standard Einstellungen bestätigen
6. Filter paar mal wiederholen (Strg + F)
7. Wenn der Rahmen die gewollte Breite hat, Filter > Gauß'sche Unschärfe
8. Ebenen zusammenführen
9. Deckkraft der Ebene auf 60% setzen
10. Fertig! Jetzt natürlich noch als PNG exportieren...

@eddiemuc but if you only need one icon I can edit it for you too. Your choice ;-)

**Comment by eddiemuc** [comment]
@fm-sys thanks a lot for the explanation! I might come back to your offer later :-)

**Comment by fm-sys** [comment]
> The reason why I would prefer this over the icon solution:
>
>   - Supports also adding more actions for the note in future without having the same problem again

We can think about it, when we have these new actions ;-)
>  - Less space consuming

The buttons are at the very bottom, so they don't really bother...
>  - Could be more easy to access as currently the user needs to scroll below the note to get to the icons/options.

To edit the text, you can click directly on the text (since recently). All other options are not that common... So I would also vote for keep is as it is, until more actions are coming.
