### ISSUE TITLE
Add meaning of c:geo to FAQs

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#8904]
Not the biggest priority, but I am really interested:
* what is the actual meaning of the name "c:geo"? Is this an acronym, and what does it mean?
* If anyone knows, this might be something to add to the FAQs

**Comment by moving-bits** [comment]
Just a blind guess: "carnero geocaching" (carnero being the original author of c:geo, before it became open source)

**Comment by Lineflyer** [comment]
Well....Let me give you my answer to this riddle:
.
.
.
I have no idea, but the theory of @moving-bits is no that unlikely.

The only person, who can probably answer that is @mucek4 

But anyhow I don't think its really needed for the FAQ...still a nice addon maybe combined with the correct pronunciation.

**Comment by mucek4** [comment]
@moving-bits is afaik correct. Name c:geo was inherent from our grandfather Carnero.

**Comment by bekuno** [comment]
To look back - the oldest web page for c:geo :
https://web.archive.org/web/20100209004446/http://cgeo.carnero.cc/

**Comment by eddiemuc** [comment]
Thanks to all of you. I created wiki page https://github.com/cgeo/cgeo/wiki/Project-roots-and-history to collect the information in this issue. Since my question is answered, and as long as we don't want to put this in FAQ, we can close this issue as far as I am concerned. I will leave it open for a few days in case there are more comments, then I will close it.

**Comment by Lomanic** [comment]
There are more details in French of the genesis of the OSS development of cgeo [in this 2013 blog article](https://geocaching-tof.fr/2013/05/27/cgeo-interview/), as told by @samueltardieu. I can add these to the wiki article.

**Comment by fm-sys** [comment]
Has anyone a backup of one of the first beta apk released in 2010. Would be cool if we could archive it on the wiki with the small hint, that login will not be possible and it will only run on very old devices...

**Comment by rsudev** [comment]
The oldest one I have is version 1.42 from December 2010, if that is of interest...

**Comment by fm-sys** [comment]
> The oldest one I have is version 1.42 from December 2010, if that is of interest...

Why not, that's quite early... I would vote for adding it.

**Comment by Lineflyer** [comment]
> The oldest one I have is version 1.42 from December 2010, if that is of interest...

Would love to try it.
Maybe I can use it for some throwback postings on Facebook.

**Comment by rsudev** [comment]
There you go:
[carnero.cgeo.zip](https://github.com/cgeo/cgeo/files/5158424/carnero.cgeo.zip)

**Comment by bekuno** [comment]
If someone want the real old code - this is the "initial" commit at github:
https://github.com/just-radovan/c-geo/tree/fafff9663462ac650ddd2ed38b356d9c8c8a42d1
The version is "0.74.6", date 22 Jul 2010.

The "first commit" at the current cgeo org was
https://github.com/cgeo/cgeo/tree/3a311f2a45a79a19ebc4e2b66f5e92a2f390c04d
version "2.26 RC1a" on 11 Jul 2011.

**Comment by fm-sys** [comment]
> There you go:
> [carnero.cgeo.zip](https://github.com/cgeo/cgeo/files/5158424/carnero.cgeo.zip)

How funny is this! Installation still works even on Android 10. And the UI is quite the same ;-) And the message: "don't forget MENU button on your phone, it will show many functions of c:geo!" I had already forgot that there was a menu button on older devices... Love it!

**Comment by Lomanic** [comment]
> > There are more details in French of the genesis of the OSS development of cgeo [in this 2013 blog article](https://geocaching-tof.fr/2013/05/27/cgeo-interview/), as told by @samueltardieu. I can add these to the wiki article.
> 
> I added the link to the wiki page

I took the liberty to detail more from the geocaching-tof.fr article while linking the first "OSS commit", also added the opensource announcement by the original developer. Hope it's OK for you @eddiemuc.

**Comment by eddiemuc** [comment]
> I took the liberty to detail more from the geocaching-tof.fr article while linking the first "OSS commit", also added the opensource announcement by the original developer. Hope it's OK for you @eddiemuc.

Thank you for improving the page so greatly! Makes it much more readable and informative. 
I edited it a bit further to include all information I gathered from the conversation in this issue.

Does anyone has some screenshots from the original version or the one uploaded by @rsudev earlier in this conversation? (@fm-sys : maybe you?) I would link them as well.

(Note: I noticed earlier that strangely there seems to be no option in the Wiki to upload images or other files, while this is obviously possible in issue conversations. Is this restriction in the Wiki really true or did I miss something there?)

**Comment by fm-sys** [comment]
Pictures and files can be added via markdown, but we need to store them somewhere else.

**Comment by eddiemuc** [comment]
> Pictures and files can be added via markdown, but we need to store them somewhere else.
> 
> Mabe at `cgeo.github.io/archive/`?

I think it also works when you simply paste pictures to an issue (regardless of which one). Then it is uploaded, and you can use the link to the uploaded image also in the wiki.

**Comment by fm-sys** [comment]
> > Pictures and files can be added via markdown, but we need to store them somewhere else.
> > Mabe at `cgeo.github.io/archive/`?
> 
> I think it also works when you simply paste pictures to an issue (regardless of which one). Then it is uploaded, and you can use the link to the uploaded image also in the wiki.

Agreed for the images, but you can't attach an apk directly and using a zip archive is not the nicest way...

**Comment by eddiemuc** [comment]
> Agreed for the images, but you can't attach an apk directly and using a zip archive is not the nicest way...

You are right of course, this is not a nice way. On the other hand, I personally feel a bit "safer" not to expose this very old APK directly installable. Exposing it as a ZIP has the advantage that someone who wants to install it 

1. has to do some explicit work (extracting it etc), thus confirming that he/she **really** wants to install it
1. has to show a minimum level of technical expertise, hence can be trusted a bit more to know what he/she's doing

I assume that we do not want users to install this old APK and actually go geocaching with it. We rather want them to use the newest version for that.

**Comment by fm-sys** [comment]
Agreed, if we use a zip archive we can also add a small readme explaining the use case of this very old and that the apk is not fully functional anymore...

**Comment by eddiemuc** [comment]
Well, this was a fruitful discussion. I learned a lot and I think we created a nice pool of preserve-worthy information. Thanks a lot to all participants.

Since the Wiki page exists now and can be used to add further things, I would close this issue.

**Comment by fm-sys** [comment]
I don't know, if it's still of interest, but here are some screenshots of one of the first c:geo versions... 

![Screenshot_20201016_130038.jpg](https://user-images.githubusercontent.com/64581222/96255443-35bde000-0fb7-11eb-95bd-7deec285c5db.jpg)![Screenshot_20201016_125942.jpg](https://user-images.githubusercontent.com/64581222/96255455-39516700-0fb7-11eb-92cf-dab3e6fe5fc7.jpg)![Screenshot_20201016_125807.jpg](https://user-images.githubusercontent.com/64581222/96255458-3b1b2a80-0fb7-11eb-9d6d-60cb8a1ded28.jpg)![Screenshot_20201016_125203.jpg](https://user-images.githubusercontent.com/64581222/96255459-3c4c5780-0fb7-11eb-90a9-6fbca83b7520.jpg)![Screenshot_20201016_124632.jpg](https://user-images.githubusercontent.com/64581222/96255465-3e161b00-0fb7-11eb-8205-c8c084fb8c57.jpg)

**Comment by eddiemuc** [comment]
@fm-sys is it ok for you if I link them to the wiki page about cgeo history?

**Comment by fm-sys** [comment]
Yes, totally fine for me!

**Comment by eddiemuc** [comment]
Done :-) Thanks a lot!
