### ISSUE TITLE
Where is map_trail_hide?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8917]
A user on Crowdin asked where this string can be found in the menu.

I was certain, that I will find it in Map - Menu - Position history (or similar translated), but its not in that menu.
Can someone enlight me or directly reply to the translator: https://crowdin.com/translate/cgeo/162/en-pt#26612

**Comment by moving-bits** [comment]
With #8910 we moved the "hide history track" menu item from "map settings" submenu to the "history track" submenu. Instead of a checkbox it's now two context-sensitive menu entries "show history track" and "hide history track".

I'll answer at Crowdin as well.

**Comment by Lineflyer** [comment]
OK, its only in tomorrows nightly. That explains, you are to fast for me ;) 
Thanks!
