### ISSUE TITLE
Offer c:geo for navigation intents

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8925]
**Is your feature request related to a problem?**
A few days ago I followed one of those Lab Adventures using the specific app. When selecting the next waypoint you can choose to open navigation - which offers all navigation apps available on your mobile (eg: Google Maps, Here we go etc.), but no c:geo. As I'm out geocaching I would love to see c:geo listed here as well, as c:geo in combination with BRouter is a fantastic navigation app (not only) for geocaching, having much more detailed (OSM) maps than Google Maps.

**Describe the solution you'd like**
Have c:geo offered as navigation map when sending a `geo:` intent.

**Additional context**
See the docs: https://developer.android.com/guide/components/intents-common#ViewMap

We should at least implement the following variants:
- `geo:latitude,longitude` - eg: `geo:47.6,-122.3`
- `geo:latitude,longitude?z=zoom` - `geo:47.6,-122.3?z=11`
- `geo:0,0?q=lat,lng(label)` - `geo:0,0?q=34.99,-106.61(Treasure)`

Create a new waypoint in the "go to" history with the given coordinates (and name, if available), and open the waypoint page for this. By tapping on the navigation symbol beside this waypoint you'll open the map at this coordinates (and start navigation, if BRoute is installed).

Optionally we could support the last variant as well and use the query string as input for our address search:
- `geo:0,0?q=my+street+address`

**Comment by geocachermgo** [comment]
Isn't BRouter in the list of the navigation tools?
