### ISSUE TITLE
Support new gc.com attributes

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8927]
Just released today, no technical info yet:

https://forums.geocaching.com/GC/index.php?/topic/358304-release-notes-new-attributes-august-31-2020/

There are 4 new atrributes..which are IMHO indeed useful:
- Bonus cache 
- Power trail
- Challenge cache
- Solution checker available

I will next days apply the attributes to my matching owned cache (AFAIR I have all of them) to allow testing.

**Comment by Lineflyer** [comment]
Attribute already added...couldn't resist:
- https://coord.info/GC3RG33  --> Challenge attribute
- https://coord.info/GC8X9BQ  --> Bonus cache
- https://coord.info/GC5HQ2Z  --> Power trail (well, a small one)

The solution checker attribute should either show up automatically or I need to re-edit the cache..not sure, what the release note means:
- https://coord.info/GC3EQ4W --> Solution checker attribute

**Comment by Narrat** [comment]
The solution checker attribute will only be added automatically if you use the gc.com checker itself. External checkers won't be covered by that

**Comment by bekuno** [comment]
Codewise the changes are prepared.
But now we need fine icons.

My favorites are
- Challenge cache: https://thenounproject.com/term/challenge/3203889/
- Bonus cache: https://thenounproject.com/term/add/2640238/
- Power trail stage: https://thenounproject.com/term/trail/689645/
- GC Solution checker: https://thenounproject.com/term/solution/2998552/

Alle 4 are licensed by Creative Commons, esp. CCBY 
(`When using it for any project, you are required to give credit to the icon‘s creator or purchase a royalty–free license.`)

What do you mean?

Does someone has ressources to prepare the icons for c:geo?
Informations are stored in main/project/attributes.
The readme.txt is a bit outdated but should sufficient to built the icons in a Linux environment (Points 1-4).

**Comment by Lineflyer** [comment]
We are already using icons from this source and have it referenced in About c:geo.

Those you suggested look quite good for their respective meaning.

**Comment by bekuno** [comment]
This would be the icons and the English texts
![grafik](https://user-images.githubusercontent.com/32555742/93616008-6e789280-f9d4-11ea-96d1-ac2122f05366.png)
