### ISSUE TITLE
Send nearby notifications to Android notification interface

### ISSUE THREAD

**Issue by Oskar1983** [cgeo/cgeo#8930]
Having nearby notifications is a nice feature. However, it would be even better if those notifications were pushed to the Android notification interface. So you'd be able to leave the smartphone in your pocket and get the nearby notifications via smartwatch, activity tracker, ...

I think, I even got some notifications to my smartwatch sporadically with an older version of c:geo. So maybe it is or was already implemented somehow?

**Comment by Lineflyer** [comment]
It should be pushed to the notification interface already (notification itself needs to be enabled in our settings).
We do however still have the drawback, that it (depending on Android version) does not yet work, if the screen is off. That is already listed in another issue.

@moving-bits Correct me, if I am wrong.

**Comment by moving-bits** [comment]
Nearby notification sent to the Android notification system is implemented. Go to map => settings => proximity notification and set the type to "text" or "text + tone".

The issue @Lineflyer relates to is #7057. We need to implement a (foreground) service to refrain Android from sparsening the location updates for c:geo.

**Comment by Oskar1983** [comment]
Thanks for the explanation. I gave it a try with two phones, an older one with Android 7 and an newer one with Android 10. 

I left the screen active all the time, so #7057 should not have had any impact. 

On the older phone everything is working. However I had to adjust the slider for notifications in the app settings for c:geo. "Let the app decide" did not show up any notification, neither on the screen nor on the smartwatch.

In contrast to this on the Android 10 phone notifications are shown on the screen without modifying the settings for the app. So here "let the app decide" seems to work better. However I did not manage to get any notification from c:geo displayed on the smartwatch. I tried all settings in the slider for the app notifications but nothing showed up on the watch. Do you know if it is possible to debug that somehow? Or is there another setting in Android 10 I missed out? Other apps are able to show notifications on the watch, c:geo is not, at least in my case.

**Comment by moving-bits** [comment]
Hm, I don't know if there is an official mechanism to force notifications to another device.
While testing I'd used a fitness tracker, and with that came a companion app. I had to adjust the settings in that app to forward the notifications coming from c:geo to the fitness tracker. Having done that, it worked for me.

**Comment by Oskar1983** [comment]
I just deleted and reinstalled everything on the Android 10 phone, c:geo and gadgetbridge for my watch. Now it seems to work fine. When installing, the phone asked for permissions. For gadgetbrigde it asked for granting location service also for background usage whereas for c:geo it only asked for location service while app is running. Maybe that's an approach for #7057 and related to change the permission request somehow?
