### ISSUE TITLE
Support color-coded cache categories

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#8932]
**Is your feature request related to a problem?**
Especially with large lists and in map display with many caches visible I would like to get a quick overview over different categories of caches which I assigned myself

**Describe the solution you'd like**
I would like to use colors to categorize my caches (a bit like I can assign color-coded categories to my emails in Outlook). One cache can have multiple "color categories"
"Color categories" could be assigned to caches in different ways:
* explicitely on a per-cache-basis
* By assigning a color-category to a list => all caches in this list have then this color category
* Advanced: by allowing the user to enter some rules based on cache attributes (e.g. "all caches from owner xy, all caches whose title starts with "Challenge", all caches with attribute "night cache" set...)

"Color categories" are displayed in many places:
* on the map (small coloured circle in upper-right corner or icon background color)
* in list results
* in cache detail view

"Color categories" can be used as filter criterion in lists

**Describe alternatives you've considered**
This is an extension of categorizing using lists alone. Not implementing the feature would be the alternative.

**Additional context**
This is inspired by the possibility to color-code caches using "Geooh GO"

**Comment by Lomanic** [comment]
There is something for whole lists, see _Set list marker_ https://cgeo.droescher.eu/en/mainmenu/lists#manage_lists

**Comment by eddiemuc** [comment]
omg, I didn't know that! Thanks a log, I will close the issue
