### ISSUE TITLE
[Nightly] Crash when tap on Saved Log

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8935]
**Describe the bug:**
After upgrading to latest nightly I can not open any ``Saved Log`` anymore, which has been saved with a previous nightly.
As soon as I tap the displayed log text, c:geo crashes with a NullPointerException - pls. see attached logfile.
These ``Saved Logs`` are created with nightlies dated August, 21st up to yesterday's nightly.
If I create a *new* ``Saved Log`` with the current nightly and reopen it, this works.

**To Reproduce:**
1. open any cache with an already offline ``Saved Log`` (must be from a previous nightly!)
2. click on the ``Saved Log`` text to edit it

**Actual behavior/state after performing these steps:**
c:geo immediately crashes and restarts in previously selected cache list.

Workaround: In order to at least get rid of the non-editable ``Saved Log``, you can use ``Select mode`` and ``Manage Caches`` => ``Clear offline logs`` to delete it (after uploading it to gc.com, of course ;) ).

**Version of c:geo used:**
2020.09.03-NB-868fddb

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.1.0.140(C431E19R2P5)
c:geo version: 2020.09.03-NB-868fddb
Google Play services: disabled - 20.30.19 (120400-326531024)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: original 
HW acceleration: enabled (default state)
System language: en_DE
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (76,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (76,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (76,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (286,4 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
BRouter connection available: true
--- End of system information ---
```

**Additional context:**
Remark: The log file moreover contains an ArrayIndexOutOfBoundsException (dated 08-26) - this was with a previous nightly version and most probably happened while switching from OSM to GM - this happens from time to time, but is not reproducible (yet) - perhaps this helps anyway, so I just left it in the log file.

[logcat_2020-09-03_02-32.txt](https://github.com/cgeo/cgeo/files/5165509/logcat_2020-09-03_02-32.txt)

**Comment by eddiemuc** [comment]
Since I did some major changes to offline logs I am pretty sure this is my wrongdoing and thus mine to look into...

**Comment by eddiemuc** [comment]
A clear bug of mine. Sorry.
Associated PR should fix it.

**Comment by Lineflyer** [comment]
Thanks @eddiemuc for the fast fix. 

@MagpieFourtyTwo Thanks for finding and reporting. I triggered production of a new nightly, which should be ready to download/upgrade in a few minutes. You may upgrade then and test if the problem is gone.

**Comment by MagpieFourtyTwo** [comment]
Yep, seems to be fixed. Thx2 @eddiemuc 
Although saving the first offline log seemed to take even more time now (like reported in #8632).
But this was just felt, not measured and the second try was like before ... nevertheless still 3 to 5 seconds ...  :/

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo the offline log change will for sure not make offline log saving faster, but it should also not make it slower.
I try to take a look at #8632 during next few days.

**Comment by MagpieFourtyTwo** [comment]
Great! Thx a lot! (cause these seconds are really annoying ... esp. while others are waiting for you to get ready ...  ;) )
