### ISSUE TITLE
Explain how to find Offline logs

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#8938]
**Is your feature request related to a problem?**
I've just updated to the latest version [ 2020.09.02-RC ] and I see that the count of offline logs are now shown on the first screen. Mine says (11172 + 7).
But I didn't know I had any offline logs - how do I find them to see if they are mistakes or logs I've forgotten to upload.

**Describe the solution you'd like**
some way to find Offline logs - maybe this exists and I just can't find it.

**Additional context**
As above, mine says (11172 + 7), according to the web site I do have 11172 finds and when I try to log a new find on cgeo I get find 11180 in my auto-generated siganture.

**Comment by rsudev** [comment]
You can select the built-in list '<all>' and than filter for 'with own information' - 'with offline log'
(the english strings are a back-translation from my current german UI)

**Comment by Lineflyer** [comment]
@rsudev post is missing the list name. It should be "history"

**Comment by alan666notb** [comment]
OK - thanks for that, I had 7 'finds' and 2 'Write notes' saved from a LONG time ago - 2016 in fact. They were all present on the website so I just 'cleared' them in cgeo and things now seem to be correct.

But the location of that info is not obvious, I think most people will struggle to figure that out.
Maybe there needs to be a better/more obvious way to get to the info?

Also, if you haven't read the release notes, it's not obvious what the "(11172 + 7)" means in the first place.

**Comment by Lineflyer** [comment]
You are right. We should probably add a FAQ entry for that.

**Comment by Lineflyer** [comment]
Opened an issue on our website repo for adding it to FAQ.

**Comment by fm-sys** [comment]
"Write note" logs should not be counted, cause it is only a found counter. I will test this...

For explaining how to find such old offline logs, it would be better to show a one-time dialog the first time a "+"-number will be displayed. Cause most of the users will not look into the FAQ.

The only question is: can we merge translations also to release?

**Comment by alan666notb** [comment]
@fm-sys - the 'Write notes' were not counted in the offline finds, I just saw them when I filtered the history list for offline data (I'd never done that before).

**Comment by fm-sys** [comment]
> @fm-sys - the 'Write notes' were not counted in the offline finds, I just saw them when I filtered the history list for offline data (I'd never done that before).

Ok, thank you! I also tested it with some log types and only found logs are counted.

Second question is: Should we include such a info message for explaining this feature?

It could be like this:
"You have offline logs, that are not uploaded yet. Therefore a counter (eg. "+ 1") will be displayed. If you don't like it, you can disable it in settings.

To find them easily, goto "history list" and filter for With personal data > With offline log"

**Comment by Lineflyer** [comment]
> The only question is: can we merge translations also to release?

Unfortunately not any longer as there are new strings on master already.
We would need to cherry pick and due conflict resolution, which is not that easy. I would prefer not doing this, as last time it totally messed up.

**Comment by fm-sys** [comment]
> I would prefer not doing this, as last time it totally messed up.

Do not translate the message (for this release) or not add it at all?

Cause mabe there will be quit a lot traffic on support by users, don't know how to filter for offline logs...

**Comment by fm-sys** [comment]
Or what about a small hint at the changelog?

**Comment by MagpieFourtyTwo** [comment]
> To find them easily, goto "history list" and filter for With personal data > With offline log"

Really?  IIRC ``History List`` gets purged after a while, didn't it? And, to be honest, based on (an admittedly pretty old) experience I don't really trust the history list ...  ;)
So wouldn't it be better to open ``All caches`` and filter for ``With personal data`` => ``With offline log`` (as not saved caches can not have an offline log for sure) ...?

Nevertheless, this filter setting results in 85 caches over here (in of course both lists), while the start screen reports "+ 66" - which is the correct value, as the difference of 19 caches are already online logged DNFs, for which I *additionally* saved an Offline DNF-Log (in order to see the blueish growny in map and lists, which is my workaround for #8604, #6614 and #3206) - which (most thankfully) are filtered out for the offline log counter on the start page.

So, perhaps one would feel the need for an additional filter for the *really* missing offline logs, representing the same filter as the start page counter uses ... but, in fact, I have no idea of how to call it shortly and concise.

**Comment by geocachermgo** [comment]
Wouldnt it be possible to create the filtered list if someone clicks on the +7?
Or add a little bit of text like (4000 + 7 offl.)?

**Comment by alan666notb** [comment]
> Wouldnt it be possible to create the filtered list if someone clicks on the +7?
> Or add a little bit of text like (4000 + 7 offl.)?

That was first instinct - tap on the "+7".
For some reason it takes you to the list of services available.

**Comment by MagpieFourtyTwo** [comment]
> For some reason it takes you to the list of services available.

In fact these lines are showing the services you currently have configured
and ending up in ``Services`` when tapping these appears to be conclusive to me ...

**Comment by fm-sys** [comment]
> So wouldn't it be better to open All caches and filter for With personal data => With offline log (as not saved caches can not have an offline log for sure) ...?

Caches not stored offline **can** have offline logs, if you delete the cache from the list where it is stored it also gets hidden in all caches but is still available at the history list. (see https://github.com/cgeo/cgeo/pull/8776#issuecomment-671519602)

**Comment by MagpieFourtyTwo** [comment]
Oops.  Ok, thanks for clarification.
Nevertheless even more reason to have a dedicated filter for this ...

**Comment by Lineflyer** [comment]
> Do not translate the message (for this release) or not add it at all?

We can add it and translation only for next release.

**Comment by geocachermgo** [comment]
Since it's implemented, can this be closed?

**Comment by fm-sys** [comment]
Yes, you are right! Thanks for the hint...
