### ISSUE TITLE
Problem with tb actions while logging

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8942]
Just copying from support mail, no time to check myself at this moment:

---

To check.
When you "report your visit", the TB are "Has visited" (personal settings). If I want to choose another reason including "do nothing" the list of choices is already on this check mark. If we take this choice again, nothing happens. You have to change the motive. Go back to this pattern for it to take effect.

---

```
--- System information ---
Device: SM-G950F (dreamltexx, samsung)
Android version: 9
Android build: PPR1.180610.011.G950FXXU9DTF1
c:geo version: 2020.09.02-RC
Google Play services: enabled - 20.30.19 (100408-326531024)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: fr_FR
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (9,1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (9,1 GB free) external non-removable
Geocache data: /storage/6432-3331/Android/data/cgeo.geocaching/files/GeocacheData (82,0 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (64,2 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Connecté) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins: contacts
BRouter connection available: true
--- End of system information ---
```

**Comment by MagpieFourtyTwo** [comment]
WFM.

```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.1.0.140(C431E19R2P5)
c:geo version: 2020.09.03-NB2-9e114df
Google Play services: disabled - 20.30.19 (120400-326531024)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: original 
HW acceleration: enabled (default state)
System language: en_DE
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (76,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (76,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (76,2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (286,4 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
BRouter connection available: true
--- End of system information ---
```

**Comment by MagpieFourtyTwo** [comment]
Withdrawal ... just upgraded to latest nightly and checked another scenario:
- in ``Settings`` => ``Logging`` set ``Visit TBs [X]``
- start to log a cache (over here a template will be inserted automatically)
- go down to TB list
- in a TB's line click ``Visited`` to change the action of *one* TB => works (this is what I checked above, with prev. nightly)
- but click ``Change All`` => choice is set to ``Do nothing``

In order to change all TBs in one go to ``Do nothing`` by using ``Change All``, you in fact have to first select ``Visited`` and then use ``Change All`` again to change them to ``Do nothing``.

Thus verified.  ;)

**Comment by eddiemuc** [comment]
My fault again

**Comment by eddiemuc** [comment]
This has to be fixed on `release` branch now, right?

**Comment by Lineflyer** [comment]
Correct

**Comment by eddiemuc** [comment]
fix provided in PR #8946 .
Is this automatically merged to master as well or do I have to do something additional for that?

**Comment by moving-bits** [comment]
> Is this automatically merged to master as well or do I have to do something additional for that?

"Automatism" in this case is @Lineflyer or me merging `release` to `master` every now and then during a beta cycle.

**Comment by Lineflyer** [comment]
Better rather just directly after merging the PR to avoid merge conflicts later on and also have the fix in nightlies.

As I am out for the next weeks I count on @moving-bits  :)

**Comment by eddiemuc** [comment]
> Better rather just directly after merging the PR to avoid merge conflicts later on and also have the fix in nightlies.
> 

Ok, In will put it into master as soon as it is in release.

**Comment by moving-bits** [comment]
> > Better rather just directly after merging the PR to avoid merge conflicts later on and also have the fix in nightlies.
> 
> Ok, In will put it into master as soon as it is in release.

You don't have to (and should not) create an extra PR for getting things to `master` branch as well - we do that by merging `release` to `master`, to keep the commit history clean and to avoid merge conflicts.

I think @Lineflyer's comment was directed into my direction regarding my "every now and then" :-)

What I wanted to say was: I'll not be able to merge on a daily basis, but I'll try to remember to merge `release` to `master` directly after merging a PR to `release`.

**Comment by MagpieFourtyTwo** [comment]
Tested - seems to be fixed. Thx!
