### ISSUE TITLE
Status of map downloader if target is not writeable

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8944]
Some beta users contacted us, that they receive a proper error message, that their downloaded map cannot be stored due to write permission limitation.
The reason is, that their map dir is set to SD, which we cannot write (as known).

I just want to clarify how this is handled by c:geo at this moment, as I do not clearly remember.
Will the download just be dismissed or is the downloaded file stored somewhere?
Or do we even check before download start?

**Comment by MagpieFourtyTwo** [comment]
There's just the message, and then the story ends.
Using e. g. internal ``Download`` dir instead (or even let the user chose a folder)
and leave it to the user to move the stuff manually would be a good alternative, I would say.
BTW: What would you think of different download sources, as I e. g. strongly prefer openandromaps ...?

**Comment by moving-bits** [comment]
> Check is done prior to download, then there's just the message, and that's where the story ends.

Confirmed

> Using e. g. internal `Download` dir instead (or even let the user chose a folder)
> and leave it to the user to move the stuff manually would be a good alternative, I would say.

I need to check first, whether I can make the downloaded file "visible" in some way.

> BTW: What would you think of different download sources, as I e. g. strongly prefer openandromaps ...?

First things first - for now I wanted to have an easy-to-use way of downloading offline map files to ease the onboarding process. Standard maps from mapsforge server don't require a special theme, so it's hassle-free.

More download sources like openandromaps (including their elevate theme) and freizeitkarte may follow as time permits.

**Comment by MagpieFourtyTwo** [comment]
>First things first

Of course - this was just to check the general acceptance of my idea ...
although in fact a virtually inevitable question, born due to Wilhelm Busch's principle: "A wish, fulfilled, immediately gets kids." ;)

**Comment by moving-bits** [comment]
> Of course - this was just to check the general acceptance of my idea ...

No problem. I have thought about it already for myself, actually, and have some ideas how to implement it, just not enough time at the moment.

> although in fact a virtually inevitable question, born due to Wilhelm Busch's principle: "A wish, fulfilled, immediately gets kids." ;)

:-)
