### ISSUE TITLE
Made offline log count in log templates optional

### ISSUE THREAD

**Issue by king-ton** [cgeo/cgeo#8947]
Hey guys,

thanks for the create work with new beta release!

It is possible to made it optional that offline logs count towards the number in log templates?

How I log caches:
1. I create a offline log while a geocache tour.
2. At end of day I write a text as a template.
3. Than I edit each offline log and insert the log template.
4. I submit the log. and do that again with the next geocache.

There is than the wrong number. I want that there is the current find count + 1

Thanks!

**Comment by fm-sys** [comment]
Not currently. But I would see tow options:
- create a settings option "legacy logging"
- create a second logging template "number (ignore offlinelogs)"

I personally prefer the firstooption

**Comment by Lineflyer** [comment]
@king-ton could also just include the find count template already in his signature. So it will be correct but he can still provide the rest later.

**Comment by fm-sys** [comment]
As we are willing to create a great geocaching app, we should fix this instead scaring some users off.

> And mabe for next release, check if some logs are newer as the cache-log you are logging and if it's the case ignore them. 

Probably I will have time to work on it this weekend, so we wouldn't need a new settings option. If it's ok to make this change without some time of testing in the nightlies...

**Comment by Lineflyer** [comment]
The second template would IMHO be the way to go to avoid yet another setting.
We can base it on ˋreleaseˋ as I guess the change is not so huge.
