### ISSUE TITLE
[Nightly] Incorrect Date of Offline Log

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8950]
**Describe the bug:**
Right now I changed and uploaded an offline log from yesterday's found to server - but over there it popped up with date of today. So I cross checked it in c::geo: On the ``Details`` page it's listed correctly (03/09/2020), but in ``Logbook`` the log is dated `"Today". Edited the log again, to "correct" the date, set it to yesterday again, but as soon as I save the log, there is "Today" again. In the ``Details`` page the date is still 03/09/20, thus correct.

**To Reproduce:**
1. open any cache with an offline log from yesterday or even earlier
   (or just create a new Offline Log and set the date to anything in the past)
2. go to ``Logbook``, edit and save the log
3. have a look at it's date ...

**Actual behavior/state after performing these steps:**
"Today" will be shown, no matter which date you've set while editing the log,
while in ``Details`` page the correct date will be displayed.
Uploading the fieldnote to server shows "Today", too.

**Expected behavior/state after performing these steps:**
Date should be saved and exported as set while the log was edited.

**Version of c:geo used:**
2020.09.04-NB-d98eb60

**Is the problem reproducible:**
Yes

**Additional context:**
Maybe this error already existed yesterday, as there is another cache from the day before yesterday, which is dated "yesterday" right now ... maybe have edited this log yesterday without recognizing the date change ...

**Comment by Lineflyer** [comment]
confirmed. Same for me.
Seems the log date is either not saved or overwritten when reopening.

**Comment by MagpieFourtyTwo** [comment]
I would say, the latter, as I just produced one offline saved log that got uploaded to the server even twice:
First a few days ago (with correct date) and today again, with today's s date ... so it most definitely has been changed by the edit.
Nevertheless, disconcerting that the date in ``Logbook`` differs from the one in ``Details`` page ...

**Comment by eddiemuc** [comment]
This is mine of course. Will see to it immediately

**Comment by eddiemuc** [comment]
Very embarassingly I am currently reading the "update" field (containing the date where the offline log was last updated) into the "date" field (containing the date of the log). Also the unit tests were not designed to find this error (I used current date for testing). Both is corrected with PR #8954

**Comment by MagpieFourtyTwo** [comment]
Great! Thx a lot for the immediate reaction!
And no need to feel embarrassed, I (and I'm absolutely sure that I'm not the only one) really appreciate your work and personal commitment. Thx again!
