### ISSUE TITLE
Log.d() does no longer work on "activate debug log" setting

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8953]
**Describe the bug:**
Messages assembled with `Log.d()` do no longer get written to the logcat, even when Settings => System => Activate debug log is set.

**To Reproduce:**
- Delete or rename any `logfiles/log.properties` file (if existing)
- Activate Settings => System => Activate debug log
- Open any program part where a `Log.d()` is used (if needed: add your own `Log.d()` call before testing)
- Disable Settings => System => Activate debug log
- Write an extended log file using Settings => System => generate logfile

**Actual behavior/state after performing these steps:**
Messages generated by `Log.d()` are not present in the logfile.

**Expected behavior/state after performing these steps:**
Messages generated by `Log.d()` should be present in the logfile in this case.

**Version of c:geo used:**
Current `master` and `release` branch.

**Is the problem reproducible:**
Yes

**Additional context:**
Does work if an appropriate `log.properties` file exists with `logging.minlevel=DEBUG` setting, but this renders the "Activate debug log" setting useless (which should not be the case).

@eddiemuc: can you look into it?

**Comment by eddiemuc** [comment]
Sure

**Comment by eddiemuc** [comment]
Should be fixed with PR #8955

**Comment by moving-bits** [comment]
@eddiemuc 
Fix confirmed - thanks for patching this so quick!

**Comment by eddiemuc** [comment]
> @eddiemuc 
> Fix confirmed - thanks for patching this so quick!

Well it was my mistake, in a very central and important component no less...
