### ISSUE TITLE
Unified handling for backing up/restoring caches & settings

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8959]
Currently we have two backup functions: `settings` and `caches/waypoints`.

While often switching between developer/nightly build, I always have to do both backups which is quite annoying and also for normal users probably rather confusing.

So I would vote for combining these functions in the UI.

And if there are really users, who only want to import settings without database (or vice-versa) we can add two checkboxes where they could deselect one part of the backup while importing...

**Comment by rsudev** [comment]
The distinction came historically, as the database backup was implemented earlier, while the settings-backup came much later, because it contains sensitive personal data like passwords. Because of the latter I would rethink the automatic inclusion of the settings into the backup...

**Comment by fm-sys** [comment]
> Because of the latter I would rethink the automatic inclusion of the settings into the backup...

Currently we have following options:
- Backup
- Backup settings (without account data)
- Backup settings (full)

Even with including the settings into the "normal" backup we can still let the user choose if he/she wants to create the backup with or without account data

**Comment by MagpieFourtyTwo** [comment]
I support the proposal (@fm-sys in fact took the words right out of my mouth), cause just having a (static) tickbox ``[X] include account data`` (and probably even one for ``[X] overwrite old backup unconditionally``) would already save 4 clicks every day.  Moreover I would suggest to replace the OK-Message(s) by a toast, thus reducing even 6 backup clicks to just one.

BTW: Perhaps even the ``Backup / restore`` entry in main menu can be replaced by ``Create Backup``, making it way more easy to create a backup on the fly ...?

**Comment by moving-bits** [comment]
You do not need to backup your settings each time you switch between different versions of c:geo. In contrast to the database structure, the structure of the settings change very seldom. AFAIK the last change to the settings file's structure has happened several years ago, so the settings file stays compatible.

Thus it should be fine if you backup settings only once in a while, maybe once in a year, or after you have done significant changes.
Restoring settings' backup is only needed if you have uninstalled c:geo completely.

**Comment by moving-bits** [comment]
Besides the technical background described above:

I'd like to keep the files (cgeo.sqlite / settings.xml) separate, they serve very different objectives.

But still one could integrate backing up / restoring into a unified handling (with some checkboxes, though, the values of which should be remembered).

**Comment by MagpieFourtyTwo** [comment]
> Thus it should be fine if you backup settings only once in a while, maybe once in a year, or after you have done significant changes.

As for me: I like to keep things simple and straight. And it's in fact a no brainer, to just backup both, without the need of thinking about necessities. Esp. as my configuration changes from time to time (just take the colors and line widths, which are still subject to change, or the "last cache log"). And new settings are invented from time to time ... Moreover I like to have DB backup, settings backup and matching apk all together, so I am pretty sure to *always* be able to switch back to a most definitely working installation.

> Restoring settings' backup is only needed if you have uninstalled c:geo completely.

Which is usually the case when using a PR version once ... or if the currently nightly immediately crashes ... or ... ;)

To be honest: I can't remember a single DB restore, where a settings restore has not been necessary, too.

Nevertheless, I would keep these two in two different files as well, as it *could* be ... and it's better to be safe than sorry.  ;)

**Comment by fm-sys** [comment]
I started working on it. Some first screenshots (but it's still WIP... ):
![VID_20200916_215402](https://user-images.githubusercontent.com/64581222/93389670-c4cac180-f86c-11ea-992f-2c1151f716d9.gif)
![Screenshot_20200916_223136](https://user-images.githubusercontent.com/64581222/93389715-d318dd80-f86c-11ea-8a25-8133765fbcbd.jpg)

Whst do you think?

**Comment by moving-bits** [comment]
Two more ideas, while you are working on it :-)

1) Would it be possible to have more than one set of backup files? Currently backup is stored to `cgeo.sqlite` and `settings.xml` files in `backup` directory. This could be extended by adding a date- or date/timestamp to the filename, and offering a file (date?) selector on restore.

2) How about including the database version number to the filename? Would make it easier for testing to select the right database for restore. Eg: `2020-09-25 cgeo-86.sqlite` (or something like this)

**Comment by MagpieFourtyTwo** [comment]
*If* there will be a more elaborated way to backup and restore, I would not rename the files, but the directories, as ...

a) settings.xml should fit the sqlite backup
b) it would be easier to find/select matching pairs
c) you would have the opportunity to even put the matching apk into this directory

(which is pretty much the way, I perform my backups right now, but just manually, of course :) )

This way you're always able to go back to a fully working installation for sure.

My implementation approach would be to just backup as usual, but additionally ...

1. check if the backup directory already exists *and* contains a file of the type, the user just wants to backup
   (in order to make it possible to first save the sqlite and then the xml file)
2. if FALSE: just put the (additional) file into it and we're done.
2. if TRUE: rename the dir to "\<yymmdd hhmm backup>, according to the creation date of the backup file in it
3. create a new backup directory and put the new stuff into it.

Number of backup dirs to keep may be a setting ...? Or just endless ... and user does housekeeping himself.

**Comment by fm-sys** [comment]
> Would it be possible to have more than one set of backup files? Currently backup is stored to `cgeo.sqlite` and `settings.xml` files in `backup` directory. This could be extended by adding a date- or date/timestamp to the filename, and offering a file (date?) selector on restore.

Nice idea! I would like to finish the UI part first, but if I have time this will *maybe* follow *later* with a second PR... 

I'm thinking of a settings option "Keep old backups" which will just move the backup in a folder with the specific timestamp without involving customized UI components for the backup/restore process.
