### ISSUE TITLE
[Nightly] Edit of found log leads to new note

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8962]
**Describe the bug:**
I logged a found and sent it to GC. Then I went again to the log (offline) and added another picture. Storing it is was a Note with the same text as the found log.

**To Reproduce:**

**Expected behavior/state after performing these steps:**
Log should not be editable.

**Version of c:geo used:**
2020.09.06-NB-099d410

**Is the problem reproducible:**
Not yet, I will try on thenext days

**System information:**
```
--- System information ---
Device: MI 8 (dipper, Xiaomi)
Android version: 10
Android build: QKQ1.190828.002 test-keys
c:geo version: 2020.09.06-NB-099d410
Google Play services: disabled - 20.33.14 (120400-327249014)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (89,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (89,3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (89,3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (8,7 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---

```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

**Comment by eddiemuc** [comment]
Clarification question: after you sent the first log to GC
* could you still open/edit an offline copy of this log (which should not be possible)
* or did you open/create a new offline log, but the text of this log turned into the same as the previous one?

**Comment by geocachermgo** [comment]
I was able to edit (I tried to just add a new picture) the old log. I wanted to check if the exif is removed (which seems to be the case with a rescaled picture) and stored it and closed the cache. When I opened it again it was stored as a additional remark. I will try to reproduce it today (Have to find a new cache to log first)

**Comment by geocachermgo** [comment]
Are there dummy xaches that can be used for testing?

**Comment by moving-bits** [comment]
> Are there dummy xaches that can be used for testing?

Not that I know of. If you are not a cache owner on your own, you can use GC5X1CZ, which is one of my caches. The cache is still live, so it would be nice if you delete those logs after testing.

**Comment by geocachermgo** [comment]
Was reproducible (used new nighly 2020.09.07-NB-0542bf7)
Sequence: Log, add picture, send, switch off internet, swipe right to logs.
![Screenshot_2020-09-07-11-37-15-501_cgeo geocaching](https://user-images.githubusercontent.com/43813636/92373686-01751b00-f0ff-11ea-82c8-5e93d9dc9311.jpg)

**Comment by eddiemuc** [comment]
> Are there dummy xaches that can be used for testing?

You can create a new cache, but not publish that cache. That way you have a cache that only you can log to (but not all log types e.g. no "found" log possible) and no one else sees it

**Comment by rsudev** [comment]
> Are there dummy xaches that can be used for testing?
I have an archived cache 'GC3BG1K' you can use. I will periodically later remove any test logs.

**Comment by eddiemuc** [comment]
regarding the issue: I will look into it. opefully can do it this evening

**Comment by geocachermgo** [comment]
One Detail: Yesterday it was a found and a note, today there were two founds.

**Comment by eddiemuc** [comment]
PR #8967 should fix this

**Comment by geocachermgo** [comment]
Thanks!  Will it appear in the next nightly?

**Comment by eddiemuc** [comment]
First it needs to be merged to master. It will then appear in the next nightly build after that. 
Actually I don't know at what time the nightlies are usually build, so I can't tell for sure.

**Comment by geocachermgo** [comment]
Is it only in the nighlies or also in the beta? When is the the bug triggered? If it happens with every log somebody else must have seen it?

**Comment by eddiemuc** [comment]
It is only in yesterday's nightly and maybe the one before since I introduced it just two days ago. You found it pretty quickly :-)

It is not in release branch, so the beta is unaffected

**Comment by geocachermgo** [comment]
Still not working with the new nightly 2020.09.08-NB-00af738.
Merge to master was done 8h ago #8967 . Nightly was available about 6h ago, so it could be in. I don't know how to check if the fix included.

**Comment by eddiemuc** [comment]
Fix is in nightly, I will check this

**Comment by geocachermgo** [comment]
Can you explain to me, where its visible that the nightly build was started after the merge?

**Comment by eddiemuc** [comment]
I only know the "developer way". I go to Jenkins (this is our CI server where all the builds are located), navigate to nightlies and check which commits are included.
* Link to nightlies in CI server: https://ci.cgeo.org/job/cgeo%20nightly/ 
* On the left side you find the nightly builds. The one from last night is number 1917: https://ci.cgeo.org/job/cgeo%20nightly/1917/
* On this page you see the commits that were newly included

Actually, I don't even know where I can find the (installable) nightly builds. Can you tell me where those are?

And also: you closed this issue. Is it fixed after all or should I recheck?

**Comment by Lineflyer** [comment]
The nightly version number has an appended commit ID. That commit was HEAD when nightly was built.

Can be found in http://download.cgeo.org/cgeo-nightly.apk

**Comment by geocachermgo** [comment]
I get the nightly via the link in cgeo or http://download.cgeo.org/cgeo-nightly.apk

**Comment by eddiemuc** [comment]
Unfortunately I have no possibility to install and test the nightly. Commit should be included, and fix works on master as far as I can check it (have no emulator with working internet connection availale unfort.). Can do more only this evening.

**Comment by eddiemuc** [comment]
OK, this time hopefully PR #8975 will fix this. Sorry...
(I handled only the case of a previously saved log being sent in a second step (when reopening the dialog)). I did not handle the case of directly editing and sending in dialog in one step (without ever saving the log locally)

**Comment by Lineflyer** [comment]
I also experienced this today. I guess its the same problem:

- Use "fast offline log" - "Found" to record find
- Later open History list, use "fast offline log" - "Log visit" for the same caches to reaccess the log
- Send log online

After that I see two Offline and online in the logbook

Strangely it was ok with NB some days ago but with todays its not.
Will retest after PR is merged.

**Comment by geocachermgo** [comment]
Tested ok with 2020.09.09-NB-b8ea9a5
