### ISSUE TITLE
In 'NewMap', 'onStop' may lead 'historyLayer' to be always set to null in 'onSaveInstanceState' 

### ISSUE THREAD

**Issue by AICT20** [cgeo/cgeo#8965]
**Description**
From Android documents,  'onStop' will be executed before 'onSaveInstanceState'  in/after Adnroid API 28.
In Activity 'NewMap', 'onSaveInstanceState' saves the field 'historyLayer' while 'onStop' sets it to null, so 'historyLayer' is always saved to null in/after API 28

**Expected behavior/state after performing these steps:**
Maybe both side should be adapted(before API28 and in/after API 28), as from my own test,  'onStop' is still executed after 'onSaveInstanceState' on devices before API 28.

**Comment by eddiemuc** [comment]
Unclear whether this is a problem leading to wrong behaviour in c:geo, thus closing for now. 
Please reopen if still relevant?
