### ISSUE TITLE
Line wrap for long cache names in *all* cache lists

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8966]
Already have it in "Sort individual route" - and it's that good and informative over there,
that I would greatly appreciate, if we can have this in *all* cache lists.  :)

Thx!

**Comment by geocachermgo** [comment]
+1
![Screenshot_2020-09-07-21-32-54-849_cgeo geocaching](https://user-images.githubusercontent.com/43813636/92413752-cd771580-f151-11ea-8fd5-0729e7d4e00c.jpg)

**Comment by MagpieFourtyTwo** [comment]
What an improvement - thx a lot!

**Comment by geocachermgo** [comment]
We forgot to add GCCC88 as a test case, that also looks fine:
![IMG_20200920_145101](https://user-images.githubusercontent.com/43813636/93711810-7d388400-fb51-11ea-8e0b-8515d39b7bb0.jpg)
