### ISSUE TITLE
Allow projection of a wp with negative angles

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#8969]
A waypoint can be projected by giving a distance and angle. At the moment only positive angles are allowed.
Angles>360° are allowed and work fine. Eg. 450° works like 90°.
I'd like to be able to shift by -90° instead of 270°.

**Comment by geocachermgo** [comment]
@eddiemuc : I tried to find it in the code yesterday but I was lost. I browsed a little bit in cgeo/main/src/cgeo/geocaching. Can you tell me in which module the projection is done?

**Comment by eddiemuc** [comment]
From looking at the code I would guess:
* Reading out values from dialog is done here: `cgeo.geocaching.EditWaypointActivity.getActivityData()`
* Actual calculation is done here: `cgeo.geocaching.location.GeoPoint.project(distance, bearing)`

**Comment by fm-sys** [comment]
Maybe take also a look at `res/layout/editwaypoint_activity.xml` and `src/cgeo/geocaching/EditWaypointActivity.java`

**Comment by geocachermgo** [comment]
I think I found it (Thanks to fm-sys!) src/cgeo/geocaching/EditWaypointActivity.java
Line 38 : android:inputType="numberDecimal"
has to be changed to
android:inputType="numberDecimal|numberSigned"
Afaics the rest of the chain works.

**Comment by fm-sys** [comment]
@geocachermgo Feel free to provide a PR for this!

**Comment by eddiemuc** [comment]
@geocachermgo your guess was absolutely correct. As an apology for the problems with #8962 (I hope this time it will work...) I created the necessary PR #8976

**Comment by geocachermgo** [comment]
My first "you may call it a code contribution". Thanks for the support.

**Comment by geocachermgo** [comment]
Works fine! (and I'm the only one with the new nightly)
![Screenshot_2020-09-09-00-41-53-590_org mozilla firefox](https://user-images.githubusercontent.com/43813636/92534628-8eba8b80-f235-11ea-8a43-868061461df8.jpg)
