### ISSUE TITLE
Icon Creation recipe in Wiki: try out and translate

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#8979]
I want to create new icon buttons, in my case one with  camera symbol and one with a "multi-picture-select" symbol.
I found our very good wiki page https://github.com/cgeo/cgeo/wiki/How-to-create-custom-icons, leading me both to a very good source for avaible icons (https://material.io/tools/icons/) as well as a tool for conversion of icons to "android-ready drawables" (http://romannurik.github.io/AndroidAssetStudio/icons-actionbar.html)

However, I thing the manual is a bit outdated because I can't find some of the described elements in the android asset studio. 
What's worse, I was not able to create icon buttons using these tools which match the existing ones:
* visible in both light and dark mode
* sort of "white inside" with a "dark thin outline"

I noticed that there are different categories of icons on https://material.io/tools/icons/ (filled, outlines, two-toned etc) as well as different settings in the android asset studio (Theme/color settings, padding etc). I experimented a lot but could't find something creating me icons "matching" the existing ones (like e.g. the "add" cross or the "edit" pencil).

Is there anyone who can give me sort of a step-by-step-isntruction on how to convert an icon from e.g. the above website into a (set of) drawables ready for usage in c:geo?

Update: @fm-sys provided a recipe, this issue is a reminder to me to try it out and translate it to english in Wiki https://github.com/cgeo/cgeo/wiki/How-to-create-custom-icons

**Comment by fm-sys** [comment]
I'm also in need of this for #8898. Probably the current icons are filled with 60% white and surrounded by a black shadow with outwardly increasing transparency (but I also don't know how to create this shadow, maybe it is possible with GIMP?)

**Comment by fm-sys** [comment]
Just as a note: procedure is described in https://github.com/cgeo/cgeo/issues/8898#issuecomment-691806534, but maybe we can add it also to the wiki...

**Comment by eddiemuc** [comment]
@fm-sys I copied your explanation to the WIki page so it does not get lost (in german though). Maybe we can edit it later.

**Comment by geocachermgo** [comment]
Since the icons are there, should this issue be closed?

**Comment by eddiemuc** [comment]
I would like to leave it open as a reminder for me to try out the icon creation recipe given by @fm-sys and translate it to english on https://github.com/cgeo/cgeo/wiki/How-to-create-custom-icons . But I can rename it a bit to make that more clear

**Comment by eddiemuc** [comment]
Works fine! I adjusted the wiki page and am happy now. Many thanks to @fm-sys for providing this solution! :-)
