### ISSUE TITLE
remove old eclipse parts

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8980]
In the last years no changed code parts for eclise. Now this is all outdated.
Therefore I vote to delete this.

I think e.g. about
- code-copy for play-services-base, -basement, -location
- .derived
- .settings
- .classpath
- .project
- .externalToolBuilders
- project.properties
- launch
- .factorypath
- manifest.mf

What do you mean?

**Comment by moving-bits** [comment]
AFAIK nobody actively working on c:geo still uses Eclipse, so +1 for deleting old unused stuff.
(I don't know the directory structure for Eclipse, though.)

**Comment by fm-sys** [comment]
We should also update the readme where eclipse is still mentioned...

**Comment by bekuno** [comment]
> 
> 
> We should also update the readme where eclipse is still mentioned...

Yes, and the Wiki.

**Comment by bekuno** [comment]
readme and wiki are changed
