### ISSUE TITLE
no irclogs since 08.09. evening

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8986]
**Describe the bug:**
The c:geo ircbot did not join the channel after third restarting the channel on that day.

**Comment by SammysHP** [comment]
I will restart it when I'm back home. But you haven't missed anything, the channel is practically dead.

**Comment by bekuno** [comment]
@SammysHP Short reminder ...

**Comment by SammysHP** [comment]
Restarted.

@mucek4 Short reminder … ;)
