### ISSUE TITLE
Splash Screen while starting c:geo 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8988]
Opening c:geo on low budget devices can take 1-2 seconds without any visual feedback, so we should integrate a splash screen which is displayed while android loads the first activity.
Currently, `windowDisablePreview` is (probably) set, that's why we don't see a just black or white empty screen while c:geo is starting up (like in some other apps). 
However, we can also display the c:geo logo on startup, like it is also done by whatsapp or the official gs geocaching app.

Approach is explained here:
https://developer.android.com/topic/performance/vitals/launch-time#themed
https://android.jlelse.eu/the-complete-android-splash-screen-guide-c7db82bce565

Sidenote: Of course, I don't want to prolong the start unnecessarily, but just "beautify" the waiting time that is already there...

**Comment by moving-bits** [comment]
Closed with #9291
