### ISSUE TITLE
Request for Review: Wiki-Page about Logging

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9004]
Since I dealt a lot with Logging in last weeks I decided to write a WIki-page about it. Here it is:
https://github.com/cgeo/cgeo/wiki/Logging 
It is meant to address primarily developers and supporters.

This is a request for review for that page.

Also I want to use this issue to upload some images and files in include in this wiki page (since unfortunately this seems not to be possible directly in the wiki)

**Comment by eddiemuc** [comment]
Image and files:
![image](https://user-images.githubusercontent.com/6909759/93002439-684b6780-f537-11ea-848a-56f239dfc1cd.png)
[log-properties.txt](https://github.com/cgeo/cgeo/files/5213102/log-properties.txt)
[log-properties.txt](https://github.com/cgeo/cgeo/files/5213103/log-properties.txt)

**Comment by moving-bits** [comment]
Like it 👍, thanks for putting all this information together into one place.

**Comment by geocachermgo** [comment]
Looks good to me. I made a little typo edit.

**Comment by Lineflyer** [comment]
I will for sure take a look at it when back from vacation. 
This information is pretty helpful when testing and for user support. Thanks @eddiemuc for preparing it!!

**Comment by Lineflyer** [comment]
FYI: Created a new issue label "Wiki" to be able to filter issues dealing with documentation in our Wiki

**Comment by moving-bits** [comment]
This useful wiki page is online since quite some time, so let's close this issue. Thanks @eddimuc for preparing that page (and thanks for all other contributors to that page as well).
