### ISSUE TITLE
Empty line for caches which fit in one line

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9007]
Since the recent changes to have multi line cache names in lists also the entries with short cache names consume significantly more space on the screen. It looks like an empty line below the cache name or the cache name being centered between two rows.

While I like the feature to fully show long cache names without need to rotate, it is IMHO not nice, that now e.g. on my phone only 9-10 caches fit in although none of them has  a long name.
Was this designed like that on purpose or is it a bug?

2020.09.13-NB

**Comment by geocachermgo** [comment]
Unnecessay line breaks in the fine print also occur
![IMG_20200914_002241](https://user-images.githubusercontent.com/43813636/93030099-c6a04500-f620-11ea-95e6-4374c257eeb9.jpg)

**Comment by geocachermgo** [comment]
I made a list of short name caches to check the difference

 2020.09.14-NB-a332e45: shows 11 caches on my screen
![IMG_20200914_105031](https://user-images.githubusercontent.com/43813636/93065632-41954a00-f679-11ea-9ab2-c15935d82759.jpg)
RC: has13 caches
![IMG_20200914_105221](https://user-images.githubusercontent.com/43813636/93065617-3cd09600-f679-11ea-9c79-ae7c30a0526a.jpg)

**Comment by moving-bits** [comment]
> Was this designed like that on purpose or is it a bug?

This is a bug, which I've encountered during development as well, but which had vanished after some further changes. Strange behavior, as mostly I removed the `maxlines="1"` and `lines="1"` attributes, and even stranger with some other artifacts I had encountered, eg. even a single line cache title using two full lines (second line being empty), and the info boxes at the right aligning below that vertically...

Either way, I'll probably have to redo the whole `<RelativeLayout>` used for cache list items to find a working solution without those side effects.

**Comment by moving-bits** [comment]
I think I've found the reason behind this (but no 1:1 solution):
It looks like the `<RelativeLayout>` and a compound drawable (cache icon included in cache title) clash with allowing a multi-line title. For a single line, we force that the additional cache info is bottom-aligned to the surrounding box, actually overlapping the compound drawable. This does not work as expected when allowing more than one line of text.

The closest I could get to is the following, by separating cache icon and the two textual infos:

![image](https://user-images.githubusercontent.com/3754370/93137027-23f9cc00-f6dd-11ea-9380-cab21367aca9.png)

What do you think?

**Comment by MagpieFourtyTwo** [comment]
As for me: The comfort of being able to read the full cache name outweighs two or three entries less by far.
Esp. as this, to be fair, must be compared to the landscape view (which was the only possibility to do so till now),
And as "losing" just half of the name of an average list name would be even less "loss", so it's even better. At least for me.  ;)

BTW: Perhaps the free space left of the lists list ;) can perhaps be used for a more prominent list marker (which currently looks a little bit lost, esp, in conjunction with a found/dnf smiley) ...?

**Comment by geocachermgo** [comment]
> 
> What do you think?
Ok.for me. Where and how long is the green "found" bar, currently on the very left?

**Comment by fm-sys** [comment]
> What do you think?

Looks even nicer as before! 

> BTW: Perhaps the free space left of the lists list ;) can perhaps be used for a more prominent list marker (which currently looks a little bit lost, esp, in conjunction with a found/dnf smiley) ...?

Yes! I also think, they could be more visible. For the map I'm thinking of something like this
![Screenshot_20200915_063215](https://user-images.githubusercontent.com/64581222/93165843-69d68480-f71d-11ea-9c20-af20d7dbcbc8.jpg)

But for the lists I have no idea currently... But we should create a new issue for this!

**Comment by geocachermgo** [comment]
Thanks to @moving-bits! I'll try this and the other changes when the continous build has finished.

**Comment by moving-bits** [comment]
> Where and how long is the green "found" bar, currently on the very left?

In PR #9016 you'll find a screenshot which includes an offline log. Marker is left-most (if no checkboxes are shown), full-height.

**Comment by geocachermgo** [comment]
Looks much better now 12.5 caches now
![IMG_20200919_125029](https://user-images.githubusercontent.com/43813636/93665445-db446900-fa76-11ea-8fc5-70cb2df7b516.jpg)

Suggestion: Since GC-Code D T Size Offline is taking almost the complete line, can we compress it?
e.g instead of D 1.5 • T 1.5
 D1.5 • T1.5 or DT 1.5/1.5 
and/or Symbol for size maybe combined cf.
![IMG_20200919_124838](https://user-images.githubusercontent.com/43813636/93665443-d41d5b00-fa76-11ea-93c7-faee4be1131b.jpg)
and/or symbol for offline 
![IMG_20200919_125351](https://user-images.githubusercontent.com/43813636/93665500-35452e80-fa77-11ea-9315-45254fa5571d.jpg) and premium?
![IMG_20200919_130903](https://user-images.githubusercontent.com/43813636/93665754-61fa4580-fa79-11ea-9be1-1ceb6d424f48.jpg)

**Comment by MagpieFourtyTwo** [comment]
Just my 2 cent: Symbols are great - if you know what they mean. But as most probably most of the cachers do not use c:geo on a daily basis (at least most of which I know), more descriptive text will be better now and then, even if you loose some space.

Had this thought already with the two symbols regarding personal note for "Save/refresh waypoints" and "Remove waypoints", which are not really that obvious to non-power users. 

So, esp over here, where clearness "understandability" would be decreased for just saving the space for probably one or two caches more per scroll, I would stay with text ... (as well as for functions, that are not really obvious to the "now and then" users). Cause better "wasted" dinner space, but created an easy interface, than just use possibly cryptic symbols (for some people) who then will never ever use this function (thus even the less used space is completely wasted for them).

**Comment by geocachermgo** [comment]
Still some unnecessay line breaks in list "All" after "Offline". I would say that in case "Offline" should not be there, because there are other lists given.
![IMG_20200919_162811](https://user-images.githubusercontent.com/43813636/93669552-469d3380-fa95-11ea-8dbc-0be4b2e0b552.jpg)
![IMG_20200919_162633](https://user-images.githubusercontent.com/43813636/93669565-63d20200-fa95-11ea-921e-ced7ba4629b8.jpg)

**Comment by moving-bits** [comment]
One could replace "Premium" with "$$", saving a few chars.
For "Offline" I have no idea at hand how to make it shorter.

I would leave the info about further lists starting in a separate line, even if it's taking up some extra space - but it's easier to understand (and distinguish from the info before) this way, IMHO.

**Comment by MagpieFourtyTwo** [comment]
> One could replace "Premium" with "$$", saving a few chars.

I would prefer "Prem." or alike. Don't want to be reminded of this payment every single time. Or perhaps "PMS" ? For Premium MemberShip, of course! ;)

> I would leave the info about further lists starting in a separate line

+1

**Comment by Lineflyer** [comment]
> One could replace "Premium" with "$$", saving a few chars.

I would leave all of this information unchanged. I personally dont like apps which use abbreviations I might not understand.

**Comment by moving-bits** [comment]
> I would leave all of this information unchanged. I personally dont like apps which use abbreviations I might not understand.

Generally agreed to. One tiny idea to save some space: We could skip the "Offline" textual info if we add the "stored" symbol (floppy disc) to the cache icon. This would be the same symbol as is used on the map.

**Comment by moving-bits** [comment]
Let's continue the discussion in the newly opened #9029
