### ISSUE TITLE
Make list marker more visible

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9010]
> BTW: Perhaps the free space left of the lists list ;) can perhaps be used for a more prominent list marker (which currently looks a little bit lost, esp, in conjunction with a found/dnf smiley) ...?

Yes! I also think, they could be more visible. For the map I'm thinking of something like this
![Screenshot_20200915_063215](https://user-images.githubusercontent.com/64581222/93165843-69d68480-f71d-11ea-9c20-af20d7dbcbc8.jpg)

But for the lists I'm not sure... Does anyone have a good idea? Maybe we could display larger dots below the cache icon (on same height as D/T, size, etc.)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/9007#issuecomment-692457774_

**Comment by MagpieFourtyTwo** [comment]
> Maybe could display larger dots below the cache icon (on same height as D/T, size, etc.)

That is what I was thinking of ...

**Comment by fm-sys** [comment]
Fixed in a slightly different way with #9748 and #9790. Larger "list markers" can now be set as cache icon...
