### ISSUE TITLE
[Nightly] visiteddate=0 for all caches in database

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9011]
**Describe the bug:**
I have a list for the found caches. Normally I have distance sorting. If I go to that list and change the sorting to Log-Date only the first entry becomes the most recent log, all other entries stay in distance order.
I added another recently logged cache: this is also sorted correctly.

It looks link most of the "old" caches in my fould list seems to have no log date or they have all the same log date.
Can the internal logdates get lost during backup/ restore of the database?

Version:
2020.09.15-NB-adcf656

I have aSQLite Manager installed and can look up things. But I have only limited SQL knowledge.

**Comment by geocachermgo** [comment]
I try to get to date of my logs by
select * from [cg_logs] WHERE [cg_logs].[geocode]=GCF014
But the WHERE condition is wrong, I get the result:
android.database.sqlite.SQLiteException: no such column: GCF014 (code 1 SQLITE_ERROR): , while compiling: select *
from [cg_logs] WHERE [cg_logs].[geocode]=GCF014 limit 20 offset 100
@MagpieFourtyTwo can you help?

**Comment by eddiemuc** [comment]
Try this one: `select *
from cg_logs WHERE geocode='GCF014'`

**Comment by geocachermgo** [comment]
; was missing too. Now it works!

**Comment by eddiemuc** [comment]
But if you are looking for the date where you yourself visited the cache, this is stored in `cg_caches`, I think in field `visiteddate` (haven't checked it)

**Comment by geocachermgo** [comment]
in cg_logs.date there is the correct date of the found (even with some pm time instead of 00:00) but 
cg_caches.visiteddate=0.
With the caches that are sorted correctly there is a valid visiteddate. So c:geo works fine only the database is corrupted
Only open question: how the date was erased. I'll check the older backups ...

**Comment by eddiemuc** [comment]
And if you are wondering how to convert the numbers in date columns to "real dates", try this:

`select geocode, date(visiteddate/1000, 'unixepoch', 'localtime') from cg_caches where geocode = 'GCF014';`

**Comment by geocachermgo** [comment]
That was easy, I used https://www.unixtimestamp.de/

**Comment by eddiemuc** [comment]
Regarding the bug: I think your personal visiteddate is only stored in c:geo if at some point it is in the recent logs of the cache when you use it in c:geo, since c:geo only ever loads the most recent 30-or-so logs of a cache. It may thus not be filled for several reasons:
* If you logged it outside of c:geo, and at first time you loaded into c:geo there were already more than 30-or-so newer logs on the cache
* At some point you lost your c:geo DB or you deleted it completely. when Caches are restored from server, only for those caches you found where no more than 30-,or-so logs have been logged since you found it the visiteddate is restored

This is what I assume, but I haven't checked it, neither by test nor in code

**Comment by geocachermgo** [comment]
In the database from 2020-09-01 the visiteddate are ok (half with visiteddate, half without). In the backup today and 2020-09-14 almost all caches have visiteddate=0) just a few a newly loged or loaded have a correct visiteddate.
==> At some point during save/restore the visited date got lost.
@eddiemuc one of the caches with a correct date is one which I loaded and my log is >5 y old. I guess the logs of yourself (and friends) will be updated independed of age.
I had also installed the RC in between.
Since it seems to work fine with a correct db I think I'll close this issue. I think its impossible to investigate how the visiteddate got lost.

**Comment by MagpieFourtyTwo** [comment]
@eddiemuc 
> since c:geo only ever loads the most recent 30-or-so logs of a cache

Thought so, was well, but au contraire, the numbers tell a different story: I in fact have about 1,5k caches with more than 35 logs (which seems to be the standard, although friend's logs may play a role over here, too), nevertheless, 20 have more than 50 and one has even 104 logs ... but this is an OC cache, where it possibly is not possible to limit the number of logs loaded (these 104 are *all* logs).

My theory: c:geo loads logs of found caches until the own log is found. Same perhaps applies to friend's logs ...?

@geocachermgo:
Don't want to be offensive, but IIRC this is not the first you're considering your DB corrupted - what for heaven's sake are you doing to her ...?  ;)

**Comment by geocachermgo** [comment]
The last time it was the problem with the DB version and since it was found and fixed I  consider it a valid contribution to the c:geo improvment.
I just reloaded all the found caches (ignored the warning regarding high traffic) now all the caches I visited seem to have a visiteddate again.

**Comment by geocachermgo** [comment]
> @geocachermgo:
> Don't want to be offensive, but IIRC this is not the first time you're considering your DB corrupted - what for heaven's sake are you doing to her ...? ;)

Just saving and restoring (with nightlys).
Is a database female like a vessel?

**Comment by MagpieFourtyTwo** [comment]
> Is a database female

For me it appears to be: Cause you have to talk to her in a very special way. And if you choose just one wrong word, you will not get any information at all - not counted the rare cases where you may fortunately at least get a cryptic hint, which you will most probably misinterprete, thus will be forced to just try&error until you get a lucky face again, ahem, the desired response. :stuck_out_tongue_winking_eye:

**Comment by geocachermgo** [comment]
If you load a cache once you get 35  logs + own logs + friends.
I guess if you update it 100 logs later you will get additionally the newest 35 logs.

**Comment by MagpieFourtyTwo** [comment]
> I now just reloaded all the found caches (ignored the warning regarding high traffic) now all the caches I visited seem to have a visiteddate again.

As this seems to be "solved", we can close it, right?

**Comment by geocachermgo** [comment]
Since the problem has shifted from "sorting does not work" to "some time ago the visiteddate got lost" which is still unsolved but is
- unreproducible
- nearly impossible to find the root case
I close this issue.
