### ISSUE TITLE
[Nightly] Improve explanation text of "FoundCount +x" popup

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9013]
Topic deals with the popup, which appears after the first start of c:geo after upgrading to the version which contains the "+x" behind the cache found count in the footer of c:geo's main screen: 

![Popup](https://user-images.githubusercontent.com/9889015/93458381-840c9000-f8e0-11ea-9279-f4607a396a27.jpg)

When I saw this popup the very first time, I thought it could be hard to understand esp. for somebody who never ever had seen the "+" before or even has paid attention to this counter at all. So I would be a bit more descriptive like:

```
You have some caches with an offline saved log,
which are not yet uploaded to geocaching,com.
For your comfort the count of these logs is now
displayed as "+x" behind your number of found
caches in the footer at c:geo's main page.

Moreover these "x" logs will be added to the
"[NUMBER]" template in your log signature.

If you don't like this new counter extension,
you can disable it under "Settings" => "Logging"
and/or use the "[NUMBER (without offline logs)"
template instead.

To easily find remaining offline logs, go to the
list "History" and filter for "With personal data
 => "With offline log".

[_] Don't show this message again     [OK]
```

As most of the users will not know what this will mean, I would add the ``Don't shown again`` marker.
This way they have the chance to see the counter at least once and then read again.

**Comment by MagpieFourtyTwo** [comment]
From @alan666notb's [comment](https://github.com/cgeo/cgeo/pull/8960#issuecomment-694147156):

> Is it possible to add a "See them now" button?
> i.e. go to the history list with the correct filter already set up.

**Comment by MagpieFourtyTwo** [comment]
German Version may be:
```
Du hast einige Caches mit Offline gespeichertem Log,
die noch nicht zu geocaching.com hochgeladen wurden.
Um es Dir einfacher zu machen, wird die Anzahl dieser
Logs nun in der Fusszeile von c:geo's Startseite als
"+x" hinter der Anzahl Deiner Cache Funde angezeigt.

Ausserdem werden diese "x" Logs zum Wert des "[NUMBER]"
Templates in Deiner Log Signatur hinzugerechnet.

Wenn Du diese Zähler-Erweiterung nicht magst,
kannst Du sie unter "Einstellungen" => "Loggen"
deaktivieren und/oder in Deiner Log Signatur das
Template "[NUMBER (ohne offline logs)" verwenden.

Um Dir die Offline Logs anzeigen zu lassen, gehe in
die Liste "History" und filtere nach "Mit eigenen
Informationen" => "Mit Offline Logs".

[_] Nicht erneut anzeigen          [OK]
```

**Comment by fm-sys** [comment]
The `Don't shown again` marker is already implemented in a slightly different way:
![Screenshot_20200917_131538](https://user-images.githubusercontent.com/64581222/93463747-78bd6280-f8e8-11ea-845c-8bef9d4f15bf.jpg)
Is it enough or should we make it a bit more difficult to don't see the message again? 

> ```
> Du hast einige Caches mit Offline gespeichertem Log,
> die noch nicht zu geocaching.com hochgeladen wurden.
> ```

The suggested explanation sounds really good at all, but I would leave out `geocaching.com` as the same message is although relevant for all other geocaching services. 

> Is it possible to add a "See them now" button?

As this message should only be read once, I don't know how useful it would be. We more want to teach the users finding their offlinelogs by themselves ;-)

**Comment by MagpieFourtyTwo** [comment]
> Is it enough or should we make it a bit more difficult to don't see the message again?

I would make it a tick field, as esp buttons in the lower right are usually immediately clicked without even looking at them.
This has become kind of a Pawlow reflex - a consequence of all those messages, Jon Average get's day for day over time.  :/

> I would leave out geocaching.com

Yes, you're of course right, so should be changed to "server" or alike.

>> Is it possible to add a "See them now" button?

> As this message should only be read once, I don't know how useful it would be. We more want to teach the users finding their offlinelogs by themselves ;-)

Yep, thought the same, but just did not want to censor ...  ;)

**Comment by MagpieFourtyTwo** [comment]
> Yes, you're of course right, so should be changed to "the server" or alike.

Whilst "upload" is in fact not completely right, as even if uploaded as fieldnotes and logged "on the server" ;) in c:geo they will still count as "Offline logs" (distorting [NUMBER] again) until you refresh the offline saved copy of the cache ... but in fact I don't know how to phrase it better ... esp. in short ...  :/

**Comment by fm-sys** [comment]
In addition, I would keep the message neutral, in other words not introduce it as a new function, as the message will also be displayed on new installations, who do not know it any different...

**Comment by MagpieFourtyTwo** [comment]
Ok, so eliminate the words "now" and "new" ...  ;)

**Comment by Lineflyer** [comment]
I would also suggest the wording "might not yet be logged online" as the most probable reason of users being unaware of offline logs still being stored is, that they have a different logging flow: Log offline in c:geo -> upload field note or simply log from browser -> delete the cache in c:geo wrongly assuming that this also deletes the offline log.

So it could be, that everything is already logged online.

**Comment by fm-sys** [comment]
![Screenshot_20200917_171905](https://user-images.githubusercontent.com/64581222/93491775-62280300-f90a-11ea-9a22-4eb105fa277a.jpg)
The new onetime dialog design will look like this (Text not jet changed)

**Comment by moving-bits** [comment]
> > Is it enough or should we make it a bit more difficult to don't see the message again?
> 
> I would make it a tick field, as esp buttons in the lower right are usually immediately clicked without even looking at them.
> This has become kind of a Pawlow reflex - a consequence of all those messages, Jon Average get's day for day over time. :/

This does not make any difference in program behavior compared to the currently implemented solution: In both ways you will close the dialog by pressing the button in the lower right, and in both implementations the popup will reappear on next program start. [That's why we have the "non destructive" button in the bottom right, and moved the other button to the left - say hello to Pawlow ;-)]

The specific dialog will only be disabled if you either tick the checkbox (proposal) or push the button in the bottom left (current implementation).

**Comment by fm-sys** [comment]
I totally agree with you @moving-bits, at first I had the same thought while reading...

But the checkbox proposal has two advantages:
1. More known from other apps
2. It's easier to use it in other contexts. For example, I want to make it possible hiding the warning message `"Do you want to overwrite the existing backup from %s?"` via this checkbox dialog, while I'm refactoring the backup workflow...

In addition, at least two clicks are required for the checkbox proposal - a slightly bigger challenge ;-)

**Comment by MagpieFourtyTwo** [comment]
BTW: Where is the tick "[X] Do not show again" stored? Haven't found a setting for it ... just in case someone wants to see it (again).
And, IIRC there was the proposal to show the message after clicking the "+x" - is this still an option or was it tilted already?

**Comment by fm-sys** [comment]
It is stored in the `cg_extension` table, even if I agree that it is more a setting. But it is way easier to store and handle the current show status (and show status for next restart) of multiple dialogs in the db then in settings... 

Btw: We can think about a settings option for resetting all dialog statuses.

**Comment by MagpieFourtyTwo** [comment]
> Btw: We can think about a settings option for resetting all dialog statuses.

Such as?

**Comment by fm-sys** [comment]
Hide/Show for all dialogs (currently only one, but some other dialogs will probably follow over time...)

**Comment by MagpieFourtyTwo** [comment]
Meant: Which dialogues apart from this one, as I did not remember any.
But in the meantime a second one came into my mind: What about the change log ...?
And possibly may be the "Overwrite previous backup" question?

**Comment by fm-sys** [comment]
> And possibly may be the "Overwrite previous backup" question?

I had the same thought some days ago. Will be part of #8959...

> What about the change log ...?

For the changelog I don't think it would be useful. Or maybe I misunderstood it? Did you mean *show the same changelog again* or *hide further changelogs*?

**Comment by MagpieFourtyTwo** [comment]
> Did you mean show the same changelog again or hide further changelogs?

Meant to show it again. But in fact you can always have a peek at "About c:geo" => "Changelog", so it's redundant.

**Comment by Lineflyer** [comment]
> For the changelog I don't think it would be useful. Or maybe I misunderstood it? Did you mean show the same changelog again or hide further changelogs?

For the changelog we AFAIR already a mechnism in place, which shows it on startup only if the content changed since last time it was shown. IMHO we should keep it like that.
