### ISSUE TITLE
Modify strings for log upload progress

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9018]
We should slightly modify the existing source strings for the log upload as it currently uses the singular form of photo/picture but users can now upload more than one pic.

Lets do it on master only to avoid necessity of backporting strings to release. Its only for perfection but no real issue.

**Comment by moving-bits** [comment]
You mean something like this: #9021?

**Comment by Lineflyer** [comment]
Yes, #9021 would be the basic solution, but it might not be easily to be translated in some language. 
Can't we use plurals here (if we have the information how many pictures are attached).
But again: Dont but too much effort into it. Not a real bug. We could also always use the plural.

BTW:There is s second string some lines further down "Sending image".

**Comment by moving-bits** [comment]
> Yes, #9021 would be the basic solution, but it might not be easily to be translated in some language.
> Can't we use plurals here (if we have the information how many pictures are attached).

We don't have the number of images attached available in the place where the string is needed, so I stayed with the more generic form to keep it simple.

> But again: Dont but too much effort into it. Not a real bug. We could also always use the plural.

Ok, I'll change it to plural only to make translation easier/consistent.

> BTW:There is s second string some lines further down "Sending image".

Thanks, will adapt that one, too.
