### ISSUE TITLE
Improve handling of pics embedded in cache listing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9019]
**Is your feature request related to a problem?**
Sometimes I stumble upon caches, where owners put the listing text into pictures or similar usage of images as main information source. 
Perfect example: GC7B8FC

**Describe the solution you'd like**
Easy method to zoom these listing images

**Describe alternatives you've considered**
Using the example cache above the only solution I found was to swipe to image tab,scroll down completely and click on listing image to enlarge then in external app.

**Comment by moving-bits** [comment]
Wouldn't this be covered by the new image gallery, allowing to zoom each image easily?

**Comment by Lineflyer** [comment]
Yes, that should be sufficient.

**Comment by fm-sys** [comment]
It would still be nice to open images in our zoomable image activity when clicking on them inside the listing.
