### ISSUE TITLE
Mention "wp from notes will be recreated" in confirmation dialog

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9026]
Taken from https://github.com/cgeo/cgeo/issues/8994#issuecomment-695202219 by @geocachermgo:

Remark from testing: Works a little strange if I have have "extract waypoint from note" active:
Everything is removed.
If you switch off "extract" and on again, the waypoints from the note are there again.
If you manually delete a waypoint, it is immediately recreated.
If the note is edited the re extract happens. If you reload the cache too.
Not if you open it for editing and cancel.
Options: 
1) Additionally switch off "extract" and note that in the warning
 2) Keep behavior but note that immediate re extract is blocked but will happen later
3) Allow immeadiate re extract (analogous to manual delete) and mention that in the warning " If you don't want to re-extract you have to switch-off extract or clear note"

My preference would be 3) followed by 1) 2)

**Comment by geocachermgo** [comment]
Will you also change the behaviour so that they are immediatly recreated?

**Comment by moving-bits** [comment]
> Will you also change the behaviour so that they are immediatly recreated?

just added this to the existing PR

**Comment by geocachermgo** [comment]
Is not working correctly: if I have a list of waypoints in the notes, delete all waypoint: the display of the list is correctly not reduced (if notes are unaltered) or reduced (if # of wps have been reduced in the notes). But if I go to the map or close the cache and reopen it: all waypoints are gone.
