### ISSUE TITLE
unnecessay line breaks in list "All" after "Offline"

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9029]
Still some unnecessay line breaks in list "All" after "Offline". I would say that in case "Offline" should not be there, because there are other lists given.
![IMG_20200919_162811](https://user-images.githubusercontent.com/43813636/93669552-469d3380-fa95-11ea-8dbc-0be4b2e0b552.jpg)
![IMG_20200919_162633](https://user-images.githubusercontent.com/43813636/93669565-63d20200-fa95-11ea-921e-ced7ba4629b8.jpg)

_Originally posted by @geocachermgo in https://github.com/cgeo/cgeo/issues/9007#issuecomment-695220604_

**Comment by moving-bits** [comment]
Just for documentation: Already discarded ideas: (see discussion in #9007)
- abbreviate "Premium" to "$$" or "Prem."
- use symbols instead of textual information
- merge the two info lines into one
- leave out "Offline" completely, if there are further offline lists

---

Current point in discussion: (copied from https://github.com/cgeo/cgeo/issues/9007#issuecomment-695756167)
> I would leave all of this information unchanged. I personally dont like apps which use abbreviations I might not understand.

Generally agreed to. One tiny idea to save some space: We could skip the "Offline" textual info if we add the "stored" symbol (floppy disc) to the cache icon. This would be the same symbol as is used on the map.

**Comment by Lineflyer** [comment]
> Generally agreed to. One tiny idea to save some space: We could skip the "Offline" textual info if we add the "stored" symbol (floppy disc) to the cache icon. This would be the same symbol as is used on the map.

I dont't fully understand the discussion. We came from a good working implementation until the new feature was merged to show long titles in two lines.
There seem to be several regressions caused by that, so either we just solve these regressions (without cutting off older features, working modes, strings) or we might also decide to revert this new feature (I can also live with tilting my phone or opening cache details in case of long names.

**Comment by bekuno** [comment]
The "Stored" symbol is already used in the "History" list.
I think that using it instead od the "Offline" text is fine and worth to become a general use.

**Comment by geocachermgo** [comment]
> I dont't fully understand the discussion. We came from a good working implementation until the new feature was merged to show long titles in two lines.
> There seem to be several regressions caused by that, so either we just solve these regressions (without cutting off older features, working modes, strings) or we might also decide to revert this new feature (I can also live with tilting my phone or opening cache details in case of long names.

The problem was, that the cache names were truncated.
That was solved and appreciated.
Of course it needs more space and there is a discussion how to mitigate this. Discussion settlement goes in the direction of changing nothing exept maybe replace the text "Offline" by a symbol or omit it.
Then there were some minor flaws (e.g. the linebreak from the issue title)
I won't name this regressions. The current state is usable and an improvment. No need to revert.

**Comment by moving-bits** [comment]
No regressions left, AFAIK, only a trade-off between readability for long titles and space needed for it. The current discussion is about how to mitigate that a bit.

**Comment by MagpieFourtyTwo** [comment]
> The "Stored" symbol is already used in the "History" list.
> I think that using it instead od the "Offline" text is fine and worth to become a general use.

+1

**Comment by Lineflyer** [comment]
> The "Stored" symbol is already used in the "History" list.
> I think that using it instead od the "Offline" text is fine and worth to become a general use.

We had this discussion some years ago (or maybe still in another open issue?) and AFAIR the majority of the team at that time was against it, as on normal stored lists the icon would be on all list items. On the history list and list of a map it was implemented at that time, because these lists may contain a mixture of saved and unsaved items.

But its the same for the text (only less prominent). So I am in favor of the icon solution and  removing the "offline" text. BTW: If we decide to do so, we should also remove it from the lists created from map (Map -> View as List) as there it is currently still shown in addition to the icon.

**Comment by MagpieFourtyTwo** [comment]
> as on normal stored lists the icon would be on all list items

Don't see a real argument reading this, as in the status quo, all entries show the word "Offline", which is at least as superfluous as the icon would be, when displaying the content of a list.

**Comment by MagpieFourtyTwo** [comment]
I know, one could even place a new issue for this, but as I consider this a really small change plus the height is s/th that has been changed in this context, we can perhaps talk about it over here, and if it's considered really necessary, I would even open a new issue for it:

>> Where and how long is the green "found" bar, currently on the very left?

> In PR #9016 you'll find a screenshot which includes an offline log. Marker is left-most (if no checkboxes are shown), full-height.

Can the height of this marker be a little bit less than the complete height? As with consecutive found or offline logged caches (which is pretty usual in appropriate lists), the separation between rows gets a little bit lost with full height ...
Moreover, with a waterfall display, the found bar looks a little bit lost, is even harder to see in the edge (with some phone covers it even completely disappears), so what about making it wider? Perhaps even double the width? This would additionally make it easier to distinguish between "Found" and "Offline Log" (esp. for guys with a slight color vision disorder, which in fact are about 10 % of all men).

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 
Have a look at #9035

**Comment by MagpieFourtyTwo** [comment]
> Just for documentation: Already discarded ideas: (see discussion in #9007)
> 
>   - abbreviate "Premium" to "$$" or "Prem."
>   - use symbols instead of textual information
>   - merge the two info lines into one
>   - leave out "Offline" completely, if there are further offline lists

What happened to the proposal to drop the blanks in "D 5.0" resp. "T 5.0"?
Then, in combination with #9036, there should not happen any "unwanted" line breaks anymore, hopefully.  ;)
Even with (currently) longest GC Codes *and* container type "Sonstige" .... (which is the longest I remember right now).

**Comment by fm-sys** [comment]
Btw. it would look better, if the distance is vertically aligned instead of being squeezed to the upper edge...

**Comment by MagpieFourtyTwo** [comment]
> it would look better, if the distance is vertically aligned

Vertically aligned may be problematic, if you have ticked ``Cache Details`` => ``Show Direction``.
Nevertheless, would be great if the distance could be vertically aligned with the (first line of) the cache name.

**Comment by geocachermgo** [comment]
Floppy symbol works. But I found an unnecessay line break after "Premium". 
![IMG_20200923_065655](https://user-images.githubusercontent.com/43813636/93968719-8d777b80-fd6a-11ea-9cdf-6183d4306404.jpg)

**Comment by geocachermgo** [comment]
Additionally the list of lists is incomplete "BiBi" is missing.
![IMG_20200923_070503](https://user-images.githubusercontent.com/43813636/93969086-58b7f400-fd6b-11ea-968e-951dd2ae39fe.jpg)

**Comment by bekuno** [comment]
> Floppy symbol works. But I found an unnecessay line break after "Premium

Thats fine so, imho. Lists should start with a separate line.

**Comment by geocachermgo** [comment]
I see. There is also no •
If this is intentional then I'll close the issue and make a new one for the missing list.

**Comment by moving-bits** [comment]
> Floppy symbol works. But I found an unnecessay line break after "Premium".

This is intended - we have two separate lines:

First line is about GC code, D/T rating, container type, and maybe premium. Used to contain the "offline" info before the recent change to show the floppy disk symbol instead.

Second line is about lists into which this cache is sorted into. This line is only shown if c:geo is configured to do so. This is a separate line intentionally, as it contains a completely different set of infos.

**Comment by moving-bits** [comment]
> Additionally the list of lists is incomplete "BiBi" is missing.

I guess the first screenshot is a listing of all caches in the "BiBi" list?

Because the currently shown list is not included into the second line as this information would be a duplicate. So second line reads "all other lists this cache belongs to", not "all lists this cache belongs to".

**Comment by geocachermgo** [comment]
Yes, it was the BiBi list. Issue closed because findings are intentional features.
