### ISSUE TITLE
c:geo show incorrect number of finds when using template NUMBER

### ISSUE THREAD

**Issue by boyank** [cgeo/cgeo#9032]
**Describe the bug:**
c:geo show incorrect number of finds when using template NUMBER in log.

**To Reproduce:**

In Settings->Logging->Signature add [Number] placeholder/template in order to show number of finds after submitting the log.
In any cache listing try to submit log via Log Visit

**Actual behavior/state after performing these steps:**
According to [User Guide](https://cgeo.droescher.eu/en/mainmenu/settings#placeholder_templates) NUMBER:

>Your  current find count for the respective geocaching platform, where the  cache you are logging belongs to, incremented by 1, thus providing the  find count for the cache you are logging.

In my case there is discrepancy of 4 - at the moment my next find will be 1498, but it show 1502.

**Expected behavior/state after performing these steps:**
Show correct number - 1498

**Version of c:geo used:**
2020.09.02-RC

**Is the problem reproducible:**
Yes, but I guess it may depend on particular user and what extra numbers it includes in the count.

**System information:**
```
--- System information ---
Device: EVA-L09 (EVA-L09, HUAWEI)
Android version: 7.0
Android build: EVA-L09C432B395
c:geo version: 2020.09.02-RC
Google Play services: enabled - 20.36.14 (040408-331796208)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (1.9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1.8 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1.8 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1.8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: dd/MMM/yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---
```

**Comment by Lineflyer** [comment]
You are using our beta version, where we introduced a new offline find count.
Please take a look at your homescreen, whether the find count behind your user name shows any +x number.

In that case you have offline logs (maybe accidentally) still stored. That would explain why [NUMBER] now uses a higher value.

You can find old offline logs if you open the list "history" and filter "With own information" - "With offline logs".

We already added an explanation to the next release, to explain this to users and help them find those offline logs.

**Comment by boyank** [comment]
Yes, you are right - there are stored listings with offline logs. I looked at the changelog before submitting the issue, but somehow missed it.

**Comment by murggel** [comment]
Mentioned on c:geo-booth at Event [Tanz auf den Vulkanen](https://coord.info/GCATPRH)
Probably the same reason for the user, having offline logs?
Alternative: use the [ONLINENUM] template instead, which will ignore all cgeo offline logs... (taken from #10007)
