### ISSUE TITLE
TB logbook not parsed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9038]
Our CI has a failing test:
https://ci.cgeo.org/job/cgeo%20pull%20request/3621/testReport/junit/cgeo.geocaching/CgeoApplicationTest/testSearchTrackable/

Indeed I can reproduce, that the logbook entries for travelbugs are not parsed/shown with current nightly.

**Comment by Lineflyer** [comment]
Also reproducible with 2020.09.02-RC. I suspect a website change.

**Comment by MagpieFourtyTwo** [comment]
Same over here with 2020.09.22-NB-c4f1a1c
And even on gc.com I see a "problem" with GC Little Helper: The date is not colored anymore, which is pretty strange.

![TB-Logs](https://user-images.githubusercontent.com/9889015/93927984-e9fe7a80-fd19-11ea-8d06-7d2af670cace.jpg)

**Comment by bekuno** [comment]
Found it (sample):
~~~
<tr class="Data BorderTop ">
    <td width="105">
        <img src="/images/logtypes/48.png" width="16" height="16" alt="Discovered It" title="Discovered It" />&nbsp;22/09/2018
    </td>
~~~
was changed to
~~~
<tr class="Data BorderTop ">
    <th class="travel-log-table-header" width="105">
        <img src="/images/logtypes/48.png" width="16" height="16" alt="Discovered It" title="Discovered It" />&nbsp;22/09/2018
    </th>
~~~
(and similar text)

I will make a PR tomorrow.
