### ISSUE TITLE
Shorten default strings for WP names

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9041]
**Is your feature request related to a problem?**
Default waypoint names like e. g. "Stage of a Multicache 1" are too long in some contexts, like e. g. in map popup of a waypoint - there you can not see, which waypoint you currently tapped, as the important part is "out of sight".

This is an in fact pointless loss of information, as the middle part "of a Multicache" has no significance at all and can safely be omitted (even more as even in Traditionals and Mysteries a "Stage" will always be named "of a Multicache").

**Describe the solution you'd like**
In order to make the significant part of a WP name visible in possibly all contexts, the (default) strings should be shortened:
- Parking Area => Parking
- Question to Answer => Puzzle (... would even match the icon better ;) )
- Stage of a Multicache => Stage
- Final Location => Final
- Reference Point => Marker (... or any better suggestion?)

This BTW will also be an advantage with function "Save WPs to PN", as shorter names eat up less space.

**Describe alternatives you've considered**
Shortening the name at time of WP creation is of course possible, but apart from the unnecessary effort, changing the default string in any way breaks the automatism of increasing the index number for follow-ups.

**Comment by Lineflyer** [comment]
Why not.
I don't know where the current texts originate from. Maybe Garmin standard or gc.com wording?

BTW:
Some time ago gc.com devided it into

- Stage of a Multicache = Physical stage
- Question to Answer = Virtual stage

How about that?

**Comment by MagpieFourtyTwo** [comment]
Yep. "Physical Stage" and "Virtual Stage" would be fine, as they fit into the popup, too.

*But* OTOH they possibly match gc.com's wording a little bit too much ... which of course *may* be seen as an additional advantage, but in fact it contains the risk of being translated into other languages by just following gc.com's translations ... and especially the German one for "Physical Stage" is absolutely horrible in any way, as it is "Gegenständliche Station" - which is a) *really* bulky (who for god's sake will use such a term?!?) and b) does not fit the popup again, so would make things worse. So, if we go with your proposal, there should be kept an eye on the translations ...

BTW: While testing the German wordings I noticed that the popup for "Physische Station 34" is *way* wider than the one for "Virtuelle Station 34" - although "Virtuelle Station" takes even more space, nearly "cracks" the border. How come?

**Comment by eddiemuc** [comment]
> Why not.
> I don't know where the current texts originate from. Maybe Garmin standard or gc.com wording?
> 
> BTW:
> Some time ago gc.com devided it into
> 
> - Stage of a Multicache = Physical stage
> - Question to Answer = Virtual stage
> 
> How about that?

I would like @MagpieFourtyTwo s initial suggestions better because names are shorter and more to the point imho. I believe that GC.com mainly made the distinction between virtual and physical so they are able to check their distance ruleset (161m to all physical stages of another cache, but not to virtual stages), for my own geocaching waypoints out in the wild this distinction is less important

**Comment by MagpieFourtyTwo** [comment]
> distinction between virtual and physical so they are able to check their distance ruleset

Yep, same guess over here.

Nevertheless it's even out in the woods good to know if you have to look for a container or just s/th "normal", which is in fact the difference I wanted to express with the wording.

But OTOH there is the icon already, and as soon as you have noticed that this is *not* a small house (which did not really make sense) but a puzzle piece (which to be honest took a while over here ;) ) this is pretty self explanatory and therefore I would even suggest to use the text "Stage x" only for *both*, as this would make it easier in e. g. a Multi to keep the numbering continuous - and consistent with the normal numbering of Multi stages.

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
Can you post a screenshot of the problem you described initially, that the long name prevents it from being shown completely?

AFAIR the name of the waypoint (as the owner defined) will be shown in the popup, but not the waypoint type.

**Comment by MagpieFourtyTwo** [comment]
Waypoint type is shown as well, although not textual but as symbol (P = Parking; Signpost = Trailhead; Puzzle = Virtual Stage; Footsteps = Phys. Stage; Dot = Reference; Flag = Final), right before the name of the waypoint:

![Screenshot_20200923_180542_cgeo geocaching](https://user-images.githubusercontent.com/9889015/94039354-eaede580-fdc7-11ea-9e8d-447f7cb0065f.jpg)

Over here we're talking of "Stage 2" - and I would appreciate to be able to see this in the map, too.  ;)
BTW: Wording may be slightly different, as I had to fake the German words - but result is still the same.
Moreover: I guess perhaps even in the German translation the word "Stage" would be very welcome, as most of the cachers I know are talking of "Stages" anyway and the ones using "Stationen" are an absolute minority (at least my impression).

**Comment by MagpieFourtyTwo** [comment]
The English wording is "Stage of a Multicache x" - and x>=10 will give the very same result.
And things get even worse when you add a short keyword to the name, as we usually do.
So we in fact just rename them to "S1 \<keyword_1>" to "Sn \<keyword_n>", keeping track of the numbers manually.
So. at least for me, in stage context even one letter would be sufficient ...

**Comment by Lineflyer** [comment]
Oh, you are talking about WPs created with c:geo.

In fact then we only talk about the prefilled name c:geo generates for waypoints but not necessarily about the naming of the types as such.
Wouldn't it then be sufficient to keep the type definition as it is but only use shorter names for prefill in user defined waypoints?
IMHO that would be a good compromise not to touch the type definition as such.

**Comment by Lineflyer** [comment]
From my understanding the strings for the waypoint types are reused to populate the waypoint name when creating it.

So a technical possibility should be to define additional shorter strings for the types as proposed and discussed above and use them isntead for the prefill.

|Long|Short|
|------|-----|
| Stage of a Multicache | Stage |
| Question to Answer | Stage |
| Parking Area | Parking |
| Final Location | Final |
| Reference point | Reference |
| Trailhead | Trail |

So you would e.g. create a waypoint with type "Stage of a Multicache" and name "Stage x".

**Comment by MagpieFourtyTwo** [comment]
Hmm - I think, we first need some definition to clarify this. So, if I understood right by now, we have (or may have) ...
1. a waypoint type - which I guess is the label, shown in the drop list? Or somewhere else?
2. a default WP name - which is the string filled in automatically on creation of a new WP

And these two have for real different sources? Or is this just your assumption? As they are literally the same right now, I implicitly assumed, they have just one ...

Ok - what in fact is bothering, is the length of "2. the default WP name", as it is too long to fit in the popup's name field.
The waypoint type, as listed in the drop down, doesn't hurt at all, but nevertheless I would prefer similarity between these two, as different naming may lead to confusion ...
But perhaps we can use them in combination, to a) shorten the name *and* b) retain (or even improve) comprehensibility by using the waypoint type (in the drop down) as kind of explanation ...?

My idea:
old WP|new WP default name|new WP type for drop down list
-------|-----------------------|---------------------------------------
Parking Area|Parking [n]|Parking Area
Question to Answer|Stage [n]|Virtual Stage
Stage of a Multicache|Stage [n]|Physical Stage
Final Location|Final [n]|Final Location
Reference Point|Marker [n]|Marker / Reference Point
Trailhead|Via [n]|Via / Trailhead / Junction

**Comment by Lineflyer** [comment]
> And these two have for real different sources?

No, they are currently not. That's the "reason" for the problem. Therefore I suggested to introduce short versions additionally.

Regarding your table:
I am a bit reluctant to modify the waypoint type definition as it is (IMHO) also used in GPX exports. I am not sure if this might affect compatability to GPSr or other tools. Maybe another developer knows, whether there is such probablity.
Anyway the easy fix would be only to add abbreviated strings but not touch the current types.

**Comment by moving-bits** [comment]
+1 for the idea of shortening the default names.

Even one-letter default names would be fine for me. (In that case we should use the already-defined one-letter codes used for storing waypoints to personal notes, which would have the positive side effect of making them more recognizable.)

If we choose to use longer strings, we could decide to make them non-translatable to make sure those names stay short. (Don't know if this is a valid option, though.)

**Comment by MagpieFourtyTwo** [comment]
> GPX exports

Although I don't really know for sure, I think it's *extremely* unlikely that a GPSr may obey the name string "Station eines Multicache" ...

**Comment by MagpieFourtyTwo** [comment]
> Even one-letter default names would be fine for me

Not to be misunderstood: One letter would (for me) be sufficient for Stages only, *and* in conjunction with it's index - as "S1" appears to be common parlance, anyway.
But a single "F" or "FN" for "Final" already looks a bit overdone to me, and although "P" may still be mnemonic enough, an "M" for "Marker", "T" for "Trailhead" or "V" for "Via" is definitely not that comprehensive, and thus prone to misunderstanding.
So, if we want to drive shortness to the max, I would love to go with "Sx", would even accept "P", but stay with at least "Final", "Marker" and "Via" - which in fact are short enough, IMO.

**Comment by MagpieFourtyTwo** [comment]
> If we choose to use longer strings, we could decide to make them non-translatable

This would work for "Stage", "Via" and "Final", as they are kind of "international", but "Parking" and "Marker" may possibly sound strange in some foreign languages ...

**Comment by moving-bits** [comment]
For documentation: Those are the waypoint type abbreviations currently being used:
f - final
o - own
p - parking
x - puzzle
s - stage
t - trailhead
w - waypoint
h - original

But I'm not bound to one-letter default names.

As I would not mix one-letter and longer default names, I propose to stay with one of the short name solutions listed in one of the earlier posts.

**Comment by Lineflyer** [comment]
> Although I don't really know for sure, I think it's extremely unlikely that a GPSr may obey the name string "Station eines Multicache" 

I quickly checked on an export.
In fact its already mapped to a standard, so these strings are not used and we could freely change them.

```
<type>Waypoint|Virtual Stage</type>
```

Taking this and other proposals into account, how about:
old WP|new WP default name|new WP type for drop down list
-------|-----------------------|---------------------------------------
Parking Area|Parking [n]|Parking Area
Question to Answer|Stage [n]|Virtual Stage
Stage of a Multicache|Stage [n]|Physical Stage
Final Location|Final [n]|Final Location
Reference Point|Marker [n]| Reference Point
Trailhead|Via [n]| Trailhead

**Comment by MagpieFourtyTwo** [comment]
+1 for the latest table (oh wonder ;) ), but I would at least mention the default name in the type list, to underline the connection between these two - otherwise someone who selected e. g. "Reference Point" and gets "Marker" as name may possibly think he missed the right list entry ... so I would come back to my proposal for e. g. "Marker / Reference Point" resp. "Via / Trailhead".

**Comment by okainov** [comment]
>Question to Answer | Stage [n] | Virtual Stage

What about still differentiating it with "physical stage"? Maybe "Question"? Just 2 chars longer than "parking"

**Comment by MagpieFourtyTwo** [comment]
The "problem" with differentiating is, that the automatic numbering does not work or is at least not really obvious anymore with changing names.

So, usually you have s/th like S1 to S9 in a Multi, where some of these are physical and others virtual - but this just makes a difference with regard to the object to search for resp. to look at (e. g. "find box" vs. "count the trees"), which is in fact already covered by the description, anyway. So, for that, the distinction is not really vitally important, i. e. has just very small advantage.

But OTOH there is a big disadvantage, as the numbering of stages gets screwed up when mixing "Physical" and "Virtual" stages, as each of them count from one. So your "real" S3 becomes "Virtual Stage 1" in c:geo, if it's the first virtual one. and the next "Physical Stage" will get number 3, although it's "real" number is 4 already ...

This would be easier (and look more consistent) if Stages will be consecutively numbered in the same way, they are in the listing.

**Comment by Lineflyer** [comment]
Taken from a comment by @SammysHP on Crowdin:
"Stage of a Multicache" is rather long and not only used to describe the waypoint type, but also as the waypoint title (plus number). This is also the default for new waypoints. We got a request that is feels just too long, so maybe "Stage" is enough?

Coming back to this topic then:
We seemingly agreed on the table in https://github.com/cgeo/cgeo/issues/9041#issuecomment-697926825 .
But in order to implement it we would need to split up the strings used for detault name and for the drop down list in waypoint creation (see table).

> But OTOH there is a big disadvantage, as the numbering of stages gets screwed up when mixing "Physical" and "Virtual" stages, as each of them count from one. So your "real" S3 becomes "Virtual Stage 1" in c:geo, if it's the first virtual one. and the next "Physical Stage" will get number 3, although it's "real" number is 4 already ...

@MagpieFourtyTwo 
Are you sure about this? AFAIK we do not sort by name but by IDs (or whatever they are called). So whatever waypoint type you create, it should be ordered by in sequence of creation (incremented ID) rather than name. Same applies for server waypoints. So this should not be the problem here.

**Comment by moving-bits** [comment]
From the source code:

Sorting is done by waypoint type:
- PARKING
- TRAILHEAD
- OWN, PUZZLE, STAGE, WAYPOINT
- FINAL
- ORIGINAL

Default names for new waypoints are calculated as follows:
- for types FINAL and TRAILHEAD return the localized name without number (if no such name already exists)
- else test for numbers 0-29 if "localized name" + " " + number already exists (if yes: remember as max)
- return "localized name" + " " + (max+1)

so numbering is done on a per-type base

```
public static String getDefaultWaypointName(final Geocache cache, final WaypointType type) {
    final ArrayList<String> wpNames = new ArrayList<>();
    for (final Waypoint waypoint : cache.getWaypoints()) {
        wpNames.add(waypoint.getName());
    }
    // try final and trailhead without index
    if ((type == WaypointType.FINAL || type == WaypointType.TRAILHEAD) && !wpNames.contains(type.getL10n())) {
        return type.getL10n();
    }
    // for other types add an index by default, which is highest found index + 1
    int max = 0;
    for (int i = 0; i < 30; i++) {
        if (wpNames.contains(type.getL10n() + " " + i)) {
            max = i;
        }
    }
    return type.getL10n() + " " + (max + 1);
}
```

**Comment by MagpieFourtyTwo** [comment]
> so numbering is done on a per-type base

Yep. this matches my observations.  And it can be pretty confusing if the stages of a Multi have alternating types.
Just following the automatism, you will get:
1. Stage of a Multi cache 1
2. Question to Answer 1
3. Question to Answer 2
4. Reference Point 1
5. Question to Answer 3
6. Stage of a Multi cache 2
7. Question to Answer 4
8. Reference Point 2
9. Question to Answer 5
10. Stage of a Multi cache 3
11.  ... ;)

**Comment by eddiemuc** [comment]
What about adding a "global" index to the waypoint default name instead of a "per-type" index? Then numbering would be consistent with creation time.

And btw: what about adding said index before the waypoint name instead of after? (E.g. "1 Physical Stage" instead of "Physical Stage 1")

Also, if it is allowed to reopen this discussion, I would vote for naming the "Physical Stage" simply "Stage" ("Virtual Stage" can stay, so there's a differenciation to "Stage")

**Comment by MagpieFourtyTwo** [comment]
>What about adding a "global" index to the waypoint default name instead of a "per-type" index?

+1

> And btw: what about adding said index before the waypoint name 

-1 - cause "1 Stage" reads and sounds really strange, while "Stage 1" is common parlance.

**Comment by eddiemuc** [comment]
>  >What about adding a "global" index to the waypoint default name instead of a "per-type" index?
> 
> +1
> 
> > And btw: what about adding said index before the waypoint name 
> 
> -1 - cause "1 Stage" reads and sounds really strange, while "Stage 1" is common parlance.

I think@moving-bits already implemented it this way ("global" index but added at the end). 

Still, I personally would prefer adding the index upfront. Would also be good for alphabetical sorting. To mitigate your valid concern, one could use some additional marker. E.g instead of writing "1 Stage" one could use
* 1: Stage
* WP1: Stage
* 1) Stage
* Waypoint 1: Stage

(my personal favorite would be 1 or 3)

Anyway, it is a minor thing to me

**Comment by moving-bits** [comment]
> I think @moving-bits already implemented it this way ("global" index but added at the end).

yes, that's part of #9678

> Still, I personally would prefer adding the index upfront.

Understandable, as it's more visible. My concern though was the existing waypoint names having the numeric identifier at the end, so you would have a mix of numer at front and number at end, which I wanted to avoid.

> Would also be good for alphabetical sorting. 

Currently it would not really make a difference in terms of sorting, as we currently sort by waypoint type first. 
Maybe we need to discuss whether we want to keep that or whether we change to a pure alphabetical sorting.

To mitigate your valid concern, one could use some additional marker. E.g instead of writing "1 Stage" one could use
>     * 1: Stage
>     * WP1: Stage
>     * `1) Stage`
>     * Waypoint 1: Stage

or #1: Stage

**Comment by Lineflyer** [comment]
While I did not dive into the details of the proposed implementation (will test it after merge then :) ) my vote regarding the numbering would be to keep it at the end for more "natural reading".

**Comment by MagpieFourtyTwo** [comment]
> my vote regarding the numbering would be to keep it at the end for more "natural reading".

+1 - while I would additionally suggest to make the numbering a little bit more intelligent, cause it "fails" as soon as the name of the waypoint has been changed: If you e. g. add a word for better identification, the next waypoint will again get number 1. Would be way better, if the numbering would just continue, thus count waypoints of the current type ... or even *all* waypoints, cause while doing a Multi, it is of no interest at all for the numbering, if a stage was physical or just virtual, And although c:geo may think, "physical stage 1" can be followed by "question to ask 1", in reality S1 will of course never occur twice ... ;)

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 
Please retest with current nightly. Numbering mechanism has changed. The beginning of the waypoint name gets completely ignored (regarding the numbering), the only important thing is having ciphers at the end. (Those are identified using a regular expression.) All waypoints of a cache are checked, and the highest found numbers of all those waypoints (type independent) is used as base for the next waypoint.

**Comment by MagpieFourtyTwo** [comment]
Had a quick test and on first sight I *really* like the new numbering!
Even adding a mnemonic keyword after the number works, thus naming like e. g.
- Stage 1 - Dog
- Stage 2 - Cat

will still generate default name "Stage 3" on next addition of a waypoint.
Same with colon or just a blank as separator. Cool!

Even adding a "Reference point" does not screw up the numbering:
- if the RP is a Stage of it's own (here: "Marker 4"), you can just leave the number where it is, and the next Stage waypoint will get the "5".
- but if it's just an orientation point, which has not been counted as Stage by the cache owner, all you have to do is remove the "4", and the next Stage waypoint will get it. Great.

Just one thing (right now ;) ) I would additionally change is, integrate the WP type "Trailhead" into this, too.
The guys I know using "Trailhead" WPs, use them as Via points - which is in fact the current default name, anyway.
But as the "Trailhead" WPs are currently sorted to the top of the list, they are named as, but do not really show up as "Vias".
One can of course use "Reference point" as Via, to make them show up at the right place, but that in fact renders the type "Trailhead" completely superfluous, IMO.

**Comment by moving-bits** [comment]
Thanks for testing.

> Even adding a mnemonic keyword after the number works, thus naming like e. g.
>     * Stage 1 - Dog
>     * Stage 2 - Cat

Oops, nice feature, but not intended originally. I need to adapt the reg exp to make sure, it's always the same number that's been taken. Should be the last ciphers found in the name, not some in the middle, IMHO.

> Just one thing (right now ;) ) I would additionally change is, integrate the WP type "Trailhead" into this, too.

If no one objects I will adapt the function to it.

**Comment by MagpieFourtyTwo** [comment]
> Oops, nice feature, but not intended originally.

Nevertheless, I would really like to keep it as it is.
However, looking for a pattern like "(Stage|Marker|Via) \([0-9]+\)" to increment \1 would be ok, too, I guess.

**Comment by moving-bits** [comment]
Current pattern is `[^0-9]*([0-9]*)`, I would extend this to `^[^0-9]*([0-9]*[^0-9]*$)` or something like this (haven't tested). Goal is to find the last ciphers in the name.

**Comment by MagpieFourtyTwo** [comment]
This is pretty exactly what would *spoil* the best effect of your changes ... :/

BTW: A star behind an expression usually means "zero or more" ...

**Comment by moving-bits** [comment]
So you say it should actually look for _every_ number in the name, even if there are multiple numbers?
Or would it be ok to check only for the last number found in a name?

**Comment by MagpieFourtyTwo** [comment]
> So you say it should actually look for every number in the name, even if there are multiple numbers?

No, nothing like that - maybe a misunderstanding?

What I wanted to say is: Don't know how RegExp is implemented in c:geo's environment, but "usually" the star means "zero or more occurrences" of the given pattern. The sign for "at least one or even more occurrences" is the "+" sign (in my RE world).

The expression ``^[^0-9]*([0-9]*[^0-9]*$)`` will (in my RegExp world) look for a line start (^), then zero or more non digits up to the first number, and after the last digit of that number again zero or more non digits - till the end of the line ($). Thus, if there are two numbers in the line, the pattern will fail completely (in my world).

If you want to get the last number in a line, you just have to look for digits *that are not followed by a digit.* Thus s/th like ``(\d+)(?!.*\d)``, where ``\d+`` is ``one or more digits`` and ``(?!.*\d)`` stands for ``zero or more non digits``.  Or in your notation most probably s/th like ``\([0-9]+\)[^0-9]*`` where ``\1`` usually represents the number that has been found by ``\([0-9]+\)``.

Nevertheless, it may be hard to understand why a WP name ``Stage 1 - 21 dogs`` will be followed by a WP named ``Stage 22`` - hence I would not just look for a number (esp. not for the last one), but 
- for the very first occurring number (as following ones will most probably be part of an add. note), or
- for the keywords "Stage", "Marker" or "Via", immediately followed by a number, and increment this number, or
- first cut off everything after a char which is *not* member of the typically used charset for a WP name, i. e. [a-zA-Z0-9],
  which would e. g. strip ``Stage 1 - 21 dogs`` to ``Stage 1 `` which then can happily be incremented

Or what do you think ...?

TMALSS: I would really like to keep the wonderful possibility to add a mnemonic keyword at the end of the WP name (to be honest: Cause this is exactly the way we are using WP names ;) ), which may even be separated with a delimiter like colon or minus or whatever, if needed ... like described above with the WP names ``Stage 1 - Dog`` and ``Stage 2 - Cat``.

**Comment by eddiemuc** [comment]
IMHO this gets all too complicated for such a simple side task... automatic naming/numbering algorithm should be so simple that the typical user understands the rules behind it when he sees the generated names.

Maybe revisit the thought of putting the number at the **beginning** of the name? This would avoid all the problems above in an easy way.

**Comment by moving-bits** [comment]
I'd like to keep things simple and not too much depending on specific translations etc. 

With #9726 I included trailheads in the numbering and fixed the "+" vs. "*" issue, but left the regexp unchanged otherwise, which means that it will look for every number in the waypoint name and take that into account for calculating the new max. value. Tests are added accordingliy (#9727). Both PR are in the current nightly.

**Comment by MagpieFourtyTwo** [comment]
> IMHO this gets all too complicated for such a simple side task

IMO, it's not really complicate, it's just about setting up a convenient regexp, while the stuff around it is already implemented, anyway. Apart from that the list mentioned above may have been misleading: It was not meant as "all of this", but just "one of the three possibilities". ;)

**Comment by MagpieFourtyTwo** [comment]
Retested - auto-numbering is not completely what I would call "intuitive" (I would still prefer the first number to be increased, instead of the biggest one), but can live with it.  Nevertheless, it's still *way* better than the previous way to handle it.  Thus: Thx a lot!

BTW: Trailhead WPs resp. "Vias" are still sorted to the top of the list, where they do not really make sense, IMO.
Does this fit in here or should it be a separate issue?

**Comment by moving-bits** [comment]
> BTW: Trailhead WPs resp. "Vias" are still sorted to the top of the list, where they do not really make sense, IMO.
> Does this fit in here or should it be a separate issue?

Let's create a separate issue for it for easier tracking and keeping the discussion separate from here.

Anything left that should be implemented from the original issue, or can we close this issue?

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
Just for your information and maybe to make some discussion/clarification easier:
We decided to try to revive our IRC channel #cgeo on freenode.net to reduce the amount of postings in issues in case some clarification is needed before the result gets back to the issue then.
Meaning: You can try to reach a developer also on the IRC, discuss about a certain issue/topic Of course the result (if any) should be posted back into the issue.

**Comment by MagpieFourtyTwo** [comment]
Ok - thx for the hint. But haven't used IRC for a *very* long time ... looked for an Android client, to no avail. Any suggestion?

**Comment by MagpieFourtyTwo** [comment]
> Anything left that should be implemented from the original issue, or can we close this issue?

As far as I am concerned, it can be closed ...

**Comment by fm-sys** [comment]
OK, then let's close it...
