### ISSUE TITLE
Automatically recreated waypoints do not get persisted

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9042]
Taken from https://github.com/cgeo/cgeo/issues/9026#issuecomment-696500835 by @geocachermgo regarding the "delete user-defined waypoints" feature:

If I have a list of waypoints in the notes, delete all waypoints: the display of the list is correctly not reduced (if notes are unaltered) or reduced (if # of wps have been reduced in the notes). But if I go to the map or close the cache and reopen it: all waypoints are gone.

**Comment by geocachermgo** [comment]
[CI Build](https://ci.cgeo.org/job/cgeo%20Continuous%20integration/2921/) failed but apk is there? Or is the builed failed because of the TB logging test fail?
I will test tomorrow with the nightly.

**Comment by Lineflyer** [comment]
Yes, the test fail is related to the real TB error. CI will fail here until the issue has been fixed.

**Comment by geocachermgo** [comment]
Ok, so "build failed" does not mean aborted and not able to generate code.

**Comment by geocachermgo** [comment]
> I will test tomorrow with the nightly.

With 2020.09.23-NB-3f87172 the problem is still there.

**Comment by eddiemuc** [comment]
> Ok, so "build failed" does not mean aborted and not able to generate code.

In this case no.

In general, the CI executes different "build stages", and depending on which stage fails there might be build results available from previous stage. Roughly speaking the stages are (not entirely sure about the order though):
* Compile code
* Execute unit tests
* Run code style checks
* Build installable APK
* Install APK in emulator and run Android instrumented tests

In current case, failure was in last stage, so the result of the previous stage (APK) is available nevertheless.

**Comment by geocachermgo** [comment]
Thank for the info. Can I but this in the wiki?

**Comment by eddiemuc** [comment]
> Thanks for the info. Can I put this in the wiki?

Generally yes, but since I only took a rough guess regarding the real stages and their order (taken from my own experience with c:geo development and CI knowledge from other projects), maybe this should be verified before by someone REALLY knowing the c:geo CI in detail :-)

**Comment by moving-bits** [comment]
> > I will test tomorrow with the nightly.
> 
> With 2020.09.23-NB-3f87172 the problem is still there. (I'm sure if its should be fixed since the issue is still open, but moving-bit commited a fix)

This is to be expected as the fix for this (PR #9043) is not yet merged, and therefore the code not yet included in the nightly.

**Comment by geocachermgo** [comment]
Tested ok, thank you.
