### ISSUE TITLE
[Nightly] Symbol for saved and own exclude each other

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9045]
Big arrow shows that the 4 corners are used for: (clockwise) saved, Final waypoint, note, found.
The first position is also used for the own star (small arrow). So if the cache is stored and owned only one symbol can be shown. Do we have even more symbols?
![IMG_20200923_101729](https://user-images.githubusercontent.com/43813636/93986599-d63d2d80-fd86-11ea-895a-8fd2bd2c5066.jpg)

Update: So position 1 is double occupied:
![IMG_20200923_160858](https://user-images.githubusercontent.com/43813636/94024188-67c49380-fdb7-11ea-965c-518cc6b98901.jpg)
![IMG_20200923_160927](https://user-images.githubusercontent.com/43813636/94024200-698e5700-fdb7-11ea-858d-272cbda836df.jpg)

**Comment by MagpieFourtyTwo** [comment]
First thought: What if symbol for ``Own`` just moves to the position of ``Found`` as these two do not come together, usually.
And in the seldom cases where both apply (adoption would be one), ``Own`` should "win", IMO.
Or perhaps boih of them may be displayed, with ``Own`` in foreground.

Another possibility would be to move ``Own`` to 6 o'clock, as ``Note`` and ``Changed coords`` are slim and (at least seem to) leave enough space for a third symbol in the middle.  While same applies to 9 o'clock - which may look even better ... if I think about it ... :)

**Comment by MagpieFourtyTwo** [comment]
Ah. stop - at 9 o'clock there is already the list marker dot ...
but this may even move to the free space below the cache symbol, as proposed in #9010 ...

**Comment by Lineflyer** [comment]
These two overlays using the same position was explicitly decided somwhen in the past for the map. On the map the "own" wins over the "saved".
We should handle it alike in the lists.

**Comment by Lineflyer** [comment]
Addon:
I have not realized, that the "own" already wins over "saved".
IMHO we should not change anything here or find any additional solution. 
BTW: This was one of the reasons why we did not use the floppy in the lists in the past. Now we decided to use it, so we have to live with that. IMHO its no real issue.

**Comment by okainov** [comment]
First time reading the text and looking at the screenshot I was not able to understand what is the problem.

But now it's clear and it seems indeed an issue (though minor one). "Own caches don't have saved icon". I'd propose to put star in the top-left.

>On the map the "own" wins over the "saved".

Do you remember the reasons, why?

**Comment by fm-sys** [comment]
> I'd propose to put star in the top-left.

+1

> These two overlays using the same position was explicitly decided somwhen in the past for the map.

I also don't see a real reason. From my point of view, this is just a matter of habit...

**Comment by geocachermgo** [comment]
> ...  IMHO its no real issue.

Feel free to close it.

**Comment by MagpieFourtyTwo** [comment]
Ahem, I'm confused, too - why close it?
I would of course switch position, as ``Own`` and ``Saved`` are not a rare constellation,
while OTOH ``Own`` and ``Found`` are kind of equal ... so these two should go together, with ``Own`` "winning" as said before.
And this said, we have an issue for real ...

**Comment by okainov** [comment]
>OTOH Own and Found are kind of equal ... so these two should go together

Not even like this - they can *never* never together by definition :)

**Comment by Lineflyer** [comment]
> Not even like this - they can never never together by definition :)

They can in case of an adopted cache. I own quite some of those.

**Comment by moving-bits** [comment]
> > OTOH Own and Found are kind of equal ... so these two should go together
> 
> Not even like this - they can _never_ never together by definition :)

They can, at least on gc.com, but only in special circumstances:
- you adopt a cache you have found earlier
- up until about 2017 it was possible to log your own cache as found

But IMHO these are relatively rare cases, and way less frequent than stored + own, so a +1 from me to move "own" to the same place as "found".

**Comment by moving-bits** [comment]
Having looked in the source I see a possible reason why floppy & own share the same space, and not found & own:

Both positions are used twice already, currently:
- top right: owner & floppy
- top left: found & offline log

(the first one winning respectively)

So the question arising is: Do we need the "offline log" indicator in map or cache detail views?
(In cache list this is being taken care of by the colored line.)

Personally, I could live without, but I'd like to gather some feedback first.

Different solutions could be
- to combine two markers, or 
- to use one of the left free spaces, eg. put the floppy at six o'clock

**Comment by Lineflyer** [comment]
I personally think, that found/offline log status is most important. Furthermore touching this area is really user relevant and IMHO (as stated above) I think the current state is totally fine and should not be touched.

I vote for not introducing any major change and even more not trying to pack even more information into the overlays by combined overlays or similar. Please also consider users, which do not have so much insights and expertise in Geocaching and/or c:geo internals.

We agreed to have the floppy in lists for consistency to map and to save space. Now we start into discussion how to mitigate follow up issues which makes things even more complicated.

**Comment by moving-bits** [comment]
I have a proposal which would solve the owner/stored problem, is compatible for both maps and lists, and affects only a (relatively) small user group at all:

- Move the "owner" icon overlay to bottom center,
- and leave all other icon overlays where they are now.

Would look like this:
![image](https://user-images.githubusercontent.com/3754370/94057275-aff7ac00-fddf-11ea-8fe0-5b6a13f82581.png)

**Comment by MagpieFourtyTwo** [comment]
> So the question arising is: Do we need the "offline log" indicator in map or cache detail views?

Yes, we do. Cause a saved offline log, which is not displayed in the map, will most probably lead to double visits ... or at least insecurity with regard to "have we already been there or not ...?"

**Comment by okainov** [comment]
>Would look like this:

IMO this doesn't look good... Especially when it's the third icon in the row. Maybe on top would be nicer, but even then if there are two icons in the corners then it might get uglier...

>So the question arising is: Do we need the "offline log" indicator in map or cache detail views?

Yes, for sure.

**Comment by MagpieFourtyTwo** [comment]
As for me. "Offline Log", "Found" and "Own" are pretty similar, so these can go together for good. IMHO.

**Comment by moving-bits** [comment]
> As for me. "Offline Log", "Found" and "Own" are pretty similar, so these can go together for good. IMHO.

In which precedence? owner > found > offline log?

**Comment by MagpieFourtyTwo** [comment]
Yep. "Owner" wins over "Found", "Found" wins over "Offline Log".

**Comment by okainov** [comment]
>Yep

I think it's more like "no, opposite" ;) At least I've read @moving-bits comment as "found overrides own and offline log overrides both"

>"Found" wins over "Offline Log".

No please. Offline log means "action required", it is "temporary" state. I do want to see the caches where I left offline log (to send and to log it on the gc service actually).

**Comment by moving-bits** [comment]
> > "Found" wins over "Offline Log".
> 
> No please. Offline log means "action required", it is "temporary" state. I do want to see the caches where I left offline log (to send and to log it on the gc service actually).

Just for the record: "Found > Offline" log is the way the symbol in the upper left corner is currently implemented, with "Found" meaning you already have logged this online.

**Comment by MagpieFourtyTwo** [comment]
That was my understanding: If you have logged it online already, a still existing offline log is in fact just a matter of db polishing. ;)
But, as I'm a friend of clean DBs, we of course can even let "Offline Log" win over "Found Log" and even let "Offline Log" win over "Own", but I would *not* let "Own" win over "Found", as "Own" is the most important state, cause this means "must be maintained", which is not the case with "Found", which in fact means "Forget about it". ;)

**Comment by okainov** [comment]
>, a still existing offline log is in fact just a matter of db polishing. ;)

Have you ever logged into a cache after finding it intentionally? =) Like visited again with fried and write note "logbook is full"? Or wandering around your place and checking the cache just because you have nothing better to do and writing DNF "seems the container is gone"? What I have in mind is of course those cases, when you *intentionally* log the cache. And of course not about the bugs when offline log was sent, but for some reason is still present in c:geo (this sounds like a bug anyway)

**Comment by Lineflyer** [comment]
How about just reverting the initial change regarding the floppy icon, which caused this (sorry!) meaningless discussion. I am a bit frustrated about it, as we spent a lot of hours find a majority in the far past for distribution and overriding of overlays we currently have.
Changing it all again will raise user questions, trigger changing of screenshots, manuals, etc.
I am out of this discussion.

**Comment by MagpieFourtyTwo** [comment]
As for me, the change from text "Offline" to the floppy symbol is a really good one - and will not raise questions at all, as the users already know this floppy anyway. They will like the saved space, for sure.
And concerning the "rest" of the discussion: I would say most of them will not even notice the change if the "Own" icon goes from upper right to upper left.
BTW: Having s/th for years does not automatically mean that is was good ...  ;)

**Comment by MagpieFourtyTwo** [comment]
> Have you ever logged into a cache after finding it intentionally? =) 

That's why I already agreed, "Offline Log" may win over "Found".  ;)

**Comment by okainov** [comment]
>How about just reverting the initial change regarding the floppy icon, 

Actually I just realized that it's all about super recent change #9036. And, at least looking at my lists, I indeed agree as I don't really see a big use in having offline icon in lists (my lists are *always* offline-only). I can imagine this for the use case when you have live map and click "show as list", but isn't it rather corner case at all? Then indeed I agree with @Lineflyer as adding the icon would pollute the main use case users as the lists are 99% offline and it makes no sense to show overlay there.

BTW I think it's not the first time there are some discussions happening due to lack of documentation of decisions from the past. What about at least thinking of having something like [ADR](https://github.com/joelparkerhenderson/architecture_decision_record) for c:geo, @Lineflyer ? =)

**Comment by Lineflyer** [comment]
> I can imagine this for the use case when you have live map and click "show as list", but isn't it rather corner case at all?

This case was already covered before recent change as we have in the past explicitly implemented the use of the floppy icon on lists which have the tendency to contain not only saved caches (search results, lists from map).

How about reverting the floppy icon but also just keeping the "offline" text removed to keep saving this space. 
This would mean:
1. On lists which might contain unsaved caches the floppy icons is already shown (also before recent change)
2. On purely saved lists we just skip this information (no icon, no text). The textual "offline" info we had before is IMHO no meaningful information.

Would that be OK to solve this discussion?

**Comment by fm-sys** [comment]
> How about reverting the floppy icon but also just keep having the "offline" text removed to save this space.

Please! That was my first thought when I saw the PR changing the text to the floppy disk.

But we should keep the floppy disk icon for history list, nearby and lists generated from livemap as there the caches can be not yet stored...

**Comment by moving-bits** [comment]
> How about reverting the floppy icon but also just keep having the "offline" text removed to save this space.

Implemented this way with #9054. Fixes both #9045 and #9050.

**Comment by geocachermgo** [comment]
> Feel free to close it.

That was serious. I thought it was a bug (which it wasn't) so it could be closed. I have no strong opinion about the discussed solutions, that's why I did not participate.

Remark: Beside the adopted caches own events are typically also found.
