### ISSUE TITLE
Include even more info into sysinfo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9049]
When trying to help users on support I do often miss the following config information, as these are typical problems:
- Current value of global cache type filter (from lower right main menu item)
- Current state whether live mode of map is enabled or not
- Current path set for offline maps
- Current path set for offline themes
- Current path set for GPX import
- Current path set for GPX export
- State of backup (existing, date/time stamp)

**Comment by SammysHP** [comment]
We could include the whole configuration (excluding credentials) to cover all c:geo related information and in addition required system information.

**Comment by moving-bits** [comment]
> We could include the whole configuration (excluding credentials) to cover all c:geo related information and in addition required system information.

I would stay with a selected subset in the system view, as displaying the whole set makes it hard to find the details needed. We can still ask the user to backup the settings (without credentials) and send it to support, if needed.

**Comment by fm-sys** [comment]
> State of backup (existing, date/time stamp)

Please wait with the backup state as there will be lager code changes related to #8959...

**Comment by moving-bits** [comment]
> > State of backup (existing, date/time stamp)
> 
> Please wait with the backup state as there will be lager code changes related to #8959...

That's why I had excluded this part from #9055.
