### ISSUE TITLE
"Stored" overlay not shown on map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9050]
**Describe the bug:**
Since some of the more recent versions there is no map marker for "stored" any more. It's shown in cache lists, though.

**To Reproduce:**
Open map, showing some stored caches.

**Actual behavior/state after performing these steps:**
No cache shows a "stored" indicator (floppy disk).

**Expected behavior/state after performing these steps:**
Show floppy disk icon overlay for stored caches.

**Version of c:geo used:**
Current master
(Release 2020.08.04 is fine)

**Is the problem reproducible:**
Yes

**Screenshots:**
![image](https://user-images.githubusercontent.com/3754370/94056663-e680f700-fdde-11ea-89aa-7e29d618d117.png)

**Comment by Lineflyer** [comment]
Verified.

**Comment by moving-bits** [comment]
IMHO this is coming from the last change to PR #9036, regarding the null handling.

The original line read `return cacheListType != CacheListType.OFFLINE;` which meant returning a `true` in the null case, but the last change altered this to `return cacheListType != null;` - IMHO it should read `return true` (do not exclude any list/display type).

(This is independent from the check whether this is a cache stored offline - that check is done by the caller.)
