### ISSUE TITLE
Hint is not displayed on compass view, when launched directly from map

### ISSUE THREAD

**Issue by bmuzzin** [cgeo/cgeo#9069]
**Describe the bug:**
When the compass is directly launched from a cache in map view (icon next to the cache title), and the "Hint" icon is pushed, the hint toast always says "No hint available", even if the cache does have a hint. Note that, if you go into "More Details", and launch the compass from that view, the hint toast is displayed correctly.

**To Reproduce:**
1. Go to map view. 
2. Click on a cache icon, that has a hint (eg. GC2BG6B)
3. Click the compass icon next to the cache title the cache summary dialog.
4. Click the hint icon next to the cache title.

**Actual behavior/state after performing these steps:**
Hint toast is displayed as "No Hint Available"

**Expected behavior/state after performing these steps:**
The hint for the cache should be displayed in the toast (in this case "[Puzzle] <a href=..."

**Version of c:geo used:**
2020.09.25-dee1772 developer build

**Is the problem reproducible:**
Yes (on my personal device LG Power X3, but also in the emulator)

**System information:**
```
--- System information ---
Device: Android SDK built for x86 (sdk_gphone_x86, google)
Android version: 8.1.0
Android build: sdk_gphone_x86-userdebug 8.1.0 OSM2.171116.002 4458339 dev-keys
c:geo version: 2020.09.25-dee1772 developer build
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (567.2 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (567.2 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (567.2 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (212.0 KB) on system internal storage
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: null
Map render theme path: 
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: MMM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---
```

**Additional context:**
Similar to #6091, but in that case, the toast isn't shown at all. In this case the toast is shown, but it always says "No Hint Available", whereas in that issue, the toast doesn't show up at all.

**Comment by fm-sys** [comment]
Yes, that's because the cache you are selecting is probably not jet fully downloaded.

But we have a bug here:
- I started the compass for one cache which is offline and has a hint. => "no hint available"
- clicked back button and started compass from livemap the same way again. => now it is working....

This case is not really reproducible but happens from time to time

**Comment by moving-bits** [comment]
> When the compass is directly launched from a cache in map view (icon next to the cache title), and the "Hint" icon is pushed, the hint toast always says "No hint available", even if the cache does have a hint. Note that, if you go into "More Details", and launch the compass from that view, the hint toast is displayed correctly.

Has the cache you're looking at been stored locally before opening the compass for it from the map?

I guess you are opening the compass from the cache popup window in the map. There should be the same hint button as in compass view, if a hint is available. Is the hint button already shown in the map popup?

**Comment by bmuzzin** [comment]
It doesn't matter whether the cache has been stored locally or not. It is
100% reproducible (it happen to me everyday while caching).

Once you go into the full screen cache page, or even touch the hint from
the cache dialog on the map, the hint does show properly from the compass
launched from the dialog. So, I do think it's a case of the cache not
getting loaded fully.

I am trying to get a handle on the codebase, so I will see if I can debug
it and come up with a fix.

**Comment by okainov** [comment]
Actually I noticed the same quite some time ago (using nightly from mid-June). It doesn't really bother me as I use compass only as compass, but still.
