### ISSUE TITLE
Chose map zoom to include waypoints

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9072]
When I have list of caches and go to the map view, the zoom is chosen in a way that all caches are displayed
If I am on the waypoint list of a cache and go via  the arrow dot the map, the  zoom is only for the cache, the waypoints are not considered.

I suggest to choose the zoom for a cache with waypoints so large, that the waypoints are included.

**Comment by Lineflyer** [comment]
There is already such option in Settings - Map
