### ISSUE TITLE
List name is 'Invisible' when creating new list

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#9073]
**Describe the bug:**
When I create a new list after long-pressing on the 'stored' tile, the list name is invisible as I type it (But the list does get created correctly).

**To Reproduce:**
1. Open cgeo, long press on 'Stored' tile
2. Choose Create new list
3. Start typing a list name

**Actual behavior/state after performing these steps:**
The cursor moves along, but the text is invisible.

**Expected behavior/state after performing these steps:**
Text should be visible.

**Version of c:geo used:**
2020.09.02-RC

**Is the problem reproducible:**
Yes

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
--- System information ---
Device: SM-G960F (starltexx, samsung)
Android version: 10
Android build: QP1A.190711.020.G960FXXSBETH2
c:geo version: 2020.09.02-RC
Google Play services: enabled - 20.33.15 (120408-330018294)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (6.9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (6.9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (6.9 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (24.2 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---
```

**Additional context:**
If I go into a list, then select 'Manage lists' -> 'Create new list', it works fine - the name is visible as I type it.

**Comment by MagpieFourtyTwo** [comment]
WFM, new name is perfectly visible, white text on grey background, Huawei P30Pro, Dark Mode.
Are you using a special "Design", (no) "Dark Mode" or anything like that?

Nevertheless, the ``New list`` input popup looks different, if you are going to create via ``Manage lists`` => ``Create list`` (with border around input area) or if you do it via main screen and tap ``Stored`` => ``<Create new list>`` (borderless) - any reason for this?  I would suggest to use just one, i. e. the first implementation in both scenarios, cause a) it seems to work better and b) to get more consistency ...?

Moreover the third way to enter the list name input is by ``Store offline`` => ``<Create new list>`` and there it seems to be the first one (with border), too (I suppose it's the same routine, anyway?).

**Comment by alan666notb** [comment]
I've got 'light skin' & 'Transparent background' set in settings/appearance.
As far as I know, I don't have any special 'Design' but I don't know where to look for it.

I guess I'm seeing white text on a white background.

I tried the 'Third way' you mentioned (via Store all) and that gave me the input popup with visible text.

**Comment by alan666notb** [comment]
I just tried switching off 'Light skin' and now the text is visible in all cases - White text on a Gray background.
But the popup boxes still have a different look about them.

**Comment by Lineflyer** [comment]
Confirmed with light skin on my device (Samsung S20, Android 10).


Remark:
The problematic dialog (coming from long press list menu item on main screen) is different from the one used in Manage lists - Create list, which is working on white theme. We should use this one also for the first case.

**Comment by Lineflyer** [comment]
Confirmed also for Android 8 by a user on support mail.
