### ISSUE TITLE
Refactoring Filtering/Searching: Discussion 

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9081]
This item is meant as a discussion item on how to refactor Filtering/Searching function in c:geo

@moving-bits was so nice as to create a new project for this topic: https://github.com/cgeo/cgeo/projects/16 

# Features

I extracted the following summary for wanted features from above project:
* Overall: 
  * regardless from where List is accesses, filtering behaviour and av. options should be the same (e.g. from stored lists, from map, from address search) #3346
  * filter options must be aware on what is possible depending on whether caches are transient, in db or only partly loaded (e.g. #5222)
* UI: better UX wanted, see e.g. Locus (#5877)
* Filtering: 
  * selectable value list for a filter shall only contain values which are present in list (e.g. country, see #8716; or #8273)
* New filters: 
  * caches which user favorited (#8377)  
  * caches found by a friend (=another user) #6511
  * by text (#5056)
  * negation filter (#2508)
* Performance / Stability:
  * Handling of large lists is not stable (slow or even crashing) e.g. #8343, #9015, #5523
  * filters shall run asynchronoulsy #5860
* Some bugs 
  * filtering for attributes does not work properly #8620
  * when coming from map then "hide own caches" can't be removed #8383
  * when opening cache from list, deleting it and then returning, cache is still shown #7540

# Technical solution

Today, filtering on list views are done completely in-memory, so even very large stored lists have to be loaded before filtering can be applied. Filtering is done using implementors of the `IFilter ` interface
  
As a starting point for discussion I propose the following:
* UI/UX:
  * A new filter dialog shall be implemented, designed nicely (maybe like proposed here: #5877)
  * This filter dialog is opened both when selecting in the Map "Hide options" (Verbergen) and when clicking "Filter" symbol in cache lists (any other place where filtering takes place?)
* Filter implementation:  
	* Each Filter implementation (`IFilter`) returns on which "type" of cache-data-availability it can be applied on. Types are "StoredInDB", "TransientPartlyLoaded" and "TransientFullyLoaded"
		* Using this, for each list (on map, as search result, as viewing stored lists) it can be filtered which filters may be applied to this list. In the common filter dialog, non-appliable filters are grayed out or sst similar
	* Each Filter implementation (`IFilter`) KEEPS the existing `accept` method for filtering in-memory, but optionally adds a `databaseFilterQuery` method returning part of a SQL WHERE clause which could be used to perform the same filtering on DB level as well. If filtering is done on a list completely in DB and filter supports it, then filtering is done in DB . otherwise in memory.
	* A new `NotFilter` is introduced which takes as a parameter another filter which it then simply negates
		* (Note: no one seems to ask for combining multiple filters (AND-Filter or OR-Filter), but this could be done the same way. I personally always missed those...)
* Large list results:
    * for efficiently displaying large list results in `CacheListActivity`, implementation shall be changed from "completely loading list into memory" into a Cursor-based approach, loading only the caches in view. This can only be done for lists stored in DB though, but can then be nicely combined with DB-filtering filters
	* this would mean, however, that something similar to filtering needs to be added for "Sort" as well (because if not all caches of a list are in memory, then sorting might not return the correct results). Maybe something like interface `ISort` has to be introduced similar to `IFilter`. (haven't looked up in detail how sorting works today, but I figure it is in-memory too?)
	

Screen 1 | Screen 2
------------ | -------------
![image](https://user-images.githubusercontent.com/6909759/94366733-71f9d100-00da-11eb-9985-9eb40ccf0ffa.png)  | ![image](https://user-images.githubusercontent.com/6909759/94366684-221b0a00-00da-11eb-9af4-8c14b9a3ffb6.png)

# Next steps

* What are your opinions on this?
* Who could provide some GUI suggestions?
* Would there be interest in AND or OR Filters?
* Would there be supporters to add kind of an "advanced query language" like e.g. JIRA has for filtering issues (see e.g. here: https://confluence.atlassian.com/jirasoftwareserver/advanced-searching-939938733.html)?

**Comment by moving-bits** [comment]
Thanks @eddiemuc for this concise summary on filtering, like it!

> What are your opinions on this?

Functional aspects LGTM.
Cannot say anything about the technical side in this case, I'm not that deep into the technical details of filtering.

> Who could provide some GUI suggestions?

Not really, just a bunch of ideas:
- should be the same filtering dialog, independent from where you call it (main screen, map, list)
- filter ideally should only offer meaningful options (if that's possible in a performant way) - e.g. region filter offers only available regions of the current list
- current filter list is way too long - is there a way to make better use of the available screen estate?
- filter settings should be stored and automatically retrieved on restarting c:geo
- have a visual indicator in map and lists, if some filters are active

> Would there be interest in AND or OR Filters?

Definitely.
We even have a bit of it today, when combining global type filter with any of the filters within lists or map.

> Would there be supporters to add kind of an "advanced query language" like e.g. JIRA has for filtering issues

Would be nice for technical people, for sure, but I don't know how much work such a thing would be to implement, and how many people would be able and interested to use it. So maybe in a later stage.

**Comment by MagpieFourtyTwo** [comment]
[adv. query language]
> how many people would be able and interested to use it.

I'm pretty sure that an c:geo AQL wold be great stuff, and would love to have s/th like this, but to be honest, I as well guess, the group using it would be a rather small one (taking my experience with GSAK users into account). Moreover these guys most probably already use SQLite or have s/th like GSAK at hand, so I would nevertheless suggest to invest this energy in areas that are more useful to the standard user.

>> Would there be interest in AND or OR Filters?

> Definitely.
> We even have a bit of it today, when combining global type filter with any of the filters within lists or map.

These are in fact just AND filters, aren't they? Or do I miss something? Anyway, combining AND and OR can be as complicated (esp. for the "non technician") as an AQL. And without wanting to be disrespectful, but most people do not even really understand even easiest boolean expressions completely (see GSAK users above), so I'm afraid such a feature, if presented as ``Standard function``, would probably bring up more (logic) problems than solutions.

Possible alternative: What about a filter, which can be set by just typing in an SQL ``WHERE`` clause? Guess this could be implemented really easy and perhaps even be hidden by default with an option like ``Show advanced filters (SQL knowledge needed)``, default: ``Disabled`` ...? This would already be kind of "AQL" *and* allow to combine AND and OR as well ...  ;)

**Comment by MagpieFourtyTwo** [comment]
As for the filtering: Really like the screenshots from #5877 and esp. the possibility to set a range for D and T.

GUI for filtering for attributes: What if the textual list changes to a group of graphics, which can be clicked like the filtering in GSAK? Or when creating Pocket Queries on gc.com? Like ...

- Default, icon greyed out (i. e. doesn't matter)
- first click: icon gets very visible (B/W or even colored): "Must be given"
- second click: icon gets crossed out: "Must not be given"
- third click: icon gets greyed out again: "Doesn't matter".

**Comment by eddiemuc** [comment]
As for the AND/OR filters: functional implementation of this would be easy imho (thanks to already existing IFilter-approach), the real problem is how to set up a good GUI for this. I think that is the reason why JIRA decided to provide a query language (via GUI you can only do AND combinations). And you know I am not a UX guy... But this can be approached later. @MagpieFourtyTwo allowing users to enter SQL would mean that we have to expose our database structure and field names, this is maybe not so good.

**Comment by eddiemuc** [comment]
As for the GUI: @MagpieFourtyTwo if GSAK has a filter GUI worth copying to c:geo, can you maybe share a screenshot or two? 
You don't want me to make up a GUI on my own, trust me :-)

**Comment by moving-bits** [comment]
As for the AND/OR GUI: You don't need to have a full-fledged GUI supporting every possible combination of AND/OR-ing filters - that would lead to something like a separate query language like JQL.

A typical (?) approach for a simplifyed AND/OR-selection would be to
- "or" all filters of the same filter type (eg: different attributes, different regions), and
- "and" all different filter types

Eg:
- you select attributes "climb" and "abandoned structure"
- you select terrain "T4", "T4.5", "T5"
- you select country "Germany"

this would result in something like (pseudo code)
`WHERE ((atributes in ("climb", "abandoned structure")) and (terrain in (4.0, 4.5, 5.0)) and (country = 'Germany'))`

**Comment by okainov** [comment]
>Would there be supporters to add kind of an "advanced query language" like e.g. JIRA has for filtering issues (see e.g. here: https://confluence.atlassian.com/jirasoftwareserver/advanced-searching-939938733.html)?

I'm quite sure it's not needed. I mean, don't get me wrong, I am also somehow software guy, so I do understand the flexibility of  full-featured SQL-like dialect. But let be honest - c:geo as an app which is **insanely overcomplicated** already. "From developers for developers", really :) There were already a lot of complains that is is not easy to get started. Adding the super advanced feature just for pair of advanced users - I think it's not the right approach. Just make existing filters good enough for 90-95% of the cases and it will be already an achievement. Honestly, for me current implementation covers _zero_ of my use cases. So anything would be an improvement here for me.

>Would there be interest in AND or OR Filters?
 Same here, I think basic AND covers almost all the cases, no need to overcomplicate.

In the meantime, I like the @MagpieFourtyTwo idea about triple-click filter icon (whatever-yes-no). This should be perfect for attributes search and might work for types as well..


>Who could provide some GUI suggestions?
Consider different icons used by different services, probably better to keep the types filter as text.


> New filters:
> caches which user favorited (#8377)
> caches found by a friend (=another user) #6511
> by text (#5056)
> negation filter (#2508)

I might be wrong, but "found by another user" and "by text" are not filters IMO . Those are search queries and it should be already implemented from search.

Please also consider offline caching cases (some of those might be already implemented, I haven't checked for long time):

- Caches with personal note
- - Ideally, caches with not synced personal note (implementation-wise "change happened on c:geo side after last sync")
- Caches with saved offline log


One more note, but this probably goes further already big area to "UI overhaul" - I really don't see a point in current filters being placed on the main screen. I'm in live map view 95% of the time (and the rest 5% in cache details view). Filters should be accessible from the map without need to go back to the main screen.

And also at such high-level it might make sense to really try to make some kind of "personas". You know, like in proper project planning :)

> As geocacher, @okainov doesn't like mysteries and earthcaches and would love to filter them out
> As geocacher, @okainov always forgets to sync personal note to the geocaching service and has lost half of his personal notes couple of times already
> As gc.su player, @okainov is frustrated by amount of caches on gc.com and their quality and gave up on even trying to filter "good" caches out of hundreds of garbage ones. // Maybe making favorite filter more explicit? Maybe making "frequency visits" filter to exclude all caches with more than 10 visitors this year?
> As both gc.com and gc.su player, @okainov would expect filters to work consistently when both services are activated

... and so on, stuff like that might help better than bare feature list...

**Comment by okainov** [comment]
More high-level references BTW

Redefining UI #7030
UI / UX overhaul - The big picture #5927

**Comment by MagpieFourtyTwo** [comment]
@okainov 
> Filters should be accessible from the map without need to go back to the main screen.

:+1: :+1: :+1: :wink:

**Comment by MagpieFourtyTwo** [comment]
@eddiemuc 
> if GSAK has a filter GUI worth copying to c:geo, can you maybe share a screenshot or two?

Hmm ... GSAK's filtering capabilities are *way* more elaborated, extensive and complex than c:geo's should ever get. ;)
Nevertheless, for a first impression you may have a look at GSAK's "official" [filter help page](https://gsak.net/help/hs4000.htm) (whose graphics BTW have *a lot* hot spots, so for further info just click into the graphics) and additionally at [saarfuchs.com](https://www.saarfuchs.com/2018/03/gsak-fuer-einsteiger-der-datenfilter.html), who even added some example scenarios.

**Comment by eddiemuc** [comment]
OK, GSAK filters are probably too much for a smart phone screen...

**Comment by eddiemuc** [comment]
My general idea for the GUI would go something like this:
* each filter can have its own "view", in a dimension similar to a list item e.g. like a waypoint or something similar. For example:
    * D/T-filter will have a "slide bar" on this
    * gecache type or attribute filter has a set of icons on it to click active/deactive
    * a "cache name" filter gets a text field
* situationspecific, a set of "default filters" is always displayed. Under those, there is a button "add more filters" or so which allows user to - well - add more filters
* each "filter view" has a trash icon to remove it
* above it all, there is a checkbox "negate filter" to negate whole filter, and another one "AND/OR-filter" to decide whether different filters shall be combined using "AND" or "OR"

**Comment by MagpieFourtyTwo** [comment]
> each filter can have its own "view",

Hmm ... "view" ... reminds me of "materialized views", but AFAIK SQLite does not support them ... or am I wrong?

> D/T-filter will have a "slide bar" on this

With two sliders, for min and max, I hope. ;) Which is in fact the part I like most, as usually we're looking for esp. a T-range, which right now is just possible by filtering for one T after the other, adding each result to a list ... possible, but pretty cumbersome.

> gecache type or attribute filter has a set of icons on it to click active/deactive

Trivalent?

> a "cache name" filter gets a text field

Regular expressions would be great ...
BTW: Thinking about this filter just led me to a new insight: As c:geo's current text search already returns even caches which contain the search string *anywhere* in it's name, it most probably already uses ``LIKE`` - hence should support ``%`` and ``_`` ... just tried ... and it really does! Great! Thanks for triggering these thoughts! ;)

And for the most probably a little bit more complex ``WHERE`` clause, resulting from all these filters, it may pay out to test which order is the most performant, cause if the criterion is first, which most probably filters out the most entries, the following ones have less to do, which can speed up the ``SELECT`` in total.

**Comment by eddiemuc** [comment]
> > each filter can have its own "view",
> 
> Hmm ... "view" ... reminds me of "materialized views", but AFAIK SQLite does not support them ... or am I wrong?

Sorry, this was formulated misleading of me. I meant "view" as an element in the GUI (not a DB view). Just an element though, such that GUI view per filter can be combined to the "complete" filter gui

> > D/T-filter will have a "slide bar" on this
> 
> With two sliders, for min and max, I hope. ;)

If it is up to me then yes :-)

> > gecache type or attribute filter has a set of icons on it to click active/deactive
> 
> Trivalent?

Yes. But currently I don't know exactly how to handle this in GUI with icons, we have very limited possibilities for icon states due to our very "black-and-white-no-colors" style

> > a "cache name" filter gets a text field
> 
> Regular expressions would be great ...

Wouldn't that be too complicated for many users?

> BTW: Thinking about this filter just led me to a new insight: As c:geo's current text search already returns even caches which contain the search string *anywhere* in it's name, it most probably already uses ``LIKE`` - hence should support ``%`` and ``_`` ... just tried ... and it really does! Great! Thanks for triggering these thoughts! ;)
> 

Didn't know that either, so thanks to you I know now too :-)

> And for the most probably a little bit more complex ``WHERE`` clause, resulting from all these filters, it may pay out to test which order is the most performant, cause if the criterion is first, which most probably filters out the most entries, the following ones have less to do, which can speed up the ``SELECT`` in total.

Full acknowledge

**Comment by fm-sys** [comment]
> > > D/T-filter will have a "slide bar" on this
> > 
> > 
> > With two sliders, for min and max, I hope. ;)
> 
> If it is up to me then yes :-)

We should use one `RangeSlider` instead of two separate ones for min and max.
![slider_basic_range.png](https://github.com/material-components/material-components-android/blob/master/docs/components/assets/slider/slider_basic_range.png?raw=true) 

See https://material.io/components/sliders

**Comment by MagpieFourtyTwo** [comment]
[slider]
This is, what I had in mind. 

[trivalent icons with b/w theme]
- doesn't matter: light grey background
- must be: black background
- to be excluded: striked out

[regular expressions]
I'm not thinking of the complete set, but basic stuff like digit and letter groups would be nice to have. But OTOH ``LIKE`` is most probably already mighty enough for 95 % of the cases. Although I don't know how it works with complex ``WHERE`` clauses, so performance may be a reason to go with ``REGEX`` (which needs a user function anyway, so even charset and performance are at "our" hand anyway ;) ).

**Comment by eddiemuc** [comment]
> > > > D/T-filter will have a "slide bar" on this
> > > 
> > > 
> > > With two sliders, for min and max, I hope. ;)
> > 
> > If it is up to me then yes :-)
> 
> We should use one `RangeSlider` instead of two separate ones for min and max.
> ![slider_basic_range.png](https://github.com/material-components/material-components-android/blob/master/docs/components/assets/slider/slider_basic_range.png?raw=true) 
> 
> See https://material.io/components/sliders

Like @MagpieFourtyTwo , this is what I had in mind too. Sorry for the confusion.

**Comment by eddiemuc** [comment]
> [trivalent icons with b/w theme]
> - doesn't matter: light grey background
> - must be: black background
> - to be excluded: striked out

Two complicating  things come to my mind about this:
* How would we "switch" this color scheme if user switches from dark mode to light mode and vice versa?
* Special case "filtering for attributes": each attribute comes in a positive and a negative version. Example: "wheelchair accessible" and "not wheelchair accessible". How do we distinguish in GUI whether someone wants to filter caches which do NOT have set the "wheelchair accessible" attribute from someone wants to filter caches which have set the "not wheelchair accessible" attribute? 

> [regular expressions]
> I'm not thinking of the complete set, but basic stuff like digit and letter groups would be nice to have. But OTOH ``LIKE`` is most probably already mighty enough for 95 % of the cases. 

I agree, this would be a valid Regex "subset"

**Comment by MagpieFourtyTwo** [comment]
> How would we "switch" this color scheme if user switches from dark mode to light mode and vice versa?

IMO background color can be the same, no matter if light or dark skin. It should just not be transparent.

> How do we distinguish in GUI whether someone wants to filter caches which do NOT have set the "wheelchair accessible" attribute from someone wants to filter caches which have set the "not wheelchair accessible" attribute?

In fact, I don't know any program, that offers filters for attributes, that are not even mentioned in the listing. So why should c:geo do? ;)

**Comment by eddiemuc** [comment]
> In fact, I don't know any program, that offers filters for attributes, that are not even mentioned in the listing. So why should c:geo do? ;)

My question was not formulated very good, let me try to rephrase using an example.

Imagine you have a stored list with following caches inside:
* Cache A has "wheelchair accessible" set (depicted in c:geo as wheelchair symbol)
* Cache B has "not wheelchair accessible" set (depicted in c:geo as striked out wheelchair symbol)
* Cache C has set none of the two wheelchair attributes set (depicted in c:geo by not display ing a wheelchair-related symbol)

If you filter this list with option "to be excluded (striked through)", which of the three caches should remain visible in the filtered list?

**Comment by moving-bits** [comment]
> If you filter this list with option "to be excluded (striked through)", which of the three caches should remain visible in the filtered list?

Actually you need to have the following choices, if you want to be complete:
- "wheelchair accessible" => would give you A
- not "wheelchair accessible" => would give you B and C
- "not wheelchair accessible" => would give you B
- not "not wheelchair accessible" => would give you A and C
- not filtered on attribute "wheelchair" or "not wheelchair" => would give you A, B and C

with
- not "xxx" meaning "xxx" attribute, but negated filter,
- "not xxx" meaning "xxx" attribute negated (striked out symbol), positive filter,
- not "not xxx" meaning "xxx" attribute negated (striked out symbol), negated filter

While this may be mathematically correct, it's probably not very user-friendly...


User expectation probably would be more something like this:
- positive filter for "wheelchair accessible" => A, C ("exclude those stating that it's not wheelchair accessible")
- positive filter for "not wheelchair accessible" => B ("take only those stating that it's not wheelchair accessible")
- negative filter for "wheelchair accessible" => B ("take only those stating that it's wheelchair accessible")
- negative filter for "not wheelchair accessible" => A, C ("exclude those stating that it's not wheelchair accessible")

What do you think?

**Comment by eddiemuc** [comment]
@moving-bits exactly my thoughts too :-) But my question was: how to put this logic in a nice and user-understandable GUI?

**Comment by moving-bits** [comment]
I think negating a filter should be a separate GUI element anyway, as negating a filter potentially could be applied to any filter. So you'll have two attribute states (positive/negative) and three filter states (unused/positive/negative).

Or, to make it simpler in terms of GUI (but more limited), you could offer negating a filter only for the complete filter set instead of for each individual filter. Then you would have two attribute states (positive/negative), a filter unused/used and - globally - an option to negate the whole filter set.

**Comment by MagpieFourtyTwo** [comment]
Generally I agree with the last enumeration @moving-bits made [two posts before](https://github.com/cgeo/cgeo/issues/9081#issuecomment-703868540) (thus the one meeting the "user expectations" ;) ), but I would express it a bit ... shorter - and (hopefully) closer to the thoughts of a "naive observer".

In fact: Just follow the icons in the listing.

Hence ...
- if icon [wheelchair accessible] is grey (default: not touched at all) => all caches
- if icon is activated => just caches which mention the positive icon [wheelchair accessible]
- if icon is striked out => just caches with the icon [wheelchair accessible] striked out (thus not wheelchair accessible)

Admittedly, this is for sure not the correct mathematical interpretation, but IMHO the easiest to understand, cause it's simply "WYSIWYG", as you can easily/visibly compare the icons untouched/set/striked-out in your filter with their siblings being in the listing.

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo I agree that this interpretation is easy to understand for the average user, and this is very important.
But i have one use case where this would not work for me. I find that many cache owners fail to set cwertain attributes, a good example is "available in winter". Thus when I cache in winter (when there is snow) I like to filter all caches which do NOT have the "not available in winter" attribute set (I want to see both the ones where the "available in winter" attribute is set and those where neither "not av in winter" or "av in winter" is set). Assuming I have other filters set active too (so I can't use @moving-bits idea of negating the filter as a whole), I would not be able to apply such a filter

**Comment by MagpieFourtyTwo** [comment]
[not ``not available in winter``]
Ok, got it - as *this* icon delivers a real usecase (was a little bit hard for me to understand why someone should look for caches, that are ``not [not wheelchair accessible]``).  ;)

This is in fact the same "problem" you have when [creating pocket queries](https://www.geocaching.com/pocket/gcquery.aspx) - and gc.com solved this with two different icon areas, while both have trivalent icons (at least trivalent for the ones who have three states). In the first area you can chose, which icon must be present in the listing and which state it should have, and in the second, which icons (resp. icon state) may explicitly *not* exist in the listing. Over [here](http://markwell.us/pq.htm#attributes) is a more documented introduction into it ...

So, in order to realize your usecase, you just have to go to the second area and select ``not available in winter`` ... and you're fine.

At least IMO ...  ;)

**Comment by eddiemuc** [comment]
> So, in order to realize your usecase, you just have to go to the second area and select `not available in winter` ... and you're fine.

Actually I like the two-area-solution with trivalent icons very much!

**Comment by MagpieFourtyTwo** [comment]
Note: Filter "Favorites" should learn to filter for "?" favos (i. e. freshly loaded caches w/o favo info).
And I would like to see a slider for them, too.  Although I don't have an idea yet, how this can work together with filtering for "?".
Apart from a ``RangeSlider``, of course, but how much sense would it make to *suppress* caches with *more* than x favos ...?  ;)

**Comment by wolverine007** [comment]
Howdy guys,

any progress for this advanced filtering topic? 

One topic which came into my mind these days, is it possible to integrate the cache type filter from the mainscreen also into the new quick settings menu? 

So the user could easily apply a filter for one or a bunch of types directly by residing inside the map? 

cheers, 
wolv

**Comment by eddiemuc** [comment]
I am full blocked with SAF migration I am afraid. Haven't forgot the topic but if no one else is picking it, it will be in my waiting list for quite some more time...

**Comment by geocachermgo** [comment]
Another point: If I search for "found by" on GC, the sorting order is "log date of that user". In cgeo it is mixed: the 20 newest founds of that owner sorted by (jn my case) distance. I would suggest to keep the GC order.
The sorting "log date of another user" is not possible in the moment.

**Comment by eddiemuc** [comment]
After a long break due to SAF I plan now to start working on this issue again. For now I will merge progress to PR #10147.
I will concentrate on this one as long as #10087 keeps undecided.

**Comment by fm-sys** [comment]
> I will concentrate on this one as long as #10087 keeps undecided.

Then we must delay the decision for as long as possible. Filtering is IMHO a very important and long overdue issue ;-)

**Comment by moving-bits** [comment]
> > I will concentrate on this one as long as #10087 keeps undecided.
> 
> Then we must delay the decision for as long as possible. Filtering is IMHO a very important and long overdue issue ;-)

Agreed. A consistent, fast and flexible filtering system within c:geo probably helps more users as integrating Whereyougo into c:geo currently would do, so if I would have to decide between the two, I would vote for a filtering system as well.

**Comment by eddiemuc** [comment]
This issue is already very long and first implementation has been merged. 
Further enhancements should be tracked via separate issues, preferably assigend to project https://github.com/cgeo/cgeo/projects/16 (Flitering/Searching)

I will thus close this issue
