### ISSUE TITLE
Locked OC cache cannot be loaded

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9083]
Unclear whether failure or intended behaviour of OKAPI:

- Have oc.de enabled and authorized
- Search for geocode OC1556C

Result:
c:geo reports "Failed to download cache details"
Log shows HTTP result code 400

Expected result:
Not sure, as this cache seems to have been locked and also deleted (according GDPR)
@teiling88  What is the intended behavior of OKAPI in such case? Perhaps we could show a better errror message in c:geo.

**Comment by bekuno** [comment]
Maybe this problem? https://github.com/opencaching/okapi/issues/565#issuecomment-699645419

**Comment by teiling88** [comment]
Hey @Lineflyer,

atm the okapi didn't returns archived caches. If I find some time, I will create a PR for okapi that only archived and hidden caches are not return.

Greetings

**Comment by Lineflyer** [comment]
Another related finding according to some user:

A user reported, that when he tries to refresh a certain OC cache it still looks like it can be found. 
The cache is OC15789. 

I assume the user saved it in c:geo before it got deleted/blocked and as c:geo fails to refresh the data the outdated information keeps being shown. 

Therefore it would be highly appreciated if OKAPI would return also blocked/archived/etc. caches (with appropriate status information). While we don't get any information back from OKAPI we can not judge what to do with this cache.

**Comment by rsudev** [comment]
I think it would be necessary to first analyse what OKAPI actually returns in this case. As it also can be, that someone creates and imports a GPX with an arbitrary OC-code (e.g. due to accidentally exchanging some of the digits) we should in a constistent fashion handle the case, that a cache is (no longer) known by a connector it should belong to.

**Comment by Lineflyer** [comment]
> I think it would be necessary to first analyse what OKAPI actually returns in this case.

As written above it returns HTTP Error 400.

**Comment by rsudev** [comment]
In the end, yes (I read that). But I am not sure, which 'question(s)' we place in the end and possibly before (and what information they migth receive), that was rather my line of thinking. But it might well be, that we get this result (Status 400 is a completely legitimate result of nothing more is to say about a topic), we just need to handle it sensibly (Perhaps introducing the status 'blocked' and/or 'not known by connector' for a cache).

**Comment by Lineflyer** [comment]
As far as I understood this case is simply a kind of fault or maybe a not covered case, that OKAPI cannot handle archived caches. Once this is solved c:geo will handle it perfectly fine.

**Comment by bekuno** [comment]
The okapi answer in detail:
~~~
{
  "error":
  {
    "developer_message" : "Parameter 'cache_code' has invalid value: This cache is not accessible via OKAPI.",
    "reason_stack":
      [
        "bad_request",
        "invalid_parameter"
      ],
    "status" : 400,
    "parameter" : "cache_code",
    "whats_wrong_about_it" : "This cache is not accessible via OKAPI.",
    "more_info" : "https:\/\/www.opencaching.de\/okapi\/introduction.html#errors"
  }
}
~~~

**Comment by bekuno** [comment]
I opend an issue for this problem at https://github.com/opencaching/okapi/issues/600

**Comment by rsudev** [comment]
Having looked into it I agree with the notion that this is an OKAPI bug. The cache is still visible on the website, it should be returned through OKAPI with the same information.

**Comment by eddiemuc** [comment]
Not an issue in c:geo but in OKAPI. Thus closing here
