### ISSUE TITLE
Premium Cache Not Showing logs

### ISSUE THREAD

**Issue by pictom1** [cgeo/cgeo#9085]
**Describe the bug:**
The app will not show previous logged logs for premium caches. I can view logs for non- premium caches. 

**To Reproduce:**
Look for logs on any premium cache. 

**Expected behavior/state after performing these steps:**
Iexpect to see the logs. 

**Version of c:geo used:**
2020.09.26-RC (but I've had this issue on previous versions) 

**Is the problem reproducible:**
Yes 
**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
--- System information ---
Device: SM-S767VL (j7topeltetfnvzw, samsung)
Android version: 9
Android build: PPR1.180610.011.S767VLUDS7BTE2
c:geo version: 2020.09.26-RC
Google Play services: enabled - 20.33.15 (100300-330018294)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: original 
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (999.2 MB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (979.2 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (979.2 MB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (10.6 MB) on system internal storage
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/cgeo/maps
Map render theme path: 
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: MMM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---

```

**Comment by geocachermgo** [comment]
I could not verify this problem with GC7N9R3 and 2020.09.28-NB-2f87ae0. All logs are there.
Is this regarding all logs of any PM cache you load into c:geo?

**Comment by moving-bits** [comment]
AFAICS from your attached system info you are logged in as a basic member.

As a basic member the website geocaching.com does not provide you with details for premium member only caches, therefore you cannot see any logs for them.

**Comment by pictom1** [comment]
Yes, this happens for ALL premium caches. I have multiple family accounts with only one being premium. I log on with the premium account, download all the geocaches in an area, then log in on a basic account. The premium caches are downloaded, but the logbook is empty.

**Comment by pictom1** [comment]
![Screenshot_20200928-070659_cgeo](https://user-images.githubusercontent.com/71992117/94425107-58e43500-0159-11eb-8ef4-74a7851fa8ba.jpg)


This is a screenshot of me signed in on our premium account. Everything downloads except the logs, including photos posted in those logs.

**Comment by Lomanic** [comment]
Shouldn't cgeo inform the user about this?

**Comment by moving-bits** [comment]
Thanks @pictom1 for your addtional info. Reopening the issue.

There may be a problem with switching between different accounts, I remember some issue with it from the past. C:geo ist not built to use different accounts at the same time, so workaround for this is completely restarting c:geo after switching accounts. - Do you completely remove c:geo from memory after having switched the accounts?

**Comment by geocachermgo** [comment]
You can store a Premium cache log as basic member A and you logout and login again as member B and send that log, it will be a log for B, even if A wrote an stored the log.

**Comment by geocachermgo** [comment]
Was the system file created when you were logged in with your premium account?

**Comment by geocachermgo** [comment]
So the sequence is:
you log on as premium, download, logs are there.
Then you change the account, (reload?) and the logs a gone?
I just tried: On my device the reload of a premium while I'm logged in as basic is not changing anything nor is there a message, that it cannot be reloaded.

**Comment by pictom1** [comment]
> Thanks @pictom1 for your addtional info. Reopening the issue.
> 
> There may be a problem with switching between different accounts, I remember some issue with it from the past. C:geo ist not built to use different accounts at the same time, so workaround for this is completely restarting c:geo after switching accounts. - Do you completely remove c:geo from memory after having switched the accounts?

No I don't completely shut down the app. BUT I can download the premium caches while in my premium account, and the logs do not show. 

What I think you're saying is to log in on my premium account, then shut down the app, reopen the app and download the premium caches. I will try this as well as clear the phone's cache.

**Comment by pictom1** [comment]
> You can store a Premium cache log as basic member A and you logout and login again as member B and send that log, it will be a log for B, even if A wrote an stored the log.

Logging is not an issue.

**Comment by pictom1** [comment]
> So the sequence is:
> you log on as premium, download, logs are there.
> Then you change the account, (reload?) and the logs a gone?
> I just tried: On my device the reload of a premium while I'm logged in as basic is not changing anything nor is there a message, that it cannot be reloaded.

No, that's not correct. Premium logs never download.

**Comment by pictom1** [comment]
THAT'S IT! 
I had to log into premium account then close app. I then went a step further and went into the phone's settings,  and did a Force Stop. I shut down the phone, turned back on and refreshed the premium caches and all the logs downloaded and show up now.
