### ISSUE TITLE
add correct timestamps to position history

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9097]
I have position history active. I have cgeo active only for the search and at home for finishing logs etc. So from one seach I have I little piece of track and another one from the next search. On the map they are connected and after a while I get a star with my home in the middle and a lot of connections to the caches I found. 

I would like to have the connections between the track pieces not shown.

If this is an issue not only for me we could discuss about a solution.

E.g. having a time / distance criteria: do not draw a line if the distance between track points is (>500 m and 5 min).

**Comment by Lomanic** [comment]
Linked (duplicate?) to #7506. I think the proposed fix there (don't draw connections between too much remote points) is not optimal. cgeo shouldn't draw connection to the default home coordinates, if possible it should check if it has a GPS fix before drawing the history line.

**Comment by geocachermgo** [comment]
Thank for referencing this. 
Yes, from the requirement (I want no "star" they didnt want "spaghetti") it's a duplicate.
If I got it right, its implemented, with a fixed value of 10km?
My typical radius is smaller, so I still get the connection lines. My break suggestion was based on how long/ far can you be without GPS position.

@moving-bits wrote in April:
> A different approach could be "no line, if two consecutive points are from different days", but that would require adding a timestamp to the trail history, so I'm in favour of the first approach.

I checked the exported trail: There is a time stamp for each point, so drawing no line if time difference is > threshold should be no problem.

Would a parameter in settings (break track time and/or distance) be an improvment?
How do you think about reducing the break distance from 10km to 0.5km or something in between?
To be considered:
 You might download a track with no or arbitray time stamps.

**Comment by moving-bits** [comment]
From the source code:
- we do not draw a connection between two consecutive trail points, if they are at least 10 km apart from each other
- we do not save date or time values (the values you see in the export are "fake" values to make OSM import happy)

Proposal would be
- to save a date value into the history
- and to skip a connection line if dates are different

Regarding the minimum distance I would prefer to not lower the value to eg. 500m, as it might me that you're using a bike or a car during your caching trip. Splitting among different dates should cover most use cases IMHO.

**Comment by eddiemuc** [comment]
> Proposal would be
> - to save a date value into the history
> - and to skip a connection line if dates are different


I would modify slightly the skip condition: skip a connection line if timestamps are more than e.g. 1 hour apart 
This might prevent false skips when someone is caching around midnight.

**Comment by geocachermgo** [comment]
Not related to this problem but why are we not having a real trail and are storing the timestamps?
Storage, privacy, ..?
For my use case your suggestion will not help. I typically open c:geo after the cache tour at home and will still get the line to my home. So it seems I have to extend my homezone to r > 10km :-)
The breaks should be permanent. If there are no timesteps in the position history there needs to be a separate list of breaks. I think thats ugly.
Then I would prefer to modify the threshold value of 10 km in the settings.

**Comment by moving-bits** [comment]
> Not related to this problem but why are we not having a real trail and are storing the timestamps?
> Storage, privacy, ..?

I'm not sure, but I suspect it to be for in-memory size, or maybe just because nobody had a need for it until now.
The first possible reason should be much less-common with today's hardware, that's why we optionally increased the trail length meanwhile.
=> IMHO there's no reason not to introduce a timestamp for history trail.

> I typically open c:geo after the cache tour at home and will still get the line to my home.

Which is to be expected for a position history. The simplest solution to this would be to turn off "location mode" in your phone after your cache tour, or at least before re-opening c:geo after your return.

Or we need to implement some workaround for this use case, such as the one @Lineflyer suggested (although that might not be without pitfalls as well). Also setting a lower distance limit would have side-effects (actual tours being split-up), so we would have to make this a separate settings. Not sure if this is really needed, taking into consideration that we have a working solution for your use case.

**Comment by geocachermgo** [comment]
> timestamp for history trail.

Are we talking about the same thing?
I was expecting a real time stamp for every point in the track like e.g. a garmin is creating.
I understood that you are discussing a separate timestamp of beginning and end of the track. Or did I got that wrong?

For me it's not high prio but a nice to have extension. At the moment i just erase the recording when the spagetti gets too dense.

**Comment by moving-bits** [comment]
> > timestamp for history trail.
> 
> Are we talking about the same thing?

At least I think so :-)

> I was expecting a real time stamp for every point in the track like e.g. a garmin is creating.
> I understood that you are discussing a separate timestamp of beginning and end of the track. Or did I got that wrong?

I'm talking about storing the individual timestamp for each point in position history in this case. This could be used for a date-based break in drawing the trail as well as in exporting the trail to a GPX file.

**Comment by geocachermgo** [comment]
Ok, I think we have a common understanding.
I would appreciate this as being a real track/position history. The possibility to optimize the drawing is a secondary aspect. I would suggest a seperate issue for that.

**Comment by moving-bits** [comment]
I'm currently working on adding the timestamp (being delayed by some db upgrade issues I encountered along the way).

While thinking about it more in-depth, I recognize that adding a timestamp will not help with your initial issue of "spaghetti lines" around your homezone:

As long as you leave location mode activated (and c:geo running in foreground with screen activated) it will continuously add trailpoints to the history, so there will be neither a relevant time gap between two trail points nor a relevant distance gap.

When you switch your screen in c:geo off or disable location mode, c:geo will stop recording new trailpoints, thus avoiding the lines all connecting to your home zone. => So this is the way to go if you want to avoid the connecting lines.

Besides that, adding timestamps will still be useful:
- for exporting the trail with correct timestamp
- for being able to not connect lines during drawing, if two trail points exceed a certain minimum time diff. [This would help with caching in different areas]

**Comment by moving-bits** [comment]
> I would appreciate this as being a real track/position history.

Ok, I'll change the issue title accordingly.

**Comment by geocachermgo** [comment]
As you correctly mentioned the "connection" problem still open for the short distance cacher. Shall I open a new issue for this? (Possible solutions : lower current 10km threshold, make km threshold adjustable, add fixed/time threshold). Is see that there are different expectations. I'd like to have mainly the walking phases on the map, whereas others want so see the different caches searches of a daytrip shown connected.

**Comment by moving-bits** [comment]
> As you correctly mentioned the "connection" problem still open for the short distance cacher. Shall I open a new issue for this? (Possible solutions : lower current 10km threshold, make km threshold adjustable, add fixed/time threshold).

Feel free to open a new issue for that, but alas, I don't see any solution for it except the following:
- switch off location mode (which you do not want to, for valid reasons), or
- close c:geo / put it in the background / switch off the screen

(all of those methods stopping c:geo from collecting new trailpoints)

_Why is a limit lower than 10 km not a solution to your problem?_
_Why is a min timestamp diff not a solution to your problem?_
=> Both for the same reason: As long as c:geo and location mode are both active, c:geo will collect new trailpoints, even if you are not geocaching at the moment. c:geo will store new trailpoints every 0.5 seconds (IIRC), so the min time diff rule would not fire, and the min distance rule won't fire as well (except you're really fast :-)).

**Comment by geocachermgo** [comment]
With the suggested values it would be a solution for me: I would still have a blob at my home but not connections from the the last acivity.

BTW and more fitting to the new title: if the track recording is interupeded, is the next new point at the old coordinates with the new time stamp? The was a flaw of the Garmin track.

**Comment by eddiemuc** [comment]
What about adding an option to simply switch on/off the tracking of trailpoints in c:geo?

**Comment by moving-bits** [comment]
> BTW and more fitting to the new title: if the track recording is interupeded, is the next new point at the old coordinates with the new time stamp? That was a flaw of the Garmin track.

Each trailpoint gets stored with the current timestamp at the time of storing that position. So if you return in the evening and start next morning from the same place, both times having c:geo + location mode activated, you will get two trailpoints with the same coordinates, but way different timestamps.

If you close c:geo etc. at the end of your evening trip, return home, and switch c:geo on the next day only at the start of your new trip, you will have different locations and different timestamps, and no connection line to your home location. End point of yesterday's trip and start point of today's trip will be connected, if they are less than 10 km apart, currently. (As this is the breaking point for drawing, as currently implemented. Minimum time diff to be implemented yet.)

**Comment by geocachermgo** [comment]
Is was not talking about the connections but only about the location/timestamps. Is there only a point stored if you have a fix or may the last coordinates be stored and then written with the new timestamp in case
-GPS fix gets lost
-location is switched off/on
-c:geo gets deactivated/activated again
-...
I'll check this when I will test the new feature but thought it would be fair to mention it beforehand

**Comment by geocachermgo** [comment]
> What about adding an option to simply switch on/off the tracking of trailpoints in c:geo?
Thats already there:
![IMG_20201003_162958](https://user-images.githubusercontent.com/43813636/94994098-c77c2500-0595-11eb-98d1-80b4a7f31d70.jpg)

**Comment by geocachermgo** [comment]
At the moment I find 15 decimals for the degree in the export. That is nm resultion! I think 7 decimals (cm) should suffice.

**Comment by geocachermgo** [comment]
@moving-bits Are you planning to also put the elevation in it?

**Comment by moving-bits** [comment]
> @moving-bits Are you planning to also put the elevation in it (currently constant 0)?

Haven't done yet, but why not? But depends on whether the data can be made available in that place.

Please open a separate issue if you would like such a feature, as this issue will be closed automatically after merging the related PR.

**Comment by geocachermgo** [comment]
If someone wants to create timestamps to a gpx file that has none,  there is a tool to create this via entry of start time and speed, so the timestamps are calculated from the distance of the points: [https://gotoes.org/strava/Add_Timestamps_To_GPX.php](url)
