### ISSUE TITLE
"show circles" setting not respected when switching from offline to GM

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9108]
Describe the bug:
If you switch for osm (online or offline) to GM the proximity circles are not shown on GM map, you have to disable and re-enable it.

To Reproduce:

 open live map with osm map and set "show circles" 
   change map to GM or GM Satellit
       no circles are shown
  If you disable and enable the circle option the circles are shown on GM

Expected behavior/state after performing these steps:
GM should respect the "show circles" setting directly.

Version of c:geo used:
2020.10.01-NB-2c03b41

Is the problem reproducible:
Yes
See also #7843

**Comment by wolverine007** [comment]
I am facing the similar problem inside 2020.12.22-RC.

So definitely a bug.

**Comment by Lineflyer** [comment]
I just retested this according to the procedure described above and can no longer reproduce it with 2022.12.28-NB.
Closing.
