### ISSUE TITLE
Document multi-branch support for Crowdin translation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9119]
Follow up of https://github.com/cgeo/cgeo/issues/9031

First of all:
Multi-branch support is enabled now for c:geo...mostly flawledd but some Need-To-Know we should document.

The following should be added:
- No restrictions on adding strings to `release` from now on. However as we might probably do that short before releasing the version, time for translators is limited, thus still ending in less translations provided in the version.
- The core team should know, that after merging translations for `release` they need to merge the change to `master` as applies for all other commits. Merging should be done before merging the (same) translations on `master`. Even if not, problems should be the exception but depend on the nature of change.
- We should avoid changing existing strings on `master` as this will change them also on `release`. Only to be done in intentional cases (e.g. fixing a wrong description). Do not change existing strings for reflecting a changed functionality only applied to one branch. New feature = New string (or reuse string BUT unchanged).
- Before we might think of adding  `cgeo-legacy` branch to the Crowdin process we have to consider if the point above might lead to unwanted effects. At least we should modify `crowdin.yml` on `cgeo-legacy` to exclude playstore descriptions as they do not apply to `cgeo-legacy` and those files always have the same name.

**Comment by fm-sys** [comment]
Two questions about the new multi-branch Crowdin translation:
1. Is it possible to rename the automatic PR title for release branch to something like "New Crowdin updates (Release)"
2. Do we need a daily PR at all? Wouldn't it be enough to merge them once a week or maybe even only manually before generating a google play apk?

**Comment by Lineflyer** [comment]
> Is it possible to rename the automatic PR title for release branch to something like "New Crowdin updates (Release)"

I searched for that, unfortunately it seems it is not customizable

> Do we need a daily PR at all? Wouldn't it be enough to merge them once a week or maybe even only manually before generating a google play apk?

24 hours is the minimum (not less frequent), what can be set on Crowdi. However we can just leave the PRs open as long as we want. Crowdin will push new commits every 24 hours into those PRs.

**Comment by Lineflyer** [comment]
Documentation has been done in our repo wiki a while ago.
