### ISSUE TITLE
Make "toggle talking" to a real toggle-button 

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#9127]
**Is your feature request related to a problem?**
Not really. Just consistency in UI.

**Describe the solution you'd like**
The menu-entry "toggle talking" should be a real toggle button like "Prevent waypoint from note". There the text is changing due to the current setting.
So the two states could be
- Start talking / Start speech
- Stop talking / Stop speech

**Describe alternatives you've considered**
Implementation like the other toggle-button. New icon is necessary (could be easily created from original icon and "main_nearby_disabled.png"

**Additional context**
![grafik](https://user-images.githubusercontent.com/70113341/94975124-ef757500-0510-11eb-8c2b-d936145e1f41.png)

![grafik](https://user-images.githubusercontent.com/70113341/94996544-9c99cd00-05a5-11eb-87cf-e0a28fdc9e8a.png)

**Comment by eddiemuc** [comment]
Feature request confirmed

**Comment by murggel** [comment]
I would remove the icon for the toggle-button, until issue #12552 is solved (implementation of colored background for toggle-icons) and show only the text .

|Talking deactive - click to activate|Talking active - click to deactivate|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/70113341/77aa61f8-b4d5-4c9c-9b80-ea24e31fc7e3)|![image](https://github.com/cgeo/cgeo/assets/70113341/aecec901-3a0d-4672-83f6-5a3dbe55a61b)|

Or use the icon for the current state in the meantime? The icon will be shown in landscape mode.
|Talking deactive - click to activate|Talking active - click to deactivate|
|---|---|
|![image](https://github.com/cgeo/cgeo/assets/70113341/01324327-7b17-4094-99d1-dc68510f4899)|![image](https://github.com/cgeo/cgeo/assets/70113341/8b18f6d2-10cd-469c-92bc-679b94233ab9)|

**Comment by fm-sys** [comment]
Looks good! Both would be fine IMHO. If I had to choose I would probably go with the icons...

**Comment by murggel** [comment]
> Looks good! Both would be fine IMHO. If I had to choose I would probably go with the icons... 

The one without icon is used, if it occurs in the menu, the one with icon is used in the "header" row, so both versions are used.

**Comment by murggel** [comment]
> The icon currently used is a "message" icon, it's not saying anything related to "read/Talking" imho
> how about
> https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atext_to_speech%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024
> or https://pictogrammers.com/library/mdi/icon/speaker-message/ and https://pictogrammers.com/library/mdi/icon/speaker-off/

The icon I used was the current one, but your proposal looks better...

**Comment by murggel** [comment]
> The icon currently used is a "message" icon, it's not saying anything related to "read/Talking" imho how about https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atext_to_speech%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024 or https://pictogrammers.com/library/mdi/icon/speaker-message/ and https://pictogrammers.com/library/mdi/icon/speaker-off/

@ztNFny  is there any "disabled" version of https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atext_to_speech%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024 ? I like that better than the variant with the speaker

What do you think about

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:record_voice_over:FILL@0;wght@400;GRAD@0;opsz@24 and https://fonts.google.com/icons?selected=Material+Symbols+Outlined:voice_over_off:FILL@0;wght@400;GRAD@0;opsz@24

![image](https://github.com/cgeo/cgeo/assets/70113341/92e82b78-bb3e-4dd1-ad58-3aaea2ad856a)

**Comment by ztNFny** [comment]
> @ztNFny is there any "disabled" version of https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atext_to_speech%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024 ? I like that better than the variant with the speaker

I can create one if you want



> What do you think about
> 
> https://fonts.google.com/icons?selected=Material+Symbols+Outlined:record_voice_over:FILL@0;wght@400;GRAD@0;opsz@24 and https://fonts.google.com/icons?selected=Material+Symbols+Outlined:voice_over_off:FILL@0;wght@400;GRAD@0;opsz@24

This is more of a "person speaking", not "device speaking" imho

**Comment by murggel** [comment]
> > @ztNFny is there any "disabled" version of https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atext_to_speech%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024 ? I like that better than the variant with the speaker
> 
> I can create one if you want
 
Yeah  - that would be nice

> 
> > What do you think about
> > https://fonts.google.com/icons?selected=Material+Symbols+Outlined:record_voice_over:FILL@0;wght@400;GRAD@0;opsz@24 and https://fonts.google.com/icons?selected=Material+Symbols+Outlined:voice_over_off:FILL@0;wght@400;GRAD@0;opsz@24
> 
> This is more of a "person speaking", not "device speaking" imho

OK

**Comment by ztNFny** [comment]
@murggel do you have a branch I could push to?

**Comment by ztNFny** [comment]
Here you go:
![text_to_speech_FILL0_wght400_GRAD0_opsz24](https://github.com/cgeo/cgeo/assets/1258173/befb72f0-74d7-4e4e-9db0-9b1315801f9b)
