### ISSUE TITLE
Documentation links regarding the new storage access framework (Android 10+)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9137]
This item is for documentation purposes only to have a single place for documentation pointers regarding the new storage access requirements enforced by Android 10+. Can be deleted after successfully switching c:geo to use SAF, and maybe en extract of the docs should be referenced on our Wiki then.

**Comment by moving-bits** [comment]
Links we have collected so far:
- [Android documentation on storage](https://developer.android.com/preview/privacy/storage)
- [Info on use-cases](https://developer.android.com/training/data-storage/use-cases#handle-non-media-files)
- [migration guide](https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage)

**Comment by moving-bits** [comment]
Some new pointers:
- [Introduction: What is scoped storage](https://www.androidcentral.com/what-scoped-storage)
- [SO: Writing files to publicly accessible documents folder in Android Q - Scoped Storage](https://stackoverflow.com/questions/60179299/writing-files-to-publicly-accessible-documents-folder-in-android-q-scoped-stor)

Android documentation:
- [Access documents and other files from shared storage](https://developer.android.com/training/data-storage/shared/documents-files)
- [Data and file storage overview](https://developer.android.com/training/data-storage)
- [Access app-specific files](https://developer.android.com/training/data-storage/app-specific)

**Comment by eddiemuc** [comment]
I think this issue has served its purpose very well, I would close it now.
