### ISSUE TITLE
wrong timezone in position history

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9143]
**Describe the bug:**
I stored a position history. The time entry was 
`<time>2020-10-05T10:40:27Z</time>` but the time was CEST 10:40:27 so the correct entry should have been +02:00 instead of Z which stands for time zone UTC:
`<time>2020-10-05T10:40:27+02:00</time>`

main\src\cgeo\geocaching\export\TrailHistoryExport.java:
timezone Zero is hardcoded:
`final SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");`

**Comment by moving-bits** [comment]
c:geo is not storing any timezone info for history trail, just plain "UNIX epoch time" (seconds since 1970-01-01 00:00:00).

Would setting a timezone marker on export be enough? (Using local timezone at the time of the export.)

Or do we actually need to store individual timezone info for every trailpoint, because it may happen that someone has a trail spanning more than one timezone?

**Comment by geocachermgo** [comment]
At the moment we claim the timezone being +00:00 (abreviation Z) but we write local time (in my case +02:00). If we write local time we should omit the Z or add the time zone.
As far as I checked ISO 8601  the time zone is not mandatory.  But the clean solution would be to store the time zone in every waypoint. 
The date is also stored for every point.
(2014 I traveled from Portugal (+1) to Spain (+2) and Morocco (+1) and back and could not believe that Exif had no possibility to store the time zone. That was only introduced 2016. So the phone was automatically adopting the changing time zones and scambling the pictures.)
Crossing a time zone during a trip (esp. in the USA) will be quite a nomal thing. Even in central Europe if somebody records a trail during the switch of daylight saving time it could become an invalid track, since the time is jumping back.

**Comment by geocachermgo** [comment]
The inventors if the gpx format [https://www.topografix.com/GPX/1/1/gpx.xsd](topografix) write: _Creation/modification timestamp for element. Date and time in are in Univeral Coordinated Time (UTC), not local time! Conforms to ISO 8601 specification for date/time representation._

**Comment by moving-bits** [comment]
> The inventors of the gpx format [https://www.topografix.com/GPX/1/1/gpx.xsd](topografix) write: _Creation/modification timestamp for element. Date and time in are in Univeral Coordinated Time (UTC), not local time! Conforms to ISO 8601 specification for date/time representation._

This would mean that export could stay as is, and we do not need to store a time zone identifier in the database for position history, but we have to convert all date/time info to UTC before storing. - Correct?

**Comment by geocachermgo** [comment]
Yes, could be a possibility. (But of course you need the time zone to convert). I will look up a Garmin track, how they did it.
I think 12:00+020 would be better for noon but 10:00Z is also correct.
If its implemented until the nightly of 25.10. I could record a track spanning the switch of daylight saving time. :-)

**Comment by geocachermgo** [comment]
Looked it up: Thats the way it's done in the recording of my old garmins. I found no sign of the local time in the files. One example started at 7:00Z. Then I opened it in Mapsource the start time was displayed (correctly) as 9:00. I guess that this is a part of my Mapsource installation. But to do this correctly no need to know the daylight saving switching dates all the way back.
==>  For cgeo: as you suggested: keep 'Z' and shift the time by the time zone.

**Comment by geocachermgo** [comment]
Tested the new feature. Works very well thanks to moving-bits!
My findings:
1) Resolution of coordinates shoud be reduced to 1e-8 (1cm) currently we have 1e-15 which is nm.
2) My mapsource program didn't read the file unless I exchanged \<ele\> and \<time\>
In the gpx spec it's also ele first. So we should exchange that.
3) timezone works fine, mapsource shows the correct time.
4) The Garmin file has a lot of LF and whitespace. Our file is without any. Maybe we could add a LF after metadata and after each \<trkp\>.
5) I think the \<name\> in the metadata section could be omitted.

**Comment by moving-bits** [comment]
Thanks @geocachermgo for testing.

> 1. Resolution of coordinates shoud be reduced to 1e-8 (1cm). Currently we have 1e-15 which is nm.

That's more a matter of decimal representation of a binary float/double number. Too many decimals do not necessarily mean a better resolution, but cutting some decimals might very well lead to a different coordinate when the decimal representation gets read back into a in-memory binary representation. Thus I would rather not change it.

> 2. My mapsource program didn't read the file unless I exchanged <ele> and <time>
>    In the gpx spec it's also ele first. So we should exchange that.

I can try to exchange that, but IMHO it's not standard-conform that the program you're using is position-dependent.

> 3. timezone works fine, mapsource shows the correct time.

That was the intent of this PR :-)

> 4. The Garmin file has a lot of LF and whitespace. Our file is without any. Maybe we could add a LF after metadata and after each <trkp>.

Not sure if it would be possible at all the way we're constructing the XML - we're not outputting a bunch of characters, but we construct an XML-tree in-memory, which (hopefully) gets written in a standard-conform character representation.
Making this XML-stream human-readable is a task for your XML-reader.

> 5. I think the <name> in the metadata section could be omitted.

At least in the samples I got before implementing this export, a `<name>` tag always was present, so I considered it a required attribute (but I could look this up in the topografix XSD). But anyway, it does not harm IMHO, and it serves as a marker for source (position trail) and date/time of creation.

**Comment by geocachermgo** [comment]
I checked the [https://www.alltrails.com/de/converter](alltrails, ex gpsies) converter. Its reading our file. The gpx output has: linefeeds, 8 decimals, ele before time. (and adds 'on AllTrails' to our track name)

 `  <trk>
    <name>c:geo history trail on AllTrails</name>
    <trkseg>
    <trkpt lat="49.89012496" lon="8.761273776">
        <ele>215.00000</ele>
        <time>2020-10-20T16:13:39Z</time>
      </trkpt>`

reg. 1) I do not see how cutting of the mm, µm and nm of a measured value (not table value where you might make a 'identical' comparison), with relative accuracy of at max several dm) will do any harm, even if the value is later modified when transferred to another representation.
reg. 2) I agree, probably the prgram is not following the standard. It's outdated by 10 years but it was market leader then. Is successor BaseCamp following the standard? If everybody (?) is doing it that way, we could do it that way too (cf. putting in '<ele>0</ele> to make OSM import (also not following the standard) happy #8519)

reg. 4) Minor issue for me
reg. 5) Alltrail was not touching the name there but just reproducing. In my example files it was not included. No need for a change.

**Comment by geocachermgo** [comment]
> If its implemented until the nightly of 25.10. I could record a track spanning the switch of daylight saving time. :-)

As annouced I took a walk tonight and the results looks good. Thanks to @moving-bits!
