### ISSUE TITLE
[Nightly] App is quite unstable

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9146]
Since yesterday the nightly c:geo is quite unstable: App closing by itself, empty log not working at the first time, and other strange things.
I was not able to track something down as reproduceable but I want to mention it.

**Comment by fm-sys** [comment]
Hm... I had a quick look at the last commits, but I can't see any potentially dangerous changes. 

But I noticed already some weeks ago that c:geo is quite slow on my device. But maybe it depends on that I'm always using my last developer build instead of a regular nightly?

**Comment by Lineflyer** [comment]
No observation here yet. Will keep an eye on it.

**Comment by moving-bits** [comment]
If you have some logcat capability it would be nice if you could create a logcat for c:geo after a crash.
(Or if c:geo happens to run successfully at some point in time, you can create a log (extended) from within c:geo.)
If you do not want to post it here, you can send it to our support email address.

**Comment by MagpieFourtyTwo** [comment]
Over here no unusual behavior ... ok, admitted, c:geo crashes now and then, but that was (sorry) always the case, now and then.
But as long as such a crash is not reproducible, I just go on, being happy to have such a great tool,  ;)

**Comment by geocachermgo** [comment]
So do I. I just observed an (for me) unusual rise in strange behaviour (every few minutes).
@moving-bits : c:geo is usable. Does it make sense do do use the extended log after something strange happens or is Magpies approach better, and we concentrate to track such events down when we are close to release?

**Comment by MagpieFourtyTwo** [comment]
AFAIK a crash always puts LogCat messages, no matter if ``[X] Debug log`` is set or not.
Problem is, to reproduce it and get a scenario with deterministic results.
Without this, you can search forever, so reporting would not make very much sense, anyway, IMNSHO.

**Comment by moving-bits** [comment]
> So do I. I just observed an (for me) unusual rise in strange behaviour (every few minutes).
> @moving-bits : c:geo is usable. Does it make sense do do use the extended log after something strange happens or is Magpies approach better, and we concentrate to track down such events when we are close to release?

This is not depending on the point of time / release state. Yes, we do extra testing during beta phase and keep an eye on Play console during that phase, but it's fine for us to get an error report at any time. So if it's sort of reproducable, you can open an issue (if none exists for it yet), and attach an extended logcat, if needed.

Sometime we may ask you to activate some additional debugging by either checking `[x] Debug log` in Systems - settings, or by putting a file called `log-properties.txt` with some specific settings into the `logfiles` directory. But this is no "every day" setting, and should only be done if requested by the c:geo team (as it produces a lot of extra output data, which puts extra strain on your hardware).

**Comment by geocachermgo** [comment]
Resume:
* until not reproducable no action
* more then normal instability not observed by anyone else
