### ISSUE TITLE
Retirement of old profile page on gc.com

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9150]
As listed on [release notes](https://forums.geocaching.com/GC/index.php?/topic/358816-release-notes-website-upcoming-retirement-of-old-profile-page/) gc.com will retire the old profile page.

I am not sure whether we use that one for any purpose (getting find count or whatever else).

Please kindly doublecheck if there is any dependency to avoid upcoming problems.

Old page: https://www.geocaching.com/my/default.aspx
New page: https://www.geocaching.com/account/dashboard

**Comment by moving-bits** [comment]
From a quick glance into the source code it looks to me that we are not using the profile page at all:

I did a grep looking for 'default.aspx' - the only hits are for `p/default.aspx?u=...`, `map/default.aspx` and `pocket/default.aspx`, the first one being a search for a specific user, but not the profile page.

`account/dashboard` isn't used.

**Comment by bekuno** [comment]
The `/default.*` adresses (eg. `default.htm`) are typicly automatic parsed.
Looking for `/my/` instead I find at least it in `GCLogin.getAvatarUrl()` and `GCConstants.PATTERN_MAP_LOGGED_IN`

**Comment by moving-bits** [comment]
good catch, will prepare a PR

**Comment by moving-bits** [comment]
Closed with https://github.com/cgeo/cgeo/commit/4233d1f7c904967c579bfd50baf40880ab08c451

**Comment by bekuno** [comment]
We use not only the users own profile page but also the profile page of other users.

Old page: https://www.geocaching.com/profile/?guid=...
New page: https://www.geocaching.com/p/default.aspx?guid=

A search for `/profile/` results in hits
 - strings_not_translatable.xml
 - GCConstants.java (PATTERN_OWNER_GUID, PATTERN_TRACKABLE_OWNER, PATTERN_TRACKABLE_SPOTTEDUSER)
 - many test data (websites)

So we need to check/fix it until end of this month (30.11.20).

**Comment by fm-sys** [comment]
> GCConstants.java (PATTERN_OWNER_GUID, PATTERN_TRACKABLE_OWNER, PATTERN_TRACKABLE_SPOTTEDUSER)

These `/profile/` links are used on the GC website for linking other users until now, so we can't change the patterns as they are all for parsing website data

**Comment by bekuno** [comment]
We have to use the new profile site instead.
The old one will shut down at the end of this month.

**Comment by fm-sys** [comment]
Currently, the cache details page _always_ use the link to the old profile page, even if you have chosen the new profile page at the GC website. The link will redirect you to the new profile page automatically - I don't know if this will be changed...

![grafik](https://user-images.githubusercontent.com/64581222/98232594-200c5c80-1f5e-11eb-9726-b9af8280a3e1.png)

**Comment by bekuno** [comment]
You are right, there are the old adresses.
Maybe we should prepare a fallback solution to be prepared if this will be changed.
On the other hand I believe that forwarding of the old adress to the new page will stay at least for a while.

So only the one user entry in strings_not_translatable.xml is used to access the (old) profile page, imho.
And this will handled by a browser, not by c:geo.

**Comment by fm-sys** [comment]
> PATTERN_OWNER_GUID 

Done in #10000
> PATTERN_TRACKABLE_OWNER

Done in #10000 
> PATTERN_TRACKABLE_SPOTTEDUSER

Not done! Could it be that we have no unit tests for this pattern but it is broken as well? I will look into it...

**Comment by fm-sys** [comment]
> > PATTERN_TRACKABLE_SPOTTEDUSER
> 
> Not done! Could it be that we have no unit tests for this pattern but it is broken as well? I will look into it...

![Screenshot_20210215_165935_cgeo geocaching](https://user-images.githubusercontent.com/64581222/107969195-baddf380-6faf-11eb-94d2-425bc0f2bdf3.png)

Indeed, this is still broken in the current release. I will provide a fix. 

BTW, is there any trackable which is permanently in the hands of a different user (not the owner), so I can write a unit test for it?
