### ISSUE TITLE
Short click on "Saved Log" should not open context menu

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9151]
**Is your feature request related to a problem?**
Once upon a time, a short click on my ``Saved Log`` immediately opened it for edit.
Which is - ok, "was" - pretty handy, as I for sure do not need to translate it into my native language. Or need to decrypt it ... ;)
Moreover a short click should always be followed by an immediate action - context menus just appear on long clicks. Usually.

**Describe the solution you'd like**
Short click on ``Saved Log`` should immediately open it for edit.
(like ``Personal Note`` already/still does correctly, as well as Waypoint list entries ... and in fact everything else in Android ... and for the sake of consistency this should even apply to the rest of ``Logbook``: Short click => en/decrypt (as before); Long click => context menu).

**Comment by eddiemuc** [comment]
This was done by me as part of #8897 and as stated before I did it. here is the quote for reference:
> As already partly discussed in #2012 I would also use this to replace the long/short press logic with a simpler logic: short press opens context menu with all options for a log available (including convert using ROI13 as currently done on short press). If that's all right?

Personally I like the current way much better than the old one. I think that UX should be designed such that long-clicks are never necessary to perform actions on single items and are only used to mark (multiple) items in a list-like view (like you can see it e.g. in popular messengers or email clients) and perform group actions on them (e.g. "copy all", "delete all", ...)
But thats a personal preference only. I am open for reverting the old way or any other solution if the community prefers something else of course.

**Comment by MagpieFourtyTwo** [comment]
Of course, all has it's ups and downs, and most of it is personal preference, but IMHO getting a context menu on short click does not match common GUI standards. And even in c:geo it's pretty unusual ... even in (sorry) Windows, the context menu you usually get by right mouse click, is mapped to long click on all touch screens. And take c:geos context menu in waypoint list (for e. g. `Delete coordinates`` or ``Copy coordinates`` or ...) is reached via long click.

As for me, a short click should perform the most usual action for an entry. And esp. for a ``Offline log`` it is ``Edit``, same as for the ``Personal note`` ...

**Comment by eddiemuc** [comment]
You are right that currently the UX in c:geo is more in opening context menu on long-click. But I personally don't like the long-click-context-menu e.g. on waypoints either... I also don't think it is so easy to define the "most commonly used function" globally for all users (for example, my personal most-often-used action on waypoints is definitely the "Copy coordinates" function). And WIndows is optimized for mouse-oriented usage, not touch-oriented usage.

But you are right of course, in the end it is always personal preference. I would love to see some kind of global UX concept for c:geo actually.

**Comment by fm-sys** [comment]
I think directly opening the offline log on short click would be useful, but the decrypt/encrypt action is really not the most used action anyway so I would stay with the short click context menu for online logs...

**Comment by MagpieFourtyTwo** [comment]
Do not underestimate the normative power of the factual!  ;)
So, I in fact remember *way* more scenarios where a \<long click> shows a context menu than with \<short click> ...

Where|Item|\<short click>|\<long click>
-------|----|-----------|---------
Drawer|c:geo icon|**open** c:geo|**context menu**
c:geo Main|``Stored``|**open** last list|list selection
c:geo Main|``Filter``|filter selection|reset global filter
Cache List|List entry|**open** cache|**context menu**
Cache Details|Owner|**context menu**|**context menu**
Cache Details|Coords|switch format|**context menu**
Cache Details|Attributes|switch to text|switch to text
Cache Details|Any Other|---|**context menu**
Cache WPs|List entry|**open** for edit|**context menu**
Cache Descr|Hint|de/encrypt|**context menu**
Cache Descr|Personal Note|**open** for edit|**context menu**
Cache Logbook|Owner|**context menu**|**context menu**
Cache Logbook|Logs|**context menu**|**context menu**
Cache Images|Image|**open** big|**context menu**

... tbc ...

The list does not claim to be complete, but has been compiled to the best of my knowledge and belief.  ;)
In fact I just went through the GUI and simply tapped all obvious elements once short and once long.
But even if I missed one or the other, already now there seems to be a kind of clear tendency ... doesn't it? ;)

Assuming that this is it, there are just 3 out of 14 scenarios, where a \<short click> currently/suddenly ;) results in a context menu, all the rest leads to an immediate action, which can mostly be described as "open". Moreover these 3 "\<short click> contexters" lack a \<long click> action completely (resp. open the context menu on \<long click>, too) ... which I would name a "waste of possibilities".  ;)

OTOH I am not sure about a useful default action for ``Other logs``, too, so perhaps in Logbook we seize the opportunity of having no style guide yet, thus being able to be consistently inconsistent and use \<short click> on own ``Saved log`` to open it for edit (which would be conform with PN, which is IMO comparable) and context menu for the downloaded logs ...?

BTW: A \<short click> on Owner name in Logbook once led to contact search, didn't it ...?

**Comment by eddiemuc** [comment]
Hehe, how would I ever underestimate the normative power of the factual :-) :-) :-)

You list is very cool, I did not know about some of the hidden features. While I still don't like long-pressing action responses other than "select" I have to agree that de facto they are the c:geo UX standard for now.

So yes, I will create a PR changing short-click on own log to open log edit again. 

As for the downloaded logs: 
* maybe with #2012 we can change the short-click action for OWN downloaded logs to edit 
* what I personally always missed for "downloaded" logs was the possibility to select text snippets out of them (not the whole log, but just snippets, like you can e.g. do when long-clicking on the cache description, the Hint or the PN). This would be my personal preferred long-click-action on them. But I suppose that is out of the question hm?

PR will follow

**Comment by MagpieFourtyTwo** [comment]
> maybe with #2012 we can change the short-click action for OWN downloaded logs to edit

Would be quite cool, as nowadays we have to do this in the browser ...

> "downloaded" logs (...) select text snippets (...) when long-clicking 
> But I suppose that is out of the question hm

Nevertheless a good idea. Although a casual observer can possibly come to the conclusion, you may start to like long clicks ...  ;)

**Comment by eddiemuc** [comment]
> Nevertheless a good idea. Although a casual observer can possibly come to the conclusion, you may start to like long clicks ... ;)

...for selection purposes only :-)

**Comment by MagpieFourtyTwo** [comment]
Yeah, even with \<short click> = action you're in fact just selecting with \<long click> ... the (other) action you want to perform ...  ;)

**Comment by geocachermgo** [comment]
Is this result something to include in the #9052 ?

**Comment by MagpieFourtyTwo** [comment]
> [PR will follow]([url](https://github.com/cgeo/cgeo/issues/9151#issuecomment-704400000))

Polite reminder. ;)

**Comment by eddiemuc** [comment]
> > [PR will follow]([url](https://github.com/cgeo/cgeo/issues/9151#issuecomment-704400000))
> 
> Polite reminder. ;)

PR exists already for quite some time: #9158
But not merged yet

**Comment by eddiemuc** [comment]
I was just reminded that now there is a merge conflict on this PR. I will handle that, hopefully tomorrow evening.

**Comment by Lomanic** [comment]
Late to the party, but https://github.com/cgeo/cgeo/issues/9151#issuecomment-704142020 is exactly the same thing that I expressed in the PR that changed the long press handling on logs https://github.com/cgeo/cgeo/pull/9065#issuecomment-699127230.

While I didn't insist at the time, I realize now that the long press and the blue (at the time) menu replacing the top header on the page is just standard Android behavior and one of the few decent UX in cgeo (again, compare with any messaging app, in particular AOSP SMS).

**Comment by fm-sys** [comment]
> Short click on "Saved Log" should not open context menu

As discussed, a short click should open "edit log" for offline logs. This is meanwhile implemented... So let's close.
