### ISSUE TITLE
"Clear offline logs" does not remove indicator bar

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9152]
**Describe the bug:**
When being in a list, caches with offline logs have a colored indicator bar.
This bar should disappear as soon as the offline log is deleted - but when using Menu => ``Manage caches`` => ``Clear offline logs``, the bar will stay until you either open and close the listing or display the list on map and return to the list.

BTW: May be this happens in ``Select mode`` only (just got aware that I have not tested it without ``Select mode``).

**Version of c:geo used:**
2020.10.05-NB-c129c9e

**Is the problem reproducible:**
Yes

**Comment by fm-sys** [comment]
I can verify this, the same also happens without `Select mode`

**Comment by murggel** [comment]
Duplicate of #9222 ? Fixed with #9252 ?

**Comment by Lineflyer** [comment]
Yes, very likely. Thanks @murggel
