### ISSUE TITLE
testSearchTrackable failed - website change ?

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9155]
currently CI fails with
~~~
12:26:50  cgeo.geocaching.CgeoApplicationTest > testSearchTrackable[android-23(AVD) - 6.0] [31mFAILED [0m
12:26:50  	org.junit.ComparisonFailure: expected:<"[aefffb86-099f-444f-b132-605436163aa8]"> but was:<"[]">
12:26:50  	at cgeo.geocaching.CgeoApplicationTest.testSearchTrackable(CgeoApplicationTest.java:69)
12:26:50  cgeo.geocaching.CgeoApplicationTest > testSearchTrackable[android-23(AVD) - 6.0] [31mFAILED [0m
12:26:50  	org.junit.ComparisonFailure: expected:<"[aefffb86-099f-444f-b132-605436163aa8]"> but was:<"[]">
12:26:50  	at cgeo.geocaching.CgeoApplicationTest.testSearchTrackable(CgeoApplicationTes~~~t.java:69)
~~~

There was no change - so I asume a website change

**Comment by eddiemuc** [comment]
Can confirm, seems to be a wesite change. The GUID part of website now reads like this:
`<a id="ctl00_ContentBody_lnkPrint" aria-labelledby="lnkPrintSrLabel" href="sheet.aspx?guid=aefffb86-099f-444f-b132-605436163aa8">Print Info Sheet</a>`

I am preparing a change, do we need this for `release ` too?

**Comment by fm-sys** [comment]
Yes, all bug fixes for already existing features go to release AFAIK

**Comment by eddiemuc** [comment]
> Yes, all bug fixes for already existing features go to release AFAIK

afaik only those that are relevant enough to push to current release (which is productive already). 
I just made PR against master, shall I drop it and start another against release?

**Comment by eddiemuc** [comment]
PR #9159

**Comment by gcey** [comment]
Is this the reason, why I get "c:geo can't load data required to log visit", when I try to log a TB?
By the way, this message is correct for visited geocaches but not for TBs (which are not really "visited").

**Comment by eddiemuc** [comment]
Oh this might indeed be the case. If this is true then I guess PR should indeed go to release, as @fm-sys already said

**Comment by eddiemuc** [comment]
Created PR #9162 to release.

Unfortunately I can't test whether this solves the trackable log error mentioned by @gcey because I have no TB where I could issue a test log.

**Comment by Lineflyer** [comment]
We also have user reports "I cannot grab a TB"...so seems a website change indeed.

**Comment by bekuno** [comment]
> Unfortunately I can't test whether this solves the trackable log error mentioned by @gcey because I have no TB where I could issue a test log.

The message occures already when you open the log dialog.
I tested the PR, it is fine.
If necessary you can write your note to my TB97G3K.

**Comment by eddiemuc** [comment]
> The message occures already when you open the log dialog.

Thanks, I didn't know that. In this case I can confirm too that such a message no longer occurs.

**Comment by eddiemuc** [comment]
Created #9165 for legacy

**Comment by gcey** [comment]
Is there a plan, when this fix will be released?
It is quite a restriction, not to be able to log TBs any more...

**Comment by bekuno** [comment]
> Is there a plan, when this fix will be released?

@gcey see #6190
