### ISSUE TITLE
Next bugfix release

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9160]
Currently two bugfixes are at release/on the way.

- [x] PR #9148 for #9145 camera not usable for log images
- [x] PR #9159 for #9155 trackable website change

Do we have further issues for release?

**Comment by Lineflyer** [comment]
I will revisit Google Play console to check crashes.

**Comment by Lineflyer** [comment]
> I will revisit Google Play console to check crashes.

At first sight I do not see any new crashed with latest release (besides what is already listed somewhere here).

**Comment by Lineflyer** [comment]
Well, someone forgot to merge `release` to `master` after yesterdays commit to `release`. 
Now we have conflicts as consecutive PRs have been merged to `master`.

Auto-merging main/src/cgeo/geocaching/connector/gc/GCConstants.java
Auto-merging main/src/cgeo/geocaching/ImageSelectActivity.java
CONFLICT (content): Merge conflict in main/src/cgeo/geocaching/ImageSelectActivity.java
Automatic merge failed; fix conflicts and then commit the result.

Someone who is familiar with changes in ImageSelectActivity.java should fix the conflict while merging branches please.

**Comment by Lineflyer** [comment]
Probably only a whitespace fix conflicting here, still someone else should take a look.

In order to avoid such additional work in future, please do not forget to merge branches after commiting something to `release` please!

**Comment by Lineflyer** [comment]
> Probably only a whitespace fix conflicting here, still someone else should take a look.

Have to correct myself:
`ImageSelectActivity.java` was modified in bcc3c510ed6204dc5f9e803842a99c354d57d3b7 on `master` and in 3ff83b2f1829ad8c740e8bfcdee165da846f1df1 on `release`. So someone has to port the `release` part into the changed file on `master` while merging branches.

**Comment by eddiemuc** [comment]
> > Probably only a whitespace fix conflicting here, still someone else should take a look.
> 
> Have to correct myself:
> `ImageSelectActivity.java` was modified in bcc3c510ed6204dc5f9e803842a99c354d57d3b7 on `master` and in 3ff83b2f1829ad8c740e8bfcdee165da846f1df1 on `release`. So someone has to port the `release` part into the changed file on `master` while merging branches.

@Lineflyer those are all mine. Conflict was expected but unavoidable due to new features/heavy refactoring in master in the same araa. It would be easy for me to do the merge. Alas I don't have permission to do so. How do you want to handle this? 

Basically you can let the master win at merge, I fixed the issues in the master PR too (but there it had to be fixed at another place)

**Comment by bekuno** [comment]
PR #9159 should also be included in the legacy branch

**Comment by eddiemuc** [comment]
> PR #9159 should also be included in the legacy branch

Good point. How is this usually handled? Will you merge `release` into `legacy`or shall I issue a separate PR for `legacy`? (Warning: I have no way of testing `legacy`)

**Comment by Lineflyer** [comment]
> Good point. How is this usually handled? Will you merge release into legacyor shall I issue a separate PR for legacy? (Warning: I have no way of testing legacy)

Legacy will not be merged to/from anywhere. So just submit the same change as PR to legacy. I can test it prior to release on my Android 4.x device.

> @Lineflyer those are all mine. Conflict was expected but unavoidable due to new features/heavy refactoring in master in the same araa. It would be easy for me to do the merge. Alas I don't have permission to do so. How do you want to handle this?

The conflict was avoidable if after merging the change on release, we first merge branches and you rebase your change on master to that base. 
I will merge this evening and try to let `master` win. I will ping you for a doublecheck and you can provide correction if needed.

**Comment by Lineflyer** [comment]
@eddiemuc I made the merge. 
Please kindly check if https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/ImageSelectActivity.java on `master` is as expected.

**Comment by eddiemuc** [comment]
> > @Lineflyer those are all mine. Conflict was expected but unavoidable due to new features/heavy refactoring in master in the same araa. It would be easy for me to do the merge. Alas I don't have permission to do so. How do you want to handle this?
> 
> The conflict was avoidable if after merging the change on release, we first merge branches and you rebase your change on master to that base. Or: There was no need to include the fix also on `master` as we merge back `release` anyway.

The conflicting changes were from two different issues (one feature request developed on master, one bug needed on master AND release), and the feature request on master was already merged before I worked on the bug. So I don't think conflict was avoidable.

**Comment by eddiemuc** [comment]
> @eddiemuc I made the merge.
> Please kindly check if https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/ImageSelectActivity.java on `master` is as expected.

Thanks for merging and stepping through conflict resolution for me. ImageSelectActivity in master remains unchanged in master which is what I would expect.

**Comment by eddiemuc** [comment]
> > Good point. How is this usually handled? Will you merge release into legacyor shall I issue a separate PR for legacy? (Warning: I have no way of testing legacy)
> 
> Legacy will not be merged to/from anywhere. So just submit the same change as PR to legacy. I can test it prior to release on my Android 4.x device.

OK, I will try to do this in the evening

**Comment by bekuno** [comment]
You can also cherry pick the commit and integrate in release.

see eg. https://www.ralfebert.de/git/cherry-pick/

**Comment by Lineflyer** [comment]
> You can also cherry pick the commit and integrate in release (with PR of course).

At least if there are no major differences the commit depends on between `legacy` and `release`. Right now this might be the case, in some months it might no longer work by cherry-picking. At the end it depends on nature and complexity. For the constants it will probably work right now.

**Comment by eddiemuc** [comment]
> > > Good point. How is this usually handled? Will you merge release into legacyor shall I issue a separate PR for legacy? (Warning: I have no way of testing legacy)
> > 
> > 
> > Legacy will not be merged to/from anywhere. So just submit the same change as PR to legacy. I can test it prior to release on my Android 4.x device.
> 
> OK, I will try to do this in the evening

Created #9165 for legacy branch

**Comment by Lineflyer** [comment]
@moving-bits 
What about #9167 and #9166 for `release` ?

We should release a bugfix release rather soon and at least #9166 should be included, or not?

**Comment by moving-bits** [comment]
> @moving-bits
> What about #9167 and #9166 for `release` ?

Both rebased to `release`, quite easy thanks to @UniQP's hint :-)

**Comment by moving-bits** [comment]
> > @moving-bits
> > What about #9167 and #9166 for `release` ?
> 
> Both rebased to `release`, quite easy thanks to @UniQP's hint :-)

and merged to `release`, changelog updated, and branches merged

**Comment by fm-sys** [comment]
AFAIK everything is done so far, so we should go on and start the rollout for our users...

**Comment by Lineflyer** [comment]
Will do the release tonight.

**Comment by Lineflyer** [comment]
Starting (for both normal and legacy):
- [x] Check/Insert correct version name as headline in ```changelog-release.xml``` 
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
Done so far, now Google takes its time. Will revisit this topic later this night.

**Comment by geocachermgo** [comment]
![IMG_20201010_220344](https://user-images.githubusercontent.com/43813636/95664049-84e1bc00-0b44-11eb-9b78-f655da2320bb.jpg)
Out and used by 1/3

**Comment by Lineflyer** [comment]
Yes, we are done. Status triggered and info posted on social media. Thanks to all!
