### ISSUE TITLE
Include offline finds in [NUMBER] variable

### ISSUE THREAD

**Issue by laslingerland** [cgeo/cgeo#9163]
When using _Offline logging_, the [NUMBER] variable in the log template doesn't include the offline logs. Offline found logs of caches that aren't logged as found on the website should optionally be added to the current value of [NUMBER]. A nice feature to debug a wrong calculation here, would be a list of all caches that are found offline and not online.

**Comment by Lineflyer** [comment]
It should already be as you described starting with 2020.10.04 release. [NUMBER] should included the sum of online and offline finds. This has been tested and working.

Regarding calculation:
Please go to your history list and filter for "With own information" -> "With offline log" to see the list you requested.

**Comment by laslingerland** [comment]
O wow! That's great! Thank you for clearing.
