### ISSUE TITLE
Easy in-app bug submitting function

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9164]
> Yes, this problem occurred before the latest beta update. I was hoping the update would fix the problem. I couldn't find a "submit problem" link within the beta version of c:geo. That would be helpful.

_Originally posted by @pictom1 in https://github.com/cgeo/cgeo/issues/9145#issuecomment-704860761_

Any ideas where we could place such a function, to make bug submitting a bit more clear and easy for our users? 

Probably the support email is the right choice for this, aren't it? And/or what about a link to our GitHub repository?

**Comment by Lineflyer** [comment]
It was more or less done on purpose to direct users at prominent places/error message to our FAQ and user guide first, which then might also contains 2nd level to contact support by mail if it did not help.

Furthermore our support mail is also contained in "About c:geo".
For the beta version there is even a link to github and support mail in the Play Store entry.

I would leave it like that, as I am afraid, that the amount of support tickets containing easy to be fixed issues contained in our FAQ will rise. Already know approx. 30% of ticket are solved with a link to our FAQ. BTW: I would estimate we receive an average of 10 tickets/day at the moment, which rises to 1000 tickets/day in case of (server)problems. So I guess most people really wanting to get something fixed will find us.

**Comment by pictom1** [comment]
Can the link not just appear in beta versions? Where the arrow points on my image...
![Screenshot_20201007-152610_cgeo](https://user-images.githubusercontent.com/71992117/95378753-5d73c080-08b2-11eb-8d4d-939dda116644.jpg)

**Comment by fm-sys** [comment]
@Lineflyer Ok, agreed. But a link to c:geo's github repository would still be a nice addition in the about c:geo section... Not least also to call for developers ;-)

**Comment by Lineflyer** [comment]
@pictom1 Its right there: Support :)

@fm-sys Yes, why not.
