### ISSUE TITLE
Adapt to serverparameters/params

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9172]
Reminder to myself: Try to make use of serverparameters/params

Taken from https://github.com/cgeo/cgeo/pull/9166#issuecomment-705702665 by @Lineflyer:

> The AvatarUrl can also be loaded from https://www.geocaching.com/play/serverparameters/params which is probably the more efficient way...
> 
> Btw this page is already parsed from c:geo at other places, so maybe these requests can also be combined (pure guessing)?

Interesting, It also delivers other maybe useful information like the login state.

**Comment by fm-sys** [comment]
BTW, I don't know how nearby and the live map are currently parsed, but there is also a web API we could use:

https://www.geocaching.com/api/proxy/web/search?box=52.509719%2C13.3733434%2C52.205967%2C13.027462&take=500&asc=true&skip=0&sort=distance&origin=52.5100498%2C13.37385447900000054

D/T, found state, owner, favorite count, everything is included. It even lists up premium caches (without coordinates) for basic members...

And it would hopefully be more robust regarding website changes
