### ISSUE TITLE
description of local! backup

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9175]
The backup menu is only explaining that a database backup is made. There might be a missunderstanding that this backup is in the cloud (cf Whatsapp backup) and protects against losing the phone.
It should be made clear that to really have a backup , the backup file needs to be tranferred to an independend device.

**Comment by geocachermgo** [comment]
Current (German)
_Bitte beachten, dass diese Funktion Caches, Wegpunkte und die Einstellungen sichert, nicht aber Cache-Bilder._
Suggestion
_Bitte beachten, dass diese Funktion Caches, Notizen, Wegpunkte und die Einstellungen sichert, nicht aber Cache-Bilder. Um  die Daten auch nach Verlust des Telefons wiederherstellen zu können, sollten die Sicherungsdateien an einem unabhängigen Ort gespeichert werden._

**Comment by fm-sys** [comment]
I added it to the todo list. See https://github.com/cgeo/cgeo/issues/9104#issue-712512860

**Comment by geocachermgo** [comment]
Close this issue?

**Comment by fm-sys** [comment]
Up to you. Both would be fine for me...

**Comment by geocachermgo** [comment]
Tracked in #9104
