### ISSUE TITLE
icon for "upload to gc"

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9180]
For uploading offline information we have different icons.
For logs we use the paper plane: ![IMG_20201011_100444](https://user-images.githubusercontent.com/43813636/95673540-9dd08880-0ba9-11eb-80a5-6c78e7685241.jpg)
For notes we use the cloud with arrow.
![IMG_20201011_100424](https://user-images.githubusercontent.com/43813636/95673544-a628c380-0ba9-11eb-9d7f-25435538a6d5.jpg)
I think the actions are very similar, so the same icon should be used.

**Comment by fm-sys** [comment]
I think they have slightly different meanings, the first one is for submitting (usually you don't edit it again) and the second is for storing it online (sync/edit/upload again is quite common). So I would leave it as it is...

**Comment by geocachermgo** [comment]
Thanks for you optinion an for adding the label.
@eddiemuc annouced that he will tackle #2012 . If we can edit logs in c:geo they are even more alike.

**Comment by eddiemuc** [comment]
For "edit" actions, usually the pencil-symbol is used in c:geo
