### ISSUE TITLE
Location update only every 6-8 seconds

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9181]
I was out caching today using 2020.10.11-NB on my bike. It was rather some weeks ago since I last used c:geo while moving, and I noticed the following:

- While using the live map my own position is only updated every approx. 6-8 seconds...did not measure the update interval but it looks like a fixed time interval. This means, that while moving the position icon stays still until after these seconds it jumps to the new position.
- Similar behaviour if I look at the map while at position A, switch back to navigation app,  move to position B, switch back to c:geo. Takes again 6-8 seconds until my position jumps from A to B
- I also started the compass while driving and see the same problem: Distance to cache is updated only every 6-8 seconds

- Checked settings: 
  - Power saving is off
  - Disabling Google Play Services makes no difference

- Navigation app (Locus) and external compass (GPS Status) update position normally

Any idea, reproducible for anyone here?

**Comment by geocachermgo** [comment]
2020.10.12-NB-3659668 Checked compass distance while walking and blue arrow on live map: normal update freqency (~1Hz)

**Comment by Lineflyer** [comment]
I just used [Lockito](https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito&hl=de) (Nice app BTW) to simulate the track I recorded yesterday and also had no issues now.

Will keep this open for a few days to see, whether I can reproduce later on.

**Comment by Lineflyer** [comment]
Appeared once again yesterday and fixed by a restart of my device. So it seems to be some kind of device problem.
