### ISSUE TITLE
"Extract waypoints" does not update waypoint list

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9184]
**Describe the bug:**
Never ever had a scenario, where I could successfully use the function ``Extract waypoints`` (and now I know why ;) ).
As today I was happy to get a grip on a listing with no WPs at all, but three coords in the description, eventually, and was curiously looking forward to the result ... so while being in ``Waypoints`` list (which was empty at this point) I used Menu => ``Extract Waypoints`` ... but although the toast said "3 waypoints extracted", the list itself remained to be empty.  :no_mouth:

**To Reproduce:**
1. open a listing containing waypoint coordinates in the description
2. go to ``Waypoints`` list
3. click hamburger menu => ``Extract waypoints``
4. watch empty (resp. unchanged) list ...  

**Actual behavior/state after performing these steps:**
Waypoint list is still empty (although WPs most definitely exist).

**Expected behavior/state after performing these steps:**
Waypoints should be shown, i. e. WP list should be refreshed.

**Version of c:geo used:**
2020.10.12-NB-3659668

**Is the problem reproducible:**
Yes

**Additional context:**
Tapping the map icon in the header row does not help: Although the new WPs are there (and even show up in the map), they will not be displayed in the WP list, even after returning from the map again.
In order to see the WPs in the list, you have to either leave the listing and reopen it again or tap [Add Waypoint] followed by [X] or [Ok] - which is pretty much the same behavior we had a while ago when waypoints added via long click in the map did not show up int he list either.

**Comment by Lineflyer** [comment]
I was not aware, that this menu is also available while being on the waypoint list. :)
I always used it while reading the listing text and afterwards swiped to waypoints, which were then existing.

So it is quite sure only a refresh needed when performing this action while on the waypoint tab.

**Comment by moving-bits** [comment]
> As today I was happy to get a grip on a listing with no WPs at all, but three coords in the description,

I assume this is a listing on gc.com? Can you share the GC code for testing a possible fix?

**Comment by MagpieFourtyTwo** [comment]
Example: https://coord.info/GC9FD0

> I always used it while reading the listing text and afterwards swiped to waypoints, which were then existing.

Doesn't work either, at least over here.

**Comment by MagpieFourtyTwo** [comment]
Seems to work - great. Thx!
