### ISSUE TITLE
PN function "Add/Update Waypoints" should use "." instead of "," as decimal minute separator

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9193]
**Is your feature request related to a problem?**
When adding the waypoints to Personal Note, coordinates are formatted like ``dd° mm,mmm`` which may mathematically be correct, but is pretty unusual - and, even worse, leads to unexpected behavior when feeding these coords to various tools.

Example: This [bearing tool](http://gps-cache.de/geocaching/koordinaten-peilung.htm):
With the default coords "N52 30.871 E013 21.005" and "N52 30.977 E013 22.659" it computes a (correct) bearing of 83,992°.
But when you use dots instead of commata in e. g. the 2nd value "N52 30,977 E013 22,659", you will get 196,708°.
Which in fact took a while until I a) even noticed that there's an error, and b) recognized the reason for the strange result.

This may of course be considered a flaw in the bearing tool, but in fact the dot is the common decimal minute separator and there are a lot of tools out there, relying on it, thus the ``Add Waypoints`` routine should use the dot, too. Esp. as even c:geo uses it everywhere else.

**Describe the solution you'd like**
Format saved waypoints like ``dd° mm.mmm`` (i. e. with dot as decimal separator).

**Comment by eddiemuc** [comment]
I would consider this a bug, not a feature request :-) And I can confirm it.
I try to handle this today or during next days.

**Comment by MagpieFourtyTwo** [comment]
Ok - assumed this was by intention, thus I did not complain since.
Even better to have reported it eventually.  ;)

**Comment by eddiemuc** [comment]
Created PR #9195 towards release since this is also in current production version

**Comment by eddiemuc** [comment]
Sorry that was wrong. Issue is only in master, so PR to master is needed. Here it is: #9196

**Comment by geocachermgo** [comment]
The coordinates of a cache or waypoint are shown as    dd° mm, mmm but copied into clipboard as dd° mm.mmm. So it is consistent with that.

**Comment by eddiemuc** [comment]
> The coordinates of a cache or waypoint are shown as dd° mm, mmm but copied into clipboard as dd° mm.mmm. So it is consistent with that.

Hi @geocachermgo , in PR I was asked to look at your comment. But I don't understand it. Do you mean that the former behaviour was good (not a bug) or bad (a bug)?

**Comment by MagpieFourtyTwo** [comment]
I first did not understand it, too - but then I got an idea: If you have a look at the ``Waypoints`` page, the waypoint coords over there are displayed as ``mm,mmm`` (i. e. with comma), too. Same as the cache coords in the ``Details`` page, BTW. But copying these coords and pasting them anywhere, *seems* to "correct" this glitch, i. e. *seemingly* changes the comma to a dot.

But I think this is not a "correction", but in fact just the (dedicated) copy function, which copies the real data - which seems to (correctly) be formatted as ``mm.mmm``. Thus to me the comma in the ``waypoint`` list's and details page's coords just seems to be a matter of external representation - which BTW should be corrected, too. Did not recognize this till now, so, thanks to @geocachermgo for pointing this out.

Nevertheless, this is a separate issue (although just cosmetic) and not the same problem as with the coords in the PN, as their comma is not just a misleading external representation, but the real coords themselves. And they get copied as they are shown, which leads to described problems while forwarding these coords to further computations.

TMALSS: As the comma is simply not in accordance with common use, it should be changed - and to make it right, in all three places (or are there even more?).

**Comment by eddiemuc** [comment]
Ok, it seems that I mistook the topic as being a straightforward one, but I was in error obviously.
@MagpieFourtyTwo I am 100% with you, but my PR will currently only fix the one place. Also I saw during coding that someone recently introduced comma-separated coord representation intentionally, so it might be that community rather wants commas in their coords (depending on language setting).
Thus I will wait for further discussion. My PR still stands in case it should be used.

**Comment by MagpieFourtyTwo** [comment]
Just a moment to get things straight, cause here get two issues mixed up, which are in fact two different topics:
1. WPs copied/stored to PN
2. external representation of coordinates

While external representation may indeed be subject of discussion (in fact, even [ISO 6709 (Annex H)](http://www.xyz.au.com/members/intelligence/pdf_files/ISO_FDIS_6709.pdf) leaves the decision for the decimal separator (comma or full stop) to the local system, thus may even be language specific), but OTOH the notation for data which is meant to be forwarded to further processing, should preferably be standardized and esp. detached from language-specific settings, as these just complicate things.

So, comma would be ok, if it's just about external representation (although I even then would suggest to use the most common notation, which is most definitely with the dot).

But over here, where the data is mainly written to be restored to the WP list, thus has to be processed, it should be standardized, to make it as unambiguous as possible. Which in fact makes the dot obligatory. Even more, as the ``Store WP`` function is de facto just a kind of "extended copy&paste", which - in my opinion - should lead to the same result as a manually performed copy&paste does. So, "to be consistent", this copy should use dot, too, otherwise we would even get two different notations in PN ... which should be avoided, as well, I would say.

So, IMHO, this issue is as straight forward, as you assumed while reading it for the very first time. ;)

**Comment by eddiemuc** [comment]
Well, then just someone from core team needs to merge the PR :-) or provide code remarks if necessary

**Comment by MagpieFourtyTwo** [comment]
What a journey ... @eddiemuc: Thx for your persistence. ;)
And thx to @UniQP for the remarks and support.

**Comment by eddiemuc** [comment]
😁
