### ISSUE TITLE
[Info] Usage over daytime, Speed of version change

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9198]
I took the data from the status page and made some diagrams:
Users online: (time is UTC+2.00)
![Online_Users](https://user-images.githubusercontent.com/43813636/96292816-112f2b80-0fea-11eb-9037-fc579b703a8b.jpg)
Averaged distribution during the weekdays:
![Weekday](https://user-images.githubusercontent.com/43813636/96292874-2c01a000-0fea-11eb-9da9-981dee84e27c.jpg)
Averaged distribution during the weekend:
![Weekend](https://user-images.githubusercontent.com/43813636/96292903-391e8f00-0fea-11eb-8eba-fac3daf38107.jpg)
Looks like we have a strong majority of European users

And the remarkable speed of the (online) users updating:
![Version_Update](https://user-images.githubusercontent.com/43813636/96294287-6c621d80-0fec-11eb-986e-e99e865ee4bb.jpg)

**Comment by geocachermgo** [comment]
Just realized the day ribble in the percentage: The RC users have a higher share during the night.

**Comment by fm-sys** [comment]
Really nice! I had the same idea some weeks ago, but never had time for going it. Btw, for the country distribution you could take a look at the usage heatmap (www.cgeo.org/heatmap)

**Comment by geocachermgo** [comment]
AFAIS the heatmap ist getting the info from here: status.cgeo.org/api/locations but I do not know how to sort it into e.g. time zones
