### ISSUE TITLE
translation for japanese

### ISSUE THREAD

**Issue by ray4423** [cgeo/cgeo#9203]
hi, i am original japanese translator. i havenot been active for a long time.
i translated some text into japanese and modified for better translation on crowdin a week ago.
but not updated.
how long will the translation be accepted?
who is proofreader for japanese?

i contacted Lineflyer on crowdin, but i didnot get a reply.
so i ask again here,

some machine translation(google translations) is not correct and unnatural (like my english :-(
which strings is translated by google?
how can i check it?

**Comment by geocachermgo** [comment]
Hello ray4423san, thank you for your crowdin contribution. Please take into account, that we develop c:geo as a hobby, so there might be some days lag time. Normally @Lineflyer is very active here, even during his vacation.

**Comment by Lineflyer** [comment]
There might be translations done by others (maybe using the Crowdin autotranslate proposals), which we set as proofreaded after some months as no proofreader was around.

I will enable you as proofreader for Japanese in a minute. Feel free to disapprove wrong translations and replace and proofread them. We are grateful for your contribution.
