### ISSUE TITLE
[wiki] update info on "Send log to developers"

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9206]
I think that this [wiki page](https://github.com/cgeo/cgeo/wiki/Send-log-to-developers) is not up to date (date 2015 and refers to android <4 1).
Maybe it should describe a approach in steps:
1) send description + system info
2) change cgeo settings and send results see [new Logging page.](https://github.com/cgeo/cgeo/wiki/Logging) 
3) install additionally tools (alogcat?) and forward results
Background: There is a user on FB who reports that the app is shutting down when opening live map.

**Comment by Lineflyer** [comment]
You are right, the page is outdated.
Instead we could/should add the now more simple steps to send us a logfile via c:geo logging feature and also describe the possibility and preferences settable via log-properties.txt
Anyhow I am probably the wrong one to describe log-properties.txt as I did not yet work with this feature.

**Comment by Lineflyer** [comment]
I updated the page https://github.com/cgeo/cgeo/wiki/Send-log-to-developers to reflect the current situation (and took some info out of the other above mentioned wiki page). However its still a draft.

Feel free to review!

Question remaining:
I thought the reason for `log-properties.txt` was to enable retrieval of a logfile also in cases, where c:geo is not even starting...but thats wrong, isn't it?
So the `log-properties.txt` is only needed in case we need more fine grained logs compared to the in-app settings of debug log. Correct?

**Comment by eddiemuc** [comment]
@Lineflyer `log-properties.txt` can also be used to set fine-grained (e.g. debug) logging when c:geo is not starting or user can't reach settings dialog for whatever reason. However, the actual log file then needs to be extracted by the user via some logcat viewer app.

**Comment by geocachermgo** [comment]
Since update was done, I close the issue.
