### ISSUE TITLE
Waypoint Calculator Read/Write to Personal Notes

### ISSUE THREAD

**Issue by Billy-Wallace** [cgeo/cgeo#9211]
The **Waypoint Calculator** is a great new addition to **cgeo** and I will certainly use it for pre-planning field trips and for aiding me to enter values in the field with less chance of making errors, especially with complex formulas.

I do most of my pre-planning in **GSAK**. What would be a great addition to the WPC is the ability to save the data stored by the calculator to the **Personal Notes** and also to be able to read the WPC formatted data in the PNs and populate the calculator if the data fields are empty for that particular cache. In much the same way as we can now do with additional child waypoints.

This would allow me to create a macro in GSAK or even a spreadsheet (For batch processing) that would fill in as many values as possible and create the formatted WPC string ready to upload to the PNs. It would also offer the opportunity to work with other cachers and share the formatted WPC strings with each other when working towards large adventures.

The PN formatted string would need to be in a format that is easily parsed to populate the WPC fields.
{wpc-start}
@Coordinate Type
@Lat formula
@Long formula
@Main (capital) equation variables (1 to many) (delimited)
@Sub (lowercase) equation variables (0 to many) (delimited)
@Notes
{wpc-end}

I believe the PNs has a 2500 character limit, so there should be plenty of capacity to store personal notes + child waypoint formatted strings + WPC formatted strings.

_Keep up the good work cgeo team, it just keeps getting better and better, adding another fun element to Geocaching._

**Comment by Billy-Wallace** [comment]
I have been using this feature fairly extensively now and finding that for most cases, the Plain option is used.

Preparation in the Cache page Personal Notes, something like:
N50 57.(A+E)(B+B)(E) W001 21.(D)(B+D)(A+B+B)
telephone number 
023806ABCDE
short walk
Checksum 30

Then in cgeo, copy the PNs into the notes of the Waypoint and you have everything needed for the calculation.

So the ability to read/write the above section of the PNs would be all that was required if the team implemented this feature.

**Comment by murggel** [comment]
That would be a great feature for me as well, even, if the value of the variables are somehow exported too. I would use it in addition as archiv-functionaltiy in GSAK.
Or preparing there, calculate some values offline at home and the remaining out in the field.
One more point, but this would be a separate issue:
Some multi have only one set of variables for all stages. So it would be great, if the value of the variables are populated to all waypoints mit formulas, probably only on demand or as an option...

**Comment by murggel** [comment]
I can have a look at it, because I thought about that already.

**Comment by murggel** [comment]
see also comments on #9338 for best format for parsing the PCN

**Comment by Billy-Wallace** [comment]
As regards to flagging c:geo that we are dealing with a Calculated WayPoint (WP), @eddiemuc proposed a prefix of **CC**:

```
{c:geo-start}
@Calculate Finals (F) (CC:N50 27.ABC W001 39.(A-B)D(E+B))
...
```

To make the prefix clearer in purpose @murggel prefers to use **(FORMULA-PLAIN)**:

```
{c:geo-start}
@Calculate Finals (F) (FORMULA-PLAIN) N50 27.ABC W001 39.(A-B)D(E+B))
...
```

Would it not make more sense to add a new WP Type to the list?
  Parking Area                   PARKING        P
  ...
  Final Location	         FINAL	        F
  Calculated Coordinates	 CALCULATED	**C**

This would now be in common with other WP Types and there would be no need for an additional prefix:

```
{c:geo-start}
@Calculate Stage 2 (C) N50 27.ABC W001 39.(A-B)D(E+B)
...
```

**Comment by eddiemuc** [comment]
Just to be sure: I am not in preference of a specific prefix to use (whether it is CC of FORMULA-PLAIN or something else does not matter to me.

@Billy-Wallace I think introduction of a new waypoint type would not work since you can combine calculated coordinates with every waypoint type, and thus one must be able to express every waypoint type as a calculated type in the text too ("is calculated" is, so to speak, it's own somewhat boolean property of a waypoint independent of its type)

**Comment by murggel** [comment]
> Just to be sure: I am not in preference of a specific prefix to use (whether it is CC of FORMULA-PLAIN or something else does not matter to me.

Ok,  let me check about regex  for the formula. I guess it will be easier, if the type of the coordinates are known, so I would prefer some prefix which indicates the type.

For me it was more about how to store the variables...

**Comment by eddiemuc** [comment]
> For me it was more about how to store the variables...

Actually I like your approach for storing the variables with the pipe Symbols.

**Comment by Billy-Wallace** [comment]
@eddiemuc, I see your point regarding any waypoint might need to be calculated, so some prefix will be needed.

@murggel, Being able to read/write any variables would be a very useful enhancement to this feature.

Another enhancement I can see is to go straight to the calculator screen when the title is selected.
Currently, when you select the title, we are presented with this screen. 
![image](https://user-images.githubusercontent.com/65713561/98534681-b8ffe800-227c-11eb-80b5-52e63adb4481.png)

I do not think this screen is intuitive, in that to get to the calculator, you first have to select the coordinates and then select 'Calculate coordinates'
![image](https://user-images.githubusercontent.com/65713561/98535330-cff30a00-227d-11eb-896b-906c2236f403.png)

Once we have decided how to detect this waypoint as a Calculated waypoint, it would be much better if selecting the waypoint title that contains a calculation, it goes straight to the calculator.
![image](https://user-images.githubusercontent.com/65713561/98535531-2b24fc80-227e-11eb-98c1-327bdf85ec91.png)

I had spent sometime teaching someone to use this feature. When they were at the cache and selected the waypoint to enter their answers, they expected to see the calculations they had previously saved. Not remembering to select the coordinates first (as it is definitely not intuitive), they aborted in frustration and resorted back to paper and pencil.

**Comment by murggel** [comment]
> I do not think this screen is intuitive, in that to get to the calculator, you first have to select the coordinates and then select 'Calculate coordinates'

Yes, I thought also about some abbreviations to the calculator input, but how then come again back to the other input formats...

... and even if you entered a formula, you don't see any annotation, that there is one already. There is already a issue - I will link it

Also would be nice  if we could have only one set of variables for all stages of a multi  because I have some caches, where the same variable is used for different stages. But this would probably be a bigger effort ...

**Comment by Billy-Wallace** [comment]
> but how then come again back to the other input formats...

If I understand you correctly, surely it would simply be a case of changing the format from 'Plain' to the required format.
![image](https://user-images.githubusercontent.com/65713561/98551523-4e0edb00-2295-11eb-8a67-d759a613d3e2.png)

> one set of variables for all stages of a multi

Maybe we need the concept of global and local variables. Perhaps a tick-box next to the variable entry, that would make the default local variable become a global variable, if it is to be used for other calculated waypoints for a particular multi. 

If a new calculated waypoint is added, the global variables would be pre-populated in the calculator.

**Comment by murggel** [comment]
No, probabaly the "other input formats" was missleading.
I mean changing from CalculatorInput
![grafik](https://user-images.githubusercontent.com/70113341/98559255-ad291b80-22a6-11eb-8f7a-21d7af34f732.png)
to Coordinates Input
![grafik](https://user-images.githubusercontent.com/70113341/98559304-be722800-22a6-11eb-9a8c-ddbca6fc706c.png)
 could be difficult, if clicking on the coordinates jump directly to the CalculatorInput.
How could this be done? But I did not really think about it, so probably there is a easy way...

**Comment by Billy-Wallace** [comment]
> I mean changing from Calculator Input to Coordinates Input

I cannot see a use case where you would want to do that! If your intent is to create a calculated waypoint from the Personal Notes with, let's say:

```
{c:geo-start}
@Calculate Finals (F) (FORMULA-PLAIN) N50 27.ABC W001 39.(A-B)D(E+B)
"Calculation Notes here"
{c:geo-end}
```

When this cache page loads into c:geo, I would expect a calculated waypoint to be created and clicking the title would take us straight to the Calculator, (with the addition of a possible GUI for entering Global values):
![image](https://user-images.githubusercontent.com/65713561/98563762-78679500-22a3-11eb-9338-05353c4cb4dd.png)

So why would we need to change the Coordinates Input, as my intent is this calculated waypoint?

**Comment by murggel** [comment]
> So why would we need to change the Coordinates Input, as my intent is this calculated waypoint?

ok, probably it is academic.
...
hm, to clear the coordinates there probably can then be a shortcut in the calculator dialog, and then the normal process can take place

**Comment by fm-sys** [comment]
BTW, why do we need all these (annoying) pop-ups at all? Wouldn't it be much more intuitive to integrate these functions to the waypoint edit screen so all functions are directly accessible?

If there's some agreement on this I will open a new issue for discussion, cause it's far of topic ...

**Comment by murggel** [comment]
> If there's some agreement on this I will open a new issue for discussion, cause it's far of topic...

I guess it is worth it to discuss about. Probably you can link / use #6833 for that...

**Comment by Lineflyer** [comment]
Just a question related to the status of this issue:
I have seen PR #9791. This seems ti implement, that formulas can be IMported from a personal note.
But just today I realized, that existing formulas in waypoints (calculated waypoints) are not backed up with the waypoint back TO a PN. Is this WIP or should this already work bidirectional?

**Comment by murggel** [comment]
> Just a question related to the status of this issue:
> I have seen PR #9791. This seems ti implement, that formulas can be IMported from a personal note.
> But just today I realized, that existing formulas in waypoints (calculated waypoints) are not backed up with the waypoint back TO a PN. Is this WIP or should this already work bidirectional?
@Lineflyer it should work bidirectional, if the formula is not yet complete. If the waypoint has valid calculated coordinates, only the coordinates are exported, not the formula.
But this can be changed, so only the formula with all values will be exported. But then the coordinates are not exported, they will be recalculated on import. So the coordinates are then not really visible in the PN

**Comment by Lineflyer** [comment]
Ah yes. That was probably the reason they have not been exported in my case.

My idea was, that it would save me time to record the variables I found while doing the cache. So that makes me think we should also store the formulas and values of completed calculations. Then the backup of waypoints is really 100%.

**Comment by murggel** [comment]
Exporting of the other formats (<> plain) is still open.

**Comment by murggel** [comment]
Done with the new waypoint calculator and global variables.
I think we can close here.

Feel free to open new issues, if necessary.
