### ISSUE TITLE
Offline logged state not refreshed after clearing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9222]
2020.10.17-NB

- Open cache list
- Log one or several caches offline
- Return to list
- These caches do now have an orange marker line (as offline logged)
- Select Menu - Manage caches - Clear offline logs
- Confirm to delete offline logs

Result:
Offline logs are cleared but the orange marker line and offline smiley is still shown

Expected result:
List view should be refreshed after clearing offline logs and orange marker should no longer be shown

**Comment by Lineflyer** [comment]
Addition:
Just noticed, that it is even not updated when closing / opening the list after clearing the offline log but only on opening the cache details of one of these caches.

**Comment by eddiemuc** [comment]
As step 4 in your list you write: "These caches do not have an orange marker line (as offline logged)"

Is that a typo? I would expect them to have such a marker since you just added an offline log to them (and did not yet delete it)

**Comment by Lineflyer** [comment]
Yes...typo. Fixed. :)

**Comment by eddiemuc** [comment]
PR #9252
