### ISSUE TITLE
Active offline log status not shown in quick offline log view

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9223]
2020.10.17-NB

- Activate offline logging feature in Settings - Logging
- Open a list
- Open cache details of a cache
- Select Menu - Quick offline log - Found
- Select again Menu - Quick offline log

Result:
Same view with log types shown as when initially offline logging the cache

Expected result:
I am pretty sure, there used to be a red tick mark right of the currently active offline log in the offline log type selection view.

**Comment by moving-bits** [comment]
Hm, IIRC we had some issue with that tick mark some time ago already - not being shown or barely readable, depending on some system- or font-specifics. Need to lookup the issue number...

**Comment by Lineflyer** [comment]
You are right, its there but barely visible exactly as shown in #7630.
Thanks for looking it up.

Duplicate of #7630
