### ISSUE TITLE
New Lint issues on CI: NonConstantResourceId

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9224]
Not sure, if this is of any importance, but I just noticed a sudden jump in amount of coding issue by Lint on our CI:
![grafik](https://user-images.githubusercontent.com/949669/96506217-90756700-1257-11eb-9123-d2b9a16fb872.png)

It started with this job which reported 473 new issues:
https://ci.cgeo.org/job/cgeo%20continuous%20integration/3030/

Any relation to removal of eclipse parts or library updating? Just guessing...

**Comment by UniQP** [comment]
Looks like the increase is due to some new checks, so it's not a regression.

**Comment by bekuno** [comment]
We have now new 390 Issues of Type NonConstantResourceId.

Description:
Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes

~~~
Avoid the usage of resource IDs where constant expressions are required. 
A future version of the Android Gradle Plugin will generate R classes with non-constant IDs 
in order to improve the performance of incremental compilation.
~~~

Sample: `@BindView(*R.id.license) protected TextView licenseLink;`

**Comment by eddiemuc** [comment]
> Sample: `@BindView(*R.id.license) protected TextView licenseLink;`
> 

Ups. This is afaik the standard pattern in most of our activities to bind gui elements to class members using Butterknife lib. Should this be changed? Maybe even further: should Butterknife be removed m

**Comment by bekuno** [comment]
> Maybe even further: should Butterknife be removed?

The answer is yes.
See https://github.com/JakeWharton/butterknife
~~~
Attention: This tool is now deprecated. Please switch to view binding. Existing versions will continue to work, obviously, but only critical bug fixes for integration with AGP will be considered. Feature development and general bug fixes have stopped.
~~~

The view binding is documented here:
https://developer.android.com/topic/libraries/view-binding

**Comment by moving-bits** [comment]
We are also using those ID in switch statements to reference menu items, example from CacheDetailActivity:

```
0474 public boolean onContextItemSelected(final MenuItem item) {
0475     switch (item.getItemId()) {
0476         // waypoints
0477         case R.id.menu_waypoint_edit:
0478             if (selectedWaypoint != null) {
0479                 ensureSaved();
0480                 EditWaypointActivity.startActivityEditWaypoint(this, cache, selectedWaypoint.getId());
0481                 refreshOnResume = true;
0482             }
0483             return true;
0484         case R.id.menu_waypoint_visited:
[...]
```

How to replace those?

**Comment by rsudev** [comment]
I think this is a particular bad idea, to sacrifice the runtime performance benefit of final members for the sake of better incremental compile performance.
Can't we possibly disable this 'feature'?

**Comment by eddiemuc** [comment]
> We are also using those ID in switch statements to reference menu items, example from CacheDetailActivity:
> 
> ```
> 0474 public boolean onContextItemSelected(final MenuItem item) {
> 0475     switch (item.getItemId()) {
> 0476         // waypoints
> 0477         case R.id.menu_waypoint_edit:
> 0478             if (selectedWaypoint != null) {
> 0479                 ensureSaved();
> 0480                 EditWaypointActivity.startActivityEditWaypoint(this, cache, selectedWaypoint.getId());
> 0481                 refreshOnResume = true;
> 0482             }
> 0483             return true;
> 0484         case R.id.menu_waypoint_visited:
> [...]
> ```
> 
> How to replace those?

We could switch to Kotlin and use "when" :-) https://kotlinlang.org/docs/reference/control-flow.html

Ok, seriously, documentation I found recommends replacement of these cases with a series of if-else-statements. There'S even a quick-fix available for this in Android Studio.

**Comment by moving-bits** [comment]
> Ok, seriously, documentation I found recommends replacement of these cases with a series of if-else-statements. 

This is getting ugly with some of our more elaborated `onOptionsItemSelected` use-cases...

**Comment by eddiemuc** [comment]
> > Maybe even further: should Butterknife be removed?
> 
> The answer is yes.
> See https://github.com/JakeWharton/butterknife
> 
> ```
> Attention: This tool is now deprecated. Please switch to view binding. 
> Existing versions will continue to work, obviously, but only critical bug fixes for integration with AGP will be considered. 
> Feature development and general bug fixes have stopped.
> ```
> 
> The view binding is documented here:
> https://developer.android.com/topic/libraries/view-binding

I opened a new issue for Butterknife replacemend: #9232

**Comment by rsudev** [comment]
IMO the question remains if it is not possible to switch this off. The syntactic sugar of kotlin doesn't help with the runtime performance either.

**Comment by bekuno** [comment]
> Can't we possibly disable this 'feature'?

Yes, we can add it in the lint.xml files.

**Comment by moving-bits** [comment]
> > Can't we possibly disable this 'feature'?
> 
> Yes, we can add it in the lint.xml files.

But wouldn't that just suppress the warnings? Gradle behavior would remain unchanged.

**Comment by bekuno** [comment]
> > > Can't we possibly disable this 'feature'?
> >
> > Yes, we can add it in the lint.xml files.

OR in a  lintOptions block:
https://developer.android.com/studio/build/gradle-tips/?gclid=EAIaIQobChMI2bn__pLD7AIVieR3Ch0nmAsuEAAYASAAEgLQSPD_BwE&gclsrc=aw.ds#configure-lint-options

> But wouldn't that just suppress the warnings? Gradle behavior would remain unchanged.

I don´t believe that the Android Studio/android gradle plugin roadmap will go back to the old behavior.
So we can suppress the warning for now and we will have a better lint result, but we have also to change the code before AS/AGP 5.0.

Since AGP 4.0 is there a possibility to disable checks (buildFeatures).
https://developer.android.com/studio/releases/gradle-plugin?hl=de#buildFeatures
Maybe we can in this way suppress the tests and so the lint warnings.
As this is now a deprecated behavier we have to change the code before AS/AGP 5.0, I think.

**Comment by bekuno** [comment]
I created PR #9271 to hide the lint messages for NonConstantResourceId.
The check was not deactivatable with a buildFeatures parameter.

Let this PR open on the way to AGP 5.0.

**Comment by bekuno** [comment]
The 390 warnings are divided in two types
 - 204x Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes
 - 186x Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them in switch case statements

The first is tracked in #9232 the second in #9283

**Comment by bekuno** [comment]
Lets close here. The folloeing tasks are defined in own issues.
