### ISSUE TITLE
Remove Android 11 incompatability warning

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9225]
According to my comment https://github.com/cgeo/cgeo/issues/8457#issuecomment-709495213 there is no problem using c:geo with Android 11.
We should therefore remove the warning currently shown on main screen if c:geo is running on Android 11.

**Comment by Lineflyer** [comment]
This change should target `release`

**Comment by moving-bits** [comment]
I still have no clear image whether c:geo will work reliably on Android 11 or not.

Documentation seems to be (relatively) clear:
> "Apps that run on Android 11 but target Android 10 (API level 29) can still request the `requestLegacyExternalStorage` attribute. This flag allows apps to temporarily opt out of the changes associated with scoped storage, such as granting access to different directories and different types of media files. After you update your app to target Android 11, the system ignores the `requestLegacyExternalStorage` flag."
_(Taken from https://developer.android.com/about/versions/11/privacy/storage)_

So it _should_ work as long as we are using targetSDK 29 only, even when running on Android 11.
I have no due date for API 30 yet, but it might as well be November 2021, if Google continues increasing their requirement by 1 every year, so the remaining time is limited.

OTOH: Our quick tests so far seem to lead to different results - sometimes / in some configurations it works, in others it doesn't. (Eg.: Just fired up my Android 11 emulator and tried running today's master for c:geo on that => crashes on startup with not being able to create certain directories, although file permission have been granted already during an earlier run.)

I'm not comfortable with those diverging results. (Although they may be limited to the emulator.)

Thus for now I would stay with the warnings - both in changelog and the notifier. (But maybe we can rephrase them to adapt to the current state of our analysis.)

And we should continue our work on the `storage_framework` branch, as we need time (and users) for testing.

**Comment by Lineflyer** [comment]
> OTOH: Our quick tests so far seem to lead to different results - sometimes / in some configurations it works, in others it doesn't. (Eg.: Just fired up my Android 11 emulator and tried running today's master for c:geo on that => crashes on startup with not being able to create certain directories, although file permission have been granted already during an earlier run.)

I will again test new installation on a real Android 11 results to be on the safe side. Maybe something is different in nightlies as I only tested current `release`.

> Thus for now I would stay with the warnings - both in changelog and the notifier. (But maybe we can rephrase them to adapt to the current state of our analysis.)

Lets see some more testing first. I will report back.

**Comment by Lineflyer** [comment]
I also posted on FB and asked for community feedback from those users running Android 11 with c:geo (if any).

**Comment by Lineflyer** [comment]
> I also posted on FB and asked for community feedback from those users running Android 11 with c:geo (if any).

Result is: 21 comments, all using Android 11 with c:geo without issues.

**Comment by moving-bits** [comment]
Thanks for collecting the feedback. Looks like it does work on physical devices (and only stresses in the emulator). I'll prepare a PR to remove the automatic warning in the update area of the mainscreen.

**Comment by eddiemuc** [comment]
Does this also mean that the whole topic of moving to storage framework becomes uncritical/optional?

**Comment by moving-bits** [comment]
> Does this also mean that the whole topic of moving to storage framework becomes uncritical/optional?

Sadly: NO.
It looks like the current workaround works even under Android 11, which I'm glad to hear.
But the flag is only active up to targetSDK 29.

As soon as Play Store forces us to set targetSDK to 30 (which I expect to come in November next year), we need to have a working solution using SAF.

**Comment by eddiemuc** [comment]
> > Does this also mean that the whole topic of moving to storage framework becomes uncritical/optional?
> 
> Sadly: NO.
> As soon as Play Store forces us to set targetSDK to 30 (which I expect to come in November next year), we need to have a working solution using SAF.

OK. I am still awaiting some sort of feedback with regards to the technical solution I sketched here: https://github.com/cgeo/cgeo/issues/8457#issuecomment-706885184 
As soon as we have an agreement in what direction to proceed I am good to go

**Comment by eddiemuc** [comment]
> Thanks for collecting the feedback. Looks like it does work on physical devices (and only stresses in the emulator). I'll prepare a PR to remove the automatic warning in the update area of the mainscreen.

I wonder if this was done intentional by Google (be more strict in emulator than on physical devices) to subtly push developers in direction of storage framework :-)

**Comment by moving-bits** [comment]
> I wonder if this was done intentional by Google (be more strict in emulator than on physical devices) to subtly push developers in direction of storage framework :-)

Don't know, but quite possible... And probably not a bad thing in itself - as we ourself have ignored the SAF quite a few years only until now as Google pushes it :-)

**Comment by Lineflyer** [comment]
@moving-bits The change was only on master, wasnt it?
Because users still wonder about this message with 2020.10.29.

**Comment by moving-bits** [comment]
Hm, quite possible. Looks like I got a bit confused by our branches lately... I'll prepare a cherry-pick for `release`.
