### ISSUE TITLE
Butterknife should be replaced with ViewBindings

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9232]
The Butterknife framework, which is used in c:geo for binding views to class members, is deprecated
See https://github.com/JakeWharton/butterknife

Code samples:
<pre>
@BindView(R.id.filters) protected LinearLayout filtersContainer; 
          ~~~~~~~~~~~~
@OptionsMenu(R.menu.filter_options)
             ~~~~~~~~~~~~~~~~~~~~~ </pre>

Attention: This tool is now deprecated. Please switch to view binding. 
Existing versions will continue to work, obviously, but only critical bug fixes for integration with AGP will be considered. 
Feature development and general bug fixes have stopped.

It should be replaced with view binding as documented here:
https://developer.android.com/topic/libraries/view-binding

(This issue was brought up here #9224)

**Comment by moving-bits** [comment]
Thanks for creating the issue. IMHO we should wait with working on it until we've branched the next release, see #9226. It looks like we can do the migration step by step - otherwise a separate branch will be better probably.

**Comment by moving-bits** [comment]
This has been finished meanwhile, so let's close this issue.
