### ISSUE TITLE
change format of position history/track

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9239]
I checked the [https://www.alltrails.com/de/converter](alltrails, ex gpsies) converter. Its reading our file. The gpx output has: linefeeds, 8 decimals, ele before time. (and adds 'on AllTrails' to our track name)

 `  <trk>
    <name>c:geo history trail on AllTrails</name>
    <trkseg>
    <trkpt lat="49.89012496" lon="8.761273776">
        <ele>215.00000</ele>
        <time>2020-10-20T16:13:39Z</time>
      </trkpt>`

reg. 1) I do not see how cutting off the mm, µm and nm of a measured value (not table value where you might make a 'identical' comparison), with relative accuracy of at max several dm) will do any harm, even if the value is later modified when transferred to another representation.
reg. 2) I agree, probably the prgram is not following the standard. It's outdated by 10 years but it was market leader then. Is successor BaseCamp following the standard? If everybody (?) is doing it that way, we could do it that way too (cf. putting in `<ele>0</ele>` to make OSM import (also not following the standard but the output of the Germin devices) happy #8519)

reg. 4) Minor issue for me
reg. 5) Alltrail was not touching the name there but just reproducing. In my example files it was not included. No need for a change.

_Originally posted by @geocachermgo in https://github.com/cgeo/cgeo/issues/9143#issuecomment-713142338_

**Comment by moving-bits** [comment]
To make the references above understandable here's a copy of the original https://github.com/cgeo/cgeo/issues/9143#issuecomment-713017365:

> My findings:
> 
> 1. Resolution of coordinates shoud be reduced to 1e-8 (1cm). Currently we have 1e-15 which is nm.
> 2. My mapsource program didn't read the file unless I exchanged <ele> and <time>
>    In the gpx spec it's also ele first. So we should exchange that.
> 3. timezone works fine, mapsource shows the correct time.
> 4. The Garmin file has a lot of LF and whitespace. Our file is without any. Maybe we could add a LF after metadata and after each <trkp>.
> 5. I think the <name> in the metadata section could be omitted.

item 4 is already being dealt with (see #9238), I'll create a PR for item 2.
