### ISSUE TITLE
Distance for Individual route not properly calculated 

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9256]
**Describe the bug:**
There is still something wrong with the distance shown for Individual route: Although the value seems to be correct while *adding* points to the route, it will not be decreased, when points are *removed* from the route.

**To Reproduce:**
Imagine there are three caches (1), (2), (3), with 200 m walking distance between them
1. go to map page (no matter which map product)
2. long click on cache (1) to start an Individual route
3. long click on cache (2) to add it to the route => route distance: [200 m]
4. long click on cache (3) to add it to the route => route distance: [400 m]
5. long click on cache (3) to remove it from route => distance remains the same: [400 m]
6. long click on cache (3) to again add it to the route => route distance: [600m]

Every time you now remove and add cache (3), another 200 m will be added to the distance.
BTW: After removing all points from the route via long clicks, the distance will still be shown,
nevertheless, the menu entry "Individual route" => "Clear individual route" will not be shown anymore,
so there seems to be no possibility, to clear the route (as it's not there anymore, anyway ;) ).
Just "seems", as leaving and re-entering map will correct the distance resp. remove the distance display.

**Version of c:geo used:**
2020.12.21-NB-13e8311

**Is the problem reproducible:**
Yes

**Screenshots:**
If scenario is not obvious enough, I can even provide a screen record.

**System information:**
```
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.1.0.156(C431E19R2P5)
c:geo version: 2020.10.21-NB-13e8311
Google Play services: disabled - 20.39.15 (120400-335085812)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_DE
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (74,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (74,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (74,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (307,5 MB) on system internal storage
GPX import path: /storage/emulated/0/Download
GPX export path: /storage/emulated/0/Download
Offline maps path: /storage/0123-4567/Locus/mapsVector
Map render theme path: /storage/0123-4567/Locus/mapsVector/_themes/Elevate4/Elements.xml
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
BRouter connection available: true
```

**Comment by moving-bits** [comment]
Behavior confirmed on 2020.10.10 release version as well. I'll look into it.
