### ISSUE TITLE
Merge strategy for translations

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9259]
This is more or less a reminder to myself to finally figure out the best merge strategy for Crowdin translations now that we have two branches (`release` and `master`) connected to Crowdin.

The duplication suppression on Crowdin works as intended (showing same string IDs only once and use it on both branches).
However as usually strings might be removed or added on `master` while `release` is stable, changes keep coming in for `release` as soon as strings existing on both branches are modified in translation.

At first I tried to merge translations to `release`first, then translations to `master` and afterwards merge `release` upstream to `master`. This resulted in merge conflicts most of the time. 

It might make more sense to reverse this approach:
- Merge translations to `master`
- Merge translations to `release`
- Merge branches

As `master` does always contain all commits contained on `release` (as those branches are merged regularly) IMHO (with my limited Git experience) it should work out without conflicts in most cases....

Need to try this once more to proof.

**Comment by fm-sys** [comment]
Take a look at https://stackoverflow.com/questions/15232000/git-ignore-files-during-merge. Corse the translation files are totally created by Crowdin for both branches they never need to be merged and should be excluded...

**Comment by Lineflyer** [comment]
Yes, you are right. Merging would not be needed.
I did however not get the final best solution out of this article: If we use `.gitattributes` it sound like each repo user needs to explicitly take care to use it while merging. On the other hand the  `.gitignore` directory cannot be used as we need those files in the hierarchy, where they are currently placed.
Am I overlooking something?

**Comment by rsudev** [comment]
As .gitattributes is expected to be part of the repo, it should be taken into account automatically, once introduced, if I understood the documentation correctly.

**Comment by Lineflyer** [comment]
@rsudev 
You are right. This link explains quite good: https://medium.com/@porteneuve/how-to-make-git-preserve-specific-files-while-merging-18c92343826b

But as first step git config needs to be modified. Isn't that something each user needs to do in his repo used for merging before pushing?

**Comment by fm-sys** [comment]
> Isn't that something each user needs to do in his repo used for merging before pushing?

From my understanding it's not only local but stored inside the `.gitconfig` and `.gitattributes` file and can pushed to the repo

**Comment by Lineflyer** [comment]
I played around a bit with the `.gitattributes` configuration as described in the link above on a local test repo. It seems to work as intended.
I configured the dedicated "dummy" merge stratagy on repo level using `git config --local merge.ours.driver true`, it gets stored in `/.git/config` as 
```
[merge "ours"]
	driver = true
```
This works.
If I however create a `.gitconfig` file on root level of the repo fwith same content (and remove it in `/.git/config`) it is no longer in use. Does anyone know what else needs to be done to create a valid and working `.gitconfig`?

**Comment by Lineflyer** [comment]
Found something on https://stackoverflow.com/questions/18329621/how-to-store-a-git-config-as-part-of-the-repository

 It is not possible to automatically include your custom configuration file through git alone, because it creates a security vulnerability.

To apply this configuration for a single repository, each user will need to run the following command in your-repo/:

```git config --local include.path ../.gitconfig```

Reference: https://git-scm.com/docs/git-config#_includes

Will try tomorrow.

**Comment by Lineflyer** [comment]
I have successfully integrated this idea on WhereYouGo. Some manual tests have shown, that it seems to work as intended.

Will review once more and prepare the same change for c:geo.
