### ISSUE TITLE
Some TB pages not opening

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9263]
Reported on support mail and reproducible with the mentioned TB. According to user it happens on some but not all TBs.

- Search for TB9P7FK

Result: "c:geo could not find this trackable"

On the webpage this TB is shown normal.
Happens for secret code as well as public code (posted only the public code here).

Reproducible for me in 2020.10.10. and 2020.10.21-NB

**Comment by geocachermgo** [comment]
Another confirmation.

**Comment by moving-bits** [comment]
Seems they have changed their HTML on some pages, added "aria-hidden" attribute and removed "alt" attribute. I'll adapt the Regexp accordingly.

**Comment by moving-bits** [comment]
Old style is like this: `<img id="ctl00_ContentBody_BugTypeImage" class="TravelBugHeaderIcon" src="/images/WptTypes/21.gif" alt="Travel&#32;Bug&#32;Dog&#32;Tag" />`, it contains the TB type in the `alt` attribute, whereas the new style does not contain this information any more: `<img id="ctl00_ContentBody_BugTypeImage" class="TravelBugHeaderIcon" aria-hidden="true" src="/images/WptTypes/6338.gif" />`.

We can parse the type from the `<title>` attribute on that page, though, - the format is something like
```
...<title>
(TB-number) Type - Name</title>
```

example:
```
<title>
	(TB9P7FK) Tiffany the Zombie Travel Tag - Tiffany the Zombie Travel Tag
</title>
```

AFAICS this is the only place on the new page, where the type is still included.

I'll prepare a PR to catch both ways.

**Comment by Lineflyer** [comment]
@moving-bits 
This problem seems to expand at the moment (either more tb pages affected or more users noticing it).
Unfortunately the change went to `master` despite being a bugfix. 

Can you backport the fix to `release`?
So we could do a short bugfix release before the next big cycle.

**Comment by bekuno** [comment]
This is also a change needed for the legacy branch.

**Comment by moving-bits** [comment]
> This is also a change needed for the legacy branch.

It's truly a legacy... Created #9302 for it.

We should publish this before Play Store enforces their new rules, or we do have to push targetSDK for cgeo-legacy as well...

**Comment by Lineflyer** [comment]
> We should publish this before Play Store enforces their new rules, or we do have to push targetSDK for cgeo-legacy as well...

Yes, I will try to go for it latest this weekend, so it could be a 2020.10.31

**Comment by fm-sys** [comment]
Can this be closed or do we want to keep it open as a reminder for releasing a new (legacy) version until 31.10.?

**Comment by moving-bits** [comment]
Can be closed IMHO. Fix is merged to cgeo-legacy as well, and we have the 'Next release' issue as reminder.
