### ISSUE TITLE
Developer Environment: get "!!! JUnit version 3.8 or later expected" exception when running local unit tests

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9273]
Since one of the latest library / Android Studio upgrades (can't tell exactly which really triggered the problem) I get the following exception when trying to run local (non-instrumented) Junit-Tests:

(I use Android Studio to execute unit tests, NOT gradle command line)

```
!!! JUnit version 3.8 or later expected:

java.lang.RuntimeException: Stub!
	at junit.runner.BaseTestRunner.<init>(BaseTestRunner.java:14)
	at junit.textui.TestRunner.<init>(TestRunner.java:54)
	at junit.textui.TestRunner.<init>(TestRunner.java:48)
	at junit.textui.TestRunner.<init>(TestRunner.java:41)
	at com.intellij.rt.junit.JUnitStarter.junitVersionChecks(JUnitStarter.java:212)
	at com.intellij.rt.junit.JUnitStarter.canWorkWithJUnitVersion(JUnitStarter.java:195)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:49)

Process finished with exit code -3
```

I googled around and found out that apparently the Android test runner / test base we use contains an older JUnit library version which conflicts with the JUnit 4+ version we are using locally. Indeed, when I comment out the following lines in `build.gradle` (for main), then local unit tests work again:

https://github.com/cgeo/cgeo/blob/4b4f1d4cf3e5b69c0da47400c5d8a56b77fac1d3/main/build.gradle#L235-L237

Unfortunately this leads to instrumented tests no longer working.

Before I fiddle around with gradle/CI things I don't understand too good and messing up other things I wanted to ask the community what can and should be done about this. Currently I am quite hindered doing development work.

Here a screenshot:
![image](https://user-images.githubusercontent.com/6909759/97103221-58cd4b80-16ab-11eb-9367-6b0f5cff2c8d.png)

**Comment by bekuno** [comment]
Deactivating `useLibrary 'android.test.runner'` is enough for local tests.
I will analyse this deeper in the next days.

**Comment by bekuno** [comment]
It is a AS 4.1 error, see https://issuetracker.google.com/issues/170328018.

**Comment by bekuno** [comment]
I have no problem with the 2 lines in my AS.
For some users it helped to uninstall/reinstall the SDK platform "R" package.
For me it is currently:
![grafik](https://user-images.githubusercontent.com/32555742/97541992-537f4200-19c6-11eb-8617-a71809fb20ca.png)

**Comment by eddiemuc** [comment]
> For some users it helped to uninstall/reinstall the SDK platform "R" package.


Thanks, I will try that

**Comment by moving-bits** [comment]
If I understand the current release notes correctly, this is fixed with today's update to AS 4.1.2:

https://androidstudio.googleblog.com/2021/01/android-studio-412-available.html
(see Issue [#170328018](https://issuetracker.google.com/issues/170328018): AS 4.1+ fail to run junit tests, compailing about junit version being too low)

**Comment by bekuno** [comment]
correct :-)

**Comment by moving-bits** [comment]
Then let's close here...

**Comment by eddiemuc** [comment]
Does not work for me with newest 4.1.2 version (just installed today).

Replacing `android.test.runner` with `androidx.test.runne`r is enought to make local unit tests runnable. However, instrumented tests won't even compile since base classes are missing

Diving a bit deeper into this I realized that our instrumented test cases are using stone-old, long-deprecated APIs , e.g. things like `android.test.ApplicationTestCase`. I think the issue lies rather here than in Android Studio 

I will reopen this issue. 
Can anyone confirm that running local unit tests run with newest 4.1.2 (and without changing gradle files)? Then I would be happy to hear what I am missing :-)

**Comment by moving-bits** [comment]
> Can anyone confirm that running local unit tests run with newest 4.1.2 (and without changing gradle files)? Then I would be happy to hear what I am missing :-)

I'm using AS 4.1.2. At least I was able to run the `model/Waypoint` tests yesterday against `release` branch. (Did not check the others.)

**Comment by eddiemuc** [comment]
It works now for me too. Strange. Maybe I forgot to restart before. Will close again.
