### ISSUE TITLE
Setting for bigger smileys on the map

### ISSUE THREAD

**Issue by cayacdev** [cgeo/cgeo#9274]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
I want a configuration in the settings (e.g. Appearance) named "Bigger smileys". When I activate this setting, the smileys on the map should replace the cache images (as in the official geocaching app). 

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
I'm happier or more satisfied when I look at the map of the official geocaching app because the smileys are more exposed to the user. 

Because I'm a java web developer I want to implement/contribute this feature on my own. Maybe some of you can give my some useful hints which classes or commits I can use as reference. Thank you :)

**Comment by Lineflyer** [comment]
Hi @cayacdev and thanks for your feature request and interest to contribute.

IMHO such a feature would be useful and was also requested in the past by some users.
I agree, that a setting for this would be a good choice as other users might like the current style (so I guess the current style should be the default). 

Not sure though, whether the setting should be placed in Appearance or map setting menus. 
As it would only be used on the map and not in lists its IMHO better suited in the Settings -Map.

I personally can not help so much when it comes to setting up the build environment, but there are people around who will be able to help you.

**Comment by moving-bits** [comment]
For creating the marker have a look at `src/cgeo/geocaching/utils/MapMarkerUtils.java:getCacheMarker()` and `createCacheMarker()`.

Settings logic is in `settings/Settings.java`, preference keys in `res/values/preference_keys.xml`, preferences in `res/xml/preferences.xml`.

**Comment by cayacdev** [comment]
Hi, thank you for the quick response. Yesterday I was able to set up the development environment successfully. With @moving-bits information I could change the image quickly and took a screenshot. 

<img src="https://user-images.githubusercontent.com/6408145/97170312-c486e580-178b-11eb-91a3-2c2b5746b569.png" width="200" />

I have some additional questions:
- @Lineflyer Do you have an idea in which submenu of the map settings the new configuration can be placed or it is better to introduce a new submenu? In my opinion the submenus "Map Content" can be used.
- I have found the documentation pages: https://cgeo.droescher.eu/de/mainmenu/settings. Do I have to mention the new setting there? 
- How can I test the icons on the map for log types that I don't have in my gc account (I don't have a dnf logged in the past)? Is there a possibility to mock some test data?
- I don't find any contribution guidelines or something like that only the coding conventions here: https://github.com/cgeo/cgeo/wiki/Coding-Conventions. My question is should I only add the needed code for the bigger smileys to the existing methods or is it okay to e.g. rename some methods, replace / refactor duplicate code to private methods? Or is it better only add the new code and don't risk merge conflicts on other feature branches?

Cheers, cayacdev ;)

**Comment by eddiemuc** [comment]
Thanks for the contribution, it looks really nice!

> * @Lineflyer Do you have an idea in which submenu of the map settings the new configuration can be placed or it is better to introduce a new submenu? In my opinion the submenus "Map Content" can be used.

I would also choose this submenu

> * I have found the documentation pages: https://cgeo.droescher.eu/de/mainmenu/settings. Do I have to mention the new setting there?

Yes, but since your feature will be available to public users only at next public c:geo release while changes to that page will be public instantly, it might be better to wait with this documentation.

> * How can I test the icons on the map for log types that I don't have in my gc account (I don't have a dnf logged in the past)? Is there a possibility to mock some test data?

Good questions. I usually mock myself some data via temporary code snippets or by writing directly in my local database to do this. Some time ago I created an own test-cache on gc.com for me which I never published (so i am the only one able to see it and log to it). Now I can use this cache for all kind of logs, except for "Found" log of course.

> * I don't find any contribution guidelines or something like that only the coding conventions here: https://github.com/cgeo/cgeo/wiki/Coding-Conventions. My question is should I only add the needed code for the bigger smileys to the existing methods or is it okay to e.g. rename some methods, replace / refactor duplicate code to private methods? Or is it better only add the new code and don't risk merge conflicts on other feature branches?

Regarding the process you may take a look here: https://github.com/cgeo/cgeo/wiki/Working-on-c%3Ageo-for-git-beginners (this is maybe more detailled than you need).
In general, don't hesitate to do some refactoring along the way if you see the chance (always leave code cleaner than you found it :-))
