### ISSUE TITLE
Super-size routing distance display (optional)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9282]
While being on a cache tour I frequently either set the next waypoint as routing target or open the popup for it. Both of it displays the distance to the selected waypoint.

When I'm using my bike, and the way gets a bit rougher, it's pretty hard to read the distance as the display gets shaken - so I probably need to stop, read the distance, and move on. "Proximity notification" or "talking compass" only help in some cases. (eg: You do not want to have your loudspeaker on in all cases and/or the surrounding may be too load for the text messages to be heard.)

So what I what like to see is a map overlay which displays the distance text ("120m") in super-size letters (like a quarter of the screen). This option should be switchable using the three dot menu in map mode, default to off.

**Comment by Lineflyer** [comment]
Couldn't this be better triggered by tapping the distance shown on upper right when the direction/navigation line is active?
It would somehow be more consistent then on the popup or using some menu.
