### ISSUE TITLE
Global filters does not work in "Live mode"

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9284]
**Describe the bug:**
All caches are shown when set the global filter "User defined cache"

**To Reproduce:**
1. Go to 'main screen'
2. Click on 'Filter'
3. Select 'User defined cache'
4. Open map

**Actual behavior/state after performing these steps:**
All caches are shown.

**Expected behavior/state after performing these steps:**
Only user defined caches are shown.

**Version of c:geo used:**
2020.10.10

**Is the problem reproducible:**
Yes

**Comment by Lineflyer** [comment]
works for me with 2020.10.24-NB

**Comment by MagpieFourtyTwo** [comment]
Confirmed with 2020.10.24-NB ;)

**Comment by Lineflyer** [comment]
Oh...my fault:
I was on 2020.10.23-NB and with that it was working.
Now I upgraded to 2020.10.25-NB and can confirm this problem.

So unless my first test was wrong this problem (its only on map) came in between those versions.

**Comment by bekuno** [comment]
@Lineflyer Please test the latest release. For me the error is already there.

**Comment by MagpieFourtyTwo** [comment]
As I am on 2020.10.24-NB for real, and there other types are shown, too, it is most probably related to changes between 2020.10.23-NB and 2020.10.24-NB ...

BTW: It's not only in map, but in ``Nearby``, too.
Only context where the global filter works properly for me is in the lists (e. g. in ``All caches``).

**Comment by eddiemuc** [comment]
Bug seems to be in released version 2020.10.10 as well, at least in my phone

**Comment by moving-bits** [comment]
Strange. Seems to work here with 2020.10.10

Start c:geo - set global filter to "UDC" - open map => only UDC are shown, although plenty others are available.

**Comment by bekuno** [comment]
I had this nearly all the time with User defined caches, but sometime also with other filters.
So the problem is not every time visible and therefore difficult to reproduce.

**Comment by Lineflyer** [comment]
> Strange. Seems to work here with 2020.10.10

For me it was also working with the nightly as posted above, now I can also see the problem.

**Comment by eddiemuc** [comment]
...what can I say? Today it works. Still with release 2020.10.10. will check again tomorrow

**Comment by Lineflyer** [comment]
oh....thats a bad sign in terms of testing. We do have something producing unreliable results.

**Comment by MagpieFourtyTwo** [comment]
Just checked UDC filter again - and was surprised to see the filter working perfectly fine ... then I checked "Live mode", which was disabled (although I don't know why), so I enabled Live - and woosh ... map cluttered with all sorts of caches, offline saved and non-saved ones. Then disabled Live again, and - plopp, there are UDCs only again ...

So the problem may be connected to Live mode?

**Comment by eddiemuc** [comment]
Created PR #9371
