### ISSUE TITLE
Preserve zoom level for leaving/entering map

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9288]
**Is your feature request related to a problem?**
This wish arose while testing the global filter.
Every time I went back to the map the map window was set to a very small window.

**Describe the solution you'd like**
When leaving the map then the current resolution/map window is saved and restored when opening the live map.
It is not necessary to store this in the database.

**Comment by rsudev** [comment]
Do I understand you correctly, that you refer to the viewport shown?
If the viewport is no longer preserved across openings of the live map, this is a bug...

**Comment by moving-bits** [comment]
Don't we have a minZoomLevel? Maybe this value needs to be decreased (or removed).

**Comment by Lineflyer** [comment]
@bekuno 
Is it this same as described as a regression in #9293 

This behavior however came in only as a regression in todays nightly.
Before that it was working as you sugggested.

**Comment by bekuno** [comment]
This is already in release 2020.10.10.

**Comment by bekuno** [comment]
And on all maps.
Eg. GSat reset to 200m if greater than 200m
OSM online/offline to 100m

**Comment by Lineflyer** [comment]
@bekuno You are right, how could I overlook such an issue.
That is a regression for sure, but no feature requests.

**Comment by eddiemuc** [comment]
I created PR #9298 for this. However, I am really unsure whether I tackled this correctly (more details in PR). 
Is it possible that this never ever worked on the new map? (mapsforge 0.14 / v4)?

**Comment by Lineflyer** [comment]
I checked older releases as I am still a bit puzzled not being stumbled upon this problem earlier:
- Open map
- Scroll to some random point and zoom out a bit
- Leave map
- Reenter map

| Version |  GMaps | OSM |
|--|--|--|
|2020.07.02| Fail | OK |
|2020.08.04 | Fail | OK |
|2020.10.04 | Fail | Fail |
|2020.10.10 | Fail | Fail |

Maybe it helps.

**Comment by moving-bits** [comment]
The change in behavior for OSM has been triggered by the zoom level fix probably, which removed the adding/substracting 3 from the GM zoom level for OSM, leading to a lower min zoom level for OSM.

As for the bug itself: I think I have seen this behavior the first time after merging the Google Maps v2 patches we may have a look at that PR, if something got introduced triggering this. I'll try to dig into the commit history...

**Comment by moving-bits** [comment]
> As for the bug itself: I think I have seen this behavior the first time after merging the Google Maps v2 patches we may have a look at that PR, if something got introduced triggering this. I'll try to dig into the commit history...

Ok, from a quick glance no offending lines jump into view... First merge was #5973 (on a separate branch at that time), if someone wants to look a bit more closely.

**Comment by eddiemuc** [comment]
Either #9293 or this issue should be marked as duplicate imho

**Comment by Lineflyer** [comment]
@eddiemuc 
Beside the behavior describedin #9332 this is fixed, isn't it?

**Comment by eddiemuc** [comment]
> @eddiemuc 
> Beside the behavior describedin #9332 this is fixed, isn't it?

Yes. Can be closed imho
