### ISSUE TITLE
Enable Navigation for "Go to" UDC

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9289]
After we introduced c:geo as receiver for navigation intents, people started using it for e.g. transferring locations of Adventure Lab caches.

Use case:
1. Open an adventure lab
2. Select Location 1 and invoke navigation, select c:geo
3. A Go to target is created in c:geo
4. Repeat steps 2.+3. for all locations of the adventure
5. You do now have all locations of the adventure you want to do as "Go To" target

Use case:
Users do now want to see these locations on a map and have been asking our support, why the quick navigation (compass rose in top bar) and also the whole Navigation sub menu is missing.
You can "only" invoke navigation for each waypoint individually (or open the live map to also see the Go to waypoints on it).

Solution:
I do see no reason to disable those functions for the "Go To" UDC.
Of course it might have undesired effects for this usecase (e.g. if still other waypoints are stored from the past), but users seem to prefer having the same structure everywhere (which IMHO makes a lot of sense).

**Comment by moving-bits** [comment]
The navigation targets are added as waypoints, and have navigation enabled as such.

The cache itself (the "Go To" UDC) has no coordinates, which automatically disables compass rose and navigation menu (as c:geo would not know in those cases where to navigate to).

**Comment by Lineflyer** [comment]
mmh...how could we enable showing all of the waypoints on a (cache) map without making a special case out of it?

BTW:
For me in the top bar menu I do see a speech bubble (talking) which is useless as well.

**Comment by moving-bits** [comment]
> Besides, the actions "refresh", "share cache", "extract waypoints" have no function and should be dissabled as well for "Go To".

Are you sure about the "share" menu entry? Can't find it here, and from the code in `CacheMenuHandler` the "share" entry should not be displayed for all UDC, including the "go to targets" UDC.

"refresh" and "extract waypoints" are now being suppressed for UDC with #9325 (already merged to `master`).

**Comment by fm-sys** [comment]
> Are you sure about the "share" menu entry? Can't find it here, and from the code in CacheMenuHandler the "share" entry should not be displayed for all UDC, including the "go to targets" UDC.

Oh, yes. You're right...

**Comment by eddiemuc** [comment]
Teammeeting 19.11.23: underlying problem is that "special" GoTo cache has no coordinates.  Workaround could be to give special GoTo cache some coordinates e.g. from first stored waypoint. Cpould happen on c:geo startup automatically.

Discussion should be started whether special GoTo functionality is still necessary in c:geo these days.

**Comment by moving-bits** [comment]
> Discussion should be started whether special GoTo functionality is still necessary in c:geo these days.

This would also implicitly "solve" #11999

+1 for removing "go to" functionality, since we have user-defined caches as a (even more flexible) replacement.

We should give a deprecation warning, though - maybe three months in advance?

No migration route required, IMHO - but we may ask for user-feedback regarding this (could be done together with deprecation notice).

**Comment by eddiemuc** [comment]
+1 for removing

**Comment by eddiemuc** [comment]
Teammeeting 11.2.24: put "migration information" into next release (put in releas notes and/or open info box when "goto" waypoint is created). Then remove feature in release after next release

**Comment by moving-bits** [comment]
I'll create a separate issue to collect the things that need to be done when removing the "go to" functionality.

Let's close this issue as "won't fix".
