### ISSUE TITLE
Change of map center between subsequent calls

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9294]
Taken from https://github.com/cgeo/cgeo/issues/9270#issuecomment-716890164 reported by @MagpieFourtyTwo as a possible regression after fixing that issue:

Sometimes the map center seems to be changed between calls ... but this one is not deterministic

**Comment by Lineflyer** [comment]
No traces of such problem.
@MagpieFourtyTwo 
Please kindly report whether you found any clue here.

**Comment by MagpieFourtyTwo** [comment]
To be honest: It did not happen anymore. So, currently I'm not able to reproduce it.
So, let's just close it. I'll have an eye on it and will open a new issue if it happens again.
And hopefully I can remember the scenario then ... ;)
