### ISSUE TITLE
Next bugfix release (incl. legacy)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9303]
Before thinking about the next feature release (different issue) we could/should do another bugfix release.

We do have a fix regarding TB pages and some smaller ones on `release`. Maybe something elese might come in related to #9300 (but hopefully not).

Anyway a release prior November, 1st 2020 would be wise at least for the legacy version as Google Play requirements will change after that date.

I will try to prepare this weekend to get a 2020.10.31.
Any changes which should be included shall be discussed here and added to `release` respectively `cgeo-legacy`

**Comment by Lineflyer** [comment]
Will go for a release tonight as tomorrow I have no time and the clock is ticking towards target28 end of life.

**Comment by Lineflyer** [comment]
- [x] Check/Insert correct version name as headline in ```changelog-release.xml``` 
_(Be aware, that Github release tags always take the newest tagged commits as latest release, independently of its branch. So if you e.g. have to tag a release for legacy and normal release, make sure to change the changelog of the normal release as last step. If you only want to release a legacy version, you seem to have no solution to keep the normal release as "latest release" on Github...to be solved)_
- [x] Build release on CI server
- [x] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
Release 2020.10.29 / 2020.10.29-legacy is under deployment!

**Comment by Lineflyer** [comment]
We are done!
Now back to #9226

**Comment by moving-bits** [comment]
Thanks @Lineflyer for preparing and rolling out the releases! 👍
