### ISSUE TITLE
GPX export of "Go to" UDC is empty

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9305]
2020.10.10 (reported on support mail, not yet verified):

- Create some waypoints in "Go to"
- Select Menu - Export - GPX

Result:
A GPX file ZZ0.gpx is created but empty.

Expected Result:
Although the cache itself has no coordinates the waypoints should be exported.

**Comment by geocachermgo** [comment]
Confirmed. GPX reads:
`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.0" creator="c:geo - http://www.cgeo.org/" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd http://www.gsak.net/xmlv1/6 http://www.gsak.net/xmlv1/6/gsak.xsd" xmlns="http://www.topografix.com/GPX/1/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1" xmlns:gsak="http://www.gsak.net/xmlv1/6" xmlns:cgeo="http://www.cgeo.org/wptext/1/0" />`

**Comment by geocachermgo** [comment]
But I do not know if you can create a valid waypoint wo coordinates.

**Comment by moving-bits** [comment]
According to https://www.topografix.com/GPX/1/1/#type_wptType each waypoint must have coordinates - that's probably why we have this code fragment currently in `GPXSerializer` (which is used on GPX export):

```
final Geopoint coords = cache.getCoords();
if (coords == null) {
    // Export would be invalid without coordinates.
    continue;
}
```

We could loop over the cache's waypoints (if any) and use the first coordinates we find.

(Or we could use 0/0 as coordinates, but that would have the negative impact of positioning the map around 0/0 coordinates when mapping this cache and its waypoints.)

**Comment by murggel** [comment]
With #8409 (#9141) waypoints with empty coords where exported with 0/0 and on import the coords are deleted, so no 0/0 coordinates after import.

I can check, if the issues is done also with that fix for the other issue ...

**Comment by Lineflyer** [comment]
Isn't there a way to export a plain waypoint gpx without the cache element (at least explicity for cases where a single cache is exported which has no coords like the ZZ0)?

**Comment by murggel** [comment]
I can check if we can use the same solution as for waypoints and store the information about empty coords in the cgeo extension.

**Comment by murggel** [comment]
Is there any possibility to check whether it's a UDC, except the ZZ-prefix?

**Comment by fm-sys** [comment]
IIRC there is a function for every connector `canHandle(String geocode)` or something like that...

**Comment by moving-bits** [comment]
You can use `InternalConnector.getInstance().canHandle(cache.getGeocode())`

**Comment by eddiemuc** [comment]
There's still code in GPX parsing checking the special case of UDCs (starting with ZZ) without coordinates (lat=lon=0.0). Can this exception be removed for GPXparsing (-> dropping everything that has no coordinate immediately)?

**Comment by moving-bits** [comment]
Regarding the last part
> dropping everything that has no coordinate immediately

The discussion above points to #9141, which explicitly sets "0" as coordinates, if they are not yet set in the listing. (This can happen for some caches on geocaching.com, if waypoints are defined in the listing, but are not assigned any coords or having the coords hidden.) To be able to fully restore such cache exports via GPX import, we must not drop them.
