### ISSUE TITLE
Greetings from a nightly user :-)

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9312]
![IMG_20201029_223339](https://user-images.githubusercontent.com/43813636/97634936-d93ad600-1a36-11eb-9e31-8c975a113d63.jpg)

**Comment by Lineflyer** [comment]
That was me...the messaging system responded strange, so I did some testing :)

**Comment by Lineflyer** [comment]
BTW: Would this nightly user (= @geocachermgo ) please contact me on support@cgeo.org for something to discuss :)

**Comment by geocachermgo** [comment]
Done
