### ISSUE TITLE
"internal_goto_targets_title" on strings.xml

### ISSUE THREAD

**Issue by ray4423** [cgeo/cgeo#9313]
**Describe the bug:**
"internal_goto_targets_title" and "internal_goto_targets_description" on strings.xml are not applied

**To Reproduce:**
1. Go to 'Go to' in main panel
2. Swipe to 'Description'

**Actual behavior/state after performing these steps:**
It shows description in english even though other languages setting
i checked in japanese and deutsch

**Expected behavior/state after performing these steps:**
It shows description in japanese and so on

**Version of c:geo used:**
2020.10.29-NB-c4e254c

**Is the problem reproducible:**
Yes

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.
![Screenshot_20201030-081450208](https://user-images.githubusercontent.com/1713571/97643407-e84b7380-1a8a-11eb-9300-25850a7bc65b.png)

**Comment by fm-sys** [comment]
The strings will only be charged when you delete and recreate the cache. So the cache description is in that language you created it if the translation is available at this time.

**Comment by moving-bits** [comment]
Description provided by @fm-sys is correct, therefore closing the issue.
