### ISSUE TITLE
multiple substitutions specified in non-positional format

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9320]
Messages on CI:
~~~
/home/jenkins/slave/workspace/cgeo pull request/main/build/intermediates/incremental/mergeBasicDebugResources/merged.dir/values/values.xml:2856: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
/home/jenkins/slave/workspace/cgeo pull request/main/build/intermediates/incremental/mergeBasicDebugResources/merged.dir/values/values.xml:2859: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
~~~

This refers to
~~~
    <string name="map_source_osm_offline_combined_attribution_details">Combined (%d maps, %d attributions): click for details</string>
    <string name="map_source_osm_offline_combined_attribution_single">Combined (%d maps): %s</string>
~~~

It should use instead the format `%1d` and `%2d`.

**Comment by eddiemuc** [comment]
This will be changed anyway since majority does not want to include map count in text message.

Question: is it somehow possible to make such warnings non-mergeable via codacy or ci-buildjob failing?

**Comment by Lineflyer** [comment]
AFAIK we can set the repository, that it does not allow merges if CI checks fail. Don't know however how to configure Jenkins and/or Codacy to report a fail on such issues.

**Comment by bekuno** [comment]
It is configured in build.gradle (for the main subproject).
~~~
    lintOptions {
        // generally we accept lint errors when building
        abortOnError false
~~~
I'm unsure if we should disable this rule general.
We can it activate only for CI. So it will fail on local lint check (if you have enabled).
In our situation the warning is only interesting for the english strings, but not the warnings for the translations in other languages.
