### ISSUE TITLE
update/ no update

### ISSUE THREAD

**Issue by pictom1** [cgeo/cgeo#9348]
**Describe the bug:**
Message on app says update available. But going to Google Play, there is no option to update. 

![IMG_20201104_080823](https://user-images.githubusercontent.com/71992117/98117740-3344fc80-1e78-11eb-9d9d-827df7bdba72.jpg)

**Comment by Lineflyer** [comment]
Questions:
- What version are you currently using?
- Did you try to "restart" your Google Play app. They sometime cache some data, leading to outdated app version info?

**Comment by pictom1** [comment]
> Questions:
> 
>     * What version are you currently using?

Don't know. I can't seem to find the ABOUT section that normally shows up after an update. I thought it was as simple as clicking the logo on the app or swiping left or right on the home screen. But nothing is happening when I do that this morning. 


> 
>     * Did you try to "restart" your Google Play app. They sometime cache some data, leading to outdated app version info?

How? Restart the phone?

**Comment by Lineflyer** [comment]
> Don't know. I can't seem to find the ABOUT section that normally shows up after an update. I thought it was as simple as clicking the logo on the app or swiping left or right on the home screen. But nothing is happening when I do that this morning.

Click on upper right "Three-dot button" and Select "About c:geo"

> How? Restart the phone?

Probably, or delete the cache data of the Google Play app.

**Comment by pictom1** [comment]
Thank you. 

2020.10.29

Cleared play store app, same results. Could it have something to do with me being a beta tester?

**Comment by Lineflyer** [comment]
There should indeed be a new version 2020.11.03.
Google Play reports it as fully available to users. No idea, why it does not show up for you, but pretty sure it is a Google Play issue.

**Comment by pictom1** [comment]
Okay, thank you

**Comment by Lineflyer** [comment]
Please kindly report back if and when Google Play offers you to update.
Maybe indeed a device restart could help (I have no idea how Google Play handled pushing of updates internally).

**Comment by pictom1** [comment]
I rebooted my phone before my last response. I connected to public wifi (even though I have service) and just tried again and it worked. I'm updated  now. 

Thank You!
