### ISSUE TITLE
Incorporate Jetpack AndroidX Activity lib v1.2.0 (once available) for usage of Activity Result API

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9349]
This is a request to include Jetpack AndroidX Activity library version 1.2.0 once it is available in a stable version (as of 4.11.2020 current version is 1.2.0-beta01)
Details: https://developer.android.com/jetpack/androidx/releases/activity 

The reason for this is my intention to use the new Activity Result API which can replace some dirty workarounds around the Activity-bound-drien approach (`startActivityWithResult `/ `onActivityResult`). Currently those are necessary to start intents-with-result from helper classes such as `ImageActivityHelper`. 
(New API is described e.g. at https://developer.android.com/training/basics/intents/result or https://proandroiddev.com/is-onactivityresult-deprecated-in-activity-results-api-lets-deep-dive-into-it-302d5cf6edd)

**Comment by bekuno** [comment]
I did not see any restrictions for older API.
And also no security ore other reasons not to use this library.

**Comment by fm-sys** [comment]
@eddiemuc Jetpack AndroidX Activity library v1.2.0 was released just some days ago. I guess this would be something we should implement rather soon, as it would clean up some SAF code parts...

**Comment by eddiemuc** [comment]
@fm-sys 
Although I discivered this library while working on SAF, this is by far not an SAF specific issues. It could clean up all places in c:geo where we manually forward onActivityResults to helper classes. At least the following Helper classes are using this pattern and their usage could be cleaned up  (only one of them is for SAF):
* `ContentStorageActivityHelper`
* `ImageActivityHelper`
* `MapDownloaderUtils`
* `IndividualRouteUtils`
* `TrackUtils`

All of those, although not being an Activity themself, have some sort of `onActivityResult` method which must be manually called inside the `onActivityResult `method of the using Activity.

**Comment by eddiemuc** [comment]
No longer necessary, Result API is already part of currently used SDK/libraries

**Comment by bekuno** [comment]
We use `startActivityForResult` in out code (eg. in `cgeo.geocaching.CacheListActivity#startListSelection`).
This is deprecated:
`This method has been deprecated in favor of using the Activity Result API which brings increased type safety via an ActivityResultContract and the prebuilt contracts for common intents available in androidx.activity.result.contract.ActivityResultContracts, provides hooks for testing, and allow receiving results in separate, testable classes independent from your activity. Use registerForActivityResult(ActivityResultContract, ActivityResultCallback) passing in a StartActivityForResult object for the ActivityResultContract.`
