### ISSUE TITLE
Light theme text problem in cache details

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9353]
Reported via support mail:

**Detailed steps causing the problem:**
- use c:geo light theme
- Open cache details of a cache having a colored text (reported example: GC8ZV6F)
- Scroll in the listing to „Von der 1.Bonusinfo peilt ihr die Hälfte der 2.Bonusinfo Meter in 3. Bonusinfo Grad“

**Actual behavior after performing these steps:**

Some words have a black background and are not readable.

**Expected behavior after performing these steps:**

Text is always readable independently from color.

**Version of c:geo used:**

2020.11.03

**System information:**

Huawei p smart

**Comment by bekuno** [comment]
html source:
~~~
<strong>
  <big>
    <font color="black">
      Von der 
      <font color="green">1.Bonusinfo</font> 
      peilt ihr 
      <font color="red">die Hälfte</font> 
      der 
      <font color="green">2.Bonusinfo</font> 
      Meter in 
      <font color="green">3.Bonusinfo</font> 
      Grad
    </font>
  </big>
  <font color="black"><br><br></font>
</strong>
~~~

**Comment by geocachermgo** [comment]
If there is a cache that uses a very broad color range it's difficult to chose a good backgroud color.

**Comment by alan666notb** [comment]
I raised this issue a while ago in #7306, but it seems to have fallen by the wayside.
In the UK this affects nearly all of the very popular 'Church micro' series cache pages.

**Comment by alan666notb** [comment]
GC81R5R is another example where the effect makes a mess of a puzzle cache.

**Comment by bekuno** [comment]
Lets close as duplicate of #7306.

**Comment by fm-sys** [comment]
> Lets close as duplicate of #7306.

I closed it now. Or is there a reason, why this issue was still open?
