### ISSUE TITLE
supress Nightly with "no changes"

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9361]
Todays Nightly has "no changes". Why is the build done nevertheless?

**Comment by rsudev** [comment]
Why not? I don't see any harm in it.

**Comment by geocachermgo** [comment]
It needs ( little) energy, tester need to install it (or check the changes).
That only a small disadvantage, but if there is a easy way to change the configuration and there is no advantage, it's muda (無駄)

**Comment by Lineflyer** [comment]
I have no idea, whether this can be configured on our CI system. I guess so by comparing the commit ID or evaluating the last change timestamp.

But at this moment we have a lack of people with knowledge of the CI. 
So lets keep it open although I do not really care as most of the developers will know when they need to install a nightly.

**Comment by geocachermgo** [comment]
https://stackoverflow.com/questions/63014786/how-to-schedule-a-github-actions-nightly-build-but-run-it-only-when-there-where

**Comment by bekuno** [comment]
Interesting. Maybe a way to go:
- get the https://api.github.com/repos/cgeo/cgeo/commits json data
- read the latest commit: 0.commit.committer.date
- stop if this date is greater 24h (maybe compare with latest nightly build)

**Comment by MagpieFourtyTwo** [comment]
I can understand the OP's intention, but in fact do not see a real pay out of the effort needed to implement such a "feature".

Esp. as not every commit is a "real change", so you may want to verify the type of changes anyway, to see if there's "interesting" or even important stuff to check out, or has to be tested thoroughly, thus e. g. needing an additional backup. So it would in fact save just one single click in the morning on a bookmark of the [commits page](https://github.com/cgeo/cgeo/commits/master). And even this single click can be saved after nights without changes only, thus effectively let's say one or two clicks per week ... as days (resp. nights ;) ) without changes are (most luckily) very rare in this project,  :)

TMALSS: Although the idea sounds good, but while looking at the numbers, I would just drop it. Just my 0,02$  ;)

**Comment by Lineflyer** [comment]
Lets keep it as it is: In all projects I know a nightly is just a daily snapshot of the development. Furthermore also other things (not necessarily covered by commit IDs) might change from time to time (e.g. build config).

Developers interested to see, whether nightly installation pays out, can take a look into the build history here:
https://ci.cgeo.org/view/Release_Nightly/job/cgeo%20nightly/
