### ISSUE TITLE
Text selection action bar theme broken

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9365]
With system wide dark mode activated the action bar for text selection appears in the wrong background color.

**Steps to reproduce:**
- activate system dark mode (AFAIK only available on android 10+)
- c:geo in dark theme
- go to cache details page
- long click geocode/coordinates/name

![Screenshot_20201111_144955](https://user-images.githubusercontent.com/64581222/98820105-08394a80-242e-11eb-95e9-5990e51fe140.jpg)

Without activated system wide dark mode it looks normal. But I can confirm, that this was working with previous versions even with activated dark mode. Oh, and I haven't installed the newest nightly yet, so it's _not_ related to #9359

![Screenshot_20201111_144945](https://user-images.githubusercontent.com/64581222/98820103-07a0b400-242e-11eb-9483-3f9bcfc6e733.jpg)

**Comment by MagpieFourtyTwo** [comment]
Hmm. Either I have not yet understood your problem, or it simply works for me ...
Have usually activated system wide dark mode, too, plus using c:geo with ``[_] Light Skin`` set, but everything is fine.
Even checked out the possible combinations, but all of them simply work.
Maybe a matter of an (additionally) applied system design ...?

**Comment by fm-sys** [comment]
Not happening anymore, strange! As it's not reproducible for me lets close it - although I have no idea what was wrong with my phone...
