### ISSUE TITLE
Ukrainian/Chinese Simplified translation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9370]
We have got a request from a polish cultural society, who are planning to provide some geocaching experience for an ukrainian speaking minority in Poland. They offered the willingness to contribute a ukrainian translation in c:geo.

I will enable Ukrainian on Crowdin and align the needed activity over there.

This issue is just for information and as a reminder to include Ukrainian into the release, once a major percentage is translated.

**Comment by Lineflyer** [comment]
Ukrainian proofreader has been set up on Crowdin.
The plan is, that this user will perform the translation over the next days/weeks. I informed, that the nightly can be used to check progress and quality / matching of the translations.

@bekuno Wasn't it, that we need a setting somewhere to have Ukrainian contained in the compiled APK? Could you do this for `master` as time permits?

**Comment by bekuno** [comment]
@Lineflyer 
As you wrote initial:
`... as a reminder to include Ukrainian into the release, once a major percentage is translated`

Normally we activated languages if the translation is ~50% ready.
Currently nothing is translated in Ukrainian.

**Comment by Lineflyer** [comment]
> Normally we activated languages if the translation is ~50% ready.

Yes, therefore only enable on `master` for now.
I would like to allow them to in-app review their translations.

> Currently nothing is translated in Ukrainian.

They told me to start next week.
As they are kind of a "company" I expect they will make fast progress. Lets see.

**Comment by bekuno** [comment]
@Lineflyer 
Now the `Ukrainian` translation level is at 37%, needing approval.
Do we want to let them active for the next release?

By the way, `Chinese Simplified` has reached 55% translation (21% approval).

**Comment by Lineflyer** [comment]
Ukrainian translation reached 95% meanwhile. I approved those strings after contacting the requestor. While it might not be perfectly proofread they prefer a broader user base (=use it in release).
So Ukrainian can stay in. The next crowdin update should push 95% of strings.

I will probably do alike for Chinese Simplified.

@bekuno Is chinese simplified already active?

**Comment by moving-bits** [comment]
> Is chinese simplified already active?

You can see the languages activated in c:geo by either looking at `main/build-gradle` (search for line starting with `del locales`), or by opening the c:geo language selector in settings, as this gets its data from the language list activated for c:geo.

**Comment by bekuno** [comment]
> @bekuno Is chinese simplified already active?

Not yet.
I will prepare a PR.
