### ISSUE TITLE
Routed distance icon no longer shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9381]
Might be related to #9380 

Without using supersize I noticed, that the icon preceding the routed distance is replaced by ...

![grafik](https://user-images.githubusercontent.com/949669/99153482-0af3a400-26a9-11eb-8768-d2a6f8c05172.png)

**Comment by moving-bits** [comment]
Hm, strange. How did you manage to get this display?
Have not been able to reproduce so far, even not with font size set to maximum in system settings.

**Comment by Lineflyer** [comment]
mmh..AFAIR I do not user anything outside the standard system settings on my phone.

**Comment by moving-bits** [comment]
Ok, I'll give it a try by enlarging the two info fields from 10sp to 15sp. Let's see if this works...

**Comment by Lineflyer** [comment]
@moving-bits 
No difference for me. Still looks like as pasted above.

**Comment by moving-bits** [comment]
> No difference for me. Still looks like as pasted above.

See #9406, which also fixes (or better: avoids) this issue

**Comment by moving-bits** [comment]
Closed with #9406
