### ISSUE TITLE
Splash screen only shown once

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9386]
Not sure if it is intended behavior:

I was able to see the splash screen once, i.e. on the first start of the app after updating to a version with splash screen.

But even if I force close c:geo or restart the device. On consecutive starts its no longer shown.
Shouldn't we show it on each startup?

**Comment by moving-bits** [comment]
I can only guess: After the first start APK is precompiled and startup too fast to recognize the splash screen?
(At least in the emulator I was able to see the splash screen after each compile cycle.)
Manifest file names `SplashActivity` as only launcher activity, and `SplashActivity` does nothing more than forwarding to our `MainActivity`.

**Comment by Lineflyer** [comment]
Might be possible. 
Do we want to only show it to bypass waiting time in such cases or do we want to use it also as a bit of branding (e.g. show it anyway for e.g. one second if startup time is smaller)?

**Comment by moving-bits** [comment]
My understanding was to fill waiting time. We still have branding on the main screen (icon in top left).

**Comment by fm-sys** [comment]
> or do we want to use it also as a bit of branding (e.g. show it anyway for e.g. one second if startup time is smaller)?

IMHO it's a bad practice to introduce unnecessary waiting time. So I'm strongly against it. 

Btw, the splash screen is shown on each app start on my mobile so it's probably a device specific problem...

**Comment by Lineflyer** [comment]
Will test on another device.

**Comment by moving-bits** [comment]
> Maybe my device is just to fast.

:-)

Probably. In the emulator on my PC you can see it for 5-10 seconds after each install...

**Comment by Lineflyer** [comment]
I meanwhile have seen its shown also more than once, depending on the state and amount of running apps on my device.
So everything OK here...just my device not needed much startup time.
