### ISSUE TITLE
Offline map download shouldn't use mobile data

### ISSUE THREAD

**Issue by mjarmstr** [cgeo/cgeo#9388]
**Describe the bug:**
1. Offline map download shouldn't use mobile data
2. There is no UI to control offline map download

**To Reproduce:**
1. Attempt to start an offline map download on sub-par wifi
2. See no indication that a download is actually in progress and assume the attempt failed.  
3. Start a download again and still see no indication that a download is in progress
4. Wait several hours, then leave the house

**Actual behavior/state after performing these steps:**
1. Get a notification from you carrier that you have a spike in data usage
2. See that c:geo just used 1Gb of mobile data to download the map

**Expected behavior/state after performing these steps:**
1. Receive a notification that a download is in progress and provide a means to cancel the download
2. Pause download when switching to mobile data

**Version of c:geo used:**
2020.11.03

**Is the problem reproducible:**
Probably, but I don't want to try.

**Screenshots:**
None

**System information:**
```
--- System information ---
Device: moto x4 (payton_fi, motorola)
Android version: 9
Android build: PPWS29.69-39-6-13
c:geo version: 2020.11.03
Google Play services: enabled - 20.42.17 (100408-342117392)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: absent
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (24.8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (24.8 GB free) external non-removable
Geocache data: /storage/0000-0000/Android/data/cgeo.geocaching/files/GeocacheData (20.9 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (29.6 MB) on user storage
GPX import path: /storage/0000-0000/Download
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/Locus/mapsVector
Map render theme path: /sdcard/Locus/mapsVector/_themes/Elevate/Elevate.xml
Live map mode: false
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   opencaching.us: Not logged in (Not authorized)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---
```

**Comment by geocachermgo** [comment]
Someone could want to do/finish a download with mobil data, so I disaprove automatic pause.
I agree that there should be a warning and option to abort or pause.
On my phone I have a data limit enabled that switches off mobil data when exeeded and presents a warning with the possibilty to enable it again.

**Comment by moving-bits** [comment]
The download itself is done by system's download manager, not by c:geo itself. Notification is activated, so you should see a system notification by your system's download manager for it (probably with possibility for cancel).

After starting a download you get a small notification within c:geo (so called a "toast") stating that download has been triggered (meaning: the system's download manager has been requested to download a certain file). It can take some time then until the actual download starts, depending on your system (eg: current cpu usage etc.). AFAIK the download notification is only shown when the actual download starts.

Currently this notification is activated only during download and vanishes after completion. I can change this behavior so that the notification stays even after finishing a download and has to be dismissed manually.

**Comment by Lineflyer** [comment]
@moving-bits 
Does the system download manager have any parameter when requesting the download to limit it to Wifi / unmetered networks only?

**Comment by moving-bits** [comment]
Regarding mobile data usage: Yes, this is currently activated, even including roaming. Those are parameters are sent to the download manager on initiating the download request, and cannot be changed later (AFAIK). I would not disable downloading over a metered network, as this may be intentionally, but maybe we can add an extra confirmation dialog before downloading, adding an option to opt-in for metered networks.

**Comment by Lineflyer** [comment]
We can ask the user if he wants to limit it to Wifi (checkbox to activate download on mobile networks) before starting the download.
This dialog could also explain, that the download is handled by the system in background.

**Comment by moving-bits** [comment]
I've added a confirmation & information dialog, which will be displayed after having chosen a map to download and before the download manager gets triggered:

![image](https://user-images.githubusercontent.com/3754370/99190803-e828c480-2768-11eb-8261-b8f9c49b9710.png)

**Comment by moving-bits** [comment]
@Lineflyer 
Target to release or to master?

**Comment by mjarmstr** [comment]
> The download itself is done by system's download manager, not by c:geo itself. Notification is activated, so you should see a system notification by your system's download manager for it (probably with possibility for cancel).
> 
> After starting a download you get a small notification within c:geo (so called a "toast") stating that download has been triggered (meaning: the system's download manager has been requested to download a certain file). It can take some time then until the actual download starts, depending on your system (eg: current cpu usage etc.). AFAIK the download notification is only shown when the actual download starts.

In my case (I just confirmed this with a couple of smaller downloads) I do see the toast and the final dialog indicating that the map file was successfully received and stored, but I do not see a notification from the download manager that a download is in progress.

**Comment by geocachermgo** [comment]
I get a little moving arrow
![IMG_20201115_195022](https://user-images.githubusercontent.com/43813636/99193864-fa602e00-277b-11eb-8a2e-f9dc4644ee8f.jpg)
and if I swipe down I get
![Screenshot_2020-11-15-19-47-44-634_com miui home](https://user-images.githubusercontent.com/43813636/99193877-02b86900-277c-11eb-938c-01786df7b22e.jpg)

**Comment by moving-bits** [comment]
> In my case (I just confirmed this with a couple of smaller downloads) I do see the toast and the final dialog indicating that the map file was successfully received and stored, 

Both are coming from c:geo itself, the first one from directly after having triggered the download manager, the second one directly after the download manager has notified c:geo that the downloaded file is available.

> but I do not see a notification from the download manager that a download is in progress.

Strange...
Not sure if it's possible: Can one disable notifications from download manager?

Do you receive download notifications from the system's download manager when doing downloads from other apps?

**Comment by mjarmstr** [comment]
> Do you receive download notifications from the system's download manager when doing downloads from other apps?

I'm not sure.  I tried to download something in Firefox and Chrome.  I got notifications for both of them, but they had the name of the app in them.  So I assume they were generated by the app, not the system download manager.
