### ISSUE TITLE
Distance info constantly shown as "0,00m" on GMaps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9390]
- 2020.11.14-RC
- Samsung S4, Android 5.0.1

I don't know how I triggered this, but on Live Map when using GMaps there is a constant display of "0,00m" in the upper right.
No individual route, no target set.
Changing to OSM it disappears, back to GMaps it appears again.
Force stop and restart c:geo, still shown on GMaps

![Screenshot_2020-11-15-11-57-12](https://user-images.githubusercontent.com/949669/99183181-438f8e00-273a-11eb-965e-5f84020347f7.png)

![Screenshot_2020-11-15-11-57-23](https://user-images.githubusercontent.com/949669/99183187-47bbab80-273a-11eb-99be-a9f5d081121f.png)

**Comment by Lineflyer** [comment]
Addition:
Also reproducible on 2020.11.15-NB with my Samsung S20, Android 10. 
Seems to be a generic bug.

**Comment by fm-sys** [comment]
I can also reproduce this. Btw, is it a bug that the old deviation circles stay at the map?

![Screenshot_20201115_122523_copy_270x367](https://user-images.githubusercontent.com/64581222/99183740-573cf380-273e-11eb-8b65-a2c312706c13.jpg)
