### ISSUE TITLE
Set activity transition for splash activity

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#9392]
Currently (at least on my device) the splash activity exits with a sliding transition which looks weird. I'd prefer a simple fading transition or no transition at all.

**Comment by MagpieFourtyTwo** [comment]
Nokia 3210? ;)

Over here I can be glad to get to see it at all. Most of the times it vanishes *so* fast that one could have the impression @Lineflyer described in #9386.

But, to be honest, I'm not really sad about it, as the quicker c:geo is "ready to serve", the better.

**Comment by SammysHP** [comment]
I see it for about 0.5 seconds. So it appears and almost immediately slides down. Also I noticed that it is skipped if using old links in the launcher (which are associated with the main activity).

**Comment by moving-bits** [comment]
> Currently (at least on my device) the splash activity exits with a sliding transition which looks weird. I'd prefer a simple fading transition or no transition at all.

Strange. Haven't set any transition effect manually in the code, and do not see that effect in the emulator (or on my physical mobile). Maybe device-, vendor- or Android version-specific?

**Comment by Lineflyer** [comment]
@SammysHP 
Do recent nighlies still show this transition effect?
@moving-bits changed the transition while trying to debug #9563

**Comment by SammysHP** [comment]
Seems to be fixed, the transition is gone. It just appears and disappears (although fading would look nicer).

The logo looks fuzzy and low resolution, but that's a different issue.
