### ISSUE TITLE
Purge deleted UDC from DB immediately (to be able to "change" UDC coords)

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9397]
**Is your feature request related to a problem?**
Once a User Defined Cache is set. there seems to be no (or at least no GUI) possibility to adjust the coords.
Things are getting worse, when trying to bypass this limitation by simply deleting the "wrong" one and creating a new one (typically near by), as the deleted ones still remain on map for three days, thus cluttering it by producing a "UDC cloud".

My current workaround is, to set a waypoint where I want the cache to be, then export it to GPX, edit the GPX (copy the WP coords to the cache coords) and after deleting the "wrong" one, I just import the GPX - which has the desired effect (i. e. move the cache), but this is, nicely said, a little bit cumbersome. ;)

Perhaps there can be implemented a long click on the UDC's coords (as short click is for format change) to edit them?
Or even a dedicated menu entry ...?

**Comment by Lineflyer** [comment]
Well, AFAIR we discussed about that and decided not the change the default "cache construct" for the UDCs (which does not support manual edit of cache coordinates. So the possibility to create a waypoint within the UDC and mark "Set as cache coordinates" like you would do for other caches (e.g. solved mysteries, mulits).

But I also stumbled upon the three day caching, which seems not suitable especially for UDC:
While other cache coordinates remain valid and showable on live map also after deleting them locally it might make more sense to delete UDCs also from the 3-days cache immediately on delete.

**Comment by MagpieFourtyTwo** [comment]
> So the possibility to create a waypoint within the UDC and mark "Set as cache coordinates" like you would do for other caches (e.g. solved mysteries, mulits) does the trick.

Not really, as the original coords are still there, cluttering.
Unless you set ``[X] Hide original coords``, of course, but at least I "need" the original coords to verity Mysteries
and to see them in Multis, as I always set the coordinates of the next WP as cache coords (locally), to make routing etc. easier.

> it might make more sense to delete UDCs also from the 3-days cache immediately on delete.

This would at least be a way more easy workaround.
As it would help to keep the default cache construct, I would favor this solution.

**Comment by moving-bits** [comment]
> Well, AFAIR we discussed about that and decided not the change the default "cache construct" for the UDCs (which does not support manual edit of cache coordinates).

We already have one distinction for UDC: We can change its name. We've implemented it standard-conform by adding a new interface "cache names editable", which is currently implemented by the internal connector only.

This gives us several possibilities:
- Add a new interface "cache coordinates editable" and implement it for internal connector. (Regular cache coordinates dialog should be used.)
- Add an option (checkbox) for editing of user-defined waypoints "set as cache coordinates and delete this waypoint". (This could be used for other (user-defined) waypoints as well.)
- Add a menu option for waypoints "overwrite cache coordinates" (without implicitly creating an "original" waypoint)
- ... (maybe more)

**Comment by MagpieFourtyTwo** [comment]
> Add an option (checkbox) for editing of user-defined waypoints "set as cache coordinates and delete this waypoint". (This could be used for other (user-defined) waypoints as well.)

Sounds as if this would be the easiest to implement. Although it's not really self-explanatory that this is the way to go, while you are in the situation to change coords ... but perhaps it would be sufficient to have stumbled upon this once, to learn about it. ;)

So, to make this more obvious, I would not use a checkbox, but an add. choice for the ``Add waypoint`` dialogue, right after "[\_] Set as cache coordinates in c:geo", maybe s/th like "[\_] Move cache to these coordinates"- the third one is vacant for UDC WPs anyway ... ;)

**Comment by MagpieFourtyTwo** [comment]
And perhaps right this ``Add waypoint`` dialogue can be opened by long tap on the coords in details page ...?
Perhaps even with "[_] Move cache to these coordinates" set as default, when coming from there ...?

**Comment by moving-bits** [comment]
Maybe we don't even need a new menu entry:
Why not extend the "Set as cache coordinates in c:geo" option for UDC in a way that it does not create an "Original waypoint" at all?

Alternatively, if the above is voted down, add a third option, UDC only: "Set as cache coordinates in c:geo, without creating Original Waypoint"

**Comment by fm-sys** [comment]
What about just making Original waypoints deletable for UDC's?

**Comment by MagpieFourtyTwo** [comment]
> UDC only: "Set as cache coordinates in c:geo, without creating Original Waypoint"

This is in fact what I thought of with my "[_] Move cache to these coordinates". Thanks for clarifying. ;)

> What about just making Original waypoints deletable for UDC's?

Would be a solution, too, although it seems to be less obvious to me ... but the more I think about it, the more I like it.

Why not just make both? :)

**Comment by moving-bits** [comment]
Let's keep it simple for now... Implemented "allow deleting original waypoint for UDC" with #9423.

**Comment by MagpieFourtyTwo** [comment]
Great. Thx!

**Comment by MagpieFourtyTwo** [comment]
Nevertheless it would still be good, if UDCs would vanish as soon as they are deleted. ;)

**Comment by fm-sys** [comment]
> Nevertheless it would still be good, if UDCs would vanish as soon as they are deleted. ;)

Maybe not deleting them directly but after closing c:geo. Better be safe than sorry ;-)

**Comment by MagpieFourtyTwo** [comment]
Following the principle "Before deletion - make sure you have a backup copy"? ;)
If I may be allowed to cite @moving-bits: "Users still need to do what they are doing...", i. e.: deleted is deleted. My 0.02 $

Moreover it's not really more safe, but in fact problematic, as "closed" appears to be a not really well defined state.
There are various scenarios you may or may not define as "closed":
- after the user switched to home screen or another app (w/o really "closing" c:geo) ...?
- after c:geo has been removed from memory (closed via "recent apps" by the user) ...?
- after Android's task manager has closed c:geo ...?
- ...?

Thus a seemingly "re-open" of the app may or may not result in purged UDCs ... or not.
So, IMHO just the "immediate" scenario is really comprehensible.

Perhaps, if a "safety belt" will be considered necessary, there can e. g. be the "Undo" toast, like when deleting "normal" caches ...?

**Comment by moving-bits** [comment]
> Perhaps, if a "safety belt" will be considered necessary, there can e. g. be the "Undo" toast, like when deleting "normal" caches ...?

Hm, never found a real use for those undo toasts, as they disappear after a few seconds. Mostly realization that I shouldn't have deleted this or that comes too late for that undo toast...

I could imagine a separate "Undo view" instead (or additionally), which lists all caches marked as "to be deleted", and allows "undeleting" (= moving to standard list, for example).

**Comment by MagpieFourtyTwo** [comment]
> separate "Undo view"

Cool idea. Esp for caches with PNs not uploaded before deletion ... although ... re-storing them brings the PN back, too, IIRC (at least in the three days purge grace period).
So I just don't really see the need for such a view ...
But if it gets implemented anyway, how about adding a "purge immediately" button (per cache)? ;)
