### ISSUE TITLE
Filter for Difficulty and Terrain 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#94]
Have seen it on facbook from some other users and I would also appreciate this improvement:
Overwork the filter setting, so that users can also set a filter for Difficulty/Terrain value of caches additionally to the cache type.

e.g.: Only show caches with Difficulty <3 and/or Only show caches with Terrain <2.

**Comment by zstatman** [comment]
Unclear if this is answered but would like ability to do either multiple filters, e.g., D or T 2.5-3.0 as well as D or T 3.0-3.5 OR the < / > ability, as > 3.5 and then mixed with another filter like D < 2.5 and T > 3.5

Tks

**Comment by janykey** [comment]
Why not have it as ot is on geocaching.com?
Let the user define the range
D: min <= cache.difficulty <= max
T: min <= cache.terrain <= max

In UI one could use either number input fields or sliders

**Comment by zstatman** [comment]
YES, would be even better

**Comment by janykey** [comment]
Something like this 
https://material.io/design/components/sliders.html#

**Comment by zstatman** [comment]
OK w me

**Comment by pstorch** [comment]
@janykey @zstatman this issue is closed, but there is another one which discusses to improve the filter: #5877

**Comment by zstatman** [comment]
Thanks

> On 6/18/2018 10:55:20 AM, Peter Storch (notifications@github.com) wrote: 
> > @janykey @zstatman this issue is closed, but there is another one which
discusses to improve the filter: #5877
