### ISSUE TITLE
OSM Attribution Format

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9411]
Found with 2020.11.16-NB-49b06e4:
![IMG_20201120_094417](https://user-images.githubusercontent.com/43813636/99779201-026df400-2b15-11eb-9029-111bac49b129.jpg)
I saw, that the (text + link) was replaced by a small (c) and if you click there, no links are available. As I understood the usage conditions require a link?

**Comment by SammysHP** [comment]
Links are working fine for me. Have you tried it with an online map? Offline maps don't have links.

**Comment by geocachermgo** [comment]
Online maps have working links.I was talking about offline maps. Is there no link needed?

**Comment by Lineflyer** [comment]
That depends on the author of the offline maps IMHO.
I use openandromaps offline maps and those have a link:
![grafik](https://user-images.githubusercontent.com/949669/99784273-de61e100-2b1b-11eb-9082-edf0b5699dff.png)

**Comment by geocachermgo** [comment]
I have OSM and thought that it's required by them. In their example (https://www.openstreetmap.org/copyright) the complete text + link is at the bottom.
It was like this in some cgeo version but was changed later (I did'nt find the issue).

**Comment by eddiemuc** [comment]
We can only display information which is available in the map file. Where did you get the non-working example, let me check what is inside (currently, the comment field of the map info section is displayed

Also, have you tried using the same map in Locus?

**Comment by rsudev** [comment]
I think we need to clearly distinguish the cases where we just display user-provided (possibly OSM) data and where we distribute  data ourselves.
In the case of user-downloaded offline maps we have no obligation at all to display any attribution, that lies with the provider of the offline map towards the downloading user.
When we display online maps we have to follow the attribution requirements of the provider (which can be a superset of the OSM requirements)
If we provide functions to download offline maps (which AFAIK in the meantime do), we distribute and therefore need to follow the attribution requirements of the source.
That said does OSM strongly recommend a link, but not require it.

**Comment by geocachermgo** [comment]
> We can only display information which is available in the map file. Where did you get the non-working example, let me check what is inside (currently, the comment field of the map info section is displayed
> 
> Also, have you tried using the same map in Locus?

Locus is not showing an attribution on the map (offline and online) but a small (c). If you tap it you get the attribution (wo link)
Locus Offline:
![IMG_20201120_212837](https://user-images.githubusercontent.com/43813636/99846997-a4262d00-2b77-11eb-8cb4-dd0b46d33851.jpg)
Locus Online:
![IMG_20201120_212908](https://user-images.githubusercontent.com/43813636/99847029-b2744900-2b77-11eb-9846-1f80edbb09f8.jpg)
I got the map from the c:geo download directory:
![IMG_20201120_213334](https://user-images.githubusercontent.com/43813636/99847334-34fd0880-2b78-11eb-97d8-24ca6267a354.jpg)
If I tap the (c) I get the info but w/o link:
![IMG_20201120_213833](https://user-images.githubusercontent.com/43813636/99847739-d2f0d300-2b78-11eb-9a6f-539ddaa822d1.jpg)
So, if Locus is compliant we are too. I was just wandering because is was changed back from "info on map" to "(c) on map"

**Comment by Lineflyer** [comment]
Yes, we took Locus as template for our implementation after quite some discussion about how to visualize it.

**Comment by geocachermgo** [comment]
Ok, somehow I missed the discussion. (Was there an issue#?))
If there are no other concerns I'll close this issue.

**Comment by eddiemuc** [comment]
@geocachermgo past discussion was in issue #6150

**Comment by geocachermgo** [comment]
Thanks!
