### ISSUE TITLE
Crash when opening live map

### ISSUE THREAD

**Issue by Buntbart** [cgeo/cgeo#9430]
**Describe the bug:**
A clear and concise/summarized description of what the bug is.

cheo immediately crashes when opening the live map view.

**To Reproduce:**

1. Start cgeo
2. Open Live Map

**Actual behavior/state after performing these steps:**
Describe the actual issue/problem/behavior in detail.

After Update to 2020-11-22:
1. Message: Google Maps not available (that's right because no Google Services installed)
2. Message: Switch to OpenStreetMap (okay)
3. c:geo crashes

**Expected behavior/state after performing these steps:**
Describe what you expected to happen instead.

Show Live Map...

**Version of c:geo used:**
You will find the c:geo version in c:geo Menu -> About c:geo

2020-11-22

**Is the problem reproducible:**
Yes

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**

Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted

--- System information ---
Device: SM-G900F (klte, samsung)
Android version: 10
Android build: lineage_klte-userdebug 10 QQ3A.200805.001 26df6ccfc3
c:geo version: 2020.11.22
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found disabled archived
Hide waypoints: visited
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (5,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (5,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (5,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (102,3 MB) on system internal storage
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/2103-2227/cgeo/maps
Map render theme path: 
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / BASIC
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

- I deleted all offline maps and downloaded them again from within c:geo, but that didn't help.

- Then I copied this one map to /storage/emulated/0/cgeo/maps/ and set this as offline map folder. This also didn't work, c:geo stll crashes when opening live map.

**Comment by eddiemuc** [comment]
Hi @Buntbart, can you probably provide a log file for analysis? Please go into `Settings` -> `System` and choose option `Create Log file`.

**Comment by Buntbart** [comment]
[logcat_2020-11-22_21-07.txt](https://github.com/cgeo/cgeo/files/5580251/logcat_2020-11-22_21-07.txt)

**Comment by eddiemuc** [comment]
Hi @buntbart this is clearly a bug. My apologies.

Please try the following as a workarounds:
* Go to `Settings` -> `System`, scroll down to last entry "`Edit Properties`" and open it
* look for properties `mapzoom` and `cachezoom`. I suspect that one or both of them is -1.
* If this is the case please change the value to a positive not-too-big value, e.g. 1

I hope this fixes your problem for now. A real fix is necessary of course.

Can you give me feedback whether the above worked for you?

**Comment by Buntbart** [comment]
cachetoom was 16 and
mapzoom was -1.
I have now set mapzoom to 1 and after that the Live Map didn't crash anymore! 
Thank you! :-)

**Comment by eddiemuc** [comment]
PR #9433

**Comment by Lineflyer** [comment]
@eddiemuc 
For support and changelog:
What precondition triggers this bug?

**Comment by eddiemuc** [comment]
> @eddiemuc 
> For support and changelog:
> What precondition triggers this bug?

Unfortunately I don't know. It just happened.

**Comment by Buntbart** [comment]
I have other devices that all showed this bug:  
- Galaxy Nexus (maguro) with SlimROM 6 (Android 6.0.1)  
- Nexus 7 (flo) with LineageOS 14.1 (Android 7.1.2)  
No device has Google Play Services installed. All my devices have offline cards. On all of them the mapzoom was -1 after the update to version 2020-11-22. Maybe this helps to narrow it down.

**Comment by Lineflyer** [comment]
We have users on support mail who stumbled upon the fact, that after upgrade their map selection was reset to Google Maps although they used OSM before. I also remember I reported this here after a certain change in nightly builds.
It seems this "map reset" causes this bug if Google Maps are not available.

**Comment by bekuno** [comment]
I got also this reset.
Maybe if the map was configured as "combined"?

**Comment by eddiemuc** [comment]
This behaviour I am afraid I am responsible for since I changed offline map behaviour under the hood to use streaming instead of File access (preparation for switching to SAF). I think this also changed the format in which the last map file is stored and thus last setting can't be found any more.

If may well be that this leads to the crash when combined with a device not having google maps enabled. The PR should have fixed that though.
