### ISSUE TITLE
dialog theming bugs when using light theme

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9434]
As already expected, PR #9422 had introduced at least one new theming bug for backup restoration dialog. Haven't checked the rest of the dialogs yet... 

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/9422#issuecomment-732023741_

Edit: I tested the other ones and these are working fine!

**Comment by moving-bits** [comment]
Ah, working on the same part at the same time... :-)

I've prepared a fix for the theming bug in `BackupUtils.restore()`, reverting to pre-#9422 state. Now it's back to using dark theme colors even when light theme is activated, but at least it's readable. There's something pretty buggy with using light theme in settings activity.

**Comment by fm-sys** [comment]
When searching for ["new AlertDialog.Builder"](https://github.com/cgeo/cgeo/search?q=new+AlertDialog.Builder) inside this repository, there are still around 30 occurrences which shouldn't be there if we want to be consistent...

**Comment by moving-bits** [comment]
> When searching for ["new AlertDialog.Builder"](https://github.com/cgeo/cgeo/search?q=new+AlertDialog.Builder) inside this repository, there are still around 30 occurrences which shouldn't be there if we want to be consistent...

You're right, I'd started with only a few of them to test how things work out. Thanks for tackling the other as well!
