### ISSUE TITLE
Error during log /w picture

### ISSUE THREAD

**Issue by pklosko** [cgeo/cgeo#9436]
**Describe the bug:**
During Logging the Cache today ...

Find cache via "magnifier at main screen" by GC code [not important] -> log cache -> 
Set date(today), add some text, insert image VIA MENU (three dots on the upper right corner), edit traceables ... tap to LOG arrow = ERROR
"Sending log Failed" ... check @ web page of cache ... see pict1 [in CZECH lang, sorry]

How to Solve:
Delete added image
Add image via ICON below the log text .. hua,... it is an thumbnail, great .. tap to LOG arrow = OK

And @ webpage = 1 log and 4 notes AliKr LOG - see https://coord.info/GC7B9HX

I'm running DEVELOP version [2020.11.22]

**Comment by eddiemuc** [comment]
Hi @pklosko , sorry you experienced this error.


Would it be possible for you to provide a log file for analysis? Must be created right after the bug occured. Go to `Settings` -> `System` and select `create logfile` there, then either send it to support email (as offered) or attach it to this issue in GitHub.

**Comment by eddiemuc** [comment]
Also, does the same error occur when using other images as well? In case this is somehow related to a specific type of image, is it possible to obtain the original image for reprocessing?

On main difference between using the three dots and the icons to add images is that when using the three dots images are NOT reduced in size (except when choosing a scale option in the dialog). Is the image maybe very large, maybe combined with a nonstable internet connection? (note that c:geo makes first one request to store the log-text, then a second one to upload the image -> if the first step is successful but the second step fails it would result in the behaviour you described)

**Comment by pklosko** [comment]
Hi @eddiemuc ,

I dont have log file content, not right after bug occured. I'll try create it when occur.
Sys info [from log file ] is: 
--- System information ---
Device: SM-A520F (a5y17ltexx, samsung)
Android version: 8.0.0
Android build: R16NW.A520FXXSFCTG8
c:geo version: 2020.11.22
Google Play services: enabled - 20.42.17 (040408-342117392)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found disabled
Hide waypoints: -
HW acceleration: enabled (default state)
System language: cs_CZ
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (6,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (6,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (6,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (896,0 KB) on system internal storage
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/cgeo
Map render theme path:
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Přihlášení bylo úspěšné) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins: none
BRouter connection available: false
--- End of system information --- 

Original image is available here : https://1drv.ms/u/s!AqRtMywvKZeRkP1PWmFHIWFCIGtDWQ?e=ZMmeEK

Petr

**Comment by eddiemuc** [comment]
Ah, I assume this means you can't reproduce the problem?

**Comment by eddiemuc** [comment]
I tried uploading your image to another cache, no problem. Hard to analyse this w/o ability to reproduce or log

**Comment by pklosko** [comment]
I can't reproduce the problem now, because of no new cache to log :)
I'll try it next time

**Comment by eddiemuc** [comment]
@pklosko feel free to issue a test log to one of my caches e.g. GC7WKNK

**Comment by geocachermgo** [comment]
But be careful: you may get the souvenir for country and state even if you delete the log.

**Comment by pklosko** [comment]
OK, no problem. I already have some DE caches logged in.

I tried log  GC7WKNK about 15(???) minutes ago, no problem.  Probably it really was a problem with the network or at geocaching.com

**Comment by eddiemuc** [comment]
The log looked ok. I deleted it again.

I don't know what else to do here now. Is it ok to close issue?
