### ISSUE TITLE
Access of stacked caches

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9437]
**Describe the bug:**
Map shows deactivated cache but click shows active cache

**To Reproduce:**
1. Create list with GC4D0B (disabled)and GC4D09
2. Shown on map
3. zoom out. Dactivated cache is shown
4. Click on cache

**Actual behavior/state after performing these steps:**
active cache (which is under the deactive) is opened
**Expected behavior/state after performing these steps:**
Click should open the cache that is shown on map (top level)
**Version of c:geo used:**
2020.11.24-NB-531da3b

**Is the problem reproducible:**
Yes 

**Screenshots:**
![Screenshot_2020-11-24-12-56-09-398_cgeo geocaching](https://user-images.githubusercontent.com/43813636/100091936-98778680-2e55-11eb-97b8-fe0c4c81d0a8.jpg)
Zoom in
![Screenshot_2020-11-24-12-56-23-118_cgeo geocaching](https://user-images.githubusercontent.com/43813636/100092336-2b182580-2e56-11eb-937c-c735eb246ae1.jpg)

**Additional context:**
[Prio low]

**Comment by Lineflyer** [comment]
This should be covered in #7511 
In fact its a missing feature on Google Maps, which is present on OSM already.

**Comment by geocachermgo** [comment]
Yes, it working with OSM on- and offline.
So I close this as duplicate.
