### ISSUE TITLE
waypoint type edit field is missing

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9441]
**Describe the bug:**
Waypoint has no field to edit the waypoint type

**To Reproduce:**
1. Open GC50F0
2. Create waypoint via "extract waypoints" 
3. Open waypoint

**Expected behavior/state after performing these steps:**
Waypoint should have normal edit field for type

**Version of c:geo used:**
2020.11.24-NB-531da3b

**Screenshots:**
![Screenshot_2020-11-24-17-30-12-328_cgeo geocaching](https://user-images.githubusercontent.com/43813636/100144377-ff695f80-2e96-11eb-8833-960867d8968c.jpg)

**Comment by MagpieFourtyTwo** [comment]
Hmm - don't get the problem.
AFAIK the type of predefined WPs is not changeable in general ... or am I wrong?
Nevertheless, the type should be shown, IMHO.

Only thing which was kind of surprising for me is: I'm able to delete it ... was this always possible?
Or is it just an side effect of the recently invented possibility to delete the original coords of UDCs?

**Comment by geocachermgo** [comment]
The WP is not predefined but extracted from the cache description

**Comment by MagpieFourtyTwo** [comment]
Have a look at it in the browser - it's already there.
It just gets extended with a user note.

**Comment by geocachermgo** [comment]
Sorry for the inconvenience. You are right.

**Comment by MagpieFourtyTwo** [comment]
Nevertheless, the WP type should be shown anyway, IMHO.
So perhaps you may want to open a FR/BR for that ...?

**Comment by geocachermgo** [comment]
No, you are also not able to edit the Cache description in cgeo and a type was set by the owner.
![IMG_20201125_141704](https://user-images.githubusercontent.com/43813636/100232819-28d2cb80-2f29-11eb-8cf4-ffca9ae102a8.jpg)

**Comment by MagpieFourtyTwo** [comment]
Misunderstanding - I don't want(ed) to edit the WP type, just like to see it, for informational purposes.
In fact I consider it helpful to know, if the WP is just a via point (Trailhead) or a "real" Multi stage (like "Question to answer").
But, never mind, it's just a cosmetic issue, as in the list the type is shown anyway.

**Comment by eddiemuc** [comment]
I checked this and I also think this would be a valid feature request:
* On edit page of user-defined waypoints the current waypoint type is shown (and the user can change it too)
* On predefined waypoints the waypoint type is not shown (as can be seen in @geocachermgo s initial screenshot)

=> for predefined waypoints the type should also be shown in detail's page (although it should not be editable of course)
