### ISSUE TITLE
Cache lists: make icon for "TB count|Fav count|GCvote color" wider

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9466]
**Is your feature request related to a problem?**
Seems as if today's high quality caches with more than 10k favos need some more room ...  ;)

![Screenshot_20201128_014328](https://user-images.githubusercontent.com/9889015/100622951-c6f7d480-3321-11eb-8faa-d9b5318d6dbb.jpg)

**Comment by Lineflyer** [comment]
I remember the same issue when we had first caches with more than 999 favorite points.
How about not explicitly giving more room but just shorten it to e.g.  
10000 - 10999 = 10k
11000 - 11999 = 11k
and so on?

**Comment by MagpieFourtyTwo** [comment]
Fine for me - although I doubt there will ever be caches with 100.000 favos or even more.
Right now there is just a single one with ~12.000 - in the whole wide world. And it took 13 years to collect, thus 1000/anno.
Milkmaid's opinion is, it will take another 70 to 80 years until it may possibly break the limit of 100.000.
But, hey, who knows.  ;)
