### ISSUE TITLE
Map - Cache popup: Different icons for OSM and GM

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9467]
**Is your feature request related to a problem?**
If you open a cache popup while being in Live Map with OSM active, you will get three icons in it's header:
1. Compass rose => map view with current cache centered, route to cache calculated (as configured) and shown
2. Route to icon =>  same as 1. (at least seemingly?)
3. Hamburger menu (with entries "Map", "Navigate" ...")

When doing the same in Google Map or SatView, icon #2 is missing.
Menu entries are nevertheless the same, i. e. "Map" and "Navigate" are there
and clicking the compass rose gives the same result as in 1. and 2. described above.

**Describe the solution you'd like**
IMO there are two alternatives:
1. If there is a difference between 1. and 2 (although not obvious)., 2. should be added to GM & GSat, too, ... OR ...
2. If they are in fact identical, one of both can safely be omitted, and additionally the corresponding menu entry may be removed, too.

**Comment by Lineflyer** [comment]
Duplicate of #7969 ?!

**Comment by MagpieFourtyTwo** [comment]
Yep. seems so. And now I remember that you and me have talked about this, recently.  ;)
