### ISSUE TITLE
Add option to update downloaded OpenStreetMaps

### ISSUE THREAD

**Issue by MakiWolf** [cgeo/cgeo#9468]
It would be great when the app has an option to update downloaded OpenStreetMaps and tells when a newer version of the map is avilable.

**Comment by Lineflyer** [comment]
The first part could be doable by storing all downloaded URLs and add an option to retrigger these downloads on demand.

The second part is more difficult and can IMHO only be indirectly solved by storing timestamps of downloaded maps and inform the user. As we are not the map source we can/should only do this on demand (can then be combined to the first part to avoid unnecessary re-downloads of same map versions).

**Comment by moving-bits** [comment]
I would skip step 1, directly store URL and timestamp, and re-check on-demand (or maybe triggered automatically every x weeks), offering a download if a new version has been detected.
(Would be available to OSM files downloaded with the integrated map downloader only, as only then we know the source URL.)

**Comment by fm-sys** [comment]
To avoid too much traffic on their servers, it's probably better to only check for updates every time the map downloader is opened by the user. All available updates could be listed in a group on top of the map downloader, before all other mapfiles are listed (That would result in a UI a bit like Google Play, where you have the available updates section...)

**Comment by moving-bits** [comment]
Notes to myself:
- on downloading a new mapfile store full URL (string) and date (long) in existing `DBExtension` fields
- on retrieving the mapfile after download create new `DBExtension` type "InstalledMapFiles" for storing the local filename/SAF identifier together with URL and date
- in map downloader view add a button "check for updates", only available if following conditions are met:
  - at least one entry in "InstalledMapFiles"
  - check those local filenames/SAF ids, if at least one file still exists
- on pressing the button: check the still existing map files
  - use stored URL minus the last part (which is the original filename, eg: "germany.map")
  - call the page & parse the retrieved HTML
  - find the line with the last part and check the "last modified" stamp
  - put all finds into a list (with download size)
  - let the user decide which ones to download
- can be implemented in two steps
  - collect original URL, date and local filename/SAF ID in first step
  - add UI for checking at a later time
- should be implemented only after switch to SAF for map files

**Comment by moving-bits** [comment]
Closing here, as implementation has been done with #9604.
