### ISSUE TITLE
Add OpenTopoMap

### ISSUE THREAD

**Issue by MakiWolf** [cgeo/cgeo#9470]
It would be great when the app also supports OpenTopoMap
[https://wiki.openstreetmap.org/wiki/OpenTopoMap](https://wiki.openstreetmap.org/wiki/OpenTopoMap)

**Comment by SammysHP** [comment]
It would be great, but I'm not sure the server can handle the load. Do you want to ask derstefan for permission?

**Comment by rsudev** [comment]
Took a look, looks nice. And they are explicitly open for usage. If no one objects (@Lineflyer ?) I'll contact the project.

**Comment by Lineflyer** [comment]
Sure, contact them.
I do however have no numbers other than those on status.cgeo.org if they ask for potential load.
In peak we might have 10k consecutive users, but distributed over several map sources or not even using the map.

**Comment by Lineflyer** [comment]
@rsudev Any reply from "derstefan"?

**Comment by wolverine007** [comment]
Checked this map right now, in the online version it is stopping on a really inaccurate zoom level - so using it for getting a better feeling where the cache might be hidden is not given for my point of view.
I am using an offline version of the German "Freizeitkarte" this map is supporting at least 2 or 3 deeper zoom level than the one OpenTopo is stopping at.

**Comment by SammysHP** [comment]
Freizeitkarte is a vector map, OpenTopoMap a rasterized map. Also the style is optimized for that zoom level.

**Comment by rsudev** [comment]
@Lineflyer No response from "derstefan" received...

**Comment by wolverine007** [comment]
> Freizeitkarte is a vector map, OpenTopoMap a rasterized map. Also the style is optimized for that zoom level.

Okay and below the line, which benefits are we receiving with this fact?

**Comment by Lineflyer** [comment]
OpenTopoMap is suitable for other use cases than Freizeitkarte, but both are valid maps to be available in c:geo.

**Comment by Lineflyer** [comment]
As we recently received another request to add this map source I took the chance trying to contact the author again.

**Comment by ztNFny** [comment]
@moving-bits did you inform them?

"Ich würde gerne die OpenTopoMap als Karte in mein Webprojekt oder meiner Applikation ("App") einbinden. Was muss ich beachten?

Dies ist jederzeit gerne möglich, sofern unser Server z.B. durch Massendownloads nicht zu stark beansprucht wird. Außerdem kann keinerlei Ausfallsicherheit garantiert werden. Wir würden uns generell über eine kurze Information über die Verwendung freuen."

**Comment by moving-bits** [comment]
> @moving-bits did you inform them?

Sure, I've sent them an email informing them that we included OpenTopoMap in our upcoming beta, but did not wait for a reply (as they mentioned high incoming email traffic and their FAQ giving a permission to include the map without prior approval).
