### ISSUE TITLE
Geokrety logging doesn't work when logging from timezone ahead of CET

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#9496]
**To Reproduce:**
1. Open some cache (I'm in SU caches)
2. Save the log with 'write note type"
3. Use Geokrety to set all as visited
5. Send the log

Cgeo will show "logging GK", but this will be really really quick and no log will be added to GK.

I first though it doesn't work just for "write note" logs, but today it didn't for for "found" logs as well...

**Version of c:geo used:**
You will find the c:geo version in c:geo Menu -> About c:geo

**Is the problem reproducible:**
Yes / often

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

**Comment by okainov** [comment]
Just in case mention @kumy, if it doesn't work for everyone, can it be something had changed in GK website?

**Comment by kumy** [comment]
@okainov thanks for notify me about this issue. There is only recent commit I can remember which might affect logging: https://github.com/geokrety/geokrety-website/commit/5755530d9ebf91da55c8946c498275b37096a58f but I don;t how it may break this feature. I'll try to reproduce here.

**Comment by kumy** [comment]
Works fine for me https://geokrety.org/konkret.php?id=65535 http://coord.info/GL139WJKX

cgeo: 2020.11.25-NB-531da3b

**Comment by okainov** [comment]
The problem is I have no idea how to dig deeper there without debugging the phone :( I can make a screen-video, but the behavior exactly as described - c:geo shows my GKs, I can select log type, but then "posting GK logs.." takes like ~1 second for 10 GKs (when the log is really being posted, it's usually 1s per GK), says "c:geo has sccessfully posted the log". Lo gappears on GC website, but nothing in GK website...

**Comment by kumy** [comment]
Are you sure the GK connector is connected to your account?

**Comment by okainov** [comment]
Yes, I did re-check and re-log-in yesterday

**Comment by kumy** [comment]
Also works with 2020.12.06-NB-b5f906d
https://geokrety.org/konkret.php?id=65535

@okainov does logging directly a GK is working?
Use the search feature with a GKxxxx reference code, then log from there please.

**Comment by okainov** [comment]
Ok, have dumped logs from logcat. That's actually exactly what I was thinking, but then discarded as it was working at some point for me...

>12-06 18:13:40.555  6263 16660 W cgeo    : [AsyncTask #3] GeokretyConnector.postLogTrackable: The date is from the future (if you are an inventor of a time travelling machine, contact with us, please)


I'm in Russia with MSK timezone.

**Comment by Lineflyer** [comment]
I have an owned GK which I let visit all my cache finds. Logged three GC caches yesterday. All visits showing up normal on the GK website.

Could it be related to @okainov logging them for GC.su caches?

**Comment by okainov** [comment]
Question 1 - why was this working for me before? I'm in Russia since October and have a lot of logs since then, my last successful GK log was 1 week ago from Kalmykia.

Question 2 - even from UI I don't see this always, it's quite sporadic. But since last week I'm getting this always..

Question 3 - why c:geo reports it as success? I'd really expect the error to be thrown here... https://github.com/cgeo/cgeo/blob/b6a2eaa63041eed2ddfed6ffc9bc1f1fc98b65ed/main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java#L436

**Comment by kumy** [comment]
arfff :(

`The date is from the future (if you are an inventor of a time travelling machine, contact with us, please)`

I knows someone will complain about this one day or another… The current GK logging implementation thread all dates as local to `Europe/Paris`. I was really afraid when I discovered this some time ago!!!

The next GK website does it's best to handle timezones correctly. This has been implemented in the api, a new parameter was added for that. 

I still need to update docuemntation there https://new-theme.staging.geokrety.org/help/api#logging
> Important: All date time need to be provided as UTC and not as user local time. It's up to the poster to made the necessary conversion. As of today we still don't have any way to pass timezone, but it'll change in the future. 

But this is for the next website version.

Our best bet as of today, is requiring c:geo to make the time conversion before sending the log…

**Comment by okainov** [comment]
>I knows someone will complain about this one day or another… The current GK logging implementation thread all dates as local to Europe/Paris. I was really afraid when I discovered this some time ago!!!

Actually I have seen this since forever in website UI, but in the UI there was a simple workaround to change the hour, so I didn't really bother :)

**Comment by kumy** [comment]
@Lineflyer may someone implement time conversion before sending logs please? I'll check, if the time needs to be passed as UTC or server local time (`Europe/Paris`) - I suspect it's server local time…

**Comment by Lineflyer** [comment]
@kumy 
Timezone handling is cause of many bugs.
The best solution is to have all involved parties use UTC and require all connectors to deliver UTC in timestamps.
All other approaches (also delivering time zone information with the timestamp) shows somehow to be more error prone based on my experience. 
So using UTC for the GKAPI in future is IMHO the best way.

**Comment by kumy** [comment]
I only partially agree, timezones are made to be used ;) ISO-8601 help to use them. Bad experiences is not a reason to not use them… correctly :D

My opinion on that is:
**API exchanges:**
1. date time given without any TZ information, should be considered as `UTC`
2. date time given with TZ, must use the given TZ
3. server may return either:
 ** date time as UTC with TZ info as UTC
 ** date time as UTC without TZ info
 ** date time in any local time **with** TZ info

**Storage:**
4. date time should be stored consistently across a systems - preferably using `UTC` - that help with `grep`
5. the server should convert received date time according the the rules above (2. 3.) and store them in the "chosen reference" TZ (.4)

**Server must avoid managing date time in local format *without* TZ info**

Unfortunately, **that's not what current GK web/API is doing** - it use local time Europe/Paris and breaks 1. - it work for most of our users [Poland, Germany, France essentially] as we share the same TZ
https://c.tadst.com/gfx/600x337/tzmap-europe-2014.png?1

**The next GKAPI follows all those rules.**

As said before, legacy code is really brittle, we must avoid making risky changes and this one is especially risky. I don't plan to take weeks to fix that. I really prefer spending my time to finally release GK-NG.

---

Back to the issue, I'm not sure the current implementation in c:geo sends date times as UTC but in rather in local date time.

[Russia use 11 time zones](https://en.wikipedia.org/wiki/Time_in_Russia), from UTC+2 (MSK-1) to UTC+12 (MSK+9). Only users in MSK-1 can have success **in summer**. This problem has just arisen as we switched DST time on  October 31. We're now in UTC+1 (from UTC+2 before Oct. 31)

@okainov which is the TZ configured on your device?

**Comment by okainov** [comment]
>Russia use 11 time zones, from UTC+2 (MSK-1) to UTC+12 (MSK+9). Only users in MSK-1 can have success in summer. This problem has just arisen as we switched DST time on October 31. We're now in UTC+1 (from UTC+2 before Oct. 31)
@okainov which is the TZ configured on your device?

As I said, I'm in MSK timezone. As noted, my last successful log from c:geo was one week ago, late November. My phone is away now, I cannot tell you exactly, but some TZ which is MSK (either Minsk/Belarus, or Moscow, or something around)


@Lineflyer @kumy I agree there should be a proper solution, either handling everything in UTC or anything else, but at the moment as GK will not change I think the suggested workaround is the quickest working fix which will make some users happy :)

**Comment by Lineflyer** [comment]
I so also think, that we can use the workaround in our code for now and change it as soon as a new API provides such time zone handling.

**Comment by kumy** [comment]
:clap: thanks @okainov for #9506
