### ISSUE TITLE
[Nightly] Crash on change of routing strategy

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9500]
**Describe the bug:**
While route to a cache was active, I wanted to change routing strategy from "car" to "walk", using the new quick settings - immediate crash of cgeo was the result. In fact I currently can not change the routing strategy anymore.

**To Reproduce:**
1. Route to any cache
2. Tap new settings icon
3. Change routing from car to walk
4. Tap outside of quick settings popup

**Actual behavior/state after performing these steps:**
cgeo crashes and restarts

**Expected behavior/state after performing these steps:**
Change of routing strategy, recalculation and display of new route

**Version of c:geo used:**
2020.12.06-NB-b5f906d

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.1.0.150(C431E19R2P5)
c:geo version: 2020.12.06-NB-b5f906d
Google Play services: disabled - 20.45.16 (120400-344294571)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_DE
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (69,0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (69,0 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (69,0 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (315,5 MB) on system internal storage
Last backup: 6 Dec, 03:10
GPX import path: /storage/emulated/0/Download
GPX export path: /storage/emulated/0/Download
Offline maps path: /storage/0123-4567/Locus/mapsVector
Map render theme path: /storage/0123-4567/Locus/mapsVector/_themes/Elevate4/Elements.xml
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
BRouter connection available: true
--- End of system information ---
```

**Comment by MagpieFourtyTwo** [comment]
Had to downgrade to 2020.12.04-NB-912b158 (without the new icons for routing in the popup) to make routing strategy changes possible again.

**Comment by moving-bits** [comment]
Can you cross-check the logfile to see if this is caused by #9493 (circles) or a separate crash?

**Comment by MagpieFourtyTwo** [comment]
Seems so. Cannot check logfile that deep due to limited possibilities while being on the road, but at a first glance it looks as if the error messages are quite the same.

Please check the logfile attached. 

[logcat_2020-12-06_11-40.txt](https://github.com/cgeo/cgeo/files/5648629/logcat_2020-12-06_11-40.txt)

After that I first unset the "Show circles" option and without the circles shown, the crash does not happen anymore.

**Comment by MagpieFourtyTwo** [comment]
BTW: After changing the routing strategy in the popup, the toast "recalculating route in background" does always appear, even if there is no route active at all ... which is a bit irritating. Can this easily be limited to the scenarios where a route is active?

**Comment by moving-bits** [comment]
> Please check the logfile attached.

Thanks, seems to be the same error.
I think I have found the cause, and prepared a fix for it (#9501) - will be in the next nightly.

**Comment by moving-bits** [comment]
> BTW: After changing the routing strategy in the popup, the toast "recalculating route in background" does always appear, even if there is no route active at all ... which is a bit irritating. Can this easily be limited to the scenarios where a route is active?

At least that's the same behavior as today, just cross-checked with current release version.
Please open a separate issue if change is requested.

**Comment by MagpieFourtyTwo** [comment]
Yep, just wanted to know if it's possible at all, resp. w/o too much effort, cause it's in fact just cosmetic.

Will open an FR tonight.

**Comment by moving-bits** [comment]
> Yep, just wanted to know if it's possible at all, resp. w/o too much effort, cause it's in fact just cosmetic.

One would need to check mapstate (single cache map?), manually set target, GPX track/route, individual route, and maybe more, haven't checked yet.

**Comment by MagpieFourtyTwo** [comment]
Ok, sounds a bit too much and may most probably not be worth the effort, so let's wait if others complain. I can live with it happily anyway. ;)

**Comment by MagpieFourtyTwo** [comment]
Just tested with the debug-apk: No crash anymore.

Thx a lot!

**Comment by moving-bits** [comment]
Thanks for cross-checking! Haven't even merged it to master yet... :-)

**Comment by MagpieFourtyTwo** [comment]
Such an excellent support and fixing should at least be honored with immediate testing. ;)

**Comment by moving-bits** [comment]
\*blush\*

;-)

**Comment by MagpieFourtyTwo** [comment]
Cui honorem, honorem.
