### ISSUE TITLE
[Nightly] Crash when adding WP from clipboard

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9509]
**Describe the bug:**
Created a parking WP in a cache yesterday. Tried to copy it via clipboard to another cache today => crash.
Cross-checked afterwards with a reference point => same result.

**To Reproduce:**
1. Create a WP in any cache
2. Copy WP to clipboard
3. Go to another cache and insert WP from clipboard

**Actual behavior/state after performing these steps:**
c:geo crashes and re-starts in main screen.

**Expected behavior/state after performing these steps:**
Guess what ...  ;)

**Version of c:geo used:**
2020,12.06-NB-b5f906d

**Is the problem reproducible:**
Yes - at least most of the times. ;)
Before filing the BR, I first checked the scenario described above with latest Nightly - and most surprisingly it worked.
Ok, I thought, has been corrected. Fine. So I did the same with the WP, I *really* wanted to copy ... => crash.  :/
So it may possibly take some attempts to reproduce ... see [logcat.txt](https://github.com/cgeo/cgeo/files/5649729/logcat_2020-12-06_23-50.txt) for details.

**System information:**
```
--- System information ---
Device: VOG-L29 (VOG-L29EEA, HUAWEI)
Android version: 10
Android build: VOG-L29 10.1.0.150(C431E19R2P5)
c:geo version: 2020.12.06-NB-b5f906d
Google Play services: disabled - 20.45.16 (120400-344294571)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_DE
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (71,2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (71,1 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (71,1 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (315,6 MB) on system internal storage
Last backup: 5 Dec, 02:42
GPX import path: /storage/emulated/0/Download
GPX export path: /storage/emulated/0/Download
Offline maps path: /storage/0123-4567/Locus/mapsVector
Map render theme path: /storage/0123-4567/Locus/mapsVector/_themes/Elevate4/Elements.xml
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
Geocaching.com date format: dd MMM yy
Installed c:geo plugins: contacts
BRouter connection available: true
--- End of system information ---
```

**Comment by geocachermgo** [comment]
I followed the instructions but no crash for me.

**Comment by MagpieFourtyTwo** [comment]
Hmm. How many attempts have you made? On the very first it worked for me, too ...
Ah, perhaps this is related to offline stored or not stored, too ...? Had this the other day in another context ...
And indeed, adding a waypoint from clipboard seems to be *not* possible with caches, which have previously been stored and then deleted ... although I am not really sure if this is a different scenario than the one above, cause I was pretty sure that both caches had been saved offline ... but can't put my hands in the fire for this.

Nevertheless, if you would be so kind to cross-check at least this scenario:
1.  open [GC8NQXA 27 Wurzeln](https://coord.info/GC8NQXA) and save offline
2. open [GC8NQWY Der Blitzer](https://coord.info/GC8NQWY) and save offline
3. open [GC8NQXA 27 Wurzeln](https://coord.info/GC8NQXA) again, ...
   1. show in map
   2. via long tap on map add a parking WP at the end of the street which ends about 200 m north west of the cache
       Remark: Although there OSM shows a parking lot right there, I used the end of the white colored street.
   3. check coords. should be s/th about N49 06.373 E9 17.674
4. copy WP to clipboard
5. go back to c:geo's main page and open [GC8NQWY Der Blitzer](https://coord.info/GC8NQWY) via search (using the magnifying glass)
6. in WP page use button ``Add from clipboard`` ...

Up to here it worked for me, this time, too, ... even after third try ... although there happened the crash multiple times ... \*grrr\*
But as told before I was able to produce a crash anyway - so please proceed as follows:

7. open [GC8NQXA 27 Wurzeln](https://coord.info/GC8NQXA) and delete it
8. open [GC8NQWY Der Blitzer](https://coord.info/GC8NQWY) and copy the parking WP we previously created to Clipboard
9. go back to c:geo's main page and open [GC8NQXA 27 Wurzeln](https://coord.info/GC8NQXA) via search (using the magnifying glass)
10. in WP page use button ``Add from clipboard`` ...
11. at least now I have a crash every single time I try it ...

Admittedly, this is a pretty unusual scenario, nevertheless c:geo should not crash, IMO.
And I'm still not convinced that [Add from clipboard] really works in all circumstances, even with saved caches ...

**Comment by Lineflyer** [comment]
Can reproduce.
For me the simplified scenario seems to be:
- Copy waypoints of a saved cache to clipboard
- Open unsaved cache
- Use "Add from clipboard" for this unsaved cache.

Crash log looks identical to your posting above. The crash log in combination with this exception should probably show whats wrong:
```
12-06 23:50:04.473  2090  2687 E Handler : This is not main thread, and the caller should invoke Looper.prepare()  and Looper.loop()called byandroid.os.Handler.<init>:122 cgeo.geocaching.utils.SimpleHandler.<init>:16 cgeo.geocaching.CacheDetailActivity$ChangeNotificationHandler.<init>:2548 cgeo.geocaching.CacheDetailActivity.notifyDataSetChanged:886 cgeo.geocaching.CacheDetailActivity.ensureSaved:1859 cgeo.geocaching.CacheDetailActivity.access$4500:183 cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$3.doInBackground:1951 cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$3.doInBackground:1947 
``

**Comment by MagpieFourtyTwo** [comment]
Thanks for simplifying.  :)

Nevertheless, still unclear, why it crashed before, cause I'm pretty sure that both caches I was working with, were saved ...
But I'll keep an eye on it. :monocle_face: ;)

**Comment by geocachermgo** [comment]
I could also reproduce now .
Afais the WP is not really in the clipboard (with all the information) but only an identifier. E.g.
`c:geo:WAYPOINT:2118`

**Comment by Lineflyer** [comment]
This content looks intentional to me. 

Looking at the crash the problem seems rather to be that the waypoint creation fails as the target cache is not properly defined or cannot be found in some async task...just guessing, a developer has to dig into this:
```
--------- beginning of crash
12-06 23:47:26.965 11136  1745 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #8
12-06 23:47:26.965 11136  1745 E AndroidRuntime: Process: cgeo.geocaching, PID: 11136
12-06 23:47:26.965 11136  1745 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:929)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8913)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1557)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:24690)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:24690)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:24690)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:24690)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:24690)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:24690)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:24690)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.widget.TextView.checkForRelayout(TextView.java:9750)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.widget.TextView.setText(TextView.java:6314)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.widget.TextView.setText(TextView.java:6142)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.widget.TextView.setText(TextView.java:6094)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at androidx.appcompat.widget.Toolbar.setTitle(Toolbar.java:783)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at androidx.appcompat.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:262)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at androidx.appcompat.widget.ToolbarWidgetWrapper.setTitle(ToolbarWidgetWrapper.java:256)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at androidx.appcompat.app.WindowDecorActionBar.setTitle(WindowDecorActionBar.java:439)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at cgeo.geocaching.activity.ActivityMixin.setTitle(ActivityMixin.java:43)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at cgeo.geocaching.activity.AbstractActionBarActivity.setTitle(AbstractActionBarActivity.java:47)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at cgeo.geocaching.activity.AbstractActivity.setCacheTitleBar(AbstractActivity.java:270)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.notifyDataSetChanged(CacheDetailActivity.java:888)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.ensureSaved(CacheDetailActivity.java:1859)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.access$4500(CacheDetailActivity.java:183)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$3.doInBackground(CacheDetailActivity.java:1951)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$3.doInBackground(CacheDetailActivity.java:1947)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:389)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-06 23:47:26.965 11136  1745 E AndroidRuntime: 	... 4 more
--------- beginning of main
```

**Comment by MagpieFourtyTwo** [comment]
> Afais the WP is not really in the clipboard (with all the information) but only an identifier. E.g.
> `c:geo:WAYPOINT:2118`

Yep. surprised me, too, the very first time I tried to copy a WP to a Telegram message, in order to share it with a group I was caching with. ;)

But seen from the perspective of c:geo (and a dev) this makes perfect sense, as it is of course *way* easier, much more reliable and less error prone, moreover memory saving and way faster to implement the passing of a well-defined short pattern, instead of first having to construct a string of virtually any length, consisting of name, type, coordinates plus one or even two comments, which can contain all possible and impossible "dangerous" characters, each of which has to be quoted separately ... and all this just for the fun to unscramble the whole thing on the pasting side (i. e. the other cache listing) - with the same high effort again ... while all this stuff is in the database anyway. ;)

Nevertheless, it would of course be great, to have the *real* WP data in the clipboard, just in case you want to share it ... and this is, where the function ``Store WPs to PN`` drops into play ...  ;)
