### ISSUE TITLE
Add 'Original coordinates' to create-coordinates popup

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#9511]
When adding a waypoint to a cache, the popup box where you set the coordinates has options for My coordinates/Cache coordinates/Calculate coordinates/Clear coordinates.

I'd like 'Original coordinates' added to these options.
i.e. when the cache has corrected coordinates, the 'Cache coordinates' button would be replaced by 'Current cache coordinates' and 'Original cache coordinates'

This would be useful when solving a series of puzzles of the form "The cache is xxx metres away on a bearing of yyy degrees". If you 'solve' a cache and then realize you've made a mistake and correct it without thinking, the 'Cache coordinates' it uses are your 'Wrong' answer.

I know there's an 'Original coordinates' waypoint created with a 'reset coordinates' option, but I forgot what it was going to do and ended up wandering all over the shop!

**Comment by Lineflyer** [comment]
I do see this as a rather rare usecase.
For such cases you can anyway copy the coords from the original waypoint and use the clipboard function on creation of a new waypoint. 

Otherwise we would further expand this crowded dialog with one more rarely used button.. My opinion
