### ISSUE TITLE
Next beta / feature release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9518]
And once again we should find an appropriate point in time to cut off a new feature release by merging `master` to `release`.

New features (like quick settings on map) are already there. Not sure though if there are any left over regressions since last release.
Some candidates I see:

#9509 
#9463

**Comment by moving-bits** [comment]
There are more candidates I'd like to include:
- #9492 (setting target from popup for GMv2) - preferably after a review by @rsudev 
  - I would add solutions for #9519 and #9520 then as well
- #9517 (fix for Sailfish OS) - I'll try to do a review over the weekend
- maybe #9521 (make "auto-target for individual route" available in map quick settings)

**Comment by moving-bits** [comment]
How about branching for a new beta soon?
AFAICS there are no relevant regressions left on current master, and we have a lot of fixes (release/master) and some new features. Anything that needs to be prepared for the next beta before branching?

**Comment by Lineflyer** [comment]
What about this google proximity circle bug?

**Comment by moving-bits** [comment]
> What about this google proximity circle bug?

AFAIK this is already somewhat older.

**Comment by Lineflyer** [comment]
You are right, still it would be good to solve this as just now its reported by quite some people.

I will anyway prepare a beta next days.

**Comment by moving-bits** [comment]
I had a look into the accuracy circles issue a couple of days ago, but could not find anything obvious. From the code: Painting a new accuracy circle deletes the existing ones, so the reason must lie elsewhere - maybe the connection to the layer getting lost etc.
I wonder what change triggers the symptons more frequently recently.

**Comment by Lineflyer** [comment]
@moving-bits or others:
Might you take a look into PRs #9559 and #9568 whether they can be merged?

After that I would cut off a new beta release as discussed.

**Comment by Lineflyer** [comment]
For your attention:

`master` has been merged to `release` in preparation of a new beta release 2020.12.22-RC

This means (as you might know), that bugfixes need to target `release` (as always but also for all recently implemented features/changes).

**Comment by Lineflyer** [comment]
Beta release 2020.12.22-RC has been uploaded to Google Play for our beta testers. Should be available in some hours.

**Comment by Lineflyer** [comment]
I just tried to get an overview about open issues which should be solved before releasing from `release` branch (i.e. regressions or urgent bugfixes). I found:
- [ ] #9592

Anything else?

**Comment by moving-bits** [comment]
> Anything else?

Nothing from my side. According to Play Console statistics current beta seems to behave pretty well - way less crashes, and no relevant new ones, AFAICS.

**Comment by Lineflyer** [comment]
> Nothing from my side. According to Play Console statistics current beta seems to behave pretty well - way less crashes, and no relevant new ones, AFAICS.

Yes, indeed it looks very promising thanks to the efforts of @cgeo/team 

Let see if we can get #9592 solved somehow and then release as soon as possible.

**Comment by fm-sys** [comment]
A fix for #9592 was merged yesterday (see #9668) so AFAIK we're ready to roll out the new release...

**Comment by Lineflyer** [comment]
> A fix for #9592 was merged yesterday (see #9668) so AFAIK we're ready to roll out the new release...

I would rather like to push another updated RC first (and if its only for a few days).
This would allow to contact the beta users which were affected by #9592 to get further feedback.

What do you think?

**Comment by moving-bits** [comment]
Ok for me. We had quite a few additional fixes on `release` since our last RC.

**Comment by Lineflyer** [comment]
@fm-sys Do you plan any further changes regarding the "chrome webview" / "open in browser" as I have just een your draft PR.
Or shall we first gain new feedback on another RC and then decide what to do?

**Comment by fm-sys** [comment]
I just now found an option to reproduce the issue which makes tackling way more easy. I plan to finish the PR tomorrow, so it would make sense to wait one day more with releasing another RC

**Comment by fm-sys** [comment]
#9687 is ready - that was hopefully the last one dealing with the "open in browser action". After merging, we would be ready from my side for another RC...

**Comment by Lineflyer** [comment]
Seeing that #9687 has been merged, I will brew a new RC tonight give it a bit of smoke test and publish it on the beta channel as an update of the existing 2020.12.22-RC.
Afterwards I will filter the support tickets dealing with "open in browser" and ask those beta tester to try the new version.

**Comment by Lineflyer** [comment]
While smoke testing I have seen, that the fixes for #9540 are not contained. I have reopened that issue and IMHO we should include these fixes before releasing another RC.

**Comment by moving-bits** [comment]
I'll look into it and prepare a cherry-picked PR (if possible).

**Comment by moving-bits** [comment]
Have to correct myself:

Installation wizard is on `master` branch only, not contained on `release` at all.

**Comment by fm-sys** [comment]
> While smoke testing I have seen, that the fixes for #9540 are not contained. I have reopened that issue and IMHO we should include these fixes before releasing another RC.



> I'll look into it and prepare a cherry-picked PR (if possible).

The commits are f9ed2992a540110d1c604b0d62bcd0efc4594187, 1681666364aa17ce8928f0c7ab9d66270a63966b and edae36547adc2e995931eecac039e8f2ad71bc69



> Installation wizard is on `master` branch only, not contained on `release` at all.

The mentioned issue was about the map settings pop-up, not the installation wizard...

**Comment by moving-bits** [comment]
> > Installation wizard is on `master` branch only, not contained on `release` at all.
> 
> The mentioned issue was about the map settings pop-up, not the installation wizard...

aaarg, sorry - too many context switches currently :-(
I'll look into it.

**Comment by moving-bits** [comment]
done & merged to `release` and `master` - ready to go for the next RC...

**Comment by Lineflyer** [comment]
Perfect, thank you very much.
Smoke testing 2021.01.06-RC1 looks OK, not uploading to Google Play beta.

**Comment by moving-bits** [comment]
I checked Play Console statistics for our latest RC. It looks mostly fine, only one message catches me: #9738.

Proposal for continuing with RC and master:
1) Check if #9738 can be fixed easily, otherwise mitigate by adding try/catch in `MfMapView.zoomToViewport`
2) Release from that state
3) Branch current `master` to a new `release` branch (and probably start a new beta in a couple of days)
4) Merge SAF stuff to `master`

Should we calculate some time buffer between 2) and 3), if the need for some hotfix should arise?

What do you think?

**Comment by bekuno** [comment]
This is exactly what I would propose. Also with a time buffer between 2 and 3 for a possible bugfix release.

**Comment by eddiemuc** [comment]
Same here, proposal makes sense. Thanks for organizing!

**Comment by fm-sys** [comment]
> Should we calculate some time buffer between 2) and 3), if the need for some hotfix should arise?

I think the current beta behaves quite smooth but we could also create a new branch `old release`, just to be sure... 

Three branches would be useful anyway, if we want to use a more scrum based approach. That would mean, we have `master`, `beta` and `release` branches and can always start a new beta directly after rolling out the last release. However, I'm not sure whether we can do  this in the long term as we all do this just in our free time...

**Comment by Lineflyer** [comment]
> What do you think?

Sound good and same as I just commented on the SAF PR.

> Three branches would be useful anyway, if we want to use a more scrum based approach. That would mean, we have master, beta and release

Not necessarily. As we use git and master always contains all our work, we can forward and revert ˋreleaseˋ as we like.
So even if we decide (for whatever reason) to bugfix a release while a beta is still in progress, we could revert  ˋreleaseˋ back to the state of the current release and apply a bugfix on it. The previous state (=beta version)  is no longer relevant anyhow as Google Play has a common version management for beta and release. Meaning: The bugfix release would then replace the beta anyhow.

**Comment by moving-bits** [comment]
> 1. Check if #9738 can be fixed easily, otherwise mitigate by adding try/catch in `MfMapView.zoomToViewport`

Mitigation for #9738 is merged to `release`.
(Fix for parsing invalid coordinates should be targeted to `master`)

Ready to release?

**Comment by Lineflyer** [comment]
> Ready to release?

Could someone take a look into #9686

I somehow have the fear it might break the workflow for people manually uploading c:geo generated field note files to gc.com.
But maybe its an issue on my machine only, would be good if someone can crosscheck.

**Comment by moving-bits** [comment]
Maybe we need to distinguish "Export fieldnotes (for GSAK)" and "Export fieldnotes (for other services)", which would write in UTF 16 LE resp. UTF 16 BE formats?

**Comment by Lineflyer** [comment]
I just closed #9686 as it was not reproducible on another test.
So, if no one stops me, I am going to release based on current state of `release` tonight.

**Comment by Lineflyer** [comment]
Release 2021.01.10 has been uploaded to Google Play!
Thanks for your work on it.

Will close this issue once the release is available on Play.


- [x] Check/Insert correct version name as headline in ```changelog-release.xml``` 
- [x] Build release on CI server
- [x] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [x] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
The release is out.
Only thing missing is the update on Fdroid due to #9773. Still closing here.
