### ISSUE TITLE
Emoji's as cache icons  for UDC's 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9523]
I use UDC's for tagging all different types of places like my home, beautiful locations, supermarkets, etc.
For easy differentiation, it would be very useful if a custom emoji could be set as cache icon...

**Comment by Lineflyer** [comment]
IMHO we shouldn't transform cgeo into a generic POI manager.

However UDC could get a dedicate icon (e.g. cgeo) logo instead.

**Comment by wolverine007** [comment]
Maybe a small adjustment is worth to be integrated.

Could imagine that setting your home location 🏡 or just the parking slot 🅿, where you left your car in a unknown city, might help some of us to navigate back.

But definitely nothing with high importance...

**Comment by moving-bits** [comment]
> However UDC could get a dedicate icon (e.g. cgeo) logo instead.

That could look like this:

![image](https://user-images.githubusercontent.com/3754370/103455653-1d747c00-4cef-11eb-8217-a203f948fa89.png)

**Comment by moving-bits** [comment]
Regarding using user-defined symbols (as requested in some other issue):

On a quick glance, they would have to be provided by the user in specific resolutions. Currently we use the following settings for our type markers ("green box" symbol etc.):

- mdpi: 22x22 px, 300x300 dpi
- hdpi: 36x36 px, 300x300 dpi

**Comment by moving-bits** [comment]
> I use UDC's for tagging all different types of places like my home, beautiful locations, supermarkets, etc.
> For easy differentiation, it would be very useful if a custom emoji could be set as cache icon...

I've played around a bit with this today and was able to draw emojis as cache markers. Do you mean something like this?

![image](https://user-images.githubusercontent.com/3754370/103475893-87edf080-4db1-11eb-8c47-f868f106e4c0.png)

(I used squared markers for emoji caches, as some emojis are rather square then round.)

**Comment by fm-sys** [comment]
> Do you mean something like this?

Yep, exactly. 👍 I am already looking forward to it!   ;-)

**Comment by moving-bits** [comment]
@fm-sys 
That's what I have come up so far:

New menu entry "Select cache icon" in cache menu opens a emoji selection popup:
![image](https://user-images.githubusercontent.com/3754370/103483289-7d018300-4de6-11eb-81fb-e56853d8de67.png)

The button in the dialog title is the currently selected icon. Tapping this button will close the dialog without changing the assigned emoji. Tapping on a different icon will select that icon as new emoji, store the cache to the database and close the popup.

Cache details page will look like this then (see cache icon in title bar):
![image](https://user-images.githubusercontent.com/3754370/103483294-838ffa80-4de6-11eb-92ec-446ac0ec3ea7.png)

Cache icon on map will change accordingly. Any insets (if selected) will be shown as usual. "BigSmiley" option has precedence, as usual.
![image](https://user-images.githubusercontent.com/3754370/103483324-cb168680-4de6-11eb-98a7-d277a63fe0b5.png)

If you return to the "Select cache icon" popup you will notice two buttons in the title now:
![image](https://user-images.githubusercontent.com/3754370/103483334-dc5f9300-4de6-11eb-9b94-1a28e693fc5d.png)

The rightmost button is still the currently selected one, closing the dialog without change.
The button left to it is the "reset to default icon" button, which will reset to standard cache icon, store the cache and close the dialog.

(Internally there's some work still to be done, like selecting the right font size depending on screen density etc.)


---

Now the big question is: Which emojis shall we include? Currently it's just a hard-coded set of 50 consecutive entries starting with 0x1f334, for testing purposes.
We can include either a simple list of emojis, or we can group into categories, if needed (not implemented yet).

What I would need is one or more lists of comma-separated Unicode codepoint values, eg. `0x1f334, 0x1f335` etc.

**Comment by fm-sys** [comment]
I'm wondering, if we should introduce this for all or only user-defined caches? 
If we would introduce this for all caches, it would be a bit like a more prominent single cache "list marker" ;-)

I could create a list of the (in my opinion) most useful emojis, but on the other hand, we don't know which emoji's others would like to use. 

AFAIK there are also some "emoji chooser" library's we could use to make our lives easy and to still provide the known emoji chooser UI. Additionally a fully grown emoji chooser would also require a "Recently used" section as it is hard  to always scroll through thousands emoji's to find the right one...

**Comment by moving-bits** [comment]
> I'm wondering, if we should introduce this for all or only user-defined caches?
> If we would introduce this for all caches, it would be a bit like a more prominent single cache "list marker" ;-)

I've made this available for all caches intentionally, as this would not only cover the use case of this issue, but be a nice workaround for other requests to fully support user-defined cache icons. (I remember someone who wanted to mark a specialized series of caches regarding churches with a "cross" marker. And there are many other use cases out there as well, as we have seen with the list markers.)

> I could create a list of the (in my opinion) most useful emojis, but on the other hand, we don't know which emoji's others would like to use.

I had started collecting a list like WA and other chat services have, but those lists are too overcrowded, IMHO, so I stopped. IMHO we should make the list no longer than app. 50 icons (which is what is shown in the screenshot above), or we should introduce categories. But if so, they should be clearly distinguishable from each other, and not too many.

> AFAIK there are also some "emoji chooser" library's we could use to make our lives easy and to still provide the known emoji chooser UI. 

I'd done some research on emoji pickers before and found a few, but they all seem to be targeted to support text editing, not selecting a single item. And most of them had been too blown, pushing c:geo size by 300 kB and more - not appropriate IMHO for our use case. - For the picker I'm currently at less than 7 kB source, including dynamic map marker creation, and no additional image resources.

> Additionally a fully grown emoji chooser would also require a "Recently used" section as it is hard to always scroll through thousands emoji's to find the right one...

That shold be easy to add, as the view adapter could be reused for this as well, and the LRU list be stored in `DBExtension`.

**Comment by moving-bits** [comment]
Possible sources to collect such a list from:
- List: https://unicode.org/emoji/charts-12.0/full-emoji-list.html
  (intentionally not taken the newest release of that list for broader support)
- Frequency: https://home.unicode.org/emoji/emoji-frequency/

**Comment by moving-bits** [comment]
LRU list is working now, needed only a handful of lines:

![image](https://user-images.githubusercontent.com/3754370/103487818-5f451580-4e08-11eb-9ea8-5bccb4a6b9d9.png)

**Comment by moving-bits** [comment]
I'm stuck currently with calculating the right font size for the emoji.

I started with setting a fixed fontsize, which worked well on the given screen, but will not work with different screen densities etc. So I tried to calculate it:
- use a reference resource ("marker", the white circle around a cache icon), into which the symbol has to fit
  ```
  final Bitmap calc = BitmapFactory.decodeResource(res, resToFitIn); 
  return calc.getHeight();
  ```
- use a font size to test and compare the resulting text height with above measured height; increase/decrease font size, if needed
  ```
  final Rect bounds = new Rect();
  tPaint.setTextSize(fontSize);
  tPaint.getTextBounds(textToBeMeasured, 0, 1, bounds);
  return (int) (bounds.height();
  ```

But somehow this (and other variants found on SO) do not work reliably. 

@eddiemuc / @fm-sys: Do you have any idea how to set a max font size, so that the text (a single unicode character) still fits into a given drawable?

**Comment by eddiemuc** [comment]
Without looking deep into it:

If a fixed don't size works, is it possible to calculate pixels out of the wanted dp value like this?

`final int px = Math.round(40 * context.getResources().getDisplayMetrics().density);`

(Example taken from `ContextMenuDialog` Line 111, here the pixel value for 40dp is calculated)

**Comment by moving-bits** [comment]
I'll need to check if a fixed fontsize works across different screen resolutions and densities for the emoji use case.

I wanted to design that function a bit more generalized, as I have more ideas where such a feature could be useful. For that I need to be able to measure both a given drawable resource ("how much space is available") and the size of a given text in a certain font size ("how much space will this text use, and will it fit into the given drawable"), using the same size units (and this last part seems to be the problem).

**Comment by eddiemuc** [comment]
For that last part: I assume the space this text uses depends on the font used. Thus maybe the font metrics are of interest to you. To get them from a TextView:

`Paint.FontMetrics metrics = textView.getPaint().getFontMetrics()`

These metrics contain all sorts of height informations about the font used in the text view. Thus you can calculate the maximum space that font will use.

Font Metrics are explained very nicely here: https://proandroiddev.com/android-and-typography-101-5f06722dd611

**Comment by moving-bits** [comment]
Finally. Found a way to calculate max font size. Tested across three devices having completely different screen resolution and densities.
The trick was using a `StaticLayout` (which I need for putting the text onto the given drawable anyway) and check its height against the available space on the drawable resource.

BTW: Nice link, thanks. Gives a good introduction into some parts of typography.
