### ISSUE TITLE
Merge save logs with logs from pocket query

### ISSUE THREAD

**Issue by mjarmstr** [cgeo/cgeo#9524]
**Is your feature request related to a problem?**

When I update a cache via c:geo it downloads many more logs and I can get from my pocket query.  I like having this additional information when I'm out in the field.  However I have weekly pocket queries of a 1,000 caches in my area and unfortunately the pocket query only contains the last five logs.  When I update my offline list with my pocket query the previously saved logs are discarded leaving me with only five.

**Describe the solution you'd like**

I'd like to have c:geo retain the previous logs and merge that with the information from the pocket query.  I realize this could leave gaps in the log history but that could be indicated somehow.

It is possible that there might be other data that is currently discarded that could be retained as well, favorite points come to mind...

**Comment by MagpieFourtyTwo** [comment]
Favorite points are kept, for sure.

I also have some PQs, esp. for high fav caches, and after importing a "list refreshing PQ", favos are missing on completely new ones only. Which is in fact the criterion I filter for a) to find the caches I have to refresh in order to e. g. get some more logs or add. stuff and b) to see which caches have been added since last refresh.

**Comment by mjarmstr** [comment]
@MagpieFourtyTwo, you are correct that favorite points are retained.  I swear that in the past they weren't, but I just checked and they are.  So maybe it is just the logs I'd like retained.

**Comment by MagpieFourtyTwo** [comment]
Perjury? ;)
I work like this since I use PQs in c:geo, although I can not definitely say, how man years this is now ...
but it's not just since last week, for sure.  ;)

**Comment by moving-bits** [comment]
Currently all existing logs are deleted for each imported cache. We could change this behavior to keep them, but will have to do some merge then.

I've debugged a bit into storing PQ data, which in the end is the same as importing a GPX file, and the only identifiers transported and parsed during the import are GC code and author, so a possible way for merging could be
- not to delete all existing logs for this cache,
- but to delete all existing logs for this cache authored by the authors of the logs to be imported.

This would delete old logs from the same author, but that would be acceptable, IMHO.
Maybe we could restrain that rule to "same log type".

What do you think?
(Keep in mind that this rule would be applied for all connectors and all ways of storing logs.)

**Comment by MagpieFourtyTwo** [comment]
> Maybe we could restrain that rule to "same log type".

+1

> this rule would be applied for (...) all ways of storing logs

What do you have in mind ...? Don't see a problem with this yet.

**Comment by mjarmstr** [comment]
I think @moving-bits proposal of keeping unique author/log type pairs would work for me.

**Comment by Lineflyer** [comment]
Merging could be done by comparing date/author/log type to be on the safe side.  
@moving-bits Are you sue, there is no thing like a log-ID in those GPX? I remember something butare not so familiar with GPX structure.

**Comment by moving-bits** [comment]
> @moving-bits Are you sue, there is no thing like a log-ID in those GPX? I remember something butare not so familiar with GPX structure.

From a look into my own database an PQ files:
- There is a field called "id" in the PQ GPX files, but it's not used, not stored into the database.
- In the database we have a field `service_log_id`, but that seems to be filled rarely. (Maybe only on direct download of caches via c:geo, not when using PQ/GPX files - haven't checked the source here.)

Regarding the comparison:
I'll start with date/author/log_type. Just be aware, that the more specific I compare, the less intended changes I can discover, eg. if the user changes the logtype or the date of the log, we'll have duplicate logs. That's ok for me in this usecase, we just have to keep that in mind.

**Comment by eddiemuc** [comment]
> In the database we have a field `service_log_id`, but that seems to be filled rarely. (Maybe only on direct download of caches via c:geo, not when using PQ/GPX files

Indeed service_log_id is currently filled only on direct download, but it should be filled for all downloads done after last release (where it was introduced). This is is service-specific and implemented for gc.com, oc and some other service. I added this field to enable direct links to log entries on website (can't remember issue id).

I guess it could be filled for GPX imports as well if the contain the service-specifc log ids

**Comment by MagpieFourtyTwo** [comment]
[``service_log_id``]
> to enable direct links to log entries on website 

Hmm, could perhaps be an approach for #9553, too?
