### ISSUE TITLE
Filter stored before last 30 days doesn't work

### ISSUE THREAD

**Issue by mjarmstr** [cgeo/cgeo#9525]
**Describe the bug:**
When selecting _Filter_, _Stored_, _Before last 30_, no caches are filtered out.  The filter before the last 7 days works as expected.

**To Reproduce:**
1. Select an offline list with some old saved caches
2. Click on Filter Icon, then _Stored_, then _Before last 30 days_.

**Actual behavior/state after performing these steps:**
All caches are shown

**Expected behavior/state after performing these steps:**
Only caches saved more than 30 days ago are shown. 

**Version of c:geo used:**
2020.12.03

**Is the problem reproducible:**
Yes 

**System information:**
```
--- System information ---
Device: moto x4 (payton_fi, motorola)
Android version: 9
Android build: PPWS29.69-39-6-13
c:geo version: 2020.12.03
Google Play services: enabled - 20.45.16 (100408-344294571)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: absent
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (24.0 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (24.0 GB free) external non-removable
Geocache data: /storage/0000-0000/Android/data/cgeo.geocaching/files/GeocacheData (18.8 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (29.5 MB) on user storage
GPX import path: /storage/0000-0000/Download
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/Locus/mapsVector
Map render theme path: /sdcard/Locus/mapsVector/_themes/Elevate/Elevate.xml
Live map mode: false
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   opencaching.us: Not logged in (Not authorized)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---

```

**Comment by MagpieFourtyTwo** [comment]
Just tested - can confirm:  If a list is filtered by ``Stored`` => ``Before last thirty days`` *all* caches are shown,
no matter if they are younger or older than 30 days.

Nevertheless. I would change the subject to "Filter stored before last 30 days does *not* work"  ;)
And the "Expected behavior" is IMO "only *older* saved caches *should be* shown",
as *younger* are the caches stored *within* 30 days.

**Comment by mjarmstr** [comment]
> Just tested - can confirm: If a list is filtered by `Stored` => `Before last thirty days` _all_ caches are shown,
> no matter if they are younger or older than 30 days.
> 
> Nevertheless. I would change the subject to "Filter stored before last 30 days does _not_ work" ;)
> And the "Expected behavior" is IMO "only _older_ saved caches _should be_ shown",
> as _younger_ are the caches stored _within_ 30 days.

That's what I get for banging out the issue on my phone.  I edited my initial submission.  Thanks.

**Comment by bekuno** [comment]
There is a "Numeric overflow in expression" in StoredFilterFactory L142/166.
Lets check if this is the reason.
