### ISSUE TITLE
Github Question: Find pictures uploaded by myself

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9535]
Is there a possibilty to search in github the pictures that have been uploaded by someone esp. by myself?

**Comment by SammysHP** [comment]
Uploads no, issues yes. You can filter all issues you've participated in.

https://github.com/cgeo/cgeo/issues?q=is%3Aissue+commenter%3Ageocachermgo

**Comment by geocachermgo** [comment]
I suspected that it's Impossible, but thanks for the confirmation.

**Comment by eddiemuc** [comment]
The full set of possibilities:
https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests

**Comment by fm-sys** [comment]
Perhaps this would have been something for `Discussion`. I don't know how we want to use this new feature, but it could be something like an "interactive FAQ"...
