### ISSUE TITLE
[Nightly] Layout search window too small at first

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9545]
[minor]
**Describe the bug:**
After the first start of the new nightly that layout was inappropiate

**Actual behavior/state after performing these steps:**
There were less then 2 letters after GC visible in the search window. The list of the last search results was very narrow.

**Version of c:geo used:**
2020.12.16-NB-7e7fd92

**Is the problem reproducible:**
Yes/No (was first like on the screenshot but switched back to normal, during writing of this report)

**Screenshots:**
![Screenshot_2020-12-16-07-05-51-255_cgeo geocaching](https://user-images.githubusercontent.com/43813636/102311758-b83e2e00-3f6d-11eb-841d-780d22a7eb79.jpg)

**Comment by fm-sys** [comment]
IMHO we should hide all other action icons if search is active. I will try to provide a PR for it...

**Comment by geocachermgo** [comment]
How I the switching supposed to work, I always see the normal layout w/o the symbols ?

**Comment by moving-bits** [comment]
> How I the switching supposed to work, I always see the normal layout w/o the symbols ?

That depends on your screen resolution, font size etc.
If there's enough space, Android displays some of the menu entries as symbols in the so-called ActionBar.
