### ISSUE TITLE
Pics on "Images" page: Add link to corresponding log

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9553]
**Is your feature request related to a problem?**
On gc.com each pic has a link to the corresponding log, which is sometimes really helpful to be able to assess the context of this image. In c:geo the only possibility to find this log is "trial & error" by clicking the image links in the logs ... or ``Open in browser``, switch to gc.com's gallery, search the image in question, open it, click the ``View Log`` link and finally open this one ... which in fact is not just cumbersome, but additionally needs a sufficient data plan and - which is in fact the real problem over here in .de - good network coverage ...

**Describe the solution you'd like**
Would be great to have a link at each pic which points to the corresponding log.

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo New gallery provides at least author, date and state of log. Is this enough?

**Comment by MagpieFourtyTwo** [comment]
This at least makes it way easier to find the corresponding log, therefore I would say we can close here.
Thanks for the improvement - and for the reminder of this topic, too.  ;)
