### ISSUE TITLE
Crash when selecting map source (IllegalStateException)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9560]
Reported on support mail.

How to reproduce:
On an Android system without Google Play services (e.g. Lineage) start c:geo. Tap (three dots) -> Settings -> Map -> Select map source

Crash:
```
12-21 08:06:06.232  5149  5149 E AndroidRuntime: FATAL EXCEPTION: main
12-21 08:06:06.232  5149  5149 E AndroidRuntime: Process: cgeo.geocaching, PID: 5149
12-21 08:06:06.232  5149  5149 E AndroidRuntime: java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.preference.ListPreference.onPrepareDialogBuilder(ListPreference.java:258)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.preference.DialogPreference.showDialog(DialogPreference.java:331)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.preference.DialogPreference.onClick(DialogPreference.java:302)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1163)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:260)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4116)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-21 08:06:06.232  5149  5149 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

Sysinfo:
```
--- System information ---
Device: ONEPLUS A6013 (OnePlus6T, OnePlus)
Android version: 10
Android build: lineage_fajita-userdebug 10 QQ3A.200805.001 08f3bde217
c:geo version: 2020.12.21-NB-87e6f15
Google Play services: unavailable
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_US / user-defined language:
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (91.4 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (91.4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (91.4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (1.5 MB) on system internal storage
Last backup: never
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/Download
Map render theme path:
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: none
BRouter connection available: false
--- End of system information ---
```

**Comment by eddiemuc** [comment]
Ähm...

Short time ago I removed exactly this code from settings activity because I thought it to be a leftover from times where MapSource could not be selected on map view directly...

Two ways to solve this:
* Restore the code
* Remove possibility to select map source in settings because it can be done directly in map view

I would personally prefer second option. Does not make sense imho to offer this in settings. What is the communities opinion on this?

**Comment by rsudev** [comment]
I would prefer to still be able to select the map source where I configure the offline folders as well.

**Comment by eddiemuc** [comment]
Screenshot from Settings:

![Screenshot_20201221-154225.jpg](https://user-images.githubusercontent.com/6909759/102788720-60eff180-43a3-11eb-8869-2145888f65ad.jpg)


Screenshot from Map viewer Menu:

![Screenshot_20201221-154255.jpg](https://user-images.githubusercontent.com/6909759/102788748-69e0c300-43a3-11eb-9574-d0c19b07c08c.jpg)

**Comment by eddiemuc** [comment]
Well this is my fault, so I will provide a PR for revert soon (although I would personally prefer deleting MapSource selection from settings)

Just one thought: I compared map source selection in settings and map viewer, and I noticed that in Settings (unlike in Map Viewer) user does not get offered the Download option for offline map. So it seems that map source selection in Settings was considered a "second-class-citizen" even before my move. Also, it took surprisingly long until anyone notices that this no linger works (admittedly, this was only in nightlies and maybe not every bug is reported).

So, if Map Source Selection shall stay in Settings, maybe someone should also make it a first-class-citizen again?

**Comment by eddiemuc** [comment]
Provided PR #9561 which will restore original behaviour and thus fixes the issue

**Comment by moving-bits** [comment]
> Just one thought: I compared map source selection in settings and map viewer, and I noticed that in Settings (unlike in Map Viewer) user does not get offered the Download option for offline map. So it seems that map source selection in Settings was considered a "second-class-citizen" even before my move.

Nah, that has been MY fault - I simply hadn't had the map selector in Settings on my mind. I'll create a separate issue and try to prepare a fix for that.

**Comment by eddiemuc** [comment]
@moving-bits never mind, I was again too fast. I found that in Settings the map download is also available, just a bit different (not in map source selection but as a separate entry):
![image](https://user-images.githubusercontent.com/6909759/102806200-b2f14100-43bc-11eb-8b49-05e136008974.png)

**Comment by fm-sys** [comment]
IMHO the map source selection via setting is superfluous. We have quite some of these duplicated settings (I'm also thinking of the quick settings pop-up) and our settings structure is already way too long. (There are reasons why multi screen settings are no longer officially supported in the androidx library... 😉) 

But the majority decides...

**Comment by Lineflyer** [comment]
I would vote for keeping it also in Settings.  Some users rarely use any map menu but set it up once together with directory settings.

I would only remove/relocate such settings once we anyway do major changes to the design. (e.g. as just recently by moving items to the quick settings.).

**Comment by moving-bits** [comment]
> @moving-bits never mind, I was again too fast. I found that in Settings the map download is also available,

Aaarg, I shouldn't answer c:geo-related questions without having c:geo opened right in front of me...
