### ISSUE TITLE
Offer "Download offline map" in map settings

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9562]
Currently the "Download offline map" option is only available in map menu. It should be offerend in the map settings as well. (See https://github.com/cgeo/cgeo/issues/9560#issuecomment-749056328)

**Comment by eddiemuc** [comment]
As written in #9560 : I was too fast with my statement. In fact, map download is also offered in Settings, just a little below map source selection:

![image](https://user-images.githubusercontent.com/6909759/102806417-19765f00-43bd-11eb-9712-61c8af053ef2.png)

**Comment by moving-bits** [comment]
Ah, you're right! Then let's close this issue.
