### ISSUE TITLE
Splash screen flashing in background

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9563]
Since some days I do have strange effects on startup of c:geo. Sadly there has also been a major version update (Andriod 10 - Android 11) also last days, so I am not sure whether the upgrade caused the problem or it was introduced by recent changes on `master`.

- 2020.12.20-NB
- Have setting active "Transparent background"
- Start c:geo

Two possible scenarios:
- Start up takes some time and the splash screen is shown normal, afterwards normal main screen with transparent background
- Start up is fast, but in that case the transparent background is replaced by an overdimensional c:geo logo for a second, afterwards normal main screen with transparent background

A video might explain it better than I can with words:
https://files.droescher.eu/public/PXL_20201221_164045435.mp4

@rsudev Any relation possible to the changes for Sailfish OS?

-

**Comment by moving-bits** [comment]
Never seen that effect so far, neither in the emulator nor in my physical testing device (which is running Android 7, IIRC).

Maybe some splash screen transition effect? (Could be related to #9392, then.)
I've no transition actively set for the splash screen, so it may be some default depending on vendor and OS version.

**Comment by Lineflyer** [comment]
@moving-bits #9584 provides no fix (looks exactly same as initially described in this issue).
Please decide if we shall keep it in anyway or revert?
@SammysHP Can you test regarding #9392 with newest nightly starting 2020.12.26-NB1?

**Comment by moving-bits** [comment]
> @moving-bits #9584 provides no fix (looks exactly same as initially described in this issue).

This has been merged to `release` branch - did you test it from there (or merged `release` to `master` before testing)?

> Please decide if we shall keep it in anyway or revert?

We can keep it in there, it does not harm.

There's another thing I can try, depending on your reply. (Setting `<item name="android:windowActivityTransitions">false</item>` in the theme for the `SplashActivity`.)

**Comment by Lineflyer** [comment]
Tested on nightly but change has of course been merged upstream before. So I should have tested correctly.

**Comment by moving-bits** [comment]
> Tested on nightly but change has of course been merged upstream before. So I should have tested correctly.

Ok, thanks. I'll prepare a PR with the config info shown above - let's see if that helps.

**Comment by Lineflyer** [comment]
No change with recent nightlies.
I do not consider it anyway important...just a glitch. Do not put to much effort in this and lets not try anything which might have negative effects on other devices. 
Maybe some day we will find it out or it gets implicitly solved once we modernize the frontend.

**Comment by Lineflyer** [comment]
Does no longer show up for me.
