### ISSUE TITLE
Cannot set list marker for default list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9577]
Not sure if it this is intentional..however AFAIR this worked before:

- Open default list
- Open menu - Manage lists

Result:
- No option "Set list marker" shown

Expected:
- Option "set list marker" should be available like on all other lists

Version:
2020.12.22-NB but also on 2020.12.03

**Comment by moving-bits** [comment]
I've searched the source code and found the reason why there's no marker available to the standard list:

The list marker id is stored in the `cg_lists` table beside the list id and list name.
But that table only contains actual user-defined lists, not "virtual" ones like "history" or "standard" list, so there's no place to store that info for "standard" list.

@Lineflyer 
If you consider it necessary / useful to be able to assign a list marker for the standard list, we can try to add a workaround for storing the list marker for the standard list, e. g. in a shared preference.

**Comment by Lineflyer** [comment]
I personally do not need that and was not asked by users about it.
So IMHO no need, I just wasn't aware, that the default list does not use the same data structure as all other lists.

**Comment by moving-bits** [comment]
Ok, then let's close this issue. If user requests for this feature should arise, we can easily reopen the issue.
