### ISSUE TITLE
Clean up cache popup menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9578]
While reworking the user manual I stumbled upon two option in the map cache popup menu which are IMHO not needed:
- Remove -> Already present as icon on the popup itself and thus can for sure be removed
- Prevent waypoints from note -> Is this really needful in the popup? IMHO this advanced option is better suitable from cache details

**Comment by murggel** [comment]
Instead of "prevent waypoint from note" I would prefer "edit personal note" in the cache popup - see #8928

**Comment by moving-bits** [comment]
> Instead of "prevent waypoint from note" I would prefer "edit personal note" in the cache popup - see #8928

Please let's keep that issue separate. To realize #8928 much more has to be done than activating/deactivating the menu entry depending on offline state of the cache.
