### ISSUE TITLE
c:geo tries to download PM-only caches for BM

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9583]
User report for beta version 2020.12.22-RC (and verified by me):

- Be logged in as basic member to gc.com
- Search for caches in Munich, Germany
- Load more results to have 40 caches in search result
- Select to store them to a new list (List name automatically set to Munich, Germany)
- Wait until download is finished
- Open the created list

Result:
The list has 40 caches and thus also contains premium only caches, which (up to my knowledge) have been skipped in earlier versions of c:geo while trying to save. Usually I had e.g. 40 caches as result but after downloading them only 40-premium caches in the list

Expected:
It makes no sense to store them as I cannot open them.
I do also see strange cache titles (e.g. for GC5G596) as presumably c:geo cannot resolve the unicode characters as it cannot open the PM cache.

Comment Lineflyer:
I could reproduce it exactly as described above.
Not sure since when this problem occurs, but I agree to the user, that in former versions the PM-only were contained in search results (which is OK) but skipped when storing.

**Comment by SammysHP** [comment]
Maybe #9344? It added parsing of basic data of PMO caches for basic members.

**Comment by fm-sys** [comment]
> Maybe #9344? It added parsing of basic data of PMO caches for basic members.

Definitely. I will try to look into it next week...

**Comment by fm-sys** [comment]
Fix was merged. Close it manually now, since the automatic closing seems to have failed...

**Comment by Lineflyer** [comment]
@fm-sys FYI: Autoclose does only apply if the fix is merged to the base branch (=master). So it would have been autoclosed as soon as `release` is merged back into `master`.

**Comment by fm-sys** [comment]
Interesting, thanks for the info...

**Comment by moving-bits** [comment]
> @fm-sys FYI: Autoclose does only apply if the fix is merged to the base branch (=master). So it would have been autoclosed as soon as `release` is merged back into `master`.

Hm, normally I do a `merge release to master` directly after applying changes to `release`... So either I have forgotten to merge this morning, or autoclose has a hiccup.
