### ISSUE TITLE
Installation wizard

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9589]
While browsing through the Play Store review notifications I've stumbled upon a wide spread between recurring users (beta reviews) and other users (regular reviews). While most beta reviews are four or five star reviews, other reviews have a high occurence of one star reviews, frequently with remarks like
- no caches shown
- no search does work
- app does not work
- Did not let me see ANY geocaches only let me see the map
- ...

IMHO there is a problem with onboarding our new users, the learning curve for c:geo is too steep.

A couple of days ago, while working on a different issue, I had to install a new app "Lockito" for automatically looping over a self-created track. I had no idea how this app worked, but after installation a short wizard took me through the most relevant settings, and so I had this app up and running in no time.

That's when my old idea of a tiny installation wizard for c:geo resurfaced. Today I started working on it, and have come up with the following so far:
|![image](https://user-images.githubusercontent.com/3754370/103156498-65544a00-47a9-11eb-9618-134388b362fd.png)|![image](https://user-images.githubusercontent.com/3754370/103156501-6ab19480-47a9-11eb-9e38-99e84dd40000.png)|
|![image](https://user-images.githubusercontent.com/3754370/103156504-6eddb200-47a9-11eb-9f3e-b61393443bd1.png)|![image](https://user-images.githubusercontent.com/3754370/103156508-7309cf80-47a9-11eb-9d20-17730ac60e5c.png)|
|![image](https://user-images.githubusercontent.com/3754370/103156512-7735ed00-47a9-11eb-94a2-ac0cd9633d29.png)|![image](https://user-images.githubusercontent.com/3754370/103156515-7c933780-47a9-11eb-99d6-131706367871.png)|
|![image](https://user-images.githubusercontent.com/3754370/103156517-8157eb80-47a9-11eb-9a70-b655f6bd4243.png)|![image](https://user-images.githubusercontent.com/3754370/103156519-85840900-47a9-11eb-8130-bef2ab590a9b.png)|
|![image](https://user-images.githubusercontent.com/3754370/103156521-8a48bd00-47a9-11eb-9796-7684192242cf.png)||

As a "bonus" you can select "advanced" on the last screen for an easy access to some more advanced settings:
![image](https://user-images.githubusercontent.com/3754370/103156524-8fa60780-47a9-11eb-97db-c1cc2cb6dd60.png)

This, BTW, also makes our BRouter integration a bit more prominent, as has been mentioned (wished for) earlier in some other issue.

**Comment by Lineflyer** [comment]
Yes, that is long time missing. A lot of people have problems to get started with c:geo and your screenshots look very promising.
Only two small comments:
- While geocaching.com will be the most likely platform people would like to use, I would think about either opening the overview of all our supported platforms and continue from there or at least have another welcome screen step where users can select between two buttons "geocaching.com" and "Opencaching and other platforms".
- AFAIR we do also have the links for "Create an account" for each service already in c:geo. In the "Configure platforms" screen we could add something like "I have an account, continue with login" or "I have to create an account". 

Finetuning for the best text can be done later.
Thanks @moving-bits for this nice work!

**Comment by moving-bits** [comment]
I've changed the text for gc.com to include info about creating an account, and I've added an extra wizard page for the other accounts:
![image](https://user-images.githubusercontent.com/3754370/103167462-95dcc800-482b-11eb-9f0b-5d0a42edffbb.png)|![image](https://user-images.githubusercontent.com/3754370/103167468-9ecd9980-482b-11eb-9994-345c7991c03c.png)

**Comment by bekuno** [comment]
To not confuse new users I would devide in the text between further geocaching platforms and additional services.

**Comment by moving-bits** [comment]
> To not confuse new users I would devide in the text between further geocaching platforms and additional services.

Or maybe do not explicitly name gcvote.com and geokrety.org in the wizard, as they do not provide access to geocaches?

**Comment by Lineflyer** [comment]
> Or maybe do not explicitly name gcvote.com and geokrety.org in the wizard, as they do not provide access to geocaches?

Yes, this could go into the advanced part.

Additionally I will check strings and provide text improvement proposals....should the wizard really use the "I am" form?

**Comment by moving-bits** [comment]
> > Or maybe do not explicitly name gcvote.com and geokrety.org in the wizard, as they do not provide access to geocaches?
> 
> Yes, this could go into the advanced part.

Currently I'm linking to the "services" page in c:geo settings from both the new wizard page and the advanced page - which lists both platforms and services.
I'll remove the two services from the info string shown during the wizard.
Shall I revert to the term "platform" throughout the regular wizard pages, and only use "services" on the advanced page?

> Additionally I will check strings and provide text improvement proposals...

Thanks, looking forward to.

**Comment by Lineflyer** [comment]
> >  Additionally I will check strings and provide text improvement proposals...
>
> Thanks, looking forward to.

Currently looking into it...coming back to my question therefore:
Shall we really use the form like "I am your installation wizard"?

**Comment by fm-sys** [comment]
On my device the changelog opens up after configuring c:geo. That might be confusing for first time users... 

Also I would leave the other geocaching services as a stand alone screen out and preferably make the advanced settings more prominent... 

> Shall we really use the form like "I am your installation wizard"?

I personally like it 😉

**Comment by Lineflyer** [comment]
After having tried the current state I have the following proposal for discussion:
- For the first "Configure platforms" screen, how about have two checkboxes below:
  - geocaching.com -> As "Next" now
  - Other supported services -> Open service menu
- The "Previous"/"Skip" and "Next" buttons are rather small and tightly bound to the bottom of the display. Couldn't we place them a little bit above the bottom and make them more bold/bigger?
- The changelog display should be ommitted after the wizard is completed (same as commented by @fm-sys )

**Comment by fm-sys** [comment]
And we might think about removing the old "getting started" page from the about screen as it's IMHO fully replaced by the new installation wizard...

**Comment by moving-bits** [comment]
I've created an update to the installation wizard (see #9613) which addresses the first two points from @Lineflyer (and other aspects). Other open issues to follow (tomorrow).

**Comment by moving-bits** [comment]
Another idea which I would like to open for discussion:

Currently I'm calling the wizard only once, after a fresh install.

How shall we react, if something's missing at a later point in time (eg: rights revoked, no platform active etc.)?
- option 1: ignore - the user has to find out theirself what's going on (as today)
- option 2: How about checking the (currently) three prerequisites (location permission, storage permission, at least one active geocaching platform) on startup and open the wizard, if something's missing.
- option 3: Or we could check it and add a menu entry "complete configuration" to the mainscreen's menu if something's missing (but not automatically open the wizard)

What do you think?

**Comment by geocachermgo** [comment]
I think we all can not really evaluate or test it since its made for the ones that are at the moment not able to get it started.
Question: is the startup for the geocaching.com app easier? So we/I could try to get testers from that group?
Can be easily recognized by having the "upload by GC App" at their pictures.

**Comment by eddiemuc** [comment]
Hi @moving-bits it seems the wizard is about to be designed to fulfill two purposes at once:
* First step guide to new users
* Setup checker to evaluate whether all basic settings are correct

With this in mind I would vote for option 2 as well as option 3. User should have the possibility to switch off the startup popup though, because c:geo has evolved so far that there might even be users using it solely as a navigation app or an offline map display tool (I do this myself sometimes e.g. when hiking with my family :-)). And for that no Geocaching service is needed.

Also I read the critical receptions on Google Play today, and it seems we might profit from a more prominent option for users to send us logfiles etc in case of problems (instead of writing a negative reception). Do you think it would be possible to tell the users in the wizard to use the "Report a problem" entry in the main screen menu in case of problems?

**Comment by Lineflyer** [comment]
There might also be users, which explicitly use c:geo without active connector, e.g. using GPX only.

Still the idea is good, therefore it might be another case for a one time message?!

e.g. "You do not have any geocaching service configured. Do you want to start the configuration wizard to help you..."

AFAIR the permission dialogs reappear anyway or @moving-bits  did you change this? This can IMHO stay as it is.

**Comment by fm-sys** [comment]
IMHO option 3 would be nice (with same style as the "an update is available" message box)

**Comment by moving-bits** [comment]
Updated the wizard to include the following things:
- changelog is no longer shown on fresh installs
- configuration wizard is available from main menu (only for incomplete installations)
- removed about:starting page
- stay on platforms wizard page on returning from gc.com authorization (so that you can add other platforms, if needed)
- make platforms info on final wizard page easier to understand
- prefill (partial) gc.com authorization data (if exists)

![image](https://user-images.githubusercontent.com/3754370/103245443-798e7780-4960-11eb-8821-9e00999a68dc.png)|![image](https://user-images.githubusercontent.com/3754370/103245490-a3479e80-4960-11eb-85cc-a36a4496d73e.png)
![image](https://user-images.githubusercontent.com/3754370/103245451-801cef00-4960-11eb-9370-1c1aa1bfec9d.png)

**Comment by moving-bits** [comment]
@geocachermgo 

> I think we all can not really evaluate or test it since its made for the ones that are at the moment not able to get it started.

If you like to test the new wizard there are several options you can do so with one of our nightly builds:
- Install c:geo on a device which has no installation of c:geo yet. 
  => wizard will open automatically on first start of c:geo
- If the device already has an installation of c:geo and reinstall is an option for you:
  Create a backup, uninstall and then reinstall c:geo
  => wizard will open automatically on first start of c:geo
- If the device already has an installation of c:geo:  
  Delete the settings key "username" (using settings => system => view settings; if gc.com is your only activated gc platform) and/or remove granted permissions for c:geo
  => Configuration is regarded "incomplete" then, and you can start the configuration wizard from the mainscreen's menu

(The last option will only be available starting with the upcoming nightly.)

**Comment by Lineflyer** [comment]
Thanks @moving-bits for this long overdue wizard!

Lets close here and better open dedicated issues for single improvement topics or related bugs.
