### ISSUE TITLE
Open in browser opens c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9592]
Several user reports on support mail for 2020.12.26-RC:

- If I select "Open in Browser" c:geo itself opens the cache in a new instance. Before this udpate I got a selection with c:geo, Firefox, etc.
- If I select "Open in Browser" it was previously opened in the "c:geo internal browser". Now it just opens c.geo again without asking which browser to use

That is seemingly a side effect of the changes regarding Chrome webview.
Is there a way to mitigate the problem, that people end up with c:geo while they used another target app before?

**Comment by Lineflyer** [comment]
Addition:
Or at least permanently exclude c:geo itself as target for the intent from the "Open in browser" function? AFAIR someone posted a link around here describing that such thing is feasible.

**Comment by wolverine007** [comment]
I am still on 2020.12.22-RC, on this release everything is fine.

Inside Android you could set a default app for several different apps or even link types, maybe here something changed with the latest update. 
But this is definitely a local user issue. 

I also recognized that Firefox nowadays wants to open the caches inside the app, even when triggering from the app to be opened inside the browser. Inside the Firefox settings you could disable this function, but only in total, also a little bit annoying...

**Comment by Lineflyer** [comment]
> Inside Android you could set a default app for several different apps or even link types, maybe here something changed with the latest update.

Yes, something changed, i.e. we removed the c:geo internal browser whichbsome users might have used before. So they will now end up in c:geo itself again as the replacement for the internal browser (Chrome webview) is not active by default.

Activating it by default on the other hand would lead to problems for users which do not have Chrome installed AFAIK.

**Comment by fm-sys** [comment]
Maybe we can detect such a loop and activate the Chrome webview automatically in this specific case...

**Comment by Lineflyer** [comment]
I think that this issue only affects users previously having set the default for this intent to c:geo. 

In previous versions this would offer them the internal browser and c:geo. As the internal browser is gone, they end up in c:geo "automatically".

The reason we deactivated the "chrome webview" by default was some discussion about the scenario if Chrome is not available on a device. Couldn't we still activate it by default (thus solving this issue for many users and providing a nice feature) and additionally try to find a way out if Chrome webview is not available?

**Comment by fm-sys** [comment]
![Screenshot_20210103_181203_com huawei android internal app_copy_431x262](https://user-images.githubusercontent.com/64581222/103484494-73c8e400-4def-11eb-9380-1883700807d2.png)

For me, it shows the chooser without the possibility to select a default. So it's probably a device specific problem which is hard to reproduce and therefore hard to solve... 
I will have look!

@Lineflyer does the users had the possibility to select the internal browser in a chooser or did it was opened directly?

**Comment by Lineflyer** [comment]
I think it was opened directly in the internal browser.

Regarding the options you see:
Once you deinstall Firefox and Geocaching I guess you will have this "loop" into c:geo as well.

**Comment by IiroP** [comment]
I think the default behaviour is that the system asks which app you would like to use, but it can be overridden.

If I go to the System Settings and find c:geo there, there is the _Open by default_ section. There is an option _Open supported links_  and if you select _Open in this app_ instead of the _Ask every time_, it'll open cgeo without asking anything. 

Can you verify if those users have this option?

_I'm using OnePlus 5T with OxygenOS, Android 10._

**Comment by fm-sys** [comment]
#9668 was merged which hopefully fixes this issue. But let's keep it open until an affected user can verify that this issue is really solved by the PR

**Comment by fm-sys** [comment]
@IiroP are you affected by the issue? If yes, I can inform you as soon as the PR is out in the release version...

**Comment by fm-sys** [comment]
@IiroP Thanks to your help with testing I came up with the right idea which should (hopefully) have solved the issue! We have released a new version yesterday that contains the fix. 

@Lineflyer Any news from support side about the "Open in browser" action? Can we close this issue?

**Comment by Lineflyer** [comment]
Lets wait a few more days but until now it looks promising also during my tests.

**Comment by fm-sys** [comment]
@Lineflyer can we close this now?

**Comment by Lineflyer** [comment]
I think so. Until now no negative feedback on support mail. Thanks :)
