### ISSUE TITLE
Users missing map settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9593]
Several mails on support mail from beta users 2020.12.22-RC:

- All the map settings are gone in the beta version?
- Why do I need to change hiding own caches now from the settings each time. It was better in last version where it was possible from the map menu!
- I can no longer change the routing between walk, drive. The menu is no longer where it was before.

Maybe it would be good to add a dismiss-able message box (didn't we introduce such generic function recently) when entering the map to explain, that all map customization has been moved to the quick settings and where they can be found?

**Comment by moving-bits** [comment]
I'll prepare a `OneTimeDialog` for it.
