### ISSUE TITLE
Migrate and use SAF for storing external user data (previous /cgeo/*)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9606]
Currently c:geo is storing external user data in `/cgeo/*` using the plain file access permission. 

Details about the current disk usage structure can be found here: https://github.com/cgeo/cgeo/wiki/Disk-usage-structure
We are talking about item <3> of the table in this wiki article (typically used for GPX imports and exports, logfiles, backups and in default case optionally also offline maps).  

Starting with target SDK=30 Android enforces to use the StorageAccessFramework (SAF) instead of plain file access permissions.
Therefore we should migrate from the current access mode into using the SAF.

The general approach has been discussed in #8457 already, which I try to summarize below (correct me, if I am wrong):
- Use SAF to request access to a base directory, which from then on is used by c:geo for storing the mentioned data and we simply use the structure below as we do today for `/cgeo/`.
- For fresh installations the user might set the base directory up to his own choice. This setup should be implemented into the installation wizard at some point (see #9589)
- In the upgrade case we recommend to the user to select the existing `/cgeo/` to be used as his base directory, which thereafter does not require any special migration. 

To be agreed/clarified (or I missed it in the original thread):
- Do we want to take care of any migration steps (i.e. copy/move files) if an existing users selects another base directory than `/cgeo/` or simply fire and forget the `/cgeo/` and let the user clean up?
- Currently we have a dir chooser to select GPX import and export directories. I would prefer to use this opportunity to get rid of these menus (and the ugly dir chooser) and simply focus everything into the selected base directory and the existing structure below (directory /gpx/). Users shall places their imports into this dir to use the internal GPX import function. Alternatively they can open GPX files with c:geo anyway. For exports we store them in our structure and offer sharing them (this is on the way or already implemented AFAIK).

**Comment by geocachermgo** [comment]
Will this affect to read maps from the locus directory?

**Comment by Lineflyer** [comment]
> Will this affect to read maps from the locus directory?
For sure, see #9609 for this topic

**Comment by eddiemuc** [comment]
Largely adressed in branch `storage_framework`, please use it as a base for contributions.
Aslo please give me (@eddiemuc) a short hint before you do since I currently `rebase ` this branch onto `master ` frequently using forced pushes.

**Comment by eddiemuc** [comment]
@Lineflyer with regards to the open points:

> Do we want to take care of any migration steps (i.e. copy/move files) if an existing users selects another base directory than /cgeo/ or simply fire and forget the /cgeo/ and let the user clean up?

Imho we should provide the option to copy/move files from previous dir to the newly selected one after the user chooses a new base folder. This includes the option to copy stuff from original "cgeo" folder. Not more than that.

> Currently we have a dir chooser to select GPX import and export directories. I would prefer to use this opportunity to get rid of these menus (and the ugly dir chooser)

This is indeed part of the plan

**Comment by Lineflyer** [comment]
> Imho we should provide the option to copy/move files from previous dir to the newly selected one after the user chooses a new base folder. This includes the option to copy stuff from original "cgeo" folder. Not more than that.

Agreed.
This probably means (to my understanding), that we need to introduce SAF while still keeping the current disk access permissions to be able to copy/move. This then means that targetSDK=30 (and removing of legacy file access) needs to be introduced well after introducing SAF. Correct?

**Comment by eddiemuc** [comment]
> > Imho we should provide the option to copy/move files from previous dir to the newly selected one after the user chooses a new base folder. This includes the option to copy stuff from original "cgeo" folder. Not more than that.
> 
> Agreed.
> This probably means (to my understanding), that we need to introduce SAF while still keeping the current disk access permissions to be able to copy/move. This then means that targetSDK=30 (and removing of legacy file access) needs to be introduced well after introducing SAF. Correct?

If I remember correctly there is some flag you can set for exactly this migration purpose: it will allow you the old way of file access even on API30 but only for apps installed before the device upgrade and only until the app is deinstalled.

**Comment by eddiemuc** [comment]
@lineflyer, @moving-bits, @bekuno I have a question with regards to our ci. I would like to write some unit tests working with SAF, but in order for them to work on the CI the emulated Android device on it needs a SAF folder with granted access. This can't be done in code, someone would need to grant this access one time (using a Setting I can provide, visible only in debug mode).
Is that possible? Can someone access this CI Android device manually including GUI usage? Would be a one-time-thing.

**Comment by Lineflyer** [comment]
AFAIK its an emulated device which will be created new each time tests are running.
I am not familiar with Android emulators and whether such thing is possible.

@mucek4 @kumy Do you know?

**Comment by eddiemuc** [comment]
Another question with regards to CI: is it possible to view somewhere the logcat logfile created by the device during test run? Or is there any other way to log information in Unit tests which is then somehow visible on the Jenkins server?
(In the normal console log of the Jenkins Job I can't find anything; I tried using Log.iForce as well as System.out.println)

**Comment by eddiemuc** [comment]
Aaaah, I am very frustrated! The SAF DocumentFile framework is working but terrribly slow. Have to get back to the drawing board and use the contentresolver query interface instead... 

Sorry, I just needed to express this.

**Comment by eddiemuc** [comment]
A question around regarding importing of GPC files:
it seems an SAF solution for importing GPX files is already build into c:geo since 2014. It is called "Import from Android" and works fine. So GPX import migration would consist simply of removing the other option "Import GPX" and maybe change the button texts.

![image](https://user-images.githubusercontent.com/6909759/103484597-403a8980-4df0-11eb-984b-a162299bc28a.png)

Is it really as simple as that? Or are there any concerns?

**Comment by Lineflyer** [comment]
> Is it really as simple as that? Or are there any concerns?

Basically yes. But users might also have placed GPX for import into `[base folder]/gpx` as they are used to from the past. Or import a GPX again which they exported into that directory before.
So we need a clever way to offer importing from there as well as importing via SAF (using the already implemented way).

**Comment by eddiemuc** [comment]
> So we need a clever way to offer importing from there as well as importing via SAF (using the already implemented way).

You can look into this dir searching for GPX files same as before. I would make it the startup dir when file chooser dialog opens. Ok?

We could offer multi-file-select, but I don't know if people are interested in that.

**Comment by Lineflyer** [comment]
> You can look into this dir searching for GPX files same as before. I would make it the startup dir when file chooser dialog opens. Ok?

Thats probably the clever solution I had in mind :)

> We could offer multi-file-select, but I don't know if people are interested in that.

Not sure either...if its straight forward to use (click one or many as you like) and we accept that all are imported to the same target list....why not.

Regarding menu items:
"Import GPX" --> removed
"Import from Android" --> reuse string and name it "Import GPX"

**Comment by eddiemuc** [comment]
@moving-bits I saw in code that you very recently added many mechanisms dealing with public files (TrackFiles in May 2020, IndividualRouteFiles in August 2020, MapDownload-Metainfo just yesterday (but we talked about this)).

This makes my work hard because I have to migrate all those places to SAF one by one, possibly introducing errors as I go. It would be good if we could postphone non-urgent issues dealing with public files while I am in middle of migration.

**Comment by Lineflyer** [comment]
> This makes my work hard because I have to migrate all those places to SAF one by one, possibly introducing errors as I go. It would be good if we could postphone non-urgent issues dealing with public files while I am in middle of migration.

Yes, thats a valid point. AFAIK there is currently no further change in progress.

Regarding the further proceeding about SAF:
My idea would be to get the current beta finalized and published, then branch again (given we have a stable situation) for another smaller feature release and afterwards we could finally merge the SAF progress onto master and continue there. This would avoid the further merging and rebasing efforts I guess.

**Comment by moving-bits** [comment]
> Regarding the further proceeding about SAF:
> My idea would be to get the current beta finalized and published, then branch again (given we have a stable situation) for another smaller feature release and afterwards we could finally merge the SAF progress onto master and continue there. This would avoid the further merging and rebasing efforts I guess.

Sounds very reasonable to me.

**Comment by eddiemuc** [comment]
Anytime :-)

**Comment by moving-bits** [comment]
> @moving-bits I saw in code that you very recently added many mechanisms dealing with public files (TrackFiles in May 2020, IndividualRouteFiles in August 2020, MapDownload-Metainfo just yesterday (but we talked about this)).
> 
> This makes my work hard because I have to migrate all those places to SAF one by one, possibly introducing errors as I go. It would be good if we could postphone non-urgent issues dealing with public files while I am in middle of migration.

Sorry, @eddiemuc, it's not my intention to make your life harder.

I've made a couple of additions last year and this year regarding importing and exporting several kinds of GPX files (GPX track file, GPX route file, individual route file, history track), but all those are of the same file type and go into the same directory, so I guess they can be handled more or less the same during migration. (IMHO we can even skip the settings that remember the currently chosen track file and request to user to re-select that once after migration, if that helps with migration.)

Other changes to the file systems by me have been (AFAIR)
- reading/writing settings backup in `<base>/backup` dir
- creating logfiles in `<base>/logfiles` dir
- copying offline map files to `<base>/maps`, yesterday complemented by map description files in the same dir (as discussed)

Currently I have no plans for adding more :-)

**Comment by eddiemuc** [comment]
@moving-bits no worries :-)

**Comment by eddiemuc** [comment]
@moving-bits I have a question wrt Track and Route files. It seems that the user can select files to open on the whole device for loading (e.g. those are public files). Is this intended? And must it be possible to save changed files then back to the same location?

**Comment by moving-bits** [comment]
> @moving-bits I have a question wrt Track and Route files. It seems that the user can select files to open on the whole device for loading (e.g. those are public files). Is this intended? 

Yes, using our file selector. => Can be replaced by the SAF file selector with `<base> /gpx` as preselected default (if possible).

> And must it be possible to save changed files then back to the same location?

Saving those files is done to the selected GPX export folder, IIRC, defaulting to `<base> /gpx`.
It does not necessarily have to be the same location as the file was read from. It's not "update the current file" but "write current track/... to a file".

**Comment by eddiemuc** [comment]
> > @moving-bits I have a question wrt Track and Route files. It seems that the user can select files to open on the whole device for loading (e.g. those are public files). Is this intended? 
> 
> Yes, using our file selector. => Can be replaced by the SAF file selector with `<base> /gpx` as preselected default (if possible).
> 
> > And must it be possible to save changed files then back to the same location?
> 
> Saving those files is done to the selected GPX export folder, IIRC, defaulting to `<base> /gpx`.
> It does not necessarily have to be the same location as the file was read from. It's not "update the current file" but "write current track/... to a file".
> 
> 

Ok thank you. I feared for a moment that c:geo writes continuously to a public file. This would be a case I haven't covered yet. What you wrote should be easy to do though (tomorrow...)

**Comment by moving-bits** [comment]
> I feared for a moment that c:geo writes continuously to a public file.

Not that I know of. Position history is kept in the database, and all those GPX files are written on demand only.

A selected GPX track/route file may be _read_ several times, though - on each activity restart.

**Comment by eddiemuc** [comment]
> A selected GPX track/route file may be _read_ several times, though - on each activity restart.

If such a file is selected and used, then c:geo is stopped and restarted: does the same file need to get read again without the user reselecting it? (Then we need persisted permissions with file selection, I only coded that for directories as of now)

Is it possible to copy the file (once the user selected it) to a c:geo-folder and use it from there? Or would that somehow interrupt the users workflow? Is it expected that the user changes the selected file outside c:geo and expects tonsee those changes when c:geo is restarted?

**Comment by moving-bits** [comment]
> > A selected GPX track/route file may be _read_ several times, though - on each activity restart.
> 
> If such a file is selected and used, then c:geo is stopped and restarted: does the same file need to get read again without the user reselecting it? (Then we need persisted permissions with file selection, I only coded that for directories as of now)

Yes, probably. Filename of selected trackfile is stored in our settings, see `Settings.getTrackFile()`.

> Is it possible to copy the file (once the user selected it) to a c:geo-folder and use it from there? Or would that somehow interrupt the users workflow? Is it expected that the user changes the selected file outside c:geo and expects tonsee those changes when c:geo is restarted?

I don't know from real user experience, but I guess it might be pretty confusing if you update your source file, and those changes are not reflected in the app. OTOH the feature to read track/route files is relatively new, so it might not have that many users yet, and we may be able to change the behavior.

If we decide to such sort of "importing" a chosen GPX track/route file, we might as well put the file contents into the database (`DBExtension`) to not have to parse it each and every time, and to not leave any file remainders in the directory.

**Comment by eddiemuc** [comment]
@moving-bits during migration I stumbled upon `cgeo.geocaching.utils.LogWriter`, which you recently created. I noticed (to my surprise) that it is not used anywhere in code. Is this class still needed (and hence to be migrated to SAF) or can it be deleted?

**Comment by eddiemuc** [comment]
And another question: in SettingsACtivity I found the enum DirChooserType with four values:
![image](https://user-images.githubusercontent.com/6909759/103671701-8f60f580-4f7b-11eb-9293-d86b7f1f3a79.png)

If I remove THEME_DIR then the Map Theme directory chooser does no longer work, so this is related.

But where can the user select directories for GPX-Import, GPX-Export and Backup? Or are these values outdated?

**Comment by fm-sys** [comment]
> But where can the user select directories for GPX-Import, GPX-Export and Backup

`BACKUP` is used for restoring from a different file location...

You can find the usage by searching for usage of the keyId. Most probably they are used in `preferences.xml`

**Comment by moving-bits** [comment]
> But where can the user select directories for GPX-Import, GPX-Export and Backup? Or are these values outdated?

Standard dirs for GPX import/export can be selected in our preferences, see "offline data" section.

**Comment by eddiemuc** [comment]
> > But where can the user select directories for GPX-Import, GPX-Export and Backup
> 
> `BACKUP` is used for restoring from a different file location...
> 
> You can find the usage by searching for usage of the keyId. Most probably they are used in `preferences.xml`

Ok found it, thanks a lot.

So we also need possibility to transiently select directories. Back to the SAF framework...

**Comment by eddiemuc** [comment]
> > But where can the user select directories for GPX-Import, GPX-Export and Backup? Or are these values outdated?
> 
> Standard dirs for GPX import/export can be selected in our preferences, see "offline data" section.

Top, found it. Thanks a lot!

**Comment by moving-bits** [comment]
But IMHO we wanted to get rid of having to remember two user-selected GPX dirs with SAF and do GPX import by on-the-fly user-selected dir (SAF), and GPX export to a fixed dir `<base> /gpx` (which could also serve as starting point for SAF GPX import selection).

**Comment by moving-bits** [comment]
> @moving-bits during migration I stumbled upon `cgeo.geocaching.utils.LogWriter`, which you recently created. I noticed (to my surprise) that it is not used anywhere in code. Is this class still needed (and hence to be migrated to SAF) or can it be deleted?

Nearly missed this one in my batch of today's emails :-)

I was once working on an issue where I needed a log of the full http conversation. Our regular log functions (or better: logcat) always truncated after a certain length, so I introduced this function to help me out. So it's only an internal helper function, and currently not in use.

Maybe let's keep it in, but add some "big red alert" comment "to be migrated to SAF" (or something like it) as reminder that we will have to update that function to SAF when we need it again.

**Comment by fm-sys** [comment]
> So we also need possibility to transiently select directories. Back to the SAF framework...

Aren't there file/directory choosers provided by the android system? These can be used here, the cgeo internal directory chooser wasn't really nice anyway...

**Comment by eddiemuc** [comment]
> > So we also need possibility to transiently select directories. Back to the SAF framework...
> 
> Aren't there file/directory choosers provided by the android system? These can be used here, the cgeo internal directory chooser wasn't really nice anyway... 

Yes, there are these choosers. But they deliver Uris, not Files. Since c:geo uses publix files rather extensively I spend the last weeks creating some sort of '"framework" to.encapsulate Uri and Stream handling and enable it to use Files and SAF interchangeable. This "framework" does not support transient dir selection yet (only persistent ones). But it will :-)

**Comment by eddiemuc** [comment]
@moving-bits I just migrated tracks and individual routes. It seems to me that individual routes does NOT have a **persisted** file uri? At least I couldn't find any settings for it. (for Tracks I could find it)

**Comment by moving-bits** [comment]
> @moving-bits I just migrated tracks and individual routes. It seems to me that individual routes does NOT have a **persisted** file uri? At least I couldn't find any settings for it. (for Tracks I could find it)

Exactly, as an individual route is kept in the database.
You may import/export it from/to a GPX file, but the current one is stored in the db.

**Comment by eddiemuc** [comment]
> > @moving-bits I just migrated tracks and individual routes. It seems to me that individual routes does NOT have a **persisted** file uri? At least I couldn't find any settings for it. (for Tracks I could find it)
> 
> Exactly, as an individual route is kept in the database.
> You may import/export it from/to a GPX file, but the current one is stored in the db.

Ah ok got it, thank you. Seems I misunderstood you before

**Comment by eddiemuc** [comment]
Ok, Tracks, Ind.Routes and GPX is done. Check out storage_framework for a sneak peek.

Now I start with "backup". I have a question with regards to "corrupted" database files. There seems to be some (legacy?) mechanism in c:geo where we search for a database file in backup folder named "data.corrupted" in the backup dir in case we fail to open the primary db. This will, of course, no longer work with SAF (at least not reliably). 

Is this mecahnism still needed? And if yes, how is it supposed to work? WHere is this "data.corrupted" file coming from?

https://github.com/cgeo/cgeo/blob/90e2fecff5a7b06459fbd15d08d57b3b0fe045ef/main/src/cgeo/geocaching/storage/DataStore.java#L753-L760

**Comment by eddiemuc** [comment]
Stumbled across the next thing: "Spoiler Images"

There is an external directory defined in LocalStorage namend "GeoCachePhotos" which is supposed to contain "spoiler images":

https://github.com/cgeo/cgeo/blob/ccb0385dd8b65b5fb124e418dbf4cf4499ad24e2/main/src/cgeo/geocaching/storage/LocalStorage.java#L344-L347

I do not have this dir on my installation. A quick code scan seems to indicate that this is only used for oc and su. 

![image](https://user-images.githubusercontent.com/6909759/103870723-63a15500-50cc-11eb-9163-e3061e5a3baf.png)


I don't use SU and OC very seldom, have not come across these spoilers yet. What is this, and is it still needed? If yes, can it go to a private folder?

**Comment by fm-sys** [comment]
> If yes, can it go to a private folder?

IMHO yes. Spoiler images should not even be publicly visible ;-)

**Comment by eddiemuc** [comment]
> > If yes, can it go to a private folder?
> 
> IMHO yes. Spoiler images should not even be publicly visible ;-)

Do you know what these "Spoiler images" are conceptually? And why they are treated somehow differently from all other images? And why they seem to exist only for OC and SU?

**Comment by eddiemuc** [comment]
Moved "Spoiler" thingy to new issue: #9719

**Comment by eddiemuc** [comment]
As of now storage_framework contains complete SAF migration for c:geo with following exceptions:
* Offline log image: treated with separate issue #9609 
* Backups: treated with separate issue #9720 
* Spoilers: sep. issues #9719 
* Map Themes: trated with separate issue #9607 

Concept is documented in wiki (https://github.com/cgeo/cgeo/wiki/Disk-Usage-migration-towards-Android-11) and review is handled by another issue (#9661)

This issue's coding results can be reviewed and tested in branch storage_framework. 

Thus I would consider this issue closed. Any objections?

**Comment by eddiemuc** [comment]
Added PR #9731 which shall end `storage_framework`

**Comment by MagpieFourtyTwo** [comment]
Sorry for jumping in at this point, missed this thread completely so far, and in fact I just stumbled upon the "Chose a directory" dialog this night, after updating to the latest nightly ... which caught me pretty off guard, thus a perfect real world test. ;)

However, I had a really hard time to understand what I have to do and what the results are ... and even though I count myself as an "above average user" I finally ended up with no Offline Maps anymore ... and I still don't know what will happen to my Ex- and Imports and the rest of my stuff ... even backup folders appeared to be doubled(!) afterwards (don't know how this happened, had 5 to 6 backup folders and after this "Chose Dir" procedure every one has a similar named sibling with no content at all).

BTW: After I at least restored the vector map folder, I ended up with a completely scrambled Offline Map list, which should be sorted alphabetically, again.  ;)

Anyway - I know, it's hard to explain what happens behind the scenes, but to me this text and the steps one has to take afterwards, are way to much to handle for Joe Average. In order to not getting the support flooded with questions about which directories to chose, how to get back maps and stuff and where will my exports go .., we need a clear list of steps over there, which tells the user how he can get to the situation he had before he was forced to grant access to some folders ...

Maybe steps are in progress anyway, to e. g. automate the stuff needed to use SAF or guide the user through this process by e. g. choosing all of his his folders step by step, so he knows where his stuff comes from and where it will go, be but the way it is now is IMO not bearably by an average user ...

As for me, I would have loved to see an example at least, based on my previous settings as just getting "chose cgeo" is a little bit ... short.

**Comment by fm-sys** [comment]
@MagpieFourtyTwo Very valuable thoughts! However, I'm a bit scared that they might get lost here in this closed issue. BTW, I've also tried to express the same fear in https://github.com/cgeo/cgeo/issues/9809#issuecomment-762219162

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo 
* First of all: I apologize for the duplicated backup folders, this is a bug of mine. Will fix as soon as possible (but difficult for me to code on c:geo during the week).
* wrt the whole UX experience: although I tried to trigger this discussion already some month ago and change is available via storage_framework for a long time, I still expected that this discussion will get serious not before the SAF stuff is in master. So no worries, nothing set in stone yet :-)

**Comment by Lineflyer** [comment]
I have opened #9870 and #9872 for the problems mentioned by @MagpieFourtyTwo . Please kindly continue over there. :)

**Comment by MagpieFourtyTwo** [comment]
> First of all: I apologize for the duplicated backup folders, this is a bug of mine. Will fix as soon as possible (but difficult for me to code on c:geo during the week).

Just for my understanding: Usually name dupes are prevented by the file system ... so how was this possible at all?
Would have assumed hard links, but then they would not be empty ... so any kind of hidden name components or non-printables ...?

**Comment by moving-bits** [comment]
The names are not exactly the same - see the addition "-" between date and time part.

**Comment by MagpieFourtyTwo** [comment]
Ah, ok, missed that - deleted them too fast. ;)
