### ISSUE TITLE
[minor] No sorting when in selection mode

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9608]
**Describe the bug:**
If in a list the selection mode ("Auswahlmodus") is active sorting does not work, even after the end of selection mode.

**To Reproduce:**
1. Go to list
2. Click on menu, selection mode
3. Click on menu, sorting e.h. GC number 

**Actual behavior/state after performing these steps:**
Sorting is not changed

**Expected behavior/state after performing these steps:**
Sorting menu should be disabled or work

**Version of c:geo used:**
2020.12.24-NB-a2423d5

**Is the problem reproducible:**
Yes

**Comment by Lineflyer** [comment]
Duplicate of #4507?

**Comment by geocachermgo** [comment]
Yes
