### ISSUE TITLE
proximity circles are still buggy 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9612]
The proximity circle (although perfectly fine working in OSM now) now gets deleted way too often in GMap: After zooming it shortly appears, then disappears again ...

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/9552#issuecomment-751302745_

**Comment by MagpieFourtyTwo** [comment]
Thx for opening an extra issue for that.

Additional observation: In GMap, if there is no circle, just wait a moment, it will appear after a while (which seems to be be an effect of position jumps). When the circle is there again, just click the zoom "-" and it will be gone again.  And sometimes it initially flashes once, then disappears and needs 5-10 secs again to appear again ... but once it is there, it stays most of the times, until you zoom or pan, then it disappears again ... while panning must be at least over a quarter of the screen.

**Comment by wolverine007** [comment]
I am facing a similar problem inside 2020.12.22-RC - during a map type switch from offline OSM to Goggle Maps, the circles are gone
I have to unselect them inside the quick settings menu and leave the menu. Reopen the menu and enable them again, so they are shown on the map.
During the last days I was also seeing one circle around no cache icon, switching back to OSM, the icon was shown again.

**Comment by Lineflyer** [comment]
> I am facing a similar problem inside 2020.12.22-RC - during a map type switch from offline OSM to Goggle Maps, the circles are gone

You are probably referring to the 161meter distance circles but not the proximity circles. Feel free to open a dedicated issue for your problem.

**Comment by MagpieFourtyTwo** [comment]
> During the last days I was also seeing one circle around no cache icon, switching back to OSM, the icon was shown again.

Apparently, he also stumbled upon the "Invisible Caches" problem #9374 ...?
