### ISSUE TITLE
 java.lang.ClassCastException on GMaps

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9619]
New in 2020.12.22-RC:

occurrences 4,  users 4

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2946)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3081)
  at android.app.ActivityThread.handleRelaunchActivityInner (ActivityThread.java:4847)
  at android.app.ActivityThread.handleRelaunchActivity (ActivityThread.java:4756)
  at android.app.servertransaction.ActivityRelaunchItem.execute (ActivityRelaunchItem.java:69)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1831)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6810)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
Caused by: java.lang.ClassCastException: 
  at cgeo.geocaching.maps.CGeoMap.onCreate (CGeoMap.java:591)
  at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreate (GoogleMapActivity.java:59)
  at android.app.Activity.performCreate (Activity.java:7224)
  at android.app.Activity.performCreate (Activity.java:7213)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1272)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2926)
```

Related to already solved #8941

**Comment by moving-bits** [comment]
It points to this line in CGeoMap:

`mapView = (MapViewImpl) activity.findViewById(mapProvider.getMapViewId());`

@eddiemuc 
Can this be related to the SAF preparations for map provider?

**Comment by eddiemuc** [comment]
> It points to this line in CGeoMap:
> 
> `mapView = (MapViewImpl) activity.findViewById(mapProvider.getMapViewId());`
> 
> @eddiemuc 
> Can this be related to the SAF preparations for map provider?
> 

This is not related to SAF.

I looked at the code. My best guess is that for whatever reason the activity at this point is somehow bound to the Mapforge-View. This would definitely lead to the classcastexception. But I can't figure out why such a thing would happen. Would be good if we had a log or other context information

**Comment by moving-bits** [comment]
> My best guess is that for whatever reason the activity at this point is somehow bound to the Mapforge-View.

`getMapViewId` returns either `R.id.map` (for GM) or `R.id.mfmapv5` (NewMap) which seems ok to me, so I guess it's more likely that the mapProvider points to a wrong value.

`mapProvider` is getting its value from `Settings.getMapProvider()` which calls `MapProviderFactory.getMapSource()` if needed. If the mapsource string from settings cannot be translated into an existing/available mapsource, it returns `MapProviderFactory.getAnyMapSource()`.

> But I can't figure out why such a thing would happen. Would be good if we had a log or other context information

Agreed. @Lineflyer Anything on support about this error?

As this error only seems to happen on the Google Maps side, and our old map framework (`CGeoMap`) only supports Google Maps (as we have discontinued MFv3), couldn't we just set mapProvider to `GoogleMapProvider` in `CGeoMap`?

**Comment by eddiemuc** [comment]
> As this error only seems to happen on the Google Maps side, and our old map framework (`CGeoMap`) only supports Google Maps (as we have discontinued MFv3), couldn't we just set mapProvider to `GoogleMapProvider` in `CGeoMap`?

Sounds reasonable. 

What is the reason why there are two different activities for GM and MF anyway?

**Comment by moving-bits** [comment]
> What is the reason why there are two different activities for GM and MF anyway?

In the past, c:geo had two implementations using the same framework (`CGeoMap`), for Google Maps v1 and Mapsforge v3.

Then @rsudev (and @pstorch?) started refactoring/modernizing things and created `NewMap`, which used a much more recent (but partly incompatible) version of the Mapsforge library. This was intended to be the common successor for both Google Maps and the old Mapsforge implementation.

In parallel, someone started working on upgrading Google Maps v1 to v2, but did so using the old `CGeoMap` base.

Then Google discontinued support for Google Maps v1 (IIRC with Android 10), so we had to act quickly, and as nobody had time & knowledge at the time to integrate Google Maps into `NewMap`, we upgraded to Google Maps v2 on the base of `CGeoMap` and integrated `NewMap` as the new Mapsforge implementation (in parallel to the old Mapsforge v3 implementation).

Finally, a few months ago, we discontinued and removed the old Mapsforge library, so `CGeoMap` nowadays only serves for Google Maps v2.

**Comment by fm-sys** [comment]
Still it would be useful if someone has the time and knowledge to merge these two map activities as we have many duplicated code parts in there which are hard to maintain...

**Comment by rsudev** [comment]
From what I see in the callstack I would deduce, that first Settings.getMapProvider returned the GoogleMapProvider, leading to the calling of GoogleMapActivity.onCreate() later than the same call has to return the MapsforgeMapProvider, leading to inflation of the mapsforge layout in line 570 and thus returning the MapsforgeMapview in line 591.
As there were recent changes in the map source area: Any idea what might trigger such a switch?

**Comment by rsudev** [comment]
Regarding the merge: I would start such a venture, but as far as I can see I would need to supply a credit card for my google developer account in order to get a v2 API key, something I am reluctant to do...

**Comment by Lineflyer** [comment]
> As there were recent changes in the map source area: Any idea what might trigger such a switch?

My amateur guess:
After upgrading to the version which is affected all users of oflinemaps will revert back to GMaps (known issue due to another change). Can this cause it?

**Comment by moving-bits** [comment]
> > As there were recent changes in the map source area: Any idea what might trigger such a switch?
> 
> My amateur guess:
> After upgrading to the version which is affected all users of oflinemaps will revert back to GMaps (known issue due to another change). Can this cause it?

This was my guess as well, therefore my initial question to @eddiemuc.
(AFAICS #9619 has a different cause than the linked #8941 as it does not happen in unparcelling a state object as in #8941, but on retrieving an casting a map view.)

I'll hardcode GoogleMapsProvider in `CGeoMap` for now as mitigation.

**Comment by moving-bits** [comment]
> Regarding the merge: I would start such a venture, 

That would be great!

> but as far as I can see I would need to supply a credit card for my google developer account in order to get a v2 API key, something I am reluctant to do...

IIRC Google pushes you to supply a credit card, but does not enforce it. At least that was the case when I updated the keys to v2. - Can't you skip the "enter CC info" part?
