### ISSUE TITLE
Use Chrome Webview also for "Open Geochecker"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9621]
I checked the Chrome Webview, which is now used for all places where I expected it (e.g. user profile, user message, etc.) but one seems missing:
"Open Geochecker" in cache details menu for caches, where we detected a link to a known geochecker, still uses the "old" method although the "Chrome Webview" option is activated in Settings.

**Comment by fm-sys** [comment]
That was explicitly designed that way, as "open geochecker" should open a geochecker app if it is installed. But you are right, that it's kind of inconsistent...

**Comment by Lineflyer** [comment]
> pen a geochecker app

**Comment by fm-sys** [comment]
https://play.google.com/store/apps/details?id=com.jokus.geochecker as an example...

**Comment by Lineflyer** [comment]
Interesting, didn't know that.
In such case its IMHO better to keep our function like it is and do not introduce Chrome Webview for it.
