### ISSUE TITLE
Keyword search not working if Emojis involved

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9622]
Beta feedback but probably no new problem:
- Open GC8M7NA
- Copy cache title via long click on it
- Go to Main Menu - Search - Search by keyword
- Paste the cache title

Result:
No result returned

Expected result:
GC8M7NA returned

Version:
2020.12.22-RC
2020.12.29-NB

Remark:
- The mentioned geocode is only an example. According to users it happens for other caches containing such kind of special characters.
- Not checked if it is a c:geo problem (unicode encoding?) or a gc.com problem

**Comment by Lineflyer** [comment]
Additional comment from a user:
- Search for keyword and insert any emoji (e.g. a normal smiley)

Result:
- GC.com: Exactly 4 GC-caches (seems always the same) are returned
- OC.de: Seemingly unrelated results are returned (might or might not contain the searched emoji, but contain some emoji)

**Comment by fm-sys** [comment]
With the new filter framework it is working fine...

![Screenshot_20210806_215247_cgeo geocaching](https://user-images.githubusercontent.com/64581222/128564657-33e6c221-2f8e-402f-9d64-d3d217a97813.png)
