### ISSUE TITLE
Copied parking waypoints not shown on map

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9627]
**Describe the bug:**
Out of two parking places only one is shown and that toggled

**To Reproduce:**
1) Store GC8GRHE (# 5) and GC7R2BQ (# 1)
2) Add a final WP to # 5
2) Copy the first parking place from # 1 to clipboard and paste to # 5
3) Copy the second parking place from # 1 to clipboard and paste to # 5
4) Show WP list of # 5 on map

**Actual behavior/state after performing these steps:**
Only one WP is shown. If I click on it  and use the back key the other one is shown. Sometimes both are displayed but only one can be clicked.

**Expected behavior/state after performing these steps:**
Both points should be shown and be clickable (As it is when i do the same with the original cache # 1

**Version of c:geo used:**
2020.12.24-NB-a2423d5

**Is the problem reproducible:**
Yes / No

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

![IMG_20201230_000911](https://user-images.githubusercontent.com/43813636/103320470-c85a1100-4a35-11eb-8f29-2d80a899c06a.jpg)
![IMG_20201230_002552](https://user-images.githubusercontent.com/43813636/103320509-e9bafd00-4a35-11eb-9b51-abcdf902bb9c.jpg)

**Comment by moving-bits** [comment]
May be fixed with #13395, which is part of our next feature release (probably to be released in a couple of days).

**Comment by moving-bits** [comment]
@geocachermgo 
Could you cross-test whether your scenario still happens after the fix provided with our release 2022.10.17?

**Comment by geocachermgo** [comment]
Seems to be fixed. I tested some copying but could not reproduce it any more with 2022.10.18-NB-ed92127

**Comment by moving-bits** [comment]
Thanks for cross-checking. Let's close here then. If anything new should arrive, feel free to open a new issue.

**Comment by geocachermgo** [comment]
Thanks for fixing!
