### ISSUE TITLE
OKAPI client test against opencaching.us failing

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9630]
All builds throughout the last days failed at least due to the `cgeo.geocaching.connector.oc.OkapiClientTest.testGetOCCache` failing.

I've debugged a bit into this and the connection to the opencaching.us server throws a `RuntimeException`: `javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Opencaching.us has a new certificate, validity starting Dec. 27th.

Using Firefox connection to the server is working, and displaying the certificate mentions no issues.
Also, retrieving the cache data using their OKAPI API in the browser does work without problems.

Doing a certificate test using https://www.digicert.com/help/ with opencaching.us domain is mostly ok, but presents one error:

```
TLS Certificate is not trusted

The certificate is not signed by a trusted authority (checking against Mozilla's root store).
If you bought the certificate from a trusted authority, you probably just need to install one
or more Intermediate certificates. Contact your certificate provider for assistance doing
this for your server platform.
```
(although it's working in Firefox)

Is there anything we can do from our side?

**Comment by fm-sys** [comment]
Maybe we can mark this certificate as trusted inside c:geo... 🤔

Or can we report this to the OKAPI developers that they are taking care of it?

**Comment by Lineflyer** [comment]
> Maybe we can mark this certificate as trusted inside c:geo... 🤔

We do not really know if its trustworthy, do we?

I will try to contact OCNA

**Comment by rsudev** [comment]
It is signed by let's encrypt and therefore accepted by all modern browsers. Might be an issue with the emulator (modern Android versions should accept let's encrypt out of the box as well)

**Comment by moving-bits** [comment]
> Might be an issue with the emulator (modern Android versions should accept let's encrypt out of the box as well)

I thought so, but at least my API 30 emulator does not, and the old API 23 we use on CI doesn't either - that's why tests on CI break.

**Comment by rsudev** [comment]
On my real device there are no issues accessing oc.us. So it is seemingly an issue with the trusted root certificates of the emulators.

**Comment by moving-bits** [comment]
Then a possible solution could be to either switch the test to a different OKAPI site (I will test that), or to install the certificate needed for opencaching.us on the CI.

**Comment by Lineflyer** [comment]
I remember somehow, that I read something about LetsEncrypt (and others) currently trying to mitigate a trust chain problem which would block out some older mobile devices. I can't remember the outcome though.

**Comment by Narrat** [comment]
> I remember somehow, that I read something about LetsEncrypt (and others) currently trying to mitigate a trust chain problem which would block out some older mobile devices. I can't remember the outcome though.

Let's Encrypt changed/adjusted their plan to avoid the issue with Androids <7.1.x.
https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

**Comment by Lineflyer** [comment]
Lets keep this open to investigate.

**Comment by moving-bits** [comment]
CI builds are back to green, as long as they are based on a state including the updated test (#9635)

**Comment by andrixnet** [comment]
I am hosting server admin for the following: 
- opencaching.ro
- opencaching.us
- opencaching.nl (helping Harrie Klomp)

Please also contact me directly if there are any issues that might have to do with these OC sites and potentially server-side problems. Due to work overload I haven't kept myself up to date with github lately, sorry. 

I will investigate the matter server-side and get back to you.

**Comment by moving-bits** [comment]
@Lineflyer 
Would it make sense to create a Wiki page which lists our contacts for the different services we support?

**Comment by andrixnet** [comment]
There might have been an inconsistency on server config. There are several virtualhosts configured, each running over https using letsencrypt certificates. Due to a misconfiguration they were all pointing to a single letsencrypt_ca file (symlink to chain.pem from one of the certificates). In fall 2020 Letsencrypt changed their CA. It is possible that for a number of days several virtualhost rand with the right certificate but the wrong (letsencrypt but non-matching) CA.

I have since corrected this problem in the configs. 

I tested with https://www.digicert.com/help/ just now and it reports all green.

**Comment by moving-bits** [comment]
@andrixnet 
Thanks for looking into that issue. Fix is confirmed - when I revert the OKAPI client test to use `OU0331`, the cache can now be retrieved successfully again.

**Comment by Lineflyer** [comment]
@moving-bits 
Shouldn't we revert to the OU cache then to have it covered in unit tests or did we see the issue also in our website tests (so OU is covered whether its working)?

**Comment by moving-bits** [comment]
> Shouldn't we revert to the OU cache then to have it covered in unit tests or did we see the issue also in our website tests (so OU is covered whether its working)?

done with #9694

**Comment by andrixnet** [comment]
@moving-bits: considering GDPR such information should either be rather generic or not entirely publicly accessible ...

**Comment by Lineflyer** [comment]
> such information

what information?

**Comment by bekuno** [comment]
The cache self is public accessible.
Therefore also the owner name, ...
But this is no real name, so not covered by GDPR, imho.

**Comment by andrixnet** [comment]
> Would it make sense to create a Wiki page which lists our contacts for the different services we support?

OC site admins contact info

**Comment by Lineflyer** [comment]
It is stored in our internal area only, not publicly accesible.

**Comment by andrixnet** [comment]
@lineflyer please contact me directly then for details

**Comment by Lineflyer** [comment]
@andrixnet I think Github does not provide a PN function. Just drop a mail to support@cgeo.org
