### ISSUE TITLE
Store service-specific log id on PQ / GPX import

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9639]
_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/9524#issuecomment-752952048_

> In the database we have a field `service_log_id`, but that seems to be filled rarely. (Maybe only on direct download of caches via c:geo, not when using PQ/GPX files

Indeed service_log_id is currently filled only on direct download, but it should be filled for all downloads done after last release (where it was introduced). This is is service-specific and implemented for gc.com, oc and some other service. I added this field to enable direct links to log entries on website (can't remember issue id).

I guess it could be filled for GPX imports as well if the contain the service-specifc log ids

**Comment by moving-bits** [comment]
Checklist (not necessarily complete):

- [ ] check if "id" in PQ GPX file equals the log id we store on directly downloading logs
- [ ] check if other services offer GPX download, and if, whether that includes a fixed id
- [ ] check how to securely identify "id" in GPX files to not confuse it with GPX files created by other standard means

**Comment by fm-sys** [comment]
BTW: We have a bug, that if you refresh a cache in c:geo and import a pocket query afterwards you have duplicated log entries. So we should either compare the log_id (if possible) or adopt the merge magic so that they are recognized as duplicate...

I will assign this to me to have it on my (already way too long) to-do list. If somebody wants to start in between, feel free!

**Comment by fm-sys** [comment]
## GPX
log id: 1026252390
Timestamp: 1623541427000
human-readable date (GMT): Saturday, 12. June 2021 23:43:47
In fact, I received the log notification mail at `Saturday, 12. June 2021 16:43` so the timestamp in the GPX seem to be server time or any other timezone...?


## DB
log id: GL14VN69Q
Timestamp: 1623456000000
human-readable date (GMT): Saturday, 12. June 2021 00:00:00

Therefore, our merge logic...
```
DELETE FROM " + dbTableLogs + " WHERE geocode = ? AND date = ? AND type = ? AND author = ?"
```
(#9637) is not working, which results in duplicated log entries. This should be fixed...

---

But for the original request: The log_id is identical (just represented in a different format, but can be converted via `GCUtils.logIdToLogCode`).

**Comment by fm-sys** [comment]
PR will follow... Should those two fixes be targeted to `release`?

**Comment by moving-bits** [comment]
> Should those two fixes be targeted to `release`?

Can be done, but is not a must have for `release` IMHO, as the underlying request which lead to this issue are not recent.

**Comment by fm-sys** [comment]
Ok, as it deals with (although uncritical) database changes let's merge to master and we are on the safe side ;-)
