### ISSUE TITLE
Allow more than one offline log for the same cache

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#9640]
Here is the scenario:
I am a cache owner. At some point I receive a "needs maintenance" notification. Typically I would process that at home at a Laptop or PC, the action would be to log a "disabled" log for the respective cache, let's call that cache "GCxyz1" for now. I do this directly using GC.com's UI.

A few days later, after getting required parts together I go out on a tour to fix GCxyz1. I have an offline copy of the listing on cgeo and use cgeo to navigate me to that cache. It is shown greyed out on the map because it is in disabled state.

I fix that cache and then I do a quick offline log "owner maintenance provided" for GCxyz1. But I also need to log a "Enabled" for GCxyz1. If I try to accomplish this with cgeo quick offline log, "Enabled", then no new log entry for GCxyz1 is being created. Instead, the one that already existed is modified. Essentially the "owner maintenance provided" log is gone. If I exported the field notes, I would get one record with log type "Enabled".

In order to model the true workflow of a geocache, at least for a geocache owner, it must be possible to create more than one offline log for the same geocache. The resulting field notes file (and the records being uploaded to GC.com), must contain two records for the scenario outlined above and not just one capturing the last log type entered.

**Comment by Lineflyer** [comment]
Did you ever try (via other means) upload a field note file with more than one offline log for the same cache? Just to make sure it would work on server side.

**Comment by baiti** [comment]
> Did you ever try (via other means) upload a field note file with more than one offline log for the same cache? Just to make sure it would work on server side.

Good Point! I haven't done so but will do right away .... stay tuned, that will be interesting.

**Comment by baiti** [comment]
Here is the sequence:

- Cleared all drafts on GC.com
- Edited the field notes file throwing away all records except one.
- Duplicated that single line in the file and changed the Log type from "Found it" to "Write note".
- Uploaded the two-record field notes file to GC.com

![Screenshot from 2020-12-31 18-32-05](https://user-images.githubusercontent.com/5296333/103420318-e2f7cb80-4b96-11eb-86e9-2b2d2a7f100b.png)

For completeness, the input file looks like this:

$ cat field_notes.txt 
��GC8KZZN,2020-08-02T12:04:08Z,Found it,""
GC8KZZN,2020-08-02T12:04:08Z,Write note,""

The first two characters originate from the Big-endian UTF-16 Unicode text as every other encoding is rejected by GC.com

**Comment by MagpieFourtyTwo** [comment]
> Did you ever try (via other means) upload a field note file with more than one offline log for the same cache?

There's no collision for sure, as this even works with the very same field note.
If you upload it twice, on gc.com there will be two for the same cache with the same type.

**Comment by MagpieFourtyTwo** [comment]
Nevertheless, I don't really see the need for more than one Offline Log per cache, as even as Owner you can simply post a) an "Owner Maintenance", containing valuable info, if needed, which is b) simply followed by an empty "Enabled" log.

Otherwise the menu entry ``Log visit`` will most probably create a new field note on every call, instead of opening the existing log for edit, as usual - and I'm afraid this will lead to a lot of double field notes or even logs, i. e. "Found" and "Write Note" ...

**Comment by andrixnet** [comment]
I encountered a simila problem using exclusively c:geo:
- open a cache
- add offline log (whatever, let's say found it)
- attempt to add another offline log (let's say a write note). The recorded offline log type has changed to that of the last selection. 

Using exclusively c:geo, I go to lists, filter by personal data - with offline log, when I have the time to write my logs, I start editing and posting each such log. 
Not using "field notes" to upload to geocaching.com website. 

In the example above perhaps I wanted to add some information about the cache in the write note, or mark a needs maintenance, besides the find. The simple act of adding a single "offline log" does not allow such multiple actions and unless I record my intentions elsewhere, being too busy in the field to type multiple texts, I might forget about it altogether. 

This usage context shows a real need for multiple offline logs.

Thank you.

**Comment by MagpieFourtyTwo** [comment]
> or mark a needs maintenance

You know the ``Report Problem`` drop down below the log text window?

**Comment by Lineflyer** [comment]
@baiti 
> The first two characters originate from the Big-endian UTF-16 Unicode text as every other encoding is rejected by GC.com

I stumbled upon your comment as we recently changed our field note export to return UTF16-LE files due to #7404 
But in fact you are right. the UTF16-LE are not accepted on manual upload but upload fine with c:geo. I think we have to look into it once again. Will open a dedicated issue for that.

**Comment by andrixnet** [comment]
@MagpieFourtyTwo "Needs Maintenance" log type has additional consequences. I know about it. Unfortunately it is IMO it works in a less desirable way: 
why pollute the "found" log with the information describing the problem and then have an additional totally generic "you cache has a problem" log entry ... Why not show another text field to describe the problem and that text become the NM log ? (this might be the topic of another issue, maybe)

**Comment by MagpieFourtyTwo** [comment]
Totally agreed, I don't like this mechanism, neither, but this is the way, gc,com has integrated it in it's dialog, so complaints should go there. As for me: I usually write the need for maintenance into either a separate log, too, or, esp. for dinos, in the normal log text (as ``Needs maintenance`` logs just draw the attention of this "wonderful" Health Score Script to the cache :/)

**Comment by MagpieFourtyTwo** [comment]
Nevertheless, I would consider the situations, where one may need more than one log for a single cache, as too rare as it would pay out to confuse the standard cacher ...

**Comment by baiti** [comment]
I have to pick this up again and I must say, I disagree with the position that this situation is "too rare" in the sense that it wouldn't be worthwhile to add the missing funcitonality to cgeo.

I go on a tour, I never do direct online logs, only offline logs. I want all my offline logs promoted to gc.com via fieldnotes export in sequence. It occurs quite frequently that I find a cache, can write into the logbook, and it just so happens that the logbook is full. So I want to log a regular found it log, offline, such that it goes into the history list, which is subject to be uploaded later, then I want to log a needs maintenance for that very same cache and I want both log entries in the history and in the fieldnotes for that sake.

I do NOT want to circumvent the missing function by uploading field notes after the found it, clearing history, logging a NM into fresh fieldnotes. I do one fieldnote set per tour and I store that in a safe place, together with the recorded track.gpx for that tour. This is my concept of documentation, a tour diary so to speak. (I have tooling to visualize and work with those tours based on this data but that is outside of the scope of this issue).

I am deeply convinced that this is a standard scenario and there is nothing obscure about it. I am actually surprised that nobody else runs into this scenario. Perhaps many do and just don't report feature requests nor bugs.

**Comment by rsudev** [comment]
I could think of a relatively non-intrusive way of integrating this functionality. If there is already an offline-log stored for a cache, add a new menu entry (besides the ones allowing to change the type or edit the log) 'new offline log' (or similar) which allows you to store a new one. Of course, this would likely have far-reaching consequences internally, as there are many places in c:geo only expecting one offline log (log date, log editing, ...)

**Comment by baiti** [comment]
I have to say, I haven't thought of any consequences it might have with respect to implementation. It is rarely a simple task to add functionality "on the side", when the initial design of an application didn't have this use case on the table. So from that perspective, I'd actually be ok if we said, well, the use case is understood and it is valid but we can't integrate it into the current design of the application. However, every now and then major refactorings, re-designs show up in the life of an application and then it would be a good time to revisit the scenario of offline logging caches. Do we have a list of topics to be considered for a re-design, refactoring of the app? Could we add this to that list?

**Comment by baiti** [comment]
Just as a comment: It is due to the lack of the described functionality, that I don't do any `needs maintenacne` or `needs archived` logs at all. It just doesn't fit into my tools supported workflow, as sad as that might be for the cache owners who trigger their maintenance activtities to the reception of NM  / NA logs. I for instance, have received close to 100,000 logs and I don't have the time to read them all. So I have setup a notification system to alert me of incoming NM / NA logs.

**Comment by baiti** [comment]
Since it is absolutely quiet here, is it safe to assume that nobody needs this capability? Or is it rather such that users don't read the issue database an also there is no upvote on feature requests? If I'd conclude that only developers participate here, none of the developers / testers need that functionality?

So, if I gave it a try and implemented it, not sure whether I can accomplish this but assume I can, would you guys consider merging it?

**Comment by fm-sys** [comment]
> Or is it rather such that users don't read the issue database an also there is no upvote on feature requests? 

Every github user has the permission to vote on every issue. However, probably nobody who isn't actively participating will have the time to read through all issues. 

> If I'd conclude that only developers participate here, none of the developers / testers need that functionality?

Yes, seems like.

> So, if I gave it a try and implemented it, not sure whether I can accomplish this but assume I can, would you guys consider merging it?

It depends on how it is implemented. New features shouldn't decrease the efficiency of primary user workflows. If users will need more clicks than before to achieve the same thing, it can be considered not straightforward enough.

**Comment by MagpieFourtyTwo** [comment]
Admittedly, I have wished for the ability to save multiple log(type)s at once, too, but that was maybe two or three times.
In about 10 years of using c:geo with several thousand logs, during which I haven't given it a single thought.

IOW: Plse don't get me wrong, but IMHO there are a lot of way more important things to do (resp. to fix) ... :)

**Comment by baiti** [comment]
I have changed my habits such that I either log a Found it or a DNF but never anything else on top. No "Found it + NM", no "DNF + NA", so given that, logging one entry per GC-code per tour works for me. It is not ideal for the respective cache owner but so it is.

**Comment by SammysHP** [comment]
You can't log individual NM or NA anyway nowadays. You post a note or other log type with a cache status flag.

**Comment by baiti** [comment]
that is new news to me. I believe I can post a standalone NM oder a standalone NA via the API. Haven't tried though in a while. Will go and verify and post a reply here, just for completeness, not because I want to push cgeo to support multiple offline logs. I have given up on that workflow.

**Comment by MagpieFourtyTwo** [comment]
@baiti 
> I have changed my habits such that I either log a Found it or a DNF

Maybe, but for this issue kind of irrelevant. ;)
Initially this issue was about Owner's wish to be able to post ``Owner Maintenance`` *plus* an ``Enable Listing``.

@SammysHP 

> You can't log individual NM or NA anyway nowadays

You can still even post a plain and manually filled NM and NA (which is pretty good, as the automatically generated NM and NA logs are pretty senseless anyway, cause they do not carry any info other than "Hey guy, please have a closer look at my log"), if you use [the old log form](https://www.geocaching.com/seek/log.aspx?ID=939015&lcn=1) (which I prefer anyway - and thanks to GC little Helper using it is pretty straight forward).

And WRT the API (at least docs): Although for [GeocacheLog](https://api.groundspeak.com/documentation#geocache-log) the ``Log type`` is marked as deprecated, it is at least still [well defined](https://api.groundspeak.com/documentation#geocache-log-types).

However, TMALSS: This function would IMHO mainly (or even only?) be useful for cache owners, therefore it can perhaps be implemented in a way that the possibility for a second log (type) pops up ...

- for own caches only ...
- and if a first already exists ...
- with e. g. a second menu entry, i. e. like ``Log Visit (second type)`` besides the already existing ``Log Visit``
  which of course does just appear if the fist two criteria are given?

Just an idea ... although me personally would not really need this func anyway.  ;)

**Comment by Lineflyer** [comment]
I do also vote for "close without implementing". Any types of doubled offline logs are rare encounter anyway. Also meanwhile c:geo does save the selection of maintenance need below the log text with the offline log. So your NM / NA won't get lost if you later log online via c:geo by reaccessing the offline log.
For owner log its also kind of rare needing to log owner specific log types offline (as you probably want to enable the cache online asap anyway).

**Comment by baiti** [comment]
> I do also vote for "close without implementing". Any types of doubled offline logs are rare encounter anyway. Also meanwhile c:geo does save the selection of maintenance need below the log text with the offline log. So your NM / NA won't get lost if you later log online via c:geo by reaccessing the offline log. For owner log its also kind of rare needing to log owner specific log types offline (as you probably want to enable the cache online asap anyway).

I never log with a smartphone no matter what tool. I upload the offline logs to a place where I have a real keyboard and screen.
But never mind, let's close it if I am the one and only geocacher on the planet who has such a strange workflow.

**Comment by baiti** [comment]
Even though I closed the issue by now and I am ok with it, I still believe there is some  very big missunterstanding of the workflow at stake here.

First of all, it is still possible to directly log an NM or a NA as a standalone offline log in cgeo. Also, once these offline logs are uploaded as "Draft logs", I can work on the on the geocaching.com website as always and as expected.

Chaining an NM or even add a TB to a log, or an image, **with cgeo** only works if the resulting log is directly sent from cgeo as a sequence of events to the geocaching,com website. It is not possible for instance, to create an offline log with cgeo and attach an image to it or reference a TB to be discovered togetther with that log.

In order to appreciate this issue here, you need to thoroughly understand the concept of offline logging. Offline logs go to a "field notes" record and if the history is cleared before a tour and once all caches on an tour are offlne logged to the "field notes" records, then that record is either (a) exported to the local filesystem, and (b) optionally uploaded as draft logs to geocaching.com AND, the fieldnotes record can be transferred to another Android APP via sharing intent. It is imposible today to log the same GC code twice into a single field notes record and that is without any doubt a lack of functionality, a deficiency that should not be there. I can live with the position that there is bigger fish to fry but it is a deficiency that should not be there. There is absolutely nothing wrong on a tour, to first log a write note to a GC code and a few minutes later log a Found it to the same GC code and both logs should be stuffed into the fieldnotes record and it should be possible to upload these as draft logs go geocaching.com. The same is true with other log types. In fact, it doesn't matter what the log  type is. I can even log 5 write note in a row for the same GC-code and I want all 5 be part of the field notes record that I can upload to the draft logs on geocaching.com in ONE batch. This is a standard workflow for me and quite a few others who I go caching with except that tey are not programmers and don't post issues here nor comment on issues others write up.

**Comment by MagpieFourtyTwo** [comment]
It may sound surprising to you, but if I got you right, I have a very similar workflow:
1. on site I do an offline log, which mainly contains some keywords, a) to remember the story
   and/or b) the condition of the cache, if there is s/th which should be communicated
2. after the tour:
   - if the number of caches is "manageable":  ;)
      1. upload offline logs (aka fieldnotes) to gc.com
      2. log them via draft list, using gc.com's (old) log form, by formulating the catchwords into a continuous text
      3. and if the draft contains s/th WRT the cache state, this will usually be mentioned at the end of the log text;
          unless it's "more extreme" - and only then there *may* follow a WN, NM or (very seldom) a NA,
          which mainly depends on cache quality, age and/or last login date of the owner,
          cause I do not want to draw the Health Script's attention to dinos or HQ caches,
          which are no longer maintained by the owner, but only by community.
   - if it was a "Power Tour"
      1. export offline logs to fieldnotes.txt and "Fetch" it into GSAK
      2. apply a tour specific template and adapt "special" caches
      3. log them via GSAK's "Publish Logs"

Easy to see that despite a presumably very similar workflow, there's nevertheless no need (for me) for an additional offline logged WN or such, since I re-read and revise my drafts anyway.

Thus, the only scenario where an additional log *could* be helpful, is after a "Power Tour" - to find the "critical" entries more easily. But since c:geo now even includes a filter for ``offline log contains <search text>``, I can find these easy enough already - and then adjust the appropriate logs (even in GSAK) before publish.

This of course doesn't mean that this is the only "good" way, it should just show how I integrate it in my workflow, with in fact no effort at all (I would say).

YMMV.  ;)

**Comment by MagpieFourtyTwo** [comment]
> I want to make sure I submit all logs exactly in the time sequence they really happened out in the field but now I have to insert and additional log (the NM) into the sequence manually and artificially construct a date that fits it into the sequence.

Just another 2 Cent: If you do it like me, i. e. export the fieldnotes.txt from c:geo and then import (resp. [Fetch]) it directly into GSAK (from file), you can perhaps simplify the process of inserting a properly timed NM by just editing the fieldnotes.txt *before* you import it to GSAK. Although GSAK offers the possibility to clone (and adapt) entries, it's IMO way more easy to use a text editor to insert e. g. an NM prior to import: Just copy the appropriate log's first line, change the type, increase the timestamp by one second and, if it was a multi-line offline log, add a closing double quote at the end of the line, and you're done.

**Comment by MagpieFourtyTwo** [comment]
An own share intent sounds really good - and if you have one anyway, why not just implement a trigger, which adds a NM or whatever additional log entry, if if stumbles upon a special keyword ... like put a #NM# into the offline log which then automatically does what I described for the manual text editor procedure ...  ;)

**Comment by baiti** [comment]
> An own share intent sounds really good - and if you have one anyway, why not just implement a trigger, which adds a NM or whatever additional log entry, if it stumbles upon a special keyword ... like put a #NM# into the offline log which then automatically does what I described for the manual text editor procedure ... ;)

Sure, could be done. Just SMOPs (Small Matter Of Programming). And I might in fact go ahead and just do it exactly that way. So the discussion had some benefits after all. Thanks much for helping to shape that thought,
