### ISSUE TITLE
Wizard: On pages with additional buttons "Next" should be "Skip"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9650]
I presented the installation wizard today to a user which did not use c:geo before (muggel). Beside some wording proposals (which will come as seperate PR) he provided the following feedback:

In the screens "Configure platforms" and "Advanced configuration" the button "Next" is misleading. It was not clear to me whether I have to use the above dedicated buttons or simply press "Next". It should be named "Skip" as it in fact skips the real setup.

**Comment by moving-bits** [comment]
Agreed in this use case.

But what about if the user has used one of the buttons? A "skip" could be interpreted as the setting configured by pressing one of the above buttons on that page should be discarded. - So maybe we need "skip" as default setting on such pages, being changed to "next" if any of the config buttons on such a page has been used?

**Comment by Lineflyer** [comment]
> being changed to "next" if any of the config buttons on such a page has been used?

Or to "Done" if the buttons have been used.

**Comment by fm-sys** [comment]
> > being changed to "next" if any of the config buttons on such a page has been used?
> 
> Or to "Done" if the buttons have been used.

Or directly step to the next screen. Am I right, that the old screen is not useful for the user anymore, if he had configured the services?

**Comment by moving-bits** [comment]
> > Or to "Done" if the buttons have been used.
> 
> Or directly step to the next screen. Am I right, that the old screen is not useful for the user anymore, if he had configured the services?

You need to stay on the page as you can configure several services (geocaching services page) / configure several things (advanced page).

**Comment by fm-sys** [comment]
> You need to stay on the page as you can configure several services (geocaching services page) / configure several things (advanced page).
 
Ok, sorry. I hadn't checked how the installation wizard currently looks like...
