### ISSUE TITLE
Extremcaching.com API not available once again

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9652]
This issue is FYI only:
Users made me aware the c:geo is currently unable to login to extremcaching.com.
The reason is pretty much obvious: They again forget to in time prolong the servers SSL certificate. It ran out on 31.12.2020.

Just wondering why our website tests did not complain this time.

**Comment by geocachermgo** [comment]
53 users are logged in at EC at the moment

**Comment by Lineflyer** [comment]
> 53 users are logged in at EC at the moment

Where do you see that?

I tried to send a mail via the web form to the admin, but the Captcha check seems to be broken (or I am totally unable to recognize the letters from the picture, which I doubt).
I will try to look up the contact information I have on file somewhere and contact them via mail.

**Comment by geocachermgo** [comment]
That was from our status page: https://www.cgeo.org/status.
I just wanted to check, how many c:geo users have an EC connector (5, 50, 500 or more)

**Comment by Lineflyer** [comment]
ah, ok. I was wondering how they could be logged in after all. The count only provides the amount of users which have activated the connector....so it rather means 53 users try to login but fail :(

**Comment by Lineflyer** [comment]
Certificate was renewed some days after expiry.
Given that only a minor percentage is using this service and its still somehow maintained I think we should keep it included in c:geo,

Also unavailability of ec.com while its active connector in c:geo seems not to block or slow down any operation.
