### ISSUE TITLE
Wrong image size, adding image from gallery to log

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#9655]
**Describe the bug:**
I discovered the problem some time ago, but only got to reporting it now. 
It is tricky that it does not appear on multiple devices.

**To Reproduce:**
1. Write a log to a cache.
2. Click on add image from gallery
![btn-3](https://user-images.githubusercontent.com/3382777/103480395-c2b94e00-4ddc-11eb-86cb-237f92d330c5.png)
3. select an image. (ie one recently taken with the camera; but using gallery)

**Actual behavior/state after performing these steps:**
The image is attached with an odd size: 4x3 pixels. 
![img-1](https://user-images.githubusercontent.com/3382777/103480470-46733a80-4ddd-11eb-91c0-c7473d7373f0.png)

This happens **_ONLY_** when using the add image from gallery button. 
This does not happen if I use menu->attach image.

**Expected behavior/state after performing these steps:**
The image should either be rescaled according to some geocaching.com rules or loaded as is. 

**Additional context:**
Importantly oddities: 

I was unable to reproduce the behaviour on another device (S9+, Android 10, c:geo 2020.12.03) with a premium account user. However taking into consideration those describe below, the problem may have an always until X nature.

While doing additional tests for doing this bug report I discovered the following: 
Since this feature has appeared, I used it directly. During additional tests, I used again menu->attach image and I noticed a dropdown there about scaling. It was set "no scaling". 
I changed that dropdown to one of the presets. After that, the "attach image from gallery" button and "attach image from camera" button began to yield proper functionality, though I am not sure according to what rules. 
E.g. after a device reboot, "attach image" button yielded what appear to be a rescale to 1024 preset, while menu->attach image scaling dropdown defaulted to "no scaling". 

Perhaps there should be a sensible default in c:geo settings, under logging section, to be used as reference, and only menu->attach image to allow different scaling since it is a more advanced dialog.

**Version of c:geo used:**
2020.12.03

**Is the problem reproducible:**
Yes - under context described, until performing at least once: menu-attach image and scale to preset size.

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
--- System information ---
Device: SM-G965F (star2ltexx, samsung)
Android version: 9
Android build: PPR1.180610.011.G965FXXS7CSK4
c:geo version: 2020.12.03
Google Play services: enabled - 20.47.13 (100400-344095733)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found disabled archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (189.8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (189.7 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (189.7 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (6.4 MB) on user storage
GPX import path: /storage/emulated/0/gpx
GPX export path: /storage/emulated/0/gpx
Offline maps path: /storage/emulated/0/maps/mapsforge
Map render theme path:
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: yyyy-MM-dd
Installed c:geo plugins: none
BRouter connection available: true
--- End of system information ---
```

**Comment by geocachermgo** [comment]
The image is reduced to your last setting and canot be increased afterwards (see #9204 and connected issues).

**Comment by eddiemuc** [comment]
@andrixnet I assume the original image is NOT 4 x 3 px in size? 

The behaviour when using the "add from gallery" button should be that the image is scaled to the last setting done via the "Menu -> Attach Image" entry OR a default value (I think it was 1024) when nothing is set there. From what you describe my first guess would be that there is a bug in determining the actual scale value, maybe a scale value of 0 is used by error in your case and it is "reset" to a sensible value when you ise the "Menu -> Attach Image" way.

Is this related to a specific image? If yes, are you able to share this image for testing (in its original state)?

And is it just the display being wrong or is the image in question really scaled down to this absurd size 4x3px?

**Comment by IiroP** [comment]
I think I was able to reproduce the issue with OnePlus 5T (Android 10) with cgeo 2020.12.22-RC. I tried to follow these steps, image ended being even smaller (1x1 px). It's not just the display, the file saved in Pictures/cgeo is only 1x1 px.

```
--- System information ---
Device: ONEPLUS A5010 (OnePlus5T, OnePlus)
Android version: 10
Android build: ONEPLUS A5010_43_201029
c:geo version: 2020.12.22-RC
Google Play services: disabled - 20.45.16 (120400-344294571)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_FI / user-defined language: 
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (15,5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (15,4 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (15,4 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (3,6 MB) on system internal storage
Last backup: never
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/mfmaps
Map render theme path: /storage/emulated/0/Locus/mapsVector/_themes/peruskartta/Peruskartta.xml
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: d.M.yyyy
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---
```

**Comment by eddiemuc** [comment]
I will provide a fix

**Comment by eddiemuc** [comment]
Bug happens when there are legacy values for log image scale stored in settings. Those were indices of possible scale values (range 0-4 or something around that) but are falsely interpreted as target scale size in pixels.

PR #9681 should fix this

**Comment by andrixnet** [comment]
@eddiemuc I have intermitently used the resize option in the menu->attach image or no resize. This through at least 2 years of usage and all update history along the way. 
And yes, my images in the gallery were not 4x3, but proper sizes (according to what the camera shot or my edits yielded.)

**Comment by eddiemuc** [comment]
@andrixnet the PR changed the scale size to never be lower than 512, regardless of the stored settings. I hope it fixes your problem. Du you have a chance to test it with a nightly?

**Comment by andrixnet** [comment]
I'll try tomorrow, if I can get my hands on another device I could use for testing.

**Comment by eddiemuc** [comment]
> I'll try tomorrow, if I can get my hands on another device I could use for testing.

That would be really great, thanks a lot!
