### ISSUE TITLE
Deactivate image buttons "extract waypoints to PN" and "delete extractred waypoints from PN" when they are not useful

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#9656]
**Describe the bug:**
Recent c:geo introduced several new features. 
One can be seen in the cache screen, below the description.

**To Reproduce:**
1. open a cache
2. go to description screen, scroll down
3. under "personal note" you will see 3 buttons. always.
![btn-4](https://user-images.githubusercontent.com/3382777/103480960-76700d00-4de0-11eb-9f3c-01f1bf0c10b0.png)

**Actual behavior/state after performing these steps:**
4. try to press the indicated button. **Nothing happens.**

**Expected behavior/state after performing these steps:**
From the icon I deduce it might have something to do with some waypoints. Being in this section would mean some waypoints of a different nature then the usual waypoints available on their dedicated screen. 
The trashcan icon in the upper right suggest to me that this button is meant to delete something. 
I presume there would be situations when under Personal note you could see some waypoints. And this button was meant to delete some/all of those waypoints. 

However, since there are no waypoints, there is nothing to delete. 
IMO this button should be shown only when there actually is content for it to act upon.

**Version of c:geo used:**
2020.12.03

**Is the problem reproducible:**
Yes

**Comment by geocachermgo** [comment]
The "long click" gives the meaning: remove waypoint (from cache note).  Since there are no waypoints in the note it locks the same after deletion
![IMG_20210103_155215](https://user-images.githubusercontent.com/43813636/103481537-f21b8b00-4ddb-11eb-92cd-a9a2d6c20425.jpg)
Copied user waypoints look like:
![IMG_20210103_155613](https://user-images.githubusercontent.com/43813636/103481600-4e7eaa80-4ddc-11eb-888a-a4771b6fcf62.jpg)

**Comment by geocachermgo** [comment]
IMHO the button needs not to be greyed out in case of empty note or no {c:geo-start} .. {c:geo-end} section in the note. If we decide to do so, also the sync button should be greyed out in case of no user waypoint present.

**Comment by eddiemuc** [comment]
As @geocachermgo already wrote: currently the buttons are not implemented in a way to activate/deactivate depending on their "usefullness". They are always active, rgardless of whether clicking them will "do something". It is IMHO a valid feature request to ask for them to get activated/deactivated depending on their current "usefullness". I changed the title accordingly.

Implementors note: it is somewhat "expensive" to check whether the delete buttons would do something if clicked: for that the PN needs to be scanned for the {c:geo-x} markers

**Comment by geocachermgo** [comment]
I find it faster to get the info "nothing to delete" / "no user waypoint to sync"  instead of having the buttons deactivated not knowing why.

**Comment by Lineflyer** [comment]
> Implementors note: it is somewhat "expensive" to check whether the delete buttons would do something if clicked: for that the PN needs to be scanned for the {c:geo-x} markers

I would also agree, we should just give an appropriate toast if nothing was done after pressing the button (if not already implemented...not sure at this moment) rather than disabling it.

**Comment by andrixnet** [comment]
Surely long-press is not the most intuitive behaviour. 
IMO either grey out or showing a message on simple click is fine :-)
