### ISSUE TITLE
SAF concept review requested

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9661]
I tried to write down the currently implemented concept with regards to SAF integration into c:geo and how folder selection as well as migration from existing state is supposed to work. You will find this concept here:

https://github.com/cgeo/cgeo/wiki/Disk-Usage-migration-towards-Android-11

I would ask you for a review and feedback to this concept so I can incorporate it into the code.

You can always try out the actual state by installing the nightly of branch `storage_framework`. I try to keep Doku and code in sync.

**Comment by Lineflyer** [comment]
Will do as time permits. Great idea!

**Comment by moving-bits** [comment]
Dito. Thanks for all the programming (and documentation) effort!

**Comment by Lineflyer** [comment]
BTW: I will try to be online again on our IRC channel. While IRC is somehow old-school, it would still be nice to be able to discuss some topics on demand over there. I have reinstalled my Android IRC chat app :)

**Comment by bekuno** [comment]
> I have reinstalled my Android IRC chat app :)

Which app do you use?

**Comment by Lineflyer** [comment]
AndroIRC (not sure if this is still out on Play but works).

**Comment by moving-bits** [comment]
Hi @eddiemuc,

if read your fine document at least twice today, again. Looks really good to me. Thanks for all the effort you put into it and into the SAF framework. I'm really looking forward to see c:geo brought to a new technical level for file handling!

Some tiny questions I have:

folder selection:
- folder selection: why are all folders marked as "persistent"? To my understanding only the base dir is persistent (and maps / map themes, to be able to read from Locus dir), all other locations are just subdirs of the `<base>` dir.
- (Or maybe it's the meaning of "persistent" in this context? My interpretation: "persistent" means we need to persistently store a SAF accessor.)
- folder selection - gpx: is marked also as "configurable" - why? IMHO we decided to fix this as a subdir of `<base>`. - Only a specific user-selected gpx route/track file accessor needs to be persisted, to be able to reload that file for display
- log images: IIRC there was a discussion to change today's location to a `<base>` based solution, e. g. fix this dir (and migrate data) to `<base>/logimages` (or similar)

single file selection:
- same applies for exporting files (GPX cache / cache list export, GPX track export, GPX indiv. route export)
- if log images are listed (which are completely managed internally by c:geo) - wouldn't other system-written files have to be listed as well (eg: logfiles)

persistent folder selection:
- change folder base: What is the default value? I would propose "Move item(s)"
- what does "user-defined" stand for in this context?
- will this function be permanently available in c:geo, so that a user can always change its `<base>` dir? (Would be helpful IMHO)

migration:
- IMHO we should include selecting the base folder include in our new installation wizard and call this wizard automatically on startup if no `<base>` folder is set or `<base>` is not accessible
- This dialog should reappear on every startup until a new `<base>` is set. Otherwise my fear would be that people skip this dialog until it's too late.

**Comment by eddiemuc** [comment]
> Hi @eddiemuc,
> 
> if read your fine document at least twice today, again. Looks really good to me. Thanks for all the effort you put into it and into the SAF framework. I'm really looking forward to see c:geo brought to a new technical level for file handling!

@moving-bits 
Thank a lot for your review and your encouragement! I tried to improve the page according to your feedback and make some things clearer. 
Since my explanation was not good enough at some places: if you have follow-up suggestions now (after I hopefully made these explanations clearer) I am very interested in those of course :-)

> Some tiny questions I have:
> 
> folder selection:
> 
> * folder selection: why are all folders marked as "persistent"? To my understanding only the base dir is persistent (and maps / map themes, to be able to read from Locus dir), all other locations are just subdirs of the `<base>` dir.

"Persistent" in this context means that the folder may have a user-defined URI (selected by the user via a dialog) as well as a "fallback" default location (which most often is <base>/xxx but is also used to provide the legacy folders in case user hasn't migrated yet). Not all folders marked as "persistent" are actually user-selectable via GUI but all of them could be made available easily. I

To clear that up, I changed the description on the page to differentiate between:
* T (transient): folder is selected on-the-fly by user, used for single use case and then forgotten
* D (defaulted): folder has a fixed default value which can not be overridden by user
* U (user-selectable): folder can be freely selected by user, but has a default location as fallback in case the user doesn't do that

> * (Or maybe it's the meaning of "persistent" in this context? My interpretation: "persistent" means we need to persistently store a SAF accessor.)

It's more like: the folder offers the *possibility* to store such a SAF accessor URI

> * folder selection - gpx: is marked also as "configurable" - why? IMHO we decided to fix this as a subdir of `<base>`. 

Folder GPX is user-selectable today in the Settings (there are even two dirs today, one for import and one for export), so I left GPX also user-selectable (but I merged GPX import and export into one dir). Should I change that?

Note: each of the public folders is in principle user-selectable, but not for all of them this is offered in the Settings. This can be changed easily of course.

> * - Only a specific user-selected gpx route/track file accessor needs to be persisted, to be able to reload that file for display

That's a separate thing and listed under "Single File Selection" (where "Track" is marked as "persistent").

> * log images: IIRC there was a discussion to change today's location to a `<base>` based solution, e. g. fix this dir (and migrate data) to `<base>/logimages` (or similar)

Yes, this is discussion state, but I am currently not so sure if this is the best solution. Because this would mean that on each BASE folder change all log images must be forced-copied (or moved). I would like to leave that open for now and continue discussion in issue #9609. Currently my feeling is that it would be better to use the Media folder (and the MediaStore API) for this.

> single file selection:
> 
> * same applies for exporting files (GPX cache / cache list export, GPX track export, GPX indiv. route export)

If you export something there can't be a file selection. We can discuss an export folder selection and entering an export file name of course. But this is not currently implemented. As of today, exports are just written to the respective public folders (mostly GPX) using generated file names. This reproduces the behaviour of c:geo in current release state.

> * if log images are listed (which are completely managed internally by c:geo) - wouldn't other system-written files have to be listed as well (eg: logfiles)

Sorry, I meant only Offline Log Images. Those are treated differently from all the other images in c:geo in that they are stored in a public dir. All other images of c:geo are stored in internal c:geo directory, this includes log images as well as images from cache listings etc. Can't tell you why...

> persistent folder selection:
> 
> * change folder base: What is the default value? I would propose "Move item(s)"

Currently it is "do nothing" (hard-coded) which is pretty neat for all my current testing :-) I added this on wiki page. But we can discuss other defaults of course. 

> * what does "user-defined" stand for in this context?

It means that user MAY (but is not foreced to) select an own directory for this folder using SAF. I added this to WIki

> * will this function be permanently available in c:geo, so that a user can always change its `<base>` dir? (Would be helpful IMHO)

I planned it like this, and it is currently implemented this way. (Need it a lot for testing currently...)

 
> migration:
> 
> * IMHO we should include selecting the base folder include in our new installation wizard and call this wizard automatically on startup if no `<base>` folder is set or `<base>` is not accessible

* Inclusion in wizard: Agreed! I would to this once the stuff is in master, is that ok?
* Checking on startup: already done (but right now with an own alert dialog)
* I updated the Wiki with this information

> * This dialog should reappear on every startup until a new `<base>` is set. Otherwise my fear would be that people skip this dialog until it's too late.

* Agreed and already implemented this way

**Comment by Lineflyer** [comment]
I had a similar question as @moving-bits already had:

Now you changed:

> To clear that up, I changed the description on the page to differentiate between:
>
>    T (transient): folder is selected on-the-fly by user, used for single use case and then forgotten
>    D (defaulted): folder has a fixed default value which can not be overridden by user
>    U (user-selectable): folder can be freely selected by user, but has a default location as fallback in case the user doesn't do that

I still have the question why e.g. gpx should be user-selectable. Shouldn't it be rather always below [base] in a folder [base]/gpx (whereas [base] is user selectable)?

**Comment by eddiemuc** [comment]
> I still have the question why e.g. gpx should be user-selectable. Shouldn't it be rather always below [base] in a folder [base]/gpx (whereas [base] is user selectable)?

I can't answer this question, this was build into c:geo long before my time (and has nothing to do with SAF)...

But we can change this and make the dir unselectable by user as of now if you wish so?

**Comment by Lineflyer** [comment]
> But we can change this and make the dir unselectable by user as of now if you wish so?

I think for import we would need the transient case to select a file somewhere for import, for export it can be defaulted as we now already have (or should new implement) a share possibility after the file has been generated.

**Comment by eddiemuc** [comment]
I think we moved past this concept now, thus will close this issue
