### ISSUE TITLE
Allow share in field note export dialog

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9662]
> It would work, of course but I would describe that approach as a kludge at best.

I'm thinking of something like we have done it for creating backups.

![Screenshot_20201216_093137_cgeo geocaching_copy_250x153](https://user-images.githubusercontent.com/64581222/102324071-98b10080-3f81-11eb-9630-d9147f0ce426.png)

Then you would be able to directly share it with your third party app, upload it to drive or whatever you like. And it would be a general solution where all users would have a benefit and it would be easy to understand... 

What do you think?

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/discussions/9544#discussioncomment-213182_

**Comment by fm-sys** [comment]
Already done in #9581
