### ISSUE TITLE
use dependabot for dependency resolution

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9677]
It is possible to automate the (gradle) dependency resolution using dependabot.
The dependabot is integrated in Github and free of charge (https://dependabot.com/#pricing).

The configuration details are described in
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

**Comment by fm-sys** [comment]
I have just now activated dependabot for my [snapdrop-android](https://github.com/fm-sys/snapdrop-android/) repository (very cool app BTW if you want to quickly share files between Android and Windows or other devices ;-) ). However, activating dependabot is quite simple:

- under `settings > security & analysis` activate `Dependabot security updates`
- afterwards, a config file needs to be created called `dependabot.yml` in the `.github` directory. In its simplest configuration it should look for gradle projects like this:
```
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
```

IMHO the only disadvantage is that every dependency gets its own PR, so they are unfortunately not grouped. (No idea if this is configurable)

_If_ we want to use it, someone with access to the repository settings needs to activate dependabot. Then I can provide a PR with the basic configuration file...

**Comment by bekuno** [comment]
The configuration should be done with the cgeo-ci-bot account, imho. @Lineflyer ?

It could at first test with the WhereYouGo repo if this works.

From reading documentation we have some more to configure
- `package-ecosystem: gradle` for global and sup projects
- define some `ignore`s
- maybe support for branch release

But this is then work in progress.

> IMHO the only disadvantage is that every dependency gets its own PR, so they are unfortunately not grouped. (No idea if this is configurable)

I would say that this is a advantage.
So we can decide if/when this should be merged.

**Comment by Lineflyer** [comment]
Are we talking about https://github.com/marketplace/dependabot-preview

In this case it seems I can either select my user (or the cgeo-ci-bot if I login as this user) or simply the c:geo oranization.

Shall I install it? But I have no idea currently how enabling for certain repository is performed. Did anyone already find a more detailed documentation about the setup?

**Comment by Lineflyer** [comment]
Addition:
After reading the post from @fm-sys I just went to Security & Analysis and enabled the dependabot for the WhereYouGo repository. Seems its no longer needed to first install the Github app into the repository...

@bekuno Feel free to try if it works in WhereYouGo by creating the yml file as mentioned by @fm-sys

**Comment by fm-sys** [comment]
dependabot is also integrated directly into github. So it just needs to be activated in the repository settings under `settings > security & analysis`

**Comment by Lineflyer** [comment]
AFAICS it was already activated for the cgeo repository and others. Only on WhereYouGo it was disabled, so I enabled it.

You may go ahead with trying to place the config YML file(s).

**Comment by bekuno** [comment]
I made a Wiki site for GitHub:  https://github.com/cgeo/cgeo/wiki/GitHub .
There is integrated a short section for dependabot.

**Comment by fm-sys** [comment]
@bekuno Anything else which needs to be done or can we close this issue?

**Comment by Lineflyer** [comment]
Well. from my perspective someone should take care to either merge or close the dependency PRs which are still open since a while. We are now just after a release and before next branching/beta release. So whatever looks save to merge we could try/test, what is technically not possible to upgrade should be closed (and documented why or configured to not disturb).

**Comment by bekuno** [comment]
I think we can close here.
The integration of dependabot is working in the code for c:geo and WhereYouGo.
It needs some tuning tasks, but this is then the normal code maintenance.
