### ISSUE TITLE
Distance info missing on GMaps direction line

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9682]
**Describe the bug:**
The distance info in upper right is missing on GMaps if map option "Show straight distance" (in addition to routed) is active

**To Reproduce:**
1. Have Brouter installed and configured
2. Have Settings - Map - "Show straight distance" disabled
2. Open GMaps live map, select a nearby cache and active direction line in cache popup

**Actual behavior/state after performing these steps:**
(Routed) direction line is drawn, cache title is shown on top of map. However routed distance info in top right is missing.
Change to OSM: Distance info is now shown

**Expected behavior/state after performing these steps:**
Routed distance should be shown on GMaps (same behavior as on OSM)

**Remark:**
If Settings - Map - "Show straight distance" is enabled, then both distances show up on GMaps (no failure). So there seems to be a wrong "if"-statement or something like this.

**Version of c:geo used:**
2021.01.03-NB

**Is the problem reproducible:**
It looked like that while I tested this problem, but in fact it might happen, that the distance shows up if you just wait for approx. 30 seconds.

**Screenshots:**
![Screenshot_20210105-135531](https://user-images.githubusercontent.com/949669/103648816-bad4e780-4f5d-11eb-9b8e-061bd8f0a927.png)

**System information:**
Google Pixel 3a, Android 11

**Comment by moving-bits** [comment]
Reason is (has been) that the distance info only gets shown on next location update.

I've prepared a PR which manually sets the current position on setting a new target using the cache/waypoint "set as target" icon.
