### ISSUE TITLE
Batch function to set cache icon for all caches in list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9685]
**Is your feature request related to a problem?**
I have imported a Adventure Lab GPX to see adventure lab caches around my homezone.
At the moment those are imported with the default (grey ??) icons.

In order to better identify those on the map a custom icon would be useful but needs to be set manually for all 200 caches on my list.

**Describe the solution you'd like**
The menu "Manage lists" could get an item "Set cache icons" which provides a batch function to set the icon for all caches on the list...same as already implemented for a single cache.

The reset function could however be a bit more tricky. In my case all caches have the same default icon...but that might be different for other scenarios and we should - in any case - provide some batch undo/reset in case someone uses this function accidentally.

**Comment by moving-bits** [comment]
> The reset function could however be a bit more tricky. In my case all caches have the same default icon...

If batch-setting a new icon is implemented, then batch-resetting is easy, as the value for default is "0".

**Comment by moving-bits** [comment]
I've put it into the "manage caches" submenu, as the function is cache-specific, not list-specific (in contrast to "set list marker"). See #9693.

**Comment by MagpieFourtyTwo** [comment]
> If batch-setting a new icon is implemented, then batch-resetting is easy, as the value for default is "0".

Just stumbled upon this function ... reset can additionally be achieved by just refreshing the caches.
(I in fact was looking for a possibility to reset changed icons to default - seems as if I have found it ;) ).

**Comment by moving-bits** [comment]
A regular reset function has been implemented meanwhile. "Resetting" an individual cache icon is as easy as storing a value of 0 to a specific member field. Icons in the list and on the map will we regenerated automatically. There's no need to reload a single cache or a whole list from the website.

**Comment by MagpieFourtyTwo** [comment]
Is this "Reset" already in the menus - and where can I find it?

**Comment by moving-bits** [comment]
> Is this "Reset" already in the menus - and where can I find it?

Reset is implemented as button in the "Set cache icon" / "Set cache icons" popup.
(Merged for lists only today, so should be in tomorrow's build.)

**Comment by wolverine007** [comment]
Hi,

really nice feature 👌

But I identified two small issues:
While being on the live map and opening a cache for updating the listing, the app is refreshing the icon as well, that's the first one. User defined icon should stay as long as the user is not updating it (my opinion).

Second one - after the refresh and therefore the icon undo, the cache is blown away from the live map. You have to leave the map and reopen it, than the disappeared cache is shown again.

Not sure if someone already asked it, but will the icon set be extended? I am missing some icons to mark for instance imported lab caches with ⚗️or🧪or something else. 

Cheers,
Wolv

**Comment by moving-bits** [comment]
@wolverine007 
Thanks for your feedback. 

Live map / icon change: 

The icon chosen is stored in the database, which should work for live map caches as well. I'll look into it. - Do I understand your workflow correctly as:
- open live map
- change cache icon for a cache not stored yet
- open popup, then cache details => there a different icon is shown

?
(A known issue is currently, that the cache popup shows the default icon. But the cache details page should show the selected icon.)

--
Live map / cache icon vanishes: That might be #9374 

--
Additional icons:

The current set ist just a priliminary selection, to be extended for sure. I've chosen icons from the following list of Unicode 5.0 supported icons: https://unicode.org/emoji/charts-5.0/full-emoji-list.html
If you like to see specific icons to be added, it would be a great help if you could provide me the Unicode codepoints for them, which are listed in the second column ("code") in above web page.

Currently we've chosen a relatively old version of the Unicode standard, which Google claims to support on Android 5+ devices (which is our current base). We might increase that later to support more characters at least on more recent devices, but need to solve some technical aspects for that first, to not show placeholder for characters/glyphs not supported by the users' specific device.

**Comment by wolverine007** [comment]
Hi,

I opened the live map (Google Map), stored the cache inside the default list.
Changed the icon with the new feature.
Left the cache and the new chosen icon was shown on the map correctly.

Opened the cache with the pop-up and clicked there the refresh icon.
Left the pop-up by clicking anywhere else on the map and the cache icon is gone.

BTW: any reason why the custom logos are shown with a squared icon instead of the default round one?

Will check the icon list later on and will provide you the codes which might be useful for labs.

Cheers,
wolv

**Comment by wolverine007** [comment]
Found right now only one symbol which is close to the lab icon: U+2697

Thanks for taking care of this nice addon :)

**Comment by bekuno** [comment]
really U+2697?
Alembic, in German Alchemie.
https://unicode-table.com/en/2697/

**Comment by moving-bits** [comment]
> really U+2697?

I guess this is for lab caches. There may be better fitting symbols (see his posting above), but those are not part of the old Unicode standard we currently have to use due to our API 21 support limit. If we manage to live-detect symbols/glyphs not supported (which I will start to try), then we can include both (and others as well).

**Comment by moving-bits** [comment]
> BTW: any reason why the custom logos are shown with a squared icon instead of the default round one?

I've chosen to do it that way because some of the characters selectable are more squared and would not fit well into our (GC-) default rounded marker. But we may discuss that.

**Comment by wolverine007** [comment]
> > BTW: any reason why the custom logos are shown with a squared icon instead of the default round one?
> 
> I've chosen to do it that way because some of the characters selectable are more squared and would not fit well into our (GC-) default rounded marker. But we may discuss that.

Okay, fine for me as well, when it is technically related.

Maybe as well an advantage, cause you could easily identify adjusted icons on the live map 🤔

**Comment by moving-bits** [comment]
> Maybe as well an advantage, cause you could easily identify adjusted icons on the live map 🤔

Depends on what geocaching services you are using. gc.com is using the rounded marker, opencaching.* the squared marker.

**Comment by moving-bits** [comment]
> While being on the live map and opening a cache for updating the listing, the app is refreshing the icon as well, that's the first one. User defined icon should stay as long as the user is not updating it (my opinion).

I've found the cause and created a fix for it (#9737) - should be in the next nightly version.

**Comment by Lineflyer** [comment]
> Maybe as well an advantage, cause you could easily identify adjusted icons on the live map 🤔
> 
> 
> Depends on what geocaching services you are using. gc.com is using the rounded marker, opencaching.* the squared marker.

That is whats makes me think we should stay with the shape predefined by the source platform. So users can still seperate GC from others even if they changed the icon for a whole list.

**Comment by moving-bits** [comment]
> That is whats makes me think we should stay with the shape predefined by the source platform. So users can still seperate GC from others even if they changed the icon for a whole list.

I can give it a try. If the custom icons gets too close to the border of (or even overlaps with) the marker, we need to/we can adjust margins and/or size of the custom icon.
