### ISSUE TITLE
[installation wizard] Wrong cgeo public directory 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9700]
**Describe the bug:**
It looks like, c:geo configures it's public directory at a time where it has no write access to the public storage, so the directory get's set to `/data/user/0/cgeo.geocaching`

System information :
```
--- System information ---
Device: SNE-LX1 (SNE-LX1, HUAWEI)
Android version: 10
Android build: SNE-LX1 10.0.0.245(C432E10R1P1)
c:geo version: 2021.01.06-NB-1237da3
Google Play services: enabled - 20.45.16 (120408-344294571)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE / user-defined language: 
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (3,6 GB free) internal
User storage c:geo dir: /data/user/0/cgeo.geocaching (3,6 GB free) internal
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (3,6 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (184,0 KB) on system internal storage
Last backup: never
GPX import path: /data/user/0/cgeo.geocaching/gpx
GPX export path: /data/user/0/cgeo.geocaching/gpx
Offline maps path: null
Map render theme path: 
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled: None
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---

```

**Comment by Lineflyer** [comment]
Indeed, I somehow remember that there might be conditions (not sure if depending on Android version, etc.) where this happens. Only on next start it detects and uses the correct working dir instead of the sys-internal fallback dir.

Don't we have an issue for that already, need to search for it?

**Comment by moving-bits** [comment]
What happens if you close c:geo in this situation (after having granted storage access), remove it from memory, and restart it?

(I remember that under some circumstances c:geo already has that problem, even before the wizard, but we could not get a hold on.)

**Comment by Lineflyer** [comment]
Related or duplicate to #7366

**Comment by fm-sys** [comment]
No, it only happens since the introduction of the new installation wizard on my device...

**Comment by fm-sys** [comment]
Jep. You are right, a restart helps. But until then the restore function is completely unusable...

![Screenshot_20210106_150548_copy_640x406](https://user-images.githubusercontent.com/64581222/103777872-cbef2880-5031-11eb-9e66-c85d229bf990.jpg)
![Screenshot_20210106_150724_copy_640x330](https://user-images.githubusercontent.com/64581222/103777878-cc87bf00-5031-11eb-9396-42ad9630bf96.jpg)

**Comment by fm-sys** [comment]
BTW, there are also some layout styling problems (and my screen is not that small -  6,3"):

![Screenshot_20210106_143307_cgeo geocaching_copy_216x468](https://user-images.githubusercontent.com/64581222/103779873-93048300-5034-11eb-92b8-11277d89a6a1.jpg)

**Comment by moving-bits** [comment]
> BTW, there are also some layout styling problems (and my screen is not that small - 6,3"):

This is due to the long texts... But having this screen to be scrolleable might be a good idea anyway, just in case. I'll prepare a PR for it.

**Comment by Lineflyer** [comment]
> No, it only happens since the introduction of the new installation wizard on my device...

Pretty sure it was there before (only in the first session).

**Comment by fm-sys** [comment]
Just for reference: will (hopefully) be implicitly fixed with #9700

**Comment by moving-bits** [comment]
Just as reminder to myself for further checking, if #9720 will not fix it:
Need to check whether internal paths need to be reset after granting read permissions.

**Comment by Lineflyer** [comment]
Shall we close #7366 as a duplicate anyway?
In there @pstorch described the probable solution as follows:

>  As you see the variable "externalPublicCgeoDirectory" is cached. I guess this should be reevaluated after c:geo got the external file permission.

**Comment by moving-bits** [comment]
@fm-sys 
Does this error still occur?

**Comment by fm-sys** [comment]
AFAIK it was fixed for our current release and will become obsolete with #9720 anyway, so we can close this one...
