### ISSUE TITLE
Corrupted database recovery mechanism: can this be removed?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9709]
From https://github.com/cgeo/cgeo/issues/9606#issuecomment-755517327 and related to SAF migration:

Edited Copy:
There seems to be some (legacy?) mechanism in c:geo where we search for a database file in backup folder named "data.corrupted" in the backup dir in case we fail to open the primary db. The original code seems to be from 2014 by @samueltardieu (hard to say for sure since it was modified a lot over the years, but those seem to be "cosmetic" changes only).

I could however not find a part of c:geo **producing** such files. So my naive guess would be that this is no longer used/needed and can be removed.

Note that if the mechanism is still needed it must be migrated to SAF which I would rather avoid if it is in vain.

Is this mechanism still necessary? And if yes, how is it supposed to work? Where are"data.corrupted" files coming from?

https://github.com/cgeo/cgeo/blob/90e2fecff5a7b06459fbd15d08d57b3b0fe045ef/main/src/cgeo/geocaching/storage/DataStore.java#L753-L760

**Comment by eddiemuc** [comment]
Sorry, I misread the code. Understand the function now and will migrate it.

**Comment by moving-bits** [comment]
> There seems to be some (legacy?) mechanism in c:geo where we search for a database file in backup folder named "data.corrupted" in the backup dir in case we fail to open the primary db. 

IIRC it's the other way around: If c:geo fails to open the database, the current database file is copied to the public c:geo dir as `data.corrupted` and a new, empty database is created instead. So it's sort of a backup mechanism in case of emergency.

**Comment by eddiemuc** [comment]
> > There seems to be some (legacy?) mechanism in c:geo where we search for a database file in backup folder named "data.corrupted" in the backup dir in case we fail to open the primary db. 
> 
> IIRC it's the other way around: If c:geo fails to open the database, the current database file is copied to the public c:geo dir as `data.corrupted` and a new, empty database is created instead. So it's sort of a backup mechanism in case of emergency.
> 

Yes, you are correct. I misread the code, sorry for this unnecessary issue. I will close it.

**Comment by moving-bits** [comment]
No problem. Clarifying was easy in this case :-)
And better to ask if somethings unclear, before diving into some hard-work task only to discover later that it has been going the wrong way.
