### ISSUE TITLE
SAF: migration of "Spoiler images" 

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9719]
This is an issue to deal with (possibly needed) SAF migration for "Spoiler image" folder

There is an external directory defined in LocalStorage namend "GeoCachePhotos" which is supposed to contain "spoiler images":

https://github.com/cgeo/cgeo/blob/ccb0385dd8b65b5fb124e418dbf4cf4499ad24e2/main/src/cgeo/geocaching/storage/LocalStorage.java#L344-L347

I do not have this dir on my installation. A quick code scan seems to indicate that this is only used for oc and su. 

![image](https://user-images.githubusercontent.com/6909759/103870723-63a15500-50cc-11eb-9163-e3061e5a3baf.png)

I don't use SU and OC very seldom, have not come across these spoilers yet. What is this, and is it still needed? If yes, can it go to a private folder?

**Comment by eddiemuc** [comment]
> If yes, can it go to a private folder?

IMHO yes. Spoiler images should not even be publicly visible ;-)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/9606#issuecomment-756029183_

**Comment by eddiemuc** [comment]
> > If yes, can it go to a private folder?
> 
> IMHO yes. Spoiler images should not even be publicly visible ;-)

Do you know what these "Spoiler images" are conceptually? And why they are treated somehow differently from all other images? And why they seem to exist only for OC and SU?

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/9606#issuecomment-756038795_

**Comment by fm-sys** [comment]
> Do you know what these "Spoiler images" are conceptually?  

Unfortunately not. Just guessing... 

Btw, where are the GC spoiler pics saved? I have no idea why they are treated differently. To degrees code complexity it would be the best if sll connectors and all images (spoilers / log images by other users) use the same architecture...

**Comment by Lineflyer** [comment]
This is used for GSAK spoilersync:
https://manual.cgeo.org/de/spoilersync

**Comment by Lineflyer** [comment]
Thus it should be kept, so the user can place his spoilersync photos below [base]/GeocachePhotos

**Comment by moving-bits** [comment]
Maybe we should rename the dir then to something which expresses its usecase more clearly, eg "spoilersync"?

**Comment by Lineflyer** [comment]
> Maybe we should rename the dir then to something which expresses its usecase more clearly, eg "spoilersync"?

We could do, but then we need a migration inside the migration or prior to SAF migration to move existing (which some users might have)

**Comment by eddiemuc** [comment]
before migrating this I want to make sure I understand it correctly. From manual above and also from code my understanding is as follows:
* This folder is so c:geo can **read** (spoiler) images placed in `[base]/GeocachePhotos` (today: `/cgeo/GeocachePhotos`)by another app (e.g. a sync tool or GSAK or whatever). Thus it cannot of course be a private app folder.
* c:geo will **not** itself  **write** anything to this folder. It will just display the images in such a folder as well if there are any available

Is this correct? I will base my implementation on this assumption.

**Comment by Lineflyer** [comment]
Yes, AFAIK this is how it works.

**Comment by eddiemuc** [comment]
In this case PR #10013 should do the trick
