### ISSUE TITLE
SAF: migration of "Backup" 

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9720]
This issue is for migration of "backup" folder to SAF.

"Backup" process currently deals a lot with File/Directories. Some basic cleanup (in master) is necessary before migration can be concluded. My suggestion:
* "File" objects shall not be used as basic parameters any more
* core backup process based on (private) c:geo files should be moved to "DataStore"
* "BackupUtils" should be redesigned to handle the transfer between external entities (not necessarily Files, but rather Uris and streams) to these core backup processes. Those "external entites" can for now be constructed out of Files but in encapsulated methods (which then can be easily exchanged with SAF access).

**Comment by eddiemuc** [comment]
@fm-sys since you redesigned the backup routines not so long ago I wonder if you are interested in doing this migration?

In this case I could provide you some "stub" methods inside the BackupUtils class "simulating" the SAF framework (while for now still working with Files underneath).

But if you want I can also do the migration myself. What would you prefer?

**Comment by fm-sys** [comment]
Hi @eddiemuc,

for sure I would like to takeover the migration of the backup process. However I'm not yet firm with the SAF but I think I can do it if you provide me a short summary how the SAF is used in c:geo and what to note. I will also read through your wiki page in the next few days...

**Comment by eddiemuc** [comment]
@fm-sys Great!

Since the framework is not yet integrated into master (only in storage_framework) we can approach this different ways:
* we let this issue rest until storage_framework is in master. Can't tell you how long that will take though
* you work on storage_framework. Note that this means participating in daily rebase-merges from master...
* I provide some "fake-classes" in master which "simulate" the framework (but really encapsulate only Files) and you work against those.

wrt the usage: I wrote a small usage guide on the wiki page https://github.com/cgeo/cgeo/wiki/Disk-Usage-migration-towards-Android-11 (scroll down to "using the framework")

**Comment by fm-sys** [comment]
> I provide some "fake-classes" in master which "simulate" the framework (but really encapsulate only Files) and you work against those.

If it's not too much effort for you, this seams to be to most efficient option to me. Otherwise it might make sense to wait until you're finished with your work at storage_framework and then build my changes on top of it...

**Comment by eddiemuc** [comment]
> > I provide some "fake-classes" in master which "simulate" the framework (but really encapsulate only Files) and you work against those.
> 
> If it's not too much effort for you, this seams to be to most efficient option to me. Otherwise it might make sense to wait until you're finished with your work at storage_framework and then build my changes on top of it... 

Well if it were up to me storage_framework would have been merged already a couple of weeks ago. But I think we have to wait for next release.

Let me see what I can do

**Comment by eddiemuc** [comment]
@fm-sys I started to write a "framework simulator", but it turns out this is more complex than I thought. Because this work would be in vain, I think it is better simply to wait until storage_framework is merged to master. I issued the PR just now. I hope this is also ok for you.

If you do not want to wait so long, you can already start to refactor BackupUtils such that it does no longer use Files except for a few methods which convert the existing File references to Uris or deliver information lists from (directory) Uris (a replacement for "dir.listFiles()"). Those methods are then the ones we can replace later with calls to ContentStorage.

**Comment by fm-sys** [comment]
> @fm-sys I started to write a "framework simulator", but it turns out this is more complex than I thought. Because this work would be in vain, I think it is better simply to wait until storage_framework is merged to master. I issued the PR just now. I hope this is also ok for you.

No worry. As the SAF is designed to work in combination with our old legacy file access in c:geo until everything is migrated refactoring the backup process shouldn't be that urgent, so I will wait until SAF is merged to master. Totally fine for me!

**Comment by eddiemuc** [comment]
Thanks!

**Comment by fm-sys** [comment]
Since SAF is now in `master`, I try to familiarize myself with the topic... 

> "Backup" process currently deals a lot with File/Directories. Some basic cleanup (in master) is necessary before migration can be concluded. My suggestion:
> 
>     * "File" objects shall not be used as basic parameters any more

Totally agree! Will not be possible in anymore with SAF. So replace with `Uri`?
> 
>     * core backup process based on (private) c:geo files should be moved to "DataStore"

Really? Isn't `DataStore` only used for database related things?

**Comment by eddiemuc** [comment]
HI @fm-sys ,

sorry, when I wrote this issue I kind of asumed I would be the one implementing it, So I wrote things maybe a bit too "short"...

Yes, `Uri `is kind of the new File object, although handling is a bit different than with `File`.

When looking into the topicI discovered the following:
* `DataStore `has two methods `restoreDatabaseInternal` and `backupDatabaseInternal` which seems to implement the "core" process for restore/backup.
* The core restore/backup process seems to need to work with `File` (at least the database itself needs to be referenced as a `File` because the interfaces don't provide stream methods)

So my initial idea was to leave the "core" processes in `DataStore` (working with `File` handles) and put all the SAF handling into `BackupUtils` (so `BackupUtils` should not use `File` in its API)

**Comment by eddiemuc** [comment]
Oh, and I meant only to put/leave the core **database** backup in DataStore, not the other backup parts (like settings) :-)

**Comment by fm-sys** [comment]
>   at least the database itself needs to be referenced as a `File` because the interfaces don't provide stream methods

What about this settings option? (How) will it work with SAF and is it migrated?

![Screenshot_20210126_091820_cgeo geocaching](https://user-images.githubusercontent.com/64581222/105819157-1ec85a00-5fb8-11eb-9934-fc9277183f78.png)

**Comment by fm-sys** [comment]
@eddiemuc When I upgraded to the today's nightly, all my backup files were duplicated. Looks like SAF doesn't like dir names which have white spaces in it. Is that something expected, and how can we maybe handle it in a better way? It should also be noted that the newly created folders are all empty...

![Screenshot_20210126_083134 - Kopie](https://user-images.githubusercontent.com/64581222/105820364-c42ffd80-5fb9-11eb-89e6-dd2ba322f30a.jpg)

**Comment by eddiemuc** [comment]
> >   at least the database itself needs to be referenced as a `File` because the interfaces don't provide stream methods
> 
> What about this settings option? (How) will it work with SAF and is it migrated?
> 
> ![Screenshot_20210126_091820_cgeo geocaching](https://user-images.githubusercontent.com/64581222/105819157-1ec85a00-5fb8-11eb-9934-fc9277183f78.png)
> 

DB is stored in app internal storage which is not affected by SAF and can use Files also in the future. Thus I did not touch this logic and I don't think it needs to change

**Comment by eddiemuc** [comment]
> @eddiemuc When I upgraded to the today's nightly, all my backup files were duplicated. Looks like SAF doesn't like dir names which have white spaces in it. Is that something expected, and how can we maybe handle it in a better way? It should also be noted that the newly created folders are all empty...
> 
> ![Screenshot_20210126_083134 - Kopie](https://user-images.githubusercontent.com/64581222/105820364-c42ffd80-5fb9-11eb-89e6-dd2ba322f30a.jpg)
> 

I don't think that SAF is unable to deal with whitespaces, this might be a bug. Did you select copy or move option when selecting new SAF base dir?

**Comment by eddiemuc** [comment]
Update: yep that's a bug on my side. I replace whitespaces with - in my code, I have to make an exception for space.

**Comment by fm-sys** [comment]
I selected "do nothing". That's why it was a bit unexpected 😅 But anyway, it looks like you already found the reason 👍

**Comment by Lineflyer** [comment]
> I selected "do nothing". 

Therefore I am still wondering why it was copied after all.
As @eddiemuc told, he found the whitespace problem on copy/move but "do nothing" should do nothing, shouldn't it?

**Comment by eddiemuc** [comment]
There are two small bugs in code which lead to this behaviour:
* I did not list space as "allowed character" for filenames
* I did accidentally leave "create folder if not exists" in when directories are scanned.

When changing dirs, the source dir is scanned to show number of files and subfolders contained. There the suspicious folders are created. Looks strange, but is harmless and easy to fix. Problem is that I currently have no chance to code on c:geo

**Comment by eddiemuc** [comment]
@fm-sys : just asking whether you still plan to tackle this issue? Everything needed is available now in master.

**Comment by fm-sys** [comment]
Still on my to do. Was just too busy for this major change so far...

**Comment by fm-sys** [comment]
I've made some progress now - but still not finished...

When we added support for multiple backups last year, I had added a migration routine to move an already existing backup to the correct subfolder. Since it has been some month ago, I would like to remove this routine, as it would make the work for SAF another piece more difficult. People who had made a backup before these days **and** never opened the settings after that will still be able to restore this backup by using the "Restore a different backup" function. It's then just not so convenient. However, it's anyway quite unlikely that someone want to restore a backup that has been out of date for months... Do you agree?

![grafik](https://user-images.githubusercontent.com/64581222/107858865-b4783c00-6e36-11eb-85cf-bd1b1183adbb.png)

**Comment by eddiemuc** [comment]
@fm-sys  I found a bug in permission checkt when using temporary folders (they are also checked against persistent folder permission cache which is of course wrong). This should be fixed with #10036, you should be able to continue once this is merged.

Your code is correctly using the contentstorage :-)
