### ISSUE TITLE
Special characters (sum symbol) not correctly shown in listing text

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9742]
From support mail:

The cache GC93DWV contains a sum symbol for calculating the coordinates (at the very end of the listing). While its rendered normal in my browser c:geo shows something like ```(\displaystyle\sum_```

**Comment by moving-bits** [comment]
Interesting, didn't know that's possible:

It uses a custom javascript in the cache listing (don't know yet if provided by gc.com or user-set) which provides mathematical symbols (similar to LaTex) by adding a specific class in the HTML:

`<span class="math-tex">\(\displaystyle\sum_{i=A}^{Y}i\)</span>`

Included JS is:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML" defer></script>`

Don't think that we have a chance to interpret such things and display them correctly, as we don't render JS code for our display (AFAIK).

**Comment by Narrat** [comment]
This kinda reminds me of LaTeX.

**Comment by Lineflyer** [comment]
:) My diploma thesis was written in LaTeX.

Lets close here. Also the official app is not rendering it and it makes no sense or might lead to unwanted results if we try to import random Javascript a user provides in his listing.

**Comment by capoaira** [comment]
Today I create a cache listing with such a math formula. I want to report, that this is not render by c:geo, but then I found this Issue. Maybe it is helpful to add a warning like for table elements "The description contains math formulas that may only be displayed correctly on geocaching.com.".
