### ISSUE TITLE
Set better subject for problem report mail

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9743]
Just a very small improvement proposal:
Currently if a user uses the new function Main Menu - Report problem the generated mail will contain the subject "c:geo system information".  As this subject gets picked up from the support mail ticketing system when replying to the user it looks a bit strange to users.

Could we use something like "c:geo problem report" for this? (no need for localization)

**Comment by eddiemuc** [comment]
@Lineflyer out of interest: did the number of reported problems increase noticeably since we have this "report" menu entry?

**Comment by Lineflyer** [comment]
Despite the fact that probably less users are ur caching during winter time, I would say still I do see an effect. More reports with attached logs.

**Comment by eddiemuc** [comment]
> Despite the fact that probably less users are out caching during winter time, I would say still I do see an effect. More reports with attached logs.

And since you are the person on the "frontline" receiving all these emails: do you see this as an improvement or is it also a burden (because you have to deal with all these emails)?

**Comment by Lineflyer** [comment]
> And since you are the person on the "frontline" receiving all these emails: do you see this as an improvement or is it also a burden (because you have to deal with all these emails)?

Well, I somehow like to do that as it provides quite some undiscovered errors and I get to know how people use c:geo. 
And since we now have this "problem report" I do need to write less mails to ask for further details, logs, sysinfo.
