### ISSUE TITLE
Sort and structure system information

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9744]
More and more items are contained in our system information. While I appreciate that as it allows to doublecheck more potential issues in beforehand, it started to get a bot crowded and I take some time to find what I am looking for.

Is there a possibility to structure the information somehow.
A very easy solution like sorting by topics and indentation below would already be helpful. No need for HTML or something like that.

Example:
```
Device:
-------
  Device type:
  Android version:
  c:geo version:
  Google Play Services:
  Location permission:
  Storage permission:
Sensor and Location:
-------
  Compass capabilities: 
  ...
```

If someone directs me where and how to do that, I can try tackling it myself (as I am the one mostly dealing with the result). I don't know however if advanced coding is needed, which would rather mean I cannot do it (without SDK).

**Comment by eddiemuc** [comment]
Can we please wait until saf is merged? There are quite some changes in there to Systeminformations

**Comment by Lineflyer** [comment]
Sure, not of any importance and your proposal sounds reasonable.
