### ISSUE TITLE
[minor] Lower Zoom Level for OSM missing

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9752]
**Describe the bug:**
If you continue to zoom in by two finger spread the maximum zoom level can be exceed and no map in shown.

**To Reproduce:**
1. Live map online OSM
2. Zoom in with finger to the max

**Actual behavior/state after performing these steps:**
No map is shown.

**Expected behavior/state after performing these steps:**
Zoom level should be limited, so that still a map is shown. 

**Version of c:geo used:**
2021.01.08-NB-493da4e

**Is the problem reproducible:**
Yes

**Screenshots:**
20m bar, + greyed out:
![Screenshot_2021-01-10-16-17-22-699_cgeo geocaching](https://user-images.githubusercontent.com/43813636/104126913-84350d80-535f-11eb-88b4-ab4324177c24.jpg)
If I zoom in to 10m: no map and I can continue to zoom in to 5m, 2m, 1m, 1ft:
![Screenshot_2021-01-10-16-19-52-014_cgeo geocaching](https://user-images.githubusercontent.com/43813636/104126972-c9f1d600-535f-11eb-9883-71f5c5bcc675.jpg)

**Additional context:**
The zoom-in via +/- button is greyed out and blocked at the correct level.
No problem for GM and offline maps.
It can also happen to have no map, if you switch map to OSM online at a very high zoom level.

**Comment by wolverine007** [comment]
Same issue occurs when you double tap on the map.

I would assume/suggest that for each map type the lowest zoom level should be something around 5m.

So even when you double tap further or use the two finger zoom, the map should stop on that level according to the grayed out "+" button.

Is it possible to grab the lowest available zoom level per map type? For an offline map it might be defined inside the map file. But where is it defined for an online map?

**Comment by moving-bits** [comment]
> Is it possible to grab the lowest available zoom level per map type? For an offline map it might be defined inside the map file. But where is it defined for an online map?

For offline maps we do this already (yes, it's defined in the map file), but for only maps I don't know of a way to get that info dynamically.

**Comment by fm-sys** [comment]
Not really. This problem also exists for offline maps... 

https://user-images.githubusercontent.com/64581222/104812103-440ed880-5800-11eb-9dbc-b8086a451cbc.mp4

**Comment by moving-bits** [comment]
> Not really. This problem also exists for offline maps...
> SVID_20210116_133722_1.mp4

Ah, I see, thanks for the video. Had missed the "two finger spread" part, thought, it would happen on any zoom.

**Comment by geocachermgo** [comment]
> Not really. This problem also exists for offline maps...
> SVID_20210116_133722_1.mp4
Can confirm, but with my map (Baden-Württemberg) it happens very late: 7 double taps after + is greyed out (scale 5m) so scale would be 0.05m (shows only ft without end bar)

**Comment by moving-bits** [comment]
Notice: When you push on increasing the OSM zoom level using double tap on the screen, you finally run into the same error listed in #9789. (Happened in my test with offline OSM reaching zoom level 32, same as in the mentioned issue.)

**Comment by moving-bits** [comment]
Ok, found the bug: Currently `NewMap` only limits the zoom controls, not the map view to the bounds given by the map. I'll prepare a fix for it.

**Comment by geocachermgo** [comment]
Seems to work correct in the nightly but I have still a case without map being shown:
Chose OSM offline Baden-W
Zoom in max (5m)
Change map to OSM online
Happens also if I change from offline map Baden-W to offline world. If I tap the - button once or shift the map it jumps to the 50km max zoom of the world map.
That trigger should be added when changing the map

**Comment by moving-bits** [comment]
> Seems to work correct in the nightly 2021.01.17-NB-52c82af but I have still a case without map being shown:

Good catch, thanks. A PR for this is on the way...
