### ISSUE TITLE
Jenkins GHPRB update not possible

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9753]
**Describe the bug:**
The GitHub pull request Builder command `add to whitelist` was not successful for the `whereyougo (PR)` job.
(adding dependabot)
So I checked it at CI andd added them manually.
When saving it I got a `java.lang.NoSuchFieldError: PARAMETERVALUE_STRATEGY_VALUES`.
Nevertheless the new user is in the list when checking the configuration once more.

edit: It does not work for all jobs.

**Comment by mucek4** [comment]
To be honest, I have no idea what I have to do here. Any hints?

**Comment by bekuno** [comment]
Maybe it is a problem with the brackets in the name: "dependabot[bot]" .
I think that we should somehow update jenkins and the plugins.

**Comment by mucek4** [comment]
There is an issue here: https://github.com/cgeo/cgeo-executor/issues/15
I was not able to start emulator in docker.

**Comment by Lineflyer** [comment]
@bekuno @mucek4 
Is this still happening after I reconfigured the PullRequestBuilder to use webhooks correctly?

**Comment by bekuno** [comment]
> @bekuno @mucek4 Is this still happening after I reconfigured the PullRequestBuilder to use webhooks correctly?

We do seldom call this command. Maybe it was only a problem for the special dependabot name.
Lets close here and check next time when adding someone to the whitelist.
