### ISSUE TITLE
Fdroid slave is offline on CI

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9773]
While publishing the release I wanted to run the job to update the release on FDroid as well. Unfortunately the slave "fdroid" is offline.

**Comment by mucek4** [comment]
I'm not hosting fdroid slave.

**Comment by rsudev** [comment]
@kumy ?

**Comment by bekuno** [comment]
Maybe the same reason as for the down geogrety.org website.

**Comment by Lineflyer** [comment]
> Maybe the same reason as for the down geogrety.org website.

That could indeed be the reason.

**Comment by kumy** [comment]
yes that was the reason

**Comment by mucek4** [comment]
I see fdroid node is back online.
