### ISSUE TITLE
WP list: "Trailhead" (resp. "Via") should be sorted like the others

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9776]
**Is your feature request related to a problem?**
WP types "Physical Stage" (aka "Stage of a Multi cache"), "Virtual Stage" (aka "Question to answer") and "Marker" (aka "Reference Point") appear in WP list sorted in the order they have been created (in fact most probably sorted by it's internal ID), while "Final" WPs will always appear at the end of the list (for obvious reasons), but "Trailhead" WPs (aka "Vias") are sorted to the start of the list, which does not really make sense, IMO.

**Describe the solution you'd like**
A "Via" should appear listed between the WPs where it belongs, otherwise it's not a "Via".  ;)

**Describe alternatives you've considered**
Using the "properly" sorted "Reference Point" as "Via" would be a solution, too, but would in fact render the "Trailhead" type useless.

**Comment by SammysHP** [comment]
A trailhead waypoint marks the start of a route or path. It is not used for vias. The reference point type is used for marking the way.

**Comment by rsudev** [comment]
I'd say for both assumptions (waypoints are globally sorted by the cache owner in a sensible fashion/trailheads mark only the beginning of a round and are not used as vias) it is easy to find counterexamples.
Defining (and documenting in the user manual) the overall assumptions and rationale for the wp sorting might be a good idea.

**Comment by MagpieFourtyTwo** [comment]
> A trailhead waypoint marks the start of a route or path. It is not used for vias. The reference point type is used for marking the way.

Maybe, but if so, the default name for user defined WPs of type "Trailhead" should add. be changed from "Via" to "Start", too ...?
Additionally, the symbol "Signpost" would be pretty misleading, too, as a signpost can stand for a start as well as for a turn,
while a (Reference) point usually refers to something static and not a movement.

> waypoints are globally sorted by the cache owner in a sensible fashion

Right - so I would refine my FR: 

A *user defined* "Via" should appear listed between the *user defined* WPs where it belongs, otherwise it's not a "Via". ;)

**Comment by eddiemuc** [comment]
It is hard/impossible to find a solution here fitting all use cases. Thus let's close here for now
