### ISSUE TITLE
Caches only visible in compact mode

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9778]
While investigating #9374 I stumbled upon another strange issue related to compact icon mode.
It might or might not be related to #9374, therefore opening as dedicated issue for the time being. Maybe it helps to get a clue for #9374 if the root cause is the same.

Test scenario (not exactly reproducible):
- Set compact icon mode to ON in quick settings on map
- Zoom out to cover a huge area
- Zoom back in 
- Open quick settings and switch OFF compact mode
- No caches shown on map
- Switch compact mode again to ON
- Caches shown again

The following video (196MB) explains better:
https://files.droescher.eu/public/issue_compactmode.mp4

**Comment by moving-bits** [comment]
@Lineflyer 
Can you retest whether this still happens with current release (which includes the fixes for #9374)?

**Comment by Lineflyer** [comment]
I could  not reproduce with release version. I assume it was a manifestation of what you recently fixed.
