### ISSUE TITLE
export personal note

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9779]
What does the "export personal note" do? It is uploading all personal notes to GC, is my guess right?

![Screenshot_20210111_145752](https://user-images.githubusercontent.com/64581222/104191259-937a9080-541d-11eb-90b6-bf2b33db892e.png)

If that's the case there are at least two things which need to be done:
- edit string, so that it is obviously that it is uploading something
- hide this action for basic members

---

- and a cancel option would be cool too, but this is more related to #1798

**Comment by Lineflyer** [comment]
You are perfectly right. "Export" is misleading...the string should not only renamed but taken out of the export menu IMHO:

**Comment by fm-sys** [comment]
> the string should not only renamed but taken out of the export menu IMHO

Where to put this function if not in the export submenu? The field notes function can upload things as well and is also in this menu. Our goal should be to group everything in submenus to keep the menu clean...

**Comment by Lineflyer** [comment]
> Where to put this function if not in the export submenu? 

Thats maybe why it was put there after all.
Still we do not use the term "export" for things we send to the geocaching server at any other place.
And the term "export" IMHO points to something I can extract out of the program (into a file).

**Comment by moving-bits** [comment]
In our discussion about restructuring the cache detail menu we decided to remove this menu entry as it is not only somewhat confusing, but also doubles the icon below the personal note field. So let's close here.
