### ISSUE TITLE
Emoji not centered

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9783]
I selected a user defined emoji for one of my cache lists (adventure labs):
![Screenshot_20210111-222327_cgeo](https://user-images.githubusercontent.com/949669/104240368-3fdb6780-545c-11eb-9416-62a0ef988054.jpg)

On the map it seems those are not really centered...no technical issue, but does not look nice.
It might be possible, that the emoji is just not meant to be in the center...not sure?!

![Screenshot_20210111-222345_cgeo](https://user-images.githubusercontent.com/949669/104240402-4d90ed00-545c-11eb-812f-b02908d042fb.jpg)

**Comment by moving-bits** [comment]
I have already fixed this locally, will be part of my oncoming emoji update
