### ISSUE TITLE
Crash on startup on special device (Android car radio)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9784]
From support mail, and an interesting topic (while a minor usecase):
A user installed c:geo on this device: https://www.amazon.de/gp/product/B08D238V4P/ref=ask_ql_qh_dp_hza
He reports, that it keeps crashing on startup.

I requested some more info:
- Exact model name / model type
- Whether he can transfer files from/to the device

Can someone tell me if we can retrieve a logfile (e.g. via the method to configure logging via the dedicacted file)? I never used it and would need assistance.

**Comment by Narrat** [comment]
Transfer of files shouldn't be a problem. Those car radios behave like smartphones. BT, Wifi, USB is all available.
Even the hardware are typical SoC. As Quad Cortex-A53 is listed as a CPU, this shouldn't be an issue.

**Comment by eddiemuc** [comment]
The configure method for logfiles should work on this device as long as the user is able to place a config file in the logfiles folder of the device. Hiwever, c:geo logs also without such a file, it is just there to fine-grain the logging. When the startup fails as described chances are good that errors are logged even w/o using a config file.

But c: geo does not write it's own Logfile, it uses the Android system Log. Log files must be extracted via logcat using a logcat reader. I don't know if such a reader is available and usable on this device.

**Comment by Lineflyer** [comment]
> But c: geo does not write it's own Logfile, it uses the Android system Log. Log files must be extracted via logcat using a logcat reader. I don't know if such a reader is available and usable on this device.

I athought the logfile config will trigger producing such a file in a crash on startup scenario...but thinking about it, how should that work if c:geo does not manage to start. My thinking was a bit shortsighted.

**Comment by fm-sys** [comment]
> Log files must be extracted via logcat using a logcat reader. I don't know if such a reader is available and usable on this device.

Logcat readers normally need either root access or read-logs-permission via ADB...

**Comment by eddiemuc** [comment]
> > But c: geo does not write it's own Logfile, it uses the Android system Log. Log files must be extracted via logcat using a logcat reader. I don't know if such a reader is available and usable on this device.
> 
> I athought the logfile config will trigger producing such a file in a crash on startup scenario...but thinking about it, how should that work if c:geo does not manage to start. My thinking was a bit shortsighted.
> 

I don't think this was shortsighted :-) In the past I thought about a log config option to ask c:geo to write all logs additionally to a c:geo-owned log file, exactly for situations like the current one. Alas, currently we don't have that.

**Comment by Lineflyer** [comment]
These kind of user problems are very rare. So I dont think we need such log file specialty for the time being.

Back to this user problem:
The user told, that he had to deinstall the device from his car as it kind of killed his car (generating system errors on CAN). So I close this.
