### ISSUE TITLE
Very long startup time

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9793]
A user contacted our support mail with this problem (translated, summarized):

---
Since several months I keep having the problem, that c:geo needs more than 30 seconds to get into the main menu after starting it (the splash screen keeps showing during that time).
- It does not happen on each startup but pretty regularly
- It does never happen if I make a fresh install and import my pocket queries (around 5-6k caches)
- It starts to happen once I refreshed the caches online (saving log pictures is switched off)
---

I have recevied settings + DB backup from the user but cannot reproduce the problem on my test devices.
I asked the user to send a log file after this happend, and this is the relevant part of that log:

```
01-12 21:10:59.233  4870  4870 W SQLiteConnectionPool: The connection pool for database '/data/user/0/cgeo.geocaching/databases/data' has been unable to grant a connection to thread 2 (main) with flags 0x5 for 30.000002 seconds.
01-12 21:10:59.233  4870  4870 W SQLiteConnectionPool: Connections: 1 active, 0 idle, 0 available.
01-12 21:10:59.233  4870  4870 W SQLiteConnectionPool: 
01-12 21:10:59.233  4870  4870 W SQLiteConnectionPool: Requests in progress:
01-12 21:10:59.233  4870  4870 W SQLiteConnectionPool:   executeForChangedRowCount started 30002ms ago - running, sql="DELETE FROM cg_logs WHERE geocode NOT IN (SELECT geocode FROM cg_caches)"
```

What is that SQL command used there `DELETE FROM cg_logs WHERE geocode NOT IN (SELECT geocode FROM cg_caches)`, and might it be related to what causes the long execution time, or is it just the first command on startup and for some unknown reason the DB cannot be accessed?

**Comment by rsudev** [comment]
I see sometimes similar behaviour on my device, seems I should take the time to investigate...
Do we have the users system info?

**Comment by Lineflyer** [comment]
Sorry, forgot to attach it:
```
--- System information ---
Device: BV9600Pro (BV9600Pro_EEA, Blackview)
Android version: 9
Android build: BV9600Pro_EEA_S700_V1.0_20190530V8
c:geo version: 2021.01.10
Google Play services: enabled - 20.47.14 (100408-349456378)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide caches: own/found archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE / user-defined language: 
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (53,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (53,3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (53,3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (183,4 MB) on system internal storage
Last backup: 21. Dez. 2020, 22:46
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/oamaps
Map render theme path: /storage/emulated/0/oamaps/themes/Elevate.xml
Live map mode: false
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: d.M.yyyy
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---
```

**Comment by gcPhil** [comment]
> Could this be the same as: [https://github.com/cgeo/cgeo/issues/9308](https://github.com/cgeo/cgeo/issues/9308) ?

I reported this issue by support-mail.

I can not clearly say if it has the same reason like yours. My long startup time appears on the first app-start after starting the device and also if the app had been inactive for some minutes. If the app had been closed only for a short time it don't needs long time, even not after force-closing the app.
But I never get that "Trying to Locate" message and my startup stopps during the orange splash screen (on your screenshot it seems that your message appears later, when the menu icons are already visible). My problem began with an update last year but unfortunately I don't know which version (I remember that it began before the splash screen had been added to c:geo. In the first time I had only the black screen for half a minute where now the splash screen is visible all the time.

**Comment by bekuno** [comment]
The description of gcPhil perfectly describes the situation also for me.
My long start time is around 22 sec (for ~22k saved caches).
On my dev device (same model) I could not yet reproduce, but there I do not have such big number of saved caches.

**Comment by Lineflyer** [comment]
Just to make sure:
Might it be an effect of our housekeeping (i.e. clearing caches from the DB 72 hours after they have been deleted)? Maybe if you delete a large amount of caches it might trigger this 72 hours after?

**Comment by bekuno** [comment]
No, I did nor delete caches the last days.
The long delay startup is not one time per day. It is when not used c:geo for a while and the you (re)start it.
This means, **sometime** you can close c:geo and start it directly then the delay can occure.

**Comment by Lineflyer** [comment]
> On my dev device (same model) 

@bekuno You mean you also have the Blackview device @gcPhil uses?
Could it be specific to some devices?

**Comment by bekuno** [comment]
No, it is at my Samsung Note 8 (Android 9).

**Comment by bekuno** [comment]
I tested on my dev device (also Note 8) with my prod. DB.
Here are the results from two app starts (combined in one log) from the AS logcat.
The first two colums are the seconds from the logged time.

In this part of the start it took 3,2 sec and 10,2 sec.
~~~
 51.362   32.157  D/NetworkSecurityConfig: No Network Security Config specified, using platform default
 51.508   32.290  D/TcpOptimizer: TcpOptimizer-ON
 51.974   32.793  W/cgeo: [main] Chosen extCgeoDir /storage/6363-3661/Android/data/cgeo.geocaching/files is not an available external dir, falling back to default extCgeoDir
 52.178   35.871  W/cgeo: [network--3] ECLogin.login: No login information stored
 52.183   35.871  W/cgeo: [network--2] Login.login: No login information stored
 52.187   35.882  D/OpenGLRenderer: Skia GL Pipeline
 52.193   35.891  D/EmergencyMode: [EmergencyManager] android createPackageContext successful
 52.228   35.940  D/InputTransport: Input channel constructed: fd=80
 52.229   35.941  D/ViewRootImpl@1f88dab[MainActivity]: setView = DecorView@7406cb2[MainActivity] TM=true MM=false
 52.412   36.163  D/ViewRootImpl@1f88dab[MainActivity]: dispatchAttachedToWindow
 54.507   42.288  D/ViewRootImpl@1f88dab[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x7 surface={valid=true 534577942528} changed=true
 54.526   42.305  I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
 54.526   42.305  I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
~~~

I have no idea how/what I can test deeper.

**Comment by gcPhil** [comment]
Is there maybe some kind of apk-archive with that I could test with which version the issue began?

**Comment by bekuno** [comment]
@gcPhil 
You can use the PR from https://ci.cgeo.org/job/cgeo%20pull%20request/
Every job has its own site, eg. https://ci.cgeo.org/job/cgeo%20pull%20request/4612
The apk there are in the form
https://ci.cgeo.org/job/cgeo%20pull%20request/4612/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk
In this way you are able to use also builds which are not in the sidebar list.
The last useable one is now 4113, this means 500 builds back. This was before 1 month 21 days, this is probaly too short.

You can however test with the release apk.
They are found at https://github.com/cgeo/cgeo/tags
It would for sure good to know which release was at first affected.

**Comment by moving-bits** [comment]
Still relevant with the fixes provided for #11227?

**Comment by fm-sys** [comment]
Actually yes, although it already got significantly better...

Most other apps have startup times of around 1-2 seconds, while cgeo needs >5 seconds on my device. I know it's kind of a luxury problem, but still can be quite annoying :)

**Comment by Lineflyer** [comment]
Seems tobe sufficiently fixed (depending on device performance maybe). I di however not get any more similar requests after the changes mentioned above.
