### ISSUE TITLE
[minor] Nightly sign under the page icons

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9797]
If I turn the phone to landscape the banner for the nightly is under the icons. Shouldn't it be on top?
![IMG_20210115_100818](https://user-images.githubusercontent.com/43813636/104705619-6a5a4880-571a-11eb-8f76-f5cf3298ee8b.jpg)

c:geo version: 2021.01.14-NB-b543f8b

**Comment by Lineflyer** [comment]
It is like that, since we introduced the notification system (also for new releases, warnings, etc.).
I can live with that...otherwise we would have to crunch the menu just for that purpose. The user can just turn it to more easily click it.

IMHO we should not put any effort to fix it.

**Comment by SammysHP** [comment]
Maybe we can just move it to the left or right side in landscape view?

**Comment by geocachermgo** [comment]
> ... Placing it on top is no real solution as it probably makes the menus inaccessible.
> 
> IMHO we should not put any effort to fix it.

I just thought it had been a slip of pen and could be fixed easily. A workaround as proposed by Sammy is not necessary in my view.
