### ISSUE TITLE
Integrate base folder selection into configuration wizard

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9808]
This issue is a reminder, that after SAF has been merged to `master`, the selection of a base folder should probably be integrated into the "first startup" wizard.

**Comment by eddiemuc** [comment]
Thank you!

**Comment by eddiemuc** [comment]
@moving-bits I was under the impression you had already done this. Is this the case?

When I put my local base folder back to legacy and restart cgeo the wizard does not show up but only my "old" dialog (which I though would be removed after integration into the wizard). Is this expected?

**Comment by moving-bits** [comment]
> @moving-bits I was under the impression you had already done this. Is this the case?

Yes, see #9906

> When I put my local base folder back to legacy and restart cgeo the wizard does not show up but only my "old" dialog (which I though would be removed after integration into the wizard). Is this expected?

The wizard will only show up automatically on a fresh install. On subsequent runs, the wizard will put a menu entry in the main screen's menu, if installation is incomplete yet.

The wizard uses `ContentStorageActivityHelper.baseFolderIsSet()` to check whether a valid base folder is set. The wizard page for setting a base folder will only be shown if that check returns false.

If that page is shown and the user selects "next", your existing dialog for setting a base folder will be called currently, as I did not want to duplicate code if not necessary, but this (and the dialog itself) may be changed as used.

**Comment by eddiemuc** [comment]
Thanks for clearing this up.

There is no "special" dialog to select the base dir, there is just one dialog to select a directory (same for base, offline-maps, gpx export and maybe later map themes dir). You call this dialog which is perfectly right. Redesign of this dialog will be done via #9872. This is the dialog in question (for base dir) as it is today:

![image](https://user-images.githubusercontent.com/6909759/106392877-26429580-63f4-11eb-82de-5e12ca72f147.png)

I was talking about the SAF-own startup dialog which is currently still popping up (in addition to the wizard) when c:geo is started:
![image](https://user-images.githubusercontent.com/6909759/106392910-43776400-63f4-11eb-8643-6e1fd760a316.png)

This dialog in my understanding is now no longer needed (since the wizard has taken its place). Thus I will remove it, PR will follow. After that in my impression this issue can be closed.

**Comment by bekuno** [comment]
In the first screenshot I can select "Do nothing". 
But then the buttons are false and should be replaced by `close`.

**Comment by eddiemuc** [comment]
> In the first screenshot I can select "Do nothing".
> But then the buttons are false and should be replaced by `close`.

Hi @bekuno the "do nothing" selection refers to what should happen with content of old folder ("source") when the folder is changed (whether it should be copied or moved or nothing should be done on folder change). The folder can still be changed while the content of the old folder is not touched (moved or copied) to the new one.

But I know that UX is currently crappy in this dialog. This is handled in #9872, I would be honored if you leave your suggestions there how to make this better (there is already a lot of suggestions there)

**Comment by eddiemuc** [comment]
PR #9926 is out

**Comment by moving-bits** [comment]
> I was talking about the SAF-own startup dialog which is currently still popping up (in addition to the wizard) when c:geo is started:
> ![image](https://user-images.githubusercontent.com/6909759/106392910-43776400-63f4-11eb-8643-6e1fd760a316.png)
> 
> This dialog in my understanding is now no longer needed (since the wizard has taken its place). Thus I will remove it, PR will follow. After that in my impression this issue can be closed.

IMHO this dialog (and the check leading to it) should be kept, as people may skip the wizard (which will pop up on fresh install only, anyway) and should get a reminder. Also it's necessary for people migrating from today's c:geo to the SAF enabled.
If people have already selected a base folder using the wizard, the dialog will not pop up, so everything should be fine, then.

**Comment by moving-bits** [comment]
Or different approach: We could make the installation wizard pop up on startup if no base folder is set - then we could remove the dialog above.

May be a neat way to show the wizard to all existing users, maybe pointing them to features like BRouter etc.?

**Comment by eddiemuc** [comment]
> Or different approach: We could make the installation wizard pop up on startup if no base folder is set - then we could remove the dialog above.
> 
> May be a neat way to show the wizard to all existing users, maybe pointing them to features like BRouter etc.?

I would personally prefer this. Actually I thought up to today that it is already implemented this way, also for other necessary checks (like storage access permission)

**Comment by moving-bits** [comment]
Ok, I'll prepare a PR for this (base folder checking).

Need to think about the other parts of the wizard, though, as it asks / presents more than the necessary things. Maybe it's better to leave it as today for the other checks, with on-demand requests for storage/location permission to not bug the user on each startup.
