### ISSUE TITLE
More precise info on login page (related to config wizard)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9818]
While testing the configuration wizard flow with a half-muggle he stumbled upon the following:

The wizard guides you very good until the point where you will be directed to the c:geo login page for geocaching.com during the process. The user had two remarks here:
- The text on the login page (Filling your credentials and pressing "Check authentication"...") could have bigger text, be more precise and shorter at the same time. Example: "If you already have an account please enter your account credentials below"
- The create account button should be prepended by an explanation and be visually separated (by that). In fact quite some explanation is needed in that case. Most importantly the user created an account using "Login with Google" which at the end made him unable to authenticate in c:geo. Furthermore the user needed to validate his mail address in the welcome mail from geocaching.com before he could later login with c:geo.
So the explanatory text here should be something like "If you do not yet have an account click below to be directed to the geocaching.com webpage to create an account. Make sure to use the method with username and password to create an account as c:geo does not support login via Google/Apple/Facebook. After account creation validation of your mail address might be needed before you can user the login with c:geo".

The long explanation is not the most user-friendly thing, but I guess we cannot solve it in a better way.

**Comment by eddiemuc** [comment]
I stumbled upon "c:geo does not support login via Google/Apple/Facebook". Would this be a wanted new feature from User-Side?
(I personally don't need this but maybe others)

**Comment by Lineflyer** [comment]
I don't think so. The "problem" is, that the geocaching.com register page we link to in case of "Create an account" offers these methods most prominent and you have to scroll down to get to the legacy login with username/password.

**Comment by moving-bits** [comment]
> While testing the configuration wizard flow with a half-muggle he stumbled upon the following:

This configuration wizard jumps into our regular service settings at this point, so if I do changes here for the wizard, they will be visible in the settings as will. Would that be ok?

**Comment by Lineflyer** [comment]
> This configuration wizard jumps into our regular service settings at this point, so if I do changes here for the wizard, they will be visible in the settings as will. Would that be ok?

I think so. Users might skip the wizard but still might need a better guidance to get the login done.
Looking at how many users registered to the user guide wiki or send2cgeo thinking they can register for "Geocaching" there, I think we have room for improvement for the unexperienced users.
Due to covid it seems we currently experience a high first user rate...looking at the amount of "How does it work at all?" mails I receive on support.

**Comment by moving-bits** [comment]
@Lineflyer 
see #9841 (with screenshots)
