### ISSUE TITLE
Deactive routing settings (or guide user) if brouter is not installed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9819]
Since we have the quick settings out on the market, it seems many users like it and use it.
Anyway since then also some users complaint came in like "I selected bike but it still shows the straight line. Why is that?". It turned out those users did not have brouter installed.

Indeed those settings are shown despite brouter being not installed on the device.
The easy solution would be to hide these settings completely in that case. The better solution would be to grey out all options except "straight line" and when the user clicks on another option to inform him, that he needs brouter to use that feature (ideally with link to the app and/or to the user guide).

**Comment by fm-sys** [comment]
Let's leave the routing settings inside the popup as an advertisement for brouter, which is currently a very cool but unknown feature. The link will direct the user directly to the playstore...

![grafik](https://user-images.githubusercontent.com/64581222/105001253-c4675080-5a2f-11eb-9d7f-383116d8f474.png)

**Comment by fm-sys** [comment]
Fixed with #9823
