### ISSUE TITLE
Found marker vanishing on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9833]
Two independent user reports for 2021.01.16 with following effect:

- Found caches set to not be hidden on map
- Login OK for both users, both users are PM (if that makes a difference...)
- Found marker of found unsaved caches vanish while using the live map (cache shown as unfound)
- According to both users it happen quite often but not clearly reproducible

Might be related to latest fixes/changes or might also be an issue of the live map of gc.com not properly setting the found state?!

**Comment by fm-sys** [comment]
I'm afraid, this is caused by #9542. Let's see what I can do here...

**Comment by fm-sys** [comment]
Ok, I checked but #9542 is definitely unrelated. 

Did the users have logged the caches from outside c:geo? If yes, the GC website is just slow again... 
There is a comment in the code that confirms this phenomenon. AFAIK there is nothing we can do here. If caches get logged from outside c:geo it takes some time (sometimes faster and these days apparently much slower) until the found state is available via the live map webAPI we use. 

https://github.com/cgeo/cgeo/blob/d6dbe15d6997a56eccfe681458f0b09356097074/main/src/cgeo/geocaching/connector/gc/GCMap.java#L157-L158

**Comment by Lineflyer** [comment]
Both users reported it happens for them on GoogleMaps, both are not sure, whether it happens on OSM as they mainly use GM.

**Comment by Lineflyer** [comment]
I will ask regarding "found delay".

**Comment by Lineflyer** [comment]
Two more users plainly reporting, that found caches suddenly appear as unfound in c:geo (might or might not be related to map). Also affecting caches found weeks ago.

I am still clueless what might happen here...all users stated it first appeared either starting with 2021.01.16 or coincidently timely related to that release.

I deactivated hiding of found caches to try to reproduce...

**Comment by Lineflyer** [comment]
> Two more users plainly reporting, that found caches suddenly appear as unfound in c:geo (might or might not be related to map). Also affecting caches found weeks ago.

The reports of those two users had another reason. They saved the cache on one device and logged them on another.

Still waiting for feedback of the first reporting users if it can be connected to the live map "found delay".

**Comment by Lineflyer** [comment]
The first reporting user was able to sort it out, respectively it does not happen anymore (maybe it was the delay on map).

However one point remains for that user, which occurs from time to time:
- Cache is shown as found on live map (smiley)
- Cache is shown as found when opening details (smiley + found state)
- But: Cache popup on map is inconsistent: Found state is shown but smiley missing in popup

![grafik](https://user-images.githubusercontent.com/949669/105717429-669ba280-5f20-11eb-91d9-238e6a2d88bc.png)

Any idea where this inconsistency might come from?

**Comment by fm-sys** [comment]
> Cache popup on map is inconsistent: Found state is shown but smiley missing in popup

This was always the case for a long time, was solved by one of my recent PR (don't know the exact number) and should be in the current beta phase...

**Comment by Lineflyer** [comment]
> This was always the case for a long time, but was solved by one of my recent PR's (don't know the exact number) and should be in the current beta phase...

Perfect. That explains. So I will close this issue unless we have more such reports. But at the moment this is not the case.
