### ISSUE TITLE
[minor] Wrong waypoint numbering

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9834]
**Describe the bug:**
A waypoint with a number in the name leads to additional waypoint 

**To Reproduce:**
1. Create waypoint with number as name beginning
2. Create new waypoint

**Actual behavior/state after performing these steps:**
New waypoint gets inrcemented as index

**Expected behavior/state after performing these steps:**
It should be recognized that the number is not an index and in this case the index should be empty or 1

**Version of c:geo used:**
2021.01.20-NB-fd6b88b

**Is the problem reproducible:**
Yes

**Screenshots:**
![IMG_20210120_175937](https://user-images.githubusercontent.com/43813636/105209445-1ef4cf80-5b4a-11eb-9622-e7a9e49ede18.jpg)

**Additional context:**
The number was a bearing. I also checked with another cache. I created a waypoint 123 and then a new marker that was named "Markierung 124"

**Comment by moving-bits** [comment]
How can c:geo detect such a situation reliably?

Current implementation for waypoint numbering works like this:
- set variable temp to 0
- for all waypoints of a cache (of whatever type)
  - scan waypoint name for numbers [may be multiple findings within a name]
  - if found, set temp to max(temp, found value)
- new waypoint gets the number temp + 1

**Comment by geocachermgo** [comment]
E.g catch only numbers at the end or better
catch only numbers immediatly after the waypoint keywords [Markierung, Parken, ..] ?
I think the main idea was that if you have several created waypoints they have different names.

**Comment by moving-bits** [comment]
The difficult thing is that our users may have very distinct use cases, and very distinct data.

> E.g catch only numbers at the end or better

That was my proposal initially, but @MagpieFourtyTwo convinced me of other use cases which would conflict with that.

> catch only numbers immediatly after the waypoint keywords [Markierung, Parken, ..] ?

Generally possible, although we would have to catch the old naming and the new naming, as there may be waypoints created before our name change. But that would not catch imported waypoints with a different naming scheme or language.

I think there is no general purpose way of detecting "the" number to use (or the ones to ignore), which would fit for all users and all their individual use cases.

Currently we catch all numbers, whereever in the name they might be. That's at least consistent and easy to understand for our users, IMHO.

**Comment by MagpieFourtyTwo** [comment]
> It should be recognized that the number is not an index and in this case the index should be empty or 1

Question is, as @moving-bits already stated, how to distinguish between "normal" numbers and "real" indexes.
Which turned out to be simply impossible. Esp. as the algorithm has to be understandable by John Average ...

"Just numbers at the end" sounds good on first sight, but WP names oftenly get an explaining keyword added,,
like "Stage 1 - Cat", "Stage 2 - Tree" and so on.  In these cases, "last number only" will fail completely.

My suggestion was, to just look for the *first* occurring number (ignoring foll. text),
which would most probably cover most use cases, esp. as the default is "Stage 42" anyway
and the ones I know just add text - but this solution would fail in your example, too.

To keep things simple and most comprehensible, we finally agreed to just use the highest number.
Which additionally seems to be the most intuitive solution.

**Comment by geocachermgo** [comment]
I thought it's only necessary to have the correct sequence of automatically c:geo generated waypoints.
Another idea: how to use the number of waypoints as a base? So if you have 7 waypoints the next one will get the index 8?
(Just as a reminder: I think it is a minor bug, so if we dont find a better solution we can just leave it the way it is)
Fun fact: if you choose 2147483647 (2^31-2)
The following waypoints names are Markierung -2147483648

**Comment by MagpieFourtyTwo** [comment]
> Another idea: how to use the number of waypoints as a base? So if you have 7 waypoints the next one will get the index 8?

Sounds good, too, but most regretfully it's again not that easy: WP count does not always start with 1, sometimes listing or parking coords are counted as S1, sometimes reference points are counted as stage, sometimes not ... then there are physical ("Stage x") and non-physical stages ("Question to answer", "Vias" aka "Trailheads" and "Reference points") ... if the CO has a different logic, stage numbers get out of sync with count (remember, there are CO- *and* user defined WPs of the same type living together, which may or may not count into the stage numbering, depending of their context) - and in these cases you may even get double names or default stage numbers that are way to high or way to low ...

**Comment by geocachermgo** [comment]
I agree that it's Impossible to always get the index correct (=as the user wants it) but I would prefer the number of actual waypoints over the current solution with the problem of getting ridiculous indices e.g. when you have a bearing, street number, coordinate or a float (e.g. 3.1415926) within a WP name.
An advantage of the current solution is (as long as no 10 digit number is involved) that a clever user can set the counting start by a dummy higher number waypoint. So in my original example I could create a waypoint named 1000 and would get 1001, 1002 as subsequent indices afterwards, to repair the wrong interpretation of the bearing as an index.
Maybe we could have a keyword waypoint like "shift waypoint index ###" that will shift the waypoint index by ### (including negative numbers)?
Then you could ramdomly change the indices of new waypoints.
Or mark a number as special for the indexing. But I have at the moment no idea to get a solution from that.

Of course if we stay with the current solution, my new cache will include a parking spot 2147483647 to create the negative and identical suggested index for all new waypoints. :-)

**Comment by geocachermgo** [comment]
For the current solution I would suggest to ignore all numbers bigger than 10100. This will give you the possibilty to start a new sequence at 100 and 1000 and 10000 of up to 100 waypoints which should be sufficient.

**Comment by moving-bits** [comment]
> For the current solution I would suggest to ignore all numbers bigger than 10100. This will give you the possibilty to start a new sequence at 100 and 1000 and 10000 of up to 100 waypoints which should be sufficient.

Looks like a reasonable workaround to me (although there may still be some edge cases, depending on CO's or users' creativity ;-)

**Comment by MagpieFourtyTwo** [comment]
Perhaps something went wrong while implementing this "enhancement" (still not sure about the benefit, cause the 10k-stuff is a very special use-case and not really intuitive), cause this morning ``Parking 1`` suddenly counted into the ``Stage n`` numbering, i. e. got ``Stage 2`` as first one, although we wanted to leave ``Parking`` out when calculating the next number for ``Stage``, ``Question to answer``, ``Reference Point`` or ``Trailhead`` ... IIRC ... or am I wrong?

**Comment by moving-bits** [comment]
Nothing changed with the tiny update in that regard. I need to cross-check in the source which types are currently excluded from numbering.

Can you provide me a short list which types _should_ be excluded? Thx.

**Comment by fm-sys** [comment]
IMHO we should rather cound only these waypoints, which have a number...

So if we have 5 references points and one of them is named "reference point 1" and all other do not contain any numbers, the next one should be named "reference point 2"

**Comment by MagpieFourtyTwo** [comment]
> Can you provide me a short list which types should be excluded? Thx.

Opinions seem to differ, but for me, there are just two that should not count: ``Parking`` and ``Final``.

**Comment by MagpieFourtyTwo** [comment]
> IMHO we should rather cound only these waypoints, which have a number...

This is the case, anyway.
"Problem" is, that WP type ``Parking`` gets a number by default, too, even if it's the only one.

**Comment by MagpieFourtyTwo** [comment]
Sometimes WP names contain the GC-Code like "GC42ABC Parking" - which currently leads to the next WP named ``Stage 43`` ...

**Comment by geocachermgo** [comment]
> bearing, street number, coordinate or a float (e.g. 3.1415926)

, GCcode, ...
 I am curious how the users will like it. I'm still not happy with it, but found no convincing solution yet.

**Comment by moving-bits** [comment]
A solution to both could be to check not only for a sequence of digits, but for one which must be either
- at the beginning or end of the wp name,
- preceeded by a space,
- or followed by a space

Or should be check for space (or name boundary) on both ends?
Something like `[^| ]([0-9]+)[ |$]`? (not tested)

**Comment by geocachermgo** [comment]
Yes this should eliminate GCcode, floats.
But it would handle "Stage 1 Tree" different to "Stage 1-Tree"

**Comment by MagpieFourtyTwo** [comment]
Therefore I would add ``"-"`` and ``"_"`` to the typical word boundaries (usually ``"\b"``, but depends on flavor),
i. e. s/th like ``"[\b-_]\([\d]+\)[\b-_]"``, perhaps bracketed by a ``"^"`` and ``"$"`` plus some ``"^[\d]"``,
depending on if you want to get the first or last number sequence
(while I would still vote for the first occurring number, as ``"<WPtype> <n>"`` is the default, anyway, and in most cases guys just add some stuff to the end of line, as it's the least effort).

**Comment by Lineflyer** [comment]
I don't want to interrupt the discussion about optimizing this behavior, but:
1. Please better open a new issue for the remainder of follow up problem of the original issues solution (That was the reason why I did not even see the discussion up to now).
2. Please kindly consider before building even more background intelligence, how many users it will actually be helpful for and for how many users a good working implementation will change unexpectedly (I do not mean the optimization only but also the new feature in general). Sometimes I think we try to fix things which are not broken and replace well understandable mechanisms by background magic, which some users might neither understand nor need. I won't block or be against this, but IMHO this is much effort for only little improvement (if any).

**Comment by moving-bits** [comment]
Created #9871 for the remaining issues.
