### ISSUE TITLE
Waypoint of DNF caches hidden when hiding of found caches is active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9844]
From support mail for 2021.01.16 and confirmed by testing:

- Have a stored cache with following status:
  - You posted a DNF log for it (blue smiley on map)
  - The cache has an additional waypoint
- View this cache on live map
- Disable "Show own/found caches" in map quick settings

Result:
- Cache still shown (correct)
- Waypoint of the cache gets hidden (Error)

**Comment by fm-sys** [comment]
Interesting though: For me, this happens only for user-created waypoints. Can anyone confirm this?

**Comment by Lineflyer** [comment]
In my case it was (kind of) a user defined waypoint, a "Original coordinate" for a solved mystery.

**Comment by fm-sys** [comment]
OK, I found the reason for it. PR follows soon...
