### ISSUE TITLE
Unused strings after merge of SAF

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9860]
Looking on Crowdin I have seen some strings which have been removed before but reappeared (maybe due to previous conflict resolution):

settings_summary_scale_map_text
settings_title_scale_map_text

These should IMHO be no longer used.

**Comment by eddiemuc** [comment]
Sorry, probably an unwanted leftover of my many merge sessions...

**Comment by Lineflyer** [comment]
no need to say sorry....that happens while merging such huge branches.
I just wanted to report it as I found it coincidentally.
