### ISSUE TITLE
"Check updates" button not shown in map downloader

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9862]
(Probably related to SAF changes, but need to debug into it)

---

_Taken from https://github.com/cgeo/cgeo/issues/9851#issuecomment-767128749 by @moving-bits:_

[...] Actual map selection & downloading works smooth, and the map gets selected and displayed - great! [...] 

One thing does not work, though: The upgrade detection. I guess it's the `OfflineMapUtils.availableOfflineMaps()` method not returning the map companion files for downloaded maps, but need yet to debug into it.

The update button in the map downloader will get displayed only when there are map companion files for maps downloaded through the downloader, and the files referenced from within the companion file still exists. I have tested downloading a new map after the SAF upgrade: The companion file got created, but the "check updates" button still did not get displayed - neither for the old map files nor for the new one.

I'll try to debug into it the next days.

[...]

**Comment by eddiemuc** [comment]
Hard to tell w/o looking into code, but iirc I return only files ending with `map` in the `availableOfflineMaps` method. So this could indeed  the reason.

**Comment by moving-bits** [comment]
This is the code (taken from utils/OfflineMapUtils.java):

```
final List<ContentStorage.FileInformation> mapDirContent = ContentStorage.get().list(PersistableFolder.OFFLINE_MAPS);
final Map<String, Uri> mapDirMap = new HashMap<>();
for (ContentStorage.FileInformation fi : mapDirContent) {
    mapDirMap.put(fi.name, fi.uri);
}
for (ContentStorage.FileInformation fi : mapDirContent) {
    final String filename = fi.name;
    if (!filename.endsWith(INFOFILE_SUFFIX)) {
        continue;
    }
    try (InputStream input = new FileInputStream(new File(filename))) {
        ...
    }
}
```

I'll debug into it to see what's happening here.

**Comment by eddiemuc** [comment]
That's strange. Can't dive into this currently, please keep me updated on what you find out

**Comment by moving-bits** [comment]
> That's strange. Can't dive into this currently, please keep me updated on what you find out

Will do

**Comment by moving-bits** [comment]
Only a tiny change seems to be necessary:

Change from 
`try (InputStream input = new FileInputStream(new File(filename))) {`
to
`try (InputStream input = ContentStorage.get().openForRead(PersistableFolder.OFFLINE_MAPS.getFolder(), filename)) {`

First tests look promising, I'll provide a PR.

**Comment by eddiemuc** [comment]
Damn I should have spotted that in the code piece you provided. You are right, that should fix it

**Comment by moving-bits** [comment]
No problem, was easy to fix thanks to the neat documentation of `ContentStorage` class! Just needed a time slot to fire up my debugger.
