### ISSUE TITLE
Use numbered variables for SAF strings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9864]
A contributor on Crowdin (in this case for Japanese) mentioned, that e.g. the string `contentstorage_err_create_failed` is hard to translate for him as his languages requires to use the placeholders/variables in a different sequence. This might apply also to other languages. 

Is it possible to give them a numbering (instead only `%s` -> `%1s` `%2s`)?

Edit:
Might apply for all strings which use more than one variable.

**Comment by eddiemuc** [comment]
It is already possible to use numbered parameters (this is called "argument index" in Java). See here: https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html Format is e.g. like this: `%2$s` (references second parameter, format as string). Also `<` can be used to reference "next" parameter.

If no explicit argument indexes are given (like in my default translations), the formatter assumes that the variables are indexed in the order in which they are provided in the string. But other translations may use indexes as they please.

So what is requested should already be possible. Or am I misunderstanding something here?

**Comment by Lineflyer** [comment]
I am not so deep into that numbered parameters, however when I do translations on Crowdin for other projects they are mostly already numbered in the source, which makes it easier to reuse them in my translated strings (without having to know how I could force them).

Example Source : "File %1$s is stored in folder %2$s"
Translation (weird example): "Im Ordner %2$s ist die Datei %1$s gespeichert"

**Comment by bekuno** [comment]
Not using number values should be already a lint error.

To make it easy for you in strings.xml you can always use the numbered form, also when only one parameter is used.

**Comment by bekuno** [comment]
> Might apply for all strings which use more than one variable.

change to: Must apply ...

**Comment by fm-sys** [comment]
> > Might apply for all strings which use more than one variable.
> 
> change to: Must apply ...

On the other hand changing all strings would lead to high retranslation effort. But we can definitely introduce this rule for all new strings

**Comment by bekuno** [comment]
> On the other hand changing all strings would lead to high retranslation effort. But we can definitely introduce this rule for all new strings

To clarify: A rule for more than 1 entry is already active. Here it is a error not to use positional parameters. So only some strings from the SAF PR should be affected.
Changing this for all strings is of cause no good idea. But it is a possibility for new/changed strings.

**Comment by Lineflyer** [comment]
> A rule for more than 1 entry is already active. Here it is a error not to use positional parameters. So only some strings from the SAF PR should be affected.

But we have strings with more than one `%s` in it. Why did the lint check not fail in this case?

**Comment by eddiemuc** [comment]
I believe this is done now. Can this be closed? Or is there still something left to do here?

**Comment by bekuno** [comment]
It is fine now.
