### ISSUE TITLE
Optimize waypoint numbering

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9871]
A followup to #9834, summarizing the current state of discussion (at least I hope I gathered everything):

- exclude single wp of type "parking" from auto-numbering (same as with wp type "final")
- check sequences of digits for specific boundaries:
  - beginning / end of line
  - word boundary characters ("\b"?)

  (to avoid GC-codes etc. to be included in numbering)
- additionally, for wp types "final" and "parking" only: those two should stay with the old wp type-specific numbering, starting from second wp of its type: First wp of type parking will be named "Parking", 2nd of this type "Parking 2", next "Parking 3" etc. (Same with wp type "Final")

@MagpieFourtyTwo @geocachermgo feel free to add if anything relevant's missing.

I'll prepare a PR against `release`.

**Comment by MagpieFourtyTwo** [comment]
In addition to common word boundaries I would add "_" and "-" as valid separator, too.

**Comment by moving-bits** [comment]
Detected during implementation that "word boundaries" do not work here, as a "." will be considered a word boundary, which would break the "3.1415" example.

I've implemented the following regex for now: `(^|[-_ ])([0-9]+)([-_ ]|$)`, meaning, that a sequence of digits has to
- be either at the name's beginning or be preceded by space, "-" or "_", and
- be either at the name's end or be succeeded by space, "-" or "_".

See #9897.
