### ISSUE TITLE
No way back to previous level in cache details menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9873]
Two beta users contacted us on support mail:
Both are more or less neutral regarding the changes in the cache detail menu (still discussing with them and maybe opening other issues for that), but at least both remarked the following:

Whenever I try to find the function I need and e.g. open the "share /export" submenu I do not see how I can go back one level without completely closing the menu and starting from zero.

Thats IMHO a valid point and I can reproduce this. Doesn't Android offer any back navigation in here to return to the upper menu level instead of dismissing the whole thing?

**Comment by moving-bits** [comment]
AFAIK this is standard menu behavior in Android. And at least during a quick search a couple of days ago, I haven't found a way to prevent this, but I haven't dived into that very deep yet.

**Comment by Lineflyer** [comment]
Don't we already have a menu with this step-back behavior. Need to check.

**Comment by Lineflyer** [comment]
No, we don't have.
Lets see what you can find out. If that would need any tricky custom implementation, we should just close here. It was just an idea brought up by a beta user.

**Comment by fm-sys** [comment]
In Meienr's opinion, we should not invest any time in this. Honestly, it would be rather annoying if you don't close the menu with a click outside / back button but just go one step back. I don't know of any app that behaves like that, and Android has good reasons why the UI elements are designed like they are.

**Comment by Lineflyer** [comment]
OK, then lets just close here.
@moving-bits Feel free to reopen if you happen to find another solution.
