### ISSUE TITLE
Explore state of using external GPS receiver with c:geo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9877]
Over some months there have been 4-5 users on support mail suddenly experiencing problems with using an external bluetooth GPS receiver with c:geo after it worked previuosly.
None of them could relate it to a certain c:geo version, however one user stated that it might have started after upgrading his device to Android 10.

Up to our last information it should work like this:
- Install the "Bluetooth GPS" app (as listed in our useful apps)
- Configure the app and connect device (enable mock gps provider)
- Disable Google Play Services in c:geo

This seems to have stopped working, it might be related to Android 10 and above , as"Bluetooth GPS" seems not to be maintained since a long time. Maybe there is something here no longer compatible?

One user reported, that it actually worked again after **enabling** GooglePlayServices in c:geo but it might be a wrong reporting...not sure.

I don't own such a device, does someone use such device ( AFAIK @rsudev used it some years ago)?

**Comment by Lineflyer** [comment]
Note to myself:
According to some customer feedback on Amazon for the "Garmin Glo" device, the users got it working by using https://play.google.com/store/apps/details?id=com.clearevo.bluetooth_gnss instead of "Bluetooth GPS".

**Comment by eddiemuc** [comment]
Teammeeting 19.11.23: according to last comment a solution was found. Therefore closing here. Feel free to reopen if issue is still relevant.
