### ISSUE TITLE
Action items on list selection no longer in one line

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9879]
Reported for 2021.01.24-RC and reproducible for me also in 2021.01.24-NB1

- Open map
- Tap unsaved cache
- Hit save icon in popup
- List selection dialog is shown

Result:
The "OK" / "Cancel" / "Last selected" have line breaks each which leads to a unnecessary scrollable view and not all items are visible and usable instantly.

![grafik](https://user-images.githubusercontent.com/949669/105972534-01fd5680-608c-11eb-98f8-877e4d8e3466.png)

Expected Result:
Have all items in one line

**Comment by MagpieFourtyTwo** [comment]
WFM.
Is it possible that the line break depends on the longest list name in the list?
I. e. if your longest list name is to short, the line break happens?
Or does the list popup already fill nearly all of your screen (horizontally)?

**Comment by fm-sys** [comment]
I can reproduce this. The three buttons do not fit horizontally side by side. However, you are right that the three buttons should be always visible, so no scrolling would be necessary...

**Comment by Lineflyer** [comment]
What changed?
IMHO we had this problem once and solved it by better fitting all three items into the line.

**Comment by moving-bits** [comment]
I can't remember any specific change triggering this.

But anyway, it seems to be sort of device-specific - here a screenshot from an API 30 emulated device:
![image](https://user-images.githubusercontent.com/3754370/106656201-a7d42800-659a-11eb-9be1-1daed254b88e.png)
(Tested both English and German)

Do we have more information on what setting triggers this behavior?

**Comment by Lineflyer** [comment]
Reproducible for me on my Samsung Galaxy S20, Android 11 (german)

**Comment by Lineflyer** [comment]
Addition:
If I reduce my system font size to real minimum, it fits in one line. But that does only show that it depends on each and every device.

Still we could optimize IMHO, because as soon as it happens I always get three lines like this:
OK
Abbrechen
Letzte Auswahl

At least two of those should fit in most cases.

**Comment by eddiemuc** [comment]
I assume if we want to stay in full control of this behaviour we have to replace all `AlertDialog` Usages in cgeo with some custom dialog.

**Comment by moving-bits** [comment]
> I assume if we want to stay in full control of this behaviour we have to replace all `AlertDialog` Usages in cgeo with some custom dialog.

Or at least need to defined our own layout for the button section. Just don't know how... (I remember having searched for it already the last time this showed up.)

**Comment by MagpieFourtyTwo** [comment]
Would it be possible to (first) line wrap "Letzte Auswahl"?

**Comment by moving-bits** [comment]
> > I assume if we want to stay in full control of this behaviour we have to replace all `AlertDialog` Usages in cgeo with some custom dialog.
> 
> Or at least need to defined our own layout for the button section. Just don't know how... (I remember having searched for it already the last time this showed up.)

So far I have found no way to specify our own button panel layout (though there is some internal method in `AlertDialog`), so I guess it's not possible without creating our own dialog from scratch.

**Comment by Lineflyer** [comment]
Any idea what might have changes between 2021.01.16 and now causing it to appear on more devices?

**Comment by fm-sys** [comment]
Have we changed the strings or translation for this dialog? In which languages does the problem occur?

**Comment by eddiemuc** [comment]
In released version (2021.01.16) I notice that the three buttons are not orange but white. Also the text is Upper-Lowercase in release whereas in screenshots above it is All-Capital-Letters (which might take more horizontal space). Was there some design change inbetween which might have triggered this behaviour?

**Comment by eddiemuc** [comment]
![Screenshot_20210206-182719.jpg](https://user-images.githubusercontent.com/6909759/107125265-0a823800-68a9-11eb-960a-ecb18ed95005.jpg)

**Comment by moving-bits** [comment]
I've noticed a difference in `StoredList.java` between `promptForMultiListSelection(...)` and `promptForListSelection(...)`: The first one uses `Dialogs.newBuilder(activity)`, whereas the latter still uses `new AlertDialog.Builder(activity)`.

The first one got changed relatively recently with e9c5e7e5e8, so this _may_ be the cause. (Although generally using the `Dialogs.newBuilder(activity)` is the right thing to do. Maybe we just need to adjust the styling behind that, to use smaller padding/margins.)

Can someone, who experienced the button stacking, cross-check whether button stacking also appears on single list choice? (It's triggered in "copy to list" and other places.)

**Comment by Lineflyer** [comment]
> Can someone, who experienced the button stacking, cross-check whether button stacking also appears on single list choice? (It's triggered in "copy to list" and other places.)

You mean copy a cache to another list? This has no ok/cancel as you just select one list.

**Comment by moving-bits** [comment]
> > Can someone, who experienced the button stacking, cross-check whether button stacking also appears on single list choice? (It's triggered in "copy to list" and other places.)
> 
> You mean copy a cache to another list? This has no ok/cancel as you just select one list.

Hm. I was coming from the source code, looking where this method gets called.
Seems this variant has no buttons at all...

So, alternatively, I could create a variant for `promptForMultiListSelection(...)` using the old theming, for testing purposes only.

**Comment by fm-sys** [comment]
> The first one got changed relatively recently with [e9c5e7e](https://github.com/cgeo/cgeo/commit/e9c5e7e5e80831faa49bdc2038cd9c9eb0b7a414), so this _may_ be the cause. (Although generally using the `Dialogs.newBuilder(activity)` is the right thing to do. Maybe we just need to adjust the styling behind that, to use smaller padding/margins.)
> 
> Can someone, who experienced the button stacking, cross-check whether button stacking also appears on single list choice? (It's triggered in "copy to list" and other places.)

Yes, thank unfortunately the reason. In e9c5e7e I aligned the styling of the multi-selection dialog to our theming. But we should edit our theming instead of reverting the commit...

**Comment by Lineflyer** [comment]
Some users on support mail with 2021.02.14 having this problem.
For some users the OK seems vanished as they do not clearly see, that they maybe scroll down the lower part (or the scrolling does not work?):

![grafik](https://user-images.githubusercontent.com/949669/108623194-f1978c00-743d-11eb-874b-7cc818e94dc7.png)

**Comment by Lineflyer** [comment]
More users with this problem and they even see a change from January version to February version:

---

Hallo, seit dem letzten Update wird in der Liste zum Speichern der Geocaches nur noch die Möglichkeit "Letzte Auswahl" und "Abbrechen" angezeigt. Die Taste "OK" ist unerreichbar außerhalb des Bereichs.
Dabei ist es inrelevant ob ich das Handy hochkant oder Landscape halte. Siehe auch die Sreenshots im Anhang.
In der Januar-Version waren diese noch, mit "OK" ganz oben, untereinander angeordnet und scrollbar.

**Comment by MagpieFourtyTwo** [comment]
What surprised me a little: In the very first screenshot the order was:

```
OK
ABBRECHEN
```

and in the others it's 

```
LETZTE AUSWAHL        ABBRECHEN
```

I am not completely in the subject, thus sorry if I'm just Captain Obvious right now, but how come?
While ``OK`` being in the last row is easy to comprehend (due to wrap), an ``OK`` in the first still surprises me ...

However, what about a quick fix, and just omit the ``AUSWAHL`` resp. ``SELECTION``?
This may not be as clear as it should be, but would make it at least usable again until a final solution is found?

**Comment by MagpieFourtyTwo** [comment]
Or just drop the ``LAST SELECTION`` button completely for the time being,
as this is (at least over here) a pretty rarely used function, anyway.

**Comment by eddiemuc** [comment]
> What surprised me a little: In the very first screenshot the order was:
> 
> ```
> OK
> ABBRECHEN
> ```
> 
> and in the others it's 
> 
> ```
> LETZTE AUSWAHL        ABBRECHEN
> ```

This is not c:geo-developed behaviour. In this place (like in many others) we use the Android predefined `AlertDialog`. You can assign up to three buttons to this dialog:
* A "positive" button (OK)
* A "negative" button (Abbrechen)
* A "neutral" button (Letzte Auswahl)

Then the system in its wisdom decides how to arrange these buttons. It seems that it decides to place them in the order neutral-negative-positive in case they fit in one line, and in the order positive-negative-neutral with one line each if not. At least this is what I conclude from the screenshots

**Comment by murggel** [comment]
> Or just drop the ``LAST SELECTION`` button completely for the time being,
> as this is (at least over here) a pretty rarely used function, anyway.

I use this button often - but probably the last used list can be (additionally to the normal position in the list) sorted to the beginning of the list? That would have the advantage that I could see the name of the last used list...

**Comment by MagpieFourtyTwo** [comment]
What if - instead of the ``Last Selection`` button - c:geo would act a little bit more offensive,
thus already starts the dialog with the last selection active,
with these selections - as usual - sorted to the beginning of the list?

@murggel 
> "(additionally to the normal position in the list)"

I would not list an entry twice, for two reasons:
1. this would be different to the normal behavior, e. g. when editing the current list membership.
2. if e. g. you previously have selected two lists, and these are accidentally the first two of your list of lists,
    then they will appear doubled and - contrary to what you expect - there are seemingly 4 lists selected instead of 2 ...

At least me would feel more confused than informed ... ;)

**Comment by murggel** [comment]
> What if - instead of the ``Last Selection`` button - c:geo would act a little bit more offensive,
> thus already starts the dialog with the last selection active,
> with these selections - as usual - sorted to the beginning of the list?

That would be fine for me too, did not thought about multiple selection.
But I don't know if preselected will be good - if I want to store it on a different list, I have to deselect it first ...

**Comment by eddiemuc** [comment]
> What if - instead of the `Last Selection` button - c:geo would act a little bit more offensive,
> thus already starts the dialog with the last selection active,
> with these selections - as usual - sorted to the beginning of the list?

I like this idea!

**Comment by Lineflyer** [comment]
> But I don't know if preselected will be good - if I want to store it on a different list, I have to deselect it first ...

But that would be a one time need as for the next saving you would have the new "last selected" then.

Or we keep anything as is but just offer plenty more rooms for the (up to three) selections shown. The only drawback would be less space for lists, so a user with many lists would need to scroll.

**Comment by MagpieFourtyTwo** [comment]
> Then the system in its wisdom decides how to arrange these buttons.

Ok, so not even the order of the button can be influenced ...
Just skimmed https://developer.android.com/reference/android/app/AlertDialog a bit.
Seems as if this is just another not so clever "clever automatism", as it that lacks the possibility to override it.

Another chance for keeping the ``Last Selection`` button could be to limit the length of the button texts,
which are passed to ``setButton(DialogInterface#BUTTON_NEUTRAL, ...)``, perhaps depending on screen resolution ...?
Or just cut at the blank ... ``Last`` or ``Letzte`` or ``Laatste`` would be clear enough anyway, IMO ...

**Comment by MagpieFourtyTwo** [comment]
> But I don't know if preselected will be good - if I want to store it on a different list, I have to deselect it first ...

Additionally to @Lineflyer's remark:
In the current implementation, after selecting ``Last selection`` you usually scroll down to check if the selection is really the one you intended, anyway, thus sorting them to the beginning and deactivate one or two will in total be even less ticks ... win-win. ;)

**Comment by MagpieFourtyTwo** [comment]
> Or we keep anything as is but just offer plenty more rooms for the (up to three) selections shown. The only drawback would be less space for lists, so a user with many lists would need to scroll.

In order to catch every single case (and esp. the one in the OP), there must be three times the space ... which is a lot, IMO.
Esp. as this problem mainly happens to the guys with small displays, who are struggling with space, anyway ...

**Comment by Lineflyer** [comment]
As can be seen in my initial post, each item is already in one line but scrollable on my device (Android 11) but just the window area is too small.
Other (older) devices seem to miss this scroll option and also use another color accent (see screenshots above)...so maybe another styling is used here or those older devices do not support the scrolling?!

**Comment by Lineflyer** [comment]
Additional comment regarding the dialog behavior on my device:
If I only have few items on the list the bottom section is expanded and can be used. Only once I have more and more lists the bottom window gets smaller and uses scrolling.
![Screenshot_20210302-140729_cgeo](https://user-images.githubusercontent.com/949669/109653105-e55baf00-7b60-11eb-93c9-86018ee0c0a8.jpg)


Is there kind of a minimum size which can be defined?

**Comment by MagpieFourtyTwo** [comment]
What I still don't get is the user's remark in the support request mentioned [here](https://github.com/cgeo/cgeo/issues/9879#issuecomment-788213840):
He said, that even in landscape mode he can't see all three buttons - but at least on my device the space for the buttons is nearly doubled in landscape mode - why is this still not enough on the reporting user's device?  Is there possibly even another problem apart from the pure space available?

Aaah, now: In landscape mode the popup width seems to be determined by the longest list name.
And if this users has just short names, the popup is possibly too narrow for the three buttons.
Seems as if the width of the buttons (in total) have no effect WRT the popup width ... is this possible?
If so, this may explain some oddities, doesn't it ...?

**Comment by moving-bits** [comment]
A different approach could be:
- keep "Ok" and "Cancel" buttons at the bottom => should always fit into one line
- add a button in the dialog's titlebar (top right) to check the items selected the last time - just need a catchy icon for it

"Ok" and "Cancel" are actions which close the dialog, whereas "last" does not, so putting them into different areas of the dialog does make some sense, IMHO.

**Comment by Lineflyer** [comment]
Proposal of a user on FB (which sounds not so bad as quick fix):
You may remove "Cancel" to gain more room and force "Last selection" and "OK" into one row. I can still use the back button on my device or tap outside to cancel the action.

Meaningful?
