### ISSUE TITLE
Show hint how to unhide internal storage 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9881]
While this happens to me only in the emulator, it could be that it affects some real live users as well.

I can only choose SD or downloads - not my internal storage, where the old cgeo folder was stored. That would not be so bad, however, I had selected "do nothing" before that. If later (before releasing) it should be detected automatically if files have to be ~copied~ _moved_ then this would still not be very nice but much more acceptable.

![2021-01-27 14_35_58-cgeo – cachedetail_activity xml  cgeo main  Android Studio](https://user-images.githubusercontent.com/64581222/105998786-49e0a580-60ad-11eb-99b1-9aaa684e8b74.png)

**Comment by fm-sys** [comment]
![grafik](https://user-images.githubusercontent.com/64581222/106000655-5bc34800-60af-11eb-9103-93fd050603cd.png)

Oh, and of course it would be better if moving works ;-) 
Unfortunately, it is not possible to see (even in Logcat) what went wrong. Could it be that moving files from one disc drive to another does not work?

**Comment by fm-sys** [comment]
Update: Some files have been moved, but not all of them. During copying, the screen went black for 10 seconds, and then the error message appeared. It would be good if the copy progress will be displayed (which file is being moved and how much percent done).

**Comment by eddiemuc** [comment]
> ![grafik](https://user-images.githubusercontent.com/64581222/106000655-5bc34800-60af-11eb-9103-93fd050603cd.png)
> 
> Oh, and of course it would be better if moving works ;-) 
> Unfortunately, it is not possible to see (even in Logcat) what went wrong. Could it be that moving files from one disc drive to another does not work?

Not good that error does not show up in log...

**Comment by eddiemuc** [comment]
For the original problem: I remember that I was able to choose "show internal storage" when I clicked the three-dot-menu in the upper right of the dir select intent

**Comment by eddiemuc** [comment]
> Update: Some files have been moved, but not all of them. During copying, the screen went black for 10 seconds, and then the error message appeared. It would be good if the copy progress will be displayed (which file is being moved and how much percent done).

I would hope that 44 files in 11 subdirs were moved before it failed (then at least the display message would be correct).

**Comment by fm-sys** [comment]
> I would hope that 44 files in 11 subdirs were moved before it failed (then at least the display message would be correct).

44 files moved but only 8 dirs where created. The files which where moved had a size of 390MB while the SD card is only 500MB large. I thought maybe the memory was full, but there are still 120MB free. Nevertheless, it could be related... 

The files that have not been moved are only 1MB in size. It looks like everything worked except for the backups. Here all subfolders are created in the destination folder (with the wrong name `"-"`), but there is not a single file. These files are only in the old cgeo folder (internal storage) so it might be related to the dir name problem and will be implicitly fixed...

By the way, I had three backup folders. So it could be that the backup subfolders where counted twice. (8+3=11 folders) 

BTW, you were right that I could enable "show internal storage" in the menu. Is just unfortunately quite hidden. Hopefully this is just for emulators...

**Comment by eddiemuc** [comment]
@fm-sys thanks, that's very valuable input. I assume that the move error is related to the directory naming problem then.

You are also right of course that more error info as well as a progress display would be good to have.

**Comment by fm-sys** [comment]
Issue is fixed meanwhile...

**Comment by MagpieFourtyTwo** [comment]
> BTW, you were right that I could enable "show internal storage" in the menu. Is just unfortunately quite hidden. Hopefully this is just for emulators...

Most regretfully, it's most definitely the same on real mobiles:
Happened to us, too, but I already knew about the possibility to show/hide internal storage,
thus I did not think about it any further, just enabled it, and this was it.

Perhaps a hint should be added to the introduction dialog ...?

**Comment by eddiemuc** [comment]
I tested with many different SDKs from 21 to 30 (all emulators), and unfortunately the file/folder selection Dialogs are very different from one SDK to another. In some SDKs the internal storage was visible always, in some I had to enable it like you experienced it. I expect further differences between different device vendors (samsung, huawei, pixel etc). 

My hope would be that people will get used to this anyway because all apps need to switch to this sooner or later. Somehow we seem to be one of the early birds for this.

**Comment by fm-sys** [comment]
> Perhaps a hint should be added to the introduction dialog ...?

Good idea. I renamed and reopened the issue.

**Comment by moving-bits** [comment]
Would this be the kind of text you have in mind for this?

![image](https://user-images.githubusercontent.com/3754370/107565718-43414a80-6be4-11eb-9019-f51f12092580.png)

**Comment by fm-sys** [comment]
Perhaps "unhide" instead of "activate displaying"?
