### ISSUE TITLE
Increase the amount of decimal places of the distances

### ISSUE THREAD

**Issue by Sheldor2101** [cgeo/cgeo#9882]
I am using c:geo together with BRouter to get my routes, which I want to hike. I started to note the distances, I predefined as an individual route. Often, I walk more than 10 km. But I got used to have the distances with two decimal places, whereas at 10 km and more there is only one left. Might it be possible to let the distances with more than 10 km still be shown with two decimal places?

**Comment by Lineflyer** [comment]
Why would no need more than a 100 meter resolution for a >10km track?
Just asking to understand the usecase.

Giving one more digit should work out on most displays, only for the supersize function it should maybe stay with one digit.

**Comment by Sheldor2101** [comment]
I use it while hiking. (I create individual caches and connect them in combination with BRouter.) I put it afterwards in an Excel sheet. (I hike almost daily.) If I want to see improvements a difference of 100 m is kinda lot. So, if I walk 10 km in 1,5 h it's 6 ⅔ (6,66666...) km/h; 10,1 km in the same time is 6,733333 km/h. But round about 9 hundredth km/h is a kinda big difference for hiking, I'd say.

**Comment by eddiemuc** [comment]
Teammeeting 19.11.23: history trail might be used in this case. Currently it is not planned to implement this feature
