### ISSUE TITLE
Unify wording: Folder or directory?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9885]
This is just a mnior one (alerted by some Crowdin users):
With SAF we recently introduced a couple of new strings which use (mostly) `folder` instead of `directory`. In the existing code before SAF we mostly used `directory` but IMHO also `folder` at one place.

I think we should use a unified wording here as there is no difference, or is there any?

From modern apps and user manuals I do much more often nowadays read `folder` (deutsch: Ordner), so I would prefer that.
Opinions?

**Comment by bekuno** [comment]
You can read a interesting discussion to this question at https://superuser.com/questions/169457/directory-vs-folder.

From history it seams that `directory` (deutsch: Verzeichnis) was a special file system container for files.
And `folder` was used later more generalized for different types of container.

I would also say that the wording `folder` (and `Ordner`) is today more common.
