### ISSUE TITLE
Google Maps location deviation in China

### ISSUE THREAD

**Issue by szamyja** [cgeo/cgeo#9890]
中国地区谷歌地图偏差大 定位不准确

**Comment by eddiemuc** [comment]
Translated to englisch by Google: 
Google Maps in China have large deviations and inaccurate positioning

**Comment by fm-sys** [comment]
AFAIK this is nothing, we can solve. Any ideas how we want to deal with this issue?

See also https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China

**Comment by SammysHP** [comment]
Indeed nothing we can change.
