### ISSUE TITLE
Multi-thread option for Mapsforge

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9895]
Mapsforge support a multi-thread tile rendering option which we don't use yet AFAICS.

We should check whether we can use it and whether it speeds up tile rendering significantly in our use-case. If so we should integrate it.

See `MapWorkerPool` etc. in Mapsforge.

**Comment by Lineflyer** [comment]
Is this just a switch to enable or is it more programming work.
In the first case I would like to try it in nightlies.

**Comment by moving-bits** [comment]
@Lineflyer 
I've created a PR #9947 for this, marked as "Do not merge". It has a fixed setting of four threads (instead of the default 1), but no user interface etc.

**Comment by Lineflyer** [comment]
Thanks @moving-bits 

I gave the PR build a small test on my Pixel3a:
It is definitely faster than before. The initial tile rendering is only a bit faster, however scrolling through the map is almost without any visible tile loading.

Not sure what side effects could occur? Could this lead to memory issues or alike?

I would be in favor to merge it (but we should have least have a setting option in case some users run into problems).
IMHO we could start with a switch where off means one thread and on (default) means 4 threads in order to make setting not to complicated.

**Comment by fm-sys** [comment]
Of course, we need to test this change across devices / android versions. However, if it works smoothly, we shouldn't introduce a setting for it.

In a somewhat ironic way, I would call the setting as follows:
`[x] degrade card render performance`
If it works across all devices, a setting doesn't really make sense for sure. I would introduce a setting only if there were problems, not just provisionally. 

What happens when the device has fewer threads than selected to use for map rendering? Will this results to a crash or is it smartly detected/ignored by mapsforge?

**Comment by bekuno** [comment]
We need no magic. See https://github.com/mapsforge/mapsforge/blob/master/mapsforge-core/src/main/java/org/mapsforge/core/util/Parameters.java
~~~
    /**
     * The default number of threads is one greater than the number of processors, as one thread is
     * likely to be blocked on I/O reading map data. Technically this value can change to a better
     * implementation, maybe one that also takes the available memory into account would be good.
     * For stability reasons (see #591), we set default number of threads to 1.
     */
    public static int NUMBER_OF_THREADS = 1;//Runtime.getRuntime().availableProcessors() + 1;
~~~
So
`     Parameters.NUMBER_OF_THREADS = Runtime.getRuntime().availableProcessors() + 1;`
should do the job

By the way, also the other mapsforge parameter could be new tested with high dpi devices and fast processors.

**Comment by Lineflyer** [comment]
> If it works across all devices, a setting doesn't really make sense for sure. I would introduce a setting only if there were problems, not just provisionally.

But that is the reason I would like a switch, as we cannot proof, that its working on all kind of devices. If problems occur for some users it could only then be easily solved by asking the users to disable the multi-threading manually.

**Comment by Lineflyer** [comment]
> So
Parameters.NUMBER_OF_THREADS = Runtime.getRuntime().availableProcessors() + 1;
should do the job

Shouldn't it be rather `-1` then?

**Comment by moving-bits** [comment]
There has been a long-ongoing discussion in the Mapsforge forum about the right number of threads, impacts on memory and CPU usage etc. Final conclusion was to not set a specific number of threads for everyone but default to 1 and let the user decide.

My proposal would be:
- add an on/off switch to settings => Map, defaulting to off
- if switched to on, use a default of 4 threads for now
- internally: store a number of threads to be future-proof (we could decide at some point to make it configurable by the end-user, or by support only etc.)

**Comment by moving-bits** [comment]
The feature itself started somewhere in 2014/2015, got improved over time, and the last bugfix was merged as recently as the current version 0.15

**Comment by moving-bits** [comment]
> It is definitely faster than before. The initial tile rendering is only a bit faster, however scrolling through the map is almost without any visible tile loading.

From the forum (but already a bit older, not sure whether it's still valid):
Rendering of a single tile is not faster by this, but several tiles are rendered in parallel.

> Not sure what side effects could occur? Could this lead to memory issues or alike?
Memory consumption and CPU usage will spike temporarily.
Not sure about other side effects.

**Comment by bekuno** [comment]
> > The default number of threads is one greater than the number of processors, as one thread is
> > * likely to be blocked on I/O reading map data.
> 
> If one thread is unavailable the used processors should be reduced by 1 or not?

The idea here is: `The default number of threads is one greater than the number of processors, as one thread is likely to be blocked on I/O reading map data.`
The management thread waits for the other threads = number of processors until they are ready.

My proposel:
 * add an on/off switch to settings => Map, defaulting to off
 * if switched to on, calculate the number from the number of cores
 * internally: store the state only if user explicitely switches it. So we can later set default to on and all user without explicitely switched off use the change

**Comment by fm-sys** [comment]
Today I activated the settings option and was totally surprised! 

While it always took seconds before the map appeared on the empty screen, it is now immediately there. IMHO we should change the default behavior of multi-threading to activated, as it will probably work on (nearly?) all devices without problems.

If we don't just try it out, we'll never know if it might have worked without problems. 

Users shouldn't have to search the entire settings to find out that the app performance could be drastically improved with just one click...

**Comment by moving-bits** [comment]
Great news, thanks for testing.

If no one objects, I'll create a PR for setting multi-threaded rendering activated as default.
