### ISSUE TITLE
Possibility to set cache icon as marker

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#9898]
**Is your feature request related to a problem?**
I like the new feature to set a cache icon. I wanted to use it, to indicate caches which need special equipement, like night caches or fishing (?) caches (german: Angelcaches).
But unfortunately if I set a icon for those caches, I now can't see, if it is a multi or puzzle or...

**Describe the solution you'd like**
I would like to have the possibility to choose, whether to replace the original cache-icon or to set the icon as marker to the cache.

**Describe alternatives you've considered**
The marker can replace the saved-marker, because I guess, the function is only available for saved caches...

**Additional context**

**Comment by fm-sys** [comment]
This is already available. Just create a new list (in your case "Angelcaches") and set the according list marker for the list (via "manage lists" > "set list marker" or something like that)

**Comment by murggel** [comment]
Cool, I forgot that! Thanks.

**Comment by murggel** [comment]
But it is really tiny 😣

**Comment by fm-sys** [comment]
Yes, that's true, unfortunately. Maybe we could enlarge the markers a bit...

**Comment by moving-bits** [comment]
> Maybe we could enlarge the markers a bit...

Not really, that would clash with the other overlays. I'd already enlarged the cache list markers by 20% in each direction compared to the old list markers.

**Comment by Lineflyer** [comment]
You could still also apply a new cach icon to all caches of the list.

**Comment by murggel** [comment]
> You could still also apply a new cach icon to all caches of the list.

But then I don't see if it is a multi or mystery-cache

**Comment by murggel** [comment]
> > Maybe we could enlarge the markers a bit...
> 
> Not really, that would clash with the other overlays. I'd already enlarged the cache list markers by 20% in each direction compared to the old list markers.

How about replacing the disk-symbol with the list-marker, if one is assigned?
