### ISSUE TITLE
Set marker for waypoint with calculated coordinates in the waypoint list

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#9899]
I also thinking of some indication in the waypoint-list, to show the formula there 
for formula in plain format this can be done easily:
![grafik](https://user-images.githubusercontent.com/70113341/104110117-ba797b00-52d4-11eb-983f-7abe78f33663.png)

If the formula is the first part of the waypoint-note, the repetition of the formula can look strange.

If it is too long, the "calculated coordinates" can be omitted.
For the other format probably only the text "calculated coordinates" could be shown

_Originally posted by @murggel in https://github.com/cgeo/cgeo/issues/6833#issuecomment-757378884_

There was also the discussion to use a add-on-icon (SVG) for indication.

**Comment by murggel** [comment]
@moving-bits pleas assign the issue to me...

I will play around a little bit

**Comment by murggel** [comment]
Taken from #6833

> 
> 
> > As it is #7856 only seems to discuss issues with API < 21, which is a moot point now.
> 
> We increased the min API level to 21 along the way, so discussion changed. But he recommended to keep the compat lib due to some quirks in Android 5/6, see [#7856 (comment)](https://github.com/cgeo/cgeo/pull/7856#issuecomment-619408476).
> 
> > But regardless I'd recommend trying to get SVG icons working first and only revert to PNG (or whatever) if the SVG fails.
> 
> Highly appreciated. Might be a starting point for more migration towards SVG.

Shall we ask NotWood to continue with his work?

Or ... I already took a look at the PR (to be honest only to be able to play around with the calculater-svg) and found out that there is no more the need for the vector drawable compat library... only one additional definition in the gradle.build is necessary. The svg can then be imported via AndroidStudio and converted to vector-drawable-xml or even in libraries there are already vector-drawables available...
It seems, that there is a possibility to create the vector-drawable out of the svgs in the build-step, but there I am not the right person for... (this would only be necessary if we want to have the svg automatically converted to vector-drawable)
The provided XML from the PR can be still used

Now I am playing around with different calculator-svg to find .
I will create a separate issue for the image to show that a waypoint has calculated coordinates, I guess there will be more discussion, which does not fit to the initial topic of this issue.

**Comment by murggel** [comment]
SVG for this case is working :-) 

I tried some motives and colors, but no one satisfied me completely so I need your feedback:
![grafik](https://user-images.githubusercontent.com/70113341/108609049-90cf6b80-73cb-11eb-9509-2bf747cdf1e4.png)
![grafik](https://user-images.githubusercontent.com/70113341/108609056-9cbb2d80-73cb-11eb-905c-128551ec1a26.png)
![grafik](https://user-images.githubusercontent.com/70113341/108609735-443a5f00-73d0-11eb-8185-f65f8646a0dc.png)
![grafik](https://user-images.githubusercontent.com/70113341/108609618-5f589f00-73cf-11eb-9f1b-355d97ca31a2.png)

![grafik](https://user-images.githubusercontent.com/70113341/108609061-a93f8600-73cb-11eb-82ef-313ab47dcf11.png)

or just staying with textual hint:
![grafik](https://user-images.githubusercontent.com/70113341/108609244-0556da00-73cd-11eb-875c-3b2ad1c8c8a1.png)


One open point is, that clearing the coordinates does not clear the calcState. So wheter a dedicated function is needed or clearing the coordinates will clear the calcState as well.

**Comment by Lineflyer** [comment]
I would keep the textual hint also if its an addition to specific icon.
Regarding the icon: How about an icon like: + sign in upper left - sign on lower right. or even combined with "a b" to visualize variables.  Not sure what fits and is readable.

**Comment by murggel** [comment]
@Lineflyer good idea with the "a b" hint:
![grafik](https://user-images.githubusercontent.com/70113341/108638658-95aa2300-7490-11eb-9cdb-ef1333f90f49.png)

I like the variant with the orange "accent-color", but I guess the black/white is more readable.

**Comment by murggel** [comment]
In addition I tried to use the tick-marker in the dialog, if waypoint has a calc-state.
![grafik](https://user-images.githubusercontent.com/70113341/108638757-1406c500-7491-11eb-9b57-039de75a28bb.png)

But I don't know, if it fits to the other options, probably the tick should then appear at the "Cache coordinates" also, if the coords are same as the cache-coords... 
Probably its sufficient in the waypoint list.

**Comment by murggel** [comment]
@Lineflyer shall we close here or give it a try in the waypoint-list with one of the icons above (see https://github.com/cgeo/cgeo/issues/9899#issuecomment-782926595)
I can currently check it only on the emulator, don't know how it will look like in real

**Comment by murggel** [comment]
Closing here, I think, the text will be sufficient and not overloading the waypoint icon.
