### ISSUE TITLE
SAF: folder legacy values not preserved on migration for Offline Map folder and GPX export/import folder

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9904]
Found while using 2021.01.28-NB (did not check newer versions, sorry if this is already solved, but I found no issue):

- Before upgrading to that version my maps folder was set to some folder on my SD card ( `SD/VectorMaps/`) and a map from there was my active map
- I upgraded to the nightly as my first version with SAF
- I selected "Cancel" in the main SAF dialog
- When I started using the map afterwards I have seen, that it now uses Google Map and no offline map can be selected
- Looking into my settings and sysinfo I do see `[Legacy]/storage/emulated/0/cgeo/maps (Default)` but that wasn't my legacy value

I was pretty sure I tested, that with the NBSAF-versions and did not see this problem before...but AFAIR @MagpieFortyTwo also reported something like that (in some closed issue?)

**Comment by Lineflyer** [comment]
I retested this on my tablet device with same result:
In fact I have seen a toast appearing on the very first start (even before the dialog itself comes up), which read something like that the folder could not be found and was set to some default. It was to fast to read it completely. IMHO this is the problem: The old folder is in fact readable AFAICS.

Here is the sys info before and after

Before:


```
--- System information ---
Device: SM-T830 (gts4lwifixx, samsung)
Android version: 10
Android build: QP1A.190711.020.T830XXU4CTL2
c:geo version: 2021.01.06-NB-1237da3
Google Play services: enabled - 20.50.16 (120400-351607135)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: original 
HW acceleration: enabled (default state)
System language: de_DE / user-defined language: 
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (19,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (19,3 GB free) external non-removable
Geocache data: /storage/0882-2439/Android/data/cgeo.geocaching/files/GeocacheData (298,3 GB free) external removable
Database: /data/user/0/cgeo.geocaching/databases/data (57,6 MB) on system internal storage
Last backup: 12. Jan., 20:57
GPX import path: /storage/emulated/0/Download
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/0882-2439/VectorMaps
Map render theme path: /storage/0882-2439/VectorMaps/_themes/Elevate/Elevate.xml
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
   opencaching.nl: Logged in (Anmeldung OK)
Geocaching.com date format: d.M.yyyy
Installed c:geo plugins: contacts
BRouter connection available: true
--- End of system information ---

```

After:

```
--- System information ---
Device: SM-T830 (gts4lwifixx, samsung)
Android version: 10
Android build: QP1A.190711.020.T830XXU4CTL2
c:geo version: 2021.01.30-NB-182c9c3
Google Play services: enabled - 20.50.16 (120400-351607135)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found 
Hide waypoints: original 
HW acceleration: enabled (default state)
System language: de_DE / user-defined language: 
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (19,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (19,3 GB free) external non-removable
Geocache data: /storage/0882-2439/Android/data/cgeo.geocaching/files/GeocacheData (298,3 GB free) external removable
Public Folders: #8
- BASE: [Vorversion]/storage/emulated/0/cgeo (Standard)[/storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::], default: (same)] (Uri: file:///storage/emulated/0/cgeo, Available:true, Fiies: 45, subdirs:15, free space: 19,3 GB, files on device: -1)
- OFFLINE_MAPS: [Vorversion]/storage/emulated/0/cgeo/maps (Standard)[/storage/emulated/0/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/maps], default: (same)] (Uri: file:///storage/emulated/0/cgeo/maps, Available:true, Fiies: 0, subdirs:0, free space: 19,3 GB, files on device: -1)
- OFFLINE_MAP_THEMES: [Vorversion]/storage/emulated/0/cgeo/themes (Standard)[/storage/emulated/0/cgeo/themes[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/themes], default: (same)] (Uri: file:///storage/emulated/0/cgeo/themes, Available:true, Fiies: 0, subdirs:0, free space: 19,3 GB, files on device: -1)
- LOGFILES: [Vorversion]/storage/emulated/0/cgeo/logfiles (Standard)[/storage/emulated/0/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/logfiles], default: (same)] (Uri: file:///storage/emulated/0/cgeo/logfiles, Available:true, Fiies: 5, subdirs:0, free space: 19,3 GB, files on device: -1)
- GPX: [Vorversion]/storage/emulated/0/Download (Benutzerdefiniert)[/storage/emulated/0/Download[FILE#0:p-file:///storage/emulated/0/Download::], default: /storage/emulated/0/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/gpx]] (Uri: file:///storage/emulated/0/Download, Available:true, Fiies: 208, subdirs:0, free space: 19,3 GB, files on device: -1)
- BACKUP: [Vorversion]/storage/emulated/0/cgeo/backup (Standard)[/storage/emulated/0/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/backup], default: (same)] (Uri: file:///storage/emulated/0/cgeo/backup, Available:true, Fiies: 15, subdirs:6, free space: 19,3 GB, files on device: -1)
- FIELD_NOTES: [Vorversion]/storage/emulated/0/cgeo/field-notes (Standard)[/storage/emulated/0/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/field-notes], default: (same)] (Uri: file:///storage/emulated/0/cgeo/field-notes, Available:true, Fiies: 0, subdirs:0, free space: 19,3 GB, files on device: -1)
- TEST_FOLDER: [Vorversion]/data/user/0/cgeo.geocaching/files/unittest (Standard)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest], default: (same)] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Available:true, Fiies: 0, subdirs:0, free space: 19,3 GB, files on device: -1)
PersistedDocumentUris: #1
- TRACK: null
Persisted Uri Permissions: #0
Database: /data/user/0/cgeo.geocaching/databases/data (57,6 MB) on system internal storage
Last backup: 12. Jan., 20:57
Map render theme path: /storage/0882-2439/VectorMaps/_themes/Elevate/Elevate.xml
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
   opencaching.nl: Logged in (Anmeldung OK)
Geocaching.com date format: d.M.yyyy
Installed c:geo plugins: contacts
BRouter connection available: true
--- End of system information ---

```

**Comment by Lineflyer** [comment]
BTW: Note the typo in sysinfo: `fiies` instead of `files` (I guess?)

**Comment by eddiemuc** [comment]
Is "Vorversion" the german translation of "Legacy"?

**Comment by Lineflyer** [comment]
Yes, nothing better came to my mind for this context.... Any idea better idea for that translation...feel free to change on Crowdin :)

**Comment by eddiemuc** [comment]
> Yes, nothing better came to my mind for this context.... Any better idea for that translation...feel free to change on Crowdin :)

Would vote for "Veraltet". I upvoted it on crowdin (was already suggested there)

**Comment by eddiemuc** [comment]
@Lineflyer your observation is absolutely correct: there is a check at startup for all folders whether they are accessible or not, and if they are not rhey are reset to default values.

With PR #9909 I changed handling of legacy values such that if switching to default value happens due to failing accessibility check, the legacy value is tried again on restart until the user actively selects a new value for the folder.

But this is not the complete solution. I still don't know why the initial check fails although you claim the folder is still accessible. Tried with different "legacy folders" on my emulator (SDK29) and this works. I assume you are on an Android <= 10 system and permission to storage is granted? Does this maybe only happen if legacy folder is on sd card?

Maybe I need to postphone accessibility check e.g. to first usage of the folder. Can you send me a c:geo startup logfile where this happens, preferably written in verbose mode?  

And of course I also corrected the typo fiiles -> files :-)

**Comment by Lineflyer** [comment]
> Would vote for "Veraltet". I upvoted it on crowdin (was already suggested there)

I approved it and also gave you the "proofreader" role in case of future need.

**Comment by Lineflyer** [comment]
> I assume you are on an Android <= 10 system and permission to storage is granted? 

Initially when seeing this: Android 11 and legacy permission is granted (normal upgrading case).
Reproducing then on: Android 10 and legacy permission is granted (normal upgrading case).

> Does this maybe only happen if legacy folder is on sd card?

Might be. That was the case on both my devices.

**Comment by Lineflyer** [comment]
> written in verbose mode?

Verbose means "Extended" when saving the logfile?

**Comment by eddiemuc** [comment]
> > written in verbose mode?
> 
> Verbose means "Extended" when saving the logfile?

I meant with `logging.minLevel` set to verbose as described here: https://github.com/cgeo/cgeo/wiki/Logging

**Comment by eddiemuc** [comment]
Is this still an open issue?

**Comment by Lineflyer** [comment]
need to check

**Comment by Lineflyer** [comment]
Tested again by upgrading from 2021.01.24-RC to 2021.02.06-NB:

Still happening.
As soon as I first start the NB when coming from pre-SAF I do see a toast, that my selected offline map folder is not acceesible and reset to default. (BTW: This is not related to the other issue regarding non-availability after reboot).

The toast is shown to short to read it completely, but I stumbled upon, that it says something like "Lars400GB/VectorMaps" is no longer accesible. This is in fact not the real directory name but it should be "/storage/0882-2439/VectorMaps". Can it be, that we try opening this newly derived name instead of the real stored path to check accessibility in the legacy case?

**Comment by eddiemuc** [comment]
This is indeed very likely the errors source.

@Lineflyer can you tell.me:
* Does the same thing happen again when you restart (you get the toast and map is switched to bad default value)?
* Can you check what is now written in setting field mapDirectory (my previous PR should lead to preservation of the old value instead of overwriting it)

**Comment by eddiemuc** [comment]
@Lineflyer @magpiefourtytwo

Some changes were done since this issue was filed. Especially now legacy values are not immediately discarted if they are not available at startup, instead they will be kept until the user explicitely chooses a different directory. This concerns both map offline folder and GPX import/export folder. So you should not not loose these legacy values any more.

I am, however, still not sure whether SAF can properly read and process all legacy values. I tested throughly with paths pointing to internal storage, but I don't have ability to test for paths pointing to external SD Card.

* Can you give this a try again and give me feedback whether this works now too? 
* And if not: 
   * can you please give me the exact values of the legacy preference keys "mapDirectory", "gpxExportDir" and "gpxImportDir" (there might be a "unused::" prepending the value which is a migration marker by me and all right. I would still need the complete value)
   * Especially: is in your opinion the value of the legacy settings (minus possible "unused::" prefix) a valid absolute (!) file path (e.g. starts with an /)?
* If this works now, can we then close this issue?

**Comment by MagpieFourtyTwo** [comment]
Hmm ... wanted to simulate legacy state by just clearing the contents of persistable settings.
And prior to this i wanted to set the legacy settings to the old state, but could not find them ...
Where have the old variables gone?

**Comment by moving-bits** [comment]
For map folder see the `mapDirectory` variable, and gpx is either `gpxExportDir` or `gpxImportDir`. Remove the prefix `unused::` in the data to reactivate (using Settings => System => Show settings).

**Comment by eddiemuc** [comment]
> For map folder see the `mapDirectory` variable, and gpx is either `gpxExportDir` or `gpxImportDir`. Remove the prefix `unused::` in the data to reactivate (using Settings => System => Show settings).

@MagpieFourtyTwo 
And if those variables are now completely gone (because you said you cleared them), then just create them anew and place the legacy value into them (without a leading unused::).

Also, if you have already set a user-defined value for the folder using SAF, then you have to set the folder back to "use default" (legacy user-defined value will only be used if no SAF user-defined value is available)

**Comment by MagpieFourtyTwo** [comment]
> And if those variables are now completely gone (because you said you cleared them),

Nop, misunderstanding, I did not clear them on purpose, they just vanished.

**Comment by eddiemuc** [comment]
> > And if those variables are now completely gone (because you said you cleared them),
> 
> Nop, misunderstanding, I did not clear them on purpose, they just vanished.

Oh. 

I remember I had one version out in master for some days where I cleared the variables after taking over their values. Probably this one was installed at the phone when you did the tests. Current master should no longer delete the bars though.

**Comment by eddiemuc** [comment]
Haven't heard back on this one, so I assume it is fixed in current nightly. Thus I will close here. If there's something left which I missed please reopen or create a new issue for it.

**Comment by MagpieFourtyTwo** [comment]
Just for clarification:  After updating to current nightly this morning, c:geo asked me for a ``_themes`` folder.
Things worked pretty well (BTW: really like the new dialog), and it even successfully defaulted to the folder I used so far.
Up to here everything seemed to run smooth, c:geo welcomed me warmly (pretty strange, but just minor cosmetic glitch ; ).
but then the strange part happened:  Although old and new folder are the same, and although nothing has changed in the settings, apart from the new notation, of course, c:geo suddenly ...
- showed a popup called ``Synching ... <whatever>``
- obviously moved or copied a bunch of files 
- and the popup closed again - way faster than I was able to read anything at all

Although it seems(!) as if nothing bad has happened, this popup left me completely uncertain about what's going on in my installation. Or with my files. Or folders. Or whatever ... which is not a really good feeling.

What I assume:
- c:geo changed the setting for ``_themes`` folder from legacy to SAF notation
- afterwards c:geo copied the stuff from the "old" folder to the "new" one (although they are in fact the same)

If this is right, at least things in my installation are still running smooth, but the bad feeling remains.
IMHO: c:geo should not leave the user with such a feeling ...
Thus there would be two possibilities:
a) as c:geo most probably knows that "old" and "new" are in fact the same (have this "testfile" in mind"), the copy process should not even start
b) if for any reason the copy process *must* happen, the user should be informed what just has happened ...

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
Thanks for your feedback and detailed description.
Without having it tried out myself, I think the copy action you have seen is caused by the fact, that we decided to copy the themes into our own app private storage as we considered SAF to slow to handle all the files (see issue).

I agree with @MagpieFourtyTwo, that no user will probably understand whats going on.
Maybe just a progress bar with title "Buffering themes internally" (or similar) would be enough in order not to confuse the user.

**Comment by Lineflyer** [comment]
BTW:
I am sorry if I missed that part of the technical implementation:
What will happen if the users places new/updated theme files into the selected SAF path? Will c:geo buffer them again automatically or is there any user action required?

**Comment by eddiemuc** [comment]
What you see is indeed the progress bar for synchronization of public theme folder to private theme folder. This will happen right now on every startup, on theme folder change and after theme file download.

I can change appearance of the progress bar, I can even leave it out, but GUI will be blocked during sync. And although in majority of cases the syn will be very fast (when everything is already in sync), it may occasionally take a long time (eg 10 seconds for extracted elevate.zip on first sync)

**Comment by eddiemuc** [comment]
Btw, maybe we should open a separate issue for "redesign" of this process if you want

**Comment by MagpieFourtyTwo** [comment]
... and another one for the function, cause over here it does not work at all:
Since I changed the Legacy to SAF path, I have no themes anymore.
Although sync happens on every fresh start (and happily counts files, as I was able to check with a screen video capture),
thus is seemingly successful - but all I got on theme choice is ``[X] default``.  :/

**Comment by MagpieFourtyTwo** [comment]
> I can change appearance of the progress bar

As it will be seen for just the fraction of a second (most of the times - hopefully) this would be pretty senseless.
Proposal: What about a toast saying ``Successfully sync'ed map theme files`` afterwards ...?

**Comment by Lineflyer** [comment]
>  happen right now on every startup,

Oha...I will check it next days. I have stored approx. 10 themes in my theme folder. Lets see how blocking this is.

> What about a toast saying Successfully sync'ed map theme files afterwards ...?

Doing in background and just toasting "done" would IMHO be more than sufficient...maybe even totally in background unless a problem appears?

Let me first test on different devices next day. If needed (from my perspective) I will open a new issue.

**Comment by fm-sys** [comment]
A async task without UI feedback should be sufficient for such a regularly scheduled event. Otherwise it might be disturbing (as this task is not relevant from user side)

**Comment by eddiemuc** [comment]
> A async task without UI feedback should be sufficient for such a regularly scheduled event. Otherwise it might be disturbing (as this task is not relevant from user side) 

Valid request.
Can we open a separate issue for this? For this to work I have to make the whole thing thread safe. (Because it is not"synced" any more over a blocking GUI)

**Comment by MagpieFourtyTwo** [comment]
Is ``thread safe`` really important?  At least for the first approach?
As most of the times the sync will be done anyway until a map can even be opened ...
And if not, who cares, if the old theme will still be used for just one single start after changing it ...?

**Comment by eddiemuc** [comment]
Dealing with threads without securing then towards each other may lead to all sorts of inconsistent behaviour and failures e.g. when two threads simultaneously access, say, the current list of available themes. I would rather secure this. I don't want to be the person having to debug this kind of errors later...

Still I can heavily use synchronized keyword in first approach, to make it easier :-)

**Comment by MagpieFourtyTwo** [comment]
Programming principle: There's always a quick'n dirty way, which will afterwards last forever, and work even better than the so called "correct" version.  ;)
