### ISSUE TITLE
Coordinates of waypoints always copied in MinDec format

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9905]
2021.01.24-RC (reported by user) and also confirmed happening on ˋmasterˋ.
Most probably its no regression of the current version, but somehow I think this worked in older versions.

- Open a cache which has waypoints with coordinates
- Positive test: Tap on the caches listing coordinates to select another format than default (MinDec), then long tap on them and copy them to clipboard. On pasting them, you will see, that the selected format is contained in the clipboard
- Now swipe to the waypoints tab
- Tap on a coordinate of the waypoint to change it into another format
- Long tap on the waypoint to open the context menu and select "Copy Coordinates"

Result:
- On pasting these coordinates you will see, that always MinDec format is copied despite another format is active

Epected:
- The shown coordinate format should be copied to clipboard (same as it works for the listing coordinates)

**Comment by murggel** [comment]
Also when opening the waypoint, the coordinates are always shown in MinDec format and not the "selected" one.
Probably that is the reason why the MinDec format is copied.

**Comment by murggel** [comment]
> MinDec is our default and the  change when tapping is transient. Still users might want to export as seen like for the listing coords.

And I would like to see i in the format I entered them

**Comment by geocachermgo** [comment]
See also #8870 which is duplicate of #6711

**Comment by Lineflyer** [comment]
Thanks for finding those...we have to many issues. I could not remember these.
