### ISSUE TITLE
DNF state not exported in GPX

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9908]
Not sure if its technically possible to solve:

2021.01.30-NB

- Have a list with two caches: One with found state (yellow smiley), one with state DNF (blue smiley)
- Export to GPX and activate checkbox "including found state"
- Import the GPX to another c:geo instance (same username)

Result:
- Caches imported. Found cache has yellow smiley but DNF cache has no smiley (only after manual refresh)

Expected:
- Export found state should include DNF as well

**Comment by fm-sys** [comment]
That's indeed true. However I have never really worked with GPX files before, and I don't know, if there is an official parameter to store a DNF state. Does anyone have an idea? How do other geocaching tools do it?

**Comment by moving-bits** [comment]
You can check at https://www.topografix.com/GPX/1/1/, that's the "official" spec for GPX files. But there are also a couple of extensions, e. g. GSAK or even c:geo itself.

**Comment by Lineflyer** [comment]
Checked an export of a found cache and it contains a string in wpt/sym with content "Geocache Found". Not sure though whether its our own namespace extension.

**Comment by murggel** [comment]
I checked the gpx-schema and it is an offical tag, but doesn't recommend values. So it depends on the programs which interact.

```
<sym>Scenic Area</sym>
Text of GPS symbol name. For interchange with other programs, use the exact spelling of the symbol on the GPS, if known.
<type>

<type>Hiking trail</type>
type (classification) of element. 
```
We use "Geocache" and "Geocache Found" on exporting GPX and specify the waypoint type in the type-tag.
At import we interpret sym- and type-tag to identify the waypoint type.

So we could introduce a sym-value "Geocache Not Found" to exchange with another cgeo-instance. But I don't know, how other programs will react.

Probably we can export a DNF-log-entry and act on importing on that log.

**Comment by murggel** [comment]
@moving-bits you can assign this to me, if it is ok to use the GSAK-tag as I think this would be an easy and fast way to solve this, if it is mainly only relevant for transfering it from one c:geo-instance to another.

**Comment by Lineflyer** [comment]
@murggel  Assignment done.

**Comment by murggel** [comment]
Done with PR #10874.

**Comment by fm-sys** [comment]
@murggel feel free to close issues yourself if you like. If possible with a short note why the issue was closed (e.g. duplicate, fixed by PR #xxxx, ...)

**Comment by murggel** [comment]
> @murggel feel free to close issues yourself if you like. If possible with a short note why the issue was closed (e.g. duplicate, fixed by PR #xxxx, ...) 

Ok, now I am allowed to do it ;-) but  I want to clarify first, how you are dealing with that, if the creator closes it after testing or tests it after closing or ...

**Comment by fm-sys** [comment]
Most of the time we use the "fix #xxxx" closing word in the PR description or close the issue manually if we forgot to link an issue. Issues can still be reopened if it turns out, that a fix was not working... ;-)
