### ISSUE TITLE
Integrate BRouter tile downloading

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9914]
Downloading routing data using BRouter app is pretty slow, as the app limits the download rate. The server itself does not have this limitation.

Proposal:
If we get the ok from the author, we could use our integrated downloader for downloading and updating the routing tiles. We could even integrate an optional download of missing routing data, if a user tries to calculate a route for which we don't have the routing data yet.

@Lineflyer 
As you have been in contact with the author in the past: Could you ask him whether we are allowed to access his routing data server directly from within c:geo? Thanks.

**Comment by moving-bits** [comment]
@eddiemuc

Thinking about the SAF side of this: Would it be possible at all?

I'm not sure where BRouter stores its routing data, whether this is an hidden/internal folder or public folder. I guess that an app-specific internal folder would be unreachable for us, right?

But if it's a public folder, we could gain access to it (by asking the user for an SAF read/write grant) and store routing tile data there, and BRouter would be able to see and to read those files, correct?

**Comment by Lineflyer** [comment]
Server usage permission has been addressed to the Brouter author (Arndt).

**Comment by Lineflyer** [comment]
BTW:
The author said in an earlier mail, that we could theroretically also include brouter into c:geo:

> > Mit c:geo nutzen wir derzeit das Routing in Verbindung mit der Brouter App. Alternativ
> wäre natürlich auch eine direkte Integration möglich. Ist die BRouter-Lib als OpenSource verfügbar?

> Ja schon, und wir haben extra die Lizenz von GPLv3 auf MIT geändert, damit das möglich ist.
Es ist eben nur keine sauber strukturierte Lib mit einer API, sondern wer das machen will muss sich vom HTTP-Server (also der Gegenstelle für BRouter-Web) oder der Mobile-App die API reverse engeneeren. So haben sie es bei Locus gemacht.

**Comment by eddiemuc** [comment]
> @eddiemuc
> 
> Thinking about the SAF side of this: Would it be possible at all?
> 
> I'm not sure where BRouter stores its routing data, whether this is an hidden/internal folder or public folder. I guess that an app-specific internal folder would be unreachable for us, right?
> 
> But if it's a public folder, we could gain access to it (by asking the user for an SAF read/write grant) and store routing tile data there, and BRouter would be able to see and to read those files, correct?

Should be possible imho. Would be pretty similar to using shared offline map files I guess. Only Problem I could think of right now are performance issues in case files are too many (like with map theme resources).

But I see from ongoing thread that you are already investigating also other ways of integration. Would be good if we use some "documented", official way.

**Comment by moving-bits** [comment]
@Lineflyer 

> Server usage permission has been addressed to the Brouter author (Arndt).

Did you receive any response from the author?

**Comment by Lineflyer** [comment]
Nope, not yet.

**Comment by Lineflyer** [comment]
@moving-bits 
Positive reply cam in (see cgeo-dev mailing list).
Summary:
We can freely use it in our downloader but no warranty if and how long in future it might be working.

**Comment by moving-bits** [comment]
> Positive reply cam in (see cgeo-dev mailing list).

Good news! Thanks for clarifying.

> We can freely use it in our downloader but no warranty if and how long in future it might be working.

Which leads to the question: What is the common source other servers take their routing tile data from, and can't we use that server instead? (Maybe even mirror such a server?)

Anyway, here are some thought on implementing such a feature:
- Downloading routing tile data ("tiles") can make use of our downloader, in the meaning of: do download asynchronously in the background, and on successful receive put the received tile in that place where BRouter expects it.
- But it is different from current map downloader, as the user should not have to explicitly select from a list of seemingly strange named files like "N50_E30.dat" (or something like this). - Selecting the "right" file should be done automatically by c:geo. I can see two places for this:
  - On receiving the first position signal: Check whether tile already exists for current position, and offer user to download it, if it does not exist yet. [Check once per session]
  - On calculating a route: Check coordinates for start point and end point in the same way.
  - If tile is missing, ask the user if he/she wants to download it (similar to the confirmation dialog in the map downloader).
  - For missing tiles: Only ask, if not having asked for it in the last xx (60?) minutes and if not already downloading that tile.
- Automatic download can be disabled in the settings.
- Automatic download is only offered when BRouter is installed and tile path is set (yet another `PersistableFolder`, but no need for migration).
- Offer an automatic update check every 30 (?) days.
- Integration of setting the tile path into the wizard (only IF BRouter is already installed)

**Comment by fm-sys** [comment]
> when BRouter is installed and tile path is set (yet another PersistableFolder, but no need for migration)

Is BRouter able to deal with custom tile paths? Otherwise it might even be better to integrate the BRouter source code directly into c:geo (if that would be ok as well for the author)

AFAIK [this](https://github.com/abrensch/brouter) is the brouter repo. There is also a link in the Readme how to build routing tiles...

**Comment by moving-bits** [comment]
> Is BRouter able to deal with custom tile paths?

Actually BRouter is able to deal with custom paths - that's how you can configure it to use SD card as storage -, but I was thinking of putting the tiles into the original BRouter folder (which should work by selecting it using the SAF directory selector). BRouter's tile folder defaults to `/brouter/segments4`.

> Otherwise it might even be better to integrate the BRouter source code directly into c:geo (if that would be ok as well for the author)

IIRC from the email exchange, this would be ok for the author, only it does not have a well documented API. So if someone wants to tackle that... :-)

Still that would not change much wrt the proposal above, only the need to ask for the folder could be skipped in that case.

> AFAIK [this](https://github.com/abrensch/brouter) is the brouter repo.

Thanks for the link.

> There is also a link in the Readme how to build routing tiles...

Ok, could be a fallback option if the server gets shutdown at some time.

**Comment by moving-bits** [comment]
I'm a few steps further by now:
- settings is implemented
- automatic detection of missing tiles does work
- downloading a missing tile does work

But: Downloaded tiles do not get recognized by BRouter :-(

@eddiemuc:
Is there some flag or something to declare a downloaded file as being visible for other apps? Or at least as being visible for a specific app?

**Comment by eddiemuc** [comment]
> @eddiemuc:
> Is there some flag or something to declare a downloaded file as being visible for other apps? Or at least as being visible for a specific app?

If I understand you correctly you want to store a file in a public folder where the user granted access to c:geo via SAF, and you want to transfer this permission to another app? Since this would somehow break the intention of scoped storage I don't think this is possible (user has to grant such access permission himself, in this case via BRouter app) but might make sense to google it.

How was this done up to now? Maybe it makes more sense to implement download functions for BRouter inside BRouter?

**Comment by moving-bits** [comment]
> > @eddiemuc:
> > Is there some flag or something to declare a downloaded file as being visible for other apps? Or at least as being visible for a specific app?
> 
> If I understand you correctly you want to store a file in a public folder where the user granted access to c:geo via SAF, and you want to transfer this permission to another app? 

BRouter is a non SAF-aware app, thus my thought was if I put a file into their public folder (`/brouter/segments4`) the app will be able to see it. Looks like this is not the case :-(

> Since this would somehow break the intention of scoped storage I don't think this is possible (user has to grant such access permission himself, in this case via BRouter app) but might make sense to google it.

I had hoped you would tell me some magic flag to achieve this :-)
Had already googled quite a bit, but to no avail so far.

> How was this done up to now? Maybe it makes more sense to implement download functions for BRouter inside BRouter?

BRouter actually has an integrated download option - will be shown when you open the BRouter app. But that's sort of clumsy, and also download is extremely slow when using BRouter. I'd like to make for a smooth user-experience, offering automatic & fast downloading from within c:geo.

Looks like I either need to find that magic flag (if it exists at all), or we really do have to integrate BRouter into c:geo.

**Comment by eddiemuc** [comment]
Hm, since you write that BRouter is not using SAF, I assume that this /brouter/segments4 folder is accessed by it via classic File interface. Then I don't see why BRouter should not see these files (BRouter will get a problem reading files from public folders once SAF is mandatory of course, like all others). Would have to google that too.
But in any case, maybe this solution is not so future-safe?

**Comment by moving-bits** [comment]
Probably the BRouter Android app will get discontinued / receive no more updates as soon as SAF is mandatory for publishing updates...

Just did a few more checks in the emulator:
- Normally BRouter files are stored in `/brouter/` and subfolders (`/brouter/segments4` for the routing tile data) - this is the way it is on my physical smartphone (Android 10, got an upgrade to Android 11) and also the way I remember from earlier devices
- But in my current API 29 emulator, as I just found out, the data is stored in `/Android/data/btools.routingapp/files/brouter/segments4` - Why is that? And what consequences will that have?

Good news is that if I grant c:geo an SAF access to that folder, downloaded tile data gets recognized by BRouter... 👍 

Will have to cross-check that on emulators running an earlier API.

**Comment by eddiemuc** [comment]
`/Android/data/btools.routingapp/files/brouter/segments4` looks like it would be an app private folder. I wonder why it is reachable via an SAF intent.

**Comment by moving-bits** [comment]
Hm, from https://developer.android.com/about/versions/11/privacy/storage:

> Access to data directories on internal storage
>
> Android 9 (API level 28) started to restrict which apps could make the files in their data directories on internal storage world-accessible to other apps. Apps that target Android 9 or higher cannot make the files in their data directories world-accessible.
> 
> Android 11 expands upon this restriction. If your app targets Android 11, it cannot access the files in any other app's data directory, even if the other app targets Android 8.1 (API level 27) or lower and has made the files in its data directory world-readable.
>
> Access to app-specific directories on external storage
>
> On Android 11, apps can no longer access files in any other app's dedicated, app-specific directory within external storage.

But that should still leave the option to access files in a non-app-dedicated public folder within external storage (like `/brouter/segments4`). - Still wondering why BRouter in the emulator used a private folder instead.

Guess I will have to check it on a physical device - uninstall both c:geo and BRouter, do fresh installs and see what will happen...

**Comment by eddiemuc** [comment]
Just out of interest: does this happen only on Android 11 (emulator) or also on lower-level emulators?

**Comment by moving-bits** [comment]
I was working with an Android 10 emulator. BRouter stored its files in the app-private folder, but I was able to access this folder using the SAF selector.

Just tested it in an Android 11 emulator: c:geo is no longer able to access the app-private folder... :-(

This leaves only a hack to use this solution: Edit `storageconfig.txt` in folder `segments4` to make the routing tile data folder point to a public folder, which then can be granted access to for c:geo - a bit hacky for the average user...

So we need to find a different solution, probably integrating BRouter into c:geo (as I guess the author of BRouter will not update his app to be SAF compatible). Just don't know where to start here...

**Comment by moving-bits** [comment]
I think - if no one objects - I'll contact the author to ask for his plans regarding SAF and how to integrate the route calculation into c:geo. (Though integrating BRouter into c:geo would mean, among other things, yet another SAF migration...)

Side note: Hm, what about if several apps make use of BRouter - e. g. not only c:geo, but also OsmAnd, Locus etc.?
I've read somewhere that some other apps already included BRouter into their own app. Will they all download the routing files separately? So we end up with tile data being multiplied? That doesn't make sense, IMHO. As with the map data, they all should use some common folder accessible to all of them, and store tile data only once.

**Comment by fm-sys** [comment]
> I'll contact the author to ask for his plans regarding SAF

As long as BRouter only uses the app internal storage (what has always been the case) it's still compatible with Android 11. Maybe it would be better to create a "download API" into the original BRouter app, so c:geo would just trigger the download via an intent and the real download is handled by BRouter itself (However, what would mean that download speed and UI blocking is still an issue. But that should be solved for BRouter in general anyway, if PR's are welcome...)

**Comment by moving-bits** [comment]
For the record: 

I received a reply from the author of BRouter. He would prefer if we integrate BRouter into c:geo, and sent me pointers to the integrated downloader and service (things I would have to adapt in both cases anyway).

I'm still in contact for him to get a better grip on which parts of the repo would need to be integrated, and which we could skip.

**Comment by moving-bits** [comment]
A bit hacky yet, but I do have a first version of c:geo with integrated BRouter engine working... :-)

(Though this is a v0.1 at most - lots of reformatting, cleanup, adaption to cgeo standards, SAF adoption etc. todo.)
