### ISSUE TITLE
Support downloading map theme files

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9919]
Reminder to myself:

Extend MapDownloader to automatically offer to download "Elevate" theme file when downloading a map file from OpenAndroMaps source.

Also add update feature (if possible).

**Comment by moving-bits** [comment]
Maybe we should wait for implementation of "zipped theme support" in Mapsforge to spare unpacking and cleanup steps.

**Comment by eddiemuc** [comment]
> Maybe we should wait for implementation of "zipped theme support" in Mapsforge to spare unpacking and cleanup steps.

Good idea :-)

**Comment by moving-bits** [comment]
BTW: Can't we temporarily base our implementation on a specific "nightly" build of Mapsforge (the first which includes the zipped theme support), and switch back to official release as soon as 0.16 is released?

**Comment by eddiemuc** [comment]
> BTW: Can't we temporarily base our implementation on a specific "nightly" build of Mapsforge (the first which includes the zipped theme support), and switch back to official release as soon as 0.16 is released?

We integrate mapsforge as libraries via gradle. I assume the are downloaded from some gradle server (something like maven central). This can only grab library versions previously uploaded by mapsforge.

I assume to use some sort of "nightly" we would have to download and compile maosforge sources ourself which seems a bit much imho. 

I can ask mapsforge if they have some sort of nightly build and whether they are willing to make this publically available

**Comment by eddiemuc** [comment]
Update: I posted a question to mapsforge

**Comment by moving-bits** [comment]
> I assume to use some sort of "nightly" we would have to download and compile maosforge sources ourself which seems a bit much imho.

agreed

> I can ask mapsforge if they have some sort of nightly build and whether they are willing to make this publically available

Would be kind, thanks. Or maybe when they plan to release 0.16? I know their normal release cycle is more like "half a year", but maybe...

**Comment by Lineflyer** [comment]
I always thought we are using our own fork https://github.com/cgeo/mapsforge in c:geo, or do we just use a tag to fetch from their repo while building c:geo.
Sorry for the unqualified question.

**Comment by bekuno** [comment]
> I assume to use some sort of "nightly" we would have to download and compile mapsforge sources ourself which seems a bit much imho.

I do not see a nightly release.
But  - we can reference to a commit ID by using `jitpack.io` as additional ressource.
I will prepare a PR.

**Comment by bekuno** [comment]
> I always thought we are using our own fork https://github.com/cgeo/mapsforge in c:geo, or do we just use a tag to fetch from their repo while building c:geo.

The own fork is for `MAPS.ME` ,
 `    implementation project(":mapswithme-api")`

**Comment by bekuno** [comment]
> But - we can reference to a commit ID by using `jitpack.io` as additional ressource.

It is queued there, see https://jitpack.io/#mapsforge/mapsforge/a623be6d9a
I don´t know when it will be ready.

**Comment by eddiemuc** [comment]
Got an answer from mapsforge. They indeed publish snapshot versions for public usage. See their integration guide:
https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md#snapshots

Apparently it is written with maven users in mind, but afaik gradle can use maven repositories right?

**Comment by Lineflyer** [comment]
>> I always thought we are using our own fork https://github.com/cgeo/mapsforge in c:geo, or do we just use a tag to fetch from their repo while building c:geo.
>
> The own fork is for MAPS.ME ,
> implementation project(":mapswithme-api")

Do we still need https://github.com/cgeo/mapsforge or is this just outdated stuff and to be deleted?

**Comment by bekuno** [comment]
The 
    // Mapsforge old version
    implementation files('libs/mapsforge-map-0.3.0-jar-with-dependencies.jar')

> Do we still need https://github.com/cgeo/mapsforge or is this just outdated stuff and to be deleted?

This is a clone of the old MF3 library with own changes.
Maybe this was the base for our own implementation. 

With commit 49b06e4f1fbb0974bc9762adafbf9b4edbf257ca the line
`    implementation files('libs/mapsforge-map-0.3.0-jar-with-dependencies.jar')`
was removed.

So I would say - yes, this is outdated and can be removed.
