### ISSUE TITLE
Support mf-theme scheme for downloading map theme files

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9920]
Reminder to myself:

Support "mf-theme" scheme to download map theme files.
Requires implementation of #9919.

**Comment by eddiemuc** [comment]
Since we are adding more and more features to the map (which is a good thing!) I want to re-ask a question I have for a long time: would it make sense to design a common map display module which can then be shared between cgeo and WhereYouGo? I have the impression this would help Whereyougo a lot, seem to be much less people involved over there

**Comment by Lineflyer** [comment]
> would it make sense to design a common map display module which can then be shared between cgeo and WhereYouGo? I have the impression this would help Whereyougo a lot, seem to be much less people involved over there

Theoretically a good idea. But it would require all WhereYouGo users to install c:geo, wouldn't it? And without c:geo WhereYouGo would have no map?
Maybe it is achievable to have a more or less identical implementation where both can be easily maintained by applying improvements likewise.

**Comment by eddiemuc** [comment]
> > would it make sense to design a common map display module which can then be shared between cgeo and WhereYouGo? I have the impression this would help Whereyougo a lot, seem to be much less people involved over there
> 
> Theoretically a good idea. But it would require all WhereYouGo users to install c:geo, wouldn't it? And without c:geo WhereYouGo would have no map?
> Maybe it is achievable to have a more or less identical implementation where both can be easily maintained by applying improvements likewise.

I meant a common code module, possibility even some sort of internal library, which is then used in both apps. So we have to maintain only one code base for both.
