### ISSUE TITLE
Avoid using html in translatable strings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9922]
We recently learned, that Crowdin does not automatically escape special chars if they are embedded into `[CDATA]` or similar tags.
See: https://github.com/cgeo/cgeo/pull/9866#issuecomment-770276140

Therefore I suggest to refrain from using HTML in strings unless there is no other way of formatting (instead of `<p>` we can easily use `\n` for separation).

Could somone convert the relevant strings from html to plain again?

**Comment by eddiemuc** [comment]
I used this for map attribution Dialogs to provide clickable links as well as basic formatting. Didn't find another way to do that yet. If this must be replaced, who knows a way to achieve same results using other means?

**Comment by Lineflyer** [comment]
Its not a must, but we should be aware about possible negative effects as just experienced (i.e. Crowdin does not handle special chars inside such elements AFAIK).
What is the map attribution dialog?

BTW: Things like `<a href=...` can be used without a problem in plain strings AFAICS from our existing strings (e.g. `string name="err_captcha"` and others).

**Comment by moving-bits** [comment]
The only `CDATA` section left in `strings.xml` is `<string name="debug_user_error_explain_options_html"><![CDATA[<p>Help us fixing c:geo problems by reporting them via email with system information and c:geo logfile included. Please do also include a detailed error description with your mail. Other contact options can be found at <i>About c:geo</i></p>]]></string>` - not sure if it's still needed there.

In `strings_not_translatable.xml` we have the map attributions, see above.

**Comment by moving-bits** [comment]
> What is the map attribution dialog?

Click on the copyright symbol in the lower left corner of an OSM offline map.

**Comment by fm-sys** [comment]
The strings which are left are there for several months. Therefore I would vote for not changing them, as that would mean a needed retranslation at crowdin...

**Comment by moving-bits** [comment]
Let's close here, if no one objects, as only one translatable string is affected. and that string is already translated in most languages.

If we do shall reformat it, feel free to reopen this issue.

**Comment by eddiemuc** [comment]
Those strings are all mine btw, and I promise never to use html in strings.xml again.

**Comment by moving-bits** [comment]
> Those strings are all mine btw, and I promise never to use html in strings.xml again.

;-)

I guess there may be situations where HTML is needed. We only should try to avoid CDATA sections in translatable strings.
