### ISSUE TITLE
Target SDK 30 (and use App bundle format) until November 2021

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9928]
New requirement schedule is out:

https://developer.android.com/distribute/best-practices/develop/target-sdk

https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

**Comment by Lineflyer** [comment]
FYI:
According to https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html
it is not mandatory for updates on existing apps to change from APK to AAB.

Not sure about possible benefits of AAB and the effort to change from APK to AAB, but this means we might decide to not change the deployment for now.

**Comment by moving-bits** [comment]
Reminder to the devs (needs to be checked in more detail yet):

There are some other changes that come with API level 30 - need to check whether they affect us, see https://developer.android.com/about/versions/11/behavior-changes-11
- Package visibility (we do check specific installed packages in several places)
- Declare interaction with TTS engines in manifest file
- APK Signature Scheme v2 now required
- maybe more?

**Comment by Lineflyer** [comment]
I guess we are done here:
- TargetSDK=30 is live
- App bundles not required for existing apps (we can stay with APK)
