### ISSUE TITLE
SAF: Handling of duplicate files

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9930]
While working on the MapDownloader I stumbled upon a surprising behavior: If a file (e. g. "berlin.map") already exists in the target folder, the new file does not overwrite the existing file (either silently or with some notification) but renames it to "berlin (1).map", which leads to duplicates in the map (or themes) folder.

The pre-SAF behavior was to notify the user beforehand and offer to rename the new or overwrite the existing file.

How can we restore that behavior?

**Comment by eddiemuc** [comment]
True, that's the implemented behaviour. I was not aware that this was different before, sorry for this.

In Scoped storage, when creating a new file and a file with same name already exists then another name is created underneath silently with unknown algorithm. To keep in control of this I made this routine explicit in code so we have a reliable name creation process for both file and document acces. It is the one you observed (with appended (1)).

It is easy to restore the behaviour you had before: one can use the `ContentStore.list` method before save to get current content and check whether a file with same name already exists. This can be slightly improved performance-wise by providing a method `ContentStore.fileExists(folder, name)` which internally only queries the file names (list queries some other information as well) and does the check inside the method.

There is no `exists` or `isFile` method in saf context like you might be used to from using `File` class.

**Comment by eddiemuc** [comment]
For overwriting an existing file, we can either `ContentStore.delete()` the old file first, then write the new one (my personal preferrence) or we can use `ContentStream.openForWrite(Uri, boolean)` on the Uri of the already existing file with `append` parameter set to `false`

**Comment by moving-bits** [comment]
ok, thanks for explaining. I'll dive into this.

**Comment by moving-bits** [comment]
@eddiemuc 

> For overwriting an existing file, we can either `ContentStore.delete()` the old file first, 

`ContentStorage.get().delete()` expects a Uri as parameter - how do I get that from PersistableFolder.XXX and filename?

**Comment by eddiemuc** [comment]
If you did a `contentstore.list` before, the uri is contained in the response for each file. I think this should be the easiest way

**Comment by moving-bits** [comment]
> If you did a `contentstore.list` before, the uri is contained in the response for each file. I think this should be the easiest way

Oh yes, you're right, thanks.

**Comment by moving-bits** [comment]
Added check for existing files as part of #9919, including handling of companion files (was missing before), including some obscure cases where downloadFile and companionFile are out of sync (because someone removed either the first or the second, but not both).

**Comment by moving-bits** [comment]
closed as part of #9919
