### ISSUE TITLE
old backups can no longer be restored

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9937]
Due to #9902 old backups can no longer be restored. The reason is that these backups don't have the extentionsDB upgrade.

Therefore, it fails with `E/SQLiteLog: (1) no such column: long3`. No crash, it simply happens nothing.

**Comment by moving-bits** [comment]
I'll look into it and provide a backward-compatible way for reading current values (at least as long as the extension itself does not need the new colums, which should be the case here).

**Comment by moving-bits** [comment]
Oh, I just see that you have assigned this to yourself. Ok, I'll stand back then.

My idea was to provide a compatibility `load` function in `DBExtension` which only reads long1/2 and string1/2 and ignores the new fields long3/4 and string3/4.

**Comment by fm-sys** [comment]
> My idea was to provide a compatibility `load` function in `DBExtension` which only reads long1/2 and string1/2 and ignores the new fields long3/4 and string3/4.

It was even way simpler than that. Just moving `load` function call into the if cause, a simple one liner.... See #9938

**Comment by moving-bits** [comment]
> It was even way simpler than that. Just moving `load` function call into the if cause, a simple one liner.... See #9938

Nice. And a good idea anyway, thinking of performance / avoiding unnecessary db access.
