### ISSUE TITLE
Integrate ZIP theme file renderer

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9939]
Just a small reminder for us:

In preparation for SAF @eddimuc created a theme file renderer for Mapsforge which handles ZIP files instead of XML + hundreds of separate resource files, to mitigate some performance issues SAF has with that.

This needs to be supported by c:geo as well, e. g.:
- allow ZIP files on file selection for theme files
- user either ZIP theme file renderer or regular XML theme renderer, depending on the selected file.

(and maybe more)

**Comment by eddiemuc** [comment]
Actually I created #9607 some time ago for this

**Comment by moving-bits** [comment]
Shame on me, didn't have this on my mind anymore, although I had posted in that thread. Too many items lately.. Closing this issue here then.
