### ISSUE TITLE
Remove Global type filter completely 

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#995]
I just read through all the issues related to filters, because the duplicate implementation of them is something I really don't like. We have
- global cache type filtering (directly in the main screen), just because the web site allows exactly this one type of filter up front.
- (several) filters in the lists, which are applied to the overall contents of the list. These filters are much more flexible, but currently we have only implemented some possible filters here.

In issue #135 we have already agreed that we should have the ability to apply multiple filters at the same time (e.g. difficulty < 3, traditional). The only way to implement this is in the lists, as the GC site doesn't allow these kinds of queries. And even if so, that wouldn't help for offline stored cache lists.

But if we implement a more advanced filtering in the lists, do we really need the global type filter at all? Just because it is available in the website doesn't mean we must use it too. I feel like that global filter should be removed completely. Because I see that it will confuse people if we implement more advanced local filters. You then have 2 places where you need to look if you start filtering on cache type (and those 2 filters may contradict each other).

Therefore my suggestion is the following:
- Remove all UI and settings related to the global type filter.
- When loading caches online and a (local) type filter is active, use the advanced search like before with the global filter (but let the app decide this, not the user via user interface).

I think that we would have the same functionality as before, are as efficient as before (i.e. we don't parse more web pages than necessary) and have less user confusion. Any comments from your side?

**Comment by eddiemuc** [comment]
This is a very long issue. Scanning through it I think that new filter framework addresses the issues discussed here for "local filters". However one aspect originally stated by @Bananeweizen remains: removal of global filter. I will close here and create a new issue for this citating him. I too would be in favor of removing global filter.

**Comment by eddiemuc** [comment]
See #10637
