### ISSUE TITLE
SAF: Map dir on extSD gets reset to default after device reboot

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9963]
Using 2021.02.01-NB-bfd9fbf

- Samsung S20, Android 11
- Set offline map directory to a folder on my real external SD 
- Offline maps can be used normally
- End c:geo
- Reboot device (Remark: As I use Android encryption of my external SD it take approx. 20-30 seconds after reboot until it is mounted and available)
- Start c:geo
- Toast is shown, that offline folder is no longer accessible and reset to default

The reason for this problem is obvious: I started c:geo before SD was initialized completely by the system.

But still its really annoying to have to set the folder permission again in such cases.

Could we postpone this check until the folder content is really needed, i.e. start the map activity?

**Comment by Lineflyer** [comment]
Now its no longer reproducible...need to do more testing. Setting unverified for now.

**Comment by eddiemuc** [comment]
A wild guess wrt the toast after reboot: maybe it was sent by c:geo before the reboot, then somehow "cached" in the Android system for display and then displayed after the reboot?

Wrt device checking: it seems that I haven't considered enough how "fragile" access to external directories really is. 
I can offer to leave out the fallback handling of "folder unavailablilty" completely, then function will simply fail if it needs access to dir and can't read/write it. Would that be an option?

**Comment by Lineflyer** [comment]
Rewritten the initial post after analyzing the problem.
Its in fact an understandable behavior, but IMHO it could be optimized.

**Comment by Lineflyer** [comment]
> I can offer to leave out the fallback handling of "folder unavailablilty" completely, then function will simply fail if it needs access to dir and can't read/write it. Would that be an option?

As edited in initial posting:

Couldn't we postpone the check until the point where something shall be read/written into it? 

BTW:
We cannot use the fallback anymore once we retire the legacy acces methods. Correct? So the fallback is no permanent solution anyway?!

**Comment by fm-sys** [comment]
> We cannot use the fallback anymore once we retire the legacy acces methods. Correct? So the fallback is no permanent solution anyway?!

Fallback means the corresponding subfolder in the cgeo base dir. As the user should have granted permission to this base folder, subfolders can be created/read also with SAF

**Comment by eddiemuc** [comment]
> > I can offer to leave out the fallback handling of "folder unavailablilty" completely, then function will simply fail if it needs access to dir and can't read/write it. Would that be an option?
> 
> As edited in initial posting:
> 
> Couldn't we postpone the check until the point where something shall be read/written from/to it? 

This would require handling for the case of non-availability at every place using the folders, but yes it can be done of course.


> BTW:
> We cannot use the fallback anymore once we retire the legacy acces methods. Correct? So the fallback is no permanent solution anyway?!

There are two different kind of fallbacks involved:
* every folder has a fallback default value which is checked at startup. In case of "base", it points to legacy folders and if this is not available to an internal app-private dir. All other folders default point to a subdirs of base. This fallback I would leave
* if folders are set to a user-defined dir already (which might be a legacy value if user has defined a folder in previous c:geo release before SAF), this is also checked for accessibility at startup, folder is switched back to default if not accessible. This check I would remove. The price is that user has to get active if folder he chose before is not accessible when needed.

**Comment by eddiemuc** [comment]
At least temporary inaccessibility of folder uris should be fixed by PR #9987
If folder is inaccessible then user has to get active in Settings.
