### ISSUE TITLE
SAF: desupport of user-defined Geocache Data Folder might be necessary

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9966]
While working on SAF Offline Log Image migration and searching for a way to create a new folder inside internal c:geo storage for the uncompressed images, I noticed that there are options in c:geo to move parts of the internal storage to external storage:
* database can be moved from internal to external storage (but only to the external storage predefined by Android system)
* directory "GeocacheData" can be moved from internal to a user-defined folder on SD-card

While I believe that the first option for moving database will work fine with SAF, I assume that the second one will not. This is because it deals again with a user-defined directory outside of Android system control and uses File interface to access it. Is there someone with an SD card who can try this out? 

I am not sure what the reason was to grant this much freedom to the user to choose his own directory when he assumingly just wants to move data to an external storage space so not to take away previous memory from internal storage. I believe if this is changed to a simple internal/external switch like with database it will still work. So what was the reason for the "much-freedom" decision, and is it an option to take that freedom away from the users?

Also, of course, we have another potential migration scenario here before us.

**Comment by moving-bits** [comment]
With SAF taking care of the access rights: Why not simply make it a sub folder of our base folder?

If someone has concerns regarding storage space, they can set the base folder to the SD card, otherwise it stays on builtin memory (but no longer in the reserved area). The folder could be named `cache` or `caches`.

**Comment by eddiemuc** [comment]
> With SAF taking care of the access rights: Why not simply make it a sub folder of our base folder?
> 
> If someone has concerns regarding storage space, they can set the base folder to the SD card, otherwise it stays on builtin memory (but no longer in the reserved area). The folder could be named `cache` or `caches`.

This would be a challenge on it's own, because then all code parts dealing with data from these folders need to be changed from using File interface to SAF/Uri/Inputstream interface. If I see it correctly it is this directory where all the html and cache listing images are stored, and Files are even passed into the Provider classes. This is not an easy task.

I would for now advise not to do that.

**Comment by Lineflyer** [comment]
> database can be moved from internal to external storage (but only to the external storage predefined by Android system)
> directory "GeocacheData" can be moved from internal to a user-defined folder on SD-card

Please have a look into the relevant wiki page, where these are described.
AFAIR we do not have a problem here:

1. The database is optionally moved into the apps one public storage /Android/data/cgeo.geocaching/*. AFAIK this is still possible even without any access rights.
2. For the Geocache data its similar. You cannot move it into a user defined directory but only move it between /Android/data/cgeo.geocaching/* directory on internal and external memory.

**Comment by Lineflyer** [comment]
See: https://github.com/cgeo/cgeo/wiki/Disk-usage-structure

**Comment by moving-bits** [comment]
But then the internal folder is the only option - The user would have no way to move that data to e. g. external SD card, as that would require SAF?

**Comment by Lineflyer** [comment]
really?
Isn't ˋContext.getExternalFilesDirs(null)[1+]ˋ still possible?

**Comment by Lineflyer** [comment]
According to https://developer.android.com/reference/android/content/Context#getExternalFilesDirs(java.lang.String) it is not depracated and 

> No additional permissions are required for the calling app to read or write files under the returned path. Write access outside of these paths on secondary external storage devices is not available.

**Comment by moving-bits** [comment]
ok, thanks for the pointer, I had remembered this wrong. 

So back to the original question: Then we could support an "internal / external" switch, and Android decides the exact location on internal resp. external memory. This solution would be fine for me, as this option is solely to overcome space restrictions on internal memory, AFAIK.

Question would be: How to migrate the data from user-selected path on external SD to "SAF"-auto-generated path on external SD?

**Comment by Lineflyer** [comment]
> Question would be: How to migrate the data from user-selected path on external SD to "SAF"-auto-generated path on external SD?

Maybe I am still to stupid to understand this issue, but IMHO there is absolutely no change needed here. It can continue to work without SAF as it does not rely on any (legacy) app permission, but uses the one and only option for apps to store its user related persistent files (removed on uninstall).

**Comment by eddiemuc** [comment]
> > Question would be: How to migrate the data from user-selected path on external SD to "SAF"-auto-generated path on external SD?
> 
> Maybe I am still to stupid to understand this issue, but IMHO there is absolutely no change needed here. It can continue to work without SAF as it does not rely on any (legacy) app permission, but uses the one and only option for apps to store its user related persistent files (removed on uninstall).

Ok, let me try to clear this up:

Android provides app-internal storage to each app. It provides basically two file paths, one pointing to internal storage, one to the primary external storage. Those work with Files, have nothing to do with SAF and will continue to work in SDK30. Context.getFilesDir returns the path to internal app-private storage, Context.gezExternalFilesDir() the path to external app-private storage. The database option switches between the two and should work fine with SDK30

But for GeocacheData there seems to be additionally the option to freely choose a file path on external storage. And this will.no longer work. This I fear needs to be desupported.

**Comment by eddiemuc** [comment]
See the two different options for database and GeocacheData in our Settings in the following screenshot:

![Screenshot_20210206-215635.jpg](https://user-images.githubusercontent.com/6909759/107129533-4c6da700-68c6-11eb-84bc-9e0ca56e99fe.jpg)

**Comment by Lineflyer** [comment]
For database you are correct, its either `Context.getFilesDir()` or `Context.getExternalFilesDir(null)` as options, whereas the first one is the default.

For Geocache Data there are usually also two options:
1. `Context.getExternalFilesDir(null)` -> internal memory (typically /Android/data/cgeo.geocaching/files)
2. `Context.getExternalFilesDirs(null)` -> other available (usually the external) memory (typically your external SD also using  /Android/data/cgeo.geocaching/files)
3. Usually two options, because method 2 might return more than one location (rare devices)

There is no user definable path here, just a selection between what is returned by the two methods explained above.
Looks like this:
![Screenshot_20210206-220901_cgeo](https://user-images.githubusercontent.com/949669/107129856-cc950c00-68c8-11eb-900c-77fd8486607b.jpg)

**Comment by Lineflyer** [comment]
Again, this is perfectly fine documented here :)
https://github.com/cgeo/cgeo/wiki/Disk-usage-structure#additional-data-for-caches

**Comment by eddiemuc** [comment]
Got it. Should work indeed. Thanks for the explanation. 

But why is there a different handling implented for database file (where you really can just check a checkbox or not) and GeocacheData (where you even see the internal file paths, which btw are not useful to the end user anyway because he can't access then anyway outside of c:geo)?

And where should I now put the offline log image dir? Should I open a third such selection option for this? This seems superflues.

**Comment by Lineflyer** [comment]
The difference between both is:
- The default for the DB is the real internal storage (no user access) and optional the (somehow) user accesible internal memory.
- For the DB we decided not to offer a removable storage intentionally.
- The default for the geocache data is the (somehow) user accesibe internal memory and the option to move it to an external memory (as these files can get rather huge in contrast to the DB)

For the offline log image I would go for what the user selected for his geocache data, as this is more or less the same kind of data stored and those also might consume storage space.

I assume those are removed after the log has been sent? So the only "danger" here is, that users might remove the storage while still having offline logs pending. If we want to avoid that, we should instead fixed use `Context.getExternalFilesDir(null)` .

**Comment by Lineflyer** [comment]
> which btw are not useful to the end user anyway because he can't access then anyway outside of c:geo)?

You can access them without a problem (at least for the time being even with Android 11) using a normal File Explorer.

**Comment by eddiemuc** [comment]
Ok. Let's keep things simple: I will create a new subfolder in GeocachData for the log images. That way the existing functionality for changing this folder (including an implicit move of the content) will be reused for log images too.

@Lineflyer log images are today not deleted after log was send. Check folder "Pictures/cgeo" and you should find all log images you ever send. I noticed this when Initially working on the multiple-images-per-log-thing many months ago and tried to discuss deleting them but to no avail. Anyway, I would indeed delete them once images are in internal storage.

Wrt the case of a removed SD card: imho we should draw a line here. If the user insists on storing his data on an external card but removes this card, then it is ok that the images are no longer there.

**Comment by eddiemuc** [comment]
I copied the last comment to #9806 where I think it belongs, and close this issue

**Comment by Lineflyer** [comment]
Thanks very much @eddiemuc for all your work around SAF implementation!!!
I have just also seen your huge contribution to mapsforge for supporting the zipped themes for scoped storage. Great!
