### ISSUE TITLE
Make user survey

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9976]
_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/7393#issuecomment-774066521_

I just stumbled across this (rather old and closed) issue and would like to voice one more idea. Not that it is in any way urgent but more for the sake of completeness: 
Instead of tracking user behavior (which I wouldn't support in any way), we could think about creating voluntary surveys for the usage of certain features. This doesn't even require changes to the source code. We would just need to post a message via c:geo's notification system linking to the survey.

**Comment by Lineflyer** [comment]
I like this idea of a survey and will take a look into some tools suitable for this.
Any recommendation for a aurvey tool/website we could make use of?

**Comment by fm-sys** [comment]
[Google Forms](https://www.google.de/intl/en/forms/about/) would be the simplest way. But I don't know if we want to make use of Google tools.

**Comment by fm-sys** [comment]
Or [surveymonkey](https://www.surveymonkey.com/) which even supports multilingual surveys...

https://www.surveymonkey.de/curiosity/in-5-einfachen-schritten-zur-mehrsprachigen-umfrage/

**Comment by Lineflyer** [comment]
> Or surveymonkey which even supports multilingual surveys...

**Comment by bekuno** [comment]
Or selfhosting a docker image like https://hub.docker.com/r/acspri/limesurvey

**Comment by Lineflyer** [comment]
Some thoughts about a possible survey (based also on my experience from different taken or created surveys):

- Better make several short surveys from time to time than a real long exhausting survey
- Use user defined answers/comments as less as possible (as these need manual evaluation and are difficult to categorize)
- Cover basic questions first, then evaluate and decide about the need and content of another dive-down survey for specific topics
- Ask for an overall rating and keep this question the same in subsequent surveys (to analyze changes)

I think we could start with getting some information about how people use c:geo (which functions are known and used).

**Comment by bekuno** [comment]
some tools:
https://www.getapp.com/p/sem/survey-software
https://www.capterra.com/sem-compare/survey-software

How about hotjar basic: https://www.hotjar.com/pricing/personal/

**Comment by Lineflyer** [comment]
I think as a first test if the users are willing to take such survey and to see if the results are meaningful, we good use Google.
AFAICS there is neither a login required nor does Google provide any personal data with the survey (just the results unless you configure it otherwise).

It could look like this (draft):
https://forms.gle/BxeTDNiNewepbU6y7

This would also be more or less the starting point for a basic survey. Feel free to suggest changes or additions.

Another limitation we should take into consideration:
Our notification system will keep displaying the info message although the user has taken the survey. This might be confusing but its still way more easy than implementing any kind of other means into the app itself.

**Comment by fm-sys** [comment]
> Another limitation we should take into consideration:
> Our notification system will keep displaying the info message although the user has taken the survey. This might be confusing but its still way more easy than implementing any kind of other means into the app itself.

Another way would be to implement some kind of onetime status notification for future c:geo versions (which hides after clicking on it). But we have to take care that a possible API change does not break anything for older c:geo versions...

Is there some kind of "API documentation" for our notification system and does every notification have some kind of unique ID?

**Comment by wolverine007** [comment]
Google Forms might be okay - tested the draft and it is looking fine for a first draw.

Found in the web Limesurvey, which must be installed on a web server, cause it is basing on php. Do we have a web server with such capabilities?
Or is anyone a student in a bigger university, cause I found working versions on bigger university web sites...

Cheers

**Comment by Lineflyer** [comment]
Thanks for testing the draft.
The answer analysis also looks fine to get an impression:

![grafik](https://user-images.githubusercontent.com/949669/108386996-78195700-720d-11eb-866b-f8c7ae1d4263.png)

**Comment by fm-sys** [comment]
We should also include some questions, with whose answers we can do something in the (near) future.

For example:
- Would users be interested in a redesign?
- Do they want to keep the dark themeing cgeo? 
- Do they want to keep the global cachetype filter or rather see the possibility to filter directly in the live map? 
- What information would users like to see directly on the start screen (nothing more - keep it like it is; live map snippet; recently opened; nearby caches)?

**Comment by Lineflyer** [comment]
I have removed the link to the survey for beta users of 2021.03.xx-RC meanwhile.
The latest results/answers are available through the link on the internal board. I will not publish them here as they contain free text comments (kind of personal data, while still anonymized).
