### ISSUE TITLE
SAF migration wizzard - what does the "Skip" Button mean?

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9977]
The migration wizzard starts with the info screen. 
On the lower left corner we have the button `skip`.
This is not understandable, there is no info what the result of this butten will be.

**Comment by moving-bits** [comment]
It skips the wizard completely.

**Comment by moving-bits** [comment]
@bekuno 
Ok? Or anything that needs to be done here?

**Comment by bekuno** [comment]
The question was from user side.
We need a description for this in the wizzard.

**Comment by fm-sys** [comment]
IMO there is no space for a description. we need to either find a different but _short_ wording, or need to leave it like it is. I would vote for leaving it, as it's a pretty common and known phrase...

**Comment by bekuno** [comment]
It is not clear what consequences are meant by this.
How about a message box after pressing the skip button with an information text?

**Comment by moving-bits** [comment]
You mean something like a confirmation dialog, e. g. "Do you really want to skip configuration? c:geo might not work as expected or may not work at all!"?

**Comment by Lineflyer** [comment]
Or append the meaning of Skip in the message shown for the wizard?

**Comment by fm-sys** [comment]
> Or append the meaning of Skip in the message shown for the wizard?

Please not. The longer a (information) text is, the less likely someone will read it.

**Comment by bekuno** [comment]
> 
> 
> You mean something like a confirmation dialog, e. g. "Do you really want to skip configuration? c:geo might not work as expected or may not work at all!"?

"Might not work" is not a useful term for the user side.
And the user maybe wants to know how long he can skip the procedure.

**Comment by eddiemuc** [comment]
What about "Remind me later" or "Not now" instead of "Skip"?

Optionally a dialog could be shown upon click with text "c:geo might not work as expected until configuration is completed. Whenever you feel ready to finalize setup, either choose "Configuration wizard" in main menu or restart c:geo."

**Comment by moving-bits** [comment]
> What about "Remind me later" or "Not now" instead of "Skip"?
> 
> Optionally a dialog could be shown upon click with text "c:geo might not work as expected until configuration is completed. Whenever you feel ready to finalize setup, either choose "Configuration wizard" in main menu or restart c:geo."

LGTM.

To help the user with the "might not work as expected" one could add a short explanation, e. g. "Depending on the missing configuration c:geo might not be able to show your position on the map and/or read/store data like offline maps, geocaches, logfiles etc."

I'll create a PR for it.

**Comment by Lineflyer** [comment]
"Not now" sound best to me instead of "Skip"
