### ISSUE TITLE
Add Map rotation for mapsforge maps

### ISSUE THREAD

**Issue by MakiWolf** [cgeo/cgeo#9986]
It would be great when the app also supports map oriantation on Live Map

- compass direction
- Movement direction
- No rotation (north always upwards)

**Comment by Lineflyer** [comment]
Its already supported when using Google Maps in cgeo.

**Comment by Lineflyer** [comment]
It seems however we do not yet have an issue to investigate such feature on mapsforge based maps. At least I was unable to find it.

**Comment by moving-bits** [comment]
If someone wants to dive into this, have a look at https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/RotateMapViewer.java as a possible starting point

**Comment by moving-bits** [comment]
This won't be implemented for our current OSM maps anymore. We have started working on a so-called "unified map", which unifies behavior (and implementation details) as much as possible between the supported tile providers. Unified map also supports map rotation for both Google Maps and OSM maps. This is a rather large task and may take another year or so, though, although a basic implementation can already be seen in c:geo when activated. See https://github.com/cgeo/cgeo/projects/25 for implementation progress.
